### PR TITLE
Try improve performance of index analisys with monotonic functions

### PR DESCRIPTION
**Pull request by CurtizJ**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Performance Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Improved performance of index analisys with monotonic functions.

### CODE REVIEW

**Comment by qoega** [comment]
Current cache implementation is unbounded?

**Comment by alexey-milovidov** [comment]
If it's per query, you should not worry. Only logarithmic amount of marks are touched, it should never be a big number.

**Comment by CurtizJ** [comment]
Also cache resets on every part.

**Comment by CurtizJ** [comment]
Closed in favor to #10026.

**Pull request closed without merging**
