### PR TITLE
Move non gtest unit tests to /examples folder

### PR DESCRIPTION
**Pull request by nikitamikhaylov**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):

- Not for changelog (changelog entry is not required)

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Detailed description / Documentation draft:

When I accidentally built ClickHouse with option `ENABLE_TESTS` the size of my build directory was suddenly increased. This is why that happened:
```bash
 --- /home/jakalletti/ClickHouse/build/memory/src/Interpreters/tests ---
                         /..
    1.3 GiB [          ] hash_map
    1.3 GiB [          ] in_join_subqueries_preprocessor
    1.3 GiB [          ] hash_map_string_3
    1.3 GiB [          ] hash_map_string_2
    1.3 GiB [          ] hash_map_string
    1.3 GiB [          ] string_hash_map
    1.3 GiB [          ] string_hash_map_aggregation
    1.3 GiB [          ] string_hash_set
    1.3 GiB [          ] hash_map_string_small
    1.3 GiB [          ] two_level_hash_map
    1.3 GiB [          ] hash_map_lookup
   37.9 MiB [          ] internal_iotop
   37.8 MiB [          ] hash_map3
   23.1 MiB [          ] /CMakeFiles
    4.0 KiB [          ] cmake_install.cmake
    4.0 KiB [          ] CTestTestfile.cmake

```

CC @alexey-milovidov

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
Actually these are not tests, but examples.
These examples are used in presentations and conversations, and I'm afraid deleting all of them.

Let's:
- add `examples` directory near `tests`;
- move these programs there;
- add `ENABLE_EXAMPLES` option in CMake, disabled by default.

**Comment by alexey-milovidov** [comment]
> internal_iotop
> in_join_subqueries_preprocessor

These are unneeded.

**Comment by nikitamikhaylov** [comment]
Ok.

**Comment by alexey-milovidov** [comment]
But I don't see the option in CMakeLists.txt

**Pull request merged**
