### PR TITLE
Fix remote constants.

### PR DESCRIPTION
**Pull request by KochetovNicolai**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Bug Fix

Changelog entry (up to few sentences, not needed for non-significant PRs):
Fix possible incorrect result for constant functions from remote servers. It happened for queries with functions like `version()`, `uptime()`, etc. which returns different constant values for different servers. #7666

Detailed description (optional):
Get constant values from remote source in RemoteBlockInputStream.

### CODE REVIEW

**Comment by KochetovNicolai** [comment]
Do not know how to create a good simple test.

**Comment by akuzm** [comment]
Is this related to https://github.com/ClickHouse/ClickHouse/pull/7247 , e.g. should we prevent pushing down non-deterministic functions to remote server?

**Comment by KochetovNicolai** [comment]
@akuzm I think it is strange to use functions like `uptime()` and `version()` in mutations indeed. Result also won't be deterministic. Probably we need another `may-be-not-deterministic-on-different-replicas` flag?

**Comment by akuzm** [comment]
uptime is already marked as non-deterministic, while version is deterministic. Maybe we should mark it as deterministic in scope of query, and only ship deterministic functions to replicas.

**Comment by KochetovNicolai** [comment]
Yes, it seems reasonable.

**Pull request merged**
