### PR TITLE
Don't throw on external engines creation in DatabaseReplicated

### PR DESCRIPTION
**Pull request by Avogar**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Let's see if it will break something

### CODE REVIEW

**Comment by robot-clickhouse** [comment]
*This is an automated comment for commit 10fecd54e0e0979b60d93c88d4d251ebab72f99f with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/59353/10fecd54e0e0979b60d93c88d4d251ebab72f99f/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/59353/10fecd54e0e0979b60d93c88d4d251ebab72f99f/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Comment by Avogar** [comment]
@tavplubix First I simply tried to set flag `attach=true` in `DatabaseReplicated`, but tests were failing and I couldn't figure out how to fix them (probably using attach has fundamental issues). So, I decided to just add one more flag to `ASTCreateQuery` that will indicate that it's create query from DatabaseReplicated during recovery of lost replica, so this flag can be used in external engines to avoid throwing exceptions.

What do you think about this approach, will it be enough or we should do something else?

**Comment by tavplubix** [comment]
> probably using attach has fundamental issues

Yep

> I decided to just add one more flag to ASTCreateQuery that will indicate that it's create query from DatabaseReplicated during recovery of lost replica, so this flag can be used in external engines to avoid throwing exceptions.

Yes, we need another stage, smth betwwen CREATE and ATTACH that creates some dirs/files/znodes (that's why tests fail when you just use "attach"), but skips sanity checks to avoid exceptions

Please review https://github.com/ClickHouse/ClickHouse/pull/60159 (although, it's not finished, because a fundamental bug was introduced in https://github.com/ClickHouse/ClickHouse/pull/50000, and it cannot be fixed by `SECONDARY_CREATE`)

**Comment by Avogar** [comment]
> because a fundamental bug was introduced in https://github.com/ClickHouse/ClickHouse/pull/50000

Ah, I think I got what the problem is. DDL entry in ZK can contain `CREATE` query without structure and it means that we will try to infer it from the data, even if we already did it on other replicas. But if external smth is not available, it won't be able to create table without the structure. The problem not in the attached PR, it can happend with all engines that supports schema inference, like S3 table engine (blob with the data could be deleted before new replica will execute `CREATE` table).

And yes, it is fundumental issue. Can we first execute `CREATE` query in the replica that received the query and than add structure to the `CREATE` query before creating DDL entry in ZK?

**Comment by Avogar** [comment]
And I just realized that https://github.com/ClickHouse/ClickHouse/pull/59092 introduced another bug as now the data format  can be detected automatically during table creation...
But it is easy to fix, if structure is known, format detection can be postponed to the first read from the storage, I will add it

**Comment by tavplubix** [comment]
> DDL entry in ZK can contain CREATE query without structure and it means that we will try to infer it from the data

It's much worse: table's metadata (both in ZK and on local disk) doesn't contain the list of columns, so if external smth is not available, the server will fail to start.

4 years ago, we had exactly the same issue with `CREATE TABLE AS table_function()` query, see https://github.com/ClickHouse/ClickHouse/pull/14295

We must normalize the CREATE statement before writing it to metadata, like here: https://github.com/ClickHouse/ClickHouse/blob/3526d7982c8cb93715e7d4878d3b81bf0f9e884b/src/Interpreters/InterpreterCreateQuery.cpp#L834-L839

> Can we first execute CREATE query in the replica that received the query and than add structure to the CREATE query before creating DDL entry in ZK?

This is tricky because we create a DDL entry in the very beginning of the query execution (although we still can try to infer the schema at this stage). But it's unlikely that the external source will become unavailable during the query execution. 

> or on each replicas before executing create query we can check if we already have structure of this table in database betadata in ZK and take it from there

It might be a good solution, but imagine we have a very stale replica, and other replicas have already dropped the table and created another table with the same name.

**Comment by tavplubix** [comment]
It's funny that the fix will be backward incompatible, because users may expect that the schema will be eventually updated in ClickHouse after it's updated in external source...

We could automatically update and rewrite the metadata on server startup, but it's not clear how to make it work with Replicated databases

**Comment by Avogar** [comment]
> It's much worse: table's metadata (both in ZK and on local disk) doesn't contain the list of columns, so if external smth is not available, the server will fail to start.

That might be not true, I just tested locally with 3 replicas and create query:
```sql
create table repl.s3 engine=S3('http://localhost:11111/test/data1.jsonl')
```

Metadata in ZK:
```sql
:) select * from system.zookeeper where path = '/clickhouse/repl/metadata' \G

SELECT *
FROM system.zookeeper
WHERE path = '/clickhouse/repl/metadata'

Query id: 1b260ef5-212c-4bb5-a167-62cc9ee06988

Row 1:
──────
name:  s3_2
value: ATTACH TABLE _ UUID 'aa3cb7ba-9aa2-41cb-8c74-2ef238054255'
(
    `number` Nullable(String)
)
ENGINE = S3('http://localhost:11111/test/data2.jsonl')

path:  /clickhouse/repl/metadata
```

Local metadata:
```sql
/server/metadata/repl$ cat s3.sql
ATTACH TABLE _ UUID 'ffe72ce2-1ca4-42b6-870e-1e02853facd3'
(
    `number` Nullable(String)
)
ENGINE = S3('http://localhost:11111/test/data1.jsonl')
```

Or you meant something different?

**Comment by tavplubix** [comment]
Hm, no, I meant this, but I haven't checked this, I just searched for `getTableStructureFromData` in `InterpreterCreateQuery` and didn't find it, looks like it's called only in constructors of storages, but probably I missed something... Where does it add columns to the AST?

**Comment by Avogar** [comment]
>  Also, why uuids are different in local metadata and in zk?

Just bad copy-paste, I had 2 tables and copied wrong query first, edited table name but forgot to edit uuid

**Comment by Avogar** [comment]
> Where does it add columns to the AST?

See `addColumnsDescriptionToCreateQueryIfNecessary` in `InterpreterCreateQuery `

**Comment by tavplubix** [comment]
> > Where does it add columns to the AST?
> 
> See `addColumnsDescriptionToCreateQueryIfNecessary` in `InterpreterCreateQuery `

Yes, that's what I missed, thanks. I was wondering why we don't add columns in `InterpreterCreateQuery::getTablePropertiesAndNormalizeCreateQuery`, but I found the answer: https://github.com/ClickHouse/ClickHouse/pull/34684#discussion_r809913277

However, I don't remember why we need to do it after storage creation; looks like in many cases, we could just call static `getTableStructureFromData` without a StoragePtr (although it would require adding it to StorageFactory), but I guess there are some tricky engines that require something more complex

Having that would allow us to easily get the list of columns in the early stage of query execution (before writing it to zk)

But I'm not sure if it's worth it

**Comment by Avogar** [comment]
> Having that would allow us to easily get the list of columns in the early stage of query execution (before writing it to zk)
But I'm not sure if it's worth it

Actually, it won't be difficult and in most cases should work quite well. Only disadvantages I see - in some engines in this case we will make the same work twice, for example, in Iceberg and other delta lake storages we parse metadata in the constructor and use structure from it, and if we will infer schema before rable creation, we will parse the same metadata twice. Similar problem with S3 engine when we need to infer both structure and data format, in this case we will read data twice (but this case can be considered as rare).

Maybe we can agree to have this disadvantage for replicated database and implement it

**Pull request closed without merging**
