### PR TITLE
Simplier isLocalAddress

### LINKED ISSUE #22080: Client alert: [DB::Exception: I/O error: 19]
when entering ck client , it alert 
```
Beling :) Cannot load data for command line suggestions: Code: 1000, e.displayText() = DB::Exception: Received from localhost:9123. DB::Exception: I/O error: 19. (version 21.2.4.6 (official build))
```

and it couldn't query cluster information , neither
```SELECT *
FROM system.clusters

Query id: f2a7867b-c4d8-4073-978d-588077d0ae6f


0 rows in set. Elapsed: 0.024 sec. 

Received exception from server (version 21.2.4):
Code: 1000. DB::Exception: Received from localhost:9123. DB::Exception: I/O error: 19. `
```

I set tcp port at 9123 and  use lsof -i :9123 to inspect, found nothing strange

`COMMAND     PID       USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
clickhous 11189 clickhouse  306u  IPv6 104707      0t0  TCP *:grcp (LISTEN)
`

### PR DESCRIPTION
**Pull request by alesapin**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Fixes https://github.com/ClickHouse/ClickHouse/issues/22080

### CODE REVIEW

**Comment by alesapin** [comment]
Not sure 100%, I hope we have tests for it.

**Comment by alesapin** [comment]
```2021-05-17 21:19:52 00163_column_oriented_formats:                                          Received exception from server (version 21.6.1):
2021-05-17 21:19:52 Code: 999. DB::Exception: Received from localhost:9000. DB::Exception: Connection loss, path: /clickhouse/task_queue/ddl/query-0000000002/finished. ```
Why this error is not retried.... We have such message in retry list.

**Comment by alesapin** [comment]
Again nothing for 7 seconds 2021.05.17 21:19:44.643057 [ 608 ] {} <Trace> RaftInstance: quorum idx 1, 155 155 155 
2021.05.17 21:19:44.643065 [ 608 ] {} <Trace> RaftInstance: local log idx 155, target_commit_idx 155, quick_commit_index_ 155, state_->get_commit_idx() 155
2021.05.17 21:19:45.642596 [ 604 ] {} <Debug> RaftInstance: heartbeat timeout for 3
2021.05.17 21:19:52.909313 [ 604 ] {} <Trace> RaftInstance: (update) new target priority: 3
2021.05.17 21:19:52.909332 [ 604 ] {} <Trace> RaftInstance: send request to 3
2021.05.17 21:19:52.909356 [ 604 ] {} <Trace> RaftInstance: last_log_idx: 155, starting_idx: 1, cur_nxt_idx: 156
2021.05.17 21:19:52.909370 [ 604 ] {} <Debug> RaftInstance: append_entries for 3 with LastLogIndex=155, LastLogTerm=1, EntriesLength=0, CommitIndex=155, Term=1, peer_last_sent_idx 156
2021.05.17 21:19:52.909379 [ 604 ] {} <Trace> RaftInstance: EMPTY PAYLOAD
2021.05.17 21:19:52.909389 [ 604 ] {} <Trace> RaftInstance: send req 1 -> 3, type append_entries_request
2021.05.17 21:19:52.909464 [ 604 ] {} <Trace> RaftInstance: sent
```
Again absolutely dead disk on test machine :(

**Comment by filimonov** [comment]
while you are here - what do you think of https://github.com/ClickHouse/ClickHouse/issues/23504 ?

**Comment by alesapin** [comment]
> ```
> 2021-05-17 21:19:52 00163_column_oriented_formats:                                          Received exception from server (version 21.6.1):
> 2021-05-17 21:19:52 Code: 999. DB::Exception: Received from localhost:9000. DB::Exception: Connection loss, path: /clickhouse/task_queue/ddl/query-0000000002/finished. 
> ```
> 
> Why this error is not retried.... We have such message in retry list.

that's why  https://github.com/ClickHouse/ClickHouse/pull/24249

**Comment by alesapin** [comment]
> while you are here - what do you think of #23504 ?

 I don't mind it, but not in this PR

**Pull request merged**
