### PR TITLE
Maybe improve server latency

### PR DESCRIPTION
**Pull request by alexey-milovidov**
Changelog category (leave one):
- Performance Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Slightly improve server latency by removing access to configuration on every connection.

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
> AST fuzzer (UBSan) — ../src/Functions/FunctionDateOrDateTimeAddInterval.h:141:18: runtime error: signed integer overflow: 47764 + 9223372036854775807 cannot be r

#19859

**Comment by alexey-milovidov** [comment]
This PR is ready but blocked by Arcadia :(

**Comment by alexey-milovidov** [comment]
I have fixed Arcadia, waiting for checks...

**Review by alesapin — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
Arcadia did not publish the results. Here they are:

Screenshot_20210201_102652

**Pull request merged**
