### PR TITLE
See impact of DISABLE_OMIT_FRAME_POINTER

### PR DESCRIPTION
**Pull request by Algunenano**
### Changelog category (leave one):
- Performance Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
- Enable frame pointers by default. 

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by robot-ch-test-poll2** [comment]
*This is an automated comment for commit 065f65cdb8cad22765ed6869df634b099b435911 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/58529/065f65cdb8cad22765ed6869df634b099b435911/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/58529/065f65cdb8cad22765ed6869df634b099b435911/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Comment by Algunenano** [comment]
image

God dammit

**Comment by Algunenano** [comment]
https://github.com/ClickHouse/ClickHouse/pull/14685

> "The "worst" code I've ever written."

😄

**Comment by Algunenano** [comment]
Many test with 1.05-1.20 (worse) performance, which confirms what I suspected. I don't think it's worth enabling by default.

**Pull request closed without merging**
