### PR TITLE
Added part_log with statistics scripts

### PR DESCRIPTION
**Pull request by Ravengg**

### CODE REVIEW

**Comment by robot-metrika-test** [comment]
Can one of the admins verify this patch?

**Comment by alexey-milovidov** [comment]
autotests

**Comment by robot-metrika-test** [comment]
Can one of the admins verify this patch?

**Comment by robot-metrika-test** [comment]
Can one of the admins verify this patch?

**Comment by alexey-milovidov** [comment]
autotests

**Comment by alexey-milovidov** [comment]
autotests

**Pull request merged**
