### PR TITLE
remove endless waits from ZK and add more logs

### PR DESCRIPTION
**Pull request by akuzm**
Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
Need to check `test_keeper_multinode_blocade_leader`.

**Comment by akuzm** [comment]
```
2021.04.16 17:29:13.977463 [ 12 ] {} <Trace> BaseDaemon: Received signal 6
2021.04.16 17:29:13.977833 [ 97 ] {} <Fatal> BaseDaemon: ########################################
2021.04.16 17:29:13.977924 [ 97 ] {} <Fatal> BaseDaemon: (version 21.5.1.6585, build id: BCD0BD860E821B1B7A6A1312B4005390B483BE90) (from thread 93) (no query) Received signal Aborted (6)
2021.04.16 17:29:13.977980 [ 97 ] {} <Fatal> BaseDaemon: 
2021.04.16 17:29:13.978070 [ 97 ] {} <Fatal> BaseDaemon: Stack trace: 0x7f8b112f918b 0x7f8b112d8859 0x7f8b112d8729 0x7f8b112e9f36 0x7f8b114b0ed9 0xaf087b6 0xad7c5d3 0x218d19f2 0x21929e4d 0x2193611c 0x21942f93 0xae9bb2c 0xaea47d4 0x7f8b114ae609 0x7f8b113d5293
2021.04.16 17:29:13.978209 [ 97 ] {} <Fatal> BaseDaemon: 3. gsignal @ 0x4618b in /usr/lib/x86_64-linux-gnu/libc-2.31.so
2021.04.16 17:29:13.978266 [ 97 ] {} <Fatal> BaseDaemon: 4. abort @ 0x25859 in /usr/lib/x86_64-linux-gnu/libc-2.31.so
2021.04.16 17:29:13.978314 [ 97 ] {} <Fatal> BaseDaemon: 5. ? @ 0x25729 in /usr/lib/x86_64-linux-gnu/libc-2.31.so
2021.04.16 17:29:13.978348 [ 97 ] {} <Fatal> BaseDaemon: 6. ? @ 0x36f36 in /usr/lib/x86_64-linux-gnu/libc-2.31.so
2021.04.16 17:29:13.978393 [ 97 ] {} <Fatal> BaseDaemon: 7. __pthread_mutex_lock_full @ 0xbed9 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
2021.04.16 17:29:13.992946 [ 97 ] {} <Fatal> BaseDaemon: 8. ./obj-x86_64-linux-gnu/../src/Common/ThreadFuzzer.cpp:0: pthread_mutex_lock @ 0xaf087b6 in /usr/bin/clickhouse
2021.04.16 17:29:13.996988 [ 12 ] {} <Trace> BaseDaemon: Received signal 11
2021.04.16 17:29:13.997343 [ 98 ] {} <Fatal> BaseDaemon: ########################################
2021.04.16 17:29:13.997433 [ 98 ] {} <Fatal> BaseDaemon: (version 21.5.1.6585, build id: BCD0BD860E821B1B7A6A1312B4005390B483BE90) (from thread 69) (no query) Received signal Segmentation fault (11)
2021.04.16 17:29:13.997527 [ 98 ] {} <Fatal> BaseDaemon: Address: 0x1000001f4 Access: read. Attempted access has violated the permissions assigned to the memory area.
2021.04.16 17:29:13.997619 [ 98 ] {} <Fatal> BaseDaemon: Stack trace: 0xadc82e5 0xadc886a 0xae0ed64 0xae0ce87 0x20481d01 0x1e9d05e3 0x1e9d4ce5 0x1e9d5f53 0xae9bb2c 0xaea47d4 0x7f8b114ae609 0x7f8b113d5293
2021.04.16 17:29:14.036978 [ 98 ] {} <Fatal> BaseDaemon: 3. ./obj-x86_64-linux-gnu/../src/Common/StackTrace.cpp:406: toStringImpl(std::__1::array<void*, 32ul> const&, unsigned long, unsigned long) @ 0xadc82e5 in /usr/bin/clickhouse
2021.04.16 17:29:14.078144 [ 98 ] {} <Fatal> BaseDaemon: 4.1. inlined from ./obj-x86_64-linux-gnu/../contrib/libcxx/include/__mutex_base:91: lock_guard
2021.04.16 17:29:14.078341 [ 98 ] {} <Fatal> BaseDaemon: 4.2. inlined from ../base/common/../common/SimpleCache.h:49: std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > SimpleCache<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > (std::__1::array<void*, 32ul> const&, unsigned long, unsigned long), &(toStringImpl(std::__1::array<void*, 32ul> const&, unsigned long, unsigned long))>::operator()<std::__1::array<void*, 32ul>&, unsigned long&, unsigned long&>(std::__1::array<void*, 32ul>&, unsigned long&, unsigned long&)
2021.04.16 17:29:14.078402 [ 98 ] {} <Fatal> BaseDaemon: 4. ../src/Common/StackTrace.cpp:432: StackTrace::toString(void**, unsigned long, unsigned long) @ 0xadc886a in /usr/bin/clickhouse
2021.04.16 17:29:14.163940 [ 98 ] {} <Fatal> BaseDaemon: 5.1. inlined from ./obj-x86_64-linux-gnu/../contrib/libcxx/include/string:4305: std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > std::__1::operator+<char, std::__1::char_traits<char>, std::__1::allocator<char> >(char const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&)
2021.04.16 17:29:14.177040 [ 98 ] {} <Fatal> BaseDaemon: 5. ../src/Common/Exception.cpp:312: DB::getCurrentExceptionMessage(bool, bool, bool) @ 0xae0ed64 in /usr/bin/clickhouse
2021.04.16 17:29:14.259274 [ 98 ] {} <Fatal> BaseDaemon: 6. ./obj-x86_64-linux-gnu/../src/Common/Exception.cpp:0: DB::tryLogCurrentException(Poco::Logger*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0xae0ce87 in /usr/bin/clickhouse
2021.04.16 17:29:14.339179 [ 97 ] {} <Fatal> BaseDaemon: 9. ./obj-x86_64-linux-gnu/../contrib/poco/Foundation/include/Poco/Event_POSIX.h:53: Poco::EventImpl::setImpl() @ 0xad7c5d3 in /usr/bin/clickhouse
2021.04.16 17:29:14.462904 [ 97 ] {} <Fatal> BaseDaemon: 10. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/functional:2090: void std::__1::__function::__policy_invoker<void (Coordination::ListResponse const&)>::__call_impl<std::__1::__function::__default_alloc_func<zkutil::ZooKeeper::getChildrenImpl(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >&, Coordination::Stat*, std::__1::function<void (Coordination::WatchResponse const&)>)::$_10, void (Coordination::ListResponse const&)> >(std::__1::__function::__policy_storage const*, Coordination::ListResponse const&) @ 0x218d19f2 in /usr/bin/clickhouse
2021.04.16 17:29:14.569559 [ 97 ] {} <Fatal> BaseDaemon: 11.1. inlined from ./obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:3211: ~shared_ptr
2021.04.16 17:29:14.569611 [ 97 ] {} <Fatal> BaseDaemon: 11. ../src/Common/ZooKeeper/ZooKeeperImpl.cpp:899: Coordination::ZooKeeper::finalize(bool, bool) @ 0x21929e4d in /usr/bin/clickhouse
2021.04.16 17:29:14.686804 [ 97 ] {} <Fatal> BaseDaemon: 12. ./obj-x86_64-linux-gnu/../src/Common/ZooKeeper/ZooKeeperImpl.cpp:663: Coordination::ZooKeeper::receiveThread() @ 0x2193611c in /usr/bin/clickhouse
2021.04.16 17:29:14.827290 [ 97 ] {} <Fatal> BaseDaemon: 13.1. inlined from ./obj-x86_64-linux-gnu/../src/Common/ThreadPool.h:179: operator()
2021.04.16 17:29:14.827434 [ 97 ] {} <Fatal> BaseDaemon: 13.2. inlined from ../contrib/libcxx/include/type_traits:3676: decltype(std::__1::forward<Coordination::ZooKeeper::ZooKeeper(std::__1::vector<Coordination::ZooKeeper::Node, std::__1::allocator<Coordination::ZooKeeper::Node> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Poco::Timespan, Poco::Timespan, Poco::Timespan)::$_1>(fp)()) std::__1::__invoke<ThreadFromGlobalPool::ThreadFromGlobalPool<Coordination::ZooKeeper::ZooKeeper(std::__1::vector<Coordination::ZooKeeper::Node, std::__1::allocator<Coordination::ZooKeeper::Node> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Poco::Timespan, Poco::Timespan, Poco::Timespan)::$_1>(Coordination::ZooKeeper::ZooKeeper(std::__1::vector<Coordination::ZooKeeper::Node, std::__1::allocator<Coordination::ZooKeeper::Node> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Poco::Timespan, Poco::Timespan, Poco::Timespan)::$_1&&)::'lambda'()&>(Coordination::ZooKeeper::ZooKeeper(std::__1::vector<Coordination::ZooKeeper::Node, std::__1::allocator<Coordination::ZooKeeper::Node> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Poco::Timespan, Poco::Timespan, Poco::Timespan)::$_1&&)
2021.04.16 17:29:14.827661 [ 97 ] {} <Fatal> BaseDaemon: 13.3. inlined from ../contrib/libcxx/include/__functional_base:348: void std::__1::__invoke_void_return_wrapper<void>::__call<ThreadFromGlobalPool::ThreadFromGlobalPool<Coordination::ZooKeeper::ZooKeeper(std::__1::vector<Coordination::ZooKeeper::Node, std::__1::allocator<Coordination::ZooKeeper::Node> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Poco::Timespan, Poco::Timespan, Poco::Timespan)::$_1>(Coordination::ZooKeeper::ZooKeeper(std::__1::vector<Coordination::ZooKeeper::Node, std::__1::allocator<Coordination::ZooKeeper::Node> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Poco::Timespan, Poco::Timespan, Poco::Timespan)::$_1&&)::'lambda'()&>(Coordination::ZooKeeper::ZooKeeper(std::__1::vector<Coordination::ZooKeeper::Node, std::__1::allocator<Coordination::ZooKeeper::Node> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Poco::Timespan, Poco::Timespan, Poco::Timespan)::$_1&&...)
2021.04.16 17:29:14.827787 [ 97 ] {} <Fatal> BaseDaemon: 13.4. inlined from ../contrib/libcxx/include/functional:1608: std::__1::__function::__default_alloc_func<ThreadFromGlobalPool::ThreadFromGlobalPool<Coordination::ZooKeeper::ZooKeeper(std::__1::vector<Coordination::ZooKeeper::Node, std::__1::allocator<Coordination::ZooKeeper::Node> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Poco::Timespan, Poco::Timespan, Poco::Timespan)::$_1>(Coordination::ZooKeeper::ZooKeeper(std::__1::vector<Coordination::ZooKeeper::Node, std::__1::allocator<Coordination::ZooKeeper::Node> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Poco::Timespan, Poco::Timespan, Poco::Timespan)::$_1&&)::'lambda'(), void ()>::operator()()
2021.04.16 17:29:14.827875 [ 97 ] {} <Fatal> BaseDaemon: 13. ../contrib/libcxx/include/functional:2089: void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPool::ThreadFromGlobalPool<Coordination::ZooKeeper::ZooKeeper(std::__1::vector<Coordination::ZooKeeper::Node, std::__1::allocator<Coordination::ZooKeeper::Node> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Poco::Timespan, Poco::Timespan, Poco::Timespan)::$_1>(Coordination::ZooKeeper::ZooKeeper(std::__1::vector<Coordination::ZooKeeper::Node, std::__1::allocator<Coordination::ZooKeeper::Node> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Poco::Timespan, Poco::Timespan, Poco::Timespan)::$_1&&)::'lambda'(), void ()> >(std::__1::__function::__policy_storage const*) @ 0x21942f93 in /usr/bin/clickhouse
2021.04.16 17:29:14.866122 [ 97 ] {} <Fatal> BaseDaemon: 14. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/functional:0: ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xae9bb2c in /usr/bin/clickhouse
2021.04.16 17:29:14.909128 [ 97 ] {} <Fatal> BaseDaemon: 15.1. inlined from ./obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:1655: std::__1::unique_ptr<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda1'()>, std::__1::default_delete<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda1'()> > >::reset(std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda1'()>*)
2021.04.16 17:29:14.909186 [ 97 ] {} <Fatal> BaseDaemon: 15.2. inlined from ../contrib/libcxx/include/memory:1612: ~unique_ptr
2021.04.16 17:29:14.909237 [ 97 ] {} <Fatal> BaseDaemon: 15. ../contrib/libcxx/include/thread:293: void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda1'()> >(void*) @ 0xaea47d4 in /usr/bin/clickhouse
2021.04.16 17:29:14.909309 [ 97 ] {} <Fatal> BaseDaemon: 16. start_thread @ 0x9609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
2021.04.16 17:29:14.909368 [ 97 ] {} <Fatal> BaseDaemon: 17. __clone @ 0x122293 in /usr/lib/x86_64-linux-gnu/libc-2.31.so
2021.04.16 17:29:15.053519 [ 98 ] {} <Fatal> BaseDaemon: 7.1. inlined from ./obj-x86_64-linux-gnu/../contrib/libcxx/include/string:1444: std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::__is_long() const
2021.04.16 17:29:15.053583 [ 98 ] {} <Fatal> BaseDaemon: 7.2. inlined from ../contrib/libcxx/include/string:2218: ~basic_string
2021.04.16 17:29:15.053639 [ 98 ] {} <Fatal> BaseDaemon: 7. ../src/Storages/StorageReplicatedMergeTree.cpp:3038: DB::StorageReplicatedMergeTree::mergeSelectingTask() @ 0x20481d01 in /usr/bin/clickhouse
2021.04.16 17:29:15.087025 [ 98 ] {} <Fatal> BaseDaemon: 8. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/functional:0: DB::BackgroundSchedulePoolTaskInfo::execute() @ 0x1e9d05e3 in /usr/bin/clickhouse
2021.04.16 17:29:15.132240 [ 98 ] {} <Fatal> BaseDaemon: 9.1. inlined from ./obj-x86_64-linux-gnu/../contrib/poco/Foundation/include/Poco/AtomicCounter.h:314: Poco::AtomicCounter::operator--()
2021.04.16 17:29:15.132306 [ 98 ] {} <Fatal> BaseDaemon: 9.2. inlined from ../contrib/poco/Foundation/include/Poco/RefCountedObject.h:82: Poco::RefCountedObject::release() const
2021.04.16 17:29:15.132351 [ 98 ] {} <Fatal> BaseDaemon: 9.3. inlined from ../contrib/poco/Foundation/include/Poco/AutoPtr.h:90: ~AutoPtr
2021.04.16 17:29:15.132385 [ 98 ] {} <Fatal> BaseDaemon: 9. ../src/Core/BackgroundSchedulePool.cpp:262: DB::BackgroundSchedulePool::threadFunction() @ 0x1e9d4ce5 in /usr/bin/clickhouse
2021.04.16 17:29:15.179878 [ 98 ] {} <Fatal> BaseDaemon: 10.1. inlined from ./obj-x86_64-linux-gnu/../src/Common/ThreadPool.h:179: operator()
2021.04.16 17:29:15.179979 [ 98 ] {} <Fatal> BaseDaemon: 10.2. inlined from ../contrib/libcxx/include/type_traits:3676: decltype(std::__1::forward<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_1>(fp)()) std::__1::__invoke<ThreadFromGlobalPool::ThreadFromGlobalPool<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_1>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_1&&)::'lambda'()&>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_1&&)
2021.04.16 17:29:15.180056 [ 98 ] {} <Fatal> BaseDaemon: 10.3. inlined from ../contrib/libcxx/include/__functional_base:348: void std::__1::__invoke_void_return_wrapper<void>::__call<ThreadFromGlobalPool::ThreadFromGlobalPool<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_1>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_1&&)::'lambda'()&>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_1&&...)
2021.04.16 17:29:15.180129 [ 98 ] {} <Fatal> BaseDaemon: 10.4. inlined from ../contrib/libcxx/include/functional:1608: std::__1::__function::__default_alloc_func<ThreadFromGlobalPool::ThreadFromGlobalPool<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_1>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_1&&)::'lambda'(), void ()>::operator()()
2021.04.16 17:29:15.180193 [ 98 ] {} <Fatal> BaseDaemon: 10. ../contrib/libcxx/include/functional:2089: void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPool::ThreadFromGlobalPool<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_1>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_1&&)::'lambda'(), void ()> >(std::__1::__function::__policy_storage const*) @ 0x1e9d5f53 in /usr/bin/clickhouse
2021.04.16 17:29:15.217665 [ 98 ] {} <Fatal> BaseDaemon: 11. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/functional:0: ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xae9bb2c in /usr/bin/clickhouse
2021.04.16 17:29:15.260485 [ 98 ] {} <Fatal> BaseDaemon: 12.1. inlined from ./obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:1655: std::__1::unique_ptr<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda1'()>, std::__1::default_delete<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda1'()> > >::reset(std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda1'()>*)
2021.04.16 17:29:15.260619 [ 98 ] {} <Fatal> BaseDaemon: 12.2. inlined from ../contrib/libcxx/include/memory:1612: ~unique_ptr
2021.04.16 17:29:15.260662 [ 98 ] {} <Fatal> BaseDaemon: 12. ../contrib/libcxx/include/thread:293: void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda1'()> >(void*) @ 0xaea47d4 in /usr/bin/clickhouse
2021.04.16 17:29:15.260753 [ 98 ] {} <Fatal> BaseDaemon: 13. start_thread @ 0x9609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
2021.04.16 17:29:15.260818 [ 98 ] {} <Fatal> BaseDaemon: 14. __clone @ 0x122293 in /usr/lib/x86_64-linux-gnu/libc-2.31.so
```
what's going on...

**Comment by akuzm** [comment]
The `IKeeper` interface makes it impossible to avoid endless waits. Its methods take a callback by value and then call it later at an unspecified point of time. It is impossible to extract the return value from the callback, because the caller doesn't have access to the copy of callback object that is actually called by `IKeeper`. The only option is to keep in the callback object a mutable reference to caller-owned result storage, which we must then guarantee to be alive until the callback is called. There is also no way to deregister a callback, so we have to wait.

**Comment by akuzm** [comment]
Not sure how to proceed, I'll ask @alesapin for advice when he returns from vacation.

**Comment by akuzm** [comment]
We are finding other ways to debug the problem, see CLICKHOUSE-5042.

**Pull request closed without merging**
