### PR TITLE
cleaning duplicate linker flags

### PR DESCRIPTION
**Pull request by amosbird**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Build/Testing/Packaging Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Clean up duplicated linker flags. Make sure the linker won't look up an unexpected symbol.

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
For the reference: before this change, the linker command was inserting `-lpthread` in the middle of the list of libraries and we get dependency on C11 threads (symbols like `cnd_broadcast`) if we build with glibc 2.28+.

**Comment by amosbird** [comment]
> symbols like cnd_broadcast

which gets picked up by librdkafka

**Comment by alexey-milovidov** [comment]
> which gets picked up by librdkafka

- rdkafka is build without flag that enables C11 threads;
- it implements its own methods for C11 threads with identical names;
- but if `-lpthread` is before `-lrdkafka`, linker is leaving the dependency on C11 symbols from pthread (?)

**Comment by alexey-milovidov** [comment]
Performance test Ok.

**Pull request merged**
