### PR TITLE
Fix read old records from logs

### PR DESCRIPTION
**Pull request by alesapin**
Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Not in release, so no backports.

### CODE REVIEW

**Comment by alesapin** [comment]
@mergifyio update

**Review by Avogar — APPROVED** [review]

**Comment by Avogar** [comment]
@Mergifyio update

**Comment by alesapin** [comment]
@Mergifyio update

**Comment by alesapin** [comment]
Finally, no related failures.

**Pull request merged**
