### PR TITLE
Improve keeper failure injection and tolerance

### PR DESCRIPTION
**Pull request by Algunenano**
### Changelog category (leave one):
- Backward Incompatible Change

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
- Reworked tolerance to keeper failures
  * Deprecated `insert_keeper_*`, `backup_restore_keeper*`, `distributed_ddl_keeper_*` settings. They have been replaced by common settings (`keeper_max_retries`, `keeper_fault_injection_probability`...) that work in any (supported) operation.
  * Backups (ON CLUSTER): Fix reconnection after keeper failure
  * Insert/attach (replicated) parts: Made them more reliable to keeper failures. If the connection to keeper fails when pushing metadata, it will now be able to retry if the data wasn't written (before it would only continue if it was written).
  * Insert/attach (replicated) parts with quorum: The process can now recover from keeper failures when verifying the quorum.
  * CI: Increment the ratio of keeper failures (from 1% to 10%) to help catch more errors. Made them also retry faster so it don't affect timings too much.

### CODE REVIEW

**Comment by robot-ch-test-poll3** [comment]
*This is an automated comment for commit f2a73bb25cef091e763aa8114a5938575d45c100 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/56389/f2a73bb25cef091e763aa8114a5938575d45c100/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td><a href="https://github.com/ClickHouse/ClickHouse/actions/runs/6775035968">✅ success</a></td></tr>
<tbody>
</table>
</details>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/56389/f2a73bb25cef091e763aa8114a5938575d45c100/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Comment by Algunenano** [comment]
My philosophy behind this PR has become "given enough retries allowed, CH should be able to recover from any keeper HW error". It's going to be painful. I'll need to limit the scope to what's already there and then try to introduce retries on other parts as needed.

**Comment by jrdi** [comment]
So this PR is not about backups anymore, right? Happy to see the effort on improving ZK retries, thanks for this!

**Comment by Algunenano** [comment]
> So this PR is not about backups anymore, right?

No, it's still about backups, but backups do many different operations :D I want to investigate if there is a simpler way to introduce both keeper faults and retries in more places

**Comment by devcrafter** [comment]
> > So this PR is not about backups anymore, right?
> 
> No, it's still about backups, but backups do many different operations :D I want to investigate if there is a simpler way to introduce both keeper faults and retries in more places

I'd suggest doing it gradually, in general. But first need to look at the changes in more details.

**Comment by Algunenano** [comment]
> I'd suggest doing it gradually, in general. But first need to look at the changes in more details.

:+1: I'm starting by adding (always disabled) faults to ReplicatedMergeTree. It means using `ZooKeeperWithFaultInjection` instead of `Zookeeper` in lots of calls

**Comment by devcrafter** [comment]
@Algunenano imo, you're doing too much at once here. Items you list in the `Changelog entry` above can be done in separate PRs.

**Comment by Algunenano** [comment]
The tests should be green right now (there might be some that I've broken with more failures, but let's see). I'm pushing some extra changes to see what happens when we add faults also to async keeper requests and I'll start moving subset of changes into smaller PRs so it's easier to review and reason about.

**Comment by Algunenano** [comment]
Quorum handling moved to https://github.com/ClickHouse/ClickHouse/pull/57986. The only thing missing from this draft is the unification of settings to have only a single set of settings for zk faults and retries for all operations: now only backup and insert, but ideally more will be added.

**Pull request closed without merging**
