### PR TITLE
Replace `<yandex>` to `<clickhouse>` in configs and more.

### PR DESCRIPTION
**Pull request by alexey-milovidov**
Changelog category (leave one):
- Documentation (changelog entry is not required)

See https://clickhouse.com/blog/en/2021/clickhouse-inc/

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
@mergifyio update

**Comment by alexey-milovidov** [comment]
> Integration tests flaky check (asan) — Failed to read...

Timeout due to too many changed tests - Ok.

**Comment by alexey-milovidov** [comment]
> Performance — Failed to parse the report. 

Failed because of trying to run old version with new `config.d` files. Ok.

**Comment by alexey-milovidov** [comment]
AST fuzzer:

> CalledProcessError: Command 'docker pull clickhouse/fuzzer:29182-4ade6cc5da6ee881a2a92c59f55e3a98e2e87d12' returned non-zero exit status 1.

**Comment by alexey-milovidov** [comment]
@mergifyio update

**Comment by alesapin** [comment]
https://github.com/ClickHouse/ClickHouse/pull/29265

**Comment by alexey-milovidov** [comment]
@Mergifyio update

**Comment by alexey-milovidov** [comment]
@Mergifyio update

**Comment by alexey-milovidov** [comment]
@mergifyio update

**Comment by alexey-milovidov** [comment]
@mergifyio update

**Comment by alexey-milovidov** [comment]
@Mergifyio update

**Comment by alexey-milovidov** [comment]
One more step to get tests passing, please be patient...

**Pull request merged**
