### PR TITLE
basic Secrets

### PR DESCRIPTION
**Pull request by Enmk**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- New Feature

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
A new function `secret` for accessing secrets defined in the config file. The secret is always a string, and it can be defined either as plain text or hierarchical structure.
...

Detailed description / Documentation draft:
...

Phase 1 of https://github.com/ClickHouse/ClickHouse/pull/23424

### CODE REVIEW

**Comment by vdimir** [comment]
IMHO, `secret` sound like something that we don't want to show in query result. Maybe it can be considered as function, that allows to get predefined user values from config, but name a bit confusing.

**Comment by Enmk** [comment]
> IMHO, `secret` sounds like something that we don't want to show in query result. Maybe it can be considered as function, that allows to get predefined user values from config, but name a bit confusing.

Agree, but  right now IMO there is no way to hide anything from the query result, and any attempt to do so will eventually fail since there is always a more convoluted way to dump the secret somewhere:
```
-- e.g.
SELECT secret('foobar');
SELECT hex(secret('foobar'));
SELECT encrypt('aes-256-gcm', secret('foobar'), some_key, some_iv);
SELECT hex(encrypt('aes-256-gcm', secret('foobar'), some_key, some_iv));
SELECT concat('some prefix', hex(encrypt('aes-256-gcm', secret('foobar'), some_key, some_iv)));
```

So IMO name `secret` is a good indicator that users should be conscious about dumping the resulting value in any way.

Also, later on, we plan to implement more secrets backends, the next one in line is the server-key based (see https://github.com/ClickHouse/ClickHouse/pull/22423 for the basic idea). And even more, things like Hashicorp Vault or environment-based one (for accessing secrets manged by k8s from within pod) are also a good example of possible secret backends.

**Comment by filimonov** [comment]
Actually i was also thinking if introducing new datatype for secrets, which can not be serialized (or always serialialized to some dummy value), otherwise it's too easy to steal secrets.

**Comment by Enmk** [comment]
> IMHO, `secret` sounds like something that we don't want to show in query result. Maybe it can be considered as function, that allows to get predefined user values from config, but name a bit confusing.

Fixed, now value produced by `secret` function doesn't seriliaze in either binary or text form, also it is almost impossible to leak value as plaintest, except to exception messages, but there seems to be no general way to fix it.

**Comment by Enmk** [comment]
> Right now the only way to leak secret is through exception message, e.g.:
Fixed, secrets are no longer leaked through exception messages

**Comment by alexey-milovidov** [comment]
We started to review the implementation and found some controversies
that may require completely changing the way how it is implemented.

Brief description of the current implementation:
- there is a function `secret` that can refer to the secret values by their names, e.g. `secret('mysql.password')`;
- the function can be used in any place in a query;
- its intended usage is for parameters for table functions (where password is needed) or key argument for encryption function;
- but it can be used for some other places as well, e.g. for user or host argument of table function;
- it returns special data type `Secret(String)` instead of just `String`;
- the data type does not permit serialization and deserialization;
- it is required to avoid obtaining secret values simply by `SELECT secret('mysql.password')`;
- this is the attack vector if user has access to perform arbitrary SQL queries but we don't want to expose secrets to the user;
- the data type `Secret` is a "monad" like `Nullable` and `LowCardinality` - the functions can have default implementation for secret arguments that unwraps secret arguments, run the function as usual and wraps the result to `Secret` data type;
- this implementation is enabled only to specific subset of functions, other functions simply refuse to work with Secret data type;

Many complications exists in current implementation to resolve the following potential issue:
- the values of arguments for some functions may appear in exception message;
- this is also true if secrets were passed to the function;
- the user can obtain a secret if it will substitute it to the argument that is being logged in exception message, for example, the hostname is logged if connection to MySQL being unsuccessful;
- the user will write `mysql(secret('password'), db, table, 'user', '')` instead of `mysql('host', db, table, 'user', secret('password'))` and will obtain the password in plaintext in exception message;

To avoid this issue, you have implemented a kludge:
- exceptions are catched and the values of all available secrets are removed from exception messages by simple substring search and replacement.

But this kludge does not work for the following reasons:
- the user may transform a secret with another function to make substring search and replace not working. E.g. it can extract the first byte of the secret by writing `substring(secret('mysql.password'), 1, 1)`. The function `substring` actually does not support secret arguments. But some other function do. For example, the `encrypt` function supports secret argument. You can encrypt the secret, substitute it to the host argument of `mysql` table function, get the exception message about connection failure and manually decrypt the secret value;
- exception messages are possibly not the only place where the arguments of functions can be logged.

We also have found the implementation to look overengineered and too massive.

Two alternatives exist:

1. The `Secret` data type should refer to the secret by its name. Every function have to support `Secret` values explicitly if needed. These functions have to extract the secret value by itself. Example: the function `secret('abc')` returns the value `abc` of type `Secret`. The table function `mysql('host', db, table, 'user', secret('abc'))` knows that the argument of type `Secret` can appear as password (but not as user) and has to manually obtain the value. The secret value will never be logged.

2. Prepared connections. You specify connection parameters (host, port, user, password, etc...) in configuration file and refer them by name. Example: `mysql(myserver, db, table)`. This is not applicable to specifying the key for encryption functions but can be implemented in addition to (1) for convenience.

**Pull request closed without merging**
