### PR TITLE
Fix for issue #3297

### PR DESCRIPTION
**Pull request by veloman-yunkan**
The pre-existing optimization in the function `JSONEachRowRowInputStream::readColumnName()` (that was extracted during the refactoring step of PR #3144) imposed a restriction on its usage - reading from the input stream might invalidate the return value of that function, and this is what happenned in `readJSONObject()` after the call to `skipColonDelimiter()`.

One way of fixing the problem while preserving the original optimization intact would be to defer the call to `skipColonDelimiter()` until the variable `name_ref` was fully consumed, however that would result in worse code (`skipColonDelimiter()` would need to be called in three different places where it doesn't really belong).

Therefore I preferred to slightly weaken the optimization by always copying the key name into the `current_column_name` data member.

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en **with the exception of the clause "9. Liability" (however hypothetical, it is still an unmanageable risk and I am not going to undertake it).**

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
We should test for the maximum performance degradation. I think, this optimization makes sense.

**Comment by champtar** [comment]
I confirm this fix #3144, thanks a lot @veloman-yunkan 
@veloman-yunkan are you able to do a test case that reproduce the breakage ?

**Comment by champtar** [comment]
Ok so just repeating the same json a lot of time should be enough
I'll try, so we have a public repro case

**Comment by champtar** [comment]
Ok here some simple repro steps:
```
CREATE TABLE test_json_parse (aaa String, bbb String) ENGINE = Memory;

for n in {1..1000000}; do echo '{"aaa":"aaa","bbb":"bbb"}'; done | curl 'http://127.0.0.1:8123/?query=INSERT%20INTO%20test_json_parse%20FORMAT%20JSONEachRow' -0 -v --data-binary @-
```

Without the patch
```
Code: 117, e.displayText() = DB::Exception: Unknown field found while parsing JSONEachRow format: a",, e.what() = DB::Exception
```

This commit fix the issue

**Comment by alexey-milovidov** [comment]
Now I will test for performance regression and merge.

**Comment by veloman-yunkan** [comment]
Thanks!

**Comment by alexey-milovidov** [comment]
There is significant performance degradation comparing to version 18.12.17.

```
$ time dbms/programs/clickhouse local --query="SELECT count() FROM table" --input-format=JSONEachRow --structure='...'

user    0m33.576s

$ time ~/clickhouse-18.12.17 local --query="SELECT count() FROM table" --input-format=JSONEachRow --structure='...'

user    0m25.540s
```

I will try to fix it.

**Comment by alexey-milovidov** [comment]
The bug was present even before this refactoring, when skipping unknown fields.
https://github.com/veloman-yunkan/ClickHouse/blob/fafecb3c25a59777ed691c0a1936d66181d4d093/dbms/src/Formats/JSONEachRowRowInputStream.cpp#L122
name_ref is invalidated at this point.

**Comment by alexey-milovidov** [comment]
But this was only related to error messages.

**Comment by alexey-milovidov** [comment]
> One way of fixing the problem while preserving the original optimization intact would be to defer the call to skipColonDelimiter() until the variable name_ref was fully consumed, however that would result in worse code (skipColonDelimiter() would need to be called in three different places where it doesn't really belong).

Maybe it is Ok.

**Comment by alexey-milovidov** [comment]
Simply returning back the optimization gives just 3 of 8 seconds.

**Comment by alexey-milovidov** [comment]
Yes, now performance is even a little better, than in 18.12.17.

```
18.12.17 (baseline):
user    0m25.540s

This pull request:
user    0m33.576s

Restored optimization (direct reference to the input buffer without a copy):
user    0m29.848s

Added optimization (caching of field order), that was mentioned in comments:
user    0m26.728s

Inline assertChar and some other functions:
user    0m23.828s
```

**Pull request merged**
