### PR TITLE
Add func tests run with s3

### PR DESCRIPTION
**Pull request by alesapin**
Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]
Time to remove `actions` from every check name.

**Comment by alesapin** [comment]
https://s3.amazonaws.com/clickhouse-test-reports/34153/9eea8e3183c68543585cb069a23e7dce47cd1c2e/stateless_tests__release__s3_storage__actions_.html :(

**Comment by alesapin** [comment]
At least server didn't crash https://s3.amazonaws.com/clickhouse-test-reports/34153/ea8ec87b34077592f15ad5428e742005e8fc2b2a/stateless_tests__release__s3_storage__actions_.html

**Comment by alesapin** [comment]
20 failed tests https://s3.amazonaws.com/clickhouse-test-reports/34153/cbf4790ea413b56ccdd02e268d33dafc31ff83b8/stateless_tests__release__s3_storage__actions_.html, no so bad, I'll exclude some incompatible with S3 and fix really failing.

**Comment by alexey-milovidov** [comment]
Sorry, wrong button.

**Pull request merged**
