### PR TITLE
Release pull request for branch 22.6

### PR DESCRIPTION
**Pull request by Felixoid**
This PullRequest is a part of ClickHouse release cycle. It is used by CI system only. Do not perform any changes with it.

### CODE REVIEW

**Comment by qoega** [comment]
ClickHouse Stateless Tests: #38337
Integration tests #38260
ClickHouse Stress Test: checking
```
2022.06.27 15:11:56.687677 [ 353383 ] {} <Error> Application: Caught exception while loading metadata: Code: 441. DB::Exception: Invalid IPv4 value: While processing _CAST('' AS value_tmp_alter13729719617978629155, 'IPv4') AS value: default expression and column type are incompatible.: Cannot attach table `test_7`.`ipv6_test` from metadata file /var/lib/clickhouse/metadata/test_7/ipv6_test.sql from query ATTACH TABLE test_7.ipv6_test (`id` UInt64, `value` IPv4 DEFAULT '') ENGINE = MergeTree ORDER BY id SETTINGS index_granularity = 8192. (CANNOT_PARSE_DOMAIN_VALUE_FROM_STRING), Stack trace (when copying this message, always include the lines below):
```

**Comment by qoega** [comment]
@tavplubix it will be easier if https://github.com/ClickHouse/ClickHouse/commit/299f102ccf92e1ea001ad9483171f75f33cb75bc was a PR to master. I could merge it just by setting the label. Now it requires manual merge

**Comment by qoega** [comment]
OK. Haven't seen this issue. It means current release is incompatible.

**Comment by qoega** [comment]
@tavplubix https://s3.amazonaws.com/clickhouse-test-reports/38146/1fc97f10cbffda0ae8460c575a4637e45e09cc11/stress_test__address__actions_.html
It is reproducing https://github.com/ClickHouse/ClickHouse/issues/37664
Proposed fix is already in 22.6.1 https://github.com/ClickHouse/ClickHouse/pull/37839/commits/2358878c381dcef89a288a414679017dc22a2a86

**Comment by qoega** [comment]
00984_parser_stack_overflow became flaky in June. Need to check if it the real issue

https://play.clickhouse.com/play?user=play#c2VsZWN0IGNoZWNrX25hbWUsIHRlc3RfbmFtZSwgY2hlY2tfc3RhcnRfdGltZSwgdGVzdF9zdGF0dXMsIHJlcG9ydF91cmwsIGNvbW1pdF9zaGEKZnJvbSBjaGVja3MgCndoZXJlIAp0ZXN0X3N0YXR1cyBub3QgaW4gWydPSycsICdTVUNDRVNTJywgJ1NLSVBQRUQnLCAnWEZBSUwnLCAnWEVSUk9SJ10gYW5kIAp0ZXN0X25hbWUgbGlrZSAnMDA5ODRfcGFyc2VyX3N0YWNrX292ZXJmbG93JScgCmFuZCBwdWxsX3JlcXVlc3RfbnVtYmVyID0gMAphbmQgY2hlY2tfc3RhcnRfdGltZSA+PSBub3coKSAtIGludGVydmFsIDMwIGRheQpvcmRlciBieSBjaGVja19zdGFydF90aW1lIGRlc2M=

**Comment by qoega** [comment]
With tsan 00984_parser_stack_overflow really takes more than 1 minute
```
2022.06.17 16:58:15.473366 [ 22916 ] {e0efd9c8-eef0-49d4-b283-469b5df2f3a4} <Debug> executeQuery: (from [::1]:50398) (comment: 00984_parser_stack_overflow.sh) SELECT ([([([([([([([([([([([([([([([([([([([([([([([([([([([([([([([([([([([([([([([([([([([([([([([([([([([([([([([([([([([([([([([([([([([([([([([([([([([([([([([([([([([([([([([([>
2022.06.17 16:59:42.964748 [ 22916 ] {e0efd9c8-eef0-49d4-b283-469b5df2f3a4} <Error> executeQuery: Code: 306. DB::Exception: Maximum parse depth (1000) exceeded. Consider rising max_parser_depth parameter. (TOO_DEEP_RECURSION) (version 22.7.1.1 (official build)) (from [::1]:50398) (comment: 00984_parser_stack_overflow.sh) (in query: SELECT (>
2022.06.17 16:59:42.987011 [ 22916 ] {e0efd9c8-eef0-49d4-b283-469b5df2f3a4} <Error> DynamicQueryHandler: Code: 306. DB::Exception: Maximum parse depth (1000) exceeded. Consider rising max_parser_depth parameter. (TOO_DEEP_RECURSION), Stack trace (when copying this message, always include the lines below):
2022.06.17 16:59:48.864062 [ 22916 ] {e0efd9c8-eef0-49d4-b283-469b5df2f3a4} <Error> DynamicQueryHandler: Cannot send exception to client: Code: 24. DB::Exception: Cannot write to ostream at offset 328. (CANNOT_WRITE_TO_OSTREAM), Stack trace (when copying this message, always include the lines below):
2022.06.17 16:59:48.864673 [ 22916 ] {e0efd9c8-eef0-49d4-b283-469b5df2f3a4} <Debug> MemoryTracker: Peak memory usage (for query): 1.00 MiB.
```

**Comment by Felixoid** [comment]
The issue is open for the last backport https://github.com/ClickHouse/ClickHouse/pull/42089

**Pull request closed without merging**
