### PR TITLE
Allow nullable key in MergeTree

### PR DESCRIPTION
**Pull request by amosbird**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- New Feature

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Allow Nullable types as keys in MergeTree tables. https://github.com/ClickHouse/ClickHouse/issues/5319

Detailed description / Documentation draft:

A new setting `allow_nullable_key` is created which enables this feature. The default value is `false`.

NULLs comparison order is NULLS_LAST, which is based on https://github.com/ClickHouse/ClickHouse/pull/8834

### CODE REVIEW

**Comment by amosbird** [comment]
Irrelevant failure due to test is flaky.

**Review by alexey-milovidov — APPROVED** [review]
Ok.

But for full support we also have to implement IS NULL, IS NOT NULL in KeyCondition.

**Comment by calebeaires** [comment]
Is this feature implemented? Based on the example above I cant create the table

```sql
CREATE TABLE nullable_key 
      (k Nullable(int), v int) ENGINE MergeTree ORDER BY k SETTINGS allow_nullable_key = 1;`

```

Error
Code: 36, e.displayText() = DB::Exception: Unknown setting allow_nullable_key for storage MergeTree (version 20.6.4.44 (official build))

**Comment by alexey-milovidov** [comment]
It's available from version 20.7.

**Comment by yanchaoguo** [comment]
你好  虽然20.7版本在create table 时解决了这个问题，但是新的MaterializeMySQL Feature是自动创建表的，如故mysql中存在索引为NULL时依然会报错

**Comment by zhang2014** [comment]
@yanchaoguo fixed in https://github.com/ClickHouse/ClickHouse/pull/14397

**Comment by yanchaoguo** [comment]
Which version will be merged

**Comment by yanchaoguo** [comment]
> @yanchaoguo fixed in #14397

Which version will be merged

**Comment by filimonov** [comment]
#5319

**Comment by filimonov** [comment]
> Which version will be merged

20.7

**Comment by yanchaoguo** [comment]
> > Which version will be merged
> 
> 20.7

你好 虽然20.7版本在create table 时解决了这个问题，但是新的MaterializeMySQL Feature是自动创建表的，如故mysql中存在索引为NULL时依然会报错

**Pull request merged**
