### PR TITLE
[ClickHouse][Copier] Improve copier work

### LINKED ISSUE #21911: some copier work needs to be improved
- some copier work needs to be improved

1. clickhouse create destionation table just once if success
2. support settings_push.replication_alter_partitions_sync =1 at attach partition 
3. ...

### PR DESCRIPTION
**Pull request by songenjie**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):

- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Supported `replication_alter_partitions_sync=1` setting for moving partitions from helping table to destination. Decreased default timeouts. Fixes [#21911](https://github.com/ClickHouse/ClickHouse/issues/21911).

/cc @nikitamikhaylov @alexey-milovidov

### CODE REVIEW

**Comment by songenjie** [comment]
@nikitamikhaylov This MR only modified the function and calling logic, and did not create a new function ,PTAL

**Comment by nikitamikhaylov** [comment]
> @nikitamikhaylov This MR only modified the function and calling logic, and did not create a new function ,PTAL

But some tests are failing...

**Comment by songenjie** [comment]
@nikitamikhaylov ./docker/test/fuzzer/run-fuzzer.sh this check  error displayed has nothing to do with mr, which is about clickhouser server, PTAL

**Comment by nikitamikhaylov** [comment]
> @nikitamikhaylov ./docker/test/fuzzer/run-fuzzer.sh this check  error displayed has nothing to do with this mr, which is about clickhouser server, PTAL

It is Ok. You need only integration tests to be green, because Copier is being tested only by them.

**Comment by songenjie** [comment]
> > @nikitamikhaylov ./docker/test/fuzzer/run-fuzzer.sh this check  error displayed has nothing to do with this mr, which is about clickhouser server, PTAL
> 
> It is Ok. You need only integration tests to be green, because Copier is being tested only by them.

the Integration tests errors is about clickhouse server

**Review by nikitamikhaylov — APPROVED** [review]

**Comment by nikitamikhaylov** [comment]
Changes in copier are isolated, so test failures are unrelated

**Comment by KochetovNicolai** [comment]
@nikitamikhaylov you forgot to change description

**Pull request merged**
