### PR TITLE
Re-evaluate performance of LZ4_decompress_fast

### LINKED ISSUE #40619: The performance of LZ4_decompress_faster is slower than official LZ4_decompress_fast
https://github.com/ClickHouse/ClickHouse/blob/7d1e3ecfa35edf23bae83081b4385f994697b6ab/src/Compression/CompressionCodecLZ4.cpp#L95-L101

I replace `LZ4::decompress(source, dest, source_size, uncompressed_size, lz4_stat)` with `LZ4_decompress_fast(source, dest, uncompressed_size)` here. And I use the Clickbench data.

```sql
SELECT COUNT(WatchID), COUNT(JavaEnable), COUNT(Title), COUNT(GoodEvent), COUNT(EventTime), COUNT(EventDate), COUNT(CounterID), COUNT(ClientIP), COUNT(RegionID), COUNT(UserID), COUNT(CounterClass), COUNT(OS), COUNT(UserAgent), COUNT(URL), COUNT(Referer), COUNT(IsRefresh), COUNT(RefererCategoryID), COUNT(RefererRegionID), COUNT(URLCategoryID), COUNT(URLRegionID), COUNT(ResolutionWidth), COUNT(ResolutionHeight), COUNT(ResolutionDepth), COUNT(FlashMajor), COUNT(FlashMinor), COUNT(FlashMinor2), COUNT(NetMajor), COUNT(NetMinor), COUNT(UserAgentMajor), COUNT(UserAgentMinor), COUNT(CookieEnable), COUNT(JavascriptEnable), COUNT(IsMobile), COUNT(MobilePhone), COUNT(MobilePhoneModel), COUNT(Params), COUNT(IPNetworkID), COUNT(TraficSourceID), COUNT(SearchEngineID), COUNT(SearchPhrase), COUNT(AdvEngineID), COUNT(IsArtifical), COUNT(WindowClientWidth), COUNT(WindowClientHeight), COUNT(ClientTimeZone), COUNT(ClientEventTime), COUNT(SilverlightVersion1), COUNT(SilverlightVersion2), COUNT(SilverlightVersion3), COUNT(SilverlightVersion4), COUNT(PageCharset), COUNT(CodeVersion), COUNT(IsLink), COUNT(IsDownload), COUNT(IsNotBounce), COUNT(FUniqID), COUNT(OriginalURL), COUNT(HID), COUNT(IsOldCounter), COUNT(IsEvent), COUNT(IsParameter), COUNT(DontCountHits), COUNT(WithHash), COUNT(HitColor), COUNT(LocalEventTime), COUNT(Age), COUNT(Sex), COUNT(Income), COUNT(Interests), COUNT(Robotness), COUNT(RemoteIP), COUNT(WindowName), COUNT(OpenerName), COUNT(HistoryLength), COUNT(BrowserLanguage), COUNT(BrowserCountry), COUNT(SocialNetwork), COUNT(SocialAction), COUNT(HTTPError), COUNT(SendTiming), COUNT(DNSTiming), COUNT(ConnectTiming), COUNT(ResponseStartTiming), COUNT(ResponseEndTiming), COUNT(FetchTiming), COUNT(SocialSourceNetworkID), COUNT(SocialSourcePage), COUNT(ParamPrice), COUNT(ParamOrderID), COUNT(ParamCurrency), COUNT(ParamCurrencyID), COUNT(OpenstatServiceName), COUNT(OpenstatCampaignID), COUNT(OpenstatAdID), COUNT(OpenstatSourceID), COUNT(UTMSource), COUNT(UTMMedium), COUNT(UTMCampaign), COUNT(UTMContent), COUNT(UTMTerm), COUNT(FromTag), COUNT(HasGCLID), COUNT(RefererHash), COUNT(URLHash), COUNT(CLID) FROM (SELECT * FROM hits);
```

The result:
```shell
# LZ4_decompress_faster decompress
[80.261, 84.438, 78.873]
# LZ4_decompress_fast
[76.442, 70.867, 67.826]
```

And I tried different times, get a similar result. Did I do anything incorrectly?

Test on MacBook Pro Apple M1 Pro Monterey 12.3

### PR DESCRIPTION
**Pull request by Lloyd-Pottiger**
Signed-off-by: Lloyd-Pottiger <yan1579196623@gamil.com>

### Changelog category (leave one):
- Performance Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
revert LZ4_decompress_faster, close #40619 

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by Lloyd-Pottiger** [comment]
@alexey-milovidov Could you please add the label `can be test`?

**Comment by Lloyd-Pottiger** [comment]
Seems the performance is very close. Any larger dataset in the performance test? @nickitat

**Comment by nickitat** [comment]
> Seems the performance is very close. Any larger dataset in the performance test? @nickitat

no, hits_100m is the largest predefined ds in our perf tests. you may check simple read queries on tpc* and ssb datasets, it would be very valuable. the latter is very simple to ingest in CH using [this](https://clickhouse.com/docs/en/getting-started/example-datasets/star-schema/) instruction.
pls check also [these](https://github.com/ClickHouse/ClickHouse/blob/ec507119dfb21bedca860945f8ad1462b17fe01e/tests/performance/lz4.xml) cases.

also we need to filter all the queries from perf tests where speedup is real (reproducible and persistent). e.g. `array_index_low_cardinality_numbers #0` seems to be one of them, I see the same improvement locally. then we could find the reasons behind this changes in perf.

**Comment by Lloyd-Pottiger** [comment]
> you may check simple read queries on tpc* and ssb datasets, it would be very valuable. the latter is very simple to ingest in CH using [this](https://clickhouse.com/docs/en/getting-started/example-datasets/star-schema/) instruction. 

I have tried it on my m1pro mbp with clickbench. I can see the improvement locally, but I am not sure about the performance in x64 platform since I don't have a x64 device. Actually both `LZ4_decompress_faster` and `LZ4_decompress_fast` focus on x64. 

> pls check also [these](https://github.com/ClickHouse/ClickHouse/blob/ec507119dfb21bedca860945f8ad1462b17fe01e/tests/performance/lz4.xml) cases.

nice! I have added them into the perf.

> also we need to filter all the queries from perf tests where speedup is real (reproducible and persistent). e.g. `array_index_low_cardinality_numbers #0` seems to be one of them, I see the same improvement locally. then we could find the reasons behind these changes in perf.

yes, I will record the result of each time running and make a summary later.

**Comment by nickitat** [comment]
thank you! I can do some tests on x86.

**Comment by nickitat** [comment]
looks like upstream implementation of `LZ4_decompress_fast` is still worse. and btw it is deprecated on behalf of `LZ4_decompress_safe` that is also [should be](https://github.com/lz4/lz4/blob/dev/lib/lz4.h#L815-L840) faster. let's check it.

**Comment by nickitat** [comment]
looks better now

**Comment by nickitat** [comment]
we need to
1. filter the queries on which changes (both positive and negative) are stably reproducible. likely many slowdowns will pass this filter, so we cannot just replace current implementation with the one from upstream.
2. thus we need to analyse the queries when `LZ4_decompress_safe` performs better to understand when and why. maybe it is smth simple like `compression factor >> 2`, maybe smth more sophisticated.

**Comment by alexey-milovidov** [comment]
Abandoned.

**Pull request closed without merging**
