### PR TITLE
Improve `grace_hash` join by reserving hash table's size

### PR DESCRIPTION
**Pull request by lgbo-ustc**
### Changelog category (leave one):
- Performance Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Try to reserve hash table's size in `grace_hash` join.

for following query
```SQL
CREATE TABLE t1 (key UInt32, s String) engine = TinyLog;
CREATE TABLE t2 (key UInt32, s String) engine = TinyLog;


insert into t1 select number as key, toString(number) as s from numbers(20000000);
insert into t2 select number as key, toString(number/3) as s from numbers(20000000);
select count(1) from (SELECT key FROM t1 AS t1 ALL LEFT JOIN t2 AS t2 USING (key) )t1 settings join_algorithm='grace_hash', max_rows_in_join=1000000;
```
before
```
1 row in set. Elapsed: 20.685 sec. Processed 40.00 million rows, 160.00 MB (1.93 million rows/s., 7.74 MB/s.)
```
after
```
1 row in set. Elapsed: 16.146 sec. Processed 40.00 million rows, 160.00 MB (2.48 million rows/s., 9.91 MB/s.)
```

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by robot-ch-test-poll3** [comment]
This is an automated comment for commit a737a34e7b157ae0e3325d8bfaec8bb8ea6c50dd with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/49816/a737a34e7b157ae0e3325d8bfaec8bb8ea6c50dd/ci_running.html)
The overall status of the commit is 🔴 failure

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🔴 failure</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Comment by lgbo-ustc** [comment]
There are 3 failures, but I think they are not related to this pr. @vdimir

**Review by vdimir — APPROVED** [review]

**Comment by vdimir** [comment]
Great!
image

**Comment by tavplubix** [comment]
Is there a chance it could break `join_set_filter`?
https://s3.amazonaws.com/clickhouse-test-reports/0/3f892ceb12b868b1b9deb0607a7df2dde5f1a139/performance_comparison_[1_4]/report.html

**Comment by vdimir** [comment]
> Is there a chance it could break join_set_filter? https://s3.amazonaws.com/clickhouse-test-reports/0/3f892ceb12b868b1b9deb0607a7df2dde5f1a139/performance_comparison_[1_4]/report.html

@tavplubix It shouldn't, I'll check the reason

**Pull request merged**
