### PR TITLE
make numactl respect EPERM error, when get_mempolicy is is restricted by seccomp

### LINKED ISSUE #68747: On Docker using Clickhouse latest e155f535964c causing permission error
**Company or project name**
Personal
Put your company name or project description here
Building a docker image from latest
**I have tried the following solutions**: https://clickhouse.com/docs/en/faq/troubleshooting/#troubleshooting-installation-errors
Swapping docker image to 24.3.7 fixes this
**Installation type**
docker on amd64
Packages, docker, single binary, curl?
docker
**Source of the ClickHouse**
dockerhub
A link to the source. Or the command you've tried

**Expected result**
completed install

**The actual result**
Logs showing "get_mempolicy operation not permitted" from clickhouse containter
What you get

**How to reproduce**
boot a clickhouse docker image from latest
* For Linux-based operating systems: provide a script for clear docker container from the official image

* For anything else: steps to reproduce on as much as possible clear system

### PR DESCRIPTION
**Pull request by filimonov**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix the issue where ClickHouse in Docker containers printed "get_mempolicy: Operation not permitted" into stderr due to restricted syscalls.

### Documentation entry for user-facing changes

```
docker run --rm clickhouse/clickhouse-server:latest
Processing configuration file '/etc/clickhouse-server/config.xml'.
Merging configuration file '/etc/clickhouse-server/config.d/docker_related_config.xml'.
Logging trace to /var/log/clickhouse-server/clickhouse-server.log
Logging errors to /var/log/clickhouse-server/clickhouse-server.err.log
get_mempolicy: Operation not permitted
get_mempolicy: Operation not permitted
get_mempolicy: Operation not permitted
```

Closes #68747

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Run only fuzzers related jobs (libFuzzer fuzzers, AST fuzzers, etc.)
- [ ]  Exclude: AST fuzzers
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]

**Comment by robot-clickhouse-ci-2** [comment]
*This is an automated comment for commit d13dbd6fcd65760d51def005a343d81fec97227e with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/70900/d13dbd6fcd65760d51def005a343d81fec97227e/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/e1025300d0c832a8d634d17dbbc793b1a144ced4/docs_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Comment by antonio2368** [comment]
@filimonov Fast test failed for some reason

**Comment by filimonov** [comment]
> @filimonov Fast test failed for some reason

Funny - it seem like the expect test send ctrl+c and exit almost simultaniosly, and ctrl+c signal did split `exit` command into 2 chunks, and clickhouse complain that he don't understant the command 'xit' :) 

I've just added waiting for a prompt between those, hope it should fix the problem

```
2024-10-22 09:35:35 send: sending "\u0003" to { exp4 }
2024-10-22 09:35:35 send: sending "exit\r" to { exp4 }
2024-10-22 09:35:35 ^Cexit
2024-10-22 09:35:35 
2024-10-22 09:35:35 bash: xit: command not found
2024-10-22 09:35:35 clickhouse@ip-172-31-37-147:/fasttest-workspace$
```

**Comment by filimonov** [comment]
Missed the change from the https://github.com/numactl/numactl/commit/8d13d63a05f0c3cd88bf777cbb61541202b7da08

**Comment by filimonov** [comment]
OK, it seems like that test was flapping from time to time, that attempt to fix made it worse:

https://play.clickhouse.com/play?user=play#U0VMRUNUIGNoZWNrX3N0YXJ0X3RpbWUsIGhlYWRfcmVmLCBjaGVja19uYW1lLCB0ZXN0X25hbWUsIHJlcG9ydF91cmwKRlJPTSBjaGVja3MKV0hFUkUgMQogICAgQU5EIGNoZWNrX3N0YXJ0X3RpbWUgPj0gbm93KCkgLSBJTlRFUlZBTCAxODAgREFZCiAgICBBTkQgdGVzdF9uYW1lIGxpa2UgJyUwMjMxMF9jbGlja2hvdXNlX2xvY2FsX0lOU0VSVF9wcm9ncmVzc19wcm9maWxlX2V2ZW50cyUnCiAgICBBTkQgdGVzdF9zdGF0dXMgIT0gJ1NLSVBQRUQnCiAgICBBTkQgKHRlc3Rfc3RhdHVzIExJS0UgJ0YlJyBPUiB0ZXN0X3N0YXR1cyBMSUtFICdFJScpIAogICAgQU5EIGNoZWNrX3N0YXR1cyAhPSAnc3VjY2VzcycKICAgIEFORCBjaGVja19uYW1lIE5PVCBMSUtFICdTUUxhbmNlciUnCk9SREVSIEJZIGNoZWNrX3N0YXJ0X3RpbWU=

And there were already several attempts to 'fix' that
https://github.com/ClickHouse/ClickHouse/pull/67961
https://github.com/ClickHouse/ClickHouse/pull/67264

Will check how to improve that...

**Comment by filimonov** [comment]
I've moved commits about flaky test to a different PR
https://github.com/ClickHouse/ClickHouse/pull/71036

**Comment by antonio2368** [comment]
Everything looks good
I merged the numactl PR, can you please set the contrib to the master commit?
Thanks again for fixing this

**Comment by filimonov** [comment]
>  I merged the numactl PR, can you please set the contrib to the master commit?

:heavy_check_mark: 

BTW - upstream also accepted both changes quickly
https://github.com/numactl/numactl/pulls?q=is%3Apr+is%3Aclosed+author%3Afilimonov

But may be let's keep it independent.

**Review by antonio2368 — APPROVED** [review]

**Pull request merged**
