### PR TITLE
Disallow Gorilla codec on non-float columns

### PR DESCRIPTION
**Pull request by rschu1ze**
Cf. #45195

### Changelog category (leave one):
- Backward Incompatible Change 

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Disallow Gorilla compression on columns of non-Float32 or non-Float64 type.

### Documentation entry for user-facing changes

- [ X ] Documentation is written (mandatory for new features)

### CODE REVIEW

**Review by Avogar — APPROVED** [review]

**Comment by davenger** [comment]
How about a test?

**Comment by rschu1ze** [comment]
Next commit :)

**Comment by den-crane** [comment]
For changelog: backward incompatible change.

**Comment by den-crane** [comment]
BTW, the issue is because of combination of codecs `codec (Delta, Gorilla, LZ4)`. Not because Decimal type.

**Comment by den-crane** [comment]
```sql
create table bug_gor_lz ( value_bug Float64 codec (Delta, Gorilla, LZ4)
) engine = MergeTree order by tuple() as select 0 from numbers(1e7);

select * from bug_gor_lz where 0.0 <> value_bug limit 10;

┌────────────────value_bug─┐
│    4.927549738046179e180 │
│   -1.154350463386742e-65 │
│   8.526606562949742e-194 │
│ -1.2810555172165677e-249 │
│  -1.0439411844753269e307 │
│   1.5110172119519233e241 │
│  -2.5236826111584395e175 │
│     6.628092400109508e37 │
│     6.628556554427993e37 │
│     6.628556558479204e37 │
└──────────────────────────┘
```

**Review by alexey-milovidov — APPROVED** [review]

**Comment by rschu1ze** [comment]
> BTW, the issue is because of the combination of codecs `codec (Delta, Gorilla, LZ4)`. Not because Decimal type.
> Delta+Gorilla -- should be forbidden as suspicious

True, thanks. Will check/block this combination too but separately. This PR makes sense in itself.

**Comment by rschu1ze** [comment]
ClickHouse Integration Tests (tsan) [6/6]
- test_merge_tree_s3/test.py::test_attach_detach_partition[node]: looks like an infra issue, test is a bit unstable

Various ClickHouse Stress Test failures, e.g.
```
2023.01.15 19:55:09.399051 [ 718520 ] {} <Error> Application: Caught exception while loading metadata: Code: 36. DB::Exception: Gorilla codec is not applicable for UInt32 because the data type is not float: Cannot attach table `test_33`.`codecs` from metadata file /var/lib/clickhouse/store/a76/a76b7007-9be4-417e-8a9e-ecc4e1837516/codecs.sql from query ATTACH TABLE test_33.codecs UUID 'cfdda7c2-a32d-4220-9214-68e571bab248' (`a` UInt8 CODEC(LZ4), `b` UInt16 CODEC(ZSTD(1)), `c` Float32 CODEC(Gorilla), `d` UInt8 CODEC(Delta(1), LZ4), `e` Float64 CODEC(Gorilla, ZSTD(1)), `f` UInt32 CODEC(Delta(4), Delta(4), Gorilla), `g` DateTime CODEC(DoubleDelta), `h` DateTime64(3) CODEC(DoubleDelta, LZ4), `i` String CODEC(NONE)) ENGINE = MergeTree ORDER BY tuple() SETTINGS index_granularity = 8192. (BAD_ARGUMENTS), Stack trace (when copying this message, always include the lines below)```
I think the system tries to start the new server with a persistence created by an old server. So a failure is expected here (--> backwards incompatible change).

**Comment by tavplubix** [comment]
@rschu1ze, Stress Tests failures were related. Stress Tests are broken in master now. Let's revert the breaking change.

https://play.clickhouse.com/play?user=play#d2l0aCAKJyVCYWNrd2FyZCBjb21wYXRpYmlsaXR5IGNoZWNrOiBTZXJ2ZXIgZmFpbGVkIHRvIHN0YXJ0JScgYXMgbmFtZV9wYXR0ZXJuLAonMjAyMi0wOS0wMScgYXMgc3RhcnRfZGF0ZSwKKCdTdGF0ZWxlc3MgdGVzdHMgKGFzYW4pJywgJ1N0YXRlbGVzcyB0ZXN0cyAoYWRkcmVzcyknLCAnU3RhdGVsZXNzIHRlc3RzIChhZGRyZXNzLCBhY3Rpb25zKScpIGFzIGJhY2twb3J0X2FuZF9yZWxlYXNlX3NwZWNpZmljX2NoZWNrcwpzZWxlY3QgCnRvU3RhcnRPZkRheShjaGVja19zdGFydF90aW1lKSBhcyBkLApjb3VudCgpLCAgZ3JvdXBVbmlxQXJyYXkocHVsbF9yZXF1ZXN0X251bWJlciksIGFueShyZXBvcnRfdXJsKQpmcm9tIGNoZWNrcyB3aGVyZSBzdGFydF9kYXRlIDw9IGNoZWNrX3N0YXJ0X3RpbWUgYW5kIHB1bGxfcmVxdWVzdF9udW1iZXIgbm90IGluIAooc2VsZWN0IHB1bGxfcmVxdWVzdF9udW1iZXIgYXMgcHJuIGZyb20gY2hlY2tzIHdoZXJlIHBybiE9MCBhbmQgc3RhcnRfZGF0ZSA8PSBjaGVja19zdGFydF90aW1lIGFuZCBjaGVja19uYW1lIGluIGJhY2twb3J0X2FuZF9yZWxlYXNlX3NwZWNpZmljX2NoZWNrcykgCmFuZCB0ZXN0X25hbWUgbGlrZSBuYW1lX3BhdHRlcm4gCmFuZCB0ZXN0X3N0YXR1cyBpbiAoJ0ZBSUwnLCAnRkxBS1knKSBncm91cCBieSBkIG9yZGVyIGJ5IGQgZGVzYw==

**Comment by tavplubix** [comment]
It should be possible to suppress BC check for intended backward incompatible changes. For example, we can use a `allow_suspicious_codecs` to allow incorrect usages of Gorilla codec and enable the setting before starting a new server in BC check here:
https://github.com/ClickHouse/ClickHouse/blob/703f223e50c3fb1cf3f05998baf7bc41d35c7b5f/docker/test/stress/run.sh#L466-L472

**Comment by rschu1ze** [comment]
Okay, thanks. Didn't think about suppressing the change. Will pick this this up again hopefully soon.

**Pull request merged**
