### PR TITLE
Refactor code related to authentication

### PR DESCRIPTION
**Pull request by aalexfvk**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by robot-clickhouse** [comment]
*This is an automated comment for commit 8a5592d700417c3e2af332d4514462ea791f21f2 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/54958/8a5592d700417c3e2af332d4514462ea791f21f2/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>✅ success</td></tr>
<tbody>
</table>
</details>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>⏳ pending</td></tr>
<tbody>
</table>

**Comment by nikitamikhaylov** [comment]
What is the motivation for the refactoring? Please link the issue or a PR which depends on this.

**Comment by aalexfvk** [comment]
> What is the motivation for the refactoring? Please link the issue or a PR which depends on this.

I am working on a new method of authentication (HTTP Basic). There is no open issue for this yet. In the process, I came across such a messy code like
https://github.com/ClickHouse/ClickHouse/blob/0f27275fcef3b9a788e1b73e8bacf85e7c16d084/src/Access/AuthenticationData.cpp#L175-L176
https://github.com/ClickHouse/ClickHouse/blob/0f27275fcef3b9a788e1b73e8bacf85e7c16d084/src/Access/AuthenticationData.cpp#L229-L236
And so on. So you need to change almost every function of `AuthenticationData` class when adding a new auth type.

Or you are forced to repeat the same code here many times. And consistency is hard to keep track of, as it is here:
https://github.com/ClickHouse/ClickHouse/blob/0f27275fcef3b9a788e1b73e8bacf85e7c16d084/src/Access/Authentication.cpp#L135-L136
https://github.com/ClickHouse/ClickHouse/blob/0f27275fcef3b9a788e1b73e8bacf85e7c16d084/src/Access/Authentication.cpp#L168-L169

So I suggested how it could be structured. But honestly it's not a blocker for my task, so I've put these changes in a separate PR in case they're not accepted.

**Comment by aalexfvk** [comment]
Closing this PR, as I am not going to support it at this point in time

**Pull request closed without merging**
