### PR TITLE
enable DateTime64 to be version column

### PR DESCRIPTION
**Pull request by MaxWk**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

enable DateTime64 to be a version column in ReplacingMergeTree

Detailed description / Documentation draft:

enable DateTime64 to be a version column in ReplacingMergeTree. https://github.com/ClickHouse/ClickHouse/issues/20865

By adding documentation, you'll allow users to try your new feature immediately, not when someone else will have time to document it later. Documentation is necessary for all features that affect user experience in any way. You can add brief documentation draft above, or add documentation right into your patch as Markdown files in [docs](https://github.com/ClickHouse/ClickHouse/tree/master/docs) folder.

If you are doing this for the first time, it's recommended to read the lightweight [Contributing to ClickHouse Documentation](https://github.com/ClickHouse/ClickHouse/tree/master/docs/README.md) guide first.

Information about CI checks: https://clickhouse.tech/docs/en/development/continuous-integration/

### CODE REVIEW

**Review by alexey-milovidov — CHANGES_REQUESTED** [review]
Need to add a test.

**Comment by alexey-milovidov** [comment]
@MaxWk The tests are located in `tests/queries/0_stateless` directory.

**Comment by MaxWk** [comment]
> @MaxWk The tests are located in `tests/queries/0_stateless` directory.

thanks ,i added sometests on it

**Review by alexey-milovidov — APPROVED** [review]

**Comment by MaxWk** [comment]
@alexey-milovidov  I am not very familiar with the process, if there is anything I can do, please let me know

**Comment by sevirov** [comment]
Internal documentation ticket: DOCSUP-9597.

**Pull request merged**
