### PR TITLE
Trying stress on top of S3

### PR DESCRIPTION
**Pull request by alesapin**
### Changelog category (leave one):

- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by alesapin** [comment]
@mergifyio update

**Comment by alesapin** [comment]
Wow, almost work now. For debug we have an assertion for thread sanitizer it's a real OOM (no traces in gdb.log)

**Comment by alesapin** [comment]
@mergifyio update

**Comment by azat** [comment]
>Wow, almost work now. For debug we have an assertion for thread sanitizer it's a real OOM (no traces in gdb.log)

Actually it is not real OOM, there is no message about it in dmesg and RSS is low, in logs:

```
2022.08.26 15:28:25.000335 [ 1698 ] {} <Trace> AsynchronousMetrics: MemoryTracking: was 7.50 GiB, peak 17.17 GiB, will set to 7.50 GiB (RSS), difference: 3.91 MiB
...
2022.08.26 15:28:59.859321 [ 1416 ] {} <Information> BaseDaemon: Stop SignalListener thread
2022.08.26 15:29:24.985224 [ 1411 ] {} <Fatal> Application: Child process was terminated by signal 9 (KILL). If it is not done by 'forcestop' command or manually, the possible cause is OOM Killer (see 'dmesg' and look at the '/var/log/kern.log' for the details).
```

```
Found pid = 1413 in the list of running processes.
The process with pid = 1413 is running.
Process (pid = 1413) is still running. Will not try to kill it.
```

The problem is that gdb does not work as expected:

```
++ pidof gdb
+ kill -TERM ''
/run.sh: line 110: kill: `': not a pid or valid job spec
```

Because of this:

```
2022-08-26 15:23:12,276 Will terminate gdb (if any)
```

This should help - #40678

**Comment by tavplubix** [comment]
> there is no message about it in dmesg

dmesg.log starts at `13:40:20` and ends at `14:04:21`, so it may be incomplete

But yes, it really looks that `clickhouse-server` was killed by `clickhouse stop --force` and the script failed to obtain stacktraces with gdb, but for completely different reason:
```
+ clickhouse stop --do-not-kill
...

The process with pid = 1413 is running.
Waiting for server to stop
/var/run/clickhouse-server/clickhouse-server.pid file exists and contains pid = 1413.
The process with pid = 1413 is running.
Waiting for server to stop
/var/run/clickhouse-server/clickhouse-server.pid file exists and contains pid = 1413.
The process with pid = 1413 is running.
Waiting for server to stop
/var/run/clickhouse-server/clickhouse-server.pid file exists and contains pid = 1413.
The process with pid = 1413 is running.
Waiting for server to stop
Found pid = 1413 in the list of running processes.
The process with pid = 1413 is running.
Waiting for server to stop
Found pid = 1413 in the list of running processes.
The process with pid = 1413 is running.

...

++ cat /var/run/clickhouse-server/clickhouse-server.pid
cat: /var/run/clickhouse-server/clickhouse-server.pid: No such file or directory
+ gdb -batch -ex 'thread apply all backtrace' -p ''
Argument required (process-id to attach).
```

As you can see, `clickhouse-server` hung after `/var/run/clickhouse-server/clickhouse-server.pid` was removed, so the script fails to get pid of `clickhouse-server`.

**Comment by alesapin** [comment]
https://github.com/ClickHouse/ClickHouse/pull/40844

**Comment by alesapin** [comment]
Race fix https://github.com/ClickHouse/ClickHouse/pull/40950

**Comment by alesapin** [comment]
Almost good, one more run and let's merge

**Comment by alesapin** [comment]
Something strange with removal of temp parts: https://pastila.nl/?0002433b/7d28cb226ba66b6f48517b93991ce2ee

**Review by kssenii — APPROVED** [review]

**Pull request merged**
