### PR TITLE
Update replacingmergetree.md

### PR DESCRIPTION
**Pull request by dreamerfable**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Documentation (changelog entry is not required)

Detailed description / Documentation draft:
- fix wrong translation of sorting key.
- fix wrong indent.
- correct the wrong links.
- make some sentences more understandable.

Negotiable:
I think the title which is a name of table engine is more approriate to keeping in english, because it is easier in searching and reading, toughly translate it into chinese is kindly weird, so I change it back to english, but I am not sure is it right.

### CODE REVIEW

**Comment by qoega** [comment]
Thank you

**Comment by dreamerfable** [comment]
@qoega ClickHouse is a powerful database,let more people to kwow it is my pleasure.

**Comment by dreamerfable** [comment]
Detailed description for updates of custom-paritioning-key:
- fix some wrong links
- fix some wrong format like the result of query
- correct the translation of the system table's name.It should not be translated
- correct the hint level according to the en version
- make some sentence more understandable

**Comment by dreamerfable** [comment]
Detailed description for updates of aggregatingmergetree:
- add missing content，like description of SimpleAggregateFunction and Sorting Key
- fix some wrong links
- correct the hint level according to the en version
- Make some sentences more understandable

**Review by alexey-milovidov — APPROVED** [review]

**Pull request merged**
