### PR TITLE
Add CPU flamegraphs for perf tests

### PR DESCRIPTION
**Pull request by azat**
In Real profiler there is too much noise (polling, cond vars, ...)

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by tavplubix** [comment]
Can we just use both?

**Review by alexey-milovidov — APPROVED** [review]
I'm ok with switching.

Maybe we will get less info, but with the fact the performance tests are not stable enough, this simplification will be for good.

**Comment by alexey-milovidov** [comment]
Looks abandoned.

**Comment by azat** [comment]
Rebased, added CPU flamegraphs in addition to Real.

**Comment by azat** [comment]
Changes in compare.sh are not required - https://github.com/ClickHouse/ClickHouse/commit/ee7045f41476a3a1efb1ec85260b2be3619d01ff#r100971867

Reverted that hunk.

**Comment by azat** [comment]
Manually downloaded the performance results, and now there are two flamegraphs, for CPU and Real. Differential flamegraph is also there for CPU and Real.

**Review by alexey-milovidov — APPROVED** [review]

**Pull request merged**
