### PR TITLE
Fix issue #17160 by adding show settings like '...'

### PR DESCRIPTION
**Pull request by zhangjmruc**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- New Feature

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Support  `SHOW SETTINGS` statement to show parameters in system.settings. `SHOW CHANGED SETTINGS` and `LIKE/ILIKE` clause are also supported.

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]
Ok, but I'd also add test case where more sophisticated expression is used.
E.g.: SHOW SETTINGS ILIKE '%MEMORY%'

**Comment by alexey-milovidov** [comment]
I would also like to have `SHOW CHANGED SETTINGS` query that will add `WHERE changed = 1`

**Comment by zhangjmruc** [comment]
@alexey-milovidov I have done with code changes according to your two comments and also handled the integration failure related to "SHOW SETTINGS PROFILES". Please review it again and let me know your opinions.

**Comment by alexey-milovidov** [comment]
There is a failure with integration tests, looks related to the changes.
Could you please also merge/rebase with master to fix timeouts of functional tests?

**Review by alexey-milovidov — CHANGES_REQUESTED** [review]
.

**Review by alexey-milovidov — APPROVED** [review]
LGTM

**Pull request merged**
