### PR TITLE
Remove two redundant lines

### PR DESCRIPTION
**Pull request by alesapin**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]
I understand why redundant try/catch is removed, but
I'm out of context, and I don't know what is `unlockSharedData` and why it is not needed here anymore.

**Comment by tavplubix** [comment]
> I'm out of context, and I don't know what is unlockSharedData and why it is not needed here anymore.

It's a key part of "zero copy replication", this lock is supposed to protect from data loss :)

**Comment by alexey-milovidov** [comment]
So, now we avoid unlocking data, and hence having less (or at least not greater) data loss?

**Comment by alesapin** [comment]
test cgroups -- unrelated to changes

**Comment by alesapin** [comment]
`02267_file_globs_schema_inference` -- flaky with aarch64

**Comment by alesapin** [comment]
Stress tests -- even no such key on start, but they fixed in another PR.

**Pull request merged**
