### PR TITLE
Evaluate perf with `-fno-builtin-memcpy`

### PR DESCRIPTION
**Pull request by nickitat**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
I think it is a really bad idea because we expect that small memcpys with constant sizes are substituted by the compiler, for example, in `unalignedLoad`. It is also part of the language standard.

**Comment by nickitat** [comment]
> I think it is a really bad idea because we expect that small memcpys with constant sizes are substituted by the compiler, for example, in `unalignedLoad`. It is also part of the language standard.

we could replace `memcpy` with `__builtin_memcpy` in our code and afaik rewriting will be applied to it. but, yes, it is crutch and it is not clear what to do with the code in contrib.

**Comment by nickitat** [comment]
yeah, results are horrible

**Comment by alexey-milovidov** [comment]
At least we successfully tested our performance tests :)

**Pull request closed without merging**
