### PR TITLE
Add support for Workload identity credentials in AzureBlobStorage

### PR DESCRIPTION
**Pull request by vinay92-ch**
Add support for Workload identity credentials in AzureBlobStorage

### Changelog category (leave one):
- New Feature

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Provide support for AzureBlobStorage function in ClickHouse server to use Azure Workload identity to authenticate against Azure blob storage. If `use_workload_identity` parameter is set in config, [workload identity](https://github.com/Azure/azure-sdk-for-cpp/tree/main/sdk/identity/azure-identity#authenticate-azure-hosted-applications) is used for authentication.

### Documentation entry for user-facing changes

- [ ] Provide support for AzureBlobStorage function in ClickHouse server to use Azure Workload identity to authenticate against Azure blob storage. If `use_workload_identity` parameter is set in config, [workload identity](https://github.com/Azure/azure-sdk-for-cpp/tree/main/sdk/identity/azure-identity#authenticate-azure-hosted-applications) is used for authentication.

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by vinay92-ch** [comment]
CI build is expected to fail. Azure cpp package has not been updated to include latest changes which have workload identity support. Looking into how to do this and also to add tests etc.

**Comment by robot-ch-test-poll3** [comment]
*This is an automated comment for commit d347bec531837af8fd7396603a15fb51c8fc73b6 with description of existing statuses. It's updated for the latest CI running*

[❌ Click here](https://s3.amazonaws.com/clickhouse-test-reports/57881/d347bec531837af8fd7396603a15fb51c8fc73b6/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs Check</td><td>Builds and tests the documentation</td><td>❌ failure</td></tr>
<tbody>
</table>

**Comment by rschu1ze** [comment]
As @vinay92-ch mentioned, the currently pointed-to code state in https://github.com/ClickHouse/azure-sdk-for-cpp is too old and needs to be upgraded. We currently use version 1.3.1 from November 2021, the latest upstream version is 1.10.3 from October 2023. @nickitat upgraded to this latest version (in this PR, thanks) and the build broke. But that is not the main concern.

Whenever an essential 3rd party library is upgraded, stateless, stateful, integration, performance and stress tests can fail. *And* of course the build may break. *And* sometimes it is possible to get rid of obsolete custom patches. I found it easier to do such upgrades in smaller increments and check the diff / changelog between two versions (see the [recent gRPC upgrade](#56853) for an example). On top of that, https://github.com/ClickHouse/azure-sdk-for-cpp doesn't follow the [branch convention](https://clickhouse.com/docs/en/development/contrib) for 3rd party libraries (i.e. `ClickHouse/`-prefixed branch names).

So if you don't mind, I can try an upgrade of azure in separate PRs afterwards, we can push this PR on top.

**Comment by vinay92-ch** [comment]
Thanks @rschu1ze. That would be great if you could please help
Upgrade Azure package as we are currently blocked on Azure testing until this PR is merged.

**Comment by rschu1ze** [comment]
> Upgrade Azure package as we are currently blocked on Azure testing until this PR is merged.

I don't know how critical this is (any deadline?) and if there is not a workaround or fallback to test regardless.

The upgrade v.1.5 looks good, but it is still too old for this PR to work. The upgrade to 1.6 (not sure if this one may suffice) additionally requires an upgrade of ClickHouse's boringssl submodule (the current version lacks symbol `BIO_seek()`), and this will be quite some effort.

**Comment by rschu1ze** [comment]
Okay, it seems that for the 1.6 upgrade we can get away with cherry-picking this upstream patch https://github.com/google/boringssl/commit/e21f272a664ab5785606d2caf5c78737458303e5 into our current boringssl.

**Comment by rschu1ze** [comment]
Azure 1.7+ upgrade: #58075. Unfortunately, that is still too old for this PR, and we need another iteration.

**Comment by rschu1ze** [comment]
The 1.7 upgrade worked, but the 1.8 upgrade fails because upstream added https://github.com/Azure/azure-sdk-for-cpp/pull/4045 and our boringssl can't decide if it wants to be OpenSSL 1.1 or OpenSSL 3. Need to check more closely tomorrow.

**Comment by rschu1ze** [comment]
The problem with 1.8 is that they (azure) added a hard dependency on OpenSSL (1.1 or 3.0) as a cryptographic library. ClickHouse uses Google’s OpenSSL fork boringssl which is supposed to be a drop-in replacement for OpenSSL. The problem is that boringssl pruned some deprecated API and re-introducing it back from OpenSSL would be very fragile. As a result, azure doesn’t find some calls and fails to compile.

I tried to remove some calls to deprecated API from Azure (this technique was used also for other 3rd party libraries which don't support boringssl) but the calls look very central and no guarantees can be given about the resulting Franken-Azure. The real fix would be #56398.

**Comment by vinay92-ch** [comment]
@rschu1ze @SmitaRKulkarni So does this mean that this feature is currently blocked until we can fix https://github.com/ClickHouse/ClickHouse/pull/56398. Do we have any ETA for the fix?

**Comment by rschu1ze** [comment]
@vinay92-ch Yes. I am back from PTO, and will continue on #56398 after looking into a backlog of customer issues. ETA is around 2 or 3 weeks.

**Comment by rschu1ze** [comment]
The Azure submodule was bumped to the latest and greatest 1.11 #62713, feel free to continue this PR.

**Review by SmitaRKulkarni — APPROVED** [review]

**Comment by SmitaRKulkarni** [comment]
CI failures 
Integration tests (asan, old analyzer) [6/6] - will be fixed by https://github.com/ClickHouse/ClickHouse/pull/63286
Stateless tests (release) - will be fixed by https://github.com/ClickHouse/ClickHouse/pull/63297
rest all unrelated failures

**Pull request merged**
