### PR TITLE
Remove old util

### PR DESCRIPTION
**Pull request by alexey-milovidov**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

The docs were updated, see https://clickhouse.com/docs/en/getting-started/example-datasets/wikistat

### CODE REVIEW

**Comment by robot-ch-test-poll2** [comment]
This is an automated comment for commit c3edb57953d41192f3c39034e105f56db000b035 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/53099/c3edb57953d41192f3c39034e105f56db000b035/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Comment by antaljanosbenjamin** [comment]
The Chinese and Russian docs still reference the `wiki-loader`. I don't know what we should do about them, but I wanted to point that out. If you think it is okay, then I am happy to approve.

**Review by antaljanosbenjamin — COMMENTED** [review]
The Chinese and Russian docs still reference the `wiki-loader`. I don't know what we should do about them, but I wanted to point that out. If you think it is okay, then I am happy to approve.

**Comment by alexey-milovidov** [comment]
Replaced with symlinks.

**Review by antaljanosbenjamin — APPROVED** [review]

**Pull request merged**
