### PR TITLE
Fix trivial count query with ConvertingBlockInputStream.

### PR DESCRIPTION
**Pull request by nicelulu**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):

- Bug Fix

Changelog entry (up to few sentences, required except for Non-significant/Documentation categories):

case: ```select count(1) from distributed_table```
and there are more than two shard local table.

DB::Exception: Conversion from AggregateFunction(count) to AggregateFunction(count, UInt8) is not supported: while converting source column `count(1)` to destination column `count(1)`.

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
We can add a test with `SELECT count(1) FROM remote('127.0.0.{1,2}')`?

**Comment by nicelulu** [comment]
> We can add a test with `SELECT count(1) FROM remote('127.0.0.{1,1,2}')` or something like that?

I added some tests.

**Comment by alesapin** [comment]
and they failed :(

**Comment by nicelulu** [comment]
> and they failed :(

I'll get the latest code and try it. This test is fine with me locally.

**Review by alexey-milovidov — APPROVED** [review]

**Comment by KochetovNicolai** [comment]
Conflicts with 19.16

**Pull request merged**
