### PR TITLE
Restore kafka on freebsd

### PR DESCRIPTION
**Pull request by snar**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=ru

Changelog category (leave one):
- Build/Testing/Packaging Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Restore Kafka input in FreeBSD builds

Detailed description:

When migrating from rdkafka to cppkafka, FreeBSD build was disabled due to bug
in cppkafka. Since then, cppkafka is fixed (https://github.com/mfontanini/cppkafka/pull/172),
so this is not an issue anymore.
Second change fixes incorrect assumption that everything that is not Apple is Linux
and have pthread_setname_np function: FreeBSD have it's specific variant 
(pthread_set_name_np), so this assumption went to broken build.

### CODE REVIEW

**Comment by qoega** [comment]
Nice. We will test that build is successful, but CI does not run on freebsd - you should check the version that will be built in CI manually

**Comment by qoega** [comment]
@snar Will you check build from https://clickhouse-builds.s3.yandex.net/18924/af2fa524366a029793de56f2fa38a6ddc532d1c7/clickhouse_special_build_check/report.html ?

**Review by qoega — APPROVED** [review]

**Comment by snar** [comment]
> @snar Will you check build from https://clickhouse-builds.s3.yandex.net/18924/af2fa524366a029793de56f2fa38a6ddc532d1c7/clickhouse_special_build_check/report.html ?

This is Linux build, i guess ? Then it makes a little sense to test it as it will neither run on FreeBSD (even within
emulator, already tried that) nor change FreeBSD behaviour (Kafka was disabled for FreeBSD only, not for Linux).

PS: this pull was tested on FreeBSD before submission: manually applied against 20.12.4.5, rebuilt,
reinstalled and works just fine.

**Comment by alexey-milovidov** [comment]
@snar This is FreeBSD build, see `clang-11-freebsd`. Just download the binary and run.

**Comment by snar** [comment]
OOps, sorry, missed that :( Downloaded, all tests passed. Thanks!

**Pull request merged**
