### PR TITLE
Add keytab parameter in kerberos section of config.xml

### PR DESCRIPTION
**Pull request by rvasin**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Added possibility to set path to service keytab file in `keytab` parameter in `kerberos` section of config.xml.

### CODE REVIEW

**Comment by rvasin** [comment]
@yakov-olkhovskiy I remember you were reviewer for my pull request related to Kerberos in June. Maybe you could be also reviewer of this pull request.

**Comment by rvasin** [comment]
@yakov-olkhovskiy or @rschu1ze Could you please assign 'can be tested' label to this PR?

**Comment by rvasin** [comment]
I see that almost all tests were successfully passed (except for non-related ones). Could someone review this PR?

**Comment by rschu1ze** [comment]
@yakov-olkhovskiy I suppose you are a lot more familiar with this code area? If not, feel free to assign to me.

**Comment by rvasin** [comment]
In total C++ part is quite simple:  there is just one call of function `krb5_gss_register_acceptor_identity`  to load the keytab. 
Integration test is a more complex part (more code, but not quite complex).

**Comment by yakov-olkhovskiy** [comment]
@rschu1ze yes, I will take a look some later.

**Review by yakov-olkhovskiy — APPROVED** [review]

**Pull request merged**
