### PR TITLE
Add Function dotProduct for array

### LINKED ISSUE #48828: `dotProduct` should work for arrays
**Use case**

Vector search databases.

**Implementation**

Currently, it works only for tuples.

```
SELECT dotProduct([1., 2.], [3., 4.])
```

Although it can be easily emulated by the following expression:
```
arraySum((x, y) -> x * y, arr1, arr2)
```

And this expression is quite fast, but there is one downside: if the arguments have Float32 data type, the intermediate expressions, and the result will have Float64 data type.

A dedicated `dotProduct` implementation should keep the calculation within the same data type.
Additionally, it could be further optimized.

### PR DESCRIPTION
**Pull request by FFFFFFFHHHHHHH**
### Changelog category (leave one):
- New Feature

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Function `dotProduct` work for array.

closes #48828

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]

**Review by nickitat — APPROVED** [review]

**Comment by FFFFFFFHHHHHHH** [comment]
> > 
> 
> OK,I'll fix it later.
> 
> > Unconditionally casting integers to float can lead to some unexpected results:
> > ```
> > SELECT dotProduct(tuple(12345678901234567), tuple(1))
> > 12345678901234567
> > 
> > SELECT dotProduct([12345678901234567], [1])
> > 12345678901234568
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I think that this behaviour should be, at least, clearly documented.
>

**Comment by FFFFFFFHHHHHHH** [comment]
@alexey-milovidov Hello, for the accuracy problem above, should I do a precalculation like a tuple to get the least satisfying type? But I think that would be less efficient because the array might vary in length, unlike a tuple, which uses more vectorization because of it's same length. Or maybe I need to document that?

**Comment by robot-clickhouse** [comment]
This is an automated comment for commit d3e027390d498f80e8cf860885420d4ffdc04b5b with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/49050/d3e027390d498f80e8cf860885420d4ffdc04b5b/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Docs Check</td><td>Builds and tests the documentation</td><td>🟡 pending</td></tr>
</table>

**Comment by FFFFFFFHHHHHHH** [comment]
> 



> > Hello, for the accuracy problem above, should I do a precalculation like tuple's `dotProduct` to get the least satisfying type? But I think that would be less efficient because the array might vary in length, unlike a tuple, which uses more vectorization because of it's same length. Or maybe I need to document that?
> 
> Handling arrays should be easier than tuples (in this regard). You can simply check the nested type of the array itself, because arrays don't contain mixed types. i.e. if the array is Array(UInt64) you can assume that all elements are UInt64.

Yes, but how to check if the data will overflow after the dot product? Even though the data originally is UInt32, it may overflow UInt256 during the dot product. 
In tuple's `dotProduct`, by taking the dot product in getReturnType to get least satisfying type. But I am concerned about the performance impact of this implementation

> > Hello, for the accuracy problem above, should I do a precalculation like tuple's `dotProduct` to get the least satisfying type? But I think that would be less efficient because the array might vary in length, unlike a tuple, which uses more vectorization because of it's same length. Or maybe I need to document that?
> 
> Handling arrays should be easier than tuples (in this regard). You can simply check the nested type of the array itself, because arrays don't contain mixed types. i.e. if the array is Array(UInt64) you can assume that all elements are UInt64.

I see what you mean, thanks for your opinion, this implementation is much better

**Comment by FFFFFFFHHHHHHH** [comment]
> > Hello, for the accuracy problem above, should I do a precalculation like tuple's `dotProduct` to get the least satisfying type? But I think that would be less efficient because the array might vary in length, unlike a tuple, which uses more vectorization because of it's same length. Or maybe I need to document that?
> 
> Handling arrays should be easier than tuples (in this regard). You can simply check the nested type of the array itself, because arrays don't contain mixed types. i.e. if the array is Array(UInt64) you can assume that all elements are UInt64.


I see what you mean, thanks for your opinion, this is much better!

**Comment by FFFFFFFHHHHHHH** [comment]
> > Hello, for the accuracy problem above, should I do a precalculation like tuple's `dotProduct` to get the least satisfying type? But I think that would be less efficient because the array might vary in length, unlike a tuple, which uses more vectorization because of it's same length. Or maybe I need to document that?
> 
> Handling arrays should be easier than tuples (in this regard). You can simply check the nested type of the array itself, because arrays don't contain mixed types. i.e. if the array is Array(UInt64) you can assume that all elements are UInt64.

@aiven-sal I'm sorry, I think there's difficult to determine the type of the result unless use `Float32/Float64`.

In tuple's dotProduct, we can get the least satisfying type because all row tuple has same length and type.
i.e. `dotProduct(tuple(UInt32, UInt8), tuple(UInt8, UInt8))`, we can get the least result satisfying type `UInt64` by using `plus/multiply->getReturnType`.

But in array's `dotProduct`, we can't get the least satisfying type because of its variable length.
i.e. 
In first row, there are two 1-length array  : `dotProduct([UInt32], [UInt32])`, we can use `UInt64` to save the result.
In second row, there are two 3-length array  : `dotProduct([UInt32, UInt32, UInt32], [UInt32, UInt32, UInt32])`, we can't use `UInt64` to save the result because of overflow. Only here float.

Therefore,  I can only use `Float32/Float64` in function `getReturnType` to ensure that there is no overflow , because of array's variable length.

Please correct me if I'm wrong :)

**Comment by alexey-milovidov** [comment]
Let's promote to the next type for integers (in the same way how it is done for a single `+` operation).
For example, the dot product of UInt8 will operate and return the UInt16 data type, no matter the overflow.

For floating point types, let's do a somewhat controversial solution: it should not promote the types at all.
For example, dot product of Float32 arrays will operate in Float32 and return Float32.

**Comment by nickitat** [comment]
@FFFFFFFHHHHHHH pls check fuzzing report

**Pull request merged**
