### PR TITLE
Refactoring for UserDefinedSQLObjectsLoader

### PR DESCRIPTION
**Pull request by chizhonkova**
We use СlickHouse as a library and in this case it is impossible to add our own SQL UDF loader, because all current loaders are friends of UserDefinedSQLFunctionFactory class. This refactoring is done to solve the problem.

### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Refactor UserDefinedSQL* classes  to make it possible to add SQL UDF storages which are different from ZooKeeper and Disk.

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by robot-ch-test-poll1** [comment]
*This is an automated comment for commit 6713b762e02ce80ada486c89c941823c7f237f2c with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/57752/6713b762e02ce80ada486c89c941823c7f237f2c/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td><a href="https://github.com/ClickHouse/ClickHouse/actions/runs/7169669839">✅ success</a></td></tr>
<tbody>
</table>
</details>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/57752/6713b762e02ce80ada486c89c941823c7f237f2c/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Comment by chizhonkova** [comment]
Seems like tests failures are unrelated:
1. test_replicated_merge_tree_s3_zero_copy/test.py::test_drop_table
2. 02479_mysql_connect_to_self

**Comment by chizhonkova** [comment]
@pufit could you, please, tell when you will have a look at this pr?

**Comment by pufit** [comment]
Hi @chizhonkova! Sorry to keep you waiting! I'll take a look at it today!

**Review by pufit — APPROVED** [review]
LGTM!

**Comment by pufit** [comment]
Flaky tests:
- 02479_race_condition_between_insert_and_droppin_mv (hung)
- test_replicated_merge_tree_s3_zero_copy/test.py::test_drop_table (https://aretestsgreenyet.com/)
- 02479_mysql_connect_to_self (probably just a flap of MySQL in CI).

**Pull request merged**
