### PR TITLE
Added link to native python driver

### PR DESCRIPTION
**Pull request by xzkostyan**

### CODE REVIEW

**Comment by robot-metrika-test** [comment]
Can one of the admins verify this patch?

**Comment by robot-metrika-test** [comment]
Can one of the admins verify this patch?

**Comment by alexey-milovidov** [comment]
Thanks!

**Comment by alexey-milovidov** [comment]
And what about english file?

**Comment by xzkostyan** [comment]
Sorry, forgot about it. Here is PR with english docs: #1104.

**Pull request merged**
