### PR TITLE
Add `abort_on_error=1` to `TSAN_OPTIONS`

### PR DESCRIPTION
**Pull request by nickitat**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by robot-clickhouse** [comment]
This is an automated comment for commit 06717fa3ddf7f96cb2e6c34ed8454df05bb686cb with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/53065/06717fa3ddf7f96cb2e6c34ed8454df05bb686cb/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Comment by nickitat** [comment]
https://github.com/ClickHouse/ClickHouse/blob/06717fa3ddf7f96cb2e6c34ed8454df05bb686cb/docker/test/base/Dockerfile#L1

@Felixoid how to do it?

**Review by alexey-milovidov — APPROVED** [review]

**Comment by Felixoid** [comment]
https://s3.amazonaws.com/clickhouse-test-reports/53065/555c90a50c200a99d143485a950794238a8dd11c/push_multi-arch_images_to_dockerhub.html

everything is published automatically and used in the CI. You can ignore the comment

**Comment by nickitat** [comment]
> https://s3.amazonaws.com/clickhouse-test-reports/53065/555c90a50c200a99d143485a950794238a8dd11c/push_multi-arch_images_to_dockerhub.html
> 
> everything is published automatically and used in the CI. You can ignore the comment

but what if I open a pr with some completely erroneous changes in dockerfile-s (but still `docker build` could run successfully) - will they all be automatically pushed to registry too?

**Comment by Felixoid** [comment]
https://github.com/ClickHouse/ClickHouse/blob/master/tests/ci/docker_images_check.py#L108-L186
It takes all changed files, looks for modified images, and builds a dependency tree to build and push everything. Then it uses these changed images in the CI

**Comment by alesapin** [comment]
What is the difference with `halt_on_error=1` and why we need them both?

**Comment by nickitat** [comment]
> What is the difference with `halt_on_error=1` and why we need them both?


abort_on_error | false (true on Darwin) | If set, the tool calls abort() instead of _exit() after printing the error report.
-- | -- | --
halt_on_error | 0 | Exit after first reported error

so I think it should help with the problem that sometimes tsan only prints report without aborting the process and it is almost impossible to find a query that produced the error and investigate it.

**Pull request merged**
