### PR TITLE
Fixed the issue "Method createColumn() is not implemented for data type Set"

### LINKED ISSUE #7799: 19.17 Method createColumn() is not implemented for data type Set.
The test case:
```
ClickHouse client version 19.17.2.4 (official build).
Connecting to localhost:9000 as user default.
Connected to ClickHouse server version 19.17.2 revision 54428.

:) select count()
FROM   system.query_log
ANY LEFT JOIN (select 1 as port) USING port
PREWHERE type in (1)
WHERE event_date = today()

SELECT count()
FROM system.query_log
ANY LEFT JOIN
(
    SELECT 1 AS port
) USING (port)
PREWHERE type IN (1)
WHERE event_date = today()

Received exception from server (version 19.17.2):
Code: 48. DB::Exception: Received from localhost:9000. DB::Exception: Method createColumn() is not implemented for data type Set.

0 rows in set. Elapsed: 0.002 sec.
```

### PR DESCRIPTION
**Pull request by alexey-milovidov**
Changelog category (leave one):
- Bug Fix

Changelog entry (up to few sentences, required except for Non-significant/Documentation categories):
Fixed the issue "Method createColumn() is not implemented for data type Set". This fixes #7799.

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
@4ertus2 has the hypothesis that the mechanics is something like that:
- we create prepared set (DataTypeSet) for IN;
- condition with set is pushed down to subquery;
- we analyze data types in subquery, but it's unexpected that one of the data types is Set.

**Comment by orloffv** [comment]
Can u check my case? https://github.com/ClickHouse/ClickHouse/issues/7799#issuecomment-560025636

**Comment by alexey-milovidov** [comment]
@orloffv It isn't fixed :( I'll try to add the fix to this PR.

**Comment by alexey-milovidov** [comment]
> I'll try to add the fix to this PR.

In next PR.

**Comment by orloffv** [comment]
@alexey-milovidov i'v created new issue with my problem, because current issue - closed
https://github.com/ClickHouse/ClickHouse/issues/8689

**Pull request merged**
