### PR TITLE
Added RowBinaryWithNamesAndTypes format

### PR DESCRIPTION
**Pull request by DarkWanderer**
* Extended BinaryRowOutputStream and BinaryRowInputStream with flags allowing to output names/types of columns
* Added new input/output format - RowBinaryWithNamesAndTypes
* Updated docs

**Category:** New Feature
**Short description:** Added new input/output format: RowBinaryWithNamesAndTypes

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]
:+1:

**Comment by alexey-milovidov** [comment]
Missing test.
We can create a test (in `dbms/tests/queries` directory) to just ensure that the format exists and the output is as expected.

**Review by alexey-milovidov — CHANGES_REQUESTED** [review]
Let's also implement input format.
It will be useful for table dumps, that can be loaded back and parsed by separate tools.

**Comment by alexey-milovidov** [comment]
This PR fixes #929

**Comment by DarkWanderer** [comment]
Added input format support + test for output format.

TODO: test for input format

**Comment by filimonov** [comment]
BTW: if there some chance to wrap AggregateFunction states somehow in RowBinary? For example - add LEB128-encoded length prefix before the value, just to be able to skip that column if it comes in the output.

It it will be added just for new format ( RowBinaryWithNamesAndTypes ) the no backward compatibility issues will appear.

That will make possible to do the roundtrip of RowBinary, and to build clients which can pass AggregateFunction states back and forward safely.

**Comment by alexey-milovidov** [comment]
> BTW: if there some chance to wrap AggregateFunction states somehow in RowBinary? For example - add LEB128-encoded length prefix before the value, just to be able to skip that column if it comes in the output.

> If it will be added just for new format ( RowBinaryWithNamesAndTypes ) then no backward compatibility issues will appear.

> That will make possible to do the roundtrip of RowBinary, and to build clients which can pass AggregateFunction states back and forward safely.

Better don't do it to avoid confusion with RowBinary format. Also note that writing LEB128 prefix requires extra copy. We've almost finished development of Protobuf format that allows to read and write AggregateFunctions as `bytes`.

**Comment by alexey-milovidov** [comment]
Input format reminds me the weird issue #3469 that should be fixed first.

**Pull request merged**
