### PR TITLE
Disable getConstantResultForNonConstArguments for IS NULL with old analyzer

### PR DESCRIPTION
**Pull request by KochetovNicolai**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix `Unknown identifier` and `Column is not under aggregate function` errors for queries with the expression `(column IS NULL).` The bug was triggered by #65088, with the disabled analyzer only.

### CODE REVIEW

**Review by vdimir — APPROVED** [review]

**Comment by vdimir** [comment]
> Stateless tests (release, old analyzer, s3, DatabaseReplicated) [1/3] — fail: 1, passed: 2231, skipped: 44 [Details](https://s3.amazonaws.com/clickhouse-test-reports/66654/8e013a1c5938e7cecba5804ac8e9f653a95e4ddc/stateless_tests__release__old_analyzer__s3__databasereplicated__[1_3].html)

Test failure related
```
2024-07-18 04:52:49 Reason: result differs with reference:  
2024-07-18 04:52:49 --- /usr/share/clickhouse-test/queries/0_stateless/02892_orc_filter_pushdown.reference	2024-07-18 04:28:56.738480967 +1000
2024-07-18 04:52:49 +++ /tmp/clickhouse-test/0_stateless/02892_orc_filter_pushdown.stdout	2024-07-18 04:52:49.789840290 +1000
2024-07-18 04:52:49 @@ -206,7 +206,7 @@
2024-07-18 04:52:49  select count(), min(negative_or_null), max(negative_or_null) from file('02892.orc', ORC, 'number UInt64, negative_or_null Int64') where (negative_or_null < -500);
2024-07-18 04:52:49  596	-1099	-501
2024-07-18 04:52:49  select count(), sum(number) from file('02892.orc', ORC, 'number UInt64, negative_or_null Int64') where indexHint(negative_or_null is null);
2024-07-18 04:52:49 -0	0
2024-07-18 04:52:49 +1000	499500
2024-07-18 04:52:49  select count(), min(negative_or_null), max(negative_or_null) from file('02892.orc', ORC, 'number UInt64, negative_or_null Int64') where (negative_or_null is null);
2024-07-18 04:52:49  0	0	0
2024-07-18 04:52:49  select count(), sum(number) from file('02892.orc', ORC, 'number UInt64, negative_or_null Int64') where indexHint(negative_or_null in (0, -1, -10, -100, -1000));
2024-07-18 04:52:49 
```

**Comment by Algunenano** [comment]
Fuzzer reports look related. E.g:

```
2024.07.18 19:12:55.882492 [ 186 ] {94ac332b-3148-4135-8cb4-6adeeef12c51} <Debug> executeQuery: (from [::ffff:127.0.0.1]:49728) (comment: /workspace/ch/tests/queries/0_stateless/03206_is_null_constant_result_old_analyzer_bug.sql) SELECT CAST(indexHint('02892.orc', 9, 9, 9, toUInt256(9), 9, 9, toLowCardinality(9), 9, 9, 9, 9, 9, 9, 9, 9, 9), 'Boolean'), now() FROM numbers(2) GROUP BY CAST(number IS NULL, 'Boolean'), now() FORMAT `Null` (stage: Complete)
2024.07.18 19:12:55.887498 [ 186 ] {94ac332b-3148-4135-8cb4-6adeeef12c51} <Trace> Planner: Query to stage Complete
2024.07.18 19:12:55.888318 [ 186 ] {94ac332b-3148-4135-8cb4-6adeeef12c51} <Trace> Planner: Query from stage FetchColumns to stage Complete
2024.07.18 19:12:55.889454 [ 186 ] {94ac332b-3148-4135-8cb4-6adeeef12c51} <Fatal> : Logical error: 'Bad cast from type DB::ColumnVector<char8_t> to DB::ColumnLowCardinality'.
2024.07.18 19:12:55.930509 [ 735 ] {} <Trace> system.text_log_sender.DistributedInsertQueue.default: Finished processing `/workspace/db/store/63c/63c5421d-59f8-4417-8a65-0e05cdadd358/shard1_replica1/254.bin` (took 1394 ms)
2024.07.18 19:12:55.930690 [ 735 ] {} <Trace> system.text_log_sender.DistributedInsertQueue.default/Bg: Execution took 1394 ms.
2024.07.18 19:12:56.000212 [ 861 ] {} <Trace> AsynchronousMetrics: MemoryTracking: was 1.76 GiB, peak 2.17 GiB, free memory in arenas 0.00 B, will set to 1.77 GiB (RSS), difference: 16.07 MiB
2024.07.18 19:12:56.021202 [ 186 ] {94ac332b-3148-4135-8cb4-6adeeef12c51} <Fatal> : Stack trace (when copying this message, always include the lines below):

0. ./contrib/llvm-project/libcxx/include/exception:141: Poco::Exception::Exception(String const&, int) @ 0x000000001df05703
1. ./build_docker/./src/Common/Exception.cpp:110: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000f7f8cf5
2. DB::Exception::Exception(PreformattedMessage&&, int) @ 0x00000000073e23a0
3. DB::Exception::Exception<String, String>(int, FormatStringHelperImpl<std::type_identity<String>::type, std::type_identity<String>::type>, String&&, String&&) @ 0x00000000073e4686
4. _Z11typeid_castIRKN2DB20ColumnLowCardinalityEKNS0_7IColumnEQsr3stdE14is_reference_vIT_EES6_RT0_ @ 0x000000000794043a
5. COW<DB::IColumn>::immutable_ptr<DB::IColumn> std::__function::__policy_invoker<COW<DB::IColumn>::immutable_ptr<DB::IColumn> (std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>>&, std::shared_ptr<DB::IDataType const> const&, DB::ColumnNullable const*, unsigned long)>::__call_impl<std::__function::__default_alloc_func<DB::(anonymous namespace)::FunctionCast::prepareUnpackDictionaries(std::shared_ptr<DB::IDataType const> const&, std::shared_ptr<DB::IDataType const> const&) const::'lambda0'(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>>&, std::shared_ptr<DB::IDataType const> const&, DB::ColumnNullable const*, unsigned long), COW<DB::IColumn>::immutable_ptr<DB::IColumn> (std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>>&, std::shared_ptr<DB::IDataType const> const&, DB::ColumnNullable const*, unsigned long)>>(std::__function::__policy_storage const*, std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>>&, std::shared_ptr<DB::IDataType const> const&, DB::ColumnNullable const*, unsigned long) @ 0x00000000077fc5ed
6. DB::(anonymous namespace)::ExecutableFunctionCast::executeImpl(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long) const @ 0x0000000007535787
7. DB::IExecutableFunction::executeDryRunImpl(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long) const @ 0x0000000007422824
8. DB::IExecutableFunction::executeWithoutLowCardinalityColumns(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x00000000085221c7
9. DB::IExecutableFunction::defaultImplementationForConstantArguments(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x0000000008521c9e
10. DB::IExecutableFunction::executeWithoutLowCardinalityColumns(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x0000000008522154
11. DB::IExecutableFunction::executeWithoutSparseColumns(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x0000000008522e97
12. DB::IExecutableFunction::execute(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x0000000008524acf
13. ./contrib/boost/boost/smart_ptr/intrusive_ptr.hpp:117: DB::ActionsDAG::evaluatePartialResult(std::unordered_map<DB::ActionsDAG::Node const*, DB::ColumnWithTypeAndName, std::hash<DB::ActionsDAG::Node const*>, std::equal_to<DB::ActionsDAG::Node const*>, std::allocator<std::pair<DB::ActionsDAG::Node const* const, DB::ColumnWithTypeAndName>>>&, std::vector<DB::ActionsDAG::Node const*, std::allocator<DB::ActionsDAG::Node const*>> const&, unsigned long, bool) @ 0x0000000017082ca6
14. ./build_docker/./src/Interpreters/ActionsDAG.cpp:0: DB::ActionsDAG::updateHeader(DB::Block const&) const @ 0x00000000170810bf
15. ./build_docker/./src/Processors/Transforms/ExpressionTransform.cpp:10: DB::ExpressionTransform::transformHeader(DB::Block const&, DB::ActionsDAG const&) @ 0x000000001a0b33ea
16. ./build_docker/./src/Processors/QueryPlan/ExpressionStep.cpp:32: DB::ExpressionStep::ExpressionStep(DB::DataStream const&, std::shared_ptr<DB::ActionsDAG> const&) @ 0x000000001a2f77b0
17. ./contrib/llvm-project/libcxx/include/string:1499: DB::(anonymous namespace)::addExpressionStep(DB::QueryPlan&, std::shared_ptr<DB::ActionsAndProjectInputsFlag> const&, String const&, std::vector<std::shared_ptr<DB::ActionsDAG>, std::allocator<std::shared_ptr<DB::ActionsDAG>>>&) @ 0x0000000017a46b41
18. ./contrib/llvm-project/libcxx/include/string:1499: DB::Planner::buildPlanForQueryNode() @ 0x0000000017a3ff05
19. ./build_docker/./src/Planner/Planner.cpp:1261: DB::Planner::buildQueryPlanIfNeeded() @ 0x0000000017a38f03
20. ./src/Planner/Planner.h:44: DB::InterpreterSelectQueryAnalyzer::getQueryPlan() @ 0x0000000017a3633b
21. ./build_docker/./src/Interpreters/executeQuery.cpp:1175: DB::executeQueryImpl(char const*, char const*, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum, DB::ReadBuffer*) @ 0x0000000017e9c69e
22. ./build_docker/./src/Interpreters/executeQuery.cpp:1390: DB::executeQuery(String const&, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum) @ 0x0000000017e98958
23. ./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:612: DB::TCPHandler::runImpl() @ 0x0000000019c2dd59
24. ./build_docker/./src/Server/TCPHandler.cpp:2368: DB::TCPHandler::run() @ 0x0000000019c4b768
25. ./build_docker/./base/poco/Net/src/TCPServerConnection.cpp:57: Poco::Net::TCPServerConnection::start() @ 0x000000001e0121a3
26. ./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:48: Poco::Net::TCPServerDispatcher::run() @ 0x000000001e012a12
27. ./build_docker/./base/poco/Foundation/src/ThreadPool.cpp:219: Poco::PooledThread::run() @ 0x000000001df8b283
28. ./build_docker/./base/poco/Foundation/src/Thread.cpp:46: Poco::(anonymous namespace)::RunnableHolder::run() @ 0x000000001df89550
29. ./base/poco/Foundation/include/Poco/SharedPtr.h:231: Poco::ThreadImpl::runnableEntry(void*) @ 0x000000001df87a2a
30. __tsan_thread_start_func @ 0x000000000735af2f
31. ? @ 0x00007f01f61aeac3
```

**Comment by KochetovNicolai** [comment]
Repro
`select count() GROUP BY CAST(indexHint(toLowCardinality(9)), 'String')`

**Comment by KochetovNicolai** [comment]
Repro fails in with and without the PR. I will make a separate fix.

**Pull request merged**
