### PR TITLE
Improvements in PODArray

### PR DESCRIPTION
**Pull request by alexey-milovidov**
Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Detailed description / Documentation draft:

Added a test. Implement insert, assign methods for iterators of different type.
Avoid overallocation in constructor.
Added reserve_exact and resize_exact methods.

Improve performance of `clang` build.
(It may lead to significant overall improvements, because we have so many queries with `materialize` in performance tests).

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
6 slower performance tests don't look good.

**Comment by alexey-milovidov** [comment]
I see no difference in clang release build for "parallel final" test.

**Comment by alexey-milovidov** [comment]
> Performance — 1 faster, 7 slower

Now totally different set of tests become slower.

**Comment by akuzm** [comment]
> > Performance — 1 faster, 7 slower
> 
> Now totally different set of tests become slower.
I'm looking at these reports:
https://clickhouse-test-reports.s3.yandex.net/12278/8092f9f8618955e2a4311149acaaa2edc1f82b3a/performance_comparison/report.html#fail1
https://clickhouse-test-reports.s3.yandex.net/12278/edb68b7f6b07f77411c033a16bfbde4f8f9018b4/performance_comparison/report.html#fail1

It's not totally different, parallel_final no. 2, 3, 19, array_element no. 1 are slower in both runs.
Flame graphs say that `ColumnVector::filter` became slower, the reason might be that the size is not power of two now, so you added it back in the second PR? Sounds reasonable. Maybe we could only round to small powers of two -- if the number is big enough, the unrolled loop should be efficient enough anyway.

**Review by akuzm — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
@akuzm This PR does not affect `size`, only `capacity`.
I can only suspect cache alignment or differences in false sharing but there are no differences in perf events metrics.

**Comment by akuzm** [comment]
Merged all parts of this except ALWAYS_INLINE which is also in variant 2 PR.

**Pull request closed without merging**
