### PR TITLE
Better writeInt

### PR DESCRIPTION
**Pull request by amosbird**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Category (leave one):
- Performance Improvement

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
Build has failed.

**Comment by amosbird** [comment]
Performance improves ranging from 1% - 10% . However for tiny strings (length <= 2) there are regressions.

```
Testing SQL : SELECT count() FROM test.hits WHERE NOT ignore(toString(<column>)) SETTINGS max_threads = 1

Column                              Before :  fallback      hybrid    After :  fallback       hybrid  

WatchID                                       0.534000,    0.302000,           0.342000,     0.278000, 
JavaEnable                                    0.093000,    0.053000,           0.088000,     0.060000, 
GoodEvent                                     0.116000,    0.054000,           0.098000,     0.056000, 
CounterID                                     0.255000,    0.129000,           0.175000,     0.111000, 
ClientIP                                      0.342000,    0.163000,           0.210000,     0.139000, 
RegionID                                      0.186000,    0.103000,           0.146000,     0.090000, 
UserID                                        0.546000,    0.306000,           0.340000,     0.281000, 
CounterClass                                  0.072000,    0.054000,           0.059000,     0.054000, 
OS                                            0.124000,    0.059000,           0.114000,     0.064000, 
UserAgent                                     0.110000,    0.058000,           0.103000,     0.063000, 
Refresh                                       0.065000,    0.050000,           0.058000,     0.057000, 
IsRobot                                       0.063000,    0.049000,           0.056000,     0.056000, 
ResolutionWidth                               0.179000,    0.096000,           0.142000,     0.087000, 
ResolutionHeight                              0.171000,    0.089000,           0.138000,     0.083000, 
ResolutionDepth                               0.124000,    0.055000,           0.114000,     0.064000, 
FlashMajor                                    0.102000,    0.055000,           0.095000,     0.060000, 
FlashMinor                                    0.074000,    0.052000,           0.065000,     0.058000, 
NetMajor                                      0.063000,    0.049000,           0.056000,     0.056000, 
NetMinor                                      0.063000,    0.049000,           0.056000,     0.056000, 
UserAgentMajor                                0.143000,    0.064000,           0.120000,     0.068000, 
CookieEnable                                  0.091000,    0.048000,           0.087000,     0.055000, 
JavascriptEnable                              0.091000,    0.048000,           0.086000,     0.055000, 
IsMobile                                      0.070000,    0.051000,           0.063000,     0.058000, 
MobilePhone                                   0.069000,    0.051000,           0.062000,     0.057000, 
IPNetworkID                                   0.258000,    0.138000,           0.176000,     0.123000, 
TraficSourceID                                0.145000,    0.085000,           0.121000,     0.083000, 
SearchEngineID                                0.081000,    0.057000,           0.068000,     0.062000, 
SearchPhrase                                  0.071000,    0.067000,           0.066000,     0.066000, 
AdvEngineID                                   0.061000,    0.048000,           0.055000,     0.055000, 
IsArtifical                                   0.092000,    0.058000,           0.084000,     0.065000, 
WindowClientWidth                             0.175000,    0.098000,           0.140000,     0.093000, 
WindowClientHeight                            0.163000,    0.086000,           0.133000,     0.083000, 
ClientTimeZone                                0.165000,    0.086000,           0.134000,     0.080000, 
SilverlightVersion1                           0.082000,    0.053000,           0.074000,     0.060000, 
SilverlightVersion2                           0.078000,    0.052000,           0.071000,     0.059000, 
SilverlightVersion3                           0.130000,    0.090000,           0.100000,     0.083000, 
SilverlightVersion4                           0.064000,    0.051000,           0.056000,     0.057000, 
CodeVersion                                   0.170000,    0.088000,           0.134000,     0.078000, 
IsLink                                        0.068000,    0.051000,           0.060000,     0.058000, 
IsDownload                                    0.061000,    0.049000,           0.055000,     0.056000, 
IsNotBounce                                   0.083000,    0.056000,           0.074000,     0.063000, 
FUniqID                                       0.432000,    0.253000,           0.280000,     0.231000, 
HID                                           0.332000,    0.168000,           0.213000,     0.152000, 
IsOldCounter                                  0.060000,    0.048000,           0.054000,     0.055000, 
IsEvent                                       0.060000,    0.048000,           0.054000,     0.055000, 
IsParameter                                   0.064000,    0.049000,           0.059000,     0.056000, 
DontCountHits                                 0.093000,    0.058000,           0.085000,     0.065000, 
WithHash                                      0.065000,    0.048000,           0.059000,     0.055000, 
Age                                           0.118000,    0.057000,           0.107000,     0.064000, 
Sex                                           0.096000,    0.054000,           0.090000,     0.061000, 
Income                                        0.096000,    0.054000,           0.089000,     0.061000, 
Interests                                     0.125000,    0.079000,           0.104000,     0.079000, 
Robotness                                     0.079000,    0.055000,           0.070000,     0.060000, 
RemoteIP                                      0.342000,    0.163000,           0.211000,     0.141000, 
WindowName                                    0.177000,    0.116000,           0.151000,     0.103000, 
OpenerName                                    0.125000,    0.083000,           0.115000,     0.069000, 
HistoryLength                                 0.138000,    0.078000,           0.117000,     0.080000, 
HTTPError                                     0.064000,    0.051000,           0.056000,     0.057000, 
SendTiming                                    0.160000,    0.110000,           0.146000,     0.099000, 
DNSTiming                                     0.144000,    0.113000,           0.137000,     0.106000, 
ConnectTiming                                 0.159000,    0.123000,           0.151000,     0.116000, 
ResponseStartTiming                           0.195000,    0.137000,           0.179000,     0.128000, 
ResponseEndTiming                             0.197000,    0.142000,           0.182000,     0.131000, 
FetchTiming                                   0.162000,    0.124000,           0.152000,     0.116000, 
RedirectTiming                                0.136000,    0.111000,           0.129000,     0.104000, 
DOMInteractiveTiming                          0.189000,    0.132000,           0.168000,     0.119000, 
DOMContentLoadedTiming                        0.178000,    0.126000,           0.164000,     0.114000, 
DOMCompleteTiming                             0.160000,    0.110000,           0.145000,     0.096000, 
LoadEventStartTiming                          0.160000,    0.110000,           0.144000,     0.096000, 
LoadEventEndTiming                            0.153000,    0.104000,           0.142000,     0.094000, 
NSToDOMContentLoadedTimin                     0.183000,    0.127000,           0.163000,     0.114000, 
FirstPaintTiming                              0.164000,    0.114000,           0.148000,     0.099000, 
RedirectCount                                 0.122000,    0.075000,           0.101000,     0.077000, 
SocialSourceNetworkID                         0.062000,    0.049000,           0.056000,     0.056000, 
ParamPrice                                    0.069000,    0.074000,           0.069000,     0.080000, 
ParamCurrencyID                               0.064000,    0.051000,           0.056000,     0.057000, 
HasGCLID                                      0.060000,    0.048000,           0.054000,     0.055000, 
RefererHash                                   0.592000,    0.346000,           0.393000,     0.331000, 
URLHash                                       0.604000,    0.358000,           0.407000,     0.344000, 
CLID                                          0.074000,    0.065000,           0.064000,     0.065000, 
YCLID                                         0.072000,    0.067000,           0.064000,     0.069000, 
RequestNum                                    0.176000,    0.104000,           0.143000,     0.092000, 
RequestTry                                    0.096000,    0.057000,           0.086000,     0.064000, 

```

**Comment by amosbird** [comment]
Also fixed a potential stack underflow (int128 might have 40 digits)

**Comment by amosbird** [comment]
optimized based on https://github.com/amdn/itoa 

```
Testing SQL : SELECT count() FROM test.hits WHERE NOT ignore(toString(<column>)) SETTINGS max_threads = 1

Column                              Before :  fallback      hybrid    After :  fallback       hybrid       optimized (based on https://github.com/amdn/itoa)

WatchID                                       0.534000,    0.302000,           0.342000,     0.278000,     0.192000,
JavaEnable                                    0.093000,    0.053000,           0.088000,     0.060000,     0.040000,
GoodEvent                                     0.116000,    0.054000,           0.098000,     0.056000,     0.046000,
CounterID                                     0.255000,    0.129000,           0.175000,     0.111000,     0.086000,
ClientIP                                      0.342000,    0.163000,           0.210000,     0.139000,     0.120000,
RegionID                                      0.186000,    0.103000,           0.146000,     0.090000,     0.085000,
UserID                                        0.546000,    0.306000,           0.340000,     0.281000,     0.195000,
CounterClass                                  0.072000,    0.054000,           0.059000,     0.054000,     0.043000,
OS                                            0.124000,    0.059000,           0.114000,     0.064000,     0.048000,
UserAgent                                     0.110000,    0.058000,           0.103000,     0.063000,     0.048000,
Refresh                                       0.065000,    0.050000,           0.058000,     0.057000,     0.038000,
IsRobot                                       0.063000,    0.049000,           0.056000,     0.056000,     0.037000,
ResolutionWidth                               0.179000,    0.096000,           0.142000,     0.087000,     0.067000,
ResolutionHeight                              0.171000,    0.089000,           0.138000,     0.083000,     0.070000,
ResolutionDepth                               0.124000,    0.055000,           0.114000,     0.064000,     0.043000,
FlashMajor                                    0.102000,    0.055000,           0.095000,     0.060000,     0.043000,
FlashMinor                                    0.074000,    0.052000,           0.065000,     0.058000,     0.040000,
NetMajor                                      0.063000,    0.049000,           0.056000,     0.056000,     0.037000,
NetMinor                                      0.063000,    0.049000,           0.056000,     0.056000,     0.037000,
UserAgentMajor                                0.143000,    0.064000,           0.120000,     0.068000,     0.052000,
CookieEnable                                  0.091000,    0.048000,           0.087000,     0.055000,     0.036000,
JavascriptEnable                              0.091000,    0.048000,           0.086000,     0.055000,     0.036000,
IsMobile                                      0.070000,    0.051000,           0.063000,     0.058000,     0.039000,
MobilePhone                                   0.069000,    0.051000,           0.062000,     0.057000,     0.039000,
IPNetworkID                                   0.258000,    0.138000,           0.176000,     0.123000,     0.099000,
TraficSourceID                                0.145000,    0.085000,           0.121000,     0.083000,     0.053000,
SearchEngineID                                0.081000,    0.057000,           0.068000,     0.062000,     0.045000,
SearchPhrase                                  0.071000,    0.067000,           0.066000,     0.066000,     0.066000,
AdvEngineID                                   0.061000,    0.048000,           0.055000,     0.055000,     0.036000,
IsArtifical                                   0.092000,    0.058000,           0.084000,     0.065000,     0.045000,
WindowClientWidth                             0.175000,    0.098000,           0.140000,     0.093000,     0.072000,
WindowClientHeight                            0.163000,    0.086000,           0.133000,     0.083000,     0.069000,
ClientTimeZone                                0.165000,    0.086000,           0.134000,     0.080000,     0.071000,
SilverlightVersion1                           0.082000,    0.053000,           0.074000,     0.060000,     0.041000,
SilverlightVersion2                           0.078000,    0.052000,           0.071000,     0.059000,     0.040000,
SilverlightVersion3                           0.130000,    0.090000,           0.100000,     0.083000,     0.068000,
SilverlightVersion4                           0.064000,    0.051000,           0.056000,     0.057000,     0.038000,
CodeVersion                                   0.170000,    0.088000,           0.134000,     0.078000,     0.071000,
IsLink                                        0.068000,    0.051000,           0.060000,     0.058000,     0.039000,
IsDownload                                    0.061000,    0.049000,           0.055000,     0.056000,     0.037000,
IsNotBounce                                   0.083000,    0.056000,           0.074000,     0.063000,     0.044000,
FUniqID                                       0.432000,    0.253000,           0.280000,     0.231000,     0.166000,
HID                                           0.332000,    0.168000,           0.213000,     0.152000,     0.132000,
IsOldCounter                                  0.060000,    0.048000,           0.054000,     0.055000,     0.036000,
IsEvent                                       0.060000,    0.048000,           0.054000,     0.055000,     0.036000,
IsParameter                                   0.064000,    0.049000,           0.059000,     0.056000,     0.037000,
DontCountHits                                 0.093000,    0.058000,           0.085000,     0.065000,     0.046000,
WithHash                                      0.065000,    0.048000,           0.059000,     0.055000,     0.036000,
Age                                           0.118000,    0.057000,           0.107000,     0.064000,     0.046000,
Sex                                           0.096000,    0.054000,           0.090000,     0.061000,     0.042000,
Income                                        0.096000,    0.054000,           0.089000,     0.061000,     0.042000,
Interests                                     0.125000,    0.079000,           0.104000,     0.079000,     0.063000,
Robotness                                     0.079000,    0.055000,           0.070000,     0.060000,     0.043000,
RemoteIP                                      0.342000,    0.163000,           0.211000,     0.141000,     0.119000,
WindowName                                    0.177000,    0.116000,           0.151000,     0.103000,     0.081000,
OpenerName                                    0.125000,    0.083000,           0.115000,     0.069000,     0.053000,
HistoryLength                                 0.138000,    0.078000,           0.117000,     0.080000,     0.059000,
HTTPError                                     0.064000,    0.051000,           0.056000,     0.057000,     0.038000,
SendTiming                                    0.160000,    0.110000,           0.146000,     0.099000,     0.082000,
DNSTiming                                     0.144000,    0.113000,           0.137000,     0.106000,     0.080000,
ConnectTiming                                 0.159000,    0.123000,           0.151000,     0.116000,     0.090000,
ResponseStartTiming                           0.195000,    0.137000,           0.179000,     0.128000,     0.114000,
ResponseEndTiming                             0.197000,    0.142000,           0.182000,     0.131000,     0.114000,
FetchTiming                                   0.162000,    0.124000,           0.152000,     0.116000,     0.090000,
RedirectTiming                                0.136000,    0.111000,           0.129000,     0.104000,     0.077000,
DOMInteractiveTiming                          0.189000,    0.132000,           0.168000,     0.119000,     0.108000,
DOMContentLoadedTiming                        0.178000,    0.126000,           0.164000,     0.114000,     0.098000,
DOMCompleteTiming                             0.160000,    0.110000,           0.145000,     0.096000,     0.083000,
LoadEventStartTiming                          0.160000,    0.110000,           0.144000,     0.096000,     0.083000,
LoadEventEndTiming                            0.153000,    0.104000,           0.142000,     0.094000,     0.072000,
NSToDOMContentLoadedTimin                     0.183000,    0.127000,           0.163000,     0.114000,     0.102000,
FirstPaintTiming                              0.164000,    0.114000,           0.148000,     0.099000,     0.088000,
RedirectCount                                 0.122000,    0.075000,           0.101000,     0.077000,     0.042000,
SocialSourceNetworkID                         0.062000,    0.049000,           0.056000,     0.056000,     0.037000,
ParamPrice                                    0.069000,    0.074000,           0.069000,     0.080000,     0.069000,
ParamCurrencyID                               0.064000,    0.051000,           0.056000,     0.057000,     0.038000,
HasGCLID                                      0.060000,    0.048000,           0.054000,     0.055000,     0.036000,
RefererHash                                   0.592000,    0.346000,           0.393000,     0.331000,     0.247000,
URLHash                                       0.604000,    0.358000,           0.407000,     0.344000,     0.262000,
CLID                                          0.074000,    0.065000,           0.064000,     0.065000,     0.049000,
YCLID                                         0.072000,    0.067000,           0.064000,     0.069000,     0.056000,
RequestNum                                    0.176000,    0.104000,           0.143000,     0.092000,     0.089000,
RequestTry                                    0.096000,    0.057000,           0.086000,     0.064000,     0.045000,
```

**Pull request merged**
