### PR TITLE
Fake in-memory ZooKeeper server inside ClickHouse

### PR DESCRIPTION
**Pull request by alesapin**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Build/Testing/Packaging Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Now ClickHouse can pretend to be a fake ZooKeeper. Currently, storage implementation is just stored in-memory hash-table, and server partially support ZooKeeper protocol.

### CODE REVIEW

**Comment by alesapin** [comment]
TODO:

- [ ] Correct settings processing from configs (timeouts and so on)
- [ ] Fix exception handling (do not use LOGICAL_ERROR in all places)
- [ ] Make TestKeeperStorage a backend for TestKeeper (remove bunch of duplicated code)
- [ ] Check XID for watches, now it works well with XID=-1.
- [ ] Add integration tests with kazoo (our client maybe substandard)
- [ ] Some better way to respond in `TestKeeperTCPHandler` (wait for 10 ms doesn't seem ok)

Accidentely I had a bug when Set response doesn't rollback if multitransaction failed. However, all our tests with `zookeeper` in name worked well...

**Comment by alesapin** [comment]
Seems like something wrong with the server restart. ZooKeeper protocol works surprisingly well.

**Comment by alesapin** [comment]
Fast test passed.

**Comment by alesapin** [comment]
almost all tests passed!

**Comment by alesapin** [comment]
For some reason, epoll version works slower... investigating

**Comment by alesapin** [comment]
Oh, we have buffered read https://github.com/ClickHouse/ClickHouse/pull/16877/commits/fc0bca1ff25b699cb3561ab45e801e357ee8bfdf

**Comment by alesapin** [comment]
Something wrong with `01509_check_many_parallel_quorum_inserts` and sometimes it reproduces locally. Possibly incorrect watch processing.

**Comment by alesapin** [comment]
`01317_no_password_in_command_line` -- known flaky test.
Ok, only kazoo tests left. I think we can make TestKeeperStorage as TestKeeper backend later.

**Comment by alesapin** [comment]
Thread sanitizer fixed in https://github.com/ClickHouse/ClickHouse/pull/17498

**Comment by alesapin** [comment]
`Make TestKeeperStorage a backend for TestKeeper (remove a bunch of duplicated code)`
Now it's not quite easy, Not going to do it in this PR.

**Comment by alesapin** [comment]
Integration test failure is not related to changes. Tried tests multiple times and every time everything is OK. 
I'm going to merge this PR without additional refactoring and comments/documentation. I think this code will change significantly after adding the RAFT implementation.

**Comment by alesapin** [comment]
Related https://github.com/ClickHouse/ClickHouse/issues/15090

**Comment by bj1116** [comment]
How to config without zookeeper ?

**Pull request merged**
