### PR TITLE
Testflows RBAC test updates and new tests for views, distributed tables, and alter privileges.

### PR DESCRIPTION
**Pull request by MyroTk**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Build/Testing/Packaging Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
- Updated RBAC syntax tests.
- Updated `INSERT` and `SELECT` RBAC tests.
- New RBAC tests for `ALTER` privileges by @ritaank
- New RBAC tests for `MATERIALIZED`, `LIVE`, and standard `VIEWS`.
- New RBAC tests for public system tables.
- New RBAC tests for `SHOW TABLES`.

### CODE REVIEW

**Comment by MyroTk** [comment]
Reopening https://github.com/ClickHouse/ClickHouse/pull/14152 with changes.

**Comment by vzakaznikov** [comment]
@vitlibar, could you please review this PR? We would like to merge it as soon as possible once the CI is green.

**Comment by vzakaznikov** [comment]
@vitlibar, TestFlows check is green. Could you please review it and merge it?

**Comment by vzakaznikov** [comment]
@MyroTk, please merge with master to resolve the conflict. Thanks!

**Comment by vzakaznikov** [comment]
@vitlibar, I know there are a lot of tests but if you can take a quick look and approve this PR for merge that would be great.

**Comment by alexey-milovidov** [comment]
@vzakaznikov @MyroTk 

test_distributed_over_live_view failed.
TestFlows LDAP failed.

**Comment by vzakaznikov** [comment]
@vitlibar, we got TestFlows check green. Ready for your review and merge :).

**Comment by vitlibar** [comment]
> @vitlibar, we got TestFlows check green. Ready for your review and merge :).

Sorry for the delay.

**Pull request merged**
