### PR TITLE
Cherry pick #68003 to 24.7: Ignore disappeared projections on start

### PR DESCRIPTION
**Pull request by robot-clickhouse-ci-2**
Original pull-request #68003

This pull-request is a first step of an automated backporting.
It contains changes similar to calling `git cherry-pick` locally.
If you intend to continue backporting the changes, then resolve all conflicts if any.
Otherwise, if you do not want to backport them, then just close this pull-request.

The check results does not matter at this step - you can safely ignore them.

### Note

This pull-request will be merged automatically. Please, **do not merge it manually** (but if you accidentally did, nothing bad will happen).

#### If the PR was manually reopened after being closed

If this PR is stuck (i.e. not automatically merged after one day), check https://github.com/ClickHouse/ClickHouse/pull/68003 for `pr-backports-created` *label* and delete it.

Manually merging will do nothing. The `pr-backports-created` *label* prevents the original PR https://github.com/ClickHouse/ClickHouse/pull/68003 from being processed.

#### If the conflicts were resolved in a wrong way

If this cherry-pick PR is completely screwed by a wrong conflicts resolution, and you want to recreate it:

- delete the `pr-cherrypick` label from the PR
- delete this branch from the repository

You also need to check the original PR https://github.com/ClickHouse/ClickHouse/pull/68003 for `pr-backports-created`, and delete if it's presented there

### CODE REVIEW

**Comment by robot-ch-test-poll** [comment]
Dear @alesapin, @kssenii, the PR is not updated for 1d24h4m57s. Please, either resolve the conflicts, or close it to finish the backport process of #68003

**Comment by robot-ch-test-poll1** [comment]
Dear @alesapin, @kssenii, the PR is not updated for 1d24h0m3s. Please, either resolve the conflicts, or close it to finish the backport process of #68003

**Comment by robot-clickhouse** [comment]
Dear @alesapin, @kssenii, the PR is not updated for 1d24h52m6s. Please, either resolve the conflicts, or close it to finish the backport process of #68003

**Comment by robot-ch-test-poll** [comment]
Dear @alesapin, @kssenii, the PR is not updated for 1d26h5m3s. Please, either resolve the conflicts, or close it to finish the backport process of #68003

**Comment by robot-ch-test-poll1** [comment]
Dear @alesapin, @kssenii, the PR is not updated for 1d24h1m54s. Please, either resolve the conflicts, or close it to finish the backport process of #68003

**Comment by robot-clickhouse** [comment]
Dear @alesapin, @kssenii, the PR is not updated for 1d25h23m20s. Please, either resolve the conflicts, or close it to finish the backport process of #68003

**Comment by robot-clickhouse** [comment]
Dear @alesapin, @kssenii, the PR is not updated for 1d25h46m7s. Please, either resolve the conflicts, or close it to finish the backport process of #68003

**Comment by robot-ch-test-poll** [comment]
Dear @alesapin, @kssenii, the PR is not updated for 1d24h45m10s. Please, either resolve the conflicts, or close it to finish the backport process of #68003

**Comment by robot-clickhouse-ci-2** [comment]
Dear @alesapin, @kssenii, the PR is not updated for 1d24h58m19s. Please, either resolve the conflicts, or close it to finish the backport process of #68003

**Comment by robot-clickhouse-ci-1** [comment]
Dear @alesapin, @kssenii, the PR is not updated for 1d24h51m58s. Please, either resolve the conflicts, or close it to finish the backport process of #68003

**Comment by robot-clickhouse-ci-1** [comment]
Dear @alesapin, @kssenii, the PR is not updated for 1d25h3m56s. Please, either resolve the conflicts, or close it to finish the backport process of #68003

**Comment by robot-clickhouse-ci-1** [comment]
Dear @alesapin, @kssenii, the PR is not updated for 1d25h52m25s. Please, either resolve the conflicts, or close it to finish the backport process of #68003

**Comment by robot-ch-test-poll** [comment]
Dear @alesapin, @kssenii, the PR is not updated for 1d24h43m7s. Please, either resolve the conflicts, or close it to finish the backport process of #68003

**Comment by robot-clickhouse** [comment]
Dear @alesapin, @kssenii, the PR is not updated for 1d24h21m8s. Please, either resolve the conflicts, or close it to finish the backport process of #68003

**Comment by robot-clickhouse-ci-2** [comment]
Dear @alesapin, @kssenii, the PR is not updated for 1d24h59m14s. Please, either resolve the conflicts, or close it to finish the backport process of #68003

**Comment by robot-ch-test-poll2** [comment]
Dear @alesapin, @kssenii, the PR is not updated for 1d25h1m58s. Please, either resolve the conflicts, or close it to finish the backport process of #68003

**Comment by robot-clickhouse-ci-2** [comment]
Dear @alesapin, @kssenii, the PR is not updated for 1d24h3m21s. Please, either resolve the conflicts, or close it to finish the backport process of #68003

**Comment by robot-ch-test-poll3** [comment]
Dear @alesapin, @kssenii, the PR is not updated for 1d24h1m44s. Please, either resolve the conflicts, or close it to finish the backport process of #68003

**Comment by robot-ch-test-poll4** [comment]
Dear @alesapin, @kssenii, the PR is not updated for 1d24h43m1s. Please, either resolve the conflicts, or close it to finish the backport process of #68003

**Comment by robot-clickhouse-ci-2** [comment]
Dear @alesapin, @kssenii, the PR is not updated for 1d24h12m15s. Please, either resolve the conflicts, or close it to finish the backport process of #68003

**Comment by robot-clickhouse-ci-2** [comment]
Dear @alesapin, @kssenii, the PR is not updated for 1d25h0m42s. Please, either resolve the conflicts, or close it to finish the backport process of #68003

**Comment by robot-clickhouse-ci-1** [comment]
Dear @alesapin, @kssenii, the PR is not updated for 1d24h53m54s. Please, either resolve the conflicts, or close it to finish the backport process of #68003

**Comment by robot-ch-test-poll3** [comment]
Dear @alesapin, @kssenii, the PR is not updated for 1d24h2m25s. Please, either resolve the conflicts, or close it to finish the backport process of #68003

**Comment by robot-clickhouse** [comment]
Dear @alesapin, @kssenii, the PR is not updated for 1d24h0m41s. Please, either resolve the conflicts, or close it to finish the backport process of #68003

**Comment by robot-ch-test-poll4** [comment]
Dear @alesapin, @kssenii, the PR is not updated for 1d24h22m23s. Please, either resolve the conflicts, or close it to finish the backport process of #68003

**Comment by robot-ch-test-poll** [comment]
Dear @alesapin, @kssenii, the PR is not updated for 1d24h36m42s. Please, either resolve the conflicts, or close it to finish the backport process of #68003

**Comment by robot-ch-test-poll2** [comment]
Dear @alesapin, @kssenii, the PR is not updated for 1d24h2m14s. Please, either resolve the conflicts, or close it to finish the backport process of #68003

**Comment by robot-ch-test-poll3** [comment]
Dear @alesapin, @kssenii, the PR is not updated for 1d24h1m15s. Please, either resolve the conflicts, or close it to finish the backport process of #68003

**Comment by robot-ch-test-poll2** [comment]
Dear @alesapin, @kssenii, the PR is not updated for 1d24h57m36s. Please, either resolve the conflicts, or close it to finish the backport process of #68003

**Comment by robot-ch-test-poll4** [comment]
Dear @alesapin, @kssenii, the PR is not updated for 1d24h7m5s. Please, either resolve the conflicts, or close it to finish the backport process of #68003

**Comment by robot-ch-test-poll2** [comment]
Dear @alesapin, @kssenii, the PR is not updated for 1d24h54m23s. Please, either resolve the conflicts, or close it to finish the backport process of #68003

**Comment by robot-clickhouse-ci-2** [comment]
Dear @alesapin, @kssenii, the PR is not updated for 1d24h1m22s. Please, either resolve the conflicts, or close it to finish the backport process of #68003

**Comment by robot-ch-test-poll2** [comment]
Dear @alesapin, @kssenii, the PR is not updated for 1d24h1m25s. Please, either resolve the conflicts, or close it to finish the backport process of #68003

**Pull request closed without merging**
