### PR TITLE
Fix flaky window view tests

### PR DESCRIPTION
**Pull request by Vxider**
Changelog category (leave one):

- Not for changelog (changelog entry is not required)

Detailed description / Documentation draft:

https://github.com/ClickHouse/ClickHouse/pull/32201#issuecomment-990788159

Try to fix the flaky window view tests by rewriting the tests using `.sh` scripts. If this works, I'll rewrite all window view tests in `.sql`.

### CODE REVIEW

**Comment by Vxider** [comment]
@kssenii  Can I have a "can be tested" label, I'll try to run these tests and we can treat this PR as a draft for now.

**Comment by Vxider** [comment]
@Mergifyio update

**Review by kssenii — APPROVED** [review]

**Comment by Vxider** [comment]
Two times of "Stateless tests flaky check" has passed. Maybe the tests are stable now.

[First stateless tests flaky check](https://s3.amazonaws.com/clickhouse-test-reports/32503/8e3529818ec71bce00b7645ac6f4c7b5186b3f35/stateless_tests_flaky_check__address__actions_.html)

[Second stateless tests flaky check](https://s3.amazonaws.com/clickhouse-test-reports/32503/add1e8302e1cd00e944675e00b6bb6a661e7347f/stateless_tests_flaky_check__address__actions_.html)

**Comment by qoega** [comment]
btw, you can sleep in sql

**Comment by Vxider** [comment]
> btw, you can sleep in sql

3 seconds might not be enough when the system froze, so I rewrite `sleep (3)` to endless retry.

**Pull request merged**
