### PR TITLE
Remove clickhouse-diagnostics from the package

### LINKED ISSUE #61071: Remove `clickhouse-diagnostics` from the package
It is written in Go, and frequently gets attention of security scanners due to a high number of library dependencies. While this motivation is not reasonable, this tool is rarely used, and we can remove it to avoid the burden.

### PR DESCRIPTION
**Pull request by alexey-milovidov**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Closes #61071.

### CODE REVIEW

**Comment by robot-ch-test-poll3** [comment]
*This is an automated comment for commit bfc7c3c89edd2454ee0d6d23052d9bade28ac2a7 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/61681/bfc7c3c89edd2454ee0d6d23052d9bade28ac2a7/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

**Review by nikitamikhaylov — APPROVED** [review]

**Comment by Felixoid** [comment]
cc @gingerwizard

**Comment by gingerwizard** [comment]
@Felixoid im sure we have good reason for this. cc @thomoco @e-mars who need to know about this.

**Comment by thomoco** [comment]
Why would clickhouse-diagnostics be removed? How will we get diagnostics for self-managed ClickHouse Deployments if it is? The need we had identified previously was to enhance clickhouse-diagnostics with SSL and object storage metrics

**Comment by e-mars** [comment]
please don't remove, it is simpler for our users to find it when we're gathering from on-prem deployments. can we maybe find a dev that could improve/maintain to address the scanner issues?

**Pull request merged**
