### PR TITLE
Try to fix Logical error 'Array sizes mismatched' while parsing JSON object

### LINKED ISSUE #43569: Object(JSON) errors for keys with the same name at different paths
I couldn't come up with a better title, sorry! Feel free to rename it :)

**Describe the unexpected behaviour**
I have this nested JSON structure that I cannot insert into my table. I'm using the experimental JSON object and am unsure if what I've come across is a bug or expected behavior due to limitations that I haven't been able to find in the documentation. Unexpected behavior, for sure!

A minimal example to reproduce. Tested on ClickHouse 22.11.
```
CREATE TABLE test
(
    `payload` JSON
)
ENGINE = MergeTree
ORDER BY tuple()
```

The object that I'm trying to insert.
```json
{
  "payload": {
    "list": [
      {
        "b": {
          "a": [
            {
              "key": "non-null value"
            },
            {
              "key": "non-null value"
            }
          ]
        },
        "a": [
          {
            "key": "non-null value"
          }
        ]
      }
    ]
  }
}
```

Inserted with ClickHouse client.
```sh
clickhouse client -q 'INSERT INTO test FORMAT JSONEachRow' < file.json
```

**Expected behavior**
The input is valid JSON, so I would expect it to be successfully inserted.

**Error message and/or stacktrace**
> Code: 49. DB::Exception: Array sizes mismatched (1 and 2): (while reading the value of key payload): While executing ParallelParsingBlockInputFormat: data for INSERT was parsed from stdin: (in query: insert into test format JSONEachRow). (LOGICAL_ERROR)

**Additional context**
- I noticed that if I make the two `a` arrays the same size, the insert works. The same is true if I rename either of them to something else.

- If I remove the outer `list` element, the object can be successfully inserted. Example:
```json
{
  "payload": {
    "b": {
      "a": [
        {
          "key": "non-null value"
        },
        {
          "key": "non-null value"
        }
      ]
    },
    "a": [
      {
        "key": "non-null value"
      }
    ]
  }
}
```

### PR DESCRIPTION
**Pull request by Avogar**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in official stable or prestable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix posssible logical error 'Array sizes mismatched' while parsing JSON object with arrays with same key names but with different nesting level. Closes https://github.com/ClickHouse/ClickHouse/issues/43569

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by Avogar** [comment]
I'm not sure if this fix is 100% correct, @CurtizJ please look at it and comment

**Review by CurtizJ — APPROVED** [review]
LGTM. Probably `JSONDataParser` should be rewritten completely with usage of `SubcolumnsTree`, because it's quite complex and there are still some case when it works incorrectly.

**Comment by CurtizJ** [comment]
AST fuzzer (debug) - is not related and also is not reproducible on master neither with default settings nor with `allow_experimental_analyzer`

**Comment by Avogar** [comment]
`AST fuzzer (debug)` - I managed to reproduce and it found segfault: https://github.com/ClickHouse/ClickHouse/issues/43758

**Pull request merged**
