### PR TITLE
Fix test_dictionaries_update_and_reload::test_reload_after_fail_by_timer flakiness

### PR DESCRIPTION
**Pull request by azat**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]

**Comment by robot-ch-test-poll2** [comment]
*This is an automated comment for commit e6921bfc595937ac6d2d448ac46cf2778119d509 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/67754/e6921bfc595937ac6d2d448ac46cf2778119d509/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/e4c165e919df7b43671fd8909176e2162c9a65fc/docs_check.html">✅ success</a></td></tr>
<tr><td>Fast test</td><td>Normally this is the first check that is ran for a PR. It builds ClickHouse and runs most of <a href="https://clickhouse.com/docs/en/development/tests#functional-tests">stateless functional tests</a>, omitting some. If it fails, further checks are not started until it is fixed. Look at the report to see which tests fail, then reproduce the failure locally as described <a href="https://clickhouse.com/docs/en/development/tests#functional-test-locally">here</a></td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/c629e2af50edbeb2b12f61f0a9b1a998251eec45/fast_test.html">✅ success</a></td></tr>
<tr><td>Unit tests</td><td>Runs the unit tests for different release types</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/c629e2af50edbeb2b12f61f0a9b1a998251eec45/unit_tests__release_.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Comment by fm4v** [comment]
I don't like this change because now we expect both statuses `["FAILED", "FAILED_AND_RELOADING"]` even in release build. Original fix expect only `"FAIL"` status and in sanitizer builds `"FAILED_AND_RELOADING"` is expected for some time which is always changed to `"FAILED"`.
I think it's better to increase `retry_count` and add same retries for second assert.


> Anyway this code is wrong, since you still can get FAILED_AND_RELOADING two lines below, there should be else at least.

Original changes fixes problem in first assert. I didn't see fix for the second assert in this PR too.

According to fails for the last 90 days:
3 fails in second asserts:
[1](https://s3.amazonaws.com/clickhouse-test-reports/0/37fe5da9e426245d40441cfc5a453e5c2f874b16/integration_tests__release__[3_4]//home/ubuntu/actions-runner/_work/_temp/test/output_dir/integration_run_parallel0_0.log 
) [2](https://s3.amazonaws.com/clickhouse-test-reports/0/9f1b3e297909874e32dd132d91da9ee2c76a5bd2/integration_tests__tsan__[3_6]//home/ubuntu/actions-runner/_work/_temp/test/output_dir/integration_run_parallel0_0.log
) [3](https://s3.amazonaws.com/clickhouse-test-reports/64281/6917c8c9d79362bbcbac000bf335dc54c16cf637/integration_tests__tsan__[3_6]//home/ubuntu/actions-runner/_work/_temp/test/output_dir/integration_run_parallel0_0.log
)
2 fails in first assert:
[1](https://s3.amazonaws.com/clickhouse-test-reports/63216/d954a273e1b775b089bbfba36ca934fddf7c25f5/integration_tests__tsan__[3_6]//home/ubuntu/actions-runner/_work/_temp/test/output_dir/integration_run_parallel0_0.log
) [2](https://s3.amazonaws.com/clickhouse-test-reports/66311/316dd790bdb5a8cb4aef11c356f14700f3b9169e/integration_tests__asan__old_analyzer__[3_6]//home/ubuntu/actions-runner/_work/_temp/test/output_dir/integration_run_parallel0_0.log
)

Also flakiness rate is decreased after first fix and why it happens?

**Comment by azat** [comment]
>I don't like this change because now we expect both statuses ["FAILED", "FAILED_AND_RELOADING"] even in release build

@fm4v 
- Why it is possible to have FAILED_AND_RELOADING under sanitizers but not release build?
- Why allowing FAILED_AND_RELOADING is bad?

**Comment by azat** [comment]
This test is not idempotent and should be rewritten completely

**Comment by azat** [comment]
@fm4v help is welcome

**Comment by fm4v** [comment]
Close in favor of https://github.com/ClickHouse/ClickHouse/pull/67793

**Comment by qoega** [comment]
> This test is not idempotent and should be rewritten completely

+1 to this. Trivial ways to fix is to either drop all dictionaries in the end of a test or to have unique dictionary name in every test run. If we rely on logs, make it dependent on specific test run

**Pull request closed without merging**
