### PR TITLE
add links for LTS repositories

### PR DESCRIPTION
**Pull request by DanRoscigno**
Update docs with links for LTS and stable repositories.

### Changelog category (leave one):
- Documentation (changelog entry is not required)

### CODE REVIEW

**Comment by Felixoid** [comment]
I wouldn't say I like it in the current view. It was previously mentioned for each type of package, and now it's noted only for Debian and apt

**Comment by DanRoscigno** [comment]
> I wouldn't say I like it in the current view. It was previously mentioned for each type of package, and now it's noted only for Debian and apt

Good point, I did not see that you have separate dirs for tgz.  Adding.

**Comment by Felixoid** [comment]
you can always do `git reset --hard $LAST_SUCCESS_SHA`, e.g. `git reset --hard 4917535` and then `git push --force`

**Comment by DanRoscigno** [comment]
Thanks!

**Pull request closed without merging**
