### PR TITLE
add cache to IAST::getColumnName to improve performance for a huge ast

### LINKED ISSUE #51224: IAST::getColumnName() may be very heavy
**Describe the situation**
Functions with prefix `get` are usually considered lightweight. However, the `IAST::getColumnName()` may be very heavy because it recursively calls virtual function `IAST::appendColumnName()`. When the AST tree is deep, the cost of recursively calling `IAST::appendColumnName()` is huge. In my practice, the cost would count half of the total elapsed time of running a big query.

**How to reproduce**
* Which ClickHouse server version to use
23.3

**Expected performance**
`IAST::getColumnName()` should be a light-weight function, as it is called many times and many places. It should not count half of total time.

Here is the dump of AST tree for my test big query.
[sql1.ast.txt](https://github.com/ClickHouse/ClickHouse/files/11816438/sql1.ast.txt)

### PR DESCRIPTION
**Pull request by frinkr**
### Changelog category (leave one):
- Performance Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Improve performance for huge query analysis. Fixes https://github.com/ClickHouse/ClickHouse/issues/51224

### CODE REVIEW

**Comment by frinkr** [comment]
We have some huge queries (3MB~13MB, generated by tools), this PR improve the overall performance by 20%~40%.

**Comment by robot-clickhouse-ci-1** [comment]
This is an automated comment for commit f06d32933cedd42fc21e3a75a1804b5ac92022cd with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/51143/f06d32933cedd42fc21e3a75a1804b5ac92022cd/ci_running.html)
The overall status of the commit is 🔴 failure

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🔴 failure</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Comment by Felixoid** [comment]
The fast tests failed with a stack trace, but because of a small issue in fast tests script, the status is not created, and it's not visible where's the issue. I address it in https://github.com/ClickHouse/ClickHouse/pull/51163, but please, see the logs in https://github.com/ClickHouse/ClickHouse/actions/runs/5309169770/jobs/9612318046?pr=51143 and address them.

**Comment by alexey-milovidov** [comment]
I strongly suggest against this change.
The cache looks too ad-hoc, and it is not thread-safe.

**Comment by frinkr** [comment]
> I strongly suggest against this change. The cache looks too ad-hoc, and it is not thread-safe.

Indeed, and that's why I converted the PR to draft. Beside, the cached value would be invalid if any decendent node was changed. @alexey-milovidov, any suggestion to fix the issue?

**Comment by alexey-milovidov** [comment]
I expect that with `allow_experimental_analyzer`, the number of `getColumnName` calls should decrease.

**Comment by frinkr** [comment]
@alexey-milovidov, unfortunately `allow_experimental_analyzer` doesn't work for us. I will close this PR and send new one ( https://github.com/ClickHouse/ClickHouse/pull/51469 )

**Pull request closed without merging**
