### PR TITLE
Cherry pick #64226 to 24.4: Fix ARRAY JOIN with Distributed.

### PR DESCRIPTION
**Pull request by robot-ch-test-poll3**
Original pull-request #64226

This pull-request is a first step of an automated backporting.
It contains changes similar to calling `git cherry-pick` locally.
If you intend to continue backporting the changes, then resolve all conflicts if any.
Otherwise, if you do not want to backport them, then just close this pull-request.

The check results does not matter at this step - you can safely ignore them.

### Note

This pull-request will be merged automatically. Please, **do not merge it manually** (but if you accidentally did, nothing bad will happen).

#### If the PR was manually reopened after being closed

If this PR is stuck (i.e. not automatically merged after one day), check https://github.com/ClickHouse/ClickHouse/pull/64226 for `pr-backports-created` *label* and delete it.

Manually merging will do nothing. The `pr-backports-created` *label* prevents the original PR https://github.com/ClickHouse/ClickHouse/pull/64226 from being processed.

#### If the conflicts were resolved in a wrong way

If this cherry-pick PR is completely screwed by a wrong conflicts resolution, and you want to recreate it:

- delete the `pr-cherrypick` label from the PR
- delete this branch from the repository

You also need to check the original PR https://github.com/ClickHouse/ClickHouse/pull/64226 for `pr-backports-created`, and delete if it's presented there

### CODE REVIEW

**Comment by robot-ch-test-poll2** [comment]
Dear @KochetovNicolai, @novikd, the PR is not updated for 1d25h0m1s. Please, either resolve the conflicts, or close it to finish the backport process of #64226

**Comment by robot-ch-test-poll4** [comment]
Dear @KochetovNicolai, @novikd, the PR is not updated for 1d24h2m33s. Please, either resolve the conflicts, or close it to finish the backport process of #64226

**Comment by robot-clickhouse-ci-1** [comment]
Dear @KochetovNicolai, @novikd, the PR is not updated for 1d24h56m21s. Please, either resolve the conflicts, or close it to finish the backport process of #64226

**Comment by robot-ch-test-poll1** [comment]
Dear @KochetovNicolai, @novikd, the PR is not updated for 1d24h1m56s. Please, either resolve the conflicts, or close it to finish the backport process of #64226

**Comment by robot-clickhouse** [comment]
Dear @KochetovNicolai, @novikd, the PR is not updated for 1d24h0m11s. Please, either resolve the conflicts, or close it to finish the backport process of #64226

**Comment by robot-clickhouse** [comment]
Dear @KochetovNicolai, @novikd, the PR is not updated for 1d24h57m8s. Please, either resolve the conflicts, or close it to finish the backport process of #64226

**Comment by robot-ch-test-poll** [comment]
Dear @KochetovNicolai, @novikd, the PR is not updated for 1d24h2m33s. Please, either resolve the conflicts, or close it to finish the backport process of #64226

**Comment by robot-clickhouse** [comment]
Dear @KochetovNicolai, @novikd, the PR is not updated for 1d24h59m33s. Please, either resolve the conflicts, or close it to finish the backport process of #64226

**Comment by robot-ch-test-poll4** [comment]
Dear @KochetovNicolai, @novikd, the PR is not updated for 1d25h0m2s. Please, either resolve the conflicts, or close it to finish the backport process of #64226

**Comment by robot-ch-test-poll2** [comment]
Dear @KochetovNicolai, @novikd, the PR is not updated for 1d24h58m31s. Please, either resolve the conflicts, or close it to finish the backport process of #64226

**Comment by robot-ch-test-poll3** [comment]
Dear @KochetovNicolai, @novikd, the PR is not updated for 1d24h2m26s. Please, either resolve the conflicts, or close it to finish the backport process of #64226

**Comment by robot-clickhouse** [comment]
Dear @KochetovNicolai, @novikd, the PR is not updated for 1d25h5m8s. Please, either resolve the conflicts, or close it to finish the backport process of #64226

**Comment by robot-clickhouse-ci-2** [comment]
Dear @KochetovNicolai, @novikd, the PR is not updated for 1d24h7m11s. Please, either resolve the conflicts, or close it to finish the backport process of #64226

**Comment by robot-clickhouse** [comment]
Dear @KochetovNicolai, @novikd, the PR is not updated for 1d25h13m39s. Please, either resolve the conflicts, or close it to finish the backport process of #64226

**Comment by robot-ch-test-poll2** [comment]
Dear @KochetovNicolai, @novikd, the PR is not updated for 1d24h46m39s. Please, either resolve the conflicts, or close it to finish the backport process of #64226

**Comment by robot-ch-test-poll1** [comment]
Dear @KochetovNicolai, @novikd, the PR is not updated for 1d24h44m28s. Please, either resolve the conflicts, or close it to finish the backport process of #64226

**Comment by robot-ch-test-poll2** [comment]
Dear @KochetovNicolai, @novikd, the PR is not updated for 1d24h2m47s. Please, either resolve the conflicts, or close it to finish the backport process of #64226

**Comment by robot-ch-test-poll3** [comment]
Dear @KochetovNicolai, @novikd, the PR is not updated for 1d24h0m56s. Please, either resolve the conflicts, or close it to finish the backport process of #64226

**Comment by robot-ch-test-poll3** [comment]
Dear @KochetovNicolai, @novikd, the PR is not updated for 1d24h58m17s. Please, either resolve the conflicts, or close it to finish the backport process of #64226

**Comment by robot-ch-test-poll4** [comment]
Dear @KochetovNicolai, @novikd, the PR is not updated for 1d24h58m20s. Please, either resolve the conflicts, or close it to finish the backport process of #64226

**Comment by robot-clickhouse-ci-2** [comment]
Dear @KochetovNicolai, @novikd, the PR is not updated for 1d24h4m6s. Please, either resolve the conflicts, or close it to finish the backport process of #64226

**Comment by robot-clickhouse-ci-2** [comment]
Dear @KochetovNicolai, @novikd, the PR is not updated for 1d25h3m12s. Please, either resolve the conflicts, or close it to finish the backport process of #64226

**Comment by robot-ch-test-poll4** [comment]
Dear @KochetovNicolai, @novikd, the PR is not updated for 1d24h55m48s. Please, either resolve the conflicts, or close it to finish the backport process of #64226

**Comment by robot-ch-test-poll3** [comment]
Dear @KochetovNicolai, @novikd, the PR is not updated for 1d24h1m27s. Please, either resolve the conflicts, or close it to finish the backport process of #64226

**Comment by robot-clickhouse-ci-2** [comment]
Dear @KochetovNicolai, @novikd, the PR is not updated for 1d24h53m43s. Please, either resolve the conflicts, or close it to finish the backport process of #64226

**Comment by robot-clickhouse** [comment]
Dear @KochetovNicolai, @novikd, the PR is not updated for 1d24h0m20s. Please, either resolve the conflicts, or close it to finish the backport process of #64226

**Comment by robot-clickhouse-ci-1** [comment]
Dear @KochetovNicolai, @novikd, the PR is not updated for 1d24h58m57s. Please, either resolve the conflicts, or close it to finish the backport process of #64226

**Comment by robot-clickhouse** [comment]
Dear @KochetovNicolai, @novikd, the PR is not updated for 1d25h3m20s. Please, either resolve the conflicts, or close it to finish the backport process of #64226

**Comment by robot-ch-test-poll4** [comment]
Dear @KochetovNicolai, @novikd, the PR is not updated for 1d24h58m14s. Please, either resolve the conflicts, or close it to finish the backport process of #64226

**Comment by robot-ch-test-poll2** [comment]
Dear @KochetovNicolai, @novikd, the PR is not updated for 1d24h59m15s. Please, either resolve the conflicts, or close it to finish the backport process of #64226

**Pull request closed without merging**
