### PR TITLE
Update azure sdk submodule

### PR DESCRIPTION
**Pull request by azat**
There was some interesting fixes.

P.S. for now I'm using my own fork.

### Changelog category (leave one):
- Build/Testing/Packaging Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Update azure sdk submodule

### CODE REVIEW

**Comment by alesapin** [comment]
Please, create PR with your interesting changes to our fork.

**Comment by azat** [comment]
@alesapin the plan is to upgrade via a temporary repository location first to run some tests, since extras repositories does not have CI

**Comment by alexey-milovidov** [comment]
Conflicts with #43020.

**Comment by azat** [comment]
How? That PR updates only **aws**, not **azure**.

**Comment by alexey-milovidov** [comment]
I misread this. Let's continue.

**Comment by azat** [comment]
Ugh, now it is not compatible with boringssl, azure sdk requires some patches.

**Comment by azat** [comment]
Will close for now.

**Pull request closed without merging**
