### PR TITLE
Docker cli example

### PR DESCRIPTION
**Pull request by vklimontovich**
Exposing the 8123 (HTTP) interface in basic example and giving CLI connection instruction makes it easier to start. For a lot of developers, curl is a native and very familiar tool

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):

- Documentation (changelog entry is not required)

### CODE REVIEW

**Comment by den-crane** [comment]
Why only 8123 ? 


Why not -p 8123:8123 -p 9000:9000 -p 9014:9014

http/tcp/mysql

**Comment by vklimontovich** [comment]
Well, the purpose of this section is to provide a very quick working example, it's unlikely that people will use it for production. Curl is the most universal name for how to run a query. And it's unlikely users will start with connecting to it through MySQL binary protocol (and for TCP protocol there's another way in examples). So I decided to suggest to expose the bare minimum.

However, exposing all ports might be an option as well. In my opinion, it will make command longer and less transparent

**Comment by filimonov** [comment]
> Curl is the most universal name for how to run a query. 

questionable. The most natural way to run query in clickhouse is to use clickhouse-client. 

Exposing a single port (HTTP only) looks weird.

**Comment by filimonov** [comment]
Since we are in a docker conventions you can show a docker example for that, smth like: 
```
echo "SELECT * FROM system.build_options" | docker run -i --rm --link some-clickhouse-server:clickhouse-server curlimages/curl 'http://clickhouse-server:8123/?query=' -s --data-binary @-
```

People using docker should know how to expose ports. The people who doesn't know that and will do copy&paste from the example line can expose their docker to the internet accidentally.

**Comment by alexey-milovidov** [comment]
@filimonov Could you please add this info to the docs?

PS. There is no "obvious" things that everyone knows. We can add both examples: with port mapping, with network=host and with linked containers.

**Comment by alexey-milovidov** [comment]
@filimonov ?

**Comment by filimonov** [comment]
@alexey-milovidov not too much of original changeset survived.

**Review by alexey-milovidov — COMMENTED** [review]
:+1:

**Comment by alexey-milovidov** [comment]
Thank you! Now it's perfect.

**Pull request merged**
