### PR TITLE
Fix native macOS build

### PR DESCRIPTION
**Pull request by rschu1ze**
#69674 broke then native macOS build, this PR fixes it.

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Review by alexkats — APPROVED** [review]

**Comment by robot-clickhouse-ci-1** [comment]
*This is an automated comment for commit 8e9fb0964e937fe367ee760014e1eb0ca09a1bb4 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/69767/8e9fb0964e937fe367ee760014e1eb0ca09a1bb4/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/69717/e0fc95c894fcd129566b7c374496423e30f94c2c/docs_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Comment by alexkats** [comment]
Do you know why the build check for darwin didn't fail in that PR?

**Comment by rschu1ze** [comment]
> Do you know why the build check for darwin didn't fail in that PR?

Yeah, CI only cross-compiles (on Linux) for macOS but it does not build for macOS on macOS. So issues with the latter go unnoticed 😢

**Comment by rschu1ze** [comment]
(needs another fix, the native macOS build is still red locally)

**Comment by rschu1ze** [comment]
> (needs another fix, the native macOS build is still red locally)

Not true, I compiled the wrong stuff. The native build is green now. Let's merge.

**Pull request merged**
