### PR TITLE
Reorganize layout of repository (part 1)

### PR DESCRIPTION
**Pull request by abyss7**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Non-significant (changelog entry is not required)

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]
Ok.

In next PR: let's add `base` to `/utils/check-style` and ensure that it is passed.

**Comment by alexey-milovidov** [comment]
In `daemon` and `mysqlxx` the directories `include` and `src` remain.
Let's merge together?

**Comment by alexey-milovidov** [comment]
#9161

**Comment by abyss7** [comment]
> In `daemon` and `mysqlxx` the directories `include` and `src` remain.
> Let's merge together?

Sure, I will do this in next PR

**Comment by azat** [comment]
After `libs/libdaemon` has been moved to `base/libdaemon`, `libs/libdaemon` can be removed from the include directories (seems that it does not used anyway), i.e. here https://github.com/ClickHouse/ClickHouse/blob/9e4b29fe6ce271993b1d07a6d520e19a6adf8cca/dbms/programs/server/CMakeLists.txt#L26

**Comment by filimonov** [comment]
@Enmk has null of changes related to DateLUT, i add him to review. Please sync it with him to avoid complicated painful merges

**Comment by alexey-milovidov** [comment]
@azat Ok.

**Pull request merged**
