### PR TITLE
Fix inconsistency of "cast('0' as DateTime64(3))" and "cast('0' as Nullable(DateTime64(3)))"

### PR DESCRIPTION
**Pull request by taiyang-li**
### Changelog category (leave one):

- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix issue https://github.com/ClickHouse/ClickHouse/issues/56285

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by robot-clickhouse-ci-1** [comment]
*This is an automated comment for commit 93be383117485dfb735214cf52a6d954e5eefc92 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/56286/93be383117485dfb735214cf52a6d954e5eefc92/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td><a href="https://github.com/ClickHouse/ClickHouse/actions/runs/6741356217">✅ success</a></td></tr>
<tbody>
</table>
</details>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/56286/93be383117485dfb735214cf52a6d954e5eefc92/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Comment by zvonand** [comment]
See my comment to the [issue](https://github.com/ClickHouse/ClickHouse/issues/56285#issuecomment-1792706723)

**Comment by taiyang-li** [comment]
Failed integration tests not related to this pr: https://s3.amazonaws.com/clickhouse-test-reports/56286/3c70b9f65d38e221db5a72f345741f16258680d8/integration_tests__asan__[2_6].html

**Comment by Algunenano** [comment]
Test failures are unrelated and already reported.

**Review by Algunenano — APPROVED** [review]

**Pull request merged**
