### PR TITLE
Support SSE-KMS configuration with S3 client

### LINKED ISSUE #48723: Support granular server-side encryption in S3 with KMS keys (SSE-KMS)
**Context/use case**

[AWS KMS](https://aws.amazon.com/kms/) is AWS's managed cryptographic key service. It [integrates with S3](https://docs.aws.amazon.com/AmazonS3/latest/userguide/UsingKMSEncryption.html) ("SSE-KMS"), allowing server-side encryption of S3 objects at either the bucket-level (via bucket configuration) or at the [object-level](https://docs.aws.amazon.com/AmazonS3/latest/userguide/specifying-kms-encryption.html) (using the `x-amz-server-side-encryption-aws-kms-key-id` HTTP header in certain requests).

Currently you can use both the S3 table engine and S3-backed MergeTree with an S3 bucket configured with bucket-level SSE-KMS without issue. However, (to my knowledge) there's no way for ClickHouse to do SSE-KMS at the object level, which means there's no way to, e.g., have different tables backed by the same S3 bucket but using different SSE-KMS keys (you might want to do this if you're mingling different data sources in a single database). It would be great if ClickHouse supported KMS key configuration for S3 endpoints/disks.

**Describe the solution you'd like**

ClickHouse already supports configuring [SSE with customer-provided keys](https://docs.aws.amazon.com/AmazonS3/latest/userguide/ServerSideEncryptionCustomerKeys.html) ("SSE-C") via the `server_side_encryption_customer_key_base64` setting, which is supported both for the [S3 table engine](https://clickhouse.com/docs/en/engines/table-engines/integrations/s3#endpoint-settings) and [S3-backed MergeTree](https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/mergetree#table_engine-mergetree-s3); see https://github.com/ClickHouse/ClickHouse/pull/19748. Ideally, a solution for KMS would provide analogous settings corresponding to the [various headers](https://docs.aws.amazon.com/AmazonS3/latest/userguide/specifying-kms-encryption.html) you can specify when configuring SSE-KMS:

- `server_side_encryption_kms_key_id` to specify a particular KMS key ID or alias for SSE, for example, "alias/my-kms-key".
- `server_side_encryption_kms_encryption_context` (corresponding to `x-amz-server-side-encryption-context`)
- `server_side_encryption_kms_bucket_key_enabled` (corresponding to `x-amz-server-side-encryption-bucket-key-enabled`)

Configuring these settings would cause ClickHouse to add (and sign) these headers to all relevant requests sent to S3.

**Describe alternatives you've considered**

1. The S3 table engine supports the [`header`](https://clickhouse.com/docs/en/engines/table-engines/integrations/s3#endpoint-settings) setting, so you might think to just specify the `x-amz-server-side-encryption-aws-kms-key-id` header manually. However, this doesn't work because S3 requires that the KMS header is signed, and the `header` setting is implemented in such a way that these custom headers are appended to the HTTP request post-signing. This setting also isn't implemented with S3 disks and so can't be used with S3-backed MergeTree.
2. You could just create separate buckets for every KMS key you want to use, and do all the configuration on the S3 side. But this is somewhat restrictive. For example, if you have many KMS keys, or many other buckets for other purposes, you may run into S3's per-account [100 bucket limit](https://docs.aws.amazon.com/AmazonS3/latest/userguide/BucketRestrictions.html).

### PR DESCRIPTION
**Pull request by johanngan**
### Changelog category (leave one):
- New Feature

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Added [server-side encryption using KMS keys](https://docs.aws.amazon.com/AmazonS3/latest/userguide/UsingKMSEncryption.html) with S3 tables, and the `header` setting with S3 disks. Closes https://github.com/ClickHouse/ClickHouse/issues/48723

### Documentation entry for user-facing changes

- [x] Documentation is written (mandatory for new features)

### CODE REVIEW

**Comment by johanngan** [comment]
Tested manually with both S3 table engine and S3-backed MergeTree by configuring a KMS key, creating tables, inserting rows, and querying them back. The appropriate unit test is also updated.

**Comment by johanngan** [comment]
The `header` support for S3 disks was a first failed attempt at this before I realized that KMS headers need to be signed. But it seemed like a generically useful change regardless so I kept it in.

**Comment by UnamedRus** [comment]
Just to confirm, https://github.com/ClickHouse/ClickHouse/issues/27140 issue also fixed? (Ie need to sign all headers with x-amz- prefix)

**Comment by johanngan** [comment]
> Just to confirm, #27140 issue also fixed? (Ie need to sign all headers with x-amz- prefix)

Unfortunately no. The change I made with the `header` setting was to port the existing feature with the S3 engine to S3 disks as well. The signing behavior of these extra headers is unchanged (so they remain unsigned). I think the proposed changed in #27140 also no longer applies to the current code; from what I could tell it'll be a bit more annoying to inject signed headers into all requests.

**Comment by robot-ch-test-poll3** [comment]
This is an automated comment for commit 731823b8733998f390c51858ef683326b795e340 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/48724/731823b8733998f390c51858ef683326b795e340/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Docs Check</td><td>Builds and tests the documentation</td><td>🟡 pending</td></tr>
</table>

**Comment by johanngan** [comment]
(Latest push is just resolving conflicts; no substantive changes)

**Review by antonio2368 — APPROVED** [review]
Thanks for the change! It's really clean with some useful refactoring

**Pull request merged**
