### PR TITLE
clickhouse-local support --database command line argument

### PR DESCRIPTION
**Pull request by vdimir**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
* `clickhouse-local` support `--database` command line argument

### CODE REVIEW

**Comment by robot-clickhouse** [comment]
This is an automated comment for commit 5061da4e8ace9664e880cb67070e295f76477da5 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/54503/5061da4e8ace9664e880cb67070e295f76477da5/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Review by alexey-milovidov — APPROVED** [review]

**Comment by vdimir** [comment]
> Stateless tests (release, s3 storage) [2/2] — fail: 1, passed: 2798, skipped: 30 [Details](https://s3.amazonaws.com/clickhouse-test-reports/54503/5061da4e8ace9664e880cb67070e295f76477da5/stateless_tests__release__s3_storage__[2_2].html)

```
2023-09-11 10:38:31 02125_many_mutations:                                                   [ FAIL ] 600.00 sec. - Timeout!
2023-09-11 10:38:31 Settings used in the test: --max_insert_threads 0 --group_by_two_level_threshold 1000000 --group_by_two_level_threshold_bytes 1 --distributed_aggregation_memory_efficient 1 --fsync_metadata 0 --output_format_parallel_formatting 1 --input_format_parallel_parsing 1 --min_chunk_bytes_for_parallel_parsing 9850272 --max_read_buffer_size 967298 --prefer_localhost_replica 0 --max_block_size 25574 --max_threads 33 --optimize_or_like_chain 1 --optimize_read_in_order 0 --enable_multiple_prewhere_read_steps 1 --read_in_order_two_level_merge_threshold 91 --optimize_aggregation_in_order 1 --aggregation_in_order_max_block_bytes 630551 --min_compress_block_size 2373843 --max_compress_block_size 1055975 --use_uncompressed_cache 1 --min_bytes_to_use_direct_io 1 --min_bytes_to_use_mmap_io 10737418240 --local_filesystem_read_method pread --remote_filesystem_read_method read --local_filesystem_read_prefetch 1 --remote_filesystem_read_prefetch 0 --allow_prefetched_read_pool_for_remote_filesystem 1 --filesystem_prefetch_max_memory_usage 32Mi --filesystem_prefetches_limit 0 --filesystem_prefetch_min_bytes_for_single_read_task 1Mi --filesystem_prefetch_step_marks 50 --filesystem_prefetch_step_bytes 0 --compile_aggregate_expressions 0 --compile_sort_description 1 --merge_tree_coarse_index_granularity 27 --optimize_distinct_in_order 1 --optimize_sorting_by_input_stream_properties 1 --http_response_buffer_size 888926 --http_wait_end_of_query True --enable_memory_bound_merging_of_aggregation_results 1 --min_count_to_compile_expression 0 --min_count_to_compile_aggregate_expression 3 --min_count_to_compile_sort_description 0 --session_timezone Mexico/BajaSur
2023-09-11 10:38:31 
2023-09-11 10:38:31 MergeTree settings used in test: --ratio_of_defaults_for_sparse_serialization 1.0 --prefer_fetch_merged_part_size_threshold 1 --vertical_merge_algorithm_min_rows_to_activate 1000000 --vertical_merge_algorithm_min_columns_to_activate 100 --allow_vertical_merges_from_compact_to_wide_parts 1 --min_merge_bytes_to_use_direct_io 9574766357 --index_granularity_bytes 10866505 --merge_max_block_size 17043 --index_granularity 43597 --min_bytes_for_wide_part 0 --marks_compress_block_size 43613 --primary_key_compress_block_size 66470
2023-09-11 10:38:31 
```

I'll try to investigate

**Comment by ruslandoga** [comment]
👋 I built ClickHouse from source today and I am still having problems with the `--database` flag.

First, I can't seem to use `--database` after creating the database without using that flag.

```console
$ ClickHouse/build/programs/clickhouse local --path data --query 'create database demo'
$ ClickHouse/build/programs/clickhouse local --path data --database demo --query 'select 1'
Code: 82. DB::Exception: Database demo already exists.: while loading database `demo` from path data/metadata/demo. (DATABASE_ALREADY_EXISTS)
```

Second, creating a table and reading from it still seems to not work.

```console
$ rm data
$ ClickHouse/build/programs/clickhouse local --path data --database demo --query 'create table demo(a UInt64) engine MergeTree order by a'
$ ClickHouse/build/programs/clickhouse local --path data --database demo --query 'select * from demo'
Code: 60. DB::Exception: Table demo.demo does not exist. (UNKNOWN_TABLE)
```

**Comment by vdimir** [comment]
@ruslandoga

I suppose the behavior described in the second case is expected because it creates a table inside a temporary database. It works the same as without the `--database` option. I don't think we should create a persistent database in case `--database` is passed; it should only change the name from `_local`

[Link to the code](https://github.com/ClickHouse/ClickHouse/blob/70ae994e77eb0d87fe0e3d654cc22114512c36fb/programs/local/LocalServer.cpp#L736-L740)

As for the first case, perhaps we can change the behavior to use an existing persistent database passed via `--database` as default. If no database with such a name exists, then the behavior described above is applied (with creating an in-memory database).

It will be like this:

```bash
$ ~/clickhouse local --path _data --query 'create database demo'

$ ~/clickhouse local --path _data --database demo --query 'select 1' 
1
$ ~/clickhouse local --path _data --database demo --query 'show databases'
INFORMATION_SCHEMA
demo
information_schema
system
$ ~/clickhouse local --path _data --database demo --query 'create table demo(a UInt64) engine MergeTree order by a'

$ ~/clickhouse local --path _data --database demo --query 'select count() from demo'

0
$ 
```

But `create table` without explicit `create database` creates it in memory:

```bash
$ rm -rf _data/
$ ~/clickhouse local --path _data --database demo --query 'create table demo(a UInt64) engine MergeTree order by a'

$ ~/clickhouse local --path _data --database demo --query 'select * from demo'

Code: 60. DB::Exception: Table demo.demo does not exist. (UNKNOWN_TABLE)
$ 
```
WDYT?

**Pull request merged**
