### PR TITLE
Fix for 992 and friends

### PR DESCRIPTION
**Pull request by tavplubix**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Looks like it runs too many mutations sometimes and fails to process them within the timeout. So if a query waits for mutations - the test fails

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-clickhouse-ci-2** [comment]
*This is an automated comment for commit 3abf636853e755d0a5264eb568ce895e55749920 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/66785/3abf636853e755d0a5264eb568ce895e55749920/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/b1b5123a6ab1262bab2c9849a1233e38189f686b/docs_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
Requires fixing the `02950_part_log_bytes_uncompressed` test.

**Comment by alexey-milovidov** [comment]
#66803

**Comment by alexey-milovidov** [comment]
Now it requires fixing the test "nested_dynamic_merges"
https://d1k2gkhrlfqv31.cloudfront.net/clickhouse-test-reports-private/12892/0eadb478bb79050721a1cab8a1b96672572372a1/stateless_tests__asan__s3_storage__[3_3].html

**Comment by alexey-milovidov** [comment]
@tavplubix it does not fix the test, see https://s3.amazonaws.com/clickhouse-test-reports/66811/44138b00954328f02742ac485fb921d983ffd7bb/stateless_tests__asan__[2_2].html

**Comment by alexey-milovidov** [comment]
Test has failed: https://s3.amazonaws.com/clickhouse-test-reports/0/516432e42a8dd394cdda460b39e956de16a2446a/stateless_tests__coverage__[4_6].html

**Comment by alexey-milovidov** [comment]
Please resubmit.

**Comment by alexey-milovidov** [comment]
@tavplubix I checked the test `03145_non_loaded_projection_backup` that failed in this pull request. It was never failing before: https://play.clickhouse.com/play?user=play#U0VMRUNUIGNoZWNrX3N0YXJ0X3RpbWUsIGNoZWNrX25hbWUsIHRlc3RfbmFtZSwgcmVwb3J0X3VybApGUk9NIGNoZWNrcwpXSEVSRSBjaGVja19zdGFydF90aW1lID49IG5vdygpIC0gSU5URVJWQUwgMSBZRUFSCiAgICBBTkQgcHVsbF9yZXF1ZXN0X251bWJlciA9IDAKICAgIEFORCB0ZXN0X3N0YXR1cyAhPSAnU0tJUFBFRCcKICAgIEFORCB0ZXN0X3N0YXR1cyBMSUtFICdGJScKICAgIEFORCBjaGVja19zdGF0dXMgIT0gJ3N1Y2Nlc3MnCiAgICBBTkQgcG9zaXRpb24odGVzdF9uYW1lLCAnMDMxNDVfbm9uX2xvYWRlZF9wcm9qZWN0aW9uX2JhY2t1cCcpID4gMApPUkRFUiBCWSBjaGVja19zdGFydF90aW1l

**Comment by tavplubix** [comment]
> @tavplubix I checked the test 03145_non_loaded_projection_backup that failed in this pull request. It was never failing before

@alexey-milovidov, I checked it too, and it was failing before, it just fails rarely: 
https://s3.amazonaws.com/clickhouse-test-reports/61995/2981ba922d34d29f8723eb8ac52c1ef535490b99/stateless_tests__msan__[2_6].html
https://s3.amazonaws.com/clickhouse-test-reports/65359/97572073cb4be716d3db4c17bd85b0996449a7c0/stateless_tests__tsan__s3_storage__[2_5].html
https://s3.amazonaws.com/clickhouse-test-reports/65833/4c277317283bae26127d6ffca6d55253179eea95/stateless_tests__debug__[2_5].html
https://s3.amazonaws.com/clickhouse-test-reports/65786/d481eeaa4191954114af3775050877a15e592adc/stateless_tests__asan__[4_4].html
https://s3.amazonaws.com/clickhouse-test-reports/65884/0e293203ac0e6dc15bee03303c414ad10898949a/stateless_tests__asan__[4_4].html

**Pull request merged**
