### PR TITLE
TTL: Only drop altogether the expired parts and not partially prune them.

### PR DESCRIPTION
**Pull request by svladykin**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

For changelog. Remove if this is non-significant change.

Category (leave one):
- Performance Improvement

Short description (up to few sentences):
MergeTree now has an additional option `ttl_only_drop_parts` (disabled by default) to avoid partial pruning of parts, so that they dropped completely when all the rows in a part are expired. 

This allows to have shorter `merge_with_ttl_timeout` times and lower impact on systems performance.

Also fixes a performance bug in `TTLBlockInputStream::readImpl()`: if we know that we will not need the data, we must never read the child stream. This change is the most risky here though.

TODO: Need to add tests.

### CODE REVIEW

**Comment by svladykin** [comment]
I click on Details for the failed Performance test and it time outs.

**Comment by CurtizJ** [comment]
Performance tests have been failed because of CI problems.

**Review by CurtizJ — COMMENTED** [review]
It's ok. But why did you revert performance bug fix? Seems that it's correct. Also, will you add a test?

**Comment by svladykin** [comment]
I reverted it because there were other tests failures. I was thinking that this fix caused them.
Maybe they happened because of the CI problems as well? 
I do not see the previous CI run results, I'll give another try to push the fix.

As for testing, do you have any ideas how to test this stuff better? The new flag does not change the client visible behaviour. Look at some metrics?

**Comment by CurtizJ** [comment]
Yes, tests failures are not related to your changes. 

It's hard to check performance with TTL using CI tests. I think it's reasonable to write unit tests for TTLMergeSelector, because TTL tests use `OPTIMIZE ... FINAL` and  selector is stayed almost unused. But it's not exactly part of this task, because test is needed for all it's functionality. So, I can add this test later.

**Comment by CurtizJ** [comment]
00974_query_profiler - flappy test failed by timeout.

**Review by CurtizJ — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
I will look at query_profiler test.

**Comment by alexey-milovidov** [comment]
query_profiler test has been fixed.

**Comment by alexey-milovidov** [comment]
@CurtizJ ?

**Pull request merged**
