### PR TITLE
Millisecond and microsecond support in date_diff / age functions

### PR DESCRIPTION
**Pull request by kardymonds**
Same https://github.com/ClickHouse/ClickHouse/pull/51291 (was reverted by https://github.com/ClickHouse/ClickHouse/pull/52129) with changes:
* all tests in one file
* add timezone to fix flaky tests

The task actually consistsed of tasks:

* new units (millisecond/microsecond) for "date_diff() and age()"
* microsecond precision for age(), (date_diff() works with precision = unit)
* bug in `DateTimeTransforms.h` in components.whole for negative fractional value (affect to `date_diff/age` and other functions (like `toYYYYMMDDhhmmss()`) )

### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Functions "date_diff() and age()" now support millisecond/microsecond unit and work with microsecond precision.

### Documentation entry for user-facing changes

- [V ] Documentation is written (mandatory for new features)

### CODE REVIEW

**Comment by kardymonds** [comment]
@hanfei1991 Do not know how to see the output (diff stateless tests) of flaky tests? (in my old pull request all tests passed, but apparently they fell down in the master,  but didn’t see where - they quickly reverted)

**Comment by robot-ch-test-poll3** [comment]
This is an automated comment for commit 0353eb1f4578c88bbea0b6051a9c0db86cd19cc4 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/52181/0353eb1f4578c88bbea0b6051a9c0db86cd19cc4/ci_running.html)
The overall status of the commit is 🔴 failure

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🔴 failure</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Comment by hanfei1991** [comment]
> @hanfei1991 Do not know how to see the output (diff stateless tests) of flaky tests? (in my old pull request all tests passed, but apparently they fell down in the master, but i didn’t see where - they quickly reverted)

@alexey-milovidov could you show me an example of the flaky test for https://github.com/ClickHouse/ClickHouse/pull/51291 ?
I could not find one in CIDB

**Comment by kardymonds** [comment]
I found, this can be seen through a tricky query[(https://play.clickhouse.com/play...)](https://play.clickhouse.com/play?user=play#CldJVEgKICAgICcwMjE2MF9zcGVjaWFsX2Z1bmN0aW9ucycgQVMgbmFtZV9zdWJzdHIsCiAgICA5MCBBUyBpbnRlcnZhbF9kYXlzLAogICAgKCdTdGF0ZWxlc3MgdGVzdHMgKGFzYW4pJywgJ1N0YXRlbGVzcyB0ZXN0cyAoYWRkcmVzcyknLCAnU3RhdGVsZXNzIHRlc3RzIChhZGRyZXNzLCBhY3Rpb25zKScsICdTdGF0ZWxlc3MgdGVzdHMgKHVic2FuKScpIEFTIGJhY2twb3J0X2FuZF9yZWxlYXNlX3NwZWNpZmljX2NoZWNrcwpTRUxFQ1QKICAgIHRvU3RhcnRPZkRheShjaGVja19zdGFydF90aW1lKSBBUyBkLAogICAgY291bnQoKSwKICAgIGdyb3VwVW5pcUFycmF5KHB1bGxfcmVxdWVzdF9udW1iZXIpIEFTIHBycywKICAgIGFueShyZXBvcnRfdXJsKQpGUk9NIGNoZWNrcwpXSEVSRSAoKG5vdygpIC0gdG9JbnRlcnZhbERheShpbnRlcnZhbF9kYXlzKSkgPD0gY2hlY2tfc3RhcnRfdGltZSkgQU5EIChwdWxsX3JlcXVlc3RfbnVtYmVyIE5PVCBJTiAoCiAgICBTRUxFQ1QgcHVsbF9yZXF1ZXN0X251bWJlciBBUyBwcm4KICAgIEZST00gY2hlY2tzCiAgICBXSEVSRSAocHJuICE9IDApIEFORCAoKG5vdygpIC0gdG9JbnRlcnZhbERheShpbnRlcnZhbF9kYXlzKSkgPD0gY2hlY2tfc3RhcnRfdGltZSkgQU5EIChjaGVja19uYW1lIElOIChiYWNrcG9ydF9hbmRfcmVsZWFzZV9zcGVjaWZpY19jaGVja3MpKQopKSBBTkQgKHBvc2l0aW9uKHRlc3RfbmFtZSwgbmFtZV9zdWJzdHIpID4gMCkgQU5EICh0ZXN0X3N0YXR1cyBJTiAoJ0ZBSUwnLCAnRVJST1InLCAnRkxBS1knKSkKR1JPVVAgQlkgZApPUkRFUiBCWSBkIERFU0MK)

**Comment by den-crane** [comment]
BTW, now you can use `set session_timezone='UTC'`

and anyway you can use clickhouse-local see https://github.com/ClickHouse/ClickHouse/blob/master/tests/queries/0_stateless/02373_datetime64_monotonicity.sh

```
tz=UTC clickhouse-local < your_sql
```

**Comment by hanfei1991** [comment]
I still don't understand why the old pr causes `02160_special_functions` flaky

**Comment by kardymonds** [comment]
@hanfei1991 
There was a case
```SELECT DATEDIFF(microsecond, '1969-12-31 23:59:59.999950'::DateTime64(6), '1970-01-01 00:00:00.000010'::DateTime64(6));```
and when the tests were randomized (in master) with a time zone `America/Mazatlan `
```1969-12-31 23:59:59.999950'::DateTime64(6) ```  return wrong value (Int64) because of https://github.com/ClickHouse/ClickHouse/issues/42653

**Review by hanfei1991 — APPROVED** [review]

**Pull request merged**
