### PR TITLE
use IDisk's interfaces to operate filesystem in Keeper

### PR DESCRIPTION
**Pull request by LiuYangkuan**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Replacing std::filesystem operations with DiskPtr APIs,  because `IDisk` is filesystem abstraction.
This way can make keeper to store logs and snapshots into more types of Disk.

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by LiuYangkuan** [comment]
@antonio2368 ready to review.

**Comment by LiuYangkuan** [comment]
@antonio2368 ready to review.

**Comment by LiuYangkuan** [comment]
@antonio2368 It breaks when build `clickhouse-keeper` target, "undefined symbol of DiskLocal". I have try to link `libdbmsd.a`, but don't works. how can I fix it?

**Comment by antonio2368** [comment]
> @antonio2368 It breaks when build `clickhouse-keeper` target, "undefined symbol of DiskLocal". I have try to link `libdbmsd.a`, but don't works. how can I fix it?

It happens when standalone build is done (to test locally call `cmake -DBUILD_STANDALONE_KEEPER=ON`)
Inside `programs/keeper/CMakeLists.txt` you will see part that defines manually all the necessary source files required for build and add what's missing. 
You should NOT link with `libdbms` we don't want to pull entire ClickHouse into standalone build.
Also, if you end up including too much we have to see if we can minimize it by extracting parts of code in a more clever way or simply put this on hold.

**Comment by LiuYangkuan** [comment]
> 

It seems difficult to resolve circle dependancies, because `src/Disks` is a high level component.

**Comment by alexey-milovidov** [comment]
Will be merged in #50098.

**Pull request closed without merging**
