### PR TITLE
Switch CI to Clang 17

### LINKED ISSUE #54723: Remove Woboq Codebrowser
Woboq Codebrowser is an amazing tool, and I would be happy to continue publishing its results, but it is difficult to support because currently, the maximum LLVM version that it can use is 15, while ClickHouse uses 16 and preparing for LLVM 17.

### PR DESCRIPTION
**Pull request by rschu1ze**
For reference, see previous switch to clang 16: #49678

Fixes: #54723
(removes Woboq infrastructure, it blocks the upgrade)

### Changelog category (leave one):
- Build/Testing/Packaging Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Bumped the compiler of official and continuous integration builds of ClickHouse from Clang 16 to 17.

### CODE REVIEW

**Comment by robot-ch-test-poll1** [comment]
This is an automated comment for commit 1fc731fa6332db87daaf820ba377b59f5332a19c with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/53831/1fc731fa6332db87daaf820ba377b59f5332a19c/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Comment by Felixoid** [comment]
https://github.com/ClickHouse/ClickHouse/issues/50077

https://github.com/ClickHouse/ClickHouse/blob/master/tests/ci/codebrowser_check.py#L64

I'd really like to have it fixed. But it does not work for long already =\

**Review by Felixoid — APPROVED** [review]
Everything is pretty straight forward!

**Comment by rschu1ze** [comment]
Tests in the previous run were green (except stress tests that timed out but this happens also in other PRs). In particular, performance tests were green. Fixing clang-tidy was a cat-and-mouse game, but it should also be green now with the last commit. Allow me to merge, in case there is any fallout (e.g. compiler errors due to new warnings), I am happy to fix in follow-up PRs.

**Comment by baibaichen** [comment]
@rschu1ze Just curious, what's the benefits of upgrading to clang 17 since we upgraded to clang-16 only half year ago. Is Clang 16 still supported?

**Comment by rschu1ze** [comment]
We generally want to keep up with new compilers to benefit from better optimization / support of C++20 / warnings etc. Clang 16 will continue to work on a best effort basis, i.e. if some PR introduces code that compiles with v17 but not v16, then CI will not notice (feel free to fix such places if you *rely* on Clang 16). The general suggestion is to upgrade to v17 though.

**Pull request merged**
