### PR TITLE
Fix analyzer - hide arguments for secret functions

### PR DESCRIPTION
**Pull request by yakov-olkhovskiy**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

fixes test_mask_sensitive_info/test.py::test_encryption_functions

### CODE REVIEW

**Review by novikd — COMMENTED** [review]
Looks pretty good, but we probably also need to add some code to `FunctionNode::dumpTree` the same ways as we have for AST now.

**Comment by yakov-olkhovskiy** [comment]
@novikd I don't see we have such functionality in `IAST::dumpTree` - there are some functions to take care of secrets, but they are utility function mostly...

**Comment by novikd** [comment]
@yakov-olkhovskiy I mean we need to repeat the logic for secrets we have in `ASTFunction::formatImplWithoutAlias`.

**Comment by KochetovNicolai** [comment]
test_backup_restore_s3/test.py::test_user_specific_auth is flaky
test_broken_projections os broken

**Pull request merged**
