### PR TITLE
Update libcxx and use unstable ABI to provide better performance

### PR DESCRIPTION
**Pull request by danlark1**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Performance Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Update libcxx and use unstable ABI to provide better performance

Detailed description / Documentation draft:
As libcxx provides unstable ABI option which is allowed to break ABI in order to gain performance, let's try to use this option. It includes
1. Better std::string performance, avoiding memmove where the assignment can guarantee no aliasing
2. Better std::string layout which guarantees alignment
3. Better smart pointers which are annotated with [[clang::trivial_abi]]
4. Better std::function, especially for small functions
5. Better index and narrowing handling of std::variant

ClickHouse is safe to use this option as everything is built from the source. The performance savings showed only speedup in one test group, however binary size was dropped by 5% which is nice to have anyway

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]

**Comment by danlark1** [comment]
logical_functions_* became slightly faster, other than that, performance diff is zero

I double checked and the macros actually work so it is not a misconfiguration issue

I'll fix macOS build somewhere soon

**Comment by danlark1** [comment]
Also the binary size dropped from 1939.04MB to 1859.7MB which is nice to have

**Comment by danlark1** [comment]
@alexey-milovidov feel free to merge

**Comment by baibaichen** [comment]
@danlark1 

I believe there is an issue in libcxx which cause build failed in native macos with MacSDKs 10.15, see my comments 
on https://github.com/llvm/llvm-project/commit/67dfba96296b37f7bac9b4a68572288bc44b63b2, here are comments:

```
    // For C++14, usr/include/malloc/_malloc.h declares aligned_alloc()) only
    // with the MacOSX11.0 SDK in Xcode 12 (which is what adds
    // MAC_OS_X_VERSION_10_16), even though the function is marked
    // availabe for 10.15. That's why the preprocessor checks for 10.16 but
    // the __builtin_available checks for 10.15.
    // People who use C++17 could call aligned_alloc with the 10.15 SDK already.
```

The workaround is upgrading macos sdk to 11.1. i.e. upgrading to big sur

**Pull request merged**
