### PR TITLE
add message print settings and CMAKE_BUILD_TYPE set red color print

### PR DESCRIPTION
**Pull request by guoxiaolongzte**
### Changelog category (leave one):
- Build/Testing/Packaging Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
add message print settings and CMAKE_BUILD_TYPE(build important features) set red color print

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
I don't think it is good to highlight a normal message in red. People may think it is an error.

**Comment by alexey-milovidov** [comment]
Additionally, by highlighting one message in red, you make an implicit question, why other messages are not highlighted in red, and how the message is more important than other messages. To avoid this problem - do nothing instead.

**Comment by alexey-milovidov** [comment]
> add message print settings and CMAKE_BUILD_TYPE(build important features) set red color print

Your changelog entry does not explain the motivation behind this change. It does not start with a capital letter and does not end with a period, which is unacceptable.

**Comment by guoxiaolongzte** [comment]
I will modify it and resubmit the PR.

**Comment by rschu1ze** [comment]
The biggest reason against colors is that build logs will appear in CI (e.g. https://github.com/ClickHouse/ClickHouse/actions/runs/6646158782/job/18067996362?pr=55983) and that only shows the escape sequences.

**Pull request closed without merging**
