### PR TITLE
Add handling of SQL_TINYINT and SQL_BIGINT, fix SQL_FLOAT in ODBC Bridge

### PR DESCRIPTION
**Pull request by traceon**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

For changelog. Remove if this is non-significant change.

Category (leave one):
- Bug Fix

Short description (up to few sentences):

Add handling of SQL_TINYINT and SQL_BIGINT, and fix handling of SQL_FLOAT data source types in ODBC Bridge.

### CODE REVIEW

**Comment by akuzm** [comment]
Should we add an integration test for this?

**Comment by alex-zaitsev** [comment]
> Should we add an integration test for this?

We can, but with MySQL the problem with SQL_FLOAT was not reproducible, because it reports different data types. So extending MySQL integration test would not help. We've faced this issue with MSSQL. I am not sure it makes sense to have MSSQL in integration tests just for this purpose.

**Comment by alexey-milovidov** [comment]
We should add integration test with MS SQL Server if the license permits:
https://hub.docker.com/_/microsoft-mssql-server

**Comment by alexey-milovidov** [comment]
The purpose of integration tests is to test as many integrations as possible.

**Comment by alexey-milovidov** [comment]
But first please add integration test of ClickHouse connection to ClickHouse through its own ODBC driver.

**Pull request merged**
