### PR TITLE
Enable ThreadFuzzer with random migrations

### PR DESCRIPTION
**Pull request by alexey-milovidov**
Changelog category (leave one):
- Non-significant (changelog entry is not required)

Detailed description / Documentation draft:
Not intended for merge. Only to run CI tests and catch a fire.

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
Nice catch!
https://clickhouse-test-reports.s3.yandex.net/9516/27fba2278b3222198f6bb153475eb59a35b33855/functional_stateless_tests_(thread)/stderr.log

**Comment by alexey-milovidov** [comment]
No more issues found.
We can selectively enable fuzzer for specific types of builds (functional tests with thread sanitizer).

**Comment by alexey-milovidov** [comment]
Bad test has been found: #10989

**Comment by alexey-milovidov** [comment]
For unknown reason, it took 12 minutes starting odbc-bridge and it does not response in next second.

**Comment by alexey-milovidov** [comment]
Found flaky tests: 01133_max_result_rows, 01474_executable_dictionary.

**Comment by azat** [comment]
>Functional stateless tests (debug) — fail: 1, passed: 2247, skipped: 15

#14957

**Comment by qoega** [comment]
@Mergifyio update

**Comment by nikitamikhaylov** [comment]
@Mergifyio update

**Comment by qoega** [comment]
@Mergifyio update

**Comment by qoega** [comment]
01275_alter_rename_column_default_expr looks like something is bad:
```
2021-06-12 15:43:31 01275_alter_rename_column_default_expr:                                 [ FAIL ] 0.68 sec. - return code 85
2021-06-12 15:43:31 [3407811b5850] 2021.06.12 15:43:31.087853 [ 5694 ] {b8ae2bbc-c277-4642-99fa-167b69562695} <Error> void DB::StorageMergeTree::waitForMutation(DB::Int64, const DB::String &): Code: 341, e.displayText() = DB::Exception: Exception happened during execution of mutation 'mutation_10.txt' with part '20191001_1_1_0_9' reason: 'Code: 47, e.displayText() = DB::Exception: Missing columns: 'value2' while processing query: 'value3, key, value3, date, value1, value2', required columns: 'value3' 'date' 'key' 'value1' 'value2', maybe you meant: ['value3','date','key','value1','value2'] (version 21.7.1.7144)'. This error maybe retryable or not. In case of unretryable error, mutation can be killed with KILL MUTATION query, Stack trace (when copying this message, always include the lines below):
2021-06-12 15:43:31 
2021-06-12 15:43:31 0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x8d8649a in /usr/lib/debug/.build-id/64/054935534e653e4f6d0e6d5773703f0e92fca7.debug
2021-06-12 15:43:31 1. DB::Exception::Exception<char const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&>(int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, char const*&&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&) @ 0x104faee3 in /usr/lib/debug/.build-id/64/054935534e653e4f6d0e6d5773703f0e92fca7.debug
2021-06-12 15:43:31 2. DB::checkMutationStatus(std::__1::optional<DB::MergeTreeMutationStatus>&, std::__1::set<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) @ 0x104fad60 in /usr/lib/debug/.build-id/64/054935534e653e4f6d0e6d5773703f0e92fca7.debug
2021-06-12 15:43:31 3. DB::StorageMergeTree::waitForMutation(long, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x1010ddff in /usr/lib/debug/.build-id/64/054935534e653e4f6d0e6d5773703f0e92fca7.debug
2021-06-12 15:43:31 4. DB::StorageMergeTree::alter(DB::AlterCommands const&, std::__1::shared_ptr<DB::Context const>, std::__1::shared_ptr<DB::RWLockImpl::LockHolderImpl>&) @ 0x1010cdd6 in /usr/lib/debug/.build-id/64/054935534e653e4f6d0e6d5773703f0e92fca7.debug
2021-06-12 15:43:31 5. DB::InterpreterAlterQuery::execute() @ 0xf9403ac in /usr/lib/debug/.build-id/64/054935534e653e4f6d0e6d5773703f0e92fca7.debug
2021-06-12 15:43:31 6. DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, bool, DB::ReadBuffer*) @ 0xfe7031c in /usr/lib/debug/.build-id/64/054935534e653e4f6d0e6d5773703f0e92fca7.debug
2021-06-12 15:43:31 7. DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, bool) @ 0xfe6e943 in /usr/lib/debug/.build-id/64/054935534e653e4f6d0e6d5773703f0e92fca7.debug
2021-06-12 15:43:31 8. DB::TCPHandler::runImpl() @ 0x106ec372 in /usr/lib/debug/.build-id/64/054935534e653e4f6d0e6d5773703f0e92fca7.debug
2021-06-12 15:43:31 9. DB::TCPHandler::run() @ 0x106ff239 in /usr/lib/debug/.build-id/64/054935534e653e4f6d0e6d5773703f0e92fca7.debug
2021-06-12 15:43:31 10. Poco::Net::TCPServerConnection::start() @ 0x133c470f in /usr/lib/debug/.build-id/64/054935534e653e4f6d0e6d5773703f0e92fca7.debug
2021-06-12 15:43:31 11. Poco::Net::TCPServerDispatcher::run() @ 0x133c619a in /usr/lib/debug/.build-id/64/054935534e653e4f6d0e6d5773703f0e92fca7.debug
2021-06-12 15:43:31 12. Poco::PooledThread::run() @ 0x134f9019 in /usr/lib/debug/.build-id/64/054935534e653e4f6d0e6d5773703f0e92fca7.debug
2021-06-12 15:43:31 13. Poco::ThreadImpl::runnableEntry(void*) @ 0x134f52aa in /usr/lib/debug/.build-id/64/054935534e653e4f6d0e6d5773703f0e92fca7.debug
2021-06-12 15:43:31 14. start_thread @ 0x9609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
2021-06-12 15:43:31 15. clone @ 0x122293 in /usr/lib/x86_64-linux-gnu/libc-2.31.so
2021-06-12 15:43:31  (version 21.7.1.7144)
```
01282_system_parts_ttl_info and 00933_ttl_with_default looks flaky.

**Comment by alexey-milovidov** [comment]
@Mergifyio update

**Comment by alexey-milovidov** [comment]
@Mergifyio update

**Comment by alexey-milovidov** [comment]
@Mergifyio update

**Comment by alexey-milovidov** [comment]
@mergifyio update

**Pull request closed without merging**
