### PR TITLE
bugfix: addresses_expr ignored for psql named collections

### PR DESCRIPTION
**Pull request by joelynch**
The `addresses_expr` field in named collections is ignored for psql.  Setting this field raises a Poco error like this:

```
DB::Exception: No address specified. (LOGICAL_ERROR)
```

I just copied what mysql does with this field.

### Changelog category (leave one):

- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

* Properly use `addresses_expr` field on named collections for PostgreSQL storage

### CODE REVIEW

**Comment by robot-clickhouse** [comment]
*This is an automated comment for commit b4bef78e639a79335e35b49ba153e82de086bc1e with description of existing statuses. It's updated for the latest CI running*

[❌ Click here](https://s3.amazonaws.com/clickhouse-test-reports/57874/b4bef78e639a79335e35b49ba153e82de086bc1e/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td><a href="https://github.com/ClickHouse/ClickHouse/actions/runs/7211663217">✅ success</a></td></tr>
<tbody>
</table>
</details>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/57874/b4bef78e639a79335e35b49ba153e82de086bc1e/ci_running.html">❌ failure</a></td></tr>
<tbody>
</table>

**Comment by jsc0218** [comment]
test_storage_postgresql should not failed.

**Comment by joelynch** [comment]
> test_storage_postgresql should not fail.

Fixed @jsc0218  :)

**Comment by jsc0218** [comment]
The failure might relate to #58026. so merged, thanks for your update.

**Pull request merged**
