### PR TITLE
Followup for #56996

### PR DESCRIPTION
**Pull request by vdimir**
### Changelog category (leave one):

- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
...

### CODE REVIEW

**Comment by robot-clickhouse-ci-2** [comment]
*This is an automated comment for commit a672d6950e8749aa9e8dc785832580f8fd5208e7 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/58289/a672d6950e8749aa9e8dc785832580f8fd5208e7/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/58289/a672d6950e8749aa9e8dc785832580f8fd5208e7/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Review by devcrafter — APPROVED** [review]

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
@vdimir, could you please fix a conflict?

**Comment by alexey-milovidov** [comment]
@vdimir, would you mind finishing this PR?

**Comment by vdimir** [comment]
> Stateless tests (tsan) [4/4] — Server died, fail: 0, passed: 895, skipped: 16 [Details](https://s3.amazonaws.com/clickhouse-test-reports/58289/5c54c7025bd87f1e4239354b5f3c0adff188dd3a/stateless_tests__tsan__[4_4].html)

Pretty interesting failure


<details>
<summary>clickhouse-test reported ProcessLookupError</summary>

```
2024-08-12 17:46:45 02907_http_exception_json_bug:                                          [ OK ] 29.26 sec.
2024-08-12 17:49:00 2173
2024-08-12 17:51:29 03173_row_binary_and_native_with_binary_encoded_types:                  [ OK ] 104.36 sec.
2024-08-12 17:51:29 Process Process-3:
2024-08-12 17:51:29 Traceback (most recent call last):
2024-08-12 17:51:29   File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
2024-08-12 17:51:29     self.run()
2024-08-12 17:51:29   File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
2024-08-12 17:51:29     self._target(*self._args, **self._kwargs)
2024-08-12 17:51:29   File "/usr/bin/clickhouse-test", line 2527, in run_tests_process
2024-08-12 17:51:29     return run_tests_array(*args, **kwargs)
2024-08-12 17:51:29   File "/usr/bin/clickhouse-test", line 2245, in run_tests_array
2024-08-12 17:51:29     stop_tests()
2024-08-12 17:51:29   File "/usr/bin/clickhouse-test", line 442, in stop_tests
2024-08-12 17:51:29     cleanup_child_processes(os.getpid())
2024-08-12 17:51:29   File "/usr/bin/clickhouse-test", line 430, in cleanup_child_processes
2024-08-12 17:51:29     child_pgid = os.getpgid(child)
2024-08-12 17:51:29 ProcessLookupError: [Errno 3] No such process
2024-08-12 17:51:29 Child processes of 2223:
2024-08-12 17:51:29 33316 /bin/sh -c pgrep --parent 2223 -a
2024-08-12 17:51:29 01852_cast_operator_bad_cases:                                          [ OK ] 134.39 sec.
2024-08-12 17:51:29 Process Process-10:
2024-08-12 17:51:29 Traceback (most recent call last):
2024-08-12 17:51:29   File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
2024-08-12 17:51:29     self.run()
2024-08-12 17:51:29   File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
2024-08-12 17:51:29     self._target(*self._args, **self._kwargs)
2024-08-12 17:51:29   File "/usr/bin/clickhouse-test", line 2527, in run_tests_process
2024-08-12 17:51:29     return run_tests_array(*args, **kwargs)
2024-08-12 17:51:29   File "/usr/bin/clickhouse-test", line 2245, in run_tests_array
2024-08-12 17:51:29     stop_tests()
2024-08-12 17:51:29   File "/usr/bin/clickhouse-test", line 442, in stop_tests
2024-08-12 17:51:29     cleanup_child_processes(os.getpid())
2024-08-12 17:51:29   File "/usr/bin/clickhouse-test", line 430, in cleanup_child_processes
2024-08-12 17:51:29     child_pgid = os.getpgid(child)
2024-08-12 17:51:29 ProcessLookupError: [Errno 3] No such process
2024-08-12 17:51:29 Child processes of 2251:
2024-08-12 17:51:29 33323 /bin/sh -c pgrep --parent 2251 -a

```

</details>


However server was running and several minutes after that got termination signal:

```
2024.08.12 17:59:55.297800 [ 1505 ] {} <Debug> system.zookeeper_log (e179afda-05ed-4bd4-9c4e-ed19f5bf12f9): Removing 6 parts from filesystem (serially): Parts: [202408_87_116_6, 202408_117_117_0, 202408_118_118_0, 202408_119_119_0, 
202408_120_120_0, 202408_121_121_0]
2024.08.12 17:59:55.304271 [ 1505 ] {} <Debug> system.zookeeper_log (e179afda-05ed-4bd4-9c4e-ed19f5bf12f9): Removing 6 parts from memory: Parts: [202408_87_116_6, 202408_117_117_0, 202408_118_118_0, 202408_119_119_0, 202408_120_120_
0, 202408_121_121_0]
2024.08.12 17:59:55.461758 [ 854 ] {} <Trace> BaseDaemon: Received signal 15
2024.08.12 17:59:55.461935 [ 854 ] {} <Information> Application: Received termination signal (Terminated)
2024.08.12 17:59:55.462084 [ 851 ] {} <Debug> Application: Received termination signal.
2024.08.12 17:59:55.462544 [ 851 ] {} <Debug> Application: Waiting for current connections to close.
2024.08.12 17:59:56.000218 [ 1565 ] {} <Trace> AsynchronousMetrics: MemoryTracking: was 4.85 GiB, peak 8.39 GiB, free memory in arenas 0.00 B, will set to 4.82 GiB (RSS), difference: -33.46 MiB
```

**Pull request merged**
