### PR TITLE
update mariadb-connector-c-cmake

### PR DESCRIPTION
**Pull request by benbiti**
update mariadb-connector-c-cmake remove OS_LINUX check

### Changelog category (leave one):
- Not for changelog

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alesapin** [comment]
@mergifyio update

**Comment by alexey-milovidov** [comment]
@Mergifyio update

**Comment by alexey-milovidov** [comment]
@benbiti It does not build on Mac, Mac M1 and FreeBSD.

**Comment by benbiti** [comment]
i will update this PR for Mac.

**Comment by alexey-milovidov** [comment]
Stale.

**Pull request closed without merging**
