### PR TITLE
Add mapAccumulate function

### PR DESCRIPTION
**Pull request by ildus**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

For changelog. Remove if this is non-significant change.

Category
- New Feature

Short description:

* Adds `mapAccumulate` function. It calculates a tuple of enumerated keys and accumulates sums of values for two sorted arrays (keys and values). The optional third argument sets and extends the upper limit of the keys.
* Extends `sumMap` so it could take tuple of arrays as argument (can be used in combination with `mapAccumulate`.

Detailed description (optional):

Basicly this function is an attempt to replace the following expression which we have to use now:
```
if(keys[1] <= max_key, arrayMap(x -> keys[1] + x - 1, arrayEnumerate(arrayResize(emptyArrayInt32(), max_key - keys[1] + 1))), []), if(keys[1] <= max_key, arrayCumSum(arrayMap(x -> values[indexOf(keys, keys[1] + x - 1)], arrayEnumerate(arrayResize(emptyArrayInt32(), max_key - keys[1] + 1)))), [])
```
and it is not efficient.

Example:
```
SELECT mapAccumulate([1, 2, 6], [10, 20, 30])

┌─mapAccumulate([1, 2, 6], [10, 20, 30])─┐
│ ([1,2,3,4,5,6],[10,30,30,30,30,60])    │
└────────────────────────────────────────┘
```

With optional third argument:

```
SELECT mapAccumulate([1, 2, 6], [10, 20, 30], 8)

┌─mapAccumulate([1, 2, 6], [10, 20, 30], 8)─────┐
│ ([1,2,3,4,5,6,7,8],[10,30,30,30,30,60,60,60]) │
└───────────────────────────────────────────────┘
```

According to our benchmarks based on our data, it works about 5 times faster.

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
One test has failed.

> Functional stateless tests (ubsan) — fail:21, passed:944, skipped:2 

And this is unrelated, it is fixed in master.

**Comment by alexey-milovidov** [comment]
The idea is Ok, but it's hard to grasp what this function does from its name.
Maybe a different name will be better...

**Comment by alexey-milovidov** [comment]
Let's propose some different names:

`fillSortedArraysCumulative`

**Comment by alexey-milovidov** [comment]
Maybe you need two functions instead:
```
SELECT mapFill([1, 2, 6], [10, 20, 30])

([1, 2, 3, 4, 5, 6], [10, 20, 0, 0, 0, 30])
```

```
SELECT arrayCumSum([10, 20, 0, 0, 0, 30])

[10, 30, 30, 30, 30, 60]
```

**Comment by ildus** [comment]
Yeah, `mapFill` would help but function has third argument `max_key` which is used to extend both arrays. So in the end `mapFill` would require this `max_key` argument and final expression would look like this (10 is `max_key`):

```
SELECT mapFill([1, 2, 6], 10), arrayCumSum(mapFill([1, 2, 6], [10, 20, 30], 10)[1]);
[1,2,3,4,5,6,7,8,9,10], [10, 20, 30, 30, 30, 60, 60, 60, 60, 60]
```

Not sure if it's better than one function, but we can live with this alternative, and I'm ready to implement `mapFill` function.

**Pull request closed without merging**
