### PR TITLE
Builtin skim

### PR DESCRIPTION
**Pull request by azat**
### Checklist:
- [x] use cxx (bridge) to make a bridge between rust and C++
- [x] configure rustc
- [x] configure cxxbridge
- [x] fix [cross compilation](https://s3.amazonaws.com/clickhouse-builds/43922/866162403e53b3b57a6c66df40d40ad38b543f7a/clickhouse_build_check/report.html) (this is only the last error for aarch64)
- [x] fix [shared build](https://s3.amazonaws.com/clickhouse-builds/43922/866162403e53b3b57a6c66df40d40ad38b543f7a/clickhouse_special_build_check/report.html)
- [ ] [extra shared libs](https://s3.amazonaws.com/clickhouse-builds/43922/866162403e53b3b57a6c66df40d40ad38b543f7a/clickhouse_build_check/report.html) (but not in result binary) 
- [ ] ~~move out `*LineReader` out from `base` (to avoid extra libraries depedencies)~~ - will be done later, since `LineReader` itself can be removed, and I don't want to mix lots of changes here
- [ ] way to avoid RW for source dir

### Changelog category (leave one):
- Build/Testing/Packaging Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Integrate skim into the client/local

Note, that it can the fail the client if the skim itself will fail,
however I haven't seen it panicd, so let's try.

### CODE REVIEW

**Comment by azat** [comment]
All builds passed, this one is ready for review.
And I've checked the binary for apple - fuzzy search works.

But due to some issues with rust dependencies there is no fuzzy search support for freebsd (you can find details in the comments).

**Review by alexey-milovidov — APPROVED** [review]
The code LGTM

**Comment by azat** [comment]
Actually this PR should break the tests for reverse-search (i.e. `01910_client_replxx_container_overflow_long`), but it does not, because on CI skim does not started, apparently due to lack of terminal, I'm looking into it.

**Comment by azat** [comment]
Oh, and the tests indeed broken, the report publisher is wrong:

```
Traceback (most recent call last):
  File "/home/ubuntu/actions-runner/_work/_temp/stateless_debug/ClickHouse/tests/ci/functional_test_check.py", line 327, in <module>
    state, description, test_results, additional_logs = process_results(
  File "/home/ubuntu/actions-runner/_work/_temp/stateless_debug/ClickHouse/tests/ci/functional_test_check.py", line 173, in process_results
    test_results = list(csv.reader(results_file, delimiter="\t"))  # type: ignore
_csv.Error: line contains NUL
INFO:root:Update Mergeable Check by Stateless tests (asan)
```

**Pull request merged**
