### PR TITLE
Allow IPv6 to UInt128 conversion and binary arithmetic

### LINKED ISSUE #56487: Missing bitwise operator (`bitAnd`) support for IPv6 Native Type and IPv6StringToNum not compatible with IPv6 Data Type
**Describe the issue**
* [Background/Context] As of ClickHouse 23.1 (https://github.com/ClickHouse/ClickHouse/pull/43221), the IPv6 data type is `UInt128` big-endian data type. In the versions before that (22.X), IPv6 dates not support the IPa type was a `FixedString(16)`. This feature is not listed as backwards-incomaptible in the Release docs.
* The `IPv6StringToNum` function still returns a `FixedString(16)` data type instead of an `IPv6` data type.
* Moreover the `bitAnd` operator does not support the IPv6 Data type anymore (It was supported in previous versions). `bitAnd` operator on IPv6 data type is exceptionally useful when it comes to network masking and other IP-related operations.

**How to reproduce**
* Which ClickHouse server versions are incompatible? 
    * 23.1 onwards [However, I only tested 23.3. and 23.8]

* 
    ```sql
    SELECT bitAnd(toIPv4('1.2.3.4'), 20000000); -- works correctly
    SELECT bitAnd(toIPv4('1.2.3.4'), IPv4StringToNum('1.2.0.0')); -- works correctly
    SELECT bitAnd(toIPv6('43:AB::'), toIPv6('ffff:ffff:0000:0000:0000:0000:0000:0000')); -- does not work
    SELECT bitAnd(toIPv6('43:AB::'), IPv6StringToNum('ffff:ffff:0000:0000:0000:0000:0000:0000'));  -- does not work
    ```

**Error message and/or stacktrace**
* ClickHouse 23.3.9

    ```sql
    myserver :) SELECT bitAnd(toIPv4('1.2.3.4'), 20000000);

    SELECT bitAnd(toIPv4('1.2.3.4'), 20000000)

    Query id: 6f2fb352-fe04-43a1-9882-a1d602e2885d

    ┌─bitAnd(toIPv4('1.2.3.4'), 20000000)─┐
    │                            16777472 │
    └─────────────────────────────────────┘

    1 row in set. Elapsed: 0.004 sec. 

    myserver :) SELECT bitAnd(toIPv4('1.2.3.4'), IPv4StringToNum('1.2.0.0'))

    SELECT bitAnd(toIPv4('1.2.3.4'), IPv4StringToNum('1.2.0.0'))

    Query id: 24f317f1-0d8a-42b4-9d00-686161ed3f03

    ┌─bitAnd(toIPv4('1.2.3.4'), IPv4StringToNum('1.2.0.0'))─┐
    │                                              16908288 │
    └───────────────────────────────────────────────────────┘

    1 row in set. Elapsed: 0.005 sec. 

    myserver :) SELECT bitAnd(toIPv6('43:AB::'), toIPv6('ffff:ffff:0000:0000:0000:0000:0000:0000'))

    SELECT bitAnd(toIPv6('43:AB::'), toIPv6('ffff:ffff:0000:0000:0000:0000:0000:0000'))

    Query id: 3da6dc0d-0672-4d80-bc78-d5813dfc09d5


    0 rows in set. Elapsed: 0.005 sec. 

    Received exception from server (version 23.3.9):
    Code: 43. DB::Exception: Received from localhost:9000. DB::Exception: Illegal types IPv6 and IPv6 of arguments of function bitAnd: While processing bitAnd(toIPv6('43:AB::'), toIPv6('ffff:ffff:0000:0000:0000:0000:0000:0000')). (ILLEGAL_TYPE_OF_ARGUMENT)

    myserver :) SELECT bitAnd(toIPv6('43:AB::'), IPv6StringToNum('ffff:ffff:0000:0000:0000:0000:0000:0000'))

    SELECT bitAnd(toIPv6('43:AB::'), IPv6StringToNum('ffff:ffff:0000:0000:0000:0000:0000:0000'))

    Query id: 4355c453-ad91-4ef7-a5ad-18aded30bf99


    0 rows in set. Elapsed: 0.005 sec. 

    Received exception from server (version 23.3.9):
    Code: 43. DB::Exception: Received from localhost:9000. DB::Exception: Illegal types IPv6 and FixedString(16) of arguments of function bitAnd: While processing bitAnd(toIPv6('43:AB::'), IPv6StringToNum('ffff:ffff:0000:0000:0000:0000:0000:0000')). (ILLEGAL_TYPE_OF_ARGUMENT)
    ```

* ClickHouse 22.8.21

    ```sql
    myserver :) SELECT bitAnd(toIPv4('1.2.3.4'), 20000000)

    SELECT bitAnd(toIPv4('1.2.3.4'), 20000000)

    Query id: 131967d4-81d6-4304-abe6-a35d88a67115

    ┌─bitAnd(toIPv4('1.2.3.4'), 20000000)─┐
    │                            16777472 │
    └─────────────────────────────────────┘

    1 row in set. Elapsed: 0.001 sec. 

    myserver :) SELECT bitAnd(toIPv4('1.2.3.4'), IPv4StringToNum('1.2.0.0'))

    SELECT bitAnd(toIPv4('1.2.3.4'), IPv4StringToNum('1.2.0.0'))

    Query id: 91a8c219-3533-421c-9cc7-d49017a2ee01

    ┌─bitAnd(toIPv4('1.2.3.4'), IPv4StringToNum('1.2.0.0'))─┐
    │                                              16908288 │
    └───────────────────────────────────────────────────────┘

    1 row in set. Elapsed: 0.002 sec. 

    myserver :) SELECT IPv6NumToString(bitAnd(toIPv6('43:AB::'), toIPv6('ffff:ffff:0000:0000:0000:0000:0000:0000')))

    SELECT IPv6NumToString(bitAnd(toIPv6('43:AB::'), toIPv6('ffff:ffff:0000:0000:0000:0000:0000:0000')))

    Query id: b0a03283-db12-42b5-bab9-57b8ed8c42bb

    ┌─IPv6NumToString(bitAnd(toIPv6('43:AB::'), toIPv6('ffff:ffff:0000:0000:0000:0000:0000:0000')))─┐
    │ 43:ab::                                                                                       │
    └───────────────────────────────────────────────────────────────────────────────────────────────┘

    1 row in set. Elapsed: 0.004 sec. 

    myserver :) SELECT IPv6NumToString(bitAnd(toIPv6('43:AB::'), IPv6StringToNum('ffff:ffff:0000:0000:0000:0000:0000:0000')))

    SELECT IPv6NumToString(bitAnd(toIPv6('43:AB::'), IPv6StringToNum('ffff:ffff:0000:0000:0000:0000:0000:0000')))

    Query id: a6625b0a-0577-4e87-a773-b34112e46753

    ┌─IPv6NumToString(bitAnd(toIPv6('43:AB::'), IPv6StringToNum('ffff:ffff:0000:0000:0000:0000:0000:0000')))─┐
    │ 43:ab::                                                                                                │
    └────────────────────────────────────────────────────────────────────────────────────────────────────────┘

    1 row in set. Elapsed: 0.003 sec. 

    ```

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by yakov-olkhovskiy**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Allow IPv6 to UInt128 conversion and binary arithmetic.

closes #56487

### CODE REVIEW

**Comment by robot-ch-test-poll2** [comment]
*This is an automated comment for commit 63619b59353699b5975acedffe0f2ca85e3985d7 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/57707/63619b59353699b5975acedffe0f2ca85e3985d7/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td><a href="https://github.com/ClickHouse/ClickHouse/actions/runs/7152705358">✅ success</a></td></tr>
<tbody>
</table>
</details>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/57707/63619b59353699b5975acedffe0f2ca85e3985d7/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Comment by alexey-milovidov** [comment]
Test needed.

**Comment by yakov-olkhovskiy** [comment]
@alexey-milovidov apparently we have problems with UInt128:
https://fiddle.clickhouse.com/c65c276a-f351-4248-b8b5-8d94113357c1
I think I need to fix it first to add appropriate test...

**Comment by alexey-milovidov** [comment]
@yakov-olkhovskiy This is about parsing literals in SQL. We don't have big-integer literals, so you cannot type them as is. You can put them into a string, then cast.

**Comment by yakov-olkhovskiy** [comment]
`CAST` doesn't work with hex... very inconvenient...

**Pull request merged**
