### PR TITLE
Add server-side time to Progress

### LINKED ISSUE #38070: Server should have Progress for server-side elapsed time for a query.
**Use case**

This will allow clickhouse-client to show the server-side elapsed time before query result and also to show a more precise CPU usage metric.

**Describe the solution you'd like**

Update it at least when ProfileEvents are sent to the client, or on every block (but then a coarse timer may be needed).

**Additional context**

Also, implement it for clickhouse-local.

### PR DESCRIPTION
**Pull request by alexey-milovidov**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
The client will show server-side elapsed time. This is important for the performance comparison of ClickHouse services in remote datacenters. This closes #38070. See also [this](https://github.com/ClickHouse/ClickBench/blob/main/hardware/benchmark-cloud.sh#L37) for motivation.

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
Checked compatibility of
- old client with new server
- new client with old server

manually.

**Review by Avogar — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
Notes about implementing this feature:

1. I did not change it in clickhouse-benchmark, may be worth changing.
2. Our protocol evolved, first, we had a separate `ProfileInfo` packet at the end of the query execution - surprisingly, it did not include the time in serialized format, while including the timer in a class member. I wanted to remove `ProfileInfo`, but it appeared to be used in many places inside the code.
3. Eventually, the `Progress` packet added new fields from the `ProfileInfo`: written rows and bytes, result rows and bytes, which makes `ProfileInfo` unneeded.
4. Lastly, we have added `ProfileEvents` packets which include both ProfileEvents and CurrentMetrics, despite the name. These packets extend both `ProfileInfo` and `Progress` and could make both of them obsolete.
5. We are sending the "final" Progress packet at the end of the query execution - it allows us to show the final progress value on the client. But there is no "final" `ProfileEvents` packet and I'm not sure if they will be correct if we add them.
6. There server-side query execution time and resource consumption can be greater than the client can see because the destructors can run after the result has been sent to the client.
7. Sometimes it's reasonable to show client-side query execution time and we don't have this choice. The user can resort to the `time` command, but it will include the application startup time and connection time.
8. There are plenty of almost duplicate Stopwatch timers in the code, one in the ProcessList, another inside Processors, and yet another inside TCPHandler. I've removed one of them, but the problem remains.
9. The elapsed time is added to Progress in TCPHandler ("from the side"), this is because I did not find a proper place to make it inside, and we need incremental values.
10. The progress in HTTP headers is unchanged, and the new field is not added (to avoid its growth).

**Comment by alexey-milovidov** [comment]
@tavplubix a test with Replicated database has failed because "Table /clickhouse/tables/test_6v6ihu/rep_fsync/auto_s1 was suddenly removed.": [https://s3.amazonaws.com/clickhouse-test-reports/39968/6b54cdffafa091254b8cd0cc25284b[…]6f3/stateless_tests__release__databasereplicated__[1/2].html](https://s3.amazonaws.com/clickhouse-test-reports/39968/6b54cdffafa091254b8cd0cc25284b4950ebb6f3/stateless_tests__release__databasereplicated__[1/2].html)

**Comment by tavplubix** [comment]
> @tavplubix a test with Replicated database has failed because "Table /clickhouse/tables/test_6v6ihu/rep_fsync/auto_s1 was suddenly removed.": [https://s3.amazonaws.com/clickhouse-test-reports/39968/6b54cdffafa091254b8cd0cc25284b[…]6f3/stateless_tests__release__databasereplicated__[1/2].html](https://s3.amazonaws.com/clickhouse-test-reports/39968/6b54cdffafa091254b8cd0cc25284b4950ebb6f3/stateless_tests__release__databasereplicated__%5B1/2%5D.html)

It's https://github.com/ClickHouse/ClickHouse/issues/34818, fixed in https://github.com/ClickHouse/ClickHouse/pull/37198

**Pull request merged**
