### PR TITLE
Cherry pick #64226 to 24.3: Fix ARRAY JOIN with Distributed.

### PR DESCRIPTION
**Pull request by robot-ch-test-poll3**
Original pull-request #64226

This pull-request is a first step of an automated backporting.
It contains changes similar to calling `git cherry-pick` locally.
If you intend to continue backporting the changes, then resolve all conflicts if any.
Otherwise, if you do not want to backport them, then just close this pull-request.

The check results does not matter at this step - you can safely ignore them.

### Note

This pull-request will be merged automatically. Please, **do not merge it manually** (but if you accidentally did, nothing bad will happen).

#### If the PR was manually reopened after being closed

If this PR is stuck (i.e. not automatically merged after one day), check https://github.com/ClickHouse/ClickHouse/pull/64226 for `pr-backports-created` *label* and delete it.

Manually merging will do nothing. The `pr-backports-created` *label* prevents the original PR https://github.com/ClickHouse/ClickHouse/pull/64226 from being processed.

#### If the conflicts were resolved in a wrong way

If this cherry-pick PR is completely screwed by a wrong conflicts resolution, and you want to recreate it:

- delete the `pr-cherrypick` label from the PR
- delete this branch from the repository

You also need to check the original PR https://github.com/ClickHouse/ClickHouse/pull/64226 for `pr-backports-created`, and delete if it's presented there

### CODE REVIEW

**Comment by robot-ch-test-poll2** [comment]
Dear @KochetovNicolai, @novikd, the PR is not updated for 1d25h0m13s. Please, either resolve the conflicts, or close it to finish the backport process of #64226

**Comment by robot-ch-test-poll4** [comment]
Dear @KochetovNicolai, @novikd, the PR is not updated for 1d24h2m35s. Please, either resolve the conflicts, or close it to finish the backport process of #64226

**Comment by robot-clickhouse-ci-1** [comment]
Dear @KochetovNicolai, @novikd, the PR is not updated for 1d24h56m21s. Please, either resolve the conflicts, or close it to finish the backport process of #64226

**Comment by robot-ch-test-poll1** [comment]
Dear @KochetovNicolai, @novikd, the PR is not updated for 1d24h1m57s. Please, either resolve the conflicts, or close it to finish the backport process of #64226

**Comment by robot-clickhouse** [comment]
Dear @KochetovNicolai, @novikd, the PR is not updated for 1d24h0m12s. Please, either resolve the conflicts, or close it to finish the backport process of #64226

**Comment by robot-clickhouse** [comment]
Dear @KochetovNicolai, @novikd, the PR is not updated for 1d24h57m9s. Please, either resolve the conflicts, or close it to finish the backport process of #64226

**Comment by robot-ch-test-poll** [comment]
Dear @KochetovNicolai, @novikd, the PR is not updated for 1d24h2m33s. Please, either resolve the conflicts, or close it to finish the backport process of #64226

**Comment by robot-ch-test-poll4** [comment]
Dear @KochetovNicolai, @novikd, the PR is not updated for 1d24h59m5s. Please, either resolve the conflicts, or close it to finish the backport process of #64226

**Comment by robot-clickhouse** [comment]
Dear @KochetovNicolai, @novikd, the PR is not updated for 1d24h59m35s. Please, either resolve the conflicts, or close it to finish the backport process of #64226

**Comment by robot-ch-test-poll4** [comment]
Dear @KochetovNicolai, @novikd, the PR is not updated for 1d25h0m2s. Please, either resolve the conflicts, or close it to finish the backport process of #64226

**Comment by robot-ch-test-poll2** [comment]
Dear @KochetovNicolai, @novikd, the PR is not updated for 1d24h58m32s. Please, either resolve the conflicts, or close it to finish the backport process of #64226

**Comment by robot-ch-test-poll3** [comment]
Dear @KochetovNicolai, @novikd, the PR is not updated for 1d24h2m26s. Please, either resolve the conflicts, or close it to finish the backport process of #64226

**Comment by robot-clickhouse** [comment]
Dear @KochetovNicolai, @novikd, the PR is not updated for 1d25h5m9s. Please, either resolve the conflicts, or close it to finish the backport process of #64226

**Comment by robot-clickhouse-ci-2** [comment]
Dear @KochetovNicolai, @novikd, the PR is not updated for 1d24h7m11s. Please, either resolve the conflicts, or close it to finish the backport process of #64226

**Comment by robot-clickhouse** [comment]
Dear @KochetovNicolai, @novikd, the PR is not updated for 1d25h13m40s. Please, either resolve the conflicts, or close it to finish the backport process of #64226

**Comment by robot-ch-test-poll2** [comment]
Dear @KochetovNicolai, @novikd, the PR is not updated for 1d24h46m41s. Please, either resolve the conflicts, or close it to finish the backport process of #64226

**Comment by robot-ch-test-poll1** [comment]
Dear @KochetovNicolai, @novikd, the PR is not updated for 1d24h44m28s. Please, either resolve the conflicts, or close it to finish the backport process of #64226

**Comment by robot-ch-test-poll2** [comment]
Dear @KochetovNicolai, @novikd, the PR is not updated for 1d24h2m47s. Please, either resolve the conflicts, or close it to finish the backport process of #64226

**Comment by robot-ch-test-poll3** [comment]
Dear @KochetovNicolai, @novikd, the PR is not updated for 1d24h0m56s. Please, either resolve the conflicts, or close it to finish the backport process of #64226

**Comment by robot-ch-test-poll3** [comment]
Dear @KochetovNicolai, @novikd, the PR is not updated for 1d24h58m17s. Please, either resolve the conflicts, or close it to finish the backport process of #64226

**Comment by robot-ch-test-poll4** [comment]
Dear @KochetovNicolai, @novikd, the PR is not updated for 1d24h58m20s. Please, either resolve the conflicts, or close it to finish the backport process of #64226

**Comment by robot-clickhouse-ci-2** [comment]
Dear @KochetovNicolai, @novikd, the PR is not updated for 1d24h4m7s. Please, either resolve the conflicts, or close it to finish the backport process of #64226

**Comment by robot-ch-test-poll1** [comment]
Dear @KochetovNicolai, @novikd, the PR is not updated for 1d25h3m34s. Please, either resolve the conflicts, or close it to finish the backport process of #64226

**Comment by robot-clickhouse-ci-2** [comment]
Dear @KochetovNicolai, @novikd, the PR is not updated for 1d25h3m12s. Please, either resolve the conflicts, or close it to finish the backport process of #64226

**Comment by robot-ch-test-poll4** [comment]
Dear @KochetovNicolai, @novikd, the PR is not updated for 1d24h55m49s. Please, either resolve the conflicts, or close it to finish the backport process of #64226

**Comment by robot-ch-test-poll3** [comment]
Dear @KochetovNicolai, @novikd, the PR is not updated for 1d24h1m29s. Please, either resolve the conflicts, or close it to finish the backport process of #64226

**Comment by robot-clickhouse-ci-2** [comment]
Dear @KochetovNicolai, @novikd, the PR is not updated for 1d24h53m43s. Please, either resolve the conflicts, or close it to finish the backport process of #64226

**Comment by robot-clickhouse** [comment]
Dear @KochetovNicolai, @novikd, the PR is not updated for 1d24h0m21s. Please, either resolve the conflicts, or close it to finish the backport process of #64226

**Comment by robot-clickhouse-ci-1** [comment]
Dear @KochetovNicolai, @novikd, the PR is not updated for 1d24h59m0s. Please, either resolve the conflicts, or close it to finish the backport process of #64226

**Comment by robot-clickhouse** [comment]
Dear @KochetovNicolai, @novikd, the PR is not updated for 1d25h3m21s. Please, either resolve the conflicts, or close it to finish the backport process of #64226

**Comment by robot-ch-test-poll4** [comment]
Dear @KochetovNicolai, @novikd, the PR is not updated for 1d24h58m15s. Please, either resolve the conflicts, or close it to finish the backport process of #64226

**Comment by robot-ch-test-poll2** [comment]
Dear @KochetovNicolai, @novikd, the PR is not updated for 1d24h59m16s. Please, either resolve the conflicts, or close it to finish the backport process of #64226

**Comment by robot-ch-test-poll** [comment]
Dear @KochetovNicolai, @novikd, the PR is not updated for 1d24h7m4s. Please, either resolve the conflicts, or close it to finish the backport process of #64226

**Comment by novikd** [comment]
We need to backport #63993 to `24.3` to resolve conflicts. I reopened #64481.

**Comment by robot-clickhouse-ci-2** [comment]
Dear @KochetovNicolai, @novikd, the PR is not updated for 1d24h22m40s. Please, either resolve the conflicts, or close it to finish the backport process of #64226

**Comment by robot-clickhouse-ci-2** [comment]
Dear @KochetovNicolai, @novikd, the PR is not updated for 1d24h1m5s. Please, either resolve the conflicts, or close it to finish the backport process of #64226

**Comment by robot-clickhouse-ci-1** [comment]
Dear @KochetovNicolai, @novikd, the PR is not updated for 1d24h1m39s. Please, either resolve the conflicts, or close it to finish the backport process of #64226

**Comment by robot-ch-test-poll1** [comment]
Dear @KochetovNicolai, @novikd, the PR is not updated for 1d24h56m54s. Please, either resolve the conflicts, or close it to finish the backport process of #64226

**Comment by robot-clickhouse-ci-1** [comment]
Dear @KochetovNicolai, @novikd, the PR is not updated for 1d24h2m40s. Please, either resolve the conflicts, or close it to finish the backport process of #64226

**Comment by robot-ch-test-poll1** [comment]
Dear @KochetovNicolai, @novikd, the PR is not updated for 1d25h0m21s. Please, either resolve the conflicts, or close it to finish the backport process of #64226

**Comment by robot-clickhouse-ci-1** [comment]
Dear @KochetovNicolai, @novikd, the PR is not updated for 1d24h58m5s. Please, either resolve the conflicts, or close it to finish the backport process of #64226

**Comment by robot-ch-test-poll4** [comment]
Dear @KochetovNicolai, @novikd, the PR is not updated for 1d24h59m17s. Please, either resolve the conflicts, or close it to finish the backport process of #64226

**Comment by robot-ch-test-poll2** [comment]
Dear @KochetovNicolai, @novikd, the PR is not updated for 1d24h3m33s. Please, either resolve the conflicts, or close it to finish the backport process of #64226

**Comment by robot-clickhouse-ci-2** [comment]
Dear @KochetovNicolai, @novikd, the PR is not updated for 1d25h1m1s. Please, either resolve the conflicts, or close it to finish the backport process of #64226

**Comment by robot-ch-test-poll** [comment]
Dear @KochetovNicolai, @novikd, the PR is not updated for 1d24h4m54s. Please, either resolve the conflicts, or close it to finish the backport process of #64226

**Comment by robot-clickhouse** [comment]
Dear @KochetovNicolai, @novikd, the PR is not updated for 1d24h51m30s. Please, either resolve the conflicts, or close it to finish the backport process of #64226

**Comment by robot-ch-test-poll** [comment]
Dear @KochetovNicolai, @novikd, the PR is not updated for 1d26h5m2s. Please, either resolve the conflicts, or close it to finish the backport process of #64226

**Comment by robot-ch-test-poll1** [comment]
Dear @KochetovNicolai, @novikd, the PR is not updated for 1d24h1m56s. Please, either resolve the conflicts, or close it to finish the backport process of #64226

**Comment by robot-clickhouse** [comment]
Dear @KochetovNicolai, @novikd, the PR is not updated for 1d25h23m18s. Please, either resolve the conflicts, or close it to finish the backport process of #64226

**Comment by robot-clickhouse** [comment]
Dear @KochetovNicolai, @novikd, the PR is not updated for 1d25h46m8s. Please, either resolve the conflicts, or close it to finish the backport process of #64226

**Comment by robot-ch-test-poll** [comment]
Dear @KochetovNicolai, @novikd, the PR is not updated for 1d24h45m10s. Please, either resolve the conflicts, or close it to finish the backport process of #64226

**Comment by robot-clickhouse-ci-2** [comment]
Dear @KochetovNicolai, @novikd, the PR is not updated for 1d24h58m43s. Please, either resolve the conflicts, or close it to finish the backport process of #64226

**Comment by robot-ch-test-poll3** [comment]
Dear @KochetovNicolai, @novikd, the PR is not updated for 1d24h7m35s. Please, either resolve the conflicts, or close it to finish the backport process of #64226

**Comment by robot-clickhouse-ci-1** [comment]
Dear @KochetovNicolai, @novikd, the PR is not updated for 1d24h52m1s. Please, either resolve the conflicts, or close it to finish the backport process of #64226

**Comment by robot-clickhouse-ci-1** [comment]
Dear @KochetovNicolai, @novikd, the PR is not updated for 1d25h3m33s. Please, either resolve the conflicts, or close it to finish the backport process of #64226

**Comment by robot-clickhouse-ci-1** [comment]
Dear @KochetovNicolai, @novikd, the PR is not updated for 1d25h52m25s. Please, either resolve the conflicts, or close it to finish the backport process of #64226

**Comment by robot-ch-test-poll** [comment]
Dear @KochetovNicolai, @novikd, the PR is not updated for 1d24h43m7s. Please, either resolve the conflicts, or close it to finish the backport process of #64226

**Comment by robot-clickhouse** [comment]
Dear @KochetovNicolai, @novikd, the PR is not updated for 1d24h21m3s. Please, either resolve the conflicts, or close it to finish the backport process of #64226

**Comment by robot-ch-test-poll1** [comment]
Dear @KochetovNicolai, @novikd, the PR is not updated for 1d25h0m38s. Please, either resolve the conflicts, or close it to finish the backport process of #64226

**Comment by robot-clickhouse-ci-2** [comment]
Dear @KochetovNicolai, @novikd, the PR is not updated for 1d24h59m15s. Please, either resolve the conflicts, or close it to finish the backport process of #64226

**Comment by robot-ch-test-poll2** [comment]
Dear @KochetovNicolai, @novikd, the PR is not updated for 1d25h1m58s. Please, either resolve the conflicts, or close it to finish the backport process of #64226

**Comment by robot-clickhouse-ci-2** [comment]
Dear @KochetovNicolai, @novikd, the PR is not updated for 1d24h3m21s. Please, either resolve the conflicts, or close it to finish the backport process of #64226

**Comment by robot-ch-test-poll3** [comment]
Dear @KochetovNicolai, @novikd, the PR is not updated for 1d24h1m43s. Please, either resolve the conflicts, or close it to finish the backport process of #64226

**Comment by robot-ch-test-poll4** [comment]
Dear @KochetovNicolai, @novikd, the PR is not updated for 1d24h43m2s. Please, either resolve the conflicts, or close it to finish the backport process of #64226

**Comment by robot-clickhouse-ci-2** [comment]
Dear @KochetovNicolai, @novikd, the PR is not updated for 1d24h12m16s. Please, either resolve the conflicts, or close it to finish the backport process of #64226

**Comment by robot-clickhouse-ci-2** [comment]
Dear @KochetovNicolai, @novikd, the PR is not updated for 1d25h0m44s. Please, either resolve the conflicts, or close it to finish the backport process of #64226

**Comment by robot-clickhouse-ci-1** [comment]
Dear @KochetovNicolai, @novikd, the PR is not updated for 1d24h53m54s. Please, either resolve the conflicts, or close it to finish the backport process of #64226

**Comment by robot-ch-test-poll3** [comment]
Dear @KochetovNicolai, @novikd, the PR is not updated for 1d24h57m45s. Please, either resolve the conflicts, or close it to finish the backport process of #64226

**Comment by robot-clickhouse** [comment]
Dear @KochetovNicolai, @novikd, the PR is not updated for 1d24h0m43s. Please, either resolve the conflicts, or close it to finish the backport process of #64226

**Comment by robot-ch-test-poll4** [comment]
Dear @KochetovNicolai, @novikd, the PR is not updated for 1d24h22m18s. Please, either resolve the conflicts, or close it to finish the backport process of #64226

**Comment by robot-ch-test-poll** [comment]
Dear @KochetovNicolai, @novikd, the PR is not updated for 1d24h36m43s. Please, either resolve the conflicts, or close it to finish the backport process of #64226

**Comment by robot-ch-test-poll2** [comment]
Dear @KochetovNicolai, @novikd, the PR is not updated for 1d24h2m17s. Please, either resolve the conflicts, or close it to finish the backport process of #64226

**Comment by robot-ch-test-poll3** [comment]
Dear @KochetovNicolai, @novikd, the PR is not updated for 1d24h1m15s. Please, either resolve the conflicts, or close it to finish the backport process of #64226

**Comment by robot-ch-test-poll2** [comment]
Dear @KochetovNicolai, @novikd, the PR is not updated for 1d24h57m37s. Please, either resolve the conflicts, or close it to finish the backport process of #64226

**Comment by robot-ch-test-poll4** [comment]
Dear @KochetovNicolai, @novikd, the PR is not updated for 1d24h7m15s. Please, either resolve the conflicts, or close it to finish the backport process of #64226

**Comment by robot-ch-test-poll2** [comment]
Dear @KochetovNicolai, @novikd, the PR is not updated for 1d24h54m11s. Please, either resolve the conflicts, or close it to finish the backport process of #64226

**Comment by robot-clickhouse-ci-2** [comment]
Dear @KochetovNicolai, @novikd, the PR is not updated for 1d24h1m23s. Please, either resolve the conflicts, or close it to finish the backport process of #64226

**Comment by robot-ch-test-poll2** [comment]
Dear @KochetovNicolai, @novikd, the PR is not updated for 1d24h1m26s. Please, either resolve the conflicts, or close it to finish the backport process of #64226

**Comment by robot-ch-test-poll3** [comment]
Dear @KochetovNicolai, @novikd, the PR is not updated for 1d24h56m27s. Please, either resolve the conflicts, or close it to finish the backport process of #64226

**Comment by robot-clickhouse-ci-1** [comment]
Dear @KochetovNicolai, @novikd, the PR is not updated for 1d25h2m2s. Please, either resolve the conflicts, or close it to finish the backport process of #64226

**Comment by robot-ch-test-poll4** [comment]
Dear @KochetovNicolai, @novikd, the PR is not updated for 1d25h1m36s. Please, either resolve the conflicts, or close it to finish the backport process of #64226

**Comment by robot-clickhouse** [comment]
Dear @KochetovNicolai, @novikd, the PR is not updated for 1d25h4m14s. Please, either resolve the conflicts, or close it to finish the backport process of #64226

**Comment by robot-ch-test-poll4** [comment]
Dear @KochetovNicolai, @novikd, the PR is not updated for 1d24h0m31s. Please, either resolve the conflicts, or close it to finish the backport process of #64226

**Pull request closed without merging**
