### PR TITLE
Update json.md

### PR DESCRIPTION
**Pull request by gingerwizard**
### Changelog category (leave one):
- Documentation (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
[Docs] Improve messaging around the JSON object data type.

### CODE REVIEW

**Comment by tbragin** [comment]
@gingerwizard one minor fix "ClickHouse handles JSON documents in a variety of way**s**" (the s on the end is missing)

Otherwise LGTM

**Comment by justindeguzman** [comment]
I actually don't think we need this PR since the second note basically already says to refer to the JSON guide already @tbragin.

**Comment by tbragin** [comment]
The reason I asked Dale to open it is -- it is hard to see the mention of the other guide in that note visually; it just sort of gets lost. Anything we can do to improve that?
Screenshot 2024-07-05 at 5 34 10 PM

**Comment by justindeguzman** [comment]
I added the following:
- Explicitly add (deprecated) to title
- Remove the note and just make it the first sentence so that users are more likely to not gloss over it
- Explicitly bold sentence that indicates the feature is deprecated

**Review by justindeguzman — APPROVED** [review]

**Comment by robot-clickhouse-ci-1** [comment]
*This is an automated comment for commit fbe172dd593108ba6728a93ed9be6b0300c631f8 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/66051/fbe172dd593108ba6728a93ed9be6b0300c631f8/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Style check</td><td>Runs a set of checks to keep the code style clean. If some of tests failed, see the related log from the report</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/66051/fbe172dd593108ba6728a93ed9be6b0300c631f8/style_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Pull request merged**
