### PR TITLE
Fix potential segfault when using Lazy database.

### PR DESCRIPTION
**Pull request by alexey-milovidov**
Changelog category (leave one):
- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix potential segfault when using `Lazy` database.

Detailed description / Documentation draft:
Continuation of #10209 that was unfinished. The bug was introduced in #7171.
See https://clickhouse-test-reports.s3.yandex.net/0/68e2f88635c3f3b1fe6aca81db986fc2413a26fd/stress_test_(address).html#fail1
No one is using Lazy database except Yandex.Metrica.

PS. Why we have so inconvenient interface of Lazy database?

### CODE REVIEW

**Review by tavplubix — APPROVED** [review]

**Comment by tavplubix** [comment]
> Why we have so inconvenient interface of Lazy database?

We can make it more convenient by saving not null `current_storage` in `DatabaseLazyIterator::next()` and just returning it from `DatabaseLazyIterator::table()`. But it will cause reloading of all tables in Lazy database when executing `DROP DATABASE` and `SELECT database, name, uuid, metadata_modification_time FROM system.tables` (in other cases when tables iterator is required tables will be reloaded anyway)

**Comment by alexey-milovidov** [comment]
Yes, I understand - avoid reloading of tables is the motivation of this design.

Also we can prepare a wrapper named StorageLazy. It will contain internal table and proxy all methods with special support for drop, detach and getName.

**Comment by alexey-milovidov** [comment]
@nikvas0 What do you think?

**Comment by nikvas0** [comment]
`SELECT database, name, uuid, metadata_modification_time FROM system.tables` should not reload tables.
I think a wrapper can be a good solution. If the current table does not exist, it can simply return "dropped" as name.
Another approach is to implement some counters (like shared_ptr) for tables in CachedTable struct and do not remove tables until the counter is equal to 0.

**Pull request merged**
