### PR TITLE
Forbid POPULATE with Replicated databases

### PR DESCRIPTION
**Pull request by vdimir**
### Changelog category (leave one):

- Backward Incompatible Change

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
* Forbid `CREATE MATERIALIZED VIEW ... ENGINE Replicated*MergeTree POPULATE AS SELECT ...` with Replicated databases

### CODE REVIEW

**Review by tavplubix — APPROVED** [review]

**Comment by robot-ch-test-poll1** [comment]
*This is an automated comment for commit 2b514745e7a01cf7021b15bf145ceefd6086e31b with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/63963/2b514745e7a01cf7021b15bf145ceefd6086e31b/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

**Comment by tavplubix** [comment]
Let's add a setting

**Comment by vdimir** [comment]
> Stateless tests (debug, s3 storage) [3/6] — fail: 1, passed: 1086, skipped: 22 [Details](https://s3.amazonaws.com/clickhouse-test-reports/63963/6fadbf1cf158fbecaf8c05092e02229c0a375892/stateless_tests__debug__s3_storage__[3_6].html)

> Stateless tests (debug, s3 storage) [4/6] — fail: 1, passed: 1137, skipped: 29 [Details](https://s3.amazonaws.com/clickhouse-test-reports/63963/6fadbf1cf158fbecaf8c05092e02229c0a375892/stateless_tests__debug__s3_storage__[4_6].html)

jemalloc known issue is being investigated, as far as I know [cidb](https://play.clickhouse.com/play?user=play#CldJVEgKICAgIGZhbHNlIGFzIG9ubHlfbWFzdGVyClNFTEVDVCAqCkZST00gKApTRUxFQ1QKICAgIHB1bGxfcmVxdWVzdF9udW1iZXIgYXMgcHJudW0sCiAgICBzdWJzdHIoY29tbWl0X3NoYSwgMSw5KSBhcyBzaGEsCiAgICByb3VuZCh0ZXN0X2R1cmF0aW9uX21zIC8gMTAwMCwgMikgYXMgZHVyLAogICAgY2hlY2tfc3RhcnRfdGltZSwKICAgIGZvcm1hdFJlYWRhYmxlVGltZURlbHRhKGludERpdihub3coKSAtIGNoZWNrX3N0YXJ0X3RpbWUsIDM2MDApICogMzYwMCkgYXMgYWdvLAogICAgY2hlY2tfbmFtZSwKICAgIHRlc3RfbmFtZSwKICAgIHJlcG9ydF91cmwKRlJPTSBjaGVja3MKV0hFUkUgMQogICAgQU5EIGNoZWNrX3N0YXJ0X3RpbWUgPj0gbm93KCkgLSBJTlRFUlZBTCA3IERBWQogICAgQU5EIChwdWxsX3JlcXVlc3RfbnVtYmVyID0gMCBPUiBub3Qgb25seV9tYXN0ZXIpCiAgICBBTkQgdGVzdF9zdGF0dXMgIT0gJ1NLSVBQRUQnCiAgICBBTkQgdGVzdF9zdGF0dXMgTElLRSAnRiUnCiAgICBBTkQgY2hlY2tfc3RhdHVzICE9ICdzdWNjZXNzJwogICAgQU5EIHRlc3RfY29udGV4dF9yYXcgaWxpa2UgJyVqZW1hbGxvYyVmYWlsJScKKQpPUkRFUiBCWSBjaGVja19zdGFydF90aW1lIERFU0MsIGNoZWNrX25hbWUsIHRlc3RfbmFtZQ==)


> Stress test (tsan) — Found signal in gdb.log [Details](https://s3.amazonaws.com/clickhouse-test-reports/63963/6fadbf1cf158fbecaf8c05092e02229c0a375892/stress_test__tsan_.html)

`Expected ReadBufferFromFile, but got DB::EmptyReadBuffer`


> Upgrade check (debug) — New settings are not reflected in settings changes history (see new_settings.txt) [Details](https://s3.amazonaws.com/clickhouse-test-reports/63963/6fadbf1cf158fbecaf8c05092e02229c0a375892/upgrade_check__debug_.html)

`input_format_json_ignore_key_case` https://github.com/ClickHouse/ClickHouse/pull/65945

**Comment by vdimir** [comment]
@tavplubix setting is added, query with populate forbidden by default, compatibility setting can be used to roll back behavior

**Review by tavplubix — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
`CRATE` -> `CREATE`

**Pull request merged**
