### PR TITLE
Build jemalloc with profiler

### PR DESCRIPTION
**Pull request by antonio2368**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Let's try building jemalloc with profiler, and have it inactive by default. The overhead should be almost non-existent.
This will allow us to activate the profiler using SQL command without the need to change any env variables or restart.

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [x]  Exclude: All with ASAN
- [x]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-ch-test-poll3** [comment]
*This is an automated comment for commit 35820eaa7baf67a02e7a875d413b53e306ba4ae9 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/65702/35820eaa7baf67a02e7a875d413b53e306ba4ae9/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Cloud fork sync (only for ClickHouse Inc. employees)</td><td>If it fails, ask a maintainer for help</td><td>⏳ pending</td></tr>
<tbody>
</table>
<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>Checks correctness of the PR's body</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

**Comment by zhanglistar** [comment]
@antonio2368 And we can enable it dynamiclly during running.

**Comment by antonio2368** [comment]
@zhanglistar what do you mean?

**Review by serxa — APPROVED** [review]
This is great

**Comment by antonio2368** [comment]
No performance impact!

**Comment by antonio2368** [comment]
@azat I enabled `opt.background_thread` to be able to use profiler, for some reason ClickHouse often deadlocks when it's not enabled.

I just now noticed the error log advising against enabling it. Does it still hold?

**Comment by azat** [comment]
>Does it still hold?

Kind of, it simply does not make sense

The question is, why it deadlocks, I've tried to disable it but vanila server with a simple `select 1` does not deadlocks, maybe you have reproducer/stacktraces?

**Comment by azat** [comment]
+1 for @zhanglistar comment

Why it has been enabled by default, instead of simply `MALLOC_CONF=prof:true` (see https://github.com/jemalloc/jemalloc/wiki/Use-Case%3A-Heap-Profiling) ?

**Comment by antonio2368** [comment]
The same thing is described here https://clickhouse.com/docs/en/operations/allocation-profiling#sampling-allocations-and-flushing-heap-profiles

the idea is to simplify and make it more accessible to use because right now it requires a restart to be able to apply such change.
As there is no negative impact on performance (because the profiler is inactive) I don't see a reason not to have it enabled, it will just boot some extra things during startup.

**Pull request merged**
