### PR TITLE
Update install.md

### PR DESCRIPTION
**Pull request by kolya7k**
https://packages.clickhouse.com/tgz/stable/ is multi-paged atm and sorted by date asc so we can't get very last version
### Changelog category (leave one):
- Documentation (changelog entry is not required)

### CODE REVIEW

**Comment by robot-clickhouse** [comment]
*This is an automated comment for commit e562d97ff59739da3ca3650a33644bf9700becd7 with description of existing statuses. It's updated for the latest CI running*

[❌ Click here](https://s3.amazonaws.com/clickhouse-test-reports/61151/e562d97ff59739da3ca3650a33644bf9700becd7/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td><a href="https://github.com/ClickHouse/ClickHouse/blob/master/.github/PULL_REQUEST_TEMPLATE.md?plain=1">❌ failure</a></td></tr>
<tbody>
</table>

**Review by yariks5s — COMMENTED** [review]
> https://packages.clickhouse.com/tgz/stable/ is multi-paged atm and sorted by date asc so we can't get very last version

I hope that better solution would be to sort elements on this page by version

**Comment by alexey-milovidov** [comment]
The latest version can be also obtained here: https://raw.githubusercontent.com/ClickHouse/ClickHouse/master/utils/list-versions/version_date.tsv

**Comment by yariks5s** [comment]
@kolya7k , could you please sign the CLA?

**Review by yariks5s — DISMISSED** [review]

**Review by alexey-milovidov — APPROVED** [review]
Small changes are ok without CLA.

**Pull request merged**
