### PR TITLE
Add file name to exception raised during decompression

### LINKED ISSUE #46037: Error message about inability to decompress the data should contain the file name if possible.
Now:

```
Received exception:
Code: 354. DB::Exception: inflateReset failed: buffer error: While executing ParallelParsingBlockInputFormat: While executing File. (ZLIB_INFLATE_FAILED)
```

How to reproduce:

Process multiple gzip files, with one of them truncated.

### PR DESCRIPTION
**Pull request by evillique**
Closes https://github.com/ClickHouse/ClickHouse/issues/46037

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
LGTM, but:

1. Add a test (with a malformed archive).
2. Does it work for URL or S3 table functions?

**Review by vmarora — COMMENTED** [review]
May I suggest a nit? Most codebase in clickhouse seems to use fmt.
return fmt::format("; While reading from: {}", filename);

**Comment by alexey-milovidov** [comment]
@vmarora Yes, good point! Although when we simply concatenate two strings, it's in question if it makes any advantage.

**Comment by evillique** [comment]
S3:
```
SELECT *
FROM s3('https://storage.googleapis.com/clickhouse-public-datasets/nyc-taxi/trips_0.gz', 'TabSeparatedWithNames', 'trip_id UInt32', br)

Query id: 1f28f730-858e-4464-8270-0517246ebcc7

↓ Progress: 0.00 rows, 0.00 B (0.00 rows/s., 0.00 B/s.)                                                                               (0.0 CPU, 4.25 MB RAM)
0 rows in set. Elapsed: 0.186 sec. 

Received exception from server (version 23.5.1):
Code: 448. DB::Exception: Received from localhost:9000. DB::Exception: brotli decode error; While reading from: clickhouse-public-datasets/nyc-taxi/trips_0.gz: While executing ParallelParsingBlockInputFormat: While executing S3. (BROTLI_READ_FAILED)
```

URL:
```
SELECT *
FROM url('https://storage.googleapis.com/clickhouse-public-datasets/nyc-taxi/trips_0.gz', 'TabSeparatedWithNames', 'trip_id UInt32', br)

Query id: 1d959782-1c3d-4535-8f0d-8f439ae07272

↑ Progress: 0.00 rows, 0.00 B (0.00 rows/s., 0.00 B/s.)                                                                               (0.0 CPU, 4.20 MB RAM)
0 rows in set. Elapsed: 0.402 sec. 

Received exception from server (version 23.5.1):
Code: 448. DB::Exception: Received from localhost:9000. DB::Exception: brotli decode error; While reading from: https://storage.googleapis.com/clickhouse-public-datasets/nyc-taxi/trips_0.gz: While executing ParallelParsingBlockInputFormat: While executing URL. (BROTLI_READ_FAILED)
```

**Comment by robot-ch-test-poll2** [comment]
This is an automated comment for commit 84432b789743fd19b820a3460c9c00ba20fa7f96 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/49241/84432b789743fd19b820a3460c9c00ba20fa7f96/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Review by alexey-milovidov — APPROVED** [review]

**Pull request merged**
