### PR TITLE
Add tests with Ordinary database to flaky check

### PR DESCRIPTION
**Pull request by tavplubix**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by tavplubix** [comment]
Stateless tests flaky check (address) - `Test runs too long` - OK

**Comment by tavplubix** [comment]
@yakov-olkhovskiy, `skip mergeable check` label does not work

**Comment by tavplubix** [comment]
Mergeable Check Expected — Waiting for status to be reported 
Updating branch did not help either...

**Comment by yakov-olkhovskiy** [comment]
@tavplubix 
>Updating branch did not help either...

but I see `Mergeable Check skipped` in actions...

**Comment by tavplubix** [comment]
At first it was waiting for other tests to start and status was `Waiting for status to be reported` for a few minutes. Then tests have started it status was changed to `skipped`

**Comment by yakov-olkhovskiy** [comment]
yup, it how it suppose to work - the stage "waiting" is generated by branch protection rule which starts immediately, but status itself is produced by specific tests - particularly `Mergeable Check skipped` is produced by `run_check.py`:
https://github.com/ClickHouse/ClickHouse/blob/dc32519207f13e8b14be9f109aabaddaa32973d7/tests/ci/run_check.py#L231

**Comment by tavplubix** [comment]
Ok, but what about previous commit? Status was not updated when I added the label

**Comment by yakov-olkhovskiy** [comment]
unfortunately labels are not very reliable right now when changing it after PR was created... I definitely will try to investigate this issue further though @Felixoid suggested not to do so, because labels are utterly broken in github :)

**Pull request merged**
