### PR TITLE
[QueryCache] Added query cache when a query shares most of the query

### PR DESCRIPTION
**Pull request by pashandor789**
### Changelog category (leave one):
- Improvement

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by pashandor789** [comment]
guys, I require some assistance. (ticket https://github.com/ClickHouse/ClickHouse/issues/57490) - `If found, construct a query pipeline that will use the data from the cache but apply the missing transformations.`
how to apply transformation (for example, ASTPtr filter) to QueryPipeline or QueryCacheEntry?

**Comment by alexey-milovidov** [comment]
It is somewhere around `Planner`. Find where the transformations are added in a regular scenario (without the query cache), and we will need to add the same transformations.

**Comment by pashandor789** [comment]
@alexey-milovidov should I create `Planner` in `executeQuery.cpp`?

**Comment by pashandor789** [comment]
Or can you help me please ?) @rschu1ze

**Pull request closed without merging**
