### PR TITLE
Move poco to base/poco/

### PR DESCRIPTION
**Pull request by rschu1ze**
See #46076

This PR moves the poco libraries from "contrib/" to "base/poco/". Reasons:
- upstream development does not look very active these days
- ClickHouse's poco fork is heavily patched, contributing these patches to upstream is infeasible
- ClickHouse uses only little of poco, the move will allow to:
    - remove unused or unwanted stuff from poco
    - make future patching of poco easier
    - apply stricter compiler warning settings
    - apply our formatting to poco sources

This was done in more detail (roughly in this order):
- contrib/poco/* was copypasted to base/poco/.
- the poco submodule was deregistered and `add_submodule(poco)` was removed from contrib/CMakeLists.txt
- poco's original CMake build descriptions were renamed to CMakeLists_native.txt
- the previous, "bundled" CMake build descriptions in contrib/poco-cmake/ were copypasted into base/poco/,
- excludes were added to spell/whitespace/style/etc. checks
- all files not used by ClickHouse build were removed from base/poco/. This reduces the code size from 1.8 mil. LOC to ca. 300k LOC.
- finally, CMakeLists files now use globbing instead of listing source files explicitly

### Changelog category (leave one):
- Build/Testing/Packaging Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
ClickHouse's fork of poco was moved from "contrib/" to "base/poco/"

### CODE REVIEW

**Comment by Felixoid** [comment]
Just as a really "a bit nice to have"

Is it possible | does it make sense to reduce the git garbage a little bit by not adding/removing 1.5M LoC? I know, that we already had binary things like images, so if it's no trivial, than don't bother yourself :+1:

**Comment by tavplubix** [comment]
> Is it possible | does it make sense to reduce the git garbage a little bit by not adding/removing 1.5M LoC?

We can simply merge with squash

Screenshot from 2023-02-07 00-26-02

**Review by yakov-olkhovskiy — APPROVED** [review]
since we are just appropriating the code, I'm assuming if it compiles - it works...

**Comment by rschu1ze** [comment]
The [squash commit](https://github.com/ClickHouse/ClickHouse/commit/b79ead9c847b9cf5077145611a1c13b8c45daa5b) was committed directly to master. Pretty nice ... we should use squashing more often.

ClickHouse Integration Tests (release) [3/4]
- test_backup_restore_on_cluster #45486

ClickHouse Integration Tests (tsan) [4/6]
- test_storage_rabbitmq test is flaky, looks like #45160

**Comment by myrrc** [comment]
@rschu1ze It makes sense to disable merges completely and allow only squash-to-master as total history size makes downloading CH a serious pain.

**Comment by rschu1ze** [comment]
I unfortunately sense no consent about this. People in the "merge" camp say that 1. Git is designed to deal with messy history and 2. if commits are self-contained units of change and have a proper commit message then why omit them in master. People in the "squash" camp say that most PRs are too messy and it's not worth to retain the individual Git commits.

**Comment by Felixoid** [comment]
I am in another camp.

I always rebase my branches and make all commits meaningful before the merge. Sometimes it brings additional pain during the review process though `¯\_(ツ)_/¯`

**Pull request merged**
