### PR TITLE
Progress bar: use FQDN to differentiate metrics from different hosts

### LINKED ISSUE #59047: Parallel replicas don't show the correct memory & CPU usage on the progress bar
**Describe the unexpected behaviour**
https://pastila.nl/?008c5509/23599a9392fa61b4260580569863f6cb#u31oU/uVIKLPW2GD2pqrAA==

### PR DESCRIPTION
**Pull request by devcrafter**
Fixes https://github.com/ClickHouse/ClickHouse/issues/59047

To differentiate metrics from different hosts on the client side, `display_name` server settings is used. The setting is used as `host_name` column in the metrics block sent to the client. So, the assumption that profile events and memory usage from different hosts will come with different `host_name`. But if `display_name` is set to the same value for all ClickHouse nodes in a cluster, then the client sees all the metrics as from one host. In such case, total memory usage for distributed query will not be calculated correctly, as well as, `max/host` memory usage will not be shown in the client progress bar.

Solution: always use hostname to differentiate metrics from different hosts (instead of server display name)

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by robot-ch-test-poll** [comment]
*This is an automated comment for commit d8a6e53d0b4b0e504982321043bec9f9180e87c1 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/59404/d8a6e53d0b4b0e504982321043bec9f9180e87c1/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/59404/d8a6e53d0b4b0e504982321043bec9f9180e87c1/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Review by antaljanosbenjamin — COMMENTED** [review]
The changes looks okay, however I would say let's write some minimal documentation (e.g. something like the description of the PR) and a changelog entry.

**Comment by devcrafter** [comment]
> The changes looks okay, however I would say let's write some minimal documentation (e.g. something like the description of the PR) and a changelog entry.

There is no need for settings. We need to keep `display_name`, - it's used as the command line prompt in `clickhouse-client `, but use actual `host_name` for profile events

**Comment by devcrafter** [comment]
Upgrade check  failure - https://github.com/ClickHouse/ClickHouse/issues/59327

**Pull request merged**
