### PR TITLE
Reproducible build

### PR DESCRIPTION
**Pull request by alexey-milovidov**
Changelog category (leave one):
- Build/Testing/Packaging Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Remove a source of nondeterminism from build. Now builds at different point of time will produce byte-identical binaries. Partially addressed #22113.

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
```
milovidov@mtlog-perftest03j:~/ClickHouse/build$ md5sum programs/clickhouse
f55e2081efcffb8e6ac224942d2c4060  programs/clickhouse
milovidov@mtlog-perftest03j:~/ClickHouse/build$ md5sum programs/clickhouse1
f55e2081efcffb8e6ac224942d2c4060  programs/clickhouse1
```

**Comment by filimonov** [comment]
Try to clone repo from the scratch into another folder or (better) do that on the another node. Or just check diffoscope report in the issue. There was much more differences. For ex. order of system.licences etc.

**Review by filimonov — APPROVED** [review]
Nice increment /improvement, but i have doubts if it really resolves the issue, as differences i saw in diffoscope was broader.

**Comment by alexey-milovidov** [comment]
@filimonov Please post all the differences here.

**Comment by alexey-milovidov** [comment]
@filimonov
> Or just check diffoscope report in the issue.

Could you please just enumerate the differences that are still needed to be fixed?

**Comment by alexey-milovidov** [comment]
> into another folder

Paths are still embedded to the binary and we are not going to fix it in this PR.

**Comment by filimonov** [comment]
> @filimonov
> 
> > Or just check diffoscope report in the issue.
> 
> Could you please just enumerate the differences that are still needed to be fixed?

I can not. Diffoscope report showed hundreds of changes, analizing them is a task not for few minutes. Just open the html inside diffoscope archive attached to ticket.

Typically one of requirements to archive that is publishing sources (together with submodules) as tar.gz. Otherwise you can not guarantee that the order of files (and order of their processing) will be the same on different machines.

**Comment by alexey-milovidov** [comment]
> Otherwise you can not guarantee that the order of files (and order of their processing) will be the same on different machines.

What exactly do you mean?

**Pull request merged**
