### PR TITLE
Show details of MaterializeMySQL tables in `system.tables`

### PR DESCRIPTION
**Pull request by stigsb**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Show full details of MaterializeMySQL tables in `system.tables`

### CODE REVIEW

**Comment by tavplubix** [comment]
Unlike `StorageSystemPartsBase`, `StorageSystemTables` uses only virtual methods of `IStorage` and does not cast storage to `MergeTreeData`, so it should work for MaterializeMySQL without replacing storage pointer. The issue is that `StorageMaterializeMySQL` [does not set](https://github.com/ClickHouse/ClickHouse/blob/master/src/Storages/StorageMaterializeMySQL.cpp#L33-L36) `partition_key`, `sorting_key` and other stuff in `StorageInMemoryMetadata`. Maybe we should try to fix it?

**Comment by stigsb** [comment]
Thanks for the feedback @tavplubix, I'll do that instead.

**Comment by stigsb** [comment]
I ended up just copying the in-memory metadata from the nested table. Can't think of any cases where that could cause other problems, what do you think @tavplubix ?

**Comment by tavplubix** [comment]
Yes, it should work, let's wait for test results

**Pull request merged**
