### PR TITLE
Enable optimize_rewrite_sum_if_to_count_if by default

### PR DESCRIPTION
**Pull request by Algunenano**
### Changelog category (leave one):
- Performance Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
- Enable optimize_rewrite_sum_if_to_count_if by default

### Documentation entry for user-facing changes

This feature was disabled by default (https://github.com/ClickHouse/ClickHouse/pull/41388) because it was buggy. It should not be buggy anymore with the analyzer, so enable it and remove the old interpreter visitor (so people using it will get correct results).

If it ends up being buggy with the analyzer then we'll either fix it or remove the pass

### CODE REVIEW

**Comment by robot-ch-test-poll4** [comment]
*This is an automated comment for commit 1ba7e5942b9cf9ad2fc57593edda2098220ce3c5 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/62929/1ba7e5942b9cf9ad2fc57593edda2098220ce3c5/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

**Comment by devcrafter** [comment]
Shouldn't we check the setting around the corresponding pass [here](https://github.com/ClickHouse/ClickHouse/blob/d2c1dfff091c208f049e3c722b8e3c91c28e9a00/src/Analyzer/QueryTreePassManager.cpp#L263) ?

**Comment by Algunenano** [comment]
It is checked inside the pass -> https://github.com/ClickHouse/ClickHouse/blob/a343406da47f62f015a5b70590fae479a3894625/src/Analyzer/Passes/SumIfToCountIfPass.cpp#L31 This seems to be the standard way of doing it

**Review by devcrafter — APPROVED** [review]

**Comment by devcrafter** [comment]
> It is checked inside the pass ->
> 
> https://github.com/ClickHouse/ClickHouse/blob/a343406da47f62f015a5b70590fae479a3894625/src/Analyzer/Passes/SumIfToCountIfPass.cpp#L31
> 
> This seems to be the standard way of doing it

Yes. But to me, it looks more natural to do it in src/Analyzer/QueryTreePassManager.cpp where we add pass

**Comment by Algunenano** [comment]
I hear you, but changing all the setting checks should be part of a different PR.

**Comment by devcrafter** [comment]
> I hear you, but changing all the setting checks should be part of a different PR.
👍 
Of course, It isn't something like a call for action here, - more about sharing perception

**Comment by Algunenano** [comment]
* Fuzzer minimized:
```
SELECT
    concatWithSeparator(sum(if((number % NULL) = 0, toUInt256(1), toLowCardinality(0))), NULL)
FROM numbers(100)
```
Already fixed in https://github.com/ClickHouse/ClickHouse/pull/62999.


* Broken coverage: Trying to fix in https://github.com/ClickHouse/ClickHouse/pull/63130
* Integration tests (asan, old analyzer) [6/6]: Unrelated, azure.
* Stateless tests (aarch64): https://github.com/ClickHouse/ClickHouse/issues/57418 although it seems different now and probably related to recent changes to OPTIMIZE FINAL waiting for merges in RMT (cc @nickitat)
* Stress tests: Unrelated, query reading from dictionary. Not sure if we try to kill active queries

**Pull request merged**
