### PR TITLE
Artifacts s3 prefix

### PR DESCRIPTION
**Pull request by Felixoid**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Move the build report to the tests reports bucket. Move the build artifacts into the PRs prefix. We'll decrease TTL for them until 1 month.

### CODE REVIEW

**Comment by Felixoid** [comment]
I intentionally don't touch ccache here, I hope to handle it in https://github.com/ClickHouse/ClickHouse/pull/46240

**Comment by Felixoid** [comment]
Please, take a look. It will allow reducing the top level directories and expiring PRs in one month

**Comment by vdimir** [comment]
> We'll decrease TTL for them until 1 month.

What is the current TTL for build artifacts?

Btw, just a random idea - storing some particular builds for a longer time can be helpful, e.g., only release builds for merge commits in master can when you need to find where some regression or bug was introduced. On the other hand, you can always build it from sources, and it's required not too often to complicate infrastructure in such a way.

**Comment by Felixoid** [comment]
> What is the current TTL for build artifacts?

It used to be 1 year before yesterday, I've decreased it to 6 months globally, so it will remain the same for master and release artifacts. The RP builds will live for only one month.

I think, it as well addresses the second part of your message

**Comment by Felixoid** [comment]
It's green, any approval to merge?

**Review by rschu1ze — APPROVED** [review]

**Pull request merged**
