### PR TITLE
A new feature which is functioning like "window function" in SQL.

### PR DESCRIPTION
**Pull request by ghost**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- New Feature

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

A new feature which is functioning like `window function` in SQL.

Detailed description / Documentation draft:

I am using ClickHouse very well. It is very fast and durable OLAP Database.

Recently, I got a new need for a feature like `window function`. So I added new feature `early window function`.

It operates like `window function` in SQL, but the difference is that it operates before the aggregation and results of `early window function` can be used in the aggregation.

For more detailed explanation, I wrote an example.

```SQL
SELECT *
FROM early_window_test
WHERE id = 'a'
ORDER BY dt ASC

┌──────────────────dt─┬─id─┬─v─┐
│ 1970-01-01 09:00:01 │ a  │ 1 │
│ 1970-01-01 09:00:02 │ a  │ 2 │
│ 1970-01-01 09:00:03 │ a  │ 3 │
└─────────────────────┴────┴───┘
```

I will use a function of `early window function` to get the last value sorted by `dt` and partitioned by `id`.

```SQL
SELECT
    *,
    windowLast(dt, v, id)
FROM early_window_test
WHERE id = 'a'
ORDER BY dt ASC

┌──────────────────dt─┬─id─┬─v─┬─windowLast(dt, v, id)─┐
│ 1970-01-01 09:00:01 │ a  │ 1 │                     3 │
│ 1970-01-01 09:00:02 │ a  │ 2 │                     3 │
│ 1970-01-01 09:00:03 │ a  │ 3 │                     3 │
└─────────────────────┴────┴───┴───────────────────────┘
```

The `early window function` behaves like `window function`, but it is executed before a step of aggregation. So, the result of `early window function` can be used by `group by`.

```SQL
SELECT
    *,
    windowLast(dt, v, id)
FROM early_window_test
ORDER BY
    id ASC,
    dt ASC

┌──────────────────dt─┬─id─┬──v─┬─windowLast(dt, v, id)─┐
│ 1970-01-01 09:00:01 │ A  │ 10 │                    30 │
│ 1970-01-01 09:00:02 │ A  │ 20 │                    30 │
│ 1970-01-01 09:00:03 │ A  │ 30 │                    30 │
│ 1970-01-01 09:00:01 │ B  │ 10 │                    30 │
│ 1970-01-01 09:00:02 │ B  │ 20 │                    30 │
│ 1970-01-01 09:00:03 │ B  │ 30 │                    30 │
│ 1970-01-01 09:00:01 │ a  │  1 │                     3 │
│ 1970-01-01 09:00:02 │ a  │  2 │                     3 │
│ 1970-01-01 09:00:03 │ a  │  3 │                     3 │
│ 1970-01-01 09:00:01 │ b  │  3 │                     1 │
│ 1970-01-01 09:00:02 │ b  │  2 │                     1 │
│ 1970-01-01 09:00:03 │ b  │  1 │                     1 │
└─────────────────────┴────┴────┴───────────────────────┘

SELECT
    windowLast(dt, v, id) AS last,
    count()
FROM early_window_test
GROUP BY last

┌─last─┬─count()─┐
│    3 │       3 │
│   30 │       6 │
│    1 │       3 │
└──────┴─────────┘
```

Thank you.

**2020-06-17 Added**
`EarlyWindowFunction` collects only local data not for the distributed data.
When Data is distributed by `user_id` among nodes, the partition key of `EarlyWindowFunction` must be the `user_id`.

### CODE REVIEW

**Comment by achimbab** [comment]
@alexey-milovidov 
The previous version of pipeline in `InterpreterSelectQuery` has gone.... lol
I have to modify this feature to use the new version of QueryPipeline.

**Comment by filimonov** [comment]
does it work across blocks / threads?

**Comment by achimbab** [comment]
@filimonov 
It seems to work fine across blocks as the below example.
```SQL
CREATE TABLE default.wl1
(
    `d` Date,
    `dt` DateTime,
    `id` String,
    `v` Int32
)
ENGINE = MergeTree()
PARTITION BY d
ORDER BY id
SETTINGS index_granularity = 8192;
```
```SQL
SELECT *
FROM wl1
FORMAT PrettySpace

         d                    dt   id    v

1970-01-02   1970-01-01 09:00:01   a    10
1970-01-02   1970-01-01 09:00:02   a    11
1970-01-02   1970-01-01 09:00:03   a    12
         d                    dt   id    v

1970-01-03   1970-01-01 09:00:04   a    13
1970-01-03   1970-01-01 09:00:05   a    14
1970-01-03   1970-01-01 09:00:06   a    15
```
```SQL
SELECT
    *,
    windowLast(dt, v, id)
FROM wl1
FORMAT PrettySpace

         d                    dt   id    v   windowLast(dt, v, id)

1970-01-03   1970-01-01 09:00:04   a    13                      15
1970-01-03   1970-01-01 09:00:05   a    14                      15
1970-01-03   1970-01-01 09:00:06   a    15                      15
1970-01-02   1970-01-01 09:00:01   a    10                      15
1970-01-02   1970-01-01 09:00:02   a    11                      15
1970-01-02   1970-01-01 09:00:03   a    12                      15
```

In terms of threads, while processing `early window function` it makes only one `EarlyWindowBlockInputStream` so it works in only one thread.

Please let me know if there is a problem.

Thank you.

**Comment by achimbab** [comment]
`EarlyWindowFunction` collects only local data not for the distributed data.
When Data is distributed by user_id among nodes, the partition key of EarlyWindowFunction must be the user_id`.

**Comment by amosbird** [comment]
What's the difference between using subqueries order by and "Early Window Function" ?
```
select * from
   ( select * from ... order by ...)
group by ...

**Comment by achimbab** [comment]
@amosbird 
Sorry for my late reply for your comment.

It is also possible using subqueries. 

```SQL
SELECT *
FROM 
(
    SELECT 
        d,
        dt,
        id,
        groupArray(v) AS g,
        anyLast(v) AS l
    FROM wl1
    GROUP BY 
        d,
        dt,
        id
    ORDER BY 
        d ASC,
        dt ASC,
        id ASC
)
ARRAY JOIN g
ORDER BY 
    d ASC,
    g ASC


 2020-11-15   2020-11-15 00:00:00   a    10   12
 2020-11-15   2020-11-15 00:00:00   a    11   12
 2020-11-15   2020-11-15 00:00:00   a    12   12
 2020-11-16   2020-11-16 00:00:00   a    13   14
 2020-11-16   2020-11-16 00:00:00   a    14   14
```

`windowLast` is more simple and It can be more optimized than the combination of `groupArray()` and `ARRAY JOIN`.

**Comment by achimbab** [comment]
Close this PR.
I closed this PR due to #18222.

**Pull request closed without merging**
