### PR TITLE
Added nano- micro- milliseconds unit for `date_trunc`

### PR DESCRIPTION
**Pull request by Misz606**
Fixes. https://github.com/ClickHouse/clickhouse-core-incidents/issues/89
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Added nano- micro- milliseconds unit for date_trunc

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

---
### Modify your CI run:
**NOTE:** If your merge the PR with modified CI you **MUST KNOW** what you are doing
**NOTE:** Checked options will be applied if set before CI RunConfig/PrepareRunConfig step

#### Include tests (required builds will be added automatically):
- [ ]  Fast test
- [ ]  Integration Tests
- [ ]  Stateless tests
- [ ]  Stateful tests
- [ ]  Unit tests
- [ ]  Performance tests
- [ ]  All with ASAN
- [ ]  All with TSAN
- [ ]  All with Analyzer
- [ ]  Add your option here

#### Exclude tests:
- [ ]  Fast test
- [ ]  Integration Tests
- [ ]  Stateless tests
- [ ]  Stateful tests
- [ ]  Performance tests
- [ ]  All with ASAN
- [ ]  All with TSAN
- [ ]  All with MSAN
- [ ]  All with UBSAN
- [ ]  All with Coverage
- [ ]  All with Aarch64
- [ ]  Add your option here

#### Extra options:
- [ ]  do not test (only style check)
- [ ]  disable merge-commit (no merge from master before tests)
- [ ]  disable CI cache (job reuse)

#### Only specified batches in multi-batch jobs:
- [ ]  1
- [ ]  2
- [ ]  3
- [ ]  4

### CODE REVIEW

**Comment by robot-ch-test-poll1** [comment]
*This is an automated comment for commit 497e3bb48fb622668adc0dbbf2ef6aa8e6b58bdd with description of existing statuses. It's updated for the latest CI running*

[❌ Click here](https://s3.amazonaws.com/clickhouse-test-reports/62335/497e3bb48fb622668adc0dbbf2ef6aa8e6b58bdd/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>❌ failure</td></tr>
<tbody>
</table>

**Review by alexey-milovidov — APPROVED** [review]

**Comment by yariks5s** [comment]
The thing is that new time units work OK with times before the Unix epoch, but bigger time units return strange results. Some of them return 1970-01-01: https://fiddle.clickhouse.com/0f8c3b48-252d-43ac-ab23-7b94fc8e6f3e, some of them return strange results: https://fiddle.clickhouse.com/f85fd340-a496-4678-a859-9e66091d58f4. I will write an issue about that

**Review by ArctypeZach — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
> AST fuzzer (asan) — Received signal 11

This requires investigation :rocket: 

> Performance Comparison [1/4] — 6 errors, 1 faster, 1 unstable 

Please merge with master :heart:

**Comment by clickgapai** [comment]
Hi @Misz606 @yariks5s @alexey-milovidov @ArctypeZach — while reviewing this PR I found the following:

- **Coverage gap:** `dateTrunc` 3-argument timezone form for `millisecond`/`microsecond`/`nanosecond` is untested; output `DataTypeDateTime64` scale (3/6/9) is also not asserted via `toTypeName` — https://github.com/ClickHouse/ClickHouse/pull/104012

Could you review the test PR and add the `can be tested` label if it looks good?
Happy to discuss — close anything that's wrong or already addressed.

**Pull request merged**
