### PR TITLE
Revert "Enable custom parquet encoder by default"

### PR DESCRIPTION
**Pull request by alexey-milovidov**
Reverts ClickHouse/ClickHouse#62088

### CODE REVIEW

**Comment by robot-ch-test-poll3** [comment]
*This is an automated comment for commit 10f7125fa6babe34e73dd6530f00821b694bdc3b with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/63153/10f7125fa6babe34e73dd6530f00821b694bdc3b/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

**Comment by ucasfl** [comment]
Why revert this PR?

**Comment by antaljanosbenjamin** [comment]
It broke one of our tests: `03036_parquet_arrow_nullable`.

**Comment by alexey-milovidov** [comment]
Yes, and the reason maybe not in the PR itself but in the race between merging different PRs.

**Pull request merged**
