### PR TITLE
Fix cluster() for inter-server secret (preserve initial user as before)

### LINKED ISSUE #66287: cluster + prefer_localhost_replica allows to query unprivileged data
table t1 is not granted to user foo, but `cluster` allows to read data from it.

```sql
CREATE TABLE t1 (d Date) ENGINE = MergeTree order by d as select today();
create user foo identified by 'xxx';
grant REMOTE ON *.* to foo;
```

24.3.4

```
$ clickhouse-client -u foo --password=xxx -q 'select count(*),user(),version() from cluster(default,default,t1) settings prefer_localhost_replica=1'

Received exception from server (version 24.3.4):
Code: 497. DB::Exception: Received from localhost:9000. DB::Exception: foo: Not enough privileges. To execute this query,

$ clickhouse-client -u foo --password=xxx -q 'select count(*),user(),version() from cluster(default,default,t1) settings prefer_localhost_replica=0'
1	foo	24.3.4.147
```

24.6.2.17

```
$ clickhouse-client -u foo --password=xxx -q 'select count(*),user(),version() from cluster(default,default,t1) settings prefer_localhost_replica=1'

Received exception from server (version 24.6.2):
Code: 497. DB::Exception: Received from localhost:9000. DB::Exception: foo: Not enough privileges.

$ clickhouse-client -u foo --password=xxx -q 'select count(*),user(),version() from cluster(default,default,t1) settings prefer_localhost_replica=0'
1	foo	24.6.2.17
```

--------

using secret

```
cat /etc/clickhouse-server/config.d/default_secret.xml
<clickhouse>
   <remote_servers>
      <default_secret>
          <secret>xxxx</secret>
          <shard>
              <replica>
                  <host>localhost</host>
                  <port>9000</port>
              </replica>
          </shard>
      </default_secret>
  </remote_servers>
</clickhouse>
```

24.3.4
```
$ clickhouse-client -u foo --password=xxx -q 'select count(*),user(),version() from cluster(default_secret,default,t1) settings prefer_localhost_replica=1'

Received exception from server (version 24.3.4):
Code: 497. DB::Exception: Received from localhost:9000. DB::Exception: foo: Not enough privileges. To execute this 

$ clickhouse-client -u foo --password=xxx -q 'select count(*),user(),version() from cluster(default_secret,default,t1) settings prefer_localhost_replica=0'

Received exception from server (version 24.3.4):
Code: 497. DB::Exception: Received from localhost:9000. DB::Exception: Received from localhost:9000. DB::Exception: foo: Not enough privileges. 
```

24.6.2

```
$ clickhouse-client -u foo --password=xxx -q 'select count(*),user(),version() from cluster(default_secret,default,t1) settings prefer_localhost_replica=1'

Received exception from server (version 24.6.2):
Code: 497. DB::Exception: Received from localhost:9000. DB::Exception: foo: Not enough privileges. 

$ clickhouse-client -u foo --password=xxx -q 'select count(*),user(),version() from cluster(default_secret,default,t1) settings prefer_localhost_replica=0'
1	foo	24.6.2.17
```

### LINKED ISSUE #66352: Table function `cluster` doesn't work when using cluster secret for authentication
**Describe the unexpected behaviour**
After upgrading to version 24.5, the table function `cluster` stops working with following error on initial server:

```
Received exception from server (version 24.5.3):
Code: 210. DB::Exception: Received from int:9011. DB::Exception: Connection reset by peer, while reading from socket (peer: 10.123.123.2:9001, local: 10.123.123.1:44352): while receiving packet from 10.32.32.1:9001: While executing Remote. (NETWORK_ERROR)
```

Remote hosts showing auth error:

```
2024.07.10 15:10:36.696500 [ 1334417 ] {} <Error> Access(user directories): from: 10.123.123.1, user: default: Authentication failed: Code: 192. DB::Exception: There is no user `default` in users_xml. (UNKNOWN_USER), Stack trace (when copying this message, always include the lines below):

0. ./build/./src/Common/Exception.cpp:101: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000c99d719
1. DB::Exception::Exception(PreformattedMessage&&, int) @ 0x000000000712926c
2. DB::Exception::Exception<String, String const&>(int, FormatStringHelperImpl<std::type_identity<String>::type, std::type_identity<String const&>::type>, String&&, String const&) @ 0x0000000007a51a4b
3. ./build/./src/Access/IAccessStorage.cpp:0: DB::IAccessStorage::throwNotFound(DB::AccessEntityType, String const&) const @ 0x000000000fa7f2a1
4. ./build/./src/Access/IAccessStorage.cpp:0: DB::IAccessStorage::authenticateImpl(DB::Credentials const&, Poco::Net::IPAddress const&, DB::ExternalAuthenticators const&, bool, bool, bool) const @ 0x000000000fa832fa
5. ./src/Access/IAccessStorage.cpp:511: DB::MultipleAccessStorage::authenticateImpl(DB::Credentials const&, Poco::Net::IPAddress const&, DB::ExternalAuthenticators const&, bool, bool, bool) const @ 0x000000000fabb93a
6. ./src/Access/IAccessStorage.cpp:499: DB::AccessControl::authenticate(DB::Credentials const&, Poco::Net::IPAddress const&, String const&) const @ 0x000000000f9f7ca4
7. ./contrib/llvm-project/libcxx/include/string:1499: DB::Session::authenticate(DB::Credentials const&, Poco::Net::SocketAddress const&) @ 0x0000000010f53d24
8. ./src/Access/Credentials.h:17: DB::TCPHandler::receiveQuery() @ 0x00000000123dbe89
9. ./build/./src/Server/TCPHandler.cpp:0: DB::TCPHandler::receivePacket() @ 0x00000000123d1084
10. ./build/./src/Server/TCPHandler.cpp:0: DB::TCPHandler::runImpl() @ 0x00000000123c1c8b
11. ./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:593: DB::TCPHandler::run() @ 0x00000000123de9d9
12. ./build/./base/poco/Net/src/TCPServerConnection.cpp:57: Poco::Net::TCPServerConnection::start() @ 0x0000000014e4bf32
13. ./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:48: Poco::Net::TCPServerDispatcher::run() @ 0x0000000014e4cdd9
14. ./build/./base/poco/Foundation/src/ThreadPool.cpp:202: Poco::PooledThread::run() @ 0x0000000014f48001
15. ./base/poco/Foundation/include/Poco/SharedPtr.h:231: Poco::ThreadImpl::runnableEntry(void*) @ 0x0000000014f4659d
16. start_thread @ 0x0000000000007ea7
17. ? @ 0x00000000000fba6f
 (version 24.4.1.1)
```

For some reason, inter server connection is trying to use authentication with initial user `default` instead of current user (and we don't even have user `default`).

May relates to https://github.com/ClickHouse/ClickHouse/pull/63013 because when creating cluster address, if we don't have `user` in config then then it will use "default".

```
Cluster::Address::Address(
        const Poco::Util::AbstractConfiguration & config,
        const String & config_prefix,
        const String & cluster_,
        const String & cluster_secret_,
        UInt32 shard_index_,
        UInt32 replica_index_)
    : cluster(cluster_)
    , cluster_secret(cluster_secret_)
    , shard_index(shard_index_)
    , replica_index(replica_index_)
{
    host_name = config.getString(config_prefix + ".host");
    if (config.has(config_prefix + ".user"))
        user_specified = true;

    user = config.getString(config_prefix + ".user", "default");
    ...
```

cc @azat

### PR DESCRIPTION
**Pull request by azat**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix cluster() for inter-server secret (preserve initial user as before)

The behaviour of cluster() with inter-server secret had been changed in #63013,
after it started to use "default" user, and this introduces a
regression.

The intention of that patch was to adjust only remote(), since it only
it accept custom user, which should be ignored.

Fixes: https://github.com/ClickHouse/ClickHouse/issues/66287 (cc @den-crane @pufit )
Fixes: https://github.com/ClickHouse/ClickHouse/issues/66352 (cc @canhld94 )
Fixes: #63013

### CODE REVIEW

**Comment by robot-clickhouse-ci-1** [comment]
*This is an automated comment for commit d75cbef5005b8a0a5bb87a3e7b12ff7463517857 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/66364/d75cbef5005b8a0a5bb87a3e7b12ff7463517857/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/d2ad1cef33f3a4b6157c02161dc786f9d406f59e/docs_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Review by pufit — APPROVED** [review]

**Comment by azat** [comment]
>Tests are not finished, fail: 6, passed: 1419, skipped

```
clickhouse-server: /build/src/Databases/DDLLoadingDependencyVisitor.cpp:216: static void DB::DDLLoadingDependencyVisitor::extractTableNameFromArgument(const ASTFunction &, Data &, size_t): Assertion `false' failed.
```

Will do a rebase

**Comment by azat** [comment]
@pufit any clue why cloud fork sync failed? Does something required to be done from my side?

**Comment by azat** [comment]
>[Integration tests flaky check (asan) — Failed tests found: error: 0, passed: 141, fail: 4, skipped: 0, broken: 0, not_fail: 0](https://s3.amazonaws.com/clickhouse-test-reports/66364/0dccc34a2004b075e290ebfd5ecc9fea3077a205/integration_tests_flaky_check__asan_.html)

Flaky check fixed in [`bdfaffa` (#66364)](https://github.com/ClickHouse/ClickHouse/pull/66364/commits/bdfaffa9d74b0405ea619330215e6c71f0b6976a)

**Comment by azat** [comment]
https://s3.amazonaws.com/clickhouse-test-reports/66364/189d1848488bb3e126df3172ac1ca18a2e315af9/integration_tests__asan__old_analyzer__[5_6].html

Fixed in da3a37c56167

**Pull request merged**
