### PR TITLE
Fix clang-tidy issue

### PR DESCRIPTION
**Pull request by HeenaBansal2009**
Changelog category:
- Not for changelog

### CODE REVIEW

**Comment by evillique** [comment]
So I can't see any warnings or things of this kind when I build ClickHouse. Can you please specify what the issue is exactly and how does it look like?

**Comment by HeenaBansal2009** [comment]
> So I can't see any warnings or things of this kind when I build ClickHouse without this fix. Could you please specify what the issue is exactly and how does it look like?
@evillique , I scanned the clickhouse source code with codecheckor which includes clangsa and clang-tidy issues. This is one of them. 
image

**Review by evillique — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
@HeenaBansal2009 Let's enable it in `.clang-tidy` if it's not enabled yet.

**Comment by HeenaBansal2009** [comment]
> @HeenaBansal2009 Let's enable it in `.clang-tidy` if it's not enabled yet.
@alexey-milovidov , Checker is added in .clang-tidy.

**Pull request merged**
