### PR TITLE
Fix multithreaded ASOF JOIN + some refactoring

### PR DESCRIPTION
**Pull request by 4ertus2**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

For changelog. Remove if this is non-significant change.

Category (leave one):
- Bugfix

Short description (up to few sentences):
Add locks for ASOF lookup data cause it has multithreaded access. Replace some macro code with templates.

### CODE REVIEW

**Comment by 4ertus2** [comment]
FYI @Gladdy

**Comment by Gladdy** [comment]
@4ertus2 The last changes being the removal of the macros or the my cleanup to make the timestamps work correctly?

**Comment by 4ertus2** [comment]
> @4ertus2 The last changes being the removal of the macros or the my cleanup to make the timestamps work correctly?

Cleanup & changes from std::map to PODArray.

**Comment by Gladdy** [comment]
Hmm - I'd be very curious to know what went wrong then. Note, that I haven't done much testing on "real" data yet, just focused on the writing and passing the test queries. If you need any help please let me know as I'm sure I'll run into the same errors when running asof on actual data that is more complicated than the test queries and those should obviously get fixed :)

**Comment by 4ertus2** [comment]
> Hmm - I'd be very curious to know what went wrong then. Note, that I haven't done much testing on "real" data yet, just focused on the writing and passing the test queries. If you need any help please let me know as I'm sure I'll run into the same errors when running asof on actual data that is more complicated than the test queries and those should obviously get fixed :)

It looks that it's something with PODArray or how we use it. It crashes when (c_end - c_end_of_storage) = 4096 + 16. That is something unexpected.

**Comment by Gladdy** [comment]
Not sure about the PODArray limitations (though shouldn't the storage extend beyond end as otherwise use you are in invalid memory? end_of_storage should be > end? The 4k might be hitting the next (unmapped) page or is just an artifact of the initial size and it not resizing correctly beyond that?) but I don't see why the hash map would not support the placement new of the AsofRowRefs object. What kind of restrictions does it place on the values stored?

**Comment by 4ertus2** [comment]
> Ah, I see now that `std::is_trivially_copyable<AsofRowRefs>::value == false`, which is a requirement for std::memmove (https://en.cppreference.com/w/cpp/string/byte/memmove) , so it shouldn't be stored in the HashTable as there is a comment about it:

Yup, I'm on the way to split AsofRowRefs::Entry and lookup structures (and make it movable). But the first attempt failed. Working for it.

**Comment by Gladdy** [comment]
Thanks for the work on making the AsofRowRefs movable (and spotting the race condition on the sorting that I had missed in introducing the SortedLookupPODArray). We should probably add a test that stresses the ASOF join beyond 4k elements with a sufficiently big hash table that the moving actually occurs and/or adding a static assert that the requirements on the hash table values are actually met?

**Comment by 4ertus2** [comment]
> We should probably add a test that stresses the ASOF join beyond 4k elements with a sufficiently big hash table that the moving actually occurs and/or adding a static assert that the requirements on the hash table values are actually met?

Currently SortedLookupPODArray uses std::vector<T> as Base cause if I changed it to PaddedPODArray it still crashes on inserts. I have no time to investigate the problem and make test. It would be cool if you have some. Generally we use insert select from system.numbers table to generate some data for stateless test. You can find samples in tests directory by searching numbers() or system.number.

> I'm not quite sure how this case differs from AsofRows, as both values seem to manage some external buffer via a pointer?

I'm not sure I understand the question. Currently AsofRowRefs contains one pointer to data in Join.asof_lookup_lists. Every time we find new key we push_back a new item into Join.asof_lookup_lists and hold it there till the Join's die. And place pointer to it into HashMap via AsofRowRefs. So it looks correct to have any number of pointers to their elements while Join hold them. We don't place std::vector into HashMap itself anymore.

**Comment by Gladdy** [comment]
I doubt PaddedPODArray vs std::vector is going to make a huge difference in performance (and if there is any performance issue later down the line profiling will show whether it is actually in that bit of the code), so whilst I did think that swapping out std::map versus this approach was going to make a big difference, I doubt PODArray vs vector is going to be. I might have quick look later though to see if I can work some things out and add a test that actually stresses the ASOF join in terms of hash table / vector size rather than the basic functionality tests included so far.

If you do not place std::vector in HashMap anymore then that invalidates my point, though it does seem to be done in `ComplexKeyCacheDictionary.cpp:172`? Not sure whether that class is actually used for any real work.

**Comment by 4ertus2** [comment]
> I doubt PaddedPODArray vs std::vector is going to make a huge difference in performance

Me too. The question is why implementation with PODArray crashes. It could be some error that is well visible with PODArray and may be hidden but not fixed with std::vector.

> If you do not place std::vector in HashMap anymore then that invalidates my point, though it does seem to be done in `ComplexKeyCacheDictionary.cpp:172`? Not sure whether that class is actually used for any real work.

It could be a mistake. It's better to make a question issue. Just not to forget.

**Comment by Gladdy** [comment]
Ok. After running some bigger tests under perf which I'll add soon, I'll try to also have a look at the locking structure (obviously the inserts have to be guarded), but I hope to make it slightly more multicore friendly than having a single std::mutex protecting all of the AsofRowRefs (needed per object for the sorting, but not the lookups).

**Pull request merged**
