### PR TITLE
Fix Crash in JSON extract from low cardinality String Tuple

### PR DESCRIPTION
**Pull request by AlfVII**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in official stable or prestable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix Crash in function JSONExtract with LowCardinality https://github.com/ClickHouse/ClickHouse/issues/42632

This PR fixes the crash produced by Merge https://github.com/ClickHouse/ClickHouse/pull/41726
Reporterd in: #42632 
And can avoid this revert: [#42633](https://github.com/ClickHouse/ClickHouse/pull/42633)

### CODE REVIEW

**Comment by CurtizJ** [comment]
Another case:
```
SELECT JSONExtract(materialize('{"a": 131231}'), 'a', 'LowCardinality(FixedString(4))') FROM numbers(10)


Received exception from server (version 22.10.1):
Code: 49. DB::Exception: Received from localhost:9000. DB::Exception: Invalid number of rows in Chunk column ColumnLowCardinality position 0: expected 10, got 25. (LOGICAL_ERROR)
```

**Comment by CurtizJ** [comment]
This is also inconsistent:
```sql
SELECT JSONExtract('{"a": 123456}', 'a', 'FixedString(4)')

┌─JSONExtract('{"a": 123456}', 'a', 'FixedString(4)')─┐
│ 1234                                                │
└─────────────────────────────────────────────────────┘

SELECT JSONExtract('{"a": "123456"}', 'a', 'FixedString(4)')


┌─JSONExtract('{"a": "123456"}', 'a', 'FixedString(4)')─┐
│                                                       │
└───────────────────────────────────────────────────────┘
```

Why it tries to extract first 4 bytes in first cast, but returns default in the second case. I prefer the behaviour from the second case, because trying to extract raw data to `FixedString` leads to writing some garbage, which is not very useful. E.g.:
```
SELECT JSONExtract('{"a": "123456"}', 'FixedString(3)')

┌─JSONExtract('{"a": "123456"}', 'FixedString(3)')─┐
│ {"a                                              │
└──────────────────────────────────────────────────┘

SELECT JSONExtract('{"a": "123456"}', 'String')

┌─JSONExtract('{"a": "123456"}', 'String')─┐
│ {"a":"123456"}                           │
└──────────────────────────────────────────┘
```

In case of `String` you can get serialized `JSON` object and do smth with it on client, but in case of `FixedString`, it's not clear what you can do with such data.

**Comment by AlfVII** [comment]
I am closing this PR and making a new one with the reverted code from https://github.com/ClickHouse/ClickHouse/pull/41726 and the fixes for the test failing here

**Comment by AlfVII** [comment]
Closing and moving to #42761

**Pull request closed without merging**
