### PR TITLE
alpine docker images - use ubuntu 22.04 as glibc donor

### PR DESCRIPTION
**Pull request by filimonov**
### Changelog category (leave one):
- Build/Testing/Packaging Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
alpine docker images now use ubuntu 22.04 as glibc donor, results in upgrade of glibc version delivered with alpine images from 2.31 to 2.35

### Documentation entry for user-facing changes
20.04 is coming to EOL in April 2025 - https://ubuntu.com/about/release-cycle

```
$ docker run --rm -it ubuntu:20.04
root@47296984e423:/#  ldd --version 
ldd (Ubuntu GLIBC 2.31-0ubuntu9.16) 2.31
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.

$ docker run --rm -it ubuntu:22.04
root@bd4869bd97c9:/# ldd --version
ldd (Ubuntu GLIBC 2.35-0ubuntu3.8) 2.35
Copyright (C) 2022 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.

$ docker run --rm -it ubuntu:24.04
root@f5256d7e8c5a:/#  ldd --version
ldd (Ubuntu GLIBC 2.39-0ubuntu8.2) 2.39
Copyright (C) 2024 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```

Here are glibc release notes https://sourceware.org/glibc/wiki/Glibc%20Timeline

Looks like kernel requirements did not change, so the upgrade seems safe.

### CODE REVIEW

**Review by Algunenano — COMMENTED** [review]
Wouldn't it make more sense to use the MUSL build for alpine images and forget about glibc instead? What's missing to be able to do that?

**Comment by filimonov** [comment]
Yes, it would be better. I'm not 100% sure if there are some blockers for that still, may be @al13n321 or @alexey-milovidov can know.

**Review by alexey-milovidov — APPROVED** [review]
The PR LGTM.

**Comment by alexey-milovidov** [comment]
Yes, it would be much better to use the Musl build here.

The problem is that it is currently only tested with the Fast Test, but not with all the test suite.
It means that it is not production-ready. If we have a different binary for Alpine, it means we will have to accept bug reports for two different binaries, one of which isn't well-tested. And some users will install Alpine for anecdotal reasons (despite the fact that it does not make sense at all).

We plan to migrate to Musl builds everywhere, so they will be tested by almost all test suites (however, sanitizers cannot use Musl, but they don't test glibc either, so that's ok), and then we will use Musl builds both in Alpine and Ubuntu.

**Comment by robot-ch-test-poll** [comment]
*This is an automated comment for commit cf1f3b4bd22d49a00e47a7904735c8b00fe85436 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/69033/cf1f3b4bd22d49a00e47a7904735c8b00fe85436/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Builds</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/e7d63b5f79fbf4ac5facbfee07ed373d9d22e9cf/builds/report.html">✅ success</a></td></tr>
<tr><td>ClickBench</td><td>Runs [ClickBench](https://github.com/ClickHouse/ClickBench/) with instant-attach table</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/e7d63b5f79fbf4ac5facbfee07ed373d9d22e9cf/clickbench__aarch64_.html">✅ success</a></td></tr>
<tr><td>Compatibility check</td><td>Checks that <b>clickhouse</b> binary runs on distributions with old libc versions. If it fails, ask a maintainer for help</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/e7d63b5f79fbf4ac5facbfee07ed373d9d22e9cf/compatibility_check__aarch64_.html">✅ success</a></td></tr>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td>✅ success</td></tr>
<tr><td>Fast test</td><td>Normally this is the first check that is ran for a PR. It builds ClickHouse and runs most of <a href="https://clickhouse.com/docs/en/development/tests#functional-tests">stateless functional tests</a>, omitting some. If it fails, further checks are not started until it is fixed. Look at the report to see which tests fail, then reproduce the failure locally as described <a href="https://clickhouse.com/docs/en/development/tests#functional-test-locally">here</a></td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/68900/f9dc1e8e1aceeef4c41f7dace24c8fbb37c2baec/fast_test.html">✅ success</a></td></tr>
<tr><td>Flaky tests</td><td>Checks if new added or modified tests are flaky by running them repeatedly, in parallel, with more randomization. Functional tests are run 100 times with address sanitizer, and additional randomization of thread scheduling. Integration tests are run up to 10 times. If at least once a new test has failed, or was too long, this check will be red. We don't allow flaky tests, read <a href="https://clickhouse.com/blog/decorating-a-christmas-tree-with-the-help-of-flaky-tests/">the doc</a></td><td>✅ success</td></tr>
<tr><td>Install packages</td><td>Checks that the built packages are installable in a clear environment</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/e7d63b5f79fbf4ac5facbfee07ed373d9d22e9cf/install_packages__aarch64_.html">✅ success</a></td></tr>
<tr><td>Integration tests</td><td>The integration tests report. In parenthesis the package type is given, and in square brackets are the optional part/total tests</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/e7d63b5f79fbf4ac5facbfee07ed373d9d22e9cf/integration_tests__aarch64__[1_6].html">✅ success</a></td></tr>
<tr><td>Performance Comparison</td><td>Measure changes in query performance. The performance test report is described in detail <a href="https://github.com/ClickHouse/ClickHouse/tree/master/docker/test/performance-comparison#how-to-read-the-report">here</a>. In square brackets are the optional part/total tests</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/e7d63b5f79fbf4ac5facbfee07ed373d9d22e9cf/performance_comparison__release__[1_4]/report.html">✅ success</a></td></tr>
<tr><td>Stateful tests</td><td>Runs stateful functional tests for ClickHouse binaries built in various configurations -- release, debug, with sanitizers, etc</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/e7d63b5f79fbf4ac5facbfee07ed373d9d22e9cf/stateful_tests__aarch64_.html">✅ success</a></td></tr>
<tr><td>Stateless tests</td><td>Runs stateless functional tests for ClickHouse binaries built in various configurations -- release, debug, with sanitizers, etc</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/e7d63b5f79fbf4ac5facbfee07ed373d9d22e9cf/stateless_tests__aarch64_.html">✅ success</a></td></tr>
<tr><td>Stress test</td><td>Runs stateless functional tests concurrently from several clients to detect concurrency-related errors</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/e7d63b5f79fbf4ac5facbfee07ed373d9d22e9cf/stress_test__asan_.html">✅ success</a></td></tr>
<tr><td>Unit tests</td><td>Runs the unit tests for different release types</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/e7d63b5f79fbf4ac5facbfee07ed373d9d22e9cf/unit_tests__asan_.html">✅ success</a></td></tr>
<tr><td>Upgrade check</td><td>Runs stress tests on server version from last release and then tries to upgrade it to the version from the PR. It checks if the new server can successfully startup without any errors, crashes or sanitizer asserts</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/69040/587bc80d5bce15284342bb70b8b50c395a2afa36/upgrade_check__debug_.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Comment by alexey-milovidov** [comment]
@filimonov, it didn't work: 
```
ERROR: failed to solve: failed to compute cache key: failed to calculate checksum of ref h59767hjxkahyqm5x9jz6azuk::63zw3gw0twb95hlh59l1un5ub: "/lib/linux-gnu/ld-2.31.so": not found
ERROR:root:The following command failed, sleep 10 before retry: docker buildx build --output=type=docker --platform=linux/amd64 --label=build-url=https://github.com/ClickHouse/ClickHouse/actions/runs/10599117447 --label=com.clickhouse.build.githash=03f31365d49f6707c54590f60baf30c939c79d44 --label=com.clickhouse.build.version= --build-arg=DIRECT_DOWNLOAD_URLS='https://s3.amazonaws.com/clickhouse-builds/PRs/68900/f9dc1e8e1aceeef4c41f7dace24c8fbb37c2baec/package_release/clickhouse-client-24.9.1.1511-amd64.tgz https://s3.amazonaws.com/clickhouse-builds/PRs/68900/f9dc1e8e1aceeef4c41f7dace24c8fbb37c2baec/package_release/clickhouse-client-24.9.1.1511-amd64.tgz.sha512 https://s3.amazonaws.com/clickhouse-builds/PRs/68900/f9dc1e8e1aceeef4c41f7dace24c8fbb37c2baec/package_release/clickhouse-common-static-24.9.1.1511-amd64.tgz https://s3.amazonaws.com/clickhouse-builds/PRs/68900/f9dc1e8e1aceeef4c41f7dace24c8fbb37c2baec/package_release/clickhouse-common-static-24.9.1.1511-amd64.tgz.sha512 https://s3.amazonaws.com/clickhouse-builds/PRs/68900/f9dc1e8e1aceeef4c41f7dace24c8fbb37c2baec/package_release/clickhouse-server-24.9.1.1511-amd64.tgz https://s3.amazonaws.com/clickhouse-builds/PRs/68900/f9dc1e8e1aceeef4c41f7dace24c8fbb37c2baec/package_release/clickhouse-server-24.9.1.1511-amd64.tgz.sha512' --tag=clickhouse/clickhouse-server:head-alpine-amd64 --metadata-file=/home/ubuntu/actions-runner/_work/_temp/test/head-alpine-amd64 --build-arg=VERSION='24.9.1.1' --progress=plain --file=/home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/docker/server/Dockerfile.alpine /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/docker/server
Run action failed for: [Docker server image] with exit code [1]
```

**Comment by filimonov** [comment]
Sorry, missed the CI/CD report - it somehow arrived much later. And again it's not moving now. 

Now seems to work (checked locally)

```
$ docker buildx build --output=type=docker --platform=linux/amd64 --label=build-url=https://github.com/ClickHouse/ClickHouse/actions/runs/10599117447 --label=com.clickhouse.build.githash=03f31365d49f6707c54590f60baf30c939c79d44 --label=com.clickhouse.build.version= --build-arg=DIRECT_DOWNLOAD_URLS='https://s3.amazonaws.com/clickhouse-builds/PRs/68900/f9dc1e8e1aceeef4c41f7dace24c8fbb37c2baec/package_release/clickhouse-client-24.9.1.1511-amd64.tgz https://s3.amazonaws.com/clickhouse-builds/PRs/68900/f9dc1e8e1aceeef4c41f7dace24c8fbb37c2baec/package_release/clickhouse-client-24.9.1.1511-amd64.tgz.sha512 https://s3.amazonaws.com/clickhouse-builds/PRs/68900/f9dc1e8e1aceeef4c41f7dace24c8fbb37c2baec/package_release/clickhouse-common-static-24.9.1.1511-amd64.tgz https://s3.amazonaws.com/clickhouse-builds/PRs/68900/f9dc1e8e1aceeef4c41f7dace24c8fbb37c2baec/package_release/clickhouse-common-static-24.9.1.1511-amd64.tgz.sha512 https://s3.amazonaws.com/clickhouse-builds/PRs/68900/f9dc1e8e1aceeef4c41f7dace24c8fbb37c2baec/package_release/clickhouse-server-24.9.1.1511-amd64.tgz https://s3.amazonaws.com/clickhouse-builds/PRs/68900/f9dc1e8e1aceeef4c41f7dace24c8fbb37c2baec/package_release/clickhouse-server-24.9.1.1511-amd64.tgz.sha512' --tag=clickhouse/clickhouse-server:head-alpine-amd64  --build-arg=VERSION='24.9.1.1' --progress=plain --file=$(pwd)/docker/server/Dockerfile.alpine $(pwd)/docker/server
#1 [internal] load build definition from Dockerfile.alpine
#1 transferring dockerfile: 4.02kB done
#1 DONE 0.0s

#2 [internal] load .dockerignore
#2 transferring context: 2B done
#2 DONE 0.0s

#3 [internal] load metadata for docker.io/library/alpine:latest
#3 DONE 0.0s

#4 [internal] load metadata for docker.io/library/ubuntu:20.04
#4 DONE 0.0s

#5 [stage-1 1/9] FROM docker.io/library/alpine
#5 DONE 0.0s

#6 [glibc-donor 1/2] FROM docker.io/library/ubuntu:20.04
#6 DONE 0.0s

#7 [internal] load build context
#7 transferring context: 9.52kB done
#7 DONE 0.0s

#8 [glibc-donor 2/2] RUN arch=amd64     && case $arch in         amd64) rarch=x86_64 ;;         arm64) rarch=aarch64 ;;     esac     && ln -s "${rarch}-linux-gnu" /lib/linux-gnu
#8 DONE 0.4s

#9 [stage-1 2/9] COPY --from=glibc-donor /lib/linux-gnu/libc.so.6 /lib/linux-gnu/libdl.so.2 /lib/linux-gnu/libm.so.6 /lib/linux-gnu/libpthread.so.0 /lib/linux-gnu/librt.so.1 /lib/linux-gnu/libnss_dns.so.2 /lib/linux-gnu/libnss_files.so.2 /lib/linux-gnu/libresolv.so.2 /lib/linux-gnu/ld-2.31.so /lib/
#9 DONE 0.1s

#10 [stage-1 3/9] COPY --from=glibc-donor /etc/nsswitch.conf /etc/
#10 DONE 0.0s

#11 [stage-1 4/9] COPY docker_related_config.xml /etc/clickhouse-server/config.d/
#11 DONE 0.0s

#12 [stage-1 5/9] COPY entrypoint.sh /entrypoint.sh
#12 DONE 0.0s

#13 [stage-1 6/9] RUN arch=amd64     && case $arch in         amd64) mkdir -p /lib64 && ln -sf /lib/ld-2.31.so /lib64/ld-linux-x86-64.so.2 ;;         arm64) ln -sf /lib/ld-2.31.so /lib/ld-linux-aarch64.so.1 ;;     esac
#13 DONE 0.4s

#14 [stage-1 7/9] RUN addgroup -S -g "101" clickhouse &&     adduser -S -h "/var/lib/clickhouse" -s /bin/bash -G clickhouse -g "ClickHouse server" -u "101" clickhouse
#14 DONE 0.5s

#15 [stage-1 8/9] RUN arch=amd64     && cd /tmp     && if [ -n "https://s3.amazonaws.com/clickhouse-builds/PRs/68900/f9dc1e8e1aceeef4c41f7dace24c8fbb37c2baec/package_release/clickhouse-client-24.9.1.1511-amd64.tgz https://s3.amazonaws.com/clickhouse-builds/PRs/68900/f9dc1e8e1aceeef4c41f7dace24c8fbb37c2baec/package_release/clickhouse-client-24.9.1.1511-amd64.tgz.sha512 https://s3.amazonaws.com/clickhouse-builds/PRs/68900/f9dc1e8e1aceeef4c41f7dace24c8fbb37c2baec/package_release/clickhouse-common-static-24.9.1.1511-amd64.tgz https://s3.amazonaws.com/clickhouse-builds/PRs/68900/f9dc1e8e1aceeef4c41f7dace24c8fbb37c2baec/package_release/clickhouse-common-static-24.9.1.1511-amd64.tgz.sha512 https://s3.amazonaws.com/clickhouse-builds/PRs/68900/f9dc1e8e1aceeef4c41f7dace24c8fbb37c2baec/package_release/clickhouse-server-24.9.1.1511-amd64.tgz https://s3.amazonaws.com/clickhouse-builds/PRs/68900/f9dc1e8e1aceeef4c41f7dace24c8fbb37c2baec/package_release/clickhouse-server-24.9.1.1511-amd64.tgz.sha512" ]; then         echo "installing from provided urls with tgz packages: https://s3.amazonaws.com/clickhouse-builds/PRs/68900/f9dc1e8e1aceeef4c41f7dace24c8fbb37c2baec/package_release/clickhouse-client-24.9.1.1511-amd64.tgz https://s3.amazonaws.com/clickhouse-builds/PRs/68900/f9dc1e8e1aceeef4c41f7dace24c8fbb37c2baec/package_release/clickhouse-client-24.9.1.1511-amd64.tgz.sha512 https://s3.amazonaws.com/clickhouse-builds/PRs/68900/f9dc1e8e1aceeef4c41f7dace24c8fbb37c2baec/package_release/clickhouse-common-static-24.9.1.1511-amd64.tgz https://s3.amazonaws.com/clickhouse-builds/PRs/68900/f9dc1e8e1aceeef4c41f7dace24c8fbb37c2baec/package_release/clickhouse-common-static-24.9.1.1511-amd64.tgz.sha512 https://s3.amazonaws.com/clickhouse-builds/PRs/68900/f9dc1e8e1aceeef4c41f7dace24c8fbb37c2baec/package_release/clickhouse-server-24.9.1.1511-amd64.tgz https://s3.amazonaws.com/clickhouse-builds/PRs/68900/f9dc1e8e1aceeef4c41f7dace24c8fbb37c2baec/package_release/clickhouse-server-24.9.1.1511-amd64.tgz.sha512"         && for url in https://s3.amazonaws.com/clickhouse-builds/PRs/68900/f9dc1e8e1aceeef4c41f7dace24c8fbb37c2baec/package_release/clickhouse-client-24.9.1.1511-amd64.tgz https://s3.amazonaws.com/clickhouse-builds/PRs/68900/f9dc1e8e1aceeef4c41f7dace24c8fbb37c2baec/package_release/clickhouse-client-24.9.1.1511-amd64.tgz.sha512 https://s3.amazonaws.com/clickhouse-builds/PRs/68900/f9dc1e8e1aceeef4c41f7dace24c8fbb37c2baec/package_release/clickhouse-common-static-24.9.1.1511-amd64.tgz https://s3.amazonaws.com/clickhouse-builds/PRs/68900/f9dc1e8e1aceeef4c41f7dace24c8fbb37c2baec/package_release/clickhouse-common-static-24.9.1.1511-amd64.tgz.sha512 https://s3.amazonaws.com/clickhouse-builds/PRs/68900/f9dc1e8e1aceeef4c41f7dace24c8fbb37c2baec/package_release/clickhouse-server-24.9.1.1511-amd64.tgz https://s3.amazonaws.com/clickhouse-builds/PRs/68900/f9dc1e8e1aceeef4c41f7dace24c8fbb37c2baec/package_release/clickhouse-server-24.9.1.1511-amd64.tgz.sha512; do             echo "Get ${url}"             && wget -c -q "$url"         ; done     else         for package in clickhouse-client clickhouse-server clickhouse-common-static; do             echo "Get https://packages.clickhouse.com/tgz/stable/${package}-24.9.1.1-${arch}.tgz"             && wget -c -q "https://packages.clickhouse.com/tgz/stable/${package}-24.9.1.1-${arch}.tgz"             && wget -c -q "https://packages.clickhouse.com/tgz/stable/${package}-24.9.1.1-${arch}.tgz.sha512"         ; done     fi     && cat *.tgz.sha512 | sed 's:/output/:/tmp/:' | sha512sum -c     && for file in *.tgz; do         if [ -f "$file" ]; then             echo "Unpacking $file";             tar xvzf "$file" --strip-components=1 -C /;         fi     ; done     && rm /tmp/*.tgz /install -r     && chmod +x /entrypoint.sh     && apk add --no-cache bash tzdata     && cp /usr/share/zoneinfo/UTC /etc/localtime     && echo "UTC" > /etc/timezone
#15 0.532 installing from provided urls with tgz packages: https://s3.amazonaws.com/clickhouse-builds/PRs/68900/f9dc1e8e1aceeef4c41f7dace24c8fbb37c2baec/package_release/clickhouse-client-24.9.1.1511-amd64.tgz https://s3.amazonaws.com/clickhouse-builds/PRs/68900/f9dc1e8e1aceeef4c41f7dace24c8fbb37c2baec/package_release/clickhouse-client-24.9.1.1511-amd64.tgz.sha512 https://s3.amazonaws.com/clickhouse-builds/PRs/68900/f9dc1e8e1aceeef4c41f7dace24c8fbb37c2baec/package_release/clickhouse-common-static-24.9.1.1511-amd64.tgz https://s3.amazonaws.com/clickhouse-builds/PRs/68900/f9dc1e8e1aceeef4c41f7dace24c8fbb37c2baec/package_release/clickhouse-common-static-24.9.1.1511-amd64.tgz.sha512 https://s3.amazonaws.com/clickhouse-builds/PRs/68900/f9dc1e8e1aceeef4c41f7dace24c8fbb37c2baec/package_release/clickhouse-server-24.9.1.1511-amd64.tgz https://s3.amazonaws.com/clickhouse-builds/PRs/68900/f9dc1e8e1aceeef4c41f7dace24c8fbb37c2baec/package_release/clickhouse-server-24.9.1.1511-amd64.tgz.sha512
#15 0.532 Get https://s3.amazonaws.com/clickhouse-builds/PRs/68900/f9dc1e8e1aceeef4c41f7dace24c8fbb37c2baec/package_release/clickhouse-client-24.9.1.1511-amd64.tgz
#15 1.669 Get https://s3.amazonaws.com/clickhouse-builds/PRs/68900/f9dc1e8e1aceeef4c41f7dace24c8fbb37c2baec/package_release/clickhouse-client-24.9.1.1511-amd64.tgz.sha512
#15 2.354 Get https://s3.amazonaws.com/clickhouse-builds/PRs/68900/f9dc1e8e1aceeef4c41f7dace24c8fbb37c2baec/package_release/clickhouse-common-static-24.9.1.1511-amd64.tgz
#15 37.90 Get https://s3.amazonaws.com/clickhouse-builds/PRs/68900/f9dc1e8e1aceeef4c41f7dace24c8fbb37c2baec/package_release/clickhouse-common-static-24.9.1.1511-amd64.tgz.sha512
#15 38.64 Get https://s3.amazonaws.com/clickhouse-builds/PRs/68900/f9dc1e8e1aceeef4c41f7dace24c8fbb37c2baec/package_release/clickhouse-server-24.9.1.1511-amd64.tgz
#15 39.83 Get https://s3.amazonaws.com/clickhouse-builds/PRs/68900/f9dc1e8e1aceeef4c41f7dace24c8fbb37c2baec/package_release/clickhouse-server-24.9.1.1511-amd64.tgz.sha512
#15 40.65 clickhouse-client-24.9.1.1511-amd64.tgz: OK
#15 41.37 clickhouse-common-static-24.9.1.1511-amd64.tgz: OK
#15 41.37 clickhouse-server-24.9.1.1511-amd64.tgz: OK
#15 41.37 Unpacking clickhouse-client-24.9.1.1511-amd64.tgz
#15 41.37 clickhouse-client-24.9.1.1511/
#15 41.37 clickhouse-client-24.9.1.1511/install/
#15 41.37 clickhouse-client-24.9.1.1511/install/doinst.sh
#15 41.37 clickhouse-client-24.9.1.1511/usr/
#15 41.37 clickhouse-client-24.9.1.1511/usr/share/
#15 41.37 clickhouse-client-24.9.1.1511/usr/share/doc/
#15 41.37 clickhouse-client-24.9.1.1511/usr/share/doc/clickhouse-client/
#15 41.37 clickhouse-client-24.9.1.1511/usr/share/doc/clickhouse-client/AUTHORS
#15 41.37 clickhouse-client-24.9.1.1511/usr/share/doc/clickhouse-client/README.md
#15 41.37 clickhouse-client-24.9.1.1511/usr/share/doc/clickhouse-client/CHANGELOG.md
#15 41.37 clickhouse-client-24.9.1.1511/usr/share/doc/clickhouse-client/LICENSE
#15 41.37 clickhouse-client-24.9.1.1511/usr/bin/
#15 41.37 clickhouse-client-24.9.1.1511/usr/bin/ch
#15 41.37 clickhouse-client-24.9.1.1511/usr/bin/clickhouse-local
#15 41.37 clickhouse-client-24.9.1.1511/usr/bin/clickhouse-compressor
#15 41.37 clickhouse-client-24.9.1.1511/usr/bin/chc
#15 41.37 clickhouse-client-24.9.1.1511/usr/bin/clickhouse-obfuscator
#15 41.37 clickhouse-client-24.9.1.1511/usr/bin/chl
#15 41.37 clickhouse-client-24.9.1.1511/usr/bin/clickhouse-benchmark
#15 41.37 clickhouse-client-24.9.1.1511/usr/bin/clickhouse-format
#15 41.37 clickhouse-client-24.9.1.1511/usr/bin/clickhouse-client
#15 41.38 clickhouse-client-24.9.1.1511/etc/
#15 41.38 clickhouse-client-24.9.1.1511/etc/clickhouse-client/
#15 41.38 clickhouse-client-24.9.1.1511/etc/clickhouse-client/config.xml
#15 41.38 Unpacking clickhouse-common-static-24.9.1.1511-amd64.tgz
#15 41.38 clickhouse-common-static-24.9.1.1511/
#15 41.38 clickhouse-common-static-24.9.1.1511/install/
#15 41.38 clickhouse-common-static-24.9.1.1511/install/doinst.sh
#15 41.38 clickhouse-common-static-24.9.1.1511/usr/
#15 41.38 clickhouse-common-static-24.9.1.1511/usr/share/
#15 41.38 clickhouse-common-static-24.9.1.1511/usr/share/clickhouse/
#15 41.38 clickhouse-common-static-24.9.1.1511/usr/share/clickhouse/protos/
#15 41.38 clickhouse-common-static-24.9.1.1511/usr/share/clickhouse/protos/google/
#15 41.38 clickhouse-common-static-24.9.1.1511/usr/share/clickhouse/protos/google/protobuf/
#15 41.38 clickhouse-common-static-24.9.1.1511/usr/share/clickhouse/protos/google/protobuf/api.proto
#15 41.38 clickhouse-common-static-24.9.1.1511/usr/share/clickhouse/protos/google/protobuf/any.proto
#15 41.38 clickhouse-common-static-24.9.1.1511/usr/share/clickhouse/protos/google/protobuf/source_context.proto
#15 41.38 clickhouse-common-static-24.9.1.1511/usr/share/clickhouse/protos/google/protobuf/descriptor.proto
#15 41.38 clickhouse-common-static-24.9.1.1511/usr/share/clickhouse/protos/google/protobuf/wrappers.proto
#15 41.38 clickhouse-common-static-24.9.1.1511/usr/share/clickhouse/protos/google/protobuf/type.proto
#15 41.38 clickhouse-common-static-24.9.1.1511/usr/share/clickhouse/protos/google/protobuf/timestamp.proto
#15 41.38 clickhouse-common-static-24.9.1.1511/usr/share/clickhouse/protos/google/protobuf/empty.proto
#15 41.38 clickhouse-common-static-24.9.1.1511/usr/share/clickhouse/protos/google/protobuf/field_mask.proto
#15 41.38 clickhouse-common-static-24.9.1.1511/usr/share/clickhouse/protos/google/protobuf/struct.proto
#15 41.38 clickhouse-common-static-24.9.1.1511/usr/share/clickhouse/protos/google/protobuf/duration.proto
#15 41.38 clickhouse-common-static-24.9.1.1511/usr/share/doc/
#15 41.38 clickhouse-common-static-24.9.1.1511/usr/share/doc/clickhouse-common-static/
#15 41.38 clickhouse-common-static-24.9.1.1511/usr/share/doc/clickhouse-common-static/AUTHORS
#15 41.38 clickhouse-common-static-24.9.1.1511/usr/share/doc/clickhouse-common-static/README.md
#15 41.38 clickhouse-common-static-24.9.1.1511/usr/share/doc/clickhouse-common-static/CHANGELOG.md
#15 41.38 clickhouse-common-static-24.9.1.1511/usr/share/doc/clickhouse-common-static/LICENSE
#15 41.38 clickhouse-common-static-24.9.1.1511/usr/share/bash-completion/
#15 41.38 clickhouse-common-static-24.9.1.1511/usr/share/bash-completion/completions/
#15 47.03 clickhouse-common-static-24.9.1.1511/usr/share/bash-completion/completions/clickhouse-local
#15 47.03 clickhouse-common-static-24.9.1.1511/usr/share/bash-completion/completions/clickhouse
#15 47.03 clickhouse-common-static-24.9.1.1511/usr/share/bash-completion/completions/clickhouse-bootstrap
#15 47.03 clickhouse-common-static-24.9.1.1511/usr/share/bash-completion/completions/clickhouse-benchmark
#15 47.03 clickhouse-common-static-24.9.1.1511/usr/share/bash-completion/completions/clickhouse-client
#15 47.03 clickhouse-common-static-24.9.1.1511/usr/bin/
#15 47.03 clickhouse-common-static-24.9.1.1511/usr/bin/clickhouse
#15 47.03 clickhouse-common-static-24.9.1.1511/usr/bin/clickhouse-extract-from-config
#15 47.03 Unpacking clickhouse-server-24.9.1.1511-amd64.tgz
#15 47.04 clickhouse-server-24.9.1.1511/
#15 47.04 clickhouse-server-24.9.1.1511/install/
#15 47.04 clickhouse-server-24.9.1.1511/install/doinst.sh
#15 47.04 clickhouse-server-24.9.1.1511/usr/
#15 47.04 clickhouse-server-24.9.1.1511/usr/share/
#15 47.04 clickhouse-server-24.9.1.1511/usr/share/doc/
#15 47.04 clickhouse-server-24.9.1.1511/usr/share/doc/clickhouse-server/
#15 47.04 clickhouse-server-24.9.1.1511/usr/share/doc/clickhouse-server/AUTHORS
#15 47.04 clickhouse-server-24.9.1.1511/usr/share/doc/clickhouse-server/README.md
#15 47.04 clickhouse-server-24.9.1.1511/usr/share/doc/clickhouse-server/CHANGELOG.md
#15 47.04 clickhouse-server-24.9.1.1511/usr/share/doc/clickhouse-server/LICENSE
#15 47.04 clickhouse-server-24.9.1.1511/usr/bin/
#15 47.04 clickhouse-server-24.9.1.1511/usr/bin/clickhouse-keeper
#15 47.04 clickhouse-server-24.9.1.1511/usr/bin/clickhouse-server
#15 47.04 clickhouse-server-24.9.1.1511/usr/bin/clickhouse-keeper-client
#15 47.04 clickhouse-server-24.9.1.1511/usr/bin/clickhouse-keeper-converter
#15 47.04 clickhouse-server-24.9.1.1511/etc/
#15 47.04 clickhouse-server-24.9.1.1511/etc/init.d/
#15 47.04 clickhouse-server-24.9.1.1511/etc/init.d/clickhouse-server
#15 47.04 clickhouse-server-24.9.1.1511/etc/clickhouse-keeper/
#15 47.04 clickhouse-server-24.9.1.1511/etc/clickhouse-keeper/keeper_config.xml
#15 47.04 clickhouse-server-24.9.1.1511/etc/clickhouse-server/
#15 47.04 clickhouse-server-24.9.1.1511/etc/clickhouse-server/config.xml
#15 47.04 clickhouse-server-24.9.1.1511/etc/clickhouse-server/users.xml
#15 47.04 clickhouse-server-24.9.1.1511/lib/
#15 47.04 clickhouse-server-24.9.1.1511/lib/systemd/
#15 47.04 clickhouse-server-24.9.1.1511/lib/systemd/system/
#15 47.04 clickhouse-server-24.9.1.1511/lib/systemd/system/clickhouse-server.service
#15 47.04 clickhouse-server-24.9.1.1511/lib/systemd/system/clickhouse-keeper.service
#15 47.09 fetch https://dl-cdn.alpinelinux.org/alpine/v3.17/main/x86_64/APKINDEX.tar.gz
#15 47.65 fetch https://dl-cdn.alpinelinux.org/alpine/v3.17/community/x86_64/APKINDEX.tar.gz
#15 48.01 (1/5) Installing ncurses-terminfo-base (6.3_p20221119-r1)
#15 48.05 (2/5) Installing ncurses-libs (6.3_p20221119-r1)
#15 48.09 (3/5) Installing readline (8.2.0-r0)
#15 48.13 (4/5) Installing bash (5.2.15-r0)
#15 48.20 Executing bash-5.2.15-r0.post-install
#15 48.20 (5/5) Installing tzdata (2024a-r0)
#15 48.39 Executing busybox-1.35.0-r29.trigger
#15 48.40 OK: 12 MiB in 20 packages
#15 DONE 48.7s

#16 [stage-1 9/9] RUN mkdir -p       "/var/lib/clickhouse"       "/var/log/clickhouse-server"       "/etc/clickhouse-client"       "/etc/clickhouse-server/config.d"       "/etc/clickhouse-server/users.d"       /docker-entrypoint-initdb.d     && chown clickhouse:clickhouse "/var/lib/clickhouse"     && chown root:clickhouse "/var/log/clickhouse-server"     && chmod ugo+Xrw -R "/var/lib/clickhouse" "/var/log/clickhouse-server" "/etc/clickhouse-client" "/etc/clickhouse-server"
#16 DONE 0.5s

#17 exporting to image
#17 exporting layers
#17 exporting layers 2.6s done
#17 writing image sha256:6fdeebeda049bfa996f3831c27767e2b880ea39bca6e424a21fe844a082a5102 done
#17 naming to docker.io/clickhouse/clickhouse-server:head-alpine-amd64 done
#17 DONE 2.6s
mfilimonov@laptop-5591:~/workspace/ClickHouse/master$ docker run -d --name ch docker.io/clickhouse/clickhouse-server:head-alpine-amd64 
ee286b2469cbd013367818394958531b1f628dd856be1210d860ba5943476c0b
mfilimonov@laptop-5591:~/workspace/ClickHouse/master$ docker exec -it ch bash 
ee286b2469cb:/# clickhouse-client 
ClickHouse client version 24.9.1.1511.
Connecting to localhost:9000 as user default.
Connected to ClickHouse server version 24.9.1.

Warnings:
 * Delay accounting is not enabled, OSIOWaitMicroseconds will not be gathered. You can enable it using `echo 1 > /proc/sys/kernel/task_delayacct` or by using sysctl.

ee286b2469cb :) exit;
```

**Pull request merged**
