### PR TITLE
Fix progress over tcp

### PR DESCRIPTION
**Pull request by azat**
Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix progress over tcp, by send progress after final update (like logs)

*P.S. commit message contains stacktrace of the final update, w/o consequent send*

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]
Ok.

**Comment by alexey-milovidov** [comment]
I have labeled it as "improvement" because I don't see how the previous behaviour can be considered a bug. It is visible only on tools that use the native protocol and receive progress and use the progress not only for visualization purposes (otherwise it's indistinguishable).

**Comment by alexey-milovidov** [comment]
Tests fail: `Unexpected packet from server (expected Exception, EndOfStream or Log, got Progress)`

**Review by alexey-milovidov — CHANGES_REQUESTED** [review]
(or just close)

**Comment by alexey-milovidov** [comment]
Now Ok.

**Comment by alexey-milovidov** [comment]
But what exactly does it fix? What scenario?

**Comment by azat** [comment]
Progress metrics after query execution (they were incomplete, i.e. number of written/read rows/bytes was less then processed)

**Pull request merged**
