### PR TITLE
S3 parallel request to listing files

### LINKED ISSUE #65572: Parallelize listing of files on S3
Listing operation in S3 is extremely slow: it typically takes 0.3 seconds and gives only 1000 items per request. That's why listing 10,000,000 items requires around one hour.

But the request accepts the starting key, and we can speculatively do many requests in parallel. We only need to guess from where to start.

To do it, we can make a first request and find the distance between the 1st and 1000th keys. Then, take slightly less than this distance (for example, 0.9) and add it several times. Make many parallel requests from those starting points. Check if the results of these requests intersect with the previous sets, and if not, make other requests to fill possible gaps between these results.

The distance between strings can be calculated if we represent them as fractions in [0..1] in base-64, where the digits are:

```
all below
0-9
A-Z
a-z
all above
```

### PR DESCRIPTION
**Pull request by scanhex12**
### Changelog category (leave one):
- Performance Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Speed-up listing files in S3. This closes #65572.

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by scanhex12** [comment]
Hi, I wrote the solution to the problem as it was written in the condition, but I ran into several problems while solving the problem
1) I executed one query (let it take time T) and n queries in the thread pool with the number of workers >n. And in total, in the second case, the query time was much longer than T, so I think there is a lock somewhere inside the client (but I did not read the internal code)
2) I noticed that in order for the algorithm to work well from the condition, it is necessary that when converting files to numbers, these numbers are distributed approximately evenly. However, this is not the case at all, because there are characters in the alphabet that are not in the file names (and they cannot be removed), so there are a lot of segments in which there are no files, but we set queries for them and it takes a lot of time

Because of these problems, I managed to speed up the solution only by about 2 times

I also noticed that we cannot initially know exactly how many segments we want to check in parallel (otherwise, queries will not become completely parallel there), so this is a hyperparameter that has to be iterated from query to query, as well as the constant 0.9 (which is not optimal for all queries)

please help me decide what to do with these problems =)

**Comment by CheSema** [comment]
CI is not running due to incomplete description.

**Comment by CheSema** [comment]
Please, fix the PR's description, @scanhex12. It needs to run the CI.

**Comment by robot-clickhouse-ci-1** [comment]
*This is an automated comment for commit 78ab060f433bf133e795edc84fba88960a824b86 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/66504/78ab060f433bf133e795edc84fba88960a824b86/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/67363/4488d65fe91b58f72fec7536a8f8314aa3deec38/docs_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Comment by alexey-milovidov** [comment]
I tried to finish this pull request, but found several problems:
1. It assumes a certain set of characters in file names. It was difficult to fix.
2. The speed-up in my tests was not as high as I expected.

**Pull request closed without merging**
