### PR TITLE
Tiny cleanup

### PR DESCRIPTION
**Pull request by azat**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
Please provide some explanations here...

**Comment by azat** [comment]
>Please provide some explanations here...

Where exactly? This is just outdated code.

**Comment by azat** [comment]
>[Stateless tests (debug, actions) [3/3] — fail: 1, passed: 1328, skipped: 8](https://s3.amazonaws.com/clickhouse-test-reports/36799/7a092e2a8c7b92d3f8037aeb4cae7056cd3c4fd4/stateless_tests__debug__actions__[3/3].html)

- `00693_max_block_size_system_tables_columns`  - #36820

```
2022.04.29 12:33:40.092467 [ 59636 ] {1db08e36-8f39-4681-8013-fc0573f4dc92} <Debug> executeQuery: (from [::1]:60566) (comment: 00693_max_block_size_system_tables_columns.sql) SELECT (SELECT count() FROM system.columns SETTINGS max_block_size = 100) = (SELECT count() FROM system.columns SETTINGS max_block_size = 1000);
...
2022.04.29 12:33:40.397528 [ 486 ] {} <Debug> SystemLog (system.asynchronous_metric_log): Existing table system.asynchronous_metric_log for system log has obsolete or different structure. Renaming it to asynchronous_metric_log_352.
Old: CREATE TABLE system.asynchronous_metric_log (`event_date` Date CODEC(Delta(2), ZSTD(1)), `event_time` DateTime CODEC(Delta(4), ZSTD(1)), `metric` LowCardinality(String) CODEC(ZSTD(1)), `value` Float64 CODEC(Gorilla, ZSTD(3))) ENGINE = MergeTree PARTITION BY toYYYYMM(event_date) ORDER BY (metric, event_date, event_time) SETTINGS index_granularity = 8192
New: CREATE TABLE system.asynchronous_metric_log (`event_date` Date CODEC(Delta(2), ZSTD), `event_time` DateTime CODEC(Delta(4), ZSTD), `metric` LowCardinality(String) CODEC(ZSTD), `value` Float64 CODEC(Gorilla, ZSTD(3))) ENGINE = MergeTree PARTITION BY toYYYYMM(event_date) ORDER BY (metric, event_date, event_time) SETTINGS index_granularity = 8192
...
2022.04.29 12:33:40.562997 [ 59636 ] {1db08e36-8f39-4681-8013-fc0573f4dc92} <Information> executeQuery: Read 6117 rows, 5.97 KiB in 0.470289616 sec., 13006 rows/sec., 12.70 KiB/sec.
```

**Comment by alexey-milovidov** [comment]
Why `reserve` in Squashing transform appeared to be outdated?

**Comment by azat** [comment]
It doesn't used anywhere

**Comment by alexey-milovidov** [comment]
What was the motivation, reserve was added initially?
Maybe it's a performance optimization that was lost?

**Comment by azat** [comment]
It has been added in #7122, without any explanation, so it is hard to say.
And setting for it had been removed in #8637 (a9d0d7472009d7517325a0ac172c567d06e966b7) with a comment `remove bad MergeJoin optimization`

**Pull request merged**
