### PR TITLE
ISSUES-4006 Support MySQL Binlog replication and parsing

### PR DESCRIPTION
**Pull request by bohutang**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- New Feature

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
#4006

Detailed description / Documentation draft:
Merged into  https://github.com/ClickHouse/ClickHouse/pull/10851 by @zhang2014 

The features implemented in this patch:
Binlog Network Stream:
- [x] Client handshake
- [x] Client ping
- [x] Client register slave
- [x] Client binlog event dump(Position and GTID)
- [x] Client receive binlog events over the network stream

Parsing Binlog Events to ClickHouse type:
- [x] QueryEvent
     - [x] DDL
     - [x] XA START/END/PREPARE/COMMIT, not ROLLBACK
- [x] RowsEvent
     - [x] MYSQL_TYPE_NULL -> Null
     - [x] MYSQL_TYPE_TINY -> UInt8
     - [x] MYSQL_TYPE_SHORT -> UInt16
     - [x] MYSQL_TYPE_INT24 -> UInt32
     - [x] MYSQL_TYPE_LONG -> UInt32
     - [x] MYSQL_TYPE_LONGLONG -> UInt64
     - [x] MYSQL_TYPE_FLOAT -> Float64
     - [x] MYSQL_TYPE_DOUBLE -> Float64
     - [x] MYSQL_TYPE_TIMESTAMP -> UInt32, Unix Timestamp 
     - [x] MYSQL_TYPE_TIME -> String, format("%02d:%02d:%02d")
     - [x] MYSQL_TYPE_DATE -> String, format("%04d-%02d-%02d")
     - [x] MYSQL_TYPE_YEAR -> String, format("%04d")
     - [x] MYSQL_TYPE_TIME2 -> String, format("%02d:%02d:%02d") or format("%02d:%02d:%02d.%06d") with fractional
     - [x] MYSQL_TYPE_TIMESTAMP2 -> UInt64, Unix Timestamp
     - [x] MYSQL_TYPE_DATETIME2 -> UInt64, Unix Timestamp
     - [x] MYSQL_TYPE_ENUM -> Int32
     - [x] MYSQL_TYPE_BIT -> UInt64
     - [x] MYSQL_TYPE_SET -> UInt64
     - [x] MYSQL_TYPE_NEWDECIMAL -> String
     - [x] MYSQL_TYPE_VARCHAR -> String
     - [x] MYSQL_TYPE_VAR_STRING -> String
     - [x] MYSQL_TYPE_STRING -> String
     - [x] MYSQL_TYPE_GEOMETRY -> String
     - [x] MYSQL_TYPE_BLOB -> String
     - [x] MYSQL_TYPE_JSON -> String, JSONB(JSON binary format)

Test plan:
- [x] tests/mysql_protocol.cpp
- [x] fuzz tests and outputs: https://gist.github.com/BohuTANG/267379680469d3a896a9681f6cf36e0d

### CODE REVIEW

**Comment by BohuTANG** [comment]
@alexey-milovidov @blinkov 

This patch is ready for review.
Can you(or get someone) do a review?
Thanks.

**Comment by vkingnew** [comment]
this function is great，when release it as a stable version?

**Comment by alexey-milovidov** [comment]
@vkingnew First Draft should be converted to "Ready for review" by @BohuTANG, then it will be assigned for review, then it will be reviewed and merged and will be available in next release, that happens to be every two-three weeks.

**Comment by BohuTANG** [comment]
@vkingnew @alexey-milovidov 
Hi, this patch is already contained in another patch with a few changes, and it's ready for review:
https://github.com/ClickHouse/ClickHouse/pull/10851

**Comment by alexey-milovidov** [comment]
Ok. Alexander @tavplubix is reviewing it. He was in vacation for two weeks but he is back this Monday.

**Comment by vkingnew** [comment]
@alexey-milovidov  As normal process，release it nedd 3 stage,every stage  need  two-three weeks.The earliest stable release version will be October? Desire it

**Comment by alexey-milovidov** [comment]
Right now we are preparing release 20.6 that is already prestable.
Release 20.7 is expected to be in middle or late August.

**Comment by BohuTANG** [comment]
Added a performance test comment: https://github.com/ClickHouse/ClickHouse/pull/10851#issuecomment-667932658

In short:
The MaterializeMySQL engine is very fast, almost in real time!

**Comment by tavplubix** [comment]
Merged in #10851

**Pull request closed without merging**
