### PR TITLE
Add column  distributed_depth for system.query_log and system.processes

### PR DESCRIPTION
**Pull request by taiyang-li**
Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Sometimes it is not enough for us to distinguish queries hierachy only by is_initial_query in system.query_log and system.processes.  So distributed_depth is needed.

### CODE REVIEW

**Review by CurtizJ — APPROVED** [review]
Please correct test `02117_show_create_table_system`. Other tests failed because of randomization of settings, I guess.

**Comment by taiyang-li** [comment]
> Please correct test `02117_show_create_table_system`. Other tests failed because of randomization of settings, I guess.

done.

**Review by CurtizJ — COMMENTED** [review]
I didn't notice it before, but `appendClientInfo` is also used in `system.query_thread_log` table, but you didn't add a new column to it, so columns in `query_thread_log` are shifted now and tests fail because of that.

**Comment by taiyang-li** [comment]
> 

I'll fix it.

**Review by CurtizJ — APPROVED** [review]

**Pull request merged**
