### PR TITLE
[RFC] Distributed over distributed (v2)

### PR DESCRIPTION
**Pull request by azat**
Fixes: #8640 

Changelog category (leave one):
- New Feature

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Add ability to query Distributed over Distributed (w/o `distributed_group_by_no_merge`)

*P.S. Not sure that it is that easy (but looks like everything worksm and performance should not be worse since before an exception had been thrown anyway), hence RFC*

*P.P.S I asked the author of the #8640 (@Enmk) and he wasn't against I'm taking a look*

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
Do I understand correctly that it forwards data when WithMergeableState -> WithMergeableState is requested and possibly, applies additional pre-sorting/distrinct/limit (but for what purpose?)

**Comment by alexey-milovidov** [comment]
We can also test queries with GLOBAL IN/JOIN but don't worry - even if they don't work in Distributed over Distributed, it's still acceptable.

**Comment by azat** [comment]
>Do I understand correctly that it forwards data when WithMergeableState -> WithMergeableState is requested and possibly, applies additional pre-sorting/distrinct/limit (but for what purpose?)

AFAIU It does not pre-sorting it sorts results that had been received so far from the shards, since otherwise this step will be skipped and only the final `WithMergeableState -> Complete` will sort, and not complete sort but only merge sorted already results.

**Comment by azat** [comment]
>We can also test queries with GLOBAL IN/JOIN

JOIN works, but GLOBAL IN does not works even now, fails with LOGACAL_ERROR `Table expression is undefined, Method: ExpressionAnalyzer::interpretSubquery.`, which then will abort in debug build

**Comment by azat** [comment]
Oh, I see, looks like the failed tests are failed on upstream/master too

**Comment by alexey-milovidov** [comment]
> AFAIU It does not pre-sorting it sorts results that had been received so far from the shards, since otherwise this step will be skipped and only the final WithMergeableState -> Complete will sort, and not complete sort but only merge sorted already results.

If we have three servers:

A (local) -> B (distributed, intermediate) -> C (distributed, final)

I expect that it will work this way:
A will do pre-sorting and pre-limit.
B will do nothing except forwarding blocks.
C will do final sorting and limit.

In the same way as without B.

**Comment by alexey-milovidov** [comment]
PS. We can do re-merging intermediate data on intermediate servers but it's out of scope of this task.

**Comment by alexey-milovidov** [comment]
> B will do nothing except forwarding blocks.

As I understand, the main challenge is that it cannot just concatenate blocks from different servers to a single stream... because it will interfere with merge sorting. Do I understand correctly that this is the reason why you are doing additional intermediate sorting?

**Comment by alexey-milovidov** [comment]
We also should pay attention to two level GROUP BY and MergingAggregatedMemoryEfficient.
In this mode, every block has bucket_num assigned and data is merged per buckets.

**Comment by azat** [comment]
>We also should pay attention to two level GROUP BY and MergingAggregatedMemoryEfficient.
In this mode, every block has bucket_num assigned and data is merged per buckets.

Looks ok (test updated)

**Comment by azat** [comment]
> As I understand, the main challenge is that it cannot just concatenate blocks from different servers to a single stream... because it will interfere with merge sorting. Do I understand correctly that this is the reason why you are doing additional intermediate sorting?

Yes, the problem is that intermediate server need to sort the data, otherwise final server will receive unsorted data and it's merged sort will not work.

**Comment by azat** [comment]
>Functional stateless tests (release, streams) — fail: 38, passed: 74
>Functional stateless tests (thread) — fail: 20, passed: 344, skipped: 5

No errors in clickhouse-server.log, OOM/reboot?
(Other tests fails in upstream/master too and performance looks unrelated)

**Comment by azat** [comment]
>but GLOBAL IN does not works even now (i.e. distributed_group_by_no_merge), fails with LOGACAL_ERROR Table expression is undefined, Method: ExpressionAnalyzer::interpretSubquery., which then will abort in debug build

Added a test into `bugs`

**Comment by alexey-milovidov** [comment]
Ok. But it also means that memory-efficient aggregation won't work without remerging.
You can test the case when servers send data by buckets...

**Comment by azat** [comment]
>memory-efficient aggregation won't work without remerging.

Nice catch! Fixed and covered!

**Comment by azat** [comment]
Test failures looks unrelated.

> test_settings_constraints
> 01098_temporary_and_external_tables

**Comment by azat** [comment]
And seems that performance tests is unstable too (since it shows `Performance 3 faster, 35 unstable, 5 errors` in upstream/master), and plus this PR should not affect them, since it does not changes existing code paths.

**Comment by alexey-milovidov** [comment]
I'm only afraid that some settings are ineffective when specified in SETTINGS clause (when they are applied before the SETTINGS clause being interpreted). Did you check that two level memory-efficient aggregation is active?

**Comment by alexey-milovidov** [comment]
Yes, it is in effect.

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
Now it looks like all cases are covered :)

**Comment by alexey-milovidov** [comment]
@azat Maybe also grab integration tests from https://github.com/ClickHouse/ClickHouse/pull/8640/files just in case?

**Comment by azat** [comment]
>@azat Maybe also grab integration tests from https://github.com/ClickHouse/ClickHouse/pull/8640/files just in case?

Sure, why not, will cherry pick it.

>Now it looks like all cases are covered :)

Just found one issue left (the case when `StorageDistributed::getQueryProcessingStage()` returns Complete when there is only one shard to query), will get back soon

**Pull request merged**
