### PR TITLE
Significant improvement of rust caching

### PR DESCRIPTION
**Pull request by Felixoid**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Follow-up for #52395. Cargo packages are now stored in S3 as a single archive per `rust/Cargo.lock` version. As well now rust is building with using of sccache.

### CODE REVIEW

**Comment by robot-clickhouse-ci-2** [comment]
This is an automated comment for commit d5246ce15c14b8a3d06b282a2194b7405fcb0c1f with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/52865/d5246ce15c14b8a3d06b282a2194b7405fcb0c1f/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Comment by Felixoid** [comment]
Since there aren't objections, I am going to merge it after successful builds.

**Comment by Felixoid** [comment]
The plan here is to implement the same scheme as it was for ccache, details are here https://github.com/ClickHouse/ClickHouse/pull/53060#issuecomment-1669171243

**Comment by Felixoid** [comment]
The implemented solution is much simpler than the previous one.

The cargo cache is now stored in S3 in a single instance, and should be downloaded and uploaded much faster than previously.

**Comment by Felixoid** [comment]
The tests must finish, there are many changes in global things like S3 and de-/compressing

**Comment by Felixoid** [comment]
@azat I need assistant to backport it

As far as I get, I need to remove existing Cargo.lock in subdirs, add the config https://github.com/ClickHouse/ClickHouse/blob/master/rust/Cargo.toml, and edit it accordingly to the repository state. What's then? invoke `cargo generate-lockfile` in the `rust/` directory?

**Comment by azat** [comment]
> As far as I get, I need to remove existing Cargo.lock in subdirs, add the config [master/rust/Cargo.toml](https://github.com/ClickHouse/ClickHouse/blob/master/rust/Cargo.toml?rgh-link-date=2023-08-11T21%3A58%3A41Z), and edit it accordingly to the repository state. What's then? invoke cargo generate-lockfile in the rust/ directory?

More or less, but there are some trickiness, see below.

```
cd rust
cp /path/to/upstream/rust/Cargo.toml ./
rm */Cargo.lock
# then you need to pin versions in the */Cargo.toml strictly, i.e. not 'foo = "0.1"' but 'foo = "=0.1"'
# otherwise vendor make download different version and to decrease amount of changes
cargo generate-lockfile
cargo vendor # to check that it works
ninja -v cargo-build__ch_rust_blake3 cargo-build__ch_rust_skim_rust cargo-build__ch_rust_prql # this is required to ensure that vendored versions are correct, due to the tricky step with replacing versions in Cargo.toml
git checkout */Cargo.toml # revert this changes
```

Actually maybe the last command it extra and we need to pin the version, but let me take a look at it this separately, definitely it should not be a part of backports.

**Comment by Felixoid** [comment]
thanks, but it's indeed too much work to try to backport it

**Pull request merged**
