### PR TITLE
"Atomically" remove parts on destroy.

### PR DESCRIPTION
**Pull request by excitoon**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Improvement

Changelog entry (up to few sentences, required except for Non-significant/Documentation categories):

"Atomically" remove parts on destroy to prevent existence of inconsistent copies #7660.

Progress on #7660.

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
Tests have failed for reason.

**Comment by excitoon** [comment]
Reverted #8790 here.

**Comment by alexey-milovidov** [comment]
Still have failed tests.

**Comment by excitoon** [comment]
I can simply remove last commit.

**Pull request merged**
