### PR TITLE
Better locking for StorageBuffer

### PR DESCRIPTION
**Pull request by amosbird**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
Do I understand correctly the difference is that we avoid unlocking the mutex before flushBuffer and then locking it again? Looks reasonable.

**Comment by alexey-milovidov** [comment]
But the tests have failed.

**Review by alexey-milovidov — CHANGES_REQUESTED** [review]
.

**Comment by amosbird** [comment]
> Do I understand correctly the difference is that we avoid unlocking the mutex before flushBuffer and then locking it again? 

Exactly.

**Pull request merged**
