### PR TITLE
[RFC] Cleanup remote_servers in dist config.xml

### LINKED ISSUE #51210: The server's default configuration can have a cluster named `default` containing one shard with one replica localhost.
It will unify single-node setups with ClickHouse Cloud that have cluster `default`, and it will allow writing some monitoring queries in the same way for self-managed and Cloud setups.

### PR DESCRIPTION
**Pull request by azat**
At first, there was no such amount of clusters in dist config, they added when someone need to write some new cluster for tests.

So let's move them to the clusters.xml that is deployed only for tests, and leave only default cluster.

And cleanup also some configs that had been copied from dist config in the repo (about test_config_* integration tests, this should be OK, since there are more_clusters.xml as well, that covers additional cases).

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Fixes: #51210

### CODE REVIEW

**Comment by robot-ch-test-poll4** [comment]
This is an automated comment for commit ef53c2f0357f82e92067e375f6b54ec3d9b8d546 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/51985/ef53c2f0357f82e92067e375f6b54ec3d9b8d546/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Comment by alexey-milovidov** [comment]
Let's add this: https://github.com/ClickHouse/ClickHouse/issues/51210

**Comment by alexey-milovidov** [comment]
Maybe go further and remove all other clusters as well?

**Comment by azat** [comment]
>Maybe go further and remove all other clusters as well?

Yes, let's do this as well.

**Comment by azat** [comment]
Does not looks related:

>PullRequestCI / SQLLogicTestRelease (pull_request) Failing after 6m

```
+ /clickhouse-tests/sqllogic/runner.py --log-file /test_output/runner-statements-test.log --log-level info statements-test --input-dir /sqllogictest --out-dir /test_output/statements-test
+ ts '%Y-%m-%d %H:%M:%S'
2023-07-09 18:02:26 multiprocessing.pool.RemoteTraceback: 
2023-07-09 18:02:26 """
2023-07-09 18:02:26 Traceback (most recent call last):
2023-07-09 18:02:26   File "/usr/lib/python3.10/multiprocessing/pool.py", line 125, in worker
2023-07-09 18:02:26     result = (True, func(*args, **kwds))
2023-07-09 18:02:26   File "/clickhouse-tests/sqllogic/runner.py", line 135, in _child_process
2023-07-09 18:02:26     runner.run_all_tests_from_file(test, input_dir)
2023-07-09 18:02:26   File "/clickhouse-tests/sqllogic/test_runner.py", line 557, in run_all_tests_from_file
2023-07-09 18:02:26     self.run_one_test(stream, test_name, test_file)
2023-07-09 18:02:26   File "/clickhouse-tests/sqllogic/test_runner.py", line 532, in run_one_test
2023-07-09 18:02:26     with self.connection.with_one_test_scope():
2023-07-09 18:02:26   File "/usr/lib/python3.10/contextlib.py", line 142, in __exit__
2023-07-09 18:02:26     next(self.gen)
2023-07-09 18:02:26   File "/clickhouse-tests/sqllogic/connection.py", line 164, in with_one_test_scope
2023-07-09 18:02:26     self.drop_all_tables()
2023-07-09 18:02:26   File "/clickhouse-tests/sqllogic/connection.py", line 136, in drop_all_tables
2023-07-09 18:02:26     logger.info("tables will be dropped: %s", list_result.get_result())
2023-07-09 18:02:26   File "/clickhouse-tests/sqllogic/connection.py", line 241, in get_result
2023-07-09 18:02:26     self.assert_no_exception()
2023-07-09 18:02:26   File "/clickhouse-tests/sqllogic/connection.py", line 264, in assert_no_exception
2023-07-09 18:02:26     raise ProgramError(
2023-07-09 18:02:26 exceptions.ProgramError: request doesn't have a result set, it has the exception, exception: ('HY000', '[HY000] HTTP status code: 500\nReceived error:\nCode: 373. DB::Exception: Session clickhouse_odbc_9370860175744060927 is locked by a concurrent client. (SESSION_IS_LOCKED) (version 23.7.1.824)\n\n (1) (SQLExecDirectW)')
2023-07-09 18:02:26 """
2023-07-09 18:02:26 
2023-07-09 18:02:26 The above exception was the direct cause of the following exception:
2023-07-09 18:02:26 
2023-07-09 18:02:26 Traceback (most recent call last):
2023-07-09 18:02:26   File "/clickhouse-tests/sqllogic/runner.py", line 428, in <module>
2023-07-09 18:02:26     main()
2023-07-09 18:02:26   File "/clickhouse-tests/sqllogic/runner.py", line 424, in main
2023-07-09 18:02:26     args.func(args)
2023-07-09 18:02:26   File "/clickhouse-tests/sqllogic/runner.py", line 208, in calle
2023-07-09 18:02:26     reports["verify-clickhouse"] = run_all_tests_in_parallel(
2023-07-09 18:02:26   File "/clickhouse-tests/sqllogic/runner.py", line 156, in run_all_tests_in_parallel
2023-07-09 18:02:26     reports = [ar.get() for ar in async_results]
2023-07-09 18:02:26   File "/clickhouse-tests/sqllogic/runner.py", line 156, in <listcomp>
2023-07-09 18:02:26     reports = [ar.get() for ar in async_results]
2023-07-09 18:02:26   File "/usr/lib/python3.10/multiprocessing/pool.py", line 774, in get
2023-07-09 18:02:26     raise self._value
2023-07-09 18:02:26 exceptions.ProgramError: request doesn't have a result set, it has the exception, exception: ('HY000', '[HY000] HTTP status code: 500\nReceived error:\nCode: 373. DB::Exception: Session clickhouse_odbc_9370860175744060927 is locked by a concurrent client. (SESSION_IS_LOCKED) (version 23.7.1.824)\n\n (1) (SQLExecDirectW)')
```

**Review by alexey-milovidov — APPROVED** [review]

**Pull request merged**
