### PR TITLE
nullIf return now the correct result when both arguments are constants

### PR DESCRIPTION
**Pull request by YiuRULE**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

For changelog. Remove if this is non-significant change.

Category (leave one):
- Bug Fix

Short description (up to few sentences):

Resolve a bug with `nullIf` function when we send a `NULL` argument on the second argument.

Detailed description (optional):

Previously, `SELECT nullIf(1, NULL)` returned `NULL` when both side were constants. (the bugs weren't reproducible when one of this arguments were not constant).

Changing the logic of the function from `if(equals(col_1, col_2), NULL, col_1)` to `if(notEquals(col_1, col_2), col_1, NULL)` seem to fix the problem.

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
Ok.

PS. For reference: http://sqlfiddle.com/#!9/0a28f18/361

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
Something is wrong:

```
milovidov@milovidov-Pro-P30:~/work/ClickHouse/dbms/tests/queries/0_stateless$ for i in {1..100}; do clickhouse-client --query "SELECT nullIf(1, NULL)"; done
\N
1
1
1
1
1
\N
1
1
1
1
1
\N
1
1
1
1
1
\N
1
1
1
1
1
\N
1
1
1
1
1
\N
1
1
1
1
1
\N
1
1
1
1
1
\N
1
1
1
1
1
\N
1
1
1
1
1
\N
1
1
1
1
1
\N
1
1
1
1
1
\N
1
1
1
1
1
\N
1
1
1
1
1
\N
1
1
1
1
1
\N
1
1
1
1
1
\N
1
1
1
1
1
\N
1
1
1
```

**Comment by YiuRULE** [comment]
Ok weird, thanks ! I will take a look

**Comment by YiuRULE** [comment]
@alexey-milovidov How is exactly the configuration you used for your test ?

I tried both on this branch and on the latest `master` branch, with building clickhouse locally inside a `build` folder, with the default configuration we can find at `dbms/programs/server/`, and I tried the test locally.

```
for i in {1..100}; do build/dbms/programs/clickhouse client --query "SELECT nullIf(1,NULL)"; done
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
```

Can you provide some input about it ? I really tried as much as I can to reproduce the bug, without success :/

**Comment by alexey-milovidov** [comment]
clang, debug build.
It also reproduces in our CI checks in various build configurations, example: https://clickhouse-test-reports.s3.yandex.net/0/b1d1a23318758c74bb7a883bf39022db584474b5/functional_stateless_tests_(ubsan).html

**Comment by alexey-milovidov** [comment]
Previous implementation was correct in terms of idea but technically wrong.

**Pull request merged**
