### PR TITLE
Replace libpq code dump by postgresql fork + bump to v14.3

### PR DESCRIPTION
**Pull request by rschu1ze**
This PR is motivated by https://github.com/ClickHouse/ClickHouse/issues/67069#issuecomment-2346414365 and it addresses libpq. This library is the C backend of libpqxx and it handles PostgreSQL connections. It used to be a code dump (here: https://github.com/ClickHouse/libpq/pull/5) ...
1) of files scraped from different directories of the PostgreSQL repository in a 2021 code version,
2) additionally, some files were modified (without extra commit) to make it build ... I found out the hard way (via `diff`) which files and which places were changed compared to the original code dump
3) additionally, a couple of extra commits of the previous code dump (before the code dump) were picked on top.

With this PR, the code dump is gone and we now have PostgreSQL as a submodule (the home of libpq). For now, this uses the same version of the code dump (1), I then re-applied all modifications (2 & 3, [here](https://github.com/ClickHouse/postgres/commits/ClickHouse/2f7bae2f92/)) and adjusted the build descriptions. In theory, nothing should break. In the long run this will allow us to upgrade libpq to more recent much more easily (e.g. as needed by https://github.com/ClickHouse/ClickHouse/issues/67069).

EDIT: Also bumping to v14.3.

Also see https://github.com/ClickHouse/ClickHouse/pull/69580 which bumps libpqxx.

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by robot-clickhouse** [comment]
*This is an automated comment for commit 4963ab603cdf003edb797ec3fc163900ee3d28fa with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/69564/4963ab603cdf003edb797ec3fc163900ee3d28fa/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/69432/6f9d1631e26bbb0263962c6d50c65e9ee2be561a/docs_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Comment by rschu1ze** [comment]
@jkartseva Like to approve this one? Thanks!

**Review by jkartseva — APPROVED** [review]
Looks good.

**Comment by antonio2368** [comment]
We now fetch the entire postgres repository
Could we at least extend `contrib/sparse-checkout` to avoid fetching so many useless files?

**Comment by rschu1ze** [comment]
> Could we at least extend contrib/sparse-checkout to avoid fetching so many useless files?

Yes, that makes sense, I'll check.

**Comment by rschu1ze** [comment]
By the way, neither the previous code dump nor the postgres repo is checked out by fastest (tests/docker_scripts/fasttest_runner.sh).

As far as I see, normal builds in CI don't use `contrib/sparse-checkout` (as they build with all dependencies). Anyways, compared to total compile times, additional checkout times are kind of small.

I actually don't know who would use `contrib/sparse-checkout` at all because it makes any changes around submodules a pain.

**Pull request merged**
