### PR TITLE
Try to fix JIT for aggregation functions

### LINKED ISSUE #48120: Incorrect query results with external aggregation and JIT
The following query must return an empty set:

```sql
SELECT
    COUNT() AS c,
    group_key,
    anyIf(r, key = 0) AS x0,
    anyIf(r, key = 1) AS x1,
    anyIf(r, key = 2) AS x2
FROM
(
    SELECT
        CRC32(toString(number)) % 1000000 AS group_key,
        number % 3 AS key,
        number AS r
    FROM numbers(10000000)
)
GROUP BY group_key
HAVING (c = 2) AND (x0 > 0) AND (x1 > 0) AND (x2 > 0)
ORDER BY group_key ASC
LIMIT 10
SETTINGS max_bytes_before_external_group_by = 200000
```

But if you run it more than 3 times, it'll start to return garbage values.
The difference between logs for those runs is the following message:

```
2023.03.28 17:20:05.728354 [ 3130963 ] {4647ed49-6e92-4131-8a0a-b87d02958eb2} <Trace> Aggregator: Compile expression count()() 0 anyIf()(UInt64, UInt8) 8 anyIf()(UInt64, UInt8) 24 anyIf()(UInt64, UInt8) 40 
```

With `compile_aggregate_expressions` set to `0` the query always returns an empty set.

cc @kitaisreal

### PR DESCRIPTION
**Pull request by devcrafter**
Did some digging. The results look like access to uninitialized memory (different values for release/debug builds). Noticed that we do something only for `if` branch ([here](https://github.com/ClickHouse/ClickHouse/blob/426221cadf3fdc310caac223181f2e8308bbf53c/src/AggregateFunctions/AggregateFunctionMinMaxAny.h#L358)) but nothing for `else` branch when building `IR` for comparison in `If`. I.e. we don't touch the initial uninitialized value for `minIf()` in `IR`

### Changelog category (leave one):
- Performance Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fixes aggregate combinator `-If` when JIT compiled. Closes https://github.com/ClickHouse/ClickHouse/issues/48120

### CODE REVIEW

**Comment by evillique** [comment]
Does `02703_jit_external_aggregation.sh` test pass with `--compile_aggregate_expressions 1`?

**Comment by devcrafter** [comment]
> Does `02703_jit_external_aggregation.sh` test pass with `--compile_aggregate_expressions 1`?

Yes, it does.
But there is a query which still failed (based on https://github.com/ClickHouse/ClickHouse/issues/47891):
```sql
SELECT count()
FROM numbers(65412)
GROUP BY if(number < 2., NULL, number)
```

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
```
Apr 26 11:46:31 Caused by:
Apr 26 11:46:31   failed to fetch `https://github.com/rust-lang/crates.io-index`
```

**Comment by evillique** [comment]
We should probably backport this PR similarly to https://github.com/ClickHouse/ClickHouse/pull/48195

**Comment by devcrafter** [comment]
> We should probably backport this PR similarly to #48195

Thanks for mentioning, but I don't see the point. Since #48195 disables JIT compilation for aggregation functions
(1) this fix will have no effect by default
(2) it can make sense only after other bugs related to `compile_aggregate_expressions` will be fixed

**Comment by evillique** [comment]
I suppose the final goal is to enable back JIT compilation by default in current and previous versions. And it seems like for us to do it we would need to also backport this PR.

**Pull request merged**
