### PR TITLE
Slightly better jepsen tests

### PR DESCRIPTION
**Pull request by alesapin**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Review by antonio2368 — APPROVED** [review]
Do we wait for jepsen to run on this branch or do we merge it instantly?
I think it needs to rerun after the label was added.

**Comment by alesapin** [comment]
@mergifyio update

**Comment by antonio2368** [comment]
```
INFO [2022-05-27 02:03:02,248] jepsen node 172.31.43.137 - jepsen.core /home/robot-clickhouse/logs/clickhouse-keeper.log pipe closed
INFO [2022-05-27 02:03:02,350] jepsen node 172.31.45.142 - jepsen.core /home/robot-clickhouse/logs/clickhouse-keeper.log doesn't exist
INFO [2022-05-27 02:03:02,454] jepsen node 172.31.34.47 - jepsen.core /home/robot-clickhouse/logs/clickhouse-keeper.log pipe closed
```
😢

**Comment by alesapin** [comment]
@mergifyio update

**Comment by alesapin** [comment]
Didn't help

**Comment by antonio2368** [comment]
We got a better message with `scp`
```
clojure.lang.ExceptionInfo: Shell command ("scp" "-rpC" "-P" "22" "-o StrictHostKeyChecking=no" "ubuntu@172.31.35.222:/home/robot-clickhouse/logs/clickhouse-keeper.log.gz" "/ch/tests/jepsen.clickhouse-keeper/store/clickhouse-keeper-quorum=true-set-blind-others-partitioner/20220531T172347.000+0300/172.31.35.222/logs/clickhouse-keeper.log.gz") returned exit status 1
scp: /home/robot-clickhouse/logs/clickhouse-keeper.log.gz: Permission denied
```
🤔

**Pull request merged**
