### PR TITLE
Fix flaky 02458_datediff_date32 test

### PR DESCRIPTION
**Pull request by rvasin**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by rvasin** [comment]
@rschu1ze Please assign yourself as reviewer for this PR.

**Comment by qoega** [comment]
Why should it help?
I see this failure in CI https://s3.amazonaws.com/clickhouse-test-reports/0/cd158b021fe7f18f7ebaad3e40816a486142bb11/stateless_tests__tsan__[3/3].html
```
+ echo 'Choosen random timezone Pacific/Guam'
+ ln -snf /usr/share/zoneinfo/Pacific/Guam /etc/localtime
```

**Comment by rvasin** [comment]
In your link I see that the test is still using year 1900. So you are using old version of CH.

In this fix year was changed from 1900 to 1927 for 02458_datediff_date32. 
Because as [explained](https://github.com/ClickHouse/ClickHouse/pull/42308#issuecomment-1288849683):

```
$ TZ=Pacific/Guam ./clickhouse-local --query "SELECT toRelativeYearNum(toDateTime64('1900-01-01 00:00:00', 3));"
1900  - OK
$ TZ=Pacific/Guam ./clickhouse-local --query "SELECT toRelativeYearNum(toDateTime64('1901-01-01 00:00:00', 3));"
1900  - Wrong
$ TZ=Pacific/Guam ./clickhouse-local --query "SELECT toRelativeYearNum(toDateTime64('1902-01-01 00:00:00', 3));"
1902  - OK
```
The issue was created specifically for that case #42615

**Comment by ilejn** [comment]
> Why should it help? 

It should help because 
the behaviour of the test queries depends on timezone if year 1900 is used
and
does not depend on timezone if year 1927 is used.
The PR can be considered as a quick fix to have CI working fine until https://github.com/ClickHouse/ClickHouse/issues/42615 is handled.

**Pull request merged**
