### PR TITLE
Optimize quantilesExact{Low,High} to use nth_element instead of sort

### PR DESCRIPTION
**Pull request by danlark1**
Changelog category (leave one):
- Performance Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Optimize quantilesExact{Low,High} to use nth_element instead of sort

### CODE REVIEW

**Comment by kitaisreal** [comment]
https://github.com/Mergifyio update

**Comment by kitaisreal** [comment]
@Mergifyio update

**Comment by danlark1** [comment]
image

**Comment by danlark1** [comment]
Failed tests look unrelated, don't they?

**Review by kitaisreal — APPROVED** [review]
Test failures look unrelated.

**Pull request merged**
