### PR TITLE
Remove orphan header files

### PR DESCRIPTION
**Pull request by alexey-milovidov**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by robot-clickhouse-ci-2** [comment]
*This is an automated comment for commit 9bf62dd6220739e183208ee0152606bae7595efe with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/56722/9bf62dd6220739e183208ee0152606bae7595efe/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td><a href="https://github.com/ClickHouse/ClickHouse/actions/runs/6860140501">✅ success</a></td></tr>
<tbody>
</table>
</details>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/56722/9bf62dd6220739e183208ee0152606bae7595efe/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Review by Algunenano — APPROVED** [review]
Poor orphans

**Comment by azat** [comment]
@alexey-milovidov There is one more - `ArrayCache.h` (hadn't been catched by the script because there is a test for it). And seems that you are the author of that file.

**Comment by alexey-milovidov** [comment]
We are removing it in https://github.com/ClickHouse/ClickHouse/pull/53770

**Pull request merged**
