### PR TITLE
Add confidence intervals to ttests

### PR DESCRIPTION
**Pull request by ghost**
Changelog category (leave one):
- New Feature

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Add confidence intervals to ttests

Detailed description / Documentation draft:
I added a confidence level parameter to welchTTest and studentTTest in order to get confidence intervals.

For example, in order to get confidence intervals with 95% confidence level, you can use ```welchTTest(0.95)(left, right)``` or ```studentTTest(0.95)(left, right)```.

Happy New Year.

### CODE REVIEW

**Comment by achimbab** [comment]
@novikd 
The failed test case `test_inconsistent_parts_if_drop_while_replica_not_active`  does not seem to be related to this PR.
Could you please review this PR?

**Comment by achimbab** [comment]
@novikd 
Please let me know if there is anything I have to do to merge this PR.
Thank you in advance.

**Comment by alexey-milovidov** [comment]
@novikd You can assign yourself again or let other people to review.

**Comment by KochetovNicolai** [comment]
@mergifyio update

**Review by KochetovNicolai — APPROVED** [review]

**Pull request merged**
