### PR TITLE
keeper SnapshotableHashTable clean optimization

### PR DESCRIPTION
**Pull request by zhanglistar**
Changelog category (leave one):
- Performance Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Use a vector to collect useless list iterators when doing a snapshot, and in latter clearOutdatedNodes, we can just traverse the vector, not the list, which is faster.

### CODE REVIEW

**Comment by zhanglistar** [comment]
> @zhanglistar could you please provide benchmarks where such optimization make improvement ? I actually skeptical about this optimization, because iterating list is bad for performance because we must fetch pointers and this lead to a lot of cache misses etc. In your case you iterate vector, and also fetch list pointers because you must delete key from arena.

Thanks  for your review. The timing result of clearOutdatedNodes is as follows:
new version:
image

master versin(34092fa2a31dadff5efbd301e7d5):
image

time code is:
image

**Comment by zhanglistar** [comment]
@qoega It seems that there is no relation to my change, can you help check it out? Thanks.

**Comment by zhanglistar** [comment]
> Yes, something was committed to master. We will fix master and run this check again

Thanks for your fast reply.

**Review by kitaisreal — APPROVED** [review]
@zhanglistar now this optimization make sense. I personally did not take a look into this SnapshotableHashTable, maybe there are additional things that could be improved, will take a look.

**Comment by zhanglistar** [comment]
> @zhanglistar the code is different, in previous version we iterate over whole list and check additionally if list node should be removed, in new version we already iterate over list nodes that must be removed.

The new version is? Could you please paste a commit id? I have checked the latest master code.

**Comment by zhanglistar** [comment]
> @zhanglistar now this optimization make sense. I personally did not take a look into this SnapshotableHashTable, maybe there are additional things that could be improved, will take a look.

Thanks, there is another PR: https://github.com/ClickHouse/ClickHouse/pull/34486, which avoids using std::distance on std::list when doing a snapshot, could you please take a look?

**Comment by kitaisreal** [comment]
@zhanglistar will take a look.

**Pull request merged**
