### PR TITLE
Should fail ddl query as soon as possible if table is shutdown

### PR DESCRIPTION
**Pull request by yiguolei**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Background thread which executes `ON CLUSTER` queries might hang waiting for dropped replicated table to do something. It's fixed.

Detailed description / Documentation draft:

Check table status during ddl execution. Set task status to exception if the table is shutdown by drop command or others.

### CODE REVIEW

**Comment by ucasFL** [comment]
LGTM.

**Comment by tavplubix** [comment]
Ok, but could you please explain which problem are you tying to solve? If table is partially shutdown, then `status.is_leader` must be false and everything should work fine, because `DDLWorker` [takes it into account](https://github.com/ClickHouse/ClickHouse/blob/6693f77c322bbadcf7479350df258037376456d3/src/Interpreters/DDLWorker.cpp#L879) and tries to execute query on other replica. If it's not possible for some reason, then query fails with `Task ... was not executed by anyone ...` after several retries.

**Comment by yiguolei** [comment]
@tavplubix If the all replica is dropped, status.is_leader is false on all replicas, so that the number of tries will not be updated by any replica. And it will have to wait for timeout currently it is MAX_EXECUTION_TIMEOUT_SEC = 3600s. It is too long and will blocking other DDL tasks.

**Comment by tavplubix** [comment]
You're right, there is a bug in `DDLWorker`. However, `DROP TABLE` is not the only thing that partially shutdowns replicated table, it also happens on lost ZooKeeper connection and `SYSTEM RESTART REPLICA`. I'm not sure if we should finish DDL query with `Table is shutdown ...` in these cases. Maybe check `IStorage::is_dropped` flag instead of `partial_shutdown_called`? On the other hand, `is_dropped` is false for detached tables, but `DETACH/ATTACH` are usually used to restart replica (and that's how `SYSTEM RESTART REPLICA` works). To avoid waiting on permanently detached tables we can use something like this:
```
bool replica_dropped = storage->is_dropped;
bool all_replicas_likely_detached = status.active_replicas == 0 && !DatabaseCatalog::instance().isTableExist(table_id, context);
if (replica_dropped || all_replicas_likely_detached) /// Table is shutdown ...
```
What do you think?

Btw, could you please add a test? It can be simple stateless test with `test_shard_localhost` cluster with one replica.

**Comment by yiguolei** [comment]
@tavplubix You are right. I have another commit. ^-^
 But I find it is hard to test it, because the table has to be dropped during the ddl task's running stage. It is very difficult to make such a test. Could you please provide some idea?

**Comment by tavplubix** [comment]
Take a look at `*.sh` tests (such as `01150_ddl_guard_rwr` and `00993_system_parts_race_condition_drop_zookeeper`). You can run two threads, one thread will execute `CREATE` and `DROP` and other thread will execute `ALTER ... ON CLUSTER`.

**Review by tavplubix — APPROVED** [review]

**Pull request merged**
