### PR TITLE
Fix: RabbitMQ OpenSSL dynamic loading issue

### PR DESCRIPTION
**Pull request by devcrafter**
Secure connections in RabbitMQ broke with #47475, e.g. in v23.8 and v23.9.

Actual fix in RabbitMQ repository: https://github.com/ClickHouse/AMQP-CPP/pull/6

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fixed the issue that the RabbitMQ table engine wasn't able to connect to RabbitMQ over a secure connection.

### CODE REVIEW

**Comment by robot-clickhouse-ci-1** [comment]
*This is an automated comment for commit c410c9b232231c01aceabe8696f4ea2cca9c2928 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/56703/c410c9b232231c01aceabe8696f4ea2cca9c2928/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td><a href="https://github.com/ClickHouse/ClickHouse/actions/runs/6855582307">✅ success</a></td></tr>
<tbody>
</table>
</details>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/56703/c410c9b232231c01aceabe8696f4ea2cca9c2928/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Comment by Algunenano** [comment]
Not sure if the remotes are set correctly (maybe you haven't pushed to the submodule?)

```
Fetching submodule contrib/AMQP-CPP
From https://github.com/ClickHouse/AMQP-CPP
 * [new branch]      fix-rabbit-openssl -> origin/fix-rabbit-openssl
fatal: remote error: upload-pack: not our ref ef1336cf645428889c69b1e5efb88b8c85d14595
Errors during submodule fetch:
        contrib/AMQP-CPP
error: could not fetch blessed
Fetching origin
```

image

**Review by alexey-milovidov — APPROVED** [review]

**Comment by rschu1ze** [comment]
@devcrafter + a test?

**Comment by devcrafter** [comment]
> @devcrafter + a test?

Will be done in separate PR. Looking into it

**Pull request merged**
