### PR TITLE
Update grpc submodule to PR 9

### PR DESCRIPTION
**Pull request by HarryLeeIBM**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
...

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by HarryLeeIBM** [comment]
@alexey-milovidov, this PR is for https://github.com/ClickHouse/grpc/pull/9.  Could u help me to merge it? Thanks!

**Comment by HarryLeeIBM** [comment]
@alexey-milovidov, could this PR be merged please? Thanks!

**Comment by alexey-milovidov** [comment]
Amazon returned 500:

```
https://s3.amazonaws.com/clickhouse-builds/37721/93be56a151cb07abc22e6d94383b79e8d4b2e03b/package_release/performance.tgz:
2022-06-01 21:38:50 ERROR 500: Internal Server Error.
```

**Comment by alexey-milovidov** [comment]
@mergifyio update

**Pull request merged**
