### PR TITLE
Revert "Add documentation for building in docker"

### PR DESCRIPTION
**Pull request by alexey-milovidov**
Reverts ClickHouse/ClickHouse#51679

### CODE REVIEW

**Comment by robot-ch-test-poll1** [comment]
This is an automated comment for commit 463c2ba5ce13a6839dfaf12223826b9e90f143c8 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/51773/463c2ba5ce13a6839dfaf12223826b9e90f143c8/ci_running.html)
The overall status of the commit is 🔴 failure

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🔴 failure</td></tr>
</table>

**Comment by guoxiaolongzte** [comment]
why?About reverts https://github.com/ClickHouse/ClickHouse/pull/51679

**Comment by alexey-milovidov** [comment]
@guoxiaolongzte broken tests.

**Comment by guoxiaolongzte** [comment]
Can I continue to use this for compilation? Should we wait for your modifications？



---Original---
From: "Alexey ***@***.***&gt;
Date: Wed, Jul 5, 2023 20:13 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [ClickHouse/ClickHouse] Revert "Add documentation for building indocker" (PR #51773)




 
@guoxiaolongzte broken tests.

**Pull request merged**
