### PR TITLE
What happens if MySQL is enabled for macOS?

### LINKED ISSUE #21191: Enable MySQL in MacOS builds

### PR DESCRIPTION
**Pull request by rschu1ze**
Addresses #21191

### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Enable MySQL/MariaDB on macOS. This closes #21191.

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
What has happened?

**Comment by robot-ch-test-poll4** [comment]
*This is an automated comment for commit 691803cc949e0d8acb7f8cee7f209a57f49f80a7 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/46316/691803cc949e0d8acb7f8cee7f209a57f49f80a7/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/46316/691803cc949e0d8acb7f8cee7f209a57f49f80a7/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Review by alexey-milovidov — APPROVED** [review]

**Comment by rschu1ze** [comment]
Thanks a lot for finishing this.

**Comment by alexey-milovidov** [comment]
My pleasure! 

The only remaining question is whether it will run on typical configurations. Because I've added a dependency on iconv's dylib. On Linux, it is part of libc, but on Mac, it is a separate library. Most likely, it is installed most of the time, but I'm not sure.

**Pull request merged**
