### PR TITLE
Added field `refcount` to `system.remote_data_paths` table

### PR DESCRIPTION
**Pull request by CurtizJ**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Added field `refcount` to `system.remote_data_paths` table

### CODE REVIEW

**Comment by robot-ch-test-poll3** [comment]
This is an automated comment for commit 4f8078c3577cb16fb823fd4a1cae036e36be6a84 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/52518/4f8078c3577cb16fb823fd4a1cae036e36be6a84/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Review by alexey-milovidov — APPROVED** [review]

**Comment by tavplubix** [comment]
@alexey-milovidov, Mergeable check did not help, it was merged with broken tests

**Comment by CurtizJ** [comment]
Nobody cares about check with analyzer.

**Comment by CurtizJ** [comment]
Looks like this test showed a bug in mutations with analyzer: some files are extra copyied instead of hardlinking.

**Comment by CurtizJ** [comment]
It's out of scope of this PR and I'm not going to fix it.

**Comment by tavplubix** [comment]
> It's out of scope of this PR and I'm not going to fix it.

It's okay, but please add it to the list of broken tests at least, just to avoid failing tests in master.

cc: @novikd

**Pull request merged**
