### PR TITLE
Add check for recursiveRemoveLowCardinality()

### PR DESCRIPTION
**Pull request by vitlibar**
### Changelog category:
- Not for changelog

### CODE REVIEW

**Comment by robot-clickhouse-ci-2** [comment]
*This is an automated comment for commit a88957d4ca976c4f3bb810dcad2cfb83d8eb6d9f with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/59845/a88957d4ca976c4f3bb810dcad2cfb83d8eb6d9f/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/59845/a88957d4ca976c4f3bb810dcad2cfb83d8eb6d9f/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
Iceberg melted down.

**Comment by vitlibar** [comment]
> Iceberg melted down.

Turned out [AvroSchemaReader::avroNodeToDataType()](https://github.com/ClickHouse/ClickHouse/blob/09d3b3c0d04aa2ee0c5661a70bb4c67bfbb0765d/src/Processors/Formats/Impl/AvroRowInputFormat.cpp#L1290) converts the Avro `record` type into our `Tuple` type, however `Avro` supports empty "records" and [we don't support empty tuples](https://clickhouse.com/docs/en/sql-reference/data-types/tuple).

Earlier the failed tests were passing despite they created wrong `ColumnTuple` objects.
Before this PR `ColumnTuple` could be created without nested columns but such ColumnTuples didn't work. Even [ColumnTuple::size()](https://github.com/ClickHouse/ClickHouse/blob/09d3b3c0d04aa2ee0c5661a70bb4c67bfbb0765d/src/Columns/ColumnTuple.h#L51) cannot work without nested columns.

In this PR I've added more checks so now those tests are failing.

**Comment by Avogar** [comment]
The place in Avro/Iceberg with empty tuple will be fixed in https://github.com/ClickHouse/ClickHouse/pull/60309.

**Pull request merged**
