### PR TITLE
Information about moves in `system.merges`

### PR DESCRIPTION
**Pull request by excitoon**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Improvement

Changelog entry (up to few sentences, required except for Non-significant/Documentation categories):

Paths and information about moves in `system.merges`.

### CODE REVIEW

**Comment by excitoon** [comment]
Made complete pull request by mistake, it should be a draft...

**Review by alesapin — CHANGES_REQUESTED** [review]
Why information about moves stored in `system.merges` table?

**Comment by filimonov** [comment]
> Why information about moves stored in `system.merges` table?

And why mutations are there? :)

More seriously - there are more options. We are open to discuss pros / cons. 

From a user perspective, we just want we need to know what the ClickHouse is doing in the background right now. Especially if it is a long-running operation creating large IO load. 

Options:
1) introduce smth like system.moves. But it means we will  also need (potentially) introduce a separate table for all possible background operations - i.e. smth like `system.ttl_operations`, `system.distributed_sends` etc. It will be quite hard to understand why clickhouse is busy (you will need to do a lot of selects).
2) introduce something like system.background_operations which will coexists with system.merges, but will be used for non-merge operation.  (but mutations are already in merges)
3) introduce something like system.background_operations which will supersede/include system.merges and will be used for all types of background operations (including merges)
4) just reuse system.merges as the nature of moves is quite similar to merges. 

Option nr. 4 just looked as the most straight-forward, and reusing existing 'infrastructure'. So 
if somebody was checking `system.merges` to understand what is happening on the server right now - can still do that.

**Comment by alesapin** [comment]
> just reuse system.merges as the nature of moves is quite similar to merges.

Moves absolutely different from merges and work at another level of abstraction (`MergeTreeData` level). 
`system.(background_)jobs` or `system.(background_)operations` looks good to me. I think this table should contain data from `system.mutations`, `system.merges` and information about system moves.

**Comment by excitoon** [comment]
Separated information about paths to #8043

**Comment by alexey-milovidov** [comment]
Outdated.

**Pull request closed without merging**
