### PR TITLE
Fix cpu count with cgroup limits

### LINKED ISSUE #2261: Clickhouse doesn't respect cgroup limits
Currently getNumberOfPhysicalCPUCores doesn't respect if CK is run inside of a docker container / cgroup. It will return the actual amount of cores on the host instead of the limited amount
Which I'm guessing means CK sizes thread pools etc to use all CPUs instead of the allocated amount

Suggested would be to read ```/sys/fs/cgroup/cpu/cpu.cfs_quota_us``` if > -1 and divide by 1000 and round up to closest integer

For memory CK could read ```/sys/fs/cgroup/memory/memory.limit_in_bytes``` if available

### LINKED ISSUE #25662: Detect that server is running under cgroup control, get cpu/memory info with limitations
Hi, we are planning to run our CH instances in kubernetes and I was wondering if the `max_server_memory_usage_to_ram_ratio` will check if we are running under a cgroup control and read the value from /sys/fs/cgroup/memory. I suspect that it doesn't but wanted to confirm (found this: https://github.com/flant/loghouse/issues/110).

### PR DESCRIPTION
**Pull request by JaySon-Huang**
Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Respect cgroup limits for CPU quota

Detailed description / Documentation draft:
close https://github.com/ClickHouse/ClickHouse/issues/2261, close https://github.com/ClickHouse/ClickHouse/issues/25662
Try to check cgroup limits under `/sys/fs/cgroup/cpu/`. Reference: http://hg.openjdk.java.net/jdk/jdk/rev/7f22774a5f42

> By adding documentation, you'll allow users to try your new feature immediately, not when someone else will have time to document it later. Documentation is necessary for all features that affect user experience in any way. You can add brief documentation draft above, or add documentation right into your patch as Markdown files in [docs](https://github.com/ClickHouse/ClickHouse/tree/master/docs) folder.

> If you are doing this for the first time, it's recommended to read the lightweight [Contributing to ClickHouse Documentation](https://github.com/ClickHouse/ClickHouse/tree/master/docs/README.md) guide first.

> Information about CI checks: https://clickhouse.tech/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by JaySon-Huang** [comment]
Tested by creating a simple docker image:
```
// a.cpp
#include <iostream>
#include "getNumberOfPhysicalCPUCores.h"
int main()
{
    std::cout << "thread: " << getNumberOfPhysicalCPUCores() << std::endl;
    return 0;
}
// g++ a.cpp


>  docker run --rm --cpus="2" jayson/test_cpu ./a.out
thread: 2
>  docker run --rm --cpus="4" jayson/test_cpu ./a.out
thread: 4
>  docker run --rm --cpus="8" jayson/test_cpu ./a.out
thread: 8
>  docker run --rm --cpus="40" jayson/test_cpu ./a.out
thread: 40
>  docker run --rm --cpus="80" jayson/test_cpu ./a.out
docker: Error response from daemon: Range of CPUs is from 0.01 to 40.00, as there are only 40 CPUs available.
See 'docker run --help'.
> docker run --rm --cpus="8.6" jayson/test_cpu ./a.out
thread: 9
```

**Comment by azat** [comment]
> Tested by creating a simple docker image:

By the way, this can be tested using integration test, something similar to https://github.com/ClickHouse/ClickHouse/blob/master/tests/integration/test_jemalloc_percpu_arena/test.py

**Comment by JaySon-Huang** [comment]
> > Tested by creating a simple docker image:
> 
> By the way, this can be tested using integration test, something similar to https://github.com/ClickHouse/ClickHouse/blob/master/tests/integration/test_jemalloc_percpu_arena/test.py

I'll try to add some tests later this week

**Comment by bobrik** [comment]
How does this work with cgroupv2 only?

**Comment by JaySon-Huang** [comment]
> @bobrik  How does this work with cgroupv2 only hierarchies?

After doing some research, this PR doesn't work under cgroup v2.
However, now both CPU and Memory don't work under cgroup v2, and v2 is not enabled by default as far as I know. Maybe we can open another issue for cgroup v2 limits?

Reference:
* Control Group v2: https://www.kernel.org/doc/html/latest/admin-guide/cgroup-v2.html

**Comment by bobrik** [comment]
I think it's ok to just add v1 and have a separate issue for v2.

**Comment by JaySon-Huang** [comment]
"Stress test (debug, actions) — OOM killer (or signal 9) in clickhouse-server.log"

I'm not sure why this test is failed.

**Comment by Felixoid** [comment]
@Mergifyio update

**Comment by Felixoid** [comment]
@Mergifyio update

**Comment by JaySon-Huang** [comment]
I think this PR is ready to be reviewed. Is there anything I need to do?

**Comment by Felixoid** [comment]
I am waiting for CI and going to merge it :+1:

**Comment by thyn** [comment]
Is any plans to backport this to 21.8?

**Comment by alexey-milovidov** [comment]
@thyn No, as it is not a bugfix.
The only effect is that queries are run slightly less efficient and consume slightly more memory.

**Pull request merged**
