### PR TITLE
Remove obsolete `--multiquery` parameter (follow-up to #63898), pt. II

### PR DESCRIPTION
**Pull request by rschu1ze**
This PR is follow-up to https://github.com/ClickHouse/ClickHouse/pull/63898, removing the obsolete `-n` parameters from tests to avoid confusion why the parameter is still there and future cargo-cult copy-pasting of obsolete stuff into new tests.

Also see https://github.com/ClickHouse/ClickHouse/pull/67435 and https://github.com/ClickHouse/ClickHouse/pull/67964

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by robot-ch-test-poll1** [comment]
*This is an automated comment for commit f3b4c18163c42aec1b9f4853dfee595b890fd100 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/67749/f3b4c18163c42aec1b9f4853dfee595b890fd100/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Builds</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/e4c165e919df7b43671fd8909176e2162c9a65fc/builds/report.html">✅ success</a></td></tr>
<tr><td>ClickBench</td><td>Runs [ClickBench](https://github.com/ClickHouse/ClickBench/) with instant-attach table</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/e4c165e919df7b43671fd8909176e2162c9a65fc/clickbench__aarch64_.html">✅ success</a></td></tr>
<tr><td>Compatibility check</td><td>Checks that <b>clickhouse</b> binary runs on distributions with old libc versions. If it fails, ask a maintainer for help</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/e4c165e919df7b43671fd8909176e2162c9a65fc/compatibility_check__aarch64_.html">✅ success</a></td></tr>
<tr><td>Docker keeper image</td><td>The check to build and optionally push the mentioned image to docker hub</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/e4c165e919df7b43671fd8909176e2162c9a65fc/docker_keeper_image.html">✅ success</a></td></tr>
<tr><td>Docker server image</td><td>The check to build and optionally push the mentioned image to docker hub</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/e4c165e919df7b43671fd8909176e2162c9a65fc/docker_server_image.html">✅ success</a></td></tr>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/e4c165e919df7b43671fd8909176e2162c9a65fc/docs_check.html">✅ success</a></td></tr>
<tr><td>Install packages</td><td>Checks that the built packages are installable in a clear environment</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/e4c165e919df7b43671fd8909176e2162c9a65fc/install_packages__aarch64_.html">✅ success</a></td></tr>
<tr><td>Integration tests</td><td>The integration tests report. In parenthesis the package type is given, and in square brackets are the optional part/total tests</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/e4c165e919df7b43671fd8909176e2162c9a65fc/integration_tests__aarch64__[1_6].html">✅ success</a></td></tr>
<tr><td>Stateful tests</td><td>Runs stateful functional tests for ClickHouse binaries built in various configurations -- release, debug, with sanitizers, etc</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/e4c165e919df7b43671fd8909176e2162c9a65fc/stateful_tests__aarch64_.html">✅ success</a></td></tr>
<tr><td>Unit tests</td><td>Runs the unit tests for different release types</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/e4c165e919df7b43671fd8909176e2162c9a65fc/unit_tests__asan_.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Review by jkartseva — APPROVED** [review]
The change itself LGTM; however, I think merging should be postponed until flaky tests are fixed.

**Comment by rschu1ze** [comment]
The flaky check fails not because one or more individual tests are flaky but because their total runtime exceeds the timeout (and lots of tests were touched by this PR) :-( This is quite hard to debug unfortunately.

I'll split this PR into two to reduce the number of touched tests.

**Comment by rschu1ze** [comment]
ClickHouse Stateless tests (aarch64): https://github.com/ClickHouse/ClickHouse/issues/68375

**Pull request merged**
