### PR TITLE
Try to improve backward compatibility check

### PR DESCRIPTION
**Pull request by Avogar**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Use tests from previous release for backward compatibility check

### CODE REVIEW

**Comment by Avogar** [comment]
@Mergifyio update

**Comment by Avogar** [comment]
@Mergifyio update

**Comment by Avogar** [comment]
@Mergifyio update

**Review by tavplubix — APPROVED** [review]
Cool, cloning repo with old tests is even better than filtering current tests!

**Pull request merged**
