### PR TITLE
Add NCHAR and NVARCHAR synonims

### PR DESCRIPTION
**Pull request by alexey-milovidov**
Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Add `NCHAR` and `NVARCHAR` synonims for data types.

Detailed description / Documentation draft:
See https://www.sqlite.org/datatype3.html

### CODE REVIEW

**Comment by zhang2014** [comment]
It work fine for NCHAR(4) ?

**Comment by qoega** [comment]
Actually it may by too risky to add them as synonyms without difference in behavior.
https://stackoverflow.com/a/176565

It can be hard to make it more close to ANSI if it has different behavior. Have you checked the difference?

**Comment by alexey-milovidov** [comment]
It's totally Ok as they are intended for Unicode strings.
We support Unicode strings in our String type with the http://utf8everywhere.org/ principle.

**Comment by mchampaneri** [comment]
NCHAR data type working when used to calculate hash, It gives differnt then the one generated by MSSQL.

```
select hashbytes("sha1",CAST(("manish") AS nchar(50)))

Output: 0x9D9462DDA7D2F09C29E9BD01C0C4893C3EA3222A
```

```
select HEX(SHA1(CAST(rightPad('manish',50,' ') AS NCHAR)));

Output: 6162D8710E618AFACBEE93876E786004984D55AA 
```

FYI: It genereates correct output for char though.

**Pull request merged**
