### PR TITLE
Skip max_partition_size_to_drop check in case of ATTACH PARTITION ... FROM

### LINKED ISSUE #30897: ATTACH PARTITION fails when existing destination table's partition is large
**Unexpected behavior**
ATTACH PARTITION command fails when destination table's existing partition size is large than `max_partition_size_to_drop`

Attaching a tiny sample of few hundred rows from `db.source_table_sample` to `db.destination_table_full` fails because partition `202108` size is (53.46 GB) which is larger than default `max_partition_size_to_drop` (50GB)

Error message:
```sql
ALTER TABLE db.destination_table_full
    ATTACH PARTITION 202108 FROM db.source_table_sample

Query id: adf2c8fb-ba8a-4846-9c32-fabdb0d387b9


0 rows in set. Elapsed: 0.002 sec.

Received exception from server (version 21.7.11):
Code: 359. DB::Exception: Received from localhost:9440. DB::Exception: Table or Partition in db.destination_table_full was not dropped.
Reason:
1. Size (53.46 GB) is greater than max_[table/partition]_size_to_drop (50.00 GB)
2. File '/drives/ssd1/clickhouse/flags/force_drop_table' intended to force DROP doesn't exist
How to fix this:
1. Either increase (or set to zero) max_[table/partition]_size_to_drop in server config
2. Either create forcing file /drives/ssd1/clickhouse/flags/force_drop_table and make sure that ClickHouse has write permission for it.
Example:
sudo touch '/drives/ssd1/clickhouse/flags/force_drop_table' && sudo chmod 666 '/drives/ssd1/clickhouse/flags/force_drop_table'.
```

However, if I try to do the same in a new empty table `db.destination_table_sample`, it can attach partition successfully.

```sql
ALTER TABLE db.destination_table_sample
    ATTACH PARTITION 202108 FROM db.source_table_sample

Query id: f1567cf5-b1da-476c-aebb-3cf9f767849e

Ok.

0 rows in set. Elapsed: 0.003 sec.
```

How I calculated partition size:
```sql
SELECT
    partition,
    formatReadableSize(sum(bytes_on_disk)),
    round(((sum(bytes_on_disk) / 1000) / 1000) / 1000, 2) AS GB
FROM system.parts
WHERE table = 'destination_table_full'
GROUP BY partition

Query id: 33862450-3dd5-410e-aee0-30fbee339b68

┌─partition─┬─formatReadableSize(sum(bytes_on_disk))─┬────GB─┐
│ 202107    │ 2.07 GiB                               │  2.22 │
│ 202108    │ 49.79 GiB                              │ 53.46 │
│ 202110    │ 5.85 GiB                               │  6.28 │
│ 202109    │ 17.89 GiB                              │ 19.21 │
└───────────┴────────────────────────────────────────┴───────┘
```

**Expected behavior**
Partitions should be attached successfully regardless of `max_partition_size_to_drop` value

**How to reproduce**
ClickHouse server version: ClickHouse server version 21.7.11.3 (official build).
Which interface to use: clickhouse-client (I originally noticed this behavior in the logs of clickhouse-copier)

### PR DESCRIPTION
**Pull request by amralaa-MSFT**
Changelog category (leave one):
- Bug Fix (user-visible misbehaviour in official stable or prestable release)

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Skip max_partition_size_to_drop check in case of ATTACH PARTITION ... FROM and MOVE PARTITION
...

Detailed description / Documentation draft:
`ATTACH PARTITION ... FROM ...` fail when target partition size is larger than the `max_partition_size_to_drop` because `ATTACH PARTITION ... FROM ...` gets interpreted as `ASTAlterCommand::REPLACE_PARTITION` command with `replace` flag set to `false`. 
That's why it enters the code path for `REPLACE_PARTITION` which checks that partition can be dropped.
This check should be skipped in the case of `ATTACH PARTITION ... FROM ...` commands that were interpreted as `REPLACE_PARTITION` (i.e. if `command->replace` is `false`)

The same limit is skipped for MOVE PARTITION as well since the partition is dropped from source table after moving to destination, so no need to worry about data loss.

Fixes #30897

### CODE REVIEW

**Comment by tavplubix** [comment]
Thank you for contributing into ClickHouse!

Btw, should we also allow moving partitions of any size between tables using `ALTER TABLE ... MOVE PARTITION` query? https://github.com/ClickHouse/ClickHouse/blob/a1f29d31ea081cf055238be9d4a253327068db1d/src/Storages/MergeTree/MergeTreeData.cpp#L3424-L3426

And it would be great to add a test. However, it can be done only in integration test like [test_force_drop_table](https://github.com/ClickHouse/ClickHouse/blob/13ae988efffc41213445a7a7185a956fb00076df/tests/integration/test_force_drop_table/test.py), but it's not so easy, because our infrastructure for integration tests is too complicated and it can be hard to setup it and run locally. If you have some troubles with running integration tests, let me know, I will do it myself.

**Comment by tavplubix** [comment]
>> Btw, should we also allow moving partitions of any size between tables using ALTER TABLE ... MOVE PARTITION query?
>
> That's a good question. In my opinion, it should be allowed regardless of the existing destination partition size (if any) and should be prevented if source partitions size is larger than `max_partition_size_to_drop`. If I understand correctly, I guess it won't matter since `MOVE_PARTITION` would drop partitions from both source and destination tables and the same limit applies to all tables.

Yes, `MOVE PARTITION` drops partition from the source table, but only after copying it to the destination table. The `force_drop_table` flag protects from accidental data loss, but since data is copied to to the destination table, no data will be lost even if we drop it from the source table. So I think it's safe enough to remove [this line](https://github.com/ClickHouse/ClickHouse/blob/a1f29d31ea081cf055238be9d4a253327068db1d/src/Storages/MergeTree/MergeTreeData.cpp#L3426) and disable this protection for `MOVE PARTITION`.

**Comment by tavplubix** [comment]
Integration tests failures are not related to the changes, these tests are broken in master, so you can ignore it.

**Review by tavplubix — APPROVED** [review]

**Comment by amralaa-MSFT** [comment]
@tavplubix Thank you so much for your help

**Pull request merged**
