### PR TITLE
Vector similarity index: make `bf16` the default quantization

### PR DESCRIPTION
**Pull request by rschu1ze**
This PR
- bumps usearch (the backend of the experimental vector similarity index) to v2.14.0
- adds `f64` and `bf16` as quantization types
- makes `bfloat16` the default quantization (from previously`f32`).

Reasons for the latter:
- approximate HNSW search on single precision vectors is comparable in size and speed as exact search via scan (at least in ClickHouse's vector similarity index, pure HNSW vs. scan may be different), half or less precision vectors provide a more interesting tradeoff
- I compared index creation times for 15 mio 384-dimensional vectors with `f32` vs. `f16` quantization and the latter was a lot slower. Did not test with `bf16` but since casts <==> `f32` are simpler, I expect `bf16` to fix performance.

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by robot-ch-test-poll1** [comment]
*This is an automated comment for commit da7d4e6451809d17addc9567e4f8452c5e39ef31 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/68678/da7d4e6451809d17addc9567e4f8452c5e39ef31/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Style check</td><td>Runs a set of checks to keep the code style clean. If some of tests failed, see the related log from the report</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/68678/da7d4e6451809d17addc9567e4f8452c5e39ef31/style_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Comment by rschu1ze** [comment]
Needs https://github.com/ClickHouse/ClickHouse/pull/68673

**Comment by rschu1ze** [comment]
Needs https://github.com/ClickHouse/ClickHouse/pull/68725

**Review by nikitamikhaylov — APPROVED** [review]

**Comment by rschu1ze** [comment]
ClickHouse performance comparison: #68822

ClickHouse Stateless tests (tsan, s3 storage) [1/3]: The test profile seems generally broken :-( Unrelated for sure.

ClickHouse Upgrade check (debug): Settings changes not reflected, fixed elsewhere.

**Pull request merged**
