### PR TITLE
[WIP] New row policies

### PR DESCRIPTION
**Pull request by vitlibar**
Changelog category:
- Improvement

Changelog entry:
Add a new kind of row policies named `simple`. Before this PR we had two kinds or row policies: `permissive` and `restrictive`.
A `simple` row policy adds a new filter on a table without any side-effects like it was for permissive and restrictive policies.

For example,

```
CREATE ROW POLICY p1 ON mydb.mytable FOR SELECT USING a=1 AS simple TO user1
```

adds a filter on `mydb.mytable` for user `user1` without any side-effects for other users. It means that `user1` will see rows with `a=1`, and `user2` will be able to see any rows.

To compare that with `permissive` and `restrictive` policies: if there are any permissive or restrictive policies defined for a table then all row access should be defined via row policies, i.e. for example

```
CREATE ROW POLICY p1 ON mydb.mytable FOR SELECT USING a=1 AS permissive TO user1
```

makes a system where user `user1` will see rows with `a=1`, and `user2` won't be able to see any rows.

Also this PR adds a new setting `rbac_version`. If it equals to 2 or greater row policies are created as `simple` by default. If it equals to 1(default) row policies are created as `permissive` by default like it was before this PR.

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
[ClickHouse special build check (actions) — 6/7 builds are OK](https://s3.amazonaws.com/clickhouse-builds/35345/afe6a1003a33a4fd00123d6206bb60582be5d415/clickhouse_special_build_check_(actions)/report.html)

**Comment by alexey-milovidov** [comment]
This PR broke clang-tidy, please resubmit.

**Comment by alexey-milovidov** [comment]
Also you forget to assign yourself for code-review.

**Comment by vitlibar** [comment]
> Also you forget to assign yourself for code-review.

Ok, I'll do that the right way: https://github.com/ClickHouse/ClickHouse/pull/35456

What an unlucky feature, it's been reverted already twice

**Pull request merged**
