### PR TITLE
Added `override` to few files. See #8760.

### PR DESCRIPTION
**Pull request by excitoon**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Non-significant (changelog entry is not required)

### CODE REVIEW

**Comment by excitoon** [comment]
#8760

**Comment by alexey-milovidov** [comment]
It isn't required for gcc 9.2
and gcc 9.1 is already obsolete.

**Comment by excitoon** [comment]
@alexey-milovidov what about 8.3?

**Comment by alexey-milovidov** [comment]
gcc 9.3 is so 2010s.

Just disable this specific warning for gcc versions less than 9.2.

**Pull request closed without merging**
