### PR TITLE
Add Linux RISC-V 64 build to CI

### PR DESCRIPTION
**Pull request by alexey-milovidov**
Changelog category (leave one):
- Build/Testing/Packaging Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Add experimental ClickHouse builds for Linux RISC-V 64 to CI.

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
This task requires support from the linker.

**Comment by alexey-milovidov** [comment]
See #40199

**Comment by alexey-milovidov** [comment]
It is almost ready: #40141
But we need to build a fresh LLVM/Clang on Docker build.

**Comment by alexey-milovidov** [comment]
Looks like the compiler-rt library is missing.

**Comment by alexey-milovidov** [comment]
clang-16 is not required, actually clang-14 is enough.

**Comment by robot-clickhouse** [comment]
This is an automated comment for commit 1eafba60d2660accae0d7ea0e1e7f1035121045f with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/31398/1eafba60d2660accae0d7ea0e1e7f1035121045f/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Comment by alexey-milovidov** [comment]
Wow, it works!

**Comment by azat** [comment]
Interesting, it does not work for me. Maybe you have real RISC-V machine?

I got SIGSEGV with qemu (this is docker image that runs qemu inside):

```sh
$ docker run -p 2222 --name riscv --rm -it davidburela/riscv-emulator
$ apt update
$ apt install curl
$ ./clickhouse local
[  361.073643] clickhouse[3167]: unhandled signal 11 code 0x1 at 0xffffffff80016180 in clickhouse[10000+137af000]
[  361.076816] CPU: 0 PID: 3167 Comm: clickhouse Not tainted 6.1.0-7-riscv64 #1  Debian 6.1.20-1
[  361.078220] Hardware name: riscv-virtio,qemu (DT)
[  361.079163] epc : 000000000d87f8b6 ra : 000000000d87f878 sp : 00ffffffce43e820
[  361.080891]  gp : 000000001399d888 tp : 00ffffffbea3c780 t0 : 00ffffff800161c0
[  361.082941]  t1 : 00000000057db19c t2 : 0000000000000000 s0 : 00000000000000f0
[  361.085026]  s1 : 00ffffff60000000 a0 : ffffffff80016180 a1 : 0000000000030000
[  361.086458]  a2 : 0000000000000000 a3 : 00ffffff60010000 a4 : 00ffffff60010000
[  361.088158]  a5 : 00ffffff60010000 a6 : 0000000000000000 a7 : 00ffffff60000000
[  361.089689]  s2 : 00ffffffbea3c980 s3 : 000000000e073080 s4 : 00ffffffce43ec68
[  361.091433]  s5 : 00ffffffbea3c790 s6 : 000000000000ffff s7 : 00ffffff00000000
[  361.092908]  s8 : 00fffffff6363820 s9 : 00fffffff6363838 s10: 00aaaaaac82bfa4c
[  361.094654]  s11: 00aaaaaac82bf9c0 t3 : 00ffffffbeb2d7be t4 : 0000000000079594
[  361.095809]  t5 : 00ffffffce43c650 t6 : 0000000002f75a7c
[  361.096791] status: 8000000200006020 badaddr: ffffffff80016180 cause: 000000000000000d
Segmentation fault
```

AFAIR the error is in jemalloc, but I haven't checked this time.

**Comment by alexey-milovidov** [comment]
We've tested it on a real RISC-V machine, including ClickBench run.

I've also tested on QEMU, and found a couple of bugs (most likely in QEMU).

**Comment by alexey-milovidov** [comment]
Check this image instead: `docker run -it --rm riscv64/ubuntu`

Or you can use chroot instead of docker - just place a few .so, mount /proc, /dev, and /tmp, and put qemu-riscv64-static there.

**Comment by alexey-milovidov** [comment]
Just in case - let's try to link it with Musl, maybe you can help...

**Comment by azat** [comment]
>Check this image instead: docker run -it --rm riscv64/ubuntu

This is different, it is for riscv64 machine, not for amd64

```
$ docker run -it --rm riscv64/ubuntu
WARNING: The requested image's platform (linux/riscv64) does not match the detected host platform (linux/amd64/v3) and no specific platform was requested
exec /usr/bin/bash: exec format error
```

**Comment by alexey-milovidov** [comment]
@azat you need to register qemu-riscv64-static in the binfmt-misc kernel module.

**Comment by azat** [comment]
>@azat you need to register qemu-riscv64-static in the binfmt-misc kernel module.

@alexey-milovidov I don't get how this will help?
binfmt is just a way to execute binaries with different interpreter.
And even if I will do this, I sitll need some files for risvv64 (like libc)

So I used docker container, that has everything inside it, and run qemu-riscv64-system

Can you share how did you run binaries for riscv64 architecture?

**Comment by alexey-milovidov** [comment]
```
cd ~/work/ClickHouse/contrib/sysroot/linux-riscv64
sudo cp ~/work/ClickHouse/programs/server/clickhouse .
sudo cp /usr/bin/qemu-riscv64-static .
mkdir dev
head -c1000 /dev/urandom > dev/urandom
mkdir proc
sudo mount -t proc /proc proc/
mkdir tmp
sudo mount -t tmpfs /tmp tmp
sudo chroot . /qemu-riscv64-static /clickhouse
sudo chroot . /qemu-riscv64-static /clickhouse local --query "SELECT 1"
```

**Comment by azat** [comment]
Nice, thank you! Forgot that all libraries are there already.

But one more thing is required actually (to use binaries from CI artifacts) - https://github.com/ClickHouse/ClickHouse/pull/52138

**Pull request merged**
