### PR TITLE
perf: disable remap_executable to avoid iTLB multihit mitigation cost

### PR DESCRIPTION
**Pull request by azat**
Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Some CPUs is affected by iTLB multihit bug [1], and the cost to mitigate
it in software is page fault.

Since according to [1]:

    In order to mitigate the vulnerability, KVM initially marks all huge
    pages as non-executable. If the guest attempts to execute in one of
    those pages, the page is broken down into 4K pages, which are then
    marked executable

  [1]: https://www.kernel.org/doc/html/latest/admin-guide/hw-vuln/multihit.html

And in case of failures of prewarm queries I see lots of SoftPageFaults [2]:

    $ clickhouse-local --input-format TSVWithNamesAndTypes --file left-query-log.tsv --structure "$(cat left-query-log.tsv.columns | sed "s/\\\'/'/g")" -q "select query_id, ProfileEvents['SoftPageFaults'] from table where query_duration_ms >= 15e3 and query_id not like '%-%-%' /* uuid */"  | column -t
    trim_numbers.query5.prewarm0        486
    avg_weighted.query7.prewarm0        986
    great_circle_dist.query1.prewarm0   1292
    hashed_dictionary.query10.prewarm0  654664
    random_string.query1.prewarm0       10091
    array_fill.query4.prewarm0          341801
    window_functions.query5.prewarm0    46230

  [2]: https://clickhouse-test-reports.s3.yandex.net/30882/54c89e0f0e9b7b18ab40e755805c115a462a6669/performance_comparison/report.html#fail1

And yes, Intel Xeon Gold 6230R [3] is vulnerable to iTLB multihit [4].

  [3]: https://ark.intel.com/content/www/us/en/ark/products/192437/intel-xeon-gold-6230-processor-27-5m-cache-2-10-ghz.html
  [4]: https://openbenchmarking.org/s/Intel%20Xeon%20Gold%206230R

NOTE: that you should not look at openbenchmarking.org for "Intel Xeon E5-2660 v4" [5],
      since apparently lscpu was old, and bugs was not reported and hence parsed

  [5]: https://ark.intel.com/content/www/us/en/ark/products/91772/intel-xeon-processor-e52660-v4-35m-cache-2-00-ghz.html

Refs: #14685
Cc: @alexey-milovidov 
Refs: https://github.com/ClickHouse/ClickHouse/pull/31063#issuecomment-967793029

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
If it will help, we can remove "remap executable" at all.

**Comment by azat** [comment]
>If it will help, we can remove "remap executable" at all.

Agree, but this is just an attempt.
Also to be sure about this change perf tests need to be run on Intel Gold CPU.

**Comment by azat** [comment]
@mergify update (an attempt to run perf tests on Intel Xeon Gold CPU)

**Comment by azat** [comment]
>[Fast test — Cannot fetch submodules](https://clickhouse-test-reports.s3.yandex.net/31543/a642577597f62b960c96a768f98dbc1694f41207/fast_test/runlog.out.log)

```
2021-11-20 10:22:49 fatal: unable to access 'https://github.com/facebook/zstd.git/': The requested URL returned error: 503
2021-11-20 10:22:49 Fetched in submodule path 'contrib/zstd', but it did not contain a488ba114ec17ea1054b9057c26a046fc122b3b6. Direct fetching of that commit failed.
```

>Marker check — Fast Test has failed

Can someone add a force-test label please?

**Comment by azat** [comment]
@mergify update (an attempt to run perf tests on Intel Xeon Gold CPU)

**Comment by azat** [comment]
@mergify update (an attempt to run perf tests on Intel Xeon Gold CPU)

**Comment by azat** [comment]
Lots of failures in performance tests due to an issue, that had been fixed #31565

**Comment by azat** [comment]
@mergify update (an attempt to run perf tests on Intel Xeon Gold CPU)

**Comment by azat** [comment]
@mergifyio update (an attempt to run perf tests on Intel Xeon Gold CPU)

**Comment by azat** [comment]
>[Performance — 3 errors, 1 faster, 4 unstable](https://clickhouse-test-reports.s3.yandex.net/31543/85f51c50a307602c08411bad170145c45b158d59/performance_comparison/report.html#fail1)

Still an issue, `parallel_final.query5.prewarm0` fails with >15sec (note, that settings was applied for both servers since it was done via xml).

cpu|query_id|time
-|-|-
Gold [this PR](https://clickhouse-test-reports.s3.yandex.net/31543/85f51c50a307602c08411bad170145c45b158d59/performance_comparison/report.html#fail1)|parallel_final.query5.prewarm0|15251
E5 [some upstream](https://clickhouse-test-reports.s3.yandex.net/0/e5fba49947e1ec0e42f6ccc149af50b7c8109f72/performance_comparison/report.html)|parallel_final.query5.prewarm0|2172
Gold [30882](https://clickhouse-test-reports.s3.yandex.net/30882/54c89e0f0e9b7b18ab40e755805c115a462a6669/performance_comparison/report.html#fail1)|parallel_final.query5.prewarm0|3313

**Pull request closed without merging**
