### PR TITLE
Fix windowFunnel result with strict_increase

### LINKED ISSUE #21835: windowFunnel: same event gets counted twice
(you don't have to strictly follow this form)

**Describe the unexpected behaviour**
Test 1: running `windowFunnel` on different events without duplicate timestamp, it works well:
```sql
SELECT
    uid,
    windowFunnel(50)(toUInt32(event_ms), event_id = 1, event_id = 2) AS level
FROM
    (
    /* emulate test dataset */
    SELECT data.1 event_id, data.2  event_ms, data.3 uid
    FROM (
        SELECT arrayJoin(
        [(1, 100, 123),
        (1, 200, 345),
        (1, 210, 345),
        (2, 99, 123),
        (2, 250, 234),
        (2, 230, 345),
        (2, 240, 345)]) data)
    )
WHERE
    event_ms >= 0
    AND event_ms <= 300
GROUP BY
    uid;

Results:
┌─uid─┬─level─┐
│ 123 │     1 │
│ 234 │     0 │
│ 345 │     2 │
└─────┴───────┘
```

Test 2: running `windowFunnel` on different events with duplicate timestamp, it count unexpected event into result.
In this case, user 123 has event 1 and event 2 both happened at 100(event_ms), theoretically, it should not count this match because timestamp of event 2 is not greater than event 1.
```sql
SELECT
    uid,
    windowFunnel(50)(toUInt32(event_ms), event_id = 1, event_id = 2) AS level
FROM
    (
    /* emulate test dataset */
    SELECT data.1 event_id, data.2  event_ms, data.3 uid
    FROM (
        SELECT arrayJoin(
        [(1, 100, 123),
        (1, 200, 345),
        (1, 210, 345),
        (2, 100, 123),
        (2, 250, 234),
        (2, 230, 345),
        (2, 240, 345)]) data)
    )
WHERE
    event_ms >= 0
    AND event_ms <= 300
GROUP BY
    uid;

Results:
┌─uid─┬─level─┐
│ 123 │     2 │
│ 234 │     0 │
│ 345 │     2 │
└─────┴───────┘
```

Test 3: running `windowFunnel` on two same event count all events twice:
```sql
SELECT
    uid,
    windowFunnel(50)(toUInt32(event_ms), event_id = 1, event_id = 1) AS level
FROM
    (
    /* emulate test dataset */
    SELECT data.1 event_id, data.2  event_ms, data.3 uid
    FROM (
        SELECT arrayJoin(
        [(1, 100, 123),
        (1, 200, 345)]) data)
    )
WHERE
    event_ms >= 0
    AND event_ms <= 300
GROUP BY
    uid;

Results:
┌─uid─┬─level─┐
│ 123 │     2 │
│ 345 │     2 │
└─────┴───────┘
```

**How to reproduce**: run SQL query pasted above
* Which ClickHouse server version to use: 21.2.3.15
* Which interface to use, if matters
* Non-default settings, if any
* `CREATE TABLE` statements for all tables involved
* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary
* Queries to run that lead to unexpected result

**Expected behavior**
When searching for qualified event chain, it should satisfy: 
**timestamp of first event < timestamp of second event <= timestamp of first event + window**

I guess currently it follows:
timestamp of first event <= timestamp of second event <= timestamp of first event + window

With that, Test 2 will generate results:
```
┌─uid─┬─level─┐
│ 123 │     1 │
│ 234 │     0 │
│ 345 │     2 │
└─────┴───────┘
```

Test 3 will generate results:
```
┌─uid─┬─level─┐
│ 123 │     1 │
│ 345 │     1 │
└─────┴───────┘

```

**Error message and/or stacktrace**

**Additional context**

### PR DESCRIPTION
**Pull request by vdimir**
### Changelog category (leave one):

- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
* Fix `windowFunnel` result with strict_increase mode in case of several conditions holds for the same event, close https://github.com/ClickHouse/ClickHouse/issues/21835

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Run only fuzzers related jobs (libFuzzer fuzzers, AST fuzzers, etc.)
- [ ]  Exclude: AST fuzzers
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-ch-test-poll** [comment]
*This is an automated comment for commit 964446f0a1bede377fe49fcce29a38a186091faa with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/69302/964446f0a1bede377fe49fcce29a38a186091faa/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Style check</td><td>Runs a set of checks to keep the code style clean. If some of tests failed, see the related log from the report</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/69302/964446f0a1bede377fe49fcce29a38a186091faa/style_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Review by novikd — APPROVED** [review]
In general, LGTM, but I'd also recommend adding queries from the issue to the tests.

**Comment by novikd** [comment]
How is it compared to #69738?

**Comment by vdimir** [comment]
It addresses the same issue, but the current PR is only for `strict_increase`, while the other introduces a new mode that doesn't enable `strict_increase` behavior but counts each event only once. The difference is in how it handles multiple events with the same timestamp. Need to decide which patch to merge, or possibly both.

**Comment by UnamedRus** [comment]
Will it cover https://github.com/ClickHouse/ClickHouse/issues/52844 ?

**Comment by vdimir** [comment]
> Will it cover #52844 ?

@UnamedRus just checked, not this PR, but https://github.com/ClickHouse/ClickHouse/pull/69738 with enabling 'strict_once' return expected result for query from the first comment from that issue

**Pull request closed without merging**
