### PR TITLE
Support to run testcases on macOS

### PR DESCRIPTION
**Pull request by FrankChen021**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
`-v` option is not supported on macOS(Monterey 12.6, the latest) bash shell. 
To make sure the `clickhouse-test` launches the test case correctly,  replace `-v` with `-n` to check if an environment variable has been set.

### CODE REVIEW

**Comment by FrankChen021** [comment]
All fasttests and integration tests have passed. The failed stress test should have no relationship to changes in this PR.

**Comment by FrankChen021** [comment]
Hello @nikitamikhaylov Could you review this change?

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
I will help.

**Comment by FrankChen021** [comment]
Thank you @alexey-milovidov for the review.

**Pull request merged**
