### PR TITLE
Added reloading storage configuration from configuration file

### PR DESCRIPTION
**Pull request by excitoon**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- New Feature

Changelog entry (up to few sentences, required except for Non-significant/Documentation categories):

Added reloading storage configuration from configuration file.

### CODE REVIEW

**Comment by nvartolomei** [comment]
This is exciting. Can you share more about the intention here and what use cases you want to support? Ie. will it be possible to just remove a disk and ClickHouse will run part checks/repair for replicated tables and missing parts?

**Comment by alexey-milovidov** [comment]
@excitoon Any updates?

@nvartolomei 

> Ie. will it be possible to just remove a disk and ClickHouse will run part checks/repair for replicated tables and missing parts?

If parts are not available or not readable, ClickHouse will download them from replicas. Removing a disk and removing it from the configuration will work.

**Comment by alexey-milovidov** [comment]
boost::shared_ptr - looks strange.
Is the assignment operator atomic by default (it's unlikely)?
Why don't use MultiVersion as discussed?

**Comment by alexey-milovidov** [comment]
(rebased but boost::shared_ptr remains)

**Comment by excitoon** [comment]
@alexey-milovidov I did not use MultiVersion because `shared_ptr` looks simpler thing to me.

**Comment by BayoNet** [comment]
@excitoon 
Hello.
Could you explain how to use it?
Update storage config first and call SYSTEM UPDATE CONFIG then?
Are there some tricky things?

**Comment by alexey-milovidov** [comment]
@BayoNet The configuration will be updated automatically when user have changed the config file.

**Pull request merged**
