### PR TITLE
Update jemalloc to fix percpu_arena with affinity mask

### PR DESCRIPTION
**Pull request by azat**
Changelog category (leave one):
- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Update jemalloc to fix percpu_arena with affinity mask

Refs: #11084 (enables per-cpu arena)
Refs: #14957 (this fix was wrong)
Refs: #9516 (had been hit here for the first time, since `ThreadFuzzer.cpp` has `sched_setaffinity()`)
Refs: https://github.com/jemalloc/jemalloc/pull/1939 (upstream PR)

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]

**Comment by azat** [comment]
>Functional stateless tests (thread) — fail: 1, passed: 2270, skipped: 12


01502_jemalloc_percpu_arena | FAIL | 6.29
-- | -- | --

Does not looks related to this PR, but interesting, TSAN bails, should be fixed by #15061

**Comment by alexey-milovidov** [comment]
Merge with master and check again?

**Comment by azat** [comment]
>Merge with master and check again?

Still a problem, because PipelineExecutor does not call wait, since it does not use ThreadPool, it only check the state, anyway it is not related to this PR, and it will fail even w/o biding to specific CPU, affinity just makes test more reliable
Fix for this problem is here - #15177

**Comment by azat** [comment]
Initially I marked this PR as a draft since I want to get feedback from the maintainers.
However [looks like](https://github.com/jemalloc/jemalloc/pull/1939#issuecomment-703950546) they don't think that dynamic affinity is the generic case, and using always total number of CPU can cause some issues for [decay](http://jemalloc.net/jemalloc.3.html#opt.dirty_decay_ms) (but clickhouse does not uses this)

So now I see the following directions:
- don't bother about dynamic affinity, i.e. **close this PR**, but may cause troubles for ThreadFuzzer (#9516) and perf tests numa bind (#15144), so does not sounds like a good option to me 
- **merge this PR as-is**
- or **wait until another way will be found** (I have some ideas like `percpu_arena:percpu_all` and `percpu_arena:percpu_eligible`)

And also if merging this PR as-is will not be selected then #14957 also should be reverted (note that, that PR does not changes anything actually)

**Comment by alexey-milovidov** [comment]
We are going to enable ThreadFuzzer in CI as soon as it will find no more flaky tests - basically as soon as possible.

**Comment by alexey-milovidov** [comment]
I'm Ok with the changes - merge as is.

**Pull request merged**
