### PR TITLE
Lower memory usage after reading from `MergeTree` tables

### PR DESCRIPTION
**Pull request by CurtizJ**
### Changelog category (leave one):
- Performance Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Lower memory usage after reading from `MergeTree` tables

### CODE REVIEW

**Comment by CurtizJ** [comment]
I made a test with table with 100 parts and 30 columns by this [script](https://pastila.nl/?033848a9/bdef501622c119ddee8da50cc7d89abb#kZXRQ7Ei8IRRlkTLvuVHgQ==).

Memory usage for horizontal merge:
```sql
SELECT
    event_time,
    table,
    merge_algorithm,
    length(merged_from) AS num_source_parts,
    formatReadableSize(peak_memory_usage) AS memory_usage,
    formatReadableSize(bytes_uncompressed) AS bytes_uncompressed,
    formatReadableQuantity(rows) AS rows
FROM system.part_log
WHERE (table IN ('t_local_normal', 't_s3_normal')) AND (event_type = 'MergeParts') AND (part_name = 'all_1_100_1')
```

Before:
```
┌──────────event_time─┬─table───────┬─merge_algorithm─┬─num_source_parts─┬─memory_usage─┬─bytes_uncompressed─┬─rows──────────┐
│ 2024-01-27 16:24:46 │ t_s3_normal │ Horizontal      │              100 │ 9.10 GiB     │ 5.94 GiB           │ 10.00 million │
└─────────────────────┴─────────────┴─────────────────┴──────────────────┴──────────────┴────────────────────┴───────────────┘
┌──────────event_time─┬─table──────────┬─merge_algorithm─┬─num_source_parts─┬─memory_usage─┬─bytes_uncompressed─┬─rows──────────┐
│ 2024-01-27 16:21:17 │ t_local_normal │ Horizontal      │              100 │ 3.94 GiB     │ 5.94 GiB           │ 10.00 million │
└─────────────────────┴────────────────┴─────────────────┴──────────────────┴──────────────┴────────────────────┴───────────────┘
```

After:

```
┌──────────event_time─┬─table───────┬─merge_algorithm─┬─num_source_parts─┬─memory_usage─┬─bytes_uncompressed─┬─rows──────────┐
│ 2024-01-27 16:38:43 │ t_s3_normal │ Horizontal      │              100 │ 4.52 GiB     │ 5.94 GiB           │ 10.00 million │
└─────────────────────┴─────────────┴─────────────────┴──────────────────┴──────────────┴────────────────────┴───────────────┘
┌──────────event_time─┬─table──────────┬─merge_algorithm─┬─num_source_parts─┬─memory_usage─┬─bytes_uncompressed─┬─rows──────────┐
│ 2024-01-27 16:36:20 │ t_local_normal │ Horizontal      │              100 │ 3.05 GiB     │ 5.94 GiB           │ 10.00 million │
└─────────────────────┴────────────────┴─────────────────┴──────────────────┴──────────────┴────────────────────┴───────────────┘
```

**Comment by robot-ch-test-poll** [comment]
*This is an automated comment for commit 9d3b4e530810b2d05f62706a22062519ba18b30b with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/59290/9d3b4e530810b2d05f62706a22062519ba18b30b/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/59290/9d3b4e530810b2d05f62706a22062519ba18b30b/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alesapin** [comment]
Wow

**Comment by alexey-milovidov** [comment]
@CurtizJ, let's merge with master to run the perf tests again.

**Comment by CurtizJ** [comment]
Build failed with error  and was not restarted automatically. I think it's a bad practice to fail the whole build and restart it because of failure in optional functionality (send traces to ci logs cluster).
```
Notice: Log Uploading profile data, path: %s, size: %s, query: %s /home/ubuntu/actions-runner/_work/_temp/build_check/profile.json 126487744 INSERT INTO build_time_trace
            (
                pull_request_number,
                commit_sha,
                check_start_time,
                check_name,
                instance_type,
                instance_id,
                file,
                library,
                time,
                pid,
                tid,
                ph,
                ts,
                dur,
                cat,
                name,
                detail,
                count,
                avgMs,
                args_name
            )
            SELECT 59290, 'ef133bfd47f2466afeaeb3453483ab9a5dae2ea6', '2024-01-28 15:35:51', 'package_release', 'c5.9xlarge', 'i-0b3431840dd73e4f3', *
            FROM input('
                file String,
                library String,
                time DateTime64(6),
                pid UInt32,
                tid UInt32,
                ph String,
                ts UInt64,
                dur UInt64,
                cat String,
                name String,
                detail String,
                count UInt64,
                avgMs UInt64,
                args_name String')
            FORMAT JSONCompactEachRow
WARNING:root:Received exception while sending data to https://p12uiq1ogd.us-east-2.aws.clickhouse-staging.com/ on 0 attempt: ('Connection aborted.', TimeoutError('The write operation timed out'))
INFO:root:Response content 'b'Code: 27. DB::Exception: Cannot parse input: expected \'[\' before: \'e_compressor","build_docker/utils/self-extracting-executable/pre_compressor.time-trace",1706456510933517,590810,591010,"X",3360876,15775,null,"RunPass","Greedy \': (at row 1)\n: \nRow 1:\nERROR: There is no \'[\' before the row.\n\n: While executing ParallelParsingBlockInputFormat. (CANNOT_PARSE_INPUT_ASSERTION_FAILED) (version 24.0.2.54351 (official build))\n''
INFO:root:Request headers '{'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'X-ClickHouse-User': 'ci', 'X-ClickHouse-Key': '4HsJb8CKmF4o~', 'Content-Length': '116927680'}', body '<_io.BufferedReader name='/home/ubuntu/actions-runner/_work/_temp/build_check/profile.json'>'
Traceback (most recent call last):
  File "/home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/tests/ci/ci.py", line 1[197](https://github.com/ClickHouse/ClickHouse/actions/runs/7686606689/job/20946384815?pr=59290#step:9:198), in <module>
    sys.exit(main())
  File "/home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/tests/ci/ci.py", line 1047, in main
    _upload_build_profile_data(
  File "/home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/tests/ci/ci.py", line 748, in _upload_build_profile_data
    ch_helper.insert_file(url, auth, query, profile_data_file)
  File "/home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/tests/ci/clickhouse_helper.py", line 55, in insert_file
    ClickHouseHelper._insert_post(
  File "/home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/tests/ci/clickhouse_helper.py", line 106, in _insert_post
    raise InsertException(error)
clickhouse_helper.InsertException: Cannot insert data into clickhouse at try 1: HTTP code 400: 'Code: 27. DB::Exception: Cannot parse input: expected '[' before: 'e_compressor","build_docker/utils/self-extracting-executable/pre_compressor.time-trace",1706456510933517,590810,591010,"X",3360876,15775,null,"RunPass","Greedy ': (at row 1)
: 
Row 1:
ERROR: There is no '[' before the row.

: While executing ParallelParsingBlockInputFormat. (CANNOT_PARSE_INPUT_ASSERTION_FAILED) (version 24.0.2.54351 (official build))
```

**Comment by alexey-milovidov** [comment]
Performance tests ok.

**Pull request merged**
