### PR TITLE
Librdkafka v2.4.0 experimental build

### PR DESCRIPTION
**Pull request by ilejn**
Experimental build against librdkafka 2.4.0
Not supposed to be merged.

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by robot-ch-test-poll** [comment]
*This is an automated comment for commit 1257034528af2092dd88aa04fffb6bc4db49e39e with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/65314/1257034528af2092dd88aa04fffb6bc4db49e39e/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>A Sync</td><td>If it fails, ask a maintainer for help</td><td>⏳ pending</td></tr>
<tbody>
</table>
<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>Checks correctness of the PR's body</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

**Comment by alexey-milovidov** [comment]
@ilejn We found a failed test, and you are the author. Let's fix it before merging this PR: #66998

**Comment by alexey-milovidov** [comment]
@ilejn a test for LDAP has failed: https://s3.amazonaws.com/clickhouse-test-reports/70660/75916285535e3855b62ed481661613e3eef2fbe0/integration_tests__aarch64__[5_6].html

**Comment by filimonov** [comment]
https://github.com/confluentinc/librdkafka/issues/4782

**Pull request closed without merging**
