### PR TITLE
Added a check for storage policy in `cloneAndLoadDataPartOnSameDisk()`

### PR DESCRIPTION
**Pull request by excitoon**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Added a check for storage policy in `ATTACH PARTITION FROM`, `REPLACE PARTITION`, `MOVE TO TABLE` which could make data of part inaccessible after restart and prevent ClickHouse to start.

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
It's unclear what bug was fixed. Looks like an assertion for the internal logic in code.

**Comment by excitoon** [comment]
> It's unclear what bug was fixed. Looks like an assertion for the internal logic in code.

I've updated the comment.

**Comment by alexey-milovidov** [comment]
@excitoon Do you mean that it's not a LOGICAL_ERROR but a user related error?

**Comment by filimonov** [comment]
TableA on disk a, tableB on disk B.

`Alter table tableB attach partition from tableB`

It hardlinks the part from TableA to tableB folder on *disk a* and add a part to list of parts of tableB (maybe some guard /logical error should be fired when adding a part from bad disk). 

I think it rates to code preserving the original disk when do hardlink involving operation (was added to make mutation work).

**Comment by excitoon** [comment]
> @excitoon Do you mean that it's not a LOGICAL_ERROR but a user related error?

Changed to `BAD_ARGUMENTS`

**Pull request merged**
