### PR TITLE
Keeper optimization: use distance counter to substitute std::distance

### PR DESCRIPTION
**Pull request by zhanglistar**
Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
1. calling std::distance on large list will decrease performance, use a counter in Node to substitute.

Effect:
client command: `./utils/keeper-bench/keeper-bench --host=127.0.0.1:12183 -c 30 --generator=create_small_data`
new version:
image

master version 0e37e8b4a09dd6529452dbe767363e366b2a6c3d:
image

### CODE REVIEW

**Comment by alesapin** [comment]
@Mergifyio update

**Comment by alesapin** [comment]
@zhanglistar push some commit (even empty) in this branch, our `can be tested` broken again....

**Review by alesapin — COMMENTED** [review]
But what about erases? We can remove element from list and `distance_from_begin` should be changed for all following elements?

**Comment by zhanglistar** [comment]
> 

Oh, yes, one way is that traversing the list to update counter. What about lazy delete in `clearOutdatedNodes`? I will submit the code.

**Comment by alesapin** [comment]
But it should finish before the next snapshot is ready.

**Comment by zhanglistar** [comment]
> > 
> 
> Oh, yes, one way is that traversing the list to update counter. What about lazy delete in `clearOutdatedNodes`? I will submit the code.

The deleted elements are truly erased in `clearOutdatedNodes()`, that satisfies?

**Comment by zhanglistar** [comment]
> But it should finish before the next snapshot is ready to start.

The deleted elements are truly erased in clearOutdatedNodes(), that satisfies?

**Comment by zhanglistar** [comment]
@alesapin  What about rollback snapshot_up_to_size feature? It seems that there is not a high performance way to do because of snapshot_up_to_size feature, we can just copy the element, I think that's faster, and free the elements after snapshot done, as clearOutdatedNodes can be very fast.

**Comment by alesapin** [comment]
> 

Have you tested it? Maybe it make sense to replace list with deque, so `std::distance` will be much faster?

**Comment by zhanglistar** [comment]
> @zhanglistar
> 
> Have you tested it? Maybe it make sense to replace list with deque, so `std::distance` will be much faster? If nothing helps let's rollback.

@alesapin  I saw that traversing a 1000w list costs time more than 1s, which will hang the normal processing. I will try to use std::deque to see the performance.

**Comment by zhanglistar** [comment]
@alesapin std::deque performs much better than std::list, so there is no need to do any further optimization using std::deque instead of std::list, but I found that there is undefined behavior, still working on it.

**Comment by zhanglistar** [comment]
The main design here:

Question:
Keeper uses a list to store all data, but it will traverse the linked list during `clearOutdatedNodes`. If there are tens of millions of linked lists, it will reach the second level, resulting in a large number of client timeouts.

Design objectives:
1. The capacity can support tens of millions of nodes or billion nodes
2. millisecond snapshots
3. It will not reduce the existing read and write performance

Design:
The list is append only. Intermediate nodes are not allowed to be modified.
Maintain the number of invalid nodes invalid_ node_ counter.
Some change to the existing data storage design: Value in Node changes to shared_ptr to reduce memcopy.

General operation:
1. Insert: the linked list only performs tail insertion, that is, append only. 
2. Erase, delete with a mark, and insert a new node at the end. invalide_ node_ counte++
3. InsertOrReplace: if the node exists, insert a new node at the end and mark to delete the existing node. invalide_ node_ counter++
4. UpdateValue, insert the updated value node at the end, and mark to delete the existing node. invalide_ node_ counter++
This may lead to a large number of value copy processes. Note that the value in the node of the linked list is changed to shared pointer.

Compaction processure:
Start an independent thread to do compaction, which is used to sort out the linked list within the range of start and end.
compact(iterator start, iterator end); The implementation is to traverse the linked list in the range of start and end and delete invalid nodes. It is only thread to modify the existing list nodes.
The trigger condition is when the chain example reaches invalid_ node_ counter/total_ nodes. When the count reaches a certain threshold, you can configure the default 3% or other value to keeper the memory not use too much.
It can also be triggered actively in the main thread to communicate messages through the queue.

Snapshot process:
Need to lock first (the current implementation is external locking, that's also OK) when doing snapshot (list. Size() - invalid)_ node_ After counter), provide the `nextIter` method, skip the invalid node, and the snapshot size is list size() - invalide_ node_ counter.
Since there is no modify list, just appending it, so there is no need to use a snapshotmode flag to indicate that we are in a snapshot. And there is also no sync clearOutdatedNode to block the whole processing. It should perform very well.

**Pull request closed without merging**
