### PR TITLE
support mysql,postgresql handler outputformat nullable column as its nestedtype

### PR DESCRIPTION
**Pull request by anneji-dev**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
support mysql,postgresql handler outputformat nullable column as its nestedtype

### CODE REVIEW

**Review by vdimir — COMMENTED** [review]
Thank you for your PR!

Could you please explain what behavior do we expect before and after the change? Was it just unsupported or produced unexpected result?

Also it's good to add some test it will help to understand as well.

**Comment by anneji-dev** [comment]
@vdimir This fix is very straight-forwad but the testing is not. I don't find an easy way to test the output types of mysql/postgresql wire-protocol. @kssenii Could you help take a look?

**Comment by kssenii** [comment]
@Mergifyio update

**Comment by kssenii** [comment]
>  I don't find an easy way to test the output types of mysql/postgresql wire-protocol. @kssenii Could you help take a look?

I think the test is easy to add, see example here https://github.com/ClickHouse/ClickHouse/blob/master/tests/queries/0_stateless/01889_postgresql_protocol_null_fields.sh and https://github.com/ClickHouse/ClickHouse/blob/master/tests/queries/0_stateless/02009_mysql_client_empty_result.sh

**Comment by anneji-dev** [comment]
I understand,for example,create table t1(c1 float null)..,insert t1 values(1.1), select c1 from t1, c1 column output type should be float, not be string，but ，It is difficult to express the difference between float and string，it result is same

**Comment by kssenii** [comment]
Does this https://github.com/ClickHouse/ClickHouse/blob/master/tests/integration/test_postgresql_protocol/test.py#L196-L211 help?

**Pull request closed without merging**
