### PR TITLE
Fix CaresPTRResolver not reading hosts file

### LINKED ISSUE #40595: 22.8.2 version   users.xml <host_regexp> abnormal
> Make sure to check documentation https://clickhouse.com/docs/en/ first. If the question is concise and probably has a short answer, asking it in Telegram chat https://telegram.me/clickhouse_en is probably the fastest way to find the answer. For more complicated questions, consider asking them on StackOverflow with "clickhouse" tag https://stackoverflow.com/questions/tagged/clickhouse 

> If you still prefer GitHub issues, remove all this text and ask your question here.

`            <networks incl="networks" replace="replace">
                <ip>127.0.0.1</ip>
                <host_regexp>^abc00[1-6]$</host_regexp>
            </networks>
`
`clickhouse-client --host abc003
ClickHouse client version 22.8.2.11 (official build).
Connecting to abc003:9000 as user default.

If you have installed ClickHouse and forgot password you can reset it in the configuration file.
The password for default user is typically located at /etc/clickhouse-server/users.d/default-password.xml
and deleting this file will reset the password.
See also /etc/clickhouse-server/users.xml on the server where ClickHouse is installed.

Code: 516. DB::Exception: Received from abc003:9000. DB::Exception: default: Authentication failed: password is incorrect or there is no user with such name. (AUTHENTICATION_FAILED)`

`if use <host> no problem`

### PR DESCRIPTION
**Pull request by arthurpassos**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in official stable or prestable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
In #40595 it was reported that the `host_regexp` functionality was not working properly with a name to address resolution in `/etc/hosts`. It's fixed.

### Details:
The existing CaresPTRResolver implementation checks only for the ptr records in `hostent::h_aliases`, which is filled by `c-ares` whenever one or multiple PTR records are returned from the DNS server. The caveat is that `c-ares` file resolution fills out `hostent::h_name` and leaves `hostent::h_aliases` empty. The solution is to read both members of the `hostent` returned structure. An unordered_set is used to prevent duplicates (`h_name` usually contains the same value as the first entry of `h_aliases`).

The interface was adapted and now an `unordered_set` is being returned. With the overhead of a linear copy, the `vector` interface could be preserved. Leaving it on the table and open for discussion.

Closes #40595 

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by tavplubix** [comment]
Please update the changelog entry, it must be user-readable and must describe how changes affect user-visible behavior (e.g. what bug is fixed)

**Review by tavplubix — APPROVED** [review]

**Comment by arthurpassos** [comment]
Hold off the merge a bit, I need to run the tests to make sure they are working

**Comment by tavplubix** [comment]
Of course we will wait for tests to pass before merging

**Comment by arthurpassos** [comment]
@tavplubix I think CI needs a re-run

**Comment by tavplubix** [comment]
In most cases CI re-runs automatically. If it does not then you can trigger it by pushing empty commit or merging master into your branch (unless some CI-related code is changed, in this case manual approval is required)

**Comment by tavplubix** [comment]
Stress tests - real OOMs in dmesg, unrelated

Let's merge?

**Comment by arthurpassos** [comment]
> Stress tests - real OOMs in dmesg, unrelated
> 
> Let's merge?

Yes, I think we are good to go!

**Pull request merged**
