### PR TITLE
Update the AMI receipt

### PR DESCRIPTION
**Pull request by Felixoid**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Updated the runner version; installed azure-cli; improved the user-data AKA cloud-init script deployment.

### CODE REVIEW

**Comment by robot-ch-test-poll** [comment]
*This is an automated comment for commit d786f76b9a5607c784bc991e4bb60383e0defba3 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/56459/d786f76b9a5607c784bc991e4bb60383e0defba3/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td><a href="https://github.com/ClickHouse/ClickHouse/actions/runs/6798460271">✅ success</a></td></tr>
<tbody>
</table>
</details>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/56459/d786f76b9a5607c784bc991e4bb60383e0defba3/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Comment by Felixoid** [comment]
@nikitamikhaylov while we're here, is there anything else needed for the infrastructure?

**Review by nikitamikhaylov — APPROVED** [review]

**Comment by Felixoid** [comment]
TODO: kill spot instance between runs on uptime > 1h

**Comment by Felixoid** [comment]
It's deployed successfully.

**Pull request merged**
