### PR TITLE
Add table_uuid to system.parts

### PR DESCRIPTION
**Pull request by azat**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Add table_uuid to system.parts

Can be useful if the table constantly recreated, i.e. in some tests.

### CODE REVIEW

**Review by kssenii — APPROVED** [review]

**Comment by kssenii** [comment]
seems like a new test is a bit flaky, probably need an order by

**Comment by azat** [comment]
>seems like a new test is a bit flaky, probably need an order by

Yep. Indeed. Fixed.

**Comment by kssenii** [comment]
> Stateless tests (tsan) [4/5] — fail: 1,

01072_window_view_multiple_columns_groupby

> Integration tests (tsan) [1/6] — fail: 1

test_grpc_protocol_ssl/test.py::test_secure_channel

> Integration tests (release) [3/4] — fail: 1

test_broken_detached_part_clean_up/test.py::test_store_cleanup

**Comment by tavplubix** [comment]
@kssenii, it could not be merged with failed Stateless tests flaky check (asan)

**Pull request merged**
