### PR TITLE
New allocator interface

### PR DESCRIPTION
**Pull request by myrrc**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):

New Feature

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Implemented a new IGrabberAllocator interface representing a combination of an allocator and a domain-specific cache. Integrated it into MarkCache, UncompressedCache.

TODO
 - [x] Throw POCO Exception on max_cache_size < MinChunkSize
 - [x] Update IGrabberAllocator with MemoryTracker usage.
 - [x] Write more tests
 - [ ]  (Optional) Update Allocator.
 - [ ] (Optional) Add insert attempts priority queue for full used cache.
 - [ ] (Optional) Change reset() semantics to invalidate used elements.

Detailed description / Documentation draft:

Can be found as Doxygen comments in the changed file.

Note: the commit history needs squashing.

### CODE REVIEW

**Comment by myrrc** [comment]
Help needed due to [server failing](https://clickhouse-test-reports.s3.yandex.net/10950/4dedcdc623db906efd7a833de1bd1c42be5dad5a/stress_test_logs/test_output/stderr.log) in stress test.

1) Allocating new RegionMetadata.create() **<- returning shared_ptr on request**

```
#1 0x196f7b4a in DB::IGrabberAllocator::RegionMetadata::create() /build/obj-x86_64-linux-gnu/../src/Common/Allocators/IGrabberAllocator.h:785:65

#5 0x196ef80b in DB::MergeTreeMarksLoader::loadMarks() 
```
2) Calling reset(). All MemoryChunks are unmapped, shared_ptr's becoming invalid.

 ```  
 #4 0x17cf0b46 in DB::IGrabberAllocator::reset() /build/obj-x86_64-linux-gnu/../src/Common/Allocators/IGrabberAllocator.h:210:21
    #5 0x17cd5953 in DB::Context::dropCaches() const /build/obj-x86_64-linux-gnu/../src/Interpreters/Context.cpp:1315:29
```

3) On first active shared_ptr delete getting an error (in fact, it could also happen on shared_ptr's .get() pointing to freed memory.

 ```
**Value * points to freed memory.**
#0 0x196f5962 in DB::IGrabberAllocator<DB::UInt128, DB::CacheMarksInCompressedFile, DB::UInt128TrivialHash, ga::Runtime, ga::Runtime, AllocatorsASLR, 67108864ul, 16ul>::onValueDelete(DB::CacheMarksInCompressedFile*) /build/obj-x86_64-linux-gnu/../src/Common/Allocators/IGrabberAllocator.h:527:9
# 4 0x196fd105 in std::__1::__shared_ptr_pointer<DB::CacheMarksInCompressedFile*, std::__1::__bind<void (DB::IGrabberAllocator<DB::UInt128, DB::CacheMarksInCompressedFile, DB::UInt128TrivialHash, ga::Runtime, ga::Runtime, AllocatorsASLR, 67108864ul, 16ul>::*)(DB::CacheMarksInCompressedFile*), DB::IGrabberAllocator<DB::UInt128, DB::CacheMarksInCompressedFile, DB::UInt128TrivialHash, ga::Runtime, ga::Runtime, AllocatorsASLR, 67108864ul, 16ul>*, std::__1::placeholders::__ph<1> const&>, std::__1::allocator<DB::CacheMarksInCompressedFile> >::__on_zero_shared() /build/obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:3536:5\```

So we can either throw on IGrabberAllocator::reset() (handling it e.g. in Context.cpp::dropCaches(), and similar) or track some `bool is_disposed` for each Value (but that seems a bad idea as for me).

**Comment by alexey-milovidov** [comment]
> Calling reset(). All MemoryChunks are unmapped, shared_ptr's becoming invalid.

`reset` should leave currently in-use elements in cache.

Note: this may lead to trouble, because cache won't be 100% invalidated when it was requested by `reset` method. But that's another story, let's postpone it later.

**Comment by myrrc** [comment]
> > Calling reset(). All MemoryChunks are unmapped, shared_ptr's becoming invalid.
> 
> `reset` should leave currently in-use elements in cache.
> 
> Note: this may lead to trouble, because cache won't be 100% invalidated when it was requested by `reset` method. But that's another story, let's postpone it later.

So, after discussion, two changes are proposed:

- ` void shrinkToFit()`, which (similarly to `std::vector::shrink_to_fit`) removes all unused elements from the cache, which includes unused (unreferenced) regions and allocated but unused memory chunks.

-  `void reset()`, which completely invalidates the cache. RegionMetadata should hold bool is_disposed, the get() and getOrSet() methods would become more complex.

The current implementation would change reset() to act like shrinkToFit()

**Comment by Akazz** [comment]
Quite a work has been done here thanks to you, @myrrc! And yet there is more to be done to make this implementation work. Thus we better suspend work on this PR until later.

**Pull request closed without merging**
