### PR TITLE
Add function "normalizeQuery"

### LINKED ISSUE #11271: Query normalization and hashing functions.
Provide a function to replace literals and lists of literals in SQL query to question marks.
Provide a function to calculate a hash of query structure without the values of literals.

Example:
`SELECT count(*) FROM table WHERE date = '2020-01-02' AND id IN (1, 2, 3) LIMIT 10, 10`
should be replaced to
`SELECT count(*) FROM table WHERE date = ? AND id IN (?) LIMIT ?`

The function should be database agnostic: it should work for ClickHouse queries as well as MySQL queries.

Why do we need this feature.
1. We will extract all unique queries from our production machines for testing.
2. These functions will be useful for various monitoring and performance tools*.

\* ClickHouse is already used as main database in multiple popular tools to analyze performance of SQL queries in MySQL, Postgres.

### PR DESCRIPTION
**Pull request by alexey-milovidov**
Changelog category (leave one):
- New Feature

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Add function `normalizeQuery` that replaces literals, sequences of literals and complex aliases with placeholders. Add function `normalizedQueryHash` that returns identical 64bit hash values for similar queries. It helps to analyze query log. This closes #11271.

PS. The name `queryHash` is rejected because it can be mixed up with URL processing functions. That's why `normalizeQuery` was preffered over `queryNormalize`.

### CODE REVIEW

**Comment by amosbird** [comment]
Is it possible to extend the function (some variant) to cover this https://github.com/ClickHouse/ClickHouse/pull/8367 ?

**Comment by alexey-milovidov** [comment]
Answered in that task.

**Comment by filimonov** [comment]
If it's not too costy - may be we can calc query_hash in advance and put it into query_log?

**Comment by alexey-milovidov** [comment]
It's in order of 200..300 MB/sec/core - more than enough.
Yes, it's a good idea to put it in query log.

**Pull request merged**
