### PR TITLE
Revert "ClickHouse's boringssl module updated to the official version of the FIPS compliant."

### PR DESCRIPTION
**Pull request by alexey-milovidov**
Reverts ClickHouse/ClickHouse#35914

### CODE REVIEW

**Comment by larryluogit** [comment]
@yakov-olkhovskiy a boringssl version change has to be reverted due to a regression.
structure x509_st that FunctionShowCertificate depends on were moved to internal in the newer boringssl version. As a result, this revert pr failed to build. Do you have any suggestions how to address this issue?

**Comment by yakov-olkhovskiy** [comment]
@larryluogit as Alexey mentioned new API contains corresponding functions now - for example X509 serialNumber:
https://www.openssl.org/docs/man1.1.1/man3/X509_get_serialNumber.html

**Comment by alexey-milovidov** [comment]
@mergifyio update

**Comment by larryluogit** [comment]
@alexey-milovidov Can this be back ported to 22.6 and 22.5 please?

**Comment by filimonov** [comment]
Reverted because fips-compatible boringssl does not support TLS 1.3. 
See the test: https://github.com/ClickHouse/ClickHouse/pull/38355

Detailed commend about TLS 1.3 status in boringssl https://kupczynski.info/posts/fips-golang/#boringcrypto-fips-and-tls-13

**Pull request merged**
