### PR TITLE
Fix optimization in PartialSortingTransform (SIGSEGV and possible incorrect result)

### PR DESCRIPTION
**Pull request by azat**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in official stable or prestable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix optimization in PartialSortingTransform (SIGSEGV and possible incorrect result)

Fixes: #37992 (cc @kitaisreal)

### CODE REVIEW

**Review by kitaisreal — APPROVED** [review]

**Comment by tavplubix** [comment]
@kitaisreal, you forgot to take a look at failed tests before merging

**Comment by azat** [comment]
@tavplubix why this has been reverted? In other words what of the test failures had been introduced by this patch?

**Comment by tavplubix** [comment]
> @tavplubix why this has been reverted? In other words what of the test failures had been introduced by this patch?

Just take a look at failed tests and you will see that it breaks Stress Tests

**Comment by kitaisreal** [comment]
In stress tests only backward compatibility check is broken.
For example https://s3.amazonaws.com/clickhouse-test-reports/38324/9db64952c0630bcd09d416499b0c88e38057337c/stress_test__debug__actions_.html.
In gdb we see that there is crash because of columns type mismatch:
```
2022-06-23 01:09:40 Thread 264 "QueryPullPipeEx" received signal SIGSEGV, Segmentation fault.
2022-06-23 01:09:40 [Switching to Thread 0x7f7155b6b700 (LWP 28987)]
2022-06-23 01:09:40 DB::ColumnNullable::isNullAt (this=0x7f71e041ea20, n=0) at ../src/Columns/ColumnNullable.h:56
2022-06-23 01:09:43 Saved corefile core.28692
2022-06-23 01:09:43 #0  DB::ColumnNullable::isNullAt (this=0x7f71e041ea20, n=0) at ../src/Columns/ColumnNullable.h:56
2022-06-23 01:09:43 No locals.
2022-06-23 01:09:43 #1  DB::ColumnNullable::compareAtImpl (this=0x7f71e041e9a0, n=1499, m=0, rhs_=..., null_direction_hint=-1, collator=0x0) at ../src/Columns/ColumnNullable.cpp:320
2022-06-23 01:09:43         nullable_rhs = @0x7f71e041ea20: {<COWHelper<DB::IColumn, DB::ColumnNullable>> = {<DB::IColumn> = {<COW<DB::IColumn>> = {<boost::sp_adl_block::intrusive_ref_counter<DB::IColumn, boost::sp_adl_block::thread_safe_counter>> = {m_ref_counter = {value_ = 1}}, <No data fields>}, _vptr$IColumn = 0x7a742b8 <vtable for DB::ColumnConst+16>}, <No data fields>}, nested_column = {value = {<boost::intrusive_ptr<DB::IColumn const>> = {px = 0x7f714d75f9f0}, <No data fields>}}, null_map = {value = {<boost::intrusive_ptr<DB::IColumn const>> = {px = 0x1}, <No data fields>}}}
2022-06-23 01:09:43         nested_rhs = <optimized out>
2022-06-23 01:09:43         lval_is_null = <optimized out>
2022-06-23 01:09:43         rval_is_null = <optimized out>
2022-06-23 01:09:43 #2  DB::ColumnNullable::compareAt (this=0x7f71e041e9a0, n=1499, m=0, rhs_=..., null_direction_hint=-1) at ../src/Columns/ColumnNullable.cpp:339
2022-06-23 01:09:43 No locals.
2022-06-23 01:09:43 #3  0x000000001739b0c3 in DB::(anonymous namespace)::compareWithThreshold (raw_block_columns=..., min_block_index=1499, threshold_columns=..., sort_description=...) at ../src/Processors/Transforms/PartialSortingTransform.cpp:74
```
In clickhouse-server.backward.stress.log https://s3.amazonaws.com/clickhouse-test-reports/38324/9db64952c0630bcd09d416499b0c88e38057337c/stress_test__debug__actions_/clickhouse-server.backward.stress.log wee see it is because of this query run.
```
2022.06.23 01:09:32.232505 [ 28695 ] {} <Debug> TCP-Session: 640e82e5-982e-4950-a33c-5cbf30a919bf Creating query context from session context, user_id: 94309d50-4f52-5250-31bd-74fecac179db, parent context user: default
2022.06.23 01:09:32.232810 [ 28695 ] {5a706641-0838-4e7b-a782-f075d6c8814c} <Debug> executeQuery: (from [::1]:51310) (comment: 02345_partial_sort_transform_optimization.sql) -- Regression for PartialSortingTransform optimization
 -- that requires at least 1500 rows.
 select * from (select * from (select 0 a, toNullable(number) b, toString(number) c from numbers(1e6)) order by a desc, b desc, c limit 1500) limit 10; (stage: Complete)
```
It seems that we try to run test 02345_partial_sort_transform_optimization.sql for old ClickHouse version, and it crash it.

**Comment by azat** [comment]
So, simply `no-backward-compatibility-check` is missing.

**Pull request merged**
