### PR TITLE
Fix incorrect ThreadPool usage after ThreadPool introspection

### PR DESCRIPTION
**Pull request by azat**
```
$ gg 'ThreadPool[^()]([A-Za-z_]\+,' src/
src/Interpreters/Context.cpp:        shared->load_marks_threadpool = std::make_unique<ThreadPool>(pool_size, pool_size, queue_size);
src/Interpreters/Context.cpp:        shared->prefetch_threadpool = std::make_unique<ThreadPool>(pool_size, pool_size, queue_size);
src/Interpreters/Context.cpp:        shared->threadpool_writer = std::make_unique<ThreadPool>(pool_size, pool_size, queue_size);
```

Fixes: #47880
Closes: #48234

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by tavplubix** [comment]
Do we have other incorrect usages? Let's make the compiler find them (it's okay to to in a separate PR)

**Review by tavplubix — APPROVED** [review]

**Comment by tavplubix** [comment]
Style check is broken in master, so it's impossible to merge anything...

**Comment by azat** [comment]
>Do we have other incorrect usages? Let's make the compiler find them (it's okay to to in a separate PR)

The problem is that before #47880 there was the following ctor:

```c
ThreadPoolImpl(
    size_t max_threads_,
    size_t max_free_threads_,
    size_t queue_size_,
    bool shutdown_on_exception_ = true);
```

After:

```c
explicit ThreadPoolImpl(
    Metric metric_threads_,
    Metric metric_active_threads_,
    size_t max_threads_);

ThreadPoolImpl(
    Metric metric_threads_,
    Metric metric_active_threads_,
    size_t max_threads_,
    size_t max_free_threads_,
    size_t queue_size_,
    bool shutdown_on_exception_ = true);
```

And `Metric` is `size_t`, so compiler does not show any error when `max_threads, max_free_threads, queue_size` was passed as `metric_threads, metric_active_threads, max_threads`

**Comment by azat** [comment]
Yep, seems that this helps - https://s3.amazonaws.com/clickhouse-test-reports/0/46e85357ce2da2a99f56ee83a079e892d7ec3726/stress_test__asan_.html

**Comment by azat** [comment]
@tavplubix yeah, I thought about this, but this will require recompile lots of stuff, so decided to postpone this, anyway here is a PR, that uncovers another, last, bug - #48314

**Pull request merged**
