### PR TITLE
Improvement #53156: Rewrite formatReadableTimeDelta to support smaller units and range of units

### PR DESCRIPTION
**Pull request by hanickadot**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
`FormatReadableTimeDelta` now supports smaller duration units and also it can specify range of units to used for formatting.

### Documentation entry for user-facing changes
- [ ] Documentation is written (mandatory for new features)

### CODE REVIEW

**Comment by UnamedRus** [comment]
What if also have `micro`/`milli`/`nano` aliases?

**Comment by robot-ch-test-poll3** [comment]
This is an automated comment for commit e7677ab9f7a77959d5ab0072c2af01e4a0a0176e with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/54046/e7677ab9f7a77959d5ab0072c2af01e4a0a0176e/ci_running.html)
The overall status of the commit is 🔴 failure

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🔴 failure</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Comment by KochetovNicolai** [comment]
@hanickadot `01521_format_readable_time_delta` tests failed, see [the report](https://s3.amazonaws.com/clickhouse-test-reports/54046/a82408bc02b6515300880bce5369cf20882e337f/fast_test.html).

Could you, please, also add some similar tests for the new functionality?

**Comment by KochetovNicolai** [comment]
It's in `tests/queries/0_stateless`
https://github.com/ClickHouse/ClickHouse/blob/571abfd41ea87fc9599709a95af660d0977644bd/tests/queries/0_stateless/01511_format_readable_timedelta.sql#L1
https://github.com/ClickHouse/ClickHouse/blob/571abfd41ea87fc9599709a95af660d0977644bd/tests/queries/0_stateless/01521_format_readable_time_delta2.sql#L1

**Comment by alexey-milovidov** [comment]
Superseded by #54250.

**Pull request closed without merging**
