### PR TITLE
[RFC] Skip leading comments in query (mostly for tests)

### PR DESCRIPTION
**Pull request by azat**
That way you know exact query to look for in system.query_log, though it will adjust the behaviour of echo mode, and maybe it is not welcome, thoughts?

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by robot-ch-test-poll1** [comment]
*This is an automated comment for commit 199fd363c5923d2fc1523b491ef0b94a5021a016 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/59185/199fd363c5923d2fc1523b491ef0b94a5021a016/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/59185/199fd363c5923d2fc1523b491ef0b94a5021a016/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Comment by Algunenano** [comment]
In some cases we are actually using the comment prior to the query to find it in the query_log. Not sure how many places there are and if it's possible/easy to adjust them.

**Comment by azat** [comment]
The main motivation was that it was very annoying to see multiline queries for test like this:

```sql
-- Tags: foobar
select 1;
```

It will have `-- Tags: foobar
select 1;` in query log, and there is no way you can avoid this, even new line will not help, since it is also skipped.

I posted this as a real RFC, to get some feedback on it.

If you feel same way than I will convert the rest and also I need to fix `-- { echo }` (since now client don't simply see it because it is trimmed).

> In some cases we are actually using the comment prior to the query to find it in the query_log. Not sure how many places there are and if it's possible/easy to adjust them.

There are around 17 test cases I guess

```
$ gg "query.*'--" tests/queries/0_stateless/ | cut -d: -f1 | sort -u | wc -l
17
```

But they could be converted to either use `log_comment` or move the comment to the end of the query, or we can avoid trimming comments for queries like this `/* foo */ select 1`

**Comment by Algunenano** [comment]
The problem I saw is with something like:

file.sql (for .sh it's easier to define query_id based on the log test name):
```sql
-- LongQuery1
Select "AAAAAAAAAAAAAAAA1"; -- Just simulating a long query

-- LongQuery2
Select "AAAAAAAAAAAAAAAA2"; -- Just simulating a long query slightly different from 1


Select * from system.query_log where event_date >= yesterday() and database = currentDatabase() and query like 'LongQuery2%';
```

I didn't know it was  possible to set the log_comment in the query itself (`SETTING log_comment='LongQuery2'`) and that would fix it too and make things clearer, so LGTM.

**Comment by UnamedRus** [comment]
People use comments to populate queries with some context.

Unconditionally forcing them to use `log_comment` doesn't looks nice. (can it be done under setting, like for query max length?)

**Comment by azat** [comment]
Using comments to distinguish queries in the query_log is a bad idea (even I did not use this...), I thought/hoped that it was using only in tests, do you know lots of such cases? Can you give some more details on them?

Making this under setting does not make sense either, it is just all too specific, I would prefer not to do this in this case.

**Comment by UnamedRus** [comment]
Yes, i know companies which do that.

For example, even metabase do that https://github.com/metabase/metabase/issues/28865

> Using comments to distinguish queries in the query_log is a bad idea

Well, it's not like standard SQL gives you a lot of options here.

**Comment by azat** [comment]
>Well, it's not like standard SQL gives you a lot of options here

There are better alternatives in ClickHouse - `log_comment`.

But, anyway, since looks like nobody interested in this, and it is questionable at least to someone, then let's simply close it.

**Pull request closed without merging**
