### PR TITLE
Merging #21330

### PR DESCRIPTION
**Pull request by kitaisreal**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- New Feature

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Added function accurateCastOrDefault(x, T). Closes #21330. Authors @taiyang-li.

### CODE REVIEW

**Comment by qoega** [comment]
`SELECT toDateTime64OrDefault(NULL);`  - > Segmentation fault (11)

**Comment by taiyang-li** [comment]
> `SELECT toDateTime64OrDefault(NULL);` - > Segmentation fault (11)

I would try to solve it.

**Comment by alexey-milovidov** [comment]
Ok, you can merge this PR into your PR and continue...

**Comment by kitaisreal** [comment]
@taiyang-li please sign in cla.

**Pull request merged**
