### PR TITLE
Add test cases to 03217_datetime64_constant_to_ast

### PR DESCRIPTION
**Pull request by vdimir**
### Changelog category (leave one):

- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
...

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [x]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-ch-test-poll3** [comment]
*This is an automated comment for commit ef40cc3baec8fdfc762aacc503e29f742b31683b with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/67966/ef40cc3baec8fdfc762aacc503e29f742b31683b/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Style check</td><td>Runs a set of checks to keep the code style clean. If some of tests failed, see the related log from the report</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/67966/ef40cc3baec8fdfc762aacc503e29f742b31683b/style_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Comment by vdimir** [comment]
TODO: check on different versions

**Review by rschu1ze — APPROVED** [review]

**Comment by vdimir** [comment]
> Stateless tests (release, old analyzer, s3, DatabaseReplicated) [4/4] — fail: 1, passed: 1657, skipped: 30 [Details](https://s3.amazonaws.com/clickhouse-test-reports/67966/ef40cc3baec8fdfc762aacc503e29f742b31683b/stateless_tests__release__old_analyzer__s3__databasereplicated__[4_4].html)

https://github.com/ClickHouse/ClickHouse/issues/68055

**Comment by vdimir** [comment]
> Stateless tests (debug, s3 storage) [1/2] — fail: 1, passed: 3358, skipped: 77 [Details](https://s3.amazonaws.com/clickhouse-test-reports/67966/64e10b2dda076cd5122d7db9642ed98376bde14a/stateless_tests__debug__s3_storage__[1_2].html)

Fixing in https://github.com/ClickHouse/ClickHouse/pull/68325

**Pull request merged**
