### PR TITLE
Fix dictGet arguments check during GROUP BY injective functions elimination

### LINKED ISSUE #11469: 20.4 + dictGet + group by = Function dictGet... takes 3 or 4 arguments.
Regression (20.3 and earlier work properly).

`dictGetString` works properly too. 

test case:
```sql
CREATE TABLE countries_table
(
  id UInt64,
  code String,
  country String
)
ENGINE = MergeTree()
ORDER BY id;

INSERT INTO countries_table VALUES (0,'AF','Afghanistan'), (1,'AL','Albania'), (2,'DZ','Algeria'), (3,'AS','American Samoa');

CREATE DICTIONARY countryId
(
  id UInt64 DEFAULT 0,
  code String DEFAULT '',
  country String DEFAULT ''
)
PRIMARY KEY id
SOURCE(CLICKHOUSE(HOST 'localhost' PORT 9000 USER 'default' TABLE 'countries_table' PASSWORD '' DB 'default'))
LIFETIME(MIN 1 MAX 10)
LAYOUT(FLAT());

-- that works
SELECT dictGetString('default.countryId', 'country', toUInt64(number)) AS country FROM numbers(2) GROUP BY country;

-- that does not work on 20.4
SELECT dictGet('default.countryId', 'country', toUInt64(number)) AS country FROM numbers(2) GROUP BY country;

-- that works
SELECT dictGet('default.countryId', 'country', toUInt64(number)) AS country FROM numbers(2);
```

### PR DESCRIPTION
**Pull request by azat**
Changelog category (leave one):
- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix dictGet arguments check during GROUP BY injective functions elimination

Fixes: #11469
Cc: @alexey-milovidov 

P.S. This patch changes the place where the dictionary will be loaded (during syntax analysis), but I guess this is fine, it will be loaded anyway.

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
But line 349 still contains a bug, the invocation of `isInjective` with bogus argument is illegal.

**Comment by azat** [comment]
>But line 349 still contains a bug, the invocation of isInjective with bogus argument is illegal.

Interesting, and Block is required only for external dictionaries...
So right now it is "legal", but unclear and bad

**Comment by alexey-milovidov** [comment]
@azat If this method is no longer used with meaningful Block argument, we can remove this argument from the method and remove all unused implementations.

**Comment by azat** [comment]
>@azat If this method is no longer used with meaningful Block argument, we can remove this argument from the method and remove all unused implementations.

I wish this was true, but it is required for dictGet* functions (since it needs attribute name to detect injectiveness)

**Comment by azat** [comment]
>I wish this was true, but it is required for dictGet* functions (since it needs attribute name to detect injectiveness)

@alexey-milovidov creaing proper sample block here will be overkill, how about convert `isInjective(Block)` to `isInjetive(std::optional<Block>)` and done with it?

**Comment by alexey-milovidov** [comment]
Ok.

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
Sorry, now it looks even more strange.

`std::optional<Block>` does not make sense, because it implies that passing empty block is somewhat acceptable.
But injectiveness of zero-argument function is degenerate case.

**Comment by alexey-milovidov** [comment]
> Yandex synchronization check (only for Yandex employees) 

It simply does not support new tests.

**Comment by azat** [comment]
>std::optional<Block> does not make sense, because it implies that passing empty block is somewhat acceptable.
But injectiveness of zero-argument function is degenerate case.

@alexey-milovidov thoughts? create proper arguments just for checking injectiveness?

Right now the only place that requires arguments for isInjective is `dictGet*`, and it has proper check of arguments (so last patch can be dropped).

https://github.com/ClickHouse/ClickHouse/blob/0fdc29be1eef2c67c973cff531455116fa17326d/src/Functions/FunctionsExternalDictionaries.h#L100-L114

**Comment by alexey-milovidov** [comment]
Yes, the last patch (with `optional`) does not make sense.

We can return false (that the function is not injective) for `dictGet` if empty block was passed.
Also document this behaviour in the interface of `isInjective` - you can pass empty block to check if the function is injective with any arguments.

**Comment by alexey-milovidov** [comment]
> Yandex synchronization check (only for Yandex employees) 

Will fix after merge.

**Comment by alesapin** [comment]
Suspicious backport...

**Pull request merged**
