### PR TITLE
Fix incorrect alias recursion in QueryNormalizer

### LINKED ISSUE #46268: Cannot use an aggregation result in select columns (ILLEGAL_AGGREGATION)
**Describe what's wrong**

The usage of an aggregation result in select columns leads to ILLEGAL_AGGREGATION error.
https://fiddle.clickhouse.com/fde0d48f-c4d8-4253-af81-ecb94a1e7c50

**Does it reproduce on recent release?**

v22.3.17.13 - lts
v22.8.13.20 - lts
v23.1.3.5

**How to reproduce**

```sql
CREATE TABLE t (a Int8, b Int8)
ENGINE = MergeTree()
ORDER BY a;

INSERT INTO t (a, b)
VALUES (1, 2), (1, 3);

SELECT max(b) AS b, b AS b1
FROM t
GROUP BY a;
```

Gets error:
```
Received exception from server (version 22.8.13):
Code: 184. DB::Exception: Received from localhost:9000. DB::Exception: Aggregate function max(b) is found inside another aggregate function in query: While processing max(b) AS b. (ILLEGAL_AGGREGATION)
(query: SELECT max(b) AS b, b AS b1
FROM t
GROUP BY a;)
```

**Expected behavior**

Select completes without error.
`b=3, b1=3`

**Additional context**

1. We have similar code in our project and it worked well. But I could not find any CH version that executes this scenario without errors now.
2. When EXPLAIN SYNTAX is used it shows that `b` replaces with `max(b)` (that may explain error but not sure):
```
Received exception from server (version 22.8.13):
Code: 184. DB::Exception: Received from localhost:9000. DB::Exception: Aggregate function max(b) is found inside another aggregate function in query: While processing max(b) AS b: While processing SELECT max(b) AS b, max(b) AS b1 FROM t GROUP BY a LIMIT 10. (ILLEGAL_AGGREGATION)
(query: EXPLAIN SYNTAX
SELECT max(b) AS b, b AS b1
FROM t
GROUP BY a
LIMIT 10;)
```
3. The problem solves when the additional cast is added:
```sql
SELECT max(b) AS b, b::Int8 AS b1
FROM t
GROUP BY a;
```

### LINKED ISSUE #46273: order by aggregate function exception
I use such sql to query data order by comment_rate, which is calculated by comment and play, But I got an error from clickhouse. 
```
select vid, sum(comment) as comment,sum(play) as play, comment / play as cr from mytable group by vid order by cr;
```
the error detail is below:
```
Received exception from server (version 23.1.3):
Code: 184. DB::Exception: Received from localhost:9000. DB::Exception: Aggregate function sum(comment) is found inside another aggregate function in query: While processing sum(comment). (ILLEGAL_AGGREGATION)
```
How to solve this problem?

### LINKED ISSUE #46724: Getting column is not under aggregate function when upgrading from 22.3 to 22.8
We are trying to upgrade our CH cluster and noticed that some queries started failing. Sample data and DDL is inside fiddle

Is it possible to have old behaviour by changing some settings?

ClickHouse 22.3.11 - query works

```sql
SELECT
    if(empty(id), toString(device), id) AS device,
    multiIf(
        notEmpty(id),'a',
        device == '00000000-0000-0000-0000-000000000000', 'b',
        'c' ) AS device_id_type,
        count()
FROM table1
GROUP BY device, device_id_type
```

https://fiddle.clickhouse.com/f3a8562d-f847-489a-bd24-f5d3eac360f6

ClickHouse 22.8.13 - query fails

```
Code: 215. DB::Exception: Received from localhost:9000. DB::Exception: Column `id` is not under aggregate function and not in GROUP BY.
```

https://fiddle.clickhouse.com/a04d554b-ea64-4fa1-b76a-ccb6dff52939

UPD: Looks similar to this https://github.com/ClickHouse/ClickHouse/issues/46268

### PR DESCRIPTION
**Pull request by Algunenano**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in official stable or prestable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
- Fix incorrect alias recursion in QueryNormalizer

Closes https://github.com/ClickHouse/ClickHouse/issues/46268
Closes https://github.com/ClickHouse/ClickHouse/issues/46273
Closes https://github.com/ClickHouse/ClickHouse/issues/46724

Should be backported to all stable releases (since the bug was backported to all releases)

Does not affect the (experimental) analyzer but I didn't add any test with it enabled to make backporting simpler.

### CODE REVIEW

**Comment by Algunenano** [comment]
Added a test for #46724 too, since this PR also fixes that backwards compatibility issue.

**Comment by simpl1g** [comment]
Any chances that this will be merged into 22.8.14? 🙄

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
Yes, if it is merged before August, it will be backported to 22.8 :)

**Comment by filimonov** [comment]
The issue was introduced by https://github.com/ClickHouse/ClickHouse/pull/42827

**Comment by srikanthccv** [comment]
@alexey-milovidov I see that this was backported to 22.8 on Mar 2nd but has not been released yet? Can you share when we can potentially expect a release?

**Pull request merged**
