### PR TITLE
Fix storage Buffer over Distributed

### LINKED ISSUE #62486: Block structure mismatch in UnionStep
``` sql
CREATE TABLE realtimedistributed (`amount` Int64, `transID` String, `userID` String, `appID` String, `appName` String, `transType` String, `orderSource` String, `nau` String, `fau` String, `transactionType` String, `supplier` String, `fMerchant` String, `bankConnCode` String, `reqDate` DateTime) ENGINE = Distributed(test_cluster_two_shards, currentDatabase(), realtimedrep, rand());

CREATE TABLE realtimebuff__fuzz_19 (`amount` Nullable(Int64), `transID` UInt256, `userID` String, `appID` String, `appName` Nullable(String), `transType` Decimal(38, 3), `orderSource` Nullable(String), `nau` Int8, `fau` LowCardinality(String), `transactionType` String, `supplier` String, `fMerchant` Nullable(String), `bankConnCode` String, `reqDate` DateTime) ENGINE = Buffer(currentDatabase(), 'realtimedistributed', 16, 3600, 36000, 10000, 1000000, 10000000, 100000000);

INSERT INTO realtimebuff__fuzz_19 (amount, transID, userID, appID, appName, transType, orderSource, nau, fau, transactionType, supplier, fMerchant, bankConnCode, reqDate) FORMAT Values

SELECT sum(amount) = 100 FROM realtimebuff__fuzz_19
```

```
❯ rg -zaui '99f2117c-09e1-4c82-853b-d40fcba4adec' server.log-14.zst -A 10
855396:2024.04.09 21:25:01.993412 [ 160 ] {99f2117c-09e1-4c82-853b-d40fcba4adec} <Debug> executeQuery: (from [::ffff:127.0.0.1]:43580) (comment: /workspace/ch/tests/queries/0_stateless/01584_distributed_buffer_cannot_find_column.sql) SELECT sum(amount) = 100 FROM realtimebuff__fuzz_19 (stage: Complete)
855397:2024.04.09 21:25:01.993887 [ 160 ] {99f2117c-09e1-4c82-853b-d40fcba4adec} <Trace> Planner: Query SELECT sum(__table1.amount) = 100 AS `equals(sum(amount), 100)` FROM default.realtimebuff__fuzz_19 AS __table1 to stage Complete
855398:2024.04.09 21:25:01.993928 [ 160 ] {99f2117c-09e1-4c82-853b-d40fcba4adec} <Trace> ContextAccess (default): Access granted: SELECT(amount) ON default.realtimebuff__fuzz_19
855399:2024.04.09 21:25:01.993993 [ 160 ] {99f2117c-09e1-4c82-853b-d40fcba4adec} <Warning> StorageBuffer (default.realtimebuff__fuzz_19): Destination table default.realtimedistributed has different type of column amount (Int64 != Nullable(Int64)). Data from destination table are converted.
855400:2024.04.09 21:25:01.994211 [ 160 ] {99f2117c-09e1-4c82-853b-d40fcba4adec} <Trace> Planner: Query SELECT sum(__table1.amount) = 100 AS `equals(sum(amount), 100)` FROM default.realtimedrep AS __table1 to stage WithMergeableState only analyze
855401:2024.04.09 21:25:01.994285 [ 160 ] {99f2117c-09e1-4c82-853b-d40fcba4adec} <Trace> Planner: Query SELECT sum(__table1.amount) = 100 AS `equals(sum(amount), 100)` FROM default.realtimedrep AS __table1 from stage FetchColumns to stage WithMergeableState only analyze
855402:2024.04.09 21:25:01.994709 [ 160 ] {99f2117c-09e1-4c82-853b-d40fcba4adec} <Trace> Planner: Query SELECT sum(__table1.amount) = 100 AS `equals(sum(amount), 100)` FROM default.realtimedrep AS __table1 to stage WithMergeableState
855403:2024.04.09 21:25:01.994784 [ 160 ] {99f2117c-09e1-4c82-853b-d40fcba4adec} <Trace> ContextAccess (default): Access granted: SELECT(amount) ON default.realtimedrep
855404:2024.04.09 21:25:01.994845 [ 160 ] {99f2117c-09e1-4c82-853b-d40fcba4adec} <Trace> Planner: Query SELECT sum(__table1.amount) = 100 AS `equals(sum(amount), 100)` FROM default.realtimedrep AS __table1 from stage FetchColumns to stage WithMergeableState
855405:2024.04.09 21:25:01.995093 [ 160 ] {99f2117c-09e1-4c82-853b-d40fcba4adec} <Trace> Planner: Query SELECT sum(__table1.amount) = 100 AS `equals(sum(amount), 100)` FROM default.realtimedrep AS __table1 to stage WithMergeableState only analyze
855406:2024.04.09 21:25:01.995155 [ 160 ] {99f2117c-09e1-4c82-853b-d40fcba4adec} <Trace> Planner: Query SELECT sum(__table1.amount) = 100 AS `equals(sum(amount), 100)` FROM default.realtimedrep AS __table1 from stage FetchColumns to stage WithMergeableState only analyze
855407:2024.04.09 21:25:01.995330 [ 160 ] {99f2117c-09e1-4c82-853b-d40fcba4adec} <Fatal> : Logical error: 'Block structure mismatch in UnionStep stream: different types:
855408-sum(__table1.amount) AggregateFunction(sum, Int64) AggregateFunction(size = 0)
855409-sum(__table1.amount) AggregateFunction(sum, Int64) AggregateFunction(size = 0)'.
855410-2024.04.09 21:25:02.000100 [ 831 ] {} <Trace> AsynchronousMetrics: MemoryTracking: was 3.30 GiB, peak 4.48 GiB, free memory in arenas 0.00 B, will set to 3.29 GiB (RSS), difference: -11.08 MiB
```

column `amount` is Nullable in one case and not-nullable in the other.
maybe we should throw an exception during `create table`?

### PR DESCRIPTION
**Pull request by vdimir**
### Changelog category (leave one):

- Backward Incompatible Change

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
* Fix logical errors with storage `Buffer` used with distributed destination table. It's a backward incompatible change: queries using `Buffer` with a distributed destination table may stop working if the table appears more than once in the query (e.g., in a self-join).

Close https://github.com/ClickHouse/ClickHouse/issues/62486

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [x]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-ch-test-poll** [comment]
*This is an automated comment for commit e5e93e1dc01416dabd0e14873c6754d0946c9ee7 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/67015/e5e93e1dc01416dabd0e14873c6754d0946c9ee7/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/65521/9d7bb2a430b142e0761cc30efcf78ea1bbeb6871/docs_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Comment by alexey-milovidov** [comment]
Needs #67170

**Comment by alexey-milovidov** [comment]
Good, but let's also label it as a backward incompatible change.

**Comment by vdimir** [comment]
> Stateless tests (msan) [2/4] — fail: 1, passed: 1719, skipped: 22 [Details](https://s3.amazonaws.com/clickhouse-test-reports/67015/645ed950016b0431e52dca33cff2434f9e9c52af/stateless_tests__msan__[2_4].html)

Fixed in https://github.com/ClickHouse/ClickHouse/issues/67169

**Comment by vdimir** [comment]
> AST fuzzer (debug) — Logical error: 'Expected single dictionary argument for function.'. [Details](https://s3.amazonaws.com/clickhouse-test-reports/67015/10a9613edb610bc36299b8ac5638f5b9a5740cc1/ast_fuzzer__debug_.html)



> Stateless tests (release, old analyzer, s3, DatabaseReplicated) [2/4] — fail: 1, passed: 1708, skipped: 35 [Details](https://s3.amazonaws.com/clickhouse-test-reports/67015/10a9613edb610bc36299b8ac5638f5b9a5740cc1/stateless_tests__release__old_analyzer__s3__databasereplicated__[2_4].html)

https://github.com/ClickHouse/ClickHouse/issues/67599

**Pull request merged**
