### PR TITLE
Add 4-letter command for yielding/resigning leadership

### PR DESCRIPTION
**Pull request by chhetripradeep**
### Changelog category (leave one):

- New Feature

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Add 4-letter command for yielding/resigning leadership (https://github.com/ClickHouse/ClickHouse/issues/56352)

### Documentation entry for user-facing changes

- [x] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by robot-ch-test-poll4** [comment]
*This is an automated comment for commit 6ae508efe9ccd7e74a774b67df197d3c1efd06f0 with description of existing statuses. It's updated for the latest CI running*

[❌ Click here](https://s3.amazonaws.com/clickhouse-test-reports/56354/6ae508efe9ccd7e74a774b67df197d3c1efd06f0/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs Check</td><td>Builds and tests the documentation</td><td>❌ failure</td></tr>
<tbody>
</table>

**Review by antonio2368 — COMMENTED** [review]
Everything looks okay, can you just replace every `yield_leader`, `YieldLeader`, `Yield to be leader` with a variant of yield leadership? Yield leader sounds strange

**Review by antonio2368 — APPROVED** [review]

**Comment by chhetripradeep** [comment]
Integration test added as part of this PR passed:

Screenshot 2023-11-07 at 6 11 39 PM

**Comment by chhetripradeep** [comment]
Thank you Antonio.

**Pull request merged**
