### PR TITLE
ODBC connection holder fix dangling reference

### PR DESCRIPTION
**Pull request by kitaisreal**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by xjewer** [comment]
any plans to backport to 21.8 lts?

**Comment by kitaisreal** [comment]
@xjewer it seems that this dangling reference is not accesses after object is created. Are there any crashes related to this ?

**Comment by xjewer** [comment]
@kitaisreal no crashes, but it fails to re-connect when faces the 08S0 Communication link failure.

connection_holders would have some garbage in connection_string which leads to errors like this:

```
[unixODBC][Driver Manager]Data source name not found, and no default driver specified , Stack trace (when copying this message, always include the lines below)
```

and it obviously can't re-connect to unknown datasource -> dictionaries are not reloading until the odbc-bridge restart

**Comment by kitaisreal** [comment]
@xjewer agreed lets backport.

**Pull request merged**
