### PR TITLE
Revert "Revert "Introduce bulk loading to StorageEmbeddedRocksDB""

### PR DESCRIPTION
**Pull request by canhld94**
### Changelog category (leave one):

- New Feature

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

- Introduce bulk loading to StorageEmbeddedRocksDB by creating and ingesting SST file instead of relying on rocksdb build-in memtable. This help to increase importing speed, especially for long-running insert query to StorageEmbeddedRocksDB tables. Also, introduce StorageEmbeddedRocksDB table settings.

Reverts ClickHouse/ClickHouse#63316

### CODE REVIEW

**Comment by canhld94** [comment]
Hi @vdimir @alexey-milovidov please help to review again [[THANKS]]
Data race happened because I mistakenly declare a local variable as static variable. I should be fixed in https://github.com/ClickHouse/ClickHouse/pull/63324/commits/44b7ec46c0f815b3365ff6f65c2013e534b77ed2 .

**Review by vdimir — APPROVED** [review]

**Comment by robot-ch-test-poll3** [comment]
*This is an automated comment for commit 44b7ec46c0f815b3365ff6f65c2013e534b77ed2 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/63324/44b7ec46c0f815b3365ff6f65c2013e534b77ed2/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

**Comment by alexey-milovidov** [comment]
@canhld94, a test has failed: https://s3.amazonaws.com/clickhouse-test-reports/60468/875507c921279d93106713934add09d05802cef3/stateless_tests__aarch64_.html

**Comment by canhld94** [comment]
I think because of the random settings. The test depends on the block size. I will fix it.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by alexey-milovidov** [comment]
Plus this: https://s3.amazonaws.com/clickhouse-test-reports/63443/2b8254f987a65d5c21d74fe67b4ee9757970466e/stateless_tests__aarch64_.html

Please set the required settings explicitly in the test.

**Comment by vdimir** [comment]
[All failures](https://play.clickhouse.com/play?user=play#CldJVEgKICAgIGZhbHNlIGFzIG9ubHlfbWFzdGVyClNFTEVDVCAqCkZST00gKApTRUxFQ1QKICAgIHB1bGxfcmVxdWVzdF9udW1iZXIgYXMgcHJudW0sCiAgICBzdWJzdHIoY29tbWl0X3NoYSwgMSw5KSBhcyBzaGEsCiAgICByb3VuZCh0ZXN0X2R1cmF0aW9uX21zIC8gMTAwMCwgMikgYXMgZHVyLAogICAgY2hlY2tfc3RhcnRfdGltZSwKICAgIGZvcm1hdFJlYWRhYmxlVGltZURlbHRhKGludERpdihub3coKSAtIGNoZWNrX3N0YXJ0X3RpbWUsIDM2MDApICogMzYwMCkgYXMgYWdvLAogICAgY2hlY2tfbmFtZSwKICAgIHRlc3RfbmFtZSwKICAgIHJlcG9ydF91cmwKRlJPTSBjaGVja3MKV0hFUkUgMQogICAgQU5EIGNoZWNrX3N0YXJ0X3RpbWUgPj0gbm93KCkgLSBJTlRFUlZBTCA3IERBWQogICAgQU5EIChwdWxsX3JlcXVlc3RfbnVtYmVyID0gMCBPUiBub3Qgb25seV9tYXN0ZXIpCiAgICBBTkQgdGVzdF9zdGF0dXMgIT0gJ1NLSVBQRUQnCiAgICBBTkQgdGVzdF9zdGF0dXMgTElLRSAnRiUnCiAgICBBTkQgY2hlY2tfc3RhdHVzICE9ICdzdWNjZXNzJwopCldIRVJFIHRlc3RfbmFtZSBsaWtlICclMDI5NTZfcm9ja3NkYl9idWxrX3NpbmslJwpPUkRFUiBCWSBjaGVja19zdGFydF90aW1lIERFU0MsIGNoZWNrX25hbWUsIHRlc3RfbmFtZQ==) is for aarch64 and I cannot reproduce locally, perhaps something specific

**Comment by alexey-milovidov** [comment]
@vdimir, it still happens: https://s3.amazonaws.com/clickhouse-test-reports/64152/ede7b1474900d0dc7e71fce6dd5e3e7ed1781a00/stateless_tests__aarch64_.html

**Comment by vdimir** [comment]
I have two hypotheses as to why this may happen. It could be due to a race condition in statistics retrieval, possibly somewhere here (and that's why it occurs more often on AArch):
https://github.com/ClickHouse/ClickHouse/blob/0ebca16da0b5bfd45c59cc1d15e4a9d6b03e7d14/src/Storages/RocksDB/StorageEmbeddedRocksDB.cpp#L654

However, access to `rocksdb_ptr` is synchronized in `truncate` and `rocksdb_ptr` is reset, so why do we get `1` instead of `0` if we retrieve statistics after truncation but before stats are updated by insert? Also why only one particular select from system.rocksdb is always affected?

Alternatively, we might be creating two sinks but for some reason writing everything through one. I'll add more logging, and let's wait for the next reproduction. https://github.com/ClickHouse/ClickHouse/pull/64203

**Comment by alexey-milovidov** [comment]
@vdimir it failed: https://s3.amazonaws.com/clickhouse-test-reports/65571/7726f9e2af38120cdd69764d22db0a42fba1e6a1/stateless_tests__ubsan__[2_2].html

**Comment by canhld94** [comment]
From the logs:

```
2024.06.24 02:19:18.331114 [ 30202 ] {ac9bbb4a-2c5a-4be2-ba35-8347c5ad759f} <Debug> StorageEmbeddedRocksDB (test_tdgmzt6g.rocksdb_worm (5cb16fb3-bc17-4054-bb4c-e4102fdd20a0)): Using bulk insert
2024.06.24 02:19:18.331338 [ 30202 ] {ac9bbb4a-2c5a-4be2-ba35-8347c5ad759f} <Debug> StorageEmbeddedRocksDB (test_tdgmzt6g.rocksdb_worm (5cb16fb3-bc17-4054-bb4c-e4102fdd20a0)): Using bulk insert
```

--> the insert query create two sinks. We expect the `SELECT` query in:

```sql
INSERT INTO rocksdb_worm SELECT number, number+1 FROM numbers_mt(1000000) SETTINGS max_threads = 2, max_insert_threads = 2, max_block_size = 10000, min_insert_block_size_rows = 0, min_insert_block_size_bytes = 0, insert_deduplication_token = '';
```

To return many blocks with `10000` rows and thus populate both sinks and create two SST files. However, only one sink is populated. I don't know it's because `SELECT` only returns one big block or other reason yet:

```
2024.06.24 02:19:18.973135 [ 32811 ] {ac9bbb4a-2c5a-4be2-ba35-8347c5ad759f} <Debug> EmbeddedRocksDBBulkSink: Writing 1000000 rows to SST file /var/lib/clickhouse/store/5cb/5cb16fb3-bc17-4054-bb4c-e4102fdd20a0/tmp_insert_0167a70d0d588e1b584c496a64bda561-udgmzwhd/0.sst
```

**Comment by vdimir** [comment]
Probably just pipeline executed in a way that all data goes into the same sink... 
ofc, we can add more info to logs https://github.com/ClickHouse/ClickHouse/pull/66107 but if it's related to pipeline execution, I'm not sure how to make it stable using two sinks. Perhaps we can also set `bulk_insert_block_size`, but it will check squashing, but not the number of sinks.

**Comment by alexey-milovidov** [comment]
@vdimir, you can remove the test.

**Pull request merged**
