### PR TITLE
Fix 01236_graphite_mt for random timezones

### PR DESCRIPTION
**Pull request by Algunenano**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
...

Detailed description / Documentation draft:

It keeps failing in the CI depending on the timezone (for example with `Asia/Kathmandu`, GMT+5:45), so use `UTC` to test instead.

### CODE REVIEW

**Comment by akuzm** [comment]
I can't figure out what's the mechanism for the failure depending on the tz. Something with rounding with fractional hours? But we use `toDataTime` so there should be no rounding... Another thing that looks problematic is the use of `today()` -- it can change halfway through the test.

**Comment by Algunenano** [comment]
> I can't figure out what's the mechanism for the failure depending on the tz. Something with rounding with fractional hours?

You are probably right, at it's likely that GraphiteRollupSortedAlgorithm.cpp::roundTimeToPrecision is incorrect.

> Another thing that looks problematic is the use of today() -- it can change halfway through the test.

Correct again. I'll review both.

**Comment by Algunenano** [comment]
@Mergifyio update

**Comment by Algunenano** [comment]
`Pacific/Auckland` should work now too.

**Pull request merged**
