### PR TITLE
Add a test for #30679

### LINKED ISSUE #30679: Error in executing 'group by' with 'prewhere'
Steps to reproduce:
```
create table table1 (
    col1 Int32,
    col2 Int32
)
ENGINE = MergeTree
partition by tuple()
order by col1;
```

```
with :id as pid
select a.col1, sum(a.col2) as summ
from table1 a
prewhere (pid is null or a.col2 = pid)
group by a.col1;
```
When `null` is passed as `:id` parameter, the query above produces error:
```
Code: 215, e.displayText() = DB::Exception: Column `col2` is not under aggregate function and not in GROUP BY: While processing col2 (version 21.8.3.44 (official build))
```
It doesn't matter, if the table is distributed or not.
If you replace `prewhere` with `where` or pass non-null value or remove `is null` part of the condition, the query executes without error.

This reproducible on 21.8.3.44 and above.

### PR DESCRIPTION
**Pull request by alexey-milovidov**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

This closes #30679.

### CODE REVIEW

**Review by SmitaRKulkarni — APPROVED** [review]
LGTM

**Comment by alexey-milovidov** [comment]
#44569

**Comment by alexey-milovidov** [comment]
#44573

**Comment by alexey-milovidov** [comment]
#44572

**Pull request merged**
