### PR TITLE
Disable implicit projections by default

### PR DESCRIPTION
**Pull request by amosbird**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Add setting `optimize_use_implicit_projections` to disable implicit projections (currently only `min_max_count` projection). This is defaulted to false until https://github.com/ClickHouse/ClickHouse/issues/52075 is fixed.

There will be some broken tests which rely on implicit projections. It will be fixed in later commits by setting optimize_use_implicit_projections = true explicitly.

### CODE REVIEW

**Comment by robot-ch-test-poll4** [comment]
This is an automated comment for commit e22a952d9d12956525b04be244885b90c822c735 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/52152/e22a952d9d12956525b04be244885b90c822c735/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Docs Check</td><td>Builds and tests the documentation</td><td>🟡 pending</td></tr>
</table>

**Comment by amosbird** [comment]
Stateless tests (aarch64) — Some queries hung, fail: 0, passed: 5407, skipped: 24

https://github.com/ClickHouse/ClickHouse/pull/52160

**Review by KochetovNicolai — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
Let's also put it under compatibility setting, so it will be disabled only if `compatibility` >= '23.7'

**Comment by amosbird** [comment]
AST fuzzer (debug) — Logical error: 'Invalid Field get from type Float64 to type UInt64'.

```
CREATE OR REPLACE TABLE test1__fuzz_35 (`p` Nullable(Int64),`k` Decimal(76, 39)) ENGINE = MergeTree PARTITION BY toDate(p) ORDER BY k SETTINGS index_granularity = 1, allow_nullable_key = 1;

INSERT INTO test1__fuzz_35 FORMAT Values ('2020-09-01 00:01:02', 1), ('2020-09-01 20:01:03', 2), ('2020-09-02 00:01:03', 3);

SELECT count() FROM test1__fuzz_35 WHERE indexHint(-2147483648, p = 1.) SETTINGS optimize_use_implicit_projections = 1;
```

This doesn't block current PR as `optimize_use_implicit_projections` is disabled by default. Will also fix this in #52151

**Pull request merged**
