### PR TITLE
Add function `arrayShingles()`

### LINKED ISSUE #54963: `shingles` function for arrays.
**Use case**

```
shingles(['Fotografías','ganadoras','del','World','Press','Photo','Awards','2014','http','t','co','F1iwa8gSWK'], 3)
= [['Fotografías','ganadoras','del'],
   ['ganadoras','del','World'],
   ['del','World','Press'],
   ['World','Press','Photo'],
   ['Press','Photo','Awards'],
   ['Photo','Awards','2014'],
   ['Awards','2014','http'],
   ['2014','http','t'],
   ['http','t','co'],
   ['t','co','F1iwa8gSWK']]
```

### PR DESCRIPTION
**Pull request by zenmiao7**
Fixes #54963

Computes subarrays of a specified length from an array:

```sql
SELECT arrayShingles([1, 2, 3, 4, 5], 3)
-- returns [[1,2,3],[2,3,4],[3,4,5]]
```

### Changelog category (leave one):
- New Feature

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md
Add function `arrayShingles()` to compute subarrays, e.g. `arrayShingles([1, 2, 3, 4, 5], 3)` returns `[[1,2,3],[2,3,4],[3,4,5]]`

### CODE REVIEW

**Comment by robot-ch-test-poll2** [comment]
*This is an automated comment for commit 5c0d34341f8ae7792cc3146ad0e13a52b03d7496 with description of existing statuses. It's updated for the latest CI running*

[❌ Click here](https://s3.amazonaws.com/clickhouse-test-reports/58396/5c0d34341f8ae7792cc3146ad0e13a52b03d7496/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td><a href="https://github.com/ClickHouse/ClickHouse/blob/master/.github/PULL_REQUEST_TEMPLATE.md?plain=1">❌ failure</a></td></tr>
<tbody>
</table>

**Comment by zenmiao7** [comment]
@alexey-milovidov Could you help give some advices to my draft PR? I have some questions need your help.
- What should we do if the second number <= 0? What I do here is returning a [];

**Comment by zenmiao7** [comment]
@robot-ch-test-poll2 run checks again.

**Comment by alexey-milovidov** [comment]
> What should we do if the second number <= 0?

Throw an exception.

**Comment by zenmiao7** [comment]
@rschu1ze  Could you help review? Thanks.

**Comment by Blargian** [comment]
Closes #54963

**Pull request merged**
