### PR TITLE
clickhouse-test: do hung check only under --hung-check

### PR DESCRIPTION
**Pull request by azat**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by robot-ch-test-poll4** [comment]
*This is an automated comment for commit d95e6a627143a908f070e7ce0fa1fa8a04247b4a with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/72806/d95e6a627143a908f070e7ce0fa1fa8a04247b4a/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/b364af07f9253814bd808cae88822aed6a3a2d0b/docs_check.html">✅ success</a></td></tr>
<tr><td>Unit tests</td><td>Runs the unit tests for different release types</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/b364af07f9253814bd808cae88822aed6a3a2d0b/unit_tests__release_.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Comment by azat** [comment]
Can someone please take a look?

**Comment by alexey-milovidov** [comment]
Stress tests have failed.

**Comment by azat** [comment]
I think it should be fixed by #72558

**Comment by azat** [comment]
CI is green

**Pull request merged**
