### PR TITLE
Update 02125_many_mutations.sh

### PR DESCRIPTION
**Pull request by tavplubix**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
https://s3.amazonaws.com/clickhouse-test-reports/61109/5cf2b53f146c1a4f24d8212f9f810d587c46bfc0/stateless_tests__release_.html

```
2024-07-17 13:07:13 02125_many_mutations:                                                   [ FAIL ] 66.29 sec.
2024-07-17 13:07:13 Reason: result differs with reference:  
2024-07-17 13:07:13 --- /usr/share/clickhouse-test/queries/0_stateless/02125_many_mutations.reference	2024-07-17 12:56:33.142765490 +0930
2024-07-17 13:07:13 +++ /tmp/clickhouse-test/0_stateless/02125_many_mutations.stdout	2024-07-17 13:07:13.361251519 +0930
2024-07-17 13:07:13 @@ -1,6 +1,6 @@
2024-07-17 13:07:13  0	0
2024-07-17 13:07:13  1	1
2024-07-17 13:07:13  20000
2024-07-17 13:07:13 -0
2024-07-17 13:07:13 -0	20000
2024-07-17 13:07:13 -1	20001
2024-07-17 13:07:13 +20000
2024-07-17 13:07:13 +0	0
2024-07-17 13:07:13 +1	1
2024-07-17 13:07:13 
```

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-ch-test-poll1** [comment]
*This is an automated comment for commit f71e91b19f579580346dc430e9603c6dfa8102e5 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/66724/f71e91b19f579580346dc430e9603c6dfa8102e5/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Builds</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/95975164250d185760287f00b98e1b1afc5278c3/builds/report.html">✅ success</a></td></tr>
<tr><td>ClickBench</td><td>Runs [ClickBench](https://github.com/ClickHouse/ClickBench/) with instant-attach table</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/95975164250d185760287f00b98e1b1afc5278c3/clickbench__aarch64_.html">✅ success</a></td></tr>
<tr><td>Compatibility check</td><td>Checks that <b>clickhouse</b> binary runs on distributions with old libc versions. If it fails, ask a maintainer for help</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/95975164250d185760287f00b98e1b1afc5278c3/compatibility_check__aarch64_.html">✅ success</a></td></tr>
<tr><td>Docker keeper image</td><td>The check to build and optionally push the mentioned image to docker hub</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/95975164250d185760287f00b98e1b1afc5278c3/docker_keeper_image.html">✅ success</a></td></tr>
<tr><td>Docker server image</td><td>The check to build and optionally push the mentioned image to docker hub</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/95975164250d185760287f00b98e1b1afc5278c3/docker_server_image.html">✅ success</a></td></tr>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/4b0ef8edce0eca049bcdb8938fd9aecb0e8c2377/docs_check.html">✅ success</a></td></tr>
<tr><td>Install packages</td><td>Checks that the built packages are installable in a clear environment</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/95975164250d185760287f00b98e1b1afc5278c3/install_packages__aarch64_.html">✅ success</a></td></tr>
<tr><td>Stateful tests</td><td>Runs stateful functional tests for ClickHouse binaries built in various configurations -- release, debug, with sanitizers, etc</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/95975164250d185760287f00b98e1b1afc5278c3/stateful_tests__aarch64_.html">✅ success</a></td></tr>
<tr><td>Unit tests</td><td>Runs the unit tests for different release types</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/95975164250d185760287f00b98e1b1afc5278c3/unit_tests__asan_.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
Something has failed.

**Comment by tavplubix** [comment]
Stateless tests (tsan, s3 storage) [2/3] - task timeout - fixed in https://github.com/ClickHouse/ClickHouse/pull/66783

**Comment by tavplubix** [comment]
The test has passed in the release build, it's disabled for other builds anyway

**Pull request merged**
