### PR TITLE
CI: Job Timeout handling

### PR DESCRIPTION
**Pull request by maxknv**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
- timeout handling for functional and integration tests, store artifacts and report if timed out
- sets 2h default timeout for all jobs

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [x]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-ch-test-poll4** [comment]
*This is an automated comment for commit 87b3ee25e728ab463c0b45d779dc7de07503284e with description of existing statuses. It's updated for the latest CI running*

[❌ Click here](https://s3.amazonaws.com/clickhouse-test-reports/67944/87b3ee25e728ab463c0b45d779dc7de07503284e/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Style check</td><td>Runs a set of checks to keep the code style clean. If some of tests failed, see the related log from the report</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/67944/87b3ee25e728ab463c0b45d779dc7de07503284e/style_check.html">❌ failure</a></td></tr>
<tbody>
</table>

**Comment by fm4v** [comment]
I have concerns about collecting logs after tests when a timeout occurs. In this case, you need to add a signal trap for the `run_tests` function to continue with teardown. Then send one more signal after 10 minutes in case the teardown hangs.

[This is the collected artifacts with current timeout on `run_tests`](https://s3.amazonaws.com/clickhouse-test-reports/68013/55ad7d30946d609159fe5ae9156f02f5b160585a/stateless_tests__release_.html)

**Comment by maxknv** [comment]
> I have concerns about collecting logs after tests when a timeout occurs. In this case, you need to add a signal trap for the `run_tests` function to continue with teardown. Then send one more signal after 10 minutes in case the teardown hangs.
> 
> [This is the collected artifacts with current timeout on `run_tests`](https://s3.amazonaws.com/clickhouse-test-reports/68013/55ad7d30946d609159fe5ae9156f02f5b160585a/stateless_tests__release_.html)

Thank you for looking into this.
I wish we can avoid signal handling anywhere deeper than upper level job script (functional_test_check.py)
Do we have any tear-down in run_tests now?

**Comment by fm4v** [comment]
> Do we have any tear-down in run_tests now?


Everything what is run after https://github.com/ClickHouse/ClickHouse/blob/cabe90d0484a757dcf6a537419d8d27800b9fb17/docker/test/stateless/run.sh#L294

**Comment by maxknv** [comment]
> Everything what is run after

I think "Everything what is run after" should not be in docker's run.sh

**Comment by maxknv** [comment]
report exmple: https://s3.amazonaws.com/clickhouse-test-reports/67944/ae169474c396cb366de9a54c90d6aecd39209246/stateless_tests__asan__[1_2].html

**Pull request merged**
