### PR TITLE
Everything related to S3 metrics was not good

### LINKED ISSUE #35483: it looks like S3 profile events numbers are inflated
ProfileEvents S3ReadMicroseconds RealTimeMicroseconds looks inconsistent.

Elapsed: 0.193 sec. / query_duration_ms = 192  
VS   
S3ReadMicroseconds  = 350736 / RealTimeMicroseconds = 383210.

```sql
INSERT INTO FUNCTION s3(s3_mydata, url = 'https://s3.us-east-1.amazonaws.com/test..../test_file22222.tsv', structure = 'A Int64', format = 'TSV', compression_method = 'none') SELECT number AS A
FROM numbers(10000)

set max_threads=1;


SELECT count()
FROM s3(s3_mydata, url = 'https://s3.us-east-1.amazonaws.com/test..../test_file22222.tsv', structure = 'A Int64', format = 'TSV', compression_method = 'none')

Query id: 2f63b92a-eae3-45c5-a30c-2a8b7681147a

┌─count()─┐
│   10000 │
└─────────┘

1 rows in set. Elapsed: 0.193 sec. Processed 10.00 thousand rows, 80.00 KB (51.72 thousand rows/s., 413.74 KB/s.)



SELECT
    query_duration_ms,
    k,
    v
FROM system.query_log
ARRAY JOIN
    ProfileEvents.keys AS k,
    ProfileEvents.values AS v
WHERE (query_id = '2f63b92a-eae3-45c5-a30c-2a8b7681147a') AND (type = 2) AND (event_date = today())

┌─query_duration_ms─┬─k─────────────────────────────────┬───────v─┐
│               192 │ Query                             │       1 │
│               192 │ SelectQuery                       │       1 │
│               192 │ IOBufferAllocs                    │       1 │
│               192 │ IOBufferAllocBytes                │ 1048576 │
│               192 │ ArenaAllocChunks                  │       1 │
│               192 │ ArenaAllocBytes                   │    4096 │
│               192 │ TableFunctionExecute              │       1 │
│               192 │ NetworkReceiveElapsedMicroseconds │       7 │
│               192 │ NetworkSendElapsedMicroseconds    │     214 │
│               192 │ NetworkSendBytes                  │    3427 │
│               192 │ SelectedRows                      │   10000 │
│               192 │ SelectedBytes                     │   80000 │
│               192 │ ContextLock                       │      28 │
│               192 │ RWLockAcquiredReadLocks           │       1 │
│               192 │ RealTimeMicroseconds              │  383210 │  --- ? 
│               192 │ UserTimeMicroseconds              │    5004 │
│               192 │ SystemTimeMicroseconds            │     492 │
│               192 │ SoftPageFaults                    │      34 │
│               192 │ OSCPUWaitMicroseconds             │      37 │
│               192 │ OSCPUVirtualTimeMicroseconds      │    5494 │
│               192 │ OSWriteBytes                      │    4096 │
│               192 │ OSReadChars                       │   53248 │
│               192 │ OSWriteChars                      │    2048 │
│               192 │ CreatedHTTPConnections            │       1 │
│               192 │ S3ReadMicroseconds                │  350736 │  --- ?
│               192 │ S3ReadBytes                       │   48890 │
│               192 │ S3ReadRequestsCount               │       1 │
└───────────────────┴───────────────────────────────────┴─────────┘

### PR DESCRIPTION
**Pull request by alexey-milovidov**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
The metrics about time spent reading from s3 now calculated correctly. Close #35483

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
Test needed.

**Comment by alexey-milovidov** [comment]
@mergifyio update after #36607.

**Comment by davenger** [comment]
@mergifyio update

**Comment by davenger** [comment]
Stress tests failures seem to be unrelated to the change

**Review by davenger — APPROVED** [review]

**Pull request merged**
