### PR TITLE
Disable 02834_apache_arrow_abort under sanitizers

### PR DESCRIPTION
**Pull request by nickitat**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Do not test
- [x]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by nikitamikhaylov** [comment]
One more duplicate of https://github.com/ClickHouse/ClickHouse/pull/66508

**Comment by robot-clickhouse** [comment]
*This is an automated comment for commit 29bc9e5ea26cda926b425b758331dd0afdbf2d89 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/66660/29bc9e5ea26cda926b425b758331dd0afdbf2d89/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Builds</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/66657/c57ce063a346698b550134762277c81e12072d88/builds/report.html">✅ success</a></td></tr>
<tr><td>Unit tests</td><td>Runs the unit tests for different release types</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/ea7a85f375bcc6c9a7596b9092e5736db0a93071/unit_tests__release_.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Comment by nickitat** [comment]
there will be more duplicates if we won't merge hot fixes for several days

**Comment by alexey-milovidov** [comment]
@nickitat, we need to fix all flaky tests, not just one. If there are many, we can collect all fixes in a single PR and merge when it is green.

**Pull request closed without merging**
