### PR TITLE
Use upstream repo for apache datasketches

### PR DESCRIPTION
**Pull request by nickitat**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Use upstream repo for apache datasketches.

---

We created our own fork but till this time it contains only one bug [fix](https://github.com/ClickHouse/datasketches-cpp/pull/1) that is now exists in the upstream.

### CODE REVIEW

**Comment by robot-clickhouse** [comment]
*This is an automated comment for commit ffd81e6990a59baac9f0476013f3247612dfcde9 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/55787/ffd81e6990a59baac9f0476013f3247612dfcde9/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td><a href="https://github.com/ClickHouse/ClickHouse/actions/runs/6561784842">✅ success</a></td></tr>
<tbody>
</table>
</details>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/55787/ffd81e6990a59baac9f0476013f3247612dfcde9/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Review by Algunenano — APPROVED** [review]
LGTM. We also included an update (https://github.com/ClickHouse/datasketches-cpp/pull/3) which was fixed in https://github.com/apache/datasketches-cpp/pull/301 and included in the fork. This code was later rewritten (https://github.com/apache/datasketches-cpp/pull/309) so the 4.1.x branch should be ok (if the sanitizers don't complain about it).

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
Tests have failed.

**Comment by rschu1ze** [comment]
This PR introduces a side effect for which I like to post a workaround.

In detail, if one clones a fresh ClickHouse repository and checks out an old branch that does not have this PR yet, for example one of the v23.9 tags, then the checkout will fail:

```bash
$ git switch --create v23.9.6.20-stable

fatal: failed to unpack tree object 7abd49bb2e72bf9a5029993d31dcb1872da88292
error: Submodule 'contrib/datasketches-cpp' could not be updated.
error: Cannot update submodule:
        contrib/datasketches-cpp
Aborting
```

This is because the old repository location (https://github.com/ClickHouse/datasketches-cpp) is not registered as a remote in the submodule. To fix this, do that:

```bash
$ cd contrib/datasketches-cpp
$ git remote add ClickHouse https://github.com/ClickHouse/datasketches-cpp.git
$ git fetch ClickHouse
$ cd ..
$ git switch --create v23.9.6.20-stable
```

**Pull request merged**
