### PR TITLE
Fix WHERE pushdown when subquery has OFFSET

### LINKED ISSUE #40416: When using OFFSET in subquery, WHERE clause in main query is also being applied to subquery first.
**Describe what's wrong**

When using OFFSET in subquery, WHERE clause in main query is also being applied to subquery first.

**Does it reproduce on recent release?**

yes. 22.7

**How to reproduce**

* Which ClickHouse server version to use:  22.7.3.5
* Which interface to use, if matters : clickhouse-client

create table: CREATE TABLE t ENGINE=Log as select * from system.numbers limit 20;

- query 1: 
```
clickhouse :) select number from t order by number desc offset 3;

SELECT number
FROM t
ORDER BY number DESC
OFFSET 3

Query id: 8c390ae6-640e-46c9-8a6c-d907f8f24277

┌─number─┐
│     16 │
│     15 │
│     14 │
│     13 │
│     12 │
│     11 │
│     10 │
│      9 │
│      8 │
│      7 │
│      6 │
│      5 │
│      4 │
│      3 │
│      2 │
│      1 │
│      0 │
└────────┘

17 rows in set. Elapsed: 0.015 sec.
```

- query 2: 
```
clickhouse :) select number from (select number from t order by number desc offset 3) where number < 18;

SELECT number
FROM
(
    SELECT number
    FROM t
    ORDER BY number DESC
    OFFSET 3
)
WHERE number < 18

Query id: 3901f6d1-7d21-437f-8bbd-575e50946426

┌─number─┐
│     14 │
│     13 │
│     12 │
│     11 │
│     10 │
│      9 │
│      8 │
│      7 │
│      6 │
│      5 │
│      4 │
│      3 │
│      2 │
│      1 │
│      0 │
└────────┘

15 rows in set. Elapsed: 0.007 sec.
```

**Expected behavior**

Should produce same result however, it does not, where clause gets applied in subquery:
```
EXPLAIN SYNTAX
SELECT number
FROM
(
SELECT number
FROM t
ORDER BY number DESC
OFFSET 3
) AS desc
WHERE number < 18

Query id: f0c5e9f4-628d-474f-9038-98d221be31b6

┌─explain──────────────────┐
│ SELECT number │
│ FROM │
│ ( │
│ SELECT number │
│ FROM t │
│ WHERE number < 18 │
│ ORDER BY number DESC │
│ OFFSET 3 │
│ ) AS desc │
│ WHERE number < 18 │
└──────────────────────────┘
```

workaround: 
```
clickhouse :)  set enable_optimize_predicate_expression=1

clickhouse :) select number from (select number from t order by number desc offset 3) where number < 18;

SELECT number
FROM
(
    SELECT number
    FROM t
    ORDER BY number DESC
    OFFSET 3
)
WHERE number < 18

Query id: ab454aba-f4c2-4683-b2d5-9250de5b320a

┌─number─┐
│     14 │
│     13 │
│     12 │
│     11 │
│     10 │
│      9 │
│      8 │
│      7 │
│      6 │
│      5 │
│      4 │
│      3 │
│      2 │
│      1 │
│      0 │
└────────┘

15 rows in set. Elapsed: 0.008 sec.
```

### PR DESCRIPTION
**Pull request by tavplubix**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in official stable or prestable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Queries with `OFFSET` clause in subquery and `WHERE` clause in outer query might return incorrect result, it's fixed. Fixes https://github.com/ClickHouse/ClickHouse/issues/40416

### CODE REVIEW

**Comment by tavplubix** [comment]
AST fuzzer failures are related, but I have no ideas why fixing an AST optimization leads to "pipeline stuck"...

@nickitat, could you please help?

**Comment by Algunenano** [comment]
> AST fuzzer failures are related, but I have no ideas why fixing an AST optimization leads to "pipeline stuck"...

Here is a sample query that caused a [Fatal error](https://s3.amazonaws.com/clickhouse-test-reports/41280/cf7d9285541b6ec21f05cf1acea12538661fe79e/fuzzer_astfuzzertsan//server.log):
```sql
CREATE TABLE t ENGINE = Log AS SELECT * FROM system.numbers LIMIT 20

SELECT NULL, 65536, number < 3, NULL, number FROM (SELECT number < NULL, number < 100, NULL, number FROM t ORDER BY number < 100 ASC NULLS FIRST, number < 2147483647 ASC NULLS FIRST OFFSET 3) WHERE number < NULL
```


```
2022.09.14 13:57:02.990407 [ 305757 ] {} <Fatal> BaseDaemon: ########################################
2022.09.14 13:57:02.990624 [ 305757 ] {} <Fatal> BaseDaemon: (version 22.9.1.1, build id: F3B95C6CF06CDE1F4599A0BCA1127D2A951076E9) (from thread 305493) (query_id: 76e1a6db-7a17-4abd-8876-a82fc886ba8f) (query: SELECT NULL, 65536, number < 3, NULL, number FROM (SELECT number < NULL, number < 100, NULL, number FROM t ORDER BY number < 100 ASC NULLS FIRST, number < 2147483647 ASC NULLS FIRST OFFSET 3) WHERE number < NULL) Received signal Aborted (6)
2022.09.14 13:57:02.990782 [ 305757 ] {} <Fatal> BaseDaemon: 
2022.09.14 13:57:02.990923 [ 305757 ] {} <Fatal> BaseDaemon: Stack trace: 0x7f832ac7349c 0x7f832ac23958 0x7f832ac0d53d 0xbb69774 0xbb69d0d 0x45c29e9d 0x45c2936e 0x45c736da 0xbd2c1ae 0xbd39d23 0x7f832ac7174d 0x7f832acf3700
2022.09.14 13:57:02.991078 [ 305757 ] {} <Fatal> BaseDaemon: 4. ? @ 0x7f832ac7349c in ?
2022.09.14 13:57:02.991224 [ 305757 ] {} <Fatal> BaseDaemon: 5. gsignal @ 0x7f832ac23958 in ?
2022.09.14 13:57:02.991331 [ 305757 ] {} <Fatal> BaseDaemon: 6. abort @ 0x7f832ac0d53d in ?
2022.09.14 13:57:03.000198 [ 305491 ] {} <Trace> AsynchronousMetrics: MemoryTracking: was 1.87 GiB, peak 1.87 GiB, will set to 1.88 GiB (RSS), difference: 9.05 MiB
2022.09.14 13:57:03.209863 [ 305757 ] {} <Fatal> BaseDaemon: 7. ./build_docker/../src/Common/Exception.cpp:40: DB::abortOnFailedAssertion(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0xbb69774 in /tmp/clickhouse
2022.09.14 13:57:03.425291 [ 305757 ] {} <Fatal> BaseDaemon: 8.1. inlined from ./build_docker/../src/Common/Exception.cpp:0: DB::handle_error_code(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool, std::__1::vector<void*, std::__1::allocator<void*> > const&)
2022.09.14 13:57:03.425501 [ 305757 ] {} <Fatal> BaseDaemon: 8. ../src/Common/Exception.cpp:70: DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xbb69d0d in /tmp/clickhouse
2022.09.14 13:57:03.564495 [ 305757 ] {} <Fatal> BaseDaemon: 9. ./build_docker/../src/Processors/Executors/PipelineExecutor.cpp:0: DB::PipelineExecutor::finalizeExecution() @ 0x45c29e9d in /tmp/clickhouse
2022.09.14 13:57:03.701553 [ 305757 ] {} <Fatal> BaseDaemon: 10. ./build_docker/../src/Processors/Executors/PipelineExecutor.cpp:108: DB::PipelineExecutor::execute(unsigned long) @ 0x45c2936e in /tmp/clickhouse
2022.09.14 13:57:03.819200 [ 305757 ] {} <Fatal> BaseDaemon: 11.1. inlined from ./build_docker/../src/Processors/Executors/PullingAsyncPipelineExecutor.cpp:79: std::__1::__atomic_base<bool, false>::store(bool, std::__1::memory_order)
2022.09.14 13:57:03.819393 [ 305757 ] {} <Fatal> BaseDaemon: 11.2. inlined from ../contrib/libcxx/include/atomic:1777: std::__1::atomic<bool>::operator=(bool)
2022.09.14 13:57:03.819515 [ 305757 ] {} <Fatal> BaseDaemon: 11.3. inlined from ../src/Processors/Executors/PullingAsyncPipelineExecutor.cpp:91: DB::threadFunction(DB::PullingAsyncPipelineExecutor::Data&, std::__1::shared_ptr<DB::ThreadGroupStatus>, unsigned long)
2022.09.14 13:57:03.819618 [ 305757 ] {} <Fatal> BaseDaemon: 11.4. inlined from ../src/Processors/Executors/PullingAsyncPipelineExecutor.cpp:107: operator()
2022.09.14 13:57:03.819745 [ 305757 ] {} <Fatal> BaseDaemon: 11.5. inlined from ../contrib/libcxx/include/type_traits:3648: decltype(static_cast<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&>(fp)()) std::__1::__invoke_constexpr<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&)
2022.09.14 13:57:03.819887 [ 305757 ] {} <Fatal> BaseDaemon: 11.6. inlined from ../contrib/libcxx/include/tuple:1595: decltype(auto) std::__1::__apply_tuple_impl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::__1::tuple<>&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::__1::tuple<>&, std::__1::__tuple_indices<>)
2022.09.14 13:57:03.820036 [ 305757 ] {} <Fatal> BaseDaemon: 11.7. inlined from ../contrib/libcxx/include/tuple:1604: decltype(auto) std::__1::apply<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::__1::tuple<>&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::__1::tuple<>&)
2022.09.14 13:57:03.820157 [ 305757 ] {} <Fatal> BaseDaemon: 11.8. inlined from ../src/Common/ThreadPool.h:193: operator()
2022.09.14 13:57:03.820321 [ 305757 ] {} <Fatal> BaseDaemon: 11.9. inlined from ../contrib/libcxx/include/type_traits:3640: decltype(static_cast<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(fp)()) std::__1::__invoke<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'()&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)
2022.09.14 13:57:03.820493 [ 305757 ] {} <Fatal> BaseDaemon: 11.10. inlined from ../contrib/libcxx/include/__functional/invoke.h:61: void std::__1::__invoke_void_return_wrapper<void, true>::__call<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'()&>(ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'()&)
2022.09.14 13:57:03.820643 [ 305757 ] {} <Fatal> BaseDaemon: 11.11. inlined from ../contrib/libcxx/include/__functional/function.h:230: std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'(), void ()>::operator()()
2022.09.14 13:57:03.820751 [ 305757 ] {} <Fatal> BaseDaemon: 11. ../contrib/libcxx/include/__functional/function.h:711: void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'(), void ()> >(std::__1::__function::__policy_storage const*) @ 0x45c736da in /tmp/clickhouse
2022.09.14 13:57:03.941926 [ 305757 ] {} <Fatal> BaseDaemon: 12. ./build_docker/../contrib/libcxx/include/__functional/function.h:0: ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xbd2c1ae in /tmp/clickhouse
2022.09.14 13:57:04.000182 [ 305491 ] {} <Trace> AsynchronousMetrics: MemoryTracking: was 1.88 GiB, peak 1.88 GiB, will set to 1.90 GiB (RSS), difference: 24.82 MiB
2022.09.14 13:57:04.092174 [ 305757 ] {} <Fatal> BaseDaemon: 13. ./build_docker/../src/Common/ThreadPool.cpp:0: void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>, bool)::'lambda0'()> >(void*) @ 0xbd39d23 in /tmp/clickhouse
2022.09.14 13:57:04.092355 [ 305757 ] {} <Fatal> BaseDaemon: 14. ? @ 0x7f832ac7174d in ?
2022.09.14 13:57:04.092481 [ 305757 ] {} <Fatal> BaseDaemon: 15. ? @ 0x7f832acf3700 in ?

```

Hope that helps

**Comment by nickitat** [comment]
> AST fuzzer failures are related, but I have no ideas why fixing an AST optimization leads to "pipeline stuck"...
> 
> @nickitat, could you please help?

I will take a look, no problem

**Comment by Algunenano** [comment]
@tavplubix My bad. I understood you have troubles getting info from the stress logs, not in understanding why the query fails now. Sorry for the noise.

**Comment by tavplubix** [comment]
Hm, I forgot to check that query works on build from master with disabled setting. And it does not, so actually it's independent issue. However, we cannot merge this PR until https://github.com/ClickHouse/ClickHouse/issues/41383 is fixed

**Comment by tavplubix** [comment]
The "pipeline stuck" error fixed in https://github.com/ClickHouse/ClickHouse/pull/41588

**Review by alexey-milovidov — APPROVED** [review]
The code LGTM

**Pull request merged**
