### PR TITLE
Ignore parse failure of opentelemetry header

### PR DESCRIPTION
**Pull request by FrankChen021**
Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
- Ignore parse failure of opentelemetry's `traceparent` header

Detailed description / Documentation draft:

Current implementation imposes a strict format on `traceparent` header of incoming HTTP requests.  If the value of such field is invalid, the query is returned immediately as failure. This behaviour is too strict.
image

Considering the opentelemetry specification is still in evolution, and upstream application may generate an id which complies with newer specification which might not be followed by ClickHouse,  I think we should ignore such errors to make sure the query can be executed.

In this PR, I move the assignment of related fields to the end of parse function to make sure they're clean if there is parse failure, so that the code work as if there is no input `traceparent`, and use log to replace original exception-throwing logic.

After applying this patch, queries can be executed even if `traceparent` is invalid

image

### CODE REVIEW

**Comment by nikitamikhaylov** [comment]
@Mergifyio update

**Comment by nikitamikhaylov** [comment]
From my point of view the current behavior is Ok, because if we ignore the parse failures of traceparent then the whole future report will be ill formed?

**Comment by FrankChen021** [comment]
if we ignore the traceparent, there're two cases at ClickHouse side.
1. current call is determined to be sampled by probability, all span logs will be generated in a new trace id.
2. current call is not determined to be sampled, ClickHouse won't generated span logs. This does not affect upstream application's trace log report,  the only problem is that the trace log is not intact from upstream application's view -- we can't see the span logs from ClickHouse for such request.

These behaviors are the same as all other applications that provide trace functionality, such as pinpoint which is a well-known APM tool for java.

From the protocol compatibility perspective, if the upstream application evolves to implement newer opentelementry specification, say the version field is upgraded to '01' from current '00', if ClickHouse throws exception for such input, the whole system is down until ClickHouse upgrades to implements newer specification. I think that's not acceptable because such trace functionality is only a side function which should not hinder the query function.

**Comment by FrankChen021** [comment]
@nikitamikhaylov do you have any other opinions?

**Comment by nikitamikhaylov** [comment]
@Mergifyio update

**Comment by FrankChen021** [comment]
@nikitamikhaylov What do I need to do to get this PR merged? I'm going to make some other improvements which is based on the changes in this PR, I don't want any conflicts.

**Comment by FrankChen021** [comment]
Now a case in stateless tests fails, saying 

```

01460_mark_inclusion_search_crash | FAIL | 0.21
-- | -- | --
2022-01-05 07:12:45 [0412836093a3] 2022.01.05 07:12:45.502889 [ 408 ] {40204d15-4f43-44f4-af0e-e0bc2331a168}  executeQuery: Code: 158. DB::Exception: Limit for rows (controlled by 'max_rows_to_read' setting) exceeded, max rows: 5.00, current rows: 6.00. (TOO_MANY_ROWS) (version 21.13.1.1876) (from [::1]:35900) (comment: 01460_mark_inclusion_search_crash.sql) (in query: SELECT toUInt32(x), y, z FROM pk WHERE (x >= toDateTime(100000)) AND (x <= toDateTime(3));), Stack trace (when copying this message, always include the lines below): 2022-01-05 07:12:45  2022-01-05 07:12:45 0. DB::Exception::Exception(std::__1::basic_string, std::__1::allocator > const&, int, bool) @ 0xa5cf73a in /usr/lib/debug/.build-id/9f/e4c138df03b005.debug 2022-01-05 07:12:45 1. DB::SizeLimits::check(unsigned long, unsigned long, char const*, int, int) const @ 0x136d3188 in /usr/lib/debug/.build-id/9f/e4c138df03b005.debug 2022-01-05 07:12:45 2. DB::MergeTreeDataSelectExecutor::filterPartsByPrimaryKeyAndSkipIndexes(std::__1::vector, std::__1::allocator > >&&, std::__1::shared_ptr, DB::SelectQueryInfo const&, std::__1::shared_ptr const&, DB::KeyCondition const&, DB::MergeTreeReaderSettings const&, Poco::Logger*, unsigned long, std::__1::vector >&, bool)::$_1::operator()(unsigned long) const @ 0x140398e5 in /usr/lib/debug/.build-id/9f/e4c138df03b005.debug 2022-01-05 07:12:45 3. DB::MergeTreeDataSelectExecutor::filterPartsByPrimaryKeyAndSkipIndexes(std::__1::vector, std::__1::allocator > >&&, std::__1::shared_ptr, DB::SelectQueryInfo const&, std::__1::shared_ptr const&, DB::KeyCondition const&, DB::MergeTreeReaderSettings const&, Poco::Logger*, unsigned long, std::__1::vector >&, bool) @ 0x140361cb in /usr/lib/debug/.build-id/9f/e4c138df03b005.debug 2022-01-05 07:12:45 4. DB::ReadFromMergeTree::selectRangesToRead(std::__1::vector, std::__1::allocator > >, std::__1::shared_ptr const&, std::__1::shared_ptr const&, DB::SelectQueryInfo const&, std::__1::shared_ptr, unsigned int, std::__1::shared_ptr, std::__1::allocator >, long, std::__1::hash, std::__1::allocator > >, std::__1::equal_to, std::__1::allocator > >, std::__1::allocator, std::__1::allocator > const, long> > > >, DB::MergeTreeData const&, std::__1::vector, std::__1::allocator >, std::__1::allocator, std::__1::allocator > > > const&, bool, Poco::Logger*) @ 0x148027a0 in /usr/lib/debug/.build-id/9f/e4c138df03b005.debug 2022-01-05 07:12:45 5. DB::ReadFromMergeTree::selectRangesToRead(std::__1::vector, std::__1::allocator > >) const @ 0x1480132c in /usr/lib/debug/.build-id/9f/e4c138df03b005.debug 
2022-01-05 07:12:45 6. DB::ReadFromMergeTree::getAnalysisResult() const @ 0x14803dd8 in /usr/lib/debug/.build-id/9f/e4c138df03b005.debug 
2022-01-05 07:12:45 7. DB::ReadFromMergeTree::initializePipeline(DB::QueryPipelineBuilder&, DB::BuildQueryPipelineSettings const&) @ 0x14804327 in /usr/lib/debug/.build-id/9f/e4c138df03b005.debug 
2022-01-05 07:12:45 8. DB::ISourceStep::updatePipeline(std::__1::vector >, std::__1::allocator > > >, DB::BuildQueryPipelineSettings const&) @ 0x147d3c65 in /usr/lib/debug/.build-id/9f/e4c138df03b005.debug 
2022-01-05 07:12:45 9. DB::QueryPlan::buildQueryPipeline(DB::QueryPlanOptimizationSettings const&, DB::BuildQueryPipelineSettings const&) @ 0x147ed10d in /usr/lib/debug/.build-id/9f/e4c138df03b005.debug 
2022-01-05 07:12:45 10. DB::InterpreterSelectWithUnionQuery::execute() @ 0x137d7346 in /usr/lib/debug/.build-id/9f/e4c138df03b005.debug 
2022-01-05 07:12:45 11. DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr, bool, DB::QueryProcessingStage::Enum, DB::ReadBuffer*) @ 0x13a27ea4 in /usr/lib/debug/.build-id/9f/e4c138df03b005.debug 2022-01-05 07:12:45 12. DB::executeQuery(std::__1::basic_string, std::__1::allocator > const&, std::__1::shared_ptr, bool, DB::QueryProcessingStage::Enum) @ 0x13a259b5 in /usr/lib/debug/.build-id/9f/e4c138df03b005.debug 
2022-01-05 07:12:45 13. DB::TCPHandler::runImpl() @ 0x144f8c4f in /usr/lib/debug/.build-id/9f/e4c138df03b005.debug 2022-01-05 07:12:45 14. DB::TCPHandler::run() @ 0x1450c979 in /usr/lib/debug/.build-id/9f/e4c138df03b005.debug 
2022-01-05 07:12:45 15. Poco::Net::TCPServerConnection::start() @ 0x1715db4f in /usr/lib/debug/.build-id/9f/e4c138df03b005.debug 
2022-01-05 07:12:45 16. Poco::Net::TCPServerDispatcher::run() @ 0x1715ffa1 in /usr/lib/debug/.build-id/9f/e4c138df03b005.debug 
2022-01-05 07:12:45 17. Poco::PooledThread::run() @ 0x17310ca9 in /usr/lib/debug/.build-id/9f/e4c138df03b005.debug 
2022-01-05 07:12:45 18. Poco::ThreadImpl::runnableEntry(void*) @ 0x1730e3a0 in /usr/lib/debug/.build-id/9f/e4c138df03b005.debug 
2022-01-05 07:12:45 19. ? @ 0x7f9b4c2ec609 in ?

```

Obviously it has nothing to do with the changes in this PR.

**Comment by nikitamikhaylov** [comment]
Sorry, was on vacation..

**Comment by FrankChen021** [comment]
@nikitamikhaylov Thank you very much.

**Pull request merged**
