### PR TITLE
Allow skip null values when serailize tuple to json objects

### PR DESCRIPTION
**Pull request by taiyang-li**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Allow skip null values when serailize tuple to json objects, which makes it possible to keep compatiability with spark to_json function, which is also useful for gluten. 

Spark
``` sql 
0: jdbc:hive2://localhost:10000/> select to_json(named_struct('a', null, 'b', 3))
. . . . . . . . . . . . . . . . > ;
+---------------------------------------+
| to_json(named_struct(a, NULL, b, 3))  |
+---------------------------------------+
| {"b":3}                               |
+---------------------------------------+
```

CH
``` sql 
SELECT toJSONString(CAST((NULL, 3), 'Tuple(a Nullable(String), b Nullable(Int64))'))
SETTINGS output_format_json_named_tuples_as_objects = 1, output_format_json_skip_null_value_in_named_tuples = 0

Query id: 4fa460c4-90dd-4118-8344-ae4080aac030

┌─toJSONString(CAST((NULL, 3), 'Tuple(a Nullable(String), b Nullable(Int64))'))─┐
│ {"a":null,"b":"3"}                                                            │
└───────────────────────────────────────────────────────────────────────────────┘


SELECT toJSONString(CAST((NULL, 3), 'Tuple(a Nullable(String), b Nullable(Int64))'))
SETTINGS output_format_json_named_tuples_as_objects = 1, output_format_json_skip_null_value_in_named_tuples = 1

Query id: a6dd038e-4776-4548-bf66-b3816a92f514

┌─toJSONString(CAST((NULL, 3), 'Tuple(a Nullable(String), b Nullable(Int64))'))─┐
│ {"b":"3"}                                                                     │
└───────────────────────────────────────────────────────────────────────────────┘


```

### CODE REVIEW

**Comment by robot-ch-test-poll1** [comment]
*This is an automated comment for commit a02c49e16fb0b2ba10b89e9acb0e3ed53c46c546 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/55956/a02c49e16fb0b2ba10b89e9acb0e3ed53c46c546/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td><a href="https://github.com/ClickHouse/ClickHouse/actions/runs/6622100688">✅ success</a></td></tr>
<tbody>
</table>
</details>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/55956/a02c49e16fb0b2ba10b89e9acb0e3ed53c46c546/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Comment by taiyang-li** [comment]
Failed uts seem not related to this pr.

**Review by serxa — APPROVED** [review]
LGTM

**Comment by serxa** [comment]
Failed tests are unrelated:
Integration test `test_backup_restore_on_cluster/test_concurrency.py::test_create_or_drop_tables_during_backup[Replicated-ReplicatedMergeTree]`: `Cannot enqueue query on this replica, because it has replication lag of 1296 queries. Try other replica`
`test_delayed_replica_failover`: `Didn't raise when stale replicas are not allowed`
`test_system_clusters_actual_information`: `Client expected to be failed but succeeded! stdout: 0`
plus analyzer-related failures and hangup in stress tests...

**Comment by savinov** [comment]
Doesn't work with Kafka engine and format JSONEachRow: producer send null values even with settings output_format_json_named_tuples_as_objects = 1, output_format_json_skip_null_value_in_named_tuples = 1

**Comment by serxa** [comment]
@savinov could you please make a new issue for this problem?

**Comment by savinov** [comment]
@serxa https://github.com/ClickHouse/ClickHouse/issues/84683

**Pull request merged**
