### PR TITLE
Enable allow_remove_stale_moving_parts by default

### PR DESCRIPTION
**Pull request by vdimir**
### Changelog category (leave one):

- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
* Enable allow_remove_stale_moving_parts by default

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by robot-ch-test-poll** [comment]
This is an automated comment for commit f2ff693a39afb89a25ba7e70b6c88d406b91503f with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/54260/f2ff693a39afb89a25ba7e70b6c88d406b91503f/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Review by alexey-milovidov — APPROVED** [review]

**Comment by jrdi** [comment]
Should `allow_remove_stale_moving_parts` be added to `src/Storages/MergeTree/MergeTreeSettings.h` to be properly documented?

**Comment by vdimir** [comment]
@jrdi Now it's already enabled by default in 23.3, 23.6, 23.7, 23.8 and current version

**Comment by azat** [comment]
> with allow_remove_stale_moving_parts = false behaviour is not correct.

@vdimir do you mean this? https://github.com/ClickHouse/ClickHouse/blob/7b6548157c9216eb52867ba10c8c9bd30a3492dd/src/Storages/MergeTree/MergeTreePartsMover.cpp#L264

**Comment by jetgm** [comment]
@vdimir When I upgraded ClickHouse from 22.8 to 23.8, the database startup process was very slow. Upon checking the logs, I found that two large tables were consistently performing remove operations on moving directory files, and the directory contained over ten thousand subdirectories. 
We waited for several hours late at night for it to finish removing. Can the operation of 'remove' be changed to asynchronous so that it doesn't affect service startup?

**Pull request merged**
