### PR TITLE
Cherry pick #55335 to 23.3: Fix SIGSEGV in MergeSortingPartialResultTransform (due to zero chunks after remerge())

### PR DESCRIPTION
**Pull request by robot-clickhouse-ci-2**
Original pull-request #55335

This pull-request is a first step of an automated backporting.
It contains changes like after calling a local command `git cherry-pick`.
If you intend to continue backporting this changes, then resolve all conflicts if any.
Otherwise, if you do not want to backport them, then just close this pull-request.

The check results does not matter at this step - you can safely ignore them.

### Note

This pull-request will be merged automatically as it reaches the mergeable state, **do not merge it manually**.

### If the PR was closed and then reopened

If it stuck, check https://github.com/ClickHouse/ClickHouse/pull/55335 for `pr-backports-created` and delete it if necessary. Manually merging will do nothing, since `pr-backports-created` prevents the original PR https://github.com/ClickHouse/ClickHouse/pull/55335 from being processed.

If you want to recreate the PR: delete the `pr-cherrypick` label and delete this branch.
You may also need to delete the `pr-backports-created` label from the original PR.

### CODE REVIEW

**Comment by robot-ch-test-poll3** [comment]
Dear @azat, @alexey-milovidov, the PR is not updated for 1d1h9m0s. Please, either resolve the conflicts, or close it to finish the backport process of #55335

**Comment by robot-ch-test-poll1** [comment]
Dear @azat, @alexey-milovidov, the PR is not updated for 1d0h49m39s. Please, either resolve the conflicts, or close it to finish the backport process of #55335

**Comment by robot-clickhouse** [comment]
Dear @azat, @alexey-milovidov, the PR is not updated for 1d0h4m46s. Please, either resolve the conflicts, or close it to finish the backport process of #55335

**Comment by robot-ch-test-poll3** [comment]
Dear @azat, @alexey-milovidov, the PR is not updated for 1d1h0m0s. Please, either resolve the conflicts, or close it to finish the backport process of #55335

**Comment by robot-ch-test-poll2** [comment]
Dear @azat, @alexey-milovidov, the PR is not updated for 1d0h58m34s. Please, either resolve the conflicts, or close it to finish the backport process of #55335

**Comment by robot-ch-test-poll** [comment]
Dear @azat, @alexey-milovidov, the PR is not updated for 1d0h3m26s. Please, either resolve the conflicts, or close it to finish the backport process of #55335

**Comment by robot-ch-test-poll2** [comment]
Dear @azat, @alexey-milovidov, the PR is not updated for 1d0h5m18s. Please, either resolve the conflicts, or close it to finish the backport process of #55335

**Comment by robot-clickhouse-ci-2** [comment]
Dear @azat, @alexey-milovidov, the PR is not updated for 1d0h52m12s. Please, either resolve the conflicts, or close it to finish the backport process of #55335

**Comment by robot-ch-test-poll** [comment]
Dear @azat, @alexey-milovidov, the PR is not updated for 1d0h0m42s. Please, either resolve the conflicts, or close it to finish the backport process of #55335

**Comment by robot-ch-test-poll3** [comment]
Dear @azat, @alexey-milovidov, the PR is not updated for 1d0h58m18s. Please, either resolve the conflicts, or close it to finish the backport process of #55335

**Comment by robot-clickhouse-ci-2** [comment]
Dear @azat, @alexey-milovidov, the PR is not updated for 1d0h0m50s. Please, either resolve the conflicts, or close it to finish the backport process of #55335

**Comment by robot-clickhouse-ci-1** [comment]
Dear @azat, @alexey-milovidov, the PR is not updated for 1d0h58m57s. Please, either resolve the conflicts, or close it to finish the backport process of #55335

**Comment by robot-ch-test-poll2** [comment]
Dear @azat, @alexey-milovidov, the PR is not updated for 1d0h0m6s. Please, either resolve the conflicts, or close it to finish the backport process of #55335

**Comment by robot-ch-test-poll1** [comment]
Dear @azat, @alexey-milovidov, the PR is not updated for 1d0h0m11s. Please, either resolve the conflicts, or close it to finish the backport process of #55335

**Comment by robot-clickhouse-ci-1** [comment]
Dear @azat, @alexey-milovidov, the PR is not updated for 1d1h2m33s. Please, either resolve the conflicts, or close it to finish the backport process of #55335

**Comment by robot-clickhouse** [comment]
Dear @azat, @alexey-milovidov, the PR is not updated for 1d1h19m7s. Please, either resolve the conflicts, or close it to finish the backport process of #55335

**Comment by robot-clickhouse** [comment]
Dear @azat, @alexey-milovidov, the PR is not updated for 1d0h2m21s. Please, either resolve the conflicts, or close it to finish the backport process of #55335

**Comment by robot-ch-test-poll4** [comment]
Dear @azat, @alexey-milovidov, the PR is not updated for 1d0h46m17s. Please, either resolve the conflicts, or close it to finish the backport process of #55335

**Comment by robot-clickhouse** [comment]
Dear @azat, @alexey-milovidov, the PR is not updated for 1d0h49m49s. Please, either resolve the conflicts, or close it to finish the backport process of #55335

**Comment by robot-clickhouse** [comment]
Dear @azat, @alexey-milovidov, the PR is not updated for 1d0h1m15s. Please, either resolve the conflicts, or close it to finish the backport process of #55335

**Comment by robot-ch-test-poll3** [comment]
Dear @azat, @alexey-milovidov, the PR is not updated for 1d0h58m41s. Please, either resolve the conflicts, or close it to finish the backport process of #55335

**Comment by robot-clickhouse-ci-2** [comment]
Dear @azat, @alexey-milovidov, the PR is not updated for 1d0h2m32s. Please, either resolve the conflicts, or close it to finish the backport process of #55335

**Comment by robot-ch-test-poll** [comment]
Dear @azat, @alexey-milovidov, the PR is not updated for 1d0h57m7s. Please, either resolve the conflicts, or close it to finish the backport process of #55335

**Comment by robot-clickhouse-ci-2** [comment]
Dear @azat, @alexey-milovidov, the PR is not updated for 1d1h0m55s. Please, either resolve the conflicts, or close it to finish the backport process of #55335

**Comment by robot-clickhouse** [comment]
Dear @azat, @alexey-milovidov, the PR is not updated for 1d1h1m46s. Please, either resolve the conflicts, or close it to finish the backport process of #55335

**Comment by robot-clickhouse** [comment]
Dear @azat, @alexey-milovidov, the PR is not updated for 1d1h9m52s. Please, either resolve the conflicts, or close it to finish the backport process of #55335

**Comment by robot-ch-test-poll3** [comment]
Dear @azat, @alexey-milovidov, the PR is not updated for 1d0h0m49s. Please, either resolve the conflicts, or close it to finish the backport process of #55335

**Comment by robot-clickhouse-ci-2** [comment]
Dear @azat, @alexey-milovidov, the PR is not updated for 1d1h2m45s. Please, either resolve the conflicts, or close it to finish the backport process of #55335

**Comment by robot-clickhouse-ci-1** [comment]
Dear @azat, @alexey-milovidov, the PR is not updated for 1d0h2m32s. Please, either resolve the conflicts, or close it to finish the backport process of #55335

**Comment by robot-ch-test-poll3** [comment]
Dear @azat, @alexey-milovidov, the PR is not updated for 1d0h57m49s. Please, either resolve the conflicts, or close it to finish the backport process of #55335

**Comment by robot-ch-test-poll4** [comment]
Dear @azat, @alexey-milovidov, the PR is not updated for 1d24h57m5s. Please, either resolve the conflicts, or close it to finish the backport process of #55335

**Comment by robot-ch-test-poll4** [comment]
Dear @azat, @alexey-milovidov, the PR is not updated for 1d25h2m55s. Please, either resolve the conflicts, or close it to finish the backport process of #55335

**Pull request closed without merging**
