### PR TITLE
Fix stupid bug in ATTACH TABLE

### PR DESCRIPTION
**Pull request by tavplubix**
Changelog category (leave one):
- Bug Fix (user-visible misbehaviour in official stable or prestable release)

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Setting `database_atomic_wait_for_drop_and_detach_synchronously` worked incorrectly for `ATTACH TABLE` query when previously detached table is still in use, It's fixed.

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]
LGTM

true <-> false

**Comment by alexey-milovidov** [comment]
Master is broken, cannot merge.

**Comment by alexey-milovidov** [comment]
@mergifyio update

**Comment by tavplubix** [comment]
Stateless tests flaky check (address, actions) - OK
Stress test (thread, actions) - #35615

**Pull request merged**
