### PR TITLE
Translate to zh: use-case/time-serial

### PR DESCRIPTION
**Pull request by ghost**
Changelog category (leave one): 
- Documentation (changelog entry is not required) 

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
...

> Information about CI checks: https://clickhouse.tech/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by cnmade** [comment]
@kitaisreal I need your help.
```
ERROR:mkdocs.commands.build:Error reading page 'faq/use-cases/time-series.md': [Errno 36] File name too long: '/repo_path/docs/zh/faq/use-cases/time-series.md'
```
what does it said file name too long?

is there any limit for it?

**Comment by cnmade** [comment]
The log file location:
https://s3.amazonaws.com/clickhouse-test-reports/33899/c57d08b76ca17352f86966f748628df71bcd5c9b/docs_check__actions_/output.log

**Comment by cnmade** [comment]
```
OSError: [Errno 36] File name too long: '/repo_path/docs/zh/faq/use-cases/time-series.md'

```

The file name not changed, i just update the content of the file, not change file name

**Comment by cnmade** [comment]
Or @alexey-milovidov may you please help?

**Comment by cnmade** [comment]
I am trying to delete the old file, and create the new file, see is it will be ok

**Review by kitaisreal — APPROVED** [review]

**Comment by cnmade** [comment]
the error log now:
```bash
DocsCheck
The self-hosted runner: i-09250028ccff7da09 lost communication with the server. Verify the machine is running and has a healthy network connection. Anything in your workflow that terminates the runner process, starves it for CPU/Memory, or blocks its network access can cause this error.
```

I am not sure what can i do next.

**Comment by kitaisreal** [comment]
@cnmade it seems like there are issues in our CI for documentation check. We need to wait until it will be fixed.

**Comment by cnmade** [comment]
@kitaisreal did the CI problem fixed? any progress?

**Comment by cnmade** [comment]
I will recreate pull request for this. close it for now.

**Comment by cnmade** [comment]
This pull request closed , and the reworked pull request is here:
https://github.com/ClickHouse/ClickHouse/pull/33967

**Pull request closed without merging**
