### PR TITLE
Fix deadlock in async inserts to `Log` tables via native protocol

### PR DESCRIPTION
**Pull request by CurtizJ**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fixed deadlock in async inserts to `Log` tables via native protocol.

Required for #59915.

### CODE REVIEW

**Comment by robot-ch-test-poll2** [comment]
*This is an automated comment for commit b9d6f4b3ed999e217d0be22f1580b4d19de4e3d9 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/61055/b9d6f4b3ed999e217d0be22f1580b4d19de4e3d9/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
It says the test didn't catch the bug - does it reproduce with some probability? Ok then.

**Comment by CurtizJ** [comment]
No, it reproduces always, but bugfix validation says: `[with NOT_OK] Nothing to run`, which is strange.

**Comment by CurtizJ** [comment]
It failed to start because of:
```
2024.03.07 18:06:13.915309 [ 771 ] {} <Error> Application: Code: 137. DB::Exception: ObjectStorageFactory: unknown object storage type: azure. (UNKNOWN_ELEMENT_IN_CONFIG), Stack trace (when copying this message, always include the lines below):

0. ./build_docker/./src/Common/Exception.cpp:96: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000cf5565b
1. DB::Exception::Exception<String&>(int, FormatStringHelperImpl<std::type_identity<String&>::type>, String&) @ 0x00000000078e0403
2. ./build_docker/./src/Disks/ObjectStorages/ObjectStorageFactory.cpp:75: DB::ObjectStorageFactory::create(String const&, Poco::Util::AbstractConfiguration const&, String const&, std::shared_ptr<DB::Context const> const&, bool) const @ 0x0000000011042cce
3. ./build_docker/./src/Disks/ObjectStorages/RegisterDiskObjectStorage.cpp:0: std::shared_ptr<DB::IDisk> std::__function::__policy_invoker<std::shared_ptr<DB::IDisk> (String const&, Poco::Util::AbstractConfiguration const&, String const&, std::shared_ptr<DB::Context const>, std::map<String, std::shared_ptr<DB::IDisk>, std::less<String>, std::allocator<std::pair<String const, std::shared_ptr<DB::IDisk>>>> const&, bool, bool)>::__call_impl<std::__function::__default_alloc_func<DB::registerDiskObjectStorage(DB::DiskFactory&, bool)::$_0, std::shared_ptr<DB::IDisk> (String const&, Poco::Util::AbstractConfiguration const&, String const&, std::shared_ptr<DB::Context const>, std::map<String, std::shared_ptr<DB::IDisk>, std::less<String>, std::allocator<std::pair<String const, std::shared_ptr<DB::IDisk>>>> const&, bool, bool)>>(std::__function::__policy_storage const*, String const&, Poco::Util::AbstractConfiguration const&, String const&, std::shared_ptr<DB::Context const>&&, std::map<String, std::shared_ptr<DB::IDisk>, std::less<String>, std::allocator<std::pair<String const, std::shared_ptr<DB::IDisk>>>> const&, bool, bool) @ 0x0000000011041cd7
4. ./contrib/llvm-project/libcxx/include/__functional/function.h:0: ? @ 0x0000000010fe7de0
5. ./build_docker/./src/Disks/DiskSelector.cpp:52: DB::DiskSelector::initialize(Poco::Util::AbstractConfiguration const&, String const&, std::shared_ptr<DB::Context const>, std::function<bool (Poco::Util::AbstractConfiguration const&, String const&, String const&)>) @ 0x0000000010feb8e3
6. ./contrib/llvm-project/libcxx/include/__functional/function.h:818: ? @ 0x000000001114df7d
7. ./build_docker/./src/Interpreters/Context.cpp:4050: DB::Context::getDisksMap(std::lock_guard<std::mutex>&) const @ 0x000000001114e414
8. ./contrib/llvm-project/libcxx/include/atomic:958: DB::Context::getDisksMap() const @ 0x000000001114f279
9. ./build_docker/./src/Interpreters/ServerAsynchronousMetrics.cpp:0: DB::ServerAsynchronousMetrics::updateImpl(std::chrono::time_point<std::chrono::system_clock, std::chrono::duration<long long, std::ratio<1l, 1000000l>>>, std::chrono::time_point<std::chrono::system_clock, std::chrono::duration<long long, std::ratio<1l, 1000000l>>>, bool, bool, std::unordered_map<String, DB::AsynchronousMetricValue, std::hash<String>, std::equal_to<String>, std::allocator<std::pair<String const, DB::AsynchronousMetricValue>>>&) @ 0x0000000011cf9684
10. ./base/glibc-compatibility/musl/clock_gettime.c:62: DB::AsynchronousMetrics::update(std::chrono::time_point<std::chrono::system_clock, std::chrono::duration<long long, std::ratio<1l, 1000000l>>>, bool) @ 0x000000000d05a87d
11. ./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:714: DB::AsynchronousMetrics::start() @ 0x000000000d04a763
12. ./build_docker/./programs/server/Server.cpp:0: DB::Server::main(std::vector<String, std::allocator<String>> const&) @ 0x000000000d0cf150
13. ./build_docker/./base/poco/Util/src/Application.cpp:0: Poco::Util::Application::run() @ 0x00000000158bbda6
14. ./build_docker/./programs/server/Server.cpp:417: DB::Server::run() @ 0x000000000d0bac91
15. ./build_docker/./base/poco/Util/src/ServerApplication.cpp:132: Poco::Util::ServerApplication::run(int, char**) @ 0x00000000158c4c19
16. ./build_docker/./programs/server/Server.cpp:0: mainEntryClickHouseServer(int, char**) @ 0x000000000d0b7d4a
17. ./build_docker/./programs/main.cpp:0: main @ 0x00000000078c47d8
18. ? @ 0x00007fdb706a7d90
19. ? @ 0x00007fdb706a7e40
20. _start @ 0x00000000060c312e
 (version 24.2.1.2248 (official build))
2024.03.07 18:06:13.915369 [ 771 ] {} <Information> Application: shutting down
```

**Pull request merged**
