### PR TITLE
Unify query elapsed time measurements

### LINKED ISSUE #33437: ExceptionBeforeStart timestamps may be confusing.
```
type:                                  ExceptionBeforeStart
event_time:                            2022-01-06 16:58:03
event_time_microseconds:               2022-01-06 16:58:03.334283
query_start_time:                      2022-01-06 16:58:03
query_start_time_microseconds:         2022-01-06 16:58:03.334283
....
query:                                 truncate table XXXX
exception:                             Code: 473, e.displayText() = DB::Exception: WRITE locking attempt on "XXXX" has timed out! (120000ms)
```

In logs;
```
2022.01.06 16:58:03.334343 [ 1157 ] {0fbfdca0-3a42-4de5-9923-cbc7f9b22b44} <Debug> executeQuery: (from 10.131.52.244:41054, user: admin) truncate table XXXX
2022.01.06 17:00:03.338396 [ 1157 ] {0fbfdca0-3a42-4de5-9923-cbc7f9b22b44} <Error> executeQuery: Code: 473, e.displayText() = DB::Exception: WRITE locking attempt on "XXXX" has timed out! (120000ms)
```

Maybe we should write into `event_time` the actual timestamp of an exception instead of repeating `query_start_time` there once again?

### LINKED ISSUE #42555: Incorrect elapsed time in JSON format result when a query has subqueries
**Describe the unexpected behaviour**
The `elapsed` field from JSON format output is wrong (shorter) than the actual query execution time when the query has subqueries.

**How to reproduce**

Data: the hits dataset from clickbench.
Query:
```
SELECT SearchPhrase FROM (select SearchPhrase, URL, EventTime FROM hits WHERE CounterID = 62 AND EventDate >= '2013-07-01' AND EventDate <= '2013-07-31' AND DontCountHits = 0 AND IsRefresh = 0 AND URL <> '') WHERE URL LIKE '%google%' ORDER BY EventTime LIMIT 10 format JSON;
```

* Which ClickHouse server version to use
ClickHouse 22.10.1.1

* Which interface to use, if matters
Both http and tcp client.

**Expected behavior**
The time from the 'elapsed' field and that from `time` command or tcp client should be close.

**Error message and/or stacktrace**
via TCP client
image

via curl
image

**Additional context**
* For HTTP requests, the cause looks like that JSONRowOutputFormat is created after the query pipeline has been created, which may take a while when there are subqueries. Consequently, the Stopwatch starts late and the measured time is then shorter.
* For TCP client, the reason could be that the JSONRowOutputFormat is created in the client after receiving the first block, which again is later than the query submission time.

### PR DESCRIPTION
**Pull request by Algunenano**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
- Unify query elapsed time measurements

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

Several changes:
- `ExceptionBeforeStart` queries now show true elapsed time and not 0 as before.
- The elapsed time used in the process list (used in system.processes or to check max_execution_time) is now the same as the one that will be reported as elapsed time in the query_log.
- The Statistics inside formats has been cleaned up and unified.
- The elapsed time output for JSON/XML/etc (formats with embedded stats) now matches the time reported by the server (if generated in the server, like using the HTML endpoint), or the one reported by the CLI (when using that endpoint).
- Minor changes to `add-test` so it creates new shell tests as executable.

Closes https://github.com/ClickHouse/ClickHouse/issues/42555
Closes https://github.com/ClickHouse/ClickHouse/issues/33437

### CODE REVIEW

**Comment by nudles** [comment]
If you want to test the HTTP/curl case, the following one could be considered,

```
run_one_sql() {
  curlTime=$(${CLICKHOUSE_CURL_COMMAND} -o ${CLICKHOUSE_TMP}/{CLICKHOUSE_DATABASE}_$(date +%s)_02883_q4.txt -s -w '%{time_total}\n' "${CLICKHOUSE_URL}?query=$1&")
  cat ${CLICKHOUSE_TMP}/{CLICKHOUSE_DATABASE}_$(date +%s)_02883_q4.txt .txt\| awk -v curlTime=$curlTime '/elapsed/ {printf "%.1f", curlTime - $2}'
  rm ${CLICKHOUSE_TMP}/{CLICKHOUSE_DATABASE}_$(date +%s)_02883_q4.txt .txt
}

q="WITH%20%28%0A%20%20%20%20%20%20%20%20SELECT%20sleepEachRow%281.0%29%0A%20%20%20%20%29%20AS%20sub%0ASELECT%20%2A%0AFROM%0A%28%0A%20%20%20%20SELECT%20%2A%0A%20%20%20%20FROM%20system.one%0A%29%0AFORMAT%20JSON%0ASETTINGS%20enable_global_with_statement%20%3D%201%22"
run_one_sql $q


```

**Comment by Algunenano** [comment]
Hitting rate limits from Github API:
```
INFO:root:Getting URL with 5 tries and sleep 0 in between: https://api.github.com/repos/ClickHouse/ClickHouse/pulls/43455
INFO:root:Exception '403 Client Error: rate limit exceeded for url: https://api.github.com/repos/ClickHouse/ClickHouse/pulls/43455' while getting, retry 1
INFO:root:Exception '403 Client Error: rate limit exceeded for url: https://api.github.com/repos/ClickHouse/ClickHouse/pulls/43455' while getting, retry 2
INFO:root:Exception '403 Client Error: rate limit exceeded for url: https://api.github.com/repos/ClickHouse/ClickHouse/pulls/43455' while getting, retry 3
INFO:root:Exception '403 Client Error: rate limit exceeded for url: https://api.github.com/repos/ClickHouse/ClickHouse/pulls/43455' while getting, retry 4
WARNING:root:Unable to get pull request event 43455 from API, fallback to received event. Exception: 403 Client Error: rate limit exceeded for url: https://api.github.com/repos/ClickHouse/ClickHouse/pulls/43455
``

**Comment by Algunenano** [comment]
Tests failures related to `00176_bson_parallel_parsing`, which has already been disabled because of it: https://github.com/ClickHouse/ClickHouse/pull/43550

**Comment by azat** [comment]
>ExceptionBeforeStart queries now show true elapsed time and not 0 as before.

Seems that this fixes #33437 ?

**Comment by Algunenano** [comment]
> Seems that this fixes https://github.com/ClickHouse/ClickHouse/issues/33437 ?

Yes. I think so. I'll add it to the list in the description

**Comment by Algunenano** [comment]
> Why still RFC? Don't you want this to be merged?

Sorry, I've just updated it. The changes look the way to go to me.

**Comment by Algunenano** [comment]
Ther errors in the CI seem unrelated (a bunch of connection failure to Azure which led to CH not starting).

**Review by nikitamikhaylov — APPROVED** [review]

**Pull request merged**
