### PR TITLE
Fix ColumnVariant permutation

### LINKED ISSUE #68677: JSON WHERE clause
Version: 24.8.1.2684

https://fiddle.clickhouse.com/d13483a4-be1e-465a-8647-1397fde51b89

I'm testing the new JSON type in a ReplacingMergeTree. I bumped into the following situation:

```sql
SELECT * FROM test_new_json_type FINAL
WHERE data.foo2 is not null;

Error: Received exception from server (version 24.8.1):
Code: 9. DB::Exception: Received from localhost:9000. DB::Exception: Size of permutation (0) is less than required (1). (SIZES_OF_COLUMNS_DOESNT_MATCH)
```

Specific conditions I've noticed:
- new (experimental) `JSON` type
- the JSON data has different properties
- `FINAL` is used 
- `WHERE` clause is on a `JSON` property that might not exist
- happens only after new inserts (there are new unmerged parts at this stage?)
- `OPTIMIZE TABLE ... FINAL` fixes it (all parts are merged and solves the problem?)

Narrowing it down:
- does not happen when `FINAL` is not used
- does not happen when `WHERE` is not used (with or without `FINAL`)
- does not happen when used JSON property exists in all data

Reproducible this way:
```sql
SET allow_experimental_json_type = 1;

CREATE TABLE test_new_json_type(id UInt32, data JSON, version UInt64) ENGINE=ReplacingMergeTree(version) ORDER BY id;

INSERT INTO test_new_json_type format JSONEachRow
{"id":1,"data":{"foo1":"bar"},"version":1}
{"id":2,"data":{"foo2":"bar"},"version":1}
{"id":3,"data":{"foo2":"bar"},"version":1}
;

-- works
SELECT * FROM test_new_json_type FINAL
WHERE data.foo2 is not null
;

-- "replace" row 2
INSERT INTO test_new_json_type
SELECT id, '{"foo2":"baz"}' AS _data, version+1 AS _version
FROM test_new_json_type where id=2;

-- Code: 9. DB::Exception: Size of permutation (0) is less than required (1). (SIZES_OF_COLUMNS_DOESNT_MATCH) (version 24.8.1.2684 (official build))
SELECT * FROM test_new_json_type FINAL
WHERE data.foo2 is not null
;

-- works
SELECT * FROM test_new_json_type 
WHERE data.foo2 is not null
;

-- works
SELECT * FROM test_new_json_type FINAL
;

-- fix
OPTIMIZE TABLE test_new_json_type FINAL;

-- works again
SELECT * FROM test_new_json_type FINAL
WHERE data.foo2 is not null
;
```

### PR DESCRIPTION
**Pull request by Avogar**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix possible error `Size of permutation (0) is less than required (...)` during Variant column permutation.

Closes https://github.com/ClickHouse/ClickHouse/issues/68677

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Run only fuzzers related jobs (libFuzzer fuzzers, AST fuzzers, etc.)
- [ ]  Exclude: AST fuzzers
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-ch-test-poll** [comment]
*This is an automated comment for commit 38f9ef6bc95550d727bc56627fd029741e99177c with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/68681/38f9ef6bc95550d727bc56627fd029741e99177c/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Style check</td><td>Runs a set of checks to keep the code style clean. If some of tests failed, see the related log from the report</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/68681/38f9ef6bc95550d727bc56627fd029741e99177c/style_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Comment by Avogar** [comment]
> AST fuzzer (debug) — Logical error: 'n < size()'.

Fuzzer found bug in JSON, will fix it separately

**Review by novikd — APPROVED** [review]

**Comment by Avogar** [comment]
> Fuzzer found bug in JSON, will fix it separately

UPD: it's also related to permutation in ColumnVariant, will add fix here

**Comment by novikd** [comment]
@Avogar I suppose we need to modify all the backport PRs because the test uses the `JSON` data type with `allow_experimental_json_type`, which didn't exist in the previous version.

**Comment by Avogar** [comment]
Yes, I will modify them. Will try to create a test without JSON

**Pull request merged**
