### PR TITLE
Issue #1000 

### PR DESCRIPTION
**Pull request by kolobaev**
remove 'diagnostic ignored -Wunused-private-field' in Collator.app

### CODE REVIEW

**Comment by robot-metrika-test** [comment]
Can one of the admins verify this patch?

**Comment by robot-metrika-test** [comment]
Can one of the admins verify this patch?

**Comment by alexey-milovidov** [comment]
What is the motivation of this change?
As I remember, the warning appears when compiling with clang
(note than clang understands `#pragma GCC diagnostic` as well)
And when disabling ICU, private field is really unused.

(And I decided to keep ifdefs in .cpp file, not in header, though it's also possible to move private field inside ifdef in header file.)

**Comment by alexey-milovidov** [comment]
PS. This is really PR #1001. Nice try!

**Comment by alexey-milovidov** [comment]
Ok, now I understand the motivation...

**Comment by alexey-milovidov** [comment]
Just change `pragma GCC diagnostic` to `pragma clang diagnostic`.

**Comment by kolobaev** [comment]
I changed "pragma GCC diagnostic to pragma clang diagnostic."
**make failed:**

ClickHouse/dbms/src/Common/Collator.cpp:13:0: error: ignoring #pragma clang diagnostic [-Werror=unknown-pragmas]
     #pragma clang diagnostic ignored "-Wunused-private-field"

cc1plus: all warnings being treated as errors
dbms/CMakeFiles/dbms.dir/build.make:5942: recipe for target 'dbms/CMakeFiles/dbms.dir/src/Common/Collator.cpp.o' failed
make[2]: *** [dbms/CMakeFiles/dbms.dir/src/Common/Collator.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
^Cmake[2]: *** Deleting file 'dbms/CMakeFiles/dbms.dir/src/Dictionaries/ComplexKeyCacheDictionary.cpp.o'
dbms/CMakeFiles/dbms.dir/build.make:3878: recipe for target 'dbms/CMakeFiles/dbms.dir/src/Dictionaries/CacheDictionary.cpp.o' failed
make[2]: *** [dbms/CMakeFiles/dbms.dir/src/Dictionaries/CacheDictionary.cpp.o] Interrupt
dbms/CMakeFiles/dbms.dir/build.make:3926: recipe for target 'dbms/CMakeFiles/dbms.dir/src/Dictionaries/ComplexKeyCacheDictionary.cpp.o' failed
make[2]: *** [dbms/CMakeFiles/dbms.dir/src/Dictionaries/ComplexKeyCacheDictionary.cpp.o] Interrupt
CMakeFiles/Makefile2:4039: recipe for target 'dbms/CMakeFiles/dbms.dir/all' failed
make[1]: *** [dbms/CMakeFiles/dbms.dir/all] Interrupt
Makefile:160: recipe for target 'all' failed
make: *** [all] Interrupt

**Comment by alexey-milovidov** [comment]
It should be like this:

```
#if __clang__
    #pragma clang diagnostic push
    #pragma clang diagnostic ignored "-Wunused-private-field"
#endif
```

**Comment by kolobaev** [comment]
thx, it works!

**Pull request merged**
