### PR TITLE
[do not merge] run perf test against clang-10 and 11

### PR DESCRIPTION
**Pull request by akuzm**
Temporary PR to run some CI checks.

Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
1. Is the result correct?
2. What is the geomean difference across all tests / all queries?

**Comment by akuzm** [comment]
> 2. What is the geomean difference across all tests / all queries?

Geometric mean of which value exactly, given the new and old query time? I started adding it and realized I don't understand what to add. Something like `1 / avg( 1 / (new_time / old_time))` doesn't make sense. What I have now in `Test Performance Changes` is just relative change (`(new - old) / old`) of the time of entire test (sum of all query times). A problem with this measure is that the relative contribution of the query depends on how long it is. Our queries are now of the same order of time, but still this is not good enough. Maybe I should calculate min/med/max relative changes across all queries in a test...

Another problem with the relative change metric is that it's not symmetric -- you can't have more than 100% speedup, but an infinitely large slowdown is possible. The 'times' metric you asked me to add is better in this sense. But I'm not sure how to best average it.

**Comment by alexey-milovidov** [comment]
> Geometric mean of which value exactly, given the new and old query time?

1. For every query, calculate old_time / new_time to measure relative boost, like 2.0 if new build is 2x faster and 0.5 if new build is 2x slower.
2. Calculate geomean like this: exp(avg(log(x)))

Example: suppose we have two queries,
```
     old_time new_time      old_time / new_time     log2(old_time / new_time)
Q1    1 sec    0.5 sec          2.0                          1
Q2  100 sec    200 sec          0.5                         -1

avg(log2(old_time / new_time)) = 0
exp2(avg(log2(old_time / new_time))) = 1

The geomean is 1.
That means the old and new builds are no faster no slower.
```

If we want to calculate the geometric mean across groups of queries (tests), first calculate geometric means across queries of each group then calculate geometric mean of means.

**Comment by alexey-milovidov** [comment]
> Something like 1 / avg( 1 / (new_time / old_time)) doesn't make sense.

What you type is harmonic mean, not geometric mean.

**Comment by alexey-milovidov** [comment]
`Total: +1.211x`
It is 21% slower that is unbelievably slow.

I hope there are a few simple reasons why it's slower, like https://github.com/ClickHouse/ClickHouse/pull/12278/files#diff-59b750fae16a0cf9bd548fa8b0b277e4R207

**Comment by akuzm** [comment]
https://clickhouse-test-reports.s3.yandex.net/13617/9a3627103693d215a6a02c2d74f13911d9384f50/performance_comparison/report.html#test-performance-changes

I disabled the profiler, and now clang is 1% faster... not sure what's going on.

**Comment by akuzm** [comment]
https://clickhouse-test-reports.s3.yandex.net/13617/bb8ce1fbb7be14f5840ed39675f87b394dfcde25/performance_comparison/report.html#fail1

Enabled the profiler back, +20% again.

**Comment by alexey-milovidov** [comment]
```
clickhouse-benchmark <<< "SELECT ignore(SHA256(toString(1000000000+number))) FROM numbers_mt(10000000) FORMAT Null"
```

gcc: 0.050 sec.
clang: 0.052 sec.

```
clickhouse-benchmark --query_profiler_real_time_period_ns 10000000 <<< "SELECT ignore(SHA256(toString(1000000000+number))) FROM numbers_mt(10000000) FORMAT Null"
```

gcc: 0.145 sec.
clang: 0.193 sec.

Real time profiler has very high overhead when multiple threads are involved.

```
clickhouse-benchmark --query_profiler_cpu_time_period_ns 10000000 <<< "SELECT ignore(SHA256(toString(1000000000+number))) FROM numbers_mt(10000000) FORMAT Null"
```

gcc: 0.124 sec.
clang: 0.153 sec.

CPU profiler also.

100 Hz sampling rate maybe too high.

**Comment by alexey-milovidov** [comment]
Proposed solution: always compare queries with disabled profiler.
Only if performance differs - run them with profiler to collect profile data.

**Comment by alexey-milovidov** [comment]
@akuzm Simply recompiling libunwind with gcc does not help.
It happens because clang generates different frame info (that appeared to be more difficult to parse).

**Comment by akuzm** [comment]
https://github.com/ClickHouse/ClickHouse/pull/15239

**Pull request closed without merging**
