### PR TITLE
Revert #11023

### PR DESCRIPTION
**Pull request by alesapin**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by alesapin** [comment]
Wait only for functional tests.

**Comment by alexey-milovidov** [comment]
What is the reason?

**Comment by alexey-milovidov** [comment]
Answer: tests under sanitizers slowed down too much.

**Comment by azat** [comment]
Plus @akuzm was noted that this may/will break parallel tests execution

**Pull request merged**
