### PR TITLE
fix bitmapAnd error when intersecting an aggregated bitmap and a scalar bitmap

### PR DESCRIPTION
**Pull request by moon03432**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Bug Fix

Changelog entry (up to few sentences, required except for Non-significant/Documentation categories):

fix bitmapAnd error when intersecting an aggregated bitmap and a scalar bitmap.

Detailed description (optional):

similar to issue #5479: bitmapHasAny in scalar subquery causes segment fault

### CODE REVIEW

**Review by alexey-milovidov — CHANGES_REQUESTED** [review]
Need to add a test.

**Comment by moon03432** [comment]
@alexey-milovidov hi, test has been added in 00829_bitmap_function.sql and reference

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
Thank you!

**Comment by vitlibar** [comment]
Conflict with 19.16.

**Pull request merged**
