### PR TITLE
Fix bug in replication queue which can lead to premature mutation finish

### PR DESCRIPTION
**Pull request by alesapin**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
It was possible that mutation was marked as done before all the parts were mutated. As a result, it was possible to non-mutated data for a short time after alter with `mutations_sync=2`.

An attempt to fix  https://s3.amazonaws.com/clickhouse-test-reports/43194/4012b46a87daa5ea375055674920205cc52bd5b4/stateless_tests__tsan__[1/3].html

Fixes https://github.com/ClickHouse/ClickHouse/pull/43231

### CODE REVIEW

**Comment by alesapin** [comment]
Reverts https://github.com/ClickHouse/ClickHouse/pulls

**Comment by alesapin** [comment]
Waiting tests and I'll add comments.

**Review by tavplubix — APPROVED** [review]

**Comment by tavplubix** [comment]
PullRequestCI / BuilderBinClangTidy - SIX HOURS were not enough for clang-tidy to finish, it failed due to timeout and restarted...
Moreover, failed BuilderBinClangTidy breaks Mergeable Check, so it's impossible to merge the PR.
cc: @rschu1ze 

Screenshot from 2022-11-25 13-11-14

**Comment by rschu1ze** [comment]
About clang-tidy performance: See https://github.com/ClickHouse/ClickHouse/pull/43623#issuecomment-1332298180

**Pull request merged**
