### PR TITLE
Include `pytest-reportlog` in the integration tests' CI runner.

### PR DESCRIPTION
**Pull request by MyroTk**
This will enable the integration test report to be output in JSON format.

### Changelog category (leave one):
- Build/Testing/Packaging Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Include `pytest-reportlog` in integration test CI runner Dockerfile to enable JSON test reports.

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
Thank you! Could you also please make two (unrelated) changes:
1. Remove aerospike - it looks like we don't use it.
2. Check what versions are installed and pin these versions for all pip packages.

(these changes are unrelated, but as you started editing this place of code, let's make it right)

**Comment by MyroTk** [comment]
Updated.

**Review by alexey-milovidov — APPROVED** [review]

**Comment by robot-ch-test-poll1** [comment]
*This is an automated comment for commit e78eb41264ebb37d3fd813850a3e55ce7690ecea with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/58926/e78eb41264ebb37d3fd813850a3e55ce7690ecea/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/58926/e78eb41264ebb37d3fd813850a3e55ce7690ecea/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Comment by alexey-milovidov** [comment]
@MyroTk, it requires one extra change.

**Comment by alexey-milovidov** [comment]
@MyroTk, Please merge with master.

**Comment by MyroTk** [comment]
@alexey-milovidov, Unable to merge due to status check fail. The fast test fails are not related to changes.

**Comment by alexey-milovidov** [comment]
Please pull everything from the origin master to your branch.

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
@MyroTk, tests have failed.

**Comment by alexey-milovidov** [comment]
@MyroTk, tests have failed.

**Comment by MyroTk** [comment]
@alexey-milovidov Looks like aerospike is required, adding it back.
https://s3.amazonaws.com/clickhouse-test-reports/58926/aa91d522778cd1b2ac01331f45643278ae002fb0/integration_tests__release__[1_4]/runner_get_all_tests.log

**Comment by alexey-milovidov** [comment]
@MyroTk, as far as I recall, Aerospike sources are not supported for dictionaries. What you see in the tests might be some dangling, unused code. Let's remove it.

**Comment by alexey-milovidov** [comment]
Ok, we can have another PR for the removal.

**Pull request merged**
