### PR TITLE
Update yarn packages for dev branches

### PR DESCRIPTION
**Pull request by Felixoid**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Update yarn packages on every run to avoid situations like in https://github.com/ClickHouse/clickhouse-docs/pull/742

### CODE REVIEW

**Review by DanRoscigno — APPROVED** [review]
LGTM

**Comment by Felixoid** [comment]
Nice, I hope the automatic merge will get it done ^_^

**Comment by DanRoscigno** [comment]
Once it does I will  rerun the tests on the PR for the GA version of Docusaurus and then rerun the tests on a PR for the beta version.

**Comment by Felixoid** [comment]
Ok, it looks like you aren't the core team member. It looks legit

**Pull request merged**
