### PR TITLE
Fix formatting for JOIN ON clause with alias for the whole expression

### PR DESCRIPTION
**Pull request by azat**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix formatting for JOIN ON clause with alias for the whole expression

### CODE REVIEW

**Comment by robot-clickhouse-ci-2** [comment]
*This is an automated comment for commit 738c0b13e97a5fabe143adc154d46efc23284be9 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/66378/738c0b13e97a5fabe143adc154d46efc23284be9/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

**Review by evillique — APPROVED** [review]

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
@azat, we want to merge this pull request, but unfortunately one test in the private repository timed out when tested with S3 storage (probably due to the slowness of Minio over EBS volumes). Could you please merge with the master branch again?

**Comment by alexey-milovidov** [comment]
@azat, could you please check why builds didn't finish?

**Comment by azat** [comment]
Closed in favor of https://github.com/ClickHouse/ClickHouse/pull/66312

**Comment by azat** [comment]
https://s3.amazonaws.com/clickhouse-test-reports/66378/37c26b302d66111323ee464a7c0c7f1f45e968f1/stateless_tests__release_.html

>2024.07.14 08:21:52.030940 [ 3316 ] {} <Warning> Application: Child process was stopped by signal 19.

19 - `SIGSTOP`

**Pull request closed without merging**
