### PR TITLE
Experiment, not likely to improve performance

### PR DESCRIPTION
**Pull request by alexey-milovidov**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
@nickitat @georgthegreat No difference in performance at all.

**Comment by nickitat** [comment]
I see that slowed down queries are from date_time_short, date_time_64 and date_time_long. and in aarch64 tests there is a slow down on date_time_64 also. I bet it is not a coincidence.
we could sacrifice or try to fix them but what is the motivation?

**Comment by nickitat** [comment]
I forgot that there is a standard annotation. so, probably remove our macros and insert [[likely]] around conversion to datetime would be an ok solution.

**Comment by alexey-milovidov** [comment]
I'm not in favor of removing likely/unlikely, I'm ok with them.
Yes, we can replace it with the standard attributes and remove the cases when it's not possible.
This PR is just for performance comparison.

**Pull request closed without merging**
