### PR TITLE
Add Bash section and related repository

### PR DESCRIPTION
**Pull request by peter279k**
Changelog category (leave one):
- Documentation (changelog entry is not required)

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
N/A

Detailed description / Documentation draft:

## Motivating examples
Some motivating examples are as follows:

- `./installer.sh` Bash script. It can run more commands to install ClickHouse database client and server quickly.

```Bash
localadmin@clickhouse02:~/clickhouse-util$ ./installer.sh
Welcome to the ClickHouse Installer!
This Bash script is only available for Ubuntu 18.04 and 20.04 now!
[sudo] password for localadmin:
Reading package lists... Done
Building dependency tree
Reading state information... Done
ca-certificates is already the newest version (20210119~18.04.2).
ca-certificates set to manually installed.
dirmngr is already the newest version (2.2.4-1ubuntu1.4).
dirmngr set to manually installed.
The following NEW packages will be installed:
  apt-transport-https
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 4,348 B of archives.
After this operation, 154 kB of additional disk space will be used.
Do you want to continue? [Y/n] Y
Get:1 http://tw.archive.ubuntu.com/ubuntu bionic-updates/universe amd64 apt-transport-https all 1.6.14 [4,348 B]
Fetched 4,348 B in 0s (16.2 kB/s)
Selecting previously unselected package apt-transport-https.
(Reading database ... 174309 files and directories currently installed.)
Preparing to unpack .../apt-transport-https_1.6.14_all.deb ...
Unpacking apt-transport-https (1.6.14) ...
Setting up apt-transport-https (1.6.14) ...
Executing: /tmp/apt-key-gpghome.m9gEYD2eNQ/gpg.1.sh --keyserver hkp://keyserver.ubuntu.com:80 --recv E0C56BD4
gpg: key C8F1E19FE0C56BD4: public key "ClickHouse Repository Key <milovidov@yandex-team.ru>" imported
gpg: Total number processed: 1
gpg:               imported: 1
deb https://repo.clickhouse.com/deb/stable/ main/
Hit:1 http://tw.archive.ubuntu.com/ubuntu bionic InRelease
Hit:2 http://tw.archive.ubuntu.com/ubuntu bionic-updates InRelease
Hit:3 http://tw.archive.ubuntu.com/ubuntu bionic-backports InRelease
Hit:4 http://security.ubuntu.com/ubuntu bionic-security InRelease
Ign:5 https://repo.clickhouse.com/deb/stable main/ InRelease
Get:6 https://repo.clickhouse.com/deb/stable main/ Release [749 B]
Get:7 https://repo.clickhouse.com/deb/stable main/ Release.gpg [836 B]
Get:8 https://repo.clickhouse.com/deb/stable main/ Packages [224 kB]
Fetched 226 kB in 3s (67.5 kB/s)
Reading package lists... Done
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  clickhouse-common-static
Suggested packages:
  clickhouse-common-static-dbg
The following NEW packages will be installed:
  clickhouse-client clickhouse-common-static clickhouse-server
0 upgraded, 3 newly installed, 0 to remove and 0 not upgraded.
Need to get 209 MB of archives.
After this operation, 680 MB of additional disk space will be used.
Get:1 https://repo.clickhouse.com/deb/stable main/ clickhouse-common-static 21.12.3.32 [208 MB]
Get:2 https://repo.clickhouse.com/deb/stable main/ clickhouse-client 21.12.3.32 [115 kB]
Get:3 https://repo.clickhouse.com/deb/stable main/ clickhouse-server 21.12.3.32 [136 kB]
Fetched 209 MB in 19s (10.8 MB/s)
Selecting previously unselected package clickhouse-common-static.
(Reading database ... 174313 files and directories currently installed.)
Preparing to unpack .../clickhouse-common-static_21.12.3.32_amd64.deb ...
Unpacking clickhouse-common-static (21.12.3.32) ...
Selecting previously unselected package clickhouse-client.
Preparing to unpack .../clickhouse-client_21.12.3.32_all.deb ...
Unpacking clickhouse-client (21.12.3.32) ...
Selecting previously unselected package clickhouse-server.
Preparing to unpack .../clickhouse-server_21.12.3.32_all.deb ...
Unpacking clickhouse-server (21.12.3.32) ...
Setting up clickhouse-common-static (21.12.3.32) ...
Setting up clickhouse-server (21.12.3.32) ...
ClickHouse binary is already located at /usr/bin/clickhouse
Symlink /usr/bin/clickhouse-server already exists but it points to /clickhouse. Will replace the old symlink to /usr/bin/clickhouse.
Creating symlink /usr/bin/clickhouse-server to /usr/bin/clickhouse.
Symlink /usr/bin/clickhouse-client already exists but it points to /clickhouse. Will replace the old symlink to /usr/bin/clickhouse.
Creating symlink /usr/bin/clickhouse-client to /usr/bin/clickhouse.
Symlink /usr/bin/clickhouse-local already exists but it points to /clickhouse. Will replace the old symlink to /usr/bin/clickhouse.
Creating symlink /usr/bin/clickhouse-local to /usr/bin/clickhouse.
Symlink /usr/bin/clickhouse-benchmark already exists but it points to /clickhouse. Will replace the old symlink to /usr/bin/clickhouse.
Creating symlink /usr/bin/clickhouse-benchmark to /usr/bin/clickhouse.
Symlink /usr/bin/clickhouse-copier already exists but it points to /clickhouse. Will replace the old symlink to /usr/bin/clickhouse.
Creating symlink /usr/bin/clickhouse-copier to /usr/bin/clickhouse.
Symlink /usr/bin/clickhouse-obfuscator already exists but it points to /clickhouse. Will replace the old symlink to /usr/bin/clickhouse.
Creating symlink /usr/bin/clickhouse-obfuscator to /usr/bin/clickhouse.
Symlink /usr/bin/clickhouse-compressor already exists but it points to /clickhouse. Will replace the old symlink to /usr/bin/clickhouse.
Creating symlink /usr/bin/clickhouse-compressor to /usr/bin/clickhouse.
Symlink /usr/bin/clickhouse-format already exists but it points to /clickhouse. Will replace the old symlink to /usr/bin/clickhouse.
Creating symlink /usr/bin/clickhouse-format to /usr/bin/clickhouse.
Symlink /usr/bin/clickhouse-extract-from-config already exists but it points to /clickhouse. Will replace the old symlink to /usr/bin/clickhouse.
Creating symlink /usr/bin/clickhouse-extract-from-config to /usr/bin/clickhouse.
Creating clickhouse group if it does not exist.
 groupadd -r clickhouse
groupadd: group 'clickhouse' already exists
Creating clickhouse user if it does not exist.
 useradd -r --shell /bin/false --home-dir /nonexistent -g clickhouse clickhouse
useradd: user 'clickhouse' already exists
Will set ulimits for clickhouse user in /etc/security/limits.d/clickhouse.conf.
Config file /etc/clickhouse-server/config.xml already exists, will keep it and extract path info from it.
/etc/clickhouse-server/config.xml has /var/lib/clickhouse as data path.
/etc/clickhouse-server/config.xml has /var/log/clickhouse-server/ as log path.
Users config file /etc/clickhouse-server/users.xml already exists, will keep it and extract users info from it.
Log directory /var/log/clickhouse-server/ already exists.
Data directory /var/lib/clickhouse already exists.
Pid directory /var/run/clickhouse-server already exists.
 chown -R clickhouse:clickhouse '/var/log/clickhouse-server/'
 chown -R clickhouse:clickhouse '/var/run/clickhouse-server'
 chown  clickhouse:clickhouse '/var/lib/clickhouse'
 groupadd -r clickhouse-bridge
 useradd -r --shell /bin/false --home-dir /nonexistent -g clickhouse-bridge clickhouse-bridge
 chown -R clickhouse-bridge:clickhouse-bridge '/usr/bin/clickhouse-odbc-bridge'
 chown -R clickhouse-bridge:clickhouse-bridge '/usr/bin/clickhouse-library-bridge'
Password for default user is already specified. To remind or reset, see /etc/clickhouse-server/users.xml and /etc/clickhouse-server/users.d.
Setting capabilities for clickhouse binary. This is optional.
Cannot set 'net_admin' or 'ipc_lock' or 'sys_nice' capability for clickhouse binary. This is optioncapability later manually.
 chown -R clickhouse:clickhouse '/etc/clickhouse-server'

ClickHouse has been successfully installed.

Start clickhouse-server with:
 sudo clickhouse start

Start clickhouse-client with:
 clickhouse-client --password

Synchronizing state of clickhouse-server.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable clickhouse-server
Setting up clickhouse-client (21.12.3.32) ...
Processing triggers for systemd (237-3ubuntu10.52) ...
Processing triggers for ureadahead (0.100.0-21) ...
ureadahead will be reprofiled on next reboot
Installing ClickHouse DB has been done!
This machine will be reboot soon...
```

- `./create_database.sh` Bash script. It can create database quickly with single Bash script:

image

- `./create_table.sh` Bash script. It can create table quickly with specific query file:

image

image

- Color highlighting and friendly and simple usage help. It can make developers clear to identify messages:

image

- Authentication setting file. It can allow users to define a database authentication file to store some credentials rather than expose the password on the terminal with `clickhouse-client` command.

image

- Advanced Error checking. It will do command and file checking before running `clickhouse-client` command.

image

- `import_data.sh` Bash script. It can simply specify a file to import to ClickHouse with single Bash script

image

- `export_data.sh` Bash script. It can simply specify output file to export all data in specific table.

image

- `drop_table.sh` Bash script. It can be easy to drop table with specific table name and authentication setting file.

image

- `drop_database.sh` Bash script. It can be easy to drop database with specific database name and authentication file.

image

- All above Bash scripts are under unit tests with shUnit2 during GitHub workflow actions and it's available [here](https://github.com/peter279k/clickhouse-util/actions).

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
I'm still not convinced.

> Welcome to the ClickHouse Installer!
This Bash script is only available for Ubuntu 18.04 and 20.04 now!

ClickHouse works on every Linux starting from Ubuntu 8.04 and CentOS 5.
It does not require bash and even bourne shell.
And if you have bourne compatible shell, you can install it as easy as:

```
curl https://clickhouse.com/ | sh
```

**Comment by alexey-milovidov** [comment]
It contains a bug: lack of escaping (SQL injection):
https://github.com/peter279k/clickhouse-util/blob/master/drop_database.sh#L32

**Comment by alexey-milovidov** [comment]
Word splitting if password contains whitespace: https://github.com/peter279k/clickhouse-util/blob/master/drop_database.sh#L34

**Comment by peter279k** [comment]
> I'm still not convinced.
> 
> > Welcome to the ClickHouse Installer!
> > This Bash script is only available for Ubuntu 18.04 and 20.04 now!
> 
> ClickHouse works on every Linux starting from Ubuntu 8.04 and CentOS 5. It does not require bash and even bourne shell. And if you have bourne compatible shell, you can install it as easy as:
> 
> ```
> curl https://clickhouse.com/ | sh
> ```

Thanks for your reply. I don't think it's a good idea to install ClickHouse on these inactive distributions.

That's the reason why I add these above warning message to notify users should use active distributions to install the database server.

**Comment by alexey-milovidov** [comment]
ClickHouse does not care about Linux distribution. We don't care about Ubuntu, CentOS, RedHat and thousand others...

**Comment by peter279k** [comment]
If we don't care Linux distributions, I think it should let ClickHouse expose some security issues on these distributions.

**Pull request closed without merging**
