### PR TITLE
Minor improvement, load from config

### PR DESCRIPTION
**Pull request by zhanglistar**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

- Motivation: remove unnecessary check for existence of a key in config - load function does it itself. Minor improvement, code simplification.

### CODE REVIEW

**Comment by zhanglistar** [comment]
@alexey-milovidov Infomation has bee added. Pls check.

**Comment by zhanglistar** [comment]
> @zhanglistar it's not clear what the improvement is - we don't want to call `loadFromConfig` if key doesn't exist.

@yakov-olkhovskiy In the code `if (config.has(std::string(CONFIG_PREFIX)))`, `CONFIG_PREFIX` is const string `hdfs`, and the config key of HDFS related is like `hdfs.read.timeout`. The condition is false, so we can not load config from `config`. This condition is useless, since in the function `builder.loadFromConfig`, there is process to traverse the keys starting with `hdfs.`. Thanks for your reply.

**Comment by alexey-milovidov** [comment]
> Support load from config

This title is incomplete.

> Support load from config, now the if expression is needless.

This changelog entry is uncomprehensible.

**Comment by zhanglistar** [comment]
> d

@alexey-milovidov Sorry for that, I have changed it.

**Comment by yakov-olkhovskiy** [comment]
@zhanglistar there is no need for such elaborate explanation, and it's not a bug - let me fix it for you first...

**Comment by yakov-olkhovskiy** [comment]
@zhanglistar also, the message of the commit ("fix bug load from config") is very misleading - it's not a bug, and we would preferer not having such record in our git log - I would recommend to change it to simple "remove unnecessary check" or something like that. There is instructions how to change commit message:
https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/changing-a-commit-message

**Comment by zhanglistar** [comment]
@yakov-olkhovskiy https://github.com/ClickHouse/ClickHouse/pull/54244 Use this PR, close this PR.

**Pull request closed without merging**
