### PR TITLE
Doc. change. max_insert_threads RU description

### PR DESCRIPTION
**Pull request by den-crane**
max_insert_threads RU description

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Documentation (changelog entry is not required)

### CODE REVIEW

**Comment by qoega** [comment]
OK. Do you plan to add English version as well?

**Comment by den-crane** [comment]
Right after a merge of this one. Because I don't want to spend time on
translation of incorrect version.

**Comment by den-crane** [comment]
Or I can add en translation if this ru is correct and valid and ready to
merge.

**Comment by BayoNet** [comment]
Hello.

I don't see any defects in the content, but we are trying to implement a single style in the documentation. Applying the [template](https://github.com/ClickHouse/ClickHouse/blob/master/docs/dscr-templates/template-setting.md), you make your text look better :-)

**Comment by alexey-milovidov** [comment]
I found that the inline documentation was absolutely wrong:
https://github.com/ClickHouse/ClickHouse/pull/9524

Please edit accordingly.

**Comment by alexey-milovidov** [comment]
@BayoNet 

> Applying the template, you make your text look better :-)

Ok, but I don't care.

**Comment by BayoNet** [comment]
A documentation style is not only about presentation. Well organized docs more comfortable for uses and maintainers both.

Docs as code. Good text architecture simplifies:
- Visual search through text and its understanding.
- Updating and extending of docs by maintainers.

**Review by alexey-milovidov — APPROVED** [review]

**Pull request merged**
