### PR TITLE
Multi-stage PREWHERE enabled by default

### PR DESCRIPTION
**Pull request by davenger**
### Changelog category (leave one):
- Performance Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Enable `move_all_conditions_to_prewhere` and `enable_multiple_prewhere_read_steps` settings by default.

### CODE REVIEW

**Comment by robot-ch-test-poll1** [comment]
This is an automated comment for commit 50a4d14b8b600635d32fbad936924e1eaf301457 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/46365/50a4d14b8b600635d32fbad936924e1eaf301457/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Comment by azat** [comment]
@davenger in theory `move_all_conditions_to_prewhere` may slowdown queries, right? maybe you have some related numbers?

**Comment by davenger** [comment]
> @davenger in theory `move_all_conditions_to_prewhere` may slowdown queries, right? maybe you have some related numbers?
@azat  yes, `move_all_conditions_to_prewhere` must be used together with `enable_multiple_prewhere_read_steps` and in this PR they both are enabled. With both settings enabled we should do no more reads reads than previously, and in good cases we should read less. Or maybe you have some example in mind that I'm missing?
There are some numbers in the original PRs description and comment: https://github.com/ClickHouse/ClickHouse/pull/46140

**Comment by azat** [comment]
I'm was worrying extra seeks, but apparently the problem is in the code.

Consider the following example:

```sql

CREATE TABLE data
(
    `a` UInt64,
    `b` UInt64,
    `c` UInt64,
    `d` UInt64
)
ENGINE = MergeTree
ORDER BY tuple();

INSERT INTO data SELECT
    number % 1,
    number % 1,
    number % 1,
    number
FROM numbers(100000000.)

Query id: 02488797-7172-45c9-88ba-243955669efe

Ok.

0 rows in set. Elapsed: 1.573 sec. Processed 100.65 million rows, 805.21 MB (63.97 million rows/s., 511.79 MB/s.)

p620.local :) select count() from data where a = 1 and b = 0 and c = 0 settings optimize_move_to_prewhere=0

SELECT count()
FROM data
WHERE (a = 1) AND (b = 0) AND (c = 0)
SETTINGS optimize_move_to_prewhere = 0

Query id: 18acb99f-3636-4e17-8778-d345ec81f341

┌─count()─┐
│       0 │
└─────────┘

1 row in set. Elapsed: 0.091 sec. Processed 100.00 million rows, 2.40 GB (1.10 billion rows/s., 26.36 GB/s.)

p620.local :) select count() from data prewhere a = 1 and b = 0 and c = 0

SELECT count()
FROM data
PREWHERE (a = 1) AND (b = 0) AND (c = 0)

Query id: fb7950c0-92ca-4a6b-98c1-277c478ed9cb

┌─count()─┐
│       0 │
└─────────┘

1 row in set. Elapsed: 0.200 sec. Processed 100.00 million rows, 2.40 GB (501.22 million rows/s., 12.03 GB/s.)

p620.local :) select count() from data prewhere a = 1 and b = 0 and c = 0 settings merge_tree_min_rows_for_seek=10e6, enable_multiple_prewhere_read_steps=1

SELECT count()
FROM data
PREWHERE (a = 1) AND (b = 0) AND (c = 0)
SETTINGS merge_tree_min_rows_for_seek = 10000000., enable_multiple_prewhere_read_steps = 1

Query id: 444e9360-360f-4669-8881-06de4387c742

┌─count()─┐
│       0 │
└─────────┘

1 row in set. Elapsed: 0.252 sec. Processed 100.00 million rows, 800.00 MB (396.17 million rows/s., 3.17 GB/s.)

```

It looks like there is something suboptimal, because in one thread the difference is not that big:

```sql
p620.local :) select count() from data prewhere a = 1 and b = 0 and c = 0 settings enable_multiple_prewhere_read_steps=1, max_threads=1

SELECT count()
FROM data
PREWHERE (a = 1) AND (b = 0) AND (c = 0)
SETTINGS enable_multiple_prewhere_read_steps = 1, max_threads = 1

Query id: 6a6d1ff0-dee5-4444-871e-b16212dcdef7

┌─count()─┐
│       0 │
└─────────┘

1 row in set. Elapsed: 0.249 sec. Processed 100.00 million rows, 800.00 MB (402.10 million rows/s., 3.22 GB/s.)

p620.local :) select count() from data where a = 1 and b = 0 and c = 0 settings optimize_move_to_prewhere=0, max_threads=1

SELECT count()
FROM data
WHERE (a = 1) AND (b = 0) AND (c = 0)
SETTINGS optimize_move_to_prewhere = 0, max_threads = 1

Query id: 2e414046-c987-49dc-9203-3c1e507b7a71

┌─count()─┐
│       0 │
└─────────┘

1 row in set. Elapsed: 0.282 sec. Processed 100.00 million rows, 2.40 GB (354.57 million rows/s., 8.51 GB/s.)
```

**Comment by azat** [comment]
> There are some numbers in the original PRs description and comment: https://github.com/ClickHouse/ClickHouse/pull/46140

This query I guess filters out a lot of data, hence it give this benefit.

**Comment by azat** [comment]
>@azat is the data in your tests on HDD?

SSD, I would say that it was even memory, because the data was in page cache.

**Comment by davenger** [comment]
> > @azat is the data in your tests on HDD?
> 
> SSD, I would say that it was even memory, because the data was in page cache.

@azat could you please check that log_level is not 'test'?
This might explain such a big difference between your result and what I see.

**Comment by davenger** [comment]
The results of ClickBench with settings off and on: https://pastila.nl/?000b1ba6/95bfe2f2029917388977bc956a6ddf6c.html
The difference of 1.5x is seen in Q22, the rest are pretty much the same

**Review by nickitat — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
Wow! 1.5x improvement on one of the queries!

**Pull request merged**
