### PR TITLE
Less copy in write buffer from s3

### PR DESCRIPTION
**Pull request by KochetovNicolai**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by KochetovNicolai** [comment]
As an interesting side effect, now `move partition` to external volume (on minio) works faster than moving back (in my setup).
```
ALTER TABLE hits_move
    MOVE PARTITION '201307' TO VOLUME 'main'

Query id: 9acedb39-6f63-4e2d-878e-fbf616298081

Ok.

0 rows in set. Elapsed: 115.934 sec. 

ALTER TABLE hits_move
    MOVE PARTITION '201307' TO VOLUME 'external'

Query id: 9550abfe-0769-4caf-903a-c42761177bb7

Connecting to localhost:9000 as user default.
Connected to ClickHouse server version 22.12.1 revision 54460.

Ok.

0 rows in set. Elapsed: 79.592 sec. 

```

**Comment by CheSema** [comment]
Sorry. I do not approve such changes.  I see the better way to do this. Will come back tomorrow with details.

**Comment by qoega** [comment]
@CheSema lets close this PR? You will fix it the other way?

**Comment by CheSema** [comment]
> @CheSema lets close this PR? You will fix it the other way?

This is not my PR to close.
Nicolai made some experiments.

**Comment by CheSema** [comment]
Now WriteBufferFromS3 doesn't have unnecessary copy.
StdIStreamFromMemory is passed to S3 client as a std::iostream in order to read the data from internal buffer.

**Comment by CheSema** [comment]
I had a talk with Nicolai, he doesn't mind to close it.

**Pull request closed without merging**
