### PR TITLE
Move SonarCloud Job to nightly

### PR DESCRIPTION
**Pull request by juliojimenez**
Signed-off-by: Julio Jimenez <julio@clickhouse.com>

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
...

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
> Style Check — Check style failed.

**Comment by alexey-milovidov** [comment]
```
INFO: Auto-configuring pull request 42724
INFO: ------------------------------------------------------------------------
INFO: EXECUTION FAILURE
INFO: ------------------------------------------------------------------------
INFO: Total time: 12.466s
ERROR: Error during SonarScanner execution
INFO: Final Memory: 19M/148M
ERROR: Could not find a default branch to fall back on.
INFO: ------------------------------------------------------------------------
ERROR: 
ERROR: Re-run SonarScanner using the -X switch to enable full debug logging.
Error: Process completed with exit code 2.
```

**Comment by juliojimenez** [comment]
> Could not find a default branch to fall back on.

@alexey-milovidov according to the several q&a's and forum posts, sonar-scanner operates on the default branch, once this PR is merged to master it will be able to do its scan. Thank you, this error baffled me at first.

**Comment by juliojimenez** [comment]
> > Style Check — Check style failed.

shellcheck rule SC2086 is flaky.

**Comment by juliojimenez** [comment]
Finally figured out how to pass a stylecheck 🤣

**Pull request merged**
