### PR TITLE
Stateless tests: add test for SIZES_OF_NESTED_COLUMNS_ARE_INCONSISTENT

### LINKED ISSUE #42083: 21.10+: MODIFY COLUMN to Nullable may lead to data becoming unavaliable / incorrect
repro

```sql
DROP TABLE IF EXISTS column_modify_test;

CREATE TABLE column_modify_test (id UInt64, val String, other_col UInt64) engine=MergeTree ORDER BY id SETTINGS min_bytes_for_wide_part=0;
INSERT INTO column_modify_test VALUES (1,'one',0);
INSERT INTO column_modify_test VALUES (2,'two',0);

-- on 21.9 that was done via mutations mechanism
ALTER TABLE column_modify_test MODIFY COLUMN val Nullable(String);

-- but since 21.10 it only applies that to new part, so old parts keep the old schema
SELECT * FROM system.mutations;

INSERT INTO column_modify_test VALUES (3,Null,0);

select name, path, type, active, modification_time from system.parts_columns where table='column_modify_test' and column='val';

-- till now everythings looks ok
SELECT * FROM column_modify_test;

-- now we do mutation. It will affect one of the parts
-- and it what part it will update columns.txt to the latest 'correct' state w/o updating the column file!
alter table column_modify_test update other_col=1 where id = 1 SETTINGS mutations_sync=1;

-- row 1 is damaged now: the column files of val columns & columns.txt is out of sync!
SELECT *, throwIf(val <> 'one') as issue FROM column_modify_test WHERE id = 1 FORMAT CSV;
-- expected result is: 1,"one",1,0

-- Code: 366. DB::Exception: Received from localhost:9000. DB::Exception: Logical error: Sizes of nested column and null map of Nullable column are not equal. (SIZES_OF_NESTED_COLUMNS_ARE_INCONSISTENT)
```

### LINKED ISSUE #59094: [LOGICAL_ERROR] Number of columns in result doesn't match number of columns in sample block (if manually define _part_offset column in table)
**Describe what's wrong**

```sql
CREATE TABLE test_table
(
    `key` UInt32,
    `_part_offset` DEFAULT 0
)
ENGINE = MergeTree
ORDER BY key



INSERT INTO test_table (key) SELECT number
FROM numbers(10);

SELECT *
FROM test_table


Elapsed: 0.002 sec.

Received exception from server (version 23.11.4):
Code: 49. DB::Exception: Received from localhost:9000. DB::Exception: Number of columns in result doesn't match number of columns in sample block, read_result: num_rows: 10, columns: 3, total_rows_per_granule: 10, no filter, column[0]:  UInt32(size = 10), column[1]:  Sparse(size = 10, UInt8(size = 1), UInt64(size = 0)), column[2]:  UInt64(size = 10), sample block: key UInt32 UInt32(size = 0), _part_offset UInt8 UInt8(size = 0): While executing MergeTreeSelect(pool: ReadPoolInOrder, algorithm: InOrder). (LOGICAL_ERROR)

SELECT
    key,
    _part_offset
FROM test_table;

Received exception from server (version 23.11.4):

Code: 49. DB::Exception: Received from localhost:9000. DB::Exception: Number of columns in result doesn't match number of columns in sample block, read_result: num_rows: 10, columns: 3, total_rows_per_granule: 10, no filter, column[0]:  UInt32(size = 10), column[1]:  Sparse(size = 10, UInt8(size = 1), UInt64(size = 0)), column[2]:  UInt64(size = 10), sample block: key UInt32 UInt32(size = 0), _part_offset UInt8 UInt8(size = 0): While executing MergeTreeSelect(pool: ReadPoolInOrder, algorithm: InOrder). (LOGICAL_ERROR)
```

### PR DESCRIPTION
**Pull request by fm4v**
Closes: https://github.com/ClickHouse/ClickHouse/issues/42083
Closes: https://github.com/ClickHouse/ClickHouse/issues/59094

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
...

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: Normal Builds
- [ ]  Allow: Special Builds
- [ ]  Allow: All NOT Required Checks
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Do not test
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-clickhouse-ci-2** [comment]
*This is an automated comment for commit b80faf453a0cac781659d28e8369bf9bcbcc3b0f with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/65056/b80faf453a0cac781659d28e8369bf9bcbcc3b0f/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>A Sync</td><td>If it fails, ask a maintainer for help</td><td>⏳ pending</td></tr>
<tbody>
</table>
<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>Checks correctness of the PR's body</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

**Review by jkartseva — COMMENTED** [review]
Was #59094 fixed in some other PR? This PR only adds tests.

**Comment by fm4v** [comment]
https://github.com/ClickHouse/ClickHouse/issues/59094 was fixed in 24.4 https://fiddle.clickhouse.com/bb2d2921-141a-4147-92a9-82dfbe18c921

**Review by jkartseva — APPROVED** [review]
@fm4v And what was the PR that fixed the issue?

**Review by alexey-milovidov — APPROVED** [review]

**Pull request merged**
