### PR TITLE
Fix LowCardinality->ArrowDictionary invalid output

### LINKED ISSUE #36832: LowCardinality->ArrowDictionary Invalid Output
When using the `Arrow` output format, `LowCardinality(String)` columns and `output_format_arrow_low_cardinality_as_dictionary=1`, an invalid result is produced when the number of distinct values in the dictionary exceeds 128. It's invalid because the data type of the indices is always `int8` even when there are more than 256 values. This is bad because each distinct value needs a distinct index and by the pigeonhole principle if there are > 256 dictionary values and only 256 indices, some indices will represent multiple dictionary values. Moreover, if the number of distinct values is greater than 128, this results in some `int8` values that are negative (since the most significant bit of the uint8 is 1 and this maps to the sign in int8), and all indices must be positive.

**Does it reproduce on recent release?**

Reproduces on ClickHouse 22.4.4.

**How to reproduce**

* Which ClickHouse server version to use
22.4
* Which interface to use, if matters
Can use ./clickhouse client

```
$ ./clickhouse client -q "select * from ftx_trades;" -f Arrow --output_format_arrow_low_cardinality_as_dictionary 0 > trades.feather                                                                                                                                 (base)
$ ./clickhouse client -q "select * from ftx_trades;" -f Arrow --output_format_arrow_low_cardinality_as_dictionary 1 > trades_dict.feather
```

`trades_dict.feather` will contain valid Arrow data (using a `string` type for the market), but `trades.feather` will not (it's dictionary type is incorrect).

* `CREATE TABLE` statements for all tables involved
```
CREATE TABLE ftx_trades (
  market LowCardinality(String),
  time DateTime64(9),
  id Int64,
  price Float64,
  size Float64,
  side LowCardinality(String),
  liquidation UInt8,
  INDEX time_range (time) TYPE minmax GRANULARITY 1
) ENGINE = MergeTree()
PRIMARY KEY (market, time)
ORDER BY (market, time, id);
```
* Sample data for all these tables

[example_trades.csv](https://github.com/ClickHouse/ClickHouse/files/8597765/example_trades.csv)

* Non-default settings

`output_format_arrow_low_cardinality_as_dictionary=1`

* Queries to run that lead to unexpected result

`select * from ftx_trades;` (any query that references the `market` column).

**Expected behavior**

Each distinct value in ClickHouse must have a unique positive index in the Arrow dictionary.

In the meantime I'm going to not set `output_format_arrow_low_cardinality_as_dictionary=1`

### PR DESCRIPTION
**Pull request by Avogar**
### Changelog category (leave one):
- Bug Fix (user-visible misbehaviour in official stable or prestable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix LowCardinality->ArrowDictionary invalid output when type of indexes is not UInt8.
Closes https://github.com/ClickHouse/ClickHouse/issues/36832

### CODE REVIEW

**Review by antonio2368 — APPROVED** [review]

**Comment by Avogar** [comment]
`Stateless tests (address, actions) [1/2]` - https://github.com/ClickHouse/ClickHouse/pull/37112
`Stateless tests flaky check (address, actions)` - new test uses `file` function and it's OK, it won't fail in master

**Comment by mhconradt** [comment]
@Avogar I tried this out using ClickHouse server version 22.5.1 revision 54455 and the indices were still invalid (used int8 instead of int16). Was this included in 22.5 or will it be in 22.6?

**Comment by mhconradt** [comment]
To be specific, I have a dictionary with 850 distinct values but it's still using int8.

**Comment by Avogar** [comment]
> @Avogar I tried this out using ClickHouse server version 22.5.1 revision 54455 and the indices were still invalid (used int8 instead of int16). Was this included in 22.5 or will it be in 22.6?

Looks like it works ok in latest 22.5.1.2079 release:
```sql
avogar-dev :) select version()

SELECT version()

Query id: 79852474-8481-4a47-87ed-b51ca082afbd

┌─version()───┐
│ 22.5.1.2079 │
└─────────────┘

1 row in set. Elapsed: 0.006 sec.

avogar-dev :) insert into function file(data.arrow) select toLowCardinality(toString(number % 850)) as x from numbers(1000) settings output_format_arrow_low_cardinality_as_dictionary=1

INSERT INTO FUNCTION file(data.arrow)
SETTINGS output_format_arrow_low_cardinality_as_dictionary = 1
SELECT toLowCardinality(toString(number % 850)) AS x
FROM numbers(1000)
SETTINGS output_format_arrow_low_cardinality_as_dictionary = 1

Query id: 1695ddb0-fdce-4aaa-94e0-a69fd0f61aba

Ok.

0 rows in set. Elapsed: 0.003 sec. Processed 1.00 thousand rows, 8.00 KB (304.73 thousand rows/s., 2.44 MB/s.)

avogar-dev :) select uniq(x) from file(data.arrow)

SELECT uniq(x)
FROM file(data.arrow)

Query id: 64a75f1c-3ed0-428f-893f-aece6e71f506

┌─uniq(x)─┐
│     850 │
└─────────┘

1 row in set. Elapsed: 0.005 sec. Processed 1.00 thousand rows, 12.11 KB (209.33 thousand rows/s., 2.53 MB/s.)
```

```python
>>> import pyarrow as pa
>>> source = pa.OSFile('data.arrow', 'rb')
>>> table = pa.ipc.open_file(source).read_all()
>>> table.schema
x: dictionary<values=binary, indices=int16, ordered=0> not null
```

**Comment by mhconradt** [comment]
Can you try the same using a `SELECT` statement with a `FORMAT` clause, using `Arrow`/`ArrowStream`? I'm using the latest release and the output still shows up as having int8 indices.

**Comment by mhconradt** [comment]
You're right, my client is 22.3! I wouldn't have guessed that's the case. Thanks 🙏.

**Pull request merged**
