### PR TITLE
Poco build fixes

### PR DESCRIPTION
**Pull request by azat**
Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
- Fix Poco::Crypto library (missing linking with crypto)
- Fix ParsingException::displayText override (guard with POCO_CLICKHOUSE_PATCH) (#17641, due to `virtual` qualifier for `displayText` - https://github.com/ClickHouse-Extras/poco/pull/31)
- Make poco library path variable scope less global

Cc: @nikitamikhaylov

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
Could you please remove all entries of `POCO_CLICKHOUSE_PATCH` macro from code?

**Comment by azat** [comment]
>Upd. No we cannot do it, because there is Arcadia build.

Ok, let's guard displayText with POCO_CLICKHOUSE_PATCH then

**Comment by azat** [comment]
>Ok, let's guard displayText with POCO_CLICKHOUSE_PATCH then


I'm not sure that this will help, since seems that it also has some different Poco?

https://github.com/ClickHouse/ClickHouse/pull/17641#issuecomment-744542579

> Yandex synchronization check failed, because I didn't patch Poco in Arcadia :((

Does it defines `POCO_CLICKHOUSE_PATCH`?

**Comment by alexey-milovidov** [comment]
Arcadia does not define `POCO_CLICKHOUSE_PATCH` and it's something more close to the original Poco (also very old).

**Comment by nikitamikhaylov** [comment]
But why it compiles successfully in my PR?

**Comment by alexey-milovidov** [comment]
@nikitamikhaylov I checked it and appeared I was wrong:
```
~/arc/arcadia/contrib/libs/poco$ grep -r POCO_CLICKHOUSE
Foundation/include/Poco/Config.h:#define POCO_CLICKHOUSE_PATCH 1
```

Nevertheless, Arcadia is using some version of Poco that is neither upstream neither the same as in ClickHouse.

**Pull request merged**
