### PR TITLE
(Re?)-enable libcxx asserts for debug builds

### PR DESCRIPTION
**Pull request by rschu1ze**
- We previously compiled libcxx with `_LIBCPP_DEBUG=0`. In old libcxx versions, this (surprisingly) enabled the basic debug mode [1].

- In libcxx 15 (the version we are currently using), `_LIBCPP_DEBUG=0`does nothing [2], the replacement is `_LIBCPP_ENABLE_DEBUG_MODE=1`.

- The debug mode is only enabled in Debug builds. Their docs say the extra check change complexity guarantees + the asserts crash which we don't want in Release builds. The debug mode detects issues like in [3]. Crashes look like this (for example)

```
/data/ch/contrib/llvm-project/libcxx/include/__iterator/wrap_iter.h:99: assertion ::std::__libcpp_is_constant_evaluated() || (__get_const_db()->__dereferenceable(this)) failed: Attempted to increment a non-incrementable iteratorAborted (core dumped)
```

EDIT: After some digging, the debug mode seems to aggressive (see my comments in CMakeLists.txt). So this PR only enables assertions (also see CMakeLists.txt).

[1] https://releases.llvm.org/12.0.0/projects/libcxx/docs/DesignDocs/DebugMode.html
[2] https://releases.llvm.org/15.0.0/projects/libcxx/docs/DesignDocs/DebugMode.html
[3] https://github.com/llvm/llvm-project/blob/main/libcxx/test/support/container_debug_tests.h

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by robot-clickhouse-ci-1** [comment]
*This is an automated comment for commit d40b641a340ef27c986ce4f7ba8bca7209902530 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/70134/d40b641a340ef27c986ce4f7ba8bca7209902530/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Style check</td><td>Runs a set of checks to keep the code style clean. If some of tests failed, see the related log from the report</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/70134/d40b641a340ef27c986ce4f7ba8bca7209902530/style_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Review by alexey-milovidov — APPROVED** [review]

**Comment by Algunenano** [comment]
What the hell happened in the performance comparison?

**Comment by rschu1ze** [comment]
That is ridiculous indeed. I'll restrict the debug mode to Debug builds, so there will not be an impact on the perf tests but I'll also check locally what is going on.

**Comment by rschu1ze** [comment]
AST Fuzzer (msan): #56640

Cloud fork sync: unrelated (opened an issue)

**Comment by rschu1ze** [comment]
I digged a bit deeper why I could only enable assertions but not the full debug mode:

The debug mode maintains for each std container (e.g. `std::vector`) a list of created iterators. Any operations on the container which take the iterator as parameter check if the iterator is in the list.

During database startup, we have code like this:

```cpp
void AggregateFunctionCombinatorFactory::registerCombinator(const AggregateFunctionCombinatorPtr & value)
{
    [...]
    dict.emplace(it, pair);
```

At that point, `dict` is empty and `it` is `dict.end()`. `vector::emplace` works just fine, it resizes the vector and inserts `pair`. In the debug mode, it complains that an unknown iterator was used but I am pretty sure that our usage of `.emplace` is correct. Besides that, the constant checks slow down the database by too much, startup in debug modes takes 30 seconds just to get to this error (and function registration happens quite early in startup).

**Comment by alexey-milovidov** [comment]
Thank you! Yes, it is correct to use the `end` iterator in emplace/insert. We should file a bug to libc++.

**Comment by rschu1ze** [comment]
> We should file a bug to libc++.

Our libcxx v15 is already out of maintenance :-(
(The latest try to bump it is #69654.)

The latest libcxx introduces "hardening modes" instead of assertions ([docs](https://libcxx.llvm.org/Hardening.html)). We should check if they work properly after bumping LLVM.

**Pull request merged**
