### PR TITLE
fix/doc: update output type of tupleHammingDistance

### PR DESCRIPTION
**Pull request by yohannj**
Changelog category (leave one):
- Documentation (changelog entry is not required)

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
...

Detailed description / Documentation draft:
A year ago, output type of tupleHammingDistance was updated ([commit](https://github.com/ClickHouse/ClickHouse/commit/c65f79d69b9f67e117370c569199504b29a9faec#diff-f931cb082a658781684eb3488f44b3b875727a3846c380fa050f61462004fb42))

Japanese and Chinese documentation already specify it's UInt32 instead of UInt8.

Here is confirmation of the fact it's not UInt8 anymore, but at least UInt32, using the method on an example, with v21.12.3
```console
root@a7f8b8372e9f:/# clickhouse-client 
ClickHouse client version 21.12.3.32 (official build).
Connecting to localhost:9000 as user default.
Connected to ClickHouse server version 21.12.3 revision 54452.

a7f8b8372e9f :) SELECT toTypeName(tupleHammingDistance((1, 2, 3), (3, 2, 1))) AS HammingDistance;
                

SELECT toTypeName(tupleHammingDistance((1, 2, 3), (3, 2, 1))) AS HammingDistance

Query id: ef6e22d5-a91a-462e-99ad-bc3e8bf3071e

┌─HammingDistance─┐
│ UInt32          │
└─────────────────┘

1 rows in set. Elapsed: 0.007 sec. 
```

> By adding documentation, you'll allow users to try your new feature immediately, not when someone else will have time to document it later. Documentation is necessary for all features that affect user experience in any way. You can add brief documentation draft above, or add documentation right into your patch as Markdown files in [docs](https://github.com/ClickHouse/ClickHouse/tree/master/docs) folder.

> If you are doing this for the first time, it's recommended to read the lightweight [Contributing to ClickHouse Documentation](https://github.com/ClickHouse/ClickHouse/tree/master/docs/README.md) guide first.

> Information about CI checks: https://clickhouse.tech/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by evillique** [comment]
It's actually not always the case, like in this example:
```
SELECT toTypeName(tupleHammingDistance(tuple(1), tuple(3))) AS HammingDistance

┌─HammingDistance─┐
│ UInt8           │
└─────────────────┘
```
Types in this case work similar to [Arithmetic Functions](https://clickhouse.com/docs/en/sql-reference/functions/arithmetic-functions/#arithmetic-functions)

**Comment by yohannj** [comment]
I see.
I simply tried the example provided with the documentation, but could have done additional search.

For additional context, I am currently working on a type safe client, it is very important for me to know return types to make sure queries being built will be valid, and return an expected type.

Back to the subject.
If I understand correctly (I never coded in c++ but know some concepts), on the [master version of the file](https://github.com/ClickHouse/ClickHouse/blob/master/src/Functions/tupleHammingDistance.cpp):
While iterating on the number of elements in the tuples, line 86 we apply the `plus` function between the current type, and the result of `notEquals` which is always UInt8.

So:
0 elements in tuple (default do UInt8)
1 element in tuple => UInt8
2 elements => UInt8 + UInt8 => UInt16
3 elements => UInt32
4 elements => UInt64
X elements => UInt64

In that case, should we precise this behavior in the documentation?
I'd like to propose to explain very basically how it works (tuple size) and redirects to https://clickhouse.com/docs/en/sql-reference/functions/arithmetic-functions/ which explains how the return type is calculated. Would that be alright if I update the PR that way?



p.s. Double check:
```
SELECT
    toTypeName(tupleHammingDistance(tuple(1), tuple(1))) AS t1,
    toTypeName(tupleHammingDistance((1, 1), (1, 1))) AS t2,
    toTypeName(tupleHammingDistance((1, 1, 1), (1, 1, 1))) AS t3,
    toTypeName(tupleHammingDistance((1, 1, 1, 1), (1, 1, 1, 1))) AS t4,
    toTypeName(tupleHammingDistance((1, 1, 1, 1, 1), (1, 1, 1, 1, 1))) AS t5,
    toTypeName(tupleHammingDistance((1, 1, 1, 1, 1, 1), (1, 1, 1, 1, 1, 1))) AS t6

Query id: 903d4abb-07e5-4fbd-b1fb-aa0173bc3665

┌─t1────┬─t2─────┬─t3─────┬─t4─────┬─t5─────┬─t6─────┐
│ UInt8 │ UInt16 │ UInt32 │ UInt64 │ UInt64 │ UInt64 │
└───────┴────────┴────────┴────────┴────────┴────────┘
```

**Comment by kitaisreal** [comment]
@yohannj yes, lets update documentation this way.

**Comment by yohannj** [comment]
I just updated the English documentation and reverted my changes for Russian. I am unable to translate the sentence in Russian.

**Comment by kitaisreal** [comment]
@Mergifyio update

**Pull request merged**
