### PR TITLE
Make SHOW CREATE TABLE multiline

### PR DESCRIPTION
**Pull request by azat**
Changelog category (leave one):
- Backward Incompatible Change

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Make SHOW CREATE TABLE multiline (because it is more readable and also mysql like)

### CODE REVIEW

**Comment by azat** [comment]
Any thoughts on this? If this is worth it, then I will update the tests.

**Comment by alexey-milovidov** [comment]
Yes, it's Ok. Let's update the tests.

**Comment by alexey-milovidov** [comment]
PS. Please don't worry about PR assigments by Ivan Blinkov. He has written a script that assigns pull request to random people. We decided that we will remove this script but Ivan has not stopped it yet.

**Comment by azat** [comment]
>01086_odbc_roundtrip

failure looks unrelated

**Comment by azat** [comment]
>Yes, it's Ok. Let's update the tests.

Done

**Comment by alexey-milovidov** [comment]
I have changed changelog category to "Backward Incompatible Change" because it is Backward Incompatible Change.

**Pull request merged**
