### PR TITLE
Improve building steps

### PR DESCRIPTION
**Pull request by peter279k**
### Changelog category (leave one):
- Documentation (changelog entry is not required)

Before installing the latest clang in Ubuntu operating system, it should import the `ppa:ubuntu-toolchain-r/test` repository firstly.

Otherwise it will present the following error dependencies message when running the automated `llvm.sh` script:

```sh
peter@ubuntu-s-4vcpu-8gb-amd-sgp1-01:~$ sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"
--2022-09-08 04:33:57--  https://apt.llvm.org/llvm.sh
Resolving apt.llvm.org (apt.llvm.org)... 146.75.94.49, 2a04:4e42:6::561
Connecting to apt.llvm.org (apt.llvm.org)|146.75.94.49|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4874 (4.8K) [application/octet-stream]
Saving to: ‘STDOUT’

-                          100%[========================================>]   4.76K  --.-KB/s    in 0s

2022-09-08 04:33:58 (52.9 MB/s) - written to stdout [4874/4874]

+ CURRENT_LLVM_STABLE=15
+ BASE_URL=http://apt.llvm.org
+ needed_binaries=(lsb_release wget add-apt-repository gpg)
+ missing_binaries=()
+ for binary in "${needed_binaries[@]}"
+ which lsb_release
+ for binary in "${needed_binaries[@]}"
+ which wget
+ for binary in "${needed_binaries[@]}"
+ which add-apt-repository
+ for binary in "${needed_binaries[@]}"
+ which gpg
+ [[ 0 -gt 0 ]]
+ LLVM_VERSION=15
+ ALL=0
++ lsb_release -is
+ DISTRO=Ubuntu
++ lsb_release -sr
+ VERSION=18.04
+ UBUNTU_CODENAME=
+ CODENAME_FROM_ARGUMENTS=
+ source /etc/os-release
++ NAME=Ubuntu
++ VERSION='18.04.6 LTS (Bionic Beaver)'
++ ID=ubuntu
++ ID_LIKE=debian
++ PRETTY_NAME='Ubuntu 18.04.6 LTS'
++ VERSION_ID=18.04
++ HOME_URL=https://www.ubuntu.com/
++ SUPPORT_URL=https://help.ubuntu.com/
++ BUG_REPORT_URL=https://bugs.launchpad.net/ubuntu/
++ PRIVACY_POLICY_URL=https://www.ubuntu.com/legal/terms-and-policies/privacy-policy
++ VERSION_CODENAME=bionic
++ UBUNTU_CODENAME=bionic
+ DISTRO=ubuntu
+ case ${DISTRO} in
+ [[ -n bionic ]]
+ CODENAME=bionic
+ [[ -n bionic ]]
+ LINKNAME=-bionic
+ '[' 0 -ge 1 ']'
+ getopts :hm:n: arg
+ [[ 0 -ne 0 ]]
+ declare -A LLVM_VERSION_PATTERNS
+ LLVM_VERSION_PATTERNS[9]=-9
+ LLVM_VERSION_PATTERNS[10]=-10
+ LLVM_VERSION_PATTERNS[11]=-11
+ LLVM_VERSION_PATTERNS[12]=-12
+ LLVM_VERSION_PATTERNS[13]=-13
+ LLVM_VERSION_PATTERNS[14]=-14
+ LLVM_VERSION_PATTERNS[15]=-15
+ LLVM_VERSION_PATTERNS[16]=
+ '[' '!' _ ']'
+ LLVM_VERSION_STRING=-15
+ [[ -n bionic ]]
+ REPO_NAME='deb http://apt.llvm.org/bionic/  llvm-toolchain-bionic-15 main'
+ wget -q --method=HEAD http://apt.llvm.org/bionic
++ apt-key list
++ grep -i llvm
Warning: apt-key output should not be parsed (stdout is not a terminal)
+ [[ -z uid           [ unknown] Sylvestre Ledru - Debian LLVM packages <sylvestre@debian.org> ]]
+ add-apt-repository 'deb http://apt.llvm.org/bionic/  llvm-toolchain-bionic-15 main'
Get:1 http://mirrors.digitalocean.com/ubuntu bionic InRelease [242 kB]
Hit:2 https://repos-droplet.digitalocean.com/apt/droplet-agent main InRelease
Hit:3 http://mirrors.digitalocean.com/ubuntu bionic-updates InRelease
Hit:4 http://mirrors.digitalocean.com/ubuntu bionic-backports InRelease
Hit:5 http://security.ubuntu.com/ubuntu bionic-security InRelease
Hit:6 https://apt.llvm.org/bionic llvm-toolchain-bionic-10 InRelease
Get:7 https://apt.llvm.org/bionic llvm-toolchain-bionic-15 InRelease [6828 B]
Get:8 https://apt.llvm.org/bionic llvm-toolchain-bionic-15/main amd64 Packages [10.5 kB]
Fetched 259 kB in 2s (151 kB/s)
Reading package lists... Done
+ apt-get update
Get:1 http://mirrors.digitalocean.com/ubuntu bionic InRelease [242 kB]
Hit:2 https://repos-droplet.digitalocean.com/apt/droplet-agent main InRelease
Hit:3 http://mirrors.digitalocean.com/ubuntu bionic-updates InRelease
Hit:4 http://mirrors.digitalocean.com/ubuntu bionic-backports InRelease
Hit:6 http://security.ubuntu.com/ubuntu bionic-security InRelease
Hit:5 https://apt.llvm.org/bionic llvm-toolchain-bionic-10 InRelease
Hit:7 https://apt.llvm.org/bionic llvm-toolchain-bionic-15 InRelease
Fetched 242 kB in 1s (164 kB/s)
Reading package lists... Done
+ PKG='clang-15 lldb-15 lld-15 clangd-15'
+ [[ 0 -eq 1 ]]
+ apt-get install -y clang-15 lldb-15 lld-15 clangd-15
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 clang-15 : Depends: libclang-cpp15 (>= 1:15.0.0~++20220907073022+7ce1ec5a2a22) but it is not going to be installed
            Depends: libgcc-s1 (>= 3.0) but it is not installable
            Depends: libllvm15 but it is not going to be installed
            Depends: libstdc++6 (>= 11) but 8.4.0-1ubuntu1~18.04 is to be installed
            Depends: libclang-common-15-dev (= 1:15.0.0~++20220907073022+7ce1ec5a2a22-1~exp1~20220907073127.48) but it is not going to be installed
            Depends: llvm-15-linker-tools (= 1:15.0.0~++20220907073022+7ce1ec5a2a22-1~exp1~20220907073127.48) but it is not going to be installed
            Depends: libclang1-15 (= 1:15.0.0~++20220907073022+7ce1ec5a2a22-1~exp1~20220907073127.48) but it is not going to be installed
            Recommends: llvm-15-dev but it is not going to be installed
 clangd-15 : Depends: libclang-cpp15 (>= 1:15.0.0~++20220907073022+7ce1ec5a2a22) but it is not going to be installed
             Depends: libgcc-s1 (>= 3.0) but it is not installable
             Depends: libllvm15 but it is not going to be installed
             Depends: libstdc++6 (>= 11) but 8.4.0-1ubuntu1~18.04 is to be installed
             Depends: libclang-common-15-dev (= 1:15.0.0~++20220907073022+7ce1ec5a2a22-1~exp1~20220907073127.48) but it is not going to be installed
 lld-15 : Depends: libgcc-s1 (>= 3.0) but it is not installable
          Depends: libllvm15 (= 1:15.0.0~++20220907073022+7ce1ec5a2a22-1~exp1~20220907073127.48) but it is not going to be installed
          Depends: libstdc++6 (>= 11) but 8.4.0-1ubuntu1~18.04 is to be installed
 lldb-15 : Depends: libclang-cpp15 (>= 1:15.0.0~++20220907073022+7ce1ec5a2a22) but it is not going to be installed
           Depends: libgcc-s1 (>= 3.0) but it is not installable
           Depends: liblldb-15 but it is not going to be installed
           Depends: libllvm15 (= 1:15.0.0~++20220907073022+7ce1ec5a2a22-1~exp1~20220907073127.48) but it is not going to be installed
           Depends: libstdc++6 (>= 11) but 8.4.0-1ubuntu1~18.04 is to be installed
           Depends: llvm-15-dev but it is not going to be installed
           Depends: python3-lldb-15 but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

The above issue is available [here](https://github.com/llvm/llvm-project/issues/56451).

### CODE REVIEW

**Review by nikitamikhaylov — APPROVED** [review]

**Comment by DanRoscigno** [comment]
@Felixoid can the style check be configured to ignore words in codeblocks?  If I am reading the failure properly it is unhappy with the spelling of Ubuntu and toolchain within a deb name.

**Comment by DanRoscigno** [comment]
@Felixoid can you have a look please?  I modified the work list for the spelling check to ignore the two words that the check failed on and re-ran the CI checks, but it still fails on the same words.

**Comment by DanRoscigno** [comment]
@Felixoid the change was in this PR https://github.com/ClickHouse/ClickHouse/pull/42132

**Comment by DanRoscigno** [comment]
ubuntu is not a typo in this particular doc, which is why I asked for typos in codeblocks to be ignored.  In a package name `ubuntu` is correct.

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
The LLVM repository should also contain all the needed dependencies.
But it does not necessarily work on every Ubuntu version.

So, your instruction makes sense, but it should be stated slightly differently.

PS. I've updated the text.

**Pull request merged**
