### PR TITLE
A faster branchless countDigits

### PR DESCRIPTION
**Pull request by zbtzbtzbt**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
A faster branchless countDigits

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
A test for this function has failed, indicating a change in behavior.

**Comment by alexey-milovidov** [comment]
A branchful version can be faster: https://github.com/ClickHouse/ClickHouse/blob/master/base/base/itoa.h#L315

**Comment by zbtzbtzbt** [comment]
Should we remove countDigits current division version？use this if version

> A branchful version can be faster: https://github.com/ClickHouse/ClickHouse/blob/master/base/base/itoa.h#L315

**Comment by alexey-milovidov** [comment]
Yes, it should be better.

**Comment by alexey-milovidov** [comment]
Continued in #46187.

**Pull request closed without merging**
