### PR TITLE
Fix log-level in `clickhouse-disks`

### LINKED ISSUE #42260: --send-logs and --log-level options in clickhouse-disks tool do not work
**Description**
--send-logs and --log-level options are present in the help, but they do not work.

```
# clickhouse-disks --help
...
  --send-logs              Send logs
  --log-level              Logging level
```

```
# clickhouse-disks --log-level ERROR list-disks
Bad arguments: too many positional options have been specified on the command line
```

```
# clickhouse-disks --send-logs false list-disks
Bad arguments: too many positional options have been specified on the command line
```

ClickHouse version: 22.8.6.71

**Use case**
Looking for a way to disable logging to stdout.

### PR DESCRIPTION
**Pull request by evillique**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Closes https://github.com/ClickHouse/ClickHouse/issues/42260.

### CODE REVIEW

**Review by kssenii — APPROVED** [review]

**Comment by kssenii** [comment]
The issue also mentions `--send-logs`, but nothing is changed there in this PR, is it still not working?

**Comment by evillique** [comment]
ASTFuzzer: https://github.com/ClickHouse/ClickHouse/issues/42330

**Comment by tavplubix** [comment]
@evillique, why do we need `send-logs` parameter at all? For server/client it means "send logs from server to client", but it does not really make sense for `clickhouse-disks`, because it does not _send_ logs anywhere, it just prints them to stderr/file. Consider removing this parameter and using `log-level=none` to disable logs.

**Comment by evillique** [comment]
@tavplubix `send-logs` parameter enables logging to file, and without it, logs are just printed to stderr. Maybe we can just choose a better name for it?

**Comment by tavplubix** [comment]
Yep, let's just rename it then, I just don't like "send"

**Comment by evillique** [comment]
Does `save-logs` sound better?

**Pull request merged**
