### PR TITLE
Cherry pick #54549 to 23.3: Fix rare case of CHECKSUM_DOESNT_MATCH error

### PR DESCRIPTION
**Pull request by robot-clickhouse-ci-1**
Original pull-request #54549

This pull-request is a first step of an automated backporting.
It contains changes like after calling a local command `git cherry-pick`.
If you intend to continue backporting this changes, then resolve all conflicts if any.
Otherwise, if you do not want to backport them, then just close this pull-request.

The check results does not matter at this step - you can safely ignore them.

### Note

This pull-request will be merged automatically as it reaches the mergeable state, **do not merge it manually**.

### If the PR was closed and then reopened

If it stuck, check https://github.com/ClickHouse/ClickHouse/pull/54549 for `pr-backports-created` and delete it if necessary. Manually merging will do nothing, since `pr-backports-created` prevents the original PR https://github.com/ClickHouse/ClickHouse/pull/54549 from being processed.

If you want to recreate the PR: delete the `pr-cherrypick` label and delete this branch.
You may also need to delete the `pr-backports-created` label from the original PR.

### CODE REVIEW

**Comment by robot-clickhouse-ci-2** [comment]
Dear @alesapin, @CheSema, the PR is not updated for 1d0h6m7s. Please, either resolve the conflicts, or close it to finish the backport process of #54549

**Comment by robot-clickhouse-ci-2** [comment]
Dear @alesapin, @CheSema, the PR is not updated for 1d0h56m27s. Please, either resolve the conflicts, or close it to finish the backport process of #54549

**Comment by robot-ch-test-poll3** [comment]
Dear @alesapin, @CheSema, the PR is not updated for 1d0h58m51s. Please, either resolve the conflicts, or close it to finish the backport process of #54549

**Comment by robot-ch-test-poll** [comment]
Dear @alesapin, @CheSema, the PR is not updated for 1d0h59m47s. Please, either resolve the conflicts, or close it to finish the backport process of #54549

**Comment by robot-ch-test-poll2** [comment]
Dear @alesapin, @CheSema, the PR is not updated for 1d1h1m15s. Please, either resolve the conflicts, or close it to finish the backport process of #54549

**Comment by robot-clickhouse** [comment]
Dear @alesapin, @CheSema, the PR is not updated for 1d0h57m12s. Please, either resolve the conflicts, or close it to finish the backport process of #54549

**Comment by robot-ch-test-poll4** [comment]
Dear @alesapin, @CheSema, the PR is not updated for 1d0h11m23s. Please, either resolve the conflicts, or close it to finish the backport process of #54549

**Comment by robot-ch-test-poll** [comment]
Dear @alesapin, @CheSema, the PR is not updated for 1d0h48m43s. Please, either resolve the conflicts, or close it to finish the backport process of #54549

**Comment by robot-ch-test-poll4** [comment]
Dear @alesapin, @CheSema, the PR is not updated for 1d0h1m36s. Please, either resolve the conflicts, or close it to finish the backport process of #54549

**Comment by robot-clickhouse** [comment]
Dear @alesapin, @CheSema, the PR is not updated for 1d1h5m1s. Please, either resolve the conflicts, or close it to finish the backport process of #54549

**Comment by robot-clickhouse-ci-2** [comment]
Dear @alesapin, @CheSema, the PR is not updated for 1d0h53m40s. Please, either resolve the conflicts, or close it to finish the backport process of #54549

**Comment by robot-ch-test-poll1** [comment]
Dear @alesapin, @CheSema, the PR is not updated for 1d0h7m33s. Please, either resolve the conflicts, or close it to finish the backport process of #54549

**Comment by robot-ch-test-poll4** [comment]
Dear @alesapin, @CheSema, the PR is not updated for 1d0h4m10s. Please, either resolve the conflicts, or close it to finish the backport process of #54549

**Comment by robot-ch-test-poll** [comment]
Dear @alesapin, @CheSema, the PR is not updated for 1d0h50m11s. Please, either resolve the conflicts, or close it to finish the backport process of #54549

**Comment by robot-ch-test-poll2** [comment]
Dear @alesapin, @CheSema, the PR is not updated for 1d0h57m36s. Please, either resolve the conflicts, or close it to finish the backport process of #54549

**Comment by robot-ch-test-poll3** [comment]
Dear @alesapin, @CheSema, the PR is not updated for 1d0h3m37s. Please, either resolve the conflicts, or close it to finish the backport process of #54549

**Pull request closed without merging**
