### PR TITLE
Follow-up to entropy-learned hashing

### PR DESCRIPTION
**Pull request by rschu1ze**
Based on #49999:
- optimize performance
- more extensive tests

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by robot-ch-test-poll** [comment]
This is an automated comment for commit 5693f36af7d5fa408768973536ee027abc4c9c66 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/50378/5693f36af7d5fa408768973536ee027abc4c9c66/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Comment by UnamedRus** [comment]
BTW, why define different versions of function via ID instead of their state, like some ML functions in ClickHouse?

**Comment by rschu1ze** [comment]
> BTW, why define different versions of function via ID instead of their state, like some ML functions in ClickHouse?

No particular reason, really. ELH is under an experimental flag, so this can be fixed separately.

**Comment by rschu1ze** [comment]
Cf. #50416

**Pull request closed without merging**
