### PR TITLE
Used main connection for suggestions in clickhouse-client

### LINKED ISSUE #52843: Make client receive suggestions from server if interactive connection is esablished
**Describe the issue**
Clickhouse client can't load suggestions using single connection when `max_sessions_for_user` is set.

**How to reproduce**

- Create a user with `<max_sessions_for_user>2</max_sessions_for_user>` in profile
- Connect to the server with clickhouse-client in interactive mode (starts a session)
- Run another instance of interactive clickhouse-client. If will fail to load suggestions (due to the limitation on concurrent sessions) but then will continue working as usual.

**Expected behavior**
No error happen in this case. Suggestions are loaded from the server using single session.

**Error message and/or stacktrace**
```
ClickHouse client version 23.7.1.1.
Connecting to localhost:9000 as user maxsessions.
Connected to ClickHouse server version 23.7.1 revision 54464.

Cannot load data for command line suggestions: Code: 700. DB::Exception: Received from localhost:9000. DB::Exception: User 5eb5f051-64a4-19bc-ff75-494154bf67a9 has overflown session count 2. () (version 23.7.1.1)
dell9510 :) select 1
```

### PR DESCRIPTION
**Pull request by Demilivor**
Closes #52843

If the client suggestion connection fails with `USER_SESSION_LIMIT_EXCEEDED` then the client will try to load suggestions with the first promted query using the main (interactive) connection/session in the main thread.

### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Client will load suggestions using the main connection if the second connection is not allowed to create a session.

### CODE REVIEW

**Comment by Demilivor** [comment]
@tavplubix Good day, Alexander, Could You please add a label 'Can be tested' and be the reviewer of this PR?

**Comment by alexey-milovidov** [comment]
Isn't this too much business-logic? Let's avoid loading suggestions if the limit is exceeded.

**Comment by Demilivor** [comment]
Without this change, it is impossible to load suggestions with only one session for user in interactive mode.
`--disable_suggestion (-A)` can be specified for clickhouse-client to avoid loading suggestions at all.

**Comment by robot-ch-test-poll2** [comment]
This is an automated comment for commit 121ab902abb6a445d5c06659ea3c05b5cf136c43 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/53177/121ab902abb6a445d5c06659ea3c05b5cf136c43/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Review by tavplubix — APPROVED** [review]

**Comment by tavplubix** [comment]
Integration tests (asan) [1/6] - #51464
Performance Comparison - https://github.com/ClickHouse/ClickHouse/pull/53131
Stateless tests - 01710_projection_part_check - https://github.com/ClickHouse/ClickHouse/pull/53272

**Pull request merged**
