### PR TITLE
Add async metrics for virtual memory mappings: VMMaxMapCount & VMNumMaps

### LINKED ISSUE #60662: New async metric VirtualMemoryMappings
**Use case**

I'm investigating quite strange case when ClickHouse 23.8 is kinda 'leaking' memory mappings when their number grows every day. 
After reaching the limit is start giving exceptions like 
```
It looks like that the process is near the limit on number of virtual memory mappings.
Current number of mappings (/proc/self/maps): 524289.
Limit on number of mappings (/proc/sys/vm/max_map_count): 524288.
You should increase the limit for vm.max_map_count in /etc/sysctl.conf
```
and 
```
<jemalloc>: Error in munmap(): Cannot allocate memory
```
and become unresponsible (being unable to start threads or allocate ram). 

I still not sure why it's happening (still checking), but would be nice to have an async metric for that. 

**Describe the solution you'd like**

system.asynchronous_metrics: 

VirtualMemoryMappings

Reflects the total number of memory mappings per process, aiding in monitoring resource utilization against the vm.max_map_count limit.

we have already the code to count the maps
https://github.com/ClickHouse/ClickHouse/blob/9bc9ca3bd96fdbc6e17dfecaf55777b399bc4722/src/Common/Exception.cpp#L308-L325

**Describe alternatives you've considered**

command line query 

```
pmap $(pidof clickhouse-server) -x 2>&1 |  clickhouse-local --input-format=Regexp --format_regexp='^\s*([0-9a-f]+)\s+([0-9]+)\s+([0-9]+)\s+([0-9]+)\s+(\S+)\s+(.*)' --format_regexp_skip_unmatched=1 --structure='Address String, Kbytes UInt64, RSS UInt64, Dirty UInt64, Mode String, Mapping String' --query='SELECT Mapping, Mode, count(), formatReadableSize(sum(Kbytes*1024)) as sum_virt, formatReadableSize(sum(RSS*1024)) as sum_rss, quantiles(0.01,0.25,0.5,0.75, 0.99)(Kbytes) as quantiles_kb from table GROUP BY Mapping, Mode ORDER BY count() FORMAT PrettyCompactMonoBlock'

┌─Mapping──────────────┬─Mode──┬─count()─┬─sum_virt───┬─sum_rss────┬─quantiles_kb───────────────────────────┐
│ libdl-2.31.so        │ rw--- │       1 │ 4.00 KiB   │ 4.00 KiB   │ [4,4,4,4,4]                            │
│ locale-archive       │ r---- │       1 │ 2.90 MiB   │ 400.00 KiB │ [2968,2968,2968,2968,2968]             │
│ libnss_files-2.31.so │ r-x-- │       1 │ 28.00 KiB  │ 28.00 KiB  │ [28,28,28,28,28]                       │
│ clickhouse           │ rw--- │       1 │ 160.00 KiB │ 128.00 KiB │ [160,160,160,160,160]                  │
│ librt-2.31.so        │ r-x-- │       1 │ 16.00 KiB  │ 16.00 KiB  │ [16,16,16,16,16]                       │
│ libnss_files-2.31.so │ rw--- │       1 │ 4.00 KiB   │ 4.00 KiB   │ [4,4,4,4,4]                            │
│ libnss_dns-2.31.so   │ rw--- │       1 │ 4.00 KiB   │ 4.00 KiB   │ [4,4,4,4,4]                            │
│ libresolv-2.31.so    │ rw--- │       1 │ 4.00 KiB   │ 4.00 KiB   │ [4,4,4,4,4]                            │
│ libc-2.31.so         │ r-x-- │       1 │ 1.47 MiB   │ 1.19 MiB   │ [1504,1504,1504,1504,1504]             │
│ libpthread-2.31.so   │ rw--- │       1 │ 4.00 KiB   │ 4.00 KiB   │ [4,4,4,4,4]                            │
│ libresolv-2.31.so    │ r-x-- │       1 │ 64.00 KiB  │ 36.00 KiB  │ [64,64,64,64,64]                       │
│ libpthread-2.31.so   │ r-x-- │       1 │ 68.00 KiB  │ 68.00 KiB  │ [68,68,68,68,68]                       │
│ libm-2.31.so         │ rw--- │       1 │ 4.00 KiB   │ 4.00 KiB   │ [4,4,4,4,4]                            │
│ librt-2.31.so        │ rw--- │       1 │ 4.00 KiB   │ 4.00 KiB   │ [4,4,4,4,4]                            │
│ libc-2.31.so         │ rw--- │       1 │ 8.00 KiB   │ 8.00 KiB   │ [8,8,8,8,8]                            │
│ libdl-2.31.so        │ r-x-- │       1 │ 8.00 KiB   │ 8.00 KiB   │ [8,8,8,8,8]                            │
│ libnss_dns-2.31.so   │ r-x-- │       1 │ 16.00 KiB  │ 8.00 KiB   │ [16,16,16,16,16]                       │
│ ld-2.31.so           │ rw--- │       1 │ 4.00 KiB   │ 4.00 KiB   │ [4,4,4,4,4]                            │
│ ld-2.31.so           │ r-x-- │       1 │ 140.00 KiB │ 140.00 KiB │ [140,140,140,140,140]                  │
│ libm-2.31.so         │ r-x-- │       1 │ 668.00 KiB │ 320.00 KiB │ [668,668,668,668,668]                  │
│ [ stack ]            │ rw--- │       1 │ 136.00 KiB │ 44.00 KiB  │ [136,136,136,136,136]                  │
│ clickhouse           │ r-x-- │       1 │ 285.29 MiB │ 217.77 MiB │ [292132,292132,292132,292132,292132]   │
│ librt-2.31.so        │ r---- │       3 │ 20.00 KiB  │ 16.00 KiB  │ [4.08,6,8,8,8]                         │
│ libnss_files-2.31.so │ r---- │       3 │ 24.00 KiB  │ 24.00 KiB  │ [4.08,6,8,10,11.92]                    │
│ libm-2.31.so         │ r---- │       3 │ 668.00 KiB │ 120.00 KiB │ [4.96,28,52,332,600.8]                 │
│ clickhouse           │ r---- │       3 │ 593.16 MiB │ 37.83 MiB  │ [2431.92,50046,99644,303472,499146.88] │
│ ld-2.31.so           │ r---- │       3 │ 40.00 KiB  │ 40.00 KiB  │ [4,4,4,18,31.439999999999998]          │
│ libpthread-2.31.so   │ r---- │       3 │ 52.00 KiB  │ 52.00 KiB  │ [4.4,14,24,24,24]                      │
│ libresolv-2.31.so    │ r---- │       3 │ 36.00 KiB  │ 8.00 KiB   │ [4.24,10,16,16,16]                     │
│ libc-2.31.so         │ r---- │       3 │ 464.00 KiB │ 440.00 KiB │ [18.4,76,136,224,308.48]               │
│ libnss_dns-2.31.so   │ r---- │       3 │ 12.00 KiB  │ 4.00 KiB   │ [4,4,4,4,4]                            │
│ libdl-2.31.so        │ r---- │       3 │ 12.00 KiB  │ 8.00 KiB   │ [4,4,4,4,4]                            │
│ [ anon ]             │ r---- │      10 │ 84.00 KiB  │ 72.00 KiB  │ [8,8,8,8,11.64]                        │
│ [ anon ]             │ r-x-- │      36 │ 284.00 KiB │ 276.00 KiB │ [5.4,8,8,8,8]                          │
│ [ anon ]             │ ----- │    1082 │ 4.23 MiB   │ 736.00 KiB │ [4,4,4,4,4]                            │
│ [ anon ]             │ rw--- │  124909 │ 6.94 GiB   │ 1.56 GiB   │ [4,4,4,12,112]                         │
└──────────────────────┴───────┴─────────┴────────────┴────────────┴────────────────────────────────────────┘
```

### PR DESCRIPTION
**Pull request by tuanpavn**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Add async metrics for virtual memory mappings: VMMaxMapCount & VMNumMaps. Closes #60662.

### CODE REVIEW

**Comment by robot-ch-test-poll** [comment]
*This is an automated comment for commit ab501ce6ce2dcee9190addf50f3c3bc963e661fd with description of existing statuses. It's updated for the latest CI running*

[❌ Click here](https://s3.amazonaws.com/clickhouse-test-reports/61354/ab501ce6ce2dcee9190addf50f3c3bc963e661fd/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td><a href="https://github.com/ClickHouse/ClickHouse/blob/master/.github/PULL_REQUEST_TEMPLATE.md?plain=1">❌ failure</a></td></tr>
<tbody>
</table>

**Comment by alexey-milovidov** [comment]
Ok. Let's add a test showing that the values at least exist and are not empty. You can use a simple, functional test (tests/queries).

**Comment by tuanpavn** [comment]
The test is added. Please help to review. Thanks.

> Ok. Let's add a test showing that the values at least exist and are not empty. You can use a simple, functional test (tests/queries).

**Comment by alexey-milovidov** [comment]
Looks good - please sign a CLA, and we can merge.

**Comment by tuanpavn** [comment]
> Looks good - please sign a CLA, and we can merge.

It has been signed.

I had to update the email of the commits to sign the CLA.
I also squashed them into one commit.

**Pull request merged**
