### PR TITLE
Fix serialize/deserialize of denominator of Average functions

### PR DESCRIPTION
**Pull request by bgiard**
**Description**

Use writeBinary/readBinary to serialize/deserialize the denominator of Average functions.

Previously it would be transmitted as an unsigned int, which means its value would get corrupted when doing an avgWeighted over a floating point number.

**Backwards compatibility (or lack thereof)**

This commit is not backwards compatible, but I am willing to work on backwards compatible version if maintainers judge it is necessary. The reason I didn't try to make it backwards compatible is because the only way I see to do it so far is to:
- write the max UInt value as some sort of flag in the serialize method, then write the binary value
- in the deserialize method, read the UInt, see if it is "max UInt". If it's not, use that value as the denominator, else, read the binary value of the actual denominator

That would be a little clumsy so I'd rather avoid having that kind of code.

**Test**

Did some manual testing, but also adding a query test. This is the result *without the fix*:
```
01268_shard_avgweighted:                                                [ FAIL ] - result differs with reference:
--- ..../tests/queries/0_stateless/01268_shard_avgweighted.reference 2020-05-08 15:10:12.185939081 -0400
+++ ..../tests/queries/0_stateless/01268_shard_avgweighted.stdout    2020-05-08 15:16:53.785654753 -0400
@@ -1,4 +1,4 @@
-100
+inf
 10
 0
 nan
```

Signed-off-by: Baudouin Giard <bgiard@bloomberg.net>

**Changelog category (leave one):**
- Bug Fix

**Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):**

Fix avgWeighted when using floating-point weight over multiple shards

**Developer's Certificate of Origin**

I was asked to attach a copy of the DCO to my PR:

```
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
I'm Ok with backward incompatible change.

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
avgWeighted is added recently and not widely used. It's remain compatible if weight is unsigned integer. We will warn users in changelog.

**Comment by bgiard** [comment]
Updated the description to pass the failing description test (switched category to only Bug Fix, since we can only have one).
Is there anything else I need to do? The perf test failing doesn't seem related to that change. About the functional tests, I can't really tell why it's failing (because of the skipped tests maybe)?

**Comment by alexey-milovidov** [comment]
I have checked and validated the failures manually.
All unrelated failures are collected here: #10775

**Pull request merged**
