### PR TITLE
Fix writing ORC statistics for unsigned types

### PR DESCRIPTION
**Pull request by al13n321**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fixed ORC statistics calculation, when writing, for unsigned types on all platforms and Int8 on ARM.

ORC doesn't have unsigned types. We were casting unsigned -> signed incorrectly (without sign-extension), so the orc library could write a file where the statistics don't match the data (e.g. maximum = 200 for type BYTE - this should be impossible, but it can be represented in the file because statistics are always 64-bit).

Also https://github.com/ClickHouse/orc/pull/13 fixes the library. When calculating min/max, it was casting BYTE values to `char`, which might be unsigned.

### CODE REVIEW

**Comment by robot-ch-test-poll2** [comment]
*This is an automated comment for commit 87e3a6b893e792bec147f91c941301a3dfe0d18c with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/64563/87e3a6b893e792bec147f91c941301a3dfe0d18c/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>A Sync</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>⏳ pending</td></tr>
<tbody>
</table>
<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

**Comment by alexey-milovidov** [comment]
Maybe also update the library?

**Comment by alexey-milovidov** [comment]
However, the new one also has the same error (we need to send a patch to them).

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
@al13n321, need to investigate the failed tests.

**Comment by al13n321** [comment]
* 02228_merge_tree_insert_memory_usage - flaky
* changed_settings.txt - breaks every month
* https://s3.amazonaws.com/clickhouse-test-reports/64563/40bea6199625c7fdad7510efed1e5bb7b275e92c/stateless_tests__aarch64_/gdb.log - segfault in libunwind
* https://s3.amazonaws.com/clickhouse-test-reports/64563/40bea6199625c7fdad7510efed1e5bb7b275e92c/stateless_tests__tsan__[5_5]/gdb.log - fixed recently, rebased.

**Comment by amosbird** [comment]
947cebaf9432d708253ac08dc3012daa6b4ede6f is now dangling after the merge of https://github.com/ClickHouse/orc/pull/13. The current commit is bcc025c09828c556f54cfbdf83a66b9acae7d17f.

**Comment by clickgapai** [comment]
Hi @al13n321 @alexey-milovidov — while reviewing this PR I found the following:

- **Bug (P1):** `Date` type values > 32767 days (after 2059-09-18) corrupted in ORC output due to `Int16` overflow — https://github.com/ClickHouse/ClickHouse/issues/104502

Happy to discuss — close anything that's wrong or already addressed.

**Pull request merged**
