### PR TITLE
Fix checking for rabbitmq liveness in tests

### PR DESCRIPTION
**Pull request by tchepavel**
### Changelog category (leave one):
- Build/Testing/Packaging Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix checking for rabbitmq liveness in tests. Fixed incorrect import

### CODE REVIEW

**Review by kssenii — APPROVED** [review]

**Comment by kssenii** [comment]
@Mergifyio update

**Comment by kssenii** [comment]
> Fast test (actions) — fail: 1

-- `02104_overcommit_memory` cc @novikd

**Comment by kssenii** [comment]
@Mergifyio update

**Comment by novikd** [comment]
> Fast test (actions) — fail: 1

It seems it's related to `clickhouse_client_loop_timeout`. cc @azat

**Pull request merged**
