### PR TITLE
Precise grants for users and roles management

### PR DESCRIPTION
**Pull request by pufit**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
This PR converts access types `CREATE_USER`, `ALTER_USER`, `DROP_USER`, `CREATE_ROLE`, `ALTER_ROLE`, `DROP_ROLE` from global to parameterized. That means users can now grant access management grants more precise:

`GRANT CREATE USER ON test_* TO user` will allow the user to create other users, but only with prefixes `test_`

For compatibility, all parameterized grants now support `*.*` as a target (e.g., `GRANT CREATE USER ON *.*`), which is automatically transformed to `*`

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Run only fuzzers related jobs (libFuzzer fuzzers, AST fuzzers, etc.)
- [ ]  Exclude: AST fuzzers
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-clickhouse-ci-2** [comment]
*This is an automated comment for commit 6cafef8da5b4595cc7b532bc23623b2726dc5e19 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/72246/6cafef8da5b4595cc7b532bc23623b2726dc5e19/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Style check</td><td>Runs a set of checks to keep the code style clean. If some of tests failed, see the related log from the report</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/72246/6cafef8da5b4595cc7b532bc23623b2726dc5e19/style_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Comment by vitlibar** [comment]
Changing your own password != changing the defaults

I mean it looks like we need a separate privilege for altering only a password (and nothing else) which will be a part of the `ALTER USER` privilege.

**Comment by vitlibar** [comment]
The first part of this PR is a good idea - it would be cool to be able to execute for example `GRANT CREATE USER ON test_* TO user`. But I believe it's better to split your PR into two quite independent parts:
1. `CREATE USER` and friends now allow a parameter
2. New privilege `SET PASSWORD` is added as a part of `ALTER USER`

**Comment by vitlibar** [comment]
Also it feels superfluous to add any implicit grants here in this PR. Not every user needs the privilege to change their password, and if necessary that privileges can be granted explicitly.

**Review by vitlibar — APPROVED** [review]

**Comment by pufit** [comment]
`test_dictionaries_postgresql/test.py::test_background_dictionary_reconnect`
`test_materialized_mysql_database/test.py::test_create_database_without_mysql_connection`
`02311_hashed_array_dictionary_hierarchical_functions`
All unrelated

**Pull request merged**
