### PR TITLE
Fix typos reported by codespell

### PR DESCRIPTION
**Pull request by filimonov**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix typos reported by codespell

Detailed description / Documentation draft:

### CODE REVIEW

**Review by akuzm — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
Looks like it doesn't run in CI, why?

**Comment by akuzm** [comment]
> Looks like it doesn't run in CI, why?

Half of the style check script doesn't run in CI, and the errors are ignored. Idk why, probably because nobody made it to run.

```
xargs: xmllint: No such file or directory
./check-typos: line 9: codespell: command not found
./check-style: line 77: shellcheck: command not found
xargs: shellcheck: No such file or directory
```

https://proxy.sandbox.yandex-team.ru/1797954634/style_check.out.log

**Comment by alexey-milovidov** [comment]
We should add it to Docker container.

**Comment by akuzm** [comment]
01150_ddl_guard_rwr failure is known, perf test failure is spurious.

**Pull request merged**
