### PR TITLE
Continue server start-up if dictionaries with broken metadata are present

### LINKED ISSUE #37571: Server fails to start when dictionary metadata is invalid
If a dictionary metadata is broken, the server fails to start.

**Relevant version**
To my observation the issue happens in 22.3+

**How to reproduce**
Created an integration test for the repro:
[tests/integration/test_dictionaries_broken_config/test.py::test_broken_dict[broken_metadata]](https://github.com/ClickHouse/ClickHouse/commit/9d1f8aa684628557a214b16c337ceb27e2fc14cf#diff-aad2ab88d46a3363a74367a643c8978338f5dbdb847864a741119cf7bf4bc584R44)

TLDR is 
1. create a dictionary with the following attribute:
```
    <attribute>
      <name>first</name>
      <type>UInt32</type>
      <!-- OOPS! null value incompatible with type -->
      <null_value>UNKNOWN</null_value>
    </attribute>
```
2. Write some data
3. Restart the instance, it won't start up.

**Non-default settings, if any**
I'm using   `<dictionaries_lazy_load>False</dictionaries_lazy_load>` but doesn't really seem to matter

**Expected behavior**
The server starts up. `ExternalDictionaryReloader` retires to reload the dictionary periodically.
`SELECT status FROM system.dictionaries` returns `FAILED`
`SELECT dictGet(...)` returns a client error with the exception below.

**Error message and/or stacktrace**
```
2022.05.26 15:26:33.027411 [ 1402 ] {} <Error> Application: DB::Exception: Error while loading dictionary 'dict.broken_metadata': DB::Exception: Unexpected data 'UNKNOWN' after parsed Number value '0': While parsing null_value for attribute with name first in dictionary broken_metadata
2022.05.26 15:26:33.027470 [ 1402 ] {} <Information> Application: shutting down
```
Notice no stack trace is shown on the main thread.

**Additional context**
The above exception is raised by [DictionaryStructure::getAttributes](https://github.com/ClickHouse/ClickHouse/blob/22.3/src/Dictionaries/DictionaryStructure.cpp#L340).

Since it's called in the main thread by [AsynchronousMetrics::update](https://github.com/ClickHouse/ClickHouse/blob/22.3/src/Interpreters/AsynchronousMetrics.cpp#L1339) via [ExternalDictionariesLoader::getDictionaryStructure](https://github.com/ClickHouse/ClickHouse/blob/22.3/src/Databases/DatabaseDictionary.cpp#L31) it ends up bringing the server down on starup.

On 21.8, this issue is not present - the dictionary is loaded successfully despite having invalid metadata.

### PR DESCRIPTION
**Pull request by tonickkozlov**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in official stable or prestable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Do not crash the server when a dictionary with invalid metadata is present.

Since 21.9 (approx.) having invalid metadata in dictionaries (e.g. when the default value is of wrong type) causes an exception. This change makes sure the server starts up successfully when one of the dictionaries is broken. Additionally, with this fix system.dictionaries reports the correct status (FAILED) and error message.

 Fixes #37571.

### CODE REVIEW

**Review by tavplubix — CHANGES_REQUESTED** [review]
Thank you for the pull request! However, I don't think we can merge it, because current behavior seems to be expected, there's no bug to fix. See https://github.com/ClickHouse/ClickHouse/issues/37571#issuecomment-1176125366

**Comment by tonickkozlov** [comment]
Thanks for your review @tavplubix . 
I understand your position although the behaviour of the previous LTS (21.8) is to continue loading the server with the broken dictionary. You can see that if you run the integration test from the PR. Would you say moving forward we should expect the new behaviour?

**Comment by tavplubix** [comment]
> the behaviour of the previous LTS (21.8) is to continue loading the server with the broken dictionary

Not precisely, 21.8 will fail to start (just like newer versions) if it fails to load a dictionary and lazy_load is false. But seems like 21.8 does not try to access `null_value` during loading, so no error happens and it loads this dictionary successfully and starts. When `null_value` should be checked and when an exception should be thrown is kind of implementation-defined-behavior and it was changed.

**Comment by tonickkozlov** [comment]
Thanks for your response @tavplubix, makes sense.

**Pull request closed without merging**
