### PR TITLE
Fix jemalloc under osx (zone_register() had been optimized out again)

### LINKED ISSUE #27568: [OSX] Server won't start
**Describe the bug**

OSx crashes right at the start when running the server.

**Does it reproduce on recent release?**

Tested with the official master build and building with master too:

**Error message and/or stacktrace**

```bash
$ ./clickhouse server
Processing configuration file 'config.xml'.
There is no file 'config.xml', will use embedded config.
Logging trace to console
Segmentation fault: 11


$ ../ClickHouse/build/programs/clickhouse-server
Processing configuration file 'config.xml'.
There is no file 'config.xml', will use embedded config.
Logging trace to console
Segmentation fault: 11
**Additional context**
```

Crash dump:
```
Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib              0x00007fff202ed946 __pthread_kill + 10
1   libsystem_pthread.dylib             0x00007fff2031c615 pthread_kill + 263
2   libsystem_c.dylib                   0x00007fff20271411 abort + 120
3   clickhouse-server                   0x000000010ee8d46d Poco::SignalHandler::handleSignal(int) + 45 (SignalHandler.cpp:94)
4   libsystem_platform.dylib            0x00007fff20361d7d _sigtramp + 29
5   dyld                                0x0000000127863799 ImageLoaderMachOCompressed::resolveTwolevel(ImageLoader::LinkContext const&, char c
onst*, ImageLoader const*, ImageLoader const*, unsigned int, bool, bool, ImageLoader const**) + 89
6   clickhouse-server                   0x00000001105e1d1d std::__1::unique_ptr<char, void (*)(void*)>::reset(char*) + 8 (memory:1658) [inline
d]
7   clickhouse-server                   0x00000001105e1d1d std::__1::unique_ptr<char, void (*)(void*)>::~unique_ptr() + 8 (memory:1612) [inlin
ed]
8   clickhouse-server                   0x00000001105e1d1d std::__1::unique_ptr<char, void (*)(void*)>::~unique_ptr() + 8 (memory:1612) [inlin
ed]
9   clickhouse-server                   0x00000001105e1d1d std::__1::__fs::filesystem::__canonical(std::__1::__fs::filesystem::path const&, st
d::__1::error_code*) + 189 (operations.cpp:643)
10  clickhouse-server                   0x00000001105e6335 std::__1::__fs::filesystem::__weakly_canonical(std::__1::__fs::filesystem::path con
st&, std::__1::error_code*) + 1077 (operations.cpp:1347)
11  clickhouse-server                   0x000000010e7cf9ea std::__1::__fs::filesystem::weakly_canonical(std::__1::__fs::filesystem::path const&) + 7 (filesystem:2219) [inlined]
12  clickhouse-server                   0x000000010e7cf9ea (anonymous namespace)::determineDefaultTimeZone() + 695 (DateLUT.cpp:78) [inlined]
13  clickhouse-server                   0x000000010e7cf9ea DateLUT::DateLUT() + 778 (DateLUT.cpp:144)
14  clickhouse-server                   0x000000010e7d14da DateLUT::DateLUT() + 12 (DateLUT.cpp:142) [inlined]
15  clickhouse-server                   0x000000010e7d14da DateLUT::getInstance() + 58 (DateLUT.cpp:162)
16  clickhouse-server                   0x000000010d09b2fa DateLUT::setDefaultTimezone(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) + 5 (DateLUT.h:37) [inlined]
17  clickhouse-server                   0x000000010d09b2fa BaseDaemon::initialize(Poco::Util::Application&) + 1978 (BaseDaemon.cpp:660)
18  clickhouse-server                   0x0000000107bcb41c DB::Server::initialize(Poco::Util::Application&) + 28
19  clickhouse-server                   0x000000010e80249b Poco::Util::Application::run() + 27 (Application.cpp:329)
20  clickhouse-server                   0x0000000107bcb356 DB::Server::run() + 662
21  clickhouse-server                   0x0000000107bc9bfe mainEntryClickHouseServer(int, char**) + 958
22  clickhouse-server                   0x0000000107b16cfb main + 1179 (main.cpp:366)
23  libdyld.dylib                       0x00007fff20337f3d start + 1
```

If I provide a config file (the default one modified to write things into /Users/r/ch and setting a timezone) it doesn't crash but aborts instead:

```
$ ./clickhouse server --config config/config.xml
Processing configuration file 'config/config.xml'.
Logging trace to /Users/r/ch/clickhouse-server/clickhouse-server.log
Abort trap: 6
```

> Add any other context about the problem here.

Happens both when running under a normal users and as root.

Tested on OSX 11.3.1 Big Sur (both under VM and real machine) and 11.4 (real machine).

The 21.6 branch (63cdcec58c07d0e0136cf2f1e54f880ceb1114e4, 21.6.9.1) built from source works. I'll try bisect it but it's a pretty slow process.

### PR DESCRIPTION
**Pull request by azat**
Changelog category (leave one):
- Not for changelog (changelog entry is not required)

*NOTE: that this has been marked as `Not for changelog` since original PR hadn't been included to any stable release yet*

Fixes: #27252
Fixes: #27568
Reverts: #27751
Refs: #11897
Refs: #27681
Cc: @Algunenano

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
Ok.

First I thought "Why do we need jemalloc in OS X with all these complications?"
But then remembered that we have performance tests https://clickhouse.tech/benchmark/hardware/

**Comment by Algunenano** [comment]
Looks good to me (haven't tested it). I tested moving back the zone call to the old file but that didn't work for some reason. I'd also consider re-enabling the allocator replacement in libroaring so it tracks memory under OSX too.

**Comment by azat** [comment]
This didn't work, will take a closer look.

>I'd also consider re-enabling the allocator replacement in libroaring so it tracks memory under OSX too.

Sure, once it will start working.

**Comment by azat** [comment]
Also note that disabling jemalloc (#27751) is not a option, since it will not allow to run ClickHouse under osx < 10.15.
Since ClickHouse requires `aligned_alloc` which exists only in 10.15 in default libc.
But, if jemalloc is in use, `aligned_alloc` is available regardless libc.

```
$ ./clickhouse client -q 'select 1'
dyld: lazy symbol binding failed: Symbol not found: _aligned_alloc
  Referenced from: /Users/vagrant/jemalloc-zone-register-test/.cmake/./clickhouse (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _aligned_alloc
  Referenced from: /Users/vagrant/jemalloc-zone-register-test/.cmake/./clickhouse (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib

Abort trap: 6
```

(This is the version from the #27751 under osx 10.14)

**Comment by azat** [comment]
>Fast test — fail: 1, passed: 2832, skipped: 480. Other tests won't be run before fast test will be fixed.

#27802

**Comment by Algunenano** [comment]
> Also note that disabling jemalloc (#27751) is not a option, since it will not allow to run ClickHouse under osx < 10.15.

Ough, that's not good. It's nos super bad as 10.13 is officially unsupported and 10.14 will be unsupported soon too (once the next macOS, Monterey, releases), but I wouldn't drop them unless there was a good reason for it.

By the way, I've done a clean build with b6f10854f and it seems to be working fine under 11.3.1.

**Comment by Algunenano** [comment]
6a600e5 works fine too!

```
$ nm programs/clickhouse | grep zone_register
                 U _malloc_zone_register
00000001070f4f60 T _zone_register
```

**Comment by azat** [comment]
>Ough, that's not good

Indeed. It hit me, because I had an old image in vagrant.

>By the way, I've done a clean build with b6f1085 and it seems to be working fine under 11.3.1.

Great, thanks for testing! (I've verified it under 10.15 and 10.14)

>6a600e5 works fine too!

Many thanks! (it is basically the same, just rebased to fix fast test)

**Review by alexey-milovidov — APPROVED** [review]
Ok.

I cannot validate the correctness of this PR, but still LGTM.

**Pull request merged**
