### PR TITLE
fix INSERT INTO table FROM INFILE does not display progress bar

### PR DESCRIPTION
**Pull request by xiedeyantu**
Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
fix INSERT INTO table FROM INFILE does not display progress bar

> Information about CI checks: https://clickhouse.tech/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by nickitat** [comment]
@Mergifyio update

**Comment by nickitat** [comment]
For some reason checks won't start

**Review by nickitat — APPROVED** [review]

**Comment by xiedeyantu** [comment]
> For some reason checks won't start

Could you help me see why checks still pending?

**Comment by nickitat** [comment]
> Could you help me see why checks still pending?

now everything looks ok

**Comment by xiedeyantu** [comment]
> > Could you help me see why checks still pending?
> 
> now everything looks ok

ok thanks

**Pull request merged**
