### PR TITLE
Introduce type contract checks in `IColumn`

### PR DESCRIPTION
**Pull request by nickitat**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Related: https://github.com/ClickHouse/ClickHouse/issues/65611

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Do not test
- [x]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-clickhouse** [comment]
*This is an automated comment for commit 4f53d60e25026409d98c2b0e6c77005b637bab4d with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/65687/4f53d60e25026409d98c2b0e6c77005b637bab4d/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Cloud fork sync (only for ClickHouse Inc. employees)</td><td>If it fails, ask a maintainer for help</td><td>⏳ pending</td></tr>
<tbody>
</table>
<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>Checks correctness of the PR's body</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

**Comment by nickitat** [comment]
unfortunately it seems clang no longer properly devirtualize calls to refactored methods (even though we do static_cast to the actual type).
waiting to get any pointers from clang maintainers here: https://github.com/llvm/llvm-project/issues/97344

**Comment by nickitat** [comment]
> unfortunately it seems clang no longer properly devirtualize calls to refactored methods (even though we do static_cast to the actual type). waiting to get any pointers from clang maintainers here: [llvm/llvm-project#97344](https://github.com/llvm/llvm-project/issues/97344)

unfortunately i see no solutions other than wrap changes in `#ifdef`-s.

**Review by alexey-milovidov — APPROVED** [review]

**Comment by antaljanosbenjamin** [comment]
Because of this PR AST fuzzer found some interesting query. I will check them out on Monday, but I think the problematic query is:
``` sql
WITH
    x AS
    (
        SELECT toLowCardinality(1 AS a)
        GROUP BY
            0.1,
            partitionId('ordinary:', 9, 9, 9, 9, 9, 9, 9, 9),
            partitionId(toNullable(toNullable('ordinary:')), 9, 9, 9, 9, toLowCardinality(toUInt128(9))),
            33.3
    ),
    xx AS
    (
        SELECT *
        FROM x, x AS x1, x AS x2
    )
SELECT partitionId('ordinary:', 9, 9, 9, 9, materialize(9), 9, 9, 9)
FROM xx
```

**Comment by nickitat** [comment]
> Because of this PR AST fuzzer found some interesting query. I will check them out on Monday, but I think the problematic query is:
> 
> ``` sql
> 
> WITH
> 
>     x AS
> 
>     (
> 
>         SELECT toLowCardinality(1 AS a)
> 
>         GROUP BY
> 
>             0.1,
> 
>             partitionId('ordinary:', 9, 9, 9, 9, 9, 9, 9, 9),
> 
>             partitionId(toNullable(toNullable('ordinary:')), 9, 9, 9, 9, toLowCardinality(toUInt128(9))),
> 
>             33.3
> 
>     ),
> 
>     xx AS
> 
>     (
> 
>         SELECT *
> 
>         FROM x, x AS x1, x AS x2
> 
>     )
> 
> SELECT partitionId('ordinary:', 9, 9, 9, 9, materialize(9), 9, 9, 9)
> 
> FROM xx
> 
> ```

It might be https://github.com/ClickHouse/ClickHouse/issues/66413

**Comment by antaljanosbenjamin** [comment]
> It might be https://github.com/ClickHouse/ClickHouse/pull/66413

Yes, and it fixes it.

**Pull request merged**
