### PR TITLE
Add support for rpmalloc

### PR DESCRIPTION
**Pull request by mkmkme**
Closes #30643

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Added support for building with `rpmalloc` instead of `jemalloc` (#30643).

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by mkmkme** [comment]
I had to use my fork of `rpmalloc` as a submodule because the original version also overrides `operator new` and `operator delete`

**Comment by robot-clickhouse** [comment]
*This is an automated comment for commit dae43bb01502970495ce21c4e665c53b8aed9014 with description of existing statuses. It's updated for the latest CI running*

[❌ Click here](https://s3.amazonaws.com/clickhouse-test-reports/56178/dae43bb01502970495ce21c4e665c53b8aed9014/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td><a href="https://github.com/ClickHouse/ClickHouse/actions/runs/6709492455">✅ success</a></td></tr>
<tbody>
</table>
</details>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/56178/dae43bb01502970495ce21c4e665c53b8aed9014/ci_running.html">❌ failure</a></td></tr>
<tbody>
</table>

**Comment by mkmkme** [comment]
The fails don't seem relevant.

**Comment by mkmkme** [comment]
Mac build fails. I'll make a follow-up commit to `rpmalloc` to fix this.

**Comment by mkmkme** [comment]
Fixed the compilation error, but the rpmalloc version of clickhouse segfaults immediately on macOS.

Looks like an `rpmalloc` internal bug. I'll take a look

**Comment by mkmkme** [comment]
Hmm, it seems the reason for crash is that `rpmalloc` is not initialised by the moment `operator new` was called for the first time. And for some reason, it seems that `operator new` from `contrib/libcxx` was called:

```
(lldb) bt
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
  * frame #0: 0x0000000000000000
    frame #1: 0x0000000109263d34 clickhouse`_rpmalloc_span_map [inlined] _rpmalloc_mmap(size=65536, offset=0x000000016fdfcf88) at rpmalloc.c:905:18 [opt]
    frame #2: 0x0000000109263d20 clickhouse`_rpmalloc_span_map [inlined] _rpmalloc_span_map_aligned_count(heap=0x00000001db425300, span_count=1) at rpmalloc.c:1185:26 [opt]
    frame #3: 0x0000000109263d10 clickhouse`_rpmalloc_span_map(heap=0x00000001db425300, span_count=1) at rpmalloc.c:1243:10 [opt]
    frame #4: 0x0000000109264ee0 clickhouse`_rpmalloc_heap_extract_new_span(heap=0x00000001db425300, heap_size_class=<unavailable>, span_count=2, class_idx=3) at rpmalloc.c:1876:9 [opt]
    frame #5: 0x0000000109264c48 clickhouse`_rpmalloc_allocate_from_heap_fallback(heap=0x00000001db425300, heap_size_class=0x00000001db425350, class_idx=3) at rpmalloc.c:2181:9 [opt]
    frame #6: 0x000000010df9ee5c clickhouse`operator new(size=40) at new.cpp:67:17 [opt]
    frame #7: 0x00000001000059b4 clickhouse`std::__1::pair<std::__1::__hash_iterator<std::__1::__hash_node<std::__1::__hash_value_type<std::__1::basic_string_view<char, std::__1::char_traits<char>>, void (*)(DB::FunctionFactory&)>, void*>*>, bool> std::__1::__hash_table<std::__1::__hash_value_type<std::__1::basic_string_view<char, std::__1::char_traits<char>>, void (*)(DB::FunctionFactory&)>, std::__1::__unordered_map_hasher<std::__1::basic_string_view<char, std::__1::char_traits<char>>, std::__1::__hash_value_type<std::__1::basic_string_view<char, std::__1::char_traits<char>>, void (*)(DB::FunctionFactory&)>, std::__1::hash<std::__1::basic_string_view<char, std::__1::char_traits<char>>>, std::__1::equal_to<std::__1::basic_string_view<char, std::__1::char_traits<char>>>, true>, std::__1::__unordered_map_equal<std::__1::basic_string_view<char, std::__1::char_traits<char>>, std::__1::__hash_value_type<std::__1::basic_string_view<char, std::__1::char_traits<char>>, void (*)(DB::FunctionFactory&)>, std::__1::equal_to<std::__1::basic_string_view<char, std::__1::char_traits<char>>>, std::__1::hash<std::__1::basic_string_view<char, std::__1::char_traits<char>>>, true>, std::__1::allocator<std::__1::__hash_value_type<std::__1::basic_string_view<char, std::__1::char_traits<char>>, void (*)(DB::FunctionFactory&)>>>::__emplace_unique_key_args<std::__1::basic_string_view<char, std::__1::char_traits<char>>, std::__1::basic_string_view<char, std::__1::char_traits<char>>, void (*&)(DB::FunctionFactory&)>(std::__1::basic_string_view<char, std::__1::char_traits<char>> const&, std::__1::basic_string_view<char, std::__1::char_traits<char>>&&, void (*&)(DB::FunctionFactory&)) + 340
    frame #8: 0x000000010000d734 clickhouse`DB::PODArrayBase<8ul, 4096ul, Allocator<false, false>, 63ul, 64ul>::minimum_memory_for_elements(unsigned long) + 244
    frame #9: 0x0000000183e015c8 dyld`invocation function for block in dyld4::Loader::findAndRunAllInitializers(dyld4::RuntimeState&) const::$_0::operator()() const + 168
    frame #10: 0x0000000183e466ec dyld`invocation function for block in dyld3::MachOAnalyzer::forEachInitializer(Diagnostics&, dyld3::MachOAnalyzer::VMAddrConverter const&, void (unsigned int) block_pointer, void const*) const + 172
    frame #11: 0x0000000183e39c60 dyld`invocation function for block in dyld3::MachOFile::forEachSection(void (dyld3::MachOFile::SectionInfo const&, bool, bool&) block_pointer) const + 496
    frame #12: 0x0000000183de12fc dyld`dyld3::MachOFile::forEachLoadCommand(Diagnostics&, void (load_command const*, bool&) block_pointer) const + 300
    frame #13: 0x0000000183e38c98 dyld`dyld3::MachOFile::forEachSection(void (dyld3::MachOFile::SectionInfo const&, bool, bool&) block_pointer) const + 192
    frame #14: 0x0000000183e3b780 dyld`dyld3::MachOFile::forEachInitializerPointerSection(Diagnostics&, void (unsigned int, unsigned int, bool&) block_pointer) const + 160
    frame #15: 0x0000000183e463e0 dyld`dyld3::MachOAnalyzer::forEachInitializer(Diagnostics&, dyld3::MachOAnalyzer::VMAddrConverter const&, void (unsigned int) block_pointer, void const*) const + 432
    frame #16: 0x0000000183dfd798 dyld`dyld4::Loader::findAndRunAllInitializers(dyld4::RuntimeState&) const + 448
    frame #17: 0x0000000183e03b14 dyld`dyld4::JustInTimeLoader::runInitializers(dyld4::RuntimeState&) const + 36
    frame #18: 0x0000000183dfdb4c dyld`dyld4::Loader::runInitializersBottomUp(dyld4::RuntimeState&, dyld3::Array<dyld4::Loader const*>&) const + 220
    frame #19: 0x0000000183e01654 dyld`dyld4::Loader::runInitializersBottomUpPlusUpwardLinks(dyld4::RuntimeState&) const::$_1::operator()() const + 112
    frame #20: 0x0000000183dfdccc dyld`dyld4::Loader::runInitializersBottomUpPlusUpwardLinks(dyld4::RuntimeState&) const + 304
    frame #21: 0x0000000183e22ad4 dyld`dyld4::APIs::runAllInitializersForMain() + 464
    frame #22: 0x0000000183de5f34 dyld`dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*) + 3192
    frame #23: 0x0000000183de4f44 dyld`start + 1948
(lldb)
```

Is there any scenario when it is expected to call `operator new` from `contrib/libcxx`?

**Comment by nikitamikhaylov** [comment]
Let's rerun the CI with the whole set of performance tests. Can you please send an empty commit?

**Comment by mkmkme** [comment]
>Let's rerun the CI with the whole set of performance tests. Can you please send an empty commit?

For that to compare, we also need to change CI to run with `rpmalloc`. By default, `rpmalloc` is disabled and `jemalloc` is used.

**Comment by Algunenano** [comment]
> For that to compare, we also need to change CI to run with rpmalloc. By default, rpmalloc is disabled and jemalloc is used.

Please change the default in a commit. The idea is to verify the performance; if it's worth it then we can clean everything up later on.

**Comment by mkmkme** [comment]
Oh, I didn't disable the `jemalloc bins` test. Hope it doesn't break the CI in a way that performance tests would be skipped.

**Comment by nickitat** [comment]
```
Nov 03 08:54:49 CMake Error at programs/keeper/CMakeLists.txt:184 (target_link_libraries):
Nov 03 08:54:49   Target "clickhouse-keeper" links to:
Nov 03 08:54:49 
Nov 03 08:54:49     ch_contrib::jemalloc
Nov 03 08:54:49 
Nov 03 08:54:49   but the target was not found.  Possible reasons include:
Nov 03 08:54:49 
Nov 03 08:54:49     * There is a typo in the target name.
Nov 03 08:54:49     * A find_package call is missing for an IMPORTED target.
Nov 03 08:54:49     * An ALIAS target is missing.
Nov 03 08:54:49 
Nov 03 08:54:49 
Nov 03 08:54:49 
Nov 03 08:54:49 -- Generating done (1.4s)
Nov 03 08:54:49 CMake Warning:
Nov 03 08:54:49   Manually-specified variables were not used by the project:
Nov 03 08:54:49 
Nov 03 08:54:49     CMAKE_AUTOGEN_VERBOSE
Nov 03 08:54:49     CMAKE_EXPORT_NO_PACKAGE_REGISTRY
```

**Comment by mkmkme** [comment]
@nickitat huh quite odd that I couldn't reproduce it...
I've pushed a follow-up commit here. Please check if it fixes it for you.

**Comment by alexey-milovidov** [comment]
All tests have failed.
Performance is much lower, 12..16% on average, up to 18 times on specific tests.

**Comment by alexey-milovidov** [comment]
@mkmkme 

> Do you mind if I keep using your CI in order to poke into the rpmalloc settings?

Yes, feel free to try, you can do it as many times as you want.

**Pull request closed without merging**
