### PR TITLE
Try fixing 03144_parallel_alter_add_drop_column_zookeeper_on_steroids

### PR DESCRIPTION
**Pull request by Algunenano**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
- Try fixing 03144_parallel_alter_add_drop_column_zookeeper_on_steroids

Checked a couple of runs and the problem was that a mutation with `DROP COLUMN value${random}` was stuck because at that point the column did not exists (we create and drop columns randomly). Then the next mutation could not execute and the test executes forever:

https://github.com/ClickHouse/ClickHouse/blob/a92b391b473a3ab18be548e08d2df48ad23e3b48/tests/queries/0_stateless/03144_parallel_alter_add_drop_column_zookeeper_on_steroids.sh#L131-L134

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-ch-test-poll1** [comment]
*This is an automated comment for commit a92b391b473a3ab18be548e08d2df48ad23e3b48 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/66547/a92b391b473a3ab18be548e08d2df48ad23e3b48/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Builds</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/66516/425ebf557ad872e8efbba239070cc1885769cdf7/builds/report.html">✅ success</a></td></tr>
<tr><td>ClickBench</td><td>Runs [ClickBench](https://github.com/ClickHouse/ClickBench/) with instant-attach table</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/e4f348acc7842caa20866fbd3b3ce6f24e5b9b17/clickbench__aarch64_.html">✅ success</a></td></tr>
<tr><td>Compatibility check</td><td>Checks that <b>clickhouse</b> binary runs on distributions with old libc versions. If it fails, ask a maintainer for help</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/e4f348acc7842caa20866fbd3b3ce6f24e5b9b17/compatibility_check__aarch64_.html">✅ success</a></td></tr>
<tr><td>Docker keeper image</td><td>The check to build and optionally push the mentioned image to docker hub</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/e4f348acc7842caa20866fbd3b3ce6f24e5b9b17/docker_keeper_image.html">✅ success</a></td></tr>
<tr><td>Docker server image</td><td>The check to build and optionally push the mentioned image to docker hub</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/e4f348acc7842caa20866fbd3b3ce6f24e5b9b17/docker_server_image.html">✅ success</a></td></tr>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td>✅ success</td></tr>
<tr><td>Install packages</td><td>Checks that the built packages are installable in a clear environment</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/e4f348acc7842caa20866fbd3b3ce6f24e5b9b17/install_packages__aarch64_.html">✅ success</a></td></tr>
<tr><td>Integration tests</td><td>The integration tests report. In parenthesis the package type is given, and in square brackets are the optional part/total tests</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/e4f348acc7842caa20866fbd3b3ce6f24e5b9b17/integration_tests__aarch64__[1_6].html">✅ success</a></td></tr>
<tr><td>Performance Comparison</td><td>Measure changes in query performance. The performance test report is described in detail <a href="https://github.com/ClickHouse/ClickHouse/tree/master/docker/test/performance-comparison#how-to-read-the-report">here</a>. In square brackets are the optional part/total tests</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/e4f348acc7842caa20866fbd3b3ce6f24e5b9b17/performance_comparison__release__[1_4]/report.html">✅ success</a></td></tr>
<tr><td>Unit tests</td><td>Runs the unit tests for different release types</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/e4f348acc7842caa20866fbd3b3ce6f24e5b9b17/unit_tests__asan_.html">✅ success</a></td></tr>
<tr><td>Upgrade check</td><td>Runs stress tests on server version from last release and then tries to upgrade it to the version from the PR. It checks if the new server can successfully startup without any errors, crashes or sanitizer asserts</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/66533/249812822dedffd7062db0d2d2383cade646b802/upgrade_check__debug_.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Comment by Algunenano** [comment]
Changing to draft since it seems something else completely

**Comment by Algunenano** [comment]
Seems there is some race condition in the memory metadata snapshot:

* Checking https://s3.amazonaws.com/clickhouse-test-reports/0/9d79bd96250fb8ee9057343f02614db331172494/stateless_tests__aarch64_.html

* Error:

```

2024.07.03 15:29:33.402760 [ 1381 ] {} <Error> 9aa428c3-e183-4c40-b64d-b7f56f77083f::all_0_90_171_99 (MergeFromLogEntryTask): virtual bool DB::ReplicatedMergeMutateTaskBase::executeStep(): Code: 16. DB::Exception: There is no column value5 in table. (NO_SUCH_COLUMN_IN_TABLE), Stack trace (when copying this message, always include the lines below):

0. ./contrib/llvm-project/libcxx/include/vector:666: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000c7de128
1. DB::Exception::Exception(PreformattedMessage&&, int) @ 0x0000000007be025c
2. DB::Exception::Exception<String const&>(int, FormatStringHelperImpl<std::type_identity<String const&>::type>, String const&) @ 0x0000000007bf0e78
3. ./build_docker/./src/Storages/StorageSnapshot.cpp:142: DB::StorageSnapshot::getColumn(DB::GetColumnsOptions const&, String const&) const @ 0x0000000010b26670
4. ./contrib/llvm-project/libcxx/include/new:246: DB::StorageSnapshot::getColumnsByNames(DB::GetColumnsOptions const&, std::vector<String, std::allocator<String>> const&) const @ 0x0000000010b263d0
5. ./build_docker/./src/Storages/MergeTree/MergeTreeSequentialSource.cpp:136: DB::createMergeTreeSequentialSource(DB::MergeTreeSequentialSourceType, DB::MergeTreeData const&, std::shared_ptr<DB::StorageSnapshot> const&, std::shared_ptr<DB::IMergeTreeDataPart const>, std::vector<String, std::allocator<String>>, std::optional<DB::MarkRanges>, std::shared_ptr<std::atomic<unsigned long>>, bool, bool, bool) @ 0x0000000010f58040
6. ./contrib/llvm-project/libcxx/include/optional:260: DB::MergeTask::VerticalMergeStage::createPipeForReadingOneColumn(String const&) const @ 0x0000000010dc4a08
7. ./build_docker/./src/Storages/MergeTree/MergeTask.cpp:638: DB::MergeTask::VerticalMergeStage::executeVerticalMergeForAllColumns() const @ 0x0000000010dc8194
8. ./build_docker/./src/Storages/MergeTree/MergeTask.cpp:891: DB::MergeTask::VerticalMergeStage::execute() @ 0x0000000010dc7c6c
9. ./build_docker/./src/Storages/MergeTree/MergeTask.cpp:951: DB::MergeTask::execute() @ 0x0000000010dc7710
10. ./build_docker/./src/Storages/MergeTree/ReplicatedMergeMutateTaskBase.cpp:208: DB::ReplicatedMergeMutateTaskBase::executeStep() @ 0x000000001101e0c8
11. ./build_docker/./src/Storages/MergeTree/MergeTreeBackgroundExecutor.cpp:294: DB::MergeTreeBackgroundExecutor<DB::DynamicRuntimeQueue>::threadFunction() @ 0x0000000010dda794
12. ./base/base/../base/wide_integer_impl.h:817: ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::worker(std::__list_iterator<ThreadFromGlobalPoolImpl<false, true>, void*>) @ 0x000000000c880224
13. ./src/Common/ThreadPool.h:252: void std::__function::__policy_invoker<void ()>::__call_impl<std::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<false, true>::ThreadFromGlobalPoolImpl<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>(void&&)::'lambda'(), void ()>>(std::__function::__policy_storage const*) @ 0x000000000c883df0
14. ./base/base/../base/wide_integer_impl.h:817: void* std::__thread_proxy[abi:v15000]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void ThreadPoolImpl<std::thread>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>>(void*) @ 0x000000000c882aa0
15. ? @ 0x000000000007d5c8
16. ? @ 0x00000000000e5edc
 (version 24.7.1.873 (official build))
```

* The merge was produce by an OPTIMIZE:
```
2024.07.03 15:29:33.346130 [ 2221 ] {e767617a-9fc5-4507-ba42-71c57b4eeed8} <Debug> executeQuery: (from [::1]:54348) (comment: 03144_parallel_alter_add_drop_column_zookeeper_on_steroids.sh) OPTIMIZE TABLE concurrent_alter_add_drop_steroids_1 FINAL SETTINGS replication_alter_partitions_sync=0 (stage: Complete)
2024.07.03 15:29:33.358167 [ 2221 ] {e767617a-9fc5-4507-ba42-71c57b4eeed8} <Debug> test_050h1eez.concurrent_alter_add_drop_steroids_1 (bbf70758-d2bb-4631-8b1d-4874ebe67d0b) (MergerMutator): Selected 1 parts from all_0_90_170_99 to all_0_90_170_99
2024.07.03 15:29:33.359091 [ 2221 ] {e767617a-9fc5-4507-ba42-71c57b4eeed8} <Trace> test_050h1eez.concurrent_alter_add_drop_steroids_1 (bbf70758-d2bb-4631-8b1d-4874ebe67d0b): Created log entry /clickhouse/tables/03144_parallel_alter_add_drop_column_zookeeper_on_steroids_test_050h1eez/concurrent_alter_add_drop_steroids_column/log/log-0000000460 for merge all_0_90_171_99
2024.07.03 15:29:33.359222 [ 2221 ] {e767617a-9fc5-4507-ba42-71c57b4eeed8} <Debug> TCPHandler: Processed in 0.013629309 sec.
```

* Checking the disk, the column **does exist** (in all 3 replicas):

```bash
$ for dir in $(find . -name all_0_90_170*); do echo $dir; ls $dir; done
./lib/clickhouse/store/bbf/bbf70758-d2bb-4631-8b1d-4874ebe67d0b/all_0_90_170_99
checksums.txt  columns.txt  count.txt  default_compression_codec.txt  key.bin  key.cmrk2  metadata_version.txt  primary.cidx  value0.bin  value0.cmrk2  value5.bin  value5.cmrk2
./lib/clickhouse/store/9aa/9aa428c3-e183-4c40-b64d-b7f56f77083f/all_0_90_170_99
checksums.txt  columns.txt  count.txt  default_compression_codec.txt  key.bin  key.cmrk2  metadata_version.txt  primary.cidx  value0.bin  value0.cmrk2  value5.bin  value5.cmrk2
./lib/clickhouse/store/014/0147fd29-0368-49e3-910c-58eebd1151b8/all_0_90_170_99
checksums.txt  columns.txt  count.txt  default_compression_codec.txt  key.bin  key.cmrk2  metadata_version.txt  primary.cidx  value0.bin  value0.cmrk2  value5.bin  value5.cmrk2
```

* Checking the merge log

It reads columns correctly until it fails reading `value5`:

```
$ grep all_0_90_171_99 aaa.log
2024.07.03 15:29:33.359091 [ 2221 ] {e767617a-9fc5-4507-ba42-71c57b4eeed8} <Trace> test_050h1eez.concurrent_alter_add_drop_steroids_1 (bbf70758-d2bb-4631-8b1d-4874ebe67d0b): Created log entry /clickhouse/tables/03144_parallel_alter_add_drop_column_zookeeper_on_steroids_test_050h1eez/concurrent_alter_add_drop_steroids_column/log/log-0000000460 for merge all_0_90_171_99
2024.07.03 15:29:33.361978 [ 951 ] {} <Trace> test_050h1eez.concurrent_alter_add_drop_steroids_2 (ReplicatedMergeTreeQueue): Insert entry queue-0000000460 to queue with type MERGE_PARTS with virtual parts [all_0_90_171_99]
2024.07.03 15:29:33.362098 [ 1386 ] {} <Trace> 9aa428c3-e183-4c40-b64d-b7f56f77083f::all_0_90_171_99 (MergeFromLogEntryTask): Executing log entry to merge parts all_0_90_170_99 to all_0_90_171_99
2024.07.03 15:29:33.362226 [ 1386 ] {9aa428c3-e183-4c40-b64d-b7f56f77083f::all_0_90_171_99} <Debug> MergeTask::PrepareStage: Merging 1 parts: from all_0_90_170_99 to all_0_90_170_99 into Wide with storage Full
2024.07.03 15:29:33.362313 [ 1386 ] {9aa428c3-e183-4c40-b64d-b7f56f77083f::all_0_90_171_99} <Debug> MergeTask::PrepareStage: Selected MergeAlgorithm: Vertical
2024.07.03 15:29:33.362500 [ 1386 ] {9aa428c3-e183-4c40-b64d-b7f56f77083f::all_0_90_171_99} <Debug> MergeTask::PrepareStage: Will merge parts reading files in O_DIRECT
2024.07.03 15:29:33.362523 [ 1386 ] {9aa428c3-e183-4c40-b64d-b7f56f77083f::all_0_90_171_99} <Debug> MergeTreeSequentialSource: Reading 18 marks from part all_0_90_170_99, total 100005 rows starting from the beginning of the part, column key
2024.07.03 15:29:33.363559 [ 1191 ] {} <Trace> test_050h1eez.concurrent_alter_add_drop_steroids_3 (ReplicatedMergeTreeQueue): Insert entry queue-0000000460 to queue with type MERGE_PARTS with virtual parts [all_0_90_171_99]
2024.07.03 15:29:33.363676 [ 1382 ] {} <Trace> 0147fd29-0368-49e3-910c-58eebd1151b8::all_0_90_171_99 (MergeFromLogEntryTask): Executing log entry to merge parts all_0_90_170_99 to all_0_90_171_99
2024.07.03 15:29:33.363801 [ 1382 ] {0147fd29-0368-49e3-910c-58eebd1151b8::all_0_90_171_99} <Debug> MergeTask::PrepareStage: Merging 1 parts: from all_0_90_170_99 to all_0_90_170_99 into Wide with storage Full
2024.07.03 15:29:33.363877 [ 1382 ] {0147fd29-0368-49e3-910c-58eebd1151b8::all_0_90_171_99} <Debug> MergeTask::PrepareStage: Selected MergeAlgorithm: Vertical
2024.07.03 15:29:33.364051 [ 1382 ] {0147fd29-0368-49e3-910c-58eebd1151b8::all_0_90_171_99} <Debug> MergeTask::PrepareStage: Will merge parts reading files in O_DIRECT
2024.07.03 15:29:33.364069 [ 1382 ] {0147fd29-0368-49e3-910c-58eebd1151b8::all_0_90_171_99} <Debug> MergeTreeSequentialSource: Reading 18 marks from part all_0_90_170_99, total 100005 rows starting from the beginning of the part, column key
2024.07.03 15:29:33.364892 [ 812 ] {} <Trace> test_050h1eez.concurrent_alter_add_drop_steroids_1 (ReplicatedMergeTreeQueue): Insert entry queue-0000000460 to queue with type MERGE_PARTS with virtual parts [all_0_90_171_99]
2024.07.03 15:29:33.365001 [ 1377 ] {} <Trace> bbf70758-d2bb-4631-8b1d-4874ebe67d0b::all_0_90_171_99 (MergeFromLogEntryTask): Executing log entry to merge parts all_0_90_170_99 to all_0_90_171_99
2024.07.03 15:29:33.365173 [ 1377 ] {bbf70758-d2bb-4631-8b1d-4874ebe67d0b::all_0_90_171_99} <Debug> MergeTask::PrepareStage: Merging 1 parts: from all_0_90_170_99 to all_0_90_170_99 into Wide with storage Full
2024.07.03 15:29:33.365253 [ 1377 ] {bbf70758-d2bb-4631-8b1d-4874ebe67d0b::all_0_90_171_99} <Debug> MergeTask::PrepareStage: Selected MergeAlgorithm: Vertical
2024.07.03 15:29:33.366341 [ 1377 ] {bbf70758-d2bb-4631-8b1d-4874ebe67d0b::all_0_90_171_99} <Debug> MergeTask::PrepareStage: Will merge parts reading files in O_DIRECT
2024.07.03 15:29:33.366371 [ 1377 ] {bbf70758-d2bb-4631-8b1d-4874ebe67d0b::all_0_90_171_99} <Debug> MergeTreeSequentialSource: Reading 18 marks from part all_0_90_170_99, total 100005 rows starting from the beginning of the part, column key
2024.07.03 15:29:33.383254 [ 1378 ] {9aa428c3-e183-4c40-b64d-b7f56f77083f::all_0_90_171_99} <Debug> MergeTreeSequentialSource: Reading 18 marks from part all_0_90_170_99, total 100005 rows starting from the beginning of the part, column value0
2024.07.03 15:29:33.385028 [ 1373 ] {0147fd29-0368-49e3-910c-58eebd1151b8::all_0_90_171_99} <Debug> MergeTreeSequentialSource: Reading 18 marks from part all_0_90_170_99, total 100005 rows starting from the beginning of the part, column value0
2024.07.03 15:29:33.386472 [ 1388 ] {bbf70758-d2bb-4631-8b1d-4874ebe67d0b::all_0_90_171_99} <Debug> MergeTreeSequentialSource: Reading 18 marks from part all_0_90_170_99, total 100005 rows starting from the beginning of the part, column value0
2024.07.03 15:29:33.393068 [ 1381 ] {9aa428c3-e183-4c40-b64d-b7f56f77083f::all_0_90_171_99} <Debug> MergeTreeSequentialSource: Reading 18 marks from part all_0_90_170_99, total 100005 rows starting from the beginning of the part, column value4
2024.07.03 15:29:33.398657 [ 1384 ] {0147fd29-0368-49e3-910c-58eebd1151b8::all_0_90_171_99} <Debug> MergeTreeSequentialSource: Reading 18 marks from part all_0_90_170_99, total 100005 rows starting from the beginning of the part, column value4
2024.07.03 15:29:33.401265 [ 1375 ] {bbf70758-d2bb-4631-8b1d-4874ebe67d0b::all_0_90_171_99} <Debug> MergeTreeSequentialSource: Reading 18 marks from part all_0_90_170_99, total 100005 rows starting from the beginning of the part, column value4
2024.07.03 15:29:33.402760 [ 1381 ] {} <Error> 9aa428c3-e183-4c40-b64d-b7f56f77083f::all_0_90_171_99 (MergeFromLogEntryTask): virtual bool DB::ReplicatedMergeMutateTaskBase::executeStep(): Code: 16. DB::Exception: There is no column value5 in table. (NO_SUCH_COLUMN_IN_TABLE), Stack trace (when copying this message, always include the lines below):
2024.07.03 15:29:33.402859 [ 1381 ] {} <Error> MergeTreeBackgroundExecutor: Exception while executing background task {9aa428c3-e183-4c40-b64d-b7f56f77083f::all_0_90_171_99}: Code: 16. DB::Exception: There is no column value5 in table. (NO_SUCH_COLUMN_IN_TABLE), Stack trace (when copying this message, always include the lines below):
```


Checking the queries there was a `DROP COLUMN` right when `OPTIMIZE` was being called:
```
2024.07.03 15:29:33.196195 [ 34720 ] {6cde092c-1441-41c0-b2eb-29ff5390d2f4} <Debug> executeQuery: (from [::1]:54300) (comment: 03144_parallel_alter_add_drop_column_zookeeper_on_steroids.sh) OPTIMIZE TABLE concurrent_alter_add_drop_steroids_2 FINAL SETTINGS replication_alter_partit
ions_sync=0 (stage: Complete)
2024.07.03 15:29:33.225048 [ 34720 ] {e0dcec2c-7ec6-4bdb-94ae-53bb75e08999} <Debug> executeQuery: (from [::1]:54314) (comment: 03144_parallel_alter_add_drop_column_zookeeper_on_steroids.sh) INSERT INTO concurrent_alter_add_drop_steroids_2 VALUES (stage: Complete)
2024.07.03 15:29:33.255653 [ 16029 ] {e9bc7703-5d0e-427e-ad52-345cf2406db7} <Debug> executeQuery: (from [::1]:54320) (comment: 03144_parallel_alter_add_drop_column_zookeeper_on_steroids.sh) ALTER TABLE concurrent_alter_add_drop_steroids_1 ADD COLUMN value4 UInt32 DEFAULT 42 SETTIN
GS replication_alter_partitions_sync=0 (stage: Complete)
2024.07.03 15:29:33.331543 [ 34720 ] {537a829c-6d84-499b-8fb4-1dbf7e167d9d} <Debug> executeQuery: (from [::1]:54330) (comment: 03144_parallel_alter_add_drop_column_zookeeper_on_steroids.sh) SELECT * FROM merge(currentDatabase(), 'concurrent_alter_add_drop_steroids_') FORMAT Null (
stage: Complete)
2024.07.03 15:29:33.336194 [ 16029 ] {d716b883-ca0e-40a2-bf92-20dcb81b9338} <Debug> executeQuery: (from [::1]:54334) (comment: 03144_parallel_alter_add_drop_column_zookeeper_on_steroids.sh) ALTER TABLE concurrent_alter_add_drop_steroids_1 DROP COLUMN value5 SETTINGS replication_al
ter_partitions_sync=0 (stage: Complete)
2024.07.03 15:29:33.346130 [ 2221 ] {e767617a-9fc5-4507-ba42-71c57b4eeed8} <Debug> executeQuery: (from [::1]:54348) (comment: 03144_parallel_alter_add_drop_column_zookeeper_on_steroids.sh) OPTIMIZE TABLE concurrent_alter_add_drop_steroids_1 FINAL SETTINGS replication_alter_partitions_sync=0 (stage: Complete)
2024.07.03 15:29:33.357176 [ 34722 ] {eca8b92f-c14e-481f-8f68-988521b7403c} <Debug> executeQuery: (from [::1]:54354) (comment: 03144_parallel_alter_add_drop_column_zookeeper_on_steroids.sh) ALTER TABLE concurrent_alter_add_drop_steroids_3 ADD COLUMN value4 UInt32 DEFAULT 42 SETTINGS replication_alter_partitions_sync=0 (stage: Complete)
```

This is why I suspect (but haven't confirmed) that the merge order (OPTIMIZE) might come from before the column was dropped, but the snapshot to execute this merge might have happened after the column was removed from memory. This is just a hunch. No findings yet

**Comment by Algunenano** [comment]
I've skimmed through 5-6 error reports and it seems in all cases it fails when doing a vertical merge, and I've never seen a failure in a horizontal merge. Considering we are inserting one row at a time and randomizing merge type, it might be a problem there and not related to the snapshot

**Comment by Algunenano** [comment]
Reproduced by forcing vertical merges and running a few times:

```
diff --git a/tests/queries/0_stateless/03144_parallel_alter_add_drop_column_zookeeper_on_steroids.sh b/tests/queries/0_stateless/03144_parallel_alter_add_drop_column_zookeeper_on_steroids.sh
index c27dfffcfc2..0eff92463df 100755
--- a/tests/queries/0_stateless/03144_parallel_alter_add_drop_column_zookeeper_on_steroids.sh
+++ b/tests/queries/0_stateless/03144_parallel_alter_add_drop_column_zookeeper_on_steroids.sh
@@ -15,7 +15,17 @@ done
 
 
 for i in $(seq $REPLICAS); do
-    $CLICKHOUSE_CLIENT --query "CREATE TABLE concurrent_alter_add_drop_steroids_$i (key UInt64, value0 UInt8) ENGINE = ReplicatedMergeTree('/clickhouse/tables/$CLICKHOUSE_TEST_ZOOKEEPER_PREFIX/concurrent_alter_add_drop_steroids_column', '$i') ORDER BY key SETTINGS max_replicated_mutations_in_queue = 1000, number_of_free_entries_in_pool_to_execute_mutation = 0, max_replicated_merges_in_queue = 1000, index_granularity = 8192, index_granularity_bytes = '10Mi'"
+    $CLICKHOUSE_CLIENT --query "CREATE TABLE concurrent_alter_add_drop_steroids_$i (key UInt64, value0 UInt8)
+    ENGINE = ReplicatedMergeTree('/clickhouse/tables/$CLICKHOUSE_TEST_ZOOKEEPER_PREFIX/concurrent_alter_add_drop_steroids_column', '$i')
+    ORDER BY key
+    SETTINGS
+      max_replicated_mutations_in_queue = 1000,
+      number_of_free_entries_in_pool_to_execute_mutation = 0,
+      max_replicated_merges_in_queue = 1000,
+      index_granularity = 8192,
+      index_granularity_bytes = '10Mi',
+      vertical_merge_algorithm_min_rows_to_activate=1,
+      vertical_merge_algorithm_min_columns_to_activate=1"
 done
 
 $CLICKHOUSE_CLIENT --query "INSERT INTO concurrent_alter_add_drop_steroids_1 SELECT number, number + 10 from numbers(100000)"
```

```
./tests/clickhouse-test --print-time --test-runs 100 03144_parallel
```

Just filter the logs looking for `executeVerticalMergeForAllColumns` until it appears.

Then I attached gdb and changed the merge mode to Horizontal (3 times, once per replica):

```
br /mnt/ch/ClickHouse/src/Storages/MergeTree/MergeTask.cpp:323
set (*global_ctx.__ptr_).chosen_merge_algorithm = MergeAlgorithm::Horizontal
```

It got unstuck and the test finished. This seems to confirm vertical merges are likely the culprit.

**Comment by Algunenano** [comment]
I'll open a clean PR

**Pull request closed without merging**
