### PR TITLE
Relax covering part check on mutation

### LINKED ISSUE #22013: Stress test: StorageReplicatedMergeTree: part is covered but should be mutated
```
2021.03.22 22:47:12.849794 [ 3039 ] {} <Error> test_25.concurrent_alter_mt_4: auto DB::StorageReplicatedMergeTree::processQueueEntry(ReplicatedMergeTreeQueue::SelectedEntryPtr)::(anonymous class)::operator()(DB::StorageReplicatedMergeTree::LogEntryPtr &) const: Code: 49, e.displayText() = DB::Exception: Part all_82_82_0 is covered by all_0_103_13_96 but should be mutated to all_82_82_0_83. This is a bug., Stack trace (when copying this message, always include the lines below):

0. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/exception:133: Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x1c5137c2 in /usr/bin/clickhouse
1. ./obj-x86_64-linux-gnu/../src/Common/Exception.cpp:56: DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xe8f01bd in /usr/bin/clickhouse
2. ./obj-x86_64-linux-gnu/../src/Storages/StorageReplicatedMergeTree.cpp:0: DB::StorageReplicatedMergeTree::tryExecutePartMutation(DB::ReplicatedMergeTreeLogEntry const&) @ 0x1aed23ec in /usr/bin/clickhouse
3. ./obj-x86_64-linux-gnu/../src/Storages/StorageReplicatedMergeTree.cpp:0: DB::StorageReplicatedMergeTree::executeLogEntry(DB::ReplicatedMergeTreeLogEntry&) @ 0x1aec07bf in /usr/bin/clickhouse
4. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/type_traits:3676: decltype(std::__1::forward<DB::StorageReplicatedMergeTree::processQueueEntry(std::__1::shared_ptr<DB::ReplicatedMergeTreeQueue::SelectedEntry>)::$_17&>(fp)(std::__1::forward<std::__1::shared_ptr<DB::ReplicatedMergeTreeLogEntry>&>(fp0))) std::__1::__invoke<DB::StorageReplicatedMergeTree::processQueueEntry(std::__1::shared_ptr<DB::ReplicatedMergeTreeQueue::SelectedEntry>)::$_17&, std::__1::shared_ptr<DB::ReplicatedMergeTreeLogEntry>&>(DB::StorageReplicatedMergeTree::processQueueEntry(std::__1::shared_ptr<DB::ReplicatedMergeTreeQueue::SelectedEntry>)::$_17&, std::__1::shared_ptr<DB::ReplicatedMergeTreeLogEntry>&) @ 0x1af4adb8 in /usr/bin/clickhouse
5. ./obj-x86_64-linux-gnu/../src/Storages/MergeTree/ReplicatedMergeTreeQueue.cpp:1385: DB::ReplicatedMergeTreeQueue::processEntry(std::__1::function<std::__1::shared_ptr<zkutil::ZooKeeper> ()>, std::__1::shared_ptr<DB::ReplicatedMergeTreeLogEntry>&, std::__1::function<bool (std::__1::shared_ptr<DB::ReplicatedMergeTreeLogEntry>&)>) @ 0x1b3a4b6c in /usr/bin/clickhouse
6. ./obj-x86_64-linux-gnu/../src/Storages/StorageReplicatedMergeTree.cpp:0: DB::StorageReplicatedMergeTree::processQueueEntry(std::__1::shared_ptr<DB::ReplicatedMergeTreeQueue::SelectedEntry>) @ 0x1af00d25 in /usr/bin/clickhouse
7. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/type_traits:3676: decltype(std::__1::forward<DB::StorageReplicatedMergeTree::getDataProcessingJob()::$_18&>(fp)()) std::__1::__invoke<DB::StorageReplicatedMergeTree::getDataProcessingJob()::$_18&>(DB::StorageReplicatedMergeTree::getDataProcessingJob()::$_18&) @ 0x1af4c205 in /usr/bin/clickhouse
8. ./obj-x86_64-linux-gnu/../src/Storages/MergeTree/BackgroundJobsExecutor.cpp:103: decltype(std::__1::forward<DB::IBackgroundJobExecutor::jobExecutingTask()::$_0&>(fp)()) std::__1::__invoke<DB::IBackgroundJobExecutor::jobExecutingTask()::$_0&>(DB::IBackgroundJobExecutor::jobExecutingTask()::$_0&) @ 0x1b0e0bec in /usr/bin/clickhouse
9. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/functional:2533: ThreadPoolImpl<ThreadFromGlobalPool>::worker(std::__1::__list_iterator<ThreadFromGlobalPool, void*>) @ 0xe94232f in /usr/bin/clickhouse
10. ./obj-x86_64-linux-gnu/../src/Common/ThreadPool.cpp:0: ThreadFromGlobalPool::ThreadFromGlobalPool<void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda1'()>(void&&, void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda1'()&&...)::'lambda'()::operator()() @ 0xe946598 in /usr/bin/clickhouse
11. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/functional:2533: ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xe9409df in /usr/bin/clickhouse
12. ./obj-x86_64-linux-gnu/../src/Common/ThreadPool.cpp:0: void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda1'()> >(void*) @ 0xe9446b6 in /usr/bin/clickhouse
13. start_thread @ 0x9609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
14. clone @ 0x122293 in /usr/lib/x86_64-linux-gnu/libc-2.31.so
 (version 21.4.1.6313)
 ```
 
 https://clickhouse-test-reports.s3.yandex.net/21895/b0284f20c3fed6d2d43da1fcc342fce2c5c55045/stress_test_(undefined).html#fail1

### PR DESCRIPTION
**Pull request by alesapin**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Now clickhouse will not throw `LOGICAL_ERROR` exception when we try to mutate the already covered part. Fixes #22013.

### CODE REVIEW

**Review by CurtizJ — APPROVED** [review]

**Comment by alesapin** [comment]
`01526_initial_query_id` not related but looks suspicious.

**Comment by alesapin** [comment]
```Coordination::Exception: No node, path: /clickhouse/tables/01108_restart_replicas_rename_deadlock_zookeeper_test_31/replica_01108_1/replicas/replica/metadata: Cannot attach table `test_31`.`replica_01108_1_tmp` from metadata file /var/lib/clickhouse/metadata/test_31/replica_01108_1_tmp.sql from query ATTACH TABLE test_31.replica_01108_1_tmp (`n` Int32) ENGINE = ReplicatedMergeTree('/clickhouse/tables/01108_restart_replicas_rename_deadlock_zookeeper_test_31/replica_01108_1', 'replica') ```

**Comment by alesapin** [comment]
> /clickhouse/tables/01108_restart_replicas_rename_deadlock_zookeeper_test_31/replica_01108_1/replicas/

Really looks like partially dropped table:
``$ ~/code/cpp/BuildCH/utils/keeper-data-dumper/keeper-data-dumper snapshots/ logs/ 2>/dev/null | grep '/clickhouse/tables/01108_restart_replicas_rename_deadlock_zookeeper_test_31'
/clickhouse/tables/01108_restart_replicas_rename_deadlock_zookeeper_test_31
/clickhouse/tables/01108_restart_replicas_rename_deadlock_zookeeper_test_31/replica_01108_1
/clickhouse/tables/01108_restart_replicas_rename_deadlock_zookeeper_test_31/replica_01108_1/metadata
/clickhouse/tables/01108_restart_replicas_rename_deadlock_zookeeper_test_31/replica_01108_1/nonincrement_block_numbers
/clickhouse/tables/01108_restart_replicas_rename_deadlock_zookeeper_test_31/replica_01108_1/temp
/clickhouse/tables/01108_restart_replicas_rename_deadlock_zookeeper_test_31/replica_01108_1/quorum
/clickhouse/tables/01108_restart_replicas_rename_deadlock_zookeeper_test_31/replica_01108_1/mutations
/clickhouse/tables/01108_restart_replicas_rename_deadlock_zookeeper_test_31/replica_01108_1/dropped
/clickhouse/tables/01108_restart_replicas_rename_deadlock_zookeeper_test_31/replica_01108_1/quorum/parallel
/clickhouse/tables/01108_restart_replicas_rename_deadlock_zookeeper_test_31/replica_01108_1/quorum/last_part
/clickhouse/tables/01108_restart_replicas_rename_deadlock_zookeeper_test_31/replica_01108_1/quorum/failed_parts
```

**Comment by alesapin** [comment]
> `` Coordination::Exception: No node, path: /clickhouse/tables/01108_restart_replicas_rename_deadlock_zookeeper_test_31/replica_01108_1/replicas/replica/metadata: Cannot attach table `test_31`.`replica_01108_1_tmp` from metadata file /var/lib/clickhouse/metadata/test_31/replica_01108_1_tmp.sql from query ATTACH TABLE test_31.replica_01108_1_tmp (`n` Int32) ENGINE = ReplicatedMergeTree('/clickhouse/tables/01108_restart_replicas_rename_deadlock_zookeeper_test_31/replica_01108_1', 'replica') ``

**Comment by alesapin** [comment]
Need to investigate.

**Comment by alesapin** [comment]
Known issue https://github.com/ClickHouse/ClickHouse/blob/1512ff832e86015b45394a28ebe6084ed2346397/src/Storages/StorageReplicatedMergeTree.cpp#L801-L803

**Pull request merged**
