### PR TITLE
Fix bug in removal of existing part directory

### PR DESCRIPTION
**Pull request by alesapin**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix bug in zero-copy replication which could lead to data loss after unsuccessful fetch operation retry.

### CODE REVIEW

**Comment by robot-clickhouse** [comment]
This is an automated comment for commit a3f9a8b87b8fc4332fd20c02780b50b005883ea2 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/49365/a3f9a8b87b8fc4332fd20c02780b50b005883ea2/ci_running.html)
The overall status of the commit is 🟢 success

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>Style Check</td><td>Runs a set of checks to keep the code style clean. If some of tests failed, see the related log from the report.</td><td>🟢 success</td></tr>
</table>

**Comment by alesapin** [comment]
Logical error reported https://github.com/ClickHouse/ClickHouse/issues/49386

**Comment by alesapin** [comment]
`test_merge_tree_s3/test.py::test_cache_with_full_disk_space[node_with_limited_disk]` -- flaky test

**Comment by alesapin** [comment]
`test_background_move` -- flaky test

**Pull request merged**
