### PR TITLE
Change PHP client names to <vendor/lib> format

### PR DESCRIPTION
**Pull request by simPod**
- change name format to help distinguish clients
- use packagist links that are more helpful for library consumers

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Documentation (changelog entry is not required)

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
Ok. Could you please also update other languages? (now the diff only contains `fa`).

**Comment by simPod** [comment]
@alexey-milovidov ok, I'll look into it. Do you want to do it in 1 MR? I'll have to explore each platform to provide best solution per each. I'm familiar with few of them.

**Comment by alexey-milovidov** [comment]
Sorry for confusion, I mean documentation languages like `en`, `zh`, `fa`...

**Comment by simPod** [comment]
oh!

**Comment by simPod** [comment]
I forgot there are more versions. Done

**Pull request merged**
