### PR TITLE
Rename support if exist 1

### PR DESCRIPTION
**Pull request by kafka1991**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):

- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

RENAME/EXCHANGE DATABASE/TABLE/DICTIONARY support IF EXISTS syntax, If this directive is used, one will not get an error if the DATABASE/TABLE/DICTIONARY to be renamed/exchanged doesn't exist.

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
Why not?

**Comment by kafka1991** [comment]
> Why not?

Reopen another pr due to the CLA，this can be closed.

**Comment by alexey-milovidov** [comment]
After CLA is signed this PR will be available for merging.

**Comment by alexey-milovidov** [comment]
Ah, ok.

**Pull request closed without merging**
