### PR TITLE
Fix SHOW MERGES

### PR DESCRIPTION
**Pull request by alexey-milovidov**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix SHOW MERGES remaining time

In previous versions, `SHOW MERGES` can output `-0` in the estimated remaining time field.

I've noticed minus zeros in the output of `SHOW MERGES` command. After investigation I figured out that the query is wrong (CC @den-crane), and it is also written in a very careless way: aliases are messed up, it is put on a few dense lines in the code, sometimes there are no whitespace after a comma, and sometimes aliases are specified without the `AS` keyword, and all of this is wildly inconsistent. Moreover, the `SHOW MERGES` query was stuffed into the `SHOW TABLES` interpreter :vomiting_face: (CC @den-crane).

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Review by thevar1able — APPROVED** [review]

**Comment by thevar1able** [comment]
AFAIR it could also show `progress > 1`.

**Comment by robot-ch-test-poll** [comment]
*This is an automated comment for commit c021f9dcd363d01d46108a9084b90c9463c9116a with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/66735/c021f9dcd363d01d46108a9084b90c9463c9116a/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/4b0ef8edce0eca049bcdb8938fd9aecb0e8c2377/docs_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Comment by alexey-milovidov** [comment]
Requires #66684

**Comment by alexey-milovidov** [comment]
GitHub is broken.

**Pull request merged**
