### PR TITLE
Add 'partitions' field for system.query_log

### PR DESCRIPTION
**Pull request by helifu**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
A new field 'partitions' is used to indicate which partitions are participating in the calculation.

### CODE REVIEW

**Comment by CheSema** [comment]
Lets add some test.

**Comment by robot-ch-test-poll3** [comment]
This is an automated comment for commit 8300e202ca66bb93b453ed27d73d0720c9169150 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/49779/8300e202ca66bb93b453ed27d73d0720c9169150/ci_running.html)
The overall status of the commit is 🔴 failure

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🔴 failure</td></tr>
</table>

**Comment by CheSema** [comment]
FYI:
`Error: Cannot run, PR description does not match the template: Changelog entry required for category 'Improvement'`
https://github.com/ClickHouse/ClickHouse/actions/runs/4947306968/jobs/8871204104?pr=49779

**Comment by helifu** [comment]
@CheSema Thanks for your reminds. The test case has been added and PR description has been update.

**Review by CheSema — APPROVED** [review]

**Comment by CheSema** [comment]
```
2023-05-23 11:58:15 -02751_query_log_test_partitions.3
2023-05-23 11:58:15 \ No newline at end of file
2023-05-23 11:58:15 +02751_query_log_test_partitions.3
```

**Pull request merged**
