### PR TITLE
Make `ColumnLowCardinality::getName()` consistent with other columns

### PR DESCRIPTION
**Pull request by taiyang-li**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by robot-ch-test-poll2** [comment]
*This is an automated comment for commit 94611dbddc08565c0ac154ad62dab1a7e8c6d8ed with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/67789/94611dbddc08565c0ac154ad62dab1a7e8c6d8ed/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Style check</td><td>Runs a set of checks to keep the code style clean. If some of tests failed, see the related log from the report</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/67789/94611dbddc08565c0ac154ad62dab1a7e8c6d8ed/style_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Review by rschu1ze — APPROVED** [review]

**Comment by rschu1ze** [comment]
Please merge again from master.

**Comment by rschu1ze** [comment]
@taiyang-li Could you please run SQL tests
- 02313_dump_column_structure_low_cardinality
- 02355_column_type_name_lc

and unit test
- IColumn.dumpStructure

locally? These tests failed in the private CI checks (the public checks did not run yet).

**Comment by taiyang-li** [comment]
> @taiyang-li Could you please run SQL tests
> 
> * 02313_dump_column_structure_low_cardinality
> * 02355_column_type_name_lc
> 
> and unit test
> 
> * IColumn.dumpStructure
> 
> locally? These tests failed in the private CI checks (the public checks did not run yet).

done

**Review by rschu1ze — APPROVED** [review]

**Comment by rschu1ze** [comment]
@taiyang-li Sorry for pinging again. Some of the checkboxes in CI Settings (Only check the boxes if you know what you are doing):` (PR message) were ticked. As a result, only some of the CI tests ran. However to be sure that nothing breaks, _all_ tests will need to run. I now un-ticked the boxes. Would you like to merge from `master` again? Thanks.

**Comment by rschu1ze** [comment]
@taiyang-li 02210_toColumnTypeName_toLowCardinality_const in FastTest is broken

**Comment by taiyang-li** [comment]
> @taiyang-li 02210_toColumnTypeName_toLowCardinality_const in FastTest is broken

done

**Comment by taiyang-li** [comment]
image

**Comment by rschu1ze** [comment]
@taiyang-li The issue in Cloud fork sync is unrelated and has been fixed in the meantime. Could you please merge once more from `master`? Thanks.

**Pull request merged**
