### PR TITLE
Fix fake race condition on system.merges merge_algorithm

### PR DESCRIPTION
**Pull request by alesapin**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
> test_materialize_mysql_database

- bad test, @zhang2014 @BohuTANG

**Comment by alesapin** [comment]
Waiting only for integration tests with thread sanitizer.

**Comment by zhang2014** [comment]
@alexey-milovidov It looks like the port is already in use. Maybe need to change the port(or it just coincidence)?
```
ERROR: for roottestmaterializemysqldatabase_mysql8_0_1  Cannot start service mysql8_0: driver failed programming external connectivity on endpoint roottestmaterializemysqldatabase_mysql8_0_1 (133260c51602e94b86fd20d9b5258a402b6f7408bc7a1740fb2a6232dc27f7f6): Error starting userland proxy: listen tcp 0.0.0.0:33308: bind: address already in use

ERROR: for mysql8_0  Cannot start service mysql8_0: driver failed programming external connectivity on endpoint roottestmaterializemysqldatabase_mysql8_0_1 (133260c51602e94b86fd20d9b5258a402b6f7408bc7a1740fb2a6232dc27f7f6): Error starting userland proxy: listen tcp 0.0.0.0:33308: bind: address already in use
Encountered errors while bringing up the project.
Removing orphan container "roottestmaterializemysqldatabase_node1_1"
Removing roottestmaterializemysqldatabase_mysql8_0_1 ... 
```

**Comment by alexey-milovidov** [comment]
@zhang2014 I don't know why port is already in use, maybe it is related to CLOSE/WAIT connections from previous tests?

**Pull request merged**
