### PR TITLE
Bump llvm to 16.x

### PR DESCRIPTION
**Pull request by rschu1ze**
I made an amateurish attempt to switch to the new pass manager based on [the tutorial](https://llvm.org/docs/NewPassManager.html#just-tell-me-how-to-run-the-default-optimization-pipeline-with-the-new-pass-manager). The legacy pass manager will be removed in LLVM >= 16. Chances are that something messes up.

The main benefit of this PR is that it enables the new libcxx.

Supersedes https://github.com/ClickHouse/ClickHouse/pull/66053 and https://github.com/ClickHouse/ClickHouse/pull/47783.

Necessary fixes in LLVM: https://github.com/ClickHouse/llvm-project/commits/ClickHouse/llvmorg-16.0.6
Necessary fixes in rocksdb: https://github.com/ClickHouse/rocksdb/commits/ClickHouse/v9.4.0/

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Bumped LLVM to 16 version. This is an internal dependency.

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Run only fuzzers related jobs (libFuzzer fuzzers, AST fuzzers, etc.)
- [ ]  Exclude: AST fuzzers
---
- [ ]  Do not test
- [x]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-ch-test-poll2** [comment]
*This is an automated comment for commit 7929a8bec0894ef3e1a243310dc8b3548c884a3c with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/69654/7929a8bec0894ef3e1a243310dc8b3548c884a3c/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/da993ad0a36a341b1baf771130601f903bbe5e24/docs_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Comment by zhanglistar** [comment]
@rschu1ze Do you still working on this? Thanks.

**Comment by rschu1ze** [comment]
Didn't work on this in the past two months and will likely not find time to continue in the next time.

**Comment by taiyang-li** [comment]
@rschu1ze do you plan to continue it ? I recently found I need it while implementing JIT for decimal types and expression.

**Comment by rschu1ze** [comment]
Perhaps I'll find somewhen between Christmas and New Year but this PR is not on my short-term TODO list.

**Comment by nikitamikhaylov** [comment]
There are several notable changes in performance:
Tests reports for ARM are here: [1](https://s3.amazonaws.com/clickhouse-test-reports/69654/7070c22a012710d6c7422063e346b19a52354cb7/performance_comparison__aarch64__[1_4]/report.html), [2](https://s3.amazonaws.com/clickhouse-test-reports/69654/7070c22a012710d6c7422063e346b19a52354cb7/performance_comparison__aarch64__[2_4]/report.html), [3](https://s3.amazonaws.com/clickhouse-test-reports/69654/7070c22a012710d6c7422063e346b19a52354cb7/performance_comparison__aarch64__[3_4]/report.html), [4](https://s3.amazonaws.com/clickhouse-test-reports/69654/7070c22a012710d6c7422063e346b19a52354cb7/performance_comparison__aarch64__[4_4]/report.html)
**Slowdowns**: jit_small_requests - 40%, int_parsing - 10%, and_function - 20%, float_formatting - 30%. 
**Speedups**:  vectorize_aggregation_combinators - 50%, rand - 50%, decimal_casts - 15%

Test reports for x86 are here: [1](https://s3.amazonaws.com/clickhouse-test-reports/69654/7070c22a012710d6c7422063e346b19a52354cb7/performance_comparison__release__[1_4]/report.html), [2](https://s3.amazonaws.com/clickhouse-test-reports/69654/7070c22a012710d6c7422063e346b19a52354cb7/performance_comparison__release__[2_4]/report.html), [3](https://s3.amazonaws.com/clickhouse-test-reports/69654/7070c22a012710d6c7422063e346b19a52354cb7/performance_comparison__release__[3_4]/report.html), [4](https://s3.amazonaws.com/clickhouse-test-reports/69654/7070c22a012710d6c7422063e346b19a52354cb7/performance_comparison__release__[4_4]/report.html)
**Slowdowns**: jit_large_requests - 80%, jit_small_requests - 50%. 

Looks like JIT's new infra is much more slow, but I guess this is Ok, because we have `compile_expressions` setting disabled by default. Not sure what to do and how to investigate other tests. I will also check LLVM-18 in another PR.

**Review by nikitamikhaylov — APPROVED** [review]

**Pull request merged**
