### PR TITLE
Remove broken lockless variant of re2

### PR DESCRIPTION
**Pull request by rschu1ze**
While looking into #54623, I noticed that the version of re2 with locking patched out (`re2_st`) unfortunately broke with #50949. The re2 version introduced with this PR switched from hand-written locking (re2/utils/mutex.h) to abseil's locking but the (super-hacky) re2_transform.cmake script that builds re2_st from re2 files was not adjusted accordingly.

This PR removes the re2_st variant. Reasons:
- neither re2 nor abseil have a build system option to omit locking. We would need to patch it out of abseil but that will be equally fragile and have an even bigger blast radius.
- nobody complained that regexp-related functionality slowed down after #54623. This includes performance tests which exist for `match()` and other regexp functions. Locking in re2 doesn't seem very relevant to performance.

(for funny reasons, clang started to complain about 0-as-NULL-ptr-constant in re2 headers, I had to add pragmas to make it compile)

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by robot-clickhouse-ci-2** [comment]
*This is an automated comment for commit 7b378dbad3a88cf90642d16c932d8ddf433a5e50 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/54642/7b378dbad3a88cf90642d16c932d8ddf433a5e50/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>✅ success</td></tr>
<tbody>
</table>
</details>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>⏳ pending</td></tr>
<tbody>
</table>

**Comment by rschu1ze** [comment]
Related: https://github.com/google/re2/issues/446

**Comment by alexey-milovidov** [comment]
There is a regression: https://pastila.nl/?01472c96/a60fd018ed6cbae724f1525bd0d012fa#9cGxeI59wUAdovGNJOKjlQ==
Is it related to locking or something else?

**Comment by alexey-milovidov** [comment]
I checked a few more times with various combinations, and found that the difference is not large. Ok to remove.

**Review by alexey-milovidov — APPROVED** [review]

**Comment by rschu1ze** [comment]
Thanks for double-checking!

**Pull request merged**
