### PR TITLE
Fix a mistake

### PR DESCRIPTION
**Pull request by helifu**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Collect the new processors correctly.

### CODE REVIEW

**Comment by nikitamikhaylov** [comment]
Which mistake?

**Comment by helifu** [comment]
> Which mistake?

`        QueryPipelineProcessorsCollector collector(delayed_pipeline, this);
        delayed_pipeline = QueryPipelineBuilder::unitePipelines(std::move(pipelines));
        processors = collector.detachProcessors();
`
In the original code above, `QueryPipelineBuilder::unitePipelines()` returns a new independent object `pipeline` and **assigns it to `delayed_pipeline`**. So the member `collected_processors` of `Pipe` in the `delayed_pipeline` is different from what is was before. Actually it is [`nullptr`](https://github.com/ClickHouse/ClickHouse/blob/e4f66b846912fa076b9fb5feaa4bc3b60d1db35d/src/QueryPipeline/QueryPipelineBuilder.cpp#L316C9-L316C9). Finally, the `detachProcessors()` can only return empty.
That's my understanding 🙄

**Comment by robot-clickhouse-ci-1** [comment]
*This is an automated comment for commit edc484d0bb92c42c6f0e732a5e98ac30e4a3ea40 with description of existing statuses. It's updated for the latest CI running*

[❌ Click here](https://s3.amazonaws.com/clickhouse-test-reports/57046/edc484d0bb92c42c6f0e732a5e98ac30e4a3ea40/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://github.com/ClickHouse/ClickHouse/blob/master/.github/PULL_REQUEST_TEMPLATE.md?plain=1">❌ failure</a></td></tr>
<tbody>
</table>

**Comment by alexey-milovidov** [comment]
@helifu, Tests have failed. Most likely, this PR introduces a mistake instead of fixing it.

**Pull request closed without merging**
