### PR TITLE
Try fix hung check 

### LINKED ISSUE #49714: Hung check failed because caches are too slow
https://s3.amazonaws.com/clickhouse-test-reports/0/3556c26075319fcb1315b6a7247f630715952be0/stress_test__debug_.html

Looks like a query got stuck: https://pastila.nl/?00f961e3/53ae35877693700435e63ef3960e3156

It's waiting for a mutex in `CacheBase`. Who holds the mutex? Let's try to find something suspicious in stacktraces of all thread from gdb. There's something:
```
Thread 1553 (Thread 0x7f07ccea7700 (LWP 15577)):
#0  DB::WriteBuffer::nextIfAtEnd (this=0x7f07cce94df8) at /build/src/IO/WriteBuffer.h:72
#1  0x000000001a3939d3 in DB::WriteBuffer::write (this=0x7f07cce94df8, from=0x10501750 "first non-downloaded offset: ", n=29) at /build/src/IO/WriteBuffer.h:87
#2  0x000000001a3938c5 in DB::writeString (data=0x10501750 "first non-downloaded offset: ", size=29, buf=...) at /build/src/IO/WriteHelpers.h:188
#3  0x000000001a39389a in DB::writeText (x=..., buf=...) at /build/src/IO/WriteHelpers.h:884
#4  0x0000000022f0aeee in DB::operator<< <char [30]> (buf=..., x=...) at /build/src/IO/Operators.h:46
#5  0x000000002be6061c in DB::FileSegment::getInfoForLogUnlocked (this=0x7f0ad1dc5118) at /build/src/Interpreters/Cache/FileSegment.cpp:698
#6  0x000000002be69608 in DB::FileSegment::getInfoForLog (this=0x7f0ad1dc5118) at /build/src/Interpreters/Cache/FileSegment.cpp:685
#7  0x000000002a69e3a6 in DB::CachedOnDiskReadBufferFromFile::nextImplStep (this=0x7f0adc945b98) at /build/src/Disks/IO/CachedOnDiskReadBufferFromFile.cpp:853
#8  0x000000002a69dd39 in DB::CachedOnDiskReadBufferFromFile::nextImpl (this=0x7f0adc945b98) at /build/src/Disks/IO/CachedOnDiskReadBufferFromFile.cpp:771
#9  0x000000001a392d7c in DB::ReadBuffer::next (this=0x7f0adc945b98) at /build/src/IO/ReadBuffer.h:70
#10 0x000000001ab3f784 in DB::ReadBuffer::eof (this=0x7f0adc945b98) at /build/src/IO/ReadBuffer.h:104
#11 DB::ReadBuffer::ignore (this=0x7f0adc945b98, n=180243) at /build/src/IO/ReadBuffer.h:117
#12 0x000000002a690da9 in DB::ReadBufferFromRemoteFSGather::readImpl (this=0x7f0b7975c000) at /build/src/Disks/IO/ReadBufferFromRemoteFSGather.cpp:189
#13 0x000000002a6905db in DB::ReadBufferFromRemoteFSGather::nextImpl (this=0x7f0b7975c000) at /build/src/Disks/IO/ReadBufferFromRemoteFSGather.cpp:151
#14 0x000000002a6904f8 in DB::ReadBufferFromRemoteFSGather::readInto (this=0x7f0b7975c000, data=0x5313bf2a7000 "", size=20277, offset=20277, ignore=712323) at /build/src/Disks/IO/ReadBufferFromRemoteFSGather.cpp:102
#15 0x000000002a6b73b0 in DB::AsynchronousReadIndirectBufferFromRemoteFS::nextImpl (this=0x7f09b155db00) at /build/src/Disks/IO/AsynchronousReadIndirectBufferFromRemoteFS.cpp:230
#16 0x000000001a392d7c in DB::ReadBuffer::next (this=0x7f09b155db00) at /build/src/IO/ReadBuffer.h:70
#17 0x000000002a2db832 in DB::ReadBuffer::eof (this=0x7f09b155db00) at /build/src/IO/ReadBuffer.h:104
#18 DB::CompressedReadBufferBase::readCompressedData (this=0x7f0a0db4ce80, size_decompressed=@0x7f07cce970d8: 0, size_compressed_without_checksum=@0x7f07cce970d0: 0, always_copy=false) at /build/src/Compression/CompressedReadBufferBase.cpp:159
#19 0x000000002cdc0000 in DB::CachedCompressedReadBuffer::nextImpl()::$_0::operator()() const (this=0x7f07cce973a8) at /build/src/Compression/CachedCompressedReadBuffer.cpp:52
#20 0x000000002cdbfd0f in DB::CacheBase<wide::integer<128ul, unsigned int>, DB::UncompressedCacheCell, UInt128TrivialHash, DB::UncompressedSizeWeightFunction>::getOrSet<DB::CachedCompressedReadBuffer::nextImpl()::$_0>(wide::integer<128ul, unsigned int> const&, DB::CachedCompressedReadBuffer::nextImpl()::$_0&&) (this=0x7f0c53623cd8, key=..., load_func=...) at /build/src/Common/CacheBase.h:148
#21 0x000000002cdbf669 in DB::UncompressedCache::getOrSet<DB::CachedCompressedReadBuffer::nextImpl()::$_0>(wide::integer<128ul, unsigned int> const&, DB::CachedCompressedReadBuffer::nextImpl()::$_0&&) (this=0x7f0c53623cd8, key=..., load=...) at /build/src/IO/UncompressedCache.h:67
```

So, the thread `15577` holds the mutex and is doing something in the filesystem cache. Let's check the log:
```
rg -Faz "[ 15577 ]" clickhouse-server.stress.log.zst  | tail
2023.05.09 09:52:34.135085 [ 15577 ] {92703eea-73f6-4535-bfaa-a68ff2ddf1a9} <Test> CachedOnDiskReadBufferFromFile(00170_test/uad/nhqsjykfslbocbcnbmulntdozdeaq): Key: 013ca1481c85d21530e8507c06c4834d. Returning with 1 bytes, buffer position: 563976 (offset: 0, predownloaded: 0), buffer available: 1, current range: [502667, 580237], file offset of buffer end: 563977, impl offset: 563977, file segment state: PARTIALLY DOWNLOADED NO CONTINUATION, current write offset: 502667, read_type: REMOTE_FS_READ_BYPASS_CACHE, reading until position: 752877, started with offset: 0, remaining ranges: [502667, 580237], [580238, 646827], [646828, 707724], [707725, 730616], [730617, 789111]
2023.05.09 09:52:34.135460 [ 15577 ] {92703eea-73f6-4535-bfaa-a68ff2ddf1a9} <Test> CachedOnDiskReadBufferFromFile(00170_test/uad/nhqsjykfslbocbcnbmulntdozdeaq): Current read type: REMOTE_FS_READ_BYPASS_CACHE, read offset: 563977, impl offset: 563977, file segment: File segment: [502667, 580237], key: 013ca1481c85d21530e8507c06c4834d, state: PARTIALLY_DOWNLOADED_NO_CONTINUATION, downloaded size: 0, reserved size: 0, downloader id: None, current write offset: 502667, first non-downloaded offset: 502667, caller id: 92703eea-73f6-4535-bfaa-a68ff2ddf1a9:15577, kind: Regular, unbound: 0
2023.05.09 09:52:34.135593 [ 15577 ] {92703eea-73f6-4535-bfaa-a68ff2ddf1a9} <Test> CachedOnDiskReadBufferFromFile(00170_test/uad/nhqsjykfslbocbcnbmulntdozdeaq): Read 1 bytes, read type REMOTE_FS_READ_BYPASS_CACHE, position: 563977, offset: 563978, segment end: 580237
2023.05.09 09:52:34.135822 [ 15577 ] {92703eea-73f6-4535-bfaa-a68ff2ddf1a9} <Test> CachedOnDiskReadBufferFromFile(00170_test/uad/nhqsjykfslbocbcnbmulntdozdeaq): Key: 013ca1481c85d21530e8507c06c4834d. Returning with 1 bytes, buffer position: 563977 (offset: 0, predownloaded: 0), buffer available: 1, current range: [502667, 580237], file offset of buffer end: 563978, impl offset: 563978, file segment state: PARTIALLY DOWNLOADED NO CONTINUATION, current write offset: 502667, read_type: REMOTE_FS_READ_BYPASS_CACHE, reading until position: 752877, started with offset: 0, remaining ranges: [502667, 580237], [580238, 646827], [646828, 707724], [707725, 730616], [730617, 789111]
2023.05.09 09:52:34.136194 [ 15577 ] {92703eea-73f6-4535-bfaa-a68ff2ddf1a9} <Test> CachedOnDiskReadBufferFromFile(00170_test/uad/nhqsjykfslbocbcnbmulntdozdeaq): Current read type: REMOTE_FS_READ_BYPASS_CACHE, read offset: 563978, impl offset: 563978, file segment: File segment: [502667, 580237], key: 013ca1481c85d21530e8507c06c4834d, state: PARTIALLY_DOWNLOADED_NO_CONTINUATION, downloaded size: 0, reserved size: 0, downloader id: None, current write offset: 502667, first non-downloaded offset: 502667, caller id: 92703eea-73f6-4535-bfaa-a68ff2ddf1a9:15577, kind: Regular, unbound: 0
2023.05.09 09:52:34.136342 [ 15577 ] {92703eea-73f6-4535-bfaa-a68ff2ddf1a9} <Test> CachedOnDiskReadBufferFromFile(00170_test/uad/nhqsjykfslbocbcnbmulntdozdeaq): Read 1 bytes, read type REMOTE_FS_READ_BYPASS_CACHE, position: 563978, offset: 563979, segment end: 580237
2023.05.09 09:52:34.136571 [ 15577 ] {92703eea-73f6-4535-bfaa-a68ff2ddf1a9} <Test> CachedOnDiskReadBufferFromFile(00170_test/uad/nhqsjykfslbocbcnbmulntdozdeaq): Key: 013ca1481c85d21530e8507c06c4834d. Returning with 1 bytes, buffer position: 563978 (offset: 0, predownloaded: 0), buffer available: 1, current range: [502667, 580237], file offset of buffer end: 563979, impl offset: 563979, file segment state: PARTIALLY DOWNLOADED NO CONTINUATION, current write offset: 502667, read_type: REMOTE_FS_READ_BYPASS_CACHE, reading until position: 752877, started with offset: 0, remaining ranges: [502667, 580237], [580238, 646827], [646828, 707724], [707725, 730616], [730617, 789111]
2023.05.09 09:52:34.136941 [ 15577 ] {92703eea-73f6-4535-bfaa-a68ff2ddf1a9} <Test> CachedOnDiskReadBufferFromFile(00170_test/uad/nhqsjykfslbocbcnbmulntdozdeaq): Current read type: REMOTE_FS_READ_BYPASS_CACHE, read offset: 563979, impl offset: 563979, file segment: File segment: [502667, 580237], key: 013ca1481c85d21530e8507c06c4834d, state: PARTIALLY_DOWNLOADED_NO_CONTINUATION, downloaded size: 0, reserved size: 0, downloader id: None, current write offset: 502667, first non-downloaded offset: 502667, caller id: 92703eea-73f6-4535-bfaa-a68ff2ddf1a9:15577, kind: Regular, unbound: 0
2023.05.09 09:52:34.137074 [ 15577 ] {92703eea-73f6-4535-bfaa-a68ff2ddf1a9} <Test> CachedOnDiskReadBufferFromFile(00170_test/uad/nhqsjykfslbocbcnbmulntdozdeaq): Read 1 bytes, read type REMOTE_FS_READ_BYPASS_CACHE, position: 563979, offset: 563980, segment end: 580237
2023.05.09 09:52:34.137302 [ 15577 ] {92703eea-73f6-4535-bfaa-a68ff2ddf1a9} <Test> CachedOnDiskReadBufferFromFile(00170_test/uad/nhqsjykfslbocbcnbmulntdozdeaq): Key: 013ca1481c85d21530e8507c06c4834d. Returning with 1 bytes, buffer position: 563979 (offset: 0, predownloaded: 0), buffer available: 1, current range: [502667, 580237], file offset of buffer end: 563980, impl offset: 563980, file segment state: PARTIALLY DOWNLOADED NO CONTINUATION, current write offset: 502667, read_type: REMOTE_FS_READ_BYPASS_CACHE, reading until position: 752877, started with offset: 0, remaining ranges: [502667, 580237], [580238, 646827], [646828, 707724], [707725, 730616], [730617, 789111]
```

```
rg -Faz "[ 15577 ]" clickhouse-server.stress.log.zst  | grep "Read 1 bytes" | wc
 485192 10189032 130748430
```

It started to fail at 2023-05-04 ([link](https://play.clickhouse.com/play?user=play#d2l0aCAKJyVIdW5nJScgYXMgbmFtZV9wYXR0ZXJuLAonJUZvdW5kIGh1bmcgcXVlcmllcyBpbiBwcm9jZXNzbGlzdCUnIGFzIGNvbnRleHRfcGF0dGVybiwKJzIwMjMtMDEtMDEnIGFzIHN0YXJ0X2RhdGUsCig0Njc5MykgYXMgbm9pc3lfcHJzLAooJ1N0YXRlbGVzcyB0ZXN0cyAoYXNhbiknLCAnU3RhdGVsZXNzIHRlc3RzIChhZGRyZXNzKScsICdTdGF0ZWxlc3MgdGVzdHMgKGFkZHJlc3MsIGFjdGlvbnMpJykgYXMgYmFja3BvcnRfYW5kX3JlbGVhc2Vfc3BlY2lmaWNfY2hlY2tzCnNlbGVjdCAKdG9TdGFydE9mRGF5KGNoZWNrX3N0YXJ0X3RpbWUpIGFzIGQsCmNvdW50KCksICBncm91cFVuaXFBcnJheShwdWxsX3JlcXVlc3RfbnVtYmVyKSwgYW55KHJlcG9ydF91cmwpCmZyb20gY2hlY2tzIHdoZXJlIHN0YXJ0X2RhdGUgPD0gY2hlY2tfc3RhcnRfdGltZSBhbmQgcHVsbF9yZXF1ZXN0X251bWJlciBub3QgaW4gCihzZWxlY3QgcHVsbF9yZXF1ZXN0X251bWJlciBhcyBwcm4gZnJvbSBjaGVja3Mgd2hlcmUgcHJuIT0wIGFuZCBzdGFydF9kYXRlIDw9IGNoZWNrX3N0YXJ0X3RpbWUgYW5kIGNoZWNrX25hbWUgaW4gYmFja3BvcnRfYW5kX3JlbGVhc2Vfc3BlY2lmaWNfY2hlY2tzKSAKYW5kIHRlc3RfbmFtZSBpbGlrZSBuYW1lX3BhdHRlcm4gYW5kICh0ZXN0X2NvbnRleHRfcmF3IGlsaWtlIGNvbnRleHRfcGF0dGVybikKYW5kIHB1bGxfcmVxdWVzdF9udW1iZXIgbm90IGluIG5vaXN5X3BycyAKYW5kIHRlc3Rfc3RhdHVzIGluICgnRkFJTCcsICdGTEFLWScsICdmYWlsdXJlJykgZ3JvdXAgYnkgZCBvcmRlciBieSBkIGRlc2M=)), probably introduced in https://github.com/ClickHouse/ClickHouse/pull/48791

### PR DESCRIPTION
**Pull request by kssenii**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Fix remote read buffer resizing itself constantly downwards in stress tests. (DRAFT because not fixed yet, cannot reproduce locally, so added more assertion and logging for now)
Closes https://github.com/ClickHouse/ClickHouse/issues/49714.

### CODE REVIEW

**Comment by tavplubix** [comment]
I guess it becomes 1 when we call `adjustBufferSize` with `file_size = 0`, shold we add an assertion there?

**Comment by tavplubix** [comment]
Hm, there's an interesting recent commit: https://github.com/ClickHouse/ClickHouse/commit/473f212c8264b902e02d4afec61712655daa2ba9#diff-46721cc7f7fb5c2b0bfb797d3f07e40359972722f11859b057e55285ef759d1d

cc: @al13n321

**Comment by kssenii** [comment]
> I guess it becomes 1 when we call adjustBufferSize with file_size = 0, shold we add an assertion there?

I saw in log that it was reading with buffer size 2 for a long time until it became 1, also with buffer size 6, 16, which is also not right.

**Comment by robot-clickhouse-ci-2** [comment]
This is an automated comment for commit 23a3e46f795583f4883709a9f9a0db32f700b9c8 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/49740/23a3e46f795583f4883709a9f9a0db32f700b9c8/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Pull request closed without merging**
