### PR TITLE
Do not implicitly read pk and version columns in lonely parts if unnecessary

### PR DESCRIPTION
**Pull request by canhld94**
### Changelog category (leave one):
- Performance Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
- Do not implicitly read pk and version columns in lonely parts if unnecessary

When query has `FINAL` but we enable `do_not_merge_across_partitions_select_final`, no need to implicitly read pk and version columns for lonely parts.

Implementation: construct two group of pipes

- merging pipes: with normal FINAL logic
- non-merging pipes: to read from lonely parts, will not implicitly read pk and version columns as well as computing sorting expression

Convert header if needed (final header is from non-merging pipes, if it's not empty) and unite all pipes

Inspired by #43296

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by canhld94** [comment]
cc @KochetovNicolai

**Comment by alexey-milovidov** [comment]
This is a huge improvement! I didn't expect we don't have it already :)

**Comment by robot-ch-test-poll3** [comment]
This is an automated comment for commit e9b0d3e4a2775bd3a9df5b167452e7971fcbc0ce with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/53919/e9b0d3e4a2775bd3a9df5b167452e7971fcbc0ce/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Comment by canhld94** [comment]
The stateless test is flaky because it rely on merges, will try to make it stable.
Performance test:
```
0.081 | 0.062 | -1.301x | -0.232 | 0.215 | parallel_final | 0 | SELECT count() FROM collapsing_final_16p_ord final
```
--> indeed this bring performance improvement (will be more clear if we set max_threads=1). Will add own performance test as well.

**Comment by canhld94** [comment]
cc @jorisgio

**Comment by canhld94** [comment]
@KochetovNicolai @alexey-milovidov pls help to review when you have time [THANKS]

**Comment by den-crane** [comment]
```
before

select max(a) from t final settings do_not_merge_across_partitions_select_final=1;
1 row in set. Elapsed: 1.912 sec. Processed 214.93 million rows, 5.48 GB (112.41 million rows/s., 2.86 GB/s.)
Peak memory usage: 1.11 MiB.

after

select max(a) from t final settings do_not_merge_across_partitions_select_final=1;
1 row in set. Elapsed: 0.535 sec. Processed 214.93 million rows, 1.72 GB (402.05 million rows/s., 3.22 GB/s.)
Peak memory usage: 266.12 KiB.
```

And `Peak memory usage` is beautiful.

**Pull request merged**
