### PR TITLE
Use the tuple element names as column names in `untuple()`

### PR DESCRIPTION
**Pull request by garcher22**
Function `untuple()` currently ignores the element names of named tuples and generates ugly result column names:

```sql
:) SELECT untuple(JSONExtract('{"key": "value"}', 'Tuple(key String)'));

┌─tupleElement(JSONExtract('{"key": "value"}', 'Tuple(key String)'), 1)─┐
│ value                                                                 │
└───────────────────────────────────────────────────────────────────────┘
```

Why would anyone want column names like this? And there's effectively no way to change these names when using `untuple()`. Let's respect the user intention and use the explicitly specified tuple element names (new behavior):

```sql
:) SELECT untuple(JSONExtract('{"key": "value"}', 'Tuple(key String)'));

┌─key───┐
│ value │
└───────┘
```

Interestingly, when the `untuple()` function itself has an alias, the result column names are already usable as of now but with an index as the column name instead of the element alias. This behavior is retained by this PR for backward compatibility:

```sql
:) SELECT untuple(JSONExtract('{"key": "value"}', 'Tuple(key String)')) a;

┌─a.1───┐
│ value │
└───────┘
```

When the element names are not specified, also keep the old behavior (ugly name):

```sql
:) SELECT untuple(JSONExtract('{"key": "value"}', 'Tuple(String)'));

┌─tupleElement(JSONExtract('{"key": "value"}', 'Tuple(String)'), 1)─┐
│ value                                                             │
└───────────────────────────────────────────────────────────────────┘
```

### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
When function "untuple()" is now called on a tuple with named elements and itself has an alias (e.g. "select untuple(tuple(1)::Tuple(element_alias Int)) AS untuple_alias"), then the result column name is now generated from the untuple alias and the tuple element alias (in the example: "untuple_alias.element_alias").

### CODE REVIEW

**Comment by UnamedRus** [comment]
It would be also great to fix `tupleToNameValuePairs ` back 
https://github.com/ClickHouse/ClickHouse/issues/36773

**Comment by alexey-milovidov** [comment]
This sounds dangerous - it previous led to a bug: https://github.com/ClickHouse/ClickHouse/pull/26179/files

**Comment by robot-clickhouse** [comment]
*This is an automated comment for commit 5150af28a9833ca4f3a975ec026b5b83c6c135ce with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/55123/5150af28a9833ca4f3a975ec026b5b83c6c135ce/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>✅ success</td></tr>
<tbody>
</table>
</details>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>⏳ pending</td></tr>
<tbody>
</table>

**Comment by amosbird** [comment]
I believe it's better to treat `untuple` as a JOIN variant, meaning it introduces another set of columns within the namespace of a table. We can enforce assigning an alias to `untuple`, similar to what we did when joining subqueries.

**Comment by alexey-milovidov** [comment]
It will be nice to support `tuple.*` with Analyzer.

**Comment by Felixoid** [comment]
> Here's a link to one of the runs: https://github.com/garcher22/ClickHouse/actions/runs/6356562956

Yes, it's your branch. The workflows are enabled automatically on new yaml files. It's questionable behavior, but it should be addressed to github itself

**Review by rschu1ze — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
Ok. Currently, the tests didn't pass. We can continue or close.

**Comment by rschu1ze** [comment]
ClickHouse Integration Tests (release) [2/4]: #52554
ClickHouse Stress Test (msan): #55148

**Comment by alexey-milovidov** [comment]
@rschu1ze, Doesn't it break query analysis?
I remember that last time I removed the `untuple` function because it was impossible for it to work correctly.

> ClickHouse Stress Test (msan)

Are you 100% sure it is not related to this pull request?

**Comment by alexey-milovidov** [comment]
@rschu1ze even if the memory sanitizer issue is not related to this pull request, its existence means that currently our repository is in a non-acceptable state, and nothing should be done other than fixing it.

**Comment by rschu1ze** [comment]
> @rschu1ze, Doesn't it break query analysis?
> I remember that last time I removed the untuple function because it was impossible for it to work correctly.

I extended the tests (#55425) and I am pretty sure that this particular PR does not add new problems. There is however a problem with untuple() and the analyzer in general which existed before this PR already, I opened #55426. If the problem cannot be fixed easily, then I'd be okay with removing untuple - the same can be achieved with sub-index access (`tuple.1`) syntax.

**Pull request merged**
