### PR TITLE
fix dictionary reload bug

### PR DESCRIPTION
**Pull request by lthaooo**
### Changelog category (leave one):

- Bug Fix (user-visible misbehaviour in official stable or prestable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix dictionary reload for `ClickHouseDictionarySource` if it contains scalar subqueries.

### CODE REVIEW

**Comment by kitaisreal** [comment]
@Mergifyio update

**Comment by kitaisreal** [comment]
@lthaooo Pull request looks good, could you please also add test ?

**Comment by lthaooo** [comment]
> @lthaooo Pull request looks good, could you please also add test ?

ok, i will add test later

**Comment by lthaooo** [comment]
> @lthaooo Pull request looks good, could you please also add test ?

done. The test case will failed without this PR

**Pull request merged**
