### PR TITLE
Bump gRPC to v1.55.4 and protobuf to v22.5

### PR DESCRIPTION
**Pull request by rschu1ze**
See #56543

(this PR will accumulate multiple version bumps, cf. https://github.com/ClickHouse/ClickHouse/pull/56059#pullrequestreview-1701362162 EDIT: No, it won't as v1.55.4 required some major changes)

Bumped gRPC to v1.55.4, this was only possible by also bumping protobuf to v22.5

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by robot-clickhouse-ci-1** [comment]
*This is an automated comment for commit 8871f8243043a2c0bdca4427769e65fe51714bfd with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/56664/8871f8243043a2c0bdca4427769e65fe51714bfd/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td><a href="https://github.com/ClickHouse/ClickHouse/actions/runs/6848811095">✅ success</a></td></tr>
<tbody>
</table>
</details>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/56664/8871f8243043a2c0bdca4427769e65fe51714bfd/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Comment by mkmkme** [comment]
Is my understanding correct that those versions do not yet require updating `proto` file to use editions?

**Comment by rschu1ze** [comment]
Editions are introduced only with [protobuf v25](https://github.com/protocolbuffers/protobuf/releases).

**Comment by rschu1ze** [comment]
Note to myself: need to remove the systemd dependency (#56671)

**Comment by mkmkme** [comment]
>Editions are introduced only with [protobuf v25](https://github.com/protocolbuffers/protobuf/releases).

Noted. Is there still a need for updating protobuf and gRPC to the latest and update the `proto` file (as discussed [in Slack](https://clickhousedb.slack.com/archives/CUDSPUJ68/p1698069049049369?thread_ts=1697532903.086469&cid=CUDSPUJ68)?

**Comment by rschu1ze** [comment]
> Noted. Is there still a need for updating protobuf and gRPC to the latest and update the `proto` file (as discussed [in Slack](https://clickhousedb.slack.com/archives/CUDSPUJ68/p1698069049049369?thread_ts=1697532903.086469&cid=CUDSPUJ68))?

@mkmkme Eventually yes, but in a future PR. gRPC and protobuf are quite hairy and can only be upgraded in "lockstep" (I believe this was also your experience). I have been trying to upgrade both but it is a slow process. Even with this PR, both are behind their current upstream versions. "Editions" are introduced with the latest and greatest protobuf that (I speculate) can be introduced in two weeks at the earliest with the current pace. I can continue the upgrade process, and in case I have questions I may come back to you.

**Comment by rschu1ze** [comment]
@Algunenano I'd appreciate if you could take a look + possibly approve, thanks.

**Review by Algunenano — APPROVED** [review]
LGTM.

There is a cmake warning for grpc but I don't know if it was introduced in this PR or one of the prior ones:
```
-- Adding contrib module grpc (configuring with grpc-cmake)
CMake Warning (dev) at contrib/grpc/CMakeLists.txt:50 (option):
  Policy CMP0077 is not set: option() honors normal variables.  Run "cmake
  --help-policy CMP0077" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  For compatibility with older versions of CMake, option is clearing the
  normal variable 'gRPC_BUILD_CSHARP_EXT'.
This warning is for project developers.  Use -Wno-dev to suppress it.
```

**Comment by rschu1ze** [comment]
Thanks. The warning technically existed already before this PR but more likely it was introduced with one of my many earlier gRPC updates. I'll check if I can get rid of it.

**Pull request merged**
