### PR TITLE
Make clickhouse-diagnostics also work for altinity release

### PR DESCRIPTION
**Pull request by ramazanpolat**
Because altinity release has `altinitystable` at the end of version number, `parse_version` function throws parse error.

Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by kitaisreal** [comment]
@ramazanpolat it is not bug fix, probably it is `Not for changelog`.

**Comment by kitaisreal** [comment]
@Mergifyio update

**Comment by kitaisreal** [comment]
@Mergifyio update

**Comment by alexey-milovidov** [comment]
If someone is applying a sticker on top of our release, that does not make it better. Exactly the opposite - the binary code will be different, so you cannot trust it and developers cannot support it.

Nevertheless, let's be generous and merge this change.

**Comment by ramazanpolat** [comment]
> @ramazanpolat it is not bug fix, probably it is `Not for changelog`.

I know but I couldn't remove the `pr-bugfix` label. In fact, I wasn't even aware of a labeling bot.

> If someone is applying a sticker on top of our release, that does not make it better. Exactly the opposite - the binary code will be different, so you cannot trust it and developers cannot support it.
> 
> Nevertheless, let's be generous and merge this change.

@alexey-milovidov When I've noticed that you've edited my previous PR #34072, I thought I should do the same and pick the most proper option, which that time looked like a bugfix would be a good fit. I assume the bot will put my name on the changelog, which I wasn't aware of it. I had no intention to put my name on the changelog for a one-line code contribution. Sorry for inconvinience.

**Comment by alex-zaitsev** [comment]
Thank you, @alexey-milovidov . The point of a sticker is to distinguish between a community and Altinity builds, because the binary code is different. We could do it without a sticker and mimic the community release completely, but it would be more confusing. Also, sometimes Altinity builds contain backports that do not exist in community ones.

**Pull request merged**
