### PR TITLE
Prevent incompatible ALTER of projection columns

### LINKED ISSUE #56932: Altering column that is part of a projection may lead to loosing data
```sql
CREATE TABLE users (uid Int16, name String, age Nullable(Int8),
  projection p1 (select age, count() group by age)
  ) ENGINE=MergeTree order by uid;

INSERT INTO users VALUES (1231, 'John', 11);
INSERT INTO users VALUES (6666, 'Ksenia', 1);
INSERT INTO users VALUES (8888, 'Alice', 1);
INSERT INTO users VALUES (6667, 'Ksenia', null);

alter table users modify column age Nullable(Int32) ;
DB::Exception: Exception happened during execution of mutation 'mutation_5.txt' with part 'all_2_2_0' reas

select count() from users;
┌─count()─┐
│       4 │
└─────────┘

detach table users;

attach table users;

select count() from users;
┌─count()─┐
│       1 │
└─────────┘
```

### PR DESCRIPTION
**Pull request by amosbird**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Now ALTER columns which are incompatible with columns used in some projections will be forbidden. Previously it could result in incorrect data. This fixes #56932. This PR also allows RENAME of index columns, and improves the exception message by providing clear information on the affected indices or projections causing the prevention.

### CODE REVIEW

**Comment by robot-ch-test-poll2** [comment]
*This is an automated comment for commit eae9392c67dbd1e2b0fa937c4667db642b29027c with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/56948/eae9392c67dbd1e2b0fa937c4667db642b29027c/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td><a href="https://github.com/ClickHouse/ClickHouse/actions/runs/6912688468">✅ success</a></td></tr>
<tbody>
</table>
</details>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/56948/eae9392c67dbd1e2b0fa937c4667db642b29027c/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Comment by den-crane** [comment]
I would add a test for measurements as well  https://fiddle.clickhouse.com/14015844-26a7-4dcf-864d-6624398bbda6

**Comment by amosbird** [comment]
It seems we should recalculate projections instead of preventing it. Because there are use cases that relies on `*` projections:

`CREATE TABLE x (col1 Int64, col2 Int64, PROJECTION 02691_drop_column_replicated (SELECT * ORDER BY col1 ))`

which will adapt to metadata changes.

**Comment by amosbird** [comment]
> I would add a test for measurements as well https://fiddle.clickhouse.com/14015844-26a7-4dcf-864d-6624398bbda6

We should also allow compatible metadata ALTERs.

**Review by KochetovNicolai — APPROVED** [review]

**Comment by amosbird** [comment]
> 01280_ttl_where_group_by

```
 ❯ curl "https://play.clickhouse.com?user=play" -d "select toStartOfHour(check_start_time) as d,count(),  groupUniqArray(pull_request_number),  any(report_url) from checks where '2022-06-01' <= check_start_time and test_name like '%01280_ttl_where_group_by%' and test_status in ('FAIL', 'FLAKY') group by d order by d desc"
2023-11-27 15:00:00     1       [57231] https://s3.amazonaws.com/clickhouse-test-reports/57231/96a445d3ac3e9547998ea80d2f29829a4986d426/stateless_tests__debug__s3_storage__[3_6].html
2023-11-26 06:00:00     1       [57205] https://s3.amazonaws.com/clickhouse-test-reports/57205/6b46070e0281c15d97c7918150d3c9f4a5bc0a8a/stateless_tests__debug__s3_storage__[3_6].html
2023-11-26 05:00:00     2       [0,57218]       https://s3.amazonaws.com/clickhouse-test-reports/0/1cc33f34303e6508cc9d63093bafb4585d833158/stateless_tests__tsan__[2_5].html
2023-11-26 02:00:00     1       [56724] https://s3.amazonaws.com/clickhouse-test-reports/56724/92e580997c5fbd436f829de62d7073504380986a/stateless_tests__debug__s3_storage__[3_6].html
2023-11-25 22:00:00     1       [0]     https://s3.amazonaws.com/clickhouse-test-reports/0/4088ec0eacc72867f943ad3a240c134a46fcd63c/stateless_tests__msan__[3_6].html
2023-11-25 19:00:00     1       [57220] https://s3.amazonaws.com/clickhouse-test-reports/57220/c2367016140e9035b21262a137b1e44228565543/stateless_tests__debug__s3_storage__[3_6].html
2023-11-25 14:00:00     2       [0,57003]       https://s3.amazonaws.com/clickhouse-test-reports/0/2e7f314599533b95627cca98608e78cc7b0bbedc/stateless_tests__debug__[2_5].html
2023-11-24 22:00:00     1       [57209] https://s3.amazonaws.com/clickhouse-test-reports/57209/1b623b0e48251303881fd4e56e50021112cf0811/stateless_tests__msan__[3_6].html
2023-11-24 20:00:00     2       [0,56383]       https://s3.amazonaws.com/clickhouse-test-reports/56383/791c01d666b50efa7090da9e5651cd3cc76b9e26/stateless_tests__tsan__s3_storage__[2_5].html
2023-11-24 19:00:00     4       [56864,56342,57076]     https://s3.amazonaws.com/clickhouse-test-reports/57076/0f7b5ebd68d44f1789a9186082a9e8fdfa906b34/stateless_tests__tsan__s3_storage__[2_5].html
2023-11-24 18:00:00     5       [57122,56269,57202,51858,57198] https://s3.amazonaws.com/clickhouse-test-reports/57122/dfba02542dc44ab1e70c81bea0b97cd12ef68c83/stateless_tests__debug__s3_storage__[3_6].
```

> 01280_ttl_where_group_by

Known flaky test:

```
 ❯ curl "https://play.clickhouse.com?user=play" -d "select toStartOfHour(check_start_time) as d,count(),  groupUniqArray(pull_request_number),  any(report_url) from checks where '2022-06-01' <= check_start_time and test_name like '%01732_race_condition_storage_join_long%' and test_status in ('FAIL', 'FLAKY') group by d order by d desc"
2023-11-28 10:00:00     1       [57299] https://s3.amazonaws.com/clickhouse-test-reports/57299/889c53eca013f1280ba9b442a98101201074ef00/stateless_tests__tsan__s3_storage__[5_5].html
2023-11-25 20:00:00     1       [49351] https://s3.amazonaws.com/clickhouse-test-reports/49351/6937c0de19e50708445e1a818c3560a92eb2b5d3/stateless_tests__tsan__s3_storage__[5_5].html
2023-11-22 07:00:00     1       [56079] https://s3.amazonaws.com/clickhouse-test-reports/56079/1e0b4f979c90564159f9cd10acfb310ba71c1e79/stateless_tests__tsan__s3_storage__[5_5].html
2023-11-21 12:00:00     1       [57034] https://s3.amazonaws.com/clickhouse-test-reports/57034/fd792a80230c954393bd4720cf46e041d535deef/stateless_tests__tsan__s3_storage__[5_5].html
2023-11-21 10:00:00     1       [57033] https://s3.amazonaws.com/clickhouse-test-reports/57033/f996dac75d017c3c3340b74073288df263feead0/stateless_tests__tsan__s3_storage__[5_5].html
2023-11-21 08:00:00     1       [56948] https://s3.amazonaws.com/clickhouse-test-reports/56948/ee1cec4d38bad32de6dbf0f4c37c99c64a1dffed/stateless_tests__tsan__s3_storage__[5_5].html
2023-11-17 18:00:00     1       [56897] https://s3.amazonaws.com/clickhouse-test-reports/56897/bedec05cccb35938cc0d82e98f59381db90ae5c7/stateless_tests__tsan__s3_storage__[5_5].html
2023-11-17 17:00:00     1       [56619] https://s3.amazonaws.com/clickhouse-test-reports/56619/4d5becb4deff91f4e9675624175f2207ea2d9ccf/stateless_tests__tsan__[5_5].html
2023-11-16 21:00:00     1       [56865] https://s3.amazonaws.com/clickhouse-test-reports/56865/7497495f05beb22c871045b500a8c4ed9e788fda/stateless_tests__tsan__s3_storage__[5_5].html
2023-11-15 12:00:00     1       [56304] https://s3.amazonaws.com/clickhouse-test-reports/56304/12a8a38d3592f92d9c86725a1fea25355478f2e4/stateless_tests__tsan__s3_storage__[5_5].html
2023-11-13 09:00:00     1       [56641] https://s3.amazonaws.com/clickhouse-test-reports/56641/6add71bd414340532a0769b2c16a1ac98aba3d5a/stateless_tests__tsan__s3_storage__[5_5].html
2023-11-11 09:00:00     1       [56485] https://s3.amazonaws.com/clickhouse-test-reports/56485/90f16d67ac63c7e2780027f43866a959ba8fe652/stateless_tests__tsan__s3_storage__[5_5].html
2023-11-06 23:00:00     2       [56394,39507]   https://s3.amazonaws.com/clickhouse-test-reports/39507/e2ca5ae1f711e8cfb8e09715a9d30e5945b5cdbb/stateless_tests__tsan__s3_storage__[5_5].html
```

> test_postgres_schema

https://github.com/ClickHouse/ClickHouse/issues/56627

> test_storage_rabbitmq/test.py::test_row_based_formats	

https://github.com/ClickHouse/ClickHouse/issues/56866

> test_system_clusters_actual_information/test.py::test

Same as above. https://github.com/ClickHouse/ClickHouse/issues/56866

**Comment by evillique** [comment]
Tests:
- Stateless tests (release, s3 storage) [2/2]: https://github.com/ClickHouse/ClickHouse/issues/57444

**Pull request merged**
