### PR TITLE
Mark coordinator Heartbeat request as read to avoid batching

### PR DESCRIPTION
**Pull request by azat**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in official stable or prestable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Mark coordinator Heartbeat request as read to avoid batching

Before you may seen such test messages in the log:

    2023.02.16 21:38:39.012787 [ 15186 ] {} <Test> virtual Coordination::ZooKeeperRequest::~ZooKeeperRequest(): Processing of request xid=-2 took 10000 ms

On a completelly idle server, the reason is that Heartbeat had been batched, and the limit in ~ZooKeeperRequest is 1sec, while operation_timeout_ms default is 10sec.

Cc: @alesapin 
Cc: @antonio2368

_Note: marked as `Bug fix` since looks like it is better to backport it, to avoid extra latency for heartbeats_

### CODE REVIEW

**Comment by antonio2368** [comment]
> to avoid batching

What batching?

**Comment by azat** [comment]
>What batching?

`max_requests_quick_batch_size` (default 10)

https://github.com/ClickHouse/ClickHouse/blob/8cd967446ca3bafb36cc08a3b4559a98b36de310/src/Coordination/KeeperDispatcher.cpp#L105-L121

>Also, it's interesting too see how does ZK handle heartbeats - as write or as read request. If it's write we should leave it as is and see how to avoid that problem differently

ZooKeeper don't have such batching AFAICS, and if we are talking about PING (heartbeat), then AFAICS it is done in place:

https://github.com/apache/zookeeper/blob/2e9c3f3ceda90aeb9380acc87b253bf7661b7794/zookeeper-server/src/main/java/org/apache/zookeeper/server/FinalRequestProcessor.java#L214-L220

There is some batching added in https://github.com/apache/zookeeper/pull/905/files

But it does not batch ping requests anyway:

https://github.com/apache/zookeeper/blob/2e9c3f3ceda90aeb9380acc87b253bf7661b7794/zookeeper-server/src/main/java/org/apache/zookeeper/server/quorum/CommitProcessor.java#L169-L194

And batching ping does not sounds right anyway to me.

**Comment by antonio2368** [comment]
> On a completelly idle server, the reason is that Heartbeat had been batched

So this batching will try to batch requests that are already in queue with 10 requests at most so it should have minimal effect on latency (it doesn't wait for anything).
If the server is idle it means it sending just a heartbeat so it doesn't even have anything to batch, in this case it will process it by itself and that's it. It doesn't even have any contention on the RequestQueue mutex.

Can you send me some examples of such problem in stress tests?

BUT having said all that, it seems like ZK is really handling heartbeat as a read request so I think this change is alright.

**Comment by azat** [comment]
>If the server is idle it means it's sending just a heartbeat so it doesn't even have anything to batch, in this case it will process it by itself and that's it. It doesn't even have any contention on the RequestQueue mutex.

The problem here is that server does not respond for writes immediately, here

https://github.com/ClickHouse/ClickHouse/blob/8cd967446ca3bafb36cc08a3b4559a98b36de310/src/Coordination/KeeperDispatcher.cpp#L140-L141

>Can you send me some examples of such problem in stress tests?

This wasn't from stress tests, I was simply started `clickhouse-server` with builtin keeper and always getting this noisy messages, on a completely idle server.

Thought let me look at stress tests from some [other PR](https://s3.amazonaws.com/clickhouse-test-reports/46499/61f27c9dabe4a204c60822a4fb11d5591c9f8609/stress_test__debug_.html):

```
$ zstd -cdq clickhouse-server.stress.log.zst | fgrep 'virtual Coordination::ZooKeeperRequest::~ZooKeeperRequest(): Processing of request xid=-2 took 10000 ms'  -c
69
```

And from this PR:

```
$ zstd -cdq clickhouse-server.stress.log.zst | fgrep 'virtual Coordination::ZooKeeperRequest::~ZooKeeperRequest(): Processing of request xid=-2 took 10000 ms'  -c
0
```

**Comment by antonio2368** [comment]
I think that's simply the RAFT overhead vs simply pinging a server and sending response instantly, and not the result of batching.

In any case, I'm okay with making heartbeat a read request.

**Comment by antonio2368** [comment]
seems some tests failed, possibly related

**Comment by azat** [comment]
Something really odd happened:

```
test_keeper_force_recovery/test.py:51: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <helpers.cluster.ClickHouseCluster object at 0x7fb4cdc3a6a0>, kill = True
ignore_fatal = True

    def shutdown(self, kill=True, ignore_fatal=True):
        sanitizer_assert_instance = None
        fatal_log = None
    
        if self.up_called:
>           with open(self.docker_logs_path, "w+") as f:
E           FileNotFoundError: [Errno 2] No such file or directory: '/ClickHouse/tests/integration/test_keeper_force_recovery/_instances_0/docker.log'
```

So by some reason docker did not start the container, though I don't see any errors in `dockerd.log`

**Comment by robot-ch-test-poll** [comment]
This is an automated comment for commit ce9aee1f11676eac5fd4b9228f09fbf442eb36f9 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/46500/ce9aee1f11676eac5fd4b9228f09fbf442eb36f9/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Comment by azat** [comment]
So, this is ~~funny~~ interesting, the problem is that when Heartbeat request considered as write request it went through the quorum, however after it became the read request it can be handled locally. And I thought that this should be great! However, the problem is how keeper handle dead sessions, they are handled on the leader, but after Heartbeat became read request and if server connected to the follower then Heartbeat will not be received by the leader and it will close the connection as a dead session.

```
(follower) 2023.07.14 08:28:45.099323 [ 9 ] {} <Trace> KeeperTCPHandler: Received heartbeat for session #2
(leader) 2023.07.14 08:28:46.045696 [ 84 ] {} <Information> KeeperDispatcher: Found dead session 2, will try to close it
(leader) 2023.07.14 08:28:46.045700 [ 84 ] {} <Information> KeeperDispatcher: Dead session close request pushed
(follower) 2023.07.14 08:28:46.047819 [ 9 ] {} <Debug> KeeperTCPHandler: Session #2 successfully closed (xid: 2147483647, op_num: Close)
```

But I guess this has been "automatically fixed" by the cd471e9c618b1, since after it there is no batching if the queue is empty.

But the whole idea that Heartbeat goes through the quorum looks odd to me. Any reasons for this?

**Pull request closed without merging**
