### PR TITLE
Don't merge just created aggregating projection blocks

### PR DESCRIPTION
**Pull request by nickitat**
### Changelog category (leave one):
- Performance Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Skip merging of newly created projection blocks during `INSERT`-s.

### CODE REVIEW

**Comment by robot-ch-test-poll** [comment]
*This is an automated comment for commit 284a0eb5e385a0263520115a21fc7b0ee272ef17 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/59405/284a0eb5e385a0263520115a21fc7b0ee272ef17/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/59405/284a0eb5e385a0263520115a21fc7b0ee272ef17/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Comment by nickitat** [comment]
Looks like in some cases we call `merge()` inside `writeProjectionPart()` on a block that was just obtained from `projection.calculate()` and it should be redundant. Maybe I just missing smth.

**Comment by nickitat** [comment]
Looks like in some cases we call `merge()` inside `writeProjectionPart()` on a block that was just obtained from `projection.calculate()` and it should be redundant. Cause we would just do `AggregatingSorted` by group by key from group by output block.
But maybe I just miss smth. @amosbird could you pls comment on that

**Comment by amosbird** [comment]
IIRC, `projection.calculate()` runs till `WithMergeableState` which might not fully merge the output block. See https://github.com/ClickHouse/ClickHouse/issues/31669

**Comment by nickitat** [comment]
yes, and we have two different methods for insert and for mutations afaiu. and for materialise we'll still pass the flag to perform merge:

https://github.com/nickitat/ClickHouse/blob/dont_merge_just_created_aggr_projection_block/src/Storages/MergeTree/MergeTreeDataWriter.cpp#L732-L757

I tested the query from denny for plain insert, it also seems to work fine:

``` sql
CREATE TABLE z
(
    `pk` Int64,
    `d` Date,
    `id` UInt64,
    `c` UInt64,
    PROJECTION pp
    (
        SELECT
            id,
            sum(c)
        GROUP BY id
    )
)
ENGINE = MergeTree
PARTITION BY d
ORDER BY pk;


INSERT INTO z SELECT
    number,
    today() + 1,
    intDiv(number, 1000000),
    1
FROM numbers(100000000);


SELECT
    database,
    table,
    name,
    partition,
    formatReadableSize(sum(data_compressed_bytes) AS size) AS compressed,
    formatReadableSize(sum(data_uncompressed_bytes) AS usize) AS uncompressed,
    round(usize / size, 2) AS compr_rate,
    sum(rows) AS rows,
    count() AS part_count
FROM system.projection_parts
WHERE (table = 'z') AND active
GROUP BY
    database,
    table,
    name,
    partition
ORDER BY size DESC


┌─database─┬─table─┬─name─┬─partition──┬─compressed─┬─uncompressed─┬─compr_rate─┬─rows─┬─part_count─┐
│ default  │ z     │ pp   │ 2024-02-01 │ 909.00 B   │ 1.64 KiB     │       1.85 │  105 │          6 │
└──────────┴───────┴──────┴────────────┴────────────┴──────────────┴────────────┴──────┴────────────┘
```

**Comment by amosbird** [comment]
> and for materialise we'll still pass the flag to perform merge:

Ah, I see. I think it's reasonable.

**Comment by den-crane** [comment]
* https://github.com/ClickHouse/ClickHouse/issues/31669

BTW, that issue was about `materialize projection pp`, insert and merge were fine.

**Pull request merged**
