### PR TITLE
increase background_fetches_pool_size to 16, background_schedule_pool_size to 512

### PR DESCRIPTION
**Pull request by den-crane**
As a support engineer I observe a lot of cases when the replication queue piles up with replication tasks because there are a lot of small inserts in the system and replication fetcher is unable to keep up (because of network latency or keeper overhead or pool overhead), large fetches (of merged parts) are blocked by the fetching new small parts and replication lag grows indefinitely in this case. Increasing background_fetches_pool_size to 16, background_schedule_pool_size to 512 solves this. And no major harm of these settings for small systems.

### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Set `background_fetches_pool_size` to 16, background_schedule_pool_size to 512 that is better for production usage with frequent small insertions.

### CODE REVIEW

**Comment by robot-ch-test-poll2** [comment]
This is an automated comment for commit e1bc6cb0a702cf8f7aed19fa3a78d221ae6c6702 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/54327/e1bc6cb0a702cf8f7aed19fa3a78d221ae6c6702/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
A test for "zero-copy replication" has failed.

**Comment by alexey-milovidov** [comment]
@den-crane tests have failed.

**Comment by den-crane** [comment]
> @den-crane tests have failed.

I don't think failures are related. Let's test again.

**Comment by alexey-milovidov** [comment]
There is a failure in the `disk_types` test that requires investigation.

**Comment by alexey-milovidov** [comment]
Tests have failed.

**Comment by alexey-milovidov** [comment]
Interesting, why the tests have failed?

**Comment by alexey-milovidov** [comment]
@den-crane tests have failed.

**Comment by alexey-milovidov** [comment]
Tests have failed.

**Comment by alexey-milovidov** [comment]
@den-crane, tests have failed.

**Comment by alexey-milovidov** [comment]
Something with `test_disk_types` that we have to figure out.

**Pull request merged**
