### PR TITLE
Fix date_diff() for hour/minute on macOS

### LINKED ISSUE #42742: date_diff function returns wrong result when unit=hour or minute
**Describe what's wrong**
```sql
SELECT dateDiff('hour', toDateTime('2018-01-01 22:00:00'), toDateTime('2018-01-02 23:00:00'));
24 # expect 25, as example in the docs https://clickhouse.com/docs/en/sql-reference/functions/date-time-functions#date_diff
SELECT dateDiff('minute', toDateTime('2018-01-01 22:00:00'), toDateTime('2018-01-01 22:12:00'));
0 # expect 12
```

**Does it reproduce on recent release?**
yes

**How to reproduce**
macOS, follow quickstart to install or manually download macOS build on github

* Which ClickHouse server version to use
I tried the following versions for macOS (intel)
22.11.1.92
22.10.1.1484
22.8.8.3
22.8.6.71

* Which interface to use, if matters
cli `./clickhouse client`

### PR DESCRIPTION
**Pull request by zzsmdfj**
### Changelog category (leave one):

- Bug Fix (user-visible misbehavior in official stable or prestable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Fix date_diff() for hour/minute on macOS. Close https://github.com/ClickHouse/ClickHouse/issues/42742

### CODE REVIEW

**Comment by vdimir** [comment]
Cloud you please give some explanation why using `time_t` here is an issue?
Is it reproduced only on MacOS, or on arm64? We have tests run on arm, probably can try to reproduce it in CI.

**Comment by zzsmdfj** [comment]
> 

I only reproduced the problem on my mac system(Intel Core i7: x86-64).  I don't think the problem has anything to do with CPU architecture.It should be related to the build environment. 

On linux :` std::is_same_v<time_t, Int64> == true`  (The actual type of time_t is long int, Int64 is long int)
but On Darwin: ` std::is_same_v<time_t, Int64> == false(`  The actual type of time_t is long, Int64 is long long) 

` toRelativeMinuteNum`  or ` toRelativeHourNum`  in DateLUTImpl.h both has two overload function(The input parameters are Time(Int64) and type form parameters), On linux, ` toRelativeMinuteNum(static_cast<time_t>(t))` , which method to call is determined, but On Darwin, things got weird. So, I'll just change the type conversion to Int64 and let the method call be determined.

But one thing I'm not sure about is that the changes function are really just calls toRelativeMinuteNum(Time t), or different methods are used depending on the build environment(I don't think that should be)?  We can run all test to verify.

About test case or CI, I don't know how to run the tests in different build environments,Or all of our tests will run in different build environments?

**Comment by devcrafter** [comment]
> I only reproduced the problem on my mac system(Intel Core i7: x86-64). I don't think the problem has anything to do with CPU architecture.It should be related to the build environment.
> 
> On linux :` std::is_same_v<time_t, Int64> == true` (The actual type of time_t is long int, Int64 is long int) but On Darwin: ` std::is_same_v<time_t, Int64> == false(` The actual type of time_t is long, Int64 is long long)

There is nice comment regarding this issue in our code:
https://github.com/ClickHouse/ClickHouse/blob/f6c129043ef57162117df033e7288c5a12e1ae70/src/Common/DateLUTImpl.h#L138-L141

**Comment by devcrafter** [comment]
Stateless tests (tsan) - https://github.com/ClickHouse/ClickHouse/issues/43659
Integration tests (release) [3/4]  - https://github.com/ClickHouse/ClickHouse/issues/43735

**Pull request merged**
