### PR TITLE
Pre-pulling images for integration tests to detect broken infrastructure earlier

### PR DESCRIPTION
**Pull request by qoega**
### Changelog category (leave one):
- Build/Testing/Packaging Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Checks will try to download images before running integration tests. If image, proxy or whatever is broken in infrastructure it will not make tests flaky. Images will be cached locally and download time will not be added to random tests. Compose images are now changed to be used without correct environment from helpers/cluster.py.

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

Example of broken tests https://s3.amazonaws.com/clickhouse-test-reports/0/f7fbaf9c995acc31e866097c6482fc2622a21fc0/integration_tests__tsan__[3/4].html

```
2023-01-02 10:55:30 [ 306 ] INFO : Got exception pulling images: Command '['docker-compose', '--env-file', '/ClickHouse/tests/integration/test_global_overcommit_tracker/_instances_gw0_0/.env', '--project-name', 'roottestglobalovercommittracker', '--file', '/ClickHouse/tests/integration/test_global_overcommit_tracker/_instances_gw0_0/node/docker-compose.yml', 'pull']' timed out after 300 seconds (cluster.py:2344, start)
2023-01-02 10:55:30 [ 306 ] DEBUG : Command:['docker-compose', '--env-file', '/ClickHouse/tests/integration/test_global_overcommit_tracker/_instances_gw0_0/.env', '--project-name', 'roottestglobalovercommittracker', '--file', '/ClickHouse/tests/integration/test_global_overcommit_tracker/_instances_gw0_0/node/docker-compose.yml', 'pull'] (cluster.py:95, run_and_check)
2023-01-02 11:00:30 [ 306 ] INFO : Got exception pulling images: Command '['docker-compose', '--env-file', '/ClickHouse/tests/integration/test_global_overcommit_tracker/_instances_gw0_0/.env', '--project-name', 'roottestglobalovercommittracker', '--file', '/ClickHouse/tests/integration/test_global_overcommit_tracker/_instances_gw0_0/node/docker-compose.yml', 'pull']' timed out after 300 seconds (cluster.py:2344, start)
2023-01-02 11:00:33 [ 306 ] DEBUG : Command:['docker-compose', '--env-file', '/ClickHouse/tests/integration/test_global_overcommit_tracker/_instances_gw0_0/.env', '--project-name', 'roottestglobalovercommittracker', '--file', '/ClickHouse/tests/integration/test_global_overcommit_tracker/_instances_gw0_0/node/docker-compose.yml', 'pull'] (cluster.py:95, run_and_check)
2023-01-02 11:05:30 [ 306 ] DEBUG : Failed to start cluster:  (cluster.py:2646, start)
2023-01-02 11:05:30 [ 306 ] DEBUG : Timeout >900.0s (cluster.py:2647, start)
```

```
time="2023-01-02T10:50:30.530651723Z" level=debug msg="Trying to pull clickhouse/integration-test from http://dockerhub-proxy.dockerhub-proxy-zone:5000/ v2"
time="2023-01-02T10:50:30.617704857Z" level=debug msg="(*service).Write started" expected="sha256:6721da03881d141e799ed0f2aac44d29634f758c44bb6cf2539fa7ce26c01a9a" ref="index-sha256:6721da03881d141e799ed0f2aac44d29634f758c44bb6cf2539fa7ce26c01a9a" total=772
time="2023-01-02T10:50:30.630700796Z" level=debug msg="Pulling ref from V2 registry: clickhouse/integration-test:latest"
time="2023-01-02T10:50:30.630728197Z" level=debug msg="docker.io/clickhouse/integration-test:latest resolved to a manifestList object with 2 entries; looking for a unknown/amd64 match"
time="2023-01-02T10:50:30.630745248Z" level=debug msg="found match for linux/amd64 with media type application/vnd.docker.distribution.manifest.v2+json, digest sha256:74f323809976f989acb211c4e2d8841a49ab65924546dcda753848f499380a1b"
time="2023-01-02T10:50:30.630891530Z" level=debug msg="(*service).Write started" expected="sha256:74f323809976f989acb211c4e2d8841a49ab65924546dcda753848f499380a1b" ref="manifest-sha256:74f323809976f989acb211c4e2d8841a49ab65924546dcda753848f499380a1b" total=5335
time="2023-01-02T10:50:30.639912959Z" level=debug msg="pulling blob \"sha256:846c0b181fff0c667d9444f8378e8fcfa13116da8d308bf21673f7e4bea8d580\""
time="2023-01-02T10:50:30.639931995Z" level=debug msg="pulling blob \"sha256:621e82801ba0c5a011036caa2b0c61bdc16e22df975247695ee39550e507f018\""
time="2023-01-02T10:50:30.639979657Z" level=debug msg="pulling blob \"sha256:f73ece051c2ee5d6f9545689219e4dfa2c2dcb04ca22e9e6747a09e2f7bced0c\""
time="2023-01-02T10:50:30.644759013Z" level=info msg="Download failed, retrying (1/5): unexpected EOF"
time="2023-01-02T10:50:30.786730820Z" level=debug msg="Downloaded 846c0b181fff to tempfile /var/lib/docker/tmp/GetImageBlob3815390944"
time="2023-01-02T10:50:30.786789912Z" level=debug msg="pulling blob \"sha256:2827b11b34c4a063e49913ec2c78e7250039541c30ae5923a6b08bd4a598bbd5\""
time="2023-01-02T10:50:30.786868959Z" level=debug msg="Using /usr/bin/unpigz to decompress"
time="2023-01-02T10:50:30.787450252Z" level=debug msg="Applying tar in /var/lib/docker/overlay2/81482d2c4387a0ca09c9d4d00ee9c0504c31c0048b5bf0170e1c64085f356f27/diff" storage-driver=overlay2
time="2023-01-02T10:50:30.792616267Z" level=debug msg="Downloaded 2827b11b34c4 to tempfile /var/lib/docker/tmp/GetImageBlob443222412"
time="2023-01-02T10:50:30.792649696Z" level=debug msg="pulling blob \"sha256:d8ca5ab71310f43fd9a2b8ce1321c6d1942ba59e3edc08162a20de097bb0522f\""
time="2023-01-02T10:50:30.796611998Z" level=info msg="Download failed, retrying (1/5): unexpected EOF"
time="2023-01-02T10:50:30.939835763Z" level=debug msg="Downloaded f73ece051c2e to tempfile /var/lib/docker/tmp/GetImageBlob1288858726"
time="2023-01-02T10:50:30.939879942Z" level=debug msg="pulling blob \"sha256:a7041e7ff257570a5acc86ff7190aeb86c4f08149ea928a6e6fc785ed7f11586\""
time="2023-01-02T10:50:30.943867816Z" level=info msg="Download failed, retrying (1/5): unexpected EOF"
time="2023-01-02T10:50:31.289433632Z" level=debug msg="Applied tar sha256:0002c93bdb3704dd9e36ce5153ef637f84de253015f3ee330468dccdeacad60b to 81482d2c4387a0ca09c9d4d00ee9c0504c31c0048b5bf0170e1c64085f356f27, size: 72785453"
time="2023-01-02T10:50:35.645023923Z" level=debug msg="pulling blob \"sha256:621e82801ba0c5a011036caa2b0c61bdc16e22df975247695ee39550e507f018\""
```

### CODE REVIEW

**Review by Felixoid — APPROVED** [review]
Very cool improvement!

**Comment by Felixoid** [comment]
> After reverting it, we dont see the fails anymore.

Maybe it struggles to bring up the cluster. Do we have any other tests with such big number of instances?

**Comment by SmitaRKulkarni** [comment]
> Maybe it struggles to bring up the cluster. Do we have any other tests with such big number of instances?

Actually `test_backup_restore_new/test.py` does not have many instances.

**Comment by Felixoid** [comment]
@qoega do you think it works as expected? It looks to me like it redownloads all the images multiple times https://github.com/ClickHouse/ClickHouse/actions/runs/4498786610/jobs/7918888231#step:6:5897

See all the logs above the given line

**Comment by qoega** [comment]
>do you think it works as expected? It looks to me like it redownloads all the images multiple times 

WTF... Is it before or after my changes? It looks the docker cache is not preserved at all between runner runs (as if we use `--tmpfs` or run `docker image prune`...) We should not download images at all after we have --pre-pull.

**Comment by SmitaRKulkarni** [comment]
>  Is it before or after my changes?

It was seen on Mar 23, (in #47586), so after this PR was merged.

**Comment by Felixoid** [comment]
It does it before https://github.com/ClickHouse/ClickHouse/actions/runs/4498786610/jobs/7918888231#step:6:104

but it looks like it downloads them multiple time

**Pull request merged**
