### PR TITLE
Less dependencies from disks in buffers

### PR DESCRIPTION
**Pull request by alesapin**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required

### CODE REVIEW

**Review by kssenii — APPROVED** [review]

**Comment by alesapin** [comment]
`DatabaseReplicatedDDLWorker::initializeLogPointer` -- unrelated fixed failure in backward comp check.

**Comment by alesapin** [comment]
Assertion in debug: https://github.com/ClickHouse/ClickHouse/issues/36098
Failure over S3: https://github.com/ClickHouse/ClickHouse/issues/36099

**Comment by alesapin** [comment]
`test_storage_mongodb` fixed in master

**Comment by alesapin** [comment]
`test_input_format_parallel_parsing_memory_tracking/test.py::test_memory_tracking_total` flaky

**Pull request merged**
