### PR TITLE
Fix cast lowcard of nullable in JoinSwitcher

### LINKED ISSUE #37385: MergeJoin extractMinMax downcast of address ... which does not point to an object of type 'const DB::ColumnNullable'
```
../src/Common/assert_cast.h:50:12: runtime error: downcast of address 0x7ff8242183e0 which does not point to an object of type 'const DB::ColumnNullable'
0x7ff8242183e0: note: object is of type 'DB::ColumnVector<unsigned long>'
 00 00 00 00  58 30 88 0a 00 00 00 00  01 00 00 00 00 00 00 00  20 e4 30 24 f8 7f 00 00  58 e4 30 24
              ^~~~~~~~~~~~~~~~~~~~~~~
              vptr for 'DB::ColumnVector<unsigned long>'

    #0 0x2340d3d4 in DB::ColumnNullable const& assert_cast<DB::ColumnNullable const&, DB::IColumn const&>(DB::IColumn const&) build_docker/../src/Common/assert_cast.h:50:12
    #1 0x2340d3d4 in DB::ColumnNullable::insertFrom(DB::IColumn const&, unsigned long) build_docker/../src/Columns/ColumnNullable.cpp:193:43
    #2 0x22e1429b in DB::(anonymous namespace)::extractMinMax(DB::Block const&, DB::Block const&) build_docker/../src/Interpreters/MergeJoin.cpp:131:21
    #3 0x22e187de in DB::MergeJoin::mergeFlushedRightBlocks()::$_0::operator()(DB::Block const&) const build_docker/../src/Interpreters/MergeJoin.cpp:618:47
    #4 0x22e187de in decltype(static_cast<DB::MergeJoin::mergeFlushedRightBlocks()::$_0&>(fp)(static_cast<DB::Block const&>(fp0))) std::__1::__invoke<DB::MergeJoin::mergeFlushedRightBlocks()::$_0&, DB::Block const&>(DB::MergeJoin::mergeFlushedRightBlocks()::$_0&, DB::Block const&) build_docker/../contrib/libcxx/include/type_traits:3640:23
    #5 0x22fca969 in std::__1::__function::__policy_func<void (DB::Block const&)>::operator()(DB::Block const&) const build_docker/../contrib/libcxx/include/__functional/function.h:843:16
    #6 0x22fca969 in std::__1::function<void (DB::Block const&)>::operator()(DB::Block const&) const build_docker/../contrib/libcxx/include/__functional/function.h:1184:12
    #7 0x22fca969 in DB::(anonymous namespace)::flushToManyFiles(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::Block const&, DB::QueryPipelineBuilder, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::function<void (DB::Block const&)>) build_docker/../src/Interpreters/SortedBlocksWriter.cpp:40:9
    #8 0x22fca678 in DB::SortedBlocksWriter::finishMerge(std::__1::function<void (DB::Block const&)>) build_docker/../src/Interpreters/SortedBlocksWriter.cpp:230:12
    #9 0x22e13b02 in DB::MergeJoin::mergeFlushedRightBlocks() build_docker/../src/Interpreters/MergeJoin.cpp:622:41
    #10 0x22e12b2d in DB::MergeJoin::setTotals(DB::Block const&) build_docker/../src/Interpreters/MergeJoin.cpp:564:5
    #11 0x24571474 in DB::FillingRightJoinSideTransform::work() build_docker/../src/Processors/Transforms/JoiningTransform.cpp:293:15
    #12 0x241f48d8 in DB::executeJob(DB::IProcessor*) build_docker/../src/Processors/Executors/ExecutionThreadContext.cpp:45:20
    #13 0x241f4618 in DB::ExecutionThreadContext::executeTask() build_docker/../src/Processors/Executors/ExecutionThreadContext.cpp:68:9
    #14 0x241e6c40 in DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*) build_docker/../src/Processors/Executors/PipelineExecutor.cpp:217:26
    #15 0x241e65a6 in DB::PipelineExecutor::executeSingleThread(unsigned long) build_docker/../src/Processors/Executors/PipelineExecutor.cpp:182:5
    #16 0x241e65a6 in DB::PipelineExecutor::executeImpl(unsigned long) build_docker/../src/Processors/Executors/PipelineExecutor.cpp:328:9
    #17 0x241e610c in DB::PipelineExecutor::execute(unsigned long) build_docker/../src/Processors/Executors/PipelineExecutor.cpp:88:9
    #18 0x241f8fc2 in DB::threadFunction(DB::PullingAsyncPipelineExecutor::Data&, std::__1::shared_ptr<DB::ThreadGroupStatus>, unsigned long) build_docker/../src/Processors/Executors/PullingAsyncPipelineExecutor.cpp:78:24
    #19 0x241f8f21 in DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0::operator()() const build_docker/../src/Processors/Executors/PullingAsyncPipelineExecutor.cpp:105:13
    #20 0x241f8f21 in decltype(static_cast<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&>(fp)()) std::__1::__invoke_constexpr<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&) build_docker/../contrib/libcxx/include/type_traits:3648:23
    #21 0x241f8dda in decltype(auto) std::__1::__apply_tuple_impl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::__1::tuple<>&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::__1::tuple<>&, std::__1::__tuple_indices<>) build_docker/../contrib/libcxx/include/tuple:1595:1
    #22 0x241f8dda in decltype(auto) std::__1::apply<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::__1::tuple<>&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::__1::tuple<>&) build_docker/../contrib/libcxx/include/tuple:1604:1
    #23 0x241f8dda in ThreadFromGlobalPool::ThreadFromGlobalPool<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'()::operator()() build_docker/../src/Common/ThreadPool.h:188:13
    #24 0x241f8dda in decltype(static_cast<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(fp)()) std::__1::__invoke<ThreadFromGlobalPool::ThreadFromGlobalPool<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'()&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&) build_docker/../contrib/libcxx/include/type_traits:3640:23
    #25 0xf9687b9 in std::__1::__function::__policy_func<void ()>::operator()() const build_docker/../contrib/libcxx/include/__functional/function.h:843:16
    #26 0xf9687b9 in std::__1::function<void ()>::operator()() const build_docker/../contrib/libcxx/include/__functional/function.h:1184:12
    #27 0xf9687b9 in ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) build_docker/../src/Common/ThreadPool.cpp:281:17
    #28 0xf96b281 in void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()::operator()() const build_docker/../src/Common/ThreadPool.cpp:143:73
    #29 0xf96b281 in decltype(static_cast<void>(fp)()) std::__1::__invoke<void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>(void&&) build_docker/../contrib/libcxx/include/type_traits:3640:23
    #30 0xf96b281 in void std::__1::__thread_execute<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>(std::__1::tuple<void, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>&, std::__1::__tuple_indices<>) build_docker/../contrib/libcxx/include/thread:282:5
    #31 0xf96b281 in void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()> >(void*) build_docker/../contrib/libcxx/include/thread:293:5
    #32 0x7ffadc641608 in start_thread /build/glibc-sMfBJT/glibc-2.31/nptl/pthread_create.c:477:8
    #33 0x7ffadc566162 in __clone /build/glibc-sMfBJT/glibc-2.31/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

https://s3.amazonaws.com/clickhouse-test-reports/37327/1ac4199e785ff9700e6752afd6cd8e43e84e7a02/fuzzer_astfuzzerubsan,actions//report.html

### PR DESCRIPTION
**Pull request by vdimir**
### Changelog category (leave one):

- Bug Fix (user-visible misbehavior in official stable or prestable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
* Fix cast lowcard of nullable in JoinSwitcher, close https://github.com/ClickHouse/ClickHouse/issues/37385

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Review by Avogar — APPROVED** [review]

**Comment by vdimir** [comment]
> Stateless tests (thread, actions) [3/3] — Tests are not finished, fail: 1, passed: 619, skipped: 2

Some tsan report, but looks unrelated to change, can't reproduce locally yet

https://pastila.nl/?00bfc54a/d1895d7b6388add2d56c73882336d1ba

> AST fuzzer (MSan, actions) — Lost connection to server. See the logs. 

No any fatal error in logs, last fuzzed queries is not related to join.

**Comment by tavplubix** [comment]
@vdimir Stress tests failures are related

**Comment by tavplubix** [comment]
> Some tsan report, but looks unrelated to change, can't reproduce locally yet

For sanitizer report (as well as for segfault, failed assertion and similar things) its not enough to just write "unrelated to change", at least it's necessary to create an issue (if not exists) and (if possible) assign/mention someone who may be interested.

(We already have issue for this particular report (#37452), I just call attention to the fact that fuzzers, stress tests, sanitizers and other randomized tests are almost useless if we simply write "unrelated to change")

**Comment by boldakovds** [comment]
Hello! Will it be merge into 22.3 lts version some bugfix (when) or i'll need to increase my version to 22.6?

**Comment by vdimir** [comment]
> Hello! Will it be merge into 22.3 lts version some bugfix (when) or i'll need to increase my version to 22.6?

@boldakovds 
Using the latest stable version of the ClickHouse server is always better, so we recommend updating. But since this fix is small, we'll try to back-port it.

**Pull request merged**
