### PR TITLE
Rework #52159 to avoid coredump generation

### PR DESCRIPTION
**Pull request by Algunenano**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

cc @alexey-milovidov 

This "feature" is generating random coredumps in stress tests because now clickhouse local and client are aborting on exceptions.

For example (CH version 23.9.2 in those stress tests)
```
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=140324858946944) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=140324858946944) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=140324858946944, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007f9fed71b476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007f9fed7017f3 in __GI_abort () at ./stdlib/abort.c:79
#5  0x000000001824dee4 in abort_message (format=0x7448df "terminating") at ./contrib/llvm-project/libcxxabi/src/abort_message.cpp:78
#6  0x000000001824dbc0 in demangling_terminate_handler () at ./contrib/llvm-project/libcxxabi/src/cxa_default_handlers.cpp:48
#7  0x000000001826a963 in std::__terminate (func=0x450b9) at ./contrib/llvm-project/libcxxabi/src/cxa_handlers.cpp:59
#8  0x000000001826a926 in std::terminate () at ./contrib/llvm-project/libcxxabi/src/cxa_handlers.cpp:92
#9  0x000000000c741ef3 in DB::Exception::Exception (this=0x7ffdfe27a248, msg_masked=..., code=704, remote_=true) at ./src/Common/Exception.cpp:100
#10 0x000000000c7acd8f in DB::Exception::Exception (this=0x7ffdfe27a248, msg=..., code=704, remote_=true) at ./src/Common/Exception.h:72
#11 DB::Exception::createDeprecated (msg=..., code=704, remote_=true) at ./src/Common/Exception.h:80
#12 DB::readException (buf=..., additional_message=..., remote_exception=true) at ./src/IO/ReadHelpers.cpp:1379
#13 0x000000001322698a in DB::Connection::receiveException (this=<optimized out>) at ./src/Client/Connection.cpp:1210
#14 0x000000001322f46d in DB::Connection::receivePacket (this=0x7f9fec945300) at ./src/Client/Connection.cpp:1047
#15 0x0000000013201265 in DB::ClientBase::receiveAndProcessPacket (this=0x7ffdfe27d480, parsed_query=..., cancelled_=false) at ./src/Client/ClientBase.cpp:1094
#16 0x00000000131ff3c8 in DB::ClientBase::receiveResult (this=0x7ffdfe27d480, parsed_query=..., signals_before_stop=1, partial_result_on_first_cancel=false) at ./src/Client/ClientBase.cpp:1069
#17 DB::ClientBase::processOrdinaryQuery (this=0x7ffdfe27d480, query_to_execute=..., parsed_query=...) at ./src/Client/ClientBase.cpp:987
#18 DB::ClientBase::processParsedSingleQuery (this=0x7ffdfe27d480, full_query=..., query_to_execute=..., parsed_query=..., echo_query_=..., report_error=<optimized out>) at ./src/Client/ClientBase.cpp:1844
#19 0x00000000131fc93a in DB::ClientBase::processTextAsSingleQuery (this=<optimized out>, full_query=...) at ./src/Client/ClientBase.cpp:840
#20 0x000000001320b75c in DB::ClientBase::processQueryText (this=0x7ffdfe27d480, text=...) at ./src/Client/ClientBase.cpp:2242
#21 0x000000001320ff3b in DB::ClientBase::runNonInteractive (this=0x7ffdfe27d480) at ./src/Client/ClientBase.cpp:2553
#22 0x000000000c89fcce in DB::Client::main (this=0x7ffdfe27d480) at ./programs/client/Client.cpp:372
#23 0x0000000015d1cc46 in Poco::Util::Application::run (this=0x7ffdfe27d480) at ./base/poco/Util/src/Application.cpp:315
#24 0x000000000c8b2e48 in mainEntryClickHouseClient (argc=129, argv=0x7f9fec937800) at ./programs/client/Client.cpp:1444
#25 0x0000000007227aba in main (argc_=<optimized out>, argv_=<optimized out>) at ./programs/main.cpp:491
```

Or clickhouse local:
```
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=139919435994496) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=139919435994496) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=139919435994496, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007f41885a6476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007f418858c7f3 in __GI_abort () at ./stdlib/abort.c:79
#5  0x000000001824dee4 in abort_message (format=0x7448df "terminating") at ./contrib/llvm-project/libcxxabi/src/abort_message.cpp:78
#6  0x000000001824dbc0 in demangling_terminate_handler () at ./contrib/llvm-project/libcxxabi/src/cxa_default_handlers.cpp:48
#7  0x000000001826a963 in std::__terminate (func=0x42316) at ./contrib/llvm-project/libcxxabi/src/cxa_handlers.cpp:59
#8  0x000000001826a926 in std::terminate () at ./contrib/llvm-project/libcxxabi/src/cxa_handlers.cpp:92
#9  0x000000000c741ef3 in DB::Exception::Exception (this=0x7f4187949680, msg_masked=..., code=62, remote_=false) at ./src/Common/Exception.cpp:100
#10 0x00000000075c238d in DB::Exception::createDeprecated(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) ()
#11 0x0000000013b0427c in DB::parseQueryAndMovePosition (parser=..., pos=<optimized out>, end=<optimized out>, query_description=..., allow_multi_statements=<optimized out>, max_query_size=<optimized out>, max_parser_depth=<optimized out>)
    at ./src/Parsers/parseQuery.cpp:363
#12 0x00000000131f97f9 in DB::ClientBase::parseQuery (this=0x7ffe502b5490, pos=<optimized out>, end=0x7f418741a2ad "", allow_multi_statements=false) at ./src/Client/ClientBase.cpp:362
#13 0x00000000131fc5c3 in DB::ClientBase::processTextAsSingleQuery (this=0x42316, full_query=...) at ./src/Client/ClientBase.cpp:811
#14 0x000000001320b75c in DB::ClientBase::processQueryText (this=0x7ffe502b5490, text=...) at ./src/Client/ClientBase.cpp:2242
#15 0x000000001320ff3b in DB::ClientBase::runNonInteractive (this=0x7ffe502b5490) at ./src/Client/ClientBase.cpp:2553
#16 0x000000000c8cab5c in DB::LocalServer::main (this=0x7ffe502b5490) at ./programs/local/LocalServer.cpp:536
#17 0x0000000015d1cc46 in Poco::Util::Application::run (this=0x7ffe502b5490) at ./base/poco/Util/src/Application.cpp:315
#18 0x000000000c8d6a2f in mainEntryClickHouseLocal (argc=3, argv=0x7f418793f6a0) at ./programs/local/LocalServer.cpp:931
#19 0x0000000007227aba in main (argc_=<optimized out>, argv_=<optimized out>) at ./programs/main.cpp:491
(gdb) f 9
#9  0x000000000c741ef3 in DB::Exception::Exception (this=0x7f4187949680, msg_masked=..., code=62, remote_=false) at ./src/Common/Exception.cpp:100
(gdb) p _msg
$2 = {static __endian_factor = 1, __r_ = {<std::__1::__compressed_pair_elem<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::__rep, 0, false>> = {__value_ = {{__l = {
            __data_ = 0x7f418715ec00 "Syntax error: failed at position 1 ('this'): this is wrong. Expected one of: Query, Query with output, EXPLAIN, SELECT query, possibly with UNION, list of union elements, SELECT query, subquery, possi"..., 
            __size_ = 2312, __cap_ = 2320, __is_long_ = 1}, __s = {__data_ = "\000\354\025\207A\177\000\000\b\t\000\000\000\000\000\000\020\t\000\000\000\000", __padding_ = 0x7f41879497a7 "\200", __size_ = 0 '\000', __is_long_ = 1 '\001'}, __r = {
            __words = {139919415962624, 2312, 
              9223372036854778128}}}}}, <std::__1::__compressed_pair_elem<std::__1::allocator<char>, 1, true>> = {<std::__1::allocator<char>> = {<std::__1::__non_trivial_if<true, std::__1::allocator<char> >> = {<No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}, static npos = 18446744073709551615}
```

I understand we want to have coredumps on ABRT so we can investigate issues that happen during stress tests, but then having any exception (from client, server, local or whatever) trigger an ABORT means we get unnecessary coredumps.

As an alternative we can exit with a status code and check for that. The program will exist immediately without output

### CODE REVIEW

**Comment by robot-clickhouse-ci-2** [comment]
*This is an automated comment for commit f9e7ec5354de9436784f4e6731840ba2ddeb630d with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/56039/f9e7ec5354de9436784f4e6731840ba2ddeb630d/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td><a href="https://github.com/ClickHouse/ClickHouse/actions/runs/6652122722">✅ success</a></td></tr>
<tbody>
</table>
</details>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/56039/f9e7ec5354de9436784f4e6731840ba2ddeb630d/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Review by alexey-milovidov — CHANGES_REQUESTED** [review]
I really need this test; it is a significant milestone in our testing.

**Comment by Algunenano** [comment]
It seems quick_exit requires GLIBC 2.24 and it's not worth looking for a way of replacing it. Let's use _Exit instead.

**Review by alexey-milovidov — APPROVED** [review]

**Comment by Algunenano** [comment]
Several docker pull failures, but one interesting failure in `Stateless tests (release)`: `01104_distributed_numbers_test` timeout out and [it seems it's stuck](https://s3.amazonaws.com/clickhouse-test-reports/56039/431ef262704de8bce9bc4b9bc68af068b2ced424/stateless_tests__release_/run.log):

The Select is "running"
```
2023-10-31 21:30:57 query:                SELECT '100' AS number FROM d_numbers AS n WHERE n.number = 100 LIMIT 2;
2023-10-31 21:30:57 query_kind:           Select
2023-10-31 21:30:57 thread_ids:           [56884,27362]
2023-10-31 21:30:57 ProfileEvents:        {'Query':1,'SelectQuery':1,'QueriesWithSubqueries':2,'SelectQueriesWithSubqueries':2,'FunctionExecute':163667033,'NetworkReceiveElapsedMicroseconds':57021,'NetworkSendElapsedMicroseconds':822507,'NetworkSendBytes':25755597,'SelectedRows':5697412946519,'SelectedBytes':45579303572152,'ContextLock':45,'RWLockAcquiredReadLocks':3,'RealTimeMicroseconds':2814214202,'UserTimeMicroseconds':2791405754,'SystemTimeMicroseconds':4199099,'SoftPageFaults':113874,'OSCPUWaitMicroseconds':16847479,'OSCPUVirtualTimeMicroseconds':2795485445,'OSReadChars':112171096,'OSWriteChars':1076196,'QueryProfilerRuns':8427,'LogTrace':5,'LogDebug':1}
2023-10-31 21:30:57 Settings:             {'min_compress_block_size':'2187809','max_compress_block_size':'2002753','max_block_size':'34811','max_threads':'1','max_read_buffer_size':'825704','connect_timeout_with_failover_ms':'2000','connect_timeout_with_failover_secure_ms':'3000','idle_connection_timeout':'36000','s3_check_objects_after_upload':'1','use_uncompressed_cache':'1','stream_like_engine_allow_direct_select':'1','replication_wait_for_inactive_replica_timeout':'30','compile_aggregate_expressions':'0','compile_sort_description':'0','min_count_to_compile_sort_description':'0','group_by_two_level_threshold':'861083','group_by_two_level_threshold_bytes':'47132600','allow_nonconst_timezone_arguments':'1','input_format_parallel_parsing':'0','min_chunk_bytes_for_parallel_parsing':'16700222','output_format_parallel_formatting':'0','merge_tree_coarse_index_granularity':'3','min_bytes_to_use_direct_io':'1981038974','min_bytes_to_use_mmap_io':'10737418240','log_queries':'1','insert_quorum_timeout':'60000','http_response_buffer_size':'4160914','fsync_metadata':'1','http_send_timeout':'60','http_receive_timeout':'60','opentelemetry_start_trace_probability':'0.1','max_untracked_memory':'1048576','memory_profiler_step':'1048576','log_comment':'01104_distributed_numbers_test.sql','send_logs_level':'warning','optimize_read_in_order':'0','optimize_aggregation_in_order':'1','aggregation_in_order_max_block_bytes':'6506189','read_in_order_two_level_merge_threshold':'66','database_atomic_wait_for_drop_and_detach_synchronously':'1','remote_filesystem_read_method':'read','local_filesystem_read_prefetch':'1','remote_filesystem_read_prefetch':'0','async_insert_busy_timeout_ms':'5000','enable_filesystem_cache':'1','enable_filesystem_cache_on_write_operations':'1','load_marks_asynchronously':'1','allow_prefetched_read_pool_for_remote_filesystem':'0','allow_prefetched_read_pool_for_local_filesystem':'0','filesystem_prefetch_step_marks':'50','filesystem_prefetch_min_bytes_for_single_read_task':'1048576','filesystem_prefetch_max_memory_usage':'134217728','filesystem_prefetches_limit':'0','optimize_sorting_by_input_stream_properties':'0','insert_keeper_max_retries':'20','insert_keeper_fault_injection_probability':'0.01','session_timezone':'Africa/Juba'}
2023-10-31 21:30:57 current_database:     test_c5r9jkdl
2023-10-31 21:30:57 stacktraces:          Thread ID 27362
2023-10-31 21:30:57 ::
2023-10-31 21:30:57 ::
2023-10-31 21:30:57 ./build_docker/./contrib/llvm-project/libcxx/src/condition_variable.cpp:77::bool ConcurrentBoundedQueue<DB::Chunk>::popImpl<true>(DB::Chunk&, std::__1::optional<unsigned long>)
2023-10-31 21:30:57 ./build_docker/./src/Common/ConcurrentBoundedQueue.h:0::DB::LazyOutputFormat::getChunk(unsigned long)
2023-10-31 21:30:57 ./build_docker/./contrib/llvm-project/libcxx/include/vector:951::DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)
2023-10-31 21:30:57 ./build_docker/./src/Processors/Executors/PullingAsyncPipelineExecutor.cpp:153::DB::PullingAsyncPipelineExecutor::pull(DB::Block&, unsigned long)
2023-10-31 21:30:57 ./build_docker/./src/Server/TCPHandler.cpp:966::DB::TCPHandler::runImpl()
2023-10-31 21:30:57 ./build_docker/./src/Server/TCPHandler.cpp:2257::DB::TCPHandler::run()
2023-10-31 21:30:57 ./build_docker/./base/poco/Net/src/TCPServerConnection.cpp:57::Poco::Net::TCPServerConnection::start()
2023-10-31 21:30:57 ./build_docker/./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:48::Poco::Net::TCPServerDispatcher::run()
2023-10-31 21:30:57 ./build_docker/./base/poco/Foundation/src/ThreadPool.cpp:202::Poco::PooledThread::run()
2023-10-31 21:30:57 ./build_docker/./base/poco/Foundation/include/Poco/SharedPtr.h:231::Poco::ThreadImpl::runnableEntry(void*)
2023-10-31 21:30:57 ::
2023-10-31 21:30:57 ::Thread ID 56884
2023-10-31 21:30:57 ./build_docker/./src/Processors/ISimpleTransform.h:34::DB::ISimpleTransform::transform(DB::Chunk&, DB::Chunk&)
```

So the DROP database can't finish.


The test itself seems to be failing occasionally [in other PRs too](https://play.clickhouse.com/play?user=play#U0VMRUNUCiAgdGVzdF9uYW1lLAogIHRvU3RhcnRPZkRheShjaGVja19zdGFydF90aW1lKSBhcyB0LAogIGNvdW50KCkgYXMgcnVucywKICBjb25jYXQocm91bmQoMTAwICogKGNvdW50SWYodGVzdF9zdGF0dXMgIT0gJ09LJyBBTkQgdGVzdF9zdGF0dXMgIT0gJ1NLSVBQRUQnKSBBUyBmKSAvIHJ1bnMsIDEpOjpTdHJpbmcsICclJykgYXMgZmFpbHVyZV9wZXJjZW50YWdlLAogIGFueUlmKHJlcG9ydF91cmwsIHRlc3Rfc3RhdHVzICE9ICdPSycgQU5EIHRlc3Rfc3RhdHVzICE9ICdTS0lQUEVEJykgYXMgbGFzdF9yZXBvcnQsCiAgZ3JvdXBBcnJheURpc3RpbmN0KGNoZWNrX25hbWUpIGFzIGNoZWNrX25hbWVzCkZST00gY2hlY2tzCldIRVJFCiAgICB0ZXN0X25hbWUgTElLRSAnJTAxMTA0X2Rpc3RyaWJ1dGVkX251bWJlcnNfdGVzdCUnCiAgICBBTkQgcHVsbF9yZXF1ZXN0X251bWJlciA9IDAKICAgIEFORCBjaGVja19zdGFydF90aW1lID4gdG9kYXkoKSAtIGludGVydmFsIDMwIGRheQpHUk9VUCBCWSB0ZXN0X25hbWUsIHQKT1JERVIgYnkgdA==) so I'm opening a ticket for investigation

**Pull request merged**
