### PR TITLE
Fix null problem in FunctionIn

### PR DESCRIPTION
**Pull request by janplus**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Category (leave one):
- Bug Fix

Short description (up to few sentences):

`In` predicate should generate Null result from Null input like the `Equal` function.

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
Tests have failed.

**Comment by janplus** [comment]
@alexey-milovidov Thanks for your quick response. I'm on my vacation now, will check these errors after back to work.

**Comment by janplus** [comment]
@alexey-milovidov Sorry for my late response. I have add an extra function to meet the new Nullable In's requirement. You may check it now.

**Comment by janplus** [comment]
@alexey-milovidov It seems have passed all tests. You may review this PR now.

**Comment by janplus** [comment]
Ping @alexey-milovidov

**Comment by alexey-milovidov** [comment]
Ok.

Now it corresponds to http://sqlfiddle.com/#!9/1b8410/1

**Pull request merged**
