### PR TITLE
Protect temporary part directories from removing during RESTORE

### LINKED ISSUE #67220: Table restore failed because tmp_restore_xxxx part was cleaned up (in test 03032_async_backup_restore)
Happened in CI run:
https://s3.amazonaws.com/clickhouse-test-reports/67176/498ae4358647dbff5fde2861a7113a9c9597930a/stateless_tests__debug__s3_storage__[2_2].html

https://pastila.nl/?000628ea/0cc76ddc1362172872c6875d86f3bcd2#e8Bk2B6g6cTnEdomCgRz2A==

In the logs I see that table tbl2 was created by restore

```
2024.07.26 11:21:51.508938 [ 33898 ] {06b2a03a-4430-4d2a-92e7-fdf12b4fbfaf} <Trace> RestorerFromBackup: Creating table test_xrb1u51c.tbl2: CREATE TABLE IF NOT EXISTS test_xrb1u51c.tbl2 UU
ID '585d5243-2829-4c58-be87-2fdc8e2b61e5' (`a` Int32) ENGINE = MergeTree ORDER BY tuple() SETTINGS index_granularity = 31030, min_bytes_for_wide_part = 0, ratio_of_defaults_for_sparse_ser
ialization = 0.8355984687805176, replace_long_file_name_to_hash = true, max_file_name_length = 11, min_bytes_for_full_part_storage = 536870912, compact_parts_max_bytes_to_buffer = 1950487
17, compact_parts_max_granules_to_buffer = 256, compact_parts_merge_max_bytes_to_prefetch_part = 18185723, merge_max_block_size = 7862, old_parts_lifetime = 480., prefer_fetch_merged_part
_size_threshold = 10737418240, vertical_merge_algorithm_min_rows_to_activate = 1000000, vertical_merge_algorithm_min_columns_to_activate = 33, min_merge_bytes_to_use_direct_io = 461731536
8, index_granularity_bytes = 23848274, concurrent_part_removal_threshold = 100, allow_vertical_merges_from_compact_to_wide_parts = true, cache_populated_by_fetch = true, marks_compress_bl
ock_size = 96071, primary_key_compress_block_size = 30522
2024.07.26 11:21:51.571949 [ 33898 ] {06b2a03a-4430-4d2a-92e7-fdf12b4fbfaf} <Debug> test_xrb1u51c.tbl2 (585d5243-2829-4c58-be87-2fdc8e2b61e5): Loading data parts
2024.07.26 11:21:51.575299 [ 33898 ] {06b2a03a-4430-4d2a-92e7-fdf12b4fbfaf} <Debug> test_xrb1u51c.tbl2 (585d5243-2829-4c58-be87-2fdc8e2b61e5): There are no data parts
2024.07.26 11:21:51.575644 [ 33898 ] {06b2a03a-4430-4d2a-92e7-fdf12b4fbfaf} <Debug> DatabaseAtomic (test_xrb1u51c): There are 0 detached tables. Start searching non used tables.
2024.07.26 11:21:51.575670 [ 33898 ] {06b2a03a-4430-4d2a-92e7-fdf12b4fbfaf} <Debug> DatabaseAtomic (test_xrb1u51c): Found 0 non used tables in detached tables.
2024.07.26 11:21:51.578000 [ 33385 ] {06b2a03a-4430-4d2a-92e7-fdf12b4fbfaf} <Trace> BackupReaderDisk: Copying file data/test_xrb1u51c/tbl/all_1_1_0/a.bin to disk s3 through buffers
2024.07.26 11:21:51.652605 [ 33385 ] {06b2a03a-4430-4d2a-92e7-fdf12b4fbfaf} <Trace> BackupReaderDisk: Copying file data/test_xrb1u51c/tbl/all_1_1_0/a.cmrk2 to disk s3 through buffers
2024.07.26 11:21:51.718474 [ 87668 ] {} <Debug> TCPHandler: Connected ClickHouse client version 24.8.0, revision: 54468, database: test_xrb1u51c, user: default.
2024.07.26 11:21:51.722464 [ 33385 ] {06b2a03a-4430-4d2a-92e7-fdf12b4fbfaf} <Trace> BackupReaderDisk: Copying file data/test_xrb1u51c/tbl/all_1_1_0/checksums.txt to disk s3 through buffer
s
2024.07.26 11:21:51.774745 [ 33385 ] {06b2a03a-4430-4d2a-92e7-fdf12b4fbfaf} <Trace> BackupReaderDisk: Copying file data/test_xrb1u51c/tbl/all_1_1_0/columns.txt to disk s3 through buffers
2024.07.26 11:21:51.799616 [ 33385 ] {06b2a03a-4430-4d2a-92e7-fdf12b4fbfaf} <Trace> BackupReaderDisk: Copying file data/test_xrb1u51c/tbl/all_1_1_0/count.txt to disk s3 through buffers
2024.07.26 11:21:51.830418 [ 33385 ] {06b2a03a-4430-4d2a-92e7-fdf12b4fbfaf} <Trace> BackupReaderDisk: Copying file data/test_xrb1u51c/tbl/all_1_1_0/default_compression_codec.txt to disk s
3 through buffers
2024.07.26 11:21:51.872196 [ 33385 ] {06b2a03a-4430-4d2a-92e7-fdf12b4fbfaf} <Trace> BackupReaderDisk: Copying file data/test_xrb1u51c/tbl/all_1_1_0/metadata_version.txt to disk s3 through
 buffers
2024.07.26 11:21:52.275425 [ 33385 ] {06b2a03a-4430-4d2a-92e7-fdf12b4fbfaf} <Trace> BackupReaderDisk: Copying file data/test_xrb1u51c/tbl/all_1_1_0/serialization.json to disk s3 through b
uffers
2024.07.26 11:21:52.277060 [ 20950 ] {} <Debug> TCPHandler: Connected ClickHouse client version 24.8.0, revision: 54468, database: test_xrb1u51c, user: default.
2024.07.26 11:21:53.033646 [ 87668 ] {} <Debug> TCPHandler: Connected ClickHouse client version 24.8.0, revision: 54468, database: test_xrb1u51c, user: default.
2024.07.26 11:21:53.376399 [ 87671 ] {} <Debug> TCPHandler: Connected ClickHouse client version 24.8.0, revision: 54468, database: test_xrb1u51c, user: default.
2024.07.26 11:21:54.500098 [ 87231 ] {} <Debug> TCPHandler: Connected ClickHouse client version 24.8.0, revision: 54468, database: test_xrb1u51c, user: default.
2024.07.26 11:21:54.959037 [ 87739 ] {} <Debug> TCPHandler: Connected ClickHouse client version 24.8.0, revision: 54468, database: test_xrb1u51c, user: default.
2024.07.26 11:21:55.340825 [ 87739 ] {} <Debug> TCPHandler: Connected ClickHouse client version 24.8.0, revision: 54468, database: test_xrb1u51c, user: default.
2024.07.26 11:21:55.849328 [ 87739 ] {} <Debug> TCPHandler: Connected ClickHouse client version 24.8.0, revision: 54468, database: test_xrb1u51c, user: default.
2024.07.26 11:21:56.351297 [ 87739 ] {} <Debug> TCPHandler: Connected ClickHouse client version 24.8.0, revision: 54468, database: test_xrb1u51c, user: default.
2024.07.26 11:21:56.858393 [ 87739 ] {} <Debug> TCPHandler: Connected ClickHouse client version 24.8.0, revision: 54468, database: test_xrb1u51c, user: default.
```
And suddenly the part that is being restored got cleaned up: 
```
2024.07.26 11:21:57.084977 [ 1612 ] {} <Warning> test_xrb1u51c.tbl2 (585d5243-2829-4c58-be87-2fdc8e2b61e5): Removing temporary directory /var/lib/clickhouse/disks/s3/store/585/585d5243-2829-4c58-be87-2fdc8e2b61e5/tmp_restore_all_1_1_0-192d2bf6-0929-4b3e-b54a-c3e2f78a27a0/
2024.07.26 11:21:57.085034 [ 1612 ] {} <Warning> test_xrb1u51c.tbl2 (585d5243-2829-4c58-be87-2fdc8e2b61e5): Since zero-copy replication is enabled we are not going to remove blobs from shared storage for /var/lib/clickhouse/disks/s3/store/585/585d5243-2829-4c58-be87-2fdc8e2b61e5/tmp_restore_all_1_1_0-192d2bf6-0929-4b3e-b54a-c3e2f78a27a0/
```
And restore failed
```
2024.07.26 11:21:57.667618 [ 33385 ] {06b2a03a-4430-4d2a-92e7-fdf12b4fbfaf} <Error> test_xrb1u51c.tbl2 (585d5243-2829-4c58-be87-2fdc8e2b61e5): Part /var/lib/clickhouse/disks/s3/store/585/585d5243-2829-4c58-be87-2fdc8e2b61e5/tmp_restore_all_1_1_0-192d2bf6-0929-4b3e-b54a-c3e2f78a27a0/ is broken and needs manual correction
2024.07.26 11:21:57.667730 [ 33385 ] {06b2a03a-4430-4d2a-92e7-fdf12b4fbfaf} <Error> test_xrb1u51c.tbl2 (585d5243-2829-4c58-be87-2fdc8e2b61e5): Failed to restore part all_1_1_0 because it's broken. You can skip broken parts while restoring by setting 'restore_broken_parts_as_detached = true'
2024.07.26 11:21:57.708863 [ 33898 ] {} <Error> BackupsWorker: Failed to restore from backup Disk('backups', '03032_async_backup_restore_test_xrb1u51c'): Code: 107. DB::ErrnoException: Cannot open file /var/lib/clickhouse/disks/s3/store/585/585d5243-2829-4c58-be87-2fdc8e2b61e5/tmp_restore_all_1_1_0-192d2bf6-0929-4b3e-b54a-c3e2f78a27a0/a.bin: , errno: 2, strerror: No such file or directory: columns: columns format version: 1

```

### PR DESCRIPTION
**Pull request by vitlibar**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Protect temporary part directories from removing during RESTORE.

After https://github.com/ClickHouse/ClickHouse/pull/66881 and before this PR some temporary part directories created by `RESTORE` could be removed by `clearOldTemporaryDirectories()` before they were attached. That caused `RESTORE` to fail with a error like
```
2024.07.26 11:21:57.708863 [ 33898 ] {} <Error> BackupsWorker: Failed to restore from backup Disk('backups', '03032_async_backup_restore_test_xrb1u51c'): Code: 107. DB::ErrnoException: Cannot open file /var/lib/clickhouse/disks/s3/store/585/585d5243-2829-4c58-be87-2fdc8e2b61e5/tmp_restore_all_1_1_0-192d2bf6-0929-4b3e-b54a-c3e2f78a27a0/a.bin: , errno: 2, strerror: No such file or directory: columns: columns format version: 1
```

This PR fixes that and protect temporary part directories `tmp_restore_*` from removing before they are attached to a table.

This PR closes https://github.com/ClickHouse/ClickHouse/issues/67220

### CODE REVIEW

**Comment by robot-ch-test-poll4** [comment]
*This is an automated comment for commit 75f3247f32a610a6a8c7c350165b1671332971f5 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/67491/75f3247f32a610a6a8c7c350165b1671332971f5/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/dea79dc2bbcdb7ffc33b6b2e535e898eda16eab4/docs_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Review by davenger — APPROVED** [review]

**Comment by vitlibar** [comment]
CI failures:
- [Logical error: Unexpected error for async deduplicated insert](https://s3.amazonaws.com/clickhouse-test-reports/67491/d421636a5fdc3b73fa5cb05e83529483d69e75e2/stateless_tests__msan__[1_4].html) - is known (https://github.com/ClickHouse/clickhouse-core-incidents/issues/24#issuecomment-2260922179)
- [test_replicated_table_attach/test.py::test_startup_with_small_bg_pool_partitioned](https://s3.amazonaws.com/clickhouse-test-reports/67491/d421636a5fdc3b73fa5cb05e83529483d69e75e2/integration_tests__aarch64__[1_6].html) - must be fixed already (https://github.com/ClickHouse/ClickHouse/issues/60217)

**Comment by divanik** [comment]
Closes #67328

**Comment by divanik** [comment]
Closes #67328

**Pull request merged**
