### PR TITLE
Strict taskstats parser

### PR DESCRIPTION
**Pull request by azat**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

This will unhide possible issues (since sometimes statistics is
inaccurate).

Also before this patch TASKSTATS_TYPE_AGGR_TGID had been handled, while
it not correct to take into account, but it was not requested anyway.

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
Waiting for #36337

**Comment by azat** [comment]
>[Stress test (memory, actions) — Hung check failed](https://s3.amazonaws.com/clickhouse-test-reports/36351/2873670650841318e07b01a6040a43acb5478820/stress_test__memory__actions_.html)

```
2022.04.18 00:30:43.762385 [ 1058 ] {} <Error> static void DB::WriteBufferFromS3::finalizeCacheIfNeeded(std::optional<FileSegmentsHolder> &): Code: 49. DB::Exception: Cache writer not initialized. (LOGICAL_ERROR), Stack trace (when copying this message, always include the lines below):
```

- #36140 / #36171

And for backward server

```
2022.04.18 00:35:33.797021 [ 88920 ] {} <Error> Application: Code: 115. DB::Exception: Setting enable_filesystem_cache_on_write_operations is neither a builtin setting nor started with the prefix 'custom_' registered for user-defined settings: while parsing profile 'default' in users configuration file: while loading configuration file '/etc/clickhouse-server/users.xml'. (UNKNOWN_SETTING), Stack trace (when copying this message, always include the lines below):
```

>[Stress test (thread, actions) — Hung check failed](https://s3.amazonaws.com/clickhouse-test-reports/36351/2873670650841318e07b01a6040a43acb5478820/stress_test__thread__actions_.html)

SIGSEGV, but no details (in gdb too)

Will try to take a look deeper, in mean time will do a rebase.

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
Tests are broken in master and this PR is reverted.
Please resubmit again.

**Comment by azat** [comment]
@alexey-milovidov which tests are broken?

**Pull request merged**
