### PR TITLE
Revert "Disable some flappy tests"

### PR DESCRIPTION
**Pull request by excitoon**
This reverts commit e6958c0e498e595099836651f083e9a639a40775.

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Non-significant (changelog entry is not required)

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
@excitoon Please enable edits for your branch.

**Comment by alexey-milovidov** [comment]
Still flaps.

**Comment by alexey-milovidov** [comment]
Still failed.

**Comment by alexey-milovidov** [comment]
?

**Comment by alexey-milovidov** [comment]
Still failing.

**Comment by excitoon** [comment]
I hope these test to start pass after #10588

**Comment by alexey-milovidov** [comment]
They did not.

**Review by alesapin — APPROVED** [review]
Ok

**Comment by alexey-milovidov** [comment]
Still failed, will revert.

https://clickhouse-test-reports.s3.yandex.net/11313/26100b64deb4718be61965ee4f517fb0bed7edb9/performance_comparison/report.html#fail1

https://clickhouse-test-reports.s3.yandex.net/10678/1b0c9fae6cfaa8e3bfdfc6ba494179f2f4fc14ee/integration_tests_(asan).html#fail1

**Comment by alexey-milovidov** [comment]
And

https://clickhouse-test-reports.s3.yandex.net/11315/3574dfe1db3e3d2bdaab1346b948357e6a9a1ec7/integration_tests_(asan).html#fail1

**Comment by alexey-milovidov** [comment]
And

https://clickhouse-test-reports.s3.yandex.net/11318/70eaae38f2fe5c91d6a43b5166df623996826042/integration_tests_(asan).html#fail1

**Pull request merged**
