### PR TITLE
Enable random CPU migrations around mutex ops

### PR DESCRIPTION
**Pull request by alexey-milovidov**
Changelog category (leave one):
- Build/Testing/Packaging Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Not for merge. Only to test how it will work in CI.

### CODE REVIEW

**Comment by qoega** [comment]
https://clickhouse-test-reports.s3.yandex.net/9813/622bca235848bf1a7950d6eeb10241204aa069eb/stress_test_(thread)/stderr.log

```
ThreadSanitizer: data race

    #6 DB::TablesBlockSource::generate() /build/obj-x86_64-linux-gnu/../dbms/src/Storages/System/StorageSystemTables.cpp:258:41 (clickhouse+0xf6a561d)

and

    #5 DB::DatabaseOnDisk::renameTable(DB::Context const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::IDatabase&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::TableStructureWriteLockHolder&) /build/obj-x86_64-linux-gnu/../dbms/src/Databases/DatabaseOnDisk.cpp:229:16 (clickhouse+0xfbaa24d)

```

**Comment by qoega** [comment]
@Mergifyio update

**Comment by nikitamikhaylov** [comment]
@Mergifyio update

**Comment by qoega** [comment]
@Mergifyio update

**Comment by alexey-milovidov** [comment]
@Mergifyio update

**Comment by alexey-milovidov** [comment]
@Mergifyio update

**Comment by alexey-milovidov** [comment]
@Mergifyio update

**Comment by alexey-milovidov** [comment]
@mergifyio update

**Pull request closed without merging**
