### PR TITLE
Update libhdfs3: add log for slow read operations

### PR DESCRIPTION
**Pull request by liubingxing**
Changelog category (leave one):

Improvement
Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Add log for slow read operations

### CODE REVIEW

**Review by tavplubix — CHANGES_REQUESTED** [review]
1. If you want to add some logs to ClickHouse, then you should use ClickHouse logging system (see `LOG_TRACE/LOG_DEBUG/etc` macros). Logging something from a third-party library is not allowed.
2. Consider using `ProfileEvents` instead of text logs

**Comment by taiyang-li** [comment]
@tavplubix  We intended to add logs just inside libhdfs3. It is useful for debugging in production environment as concurrency access of HDFS may cause slow read.

**Comment by tavplubix** [comment]
But we don't need changes in https://github.com/ClickHouse/libhdfs3 unless these changes are useful for https://github.com/ClickHouse/ClickHouse

**Comment by taiyang-li** [comment]
> But we don't need changes in https://github.com/ClickHouse/libhdfs3 unless these changes are useful for https://github.com/ClickHouse/ClickHouse

It's useful for those table engines based on HDFS. Sometimes reading remote HDFS files is rather slow, and those logs would help optimize HDFS systems.

**Comment by tavplubix** [comment]
> It's useful for those table engines based on HDFS.

Profile events would be much more useful for table engines based on HDFS

> Sometimes reading remote HDFS files is rather slow, and those logs would help tuning HDFS systems. It is necessary in production.

`libhdfs3` will write logs to an unknown location. How am I supposed to find these logs on production in a cloud environment with some Docker containers or Kubernetes, for example? All logs must be written through ClickHouse logging system

**Comment by taiyang-li** [comment]
> 

libhdfs3 logs are written to stdout.log, which is part of CH logging system.

**Comment by tavplubix** [comment]
> which is part of CH logging system

It is not. ClickHouse logging system writes logs through `OwnSplitChannel` to a configurable location (usually `/var/log/clickhouse-server/`) and (optionally) to `system.text_log`. Yes, it also can write logs to stderr, but it's not a common usecase. Can I configure libhdfs3 to write logs to `/var/log/clickhouse-server/` and `system.text_log`?

**Comment by alexey-milovidov** [comment]
We don't allow logs to stderr.

**Comment by zhanglistar** [comment]
It's OK, we will contribute code of slow IO optimization.

**Pull request closed without merging**
