### PR TITLE
Fix CLion

### LINKED ISSUE #66994: When editing a file in CLion, it freezes for a minute on every keypress
CLion is an IDE for C++ from Jetbrains.
It is written in Java, and it is one of the most bizarre and convoluted pieces of engineering ever created.
It has many bugs and it barely works at all.

But there is a workaround:
https://www.jetbrains.com/help/clion/detecting-origin-of-cmake-invocation.html

### PR DESCRIPTION
**Pull request by alexey-milovidov**
### Changelog category (leave one):
- Build/Testing/Packaging Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Allow to use CLion with ClickHouse. In previous versions, CLion freezed for a minute on every keypress. This closes #66994.

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-clickhouse-ci-1** [comment]
*This is an automated comment for commit 385dabaa19a41a703d549925aeb6c9ecc9c0a493 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/66995/385dabaa19a41a703d549925aeb6c9ecc9c0a493/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/65521/9d7bb2a430b142e0761cc30efcf78ea1bbeb6871/docs_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Review by nikitamikhaylov — APPROVED** [review]

**Comment by nikitamikhaylov** [comment]
Interesting, what will be if you will press "Build" button in the CLion? Will it break? Or this invocation counts as one done from terminal?

**Comment by alexey-milovidov** [comment]
Build works fine - it invokes the usual build command, and that macro is only related to CLion's internal parser/analysis. The only downside is that there is no autocomplete for settings, and it highlights an error under the `.` symbol.

**Comment by alexey-milovidov** [comment]
Needs #67173.

**Pull request merged**
