### PR TITLE
Fix one more race in TestKeeper

### PR DESCRIPTION
**Pull request by alesapin**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Race example: https://clickhouse-test-reports.s3.yandex.net/0/52f570c28a2ed76742223c7fd7c081b50469b0a9/stress_test_(thread).html#fail1

The race happens during normal session close. This callback https://github.com/ClickHouse/ClickHouse/blob/master/src/Server/TestKeeperTCPHandler.cpp#L313-L318 called by `Storage` thread when a response is ready to be sent to the client. When `TestKeeperTCPHandler` sees `close` response https://github.com/ClickHouse/ClickHouse/blob/master/src/Server/TestKeeperTCPHandler.cpp#L357-L361 it just finishes (we don't need to send `close` to the client). So the race happens on callback call for `close` response. We add it to the `responses` queue and sleep for some time. At this moment `TestKeeperTCPHandler` thread pops this response from the responses queue and finishes. After that storage thread wakes up and tries to write the signaling byte into a closed descriptor: https://github.com/ClickHouse/ClickHouse/blob/master/src/Server/TestKeeperTCPHandler.cpp#L317. 
The race happened because of inconsistency between signaling pipe fd and responses queue. This fix makes them consistent (now we process only responses that were read from signaling pipe fd).

### CODE REVIEW

**Review by nikitamikhaylov — APPROVED** [review]

**Comment by alesapin** [comment]
Asan reported https://github.com/ClickHouse/ClickHouse/issues/19441

**Comment by alesapin** [comment]
`test_materialize_mysql_database/test.py::test_select_without_columns_8_0` known flaky.

**Comment by alesapin** [comment]
Fuzzer debug: 
`2021.01.22 16:28:15.128031 [ 82 ] {} <Fatal> Application: Child process was terminated by signal 11.`
And nothing more.

**Comment by alesapin** [comment]
ubsan reported https://github.com/ClickHouse/ClickHouse/issues/19457

**Pull request merged**
