### PR TITLE
Fix `02944_dynamically_change_filesystem_cache_size`

### PR DESCRIPTION
**Pull request by evillique**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Broken after https://github.com/ClickHouse/ClickHouse/pull/57732

### CODE REVIEW

**Comment by robot-ch-test-poll** [comment]
*This is an automated comment for commit be901bee5b572fc93799a6662a0ef10252ad931d with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/58445/be901bee5b572fc93799a6662a0ef10252ad931d/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/58445/be901bee5b572fc93799a6662a0ef10252ad931d/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Comment by bharatnc** [comment]
Thank you for fixing, I just noticed this build fail in my other PR.

**Comment by qoega** [comment]
Something was broken really bad
```
2024.01.03 06:07:35.982593 [ 152682 ] {} <Fatal> BaseDaemon: (version 24.1.1.1, build id: 0BE79DF0DCA61A3CB62B4E325A6EA49A8522F6FC, git hash: a4ad8c3abb6e46f16815df22dc6c10cb63e6942d) (from thread 154172) Terminate called for uncaught exception:
2024.01.03 06:07:35.982676 [ 152682 ] {} <Fatal> BaseDaemon: Code: 210. DB::NetException: I/O error: Broken pipe, while writing to socket ([::ffff:127.0.0.1]:8123 -> [::ffff:127.0.0.1]:33914). (NETWORK_ERROR), Stack trace (when copying this message, always include the lines below):
2024.01.03 06:07:35.982723 [ 152682 ] {} <Fatal> BaseDaemon:
2024.01.03 06:07:35.982755 [ 152682 ] {} <Fatal> BaseDaemon: 0. ./contrib/llvm-project/libcxx/include/exception:134: Poco::Exception::Exception(String const&, int) @ 0x000000000dc1fd12 in /fasttest-workspace/build/programs/clickhouse
2024.01.03 06:07:35.982779 [ 152682 ] {} <Fatal> BaseDaemon: 1. /fasttest-workspace/build/./src/Common/Exception.cpp:96: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x0000000007a3f637 in /fasttest-workspace/build/programs/clickhouse
2024.01.03 06:07:35.982808 [ 152682 ] {} <Fatal> BaseDaemon: 2. ./contrib/llvm-project/libcxx/include/string:1499: DB::NetException::NetException<String, String, String>(int, FormatStringHelperImpl<std::type_identity<String>::type, std::type_identity<String>::type, std::type_identity<String>::type>, String&&, String&&, String&&) @ 0x0000000007c6f8de in /fasttest-workspace/build/programs/clickhouse
2024.01.03 06:07:35.982856 [ 152682 ] {} <Fatal> BaseDaemon: 3. /fasttest-workspace/build/./src/IO/WriteBufferFromPocoSocket.cpp:0: DB::WriteBufferFromPocoSocket::nextImpl() @ 0x0000000007c6f107 in /fasttest-workspace/build/programs/clickhouse
2024.01.03 06:07:35.982878 [ 152682 ] {} <Fatal> BaseDaemon: 4. ./src/Server/HTTP/HTTPServerResponse.h:166: DB::HTTPWriteBuffer::nextImplChunked() @ 0x000000000d20f469 in /fasttest-workspace/build/programs/clickhouse
2024.01.03 06:07:35.983351 [ 152682 ] {} <Fatal> BaseDaemon: 5. ./src/Server/HTTP/HTTPServerResponse.h:0: DB::WriteBufferFromHTTPServerResponse::nextImpl() @ 0x000000000d20eaaa in /fasttest-workspace/build/programs/clickhouse
2024.01.03 06:07:35.983384 [ 152682 ] {} <Fatal> BaseDaemon: 6. ./src/IO/WriteBuffer.h:65: DB::HTTPWriteBuffer::finalizeImpl() @ 0x000000000d20f37a in /fasttest-workspace/build/programs/clickhouse
2024.01.03 06:07:35.983465 [ 152682 ] {} <Fatal> BaseDaemon: 7. /fasttest-workspace/build/./src/Server/HTTP/WriteBufferFromHTTPServerResponse.cpp:0: DB::WriteBufferFromHTTPServerResponse::finalizeImpl() @ 0x000000000d20f16c in /fasttest-workspace/build/programs/clickhouse
2024.01.03 06:07:35.983503 [ 152682 ] {} <Fatal> BaseDaemon: 8. DB::WriteBuffer::finalize() @ 0x0000000002e2d90e in /fasttest-workspace/build/programs/clickhouse
2024.01.03 06:07:35.983522 [ 152682 ] {} <Fatal> BaseDaemon: 9. /fasttest-workspace/build/./src/Server/HTTP/WriteBufferFromHTTPServerResponse.cpp:157: DB::WriteBufferFromHTTPServerResponse::~WriteBufferFromHTTPServerResponse() @ 0x000000000d20f089 in /fasttest-workspace/build/programs/clickhouse
2024.01.03 06:07:35.983536 [ 152682 ] {} <Fatal> BaseDaemon: 10. ./src/Server/HTTPHandler.h:94: DB::HTTPHandler::trySendExceptionToClient(String const&, int, DB::HTTPServerRequest&, DB::HTTPServerResponse&, DB::HTTPHandler::Output&) @ 0x000000000d19b9fc in /fasttest-workspace/build/programs/clickhouse
2024.01.03 06:07:35.983556 [ 152682 ] {} <Fatal> BaseDaemon: 11. ./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:290: DB::HTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&, StrongTypedef<unsigned long, ProfileEvents::EventTag> const&) @ 0x000000000d19da0a in /fasttest-workspace/build/programs/clickhouse
2024.01.03 06:07:35.983607 [ 152682 ] {} <Fatal> BaseDaemon: 12. ./base/poco/Foundation/include/Poco/AutoPtr.h:205: DB::HTTPServerConnection::run() @ 0x000000000d20a699 in /fasttest-workspace/build/programs/clickhouse
2024.01.03 06:07:35.983622 [ 152682 ] {} <Fatal> BaseDaemon: 13. /fasttest-workspace/build/./base/poco/Net/src/TCPServerConnection.cpp:57: Poco::Net::TCPServerConnection::start() @ 0x000000000dc0e2c7 in /fasttest-workspace/build/programs/clickhouse
2024.01.03 06:07:35.983714 [ 152682 ] {} <Fatal> BaseDaemon: 14. ./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:48: Poco::Net::TCPServerDispatcher::run() @ 0x000000000dc0e7ad in /fasttest-workspace/build/programs/clickhouse
2024.01.03 06:07:35.983734 [ 152682 ] {} <Fatal> BaseDaemon: 15. /fasttest-workspace/build/./base/poco/Foundation/src/ThreadPool.cpp:202: Poco::PooledThread::run() @ 0x000000000dc73ec7 in /fasttest-workspace/build/programs/clickhouse
2024.01.03 06:07:35.983750 [ 152682 ] {} <Fatal> BaseDaemon: 16. ./base/poco/Foundation/include/Poco/SharedPtr.h:139: Poco::ThreadImpl::runnableEntry(void*) @ 0x000000000dc71a02 in /fasttest-workspace/build/programs/clickhouse
2024.01.03 06:07:35.983762 [ 152682 ] {} <Fatal> BaseDaemon:  (version 24.1.1.1)
```

**Review by tavplubix — APPROVED** [review]

**Comment by tavplubix** [comment]
> Something was broken really bad

Related to https://github.com/ClickHouse/ClickHouse/pull/56064, @yakov-olkhovskiy please take a look

**Pull request merged**
