### PR TITLE
Added ASK_PASSWORD client constant instead of hardcoded '\n'

### PR DESCRIPTION
**Pull request by Demilivor**
Added ASK_PASSWORD client constant instead of hardcoded '\n'.

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by Demilivor** [comment]
Please review the changes add the label can be tested.

**Comment by robot-ch-test-poll3** [comment]
This is an automated comment for commit 25948cdd9e6ba2523cd293a66ac83f273c953a9d with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/51723/25948cdd9e6ba2523cd293a66ac83f273c953a9d/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Comment by alexey-milovidov** [comment]
Why don't we use a separate variable for that?

**Comment by Demilivor** [comment]
> Why don't we use a separate variable for that?

ClickHouse client already has an option `--ask-password`. Convert `--password` without argument to `--ask-password` in `Client.cpp` will work, but will result in incomprehensible error descriptions for the user:

```bash
clickhouse-client --password --password 'pass'
ClickHouse client version 23.6.1.1.
Code: 36. DB::Exception: Specified both --password and --ask-password. Remove one of them. (BAD_ARGUMENTS)
```

**Review by alexey-milovidov — APPROVED** [review]

**Review by alexey-milovidov — APPROVED** [review]

**Pull request merged**
