### PR TITLE
Add avx512 support for Aggregate Sum, function unary arithmetic, func…

### PR DESCRIPTION
**Pull request by zzachimed**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Add avx512 support for Aggregate Sum, function unary arithmetic, function comparison

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/
Add avx512 support for Aggregate Sum, function unary arithmetic, function comparison

### CODE REVIEW

**Comment by kitaisreal** [comment]
@zzachimed it was not added on purpose.
AVX512 can be slower than AVX2 (we can combine dispatch with statistics collection, please check how this is done for functions). AVX512 can also produce downclock side effects for old processors https://stackoverflow.com/questions/56852812/simd-instructions-lowering-cpu-frequency. We have pull request where AVX512 is enabled by default and you can see that a lof of queries are slower https://github.com/ClickHouse/ClickHouse/pull/34071.

Such specializations also could introduce additional code bloat, currently each such loop wrapped in DISPATCH is instantiated in some places many times, so it is better to only enable AVX512F or AVX512BW.

From tests I see that it could make sense for some functions like `roundDuration` (AVX512 has special instruction that can do that) or compare functions.
Lets investigate if https://s3.amazonaws.com/clickhouse-test-reports/37870/824656a3c73a89a4e45a7c2fd0a52b4d1ef127c9/performance_comparison_[1/4]/report.html performance degradations are related to changes.

**Comment by zzachimed** [comment]
> @zzachimed it was not added on purpose. AVX512 can be slower than AVX2 (we can combine dispatch with statistics collection, please check how this is done for functions). AVX512 can also produce downclock side effects for old processors https://stackoverflow.com/questions/56852812/simd-instructions-lowering-cpu-frequency. We have pull request where AVX512 is enabled by default and you can see that a lof of queries are slower #34071.
> 
> Such specializations also could introduce additional code bloat, currently each such loop wrapped in DISPATCH is instantiated in some places many times, so it is better to only enable AVX512F or AVX512BW.
> 
> From tests I see that it could make sense for some functions like `roundDuration` (AVX512 has special instruction that can do that) or compare functions. Lets investigate if [https://s3.amazonaws.com/clickhouse-test-reports/37870/824656a3c73a89a4e45a7c2fd0a52b4d1ef127c9/performance_comparison_[1/4]/report.html](https://s3.amazonaws.com/clickhouse-test-reports/37870/824656a3c73a89a4e45a7c2fd0a52b4d1ef127c9/performance_comparison_%5B1/4%5D/report.html) performance degradations are related to changes.

@kitaisreal :
  Maybe in your CI enviroment test avx512.  you can reference this :"root@icx-08:~# cpupower idle-set -d c2" "root@icx-08:~# cpupower frequency-set -d 3100000 -u 3100000 -g performance" . disable some idle state ,let cpu not go in to some deep sleep. and also let cpu run in fixed frequence.

**Comment by alexey-milovidov** [comment]
Thank you! CI shows significant improvement on many tests!

**Comment by alexey-milovidov** [comment]
Screenshot_20230219_152213
Screenshot_20230219_152154
Screenshot_20230219_152130

And the average improvement (across all relevant and irrelevant tests) is >1%.

**Comment by tavplubix** [comment]
Seems like PerformanceComparison started to fail with OOM after this PR:
```
2023-02-19T22:17:04.4761030Z 2023-02-20 01:17:04	 + numactl --cpunodebind=all --membind=all parallel --jobs 12 --joblog analyze/parallel-log.txt --null
2023-02-19T22:18:11.8831152Z /home/ubuntu/actions-runner/_work/_temp/0921cb20-4c12-4a1a-8e3c-393d26ed9403.sh: line 5: 2913775 Killed                  python3 performance_comparison_check.py "$CHECK_NAME"
2023-02-19T22:18:12.2363616Z ##[error]Process completed with exit code 137.
```
Examples: https://github.com/ClickHouse/ClickHouse/actions/runs/4216671729/jobs/7322508568, https://github.com/ClickHouse/ClickHouse/actions/runs/4219206954/jobs/7325746806

We can simply reduce the number of threads (https://github.com/ClickHouse/ClickHouse/pull/46599), but maybe it makes sense to take a look and try to investigate why it fails.

**Pull request merged**
