### PR TITLE
Add CapnProto output format, refactor CapnProto input format

### PR DESCRIPTION
**Pull request by Avogar**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- New Feature

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Add CapnProto output format, refactor CapnProto input format.

Detailed description / Documentation draft:

Add CapnProto output format, avoid possible LogicalError in CapnProto input format by removing logic with Fields and adding more type checks.

CapnProto and ClickHouse data types matching:

| CapnProto data type (`INSERT`) | ClickHouse data type | CapnProto data type (`SELECT`)  |
|---------------------------------------------|------------------------------|-----------------------------------------------|
| UInt8, bool                                   | UInt8                           | UInt8                                              |
| UInt16                                          | UInt16, Date               | UInt16                                            |
| UInt32                                          | UInt32, DateTime       | UInt32                                            |
| UInt64                                          | UInt64                         | UInt64                                            |
| Int8                                               | Int8                             | Int8                                                 |
| Int16                                             | Int16                           | Int16                                               |
| Int32                                             | Int32                           | Int32                                               |
| Int64                                             | Int64, DateTime64      | Int64                                               |
| Float32                                         | Float32                       | Float32                                           |
| Float64                                         | Float64                       | Float64                                           |
| Text, Data                                     | String, FixedString     | Text, Data                                       |
| List                                               | Array                           | List                                                 |
| Enum                                            | Enum8, Enum16        | Enum                                             |
| union(T, Void), union(Void, T)       | Nullable(T)                 | union(T, Void), union(Void, T)        |
| struct                                             | Tuple                         | struct                                              |

For working with Enum in CapnProto format there is a new setting, that determines how to map ClickHouse Enum and CapnProto Enum from schema. It has 3 values:
- `by_values`: values in Enums should be the same, names can be different.
- `by_names`: names in enums should be the same, values can be different.
- `by_name_case_insensitive`:  names in enums should be the same case-insensitive, values can be different.

### CODE REVIEW

**Comment by Avogar** [comment]
Will add tests a bit later

**Comment by Avogar** [comment]
@Mergifyio update

**Comment by Avogar** [comment]
@Mergifyio update

**Review by novikd — APPROVED** [review]
LGTM. You should also add tests for nested structures.

**Comment by novikd** [comment]
I was talking about nested declarations, i.e.:
```
struct Person {
  name @0 :Text;
  birthdate @3 :Date;

  email @1 :Text;
  phones @2 :List(PhoneNumber);

  struct PhoneNumber {
    number @0 :Text;
    type @1 :Type;

    enum Type {
      mobile @0;
      home @1;
      work @2;
    }
  }
}
```
CapnProto website says it's [a valid code](https://capnproto.org/language.html).

**Pull request merged**
