### PR TITLE
SummingMergeTree support for DateTime64

### LINKED ISSUE #49938: SummingMergeTree support for DateTime64
**Describe the unexpected behaviour**

When using a `DateTime64` in a `SummingMergeTree` on a column that is not part of the sorting key or a summarizable field. You get the following error on insert time:

```
Received exception from server (version 23.5.1):
Code: 43. DB::Exception: Received from localhost:9000. DB::Exception: Illegal type DateTime64(3) of argument for aggregate function sumWithOverflow. (ILLEGAL_TYPE_OF_ARGUMENT)
(query: INSERT INTO summ.landing SELECT 1 pk, now64(3) timestamp, 1 value;)
```

This was discovered in CH 22.8 but is also happening in master.

**How to reproduce**

To reproduce the issue:

```sql
DROP DATABASE IF EXISTS summ;
CREATE DATABASE summ;

CREATE TABLE summ.landing ( `pk` UInt64, `timestamp` DateTime64(3), `value` UInt64)
ENGINE = SummingMergeTree() ORDER BY pk;

INSERT INTO summ.landing SELECT 1 pk, now64(3) timestamp, 1 value;
INSERT INTO summ.landing SELECT 1 pk, now64(3) timestamp, 2 value;
INSERT INTO summ.landing SELECT 1 pk, now64(3) timestamp, 3 value;
INSERT INTO summ.landing SELECT 1 pk, now64(3) timestamp, 4 value;
INSERT INTO summ.landing SELECT 1 pk, now64(3) timestamp, 5 value;

SELECT * FROM summ.landing FINAL FORMAT PrettyCompact;
```

**Expected behavior**

I'd expect the DateTime64 column to behave in a similar way to how DateTime behaves, the column is not summarized, and an arbitrary value gets selected.

See:

```sql
DROP DATABASE IF EXISTS summ;
CREATE DATABASE summ;

CREATE TABLE summ.landing ( `pk` UInt64, `timestamp` DateTime, `value` UInt64)
ENGINE = SummingMergeTree() ORDER BY pk;

INSERT INTO summ.landing SELECT 1 pk, now() timestamp, 1 value;
INSERT INTO summ.landing SELECT 1 pk, now() timestamp, 2 value;
INSERT INTO summ.landing SELECT 1 pk, now() timestamp, 3 value;
INSERT INTO summ.landing SELECT 1 pk, now() timestamp, 4 value;
INSERT INTO summ.landing SELECT 1 pk, now() timestamp, 5 value;

SELECT * FROM summ.landing FINAL FORMAT PrettyCompact;

```

=> 

```
┌─pk─┬───────────timestamp─┬─value─┐
│  1 │ 2023-05-17 09:21:08 │    15 │
└────┴─────────────────────┴───────┘
```

### PR DESCRIPTION
**Pull request by jrdi**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Fix SummingMergeTree support for DateTime64. Previously, SummingSortingAlgorithm.cpp was considering DateTime64 type as summable.

Setting DateTime64 as not summable fixes the issue but could potentially change behavior in some other places. Let's see what the CI reports.

Closes #49938

### CODE REVIEW

**Comment by den-crane** [comment]
I would also add some negative tests, that DateTime64 is not summable.

Though it's already throws errors

```
select sum(now64(3));
 DB::Exception: Illegal type DateTime64(3) of argument for aggregate function sum. (ILLEGAL_TYPE_OF_ARGUMENT)

select now64(3) + now64(3);
DB::Exception: Illegal types DateTime64(3) and DateTime64(3) of arguments of function plus: While processing now64(3) + now64(3)
```

**Comment by robot-clickhouse-ci-1** [comment]
This is an automated comment for commit f8791a0ea393120dbfba8eec8627edbc8d00deb8 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/50797/f8791a0ea393120dbfba8eec8627edbc8d00deb8/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
LGTM, but the tests are broken - need to be fixed first.

**Comment by jrdi** [comment]
I have been reviewing test failures and are unrelated to this PR changes.

**Review by alexey-milovidov — APPROVED** [review]

**Pull request merged**
