### PR TITLE
Try fix perftests.

### PR DESCRIPTION
**Pull request by KochetovNicolai**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by traceon** [comment]
Just noticed this PR. Thanks.

**Comment by KochetovNicolai** [comment]
Let's wait for perftests.

**Comment by traceon** [comment]
Maybe it is worth reducing the amount data?

**Comment by traceon** [comment]
> Maybe it is worth reducing the amount of data?

Pushed in #21442.

**Pull request merged**
