### PR TITLE
Add a note about potential caveats for the "session_timezone" setting

### PR DESCRIPTION
**Pull request by alexey-milovidov**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
The `session_timezone` setting is demoted to experimental.

### CODE REVIEW

**Comment by robot-ch-test-poll3** [comment]
This is an automated comment for commit 9a5aed35e24a9aa4d7de71971665449cf344f917 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/52445/9a5aed35e24a9aa4d7de71971665449cf344f917/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Comment by den-crane** [comment]
It's really important feature. All other databases has it. 
I don't understand how users use Clickhouse with BI systems without it.

Right now all my SQL queries stuffed with macro `{ui_timezone}`
Some SQL queries have 20 timezone macro substitution.

```
  tuple(nullIf(toDate(toTimeZone(utc_access_hour, 'US/Eastern')), toDate(0)))  as `ctuple_null_135`
...
      (utc_access_hour <= toDateTime('2023-07-22 23:00:00', 'US/Eastern'))
  AND  (utc_access_hour >= toDateTime('2023-07-22 00:00:00', 'US/Eastern'))
```
I was going to replace this boilerplate with one pass `session_timezone` to the SQL session.

**Comment by zvonand** [comment]
I will take a deeper look into potential problems that may occur.

**Comment by zvonand** [comment]
> due to potential caveats

Which caveats do you mean?

**Comment by alexey-milovidov** [comment]
It can affect the server's logic unrelated to user queries.
It has been demonstrated by randomized testing: #52325

**Comment by filimonov** [comment]
> It has been demonstrated by randomized testing: https://github.com/ClickHouse/ClickHouse/pull/52325

Problems of the same nature appear when the server timezone gets changed, indexes with time functions stop working correctly etc.  So it's not something new, but once it becomes more dynamic the problem becomes more obvious/visible.

**Pull request merged**
