### PR TITLE
ISSUES-8317 fix negative with bloom filter

### LINKED ISSUE #8317: BloomFilter index couldn't find negative integers.
BloomFilter index is very fast and awesome feature of ClickHouse. 
But, there was an unexpected behavior.
It seems not to handle negative integers.
If you want to reproduce this bug, follow below queries.

**Create a test table and insert a negative integer**
```SQL
SET allow_experimental_data_skipping_indices = 1;

CREATE TABLE bf_int
(
    `id` int,
    `i` int,
    INDEX idx i TYPE bloom_filter(0.01) GRANULARITY 8192
)
ENGINE = MergeTree()
ORDER BY id;

INSERT INTO bf_int VALUES (1, -1);
```

**Select with where statement for the negative integer**
```SQL
SELECT *
FROM bf_int
WHERE i = -1

Ok.

0 rows in set. Elapsed: 0.003 sec. 

```

The result for the `select` returned 0 row.

But, there must had been one row...

```SQL
SELECT *
FROM bf_int
FORMAT TSV

1       -1

1 rows in set. Elapsed: 0.002 sec. 
```

### PR DESCRIPTION
**Pull request by zhang2014**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category:
- Bug Fix

Changelog entry:
Fixed incorrect bloom filter results under negative. This fixes #8317.

Detailed description (optional):
#8317

### CODE REVIEW

**Comment by zhang2014** [comment]
Unit tests executed in parallel ? The only conceivable error could be caused by executing at the same time as [multi_nice_exception_msg](https://github.com/ClickHouse/ClickHouse/blob/master/dbms/src/Common/ZooKeeper/tests/gtest_zkutil_test_multi_exception.cpp#L29)

**Comment by zhang2014** [comment]
The `zkutil.multi_async` failure seems to have nothing to do with the this patch. But it shouldn't have happened. Do we need to look into why ?

BTW: Maybe should provide application log and commit log of zookeeper

**Comment by alexey-milovidov** [comment]
`zkutil.multi_async` is flacky test.

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alesapin** [comment]
conflict in 19.17

**Pull request merged**
