### PR TITLE
JIT compilation migration to LLVM 15

### LINKED ISSUE #41548: CHJIT::compileModule failed with use-of-uninitialized-value in stress tests
```
MemorySanitizer: use-of-uninitialized-value
    #0 0x49c05839 in llvm::iplist_impl<llvm::simple_ilist<llvm::MachineInstr, llvm::ilist_sentinel_tracking<true>>, llvm::ilist_traits<llvm::MachineInstr>>::~iplist_impl() MachineBasicBlock.cpp
    #1 0x49c05c5f in llvm::MachineBasicBlock::~MachineBasicBlock() (/usr/bin/clickhouse+0x49c05c5f) (BuildId: 
    ...
    #13 0x41784edf in DB::JITCompiler::compile(llvm::Module&) build_docker/../src/Interpreters/JIT/CHJIT.cpp:78:22
    #14 0x4178047d in DB::CHJIT::compileModule(std::__1::unique_ptr<llvm::Module, std::__1::default_delete<llvm::Module>>) build_docker/../src/Interpreters/JIT/CHJIT.cpp:378:29
    #15 0x4177f6ed in DB::CHJIT::compileModule(std::__1::function<void (llvm::Module&)>) build_docker/../src/Interpreters/JIT/CHJIT.cpp:359:24
    ...
```

[play ci](https://play.clickhouse.com/play?user=play#CiAgICBTRUxFQ1QKICAgICAgICByZXBsYWNlKGFueShyZXBvcnRfdXJsKSwgJy5odG1sJywgJy9zdGRlcnIubG9nJykgYXMgciwKICAgICAgICBjaGVja19uYW1lLAogICAgICAgIGdyb3VwQXJyYXlEaXN0aW5jdCh0ZXN0X25hbWUpIGFzIHRlc3QsCiAgICAgICAgY2hlY2tfc3RhcnRfdGltZSwKICAgICAgICBncm91cEFycmF5RGlzdGluY3QodGVzdF9zdGF0dXMpIGFzIHN0LAogICAgICAgIHN1YnN0cmluZyhjb21taXRfc2hhLCAxLCAxMCkgYXMgY29tbWl0X3Nob3J0LAogICAgICAgIHB1bGxfcmVxdWVzdF9udW1iZXIgYXMgcHJudW0KCiAgICBGUk9NIGNoZWNrcwogICAgV0hFUkUgdGVzdF9zdGF0dXMgbm90IGluICgnT0snLCAnU0tJUFBFRCcsICcnKQogICAgICAgIEFORCBjaGVja19uYW1lIGxpa2UgJyVTdHJlc3MgdGVzdCUnCiAgICAgICAgQU5EIHRlc3RfbmFtZSBpbGlrZSAnJVNhbml0aXplciUnCiAgICAgICAgQU5EIG5vdygpIC0gSU5URVJWQUwgJzMnIGRheSA8IGNoZWNrX3N0YXJ0X3RpbWUKICAgICAgICBBTkQgcHJudW0gPSAwCkdST1VQIEJZIHBybnVtLCBjaGVja19uYW1lLCBjb21taXRfc2hvcnQsIGNoZWNrX3N0YXJ0X3RpbWUKT1JERVIgQlkgY2hlY2tfc3RhcnRfdGltZSBERVNDCgoK)

### PR DESCRIPTION
**Pull request by kitaisreal**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Closes #41548.

### CODE REVIEW

**Comment by rschu1ze** [comment]
Unfortunately there are some errors, e.g.

https://s3.amazonaws.com/clickhouse-test-reports/42123/1fc7833538d7a3547bdae5ee11eab5ec9390b291/stateful_tests__debug_/clickhouse-server.log

```
2022.10.07 16:06:46.621514 [ 1236 ] {} <Fatal> BaseDaemon: ########################################
2022.10.07 16:06:46.621633 [ 1236 ] {} <Fatal> BaseDaemon: (version 22.10.1.1, build id: 1114F3DB38636A8EB4DB8FBFF97C6F266A9E2708) (from thread 734) (query_id: 8abee036-04af-48c0-9f6b-c51bc1e23479::202210_1_10_2) (query: ) Received signal Aborted (6)
2022.10.07 16:06:46.621738 [ 1236 ] {} <Fatal> BaseDaemon: 
2022.10.07 16:06:46.621880 [ 1236 ] {} <Fatal> BaseDaemon: Stack trace: 0x7f0b5646c00b 0x7f0b5644b859 0x7f0b5644b729 0x7f0b5645cfd6 0x1f910d24 0x1f91166d 0x274fc8d2 0x274f9534 0x274f89e8 0x274f899d 0x274f895d 0x274f891d 0x274f88e8 0x274dc81e 0x274d019d 0x274ce452 0x274f1e2c 0x28a4145f 0x28a4034f 0x28a3f652 0x28acdc4b 0x28aac298 0x28aab2f4 0x27f5e094 0x27f5df95 0x27f5dec3 0x27f5dd75 0x27f4a07b 0x27f40854 0x27f3e08c 0x27f56658 0x27f56635 0x27f56615 0x27f565f5 0x27f565bd 0x1f585eb6 0x1f585255 0x27f41da6 0x27f463d2 0x2833f792 0x27f6bdea
2022.10.07 16:06:46.622022 [ 1236 ] {} <Fatal> BaseDaemon: 4. raise @ 0x7f0b5646c00b in ?
2022.10.07 16:06:46.622111 [ 1236 ] {} <Fatal> BaseDaemon: 5. abort @ 0x7f0b5644b859 in ?
2022.10.07 16:06:46.622197 [ 1236 ] {} <Fatal> BaseDaemon: 6. ? @ 0x7f0b5644b729 in ?
2022.10.07 16:06:46.622282 [ 1236 ] {} <Fatal> BaseDaemon: 7. ? @ 0x7f0b5645cfd6 in ?
2022.10.07 16:06:46.860661 [ 1236 ] {} <Fatal> BaseDaemon: 8. /build/build_docker/../contrib/llvm-project/llvm/include/llvm/IR/Instructions.h:964: llvm::GetElementPtrInst::Create(llvm::Type*, llvm::Value*, llvm::ArrayRef<llvm::Value*>, llvm::Twine const&, llvm::Instruction*) @ 0x1f910d24 in /usr/bin/clickhouse
2022.10.07 16:06:47.004003 [ 926 ] {} <Trace> AsynchronousMetrics: MemoryTracking: was 1.78 GiB, peak 2.56 GiB, will set to 2.01 GiB (RSS), difference: 50.20 MiB
2022.10.07 16:06:47.098371 [ 1236 ] {} <Fatal> BaseDaemon: 9. /build/build_docker/../contrib/llvm-project/llvm/include/llvm/IR/Instructions.h:986: llvm::GetElementPtrInst::CreateInBounds(llvm::Type*, llvm::Value*, llvm::ArrayRef<llvm::Value*>, llvm::Twine const&, llvm::Instruction*) @ 0x1f91166d in /usr/bin/clickhouse
2022.10.07 16:06:47.296347 [ 1236 ] {} <Fatal> BaseDaemon: 10. /build/build_docker/../contrib/llvm-project/llvm/include/llvm/IR/IRBuilder.h:1759: llvm::IRBuilderBase::CreateInBoundsGEP(llvm::Type*, llvm::Value*, llvm::Value*, llvm::Twine const&) @ 0x274fc8d2 in /usr/bin/clickhouse
2022.10.07 16:06:47.493728 [ 1236 ] {} <Fatal> BaseDaemon: 11. /build/build_docker/../src/Interpreters/JIT/compileFunction.cpp:568: DB::compileSortDescription(llvm::Module&, DB::SortDescription&, std::__1::vector<std::__1::shared_ptr<DB::IDataType const>, std::__1::allocator<std::__1::shared_ptr<DB::IDataType const> > > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x274f9534 in /usr/bin/clickhouse
2022.10.07 16:06:47.687010 [ 1236 ] {} <Fatal> BaseDaemon: 12. /build/build_docker/../src/Interpreters/JIT/compileFunction.cpp:636: DB::compileSortDescription(DB::CHJIT&, DB::SortDescription&, std::__1::vector<std::__1::shared_ptr<DB::IDataType const>, std::__1::allocator<std::__1::shared_ptr<DB::IDataType const> > > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::$_2::operator()(llvm::Module&) const @ 0x274f89e8 in /usr/bin/clickhouse
2022.10.07 16:06:47.883451 [ 1236 ] {} <Fatal> BaseDaemon: 13. /build/build_docker/../contrib/libcxx/include/type_traits:3640: decltype(static_cast<DB::compileSortDescription(DB::CHJIT&, DB::SortDescription&, std::__1::vector<std::__1::shared_ptr<DB::IDataType const>, std::__1::allocator<std::__1::shared_ptr<DB::IDataType const> > > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::$_2&>(fp)(static_cast<llvm::Module&>(fp0))) std::__1::__invoke<DB::compileSortDescription(DB::CHJIT&, DB::SortDescription&, std::__1::vector<std::__1::shared_ptr<DB::IDataType const>, std::__1::allocator<std::__1::shared_ptr<DB::IDataType const> > > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::$_2&, llvm::Module&>(DB::compileSortDescription(DB::CHJIT&, DB::SortDescription&, std::__1::vector<std::__1::shared_ptr<DB::IDataType const>, std::__1::allocator<std::__1::shared_ptr<DB::IDataType const> > > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::$_2&, llvm::Module&) @ 0x274f899d in /usr/bin/clickhouse
2022.10.07 16:06:48.004047 [ 926 ] {} <Trace> AsynchronousMetrics: MemoryTracking: was 2.39 GiB, peak 2.56 GiB, will set to 2.31 GiB (RSS), difference: -257.47 MiB
2022.10.07 16:06:48.077197 [ 1236 ] {} <Fatal> BaseDaemon: 14. /build/build_docker/../contrib/libcxx/include/__functional/invoke.h:62: void std::__1::__invoke_void_return_wrapper<void, true>::__call<DB::compileSortDescription(DB::CHJIT&, DB::SortDescription&, std::__1::vector<std::__1::shared_ptr<DB::IDataType const>, std::__1::allocator<std::__1::shared_ptr<DB::IDataType const> > > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::$_2&, llvm::Module&>(DB::compileSortDescription(DB::CHJIT&, DB::SortDescription&, std::__1::vector<std::__1::shared_ptr<DB::IDataType const>, std::__1::allocator<std::__1::shared_ptr<DB::IDataType const> > > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::$_2&, llvm::Module&) @ 0x274f895d in /usr/bin/clickhouse
2022.10.07 16:06:48.270834 [ 1236 ] {} <Fatal> BaseDaemon: 15. /build/build_docker/../contrib/libcxx/include/__functional/function.h:230: std::__1::__function::__default_alloc_func<DB::compileSortDescription(DB::CHJIT&, DB::SortDescription&, std::__1::vector<std::__1::shared_ptr<DB::IDataType const>, std::__1::allocator<std::__1::shared_ptr<DB::IDataType const> > > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::$_2, void (llvm::Module&)>::operator()(llvm::Module&) @ 0x274f891d in /usr/bin/clickhouse
2022.10.07 16:06:48.464512 [ 1236 ] {} <Fatal> BaseDaemon: 16. /build/build_docker/../contrib/libcxx/include/__functional/function.h:711: void std::__1::__function::__policy_invoker<void (llvm::Module&)>::__call_impl<std::__1::__function::__default_alloc_func<DB::compileSortDescription(DB::CHJIT&, DB::SortDescription&, std::__1::vector<std::__1::shared_ptr<DB::IDataType const>, std::__1::allocator<std::__1::shared_ptr<DB::IDataType const> > > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::$_2, void (llvm::Module&)> >(std::__1::__function::__policy_storage const*, llvm::Module&) @ 0x274f88e8 in /usr/bin/clickhouse
2022.10.07 16:06:48.479956 [ 916 ] {} <Trace> SystemLog (system.metric_log): Flushing system log, 8 entries to flush up to offset 40
2022.10.07 16:06:48.701080 [ 1236 ] {} <Fatal> BaseDaemon: 17. /build/build_docker/../contrib/libcxx/include/__functional/function.h:843: std::__1::__function::__policy_func<void (llvm::Module&)>::operator()(llvm::Module&) const @ 0x274dc81e in /usr/bin/clickhouse
```

https://s3.amazonaws.com/clickhouse-test-reports/42123/1fc7833538d7a3547bdae5ee11eab5ec9390b291/fuzzer_astfuzzerdebug//server.log

```
2022.10.06 20:08:55.017269 [ 204 ] {27906ee5-78c9-4a3b-b89a-d56208890315::202210_1_6_1} <Debug> MergeTreeSequentialSource: Reading 2 marks from part 202210_5_5_0, total 8 rows starting from the beginning of the part
2022.10.06 20:08:55.120279 [ 204 ] {27906ee5-78c9-4a3b-b89a-d56208890315::202210_1_6_1} <Debug> MergeTreeSequentialSource: Reading 2 marks from part 202210_6_6_0, total 8 rows starting from the beginning of the part
2022.10.06 20:08:55.242349 [ 204 ] {27906ee5-78c9-4a3b-b89a-d56208890315::202210_1_6_1} <Trace> SortDescription: Compile sort description Date 1 1DateTime 1 1
2022.10.06 20:09:32.025229 [ 411 ] {} <Fatal> BaseDaemon: ########################################
2022.10.06 20:09:32.025394 [ 411 ] {} <Fatal> BaseDaemon: (version 22.10.1.1, build id: 1114F3DB38636A8EB4DB8FBFF97C6F266A9E2708) (from thread 204) (query_id: 27906ee5-78c9-4a3b-b89a-d56208890315::202210_1_6_1) (query: ) Received signal Aborted (6)
2022.10.06 20:09:32.025540 [ 411 ] {} <Fatal> BaseDaemon: 
2022.10.06 20:09:32.025703 [ 411 ] {} <Fatal> BaseDaemon: Stack trace: 0x7f36b367100b 0x7f36b3650859 0x7f36b3650729 0x7f36b3661fd6 0x1f910d24 0x1f91166d 0x274fc8d2 0x274f9534 0x274f89e8 0x274f899d 0x274f895d 0x274f891d 0x274f88e8 0x274dc81e 0x274d019d 0x274ce452 0x274f1e2c 0x28a4145f 0x28a4034f 0x28a3f652 0x28acdc4b 0x28aac298 0x28aab2f4 0x27f5e094 0x27f5df95 0x27f5dec3 0x27f5dd75 0x27f4a07b 0x27f40854 0x27f3e08c 0x27f56658 0x27f56635 0x27f56615 0x27f565f5 0x27f565bd 0x1f585eb6 0x1f585255 0x27f41da6 0x27f463d2 0x2833f792 0x27f6bdea
2022.10.06 20:09:32.025894 [ 411 ] {} <Fatal> BaseDaemon: 4. raise @ 0x7f36b367100b in ?
2022.10.06 20:09:32.026005 [ 411 ] {} <Fatal> BaseDaemon: 5. abort @ 0x7f36b3650859 in ?
2022.10.06 20:09:32.026109 [ 411 ] {} <Fatal> BaseDaemon: 6. ? @ 0x7f36b3650729 in ?
2022.10.06 20:09:32.026221 [ 411 ] {} <Fatal> BaseDaemon: 7. ? @ 0x7f36b3661fd6 in ?
2022.10.06 20:09:32.282120 [ 411 ] {} <Fatal> BaseDaemon: 8. /build/build_docker/../contrib/llvm-project/llvm/include/llvm/IR/Instructions.h:964: llvm::GetElementPtrInst::Create(llvm::Type*, llvm::Value*, llvm::ArrayRef<llvm::Value*>, llvm::Twine const&, llvm::Instruction*) @ 0x1f910d24 in /workspace/clickhouse
2022.10.06 20:09:32.510870 [ 411 ] {} <Fatal> BaseDaemon: 9. /build/build_docker/../contrib/llvm-project/llvm/include/llvm/IR/Instructions.h:986: llvm::GetElementPtrInst::CreateInBounds(llvm::Type*, llvm::Value*, llvm::ArrayRef<llvm::Value*>, llvm::Twine const&, llvm::Instruction*) @ 0x1f91166d in /workspace/clickhouse
2022.10.06 20:09:32.701511 [ 411 ] {} <Fatal> BaseDaemon: 10. /build/build_docker/../contrib/llvm-project/llvm/include/llvm/IR/IRBuilder.h:1759: llvm::IRBuilderBase::CreateInBoundsGEP(llvm::Type*, llvm::Value*, llvm::Value*, llvm::Twine const&) @ 0x274fc8d2 in /workspace/clickhouse
2022.10.06 20:09:32.893498 [ 411 ] {} <Fatal> BaseDaemon: 11. /build/build_docker/../src/Interpreters/JIT/compileFunction.cpp:568: DB::compileSortDescription(llvm::Module&, DB::SortDescription&, std::__1::vector<std::__1::shared_ptr<DB::IDataType const>, std::__1::allocator<std::__1::shared_ptr<DB::IDataType const> > > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x274f9534 in /workspace/clickhouse
2022.10.06 20:09:33.081623 [ 411 ] {} <Fatal> BaseDaemon: 12. /build/build_docker/../src/Interpreters/JIT/compileFunction.cpp:636: DB::compileSortDescription(DB::CHJIT&, DB::SortDescription&, std::__1::vector<std::__1::shared_ptr<DB::IDataType const>, std::__1::allocator<std::__1::shared_ptr<DB::IDataType const> > > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::$_2::operator()(llvm::Module&) const @ 0x274f89e8 in /workspace/clickhouse
2022.10.06 20:09:33.272443 [ 411 ] {} <Fatal> BaseDaemon: 13. /build/build_docker/../contrib/libcxx/include/type_traits:3640: decltype(static_cast<DB::compileSortDescription(DB::CHJIT&, DB::SortDescription&, std::__1::vector<std::__1::shared_ptr<DB::IDataType const>, std::__1::allocator<std::__1::shared_ptr<DB::IDataType const> > > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::$_2&>(fp)(static_cast<llvm::Module&>(fp0))) std::__1::__invoke<DB::compileSortDescription(DB::CHJIT&, DB::SortDescription&, std::__1::vector<std::__1::shared_ptr<DB::IDataType const>, std::__1::allocator<std::__1::shared_ptr<DB::IDataType const> > > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::$_2&, llvm::Module&>(DB::compileSortDescription(DB::CHJIT&, DB::SortDescription&, std::__1::vector<std::__1::shared_ptr<DB::IDataType const>, std::__1::allocator<std::__1::shared_ptr<DB::IDataType const> > > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::$_2&, llvm::Module&) @ 0x274f899d in /workspace/clickhouse
2022.10.06 20:09:33.460389 [ 411 ] {} <Fatal> BaseDaemon: 14. /build/build_docker/../contrib/libcxx/include/__functional/invoke.h:62: void std::__1::__invoke_void_return_wrapper<void, true>::__call<DB::compileSortDescription(DB::CHJIT&, DB::SortDescription&, std::__1::vector<std::__1::shared_ptr<DB::IDataType const>, std::__1::allocator<std::__1::shared_ptr<DB::IDataType const> > > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::$_2&, llvm::Module&>(DB::compileSortDescription(DB::CHJIT&, DB::SortDescription&, std::__1::vector<std::__1::shared_ptr<DB::IDataType const>, std::__1::allocator<std::__1::shared_ptr<DB::IDataType const> > > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::$_2&, llvm::Module&) @ 0x274f895d in /workspace/clickhouse
2022.10.06 20:09:33.648726 [ 411 ] {} <Fatal> BaseDaemon: 15. /build/build_docker/../contrib/libcxx/include/__functional/function.h:230: std::__1::__function::__default_alloc_func<DB::compileSortDescription(DB::CHJIT&, DB::SortDescription&, std::__1::vector<std::__1::shared_ptr<DB::IDataType const>, std::__1::allocator<std::__1::shared_ptr<DB::IDataType const> > > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::$_2, void (llvm::Module&)>::operator()(llvm::Module&) @ 0x274f891d in /workspace/clickhouse
```

https://s3.amazonaws.com/clickhouse-test-reports/42123/1fc7833538d7a3547bdae5ee11eab5ec9390b291/fuzzer_astfuzzermsan//server.log

```

    #0 0x4a580339 in llvm::iplist_impl<llvm::simple_ilist<llvm::MachineInstr, llvm::ilist_sentinel_tracking<true>>, llvm::ilist_traits<llvm::MachineInstr>>::~iplist_impl() MachineBasicBlock.cpp
    #1 0x4a58075f in llvm::MachineBasicBlock::~MachineBasicBlock() (/workspace/clickhouse+0x4a58075f) (BuildId: 2ef7404ebaca03c46dc77217c27f942796dfe588)
    #2 0x4a6f931f in llvm::ilist_alloc_traits<llvm::MachineBasicBlock>::deleteNode(llvm::MachineBasicBlock*) (/workspace/clickhouse+0x4a6f931f) (BuildId: 2ef7404ebaca03c46dc77217c27f942796dfe588)
    #3 0x4a5ac396 in llvm::MachineBasicBlock::eraseFromParent() (/workspace/clickhouse+0x4a5ac396) (BuildId: 2ef7404ebaca03c46dc77217c27f942796dfe588)
    #4 0x4aebd4a7 in llvm::TailDuplicator::removeDeadBlock(llvm::MachineBasicBlock*, llvm::function_ref<void (llvm::MachineBasicBlock*)>*) (/workspace/clickhouse+0x4aebd4a7) (BuildId: 2ef7404ebaca03c46dc77217c27f942796dfe588)
    #5 0x4aeb52a1 in llvm::TailDuplicator::tailDuplicateAndUpdate(bool, llvm::MachineBasicBlock*, llvm::MachineBasicBlock*, llvm::SmallVectorImpl<llvm::MachineBasicBlock*>*, llvm::function_ref<void (llvm::MachineBasicBlock*)>*, llvm::SmallVectorImpl<llvm::MachineBasicBlock*>*) (/workspace/clickhouse+0x4aeb52a1) (BuildId: 2ef7404ebaca03c46dc77217c27f942796dfe588)
    #6 0x4aebdcb9 in llvm::TailDuplicator::tailDuplicateBlocks() (/workspace/clickhouse+0x4aebdcb9) (BuildId: 2ef7404ebaca03c46dc77217c27f942796dfe588)
    #7 0x4aeb171c in (anonymous namespace)::TailDuplicateBase::runOnMachineFunction(llvm::MachineFunction&) TailDuplication.cpp
    #8 0x4a736f43 in llvm::MachineFunctionPass::runOnFunction(llvm::Function&) (/workspace/clickhouse+0x4a736f43) (BuildId: 2ef7404ebaca03c46dc77217c27f942796dfe588)
    #9 0x4f60660d in llvm::FPPassManager::runOnFunction(llvm::Function&) (/workspace/clickhouse+0x4f60660d) (BuildId: 2ef7404ebaca03c46dc77217c27f942796dfe588)
    #10 0x4f62fc61 in llvm::FPPassManager::runOnModule(llvm::Module&) (/workspace/clickhouse+0x4f62fc61) (BuildId: 2ef7404ebaca03c46dc77217c27f942796dfe588)
    #11 0x4f60aeb2 in llvm::legacy::PassManagerImpl::run(llvm::Module&) (/workspace/clickhouse+0x4f60aeb2) (BuildId: 2ef7404ebaca03c46dc77217c27f942796dfe588)
    #12 0x4f630a4b in llvm::legacy::PassManager::run(llvm::Module&) (/workspace/clickhouse+0x4f630a4b) (BuildId: 2ef7404ebaca03c46dc77217c27f942796dfe588)
    #13 0x41e5a39f in DB::JITCompiler::compile(llvm::Module&) build_docker/../src/Interpreters/JIT/CHJIT.cpp:78:22
    #14 0x41e5591d in DB::CHJIT::compileModule(std::__1::unique_ptr<llvm::Module, std::__1::default_delete<llvm::Module>>) build_docker/../src/Interpreters/JIT/CHJIT.cpp:378:29
    #15 0x41e54b8d in DB::CHJIT::compileModule(std::__1::function<void (llvm::Module&)>) build_docker/../src/Interpreters/JIT/CHJIT.cpp:359:24
    #16 0x41e947de in DB::compileAggregateFunctions(DB::CHJIT&, std::__1::vector<DB::AggregateFunctionWithOffset, std::__1::allocator<DB::AggregateFunctionWithOffset>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>) build_docker/../src/Interpreters/JIT/compileFunction.cpp:473:32
    #17 0x3e59b3ba in DB::Aggregator::compileAggregateFunctionsIfNeeded()::$_0::operator()() const build_docker/../src/Interpreters/Aggregator.cpp:693:49
    #18 0x3e59b3ba in std::__1::pair<std::__1::shared_ptr<DB::CompiledExpressionCacheEntry>, bool> DB::CacheBase<wide::integer<128ul, unsigned int>, DB::CompiledExpressionCacheEntry, UInt128Hash, DB::CompiledFunctionWeightFunction>::getOrSet<DB::Aggregator::compileAggregateFunctionsIfNeeded()::$_0>(wide::integer<128ul, unsigned int> const&, DB::Aggregator::compileAggregateFunctionsIfNeeded()::$_0&&) build_docker/../src/Common/CacheBase.h:125:24
    #19 0x3e59b3ba in DB::Aggregator::compileAggregateFunctionsIfNeeded() build_docker/../src/Interpreters/Aggregator.cpp:689:70
    #20 0x3e593195 in DB::Aggregator::Aggregator(DB::Block const&, DB::Aggregator::Params const&) build_docker/../src/Interpreters/Aggregator.cpp:626:5
    #21 0x45e75093 in DB::Aggregator* std::__1::construct_at<DB::Aggregator, DB::Block const&, DB::Aggregator::Params&, DB::Aggregator*>(DB::Aggregator*, DB::Block const&, DB::Aggregator::Params&) build_docker/../contrib/libcxx/include/__memory/construct_at.h:38:50
    #22 0x45e75093 in void std::__1::allocator_traits<std::__1::allocator<std::__1::__list_node<DB::Aggregator, void*>>>::construct<DB::Aggregator, DB::Block const&, DB::Aggregator::Params&, void, void>(std::__1::allocator<std::__1::__list_node<DB::Aggregator, void*>>&, DB::Aggregator*, DB::Block const&, DB::Aggregator::Params&) build_docker/../contrib/libcxx/include/__memory/allocator_traits.h:298:9
    #23 0x45e75093 in std::__1::__list_iterator<DB::Aggregator, void*> std::__1::list<DB::Aggregator, std::__1::allocator<DB::Aggregator>>::emplace<DB::Block const&, DB::Aggregator::Params&>(std::__1::__list_const_iterator<DB::Aggregator, void*>, DB::Block const&, DB::Aggregator::Params&) build_docker/../contrib/libcxx/include/list:1648:5
    #24 0x45e75093 in DB::AggregatingTransformParams::AggregatingTransformParams(DB::Block const&, DB::Aggregator::Params const&, bool) build_docker/../src/Processors/Transforms/AggregatingTransform.h:41:44
    #25 0x45e72d40 in DB::AggregatingTransformParams* std::__1::construct_at<DB::AggregatingTransformParams, DB::Block const&, DB::Aggregator::Params, bool&, DB::AggregatingTransformParams*>(DB::AggregatingTransformParams*, DB::Block const&, DB::Aggregator::Params&&, bool&) build_docker/../contrib/libcxx/include/__memory/construct_at.h:38:50
    #26 0x45e72d40 in void std::__1::allocator_traits<std::__1::allocator<DB::AggregatingTransformParams>>::construct<DB::AggregatingTransformParams, DB::Block const&, DB::Aggregator::Params, bool&, void, void>(std::__1::allocator<DB::AggregatingTransformParams>&, DB::AggregatingTransformParams*, DB::Block const&, DB::Aggregator::Params&&, bool&) build_docker/../contrib/libcxx/include/__memory/allocator_traits.h:298:9
    #27 0x45e72d40 in std::__1::__shared_ptr_emplace<DB::AggregatingTransformParams, std::__1::allocator<DB::AggregatingTransformParams>>::__shared_ptr_emplace<DB::Block const&, DB::Aggregator::Params, bool&>(std::__1::allocator<DB::AggregatingTransformParams>, DB::Block const&, DB::Aggregator::Params&&, bool&) build_docker/../contrib/libcxx/include/__memory/shared_ptr.h:293:9
    #28 0x45e72d40 in std::__1::shared_ptr<DB::AggregatingTransformParams> std::__1::allocate_shared<DB::AggregatingTransformParams, std::__1::allocator<DB::AggregatingTransformParams>, DB::Block const&, DB::Aggregator::Params, bool&, void>(std::__1::allocator<DB::AggregatingTransformParams> const&, DB::Block const&, DB::Aggregator::Params&&, bool&) build_docker/../contrib/libcxx/include/__memory/shared_ptr.h:954:55
    #29 0x45e72d40 in std::__1::shared_ptr<DB::AggregatingTransformParams> std::__1::make_shared<DB::AggregatingTransformParams, DB::Block const&, DB::Aggregator::Params, bool&, void>(DB::Block const&, DB::Aggregator::Params&&, bool&) build_docker/../contrib/libcxx/include/__memory/shared_ptr.h:963:12
    #30 0x45e5a890 in DB::AggregatingStep::transformPipeline(DB::QueryPipelineBuilder&, DB::BuildQueryPipelineSettings const&) build_docker/../src/Processors/QueryPlan/AggregatingStep.cpp:139:29
    #31 0x45f61ca7 in DB::ITransformingStep::updatePipeline(std::__1::vector<std::__1::unique_ptr<DB::QueryPipelineBuilder, std::__1::default_delete<DB::QueryPipelineBuilder>>, std::__1::allocator<std::__1::unique_ptr<DB::QueryPipelineBuilder, std::__1::default_delete<DB::QueryPipelineBuilder>>>>, DB::BuildQueryPipelineSettings const&) build_docker/../src/Processors/QueryPlan/ITransformingStep.cpp:48:9
    #32 0x45fc7931 in DB::QueryPlan::buildQueryPipeline(DB::QueryPlanOptimizationSettings const&, DB::BuildQueryPipelineSettings const&) build_docker/../src/Processors/QueryPlan/QueryPlan.cpp:187:47
```

**Review by rschu1ze — COMMENTED** [review]
Code changes look (as far as I can judge) good.

**Comment by kitaisreal** [comment]
I did not merged submodule, I just checked that issue will be reproducible.

**Comment by rschu1ze** [comment]
Okay. I wondered why the submodule still on 14.

I actually prepared the upgrade to 15 [here](https://github.com/ClickHouse/ClickHouse/pull/42047) but I will abandon that PR because this PR makes it obsolete.

You upgraded to the correct submodule hash (--> https://github.com/ClickHouse/llvm-project/pull/5/commits), thanks.

Just as a smaller hint: Could you please upgrade set LLVM_VERSION in "contrib/llvm-project/CMakeLists.txt" to "15.0.0bundled"?

**Review by rschu1ze — APPROVED** [review]
Test failures are unrelated. Can be merged. Thanks.

**Comment by kitaisreal** [comment]
@rschu1ze we need somehow get performance tests results

**Pull request merged**
