### PR TITLE
chore: bump testcontainers-go to 0.18.0

### PR DESCRIPTION
**Pull request by mdelapenya**
This PR bumps the dependency with testcontainers-go, using the latest release 0.18.0: https://github.com/testcontainers/testcontainers-go/releases/tag/v0.18.0

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
...

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
Do we need this? Everything was alright...

**Comment by mdelapenya** [comment]
> Do we need this? Everything was alright...

Indeed, everything was fine and working 😃.

As part of an OSS team maintaining testcontainers-go, we'd like to support other OSS projects in their testing activities, that's why I wanted to help out with keeping this dependency updated to its [latest released version](https://github.com/testcontainers/testcontainers-go/releases/tag/v0.18.0). Just to let you know, in 0.16.0 and 0.17.0 we were forced to add certain replace directives with the Docker dependencies, which caused some trouble with the dependencies. It has finally been resolved in this 0.18.0.

In any case, the bump is not mandatory nor critical, so I'd understand keeping it in the 0.15.0 version.

**Comment by alexey-milovidov** [comment]
Ok. Let's merge it...

Just to note:
- we have one tiny tool written in Go, it represents maybe less than 0.1% of our codebase;
- avoiding "supply chain attacks" (like left-pad.js) can be more important than constantly updating the libraries;
- especially when the libraries are not used in runtime but only in the build process;

**Comment by mdelapenya** [comment]
Thanks for your work here @alexey-milovidov, I see your point, which I strongly share 🙏

**Pull request merged**
