### PR TITLE
Check socket is connected in HTTPSession

### PR DESCRIPTION
**Pull request by nikitamikhaylov**
### Changelog category (leave one):

- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Review by alexey-milovidov — COMMENTED** [review]
What if it will become disconnected before
```
HTTPServerResponse response(session);
```

**Comment by nikitamikhaylov** [comment]
Exception `Socket is not connected` will be thrown from the Poco internals

**Comment by nikitamikhaylov** [comment]
Exception `Socket is not connected` will be thrown from the Poco internals

**Review by alexey-milovidov — APPROVED** [review]
This fix is not enough, we can catch the exception and skip "socket is not connected", but the fix makes things better, so LGTM.

**Comment by alexey-milovidov** [comment]
Need to investigate something new that has been found by AST fuzzer.

**Comment by alexey-milovidov** [comment]
Stress test - by #36660

**Comment by nikitamikhaylov** [comment]
AST Fuzzer: #36748

**Pull request merged**
