### PR TITLE
Try to run stateful tests in parallel

### PR DESCRIPTION
**Pull request by tavplubix**
Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Because after #33717 (merged on 2022-03-11, added `minio`, `test.hits_s3` table and new long test) and #35047 (merged on 2022-03-24, added `max_threads` randomization) 1 hour is not enough to run all stateful tests sometimes:

Example: https://s3.amazonaws.com/clickhouse-test-reports/0/9a8e9198e59c4cf0b3b7204ada83e87bdf845590/stateful_tests__thread__actions_/runlog.log

Average check time:

[TSan](http://a137ed393136a448a8a0b796e91304c4-2000240599.us-east-1.elb.amazonaws.com:8123/play?user=default#c2VsZWN0IAp0b1N0YXJ0T2ZEYXkoY2hlY2tfc3RhcnRfdGltZSkgYXMgZCwKY291bnQoKSwKcm91bmQoYXZnKGNoZWNrX2R1cmF0aW9uX21zKSAvIDEwMDAgLyA2MCwgMSkgYXMgYXZnX2R1cl9taW4sCnJvdW5kKHF1YW50aWxlKDAuMSkoY2hlY2tfZHVyYXRpb25fbXMpIC8gMTAwMCAvIDYwLCAxKSBhcyBxMV9kdXJfbWluLApyb3VuZChxdWFudGlsZSgwLjUpKGNoZWNrX2R1cmF0aW9uX21zKSAvIDEwMDAgLyA2MCwgMSkgYXMgcTVfZHVyX21pbiwKcm91bmQocXVhbnRpbGUoMC45KShjaGVja19kdXJhdGlvbl9tcykgLyAxMDAwIC8gNjAsIDEpIGFzIHE5X2R1cl9taW4KZnJvbSBgZ2gtZGF0YWAuY2hlY2tzIHdoZXJlICcyMDIxLTAxLTAxJyA8PSBjaGVja19zdGFydF90aW1lIGFuZCB0ZXN0X25hbWU9JycgYW5kIGNoZWNrX25hbWUgaWxpa2UgJyVzdGF0ZWZ1bCV0aHJlYWQlJyBhbmQgY2hlY2tfZHVyYXRpb25fbXMgPiAzMDAwMDAgYW5kIHB1bGxfcmVxdWVzdF9udW1iZXI9MCBncm91cCBieSBkIG9yZGVyIGJ5IGQ=) became 20 minutes longer since 2022-03-11 and 10 minutes longer since 2022-03-24

[Debug](http://a137ed393136a448a8a0b796e91304c4-2000240599.us-east-1.elb.amazonaws.com:8123/play?user=default#c2VsZWN0IAp0b1N0YXJ0T2ZEYXkoY2hlY2tfc3RhcnRfdGltZSkgYXMgZCwKY291bnQoKSwKcm91bmQoYXZnKGNoZWNrX2R1cmF0aW9uX21zKSAvIDEwMDAgLyA2MCwgMSkgYXMgYXZnX2R1cl9taW4sCnJvdW5kKHF1YW50aWxlKDAuMSkoY2hlY2tfZHVyYXRpb25fbXMpIC8gMTAwMCAvIDYwLCAxKSBhcyBxMV9kdXJfbWluLApyb3VuZChxdWFudGlsZSgwLjUpKGNoZWNrX2R1cmF0aW9uX21zKSAvIDEwMDAgLyA2MCwgMSkgYXMgcTVfZHVyX21pbiwKcm91bmQocXVhbnRpbGUoMC45KShjaGVja19kdXJhdGlvbl9tcykgLyAxMDAwIC8gNjAsIDEpIGFzIHE5X2R1cl9taW4KZnJvbSBgZ2gtZGF0YWAuY2hlY2tzIHdoZXJlICcyMDIxLTAxLTAxJyA8PSBjaGVja19zdGFydF90aW1lIGFuZCB0ZXN0X25hbWU9JycgYW5kIGNoZWNrX25hbWUgaWxpa2UgJyVzdGF0ZWZ1bCVkZWJ1ZyUnIGFuZCBjaGVja19kdXJhdGlvbl9tcyA+IDMwMDAwMCBhbmQgcHVsbF9yZXF1ZXN0X251bWJlcj0wIGdyb3VwIGJ5IGQgb3JkZXIgYnkgZA==) became 3 minutes longer since 2022-03-11 and 5 minutes longer since 2022-03-24

### CODE REVIEW

**Comment by alesapin** [comment]
@mergifyio update

**Comment by tavplubix** [comment]
[c37945b](https://github.com/ClickHouse/ClickHouse/pull/35720/commits/c37945b2c81fd3f042331faf693d5df20b813cc1): Stateful tests (thread, actions) - `00170_s3_cache` - server crashed with no stacktrace, cc: @kssenii 
I marked `00170_s3_cache` as `no-parallel` to make tests pass. Probably it was due to high memory usage, but need to check.

**Comment by tavplubix** [comment]
All stateful tests checks passed.
Stateful tests (thread, actions):
```
2022-03-30 12:34:39 Using queries from '/usr/share/clickhouse-test/queries' directory
...
2022-03-30 13:10:45 All tests have finished.
```
So it takes about 36 minutes. Current timeout for `clickhouse-test` is `60*0.9=54` minutes.

**Comment by alesapin** [comment]
Let's merge then.

**Pull request merged**
