### PR TITLE
 Better management of DateTime partitionning #3786 

### PR DESCRIPTION
**Pull request by edonin**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Has discussed in the issue #3786, I added two columns called "min_time" and "max_time" in the system.parts table. They contain the min datetime and max datetime of the partition if the merge tree is using one and only datetime in the sorting index. Otherwise, these columns are equals to 0.

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
Missing functional test. Look at `dbms/tests/queries` directory.

**Comment by alexey-milovidov** [comment]
I think, the user will expect, that `min_date`, `max_date` columns will be also filled with non-zero value, if there is `min_time`, `max_time`.

**Review by alexey-milovidov — CHANGES_REQUESTED** [review]
.

**Comment by edonin** [comment]
For the tests, I will take a look.

**Comment by edonin** [comment]
For the other issue, I have a doupt.

For my understanding, DateTime is timezone agnostic (it could be seen to any timezone, and still refer to the same instant). But Date is timezone dependant.  So for converting a DateTime to Date, you need to specify a timezone. So here, which timezone could we use for converting the DateTime to Date ? The system timezone ? The user timezone ?

Thanks,

**Comment by alexey-milovidov** [comment]
> For my understanding, DateTime is timezone agnostic (it could be seen to any timezone, and still refer to the same instant). But Date is timezone dependant. So for converting a DateTime to Date, you need to specify a timezone. So here, which timezone could we use for converting the DateTime to Date ? The system timezone ? The user timezone ?

You're right, let leave it as is.

**Comment by edonin** [comment]
I added some tests.

Nevertheless, the result is a bit different of what i described in the issue. The column min_time and max_time are filled if the merge tree **partitionning index** contains a DateTime. It does not care about the merge tree **sorting index**.

Since these two columns is defined for each partition, it seems more logical that they depend of the partitionning index.

**Comment by alexey-milovidov** [comment]
Ok.

**Pull request merged**
