### PR TITLE
[RFC] Fix settings/current_database in system.processes for async BACKUP/RESTORE

### PR DESCRIPTION
**Pull request by azat**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix settings/current_database in system.processes for async BACKUP/RESTORE

### CODE REVIEW

**Comment by robot-ch-test-poll1** [comment]
*This is an automated comment for commit 8a48b3334433fe5e77c23ff6df10e454db2d3f82 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/68163/8a48b3334433fe5e77c23ff6df10e454db2d3f82/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/67962/e582118544f3c49c3c6600ac8fa252151714d25f/docs_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Review by antaljanosbenjamin — COMMENTED** [review]
The changes looks okay. I don't see a reliable way to write a test for this as I have no idea how we could stretch the length of backup/restore, but you might have some ideas. Do you think you can add a reliable test in some way?

**Comment by azat** [comment]
> I don't see a reliable way to write a test for this as I have no idea how we could stretch the length of backup/restore, but you might have some ideas. Do you think you can add a reliable test in some way?

Yes, right now it is tricky.

`max_backup_bandwidth` could be used to throttle backup, but the problem is that you cannot KILL the backup in the middle of the copy now, so what I'm planning to do, is to finish [#52092 ](https://github.com/ClickHouse/ClickHouse/issues/52092#issuecomment-2282879200) and then, write a test (it possible to write a test even now, but it will be an integration test, which I don't like)

**Review by antaljanosbenjamin — APPROVED** [review]
I am from my phone, will merge the PR once I get back in front my laptop (latest tomorrow).

**Comment by antaljanosbenjamin** [comment]
The performance tests is very unlikely to be related, honestly I cannot imagine it is related.

**Pull request merged**
