### PR TITLE
Generic constructor of ColumnVector from initializer list

### PR DESCRIPTION
**Pull request by alexey-milovidov**
Changelog category (leave one):
- Non-significant (changelog entry is not required)

Continuation of #9367

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
This is wrong.

**Comment by huiwangcs** [comment]
what's wrong?

**Comment by alexey-milovidov** [comment]
Specializations of `insert` method in PODArray with type U that is different than T (and also probably, not trivially copyable) require a loop with element by element assignment instead of memcpy.

**Comment by alexey-milovidov** [comment]
This can be improved... We just need more specializations.
Do you want to make another pull request on top of my changes?

**Comment by huiwangcs** [comment]
@alexey-milovidov if it's not urgent, i'm willing to make another pull request. it may take me some time.

**Comment by alexey-milovidov** [comment]
Not urgent at all. Yes, it will be appreciated!

**Pull request merged**
