### PR TITLE
Use ClickHouse threads in NuRaft

### PR DESCRIPTION
**Pull request by alesapin**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

### CODE REVIEW

**Comment by alesapin** [comment]
Bloked by https://github.com/ClickHouse/ClickHouse/pull/62156

**Comment by robot-ch-test-poll2** [comment]
*This is an automated comment for commit c2995b13e21b49bf490ef603d237361b639400a9 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/62196/c2995b13e21b49bf490ef603d237361b639400a9/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

**Review by antonio2368 — APPROVED** [review]

**Comment by canhld94** [comment]
@antonio2368 @alesapin I believe we have a problem here. When running keeper as a standalone process, `bg_commit_thread_` (in `raft_server`) won't start at all, and it prevent keeper server to start.

**Comment by antonio2368** [comment]
@canhld94 can you please create an issue with more information?

**Pull request merged**
