### PR TITLE
Experiment with start/stop in stress test

### PR DESCRIPTION
**Pull request by alexey-milovidov**
Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Our native start/stop commands provide more diagnostics.

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
> 00956_sensitive_data_masking

- fixed in #13748

**Comment by alexey-milovidov** [comment]
@nikitamikhaylov TSan report in cache dictionary.

**Comment by alexey-milovidov** [comment]
Squashing is Ok.

**Comment by nikitamikhaylov** [comment]
> @nikitamikhaylov TSan report in cache dictionary.

Already fixed in my PR.

**Pull request merged**
