### PR TITLE
Ignore case for engine name

### PR DESCRIPTION
**Pull request by zhang2014**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
I wonder, why you really need this?

**Comment by zhang2014** [comment]
@alexey-milovidov I just saw someone was confused by the error : )

**Comment by alexey-milovidov** [comment]
It will contradict our principles: all names are case sensitive except names that are identical to the names from the SQL standard. Example: `formatReadableSize` function name is case sensitive; and `sum`, `dateDiff` are case insensitive just for compatibility.

I would like to make all factories more user friendly by adding suggestions based on case insensitive levenstein distance (edit distance). Example:

```
SELECT FomratReadableSize(*) FROM table
```

Should give an error like:

```
Unknown function 'FomratReadableSize', did you mean 'formatReadableSize'?
```

The same for `StorageFactory`, etc.

For the implementation, you can calculate and compare levenstein distance for all names by O(N) (brute force) - this is appropriate for the exceptional case. Or implement trigram index (but this is an overkill).

**Comment by zhang2014** [comment]
Sorry, I'm not sure about the current principle.

**Pull request closed without merging**
