### PR TITLE
Try fix 02151_hash_table_sizes_stats.sh test

### LINKED ISSUE #48173: 02151_hash_table_sizes_stats triggers OOM
Examples:
https://s3.amazonaws.com/clickhouse-test-reports/0/5fa519d04311615433ad7e016d974de6f7af9860/stateless_tests__tsan__[3/3].html
https://s3.amazonaws.com/clickhouse-test-reports/0/278b8f74c2a54e832cb25c9cd629f6b1939dcfb6/stateless_tests__tsan__[3/3].html

See also https://github.com/ClickHouse/ClickHouse/pull/45181#issuecomment-1380411041

Seems like `02151_hash_table_sizes_stats_distributed` triggers OOM as well. But it was disabled in https://github.com/ClickHouse/ClickHouse/pull/45287, and then we forgot about it. We should try to enable it back.

### PR DESCRIPTION
**Pull request by nickitat**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by tavplubix** [comment]
Our memory trackers work with sanitizers as well. So why OOM happens?

**Comment by nickitat** [comment]
I have no idea, let's at least reduce the amount of noise

**Comment by tavplubix** [comment]
Let's try to debug it. OOMs like this usually happen when we allocate a huge chunk of memory without checking that it doesn't exceed limitations. In other words, when we call `CurrentMemoryTracker::allocNoThrow` instead of `CurrentMemoryTracker::alloc` for huge allocations. In other words, when we use `new` or `malloc` for huge allocations without additional checks (`malloc` and `new` call `allocNoThrow` because they cannot throw). I quickly looked through `Aggregator` and found two suspicious places:
https://github.com/ClickHouse/ClickHouse/blob/73e98de46dd76ab5bcaa2b72301703856a17e2ad/src/Interpreters/Aggregator.cpp#L1175
https://github.com/ClickHouse/ClickHouse/blob/73e98de46dd76ab5bcaa2b72301703856a17e2ad/src/Interpreters/Aggregator.cpp#L2809

Where `row_end` is actually a block size and can be quite big. I tried increasing `max_block_size` and got an interesting result:
https://pastila.nl/?00b0c940/f011d9e7124b0c30b20cdb4be9872be6

At first, it logs
```
[ 982431 ] ... <Debug> MemoryTracker: Current memory usage (for query): 16.00 GiB.
```
and after that it throw an exception in another thread:
```
Memory limit (for user) exceeded: would use 16.00 GiB (attempt to allocate chunk of 17179953272 bytes), maximum: 953.67 MiB
```

The maximum was about 1GiB, but looks like `Aggregator` had allocated 16GiB. 

Can it be the reason? Do we have other (less obvious) places in `Aggregator` where huge allocations may happen?

**Review by tavplubix — APPROVED** [review]
We can merge it to suppress the issue temporarily, but the root cause must be investigated. We definitely have some bugs with memory accounting in Aggregator.

**Pull request merged**
