### PR TITLE
Support for LIVE VIEW and LIVE CHANNEL tables

### PR DESCRIPTION
**Pull request by KochetovNicolai**
**BlackBerry Limited contributes this under the terms of the Apache-2.0 license as indicated in the modifications.**

Modifications were made to ClickHouse version 54318 to add support for ``LIVE VIEW`` and ``LIVE CHANNEL`` tables to enable real-time command line and web applications. The purpose of this pull request is to demonstrate the proposed functionality and discuss the potential of adding these features to the current master. 

LIVE VIEW table
=============

Used for implementing live views (for more information, see ``CREATE LIVE VIEW``). It does not store any data permanently, but stores a ``SELECT`` query and caches its result. The result of the query is updated automatically when changes to the table specified in the ``SELECT`` are made. In addition to a ``SELECT`` query for reading the current result of the query, the table also supports a ``WATCH`` query to constantly receive an updated query result. Currently, filtering using a ``WHERE`` clause is not supported when reading a table using a ``SELECT`` query.

LIVE CHANNEL table
=================

Used for implementing live channels (for more information, see ``CREATE LIVE CHANNEL``). It does not store any data but could group one or more live views into a single channel. Live view tables are added or removed from the channel using the ``ALTER CHANNEL`` command. The table does not support reading using a ``SELECT`` query, but only supports watching the channel using a ``WATCH`` query. When watching the table, the result from each live view is multiplexed and updated automatically when any query results change.

CREATE LIVE VIEW
=================

```sql
CREATE [TEMPORARY] LIVE VIEW [IF NOT EXISTS] [db.]name AS SELECT ...
```

Creates a live view. Live views do not store any data but similar to normal views store a saved query that is specified during table creation. However, in addition to supporting reading a table, it allows to ``WATCH`` a table to get updated saved query results. The query result is updated when changes are made to the table, specified in the ``SELECT`` during table creation, if the change affects the saved query result.

As an example, you can create a ``LIVE VIEW`` table similar to a normal view using the ``CREATE LIVE VIEW`` command

```sql
CREATE LIVE VIEW view AS SELECT ...
```

where the ``SELECT`` clause specifies the saved query whose result the live view will contain.

If a ``TEMPORARY`` live view table is created then the table is automatically removed if there are no active ``WATCH`` queries after timeout specified by the ``temporary_live_view_timeout`` setting.

Multiple live views could be grouped into a channel using a ``LIVE CHANNEL`` table.
Because multiple query results are sent when a live view is watched, it is best to use ``FORMAT`` that supports query result framing such as ``JSON`` or ``JSONOneLine``.

When a ``LIVE VIEW`` table is watched with a ``WATCH`` query, it produces heartbeats if there are no updates within the time period specified by the ``heartbeat_delay`` setting. Currently, only ``JSON`` and ``JSONOneLine`` formats support heartbeats. Heartbeats are used to keep a long-lived connection executing a ``WATCH`` query alive. Similar to normal views, a ``LIVE VIEW`` table can be deleted using the ``DROP TABLE`` command.

CREATE LIVE CHANNEL
====================

```sql
CREATE [TEMPORARY] LIVE CHANNEL [IF NOT EXISTS] [db.]name WITH ...
```

Creates a live channel to group one or more live views. When a table is being created existing live views could be specified in a ``WITH`` clause. For example, to create a live channel

```sql
CREATE LIVE CHANNEL channel WITH view, ...
```

Similar to live views, live channels can be ``TEMPORARY`` and in that case, the table will be automatically removed if there are no active ``WATCH`` queries after the timeout specified by the ``temporary_live_channel_timeout`` setting.

A live channel only supports a ``WATCH`` query, it does not support reading using the ``SELECT``, and the result of a ``WATCH`` query is a multiplexed stream of live view query results. Live views can be added or
removed from the channel using the ``ALTER CHANNEL`` command. When multiple live views are added to the channel, live views are checked for updated results in a round-robin fashion to ensure that no
one live view consumes all the channel bandwidth. Because multiple query results are multiplexed on the same channel, it is best to use ``FORMAT`` that supports query result framing
such as ``JSON`` or ``JSONOneLine``.

When a live channel is watched it produces heartbeats if are no updates within the time period specified by the ``heartbeat_delay`` setting. Currently, only ``JSON`` and ``JSONOneLine`` formats support heartbeats. Heartbeats are used to keep a long-lived connection executing a ``WATCH`` query alive. Similar to views, live channels can be deleted using the ``DROP TABLE`` command.

ALTER CHANNEL
===============
```sql
ALTER CHANNEL channel ADD|REMOVE|MODIFY|REFRESH ...
```

Modifies channel state. One or more live views can be added or removed using ``ADD`` or ``REMOVE`` commands. To specify a new group of live views that belong to the channel use the ``MODIFY`` command. If a refreshed live view query result is needed to be sent on the channel then the ``REFRESH`` command can be used. 

For example, to add a ``LIVE VIEW`` to a channel:

```sql
ALTER CHANNEL channel ADD view
```

to remove a ``LIVE VIEW`` from a channel:

```sql
ALTER CHANNEL channel REMOVE view
```

to modify channel's ``LIVE VIEW`` list:

```sql
ALTER CHANNEL channel MODIFY view, ...
```

to refresh ``LIVE VIEW`` query results:

```sql
ALTER CHANNEL channel REFRESH view, ...
```

The command timeout is determined by the ``alter_channel_wait_ms`` setting. If the timeout is reached then the command is aborted while partial changes to the channel might have been applied. The timeout is present because channels can have a large number of live views and the changes have to be propagated to all active ``WATCH`` queries in order to keep a consistent channel state.

WATCH
=======

```sql
WATCH [db.]name [LIMIT n] [FORMAT format]
```

This query is used to watch either ``LIVE VIEW`` or ``LIVE CHANNEL`` tables. A ``LIMIT`` can be specified to set the number of updates to receive before terminating the query. By default, the number of updates is not limited. Similar to a ``SELECT`` query the output format is specified using the ``FORMAT`` clause. Because multiple query results are sent as the result of a ``WATCH`` query, it is best to use ``FORMAT`` that supports query result framing such as ``JSON`` or ``JSONOneLine``.

JSONOneLine format
==================

Differs from ``JSON`` format only in that the object is output as one line and without empty spaces.
This format is convenient to use when multiple objects are sent during the query execution such as
in the case of a ``WATCH`` query. In this case, a new line character can be used as a delimiter between different query results.

Example:

```json
{
    "meta": [{"name":"1", "type":"UInt8"}],
    "data": [{"1":1}],
    "rows":1,
    "statistics": {"elapsed":0.000272909,"rows_read":0,"bytes_read":0}
}
```

When used with a ``WATCH`` query, ``hash`` attribute is added to the result:

```json 
{
    "hash":"687d4e26eeadf6dfe009b66f0c22edf",
    "meta":[{"name":"1","type":"UInt8"}],
}
```

heartbeat objects are supported for a ``WATCH`` query:

```json 
{
    "heartbeat": {
         "timestamp":"1517023830793441",
         "hash": {
              "blocks":"687d4e26eeadf6dfe009b66f0c22edf"
         }
    }
}
```

This format is only appropriate for outputting query result, not for parsing. See ``JSONEachRow`` format for ``INSERT`` queries.

JSON format (updates)
===================

When used in a ``WATCH`` query,  ``hash`` attribute is added to the result:

```json
  {
          "hash": "687d4e26eeadf6dfe009b66f0c22edf",
          "meta": [
                {"name": "SearchPhrase", "type": "String"},
                {"name": "c", "type": "UInt64"}
          ],
  }
```

heartbeat objects are supported for a ``WATCH`` query 

```json
  {
          "heartbeat": {
                  "timestamp": "1517023310853606",
                  "hash": {
                          "blocks": "687d4e26eeadf6dfe009b66f0c22edf"
                  }
          }
  }
```

New settings
==========

temporary_live_view_timeout
-------------------------------------
Timeout in seconds after which temporary live view table is deleted if there are no active ``WATCH`` queries.

temporary_live_channel_timeout
------------------------------------------
Timeout in seconds after which temporary live channel table is deleted if there are no active ``WATCH`` queries.

heartbeat_delay
---------------------
Interval in microseconds of inactivity after which heartbeat is sent to keep live view or live channel ``WATCH`` query connection alive.

alter_channel_wait_ms
------------------------------
The maximum timeout to wait in milliseconds for the ``ALTER CHANNEL`` query to complete.

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
We have prepared this PR for merge and we have evaluated this feature, but the use case looks very narrow.

At the same time, there are too many additional things to consider about this feature (how does it work in distributed setup; how the client can commit read data; persistency options) and this feature is likely to be easily misunderstood by potential users.

It still can be merged if the implementation is unintrusive (isolated) as much as possible to the existing codebase. But it is not (it requires several modifications of Block and DataStreams).

We've asked several third-party companies (including Altinity) for the use cases and we have struggled to find them. Let's close this PR for now, but we still can address it later.

**Comment by vzakaznikov** [comment]
I finally got permission to participate in ClickHouse open-source project on my free time and so if there is interest from your side we could try to revive this PR.

I will try to provide the supporting discussion related to LIVE VIEWs and LIVE CHANNELs. Hopefully, it can be useful and will revive thе interest in this feature. As the PR states, the purpose is to add support for real-time command line and web applications with the web applications being the more important of the two.  First I will start with a general discussion and move on to some example use cases.

In general, when I think about a database, I think of it as a data store that I can ask a question and get an answer. Currently, most databases support asking a question and get a hopefully correct current answer. If the answer to a question is not static but changes over time, and changes are not consistent in time, in order to get an updated answer for the same question we have to reask the question over and over again at some fixed interval as there is no support for being notified when we should even re-ask the question and the best we can do is to poll for the new answer. 

However, in general, it would seem useful

1. Ask a question and know the current answer without the need to keep asking the database over and over again in the hope to stay current with the answer to the question.

2. Not bother the database with a question to which the answer has not changed. 

3. Instead of asking a question and then getting an answer and turning away, to keep listening so that we can get a new answer as soon as the database knows the new answer.

4. The database could always know the answer to some questions. 

Keeping these generalized ideas in mind, the functionality is identical to the change-feeds in RethinkDB (https://www.rethinkdb.com/docs/changefeeds/javascript/) and has some similarities to the percolators in the Elasticsearch (https://www.elastic.co/blog/percolator)

The use cases follow from the generalized points above.

One of the use cases would be a web application dashboard, similar to the one that can be constructed in Grafana when instead of setting a refresh rate for some queries the updates are received as soon as they are available. In this case, a complicated dashboard has to send a lot of queries over and over again. This PR attempts to provide PUSH functionality instead of currently available POLLing.
 
For example, a dashboard that provides real-time monitoring of user activity on a web site, or potentially looking at the real-time response to an advertising campaign where we want to adapt to viewers response in real-time instead of post processing or maybe even enable customization of our campaign per viewer based on their current behavior. Another potential example would be real-time monitoring of the massive amount of live data coming from the IoT device sensors. In all of these cases, we would want to combine analytics from the vast amounts of historical data with the most recent events and use one system to do it. ClickHouse is great for analytics so this PR adds the missing piece of combining historical analytics with the new data.   

The fundamental problem that this PR attempts to solve is to greatly simplify the implementation of a system when real-time results are needed and require executing non-trivial queries when new data is available. I guess the benefit of this PR
can be only measured in comparison to the complexity that is needed to implement this behavior without ClickHouse providing this functionality out of the box. The overall system is greatly simplified and the client code becomes efficient. 

As for the implementation, I do see how changes to Block and Datastreams would break backward compatibility and might be too drastic to be pulled in. 

We could look into restructuring the implementation and have a specific type of Block and Datastreams for processing these live streams, something like LiveBlock and LiveDatastreams, 
that will only be used for LIVE VIEWs and LIVE CHANNELs in an attempt 
to provide a less intrusive implementation.

Looking forward to discussing use cases and this feature in general.

**Comment by vzakaznikov** [comment]
I am working on a variant of this PR to meet the "not intrusive" requirement
so that BlockInfo and Datastreams do not have to be modified.
Unfortunately, we can't keep the full original functionality without being intrusive.
However, I believe we can get most of the functionality with some modifications which
can be a reasonable compromise. 

The plan is for the modifications to include the following major changes:

1. Support for the pure "WATCH table" query for LIVE VIEWs and LIVE CHANNELs will be dropped and an unsupported error will be returned. We can keep the original "WATCH table" query as reserved in the case that at some point in the future the BlockInfo can be modified to support the extra metadata fields that are needed for streams that carry multiple results for the same table or multiple results from different tables.

2. Support for the "WATCH table EVENTS" query will be added for LIVE VIEW and LIVE CHANNEL tables that will allow receiving change events. In the case of a LIVE VIEW, a change event is sent when the result of the query changes or in the case of a LIVE CHANNEL the result of one of the LIVE VIEW queries in the channel changes.  

The new "WATCH table EVENTS" query can be implemented using existing blocks and output formats. The query can be used by the clients to get real-time notifications when the result of a LIVE VIEW or one of the results of LIVE CHANNEL changes. This way the client can re-run the SELECT on the LIVE VIEW table to get the new result. Because HTTP connection can use keep-alive and the query result itself is cached in the memory, the performance penalties are minimized and the performance should still better than in the case of pure polling. 

At least this is what I have in mind. I am happy to discuss this further.

**Comment by javisantana** [comment]
@alexey-milovidov wouldn't a mat view with a table using URL engine would be useful to notify changes, like:

```
:) create table test_maser (a Int32) Engine=MergeTree order by tuple();
:) create table test_url (a Int32) Engine = URL('http://localhost:8080', 'CSV');
# i know it would need an aggregatingmergetree but just to notify would be enough
:) create materialized view watch_view to test_url as select count() from test_master;
:) insert into test_master values (1);
```

**Comment by alex-zaitsev** [comment]
@javisantana That was also my idea while ago to notify of changes. But looks more complicated comparing to select and wait for the data to appear

**Comment by javisantana** [comment]
totally, it's a poor mans version of that

**Comment by vzakaznikov** [comment]
Currently working on this in my private fork at https://github.com/vzakaznikov/ClickHouse/tree/liveview and once the first draft is ready, I will create a new pull request.

**Comment by Vxider** [comment]
Hi, I think Live View provide the abilities of streaming computing,  is the live view use  an incremental calculation? For example, performing a word count job on a table,  does it recalculate the entire table each time data is inserted ?

**Comment by vzakaznikov** [comment]
Hi @Vxider, the LIVE VIEW table implementation does use incremental computation as much as possible. The implementation uses the same approach as a distributed table. In the case of the query against a distributed table, the result is computed partially on each server and then merged on the
server where the query originated. The LIVE VIEW table uses the same approach, but in this case,
instead of having data on multiple servers the result is computed from the data which already has been processed and the new data block that has arrived. The result of the query is computed by merging
two partial results. The partial result for the processed data is cached in memory and when a new data block arrives the stored query is executed only against the new data block and then merged with the cached partial result.

The caching of partial result in memory requires that memory is available to store this data. In addition to the partial result, the current result of the query is also cached in memory. This provides for maximum speed when the new data block arrives but at the cost of memory consumption. Moreover, as the number of new data blocks increases the memory consumption goes up. As a temporary workaround, the query does get re-executed after every 64 new blocks to limit the number of partial results stored in memory so that to collapse the number of mergeable blocks. A better implementation
requires adding support for merging partial results if possible so that query re-execution is not necessary. 

You can check the latest version in https://github.com/yandex/ClickHouse/pull/5541 that provides a draft of an unintrusive version of LIVE VIEW tables.

**Pull request closed without merging**
