### PR TITLE
Send profile events for INSERT queries (previously only SELECT was supported)

### LINKED ISSUE #37241: clickhouse-client --print-profile-events not working for insert in non-interactive mode?
It seems `--print-profile-events --profile-events-delay-ms=-1` only works for select query but not insert.

For instance, `clickhouse-client --query="select 1" --print-profile-events --profile-events-delay-ms=-1` prints profile events like below.
```
[node1.some.cluster] 2022.05.14 07:07:55 [ 0 ] ContextLock: 12 (increment)
[node1.some.cluster] 2022.05.14 07:07:55 [ 0 ] MemoryTrackerUsage: 8704 (gauge)
[node1.some.cluster] 2022.05.14 07:07:55 [ 0 ] NetworkSendBytes: 57 (increment)
[node1.some.cluster] 2022.05.14 07:07:55 [ 0 ] NetworkSendElapsedMicroseconds: 84 (increment)
[node1.some.cluster] 2022.05.14 07:07:55 [ 0 ] Query: 1 (increment)
[node1.some.cluster] 2022.05.14 07:07:55 [ 0 ] RWLockAcquiredReadLocks: 1 (increment)
[node1.some.cluster] 2022.05.14 07:07:55 [ 0 ] RealTimeMicroseconds: 139 (increment)
[node1.some.cluster] 2022.05.14 07:07:55 [ 0 ] SelectQuery: 1 (increment)
[node1.some.cluster] 2022.05.14 07:07:55 [ 0 ] SelectedBytes: 1 (increment)
[node1.some.cluster] 2022.05.14 07:07:55 [ 0 ] SelectedRows: 1 (increment)
```

However, `echo -e "1\t2" | clickhouse-client --query="insert into aaa format TSV" --print-profile-events --profile-events-delay-ms=-1` shows nothing.
Note: you can use `create table aaa(a String, b String)engine=Memory` to create the test table.

### PR DESCRIPTION
**Pull request by azat**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Send profile events for INSERT queries (previously only SELECT was supported)

Reproducer:

    echo "1" | clickhouse-client --query="insert into function null('foo String') format TSV" --print-profile-events --profile-events-delay-ms=-1

But note, that in case of `clickhouse-local` they were implicitly supported, but only if query was long enough, i.e.:

    # yes | head -n100000 | clickhouse-local --query="insert into function null('foo String') format TSV" --print-profile-events --profile-events-delay-ms=-1
    [s1.ch] 2022.05.20 15:20:27 [ 0 ] ContextLock: 10 (increment)
    [s1.ch] 2022.05.20 15:20:27 [ 0 ] DiskReadElapsedMicroseconds: 29 (increment)
    [s1.ch] 2022.05.20 15:20:27 [ 0 ] IOBufferAllocBytes: 200000 (increment)
    [s1.ch] 2022.05.20 15:20:27 [ 0 ] IOBufferAllocs: 1 (increment)
    [s1.ch] 2022.05.20 15:20:27 [ 0 ] InsertQuery: 1 (increment)
    [s1.ch] 2022.05.20 15:20:27 [ 0 ] InsertedBytes: 1000000 (increment)
    [s1.ch] 2022.05.20 15:20:27 [ 0 ] InsertedRows: 100000 (increment)
    [s1.ch] 2022.05.20 15:20:27 [ 0 ] MemoryTrackerUsage: 1521975 (gauge)
    [s1.ch] 2022.05.20 15:20:27 [ 0 ] OSCPUVirtualTimeMicroseconds: 102148 (increment)
    [s1.ch] 2022.05.20 15:20:27 [ 0 ] OSReadChars: 135700 (increment)
    [s1.ch] 2022.05.20 15:20:27 [ 0 ] OSWriteChars: 8 (increment)
    [s1.ch] 2022.05.20 15:20:27 [ 0 ] Query: 1 (increment)
    [s1.ch] 2022.05.20 15:20:27 [ 0 ] RWLockAcquiredReadLocks: 2 (increment)
    [s1.ch] 2022.05.20 15:20:27 [ 0 ] ReadBufferFromFileDescriptorRead: 5 (increment)
    [s1.ch] 2022.05.20 15:20:27 [ 0 ] ReadBufferFromFileDescriptorReadBytes: 134464 (increment)
    [s1.ch] 2022.05.20 15:20:27 [ 0 ] RealTimeMicroseconds: 293747 (increment)
    [s1.ch] 2022.05.20 15:20:27 [ 0 ] SoftPageFaults: 382 (increment)
    [s1.ch] 2022.05.20 15:20:27 [ 0 ] TableFunctionExecute: 1 (increment)
    [s1.ch] 2022.05.20 15:20:27 [ 0 ] UserTimeMicroseconds: 102148 (increment)

Fixes: #37241 (cc @alexey-milovidov @zhicwu )

### CODE REVIEW

**Comment by kssenii** [comment]
> not used by the clickhouse-client for RAM/CPU usage

but it possibly can, later, so not really a caveat?

**Comment by azat** [comment]
>but it possibly can, later, so not really a caveat?

Not sure, usually you pass stdin/--file to the client in this case, and so you cannot use interactive mode.

**Comment by kssenii** [comment]
> Not sure, usually you pass stdin/--file to the client in this case, and so you cannot use interactive mode.

but progress can be shown for non-interactive mode

**Comment by azat** [comment]
I'm fine with caveats that I've found.

>but progress (+ RAM/CPU usage) can be shown for non-interactive mode

Indeed, and with this patch it will be rendered by the client.
Also I found one issue (with concurrent access) after this patch, that had been fixed now.

**Review by kssenii — APPROVED** [review]
lgtm

**Comment by zhicwu** [comment]
@azat, will DDL be supported as well? For example: `clickhouse-client --query="create database if not exists test" --print-profile-events --profile-events-delay-ms=-1`

**Comment by zhicwu** [comment]
> No, such queries will not provide ProfileEvents. But does this makes sense for DDL?

Good to know. Yes, it's probably useless for DDL, except ALTER UPDATE/DELETE.

> What event you are interested in?

Thanks @azat. As of now, `SelectedBytes` and `SelectedRows` for select queries, and `InsertedBytes` and `InsertedRows` for inserts, should be good enough. The purpose was to get consistent summary like `{"read_rows":"0","read_bytes":"0","written_rows":"0","written_bytes":"0","total_rows_to_read":"0"}` returned from http interface.

**Comment by kssenii** [comment]
@Mergifyio update

**Comment by kssenii** [comment]
> Stateless tests flaky check (address, actions) — Some queries hung, fail: 1, passed: 299

do you know why it hangs?

**Comment by azat** [comment]
>do you know why it hangs?

The problem is that now there is mutex for profile events and under thread fuzzer for some of runs 10 mins may not be enough:

```
2022-06-07 19:34:52 Thread 3 (Thread 0x7ff78de5d700 (LWP 609)):
2022-06-07 19:34:52 #0  __syscall () at ../base/glibc-compatibility/musl/x86_64/syscall.s:14
2022-06-07 19:34:52 #1  0x000000003e5553a6 in clock_nanosleep (clk=<optimized out>, flags=<optimized out>, req=<optimized out>, rem=<optimized out>) at ../base/glibc-compatibility/musl/clock_nanosleep.c:21
2022-06-07 19:34:52 #2  0x00000000368b0454 in sleepForNanoseconds (nanoseconds=<optimized out>) at ../base/base/sleep.cpp:48
2022-06-07 19:34:52 #3  0x000000000d82cda2 in DB::injection (yield_probability=<optimized out>, migrate_probability=<optimized out>, sleep_probability=<optimized out>, sleep_time_us=<optimized out>) at ../src/Common/ThreadFuzzer.cpp:242
2022-06-07 19:34:52 #4  0x000000000d82c6f5 in DB::ThreadFuzzer::signalHandler () at ../src/Common/ThreadFuzzer.cpp:253
2022-06-07 19:34:52 #5  <signal handler called>
2022-06-07 19:34:52 #6  0x00007ff88d23e84b in sched_setaffinity () from /lib/x86_64-linux-gnu/libc.so.6
2022-06-07 19:34:52 #7  0x000000000d82cc6f in DB::injection (yield_probability=<optimized out>, migrate_probability=<optimized out>, sleep_probability=<optimized out>, sleep_time_us=<optimized out>) at ../src/Common/ThreadFuzzer.cpp:232
2022-06-07 19:34:52 #8  0x000000000d82cedd in pthread_mutex_unlock (arg=<optimized out>) at ../src/Common/ThreadFuzzer.cpp:317
2022-06-07 19:34:52 #9  0x000000000d6fdd8a in std::__1::lock_guard<std::__1::mutex>::~lock_guard (this=<optimized out>) at ../contrib/libcxx/include/__mutex_base:97
2022-06-07 19:34:52 #10 DB::ThreadGroupStatus::getProfileEventsCountersAndMemoryForThreads (this=0x0) at ../src/Common/ThreadStatus.cpp:93
2022-06-07 19:34:52 #11 0x000000002d890086 in ProfileEvents::getProfileEvents (server_display_name=..., profile_queue=..., block=..., last_sent_snapshots=...) at ../src/Interpreters/ProfileEventsExt.cpp:120
2022-06-07 19:34:52 #12 0x000000002fea97d7 in DB::TCPHandler::sendProfileEvents (this=<optimized out>) at ../src/Server/TCPHandler.cpp:870
2022-06-07 19:34:52 #13 0x000000002fea1173 in DB::TCPHandler::sendInsertProfileEvents (this=0x0) at ../src/Server/TCPHandler.cpp:896
2022-06-07 19:34:52 #14 DB::TCPHandler::readDataNext (this=<optimized out>) at ../src/Server/TCPHandler.cpp:591
2022-06-07 19:34:52 #15 0x000000002fe9d676 in DB::TCPHandler::processInsertQuery()::$_0::operator()<DB::PushingPipelineExecutor>(DB::PushingPipelineExecutor&) const (executor=..., this=<optimized out>) at ../src/Server/TCPHandler.cpp:649
```

```
2022-06-07 19:34:52         "elapsed": 714.65320192,
2022-06-07 19:34:52         "is_cancelled": 0,
2022-06-07 19:34:52         "is_all_data_sent": 0,
2022-06-07 19:34:52         "read_rows": "18754767",
2022-06-07 19:34:52         "read_bytes": "187547670",
2022-06-07 19:34:52         "total_rows_approx": "0",
2022-06-07 19:34:52         "written_rows": "18754767",
2022-06-07 19:34:52         "written_bytes": "187547670",
2022-06-07 19:34:52         "memory_usage": "12593182",
2022-06-07 19:34:52         "peak_memory_usage": "14690334",
2022-06-07 19:34:52         "query": "insert into function null('foo String') format TSV",
2022-06-07 19:34:52         "thread_ids": [
2022-06-07 19:34:52             "609"
2022-06-07 19:34:52         ],
```

So I've decreased number of rows for this test and rebased.

**Review by kssenii — APPROVED** [review]

**Comment by kssenii** [comment]
> 01183_custom_separated_format_http, 01184_long_insert_values_huge_strings

not related to changes

**Pull request merged**
