### PR TITLE
Vectorize AssociativeGenericApplierImpl::apply

### PR DESCRIPTION
**Pull request by ZhiguoZh**
This commit achieved the auto-vectorization by redefining numerical values of ternary representations and corresponding implementations of And/Or operators, caching the intermediate ternary values in a continuous range of memory for the SIMD instructions to consume, and removing the short-circuit for the ternary logic evaluation.

### Changelog category (leave one):
- Performance Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
As a follow-up of #42214, this PR tries to optimize the column-wise ternary logic evaluation by achieving auto-vectorization. In the performance test of this [microbenchmark](https://github.com/ZhiguoZh/ClickHouse/blob/20221123-ternary-logic-opt-example/src/Functions/examples/associative_applier_perf.cpp), we've observed a peak **performance gain** of **21x** on the ICX device (Intel Xeon Platinum 8380 CPU).

This change is very similar to the one we introduced in #42214. However, we found that simply removing the short-circuit could not efficiently vectorize the ternary logic evaluation. Two major causes are identified in our analysis:
1. To share the exact And/Or operator implementation with binary one, the ternary value is defined as: True(0xFF), Null(0x01) and False(0x00). And to determine the ternary values with data (Zero/Non-zero) and null map column (if the entry is Null), the original implementation utilized the if-else clause, which hinders the generation of vectorized code.
2. Unlike the binary logic functions, whose operand is simply ColumnUInt8, the ternary logic functions would take as arguments the ColumnNullables which contain a ColumnUInt8 null map column and a Column{UInt8, UInt16, UInt32, UInt64, …} data column. The ClickHouse implemented getter functions for each type of data column. As a result, the getter functions would be called for each entries in the columns, and at the same time hinder the vectorization.

To overcome the above problems, we firstly redefined the ternary representations which are feasible for vectorization, we then replaced the getter functions with intermediate columns containing the ternary values for the SIMD instructions to consume, and we finally removed the short-circuit evaluation to ensure all rows share the exact code path.

Meanwhile, this optimization need an **O(m*n)** memory cost for the intermediate ternary values of **n** columns with **m** elements.

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by ZhiguoZh** [comment]
This method, AssociativeGenericApplierImpl::apply, could handle columns of 3 types in a generic approach: the null-only column (x->onlyNull() == true), the nullable column and non-nullable column. And the [microbenchmark](https://github.com/ZhiguoZh/ClickHouse/blob/20221123-ternary-logic-opt-example/src/Functions/examples/associative_applier_perf.cpp) has been designed accordingly to measure the elapsed time of **_OperationApplier<Op, AssociativeGenericApplierImpl>::apply_** method (**_Op_** is **_And/Or_** operator) which performs ternary logic calculations on N (N=1, 2, … , 8) 10M-element columns for these cases. And as the zero ratio of data would determine the overall performance in the baseline, we take it as a variable in our performance test, besides the column count N. We then compare the elapsed time with and without this change for evaluating the performance gain on the ICX server (Intel Xeon Platinum 8380 CPU), which lists as follows:
## 1. Null-Only Columns
In this case, the **_And_** and **_Or_** operators are applied to N (1, 2, ..., 8) **_ColumnNullable_**, whose **_NestedColumn_** is the **_ColumnNothing_**. This change could accelerate this method by **9.2x to 15.5x** for both operators: 
image

## 2. Non-Nullable Columns
The columns of **_ColumnVector_** could also be arguments of the ternary logic evaluation, and we took the **_ColumnVector_<UInt8>** as the specific example, which shows a peak performance gain of **~30x** for both **_And_** and **_Or_** operators on 2 columns with the zero ratio of 0.4 and 0.6:
image

## 3. Nullable Columns 
The nullable column (**_ColumnNullable_**) is quite complicated as its **_NestedColumn_** could be multiple types, including UInt8, UInt16, UInt32, UInt64, Int8, Int16, Int32, Int64, Float32, Float64. We found the all performance gains reach their peaks when applying the  **_And_** and **_Or_** operators on 2 columns with the zero ratio of 0.4 and 0.6, and will not address it in the later report. The report would be categorized by data type (integer and float) and data width for direct comparison.
### 3.1 UInt8 and Int8
The peak gain is **~20x** and **all** other cases could benefit from this change.
UInt8
image
Int8
image
### 3.2 UInt16 and Int16
The peak gain is **~10x** and **all** other cases could benefit from this change.
UInt16
image
Int16
image
### 3.3 UInt32 and Int32
The peak gain exceeds **~5x**. Though, some regressions are observed in some extreme cases with all-zero or all-non-zero data, the geomean of the improvement of the cases still reaches **2.29x**.
UInt32
image
Int32
image
### 3.4 UInt64 and Int64
The peak gain is only **2.2x-2.6x**. And due to the regressions near the "border" of the tables, we could only slightly improve the geomean of elapsed time by **1.055x** and **1.013x** for UInt64 and Int64 respectively. 
UInt64
image
Int64
image
### 3.5 Float32 and Float64
For Float32, the peak gain is **5.5x-6.4x** and the geomean of the improvement of the cases reaches **2.54x**.
Float32
image
For Float64, the peak gain is **2.5x-2.9x** and the geomean of the improvement of the cases reaches **1.14x**.
Float64
image

**Comment by ZhiguoZh** [comment]
We could also note that the performance gain almost halved when the column data width changes from 8 to 16, 32 and finally to 64. This should be closely related the SIMD register width: given fixed register width, when the bit width of data doubles, the data processed by a single instruction is halved, and thus the data throughput is almost halved. 

As SSE is the default instruction flag for ClickHouse, we measured the performance data with only SSE enabled. To mitigate the regression and to further improve the peak gains, we turned on AVX and AVX2 options, hoping the wider register could bring additional gain. And as the following figures show, for ColumnNullable(UInt64), one of the least-optimized cases, with AVX/AVX2, the performance for each case is almost doubled, and the geomean of the improvements has increased from **1.05x** to **1.99x**.

ColumnNullable(Uint64) with Only SSE
image
ColumnNullable(Uint64) with AVX/AV2
image

**Comment by nickitat** [comment]
@ZhiguoZh pls take a look on failed tests

**Comment by ZhiguoZh** [comment]
> @ZhiguoZh pls take a look on failed tests

OK, got it, thanks Nikita!

**Comment by ZhiguoZh** [comment]
@nickitat, I've fixed the issues we identified last week. And it seems the failed 3 cases of stress test are not caused by this change. I think this PR is ready for your further review. Thanks!

**Comment by ZhiguoZh** [comment]
Thanks for your review and comment!

As you suggested, this optimization would regress significantly in the marginal cases of 32- and 64-byte data types, and I've tried to further optimize them in the latter commit "**Optimize TernaryValueBuilder for ColumnNullable**", which handles the insufficient SIMD register usage and significantly enhance the performance of the deteriorative cases.

Let's take the UInt64 and UInt32 as examples, and this results also apply to other cases with the same data width:
### UInt64
As the following figures show, this optimization could almost double the performance of all the cases of the UInt64: the peak performance gain has exceeded **5x** and the regressed cases have shrunk to all-zero and all-none-zero ones, and the worst performance impact also increased from **0.27x** to **0.53x**. 

Before optimization
image

After optimization
image

### UInt32
Likewise, UInt32 also benefits from this optimization: the peak performance gain improved from **5.78x** to **8.41x**, only 3 extreme all-zero cases regressed, and the worst performance impact has increased from **0.56x** to **0.77x**. 

Before optimization
image

After optimization
image

**Comment by ZhiguoZh** [comment]
As you may note, the regressed cases in the form are actually the extreme cases. For example, we found in UInt64-After-Optimization form, the worst performance impact is 0.53x (or regressed by 47%), however, this low point is reached **only when** the OR operator is applied on the **8 UInt64-nullable column** with **all** entries are **not null** and are **non-zero**.  I think this case could be hardly encountered in real scenario.

And I've tried to partially apply the optimizations only on 8- and 16-bit data, however found it hard to achieve as this optimization works under the condition that all the ternary values are evaluated and stored in contiguous memory spaces for the vectorized logical operator to consume. It seems we could only choose to entirely switch to the optimized path or keep the original one.

The overall performance gain is largely determined by the false/true distribution of user data, which we could not know in advance, however, we've achieved great improvements in most cases except the few extreme ones. Given the existing performance data, I think the advantages overweigh the disadvantages. WDYT?

**Comment by ZhiguoZh** [comment]
Hi Nikita, as the latter commit could to some degree mitigate regressions in the marginal cases, I'm not sure if it is still your concern, could you kindly share with me your insights so that we could move on to the next phase? Thanks a lot!

@nickitat

**Comment by nickitat** [comment]
@ZhiguoZh my apologies for the delayed response. imo it is fine, we can neglect this subtle slowdowns, apart from them everything is awesome.

**Comment by nickitat** [comment]
> > @ZhiguoZh my apologies for the delayed response. imo it is fine, we can neglect this subtle slowdowns, apart from them everything is awesome.
> 
> It's OK, Nikita, Actually I'd appreciate you for continuous help!
> 
> BTW, do you know if there is any real-scenario workload, like SSB, that could reflect the performance gain of this optimization of the method, AssociativeGenericApplierImpl::apply? My team is seeking one for the optimization evaluation. Thanks!

I'm afraid it could be not easy, because contribution of logical functions should be small compared to io/aggr/join.

**Comment by nickitat** [comment]
test failures are irrelevant.

**Comment by ZhiguoZh** [comment]
> > > @ZhiguoZh my apologies for the delayed response. imo it is fine, we can neglect this subtle slowdowns, apart from them everything is awesome.
> > 
> > 
> > It's OK, Nikita, Actually I'd appreciate you for continuous help!
> > BTW, do you know if there is any real-scenario workload, like SSB, that could reflect the performance gain of this optimization of the method, AssociativeGenericApplierImpl::apply? My team is seeking one for the optimization evaluation. Thanks!
> 
> I'm afraid it could be not easy, because contribution of logical functions should be small compared to io/aggr/join. but on a synthetic queries from perf tests the difference is clearly visible.

OK, got it! Thanks again for your review and acceptance of this patch!

**Pull request merged**
