### PR TITLE
Make type names in `SHOW COLUMNS` dependent on connection type

### PR DESCRIPTION
**Pull request by rschu1ze**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
`SHOW COLUMNS` now displays MySQL's equivalent data type name when the connection was made through the MySQL protocol. Previously, this was the case when setting `use_mysql_types_in_show_columns = 1`. The setting is retained but made obsolete.

### CODE REVIEW

**Comment by robot-clickhouse-ci-1** [comment]
*This is an automated comment for commit 5421084205b2cefff97f5fca536c1d80aa357878 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/56277/5421084205b2cefff97f5fca536c1d80aa357878/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td><a href="https://github.com/ClickHouse/ClickHouse/actions/runs/6737331218">✅ success</a></td></tr>
<tbody>
</table>
</details>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/56277/5421084205b2cefff97f5fca536c1d80aa357878/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Comment by rschu1ze** [comment]
@slvrtrn That's what we planned for a while. I'd have two kind requests:

1. should we make the same kind of change for `mysql_map_string_to_text_in_show_columns` and `mysql_map_fixed_string_to_text_in_show_columns`? (probably not since QuickSight / Looker Studio / Tableau Online) require different settings.

2. You are an experienced MySQL tester. Would you like to check that the `SHOW COLUMNS` results is as expected when connecting via MySQL? Afais, the only way to test this is an integration test :-/

Mental note to myself: The comments about `use_mysql_types_in_show_columns` in https://clickhouse.com/docs/en/integrations/quicksight are obsolete. --> fix in clickhouse-docs repo.

**Comment by slvrtrn** [comment]
@rschu1ze
1. We will have to keep these settings, but these should anyway work only when using MySQL interface
2. I will write a Python test that uses a real MySQL client to verify that (mostly a duplicate of what we have in `02775_show_columns_mysql_compatibility`)

**Comment by Algunenano** [comment]
> Afais, the only way to test this is an integration test

There is one stateless test at least -> 01176_mysql_client_interactive, `${MYSQL_CLIENT_BINARY}` should be available in non-fasttests runs AFAICR

**Comment by rschu1ze** [comment]
> There is one stateless test at least -> 01176_mysql_client_interactive, `${MYSQL_CLIENT_BINARY}` should be available in non-fasttests runs AFAICR

Thanks, I'll make a similar test like that one.

**Review by slvrtrn — APPROVED** [review]

**Pull request merged**
