### PR TITLE
Prohibit toUnixTimestamp(Date())

### LINKED ISSUE #7479: toUnixTimestamp wrong behaviour for Date argument.
```
SELECT
    toDate('2019-01-01') AS date,
    toUnixTimestamp(date) AS UnixTimestamp

┌───────date─┬─UnixTimestamp─┐
│ 2019-01-01 │         17897 │
└────────────┴───────────────┘
```

Expected result : 1546300800
the same as toUnixTimestamp(toDateTime(date))

### PR DESCRIPTION
**Pull request by azat**
Changelog category (leave one):
- Backward Incompatible Change

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Prohibit toUnixTimestamp(Date()) (before it just returns UInt16 representation of Date)

Detailed description / Documentation draft:
Making it implicitly cast to Date() correctly does not looks correct, since before it returns somewhat unexpected result:

    SELECT toUnixTimestamp(today())

    ┌─toUnixTimestamp(today())─┐
    │                    18591 │
    └──────────────────────────┘

And if you want old behavior you can still use:

    SELECT toUnixTimestamp(toUInt16(today()))

    ┌─toUnixTimestamp(toUInt16(today()))─┐
    │                              18591 │
    └────────────────────────────────────┘

Closes: #7479

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
Ok.

It's better to make a function

toUnixTimestamp(date, [timezone])

that will first convert to datetime according to the timezone and then return a unix timestamp.

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
The original behaviour was intentional, but the name is not appropriate (better would be to name it `toUnixDay` but `toUInt16` is enough).

**Comment by den-crane** [comment]
issue: https://github.com/ClickHouse/ClickHouse/issues/7479

**Comment by azat** [comment]
@alexey-milovidov maybe it worth marking it as "Backward Incompatible Change" instead of "Improvement"?

**Comment by alexey-milovidov** [comment]
Ok. @azat Also need to cleanup perf test.

**Comment by azat** [comment]
@alexey-milovidov can you also remove the "pr-improvement" label? (although note sure that it is used for something, i.e. changelog generation)

**Comment by alexey-milovidov** [comment]
Changelog is using PR description - it's Ok.

**Comment by azat** [comment]
>Performance — 6 errors, 4 too long, 8 faster, 7 slower, 40 unstable

Failures looks unrelated (after date_time_short has been updated)

**Comment by den-crane** [comment]
An error message is slightly confusing for newbies

SELECT
    toUnixTimestamp(toDate('2020-01-01'), 'Europe/Moscow')

DB::Exception: Illegal column UInt16 of first argument of function toUnixTimestamp: 
While processing toUnixTimestamp(toDate('2020-01-01')

UInt16, Not Date.

**Comment by alexey-milovidov** [comment]
Yes, it should be checked on type, not by column.

**Pull request merged**
