### PR TITLE
Add ability to specify PRIMARY KEY without ORDER BY

### LINKED ISSUE #15591: Allow to specify PRIMARY KEY near the list of columns
`CREATE TABLE test (x Int32, y Int32, s String, PRIMARY KEY (x, y)) ENGINE = MergeTree;`
should be equivalent to
`CREATE TABLE test (x Int32, y Int32, s String) ENGINE = MergeTree PRIMARY KEY (x, y);`

### PR DESCRIPTION
**Pull request by alesapin**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Now it's possible to specify `PRIMARY KEY` without `ORDER BY` for MergeTree table engines family. Closes #15591.

### CODE REVIEW

**Review by CurtizJ — APPROVED** [review]

**Comment by amosbird** [comment]
Perhaps we can serialize the metadata with `ORDER BY` clause generated?

**Comment by alesapin** [comment]
> Perhaps we can serialize the metadata with `ORDER BY` clause generated?

Yes, but it can be surprising for the user. You just typed one `CREATE` query, and `SHOW CREATE TABLE` shows you different one.

**Comment by amosbird** [comment]
> > Perhaps we can serialize the metadata with `ORDER BY` clause generated?
> 
> Yes, but it can be surprising for the user. You just typed one `CREATE` query, and `SHOW CREATE TABLE` shows you different one.

Currently it already shows different things (such as settings index_granularity = 8192)

**Comment by alesapin** [comment]
> > > Perhaps we can serialize the metadata with `ORDER BY` clause generated?
> > 
> > 
> > Yes, but it can be surprising for the user. You just typed one `CREATE` query, and `SHOW CREATE TABLE` shows you different one.
> 
> Currently it already shows different things (such as settings index_granularity = 8192)

Well, you've convinced me)

**Review by amosbird — APPROVED** [review]

**Pull request merged**
