### PR TITLE
Improve check access in table functions

### PR DESCRIPTION
**Pull request by taiyang-li**
Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
For table function `s3cluster` or `HDFSCluster` or `hive`, we can't get right `AccessType` by `StorageFactory::instance().getSourceAccessType(getStorageTypeName())`. This pr fix it.

### CODE REVIEW

**Comment by kssenii** [comment]
> For table function s3cluster or HDFSCluster or hive, we can't get right AccessType by StorageFactory::instance().getSourceAccessType(getStorageTypeName()).

why?

**Comment by taiyang-li** [comment]
For example,  in `TableFunctionS3Cluster`,  function `getStorageTypeName` returns `S3Cluster`.  

When execute `StorageFactory::instance().getSourceAccessType(getStorageTypeName())` in `ITableFunction::execute`,  we will get `AccessType::NONE` instead of `AccessType::S3` because `S3Cluster` is not registered in `StorageFactory` 


See 
``` cpp

AccessType StorageFactory::getSourceAccessType(const String & table_engine) const
{
    auto it = storages.find(table_engine);
    if (it == storages.end())
        return AccessType::NONE;
    return it->second.features.source_access_type;
}
```

**Review by kssenii — APPROVED** [review]

**Comment by kssenii** [comment]
@Mergifyio update

**Comment by kssenii** [comment]
Fast test still fails `Fast test (actions) — fail: 1`

**Comment by taiyang-li** [comment]
> 

Fixed.

**Comment by kssenii** [comment]
@taiyang-li can you please merge with master?

**Comment by taiyang-li** [comment]
> @taiyang-li can you please merge with master?

done

**Comment by kssenii** [comment]
@taiyang-li can you please merge with master once again?

**Comment by taiyang-li** [comment]
> @taiyang-li can you please merge with master once again?

done

**Comment by taiyang-li** [comment]
Failed tests not  related with this PR.

**Pull request merged**
