### PR TITLE
fix performance: MergeTreeRangeReader immediately return if pre where matc…

### PR DESCRIPTION
**Pull request by kangtiann**
Changelog category (leave one):
- Performance Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Improve MergeTree read performance, if per where has 0 rows, immediately return.

> Information about CI checks: https://clickhouse.tech/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by kitaisreal** [comment]
https://github.com/Mergifyio update

**Comment by kitaisreal** [comment]
@Mergifyio update

**Comment by kitaisreal** [comment]
@kangtiann please sign in CLA license

**Comment by kitaisreal** [comment]
@kangtiann it seems that this logic is important, please check tests.

**Comment by kangtiann** [comment]
It's my fault, I see that `continueReadingChain` done some thing to finish stream.


```cpp
Columns MergeTreeRangeReader::continueReadingChain(ReadResult & result, size_t & num_rows)
{
    Columns columns;
    num_rows = 0;
    
    if (result.rowsPerGranule().empty())  /// Mark: finish read at this place....
    {
        /// If zero rows were read on prev step, than there is no more rows to read.
        /// Last granule may have less rows than index_granularity, so finish reading manually.
        stream.finish();
        return columns;
    }
```

**Comment by kangtiann** [comment]
> CLA

Need help，Any ideas with  Can not open CLA website in China ？

image

**Comment by kitaisreal** [comment]
Need to ask @blinkov.

**Comment by alexey-milovidov** [comment]
The service "CLA Assistant" is notoriously annoying.
I've created three issues in their repo: #835, #836, #837.

**Comment by kangtiann** [comment]
> 

Thanks ~

**Comment by kitaisreal** [comment]
@kangtiann should this be closed ? Seems like this problem is already handled.

**Comment by kitaisreal** [comment]
@kangtiann will close it for now. If this pull request handle some additional issues in reader lets reopen.

**Pull request closed without merging**
