### PR TITLE
Fix if condition in #63151

### PR DESCRIPTION
**Pull request by zvonand**
Fix `if` that will never be true. https://github.com/ClickHouse/ClickHouse/pull/63151#discussion_r1888943808
Cc @devcrafter 

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Run only fuzzers related jobs (libFuzzer fuzzers, AST fuzzers, etc.)
- [ ]  Exclude: AST fuzzers
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-ch-test-poll3** [comment]
*This is an automated comment for commit e8efa7c5bb851d41370f863e4794f684d96289fd with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/73504/e8efa7c5bb851d41370f863e4794f684d96289fd/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/bde0c510332b8d112b6f6e2ade75a9e7c54b5abe/docs_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Review by devcrafter — APPROVED** [review]

**Comment by devcrafter** [comment]
AST fuzzer (debug) — Logical error: 'Block structure mismatch in QueryPipeline stream: different ... - https://github.com/ClickHouse/ClickHouse/issues/71217

**Comment by zvonand** [comment]
No other fails exist

**Comment by devcrafter** [comment]
> No other fails exist

Please update your branch with master

**Comment by zvonand** [comment]
@devcrafter CI is green

**Pull request merged**
