### PR TITLE
`column_length` is not updated in `ColumnTuple::insertManyFrom`

### LINKED ISSUE #66591: Invalid number of rows in Chunk column Const(UInt8)
**Describe the bug**

https://s3.amazonaws.com/clickhouse-test-reports/66413/9c1532e02f5f1dfeb2f3833afe585e26d08ccbf0/ast_fuzzer__ubsan_.html

```
SELECT * FROM (SELECT tuple(),  1 GROUP BY greatCircleAngle(toNullable(1048575), 257, toInt128(-9223372036854775808), materialize(1048576)) WITH TOTALS) AS t, (SELECT greatCircleAngle(toUInt256(1048575), 257, toNullable(-9223372036854775808), 1048576), 1048575,  2) AS u
```

Error: 

```
2024.07.16 12:49:02.519439 [ 6727 ] {0fdfc1bf-2bc2-48f6-85eb-9b775faaa36d} <Fatal> : Logical error: 'Invalid number of rows in Chunk column Const(UInt8) position 1: expected 0, got 1'.
2024.07.16 12:49:02.626941 [ 6727 ] {0fdfc1bf-2bc2-48f6-85eb-9b775faaa36d} <Fatal> : Stack trace (when copying this message, always include the lines below):

0. ./contrib/llvm-project/libcxx/include/exception:141: Poco::Exception::Exception(String const&, int) @ 0x0000000033838df4
1. /home/ubuntu/ClickHouse/build/./src/Common/Exception.cpp:110: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000001aa83aae
2. DB::Exception::Exception(PreformattedMessage&&, int) @ 0x000000000a73a22c
3. DB::Exception::Exception<String, String, String>(int, FormatStringHelperImpl<std::type_identity<String>::type, std::type_identity<String>::type, std::type_identity<String>::type>, String&&, String&&, String&&) @ 0x000000000a918f60
4. /home/ubuntu/ClickHouse/build/./src/Processors/Chunk.cpp:79: DB::Chunk::checkNumRowsIsConsistent() @ 0x000000002c983a25
5. ./contrib/llvm-project/libcxx/include/vector:590: DB::JoiningTransform::transform(DB::Chunk&) @ 0x000000002d013921
6. ./contrib/llvm-project/libcxx/include/__utility/swap.h:36: DB::JoiningTransform::work() @ 0x000000002d012552
7. ./contrib/llvm-project/libcxx/include/list:588: DB::ExecutionThreadContext::executeTask() @ 0x000000002c9dde8e
8. /home/ubuntu/ClickHouse/build/./src/Processors/Executors/PipelineExecutor.cpp:273: DB::PipelineExecutor::executeStepImpl(unsigned long, std::atomic<bool>*) @ 0x000000002c9c4c11
9. /home/ubuntu/ClickHouse/build/./src/Processors/Executors/PipelineExecutor.cpp:381: void std::__function::__policy_invoker<void ()>::__call_impl<std::__function::__default_alloc_func<DB::PipelineExecutor::spawnThreads()::$_0, void ()>>(std::__function::__policy_storage const*) @ 0x000000002c9c6b35
10. ./contrib/llvm-project/libcxx/include/__functional/function.h:0: ? @ 0x000000001ac26e59
11. ./src/Common/ThreadPool.h:252: ThreadFromGlobalPoolImpl<false, true>::ThreadFromGlobalPoolImpl<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>(void&&)::'lambda'()::operator()() @ 0x000000001ac2e03d
12. ./contrib/llvm-project/libcxx/include/__functional/function.h:0: ? @ 0x000000001ac2089c
13. ./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:302: void* std::__thread_proxy[abi:v15007]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void ThreadPoolImpl<std::thread>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>>(void*) @ 0x000000001ac2a79f
14. asan_thread_start(void*) @ 0x000000000a6eee39
15. ? @ 0x00007f32d6119609
16. ? @ 0x00007f32d603e353
```

**How to reproduce**

Fails on current master with `LOGICAL_ERROR` https://fiddle.clickhouse.com/27d7dbdf-830c-46d4-8747-cb2dee6ced64
Fails with another error on latest stable (`24.5`): https://fiddle.clickhouse.com/42e49357-ef61-4302-9d2b-f3ea02e86747

### PR DESCRIPTION
**Pull request by lgbo-ustc**
### Changelog category (leave one):

- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

`column_length` is not updated in `ColumnTuple::insertManyFrom`.

Fix https://github.com/ClickHouse/ClickHouse/issues/66591

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
Add a test.

**Comment by alexey-milovidov** [comment]
Merge this PR into yours please: https://github.com/ClickHouse/ClickHouse/pull/66623

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
Ok, but the commits from `fix-clang-tidy-2` are not merged, let's merge it here to avoid waiting...

**Comment by robot-clickhouse** [comment]
*This is an automated comment for commit c7091578fcfe3a92a555cbddc461cb7fb847389f with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/66626/c7091578fcfe3a92a555cbddc461cb7fb847389f/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/64f947c3d742791e3f1e4c4562fc548584fe270e/docs_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Comment by alexey-milovidov** [comment]
@lgbo-ustc builds failed due to an error in AWS S3.
Could you please merge with the master branch?

**Pull request merged**
