### PR TITLE
Fix serialization of parameterized view parameters

### LINKED ISSUE #62282: Parametrized views with non-literal const arguments
```
:) CREATE VIEW dummy_daily_stat AS select event_date, count() from system.query_log WHERE event_date = {date:Date} group by event_date;

CREATE VIEW dummy_daily_stat AS
SELECT
    event_date,
    count()
FROM system.query_log
WHERE event_date = {date:Date}
GROUP BY event_date;

:) select * from dummy_daily_stat(date = '2024-04-03');

SELECT *
FROM dummy_daily_stat(date = '2024-04-03')

┌─event_date─┬─count()─┐
│ 2024-04-03 │      10 │
└────────────┴─────────┘

:) select * from dummy_daily_stat(date = yesterday());

SELECT *
FROM dummy_daily_stat(date = yesterday())

DB::Exception: Substitution `date` is not set. (UNKNOWN_QUERY_PARAMETER)

```

Probably just substituting the const arguments with literal in the AST should work.

### PR DESCRIPTION
**Pull request by shiyer7474**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fixes https://github.com/ClickHouse/ClickHouse/issues/62282. Removed the call to `convertFieldToString()` and added datatype specific serialization code. Parameterized view substitution was broken for multiple datatypes when parameter value was a function or expression returning datatype instance.  

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by shiyer7474** [comment]
Details : `Field `is unaware of Date/Date32 types and so `convertFieldToString()` serializes the integer value of a Date/Date32 into a simple number string. This integer value is of course the number of days elapsed since epoch (01/01/1970). Thus a date like ‘2024-07-22’ has an internal integer value of 19926 and `convertFieldToString() `will serialize this date as “19926”. During deserialization in `ReplaceQueryParameterVisitor(),` `SerializationDate::deserializeText()->readDateText()` is called and that function will not understand “19926” and throws an exception.

A possible quick fix specific to Date/Date32 would have been to just enhance` readDateTextFallback()` to successfully parse a string like “19926” by treating the string as the number of days since epoch. But that is new behaviour and could break existing applications. 

But a fix restricted to `readDateTextFallback()` is insufficient when passing values of UUID/IPv4 datatypes where again `convertFieldToString()` differs from corresponding data type deserialization.

This patch now just implements the simple technique of using data type specific serialization. A temporary column of the real data type is instantiated from the constant value and the appropriate serialization interface is used to convert value to text. 

Testcase added to cover Date/Date32/UUID/IP datatypes

**Comment by robot-ch-test-poll2** [comment]
*This is an automated comment for commit 0772ed7f6ac92bb2e016e5db00e85deafeecb127 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/67654/0772ed7f6ac92bb2e016e5db00e85deafeecb127/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

**Review by kssenii — APPROVED** [review]

**Comment by shiyer7474** [comment]
> _This is an automated comment for commit [0772ed7](https://github.com/ClickHouse/ClickHouse/commit/0772ed7f6ac92bb2e016e5db00e85deafeecb127) with description of existing statuses. It's updated for the latest CI running_
> 
> [❌ Click here](https://s3.amazonaws.com/clickhouse-test-reports/67654/0772ed7f6ac92bb2e016e5db00e85deafeecb127/ci_running.html) to open a full report in a separate page
> 
> Check name	Description	Status
> Stateless tests	Runs stateless functional tests for ClickHouse binaries built in various configurations -- release, debug, with sanitizers, etc	[❌ failure](https://s3.amazonaws.com/clickhouse-test-reports/67654/0772ed7f6ac92bb2e016e5db00e85deafeecb127/stateless_tests__release__old_analyzer__s3__databasereplicated__[1_4].html)
> Upgrade check	Runs stress tests on server version from last release and then tries to upgrade it to the version from the PR. It checks if the new server can successfully startup without any errors, crashes or sanitizer asserts	[❌ failure](https://s3.amazonaws.com/clickhouse-test-reports/67654/0772ed7f6ac92bb2e016e5db00e85deafeecb127/upgrade_check__debug_.html)
> Successful checks

Checked the 2 failures. The failure in `Stateless tests` is in "`stateless_tests__release__old_analyzer__s3__databasereplicated_`. The testcase added in this PR is failing with the old analyzer. I will add `allow_experimental_analyzer=1 `to the test and push the commit

The 2nd failure in `Upgrade check` regarding "Changed settings" is not related to this PR, let me check if there is some history

Changed settings are not reflected in settings changes history (see changed_settings.txt) | FAIL
-- | --
┌─name─────────────────────────────────────────────┬─new_value─┬─old_value─┐ 1. │ merge_tree_min_bytes_per_task_for_remote_reading │ 2097152   │ 4194304   │    └──────────────────────────────────────────────────┴───────────┴───────────┘

**Comment by shiyer7474** [comment]
The 2 failures in the 1st test run have gone, including the fix to the new test.

In the 2nd run, following are the errors :

**1.[Tests_2 / s (Stateless tests (ubsan), func-tester) / Stateless tests (ubsan)-1]**
```
2024-08-03 10:28:30 00993_system_parts_race_condition_drop_zookeeper:                       [ OK ] 61.37 sec.
Recursive internal problem.
2024-08-03 10:35:32 00992_system_parts_race_condition_zookeeper_long:                       [ FAIL ] 412.24 sec.
2024-08-03 10:35:32 Reason: return code:  210
2024-08-03 10:35:32 Code: 210. DB::NetException: Connection refused (localhost:9000). (NETWORK_ERROR)
2024-08-03 10:35:32 
2024-08-03 10:35:32 Code: 210. DB::NetException: Connection refused (localhost:9000). (NETWORK_ERROR)
2024-08-03 10:35:32 
2024-08-03 10:35:32 Code: 210. DB::NetException: Connection refused (localhost:9000). (NETWORK_ERROR)
2024-08-03 10:35:32 
```


Test name | Test status | Test time, sec.
-- | -- | --
00965_shard_unresolvable_addresses | SERVER_DIED | 0.0
00992_system_parts_race_condition_zookeeper_long | SERVER_DIED | 412.24
Server died | FAIL | 0.0
01624_soft_constraints | BROKEN | 15.17
02944_variant_as_common_type | BROKEN | 0.87



**2.[Tests_2 / s (Integration tests (aarch64), func-tester-aarch64) / Integration tests (aarch64)-5]**


test_ssl_cert_authentication/test.py::test_native_wrong_cert | FAIL
-- | --




**3.ClickHouse Bugfix Validation for PR #67654**


Test name | Test status
-- | --
[with NOT_OK] Nothing to run | FAIL



Failures in the Stateless and Integration jobs cannot be related to the PR. 

The 3rd failure is interesting. It kind of states that the new testcase succeeded on the main branch without the fix. Let me check how does the test suite work.

**Comment by shiyer7474** [comment]
The error in `Bugfix validation `is test suite is :

```
Unpacking clickhouse-odbc-bridge (24.7.2.13) ...
dpkg-deb (subprocess): cannot copy archive member from 'package_folder/clickhouse-odbc-bridge_24.7.2.13_amd64.deb' to decompressor pipe: unexpected end of file or stream
dpkg-deb (subprocess): decompressing archive 'package_folder/clickhouse-odbc-bridge_24.7.2.13_amd64.deb' (size=262144000) member 'data.tar': internal gzip read error: buffer error
dpkg-deb: error: <decompress> subprocess returned error exit status 2
dpkg: error processing archive package_folder/clickhouse-odbc-bridge_24.7.2.13_amd64.deb (--install):
 cannot copy extracted data for './usr/bin/clickhouse-odbc-bridge' to '/usr/bin/clickhouse-odbc-bridge.dpkg-new': unexpected end of file or stream
Errors were encountered while processing:
 package_folder/clickhouse-odbc-bridge_24.7.2.13_amd64.deb
```
https://s3.amazonaws.com/clickhouse-test-reports/67654/8cb2e308f41638ebb6ba7fddbd4f0bf89d4d612e/bugfix_validation/run__stateless_tests__release_.log

@kssenii Please check last 2 updates regarding test failure details and let me know what you recommend next. Thanks!

**Comment by vdimir** [comment]
> The 2nd failure in Upgrade check regarding "Changed settings" is not related to this PR, let me check if there is some history

This one is unrelated and fixed in https://github.com/ClickHouse/ClickHouse/pull/67524

**Comment by kssenii** [comment]
> Stateless tests (ubsan) [2/2]

https://github.com/ClickHouse/ClickHouse/issues/67799

**Pull request merged**
