### PR TITLE
Correct Criteo example dataset instruction section

### PR DESCRIPTION
**Pull request by peter279k**
### Changelog category (leave one):

- Documentation (changelog entry is not required)

According to the shell script in this section, it's about the `Insert the data` section, not `Download the data`:

```shell
$ for i in {00..23}; do echo $i; zcat datasets/criteo/day_${i#0}.gz | sed -r 's/^/2000-01-'${i/00/24}'\t/' | clickhouse-client --host=example-perftest01j --query="INSERT INTO criteo_log FORMAT TabSeparated"; done
```

### CODE REVIEW

**Comment by robot-clickhouse-ci-2** [comment]
*This is an automated comment for commit 978fb783517639f495fbfbc67fe721cb8c8b2f5d with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/61415/978fb783517639f495fbfbc67fe721cb8c8b2f5d/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

**Comment by alexey-milovidov** [comment]
@peter279k there is something with the Docs check. It can be after your changes (then should be fixed) or due to an unfortunate moment when it was already broken (then merge with master).

**Comment by peter279k** [comment]
@alexey-milovidov, thanks for your explanation. What should I do for this docs checking? Or just wait for PR to be merged automatically?

**Comment by alexey-milovidov** [comment]
It cannot be merged, not automatically, not even manually, because it didn't pass the tests.

**Comment by alexey-milovidov** [comment]
Merge with master.

**Comment by peter279k** [comment]
@alexey-milovidov, thanks for your reply. What should I resolve this? Close the PR and create it again?

**Comment by alexey-milovidov** [comment]
Merge with master, for example using the following command:

```
git pull --no-rebase https://github.com/ClickHouse/ClickHouse.git master
```

**Review by alexey-milovidov — APPROVED** [review]

**Review by alexey-milovidov — APPROVED** [review]

**Pull request merged**
