### PR TITLE
Support default expression for storage hdfs and optimize fetching when source is column oriented

### PR DESCRIPTION
**Pull request by taiyang-li**
Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Support default expression for storage hdfs and optimize fetching when source is column oriented

Detailed description / Documentation draft:
Support default expression for storage hdfs and optimize fetching when source is column oriented

### CODE REVIEW

**Review by kssenii — APPROVED** [review]
Ok, I see the changes are copied from StorageFile so LGTM.

**Comment by taiyang-li** [comment]
> Ok, I see the changes are copied from StorageFile so LGTM.

Yes..

**Comment by kssenii** [comment]
@Mergifyio update

**Comment by kssenii** [comment]
> Integration tests (thread, actions) — fail: 9

Not related to changes, something with docker:
```
```

**Pull request merged**
