### PR TITLE
Make embedded documentation for Settings strictly better than the Markdown docs

### PR DESCRIPTION
**Pull request by alexey-milovidov**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Embedded documentation for settings will be strictly more detailed and complete than the documentation on the website. This is the first step before making the website documentation always auto-generated from the source code. This has long-standing implications: - it will be guaranteed to have every setting; - there is no chance of having default values obsolete; - we can generate this documentation for each ClickHouse version; - the documentation can be displayed by the server itself even without Internet access. Generate the docs on the website from the source code.

Note: this is done by the following SQL query:
```
WITH

'docs/en/operations/settings/settings-formats.md' AS doc_file,
'src/Core/FormatFactorySettingsDeclaration.h' AS cpp_file,

settings_from_docs AS
(
    WITH arrayJoin(extractAllGroups(raw_blob, '## (\w+)(?:\s[^\n]+)?\n\s+((?:[^#]|#[^#]|##[^ ])+)')) AS g,
        g[1] AS name, replaceRegexpAll(replaceRegexpAll(g[2], '\n(Type|Default( value)?): [^\n]+\n', ''), '^\n+|\n+$', '') AS doc
    SELECT name, doc
    FROM file(doc_file, RawBLOB)
),

settings_from_cpp AS
(
    WITH extractGroups(line, 'M\((\w+), (\w+), ([^,]+|\',\'), "(.+?)", (\w+)\)(.+)$') AS g,
        g[1] AS type, g[2] AS name, g[3] AS default, g[4] AS doc, g[5] AS important, g[6] AS suffix
    SELECT name, type, default, doc, important, suffix
    FROM file(cpp_file, LineAsString)
    WHERE match(line, '^\s*M\(')
),

best_doc AS
(
    SELECT name,
        length(md.doc) > length(cpp.doc)
            ? md.doc
            : cpp.doc -- : format('{}\n\nType: {}\n\nDefault value: {}', cpp.doc, cpp.type, cpp.default)
        AS doc,
        type, default, important, suffix
    FROM settings_from_cpp AS cpp LEFT JOIN settings_from_docs AS md USING name
),

reconstructed AS
(
    SELECT name, format('    M({}, {}, {}, R"(\n{}\n)", {}){}', type, name, default, doc, important, suffix) AS line
    FROM best_doc
),

replaced_cpp AS
(
    WITH extract(f.line, 'M\(\w+, (\w+),') AS f_name
    SELECT empty(reconstructed.line) ? f.line : reconstructed.line AS res
    FROM file(cpp_file, LineAsString) AS f LEFT JOIN reconstructed ON f_name = reconstructed.name
)

SELECT * FROM replaced_cpp
INTO OUTFILE 'new.cpp' TRUNCATE FORMAT LineAsString
```

Then, generation of Markdown files is done by this query:
```
WITH

'docs/en/operations/settings/settings.md' AS doc_file,
'src/Core/Settings.cpp' AS cpp_file,

settings_from_cpp AS
(
    SELECT extract(line, 'M\(\w+, (\w+),') AS name
    FROM file(cpp_file, LineAsString)
    WHERE match(line, '^\s*M\(')
),

main_content AS
(
    SELECT format('## {} {}\n\nType: {}\n\nDefault value: {}\n\n{}\n\n', name, '{#'||name||'}', type, default, trim(BOTH '\n' FROM description))
    FROM system.settings WHERE name IN settings_from_cpp
    ORDER BY name
),

(SELECT extract(raw_blob, '(^(?:[^#]|#[^#])+)##') FROM file(doc_file, RawBLOB)) AS prefix

SELECT prefix || (SELECT groupConcat(*) FROM main_content)
INTO OUTFILE 'new.md' TRUNCATE FORMAT LineAsString
```

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Run only fuzzers related jobs (libFuzzer fuzzers, AST fuzzers, etc.)
- [ ]  Exclude: AST fuzzers
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-clickhouse** [comment]
*This is an automated comment for commit 4790e989b0120eed7df0c2032f13647196b89fbc with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/70289/4790e989b0120eed7df0c2032f13647196b89fbc/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/816a5a5b2186163dcd641c3b61152454698a7774/docs_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Comment by alexey-milovidov** [comment]
Needs #70320

**Comment by nikitamikhaylov** [comment]
What's your workflow? Do you generate a markdown page and literally compare it to https://clickhouse.com/docs/en/operations/settings/settings ? And then put the documentation back to the code until the diff is 0 lines?

**Comment by alexey-milovidov** [comment]
@nikitamikhaylov, First, I've generated the new C++ code with the first SQL query, which combines the documentation from Markdown and the original C++ file, then I generated the new Markdown documentation by the second SQL query, which generates it from the C++ code from the first step.

**Comment by alexey-milovidov** [comment]
The first step (importing better docs from the .md to .h/.cpp) is required only once. After this PR will be merged, the Markdown docs will be always auto-generated, and maybe we will even delete the .md file from the repository.

**Comment by Avogar** [comment]
Screenshot 2024-10-07 at 12 19 46
Screenshot 2024-10-07 at 12 20 12
Can we improve it somehow?

**Comment by Avogar** [comment]
Also previously `settings-format.md` file contained settings in a structured way - it had sections for each data format with all settings related to this format. It was easier to read such docs rather then just a list of settings in sorted order. Can we improve it somehow? Maybe we can group settings in the source code in sections with settings related to the same data format and then use it somehow during the docs generation?

**Comment by alexey-milovidov** [comment]
> Can we improve it somehow?

Yes, let me try to apply escaping for the values.

> Also previously settings-format.md file contained settings in a structured way

I didn't notice it... Let me add automatic generation to the repository, and then we will add it there.

**Pull request merged**
