### PR TITLE
fix server settings nav

### PR DESCRIPTION
**Pull request by DanRoscigno**
Related to https://github.com/ClickHouse/clickhouse-docs/issues/1229

Note: This PR will not pass CI as it depends on https://github.com/ClickHouse/clickhouse-docs/pull/1265

### Changelog category (leave one):
- Documentation (changelog entry is not required)

### CODE REVIEW

**Comment by robot-ch-test-poll1** [comment]
This is an automated comment for commit da693c3c32005d8f8ac6c30dae8ff2952462d1fe with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/51246/da693c3c32005d8f8ac6c30dae8ff2952462d1fe/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Review by rfraposa — APPROVED** [review]
LGTM

**Comment by al13n321** [comment]
There are CI errors because `docs/en/operations/server-configuration-parameters/index.md` was deleted, but `docs/redirects.txt` still points to it: https://s3.amazonaws.com/clickhouse-test-reports/51171/4a570a05c9714c8ee94e68e4dda58efa759c8780/docs_check/run.log

Need to delete the redirect, or make both URLs redirect to `settings.md`?

**Comment by DanRoscigno** [comment]
> There are CI errors because `docs/en/operations/server-configuration-parameters/index.md` was deleted, but `docs/redirects.txt` still points to it: https://s3.amazonaws.com/clickhouse-test-reports/51171/4a570a05c9714c8ee94e68e4dda58efa759c8780/docs_check/run.log
> 
> Need to delete the redirect, or make both URLs redirect to `settings.md`?

The redirects are done in docusaurus-config.js on the docs repo, on my list for tomorrow is to remove the redirects.txt file over in this repo (I think that is a leftover from the old doc system).  It was failing CI because the redirects could not be added until the page was removed, so I had to merge this one first and then the change in the other repo.

**Pull request merged**
