### PR TITLE
[Don't merge] Do not ignore MEMORY_LIMIT_EXCEEDED for new

### PR DESCRIPTION
**Pull request by azat**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
TBD

This is attempt to see if this can fix OOM in stress tests.

Refs: #24483

### CODE REVIEW

**Comment by tavplubix** [comment]
It will drastically increase probability of throwing exceptions from unexpected places triggering obscure bugs. Our code is not ready for this. But we can use this PR to test exception-safety of our code, there are many interesting failures here.

**Comment by tavplubix** [comment]
For example: 
[f1cffd4](https://github.com/ClickHouse/ClickHouse/pull/40314/commits/f1cffd42efab653b42f7f90bcb2bd179f8f9623d) - 
Stateless tests (debug) [1/3]:
```
2022.08.18 12:00:28.125456 [ 18500 ] {} <Fatal> BaseDaemon: ########################################
2022.08.18 12:00:28.125971 [ 18500 ] {} <Fatal> BaseDaemon: (version 22.8.1.1, build id: EE060B7281CE2F3A) (from thread 7490) (query_id: 902b97b5-7beb-4110-a97a-ca7057202e5b) (query:  insert into data_01278 select number, reinterpretAsString(number), // s1
2022.08.18 12:00:28.126320 [ 18500 ] {} <Fatal> BaseDaemon: 
2022.08.18 12:00:28.126672 [ 18500 ] {} <Fatal> BaseDaemon: Stack trace: 0x7fb750a8d00b 0x7fb750a6c859 0x2cf966a3 0x2cf965b6 0x2ced98c4 0x2cec93f6 0x2cec90f5 0x2cec95f8 0x17201101 0x2c871041 0x2c66c7b7 0x2c665275 0x2c66f960 0x2c66f999 0x2c667ffe 0x2798864a 0x27987a3b 0x279877a1 0x279acf5d 0x26d327a0 0x26d31e2f 0x26d2b352 0x26d2a28b 0x266cbba9 0x26c98e6d 0x29085687 0x290855c6 0x29085535 0x29085404 0x29084443 0x290cd6c7 0x290d0fbc 0x290f7580 0x273e2e87 0x28f9b019 0x28f9ad85 0x28e887e4 0x28e88775 0x28e8873d 0x28e88715 0x28e886dd
2022.08.18 12:00:28.127031 [ 18500 ] {} <Fatal> BaseDaemon: 4. raise in ?
2022.08.18 12:00:28.127290 [ 18500 ] {} <Fatal> BaseDaemon: 5. abort in ?
2022.08.18 12:00:28.244473 [ 18500 ] {} <Fatal> BaseDaemon: 6. /build/build_docker/../contrib/jemalloc/src/safety_check.c:34: safety_check_fail in /usr/bin/clickhouse
2022.08.18 12:00:28.361561 [ 18500 ] {} <Fatal> BaseDaemon: 7. /build/build_docker/../contrib/jemalloc/src/safety_check.c:16: safety_check_fail_sized_dealloc in /usr/bin/clickhouse
2022.08.18 12:00:28.507614 [ 18500 ] {} <Fatal> BaseDaemon: 8. /build/build_docker/../contrib/jemalloc/src/jemalloc.c:2910: maybe_check_alloc_ctx in /usr/bin/clickhouse
2022.08.18 12:00:28.616636 [ 18500 ] {} <Fatal> BaseDaemon: 9. /build/build_docker/../contrib/jemalloc/src/jemalloc.c:2967: isfree in /usr/bin/clickhouse
2022.08.18 12:00:28.697847 [ 18500 ] {} <Fatal> BaseDaemon: 10. /build/build_docker/../contrib/jemalloc/src/jemalloc.c:3976: sdallocx_default in /usr/bin/clickhouse
2022.08.18 12:00:28.768791 [ 18500 ] {} <Fatal> BaseDaemon: 11. /build/build_docker/../contrib/jemalloc/src/jemalloc.c:3988: sdallocx in /usr/bin/clickhouse
2022.08.18 12:00:28.781034 [ 18500 ] {} <Fatal> BaseDaemon: 12. /build/build_docker/../src/Common/new_delete.cpp:138: operator delete(void*, unsigned long) in /usr/bin/clickhouse
2022.08.18 12:00:34.654660 [ 18500 ] {} <Fatal> BaseDaemon: 13. llvm::deallocate_buffer(void*, unsigned long, unsigned long) in /usr/bin/clickhouse
2022.08.18 12:00:40.475243 [ 18500 ] {} <Fatal> BaseDaemon: 14. llvm::DenseMap<llvm::Pass*, llvm::SmallPtrSet<llvm::Pass*, 8u>, llvm::DenseMapInfo<llvm::Pass*>, llvm::detail::DenseMapPair<llvm::Pass*, llvm::SmallPtrSet<llvm::Pass*, 8u> > >::~DenseMap() in /usr/bin/clickhouse
2022.08.18 12:00:46.304220 [ 18500 ] {} <Fatal> BaseDaemon: 15. llvm::PMTopLevelManager::~PMTopLevelManager() in /usr/bin/clickhouse
2022.08.18 12:00:48.625450 [ 624 ] {} <Fatal> Application: Child process was terminated by signal 6.
```

**Comment by alexey-milovidov** [comment]
+1, too risky.

**Comment by azat** [comment]
That wasn't for merge.

It was an attempt to debug OOM in stress tests, since those should never happens there (server should use only 0.75% of memory).

And so one of ideas was to ensure that there are no such allocations that bypass `Allocator`.

Although what I've figured out during debugging these lots of OOMs are not OOMs indeed, those are just because of clickhouse does not terminated with TERM within timeout, but those has small RSS usage in logs, while there are real ones, there have been some changes (fix for accounting in MemoryTracker and dmesg), so let's see if this will happen after.

Also it worth to improve stress script to report real OOMs only, for this few places can be analysed:
- dmesg (now)
- `clickhouse stop` kills real pid

**Comment by alexey-milovidov** [comment]
@azat Ok, we can reopen if more experiments are needed.

**Comment by azat** [comment]
>For example:
[f1cffd4](https://github.com/ClickHouse/ClickHouse/pull/40314/commits/f1cffd42efab653b42f7f90bcb2bd179f8f9623d) -

I looked through that failure, but there is enough information, I wish it has core dump.

**Pull request closed without merging**
