### PR TITLE
Supported cluster macros inside table function 'cluster'

### PR DESCRIPTION
**Pull request by PolyProgrammist**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- New Feature

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Supported cluster macros inside table functions 'cluster' and 'clusterAllReplicas'

Detailed description / Documentation draft:

You can do this query: 
```
create table test_db_o on cluster 'test_shard_localhost' (date DateTime, value UInt32) engine=MergeTree() order by date
```
And it's equivalent with macros (if there is a value 'cluster' -> 'test_shard_localhost' in system.macros):
```
create table test_db_a on cluster '{cluster}' (date DateTime, value UInt32) engine=MergeTree() order by date
```
Also you can call table functions `cluster` and `clusterAllReplicas`:
```
select * from cluster('test_shard_localhost', default.test_db_o)
```
However currently you cannot call it with `cluster` macros:
```
select * from cluster('{cluster}', default.test_db_4)`
```
The query gives an error:
```
Code: 170, e.displayText() = DB::Exception: Requested cluster '{cluster}' not found
```
The aim of this task is to allow to use `cluster` macros for table functions 'cluster' and 'clusterAllReplicas'

### CODE REVIEW

**Comment by ianton-ru** [comment]
LGTM

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
Also add it to skip list of fast test: docker/test/fasttest/run.sh or add config there.

**Comment by PolyProgrammist** [comment]
Thank you. 
> Also add it to skip list of fast test: docker/test/fasttest/run.sh or add config there.

@alexey-milovidov could you please merge this pull request once you are ok with it?

I consulted with @tavplubix about the failed test 01099_operators_date_and_timestamp and he says it may be flapping.

**Review by tavplubix — APPROVED** [review]

**Comment by sevirov** [comment]
Internal documentation ticket: DOCSUP-12413

**Pull request merged**
