### PR TITLE
Update HDFS (2)

### PR DESCRIPTION
**Pull request by alexey-milovidov**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Support for erasure codes in HDFS, author: @M1eyu2018, @tomscut.

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
@M1eyu2018, @tomscut, tests have failed.

**Comment by alexey-milovidov** [comment]
No success, closing.

**Comment by taiyang-li** [comment]
@alexey-milovidov @M1eyu2018 ,  we need to add a submodule of intel-isal before apply libhdfs ec to CH.

**Comment by M1eyu2018** [comment]
> @alexey-milovidov @M1eyu2018 , we need to add a submodule of intel-isal before apply libhdfs ec to CH.

@taiyang-li @alexey-milovidov 
Please check https://github.com/ClickHouse/ClickHouse/pull/48833.

**Pull request closed without merging**
