### PR TITLE
Fix flaky test `distributed_ddl_output_mode`

### PR DESCRIPTION
**Pull request by alexey-milovidov**
Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Also includes #26469.
@KochetovNicolai @tavplubix I did not find the reason why it was flaky.

### CODE REVIEW

**Review by KochetovNicolai — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
@KochetovNicolai @nikitamikhaylov @tavplubix My latest hypothesis is that remaining test flakiness is caused by parallel formatting.
Parallel formatting may lead to exception from port to be thrown out of order relative to data output. Does it sound realistic?

We don't have any other places where exceptions are pushed into output ports and where we require exception to be throw strictly after data output. Distributed DDL queries is the only place and I don't like it.

**Comment by KochetovNicolai** [comment]
> We don't have any other places where exceptions are pushed into output ports

Here
https://github.com/ClickHouse/ClickHouse/blob/remove-some-more-streams/src/Processors/ISimpleTransform.cpp#L92-L97

Try 
```
set query_plan_enable_optimizations = 0;
select * from (SELECT throwIf(number = 1000000) FROM system.numbers_mt) limit 1000000 settings max_block_size = 1000 format Null;
```
Sometimes it throws and swallows exception because of the parallel execution (query does not fail).

**Comment by alexey-milovidov** [comment]
> Functional stateless tests flaky check (address) — fail: 0, passed: 100 

It's fixed, but maybe it is a coincidence (in previous two runs it failed only 1 of 100 times).

**Comment by alexey-milovidov** [comment]
> Sometimes it throws and swallows exception because of the parallel execution (query does not fail).

This is Ok :) Exception is thrown only if function `throwIf` was calculated.

**Comment by alexey-milovidov** [comment]
But in ON CLUSTER query it depends on *parallel formatting*.

**Pull request merged**
