### PR TITLE
[WIP] ISSUES-590 fix Distributed push down stage

### PR DESCRIPTION
**Pull request by zhang2014**
#590 
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

### CODE REVIEW

**Comment by zhang2014** [comment]
Just fix the part of @MikhailKalashnikov in #590

**Comment by alexey-milovidov** [comment]
Sorry, but the fix is wrong.

When a query is issued to a Distributed table with multiple shards,
it will be processed in Distributed table up to WithMergeableState. No other option.

**Comment by alexey-milovidov** [comment]
Proper solution is to substitute aliases when rewriting query before sending to remote servers.

**Comment by alexey-milovidov** [comment]
Fixed in a different way.

**Pull request closed without merging**
