### PR TITLE
Minor changes in MergeTask

### PR DESCRIPTION
**Pull request by vdimir**
### Changelog category (leave one):

- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
...

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-ch-test-poll4** [comment]
*This is an automated comment for commit 624d7f0b7b0974cdd2ad412162956cc8fc966d9a with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/66605/624d7f0b7b0974cdd2ad412162956cc8fc966d9a/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/66586/e8627601b52e28a4d4203cd365cd5e4693e2af57/docs_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Review by nikitamikhaylov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
@vdimir It requires https://github.com/ClickHouse/ClickHouse/pull/66509

**Comment by vdimir** [comment]
> Stateless tests (aarch64) — fail: 1, passed: 6759, skipped: 17 [Details](https://s3.amazonaws.com/clickhouse-test-reports/66605/4f59ee11f783f62f5b47c7f94ddb5b979d137da8/stateless_tests__aarch64_.html)

> Stateless tests (debug, s3 storage) [2/2] — fail: 1, passed: 3313, skipped: 80 [Details](https://s3.amazonaws.com/clickhouse-test-reports/66605/4f59ee11f783f62f5b47c7f94ddb5b979d137da8/stateless_tests__debug__s3_storage__[2_2].html)


https://github.com/ClickHouse/ClickHouse/issues/67460 https://github.com/ClickHouse/ClickHouse/issues/65583

**Comment by vdimir** [comment]
> Upgrade check (debug) — Changed settings are not reflected in settings changes history (see changed_settings.txt) [Details](https://s3.amazonaws.com/clickhouse-test-reports/66605/e88acd675e10f9acf2e67bc05d84a712770989e3/upgrade_check__debug_.html)

Upgrade check was broken, now should be fixed

**Comment by vdimir** [comment]
> Stateless tests (release, old analyzer, s3, DatabaseReplicated) [1/4] — fail: 1, passed: 1717, skipped: 34 [Details](https://s3.amazonaws.com/clickhouse-test-reports/66605/fd62b3dbcd4a288f9b0bb8ed6c3ca24a3d772783/stateless_tests__release__old_analyzer__s3__databasereplicated__[1_4].html)

Fixing test in https://github.com/ClickHouse/ClickHouse/pull/68329

**Comment by vdimir** [comment]
> Stateless tests (tsan) [4/4] — Server died, fail: 3, passed: 311, skipped: 5 (but script exited with an error) [Details](https://s3.amazonaws.com/clickhouse-test-reports/66605/40b55ac6439f06b6361cd243f55d758ce96b8048/stateless_tests__tsan__[4_4].html)

https://github.com/ClickHouse/ClickHouse/pull/67737#issuecomment-2269302131

> Stateless tests (debug, s3 storage) [2/2] — fail: 1, passed: 3367, skipped: 87 [Details](https://s3.amazonaws.com/clickhouse-test-reports/66605/40b55ac6439f06b6361cd243f55d758ce96b8048/stateless_tests__debug__s3_storage__[2_2].html)

❓ 
<details>
<summary>Details</summary>

```
2024-08-14 18:16:43 Has fatal logs from client:
2024-08-14 18:16:43 
2024-08-14 18:16:43 ########## Short fault info ############
2024-08-14 18:16:43 (version 24.9.1.52, build id: , git hash: ) (from thread 110131) Received signal 20
2024-08-14 18:16:43 Signal description: Stopped
2024-08-14 18:16:43 This is a signal used for debugging purposes by the user.
2024-08-14 18:16:43 Stack trace: 0x000000000c625508 0x000000000c865ede 0x00007fe122ffc520 0x00007fe1230d2bd0 0x00000000163e6b1f 0x00000000163e6ce8 0x000000000c71f9ec 0x0000000012aac8d0 0x0000000012aabbdd 0x0000000012aaa53f 0x0000000012ab3063 0x0000000012ab3d46 0x0000000012ab671e 0x000000000c7ca285 0x000000001640cde6 0x000000000c7d5c52 0x0000000006fcfc6b 0x00007fe122fe3d90 0x00007fe122fe3e40 0x0000000006fcf02e
2024-08-14 18:16:43 ########################################
2024-08-14 18:16:43 (version 24.9.1.52, build id: , git hash: ) (from thread 110131) (no query) Received signal Stopped (20)
2024-08-14 18:16:43 This is a signal used for debugging purposes by the user.
2024-08-14 18:16:43 Stack trace: 0x000000000c625508 0x000000000c865ede 0x00007fe122ffc520 0x00007fe1230d2bd0 0x00000000163e6b1f 0x00000000163e6ce8 0x000000000c71f9ec 0x0000000012aac8d0 0x0000000012aabbdd 0x0000000012aaa53f 0x0000000012ab3063 0x0000000012ab3d46 0x0000000012ab671e 0x000000000c7ca285 0x000000001640cde6 0x000000000c7d5c52 0x0000000006fcfc6b 0x00007fe122fe3d90 0x00007fe122fe3e40 0x0000000006fcf02e
2024-08-14 18:16:43 0.0. inlined from /build/src/Common/StackTrace.cpp:349: StackTrace::tryCapture()
2024-08-14 18:16:43 0. /build/src/Common/StackTrace.cpp:318: StackTrace::StackTrace(ucontext_t const&) @ 0x000000000c625508
2024-08-14 18:16:43 1. /build/src/Common/SignalHandlers.cpp:0: signalHandler(int, siginfo_t*, void*) @ 0x000000000c865ede
2024-08-14 18:16:43 2. ? @ 0x00007fe122ffc520
2024-08-14 18:16:43 3. ? @ 0x00007fe1230d2bd0
2024-08-14 18:16:43 4. /build/base/poco/Net/src/SocketImpl.cpp:0: Poco::Net::SocketImpl::pollImpl(Poco::Timespan&, int) @ 0x00000000163e6b1f
2024-08-14 18:16:43 5. /build/base/poco/Net/src/SocketImpl.cpp:506: Poco::Net::SocketImpl::poll(Poco::Timespan const&, int) @ 0x00000000163e6ce8
2024-08-14 18:16:43 6.0. inlined from /build/base/poco/Net/include/Poco/Net/Socket.h:374: Poco::Net::Socket::poll(Poco::Timespan const&, int) const
2024-08-14 18:16:43 6. /build/src/IO/ReadBufferFromPocoSocket.cpp:134: DB::ReadBufferFromPocoSocket::poll(unsigned long) const @ 0x000000000c71f9ec
2024-08-14 18:16:43 7. /build/src/Client/ClientBase.cpp:1124: DB::ClientBase::receiveResult(std::shared_ptr<DB::IAST>, int, bool) @ 0x0000000012aac8d0
2024-08-14 18:16:43 8. /build/src/Client/ClientBase.cpp:1048: DB::ClientBase::processOrdinaryQuery(String const&, std::shared_ptr<DB::IAST>) @ 0x0000000012aabbdd
2024-08-14 18:16:43 9. /build/src/Client/ClientBase.cpp:1944: DB::ClientBase::processParsedSingleQuery(String const&, String const&, std::shared_ptr<DB::IAST>, std::optional<bool>, bool) @ 0x0000000012aaa53f
2024-08-14 18:16:43 10. /build/src/Client/ClientBase.cpp:2262: DB::ClientBase::executeMultiQuery(String const&) @ 0x0000000012ab3063
2024-08-14 18:16:43 11. /build/src/Client/ClientBase.cpp:0: DB::ClientBase::processQueryText(String const&) @ 0x0000000012ab3d46
2024-08-14 18:16:43 12.0. inlined from /build/contrib/llvm-project/libcxx/include/string:1499: String::__is_long[abi:v15007]() const
2024-08-14 18:16:43 12.1. inlined from /build/contrib/llvm-project/libcxx/include/string:2333: ~basic_string
2024-08-14 18:16:43 12. /build/src/Client/ClientBase.cpp:2733: DB::ClientBase::runNonInteractive() @ 0x0000000012ab671e
2024-08-14 18:16:43 13.0. inlined from /build/contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:290: std::unique_ptr<DB::Exception, std::default_delete<DB::Exception>>::operator bool[abi:v15007]() const
2024-08-14 18:16:43 13. /build/programs/client/Client.cpp:397: DB::Client::main(std::vector<String, std::allocator<String>> const&) @ 0x000000000c7ca285
2024-08-14 18:16:43 14. /build/base/poco/Util/src/Application.cpp:0: Poco::Util::Application::run() @ 0x000000001640cde6
2024-08-14 18:16:43 15. /build/programs/client/Client.cpp:0: mainEntryClickHouseClient(int, char**) @ 0x000000000c7d5c52
2024-08-14 18:16:43 16.0. inlined from /build/contrib/llvm-project/libcxx/include/vector:438: std::vector<char*, std::allocator<char*>>::__destroy_vector::operator()[abi:v15007]()
2024-08-14 18:16:43 16.1. inlined from /build/contrib/llvm-project/libcxx/include/vector:449: ~vector
2024-08-14 18:16:43 16. /build/programs/main.cpp:255: main @ 0x0000000006fcfc6b
2024-08-14 18:16:43 17. ? @ 0x00007fe122fe3d90
2024-08-14 18:16:43 18. ? @ 0x00007fe122fe3e40
2024-08-14 18:16:43 19. _start @ 0x0000000006fcf02e
2024-08-14 18:16:43 This ClickHouse version is not official and should be upgraded to the official build.
2024-08-14 18:16:43 
2024-08-14 18:16:43 All tests have finished.
```

</details>

**Comment by vdimir** [comment]
Conflicted and build is broken, probably need to re-create patch from current diff

**Pull request closed without merging**
