### PR TITLE
Fix flaky `test_multiple_disks`

### LINKED ISSUE #45404: Flaky test_multiple_disks
Also failed `test_multiple_disks/test.py::test_background_move[mt]`

```
>           assert used_disks[0] == "external"
E           AssertionError: assert 'jbod1' == 'external'
E             - external
E             + jbod1
```
https://s3.amazonaws.com/clickhouse-test-reports/0/cfba9b19eb0941f4e40d216d55ef2a68f6d2cf5e/integration_tests__release__[2/2]/integration_run_parallel5_0.log

_Originally posted by @qoega in https://github.com/ClickHouse/ClickHouse/issues/45180#issuecomment-1387299684_

### PR DESCRIPTION
**Pull request by antonio2368**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

The test creates 5 parts and we check that the first part is moved to the external disk. The problem is after `START MOVE` only subset of parts can be moved, increasing the modification time of the first part. The oldest part becomes a later insert because it was not moved so modification time is lower. Multiple moves are also done in parallel so later insert can also be moved before the first inserted part.
All in all, we need to check explicitly until the first part is moved to the `external`

Fix https://github.com/ClickHouse/ClickHouse/issues/45404

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by robot-ch-test-poll2** [comment]
This is an automated comment for commit 18b2f6164c0cbaa73b1475dbf61cb2bb47e928da with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/51821/18b2f6164c0cbaa73b1475dbf61cb2bb47e928da/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Review by alesapin — APPROVED** [review]

**Comment by antonio2368** [comment]
I suspect `test_background_move` has the same problem, will change it also

**Review by alexey-milovidov — APPROVED** [review]

**Comment by CheSema** [comment]
Hi. It happens that I also is looking at this.
According to your explanation, some moves are take place after that is done
https://github.com/ClickHouse/ClickHouse/blob/095b75e2c70489f0116e3df6cc3b4cd1fe640470/tests/integration/test_multiple_disks/test.py#L846

However Im reading the logs. 
That for example https://s3.amazonaws.com/clickhouse-test-reports/51696/7b6b406af1dfa3f658b80c1f977375d053ae559f/integration_tests__asan__[4_6].html 
I do not see any moves for all the time after `START MOVES`. 
There should be a message `Got {} parts to move.`

My theory is that somehow `background_moves_assignee.postpone()` has been called too much times. I'm checking it right now. If you are sure that you fixed it totally, I will stop digging.

**Comment by antonio2368** [comment]
@CheSema funny you mentioned this because I was looking at the exact issue now.
Noticed that a different assert failed in these 2 runs:
https://s3.amazonaws.com/clickhouse-test-reports/0/2575db15221dbe3ebbf3c109ea67c1255dfb7b1b/integration_tests__tsan__[4_6].html
https://s3.amazonaws.com/clickhouse-test-reports/0/41783c47d1fead9e8094dc460038e6571de1e83a/integration_tests__asan__[4_6].html

and they are the same as the ones you mentioned.

I quickly checked the logs and the only thing I noticed for now that moves are completely blocked for some reason like you said.

As you already started looking at it, can you continue on this branch so we completely fix the test with this PR. My PR solves only one of the issues and I hope you will fix the second part.

**Comment by CheSema** [comment]
mine 5 cents here would be
```
max_replicated_merges_in_queue=0
```
explanation
https://github.com/ClickHouse/ClickHouse/issues/45404#issuecomment-1622371017

**Pull request merged**
