### PR TITLE
Allow to use String type instead of Binary in Arrow/Parquet/ORC formats

### LINKED ISSUE #37254: Allow Configuring ClickHouse to Use Arrow String Type for String Columns
I have several text columns in my datasets and would like them to use a string data type instead of binary when using either `ArrowStream` or `Arrow` output formats. Currently, I have to cast them to `string`, which somewhat defeats the purpose of using Arrow.

> A clear and concise description of what is the intended usage scenario is.

I propose adding a flag `output_format_arrow_string_as_string` similar to `output_format_arrow_low_cardinality_as_dictionary`.

> A clear and concise description of what you want to happen.

String columns in the result would use Arrow's `string` type if and only if `output_format_arrow_string_as_string=1`.

> A clear and concise description of any alternative solutions or features you've considered.

A setting that allows multiple output types: `output_format_arrow_string_type=large_string`, `output_format_arrow_string_type=string`, etc. It would default to `binary` for backwards compatibility.

### PR DESCRIPTION
**Pull request by Avogar**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Allow to use String type instead of Binary in Arrow/Parquet/ORC formats. This PR introduces 3 new settings for it: `output_format_arrow_string_as_string`, `output_format_parquet_string_as_string`, `output_format_orc_string_as_string`. Default value for all settings is `false`.

Closes https://github.com/ClickHouse/ClickHouse/issues/37254

### CODE REVIEW

**Comment by Avogar** [comment]
I noticed that we don't have a lot of settings for Arrow/Parquet/ORC formats in docs, I will add them here later

**Review by vdimir — APPROVED** [review]
lgtm

**Comment by vdimir** [comment]
> Fast test (actions) — fail: 1

`Cannot determine the file format by it's extension. (BAD_ARGUMENTS)`
Does `.parquet` listed in extension to format mapping?

**Comment by Avogar** [comment]
@Mergifyio update

**Comment by Avogar** [comment]
@Mergifyio update

**Comment by Avogar** [comment]
`AST fuzzer (UBSan, actions)` - https://github.com/ClickHouse/ClickHouse/issues/37385

**Comment by ilejn** [comment]
It's a bit strange that for Avro we can do it in a more fine-grained manner https://github.com/ClickHouse/ClickHouse/pull/26245

**Comment by ilejn** [comment]
> While doing it I didn't actually know about similar setting for Avro, I will think about making the same behaviour for Arrow/ORC/Parquet before it's included in any release

@Avogar , actually my initial intent was to have a single switch for Avro as well ;)
Some discussion https://github.com/ClickHouse/ClickHouse/issues/22414

**Pull request merged**
