### PR TITLE
Respect PK for aggregate projection.

### LINKED ISSUE #49150: Projection makes things worse when aggregation matches but filter condition can't be applied to primary key
```
CREATE TABLE t0
(
    `c1` Int64,
    `c2` Int64,
    `c3` Int64,
    `c4` Int64,
    PROJECTION p1
    (
        SELECT
            c1,
            c2,
            sum(c4)
        GROUP BY
            c2,
            c1
    )
)
ENGINE = MergeTree
ORDER BY (c1, c2);

INSERT INTO t0 SELECT
    number,
    rand(1),
    rand(2),
    rand(3)
FROM numbers_mt(10000000);
```

```
SELECT
    c1,
    sum(c4)
FROM t0
WHERE c1 = 100
GROUP BY c1
SETTINGS allow_experimental_projection_optimization = 0

Query id: b7e8c17b-069a-4213-a455-2e452e7e699a

┌──c1─┬────sum(c4)─┐
│ 100 │ 3027309634 │
└─────┴────────────┘

1 row in set. Elapsed: 0.004 sec. Processed 8.19 thousand rows, 66.34 KB (2.28 million rows/s., 18.47 MB/s.)

ip-172-31-38-198.us-east-2.compute.internal :) SELECT c1, sum(c4) FROM t0 WHERE c1=100 GROUP BY c1 SETTINGS allow_experimental_projection_optimization=1

SELECT
    c1,
    sum(c4)
FROM t0
WHERE c1 = 100
GROUP BY c1
SETTINGS allow_experimental_projection_optimization = 1

Query id: f0a793c5-5fed-4b6c-91ef-9b7e336948e1

┌──c1─┬────sum(c4)─┐
│ 100 │ 3027309634 │
└─────┴────────────┘

1 row in set. Elapsed: 0.040 sec. Processed 10.00 million rows, 302.36 MB (251.43 million rows/s., 7.60 GB/s.)
```

```
EXPLAIN
SELECT
    c1,
    sum(c4)
FROM t0
WHERE c1 = 100
GROUP BY c1

Query id: 3e90cd34-79b8-4a29-a893-49d85811e0ab

┌─explain─────────────────────────────────────┐
│ Expression ((Projection + Before ORDER BY)) │
│   Aggregating                               │
│     Filter                                  │
│       ReadFromMergeTree (p1)                │
└─────────────────────────────────────────────┘

4 rows in set. Elapsed: 0.004 sec.
```
p1 is used and we read all the data from projection instead of couple of granules and aggregate them.

### PR DESCRIPTION
**Pull request by KochetovNicolai**
### Changelog category (leave one):
- Performance Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Use aggregate projection only if it reads fewer granules than normal reading. It should help in case if query hits the PK of the table, but not the projection. Fixes #49150

This will fix only 23.3+

### CODE REVIEW

**Comment by robot-clickhouse-ci-1** [comment]
This is an automated comment for commit 75597efeb690da09457292249d8653cf07cea402 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/49417/75597efeb690da09457292249d8653cf07cea402/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Review by alexey-milovidov — APPROVED** [review]

**Comment by UnamedRus** [comment]
> Use aggregate projection only if it reads fewer granules than normal reading.

TBH, it would be better, if it will be based not on amount of granules, but on size.

IE, for example you have uniq function in projection, and you want to read only one row from agg projection, but you will read 8192 rows instead (actually more, because of compression block size).

**Comment by tavplubix** [comment]
@KochetovNicolai, looks like it breaks `01710_projection_aggregation_in_order`: [link](https://play.clickhouse.com/play?user=play#d2l0aCAKJyUwMTcxMF9wcm9qZWN0aW9uX2FnZ3JlZ2F0aW9uX2luX29yZGVyJScgYXMgbmFtZV9wYXR0ZXJuLAonJSUnIGFzIGNvbnRleHRfcGF0dGVybiwKJzIwMjItMTItMDEnIGFzIHN0YXJ0X2RhdGUsCig0NTQ2MSwgNDUyMzYsIDQ0OTg1LCA0NzQ3NSkgYXMgbm9pc3lfcHJzLAooJ1N0YXRlbGVzcyB0ZXN0cyAoYXNhbiknLCAnU3RhdGVsZXNzIHRlc3RzIChhZGRyZXNzKScsICdTdGF0ZWxlc3MgdGVzdHMgKGFkZHJlc3MsIGFjdGlvbnMpJykgYXMgYmFja3BvcnRfYW5kX3JlbGVhc2Vfc3BlY2lmaWNfY2hlY2tzCnNlbGVjdCAKdG9TdGFydE9mRGF5KGNoZWNrX3N0YXJ0X3RpbWUpIGFzIGQsCmNvdW50KCksICBncm91cFVuaXFBcnJheShwdWxsX3JlcXVlc3RfbnVtYmVyKSwgYW55KHJlcG9ydF91cmwpCmZyb20gY2hlY2tzIHdoZXJlIHN0YXJ0X2RhdGUgPD0gY2hlY2tfc3RhcnRfdGltZSBhbmQgcHVsbF9yZXF1ZXN0X251bWJlciBub3QgaW4gCihzZWxlY3QgcHVsbF9yZXF1ZXN0X251bWJlciBhcyBwcm4gZnJvbSBjaGVja3Mgd2hlcmUgcHJuIT0wIGFuZCBzdGFydF9kYXRlIDw9IGNoZWNrX3N0YXJ0X3RpbWUgYW5kIGNoZWNrX25hbWUgaW4gYmFja3BvcnRfYW5kX3JlbGVhc2Vfc3BlY2lmaWNfY2hlY2tzKSAKYW5kIHRlc3RfbmFtZSBpbGlrZSBuYW1lX3BhdHRlcm4gYW5kICh0ZXN0X2NvbnRleHRfcmF3IGlsaWtlIGNvbnRleHRfcGF0dGVybikKYW5kIHB1bGxfcmVxdWVzdF9udW1iZXIgbm90IGluIG5vaXN5X3BycyAKYW5kIHRlc3Rfc3RhdHVzIGluICgnRkFJTCcsICdGTEFLWScsICdmYWlsdXJlJykgZ3JvdXAgYnkgZCBvcmRlciBieSBkIGRlc2M=)

**Comment by tavplubix** [comment]
[0e5c3ea](https://github.com/ClickHouse/ClickHouse/pull/49417/commits/0e5c3ea9acf54b559726e4de0c269919f8dd1830) - Stateless tests (debug) [2/5] - `02516_projections_with_rollup` - this failure looks suspicious too, but it was ignored

**Pull request merged**
