### PR TITLE
Fixed build of `openssl` with `make`

### PR DESCRIPTION
**Pull request by excitoon**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Non-significant (changelog entry is not needed)

### CODE REVIEW

**Review by alexey-milovidov — CHANGES_REQUESTED** [review]
Don't understand the mechanics of this fix.

**Comment by excitoon** [comment]
Perl code generation scripts require destination directory to exist,
otherwise they output files to `STDOUT`. CMake automatically creates binary
directories only if corresponding source directory was added with
`add_subdirectory`. Everything works fine on other OSes probably because
`crypto` from system is being used (and on Arch Linux there are no static
libraries by design).

**Comment by alexey-milovidov** [comment]
> CMake automatically creates binary
directories only if corresponding source directory was added with
`add_subdirectory`.

If "crypto" is disabled, why we are going to this directory and interpreting this CMakeLists file?

> Everything works fine on other OSes probably because
`crypto` from system is being used (and on Arch Linux there are no static
libraries by design).

We don't use libraries from OS by default. It is strongly discouraged and can only be enabled by setting `UNBUNDLED` option manually.

**Comment by excitoon** [comment]
Okay, this is Ninja issue, because it creates output directories by itself:

> Output directories are always implicitly created before running the command that relies on them. 

And `make` does not.

> If "crypto" is disabled, why we are going to this directory and interpreting this CMakeLists file?

I meant that internal subdirectories for `.s` files are not being created automatically, only main `openssl`.

**Pull request merged**
