### PR TITLE
Masking sensitive info in gcs() table function

### PR DESCRIPTION
**Pull request by vitlibar**
### Changelog category:
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Masking sensitive info in `gcs()` table function

### CODE REVIEW

**Comment by robot-ch-test-poll4** [comment]
*This is an automated comment for commit a461d20af92278fb973ba7a86ec84fb58946ce74 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/69611/a461d20af92278fb973ba7a86ec84fb58946ce74/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/2fce90ab76b851198b39041c9e7c4b03ad601ff7/docs_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Review by evillique — APPROVED** [review]

**Comment by vitlibar** [comment]
CI failures are unrelated:
- [Logical error: 'RangeReader read 1 rows, but 8192 expected.'](https://s3.amazonaws.com/clickhouse-test-reports/69611/a461d20af92278fb973ba7a86ec84fb58946ce74/ast_fuzzer__msan_.html) - see https://github.com/ClickHouse/ClickHouse/issues/56640#issuecomment-2352236826

**Comment by novikd** [comment]
@vitlibar It doesn't seem to mask credentials in the new analyzer.

**Comment by vitlibar** [comment]
> @vitlibar It doesn't seem to mask credentials in the new analyzer.

This PR is to mask secret in logs. And it works correctly with both old analyzer and new analyzer.

What seems to be not working is hiding secrets in the output of `EXPLAIN QUERY TREE`:

```
EXPLAIN QUERY TREE SELECT * FROM s3('http://127.0.0.1:9836/mybucket/1.csv', 'key', 'secret', 'CSV', 'a Int64, b Int64')
```

That will be probably solved after as a part of more general issue https://github.com/ClickHouse/ClickHouse/issues/69571

**Comment by clickgapai** [comment]
Hi @vitlibar @evillique — while reviewing this PR I found the following:

- **Bug (P1):** GCS table ENGINE secrets not masked in SHOW CREATE and system.tables — https://github.com/ClickHouse/ClickHouse/issues/105013

Happy to discuss — close anything that's wrong or already addressed.

**Pull request merged**
