### PR TITLE
copy self-extracting to output

### LINKED ISSUE #34755: Make `clickhouse` binary a self extracting executable.
**Use case**

1. More quick downloads but without the need of unpacking or installing any separate tools.
2. Include `odbc-bridge` and `library-bridge` in single-binary ClickHouse downloads despite the fact that they are separate binaries.
3. Maybe the size will be ok to always include debug info, even in .deb/.rpm packages.
4. It will also speed up cold start in the cloud.
5. #29378

**Describe the solution you'd like**

Compile a tool that can compress and decompress with ZSTD. It can use the official zstd framing format but not necessarily. It should support compression by blocks of size around 10..100 MiB (to avoid too high memory usage) and checksums. It should not depend on glibc version, and even better if it will be statically linked. Maybe two tools - one for compression and another for decompression.

Post-build rule will compress `clickhouse` (and possibly `clickhouse-odbc-bridge` and `clickhouse-jdbc-bridge`) binary into blob and then include it into the decompressor with `llvm-objcopy` as a custom ELF section (alternatively - maybe we can concatenate it after the decompressor binary).

Decompressor should check the free space in the current directory, decompress the content into temporary file with a similar name (like `clickhouse.tmp`), perform `fsync`, rename the current binary to a file with similar name (like `.compressed`), rename the decompressed binary to the original name, delete the compressed binary and run the decompressed binary with the same arguments.

If `clickhouse-odbc-bridge` and `clickhouse-odbc-bridge` binaries are present, they should be extracted into current directory and `clickhouse install` script should check if they are present.

**Describe alternatives you've considered**

There are existing specialized tools for compressing executables (like UPX). But zstd will do it better.

**Additional context**

A shortcut for `clickhouse install` in the decompressor can be implemented to avoid extra file copies (first into current directory then to the install destination like `/usr/bin`).

It makes sense to parallelize decompression.

### PR DESCRIPTION
**Pull request by yakov-olkhovskiy**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Deploy compressed self-extracting clickhouse to s3

Closes #34755

### CODE REVIEW

**Review by rschu1ze — APPROVED** [review]

**Review by Felixoid — APPROVED** [review]
Looks 👍

**Comment by alexey-milovidov** [comment]
```
milovidov@milovidov-desktop:~$ chmod +x clickhouse
milovidov@milovidov-desktop:~$ time ./clickhouse
sh: 1: Syntax error: end of file unexpected (expecting ")")

real    0m1,655s
user    0m2,027s
sys     0m8,165s
```

**Review by alexey-milovidov — CHANGES_REQUESTED** [review]
Almost...

**Comment by alexey-milovidov** [comment]
Does not work:

```
$ ./clickhouse local --query "SELECT 1"
Code: 36. DB::Exception: Positional options are not supported. (BAD_ARGUMENTS)
```

**Comment by alexey-milovidov** [comment]
https://github.com/ClickHouse/ClickHouse/pull/35775/files#r933707748

**Comment by yakov-olkhovskiy** [comment]
@alexey-milovidov strangely enough I was able to reproduce this `sh: 1: Syntax error: end of file unexpected (expecting ")")` exactly once, and since then everything is working just fine... kinda puzzling... Is it reproducible for you?

**Comment by alexey-milovidov** [comment]
@yakov-olkhovskiy because the file is decompressed and replaced with the decompressed result.

**Comment by yakov-olkhovskiy** [comment]
@yakov-olkhovskiy of course I preserved compressed and was replaced it back every time :) there's some mystery...

**Comment by yakov-olkhovskiy** [comment]
@alexey-milovidov of course I preserved compressed and was replacing it back every time :) there's some mystery...

**Comment by yakov-olkhovskiy** [comment]
...one more issue - self-extracting shouldn't be built for split - will fix it with another PR

**Review by alexey-milovidov — APPROVED** [review]
Wow, it works!

**Comment by rschu1ze** [comment]
Also noticed a considerable slowdown when doing incremental builds locally. Related: https://github.com/ClickHouse/ClickHouse/pull/39988

**Comment by yakov-olkhovskiy** [comment]
yes, compressed clickhouse requires to run not from link initially to properly decompress - will fix it soon

**Comment by alexey-milovidov** [comment]
We can avoid compressing in dev environments, and only compress in CI.
Similarly how we are doing that with clickhouse-hash-binary.

**Pull request merged**
