### PR TITLE
Remove default cluster from default config from test config

### PR DESCRIPTION
**Pull request by Algunenano**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
- Remove default cluster from default config from test config

### Documentation entry for user-facing changes

It's being a PITA in private sync, since having a cluster defined as `default` without knowing the topology is bad. We should be using known clusters for testing to begin with, such as test_shard_localhost, so let's remove it.

### CODE REVIEW

**Comment by robot-clickhouse** [comment]
*This is an automated comment for commit 2f1f7c60d8afe90b7248572d103becf844f41004 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/61396/2f1f7c60d8afe90b7248572d103becf844f41004/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

**Review by nikitamikhaylov — APPROVED** [review]

**Comment by filimonov** [comment]
Maybe we can return back test clusters to default config? I'm missing them :)

Having 'some' cluster predefined allows to create distributed tables quickly. It's superhandy in docker tests, or in fiddle.

Maybe we can rename it back to test_shard_localhost, or call it dummy or whatever similar.

**Comment by filimonov** [comment]
Related https://github.com/ClickHouse/ClickHouse/pull/51985
Cc @azat

**Comment by alexey-milovidov** [comment]
This is needed to unify tools and observability between self-managed and ClickHouse Cloud.

**Comment by Algunenano** [comment]
We need to at least change the tests that use `default`. Ideally block any future tests too since they will require extra steps on PR review.

**Comment by alexey-milovidov** [comment]
@Algunenano, you can add a config override for tests that will remove the default cluster.

**Comment by Algunenano** [comment]
Changed it to only remove the cluster for testing but keep it in the default config

**Review by filimonov — APPROVED** [review]

**Review by alexey-milovidov — APPROVED** [review]

**Pull request merged**
