### PR TITLE
Fix mismatched aggreage function name of quantileExactWeightedInterpolated

### PR DESCRIPTION
**Pull request by taiyang-li**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix mismatched aggreage function name of quantileExactWeightedInterpolated. The bug was introduced in https://github.com/ClickHouse/ClickHouse/pull/69619.  cc @Algunenano  

Before
``` sql 
SELECT toTypeName(quantilesExactWeightedInterpolatedState(0.2, 0.4, 0.6, 0.8)(number + 1, 1) AS x)
FROM numbers(49999)

Query id: 24509428-537c-4da2-923c-6df9a7917bb8

   ┌─toTypeName(x)────────────────────────────────────────────────────────────────┐
1. │ AggregateFunction(quantilesExactWeighted(0.2, 0.4, 0.6, 0.8), UInt64, UInt8) │
   └──────────────────────────────────────────────────────────────────────────────┘
```

After
``` sql
SELECT toTypeName(quantilesExactWeightedInterpolatedState(0.2, 0.4, 0.6, 0.8)(number + 1, 1) AS x)
FROM numbers(49999)

Query id: e4f9160b-c91d-4ca3-af14-8e4a3d1e0c73

   ┌─toTypeName(x)────────────────────────────────────────────────────────────────────────────┐
1. │ AggregateFunction(quantilesExactWeightedInterpolated(0.2, 0.4, 0.6, 0.8), UInt64, UInt8) │
   └──────────────────────────────────────────────────────────────────────────────────────────┘ 
```

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Run only fuzzers related jobs (libFuzzer fuzzers, AST fuzzers, etc.)
- [ ]  Exclude: AST fuzzers
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-ch-test-poll1** [comment]
*This is an automated comment for commit 219cc4e5d241201d8bb4838cc440735ec5c905ea with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/71168/219cc4e5d241201d8bb4838cc440735ec5c905ea/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Style check</td><td>Runs a set of checks to keep the code style clean. If some of tests failed, see the related log from the report</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/71168/219cc4e5d241201d8bb4838cc440735ec5c905ea/style_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Review by novikd — COMMENTED** [review]
Could you please provide a test to reproduce the bug fix?

**Comment by taiyang-li** [comment]
> Could you please provide a test to reproduce the bug fix?

I'll try.

**Comment by taiyang-li** [comment]
@novikd I had already add the tests, could you review again? Thanks!

**Review by novikd — APPROVED** [review]

**Comment by novikd** [comment]
@taiyang-li, please merge the master into the branch or allow contributes to push to your PRs

**Pull request merged**
