### PR TITLE
Scheduler queue throughput introspection, Fix CPU indication in client

### PR DESCRIPTION
**Pull request by serxa**
Adds a new column `throughput`  in `system.scheduler` with the recent throughput of every scheduler node. Based on EventRateMeter, which is also used in CPU indicating of a query. Fixes a bug in it (more details are in commit message for the fix).

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
...

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-ch-test-poll** [comment]
*This is an automated comment for commit b0ac0327d4d38a918e9be8fc499038cc43cafb2c with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/65654/b0ac0327d4d38a918e9be8fc499038cc43cafb2c/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Cloud fork sync (only for ClickHouse Inc. employees)</td><td>If it fails, ask a maintainer for help</td><td>⏳ pending</td></tr>
<tbody>
</table>
<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>Checks correctness of the PR's body</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

**Review by nikitamikhaylov — APPROVED** [review]

**Comment by serxa** [comment]
> Performance Comparison (release) [4/4] — Errors while building the report.
Both left and right servers died multiple times with:
```
❯ rg -a '<Fatal>' left-*.log | rg -v 'BaseDaemon' | cut -f 8- -d ' ' | sort | uniq -c
 119 Application: Child process was terminated by signal 6.
   1 Application: Child process was terminated by signal 9 (KILL). If it is not done by 'forcestop' command or manually, the possible cause is OOM Killer (see 'dmesg' and look at the '/var/log/kern.log' for the details).
 119 KeeperStateMachine: Digest for nodes is not matching after preprocessing request of type 'Heartbeat' at log index 11.
❯ rg -a '<Fatal>' right-*.log | rg -v 'BaseDaemon' | cut -f 8- -d ' ' | sort | uniq -c
 119 Application: Child process was terminated by signal 6.
 119 KeeperStateMachine: Digest for nodes is not matching after preprocessing request of type 'Heartbeat' at log index 11.
```

The stack traces are all similar and have something to do with thread fuzzer:
```

Stack trace: 0x000000000d267f8c 0x00007f32799c5520 0x00007f3279a199fd 0x00007f32799c5476 0x00007f32799ab7f3 0x000000000d267a70 0x00000000179dba43 0x00000000179dba3b 0x000000001315921e 0x0000000013158de4 0x000000001315a8e4 0x000000001528b8be 0x000000001528af60 0x00000000130eeef9 0x0000000015285922 0x000000000d077c83 0x00007f3279a17ac3 0x00007f3279aa9850
0. ./build_docker/./src/Daemon/BaseDaemon.cpp:161: signalHandler(int, siginfo_t*, void*) @ 0x000000000d267f8c
1. ? @ 0x00007f32799c5520
2. ? @ 0x00007f3279a199fd
3. ? @ 0x00007f32799c5476
4. ? @ 0x00007f32799ab7f3
5.0. inlined from ./contrib/llvm-project/libcxxabi/src/cxa_exception.cpp:670: __cxa_decrement_exception_refcount
5.1. inlined from ./contrib/llvm-project/libcxx/src/support/runtime/exception_pointer_cxxabi.ipp:17: ~exception_ptr
5. ./build_docker/./src/Daemon/BaseDaemon.cpp:629: terminate_handler() @ 0x000000000d267a70
6. ./build_docker/./contrib/llvm-project/libcxxabi/src/cxa_handlers.cpp:61: std::__terminate(void (*)()) @ 0x00000000179dba43
7. ? @ 0x00000000179dba3b
8. ./build_docker/./src/Coordination/KeeperStateMachine.cpp:0: DB::(anonymous namespace)::assertDigest(DB::KeeperStorage::Digest const&, DB::KeeperStorage::Digest const&, Coordination::ZooKeeperRequest const&, unsigned long, bool) (.llvm.5429427660923619534) @ 0x000000001315921e
9.0. inlined from ./contrib/llvm-project/libcxx/include/atomic:958: bool std::__cxx_atomic_load[abi:v15000]<bool>(std::__cxx_atomic_base_impl<bool> const*, std::memory_order)
9.1. inlined from ./contrib/llvm-project/libcxx/include/atomic:1588: std::__atomic_base<bool, false>::load[abi:v15000](std::memory_order) const
9.2. inlined from ./src/Common/ThreadFuzzer.cpp:196: DB::ThreadFuzzer::isStarted()
9.3. inlined from ./src/Common/ThreadFuzzer.cpp:445: pthread_mutex_unlock
9.4. inlined from ./contrib/llvm-project/libcxx/include/__threading_support:314: std::__libcpp_mutex_unlock[abi:v15000](pthread_mutex_t*)
9.5. inlined from ./contrib/llvm-project/libcxx/src/mutex.cpp:52: std::mutex::unlock()
9.6. inlined from ./contrib/llvm-project/libcxx/include/__mutex_base:100: ~lock_guard
9. ./build_docker/./src/Coordination/KeeperStateMachine.cpp:301: DB::KeeperStateMachine::preprocess(DB::KeeperStorage::RequestForSession const&) @ 0x0000000013158de4
10. ./build_docker/./src/Coordination/KeeperStateMachine.cpp:391: DB::KeeperStateMachine::commit(unsigned long, nuraft::buffer&) @ 0x000000001315a8e4
11.0. inlined from ./build_docker/./contrib/NuRaft/src/handle_commit.cxx:335: nuraft::raft_server::commit_app_log(unsigned long, std::shared_ptr<nuraft::log_entry>&, bool, bool)
11. ./build_docker/./contrib/NuRaft/src/handle_commit.cxx:265: nuraft::raft_server::commit_in_bg_exec(unsigned long, bool) @ 0x000000001528b8be
12. ./build_docker/./contrib/NuRaft/src/handle_commit.cxx:158: nuraft::raft_server::commit_in_bg() @ 0x000000001528af60
13.0. inlined from ./src/Common/LockMemoryExceptionInThread.cpp:18: ~LockMemoryExceptionInThread
13. ./build_docker/./src/Coordination/KeeperServer.cpp:199: DB::KeeperServer::KeeperRaftServer::commit_in_bg() @ 0x00000000130eeef9
14.0. inlined from ./contrib/llvm-project/libcxx/include/__functional/invoke.h:0: ?
14.1. inlined from ./contrib/llvm-project/libcxx/include/__functional/invoke.h:394: ?
14.2. inlined from ./contrib/llvm-project/libcxx/include/__functional/invoke.h:479: ?
14.3. inlined from ./contrib/llvm-project/libcxx/include/__functional/function.h:235: ?
14. ./contrib/llvm-project/libcxx/include/__functional/function.h:716: ? @ 0x0000000015285922
15.0. inlined from ./base/base/../base/wide_integer_impl.h:817: bool wide::integer<128ul, unsigned int>::_impl::operator_eq<wide::integer<128ul, unsigned int>>(wide::integer<128ul, unsigned int> const&, wide::integer<128ul, unsigned int> const&)
15.1. inlined from ./base/base/../base/wide_integer_impl.h:1491: bool wide::operator==<128ul, unsigned int, 128ul, unsigned int>(wide::integer<128ul, unsigned int> const&, wide::integer<128ul, unsigned int> const&)
15.2. inlined from ./base/base/../base/strong_typedef.h:42: StrongTypedef<wide::integer<128ul, unsigned int>, DB::UUIDTag>::operator==(StrongTypedef<wide::integer<128ul, unsigned int>, DB::UUIDTag> const&) const
15.3. inlined from ./src/Common/OpenTelemetryTraceContext.h:65: DB::OpenTelemetry::Span::isTraceEnabled() const
15.4. inlined from ./build_docker/./src/Common/ThreadPool.cpp:464: ThreadPoolImpl<std::thread>::worker(std::__list_iterator<std::thread, void*>)
15.5. inlined from ./build_docker/./src/Common/ThreadPool.cpp:219: operator()
15.6. inlined from ./contrib/llvm-project/libcxx/include/__functional/invoke.h:394: ?
15.7. inlined from ./contrib/llvm-project/libcxx/include/thread:284: _ZNSt3__116__thread_executeB6v15000INS_10unique_ptrINS_15__thread_structENS_14default_deleteIS2_EEEEZN14ThreadPoolImplINS_6threadEE12scheduleImplIvEET_NS_8functionIFvvEEE8PriorityNS_8optionalImEEbEUlvE0_JETpTnmJEEEvRNS_5tupleIJSA_T0_DpT1_EEENS_15__tuple_indicesIJXspT2_EEEE
15. ./contrib/llvm-project/libcxx/include/thread:295: void* std::__thread_proxy[abi:v15000]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void ThreadPoolImpl<std::thread>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>>(void*) @ 0x000000000d077c83
16. ? @ 0x00007f3279a17ac3
17. ? @ 0x00007f3279aa9850
```

@antonio2368 Is it something known or should I create an issue?

**Comment by antonio2368** [comment]
@serxa it's known that something strange is going on with Keeper after restarts during performance tests.

**Comment by serxa** [comment]
`00180_no_seek_avoiding_when_reading_from_cache` (ubsan) – flaky

**Pull request merged**
