### PR TITLE
Break some tests

### PR DESCRIPTION
**Pull request by tavplubix**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Detailed description / Documentation draft:
Check replication consistency after 993-like tests

### CODE REVIEW

**Comment by tavplubix** [comment]
@Mergifyio update

**Comment by tavplubix** [comment]
Wow, no related failures! But we should backport all fixes before merging this. And this PR will probably make tests more flaky

**Comment by tavplubix** [comment]
@Mergifyio update

**Comment by tavplubix** [comment]
@Mergifyio update

**Comment by tavplubix** [comment]
Stress test (address) — Hung check failed - #27931

**Comment by tavplubix** [comment]
@Mergifyio update

**Comment by tavplubix** [comment]
Functional stateless tests (release) - `Code: 415. DB::Exception: All replicas are lost. (ALL_REPLICAS_LOST)`

**Comment by tavplubix** [comment]
No related failures

**Comment by tavplubix** [comment]
@Mergifyio update

**Review by alesapin — APPROVED** [review]

**Pull request merged**
