### PR TITLE
Add clickhouse client hints

### LINKED ISSUE #32237: Poor usability of command line options in clickhouse-client
```
milovidov@milovidov-desktop:~/work/ClickHouse$ clickhouse-client --hardware_utilization 1
Code: 552. DB::Exception: Unrecognized option '--hardware_utilization'. (UNRECOGNIZED_ARGUMENTS)

milovidov@milovidov-desktop:~/work/ClickHouse$ clickhouse-client --hardware-utilization 1
Code: 36. DB::Exception: Positional options are not supported. (BAD_ARGUMENTS)

milovidov@milovidov-desktop:~/work/ClickHouse$ clickhouse-client --hardware-utilization
ClickHouse client version 21.12.1.1.
Connecting to localhost:9000 as user default.
Connected to ClickHouse server version 21.12.1 revision 54452.

milovidov-desktop :)
```

No hints for typos in option names.
We should add hints with `IHints`.

### PR DESCRIPTION
**Pull request by lingtaolf**
Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Support hints for clickhouse-client and clickhouse-local. Closes https://github.com/ClickHouse/ClickHouse/issues/32237,

Detailed description / Documentation draft:
This PR solved the problem mentioned in #32237

After changing, client will give the hints if you used a wrong option:
```text
(base) ➜  ~ clickhouse-client --hardware_utilization 1
Code: 552. DB::Exception: Unrecognized option '--hardware_utilization'. Maybe you meant ['--hardware-utilization']. (UNRECOGNIZED_ARGUMENTS)  
```

### CODE REVIEW

**Comment by lingtaolf** [comment]
@kssenii I have no idea on how to do functional testing. Do you have any suggestions?

**Comment by kssenii** [comment]
> @kssenii I have no idea on how to do functional testing. Do you have any suggestions?

See about stateless tests here https://clickhouse.com/docs/en/development/tests/

**Comment by lingtaolf** [comment]
> > @kssenii I have no idea on how to do functional testing. Do you have any suggestions?
> 
> See about stateless tests here https://clickhouse.com/docs/en/development/tests/

@kssenii Thanks for you reply. I know how to add tests for clickhouse. I mean I don't know how to add test for this PR. It just give hints when users use wrong options. Should I add a script to parse the exception message and make sure clickhouse client return the hints when users input wrong options?

**Comment by kssenii** [comment]
Yes, let's add, it will be the same as https://github.com/ClickHouse/ClickHouse/blob/master/tests/queries/0_stateless/02050_clickhouse_local_parsing_exception.sh, so very easy to add.

**Comment by lingtaolf** [comment]
> Yes, let's add, it will be the same as https://github.com/ClickHouse/ClickHouse/blob/master/tests/queries/0_stateless/02050_clickhouse_local_parsing_exception.sh, so very easy to add -- just to check correct exception message for one case.

done ! Thanks for your help.

**Comment by kssenii** [comment]
@lingtaolf there are many related tests failures. Seek failed stateless tests.

**Comment by lingtaolf** [comment]
> @lingtaolf there are many related tests failures. Seek failed stateless tests.
  
ok, I'll try to fix the related tests.

**Comment by lingtaolf** [comment]
@kssenii The CI is running too slowly . Is there something wrong with it ? Should I push an empty commit to restart it ?

**Comment by kssenii** [comment]
> @kssenii The CI is running too slowly . Is there something wrong with it ? Should I push an empty commit to restart it ?

No, CI is ok, tests are finished, except for performance tests but its ok.

Need to fix style check:
https://s3.amazonaws.com/clickhouse-test-reports/32841/5c683f91a88ee413606c84c97f3620feb6c4bc79/style_check__actions_.html

**Comment by lingtaolf** [comment]
> > @kssenii The CI is running too slowly . Is there something wrong with it ? Should I push an empty commit to restart it ?
> 
> No, CI is ok, tests are finished, except for performance tests but its ok.
> 
> Need to fix style check: https://s3.amazonaws.com/clickhouse-test-reports/32841/5c683f91a88ee413606c84c97f3620feb6c4bc79/style_check__actions_.html
> 
> ```
> /ClickHouse/src/Client/ClientBase.cpp:1723:    auto getter = [](const auto & op) {
> /ClickHouse/src/Client/ClientBase.cpp:1733:    
> /ClickHouse/src/Client/ClientBase.cpp:    
> ^ Trailing whitespaces.
> ```

I can't find the whitespace

> > @kssenii The CI is running too slowly . Is there something wrong with it ? Should I push an empty commit to restart it ?
> 
> No, CI is ok, tests are finished, except for performance tests but its ok.
> 
> Need to fix style check: https://s3.amazonaws.com/clickhouse-test-reports/32841/5c683f91a88ee413606c84c97f3620feb6c4bc79/style_check__actions_.html
> 
> ```
> /ClickHouse/src/Client/ClientBase.cpp:1723:    auto getter = [](const auto & op) {
> /ClickHouse/src/Client/ClientBase.cpp:1733:    
> /ClickHouse/src/Client/ClientBase.cpp:    
> ^ Trailing whitespaces.
> ```

Emmm.... I can't find any whitespaces at the end of this line. T_T

**Review by kssenii — APPROVED** [review]

**Pull request merged**
