### PR TITLE
Cherry pick #60464 to 24.1: Try to avoid calculation of scalar subqueries for CREATE TABLE.

### PR DESCRIPTION
**Pull request by robot-clickhouse**
Original pull-request #60464

This pull-request is a first step of an automated backporting.
It contains changes similar to calling `git cherry-pick` locally.
If you intend to continue backporting the changes, then resolve all conflicts if any.
Otherwise, if you do not want to backport them, then just close this pull-request.

The check results does not matter at this step - you can safely ignore them.

### Note

This pull-request will be merged automatically. Please, **do not merge it manually** (but if you accidentally did, nothing bad will happen).

#### If the PR was manually reopened after being closed

If this PR is stuck (i.e. not automatically merged after one day), check https://github.com/ClickHouse/ClickHouse/pull/60464 for `pr-backports-created` *label* and delete it.

Manually merging will do nothing. The `pr-backports-created` *label* prevents the original PR https://github.com/ClickHouse/ClickHouse/pull/60464 from being processed.

#### If the conflicts were resolved in a wrong way

If this cherry-pick PR is completely screwed by a wrong conflicts resolution, and you want to recreate it:

- delete the `pr-cherrypick` label from the PR
- delete this branch from the repository

You also need to check the original PR https://github.com/ClickHouse/ClickHouse/pull/60464 for `pr-backports-created`, and delete if it's presented there

### CODE REVIEW

**Comment by robot-ch-test-poll** [comment]
Dear @KochetovNicolai, @antaljanosbenjamin, the PR is not updated for 1d24h58m34s. Please, either resolve the conflicts, or close it to finish the backport process of #60464

**Comment by robot-ch-test-poll4** [comment]
Dear @KochetovNicolai, @antaljanosbenjamin, the PR is not updated for 1d25h0m14s. Please, either resolve the conflicts, or close it to finish the backport process of #60464

**Comment by robot-ch-test-poll3** [comment]
Dear @KochetovNicolai, @antaljanosbenjamin, the PR is not updated for 1d24h2m9s. Please, either resolve the conflicts, or close it to finish the backport process of #60464

**Comment by robot-ch-test-poll4** [comment]
Dear @KochetovNicolai, @antaljanosbenjamin, the PR is not updated for 1d25h2m5s. Please, either resolve the conflicts, or close it to finish the backport process of #60464

**Comment by robot-ch-test-poll** [comment]
Dear @KochetovNicolai, @antaljanosbenjamin, the PR is not updated for 1d24h55m23s. Please, either resolve the conflicts, or close it to finish the backport process of #60464

**Comment by robot-clickhouse** [comment]
Dear @KochetovNicolai, @antaljanosbenjamin, the PR is not updated for 1d24h59m58s. Please, either resolve the conflicts, or close it to finish the backport process of #60464

**Comment by robot-clickhouse** [comment]
Dear @KochetovNicolai, @antaljanosbenjamin, the PR is not updated for 1d24h0m39s. Please, either resolve the conflicts, or close it to finish the backport process of #60464

**Comment by robot-clickhouse** [comment]
Dear @KochetovNicolai, @antaljanosbenjamin, the PR is not updated for 1d24h59m45s. Please, either resolve the conflicts, or close it to finish the backport process of #60464

**Comment by robot-ch-test-poll1** [comment]
Dear @KochetovNicolai, @antaljanosbenjamin, the PR is not updated for 1d24h59m45s. Please, either resolve the conflicts, or close it to finish the backport process of #60464

**Comment by robot-ch-test-poll** [comment]
Dear @KochetovNicolai, @antaljanosbenjamin, the PR is not updated for 1d24h59m27s. Please, either resolve the conflicts, or close it to finish the backport process of #60464

**Comment by robot-ch-test-poll** [comment]
Dear @KochetovNicolai, @antaljanosbenjamin, the PR is not updated for 1d25h1m33s. Please, either resolve the conflicts, or close it to finish the backport process of #60464

**Comment by robot-ch-test-poll** [comment]
Dear @KochetovNicolai, @antaljanosbenjamin, the PR is not updated for 1d24h0m23s. Please, either resolve the conflicts, or close it to finish the backport process of #60464

**Comment by robot-ch-test-poll** [comment]
Dear @KochetovNicolai, @antaljanosbenjamin, the PR is not updated for 1d25h1m0s. Please, either resolve the conflicts, or close it to finish the backport process of #60464

**Comment by robot-clickhouse-ci-1** [comment]
Dear @KochetovNicolai, @antaljanosbenjamin, the PR is not updated for 1d24h56m15s. Please, either resolve the conflicts, or close it to finish the backport process of #60464

**Comment by robot-clickhouse-ci-2** [comment]
Dear @KochetovNicolai, @antaljanosbenjamin, the PR is not updated for 1d24h2m38s. Please, either resolve the conflicts, or close it to finish the backport process of #60464

**Comment by robot-ch-test-poll** [comment]
Dear @KochetovNicolai, @antaljanosbenjamin, the PR is not updated for 1d24h14m24s. Please, either resolve the conflicts, or close it to finish the backport process of #60464

**Comment by robot-ch-test-poll3** [comment]
Dear @KochetovNicolai, @antaljanosbenjamin, the PR is not updated for 1d26h52m8s. Please, either resolve the conflicts, or close it to finish the backport process of #60464

**Comment by robot-ch-test-poll4** [comment]
Dear @KochetovNicolai, @antaljanosbenjamin, the PR is not updated for 1d25h22m10s. Please, either resolve the conflicts, or close it to finish the backport process of #60464

**Comment by robot-clickhouse-ci-1** [comment]
Dear @KochetovNicolai, @antaljanosbenjamin, the PR is not updated for 1d24h1m48s. Please, either resolve the conflicts, or close it to finish the backport process of #60464

**Comment by robot-ch-test-poll3** [comment]
Dear @KochetovNicolai, @antaljanosbenjamin, the PR is not updated for 1d24h32m6s. Please, either resolve the conflicts, or close it to finish the backport process of #60464

**Comment by robot-clickhouse-ci-1** [comment]
Dear @KochetovNicolai, @antaljanosbenjamin, the PR is not updated for 1d24h56m14s. Please, either resolve the conflicts, or close it to finish the backport process of #60464

**Comment by robot-ch-test-poll** [comment]
Dear @KochetovNicolai, @antaljanosbenjamin, the PR is not updated for 1d24h59m56s. Please, either resolve the conflicts, or close it to finish the backport process of #60464

**Comment by robot-ch-test-poll2** [comment]
Dear @KochetovNicolai, @antaljanosbenjamin, the PR is not updated for 1d24h0m32s. Please, either resolve the conflicts, or close it to finish the backport process of #60464

**Comment by robot-clickhouse-ci-2** [comment]
Dear @KochetovNicolai, @antaljanosbenjamin, the PR is not updated for 1d24h59m41s. Please, either resolve the conflicts, or close it to finish the backport process of #60464

**Comment by robot-ch-test-poll1** [comment]
Dear @KochetovNicolai, @antaljanosbenjamin, the PR is not updated for 1d24h59m35s. Please, either resolve the conflicts, or close it to finish the backport process of #60464

**Comment by robot-ch-test-poll1** [comment]
Dear @KochetovNicolai, @antaljanosbenjamin, the PR is not updated for 1d24h0m14s. Please, either resolve the conflicts, or close it to finish the backport process of #60464

**Comment by robot-ch-test-poll1** [comment]
Dear @KochetovNicolai, @antaljanosbenjamin, the PR is not updated for 1d24h59m37s. Please, either resolve the conflicts, or close it to finish the backport process of #60464

**Comment by robot-clickhouse-ci-1** [comment]
Dear @KochetovNicolai, @antaljanosbenjamin, the PR is not updated for 1d24h0m2s. Please, either resolve the conflicts, or close it to finish the backport process of #60464

**Comment by robot-ch-test-poll1** [comment]
Dear @KochetovNicolai, @antaljanosbenjamin, the PR is not updated for 1d25h0m4s. Please, either resolve the conflicts, or close it to finish the backport process of #60464

**Comment by robot-ch-test-poll** [comment]
Dear @KochetovNicolai, @antaljanosbenjamin, the PR is not updated for 1d24h1m9s. Please, either resolve the conflicts, or close it to finish the backport process of #60464

**Comment by robot-ch-test-poll1** [comment]
Dear @KochetovNicolai, @antaljanosbenjamin, the PR is not updated for 1d24h57m6s. Please, either resolve the conflicts, or close it to finish the backport process of #60464

**Comment by robot-ch-test-poll4** [comment]
Dear @KochetovNicolai, @antaljanosbenjamin, the PR is not updated for 1d24h1m35s. Please, either resolve the conflicts, or close it to finish the backport process of #60464

**Comment by robot-ch-test-poll4** [comment]
Dear @KochetovNicolai, @antaljanosbenjamin, the PR is not updated for 1d24h0m7s. Please, either resolve the conflicts, or close it to finish the backport process of #60464

**Comment by robot-clickhouse-ci-2** [comment]
Dear @KochetovNicolai, @antaljanosbenjamin, the PR is not updated for 1d24h59m44s. Please, either resolve the conflicts, or close it to finish the backport process of #60464

**Comment by robot-ch-test-poll4** [comment]
Dear @KochetovNicolai, @antaljanosbenjamin, the PR is not updated for 1d24h27m3s. Please, either resolve the conflicts, or close it to finish the backport process of #60464

**Comment by robot-ch-test-poll** [comment]
Dear @KochetovNicolai, @antaljanosbenjamin, the PR is not updated for 1d24h32m4s. Please, either resolve the conflicts, or close it to finish the backport process of #60464

**Comment by robot-ch-test-poll** [comment]
Dear @KochetovNicolai, @antaljanosbenjamin, the PR is not updated for 1d24h0m56s. Please, either resolve the conflicts, or close it to finish the backport process of #60464

**Comment by robot-ch-test-poll4** [comment]
Dear @KochetovNicolai, @antaljanosbenjamin, the PR is not updated for 1d24h59m52s. Please, either resolve the conflicts, or close it to finish the backport process of #60464

**Pull request closed without merging**
