### PR TITLE
CI: make style check faster

### PR DESCRIPTION
**Pull request by maxknv**
#do_not_test

### Changelog category (leave one):
- CI Fix or Improvement (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
...

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by robot-ch-test-poll3** [comment]
*This is an automated comment for commit 0ada98e98b05b78beaaa95e3eceeacda1191a211 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/61133/0ada98e98b05b78beaaa95e3eceeacda1191a211/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
@maxknv There is no style check in release branches.

**Comment by alexey-milovidov** [comment]
Something is strange - all style checks started to fail.

**Comment by maxknv** [comment]
> Something is strange - all style checks started to fail.
my bad

> @maxknv There is no style check in release branches.
do you mean no need to backport? backport is automatic for ci now

**Pull request merged**
