### PR TITLE
Fix actions execution during preliminary filtering (PK, partition pruning)

### PR DESCRIPTION
**Pull request by azat**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix actions execution during preliminary filtering (PK, partition pruning)

Previously preliminary filtering works incorrectly if input columns had
been used multiple times, because:
- position initialized only for the first user
- column had been moved, so the second user will get nullptr

And this was the case when it had been required multiple times.

Consider the following example:

    select * from data final prewhere indexHint(_partition_id = 'all') or indexHint(_partition_id = 'all')

Actions for this PREWHERE is the following:

    (lldb) p actions.__ptr_->dumpActions()
    (std::string) $1 = "input:
    _partition_id LowCardinality(String)
    _partition_id LowCardinality(String)

    actions:
    INPUT : 0 -> _partition_id LowCardinality(String) : 0
    COLUMN Const(String) -> 'all' String : 1
    COLUMN Const(String) -> 'UInt8'_String String : 2
    INPUT : 1 -> _partition_id LowCardinality(String) : 3
    COLUMN Const(String) -> 'all' String : 4
    COLUMN Const(String) -> 'UInt8'_String String : 5
    FUNCTION equals(_partition_id :: 0, 'all' :: 1) -> equals(_partition_id, 'all') LowCardinality(UInt8) : 6
    FUNCTION equals(_partition_id :: 3, 'all' :: 4) -> equals(_partition_id, 'all') LowCardinality(UInt8) : 1
    FUNCTION _CAST(equals(_partition_id, 'all') :: 6, 'UInt8'_String :: 2) -> _CAST(equals(_partition_id, 'all'), 'UInt8'_String) UInt8 : 4
    FUNCTION _CAST(equals(_partition_id, 'all') :: 1, 'UInt8'_String :: 5) -> _CAST(equals(_partition_id, 'all'), 'UInt8'_String) UInt8 : 2
    FUNCTION or(_CAST(equals(_partition_id, 'all'), 'UInt8'_String) :: 4, _CAST(equals(_partition_id, 'all'), 'UInt8'_String) :: 2) -> or(indexHint(), indexHint())"...

It has _partition_id column in input multiple times.

So fix this by adding a flag (`allow_duplicates_in_input`), if set,
columns will be fully initialized.

### CODE REVIEW

**Comment by robot-ch-test-poll2** [comment]
*This is an automated comment for commit 0bbd87c42160e351b6eb5ada62ba107bed7f5409 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/60196/0bbd87c42160e351b6eb5ada62ba107bed7f5409/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/60196/0bbd87c42160e351b6eb5ada62ba107bed7f5409/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Comment by jkartseva** [comment]
Please check the chase where input columns repeat three and more times, e.g.:
``` sql
select * from data final prewhere indexHint(_partition_id = 'all') or indexHint(_partition_id = 'all') or indexHint(_partition_id = 'all');
```

I'm getting
```
Received exception from server (version 24.2.1):
Code: 11. DB::Exception: Received from localhost:9000. DB::Exception: Position out of bound in Block::erase(), max position = 0. (POSITION_OUT_OF_BOUND)
(query: select * from data final prewhere indexHint(_partition_id = 'all') or indexHint(_partition_id = 'all') or indexHint(_partition_id = 'all');)
```

**Comment by azat** [comment]
>AST fuzzer (msan) — Received signal 11

- https://github.com/ClickHouse/ClickHouse/issues/59684

**Review by jkartseva — APPROVED** [review]

**Comment by azat** [comment]
>Bugfix validation — New test(s) failed to reproduce a bug

- https://github.com/ClickHouse/ClickHouse/pull/60375

>AST fuzzer (asan) — Received signal 11

- https://github.com/ClickHouse/ClickHouse/issues/59684

>Stress test (tsan) — Sanitizer assert (in stderr.log)

- https://github.com/ClickHouse/ClickHouse/issues/60376

**Pull request merged**
