### PR TITLE
Changelog script

### PR DESCRIPTION
**Pull request by Felixoid**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Rewrite the changelog generator script to a pure python. Run it for 2022. Add it for freshly created tags.

### CODE REVIEW

**Comment by Felixoid** [comment]
the latest run of CI

**Review by qoega — COMMENTED** [review]
I think we need to show full changelog in stable release. Prestable one is a subset of it. Is it so?

**Comment by Felixoid** [comment]
> I think we need to show full changelog in stable release. Prestable one is a subset of it. Is it so?

It takes the previous tag automatically and generates a changelog for it. Since we'll have raw changelogs only, and will process them manually in any case, one will use prestable for notes in stable, I assume.

Another thing we consider now is completely to get rid of prestable, so I wouldn't invest time into ignoring them too much.

**Review by alexey-milovidov — APPROVED** [review]

**Review by melvynator — APPROVED** [review]
Lgtm

**Comment by tavplubix** [comment]
@Felixoid, you forgot to take a look at failed checks before merging, Style Check failure is probably related

**Comment by Felixoid** [comment]
It was cancelled by a lambda https://github.com/ClickHouse/ClickHouse/actions/runs/2299711650/attempts/1

But still, yes, I forgot

**Comment by alexey-milovidov** [comment]
@Felixoid unfortunately this script is wrong, unstable, and leads to data loss.
That's the reason we missed some new features in the changelog for version 22.6.

**Comment by alexey-milovidov** [comment]
For example, this is the bulletproof script from @KochetovNicolai: #4169
And this is a quite alright script from @akuzm: https://github.com/ClickHouse/ClickHouse/blame/2c88e914d704ace3fb3ca503609c55bc0398ea39/utils/simple-backport/changelog.sh

**Comment by Felixoid** [comment]
I address potential and, probably, real issues in #39421

**Comment by Felixoid** [comment]
BTW, I tried the old script against 22.6, and it didn't add anything new. We should find, for sure, if there's something missed. But it just works for me

**Pull request merged**
