### PR TITLE
Vectorize bitHammingDistance with simsimd

### PR DESCRIPTION
**Pull request by rickif**
### Changelog category (leave one):
- Performance Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Vectorize bitHammingDistance with simsimd, to close https://github.com/ClickHouse/ClickHouse/issues/59389

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [x]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Run only fuzzers related jobs (libFuzzer fuzzers, AST fuzzers, etc.)
- [ ]  Exclude: AST fuzzers
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-clickhouse-ci-2** [comment]
*This is an automated comment for commit 03534fa3869042162c326b70e12963bd3db15f85 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/70845/03534fa3869042162c326b70e12963bd3db15f85/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/71df65c2888cd67c8b0885bb001c360644ece769/docs_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Review by alexey-milovidov — CHANGES_REQUESTED** [review]
This applies it on a per-element basis which defeats the purpose.
This PR does not apply it for big integers.
What is the difference in performance?

**Comment by alexey-milovidov** [comment]
@rickif, currently it does not build.

**Comment by rickif** [comment]
@alexey-milovidov Sorry for the late response.
So should we implement vectorization that handles multiple elements at once? I misunderstood this issue. I'll try to modify the code.

**Comment by alexey-milovidov** [comment]
Yes, vectorization only makes sense when it handles multiple elements at once.
But regardless of what the changes are, they should be proven by a test, showing that queries sped up.

**Pull request closed without merging**
