### PR TITLE
Fix fundamentally broken `test_throttling`

### LINKED ISSUE #68179: `test_throttling` has failed
https://s3.amazonaws.com/clickhouse-test-reports/60197/eb652adf62ea7de7836e3631e4fd97c28ab09ccf/integration_tests__asan__old_analyzer__[2_6].html

### PR DESCRIPTION
**Pull request by alexey-milovidov**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Closes #68179
CC @azat

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
The test has so many mistakes - no wonder it fails.

**Comment by robot-ch-test-poll3** [comment]
*This is an automated comment for commit 20b97a45bf3c73960e71e1a158cec35ec522ccff with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/68180/20b97a45bf3c73960e71e1a158cec35ec522ccff/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Builds</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/c1c8e6dd8d3b5aaf8f4e8589371254334e88ee10/builds/report.html">✅ success</a></td></tr>
<tr><td>ClickBench</td><td>Runs [ClickBench](https://github.com/ClickHouse/ClickBench/) with instant-attach table</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/c1c8e6dd8d3b5aaf8f4e8589371254334e88ee10/clickbench__aarch64_.html">✅ success</a></td></tr>
<tr><td>Compatibility check</td><td>Checks that <b>clickhouse</b> binary runs on distributions with old libc versions. If it fails, ask a maintainer for help</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/c1c8e6dd8d3b5aaf8f4e8589371254334e88ee10/compatibility_check__aarch64_.html">✅ success</a></td></tr>
<tr><td>Docker keeper image</td><td>The check to build and optionally push the mentioned image to docker hub</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/c1c8e6dd8d3b5aaf8f4e8589371254334e88ee10/docker_keeper_image.html">✅ success</a></td></tr>
<tr><td>Docker server image</td><td>The check to build and optionally push the mentioned image to docker hub</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/c1c8e6dd8d3b5aaf8f4e8589371254334e88ee10/docker_server_image.html">✅ success</a></td></tr>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/68161/d314e5aa45fb8ac91324721ab278185b09437a40/docs_check.html">✅ success</a></td></tr>
<tr><td>Fast test</td><td>Normally this is the first check that is ran for a PR. It builds ClickHouse and runs most of <a href="https://clickhouse.com/docs/en/development/tests#functional-tests">stateless functional tests</a>, omitting some. If it fails, further checks are not started until it is fixed. Look at the report to see which tests fail, then reproduce the failure locally as described <a href="https://clickhouse.com/docs/en/development/tests#functional-test-locally">here</a></td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/0b1887eb65707da3a1053c5e658b526be72f7946/fast_test.html">✅ success</a></td></tr>
<tr><td>Flaky tests</td><td>Checks if new added or modified tests are flaky by running them repeatedly, in parallel, with more randomization. Functional tests are run 100 times with address sanitizer, and additional randomization of thread scheduling. Integration tests are run up to 10 times. If at least once a new test has failed, or was too long, this check will be red. We don't allow flaky tests, read <a href="https://clickhouse.com/blog/decorating-a-christmas-tree-with-the-help-of-flaky-tests/">the doc</a></td><td>✅ success</td></tr>
<tr><td>Install packages</td><td>Checks that the built packages are installable in a clear environment</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/c1c8e6dd8d3b5aaf8f4e8589371254334e88ee10/install_packages__aarch64_.html">✅ success</a></td></tr>
<tr><td>Stateful tests</td><td>Runs stateful functional tests for ClickHouse binaries built in various configurations -- release, debug, with sanitizers, etc</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/c1c8e6dd8d3b5aaf8f4e8589371254334e88ee10/stateful_tests__aarch64_.html">✅ success</a></td></tr>
<tr><td>Unit tests</td><td>Runs the unit tests for different release types</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/c1c8e6dd8d3b5aaf8f4e8589371254334e88ee10/unit_tests__asan_.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Comment by azat** [comment]
>The test has so many mistakes - no wonder it fails.

@alexey-milovidov And what are this "so many mistakes"? Now it just don't have upper limit, of course this will help, but the idea was to keep it strict, since there was couple of bugs that had been uncovered by this, for instance multi-write to S3 (https://github.com/ClickHouse/ClickHouse/pull/55559)

**Comment by alexey-milovidov** [comment]
We run tests on busy machines in parallel. To reliably check the upper bound of runtime, you need to organize the test differently.

**Comment by alexey-milovidov** [comment]
See `should_take` and `bandwidth`.

**Comment by azat** [comment]
>See should_take and bandwidth.

Those are just typos

**Comment by alexey-milovidov** [comment]
https://github.com/ClickHouse/ClickHouse/issues/68316

**Comment by alexey-milovidov** [comment]
@azat It is fundamentally broken. For example, it failed again today: https://s3.amazonaws.com/clickhouse-test-reports/0/a51f867ce014a4cb8f97c46e004b90f5feafd80f/integration_tests__asan__[4_4].html

We cannot tolerate fundamentally broken tests.

**Pull request merged**
