### PR TITLE
Fix an error in the release script - it didn't allow to make 23.12.

### PR DESCRIPTION
**Pull request by alexey-milovidov**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by robot-clickhouse-ci-1** [comment]
*This is an automated comment for commit 9d1e124102743e2d86e8dcbc6697f47cc25a2f0d with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/58288/9d1e124102743e2d86e8dcbc6697f47cc25a2f0d/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/58288/9d1e124102743e2d86e8dcbc6697f47cc25a2f0d/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Comment by Felixoid** [comment]
@alexey-milovidov instead of updating the version to 24.1 you've decided to break the working script and make nonsense 23.13?

The script did its best, though.

**Comment by alexey-milovidov** [comment]
I wanted to release the **minor** version 23.12, but it didn't allow me to do it.

**Comment by Felixoid** [comment]
The version to release 23.12 exists since 23.11 spun out. The script bumps the next version, and in one month we'll need 24.1, not the 23.13 that was made.

It's not me who invented the process. I just reflected it in the code preventing doing the wrong things.

**Pull request merged**
