### PR TITLE
Add primitive charting capabilities

### PR DESCRIPTION
**Pull request by alexey-milovidov**
### Changelog category (leave one):
- New Feature

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Add chart visualization to Play UI.

Screenshot_20220618_181642
Screenshot_20220618_182324

See https://youtu.be/0fSp9SF8N8A?t=813

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
Three bugs exist:
- the ticks at the bottom can overlap in some rare cases;
- the ticks at the left can not fit and overflow if fractional numbers are drawn;
- there can be excessive ticks: https://github.com/leeoniya/uPlot/issues/709

These bugs are "won't fix" because I'm not a JS developer and I don't want to bother.

**Comment by alexey-milovidov** [comment]
@mergifyio update

**Comment by azat** [comment]
https://s3.amazonaws.com/clickhouse-test-reports/38197/f3264e50ec4232041e9703661549973f242006ab/stateless_tests__ubsan__actions_.html

```
2022-06-20 10:09:35 02232_dist_insert_send_logs_level_hung:                                 [ FAIL ] 620.03 sec. - having stderror: 
```

@alexey-milovidov The problem is that `log_comment` is not correct w/o #37932 

```
2022.06.20 10:03:25.312680 [ 182192 ] {8bf16470-ee6a-4b07-8c66-08406a0f4663} <Debug> executeQuery: (from [::1]:46328) (comment: '02232_dist_insert_send_logs_level_hung.sh') KILL QUERY WHERE Settings['log_comment'] = '02232_dist_insert_send_logs_level_hung.sh' SYNC (stage: Complete)
```

**Comment by alexey-milovidov** [comment]
@mergifyio update

**Pull request merged**
