### PR TITLE
Make performance test `test norm_dist.xml` more realistic

### PR DESCRIPTION
**Pull request by rschu1ze**
Re-submit of #58922 (motivated by #58866) which was reverted with #58989.

Dimension = 200 (instead of 10) is more realistic for vector search use cases.

Additionally fixes test errors like [here](https://s3.amazonaws.com/clickhouse-test-reports/58949/7518241be40acdb29c8aaa9e4ee89e61ee57c9ec/performance_comparison_%5B2_4%5D/report.html) which caused the revert.

Explanation about the test failures: The test data was stored in in-memory Array and Tuple tables, each consuming about 80 GB. The population of the Tuple tables exceeded the maximum memory thresholds (*).

Therefore,
- Reduce the Array cardinality from 200 to 150 and the number of rows from 10 to 8 million, reducing memory consumption to ca. 50 GB. This should pass the memory threshold and does not affect the test purpose.
- Don't test tuples. Due to their data layout, vector search is not efficient anyways. Saves another 80 GB.

Besides that, this PR delete redundant test `norm_distance_float.xml` which duplicates the workload in `norm_distance.xml`

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by robot-ch-test-poll1** [comment]
*This is an automated comment for commit aa2d36e598508a95522b93b9fd4b55d9cec9f75d with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/58995/aa2d36e598508a95522b93b9fd4b55d9cec9f75d/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/58995/aa2d36e598508a95522b93b9fd4b55d9cec9f75d/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Comment by Algunenano** [comment]
Let's see if we can force perf tests to run. If not we should change it to a perf improvement tag and then change it back to not for changelog

**Comment by rschu1ze** [comment]
Afaik, x86 perf tests run on every code-related PR. Label `pr-performance-tests` only triggers ARM perf tests (which are nice-to-have on this PR, of course).

**Comment by Algunenano** [comment]
I'm not sure if this is true anymore. In the original PR (https://github.com/ClickHouse/ClickHouse/pull/58922) the performance tests were skipped. It might be an unintended change at some recent point though

**Review by Algunenano — APPROVED** [review]

**Comment by Algunenano** [comment]
This is again crashing performance servers, e.g. https://s3.amazonaws.com/clickhouse-test-reports/59078/74e012049bad67b1c70d2f3aa9eb32d9fc96a1ca/performance_comparison_[1_4]/report.html#run-errors

```
2024.01.22 22:38:55.169019 [ 867 ] {} <Fatal> Application: Child process was terminated by signal 9 (KILL). If it is not done by 'forcestop' command or manually, the possible cause is OOM Killer (see 'dmesg' and look at the '/var/log/kern.log' for the details).
```

**Comment by rschu1ze** [comment]
:-( The per-test timeout of 300 sec is still hit in the failing tests. I'll reduce the test complexity further.

@Algunenano Do you know if there is some central monitoring of performance tests (similar to [this](https://play.clickhouse.com/play?user=play#c2VsZWN0IHB1bGxfcmVxdWVzdF9udW1iZXIgYXMgcHIsIGNoZWNrX3N0YXJ0X3RpbWUsIGNoZWNrX25hbWUsIHRlc3RfbmFtZSwgdGVzdF9zdGF0dXMgYXMgc3RhdHVzLCByZXBvcnRfdXJsCmZyb20gY2hlY2tzCndoZXJlIHRvRGF0ZShjaGVja19zdGFydF90aW1lKSA+ICcyMDIzLTAxLTE1JyBhbmQgdGVzdF9uYW1lIGxpa2UgJyUwMjk1MV9pbnZlcnRlZF9pbmRleF9zdXBwb3J0X21hdGNoJScKb3JkZXIgYnkgY2hlY2tfc3RhcnRfdGltZSBkZXNj) for functional tests)?

**Pull request merged**
