### PR TITLE
Update argmax.md 

### PR DESCRIPTION
**Pull request by Taschenbergerm**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Improvement

Changed the description of the usage of tuple in argMax. 
First, the syntax was not correct agMax need two arguments and now it shows even better the usage with an arbitrary number of arguments.

### CODE REVIEW

**Comment by kitaisreal** [comment]
Hello, `argMax`, `argMin` function require two arguments, but if only one argument is passed and this argument is tuple of two elements special case is applied and first tuple columns used and first argument and second tuple column used as second argument.
```
CREATE TABLE test_argmax (user String, salary UInt64) ENGINE=TinyLog;
INSERT INTO test_argmax VALUES ('first', 10), ('second', 30), ('third', 20);
```
Standard case:
```
SELECT argMax(user, salary) FROM test_argmax
┌─argMax(user, salary)─┐
│ second               │
└──────────────────────
```
Special case is applied:
```
SELECT argMax((user, salary)) FROM test_argmax
┌─argMax(tuple(user, salary))─┐
│ ('second',30)               │
└─────────────────────────────┘
```

If we call it like argMax((user, salary), salary), standard case is applied, documentation probably is right.

**Comment by Taschenbergerm** [comment]
Hi kitaisreal, 

we just recently tried on our instance ( when we first encountered the documentation) But when we just gave the tuple argument without the second parameter - we did get a SQL error.  
That was the motivation for the fork 

Query: CREATE TABLE default.test_arg_max(
arg1 Int8, 
date_time DateTime)
ENGINE=MergeTree()
ORDER BY date_time; 

INSERT INTO default.test_arg_max VALUES(1, now());
INSERT INTO default.test_arg_max VALUES(2, now());

SELECT argMax(tuple(arg1, date_time)) 
FROM default.test_arg_max

Error 
SQL Error [42]: ClickHouse exception, code: 42, host: <server> port: 8123; Code: 42, e.displayText() = DB::Exception: Aggregate function argMax requires two arguments (version 20.11.4.13 (official build))

**Comment by alexey-milovidov** [comment]
@Taschenbergerm Maybe it's only in newer versions?

**Comment by kitaisreal** [comment]
@Taschenbergerm, support for tuple as single argument was added in newer versions in this pull request https://github.com/ClickHouse/ClickHouse/pull/17359. Documentation is fine.

CC: @alexey-milovidov

**Pull request merged**
