### PR TITLE
Fix invalid format detection in schema inference

### LINKED ISSUE #66888: LOGICAL_ERROR: Format {} doesn't support schema inference
https://s3.amazonaws.com/clickhouse-test-reports/0/5547ce1a91c95b6b88f911e7bbddf3faeef871e6/stress_test__azure__tsan_.html

```
SELECT [''], ( SELECT * FROM file('') ) , ( SELECT * FROM cosn('', 8.7) ) , (CAST(([]) AS DateTime))
```

Error in 24.6:
```
Code: 715. DB::Exception: The data format cannot be detected by the contents of the files. You can specify the format manually: (in file/uri /mnt/ch/ClickHouse/). (CANNOT_DETECT_FORMAT)
```

Error in master:
```
Received exception:
Code: 636. DB::Exception: The table structure cannot be extracted from a Markdown format file. Error:
Code: 49. DB::Exception: FormatFactory: Format Markdown doesn't support schema inference. (LOGICAL_ERROR) (version 24.7.1.1).
You can specify the structure manually: (in file/uri /mnt/ch/ClickHouse/.git-blame-ignore-revs). (CANNOT_EXTRACT_TABLE_STRUCTURE)
```

### PR DESCRIPTION
**Pull request by Avogar**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix invalid format detection in schema inference that could lead to logical error Format {} doesn't support schema inference.

Closes https://github.com/ClickHouse/ClickHouse/issues/66888

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-clickhouse** [comment]
*This is an automated comment for commit 454eb1af7ed69d00617e6bfa3daece508fcb565b with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/66899/454eb1af7ed69d00617e6bfa3daece508fcb565b/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/91693daf599bbaeaed5adb8cba257c176628e2be/docs_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Review by thevar1able — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
What about the case when the format is inferred from the file name, using `auto`, but the structure was specified explicitly, so it does not have to be inferred?

**Comment by Avogar** [comment]
> What about the case when the format is inferred from the file name, using auto, but the structure was specified explicitly, so it does not have to be inferred?

It's happening in another place. This PR touches only code related to format detection + schema inferencee

**Review by alexey-milovidov — APPROVED** [review]

**Comment by Avogar** [comment]
> Stateless tests (release) — fail: 1

https://github.com/ClickHouse/ClickHouse/pull/66839

**Pull request merged**
