### PR TITLE
Allow tupleElement accept nullable input argument

### PR DESCRIPTION
**Pull request by taiyang-li**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Allow tupleElement accept nullable input argument. It makes sense for gluten.

### CODE REVIEW

**Comment by robot-clickhouse-ci-2** [comment]
*This is an automated comment for commit 89e29f54fd9570f79409eaf4500817e5db425d71 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/58238/89e29f54fd9570f79409eaf4500817e5db425d71/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/58238/89e29f54fd9570f79409eaf4500817e5db425d71/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Comment by Avogar** [comment]
Do I understand correctly that this PR will make sense only after https://github.com/ClickHouse/ClickHouse/pull/53443?

**Comment by taiyang-li** [comment]
> Do I understand correctly that this PR will make sense only after #53443?

You are right.

**Comment by Avogar** [comment]
> But this pr could be merged before https://github.com/ClickHouse/ClickHouse/pull/53443 because it doesn't have impact on current impls based on assumption that complex types can't be nullable.

I don't think we should merge this PR before https://github.com/ClickHouse/ClickHouse/pull/53443 for several reasons:
- The change just doesn't make any sense without that PR (and it's unclear who and when will finish that PR)
- Without that PR we cannot even test changes in this PR
- This code will be really confusing for future readers without merging that PR

**Comment by taiyang-li** [comment]
@Avogar I'll close this PR and reopen it after https://github.com/ClickHouse/ClickHouse/pull/53443

**Pull request closed without merging**
