### PR TITLE
Translate zh/faq/operations/multi-region-replication:

### PR DESCRIPTION
**Pull request by ghost**
Changelog category (leave one):
- Documentation (changelog entry is not required)

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
...

> Information about CI checks: https://clickhouse.tech/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by kitaisreal** [comment]
@Mergifyio update

**Comment by cnmade** [comment]
@kitaisreal hello, may this pull request be done?

**Comment by kitaisreal** [comment]
@Mergifyio update

**Comment by kitaisreal** [comment]
@Mergifyio update

**Comment by cnmade** [comment]
@evillique @kitaisreal hello, can this pull request be done?

**Review by kitaisreal — APPROVED** [review]

**Pull request merged**
