### PR TITLE
fix: wrong documentation toc title

### PR DESCRIPTION
**Pull request by arjenzhou**
Changelog category (leave one):
- Documentation (changelog entry is not required)

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

fix wrong documentation in `ALTER` toc title. 

> Information about CI checks: https://clickhouse.tech/docs/en/development/continuous-integration/

### CODE REVIEW

**Review by qoega — APPROVED** [review]

**Comment by kitaisreal** [comment]
@Mergifyio update

**Comment by kitaisreal** [comment]
@Mergifyio update

**Comment by kitaisreal** [comment]
@arjenzhou documentation build is broken https://s3.amazonaws.com/clickhouse-test-reports/33931/494dccd98c8730db43e7648500d1d2618b552543/docs_check__actions_.html, need to be fixed. Probably `toc_title: ALTER` is valid, because we already have `toc_title: TABLE`.

**Comment by arjenzhou** [comment]
@kitaisreal copy that, I'm going to close this.

**Pull request closed without merging**
