### PR TITLE
Implement ForEach modifier for aggregate functions.

### PR DESCRIPTION
**Pull request by mfridental**

### CODE REVIEW

**Comment by robot-metrika-test** [comment]
Can one of the admins verify this patch?

**Comment by alexey-milovidov** [comment]
Everything is fine and ready to merge!
I will fix style and check some edge cases (when arrays have different size), after merging.

**Comment by alexey-milovidov** [comment]
In fact, the code is totally wrong. I am preparing a fix right now.

**Comment by alexey-milovidov** [comment]
https://github.com/yandex/ClickHouse/commit/83ed2a794bfff2fae245b647fdde9348a00aaf60
https://github.com/yandex/ClickHouse/commit/d9793bf5fea890e936c868209a71896cdd4adbe9
https://github.com/yandex/ClickHouse/commit/6b5e6104a9db556d907b4a73f25f272a20d2d4bf
https://github.com/yandex/ClickHouse/commit/3fa1639877eb94a0ceaa4a1d6d54684f0c0c7623

(most changes are in first commit)

Notable differences:
- incorrect usage of Arena::allocContinue;
- no exception safety in methods ensureAggregateData and deserialize;
- redundant code in method insertResultInto.

**Comment by alexey-milovidov** [comment]
Syntetic performance test:
```
SELECT sumForEach([number, number]) FROM system.numbers_mt
```

(performance is Ok)

**Comment by alexey-milovidov** [comment]
The combinator also works for parametric aggregate functions, example:
```
SELECT 
    k, 
    groupArrayForEach(arr), 
    quantilesExactForEach(0.5, 0.9)(arr)
FROM 
(
    SELECT 
        intDiv(number, 3) AS k, 
        arrayMap(x -> (number + x), range(number)) AS arr
    FROM system.numbers 
    LIMIT 10
) 
GROUP BY k
ORDER BY k ASC

┌─k─┬─groupArrayForEach(arr)──────────────────────────────────────────────────┬─quantilesExactForEach(0.5, 0.9)(arr)────────────────────────────────────┐
│ 0 │ [[1,2],[3]]                                                             │ [[2,2],[3,3]]                                                           │
│ 1 │ [[3,4,5],[4,5,6],[5,6,7],[7,8],[9]]                                     │ [[4,5],[5,6],[6,7],[8,8],[9,9]]                                         │
│ 2 │ [[6,7,8],[7,8,9],[8,9,10],[9,10,11],[10,11,12],[11,12,13],[13,14],[15]] │ [[7,8],[8,9],[9,10],[10,11],[11,12],[12,13],[14,14],[15,15]]            │
│ 3 │ [[9],[10],[11],[12],[13],[14],[15],[16],[17]]                           │ [[9,9],[10,10],[11,11],[12,12],[13,13],[14,14],[15,15],[16,16],[17,17]] │
└───┴─────────────────────────────────────────────────────────────────────────┴─────────────────────────────────────────────────────────────────────────┘
```

**Comment by mfridental** [comment]
Wow, that was quick, thank you so much!

I was trying to understand today what's wrong with using Arena::allocContinue, could you please explain?

About too much work in insertResultInto, I was under impression that one AggregateDataPtr can point to results for several aggregation keys. Now in the hindsight, its obviously wrong, because for example otherwise the IAggregateFunction::add would need to take aggregation key as an argument. Perhaps we could add in the comments of IAggreateFunction::add and IAggregateFunction::insertResultInto that  each AggregateDataPtr place will be used for at most one aggregation key (but one aggregation key could correspond to several AggregateDataPtr places)?

**Comment by alexey-milovidov** [comment]
> I was trying to understand today what's wrong with using Arena::allocContinue, could you please explain?

`allocContinue` is intended only for resizing just allocated memory region. The purpose is for almost free resizing in most cases, when just allocated region could be expanded inside same chunk.

It is not suitable in your case, because, during aggregation, one key could be updated, then second key, then first key, again, with larger array - and you need to reallocate memory for first aggregation state, but it is not just-allocated memory.

**Comment by alexey-milovidov** [comment]
> Perhaps we could add in the comments of IAggreateFunction::add and IAggregateFunction::insertResultInto that each AggregateDataPtr place will be used for at most one aggregation key (but one aggregation key could correspond to several AggregateDataPtr places)?

Aggregation state could not be shared for multiple keys - this seems obviously (otherwise, how it will be possible to extract several results from that state).

Data for one key could be aggregated inside several aggregation states - in different threads of execution (parallel query execution) and on different servers (distributed query execution). These states will be merged into one to obtain final result.

Also multiple states could be merged to produce TOTALS values, when using WITH TOTALS modifier.

**Pull request merged**
