### PR TITLE
Fix output of clickhouse-test in case of tests timeouts

### PR DESCRIPTION
**Pull request by azat**
After https://github.com/ClickHouse/ClickHouse/pull/67737 the output will be broken, since in case of timeout it will print to stdout.

Let's just capture it and add it to stderr.

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Follow-up for: https://github.com/ClickHouse/ClickHouse/pull/67737

### CODE REVIEW

**Comment by nickitat** [comment]
is there maybe an easy way to test this?

**Comment by azat** [comment]
There are no tests for `clickhouse-test`, but I've tested it manually it works

**Comment by nickitat** [comment]
ok.

**Review by nickitat — APPROVED** [review]

**Comment by robot-ch-test-poll3** [comment]
*This is an automated comment for commit a66db7abc2cced463e8ff9a04530c4647ddf8a22 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/68487/a66db7abc2cced463e8ff9a04530c4647ddf8a22/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/cb3468f6d1376a869e916ff31dcd2916d737b255/docs_check.html">✅ success</a></td></tr>
<tr><td>Fast test</td><td>Normally this is the first check that is ran for a PR. It builds ClickHouse and runs most of <a href="https://clickhouse.com/docs/en/development/tests#functional-tests">stateless functional tests</a>, omitting some. If it fails, further checks are not started until it is fixed. Look at the report to see which tests fail, then reproduce the failure locally as described <a href="https://clickhouse.com/docs/en/development/tests#functional-test-locally">here</a></td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/da1d09b2d9c8f9a70527f704de54019f64331bc7/fast_test.html">✅ success</a></td></tr>
<tr><td>Unit tests</td><td>Runs the unit tests for different release types</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/da1d09b2d9c8f9a70527f704de54019f64331bc7/unit_tests__release_.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Comment by azat** [comment]
>Stateful tests (msan) — Invalid check_status.tsv

According to logs looks like spot instances issue

**Pull request merged**
