### PR TITLE
Fix data race in S3::ClientCache

### PR DESCRIPTION
**Pull request by k-morozov**
We read region_for_bucket_cache and uri_for_bucket_cache from other_client without locking. At the same time other_client can execute ClientCache::clearCache() in another thread.

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [x]  Allow: All Required Checks
- [x]  Allow: Stateless tests
- [x]  Allow: Stateful tests
- [x]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by antonio2368** [comment]
Makes sense. Was it caught with a sanitizer or did you notice it in the code?

**Comment by k-morozov** [comment]
> Makes sense. Was it caught with a sanitizer or did you notice it in the code?

I noticed it in the code.
We have a problem that S3 disk cache holds a large number of connections and does not close them in time (status CLOSE_WAIT), which leads to increased consumption of tcp_mem. So I reserched this problem and I found this data race. Im not sure that it wiil resolve my problem. However, maybe the problems are related.. 

I would also like to point out that TSA_GUARDED_BY doesn't found this problem in copy ctor.

**Comment by antonio2368** [comment]
This is not a connection cache, but just information cache mapping a bucket to correct region/URI
Few months ago we introduced connection pool and with that couple of configs:
https://github.com/ClickHouse/ClickHouse/pull/58845/files#diff-3f7b59d638c38403accf4f916f98a03ceecfae10cdd71bac4cd2cc2d9b08cae1
Maybe it could be related to that

**Review by antonio2368 — APPROVED** [review]

**Comment by k-morozov** [comment]
@antonio2368 my typo, lock other's mutexes.

**Comment by robot-clickhouse-ci-1** [comment]
*This is an automated comment for commit 0de54b9d296927b7a8bc84bf1f8bfe5a5a01f080 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/66644/0de54b9d296927b7a8bc84bf1f8bfe5a5a01f080/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/93abd4a6e900cc7ac2c2ba8eb00c8262e8ec2866/docs_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Pull request merged**
