### PR TITLE
A desperate attempt to improve the integration tests codestyle.

### PR DESCRIPTION
**Pull request by pufit**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

It's not a secret that the quality standards for code in tests are usually lower than those for production code. That said, when the test infrastructure becomes more complex, I believe good quality code can significantly reduce the new potential flaky tests. This PR is a desperate attempt to refactor the libraries for integration testing. I'll probably split this refactoring into a couple of PRs and will do it in my free time.

### TODO
- ~~typing declaration in returns~~
- ~~finish the replacement of all .format to f-strings~~

### Known problems:
Using .format or f-strings in logging is an anti-pattern. But unfortunately, it is so commonly spread in our code that I'll leave it as is. Also, I am currently trying to minimalize changing of actual test logic.

### CODE REVIEW

**Review by nikitamikhaylov — APPROVED** [review]

**Comment by robot-ch-test-poll1** [comment]
This is an automated comment for commit d6a800805d6c51d743655fe43fa11de5158af58b with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/47665/d6a800805d6c51d743655fe43fa11de5158af58b/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Comment by alexey-milovidov** [comment]
Is it desperate?

**Comment by alexey-milovidov** [comment]
@pufit How desperate is it?

**Comment by pufit** [comment]
> @pufit How desperate is it?

It is quite desperate, but I hope I will be able to finish at least this small part soon!

**Comment by alexey-milovidov** [comment]
Please reopen if needed.

**Pull request closed without merging**
