### PR TITLE
Query in form data

### PR DESCRIPTION
**Pull request by stavrolia**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

New feature: now you can send query to HTTP api along with `multipart/form-data` as file with name `query`. It is usable, if you have to send external tables, but your query is big enough to be sent via GET param (in uri).

It can be tested with: `curl localhost:8123/?query="select" -X POST -F "query= 1;"`

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
Please add a test. Look at `dbms/tests/queries` directory. You can use any test of `sh` type as an example.

**Comment by stavrolia** [comment]
There is a basic test, and what do you mean by external tables?

**Comment by stavrolia** [comment]
In updated version of this branch it is able to send >16K (I tested on 20K). I can add it to test if necessary.

**Comment by alexey-milovidov** [comment]
Merged manually
(because branch was created from `stable`, not from `master`)

**Comment by alexey-milovidov** [comment]
Looks perfectly correct. Thank you!

**Pull request closed without merging**
