### PR TITLE
Uniform SSL configuration for Keeper and CH server

### PR DESCRIPTION
**Pull request by Enmk**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Allowing the SSL configuration of Keeper to be more fine-grained and uniform with the ClickHouse server, by re-using Poco's `SSL_CTX`. That adds support for all of the configuration features that were not set by the initial implementation: `openSSL.server.dhParamsFile`, `openSSL.server.cipherList`, `openSSL.server.disableProtocols`, and others.

Depends on https://github.com/eBay/NuRaft/pull/412

`SSL_CTX` instances are already shared by 'server' threads of ClickHouse when handling multiple incoming SSL requests and by 'client' threads when establishing outgoing SSL connections and that seems to be working just fine.

### Documentation entry for user-facing changes

- [x] Documentation is written (mandatory for new features)

Keeper's NuRaft SSL connections can now be configured in exactly the same way as ClickHouse server SSL connections, supporting the full range of [Poco's SSL configuration options](https://docs.pocoproject.org/current/Poco.Net.SSLManager.html).

This change could potentially lead to issues with existing secure Keeper-to-Keeper configurations due to differences in defaults and behavior.
| what | old behaviour  | new behaviour | how to restore to old behaviour |
| -------- | -------------- | ----------- | --------- |
| ⚠️ client (outgoing SSL connections) configuration | Used the same configuration as the server from `openssl.server` | Uses client-specific configuration from `openssl.client` | Copy contents of `openssl.server` configuration into `openssl.client` |
| ⚠️ `verificationMode` default mode (when not explicitly set) |  ⚠️ default mode is `none`<sup>*</sup> and certificate checks errors are ignored | ⚠️ default mode is `relaxed`, certificate check errors not ignored, aborting connection process  | to maintain previous NON-SECURE behavior set `verificationMode` to `none` and set `<invalidCertificateHandler></name>AcceptCertificateHandler</name></invalidCertificateHandler>` for both client and server SSL configurations |
| ⚠️ `loadDefaultCAFile` | **doesn't load** default CA files if `loadDefaultCAFile` is not explicitly set | ⚠️ **loads** default CA files if `loadDefaultCAFile` is not explicitly set | set `loadDefaultCAFile` to `false` | 
| `privateKeyFile` | MUST be present | may be skipped | |
| `certificateFile` | MUST be present | may be skipped | | 
| `caConfig` | only supports file. Requiring to amalgamate trust chain into a single certificate file for complex configurations | supports both file and directory configuration | |

- ⚠️ means behavior changed in a way that may cause problems with establishing connections.
- <sup>*</sup> Only `none` and `relaxed` are supported, any value other than `none` effectively means `relaxed`.

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by robot-clickhouse** [comment]
This is an automated comment for commit d15122b8e45f8192e3f7d9c91fcfe37e63a6f896 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/52535/d15122b8e45f8192e3f7d9c91fcfe37e63a6f896/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Comment by antonio2368** [comment]
Some related tests failed

**Comment by Enmk** [comment]
> Some related tests failed

Yep, that was due to different defaults for NuRaft and Poco's SSL_CTX. Fixed that

**Comment by antonio2368** [comment]
same test failed again

**Comment by alexey-milovidov** [comment]
@Enmk tests have failed.

**Pull request closed without merging**
