### PR TITLE
Allow to change the size of background pools in runtime

### LINKED ISSUE #34311: Allow to change the size of background pools in runtime.
**Use case**

The server is not loaded and I want to do more merges quickly.

**Describe the solution you'd like**

```
SYSTEM SET MERGE POOL SIZE 48
SYSTEM SET FETCH POOL SIZE 48
...
```

### PR DESCRIPTION
**Pull request by zhongyuankai**
Changelog category (leave one):
- New Feature

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
 Change the size of background pools through the system statement. close #34311

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
Ok, but please check that access control is correctly applied for these system commands.
Also need to add a test that proves that it works... it may be not easy, ask @nikitamikhaylov how to do it.

**Comment by zhongyuankai** [comment]
> Ok, but please check that access control is correctly applied for these system commands. Also need to add a test that proves that it works... it may be not easy, ask @nikitamikhaylov how to do it.

@alexey-milovidov @nikitamikhaylov I have an idea, is it possible to increase the background pools metric in `system.metrics`.

**Comment by zhongyuankai** [comment]
@Mergifyio update

**Comment by zhongyuankai** [comment]
@alexey-milovidov @nikitamikhaylov Can you help me, how to avoid errors caused by concurrent testing.

**Comment by zhongyuankai** [comment]
Hi, @alexey-milovidov no one reiview it?

**Comment by nikitamikhaylov** [comment]
And I don't know why these values are defined as settings and not defined in top level config. Because this is a global setting, not a user level... There is no effect to have one value for default profile and one for custom.

**Comment by zhongyuankai** [comment]
> There are several problems. What about RBAC in context of new SYSTEM queries? I am not sure there won't be problems with evicting running tasks from the Executors... I'd like only to allow only to increase the number of threads/tasks at runtime. To lower the number - do a restart.


Thank you for your reply, but I don't understand why modifying the thread pool size affects RBAC, and I think the `MergeTreeBackgroundExecutor<Queue>::wait()` method is a safe exit, and I didn't expect unknown problems.

**Comment by zhongyuankai** [comment]
> And I don't know why these values are defined as settings and not defined in top level config. Because this is a global setting, not a user level... There is no effect to have one value for default profile and one for custom.

Yes, it feels more appropriate to define it in config

**Comment by zhongyuankai** [comment]
@nikitamikhaylov How should this patch be done? Can you give me some hints?

**Comment by nikitamikhaylov** [comment]
Done here https://github.com/ClickHouse/ClickHouse/pull/36425

**Pull request closed without merging**
