### PR TITLE
Disable compressed logs by default in Keeper

### PR DESCRIPTION
**Pull request by antonio2368**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Keeper improvement: disable compressed logs by default in Keeper.

Compressed logs are unreliable. E.g. if we didn't properly write the last uncommitted data to disk we could lose an unknown amount of entries, including committed logs. 

cc @alesapin 

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by robot-ch-test-poll1** [comment]
*This is an automated comment for commit 03c3e968595512558f2cd4a3fddeec0ede75990c with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/56763/03c3e968595512558f2cd4a3fddeec0ede75990c/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td><a href="https://github.com/ClickHouse/ClickHouse/actions/runs/6867386884">✅ success</a></td></tr>
<tbody>
</table>
</details>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/56763/03c3e968595512558f2cd4a3fddeec0ede75990c/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Comment by alexey-milovidov** [comment]
I don't understand - why the logs don't use an incremental compression approach with checkpoints allowing to decompress up to every selected record?

**Review by alexey-milovidov — CHANGES_REQUESTED** [review]
.

**Comment by antonio2368** [comment]
> I don't understand - why the logs don't use an incremental compression approach with checkpoints allowing to decompress up to every selected record?

We do that but the problem is the unreliability.
RAFT relies heavily on the fact that the committed data is safely stored and data loss on a single node can lead to a data loss.
I'm not yet sure how to properly test it, maybe we can introduce some fault injection that will only partially write a batch of logs and fail the append (the problem here is that the failed append will abort the Keeper so we can't just enable it in stateless/stress tests because we run embedded Keeper).
Until we test it properly and are confident enough in it, I'm not okay with enabling it by default for everyone.
This PR also allows to safely switch between different types of logs for existing clusters so we can safely change the default in the future again.

**Review by alexey-milovidov — APPROVED** [review]

**Review by alesapin — APPROVED** [review]

**Pull request merged**
