### PR TITLE
tests: fix test_hive_query flakiness

### LINKED ISSUE #41547: Flaky test_hive_query/test.py::test_text_count
Failing in master last three days
[play ci](https://play.clickhouse.com/play?user=play#CiAgICBTRUxFQ1QKICAgICAgICBjaGVja19uYW1lLAogICAgICAgIGdyb3VwQXJyYXlEaXN0aW5jdCh0ZXN0X25hbWUpLAogICAgICAgIHRvU3RhcnRPZkRheShjaGVja19zdGFydF90aW1lKSwKICAgICAgICBjb3VudCgpCiAgICBGUk9NIGNoZWNrcwogICAgV0hFUkUgdGVzdF9zdGF0dXMgbm90IGluICgnT0snLCAnU0tJUFBFRCcpCiAgICAgICAgQU5EIHRlc3RfbmFtZSBpbGlrZSAnJXRlc3RfaGl2ZV9xdWVyeSUnCiAgICAgICAgQU5EIG5vdygpIC0gSU5URVJWQUwgJzEwJyBkYXkgPD0gY2hlY2tfc3RhcnRfdGltZQogICAgICAgIEFORCBwdWxsX3JlcXVlc3RfbnVtYmVyID09IDAKICAgIEdST1VQIEJZIGNoZWNrX25hbWUsIHRvU3RhcnRPZkRheShjaGVja19zdGFydF90aW1lKSAgIAogICAgT1JERVIgQlkKICAgICAgICB0b1N0YXJ0T2ZEYXkoY2hlY2tfc3RhcnRfdGltZSkgREVTQwogICAgTElNSVQgMjAKCg==)

### PR DESCRIPTION
**Pull request by azat**
Just to make CI green.

### Changelog category (leave one):
- Not for changelog (changelog entry is not required

Cc: @kssenii @taiyang-li 

Fixes: #41547

### CODE REVIEW

**Review by kssenii — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
I don't understand - what was the reason it was broken suddenly?

**Comment by alexey-milovidov** [comment]
This PR did not fix it and now two tests have failed instead of one.

**Comment by azat** [comment]
>I don't understand - what was the reason it was broken suddenly?

The problem is that now some test from this module can be run in parallel, and this breaks them, because some tests there assume the order, i.e. they does not create the tables.

The reason I guess is that because of some new integration tests had been added, the order of parallel execution had been changed and now it became possible to run multiple tests in this module not sequentially.

**Comment by azat** [comment]
>This PR did not fix it and now two tests have failed instead of one.

Yep, because of a silly mistake, lack of semicolon (I hope that it is it), fixed.

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
Interesting, can we add more randomization of tests order?

**Comment by azat** [comment]
>Interesting, can we add more randomization of tests order?

Sure, the magic is here:

- https://github.com/ClickHouse/ClickHouse/blob/b01f5bdca8ed6e71b551234d94b861be299ceabc/tests/integration/runner#L294 (can be changed to `--dist=load`)
- https://github.com/ClickHouse/ClickHouse/blob/master/tests/integration/ci-runner.py

But I don't think it is a good idea to do this right now.

**Comment by alexey-milovidov** [comment]
Let's do it in another PR.

Having uniformly flaky tests is much better than having them stable by unexplainable reason.

**Pull request merged**
