### PR TITLE
Fix fsync_part_directory for horizontal merge

### PR DESCRIPTION
**Pull request by azat**
Changelog category (leave one):
- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix fsync_part_directory for horizontal merge

P.S. looks like fsync related settings are not production ready, maybe worth adding some note about this?

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
What's wrong with the `test_replace_partition/test.py::test_replace_after_replace_failover`?

**Comment by azat** [comment]
>What's wrong with the test_replace_partition/test.py::test_replace_after_replace_failover?

Let's try #21674

**Comment by alexey-milovidov** [comment]
> P.S. looks like fsync related settings are not production ready, maybe worth adding some note about this?

Currently we don't use fsync related settings on any of production services in Yandex, because they don't make any improvement in case when geographically distributed replication is used with quorum inserts (there is no sense to enable these settings). Replication across multiple DCs is the must for all Yandex services.

Most likely these settings will be enabled for Yandex Cloud instances, where users can configure replicas in single datacenter or don't use replicas at all.

**Comment by alexey-milovidov** [comment]
> P.S. looks like fsync related settings are not production ready, maybe worth adding some note about this?

Currently we don't use fsync related settings on any of production services in Yandex, because they don't make any improvement in case when geographically distributed replication is used with quorum inserts (there is no sense to enable these settings). Replication across multiple DCs is the must for all Yandex services.

Most likely these settings will be enabled for Yandex Cloud instances, where users can configure replicas in single datacenter or don't use replicas at all.

**Pull request merged**
