### PR TITLE
Added test `test_ttl_move::test_alter_with_merge_work`.

### PR DESCRIPTION
**Pull request by excitoon**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- New Feature
- Bug Fix
- Improvement
- Performance Improvement
- Backward Incompatible Change
- Build/Testing/Packaging Improvement
- Documentation
- Other
- Non-significant (changelog entry is not needed)

Changelog entry (up to few sentences, required except for Non-significant/Documentation categories):

...

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
?

**Comment by alexey-milovidov** [comment]
Your own test have failed.

**Comment by alexey-milovidov** [comment]
Do you want to continue?

**Comment by alesapin** [comment]
Closed in favor of https://github.com/ClickHouse/ClickHouse/pull/11509

**Pull request closed without merging**
