### PR TITLE
Support start up clickhouse server in daemon mode with relative config path

### PR DESCRIPTION
**Pull request by hexiaoting**
path

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Support start up clickhouse server in daemon mode with relative config path

Detailed description / Documentation draft:

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
@hexiaoting One test failure is related, need to take a look.

**Comment by alexey-milovidov** [comment]
Also need to add a test for a new feature.

**Comment by hexiaoting** [comment]
> @hexiaoting One test failure is related, need to take a look.

The error in fast test:
```
2021-01-29 11:50:03 01669_columns_declaration_serde:                                        [ FAIL ] - return code 253
2021-01-29 11:50:03 [03cbf02603de] 2021.01.29 11:50:02.855845 [ 44909 ] {0f4c46a7-1e94-471b-a80c-6f150fd34db8} <Warning> default.test_r1 (5923484b-24b9-45fb-a95d-76a90204c619): It looks like the table /clickhouse/test was created by another server at the same moment, will retry
2021-01-29 11:50:03 [03cbf02603de] 2021.01.29 11:50:02.856392 [ 44909 ] {0f4c46a7-1e94-471b-a80c-6f150fd34db8} <Warning> default.test_r1 (5923484b-24b9-45fb-a95d-76a90204c619): It looks like the table /clickhouse/test was created by another server at the same moment, will retry
```
I don't know how to reproduce it.


A test case for this kind of startup server, Are there any examples?

**Comment by alexey-milovidov** [comment]
@mergifyio update

**Comment by alexey-milovidov** [comment]
Stale.

**Pull request closed without merging**
