### PR TITLE
Allow clickhouse-keeper to serve 4-letter commands before quorum

### LINKED ISSUE #35464: clickhouse-keeper answers 4-letter commands only after getting the quorum
clickhouse-keeper opens the port & start answering 4-letter commands only after getting the quorum

That differs from zookeeper, which start to answer them just after the start.

/cc @Slach @alesapin

### PR DESCRIPTION
**Pull request by antonio2368**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
`clickhouse-keeper` starts answering 4-letter commands before getting the quorum

> Information about CI checks: https://clickhouse.tech/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by nikitamikhaylov** [comment]
How it will serve `srvr` or `mntr` commands? Where the is an info about a replica role inside quorum? `follower` or `leader`?

**Review by qoega — COMMENTED** [review]
We need to check that liveness checks are using ruok and not just open port

**Comment by antonio2368** [comment]
> We need to check that liveness checks are using ruok and not just open port

How do you define liveness? `ruok` will return `imok` without quorum if we start serving commands immediately.

**Comment by antonio2368** [comment]
After checking out how ZooKeeper handles commands, it accepts command requests instantly but for majority of them it refuses to serve results until it's synced with the cluster (quorum is achieved).

Commands without the check: `ruok`, `gtmk`, `envi`. Everything else checks if the server is in a valid state.

What we had until now is a check only for the `mntr` command (if the Keeper has leader, i.e. there is a quorum).
Now, I can add the check for all the commands that ZooKeeper has protected like that to be consistent with it.
The difference from the previous behaviour is that the user will be able to receive that the `instance is not currently serving requests` before the initial quorum is achieved. That means that the same message will be sent if quorum is lost during instance lifetime.

@nikitamikhaylov What do you think?

**Review by nikitamikhaylov — APPROVED** [review]

**Pull request merged**
