### PR TITLE
Merging (feature) Use Map data type for system logs tables

### LINKED ISSUE #18698: Use Map data type for system logs tables.
**Use case**
For `Settings` and `ProfileEvents` fields in `query_log` and `query_thread_log`.
So you don't have to write `ProfileEvents.Values[indexOf(ProfileEvents.Names, 'FileOpen')]` anymore.
It should work as `ProfileEvents['FileOpen']`.

**Implementation**
Just replace the type.
No need to worry about compatibility.

### PR DESCRIPTION
**Pull request by hexiaoting**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Merging https://github.com/ClickHouse/ClickHouse/pull/18762

Changelog category (leave one):
- Backward Incompatible Change

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
- Backward Incompatible Change:

Use Map data type for system logs tables (system.query_log, system.query_thread_log, system.processes, system.OpenTelemetrySpanLog).
These tables will be auto created with new datatypes, old queries maybe incompatible.
Close https://github.com/ClickHouse/ClickHouse/issues/18698

### CODE REVIEW

**Comment by hexiaoting** [comment]
Functional stateless tests (address) failed query: `01455_shard_leaf_max_rows_bytes_to_read.sql`. 
But I run this test case on my server, it's OK. And I don't change any code related to it. 
Any advice?

**Comment by kitaisreal** [comment]
@hexiaoting we recently checked and a lot of users rely on our system tables, for example there are tools that are not longer supported by maintainers that rely on some system.tables structure. As additional change we need to keep old columns as virtual storage columns. Check for example system.dictionaries. That way there will be no backward incompatible changes.

**Comment by kitaisreal** [comment]
@hexiaoting yes, it will be best solution for us, because if we merge it as is, there will be issues that some tool that cannot be updated is commited to our system tables column names.

**Comment by hexiaoting** [comment]
> @hexiaoting yes, it will be best solution for us, because if we merge it as is, there will be issues that some tool that cannot be updated is commited to our system tables column names.

OK, I will rewrite the implementation.

**Comment by hexiaoting** [comment]
@kitaisreal I have check `system.dictionaries ` and found it has an interface called `getVirtuals` to set virtual columns.
But system tables like `query_log`, it is not implemented by basing IStorage, It is using `std::make_shared<ASTCreateQuery>()` to create, so it has no interface to set virtual columns. 

Another way, If I using alias like:
`attributes Map(String, String)`
`attribute.names alias mapKeys(attributes)`
`attribute.types alias mapValues(attributes)`
I think It is redundant and not necessary.

So, any advice?

**Comment by hexiaoting** [comment]
@kitaisreal  I need your help.

**Comment by kitaisreal** [comment]
@hexiaoting sorry for the delay, I need to investigate this. Maybe it will require some additional refactoring, but we cannot change logs tables in backward incompatible way, please check https://github.com/ClickHouse/ClickHouse/issues/23435.

**Pull request merged**
