### PR TITLE
Vertical line

### PR DESCRIPTION
**Pull request by Volodyachan**
### Changelog category (leave one):
- New Feature

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Transforms pretty format to vertical format if a single row with multiple columns is received

By default the number of columns is 20 but can be changed by setting `output_format_pretty_min_columns_for_vertical_row`

Value 0 disables the transformation

### CODE REVIEW

**Comment by robot-ch-test-poll4** [comment]
*This is an automated comment for commit ec9a5ed96d1d39bdce5070f8de05478bee800653 with description of existing statuses. It's updated for the latest CI running*

[❌ Click here](https://s3.amazonaws.com/clickhouse-test-reports/63922/ec9a5ed96d1d39bdce5070f8de05478bee800653/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>❌ failure</td></tr>
<tbody>
</table>

**Comment by alexkats** [comment]
Is there a justification why it's enabled by default?

**Review by alexkats — CHANGES_REQUESTED** [review]
I took a look at the code, everything looks good in general, thanks. A couple of things:
- I'd prefer to have this setting disabled by default (I'm also open to hear a good justification why it should be enabled)
- Please squash some commits, so that we'll have a cleaner history
- Resolve the conflicts

Test failure is unrelated and should be fixed by syncing your branch with the latest master

**Comment by alexkats** [comment]
Since there hasn't been any work done quite for some time, I'll close this PR for now. Feel free to reopen it if you decide to continue your work on it.

**Pull request closed without merging**
