### PR TITLE
Rename (un)likely macros to ch_(un)likely to avoid conflicts with e. g. boost::date_time

### PR DESCRIPTION
**Pull request by georgthegreat**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by tavplubix** [comment]
What conflicts are you trying to avoid?

**Comment by georgthegreat** [comment]
In out codebase, likely [conflicts](https://github.com/boostorg/date_time/blob/acbee0dc6a168289c398041e91e053b3684083fc/include/boost/date_time/time_parsing.hpp#L312) with boost/date_time method.

**Comment by Algunenano** [comment]
Have you considered replacing them with the C++20 attributes? For example:

```patch
diff --git a/src/Common/CurrentThread.cpp b/src/Common/CurrentThread.cpp
index a2cdf9c836..bf60a30194 100644
--- a/src/Common/CurrentThread.cpp
+++ b/src/Common/CurrentThread.cpp
@@ -20,7 +20,7 @@ namespace ErrorCodes
 
 void CurrentThread::updatePerformanceCounters()
 {
-    if (unlikely(!current_thread))
+    if (!current_thread) [[unlikely]]
         return;
     current_thread->updatePerformanceCounters();
 }
```

That would get rid of the macros altogether.

**Comment by rschu1ze** [comment]
If this PR gets green light then it would be nice if the old definition of likely() isn't deleted right away but stays there for a little longer. Otherwise, there is a high risk of broken builds during the next weeks - not all open PRs merge master before submit.

Oh, and a purely personal preference: lowercase `ch_likely` / `ch_unlikely` would be less violent on the eyes than `CH_LIKELY`/ `CH_UNLIKELY` (yes, even if macros are supposed to be uppercase).

**Comment by tavplubix** [comment]
But we don't have any issues with these macros, so there's a lack of motivation for renaming everything. Also I don't really like how `CH_LIKELY`/`CH_UNLIKELY` look. So I'm not sure that we should merge this.

**Comment by georgthegreat** [comment]
@alexey-milovidov suggested to remove these statements at all and take a look on the benchmark.

I suggest the following sequence

1. We merge this PR, as it does not cause any harm
2. I bring up new PR which will eval the statements to noop.
3. We launch the benchmarks and considering further actions (if any).

**Comment by tavplubix** [comment]
> We merge this PR, as it does not cause any harm

It does harm to the eyes of some developers, what do you think about making these macros lowercase at least (as @rschu1ze suggested)? And if we're going to touch this code anyway it makes sense to replace macros with standard `[[(un)likely]]` were possible (so changes will not be completely useless).

**Comment by tavplubix** [comment]
> This looks like a full-time job for ClickHouse, Inc

AFAIK, ClickHouse, Inc is totally fine with `(un)likely` macros, we don't need to change anything at all.

**Comment by rschu1ze** [comment]
I'm fine with renaming to `ch_(un)likely`.

> suggested to remove these statements at all and take a look on the benchmark.

The renaming and above task are orthogonal. Feel free to open a second PR where `(un)likely` is made a no-op.

**Comment by tavplubix** [comment]
I mean that this PR makes code (a bit) worse for no reason, so I think that it cannot be merged. Replacing macros with standard solution (where possible) will make it a bit better and it will be a reason to merge it.

**Comment by georgthegreat** [comment]
> I mean that this PR makes code (a bit) worse for no reason

This PR resolves macro conflict inside Yandex codebase, which uses ClickHouse as a query executor engine.
While ClickHouse, Inc might be totally fine with current macro naming, we are not, as we have code that depends on both boost::date_time and ClickHouse (I do not see any problem in depending on both).

Renamic the macros is easy and non-demanding change which resolves the conflict.
Every other option is much more demanding.

I will send the PR to make these macros no-op later on.

**Comment by alexey-milovidov** [comment]
boost::date_time is not a good library, because it does not have support for historical timezone offsets (cctz should be used instead).

**Comment by georgthegreat** [comment]
> boost::date_time is not a good library, because it does not have support for historical timezone offsets (cctz should be used instead).

I can not save entire monorepo from using bad libraries, if they have these usages already.

**Comment by rschu1ze** [comment]
Build error after merge from master:

```
2022-09-03 20:34:12 /ClickHouse/src/Common/MemoryTracker.cpp:215:9: error: use of undeclared identifier 'unlikely'
2022-09-03 20:34:12     if (unlikely(current_hard_limit && will_be > current_hard_limit))
2022-09-03 20:34:12         ^
2022-09-03 20:34:12 1 error generated.
```

To avoid similar errors prior and after merging this PR, see my suggestion [here](https://github.com/ClickHouse/ClickHouse/pull/40676#issuecomment-1228690252).

**Comment by clickhouse-robot-curie** [comment]
I'm ok removing the old definitions and breaking some of the pending pull requests.

**Comment by georgthegreat** [comment]
I am closing this, as boost/date_time was easier to update.

**Pull request closed without merging**
