### PR TITLE
Add schema inference for values() table function.

### LINKED ISSUE #33811: Schema inference for table function `values`.
```
milovidov-desktop :) SELECT * FROM VALUES('a UInt8, b UInt8', (1, 2), (3, 4))

SELECT *
FROM VALUES('a UInt8, b UInt8', (1, 2), (3, 4))

Query id: a377da6f-64a4-408f-a688-123ceb628236

┌─a─┬─b─┐
│ 1 │ 2 │
│ 3 │ 4 │
└───┴───┘

2 rows in set. Elapsed: 0.001 sec. 

milovidov-desktop :) SELECT * FROM VALUES((1, 2), (3, 4))

SELECT *
FROM VALUES((1, 2), (3, 4))

Query id: 28a73a8d-87e7-49ac-bebd-386d76e0b75e


0 rows in set. Elapsed: 0.000 sec. 

Received exception:
Code: 170. DB::Exception: Bad get: has Tuple, requested String. (BAD_GET)
```

### PR DESCRIPTION
**Pull request by Avogar**
Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Add schema inference for values() table function. Closes https://github.com/ClickHouse/ClickHouse/issues/33811

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]

**Comment by Avogar** [comment]
@Mergifyio update

**Comment by alexey-milovidov** [comment]
GitHub is notoriously unstable in the last day, so CI is delayed.

**Comment by alexey-milovidov** [comment]
@Mergifyio update

**Comment by alexey-milovidov** [comment]
@Mergifyio update

**Comment by Avogar** [comment]
@Mergifyio update

**Pull request merged**
