### PR TITLE
Fix ThreadSanitizer data race in librdkafka 

### PR DESCRIPTION
**Pull request by ilejn**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Documentation entry for user-facing changes
Use more recent librdkafka submodule contains https://github.com/ClickHouse/librdkafka/pull/10 to address https://github.com/ClickHouse/ClickHouse/issues/56043

### CODE REVIEW

**Comment by robot-ch-test-poll4** [comment]
*This is an automated comment for commit b31816cc901707ec87eb7c531487467146468d12 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/57791/b31816cc901707ec87eb7c531487467146468d12/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td><a href="https://github.com/ClickHouse/ClickHouse/actions/runs/7184689565">✅ success</a></td></tr>
<tbody>
</table>
</details>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/57791/b31816cc901707ec87eb7c531487467146468d12/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Comment by ilejn** [comment]
Hello @antaljanosbenjamin ,
waiting for IntegrationTestsTsan ...

**Review by antaljanosbenjamin — APPROVED** [review]

**Comment by antaljanosbenjamin** [comment]
The PR looks okay, I cannot imaggine how the tests would be related to the change in librdkafka, however I would like to check the tests to be 100% sure. I will merge this PR later today.

**Comment by ilejn** [comment]
> The PR looks okay, I cannot imaggine how the tests would be related to the change in librdkafka, however I would like to check the tests to be 100% sure. I will merge this PR later today.

Hello Benjamin @antaljanosbenjamin ,
thank you for approval.

02443_detach_attach_partition (stateless) is known as flaky https://github.com/ClickHouse/ClickHouse/issues/54748

Errors in test_postgresql_replica_database_engine_1/test.py::test_many_concurrent_queries are rather common as well https://play.clickhouse.com/play?user=play#LS0gZGVzYyBjaGVja3MKc2VsZWN0IApjb3VudCgpCmZyb20gY2hlY2tzIHdoZXJlIHRlc3RfbmFtZSBsaWtlICcldGVzdF9tYW55X2NvbmN1cnJlbnRfcXVlcmllcyUnICBhbmQgdGVzdF9zdGF0dXMgaW4gKCdGQUlMJywgJ0ZMQUtZJywgJ0VSUk9SJykgYW5kIGNoZWNrX3N0YXJ0X3RpbWUgPiAnMjAyMy0xMS0xMSc7
And the test name sound suspicious enough ;)

The chances that the test failures above are introduced by this PR are close to zero.

**Comment by antaljanosbenjamin** [comment]
Thanks @ilejn!

**Pull request merged**
