### PR TITLE
Fixed flappy `test_multiple_disks`

### PR DESCRIPTION
**Pull request by excitoon**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Fixed flappy `test_multiple_disks`.

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
CI shows that the test `test_multiple_disks/test.py::test_jbod_overflow` is still flaky.

**Review by alexey-milovidov — APPROVED** [review]

**Comment by Akazz** [comment]
Addressess issues discovered in #16235

**Comment by excitoon** [comment]
@alexey-milovidov This PR is unfinished :( Test is still flappy and it passed by good chance

**Comment by alexey-milovidov** [comment]
Well have a good night.

**Comment by excitoon** [comment]
It passed not by chance but because nothing was changed in integration tests.

**Pull request merged**
