### PR TITLE
Refactor CI_CONFIG

### PR DESCRIPTION
**Pull request by Felixoid**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
The previous implementation of `CI_CONFIG` didn't allow tracking the entity types. Now it's easy to achieve, and at the same time, we have a validator for the wrong config content.

### CODE REVIEW

**Comment by robot-clickhouse-ci-2** [comment]
This is an automated comment for commit cf8eff7c9432d38d11b9586cf47445c1a2785ab9 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/52948/cf8eff7c9432d38d11b9586cf47445c1a2785ab9/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Comment by Felixoid** [comment]
It's related to #52847 issue as an intermediate stated for clickhouse-repos-manager

**Comment by alexey-milovidov** [comment]
@Felixoid I don't understand why CI_CONFIG does not work in my PR: https://github.com/ClickHouse/ClickHouse/pull/52293

**Review by alesapin — APPROVED** [review]

**Comment by Felixoid** [comment]
I'll try to backport it to 23.3, otherwise, the conflict will remain for another 7 months

**Pull request merged**
