### PR TITLE
Remove upgrade checks with sanitizers

### PR DESCRIPTION
**Pull request by antaljanosbenjamin**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

We have a lot of issues with OOM in upgrade checks with sanitizers, so they are not required to succeed in order to merge a PR.

### CODE REVIEW

**Comment by robot-ch-test-poll3** [comment]
This is an automated comment for commit c874e5955b49dd818315014f5baa6608a9980fba with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/53051/c874e5955b49dd818315014f5baa6608a9980fba/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Review by Felixoid — APPROVED** [review]
Good to go!

**Review by alexey-milovidov — APPROVED** [review]

**Comment by qoega** [comment]
Change is not enough to disable check.
You need to remove them from workflows as well
image

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
@qoega we are not going to disable the checks.

**Comment by alexey-milovidov** [comment]
@antaljanosbenjamin the remaining check showed itself :rofl:

**Comment by antaljanosbenjamin** [comment]
Upgrade check (msan): https://github.com/ClickHouse/ClickHouse/issues/52978

**Pull request merged**
