### PR TITLE
Second attempt: Use CH Buffer for HTTP out stream, add metrics for interfaces

### PR DESCRIPTION
**Pull request by yakov-olkhovskiy**
Reverts ClickHouse/ClickHouse#58450

### CODE REVIEW

**Comment by robot-ch-test-poll1** [comment]
*This is an automated comment for commit 85f03478efd8f8c2d20c7b6ea3db6d0fb4c38996 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/58475/85f03478efd8f8c2d20c7b6ea3db6d0fb4c38996/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/58475/85f03478efd8f8c2d20c7b6ea3db6d0fb4c38996/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Comment by yakov-olkhovskiy** [comment]
@CheSema could you please review it again - I fixed two issues here

**Comment by CheSema** [comment]
> @CheSema could you please review it again - I fixed two issues here

Do you know how can I see the diff with prev version?

**Comment by yakov-olkhovskiy** [comment]
In general you would need to take diff between commit this branch is branched and head of this branch. But it will be messy since there are couple merges with master in this branch. But changes are not that big - you can take a look just at individual commits above - 
fix for leaking exception:
https://github.com/ClickHouse/ClickHouse/pull/58475/commits/84dd4a74bc75541e2c1cd5499f33b31ba9322c34
fix for flaky "connection reset by peer":
https://github.com/ClickHouse/ClickHouse/pull/58475/commits/feab8127126f42e7cd78d13188a9f97d8bb08cac

**Review by CheSema — APPROVED** [review]

**Pull request merged**
