### PR TITLE
CI: Add ARM+TSAN build and functional tests

### PR DESCRIPTION
**Pull request by maxknv**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
...

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Run only fuzzers related jobs (libFuzzer fuzzers, AST fuzzers, etc.)
- [ ]  Exclude: AST fuzzers
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [x]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-clickhouse-ci-2** [comment]
*This is an automated comment for commit fcbb4f064c054e55c319d9e2353288806a385131 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/71272/fcbb4f064c054e55c319d9e2353288806a385131/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td>✅ success</td></tr>
<tr><td>Fast test</td><td>Normally this is the first check that is ran for a PR. It builds ClickHouse and runs most of <a href="https://clickhouse.com/docs/en/development/tests#functional-tests">stateless functional tests</a>, omitting some. If it fails, further checks are not started until it is fixed. Look at the report to see which tests fail, then reproduce the failure locally as described <a href="https://clickhouse.com/docs/en/development/tests#functional-test-locally">here</a></td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/1c878c397d84c0f57040652d798db331282a7c76/fast_test.html">✅ success</a></td></tr>
<tr><td>Unit tests</td><td>Runs the unit tests for different release types</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/1c878c397d84c0f57040652d798db331282a7c76/unit_tests__release_.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Review by pamarcos — APPROVED** [review]
LGTM :+1: 
I verified that in https://s3.amazonaws.com/clickhouse-test-reports/71272/3a58012c33f9d73ffcfc14c4320b69c9a95272c6/ci_running.html we have the new stateful and 4 stateless tests for `aarch64, tsan`

**Comment by maxknv** [comment]
@rschu1ze can you help please with this arm+tsan [tests](https://s3.amazonaws.com/clickhouse-test-reports/71272/4d2b61e67c2005ed18ed1518cd9d127447ff6e96/stateless_tests__aarch64__tsan__[4_4].html) Does this job makes sense in CI? Can we do something to make it work?

**Comment by rschu1ze** [comment]
@maxknv 

> Does this job makes sense in CI?

In my view, it doesn't. I think that TSAN will find the same issues on x86 and ARM. Since we run stateless and stateful tests on x86 already, I think we don't need to run such tests on ARM as well.

(of course, if there is an overall goal to make the "test landscape" consistent between x86 and ARM, then this PR makes sense).

Regarding https://s3.amazonaws.com/clickhouse-test-reports/71272/4d2b61e67c2005ed18ed1518cd9d127447ff6e96/stateless_tests__aarch64__tsan__%5B4_4%5D.html Upon a quick look, I don't see failures due to TSAN, tests fail because TSAN makes them slower and they timeout, so the fix would be to mark them as `no-tsan`, like done for 02354_vector_search_expansion_search.sql.

**Comment by maxknv** [comment]
Thank you, @rschu1ze.
Since this job doesn’t provide clear value, I think it’s best to close this PR.

**Pull request closed without merging**
