### PR TITLE
change supportsPrewhere() of Buffer and return its destination_table supportsPrewhere

### PR DESCRIPTION
**Pull request by LiuYangkuan**
change supportsPrewhere() of table engine Buffer and return its destination_table supportsPrewhere() or not

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Buffer can help users to batch insert records into MergeTree from small inserting with great frequency. And use Prewhere clause in MergeTree can reduce the volume of data to read.
We often use Buffer upon MergeTree for inserting data, and  only query MergeTree table using prewhere condition, because Buffer can't support prewhere. But this method will make us lost the latest data in the query result.

so this PR can improve Buffer engine and solve the above problem.

Category (leave one):
- Improvement

Short description (up to few sentences):
`Buffer` table engine now supports PREWHERE.

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
PREWHERE is disabled for Buffer engine for reason.

When you query Buffer table, it will read from two places:
- from the destination table;
- from its buffers in memory;

When a query with PREWHERE is executed, filtering by PREWHERE expression must be done entirely inside Storage. In contrast to WHERE, it is not performed in InterpreterSelectQuery. It means, the Storage must be able to perform PREWHERE.

But StorageBuffer does not evaluate PREWHERE when reading from its buffers in memory.

**Comment by alexey-milovidov** [comment]
Here is a test that will provide incorrect results with your PR:
```
USE test;
DROP TABLE IF EXISTS dest;
DROP TABLE IF EXISTS buffer;
CREATE TABLE dest (s String, payload DEFAULT arrayMap(x -> s, range(1000))) ENGINE = MergeTree ORDER BY tuple();
CREATE TABLE buffer AS dest ENGINE = Buffer(test, dest, 1, 10, 60, 10000, 100000, 1000000, 10000000);
INSERT INTO dest (s) VALUES ('hello'), ('world');
INSERT INTO buffer (s) VALUES ('hello'), ('world');
SELECT * FROM dest PREWHERE s = 'world';
SELECT * FROM buffer PREWHERE s = 'world';
DROP TABLE dest;
DROP TABLE buffer;
```

**Comment by alexey-milovidov** [comment]
Your own test has also failed.

**Comment by alexey-milovidov** [comment]
Nevertheless, you can complete this PR in a proper way.
To do it, you should add interpretation of PREWHERE (create ExpressionBlockInputStream FilterBlockInputStream) inside StorageBuffer::read for processing of buffered data.

**Review by alexey-milovidov — CHANGES_REQUESTED** [review]
.

**Comment by LiuYangkuan** [comment]
> Your own test has also failed.

Yes, if I execute my test sql wholly in multi-commands mode, test will be failed. I will take your advice and add interpretation of PREWHERE. Thank you for your advice!

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
The test failure `00637_sessions_in_http_interface_and_settings` - unrelated, already fixed in master.

**Comment by alexey-milovidov** [comment]
Now the implementation looks perfect. Thank you!

**Comment by adubovikov** [comment]
great job!

**Pull request merged**
