### PR TITLE
Remove some dead and commented code

### PR DESCRIPTION
**Pull request by tavplubix**
### Changelog category (leave one):

- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Review by rschu1ze — APPROVED** [review]

**Comment by rschu1ze** [comment]
Just wondering, how did you find the dead code? Does CH run coverage tests?

**Review by alexey-milovidov — APPROVED** [review]

**Comment by tavplubix** [comment]
> Just wondering, how did you find the dead code? 

I was wondering if #39158 may affect user-visible behavior, looked for usages of `SmallMapTable` and found nothing. Also syntax highlighting in CLion helps to find unused functions sometimes.  

> Does CH run coverage tests?

We had coverage (for functional tests) in our CI about two years ago, but we did not manage to support it. Runs with coverage are extremely slow and dump a lot of files to disk that have to be merged, of course it affects tests and causes test failures. But I hope we will resurrect coverage sometime.

**Comment by tavplubix** [comment]
Integration tests (asan, actions) [3/3] - `test_postgresql_replica_database_engine_1`, cc: @kssenii 
Tests with asan were broken in master
Stress test (memory, actions) -  #39490

**Comment by pkit** [comment]
@tavplubix "dead" code was not that dead.
Examples compilation fails after this PR, i.e. `src/Common/examples/small_table.cpp` is broken.

**Comment by pkit** [comment]
Probably need to remove it from samples too then.

**Comment by rschu1ze** [comment]
Follow-up: https://github.com/ClickHouse/ClickHouse/pull/39517

BuilderBinClangTidy is currently the only builder which builds with `-DENABLE_EXAMPLES=1`, which would have detected the problem. Just need to let it finish :grin:

**Comment by pkit** [comment]
> Just need to let it finish

Yup. See #39517

**Comment by tavplubix** [comment]
> "dead" code was not that dead.
> Examples compilation fails after this PR, i.e. src/Common/examples/small_table.cpp is broken.

This example is probably useless and has to be removed as well. Thank you for removing it!

> I would suggest to use -DENABLE_EXAMPLES=1 in CLion to avoid these in the future. As samples were broken too frequently in the last months...

It cannot avoid anything. There are only two ways that can work: completely remove examples or build them in CI (and maybe turn examples into unit tests if possible). 

> BuilderBinClangTidy is currently the only builder which builds with -DENABLE_EXAMPLES=1, which would have detected the problem. Just need to let it finish

All builds (including clang-tidy) have finished successfully on a8da5d96fce7e72859dca8b83c8b1d509b926c69, seems like `-DENABLE_EXAMPLES=1` does not work: https://s3.amazonaws.com/clickhouse-builds/39460/a8da5d96fce7e72859dca8b83c8b1d509b926c69/binary_tidy/build_log.log

**Comment by pkit** [comment]
> All builds (including clang-tidy) have finished successfully on https://github.com/ClickHouse/ClickHouse/commit/a8da5d96fce7e72859dca8b83c8b1d509b926c69, seems like -DENABLE_EXAMPLES=1 does not work: https://s3.amazonaws.com/clickhouse-builds/39460/a8da5d96fce7e72859dca8b83c8b1d509b926c69/binary_tidy/build_log.log

Hmm, it does look like it, as examples are not built in that log, although `-DENABLE_EXAMPLES=1` is clearly present.
Probably it's something specific to that `binary-build` script, because it's not the same as the default one.

**Pull request merged**
