### PR TITLE
Standard join type syntax position

### PR DESCRIPTION
**Pull request by 4ertus2**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Allow to set JOIN kind and type in more standad way: `LEFT SEMI JOIN` instead of `SEMI LEFT JOIN`. For now both are correct.

### CODE REVIEW

**Comment by akuzm** [comment]
What is a `LEFT SEMI JOIN`? `SEMI` selects left side where matching right side exists, and `LEFT` selects left side always. Together it doesn't make sense. I guess our definition of semi join includes right side columns, so this should select all left rows and any matching right row? Saying this is more standard is a stretch...

**Comment by 4ertus2** [comment]
> What is a `LEFT SEMI JOIN`?

It is present on internet. Ex. https://stackoverflow.com/questions/21738784/difference-between-inner-join-and-left-semi-join
SEMI means not INNER or OURER. `SEMI JOIN` is `LEFT SEMI JOIN` with omitted LEFT. It's just like `JOIN` is `INNER JOIN` with omitted `INNER`.

**Comment by akuzm** [comment]
> > What is a `LEFT SEMI JOIN`?
> 
> It is present on internet. Ex. https://stackoverflow.com/questions/21738784/difference-between-inner-join-and-left-semi-join
> `SEMI` means not `INNER` or `OUTER`. `SEMI JOIN` is `LEFT SEMI JOIN` with omitted `LEFT`. It's just like `JOIN` is `INNER JOIN` with omitted `INNER`.

You mean, `LEFT` keyword is not the same as `LEFT` join, but means that the left side is returned for `SEMI` join, and `RIGHT SEMI JOIN` would be a mirrored version? I think I'm not the last person by far to be confused about this grammar, and the new grammar looks even worse. Not sure what could be better, maybe I'd even write it in one word as `SEMILEFT` to emphasize that is doesn't have anything to do with a `LEFT JOIN`.

**Comment by akuzm** [comment]
I think I understand it better now after looking at this image... Maybe it's more standard this way indeed.

TbHy6

**Comment by 4ertus2** [comment]
> I think I understand it better now after looking at this image... 

Cool picture

**Pull request merged**
