### PR TITLE
Fix logical error in group_by_use_nulls + grouping set + analyzer + materialize/constant

### LINKED ISSUE #61531: Logical error "Expected single dictionary argument for function" in `materialize(toLowCardinality(...))`
**Describe what's wrong**
```
SELECT trunc(materialize(toLowCardinality(0)), materialize(toLowCardinality(0)));

Received exception from server (version 24.2.2):
Code: 49. DB::Exception: Received from localhost:9000. DB::Exception: Expected single dictionary argument for function.. (LOGICAL_ERROR)
(query: SELECT trunc(materialize(toLowCardinality(0)), materialize(toLowCardinality(0))))
```
https://fiddle.clickhouse.com/a91273fc-32a6-4735-92e1-68bf1a6fd00a

**Does it reproduce on the most recent release?**
yes

**Expected behavior**
should not produce LOGICAL_ERROR

**Additional context**
Found by fuzzer:
https://s3.amazonaws.com/clickhouse-test-reports/58223/be4554ba431c2c496c139e6b4869a68ca3ba58dc/ast_fuzzer__ubsan_.html

### PR DESCRIPTION
**Pull request by Avogar**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix logical error ''Unexpected return type from materialize. Expected Nullable. Got UInt8' while using group_by_use_nulls with analyzer and materialize/constant in grouping set. Closes #61531

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by novikd** [comment]
I think #59986 is a better fix.

**Comment by Avogar** [comment]
> I think https://github.com/ClickHouse/ClickHouse/pull/59986 is a better fix.

Checked binary from that PR, It doesn't fix logical errors that this PR fixes

**Comment by Avogar** [comment]
Fuzzer found more issues with analyzer + group_by_use_nulls + grouping set . Now with optimization `optimize_injective_functions_in_group_by`:
```
avogar-dev :) SELECT intExp2(intExp2(number)) + 3 FROM numbers(10) GROUP BY GROUPING SETS (('str', intExp2(intExp2(number))), ('str'))

2024.03.19 21:30:54.879840 [ 141977 ] {554cd503-3ee5-44ea-b1ae-69aee68972ee} <Fatal> : Logical error: 'intExp2's argument does not match the expected data type'.

:) SELECT tuple(tuple(tuple(number))) FROM numbers(10) GROUP BY GROUPING SETS (('str', tuple(tuple(number))), ('str'))

2024.03.19 21:36:08.450028 [ 142147 ] {abfb7bf2-f410-4abf-b5e7-58604be9e187} <Fatal> : Logical error: 'Bad cast from type DB::ColumnNullable to DB::ColumnVector<unsigned long>'.

:) SELECT materialize(3) + 3 FROM numbers(10) GROUP BY GROUPING SETS (('str', materialize(materialize(3))), ('str'))

2024.03.19 21:37:18.963723 [ 142170 ] {81540cdc-0a95-469a-a96f-cb5f6d95bf70} <Fatal> : Logical error: 'Unexpected return type from plus. Expected UInt16. Got Nullable'.
```

AFAIU when we replace injection function with it's arguments, we will make these arguments `Nullable` when `group_by_use_nulls=1` instead of initial keys with injective functions, and it leads to unexpected `Nullable` columns in functions execution. I couldn't come up with a good solution, so I propose to just disable `optimize_injective_functions_in_group_by` optimization when `group_by_use_nulls=1`. Any other ideas? @novikd @KochetovNicolai

**Comment by Avogar** [comment]
Ok, if no objections, I will disable `optimize_injective_functions_in_group_by` optimization when `group_by_use_nulls=1`

**Review by yakov-olkhovskiy — APPROVED** [review]

**Comment by tavplubix** [comment]
AST fuzzer (tsan) - https://github.com/ClickHouse/ClickHouse/pull/59986#issuecomment-2015357273
ClickHouse special build check - riscv build was broken in master

**Related failures:**
AST fuzzer (ubsan) - https://github.com/ClickHouse/ClickHouse/issues/61783, but it looks suspicious
Stateless tests (aarch64) - the new test `03014_group_by_use_nulls_injective_functions_and_analyzer` is flaky

**Comment by Avogar** [comment]
And fuzzer finds more and more bugs in analyzer + `group_by_use_nulls`, maybe something is complitely broken in the logic:
```
avogar-dev :) SELECT number, tuple(tuple(number)) FROM numbers(10) GROUP BY number, tuple(tuple(number)) WITH ROLLUP settings allow_experimental_analyzer=1, group_by_use_nulls=1

<Fatal> : Logical error: 'Bad cast from type DB::ColumnVector<unsigned long> to DB::ColumnNullable'.
```

**Comment by Avogar** [comment]
And one more:
```
avogar-dev :) SELECT ignore(toLowCardinality(number)) FROM numbers(10) GROUP BY GROUPING SETS ((ignore(toLowCardinality(number)), toLowCardinality(number)))

<Fatal> : Logical error: 'Unexpected return type from ignore. Expected Nullable. Got UInt8'.
```

This one is caused by optimization `optimize_group_by_function_keys`

**Comment by Avogar** [comment]
Remaining fuzzer failures should be fixed in https://github.com/ClickHouse/ClickHouse/pull/61933

**Pull request merged**
