### PR TITLE
Fix send_logs_level for clickhouse local

### LINKED ISSUE #35653: send_logs_level don't work in clickhouse-local
```
clickhouse-local --send_logs_level=trace
ClickHouse local version 22.3.2.1.

2758013ff22e :) select 1;

SELECT 1

Query id: 9dd074e3-a6e7-45aa-824e-803a8afd475e

┌─1─┐
│ 1 │
└───┘

1 rows in set. Elapsed: 0.002 sec. 
```

### PR DESCRIPTION
**Pull request by kssenii**
Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix send_logs_level for clickhouse local. Closes https://github.com/ClickHouse/ClickHouse/issues/35653.

### CODE REVIEW

**Comment by CurtizJ** [comment]
Maybe support `send_logs_level` with `SET` query if it's possible?

**Comment by kssenii** [comment]
It is possible but it will require to substitute logger initialisation with NullChannel by default to not-NullChannel and set log level to  none, then setting log level via query will work. But I am not sure that it will be better, what do you think?

**Comment by CurtizJ** [comment]
Maybe reinitialise loggers when we receive `SET send_logs_level ` query and throw an exception if `server_logs_file` is set?

**Review by CurtizJ — APPROVED** [review]

**Comment by CurtizJ** [comment]
Stress test `Backward compatibility check: Fatal message in clickhouse-server.log` is not related to changes.

**Pull request merged**
