### PR TITLE
Revert prefixes s3 + add retries on write requests unexpected errors

### PR DESCRIPTION
**Pull request by alesapin**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
@kssenii `test_hive_query` has failed.

**Comment by alexey-milovidov** [comment]
#41450

**Comment by alesapin** [comment]
Looks like works?

**Comment by alesapin** [comment]
` Stateless tests (release, s3 storage) — fail: 0, passed: 4416, skipped: 61 ` Ok, let's merge

**Pull request merged**
