### PR TITLE
performance test for lowcardinality array

### PR DESCRIPTION
**Pull request by filimonov**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

For changelog. Remove if this is non-significant change.

Category (leave one):
- Build/Testing/Packaging Improvement

Short description (up to few sentences):
performance test for lowcardinality array

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
@Akazz to check "some queries hung" in functional tests (unrelated).

**Comment by Akazz** [comment]
> @Akazz to check "some queries hung" in functional tests (unrelated).

Thanks for reporting this "hung query" check failure! It is safe to say that it has nothing to do with current PR. As for the failed check, I was able to reproduce such stalls in testing environment and I am currently working on it.

**Review by Akazz — APPROVED** [review]
> @Akazz to check "some queries hung" in functional tests (unrelated).

Thanks for reporting this "hung query" check failure! It is safe to say that it has nothing to do with current PR. As for the failed check, I was able to reproduce such stalls in testing environment and I am currently working on it.

**Review by dimarub2000 — COMMENTED** [review]
Seems fine.

**Pull request merged**
