### PR TITLE
Revert "Merge pull request #53673 from arenadata/ADQM-1105"

### PR DESCRIPTION
**Pull request by Algunenano**
This reverts commit 1eff7bee5e76e2575d57a8c47f176bea6e01e516, reversing changes made to cbbb81f5ccf94e7549fd5608f9c157adc63a8dbd.

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
...

This PR broke interserver communication when using an old client and old server + new server. See https://github.com/ClickHouse/ClickHouse/pull/53673#issuecomment-1695323687 for examples

Requesting a revert until that is fixed, as it complicates any kind of upgrade process.

### CODE REVIEW

**Comment by robot-ch-test-poll1** [comment]
This is an automated comment for commit 24476480b3ab46e9d62fd0c2f03e375c1927433d with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/53869/24476480b3ab46e9d62fd0c2f03e375c1927433d/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Review by nikitamikhaylov — APPROVED** [review]

**Comment by Demilivor** [comment]
I think it would be better to make a backward compatibility fix instead of reverting these changes.

These changes contain not just client_info validation but also fixes for different client_info data sent from clickhouse-client, tests, and clickhouse-benchmark.

I'm able to do a backward compatibility fix tomorrow (add a new configuration parameter allowing disable client_info validation (see https://github.com/ClickHouse/ClickHouse/pull/53673#issuecomment-1695407017 and discussion below).

**Comment by nikitamikhaylov** [comment]
@Demilivor Okay, let's wait for tomorrow.

**Comment by Demilivor** [comment]
@nikitamikhaylov @Algunenano Created PR with optional validation in https://github.com/ClickHouse/ClickHouse/pull/53673

**Comment by Algunenano** [comment]
Closing in favor of https://github.com/ClickHouse/ClickHouse/pull/53907

**Pull request closed without merging**
