### PR TITLE
Add CI check for darwin-aarch64

### PR DESCRIPTION
**Pull request by abyss7**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Build/Testing/Packaging Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Add CI check for darwin-aarch64 cross-compilation

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]

**Comment by filimonov** [comment]
After that will be merged - can you also try to enable the things disabled by default on Darwin (like mysql)?

**Comment by abyss7** [comment]
> After that will be merged - can you also try to enable the things disabled by default on Darwin (like mysql)?

I will give it a try. Do you have any meaningful way to test it?

**Comment by filimonov** [comment]
> > After that will be merged - can you also try to enable the things disabled by default on Darwin (like mysql)?
> 
> I will give it a try. 

I think it should be quite straight forward. If i'm wrong - don't waste too much time on that. 


> Do you have any meaningful way to test it?

Successful compilation with mysql enabled is already a good start. Manual test with `select * from mysql(...)` table function to some mysql server is ok. 

Creating a test especially for that may be a bit painful - setting up full test env on Darwin is out of scope, roundtrip clickhouse 2 clickhouse via mysql protocol depends on information_schema task - see #9760 and #9769

**Comment by abyss7** [comment]
@kitaisreal tested on his Mac M1

**Pull request merged**
