### PR TITLE
Cherry pick #42791 to 22.3: Fix incorrect UserTimeMicroseconds/SystemTimeMicroseconds accounting

### PR DESCRIPTION
**Pull request by robot-clickhouse-ci-2**
Original pull-request #42791

This pull-request is a first step of an automated     backporting.
It contains changes like after calling a local command `git cherry-pick`.
If you intend to continue backporting this changes, then resolve all conflicts if any.
Otherwise, if you do not want to backport them, then just close this pull-request.

The check results does not matter at this step - you can safely ignore them.
Also this pull-request will be merged automatically as it reaches the mergeable state,     but you always can merge it manually.

### CODE REVIEW

**Comment by Felixoid** [comment]
@alexey-milovidov and @azat please, take a look

**Comment by azat** [comment]
@Felixoid You are talking about test failures?

**Comment by azat** [comment]
Actually AFAIK this is just a cherrypick, and running tests on it does not makes a lot of sense, and it even marked as `do not test` (but apparently something is wrong).

**Comment by Felixoid** [comment]
I mean conflict particularly

**Comment by azat** [comment]
>I mean conflict particularly

Oh, now I see it, but I cannot solve them within this PR.
And submitting cherry picks/backports manually AFAIR is not possible (remember? we tried before)

**Comment by Felixoid** [comment]
If you'd say where I can take a merge-commit with solved conflict, I'd push it here

**Comment by azat** [comment]
@Felixoid you can find it here https://github.com/azat/ClickHouse/pull/new/backports/42791-to-22.3-merge

Or git URL - `https://github.com/azat/ClickHouse backports/42791-to-22.3-merge`

**Pull request merged**
