### PR TITLE
Fix table aliases in MATERIALIZED VIEWS error

### PR DESCRIPTION
**Pull request by songenjie**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

https://github.com/ClickHouse/ClickHouse/issues/10894
https://github.com/ClickHouse/ClickHouse/issues/11000

### CODE REVIEW

**Comment by vdimir** [comment]
Do you mind add some cases from linked issues to tests?

**Comment by songenjie** [comment]
> Do you mind add some cases from linked issues to tests?

I don't mind

**Comment by songenjie** [comment]
@vdimir  PTAL, the Stress test was `show databases` error, Functional stateless tests is TIMOUT error,  which has nothing to do with this mr

**Comment by alexey-milovidov** [comment]
@mergifyio update

**Comment by alexey-milovidov** [comment]
Test showed the issue with the changes in this PR:

```
../src/Interpreters/AddDefaultDatabaseVisitor.h:110:27: runtime error: member access within address 0x7f6695e0eec8 which does not point to an object of type 'DB::ASTWithAlias' Received signal -3 Received signal Unknown signal (-3)
```

**Comment by songenjie** [comment]
> Test showed the issue with the changes in this PR:
> 
> `../src/Interpreters/AddDefaultDatabaseVisitor.h:110:27: runtime error: member access within address 0x7f6695e0eec8 which does not point to an object of type 'DB::ASTWithAlias' Received signal -3 Received signal Unknown signal (-3)`

3ks, done

**Comment by alexey-milovidov** [comment]
There are still issues with memory safety.

**Comment by alexey-milovidov** [comment]
@songenjie This change looks very simple, but it does not work. The reason (as I understand) is that if you change aliases, they may clash with other columns with different types. Then all the trouble happens.

Do you mind if this PR will be closed? Let's try to implement it in some different way...

**Pull request closed without merging**
