### PR TITLE
Only log to stdout in containers

### PR DESCRIPTION
**Pull request by cjw296**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Docker containers are now configured to log to `stdout` by default.

### CODE REVIEW

**Comment by cjw296** [comment]
Closes https://github.com/ClickHouse/ClickHouse/issues/48448

**Comment by filimonov** [comment]
BTW: i would love to have a env variable to enable logging to strout. Maybe you can add the change into entrypoint - smth similar to https://github.com/ClickHouse/ClickHouse/blob/27756b5971b979561ed3d19ca9f3f842b4f80cb6/docker/server/entrypoint.sh#L83

**Review by filimonov — CHANGES_REQUESTED** [review]
BTW: i would love to have a env variable to enable logging to stdout. Maybe you can add the change into entrypoint - smth similar to https://github.com/ClickHouse/ClickHouse/blob/27756b5971b979561ed3d19ca9f3f842b4f80cb6/docker/server/entrypoint.sh#L83

**Comment by cjw296** [comment]
I have no hesitation about changing logging to go to `stdout`, I'm not sure what gave that impression?

It's standard practice for containers to log to stdout, and it would be better if the Clickhouse image followed this default.
See the equivalents here:

- https://hub.docker.com/_/mariadb
- https://hub.docker.com/_/postgres

I don't think the logging volume is an issue, but how would we change the logging config xml to only log an info and above?

I don't have a lot of time to give to this, but it's weird to have to volume mount a config to get behaviour that is provided by other similar container images and is pretty much standard (12 factor, etc)

**Comment by filimonov** [comment]
Bad wording on my side.

I have hesitations that your intention to change the output to stdout is so good for a very specific container - the clickhouse one, because it has 6 years history, and the logs are huge. 

And i know 12 factor apps, and know / use a lot of other containers of rdbms.

I don't disagree with fact that 'this is a good practice'. But beside that 'following good practices' there are practical aspects.

**Comment by cjw296** [comment]
It would certainly be a change, but it would bring the clickhouse container inline with the rest of the container landscape.
If the logging volume is too much, you might consider raising the default log level in the container too, maybe to info?

I suspect you'll find the majority of your users would be surprised to find there's logging happening, and that it's at a super low debug level - even writing inside the container's fs, all that debug logging does not come at zero performance cost ;-)

**Comment by cjw296** [comment]
> It does if you do it carefully :)

Then change the default container config to match that of similar container images folks will encounter,

> Actually, we had a kind of "logging levels inflation/devaluation", so the "debug" and even "trace" levels show some really useful messages, and it's highly recommended to use the "debug" or "trace" level in production env to be able to investigate some complex issues. For real debug logging we use a special "test" log level.

This reads as "we've got our logging levels wrong and don't want to fix it", which is pretty disappointing :-/

**Comment by cjw296** [comment]
> It does if you do it carefully :)

Then change the default container config to match that of similar container images folks will encounter,

> Actually, we had a kind of "logging levels inflation/devaluation", so the "debug" and even "trace" levels show some really useful messages, and it's highly recommended to use the "debug" or "trace" level in production env to be able to investigate some complex issues. For real debug logging we use a special "test" log level.

This reads as "we've got our logging levels wrong and don't want to fix it", which is pretty disappointing :-/

**Comment by tavplubix** [comment]
> This reads as "we've got our logging levels wrong and don't want to fix it", which is pretty disappointing :-/

I just tried to explain that the "debug" level does not actually mean debug logging and why. Feel free to open a Pull Request that will fix logging levels.

**Comment by Felixoid** [comment]
Hi @cjw296 

You are right, the default docker approach is logging everything to stdout. But changing the default behavior, which settled out after more than 6 years, rather looks to me like a breaking change.

As Mikhail and Alexander mentioned, the default logging level is very intensive, and by default will spoil the user's daemon.

I'd agree to have logs on some decent level in stdout in addition to `/var/log/clickhouse`, because removing them is a great change, that basically nobody expects.

**Comment by lifeofguenter** [comment]
Virtually every other system running in a docker container has not have had any issue in using STDOUT/STDERR for logging.

Just because a volume is being used, it does not solve all issues but only a single one: perceived storage issue with standard docker logging. Still needs to be shipped, rotated, managed somehow.

Furthermore this is just a "default", anyone who believes logging into a volume would still be able to do so. Similarly, the standard dockerd logging (file rotation) is neither made for production, nor really used for it anymore, in favor of much better log shippers/handlers for containers.

But being able to rely on stdout/stderr still makes things a lot easier to manage.

**Pull request closed without merging**
