### PR TITLE
Fix client `-s` argument

### PR DESCRIPTION
**Pull request by Felixoid**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix `clickhouse-client -s` argument, it was broken by defining it two times.

### CODE REVIEW

**Comment by robot-clickhouse-ci-2** [comment]
*This is an automated comment for commit 94ca5278bbe31c5684fffeda5a09c41bc2c3b1b4 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/61530/94ca5278bbe31c5684fffeda5a09c41bc2c3b1b4/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

**Review by antaljanosbenjamin — APPROVED** [review]
The changes looks good, I only have two small comments:
1. Can we add a test with `-no-secure` also? If it requires additional changes apart from adding a single line to a stateless test, then it might not worth it.
2. The changelog item I think could be improved to let the users know what the fix about without opening a PR.

**Comment by Felixoid** [comment]
The best I can think of is to add `$CLICKHOUSE_CLIENT --no-secure -q "SELECT 0;"` in the beginning. Would it work? Because more complex logic is far behind a simple fix.

**Comment by antaljanosbenjamin** [comment]
> The best I can think of is to add $CLICKHOUSE_CLIENT --no-secure -q "SELECT 0;" in the beginning. Would it work? Because more complex logic is far behind a simple fix.

I was thinking about the same line. Let's try. I think it should succeed, but I can be wrong.

**Comment by Felixoid** [comment]
A link for the reference https://github.com/ClickHouse/ClickHouse/pull/59075

**Comment by Felixoid** [comment]
sadly, fast tests are built w/o netSSL

**Comment by Felixoid** [comment]
Yaaaaaay!

` 2024-03-19 13:20:28 00505_secure:                                                           [ OK ] 0.53 sec.`
https://github.com/ClickHouse/ClickHouse/actions/runs/8341963627/job/22831139617?pr=61530#step:8:9113

**Comment by Felixoid** [comment]
Pushed again to see if the bugfix check is fixed in #61607

**Pull request merged**
