### PR TITLE
Fix bug on mutations with subcolumns of type JSON in predicates of UPDATE and DELETE queries.

### LINKED ISSUE #40990: Delete rows bug for JSON column type
clickhouse version 22.8
doesn't delete row from table using alter table delete command

create table query:
```
CREATE TABLE logs
(
    datetime DEFAULT now() Codec(DoubleDelta, LZ4),
    message JSON
)
ENGINE = MergeTree
order by datetime;
```

insert query:
```
INSERT INTO logs(message) VALUES ('{"a": 2, "b": { "c": 22, "d": [12, 122, 13] }, "f": "a"}');
```

delete query:
```
alter table logs delete where message.f = 'a';
```

error from select * from system.mutations;
```
Code: 47. DB::Exception: Missing columns: 'message.f' while processing query: 'SELECT count() WHERE (message.f = 'a') OR (message.f = 'a')', required columns: 'message.f', maybe you meant: ['message']. (UNKNOWN_IDENTIFIER) (version 22.3.8.40.altinitystable (altinity build))
```

### PR DESCRIPTION
**Pull request by VanDarkholme7**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Allow to use JSON subcolumns in predicates of UPDATE and DELETE queries.

TODO: This won't work when there are missing subcolumns in different shards.

Fixes https://github.com/ClickHouse/ClickHouse/issues/40990.

For some reasons I resubmitted this pull request, it's the same to https://github.com/ClickHouse/ClickHouse/pull/53442

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by robot-ch-test-poll4** [comment]
This is an automated comment for commit 2638cc69d76e824e549c9dc0a008e104d316e95c with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/53677/2638cc69d76e824e549c9dc0a008e104d316e95c/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Comment by VanDarkholme7** [comment]
Currently if we SELECT or DELETE with some missing JSON subcolumns, it will throw an exception.

create and insert query:
`CREATE TABLE test ( a UInt64, b JSON) ENGINE=MergeTree ORDER BY a; `
`INSERT INTO test VALUES (1, '{"a":"aa"}');`
`INSERT INTO test VALUES (2, '{"b":"bb"}');`

delete query:
`ALTER TABLE test DELETE WHERE b.c='cc';` 

it throws an exception:
`Code: 47. DB::Exception: Received from localhost:9000. DB::Exception: Missing columns: 'b.c' while processing query: 'isZeroOrNull(b.c = 'cc'), b, a', required columns: 'b.c' 'b' 'a', maybe you meant: 'b' or 'a'. (UNKNOWN_IDENTIFIER)`

Since JSON type is schema free, should it ignore the missing subcolumns instead of throrwing an exception?

@CurtizJ

**Review by CurtizJ — APPROVED** [review]
I did a [failed attempt](https://github.com/ClickHouse/ClickHouse/pull/41116) to do the same thing, but looks like it works now.

**Comment by VanDarkholme7** [comment]
I tested the failing integration tests locally, but they all passed, so I think it's irrelevant. Could you please take a look? @CurtizJ

**Comment by CurtizJ** [comment]
Yes, failed tests are not related.

**Comment by tavplubix** [comment]
> Yes, failed tests are not related.

@CurtizJ, I'm pretty sure they are, this PR breaks `00992_system_parts_race_condition_zookeeper_long` and `00002_log_and_exception_messages_formatting`. Let's revert and check if it helps (I'm pretty sure it will)

**Pull request merged**
