### PR TITLE
Fix crash for uploading parts which size is greater then INT_MAX to S3

### LINKED ISSUE #47679: SIGSEGV while uploading to S3 for part > INT_MAX
Reproducer:

```sql
INSERT INTO FUNCTION s3('https://test.s3.us-east-1.amazonaws.com/clickhouse/test.csv', '', '', 'TSV')
SETTINGS s3_truncate_on_insert = 1, s3_max_single_part_upload_size = '10Gi'
SELECT repeat('a', 1024)
FROM numbers((pow(2, 30) * 5) / 1024)
SETTINGS s3_truncate_on_insert = 1, s3_max_single_part_upload_size = '10Gi'
```

Note, that usually it is not a problem since multi part upload is used, but when you turn it OFF you can see the problem.

And the problem is the `stringstream::gcount` breaks `stringstream` when it holds more the `INT_MAX`

Here is a patch in llvm-project - https://reviews.llvm.org/D146294

### PR DESCRIPTION
**Pull request by azat**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in official stable or prestable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix crash for uploading parts which size is greater then INT_MAX to S3

The problem was that `std::stringstream` from libc++ crashes when you have > INT_MAX bytes there (after calling `gcount()`).

Refs: https://github.com/ClickHouse/llvm-project/pull/9
Refs: https://github.com/ClickHouse/llvm-project/pull/16
Fixes: #47679
Reverts: #48816
Cc: @rschu1ze

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
@azat a submodule is updated by mistake.

**Comment by alexey-milovidov** [comment]
stringstream, as well as iostreams - are not allowed in the ClickHouse source code.

**Comment by alexey-milovidov** [comment]
Parts should be uploaded in a streaming fashion without extra buffering or copying.

**Comment by azat** [comment]
> a submodule is updated by mistake.

It was done by intention, since submodule update contain a fix for the `std::stringstream` - https://github.com/ClickHouse/llvm-project/pull/9 (but as comment in the header of the PR states it also contains few unrelated changes because HEAD was not pointed correctly before https://github.com/ClickHouse/llvm-project/pull/10)

 >stringstream, as well as iostreams - are not allowed in the ClickHouse source code.

I'm not the fan of them either, but aws-cpp-sdk accepts them.

>Parts should be uploaded in a streaming fashion without extra buffering or copying.

By default they "do" (as you can see the test sets `s3_max_single_part_upload_size` to disable this).

But recently I've played with R2 storage, and it does not work nicely with multi-part upload, I've tried to upload everything in one part and server crashed, and after some digging I found this bug in the libc++ implementation of `std::stringstream` when there is more then INT_MAX bytes.

Also default size of `s3_max_upload_part_size` is 5GiB, which can crash the server with default settings. And frankly speaking this does not looks like a sane default.

**Comment by alexey-milovidov** [comment]
Changes to the LLVM submodule are merged, let's update and merge this PR.

**Comment by azat** [comment]
>[Integration tests (asan) [3/6] — fail: 1, passed: 231, flaky: 0](https://s3.amazonaws.com/clickhouse-test-reports/47693/fff6062c7b36eb9abd42746fb22b9282461898e5/integration_tests__asan__[3/6].html)

- `test_backup_restore_on_cluster/test_disallow_concurrency.py::test_concurrent_restores_on_same_node` - is flaky

**Pull request merged**
