### PR TITLE
fix constant condition conflict with column name and add stateless test

### PR DESCRIPTION
**Pull request by liuneng1994**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix exception which may happen when `SELECT` has constant `WHERE` condition and source table has columns which names are digits.

### CODE REVIEW

**Comment by liuneng1994** [comment]
Root cause is that KeyCondition::getBlockWithConstants in MergeTreeWhereOptimizer will change ASTLiteral::unique_column_name, but source columns is not available.

**Review by KochetovNicolai — APPROVED** [review]
LGTM

**Comment by den-crane** [comment]
Not a bug . You should use ` or " for database objects with names started with digit.

```
SELECT *
FROM ttt01778
WHERE `1` = toString(`2`)

Query id: aa37a978-75e4-4931-a58b-40cbca197e6a

┌─1─┬─2─┐
│ 1 │ 1 │
│ 2 │ 2 │
│ 3 │ 3 │
└───┴───┘

```

**Comment by KochetovNicolai** [comment]
@den-crane that's true, but query
`select * from ttt01778 where 1=2;`
still correct and should not throw an exception.

**Comment by den-crane** [comment]
OK. I misunderstood the issue,

I checked with testing 21.4.1.6364

```
SELECT *
FROM ttt01778
WHERE 1 = 2

Ok.

0 rows in set
```

**Comment by liuneng1994** [comment]
@den-crane I see some integration test failed. Is it because of my code?  Thanks.

**Comment by KochetovNicolai** [comment]
Before changes it got error for me:
```
SELECT *
FROM ttt01778
WHERE 1 = 2

Query id: e3b14641-ae1e-4762-bf80-226ffabc7aef


0 rows in set. Elapsed: 0.133 sec. 

Received exception from server (version 21.4.1):
Code: 386. DB::Exception: Received from localhost:9000. DB::Exception: There is no supertype for types String, Int32 because some of them are String/FixedString and some of them are not: while executing 'FUNCTION equals(1 : 0, 2 : 1) -> equals(1, 2) UInt8 : 2'. 
```

**Pull request merged**
