### PR TITLE
Fix number of dropped granules in EXPLAIN PLAN index=1

### LINKED ISSUE #52107: why set type index should invalid，but the explain shows Selected Granules is less than Initial Granules
i have a big data table, there is a column with non-repetitive datas. there is a set type index on this column. the max_rows was set 100.( index_granularity = 8192, and GRANULARITY of the index is 16. so i think the row number is 131072, is bigger than max_rows which be set as 100,  so as the official document said, this index should be invalid )
but where i execute explain indexes = 1, it show, after using this index ,Selected Granules is less than Initial Granules, it shows the index is valid, so im confused about this.

the explain info of this index :
                                          "Type": "Skip",
                                          "Name": "a",
                                          "Description": "set GRANULARITY 16",
                                          "Initial Parts": 8,
                                          "Selected Parts": 8,
                                          "Initial Granules": 41323,
                                          "Selected Granules": 3201

### LINKED ISSUE #52637: Skip indexes and functions and dropped granules
-- granularity 100
```sql
ClickHouse local version 23.6.2.18 (official build).

create table test (K Int64,  A Int64, B Int64, C Int64, 
index x1 (greatest(A,B,C)) type minmax granularity 100) 
Engine=MergeTree order by K as select number,0,0,0 from numbers(1e7);

select count() from test where greatest(A,B,C) >0;

Index `x1` has dropped 15/1221 granules.


select count() from test where greatest(A,B,C)!=0;

Index `x1` has dropped 15/1221 granules.
```

why only 15 granules is dropped?

-- granularity 1
```sql
create table test (K Int64,  A Int64, B Int64, C Int64, 
index x1 (greatest(A,B,C)) type minmax granularity 1) 
Engine=MergeTree order by K as select number,0,0,0 from numbers(1e7);

select count() from test where greatest(A,B,C) >0;
Index `x1` has dropped 1221/1221 granules.
```

it seems it's a statistics/show issue.

```sql
create table test (K Int64,  A Int64, B Int64, C Int64, 
index x1 (A>0,B>0,C>0) type set(2) granularity 1000) 
Engine=MergeTree order by K as select number,0,0,0 from numbers(1e8);

select count() from test where A>0 and B>0 and C>0;

Index `x1` has dropped 14/12209 granules.
Selected 5/5 parts by partition key, 0 parts by primary key, 12209/12209 marks by primary key, 0 marks to read from 0 ranges
```

### PR DESCRIPTION
**Pull request by wzb5212**
Fixes #52107
Fixes #52637

```
CREATE TABLE test_skip_idx
(
    `id` UInt32,
    INDEX name_idx_g2 id TYPE minmax GRANULARITY 2,
    INDEX name_idx_g1 id TYPE minmax GRANULARITY 1
)
ENGINE = MergeTree
ORDER BY tuple()
SETTINGS index_granularity = 1, index_granularity_bytes = 0;

INSERT INTO test_skip_idx SELECT number FROM system.numbers LIMIT 5 OFFSET 1;

EXPLAIN indexes = 1 SELECT * FROM test_skip_idx WHERE id < 2;
┌─explain───────────────────────────────────────┐
│ Expression ((Projection + Before ORDER BY))   │
│   Filter (WHERE)                              │
│     ReadFromMergeTree (default.test_skip_idx) │
│     Indexes:                                  │
│       Skip                                    │
│         Name: name_idx_g2                     │
│         Description: minmax GRANULARITY 2     │
│         Parts: 1/1                            │
│         Granules: 3/5                         │
│       Skip                                    │
│         Name: name_idx_g1                     │
│         Description: minmax GRANULARITY 1     │
│         Parts: 1/1                            │
│         Granules: 1/3                         │
└───────────────────────────────────────────────┘

EXPLAIN indexes = 1 SELECT * FROM test_skip_idx WHERE id < 3;
┌─explain───────────────────────────────────────┐
│ Expression ((Projection + Before ORDER BY))   │
│   Filter (WHERE)                              │
│     ReadFromMergeTree (default.test_skip_idx) │
│     Indexes:                                  │
│       Skip                                    │
│         Name: name_idx_g2                     │
│         Description: minmax GRANULARITY 2     │
│         Parts: 1/1                            │
│         Granules: 3/5                         │
│       Skip                                    │
│         Name: name_idx_g1                     │
│         Description: minmax GRANULARITY 1     │
│         Parts: 1/1                            │
│         Granules: 2/3                         │
└───────────────────────────────────────────────┘


## expected behavior

EXPLAIN indexes = 1 SELECT * FROM test_skip_idx WHERE id < 2;
┌─explain───────────────────────────────────────┐
│ Expression ((Projection + Before ORDER BY))   │
│   Filter (WHERE)                              │
│     ReadFromMergeTree (default.test_skip_idx) │
│     Indexes:                                  │
│       Skip                                    │
│         Name: name_idx_g2                     │
│         Description: minmax GRANULARITY 2     │
│         Parts: 1/1                            │
│         Granules: 2/5                         │
│       Skip                                    │
│         Name: name_idx_g1                     │
│         Description: minmax GRANULARITY 1     │
│         Parts: 1/1                            │
│         Granules: 1/2                         │
└───────────────────────────────────────────────┘

EXPLAIN indexes = 1 SELECT * FROM test_skip_idx WHERE id < 3;
┌─explain───────────────────────────────────────┐
│ Expression ((Projection + Before ORDER BY))   │
│   Filter (WHERE)                              │
│     ReadFromMergeTree (default.test_skip_idx) │
│     Indexes:                                  │
│       Skip                                    │
│         Name: name_idx_g2                     │
│         Description: minmax GRANULARITY 2     │
│         Parts: 1/1                            │
│         Granules: 2/5                         │
│       Skip                                    │
│         Name: name_idx_g1                     │
│         Description: minmax GRANULARITY 1     │
│         Parts: 1/1                            │
│         Granules: 2/2                         │
└───────────────────────────────────────────────┘

```

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fixed a bug in EXPLAIN PLAN index=1 where the number of dropped granules was incorrect

### CODE REVIEW

**Comment by robot-ch-test-poll1** [comment]
This is an automated comment for commit 8bb0f1801970687a02bc2a6c4a4d28947b2db444 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/53616/8bb0f1801970687a02bc2a6c4a4d28947b2db444/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Comment by alexey-milovidov** [comment]
@wzb5212 why closed?

**Comment by wzb5212** [comment]
> @wzb5212 why closed?

Just a moment, let me check the code.

**Comment by wzb5212** [comment]
@alexey-milovidov please take a look.

**Pull request merged**
