### PR TITLE
Build with lld for gcc in CI images.

### PR DESCRIPTION
**Pull request by alesapin**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Build/Testing/Packaging Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Now we link ClickHouse in CI using `lld` even for `gcc`.

### CODE REVIEW

**Comment by alesapin** [comment]
gcc looks for linker:
```
[pid 13608] stat("/usr/lib/gcc/x86_64-linux-gnu/9/real-ld", 0x7ffef6e21300) = -1 ENOENT (No such file or directory)                                                                                                                             
[pid 13608] stat("/usr/lib/gcc/x86_64-linux-gnu/9/real-ld", 0x7ffef6e21300) = -1 ENOENT (No such file or directory)                                                                                                                             
[pid 13608] stat("/usr/lib/gcc/x86_64-linux-gnu/real-ld", 0x7ffef6e21300) = -1 ENOENT (No such file or directory)                                                                                                                               
[pid 13608] stat("/usr/lib/gcc/x86_64-linux-gnu/9/real-ld", 0x7ffef6e21300) = -1 ENOENT (No such file or directory)                                                                                                                             
[pid 13608] stat("/usr/lib/gcc/x86_64-linux-gnu/real-ld", 0x7ffef6e21300) = -1 ENOENT (No such file or directory)                                                                                                                               [pid 13608] stat("/usr/lib/gcc/x86_64-linux-gnu/9/collect-ld", 0x7ffef6e21300) = -1 ENOENT (No such file or directory)                                                                                                                          
[pid 13608] stat("/usr/lib/gcc/x86_64-linux-gnu/9/collect-ld", 0x7ffef6e21300) = -1 ENOENT (No such file or directory)                                                                                                                          
[pid 13608] stat("/usr/lib/gcc/x86_64-linux-gnu/collect-ld", 0x7ffef6e21300) = -1 ENOENT (No such file or directory)                                                                                                                            [pid 13608] stat("/usr/lib/gcc/x86_64-linux-gnu/9/collect-ld", 0x7ffef6e21300) = -1 ENOENT (No such file or directory)                                                                                                                          [pid 13608] stat("/usr/lib/gcc/x86_64-linux-gnu/collect-ld", 0x7ffef6e21300) = -1 ENOENT (No such file or directory)                                                                                                                            [pid 13608] stat("/usr/lib/gcc/x86_64-linux-gnu/9/ld.lld", 0x7ffef6e21300) = -1 ENOENT (No such file or directory)                                                                                                                              [pid 13608] stat("/usr/lib/gcc/x86_64-linux-gnu/9/ld.lld", 0x7ffef6e21300) = -1 ENOENT (No such file or directory)                                                                                                                              [pid 13608] stat("/usr/lib/gcc/x86_64-linux-gnu/ld.lld", 0x7ffef6e21300) = -1 ENOENT (No such file or directory)                                                                                                                                
[pid 13608] stat("/usr/lib/gcc/x86_64-linux-gnu/9/ld.lld", 0x7ffef6e21300) = -1 ENOENT (No such file or directory)                                                                                                                              
[pid 13608] stat("/usr/lib/gcc/x86_64-linux-gnu/ld.lld", 0x7ffef6e21300) = -1 ENOENT (No such file or directory)                                                                                                                                
[pid 13608] stat("/home/alesap/yandex-cloud/bin/ld.lld", 0x7ffef6e21300) = -1 ENOENT (No such file or directory)                                                                                                                                
[pid 13608] stat("/usr/local/sbin/ld.lld", 0x7ffef6e21300) = -1 ENOENT (No such file or directory)
[pid 13608] stat("/usr/local/bin/ld.lld", 0x7ffef6e21300) = -1 ENOENT (No such file or directory)                                                                                                                                               
[pid 13608] stat("/usr/sbin/ld.lld", 0x7ffef6e21300) = -1 ENOENT (No such file or directory)                                                                                                                                                    
[pid 13608] stat("/usr/bin/ld.lld", 0x7ffef6e21300) = -1 ENOENT (No such file or directory)                                                                                                                                                     
[pid 13608] stat("/sbin/ld.lld", 0x7ffef6e21300) = -1 ENOENT (No such file or directory)                                                                                                                                                        
[pid 13608] stat("/bin/ld.lld", 0x7ffef6e21300) = -1 ENOENT (No such file or directory)                                                                                                                                                         
[pid 13608] stat("/usr/games/ld.lld", 0x7ffef6e21300) = -1 ENOENT (No such file or directory)                                                                                                                                                   
[pid 13608] stat("/usr/local/games/ld.lld", 0x7ffef6e21300) = -1 ENOENT (No such file or directory)
```

**Comment by alesapin** [comment]
Will perform experiments after release.

**Comment by alexey-milovidov** [comment]
@alesapin Suddenly, all the tests have passed.

**Comment by alexey-milovidov** [comment]
The issue may be related to the wrong code of #8765  (it contains data race).

**Comment by alexey-milovidov** [comment]
Should continue after #9472

**Pull request merged**
