### PR TITLE
Upgrade integration-runner image

### PR DESCRIPTION
**Pull request by Felixoid**
### Changelog category (leave one):
- CI Fix or Improvement (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
- Improve pipdeptree generator for docker images.
- Update requirements.txt for the integration tests runner container
- Remove some small dependencies, improve `helpers/retry_decorator.py`
- Upgrade docker-compose from EOL version 1 to version 2

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Run only fuzzers related jobs (libFuzzer fuzzers, AST fuzzers, etc.)
- [ ]  Exclude: AST fuzzers
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by qoega** [comment]
Looks fine. Waiting for integration tests results

**Comment by Felixoid** [comment]
I think it should be fixed now.

**Comment by qoega** [comment]
I guess you have the same issue as I here 
https://github.com/ClickHouse/ClickHouse/pull/66867

**Comment by Felixoid** [comment]
Commands like following

```
docker compose --env-file /ClickHouse/tests/integration/test_user_ip_restrictions/_instances-0-gw1/.env --project-name roottestuseriprestrictions-gw1 --file /ClickHouse/tests/integration/helpers/../../../tests/integration/compose/docker_compose_net.yml --file /ClickHouse/tests/integration/test_user_ip_restrictions/_instances-0-gw1/node_ipv4/docker-compose.yml --file /ClickHouse/tests/integration/helpers/../../../tests/integration/compose/docker_compose_net.yml --file /ClickHouse/tests/integration/test_user_ip_restrictions/_instances-0-gw1/client_ipv4_ok/docker-compose.yml --file /ClickHouse/tests/integration/helpers/../../../tests/integration/compose/docker_compose_net.yml --file /ClickHouse/tests/integration/test_user_ip_restrictions/_instances-0-gw1/client_ipv4_ok_direct/docker-compose.yml --file /ClickHouse/tests/integration/helpers/../../../tests/integration/compose/docker_compose_net.yml --file /ClickHouse/tests/integration/test_user_ip_restrictions/_instances-0-gw1/client_ipv4_ok_full_mask/docker-compose.yml --file /ClickHouse/tests/integration/helpers/../../../tests/integration/compose/docker_compose_net.yml --file /ClickHouse/tests/integration/test_user_ip_restrictions/_instances-0-gw1/client_ipv4_bad/docker-compose.yml --file /ClickHouse/tests/integration/helpers/../../../tests/integration/compose/docker_compose_net.yml --file /ClickHouse/tests/integration/test_user_ip_restrictions/_instances-0-gw1/node_ipv6/docker-compose.yml --file /ClickHouse/tests/integration/helpers/../../../tests/integration/compose/docker_compose_net.yml --file /ClickHouse/tests/integration/test_user_ip_restrictions/_instances-0-gw1/client_ipv6_ok/docker-compose.yml --file /ClickHouse/tests/integration/helpers/../../../tests/integration/compose/docker_compose_net.yml --file /ClickHouse/tests/integration/test_user_ip_restrictions/_instances-0-gw1/client_ipv6_ok_direct/docker-compose.yml --file /ClickHouse/tests/integration/helpers/../../../tests/integration/compose/docker_compose_net.yml --file /ClickHouse/tests/integration/test_user_ip_restrictions/_instances-0-gw1/client_ipv6_bad/docker-compose.yml up -d --no-recreate
```

fail, because there are more than one `--file /ClickHouse/tests/integration/helpers/../../../tests/integration/compose/docker_compose_net.yml`. A new docker-compose got the brain's cucumbers.

**Comment by Felixoid** [comment]
I'll take a closer look at failed flaky tests in the next PR, where I'll improve the integration_tests_runner.py

https://s3.amazonaws.com/clickhouse-test-reports/70146/84c81cdc3cbdd7609d73b698266b8e0308824ea2/integration_tests_flaky_check__asan_.html

Most of them are either timing out or non-idempotent. But all of them are success on the first run

**Comment by Felixoid** [comment]
I'll try to backport it in the most recent releases

**Pull request merged**
