### PR TITLE
WHERE condtions optimization leveraging projection feature

### PR DESCRIPTION
**Pull request by suzyw-w**
This is a proposal to optimize select query by leveraging projection feature.
Since PROJECTION can effectively create a new primary key for the table, it can increase the searching speed if using properly.
This implementation inserts a new subquery to the original where condition, in order to use the projection feature in more general cases.
For example, 
`select * from table where secondary_key='-42';` 
will now become 
`select * from table where primary_key in (select primary_key from test_a where secondary_key='-42') and secondary_key='-42';`
This implementation is tested and proved increasing query execution speed vastly.

Thanks to @UnamedRus 's suggestion, indexHint() is also added to further optimize the query. Now the query is going to be re-write to `select * from table where indexHint(primary_key in (select primary_key from test_a where secondary_key='-42')) and secondary_key='-42';`
It is proved that this will also optimize query execution speed. [Tests results](#Test-Result) are attached below.

## Pseudo Code ##
```
for each query (including subqueries):
   for each predicate in WHERE clause in the query:
	 1. check if it's a simple condition <column>=<value>;
	 2. check if <column> is NOT the primary key of the table;
	 3. check if <column> is the primary key of a projection that contains table primary keys;
	 4. if all condition met, rewrite the query as mentioned above and break
```

## Restrictions ##
1. Currently the re-write only works for WHERE condition with no subquery. (e.x Select * Where src in (<subquery>) will not be optimized).
2. The re-write only support WHERE condition that is using `=` function.
3. The re-write can work with Alias but not function wrapping around columns. 
For example, 
```
SELECT
      user_account AS my_user,
      user_id
FROM events
WHERE my_user = 'admin'
```
can be re-written to 
```
SELECT                                                     
     user_account AS my_user,                    
     user_id
 FROM events                                                                          
 WHERE (my_user = 'admin') AND indexHint( primary_key IN (
     SELECT primary_key 
     FROM events                                           
     WHERE (user_account AS my_user) = 'admin'
 )) 
```
However, query like the following will not be recognized, and will not be re-written. 
```
SELECT
      If(user_id = 0, NULL, user_account) AS user_id AS my_user,
      user_id
FROM events
WHERE my_user = 'admin'

```
4. Aggregation Function projection is not supported.
5. This re-written is implemented on top of projection feature, hence anything that Projection feature currently does not support will not be supported with this optimization. 

## Test result ##
<pre>
CREATE TABLE test_a
(
    `src` String,
    `dst` String,
    `other_cols` String,
    PROJECTION p1
    (
        SELECT
            src,
            dst
        ORDER BY dst
    )
)
ENGINE = MergeTree
ORDER BY src
</pre>

/* Query using primary key (fastest) */
<pre>
palmtops1.fyre.ibm.com :) select * from test_a where src='42';

SELECT *
FROM test_a
WHERE src = '42'

Query id: 9220dadb-bdbc-4fe5-bf70-b4c04b3e7ddd

┌─src─┬─dst─┬─other_cols───┐
│ 42  │ -42 │ other_col 42 │
└─────┴─────┴──────────────┘

1 row in set. Elapsed: <b>0.042 sec</b>. Processed 16.38 thousand rows, 619.85 KB (388.58 thousand rows/s., 14.70 MB/s.)
Peak memory usage: 44.66 KiB.
</pre>

/* Query does not using projection */
<pre>
palmtops1.fyre.ibm.com :) select * from test_a where dst='-42';

SELECT *
FROM test_a
WHERE dst = '-42'

Query id: 7835b759-e894-4e34-b51b-f54fe3d1645c

┌─src─┬─dst─┬─other_cols───┐
│ 42  │ -42 │ other_col 42 │
└─────┴─────┴──────────────┘

1 row in set. Elapsed: <b>2.177 sec</b>. Processed 100.00 million rows, 1.79 GB (45.94 million rows/s., 821.86 MB/s.)
Peak memory usage: 1021.77 KiB.
</pre>

/* Optimized non-projection query now can leveraging projection feature */
<pre>
palmtops1.fyre.ibm.com :) select * from test_a where src in (select src from test_a where dst='-42') and dst='-42';

SELECT *
FROM test_a
WHERE (src IN (
    SELECT src
    FROM test_a
    WHERE dst = '-42'
)) AND (dst = '-42')

Query id: 68ca1b70-940f-41d2-983b-4df7c06df5ae

┌─src─┬─dst─┬─other_cols───┐
│ 42  │ -42 │ other_col 42 │
└─────┴─────┴──────────────┘

1 row in set. Elapsed: <b>0.101 sec</b>. Processed 32.77 thousand rows, 1.18 MB (325.38 thousand rows/s., 11.75 MB/s.)
Peak memory usage: 275.28 KiB
</pre>

/* Optimized query with indexHint */
<pre>
palmtops1.fyre.ibm.com :) select * from test_a where indexHint(src in (select src from test_a where dst='-42')) and dst='-42';

SELECT *
FROM test_a
WHERE indexHint(src IN (
    SELECT src
    FROM test_a
    WHERE dst = '-42'
)) AND (dst = '-42')

Query id: 365d4fae-93dc-48e5-b0c0-42dc2ba9904e

┌─src─┬─dst─┬─other_cols───┐
│ 42  │ -42 │ other_col 42 │
└─────┴─────┴──────────────┘

1 row in set. Elapsed: <b>0.094 sec</b>. Processed 32.77 thousand rows, 1.18 MB (350.31 thousand rows/s., 12.65 MB/s.)
Peak memory usage: 223.92 KiB.
</pre>

Query using primary key (fastest) : 0.042 sec, Peak memory usage: 44.66 KiB
Query does not using projection : 2.177 sec, Peak memory usage: 1021.77 KiB.
Optimized non-projection query : 0.101 sec, Peak memory usage: 275.28 KiB
Optimized query with indexHint : 0.094 sec, Peak memory usage: 223.92 KiB.

### Changelog category (leave one):
- Improvement

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by UnamedRus** [comment]
Should be slightly better


```
select * from table where indexHint(primary_key in (select primary_key from test_a where secondary_key='-42')) and secondary_key='-42';
```

But there is also potential problem, with case when subquery return big set of keys, index analysis in that case can be slower than reading whole table and filtering.

**Comment by robot-ch-test-poll3** [comment]
*This is an automated comment for commit f93ef84164ed9497ba4b9d8dd56087bcf8c94912 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/57216/f93ef84164ed9497ba4b9d8dd56087bcf8c94912/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td><a href="https://github.com/ClickHouse/ClickHouse/actions/runs/6984694222">✅ success</a></td></tr>
<tbody>
</table>
</details>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/57216/f93ef84164ed9497ba4b9d8dd56087bcf8c94912/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Comment by amosbird** [comment]
I also have some plan to implement secondary indices on top of normal projections. It might rely on ColumnLazy.

**Comment by SuzyWangIBMer** [comment]
TODO list:

- Recognition of a select query already using projection feature, no rewrite of such query

**Comment by UnamedRus** [comment]
Ideally, this "rewrite" should happen on level of part.

So each part, will be filtered by list of PK from it's own projection.

**Comment by SuzyWangIBMer** [comment]
> Ideally, this "rewrite" should happen on level of part.
> 
> So each part, will be filtered by list of PK from it's own projection.

This is in our consideration for the next stage.

**Comment by amosbird** [comment]
With https://github.com/ClickHouse/ClickHouse/pull/58224 you can use _part_offset instead of real PK.

**Comment by SuzyWangIBMer** [comment]
> With #58224 you can use _part_offset instead of real PK.

As my understand so far, _part_offset is hidden. How would you suggest to use _part_offset replacing real pk in this case?
```
SELECT *
FROM test_a
WHERE indexHint(_part_offset IN (
    SELECT _part_offset
    FROM test_a
    WHERE dst = '-42'
)) AND (dst = '-42')

Query id: ff98d684-c6b1-47c8-bf69-df72a5124c12


0 rows in set. Elapsed: 0.377 sec.

Received exception from server (version 24.1.1):
Code: 10. DB::Exception: Received from localhost:9000. DB::Exception: Not found column _part_offset:  in block dst String String(size = 0). (NOT_FOUND_COLUMN_IN_BLOCK)

```

**Comment by amosbird** [comment]
`test_a` should be a `*MergeTree` table.

btw, `indexHint` is not enough, so as `_part_offset` alone. The correct query should be:

```
SELECT *
FROM test_a
WHERE (_part_offset, _part) IN (
    SELECT (_part_offset, _part)
    FROM test_a
    WHERE dst = '-42'
)
```

However, currently this query is still not 100% correct, because we acquires two different StorageSnapshots. This should be easy to improve.

**Comment by UnamedRus** [comment]
But in order _part_offset to work, you need to rebuild projection after each merge, to get correct offset value.

**Comment by SuzyWangIBMer** [comment]
> `test_a` should be a `*MergeTree` table.
> 
> btw, `indexHint` is not enough, so as `_part_offset` alone. The correct query should be:
> 
> ```
> SELECT *
> FROM test_a
> WHERE (_part_offset, _part) IN (
>     SELECT (_part_offset, _part)
>     FROM test_a
>     WHERE dst = '-42'
> )
> ```
> 
> However, currently this query is still not 100% correct, because we acquire two different StorageSnapshots. This should be easy to improve.

Can you please elaborate on this?


> But in order _part_offset to work, you need to rebuild projection after each merge, to get correct offset value.

Would this actually slow down the process?

**Comment by UnamedRus** [comment]
> Would this actually slow down the process?

It could slowdown merge, but we still need to do it in that way because of Replacing/... table engines https://github.com/ClickHouse/ClickHouse/issues/24778

**Comment by SuzyWangIBMer** [comment]
> > Would this actually slow down the process?
> 
> It could slowdown merge, but we still need to do it in that way (for some engines) because of Replacing/... table engines #24778

So far we have been limited our usecase of MergeTree Enginee while using projection. Is this a known issue for CollapsingMergeTree and ReplacingMergeTree only? Meaning does MergeTree enginee has the same problem?

**Comment by UnamedRus** [comment]
> Is this a known issue for CollapsingMergeTree and ReplacingMergeTree only? 

It's known issue that currently projections are not working correctly (but, it's mostly harm aggregation projections) for ReplacingMergeTree and CollapsingMergeTree.

Fix is to recalculate projections from result of merge, instead of source projections.


For your case, if we want to use `_part_offset` column instead of PK in projection for filtering. we also need to recalculate projection in order to obtain new `_part_offset` in merged part.

**Comment by SuzyWangIBMer** [comment]
> > Is this a known issue for CollapsingMergeTree and ReplacingMergeTree only?
> 
> It's known issue that currently projections are not working correctly (but, it's mostly harm aggregation projections) for ReplacingMergeTree and CollapsingMergeTree.
> 
> Fix is to recalculate projections from result of merge, instead of source projections.
> 
> For your case, if we want to use `_part_offset` column instead of PK in projection for filtering. we also need to recalculate projection in order to obtain new `_part_offset` in merged part.

It sounds like there's still some uncertainty about `_part_offset`, I think it is the best that we open a separate pr and keep this pr simple.

**Comment by SuzyWangIBMer** [comment]
@alexey-milovidov Hi, can someone please take a look at this pr?

**Comment by SuzyWangIBMer** [comment]
@UnamedRus  @amosbird  Hi, as you guys are the expert on this, do we have any more concerns of this change?

**Comment by SuzyWangIBMer** [comment]
@alexey-milovidov @KochetovNicolai @davenger Hi, Can we please have someone review the pr?

**Comment by SuzyWangIBMer** [comment]
@UnamedRus @amosbird @alexey-milovidov @KochetovNicolai @davenger Hi, as this pr has been sitting around for a while, can we please have someone start reviewing this?

**Comment by UnamedRus** [comment]
I'm not a part of ClickHouse Inc team.

Overall Idea is good and needs to be implemented.

But, i see few concern points:

1. What if projection is not materialized for some parts.
If this subquery will be added explicitly as normal part of query, it would force "materialization" of projection for those parts on fly, basically read main table instead of "lightweight" projection. (but, it's back to a question of making such optimization on part level)

2. New ast based optimizations for old parser is debatable topic because of it's fragile nature and ongoing movement to new analyzer-based infrastructure. 
https://github.com/ClickHouse/ClickHouse/tree/b9d3ae3b0a1c62fd6d0bfa413ac2ad7a78e18849/src/Analyzer/Passes

**Comment by SuzyWangIBMer** [comment]
> I'm not a part of ClickHouse Inc team. (so I can only speak for myself)
> 
> Overall Idea is good and needs to be implemented.
> 
> But, i see few concern points:
> 
> 1. What if projection is not materialized for some parts.
>    If this subquery will be added explicitly as normal part of query, it would force "materialization" of projection for those parts on fly, basically read main table instead of "lightweight" projection. (but, it's back to a question of making such optimization on part level)
> 2. New ast based optimizations for old parser is debatable topic because of it's fragile nature and ongoing movement to new analyzer-based infrastructure.
>    https://github.com/ClickHouse/ClickHouse/tree/b9d3ae3b0a1c62fd6d0bfa413ac2ad7a78e18849/src/Analyzer/Passes

Thank you for your response. I do need some backup here to let clickhouse team start looking at this pr.

**Comment by SuzyWangIBMer** [comment]
@alexey-milovidov @KochetovNicolai @davenger Can we please have someone start review this pr?

**Comment by alexey-milovidov** [comment]
@SuzyWangIBMer This pull request didn't pass tests.

**Comment by SuzyWangIBMer** [comment]
@alexey-milovidov  Conflicts are resolved now. Current failures seems non-relevant to my change.

**Comment by SuzyWangIBMer** [comment]
Closes as new implementation moving to Analyzer/Passes is done. New PR opened #63207

**Pull request closed without merging**
