### PR TITLE
Skip object fields on json input

### LINKED ISSUE #2367: Cannot skip nested JSON field when inserting JSON data with input_format_skip_unknown_fields=1
Hello,
Following cmd fails if input JSON contains nested fields: 

`clickhouse-client --input_format_skip_unknown_fields=1 --query="INSERT INTO my_table FORMAT JSONEachRow" < my.json`

**Code: 117. DB::Exception: Unexpected nested field for key 'originalMsg'**

In my case input JSON contains fields prepared for insertion into clickhouse and  'originalMsg' filed containing 'backup data' which is valid JSON object too.

### PR DESCRIPTION
**Pull request by blahgeek**
Fixes #2367 

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
:+1:

**Comment by kmatt** [comment]
Build stable with this PR, and while it skips undefined columns from JSON messages in a Kafka table, adding a materialized view from the consumer to a shard table starts the following to be logged. Uncertain if this is from the PR, or another issue:

```
2018.09.05 15:46:10.769379 [ 21 ] <Error> void DB::StorageKafka::streamThread(): Code: 49, e.displayText() = DB::Exception: Attempt to attach to nullptr thread group, e.what() = DB::Exception, Stack trace:

0. clickhouse-server(StackTrace::StackTrace()+0x16) [0x54b10a6]
1. clickhouse-server(DB::Exception::Exception(std::string const&, int)+0x1f) [0x290fc7f]
2. clickhouse-server(DB::ThreadStatus::attachQuery(std::shared_ptr<DB::ThreadGroupStatus> const&, bool)+0x43a) [0x4e53b3a]
3. clickhouse-server(DB::CurrentThread::attachTo(std::shared_ptr<DB::ThreadGroupStatus> const&)+0x26) [0x4e53c36]
4. clickhouse-server(DB::ParallelInputsProcessor<DB::UnionBlockInputStream<(DB::StreamUnionMode)0>::Handler, (DB::StreamUnionMode)0>::thread(std::shared_ptr<DB::ThreadGroupStatus>, unsigned long)+0x5a) [0x4de0aea]
5. clickhouse-server(std::thread::_State_impl<std::thread::_Invoker<std::tuple<DB::ParallelInputsProcessor<DB::UnionBlockInputStream<(DB::StreamUnionMode)0>::Handler, (DB::StreamUnionMode)0>::process()::{lambda()#1}> > >::_M_run()+0x40) [0x4de1120]
6. clickhouse-server() [0x5dec3af]
7. /lib64/libpthread.so.0(+0x7e25) [0x7ff5057c7e25]
8. /lib64/libc.so.6(clone+0x6d) [0x7ff504fe7bad]
```

**Comment by alexey-milovidov** [comment]
It's not related to this PR.

And the branch `stable` doesn't contain any features related to `ThreadStatus`, `CurrentThread`, etc. It looks like you have built master or testing version.

**Comment by kmatt** [comment]
@alexey-milovidov Thanks. I rebuilt from a clean v18.12.3-testing without applying the PR and get the same exception.

**Comment by alexey-milovidov** [comment]
The fix https://github.com/yandex/ClickHouse/commit/5a096ee0992ce139b4982a6edbade5a5c9beca3b is from 18.12.5. I recommend to install latest testing, currently it is 18.12.11.

**Pull request merged**
