### PR TITLE
[RFC] Fix memory tracking with min_bytes_to_use_mmap_io

### PR DESCRIPTION
**Pull request by azat**
Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix memory tracking with min_bytes_to_use_mmap_io

Detailed description / Documentation draft:
With min_bytes_to_use_mmap_io=1 memory regions for mmap() will not be
accounted. But this creates issues, since if you will run simple
"SELECT * FROM big_enough_table" it will mmap lot's of files and the
process RSS will grow at some point, and before the kernel will
understand that it needs to unmap physical pages the clickhouse-server
will sync total_memory_tracker with RSS of the process and the
allocations will fail by per-server memory limits.

Also note, that this does not address all the issues with mmap()
regions.

*P.S. marked as `Improvement`, but maybe it should be marked as `Bug fix`*

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
> RSS will grow, total_memory_tracker will be synced with RSS and the allocations will start to fail.

But how does it help to add something to memory tracker?
The total memory tracker will still be corrected to higher value.

**Comment by azat** [comment]
> The total memory tracker will still be corrected to higher value.

Right, but this is not enough

> But how does it help to add something to memory tracker?

Suppose you have lots of small queries and few big queries that just read all the data from the table, in this case one of that big queries will mmap all the files and eventually RSS of the process will reach `max_server_memory_usage*max_server_memory_usage_to_ram_ratio` which will fail any allocations for other queries.

By tracking these memory in the query that particular query will fail instead of random query due to total memory limits.

Another option is not account mapped files for amount of the total memory tracker, but this may cause some other trickery I guess.

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
We suspect that performance test is broken after this PR. Could you please resubmit it?

**Comment by azat** [comment]
>We suspect that performance test is broken after this PR.

Yes.

> Could you please resubmit it?

Ok, will resubmit with perf tests adjusted.

**Pull request merged**
