### PR TITLE
Translate  docs/zh/sql-reference/data-types/map.md

### PR DESCRIPTION
**Pull request by yjant**
Translate map.md into Chinese

Changelog category (leave one):
- Documentation (changelog entry is not required)

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
...

> Information about CI checks: https://clickhouse.tech/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by kitaisreal** [comment]
@Mergifyio update

**Comment by kitaisreal** [comment]
@Mergifyio update

**Comment by kitaisreal** [comment]
@Mergifyio update

**Comment by alexey-milovidov** [comment]
@mergifyio update

**Pull request merged**
