### PR TITLE
Fix utils build on CI

### PR DESCRIPTION
**Pull request by azat**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
- Fix building keeper-data-dumper
- Remove --verbose=1 for cmake on configuration stage
- Build utils on CI when they was requested
- Fix clickhouse-su building in splitted build
- Fix clang-tidy in utils/examples

### CODE REVIEW

**Comment by pkit** [comment]
@azat good, another broken master though :)

**Comment by azat** [comment]
>Jul 28 18:45:59 /build/programs/su/clickhouse-su.cpp:1:10: fatal error: 'Common/Exception.h' file not found

@alexey-milovidov BTW `clickhouse-su` should be in the packets (bundle), right?

**Comment by alexey-milovidov** [comment]
@azat yes, it's included in the `clickhouse` binary and we use it in Docker packages.

**Comment by azat** [comment]
>ClickHouse build check — 23/23 artifact groups are OK
>ClickHouse special build check — 7/7 artifact groups are OK

Now everything is OK.

**Comment by rschu1ze** [comment]
Thanks a lot, BuilderDebSplitted and BuilderBinClangTidy now finally build "utils". --> Good to merge.

**Pull request merged**
