### PR TITLE
Enable custom parquet encoder by default, attempt 2

### PR DESCRIPTION
**Pull request by al13n321**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Unrevert https://github.com/ClickHouse/ClickHouse/pull/62088

### CODE REVIEW

**Comment by robot-clickhouse-ci-2** [comment]
*This is an automated comment for commit 2281f3cc4b6b7b043b667b92077607bcf457e080 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/63210/2281f3cc4b6b7b043b667b92077607bcf457e080/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

**Comment by alexey-milovidov** [comment]
@al13n321, it failed.

**Comment by al13n321** [comment]
Huh, the test fails because custom encoder apparently writes arrays and maps *more* correctly. The arrow adapter+encoder turns `Array(UInt64)` into `Array(Nullable(UInt64))`, the custom encoder keeps `Array(UInt64)`.

I'll just update the .reference to accept the new behavior.

**Review by alexey-milovidov — APPROVED** [review]

**Comment by al13n321** [comment]
* Fuzzer failure unrelated: https://github.com/ClickHouse/ClickHouse/pull/63357
* Integration test failure looks unrelated, but I didn't investigate: https://s3.amazonaws.com/clickhouse-test-reports/63210/def04d25684ea7fc256b169b3d1468c0f32eb27b/integration_tests__tsan__[1_6]//home/ubuntu/actions-runner/_work/_temp/test/output_dir/integration_run_parallel3_0.log

**Comment by al13n321** [comment]
00002_log_and_exception_messages_formatting unrelated: https://github.com/ClickHouse/ClickHouse/pull/63358
02479_mysql_connect_to_self likely unrelated: https://pastila.nl/?05bd15c7/a9f779fe27064d8de9f6946b13e2711c.link#BAlOrMxawRWKQgipptEcoA==

**Pull request merged**
