### PR TITLE
Compressed logs for keeper

### PR DESCRIPTION
**Pull request by alesapin**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Add `compress_logs` settings for clickhouse-keeper which allow to compress clickhouse-keeper logs in `ZSTD` . Implements: #26977.

### CODE REVIEW

**Comment by alesapin** [comment]
For some reason zstd still argues, while keeper is able to read compressed logs:
```zstd -v -d var/lib/clickhouse/coordination/logs/changelog_1_100000.bin.zst                                                                                                                                                                    
*** zstd command line interface 64-bits v1.3.3, by Yann Collet ***                                                                                                                                                                                                               
log_1_100000.bin.zst : 14 MB...     log_1_100000.bin.zst : Read error (39) : premature end                                                                                                                                                                                       ```
Maybe I have stale version.

**Comment by alesapin** [comment]
```./zstd -v -d ../var/lib/clickhouse/coordination/logs/changelog_100001_200000.bin.zstd 
*** zstd command line interface 64-bits v1.4.9, by Yann Collet ***
0001_200000.bin.zstd : 43 MB...     0001_200000.bin.zstd : Read error (39) : premature end 
```

**Comment by alesapin** [comment]
@mergifyio update

**Comment by alesapin** [comment]
Ok, logs became much smaller. Now need to make snapshots compressed also with ZSTD.

**Review by nikitamikhaylov — APPROVED** [review]

**Comment by nikitamikhaylov** [comment]
Discussed a bit in private chat. Need to fix some issue.

**Comment by filimonov** [comment]
BTW - why not LZ4? It's few times faster (quite important for logs)

**Comment by alesapin** [comment]
> BTW - why not LZ4? It's few times faster (quite important for logs)
Simpler stream compression, good compression ration, small amount of data.

**Comment by alexey-milovidov** [comment]
LZ4 is too fast for ZooKeeper logs.
If we have several gigabytes of ZooKeeper logs per second - it's way more significant problem.

**Pull request merged**
