### PR TITLE
Keep alias type name to metadata

### PR DESCRIPTION
**Pull request by zhang2014**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Non-significant (changelog entry is not needed)

Detailed description (optional):
keep column data type alias to metadata

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]
Ok.

Looks like it will be useful for various BI platforms that generate CREATE queries and then look at the table structure.

BTW, could you please share your use case - where it is needed for you?

**Comment by alexey-milovidov** [comment]
Suspicious places in code:

FunctionsComparison:
```
|| (left.isEnum() && right.isEnum() && arguments[0]->getName() == arguments[1]->getName()) /// only equivalent enum type values can be compared against
```

RowInputFormatWithDiagnosticInfo:
```
    if (exception)
    {
        if (type->getName() == "DateTime")
            out << "ERROR: DateTime must be in YYYY-MM-DD hh:mm:ss or NNNNNNNNNN (unix timestamp, exactly 10 digits) format.\n";
        else if (type->getName() == "Date")
            out << "ERROR: Date must be in YYYY-MM-DD format.\n";
        else
            out << "ERROR\n";
        return false;
    }
```

MergeTreeData, isMetadataOnlyConversion.

We must continue and fix these use cases.

Also it will be useful to add a method `getCanonicalName` to IDataType and add a column with canonical type name to DESC TABLE and system.columns.

**Comment by zhang2014** [comment]
> BTW, could you please share your use case - where it is needed for you?

We have some users who are not very proficient with ClickHouse, and some of their code depend `DESC TABLE` result

> Suspicious places in code:

Sorry, I only focused on the test result and missed them. I will look into the code immediately.

**Comment by loyd** [comment]
It's too serious breaking changes. In fact, now many libraries are broken because they (for instance [python](https://github.com/mymarilyn/clickhouse-driver/blob/master/clickhouse_driver/columns/decimalcolumn.py#L140) or [rust](https://github.com/suharev7/clickhouse-rs) (now it's fixed)) don't support aliases. It is very strange to see such changes without any options.

**Comment by zhang2014** [comment]
It only works for tables that are created after this modification(not broken already tables)

Related #8429

**Pull request merged**
