### PR TITLE
Fixing race condition between INSERT into the dependent table and the CREATE and DELETE statements in Live View and Materialized View

### PR DESCRIPTION
**Pull request by vzakaznikov**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
* Fixing race condition between INSERT into the dependent table and the CREATE and DELETE statements in LIVE VIEW and MATERIALIZED VIEW.

Detailed description / Documentation draft:
* Fixing race condition between INSERT into the dependent table and the CREATE and DELETE statements in LIVE VIEW and MATERIALIZED VIEW as reported in https://github.com/ClickHouse/ClickHouse/issues/23157.
* Changing error code in MATERIALIZED VIEW when table is not supported.

### CODE REVIEW

**Comment by vzakaznikov** [comment]
@alexey-milovidov, @KochetovNicolai the same issue is most likely present in MV and any other table engine that calls `DatabaseCatalog::instance().addDependency` inside its constructor.

**Comment by vzakaznikov** [comment]
@alexey-milovidov, @KochetovNicolai  flaky test check is now passing https://clickhouse-test-reports.s3.yandex.net/25832/7f1834f5b16657c71066222e35f5018acdae7981/functional_stateless_tests_flaky_check_(address).html.

The parallel CREATE and INSERT are fixed by moving `addDependency` call to the `startup()` instead of being inside the table constructor.

The tricky part is to review https://github.com/ClickHouse/ClickHouse/pull/25832/commits/7f1834f5b16657c71066222e35f5018acdae7981. The diff looks bad but really I just added catching of `TABLE_IS_DROPPED` and `UNKNOWN_TABLE` in two places. This is needed to make sure that parallel DROP of the Materialized or Live view and INSERT into the source table does not cause INSERT to fail as from the user perspective presence or absence of any view should not affect operations on the source table.

**Comment by alexey-milovidov** [comment]
`PushingToViewsBlockOutputStream.cpp` does not exist anymore.

**Comment by vzakaznikov** [comment]
@alexey-milovidov, even if `PushingToViewsBlockOutputStream.cpp` does not exist anymore the tests that were added to this PR still show that problem persists and INSERT into source table still can randomly fail when either Materialized View or Live View is created over the source table or dropped. Please see the following tests: 

01932_live_view_insert_create_race_condition.sh
01933_materialized_view_insert_create_race_condition.sh 

You can easily reproduce the problem by increasing iterations count to 100. See https://github.com/vzakaznikov/ClickHouse/blob/7f1834f5b16657c71066222e35f5018acdae7981/tests/queries/0_stateless/01932_live_view_insert_create_race_condition.sh#L9.

**Pull request closed without merging**
