### PR TITLE
add aliases to visitParam/visitParamExtract* functions

### LINKED ISSUE #21383: Add aliases to visitParam (e.g. JSONS (Simplified))
visitParamHas -> JSONSHas
visitParamExtractUInt -> JSONSExtractUInt

### PR DESCRIPTION
**Pull request by fastio**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Add aliases `simpleJSONExtract/simpleJSONHas` to `visitParam/visitParamExtract{UInt, Int, Bool, Float, Raw, String}`. Fixes #21383.

Detailed description / Documentation draft:

#21383

### CODE REVIEW

**Comment by kssenii** [comment]
@fastio, can you, please, add it to a test ([may be here](https://github.com/ClickHouse/ClickHouse/blob/master/tests/queries/0_stateless/00539_functions_for_working_with_json.sql)).

**Comment by alexey-milovidov** [comment]
I'm against `JSONS` abbreviation, let's write `simpleJSON`.

**Comment by fastio** [comment]
> I'm against `JSONS` abbreviation, let's write `simpleJSON...`.

Ok, I'll rename it.

**Review by kssenii — APPROVED** [review]

**Comment by gyuton** [comment]
Internal documentation ticket: DOCSUP-8215.

**Pull request merged**
