### PR TITLE
Docs: Remove mention of materialized view table engine

### PR DESCRIPTION
**Pull request by rschu1ze**
The MV table engine is used purely internally: `CREATE TABLE t (a UInt32) ENGINE = MaterializedView` throws an error `DB::Exception: Direct creation of tables with ENGINE MaterializedView is not supported, use CREATE MATERIALIZED VIEW statement. (INCORRECT_QUERY)`. There is no point in mentioning the MaterializedView table engine in *user* documentation, not even in the "Special Table Engines" section which includes exotic but *usable* table engines.

### Changelog category (leave one):
- Documentation (changelog entry is not required)

### CODE REVIEW

**Comment by robot-ch-test-poll2** [comment]
*This is an automated comment for commit b9f281f6721b73545a8cb4347d4a8af0f446dd9d with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/57547/b9f281f6721b73545a8cb4347d4a8af0f446dd9d/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td><a href="https://github.com/ClickHouse/ClickHouse/actions/runs/7105628746">✅ success</a></td></tr>
<tbody>
</table>
</details>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/57547/b9f281f6721b73545a8cb4347d4a8af0f446dd9d/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Comment by jsc0218** [comment]
related to my recent push #56945, I might move the grant ability for it as well.

**Comment by rschu1ze** [comment]
Sure, go ahead with that.

**Comment by johnnymatthews** [comment]
Redirects are defined in https://github.com/ClickHouse/clickhouse-docs/blob/main/docusaurus.config.js starting at [line 286](https://github.com/ClickHouse/clickhouse-docs/blob/5ad2b93992df7eb57bb716cddc1cb0cbd9695689/docusaurus.config.js#L268).

**Comment by rschu1ze** [comment]
@johnnymatthews The redirects are still there, it would be great if you could check again? (or if I do it by myself, will I break something?)

**Pull request merged**
