### PR TITLE
Always prefer case insensitive suggestions

### PR DESCRIPTION
**Pull request by amosbird**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Non-significant (changelog entry is not required)

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

@alexey-milovidov btw, insensitive suggestion also works when built with readline now.

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
@amosbird I found strange issue:
when I type `merge` or `replica` and press TAB, there is no highlight of matched prefix by color.
while when I type, `max_rows` or `split`, it works as expected.

**Comment by alexey-milovidov** [comment]
Screenshot_20200319_124314

**Comment by amosbird** [comment]
If you type `format_` the prefix will be highlighted correctly. This is because replxx doesn't do case insensitive comparison when doing LCP https://github.com/AmokHuginnsson/replxx/blob/master/src/replxx_impl.cxx#L830

and the current implementation is naive. Let's patch it.

**Comment by alexey-milovidov** [comment]
Ok, now we have to patch it, because it's a little regresstion.

**Comment by amosbird** [comment]
https://github.com/ClickHouse-Extras/replxx/pull/3

**Comment by alexey-milovidov** [comment]
@amosbird Sorry, one more minor issue has been found.

If you type `Merg` (with intent to find MergeTree table) and press TAB, then the line is replaced to lowercase `merge` despite the fact that the `MergeTree` variant is also present in the completion list.

**Comment by amosbird** [comment]
@alexey-milovidov that's expected because the `merge` table function is also a correct candidate (although I cannot reproduce locally since there is also a `Merge` engine). You can type an additional `t` to complete `MergeTree`.

**Comment by alexey-milovidov** [comment]
Ok.

**Comment by alexey-milovidov** [comment]
FYI other regressions of replxx:
https://github.com/ClickHouse/ClickHouse/issues/9475
https://github.com/ClickHouse/ClickHouse/issues/9474

**Pull request merged**
