### PR TITLE
Replace --no-system-tables with loading virtual tables of system database lazily

### PR DESCRIPTION
**Pull request by azat**
**Note: this is just an draft patch, since it has `const_cast` and some `FIXME` that should be addressed first**

### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Replace --no-system-tables with loading virtual tables of system database lazily

First of all the problem is that that simple 'SELECT 1' cannot be runned without system.one, which makes --no-system-tables almost useless:

    $ ./clickhouse-debug local --no-system-tables -q "select 1"
    Code: 81. DB::Exception: Database system does not exist. (UNKNOWN_DATABASE)

Secondly there are just too many switches.

This patch should improve startup time of the clickhouse-local almost 3x in debug builds (but to make it 100% real profile events should be disabled as well, since it also requires DateLUT initialization).

Refs: #52489
Refs: #51347
Refs: #47475
Refs: #51199
Cc: @alexey-milovidov 
Cc: @davenger

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
I like the idea, and I like the removal of `--no-system-tables`. We can continue :)
It can be tricky though...

**Comment by azat** [comment]
Basically this should work, but proper interface changes is required now.

**Comment by azat** [comment]
I did the following interface changes:
- Make IDatabase::attachTableUnlocked() virtual and use it for overrides
- Move lazy table initialization interface into IDatabase

And I made this lazy initialization only for clickhouse-local, since the server will not win from this anything.

**Comment by azat** [comment]
Looks good.

>AST fuzzer (ubsan) — Logical error: 'Pipeline stuck. Current state:

- https://github.com/ClickHouse/ClickHouse/issues/57728 (cannot reproduce easily)

**Review by alexey-milovidov — APPROVED** [review]

**Comment by azat** [comment]
Though this PR does not makes any difference for debug binary, because of https://github.com/ClickHouse/ClickHouse/pull/56956/files - now logger is initialized everytime, so the DateLUTImpl will be initialized always, and this is the most slowest thing in debug builds.

At least let's do https://github.com/ClickHouse/ClickHouse/pull/57729

**Comment by incfly** [comment]
Hi @azat I think this PR introduces some [flakiness](https://play.clickhouse.com/play?user=play#c2VsZWN0IAp0b1N0YXJ0T2ZIb3VyKGNoZWNrX3N0YXJ0X3RpbWUpIGFzIGQsCmNvdW50KCksIGdyb3VwVW5pcUFycmF5KHB1bGxfcmVxdWVzdF9udW1iZXIpLCBncm91cFVuaXFBcnJheShjb21taXRfc2hhKQpmcm9tIGNoZWNrcyB3aGVyZSAnMjAyMi0wMy0wMScgPD0gY2hlY2tfc3RhcnRfdGltZSBhbmQgdGVzdF9uYW1lIGlsaWtlICclMDI5MzJfa2lsbF9xdWVyeV9zbGVlcCUnIGFuZCB0ZXN0X3N0YXR1cyBpbiAoJ0ZBSUwnLCAnRkxBS1knLCAnRVJST1InKSBncm91cCBieSBkIG9yZGVyIGJ5IGQgZGVzYw==) for our tests. `02932_kill_query_sleep` starts to fail after the merge. This is one of the [failure](https://s3.amazonaws.com/clickhouse-test-reports/56563/8edabdfd61a7c7c37f57379fc2a40a3d25e4e7bc/fast_test.html) error log


```
2023-12-13 20:54:30 [ip-172-31-79-4] 2023.12.13 20:54:28.674232 [ 153037 ] {a6bf8653-5b50-48ee-8142-6aa3b4b67bf7} <Error> executeQuery: Code: 60. DB::Exception: Table system.query_log does not exist. (UNKNOWN_TABLE) (version 23.12.1.1) (from [::ffff:127.0.0.1]:46694) (comment: 02932_kill_query_sleep.sh) (in query: SELECT count() FROM system.query_log WHERE query_id='sleep_query_id_02932_kill_query_sleep_test_0p312oce_15385' AND current_database = currentDatabase()), Stack trace (when copying this message, always include the lines below):
```

Maybe we can this still a configurable option and only applies to `-local`? Not sure.

**Comment by azat** [comment]
This patch is already only for `clickhouse-local`, though there is some generic code for all parts.

But about this test, it is not related to this patch, here is a simple fix for this test - https://github.com/ClickHouse/ClickHouse/pull/57849

**Comment by azat** [comment]
But about this patch, it does not help to improve the startup time due to logging system is not initialized everytime, and I'm not sure that this complexity worth it, let's revert it - https://github.com/ClickHouse/ClickHouse/pull/57851

**Pull request merged**
