### PR TITLE
Fix Zero-Copy replication with several S3 volumes (issue 22679)

### LINKED ISSUE #22679: Replicated tables with TTL moves or delete do not work when <allow_s3_zero_copy_replication> is set to 1
**Describe the bug**
When <allow_s3_zero_copy_replication> is set to 1 in the <merge_tree> configuration, replicated tables with TTL moves or delete are broken. SELECT from replicated tables with TTL moves or delete causes errors.

**Does it reproduce on recent release?**
[The list of releases](https://github.com/ClickHouse/ClickHouse/blob/master/utils/list-versions/version_date.tsv)

* 21.4.1 revision 54447

**How to reproduce**
* Version: 21.4.1 revision 54447
* Storage configuration: 
```
<yandex>
  <storage_configuration>
    <disks>
      <external>
        <type>s3</type>
        <endpoint>[AWS S3 endpoint]</endpoint>
        <access_key_id>[access_key_id]</access_key_id>
        <secret_access_key>[secret_access_key]</secret_access_key>
      </external>
      <external_tiered>
        <type>s3</type>
        <endpoint>[AWS S3 endpoint]</endpoint>
        <access_key_id>[access_key_id]</access_key_id>
        <secret_access_key>[secret_access_key]</secret_access_key>
      </external_tiered>
    </disks>
    <policies>
      <external>
        <volumes>
          <external>
            <disk>external</disk>
          </external>
        </volumes>
      </external>
      <tiered>
        <volumes>
          <default>
            <disk>external</disk>
          </default>
          <external>
            <disk>external_tiered</disk>
          </external>
        </volumes>
      </tiered>
    </policies>
  </storage_configuration>
</yandex>
```
* Merge tree configuration:
```
<yandex>
  <merge_tree>
    <allow_s3_zero_copy_replication>1</allow_s3_zero_copy_replication>
  </merge_tree>
</yandex>
```
* Statements to reproduce error: 
Note: either of the two following create statements could be used -- the error occurs with both TTL move and TTL delete.

Create replicated table with TTL move on two instances of ClickHouse:
```
CREATE TABLE zero_copy_replication ( d UInt64, d1 DateTime ) ENGINE = ReplicatedMergeTree('/clickhouse/zero_copy_replication_ttl', '1') ORDER BY d 
TTL d1 + interval 2 day to volume 'external'
SETTINGS storage_policy='tiered';
CREATE TABLE zero_copy_replication ( d UInt64, d1 DateTime ) ENGINE = ReplicatedMergeTree('/clickhouse/zero_copy_replication_ttl', '2') ORDER BY d 
TTL d1 + interval 2 day to volume 'external'
SETTINGS storage_policy='tiered';
```
Alternate create statement, replicated table with TTL delete on two instances of ClickHouse:
```
CREATE TABLE zero_copy_replication ( d UInt64, d1 DateTime ) ENGINE = ReplicatedMergeTree('/clickhouse/zero_copy_replication_ttl', '1') ORDER BY d 
TTL d1 + interval 2 day
SETTINGS storage_policy='tiered';
CREATE TABLE zero_copy_replication ( d UInt64, d1 DateTime ) ENGINE = ReplicatedMergeTree('/clickhouse/zero_copy_replication_ttl', '2') ORDER BY d 
TTL d1 + interval 2 day
SETTINGS storage_policy='tiered';
```
Insert data into the table, with some rows before the 2 day TTL, and some rows after the 2 day TTL.
Then, SELECT using a command similar to the following:
```
SELECT COUNT() FROM zero_copy_replication
```

**Expected behavior**
Expect to be able to SELECT from a replicated table with TTL with <allow_s3_zero_copy_replication> set to 1.

**Error message and/or stacktrace**
Error message:
```
Code: 499. DB::Exception: Received from localhost:9000. 
DB::Exception: <?xml version="1.0" encoding="UTF-8"?><Error><Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>data/zero-copy-replication/xqzqytlaumwdavygqraanbwlllelhijs</Key>
<RequestId>0W01GFT6FX2J4VDF</RequestId>
<HostId>FGeqq3GokrJx9qHMxu9TeFgmWrm/2nH0c6xMLTAGxcWXBeZgnapkwOfJixZZN9JXjjjd6Ei6CKY=</HostId>
</Error>: (while reading column d): (while reading from part 
/var/lib/clickhouse/disks/external/store/83b/83b6fb95-f932-417a-aaaf-c709d864e7a5/all_2_2_0/ 
from mark 23 with max_rows_to_read = 8192): While executing MergeTreeReverse.
```

### PR DESCRIPTION
**Pull request by ianton-ru**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Fix Zero-Copy replication with several S3 volumes (Fixes #22679)

Detailed description / Documentation draft:

If ClickHouse used storage with several S3 volumes, there was a big chance to remove data on S3 when volumes used the same S3 storage, and to make a second copy when volumes used different S3 storages.

### CODE REVIEW

**Comment by taiwhite** [comment]
@ianton-ru I am still receiving the same error from ttl moves with zero copy replication.

The tables I am using are the same as before. Note: This error occurs when there are two S3 buckets (the bucket urls are different).

Query: SELECT d FROM zero_copy_replication ORDER BY d DESC LIMIT 1
Error: Received exception from server (version 21.5.1): Code: 499. DB::Exception: Received from localhost:9000. DB::Exception: <?xml version="1.0" encoding="UTF-8"?> <Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Key>data/zero-copy-replication/yxgvblyphtcqefyfbopccojormhshpsl</Key><BucketName>root</BucketName><Resource>/root/data/zero-copy-replication/yxgvblyphtcqefyfbopccojormhshpsl</Resource><RequestId>1675210639F9C58A</RequestId><HostId>2b32c6b5-0aba-4acc-952c-7080ad9280db</HostId></Error>: (while reading column d): (while reading from part /var/lib/clickhouse/disks/external/store/3f5/3f5917b5-defe-477a-8303-90cd6ad2c89a/all_2_2_0/ from mark 23 with max_rows_to_read = 8192): While executing MergeTreeReverse.

**Review by alesapin — APPROVED** [review]
Approve but need one comment and maybe we can avoid a separate DeleteOnDestroyKeepS3 state with some flag. Discussed in tg.

**Comment by alesapin** [comment]
@mergifyio update

**Comment by alesapin** [comment]
@Mergifyio update

**Comment by alesapin** [comment]
no related failures.

**Comment by alesapin** [comment]
thread sanitizer:
```
2021-05-26 09:53:13,170 All tests from group test_s3_zero_copy_replication/test.py passed
2021-05-26 09:53:13,171 Tests from group test_s3_zero_copy_replication/test.py stats, SKIPPED count 0
2021-05-26 09:53:13,171 Totally have 0 with status SKIPPED
2021-05-26 09:53:13,171 Tests from group test_s3_zero_copy_replication/test.py stats, FAILED count 0
2021-05-26 09:53:13,171 Totally have 0 with status FAILED
2021-05-26 09:53:13,171 Tests from group test_s3_zero_copy_replication/test.py stats, FLAKY count 0
2021-05-26 09:53:13,171 Totally have 3 with status FLAKY
2021-05-26 09:53:13,171 Tests from group test_s3_zero_copy_replication/test.py stats, PASSED count 8
2021-05-26 09:53:13,171 Totally have 582 with status PASSED
2021-05-26 09:53:13,171 Tests from group test_s3_zero_copy_replication/test.py stats, ERROR count 0
```

**Pull request merged**
