### PR TITLE
Removes duplicated slugs in docs.

### LINKED ISSUE #1654: Fix `Duplicate routes` warning.
This repo creates the following warning when building (`yarn build`):

```
10:50:07 AM: - Attempting to create page at /docs/en/getting-started/example-datasets/wikistat, but a page already exists at this route.
10:50:07 AM: - Attempting to create page at /docs/en/getting-started/example-datasets/wikistat, but a page already exists at this route.
10:50:07 AM: - Attempting to create page at /docs/en/operations/optimizing-performance/profile-guided-optimization, but a page already exists at this route.
10:50:07 AM: - Attempting to create page at /docs/en/operations/optimizing-performance/profile-guided-optimization, but a page already exists at this route.
10:50:07 AM: This could lead to non-deterministic routing behavior.
```

Probably because we've got >1 file that uses `/getting-started/example-datasets/wikistat` as the `url` or `slug` variable in the front-matter. Should be a pretty simple fix.

### PR DESCRIPTION
**Pull request by johnnymatthews**
### Changelog category (leave one):
- Documentation (changelog entry is not required)

### Documentation entry for user-facing changes

- [x] Documentation is written (mandatory for new features)

---

Closes https://github.com/ClickHouse/clickhouse-docs/issues/1654

We're getting some warning when building the docs site:

```plaintext
10:50:07 AM: - Attempting to create page at /docs/en/getting-started/example-datasets/wikistat, but a page already exists at this route.
10:50:07 AM: - Attempting to create page at /docs/en/getting-started/example-datasets/wikistat, but a page already exists at this route.
10:50:07 AM: - Attempting to create page at /docs/en/operations/optimizing-performance/profile-guided-optimization, but a page already exists at this route.
10:50:07 AM: - Attempting to create page at /docs/en/operations/optimizing-performance/profile-guided-optimization, but a page already exists at this route.
10:50:07 AM: This could lead to non-deterministic routing behavior.
```

This is because the two files changed in this PR (`/docs/en/operations/optimizing-performance/profile-guided-optimization.md` and `/docs/en/getting-started/example-datasets/wikistat.md` had slugs identical to the addresses given to them by Docusaurs at build-time.

Removing these two slugs from the front-matter removed the above error. The pages are still available are their normal addresses -- there are no redirects needed.

### CODE REVIEW

**Comment by robot-ch-test-poll3** [comment]
*This is an automated comment for commit ecc012cc4de09b2668d5bcb25419d2ad4a3612d3 with description of existing statuses. It's updated for the latest CI running*

[❌ Click here](https://s3.amazonaws.com/clickhouse-test-reports/56539/ecc012cc4de09b2668d5bcb25419d2ad4a3612d3/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://github.com/ClickHouse/ClickHouse/blob/master/.github/PULL_REQUEST_TEMPLATE.md?plain=1">❌ failure</a></td></tr>
<tbody>
</table>

**Review by alexey-milovidov — APPROVED** [review]

**Comment by nikitamikhaylov** [comment]
@johnnymatthews Please follow the PR description template as CI checks it https://github.com/ClickHouse/ClickHouse/blob/master/.github/PULL_REQUEST_TEMPLATE.md

**Comment by johnnymatthews** [comment]
@nikitamikhaylov ah sorry. Didn't realize that also ran for purely docs edits. I've added the content to the top of my PR description. Will that work, or does the PR need to be re-created?

**Comment by nikitamikhaylov** [comment]
Let me just push an empty commit to rerun the CI.

**Pull request merged**
