### PR TITLE
Fix false positives leaky memory warnings in OpenSSL

### LINKED ISSUE #63792: memory leak in openssl
The leak has been catch in clickhouse-local

Here is the report:
https://s3.amazonaws.com/clickhouse-test-reports/62652/d8856b06d873797117ca260d009d55a7632bcb58/stress_test__asan_/run.log

It happened that `LeakSanitizer does not work under ptrace (strace, gdb, etc)`.
It means that we do not see memory sanitizers reports for all our stress tests. That is sad.

### PR DESCRIPTION
**Pull request by rschu1ze**
Fixes #63792
Fixes https://github.com/ClickHouse/clickhouse-private/issues/10107

Longer explanation here:
- https://github.com/ClickHouse/openssl/commit/5c4b034785bf04f80380138cf49bf9743400f144
- https://github.com/ClickHouse/openssl/commit/67c0b63e578e4c751ac9edf490f5a96124fff8dc

I could actually reproduce only the first one locally but I think that the PR fixes both. If the issue re-occurs, please re-open.

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by robot-ch-test-poll3** [comment]
*This is an automated comment for commit e0279e856f874c652d292d8c903975f51f2de3ba with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/65125/e0279e856f874c652d292d8c903975f51f2de3ba/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>A Sync</td><td>If it fails, ask a maintainer for help</td><td>⏳ pending</td></tr>
<tbody>
</table>
<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>Checks correctness of the PR's body</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

**Comment by alexey-milovidov** [comment]
This also indicates the poor development culture of OpenSSL. Either no testing with ASan or no testing of these code paths.

**Comment by rschu1ze** [comment]
Could not find further leak findings (`LeakSanitizer: detected memory leaks`) in run.log of asan stateless tests and in log files of asan stress tests, so we should be good.

**Review by hanfei1991 — APPROVED** [review]

**Comment by rschu1ze** [comment]
ClickHouse Integration Tests (aarch64) [5/6]: https://github.com/ClickHouse/ClickHouse/issues/64451
ClickHouse Stateless Tests (tsan) [4/5]: 
ClickHouse Upgrade Check (debug): Setting changes not reflected in setting history

**Pull request merged**
