### PR TITLE
Write metadata to disk and keeper in the same format

### LINKED ISSUE #54750: Wrong parsing of AST in CREATE TABLE with multiple CSEs
IMPORTANT: due to this bug table gets inconsistent metadata on disk vs ZK, if used with a different table engine. So clickhouse will not start.

**How to reproduce**
```
~ :) create table kek (
    `id` String,
    `value1` Float32,
    `value2` Float32,
    `param` String,
    `date` String,
    `val1` Float32 MATERIALIZED value1 * dictGetFloat32('default.dict', 'rate', (param, toDate(date) AS date_local)),
    `val2` Float32 MATERIALIZED value2 * dictGetFloat32('default.dict', 'rate', (param, toDate(date) AS date_local))
)
ENGINE = MergeTree()
PRIMARY KEY id
ORDER BY id
SETTINGS index_granularity = 8192

CREATE TABLE kek
(
    `id` String,
    `value1` Float32,
    `value2` Float32,
    `param` String,
    `date` String,
    `val1` Float32 MATERIALIZED value1 * dictGetFloat32('default.dict', 'rate', (param, toDate(date) AS date_local)),
    `val2` Float32 MATERIALIZED value2 * dictGetFloat32('default.dict', 'rate', (param, date_local)) <----- problem is here
)
ENGINE = MergeTree
PRIMARY KEY id
ORDER BY id
SETTINGS index_granularity = 8192

Query id: ff4986cc-34ff-46d9-8310-d44bc3e7b2cb

Ok.
```

There are two "AS date_local" which leads to wrong AST parsing due to the following code:

https://github.com/ClickHouse/ClickHouse/blob/ed22d0f028ca15256d4807d879fe22a722f751e8/src/Parsers/ASTWithAlias.cpp#L19-L27

### PR DESCRIPTION
**Pull request by mstetsyuk**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Make `ColumnsDescription::toString` format each column using the same `IAST::FormatState object`. This results in uniform columns metadata being written to disk and ZooKeeper.

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Run only fuzzers related jobs (libFuzzer fuzzers, AST fuzzers, etc.)
- [ ]  Exclude: AST fuzzers
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-ch-test-poll1** [comment]
*This is an automated comment for commit 0b9c24f31d548c87deca3334282c14fc78a295ba with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/68733/0b9c24f31d548c87deca3334282c14fc78a295ba/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

**Comment by nikitamikhaylov** [comment]
What about backward compatibility in a mixed-versions cluster?

**Comment by mstetsyuk** [comment]
@nikitamikhaylov, this change is backward compatible because a new server version can process old columns' metadata (where the aliases are "expanded") without issues. It is also forward compatible.

**Comment by mstetsyuk** [comment]
merging since exactly the same PR was previously approved: https://github.com/ClickHouse/ClickHouse/pull/68580

**Comment by evillique** [comment]
Although this fixes the issue with tables not working after a restart, the table will not be able to be ALTERed after a restart.

To reproduce you can add
```
node.query(f"ALTER TABLE {table_name} ADD COLUMN _test_ UInt8, DROP COLUMN _test_;")
```
after this:
https://github.com/ClickHouse/ClickHouse/blob/0b9c24f31d548c87deca3334282c14fc78a295ba/tests/integration/test_aliases_in_default_expr_not_break_table_structure/test.py#L60

You will get the following error:
```
Code: 47. DB::Exception: Received from 172.16.1.6:9000. DB::Exception: Missing columns: 'event' while processing query: 'JSONExtractString(event, 'col2-key')', required columns: 'event' 'event'. Stack trace:
```

So to me, this fix looks incorrect, the resulting column definition erases all the definitions of aliases except in one column. The alias with the same name & definition can be used in other columns and if we try to ALTER anything we would get the error above from the columns where this alias is not defined (even though we don't modify them directly).

The proper solution to make the metadata consistent is to make the table definition saved inside databases include all the alias definitions provided by the user, additionally adding a check that a default expression defines all the used aliases, and doesn't refer to the aliases inside other columns' default expressions.

cc @tavplubix

**Comment by tavplubix** [comment]
> The alias with the same name & definition can be used in other columns and if we try to ALTER anything we would get the error above from the columns where this alias is not defined (even though we don't modify them directly)

This looks like another bug in validation of ALTERs: https://github.com/ClickHouse/clickhouse-private/issues/14825

**Comment by evillique** [comment]
Well, changing how we validate is another option to fix it but in that case we would need to handle the case when we drop the first (and only) column where this alias is defined and throw somewhat user-friendly exception.

To mitigate this exception we would need to add this alias definition to another column which contains this alias, but adding it in a separate ALTER will not work (we will erase it once again), so we have to do it in a single ALTER. And repeat it, if we will need to drop this second column at some point. Not the best user experience that we could provide, at least in my opinion.

**Pull request merged**
