### PR TITLE
Revert "Slightly better calculation of primary index"

### PR DESCRIPTION
**Pull request by alesapin**
Reverts ClickHouse/ClickHouse#66099

Breaks memory tracker for long running INSERT/SELECT.

### CODE REVIEW

**Review by Algunenano — APPROVED** [review]

**Comment by alesapin** [comment]
```
CREATE TABLE default.wikistat                                                                                                                                                                                                                                                                    
(                                                                                                                                                                                                                                                                                                     
    `time` DateTime CODEC(Delta(4), ZSTD(3)),                                                                                                                                                                                                                                                         
    `project` LowCardinality(String),                                                                                                                                                                                                                                                                 
    `subproject` LowCardinality(String),                                                                                                                                                                                                                                                              
    `path` String CODEC(ZSTD(3)),                                                                                                                                                                                                                                                                     
    `hits` UInt64 CODEC(ZSTD(3))                                                                                                                                                                                                                                                                      
)                                                                                                                                                                                                                                                                                                     
ENGINE = MergeTree()                                                                                                                                                                                                                                                             
ORDER BY (path, time)                                                                                                                                                                                                                                                                                 
SETTINGS index_granularity = 8192

SET min_insert_block_size_bytes = 2000000000, min_insert_block_size_rows = 0

INSERT INTO wikistat WITH                                                                                                   
    parseDateTimeBestEffort(extract(_file, '^pageviews-([\\d\\-]+)\\.gz$')) AS time,                                                               
    splitByChar(' ', line) AS values,                                                                                                              
    splitByChar('.', values[1]) AS projects                                                                                                        
SELECT                                                                                                                                             
    time,                                                                                                                                          
    projects[1] AS project,                                                                                                                        
    projects[2] AS subproject,                                                                                                                     
    decodeURLComponent(values[2]) AS path,                                                                                                         
    CAST(values[3], 'UInt64') AS hits                                                                                                              
FROM s3('https://clickhouse-public-datasets.s3.amazonaws.com/wikistat/original/pageviews*.gz', 'NOSIGN', 'LineAsString')                                                                                                                                                                              
WHERE length(values) >= 3                                                                                                                          
```

Wait for 4 minutes. Memory should be around 2-7 gigs, if it grow above than it's a bug.

**Comment by robot-ch-test-poll1** [comment]
*This is an automated comment for commit c2a40940dbc6a2bac3623bef2ac56bc842d837fd with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/67392/c2a40940dbc6a2bac3623bef2ac56bc842d837fd/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/67363/4488d65fe91b58f72fec7536a8f8314aa3deec38/docs_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Comment by alexey-milovidov** [comment]
@alesapin Could you please add a test?

**Comment by alesapin** [comment]
@alexey-milovidov , I've tried, but for some reason failed with generateRandom and long strings in PK. I don't think that test which depend on public S3 bucket is good idea. I'll try to find a way how to test it properly.

**Comment by alesapin** [comment]
This revert is required for release stability.

**Comment by alesapin** [comment]
Replicated DB: https://github.com/ClickHouse/ClickHouse/issues/67444

**Comment by alesapin** [comment]
Fuzzer: https://github.com/ClickHouse/ClickHouse/issues/67445

**Pull request merged**
