### PR TITLE
Optimize DB::combineFilters with AVX512_VBMI2 intrinsic

### PR DESCRIPTION
**Pull request by ZhiguoZh**
Optimize DB::combineFilters with AVX512_VBMI2 intrinsic

The DB::combineFilters combines two UInt8 columns (filters) by scanning the first column for non-zero elements and replacing them with elements in the second column contiguously.

This function is optimized with Intel's AVX512_VBMI2 intrinsic, _mm512_mask_expandloadu_epi8, which is designed for implementing the exact operation when the bits in the writemask are set when the corresponding packed integers in the first filter are non-zero, and are not set otherwise. The dynamic dispatch ensures that this optimization only applies to devices with AVX512_VBMI2 support.

### Changelog category (leave one):
- Performance Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
The performance experiments of **OnTime** on the ICX device (Intel Xeon Platinum 8380 CPU, 80 cores, 160 threads) show that this change could bring the improvements of **7.4%, 5.9%, 4.7%, 3.0%, and 4.6%** to the QPS of the query Q2, Q3, Q4, Q5 and Q6 respectively while having no impact on others.

The [manual](https://www.intel.com/content/www/us/en/docs/intrinsics-guide/index.html#text=_mm512_mask_expandloadu_epi8) of this intrinsic describes its behavior with the following pseudocode, which might be helpful for your code review:
image

  

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by robot-clickhouse** [comment]
*This is an automated comment for commit af0f1e77feded3e5e25259144b73a70f5dd0adf9 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/56079/af0f1e77feded3e5e25259144b73a70f5dd0adf9/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td><a href="https://github.com/ClickHouse/ClickHouse/actions/runs/6667831623">✅ success</a></td></tr>
<tbody>
</table>
</details>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/56079/af0f1e77feded3e5e25259144b73a70f5dd0adf9/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Comment by ZhiguoZh** [comment]
It seems that the 3 failed cases were not resulted from this code change. This PR is ready for your code review.

Hi Alexey, could you kindly help me review this PR? Thanks so much for your help! @alexey-milovidov

**Comment by ZhiguoZh** [comment]
Hi Dmitry, thanks for your review of this PR! BTW, I'm actually not sure if more tests or data are needed to further validate the correctness and performance impact of this vectorized alternative implementation. Could you kindly share with me your insights into this PR?

@novikd

**Review by novikd — COMMENTED** [review]
In general LGTM, but I think it's better to add more tests

**Comment by ZhiguoZh** [comment]
Hi Dmitry, thank you very much for your suggestion! And following your suggestion, I've added more tests which combine two UInt8 columns. Compared with the existing one, it is designed for enhancing the effectiveness of the unit tests in two aspects:

1. The interval between two consecutive non-zero elements in the **first column** is inconstant, ranging from 0 to ~630, while the previous fixed interval is 2.
2. The values in the **second column** are no longer 0 and 1, so that much contingency of the data could be eliminated.

It seems the two failed tests were unrelated to this code change and I think this PR is ready for your further review. Thanks for your help!

@novikd

**Comment by ZhiguoZh** [comment]
Thanks Dmitry and Alexey for kindly reviewing the code!

@novikd @alexey-milovidov

**Pull request merged**
