### PR TITLE
Build improvements by removing magic enum from header and apply some explicit template instantiation

### PR DESCRIPTION
**Pull request by antaljanosbenjamin**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

This PR addresses two things:
1. remove some `magic_enum` inclusion from headers
2. explicitly instantiate some `CacheBase` templates

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by robot-ch-test-poll2** [comment]
*This is an automated comment for commit 2920d63c6351378f4337410ffe20615ef9fe9eed with description of existing statuses. It's updated for the latest CI running*

[❌ Click here](https://s3.amazonaws.com/clickhouse-test-reports/61665/2920d63c6351378f4337410ffe20615ef9fe9eed/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td><a href="https://github.com/ClickHouse/ClickHouse/blob/master/.github/PULL_REQUEST_TEMPLATE.md?plain=1">❌ failure</a></td></tr>
<tbody>
</table>

**Review by alexey-milovidov — APPROVED** [review]

**Comment by antaljanosbenjamin** [comment]
Please don't merge the PR until I can verify that the improvements actually work.

**Comment by antaljanosbenjamin** [comment]
The `CacheBase` related improvements [worked](https://pastila.nl/?0015dce3/8ad1eea3a6622f3fd416d84c80bd873f#GkWG2QI/pBRXOjO80XkSFg==)!

I will try to figure out the magic enum related ones.

**Comment by antaljanosbenjamin** [comment]
For the other ones it is much harder to find an exact comparison, because it is about parsing time (as I removed some includes). Thus if everything works, I will merge the PR.

**Review by alexey-milovidov — APPROVED** [review]

**Pull request merged**
