### PR TITLE
Allow reloading max_concurrent_queries without a server restart

### PR DESCRIPTION
**Pull request by Algunenano**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Apply config changes to `max_concurrent_queries` during runtime (no need to restart).

Detailed description / Documentation draft:

In some situations (incidents) it's useful to be able to temporarily modify `max_concurrent_queries` without needing to restart the server.

### CODE REVIEW

**Review by nikitamikhaylov — APPROVED** [review]

**Comment by amosbird** [comment]
We already provide similar functionality via a different user setting https://github.com/ClickHouse/ClickHouse/pull/16154

**Comment by Algunenano** [comment]
> We already provide similar functionality via a different user setting #16154

The idea in this case is to allow extra "work" queries (temporarily or permanently), not to add an extra connection to be able to get in.

**Comment by amosbird** [comment]
> The idea in this case is to allow extra "work" queries (temporarily or permanently)

That's exactly what `max_concurrent_queries_for_all_users` is for. It doesn't have the name of **connection**.

**Comment by Algunenano** [comment]
> That's exactly what max_concurrent_queries_for_all_users is for. It doesn't have the name of connection.

max_concurrent_queries_for_all_users won't work if max_concurrent_queries is smaller. For example, in the default config you have `max_concurrent_queries: 100` and `max_concurrent_queries_for_all_users : 0`. If you now want to allow 200 concurrent queries you will need to raise `max_concurrent_queries` and restart the server, right?

**Comment by amosbird** [comment]
> max_concurrent_queries_for_all_users won't work if max_concurrent_queries is smaller.

Yes. But why not use `max_concurrent_queries_for_all_users` only and ditch the old `max_concurrent_queries` server setting?

**Comment by Algunenano** [comment]
> Yes. But why not use max_concurrent_queries_for_all_users only and ditch the old max_concurrent_queries server setting?

I mean yeah, if you know about the option and think it can be an issue you are going to face then using `max_concurrent_queries_for_all_users` and setting `max_concurrent_queries` to 0 is the way to go. 

But since `max_concurrent_queries` is the default control, I think it would be beneficial for end users to be able to change it during runtime, even if it is to then start using user settings.

**Pull request merged**
