### PR TITLE
Resurrect `arrayFold()`

### PR DESCRIPTION
**Pull request by rschu1ze**
Function `arrayFold()` was rolled back in #57836 due to two bugs.

This PR
- reverts the revert: https://github.com/ClickHouse/ClickHouse/pull/57879/commits/b36a93a25d880ee95c6167c228d7ef8b9d97fcc2
- refactors the code (expressive variable names, smaller scopes, comments) such that future readers don't need to debug for hours and hours (like me) just to understand what is going on: https://github.com/ClickHouse/ClickHouse/pull/57879/commits/f17d7e44f40af656d3d2bf599980440efb5096f4
- fixes the actual bugs: https://github.com/ClickHouse/ClickHouse/pull/57879/commits/eee4bacd712f726abc092301c6f15f1179ac8342 https://github.com/ClickHouse/ClickHouse/pull/57879/commits/69007b5f7175e260dd6c656a3423378d0eac072e

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Resurrect function `arrayFold()` (https://github.com/ClickHouse/ClickHouse/pull/57836) but this time, really fix it.

### CODE REVIEW

**Comment by robot-ch-test-poll4** [comment]
*This is an automated comment for commit b3ee02784254fda264612502b90f7ef891f793fb with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/57879/b3ee02784254fda264612502b90f7ef891f793fb/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td><a href="https://github.com/ClickHouse/ClickHouse/actions/runs/7214140606">✅ success</a></td></tr>
<tbody>
</table>
</details>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/57879/b3ee02784254fda264612502b90f7ef891f793fb/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
Ok. One question - why this bug was not found by fuzzing? Please enhance our fuzzer in a way that makes this bug easily found (it's ok to do it in another PR).

**Comment by pheepa** [comment]
I see this `SELECT arrayFold(acc, x -> arrayIntersect(acc, x), [['qwe', 'asd'], ['qwe','asde']], []);` fixed but 

We still have
```
SELECT arrayFold((acc, x) -> arrayConcat(acc, x), [[1, 2], [3, 4]], [])

Query id: 18c0de2f-ed88-45e8-ac23-f234266f1465


Elapsed: 0.001 sec. 

Received exception:
Code: 53. DB::Exception: Return type of lambda function must be the same as the accumulator type, inferred return type of lambda: Array(UInt8), inferred type of accumulator: Array(Nothing): In scope SELECT arrayFold((acc, x) -> arrayConcat(acc, x), [[1, 2], [3, 4]], []). (TYPE_MISMATCH)
```

Is it a bug?

**Comment by rschu1ze** [comment]
The error message points to the problem, you can rewrite the query to

```sql
SELECT arrayFold((acc, x) -> arrayConcat(acc, x), [[1, 2], [3, 4]], emptyArrayUInt8())
```

**Pull request merged**
