### PR TITLE
Delete a test

### PR DESCRIPTION
**Pull request by kssenii**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by robot-ch-test-poll3** [comment]
*This is an automated comment for commit ca14363d0d4acbd022e443ecd966687de525e712 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/54984/ca14363d0d4acbd022e443ecd966687de525e712/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>✅ success</td></tr>
<tbody>
</table>
</details>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>⏳ pending</td></tr>
<tbody>
</table>

**Comment by kssenii** [comment]
Will merge without tests as I just deleted the test so there is not reason for a full tests run.
(p.s. deleted the test because after tests with dynamic cached disks were added there is no way to make this test non-flaky)

**Comment by tavplubix** [comment]
Now we don't have any tests for `DESCRIBE FILESYSTEM CACHE`, so consider removing this feature as well

**Comment by tavplubix** [comment]
> Now we don't have any tests for `DESCRIBE FILESYSTEM CACHE`, so consider removing this feature as well

A new test added in https://github.com/ClickHouse/ClickHouse/pull/55003

**Pull request merged**
