### PR TITLE
Fix IPv4/IPv6 serialization/deserialization in binary formats

### LINKED ISSUE #46522: Array(IPv6) type check is broken for capnp format
I use kafka engine and capnp schema to insert data to my clickhouse servers.
After upgrade from the clickhouse 21.8.15.7 to 22.3.12.19 my capnp deserlialization was broken. Please see https://github.com/ClickHouse/ClickHouse/issues/43319 to get more details.

The ticket https://github.com/ClickHouse/ClickHouse/issues/43319 was fixed in https://github.com/ClickHouse/ClickHouse/pull/43379, but we still have problems in the last clickhouse version (23.1.3.5). Now we cannot convert ClickHouse type Array(IPv6) to CapnProto type List(Data).

**Steps to reproduce**

Create the table:
```sql
create table ArrayIPv6Example
(
    myField Array(IPv6)
) engine MergeTree
order by tuple();
```

Create schema.capnp file:
```
@0xb6ecde1cd54a101d;

struct ArrayIPv6Example {
    myField @0 :List(Data);
}
```
Execute command: `clickhouse-client --query "SELECT * FROM ArrayIPv6Example FORMAT CapnProto SETTINGS format_schema = 'schema:ArrayIPv6Example'"`.

You will see the error: `Code: 623. DB::Exception: Code: 623. DB::Exception: Cannot convert ClickHouse type Array(IPv6) to CapnProto type List(Data). (CAPN_PROTO_BAD_CAST) (version 23.1.3.5 (official build)): (in query: SELECT * FROM ArrayIPv6Example FORMAT CapnProto SETTINGS format_schema = 'schema:ArrayIPv6Example'). (CAPN_PROTO_BAD_CAST)`

@Avogar is it possible to add a new config in clickhouse to disable this type checks?

### PR DESCRIPTION
**Pull request by Avogar**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in official stable or prestable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix IPv4/IPv6 serialization/deserialization in binary formats that was broken in https://github.com/ClickHouse/ClickHouse/pull/43221.
Closes https://github.com/ClickHouse/ClickHouse/issues/46522

### CODE REVIEW

**Comment by KochetovNicolai** [comment]
Thank you!
@Avogar can you additionally verify that serialization is the same it was before https://github.com/ClickHouse/ClickHouse/pull/43221 ? (even better, add a test)

I think we should also backport it to 23.1 and 23.2

**Comment by Avogar** [comment]
> can you additionally verify that serialization is the same it was before https://github.com/ClickHouse/ClickHouse/pull/43221 ? (even better, add a test)

You mean check that we serialize IPv4/IPv6 in the same way in different formats that it was before? I tried to implement it to be the same as it was for binary formats. We can add a test where we compare current IPv4/IPv6 serialization with serialization of UInt32/FixedString with the same value (as it was previously)

> I think we should also backport it to 23.1

Sure, I also wanted to backport it

**Review by yakov-olkhovskiy — APPROVED** [review]

**Comment by Algunenano** [comment]
It seems that the test introduced here [hasn't worked a single time in master ](https://play.clickhouse.com/play?user=play#U0VMRUNUCiAgY2hlY2tfc3RhcnRfdGltZSwKICBjaGVja19zdGF0dXMsCiAgY2hlY2tfbmFtZSwKICB0ZXN0X25hbWUKRlJPTSBjaGVja3MKV0hFUkUKICAgIHRlc3RfbmFtZSA9ICcwMjU2Nl9pcHY0X2lwdjZfYmluYXJ5X2Zvcm1hdHMnCiAgICBBTkQgcHVsbF9yZXF1ZXN0X251bWJlciA9IDAKICAgIEFORCBjaGVja19zdGFydF90aW1lID4gbm93KCkgLSBpbnRlcnZhbCA3IGRheQo=) -> https://github.com/ClickHouse/ClickHouse/issues/47294

**Comment by yakov-olkhovskiy** [comment]
@Algunenano I've noticed it too in some other PR - very strange it's reported as flaky and wasn't reported in this PR... most likely we need to fix test itself:
```
2023-03-07 04:53:04 --- /usr/share/clickhouse-test/queries/0_stateless/02566_ipv4_ipv6_binary_formats.reference	2023-03-07 04:34:59.453041294 +0100
2023-03-07 04:53:04 +++ /tmp/clickhouse-test/0_stateless/02566_ipv4_ipv6_binary_formats.stdout	2023-03-07 04:53:04.457182803 +0100
2023-03-07 04:53:04 @@ -6,7 +6,7 @@
2023-03-07 04:53:04  2001:db8:11a3:9d7:1f34:8a2e:7a0:765d	127.0.0.1
2023-03-07 04:53:04  Parquet
2023-03-07 04:53:04  ipv6	Nullable(FixedString(16))					
2023-03-07 04:53:04 -ipv4	Nullable(Int64)					
2023-03-07 04:53:04 +ipv4	Nullable(UInt32)					
2023-03-07 04:53:04  2001:db8:11a3:9d7:1f34:8a2e:7a0:765d	127.0.0.1
2023-03-07 04:53:04  ORC
2023-03-07 04:53:04  ipv6	Nullable(String)					
2023-03-07 04:53:04 
```

**Comment by Avogar** [comment]
Already fixed, see https://github.com/ClickHouse/ClickHouse/issues/47294#issuecomment-1457871148

**Pull request merged**
