### PR TITLE
Adding support for INSERT INTO table WATCH query to build streaming systems using LIVE VIEW tables

### PR DESCRIPTION
**Pull request by vzakaznikov**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
- Adding support for `INSERT INTO [db.]table WATCH` query

Detailed description / Documentation draft:
Adding support for `INSERT INTO [db.]table WATCH` query to allow live streams from LIVE VIEW tables provided by the `WATCH` query to be pushed to other tables or table functions such as url() etc. 

The `output_format_enable_streaming` setting is added to support streaming outputs.
This setting can be used by any output format to enable streaming mode, if implemented.

Test Plan:
- [x] Add test to push results to `MergeTree` table
- [x] Add test to push results to `url` table function using `CSV` format 
- [x] Add test to push results to `url` table function using `JSONEachRow` format
- [x] Add test to push results to `url` table function using `JSONEachRowWithProgress` format

Supported Streaming Output Formats:
- [x] using the new auto_flush flag for all the formats

### CODE REVIEW

**Comment by vzakaznikov** [comment]
@KochetovNicolai, I've added a test `0_stateless/01247_insert_into_watch_live_view_url.py ` but it does not pass. There seems to be an issue with the `url` table function. The data is being buffered somewhere by the StorageURL's output stream and does not get written out until the stream is finalized. Any ideas how it can be fixed?

**Comment by vzakaznikov** [comment]
Resolving the issue with `url` table function by using the `output_format_enable_stream` setting. Most row output formats can be updated to support streaming mode by flushing their output buffers after each block is consumed.

**Comment by jason-godden** [comment]
This is a great feature. Will this also work within materialised views to provide continuous aggregations and as input into versioned Replacing MergeTree?

**Comment by vzakaznikov** [comment]
> This is a great feature. Will this also work within materialised views to provide continuous aggregations and as input into versioned Replacing MergeTree?

Hi Jason, could you provide an example of what you have in mind?

**Comment by jason-godden** [comment]
Hey @vzakaznikov  

I was wondering how this would work with materialized views - so something like:

```sql
CREATE MATERIALIZED VIEW x TO replicated_merge_tree AS
WATCH some_live_view
```

I'm not sure how the current INSERT INTO x WATCH some_live_view would work - does it run continuously until the server is stopped and start again once the server is started? Or is it sort of once off thing - not sure how you interact in a single session or kill/restart it etc..

Thanks

**Comment by vzakaznikov** [comment]
@jason-godden, for the case of something like 
```sql
CREATE MATERIALIZED VIEW x TO replicated_merge_tree AS
WATCH some_live_view
```
it would not work. But what will work is `INSERT INTO replicated_merge_tree WATCH some_live_view` where you "insert right into the inner table". You would not need MATERIALIZED VIEW as the LIVE VIEW would do all the work.
The disadvantage is that `INSERT INTO replicated_merge_tree WATCH` is just a query that would never end and has to be started and managed manually. So this PR will not directly get what you want. I guess for what you have in mind we would need to add something like 
```sql
CREATE LIVE VIEW some_live_view TO replicated_merge_tree AS SELECT ....
```
which I think is totally doable and would not be hard to implement.

**Review by KochetovNicolai — APPROVED** [review]

**Comment by vzakaznikov** [comment]
https://github.com/ClickHouse/ClickHouse/pull/10498/commits/9d280665391a3f171ba40bb0833ab6afe0457cbe

**Pull request merged**
