### PR TITLE
Added multiple query formatting on clickhouse-format

### PR DESCRIPTION
**Pull request by dgrr**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

The `clickhouse-format` tool is now able to format multiple queries when the `-n` argument is used.

Detailed description / Documentation draft:

If the `-n` is specified `clickhouse-format` will be able to format multiple queries printing `\n;\n`
as separation string between them.

By adding documentation, you'll allow users to try your new feature immediately, not when someone else will have time to document it later. Documentation is necessary for all features that affect user experience in any way. You can add brief documentation draft above, or add documentation right into your patch as Markdown files in [docs](https://github.com/ClickHouse/ClickHouse/tree/master/docs) folder.

If you are doing this for the first time, it's recommended to read the lightweight [Contributing to ClickHouse Documentation](https://github.com/ClickHouse/ClickHouse/tree/master/docs/README.md) guide first.

### CODE REVIEW

**Comment by qoega** [comment]
Looks OK. Lets look on build results.

**Comment by nvartolomei** [comment]
A test would be useful, see https://github.com/ClickHouse/ClickHouse/blob/97f2a2213e754ba25dabba4bc8ddf507cd67660c/tests/queries/0_stateless/00948_format_in_with_single_element.sh together with https://github.com/ClickHouse/ClickHouse/blob/97f2a2213e754ba25dabba4bc8ddf507cd67660c/tests/queries/0_stateless/00948_format_in_with_single_element.reference for an example.

**Comment by dgrr** [comment]
What are the naming conventions for the test scripts? I didn't find out on the wiki anything related with test name convention

**Comment by alexey-milovidov** [comment]
@dgrr Just keep it similar to other tests (most other tests are in lower_case).
I see that everything is alright.

**Comment by dgrr** [comment]
The tests show errors that didn't happen in my test cases

**Review by alexey-milovidov — APPROVED** [review]

**Pull request merged**
