### PR TITLE
Support merging finalized aggregation result from different servers on initiator node

### LINKED ISSUE #18275: Support running aggregation to final status on different servers and merge final result on initiator node for distributed query
**Scenario Description**
In some scenarios, data is written to different shards of one distributed table according to sharding key, eg. user_id.
When we read these data and do some aggregation functions on the distributed table, it may be expensive to read aggregation states from different servers and do the merge on initiator node, because the aggregation state may be huge.

One solution here is to set distributed_group_by_no_merge and get final aggregation result from different servers in case we are sure that the different server own different data for the aggregation functions.

The problem of the solution above is that the result returned to user may need further merging to generate global final result.

**Sample Case**
we have local table testtbl on 2 nodes (node-1 and node-2) : 
```
CREATE TABLE testtbl
(
    `id` String,
    `dt` String
)
ENGINE = MergeTree
PARTITION BY dt
ORDER BY id
```
and distributed table testtbl_dst : 
```
CREATE TABLE testtbl_dst
(
    `id` String,
    `dt` String
)
ENGINE = Distributed('test_cluster_two_shards', 'testdb', 'testtbl', sipHash64(id))
```
And we have data ('1', '2020-01-01') on node-1, and (2, '2020-01-01') on node-2.
if we run below SQL : 
```
SELECT
    dt,
    countDistinct(id) AS dst_cnt
FROM testtbl_dst
GROUP BY dt
SETTINGS distributed_group_by_no_merge = 1
```
we get : 
```
┌─dt─────────┬─dst_cnt─┐
│ 2020-01-01 │       1 │
└────────────┴─────────┘
┌─dt─────────┬─dst_cnt─┐
│ 2020-01-01 │       1 │
└────────────┴─────────┘
```
but what we want is ('2020-01-01', 2).

**Solution Description**
We can modify the IAggregationFunction interface a little bit to make it possible to support different ways of merging finalized result on initiator node for different aggregation functions.

### PR DESCRIPTION
**Pull request by fuwhu**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
support merging finalized aggregation result from different servers on initiator node, implemented for countDistinct.
fix #18275

### CODE REVIEW

**Comment by fuwhu** [comment]
@alexey-milovidov 
The failed checks seems not due to the code of this PR.
Could you please help on this ? thanks a lot in advance. :)

**Comment by fuwhu** [comment]
@alexey-milovidov @amosbird @akuzm 
Hi All,
could you please help review on this? or some other idea about this change ?

**Comment by fuwhu** [comment]
@CurtizJ 
I just fixed the conflict. Could you please help review this PR?

**Review by CurtizJ — CHANGES_REQUESTED** [review]
However, your test fails with segfault after merge with master.

**Pull request closed without merging**
