### PR TITLE
Speed up buildup of inverted index using absl::flat_hash_map

### PR DESCRIPTION
**Pull request by HarryLeeIBM**
The original inverted index building uses `std::unordered_map` for the posting list builder and FST builder. The fix uses `absl::flat_hash_map` to replace `std::unordered_map`. It can accelerate the building process by ca. 30%.

Performance test:

```
set allow_experimental_inverted_index=1;
set max_insert_threads=6;

-- Insert all rows from table "hackernews" to a inverted(ngrams=3) indexed table called "hn3_28":

CREATE TABLE hackernews ENGINE = MergeTree ORDER BY id
          AS SELECT * FROM url('https://datasets.clickhouse.com/hackernews.native.zst', Native,
          $$
          id UInt32,
          deleted UInt8,
          type Enum('story' = 1, 'comment' = 2, 'poll' = 3, 'pollopt' = 4, 'job' = 5),
          by LowCardinality(String),
          time DateTime,
          text String,
          dead UInt8,
          parent UInt32,
          poll UInt32,
          kids Array(UInt32),
          url String,
          score Int32,
          title String,
          parts Array(UInt32),
          descendants Int32
          $$);
CREATE TABLE hn3_28
(
id UInt32,
          deleted UInt8,
          type Enum('story' = 1, 'comment' = 2, 'poll' = 3, 'pollopt' = 4, 'job' = 5),
          by LowCardinality(String),
          time DateTime,
          text String,
          dead UInt8,
          parent UInt32,
          poll UInt32,
          kids Array(UInt32),
          url String,
          score Int32,
          title String,
          parts Array(UInt32),
          descendants Int32,
		  INDEX gin_index(text) TYPE inverted(3) GRANULARITY 1
) ENGINE = MergeTree ORDER BY id;

insert into hn3_28 select * from hackernews;
```

Before the fix, the result  of the insert statement is as following:
```
0 rows in set. Elapsed: 388.717 sec. Processed 28.74 million rows, 11.88 GB (73.93 thousand rows/s., 30.57 MB/s.)
Peak memory usage: 5.30 GiB.
```

After the fix, the result of the insert statement is as following:
```
0 rows in set. Elapsed: 269.037 sec. Processed 28.74 million rows, 11.88 GB (106.82 thousand rows/s., 44.17 MB/s.)
Peak memory usage: 5.28 GiB.
```

### Changelog category (leave one):
- Performance Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Improved the performance of inverted index creation by 30%. This was achieved by replacing `std::unordered_map` with `absl::flat_hash_map`.

### CODE REVIEW

**Comment by zhanglistar** [comment]
Is absl::flat_hash_map the fatest hashmap in this senario?

**Comment by HarryLeeIBM** [comment]
> Is absl::flat_hash_map the fatest hashmap in this senario?

I also tried several other options like std::map and absl::btree_map, so far absl::flat_hash_map by far is the fastest.

**Comment by HarryLeeIBM** [comment]
@rschu1ze , could you review this full text search PR? Thanks!

**Comment by robot-ch-test-poll4** [comment]
*This is an automated comment for commit 9e1208a79389172ee95523a02722d0791860589a with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/55210/9e1208a79389172ee95523a02722d0791860589a/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td><a href="https://github.com/ClickHouse/ClickHouse/actions/runs/6386246356">✅ success</a></td></tr>
<tbody>
</table>
</details>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/55210/9e1208a79389172ee95523a02722d0791860589a/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Comment by FrankChen021** [comment]
Hello @HarryLeeIBM , could u give me a brief explanation that why or how the flat_hash_map improves the performance in this case?

**Comment by HarryLeeIBM** [comment]
> Hello @HarryLeeIBM , could u give me a brief explanation that why or how the flat_hash_map improves the performance in this case?
I think flat_hash_map is very cache-friendly and according to [Martin Leitner-Ankerl's analysis](https://martin.ankerl.com/2022/08/27/hashmap-bench-01/#abslflat_hash_map-), flat_hash_map is very fast on searching in relatively big map and this matches the scenario where the inverted building process involves heavy string searching in GinIndexPostingsBuilderContainer.

**Pull request merged**
