### PR TITLE
Improve grace_hash join by reserving hash table's size

### PR DESCRIPTION
**Pull request by lgbo-ustc**
### Changelog category (leave one):

- Performance Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

* Improve grace_hash join by reserving hash table's size (resubmit)

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by lgbo-ustc** [comment]
@vdimir Would you make this ci run ? We notice that all the failures about adding joined blocks in a hash_join which is released is after the pr #49816. We add some debug codes in this new pr and try to make it reproduced.

**Comment by nickitat** [comment]
@lgbo-ustc Vladimir is on vacation, tag me if you need any help

**Comment by lgbo-ustc** [comment]
@nickitat will you trigger this ci ?

**Comment by lgbo-ustc** [comment]
@nickitat will you trigger this ci ?

**Comment by lgbo-ustc** [comment]
@vdimir  would you review this again?

**Review by nickitat — APPROVED** [review]
lgtm

**Comment by lgbo-ustc** [comment]
@nickitat could this be merged?

**Pull request merged**
