### PR TITLE
Add test for #48049

### LINKED ISSUE #48049: <Fatal> : Logical error: 'Can't set alias of test_table.COLUMNS(id)'.
https://s3.amazonaws.com/clickhouse-test-reports/48015/b143a1a3ebabb9333192fcbbf98bbcff791d1819/fuzzer_astfuzzerubsan/report.html
```
2023.03.27 00:27:38.802743 [ 146 ] {25b68353-d3ac-4ea3-bd62-d93c6808eff3} <Fatal> : Logical error: 'Can't set alias of test_table.COLUMNS(id)'.
2023.03.27 00:27:38.803147 [ 601 ] {} <Fatal> BaseDaemon: ########################################
2023.03.27 00:27:38.803180 [ 601 ] {} <Fatal> BaseDaemon: (version 23.3.1.1, build id: 8697861A7D2AED19F8853254E2F37E4C8E990383) (from thread 146) (query_id: 25b68353-d3ac-4ea3-bd62-d93c6808eff3) (query: DESCRIBE TABLE (SELECT test_table.COLUMNS(id) FROM test_table WHERE '2147483647')) Received signal Aborted (6)
2023.03.27 00:27:38.803199 [ 601 ] {} <Fatal> BaseDaemon: 
2023.03.27 00:27:38.803247 [ 601 ] {} <Fatal> BaseDaemon: Stack trace: 0x7ffaae94600b 0x7ffaae925859 0x22ffa0cb 0x22ffa9ce 0x18687547 0x2324f96b 0x2f57f151 0x2f55458c 0x2f53a401 0x2f0d4f5c 0x2f0cf505 0x2f0c9d0f 0x2f1b7ba8 0x2f1b432e 0x2f1b1e31 0x2f1b0483 0x2f1b4ecc 0x2f098cb5 0x2f63e91a 0x2f63a0cc 0x30a20c90 0x30a44776 0x31ec78db 0x31ec88b6 0x32134785 0x3212ff75 0x7ffaaeafd609 0x7ffaaea22133
2023.03.27 00:27:38.803280 [ 601 ] {} <Fatal> BaseDaemon: 3. gsignal @ 0x7ffaae94600b in ?
2023.03.27 00:27:38.803299 [ 601 ] {} <Fatal> BaseDaemon: 4. abort @ 0x7ffaae925859 in ?
2023.03.27 00:27:38.833272 [ 601 ] {} <Fatal> BaseDaemon: 5. ./build_docker/../src/Common/Exception.cpp:48: DB::abortOnFailedAssertion(String const&) @ 0x22ffa0cb in /workspace/clickhouse
2023.03.27 00:27:38.862079 [ 601 ] {} <Fatal> BaseDaemon: 6. ./build_docker/../src/Common/Exception.cpp:92: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x22ffa9ce in /workspace/clickhouse
2023.03.27 00:27:41.300112 [ 601 ] {} <Fatal> BaseDaemon: 7. DB::Exception::Exception<String>(int, FormatStringHelperImpl<std::type_identity<String>::type>, String&&) @ 0x18687547 in /workspace/clickhouse
2023.03.27 00:27:41.438428 [ 601 ] {} <Fatal> BaseDaemon: 8. ./build_docker/../src/Parsers/IAST.h:0: DB::IAST::setAlias(String const&) @ 0x2324f96b in /workspace/clickhouse
2023.03.27 00:27:41.465362 [ 601 ] {} <Fatal> BaseDaemon: 9.1. inlined from ./build_docker/../contrib/llvm-project/libcxx/include/string:1499: String::__is_long[abi:v15000]() const
2023.03.27 00:27:41.465399 [ 601 ] {} <Fatal> BaseDaemon: 9.2. inlined from ./build_docker/../contrib/llvm-project/libcxx/include/string:2333: ~basic_string
2023.03.27 00:27:41.465416 [ 601 ] {} <Fatal> BaseDaemon: 9. ./build_docker/../src/Interpreters/SubstituteColumnOptimizer.cpp:248: DB::SubstituteColumnOptimizer::perform() @ 0x2f57f151 in /workspace/clickhouse
2023.03.27 00:27:41.502054 [ 601 ] {} <Fatal> BaseDaemon: 10.1. inlined from ./build_docker/../src/Interpreters/SubstituteColumnOptimizer.h:19: ~SubstituteColumnOptimizer
2023.03.27 00:27:41.502115 [ 601 ] {} <Fatal> BaseDaemon: 10.2. inlined from ./build_docker/../src/Interpreters/TreeOptimizer.cpp:594: DB::(anonymous namespace)::optimizeSubstituteColumn(DB::ASTSelectQuery*, std::unordered_map<String, std::shared_ptr<DB::IAST>, std::hash<String>, std::equal_to<String>, std::allocator<std::pair<String const, std::shared_ptr<DB::IAST>>>>&, std::unordered_set<String, std::hash<String>, std::equal_to<String>, std::allocator<String>> const&, std::vector<DB::TableWithColumnNamesAndTypes, std::allocator<DB::TableWithColumnNamesAndTypes>> const&, std::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::shared_ptr<DB::IStorage const> const&)
2023.03.27 00:27:41.502140 [ 601 ] {} <Fatal> BaseDaemon: 10. ./build_docker/../src/Interpreters/TreeOptimizer.cpp:776: DB::TreeOptimizer::apply(std::shared_ptr<DB::IAST>&, DB::TreeRewriterResult&, std::vector<DB::TableWithColumnNamesAndTypes, std::allocator<DB::TableWithColumnNamesAndTypes>> const&, std::shared_ptr<DB::Context const>) @ 0x2f55458c in /workspace/clickhouse
2023.03.27 00:27:41.593911 [ 601 ] {} <Fatal> BaseDaemon: 11. ./build_docker/../src/Interpreters/TreeRewriter.cpp:0: DB::TreeRewriter::analyzeSelect(std::shared_ptr<DB::IAST>&, DB::TreeRewriterResult&&, DB::SelectQueryOptions const&, std::vector<DB::TableWithColumnNamesAndTypes, std::allocator<DB::TableWithColumnNamesAndTypes>> const&, std::vector<String, std::allocator<String>> const&, std::shared_ptr<DB::TableJoin>, bool, std::unordered_map<String, String, std::hash<String>, std::equal_to<String>, std::allocator<std::pair<String const, String>>>, std::unordered_map<String, String, std::hash<String>, std::equal_to<String>, std::allocator<std::pair<String const, String>>>) const @ 0x2f53a401 in /workspace/clickhouse
2023.03.27 00:27:41.752640 [ 601 ] {} <Fatal> BaseDaemon: 12. ./build_docker/../src/Interpreters/InterpreterSelectQuery.cpp:588: DB::InterpreterSelectQuery::InterpreterSelectQuery(std::shared_ptr<DB::IAST> const&, std::shared_ptr<DB::Context> const&, std::optional<DB::Pipe>, std::shared_ptr<DB::IStorage> const&, DB::SelectQueryOptions const&, std::vector<String, std::allocator<String>> const&, std::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::shared_ptr<DB::PreparedSets>)::$_4::operator()(bool) const @ 0x2f0d4f5c in /workspace/clickhouse
2023.03.27 00:27:41.902863 [ 601 ] {} <Fatal> BaseDaemon: 13. ./build_docker/../src/Interpreters/InterpreterSelectQuery.cpp:0: DB::InterpreterSelectQuery::InterpreterSelectQuery(std::shared_ptr<DB::IAST> const&, std::shared_ptr<DB::Context> const&, std::optional<DB::Pipe>, std::shared_ptr<DB::IStorage> const&, DB::SelectQueryOptions const&, std::vector<String, std::allocator<String>> const&, std::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::shared_ptr<DB::PreparedSets>) @ 0x2f0cf505 in /workspace/clickhouse
2023.03.27 00:27:42.057355 [ 601 ] {} <Fatal> BaseDaemon: 14. ./build_docker/../src/Interpreters/InterpreterSelectQuery.cpp:0: DB::InterpreterSelectQuery::InterpreterSelectQuery(std::shared_ptr<DB::IAST> const&, std::shared_ptr<DB::Context> const&, DB::SelectQueryOptions const&, std::vector<String, std::allocator<String>> const&) @ 0x2f0c9d0f in /workspace/clickhouse
2023.03.27 00:27:42.123618 [ 601 ] {} <Fatal> BaseDaemon: 15. ./build_docker/../contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:714: std::__unique_if<DB::InterpreterSelectQuery>::__unique_single std::make_unique[abi:v15000]<DB::InterpreterSelectQuery, std::shared_ptr<DB::IAST> const&, std::shared_ptr<DB::Context>&, DB::SelectQueryOptions&, std::vector<String, std::allocator<String>> const&>(std::shared_ptr<DB::IAST> const&, std::shared_ptr<DB::Context>&, DB::SelectQueryOptions&, std::vector<String, std::allocator<String>> const&) @ 0x2f1b7ba8 in /workspace/clickhouse
2023.03.27 00:27:42.179530 [ 601 ] {} <Fatal> BaseDaemon: 16.1. inlined from ./build_docker/../contrib/llvm-project/libcxx/include/__memory/compressed_pair.h:40: __compressed_pair_elem<DB::InterpreterSelectQuery *, void>
2023.03.27 00:27:42.179564 [ 601 ] {} <Fatal> BaseDaemon: 16.2. inlined from ./build_docker/../contrib/llvm-project/libcxx/include/__memory/compressed_pair.h:108: __compressed_pair<DB::InterpreterSelectQuery *, std::default_delete<DB::InterpreterSelectQuery> >
2023.03.27 00:27:42.179602 [ 601 ] {} <Fatal> BaseDaemon: 16.3. inlined from ./build_docker/../contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:211: unique_ptr<DB::InterpreterSelectQuery, std::default_delete<DB::InterpreterSelectQuery>, void, void>
2023.03.27 00:27:42.179638 [ 601 ] {} <Fatal> BaseDaemon: 16. ./build_docker/../src/Interpreters/InterpreterSelectWithUnionQuery.cpp:254: DB::InterpreterSelectWithUnionQuery::buildCurrentChildInterpreter(std::shared_ptr<DB::IAST> const&, std::vector<String, std::allocator<String>> const&) @ 0x2f1b432e in /workspace/clickhouse
2023.03.27 00:27:42.229043 [ 601 ] {} <Fatal> BaseDaemon: 17. ./build_docker/../src/Interpreters/InterpreterSelectWithUnionQuery.cpp:0: DB::InterpreterSelectWithUnionQuery::InterpreterSelectWithUnionQuery(std::shared_ptr<DB::IAST> const&, std::shared_ptr<DB::Context>, DB::SelectQueryOptions const&, std::vector<String, std::allocator<String>> const&) @ 0x2f1b1e31 in /workspace/clickhouse
2023.03.27 00:27:42.283865 [ 601 ] {} <Fatal> BaseDaemon: 18. ./build_docker/../src/Interpreters/InterpreterSelectWithUnionQuery.cpp:0: DB::InterpreterSelectWithUnionQuery::InterpreterSelectWithUnionQuery(std::shared_ptr<DB::IAST> const&, std::shared_ptr<DB::Context const>, DB::SelectQueryOptions const&, std::vector<String, std::allocator<String>> const&) @ 0x2f1b0483 in /workspace/clickhouse
2023.03.27 00:27:42.342231 [ 601 ] {} <Fatal> BaseDaemon: 19. ./build_docker/../src/Interpreters/InterpreterSelectWithUnionQuery.cpp:286: DB::InterpreterSelectWithUnionQuery::getSampleBlock(std::shared_ptr<DB::IAST> const&, std::shared_ptr<DB::Context const>, bool, bool) @ 0x2f1b4ecc in /workspace/clickhouse
2023.03.27 00:27:42.379652 [ 601 ] {} <Fatal> BaseDaemon: 20. [./build_docker/../src/Interpreters/InterpreterDescribeQuery.cpp:0: DB::InterpreterDescribeQuery::execute() @ 0x2f098cb5 in ](https://s3.amazonaws.com/clickhouse-test-reports/48015/b143a1a3ebabb9333192fcbbf98bbcff791d1819/fuzzer_astfuzzerubsan/report.html)/workspace/clickhouse
2023.03.27 00:27:42.460248 [ 601 ] {} <Fatal> BaseDaemon: 21. ./build_docker/../src/Interpreters/executeQuery.cpp:0: DB::executeQueryImpl(char const*, char const*, std::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, DB::ReadBuffer*) @ 0x2f63e91a in /workspace/clickhouse
2023.03.27 00:27:42.542617 [ 601 ] {} <Fatal> BaseDaemon: 22. ./build_docker/../src/Interpreters/executeQuery.cpp:1160: DB::executeQuery(String const&, std::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum) @ 0x2f63a0cc in /workspace/clickhouse
2023.03.27 00:27:42.618767 [ 601 ] {} <Fatal> BaseDaemon: 23. ./build_docker/../src/Server/TCPHandler.cpp:420: DB::TCPHandler::runImpl() @ 0x30a20c90 in /workspace/clickhouse
2023.03.27 00:27:42.729362 [ 601 ] {} <Fatal> BaseDaemon: 24. ./build_docker/../src/Server/TCPHandler.cpp:2039: DB::TCPHandler::run() @ 0x30a44776 in /workspace/clickhouse
2023.03.27 00:27:42.737444 [ 601 ] {} <Fatal> BaseDaemon: 25. ./build_docker/../base/poco/Net/src/TCPServerConnection.cpp:57: Poco::Net::TCPServerConnection::start() @ 0x31ec78db in /workspace/clickhouse
2023.03.27 00:27:42.749484 [ 601 ] {} <Fatal> BaseDaemon: 26.1. inlined from ./build_docker/../contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:302: std::unique_ptr<Poco::Net::TCPServerConnection, std::default_delete<Poco::Net::TCPServerConnection>>::reset[abi:v15000](Poco::Net::TCPServerConnection*)
2023.03.27 00:27:42.749522 [ 601 ] {} <Fatal> BaseDaemon: 26.2. inlined from ./build_docker/../contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:259: ~unique_ptr
2023.03.27 00:27:42.749560 [ 601 ] {} <Fatal> BaseDaemon: 26. ./build_docker/../base/poco/Net/src/TCPServerDispatcher.cpp:116: Poco::Net::TCPServerDispatcher::run() @ 0x31ec88b6 in /workspace/clickhouse
2023.03.27 00:27:42.758127 [ 601 ] {} <Fatal> BaseDaemon: 27. ./build_docker/../base/poco/Foundation/src/ThreadPool.cpp:202: Poco::PooledThread::run() @ 0x32134785 in /workspace/clickhouse
2023.03.27 00:27:42.766086 [ 601 ] {} <Fatal> BaseDaemon: 28. ./build_docker/../base/poco/Foundation/src/Thread_POSIX.cpp:0: Poco::ThreadImpl::runnableEntry(void*) @ 0x3212ff75 in /workspace/clickhouse
2023.03.27 00:27:42.766117 [ 601 ] {} <Fatal> BaseDaemon: 29. ? @ 0x7ffaaeafd609 in ?
2023.03.27 00:27:42.766160 [ 601 ] {} <Fatal> BaseDaemon: 30. __clone @ 0x7ffaaea22133 in ?
2023.03.27 00:27:42.766208 [ 601 ] {} <Fatal> BaseDaemon: Integrity check of the executable skipped because the reference checksum could not be read.
2023.03.27 00:34:05.317219 [ 137 ] {} <Fatal> Application: Child process was terminated by signal 6.
```

### PR DESCRIPTION
**Pull request by Algunenano**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
- Add test for #48049

### Documentation entry for user-facing changes

Closes #48049

### CODE REVIEW

**Comment by robot-clickhouse-ci-1** [comment]
*This is an automated comment for commit 160b6d5d041d183391b5e59dbd4cfbe4d8d09b15 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/63351/160b6d5d041d183391b5e59dbd4cfbe4d8d09b15/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

**Comment by Algunenano** [comment]
The fuzzer is detecting issues when running the query under `EXPLAIN SYNTAX`, since that uses the old analyzer.

**Review by yariks5s — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
@Algunenano, fuzzer has found an error.

**Comment by alexey-milovidov** [comment]
Reproduced in master:

```
milovidov-pc :) CREATE TABLE test_table
(
    id UInt64,
    value String
) ENGINE=TinyLog;

CREATE TABLE test_table
(
    `id` UInt64,
    `value` String
)
ENGINE = TinyLog

Query id: b6648101-08d3-433e-8543-7d8bb00a109d

Ok.

0 rows in set. Elapsed: 0.001 sec. 

milovidov-pc :) EXPLAIN SYNTAX WITH CAST(tuple(1), 'Tuple (value UInt64)') AS compound_value SELECT id, test_table.* APPLY (x -> compound_value.*) FROM test_table WHERE arrayMap(x -> toString(x) AS lambda, [NULL, 256, 257, NULL, NULL]) SETTINGS convert_query_to_cnf = true, optimize_using_constraints = true, optimize_substitute_columns = true

EXPLAIN SYNTAX
WITH CAST(tuple(1), 'Tuple (value UInt64)') AS compound_value
SELECT
    id,
    test_table.* APPLY (x -> compound_value.*)
FROM test_table
WHERE arrayMap(x -> toString(x) AS lambda, [NULL, 256, 257, NULL, NULL])
SETTINGS convert_query_to_cnf = true, optimize_using_constraints = true, optimize_substitute_columns = true

Query id: 779f944d-ed5a-4eb8-a931-23ba60d4e92c


Elapsed: 0.012 sec. 

Received exception:
Code: 49. DB::Exception: Can't set alias of compound_value.*: While processing WITH CAST(tuple(1), 'Tuple (value UInt64)') AS compound_value SELECT id AS id, compound_value.*, compound_value.* FROM test_table WHERE arrayMap(x -> toString(x) AS lambda, [NULL, 256, 257, NULL, NULL]) SETTINGS convert_query_to_cnf = true, optimize_using_constraints = true, optimize_substitute_columns = true. (LOGICAL_ERROR)
```

**Review by alexey-milovidov — APPROVED** [review]

**Comment by Algunenano** [comment]
> @Algunenano, fuzzer has found an error.

Yes, that's why I didn't merge it yet as I hadn't investigated properly what it was finding

**Pull request merged**
