### PR TITLE
Revert: fix: function filters with token-based text indexes

### PR DESCRIPTION
**Pull request by Algunenano**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
- Revert: fix: function filters with token-based text indexes

### Documentation entry for user-facing changes

Tests are broken in private and needs to be investigated. Reverting and will create a new PR to reintroduce them properly

### CODE REVIEW

**Comment by robot-ch-test-poll2** [comment]
*This is an automated comment for commit a53ce5637e2e6ce7fd5bd33f04b0d0e3d9b2dac0 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/64989/a53ce5637e2e6ce7fd5bd33f04b0d0e3d9b2dac0/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>A Sync</td><td>If it fails, ask a maintainer for help</td><td>⏳ pending</td></tr>
<tbody>
</table>
<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>Checks correctness of the PR's body</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

**Comment by tavplubix** [comment]
cc: @jkartseva

**Review by jkartseva — APPROVED** [review]
Looking at the [Cannot read file, because reader is not initialized. (NOT_INITIALIZED)](https://pastila.nl/?002508b0/efe8e87d0f00f9cea44c0ff6561e173b#tjI9j5+KLE6ubkOV0+py+w==) crash in private..

**Comment by jkartseva** [comment]
The reason is inverted indices do not work with packed part storage. I reproed the crash by setting `min_bytes_for_full_part_storage` to a non-zero value. 
It should be fixed by adding 'no-random-merge-tree-settings' tag to the test, I can file a pr

cc @rschu1ze

**Pull request closed without merging**
