### PR TITLE
Fix mac build documentation

### PR DESCRIPTION
**Pull request by nikitamikhaylov**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Documentation

#7970

### CODE REVIEW

**Comment by nikitamikhaylov** [comment]
Need to test it on real Mac.

**Comment by liukun4515** [comment]
I meet the same problem for [#7970 ](https://github.com/ClickHouse/ClickHouse/issues/7970), and test 
```
cmake .. -DCMAKE_CXX_COMPILER=`which clang++` -DCMAKE_C_COMPILER=`which clang`
```
in my mac

**Comment by liukun4515** [comment]
My clang version is 
```
pple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**Comment by liukun4515** [comment]
The Chinese docs should also be updated synchronously.
If Chinese is not easy for you, I would like to help you.

**Comment by kolen** [comment]
With this configuration I go further in compilation process, but then I get the following error:

```
[1194/4432] Building ASM object contrib/openssl-cmake/CMakeFiles/crypto.dir/__/openssl/crypto/aes/aesni-mb-x86_64.s.o
FAILED: contrib/openssl-cmake/CMakeFiles/crypto.dir/__/openssl/crypto/aes/aesni-mb-x86_64.s.o
/Library/Developer/CommandLineTools/usr/bin/clang -DAES_ASM -DBSAES_ASM -DECP_NISTZ256_ASM -DENGINESDIR=\"/usr/lib/engines-3\" -DGHASH_ASM -DKECCAK1600_ASM -DL_ENDIAN -DMD5_ASM -DMODULESDIR=\"/usr/local/lib/ossl-modules\" -DOPENSSLDIR=\"/etc/ssl\" -DOPENSSL_BN_ASM_GF2m -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_USE_NODELETE -DPOLY1305_ASM -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DVPAES_ASM -DWHIRLPOOL_ASM -DX25519_ASM -isystem ../contrib/openssl-cmake/linux_x86_64/include -isystem ../contrib/openssl-cmake/linux_x86_64/include_private -isystem ../contrib/openssl/include -isystem ../contrib/openssl/providers/common/include -isystem ../contrib/openssl/providers/implementations/include -isystem ../contrib/openssl/crypto -isystem ../contrib/openssl/crypto/include -isystem ../contrib/openssl/crypto/ec/curve448 -isystem ../contrib/openssl/crypto/ec/curve448/arch_32 -isystem ../contrib/openssl -isystem ../contrib/libcxx/include -isystem ../contrib/libcxxabi/include -O2 -g -DNDEBUG   -D OS_DARWIN -Wno-unused-command-line-argument -nostdinc++ -Wno-reserved-id-macro -Wno-ctad-maybe-unsupported -MD -MT contrib/openssl-cmake/CMakeFiles/crypto.dir/__/openssl/crypto/aes/aesni-mb-x86_64.s.o -MF contrib/openssl-cmake/CMakeFiles/crypto.dir/__/openssl/crypto/aes/aesni-mb-x86_64.s.o.d -o contrib/openssl-cmake/CMakeFiles/crypto.dir/__/openssl/crypto/aes/aesni-mb-x86_64.s.o -c contrib/openssl/crypto/aes/aesni-mb-x86_64.s
warning: unknown warning option '-Wno-ctad-maybe-unsupported'; did you mean '-Wno-unsupported-cb'? [-Wunknown-warning-option]
1 warning generated.
contrib/openssl/crypto/aes/aesni-mb-x86_64.s:6:1: error: unknown directive
.type aesni_multi_cbc_encrypt,@function
^
contrib/openssl/crypto/aes/aesni-mb-x86_64.s:7:8: error: invalid alignment value
.align 32
       ^
```

`clang` is used to build assembly code `contrib/openssl/crypto/aes/aesni-mb-x86_64.s`, which it cannot build for some reason

Adding ``` -DCMAKE_ASM_COMPILER=`which clang` ``` is meaningless, as it's already clang 😕

(I don't mean that this changeset should be paused until it builds for everyone, it's still better than before)

**Review by alexey-milovidov — APPROVED** [review]

**Pull request merged**
