### PR TITLE
Enable keep_free_space_bytes for the metadata storage.

### PR DESCRIPTION
**Pull request by MikhailBurdukov**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Added a new setting, `metadata_keep_free_space_bytes` to keep free space on the metadata storage disk.

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

<details>
    <summary>Modify your CI run</summary>

**NOTE:** If your merge the PR with modified CI you **MUST KNOW** what you are doing
**NOTE:** Checked options will be applied if set before CI RunConfig/PrepareRunConfig step

#### Include tests (required builds will be added automatically):
- [ ]  Fast test
- [ ]  Integration Tests
- [ ]  Stateless tests
- [ ]  Stateful tests
- [ ]  Unit tests
- [ ]  Performance tests
- [ ]  All with ASAN
- [ ]  All with TSAN
- [ ]  All with Analyzer
- [ ]  All with Azure
- [ ]  Add your option here

#### Exclude tests:
- [ ]  Fast test
- [ ]  Integration Tests
- [ ]  Stateless tests
- [ ]  Stateful tests
- [ ]  Performance tests
- [ ]  All with ASAN
- [ ]  All with TSAN
- [ ]  All with MSAN
- [ ]  All with UBSAN
- [ ]  All with Coverage
- [ ]  All with Aarch64
- [ ]  Add your option here

#### Extra options:
- [ ]  do not test (only style check)
- [ ]  disable merge-commit (no merge from master before tests)
- [ ]  disable CI cache (job reuse)

#### Only specified batches in multi-batch jobs:
- [ ]  1
- [ ]  2
- [ ]  3
- [ ]  4

</details>

### CODE REVIEW

**Comment by robot-ch-test-poll1** [comment]
*This is an automated comment for commit 1cf0863a25b980cb25daebf34839b95a79e1a482 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/64128/1cf0863a25b980cb25daebf34839b95a79e1a482/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

**Review by kssenii — APPROVED** [review]

**Comment by kssenii** [comment]
Please push some empty commit to restart the checks, the PR is not mergeable because of failed special build check, though the check failure looks unrelated:
```
src/CMakeFiles/dbms.dir/Functions/FunctionsConversion.cpp.o -MF src/CMakeFiles/dbms.dir/Functions/FunctionsConversion.cpp.o.d -o src/CMakeFiles/dbms.dir/Functions/FunctionsConversion.cpp.o -c /build/src/Functions/FunctionsConversion.cpp
May 20 21:22:13 sccache: warning: The server looks like it shut down unexpectedly, compiling locally instead
May 20 21:22:13 sccache: Compile terminated by signal 9
May 20 21:22:13 ninja: build stopped: subcommand failed.
```

**Comment by kssenii** [comment]
Please merge your branch with master branch, it should fix the clang-tidy build failure.

**Comment by MikhailBurdukov** [comment]
Will restart again :) 
```
May 22 16:30:51 sccache: error: Server startup failed: cache storage failed to read: Unexpected (temporary) at stat
May 22 16:30:51 
May 22 16:30:51 Context:
May 22 16:30:51    uri: https://s3.us-east-1.amazonaws.com/clickhouse-builds/ccache/sccache/.sccache_check
May 22 16:30:51    response: Parts { status: 500, 
```

**Comment by MikhailBurdukov** [comment]
@kssenii CI seems fine

**Comment by kssenii** [comment]
> Stateless tests (tsan, s3 storage) [1/5] — fail: 1

03023_zeros_generate_random_with_limit_progress_bar -- not related to changes

> Stress test (asan) — Found signal in gdb.log

https://github.com/ClickHouse/ClickHouse/issues/64297

> Mergeable Check — failed: A Sync

`A Sync` is fully green, looks like some problem with status update

**Pull request merged**
