### PR TITLE
Use disk operation to serialize and deserialize meta files of StorageFilelog

### PR DESCRIPTION
**Pull request by ucasfl**
### Changelog category (leave one):

- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Closes #43800.

### CODE REVIEW

**Review by Avogar — APPROVED** [review]
Looks OK, but smth strange with tests

**Comment by Avogar** [comment]
Seems like tests failures are related. Running test `02025_storage_filelog_virtual_col.sh` leads to `Memory limit (total) exceeded` errors in server

**Comment by ucasfl** [comment]
```
2022-12-11 20:10:26 [4e2c52ec262e] 2022.12.11 20:10:26.568404 [ 36853 ] {63563dbf-ec55-4dfb-bde4-db678a0494f9}  DB::StorageFileLog::StorageFileLog(const DB::StorageID &, DB::ContextPtr, const DB::ColumnsDescription &, const DB::String &, const DB::String &, const DB::String &, std::unique_ptr, const DB::String &, bool): Code: 624. DB::Exception: The file a.txt under store/801/801e78c1-5b43-4696-89aa-96194bc0992b/metadata is not a regular file when deserializing meta files. (BAD_FILE_TYPE), Stack trace (when copying this message, always include the lines below):
```

Why `a.txt` under metadata directory not a regular file?

**Comment by ucasfl** [comment]
Tests failed should not related.

**Comment by Avogar** [comment]
`AST fuzzer (ubsan)` - https://github.com/ClickHouse/ClickHouse/issues/44191

**Pull request merged**
