### PR TITLE
Fix bad markup of "Hardware benchmark" page

### PR DESCRIPTION
**Pull request by alexey-milovidov**
Changelog category (leave one):
- Documentation (changelog entry is not required)

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
The current hardware benchmark page is unusable, revert it back to normal.

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
@blinkov You have to explain.

**Comment by blinkov** [comment]
We're discussing it in chat.

**Comment by alexey-milovidov** [comment]
@blinkov Do you have any schedule to fix the ugly markup?

**Comment by alexey-milovidov** [comment]
I have fixed the ugly markup of the benchmark page.
It took more than two years, but better late than never.

The new page is located at https://benchmark.clickhouse.com/hardware/

**Pull request closed without merging**
