### PR TITLE
Add stateless tests with s3 storage with debug and tsan

### PR DESCRIPTION
**Pull request by kssenii**
Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by kssenii** [comment]
@Mergifyio update

**Comment by kssenii** [comment]
@Mergifyio update

**Comment by alesapin** [comment]
@mergifyio update

**Comment by kssenii** [comment]
@Mergifyio update

**Review by alexey-milovidov — APPROVED** [review]
LGTM (if it works)

**Comment by kssenii** [comment]
It works, but it is on always green mode now. Under tan 0 tests failed, but under debug 7 tests failed.

Screenshot 2022-08-04 at 14 03 01

Screenshot 2022-08-04 at 14 03 16

**Comment by kssenii** [comment]
test failures in debug does not look serious, I'll try to fix
```
01283_max_threads_simple_query_optimization
01524_do_not_merge_across_partitions_select_final
01323_too_many_threads_bug
00314_sample_factor_virtual_column
00090_union_race_conditions_1
02228_merge_tree_insert_memory_usage
02127_plus_before_float
```

**Comment by alexey-milovidov** [comment]
We need this :)

**Comment by alexey-milovidov** [comment]
All the new tests passed:

Stateless tests (debug, s3 storage) [2/3] — fail: 0, passed: 1438, skipped: 37
[Details](https://s3.amazonaws.com/clickhouse-test-reports/35262/a819f2c75b156481998f276b3e7edcad640c883a/stateless_tests__debug__s3_storage__[2/3].html)
@robot-clickhouse
Stateless tests (debug, s3 storage) [3/3] — fail: 0, passed: 1430, skipped: 27
[Details](https://s3.amazonaws.com/clickhouse-test-reports/35262/a819f2c75b156481998f276b3e7edcad640c883a/stateless_tests__debug__s3_storage__[3/3].html)
@robot-ch-test-poll
Stateless tests (thread, s3 storage) [2/3] — fail: 0, passed: 1438, skipped: 37
[Details](https://s3.amazonaws.com/clickhouse-test-reports/35262/a819f2c75b156481998f276b3e7edcad640c883a/stateless_tests__thread__s3_storage__[2/3].html)
@robot-clickhouse
Stateless tests (thread, s3 storage) [3/3] — fail: 0, passed: 1430, skipped: 27

**Comment by kssenii** [comment]
👀 oh, zero tests failed 

Screenshot 2022-09-05 at 16 13 14
Screenshot 2022-09-05 at 16 14 16

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
`thread` vs `tsan` in the check name.
Let's unify to `tsan`.

**Review by alexey-milovidov — APPROVED** [review]

**Pull request merged**
