### PR TITLE
Remove needless code duplication between `arrayROCAUC` and `arrrayAUCPR`

### PR DESCRIPTION
**Pull request by emmanuelsdias**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by emmanuelsdias** [comment]
Opening this PR as suggested by @yariks5s on https://github.com/ClickHouse/ClickHouse/pull/72073#issuecomment-2523699840

**Comment by robot-clickhouse-ci-1** [comment]
*This is an automated comment for commit a2dad7be45bcfba242a3650b5fd56b1c42a20c44 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/72950/a2dad7be45bcfba242a3650b5fd56b1c42a20c44/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Style check</td><td>Runs a set of checks to keep the code style clean. If some of tests failed, see the related log from the report</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/72950/a2dad7be45bcfba242a3650b5fd56b1c42a20c44/style_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Comment by emmanuelsdias** [comment]
I've expanded the description of the function on the docs and added a couple of links, as suggested by @rschu1ze [here](https://github.com/ClickHouse/ClickHouse/pull/72073#discussion_r1876828253). I wasn't sure how much to expand on it, so feel free to suggest changes or alter it.

**Review by rschu1ze — APPROVED** [review]

**Comment by emmanuelsdias** [comment]
Thanks a lot, @rschu1ze! The template does indeed prevent duplicating the codes, I had no idea that was possible =)

Could you take a look [here](https://github.com/ClickHouse/ClickHouse/pull/71910#issuecomment-2537925364) just so we can converge into a single solution? I was thinking of:

1. Keep `arrayAUC` and add `arrayAUCROC` as an alias.
2. Or rename the main function to `arrayAUCROC` and keep `arrayAUC` as an alias.
3. Have this new function be called `arrayAUCPR` (instead of `arrayAUCPr`).

Point no. 3 affects this PR, while 1 or 2 affect https://github.com/ClickHouse/ClickHouse/pull/71910.

Wdyt?

**Comment by rschu1ze** [comment]
Failures of performance tests `arrayAUCPR` and `arrayROCAUC` are expected as they have been renamed.

**Comment by emmanuelsdias** [comment]
Just to have an estimate here @rschu1ze, when will this change be available for the end-users? Is it on the upcoming release?

**Comment by clickgapai** [comment]
Hi @emmanuelsdias @rschu1ze — while reviewing this PR I found the following:

- **Bug (P1):** Missing `arrayPrAUC` alias breaks backward compatibility with v24.12.1 function name — https://github.com/ClickHouse/ClickHouse/issues/104788

Happy to discuss — close anything that's wrong or already addressed.

**Pull request merged**
