### PR TITLE
Distance/ Norm functions for array

### PR DESCRIPTION
**Pull request by qieqieplus**
### Changelog category (leave one):
- New Feature

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Related issue
 - #35101

Implement 
 - L1, L2, Linf, Cosine distance functions for array
 - L1, L2, Linf norm functions for array

Currently there is a lack of documentation, please check tests for usage.

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by qieqieplus** [comment]
The style check reports 
`All the submodules should be from https://github.com/`
But the official Eigen repository is moved to gitlab and mirror repo is deprecated.

**Comment by davenger** [comment]
PPC64 build failed with the following error:

May 12 13:33:43 FAILED: src/Functions/array/CMakeFiles/clickhouse_functions_array.dir/arrayNorm.cpp.o 
May 12 13:33:43 prlimit --as=10000000000 --data=5000000000 --cpu=1000 /usr/bin/ccache /usr/bin/clang++-13 --target=ppc64le-linux-gnu --sysroot=/build/cmake/linux/../../contrib/sysroot/linux-powerpc64le/powerpc64le-linux-gnu/libc  -DAWS_SDK_VERSION_MAJOR=1 -DAWS_SDK_VERSION_MINOR=7 -DAWS_SDK_VERSION_PATCH=231 -DBOOST_ASIO_HAS_STD_INVOKE_RESULT=1 -DBOOST_ASIO_STANDALONE=1 -DEIGEN_MPL2_ONLY -DENABLE_MULTITARGET_CODE=1 -DENABLE_OPENSSL_ENCRYPTION -DHAS_RESERVED_IDENTIFIER -DHAS_SUGGEST_DESTRUCTOR_OVERRIDE -DHAS_SUGGEST_OVERRIDE -DPOCO_ENABLE_CPP11 -DPOCO_HAVE_FD_EPOLL -DPOCO_OS_FAMILY_UNIX -DSTD_EXCEPTION_HAS_STACK_TRACE=1 -DWITH_COVERAGE=0 -DWITH_GZFILEOP -DZLIB_COMPAT -Iincludes/configs -I../src -Isrc -Isrc/Core/include -I../base/base/.. -Ibase/base/.. -I../contrib/cctz/include -I../base/pcg-random/. -I../contrib/miniselect/include -I../contrib/zstd/lib -I../src/Common/mysqlxx/. -isystem ../contrib/libcxx/include -isystem ../contrib/libcxx/src -isystem ../contrib/libcxxabi/include -isystem ../contrib/libunwind/include -isystem ../contrib/abseil-cpp -isystem ../contrib/croaring/cpp -isystem ../contrib/croaring/include -isystem ../contrib/cityhash102/include -isystem ../contrib/boost -isystem ../contrib/poco/Net/include -isystem ../contrib/poco/Foundation/include -isystem ../contrib/poco/NetSSL_OpenSSL/include -isystem ../contrib/poco/Crypto/include -isystem ../contrib/boringssl/include -isystem ../contrib/poco/Util/include -isystem ../contrib/poco/JSON/include -isystem ../contrib/poco/XML/include -isystem ../contrib/replxx/include -isystem ../contrib/fmtlib-cmake/../fmtlib/include -isystem ../contrib/magic_enum/include -isystem ../contrib/double-conversion -isystem ../contrib/dragonbox/include -isystem ../contrib/re2 -isystem contrib/re2-cmake -isystem ../contrib/zlib-ng -isystem contrib/zlib-ng-cmake -isystem ../contrib/pdqsort -isystem ../contrib/xz/src/liblzma/api -isystem ../contrib/aws-c-common/include -isystem ../contrib/aws-c-event-stream/include -isystem ../contrib/aws/aws-cpp-sdk-s3/include -isystem ../contrib/aws/aws-cpp-sdk-core/include -isystem contrib/aws-s3-cmake/include -isystem ../contrib/azure/sdk/core/azure-core/inc -isystem ../contrib/azure/sdk/identity/azure-identity/inc -isystem ../contrib/azure/sdk/storage/azure-storage-common/inc -isystem ../contrib/azure/sdk/storage/azure-storage-blobs/inc -isystem ../contrib/snappy -isystem contrib/snappy-cmake -isystem ../contrib/msgpack-c/include -isystem ../contrib/fast_float/include -isystem ../contrib/NuRaft/include -isystem contrib/mariadb-connector-c-cmake/include-public -isystem ../contrib/mariadb-connector-c/include -isystem ../contrib/mariadb-connector-c/libmariadb -isystem ../contrib/s2geometry/src -isystem ../contrib/AMQP-CPP/include -isystem ../contrib/AMQP-CPP -isystem ../contrib/libuv/include -isystem ../contrib/sqlite-amalgamation -isystem ../contrib/rocksdb/include -isystem ../contrib/libpqxx/include -isystem ../contrib/libpq -isystem ../contrib/libpq/include -isystem ../contrib/libstemmer_c/include -isystem ../contrib/wordnet-blast -isystem ../contrib/lemmagen-c/include -isystem ../contrib/consistent-hashing -isystem ../contrib/eigen --gcc-toolchain=/build/cmake/linux/../../contrib/sysroot/linux-powerpc64le --gcc-toolchain=/build/cmake/linux/../../contrib/sysroot/linux-powerpc64le -std=c++20 -fdiagnostics-color=always -Xclang -fuse-ctor-homing -fsized-deallocation  -gdwarf-aranges -pipe -maltivec -mcpu=power8 -D__SSE2__=1 -DNO_WARN_X86_INTRINSICS -mpopcnt -fasynchronous-unwind-tables -ffile-prefix-map=/build=. -falign-functions=32   -Wall -Wno-unused-command-line-argument  -fdiagnostics-absolute-paths -fstrict-vtable-pointers -fexperimental-new-pass-manager -Wextra -Wframe-larger-than=65536 -Wpedantic -Wno-vla-extension -Wno-zero-length-array -Wno-c11-extensions -Weverything -Wno-c++98-compat-pedantic -Wno-c++98-compat -Wno-c99-extensions -Wno-conversion -Wno-ctad-maybe-unsupported -Wno-deprecated-dynamic-exception-spec -Wno-disabled-macro-expansion -Wno-documentation-unknown-command -Wno-double-promotion -Wno-exit-time-destructors -Wno-float-equal -Wno-global-constructors -Wno-missing-prototypes -Wno-missing-variable-declarations -Wno-nested-anon-types -Wno-packed -Wno-padded -Wno-shift-sign-overflow -Wno-sign-conversion -Wno-switch-enum -Wno-undefined-func-template -Wno-unused-template -Wno-vla -Wno-weak-template-vtables -Wno-weak-vtables -O2 -g -DNDEBUG -O3 -g -gdwarf-4  -fno-pie   -D OS_LINUX -g0 -Werror -nostdinc++ -std=gnu++2a -MD -MT src/Functions/array/CMakeFiles/clickhouse_functions_array.dir/arrayNorm.cpp.o -MF src/Functions/array/CMakeFiles/clickhouse_functions_array.dir/arrayNorm.cpp.o.d -o src/Functions/array/CMakeFiles/clickhouse_functions_array.dir/arrayNorm.cpp.o -c ../src/Functions/array/arrayNorm.cpp
May 12 13:33:43 In file included from ../src/Functions/array/arrayNorm.cpp:5:
May 12 13:33:43 In file included from ../contrib/eigen/Eigen/Core:205:
May 12 13:33:43 /build/contrib/eigen/Eigen/src/Core/arch/SSE/PacketMath.h:507:7: error: couldn't allocate output register for constraint 'x'
May 12 13:33:43   asm("maxps %[a], %[res]" : [res] "+x" (res) : [a] "x" (a));
May 12 13:33:43       ^
May 12 13:33:43 /build/contrib/eigen/Eigen/src/Core/arch/SSE/PacketMath.h:507:7: error: couldn't allocate output register for constraint 'x'
May 12 13:33:43 /build/contrib/eigen/Eigen/src/Core/arch/SSE/PacketMath.h:507:7: error: couldn't allocate output register for constraint 'x'
May 12 13:33:43 /build/contrib/eigen/Eigen/src/Core/arch/SSE/PacketMath.h:507:7: error: couldn't allocate output register for constraint 'x'
May 12 13:33:43 /build/contrib/eigen/Eigen/src/Core/arch/SSE/PacketMath.h:526:7: error: couldn't allocate output register for constraint 'x'
May 12 13:33:43   asm("maxpd %[a], %[res]" : [res] "+x" (res) : [a] "x" (a));
May 12 13:33:43       ^
May 12 13:33:43 /build/contrib/eigen/Eigen/src/Core/arch/SSE/PacketMath.h:526:7: error: couldn't allocate output register for constraint 'x'
May 12 13:33:43 /build/contrib/eigen/Eigen/src/Core/arch/SSE/PacketMath.h:526:7: error: couldn't allocate output register for constraint 'x'
May 12 13:33:43 /build/contrib/eigen/Eigen/src/Core/arch/SSE/PacketMath.h:526:7: error: couldn't allocate output register for constraint 'x'
May 12 13:33:43 8 errors generated.

**Comment by davenger** [comment]
@mergifyio update

**Comment by qieqieplus** [comment]
I'll add array sizes check for short-cut fillMatrix, maybe sometime later to avoid code conflicts. @davenger

**Comment by davenger** [comment]
Stress failed in avro::DataFileReaderBase::readDataBlock
Maybe it is #33652 ?
Looks unrelated to the to this PR

**Review by davenger — APPROVED** [review]

**Comment by davenger** [comment]
We decided to rename arrayXXNorm and arrayXXDistance functions into XXNorm and XXDistance to match these functions for tuples. Committed in #37502

**Pull request merged**
