### PR TITLE
Query Cache: Try to fix bad cast from ColumnConst to ColumnVector<char8_t>

### LINKED ISSUE #49445: Bad cast from type DB::ColumnConst to DB::ColumnVector<char8_t>
https://s3.amazonaws.com/clickhouse-test-reports/49211/a08225d9ea4d0ca6ddf665a1b5b7fc69b2147137/stress_test__debug_.html

### PR DESCRIPTION
**Pull request by rschu1ze**
Hopefully resolves #49445

The query cache buffers query result chunks and eventually squashes them before insertion into the cache. Here, squashing failed because not all chunks were of the same type. Looks like chunks of the same underlying type (e.g. UInt8) in a query result can be of mixed const, sparse or low-cardinality type. Fixed this by always materializing the data regardless of the compression. Strange thing is that the failing query in the stress test (*) isn't able to reproduce the bug, and I haven't managed to trigger the issue otherwise --> no test case added.

(*) `SELECT 1 UNION ALL SELECT 1 INTERSECT SELECT 1`,  [here](https://s3.amazonaws.com/clickhouse-test-reports/0/18817517ed6f8849e3d979e10fbb273e0edf0eaa/stress_test__debug_/fatal_messages.txt)

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix assert in query cache with mixed const/non-const result chunks

### CODE REVIEW

**Comment by robot-clickhouse-ci-2** [comment]
This is an automated comment for commit 4e41bcd9beebcd106533b15aae2cb30e07b10699 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/50704/4e41bcd9beebcd106533b15aae2cb30e07b10699/ci_running.html)
The overall status of the commit is 🔴 failure

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🔴 failure</td></tr>
</table>

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
LGTM, but the tests have failed. Please fix the tests first.

Also,

> Bugfix validate check | Checks  that either a new test (functional or integration) or there some changed  tests that fail with the binary built on master branch

please add a new test.

**Comment by alexey-milovidov** [comment]
@rschu1ze add a test plz.

**Comment by alexey-milovidov** [comment]
Please add a test.

**Comment by rschu1ze** [comment]
Sorry, this PR got a bit rusty. Checking again locally now, in my first try two weeks ago I could not find a repro.

**Comment by alexey-milovidov** [comment]
It's ok to add a test that could only occasionally reproduce the issue.

**Comment by rschu1ze** [comment]
Update: As the original issue happened (sporadically) during stress testing, I isolated the bad query + test case, and ran it with query cache enabled + custom settings from the stress test overnight in a loop. Didn't reproduce and no other repro exists right now 😞 

There were a few new issues in CI:
- bad_cast in other (non-query-cache) locations during stress testing. All of them are about casts to ColumnLowCardinality (the original issue was a bad cast from ColumnConst). Could be related but not sure. I'll try to make the fix more minimal for now.
- the upgrade check in stress test failed ("Cached disk is allowed only on top of object storage. (BAD_ARGUMENTS)"). I think this is unrelated.

**Comment by rschu1ze** [comment]
ClickHouse Integration Tests (asan) [4/6]:
- test_multiple_disks/test.py::test_start_stop_moves[replicated]: #45404

ClickHouse Stateless Tests (release, Wide Parts Enabled):
- 02354_distributed_with_external_aggregation_memory_usage: #50703

ClickHouse Bugfix Validate Check for [PR](https://github.com/ClickHouse/ClickHouse/pull/50704):
- ... well, no repro exists but I am pretty sure that the PR fixes the issue.

**Pull request merged**
