### PR TITLE
Fix a bug that CORS headers are missing in some HTTP responses

### PR DESCRIPTION
**Pull request by FrankChen021**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in official stable or prestable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix a bug that CORS headers are missing in some HTTP responses

### Description

In current implementation, for HTTP POST requests, CORS headers are added after user authentication. If the authentication fails, the returned HTTP response has no CORS headers. This leads some front-end libs, such as axios, fail to process the response - they can't even get the http status nor the error message because the missed headers block them to do so.

To make the front-end projects correctly handle such 403 exceptions or in case of any exception raised before CORS headers are added, we need to make some adjustment to current CORS handling, that is adding these headers before a query is processed.

BTW, there is a very old setting `add_http_cors_header`, this setting does not work if the authentication fails. The contradiction is we can only get the user setting after the authentication but the CORS processing requires us to add headers before any processing.

Link to #29155 for better understanding.

### CODE REVIEW

**Comment by FrankChen021** [comment]
Looks like the failures in CI are not relevant to these changes.

**Review by yakov-olkhovskiy — APPROVED** [review]

**Comment by FrankChen021** [comment]
Hello @yakov-olkhovskiy Can this be merged?

**Comment by yakov-olkhovskiy** [comment]
@FrankChen021 sure, but let me rerun integration test

**Comment by FrankChen021** [comment]
Thanks you @yakov-olkhovskiy for the review.

**Comment by isublimity** [comment]
After this fix, Tabix can`t send GET query to CH server, because it cannot pass the ORIGIN header. 

If code like this, i think tabix work fine 


```
if (settings.add_http_cors_header ||  ( !request.get("Origin", "").empty() && !config.has("http_options_response")))
```

**Pull request merged**
