### PR TITLE
Performance test with AVX2

### PR DESCRIPTION
**Pull request by alexey-milovidov**
Changelog category (leave one):
- Not for changelog (changelog entry is not required)

This PR is to check - if we simply enable AVX2 what will be the difference in perf tests?
Hope it will get to CI server with AVX2 capable CPU.

It is not meant to be merged.

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
> Instruction check fail. The CPU does not support AVX2 instruction set.

Fast test have no luck to get into the right server. But at least our instruction check works perfectly!

**Comment by alexey-milovidov** [comment]
It cannot build on our CI machines, we don't have enough servers with AVX2.

**Comment by alexey-milovidov** [comment]
I will trigger the task manually to run on appropriate servers.

**Comment by alexey-milovidov** [comment]
@alesapin maybe you can help?

The build has finished successfully but it cannot be found in s3.

**Comment by fuwhu** [comment]
> @alesapin maybe you can help?
> 
> The build has finished successfully but it cannot be found in s3.

Hi Alexey,

Have you tested the performance difference of windowFunnel after this change ?
Per my observation, the performance bottle neck of the windowFunnel function seems be the memory store and read of data elements. Will AVX be helpful for such operations ?

**Comment by alexey-milovidov** [comment]
Most likely no - windowFunnel algorithm is too complex to be auto-vectorized by compiler.
There is also no much chance that it can be vectorized manually.

Looks like it can be optimized by careful tweaks in the algorithm and by looking at the most frequent special cases.
If you want to optimize it, you need to prepare (maybe obfuscated) datasets from production, so we can run model queries and check various changes.

**Comment by fuwhu** [comment]
> Most likely no - windowFunnel algorithm is too complex to be auto-vectorized by compiler.
> There is also no much chance that it can be vectorized manually.
> 
> Looks like it can be optimized by careful tweaks in the algorithm and by looking at the most frequent special cases.
> If you want to optimize it, you need to prepare (maybe obfuscated) datasets from production, so we can run model queries and check various changes.

Since the data is kind of sensitive, is it possible that we provide the flame graph and you can then give some advices on the optimization ?

**Comment by alexey-milovidov** [comment]
Performance optimizations require quick iterations on real datasets.
Maybe you can create obfuscated dataset?

Run `clickhouse-obfuscator --help` and follow the instruction.

You can have 100 bn records but to reproduce performance maybe some subset of a few million records can be enough?

**Comment by fuwhu** [comment]
> Performance optimizations require quick iterations on realistic datasets.
> Maybe you can create obfuscated dataset?
> 
> Run `clickhouse-obfuscator --help` and follow the instruction.
> 
> You can have 100 bn records but to reproduce performance maybe some subset of a few million records can be enough?

sure, let me check on this tool. thanks Alexey.

**Comment by fuwhu** [comment]
> Performance optimizations require quick iterations on realistic datasets.
> Maybe you can create obfuscated dataset?
> 
> Run `clickhouse-obfuscator --help` and follow the instruction.
> 
> You can have 100 bn records but to reproduce performance maybe some subset of a few million records can be enough?

@alexey-milovidov 
How shall i share the testing data ?

**Comment by alexey-milovidov** [comment]
If it's less than about 100MB compressed, you can send it to clickhouse-feedback@yandex-team.com in attachment.
If it's more, you can upload to Google Drive or Dropbox or https://disk.yandex.com/ or other file sharing service, and send a link to clickhouse-feedback@yandex-team.com.
If it's even large and does not fit these services, you can prepare a server that I can ssh into, send me the address to clickhouse-feedback@yandex-team.com and I will send my public key to log in. Also you can prepare HTTP service where I can download the file and send me a link. Also you can put data in Amazon S3 bucket.

**Comment by fuwhu** [comment]
> If it's less than about 100MB compressed, you can send it to [clickhouse-feedback@yandex-team.com](mailto:clickhouse-feedback@yandex-team.com) in attachment.
> If it's more, you can upload to Google Drive or Dropbox or https://disk.yandex.com/ or other file sharing service, and send a link to [clickhouse-feedback@yandex-team.com](mailto:clickhouse-feedback@yandex-team.com).
> If it's even larger and does not fit these services, you can prepare a server that I can ssh into, send me the address to [clickhouse-feedback@yandex-team.com](mailto:clickhouse-feedback@yandex-team.com) and I will send my public key to log in. Also you can prepare HTTP service where I can download the file and send me a link. Also you can put data in Amazon S3 bucket.

@alexey-milovidov 
Hi alexey, i just put the files in a github repo : https://github.com/fuwhu/file-sharing
you can download xaa, xab, xac, and then use the command below to get the original compressed file :
`cat xaa xab xac > out.tar.gz`

I already invited you to access the repo above, if you have any problem in accessing it, please let me know and i will try the file sharing service you mentioned above. 

Thanks a lot in advance for your patience and help.

**Comment by fuwhu** [comment]
> > If it's less than about 100MB compressed, you can send it to [clickhouse-feedback@yandex-team.com](mailto:clickhouse-feedback@yandex-team.com) in attachment.
> > If it's more, you can upload to Google Drive or Dropbox or https://disk.yandex.com/ or other file sharing service, and send a link to [clickhouse-feedback@yandex-team.com](mailto:clickhouse-feedback@yandex-team.com).
> > If it's even larger and does not fit these services, you can prepare a server that I can ssh into, send me the address to [clickhouse-feedback@yandex-team.com](mailto:clickhouse-feedback@yandex-team.com) and I will send my public key to log in. Also you can prepare HTTP service where I can download the file and send me a link. Also you can put data in Amazon S3 bucket.
> 
> @alexey-milovidov
> Hi alexey, i just put the files in a github repo : https://github.com/fuwhu/file-sharing
> you can download xaa, xab, xac, and then use the command below to get the original compressed file :
> `cat xaa xab xac > out.tar.gz`
> 
> And the file 'sample_queries.sql' in the repo is the SQLs that we need to run against the table. just FYI.
> 
> I already invited you to access the repo above, if you have any problem in accessing it, please let me know and i will try the file sharing service you mentioned above.
> 
> Thanks a lot in advance for your patience and help.

@alexey-milovidov 
Hi Alexey, have you got the files ?

**Comment by alexey-milovidov** [comment]
Yes, I've got the files.

**Comment by alexey-milovidov** [comment]
Here are performance results:

https://clickhouse-test-reports.s3.yandex.net/20001/967af339e1ca75143e32f3f4a5b255dd00f40427/performance_comparison/report.html

42 queries are faster, there are no slower queries.
For faster queries improvements about 1.5 times are typical.
The average difference across all queries is just about 1%.

**Pull request closed without merging**
