### PR TITLE
Revert Revert "Implementing new commands for keeper-client"

### PR DESCRIPTION
**Pull request by pufit**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Added a bunch of custom commands (mostly to make ClickHouse debugging easier).

- get_stat - returns the node's stat
- find_super_nodes - finds nodes with number of children larger than some threshold for the given path
- delete_stale_backups - deletes ClickHouse nodes used for backups that are now inactive
- find_big_family - returns the top nodes which have the biggest family - the total number of nodes in the whole subtree
- touch - creates new node with an empty string as value. Doesn't throw an exception if the node already exists

Original PR https://github.com/ClickHouse/ClickHouse/pull/51117

### CODE REVIEW

**Review by yariks5s — APPROVED** [review]
It seems like previous problems were solved, but isn't the `test_delete_stale_backups` still flaky?

**Comment by pufit** [comment]
> It seems like previous problems were solved, but isn't the `test_delete_stale_backups` still flaky?

Sorry, I missed your comment. No, it shouldn't be flaky anymore. The previous problem was that, for whatever reason, sometimes the keeper had a `/clickhouse` node created by default and sometimes hadn't. So I added `touch /clickhouse`

**Comment by pufit** [comment]
Here is the error log from the previous version https://s3.amazonaws.com/clickhouse-test-reports/0/561b094e69b0044fcd6b61966fb5a7fbfda16331/integration_tests__release__[4_4]/integration_run_parallel2_0.log

**Comment by yariks5s** [comment]
Okay, thanks for explaining.

**Pull request merged**
