### PR TITLE
fix align of AggregateFunctionDistinct

### PR DESCRIPTION
**Pull request by BiteTheDDDDt**
I'm not really sure if clickhouse needs this fix, but it looks like the original AggregateFunctionDistinct doesn't guarantee memory alignment for nested functions.

### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
change the prefix size of AggregateFunctionDistinct to make sure nested function data memory aligned

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Review by alexey-milovidov — COMMENTED** [review]
LGTM, but can we also construct an example query that will reproduce this issue with UBSan and add it to the tests?

**Comment by BiteTheDDDDt** [comment]
> LGTM, but can we also construct an example query that will reproduce this issue with UBSan and add it to the tests?

I don't know under what circumstances not alignment will cause an error, do you have any ideas?

**Review by CurtizJ — APPROVED** [review]
I also tried to come up with test, but didn't find any case where alignment can lead lead to crash or sanitizer report.

**Comment by CurtizJ** [comment]
Test failures are not related.

**Pull request merged**
