### PR TITLE
Fix logging in MergeTreeDataSelectExecutor for multiple threads (attach to thread group)

### PR DESCRIPTION
**Pull request by azat**
Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Fixes: #12589
Cc: @KochetovNicolai 
Cc: @bobrik 

<details>

HEAD:
- bad09ac00d1c2676a89effd3b9f51907f57b234d - v0
- a47814b2c20fd3a170d17a6d8ee615a5b719e19a - test fix
- eba14eb527c7bae3c84584e813d29077324eb0ff - merge with master
- 5eaf39d3faf0abdd425cca9b7ee5778b06aad716 - rebase against master
- 43af55b9a109279fea3147a95f9fef26824fdca0 - rebased against master after https://github.com/ClickHouse/ClickHouse/pull/13201#issuecomment-667646956

</details>

### CODE REVIEW

**Review by KochetovNicolai — APPROVED** [review]

**Comment by azat** [comment]
#12589 does not included into any release, so no need to mark it as `pr-bugfix`

**Comment by alexey-milovidov** [comment]
@azat Integration tests has to be investigated.

**Comment by alexey-milovidov** [comment]
@azat I reverted one accidential commit, let's merge with master.

**Comment by azat** [comment]
@alexey-milovidov Looks like CI hangs?

**Comment by azat** [comment]
Since CI hanged anyway, rebased against upstream/master

**Comment by azat** [comment]
>Functional stateless tests (debug) — fail: 0, passed: 0

```
Start clickhouse-server service: Poco::Exception. Code: 1000, e.code() = 2, e.displayText() = File not found: /etc/clickhouse-server/config.d/custom_settings_prefixes.xml (version 20.7.1.4248)
```

After #13013 merged, docker images updated, so all PRs should be rebased against master.

**Comment by azat** [comment]
>Fast test — fail: 1, passed: 1905, skipped: 227

Failed because the test runs twice:

```
2020.08.02 01:30:52.134708 [ 38587 ] {a02a8427-aeb1-44b0-9599-83e91b0b4b08} <Debug> executeQuery: (from [::1]:46614) SELECT 'Running test stateless/01323_too_many_threads_bug.sql from pid=18506';
2020.08.02 01:36:05.784053 [ 63974 ] {ff9d16d5-bbbc-4abb-9b95-8b629597228f} <Debug> executeQuery: (from [::1]:56440) SELECT 'Running test stateless/01323_too_many_threads_bug.sql from pid=63982';
```

And this is the test that uses query_log, so it will fail the second time (can be fixed, but there are tons of other tests that behaves the same way)

**Comment by azat** [comment]
>Failed because the test runs twice:

That was retries, the test failed both times

**Comment by azat** [comment]
>AST-based query fuzzer — Received signal 11

The server got SIGSEGV, due to large allocation that was wrapped to 0 - #13234

**Comment by azat** [comment]
>AST-based query fuzzer — Received signal 11

FWIW looks like now each PR may contain some failures of AST query fuzzer, @alexey-milovidov @akuzm  maybe it will be better to run it constantly in background, instead of for each PR? (at least until all existing issues will be fixed)

**Comment by alexey-milovidov** [comment]
> FWIW looks like now each PR may contain some failures of AST query fuzzer, @alexey-milovidov @akuzm maybe it will be better to run it constantly in background, instead of for each PR? (at least until all existing issues will be fixed)

Let's just fix all the issues.
We will also add longer runs for the new tests in every PR.

**Comment by azat** [comment]
>Functional stateless tests (unbundled) — fail: 1, passed: 2095, skipped: 45

`00834_kill_mutation` does not looks related, should be added to ci fest?

**Pull request merged**
