### PR TITLE
Analyzer: do not enable it for old servers in tests

### PR DESCRIPTION
**Pull request by novikd**
### Changelog category (leave one):

- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Fix integration tests with the analyzer. Do not try to enable `allow_experimental_analyzer` setting on old server versions.

### CODE REVIEW

**Comment by robot-ch-test-poll2** [comment]
This is an automated comment for commit 02ed17dfa54b46b6439401fffd1591d77b07e2b7 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/53053/02ed17dfa54b46b6439401fffd1591d77b07e2b7/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Comment by vdimir** [comment]
- [ ] test_replicating_constants/test.py::test_different_versions

**Review by qoega — APPROVED** [review]

**Review by vdimir — COMMENTED** [review]
Can't we only handle `tag` inside `add_instance`? E.g. disable analyzer if `tag` is passed or check particular value.

**Comment by novikd** [comment]
> 
Can't we only handle tag inside add_instance? E.g. disable analyzer if tag is passed or check particular value.

No, there are tests where we need to disable the analyzer on nodes that do not have a tag.

**Pull request merged**
