### PR TITLE
SerializationString improve performance

### PR DESCRIPTION
**Pull request by kitaisreal**
### Changelog category (leave one):
- Performance Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Improve performance of string serialization.

### CODE REVIEW

**Comment by kitaisreal** [comment]
Prepare table:
```
CREATE TABLE test_table (id UInt64, value String) ENGINE=ReplacingMergeTree ORDER BY (id) SETTINGS index_granularity = 32768;
INSERT INTO test_table SELECT number, number % 15000 FROM numbers(1500000000);
```

Before:
```
SELECT max(length(value))
FROM test_table
FORMAT `Null`

0 rows in set. Elapsed: 0.855 sec. Processed 1.50 billion rows, 19.89 GB (1.75 billion rows/s., 23.27 GB/s.)
Peak memory usage: 1.24 MiB.
```

After:
```
SELECT max(length(value))
FROM test_table
FORMAT `Null`

0 rows in set. Elapsed: 0.691 sec. Processed 1.50 billion rows, 19.89 GB (2.17 billion rows/s., 28.79 GB/s.)
Peak memory usage: 1.17 MiB.
```

**Comment by robot-ch-test-poll3** [comment]
*This is an automated comment for commit a0e186699cf447ea1c2233baa943f3a67a570e31 with description of existing statuses. It's updated for the latest CI running*

[❌ Click here](https://s3.amazonaws.com/clickhouse-test-reports/57717/a0e186699cf447ea1c2233baa943f3a67a570e31/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://github.com/ClickHouse/ClickHouse/blob/master/.github/PULL_REQUEST_TEMPLATE.md?plain=1">❌ failure</a></td></tr>
<tbody>
</table>

**Comment by alexey-milovidov** [comment]
Please add the changelog entry and merge with master.

**Review by alexey-milovidov — APPROVED** [review]
Looks like a clear win!

**Pull request merged**
