### PR TITLE
Add tests for primary key clear column

### PR DESCRIPTION
**Pull request by alesapin**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Build/Testing/Packaging Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Add a test for `ALTER TABLE CLEAR COLUMN` query for primary key columns.

### CODE REVIEW

**Review by alexey-milovidov — COMMENTED** [review]
Ok

... but I remember the use case that Kirill Shvakov @kshvakov told on the meetup:
You can safely clear the last column of primary key. It will not affect the order of data. But after that, the data will be aggregated in SummingMergeTree/AggregatingMergeTree.

**Review by alexey-milovidov — APPROVED** [review]
If it's already forbidden, maybe we can just forget about this use case.

**Comment by alexey-milovidov** [comment]
Do you remeber when it was started to be forbidden?

**Comment by alesapin** [comment]
> Ok
> 
> ... but I remember the use case that Kirill Shvakov @kshvakov told on the meetup:
> You can safely clear the last column of primary key. It will not affect the order of data. But after that, the data will be aggregated in SummingMergeTree/AggregatingMergeTree.

Actually it's a strange and dangerous use case. Neither old alter nor new mutations alter is touching `primary.idx`. So after we clear (actually drop) column of the primary key, we will get inconsistency between `primary.idx` and columns in part. I think if we, detach/attach such part we will get an error https://github.com/clickhouse/ClickHouse/blob/master/src/Storages/MergeTree/IMergeTreeDataPart.cpp#L471.

**Pull request merged**
