### PR TITLE
Speedup avg and sumCount aggregate functions

### LINKED ISSUE #31628: avg/sumCount doesn't have optimization for Nullable/-If combinator like count/sum
**Describe the situation**
avg/sumCount function doesn't have optimizations similar to count/sum

**How to reproduce**
ClickHouse 21.12

```
SELECT avgIf(key, key != -1)
FROM
(
    SELECT materialize(1) AS key
    FROM numbers(100000000)
)

Query id: 73197ca1-026c-4f50-932c-1b44ed744581

┌─avgIf(key, notEquals(key, -1))─┐
│                              1 │
└────────────────────────────────┘

1 rows in set. Elapsed: 0.838 sec. Processed 100.03 million rows, 800.21 MB (119.33 million rows/s., 954.67 MB/s.)

SELECT avgIf(key, key != -1)
FROM
(
    SELECT materialize(toNullable(1)) AS key
    FROM numbers(100000000)
)

Query id: 4ac5d052-9243-42fa-9f7d-e2984cebb2c8

┌─avgIf(key, notEquals(key, -1))─┐
│                              1 │
└────────────────────────────────┘

1 rows in set. Elapsed: 0.889 sec. Processed 100.03 million rows, 800.21 MB (112.56 million rows/s., 900.52 MB/s.)

SELECT avg(key)
FROM
(
    SELECT materialize(toNullable(1)) AS key
    FROM numbers(100000000)
)

Query id: 28856670-3f6b-4ce4-837b-8b4ee823fa44

┌─avg(key)─┐
│        1 │
└──────────┘

1 rows in set. Elapsed: 0.822 sec. Processed 100.03 million rows, 800.21 MB (121.63 million rows/s., 973.01 MB/s.)


SELECT sum(key) / count(key)
FROM
(
    SELECT materialize(toNullable(1)) AS key
    FROM numbers(100000000)
)

Query id: 402d6376-7957-4204-b445-d0264d36bc48

┌─divide(sum(key), count(key))─┐
│                            1 │
└──────────────────────────────┘

1 rows in set. Elapsed: 0.273 sec. Processed 100.03 million rows, 800.21 MB (366.37 million rows/s., 2.93 GB/s.)

SELECT sum(key) / count(key)
FROM
(
    SELECT materialize(toNullable(1)) AS key
    FROM numbers(100000000)
)
SETTINGS optimize_fuse_sum_count_avg = 1

Query id: 3ef60ed7-1954-4eaa-a65d-3c9e469fc0f1

┌─divide(tupleElement(sumCount(key), 1), tupleElement(sumCount(key), 2))─┐
│                                                                      1 │
└────────────────────────────────────────────────────────────────────────┘

1 rows in set. Elapsed: 0.847 sec. Processed 100.03 million rows, 800.21 MB (118.04 million rows/s., 944.36 MB/s.)
```

**Expected performance**
The performance of avg ~ sum+count

**Additional context**
Related
https://github.com/ClickHouse/ClickHouse/pull/26248
https://github.com/ClickHouse/ClickHouse/pull/28272

### PR DESCRIPTION
**Pull request by Algunenano**
Changelog category (leave one):
- Performance Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Speedup avg and sumCount aggregate functions

Detailed description / Documentation draft:

* Brings the performance improvements to `sum` (https://github.com/ClickHouse/ClickHouse/pull/26248 and https://github.com/ClickHouse/ClickHouse/pull/28272 and https://github.com/ClickHouse/ClickHouse/pull/28906) into `avg` and `sumCount`.
* Adds some extra performance tests to show some of the improvements (2-5x in most cases, but it depends on the load and so on).
* Adds some extra tests to avg and specially to sumCount to confirm behaviour (mostly in terms of what type is used to accumulate and what type is returned).
* `AggregateFunctionSumCount` now inherits from `AggregateFunctionAvg` which allows me to reuse the implementation of ::add, ::addBatchSinglePlace and ::addBatchSinglePlaceNotNull as it was identical.
 
* Closes https://github.com/ClickHouse/ClickHouse/issues/31628

### CODE REVIEW

**Comment by Algunenano** [comment]
In general performance looks good:

image

Some notes:
* I'm going to need to reduce the size of some of the tests to fix the `Some query of the test 'avg' is too slow to run. See the all queries report`.
* It complains about `synthetic_hardware_benchmark` getting slower. I've tested with the reldebug build from the PR and one from master and the performance is the same (at around ~5GB/s)
* There are many queries that seem to be affected, either positively or negatively, by this PR eventhough their code is untouched. My guess would be that all the extra code added via templates, which is quite a bit, might influence how the compiler lays out or optimizes the final build. I'm not sure how much, if anything, can be done there.

**Comment by Algunenano** [comment]
I've just realized that countBytesInFilter exists and it should be better than some of the loops that are added in this PR. I'll give it a try

**Comment by qoega** [comment]
>AggregateFunctionSumCount now inherits from AggregateFunctionAvg

Probably we can use better naming for parent class? SumCount does not look like 'avg' function.

**Comment by Algunenano** [comment]
Testing the change to use countBytesInFilter:

```sql
SELECT sumCountIf(n, n IS NOT NULL)
FROM
(
    SELECT number AS n
    FROM system.numbers
    LIMIT 10000000000
)
```

* Before this PR: Elapsed: 22.676 sec. Processed 9.98 billion rows, 79.81 GB (439.96 million rows/s., 3.52 GB/s.)
* With manual loop: Elapsed: 3.685 sec. Processed 9.79 billion rows, 78.29 GB (2.66 billion rows/s., 21.25 GB/s.)
* With countBytesInFilter: Elapsed: 2.872 sec. Processed 9.76 billion rows, 78.07 GB (3.40 billion rows/s., 27.19 GB/s.)



```sql
SELECT sumCountIf(n, n IS NOT NULL)
FROM
(
    SELECT toNullable(number) AS n
    FROM system.numbers
    LIMIT 10000000000
)
```

* Before this PR: 1 rows in set. Elapsed: 23.775 sec. Processed 9.98 billion rows, 79.82 GB (419.66 million rows/s., 3.36 GB/s.)
* With manual loop: 1 rows in set. Elapsed: 4.285 sec. Processed 9.82 billion rows, 78.53 GB (2.29 billion rows/s., 18.33 GB/s.)
* With countBytesInFilter: 1 rows in set. Elapsed: 3.506 sec. Processed 10.00 billion rows, 79.97 GB (2.85 billion rows/s., 22.81 GB/s.)

Technically speaking, the count could be done inside addManyConditional_internal but adding extra conditions inside the sum code seems like asking for trouble. Anyway, this is going from 3.5 GB/s to 27.2 GB/s for not-nullable type and from 3.3 to 22.8 for nullables and that seems good to me.

**Comment by Algunenano** [comment]
> Probably we can use better naming for parent class? SumCount does not look like 'avg' function.

Note that it was already inheriting from `AggregateFunctionAvgBase`, I "just" changed it from `AggregateFunctionAvgBase<AvgFieldType<T>, UInt64, AggregateFunctionSumCount<T>>` to `AggregateFunctionAvg<T>`.

I'm not sure what the parent class should be named since `AggregateFunctionAvg` literally implements avg() and `AggregateFunctionSumCount` now only inherits from it and changes the result type and output. I'm open to suggestions.

**Comment by CurtizJ** [comment]
> There are many queries that seem to be affected, either positively or negatively, by this PR eventhough their code is untouched.

Most of them like `logical_functions` test are often unstable. So. it's ok.

**Review by CurtizJ — APPROVED** [review]

**Pull request merged**
