### PR TITLE
Get rid of fs paths keeper

### PR DESCRIPTION
**Pull request by alesapin**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Get rid of very strange and redundant abstraction.

### CODE REVIEW

**Review by kssenii — APPROVED** [review]

**Comment by alesapin** [comment]
darwin build finished successfully (with tons of warnings) but reported error.

**Comment by alesapin** [comment]
`01171_mv_select_insert_isolation_long` -- @kssenii is fixing right now

**Comment by alesapin** [comment]
Mongo test in progress.

**Comment by alesapin** [comment]
Stress -- oom

**Pull request merged**
