### PR TITLE
Laplab update libunwind

### PR DESCRIPTION
**Pull request by alexey-milovidov**
Addition to #4828

### CODE REVIEW

**Comment by zhang2014** [comment]
Need help:
- I compiled with the `-DCMAKE_BUILD_TYPE=Debug -DUSE_GPERF=0  -DUSE_INTERNAL_UNWIND_LIBRARY=1`, the run `SELECT * FROM build_options;`, and got:
```
2019.07.08 17:07:55.943252 [ 55 ] {} <Error> BaseDaemon: ########################################
2019.07.08 17:07:55.943558 [ 55 ] {} <Error> BaseDaemon: (version 19.11.0) (from thread 44) Received signal Aborted (6).
2019.07.08 17:07:55.943637 [ 55 ] {} <Error> BaseDaemon: 
2019.07.08 17:07:56.150073 [ 55 ] {} <Error> BaseDaemon: 0. /data/dev/ClickHouse/build/dbms/programs/clickhouse-server(StackTrace::tryCapture()+0x34) [0x10dc7710]
1. /data/dev/ClickHouse/build/dbms/programs/clickhouse-server(StackTrace::StackTrace(ucontext const&)+0x28) [0x10dc75a0]
2. /data/dev/ClickHouse/build/dbms/programs/clickhouse-server() [0xb8ec51b]
3. /lib/x86_64-linux-gnu/libc.so.6(+0x354b0) [0x7f35d8e414b0]
4. /lib/x86_64-linux-gnu/libc.so.6(gsignal+0x38) [0x7f35d8e41428]
5. /lib/x86_64-linux-gnu/libc.so.6(abort+0x16a) [0x7f35d8e4302a]
6. /data/dev/ClickHouse/build/dbms/programs/clickhouse-server() [0xb8ec643]
7. /data/dev/ClickHouse/build/dbms/programs/clickhouse-server(__cxxabiv1::__terminate(void (*)())+0x6) [0x114e9fe6]
8. /data/dev/ClickHouse/build/dbms/programs/clickhouse-server() [0x11583539]
9. /data/dev/ClickHouse/build/dbms/programs/clickhouse-server(__gxx_personality_v0+0x2e8) [0x114f5688]
10. /data/dev/ClickHouse/build/dbms/programs/clickhouse-server() [0x10e7e1b8]
11. /data/dev/ClickHouse/build/dbms/programs/clickhouse-server(_Unwind_RaiseException+0xd3) [0x10e7e873]
12. /lib/x86_64-linux-gnu/libgcc_s.so.1(_Unwind_Resume_or_Rethrow+0x18d) [0x7f35d8c04fed]
13. /data/dev/ClickHouse/build/dbms/programs/clickhouse-server(__cxa_rethrow+0x3c) [0x114ea3fc]
14. /data/dev/ClickHouse/build/dbms/programs/clickhouse-server(DB::getCurrentExceptionMessage[abi:cxx11](bool, bool)+0x59) [0x105420a2]
15. /data/dev/ClickHouse/build/dbms/programs/clickhouse-server() [0xb8ec6a7]
16. /data/dev/ClickHouse/build/dbms/programs/clickhouse-server(__cxxabiv1::__terminate(void (*)())+0x6) [0x114e9fe6]
17. /data/dev/ClickHouse/build/dbms/programs/clickhouse-server() [0x11583539]
18. /data/dev/ClickHouse/build/dbms/programs/clickhouse-server(__gxx_personality_v0+0x2e8) [0x114f5688]
19. /data/dev/ClickHouse/build/dbms/programs/clickhouse-server() [0x10e7e1b8]
20. /data/dev/ClickHouse/build/dbms/programs/clickhouse-server(_Unwind_RaiseException+0xd3) [0x10e7e873]
21. /data/dev/ClickHouse/build/dbms/programs/clickhouse-server(__cxa_throw+0x37) [0x114ea3a7]
22. /data/dev/ClickHouse/build/dbms/programs/clickhouse-server(DB::Context::getTable(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const+0xbd) [0xf7c07bd]
23. /data/dev/ClickHouse/build/dbms/programs/clickhouse-server(DB::InterpreterSelectQuery::InterpreterSelectQuery(std::shared_ptr<DB::IAST> const&, DB::Context const&, std::shared_ptr<DB::IBlockInputStream> const&, std::shared_ptr<DB::IStorage> const&, DB::SelectQueryOptions const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)+0x7a2) [0xf9e1256]
24. /data/dev/ClickHouse/build/dbms/programs/clickhouse-server(DB::InterpreterSelectQuery::InterpreterSelectQuery(std::shared_ptr<DB::IAST> const&, DB::Context const&, DB::SelectQueryOptions const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)+0x7b) [0xf9e060b]
25. /data/dev/ClickHouse/build/dbms/programs/clickhouse-server(std::_MakeUniq<DB::InterpreterSelectQuery>::__single_object std::make_unique<DB::InterpreterSelectQuery, std::shared_ptr<DB::IAST>&, DB::Context&, DB::SelectQueryOptions const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&>(std::shared_ptr<DB::IAST>&, DB::Context&, DB::SelectQueryOptions const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)+0x82) [0xfed0cfe]
26. /data/dev/ClickHouse/build/dbms/programs/clickhouse-server(DB::InterpreterSelectWithUnionQuery::InterpreterSelectWithUnionQuery(std::shared_ptr<DB::IAST> const&, DB::Context const&, DB::SelectQueryOptions const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)+0x858) [0xfecf6fa]
27. /data/dev/ClickHouse/build/dbms/programs/clickhouse-server(std::_MakeUniq<DB::InterpreterSelectWithUnionQuery>::__single_object std::make_unique<DB::InterpreterSelectWithUnionQuery, std::shared_ptr<DB::IAST>&, DB::Context&, DB::SelectQueryOptions>(std::shared_ptr<DB::IAST>&, DB::Context&, DB::SelectQueryOptions&&)+0x8e) [0xf749a3c]
28. /data/dev/ClickHouse/build/dbms/programs/clickhouse-server(DB::InterpreterFactory::get(std::shared_ptr<DB::IAST>&, DB::Context&, DB::QueryProcessingStage::Enum)+0x143) [0xf7489fb]
29. /data/dev/ClickHouse/build/dbms/programs/clickhouse-server() [0xf836ef0]
30. /data/dev/ClickHouse/build/dbms/programs/clickhouse-server(DB::executeQuery(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, DB::Context&, bool, DB::QueryProcessingStage::Enum, bool)+0xd5) [0xf837db3]
31. /data/dev/ClickHouse/build/dbms/programs/clickhouse-server(DB::TCPHandler::runImpl()+0xc26) [0xb75d036]
```

**Comment by alexey-milovidov** [comment]
@zhang2014 It looks like build misconfiguration, 
because we should not link to `gcc_s`.

You can use static linkage (the default).

**Comment by alexey-milovidov** [comment]
@zhang2014 I've fixed this issue in https://github.com/yandex/ClickHouse/pull/5948

**Comment by zhang2014** [comment]
Thanks

**Pull request merged**
