### PR TITLE
Fix projection part removal with zero-copy replication

### PR DESCRIPTION
**Pull request by alesapin**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix redundant error message in the log when `MATERIALIZE`ing big projection in ReplicatedMergeTree with zero-copy replication.

### CODE REVIEW

**Comment by davenger** [comment]
This PR fixes
```
2022.11.08 06:48:03.396937 [ 135 ] {aeb59838-dc78-43e0-a046-61fd1c739de5::all_0_227_3_228} <Warning> default.testing (aeb59838-dc78-43e0-a046-61fd1c739de5): Projection part testing_url_332 should be removed by its parent all_0_227_3_228.
2022.11.08 06:48:03.398418 [ 135 ] {aeb59838-dc78-43e0-a046-61fd1c739de5::all_0_227_3_228} <Error> void DB::IMergeTreeDataPart::removeIfNeeded(): while removing part testing_url_332 with path store/aeb/aeb59838-dc78-43e0-a046-61fd1c739de5/tmp_mut_all_0_227_3_228/testing_url_332.tmp_proj/: Code: 233. DB::Exception: Unexpected part name: testing_url_332. (BAD_DATA_PART_NAME), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xce1893a in /usr/bin/clickhouse
1. ? @ 0x7fd9618 in /usr/bin/clickhouse
2. DB::MergeTreePartInfo::fromPartName(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, StrongTypedef<unsigned int, DB::MergeTreeDataFormatVersionTag>) @ 0x1311a9c8 in /usr/bin/clickhouse
3. DB::StorageReplicatedMergeTree::unlockSharedDataByID(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<zkutil::ZooKeeper>, DB::MergeTreeSettings const&, Poco::Logger*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, StrongTypedef<unsigned int, DB::MergeTreeDataFormatVersionTag>) @ 0x12cf8454 in /usr/bin/clickhouse
4. DB::StorageReplicatedMergeTree::unlockSharedData(DB::IMergeTreeDataPart const&) const @ 0x12c5a789 in /usr/bin/clickhouse
5. DB::IMergeTreeDataPart::canRemovePart() const @ 0x12f77d38 in /usr/bin/clickhouse
6. ? @ 0x12f83213 in /usr/bin/clickhouse
7. DB::DataPartStorageOnDisk::remove(std::__1::function<DB::CanRemoveDescription ()>&&, DB::MergeTreeDataPartChecksums const&, std::__1::list<DB::IDataPartStorage::ProjectionChecksums, std::__1::allocator<DB::IDataPartStorage::ProjectionChecksums> >, bool, DB::MergeTreeDataPartState, Poco::Logger*) @ 0x12f09d7d in /usr/bin/clickhouse
8. DB::IMergeTreeDataPart::remove() const @ 0x12f689ba in /usr/bin/clickhouse
9. DB::IMergeTreeDataPart::removeIfNeeded() @ 0x12f67e86 in /usr/bin/clickhouse
10. DB::MergeTreeDataPartWide::~MergeTreeDataPartWide() @ 0x1308a690 in /usr/bin/clickhouse
11. DB::FutureMergedMutatedPart::~FutureMergedMutatedPart()? @ 0x12d21f6f in /usr/bin/clickhouse
12. DB::MergeProjectionPartsTask::executeStep() ? @ 0x131b3a28 in /usr/bin/clickhouse
13. DB::MutateSomePartColumnsTask::executeStep() ? @ 0x131b8e2e in /usr/bin/clickhouse
14. DB::MutateFromLogEntryTask::executeInnerTask() ? @ 0x1319e4c3 in /usr/bin/clickhouse
15. DB::ReplicatedMergeMutateTaskBase::executeImpl() @ 0x131e1cc4 in /usr/bin/clickhouse
16. DB::ReplicatedMergeMutateTaskBase::executeStep() @ 0x131e0f22 in /usr/bin/clickhouse
17. DB::MergeTreeBackgroundExecutor<DB::MergeMutateRuntimeQueue>::routine(std::__1::shared_ptr<DB::TaskRuntimeData>) @ 0x7be898b in /usr/bin/clickhouse
18. DB::MergeTreeBackgroundExecutor<DB::MergeMutateRuntimeQueue>::threadFunction() @ 0x7be83d0 in /usr/bin/clickhouse
19. ThreadPoolImpl<ThreadFromGlobalPoolImpl<false> >::worker(std::__1::__list_iterator<ThreadFromGlobalPoolImpl<false>, void*>) @ 0xced7a2c in /usr/bin/clickhouse
20. void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false> >::scheduleImpl<void>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()>(void&&)::'lambda'(), void ()> >(std::__1::__function::__policy_storage const*) @ 0xceda7b7 in /usr/bin/clickhouse
21. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xced3f4c in /usr/bin/clickhouse
22. ? @ 0xced96be in /usr/bin/clickhouse
23. ? @ 0x7efcf8bf4609 in ?
24. clone @ 0x7efcf8b19133 in ?
 (version 22.10.1.17597 (official build))

```

**Comment by MaXal** [comment]
> Fix redundant error message 

Does it mean that the message in the log: `0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xce1893a in /usr/bin/clickhouse
` doesn't indicate any real problem?

I'm asking since we have some issues with fetching data from Clickhouse and I see this message in the logs and so thought that this is a reason of broken fetches.

**Comment by davenger** [comment]
> 0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xce1893a in /usr/bin/clickhouse

@MaXal the line above will be present in log for pretty much any error - it is just a first frame of callstack when an exception is thrown.
This PR fixes the issue when that produces log messages like 
```
2022.11.08 06:48:03.396937 [ 135 ] {aeb59838-dc78-43e0-a046-61fd1c739de5::all_0_227_3_228} <Warning> default.testing (aeb59838-dc78-43e0-a046-61fd1c739de5): Projection part testing_url_332 should be removed by its parent all_0_227_3_228.
2022.11.08 06:48:03.398418 [ 135 ] {aeb59838-dc78-43e0-a046-61fd1c739de5::all_0_227_3_228} <Error> void DB::IMergeTreeDataPart::removeIfNeeded(): while removing part testing_url_332 with path store/aeb/aeb59838-dc78-43e0-a046-61fd1c739de5/tmp_mut_all_0_227_3_228/testing_url_332.tmp_proj/: Code: 233. DB::Exception: Unexpected part name: testing_url_332. (BAD_DATA_PART_NAME), Stack trace (when copying this message, always include the lines below):
```

**Review by davenger — APPROVED** [review]

**Comment by alesapin** [comment]
Flaky check is too strict. This test works less than 60 seconds if you don't run it in 100 threads.

**Comment by alesapin** [comment]
Tests ok

**Comment by KochetovNicolai** [comment]
the test is flaky
https://s3.amazonaws.com/clickhouse-test-reports/42829/0261ff509575433607c7bab06b5bb0301ede4899/fast_test.html

**Pull request merged**
