### PR TITLE
Add 00002_log_and_exception_messages_formatting back

### PR DESCRIPTION
**Pull request by tavplubix**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
It looks like this test cannot work if it runs among the first tests.

**Comment by tavplubix** [comment]
> It looks like this test cannot work if it runs among the first tests.

Yes, that's why it's named `00002_` and marked as `no-parallel` so `clickhouse-test` will run it in the end. I can make it a part of `clickhouse-test` itself (to guarantee that we always run it after all tests) if you insist, but an `.sql` file is much simpler than a bunch of python functions.

**Comment by tavplubix** [comment]
Integration tests (tsan) [2/6] - https://github.com/ClickHouse/ClickHouse/issues/45960
Integration tests (tsan) [4/6] - https://github.com/ClickHouse/ClickHouse/pull/46242
Integration tests (tsan) [6/6] - https://github.com/ClickHouse/ClickHouse/pull/46243
Stateless tests (asan) [1/4] - https://github.com/ClickHouse/ClickHouse/pull/46245
Stateless tests flaky check (asan) - expected (see the comments above)

**Comment by alexey-milovidov** [comment]
We can make a directly near 0_stateless, 1_stateful, named `after`.

**Pull request merged**
