### PR TITLE
fix error message

### LINKED ISSUE #62580: Improperly formatted error when adding an index for nonexistent column.
**Describe the unexpected behaviour**
The error message when adding an index for a nonexistent column repeats the column name too many times.

**How to reproduce**
Any version
fiddle: https://fiddle.clickhouse.com/b11fc39f-e320-4dda-8821-41e17bb6d612

```
ALTER TABLE users ADD INDEX heightidx height TYPE bloom_filter;

Received exception from server (version 24.3.2):
Code: 47. DB::Exception: Received from localhost:9000. DB::Exception: Missing columns: 'height' while processing query: 'height', required columns: 'height' 'height'. (UNKNOWN_IDENTIFIER)
(query: ALTER TABLE users ADD INDEX heightidx height TYPE bloom_filter;)
```
'height' appears 4 times in the above message, twice in a row at the end.

**Expected behavior**
Error message should be formatted better.

### PR DESCRIPTION
**Pull request by HowePa**
resolve #62580
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
...

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

---
### Modify your CI run:
**NOTE:** If your merge the PR with modified CI you **MUST KNOW** what you are doing
**NOTE:** Checked options will be applied if set before CI RunConfig/PrepareRunConfig step

#### Include tests (required builds will be added automatically):
- [ ]  Fast test
- [ ]  Integration Tests
- [ ]  Stateless tests
- [ ]  Stateful tests
- [ ]  Unit tests
- [ ]  Performance tests
- [ ]  All with ASAN
- [ ]  All with TSAN
- [ ]  All with Analyzer
- [ ]  Add your option here

#### Exclude tests:
- [ ]  Fast test
- [ ]  Integration Tests
- [ ]  Stateless tests
- [ ]  Stateful tests
- [ ]  Performance tests
- [ ]  All with ASAN
- [ ]  All with TSAN
- [ ]  All with MSAN
- [ ]  All with UBSAN
- [ ]  All with Coverage
- [ ]  All with Aarch64
- [ ]  Add your option here

#### Extra options:
- [ ]  do not test (only style check)
- [ ]  disable merge-commit (no merge from master before tests)
- [ ]  disable CI cache (job reuse)

#### Only specified batches in multi-batch jobs:
- [ ]  1
- [ ]  2
- [ ]  3
- [ ]  4

### CODE REVIEW

**Comment by robot-ch-test-poll3** [comment]
*This is an automated comment for commit 78d53412ae4590eba1ee5b0053c96104ca3b32f7 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/62581/78d53412ae4590eba1ee5b0053c96104ca3b32f7/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

**Review by yariks5s — CHANGES_REQUESTED** [review]
This solution is not working, you can check it locally. I suppose that there is something wrong with the part: `queryToString(query)` on l.1198

upd: it'll be good if you add a test case showing that the exception message is correct once the problem with query is fixed

**Comment by HowePa** [comment]
Note: need to modify `"while processing query: {query_str}"`

Previous output

```
ALTER TABLE users
    (ADD INDEX heightidx height TYPE bloom_filter GRANULARITY 1)

Query id: 373a2a5b-bc9d-429c-bfc3-69c118d72ca1


Elapsed: 0.015 sec.

Received exception from server (version 24.4.1):
Code: 47. DB::Exception: Received from localhost:9000. DB::Exception: Missing columns: 'height' while processing query: 'height', required columns: 'height' 'height'. (UNKNOWN_IDENTIFIER)
```


Commit 1 output

```
ALTER TABLE users
    (ADD INDEX heightidx height TYPE bloom_filter GRANULARITY 1)

Query id: b401e037-1006-43aa-9736-5d4019ed4942


Elapsed: 0.015 sec.

Received exception from server (version 24.4.1):
Code: 47. DB::Exception: Received from localhost:9000. DB::Exception: Missing columns: 'height' while processing query: 'height', required columns: 'height', source columns:  'age' 'name' 'uid'. (UNKNOWN_IDENTIFIER)
```

**Comment by yariks5s** [comment]
Yes, that is what I meant, the `current columns` part works good now, but the `query` part need to be fixed as well

**Comment by HowePa** [comment]
This problem is caused by the incomplete AST passed to `TreeRewriter::anaylze()`.  
Specifically, from `InterpreterAlterQuery` => `AlterCommand` => `IndexDescription`, the query was deconstructed three times through the pipeline. The same problem also happens in many places, for example, `src/storage/XXXDescription.cpp`.

image

To solve this problem, many of the intermediate steps need to change if pass the whole query instead. Or is there any other way?

**Comment by yariks5s** [comment]
> To solve this problem, many of the intermediate steps need to change if pass the whole query instead. Or is there any other way?

Passing the whole query can be unnecessary. I suppose that we need to pass at least the query in the current state + provide the ability to format the query for exceptions. If I will have other ideas later, I will write it here🙂

**Comment by HowePa** [comment]
Maybe add `ASTPtr parent` in `IAST.h` so there is a way to get the whole query.  At least it's a small change.  :confused:

**Pull request closed without merging**
