### PR TITLE
JSONExtract String or Raw

### PR DESCRIPTION
**Pull request by amosbird**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):

- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Allow extract non-string element as string using JSONExtract. This is for https://github.com/ClickHouse/ClickHouse/issues/25414

Detailed description / Documentation draft:

.

### CODE REVIEW

**Comment by Avogar** [comment]
The changes also affect `JSONExtractKeysAndValues` function:
```sql
SELECT JSONExtractKeysAndValues('{"a": "string", "b": [1, 2]}', 'String') = [('a','string'),('b','[1,2]')]
```
Do we really want such behaviour?

**Comment by amosbird** [comment]
> Do we really want such behaviour?

Looks ok to me)

**Comment by Avogar** [comment]
Ok, let's fix tests and merge it

**Review by Avogar — APPROVED** [review]

**Comment by filimonov** [comment]
The main problem in that implementation is ambiguity of
```
{"a": "{}", "b": {} }
```

And lack of possibility to extract string field with surrounding quotes (to have always valid sub-json, which can be parsed)

**Comment by alexey-milovidov** [comment]
@filimonov This is what JSONExtractRaw for.

**Comment by filimonov** [comment]
> @filimonov This is what JSONExtractRaw for.

Check #25414

**Comment by Avogar** [comment]
@filimonov maybe you have an idea how to solve this ambiguity? One of the possible solution is to add new data type RawString, but this is overkill I think.

**Comment by amosbird** [comment]
> @filimonov maybe you have an idea how to solve this ambiguity? One of the possible solution is to add new data type RawString, but this is overkill I think.

It's also possible to give a different name like `JSONExtractWithRawString`

**Comment by filimonov** [comment]
> > @filimonov maybe you have an idea how to solve this ambiguity? One of the possible solution is to add new data type RawString, but this is overkill I think.
> 
> It's also possible to give a different name like `JSONExtractWithRawString`. However, I don't understand the impact of this ambiguity. What would break?

Maybe it's not 

> > @filimonov maybe you have an idea how to solve this ambiguity? One of the possible solution is to add new data type RawString, but this is overkill I think.
> 
> It's also possible to give a different name like `JSONExtractWithRawString`. However, I don't understand the impact of this ambiguity. What would break?

For ex. things like
```
with '{a:{b:1}}' as json
Select if(JSONExtract(json, 'a'), JSONExtract(json, 'a'), JSONExtract(json, 'a.b'))
```

```

**Comment by alexey-milovidov** [comment]
@mergifyio update

**Comment by filimonov** [comment]
That needs a clear documentation. Also a note in changelog.

**Comment by wangqinghuan** [comment]
This change does not affect JSONExtractString(). Could we keep same behavior in all JSONExtract String function？ @amosbird

**Pull request merged**
