### PR TITLE
Fix memory leak in StorageHDFS

### LINKED ISSUE #57819: Memory leak in StorageHDFS (test_storage_hdfs)
**Describe the bug**
[A link to the report](https://s3.amazonaws.com/clickhouse-test-reports/57811/090d412d7cc37104ba90355c880a357fbd34e091/integration_tests__asan__[3_4]/integration_run_parallel5_0.log)

```
E           Exception: Sanitizer assert found for instance =================================================================
E           ==1==ERROR: LeakSanitizer: detected memory leaks
E           
E           Direct leak of 36 byte(s) in 1 object(s) allocated from:
E               #0 0x5634da5e8d5d in operator new[](unsigned long) (/usr/bin/clickhouse+0xa88ed5d) (BuildId: 2418d44073b11d3b0f437855a0f1dd6bd8d1ce2b)
E               #1 0x56350dabc20e in Strdup(char const*) build_docker/./contrib/libhdfs3/src/client/Hdfs.cpp:88:21
E               #2 0x56350dabc20e in ConstructHdfsFileInfo(hdfsFileInfo*, std::__1::vector<Hdfs::FileStatus, std::__1::allocator<Hdfs::FileStatus>> const&) build_docker/./contrib/libhdfs3/src/client/Hdfs.cpp:1055:26
E               #3 0x56350dabcdec in hdfsGetPathInfo build_docker/./contrib/libhdfs3/src/client/Hdfs.cpp:1100:9
E               #4 0x5634fb360e56 in DB::(anonymous namespace)::LSWithRegexpMatching(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::unique_ptr<HdfsFileSystemInternalWrapper, DB::detail::HDFSFsDeleter> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) build_docker/./src/Storages/HDFS/StorageHDFS.cpp:94:28
E               #5 0x5634fb34ff22 in DB::(anonymous namespace)::getPathsList(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::shared_ptr<DB::Context const>) build_docker/./src/Storages/HDFS/StorageHDFS.cpp:182:32
E               #6 0x5634fb34e343 in DB::StorageHDFS::getTableStructureFromData(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::shared_ptr<DB::Context const>) build_docker/./src/Storages/HDFS/StorageHDFS.cpp:397:28
E               #7 0x5634f970fa73 in DB::TableFunctionHDFS::getActualTableStructure(std::__1::shared_ptr<DB::Context const>, bool) const build_docker/./src/TableFunctions/TableFunctionHDFS.cpp:36:16
E               #8 0x5634fec93705 in DB::InterpreterDescribeQuery::fillColumnsFromTableFunction(DB::ASTTableExpression const&) build_docker/./src/Interpreters/InterpreterDescribeQuery.cpp:147:52
E               #9 0x5634fec90bc0 in DB::InterpreterDescribeQuery::execute() build_docker/./src/Interpreters/InterpreterDescribeQuery.cpp:89:9
E               #10 0x5634ffa24ec5 in DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum, DB::ReadBuffer*) build_docker/./src/Interpreters/executeQuery.cpp:1109:40
E               #11 0x5634ffa1b609 in DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum) build_docker/./src/Interpreters/executeQuery.cpp:1287:26
E               #12 0x56350297dd28 in DB::TCPHandler::runImpl() build_docker/./src/Server/TCPHandler.cpp:498:54
E               #13 0x5635029c24af in DB::TCPHandler::run() build_docker/./src/Server/TCPHandler.cpp:2292:9
E               #14 0x56350a6a46ee in Poco::Net::TCPServerConnection::start() build_docker/./base/poco/Net/src/TCPServerConnection.cpp:43:3
E               #15 0x56350a6a5416 in Poco::Net::TCPServerDispatcher::run() build_docker/./base/poco/Net/src/TCPServerDispatcher.cpp:115:20
E               #16 0x56350aab0dfb in Poco::PooledThread::run() build_docker/./base/poco/Foundation/src/ThreadPool.cpp:188:14
E               #17 0x56350aaa9dc7 in Poco::ThreadImpl::runnableEntry(void*) build_docker/./base/poco/Foundation/src/Thread_POSIX.cpp:335:27
E               #18 0x5634da5b3c1a in asan_thread_start(void*) crtstuff.c
E           
E           Direct leak of 11 byte(s) in 1 object(s) allocated from:
E               #0 0x5634da5e8d5d in operator new[](unsigned long) (/usr/bin/clickhouse+0xa88ed5d) (BuildId: 2418d44073b11d3b0f437855a0f1dd6bd8d1ce2b)
E               #1 0x56350dabc02e in Strdup(char const*) build_docker/./contrib/libhdfs3/src/client/Hdfs.cpp:88:21
E               #2 0x56350dabc02e in ConstructHdfsFileInfo(hdfsFileInfo*, std::__1::vector<Hdfs::FileStatus, std::__1::allocator<Hdfs::FileStatus>> const&) build_docker/./contrib/libhdfs3/src/client/Hdfs.cpp:1049:27
E               #3 0x56350dabcdec in hdfsGetPathInfo build_docker/./contrib/libhdfs3/src/client/Hdfs.cpp:1100:9
E               #4 0x5634fb360e56 in DB::(anonymous namespace)::LSWithRegexpMatching(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::unique_ptr<HdfsFileSystemInternalWrapper, DB::detail::HDFSFsDeleter> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) build_docker/./src/Storages/HDFS/StorageHDFS.cpp:94:28
E               #5 0x5634fb34ff22 in DB::(anonymous namespace)::getPathsList(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::shared_ptr<DB::Context const>) build_docker/./src/Storages/HDFS/StorageHDFS.cpp:182:32
E               #6 0x5634fb34e343 in DB::StorageHDFS::getTableStructureFromData(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::shared_ptr<DB::Context const>) build_docker/./src/Storages/HDFS/StorageHDFS.cpp:397:28
E               #7 0x5634f970fa73 in DB::TableFunctionHDFS::getActualTableStructure(std::__1::shared_ptr<DB::Context const>, bool) const build_docker/./src/TableFunctions/TableFunctionHDFS.cpp:36:16
E               #8 0x5634fec93705 in DB::InterpreterDescribeQuery::fillColumnsFromTableFunction(DB::ASTTableExpression const&) build_docker/./src/Interpreters/InterpreterDescribeQuery.cpp:147:52
E               #9 0x5634fec90bc0 in DB::InterpreterDescribeQuery::execute() build_docker/./src/Interpreters/InterpreterDescribeQuery.cpp:89:9
E               #10 0x5634ffa24ec5 in DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum, DB::ReadBuffer*) build_docker/./src/Interpreters/executeQuery.cpp:1109:40
E               #11 0x5634ffa1b609 in DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum) build_docker/./src/Interpreters/executeQuery.cpp:1287:26
E               #12 0x56350297dd28 in DB::TCPHandler::runImpl() build_docker/./src/Server/TCPHandler.cpp:498:54
E               #13 0x5635029c24af in DB::TCPHandler::run() build_docker/./src/Server/TCPHandler.cpp:2292:9
E               #14 0x56350a6a46ee in Poco::Net::TCPServerConnection::start() build_docker/./base/poco/Net/src/TCPServerConnection.cpp:43:3
E               #15 0x56350a6a5416 in Poco::Net::TCPServerDispatcher::run() build_docker/./base/poco/Net/src/TCPServerDispatcher.cpp:115:20
E               #16 0x56350aab0dfb in Poco::PooledThread::run() build_docker/./base/poco/Foundation/src/ThreadPool.cpp:188:14
E               #17 0x56350aaa9dc7 in Poco::ThreadImpl::runnableEntry(void*) build_docker/./base/poco/Foundation/src/Thread_POSIX.cpp:335:27
E               #18 0x5634da5b3c1a in asan_thread_start(void*) crtstuff.c
E           
E           Direct leak of 5 byte(s) in 1 object(s) allocated from:
E               #0 0x5634da5e8d5d in operator new[](unsigned long) (/usr/bin/clickhouse+0xa88ed5d) (BuildId: 2418d44073b11d3b0f437855a0f1dd6bd8d1ce2b)
E               #1 0x56350dabc2d9 in Strdup(char const*) build_docker/./contrib/libhdfs3/src/client/Hdfs.cpp:88:21
E               #2 0x56350dabc2d9 in ConstructHdfsFileInfo(hdfsFileInfo*, std::__1::vector<Hdfs::FileStatus, std::__1::allocator<Hdfs::FileStatus>> const&) build_docker/./contrib/libhdfs3/src/client/Hdfs.cpp:1056:27
E               #3 0x56350dabcdec in hdfsGetPathInfo build_docker/./contrib/libhdfs3/src/client/Hdfs.cpp:1100:9
E               #4 0x5634fb360e56 in DB::(anonymous namespace)::LSWithRegexpMatching(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::unique_ptr<HdfsFileSystemInternalWrapper, DB::detail::HDFSFsDeleter> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) build_docker/./src/Storages/HDFS/StorageHDFS.cpp:94:28
E               #5 0x5634fb34ff22 in DB::(anonymous namespace)::getPathsList(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::shared_ptr<DB::Context const>) build_docker/./src/Storages/HDFS/StorageHDFS.cpp:182:32
E               #6 0x5634fb34e343 in DB::StorageHDFS::getTableStructureFromData(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::shared_ptr<DB::Context const>) build_docker/./src/Storages/HDFS/StorageHDFS.cpp:397:28
E               #7 0x5634f970fa73 in DB::TableFunctionHDFS::getActualTableStructure(std::__1::shared_ptr<DB::Context const>, bool) const build_docker/./src/TableFunctions/TableFunctionHDFS.cpp:36:16
E               #8 0x5634fec93705 in DB::InterpreterDescribeQuery::fillColumnsFromTableFunction(DB::ASTTableExpression const&) build_docker/./src/Interpreters/InterpreterDescribeQuery.cpp:147:52
E               #9 0x5634fec90bc0 in DB::InterpreterDescribeQuery::execute() build_docker/./src/Interpreters/InterpreterDescribeQuery.cpp:89:9
E               #10 0x5634ffa24ec5 in DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum, DB::ReadBuffer*) build_docker/./src/Interpreters/executeQuery.cpp:1109:40
E               #11 0x5634ffa1b609 in DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum) build_docker/./src/Interpreters/executeQuery.cpp:1287:26
E               #12 0x56350297dd28 in DB::TCPHandler::runImpl() build_docker/./src/Server/TCPHandler.cpp:498:54
E               #13 0x5635029c24af in DB::TCPHandler::run() build_docker/./src/Server/TCPHandler.cpp:2292:9
E               #14 0x56350a6a46ee in Poco::Net::TCPServerConnection::start() build_docker/./base/poco/Net/src/TCPServerConnection.cpp:43:3
E               #15 0x56350a6a5416 in Poco::Net::TCPServerDispatcher::run() build_docker/./base/poco/Net/src/TCPServerDispatcher.cpp:115:20
E               #16 0x56350aab0dfb in Poco::PooledThread::run() build_docker/./base/poco/Foundation/src/ThreadPool.cpp:188:14
E               #17 0x56350aaa9dc7 in Poco::ThreadImpl::runnableEntry(void*) build_docker/./base/poco/Foundation/src/Thread_POSIX.cpp:335:27
E               #18 0x5634da5b3c1a in asan_thread_start(void*) crtstuff.c
E           
E           SUMMARY: AddressSanitizer: 52 byte(s) leaked in 3 allocation(s).

helpers/cluster.py:3109: Exception
```

Seems like this code was introduced recently in  https://github.com/ClickHouse/ClickHouse/pull/56141. cc @zvonand

### PR DESCRIPTION
**Pull request by zvonand**
Closes #57819.

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by robot-clickhouse** [comment]
*This is an automated comment for commit 7d7aea9826dc5f3f15fe55d0960bfb3bd5deebe9 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/57860/7d7aea9826dc5f3f15fe55d0960bfb3bd5deebe9/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td><a href="https://github.com/ClickHouse/ClickHouse/actions/runs/7208563334">✅ success</a></td></tr>
<tbody>
</table>
</details>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/57860/7d7aea9826dc5f3f15fe55d0960bfb3bd5deebe9/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Comment by zvonand** [comment]
If it succeeds, I'd still run it a couple of times to make sure it helps

**Comment by zvonand** [comment]
@Algunenano it passed ok 3 times. I hope it resolves the issue completely

**Comment by Algunenano** [comment]
Failures:
* Integration tests (asan) [4/4]: `test_storage_azure_blob_storage/test_cluster.py::test_unset_skip_unavailable_shards` -> Already reported https://github.com/ClickHouse/ClickHouse/issues/57889. 82 failures in the last 24 hours :cold_sweat: 
* Integration tests (release) [4/4] : Same
* Performance Comparison [3/4] : `EOFError: Unexpected EOF while reading bytes` Seems like a network problem or something similar in a test run. Not related
* Stress test (tsan): Failure in a join. I can't reproduce it and the settings are not available. Will open a ticket.

**Pull request merged**
