### PR TITLE
Try to fix 2572

### PR DESCRIPTION
**Pull request by jsc0218**
Trying to solve this [issue](https://github.com/ClickHouse/ClickHouse/issues/65166). I cannot reproduce it locally with setting from the [report](https://s3.amazonaws.com/clickhouse-test-reports/65125/848054e85f743cee8797a7419163840764d76935/stateless_tests__tsan__[4_5].html). Not much clue from the run.log. Any other input would be appreciated.

1. But considering the test fails after 15s with debug and sanitizer = true, I set the sleep time proportionally. Can use optimize to force flushing, but it looks like the original author wants to test the [context](https://github.com/ClickHouse/ClickHouse/commit/9235d1cde214b2a200cc7994a860a35a40e99d10) issue.
2. Reordered the check of system table. According to the report, the system table shows query finishes right after select from the data and copy (2nd time). So after reordering, if the system table still shows query finishes without content in data and copy table in the future, then it must be an error.

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
...

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-clickhouse** [comment]
*This is an automated comment for commit 3f70977cd660e4617d9bbd68cc229020adc57f98 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/67158/3f70977cd660e4617d9bbd68cc229020adc57f98/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/66982/93a2dbf85c446cd5efa802dfe8fc99e2a82f394f/docs_check.html">✅ success</a></td></tr>
<tr><td>Unit tests</td><td>Runs the unit tests for different release types</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/d2c04a21983d80c0b30c17f20ede0677e1f0b3a1/unit_tests__release_.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Comment by CheSema** [comment]
Consider to rewrite this tests to the bash or python.

This tests are checking something which happens in the background and the test waits that. Instead just increasing timeouts for all the runs lets literally wait that event in cycle.

**Review by CheSema — CHANGES_REQUESTED** [review]
Lets make timeouts not fixed but limited.

**Comment by alexey-milovidov** [comment]
Needs https://github.com/ClickHouse/ClickHouse/pull/66863

**Pull request merged**
