### PR TITLE
Update RocksDB to master

### PR DESCRIPTION
**Pull request by alexey-milovidov**
Changelog category (leave one):
- Build/Testing/Packaging Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Update RocksDB to 2021-07-16 master.

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
> 01882_total_rows_approx

Looks like a flaky test.

**Comment by alexey-milovidov** [comment]
@mergifyio update

**Comment by alexey-milovidov** [comment]
@azat I have seen failures of the `01882_total_rows_approx` multiple times already.

**Comment by alexey-milovidov** [comment]
Also `01455_shard_leaf_max_rows_bytes_to_read` is quite annoying.

| check_name | test_name | test_status | check_start_time | report_url |
|:-|:-|:-|-:|:-|
| Fast test | 01455_shard_leaf_max_rows_bytes_to_read | FAIL | 2021-07-15 05:34:08 | https://clickhouse-test-reports.s3.yandex.net/0/59e6502a3b5fc63cb0042bbd8f5eb3d473610ee7/fast_test.html |
| Fast test | 01149_zookeeper_mutation_stuck_after_replace_partition | FAIL | 2021-06-23 14:09:05 | https://clickhouse-test-reports.s3.yandex.net/0/fdff177823325c59ad8f9887d470d1a6d0a37d1a/fast_test.html |
| Fast test | 01882_total_rows_approx | FAIL | 2021-06-21 20:27:48 | https://clickhouse-test-reports.s3.yandex.net/0/992ecfabf42139bcffacc4787486b7dc34ce40ff/fast_test.html |
| Fast test | 01532_execute_merges_on_single_replica | FAIL | 2021-06-17 07:28:55 | https://clickhouse-test-reports.s3.yandex.net/0/7aacca94e35151e78b4b927840a6f58b622cf144/fast_test.html |
| Fast test | 01532_execute_merges_on_single_replica | FAIL | 2021-06-17 06:41:33 | https://clickhouse-test-reports.s3.yandex.net/0/0972b53ef4f39a67a5993505e43b9ecdffd7620f/fast_test.html |
| Fast test | 01532_execute_merges_on_single_replica | FAIL | 2021-06-14 21:56:16 | https://clickhouse-test-reports.s3.yandex.net/0/15f3ac978706207ece6b50905f8c36ca90161218/fast_test.html |
| Fast test | 01532_execute_merges_on_single_replica | FAIL | 2021-06-12 19:57:28 | https://clickhouse-test-reports.s3.yandex.net/0/494107e43709ad509cb045088d6f6327f3cd4703/fast_test.html |
| Fast test | 01606_git_import | FAIL | 2021-06-11 08:51:21 | https://clickhouse-test-reports.s3.yandex.net/0/e549b29bffbf07d0cc94814ef204d0bbf4f1a620/fast_test.html |
| Fast test | 01882_total_rows_approx | FAIL | 2021-06-11 08:04:54 | https://clickhouse-test-reports.s3.yandex.net/0/54f9db670ffbbae82d482b32998d216dc81548cb/fast_test.html |
| Fast test | 01882_total_rows_approx | FAIL | 2021-06-10 01:01:40 | https://clickhouse-test-reports.s3.yandex.net/0/db02da4c42bafa2417aa5225e5293b08d9205abb/fast_test.html |
| Fast test | 01532_execute_merges_on_single_replica | FAIL | 2021-06-09 09:21:22 | https://clickhouse-test-reports.s3.yandex.net/0/82b8d45cd71128378b334e0aa4abc756898e688d/fast_test.html |
| Fast test | 01035_concurrent_move_partition_from_table_zookeeper | FAIL | 2021-06-01 10:10:20 | https://clickhouse-test-reports.s3.yandex.net/0/c673eb20408e01e546719f11690a69932c3fdced/fast_test.html |
| Fast test | 01532_execute_merges_on_single_replica | FAIL | 2021-05-27 00:24:17 | https://clickhouse-test-reports.s3.yandex.net/0/0d3462afc89e4c6c9abceeb307468b44351ae5dd/fast_test.html |
| Fast test | 01593_concurrent_alter_mutations_kill | FAIL | 2021-05-24 20:15:48 | https://clickhouse-test-reports.s3.yandex.net/0/45a4bdc5d9dfa9345ef567f42f50cf7d0618f584/fast_test.html |
| Fast test | 01085_max_distributed_connections | FAIL | 2021-05-23 10:37:41 | https://clickhouse-test-reports.s3.yandex.net/0/d0e96defc4ac13751a1945b7e114184ec4bb75f6/fast_test.html |
| Fast test | 00705_drop_create_merge_tree | FAIL | 2021-05-23 07:59:47 | https://clickhouse-test-reports.s3.yandex.net/0/3f2d280e3456cd9914d64a4d93c751717e4fc22f/fast_test.html |
| Fast test | 00705_drop_create_merge_tree | FAIL | 2021-05-23 00:24:05 | https://clickhouse-test-reports.s3.yandex.net/0/40595da023f4089f07f2918e0bc85abae65cafcb/fast_test.html |
| Fast test | 01282_system_parts_ttl_info | FAIL | 2021-05-20 07:59:20 | https://clickhouse-test-reports.s3.yandex.net/0/cf94bc9b8c57414a8a576d6e69ada06e669c85f2/fast_test.html |
| Fast test | 01852_hints_enum_name | FAIL | 2021-05-19 22:45:06 | https://clickhouse-test-reports.s3.yandex.net/0/335dafe887dc55b7a90fd5f0f058d05bb82c99a1/fast_test.html |
| Fast test | 01852_hints_enum_name | FAIL | 2021-05-19 18:45:49 | https://clickhouse-test-reports.s3.yandex.net/0/9982f05e4deb23d923f4f17ace5cef9d53146b67/fast_test.html |
| Fast test | 00705_drop_create_merge_tree | FAIL | 2021-05-19 15:12:27 | https://clickhouse-test-reports.s3.yandex.net/0/218f534a6f5a4389c8c3b47f0a3fe3acd6ac3aee/fast_test.html |
| Fast test | 01852_hints_enum_name | FAIL | 2021-05-19 14:00:25 | https://clickhouse-test-reports.s3.yandex.net/0/e9b69bbd708b5fc1761df09812359d8112b87aae/fast_test.html |
| Fast test | 00705_drop_create_merge_tree | FAIL | 2021-05-19 13:57:46 | https://clickhouse-test-reports.s3.yandex.net/0/f80f6b130c803f87c556c0c8ab800650876bdd9a/fast_test.html |

**Comment by alexey-milovidov** [comment]
@azat Timing around 10 seconds is unreliable, maybe simply remove the test?

**Review by kitaisreal — APPROVED** [review]

**Comment by azat** [comment]
@alexey-milovidov The following tests, should be addressed in #26431
- `01882_total_rows_approx`
- `01455_shard_leaf_max_rows_bytes_to_read`

**Pull request merged**
