### PR TITLE
Revert "CI: Backports updates"

### PR DESCRIPTION
**Pull request by maxknv**
#do_not_test
Reverts ClickHouse/ClickHouse#64603

### CODE REVIEW

**Comment by robot-clickhouse** [comment]
*This is an automated comment for commit 817e88bd5f42dce78339cd2434995b1763c289fd with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/64995/817e88bd5f42dce78339cd2434995b1763c289fd/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>A Sync</td><td>If it fails, ask a maintainer for help</td><td>⏳ pending</td></tr>
<tbody>
</table>
<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>Checks correctness of the PR's body</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

**Review by Felixoid — APPROVED** [review]
We need to merge it ASAP and then remove all tags `pr-backport-created` and `pr-backports-created-cloud` created since 2024-05-29

It will, maybe, re-create some closed cherry-pick commits, but it's the only way to fix the issue like in https://github.com/ClickHouse/ClickHouse/pull/64858, where one `cherry-pick` PR is still open, but the tag is applied

**Comment by Felixoid** [comment]
Here are affected PRs https://github.com/ClickHouse/ClickHouse/pulls?q=is%3Apr+label%3Apr-backports-created-cloud+is%3Aclosed+merged%3A2024-05-29..2024-06-07

**Comment by Felixoid** [comment]
The workflow launched from this branch https://github.com/ClickHouse/ClickHouse/actions/runs/9420359733/job/25952226446, all PRs are cleaned from `pr-backport-created` and `pr-backports-created-cloud`

**Pull request closed without merging**
