### PR TITLE
Change FROM clause formatting (make it more human friendly)

### PR DESCRIPTION
**Pull request by azat**
Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix trailing whitespaces in FROM clause with subqueries in multiline mode, and also changes the output of the queries slightly in a more human friendly way.

Detailed description / Documentation draft:
Before:

    $ clickhouse-format <<<'select * from system.one, (select * from system.one)'
    SELECT *
    FROM system.one
    ,
    (
        SELECT *
        FROM system.one
    )

After:

    $ clickhouse-format <<<'select * from system.one, (select * from system.one)'
    SELECT *
    FROM system.one,
    (
        SELECT *
        FROM system.one
    )

*NOTE: should it be marked with `Backward Incompatible Change`? (since it changes the output that someone may relay on)*

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
> should it be marked with Backward Incompatible Change?

It's alright, we shouldn't guarantee how queries will be formatted.

**Review by alexey-milovidov — APPROVED** [review]

**Comment by kitaisreal** [comment]
@azat there are some issues with functional statelss tests. Are they related to changes ?

**Comment by azat** [comment]
> there are some issues with functional statelss tests. Are they related to changes ?

AFAICS - no

- there are few failures due to the test takes too long (marked them as long)
- there is one strange failure - `01414_push_predicate_when_contains_with_clause` (will take a look)
- and unrelated `00953_zookeeper_suetin_deduplication_bug`

**Comment by azat** [comment]
>[Functional stateless tests flaky check (address) — Timeout, fail: 67, passed: 2682](https://clickhouse-test-reports.s3.yandex.net/24151/147ae1749fb0d548a1283ffcd32428ec4e9fd542/functional_stateless_tests_flaky_check_(address).html#fail1)

`01414_push_predicate_when_contains_with_clause` - #24259

**Review by alexey-milovidov — APPROVED** [review]

**Pull request merged**
