### PR TITLE
CI: Auto backport for bugfix and ci-fix

### PR DESCRIPTION
**Pull request by maxknv**
### Changelog category (leave one):
- CI Fix or Improvement (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
...

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Review by Felixoid — COMMENTED** [review]
Good, but the remaining fix is `utils/changelog/changelog.py`

And I think, it should be something easies, like `CI/CD`. And we shouldn't put it to the changelog, so `CI/CD (changelog entry is not required)`

**Comment by Felixoid** [comment]
@maxknv after the #60461 is unintentionally merged, we should hurry up here `¯\_(ツ)_/¯`

**Comment by maxknv** [comment]
> @maxknv after the #60461 is unintentionally merged, we should hurry up here `¯\_(ツ)_/¯`

why?

**Comment by maxknv** [comment]
@Felixoid I guess w/o updates in changelog.py pr-ci will end up in category "Other" in change log. It should be ok, right?

**Comment by Felixoid** [comment]
Yes, but I still think we should change the changelog is unnecessary for `CI` changes

**Comment by Felixoid** [comment]
Please add the `(not for changelog)` everywhere.

And since we're here, let's make the message in each place with changelog categories clear. `Every place MUST be updated simultaneously`

**Pull request merged**
