### PR TITLE
Fix key analysis (with set) for `Merge` engine

### LINKED ISSUE #51846: IN operator much slower on 23.6.1 than on 23.4.2.11
(you don't have to strictly follow this form)

**Describe the unexpected behaviour**
I have a merge table (say) t_merge, and a memory table t_memory.
on version 23.4.2.11, I use IN operator to query records from t_merge, by "where (xx, xxx) in t_memory). It is really quick than "t_merge left semi join t_memory". that is 100ms vs 6s.
but when upgrade to version 23.6.1, the IN operator slow down to 6s, almost same as "left semi join".
what is wrong?

**How to reproduce**
* Which ClickHouse server version to use - 23.6.1
* Which interface to use, if matters - JetBrains DataGrip with http
* Non-default settings, if any
* `CREATE TABLE` statements for all tables involved
* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary
* Queries to run that lead to unexpected result

**Expected behavior**
IN operator performance better.

**Error message and/or stacktrace**

**Additional context**
there is some signal may related:
that seems clickhouse server return rows quickly just as former version, (not sure all or just part of them). then after several seconds it show query finished. 
maybe server finished work already, but block for a while then finish the query process?

### PR DESCRIPTION
**Pull request by nickitat**
### Changelog category (leave one):
- Performance Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fixed filtering by `IN(...)` condition for `Merge` table engine.

Fixes: #51846

### CODE REVIEW

**Comment by robot-ch-test-poll2** [comment]
*This is an automated comment for commit c50ef0a6a9d451b85e58a200f0b6855d892a67c6 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/54905/c50ef0a6a9d451b85e58a200f0b6855d892a67c6/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>✅ success</td></tr>
<tbody>
</table>
</details>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>⏳ pending</td></tr>
<tbody>
</table>

**Comment by nickitat** [comment]
the problem was that we built query plans for child tables in `initializePipeline` (too late). at this moment we already finish `optimize` of the main query plan and took `prepared_sets` out of `query_info` to build normal set creation step. Ultimately I think that it is better to build child plans at the same time we build `ReadFromMerge` itself as well as other reading steps. In particular it will allow to create right `applyFilters()` overload for `ReadFromMerge` that will actually call `applyFilters()` on child plans, create key condition with this set and use it for PK filtering.

**Comment by nickitat** [comment]
@KochetovNicolai maybe you could take a look?

**Comment by SaltTan** [comment]
I'm waiting for this one to upgrade to 23.8...

**Comment by nickitat** [comment]
> I'm waiting for this one to upgrade to 23.8...

jfyi, we don't back-port perf fixes

**Comment by SaltTan** [comment]
> > I'm waiting for this one to upgrade to 23.8...
> 
> jfyi, we don't back-port perf fixes

23.11 then :)

**Comment by SaltTan** [comment]
I should have said that I'm waiting for this one to upgrade from 23.4 :)

**Review by KochetovNicolai — APPROVED** [review]

**Comment by whitemay** [comment]
Is this pull already in some version or not?
issue #51846 already closed. but i checked on v23.10.5, issue still remains.

**Comment by nickitat** [comment]
pr was merged Nov 9, it cannot be included in Oct release

**Pull request merged**
