### PR TITLE
Fixed a sorting order breakage in TTL GROUP BY

### PR DESCRIPTION
**Pull request by nikitamikhaylov**
### Changelog category (leave one):

- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fixed a bug in TTL GROUP BY which could break the sorting order of data parts. Added additional sorting order checks in debug builds.

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]

**Review by KochetovNicolai — APPROVED** [review]

**Comment by nikitamikhaylov** [comment]
Hello 

```
2023.04.27 23:56:02.599439 [ 93558 ] {a3c59481-0805-4aa9-8add-4d72cf674f58::all_1_5_3} <Fatal> : Logical error: 'Sort order of blocks violated for column number 4, left: Int64_-2, right: Int64_-12. Chunk 0, rows read 2. (all_1_5_2)'.
2023.04.27 23:56:02.600924 [ 94028 ] {} <Fatal> BaseDaemon: ########################################
2023.04.27 23:56:02.601031 [ 94028 ] {} <Fatal> BaseDaemon: (version 23.5.1.1, build id: 1B41FCF1E034CAC5301387D5B53FC2D061FA5B21) (from thread 93558) (query_id: a3c59481-0805-4aa9-8add-4d72cf674f58::all_1_5_3) (query: ) Received signal Aborted (6)
2023.04.27 23:56:02.601109 [ 94028 ] {} <Fatal> BaseDaemon: 
2023.04.27 23:56:02.601240 [ 94028 ] {} <Fatal> BaseDaemon: Stack trace: 0x7ff6ce2f500b 0x7ff6ce2d4859 0x22db831e 0x22db8395 0x22db879f 0x1a2bb2ca 0x2d795496 0x2d793157 0x2d792c00 0x26c876c2 0x2d340972 0x2d3800c3 0x2d37fe00 0x2d360561 0x2d3600ce 0x2d38a27e 0x2d38a321 0x2cba9df0 0x2cbc1018 0x2cbc0ff5 0x2cbc0fd5 0x2cbc0fb5 0x2cbc0f7d 0x22d7b7d6 0x22d7ab15 0x2cba9d06 0x2cbae3d2 0x2d0e4af8 0x2d0a6a24 0x2d0a68e3 0x2d0abf04 0x2b8eb105 0x2bea4c57 0x2bea0a04 0x2d2d872d 0x2d2ea325 0x3277a319 0x3277ab5c 0x329bb8f4 0x329b869a 0x329b739e
2023.04.27 23:56:02.601358 [ 94028 ] {} <Fatal> BaseDaemon: 4. gsignal @ 0x7ff6ce2f500b in ?
2023.04.27 23:56:02.601428 [ 94028 ] {} <Fatal> BaseDaemon: 5. abort @ 0x7ff6ce2d4859 in ?
2023.04.27 23:56:02.678807 [ 94028 ] {} <Fatal> BaseDaemon: 6. /build/src/Common/Exception.cpp:41: DB::abortOnFailedAssertion(String const&) @ 0x22db831e in /usr/bin/clickhouse
2023.04.27 23:56:02.755293 [ 94028 ] {} <Fatal> BaseDaemon: 7. /build/src/Common/Exception.cpp:64: DB::handle_error_code(String const&, int, bool, std::vector<void*, std::allocator<void*>> const&) @ 0x22db8395 in /usr/bin/clickhouse
2023.04.27 23:56:02.821728 [ 94028 ] {} <Fatal> BaseDaemon: 8. /build/src/Common/Exception.cpp:92: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x22db879f in /usr/bin/clickhouse
2023.04.27 23:56:02.901547 [ 94028 ] {} <Fatal> BaseDaemon: 9. /build/src/Common/Exception.h:54: DB::Exception::Exception(String&&, int, bool) @ 0x1a2bb2ca in /usr/bin/clickhouse
2023.04.27 23:56:02.993298 [ 94028 ] {} <Fatal> BaseDaemon: 10. /build/src/Common/Exception.h:81: DB::Exception::Exception<unsigned long&, String, String, unsigned long&, unsigned long&, String>(int, FormatStringHelperImpl<std::type_identity<unsigned long&>::type, std::type_identity<String>::type, std::type_identity<String>::type, std::type_identity<unsigned long&>::type, std::type_identity<unsigned long&>::type, std::type_identity<String>::type>, unsigned long&, String&&, String&&, unsigned long&, unsigned long&, String&&) @ 0x2d795496 in /usr/bin/clickhouse
2023.04.27 23:56:03.068802 [ 94028 ] {} <Fatal> BaseDaemon: 11. /build/src/Processors/Transforms/CheckSortedTransform.cpp:44: DB::CheckSortedTransform::transform(DB::Chunk&)::$_0::operator()(std::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn>>> const&, unsigned long, std::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn>>> const&, unsigned long) const @ 0x2d793157 in /usr/bin/clickhouse
2023.04.27 23:56:03.144547 [ 94028 ] {} <Fatal> BaseDaemon: 12. /build/src/Processors/Transforms/CheckSortedTransform.cpp:62: DB::CheckSortedTransform::transform(DB::Chunk&) @ 0x2d792c00 in /usr/bin/clickhouse
2023.04.27 23:56:03.238982 [ 94028 ] {} <Fatal> BaseDaemon: 13. /build/src/Processors/ISimpleTransform.h:33: DB::ISimpleTransform::transform(DB::Chunk&, DB::Chunk&) @ 0x26c876c2 in /usr/bin/clickhouse
2023.04.27 23:56:03.294723 [ 94028 ] {} <Fatal> BaseDaemon: 14. /build/src/Processors/ISimpleTransform.cpp:89: DB::ISimpleTransform::work() @ 0x2d340972 in /usr/bin/clickhouse
2023.04.27 23:56:03.325658 [ 94028 ] {} <Fatal> BaseDaemon: 15. /build/src/Processors/Executors/ExecutionThreadContext.cpp:47: DB::executeJob(DB::ExecutingGraph::Node*, DB::ReadProgressCallback*) @ 0x2d3800c3 in /usr/bin/clickhouse
2023.04.27 23:56:03.354007 [ 94028 ] {} <Fatal> BaseDaemon: 16. /build/src/Processors/Executors/ExecutionThreadContext.cpp:92: DB::ExecutionThreadContext::executeTask() @ 0x2d37fe00 in /usr/bin/clickhouse
2023.04.27 23:56:03.438322 [ 94028 ] {} <Fatal> BaseDaemon: 17. /build/src/Processors/Executors/PipelineExecutor.cpp:255: DB::PipelineExecutor::executeStepImpl(unsigned long, std::atomic<bool>*) @ 0x2d360561 in /usr/bin/clickhouse
2023.04.27 23:56:03.522401 [ 94028 ] {} <Fatal> BaseDaemon: 18. /build/src/Processors/Executors/PipelineExecutor.cpp:151: DB::PipelineExecutor::executeStep(std::atomic<bool>*) @ 0x2d3600ce in /usr/bin/clickhouse
2023.04.27 23:56:03.587715 [ 94028 ] {} <Fatal> BaseDaemon: 19. /build/src/Processors/Executors/PullingPipelineExecutor.cpp:54: DB::PullingPipelineExecutor::pull(DB::Chunk&) @ 0x2d38a27e in /usr/bin/clickhouse
2023.04.27 23:56:03.652970 [ 94028 ] {} <Fatal> BaseDaemon: 20. /build/src/Processors/Executors/PullingPipelineExecutor.cpp:65: DB::PullingPipelineExecutor::pull(DB::Block&) @ 0x2d38a321 in /usr/bin/clickhouse
2023.04.27 23:56:04.068270 [ 94028 ] {} <Fatal> BaseDaemon: 21. /build/src/Storages/MergeTree/MergeTask.cpp:424: DB::MergeTask::ExecuteAndFinalizeHorizontalPart::executeImpl() @ 0x2cba9df0 in /usr/bin/clickhouse
2023.04.27 23:56:04.530983 [ 94028 ] {} <Fatal> BaseDaemon: 22. /build/src/Storages/MergeTree/MergeTask.h:239: DB::MergeTask::ExecuteAndFinalizeHorizontalPart::subtasks::'lambda0'()::operator()() const @ 0x2cbc1018 in /usr/bin/clickhouse
2023.04.27 23:56:05.026855 [ 94028 ] {} <Fatal> BaseDaemon: 23. /build/contrib/llvm-project/libcxx/include/__functional/invoke.h:394: decltype(std::declval<DB::MergeTask::ExecuteAndFinalizeHorizontalPart::subtasks::'lambda0'()&>()()) std::__invoke[abi:v15000]<DB::MergeTask::ExecuteAndFinalizeHorizontalPart::subtasks::'lambda0'()&>(DB::MergeTask::ExecuteAndFinalizeHorizontalPart::subtasks::'lambda0'()&) @ 0x2cbc0ff5 in /usr/bin/clickhouse
2023.04.27 23:56:05.491070 [ 94028 ] {} <Fatal> BaseDaemon: 24. /build/contrib/llvm-project/libcxx/include/__functional/invoke.h:470: bool std::__invoke_void_return_wrapper<bool, false>::__call<DB::MergeTask::ExecuteAndFinalizeHorizontalPart::subtasks::'lambda0'()&>(DB::MergeTask::ExecuteAndFinalizeHorizontalPart::subtasks::'lambda0'()&) @ 0x2cbc0fd5 in /usr/bin/clickhouse
2023.04.27 23:56:05.955775 [ 94028 ] {} <Fatal> BaseDaemon: 25. /build/contrib/llvm-project/libcxx/include/__functional/function.h:235: std::__function::__default_alloc_func<DB::MergeTask::ExecuteAndFinalizeHorizontalPart::subtasks::'lambda0'(), bool ()>::operator()[abi:v15000]() @ 0x2cbc0fb5 in /usr/bin/clickhouse
2023.04.27 23:56:06.419063 [ 94028 ] {} <Fatal> BaseDaemon: 26. /build/contrib/llvm-project/libcxx/include/__functional/function.h:716: bool std::__function::__policy_invoker<bool ()>::__call_impl<std::__function::__default_alloc_func<DB::MergeTask::ExecuteAndFinalizeHorizontalPart::subtasks::'lambda0'(), bool ()>>(std::__function::__policy_storage const*) @ 0x2cbc0f7d in /usr/bin/clickhouse
2023.04.27 23:56:06.566739 [ 94028 ] {} <Fatal> BaseDaemon: 27. /build/contrib/llvm-project/libcxx/include/__functional/function.h:848: std::__function::__policy_func<bool ()>::operator()[abi:v15000]() const @ 0x22d7b7d6 in /usr/bin/clickhouse
2023.04.27 23:56:06.713220 [ 94028 ] {} <Fatal> BaseDaemon: 28. /build/contrib/llvm-project/libcxx/include/__functional/function.h:1187: std::function<bool ()>::operator()() const @ 0x22d7ab15 in /usr/bin/clickhouse
2023.04.27 23:56:07.123970 [ 94028 ] {} <Fatal> BaseDaemon: 29. /build/src/Storages/MergeTree/MergeTask.cpp:412: DB::MergeTask::ExecuteAndFinalizeHorizontalPart::execute() @ 0x2cba9d06 in /usr/bin/clickhouse
2023.04.27 23:56:07.538070 [ 94028 ] {} <Fatal> BaseDaemon: 30. /build/src/Storages/MergeTree/MergeTask.cpp:831: DB::MergeTask::execute() @ 0x2cbae3d2 in /usr/bin/clickhouse
2023.04.27 23:56:07.607975 [ 94028 ] {} <Fatal> BaseDaemon: 31. /build/src/Storages/MergeTree/MergePlainMergeTreeTask.cpp:57: DB::MergePlainMergeTreeTask::executeStep() @ 0x2d0e4af8 in /usr/bin/clickhouse
2023.04.27 23:56:08.066371 [ 94028 ] {} <Fatal> BaseDaemon: 32. /build/src/Storages/MergeTree/MergePlainMergeTreeTask.h:103: DB::executeHere(std::shared_ptr<DB::MergePlainMergeTreeTask>) @ 0x2d0a6a24 in /usr/bin/clickhouse
2023.04.27 23:56:08.416156 [ 94028 ] {} <Fatal> BaseDaemon: 33. /build/src/Storages/StorageMergeTree.cpp:1049: DB::StorageMergeTree::merge(bool, String const&, bool, bool, std::vector<String, std::allocator<String>> const&, bool, std::shared_ptr<DB::MergeTreeTransaction> const&, String*, bool) @ 0x2d0a68e3 in /usr/bin/clickhouse
2023.04.27 23:56:08.794814 [ 94028 ] {} <Fatal> BaseDaemon: 34. /build/src/Storages/StorageMergeTree.cpp:1441: DB::StorageMergeTree::optimize(std::shared_ptr<DB::IAST> const&, std::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::shared_ptr<DB::IAST> const&, bool, bool, std::vector<String, std::allocator<String>> const&, bool, std::shared_ptr<DB::Context const>) @ 0x2d0abf04 in /usr/bin/clickhouse
2023.04.27 23:56:08.860472 [ 94028 ] {} <Fatal> BaseDaemon: 35. /build/src/Interpreters/InterpreterOptimizeQuery.cpp:82: DB::InterpreterOptimizeQuery::execute() @ 0x2b8eb105 in /usr/bin/clickhouse
2023.04.27 23:56:09.078256 [ 94028 ] {} <Fatal> BaseDaemon: 36. /build/src/Interpreters/executeQuery.cpp:713: DB::executeQueryImpl(char const*, char const*, std::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, DB::ReadBuffer*) @ 0x2bea4c57 in /usr/bin/clickhouse
2023.04.27 23:56:09.306490 [ 94028 ] {} <Fatal> BaseDaemon: 37. /build/src/Interpreters/executeQuery.cpp:1168: DB::executeQuery(String const&, std::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum) @ 0x2bea0a04 in /usr/bin/clickhouse
2023.04.27 23:56:09.538536 [ 94028 ] {} <Fatal> BaseDaemon: 38. /build/src/Server/TCPHandler.cpp:420: DB::TCPHandler::runImpl() @ 0x2d2d872d in /usr/bin/clickhouse
2023.04.27 23:56:09.802322 [ 94028 ] {} <Fatal> BaseDaemon: 39. /build/src/Server/TCPHandler.cpp:2043: DB::TCPHandler::run() @ 0x2d2ea325 in /usr/bin/clickhouse
2023.04.27 23:56:09.821885 [ 94028 ] {} <Fatal> BaseDaemon: 40. /build/base/poco/Net/src/TCPServerConnection.cpp:43: Poco::Net::TCPServerConnection::start() @ 0x3277a319 in /usr/bin/clickhouse
2023.04.27 23:56:09.846819 [ 94028 ] {} <Fatal> BaseDaemon: 41. /build/base/poco/Net/src/TCPServerDispatcher.cpp:115: Poco::Net::TCPServerDispatcher::run() @ 0x3277ab5c in /usr/bin/clickhouse
2023.04.27 23:56:09.875258 [ 94028 ] {} <Fatal> BaseDaemon: 42. /build/base/poco/Foundation/src/ThreadPool.cpp:188: Poco::PooledThread::run() @ 0x329bb8f4 in /usr/bin/clickhouse
2023.04.27 23:56:09.901989 [ 94028 ] {} <Fatal> BaseDaemon: 43. /build/base/poco/Foundation/src/Thread.cpp:46: Poco::(anonymous namespace)::RunnableHolder::run() @ 0x329b869a in /usr/bin/clickhouse
2023.04.27 23:56:09.927739 [ 94028 ] {} <Fatal> BaseDaemon: 44. /build/base/poco/Foundation/src/Thread_POSIX.cpp:335: Poco::ThreadImpl::runnableEntry(void*) @ 0x329b739e in /usr/bin/clickhouse
2023.04.27 23:56:09.927856 [ 94028 ] {} <Fatal> BaseDaemon: Integrity check of the executable skipped because the reference checksum could not be read.
2023.04.27 23:56:17.744533 [ 704 ] {} <Fatal> Application: Child process was terminated by signal 6.
```

**Comment by robot-clickhouse-ci-2** [comment]
*This is an automated comment for commit 2db06598633ebe8f2feeed53d0ff44dd856fab7a with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/49103/2db06598633ebe8f2feeed53d0ff44dd856fab7a/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td><a href="https://github.com/ClickHouse/ClickHouse/actions/runs/6451305497">✅ success</a></td></tr>
<tbody>
</table>
</details>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/49103/2db06598633ebe8f2feeed53d0ff44dd856fab7a/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Comment by alexey-milovidov** [comment]
@KochetovNicolai what happened?

**Comment by alexey-milovidov** [comment]
@nikitamikhaylov please merge with master.

**Comment by KochetovNicolai** [comment]
This PR found an issue with TTL GROUP BY, which can break PK order  (in 01763_long_ttl_group_by).
Example:
```
DROP TABLE IF EXISTS test_ttl_group_by01763;
CREATE TABLE test_ttl_group_by01763
(key UInt32, ts DateTime, value UInt32, min_value UInt32 default value, max_value UInt32 default value)
ENGINE = MergeTree() PARTITION BY toYYYYMM(ts)
ORDER BY (key, toStartOfInterval(ts, toIntervalMinute(3)), ts) 
TTL ts + INTERVAL 5 MINUTE GROUP BY key, toStartOfInterval(ts, toIntervalMinute(3)) 
SET value = sum(value), min_value = min(min_value), max_value = max(max_value),  ts=min(toStartOfInterval(ts, toIntervalMinute(3)));


INSERT INTO test_ttl_group_by01763(key, ts, value) SELECT number%5 as key, now() - interval 10 minute + number, 0 FROM numbers(1000);

:) select * from (select _part, rowNumberInAllBlocks(), (key, toStartOfInterval(ts, toIntervalMinute(3)), ts) as cur, lagInFrame((key, toStartOfInterval(ts, toIntervalMinute(3)), ts), 1) over () as prev, 1 from test_ttl_group_by01763) where cur < prev limit 2 settings max_threads=1;

SELECT *
FROM
(
    SELECT
        _part,
        rowNumberInAllBlocks(),
        (key, toStartOfInterval(ts, toIntervalMinute(3)), ts) AS cur,
        lagInFrame((key, toStartOfInterval(ts, toIntervalMinute(3)), ts), 1) OVER () AS prev,
        1
    FROM test_ttl_group_by01763
)
WHERE cur < prev
LIMIT 2
SETTINGS max_threads = 1

Query id: 8cdb8a92-5978-479a-9bf5-0ba89d30b94b

┌─_part────────┬─rowNumberInAllBlocks()─┬─cur─────────────────────────────────────────────┬─prev────────────────────────────────────────────┬─1─┐
│ 202311_1_1_1 │                     33 │ (0,'2023-11-20 16:36:00','2023-11-20 16:36:00') │ (0,'2023-11-20 16:36:00','2023-11-20 16:38:57') │ 1 │
│ 202311_1_1_1 │                    176 │ (1,'2023-11-20 16:36:00','2023-11-20 16:36:00') │ (1,'2023-11-20 16:36:00','2023-11-20 16:38:58') │ 1 │
└──────────────┴────────────────────────┴─────────────────────────────────────────────────┴─────────────────────────────────────────────────┴───┘


:) select * from test_ttl_group_by01763 limit 35 settings max_threads=1;

SELECT *
FROM test_ttl_group_by01763
LIMIT 35
SETTINGS max_threads = 1

Query id: 56daad4c-7829-42c7-a0f8-793597f3184f

┌─key─┬──────────────────ts─┬─value─┬─min_value─┬─max_value─┐
│   0 │ 2023-11-20 16:30:00 │     0 │         0 │         0 │
│   0 │ 2023-11-20 16:33:00 │     0 │         0 │         0 │
│   0 │ 2023-11-20 16:36:27 │     0 │         0 │         0 │
│   0 │ 2023-11-20 16:36:32 │     0 │         0 │         0 │
│   0 │ 2023-11-20 16:36:37 │     0 │         0 │         0 │
│   0 │ 2023-11-20 16:36:42 │     0 │         0 │         0 │
│   0 │ 2023-11-20 16:36:47 │     0 │         0 │         0 │
│   0 │ 2023-11-20 16:36:52 │     0 │         0 │         0 │
│   0 │ 2023-11-20 16:36:57 │     0 │         0 │         0 │
│   0 │ 2023-11-20 16:37:02 │     0 │         0 │         0 │
│   0 │ 2023-11-20 16:37:07 │     0 │         0 │         0 │
│   0 │ 2023-11-20 16:37:12 │     0 │         0 │         0 │
│   0 │ 2023-11-20 16:37:17 │     0 │         0 │         0 │
│   0 │ 2023-11-20 16:37:22 │     0 │         0 │         0 │
│   0 │ 2023-11-20 16:37:27 │     0 │         0 │         0 │
│   0 │ 2023-11-20 16:37:32 │     0 │         0 │         0 │
│   0 │ 2023-11-20 16:37:37 │     0 │         0 │         0 │
│   0 │ 2023-11-20 16:37:42 │     0 │         0 │         0 │
│   0 │ 2023-11-20 16:37:47 │     0 │         0 │         0 │
│   0 │ 2023-11-20 16:37:52 │     0 │         0 │         0 │
│   0 │ 2023-11-20 16:37:57 │     0 │         0 │         0 │
│   0 │ 2023-11-20 16:38:02 │     0 │         0 │         0 │
│   0 │ 2023-11-20 16:38:07 │     0 │         0 │         0 │
│   0 │ 2023-11-20 16:38:12 │     0 │         0 │         0 │
│   0 │ 2023-11-20 16:38:17 │     0 │         0 │         0 │
│   0 │ 2023-11-20 16:38:22 │     0 │         0 │         0 │
│   0 │ 2023-11-20 16:38:27 │     0 │         0 │         0 │
│   0 │ 2023-11-20 16:38:32 │     0 │         0 │         0 │
│   0 │ 2023-11-20 16:38:37 │     0 │         0 │         0 │
│   0 │ 2023-11-20 16:38:42 │     0 │         0 │         0 │
│   0 │ 2023-11-20 16:38:47 │     0 │         0 │         0 │
│   0 │ 2023-11-20 16:38:52 │     0 │         0 │         0 │
│   0 │ 2023-11-20 16:38:57 │     0 │         0 │         0 │
│   0 │ 2023-11-20 16:36:00 │     0 │         0 │         0 │ <-----------------
│   0 │ 2023-11-20 16:39:02 │     0 │         0 │         0 │
└─────┴─────────────────────┴───────┴───────────┴───────────┘

35 rows in set. Elapsed: 0.002 sec. 

```

**Review by CurtizJ — APPROVED** [review]

**Pull request merged**
