### PR TITLE
Allow vertical merges from compact to wide parts

### LINKED ISSUE #46084: Make it possible to use Vertical merge algorithm together with parts of Compact type
**Use case**

There is a special algorithm inside ClickHouse for executing background merges called Vertical. It merges only PRIMARY KEY columns first and computes a permutation mask (in what order rows from all source parts should be fetched and written to the result part to get the right result). This algorithm allows ClickHouse server to consume a lot less memory in comparison with default and naive algorithm called Horizontal.  

Unfortunately, ClickHouse may want to assign a merge operation for parts in a Compact format together with parts in a Wide format. In this case this background operation will be executed using Horizonal algorithm and thus may consume a lot of memory.

**Describe the solution you'd like**

Allow using Vertical merge algorithm with parts in Compact format.

### PR DESCRIPTION
**Pull request by CurtizJ**
### Changelog category (leave one):
- Performance Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Allow using Vertical merge algorithm with parts in Compact format. This will allow ClickHouse server to use much less memory for background operations. This closes #46084

### CODE REVIEW

**Review by novikd — APPROVED** [review]

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
Let's mark it as a "Performance improvement", although it is mostly a memory usage improvement.

**Comment by KochetovNicolai** [comment]
Interestingly that for a case of 2 wide parts merge required 674.98 MiB. Looks too much.

**Comment by CurtizJ** [comment]
Seems that it breaks the rolling upgrade. Will reupload under a settings.

**Comment by alexey-milovidov** [comment]
Interesting, how exactly?

**Comment by CurtizJ** [comment]
@alexey-milovidov 

The way how `index_granularity` is computed differs in vertical and horizontal merges. That leads to `CHECKSUM_DOESNT_MATCH` error.

**Comment by alexey-milovidov** [comment]
CHECKSUM_DOESNT_MATCH is not an incompatibility, it is a normal situation during upgrading.

**Comment by CurtizJ** [comment]
Also I'm afraid that this [change](https://github.com/CurtizJ/ClickHouse/blob/7dfea59267eb6ec837753676ac7cd98de8d624cd/src/Storages/MergeTree/MergeTreeDataPartWriterOnDisk.cpp#L162-L166) will trigger `LOGICAL_ERROR` on old version.

**Pull request merged**
