### PR TITLE
Fix race in SecureSocket

### PR DESCRIPTION
**Pull request by nikitamikhaylov**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fixed race on SSL object inside SecureSocket in Poco.

### CODE REVIEW

**Comment by qoega** [comment]
Can we write a test?

**Comment by nikitamikhaylov** [comment]
> Can we write a test?

I've added a concurrent selecting from system.zookeeper in integration test. It catched a race before fixes.

**Comment by nikitamikhaylov** [comment]
#21452

**Comment by nikitamikhaylov** [comment]
Ready to merge

**Review by kitaisreal — APPROVED** [review]

**Pull request merged**
