### PR TITLE
Add new function fromJSONString

### PR DESCRIPTION
**Pull request by taiyang-li**
### Changelog category (leave one):
- New Feature

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Add new function fromJSONString, which make it possible to generate column with complex data types from json string. 

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by den-crane** [comment]
This function looks exactly as JSONExtract

```
 select JSONExtract('{"a": {"i": 1, "f": "2.22", "s": "hello"}}', 'Tuple(Tuple(f Float64, s String, i Int8))');

select fromJSONString('{"a": {"i": 1, "f": "2.22", "s": "hello"}}', 'Map(String, Tuple(f Float64, s String, i Int8))');

```

Why it's not in JSONExtract ?

**Comment by taiyang-li** [comment]
@den-crane  In JSONExtract, we must keep return type exactly the same with what it is in JSON. But in `fromJSONString`, number/string can be cast each other, besides, map/array/tuple can be cast to string. I think it is more friendly and flexible for clickhouse users.

**Comment by taiyang-li** [comment]
Besides,  `JSONExtract` doesn't support map type, which is very important for those users who want to update schema dynamicly. 


```
:)  select JSONExtract('{"a": "b"}', 'Map(String, String)');

SELECT JSONExtract('{"a": "b"}', 'Map(String, String)')

Query id: e98acdd5-7695-481c-9622-ea7e8a3d5e24


0 rows in set. Elapsed: 0.030 sec. 

Received exception from server (version 22.13.1):
Code: 43. DB::Exception: Received from localhost:9000. DB::Exception: Function JSONExtract doesn't support the return type schema: Map(String, String): While processing JSONExtract('{"a": "b"}', 'Map(String, String)'). (ILLEGAL_TYPE_OF_ARGUMENT)

```

**Comment by taiyang-li** [comment]
> Why not extend the ability and flexibility of `JSONExtract` (maybe setting a variable to enable it)? I can't see the necessity of adding a new function with same form of params and sematics.

fromJSONString is the opposite of toJSONString

**Comment by hanfei1991** [comment]
> @den-crane In JSONExtract, we must keep return type exactly the same with what it is in JSON. But in `fromJSONString`, number/string can be cast each other, besides, map/array/tuple can be cast to string. Anyway I think it is more friendly and flexible for clickhouse users.

Not really, for example:
```
hanfei-XPS :) SELECT JSONExtract('{"a": "hello", "b": ["-100", "200.0", "300"]}', 'Tuple(String, Array(Float64))')

SELECT JSONExtract('{"a": "hello", "b": ["-100", "200.0", "300"]}', 'Tuple(String, Array(Float64))')

Query id: 03c7855c-ba99-4131-98e6-5cb2e1e4a9fe

┌─JSONExtract('{"a": "hello", "b": ["-100", "200.0", "300"]}', 'Tuple(String, Array(Float64))')─┐
│ ('hello',[-100,200,300])                                                                      │
└───────────────────────────────────────────────────────────────────────────────────────────────┘
```

We are able to convert type implictly in `JSONExtract`.

To Support `Map`, How about adding a `JSONExtractMap` function?

Add this behaviour `select fromJSONString('["a": "b"]', 'Array(String)'); -> ['a','b']` does not make sense to me. What is it for? It's more like to make JSON flat instead of `fromJSONString`.

@CurtizJ What do you think about it?

**Comment by CurtizJ** [comment]
I agree with Han Fei. I don't see any new features in `fromJSONString` in comparison to `JSONExtract`. `JSONExtract` also support implicit conversions.

```sql
SELECT JSONExtract('{"a": "hello", "b": 200.0}', 'b', 'Int32');

┌─JSONExtract('{"a": "hello", "b": 200.0}', 'b', 'Int32')─┐
│                                                     200 │
└─────────────────────────────────────────────────────────┘

SELECT JSONExtract('{"a": "hello", "b": "200.0"}', 'b', 'Int32');

┌─JSONExtract('{"a": "hello", "b": "200.0"}', 'b', 'Int32')─┐
│                                                         0 │
└───────────────────────────────────────────────────────────┘

SELECT JSONExtract('{"a": "hello", "b": "200"}', 'b', 'Int32');

┌─JSONExtract('{"a": "hello", "b": "200"}', 'b', 'Int32')─┐
│                                                     200 │
└─────────────────────────────────────────────────────────┘
```

Yes, in the second query conversion failed, but I think it's a minor bug and can be easily fixed.

I think it's worth just to add support of `Map` type into `JSONExtract`, because introducing a new function with almost the same functionality is confusing.

```sql
select JSONExtract('["a": "b"]', 'Array(String)'); -> []
select fromJSONString('["a": "b"]', 'Array(String)'); -> ['a','b']
```

This is just incorrect, because this JSON is invalid.
It should be either

```sql
SELECT JSONExtract('["a", "b"]', 'Array(String)')

┌─JSONExtract('["a", "b"]', 'Array(String)')─┐
│ ['a','b']                                  │
└────────────────────────────────────────────┘
```

or 

```sql
SELECT JSONExtract('[{"a": "b"}]', 'Array(Tuple(a String))')

┌─JSONExtract('[{"a": "b"}]', 'Array(Tuple(a String))')─┐
│ [('b')]                                               │
└───────────────────────────────────────────────────────┘
```

**Comment by taiyang-li** [comment]
@hanfei1991  @CurtizJ  thanks for your detailed explaination. I will take your advice to support map/array type in JSONExtract

**Comment by hanfei1991** [comment]
@taiyang-li Thanks for your contribution again! Looking forward to your PRs!

**Pull request closed without merging**
