### PR TITLE
Backport #46367 to 23.1: Do not build libclickhouse-keeper-lib.a for standalone keeper

### PR DESCRIPTION
**Pull request by robot-ch-test-poll1**
Original pull-request #46367
Cherry-pick pull-request #46476

This pull-request is a last step of an automated backporting.
Treat it as a standard pull-request: look at the checks and resolve conflicts.
Merge it only if you intend to backport changes to the target branch, otherwise just     close it.

### CODE REVIEW

**Comment by Felixoid** [comment]
@alexey-milovidov why?

**Comment by alexey-milovidov** [comment]
Insignificant change, not worth looking at.

**Comment by Felixoid** [comment]
It reduces the build time significantly by removing A LOT of THINLTO linking. And even one less unnecessary build.

It really worth to merge back everywhere

**Comment by Felixoid** [comment]
Integration and stree tests are the same as in the PR, the `00933_test_fix_extra_seek_on_compressed_cache` flaps for backports https://play.clickhouse.com/play?user=play#U0VMRUNUICogRlJPTSBjaGVja3MKV0hFUkUgdGVzdF9uYW1lID09ICcwMDkzM190ZXN0X2ZpeF9leHRyYV9zZWVrX29uX2NvbXByZXNzZWRfY2FjaGUnCkFORCB0b0RhdGUoY2hlY2tfc3RhcnRfdGltZSkgPj0gJzIwMjMtMDItMTUnIEFORCB0b0RhdGUoY2hlY2tfc3RhcnRfdGltZSkgPD0gJzIwMjMtMDItMjMnCkFORCB0ZXN0X3N0YXR1cyAhPSAnT0sn

**Pull request merged**
