### PR TITLE
Fix H3 function name (h3ResIsClassIII to h3IsResClassIII)

### PR DESCRIPTION
**Pull request by bharatnc**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Not for changelog

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Rename H3 function `h3ResIsClassIII` to `h3IsResClassIII` to be consistent with the upstream H3 api.

### CODE REVIEW

**Comment by bharatnc** [comment]
@kitaisreal, my bad that I just noticed that this function name is slightly misplaced. It should be `h3IsResClassIII` instead of `h3ResIsClassIII` https://h3geo.org/docs/api/inspection#h3isresclassiii. I guess this is a bug fix (since it will be user visible). Also not sure about compatibility as I noticed that this function is now in v21.7.11.3-stable ?

**Comment by kitaisreal** [comment]
@bharatnc from my perspective we should just merge it without backport or changelog.

**Comment by bharatnc** [comment]
> @bharatnc from my perspective we should just merge it without backport or changelog.

Sure, sounds good to me.

**Review by kitaisreal — APPROVED** [review]

**Comment by kitaisreal** [comment]
@bharatnc could you please check tests failures ?

**Comment by bharatnc** [comment]
> @bharatnc could you please check tests failures ?

:+1: missed renaming the reference file.

**Pull request merged**
