### PR TITLE
Fix a bug moving one partition from one to itself

### LINKED ISSUE #62459: Clickhouse hangs with ALTER MOVE PARTITION TO TABLE when source and destination are the same
**Describe the unexpected behaviour**
Clickhouse enters an unresponsive state if ALTER TABLE MOVE PARTITION TO TABLE uses the same source and destination.

**How to reproduce**
Observed on 23.X and 24.X

```
CREATE TABLE test (v Int16) ENGINE=MergeTree() ORDER BY v PARTITION BY (v % 2);
INSERT INTO test SELECT * FROM numbers(10);
SELECT partition FROM system.parts WHERE table='test';
ALTER TABLE test MOVE PARTITION 1 TO TABLE test;
```
This hangs for a while and then I get
```
Timeout exceeded while receiving data from server. Waited for 300 seconds, timeout is 300 seconds. 
Cancelling query.
```
But that also never completes.

On a second client I can try some other queries
```
SELECT * FROM test
SELECT name FROM system.parts
```
Either of those hang too. 
Some queries don't always hang, for example, this works if run before the ALTER times out. Otherwise, it gets stuck with a progress spinner.
```
SELECT name FROM system.tables
 Progress: 0.00 rows, 0.00 B (0.00 rows/s., 0.00 B/s.)
```
Trying to cancel this with ctrl-c also doesn't work, it just stops the spinner, I have to exit the client.

**Expected behavior**
I should get an immediate success or error message.

### PR DESCRIPTION
**Pull request by helifu**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix [62459](https://github.com/ClickHouse/ClickHouse/issues/62459)

### CODE REVIEW

**Comment by robot-clickhouse** [comment]
*This is an automated comment for commit 7db140c6b335124348f1d4a580eef7ffb9488e67 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/62524/7db140c6b335124348f1d4a580eef7ffb9488e67/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

**Review by yariks5s — COMMENTED** [review]
Could you please write a reproduction test for this bug?

**Comment by helifu** [comment]
> Could you please write a reproduction test for this bug?

Sure:)

**Review by yariks5s — APPROVED** [review]

**Comment by realyota** [comment]
it will be good idea to backport it to 24.3 LTS

**Comment by clickgapai** [comment]
Hi @helifu @yariks5s — while reviewing this PR I found the following:

- **Coverage gap:** `MergeTreeData::movePartitionToTable` `NOT_IMPLEMENTED` throw for non-`MergeTree`-family destination is untested — https://github.com/ClickHouse/ClickHouse/pull/104061

Could you review the test PR and add the `can be tested` label if it looks good?
Happy to discuss — close anything that's wrong or already addressed.

**Pull request merged**
