### PR TITLE
Fix big memory usage for fetch.

### LINKED ISSUE #39915: Do replicated fetches use up RAM and how to prevent it?
We have a big replicated table (~15TB/server compressed) with two replicas. When I tried to add two more replicas on new servers, they started to restart because of OOM:
image

I tried to set the `max_replicated_fetches_network_bandwidth` setting on the new replicas but it didn't help; the RAM usage continues to grow, although more slowly, until it eventually blows up again:
image

I was looking for what's causing it and it appears Clickhouse is fetching the parts into memory first, as the numbers of the below query correlate with the RAM usage reported by the system:
```
SELECT
    database,
    table,
    formatReadableSize(sum(total_size_bytes_compressed)) AS total,
    formatReadableSize(sum(bytes_read_compressed)) AS read
FROM system.replicated_fetches
GROUP BY
    database,
    table

Query id: f7d90b30-04a8-441f-a809-ed8c9f8fdf69

┌─database────────────┬─table────────────┬─total────┬─read─────┐
│ xxxxxxxxxx_20210401 │ xxxxxxxxxxxxxxxx │ 2.29 TiB │ 1.17 TiB │
└─────────────────────┴──────────────────┴──────────┴──────────┘

1 row in set. Elapsed: 0.004 sec. 
```
I can't see any setting that would limit the RAM usage by replicated fetches, and it's also quite unexpected that RAM is used instead of writing the replicated parts straight to the disk. Am I missing something?

### PR DESCRIPTION
**Pull request by KochetovNicolai**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in official stable or prestable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix big memory usage during fetches. Fixes #39915

### CODE REVIEW

**Comment by KochetovNicolai** [comment]
Additionally checked all the calls of writeFile for IDataPartStorage. Looks like it's the only place with such a bug.

**Review by Avogar — APPROVED** [review]

**Comment by KochetovNicolai** [comment]
Nice: Automatic style fix

**Comment by tavplubix** [comment]
What about other places where `file_size` is passed/`adjustBufferSize` is removed?

**Comment by tavplubix** [comment]
Sorry, I got confused, other places look fine

**Review by alexey-milovidov — APPROVED** [review]

**Pull request merged**
