### PR TITLE
Added integration test for session_log using concurrrent GRPC/PostgreSQL/MySQL sessions

### PR DESCRIPTION
**Pull request by Demilivor**
This PR is a part of previously reverted [PR](https://github.com/ClickHouse/ClickHouse/pull/53255)
Added test for session_log using concurrent GRPC/PostgreSQL/MySQL sessions.

PostgreSQL test case temporary skipped because of these fails: https://github.com/ClickHouse/ClickHouse/pull/53255#issuecomment-1674126849

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by robot-clickhouse-ci-2** [comment]
This is an automated comment for commit eb633dc9e5c4722b9c0bad3256c37b7d69b42b90 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/53305/eb633dc9e5c4722b9c0bad3256c37b7d69b42b90/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Comment by alexey-milovidov** [comment]
@tavplubix looks :green_circle: surprisingly :green_apple: green :evergreen_tree:

**Comment by Demilivor** [comment]
The failing test  `test_postgres_session` is temporary disabled.

**Comment by Demilivor** [comment]
ClickHouse several PostgreSQL tests broken:

https://github.com/ClickHouse/ClickHouse/blob/33763e7e50d283d2ad08b7e831c9494c9043ba2f/tests/analyzer_integration_broken_tests.txt#L98C6-L98C25

https://github.com/ClickHouse/ClickHouse/blob/33763e7e50d283d2ad08b7e831c9494c9043ba2f/tests/analyzer_integration_broken_tests.txt#L85

I can rewrite the test using the native PostgreSQL client `psql` instead of disabling it and give the test another chance.

**Comment by Demilivor** [comment]
Update: changed `psycopg2` to native `psql` client.

**Comment by tavplubix** [comment]
> ClickHouse several PostgreSQL tests broken:
> https://github.com/ClickHouse/ClickHouse/blob/33763e7e50d283d2ad08b7e831c9494c9043ba2f/tests/analyzer_integration_broken_tests.txt#L98C6-L98C25

This list is related to "Analyzer", it's a new feature that is currently being developed, and some tests don't work with `allow_experimental_analyzer=1`. The new test for session_log was failing without Analyzer too ([example](https://s3.amazonaws.com/clickhouse-test-reports/0/fd7b92e90aab592594712b074a51ccd00bde5fd5/integration_tests__tsan__%5B2_6%5D.html)), so it's not related

**Comment by Demilivor** [comment]
Ok, thanks for explaining.  It corresponds to this [query](https://play.clickhouse.com/play?user=play#U0VMRUNUIGNoZWNrX3N0YXJ0X3RpbWUsIHB1bGxfcmVxdWVzdF9udW1iZXIsIGNoZWNrX25hbWUsIHRlc3RfbmFtZSwgcmVwb3J0X3VybCwKRlJPTSBjaGVja3MKV0hFUkUgY2hlY2tfc3RhcnRfdGltZSA+PSBub3coKSAtIElOVEVSVkFMIDE0IGRheQogICAgQU5EIHRlc3Rfc3RhdHVzICE9ICdTS0lQUEVEJwogICAgQU5EIHRlc3Rfc3RhdHVzICE9ICdPSycKICAgIEFORCBjaGVja19zdGF0dXMgIT0gJ3N1Y2Nlc3MnCiAgICBBTkQgcG9zaXRpb24odGVzdF9uYW1lLCAncG9zdGdyZXMnKSA+IDAgCiAgICBBTkQgTk9UIHBvc2l0aW9uKGNoZWNrX25hbWUsICdhbmFseXplcicpID4gMCAKT1JERVIgQlkgY2hlY2tfc3RhcnRfdGltZSBERVND).  So this test was the only failing test  with `postgres` substring in name

**Comment by tavplubix** [comment]
Integration tests are ok, the rest checks are entirely broken by https://github.com/ClickHouse/ClickHouse/pull/53354 and similar PRs

**Pull request merged**
