### PR TITLE
Increasing timeout for live view stateless tests

### PR DESCRIPTION
**Pull request by vzakaznikov**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Build/Testing/Packaging Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Increasing timeout for live view stateless tests.

Detailed description / Documentation draft:
Increasing timeout for live view stateless tests.

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
We cannot afford so long tests. I cannot imagine a reason why it requires so large timeout and why increasing timeout may help.

**Comment by alexey-milovidov** [comment]
120 seconds is already large enough to cover possible glitches in CI environment.

**Comment by alexey-milovidov** [comment]
Thank you, but let's not merge this.

**Comment by vzakaznikov** [comment]
> We cannot afford so long tests. I cannot imagine a reason why it requires so large timeout and why increasing timeout may help.

It will not increase test time unless the test fails.

**Comment by vzakaznikov** [comment]
> 120 seconds is already large enough to cover possible glitches in CI environment.

Maybe 600 sec is extreme but I would still consider making timeout a little larger just to make sure it is not CI.

**Comment by vzakaznikov** [comment]
> Thank you, but let's not merge this.

OK, but do we have any statistics on how many time this test fails in the CI to keep an eye for this?

**Comment by alexey-milovidov** [comment]
It failed two times in the last 100 days:
https://github.com/ClickHouse/ClickHouse/pull/23486, e4def2dea2d2b3533918120523df31cb1c403aac
https://github.com/ClickHouse/ClickHouse/pull/8482, 0ac4f0208aad8803479653d75d30a41dfe9ca77b

**Pull request closed without merging**
