### PR TITLE
Merging #24866

### LINKED ISSUE #9770: Add INFORMATION_SCHEMA database
to satisfy (at least some) of SQL92 requirements:

http://www.contrib.andrew.cmu.edu/~shadow/sql/sql1992.txt

We can easily fill those from system:
21.2.4  SCHEMATA view
21.2.7  TABLES view
21.2.8  VIEWS view
21.2.9  COLUMNS view

Rest - should be reviewed, we can fill (where possible), skip or create empty.
 
And that should allow to improve SQL 92 compatibility and fix issues like
https://github.com/ClickHouse/ClickHouse/issues/9769
https://github.com/ClickHouse/ClickHouse/issues/9336 (partially)

The problematic part here is the case insensitivity of those.

### PR DESCRIPTION
**Pull request by tavplubix**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- New Feature

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Added `INFORMATION_SCHEMA` database with `SCHEMATA`, `TABLES`, `VIEWS` and `COLUMNS` views to the corresponding tables in `system` database. Closes #9770.

Detailed description / Documentation draft:
 #24866

### CODE REVIEW

**Comment by tavplubix** [comment]
@Mergifyio update

**Comment by tavplubix** [comment]
@Mergifyio update

**Comment by tavplubix** [comment]
@Mergifyio update

**Review by alexey-milovidov — APPROVED** [review]

**Comment by tavplubix** [comment]
Test failures are irrelevant

**Comment by sevirov** [comment]
Internal documentation ticket: DOCSUP-14981

**Pull request merged**
