### PR TITLE
Update avg_weighted.xml

### PR DESCRIPTION
**Pull request by tavplubix**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

See https://github.com/ClickHouse/ClickHouse/pull/56350 

Logs: https://pastila.nl/?00090cfa/ce75d9e9f04bb35eda73a2e068068d60#+TLUDpFq/8LevyrVOnzgOQ==

### CODE REVIEW

**Comment by robot-ch-test-poll4** [comment]
*This is an automated comment for commit a73297b7194982172e0c059afac6273a3a6708d7 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/56797/a73297b7194982172e0c059afac6273a3a6708d7/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td><a href="https://github.com/ClickHouse/ClickHouse/actions/runs/6879560086">✅ success</a></td></tr>
<tbody>
</table>
</details>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/56797/a73297b7194982172e0c059afac6273a3a6708d7/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Review by Algunenano — APPROVED** [review]

**Comment by tavplubix** [comment]
Something went wrong here:
```
2023-11-16 07:03:27	 + mkdir analyze analyze/tmp
2023-11-16 07:03:27	 + for test_file in *-raw.tsv
2023-11-16 07:03:27	 ++ basename '*-raw.tsv' -raw.tsv
2023-11-16 07:03:27	 + test_name='*'
2023-11-16 07:03:27	 + sed -n 's/^query\t/*\t/p'
2023-11-16 07:03:27	 right/scripts/compare.sh: line 387: *-raw.tsv: No such file or directory
2023-11-16 07:03:27	 + sed -n 's/^profile\t/*\t/p'
2023-11-16 07:03:27	 right/scripts/compare.sh: line 388: *-raw.tsv: No such file or directory
2023-11-16 07:03:27	 + sed -n 's/^client-time\t/*\t/p'
2023-11-16 07:03:27	 right/scripts/compare.sh: line 389: *-raw.tsv: No such file or directory
2023-11-16 07:03:27	 + sed -n 's/^report-threshold\t/*\t/p'
2023-11-16 07:03:27	 right/scripts/compare.sh: line 390: *-raw.tsv: No such file or directory
2023-11-16 07:03:27	 + sed -n 's/^skipped\t/*\t/p'
2023-11-16 07:03:27	 right/scripts/compare.sh: line 391: *-raw.tsv: No such file or directory
2023-11-16 07:03:27	 + sed -n 's/^display-name\t/*\t/p'
2023-11-16 07:03:27	 right/scripts/compare.sh: line 392: *-raw.tsv: No such file or directory
2023-11-16 07:03:27	 + sed -n 's/^partial\t/*\t/p'
2023-11-16 07:03:27	 right/scripts/compare.sh: line 393: *-raw.tsv: No such file or directory
```

**Comment by tavplubix** [comment]
```
2023-11-16 07:03:24	 ++ echo ''
2023-11-16 07:03:24	 ++ wc -w
2023-11-16 07:03:24	 + total_tests=0
2023-11-16 07:03:24	 + current_test=0
2023-11-16 07:03:24	 + test_name='<none>'
```

Looks like a bug in the code that runs changed tests without sampling

**Comment by tavplubix** [comment]
```
2023-11-16 07:03:24	 + test_files=($(sed "s/tests\/performance/${test_prefix//\//\\/}/" changed-test-definitions.txt))
...
2023-11-16 07:03:24	 + for index in "${!test_files[@]}"
2023-11-16 07:03:24	 + '[' 0 '!=' 1 ']'
2023-11-16 07:03:24	 + unset -v 'test_files[$index]'
2023-11-16 07:03:24	 + test_files=("${test_files[@]}")
...
2023-11-16 07:03:24	 + test_files=
```

Fix: https://github.com/ClickHouse/ClickHouse/pull/56881

**Pull request merged**
