### PR TITLE
Make `Pretty` formats even prettier.

### LINKED ISSUE #49153: Pretty formats: squash blocks if not much time passed since output of the previous block.
```
┌─exception_code─┬──count()─┐
│            252 │ 35961274 │
└────────────────┴──────────┘
┌─exception_code─┬─count()─┐
│            645 │  721594 │
└────────────────┴─────────┘
┌─exception_code─┬─count()─┐
│           1001 │  719897 │
└────────────────┴─────────┘
┌─exception_code─┬─count()─┐
│             26 │  679782 │
└────────────────┴─────────┘
┌─exception_code─┬─count()─┐
│             62 │  465018 │
└────────────────┴─────────┘
┌─exception_code─┬─count()─┐
│            241 │  443922 │
└────────────────┴─────────┘
```

This output looks bad.

Let's squash blocks before formatting unless they are large or 100 ms passed since the first block.
The max timeout can be controlled by a setting.

The feature can be implemented by extending the Squashing... something, but it should apply only for pretty formats.

### PR DESCRIPTION
**Pull request by alexey-milovidov**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Make `Pretty` formats prettier: squash blocks if not much time passed since the output of the previous block. This is controlled by a new setting `output_format_pretty_squash_ms` (100ms by default). This closes #49153

### CODE REVIEW

**Comment by robot-ch-test-poll3** [comment]
This is an automated comment for commit 90b0de5677ef0d4e08bebe5507dfe193695d5dae with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/49537/90b0de5677ef0d4e08bebe5507dfe193695d5dae/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Review by qoega — APPROVED** [review]
But tests on Pretty formats need to be updated.

**Comment by alexey-milovidov** [comment]
Unfortunately, a bug has been found:

```
milovidov-desktop :) SET output_format_pretty_squash_ms = 0

SET output_format_pretty_squash_ms = 0

Query id: 70929639-98d4-42d6-bc5e-b3a445c4e333

Ok.

0 rows in set. Elapsed: 0.000 sec. 

milovidov-desktop :) SELECT DISTINCT length(*) FROM file('embeddings2.tsv')

SELECT DISTINCT length(*)
FROM file('embeddings2.tsv')

Query id: f5af7aee-a96a-484e-ac6f-33d7cd3a9068

┌─length(c1)─┐
│        384 │
└────────────┘
Cancelling query.
Query was cancelled.

1 row in set. Elapsed: 1.946 sec. Processed 428.98 thousand rows, 1.49 GB (220.44 thousand rows/s., 763.59 MB/s.)

milovidov-desktop :) SET output_format_pretty_squash_ms = 1

SET output_format_pretty_squash_ms = 1

Query id: 43ae64a4-c0d4-4bf3-b39b-6667b8ba5b5b

Ok.

0 rows in set. Elapsed: 0.000 sec. 

milovidov-desktop :) SELECT DISTINCT length(*) FROM file('embeddings2.tsv')

SELECT DISTINCT length(*)
FROM file('embeddings2.tsv')

Query id: 30c0c029-7957-4832-b803-730f4c75c3d5

┌─length(c1)─┐
│        384 │
└────────────┘
Cancelling query.
Query was cancelled.

1 row in set. Elapsed: 1.648 sec. Processed 552.09 thousand rows, 1.91 GB (334.90 thousand rows/s., 1.16 GB/s.)

milovidov-desktop :) SET output_format_pretty_squash_ms = 100

SET output_format_pretty_squash_ms = 100

Query id: dcfc00bf-47e8-4d76-b414-8af3e503e7e8

Ok.

0 rows in set. Elapsed: 0.000 sec. 

milovidov-desktop :) SELECT DISTINCT length(*) FROM file('embeddings2.tsv')

SELECT DISTINCT length(*)
FROM file('embeddings2.tsv')

Query id: cb6fb3ec-9d1f-4e47-9459-9235900337df

Cancelling query.
┌─length(c1)─┐
│        384 │
└────────────┘
Query was cancelled.

1 row in set. Elapsed: 12.930 sec. Processed 3.55 million rows, 12.28 GB (274.28 thousand rows/s., 950.10 MB/s.)
```

See the last example - it does not output even after 100ms.

**Comment by alexey-milovidov** [comment]
Funny, but this problem is not easily fixable.
It requires an additional processor instead of changing the format.

**Pull request merged**
