### PR TITLE
Docs: Remove obsolete misc page

### PR DESCRIPTION
**Pull request by rschu1ze**
Removes page https://clickhouse.com/docs/en/sql-reference/statements/misc

 It indexes "miscellaneous" SQL statements but these are already easily reachable by the sidebar.

### Changelog category (leave one):
- Documentation (changelog entry is not required)

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
Docs check failed (non zero exit code)

**Comment by rschu1ze** [comment]
@DanRoscigno Totally not urgent but I remember that redirects need to be adjusted when pages are deleted. Since this is a bit of black magic ... would you like to take a look? Thanks.

**Comment by DanRoscigno** [comment]
yup, probably sometime this week once the jetlag wears off ;)

**Comment by rschu1ze** [comment]
Thanks. Jetlag when flying from west to east is the worst 😄

**Pull request merged**
