### PR TITLE
Use only adaptive heuristic to choose task sizes for remote reading

### PR DESCRIPTION
**Pull request by nickitat**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

---

* the main goal is to not use `merge_tree_min_*_for_concurrent_read_for_remote_filesystem` settings anymore to determine the task size. the problem with settings-based approach is that it provides a constant value that doesn't depend on how many columns do we read and how big are those columns. for that we introduced [adaptive heuristic](https://github.com/ClickHouse/ClickHouse/blob/f3df7bd171d3dbc0db72f118146fa9a5b9a0c896/src/Storages/MergeTree/MergeTreeReadPoolBase.cpp#L58-L96). now we want to rely on it at full extent
* a little change was implemented in the heuristic: instead of using the total size of all prewhere columns for estimation we will now choose the max of all prewhere steps (see `getHeaviestSetOfColumnsAmongPrewhereSteps`)
* also there
https://github.com/ClickHouse/ClickHouse/blob/f3df7bd171d3dbc0db72f118146fa9a5b9a0c896/src/Storages/MergeTree/MergeTreeReadPoolBase.cpp#L66
was a bug: we should take the total number of marks in the part instead of the number of marks we plan to read in this query
* this old heuristic
https://github.com/ClickHouse/ClickHouse/blob/67c1e89d90ef576e62f8b1c68269742a3c6f9b1e/src/Storages/MergeTree/MergeTreeIndexGranularity.cpp#L106-L120
was removed since this logic doesn't exist in `MergeTreeReadPool` de-facto for a long time

### CODE REVIEW

**Comment by robot-ch-test-poll1** [comment]
*This is an automated comment for commit d6d55ca3ef58f648c51529dd6a7a92c5ba5d386f with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/69778/d6d55ca3ef58f648c51529dd6a7a92c5ba5d386f/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/69717/e0fc95c894fcd129566b7c374496423e30f94c2c/docs_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Comment by nickitat** [comment]
some issues found so far:

1. this outdated [logic]( https://github.com/ClickHouse/ClickHouse/blob/master/src/Storages/MergeTree/MergeTreeIndexGranularity.cpp#L104-L118) that could be removed based on testing results

2. [here](https://github.com/ClickHouse/ClickHouse/blob/master/src/Storages/MergeTree/MergeTreeReadPoolBase.cpp#L66) we have a small bug. we should take the total number of marks in the part instead of the number of marks we plan to read in this query

3. we have to have a reasonable lower bound on the task size.

4. an interesting example is Q22: 
	``` sql
	SELECT SearchPhrase, MIN(URL), MIN(Title), COUNT(*) AS c, COUNT(DISTINCT UserID) FROM hits WHERE Title LIKE '%Google%' AND URL NOT LIKE '%.google.%' AND SearchPhrase <> '' GROUP BY SearchPhrase ORDER BY c DESC LIMIT 10
	```
	actually it is the only query when the new version is visibly worse than master. the reason is 3/4 columns (and the fourth is negligible in terms of size) are read within PREWHERE. and on top of that we split prewhere on 3 steps each processing its column. so, heuristic considers all prewhere columns altogether and just sums their sizes, while read tasks will read them one-by-one. i guess i'll just try to change this part and will select max among prewhere steps.

**Comment by nickitat** [comment]
`AST fuzzer (debug)` - #70133

**Comment by nickitat** [comment]
`Stateless tests (release, old analyzer, s3, DatabaseReplicated) [2/2] ` - https://github.com/ClickHouse/ClickHouse/issues/70319

**Review by alexey-milovidov — APPROVED** [review]

**Pull request merged**
