### PR TITLE
Implement Three Dots Pattern (...) for select statement

### PR DESCRIPTION
**Pull request by mfridental**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Category (leave one):
- New Feature

Short description (up to few sentences):

It is possible to select several columns by providing a pattern of three dots before or after of a stem, eg.
`select order... from table`
would select `order_price`, `order_date`, etc.

Detailed description (optional):
We're having tables with more than 700 columns. Having such a big amount of columns make it hard to handle them comfortably, so we impose a semantic structure upon them using a naming convention regarding prefixes and/or suffixes as parts of column names. This feature should make selection of subgroups of columns easier.
I've considered reusing the star` "*"` to make it uniform with a `"select *",` but then there is an ambiguity for example between` "select a* b from"` (a multiplication of two fields) and` "select a* from"`, requiring a more complicated Lexer and/or Parsers.

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
This is very interesting and unusual feature!

But we need to consider all possible alternative implementation options... because syntax extension is the most intrusive implementation possible. I will ask my collegues and community members, what they think.

For example, another possible option is to use quoted column names with special characters:
```
SELECT `order*` FROM table
```
(it will also break backward compatibility, because the column name "order*" is technically possible)

**Comment by alexey-milovidov** [comment]
Another option is to add COLUMNS keyword to select columns by regexp:
```
SELECT a, COLUMNS('x.+'), b FROM table
```

**Comment by alexey-milovidov** [comment]
@blinkov has pointed out to the related feature: https://cloud.google.com/bigquery/docs/reference/standard-sql/query-syntax#select-except

**Comment by alexey-milovidov** [comment]
We came to the conclusion, that `COLUMNS('^x')` is the right solution.

**Review by alexey-milovidov — CHANGES_REQUESTED** [review]
At least you don't have to modify lexer :)

**Comment by mfridental** [comment]
I agree that COLUMNS is a better syntax. Also, in the second step I wanted to extend that to be able to retrieve only columns having at least one not-null and not-default value in them. Not sure whether is it possible with good performance, but what might be the syntax for that, something like `COLUMNS('.*') IF NOT EMPTY`? Do we really need the brackets or can it be like
`COLUMNS '^stem' [IF NOT EMPTY]`

**Comment by alexey-milovidov** [comment]
I have started code review and planning to merge today.

> Do we really need the brackets

We need brackets, because
`table.COLUMNS('a\\d+')`
will look much better than
`table.COLUMNS 'a\\d+'`

> Also, in the second step I wanted to extend that to be able to retrieve only columns having at least one not-null and not-default value in them.

How will you select these columns in query analysis stage?

**Comment by alexey-milovidov** [comment]
Continued in #6038

**Comment by alexey-milovidov** [comment]
What I have changed:

1. Made parentheses mandatory to allow `table.COLUMNS('regexp')` in future.
2. Made regexp non-anchored to be consistent with `merge` table function.
3. Renamed ColumnsClause to ColumnsMatcher, because it doesn't look similar to SELECT, WHERE, HAVING... clauses.
4. Fixed error in AST formatting (there was no escaping).

TODO:

Tests where no columns have matched.
Tests for JOINs and predicate pushdown.
Allow qualified expressions.

**Pull request merged**
