### PR TITLE
continue translate domain data type

### PR DESCRIPTION
**Pull request by zhang2014**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Category:
- Document

Short description (up to few sentences):
continue #6202

### CODE REVIEW

**Comment by zhang2014** [comment]
@blinkov

**Comment by alexey-milovidov** [comment]
@zhang2014 You have pasted articles in a symlink path :rofl: :laughing: that effectively broke my repository (cannot create symlink, file name too long):

```
~/ClickHouse/docs/zh/data_types/domains$ ls -l
total 12
lrwxrwxrwx 1 milovidov dpt_yandex_monetize_metrica_dev_stat 3310 авг  6 17:41 ipv4.md -> '''## IPv4'$'\n\n''`IPv4`是与`UInt32`类型保持二进制兼容的Domain类型，其用于存储IPv4地址的值。它提供了更为紧凑的二进制存储的同时支持识别可读性更加友好的输入输出格式。'$'\n\n''### 基本使用'$'\n\n''``` sql'$'\n''CREATE TABLE hits (url String, from IPv4) ENGINE = MergeTree() ORDER BY url;'$'\n\n''DESCRIBE TABLE hits;'$'\n''```'$'\n\n''```'$'\n''┌─name─┬─type───┬─default_type─┬─default_expression─┬─comment─┬─codec_expression─┐'$'\n''│ url  │ String │              │                    │         │                  │'$'\n''│ from │ IPv4   │              │                    │         │                  │'$'\n''└──────┴────────┴──────────────┴────────────────────┴─────────┴──────────────────┘'$'\n''```'$'\n\n''同时您也可以使用`IPv4`类型的列作为主键：'$'\n\n''``` sql'$'\n''CREATE TABLE hits (url String, from IPv4) ENGINE = MergeTree() ORDER BY from;'$'\n''```'$'\n\n''在写入与查询时，`IPv4`类型能够识别可读性更加友好的输入输出格式：'$'\n\n''``` sql'$'\n''INSERT INTO hits (url, from) VALUES ('\''https://wikipedia.org'\'', '\''116.253.40.133'\'')('\''https://clickhouse.yandex'\'', '\''183.247.232.58'\'')('\''https://clickhouse.yandex/docs/en/'\'', '\''116.106.34.242'\'');'$'\n\n''SELECT * FROM hits;'$'\n''```'$'\n\n''```'$'\n''┌─url────────────────────────────────┬───────────from─┐'$'\n''│ https://clickhouse.yandex/docs/en/ │ 116.106.34.242 │'$'\n''│ https://wikipedia.org              │ 116.253.40.133 │'$'\n''│ https://clickhouse.yandex          │ 183.247.232.58 │'$'\n''└────────────────────────────────────┴────────────────┘'$'\n''```'$'\n\n''同时它提供更为紧凑的二进制存储格式：'$'\n\n''``` sql'$'\n''SELECT toTypeName(from), hex(from) FROM hits LIMIT 1;'$'\n''```'$'\n\n''```'$'\n''┌─toTypeName(from)─┬─hex(from)─┐'$'\n''│ IPv4             │ B7F7E83A  │'$'\n''└──────────────────┴───────────┘'$'\n''```'$'\n\n''不可隐式转换为除`UInt32`以外的其他类型类型。如果要将`IPv4`类型的值转换成字符串，你可以使用`IPv4NumToString()`显示的进行转换：'$'\n\n''``` sql'$'\n''SELECT toTypeName(s), IPv4NumToString(from) as s FROM hits LIMIT 1;'$'\n''```'$'\n\n''```'$'\n''┌─toTypeName(IPv4NumToString(from))─┬─s──────────────┐'$'\n''│ String                            │ 183.247.232.58 │'$'\n''└───────────────────────────────────┴────────────────┘'$'\n''```'$'\n\n''或可以使用`CAST`将它转换为`UInt32`类型:'$'\n\n''``` sql'$'\n''SELECT toTypeName(i), CAST(from as UInt32) as i FROM hits LIMIT 1;'$'\n''```'$'\n\n''```'$'\n''┌─toTypeName(CAST(from, '\''UInt32'\''))─┬──────────i─┐'$'\n''│ UInt32                           │ 3086477370 │'$'\n''└──────────────────────────────────┴────────────┘'$'\n''```'$'\n\n''[来源文章](https://clickhouse.yandex/docs/en/data_types/domains/ipv4) <!--hide-->'$'\n'
lrwxrwxrwx 1 milovidov dpt_yandex_monetize_metrica_dev_stat 3788 авг  6 17:41 ipv6.md -> '''## IPv6'$'\n\n''`IPv6`是与`FixedString(16)`类型保持二进制兼容的Domain类型，其用于存储IPv6地址的值。它提供了更为紧凑的二进制存储的同时支持识别可读性更加友好的输入输出格式。'$'\n\n''### 基本用法'$'\n\n''``` sql'$'\n''CREATE TABLE hits (url String, from IPv6) ENGINE = MergeTree() ORDER BY url;'$'\n\n''DESCRIBE TABLE hits;'$'\n''```'$'\n\n''```'$'\n''┌─name─┬─type───┬─default_type─┬─default_expression─┬─comment─┬─codec_expression─┐'$'\n''│ url  │ String │              │                    │         │                  │'$'\n''│ from │ IPv6   │              │                    │         │                  │'$'\n''└──────┴────────┴──────────────┴────────────────────┴─────────┴──────────────────┘'$'\n''```'$'\n\n''同时您也可以使用`IPv6`类型的列作为主键：'$'\n\n''``` sql'$'\n''CREATE TABLE hits (url String, from IPv6) ENGINE = MergeTree() ORDER BY from;'$'\n''```'$'\n\n''在写入与查询时，`IPv6`类型能够识别可读性更加友好的输入输出格式：'$'\n\n''``` sql'$'\n''INSERT INTO hits (url, from) VALUES ('\''https://wikipedia.org'\'', '\''2a02:aa08:e000:3100::2'\'')('\''https://clickhouse.yandex'\'', '\''2001:44c8:129:2632:33:0:252:2'\'')('\''https://clickhouse.yandex/docs/en/'\'', '\''2a02:e980:1e::1'\'');'$'\n\n''SELECT * FROM hits;'$'\n''```'$'\n\n''```'$'\n''┌─url────────────────────────────────┬─from──────────────────────────┐'$'\n''│ https://clickhouse.yandex          │ 2001:44c8:129:2632:33:0:252:2 │'$'\n''│ https://clickhouse.yandex/docs/en/ │ 2a02:e980:1e::1               │'$'\n''│ https://wikipedia.org              │ 2a02:aa08:e000:3100::2        │'$'\n''└────────────────────────────────────┴───────────────────────────────┘'$'\n''```'$'\n\n''同时它提供更为紧凑的二进制存储格式：'$'\n\n''``` sql'$'\n''SELECT toTypeName(from), hex(from) FROM hits LIMIT 1;'$'\n''```'$'\n\n''```'$'\n''┌─toTypeName(from)─┬─hex(from)────────────────────────┐'$'\n''│ IPv6             │ 200144C8012926320033000002520002 │'$'\n''└──────────────────┴──────────────────────────────────┘'$'\n''```'$'\n\n''不可隐式转换为除`FixedString(16)`以外的其他类型类型。如果要将`IPv6`类型的值转换成字符串，你可以使用`IPv6NumToString()`显示的进行转换：'$'\n\n''``` sql'$'\n''SELECT toTypeName(s), IPv6NumToString(from) as s FROM hits LIMIT 1;'$'\n''```'$'\n\n''```'$'\n''┌─toTypeName(IPv6NumToString(from))─┬─s─────────────────────────────┐'$'\n''│ String                            │ 2001:44c8:129:2632:33:0:252:2 │'$'\n''└───────────────────────────────────┴───────────────────────────────┘'$'\n''```'$'\n\n''或使用`CAST`将其转换为`FixedString(16)`：'$'\n\n''``` sql'$'\n''SELECT toTypeName(i), CAST(from as FixedString(16)) as i FROM hits LIMIT 1;'$'\n''```'$'\n\n''```'$'\n''┌─toTypeName(CAST(from, '\''FixedString(16)'\''))─┬─i───────┐'$'\n''│ FixedString(16)                           │  ��� │'$'\n''└───────────────────────────────────────────┴─────────┘'$'\n''```'$'\n\n''[来源文章](https://clickhouse.yandex/docs/en/data_types/domains/ipv6) <!--hide-->'$'\n'
lrwxrwxrwx 1 milovidov dpt_yandex_monetize_metrica_dev_stat 1495 авг  6 17:41 overview.md -> '# Domains'$'\n\n''Domain类型是特定实现的类型，它总是与某个现存的基础类型保持二进制兼容的同时添加一些额外的特性，以能够在维持磁盘数据不变的情况下使用这些额外的特性。目前ClickHouse暂不支持自定义domain类型。'$'\n\n''如果你可以在一个地方使用与Domain类型二进制兼容的基础类型，那么在相同的地方您也可以使用Domain类型，例如：'$'\n\n''* 使用Domain类型作为表中列的类型'$'\n''* 对Domain类型的列进行读/写数据'$'\n''* 如果与Domain二进制兼容的基础类型可以作为索引，那么Domain类型也可以作为索引'$'\n''* 将Domain类型作为参数传递给函数使用'$'\n''* 其他'$'\n\n''### Domains的额外特性'$'\n\n''* 在执行SHOW CREATE TABLE 或 DESCRIBE TABLE时，其对应的列总是展示为Domain类型的名称'$'\n''* 在INSERT INTO domain_table(domain_column) VALUES(...)中输入数据总是以更人性化的格式进行输入'$'\n''* 在SELECT domain_column FROM domain_table中数据总是以更人性化的格式输出'$'\n''* 在INSERT INTO domain_table FORMAT CSV ...中，实现外部源数据以更人性化的格式载入'$'\n\n''### Domains类型的限制'$'\n\n''* 无法通过`ALTER TABLE`将基础类型的索引转换为Domain类型的索引。'$'\n''* 当从其他列或表插入数据时，无法将string类型的值隐式地转换为Domain类型的值。'$'\n''* 无法对存储为Domain类型的值添加约束。'$'\n\n''[来源文章](https://clickhouse.yandex/docs/en/data_types/domains/overview) <!--hide-->'$'\n'
```

**Comment by alexey-milovidov** [comment]
I have reverted your commit, please make another PR.

**Comment by zhang2014** [comment]
sorry very much, I didn't notice that

**Pull request merged**
