### PR TITLE
Fix UB in StoragesInfoStream

### PR DESCRIPTION
**Pull request by tavplubix**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Category (leave one):
- Bug Fix

Short description (up to few sentences):
`offsets[i]` was not been initialized for `Lazy` databases

### CODE REVIEW

**Review by akuzm — APPROVED** [review]
If it's a user-visible bug, the description for changelog should be in user terms (i.e. system.parts can show wrong records if there is a Lazy database).
If it isn't, we probably don't want to backport it, and can mark it as pr-build instead of pr-bugfix.

**Comment by tavplubix** [comment]
It rather leads to segfaults, sanitizer reports or exceptions like `Cannot mmap 4.00 EiB`, then to wrong records.

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
> File access error: no space left on device

- CI infrastructure issue @alesapin

**Comment by akuzm** [comment]
backport conflict in 19.15

**Pull request merged**
