### PR TITLE
Disable `deltaLake` and `hudi` table functions in readonly mode

### PR DESCRIPTION
**Pull request by antonio2368**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Disable `deltaLake` and `hudi` table functions in readonly mode.

cc @SmitaRKulkarni  tell me if I missed something

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]

**Review by SmitaRKulkarni — APPROVED** [review]
LGTM

**Comment by ucasfl** [comment]
Hi, what does `allow_readonly` means?

**Comment by antonio2368** [comment]
@ucasfl recently we enabled some table functions for readonly mode, previously all of them were disabled for security reasons.
deltaLake and hudi have network access so it's better if we disable them.
I tagged you just for informative reasons as the author of the original PR.

**Comment by ucasfl** [comment]
> @ucasfl recently we enabled some table functions for readonly mode, previously all of them were disabled for security reasons. deltaLake and hudi have network access so it's better if we disable them. I tagged you just for informative reasons as the author of the original PR.

Why `cluster` is `allow_readonly` but `remote` is not?

**Comment by alexey-milovidov** [comment]
It is determined by the possibility of making requests to arbitrary hostnames.

If users can make a request to an arbitrary hostname, they can get the info from the internal network or manipulate internal APIs (say - put some data into Memcached, which is available only in the corporate network). This is named "SSRF attack".

Or a user can use an open ClickHouse server to amplify DoS attacks.

**Pull request merged**
