### PR TITLE
Maybe fix false MSan report in GRPC

### PR DESCRIPTION
**Pull request by alexey-milovidov**
Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by alesapin** [comment]
But why "maybe"? It's 100% false positive and we have the same fixes for some other libraries.

**Review by alesapin — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
I did not reproduce it - did not check that the fix has effect.
Moreover, we disabled Integration tests with MSan in PRs, so we will have to merge blindly.

**Comment by alexey-milovidov** [comment]
> ClickHouse special build check — Some exception occurred :( 

`RateLimitExceededException: 403 {"documentation_url": "https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting", "message": "API rate limit exceeded for user ID 41385210."}`

**Comment by alexey-milovidov** [comment]
> AST fuzzer (TSan) — Lost connection to server. See the logs. 

OOM.

**Comment by alexey-milovidov** [comment]
Let's check in master.

**Pull request merged**
