### PR TITLE
Enable projections and zero copy replication

### PR DESCRIPTION
**Pull request by alesapin**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Now projections can be used with zero copy replication.

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
I don't understand:
- why do we need some separate methods to send projections, why don't send the data part as a whole?
- what are the .proj files and why do we skip them? Maybe duplicate a comment about them?

**Comment by alexey-milovidov** [comment]
I still don't understand, what is special about projection files. Why don't treat everything as a directory tree while transferring?

**Comment by alesapin** [comment]
> I still don't understand, what is special about projection files. Why don't treat everything as a directory tree while transferring?

Honestly I don't understand your question. We send projection name, we send whole projection checksums (name.proj) inside "parent" checksums. And what is special here? It's quite convenient to use recursive calls of the same functions to send and download projections. If we wound send part with projections just as directory tree we will need more complex logic to understand which file related to which projection and build projection parts inside loop.

**Comment by alesapin** [comment]
Failures unrelated, let's merge

**Pull request merged**
