### PR TITLE
Ignore ON CLUSTER clause in queries for management of replicated named collections.

### PR DESCRIPTION
**Pull request by MikhailBurdukov**
Add settings to ignore ON CLUSTER clause in queries for named collection management with replicated storage.
It is necessary for seamless migration of the existing codebase to replicated storage without changing current SQL queries. 
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Add settings to ignore ON CLUSTER clause in queries for named collection management with replicated storage.

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-clickhouse** [comment]
*This is an automated comment for commit 9fc557ad65ab0a306e417d01ea0b4636a0569824 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/66288/9fc557ad65ab0a306e417d01ea0b4636a0569824/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/4add9db84859bff7410cf934a3904b0414e36e51/docs_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Comment by den-crane** [comment]
this is kinda inconsistent with other entities

```
CREATE USER dfsdfsdfsd ON CLUSTER segmented

Query id: 66a80520-58af-4049-af84-ec42d686e059

Connecting to localhost:9000 as user default.
Connected to ClickHouse server version 24.3.4.

   ┌─host────────────────────────┬─port─┬─status─┬─error─┬─num_hosts_remaining─┬─num_hosts_active─┐
1. │ chdw1-1.sde10190.mycmdb.net │ 9000 │      0 │       │                   1 │                0 │
   └─────────────────────────────┴──────┴────────┴───────┴─────────────────────┴──────────────────┘
   ┌─host────────────────────────┬─port─┬─status─┬─error───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬─num_hosts_remaining─┬─num_hosts_active─┐
2. │ chdw1-1.sde10186.mycmdb.net │ 9000 │    493 │ Code: 493. DB::Exception: user `dfsdfsdfsd`: cannot insert because user `dfsdfsdfsd` already exists in replicated. (ACCESS_ENTITY_ALREADY_EXISTS) (version 24.3.4.147 (official build)) │                   0 │                0 │
   └─────────────────────────────┴──────┴────────┴─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴─────────────────────┴──────────────────┘
```

**Review by kssenii — APPROVED** [review]

**Comment by MikhailBurdukov** [comment]
> this is kinda inconsistent with other entities
> 
> ```
> CREATE USER dfsdfsdfsd ON CLUSTER segmented
> 
> Query id: 66a80520-58af-4049-af84-ec42d686e059
> 
> Connecting to localhost:9000 as user default.
> Connected to ClickHouse server version 24.3.4.
> 
>    ┌─host────────────────────────┬─port─┬─status─┬─error─┬─num_hosts_remaining─┬─num_hosts_active─┐
> 1. │ chdw1-1.sde10190.mycmdb.net │ 9000 │      0 │       │                   1 │                0 │
>    └─────────────────────────────┴──────┴────────┴───────┴─────────────────────┴──────────────────┘
>    ┌─host────────────────────────┬─port─┬─status─┬─error───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬─num_hosts_remaining─┬─num_hosts_active─┐
> 2. │ chdw1-1.sde10186.mycmdb.net │ 9000 │    493 │ Code: 493. DB::Exception: user `dfsdfsdfsd`: cannot insert because user `dfsdfsdfsd` already exists in replicated. (ACCESS_ENTITY_ALREADY_EXISTS) (version 24.3.4.147 (official build)) │                   0 │                0 │
>    └─────────────────────────────┴──────┴────────┴─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴─────────────────────┴──────────────────┘
> ```

AFAIK it is expected behaviour. For ignoring `ON CLUSTER` in access entities management queries you should use `ignore_on_cluster_for_replicated_access_entities_queries`  opt. It's disabled by default.

**Comment by MikhailBurdukov** [comment]
Failed tests seems unrelated, can we merge? @kssenii

**Comment by kssenii** [comment]
> AST fuzzer (ubsan) 

https://github.com/ClickHouse/ClickHouse/issues/64945

**Pull request merged**
