### PR TITLE
added 'questions' section to English reference

### PR DESCRIPTION
**Pull request by Ngalstyan4**
This is a great product, thank you for open sourcing it!

While reading through the documentation I realized that there is a section missing from English version of the reference so I translated it so it is reachable to a bigger community

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
Great, thanks!
Please, do some cleanup of missing/excessive whitespaces here:
```
operation(partial reduce)
streaming mode,so can
In 2014-2016 YT  is to develop
sorting " functionality  using
```

**Comment by Ngalstyan4** [comment]
Done, 

A couple of points:
Shark for Spark is deprecated. Spark SQL is actually a replacement of Shark so I am not sure if both should be mentioned.

Also, I did not get what YT is referring to. Is it [yt-project](http://yt-project.org/ )
In any case shall a link be added?

**Comment by alexey-milovidov** [comment]
> Shark for Spark is deprecated. Spark SQL is actually a replacement of Shark so I am not sure if both should be mentioned.

Ok. Shark could be removed from text, or added note about obsoleteness... but it doesn't matter much.

> Also, I did not get what YT is referring to. Is it yt-project
In any case shall a link be added?

No, it is completely different proprietary product. 
Here is presentation in english:
https://yandexdataschool.ru/about/conference/program/babenko
In russian:
https://events.yandex.ru/lib/talks/1091/
http://www.slideshare.net/yandex/yt-26753367

Links could be added, as you wish.

**Comment by alexey-milovidov** [comment]
Merged.
By the way, it is not Markdown.

Replaced links with
```
\[([^\]]+)\]\((http[^\)]+)\)
```
to
```
<a href="\2">\1</a>
```

**Comment by alexey-milovidov** [comment]
https://github.com/yandex/ClickHouse/commit/708c6e532b570da561741cce55044501710fde75

**Pull request merged**
