### PR TITLE
Force clickhouse-test to use python2

### PR DESCRIPTION
**Pull request by azat**
Changelog category (leave one):
- Non-significant (changelog entry is not required)

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
Ok.

BTW, we already decided to migrate all Python scripts to Python 3.

**Review by alexey-milovidov — APPROVED** [review]

**Comment by azat** [comment]
>BTW, we already decided to migrate all Python scripts to Python 3.

Yes I though that it will be better to migrate them to python3, but decided not to look into this since this will (at least) require updating some docker images.

**Comment by alexey-milovidov** [comment]
No problem, just modify Dockerfiles and we will rebuild images.

**Review by alesapin — APPROVED** [review]
LGTM. `Split build smoke test` looks like flap.

**Comment by azat** [comment]
>BTW, we already decided to migrate all Python scripts to Python 3.

@alexey-milovidov do you have any progress on this? (I already have some changes for this, but I can wait if you are working on this)

**Pull request merged**
