### PR TITLE
Cherry pick #52161 to 22.8: Fix error in `groupArrayMoving` functions

### PR DESCRIPTION
**Pull request by robot-clickhouse**
Original pull-request #52161

This pull-request is a first step of an automated backporting.
It contains changes like after calling a local command `git cherry-pick`.
If you intend to continue backporting this changes, then resolve all conflicts if any.
Otherwise, if you do not want to backport them, then just close this pull-request.

The check results does not matter at this step - you can safely ignore them.

### Note

This pull-request will be merged automatically as it reaches the mergeable state, **do not merge it manually**.

### If the PR was closed and then reopened

If it stuck, check https://github.com/ClickHouse/ClickHouse/pull/52161 for `pr-backports-created` and delete it if necessary. Manually merging will do nothing, since `pr-backports-created` prevents the original PR https://github.com/ClickHouse/ClickHouse/pull/52161 from being processed.

If you want to recreate the PR: delete the `pr-cherrypick` label and delete this branch.
You may also need to delete the `pr-backports-created` label from the original PR.

### CODE REVIEW

**Comment by robot-ch-test-poll3** [comment]
Dear @alexey-milovidov, the PR is not updated for 1d1h24m58s. Please, either resolve the conflicts, or close it to finish the backport process of #52161

**Comment by robot-ch-test-poll3** [comment]
Dear @alexey-milovidov, the PR is not updated for 1d0h0m24s. Please, either resolve the conflicts, or close it to finish the backport process of #52161

**Comment by robot-ch-test-poll3** [comment]
Dear @alexey-milovidov, the PR is not updated for 1d0h1m1s. Please, either resolve the conflicts, or close it to finish the backport process of #52161

**Comment by robot-ch-test-poll** [comment]
Dear @alexey-milovidov, the PR is not updated for 1d0h52m19s. Please, either resolve the conflicts, or close it to finish the backport process of #52161

**Comment by robot-ch-test-poll3** [comment]
Dear @alexey-milovidov, the PR is not updated for 1d0h39m41s. Please, either resolve the conflicts, or close it to finish the backport process of #52161

**Comment by robot-ch-test-poll3** [comment]
Dear @alexey-milovidov, the PR is not updated for 1d0h1m38s. Please, either resolve the conflicts, or close it to finish the backport process of #52161

**Comment by robot-ch-test-poll3** [comment]
Dear @alexey-milovidov, the PR is not updated for 1d0h58m27s. Please, either resolve the conflicts, or close it to finish the backport process of #52161

**Comment by robot-clickhouse-ci-1** [comment]
Dear @alexey-milovidov, the PR is not updated for 1d0h1m45s. Please, either resolve the conflicts, or close it to finish the backport process of #52161

**Comment by robot-ch-test-poll3** [comment]
Dear @alexey-milovidov, the PR is not updated for 1d0h1m16s. Please, either resolve the conflicts, or close it to finish the backport process of #52161

**Comment by robot-ch-test-poll1** [comment]
Dear @alexey-milovidov, the PR is not updated for 1d0h59m29s. Please, either resolve the conflicts, or close it to finish the backport process of #52161

**Comment by robot-ch-test-poll3** [comment]
Dear @alexey-milovidov, the PR is not updated for 1d0h57m31s. Please, either resolve the conflicts, or close it to finish the backport process of #52161

**Comment by robot-ch-test-poll1** [comment]
Dear @alexey-milovidov, the PR is not updated for 1d0h1m13s. Please, either resolve the conflicts, or close it to finish the backport process of #52161

**Comment by robot-ch-test-poll2** [comment]
Dear @alexey-milovidov, the PR is not updated for 1d0h59m5s. Please, either resolve the conflicts, or close it to finish the backport process of #52161

**Comment by robot-ch-test-poll1** [comment]
Dear @alexey-milovidov, the PR is not updated for 1d0h1m41s. Please, either resolve the conflicts, or close it to finish the backport process of #52161

**Comment by robot-ch-test-poll1** [comment]
Dear @alexey-milovidov, the PR is not updated for 1d0h58m9s. Please, either resolve the conflicts, or close it to finish the backport process of #52161

**Comment by robot-ch-test-poll** [comment]
Dear @alexey-milovidov, the PR is not updated for 1d0h0m50s. Please, either resolve the conflicts, or close it to finish the backport process of #52161

**Comment by robot-ch-test-poll1** [comment]
Dear @alexey-milovidov, the PR is not updated for 1d0h5m46s. Please, either resolve the conflicts, or close it to finish the backport process of #52161

**Pull request closed without merging**
