### PR TITLE
 Compatible with LowCardinality type data write

### PR DESCRIPTION
**Pull request by nicelulu**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
Looks reasonable.
As I understand, the case is when you shard by a function of LowCardinality data type.
But there is lack of test and comment.

**Comment by nicelulu** [comment]
```
CREATE TABLE db.table_all ( id String ) ENGINE = Distributed(cluster1, db, table, sipHash64(id))
ALTER TABLE db.table_all MODIFY COLUMN id LowCardinality(String)
INSERT INTO db.table_all (id) VALUES ('123')
 DB::Exception: Sharding key expression does not evaluate to an integer type
```

The user uses ALTER to modify the field type to LowCardinality.
The function of type LowCardinality needs to be the same as the result of the function used before, otherwise the user needs to re-import the historical data, which seems to me to be the same as the effect of my modification.

**Comment by alexey-milovidov** [comment]
Ok. Still waiting for a test and code comment.

**Comment by alexey-milovidov** [comment]
The code does not compile.

**Comment by nicelulu** [comment]
> Ok. Still waiting for a test and code comment.

Done.

**Pull request merged**
