### PR TITLE
Add arrayReverseSort, arraySort to docs

### PR DESCRIPTION
**Pull request by wingrime**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
The functions are capable to sort the array according to transformed values.
Please check the test: https://github.com/yandex/ClickHouse/blob/master/dbms/tests/queries/0_stateless/00390_array_sort.sql

**Comment by alexey-milovidov** [comment]
These functions should be in "higher order functions" as they accept a function as an optional first argument. "Schwartzsort" algorithm should be mentioned with a link to Wikipedia article.

**Comment by wingrime** [comment]
> No mention about behaviour on NULLs and NaNs

I can't deduce it from code, there is no special code for NaN handing in implementation of arrayReverseSort,arraySort If it's comm,on

**Comment by alexey-milovidov** [comment]
NaNs and NULLs are last (with NaNs before NULLs).
It is described in `IColumn::compareAt` (look at `nan_direction_hint` parameter).

**Comment by alexey-milovidov** [comment]
```
SELECT arraySort([1, nan, 2, NULL, 3, nan, 4, NULL])

┌─arraySort([1, nan, 2, NULL, 3, nan, 4, NULL])─┐
│ [1,2,3,4,nan,nan,NULL,NULL]                   │
└───────────────────────────────────────────────┘

1 rows in set. Elapsed: 0.083 sec. 

SELECT arrayReverseSort([1, nan, 2, NULL, 3, nan, 4, NULL])

┌─arrayReverseSort([1, nan, 2, NULL, 3, nan, 4, NULL])─┐
│ [4,3,2,1,nan,nan,NULL,NULL]                          │
└──────────────────────────────────────────────────────┘
```

**Pull request merged**
