### PR TITLE
Reduce peak memory while executing filter

### PR DESCRIPTION
**Pull request by taiyang-li**
### Changelog category (leave one):
- Performance Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Trivial optimize on column filter. Avoid those filter columns whoes underlying data type is not number being filtered with `result_size_hint = -1`.  Peak memory can be reduced to 44% of the original in some cases.

### CODE REVIEW

**Comment by robot-ch-test-poll3** [comment]
*This is an automated comment for commit c4d84ff9fd0e2b6d41225d2b8fac658f64729013 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/59698/c4d84ff9fd0e2b6d41225d2b8fac658f64729013/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/59698/c4d84ff9fd0e2b6d41225d2b8fac658f64729013/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Review by jsc0218 — APPROVED** [review]

**Comment by jsc0218** [comment]
probably update once so less check fails.

**Comment by taiyang-li** [comment]
``` sql 
create table  test_filter engine = Memory as  select * from generateRandom('t Tuple(a Decimal256(3), b Float64, c Int256), i8 Int8, i16 Int16', 1, 19, 2) limit 100000000;   

select * from test_filter where i16 > 100 format Null;  

Old: Peak memory usage: 182.95 MiB.
New: Peak memory usage: 182.94 MiB. 

```

**Comment by taiyang-li** [comment]
@jsc0218  is it ok to merge it now? Thanks!

**Pull request merged**
