### PR TITLE
[bugfix] possible postgresql logical replication error: wrong type conversion

### PR DESCRIPTION
**Pull request by takakawa**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
- Fix  possible postgresql logical replication  conversion_error when using MaterializedPostgreSQL

### Documentation entry for user-facing changes
```
2023.08.14 20:16:59.971005 [ 4326 ] {} <Error> void DB::DatabaseMaterializedPostgreSQL::startSynchronization(): std::exception. Code: 1001, type: pqxx::conversion_error, e.what() = Could not convert string to numeric value: 'male'., Stack trace (when copying this message, always include the lines below):

0. ./build_docker/../contrib/libpqxx/src/except.cxx:98: pqxx::internal::float_traits<double>::from_string(std::__1::basic_string_view<char, std::__1::char_traits<char> >) @ 0x16b8cf0a in /usr/lib/debug/usr/bin/clickhouse.debug
1. ./build_docker/../src/Common/PODArray.h:436: DB::insertPostgreSQLValue(DB::IColumn&, std::__1::basic_string_view<char, std::__1::char_traits<char> >, DB::ExternalResultDescription::ValueType, std::__1::shared_ptr<DB::IDataType const>, std::__1::unordered_map<unsigned long, DB::PostgreSQLArrayInfo, std::__1::hash<unsigned long>, std::__1::equal_to<unsigned long>, std::__1::allocator<std::__1::pair<unsigned long const, DB::PostgreSQLArrayInfo> > >&, unsigned long) @ 0x11b740d2 in /usr/lib/debug/usr/bin/clickhouse.debug
2. ./build_docker/../src/Processors/Transforms/PostgreSQLSource.cpp:156: DB::PostgreSQLSource<pqxx::transaction<(pqxx::isolation_level)1, (pqxx::write_policy)0> >::generate() @ 0x78b6e39 in /usr/lib/debug/usr/bin/clickhouse.debug
3. ./build_docker/../src/Processors/Chunk.h:90: DB::ISource::tryGenerate() @ 0x12fe9675 in /usr/lib/debug/usr/bin/clickhouse.debug
4. ./build_docker/../contrib/libcxx/include/optional:321: DB::ISource::work() @ 0x12fe9206 in /usr/lib/debug/usr/bin/clickhouse.debug
5. ./build_docker/../src/Processors/Executors/ExecutionThreadContext.cpp:0: DB::ExecutionThreadContext::executeTask() @ 0x13004ce6 in /usr/lib/debug/usr/bin/clickhouse.debug
6. ./build_docker/../src/Processors/Executors/PipelineExecutor.cpp:228: DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*) @ 0x12ff94bc in /usr/lib/debug/usr/bin/clickhouse.debug
7. ./build_docker/../contrib/libcxx/include/__memory/shared_ptr.h:702: DB::PipelineExecutor::executeImpl(unsigned long) @ 0x12ff7ed9 in /usr/lib/debug/usr/bin/clickhouse.debug
```

### CODE REVIEW

**Comment by takakawa** [comment]
there is no guarantee that  the SQL below get the same column order with real table data. 
```
 "SELECT attname AS name, format_type(atttypid, atttypmod) AS type, "
           "attnotnull AS not_null, attndims AS dims, atttypid as type_id, atttypmod as type_modifier "
           "FROM pg_attribute "
           "WHERE attrelid = (SELECT oid FROM pg_class WHERE {}) "
           "AND NOT attisdropped AND attnum > 0
```


image

**Review by alexey-milovidov — APPROVED** [review]

**Comment by robot-clickhouse-ci-2** [comment]
This is an automated comment for commit 16275168cb515cab7b734cd56629f9d8f32961a6 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/53721/16275168cb515cab7b734cd56629f9d8f32961a6/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Comment by alexey-milovidov** [comment]
Please merge with the master branch, as we had a few fixes in the meantime.

**Comment by takakawa** [comment]
hi, what should I do to with this pull request? Do I need provide more tests reports  or something else ?

**Comment by alexey-milovidov** [comment]
The changes LGTM, let's check again...

**Comment by alexey-milovidov** [comment]
But it will not allow to have the "bugfix" category without a test. I feel that writing a test will be difficult - let's change to "improvement".

**Comment by alexey-milovidov** [comment]
I have edited it for better style consistency.

**Comment by alexey-milovidov** [comment]
@takakawa, thank you for the pull request. It is merged!

**Pull request merged**
