### PR TITLE
Add TextFile format Support

### PR DESCRIPTION
**Pull request by sundy-li**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- New Feature

Changelog entry (up to few sentences, required except for Non-significant/Documentation categories):

Add TextFile format Support (fields is separated by CTRL-A (\001), which is the default delimiter of Hive)

Detailed description (optional):

Currently `set format_csv_delimiter = char(1)`  is not supported and  `select '\001'` will translated to  String `01`. Then I think it's better to support `TextFile` format than make `format_csv_delimiter` eval value ASTFunction.

If it's approved, I will continue to write the documentation.

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
> Currently set format_csv_delimiter = char(1) is not supported and select '\001' will translated to String 01.

BTW, it is possible to write `SET format_csv_delimiter = '\x01'`

**Comment by alexey-milovidov** [comment]
TextFile is too good name for it. Maybe better to name it `HiveTextFile`?

**Comment by alexey-milovidov** [comment]
The existence of a special name for CSV with a specific separator is Ok.

**Comment by alexey-milovidov** [comment]
Do you know how the character \x01 is escaped inside strings in TextFile format?
How the strings are quoted? How the NULLs are written?
What about Date and DateTime data types?

**Comment by sundy-li** [comment]
> BTW, it is possible to write SET format_csv_delimiter = '\x01'

I just noticed that. It will be very helpful.

> Do you know how the character \x01 is escaped inside strings in TextFile format?
How the strings are quoted? How the NULLs are written?

'\x01' will not be escaped inside strings in TextFile format by default, users must ensure that.
And strings are not quoted, NULLS will be \N.

Eg.
```
insert overwrite table tmp.textfile_test PARTITION(day='2019-12-01') select '1\00111\0011',  '22\001222\001\0012\001\001\0012', to_date('2019-01-10'),  current_timestamp();

This insert query works fine, yet the select query may not be ok 

select * from tmp.textfile_test;
OK
1	11	NULL	NULL	2019-12-01
```

> What about Date and DateTime data types?

Date type is just like `2019-01-01`, it's ok.
Yet DateTime type is  called `timestamp`  will be written as `2019-01-01 12:05:00.123`.
It's not ok when parsing to  `DateTime` type column.
Maybe we should just remove the millisecond numbers and cast to `DateTime`.

**Comment by sundy-li** [comment]
And there are some other formats in Hive like `serd2`, it allows to set some custom properties like `quoteChar `, `separatorChar `

```
CREATE TABLE test(a string, b string,..)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde'
WITH SERDEPROPERTIES (
   "separatorChar" = ",",
   "quoteChar"     = "\""
)  
STORED AS TEXTFILE 
location 'location of csv file';
```

**Comment by alexey-milovidov** [comment]
> And strings are not quoted

It means it cannot be based on CSV (because in CSV we quote all strings in output).
Maybe our new `CustomSeparated` format will suite better for this case?

**Comment by sundy-li** [comment]
> Maybe our new CustomSeparated format will suite better for this case
I do agree with that.

**Comment by alexey-milovidov** [comment]
BTW the proposed alias `HiveTextFile` for a preconfigured `CustomSeparated` format can still make sense.

**Pull request closed without merging**
