### PR TITLE
minor fix error msg, replace outdated func name

### PR DESCRIPTION
**Pull request by Aaaaaaron**
### Changelog category (leave one):
- Documentation (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
minor fix error msg, replace outdated func name: mergeAndConvertToBlocks

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Review by rschu1ze — APPROVED** [review]

**Comment by rschu1ze** [comment]
@Aaaaaaron Could you please also sign the CLA? Thanks.

**Comment by Aaaaaaron** [comment]
@rschu1ze sorry for that didn't notice that I used the company's email that was not linked to my GitHub account, I changed the email for the commit and it should be ok now

**Comment by rschu1ze** [comment]
@Aaaaaaron Thanks. I see a yellow "CLA not signed yet" button above. I can only merge this commit if it is green, i.e. if you signed the CLA. Could you try to click the button and follow the process?

**Comment by alexey-milovidov** [comment]
It's ok as is.

**Pull request merged**
