### PR TITLE
Fix UB in hopEnd, hopStart, tumbleEnd, and tumbleStart

### PR DESCRIPTION
**Pull request by aiven-sal**
This was causing segfaults because of a NULL pointer dereference

It was found by CI in a different PR

https://s3.amazonaws.com/clickhouse-test-reports/68025/3bae6c2ed53d09657e80ab5e18ec3a22e0a150b3/stateless_tests__asan__[1_2].html

### Changelog category (leave one):
- Critical Bug Fix (crash, LOGICAL_ERROR, data loss, RBAC)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fixed a NULL pointer dereference, triggered by a specially crafted query, that crashed the server via hopEnd, hopStart, tumbleEnd, and tumbleStart.

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by aiven-sal** [comment]
I added another commit that fixes a similar issue in the same file.

**Review by nickitat — APPROVED** [review]

**Comment by robot-clickhouse** [comment]
*This is an automated comment for commit 1875e8d9cd581871c247e3a4cc58f1f57ffa0659 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/68098/1875e8d9cd581871c247e3a4cc58f1f57ffa0659/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/21f8b03789220648948a0d545989d77d9183a927/docs_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Comment by aiven-sal** [comment]
I'm lucky. The fuzzer keeps fidining issues with hopEnd in my PRs even if they are unrelated to my changes.
This time is:
```
SELECT hopEnd((makeDate32(1, toNullable(1)), toDateTime('2019-01-10 00:00:00')));
```
that can also be triggered by
```
SELECT hopEnd((makeDate32(1, 1), toDateTime('2019-01-10 00:00:00')));
```
It looks less dangerous than the issue I'm trying to fix here, so maybe it should be fixed in a separate PR.

**Comment by nickitat** [comment]
> I'm lucky. The fuzzer keeps fidining issues with hopEnd in my PRs even if they are unrelated to my changes. This time is:
> 
> ```
> SELECT hopEnd((makeDate32(1, toNullable(1)), toDateTime('2019-01-10 00:00:00')));
> ```
> 
> that can also be triggered by
> 
> ```
> SELECT hopEnd((makeDate32(1, 1), toDateTime('2019-01-10 00:00:00')));
> ```
> 
> It looks less dangerous than the issue I'm trying to fix here, so maybe it should be fixed in a separate PR.

created an issue: #68199

**Pull request merged**
