### PR TITLE
Fix: ERROR: column "attgenerated" does not exist for old PostgreSQL

### LINKED ISSUE #60651: PostgreSQL table engine: Postgres 11 not supported as of 23.12 release
**Describe the issue**
When using the PostgreSQL table engine with Postgres 11 on ClickHouse v23.12 or above, the database cannot be accessed.

**How to reproduce**
* Which ClickHouse server versions are incompatible: 23.12 and up
* Which interface to use, if matters: N/A
* Queries to run that lead to unexpected result: `SELECT * FROM postgresql(postgres_creds, table='table1');` using a PostgreSQL 11 database.

**Error message and/or stacktrace**
```
Code: 36. DB::Exception: Error: ERROR: column "attgenerated" does not exist LINE 1: ... atttypid as type_id, atttypmod as type_modifier, attgenerat... ^ (in query: SELECT attname AS name, format_type(atttypid, atttypmod) AS type, attnotnull AS not_null, attndims AS dims, atttypid as type_id, atttypmod as type_modifier, attgenerated as generated FROM pg_attribute WHERE attrelid = (SELECT oid FROM pg_class WHERE relname = 'dim_companies' AND relnamespace = (SELECT oid FROM pg_namespace WHERE nspname = 'analytics')) AND NOT attisdropped AND attnum > 0 ORDER BY attnum ASC). (BAD_ARGUMENTS) (version 24.0.2.54390 (official build))
```
**Additional context**
My hypothesis is that the issue is related to this PR which adds support for generated columns which do not yet exist in Postgres 11: https://github.com/ClickHouse/ClickHouse/pull/57568.

I have only tested the table engine in Cloud so far, this likely also affects other engines that use the `fetchPostgreSQLTableStructure` function.

### PR DESCRIPTION
**Pull request by 0xMihalich**
Restore support for GreenPlum and older versions of PostgreSQL without affecting existing functionality.

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix error column "attgenerated" does not exist for old PostgreSQL, fix https://github.com/ClickHouse/ClickHouse/issues/60651

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [x]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Run only fuzzers related jobs (libFuzzer fuzzers, AST fuzzers, etc.)
- [ ]  Exclude: AST fuzzers
---
- [ ]  Do not test
- [x]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by 0xMihalich** [comment]
Hi, I see some errors in tests, but its not for my code, isn't it? How I can help to solve this errors?

**Comment by robot-ch-test-poll1** [comment]
*This is an automated comment for commit a4e576924b16ed199e3726313f96c241b604d4b6 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/71396/a4e576924b16ed199e3726313f96c241b604d4b6/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/4bfce22caaa2afdb86ca034e33c94cc6dc454527/docs_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Review by kssenii — APPROVED** [review]

**Comment by 0xMihalich** [comment]
In log I see error for tests in test_quorum_inserts/test.py::test_insert_quorum_with_keeper_loss_connection
But this test not for postgresql functions. Its not for this PR

**Review by kssenii — APPROVED** [review]
I will add a test myself in a separate PR

**Comment by MikhailBurdukov** [comment]
@kssenii hi, Is it possible to make a backport after merging the PR with the test?

**Pull request merged**
