### PR TITLE
Changes to support the OpenSSL In-house build. 

### PR DESCRIPTION
**Pull request by MeenaRenganathan22**
Changes to support the OpenSSL using the build flag. User will be provided with the option to select between BoringSSL and OpenSSL. By default, the BoringSSL in-house build will be used.

### Changelog category (leave one):
- New Feature

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
This PR is to support the OpenSSL in-house build like the BoringSSL submodule. Build flag i.e. ENABLE_CH_BUNDLE_BORINGSSL is used to choose between BoringSSL and OpenSSL. 
By default, the BoringSSL in-house build will be used.

In case of OpenSSL, AEAD mode exclusively supported in BoringSSL and is not supported by OpenSSL. So, the encrypted compression will be disabled.

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by tavplubix** [comment]
I'm sorry, but we are not going to support OpenSSL as special option, because we don't need it.

**Comment by larryluogit** [comment]
> I'm sorry, but we are not going to support OpenSSL as special option, because we don't need it and don't use it in official builds. This PR significantly increases complexity for no reason.

@tavplubix The latest BoringSSL is not FIPS compliant. OpenSSL 3.0 is. 
BoringSSL will be the default. This option allows user to choose FIPS compliant OpenSSL when they need to deploy ClickHouse in some environment that requires FIPS compliance.

**Comment by tavplubix** [comment]
Well, are there any **technical** reasons why OpenSSL is better than BoringSSL? Why is OpenSSL "FIPS compliant" and BoringSSL is not? Does BoringSSL have some known vulnerabilities? Or does BoringSSL use some encryption algorithms that are not strong enough? We can replace BoringSSL with OpenSSL or make some patches to BoringSSL if there are technical reasons for this. But I don't like the idea of making such significant changes (this PR add 35k lines of code, it will take a month to review) and increasing complexity for only **bureaucratic** reasons.

**Comment by larryluogit** [comment]
> Well, are there any **technical** reasons why OpenSSL is better than BoringSSL? Why is OpenSSL "FIPS compliant" and BoringSSL is not? Does BoringSSL have some known vulnerabilities? Or does BoringSSL use some encryption algorithms that are not strong enough? We can replace BoringSSL with OpenSSL or make some patches to BoringSSL if there are technical reasons for this. But I don't like the idea of making such significant changes (this PR adds 35k lines of code, it will take a month to review) and increasing complexity for only **bureaucratic** reasons.

First of all, I share lots of your view :)
Being FIPS compliant is a status that needs to go through a long process to get. An older version of BoringSSL is FIPS compliant but missing TLS1.3 support. The latest BoringSSL has TLS1.3 but don't have FIPS compliant status anymore.
The changes to ClickHouse core code are not that much. They just accommodate some the differences between BoringSSL and OpenSSL.

**Comment by alexey-milovidov** [comment]
Let's split this PR into three steps.

In the first step - make the changes for ClickHouse code and other libraries, but don't switch from BoringSSL to OpenSSL.
In the second step - allow switching from BoringSSL to OpenSSL, and make it temporary as default to ensure all builds and tests work.
In the third step, we can try to add it as a special build to CI.

**Comment by MeenaRenganathan22** [comment]
> Let's split this PR into three steps.
> 
> In the first step - make the changes for ClickHouse code and other libraries, but don't switch from BoringSSL to OpenSSL. In the second step - allow switching from BoringSSL to OpenSSL, and make it temporary as default to ensure all builds and tests work. In the third step, we can try to add it as a special build to CI.

Thanks @alexey-milovidov for the approach.
So, just to be clear, in the second step, it is expected the OpenSSL needs to be set as default, right?

**Comment by alexey-milovidov** [comment]
In the second step, you will set OpenSSL by default, then make all the tests green, then turn it off again.

**Comment by MeenaRenganathan22** [comment]
Hi @alexey-milovidov , this is the first step of the PR. Committing the ClickHouse core changes and other libraries changes.
Could you please help to start the build?

**Comment by MeenaRenganathan22** [comment]
Hi @tavplubix, @alexey-milovidov,

I've made the changes for the ClickHouse core and other libraries. Ensured the failures not related with these changes.
Could you please review and let us know whether to proceed for the step 2?

**Comment by MeenaRenganathan22** [comment]
@tavplubix, @alexey-milovidov 

Please confirm whether I can proceed with the step2 of this PR.

**Comment by alexey-milovidov** [comment]
Almost alright, I'd rename the CMake flag, and it will be ready to merge.

**Comment by MeenaRenganathan22** [comment]
> Almost alright, I'd rename the CMake flag, and it will be ready to merge.

Thank you @alexey-milovidov. But, this is the first step of this PR. I have to complete the below two steps.

In the second step - allow switching from BoringSSL to OpenSSL, and make it temporary as default to ensure all builds and tests work.
In the third step, we can try to add it as a special build to CI.

You want me to continue with the last two steps. Otherwise we will merge the changes first and then proceed with the another PR for the remaining changes. Please confirm.

**Comment by alexey-milovidov** [comment]
All the steps should be in separate pull requests.

**Comment by MeenaRenganathan22** [comment]
> All the steps should be in separate pull requests.

Thank you @alexey-milovidov. Ok, I will proceed with the second step in the new pull request.

**Comment by alexey-milovidov** [comment]
I did not take this pull request for review yet.

**Comment by alexey-milovidov** [comment]
Let's do the following changes.

Instead of `ENABLE_CH_BUNDLE_BORINGSSL` we will have another option, named
`ENABLE_EXTERNAL_OPENSSL` with the opposite meaning.

The description should highlight that this option is dangerous and insecure, and you should never use it.

**Comment by MeenaRenganathan22** [comment]
@alexey-milovidov,

Updated the flag as suggested. Please review.

**Comment by alexey-milovidov** [comment]
Some commits are from "root", I will have to use "squash" for merging.

**Review by alexey-milovidov — APPROVED** [review]

**Pull request merged**
