### PR TITLE
Add support for extended (chunked) arrays for Parquet format

### LINKED ISSUE #39944: Add support for extended (chunked) arrays for Parquet format in ClickHouse please
### Problem
The S3 function fails with an exception when reading from a Parquet file with large map data.  

### Version
22.3.6.5

### Reproduction

Here is the SELECT that triggers the problem. 
```
select id, fields_map
from s3(
'my_parquet_file.parquet',
'Parquet',
'id Int64, fields_map Map(String, String)')
;
```
Here is the the schema and data size that triggers problems. (Collected with `parquet-tools`.) 
```
  optional group fields_map (MAP) = 217 {
    repeated group key_value {
      required binary key (STRING) = 218;
      optional binary value (STRING) = 219;
    }
  }

fields_map.key_value.value-> Size In Bytes: 13243589 Size In Ratio: 0.20541047
fields_map.key_value.key-> Size In Bytes: 3008860 Size In Ratio: 0.046667963
```
And here is the resulting error. 
```
Code: 33. DB::Exception: Received from localhost:9000. DB::Exception: Error while reading Parquet data: NotImplemented: Nested data conversions not implemented for chunked array outputs: While executing ParquetBlockInputFormat: While executing S3. (CANNOT_READ_ALL_DATA)
```

The full stack trace is as follows: 
```
chi-ch-39-ch-39-0-0-0 ch 2022.08.06 18:24:41.451777 [ 2347 ] {a7552683-f8dc-4ad4-a838-4555dc944e28} <Error> TCPHandler: Code: 33. DB::Exception: Error while reading Parquet data: NotImplemented: Nested data conversions not implemented for chunked array outputs: While executing ParquetBlockInputFormat: While executing S3. (CANNOT_READ_ALL_DATA), Stack trace (when copying this message, always include the lines below):
chi-ch-39-ch-39-0-0-0 ch
chi-ch-39-ch-39-0-0-0 ch 0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xb37173a in /usr/bin/clickhouse
chi-ch-39-ch-39-0-0-0 ch 1. DB::ParquetBlockInputFormat::generate() @ 0x169f6702 in /usr/bin/clickhouse
chi-ch-39-ch-39-0-0-0 ch 2. DB::ISource::tryGenerate() @ 0x168fc395 in /usr/bin/clickhouse
chi-ch-39-ch-39-0-0-0 ch 3. DB::ISource::work() @ 0x168fbf5a in /usr/bin/clickhouse
chi-ch-39-ch-39-0-0-0 ch 4. DB::ExecutionThreadContext::executeTask() @ 0x1691c6e3 in /usr/bin/clickhouse
chi-ch-39-ch-39-0-0-0 ch 5. DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*) @ 0x1691013e in /usr/bin/clickhouse
chi-ch-39-ch-39-0-0-0 ch 6. DB::PipelineExecutor::executeStep(std::__1::atomic<bool>*) @ 0x1690f960 in /usr/bin/clickhouse
chi-ch-39-ch-39-0-0-0 ch 7. DB::PullingPipelineExecutor::pull(DB::Chunk&) @ 0x1692120e in /usr/bin/clickhouse
chi-ch-39-ch-39-0-0-0 ch 8. DB::StorageS3Source::generate() @ 0x160f5a6c in /usr/bin/clickhouse
chi-ch-39-ch-39-0-0-0 ch 9. DB::ISource::tryGenerate() @ 0x168fc395 in /usr/bin/clickhouse
chi-ch-39-ch-39-0-0-0 ch 10. DB::ISource::work() @ 0x168fbf5a in /usr/bin/clickhouse
chi-ch-39-ch-39-0-0-0 ch 11. DB::SourceWithProgress::work() @ 0x16b53862 in /usr/bin/clickhouse
chi-ch-39-ch-39-0-0-0 ch 12. DB::ExecutionThreadContext::executeTask() @ 0x1691c6e3 in /usr/bin/clickhouse
chi-ch-39-ch-39-0-0-0 ch 13. DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*) @ 0x1691013e in /usr/bin/clickhouse
chi-ch-39-ch-39-0-0-0 ch 14. ? @ 0x16911aa4 in /usr/bin/clickhouse
chi-ch-39-ch-39-0-0-0 ch 15. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xb418b97 in /usr/bin/clickhouse
chi-ch-39-ch-39-0-0-0 ch 16. ? @ 0xb41c71d in /usr/bin/clickhouse
chi-ch-39-ch-39-0-0-0 ch 17. ? @ 0x7f7e70c2e609 in ?
chi-ch-39-ch-39-0-0-0 ch 18. __clone @ 0x7f7e70b53163 in ?
```
### Workaround?
There does not appear to be a workaround for this problem. 

### Additional Information 
A similar-looking problem was fixed in Arrow libraries in 2019: https://issues.apache.org/jira/browse/ARROW-4688. This increased the limit from 16MB to 2GB. Other usages of these parquet files outside ClickHouse don't encounter read issues, so maybe the ClickHouse library is out of date?

### PR DESCRIPTION
**Pull request by arthurpassos**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
ClickHouse was using parquet::FileReader::ReadAll to parse Parquet. This code path leads to [Nested data conversions not implemented for chunked array outputs](https://github.com/apache/arrow/blob/7f6b074b84b1ca519b7c5fc7da318e8d47d44278/cpp/src/parquet/arrow/reader.cc#L95) when the input ends up building a chunked array internally. According to [arrow-upstream](https://issues.apache.org/jira/browse/ARROW-3762) folks, using the `FileReader::GetRecordBatchReader` would result in a different code path that could work. 

The SELECT statement succeeds when using the latter, but I couldn't verify if the data is correct. I believe it is. In order to verify, I need to find a way to compare the original Parquet file with the one processed by ClickHouse. The test file I have been using is big and ClickHouse fails to export it to Parquet (this is a different problem not in the scope of this PR).

I have tried some combinations of transformations (JSON & Parquet) using Python, Spark & ClickHouse to find a way to validate the data, all of them failed because of a variety of reasons like:
1. Python's `pyarrow` throws the very same exception ClickHouse was throwing when it tries to read the original file. Can't load it into memory.
2. Python's `fastparquet` fails to read the original file with weird exception.
3. ClickHouse can't export the SELECT statement into Parquet because of some `arrow` internal memory limitation. It throws an Exception.
4. Splitting the files into chunks and exporting failed because of formatting and encoding issues. In JSON, for instance, some escape characters were added by ClickHouse, while they were not added by Spark.

I'll continue investigating ways to validate the impl and possibly implement a test.

Closes #39944

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by arthurpassos** [comment]
Earlier this morning I managed to compare the top 50% of the original file with the one processed by ClickHouse using Spark & pyspark. They match! Didn't compare the other half because the pyspark API interface available to grab last N elements is `tail` and it was taking way more memory than `limit`.

I can't use the test file I have to implement a test because it's confidential data. I just managed to generate a file with the schema presented in the issue, but it doesn't raise the exception. The test file that was provided contains many more columns than what was in the select statement, maybe it has something to do with that. Will investigate further.

**Comment by arthurpassos** [comment]
I have validated the implementation by doing the following:
1. Export the file processed by ClickHouse into two Parquet files, command: `clickhouse-client --query "select id, _acc_fields_map from s3(<file_path>, 'Parquet', 'id Int64, _acc_fields_map Map(String, String)') order by id limit <lower_limit>, <upper_limit> FORMAT Parquet" > parquet validation/processed<part_number>.parquet`. `lower_limit`, `upper_limit` and `part_number` being 0/80692, 80692/161384 and 1/2 for part1 and part2 respectively.
2. Using PySpark, concat both parts processed by ClickHouse into a single DataFrame. Then, assert the equality of the original dataframe (read from original file) with the processed data frame. Python script: 

```
original_df = spark.read.parquet("original-strippedd.parquet").orderBy("id")

processed_df1 = spark.read.parquet("processed1.parquet")

processed_df2 = spark.read.parquet("processed2.parquet")

processed_concatened = processed_df1.union(processed_df2).withColumn("fields_map", F.col("fields_map").cast("map<string,string>"))

assert original_df_filtered.collect() == processed_concatened.collect()
```

To be sure the assertion was doing its job, I dropped the first row in the original DataFrame and the assertion failed. Dropped it with `original_df_filtered = original_df.where(original_df.id > <first_id>)`. The assertion failed.

I have spent the last week trying to write a test, but failed to do so. Mainly because I could not generate a file that raises the exception. I have tried several combinations using VERY large strings with LOW and HIGH cardinality. None of them caused the issue. AFAIK, the data gets internally chunked when the chunk memory limit is reached within a rowgroup. As of now, it's [set to 2^32 - 1](https://github.com/apache/arrow/blob/master/cpp/src/arrow/type.h#L660).

Since I validated it works in that case, I'll set this PR as ready for review. I am open for discussions.

**Comment by arthurpassos** [comment]
Marked it as draft again. While the initial case is working properly, the below isn't:

```
import pyarrow as pa
import pyarrow.parquet as pq

arr = pa.array([[("a" * 2**30, 1)]], type = pa.map_(pa.string(), pa.int32()))
arr = pa.chunked_array([arr, arr])
tab = pa.table({ "arr": arr })

pq.write_table(tab, "test.parquet")

pq.read_table("test.parquet")
```

**Comment by arthurpassos** [comment]
> Marked it as draft again. While the initial case is working properly, the below isn't:
> 
> ```
> import pyarrow as pa
> import pyarrow.parquet as pq
> 
> arr = pa.array([[("a" * 2**30, 1)]], type = pa.map_(pa.string(), pa.int32()))
> arr = pa.chunked_array([arr, arr])
> tab = pa.table({ "arr": arr })
> 
> pq.write_table(tab, "test.parquet")
> 
> pq.read_table("test.parquet")
> ```

Arrow lib contains two variants of String: String and LargeString. After some hackish changes on `arrow` lib, I managed to force the use of LargeStrings and the data doesn't get chunked anymore. Using LargeString by default certainly has its implications and does use more resources. Suggestion from `arrow` upstream folks is to add a setting to the library API that allows conversion from non-large types to large types. Since it's a 3rd party library and a rather complicated change, it could take a long time to get this right & merged. More info on [ARROW-17459](https://issues.apache.org/jira/browse/ARROW-17459).

The changes in this PR seems to fix the original case by avoiding that code path. It doesn't solve the latter, tho. It was a suggestion from `arrow` upstream folks in [ARROW-17459-comment](https://issues.apache.org/jira/browse/ARROW-17459?focusedCommentId=17581502&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-17581502).

Based on that, I am re-opening this PR as ready-for-review.

**Comment by arthurpassos** [comment]
@Avogar kind ping :)

**Review by Avogar — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
`arrow::Status read_status = rbr->ReadAll(&table);`

WTF?
Revert?

**Comment by alexey-milovidov** [comment]
Actually it's alright.

**Pull request merged**
