### PR TITLE
WIP USING for multple JOIN

### PR DESCRIPTION
**Pull request by ilejn**
Changelog category (leave one):
- Improvement

USING for multiple JOIN
...

It is possible to 
SELECT from t1 join t2 on t1.id=t2.id join t3 on t1.id=t3.id
while 
SELECT from t1 join t2 using(id) join t3 using(id)
is not supported.
Try to have it working.
...

### CODE REVIEW

**Comment by lepfhty** [comment]
+1 for this feature

**Comment by alexey-milovidov** [comment]
Please resolve conflicts.

**Comment by ilejn** [comment]
> Please resolve conflicts.

Hello @alexey-milovidov, 
looks like I've failed to catch master again ;)
But I've done some performance tests https://github.com/ClickHouse/ClickHouse/issues/34236#issuecomment-1229920651

**Comment by kitaisreal** [comment]
Already done in https://github.com/ClickHouse/ClickHouse/pull/31796

**Comment by kitaisreal** [comment]
Tests are here https://github.com/ClickHouse/ClickHouse/pull/31796/files#diff-e017b5f2830a8e578431a0216d0442c2076d0994ce31303b40e6f7346d318fe4R63. In this pull request JOIN planning is analyze and planning stages are completely reimplemented.
Main changes related to JOINs:
1. Multiple JOINs are no longer rewrite themselves to to subqueries. Previous approach was not scalable, for more than several joins performance degrades dramatically.
2. Native support for join_use_nulls, without ad-hoc column casts.
3. Native support for USING for multiple JOINs.
4. Potential ability to reorder JOINs using CBO, because now they are planned inside single function.

**Comment by ilejn** [comment]
> Tests are here https://github.com/ClickHouse/ClickHouse/pull/31796/files#diff-e017b5f2830a8e578431a0216d0442c2076d0994ce31303b40e6f7346d318fe4R63. In this pull request JOIN planning is analyze and planning stages are completely reimplemented. Main changes related to JOINs:
> 
>     1. Multiple JOINs are no longer rewrite themselves to to subqueries. Previous approach was not scalable, for more than several joins performance degrades dramatically.

Hello Maxim @kitaisreal , as far as I can see there is no AST transformations regarding multiple joins any more, which is cool. But join machinery is not affected. Joins are still executed for two tables (or queries), there is no attempts to join multiple tables at once.
Is it correct vision?
Asking because my goal is to introduce an operation to join several (e.g. dozens) tables with same ordering.

**Comment by kitaisreal** [comment]
@ilejn yes. We do not have any internal work to support execution of multiple joins at once. I would be glad to see a pull request, which add query plan step, and execution algorithm. I have a lot of plans to improve JOINs in Q4 and Q1 of next year.
We plan to merge new Analyzer, Planner pull request soon to master branch, so it will be more easy to start contributing. But enable it in production after additional work will be finished (a lot of tests need to be regenerated because now plan looks different, and a lot of old code need to be deleted). Currently Analyzer is finished. Planner does not support:
1. Distributed (we do not know how we want to support it yet, our goal is to send query plan directly without sending query stage, but probably it will be a totally separate task and initially will be implemented as it is now).
2. Projections.
3. Some small optimizations.
After that we will try to simplify our query plan to allow more optimizations on top of it. We are most interested in:
1. JOINS reordering.
2. READ in order optimizations based on query plan.
3. Execution of multiple JOINS together could also be implemented on top of Query Plan optimizations.
4. Remove actions chain and implement it on top of query plan.
5. Better indexes support. (KeyCondition and skipping indexes were not properly supported in case of JOINs, they work in my branch). 
Currently query plan does not allow such optimizations. Main problem are that input and output are fixed, and some steps in plan are not logical (ReadFromMergeTree).
CC: @alexey-milovidov

**Comment by alexey-milovidov** [comment]
These are great news, let's merge Analyzer as soon as possible!

**Comment by ilejn** [comment]
Hello @alexey-milovidov , we still believe that multiple JOINs are usefull in new Analyzer based world.
Some details about the nature of this PS are in my comments in https://github.com/ClickHouse/ClickHouse/issues/34236

On the other hand, I am not sure that it is reasonable to go on with development right now, it may be better to wait while Analyzer is stabilized.

**Comment by alexey-milovidov** [comment]
Let's keep it open and continue later.

**Pull request closed without merging**
