### PR TITLE
Add transition from reading key to reading quoted key when double quotes are found

### PR DESCRIPTION
**Pull request by arthurpassos**
Address one of the use cases in https://github.com/ClickHouse/ClickHouse/issues/56357

### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Add transition from reading key to reading quoted key when double quotes are found

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]

**Comment by robot-ch-test-poll2** [comment]
*This is an automated comment for commit e4400ec24c1a7949638f80642f8510978dc6bbea with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/56423/e4400ec24c1a7949638f80642f8510978dc6bbea/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td><a href="https://github.com/ClickHouse/ClickHouse/actions/runs/6787669750">✅ success</a></td></tr>
<tbody>
</table>
</details>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/56423/e4400ec24c1a7949638f80642f8510978dc6bbea/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Comment by arthurpassos** [comment]
@alexey-milovidov failures are not related

**Comment by arthurpassos** [comment]
@alexey-milovidov ping

**Comment by alexey-milovidov** [comment]
@arthurpassos, this PR cannot be merged because the tests have failed.

**Comment by alexey-milovidov** [comment]
Either you fix the tests by yourself or wait while they are fixed and merge with master.

**Pull request merged**
