### PR TITLE
Potential fix for Issue:  Extend and update corpus for fuzzing #42762 

### LINKED ISSUE #42762: Extend and update corpus for fuzzing
Among all the fuzzers we have one specific - codegen_select_fuzzer. It uses a custom protobuf mutator and translates a protobuf to an SQL query. We can add more query templates here https://github.com/ClickHouse/ClickHouse/blob/835daee0f3e05ff6efcc451ee66c4ddc6d2119d5/src/Parsers/fuzzers/codegen_fuzzer/clickhouse-template.g#L28-L37
How to do this? We can do this semi-automatic. Write a code inside our codebase to extract all the keywords (SELECT, ORDER BY, GROUP BY) around the Lexer or write which will replace all `ASTIdentifier` or `ASTExpressionList` from the AST and just print the resulting query to some file. Then just execute all our stateless tests and that's it. 
Additionally we can update all the functions names here https://github.com/ClickHouse/ClickHouse/blob/master/tests/fuzz/all.dict

### PR DESCRIPTION
**Pull request by dgeorgi**
### Changelog category (leave one):
- Build/Testing/Packaging Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Extended the corpus for `codegen_select_fuzzer`, new query templates were added and the keyword dictionary was updated. This closes: https://github.com/ClickHouse/ClickHouse/issues/42762

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
Could you please describe the changes? What exactly has been done, and how to use it?

**Comment by dgeorgi** [comment]
Sure, fix was a poor choice of wording. I wrote a python script that reads all function names and keywords from the file all.dict and generates permutation and writes them into the a new file called combinations.txt. then I added those combinations to the file clickhouse-template.g as new templates to be used when fuzzing codegen_select_fuzzer.

**Comment by alexey-milovidov** [comment]
I forgot how to use this fuzzer, could you please provide some examples and the experiment results?

**Comment by nikitamikhaylov** [comment]
This is great, please ask me if you have any questions!

**Pull request closed without merging**
