### PR TITLE
ClickHouse app for showing process table and also some metrics

### PR DESCRIPTION
**Pull request by a-kush**
### Changelog category (leave one):
- New Feature
- Improvement
- Performance Improvement
- Backward Incompatible Change
- Build/Testing/Packaging Improvement
- Documentation (changelog entry is not required)
- Bug Fix (user-visible misbehavior in an official stable release)
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
...

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by a-kush** [comment]
IMAGE 2023-05-28 17:26:45

**Comment by a-kush** [comment]
IMAGE 2023-05-28 17:26:58

**Comment by a-kush** [comment]
IMAGE 2023-05-28 17:27:18

**Comment by a-kush** [comment]
i have a list of improvements but need review for university until 29.05 23:59. please check comments above "queryToString" function in Top.cpp

**Comment by a-kush** [comment]
works on Linux and MacOS

**Comment by robot-ch-test-poll** [comment]
This is an automated comment for commit 104deac01eb8651836657267606b1c860a6f1a66 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/50288/104deac01eb8651836657267606b1c860a6f1a66/ci_running.html)
The overall status of the commit is 🔴 failure

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🔴 failure</td></tr>
<tr><td>Docs Check</td><td>Builds and tests the documentation</td><td>🟡 pending</td></tr>
</table>

**Comment by alexey-milovidov** [comment]
Ok. This PR is just a demo, but it will take much more effort to make it production ready:
- get rid of ncurses;
- rewrite in Rust;
- support across cluster statistics.

**Comment by a-kush** [comment]
If it is any important, I made little changes since last time to make a presentation at school. It's in my fork

**Pull request closed without merging**
