### PR TITLE
Do not load indexes if key condition in not useful

### PR DESCRIPTION
**Pull request by davenger**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Queries like 'SELECT * FROM t LIMIT 1' used to load part indexes even though they were not used.

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Run only fuzzers related jobs (libFuzzer fuzzers, AST fuzzers, etc.)
- [ ]  Exclude: AST fuzzers
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-clickhouse-ci-2** [comment]
*This is an automated comment for commit 796ac4350ff7c1a73a09c4386e451063b6959cac with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/71866/796ac4350ff7c1a73a09c4386e451063b6959cac/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/d38bd0df0aa277f4ec33b58f6832e45de596525c/docs_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Review by novikd — COMMENTED** [review]
Great contribution! I'd prefer also adding tests for this case.

**Comment by davenger** [comment]
> Great contribution! I'd prefer also adding tests for this case.
Thank you! :)
I marked it as draft for now to first check if any existing test breaks

**Comment by davenger** [comment]
@novikd I found [2 tests](https://s3.amazonaws.com/clickhouse-test-reports/71866/796ac4350ff7c1a73a09c4386e451063b6959cac/fast_test.html)  that were checking loaded index sizes after 'SELECT * LIMIT 1' queries and updated them

**Review by novikd — APPROVED** [review]
LGTM

**Pull request merged**
