### PR TITLE
[RFC] Fix data skipping indexes for columns with additional actions during merge

### PR DESCRIPTION
**Pull request by azat**
Changelog category (leave one):
- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
If data skipping index is dependent on columns that are going to be modified during background merge (for SummingMergeTree, AggregatingMergeTree as well as for TTL GROUP BY), it was calculated incorrectly. This issue is fixed by moving index calculation after merge so the index is calculated on merged data.

Detailed description / Documentation draft:
For example for AggregatingMergeTree if the column in the data skipping
index is under some aggregate function, then data skipping index will be
incorrect.

Fix this by calculating data skipping indexes after aggregation has been
done.

P.S. looks like all versions affected

### CODE REVIEW

**Comment by azat** [comment]
Rebased, previous HEAD - 7d196d08e4af015664675beac6d2f6714db673a5 (contains tests)

**Comment by alexey-milovidov** [comment]
@abyss7 No work done on review, unassigned.

**Comment by alexey-milovidov** [comment]
Ok.

I've edited the changelog entry to make it more comprehensible (so the user can understand the scope of this issue):

From:
> Fix data skipping indexes for columns with additional actions during merge

To:
> If data skipping index is dependent on columns that are going to be modified during background merge (for SummingMergeTree, AggregatingMergeTree as well as for TTL GROUP BY), it was calculated incorrectly. This issue is fixed by moving index calculation after merge.

**Review by alexey-milovidov — APPROVED** [review]

**Comment by azat** [comment]
>I've edited the changelog entry to make it more comprehensible (so the user can understand the scope of this issue):

I always forget making changelog entry "user friendly", thanks!

**Comment by KochetovNicolai** [comment]
Reverted fix from 20.1 and 20.3 because it cause exception `Column  already exists` for `OPTIMIZE TABLE` queries:
https://clickhouse-test-reports.s3.yandex.net/9624/3f2cba6824fddf31c30bde8c6f4f860572f4f580/functional_stateless_tests_(release).html#fail1

**Comment by alexey-milovidov** [comment]
@KochetovNicolai Should we also revert from 20.4 and master?

**Comment by KochetovNicolai** [comment]
As I see from tests, it works for 20.4 and master.
Probably, some refactoring wasn't backported for other branches.

**Comment by azat** [comment]
This PR should not be backported without #11259

**Comment by KochetovNicolai** [comment]
I've decided to not backport this pr at all.

**Pull request merged**
