### PR TITLE
Fix sleepEachRow max time

### PR DESCRIPTION
**Pull request by novikd**
Changelog category (leave one):

- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

`sleepEachRow` function is now limited to sleep no more than 3 seconds per block. The behaviour is now similar to `sleep` function.

Related to #34397
cc @alexey-milovidov

### CODE REVIEW

**Review by Avogar — APPROVED** [review]
Some tests should be adjusted

**Comment by novikd** [comment]
@Mergifyio update

**Comment by novikd** [comment]
@Mergifyio update

**Comment by alexey-milovidov** [comment]
@novikd @Avogar Let's continue.

**Comment by alexey-milovidov** [comment]
@novikd what a good pull request!

**Comment by alexey-milovidov** [comment]
@novikd no progress in more than a year.
Continued in https://github.com/ClickHouse/ClickHouse/pull/49343.

**Pull request closed without merging**
