### PR TITLE
Add "harmful" library

### PR DESCRIPTION
**Pull request by alexey-milovidov**
Changelog category (leave one):
- Build/Testing/Packaging Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Add a library that replaces some `libc` functions to traps that will terminate the process.

Motivated by: https://clickhouse-test-reports.s3.yandex.net/0/c13ab94f91ed4fddd4b9b87adadad68c0ade8684/stress_test_(thread)/stderr.log

Caveats:
1. The list of harmful functions should be different for main ClickHouse source code and for third-party libraries. For example, it's profane to use `fopen` `strtok`, `qsort`, `bsearch`, `strptime`, `localtime`, `gmtime`, `drand48_r`... in the main source code, but they are Ok for third-party libraries.
2. It will be better to provide different libc headers for the main source code of ClickHouse that will simply lack these functions or mark them as deprecated.
3. If it's not possible to implement with custom headers, we can also control it on linking stage.
4. It's mostly unrelated but also worth doing to protect `clickhouse-odbc-bridge` and ClickHouse itself with `seccomp`.
5. I personally would like if `dlopen` will terminate the program immediately. But we are using it in two places and glibc also using it.

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
@nikitamikhaylov It works perfectly: `SELECT roundBankers(WelchTTest(left, right).2, 16) from welch_ttest;`

**Comment by alexey-milovidov** [comment]
\+ you have to name aggregate function camelCase, not CamelCase.

**Comment by nikitamikhaylov** [comment]
> \+ you have to name aggregate function camelCase, not CamelCase.

I thought their name are case-independent. In any case I specified this property in the code

**Comment by alexey-milovidov** [comment]
No, for functions that are specific for ClickHouse (as opposed to SQL compatible), better to use case-sensitive names.

**Comment by alexey-milovidov** [comment]
#16407

**Comment by alexey-milovidov** [comment]
Should be disabled for `clickhouse-odbc-bridge`.

**Comment by alexey-milovidov** [comment]
Will enable harmful library only in debug builds.

**Comment by qoega** [comment]
[getservbyname](https://clickhouse-test-reports.s3.yandex.net/16366/bbc676d8219ba9e61d5778aa171b4e813e28494a/functional_stateless_tests_(debug).html#fail)

https://github.com/ClickHouse/ClickHouse/blob/ac989f3a8fe8e2135e25ac7d6e340b048092e906/src/Common/DNSResolver.cpp#L84

**Comment by alexey-milovidov** [comment]
#18647

**Comment by abyss7** [comment]
The log in the description is lost - so what was the motivation?

**Comment by alexey-milovidov** [comment]
@abyss7 Don't allow to use harmful functions in code.

**Pull request merged**
