### PR TITLE
Update Poco: Fix thread counter leak

### LINKED ISSUE #17200: clickhouse-client connection server is abnormal: Code: 32. DB::Exception: Attempt to read after eof
system: centos7
clickhouse version: 20.3.11.97

Link to server through different host client, report exception；
```
ClickHouse client version 20.3.11.97.
Connecting to ***:9000 as user admin.
Code: 32. DB::Exception: Attempt to read after eof
```
But the clickhouse-server.err.log has no abnormal updates,  clickhouse-server.err.log such as ReplicatedMergeTreePartCheckThread are output normally at this time;  The link returns to normal after restarting the server。
How to troubleshoot the change? Client is not installed on the server host

### PR DESCRIPTION
**Pull request by alexey-milovidov**
Changelog category (leave one):
- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix the issue when server can stop accepting connections in very rare cases.

Details:
This PR also includes some changes for BoringSSL.

This closes #17200.

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
> 01415_sticking_mutations

@alesapin

**Comment by alexey-milovidov** [comment]
https://github.com/ClickHouse/ClickHouse/pull/17597

**Comment by nvartolomei** [comment]
Should this be backported to 20.8 lts as well?

**Comment by alexey-milovidov** [comment]
Yes.

**Pull request merged**
