### PR TITLE
Inline small but frequently invoked functions in PODArrayDetails 

### PR DESCRIPTION
**Pull request by taiyang-li**
```
./clickhouse benchmark  --query  "with 'Many years later as he faced the firing squad, Colonel Aureliano Buendia was to remember that distant afternoon when his father took him to discover ice.' as s select splitByChar(' ', materialize(s)) as w from numbers(1000000) format Null;" 
```

Before opt: 

```
localhost:9001, queries: 20, QPS: 1.695, RPS: 1695003.180, MiB/s: 12.932, result RPS: 0.000, result MiB/s: 0.000.

0.000%          0.518 sec.
10.000%         0.530 sec.
20.000%         0.540 sec.
30.000%         0.551 sec.
40.000%         0.564 sec.
50.000%         0.567 sec.
60.000%         0.573 sec.
70.000%         0.582 sec.
80.000%         0.593 sec.
90.000%         0.624 sec.
95.000%         0.658 sec.
99.000%         0.889 sec.
99.900%         0.889 sec.
99.990%         0.889 sec.  
```

After opt: 

```
localhost:9001, queries: 20, QPS: 1.763, RPS: 1763295.127, MiB/s: 13.453, result RPS: 0.000, result MiB/s: 0.000.

0.000%          0.518 sec.
10.000%         0.529 sec.
20.000%         0.540 sec.
30.000%         0.561 sec.
40.000%         0.564 sec.
50.000%         0.571 sec.
60.000%         0.572 sec.
70.000%         0.573 sec.
80.000%         0.578 sec.
90.000%         0.580 sec.
95.000%         0.583 sec.
99.000%         0.586 sec.
99.900%         0.586 sec.
99.990%         0.586 sec.
```

Below graph is the flamegraph before optimization. It is obvious that the overhead of calling `byte_size` should be not ignored because `byte_size` is on the hot path.  
image

### Changelog category (leave one):
- Performance Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
More frequently invoked functions in PODArray are now force-inlined.

### CODE REVIEW

**Comment by robot-ch-test-poll2** [comment]
*This is an automated comment for commit 150e7f338a3a1d49104f4d605bd2f65bd20fa149 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/61144/150e7f338a3a1d49104f4d605bd2f65bd20fa149/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

**Comment by taiyang-li** [comment]
Let's wait for performance report in CI.

**Comment by rschu1ze** [comment]
(Seems a bit like microoptimization but why not. Can merge next week, CI is currently too broken.)

**Review by rschu1ze — APPROVED** [review]

**Comment by taiyang-li** [comment]
image

image

**Comment by taiyang-li** [comment]
I doubt the 2 slower perf tests are not related to inline of PODArrayDetails. I can't even find `PODArrayDetails` in framegraphs.

**Review by rschu1ze — APPROVED** [review]

**Comment by taiyang-li** [comment]
> I doubt the 2 slower perf tests are not related to inline of PODArrayDetails. I can't even find `PODArrayDetails` in framegraphs.

Yes. Perf tests seem not stable. I merged master again, and we now have different slower and faster cases.

**Comment by rschu1ze** [comment]
The merge button is greyed out for me because `binary_riscv64` and `binary_tidy` builders failed. The former looks like an infrastructure issue, the latter is unrelated to this PR.

I could not merge from master as I don't have permissions to push to your repository:

```
~/repo/ch5 (inline_poaarray_details >) $ git push bigo-sg inline_poaarray_details
remote: Permission to bigo-sg/ClickHouse.git denied to rschu1ze.
fatal: unable to access 'https://github.com/bigo-sg/ClickHouse.git/': The requested URL returned error: 403
```

Kindly merge from master by yourself, thanks!

**Comment by rschu1ze** [comment]
The RISC-V build is still broken, a fix is https://github.com/ClickHouse/ClickHouse/pull/61604.

**Comment by taiyang-li** [comment]
> The RISC-V build is still broken, a fix is #61604.

It is merged now. Let us see the newest CI

**Review by rschu1ze — APPROVED** [review]

**Comment by taiyang-li** [comment]
@rschu1ze can we merge it now? Thanks!

**Pull request merged**
