### PR TITLE
Remove height restrictions from the query div in play web tool, and m…

### PR DESCRIPTION
**Pull request by guyco87**
Changelog category:
Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Modify query div in play.html to be extendable beyond 20% height. In case of very long queries it is helpful to extend the textarea element, only today, since the div is fixed height, the extended textarea hides the data div underneath. With this fix, extending the textarea element will push the data div down/up such the extended textarea won't hide it.
Also, keeps query box width 100% even when the user adjusting the size of the query textarea

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
I've tested, but it does not work:
Screenshot_20220524_235654

Sorry, I've tested after merge (for convenience), so let's revert.
Please resubmit.

**Comment by alexey-milovidov** [comment]
In comparison, here is the correct rendering:
Screenshot_20220524_235815

**Comment by guyco87** [comment]
Hi, thanks for testing this.

Which browser and os are you using? I tested it on my mac in both chrome and FF and it worked, but there's always issues with different browsers+OS.

Can you check if this issue is reproduced in both Chrome and FF? I'm trying to narrow it down to the problematic combinations.

Btw, it should still be functional because you should be able to adjust the query box by dragging the bottom right corner, although of course this should be as big as before by default.

**Comment by alexey-milovidov** [comment]
Firefox 100.0.

**Comment by alexey-milovidov** [comment]
> Btw, it should still be functional

Functional but ugly.

**Comment by guyco87** [comment]
Hi, thanks for testing this.

Which browser and os are you using? I tested it on my mac in both chrome
and FF and it worked, but there's always issues with different browsers+OS.

Can you check if this issue is reproduced in both Chrome and FF? I'm trying
to narrow it down to the problematic combinations.

**Comment by alexey-milovidov** [comment]
The code has been slightly changed and the patch no longer applies.

**Pull request merged**
