### PR TITLE
Update usearch

### LINKED ISSUE #61780: `heap-buffer-overflow` in `usearch`
UBSan crashed because of memory corruption
https://s3.amazonaws.com/clickhouse-test-reports/0/b8b977e99fefcedcd55900b3198f5a317c7f5090/ast_fuzzer__ubsan_.html

It's easily reproducible with ASAN build:

```sql
SET allow_experimental_usearch_index = 1;

CREATE TABLE tab_usearch__fuzz_9 (`id` UInt256, `vec` Tuple(Float32, Float32), INDEX idx vec TYPE usearch('cosineDistance', 'f64') GRANULARITY 2) ENGINE = MergeTree ORDER BY id SETTINGS index_granularity = 3;

INSERT INTO tab_usearch__fuzz_9 FORMAT Values (0, (4.6, 2.3)), (1, (2.0, 3.2)), (2, (4.2, 3.4)), (3, (5.3, 2.9)), (4, (2.4, 5.2)), (5, (5.3, 2.3)), (6, (1.0, 9.3)), (7, (5.5, 4.7)), (8, (6.4, 3.5)), (9, (5.3, 2.5)), (10, (6.4, 3.4)), (11, (6.4, 3.2));

WITH  coalesce(255, toNullable(2)), (0., 2.) AS reference_vec SELECT coalesce(toFixedString('val', 3), 3, 3, toNullable(3), 3, 3, 3, 24, 13), id, vec, cosineDistance(vec, reference_vec) FROM tab_usearch__fuzz_9 PREWHERE coalesce(13, toUInt128(510), toLowCardinality(toNullable('- Annoy: WHERE-type')), toNullable(19), 19, 13) ORDER BY cosineDistance(vec, reference_vec) ASC NULLS LAST LIMIT 9223372036854775806 SETTINGS allow_experimental_analyzer = true, allow_experimental_annoy_index = true, allow_experimental_usearch_index = true, max_limit_for_ann_queries = 9223372036854775806;
```

ASAN report
https://pastila.nl/?000ff419/74f4be307caddd1a7e92e4423047849b#/Td8ZXUHS/7Y5MtLTPEBgA==

### PR DESCRIPTION
**Pull request by antonio2368**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Fix https://github.com/ClickHouse/ClickHouse/issues/61780

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-ch-test-poll2** [comment]
*This is an automated comment for commit 33bb6624db355c32684222d61d0381ffcb53a7fe with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/67884/33bb6624db355c32684222d61d0381ffcb53a7fe/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

**Review by alexey-milovidov — APPROVED** [review]

**Comment by antonio2368** [comment]
https://s3.amazonaws.com/clickhouse-test-reports/67884/83848cc22408b1ee01da9bc654e8c451551c130f/stateless_tests__release__old_analyzer__s3__databasereplicated__[1_4].html
Failure related

**Comment by rschu1ze** [comment]
[@antonio2368 Thanks for this PR. It actually performs a full-fledged update of usearch as the [fix](https://github.com/unum-cloud/usearch/pull/402/commits/9c16dba333617a3d90eaf91debdb4a77e353a28c) for https://github.com/ClickHouse/ClickHouse/issues/61780 was mixed into a [huge library upgrade PR](https://github.com/unum-cloud/usearch/pull/402#event-13771876964) 🫤

The thing is: https://github.com/ClickHouse/ClickHouse/pull/63675 reworks usearch indexes anyways, and a usearch library will introduce another source of instability (I found already some issues with usearch in that other PR). Also, a proper usearch upgrade also needs upgraded simsimd and PF16 submodules. Basically, I would like to do the upgrade separately and after the other PR is merged.

As a more lightweight-alternative, I forked usearch and applied your fix on top of the current version (we should have done so right from the beginning).

**Comment by antonio2368** [comment]
@rschu1ze no worries, it really took too long for the version to get released... thanks for taking care of it

**Pull request closed without merging**
