### PR TITLE
Add a docs page for the PostgreSQL wire protocol

### PR DESCRIPTION
**Pull request by rfraposa**
### Changelog category (leave one):
- Documentation (changelog entry is not required)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
Do regular sha256 passwords work? I remember there was something about password_double_sha1_hex? Or it is for MySQL?

**Comment by alexey-milovidov** [comment]
Also a question about TLS, do I have to enable it or everything works automatically?

**Comment by rfraposa** [comment]
I used a plain-text password for `alice` and it worked fine. I'm not sure about TLS - I did not test it. Let me play around with it.

```
<clickhouse>
    <users>
      <alice>
          <profile>analytics</profile>
            <networks>
                  <ip>::/0</ip>
            </networks>
          <password>password</password>
          <quota>analytics</quota>
      </alice>
    </users>
</clickhouse>
```

**Comment by alexey-milovidov** [comment]
Not many users will be ok with plaintext password - nevertheless, one of sha256, double_sha256 work, we should add it to the examples. TLS also needed.

**Comment by rfraposa** [comment]
Yes - more work is needed here. Using any other type of password (like `password_sha256_hex` or `password_double_sha1_hex`) causes a connection error from `psql`:

```
psql -p 9005 -h 127.0.0.1 -U alice -W default
Password:
psql: error: connection to server at "127.0.0.1", port 9005 failed: SSL SYSCALL error: Undefined error: 0
connection to server at "127.0.0.1", port 9005 failed: ERROR:  Authentication method is not supported
```

**Comment by e-mars** [comment]
some notes from my tests, if they are helpful.

created a SQL user and granted admin rights for testing with only plain text password:
```
CREATE USER clickhouse_admin IDENTIFIED WITH plaintext_password BY 'password';
GRANT ALL ON *.* TO clickhouse_admin WITH GRANT OPTION;
```

used this new user in `psql` and the cert/key from the target clickhouse node.
```
[root@marsdb4 ssl-chnode1]# psql "port=9005 host=chnode1.marsnet.local user=clickhouse_admin dbname=default sslcert=/Data/ssl-chnode1/chnode1.crt sslkey=/Data/ssl-chnode1/chnode1.key sslrootcert=/Data/ssl-chnode1/marsnet_ca.crt sslmode=verify-ca"
Password for user clickhouse_admin:
psql (12.10, server 22.3.3.44)
WARNING: psql major version 12, server major version 22.
         Some psql features might not work.
SSL connection (protocol: TLSv1.2, cipher: ECDHE-RSA-AES256-GCM-SHA384, bits: 256, compression: off)
Type "help" for help.

default=>
```

Existing Github Issue. I added the `enhancement` and `unfinished code` labels.
https://github.com/ClickHouse/ClickHouse/issues/28159

**Pull request merged**
