### PR TITLE
Fix non-deterministic test results uncovered by SSE2-only build

### PR DESCRIPTION
**Pull request by rschu1ze**
Fixes some non-deterministic expected test results uncovered by #41288 caused by missing `ORDER BY`.

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
Ok.

FYI everything is because of the usage of CRC32-C.

**Comment by rschu1ze** [comment]
True.

This PR can be merged when tests are green but I'll likely do another cycle in the [original PR](https://github.com/ClickHouse/ClickHouse/pull/41288) because I was not sure for every test failure if it is caused by SSE2 or something else.

**Comment by rschu1ze** [comment]
... like you said (and I verified locally): the remaining failures are because some sql functions use intHashCRC32() / _mm_crc32_u64. So there is nothing left to fix here.

**Comment by rschu1ze** [comment]
Changed tests were green --> merging.

**Pull request merged**
