### PR TITLE
Update style python

### PR DESCRIPTION
**Pull request by Felixoid**
### Changelog category (leave one):
- Build/Testing/Packaging Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Update python related style checkers. Continue the #50174

### CODE REVIEW

**Comment by robot-ch-test-poll1** [comment]
*This is an automated comment for commit 98d08809529ba870f753ca38d20c81723309c4da with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/60408/98d08809529ba870f753ca38d20c81723309c4da/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/60408/98d08809529ba870f753ca38d20c81723309c4da/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Comment by Felixoid** [comment]
Here's a success style check https://s3.amazonaws.com/clickhouse-test-reports/60408/574e66194e4d850eb1b3a1b4a0d00b4774982e97/style_check.html

**Comment by Felixoid** [comment]
@maxknv what do you think, can we easily identify if the style check image differs for head and merge commit?

It's following the https://github.com/ClickHouse/ClickHouse/pull/61105#issuecomment-1986385268

Then we can reliably suggest updating the branch in the report, I think.

**Comment by maxknv** [comment]
such a style check update breaks CI for all open PRs that are receiving new commit.
this solution won't make people happy, I'm afraid

**Comment by Felixoid** [comment]
I think, even if we would notify the PR about a way-to-fix, it would be an improvement. Sure, the best approach would be avoiding breaking, but I am stuck in the thinking of how to implement it.

**Pull request merged**
