### PR TITLE
Add simple "fake time" capabilities

### LINKED ISSUE #18711: Randomize wall clock time for tests
Provide wrapper functions for libc (similar to libfaketime) to randomize time:
- start time from random point;
- increment time by random intervals at every call.

It will help to catch more errors in tests (time bombs, lack of DST support, etc).

### PR DESCRIPTION
**Pull request by alexey-milovidov**
Changelog category (leave one):
- Build/Testing/Packaging Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Allow to forge current time for testing purposes. This closes #18711.

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
Waiting on condvars with timeout is broken.

**Comment by alexey-milovidov** [comment]
@zhang2014 @BohuTANG

> test_materialize_mysql_database/test.py::test_select_without_columns_8_0[clickhouse_node1]

Failed without a reason.

**Comment by zhang2014** [comment]
> Failed without a reason.

I will try to fix it.

**Comment by alexey-milovidov** [comment]
The task appeared to be too hard to implement correctly for condvars with timedwait functions expecting absolute time.

**Comment by alexey-milovidov** [comment]
Although testing with fake time is very valuable for detection of time bombs.

**Comment by alexey-milovidov** [comment]
This PR will be easier to do if/when we will compile our own libc (Musl or LLVM-libc) from sources.

**Pull request closed without merging**
