### PR TITLE
Update Annoy

### PR DESCRIPTION
**Pull request by alexey-milovidov**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Note: the Annoy library is almost dormant, and the code quality is amateur-grade (see https://github.com/spotify/annoy/issues/456)
It's unclear if we will be able to use it in production.

### CODE REVIEW

**Comment by robot-ch-test-poll** [comment]
*This is an automated comment for commit 7a42fb832f5a27f02ab3e85cdb062812aae40c4a with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/58572/7a42fb832f5a27f02ab3e85cdb062812aae40c4a/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/58572/7a42fb832f5a27f02ab3e85cdb062812aae40c4a/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Review by Algunenano — CHANGES_REQUESTED** [review]
Great job by the CI. Crash in 02354_vector_search_bugs (which uses annoy) https://s3.amazonaws.com/clickhouse-test-reports/58572/8246e05f53b8318e2056e67d4c56bce7603c9ed1/stateless_tests__msan__[5_6].html

**Comment by alexey-milovidov** [comment]
I'm still not convinced whether we need Annoy at all.

Advantages:
- it is a single .h file, only 1500 lines;

Disadvantages:
- a mixture of weird templates and C-style code from the 80s;

We should deconstruct this library, understand every piece of it, and possibly decide that we don't need it at all.

**Comment by Algunenano** [comment]
> a mixture of weird templates and C-style code from the 80s;

https://www.youtube.com/watch?v=dOV5WXISM24

**Pull request closed without merging**
