### PR TITLE
increase default replicated_deduplication_window from 100 to 1k

### PR DESCRIPTION
**Pull request by sichenzhao**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Increase default `replicated_deduplication_window` of MergeTree settings from 100 to 1k.

### Documentation entry for user-facing changes

- [ x ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by robot-ch-test-poll2** [comment]
*This is an automated comment for commit 1b8b1c0a63878f2c4e536f824df7ea77504bf8cf with description of existing statuses. It's updated for the latest CI running*

[❌ Click here](https://s3.amazonaws.com/clickhouse-test-reports/57335/1b8b1c0a63878f2c4e536f824df7ea77504bf8cf/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://github.com/ClickHouse/ClickHouse/blob/master/.github/PULL_REQUEST_TEMPLATE.md?plain=1">❌ failure</a></td></tr>
<tbody>
</table>

**Comment by den-crane** [comment]
Why do you think it's a good idea? 
It will increase Zookeeper database size for all users. 
Also it will increase network traffic between Zookeeper and Clickhouse, because Clickhouse fetches all deduplication blocks during cleaning.

It's quite danger change.

**Comment by CheSema** [comment]
It is already:
 > replicated_deduplication_window_for_async_inserts, 10000

The same code is clearing "blocks" and "async_blocks".

**Comment by CheSema** [comment]
The deduplication is stop working with obscure error when that window overflow due to intensive inserts. That is the motivation to increase that settings.

**Review by CheSema — APPROVED** [review]

**Pull request merged**
