### PR TITLE
Add tests from #15889

### LINKED ISSUE #15889: Block structure mismatch in PipelineExecuting stream
```
2020.10.12 13:15:05.239308 [ 97 ] {d01a7689-5432-480c-8007-6a12895bf9ee} <Debug> executeQuery: (from [::1]:46320) WITH ((SELECT query_start_time_microseconds FROM system.query_log ORDER BY query_start_time DESC LIMIT 1) AS time_with_microseconds, (SELECT inf, query_start_time FROM system.query_log ORDER BY query_start_time DESC LIMIT 1) AS t) SELECT if(dateDiff('second', toDateTime(time_with_microseconds), toDateTime(t)) = -9223372036854775808, 'ok', '')
2020.10.12 13:15:05.243710 [ 97 ] {d01a7689-5432-480c-8007-6a12895bf9ee} <Trace> ContextAccess (default): Access granted: SELECT(query_start_time, query_start_time_microseconds) ON system.query_log
2020.10.12 13:15:05.245355 [ 97 ] {d01a7689-5432-480c-8007-6a12895bf9ee} <Debug> system.query_log (d975bd7e-9255-4c3a-9c9e-84a3ac6e62aa) (SelectExecutor): Key condition: unknown
2020.10.12 13:15:05.245454 [ 97 ] {d01a7689-5432-480c-8007-6a12895bf9ee} <Debug> system.query_log (d975bd7e-9255-4c3a-9c9e-84a3ac6e62aa) (SelectExecutor): MinMax index condition: unknown
2020.10.12 13:15:05.245813 [ 235 ] {d01a7689-5432-480c-8007-6a12895bf9ee} <Trace> system.query_log (d975bd7e-9255-4c3a-9c9e-84a3ac6e62aa) (SelectExecutor): Not using primary index on part 202010_1_60_9
2020.10.12 13:15:05.245845 [ 229 ] {d01a7689-5432-480c-8007-6a12895bf9ee} <Trace> system.query_log (d975bd7e-9255-4c3a-9c9e-84a3ac6e62aa) (SelectExecutor): Not using primary index on part 202010_63_63_0
2020.10.12 13:15:05.245863 [ 226 ] {d01a7689-5432-480c-8007-6a12895bf9ee} <Trace> system.query_log (d975bd7e-9255-4c3a-9c9e-84a3ac6e62aa) (SelectExecutor): Not using primary index on part 202010_61_61_0
2020.10.12 13:15:05.245884 [ 234 ] {d01a7689-5432-480c-8007-6a12895bf9ee} <Trace> system.query_log (d975bd7e-9255-4c3a-9c9e-84a3ac6e62aa) (SelectExecutor): Not using primary index on part 202010_64_64_0
2020.10.12 13:15:05.245916 [ 228 ] {d01a7689-5432-480c-8007-6a12895bf9ee} <Trace> system.query_log (d975bd7e-9255-4c3a-9c9e-84a3ac6e62aa) (SelectExecutor): Not using primary index on part 202010_62_62_0
2020.10.12 13:15:05.246204 [ 97 ] {d01a7689-5432-480c-8007-6a12895bf9ee} <Debug> system.query_log (d975bd7e-9255-4c3a-9c9e-84a3ac6e62aa) (SelectExecutor): Selected 5 parts by partition key, 5 parts by primary key, 12 marks by primary key, 12 marks to read from 5 ranges
2020.10.12 13:15:05.248770 [ 97 ] {d01a7689-5432-480c-8007-6a12895bf9ee} <Trace> system.query_log (d975bd7e-9255-4c3a-9c9e-84a3ac6e62aa) (SelectExecutor): Reading approx. 19739 rows with 5 streams
2020.10.12 13:15:05.251524 [ 97 ] {d01a7689-5432-480c-8007-6a12895bf9ee} <Trace> InterpreterSelectQuery: FetchColumns -> Complete
2020.10.12 13:15:05.260614 [ 227 ] {d01a7689-5432-480c-8007-6a12895bf9ee} <Debug> MergingSortedTransform: Merge sorted 1 blocks, 1 rows in 0.004000037 sec., 249.99768752139045 rows/sec., 18.55 KiB/sec
2020.10.12 13:15:05.261034 [ 227 ] {d01a7689-5432-480c-8007-6a12895bf9ee} <Trace> PipelineExecutor: Thread finished. Total time: 0.003778689 sec. Execution time: 0.003262682 sec. Processing time: 0.000480476 sec. Wait time: 3.5531e-05 sec.
2020.10.12 13:15:05.261079 [ 236 ] {d01a7689-5432-480c-8007-6a12895bf9ee} <Trace> PipelineExecutor: Thread finished. Total time: 0.003783064 sec. Execution time: 0.000933743 sec. Processing time: 0.000229429 sec. Wait time: 0.002619892 sec.
2020.10.12 13:15:05.261081 [ 225 ] {d01a7689-5432-480c-8007-6a12895bf9ee} <Trace> PipelineExecutor: Thread finished. Total time: 0.003868763 sec. Execution time: 0.00091308 sec. Processing time: 0.000267219 sec. Wait time: 0.002688464 sec.
2020.10.12 13:15:05.261081 [ 238 ] {d01a7689-5432-480c-8007-6a12895bf9ee} <Trace> PipelineExecutor: Thread finished. Total time: 0.003764126 sec. Execution time: 0.000826601 sec. Processing time: 0.000233279 sec. Wait time: 0.002704246 sec.
2020.10.12 13:15:05.261082 [ 230 ] {d01a7689-5432-480c-8007-6a12895bf9ee} <Trace> PipelineExecutor: Thread finished. Total time: 0.003799183 sec. Execution time: 0.000983339 sec. Processing time: 0.000247121 sec. Wait time: 0.002568723 sec.
2020.10.12 13:15:05.266979 [ 97 ] {d01a7689-5432-480c-8007-6a12895bf9ee} <Trace> ContextAccess (default): Access granted: SELECT(query_start_time) ON system.query_log
2020.10.12 13:15:05.268713 [ 97 ] {d01a7689-5432-480c-8007-6a12895bf9ee} <Debug> system.query_log (d975bd7e-9255-4c3a-9c9e-84a3ac6e62aa) (SelectExecutor): Key condition: unknown
2020.10.12 13:15:05.268798 [ 97 ] {d01a7689-5432-480c-8007-6a12895bf9ee} <Debug> system.query_log (d975bd7e-9255-4c3a-9c9e-84a3ac6e62aa) (SelectExecutor): MinMax index condition: unknown
2020.10.12 13:15:05.269171 [ 231 ] {d01a7689-5432-480c-8007-6a12895bf9ee} <Trace> system.query_log (d975bd7e-9255-4c3a-9c9e-84a3ac6e62aa) (SelectExecutor): Not using primary index on part 202010_1_60_9
2020.10.12 13:15:05.269174 [ 239 ] {d01a7689-5432-480c-8007-6a12895bf9ee} <Trace> system.query_log (d975bd7e-9255-4c3a-9c9e-84a3ac6e62aa) (SelectExecutor): Not using primary index on part 202010_61_61_0
2020.10.12 13:15:05.269197 [ 233 ] {d01a7689-5432-480c-8007-6a12895bf9ee} <Trace> system.query_log (d975bd7e-9255-4c3a-9c9e-84a3ac6e62aa) (SelectExecutor): Not using primary index on part 202010_63_63_0
2020.10.12 13:15:05.269229 [ 237 ] {d01a7689-5432-480c-8007-6a12895bf9ee} <Trace> system.query_log (d975bd7e-9255-4c3a-9c9e-84a3ac6e62aa) (SelectExecutor): Not using primary index on part 202010_64_64_0
2020.10.12 13:15:05.269241 [ 240 ] {d01a7689-5432-480c-8007-6a12895bf9ee} <Trace> system.query_log (d975bd7e-9255-4c3a-9c9e-84a3ac6e62aa) (SelectExecutor): Not using primary index on part 202010_62_62_0
2020.10.12 13:15:05.269508 [ 97 ] {d01a7689-5432-480c-8007-6a12895bf9ee} <Debug> system.query_log (d975bd7e-9255-4c3a-9c9e-84a3ac6e62aa) (SelectExecutor): Selected 5 parts by partition key, 5 parts by primary key, 12 marks by primary key, 12 marks to read from 5 ranges
2020.10.12 13:15:05.271821 [ 97 ] {d01a7689-5432-480c-8007-6a12895bf9ee} <Trace> system.query_log (d975bd7e-9255-4c3a-9c9e-84a3ac6e62aa) (SelectExecutor): Reading approx. 19739 rows with 5 streams
2020.10.12 13:15:05.274314 [ 97 ] {d01a7689-5432-480c-8007-6a12895bf9ee} <Trace> InterpreterSelectQuery: FetchColumns -> Complete
2020.10.12 13:15:05.281264 [ 229 ] {d01a7689-5432-480c-8007-6a12895bf9ee} <Debug> MergingSortedTransform: Merge sorted 1 blocks, 1 rows in 0.004000038 sec., 249.9976250225623 rows/sec., 18.55 KiB/sec
2020.10.12 13:15:05.281608 [ 229 ] {d01a7689-5432-480c-8007-6a12895bf9ee} <Trace> PipelineExecutor: Thread finished. Total time: 0.002385765 sec. Execution time: 0.001881305 sec. Processing time: 0.00046749 sec. Wait time: 3.697e-05 sec.
2020.10.12 13:15:05.281631 [ 235 ] {d01a7689-5432-480c-8007-6a12895bf9ee} <Trace> PipelineExecutor: Thread finished. Total time: 0.002407127 sec. Execution time: 0.000738441 sec. Processing time: 0.000247655 sec. Wait time: 0.001421031 sec.
2020.10.12 13:15:05.281710 [ 227 ] {d01a7689-5432-480c-8007-6a12895bf9ee} <Trace> PipelineExecutor: Thread finished. Total time: 0.00241224 sec. Execution time: 0.000765352 sec. Processing time: 0.000233002 sec. Wait time: 0.001413886 sec.
2020.10.12 13:15:05.281710 [ 226 ] {d01a7689-5432-480c-8007-6a12895bf9ee} <Trace> PipelineExecutor: Thread finished. Total time: 0.002424628 sec. Execution time: 0.000724931 sec. Processing time: 0.000227065 sec. Wait time: 0.001472632 sec.
2020.10.12 13:15:05.281711 [ 228 ] {d01a7689-5432-480c-8007-6a12895bf9ee} <Trace> PipelineExecutor: Thread finished. Total time: 0.002506015 sec. Execution time: 0.000779022 sec. Processing time: 0.000249285 sec. Wait time: 0.001477708 sec.
2020.10.12 13:15:05.281775 [ 97 ] {d01a7689-5432-480c-8007-6a12895bf9ee} <Error> : Logical error: 'Block structure mismatch in PipelineExecuting stream: different columns:
inf Float64 Float64(size = 1), query_start_time DateTime UInt32(size = 1)
inf Float64 Const(size = 0, Float64(size = 1)), query_start_time DateTime UInt32(size = 0)'.
clickhouse-server: ../src/Common/Exception.cpp:45: DB::Exception::Exception(const std::string &, int): Assertion `false' failed.
2020.10.12 13:15:05.282203 [ 64 ] {} <Trace> BaseDaemon: Received signal 6
[linux-ubuntu-14-04-trusty] 2020.10.12 13:15:05.282647 [ 241 ] <Fatal> BaseDaemon: ########################################
[linux-ubuntu-14-04-trusty] 2020.10.12 13:15:05.283063 [ 241 ] <Fatal> BaseDaemon: (version 20.11.1.4898, build id: 04CB12865EE1D398) (from thread 97) (query_id: d01a7689-5432-480c-8007-6a12895bf9ee) Received signal Aborted (6)
[linux-ubuntu-14-04-trusty] 2020.10.12 13:15:05.283229 [ 241 ] <Fatal> BaseDaemon: 
[linux-ubuntu-14-04-trusty] 2020.10.12 13:15:05.283412 [ 241 ] <Fatal> BaseDaemon: Stack trace: 0x7f145def3f47 0x7f145def58b1 0x7f145dee542a 0x7f145dee54a2 0xfb3303c 0x17df0033 0x17ded659 0x17decdb5 0x17f650eb 0x18bf4646 0x18bf4011 0x18bb782b 0x18bb7906 0x18bb783d 0x18bf5584 0x18bf4042 0x18bb782b 0x18bb7906 0x18bb783d 0x18bb7906 0x18bb783d 0x18baff40 0x18bae6d0 0x18704084 0x1870276e 0x187015cc 0x18a048c1 0x18a0340d
[linux-ubuntu-14-04-trusty] 2020.10.12 13:15:05.283768 [ 241 ] <Fatal> BaseDaemon: 4. /build/glibc-2ORdQG/glibc-2.27/signal/../sysdeps/unix/sysv/linux/raise.c:51: gsignal @ 0x3ef47 in /usr/lib/debug/lib/x86_64-linux-gnu/libc-2.27.so
[linux-ubuntu-14-04-trusty] 2020.10.12 13:15:05.284042 [ 241 ] <Fatal> BaseDaemon: 5. /build/glibc-2ORdQG/glibc-2.27/stdlib/abort.c:81: abort @ 0x408b1 in /usr/lib/debug/lib/x86_64-linux-gnu/libc-2.27.so
[linux-ubuntu-14-04-trusty] 2020.10.12 13:15:05.284294 [ 241 ] <Fatal> BaseDaemon: 6. /build/glibc-2ORdQG/glibc-2.27/assert/assert.c:89: __assert_fail_base @ 0x3042a in /usr/lib/debug/lib/x86_64-linux-gnu/libc-2.27.so
[linux-ubuntu-14-04-trusty] 2020.10.12 13:15:05.284700 [ 241 ] <Fatal> BaseDaemon: 7. ? @ 0x304a2 in /usr/lib/debug/lib/x86_64-linux-gnu/libc-2.27.so
[linux-ubuntu-14-04-trusty] 2020.10.12 13:15:05.285015 [ 241 ] <Fatal> BaseDaemon: 8. /build/obj-x86_64-linux-gnu/../src/Common/Exception.cpp:48: DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0xfb3303c in /workspace/clickhouse
[linux-ubuntu-14-04-trusty] 2020.10.12 13:15:05.316964 [ 241 ] <Fatal> BaseDaemon: 9. /build/obj-x86_64-linux-gnu/../src/Core/Block.cpp:469: void DB::checkBlockStructure<void>(DB::Block const&, DB::Block const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::'lambda'(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int)::operator()(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) const @ 0x17df0033 in /workspace/clickhouse
[linux-ubuntu-14-04-trusty] 2020.10.12 13:15:05.348594 [ 241 ] <Fatal> BaseDaemon: 10. /build/obj-x86_64-linux-gnu/../src/Core/Block.cpp:496: void DB::checkBlockStructure<void>(DB::Block const&, DB::Block const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x17ded659 in /workspace/clickhouse
[linux-ubuntu-14-04-trusty] 2020.10.12 13:15:05.380109 [ 241 ] <Fatal> BaseDaemon: 11. /build/obj-x86_64-linux-gnu/../src/Core/Block.cpp:524: DB::assertBlocksHaveEqualStructure(DB::Block const&, DB::Block const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x17decdb5 in /workspace/clickhouse
[linux-ubuntu-14-04-trusty] 2020.10.12 13:15:05.411921 [ 241 ] <Fatal> BaseDaemon: 12. /build/obj-x86_64-linux-gnu/../src/DataStreams/IBlockInputStream.cpp:90: DB::IBlockInputStream::read() @ 0x17f650eb in /workspace/clickhouse
[linux-ubuntu-14-04-trusty] 2020.10.12 13:15:05.450022 [ 241 ] <Fatal> BaseDaemon: 13. /build/obj-x86_64-linux-gnu/../src/Interpreters/ExecuteScalarSubqueriesVisitor.cpp:123: DB::ExecuteScalarSubqueriesMatcher::visit(DB::ASTSubquery const&, std::__1::shared_ptr<DB::IAST>&, DB::ExecuteScalarSubqueriesMatcher::Data&) @ 0x18bf4646 in /workspace/clickhouse
[linux-ubuntu-14-04-trusty] 2020.10.12 13:15:05.488681 [ 241 ] <Fatal> BaseDaemon: 14. /build/obj-x86_64-linux-gnu/../src/Interpreters/ExecuteScalarSubqueriesVisitor.cpp:62: DB::ExecuteScalarSubqueriesMatcher::visit(std::__1::shared_ptr<DB::IAST>&, DB::ExecuteScalarSubqueriesMatcher::Data&) @ 0x18bf4011 in /workspace/clickhouse
[linux-ubuntu-14-04-trusty] 2020.10.12 13:15:05.527750 [ 241 ] <Fatal> BaseDaemon: 15. /build/obj-x86_64-linux-gnu/../src/Interpreters/InDepthNodeVisitor.h:32: DB::InDepthNodeVisitor<DB::ExecuteScalarSubqueriesMatcher, true, std::__1::shared_ptr<DB::IAST> >::visit(std::__1::shared_ptr<DB::IAST>&) @ 0x18bb782b in /workspace/clickhouse
[linux-ubuntu-14-04-trusty] 2020.10.12 13:15:05.566789 [ 241 ] <Fatal> BaseDaemon: 16. /build/obj-x86_64-linux-gnu/../src/Interpreters/InDepthNodeVisitor.h:45: DB::InDepthNodeVisitor<DB::ExecuteScalarSubqueriesMatcher, true, std::__1::shared_ptr<DB::IAST> >::visitChildren(std::__1::shared_ptr<DB::IAST>&) @ 0x18bb7906 in /workspace/clickhouse
[linux-ubuntu-14-04-trusty] 2020.10.12 13:15:05.605881 [ 241 ] <Fatal> BaseDaemon: 17. /build/obj-x86_64-linux-gnu/../src/Interpreters/InDepthNodeVisitor.h:35: DB::InDepthNodeVisitor<DB::ExecuteScalarSubqueriesMatcher, true, std::__1::shared_ptr<DB::IAST> >::visit(std::__1::shared_ptr<DB::IAST>&) @ 0x18bb783d in /workspace/clickhouse
[linux-ubuntu-14-04-trusty] 2020.10.12 13:15:05.643867 [ 241 ] <Fatal> BaseDaemon: 18. /build/obj-x86_64-linux-gnu/../src/Interpreters/ExecuteScalarSubqueriesVisitor.cpp:205: DB::ExecuteScalarSubqueriesMatcher::visit(DB::ASTFunction const&, std::__1::shared_ptr<DB::IAST>&, DB::ExecuteScalarSubqueriesMatcher::Data&) @ 0x18bf5584 in /workspace/clickhouse
[linux-ubuntu-14-04-trusty] 2020.10.12 13:15:05.681551 [ 241 ] <Fatal> BaseDaemon: 19. /build/obj-x86_64-linux-gnu/../src/Interpreters/ExecuteScalarSubqueriesVisitor.cpp:64: DB::ExecuteScalarSubqueriesMatcher::visit(std::__1::shared_ptr<DB::IAST>&, DB::ExecuteScalarSubqueriesMatcher::Data&) @ 0x18bf4042 in /workspace/clickhouse
[linux-ubuntu-14-04-trusty] 2020.10.12 13:15:05.719981 [ 241 ] <Fatal> BaseDaemon: 20. /build/obj-x86_64-linux-gnu/../src/Interpreters/InDepthNodeVisitor.h:32: DB::InDepthNodeVisitor<DB::ExecuteScalarSubqueriesMatcher, true, std::__1::shared_ptr<DB::IAST> >::visit(std::__1::shared_ptr<DB::IAST>&) @ 0x18bb782b in /workspace/clickhouse
[linux-ubuntu-14-04-trusty] 2020.10.12 13:15:05.757929 [ 241 ] <Fatal> BaseDaemon: 21. /build/obj-x86_64-linux-gnu/../src/Interpreters/InDepthNodeVisitor.h:45: DB::InDepthNodeVisitor<DB::ExecuteScalarSubqueriesMatcher, true, std::__1::shared_ptr<DB::IAST> >::visitChildren(std::__1::shared_ptr<DB::IAST>&) @ 0x18bb7906 in /workspace/clickhouse
[linux-ubuntu-14-04-trusty] 2020.10.12 13:15:05.796083 [ 241 ] <Fatal> BaseDaemon: 22. /build/obj-x86_64-linux-gnu/../src/Interpreters/InDepthNodeVisitor.h:35: DB::InDepthNodeVisitor<DB::ExecuteScalarSubqueriesMatcher, true, std::__1::shared_ptr<DB::IAST> >::visit(std::__1::shared_ptr<DB::IAST>&) @ 0x18bb783d in /workspace/clickhouse
[linux-ubuntu-14-04-trusty] 2020.10.12 13:15:05.834343 [ 241 ] <Fatal> BaseDaemon: 23. /build/obj-x86_64-linux-gnu/../src/Interpreters/InDepthNodeVisitor.h:45: DB::InDepthNodeVisitor<DB::ExecuteScalarSubqueriesMatcher, true, std::__1::shared_ptr<DB::IAST> >::visitChildren(std::__1::shared_ptr<DB::IAST>&) @ 0x18bb7906 in /workspace/clickhouse
[linux-ubuntu-14-04-trusty] 2020.10.12 13:15:05.872787 [ 241 ] <Fatal> BaseDaemon: 24. /build/obj-x86_64-linux-gnu/../src/Interpreters/InDepthNodeVisitor.h:35: DB::InDepthNodeVisitor<DB::ExecuteScalarSubqueriesMatcher, true, std::__1::shared_ptr<DB::IAST> >::visit(std::__1::shared_ptr<DB::IAST>&) @ 0x18bb783d in /workspace/clickhouse
[linux-ubuntu-14-04-trusty] 2020.10.12 13:15:05.910316 [ 241 ] <Fatal> BaseDaemon: 25. /build/obj-x86_64-linux-gnu/../src/Interpreters/TreeRewriter.cpp:229: DB::(anonymous namespace)::executeScalarSubqueries(std::__1::shared_ptr<DB::IAST>&, DB::Context const&, unsigned long, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, DB::Block, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, DB::Block> > >&, bool) @ 0x18baff40 in /workspace/clickhouse
[linux-ubuntu-14-04-trusty] 2020.10.12 13:15:05.947266 [ 241 ] <Fatal> BaseDaemon: 26. /build/obj-x86_64-linux-gnu/../src/Interpreters/TreeRewriter.cpp:608: DB::TreeRewriter::analyzeSelect(std::__1::shared_ptr<DB::IAST>&, DB::TreeRewriterResult&&, DB::SelectQueryOptions const&, std::__1::vector<DB::TableWithColumnNamesAndTypes, std::__1::allocator<DB::TableWithColumnNamesAndTypes> > const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::shared_ptr<DB::TableJoin>) const @ 0x18bae6d0 in /workspace/clickhouse
[linux-ubuntu-14-04-trusty] 2020.10.12 13:15:05.983404 [ 241 ] <Fatal> BaseDaemon: 27. /build/obj-x86_64-linux-gnu/../src/Interpreters/InterpreterSelectQuery.cpp:314: DB::InterpreterSelectQuery::InterpreterSelectQuery(std::__1::shared_ptr<DB::IAST> const&, DB::Context const&, std::__1::shared_ptr<DB::IBlockInputStream> const&, std::__1::optional<DB::Pipe>, std::__1::shared_ptr<DB::IStorage> const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&)::$_2::operator()(bool) const @ 0x18704084 in /workspace/clickhouse
[linux-ubuntu-14-04-trusty] 2020.10.12 13:15:06.019105 [ 241 ] <Fatal> BaseDaemon: 28. /build/obj-x86_64-linux-gnu/../src/Interpreters/InterpreterSelectQuery.cpp:405: DB::InterpreterSelectQuery::InterpreterSelectQuery(std::__1::shared_ptr<DB::IAST> const&, DB::Context const&, std::__1::shared_ptr<DB::IBlockInputStream> const&, std::__1::optional<DB::Pipe>, std::__1::shared_ptr<DB::IStorage> const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&) @ 0x1870276e in /workspace/clickhouse
[linux-ubuntu-14-04-trusty] 2020.10.12 13:15:06.054345 [ 241 ] <Fatal> BaseDaemon: 29. /build/obj-x86_64-linux-gnu/../src/Interpreters/InterpreterSelectQuery.cpp:146: DB::InterpreterSelectQuery::InterpreterSelectQuery(std::__1::shared_ptr<DB::IAST> const&, DB::Context const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) @ 0x187015cc in /workspace/clickhouse
[linux-ubuntu-14-04-trusty] 2020.10.12 13:15:06.089993 [ 241 ] <Fatal> BaseDaemon: 30. /build/obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:3028: std::__1::__unique_if<DB::InterpreterSelectQuery>::__unique_single std::__1::make_unique<DB::InterpreterSelectQuery, std::__1::shared_ptr<DB::IAST>&, DB::Context&, DB::SelectQueryOptions&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&>(std::__1::shared_ptr<DB::IAST>&, DB::Context&, DB::SelectQueryOptions&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) @ 0x18a048c1 in /workspace/clickhouse
[linux-ubuntu-14-04-trusty] 2020.10.12 13:15:06.126074 [ 241 ] <Fatal> BaseDaemon: 31. /build/obj-x86_64-linux-gnu/../src/Interpreters/InterpreterSelectWithUnionQuery.cpp:84: DB::InterpreterSelectWithUnionQuery::InterpreterSelectWithUnionQuery(std::__1::shared_ptr<DB::IAST> const&, DB::Context const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) @ 0x18a0340d in /workspace/clickhouse
```

### PR DESCRIPTION
**Pull request by KochetovNicolai**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Closes #15889

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]

**Comment by KochetovNicolai** [comment]
Ok, it fails for debug build.

**Comment by alexey-milovidov** [comment]
@KochetovNicolai Arcadia does not support distributed queries:

```
Code: 279. DB::Exception: Received from localhost:35650. DB::Exception: All connection tries failed. Log: 
E   
E   Code: 210, e.displayText() = DB::NetException: Connection refused (localhost:59000) (version 21.1.1.5646-arcadia)
E   Code: 210, e.displayText() = DB::NetException: Connection refused (localhost:59000) (version 21.1.1.5646-arcadia)
E   Code: 210, e.displayText() = DB::NetException: Connection refused (localhost:59000) (version 21.1.1.5646-arcadia)
```

**Comment by alexey-milovidov** [comment]
`Table system.query_log doesn't exist`

Need one more change to make sure query_log exists.

**Comment by alexey-milovidov** [comment]
Ok, I've added SYSTEM FLUSH LOGS.

**Pull request merged**
