### PR TITLE
Create detached folder during fetch partition if necessary

### PR DESCRIPTION
**Pull request by canhld94**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
- Create detached folder during fetch partition if necessary

Because `detached` folder may be lost, e.g. when we insert new disk, then add to storage policy, without restarting the clickhouse process.

### Documentation entry for user-facing changes

- [x] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by tavplubix** [comment]
> Because detached folder may be lost, e.g. when we insert new disk, then add to storage policy, without restarting the clickhouse process.

The detached folder should never be lost. How to reproduce it? Is it possible to add a test? Do I understand correctly that it requires manual intervention?

**Comment by canhld94** [comment]
> The detached folder should never be lost. How to reproduce it? Is it possible to add a test? Do I understand correctly that it requires manual intervention?

It's hard to add a test, but I can give an example of missing `detached` folder. We have a server with 3 disks 0, 1, 2; and CH are using 2 disks 0 and 1  to store data with a JBOD policy. Then disks `0` and `1` run out of space, so we need to add disk 2 to the storage policy, and CH start writing data to disk 2. Everything is fine, except there's no `detached` folder, so `FETCH PARTITION` commands start failing.

I did check the code. The `detached` folder will only be created when in the constructor of `StorageReplicatedMergeTree`, which requires restarting CH.

**Comment by canhld94** [comment]
@tavplubix hi, is this example make sense to you? I think we can reproduce it fairly easy, is this necessary to add a test?
Even though the issue is not severe and can be easily fixed by restarting the ClickHouse process, it can confuse the operation engineer who are not familiar with the codebase.  And I think adding new disk without restarting the ClickHouse process is quite a common practice.

**Comment by canhld94** [comment]
> * Introduce a mechanism that will notify tables about changed storage policies, so *MergeTree tables will be able to call `initializeDirectoriesAndFormatVersion` if new disks were added.

May be this a good way to go, I will check if this is possible to do.

**Comment by alexey-milovidov** [comment]
Ok. Please send a PR with the proposed change.

**Comment by canhld94** [comment]
@tavplubix just a quick note:

> - Do not reload storage policies from config without restarting the server (because it works incorrectly without restarting).
> - Introduce a mechanism that will notify tables about changed storage policies, so *MergeTree tables will be able to call initializeDirectoriesAndFormatVersion if new disks were added.

Unfortunately I think both solutions will not completely solve the issue. This exception can also happens in another case: a disk mounted on `/disk1` corrupted, then we replace it with a completely new disk. This is pure hardware intervention and I don't know how we can notify CH about this change.

Thinking more about the solution.

**Comment by tavplubix** [comment]
> This exception can also happens in another case: a disk mounted on /disk1 corrupted, then we replace it with a completely new disk. This is pure hardware intervention and I don't know how we can notify CH about this change.

Just restart the server. It will call `initializeDirectoriesAndFormatVersion` on startup and will create missing `detached/` dir. We don't need to support "hot" hardware interventions in runtime. 

The problem with reloading storage policies config is that it can change storage configuration in runtime, and MergeTree does not expect that

**Comment by canhld94** [comment]
> Just restart the server. It will call initializeDirectoriesAndFormatVersion on startup and will create missing detached/ dir. We don't need to support "hot" hardware interventions in runtime.
> 
> The problem with reloading storage policies config is that it can change storage configuration in runtime, and MergeTree does not expect that

Then, the idea could be: `DatabaseCatalog` can have a `reinit_merge_tree_directories` task. When `Context::updateStorageConfiguration` called, it will ask `DatabaseCatalog` to schedule this task. The task will loop through all table, if it's a `MergeTreeData` object then will call `initializeDirectoriesAndFormatVersion`.

Does this sound ok to you?

**Comment by tavplubix** [comment]
> Then, the idea could be: DatabaseCatalog can have a reinit_merge_tree_directories task. When Context::updateStorageConfiguration called, it will ask DatabaseCatalog to schedule this task. The task will loop through all table

This part sounds ok.

> if it's a MergeTreeData object then will call initializeDirectoriesAndFormatVersion.

 - What about `StorageDistributed`, for example? (see my comment above)
 - `initializeDirectoriesAndFormatVersion` is some internal method of `MergeTreeData`, I'm not sure if we can simply call it from outside like this

So we need some public method in `IStorage` interface, like `reloadStoragePolicy`

----

But tbh, I would prefer another option: do not reload storage policy without restarting the server (or reload only settings, without adding/removing disks). I'm pretty sure that there are other issues with adding/removing disks in runtime

**Pull request closed without merging**
