### PR TITLE
Use interserver_http_host in isLocalAddress

### PR DESCRIPTION
**Pull request by jpiper**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

I haven't tested this yet, but I think this will fix the issue I'm having in #2154

### CODE REVIEW

**Comment by jpiper** [comment]
Gah, I have no idea what I'm doing here (I'm not a C++ dev)...

**Comment by tobad357** [comment]
I think this may fix #1793 which is that distributed ddl doesn't work if using nat interserver_http_host

**Comment by jpiper** [comment]
This PR is garbage though, so it won’t work :p but something similar should be implemented if we want CH to work behind NAT (or on clickhouse). I’ve had to resort to using hostNetwork for the timebeing

**Comment by derekperkins** [comment]
@jpiper Other than this issue, has running ClickHouse on Kubernetes been a good experience for you?

**Comment by jpiper** [comment]
It’s not that easy if you want to use the replicated tables as you have to specify the sharding schema up front with the hostnames of each node in the cluster. This is fine if you’re happy using a stateful set with persistent volumes claims but I want more control as I need replicas to be spread across failure domains (in our case, racks). In the end we ended up doing everything very un-Kubernetes - we deploy using affinity rules to keep the pods on a set of specific hosts (and not more than one pod per host) and we have to use hostNetwork (rather than hostPort) to get around the NAT issue. Data is mounted in via hostPath. 

We had a prototype running on 4 nodes as a statefulset with no data replication working very well. It’s only when we wanted to go to production and had to be sure about failure domains and replication it got a bit dicey.

**Comment by derekperkins** [comment]
Thanks for the feedback. With 1.10 supporting local PVC, I think a lot of your setup workarounds can be done more Kubernetes-y. :)

**Comment by jpiper** [comment]
The problem with local PVC is that you still don’t know about the placement before you schedule so configuring your sharding schema before you deploy isn’t possible in order to spread replicas across failure domains. Local PVs are also in beta, and I’m wary of putting all my state into a beta feature!

**Pull request closed without merging**
