### PR TITLE
Support write hdfs files with space

### PR DESCRIPTION
**Pull request by exmy**
Currently write hdfs files with space is not supported, a exception `Bad URI syntax: URI contains invalid characters. (POCO_EXCEPTION)` will throw.

But read hdfs files with space is supported.

### Changelog category (leave one):

- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Support write hdfs files with space

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Run only fuzzers related jobs (libFuzzer fuzzers, AST fuzzers, etc.)
- [ ]  Exclude: AST fuzzers
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-clickhouse-ci-1** [comment]
*This is an automated comment for commit 490371cad478ccb65979266a2946a1fe20a236e8 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/71105/490371cad478ccb65979266a2946a1fe20a236e8/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/c82cf25b3e5864bcc153cbe45adb8c6527e1ec6e/docs_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Review by yariks5s — CHANGES_REQUESTED** [review]
Could you please add a test for this case, as you described in the changelog entry?

**Comment by exmy** [comment]
> Could you please add a test for this case, as you described in the changelog entry?

@yariks5s Thanks for review! This pr may still need some change and I will add a test later.

**Comment by exmy** [comment]
@yariks5s Have updated and added a test. Please help review if you have time.

**Comment by exmy** [comment]
Seems the failed ci jobs are not related to this pr change?

**Comment by yariks5s** [comment]
> Seems the failed ci jobs are not related to this pr change?

Yes, this test is currently flaky. I will review the PR, and we will merge it if everything is ok🙂

**Review by yariks5s — APPROVED** [review]
Good overall, while reading the code, I noticed one small objection that is not related to your code, reported here: https://github.com/ClickHouse/ClickHouse/pull/59767/files#r1822779554

Upd: this is a valid issue, created a PR to fix that typo: https://github.com/ClickHouse/ClickHouse/pull/71267

**Pull request merged**
