### PR TITLE
Respect MINSIGSTKSZ for alternative stack to fix under aarch64

### LINKED ISSUE #18785: INSERT INTO table FORMAT CSV successfully but reports error msg
I run the bin/upload-data.sh from https://github.com/Altinity/tpc-ds

```
#!/bin/bash

for file_name in `ls ../data/*.dat`; do
    table_file=$(echo "${file_name##*/}")
    table_name=$(echo "${table_file%_*}" | tr '[:upper:]' '[:lower:]' | tr -d [0-9]|sed 's/__//g')
    upload_data_sql="INSERT INTO $table_name FORMAT CSV"

    echo "$upload_data_sql <-- $(du -h $file_name)"

    cat $file_name | clickhouse client --format_csv_delimiter="|" --max_partitions_per_insert_block=100 --database="tpcds" --query="$upload_data_sql"
    rm $file_name

    sleep 5
done
```
reports
INSERT INTO customer_address FORMAT CSV <-- 5.3M	../data/customer_address_1_64_0001.dat
Cannot set alternative signal stack for thread, errno: 12, strerror: Cannot allocate memory
Cannot set alternative signal stack for thread, errno: 12, strerror: Cannot allocate memory

### PR DESCRIPTION
**Pull request by azat**
Introduced-in: #16346 
Fixes: #18785

Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by azat** [comment]
01600_count_of_parts_metrics is flaky, can someone add fast-test label please?

**Comment by alexey-milovidov** [comment]
@azat #18834

**Review by alexey-milovidov — APPROVED** [review]

**Comment by azat** [comment]
Looks like it stuck already, will rebase against upstream/master

**Comment by alexey-milovidov** [comment]
BTW, what is the value of MINSIGSTKSZ on AArch64?

**Comment by azat** [comment]
>BTW, what is the value of MINSIGSTKSZ on AArch64?

5120

Refs:
- https://elixir.bootlin.com/linux/v5.11-rc2/source/arch/arm64/include/uapi/asm/signal.h#L23
- https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=c9692657c0

**Comment by alexey-milovidov** [comment]
Reasoning:
https://patchwork.ozlabs.org/project/glibc/patch/mvmwq1v2aqw.fsf@hawking.suse.de/

**Pull request merged**
