### PR TITLE
rewrite avg for algebraic optimization

### LINKED ISSUE #20092: Perform algebraic optimizations of arithmetic expressions inside aggregate functions.
Some aggregate functions are commutative with some arithmetic expressions.

```
avg(x + const) = avg(x) + const
```

This is applicable for aggregate functions: `sum`, `avg`, `min`, `max` and operations: `+`, `-`, `*`, `/` (but not for `intDiv` and `modulo`).

In case of integer overflow it either works correctly (for `sum`) or we may assume that integer overflow is implementation specific behaviour and apply optimization under this assumption.

**Possible implementation**

AST rewrite with InDepthNodeVisitor.
Should not rewrite if expression has alias.

### PR DESCRIPTION
**Pull request by ucasfl**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Perform algebraic optimizations of arithmetic expressions inside `avg` aggregate function. close #20092.

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
I have some doubts about the cases when result may change. Maybe add a separate option for it?

**Comment by ucasFL** [comment]
> I have some doubts about the cases when result may change. Maybe add a separate option for it?

There is already a setting `optimize_arithmetic_operations_in_aggregate_functions`, you mean add another setting for `avg`?

**Comment by alexey-milovidov** [comment]
Yes, let's name it `optimize_arithmetic_operations_in_aggregate_functions_avg`.

**Comment by alexey-milovidov** [comment]
Why I'm worried?

`avg(x / 2)` does not overflow right now but may start to overflow when optimization is enabled.
It is still Ok to enable it by default but we need a separate setting.

**Comment by ucasFL** [comment]
> Why I'm worried?
> 
> `avg(x / 2)` does not overflow right now but may start to overflow when optimization is enabled.
> It is still Ok to enable it by default but we need a separate setting.

But I think `sum(n / 2)` also has the problem.

**Comment by alexey-milovidov** [comment]
Ok, reasonable. Let's merge as is.

**Review by alexey-milovidov — APPROVED** [review]

**Pull request merged**
