### PR TITLE
Fix Integer overflow in Poco::UTF32Encoding

### PR DESCRIPTION
**Pull request by anfedotoff**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
- Fix Integer overflow in Poco::UTF32Encoding

[Patch](https://github.com/pocoproject/poco/commit/62f875dfe1298041289f926a6a1a39cb765b13ee) from this [issue](https://github.com/pocoproject/poco/issues/4320).

### CODE REVIEW

**Comment by robot-ch-test-poll2** [comment]
*This is an automated comment for commit 341806d44017a9c9fff3b4872e3eec40acf014d2 with description of existing statuses. It's updated for the latest CI running*

[❌ Click here](https://s3.amazonaws.com/clickhouse-test-reports/58073/341806d44017a9c9fff3b4872e3eec40acf014d2/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td><a href="https://github.com/ClickHouse/ClickHouse/actions/runs/7276276618">✅ success</a></td></tr>
<tbody>
</table>
</details>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/58073/341806d44017a9c9fff3b4872e3eec40acf014d2/ci_running.html">❌ failure</a></td></tr>
<tbody>
</table>

**Review by nickitat — APPROVED** [review]

**Comment by Algunenano** [comment]
> is it possible to update the last release after merge, or create the new patch release?

Is this a bugfix that needs to be backported? It's tagged as `Not for changelog` and it doesn't have tests that reproduce the incorrect behaviour that's being changed.

**Comment by anfedotoff** [comment]
> > is it possible to update the last release after merge, or create the new patch release?
> 
> Is this a bugfix that needs to be backported? It's tagged as `Not for changelog` and it doesn't have tests that reproduce the incorrect behaviour that's being changed.

In POCO it is a security issue. I couldn't say how it affects ClickHouse, but maybe it's better to update.

**Comment by Algunenano** [comment]
I've tested removing the following functions:
```
-    int convert(const unsigned char * bytes) const;
-    int convert(int ch, unsigned char * bytes, int length) const;
-    int queryConvert(const unsigned char * bytes, int length) const;
```

CH still builds and runs. It seems CH doesn't use these functions, so no need to backport.

**Comment by Algunenano** [comment]
I was wrong and the code still might be used. It seems POCO code doesn't go through normal linters and doesn't declare `override`, so those methods would still exists (from the parent class) when I deleted them.

**Comment by anfedotoff** [comment]
> I was wrong and the code still might be used. It seems POCO code doesn't go through normal linters and doesn't declare `override`, so those methods would still exists (from the parent class) when I deleted them.

Do we need just to change tag for backporting this patch, or we need  to prove reachability first?

**Comment by anfedotoff** [comment]
> Let me start by saying that is my opinion:
> * We can start by tagging this as a bugfix and mark it to be backported. Minor patches will be released in a normal fashion (best effort as with other bugfixes).
> * If you can prove reachability or that it means a security problem, you can report it (https://github.com/ClickHouse/ClickHouse/blob/master/SECURITY.md) to security@clickhouse.com and the process will go from there (reviewing impact, affected releases, ensure patch releases are done ASAP, etc).
> 
> Does that make sense to you?

Let's tag it as bugfix and mark it to be backported. A little bit later try to investigate the reachability.

**Comment by Algunenano** [comment]
Failures:
* `Stateless tests (release, DatabaseReplicated) [2/4]` -> `02567_and_consistency`. Already fixed in master.
* `Stress test (tsan)`. Stuck query (S3::S3Client::GetObject -> AttemptExhaustively -> RetryRequestSleep). I'll create a ticket
* Upgrade test failures due to is_deleted feature removal.

**Pull request merged**
