### PR TITLE
Make single image for building coverage report

### PR DESCRIPTION
**Pull request by alesapin**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by alesapin** [comment]
Need build for coverage with tidy. After that tests should be stopped.

**Comment by alesapin** [comment]
Small coverage https://clickhouse-test-reports.s3.yandex.net/18312/24cb824bfe79f671794816492b69a01f04d7dd74/coverage_report/test_output/index.html

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alesapin** [comment]
Coverage report https://clickhouse-test-reports.s3.yandex.net/18312/cc0c43ace53fe94c599a3ba9ec9417e184f7f15c/coverage_report/test_output/index.html,
But takes about 05h:21m:52s to prepare. Trying to build contrib in release mode.

**Comment by alesapin** [comment]
Failed to disable `-fno-inline` for libcxx, libcxx-abi and libunwind. Even when specified `-finline-functions -finline-hint-functions ` in corresponding files `target_compile_options(cxx PRIVATE -finline-functions -finline-hint-functions)` and so on. So exceptions unwinding extremely slow:
image

**Comment by alesapin** [comment]
I think as daily job we can merge it as is (5 hours per day is not too much). And trying to optimise is different PR :(

**Comment by alesapin** [comment]
When I've disabled `-fno-inline` globally everything speed up significantly.
`set (CMAKE_CXX_FLAGS_DEBUG               "${CMAKE_CXX_FLAGS_DEBUG} -O0 -g3 -ggdb3 ${CMAKE_CXX_FLAGS_ADD}")`

**Comment by alesapin** [comment]
Istructions which looks like coverage collection
image

**Comment by alesapin** [comment]
Ok, better than it was before. Will try to optimise coverage build in different PR.

**Pull request merged**
