### PR TITLE
Bump libssh to 0.9.8

### PR DESCRIPTION
**Pull request by rschu1ze**
This PR does three things:

1. I undoes some terrible silent patching caused in the submodule (also see https://github.com/ClickHouse/libssh/pull/9): https://github.com/ClickHouse/ClickHouse/pull/59563/commits/ae7dcdffd89083e3a5a4ee66838387c35853f54b

2. it upgrades libssh from v0.9.7 to v0.9.8: https://github.com/ClickHouse/ClickHouse/pull/59563/commits/e3896a31c69ae6d1f40c24ae4d40f2c7215f9e09

3. Does some cleanup in the build description for the libssh submodule https://github.com/ClickHouse/ClickHouse/pull/59563/commits/a740fc7835ff54bda95c322d9d19e31349144d8e

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by robot-ch-test-poll3** [comment]
*This is an automated comment for commit 54330087b9c0a062ea0dc82495d07cd7bb972739 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/59563/54330087b9c0a062ea0dc82495d07cd7bb972739/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/59563/54330087b9c0a062ea0dc82495d07cd7bb972739/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Comment by rschu1ze** [comment]
Ideally needs re-generated platform includes:
https://github.com/ClickHouse/ClickHouse/pull/41109/files/5c6e9416eaf2db41daf10536c9c3f05923ce807d#r1478226271

**Comment by antaljanosbenjamin** [comment]
Just posting here for visibility. I left a comment on the original PR on Robert's comment:
> Based on [config.h.cmake](https://github.com/canonical/libssh/blob/multipass/config.h.cmake) and [this](https://github.com/canonical/libssh/blob/6f4ec9be4cc3ca851de6bd1eafbd72cca18b8440/CMakeLists.txt#L112) command you have to generate them by configuring libssh using the built in cmake.

**Comment by rschu1ze** [comment]
Thanks @antaljanosbenjamin ... I updated the PR and combined it with some cleanup.

**Review by antaljanosbenjamin — APPROVED** [review]

**Comment by rschu1ze** [comment]
ClickHouse AST Fuzzer (msan): Unrelated, opened #60017

SQLLancer (release): looking at the output ([here](https://s3.amazonaws.com/clickhouse-test-reports/59563/ea89154f9f112411066eae617883c50cb741faa7/sqlancer__release_.html) and [here](https://s3.amazonaws.com/clickhouse-test-reports/59563/ea89154f9f112411066eae617883c50cb741faa7/sqlancer__release_/TLPAggregate.err)), it is not clear to me what went wrong but it is surely unrelated.

Stress test and upgrade check: unrelated as well.

**Pull request merged**
