### PR TITLE
Keeper change log compaction optimization

### PR DESCRIPTION
**Pull request by zhanglistar**
Changelog category (leave one):
- Performance Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
In the method `compact` of `Changelog`, the data structure `logs` is synchronously deleted to `up_to_log_index`, which in big data scenario, the process is slow to about second level in the current implementation, resulting operation timedout.
The change is deleting the logs spread evenly to latter reading or writing operations, which obviously decreases the long tail latency of compact.

Effect: 
client command: `./utils/keeper-bench/keeper-bench --host=127.0.0.1:12183 -c 64 --generator=create_small_data`
Pasted Graphic 7

master version(db69ab9d17d1bbb772cc8b2c18db33df6f7502ee):
read requests 0, write requests 8159900, Write RPS 46126 8  Write MiBs

> Information about CI checks: https://clickhouse.tech/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by zhanglistar** [comment]
@alesapin Can you please review the code? You are the most familiar with code here. Thanks.

**Comment by zhanglistar** [comment]
@alesapin  Unrelated fail.

**Comment by zhanglistar** [comment]
@alesapin Have time to review? Thanks in advance.

**Comment by zhanglistar** [comment]
@alesapin Have time?

**Comment by gyfis** [comment]
@zhanglistar Hi! What's the status of this PR, can I ask why you closed it? Thanks!

**Pull request closed without merging**
