### PR TITLE
Fix integration tests

### PR DESCRIPTION
**Pull request by kssenii**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Review by KochetovNicolai — APPROVED** [review]
Thanks!

**Comment by KochetovNicolai** [comment]
What about adding timeout here?
https://github.com/ClickHouse/ClickHouse/blob/f0a7c6ec945c780645cab19e2657b5bc182d4133/tests/integration/test_postgresql_replica_database_engine/test.py#L122-L125

**Comment by kssenii** [comment]
> What about adding timeout here?

Yes, will be good, though strange that default pytest timeout didn't work.

**Comment by KochetovNicolai** [comment]
Checked integration tests locally, those which are changed are fixed.
Merging because in master is broken anyway

**Pull request merged**
