### PR TITLE
Ignore async_load_databases for ATTACH query

### PR DESCRIPTION
**Pull request by azat**
It is quite odd that when ATTACH finishes the tables may not be exists,
due to async_load_databases.

For server startup it makes total sense, but not for queries.

Plus, you can execute queries in parallel if you want to make it faster.

Note, that server startup does not uses this code, see loadMetadata.cpp.

### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Ignore async_load_databases for ATTACH query (previously it was possible for ATTACH to return before the tables had been attached)

Follow-up for: https://github.com/ClickHouse/ClickHouse/pull/49351 (cc @serxa )
Reverts: https://github.com/ClickHouse/ClickHouse/pull/65571 (cc @alexey-milovidov )

### CODE REVIEW

**Comment by robot-ch-test-poll4** [comment]
*This is an automated comment for commit 72deb412519c4d996d0c3aa9283d102d3bec0511 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/66240/72deb412519c4d996d0c3aa9283d102d3bec0511/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/b710af349958257e7cb9ab57235394d56968a96e/docs_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Review by serxa — APPROVED** [review]

**Comment by serxa** [comment]
cc @tavplubix JFYI. The new behaviour turned out to be a bit unexpected for ATTACH queries.

**Comment by serxa** [comment]
One thing that I'm worried about is that without ATTACH being async this new feature as a whole is hard to test.

**Review by tavplubix — APPROVED** [review]

**Comment by serxa** [comment]
Could you merge master into it please?

**Comment by azat** [comment]
@serxa Done

**Pull request merged**
