### PR TITLE
Disable hedged requests

### PR DESCRIPTION
**Pull request by alexey-milovidov**
Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Disable settings `use_hedged_requests` and `async_socket_for_remote` because there is an evidence that it may cause issues.

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
The settings won't be enabled until we recieve an answer from @KochetovNicolai here: https://github.com/ClickHouse/ClickHouse/issues/21167#issuecomment-820907631
and the potential issue found here #23257 will be investigated.

CC @KochetovNicolai @Avogar

**Comment by azat** [comment]
>and the potential issue found here #23257 will be investigated.

Note, that the test fails not because of async_socket_for_remote or use_hedged_requests.

And the only issue that I'm aware of for async_socket_for_remote right now is that it does not respect max_distributed_connection setting (because of the nature of Async)

**Comment by alexey-milovidov** [comment]
@azat Do you know what to answer here? https://github.com/ClickHouse/ClickHouse/issues/21167#issuecomment-820907631

**Comment by alexey-milovidov** [comment]
Isn't the issue fixed, can we close it?

**Comment by azat** [comment]
>Isn't the issue fixed, can we close it?

Let's wait for the answer in that issue.

**Comment by alexey-milovidov** [comment]
@azat But also you have noticed this:
```
too huge delay, look like another issue with async_socket_for_remote/use_hedged_requests
```

So, we should suspect another issue?

**Comment by alexey-milovidov** [comment]
No: https://github.com/ClickHouse/ClickHouse/pull/23257#issuecomment-822594963

**Pull request merged**
