### PR TITLE
feat: implement dynamic dispatch utilities with an example

### PR DESCRIPTION
**Pull request by SchrodingerZhu**
Signed-off-by: Schrodinger ZHU Yifan <i@zhuyi.fan>

This PR introduces a new sub library `microarchitecture` into `base`, providing:

- standalone facilitiesto detect hardware capabilities
- macros to dispatch function implementation to best-fit architecture

The library was designed to support both ifunc dispatch and runtime dispatch. However, considering the future develonebt plan and potential portability issues, ifunc strategy is not enabled on default.

### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Improve data loading performance.

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
Note: we are going to remove glibc and dynamic linker altogether very soon, that's why I'd not count on ifuncs.

**Comment by SchrodingerZhu** [comment]
> Note: we are going to remove glibc and dynamic loader altogether very soon, that's why I'd not count on ifuncs.

Oops. That is actually a good step towards portability. Another good thing is, it will enable products to be delivered with some images like `alpine`, which has a much smaller base environment, and hence, has a smaller chance of encountering security issue.

TiFlash also constantly experiences issues due to glibc's versioned symbols. But we are hesitated to move to MUSL because we do not have an avaiable analysis on potential perf regression caused by optimized routines. Actually, playing with https://github.com/ARM-software/optimized-routines, I can actually find a big performance difference on aarch64 platforms. Handling analytical workload, we may face a lot of memory manipulations.


May I ask if there is existing public analysis report on this? Thanks a lot!

**Comment by SchrodingerZhu** [comment]
I modified the code to also provide runtime dispatch if capable. The strategy is similar to `TargetSpecific` but it generates a unified entry point.

**Comment by SchrodingerZhu** [comment]
Just noticed that LTO is affected by LLVM's bug regarding ifunc. Will workaround it.
https://discourse.llvm.org/t/bug-56290-stop-assuming-that-aliasee-are-functions/63574

**Comment by SchrodingerZhu** [comment]
the errors are becoming strange. will come back later.

**Comment by alexey-milovidov** [comment]
I advise implementing dynamic dispatch manually, but not using ifuncs.

**Comment by SchrodingerZhu** [comment]
Performance of string related scanning improved on aarch64:
image

**Comment by alexey-milovidov** [comment]
Closing for obvious reasons (ifunc isn't supported on Musl).
Keep in mind that not merging this pull request prevented us from https://www.openwall.com/lists/oss-security/2024/03/29/4

**Pull request closed without merging**
