### PR TITLE
Cherry pick #62840 to 24.2: Fix crash in function `formatRow` with `JSON` format and HTTP  interface

### PR DESCRIPTION
**Pull request by robot-ch-test-poll2**
Original pull-request #62840

This pull-request is a first step of an automated backporting.
It contains changes similar to calling `git cherry-pick` locally.
If you intend to continue backporting the changes, then resolve all conflicts if any.
Otherwise, if you do not want to backport them, then just close this pull-request.

The check results does not matter at this step - you can safely ignore them.

### Note

This pull-request will be merged automatically. Please, **do not merge it manually** (but if you accidentally did, nothing bad will happen).

#### If the PR was manually reopened after being closed

If this PR is stuck (i.e. not automatically merged after one day), check https://github.com/ClickHouse/ClickHouse/pull/62840 for `pr-backports-created` *label* and delete it.

Manually merging will do nothing. The `pr-backports-created` *label* prevents the original PR https://github.com/ClickHouse/ClickHouse/pull/62840 from being processed.

#### If the conflicts were resolved in a wrong way

If this cherry-pick PR is completely screwed by a wrong conflicts resolution, and you want to recreate it:

- delete the `pr-cherrypick` label from the PR
- delete this branch from the repository

You also need to check the original PR https://github.com/ClickHouse/ClickHouse/pull/62840 for `pr-backports-created`, and delete if it's presented there

### CODE REVIEW

**Comment by robot-ch-test-poll3** [comment]
Dear @alexey-milovidov, @CurtizJ, the PR is not updated for 1d24h59m18s. Please, either resolve the conflicts, or close it to finish the backport process of #62840

**Comment by robot-ch-test-poll1** [comment]
Dear @alexey-milovidov, @CurtizJ, the PR is not updated for 1d24h0m17s. Please, either resolve the conflicts, or close it to finish the backport process of #62840

**Comment by robot-clickhouse** [comment]
Dear @alexey-milovidov, @CurtizJ, the PR is not updated for 1d24h59m51s. Please, either resolve the conflicts, or close it to finish the backport process of #62840

**Comment by robot-clickhouse-ci-2** [comment]
Dear @alexey-milovidov, @CurtizJ, the PR is not updated for 1d24h59m57s. Please, either resolve the conflicts, or close it to finish the backport process of #62840

**Comment by robot-ch-test-poll2** [comment]
Dear @alexey-milovidov, @CurtizJ, the PR is not updated for 1d25h0m8s. Please, either resolve the conflicts, or close it to finish the backport process of #62840

**Comment by robot-ch-test-poll3** [comment]
Dear @alexey-milovidov, @CurtizJ, the PR is not updated for 1d24h0m9s. Please, either resolve the conflicts, or close it to finish the backport process of #62840

**Comment by robot-clickhouse-ci-2** [comment]
Dear @alexey-milovidov, @CurtizJ, the PR is not updated for 1d24h58m4s. Please, either resolve the conflicts, or close it to finish the backport process of #62840

**Comment by robot-clickhouse-ci-2** [comment]
Dear @alexey-milovidov, @CurtizJ, the PR is not updated for 1d24h0m17s. Please, either resolve the conflicts, or close it to finish the backport process of #62840

**Comment by robot-clickhouse-ci-2** [comment]
Dear @alexey-milovidov, @CurtizJ, the PR is not updated for 1d24h3m42s. Please, either resolve the conflicts, or close it to finish the backport process of #62840

**Comment by robot-clickhouse** [comment]
Dear @alexey-milovidov, @CurtizJ, the PR is not updated for 1d24h57m48s. Please, either resolve the conflicts, or close it to finish the backport process of #62840

**Comment by robot-clickhouse-ci-1** [comment]
Dear @alexey-milovidov, @CurtizJ, the PR is not updated for 1d24h59m54s. Please, either resolve the conflicts, or close it to finish the backport process of #62840

**Comment by robot-clickhouse-ci-1** [comment]
Dear @alexey-milovidov, @CurtizJ, the PR is not updated for 1d25h1m8s. Please, either resolve the conflicts, or close it to finish the backport process of #62840

**Comment by robot-ch-test-poll** [comment]
Dear @alexey-milovidov, @CurtizJ, the PR is not updated for 1d24h0m0s. Please, either resolve the conflicts, or close it to finish the backport process of #62840

**Comment by robot-ch-test-poll** [comment]
Dear @alexey-milovidov, @CurtizJ, the PR is not updated for 1d24h59m49s. Please, either resolve the conflicts, or close it to finish the backport process of #62840

**Comment by robot-ch-test-poll** [comment]
Dear @alexey-milovidov, @CurtizJ, the PR is not updated for 1d24h0m34s. Please, either resolve the conflicts, or close it to finish the backport process of #62840

**Comment by robot-ch-test-poll** [comment]
Dear @alexey-milovidov, @CurtizJ, the PR is not updated for 1d24h2m52s. Please, either resolve the conflicts, or close it to finish the backport process of #62840

**Comment by robot-ch-test-poll4** [comment]
Dear @alexey-milovidov, @CurtizJ, the PR is not updated for 1d24h56m7s. Please, either resolve the conflicts, or close it to finish the backport process of #62840

**Comment by robot-clickhouse-ci-2** [comment]
Dear @alexey-milovidov, @CurtizJ, the PR is not updated for 1d25h1m19s. Please, either resolve the conflicts, or close it to finish the backport process of #62840

**Comment by robot-clickhouse-ci-1** [comment]
Dear @alexey-milovidov, @CurtizJ, the PR is not updated for 1d24h57m52s. Please, either resolve the conflicts, or close it to finish the backport process of #62840

**Comment by robot-clickhouse-ci-1** [comment]
Dear @alexey-milovidov, @CurtizJ, the PR is not updated for 1d24h59m31s. Please, either resolve the conflicts, or close it to finish the backport process of #62840

**Comment by robot-clickhouse-ci-1** [comment]
Dear @alexey-milovidov, @CurtizJ, the PR is not updated for 1d24h5m1s. Please, either resolve the conflicts, or close it to finish the backport process of #62840

**Comment by robot-clickhouse-ci-1** [comment]
Dear @alexey-milovidov, @CurtizJ, the PR is not updated for 1d24h59m16s. Please, either resolve the conflicts, or close it to finish the backport process of #62840

**Comment by robot-ch-test-poll3** [comment]
Dear @alexey-milovidov, @CurtizJ, the PR is not updated for 1d24h57m22s. Please, either resolve the conflicts, or close it to finish the backport process of #62840

**Comment by robot-ch-test-poll3** [comment]
Dear @alexey-milovidov, @CurtizJ, the PR is not updated for 1d24h57m0s. Please, either resolve the conflicts, or close it to finish the backport process of #62840

**Comment by robot-ch-test-poll2** [comment]
Dear @alexey-milovidov, @CurtizJ, the PR is not updated for 1d24h56m32s. Please, either resolve the conflicts, or close it to finish the backport process of #62840

**Comment by robot-ch-test-poll3** [comment]
Dear @alexey-milovidov, @CurtizJ, the PR is not updated for 1d24h1m24s. Please, either resolve the conflicts, or close it to finish the backport process of #62840

**Comment by robot-clickhouse-ci-1** [comment]
Dear @alexey-milovidov, @CurtizJ, the PR is not updated for 1d24h0m25s. Please, either resolve the conflicts, or close it to finish the backport process of #62840

**Comment by robot-clickhouse-ci-1** [comment]
Dear @alexey-milovidov, @CurtizJ, the PR is not updated for 1d24h1m23s. Please, either resolve the conflicts, or close it to finish the backport process of #62840

**Comment by robot-ch-test-poll3** [comment]
Dear @alexey-milovidov, @CurtizJ, the PR is not updated for 1d24h0m25s. Please, either resolve the conflicts, or close it to finish the backport process of #62840

**Comment by robot-ch-test-poll2** [comment]
Dear @alexey-milovidov, @CurtizJ, the PR is not updated for 1d24h57m43s. Please, either resolve the conflicts, or close it to finish the backport process of #62840

**Comment by robot-ch-test-poll2** [comment]
Dear @alexey-milovidov, @CurtizJ, the PR is not updated for 1d24h2m5s. Please, either resolve the conflicts, or close it to finish the backport process of #62840

**Comment by robot-ch-test-poll2** [comment]
Dear @alexey-milovidov, @CurtizJ, the PR is not updated for 1d24h57m57s. Please, either resolve the conflicts, or close it to finish the backport process of #62840

**Comment by robot-ch-test-poll** [comment]
Dear @alexey-milovidov, @CurtizJ, the PR is not updated for 1d24h0m39s. Please, either resolve the conflicts, or close it to finish the backport process of #62840

**Pull request closed without merging**
