### PR TITLE
Tune the concurrency settings

### PR DESCRIPTION
**Pull request by alexey-milovidov**
### Changelog category (leave one):
- Performance Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Increase the default value of `max_concurrent_queries` from 100 to 1000. This makes sense when there is a large number of connecting clients, which are slowly sending or receiving data, so the server is not limited by CPU, or when the number of CPU cores is larger than 100. Also, enable the concurrency control by default, and set the desired number of query processing threads in total as twice the number of CPU cores. It improves performance in scenarios with a very large number of concurrent queries.

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
TODO:
- [ ] `compatibility` setting;
- [ ] settings randomization.

**Comment by nickitat** [comment]
I'm afraid there will be many flaky tests after this change. maybe we better to set old values in test configs?

**Comment by alexey-milovidov** [comment]
It makes sense for the new config to be thoroughly tested... I hope we will deal with flaky tests.

**Comment by alexey-milovidov** [comment]
We need to make concurrency settings tuneable on a per-query basis.

**Comment by alexey-milovidov** [comment]
Depends on #49618

**Comment by robot-clickhouse** [comment]
This is an automated comment for commit 231d0f684a9f483bee526af1e6319f3bd16b343a with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/46927/231d0f684a9f483bee526af1e6319f3bd16b343a/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Comment by alexey-milovidov** [comment]
This PR looks ready.

The only test that failed on Aug 29th was also flaky long time ago: https://play.clickhouse.com/play?user=play#U0VMRUNUIGNoZWNrX3N0YXJ0X3RpbWUsIGNoZWNrX25hbWUsIHRlc3RfbmFtZSwgcmVwb3J0X3VybApGUk9NIGNoZWNrcwpXSEVSRSBjaGVja19zdGFydF90aW1lID49IG5vdygpIC0gSU5URVJWQUwgMTIgTU9OVEgKICAgIEFORCBwdWxsX3JlcXVlc3RfbnVtYmVyID0gMAogICAgQU5EIHRlc3Rfc3RhdHVzICE9ICdTS0lQUEVEJwogICAgQU5EIHRlc3Rfc3RhdHVzIExJS0UgJ0YlJwogICAgQU5EIGNoZWNrX3N0YXR1cyAhPSAnc3VjY2VzcycKICAgIEFORCBwb3NpdGlvbih0ZXN0X25hbWUsICdjb25jdXJyZW50X3RocmVhZHMnKSA+IDAKT1JERVIgQlkgY2hlY2tfc3RhcnRfdGltZQ==

**Pull request merged**
