### PR TITLE
Change the default for wait_dictionaries_load_at_startup to true

### PR DESCRIPTION
**Pull request by vitlibar**
### Changelog category:
- Improvement

### Changelog entry:
Change the default for `wait_dictionaries_load_at_startup` to true, and use this setting only if `dictionaries_lazy_load` is false.

This PR is an improvement after https://github.com/ClickHouse/ClickHouse/pull/56782 to make `dictionaries_lazy_load` work in more obvious way.

### CODE REVIEW

**Comment by robot-ch-test-poll** [comment]
*This is an automated comment for commit 3fbcc5acfa697b79ae46535883144a58b8dcaab9 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/57133/3fbcc5acfa697b79ae46535883144a58b8dcaab9/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td><a href="https://github.com/ClickHouse/ClickHouse/actions/runs/6963846738">✅ success</a></td></tr>
<tbody>
</table>
</details>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/57133/3fbcc5acfa697b79ae46535883144a58b8dcaab9/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Review by vdimir — APPROVED** [review]
Makes sense.
And since we have `dictionaries_lazy_load = true` by default, the server's default behavior remains unchanged, right?

**Comment by vitlibar** [comment]
> And since we have `dictionaries_lazy_load = true` by default, the server's default behavior remains unchanged, right?

yes

**Comment by vitlibar** [comment]
Flaky tests:
- [02152_http_external_tables_memory_tracking](https://s3.amazonaws.com/clickhouse-test-reports/57133/5f461ff7805e1ab7a94c73925709181ab08c994a/stateless_tests__debug__[3_5].html) - see [issue 53215](https://github.com/ClickHouse/ClickHouse/issues/53215)

**Pull request merged**
