### PR TITLE
Fix a bug with projections and the aggregate_functions_null_for_empty setting during insertion.

### PR DESCRIPTION
**Pull request by amosbird**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix a bug with projections and the `aggregate_functions_null_for_empty` setting during insertion. This is an addition to #42198 and #49873. The bug was found by fuzzer in #56666. This PR also fix potential issues with projections and the `transform_null_in` setting.

### CODE REVIEW

**Review by KochetovNicolai — APPROVED** [review]

**Comment by KochetovNicolai** [comment]
Probably there is some assert with `Stateless tests (debug)`

**Comment by amosbird** [comment]
> Probably there is some assert with Stateless tests (debug)

I've checked all 5 error logs. All of them exit normally. Let's see if rebasing with master will help.

**Comment by amosbird** [comment]
> It's detecting issues related to the new test

Yeah, fuzzer just found another projection incompatible setting: `legacy_column_name_of_tuple_literal`

**Comment by amosbird** [comment]
> AST fuzzer (msan)

https://github.com/ClickHouse/ClickHouse/issues/57465

> Integration tests (asan) [4/4] — fail: 1, passed: 665
> Integration tests (asan, analyzer) [6/6] — fail: 1, passed: 493
> Integration tests (release) [4/4] — fail: 1, passed: 666
> Integration tests (tsan) [6/6] — fail: 1, passed: 495

Something went wrong in test `test_cross_replication` and `test_consistent_parts_after_clone_replica`. It should be unrelated to current PR.

**Comment by amosbird** [comment]
> Performance Comparison [3/4] — 2 errors, 3 unstable

https://github.com/ClickHouse/ClickHouse/issues/58593

> Stateless tests (ubsan) [2/2] — Tests are not finished, fail: 9, passed: 619, skipped: 6

https://github.com/ClickHouse/ClickHouse/issues/56037

**Pull request merged**
