### PR TITLE
Fix ZstdDeflatingWriteBuffer truncating the output sometimes

### LINKED ISSUE #53028: query zstd parquet file error
clickhouse-local version: ClickHouse local version 23.7.1.2470 (official build)
mysql: 8.0.28

```sql
CREATE TABLE archive_test (
  id bigint unsigned NOT NULL,
  c1 bigint NOT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC;

INSERT INTO `archive_test` (`id`, `c1`)
VALUES
	(1, 11),
	(2, 12),
	(3, 13);
```

export data into parquet file in s3 successfully.
```
# clickhouse-local -q "SET output_format_parquet_row_group_size = 10240, output_format_parquet_compression_method='zstd'; INSERT INTO FUNCTION s3('http://bucket_name.oss_addr/mysql_archive.parquet', 'ak', 'sk') select id, c1 from mysql('mysql_hostname:3306','dbtest','archive_test','username','password')"
```
query from the parquet file。
```
# clickhouse-local -q "select count(*) FROM s3('http://bucket_name.oss_addr/mysql_archive.parquet', 'ak', 'sk')"
```
I get the error as below. but it's no problem when use output_format_parquet_compression_method=lz4. is it a bug？
```
Code: 33. DB::ParsingException: Error while reading Parquet data: IOError: ZSTD decompression failed: Restored data doesn't match checksum: While executing ParquetBlockInputFormat: While executing OSS. (CANNOT_READ_ALL_DATA)
```

### PR DESCRIPTION
**Pull request by al13n321**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fixed `output_format_parquet_compression_method='zstd'` producing invalid Parquet files sometimes. In older versions, use setting `output_format_parquet_use_custom_encoder = 0` as a workaround.

Closes https://github.com/ClickHouse/ClickHouse/issues/53028

`ZstdDeflatingWriteBuffer::finalizeBefore()` was calling `ZSTD_compressStream2()` once instead of in a loop.

Along the way, deduplicated nearly identical code between `nextImpl()` and `finalizeBefore()` in `ZstdDeflatingWriteBuffer` `ZstdDeflatingAppendableWriteBuffer`. Merging nearly identical `ZstdDeflatingWriteBuffer` and `ZstdDeflatingAppendableWriteBuffer` into one class is left as an exercise to the reader.

### CODE REVIEW

**Comment by robot-ch-test-poll** [comment]
This is an automated comment for commit 9a128fa5544cc0cf411ee367d28a564a5f7f8b98 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/53064/9a128fa5544cc0cf411ee367d28a564a5f7f8b98/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Review by alexey-milovidov — APPROVED** [review]

**Comment by antonio2368** [comment]
I'm afraid this breaks Keeper and writing to compressed log files

**Comment by antonio2368** [comment]
@al13n321 I'm going to revert `src/IO/ZstdDeflatingAppendableWriteBuffer.cpp` files.
It should be only used in Keeper and it's really brittle implementation you proved yourself now because it's not easy to make appendable ZSTD write buffer work.

**Comment by tavplubix** [comment]
Yes, it breaks Keeper and Stress tests: https://github.com/ClickHouse/ClickHouse/pull/53090#issuecomment-1667527071 
I think it's okay to revert it from master now (to fix Stress tests) and freeze 22.7 until this PR is resubmitted or reverted from 22.7 as well

**Pull request merged**
