### PR TITLE
[RFC] Fix rare intersecting parts in case of errors during handling broken parts

### LINKED ISSUE #44845: intersecting parts in stress test
https://s3.amazonaws.com/clickhouse-test-reports/44657/80ef5326d29fec05ba94837449b9e1658eb13fa7/stress_test__ubsan_.html
```
/var/log/clickhouse-server/clickhouse-server.err.log:2022.12.31 05:13:24.019988 [ 1760 ] {} <Fatal> : Logical error: 'Part all_0_2_1 intersects previous part all_0_1_1. It is a bug or a result of manual intervention in the ZooKeeper data.'.
/var/log/clickhouse-server/clickhouse-server.err.log:2022.12.31 05:14:03.216825 [ 186148 ] {} <Fatal> BaseDaemon: ########################################
/var/log/clickhouse-server/clickhouse-server.err.log:2022.12.31 05:14:03.216856 [ 186148 ] {} <Fatal> BaseDaemon: (version 22.13.1.1, build id: A85C3FB51DBE03E7A40B185D67DC8491E5948CE5) (from thread 1760) (no query) Received signal Aborted (6)
/var/log/clickhouse-server/clickhouse-server.err.log:2022.12.31 05:14:03.216880 [ 186148 ] {} <Fatal> BaseDaemon: 
/var/log/clickhouse-server/clickhouse-server.err.log:2022.12.31 05:14:03.216960 [ 186148 ] {} <Fatal> BaseDaemon: Stack trace: 0x7f0feea9100b 0x7f0feea70859 0x216379c3 0x21637ccf 0x1751903f 0x2e4abdce 0x2e4ab817 0x2e8c7383 0x2e8d0e6b 0x2e1a5893 0x2bf6caa1 0x2bf6ecd7 0x2bf6f6ed 0x2174083a 0x21744284 0x7f0feec48609 0x7f0feeb6d133
/var/log/clickhouse-server/clickhouse-server.err.log:2022.12.31 05:14:03.217004 [ 186148 ] {} <Fatal> BaseDaemon: 3. raise @ 0x7f0feea9100b in ?
/var/log/clickhouse-server/clickhouse-server.err.log:2022.12.31 05:14:03.217036 [ 186148 ] {} <Fatal> BaseDaemon: 4. abort @ 0x7f0feea70859 in ?
/var/log/clickhouse-server/clickhouse-server.err.log:2022.12.31 05:14:03.251611 [ 186148 ] {} <Fatal> BaseDaemon: 5. ./build_docker/../src/Common/Exception.cpp:48: DB::abortOnFailedAssertion(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) @ 0x216379c3 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2022.12.31 05:14:03.282508 [ 186148 ] {} <Fatal> BaseDaemon: 6. ./build_docker/../src/Common/Exception.cpp:78: DB::Exception::Exception(DB::Exception::MessageMasked const&, int, bool) @ 0x21637ccf in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2022.12.31 05:14:04.748306 [ 186148 ] {} <Fatal> BaseDaemon: 7. DB::Exception::Exception<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>(int, fmt::v8::basic_format_string<char, fmt::v8::type_identity<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>::type, fmt::v8::type_identity<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>::type>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>&&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>&&) @ 0x1751903f in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2022.12.31 05:14:04.762307 [ 186148 ] {} <Fatal> BaseDaemon: 8. ./build_docker/../src/Storages/MergeTree/ActiveDataPartSet.cpp:0: DB::ActiveDataPartSet::add(DB::MergeTreePartInfo const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>>*) @ 0x2e4abdce in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2022.12.31 05:14:04.776147 [ 186148 ] {} <Fatal> BaseDaemon: 9. ./build_docker/../src/Storages/MergeTree/ActiveDataPartSet.cpp:0: DB::ActiveDataPartSet::add(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>>*) @ 0x2e4ab817 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2022.12.31 05:14:04.940256 [ 186148 ] {} <Fatal> BaseDaemon: 10. ./build_docker/../src/Storages/MergeTree/ReplicatedMergeTreeQueue.cpp:0: DB::ReplicatedMergeTreeQueue::insertUnlocked(std::__1::shared_ptr<DB::ReplicatedMergeTreeLogEntry> const&, std::__1::optional<long>&, std::__1::lock_guard<std::__1::mutex>&) @ 0x2e8c7383 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2022.12.31 05:14:05.094501 [ 186148 ] {} <Fatal> BaseDaemon: 11.1. inlined from ./build_docker/../contrib/llvm-project/libcxx/include/string:1499: std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>::__is_long[abi:v15000]() const
/var/log/clickhouse-server/clickhouse-server.err.log:2022.12.31 05:14:05.104899 [ 186148 ] {} <Fatal> BaseDaemon: 11.2. inlined from ./build_docker/../contrib/llvm-project/libcxx/include/string:2333: ~basic_string
/var/log/clickhouse-server/clickhouse-server.err.log:2022.12.31 05:14:05.104959 [ 186148 ] {} <Fatal> BaseDaemon: 11. ./build_docker/../src/Storages/MergeTree/ReplicatedMergeTreeQueue.cpp:706: DB::ReplicatedMergeTreeQueue::pullLogsToQueue(std::__1::shared_ptr<zkutil::ZooKeeper>, std::__1::function<void (Coordination::WatchResponse const&)>, DB::ReplicatedMergeTreeQueue::PullLogsReason) @ 0x2e8d0e6b in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2022.12.31 05:14:05.436732 [ 186148 ] {} <Fatal> BaseDaemon: 12.1. inlined from ./build_docker/../contrib/llvm-project/libcxx/include/__functional/function.h:818: ~__policy_func
/var/log/clickhouse-server/clickhouse-server.err.log:2022.12.31 05:14:05.487923 [ 186148 ] {} <Fatal> BaseDaemon: 12.2. inlined from ./build_docker/../contrib/llvm-project/libcxx/include/__functional/function.h:1174: ~function
/var/log/clickhouse-server/clickhouse-server.err.log:2022.12.31 05:14:05.487964 [ 186148 ] {} <Fatal> BaseDaemon: 12. ./build_docker/../src/Storages/StorageReplicatedMergeTree.cpp:2937: DB::StorageReplicatedMergeTree::queueUpdatingTask() @ 0x2e1a5893 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2022.12.31 05:14:05.506140 [ 186148 ] {} <Fatal> BaseDaemon: 13. ./build_docker/../contrib/llvm-project/libcxx/include/__functional/function.h:0: DB::BackgroundSchedulePoolTaskInfo::execute() @ 0x2bf6caa1 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2022.12.31 05:14:05.541760 [ 186148 ] {} <Fatal> BaseDaemon: 14. ./build_docker/../src/Core/BackgroundSchedulePool.cpp:0: DB::BackgroundSchedulePool::threadFunction() @ 0x2bf6ecd7 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2022.12.31 05:14:05.581988 [ 186148 ] {} <Fatal> BaseDaemon: 15.1. inlined from ./build_docker/../src/Core/BackgroundSchedulePool.cpp:0: operator()
/var/log/clickhouse-server/clickhouse-server.err.log:2022.12.31 05:14:05.582037 [ 186148 ] {} <Fatal> BaseDaemon: 15.2. inlined from ./build_docker/../contrib/llvm-project/libcxx/include/__functional/invoke.h:394: decltype(std::declval<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_2>()()) std::__1::__invoke[abi:v15000]<ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_2>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_2&&)::'lambda'()&>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_2&&)
/var/log/clickhouse-server/clickhouse-server.err.log:2022.12.31 05:14:05.582074 [ 186148 ] {} <Fatal> BaseDaemon: 15.3. inlined from ./build_docker/../contrib/llvm-project/libcxx/include/__functional/invoke.h:479: void std::__1::__invoke_void_return_wrapper<void, true>::__call<ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_2>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_2&&)::'lambda'()&>(ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_2>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_2&&)::'lambda'()&)
/var/log/clickhouse-server/clickhouse-server.err.log:2022.12.31 05:14:05.582098 [ 186148 ] {} <Fatal> BaseDaemon: 15.4. inlined from ./build_docker/../contrib/llvm-project/libcxx/include/__functional/function.h:235: std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_2>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_2&&)::'lambda'(), void ()>::operator()[abi:v15000]()
/var/log/clickhouse-server/clickhouse-server.err.log:2022.12.31 05:14:05.582114 [ 186148 ] {} <Fatal> BaseDaemon: 15. ./build_docker/../contrib/llvm-project/libcxx/include/__functional/function.h:716: void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_2>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_2&&)::'lambda'(), void ()>>(std::__1::__function::__policy_storage const*) @ 0x2bf6f6ed in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2022.12.31 05:14:05.598428 [ 186148 ] {} <Fatal> BaseDaemon: 16.1. inlined from ./build_docker/../base/base/strong_typedef.h:23: StrongTypedef<std::__1::integral_constant<bool, true> >
/var/log/clickhouse-server/clickhouse-server.err.log:2022.12.31 05:14:05.729508 [ 186148 ] {} <Fatal> BaseDaemon: 16.2. inlined from ./build_docker/../src/Common/OpenTelemetryTraceContext.h:39: DB::OpenTelemetry::Span::isTraceEnabled() const
/var/log/clickhouse-server/clickhouse-server.err.log:2022.12.31 05:14:05.730752 [ 186148 ] {} <Fatal> BaseDaemon: 16. ./build_docker/../src/Common/ThreadPool.cpp:297: ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x2174083a in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2022.12.31 05:14:05.752771 [ 186148 ] {} <Fatal> BaseDaemon: 17. ./build_docker/../src/Common/ThreadPool.cpp:0: void* std::__1::__thread_proxy[abi:v15000]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()>>(void*) @ 0x21744284 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2022.12.31 05:14:05.794695 [ 186148 ] {} <Fatal> BaseDaemon: 18. ? @ 0x7f0feec48609 in ?
/var/log/clickhouse-server/clickhouse-server.err.log:2022.12.31 05:14:05.794808 [ 186148 ] {} <Fatal> BaseDaemon: 19. clone @ 0x7f0feeb6d133 in ?
```

CC: @tavplubix

### PR DESCRIPTION
**Pull request by azat**
_I came across similar issues (`Intersecting parts`) in production, hence decided to dig into the problem_

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in official stable or prestable release)

### Documentation entry for user-facing changes
Fix rare intersecting parts in case of errors during handling broken parts

Before this patch it was possible that session expired error during handling broken parts could lead to intersecting parts.

Here is what CI had been found [1] (with some additional clarifications in the comments):

    # Here all_0_1_1 is a broken part that had been created by 02369_lost_part_intersecting_merges
    2022.12.31 05:13:22.687083 [ 1775 ] {} <Trace> test_5yo19yin.rmt1 (ReplicatedMergeTreePartCheckThread): Part all_0_1_1 in zookeeper: true, locally: true
    2022.12.31 05:13:22.801196 [ 1775 ] {} <Error> test_5yo19yin.rmt1 (ReplicatedMergeTreePartCheckThread): Part all_0_1_1 looks broken. Removing it and will try to fetch.
    2022.12.31 05:13:22.801230 [ 1775 ] {} <Information> test_5yo19yin.rmt1: Cloning part all_0_1_1 to broken_all_0_1_1 and making it obsolete.
    2022.12.31 05:13:22.805492 [ 1775 ] {} <Test> VersionMetadata: Trying to lock removal_tid by (1, 1, 00000000-0000-0000-0000-000000000000), table: test_5yo19yin.rmt1, part: all_0_1_1
    2022.12.31 05:13:22.805562 [ 1775 ] {} <Warning> test_5yo19yin.rmt1 (ReplicatedMergeTreePartCheckThread): Checking if anyone has a part all_0_1_1 or covering part.
    2022.12.31 05:13:22.886463 [ 1775 ] {} <Error> test_5yo19yin.rmt1 (ReplicatedMergeTreePartCheckThread): void DB::ReplicatedMergeTreePartCheckThread::run(): Code: 999. Coordination::Exception: Session expired, path: Session expired. (KEEPER_EXCEPTION), Stack trace (when copying this message, always include the lines below):
    ..
    # Some error happened during handling this broken part, normal log:
    # 2023.02.28 19:54:18.168792 [ 2912 ] {} <Information> test_tc42qyhv.rmt1 (ReplicatedMergeTreePartCheckThread): Found parts with the same min block and with the same max block as the missing part all_0_1_1 on replica 2. Hoping that it will eventually appear as a result of a merge. Parts: all_0_0_0, all_1_1_0
    # 2023.02.28 19:54:18.168801 [ 2912 ] {} <Warning> test_tc42qyhv.rmt1 (ReplicatedMergeTreePartCheckThread): Part all_0_1_1 exists in ZooKeeper but not locally and not found on other replica. Removing it from ZooKeeper.
    # 2023.02.28 19:54:18.168811 [ 2912 ] {} <Debug> test_tc42qyhv.rmt1 (ReplicatedMergeTreeQueue): Removed 0 entries from queue. Waiting for 0 entries that are currently executing.
    # 2023.02.28 19:54:18.169625 [ 2912 ] {} <Trace> test_tc42qyhv.rmt1 (ReplicatedMergeTreeQueue): Insert entry queue-0000000003 to queue with type GET_PART with virtual parts [all_0_1_1]

    # and after ATTACH:
    2022.12.31 05:13:22.926378 [ 1821 ] {} <Trace> test_5yo19yin.rmt1 (ReplicatedMergeTreeQueue): Initializing parts in queue
    2022.12.31 05:13:22.926554 [ 1821 ] {} <Test> test_5yo19yin.rmt1 (ReplicatedMergeTreeQueue): Adding part all_0_0_0 to current and virtual parts
    2022.12.31 05:13:22.926577 [ 1821 ] {} <Test> test_5yo19yin.rmt1 (ReplicatedMergeTreeQueue): Adding part all_1_1_0 to current and virtual parts
    2022.12.31 05:13:22.926600 [ 1821 ] {} <Test> test_5yo19yin.rmt1 (ReplicatedMergeTreeQueue): Adding part all_0_1_1 to current and virtual parts # Here we still have part
    ...
    # But here it will been removed from ZooKeeper and no this replica nothing knows about this part and can schedule an incorrect merge, i.e. all_0_2_1
    2022.12.31 05:13:22.929130 [ 1732 ] {} <Trace> test_5yo19yin.rmt1: Found 1 old parts to remove. Parts: [all_0_1_1]
    2022.12.31 05:13:22.936244 [ 1732 ] {} <Debug> test_5yo19yin.rmt1: Removing 1 old parts from ZooKeeper
    ...
    2022.12.31 05:13:24.013627 [ 8170 ] {773f11e2-6c61-4ea2-9955-47fa14e67cc3} <Trace> test_5yo19yin.rmt1: Created log entry /test/02369/02369_lost_part_intersecting_merges_test_5yo19yin/test_5yo19yin/log/log-0000000004 for merge all_0_2_1
    2022.12.31 05:14:03.325437 [ 1665 ] {test_5yo19yin.rmt1::all_0_2_1} <Trace> test_5yo19yin.rmt1 (MergerMutator): Merged 3 parts: [all_0_0_0, all_2_2_0] -> [] # WHY?
    ...
    2022.12.31 05:13:24.019988 [ 1760 ] {} <Fatal> : Logical error: 'Part all_0_2_1 intersects previous part all_0_1_1. It is a bug or a result of manual intervention in the ZooKeeper data.'.

  [1]: https://s3.amazonaws.com/clickhouse-test-reports/44657/80ef5326d29fec05ba94837449b9e1658eb13fa7/stress_test__ubsan_.html

Fixes: #44845
Cc: @tavplubix

### CODE REVIEW

**Comment by tavplubix** [comment]
Thank you for taking a look and trying to fix this, I really appreciate that! However, this patch will not solve the problem. 

One of the fundamental invariants of `ReplicatedMergeTreeQueue` is that all parts must be present as "current parts" in the list of parts in zk or as "virtual parts" in entries in the replication queue in zk. And the problem is that the invariant was violated: the part was removed from the list, see https://pastila.nl/?007451bf/fccf78bf5aa4ff89fe5cecfaa9f59fa2. The loop that you added check only parts from the list: https://github.com/ClickHouse/ClickHouse/blob/0e0a24234aa3409bb7799cc9a4b7a72bb006a923/src/Storages/MergeTree/ReplicatedMergeTreeQueue.cpp#L62 https://github.com/ClickHouse/ClickHouse/blob/0e0a24234aa3409bb7799cc9a4b7a72bb006a923/src/Storages/MergeTree/ReplicatedMergeTreeQueue.cpp#L78 so it will not find the part and will not enqueue a fetch.

Potential fixes that could help:
 - Do not mark a broken part as Outdated until a fetch is enqueued
 - Set some "flag" when marking a broken part as Outdated and do not remove it from zk (it can be removed from zk through `removePartAndEnqueueFetch` only)

**Comment by azat** [comment]
Hm, but AFAICS the part had not been removed from the queue yet, so here it fails:

```
2022.12.31 05:13:22.886463 [ 1775 ] {} <Error> test_5yo19yin.rmt1 (ReplicatedMergeTreePartCheckThread): void DB::ReplicatedMergeTreePartCheckThread::run(): Code: 999. Coordination::Exception: Session expired, path: Session expired. (KEEPER_EXCEPTION), Stack trace (when copying this message, always include the lines below): 

3Common/ZooKeeper/IKeeper.cpp:0: Coordination::Exception::Exception() @ 0x2f776778 in /usr/bin/clickhouse
...
9.  Common/ZooKeeper/ZooKeeper.cpp:232: zkutil::ZooKeeper::getChildren() 
10. Storages/MergeTree/ReplicatedMergeTreePartCheckThread.cpp:0: DB::ReplicatedMergeTreePartCheckThread::searchForMissingPartOnOtherReplicas() 
11. Storages/MergeTree/ReplicatedMergeTreePartCheckThread.cpp:0: DB::ReplicatedMergeTreePartCheckThread::searchForMissingPartAndFetchIfPossible() 
12. Storages/MergeTree/ReplicatedMergeTreePartCheckThread.cpp:0: DB::ReplicatedMergeTreePartCheckThread::checkPart() 
```

And this should be this place in the code -https://github.com/ClickHouse/ClickHouse/blob/00c05f7f8b8f11bcb9c11e54c9bec6b77932933f/src/Storages/MergeTree/ReplicatedMergeTreePartCheckThread.cpp#L224

And `removePartAndEnqueueFetch` had not been called yet, and `removePartAndEnqueueFetch` do not simply remove the part, but enqueue fetch + remove part in a single transaction, what did I miss?

**Comment by tavplubix** [comment]
>  the part had not been removed from the queue yet

It does not matter if it was removed from the check queue or not. The issue is that the part was removed from the list of parts in zk.

> And removePartAndEnqueueFetch had not been called yet

Yes. But `outdateBrokenPartAndCloneToDetached` was.

> and removePartAndEnqueueFetch do not simply remove the part, but enqueue fetch + remove part in a single transaction

Yes, `removePartAndEnqueueFetch` works correctly.

See my comments in https://pastila.nl/?007451bf/fccf78bf5aa4ff89fe5cecfaa9f59fa2:
 - The problem is that all_0_1_1 was marked as Outdated ("Cloning part all_0_1_1 to broken_all_0_1_1 and making it obsolete")
 - After that it was able to remove the part from zk during usual parts cleanup

**Comment by azat** [comment]
>Yes. But outdateBrokenPartAndCloneToDetached was.

Oh, forgot about cleanup, now I understood, thanks for clarifications! (even though this patch may help with that particular problem it will not help in all cases)

**Comment by azat** [comment]
>Do not mark a broken part as Outdated until a fetch is enqueued

Looks like this can break some code, since you will have active part and a GET_PART for it at the same time.

**Comment by tavplubix** [comment]
I've implemented the fix in a bit simpler way and added another test: https://github.com/ClickHouse/ClickHouse/pull/47659

**Pull request closed without merging**
