### PR TITLE
Add `max_parts_to_merge_at_once` setting

### LINKED ISSUE #1820: Lowering the default for maximum of parts to be merged at once, or make it configurable
We have this case recently

```
:) select num_parts, formatReadableSize(total_size_bytes_compressed) from system.merges where num_parts > 100;

SELECT
    num_parts,
    formatReadableSize(total_size_bytes_compressed)
FROM system.merges
WHERE num_parts > 100

┌─num_parts─┬─formatReadableSize(total_size_bytes_compressed)─┐
│      1001 │ 49.31 GiB                                       │
└───────────┴─────────────────────────────────────────────────┘
```

where we hits the hard-coded limit of number of parts being merged at once. Merging 1000 parts at once is rarely a good idea though. Can we lower this, or make it configurable somehow ?

### PR DESCRIPTION
**Pull request by alesapin**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Add merge tree setting `max_parts_to_merge_at_once` which limits the number of parts that can be merged in the background at once. Doesn't affect `OPTIMIZE FINAL` query. Fixes #1820.

### CODE REVIEW

**Comment by alesapin** [comment]
@Mergifyio update

**Review by kitaisreal — APPROVED** [review]

**Comment by alesapin** [comment]
Flaky test....

**Comment by alesapin** [comment]
```01882_check_max_parts_to_merge_at_once:                                 [ FAIL ] 39.49 sec. - Test runs too long (> 30s). Make it faster.```
yarrrr! The test is not `long`, but when you run 100 of them concurrently it can wait for the background pool.

**Comment by alesapin** [comment]
No related failures

**Pull request merged**
