### PR TITLE
CREATE TABLE AS copy PRIMARY KEY, ORDER BY, and similar clauses.

### LINKED ISSUE #63155: CREATE TABLE AS should copy PRIMARY KEY, ORDER BY, and similar clauses.
**Use case**

```
CREATE TABLE hits2 AS hits ENGINE = MergeTree SETTINGS enable_block_number_column = 1, enable_block_offset_column = 1;
```

```
Code: 36. DB::Exception: Received from localhost:9000. DB::Exception: You must provide an ORDER BY or PRIMARY KEY expression in the table definition. If you don't want this table to be sorted, use ORDER BY/PRIMARY KEY (). Otherwise, you can use the setting 'create_table_empty_primary_key_by_default' to automatically add an empty primary key to the table definition. (BAD_ARGUMENTS)
```

### PR DESCRIPTION
**Pull request by sakulali**
Resolves https://github.com/ClickHouse/ClickHouse/issues/63155

### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
CREATE TABLE AS copy PRIMARY KEY, ORDER BY, and similar clauses. Now it supports only for MergeTree family of table engines.

### CODE REVIEW

**Comment by robot-ch-test-poll3** [comment]
*This is an automated comment for commit aad57f438cf4ab5d09c0f02b8946f54e44e7d8f8 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/69076/aad57f438cf4ab5d09c0f02b8946f54e44e7d8f8/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/a7d0a5991e5e0e0be9bce7bc7ac9e1de5f376903/docs_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Review by jsc0218 — APPROVED** [review]

**Comment by sakulali** [comment]
Hi @jsc0218, thank you very much for helping with the review :). I ran the failed CI test in my local environment and did not encounter errors. It seems that the failure is not related to this PR. Do you think we should rerun the CI test?

**Comment by jsc0218** [comment]
@sakulali thanks for contributing, the failure should be unrelated. I just restarted the test. If it still fails, can try merge with the latest master then.

**Comment by sakulali** [comment]
> > the failure should be unrelated
> 
> Nope, the failure is probably very much related:
> 
> ```
> Traceback (most recent call last):
>   File "/workspace/right/scripts/perf.py", line 312, in <module>
>     t.join()
>   File "/workspace/right/scripts/perf.py", line 44, in join
>     raise self.run_exception[1]
>   File "/workspace/right/scripts/perf.py", line 37, in run
>     super().run()
>   File "/usr/lib/python3.10/threading.py", line 953, in run
>     self._target(*self._args, **self._kwargs)
>   File "/workspace/right/scripts/perf.py", line 300, in do_create
>     connection.execute(q)
>   File "/usr/local/lib/python3.10/dist-packages/clickhouse_driver/client.py", line 382, in execute
>     rv = self.process_ordinary_query(
>   File "/usr/local/lib/python3.10/dist-packages/clickhouse_driver/client.py", line 580, in process_ordinary_query
>     return self.receive_result(with_column_types=with_column_types,
>   File "/usr/local/lib/python3.10/dist-packages/clickhouse_driver/client.py", line 213, in receive_result
>     return result.get_result()
>   File "/usr/local/lib/python3.10/dist-packages/clickhouse_driver/result.py", line 50, in get_result
>     for packet in self.packet_generator:
>   File "/usr/local/lib/python3.10/dist-packages/clickhouse_driver/client.py", line 229, in packet_generator
>     packet = self.receive_packet()
>   File "/usr/local/lib/python3.10/dist-packages/clickhouse_driver/client.py", line 246, in receive_packet
>     raise packet.exception
> clickhouse_driver.errors.ServerException: Code: 42.
> DB::Exception: With extended storage definition syntax storage MergeTree requires no parameters
> 
> Syntax for the MergeTree table engine:
> 
> CREATE TABLE [IF NOT EXISTS] [db.]table_name [ON CLUSTER cluster]
> (
>     name1 [type1] [DEFAULT|MATERIALIZED|ALIAS expr1] [TTL expr1],
>     name2 [type2] [DEFAULT|MATERIALIZED|ALIAS expr2] [TTL expr2],
>     ...
>     INDEX index_name1 expr1 TYPE type1(...) [GRANULARITY value1],
>     INDEX index_name2 expr2 TYPE type2(...) [GRANULARITY value2]
> ) ENGINE = MergeTree()
> ORDER BY expr
> [PARTITION BY expr]
> [PRIMARY KEY expr]
> [SAMPLE BY expr]
> [TTL expr [DELETE|TO DISK 'xxx'|TO VOLUME 'xxx'], ...]
> [SETTINGS name=value, ...]
> [COMMENT 'comment']
> 
> See details in documentation: https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/mergetree/. Other engines of the family support different syntax, see details in the corresponding documentation topics.
> 
> If you use the Replicated version of engines, see https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/replication/.
> . Stack trace:
> 
> 0. ./build_docker/./src/Common/Exception.cpp:111: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000db8723b
> 1. DB::Exception::Exception(PreformattedMessage&&, int) @ 0x0000000007e8114c
> 2. ./src/Common/Exception.h:128: DB::Exception::Exception<String const&, String&, char const* const&>(int, FormatStringHelperImpl<std::type_identity<String const&>::type, std::type_identity<String&>::type, std::type_identity<char const* const&>::type>, String const&, String&, char const* const&) @ 0x0000000012df8a6d
> 3. ./build_docker/./src/Storages/MergeTree/registerStorageMergeTree.cpp:507: DB::create(DB::StorageFactory::Arguments const&) @ 0x0000000012df59ab
> 4. ./contrib/llvm-project/libcxx/include/__functional/function.h:848: ? @ 0x000000001246a47b
> 5. ./build_docker/./src/Interpreters/InterpreterCreateQuery.cpp:1712: DB::InterpreterCreateQuery::doCreateTable(DB::ASTCreateQuery&, DB::InterpreterCreateQuery::TableProperties const&, std::unique_ptr<DB::DDLGuard, std::default_delete<DB::DDLGuard>>&, DB::LoadingStrictnessLevel) @ 0x0000000011aa5634
> 6. ./build_docker/./src/Interpreters/InterpreterCreateQuery.cpp:1536: DB::InterpreterCreateQuery::createTable(DB::ASTCreateQuery&) @ 0x0000000011a9d766
> 7. ./build_docker/./src/Interpreters/InterpreterCreateQuery.cpp:2036: DB::InterpreterCreateQuery::execute() @ 0x0000000011aac798
> 8. ./build_docker/./src/Interpreters/executeQuery.cpp:1238: DB::executeQueryImpl(char const*, char const*, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum, DB::ReadBuffer*) @ 0x0000000011ee86b9
> 9. ./build_docker/./src/Interpreters/executeQuery.cpp:1404: DB::executeQuery(String const&, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum) @ 0x0000000011ee477a
> 10. ./build_docker/./src/Server/TCPHandler.cpp:564: DB::TCPHandler::runImpl() @ 0x000000001309ca14
> 11. ./build_docker/./src/Server/TCPHandler.cpp:2484: DB::TCPHandler::run() @ 0x00000000130b8338
> 12. ./build_docker/./base/poco/Net/src/TCPServerConnection.cpp:43: Poco::Net::TCPServerConnection::start() @ 0x0000000015ebd207
> 13. ./build_docker/./base/poco/Net/src/TCPServerDispatcher.cpp:115: Poco::Net::TCPServerDispatcher::run() @ 0x0000000015ebd699
> 14. ./build_docker/./base/poco/Foundation/src/ThreadPool.cpp:205: Poco::PooledThread::run() @ 0x0000000015e8a281
> 15. ./base/poco/Foundation/src/Thread_POSIX.cpp:335: Poco::ThreadImpl::runnableEntry(void*) @ 0x0000000015e8883d
> 16. ? @ 0x00007f64f09ccac3
> 17. ? @ 0x00007f64f0a5e850
> 
> Test merge_table_streams failed with error code 1
> ```
Hi @antaljanosbenjamin, sorry for the late reply. Thanks you very much for this crucial error message which provided significant hints! I found the error output in the CI test reports in the file `merge_table_streams-err.log`. Upon analysis, I discovered that I did not handle the old format of the merge tree correctly. I intend to address this issue. Could I restore 
the branch or submit a new PR?

**Comment by antaljanosbenjamin** [comment]
Better to start a new PR, feel free to mention this PR as a history though.

**Pull request merged**
