### PR TITLE
Speed up `parseDateTime[InJodaSyntax]Or(Null|Zero)` on invalid inputs

### PR DESCRIPTION
**Pull request by liuneng1994**
This is a re-implementation of #62538 based on https://github.com/ClickHouse/ClickHouse/pull/62538#issuecomment-2051985193

`parseDateTime` previously always threw an exception when there was a parse error. This error was handled in the top-level loop and rethrown (for standard `parseDateTime`) or suppressed (`*OrNull/*OrZero` variants). With this PR, we no longer throw internal exceptions, instead faults are communicated back as error code.

In my local measurements, runtime to parse 100k invalid date/time strings (`max_threads = 1`) goes down from 2.1 sec to 0.0015 sec.

### Changelog category (leave one):
- Performance Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Functions `parseDateTimeOrNull`, `parseDateTimeOrZero`, `parseDateTimeInJodaSyntaxOrNull` and `parseDateTimeInJodaSyntaxOrZero` now run significantly faster (10x - 1000x) when the input contains mostly non-parseable values.

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### CODE REVIEW

**Comment by liuneng1994** [comment]
@rschu1ze new version base on expected

**Comment by rschu1ze** [comment]
Thanks, I'll check, but please expect a bit of delay as I am working in the next 1.5 weeks from a remote location with only random access to my laptop.

**Comment by robot-clickhouse-ci-2** [comment]
*This is an automated comment for commit a98cba351d2448e16e70047b94fa163961d3303a with description of existing statuses. It's updated for the latest CI running*

[❌ Click here](https://s3.amazonaws.com/clickhouse-test-reports/62634/a98cba351d2448e16e70047b94fa163961d3303a/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>❌ failure</td></tr>
<tbody>
</table>

**Comment by rschu1ze** [comment]
@liuneng1994 Hi, would it be possible to add a macro

```cpp
#define RETURN_ERROR(res, function_call) \     ■■ Macro is
{                                                         \
    if (auto result = function_call; !result.has_value()) \
        return tl::unexpected(result.error());            \
}
```

which can handle repeated code like

```cpp
if (auto result = date.setSecond(second); !result.has_value())
    return tl::unexpected(result.error());
```

? (I know, I removed it in your first PR ... bad idea, for uniformity we should get the macro back) - thanks!

**Comment by rschu1ze** [comment]
@liuneng1994 Thanks a lot. I fixed a few things:
- I added `[[nodiscard]]` everywhere because it is easy to forget checking the return code. There was actually one place where a return code was not checked.
- I reduced the number of thread in the performance tests (back) from 10 to 1. It is not guaranteed that every machine in CI has 10 cores. Also, performance improvements (because we no longer unwind the stack due to exception handling once per row), will also be visible for single-thead execution.

**Comment by rschu1ze** [comment]
>  When the new use case is run in a single thread, a timeout will occur. Is there any way to increase the timeout of this use case? Otherwise, the number of test records needs to be reduced.

The only way to deal with that is to reduce the dataset size... I also did that (1 mio rows --> 100k rows).

**Review by rschu1ze — APPROVED** [review]

**Comment by clickgapai** [comment]
Hi @liuneng1994 @rschu1ze — while reviewing this PR I found the following:

- **Coverage gap:** Post-instruction error paths (`cur < end` malformed input; `buildDateTime` failure) untested for `parseDateTime*Or(Null|Zero)` variants — https://github.com/ClickHouse/ClickHouse/pull/104074

Could you review the test PR and add the `can be tested` label if it looks good?
Happy to discuss — close anything that's wrong or already addressed.

**Pull request merged**
