### PR TITLE
Changed the error code of the function

### PR DESCRIPTION
**Pull request by xogoodnow**
### Changelog category (leave one):
- Not for changelog

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
I believe the error code for this function should not be "NOT_ALLOWED" since it simply is an invalid query and "BAD_QUERY_PARAMETER" is a more reasonable error code for this

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
@xogoodnow, the PR description was incorrect. I have edited it, please merge with the master branch.

**Comment by robot-clickhouse-ci-2** [comment]
*This is an automated comment for commit bb542c137e0fbf1ea1a587b507ed4da12cfaf402 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/66491/bb542c137e0fbf1ea1a587b507ed4da12cfaf402/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/84760f83a626da47666c26dc95ae8b0b4bfbf681/docs_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Comment by alexey-milovidov** [comment]
https://s3.amazonaws.com/clickhouse-test-reports/66491/1e1563e6a491687e7d264eb9325f52d9eda304f5/style_check.html

**Comment by alexey-milovidov** [comment]
Style check has failed. Please fix the style and merge with the master branch.

**Comment by xogoodnow** [comment]
Yes, sorry about that.
Fixed

**Comment by xogoodnow** [comment]
The runner is non-responsive apparently
https://s3.amazonaws.com/clickhouse-test-reports/66491/2d753ca930df4de74a77f6023d31dbd8b32445b9/stateless_tests__release_.html

**Pull request merged**
