### PR TITLE
Enable mlock of clickhouse binary by default

### PR DESCRIPTION
**Pull request by alexey-milovidov**
Changelog category (leave one):
- Performance Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Enable mlock of clickhouse binary by default. It will prevent clickhouse executable from being paged out under high IO load.

### CODE REVIEW

**Comment by akuzm** [comment]
No difference in perf test. This might be a problem on laptops, so new contributors have to be aware of this and change the default config.

**Comment by filimonov** [comment]
Maybe we should have 2 variants of config in distribution? Config.xml (as now) and config.xml.optimized (mostly for prod setup)?

**Comment by alexey-milovidov** [comment]
> The mlock might be a problem on systems with low memory such as laptops, so new contributors have to be aware of this and change the default config.

I also had the same thoughts and run some experiments. For whatever reason, I did not observe any slowdown.

Notes:
- only small part of the binary is mapped (e.g. code segment), about 200 MB (if I remember correctly) of 3000 MB (most of that is debug info);
- if you run the binary after build (on development machine) or after installation, it will be already in page cache;
- some part of the binary will be in memory after startup nevertheless (the question - what is the size of this part of binary, how it compares to the size of all code) - need more experiments;
- paging out of code segment is a huge issue in production servers.

> Maybe we should have 2 variants of config in distribution? Config.xml (as now) and config.xml.optimized (mostly for prod setup)?

It's unnecessary complexity (remember `my_tiny.cnf`).

**Comment by alexey-milovidov** [comment]
On my machine, fresh startup:
```
$ echo 3 | sudo tee /proc/sys/vm/drop_caches
$ ./clickhouse-server
...
$ vmtouch -f clickhouse-server
           Files: 1
     Directories: 0
  Resident Pages: 17820/407775  69M/1G  4.37%
         Elapsed: 0.011254 seconds
```

**Comment by alexey-milovidov** [comment]
For development machines it won't work nevertheless, because it requires CAP_IPC_LOCK (that is set up only on package installation).

**Comment by alexey-milovidov** [comment]
Another experiment:
```
$ sudo setcap cap_ipc_lock=+ep /home/milovidov/work/ClickHouse/build/programs/clickhouse
$ ./clickhouse-server
...
$ vmtouch -f clickhouse-server
           Files: 1
     Directories: 0
  Resident Pages: 65256/407775  254M/1G  16%
         Elapsed: 0.016184 seconds
```

Yes, it works as expected.

254M vs 69M
- there is a difference indeed but not radical.

**Comment by alexey-milovidov** [comment]
An experiment on a server with HDDs:
```
milovidov@mtlog-perftest03j:~$ time /usr/bin/clickhouse server 2>&1 | head -n1
Processing configuration file 'config.xml'.

real    0m0,104s
user    0m0,080s
sys     0m0,020s
milovidov@mtlog-perftest03j:~$ echo 3 | sudo tee /proc/sys/vm/drop_caches 
3
milovidov@mtlog-perftest03j:~$ time /usr/bin/clickhouse server 2>&1 | head -n1
Processing configuration file 'config.xml'.

real    0m1,880s
user    0m0,064s
sys     0m0,092s
```

It took almost 2 seconds to startup (this is before even enabling mlock).

**Comment by alexey-milovidov** [comment]
I ran a few another experiments on a slow server:
```
milovidov@example:~/ClickHouse/build_gcc9$ sudo setcap cap_ipc_lock=+ep /opt/milovidov/ClickHouse/build_gcc9/programs/clickhouse
milovidov@example:~/ClickHouse/build_gcc9$ echo 3 | sudo tee /proc/sys/vm/drop_caches
milovidov@example:~/ClickHouse/build_gcc9$ programs/clickhouse server -C ../programs/server/config.xml -- --mlock_executable=1
```

Additional time for mlock is just 0.3 .. 0.9 seconds in the worst case:

```
2020.05.23 12:06:05.052643 [ 332996 ] {} <Trace> Application: Will mlockall to prevent executable memory from being paged out. It may take a few seconds.
2020.05.23 12:06:05.941579 [ 332996 ] {} <Trace> Application: The memory map of clickhouse executable has been mlock'ed
```

```
2020.05.23 12:06:35.005275 [ 333311 ] {} <Trace> Application: Will mlockall to prevent executable memory from being paged out. It may take a few seconds.
2020.05.23 12:06:35.344082 [ 333311 ] {} <Trace> Application: The memory map of clickhouse executable has been mlock'ed
```

Looks worth doing.

**Comment by alexey-milovidov** [comment]
+200 MB of resident memory looks acceptable even for development laptop.

**Pull request merged**
