### PR TITLE
Log file name on error in FileChecker ctor

### PR DESCRIPTION
**Pull request by vdimir**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Review by alesapin — APPROVED** [review]
LGTM

**Comment by alexey-milovidov** [comment]
Need to fix `test_storage_kerberized_hdfs`.

**Comment by alesapin** [comment]
@Mergifyio update

**Comment by vdimir** [comment]
Fuzzer known issue https://github.com/ClickHouse/ClickHouse/issues/23645

**Pull request merged**
