### PR TITLE
Revert of "Revert the revert of "ColumnVector: optimize filter with AVX512 VBMI2 compress store" #40033"

### PR DESCRIPTION
**Pull request by alexey-milovidov**
This reverts #40033 due to the issues found in CI:

https://github.com/ClickHouse/ClickHouse/issues/41745
https://github.com/ClickHouse/ClickHouse/issues/41751

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by guowangy** [comment]
@alexey-milovidov This should relate to https://github.com/ClickHouse/ClickHouse/pull/41247 
I will try to find the root cause ASAP.

**Comment by guowangy** [comment]
The root cause is when `limit` is zero, the original code will still try to load from `data` which is zero length.
Patch is working in progress.
```
inline void vectorIndexImpl(const Container & data, const PaddedPODArray<Type> & indexes, size_t limit, Container & res_data)
```

**Comment by guowangy** [comment]
PR: https://github.com/ClickHouse/ClickHouse/pull/41765

**Comment by alexey-milovidov** [comment]
@guowangy Thank you!
I will first revert, and backport it to 22.9, then we will merge your PR and it will be available from 22.10.

**Comment by guowangy** [comment]
@alexey-milovidov 
But it's not related to #40033,  actually #41247 causes the problem.

**Comment by alexey-milovidov** [comment]
Ok. https://github.com/ClickHouse/ClickHouse/pull/41797

**Pull request merged**
