### PR TITLE
Preserve column alias with optimize_aggregators_of_group_by_keys

### PR DESCRIPTION
**Pull request by azat**
Changelog category (leave one):
- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Preserve column alias with optimize_aggregators_of_group_by_keys (`optimize_aggregators_of_group_by_keys` has been introduced in #11667)

Cc: @xPoSx 

<details>

HEAD:
- 3010b47489edba694a517a0b408a3a136cb880b7

</details>

### CODE REVIEW

**Comment by azat** [comment]
@alexey-milovidov @4ertus2 I just noticed 20.5 branch, looks like 20.5 should contains this fix?

P.S. maybe I wrote bad description, but the following query fails without this fix:

```sql
SELECT foo FROM (SELECT anyLast(number) AS foo FROM numbers(1) GROUP BY number);
Code: 47. DB::Exception: Received from localhost:9000. DB::Exception: Missing columns: 'foo' while processing query: 'SELECT foo FROM (SELECT anyLast(number) AS foo FROM numbers(1) GROUP BY number)', required columns: 'foo', source columns: 'number'. 
```

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
@azat Thank you for the fix! 
We don't have 20.5 prestable release yet and the checklist is not done: https://github.com/ClickHouse/ClickHouse/issues/11288
Yes, this bugfix must go to 20.5.

**Comment by azat** [comment]
@alexey-milovidov 

>We don't have 20.5 prestable release yet 

Yep, but AFAIU the release will be done from the 20.5 branch not from the master. Am I understand the release cycle correctly?

>and the checklist is not done: #11288

P.S. I was monitoring it and before writing comment checked the checklist, and saw that it was fully done.

**Comment by alexey-milovidov** [comment]
@azat I have no idea why we have 20.5 branch - it should not exist.

**Comment by azat** [comment]
>@azat I have no idea why we have 20.5 branch - it should not exist.

@alexey-milovidov will it be reseted to upstream/master?

**Comment by alexey-milovidov** [comment]
I have deleted 20.5 branch.

**Pull request merged**
