### PR TITLE
Support reading arrow::LargeListArray

### PR DESCRIPTION
**Pull request by edef1c**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Add support for LARGE_LIST with Arrow

### CODE REVIEW

**Comment by robot-clickhouse-ci-2** [comment]
*This is an automated comment for commit 99bd2b5643c3a965d720c3e977f149feda5ed304 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/56118/99bd2b5643c3a965d720c3e977f149feda5ed304/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td><a href="https://github.com/ClickHouse/ClickHouse/actions/runs/6690191475">✅ success</a></td></tr>
<tbody>
</table>
</details>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/56118/99bd2b5643c3a965d720c3e977f149feda5ed304/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Comment by edef1c** [comment]
```
<Error> TCPHandler: Code: 49. DB::Exception: Port is not connected. (LOGICAL_ERROR)
```

This seems like unrelated CI flakiness?

**Comment by rschu1ze** [comment]
ClickHouse Integration Tests (asan) [1/6]:
- test_zookeeper_config: #51464

ClickHouse Integration Tests (tsan) [6/6]:
- test_storage_kafka: #56043

**Comment by edef1c** [comment]
@Avogar GitHub doesn't make this super obvious, but I've only rebased and added whitespace (to conform more closely to the style guide) since the version you approved.

**Comment by Avogar** [comment]
Sorry for long review, I was on vacation. I will take a look today

**Comment by Avogar** [comment]
LGTM, but need to add a test with reading parquet file with large list.

**Comment by edef1c** [comment]
I've added tests. The CI failures again don't look particularly related: I don't think `test_dictionaries_postgresql/test.py::test_predefined_connection_configuration` is affected by this change, nor is AST parsing.

**Review by Avogar — APPROVED** [review]

**Pull request merged**
