### PR TITLE
Revert "Merge pull request #25888 from azat/replxx-convert-history-file"

### PR DESCRIPTION
**Pull request by alexey-milovidov**
This reverts commit e4cb2b4a8407a399b160341cbbb76faa51feb5e3.

See #25888

Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
@vdimir FYI

> Functional stateless tests flaky check (address) — Timeout, fail: 0, passed: 0 

It is a wrong report if PR only has removed tests.

**Comment by azat** [comment]
@alexey-milovidov Can you wait a little bit? The fix is trivial, I'm going to submit it today (there is still some time before the release)

**Comment by alexey-milovidov** [comment]
Ok, let's wait for tonight.

**Comment by vdimir** [comment]
> @vdimir FYI
> 
> > Functional stateless tests flaky check (address) — Timeout, fail: 0, passed: 0
> 
> It is wrong report if PR only has removed tests.

This should solve the issue https://github.com/ClickHouse/ClickHouse/pull/26552

**Pull request closed without merging**
