### PR TITLE
MergeTree Merge use BatchHeap

### PR DESCRIPTION
**Pull request by kitaisreal**
### Changelog category (leave one):
- Performance Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Improve performance of Merge operation for MergeTree using BatchHeap data structure.

### CODE REVIEW

**Comment by robot-ch-test-poll** [comment]
*This is an automated comment for commit d13d8644ea16c6ea6f34b3fc57cfc70770489bc6 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/56051/d13d8644ea16c6ea6f34b3fc57cfc70770489bc6/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td><a href="https://github.com/ClickHouse/ClickHouse/actions/runs/6656730098">✅ success</a></td></tr>
<tbody>
</table>
</details>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/56051/d13d8644ea16c6ea6f34b3fc57cfc70770489bc6/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Comment by kitaisreal** [comment]
MergeTree PRIMARY KEY column should have low-cardinality. Can be reproduces with such example:
```
DROP TABLE IF EXISTS test_table;

CREATE TABLE test_table (id UInt64, value UInt64) ENGINE=MergeTree ORDER BY (id);
SYSTEM STOP MERGES test_table;

INSERT INTO test_table SELECT number % 15, number FROM numbers_mt(500000000);
SYSTEM START MERGES test_table;
```

Before:
```
OPTIMIZE TABLE test_table

0 rows in set. Elapsed: 19.328 sec.
```

After:
```
OPTIMIZE TABLE test_table;

0 rows in set. Elapsed: 12.578 sec.
```

**Comment by nikitamikhaylov** [comment]
What about memory consumption for merges? Did it increase?

**Comment by kitaisreal** [comment]
> What about memory consumption for merges? Did it increase?

No it is the same.

**Comment by nikitamikhaylov** [comment]
Tests have failed.

**Comment by alexey-milovidov** [comment]
@kitaisreal tests have failed.

**Comment by alexey-milovidov** [comment]
Tests have failed.

**Comment by alexey-milovidov** [comment]
No activity in several months.

**Pull request closed without merging**
