### PR TITLE
[RFC] Fix possible parts duplicates after ALTER TABLE MOVE PART TO SHARD

### LINKED ISSUE #49574: test_part_moves_between_shards/test.py::test_deduplication_while_move flaky
Stats
https://play.clickhouse.com/play?user=play#c2VsZWN0IAp0b1N0YXJ0T2ZIb3VyKGNoZWNrX3N0YXJ0X3RpbWUpIGFzIGQsCmNvdW50KCksICBncm91cFVuaXFBcnJheShwdWxsX3JlcXVlc3RfbnVtYmVyKSwgIGFueShyZXBvcnRfdXJsKQpmcm9tIGNoZWNrcyB3aGVyZSAnMjAyMi0wNi0wMScgPD0gY2hlY2tfc3RhcnRfdGltZSBhbmQgdGVzdF9uYW1lIGxpa2UgJyV0ZXN0X3BhcnRfbW92ZXNfYmV0d2Vlbl9zaGFyZHMlJyBhbmQgdGVzdF9zdGF0dXMgaW4gKCdGQUlMJywgJ0ZMQUtZJykgZ3JvdXAgYnkgZCBvcmRlciBieSBkIGRlc2M=

Fails in master
https://s3.amazonaws.com/clickhouse-test-reports/0/6e08e43439f2d176f0f806e6d203365d95fb058b/integration_tests__release__[4_4]/integration_run_parallel2_0.log

### PR DESCRIPTION
**Pull request by azat**
The patch is pretty icky, hence - RFC

### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix possible parts duplicates after ALTER TABLE MOVE PART TO SHARD (not a production feature)

Before this patch ALTER TABLE MOVE PART TO SHARD has a race, and that
was the reason for flaky test.

Parts moves between shards works as follow (some steps are omitted, only
relevant is here):

1) I: writes parts for migration written to zookeeper (/pinned_parts_uuids)
2) I: queue request to read this parts from zookeeper (SYNC_SOURCE)
3) R1/R2: process SYNC_SOURCE
4) R1/R2: process SYNC_PINNED_PARTS_UUIDS (read parts from /pinned_parts_uuids)
5) R1/R2: triggers DESTINATION_FETCH (after this destionation shard could clone the part)

Where:
- I - initiator
- R1/R2 - replica 1 and 2

Now imagine the following, SELECT query started before (4) finished, and
now (4) finished, and so now remote nodes could already fetch data from
the replicas, but those SELECT query may know nothing about
pinned_parts_uuids and in this case, the query will not filter out
duplicates (since it is done only if there are pinned_parts_uuids - to
avoid overhead for tables without active parts movements), and this will
lead to duplicates in the query.

So to fix this I see only one (icky) option - do not allow any queries
in parallel with updating pinned_parts_uuids. Note, that this should be
enough because SYNC_PINNED_PARTS_UUIDS processed synchronously on all
replicas, so it is not possible that parts will appears on the
destination shards before it is finished. And AFAICS dead lock should
not be possible, since acquiring locks in reverse order
(exclusive_lock, pinned_part_uuids_mutex) does not happens.

Refs: #49579 (cc @alexey-milovidov )
Fixes: #49574
Follow-up for: #17348 (cc @xjewer)
Follow-up for: #17871 (cc @nvartolomei)

_Another option is to remove this feature all together, though it could be useful for automatic re-sharding_

### CODE REVIEW

**Comment by robot-ch-test-poll4** [comment]
This is an automated comment for commit 14ecff6db4b603bba1529f9c2790488216e1d5e1 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/50777/14ecff6db4b603bba1529f9c2790488216e1d5e1/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Comment by alesapin** [comment]
I would prefer to remove this experimental feature.

**Comment by azat** [comment]
>I would prefer to remove this experimental feature.

@alesapin This could be one of possible building block for automatic data re-sharding, can you explain your concerns about it?

**Comment by alexey-milovidov** [comment]
This building block is too complex and fragile, it is better to remove it entirely and write a new one.

**Comment by azat** [comment]
Actually I don't like this patch, since it uses the lock that is not intended to leak into such places I would say, and I think that there will be a better way to distribute parts between replicas.

However I was thinking about keeping this feature until #45766 will be resolved.

So if you also don't like this patch as well, then let's close this, and I guess that this feature should be removed completely then, since it has this problem (even though it is pretty rare, but still) and it looks like original authors are not interested in it anymore.

**Comment by alexey-milovidov** [comment]
Ok. I also thought that we don't need part UUIDs. Instead, we should identify parts by their content hashes, as they are perfectly immutable.

**Comment by nvartolomei** [comment]
@alexey-milovidov iirc it was possible to have parts created with the same hash some time ago since the part data was solely based on their contents. min/max block ids didn't work either because they would conflict across shards. This is why we opted for the UUID, to have a globally unique identifier in a distributed fashion.

**Comment by EmeraldShift** [comment]
Do consistent storage snapshots (#79471) make this task any easier? Im quite interested in the feature to move parts between shards "atomically", or at least in some automated way :)

**Pull request closed without merging**
