### PR TITLE
Fix pushdown of having

### PR DESCRIPTION
**Pull request by CurtizJ**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix pushdown of `HAVING` in case, when filter column is used in aggregation.

Detailed description / Documentation draft:
The problem is that columns are rearranged after pushdown optimization, but their positions were already saved in aggregator params.

### CODE REVIEW

**Comment by CurtizJ** [comment]
This pr should fix Sqlancer check.

**Comment by alexey-milovidov** [comment]
Don't understand how this change breaks everything...

**Comment by KochetovNicolai** [comment]
queries 
```
SELECT c0 + -1, sum(intDivOrZero(intDivOrZero(NULL, NULL), '2'), intDivOrZero(10000000000., intDivOrZero(intDivOrZero(intDivOrZero(NULL, NULL), 10), NULL))) FROM t_having GROUP BY c0 = 2, c0 = 10, intDivOrZero(intDivOrZero(intDivOrZero(NULL, NULL), NULL), NULL), c0 HAVING c0 = 2 SETTINGS enable_optimize_predicate_expression = 0

SELECT sum(c0 + 257) FROM t_having GROUP BY c0 = -9223372036854775808, NULL, -2147483649, c0 HAVING c0 = -9223372036854775808 SETTINGS enable_optimize_predicate_expression = 0
```

were fuzzed, but they crash in master too.

**Comment by KochetovNicolai** [comment]
```
The query formatting is broken.
Changed settings: optimize_skip_unused_shards = '1', force_optimize_skip_unused_shards = '1', optimize_skip_unused_shards_nesting = '1', force_optimize_skip_unused_shards_nesting = '2', any_join_distinct_right_table_keys = '1', optimize_duplicate_order_by_and_distinct = '1'
Got the following (different) text after formatting the fuzzed query and parsing it back:
'WITH NULL AS a SELECT (-2147483648 IN (NULL, NULL), -65535 IN (0 IN (NULL, '1048577'), 2147483648 IN tuple(nan))), tuple(-1048576 IN (-2. IN (NULL, '1048577'), -65537 IN tuple(100000002004087730000.)))'
, expected:
'WITH NULL AS a SELECT (-2147483648 IN (NULL, NULL), -65535 IN (-0 IN (NULL, '1048577'), 2147483648 IN tuple(nan))), tuple(-1048576 IN (-2. IN (NULL, '1048577'), -65537 IN tuple(100000002004087730000.)))'
```

Does not look like a error to me ...

**Comment by alexey-milovidov** [comment]
This is what @akuzm is going to fix in #22703

**Review by KochetovNicolai — APPROVED** [review]

**Pull request merged**
