### PR TITLE
SimpleAggregateFunction data type

### PR DESCRIPTION
**Pull request by bgranvea**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

For changelog. Remove if this is non-significant change.

Category (leave one):
- New Feature

Short description:
This new data type allows to have columns with light aggregation in an AggregatingMergeTree. This can only be used with simple functions like any, anyLast, sum, min, max.

Detailed description:
A column of type SimpleAggregateFunction(anyLast,Float64) in an AggregatingMergeTree behaves like a standard Float64 column, but when rows are merged, the aggregate function anyLast will be applied and the Float64 result will be stored. 
This allows better performance than the standard approach Null engine table + AggregatingMergeTree materialized view + aggregation finalization view in this simple case.

See https://github.com/yandex/ClickHouse/issues/3852 for a complete description of our use case.

### CODE REVIEW

**Comment by bgranvea** [comment]
The implementation is different from what I initially proposed in https://github.com/yandex/ClickHouse/issues/3852. 

Wrapping an existing data (like it is done for Nullable and LowCardinality) was too complex because there are many places in the code where the type is directly tested (dynamic_cast<TypeDataNullable *>...). Moreover the new data type doesn't change the behavior of the wrapped type at all. 

So my current solution is to use a DataTypeDomain as a way to add extra information on an existing DataType.

**Comment by bgranvea** [comment]
there are 2 failing tests, is it really related to my PR?

**Comment by alexey-milovidov** [comment]
The failing test is not related to your changes.

**Comment by bgranvea** [comment]
@alexey-milovidov I've rebased the pull request because there was a conflict. It is ready for reviewing.

**Comment by alexey-milovidov** [comment]
I've reviewed this PR. Sorry for the delay.

The code is mostly Ok, I have some minor complaints:

`void setCustomization(DataTypeCustomDescPtr custom_desc_) const;`
Better to return customized data type instead of modification of mutable member.

`static const std::vector<String> supported_functions{"any", "anyLast", "min", "max", "sum"};`
- better to have the method in IAggregateFunction
- heavy static initializers

`boost::algorithm::join(supported_functions, ","),`
- missing whitespace (`min,max` -> `min, max`)

Also I have some considerations:

The class hierarchy looks more complex than needed. I cannot grasp it at the first glance. If we use only "Simple" variants of "IDataTypeCustom", do we need anything else? Why customization of text serialization and name comes separately? Probably it was already the issue with previous implementation of DataTypeDomain. It will be nice if you will try to remove as much code as possible.

**Comment by bgranvea** [comment]
Thank you for your review. Regarding your points:

- I'm not very happy with the mutable member in IDataType either. But to get rid of that, I would have to change the creator of all existing datatypes to take extra parameters because they all can be wrapped in a SimpleAggregateFunction. This looks like very impacting.

- I've separated the customization of text serialization and name in order to support data types like SimpleAggregateFunction('anyLast', IPv4): in this case, the base datatype is a UInt32 with custom text serialization functions (because of IPv4) and with a custom name containing SimpleAggregateFunction info.

I think it is however possible to simplify the class hierarchy  by getting rid of  the SimpleTextSerialization level. 

I look at the other points and try to improve the code.

**Pull request merged**
