### PR TITLE
add distributed_ddl description, sync EN with RU version

### PR DESCRIPTION
**Pull request by Slach**
Signed-off-by: Slach <bloodjazman@gmail.com>

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Documentation (changelog entry is not required)

### CODE REVIEW

**Review by tavplubix — APPROVED** [review]

**Comment by tavplubix** [comment]
@Mergifyio update

**Comment by Slach** [comment]
@tavplubix looks like https://clickhouse-test-reports.s3.yandex.net/29078/700c1c4ce068c18c99111b01f226e2a267c861ef/docs_check.html#fail1 fails is not related to my code changes, should I resolve it?

**Comment by Slach** [comment]
@Mergifyio update

**Comment by Slach** [comment]
@tavplubix is PR ready to merge?

**Comment by alexey-milovidov** [comment]
@tavplubix Docs check did not pass because of a broken link: https://github.com/ClickHouse/ClickHouse/pull/29078/files#diff-235ccf8baa886b62296915758c7daba6dadedfc63a3071437d06df9bc68a76edR956

Fixed in https://github.com/ClickHouse/ClickHouse/commit/1e3fc8d434470f2586f6c265aaecae9bfdf076da

**Pull request merged**
