### PR TITLE
Fix MSan report in Kerberos library

### LINKED ISSUE #19132: Kerberos library is not MSan friendly.
**Describe the bug**
```
Uninitialized value was created by an allocation of 'buf' in the stack frame of function 'krb5_c_random_os_entropy'
    #0 0x3f05bb20 in krb5_c_random_os_entropy obj-x86_64-linux-gnu/../contrib/krb5/src/lib/crypto/krb/prng_fortuna.c:448
```
is not annotated.

### PR DESCRIPTION
**Pull request by alexey-milovidov**
Changelog category (leave one):
- Not for changelog (changelog entry is not required)

This closes #19132.

### CODE REVIEW

**Comment by alesapin** [comment]
Let me run integration tests with msan manually.

**Comment by alesapin** [comment]
Tons of failures https://clickhouse-test-reports.s3.yandex.net/19215/ce6dc40888de09919013809c34af3c59c05e87a5/integration_tests_(memory).html and kerberized kafka tests even didn't start.

**Comment by alexey-milovidov** [comment]
So everything is alright :)

**Comment by alesapin** [comment]
Ok, let's merge.

**Pull request merged**
