### PR TITLE
Add Bash script about installing stable version

### PR DESCRIPTION
**Pull request by peter279k**
Changelog category (leave one):

- Documentation (changelog entry is not required)

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
N/A

Detailed description / Documentation draft:

- Adding this example Bash script for use to know how to install the stable version.

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
It has more than a few commands.

**Comment by alexey-milovidov** [comment]
https://clickhouse.com/#quick-start

We only propose it if the user want to make full ClickHouse installation on generic Linux system, other than deb or rpm.

**Comment by peter279k** [comment]
So we don't need to provide the stable ClickHouse version installation for users?

I provide this because it only has the recommended message, but it doesn't have the related example.

**Comment by peter279k** [comment]
I think another approach to simplify this PR:

- Moving the stable version installation example to my specific Gist link.
- And change original example to following message:

```
If users want to know more details about stable version installation, please refer this [link](https://the_gist_link).
```

What do you think about that? I think it can let people who are interested in this example have the reference and it will not be complicated/frightening for normal people.

**Comment by alexey-milovidov** [comment]
It is still too complicated. Better to not have this instruction than to have it so complex.

**Pull request closed without merging**
