### PR TITLE
Disable optimize_trivial_count when deduplication for part movement feature is enabled

### PR DESCRIPTION
**Pull request by nvartolomei**
Changelog category (leave one):
- Bug Fix (user-visible misbehaviour in official stable or prestable release)

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Fix incorrect trivial count result when part movement feature is used #34089

### CODE REVIEW

**Review by novikd — APPROVED** [review]

**Comment by amosbird** [comment]
Could you also check if `count()`  works correctly when you enable `allow_experimental_projection_optimization`? It introduces a different strategy of trivial count optimization.

**Comment by nvartolomei** [comment]
@amosbird indeed projections don't work together with deduplication required for part movement. Disabled projections for now as you suggested.

**Comment by nvartolomei** [comment]
BuilderBinTidy failure seems unrelated:

```
Feb 08 13:19:58 /build/build_docker/../src/Processors/ForkProcessor.cpp:68:29: error: Method called on moved-from object 'data' [clang-analyzer-cplusplus.Move,-warnings-as-errors]
Feb 08 13:19:58                 output.push(data.clone());
Feb 08 13:19:58                             ^~~~~~~~~~~~
```

**Comment by novikd** [comment]
> Stateless tests (release, s3 storage, actions) — fail: 3, passed: 3810, skipped: 41

Unrelated

> Integration tests (release, actions) [1/2] — fail: 1, passed: 858, flaky: 0

Seems unrelated

**Pull request merged**
