### PR TITLE
Use sorting for full_sorting_merge join

### PR DESCRIPTION
**Pull request by vdimir**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
* Use sorting in `full_sorting_merge` JOIN if stream already sorted

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by srikanthccv** [comment]
@vdimir thanks for the amazing work. Is there a way something like dev/nightly build where I can use and thst this for my use-case posted here https://github.com/ClickHouse/ClickHouse/issues/40791#issue-1355468326?

**Comment by vdimir** [comment]
@srikanthccv 

Thank you for being so interested in ClickHouse and its new features!

You can download the build from CI. There's `ClickHouse build check` in the checks list, then click Details and download binary (`relwithdebuginfo | none | static`).

Right now, it's not available in this PR since tests are broken. I'm going to fix it soon.

After that, this feature turns on by following options:

```
SET join_algorithm = 'full_sorting_merge';
SET optimize_read_in_order = 1;
SET optimize_sorting_by_input_stream_properties = 1;
```


You may want to check if it's applied or not for your query by [EXPLAIN PIPELINE](https://clickhouse.com/docs/en/sql-reference/statements/explain/#explain-pipeline)

Examples:

<details>
<summary>Non optimized</summary>

```
(Expression)
ExpressionTransform
  (Aggregating)
  AggregatingTransform
    (Expression)
    ExpressionTransform
      (Join)
      MergeJoinTransform 2 → 1
        (Sorting)
        MergingSortedTransform 18 → 1
          MergeSortingTransform × 18
            LimitsCheckingTransform × 18
              PartialSortingTransform × 18
                (Expression)
                ExpressionTransform × 18
                  (ReadFromMergeTree)
                  MergeTreeThread × 18 0 → 1
        (Sorting)
        MergingSortedTransform 18 → 1
          MergeSortingTransform × 18
            LimitsCheckingTransform × 18
              PartialSortingTransform × 18
                (Expression)
                ExpressionTransform × 18
                  (ReadFromMergeTree)
                  MergeTreeThread × 18 0 → 1
```

</details>



<details>
<summary>Optimized</summary>

```
(Expression)
ExpressionTransform
  (Aggregating)
  AggregatingTransform
    (Expression)
    ExpressionTransform
      (Join)
      MergeJoinTransform 2 → 1
        (Sorting)
        MergingSortedTransform 23 → 1
          (Expression)
          ExpressionTransform × 23
            (ReadFromMergeTree)
            MergeTreeInOrder × 23 0 → 1
        (Sorting)
        MergingSortedTransform 23 → 1
          (Expression)
          ExpressionTransform × 23
            (ReadFromMergeTree)
            MergeTreeInOrder × 23 0 → 1
```

</details>

The optimized pipeline still contains `MergingSortedTransform` because we read sorted data in parallel and merge sort it into one stream, and it wouldn't consume additional memory.

Also note that only limited cases are supported (e.g., `JOIN ON t1.a = t2.a+1` wouldn't work for now since the expressions are not analyzed, also not sure about queries with several JOINs and queries with subqueries).

If you would try a new feature, please send your feedback. We would appreciate it.

**Comment by srikanthccv** [comment]
@vdimir thanks for the pointers. With the help of https://github.com/ClickHouse/ClickHouse/tree/master/docker/server and artifacts published here https://s3.amazonaws.com/clickhouse-builds/40492/dad3220ecc836103bfa027388cd4fa4fad830105/clickhouse_build_check/report.html I built a new image and tried using this. 
This is the settings config
```
┌─name────────────────────────────────────────┬─value──────────────┬─changed─┬─description───────────────────────────────────────────────────────────────────────────────┬─min──┬─max──┬─readonly─┬─type──────────┐
│ join_algorithm                              │ full_sorting_merge │       1 │ Specify join algorithm.                                                                   │ ᴺᵁᴸᴸ │ ᴺᵁᴸᴸ │        0 │ JoinAlgorithm │
│ optimize_read_in_order                      │ 1                  │       1 │ Enable ORDER BY optimization for reading data in corresponding order in MergeTree tables. │ ᴺᵁᴸᴸ │ ᴺᵁᴸᴸ │        0 │ Bool          │
│ optimize_sorting_by_input_stream_properties │ 1                  │       1 │ Optimize sorting by sorting properties of input stream                                    │ ᴺᵁᴸᴸ │ ᴺᵁᴸᴸ │        0 │ Bool          │
└─────────────────────────────────────────────┴────────────────────┴─────────┴───────────────────────────────────────────────────────────────────────────────────────────┴──────┴──────┴──────────┴───────────────┘
```
This is the result of `EXPLAIN PIPELINE` for my query.

```
┌─explain─────────────────────────────┐
│ (Expression)                        │
│ ExpressionTransform                 │
│   (Join)                            │
│   MergeJoinTransform 2 → 1          │
│     (Sorting)                       │
│     MergingSortedTransform 30 → 1   │
│       (Expression)                  │
│       ExpressionTransform × 30      │
│         (ReadFromMergeTree)         │
│         MergeTreeInOrder × 30 0 → 1 │
│     (Sorting)                       │
│     MergeSortingTransform           │
│       (Expression)                  │
│       ExpressionTransform           │
│         (Filter)                    │
│         FilterTransform             │
│           (ReadFromMergeTree)       │
│           MergeTreeInOrder 0 → 1    │
└─────────────────────────────────────┘
```

If I understand correctly this is the optimized version. I am curious what does this mean because It's significantly slower than the other join algorithms. Here are different join algo and the time it took to query response. Is there something I am missing?

```
full_sorting_merge :
6000 rows in set. Elapsed: 483.703 sec. Processed 670.23 million rows, 25.63 GB (1.39 million rows/s., 52.98 MB/s.)

hash:
6000 rows in set. Elapsed: 27.897 sec. Processed 878.27 million rows, 33.13 GB (31.48 million rows/s., 1.19 GB/s.)

parallel_merge:
6000 rows in set. Elapsed: 31.440 sec. Processed 878.27 million rows, 33.13 GB (27.93 million rows/s., 1.05 GB/s.)


```

**Comment by vdimir** [comment]
@srikanthccv 

The pipeline looks correct. For particular use cases, hash would be better (in the case of a small right table). But the difference is so huge 😕
May you please share the table size, approximate schema, and the number of unique keys in the tables to reproduce the issue?

Also interesting to look at `memory_usage` (from `system.query_log`)

**Comment by srikanthccv** [comment]
@vdimir Yes, I was really surprised by the difference too. I wanted to know if I am doing something wrong. 

>May you please share the table size, approximate schema, and the number of unique keys in the tables to reproduce the issue?

Sure, will do that.

**Comment by srikanthccv** [comment]
@vdimir Here are more details.

Operating system details:

AWS EC2 i3.4x large instance with 16 CPUs with NVME disk.

Schema details:

I have two tables created for time series data where one table contains the measurements/samples and other table contains the unique collection of label sets used for creating measurements

```sql
CREATE TABLE IF NOT EXISTS samples (
    metric_name LowCardinality(String),
    fingerprint UInt64 Codec(DoubleDelta, LZ4),
    timestamp_ms Int64 Codec(DoubleDelta, LZ4),
    value Float64 Codec(Gorilla, LZ4)
)
ENGINE = MergeTree
    PARTITION BY toDate(timestamp_ms / 1000)
    ORDER BY (metric_name, fingerprint, timestamp_ms)

CREATE TABLE IF NOT EXISTS signatures (
    metric_name LowCardinality(String),
    fingerprint UInt64 Codec(DoubleDelta, LZ4),
    timestamp_ms Int64 Codec(DoubleDelta, LZ4),
    labels_object JSON DEFAULT labels CODEC(ZSTD(5))
)
ENGINE = ReplacingMergeTree
    PARTITION BY toDate(timestamp_ms / 1000)
    ORDER BY (metric_name, fingerprint)
```

And the below is the table details.

```
┌─parts.database─┬─parts.table────┬──────rows─┬─latest_modification─┬─disk_size─┬─primary_keys_size─┬─engine─────────────┬─bytes_size─┬─compressed_size─┬─uncompressed_size─┬───────────────ratio─┐
│        metrics │ samples        │ 877965016 │ 2022-08-31 20:24:47 │ 3.30 GiB  │ 5.74 MiB          │ MergeTree          │ 3544245999 │ 3.28 GiB        │ 21.23 GiB         │ 0.15463137481930148 │
│        metrics │ signatures     │ 173163666 │ 2022-08-31 19:56:31 │ 1.46 GiB  │ 995.99 KiB        │ ReplacingMergeTree │ 1567036193 │ 1.44 GiB        │ 168.86 GiB        │ 0.00850110051402323 │
└────────────────┴────────────────┴───────────┴─────────────────────┴───────────┴───────────────────┴────────────────────┴────────────┴─────────────────┴───────────────────┴─────────────────────┘
```

The number of unique keys in the right table is ~140M but the query will include some filtering which trims down the right side table to few thousand rows.

The query I am running which is taking unusually long.

```sql
SELECT
    fingerprint,
    toStartOfInterval(toDateTime(intDiv(timestamp_ms, 1000)), toIntervalSecond(60)) AS ts,
    max(value) AS value
FROM samples as tbl1
INNER JOIN
(
    SELECT
        metric_name,
        fingerprint
    FROM signatures
    WHERE (metric_name = 'some_metric_name_with_6k_entries')
) AS tbl2 ON tbl1.metric_name = tbl2.metric_name AND tbl1.fingerprint = tbl2.fingerprint 
GROUP BY
    fingerprint,
    ts
ORDER BY
    fingerprint ASC,
    ts ASC
```

The `memory_usage` part of `query_log` shows 186264345.

Here is the full detail of the query_log
```
┌─type────────┬─event_date─┬──────────event_time─┬────event_time_microseconds─┬────query_start_time─┬─query_start_time_microseconds─┬─query_duration_ms─┬─read_rows─┬──read_bytes─┬─written_rows─┬─written_bytes─┬─result_rows─┬─result_bytes─┬─memory_usage─┬─current_database─┬─query──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬─formatted_query─┬─normalized_query_hash─┬─query_kind─┬─databases──────────┬─tables────────────────────────────────────────────────────────┬─columns──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬─projections─┬─views─┬─exception_code─┬─exception─┬─stack_trace─┬─is_initial_query─┬─user────┬─query_id─────────────────────────────┬─address──────────┬──port─┬─initial_user─┬─initial_query_id─────────────────────┬─initial_address──┬─initial_port─┬─initial_query_start_time─┬─initial_query_start_time_microseconds─┬─interface─┬─is_secure─┬─os_user─┬─client_hostname─┬─client_name─┬─client_revision─┬─client_version_major─┬─client_version_minor─┬─client_version_patch─┬─http_method─┬─http_user_agent─┬─http_referer─┬─forwarded_for─┬─quota_key─┬─distributed_depth─┬─revision─┬─log_comment─┬─thread_ids────────────────────────────────────────────────────────────────────────────────┬─ProfileEvents──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬─Settings──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬─used_aggregate_functions─┬─used_aggregate_function_combinators─┬─used_database_engines─┬─used_data_type_families─┬─used_dictionaries─┬─used_formats─┬─used_functions────────────────────────────────────────────────────────────────┬─used_storages─┬─used_table_functions─┬─transaction_id───────────────────────────────┐
│ QueryFinish │ 2022-09-02 │ 2022-09-02 08:48:33 │ 2022-09-02 08:48:33.341225 │ 2022-09-02 08:45:11 │    2022-09-02 08:45:11.410519 │            201930 │ 286018520 │ 11045250371 │            0 │             0 │       78000 │      1560096 │    186264345 │ metrics   │ SELECT
    fingerprint,
    toStartOfInterval(toDateTime(intDiv(timestamp_ms, 1000)), toIntervalSecond(60)) AS ts,
    max(value) AS value
FROM metrics.samples as tbl1
INNER JOIN
(
    SELECT
        metric_name,
        fingerprint
    FROM metrics.signatures
    WHERE (metric_name = 'avalanche_metric_mmmmm_1_4')
) AS tbl2 ON tbl1.metric_name = tbl2.metric_name AND tbl1.fingerprint = tbl2.fingerprint
GROUP BY
    fingerprint,
    ts
ORDER BY
    fingerprint ASC,
    ts ASC │                 │  10775926354040889501 │ Select     │ ['metrics'] │ ['metrics.samples','metrics.signatures'] │ ['metrics.samples.fingerprint','metrics.samples.metric_name','metrics.samples.timestamp_ms','metrics.samples.value','metrics.signatures.fingerprint','metrics.signatures.metric_name'] │ []          │ []    │              0 │           │             │                1 │ default │ a9ee67a3-f915-437c-bfe4-92429265c168 │ ::ffff:127.0.0.1 │ 43342 │ default      │ a9ee67a3-f915-437c-bfe4-92429265c168 │ ::ffff:127.0.0.1 │        43342 │      2022-09-02 08:45:11 │            2022-09-02 08:45:11.410519 │         1 │         0 │         │ 803a945f616a    │ ClickHouse  │           54460 │                   22 │                    9 │                    1 │           0 │                 │              │               │           │                 0 │    54466 │             │ [316,287,144,323,274,291,299,129,320,323,287,319,291,274,320,319,291,144,323,287,129,299] │ {'Query':1,'SelectQuery':1,'FileOpen':97,'ReadBufferFromFileDescriptorReadBytes':1203599048,'ReadCompressedBytes':1149834643,'CompressedReadBufferBlocks':113345,'CompressedReadBufferBytes':7433845612,'OpenedFileCacheHits':37,'OpenedFileCacheMisses':97,'IOBufferAllocs':192,'IOBufferAllocBytes':91335249,'ArenaAllocChunks':9,'ArenaAllocBytes':2093056,'FunctionExecute':25,'MarkCacheHits':124,'MarkCacheMisses':5,'CreatedReadBufferOrdinary':134,'DiskReadElapsedMicroseconds':559471,'NetworkReceiveElapsedMicroseconds':17149,'NetworkSendElapsedMicroseconds':197873,'NetworkSendBytes':6791010,'SelectedParts':26,'SelectedRanges':26,'SelectedMarks':107264,'SelectedRows':286018520,'SelectedBytes':11045250371,'ContextLock':108,'RWLockAcquiredReadLocks':4,'RealTimeMicroseconds':2019225821,'UserTimeMicroseconds':226375328,'SystemTimeMicroseconds':1790321,'SoftPageFaults':200685,'OSCPUWaitMicroseconds':1437769,'OSCPUVirtualTimeMicroseconds':228161857,'OSReadChars':1207066372,'OSWriteChars':334896,'QueryProfilerRuns':2248,'ThreadPoolReaderPageCacheHit':1225,'ThreadPoolReaderPageCacheHitBytes':1203599048,'ThreadPoolReaderPageCacheHitElapsedMicroseconds':559471,'AggregationPreallocatedElementsInHashTables':78000} │ {'load_balancing':'random','join_algorithm':'full_sorting_merge','max_memory_usage':'10000000000','optimize_read_in_order':'1','optimize_sorting_by_input_stream_properties':'1'} │ ['max']                  │ []                                  │ []                    │ []                      │ []                │ []           │ ['toIntervalSecond','and','toStartOfInterval','intDiv','toDateTime','equals'] │ []            │ []                   │ (0,0,'00000000-0000-0000-0000-000000000000') │
└─────────────┴────────────┴─────────────────────┴────────────────────────────┴─────────────────────┴───────────────────────────────┴───────────────────┴───────────┴─────────────┴──────────────┴───────────────┴─────────────┴──────────────┴──────────────┴──────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴─────────────────┴───────────────────────┴────────────┴────────────────────┴───────────────────────────────────────────────────────────────┴──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴─────────────┴───────┴────────────────┴───────────┴─────────────┴──────────────────┴─────────┴──────────────────────────────────────┴──────────────────┴───────┴──────────────┴──────────────────────────────────────┴──────────────────┴──────────────┴──────────────────────────┴───────────────────────────────────────┴───────────┴───────────┴─────────┴─────────────────┴─────────────┴─────────────────┴──────────────────────┴──────────────────────┴──────────────────────┴─────────────┴─────────────────┴──────────────┴───────────────┴───────────┴───────────────────┴──────────┴─────────────┴───────────────────────────────────────────────────────────────────────────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴──────────────────────────┴─────────────────────────────────────┴───────────────────────┴─────────────────────────┴───────────────────┴──────────────┴───────────────────────────────────────────────────────────────────────────────┴───────────────┴──────────────────────┴──────────────────────────────────────────────┘
```

Please let me know if you need more information

**Comment by srikanthccv** [comment]
@vdimir Here are the flamegraphs for two different join algorithms if it helps.

13fdd91b-1cfa-404a-b58b-c161afb17484 CPU



And 
487d4564-2476-43c6-a0b4-7bf2daba78db CPU

**Comment by vdimir** [comment]
Also, this PR will most likely be postponed until analyzer https://github.com/ClickHouse/ClickHouse/pull/31796 is merged (because of changes in Interpreter). I will check which parts need to be changed to support the new analyzer.

**Comment by vdimir** [comment]
Will try to implement it again in another PR

**Comment by alanpaulkwan** [comment]
Is there a PR open or associated push for using the on-disk ordering of the table? I am curious to test it out for my join speed issues.

**Pull request closed without merging**
