### PR TITLE
Add setting allow_experimental_partial_result

### PR DESCRIPTION
**Pull request by vdimir**
### Changelog category (leave one):

- Not for changelog (changelog entry is not required)

Follow up for https://github.com/ClickHouse/ClickHouse/pull/54476

### CODE REVIEW

**Comment by robot-ch-test-poll3** [comment]
This is an automated comment for commit 93f17c0420b51856b8c99dab57a70043fe8aa047 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/54514/93f17c0420b51856b8c99dab57a70043fe8aa047/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Review by KochetovNicolai — APPROVED** [review]

**Comment by KochetovNicolai** [comment]
Stresstest triggered logical error :)
https://s3.amazonaws.com/clickhouse-test-reports/54514/9d068fa5a004b40c99ef98d6ca53ade5d9cd144d/stress_test__asan_/gdb.log

**Review by KochetovNicolai — CHANGES_REQUESTED** [review]
Logical error should be fixed.

**Comment by vdimir** [comment]
> AST fuzzer (ubsan) — Logical error: 'Can't set alias of compound_value.*'. [Details](https://s3.amazonaws.com/clickhouse-test-reports/54514/f21615408997d9e41eea09a20d651ebc3f04fe11/fuzzer_astfuzzerubsan/report.html)

https://github.com/ClickHouse/ClickHouse/issues/48049

> Stateless tests (tsan, s3 storage) [3/5] — Tests are not finished, fail: 1, passed: 29 [Details](https://s3.amazonaws.com/clickhouse-test-reports/54514/f21615408997d9e41eea09a20d651ebc3f04fe11/stateless_tests__tsan__s3_storage__[3_5].html)

https://github.com/ClickHouse/ClickHouse/pull/54928

**Review by KochetovNicolai — APPROVED** [review]

**Comment by vdimir** [comment]
> Stress test (msan) — Killed by signal (in clickhouse-server.log) [Details](https://s3.amazonaws.com/clickhouse-test-reports/54514/cb3bdaa4b01cd9a0778cd391b5c01f095350c881/stress_test__msan_.html)

One more fix https://github.com/ClickHouse/ClickHouse/pull/54514/commits/a134569bc3de0bb7b85d0fa40d4e53e26afbdb93

**Comment by vdimir** [comment]
> Stress test (tsan) — Found signal in gdb.log [Details](https://s3.amazonaws.com/clickhouse-test-reports/54514/a134569bc3de0bb7b85d0fa40d4e53e26afbdb93/stress_test__tsan_.html)

https://github.com/ClickHouse/ClickHouse/issues/55041

**Pull request merged**
