### PR TITLE
Fix kafka storage does not work with arrow and arrowstream format messages

### PR DESCRIPTION
**Pull request by godliness**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):

- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Kafka storage may support `arrow` and  `arrowstream` format messages

Detailed description / Documentation draft:

Before:

`prepareReader` create `file_reader` or `stream_reader` before kafka messages received and available

After:

Put `prepareReader` into `generate`, when `generate` called kafka messages should be available

### CODE REVIEW

**Review by filimonov — APPROVED** [review]

**Comment by filimonov** [comment]
LGTM. So that prepareReader was opening and trying to read the buffer in the constructor. It was obviously wrong. Such operations should not happen at construction time, generate is a proper place for that. Thanks! 

Let's just wait for tests to pass.

**Comment by godliness** [comment]
> Let's just wait for tests to pass.

Thanks for your reviewed.

Checked the failed test, did not find any information related to this PR, so i think it's other reasons occur these test failed.

PTAL

**Comment by alexey-milovidov** [comment]
> Integration tests (thread) — Timeout

This is just a timeout (test take too long time).

> Integration tests (asan) — fail: 1
test_polymorphic_parts/test.py::test_in_memory_wal

This fails currently in master, acknowledged.

>  SQLancer test — SQLancer test run. See report

This is a brand new check that we added a few days ago.
It does not pass right now, one of the fixes is here: https://github.com/ClickHouse/ClickHouse/pull/23359

**Comment by godliness** [comment]
> > Integration tests (thread) — Timeout
> 
> This is just a timeout (tests take too long time).
> 
> > Integration tests (asan) — fail: 1
> > test_polymorphic_parts/test.py::test_in_memory_wal
> 
> This fails currently in master, acknowledged.
> 
> > SQLancer test — SQLancer test run. See report
> 
> This is a brand new check that we added a few days ago.
> It does not pass right now, one of the fixes is here: #23359

Learned it! 

Thanks!

**Pull request merged**
