### PR TITLE
Split `RangeHashedDictionary`

### PR DESCRIPTION
**Pull request by antaljanosbenjamin**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
...

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

Trying to split `RangeHashedDictionary` into separate source files to reduce compilation complexity.

Here are the measurements on my dev machine:
- [master](https://pastila.nl/?017c8174/46b5876be1457a0ac4f6141699730bad#h3boCVZ9L6WFH66UHEt+Xg==)
- [after moving `getColumn` into `RangeHashedSource.cpp`](https://pastila.nl/?006cb97a/33805689cd2822dbdca22cd7ad90478f#Fi2MKvBn7foe/N9tG7ZepA==)
- [tried](https://pastila.nl/?002ea6fe/6a34a23bf18a3bc604f7bbe5ecb5dbe1#zkYvUmtKSsHZmhoYkJI8WA==) to move `getColumnInternal` also to source file (`RangeHashedDictionary2.cpp`), but it didn't have any impact
- [tried](https://pastila.nl/?00190409/a6c19d8f2e4b5a3b4e80895933872848#WuygiGKx4aZntAmG3UigWA==) to move the different specializations of `getColumn` into different files, but it didn't help, actually it performed worse than a single file in terms of file size and sum of compilation time

So far `RangeHashedSource.cpp` is the bottleneck. It is hard to split it because of lambdas, but I will try to make some improvements. However the object sizes are dropped: from `75MB` and `65MB` to `18MB` and `18MB` plus the extra `27MB`. Still trying to figure it out. The peak memory usage (in RelWithDebInfo build) dropped from `3.6G` to `2.9G`.

### CODE REVIEW

**Comment by robot-ch-test-poll3** [comment]
*This is an automated comment for commit b2859f9d2da293eaccd600dd66406f9ac8b18276 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/61162/b2859f9d2da293eaccd600dd66406f9ac8b18276/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

**Comment by rschu1ze** [comment]
AWSCredentialsProvider.cpp was changed, intended?

**Comment by antaljanosbenjamin** [comment]
Good point, and no! It was not intended. Thanks.

**Review by Algunenano — APPROVED** [review]

**Comment by antaljanosbenjamin** [comment]
It [doesn't help](https://s3.amazonaws.com/clickhouse-builds/PRs/61162/f1f388d9d26dbaf0775e90fdc26f9085b83b1c26/package_release_coverage/build_log.log). Let's see what I can do here.

**Comment by antaljanosbenjamin** [comment]
Far from being a good solution, but splitting the explicit template instantiations into multiple compilation units [seems like](https://pastila.nl/?00a0cd48/7058f156297c1f4a3d5f609aa1c445a0#hVvo3pyPBX47T6HZ98JwOA==) to help a lot. The maximum memory used dropped to `~1GB` in `RelWithDebInfo` (with the same config as before). Hopefully this will help.

**Pull request merged**
