### PR TITLE
bugfix: close rocks db files before deleting data when executing drop table command

### PR DESCRIPTION
**Pull request by liangliangpan**
close rocks db files before executing drop table. currently StorageEmbeddedRocksDB does not implement drop method, so when drop table is executing,  rocksdb file pointers are not closed.  In DatabaseCatalog::dropTableFinally() tries to remove the data directory from disk, but it fails.  The reason is there are opened files in this dir.  Linux kernel renames the opened file to .xxxx files., then the directory cannot be removed.
 We must implement drop() interface for rocksdb  storage to solve this problem. 
  

### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix a subtle issue with a rarely used `EmbeddedRocksDB` table engine in an extremely rare scenario: sometimes the `EmbeddedRocksDB` table engine does not close files correctly in NFS after running `DROP TABLE`.

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Review by vdimir — COMMENTED** [review]
Thank you for your PR!

Is it possible to add a test for the case?

**Comment by robot-ch-test-poll1** [comment]
This is an automated comment for commit 2db0b4f52afb445a23c9e947858269c8cf57e271 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/53502/2db0b4f52afb445a23c9e947858269c8cf57e271/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Comment by liangliangpan** [comment]
> 

I found this bug in NFS mount dir. The NFS driver use silly_rename mechanism to delete unclosed files.
I test this bug in local Mac and linux ext4 dir, can not reproduce.
So it is not necessary to add test case for this fix

**Comment by liangliangpan** [comment]
0_stateless/02416_rocksdb_delete_update.sql
this test case already include the create and drop table sql for rocksdb engine

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
Could you please merge with the master branch?

**Comment by liangliangpan** [comment]
> Could you please merge with the master branch?

how should I merge with the master branch?

**Comment by alexey-milovidov** [comment]
> Bugfix validate check — Changed tests don't reproduce the bug 

This check failed. If the bug cannot be reproduced, it should be classified as "Improvement". I will edit the description.

**Comment by alexey-milovidov** [comment]
> close rocks db files before executing drop table.

This changelog entry is not understandable to the end user.
I will change the category to "Not for changelog", so it will not be included in the release notes.

Or you can edit it accordingly...

**Comment by alexey-milovidov** [comment]
I decided to edit the changelog entry by myself, so it has a chance to appear in the release notes.

**Pull request merged**
