### PR TITLE
Build with avx2

### PR DESCRIPTION
**Pull request by nickitat**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by nickitat** [comment]
for some functions enabling avx2 itself gives significant speed up. apparently, it is evidence that we can gain some perf by providing avx specializations for them.

I still investigating why some functions slowed down. for some of them the reason is mixing between default and avx implementation in `ImplementationSelector`,  see: https://filetransfer.io/data-package/rGB1r6uJ#link

**Comment by nickitat** [comment]
from local benchmarks I see that w/o `-mavx` switch it completely sucks

**Comment by nickitat** [comment]
still, many queries slowed down. it seems the most common cases are empty or very short strings. we need to adjust the padding to 32 bytes.

**Comment by nickitat** [comment]
So, only one test is left to be fixed (01103_check_cpu_instructions_at_startup).

Perf tests:
[1](https://s3.amazonaws.com/clickhouse-test-reports/36593/9a388964296dc43fc4c618a01e70248e0febcffb/performance_comparison__actions__[1/4]/report.html)
[2](https://s3.amazonaws.com/clickhouse-test-reports/36593/9a388964296dc43fc4c618a01e70248e0febcffb/performance_comparison__actions__[2/4]/report.html)
[3](https://s3.amazonaws.com/clickhouse-test-reports/36593/9a388964296dc43fc4c618a01e70248e0febcffb/performance_comparison__actions__[3/4]/report.html)
[4](https://s3.amazonaws.com/clickhouse-test-reports/36593/9a388964296dc43fc4c618a01e70248e0febcffb/performance_comparison__actions__[4/4]/report.html)

not very good (

let's try without changes in memcpy.

**Comment by nickitat** [comment]
@Mergifyio update

**Comment by nickitat** [comment]
perf tests are almost good. though there are still some slowed down queries that don't work slower on my machine 🤷🏼‍♂️
continue investigation

**Comment by nickitat** [comment]
@Mergifyio update

**Comment by nickitat** [comment]
new:
* https://s3.amazonaws.com/clickhouse-test-reports/36593/04b5df0b2537ef34562102fa614c9f6b4debf5cf/performance_comparison_[1/4]/report.html
* https://s3.amazonaws.com/clickhouse-test-reports/36593/04b5df0b2537ef34562102fa614c9f6b4debf5cf/performance_comparison_[2/4]/report.html
* https://s3.amazonaws.com/clickhouse-test-reports/36593/04b5df0b2537ef34562102fa614c9f6b4debf5cf/performance_comparison_[3/4]/report.html
* https://s3.amazonaws.com/clickhouse-test-reports/36593/04b5df0b2537ef34562102fa614c9f6b4debf5cf/performance_comparison_[4/4]/report.html

---

grouped by reason:
__modulo__:
* modulo_1
* distinct_combinator_2
* distinct_combinator_3
* synthetic_hardware_benchmark_16
* conditional_9

__aggregation method one number__:
* synthetic_hardware_benchmark_16
* aggregation_overflow_0

__conversion__:
* sum_4
* sum_12
* unary_arithmetic_functions_95
* unary_arithmetic_functions_96
* decimal_casts_4
* sum_14
* unary_logical_functions
* math_12

__extract raw__:
* visit_param_extract_raw

__match impl__:
* re2_regex_caching_3

__round age__:
* unary_arithmetic_functions_96

__md5__:
* cpu_synthetic_12

__idn__:
* array_join_1

**Comment by nickitat** [comment]
@Mergifyio update

**Comment by nickitat** [comment]
@Mergifyio update

**Comment by alexey-milovidov** [comment]
@nickitat, let's adjust the padding to 31 bytes and continue.

**Pull request closed without merging**
