### PR TITLE
Use tmp disk for vertical merge files

### PR DESCRIPTION
**Pull request by GrigoryPervakov**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Performance Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Explicitly use a temporary disk to store vertical merge temporary data.

Detailed description / Documentation draft:

### CODE REVIEW

**Comment by alesapin** [comment]
But we need to store the file with rows mapping on tmp disk?

**Review by alexey-milovidov — APPROVED** [review]
LGTM

**Comment by GrigoryPervakov** [comment]
If you use S3 disk as first storage, this file uploaded to cloud and then deleted after merge.

**Comment by amosbird** [comment]
It seems we will leave a lot of garbage `tmp_merge` directories in tmp disk. And this don't work well in shared data and tmp disks.

**Comment by amosbird** [comment]
https://github.com/ClickHouse/ClickHouse/pull/28299

**Comment by rameshgarg475** [comment]
Hi, i am facing an issue.  my /tmp folder is not getting deleted automatically. i want to free the space. is it safe to delete it manually?. if yes, will it impact data in DB?

**Comment by azat** [comment]
>Hi, i am facing an issue. my /tmp folder is not getting deleted automatically. i want to free the space. is it safe to delete it manually?. if yes, will it impact data in DB?

It depends, do those files persist after restart? If yes, and you completely sure that it is tmp folder then you can safely delete it, ClickHouse will not use after restart anyway.

By the way, which version of ClickHouse do you have?
`tmp_path`/`tmp_policy` should be automatically cleaned up (everything that start with `tmp` in it).

**Comment by rameshgarg475** [comment]
> > Hi, i am facing an issue. my /tmp folder is not getting deleted automatically. i want to free the space. is it safe to delete it manually?. if yes, will it impact data in DB?
> 
> It depends, do those files persist after restart? If yes, and you completely sure that it is tmp folder then you can safely delete it, ClickHouse will not use after restart anyway.
> 
> By the way, which version of ClickHouse do you have? `tmp_path`/`tmp_policy` should be automatically cleaned up (everything that start with `tmp` in it).

We are using 21.2.5.5,  and system is not deleting them automatically . We can't restart db frequently , so as a workaround we deleted them manually. Now some of our data is missing.
Please suggest the better alternate .

**Comment by rameshgarg475** [comment]
> > so as a workaround we deleted 150+ days /tmp folders manually, but now some of our 60+ days data is missing. Which is our main concern.
> 
> It is unlikely that data older then 150 days are used, so I don't think that it is related to data miss.
> 
> > And reason for this behaviour
> 
> It depends on which files do you have in tmp. Can you post `find tmp -type f` ?

/tmp contains empty directories, so this command give blank.

**Comment by azat** [comment]
>/tmp contains empty directories, so this command give blank.

It is fine to remove empty directories and this should not lead to any data loss.

**Comment by rameshgarg475** [comment]
> > /tmp contains empty directories, so this command give blank.
> 
> It is fine to remove empty directories and this should not lead to any data loss.

okay, what is the significance of this tmp folder and when is it created?

**Comment by azat** [comment]
If you mean "tmp folders inside tmp path" then nothing significant, just left overs, some cleanup issues I guess (If you will provide a reproducer than it can be fixed).

**Pull request merged**
