### PR TITLE
Parallel merge sort (experimental)

### PR DESCRIPTION
**Pull request by alexey-milovidov**
Changelog category (leave one):
- Performance Improvement

Changelog entry (up to few sentences, required except for Non-significant/Documentation categories):
Improved performance of sorting without a limit or with big limit and external sorting.

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
```
SET max_memory_usage = 100000000000, max_bytes_before_external_sort = 50000000000;

SELECT number FROM numbers_mt(1000000) ORDER BY intHash64(number) LIMIT 900000, 10;
old: 0.149 sec.
new: 0.119 sec.

SELECT number FROM numbers_mt(10000000) ORDER BY intHash64(number) LIMIT 9000000, 10;
old: 2.622 sec.
new: 1.218 sec.

SELECT number FROM numbers_mt(100000000) ORDER BY intHash64(number) LIMIT 90000000, 10;
old: 60.771 sec.
new: 11.946 sec.

SELECT number FROM numbers_mt(1000000000) ORDER BY intHash64(number) LIMIT 900000000, 10;
old: 1376.686 sec.
new: 122.873 sec

SELECT number FROM numbers_mt(10000000000) ORDER BY intHash64(number) LIMIT 9000000000, 10;
old: 20719.163 sec.
new: 1636.834 sec
```

Up to 12 times faster on 16 core server.

**Comment by alexey-milovidov** [comment]
Performance test shows significant improvement:
https://clickhouse-test-reports.s3.yandex.net/8545/2314bb5a3430c421ddc371daeb9d20134bdaf181/performance_test/comparison_min_time_gcc_9.html

**Comment by alexey-milovidov** [comment]
@KochetovNicolai This has to be ported to "Processors" branch.

**Comment by zhang2014** [comment]
It changes the result of the following statement(Is that expected?)
```
SELECT * FROM (SELECT a, runningDifference(a) rd FROM (SELECT * FROM (SELECT 1 a UNION ALL SELECT 2 a ) ORDER BY a DESC ));
```

**Comment by alexey-milovidov** [comment]
It's not guaranteed how the returned data will be split in blocks.
Yes, this result is valid.

**Comment by alexey-milovidov** [comment]
@zhang2014 Let's just adapt the remaining test and we will merge #8503.

**Comment by GPF199541** [comment]
Connecting to 127.0.0.1:9000 as user default.
Connected to ClickHouse server version 20.9.2 revision 54439.

dbrtmappredb01 :)  SELECT * FROM (SELECT a, runningDifference(a) rd FROM (SELECT * FROM (SELECT 1 a UNION ALL SELECT 2 a ) ORDER BY a DESC ));

SELECT *
FROM 
(
    SELECT 
        a,
        runningDifference(a) AS rd
    FROM 
    (
        SELECT *
        FROM 
        (
            SELECT 1 AS a
            UNION ALL
            SELECT 2 AS a
        )
        ORDER BY a DESC
    )
)

┌─a─┬─rd─┐
│ 2 │  0 │
└───┴────┘
┌─a─┬─rd─┐
│ 1 │  0 │
└───┴────┘

2 rows in set. Elapsed: 0.042 sec. 


the version 20.9.2 is the same question,how to solve this problem

**Comment by den-crane** [comment]
@GPF199541  No solution. 2 blocks. runningDifference works only in block.
You can use arrays 
```
SELECT arrayJoin(arrayDifference(groupArray(a))) from 
  (select * FROM (SELECT 1 a UNION ALL SELECT 2 a ) ORDER BY a DESC)
```

**Pull request merged**
