### PR TITLE
Enable parallel INSERT for materialized view

### PR DESCRIPTION
**Pull request by Vxider**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Performance Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Enable parallel insert of materialized view when its target table supports.

Detailed description / Documentation draft:

Enable parallel insert of materialized view when its target table supports. this can benefit when pushing data by using `INSERT SELECT` query.

### CODE REVIEW

**Comment by qoega** [comment]
Did you try to test it after changes?

**Comment by Vxider** [comment]
> Did you try to test it after changes?

Sorry, I don’t have a complete test environment locally, so I can’t run all the tests (e.g. Kafka, zookeeper) on my computer.

**Comment by qoega** [comment]
Actually all integrational, stateless, stateful tests are available via docker. There are no tests for now that can show whether this change improves performance and there are no problems with it.

**Comment by Vxider** [comment]
I think this PR is beneficial in the INSERT SELECT query. I ran a simple test on my computer.

```
CREATE TABLE my_ints(number UInt64) ENGINE MergeTree order by tuple();
CREATE MATERIALIZED VIEW mv ENGINE MergeTree order by tuple() AS SELECT * FROM my_ints;
```

With the parallel insert:
```
INSERT INTO my_ints SELECT number FROM numbers_mt(100000000);

↓ Progress: 100.00 million rows, 800.00 MB (222.48 million rows/s., 1.78 GB/s.) Ok.

0 rows in set. Elapsed: 0.450 sec. Processed 100.00 million rows, 800.00 MB (222.42 million rows/s., 1.78 GB/s.)
```

Without the parallel insert:
```
INSERT INTO my_ints SELECT number FROM numbers_mt(100000000);

← Progress: 100.00 million rows, 800.00 MB (186.04 million rows/s., 1.49 GB/s.) Ok.

0 rows in set. Elapsed: 0.538 sec. Processed 100.00 million rows, 800.00 MB (186.03 million rows/s., 1.49 GB/s.)
```

If we insert into `mv` directly ( I'm not sure about this, but ClickHouse allows users to insert data into materialized view directly):

With the parallel insert:

```
INSERT INTO mv SELECT number FROM numbers_mt(100000000);

← Progress: 100.00 million rows, 800.00 MB (425.35 million rows/s., 3.40 GB/s.) Ok.

0 rows in set. Elapsed: 0.235 sec. Processed 100.00 million rows, 800.00 MB (425.11 million rows/s., 3.40 GB/s.)
```

Without the parallel insert:

```
INSERT INTO mv SELECT number FROM numbers_mt(100000000);

← Progress: 100.00 million rows, 800.00 MB (43.70 million rows/s., 349.62 MB/s.) Ok.

0 rows in set. Elapsed: 2.288 sec. Processed 100.00 million rows, 800.00 MB (43.70 million rows/s., 349.61 MB/s.)
```

**Review by alexey-milovidov — APPROVED** [review]
The code LGTM.

**Comment by alexey-milovidov** [comment]
`01231_distributed_aggregation_memory_efficient_mix_levels`
- already fixed.

**Comment by alexey-milovidov** [comment]
> Performance — 150 errors 

- unknown issue.

**Comment by alexey-milovidov** [comment]
But I need to figure out how INSERT SELECT appeared to be parallel for materialized view after this change...

**Comment by akuzm** [comment]
> > Performance — 150 errors
> 
> * unknown issue.

Should be fixed in master now (def6817ede8854d7c422429d2bbe9204c134ae25)

**Comment by alexey-milovidov** [comment]
> But I need to figure out how INSERT SELECT appeared to be parallel for materialized view after this change...

Ok.

**Comment by alexey-milovidov** [comment]
@qoega @Vxider You can add a performance test if you like.

**Pull request merged**
