### PR TITLE
Compress state of dashboard

### PR DESCRIPTION
**Pull request by amosbird**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
The state of URL's #hash in the dashboard is now compressed using [lz-string](https://github.com/pieroxy/lz-string). The default size of the state string is compressed from 6856B to 2823B.

### CODE REVIEW

**Comment by robot-ch-test-poll4** [comment]
*This is an automated comment for commit 7e86c0e9280bb6e46183c2c358474bfd283e2554 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/59124/7e86c0e9280bb6e46183c2c358474bfd283e2554/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/59124/7e86c0e9280bb6e46183c2c358474bfd283e2554/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Review by alexey-milovidov — APPROVED** [review]

**Comment by Felixoid** [comment]
Could it be the reason, that an old dashboard does not work anymore? 

https://pastila.nl/?00a7fcf5/a588d886ed9f8c1b17af5d918834efb8.link#ZJiiu8oxXkY7ivEyngU3TA==
https://pastila.nl/?006e08dc/99c290e565aaa182afb0b97223442795.link#WEPsCC47nYZJMe4+IQAm+Q==

**Comment by Felixoid** [comment]
Yes, manually decoding the after-hash with base64 and inserting it into the dashboard data helped. Could you make it backward compatible?

**Comment by amosbird** [comment]
> Could you make it backward-compatible?

Sure. Will investigate tomorrow.

**Comment by amosbird** [comment]
@Felixoid #59548 should work.

**Comment by serxa** [comment]
It turned out not to throw. It just returns empty string in case decoding fails. So here is a proper fix https://github.com/ClickHouse/ClickHouse/pull/59554

**Comment by amosbird** [comment]
> It turned out not to throw.

Oh, that's weird. In my env `JSON.parse` throws when it encounters invalid JSON string.

**Comment by serxa** [comment]
Now I get it. Decode does not throw, but `JSON.parse` throws. Your fix also works. Anyway, let's extract it into separate functions just for simplicity.

**Pull request merged**
