### PR TITLE
Fix erasing nonexistent column

### PR DESCRIPTION
**Pull request by lgbo-ustc**
Changelog category (leave one):
- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Avoid erasing columns from a block if it doesn't exist while reading data from Hive.

> Information about CI checks: https://clickhouse.tech/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
@antonio2368 This is the case when both changelog entry and PR title has to be edited :)

**Comment by lgbo-ustc** [comment]
The master branch has compile errors.
```
Mar 21 03:16:12 ../src/Access/Common/RowPolicyDefs.h:70:8: error: function 'DB::toString' has a definition with different parameter names [readability-inconsistent-declaration-parameter-name,-warnings-as-errors]
Mar 21 03:16:12 String toString(RowPolicyKind kind);
Mar 21 03:16:12        ^
Mar 21 03:16:12 /build/build_docker/../src/Access/Common/RowPolicyDefs.cpp:81:8: note: the definition seen here
Mar 21 03:16:12 String toString(RowPolicyKind type)
Mar 21 03:16:12        ^
Mar 21 03:16:12 /build/build_docker/../src/Access/Common/RowPolicyDefs.h:70:8: note: differing parameters are named here: ('kind'), in definition: ('type')
Mar 21 03:16:12 String toString(RowPolicyKind kind);
Mar 21 03:16:12        ^                      ~~~~
Mar 21 03:16:12                               type
Mar 21 03:16:12 69712 warnings generated.
Mar 21 03:16:12 Suppressed 69713 warnings (69711 in non-user code, 2 NOLINT).
```

**Comment by antonio2368** [comment]
@Mergifyio update

**Comment by antonio2368** [comment]
@lgbo-ustc the code in question is removed in the master so it should work after you merge it into this branch

**Review by antonio2368 — APPROVED** [review]

**Pull request merged**
