### PR TITLE
Add `blockSerializedSize` function (size on disk without compression)

### PR DESCRIPTION
**Pull request by azat**
Changelog category (leave one):
- New Feature

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Add blockSerializedSize() function (size on disk without compression)

Detailed description / Documentation draft:
Sometimes it is useful to know how much does this data will take on
disk, with blockSerializedSize() you can know this (although without
compression).

This can be a major knowledge for various aggregation functions that
tracking some state (i.e. `uniqCombined`).

*P.S. not sure that this is the best naming though, hence any suggestions are welcome! At first I was thinking about `getSizeOf()`, but this can be confused with size in memory, while they are differs*

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
This function is very specific. It works on blocks rather than individual values that is very confusing.

Maybe name it `blockSerializedSize` that will resemble `blockSize`? And we can allow multiple agruments.

**Comment by azat** [comment]
>This function is very specific. It works on blocks rather than individual values that is very confusing.

Indeed, nice catch, thanks!

> Maybe name it blockSerializedSize that will resemble blockSize? And we can allow multiple agruments.

Done

**Comment by alexey-milovidov** [comment]
Ok. *Almost* ready.
The usage of `MemoryWriteBuffer` is (1) overkill, (2) incorrect.
1. We should invent `NullWriteBuffer` that will do nothing on `nextImpl` method (`next` will just move cursor to the front and overwrite data).
2. You use the `offset` method that gives the offset inside current buffer. But what we need is `count` method that returns total number of written bytes.

**Comment by azat** [comment]
>The usage of MemoryWriteBuffer is (1) overkill, (2) incorrect.

Agree, done

**Review by alexey-milovidov — APPROVED** [review]

**Pull request merged**
