### PR TITLE
ISSUES-3110 fix merge and distributed engine query stage

### PR DESCRIPTION
**Pull request by zhang2014**
#3110 
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
Integration `test_merge_table_over_distributed` is broken.

**Comment by zhang2014** [comment]
Can you give me some information?  My development environment is working fine.
image

**Comment by ztlpn** [comment]
Current master:
```=========================================================================================== test session starts ============================================================================================
platform linux2 -- Python 2.7.12, pytest-3.7.4, py-1.6.0, pluggy-0.7.1 -- /usr/bin/python
cachedir: .pytest_cache
rootdir: /home/ztlpn/ClickHouse/dbms/tests/integration, inifile: pytest.ini
collected 3 items

test_merge_table_over_distributed/test.py::test_global_in PASSED                                                                                                                                     [ 33%]
test_merge_table_over_distributed/test.py::test_filtering FAILED                                                                                                                                     [ 66%]
test_merge_table_over_distributed/test.py::test_select_table_name_from_merge_over_distributed PASSED                                                                                                 [100%]

================================================================================================= FAILURES =================================================================================================
______________________________________________________________________________________________ test_filtering ______________________________________________________________________________________________

started_cluster = <helpers.cluster.ClickHouseCluster instance at 0x7f6f51ad1b00>

    def test_filtering(started_cluster):

        assert node1.query("SELECT id, val FROM merge_table WHERE id = 1").rstrip() == '1\tnode1'

        assert node1.query("SELECT id + 1, val FROM merge_table WHERE id = 1").rstrip() == '2\tnode1'

        assert node1.query("SELECT id + 1 FROM merge_table WHERE val = 'node1'").rstrip() == '2'

>       assert node1.query("SELECT id + 1, val FROM merge_table PREWHERE id = 1 WHERE _table != '_dummy'").rstrip() == '2\tnode1'

test_merge_table_over_distributed/test.py:54:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
helpers/cluster.py:332: in query
    return self.client.query(sql, stdin, timeout, settings, user, ignore_error)
helpers/client.py:21: in query
    return self.get_query_request(sql, stdin=stdin, timeout=timeout, settings=settings, user=user, ignore_error=ignore_error).get_answer()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <helpers.client.CommandRequest instance at 0x7f6f4fda2ef0>

    def get_answer(self):
        self.process.wait()
        self.stdout_file.seek(0)
        self.stderr_file.seek(0)

        stdout = self.stdout_file.read()
        stderr = self.stderr_file.read()

        if self.timer is not None and not self.process_finished_before_timeout and not self.ignore_error:
            raise QueryTimeoutExceedException('Client timed out!')

        if (self.process.returncode != 0 or stderr) and not self.ignore_error:
>           raise QueryRuntimeException('Client failed! Return code: {}, stderr: {}'.format(self.process.returncode, stderr))
E           QueryRuntimeException: Client failed! Return code: 10, stderr: Received exception from server (version 18.13.0):
E           Code: 10. DB::Exception: Received from 172.22.0.3:9000. DB::Exception: Not found column 1 in block. There are only columns: id, val, _table. Stack trace:
E
E           0. /usr/bin/clickhouse(StackTrace::StackTrace()+0x16) [0x55b3716]
E           1. /usr/bin/clickhouse(DB::Exception::Exception(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)+0x1f) [0x2ac836f]
E           2. /usr/bin/clickhouse(DB::Block::getByName(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)+0x193) [0x4875403]
E           3. /usr/bin/clickhouse(DB::ExpressionAction::execute(DB::Block&, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned long, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, unsigned long> > >&) const+0x1c6) [0x53c1826]
E           4. /usr/bin/clickhouse(DB::ExpressionActions::execute(DB::Block&) const+0x102) [0x53c2f32]
E           5. /usr/bin/clickhouse(DB::FilterBlockInputStream::FilterBlockInputStream(std::shared_ptr<DB::IBlockInputStream> const&, std::shared_ptr<DB::ExpressionActions> const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)+0x68a) [0x52c01fa]
E           6. /usr/bin/clickhouse() [0x4f65f4d]
E           7. /usr/bin/clickhouse(DB::InterpreterSelectQuery::executeImpl(DB::InterpreterSelectQuery::Pipeline&, std::shared_ptr<DB::IBlockInputStream> const&, bool)+0xd47) [0x4f6eca7]
E           8. /usr/bin/clickhouse(DB::InterpreterSelectQuery::executeWithMultipleStreams()+0x4b) [0x4f70a4b]
E           9. /usr/bin/clickhouse(DB::InterpreterSelectWithUnionQuery::executeWithMultipleStreams()+0x64) [0x4f5e5a4]
E           10. /usr/bin/clickhouse(DB::InterpreterSelectWithUnionQuery::execute()+0x35) [0x4f5eb25]
E           11. /usr/bin/clickhouse() [0x4ee8595]
E           12. /usr/bin/clickhouse(DB::executeQuery(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, DB::Context&, bool, DB::QueryProcessingStage::Enum)+0x65) [0x4eea045]
E           13. /usr/bin/clickhouse(DB::TCPHandler::runImpl()+0x76a) [0x2ad4c4a]
E           14. /usr/bin/clickhouse(DB::TCPHandler::run()+0x2b) [0x2ad545b]
E           15. /usr/bin/clickhouse(Poco::Net::TCPServerConnection::start()+0xf) [0x56e547f]
E           16. /usr/bin/clickhouse(Poco::Net::TCPServerDispatcher::run()+0xe5) [0x571dbc5]
E           17. /usr/bin/clickhouse(Poco::PooledThread::run()+0x81) [0x57b68b1]
E           18. /usr/bin/clickhouse(Poco::ThreadImpl::runnableEntry(void*)+0x38) [0x5817728]
E           19. /usr/bin/clickhouse() [0x5cf8e2f]
E           20. /lib/x86_64-linux-gnu/libpthread.so.0(+0x8184) [0x7fc507fa0184]
E           21. /lib/x86_64-linux-gnu/libc.so.6(clone+0x6d) [0x7fc5075bb03d]

helpers/client.py:89: QueryRuntimeException
==================================================================================== 1 failed, 2 passed in 3.94 seconds ====================================================================================```

**Comment by ztlpn** [comment]
@zhang2014 Are you sure you are testing with the correct version?

**Comment by zhang2014** [comment]
Yes. commit id : 13779bc75d85a3f52299c4df34a741208ebf4cf7

**Comment by zhang2014** [comment]
Next I'll try to recreate the problem in the same environment as the integration test

**Comment by zhang2014** [comment]
@ztlpn Thanks:) 
I successfully repeated the problem in the development environment. I will fix the problem as soon as possible.

**Comment by zhang2014** [comment]
@ztlpn @alexey-milovidov  fixed in #3159

**Pull request merged**
