### PR TITLE
add aliases for parts name and names

### LINKED ISSUE #48718: Alias `part` and `part_name` for system.part_log and system.parts
```
DESCRIBE TABLE system.parts
...
name                                  │ String
```

```
DESCRIBE TABLE system.part_log
...
part_name               │ String
```

^
This columns have the same meaning. Let's add an alias `part_name -> name` for `system.parts` and `name -> part_name` for `system.part_log`.

### PR DESCRIPTION
**Pull request by sichenzhao**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Add aliases `name` and `part_name` form `system.parts` and `system.part_log`. Closes #48718

### CODE REVIEW

**Comment by sichenzhao** [comment]
image

**Comment by sichenzhao** [comment]
image


image

**Comment by hanfei1991** [comment]
> image
> 
> image

Good job! Shall we add this to our tests?

**Review by hanfei1991 — APPROVED** [review]
but I think this change is very simple, so it's also okay to not add a test

**Comment by hanfei1991** [comment]
@sichenzhao test fails ...

**Pull request merged**
