### PR TITLE
Prepare for MemorySanitizer build in CI.

### PR DESCRIPTION
**Pull request by akuzm**
This is a preparatory commit just to get the msan build running in some
shape. It disables many external libraries that are not yet tested.

The current cmake command to build with msan is
`cmake -DSANITIZE=memory -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_CXX_FLAGS_ADD="-O1" -DCMAKE_C_FLAGS_ADD="-O1"`

It doesn't link in Debug, because executables are too big:
`ld.lld: error: crtstuff.c:(.text+0x7): relocation R_X86_64_32S out of range: 2166264512 is not in [-2147483648, 2147483647]`

Category (leave one):
- Build/Testing/Packaging Improvement

Short description (up to few sentences):
Add build with MemorySanitizer to CI.

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
Why `-O1`? It may lead to missed bugs.

**Comment by alexey-milovidov** [comment]
> It doesn't link in Debug, because executables are too big

We can fallback to `gold` if it is `lld` issue.

**Comment by alexey-milovidov** [comment]
> -fno-optimize-sibling-calls

That requires clarification.

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
Ok, but questions remain.

**Comment by akuzm** [comment]
Added a comment https://github.com/ClickHouse/ClickHouse/commit/6e32553e0184e151b23dd109a75acfa28630ca4d

**Pull request merged**
