### PR TITLE
Removing more enum-to-string utilities

### PR DESCRIPTION
**Pull request by myrrc**
Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by myrrc** [comment]
@Mergify update

**Comment by myrrc** [comment]
@mergifyio update

**Comment by myrrc** [comment]
Sadly, I don't have time to finish this PR, is someone is interested -- the branch will not be deleted.

**Comment by alexey-milovidov** [comment]
This PR makes sense.

**Pull request closed without merging**
