### PR TITLE
Restore the broken s390x build

### PR DESCRIPTION
**Pull request by HarryLeeIBM**
Restores the s390x build which broke in the boringssl --> OpenSSL transition ([PR](https://github.com/ClickHouse/ClickHouse/pull/59870)), see
- https://github.com/ClickHouse/ClickHouse/pull/59870#issuecomment-1959910652
- https://github.com/ClickHouse/ClickHouse/pull/59870#issuecomment-1961451875

Also hooks the build back into CI.

### Changelog category (leave one):
- Build/Testing/Packaging Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Re-enable broken s390x build in CI

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

---
### Modify your CI run:
**NOTE:** If your merge the PR with modified CI you **MUST KNOW** what you are doing
**NOTE:** Checked options will be applied if set before CI RunConfig/PrepareRunConfig step

#### Include tests (required builds will be added automatically):
- [ ]  Fast test
- [ ]  Integration Tests
- [ ]  Stateless tests
- [ ]  Stateful tests
- [ ]  Unit tests
- [ ]  Performance tests
- [ ]  All with ASAN
- [ ]  All with TSAN
- [ ]  All with Analyzer
- [ ]  Add your option here

#### Exclude tests:
- [ ]  Fast test
- [ ]  Integration Tests
- [ ]  Stateless tests
- [ ]  Stateful tests
- [ ]  Performance tests
- [ ]  All with ASAN
- [ ]  All with TSAN
- [ ]  All with MSAN
- [ ]  All with UBSAN
- [ ]  All with Coverage
- [ ]  All with Aarch64
- [ ]  Add your option here

#### Extra options:
- [ ]  do not test (only style check)
- [ ]  disable merge-commit (no merge from master before tests)
- [ ]  disable CI cache (job reuse)

#### Only specified batches in multi-batch jobs:
- [ ]  1
- [ ]  2
- [ ]  3
- [ ]  4

### CODE REVIEW

**Comment by HarryLeeIBM** [comment]
@rschu1ze, could you review the PR which fixes the broken s390x build when building openssl dynamic library? Thanks!

**Comment by robot-ch-test-poll1** [comment]
*This is an automated comment for commit bf3c8b6966d01d62d71fa3b9c3b45cbf7d7be7ed with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/63135/bf3c8b6966d01d62d71fa3b9c3b45cbf7d7be7ed/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
Can we also enable it in CI?

**Comment by rschu1ze** [comment]
> Can we also enable it in CI?

Done

**Comment by rschu1ze** [comment]
@HarryLeeIBM Sort-of-related question: When I https://github.com/ClickHouse/ClickHouse/pull/59870 from boringssl to OpenSSL, I followed the [s390x cross-compilation guide](https://clickhouse.com/docs/en/development/build-cross-s390x) but the build - even the previous build with boringssl - failed with linker errors and some of my comments in the PR express my frustration about that.

My understanding is that one needs to [force a specific version of mold](https://github.com/ClickHouse/ClickHouse/pull/59870#issuecomment-1978990248), at least this is what happens in CI (see [here](https://github.com/ClickHouse/ClickHouse/pull/63135/commits/6af89ecf120a71947725b547176391f7e59b44d8#diff-b149ed6549ff3637466c8579451e259aa06060c245d887a528ce52dcbce14fca)).

So I
- followed the guide to setup the dependencies
- got mold 2.0 as referenced in the Dockerfile
- ran `cmake -DCMAKE_TOOLCHAIN_FILE=cmake/linux/toolchain-s390x.cmake ..  -DLINKER_NAME=mold` (setting the latter is probably not necessary, just to make sure CMake picks up mold)
- ran `ninja` which fails with

```
ld.lld: error: unknown emulation: elf64_s390
clang++-17: error: linker command failed with exit code 1 (use -v to see invocation)
```

Note that the error is generated from `ld.lld`. This is funny because
- `cmake/linux/toolchain-s390x.cmake` sets the linker as mold (even without setting it explicitly via `-DLINKER_NAME`) but
- `contrib/openssl-cmake/CMakeLists.txt` overrides that and sets it as `lld`, as per your [recent fix](https://github.com/ClickHouse/clickhouse-private/pull/8595). S390x is the only ClickHouse platform where OpenSSL is build as a shared lib, i.e. `ENABLE_OPENSSL_DYNAMIC` is on by default.

So something is broken :-( Perhaps you like to go through the guide on a fresh Ubuntu 22.04 and update it as appropriate, thanks!

**Comment by HarryLeeIBM** [comment]
@rschu1ze, it has that link error for clang 17 and below. I am using clang 18 and it doesn't have the issue. I will do more investigation on clang 17 and mold linker.

**Comment by rschu1ze** [comment]
@HarryLeeIBM Interesting, thanks. Btw., the upgrade to compile everything with Clang 18 is upcoming ([PR](https://github.com/ClickHouse/ClickHouse/pull/60469)) but it is not clear yet when it will land.

**Review by rschu1ze — APPROVED** [review]

**Comment by HarryLeeIBM** [comment]
@rschu1ze, I made a change for clang-17 and mold linker issue, but there are some test errors in CI which seems unrelated to the change. Could it be merged now? Let me know if there is anything to do on my side. Thanks!

**Review by rschu1ze — APPROVED** [review]

**Comment by larryluogit** [comment]
@alexey-milovidov @rschu1ze Can this pr be backported to 24.3LTS?

**Comment by Algunenano** [comment]
It's not possible to backport new features to old releases. Not only that, it depends on the OpenSSL migration which happened in 24.4.

**Comment by rschu1ze** [comment]
@larryluogit Something seems mixed up:
- v24.3 LTS: uses boringssl by default on all platforms, including s390x. ClickHouse can _optionally_ be compiled with OpenSSL instead. Also, one can configure if OpenSSL should be linked statically or dynamically. The latter allows to run ClickHouse with OS-provided OpenSSL via hijacked $LD_LIBRARY_PATH$.
- v24.4: uses OpenSSL on all platforms, boringssl is no longer supported. The s390x build indeed broke during the migration, s390x builds in CI were consequently disabled. This PR fixes that.

As a result, this PR is not relevant for 24.3 LTS. @larryluogit if you actually meant 24.4, then I would be open to a backport since it is a build system fix and affects only s390x (= no stability risk for a non-LTS version).

**Comment by larryluogit** [comment]
@rschu1ze You're correct. I mixed up the releases :(. I actually meant 24.3 LTS. Sorry for the confusion. We are all good.

**Pull request merged**
