### PR TITLE
Fix a typo on the site.

### PR DESCRIPTION
**Pull request by akuzm**
Also:

* remove .mo files that are autogenerated from .po files

* reset all machine-generated translations (they all ask to 'feel the
form' so obviously nobody ever checked them and we can just throw them
out).

Changelog category (leave one):
- Documentation (changelog entry is not required)

### CODE REVIEW

**Comment by akuzm** [comment]
Good intro to gettext: https://www.labri.fr/perso/fleury/posts/programming/a-quick-gettext-tutorial.html
The command I used to reset: `for x in es fa fr ja ru tr zh ; do msginit --input=messages.pot --locale=$x --no-translator --output=$x/LC_MESSAGES/messages.po ; done`

**Review by alexey-milovidov — APPROVED** [review]

**Comment by blinkov** [comment]
@akuzm Docs check has not been launched for some reason while this might easily break the website build. These files were generated by `pybabel` instead of raw gettext tools, so the output differs significantly and `*.mo` are deleted for some reason (their compilation has not been added to the website build pipeline yet).

**Comment by alexey-milovidov** [comment]
@akuzm @blinkov We need this :)

**Comment by alexey-milovidov** [comment]
@blinkov We need this.

**Comment by akuzm** [comment]
Docs check OK, merging.

**Pull request merged**
