### PR TITLE
Faster server startup after stress test

### PR DESCRIPTION
**Pull request by alexey-milovidov**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Sometimes it take long time to start due to:
```
2022.12.25 00:18:34.895837 [ 256684 ] {} <Error> ZooKeeperClient: Code: 999. Coordination::Exception: Session expired, path: Session expired (fault injected on recv). (KEEPER_EXCEPTION)
```

and for some reason, it did not repair in 9 minutes.

### CODE REVIEW

**Comment by alesapin** [comment]
The reason is clear 
```
grep 'injected' clickhouse-server.backward.clean.log | wc -l
217
```

**Comment by alexey-milovidov** [comment]
#44613

**Comment by alexey-milovidov** [comment]
https://github.com/ClickHouse/ClickHouse/pull/44573

**Comment by alesapin** [comment]
```
Won't run stateful tests because test data wasn't loaded.
Traceback (most recent call last):
  File "/usr/bin/clickhouse-test", line 2354, in <module>
    main(args)
  File "/usr/bin/clickhouse-test", line 1893, in main
    processlist = get_processlist(args)
  File "/usr/bin/clickhouse-test", line 236, in get_processlist
    return clickhouse_execute_json(args, "SHOW PROCESSLIST")
  File "/usr/bin/clickhouse-test", line 131, in clickhouse_execute_json
    data = clickhouse_execute_http(base_args, query, timeout, settings, "JSONEachRow")
  File "/usr/bin/clickhouse-test", line 118, in clickhouse_execute_http
    res = client.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1348, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 277, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
2022-12-28 18:28:46,753 Hung check failed with exit code 1
```
Hung check failure unrelated

**Pull request merged**
