### PR TITLE
Properly cancel the query after client format error

### PR DESCRIPTION
**Pull request by azat**
Changelog category (leave one):
- Not for changelog (changelog entry is not required)

In case of format error (i.e. `select 2 settings
format_template_row='/dev/null' format Template`) the client will reset the connection,
since it will not expect Data blocks.

To fix this, catch this client error and properly cancel the query. This
should also fix query hang checks (the one that executed after each test).

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
FYI,

SETTINGS should go before FORMAT, not after.
This is a wrong implementation that has to be fixed ASAP, even with a cost of breaking something.

**Comment by alexey-milovidov** [comment]
Nothing else can be parsed after format, only the data.

**Comment by alexey-milovidov** [comment]
See #35100.

**Comment by alexey-milovidov** [comment]
Let's do nothing in this PR before carefully reverting all the "crap" here: https://github.com/ClickHouse/ClickHouse/issues/20343

**Comment by azat** [comment]
>SETTINGS should go before FORMAT, not after.
>This is a wrong implementation that has to be fixed ASAP, even with a cost of breaking something.

AFAIR when I first saw that FORMAT settings supported after the SETTINGS I though that it should only format-related settings...

So I'm suggesting to remove SETTINGS support after FORMAT, but note that:
- SELECT supports both, before and after FORMAT
- INSERT does not support SETTINGS before FORMAT

**Comment by azat** [comment]
>SETTINGS should go before FORMAT, not after.

BTW even query formatter wrote SETTINGS after FORMAT:

https://github.com/ClickHouse/ClickHouse/blob/7c3227adc5a716eef2b2f9dcdf4874b83ecf56da/src/Parsers/ASTQueryWithOutput.cpp#L37-L47

**Comment by azat** [comment]
>[Integration tests (asan, actions) [1/3] — fail: 1, passed: 669, flaky: 0](https://s3.amazonaws.com/clickhouse-test-reports/35867/3ce4844d4b30f63ed5e7e7c816b1b5fd69f78145/integration_tests__asan__actions__[1/3].html)

- `test_storage_postgresql_replica/test.py::test_abrupt_server_restart_while_heavy_replication` - fails in upstream too

**Comment by SaltTan** [comment]
Will this change affect the issue when ClickHouse can insert a partially received block if the connection was interrupted?
https://github.com/ClickHouse/ClickHouse/issues/27667
This happens to me regularly when there is a parsing error.
Every time a partial block inserted there is a message in the log: `<Information> TCPHandler: Client has dropped the connection, cancel the query.`
Parallel parsing and block squashing is enabled in my system.

**Comment by azat** [comment]
>Will this change affect the issue when ClickHouse can insert a partially received block if the connection was interrupted?

The `clickhouse-client` will send `Cancel` in this case, but I doubt that it will avoid partially inserted blocks completelly, this depends on lots of factors:
- in which table do you insert
- do you use async insert

But there is new setting, that is called `max_insert_delayed_streams_for_parallel_write` (per table level, see #34780), that may delay parts commit, and if the query will be cancelled before then this will avoid partial block INSERT.

**Comment by azat** [comment]
@alexey-milovidov can you please take a look? this is required for some other changes.

**Comment by alexey-milovidov** [comment]
@mergifyio update

**Review by alexey-milovidov — APPROVED** [review]

**Pull request merged**
