### PR TITLE
Revert "CI: disable ARM integration test cases with libunwind crash"

### LINKED ISSUE #63855: Not a bug: libunwind: aarch64: SIGSEGV signal handler leads to another seg fault
Problem can be 100% reproduced in integration tests on ARM in TCs:

1. test_crash_log/test.py::test_pkill
2. test_send_crash_reports/test.py::test_send_segfault

Stack trace:
```
#0  libunwind::CFI_Parser<libunwind::LocalAddressSpace>::parseFDEInstructions (addressSpace=..., fdeInfo=..., cieInfo=..., upToPC=<optimized out>, arch=<optimized out>, results=<optimized out>)
    at /tmp/ClickHouse/contrib/libunwind/src/DwarfParser.hpp:561
561     /tmp/ClickHouse/contrib/libunwind/src/DwarfParser.hpp: No such file or directory.
[Current thread is 1 (Thread 0xffffa8bae020 (LWP 13297))]
(gdb) bt
#0  libunwind::CFI_Parser<libunwind::LocalAddressSpace>::parseFDEInstructions (addressSpace=..., fdeInfo=..., cieInfo=..., upToPC=<optimized out>, arch=<optimized out>, results=<optimized out>)
    at /tmp/ClickHouse/contrib/libunwind/src/DwarfParser.hpp:561
#1  0x0000aaaae80afa60 in libunwind::UnwindCursor<libunwind::LocalAddressSpace, libunwind::Registers_arm64>::getInfoFromFdeCie (this=0xffff20832370, fdeInfo=..., cieInfo=..., pc=187651014192840, 
    dso_base=187650590556160) at /tmp/ClickHouse/contrib/libunwind/src/UnwindCursor.hpp:1614
#2  libunwind::UnwindCursor<libunwind::LocalAddressSpace, libunwind::Registers_arm64>::getInfoFromDwarfSection (this=0xffff20832370, pc=187651014192840, sects=..., fdeSectionOffsetHint=0)
    at /tmp/ClickHouse/contrib/libunwind/src/UnwindCursor.hpp:1689
#3  libunwind::UnwindCursor<libunwind::LocalAddressSpace, libunwind::Registers_arm64>::setInfoBasedOnIPRegister (this=this@entry=0xffff20832370, isReturnAddress=<optimized out>)
    at /tmp/ClickHouse/contrib/libunwind/src/UnwindCursor.hpp:2592
#4  0x0000aaaae80ae01c in __unw_init_local (cursor=0xffff20832370, context=0xffff208325e0) at /tmp/ClickHouse/contrib/libunwind/src/libunwind.cpp:91
#5  0x0000aaaae80aeed8 in unw_backtrace (buffer=0xffff208328f8, size=45) at /tmp/ClickHouse/contrib/libunwind/src/libunwind.cpp:346
#6  0x0000aaaad654cde8 in StackTrace::tryCapture (this=0xffff208328e8) at /tmp/ClickHouse/src/Common/StackTrace.cpp:347
#7  0x0000aaaad654ccbc in StackTrace::StackTrace (this=0xffff208328e8, signal_context=...) at /tmp/ClickHouse/src/Common/StackTrace.cpp:316
#8  0x0000aaaad6959244 in signalHandler (sig=11, info=0xffff20832da0, context=0xffff20832e20) at /tmp/ClickHouse/src/Daemon/BaseDaemon.cpp:154
#9  <signal handler called>
```
libunwind fork commit: 40d8eadf96b127d9b22d53ce7a4fc52aaedea965

To reproduce manually (not in tests):
1. run CH server on Aarch64 linux
2. kill -SEGV pid
3. Server crashes with segfault, No crash report will be generated `SELECT COUNT(*) FROM system.crash_log ==> 0`

### PR DESCRIPTION
**Pull request by azat**
Let's try re-run after https://github.com/ClickHouse/ClickHouse/pull/63865

Reverts ClickHouse/ClickHouse#63867

Fixes: https://github.com/ClickHouse/ClickHouse/issues/63855

#job_style_check
#job_Integration_tests_aarch64
#job_Integration_tests_release

### CODE REVIEW

**Comment by robot-ch-test-poll2** [comment]
*This is an automated comment for commit 1f5930e3c8ecdacf52a8782f78dac7e96d472d3a with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/63959/1f5930e3c8ecdacf52a8782f78dac7e96d472d3a/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

**Comment by alesapin** [comment]
Tried to check it locally -- didn't help.

**Comment by azat** [comment]
OK, but you were saying that it does not work?

**Comment by alesapin** [comment]
`> OK, but you were saying that it does not work?`
Yes, but I have build with clang-17. In CI we have clang-18... Maybe there is some difference...

**Comment by alesapin** [comment]
yes, didn't help, no stack trace on segfault.

**Comment by azat** [comment]
Hm, no stacktrace on SIGSEGV is a different story.

But anyway, for it works:

```
$ wget https://s3.amazonaws.com/clickhouse-builds/24.5/ee984e849f5af5f889411db08ece706b03a5e2ce/package_aarch64/clickhouse
$ ./clickhouse  server -- --listen_host=::  --trace_log=
$ ./clickhouse benchmark --query_profiler_cpu_time_period_ns=1 --query_profiler_real_time_period_ns=1 -q "select * from remote('127.{1..200}', system.one)"
^CStopping launch of queries. SIGINT received.

Queries executed: 203.

localhost:9000, queries: 203, QPS: 4.311, RPS: 862.155, MiB/s: 0.001, result RPS: 862.155, result MiB/s: 0.001.

0.000%          0.186 sec.
10.000%         0.194 sec.
20.000%         0.196 sec.
30.000%         0.198 sec.
40.000%         0.201 sec.
50.000%         0.203 sec.
60.000%         0.205 sec.
70.000%         0.207 sec.
80.000%         0.211 sec.
90.000%         0.217 sec.
95.000%         0.225 sec.
99.000%         0.260 sec.
99.900%         0.601 sec.
99.990%         0.601 sec.
```

```
SELECT arrayStringConcat(arrayMap(x -> concat(addressToLine(x), '::', demangle(addressToSymbol(x))), trace), '\n') AS sym
FROM system.trace_log
LIMIT 10
SETTINGS allow_introspection_functions = 1

   ┌─sym────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
1. │ ./src/Common/StackTrace.h:0::MemoryTracker::allocImpl(long, bool, MemoryTracker*, double)                                                                                                                                                                 …│
   │…./build_docker/./src/Common/MemoryTracker.cpp:0::MemoryTracker::allocImpl(long, bool, MemoryTracker*, double)                                                                                                                                             …│
   │…./build_docker/./src/Common/CurrentMemoryTracker.cpp:59::CurrentMemoryTracker::alloc(long)                                                                                                                                                                …│
   │…./build_docker/./src/Common/Allocator.cpp:114::Allocator<false, false>::alloc(unsigned long, unsigned long)                                                                                                                                               …│
   │…./src/IO/BufferWithOwnMemory.h:131::DB::Memory<Allocator<false, false>>::alloc(unsigned long)                                                                                                                                                             …│
   │…./src/IO/BufferWithOwnMemory.h:159::DB::WriteBufferFromFileDescriptor::WriteBufferFromFileDescriptor(int, unsigned long, char*, std::__1::shared_ptr<DB::Throttler>, unsigned long, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>)…│
   │…./contrib/llvm-project/libcxx/include/string:1499::DB::WriteBufferFromFile::WriteBufferFromFile(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, unsigned long, int, std::__1::shared_ptr<DB::Throttler>, unsigned int, char*, unsigned long)…│
   │…./contrib/llvm-project/libcxx/include/string:1499::DB::DiskLocal::writeFile(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, unsigned long, DB::WriteMode, DB::WriteSettings const&)                          …│
   │…./contrib/llvm-project/libcxx/include/string:1499::DB::DataPartStorageOnDiskFull::writeFile(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, unsigned long, DB::WriteMode, DB::WriteSettings const&)          …│
   │…./contrib/llvm-project/libcxx/include/string:1499::DB::MergeTreePartition::store(DB::MergeTreeData const&, DB::IDataPartStorage&, DB::MergeTreeDataPartChecksums&) const                                                                                  …│
   │…./build_docker/./src/Storages/MergeTree/MergedBlockOutputStream.cpp:239::DB::MergedBlockOutputStream::finalizePartAsync(std::__1::shared_ptr<DB::IMergeTreeDataPart> const&, bool, DB::NamesAndTypesList const*, DB::MergeTreeDataPartChecksums*)         …│
   │…./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:295::DB::MergeTreeData::createEmptyPart(DB::MergeTreePartInfo&, DB::MergeTreePartition const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::shared_ptr<DB::MergeTreeTransact
ion> const&)…│
   │…./contrib/llvm-project/libcxx/include/vector:1595::DB::createEmptyDataParts(DB::MergeTreeData&, std::__1::vector<DB::FutureNewEmptyPart, std::__1::allocator<DB::FutureNewEmptyPart>>&, std::__1::shared_ptr<DB::MergeTreeTransaction> const&)            …│
   │…./build_docker/./src/Storages/StorageMergeTree.cpp:1849::DB::StorageMergeTree::truncate(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::shared_ptr<DB::Context const>, DB::TableExclusiveLockHolder&)…│
   │…./build_docker/./src/Interpreters/InterpreterDropQuery.cpp:277::DB::InterpreterDropQuery::executeToTableImpl(std::__1::shared_ptr<DB::Context const> const&, DB::ASTDropQuery&, std::__1::shared_ptr<DB::IDatabase>&, StrongTypedef<wide::integer<128ul, unsigned int>, DB::UUIDTag>&)…│
   │…./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:701::DB::InterpreterDropQuery::execute()                                                                                                                                                      …│
   │…./build_docker/./src/Interpreters/executeQuery.cpp:1198::DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum, DB::ReadBuffer*)                                               …│
   │…./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:612::DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum)…│
   │…./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:612::DB::TCPHandler::runImpl()                                                                                                                                                                …│
   │…./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:594::DB::TCPHandler::run()                                                                                                                                                                    …│
   │…./build_docker/./base/poco/Net/src/TCPServerConnection.cpp:57::Poco::Net::TCPServerConnection::start()                                                                                                                                                    …│
   │…./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:48::Poco::Net::TCPServerDispatcher::run()                                                                                                                                                     …│
   │…./build_docker/./base/poco/Foundation/src/ThreadPool.cpp:202::Poco::PooledThread::run()                                                                                                                                                                   …│
   │…./base/poco/Foundation/include/Poco/SharedPtr.h:231::Poco::ThreadImpl::runnableEntry(void*)                                                                                                                                                               …│
   │…::                                                                                                                                                                                                                                                        …│
   │…::                                                                                                                                                                                                                                                         │
```

But there is one problem - ASLR, that leads to the problem that after server restart you will not get any stacktraces, workaround - disable it:

```
sudo sysctl kernel.randomize_va_space=2
```

**Comment by azat** [comment]
Ok, understood the problem, my comment is not related to it

**Comment by azat** [comment]
Hm, I've just tried on aarch64 and it works for me:

```
$ cmake -DCMAKE_C_COMPILER=clang-18 -DCMAKE_CXX_COMPILER=clang++-18 ..
$ time ninja
real    10m55.615s
user    1086m55.863s
sys     74m33.487s
```

```
$ pkill -SEGV clickhouse
2024.05.17 14:00:36.524536 [ 75262 ] {} <Trace> BaseDaemon: Received signal 11
2024.05.17 14:00:36.524955 [ 75912 ] {} <Fatal> BaseDaemon: ########## Short fault info ############
2024.05.17 14:00:36.525185 [ 75912 ] {} <Fatal> BaseDaemon: (version 24.5.1.1, build id: 8C5065E51D894D7880560078921C3D084339FF4E, git hash: 44c134c657357f084e59a6b203434fd66b471e9d) (from thread 75261) Received signal 11
2024.05.17 14:00:36.525239 [ 75912 ] {} <Fatal> BaseDaemon: Signal description: Segmentation fault
2024.05.17 14:00:36.525260 [ 75912 ] {} <Fatal> BaseDaemon: Address: 0x12887. Access: read. Unknown si_code.
2024.05.17 14:00:36.525281 [ 75912 ] {} <Fatal> BaseDaemon: Stack trace: 0x000000000af81b68 0x000000000b1ba641 0x00007a8608845320 0x00007a8608898d62 0x00007a860889b7dd 0x000000001527bb4f 0x000000000b1bc8eb 0x000000000b0cbaab 0x0000000013140346 0x000000000b0b8f97 0x0000000013153d02 0x000000000b0b6628 0x00000000064160b1 0x00007a860882a1ca 0x00007a860882a28b 0x000000000641502e
2024.05.17 14:00:36.525310 [ 75912 ] {} <Fatal> BaseDaemon: ########################################
2024.05.17 14:00:36.525332 [ 75912 ] {} <Fatal> BaseDaemon: (version 24.5.1.1, build id: 8C5065E51D894D7880560078921C3D084339FF4E, git hash: 44c134c657357f084e59a6b203434fd66b471e9d) (from thread 75261) (no query) Received signal Segmentation fault (11)
2024.05.17 14:00:36.525345 [ 75912 ] {} <Fatal> BaseDaemon: Address: 0x12887. Access: read. Unknown si_code.
2024.05.17 14:00:36.525361 [ 75912 ] {} <Fatal> BaseDaemon: Stack trace: 0x000000000af81b68 0x000000000b1ba641 0x00007a8608845320 0x00007a8608898d62 0x00007a860889b7dd 0x000000001527bb4f 0x000000000b1bc8eb 0x000000000b0cbaab 0x0000000013140346 0x000000000b0b8f97 0x0000000013153d02 0x000000000b0b6628 0x00000000064160b1 0x00007a860882a1ca 0x00007a860882a28b 0x000000000641502e
2024.05.17 14:00:36.535112 [ 75912 ] {} <Fatal> BaseDaemon: 0.0. inlined from ./.cmake/./src/Common/StackTrace.cpp:347: StackTrace::tryCapture()
2024.05.17 14:00:36.535132 [ 75912 ] {} <Fatal> BaseDaemon: 0. ./.cmake/./src/Common/StackTrace.cpp:316: StackTrace::StackTrace(ucontext_t const&) @ 0x000000000af81b68
2024.05.17 14:00:36.559825 [ 75912 ] {} <Fatal> BaseDaemon: 1. ./.cmake/./src/Daemon/BaseDaemon.cpp:0: signalHandler(int, siginfo_t*, void*) @ 0x000000000b1ba641
2024.05.17 14:00:36.559848 [ 75912 ] {} <Fatal> BaseDaemon: 2. ? @ 0x00007a8608845320
2024.05.17 14:00:36.559858 [ 75912 ] {} <Fatal> BaseDaemon: 3. ? @ 0x00007a8608898d62
2024.05.17 14:00:36.559864 [ 75912 ] {} <Fatal> BaseDaemon: 4. ? @ 0x00007a860889b7dd
2024.05.17 14:00:36.561762 [ 75912 ] {} <Fatal> BaseDaemon: 5. ./.cmake/./contrib/llvm-project/libcxx/src/condition_variable.cpp:47: std::condition_variable::wait(std::unique_lock<std::mutex>&) @ 0x000000001527bb4f
2024.05.17 14:00:36.586826 [ 75912 ] {} <Fatal> BaseDaemon: 6.0. inlined from ./contrib/llvm-project/libcxx/include/atomic:958: unsigned long std::__cxx_atomic_load[abi:v15000]<unsigned long>(std::__cxx_atomic_base_impl<unsigned long> const*, std::memory_order)
2024.05.17 14:00:36.586847 [ 75912 ] {} <Fatal> BaseDaemon: 6.1. inlined from ./contrib/llvm-project/libcxx/include/atomic:1588: std::__atomic_base<unsigned long, false>::load[abi:v15000](std::memory_order) const
2024.05.17 14:00:36.586858 [ 75912 ] {} <Fatal> BaseDaemon: 6.2. inlined from ./contrib/llvm-project/libcxx/include/atomic:1592: std::__atomic_base<unsigned long, false>::operator unsigned long[abi:v15000]() const
2024.05.17 14:00:36.586865 [ 75912 ] {} <Fatal> BaseDaemon: 6.3. inlined from ./.cmake/./src/Daemon/BaseDaemon.cpp:1164: operator()
2024.05.17 14:00:36.586879 [ 75912 ] {} <Fatal> BaseDaemon: 6.4. inlined from ./contrib/llvm-project/libcxx/include/__mutex_base:397: void std::condition_variable::wait<BaseDaemon::waitForTerminationRequest()::$_0>(std::unique_lock<std::mutex>&, BaseDaemon::waitForTerminationRequest()::$_0)
2024.05.17 14:00:36.586887 [ 75912 ] {} <Fatal> BaseDaemon: 6. ./.cmake/./src/Daemon/BaseDaemon.cpp:1164: BaseDaemon::waitForTerminationRequest() @ 0x000000000b1bc8eb
2024.05.17 14:00:36.615280 [ 75912 ] {} <Fatal> BaseDaemon: 7.0. inlined from ./contrib/llvm-project/libcxx/include/vector:434: ~vector
2024.05.17 14:00:36.615301 [ 75912 ] {} <Fatal> BaseDaemon: 7. ./.cmake/./programs/server/Server.cpp:2210: DB::Server::main(std::vector<String, std::allocator<String>> const&) @ 0x000000000b0cbaab
2024.05.17 14:00:36.621718 [ 75912 ] {} <Fatal> BaseDaemon: 8. ./.cmake/./base/poco/Util/src/Application.cpp:0: Poco::Util::Application::run() @ 0x0000000013140346
2024.05.17 14:00:36.672471 [ 75912 ] {} <Fatal> BaseDaemon: 9. ./.cmake/./programs/server/Server.cpp:420: DB::Server::run() @ 0x000000000b0b8f97
2024.05.17 14:00:36.674358 [ 75912 ] {} <Fatal> BaseDaemon: 10. ./.cmake/./base/poco/Util/src/ServerApplication.cpp:132: Poco::Util::ServerApplication::run(int, char**) @ 0x0000000013153d02
2024.05.17 14:00:36.722868 [ 75912 ] {} <Fatal> BaseDaemon: 11. ./.cmake/./programs/server/Server.cpp:0: mainEntryClickHouseServer(int, char**) @ 0x000000000b0b6628
2024.05.17 14:00:36.724626 [ 75912 ] {} <Fatal> BaseDaemon: 12.0. inlined from ./contrib/llvm-project/libcxx/include/vector:434: ~vector
2024.05.17 14:00:36.724643 [ 75912 ] {} <Fatal> BaseDaemon: 12. ./.cmake/./programs/main.cpp:509: main @ 0x00000000064160b1
2024.05.17 14:00:36.724652 [ 75912 ] {} <Fatal> BaseDaemon: 13. ? @ 0x00007a860882a1ca
2024.05.17 14:00:36.724663 [ 75912 ] {} <Fatal> BaseDaemon: 14. ? @ 0x00007a860882a28b
2024.05.17 14:00:37.002360 [ 75904 ] {} <Trace> AsynchronousMetrics: MemoryTracking: was 364.51 MiB, peak 364.51 MiB, free memory in arenas 22.01 MiB, will set to 606.00 MiB (RSS), difference: 241.49 MiB
2024.05.17 14:00:37.438726 [ 75912 ] {} <Fatal> BaseDaemon: 15. _start @ 0x000000000641502e
2024.05.17 14:00:37.438752 [ 75912 ] {} <Fatal> BaseDaemon: Integrity check of the executable skipped because the reference checksum could not be read.
2024.05.17 14:00:37.438765 [ 75912 ] {} <Information> SentryWriter: Not sending crash report
2024.05.17 14:00:37.438782 [ 75912 ] {} <Fatal> BaseDaemon: This ClickHouse version is not official and should be upgraded to the official build.
2024.05.17 14:00:38.002750 [ 75904 ] {} <Trace> AsynchronousMetrics: MemoryTracking: was 606.00 MiB, peak 606.00 MiB, free memory in arenas 22.20 MiB, will set to 1.03 GiB (RSS), difference: 447.00 MiB
2024.05.17 14:00:38.002781 [ 75904 ] {} <Debug> MemoryTracker: Current memory usage (total): 1.03 GiB.
Segmentation fault (core dumped)
```

The problem could be due to:
- kernel version
- libc version

Mine:

```
root@ip-172-31-35-35:/src/clickhouse/.cmake# uname -a
Linux ip-172-31-35-35 6.8.0-1008-aws #8-Ubuntu SMP Sat Apr 20 00:46:25 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
root@ip-172-31-35-35:/src/clickhouse/.cmake# apt-cache policy libc6
libc6:
  Installed: 2.39-0ubuntu8.1
  Candidate: 2.39-0ubuntu8.1
  Version table:
 *** 2.39-0ubuntu8.1 500
        500 http://us-east-1.ec2.archive.ubuntu.com/ubuntu noble-updates/main amd64 Packages
        500 http://security.ubuntu.com/ubuntu noble-security/main amd64 Packages
        100 /var/lib/dpkg/status
     2.39-0ubuntu8 500
        500 http://us-east-1.ec2.archive.ubuntu.com/ubuntu noble/main amd64 Packages
```

**Comment by azat** [comment]
OK, I've found the root cause - https://github.com/ClickHouse/ClickHouse/pull/64058

**Pull request closed without merging**
