### PR TITLE
Replace BackgroundProcessingPool with SchedulePool task and ThreadPool.

### PR DESCRIPTION
**Pull request by alesapin**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Simplify the implementation of background tasks processing for the MergeTree table engines family. There should be no visible changes for user.

### CODE REVIEW

**Comment by alesapin** [comment]
The server just silently refused to answer in stateless tests with thread sanitizer. Doesn't look good.

**Comment by alesapin** [comment]
Stress:
```
2020.10.21 02:51:14.812613 [ 420272 ] {} <Error> Application: Caught exception while loading metadata: Code: 57, e.displayText() = DB::Exception: Mapping for table with UUID=00000738-1000-4000-8000-000000000001 al
ready exists: Cannot attach table `test_16`.`mv` from metadata file /var/lib/clickhouse/store/b87/b87c0582-b3b2-4e92-b7fb-0b49c866ebd8/mv.sql from query ATTACH MATERIALIZED VIEW test_16.mv UUID '00000738-1000-4000
-8000-000000000001' (`a` Int32) ENGINE = Log AS SELECT a FROM test_16.tab_00738: while loading database `test_16` from path /var/lib/clickhouse/metadata/test_16, Stack trace (when copying this message, always incl
ude the lines below):
```

**Comment by alesapin** [comment]
No performance degradation on "merge tests":
insert sequential:
```
display-name    0       INSERT INTO t SELECT * FROM numbers(20000)
prewarm 0       insert_sequential.query0.prewarm0       0       2.492506265640259
prewarm 0       insert_sequential.query0.prewarm0       1       2.634366273880005
query   0       insert_sequential.query0.run0   0       2.502760410308838
query   0       insert_sequential.query0.run0   1       2.6985974311828613
query   0       insert_sequential.query0.run1   0       2.622211456298828
query   0       insert_sequential.query0.run1   1       2.68269419670105
query   0       insert_sequential.query0.run2   0       2.594139337539673
query   0       insert_sequential.query0.run2   1       2.7583072185516357
query   0       insert_sequential.query0.run3   0       2.702134847640991
query   0       insert_sequential.query0.run3   1       2.678210735321045
query   0       insert_sequential.query0.run4   0       2.6729700565338135
query   0       insert_sequential.query0.run4   1       2.9415955543518066
query   0       insert_sequential.query0.run5   0       2.589402198791504
query   0       insert_sequential.query0.run5   1       2.9460606575012207
query   0       insert_sequential.query0.run6   0       2.6683897972106934
query   0       insert_sequential.query0.run6   1       3.1266672611236572
query   0       insert_sequential.query0.run7   0       2.779920816421509
query   0       insert_sequential.query0.run7   1       3.388561964035034
query   0       insert_sequential.query0.run8   0       3.215115785598755
query   0       insert_sequential.query0.run8   1       3.2069432735443115
query   0       insert_sequential.query0.run9   0       3.0471608638763428
query   0       insert_sequential.query0.run9   1       3.2801365852355957
query   0       insert_sequential.query0.run10  0       2.925520658493042
query   0       insert_sequential.query0.run10  1       3.3361318111419678
query   0       insert_sequential.query0.run11  0       3.204563856124878
query   0       insert_sequential.query0.run11  1       3.8117313385009766
query   0       insert_sequential.query0.run12  0       2.956451892852783
query   0       insert_sequential.query0.run12  1       3.3952388763427734
```
read_in_order_many_parts:
```
create  0       23.193586349487305      INSERT INTO mt_100_parts SELECT number, rand() % 10000, rand() FROM numbers_mt(100000000)
create  1       23.504029035568237      INSERT INTO mt_100_parts SELECT number, rand() % 10000, rand() FROM numbers_mt(100000000)
create  1       41.7405641078949        INSERT INTO mt_1000_parts SELECT number, rand() % 10000, rand() FROM numbers_mt(100000000)
create  0       43.55165767669678       INSERT INTO mt_1000_parts SELECT number, rand() % 10000, rand() FROM numbers_mt(100000000)
create  1       3.8340775966644287      OPTIMIZE TABLE mt_100_parts FINAL
create  0       3.8088648319244385      OPTIMIZE TABLE mt_100_parts FINAL
create  0       156.07441067695618      OPTIMIZE TABLE mt_1000_parts FINAL
create  1       166.2251718044281       OPTIMIZE TABLE mt_1000_parts FINAL
```

**Comment by alesapin** [comment]
Connected issue https://github.com/ClickHouse/ClickHouse/issues/10987

**Comment by alesapin** [comment]
Performance looks OK.

**Review by alexey-milovidov — APPROVED** [review]

**Pull request merged**
