### PR TITLE
Refreshable MV: move data between tables instead of exchanging tables

### PR DESCRIPTION
**Pull request by al13n321**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

This PR is stacked on top of https://github.com/ClickHouse/ClickHouse/pull/58934 . Please look only at commits starting from "Refreshable MV: move data between tables instead of exchanging tables".

Instead of creating/dropping/renaming temp tables on each refresh, create a scratch table once and keep using it. Add a new operation in IStorage that target tables of refreshable MVs now need to support:
```
void transferAllDataFrom(StoragePtr source, bool remove_from_source, bool replace_at_destination, ContextPtr context);
```
It atomically moves all data from one table to another (with the same engine).

Refresh now looks like this:
 1. Truncate table `.inner_scratch_id.<uuid>`
 2. Do an INSERT SELECT into it.
 3. Move all data from `.inner_scratch_id.<uuid>` to `.inner_id.<uuid>`

ATTACH TABLE supports new syntax for providing multiple UUIDs for inner tables: `TO INNER UUID (<uuid1>, <uuid2>)`

`transferAllDataFrom()` for non-partitioned *MergeTree is implemented as just `REPLACE PARTITION ()` followed by `TRUNCATE`, so it automatically works for Replicated and Shared MergeTree. Not implemented for partitioned *MergeTree.

This may sound more complicated than renaming tables, but it avoids so many problems that it seems worth it. Problems with renaming tables:
 * Can't work for non-replicated tables in replicated databases. E.g. each replica independently refreshing its own Memory table.
 * Complicated to make work with replicated DB (see internal slack thread that starts with: https://pastila.nl/?0063c950/77d1d662f48cdd1acece87cd705721e3#szovDiRhTfklQpUDjS0/Yg== ). Kind of goes against how MV inner table is currently handled.
 * Creating replicated tables is expensive and slow (250ms).
 * If table was ALTERed during refresh, the exchange will undo the alter (can be fixed by checking version though).
 * Swapping two tables back and forth would be difficult to make correct because stale regular SELECTs may still be reading from the either table.
 * Arguably, constantly changing the target table's uuid feels sketchy and likely to cause more problems that we haven't noticed yet.

Still, adding a whole new operation for IStorage-s to implement is not good, lmk if you have better ideas.

### CODE REVIEW

**Comment by robot-clickhouse** [comment]
*This is an automated comment for commit eeccbbfa17bbb9effd79876f43d880ef36a4e03c with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/59745/eeccbbfa17bbb9effd79876f43d880ef36a4e03c/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/59745/eeccbbfa17bbb9effd79876f43d880ef36a4e03c/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Comment by tavplubix** [comment]
> transferAllDataFrom() for non-partitioned *MergeTree is implemented as just REPLACE PARTITION () followed by TRUNCATE

Is it actually more optimal than EXCHANGE TABLES? AFAIK, with zero-copy-replication, REPLACE PARTITION does a deep copy of all data parts.

> Can't work for non-replicated tables in replicated databases. 

Why?

> Creating replicated tables is expensive and slow (250ms).

Is REPLACE PARTITION less expensive? Especially if there are a lot of partitions to replace

> Swapping two tables back and forth would be difficult to make correct because stale regular SELECTs may still be reading from the either table.

AFAIU, we have exactly the same issue with swapping data parts sets. But it's absolutely fine that old queries read from the old table or the old set of parts

**Comment by tavplubix** [comment]
> like for EXCHANGE, which requires all replicas to be alive to complete

It does not require this, probably we can just turn off the waiting. 

I will review the rest later this week and will try to suggest something (there are a lot of things to consider)

**Comment by al13n321** [comment]
>> like for EXCHANGE, which requires all replicas to be alive to complete

> It does not require this, probably we can just turn off the waiting.

Without the wait it seems impossible to make ping-ponging tables work. Consider this scenario:
1. Table with UUID X is currently the main table (`.inner_id...`) and Y is the scratch table (`.inner_scratch_id...`).
2. Replica r2 started a refresh. It did an INSERT SELECT into Y.
3. A SELECT on replica r1 started. It mapped table name "`.inner_id...`" to StoragePtr X.
4. The refresh on r2 finished the INSERT SELECT, EXCHANGEd tables X and Y (*without waiting for r1*), and truncated table X.
5. r1 didn't notice the EXCHANGE yet (in DDL queue or SharedCatalog znodes), but did apply the truncate (through RMT log or SMT parts list).
6. The SELECT on r1 proceeds to read from X and sees empty data (or partial data if r2 already started another refresh).

**Comment by al13n321** [comment]
In summary, the 3 candidate approaches are:
 1. Moving data between tables (this PR). Requires reimplementing something like REPLACE PARTITION for RMT to avoid copying data. Will still be relatively inefficient because of O(num files) znode operations.
 2. Exchanging tables back and forth. Requires some complicated fragile logic for synchronizing SELECT vs EXCHANGE+TRUNCATE to avoid seeing incomplete data. That logic probably requires waiting for all replicas on each refresh.
 3. Creating a new table for each refresh. Need to come up with a new mechanism for managing MV's internal tables, different from what DatabaseReplicated is currently doing.

At this point, (3) seems the most promising. It can work something like this.

Refresh would:
* Create a new temporary table. Put replica name in the table name, e.g. `.inner_tmp_id.<mv_uuid>.<current_replica_name>`
* Exchange.
* Drop.

All 3 operations wait for the current replica to apply the DDL entry but don't wait for other replicas. The wait is interrupted if the MV is dropped.

The MV's main table will be managed the same way as today: each replica would create/drop the inner table locally when the MV is created/dropped locally by DDL worker. Except that there won't be TO INNER UUID because the UUID will change with each refresh. I guess that's fine, or does TO INNER UUID do something important?

The remaining question is how to reliably drop all temporary tables when dropping the MV. The following seems sufficient: when DDL worker drops the MV locally, enqueue a DDL queue entry `DROP TABLE IF EXISTS .inner_tmp_id.<mv_uuid>.<current_replica_name>`. (Do this after shutting down the IStorage, to make sure it won't enqueue a CREATE after our DROP IF EXISTS.) A downside is that the garbage tables will remain for a short while after the MV is dropped.

For SharedCatalog, instead of enqueueing DROP TABLE IF EXISTS we'd just delete the znode. I guess the common abstraction is "do this query asynchronously, without waiting for it even locally", and it should work even from DDL worker. Maybe it can also be reused to implement the interruptible wait for CREATE/EXCHANGE/DROP in refresh? Instead of one function to do a DDL operation there would be two: first do a keeper transaction to request the operation and return a version number, then wait for current/all replicas to reach that version number.

**Comment by tavplubix** [comment]
> here a SELECT from refreshable view may see empty table or a half-filled table

But why? I would not expect this. I see some explanation in your comment in Slack:

> Exchanging two tables back and forth? It would race with regular SELECTs, I think: suppose a SELECT (from MV) looked up the StoragePtr (by table name .inner[..]), then a refresh swapped and truncated the table, then the SELECT proceeded to read() from it - it'll get empty result. We have no lock preventing this, right?
> To do the whole refresh in a compare-and-swap way without mutex, we'd need to make the TRUNCATE return some kind of version number

But we don't need TRUNCATE at all, let's just DROP the old inner table after exchanging. It will be marked as dropped immediately, and then a background thread will remove the data once the table's refcount becomes 0. Queries that have a StoragePtr to the old table will be able to read the data. AFAIU, we don't need extra synchronization here.

> Without that wait (or something like it) it seems impossible to make ping-ponging tables work. Consider this scenario:
> r1 didn't notice the EXCHANGE yet (in DDL queue or SharedCatalog znodes), but did apply the truncate (through RMT log or SMT parts list).

Again, let's replace TRUNCATE with DROP. Only the last replica dropping the table will actually remove the data (so it will not see empty data until it drop the data by itself)

> I guess that's fine, or does TO INNER UUID do something important?

The only purpose of `TO INNER UUID` is to generate the UUID of the inner table on the initiator and pass it to other replicas. So all replicas will have the same UUID.

**Pull request closed without merging**
