### PR TITLE
Fixed SELECTing from ReplacingMergeTree with do_not_merge_across_partitions_select_final

### LINKED ISSUE #49685: Setting do_not_merge_across_partitions_select_final = 1 does not filter deleted rows in ReplacingMergeTree
We are using Clickhouse 23.3.2 version and we have a few ReplacingMergeTree tables defined like below:

```
CREATE TABLE subscriptions_replacing
(
    `subscription_id` UInt64,
    `account_id` UInt64,
    ...
    `_is_deleted` UInt8,
    `_version` UInt64
)
ENGINE = ReplicatedReplacingMergeTree('/clickhouse/{cluster}/tables/{database}/{table}', '{replica}', _version, _is_deleted)
PRIMARY KEY (account_id, subscription_id)
ORDER BY (account_id, subscription_id)
SETTINGS min_age_to_force_merge_seconds = 300, min_age_to_force_merge_on_partition_only = 1, index_granularity = 8192
```

When we are querying with `FINAL`, we get different results if we add the setting `do_not_merge_across_partitions_select_final = 1`. It seems like it skips filtering the deleted rows:

```
$ select count(), _is_deleted from intermediate_glacier.subscriptions_replacing group by _is_deleted

┌─count()─┬─_is_deleted─┐
│ 1096219 │           0 │
│  264359 │           1 │
└─────────┴─────────────┘

2 rows in set. Elapsed: 0.010 sec. Processed 1.36 million rows, 1.36 MB (139.59 million rows/s., 139.59 MB/s.)

$ select count() from subscriptions_replacing final 

┌─count()─┐
│ 1096219 │
└─────────┘

1 row in set. Elapsed: 0.066 sec. Processed 1.37 million rows, 34.22 MB (20.85 million rows/s., 521.13 MB/s.)

$ select count() from subscriptions_replacing final SETTINGS do_not_merge_across_partitions_select_final = 1

┌─count()─┐
│ 1360578 │
└─────────┘

1 row in set. Elapsed: 0.019 sec. Processed 1.36 million rows, 34.01 MB (72.04 million rows/s., 1.80 GB/s.)

$ select count() from subscriptions_replacing final where _is_deleted=0 SETTINGS do_not_merge_across_partitions_select_final = 1 

┌─count()─┐
│ 1096219 │
└─────────┘

1 row in set. Elapsed: 0.021 sec. Processed 1.36 million rows, 34.01 MB (65.00 million rows/s., 1.62 GB/s.)
```

Unfortunately I couldn't reproduce in a local setup. 

Is it expected that this setting affects the latest behaviour of `ReplacingMergeTrees` which filters the deleted rows, or is this a bug?

### PR DESCRIPTION
**Pull request by Enmk**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fixed ReplacingMergeTree to properly process single-partition cases when `do_not_merge_across_partitions_select_final=1`. Previously `SELECT` could return rows that were marked as deleted.

Closes: #49685

### CODE REVIEW

**Comment by robot-ch-test-poll4** [comment]
This is an automated comment for commit 322db80cd9f609e2de4e119eda6245d1c60e8fca with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/53511/322db80cd9f609e2de4e119eda6245d1c60e8fca/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Comment by Enmk** [comment]
> Style Check	Runs a set of checks to keep the code style clean. If some of tests failed, see the related log from the report	🔴 failure

Right now `Style check` reports only shell-related issues. This PR doesn't have any shell-scripts.

**Comment by den-crane** [comment]
try to merge with master. 
Style checker was updated 
* https://github.com/ClickHouse/ClickHouse/pull/53493/

**Review by alexey-milovidov — APPROVED** [review]
The change LGTM.

**Comment by alexey-milovidov** [comment]
@Enmk, would you like to continue?

**Comment by Enmk** [comment]
> @Enmk, would you like to continue?

Sure, was a bit busy with something else, but definitely want to finish this one.

**Comment by Enmk** [comment]
It looks like rabbitMQ service failed to start, in [ClickHouse Integration Tests (asan) [4/6]](https://s3.amazonaws.com/clickhouse-test-reports/53511/f896c6349c0f1005610b9b1c64c5be3ab0ca4ba9/integration_tests__asan__[4_6].html)

Figuring out why...

**Pull request merged**
