### PR TITLE
doc: try to fix PGO docs

### PR DESCRIPTION
**Pull request by zamazan4ik**
### Changelog category (leave one):
- Documentation (changelog entry is not required)

### Documentation entry for user-facing changes

- [x] Documentation is written (mandatory for new features)

This PR trying to fix the issues introduced by https://github.com/ClickHouse/ClickHouse/pull/52877

Added missing symlinks to the Russian and Chinese versions according to the guideline - probably that's the reason. If it doesn't help - another idea is try to change `sidebar_position`.

### CODE REVIEW

**Comment by robot-ch-test-poll3** [comment]
This is an automated comment for commit b4d692c95f93583b30d28c4c624979e4eb0763b3 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/52939/b4d692c95f93583b30d28c4c624979e4eb0763b3/ci_running.html)
The overall status of the commit is 🔴 failure

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🔴 failure</td></tr>
</table>

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
Please use this https://github.com/ClickHouse/ClickHouse/blob/master/.github/PULL_REQUEST_TEMPLATE.md

**Comment by zamazan4ik** [comment]
Done

**Comment by zamazan4ik** [comment]
@alexey-milovidov could you please trigger the CI once again?

**Review by alexey-milovidov — APPROVED** [review]

**Pull request merged**
