### PR TITLE
Improve decompression in readbig to avoid unnecessary memcpy

### PR DESCRIPTION
**Pull request by jinjunzh**
Co-authored-by: @vesslanjin jun.i.jin@intel.com

Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
- Add branch to avoid unnecessary memcpy in readbig.

Detailed description / Documentation draft:
When decompress consecutive blocks in readbig function, there are three cases: 1. entire block fits where it needs to be copied. 2. back part of block fits (always be the first block). 3. front part of block fits (always be the last block), we need handle these three cases differently so that we can avoid  unnecessary memcpy. In previous code, it put case 2 and case 3 together which probably have to call nextImpl and then memcpy in case 2, but actually we can avoid memcpy here.

### CODE REVIEW

**Comment by jinjunzh** [comment]
@nickitat 
Hi, It looks the error is not relevant to my commits, do you have any suggestions?

**Comment by nickitat** [comment]
@jinjunzh yeap, tests failures seem irrelevant and don't block merging the pr.
but unfortunately perf tests show more of a regression than a win [1](https://s3.amazonaws.com/clickhouse-test-reports/36095/0875fd087fc9f60c5d83d7eea2f3322b732b7ead/performance_comparison__actions__[1/4]/report.html), [2](https://s3.amazonaws.com/clickhouse-test-reports/36095/0875fd087fc9f60c5d83d7eea2f3322b732b7ead/performance_comparison__actions__[2/4]/report.html), [3](https://s3.amazonaws.com/clickhouse-test-reports/36095/0875fd087fc9f60c5d83d7eea2f3322b732b7ead/performance_comparison__actions__[3/4]/report.html), [4](https://s3.amazonaws.com/clickhouse-test-reports/36095/0875fd087fc9f60c5d83d7eea2f3322b732b7ead/performance_comparison__actions__[4/4]/report.html)

**Comment by jinjunzh** [comment]
> @jinjunzh yeap, tests failures seem irrelevant and don't block merging the pr. but unfortunately perf tests show more of a regression than a win [1](https://s3.amazonaws.com/clickhouse-test-reports/36095/0875fd087fc9f60c5d83d7eea2f3322b732b7ead/performance_comparison__actions__%5B1/4%5D/report.html), [2](https://s3.amazonaws.com/clickhouse-test-reports/36095/0875fd087fc9f60c5d83d7eea2f3322b732b7ead/performance_comparison__actions__%5B2/4%5D/report.html), [3](https://s3.amazonaws.com/clickhouse-test-reports/36095/0875fd087fc9f60c5d83d7eea2f3322b732b7ead/performance_comparison__actions__%5B3/4%5D/report.html), [4](https://s3.amazonaws.com/clickhouse-test-reports/36095/0875fd087fc9f60c5d83d7eea2f3322b732b7ead/performance_comparison__actions__%5B4/4%5D/report.html)

**Comment by jinjunzh** [comment]
> @jinjunzh yeap, tests failures seem irrelevant and don't block merging the pr. but unfortunately perf tests show more of a regression than a win [1](https://s3.amazonaws.com/clickhouse-test-reports/36095/0875fd087fc9f60c5d83d7eea2f3322b732b7ead/performance_comparison__actions__%5B1/4%5D/report.html), [2](https://s3.amazonaws.com/clickhouse-test-reports/36095/0875fd087fc9f60c5d83d7eea2f3322b732b7ead/performance_comparison__actions__%5B2/4%5D/report.html), [3](https://s3.amazonaws.com/clickhouse-test-reports/36095/0875fd087fc9f60c5d83d7eea2f3322b732b7ead/performance_comparison__actions__%5B3/4%5D/report.html), [4](https://s3.amazonaws.com/clickhouse-test-reports/36095/0875fd087fc9f60c5d83d7eea2f3322b732b7ead/performance_comparison__actions__%5B4/4%5D/report.html)



> @jinjunzh yeap, tests failures seem irrelevant and don't block merging the pr. but unfortunately perf tests show more of a regression than a win [1](https://s3.amazonaws.com/clickhouse-test-reports/36095/0875fd087fc9f60c5d83d7eea2f3322b732b7ead/performance_comparison__actions__%5B1/4%5D/report.html), [2](https://s3.amazonaws.com/clickhouse-test-reports/36095/0875fd087fc9f60c5d83d7eea2f3322b732b7ead/performance_comparison__actions__%5B2/4%5D/report.html), [3](https://s3.amazonaws.com/clickhouse-test-reports/36095/0875fd087fc9f60c5d83d7eea2f3322b732b7ead/performance_comparison__actions__%5B3/4%5D/report.html), [4](https://s3.amazonaws.com/clickhouse-test-reports/36095/0875fd087fc9f60c5d83d7eea2f3322b732b7ead/performance_comparison__actions__%5B4/4%5D/report.html)

**Comment by nickitat** [comment]
> I checked the queries regression in perf test and tried to run them on my local setup. I find they are not stable and even never run into my modified function: readbig. So i think it also irrelevant to my commit.

yeah, but what queries became faster?

**Comment by jinjunzh** [comment]
> 

Yes, It looks no perf boost by this commit, but actually the code logic in readBig need improve as this commit did, please look into "Detailed description"  in first comment for detailed logic and why it need to improve. 
Meanwhile, I changed  category from "Performence Improvement" to "Improvement".
If you still think worthless, let's drop it.

**Comment by nickitat** [comment]
maybe it would be better if we could avoid repeating this 
https://github.com/ClickHouse/ClickHouse/blob/ba112c230275e202c97598e43b1e976c03d3da97/src/Compression/CompressedReadBufferFromFile.cpp#L105-L110
for the back part of the block which fits? do it worth experimenting in your opinion?

**Comment by jinjunzh** [comment]
> 
@nickitat I don't think we can avoid repeating the section you mentioned because readCompressedData must be called for each block. Meanwhile, i fixed the expression error in my first comment that the words: "front" and "back"  reversed the order.
To make sure you don't have misunderstanding ,I attached a flow chart here
image

**Comment by jinjunzh** [comment]
@nickitat how do you think about this?

**Comment by nickitat** [comment]
> @nickitat how do you think about this?

sorry, I have not yet found time to look closely at the code (not really familiar with this part of the codebase), but I plan to do this soon since the proposed changes look good.

**Review by nickitat — APPROVED** [review]
lgtm

**Pull request merged**
