### PR TITLE
Improve performance of aggregate functions

### PR DESCRIPTION
**Pull request by alexey-milovidov**
Changelog category (leave one):
- Performance Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Improve performance of aggregate functions by more strict aliasing.

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
> AST fuzzer (UBSan) — ../src/Functions/GeoHash.cpp:299:24: runtime error: -5.96529e+07 is outside the range of representable values of type 'unsigned int' 

#19956

**Comment by alexey-milovidov** [comment]
>  @robot-clickhouse
Stress test (memory) — Sanitizer assert (in stderr.log) 

#19957

**Comment by alexey-milovidov** [comment]
1.6 times improvement.

**Comment by l1t1** [comment]
does this improve work on arm64 Linux?

**Comment by alexey-milovidov** [comment]
Yes, it is applicable for all architectures.

**Comment by weijietong** [comment]
@alexey-milovidov  I try to verify this performance gain by writing some codes which behave like what the Clickhouse HashAgg does. I don't find any remarkable performance improve. Could you explain why ? You could update the linked benchmark code. https://quick-bench.com/q/uTXRDkIgeHhi5qfhJshURx6jBts

The restric keyword seems to gain performance improvement to the case that acculate mulitple value to the same aggregation key in a for loop. But to Clickhouse, the addBatch()'s implementation does not work that way.

**Comment by azat** [comment]
@weijietong your benchmark a little bit different, I've adjusted it a little - [gcc](https://quick-bench.com/q/ub1aqhsngbG619vOsrKY6rMBrGk) and [clang](https://quick-bench.com/q/jE78p6Mwbbh4E9LH_Q5nR14VWcI)

This one shows the difference.

And this 20% gain (in ClickHouse and almost 3x in the bench, interesting fact that with -msse4.2 the difference is smaller) is due to loop unroll:

```
$ clang++ -Rpass-analysis=loop-vectorize -Rpass=loop-vectorize -O3 -g3 -lbenchmark -lbenchmark_main benchmark.cpp -o benchmark
# addBatchWithoutOpt
benchmark.cpp:33:7: remark: loop not vectorized: unsafe dependent memory operations in loop. Use #pragma loop distribute(enable) to allow loop distribution to attempt to isolate the offending operations into a separate loop [-Rpass-analysis=loop-vectorize]
      for (size_t i = 0; i < batch_size; ++i) {
# addWithoutOpt
benchmark.cpp:50:39: remark: loop not vectorized: value that could not be identified as reduction is used outside the loop [-Rpass-analysis=loop-vectorize]
    data_without_opt(state).numerator += args[0].data()[row_num];
# addBatch
benchmark.cpp:27:7: remark: vectorized loop (vectorization width: 2, interleaved count: 2) [-Rpass=loop-vectorize]
```

P.S. also quick-bench does not allow to enable SSE (`-msse4.2`), but this is not significant for this particular case.

**Comment by azat** [comment]
>but to clickhouse, it's impossible to actor as the codes you implemented. These's no way to make all the input rows have the same keys consecutive together then they aggregated into the same one AggregateDataPtr like what you write.See the Aggregator::executeImplBatch method,to know how the places was created.

It is possible w/o keys for group by, just like [performance test that had been added in this PR](https://github.com/ClickHouse/ClickHouse/pull/19946/files#diff-c15a297ac163d63da6d9250ef9fc28115f6c3eb7c2198f22d2323a780f4d09d2) - `SELECT avg(number) FROM numbers(1000000000)`

>Btw,how you benchmark the clickhouse to this improvement ? what's the benchmark code ?

[`tests/performance/avg.xml`](https://github.com/ClickHouse/ClickHouse/pull/19946/files#diff-c15a297ac163d63da6d9250ef9fc28115f6c3eb7c2198f22d2323a780f4d09d2) had been added, and there was performance tests run for this PR that compared this change to upstream/master and it is likely showed that 1.6x time improvement as reported by @alexey-milovidov (but results of that performance tests comparison is already not available since they had TTL).

**Comment by weijietong** [comment]
Even the performance improvement version [benchamark](https://quick-bench.com/q/ub1aqhsngbG619vOsrKY6rMBrGk), I compared their assembly codes,no difference found except the different jmp like codes. Really magic!

**Comment by azat** [comment]
There is difference, but for the different function (addBatchWithoutOpt and addBatch), that quick-bench doesn't show, since I've added noinline attribute for them (otherwise quick bench fails for me)

**Comment by weijietong** [comment]
@azat  I got why this improvement happend. This applied at the no group by cases. The _restric keyword will make different. Anyway, thanks for the reply.

**Pull request merged**
