### PR TITLE
Invert .clang-tidy

### PR DESCRIPTION
**Pull request by rschu1ze**
Instead of disabling all checks + specifying which are enabled
(whitelist), enable all checks + specify which checks are disabled
(blacklist). The same set of checks executes as before.

Motivation:

a) Given the goal to (generally) enable as many checks as possible, a
   blacklist produces a smaller and easier to maintain .clang-tidy file.

b) Many new checks introduced with LLVM 12/13/14 were forgotten to turn
   on. A blacklist makes sure that future compiler upgrades enable new
   checks by default.

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by qoega** [comment]
Nice, but current check failed.

**Comment by rschu1ze** [comment]
Will take care.
With so many different build options, I feel getting the CI builds green for the first try is a bit of dark magic 😁

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
Good.

Initially I did not enable all of them, because there are many product-specific checks (like Fuchsia) and some checks contradict with each other (pass by reference, pass by value).

**Comment by qoega** [comment]
At least tidy build should be green.

**Comment by rschu1ze** [comment]
CI builds use clang-tidy 13, I was using v14. I am fixing that right now.

**Comment by rschu1ze** [comment]
Clang-tidy build is green, test failures cannot be related --> merging.

**Pull request merged**
