### PR TITLE
Add function bankerRound

### PR DESCRIPTION
**Pull request by hczhcz**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- New Feature

Changelog entry (up to few sentences, required except for Non-significant/Documentation categories):
Add function `bankerRound` which performs banker's rounding

### CODE REVIEW

**Comment by hczhcz** [comment]
Related: #1211 #7044 #7315

**Comment by alexey-milovidov** [comment]
Ok. Could you please add performance test and check how slower the function is comparing to the existing round? If it's no slower, we can make it the default.

PS. Probably the better name is `bankersRound` instead of `bankerRound`?

**Comment by akuzm** [comment]
query | rps
-- | --
SELECT count() FROM system.numbers WHERE NOT ignore(round(toInt64(number), -2)) | (386154838 rps.) 
SELECT count() FROM system.numbers WHERE NOT ignore(bankersRound(toInt64(number), -2)) | (294367764 rps.) 

Looks like it's significantly slower for ints.

Overall, I think the code became somewhat complicated. I'd add banker's round as a new mode to RoundingMode, implement each mode for each type, make them accessible from SQL as bankersRound() & roundToInt() or something. And then for backwards compatibility write out our current round() as calls to bankers() for float or toInt() for others.

To add to the confusion, Intel does banker's round for floats, but calls it _MM_FROUND_TO_NEAREST_INT :thinking: 

A nice memo on rounding modes on different architectures: https://www.ocf.berkeley.edu/~horie/rounding.html

**Comment by alexey-milovidov** [comment]
> Overall, I think the code became somewhat complicated. I'd add banker's round as a new mode to RoundingMode, implement each mode for each type, make them accessible from SQL as bankersRound() & roundToInt() or something. And then for backwards compatibility write out our current round() as calls to bankers() for float or toInt() for others.

We can make it in the following steps:
1. Add `bankersRound` function (or: it should be called `roundBankers`, see below).
2. Add `roundHalfToGreater` function (the name can be better; but definitely not roundToInt).
3. Make `round` function consistent in mode for integers and floats.

This PR is good for step 1 and we can merge it.

PS.
> Intel does banker's round for floats, but calls it _MM_FROUND_TO_NEAREST_INT

Yes, that's very convenient, and it's documented (*almost* correctly)
https://clickhouse.yandex/docs/en/query_language/functions/rounding_functions/#rounding_functions-round

**Comment by hczhcz** [comment]
I would suggest `roundHalfUp`.
And maybe `roundHalfDown`, `roundHalfTowardZero`, and `roundHalfTowardInfinity` if people really need them.

**Comment by alexey-milovidov** [comment]
Current implementation is "round half towards higer absolute value":

```
milovidov-Pro-P30 :) SELECT round(15, -1)

SELECT round(15, -1)

┌─round(15, -1)─┐
│            20 │
└───────────────┘

1 rows in set. Elapsed: 0.020 sec. 

milovidov-Pro-P30 :) SELECT round(-15, -1)

SELECT round(-15, -1)

┌─round(-15, -1)─┐
│            -20 │
└────────────────┘
```

**Review by alexey-milovidov — APPROVED** [review]

**Comment by BayoNet** [comment]
Does this result is correct?
```
SELECT roundBankers(45.33, -1)

┌─roundBankers(45.33, -1)──┐
│                      50                    │
└──────────────────┘
```

**Comment by alexey-milovidov** [comment]
@BayoNet Yes, it is. Because the value is greater than the half (45).

**Comment by alexey-milovidov** [comment]
```
SELECT roundBankers(45., -1)

┌─roundBankers(45., -1)─┐
│                    40 │
└───────────────────────┘
```

**Pull request merged**
