### PR TITLE
Fix gpg fetch command for Ubuntu/Debian

### PR DESCRIPTION
**Pull request by Holi0317**
### Changelog category (leave one):
- Documentation (changelog entry is not required)

### Documentation entry for user-facing changes

- [x] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

Was trying to use the gpg command in CH documentation and I got this error from a fresh Ubuntu 22.04 instance on AWS:

```bash
$ sudo gpg --no-default-keyring --keyring /usr/share/keyrings/clickhouse-keyring.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 8919F6BD2B48D754

gpg: keybox '/usr/share/keyrings/clickhouse-keyring.gpg' created                                     
gpg: failed to create temporary file '/root/.gnupg/.#lk0x0000aaaaf03cc0e0.ip-10-10-210-237.1198': No such file or directory
gpg: connecting dirmngr at '/root/.gnupg/S.dirmngr' failed: No such file or directory              
gpg: keyserver receive failed: No dirmngr
```

And the key was not written to `/usr/share/keyrings/clickhouse-keyring.gpg`

I found this snippet from StackExchange for downloading the gpg key without modifying keyring: https://superuser.com/a/1801970

CC @peter279k @Felixoid

### CODE REVIEW

**Comment by peter279k** [comment]
According to the `gpg: keyserver receive failed: No dirmngr` error, it should need to install the `dirmngr` pacakage.

Please look at the [reference](https://clickhouse.com/docs/en/guides/troubleshooting#canot-import-gpg-keys-from-keyserverubuntucom-with-gpg).

**Comment by Felixoid** [comment]
@peter279k this [simplification](https://github.com/ClickHouse/ClickHouse/commit/440d29ce9e6dcadde63fe819b5ba9b510ab1bb6d) actually breaks the and leaves leftovers.

The reason for having a temporary `GPGHOME` is to remove everything and leave the root directory untouched. 

The new documentation doesn't work indeed

```
> docker run -it --rm ubuntu:22.04 bash
root@1bed8b42dae7:/# apt update &> /dev/null
root@1bed8b42dae7:/# apt-get install -y apt-transport-https ca-certificates dirmngr &> /dev/null
root@1bed8b42dae7:/# gpg --no-default-keyring --keyring /usr/share/keyrings/clickhouse-keyring.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 8919F6BD2B48D754
gpg: keybox '/usr/share/keyrings/clickhouse-keyring.gpg' created
gpg: failed to create temporary file '/root/.gnupg/.#lk0x00005e63e9db7db0.1bed8b42dae7.2919': No such file or directory
gpg: connecting dirmngr at '/root/.gnupg/S.dirmngr' failed: No such file or directory
gpg: keyserver receive failed: No dirmngr
```

comparing to the old one:

```
root@1bed8b42dae7:/# GNUPGHOME=$(mktemp -d)
root@1bed8b42dae7:/# GNUPGHOME="$GNUPGHOME" gpg --no-default-keyring --keyring /usr/share/keyrings/clickhouse-keyring.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 8919F6BD2B48D754
gpg: /tmp/tmp.FbPoiYGcvn/trustdb.gpg: trustdb created
gpg: key 8919F6BD2B48D754: public key "ClickHouse Inc. Repositories Key <packages@clickhouse.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1
root@1bed8b42dae7:/# rm -rf "$GNUPGHOME"
root@1bed8b42dae7:/# ls -l /usr/share/keyrings/clickhouse-keyring.gpg
-rw-r--r-- 1 root root 4203 Mar 12 10:08 /usr/share/keyrings/clickhouse-keyring.gpg
root@1bed8b42dae7:/# chmod +r /usr/share/keyrings/clickhouse-keyring.gpg
root@1bed8b42dae7:/# ls -l /usr/share/keyrings/clickhouse-keyring.gpg
-rw-r--r-- 1 root root 4203 Mar 12 10:08 /usr/share/keyrings/clickhouse-keyring.gpg
```

Let's make it work in a fresh container if you'd like to keep it like that. But I wouldn't say I like the current one. It leaves the user's environment dirty and assumes something in advance.

**Comment by peter279k** [comment]
The `gpg` command in the  `Ubuntu` with Docker image version is not initialized for creating the gnupg home directory.

By default, the `gpg` command needs to create the `.gnupg` directory in the home directory.

If not, the're two ways to resolve the following issue:

First approach:

```sh
$ docker run -it --rm ubuntu:22.04 bash
root@f3472ac60dbc:/# apt-get update
root@f3472ac60dbc:/# apt-get install -y apt-transport-https ca-certificates dirmngr
root@f3472ac60dbc:/# mkdir /root/.gnupg
root@f3472ac60dbc:/# chmod -R 700 /root/.gnupg
root@f3472ac60dbc:/# gpg --no-default-keyring --keyring /usr/share/keyrings/clickhouse-keyring.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 8919F6BD2B48D754
gpg: /root/.gnupg/trustdb.gpg: trustdb created
gpg: key 8919F6BD2B48D754: public key "ClickHouse Inc. Repositories Key <packages@clickhouse.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1
```

Second approach:

```sh
$ docker run -it --rm ubuntu:22.04 bash
root@f313ef811406:/# apt-get update
root@f313ef811406:/# apt-get install -y apt-transport-https ca-certificates dirmngr
root@f313ef811406:/# gpg --check-trustdb
gpg: directory '/root/.gnupg' created
gpg: keybox '/root/.gnupg/pubring.kbx' created
gpg: /root/.gnupg/trustdb.gpg: trustdb created
gpg: no ultimately trusted keys found
root@f313ef811406:/# gpg --no-default-keyring --keyring /usr/share/keyrings/clickhouse-keyring.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 8919F6BD2B48D754
gpg: keybox '/usr/share/keyrings/clickhouse-keyring.gpg' created
gpg: key 8919F6BD2B48D754: public key "ClickHouse Inc. Repositories Key <packages@clickhouse.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1
```

**Comment by Felixoid** [comment]
So, we either reflect it in the documentation to spoil the user's data or create a temporary directory. However, the current documentation is not complete.

I prefer a way to make it without leftovers.

**Comment by peter279k** [comment]
I found another way to import GPG keys for `apt`:

```sh
$ docker run -it --rm ubuntu:22.04 bash
root@c021065a4705:/# apt-get update
root@c021065a4705:/# apt-get install -y ca-certificates curl
root@c021065a4705:/# curl -fsSL 'https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x8919f6bd2b48d754' -o /etc/apt/keyrings/clickhouse.asc
root@c021065a4705:/# chmod a+r /etc/apt/keyrings/clickhouse.asc
root@c021065a4705:/# echo "deb [signed-by=/etc/apt/keyrings/clickhouse.asc] https://packages.clickhouse.com/deb stable main" | tee /etc/apt/sources.list.d/clickhouse.list
root@c021065a4705:/# apt-get update
Hit:1 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:2 http://security.ubuntu.com/ubuntu jammy-security InRelease
Get:3 https://packages.clickhouse.com/deb stable InRelease [2490 B]
Get:4 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [119 kB]
Hit:5 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Get:6 https://packages.clickhouse.com/deb stable/main amd64 Packages [118 kB]
Fetched 237 kB in 3s (85.8 kB/s)
Reading package lists... Done
```

If we need to be convenient and ignore remaining leftovers for many Debian-based distributions, this approach can also be considered.

**Comment by Felixoid** [comment]
Using curl is a so-so solution, but sticking to a custom API of an external provider sounds, well, not so nice.

With the same result, we can use our own [key](https://packages.clickhouse.com/rpm/lts/repodata/repomd.xml.key) from https://packages.clickhouse.com/rpm/lts/repodata/ or put it somewhere in https://packages.clickhouse.com/deb

The nice thing, keys in [lts](https://packages.clickhouse.com/rpm/lts/repodata/repomd.xml.key) and [stable](https://packages.clickhouse.com/rpm/stable/repodata/repomd.xml.key) rpm repositories are alredy the most [fresh](https://github.com/ClickHouse/clickhouse-repos-manager/blob/eb26257/clickhouse-repos-manager/repos.py#L164-L167) and we don't need anything else.

**Comment by Felixoid** [comment]
but don't forget testing it in an older versions

```
> docker run -it --rm ubuntu:16.04 bash
Unable to find image 'ubuntu:16.04' locally
16.04: Pulling from library/ubuntu
58690f9b18fc: Pull complete
b51569e7c507: Pull complete
da8ef40b9eca: Pull complete
fb15d46c38dc: Pull complete
Digest: sha256:1f1a2d56de1d604801a9671f301190704c25d604a416f59e03c04f5c6ffee0d6
Status: Downloaded newer image for ubuntu:16.04
root@2f409f957416:/# apt update &> /dev/null && apt-get install -y apt-transport-https ca-certificates curl &> /dev/nullroot@2f409f957416:/# curl -fsSL https://packages.clickhouse.com/rpm/stable/repodata/repomd.xml.key -o /etc/apt/keyrings/clickhouse.asc
curl: (23) Failed writing body (0 != 978)
root@2f409f957416:/# mkdir /etc/apt/keyrings
root@2f409f957416:/# curl -fsSL https://packages.clickhouse.com/rpm/stable/repodata/repomd.xml.key -o /etc/apt/keyrings/clickhouse.asc
root@2f409f957416:/# echo "deb [signed-by=/etc/apt/keyrings/clickhouse.asc] https://packages.clickhouse.com/deb stable main" | tee /etc/apt/sources.list.d/clickhouse.list
deb [signed-by=/etc/apt/keyrings/clickhouse.asc] https://packages.clickhouse.com/deb stable main
root@2f409f957416:/# apt update
Get:1 https://packages.clickhouse.com/deb stable InRelease [2490 B]
Err:1 https://packages.clickhouse.com/deb stable InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 3E4AD4719DDE9A38
Hit:2 http://security.ubuntu.com/ubuntu xenial-security InRelease
Hit:3 http://archive.ubuntu.com/ubuntu xenial InRelease
Hit:4 http://archive.ubuntu.com/ubuntu xenial-updates InRelease
Hit:5 http://archive.ubuntu.com/ubuntu xenial-backports InRelease
Reading package lists... Done
W: GPG error: https://packages.clickhouse.com/deb stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 3E4AD4719DDE9A38
E: The repository 'https://packages.clickhouse.com/deb stable InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Comment by Felixoid** [comment]
The previous version of documentation works there:

```
> docker run --network=host -it --rm ubuntu:16.04 bash
root@slim-click:/# apt update &> /dev/null ; apt-get install -y apt-transport-https ca-certificates curl dirmngr &> /dev/null
root@slim-click:/# GNUPGHOME=$(mktemp -d); GNUPGHOME="$GNUPGHOME" gpg --no-default-keyring --keyring /usr/share/keyrings/clickhouse-keyring.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 8919F6BD2B48D754
gpg: keyring `/tmp/tmp.YWNU9QAtWj/secring.gpg' created
gpg: keyring `/usr/share/keyrings/clickhouse-keyring.gpg' created
gpg: requesting key 2B48D754 from hkp server keyserver.ubuntu.com
gpg: /tmp/tmp.YWNU9QAtWj/trustdb.gpg: trustdb created
gpg: key 2B48D754: public key "ClickHouse Inc. Repositories Key <packages@clickhouse.com>" imported
gpg: key 2B48D754: no user ID for key signature packet of class 10
gpg: key 2B48D754: no user ID for key signature packet of class 10
gpg: no ultimately trusted keys found
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
root@slim-click:/# rm -rf "$GNUPGHOME"
root@slim-click:/# echo "deb [signed-by=/usr/share/keyrings/clickhouse-keyring.gpg] https://packages.clickhouse.com/deb stable main" | tee     /etc/apt/sources.list.d/clickhouse.list
deb [signed-by=/usr/share/keyrings/clickhouse-keyring.gpg] https://packages.clickhouse.com/deb stable main
root@slim-click:/# apt-get update
Hit:1 http://security.ubuntu.com/ubuntu xenial-security InRelease
Get:2 https://packages.clickhouse.com/deb stable InRelease [2490 B]
Hit:3 http://archive.ubuntu.com/ubuntu xenial InRelease
Ign:2 https://packages.clickhouse.com/deb stable InRelease
Get:4 https://packages.clickhouse.com/deb stable/main amd64 Packages [118 kB]
Hit:5 http://archive.ubuntu.com/ubuntu xenial-updates InRelease
Hit:6 http://archive.ubuntu.com/ubuntu xenial-backports InRelease
Fetched 120 kB in 0s (204 kB/s)
Reading package lists... Done
W: GPG error: https://packages.clickhouse.com/deb stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 3E4AD4719DDE9A38
W: The repository 'https://packages.clickhouse.com/deb stable InRelease' is not signed.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
root@slim-click:/# chmod +r /usr/share/keyrings/clickhouse-keyring.gpg
root@slim-click:/# apt-get update
Hit:1 http://security.ubuntu.com/ubuntu xenial-security InRelease
Hit:2 http://archive.ubuntu.com/ubuntu xenial InRelease
Hit:3 http://archive.ubuntu.com/ubuntu xenial-updates InRelease
Hit:4 http://archive.ubuntu.com/ubuntu xenial-backports InRelease
Get:5 https://packages.clickhouse.com/deb stable InRelease [2490 B]
Fetched 2490 B in 0s (4601 B/s)
Reading package lists... Done
```

**Comment by peter279k** [comment]
Thanks for your reply, here is the fixed approach and it's successful in the older version (it's worked in the new version):

For the `Ubuntu 16.04`:

```sh
$ docker run -it --rm ubuntu:16.04 bash
root@cac71a1d4d16:/# apt update &> /dev/null && apt-get install -y apt-transport-https ca-certificates curl gpg &> /dev/null
root@cac71a1d4d16:/# curl -fsSL 'https://packages.clickhouse.com/rpm/lts/repodata/repomd.xml.key' | gpg --dearmor -o /usr/share/keyrings/clickhouse.gpg
root@cac71a1d4d16:/# echo "deb [signed-by=/usr/share/keyrings/clickhouse.gpg] https://packages.clickhouse.com/deb stable main" | tee /etc/apt/sources.list.d/clickhouse.list
root@cac71a1d4d16:/# apt update
Hit:1 http://security.ubuntu.com/ubuntu xenial-security InRelease
Get:2 https://packages.clickhouse.com/deb stable InRelease [2490 B]
Hit:3 http://archive.ubuntu.com/ubuntu xenial InRelease
Hit:4 http://archive.ubuntu.com/ubuntu xenial-updates InRelease
Hit:5 http://archive.ubuntu.com/ubuntu xenial-backports InRelease
Fetched 2490 B in 1s (2385 B/s)
Reading package lists... Done
Building dependency tree
Reading state information... Done
2 packages can be upgraded. Run 'apt list --upgradable' to see them.
```

For the `Ubuntu 22.04`:

```sh
$ docker run -it --rm ubuntu:22.04 bash
root@bd464a38e350:/# apt update &> /dev/null && apt-get install -y apt-transport-https ca-certificates curl gpg &> /dev/null
root@bd464a38e350:/# curl -fsSL 'https://packages.clickhouse.com/rpm/lts/repodata/repomd.xml.key' | gpg --dearmor -o /usr/share/keyrings/clickhouse.gpg
root@bd464a38e350:/# apt update
Get:1 https://packages.clickhouse.com/deb stable InRelease [2490 B]
Hit:2 http://archive.ubuntu.com/ubuntu jammy InRelease
Get:3 https://packages.clickhouse.com/deb stable/main amd64 Packages [118 kB]
Hit:4 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:5 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:6 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Fetched 120 kB in 1s (101 kB/s)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
1 package can be upgraded. Run 'apt list --upgradable' to see it.
```

**Comment by Holi0317** [comment]
Seems @peter279k got a solution. Maybe you can open a PR instead? Don't want to take credit for the work I didn't do lol.

**Comment by peter279k** [comment]
> Seems @peter279k got a solution. Maybe you can open a PR instead? Don't want to take credit for the work I didn't do lol.

Thanks for reporting the issue! I appreciate that 🙏.

**Pull request closed without merging**
