### PR TITLE
Update DiskS3.cpp

### PR DESCRIPTION
**Pull request by KochetovNicolai**
Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by nickitat** [comment]
pls provide a description

**Comment by KochetovNicolai** [comment]
Continuation of #34734

**Comment by KochetovNicolai** [comment]
@mergifyio update

**Comment by KochetovNicolai** [comment]
Crash in stresstest should be fixed in #34963, let's check

**Pull request merged**
