### PR TITLE
fix issue#50582 Not found column NULL in block

### LINKED ISSUE #50582: Unexpected error: Not found column NULL in block
**Describe what's wrong**

The two SELECT statements should output the same results, but one of them throws an exception.

**Does it reproduce on recent release?**

It can be reproduced in the latest version.

**How to reproduce**

Version: 23.5.1 (commit eb5985e5fc0e83c94aa1af134f2718e9fe87979c)

Easy reproduce in ClickHouse fiddle: https://fiddle.clickhouse.com/11823026-1268-4336-b744-7729f9025eeb

_Set up database_

```sql
create table t0 (vkey UInt32, c0 Float32, primary key(c0)) engine = AggregatingMergeTree;
insert into t0 values (19000, 1);
```

_SELECT statement 1_

```sql
select 
    null as c_2_0, 
    ref_2.c0 as c_2_1, 
    ref_2.vkey as c_2_2 
  from 
    t0 as ref_2
  order by c_2_0 asc, c_2_1 asc, c_2_2 asc;
```
Then, I remove `c_2_2 asc` in the ORDER BY. The number of outputted rows should not be changed.

_SELECT statement 2_

```sql
select 
    null as c_2_0, 
    ref_2.c0 as c_2_1, 
    ref_2.vkey as c_2_2 
  from 
    t0 as ref_2
  order by c_2_0 asc, c_2_1 asc;
```

**Expected behavior**

The two SELECT statements output the same results, or both of them throw the same exceptions.

**Actual behavior**

One outputs a row, and another one throws an exception.

SELECT statement 1 throws an exception:
```
Received exception from server (version 23.4.2):
Code: 10. DB::Exception: Received from localhost:9000. DB::Exception: Not found column NULL in block. There are only columns: vkey, c0. (NOT_FOUND_COLUMN_IN_BLOCK)
(query: select 
    null as c_2_0, 
    ref_2.c0 as c_2_1, 
    ref_2.vkey as c_2_2 
  from 
    t0 as ref_2
  order by c_2_0 asc, c_2_1 asc, c_2_2 asc;)
```

SELECT statement 2 outputs:
```
+-------+-------+-------+
| c_2_0 | c_2_1 | c_2_2 |
+-------+-------+-------+
| NULL  |     1 | 19000 |
+-------+-------+-------+
```

**Additional context**

The earliest reproducible version is 22 in fiddle: https://fiddle.clickhouse.com/a7482d31-b9f8-44bc-88e7-30368913c35d

Before version 22, both SELECT statements output one row (e.g., 21.12.4.1 https://fiddle.clickhouse.com/9aedf68b-3928-4b23-ae48-e61d21ba75bf)

### PR DESCRIPTION
**Pull request by Chen768959**
Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
- Fix #50582. Avoid the `Not found column ... in block` error in some cases of reading in-order and constants.

The buildInputOrderInfo() method in optimizeReadInOrder.cpp adds constant columns to order_key_prefix_descr.
However, since header_without_constants does not contain constant columns.
as issue #50582, an error “Unexpected error: Not found column xxx in block” occurs when constant columns are present in order_key_prefix_descr. Therefore, it is necessary to remove constant columns from description_sorted_ in advance.

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
It needs a test.

**Comment by robot-ch-test-poll3** [comment]
This is an automated comment for commit 9b7ecbaa277bc29962cccd1e0faf379fbbef36af with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/52259/9b7ecbaa277bc29962cccd1e0faf379fbbef36af/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Comment by Chen768959** [comment]
> It needs a test.

ok

**Comment by Chen768959** [comment]
> It needs a test.

hello, I have added the necessary tests. Please let me know if there is anything else I can add to the PR.

**Comment by Chen768959** [comment]
It seems that running the 01655_plan_optimizations_optimize_read_in_window_order_long test case does indeed result in a "Memory limit" exception. I will investigate and resolve the issue.

**Review by alexey-milovidov — APPROVED** [review]

**Pull request merged**
