### PR TITLE
Try to fix failed tests

### PR DESCRIPTION
**Pull request by Avogar**
Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by azat** [comment]
Let's also apply this change then (this problem also had been introduced in #34092):

```patch
$ git diff
diff --git a/tests/clickhouse-test b/tests/clickhouse-test
index 4c94e4d6493..121a283d0e4 100755
--- a/tests/clickhouse-test
+++ b/tests/clickhouse-test
@@ -446,7 +446,7 @@ class TestCase:
         else:
             os.environ['CLICKHOUSE_URL_PARAMS'] = self.base_url_params + '&' + '&'.join(self.random_settings)
 
-        new_options = "--allow_repeated_settings --" + " --".join(self.random_settings)
+        new_options = " --allow_repeated_settings --" + " --".join(self.random_settings)
         os.environ['CLICKHOUSE_CLIENT_OPT'] = self.base_client_options + new_options + ' '
         return client_options + new_options
```

**Comment by alexey-milovidov** [comment]
Looks like this is for

```
00001_select_1:                                                         [ FAIL ] - return code: 1
Code: 27. DB::ParsingException: Cannot parse input: expected 'eof' before: '--allow_repeated_settings'. (CANNOT_PARSE_INPUT_ASSERTION_FAILED)
```

As we have failed "hung check" in stress test in master.

**Comment by alexey-milovidov** [comment]
Fast test: https://github.com/ClickHouse/ClickHouse/pull/35050

**Comment by alexey-milovidov** [comment]
@mergifyio update

**Review by alexey-milovidov — APPROVED** [review]

**Pull request merged**
