### PR TITLE
ClusterCopier: refine zxid definition

### PR DESCRIPTION
**Pull request by dingxiangfei2009**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Bug Fix

Changelog entry (up to few sentences, required except for Non-significant/Documentation categories):
Refine the definition of ZXid according to the ZooKeeper Programmer's Guide.

...

Detailed description (optional):
Sorry for making this pull request so late. As explained in an earlier session, the 64-bit Zxids should be interpreted as [two wrapping 32-bit unsigned integers](https://github.com/apache/zookeeper/blob/631d1b284f0edb1c4f6b0fb221bf2428aec71aaa/zookeeper-docs/src/main/resources/markdown/zookeeperInternals.md#guarantees-properties-and-definitions). A simple numerical comparison between two Zxids cannot establish a "causal" relation correctly, which currently the `ClusterCopier` depends on. Therefore, this request is to rectify the related constructions to reflect this fact.
...

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]
Ok.

Could you please also add a comment with a link to info about it? Somewhere near ZK docs...

PS. Is the name "warping" correct? Maybe "wrapping" is more appropriate?

**Comment by alexey-milovidov** [comment]
I have added a comment. Please check that I understand the changes correctly :)

**Comment by dingxiangfei2009** [comment]
Oh, sorry. Yes, I should have used "wrapping".
Thanks for the help. :+1:

**Comment by dingxiangfei2009** [comment]
A reference to the "ZooKeeper Internals" manual is included in the comment, which is a permanent link to the section on the definitions.

**Pull request merged**
