### PR TITLE
Add documentation for minSampleSizeConversion and minSampleSizeContinous

### PR DESCRIPTION
**Pull request by caffeinated-koala**
Added descriptions for two previously undocumented functions, `minSampleSizeConversion` and `minSampleSizeContinous`, released in ClickHouse 22.4.

### Changelog category
- Documentation (changelog entry is not required)

### CODE REVIEW

**Comment by robot-ch-test-poll4** [comment]
*This is an automated comment for commit c59d7003924bdf2f2769db0b04558ecfe301b5a2 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/56138/c59d7003924bdf2f2769db0b04558ecfe301b5a2/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td><a href="https://github.com/ClickHouse/ClickHouse/actions/runs/6698141209">✅ success</a></td></tr>
<tbody>
</table>
</details>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/56138/c59d7003924bdf2f2769db0b04558ecfe301b5a2/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Comment by nikitamikhaylov** [comment]
What about typo which will be fixed in https://github.com/ClickHouse/ClickHouse/pull/56143 ?

**Comment by crackhead-koala** [comment]
@nikitamikhaylov
Updated the file to reflect new changes

**Comment by crackhead-koala** [comment]
@nikitamikhaylov hi! Can this PR be merged? The CI shows all checks passed

**Review by nikitamikhaylov — APPROVED** [review]

**Pull request merged**
