### PR TITLE
Improvements in PODArray, variant 2

### PR DESCRIPTION
**Pull request by alexey-milovidov**
Changelog category (leave one):
- Not for changelog (changelog entry is not required)

The same as #12278 but without a change that should affect performance in gcc build.

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
@akuzm The result of performance test is not published.

**Comment by akuzm** [comment]
> @akuzm The result of performance test is not published.

It's probably the S3 quota troubles, and also the fact that the CI is overloaded and the perf test tasks wait in queue for more than a day sometimes. There is a workaround to get it sooner -- click 'Details' and increase the task priority manually (i've done that already for this one).

**Comment by alexey-milovidov** [comment]
Results of performance test has been changed exactly as in https://github.com/ClickHouse/ClickHouse/pull/12443

**Comment by alexey-milovidov** [comment]
Performance test has shown that QPS on concurrent benchmark is improved.

```
queries/s | 0.892 | 1.035 | 0.161 | x1.161
```
But I did not change anything for it.

And the full performance report did not build.

**Comment by akuzm** [comment]
parallel_final_2_scatter_2d_PerfBranchInstructions_per_client_time
parallel_final_2_scatter_2d_PerfBranchMisses_per_client_time

We're seeing more branch misses. Judging by the flame graph, it's this one https://github.com/ClickHouse/ClickHouse/blob/master/src/Columns/ColumnVector.cpp#L396, but why...

**Comment by alexey-milovidov** [comment]
@akuzm We still have a chance to improve performance of clang build.
And to avoid overallocation...

**Comment by akuzm** [comment]
> @akuzm We still have a chance to improve performance of clang build.
> And to avoid overallocation...

I think I've merged all parts related to overallocation. I don't know about the clang performance, so I made a comparison with clang 10 in CI: https://clickhouse-test-reports.s3.yandex.net/13617/d293dfcee1dfb6b2686bba1d91246862d50158fa/performance_comparison/report.html#fail1

The report is kinda bad and I couldn't understand much from it. The normal report is not very helpful here, because it is designed to catch a slowdown in some queries. We need to invent some other kind of report to compare different releases or compilers.

**Comment by alexey-milovidov** [comment]
Ok, thank you!

**Pull request closed without merging**
