### PR TITLE
Support compress marks and primary key

### LINKED ISSUE #34437: It makes sense to compress marks and primary.idx
**Describe the issue**
```
root@ip-172-31-22-38:/opt/clickhouse/store/308/30855e33-a73f-481b-942c-04710e028fe9# find . -name *.mrk2 | xargs wc -c
7602201768 total
root@ip-172-31-22-38:/opt/clickhouse/store/308/30855e33-a73f-481b-942c-04710e028fe9# find . -name *.mrk2 | xargs cat | clickhouse-compressor | wc -c
1367956184
root@ip-172-31-22-38:/opt/clickhouse/store/308/30855e33-a73f-481b-942c-04710e028fe9# find . -name *.mrk2 | xargs cat | clickhouse-compressor --codec 'ZSTD' | wc -c
455141209
root@ip-172-31-22-38:/opt/clickhouse/store/308/30855e33-a73f-481b-942c-04710e028fe9# find . -name *.mrk2 | xargs cat | clickhouse-compressor --codec 'ZSTD(3)' | wc -c
364667373
root@ip-172-31-22-38:/opt/clickhouse/store/308/30855e33-a73f-481b-942c-04710e028fe9# find . -name primary.idx | xargs wc -c
1184498877 total
root@ip-172-31-22-38:/opt/clickhouse/store/308/30855e33-a73f-481b-942c-04710e028fe9# find . -name primary.idx | xargs cat | clickhouse-compressor | wc -c
756816544
root@ip-172-31-22-38:/opt/clickhouse/store/308/30855e33-a73f-481b-942c-04710e028fe9# find . -name primary.idx | xargs cat | clickhouse-compressor --codec 'ZSTD' | wc -c
602538200
root@ip-172-31-22-38:/opt/clickhouse/store/308/30855e33-a73f-481b-942c-04710e028fe9# find . -name primary.idx | xargs cat | clickhouse-compressor --codec 'ZSTD(3)' | wc -c
552119618
```

In this example, marks compressed 20 times and primary key - 2 times.
That's a huge difference if they are loaded over slow network (example: using MergeTree over `web` disk plugged on my desktop).

### PR DESCRIPTION
**Pull request by zhongyuankai**
### Changelog category (leave one):
- Performance Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Implement compress marks and primary key. close  #34437.

### CODE REVIEW

**Comment by zhongyuankai** [comment]
@alexey-milovidov Hi, can you help me review it

**Comment by alexey-milovidov** [comment]
Thank you! The tests are 100% green, and I really need this feature. Strange that no one else took it for review. I will help reviewing.

**Comment by zhongyuankai** [comment]
Thank you for your reply, hope to get help to complete this feature.

**Comment by alexey-milovidov** [comment]
I've started reviewing, and made some modifications to lower duplication: #40715

I've also tried to push into your fork, but it pushed too much, so I will continue in a separate PR.
When #40715 will be merged, your PR will also be automatically merged.

**Comment by alexey-milovidov** [comment]
There is a scenario when I have an already created table and want to switch to compressed/uncompressed marks/primary key for new data parts. I will check what will happen. Not sure if it's supported.

**Comment by zhongyuankai** [comment]
> I've started reviewing, and made some modifications to lower duplication: #40715
> 
> I've also tried to push into your fork, but it pushed too much, so I will continue in a separate PR. When #40715 will be merged, your PR will also be automatically merged.

Thanks for your reply, I will keep working on the new branch.

**Comment by zhongyuankai** [comment]
> There is a scenario when I have an already created table and want to switch to compressed/uncompressed marks/primary key for new data parts. I will check what will happen. Not sure if it's supported.

Compressed/uncompressed can be switched, I will continue to add tests

**Comment by alexey-milovidov** [comment]
Does not work (yet):

```
$ clickhouse-client --echo -n < 02416_compress_marks_dynamic.sql 
DROP TABLE IF EXISTS test;
CREATE TABLE test (a UInt64, b String) ENGINE = MergeTree order by (a, b);
INSERT INTO test VALUES (1, 'Hello');
ALTER TABLE test MODIFY SETTING compress_marks = true, compress_primary_key = true;
INSERT INTO test VALUES (2, 'World');
SELECT * FROM test ORDER BY a;
Received exception from server (version 22.9.1):
Code: 432. DB::Exception: Received from localhost:9000. DB::Exception: Unknown codec family code: 42: While executing MergeTreeInOrder. (UNKNOWN_CODEC)
(query: SELECT * FROM test ORDER BY a;)
```

**Comment by zhongyuankai** [comment]
> Does not work (yet):

I have fixed it, but how do I commit the code to the new branch, it seems that I don't have enough permissions.

**Comment by alexey-milovidov** [comment]
@zhongyuankai I've pushed my changes to your branch, now you can push your changes to this branch :)

**Comment by zhongyuankai** [comment]
@alexey-milovidov Hi, can you help to continue the review, the failed test doesn't seem to be related to the change.

**Comment by alexey-milovidov** [comment]
Yes, looks like the tests are perfectly green!

**Comment by alexey-milovidov** [comment]
The code became complicated and fragile.
I will need a few more days for review.

**Comment by zhongyuankai** [comment]
Awesome, the code has become more readable.

**Comment by alexey-milovidov** [comment]
Thank you! Just some final steps and it will be ready for merge!

**Comment by alexey-milovidov** [comment]
Wow, it's merged :)

**Comment by zhongyuankai** [comment]
Great, got a lot, thank you.

**Pull request merged**
