### PR TITLE
Upgrade rocksdb version to v9.2.2

### PR DESCRIPTION
**Pull request by canhld94**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
- Upgrade rocksdb library version to v9.2.2

Main motivation is because current rocksdb version is too old. Once we have some SST files built by default bookworm rocksdb (8.10 iirc) and it cannot be read by ClickHouse rocksdb engine.

In addition, as discussed in https://github.com/ClickHouse/ClickHouse/pull/66479, upgrading from current version -> 9.2.2 will introduce 2 breaking changes:
1. In version [6.27.0](https://github.com/facebook/rocksdb/blob/main/HISTORY.md#new-features-30) new hash type `kXXH3` was added. Then in [v7.8.0](https://github.com/facebook/rocksdb/blob/main/HISTORY.md#public-api-changes-19) `kXXH3` was made default.
2. Same, current version `format_version` is `5`, but from in version 8.x `format_version = 6` was introduced and made by default.

So we try to keep the new version data compatible with current version data (just in case anyone need to rollback) by explicitly set:
```
table_options.checksum = rocksdb::ChecksumType::kxxHash64;
table_options.format_version = 5;
``` 
When the new version is stable, we can remove above code and use default value in rocksdb 9.2.2.

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by canhld94** [comment]
cc @rschu1ze 
Currently I'm using rocksdb repo at https://github.com/canhld94/rocksdb/tree/clickhouse/v9.2.2 (v9.2.2 + some extra commits from ClickHouse repo). Can you help to move it to https://github.com/ClickHouse/rocksdb [THANKS].

**Comment by robot-clickhouse-ci-1** [comment]
*This is an automated comment for commit 22b8e6ee98ec96cec5caa91568bebbc0c74b1271 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/67274/22b8e6ee98ec96cec5caa91568bebbc0c74b1271/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

**Comment by canhld94** [comment]
Re. failing test:

I don't understand yet why we explicitly set rocksdb log level to error, but the warning messages still being printed:

```
2024-07-28 08:08:51 Reason: having stderror:  
2024-07-28 08:08:51 [9d89e5687183] 2024.07.28 05:08:48.177662 [ 51097 ] {131ea5f5-19c6-433c-b959-1a40c4e674e1} <Warning> StorageEmbeddedRocksDB (test_6uvtfta1.dict_with_ttl (bc57c65f-fb09-4e93-9b5c-bbe1d2e7e371)): [table/block_based/block_based_table_reader.cc:863] Tail prefetch size 524288 is calculated based on heuristics
2024-07-28 08:08:51 
2024-07-28 08:08:51 stdout:
2024-07-28 08:08:51 0	foo
2024-07-28 08:08:51 0
```

May be @azat do you have any idea?

**Comment by canhld94** [comment]
> Re. failing test in [https://s3.amazonaws.com/clickhouse-test-reports/67274/f84e2d29482879aeedb70af9d89f1014df787c6d/stateless_tests__asan__[1_2].html](https://s3.amazonaws.com/clickhouse-test-reports/67274/f84e2d29482879aeedb70af9d89f1014df787c6d/stateless_tests__asan__%5B1_2%5D.html):
> 
> I don't understand yet why we explicitly set rocksdb log level to error, but the warning messages still being printed:
> 
> ```
> 2024-07-28 08:08:51 Reason: having stderror:  
> 2024-07-28 08:08:51 [9d89e5687183] 2024.07.28 05:08:48.177662 [ 51097 ] {131ea5f5-19c6-433c-b959-1a40c4e674e1} <Warning> StorageEmbeddedRocksDB (test_6uvtfta1.dict_with_ttl (bc57c65f-fb09-4e93-9b5c-bbe1d2e7e371)): [table/block_based/block_based_table_reader.cc:863] Tail prefetch size 524288 is calculated based on heuristics
> 2024-07-28 08:08:51 
> 2024-07-28 08:08:51 stdout:
> 2024-07-28 08:08:51 0	foo
> 2024-07-28 08:08:51 0
> ```
> 
> May be @azat do you have any idea?

So it turns out that in CI we set rocksdb log level to debug to trace some unstable test.
The unstable test was removed anyway.
Regarding some warning error during importing data, it all relates to construction of a new table reader during ingestion of external SST file in `external_sst_file_ingestion_job.cc`
```
  status = cfd_->ioptions()->table_factory->NewTableReader(
      TableReaderOptions(
          *cfd_->ioptions(), sv->mutable_cf_options.prefix_extractor,
          env_options_, cfd_->internal_comparator(),
          sv->mutable_cf_options.block_protection_bytes_per_key,
          /*skip_filters*/ false, /*immortal*/ false,
          /*force_direct_prefetch*/ false, /*level*/ -1,
          /*block_cache_tracer*/ nullptr,
          /*max_file_size_for_l0_meta_pin*/ 0, versions_->DbSessionId(),
          /*cur_file_num*/ new_file_number,
          /* unique_id */ {}, /* largest_seqno */ 0,
          /* tail_size */ 0, user_defined_timestamps_persisted),
      std::move(sst_file_reader), file_to_ingest->file_size, table_reader);
  return status;
```
Here `unique_id = {}` and thus when opening DB we have warning `At least one SST file opened without unique ID to verify...` and `tail_size = 0`, so we have warning `Tail prefetch size xxx is calculated based on heuristics`. It's more likely a message at `debug` level to me, not `warning`.

So proposed action is to change log level in CI to error.

Note: Looking at this https://github.com/facebook/rocksdb/pull/12667#pullrequestreview-2062144222, `Tail prefetch size xxx is calculated based on heuristics` is at warning level because rocksdb maintainer want to track use cases that are at risk of regression when finally remove TailPrefetchStats.

**Comment by canhld94** [comment]
No sanitizer error found.. Not surprised because we also have sanitizer build tests in CI and had been running this rocksdb version for a month (though less comprehensive than ClickHouse CI).

Flaky test because I forget to drop table after test. Let's run CI for few more iteration.

**Comment by canhld94** [comment]
To be done in https://github.com/ClickHouse/ClickHouse/pull/66479

**Pull request closed without merging**
