### PR TITLE
Mark Gorilla codec on non-float columns as suspicous

### PR DESCRIPTION
**Pull request by rschu1ze**
This PR marks the Gorilla codec on non-float columns as "suspicious codec".

Reasons:

1. The original Gorilla paper proposed a compression schema for pairs of time stamps and double-precision FP values (see ["Gorilla: a fast, scalable, in-memory time series database"](https://doi.org/10.14778/2824032.2824078), Sec. 4.1.2, "Gorilla restricts the value element in its tuple to a double floating point type."). ClickHouse's Gorilla codec only implements compression of the latter and it does not impose any data type restrictions.
- Data types != Float* or (U)Int* (e.g. Decimal, Point etc.) are definitely not supposed to be used with Gorilla.
- (U)Int* types are debatable. The paper only considers integers-represented-as-FP-values, a practical use case for which Gorilla works well. Standalone integers are not considered which makes them at least suspicious.

2. Achieve consistency with FPC, another specialized floating-point timeseries codec, which rejects non-float data.

3. On practical datasets, ZSTD is often ["good enough"](https://clickhouse.com/blog/optimize-clickhouse-codecs-compression-schema) so it should be okay to disincentive non-ZSTD codecs a little bit. If needed, Delta and DoubleDelta codecs are viable alternative for slowly changing (i.e. time-series-like) integer sequences.

This PR disallows the creation of new Gorilla-compressed non-float columns unless setting "allow_suspicious_codecs" is "true". Existing data of this kind will continue to load just fine because setting "allow_suspicous_codecs" is ignored during server startup and in `ATTACH TABLE`.

Side note: Gorilla-compressed non-float columns should not be very common in practice since the [documentation](https://clickhouse.com/docs/en/sql-reference/statements/create/table/) always listed Gorilla as a specialized codec for "series of floating-point values".

### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Mark Gorilla compression on columns of non-Float* type as suspicious.

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
@rschu1ze IIRC, we allow all codecs (including suspicious) for ATTACH TABLE queries and on server startup. So, why don't turn the check on by default?

**Comment by rschu1ze** [comment]
@alexey-milovidov Thanks, you are right ... I verified locally that server startup and ATTACH TABLE don't care about suspicious_codecs. So basically, when we make Gorilla-on-nonfloats suspicious right now, the creation of such tables will only work with `allow_suspicous_codecs = true` but all existing use cases will continue to work. Cool, then I'll change this PR, it will simplify things.

**Comment by rschu1ze** [comment]
Test failures are all unrelated or fixed in master.

**Comment by rschu1ze** [comment]
@alexey-milovidov Approve + merge? Thanks!

**Comment by alexey-milovidov** [comment]
Is it ok for Nullable(Float)? Array(Float)? Tuple(Float, Float)?

**Comment by rschu1ze** [comment]
> Is it ok for Nullable(Float)? Array(Float)? Tuple(Float, Float)?

Fixed that, thanks.

**Review by alexey-milovidov — APPROVED** [review]

**Pull request merged**
