### PR TITLE
Add more options to prefer_column_name_to_alias

### PR DESCRIPTION
**Pull request by amosbird**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Add more options to `prefer_column_name_to_alias` setting. This is for  https://github.com/ClickHouse/ClickHouse/issues/24237

set prefer_column_name_to_alias=1 --> prefer column over alias in all sub clauses;

set prefer_column_name_to_alias=2 --> prefer column over alias in all sub clauses before and include group by;

set prefer_column_name_to_alias=3 --> prefer column over alias in all sub clauses before group by;

Detailed description / Documentation draft:

.

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
@akuzm What do you think?

**Comment by akuzm** [comment]
Not sure about this. As a user, I want to have some predictable rules for name resolution, and probably don't want to control it with several arcane multi-valued settings. What's more important, I'm not sure we will be able to continue supporting all these variants when we introduce some "proper" name resolution phase. Maybe we have to introduce two name resolution modes, ANSI and ClickHouse, and refuse to support anything else, for simplicity.

How well does this PR work with the plan for name resolution we have here https://github.com/ClickHouse/ClickHouse/issues/23194 ?

**Comment by amosbird** [comment]
> Maybe we have to introduce two name resolution modes, ANSI and ClickHouse, and refuse to support anything else, for simplicity.

Indeed. I'll try to make `prefer_column_name_to_alias = 1` compatible with ANSI.

**Comment by alexey-milovidov** [comment]
@kitaisreal took over this task in #23194

**Pull request closed without merging**
