### PR TITLE
ASTLiteral clone only value

### LINKED ISSUE #36279: Argument at index 1 for function ilike must be constant: while executing. (ILLEGAL_COLUMN)
**How to reproduce**

```
CREATE TABLE test_local on cluster '{cluster}' (text String, text2 String) ENGINE = MergeTree() ORDER BY text;
CREATE TABLE test_distruted (text String, text2 String) ENGINE = Distributed('{cluster}', currentDatabase(), test_local);
INSERT INTO test_distruted SELECT randomString(100) as text, randomString(100) as tex2 from system.numbers limit 1;
```

```
SELECT COUNT() AS count
FROM test_distruted
INNER JOIN
(
    SELECT text
    FROM test_distruted
    WHERE (text ILIKE '%text-for-search%') AND (text2 ILIKE '%text-for-search%')
) USING (text)
WHERE (text ILIKE '%text-for-search%') AND (text2 ILIKE '%text-for-search%')
```

```
Received exception from server (version 22.3.2):
Code: 44. DB::Exception: Received from xxx. DB::Exception: Argument at index 1 for function ilike must be constant: while executing 'FUNCTION ilike(text2 : 3, '%text-for-search%' : 0) -> ilike(text2, '%text-for-search%') UInt8 : 4'. (ILLEGAL_COLUMN)
```

Simple query - it works
```
SELECT text
FROM test_distruted
WHERE (text ILIKE '%text-for-search%') AND (text2 ILIKE '%text-for-search%')

Query id: 4960850f-6e27-4a10-a7a0-c9182fdf27ac

Ok.

0 rows in set. Elapsed: 0.010 sec.
```

**Versions with bug**:
22.3.2, 21.11.11

### PR DESCRIPTION
**Pull request by vdimir**
### Changelog category (leave one):
- Bug Fix (user-visible misbehaviour in official stable or prestable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
- Fix potential error with literals in `WHERE` for join queries. Close https://github.com/ClickHouse/ClickHouse/issues/36279

> Information about CI checks: https://clickhouse.tech/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by vdimir** [comment]
Added test failed in CI, going to investigate ...

**Comment by yakov-olkhovskiy** [comment]
@vdimir still produces same error:
https://s3.amazonaws.com/clickhouse-test-reports/36542/ffb0570cae70c28719e7c921c3a37a840d1bbb6a/stateless_tests__release__actions_.html
...very strange

**Comment by vdimir** [comment]
Seems that error `table not found` was caused by another bug, current table name is not substituted into JOIN subquery
https://github.com/ClickHouse/ClickHouse/pull/36902

**Review by yakov-olkhovskiy — APPROVED** [review]

**Comment by den-crane** [comment]
it can solve https://github.com/ClickHouse/ClickHouse/issues/36891

**Comment by SaltTan** [comment]
Backport?

**Comment by filimonov** [comment]
> issue have workaround `SET optimize_move_to_prewhere = 0;`

It is not an acceptable workaround for most clickhouse users. Too significant performance impact.

**Pull request merged**
