### PR TITLE
Release pull request for branch 20.8

### PR DESCRIPTION
**Pull request by robot-clickhouse**
This PullRequest is part of ClickHouse release cycle. It's used by CI system only. Don't perform any changes with it.

### CODE REVIEW

**Comment by alesapin** [comment]
`00600_replace_running_query` in flaky in debug? Test log https://gist.github.com/alesapin/db850cf068eb64f6a66e4603ee090b9b.

**Comment by alesapin** [comment]
`00652_replicated_mutations_zookeeper` fixed in master.

**Comment by alesapin** [comment]
image
:( Fixed in the latest commit. But we have to wait again(

**Comment by alesapin** [comment]
Release build killed by OOM, I'll just rerun it and release.

**Comment by alesapin** [comment]
Ok, will wait for release tests.

**Comment by alesapin** [comment]
Report OK https://clickhouse-test-reports.s3.yandex.net/14297/3371a62513dfa6abbb065f51502ae86e2930c820/integration_tests_(release).html

**Comment by nikitamikhaylov** [comment]
Thread leak in live view? Some thread doesn't join?
```
Stats: LargeMmapAllocator: allocated 1061217 times, remains 49 (130820 K) max 1240 M; by size logs: 17:43485; 18:91665; 19:178646; 20:734439; 21:6755; 22:5260; 23:824; 24:99; 25:44; 
==================
WARNING: ThreadSanitizer: thread leak (pid=304)
  Thread T376 (tid=490578, finished) created by thread T378 at:
    #0 pthread_create <null> (clickhouse+0xeffe7ab)
    #1 std::__1::__libcpp_thread_create(unsigned long*, void* (*)(void*), void*) /build/obj-x86_64-linux-gnu/../contrib/libcxx/include/__threading_support:394:10 (clickhouse+0x1af044a8)
    #2 std::__1::thread::thread<void (*)(std::__1::shared_ptr<DB::StorageLiveView>, unsigned long const&), std::__1::shared_ptr<DB::StorageLiveView>, unsigned long const&, void>(void (*&&)(std::__1::shared_ptr<DB::StorageLiveView>, unsigned long const&), std::__1::shared_ptr<DB::StorageLiveView>&&, unsigned long const&) /build/obj-x86_64-linux-gnu/../contrib/libcxx/include/thread:300:16 (clickhouse+0x1af044a8)
    #3 DB::StorageLiveView::startNoUsersThread(unsigned long const&) /build/obj-x86_64-linux-gnu/../src/Storages/LiveView/StorageLiveView.cpp:464:31 (clickhouse+0x1af0136b)
    #4 DB::LiveViewBlockInputStream::~LiveViewBlockInputStream() /build/obj-x86_64-linux-gnu/../src/Storages/LiveView/LiveViewBlockInputStream.h:24:22 (clickhouse+0x1af0cfde)
    #5 std::__1::__shared_ptr_emplace<DB::LiveViewBlockInputStream, std::__1::allocator<DB::LiveViewBlockInputStream> >::__on_zero_shared() /build/obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:3602:23 (clickhouse+0x1af0c9c7)
    #6 std::__1::__shared_count::__release_shared() /build/obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:3440:9 (clickhouse+0x1a790b9c)
    #7 std::__1::__shared_weak_count::__release_shared() /build/obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:3482:27 (clickhouse+0x1a790b9c)
    #8 std::__1::shared_ptr<DB::IBlockInputStream>::~shared_ptr() /build/obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:4207:19 (clickhouse+0x1a790b9c)
    #9 DB::QueryStatus::releaseQueryStreams() /build/obj-x86_64-linux-gnu/../src/Interpreters/ProcessList.cpp:305:1 (clickhouse+0x1a790b9c)
    #10 DB::BlockIO::reset() /build/obj-x86_64-linux-gnu/../src/DataStreams/BlockIO.cpp:44:35 (clickhouse+0x19f16c7b)
    #11 DB::BlockIO::operator=(DB::BlockIO&&) /build/obj-x86_64-linux-gnu/../src/DataStreams/BlockIO.cpp:57:5 (clickhouse+0x19f16d30)
    #12 DB::QueryState::operator=(DB::QueryState&&) /build/obj-x86_64-linux-gnu/../src/Server/TCPHandler.h:31:8 (clickhouse+0x1afac3c1)
    #13 DB::QueryState::reset() /build/obj-x86_64-linux-gnu/../src/Server/TCPHandler.h:84:15 (clickhouse+0x1af9e019)
    #14 DB::TCPHandler::runImpl() /build/obj-x86_64-linux-gnu/../src/Server/TCPHandler.cpp:285:19 (clickhouse+0x1af9e019)
    #15 DB::TCPHandler::run() /build/obj-x86_64-linux-gnu/../src/Server/TCPHandler.cpp:1217:9 (clickhouse+0x1afa9c47)
    #16 Poco::Net::TCPServerConnection::start() /build/obj-x86_64-linux-gnu/../contrib/poco/Net/src/TCPServerConnection.cpp:43:3 (clickhouse+0x1de01112)
    #17 Poco::Net::TCPServerDispatcher::run() /build/obj-x86_64-linux-gnu/../contrib/poco/Net/src/TCPServerDispatcher.cpp:112:19 (clickhouse+0x1de01960)
    #18 Poco::PooledThread::run() /build/obj-x86_64-linux-gnu/../contrib/poco/Foundation/src/ThreadPool.cpp:199:14 (clickhouse+0x1df6a746)
    #19 Poco::(anonymous namespace)::RunnableHolder::run() /build/obj-x86_64-linux-gnu/../contrib/poco/Foundation/src/Thread.cpp:55:11 (clickhouse+0x1df68e7f)
    #20 Poco::ThreadImpl::runnableEntry(void*) /build/obj-x86_64-linux-gnu/../contrib/poco/Foundation/src/Thread_POSIX.cpp:345:27 (clickhouse+0x1df67707)

SUMMARY: ThreadSanitizer: thread leak (/usr/bin/clickhouse+0xeffe7ab) in pthread_create
```

**Comment by alesapin** [comment]
How is it possible https://clickhouse-test-reports.s3.yandex.net/14297/796b083e9727a517f8c603af021d7b296cf9a5b5/push_to_dockerhub.html#fail1? We don't have these lines in this file for this branch.

**Comment by alexey-milovidov** [comment]
The support period has ended.

**Pull request closed without merging**
