### PR TITLE
Fix statistic merge

### PR DESCRIPTION
**Pull request by JackyWoo**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Add merge to statistic

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by JackyWoo** [comment]
@hanfei1991 please take a look at the PR

**Comment by alexey-milovidov** [comment]
> Add merge to statistic

What improvement has been made for the user?

**Comment by hanfei1991** [comment]
It's weird to only add an interface without any purpose

**Comment by JackyWoo** [comment]
The interface is used in`PartColumnEstimator` to merge other statistic.
https://github.com/ClickHouse/ClickHouse/blob/d30792b196361281a71b84058b3aa87aa6913866/src/Storages/Statistics/Estimator.h#L32-L41

**Comment by hanfei1991** [comment]
1. This is not a "Bug Fix"
2. The interface will change a lot in this PR https://github.com/ClickHouse/ClickHouse/pull/59357

**Comment by JackyWoo** [comment]
I checked the PR, indeed this will change a lot, thanks.

**Pull request closed without merging**
