### PR TITLE
docs: fix garbled

### PR DESCRIPTION
**Pull request by Jiasm**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
Documentation

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Fix garbled in Chinese.

Detailed description / Documentation draft:

### CODE REVIEW

**Review by qoega — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
@blinkov You should *never* do machine translation for docs.

**Comment by Jiasm** [comment]
> @Jiasm Thank you!
> 
> CC @blinkov You should _never_ do machine translation for docs.

lol，I will check if the same problems exist on other pages and try to fix them.

**Comment by blinkov** [comment]
@Jiasm https://twitter.com/ClickHouseDB/status/1288844861207085056

**Comment by Jiasm** [comment]
> @Jiasm https://twitter.com/ClickHouseDB/status/1288844861207085056

Woow so lucky for me to be the 500th contributor, thank u bro♥️

**Pull request merged**
