### PR TITLE
Merging Avro format.

### PR DESCRIPTION
**Pull request by alexey-milovidov**
Changelog category (leave one):
- Other

Changelog entry (up to few sentences, required except for Non-significant/Documentation categories):
Continuation of #8571

### CODE REVIEW

**Comment by oandrew** [comment]
@alexey-milovidov  

Disabling AvroConfluent makes sense - it needs more work.
I have tried integrating libserdes (https://github.com/confluentinc/libserdes) locally and it works fine. 
My only concern about libserdes is that it brings in additional dependencies -  `curl` and `libjansson`. Also I had make some changes  to make it compatible with avrocpp 1.9. (https://github.com/confluentinc/libserdes/issues/18).
Do you think it's worth it?


Also few more questions:
1. KafkaStorage creates a new input format instance for each batch of messages: https://github.com/ClickHouse/ClickHouse/blob/master/dbms/src/Storages/Kafka/KafkaBlockInputStream.cpp#L68-L70. 

In order to reuse  existing schema registry clients between multiple instances of `AvroConfluentRowInputFormat`  I  tried adding per-url cache by using LRUCache as a static variable.
e.g. in `AvroRowInputFormat`
```
class SchemaRegistry
{
public:
    virtual ~SchemaRegistry() {};
    virtual avro::ValidSchema getSchema(uint32_t id) = 0;
};

using SchemaRegistryCache = LRUCache<std::string, SchemaRegistry>;

static SchemaRegistryCache  schema_registry_cache(1000);

static std::shared_ptr<SchemaRegistry> get_schema_registry(const FormatSettings & format_settings)
{
    auto url = format_settings.avro.schema_registry_url;
    auto [schema_registry, loaded] = schema_registry_cache.getOrSet(
        url, 
        [url] 
        {
            return std::make_shared<SchemaRegistryImpl>(url);
        }
    );
    return schema_registry;
}
```
Does this sound like a good approach or is there a better way?

2. I noticed MemoryTracker reporting high memory usage when using  AvroRowOutputFormat  with many rows (50M+) while in reality memory usage was constant (on mac / clang)
After some digging I noticed it's caused by this: 
https://github.com/apache/avro/blob/master/lang/c%2B%2B/impl/Stream.cc#L130-L134
When I  replace `new uint8_t[] / delete[]` with `malloc/free` the problem is gone.

**Comment by alexey-milovidov** [comment]
> I have tried integrating libserdes (https://github.com/confluentinc/libserdes) locally and it works fine.

Current AvroConfluent implementation is very simple and there is no need to add this library. Is there any other benefits that this library provides?

>  I tried adding per-url cache by using LRUCache as a static variable.

Yes, this is reasonable. You can make it singleton for lazy initialization.

> I noticed MemoryTracker reporting high memory usage when using AvroRowOutputFormat

Memory tracker is hooked inside operators new and delete. It's possible that it works wrong for array versions of these operators. It can overestimate memory usage and it will lead to "memory limit exceeded" exception on long streaming inserts. But this is minor issue, because small to medium inserts with Avro will work fine.

**Comment by alexey-milovidov** [comment]
"unbundled" test fail: as expected (will exclude in CI)

**Comment by oandrew** [comment]
p.s. MemoryTracker issue happens only on Select. Inserts are ok

**Comment by oandrew** [comment]
libserdes has only one additional "feature" - support for multiple comma separated schema registry URLs. But that should be  easy to implement.

**Comment by alexey-milovidov** [comment]
> But that should be easy to implement.

Or just postpone the implementation before first use case will appear.

**Comment by alexey-milovidov** [comment]
```
~/ClickHouse$ time clickhouse-client --query "SELECT * FROM test.hits" --format Avro > hits.avro
Code: 44. DB::Exception: Type UInt64 is not supported for Avro output: column WatchID
```

Why so bad?

**Comment by alexey-milovidov** [comment]
Maybe better to support implicit signed <-> unsigned conversions?

**Comment by oandrew** [comment]
Avro doesn't support UInt64. 
https://avro.apache.org/docs/current/spec.html#schema_primitive

Truncating to Int64 (max avro supports) would mean potentially incorrect data in the output

**Comment by alexey-milovidov** [comment]
I mean - type conversion with the same bit representation.

Also UInt8 <-> bool is questionable choice, because UInt8 is often used for small identifiers.

**Comment by alexey-milovidov** [comment]
String must be serialized as Bytes. Because our strings can contain arbitrary binary data.

**Comment by alexey-milovidov** [comment]
But we can also support schema conversion at write (writing data with defined schema).

**Comment by oandrew** [comment]
For UInt64 I see few options:
- truncate to Int64  - large numbers truncated as 2^63-1
- output as-is (same bit representation) - large numbers appear as negative numbers
- have a special flag that enables one of the above
- output as custom type fixed 8-bytes. << I think I prefer this one the most

**Comment by alexey-milovidov** [comment]
> output as-is (same bit representation) - large numbers appear as negative numbers

This.

**Comment by oandrew** [comment]
I mean yeah truncating is dumb cause it looses data.
I'm fine with same bits (we would just need to make it clear in docs).
Using custom type would be nicely compatible with Clickhouse<->Clickhouse but not with other systems.

**Comment by alexey-milovidov** [comment]
```
~/ClickHouse$ time clickhouse-client --query "SELECT * FROM test.hits" --format TSV > hits.tsv

real    0m44.239s
user    0m35.752s
sys     0m5.876s

~/ClickHouse$ time clickhouse-client --query "SELECT * FROM test.hits" --format Avro > hits.avro

real    1m4.151s
user    0m59.476s
sys     0m4.112s
```

Not bad.

**Comment by oandrew** [comment]
Try without compression `--output_format_avro_codec  null`

**Comment by alexey-milovidov** [comment]
Without compression it is almost the same as TSV:

```
~/ClickHouse$ time clickhouse-client --query "SELECT * FROM test.hits" --format Avro --output_format_avro_codec null > hits.avro.null

real    0m44.714s
user    0m38.064s
sys     0m6.204s
```

But is more compact:
```
~/ClickHouse$ ls -l hits.avro hits.avro.null hits.tsv                                                                                                                                                        
-rw-r--r-- 1 milovidov 1867326594 янв 19 04:32 hits.avro                                                                                                                                            
-rw-r--r-- 1 milovidov 5150275415 янв 19 04:40 hits.avro.null                                                                                                                                       
-rw-r--r-- 1 milovidov 7784443787 янв 19 04:02 hits.tsv
```

**Comment by alexey-milovidov** [comment]
Is `null` the preferred name for "no compression"?
I'm asking because we already have format Null that means - don't write anything; and we already have option to choose generic compression method for text files, and in that option, no compression is `none` not `null`. Maybe it's reasonable to remane `null` to `none` for consistency.

**Comment by oandrew** [comment]
p.s. Avro with snappy also calculates crc (avro cpp uses boost crc for that)  and it is not optimized (in case someone wants to speed it up)

**Comment by oandrew** [comment]
Yeah I had the same question about calling it `null`. It's from the avro spec. 
+1 for `none`. (we can support both `null` and `none` but mention only `none` in the docs/cli help)

**Comment by alexey-milovidov** [comment]
Current status:
- need to add type conversions in reader, then we can merge.

Next steps (after merge):
- support for `input_format_null_as_default` setting;
- support for schema-aware output;
- enable AvroConfluent with appropriate changes.

**Comment by alexey-milovidov** [comment]
@oandrew I started testing and found that it doesn't work at all. It cannot successfully round-trip our `hits` dataset. Because all FixedString data types are written under the same name `fixed` and collapsed to the same type in schema.

Example:

```
$ build_gcc9/dbms/programs/clickhouse local --input-format CSV --output-format Avro -S 'x FixedString(5), y FixedString(5)' --query "SELECT * FROM table" <<< 'Hello,World'
fixedfixedObjavro.codec
                       snappyavro.schema�{"type":"record","name":"row","fields":[{"name":"x","type":{"type":"fixed","name":"fixed","size":5}},{"name":"y","type":"fixed"}]}eOGt�|Fjl[��bs
```

And deserializer cannot read this schema:

```
{"type":"record","name":"row","fields":[{"name":"x","type":{"type":"fixed","name":"fixed","size":5}},{"name":"y","type":"fixed"}]}
```

**Comment by alexey-milovidov** [comment]
And you forget to write comments:

```
std::vector<int> field_mapping;
std::vector<SkipFn> skip_fns;
std::vector<DeserializeFn> deserialize_fns;
```

I have to struggle with that code.

**Comment by alexey-milovidov** [comment]
It looks like we have two bugs:
1. Different types was serialized under the same name in AvroOutputFormat.
2. AvroInputFormat doesn't support references to previously defined type.

Let me fix the first bug and you'll fix the second after merge.

**Comment by alexey-milovidov** [comment]
Now it at least passes roundtrip test with `hits`.

**Comment by oandrew** [comment]
@alexey-milovidov sounds good. 

p.s. I am out of town until Jan 31. I'll fix those outstanding issues as soon as I'm back.

**Comment by alexey-milovidov** [comment]
Avro has UB in its ZigZag encoder.
https://clickhouse-test-reports.s3.yandex.net/8717/64baafd24511aa97a0394092bb64510aec3327ea/functional_stateful_tests_(ubsan)/stderr.log

Requires patch.

**Comment by filimonov** [comment]
```
../contrib/avro/lang/c++/impl/Zigzag.cc:27:20: runtime error: left shift of negative value -1
    #0 0x213e5608 in avro::encodeZigzag64(long) /build/obj-x86_64-linux-gnu/../contrib/avro/lang/c++/impl/Zigzag.cc:27:20
    #1 0x213e5608 in avro::encodeInt64(long, std::__1::array<unsigned char, 10ul>&) /build/obj-x86_64-linux-gnu/../contrib/avro/lang/c++/impl/Zigzag.cc:52
    #2 0x21429653 in avro::BinaryEncoder::doEncodeLong(long) /build/obj-x86_64-linux-gnu/../contrib/avro/lang/c++/impl/BinaryEncoder.cc:165:19
```

https://github.com/apache/avro/blob/ca38fb98f83e0345ca6c49b0660e9fbd03ea3cd5/lang/c%2B%2B/impl/Zigzag.cc#L24-L28

**Comment by alexey-milovidov** [comment]
https://issues.apache.org/jira/browse/AVRO-2717

**Comment by filimonov** [comment]
New errors from PVS?

**Comment by alexey-milovidov** [comment]
Yes, they are PVS own errors. Possibly due to misconfiguration.

**Pull request merged**
