### PR TITLE
PCHed build

### PR DESCRIPTION
**Pull request by kreuzerkrieg**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- RFC

RFC PR for CMake 3.16 build with precompiled headers.

I've employed the PCH provided by CMake 3.16, however I dont see any improvement in build time. Which is quite odd. I ask you to review it and comment if you see anything in the way I use the PCH.

I see gch files created and `-include` added to each compile unit, so looks like I did it the right way, however...

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]
LGTM.

I'm not an expert in CMake, but it looks Ok.

**Comment by alexey-milovidov** [comment]
Probably it won't work in our CI because we use old CMake.
Is it possible to enable it conditionally depending on the version?

**Comment by kreuzerkrieg** [comment]
> Probably it won't work in our CI because we use old CMake.
> Is it possible to enable it conditionally depending on the version?

you didnt read what I've wrote :)
It doesnt make any difference in build time, it is RFC PR, maybe you guys can see what I did (or didnt) wrong

**Comment by alexey-milovidov** [comment]
I have tested pch long time ago (with compiled Aggregator) and it made only slight improvement in build time. As far as I understand, the main cost of build time is template instantiation rather than headers parsing.

**Comment by kreuzerkrieg** [comment]
> I have tested pch long time ago (with compiled Aggregator) and it made only slight improvement in build time. As far as I understand, the main cost of build time is template instantiation rather than headers parsing.

Hm... interesting... Then what improvement was exhibited by `cotire`? For some reason the detected improvement was associated with precompiled headers, at least I attributed it to PCH.
As of templates, you dont (I think) such a big amount of templates, didnt notice you were using Boots.Hana :)

**Comment by kreuzerkrieg** [comment]
Maybe  @proller or @nvartolomei can see something wrong with this PCH usage?

**Comment by abyss7** [comment]
We made analysis some time ago on what consumes the most time while compiling CH: https://pastebin.com/VQsJXKkm

Looks like you did everything correct, but just try to precompile the most expensive headers to get some improvements.

**Comment by kreuzerkrieg** [comment]
> We made analysis some time ago on what consumes the most time while compiling CH: https://pastebin.com/VQsJXKkm
> 
> Looks like you did everything correct, but just try to precompile the most expensive headers to get some improvements.

Will try these under `Expensive headers`
The question how frequently it changes

**Comment by kreuzerkrieg** [comment]
74 minutes clean build with PCH
76 without
Do we have any new ideas?

**Comment by abyss7** [comment]
Will try locally.

**Comment by kreuzerkrieg** [comment]
> Will try locally.

Dont know why we dont see any benefit, but I have a theory, will check it later

**Comment by alexey-milovidov** [comment]
@kreuzerkrieg Removing includes from source files will make the code less readable and will compromise code navigation - not acceptable.

**Comment by kreuzerkrieg** [comment]
> @kreuzerkrieg Removing includes from source files will make the code less readable and will compromise code navigation - not acceptable.

Thats why the commit wasnt squashed with others. Just was checking my theory and it didnt work at all. I doubt @abyss7 will see anything interesting in his local checks, but who knows, maybe miracles happen, but I'm close to abandon the idea of precompiled headers if you guys dont come with some brilliant idea.

**Comment by alexey-milovidov** [comment]
Maybe you know some gcc hackers/experts and can invite them here?

**Comment by kreuzerkrieg** [comment]
> Maybe you know some gcc hackers/experts and can invite them here?

Unfortunately not, was hoping you have some.
The precompiled headers is just not the same as it on Windows, there it is widely used and considered first class citizen compiler feature. On Linux it is some obscure, rarely used feature. I will try and see if switching to clang makes any difference

**Comment by alexey-milovidov** [comment]
http://llunak.blogspot.com/2019/05/why-precompiled-headers-do-not-improve.html
https://www.reddit.com/r/cpp/comments/bsdrkv/why_precompiled_headers_do_not_improve_c_compile/
https://stackoverflow.com/questions/13309228/gcc-build-time-doesnt-benefit-much-from-precompiled-headers

**Pull request closed without merging**
