### PR TITLE
Fix no attribute decode with python3

### PR DESCRIPTION
**Pull request by MaxWk**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Build/Testing/Packaging Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
remove decode method with python3

Detailed description / Documentation draft:
Run httpechoserver.py with python3 ,it will throw an exception "'str' object has no attribute 'decode'".

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
@MaxWk I'm not a Python developer, could you please explain the meaning of these changes?
Why is it needed as everything is already working fine in our CI environment?

**Comment by alesapin** [comment]
Seems like this file is just unused, but the fix is correct. Let's remove the whole file?

**Review by alesapin — APPROVED** [review]

**Comment by alesapin** [comment]
Waiting for any run of functional tests.

**Comment by alesapin** [comment]
Done.

**Pull request merged**
