### PR TITLE
feat: add quantile DDSketch

### LINKED ISSUE #6739: DDSketch Quantiles
(you don't have to strictly follow this form)

**Use case**
We are currently using two `QuantilesTimingWeighted` columns, one for values up to 30sec and one scaled by 100 for larger values. We'd like to be able to use just one column to gain speed, but t-digest is slower overall. 

**Describe the solution you'd like**
DDSketch has just been released, but it is described as being very fast. Our hope is that we can use DDSketch with a single `QuantilesTiming` column with decent precision and gain speed.

**Additional context**
HN thread: https://news.ycombinator.com/item?id=20829404

### PR DESCRIPTION
**Pull request by srikanthccv**
Fixes https://github.com/ClickHouse/ClickHouse/issues/6739

### Changelog category (leave one):
- New Feature

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Add `quantileDDSketch` aggregate function as well as the corresponding `quantilesDDSketch` and `medianDDSketch`. It is based on the DDSketch https://www.vldb.org/pvldb/vol12/p2195-masson.pdf.
### Documentation entry for user-facing changes

- [x] Documentation is written (mandatory for new features)

- Motivation: It is very important to calculate accurate quantiles fast. The OpenTelemetry project is the emerging standard in the observability ecosystem, and the preferred way to record the latencies is [`ExponentialHistogram`](https://github.com/open-telemetry/opentelemetry-proto/blob/cfbf9357c03bf4ac150a3ab3bcbe4cc4ed087362/opentelemetry/proto/metrics/v1/metrics.proto#L222). Having this feature in ClickHouse makes it more adaptable.   
- Parameters: relative accuracy (or gamma in the paper) 
- Example use: 

```sql
CREATE TABLE default.comparision
(
    `id` UInt64,
    `sketch` AggregateFunction(quantilesDDSketch(0.0003, 0.9), UInt64),
    `td` AggregateFunction(quantilesTDigest(0.5, 0.9, 0.99), UInt64),
    `bf` AggregateFunction(quantilesBFloat16(0.5, 0.9, 0.99), UInt64)
)
ENGINE = SummingMergeTree
ORDER BY id
SETTINGS index_granularity = 8192


insert into comparision
select
    number % 10000 as id,
    quantilesDDSketchState(0.0003, 0.9)(number) as sketch,
    quantilesTDigestState(0.5, 0.9, 0.99)(number) as td,
    quantilesBFloat16State(0.5, 0.9, 0.99)(number) as bf  
from numbers(100000000)
group by id;


SELECT
    quantilesDDSketchMerge(0.0003, 0.9)(sketch) AS sketch
FROM comparision

SELECT
    quantileTDigestMerge(0.9)(td) AS td
FROM comparision

SELECT
    quantileBFloat16Merge(0.9)(bf) AS bf
FROM comparision

```

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

PS: 

We at [SigNoz](https://signoz.io) love ClickHouse.

### CODE REVIEW

**Comment by srikanthccv** [comment]
I couldn't find documentation on adding tests. I would appreciate some help with how to add unit/integration tests.

**Comment by alexey-milovidov** [comment]
Thank you! About the naming - the other quantile functions (quantile, quantileTiming, quantileTDigest, quantileBFloat16) are also sketches of their kinds. And this function is a particular kind of sketch - DDSketch. Let's name it quantileDDSketch.

**Comment by robot-clickhouse-ci-2** [comment]
*This is an automated comment for commit d7299178348b34e1432385859ba7456a65130332 with description of existing statuses. It's updated for the latest CI running*

[❌ Click here](https://s3.amazonaws.com/clickhouse-test-reports/55305/d7299178348b34e1432385859ba7456a65130332/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs Check</td><td>Builds and tests the documentation</td><td>❌ failure</td></tr>
<tbody>
</table>

**Comment by alexey-milovidov** [comment]
The tests are in `tests/queries/0_stateless` - add an .sql file similar to others, then generate a .reference file by running `clickhouse-client -n < ....sql > ....reference`

**Comment by alexey-milovidov** [comment]
PS. Congrats on the super-exciting news! https://techcrunch.com/2023/09/28/open-source-datadog-rival-signoz-lands-on-the-cloud-with-6-5m-investment/

**Comment by srikanthccv** [comment]
Thanks. I was unsure about using the name "DDSketch," but I think it should be fine. I will update it and mark it as ready after adding tests and fixing any failing checks.

**Comment by alexey-milovidov** [comment]
Ok. Checks have failed, need to fix them.

**Comment by srikanthccv** [comment]
This is ready for review

**Comment by bharatnc** [comment]
I noticed that this PR is failing docs check. You would need to add docs for this new function QuantileDDSketch before the builds can proceed. You can document it [here](https://github.com/ClickHouse/ClickHouse/tree/master/docs/en/sql-reference/aggregate-functions/reference).

You might also need to add your new function to the test [here](https://github.com/bharatnc/ClickHouse/blob/master/tests/queries/0_stateless/02415_all_new_functions_must_be_documented.reference).

**Comment by srikanthccv** [comment]
I will open a new PR.

**Pull request closed without merging**
