### PR TITLE
Fix right offset for reading LowCardinality dictionary from remote fs

### LINKED ISSUE #44709: CANNOT_READ_ALL_DATA / LowCardinality /  S3 threadpool
@den-crane Thanks for the reply, we faced similar issue in few of our instances, where remote storage is S3. below is the stack trace. `operationName` column is of type LowCardinality.

```
2022.12.22 06:43:31.949698 [ 16873 ] {f33b0bd4-95db-4330-89d9-f18f24f3ac51} <Error> executeQuery: Code: 33. DB::Exception: Cannot read all data. Bytes read: 114. Bytes expected: 266.: (while reading column operationName): (while reading from part /var/lib/clickhouse/disks/s3_disk/store/961/961a395d-04ae-4f43-bf90-45a6c041b49e/1670889600_0_33677_2140/ from mark 26 with max_rows_to_read = 8192): While executing MergeTreeThread. (CANNOT_READ_ALL_DATA) (version 22.10.1.1877 (official build)) (from x.x.x.x:48908) (in query: SELECT operationName FROM <db>.<table_name> WHERE serviceName = 'xxx-xxx-xxx-xxx' GROUP BY operationName ORDER BY operationName LIMIT 10000), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xce3f35a in /usr/bin/clickhouse
1. ? @ 0xce9e494 in /usr/bin/clickhouse
2. ? @ 0x11a065b1 in /usr/bin/clickhouse
3. DB::SerializationLowCardinality::deserializeBinaryBulkWithMultipleStreams(COW<DB::IColumn>::immutable_ptr<DB::IColumn>&, unsigned long, DB::ISerialization::DeserializeBinaryBulkSettings&, std::__1::shared_ptr<DB::ISerialization::DeserializeBinaryBulkState>&, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, COW<DB::IColumn>::immutable_ptr<DB::IColumn> > > >*) const @ 0x119e63e7 in /usr/bin/clickhouse
4. DB::MergeTreeReaderWide::readData(DB::NameAndTypePair const&, std::__1::shared_ptr<DB::ISerialization const> const&, COW<DB::IColumn>::immutable_ptr<DB::IColumn>&, unsigned long, bool, unsigned long, unsigned long, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, COW<DB::IColumn>::immutable_ptr<DB::IColumn> > > >&, bool) @ 0x1322673b in /usr/bin/clickhouse
5. DB::MergeTreeReaderWide::readRows(unsigned long, unsigned long, bool, unsigned long, std::__1::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn> > >&) @ 0x132259b8 in /usr/bin/clickhouse
6. DB::MergeTreeRangeReader::DelayedStream::finalize(std::__1::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn> > >&) @ 0x139167e3 in /usr/bin/clickhouse
7. DB::MergeTreeRangeReader::startReadingChain(unsigned long, std::__1::deque<DB::MarkRange, std::__1::allocator<DB::MarkRange> >&) @ 0x1391c4a9 in /usr/bin/clickhouse
8. DB::MergeTreeRangeReader::read(unsigned long, std::__1::deque<DB::MarkRange, std::__1::allocator<DB::MarkRange> >&) @ 0x13919f95 in /usr/bin/clickhouse
9. DB::MergeTreeBaseSelectProcessor::readFromPartImpl() @ 0x13911c2e in /usr/bin/clickhouse
10. DB::MergeTreeBaseSelectProcessor::readFromPart() @ 0x139127b9 in /usr/bin/clickhouse
11. DB::MergeTreeBaseSelectProcessor::generate() @ 0x1390de31 in /usr/bin/clickhouse
12. DB::ISource::tryGenerate() @ 0x13590475 in /usr/bin/clickhouse
13. DB::ISource::work() @ 0x13590006 in /usr/bin/clickhouse
14. DB::ExecutionThreadContext::executeTask() @ 0x135ac186 in /usr/bin/clickhouse
15. DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*) @ 0x135a02dc in /usr/bin/clickhouse
16. ? @ 0x135a293d in /usr/bin/clickhouse
17. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xcefa04c in /usr/bin/clickhouse
18. ? @ 0xceff7be in /usr/bin/clickhouse
19. start_thread @ 0x7de5 in /lib64/libpthread-2.17.so
20. __clone @ 0xfebad in /lib64/libc-2.17.so
```

Any idea/suggestions on this one? Clickhouse version: `22.10.1.1877`

_Originally posted by @Dileep-Dora in https://github.com/ClickHouse/ClickHouse/issues/41756#issuecomment-1366388814_

### PR DESCRIPTION
**Pull request by KochetovNicolai**
… in case if the right mark was in the middle of the compressed block.

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in official stable or prestable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Another fix for `Cannot read all data` error which could happen while reading `LowCardinality` dictionary from remote fs. Fixes #44709

### CODE REVIEW

**Review by CurtizJ — APPROVED** [review]
LGTM

**Comment by CurtizJ** [comment]
Test failures are unrelated to changes.

**Comment by den-crane** [comment]
Please backport it to 22.8.

**Comment by Dileep-Dora** [comment]
Hi there's a recent release https://github.com/ClickHouse/ClickHouse/releases/tag/v22.3.17.13-lts

but can't see these file changes in 22.3 branch, can anyone confirm in which release we'll get this fix?

**Comment by den-crane** [comment]
it worths to merge at least to 22.3 and 22.8

**Pull request merged**
