### PR TITLE
CapnProtoInputStream jagged structures

### PR DESCRIPTION
**Pull request by Miniwoffer**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

For changelog. Remove if this is non-significant change.

**Category:**
- Improvement

**Short description:**
Changed the way CapnProtoInputStream creates actions in such a way that it now support structures that are jagged.

**Detailed description:**
CapnProtoInputStream only worked with CapnProto objects where at most one child could have children of its own.

To fix backtracking was implemented.

Also, added '_' as separator in addition to '.', this should not cause problems since '_' is not allowed in CapnProto names.

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
Missing test.

**Comment by alexey-milovidov** [comment]
I have some troubles reading this code and I've removed the function `checkEqualFrom` by mistake.

**Comment by alexey-milovidov** [comment]
I've fixed build but your test is not passed:
```
Field nestedone_nestednestedone_nestednestednumber doesn't exist in schema CapnProto
```

**Comment by alexey-milovidov** [comment]
How did you generated Cap'n'Proto test message?

**Comment by Miniwoffer** [comment]
With the cli tool
`capnp convert json:binary test.capnp CapnProto < test.json`
I can supply the json file if needed

**Comment by alexey-milovidov** [comment]
Ok.

The code is a bit difficult to understand for me. I have rewritten it a little and now test passed.
But I'm not sure that my modifications are correct. Can you please review my modifications?

(and add more tests if required in separate PR)

**Comment by Miniwoffer** [comment]
I'm sorry this is a little late. It looks good, i also did some manual testing and wrote two additional tests that takes care of edge cases if there are changes in the future.
The tests are not needed.

**Pull request merged**
