### PR TITLE
increase s3_retry_attempts

### PR DESCRIPTION
**Pull request by CheSema**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
It is better to retry retriable s3 errors than totally fail the query. Set bigger value to the s3_retry_attempts by default.

It is safe to increase s3_retry_attempts after this fixes:
https://github.com/ClickHouse/ClickHouse/pull/54651
https://github.com/ClickHouse/ClickHouse/pull/54697

### CODE REVIEW

**Comment by robot-ch-test-poll4** [comment]
*This is an automated comment for commit ca85ab26a1a9b50071ce0a9781e9f801ad0189c8 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/54770/ca85ab26a1a9b50071ce0a9781e9f801ad0189c8/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>✅ success</td></tr>
<tbody>
</table>
</details>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>⏳ pending</td></tr>
<tbody>
</table>

**Review by kssenii — APPROVED** [review]

**Comment by alifirat** [comment]
hey @CheSema this setting can be applied also when using the S3 disk as storage?
What is the name of the setting to set in the storage.xml file to update the number of retries?

**Comment by CheSema** [comment]
> hey @CheSema this setting can be applied also when using the S3 disk as storage? What is the name of the setting to set in the storage.xml file to update the number of retries?

Check the linked PR. They are connected. As it tuned out it is not enough to just raise the numbers of retries.

```storage_configuration -> disks -> {your s3 disk name} -> s3_retry_attempts```

**Comment by CheSema** [comment]
00385_storage_file_and_clickhouse-local_app_long https://github.com/ClickHouse/ClickHouse/issues/55674
Possible deadlock on shutdown -- cant find a problem in traces. See that at leas one thread (`DistributedAsyncInsertDirectoryQueue::hasPendingFiles`) is doing real work.

**Pull request merged**
