### PR TITLE
Fix possible "Different expressions with the same alias" for Distributed queries

### PR DESCRIPTION
**Pull request by azat**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix possible "Different expressions with the same alias" for Distributed queries

Subquery ids may overlaps on various servers, it is actually possible
even within one server by playing with _subquery aliases (see the test).

### CODE REVIEW

**Comment by robot-clickhouse** [comment]
*This is an automated comment for commit 181eca950676911fb4ebdabcc3e3656abf0d633a with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/60328/181eca950676911fb4ebdabcc3e3656abf0d633a/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/60328/181eca950676911fb4ebdabcc3e3656abf0d633a/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Comment by azat** [comment]
>Bugfix validation — New test(s) failed to reproduce a bug

- https://github.com/ClickHouse/ClickHouse/pull/61363

**Comment by jkartseva** [comment]
The change LGTM but please please take a look at the new test (it failed): 
https://github.com/ClickHouse/ClickHouse/actions/runs/8279979435/job/22657992028?pr=60328#step:8:4077

Perhaps an integration test will suit better for the purpose?

**Comment by azat** [comment]
The problem is that `QueryAliasesVisitor` does not follows into `ASTSelectWithUnionQuery`. We can either do this, or update the alias in case of AST hash mismatch if the alias was set in `QueryAliasesVisitor`, but I don't think it worth doing for the old analyzer, so let's simply close it.

But it does not work with analyzer as well, but this is a separate problem.

**Pull request closed without merging**
