### PR TITLE
Resubmit "Fix uncaught DNS_ERROR on failed connection to replicas"

### PR DESCRIPTION
**Pull request by coelho**
Reverts ClickHouse/ClickHouse#41252 that reverted ClickHouse/ClickHouse#40881 Bugfix
Resubmitted at request of [tavplubix](https://github.com/tavplubix)

This bug breaks Distributed HA in the case of DNS errors. I believe the revert was a mistake & we should make sure this is in 22.9.

Causes a test `host_is_drop_from_cache_after_consecutive_failures ` https://github.com/ClickHouse/ClickHouse/issues/41250 to be flaky.
- Logs: https://s3.amazonaws.com/clickhouse-test-reports/0/8587fa59f7c1a8d046395d40e01a404b2bffeac1/integration_tests__tsan__[3/4]/integration_run_test_dns_cache_test_py_0.log
- I believe this does not affect actual functionality and is just a testing error.

_Original description:_

DNS_ERROR would cause the replica to not be marked as unusable, resulting in the replica being repeatedly reattempted on subsequent queries and for connection failover to not function.
(This is common in Kubernetes setups where a replica has failed and it's DNS record is returning NXDOMAIN)

On SELECT of a Distributed table, would additionally result in an intermittent query error if the failed replica is chosen:
`Code: 198. DB::Exception: Received from localhost:9000. DB::Exception: Not found address of host: chi-clickhouse-main-2-0: While executing Remote. (DNS_ERROR)`

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in official stable or prestable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix uncaught DNS_ERROR on failed connection to replicas.

### CODE REVIEW

**Comment by tavplubix** [comment]
Nothing was changed, so I suppose this PR still breaks the test, it does not really make sense to restart checks

**Comment by coelho** [comment]
@tavplubix Any news on this? The bug this patch fixes still exists in `HEAD`.

For context: Due to this bug, if we restart any Clickhouse Server in our Kube Cluster, the DNS record disappears, and every Distributed table in our cluster starts throwing query errors `DNS_ERROR` (even with an alive replica)

**Comment by alexey-milovidov** [comment]
@coelho 

The code looks ok, but we need to figure out why it leads to the failure of the
> host_is_drop_from_cache_after_consecutive_failures

test. It is definitely related.

**Comment by alexey-milovidov** [comment]
Finally, it was merged.

**Pull request closed without merging**
