### PR TITLE
MaterializedMySQL: Support CREATE TABLE AS SELECT

### PR DESCRIPTION
**Pull request by valbok**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
- CREATE TABLE ... AS SELECT .. is now supported in MaterializedMySQL

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by robot-clickhouse-ci-1** [comment]
This is an automated comment for commit 87b54acf66e123151498d87803d7c8e97a723707 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/52067/87b54acf66e123151498d87803d7c8e97a723707/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Review by kssenii — APPROVED** [review]

**Comment by valbok** [comment]
I can't find any failed tests even if 
Integration tests flaky check (asan) — Invalid check_status.tsv
Mergeable Check — failed: Integration tests flaky check (asan)

shows failed?

**Comment by kssenii** [comment]
If you open `integration_run_0_flaky.log` in `details` of `Integration tests flaky check (asan) — Invalid check_status.tsv `
you will see:
```
=============================== warnings summary ===============================
test_materialized_mysql_database/test.py::test_mysql_killed_while_insert_5_7
  /usr/local/lib/python3.10/dist-packages/_pytest/threadexception.py:73: PytestUnhandledThreadExceptionWarning: Exception in thread Thread-1 (insert)
  
  Traceback (most recent call last):
    File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
      self.run()
    File "/usr/lib/python3.10/threading.py", line 953, in run
      self._target(*self._args, **self._kwargs)
    File "/ClickHouse/tests/integration/test_materialized_mysql_database/materialized_with_ddl.py", line 1401, in insert
      mysql_node.query(query)
    File "/ClickHouse/tests/integration/test_materialized_mysql_database/test.py", line 101, in query
      cursor.execute(execution_query)
    File "/usr/local/lib/python3.10/dist-packages/pymysql/cursors.py", line 153, in execute
      result = self._query(query)
    File "/usr/local/lib/python3.10/dist-packages/pymysql/cursors.py", line 322, in _query
      conn.query(q)
    File "/usr/local/lib/python3.10/dist-packages/pymysql/connections.py", line 558, in query
      self._affected_rows = self._read_query_result(unbuffered=unbuffered)
    File "/usr/local/lib/python3.10/dist-packages/pymysql/connections.py", line 822, in _read_query_result
      result.read()
    File "/usr/local/lib/python3.10/dist-packages/pymysql/connections.py", line 1200, in read
      first_packet = self.connection._read_packet()
    File "/usr/local/lib/python3.10/dist-packages/pymysql/connections.py", line 772, in _read_packet
      packet.raise_for_error()
    File "/usr/local/lib/python3.10/dist-packages/pymysql/protocol.py", line 221, in raise_for_error
      err.raise_mysql_exception(self._data)
    File "/usr/local/lib/python3.10/dist-packages/pymysql/err.py", line 143, in raise_mysql_exception
      raise errorclass(errno, errval)
  pymysql.err.OperationalError: (1053, 'Server shutdown in progress')
  
    warnings.warn(pytest.PytestUnhandledThreadExceptionWarning(msg))

test_materialized_mysql_database/test.py::test_mysql_killed_while_insert_8_0
  /usr/local/lib/python3.10/dist-packages/_pytest/threadexception.py:73: PytestUnhandledThreadExceptionWarning: Exception in thread Thread-2 (insert)
  
  Traceback (most recent call last):
    File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
      self.run()
    File "/usr/lib/python3.10/threading.py", line 953, in run
      self._target(*self._args, **self._kwargs)
    File "/ClickHouse/tests/integration/test_materialized_mysql_database/materialized_with_ddl.py", line 1401, in insert
      mysql_node.query(query)
    File "/ClickHouse/tests/integration/test_materialized_mysql_database/test.py", line 100, in query
      with self.alloc_connection().cursor() as cursor:
    File "/ClickHouse/tests/integration/test_materialized_mysql_database/test.py", line 97, in alloc_connection
      raise Exception("Connection not establised, {}".format(errors))
  Exception: Connection not establised, ['(2003, "Can\'t connect to MySQL server on \'172.16.1.3\' ([Errno 111] Connection refused)")', '(2003, "Can\'t connect to MySQL server on \'172.16.1.3\' ([Errno 111] Connection refused)")', '(2003, "Can\'t connect to MySQL server on \'172.16.1.3\' ([Errno 111] Connection refused)")', '(2003, "Can\'t connect to MySQL server on \'172.16.1.3\' ([Errno 111] Connection refused)")', '(2003, "Can\'t connect to MySQL server on \'172.16.1.3\' ([Errno 111] Connection refused)")']
```

**Comment by kssenii** [comment]
hm, but looks like it is just a warning 🤔

**Comment by valbok** [comment]
thanks

**Pull request merged**
