### PR TITLE
Attempt to fix a possible deadlock

### LINKED ISSUE #51820: Replicas enter a "stuck" state when global threads pool is saturated
**Describe the unexpected behaviour**
If ClickHouse replicas reach `max_thread_pool_size` (Size of the global thread pool)  and  also saturate `max_thread_pool_size` (global thread pool queue size), 

**How to reproduce**

Encountered in v22.3, but reproducible in build from the master branch.

Set `max_thread_pool_size` to a low value such as 300, and `max_thread_pool_size` to disable queueing .

clickhouse benchmark  --max-consecutive-errors 1000 -c 50 -h <hostname>   --cumulative  --query "SELECT sleep(3)"

After several seconds,  queries in ClickHouse benchmark will begin to hang and return `Code: 209. DB::NetException: Timeout: connect timed out` errors as we hit timeouts.

No existing queries make progress. Here's a high-level summary of threads per name on a replica in this condition:
```
sudo ps  -T -p $(pidof clickhouse-server) -o pid,tid,stat,time,comm | awk '{ print $5 }' | sort | uniq -c
      1 AsyncMetrics
    128 BgSchPool
      1 BgSchPool/D
     10 clickhouse-serv
      1 COMMAND
      8 Common
      2 ConfigReloader
      1 DDLWorker
      1 DDLWorkerClnr
      1 DictReload
      3 ExterLdrReload
      8 Fetch
      1 HTTPHandler
     40 MergeMutate
      8 Move
     84 QueryPipelineEx
     10 SystemLogFlush
    193 TCPHandler
      1 TraceCollector
```
All threads that use the global thread pool are stuck. (`QueryPipelineEx` for example).

Looking at the state of threads in GDB, TCP Handler and Query Pipeline threads are all blocked on a mutex:

```
Thread 499 (Thread 0x7efb8dbe3700 (LWP 2466) "TCPHandler"):
#0  futex_wait_cancelable (private=0, expected=0, futex_word=0x7f07c3b79764) at ../sysdeps/nptl/futex-internal.h:186
#1  __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x7f07c3b79710, cond=0x7f07c3b79738) at pthread_cond_wait.c:508
#2  __pthread_cond_wait (cond=0x7f07c3b79738, mutex=0x7f07c3b79710) at pthread_cond_wait.c:638
#3  0x00000000159c52a1 in Poco::EventImpl::waitImpl() ()
#4  0x0000000015a37eda in Poco::PooledThread::run() ()
#5  0x0000000015a35300 in Poco::ThreadImpl::runnableEntry(void*) ()
#6  0x00007f096b378ea7 in start_thread (arg=<optimized out>) at pthread_create.c:477
#7  0x00007f096b288a2f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 498 (Thread 0x7efb8e3e4700 (LWP 2465) "TCPHandler"):
#0  futex_wait_cancelable (private=0, expected=0, futex_word=0x7f07c3b78d64) at ../sysdeps/nptl/futex-internal.h:186
#1  __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x7f07c3b78d10, cond=0x7f07c3b78d38) at pthread_cond_wait.c:508
#2  __pthread_cond_wait (cond=0x7f07c3b78d38, mutex=0x7f07c3b78d10) at pthread_cond_wait.c:638
#3  0x00000000159c52a1 in Poco::EventImpl::waitImpl() ()
#4  0x0000000015a37eda in Poco::PooledThread::run() ()
#5  0x0000000015a35300 in Poco::ThreadImpl::runnableEntry(void*) ()
```

Pipeline Executor thread:
```
Thread 15 (Thread 0x7f0944dfe700 (LWP 24) "QueryPipelineEx"):
#0  futex_wait_cancelable (private=0, expected=0, futex_word=0x7f08ca3d5360) at ../sysdeps/nptl/futex-internal.h:186
#1  __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x7f08ca3d5368, cond=0x7f08ca3d5338) at pthread_cond_wait.c:508
#2  __pthread_cond_wait (cond=0x7f08ca3d5338, mutex=0x7f08ca3d5368) at pthread_cond_wait.c:638
#3  0x000000001477f1cb in DB::ExecutionThreadContext::wait(std::__1::atomic<bool>&) ()
#4  0x00000000147728d5 in DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*) ()
#5  0x00000000147747a4 in void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPool::ThreadFromGlobalPool<DB::PipelineExecutor::executeImpl(unsigned long)::$_1>(DB::PipelineExecutor::executeImpl(unsigned long)::$_1&&)::{lambda()#1}, void ()> >(std::__1::__function::__policy_storage const*) ()
#6  0x0000000009ba4017 in ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) ()
#7  0x0000000009ba7b9d in void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::{lambda()#2}> >(void*) ()
#8  0x00007f096b378ea7 in start_thread (arg=<optimized out>) at pthread_create.c:477
#9  0x00007f096b288a2f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

I will add an integration test to reproduce this also, but has anyone else seen this or got any thoughts on behaviour when the Global thread pool is saturated?

**Expected behavior**
The expected behaviour is for ClickHouse to return an error to clients on any new requests that are made via HTTP or the Native protocol, but not enter this state and for existing threads to  to not be affected.

### PR DESCRIPTION
**Pull request by nikitamikhaylov**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Avoid possible deadlock which usually may occur after changing `max_thread_pool_size` to some miserable value while server experiences heavy SELECT load. This closes: https://github.com/ClickHouse/ClickHouse/issues/51820

### CODE REVIEW

**Comment by nikitamikhaylov** [comment]
I will check another places where we use `scheduleOrThrowOnError`.

**Comment by robot-clickhouse** [comment]
*This is an automated comment for commit 8aacb89a99fc98e35b6d580d4fe9cb933d829b3f with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/56431/8aacb89a99fc98e35b6d580d4fe9cb933d829b3f/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td><a href="https://github.com/ClickHouse/ClickHouse/actions/runs/6790800310">✅ success</a></td></tr>
<tbody>
</table>
</details>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/56431/8aacb89a99fc98e35b6d580d4fe9cb933d829b3f/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Comment by seandhaynes** [comment]
Thank you so much for working on this, @nikitamikhaylov . Sorry for the delay in looking at it myself, too.

I made a PR for this too https://github.com/ClickHouse/ClickHouse/pull/59427that also removes use of `scheduleOrThrowOnError` in code that loads part metadata on startup. As I found that ClickHouse can get deadlocked when starting due to the same issue. I've also added an integration test which passes in our CI, as well as confirming these changes work for us in several clusters.

Feel free to delete it if you prefer your change, but otherwise would love your review.

PR: https://github.com/ClickHouse/ClickHouse/pull/59427

Thanks again!

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
Duplicate.

**Pull request closed without merging**
