### PR TITLE
Cherry pick #38838 to 22.3: Update simdjson

### PR DESCRIPTION
**Pull request by robot-clickhouse**
Original pull-request #38838

This pull-request is a first step of an automated backporting.
It contains changes like after calling a local command `git cherry-pick`.
If you intend to continue backporting this changes, then resolve all conflicts if any.
Otherwise, if you do not want to backport them, then just close this pull-request.

The check results does not matter at this step - you can safely ignore them.
Also this pull-request will be merged automatically as it reaches the mergeable state, but you always can merge it manually.

### CODE REVIEW

**Comment by Felixoid** [comment]
@alexey-milovidov @davenger can you decide on the backport, please? It's quite stale and should be either closed or resolved

**Comment by alexey-milovidov** [comment]
This bug is significant, it can lead to crashes.
@davenger if updating simdjson is difficult, let's cut off AVX-512 from it.

**Comment by Felixoid** [comment]
I'd say, one needs just to chose a proper simdjson commit and commit it

**Comment by alexey-milovidov** [comment]
Without this PR people will have crashes on AVX-512 machines if they prefer the older LTS ClickHouse version.

**Comment by alexey-milovidov** [comment]
@davenger older ClickHouse versions are not usable on AVX-512 machines due to this bug.

**Pull request merged**
