### PR TITLE
Configure librdkafka (logging and thread names)

### PR DESCRIPTION
**Pull request by azat**
Changelog category (leave one):
- Improvement

Changelog Entry:
Set thread names for internal threads of rdkafka library. Make logs from rdkafka available in server logs.

#### Notes about thread names

Not only it is nice to have table name in it, but also it was broken before, due to `glibc-compatibility`.
`librdkafka` uses `pthread_setname_np()`, but `glibc-compatibility` makes it noop.
    
      # librdkafka uses rdk: prefix for thread names by default
      $ grep rdk /proc/$(pgrep clickhouse-serv)/task/*/comm
      # just in case:
      $ grep rdk /proc/*/task/*/comm
      $ grep rdk /proc/*/comm
    
      (gdb) disas pthread_setname_np
      Dump of assembler code for function pthread_setname_np:
         0x000000000c603250 <+0>:     xor    %eax,%eax
         0x000000000c603252 <+2>:     retq
      End of assembler dump.

Cc: @filimonov 
Refs: #10657

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]

**Comment by azat** [comment]
@alexey-milovidov FYI I'm observing failure for the test_storage_kafka::test_kafka_virtual_columns2, and it passes if I run only it, but this PR should not affect it, maybe only due to some timing issues, not sure, will take a look

**Comment by filimonov** [comment]
1) Logging in clickhouse logs looks great, interesing when if it's able to log (for example) during destroy.  
2) Thread names are a bit 'out of convention' (other threads use CamelCasing with shortcuts) but ok.  
3) I also have 2 failures locally:  test_kafka_rebalance & test_kafka_virtual_columns2 I didn't check but maybe it's performance-related. Please check that is happening, people will be disappointed if we will make performance (with is not great) worse. I don't have too much ideas here, you can   check/try the `log.queue` setting of rdkafka and / or  consider rd_kafka_set_log_queue as an alternative.

**Comment by azat** [comment]
>people will be disappointed if we will make performance (with is not great) worse

I have the same thoughts, but I've verified that tests passes on the internal CI
But if this is indeed performance related, then people will not see this, since there are debug logs enabled in this tests, which people don't do on production most of the time.

>you can check/try the log.queue setting of rdkafka and / or consider rd_kafka_set_log_queue as an alternative.

Will take a look when will get to this, thanks!

P.S. the performance of the StorageKafka is not great anyway, but this is another topic.

**Comment by filimonov** [comment]
Thread names during the execution of `test_kafka_rebalance`

```
 ps H -o 'tid comm' $(pidof clickhouse)
  TID COMMAND
 8692 clickhouse
 8808 clickhouse
 8809 clickhouse
 8815 clickhouse
 8818 ExterLdrReload
 8819 SystemLogFlush
 8820 SystemLogFlush
 8821 clickhouse
 8822 SystemLogFlush
 8823 SystemLogFlush
 8824 BgSchPool
 8825 BgSchPool
 8826 BgSchPool
 8827 BgSchPool
 8828 BgSchPool
 8829 BgSchPool
 8830 BgSchPool
 8831 BgSchPool
 8832 BgSchPool
 8833 BgSchPool
 8834 BgSchPool
 8835 BgSchPool
 8836 BgSchPool
 8837 BgSchPool
 8838 BgSchPool
 8839 BgSchPool/D
 8840 BgSchPool
 8841 clickhouse
 8842 DDLWorker
 8843 DDLWorkerClnr
 8844 TCPHandler
 8845 TCPHandler
 8846 TCPHandler
 8847 AsyncMetrics
 8851 ZooKeeperSend
 8852 ZooKeeperRecv
 8854 SessionCleaner
 8855 clickhouse
 8856 clickhouse
 8857 clickhouse
 8858 clickhouse
 8859 ConfigReloader
 8860 ConfigReloader
 8861 ExterLdrReload
 8973 QueryPipelineEx
 8993 BackgrProcPool
 8994 BackgrProcPool
 8995 BackgrProcPool
 8996 BackgrProcPool
 8997 BackgrProcPool
 8998 BackgrProcPool
 8999 BackgrProcPool
 9000 BackgrProcPool
 9001 BackgrProcPool
 9002 BackgrProcPool
 9003 BackgrProcPool
 9004 BackgrProcPool
 9005 BackgrProcPool
 9006 BackgrProcPool
 9007 BackgrProcPool
 9008 BackgrProcPool
 9010 QueryPipelineEx
 9011 QueryPipelineEx
 9324 QueryPipelineEx
 9325 QueryPipelineEx
 9326 QueryPipelineEx
 9327 QueryPipelineEx
 9328 QueryPipelineEx
 9366 QueryPipelineEx
13885 TCPHandler
13886 TCPHandler
13900 TCPHandler
14611 rdk:b/kafka_wri
14612 rdk:m/kafka_wri
14613 rdk:b/kafka_wri
14614 rdk:b/kafka_wri
15430 rdk:b/kafka_con
15431 rdk:m/kafka_con
15432 rdk:b/kafka_con
15433 rdk:b/kafka_con
15522 rdk:b/kafka_con
15523 rdk:m/kafka_con
15524 rdk:b/kafka_con
15525 rdk:b/kafka_con
15608 rdk:b/kafka_con
15609 rdk:m/kafka_con
15610 rdk:b/kafka_con
15611 rdk:b/kafka_con
15697 rdk:b/kafka_con
15698 rdk:m/kafka_con
15699 rdk:b/kafka_con
15700 rdk:b/kafka_con
15791 rdk:b/kafka_con
15792 rdk:m/kafka_con
15793 rdk:b/kafka_con
15794 rdk:b/kafka_con
15887 rdk:b/kafka_con
15888 rdk:m/kafka_con
15889 rdk:b/kafka_con
15890 rdk:b/kafka_con
15984 rdk:b/kafka_con
15985 rdk:m/kafka_con
15986 rdk:b/kafka_con
15987 rdk:b/kafka_con
16069 rdk:b/kafka_con
16070 rdk:m/kafka_con
16071 rdk:b/kafka_con
16072 rdk:b/kafka_con
16166 rdk:b/kafka_con
16167 rdk:m/kafka_con
16168 rdk:b/kafka_con
16169 rdk:b/kafka_con
16263 rdk:b/kafka_con
16264 rdk:m/kafka_con
16265 rdk:b/kafka_con
16266 rdk:b/kafka_con
16369 rdk:b/kafka_con
16370 rdk:m/kafka_con
16371 rdk:b/kafka_con
16372 rdk:b/kafka_con
16461 clickhouse
```

**Comment by azat** [comment]
>Thread names are a bit 'out of convention' (other threads use CamelCasing with shortcuts) but ok.

By initial thoughts was:
- keep `rdk` for "compatibility"
- broker/main/background abbrevs
- table name

Don't see where CamelCase can be used here, but suggestions are welcome!

**Pull request merged**
