### PR TITLE
JWT auth with the signature and payload validation

### PR DESCRIPTION
**Pull request by maniak89**
### Changelog category (leave one):
- New Feature

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
- JWT auth with the signature and payload validation

### Documentation entry for user-facing changes

- Added a new jwt_verifier section to config.xml. The JWKS configuration is almost the same as the http_authentication section with the additional Refresh_ms parameter. Additionally, static JWKS from a configuration or file, a static key for verification, is supported.
- Added new authentication function - jwt. The username is extracted from the token payload, and the token's expiration time and signature are checked. Supported in http and native protocols. It can check the JWT payload if necessary.

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-ch-test-poll3** [comment]
*This is an automated comment for commit dd30c7c57b23bbdcbe9d234cc2049257e811474c with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/66058/dd30c7c57b23bbdcbe9d234cc2049257e811474c/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Push to Dockerhub</td><td>The check for building and pushing the CI related docker images to docker hub</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/66058/dd30c7c57b23bbdcbe9d234cc2049257e811474c/push_to_dockerhub_aarch64.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Comment by zvonand** [comment]
@maniak89 do you have plans to continue working on this?

**Comment by maniak89** [comment]
> @maniak89 do you have plans to continue working on this?
> 
> I am asking because I also need to implement similar functionality for #28383; If you are not planning to go on, I will take it from here

I spoke with @alexey-milovidov, he said that this functionality is being implemented by the company's core team and that the security service allegedly discovered some problems, although he did not say what exactly.

**Comment by zvonand** [comment]
@alexey-milovidov this means that jwt will go public? Or this is a wrong idea and it will remain cloud-only?

**Comment by zvonand** [comment]
> If necessary, I can merge the master and resolve conflicts.

Never mind, I already did this

**Comment by maniak89** [comment]
Merge master and resolve conflicts

**Pull request closed without merging**
