### PR TITLE
Basic prepared statements implementation for MySQL interface

### PR DESCRIPTION
**Pull request by slvrtrn**
Related to https://github.com/ClickHouse/ClickHouse/issues/51103 (though does not resolve it fully).

Bare-bones implementation of `COM_STMT_PREPARE`, `COM_STMT_EXECUTE`, `COM_STMT_CLOSE` required to run almost any query with Tableau Online via MySQL interface.

Tableau Online does not send any parameters with those queries; they just wrap it as prepared statements for an unknown reason.

For example:

```
2023-08-04T16:26:38.303416Z	    9 Prepare	SELECT `posts`.`author_id` AS `author_id`,
  SUBSTRING(`posts`.`content`, 1, 1024) AS `content`,
  `posts`.`date` AS `date`,
  `posts`.`description` AS `description`,
  `posts`.`id` AS `id (posts)`,
  `posts`.`title` AS `title`
FROM `posts`
LIMIT 100
2023-08-04T16:26:38.344468Z	    9 Execute	SELECT `posts`.`author_id` AS `author_id`,
  SUBSTRING(`posts`.`content`, 1, 1024) AS `content`,
  `posts`.`date` AS `date`,
  `posts`.`description` AS `description`,
  `posts`.`id` AS `id (posts)`,
  `posts`.`title` AS `title`
FROM `posts`
LIMIT 100
2023-08-04T16:26:38.427837Z	    9 Close stmt	
2023-08-04T16:26:38.489220Z	    9 Prepare	SELECT SUM(1) AS `cnt_posts_C0B5353898404434BB621DFC8BD4D67A_ok`
FROM `posts`
HAVING (COUNT(1) > 0)
2023-08-04T16:26:38.530203Z	    9 Execute	SELECT SUM(1) AS `cnt_posts_C0B5353898404434BB621DFC8BD4D67A_ok`
FROM `posts`
HAVING (COUNT(1) > 0)
2023-08-04T16:26:38.575748Z	    9 Close stmt	

2023-08-04T16:26:39.017798Z	   13 Query	SET NAMES utf8mb4
2023-08-04T16:26:39.058728Z	   13 Query	SET character_set_results = NULL
2023-08-04T16:26:39.099530Z	   13 Query	SET SQL_AUTO_IS_NULL = 0
2023-08-04T16:26:39.142712Z	   13 Prepare	SELECT CONNECTION_ID()
2023-08-04T16:26:39.183812Z	   13 Query	set @@sql_select_limit=DEFAULT
2023-08-04T16:26:39.224552Z	   13 Execute	SELECT CONNECTION_ID()
2023-08-04T16:26:39.268088Z	   13 Close stmt
```

Prior to these changes, MySQLHandler would fail in the case of `COM_STMT_PREPARE`, `COM_STMT_EXECUTE`, and `COM_STMT_CLOSE` commands as they were not implemented at all.

Now Tableau Online can execute its queries just fine.

### Changelog category (leave one):
- New Feature

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Basic implementation of `COM_STMT_PREPARE`, `COM_STMT_EXECUTE`, and `COM_STMT_CLOSE` for MySQL interface (without actual parameters binding support) for compatibility with tools that wrap their queries as prepared statements without parameters.

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features) - WIP

### CODE REVIEW

**Comment by robot-ch-test-poll** [comment]
This is an automated comment for commit 7fdb414793e533444808d111fd29f8fda904e15e with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/53217/7fdb414793e533444808d111fd29f8fda904e15e/ci_running.html)
The overall status of the commit is 🔴 failure

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🔴 failure</td></tr>
<tr><td>Docs Check</td><td>Builds and tests the documentation</td><td>🟡 pending</td></tr>
</table>

**Comment by slvrtrn** [comment]
Closing this for now as it turned out we need to implement https://dev.mysql.com/doc/dev/mysql-server/latest/page_protocol_binary_resultset.html for COM_STMT_EXECUTE to make it work properly.

**Comment by pxaccountforautomation** [comment]
Hello gents! Any new ticket tracking the progress of the implementation that slvrtrn mentioned?

**Comment by slvrtrn** [comment]
@pxaccountforautomation, a new PR from me is coming soon.

**Comment by slvrtrn** [comment]
@pxaccountforautomation, this is the PR I was talking about: #54115

**Comment by pxaccountforautomation** [comment]
Awesome, watching closely! 😉


Mark van Heyningen

[signature_2840904788]

Chief of Staff

[signature_1239581382]

+ 31 618 304 789

px.com<http://www.px.com/>

________________________________

**Pull request closed without merging**
