### PR TITLE
make more SQL queries copyable from docs in one click

### PR DESCRIPTION
**Pull request by serxa**
### Changelog category (leave one):
- Documentation (changelog entry is not required)

### CODE REVIEW

**Review by evillique — APPROVED** [review]

**Comment by DanRoscigno** [comment]
@serxa Thanks for this, I have been doing the same as I edit.  One additional thing I do is change:

<pre>
``` text
</pre>

to 
<pre>
```response
</pre>

as this removes the yellow (orange?) line around the code block to differentiate between things that should be copied and things that should be seen.  What do you think?

![image](https://user-images.githubusercontent.com/25182304/211823981-c0fde238-3c2f-4518-b389-334239bc9457.png)

**Comment by serxa** [comment]
Yes, totally agree. Didn't know about it, will use it for all other changes.

**Comment by DanRoscigno** [comment]
great, I will update this PR

**Comment by DanRoscigno** [comment]
I am done making changes.

**Review by DanRoscigno — APPROVED** [review]
LGTM

**Pull request merged**
