### PR TITLE
Analyzer: Refactor ConstantNode

### PR DESCRIPTION
**Pull request by novikd**
### Changelog category (leave one):

- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Improve new analyzer infrastructure performance via storing `ColumnPtr` instead of `Field` in the `ConstantNode`. Related to #62245.

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

---
### Modify your CI run:
**NOTE:** If your merge the PR with modified CI you **MUST KNOW** what you are doing
**NOTE:** Checked options will be applied if set before CI RunConfig/PrepareRunConfig step

#### Include tests (required builds will be added automatically):
- [ ]  Fast test
- [ ]  Integration Tests
- [ ]  Stateless tests
- [ ]  Stateful tests
- [ ]  Unit tests
- [ ]  Performance tests
- [ ]  All with ASAN
- [ ]  All with TSAN
- [ ]  All with Analyzer
- [ ]  Add your option here

#### Exclude tests:
- [ ]  Fast test
- [ ]  Integration Tests
- [ ]  Stateless tests
- [ ]  Stateful tests
- [ ]  Performance tests
- [ ]  All with ASAN
- [ ]  All with TSAN
- [ ]  All with MSAN
- [ ]  All with UBSAN
- [ ]  All with Coverage
- [ ]  All with Aarch64
- [ ]  Add your option here

#### Extra options:
- [ ]  do not test (only style check)
- [ ]  disable merge-commit (no merge from master before tests)
- [ ]  disable CI cache (job reuse)

#### Only specified batches in multi-batch jobs:
- [ ]  1
- [ ]  2
- [ ]  3
- [ ]  4

### CODE REVIEW

**Comment by robot-ch-test-poll3** [comment]
*This is an automated comment for commit 054c5e3c80cd592148310cadffa456a10a8e6acc with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/63198/054c5e3c80cd592148310cadffa456a10a8e6acc/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

**Comment by vdimir** [comment]
Tests should be easy to fix

`2024.04.30 18:44:37.378482 [ 181713 ] {} <Fatal> BaseDaemon: (version 24.4.1.1, build id: D1BDCDB9412608E981FE716D390AC1A8504D75F9, git hash: 82eda17cc619808ee528b14d47666ba4bf310ddd) (from thread 171436) (query_id: ad2d7db9-e02b-4bbf-9834-0bb0ed9d2528) (query: SELECT (SELECT 1) AS subquery, 1 AS subquery;) Received signal Segmentation fault (11)`)

**Review by vdimir — APPROVED** [review]
Changes looks clear and sane

**Comment by novikd** [comment]
> Tests should be easy to fix

Actually, there is a problem that I don't know how to fix yet. In `ConstantNode::updateTreeHashImpl` we try to call `ColumnObject::updateHashFast` which is not implemented.
It's unclear how to handle this case.

**Pull request merged**
