### PR TITLE
Increase backoff a little for inserts

### PR DESCRIPTION
**Pull request by alesapin**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Increase backoff because with slow builds sometimes 100ms is not enough to recover.

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Review by Algunenano — APPROVED** [review]

**Comment by robot-ch-test-poll** [comment]
*This is an automated comment for commit a3d02291b42ad0de78534bf9ae64a2f0dc3a3826 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/66653/a3d02291b42ad0de78534bf9ae64a2f0dc3a3826/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Fast test</td><td>Normally this is the first check that is ran for a PR. It builds ClickHouse and runs most of <a href="https://clickhouse.com/docs/en/development/tests#functional-tests">stateless functional tests</a>, omitting some. If it fails, further checks are not started until it is fixed. Look at the report to see which tests fail, then reproduce the failure locally as described <a href="https://clickhouse.com/docs/en/development/tests#functional-test-locally">here</a></td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/8c1cff0a7ee2a2d149cd79bf260c5ce749eae24a/fast_test.html">✅ success</a></td></tr>
<tr><td>Unit tests</td><td>Runs the unit tests for different release types</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/5ce0675de82d9b885a6202bf240c9fedfc7006c0/unit_tests__release_.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Comment by alexey-milovidov** [comment]
@alesapin a test for asynchronous inserts has failed.
Fix it by yourself or demand a fix from @CurtizJ.

If you will merge this PR before fixing the test, you take a debt, that I will never forget.

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alesapin** [comment]
@alexey-milovidov I would better close this PR or forget about it. You threatened me too much.

**Comment by alexey-milovidov** [comment]
@alesapin, no worries. Fix the test and move on.

**Comment by alexey-milovidov** [comment]
GRPC: #66509
Async inserts: #66771

**Pull request merged**
