### PR TITLE
Remove extra semicolons

### PR DESCRIPTION
**Pull request by bgaifullin**
### Changelog category (leave one):

- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
...

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by robot-clickhouse** [comment]
This is an automated comment for commit 8556493c9e26164829e8b86c24e7a8e8a18aeb84 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/49545/8556493c9e26164829e8b86c24e7a8e8a18aeb84/ci_running.html)
The overall status of the commit is 🔴 failure

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🔴 failure</td></tr>
<tr><td>Docs Check</td><td>Builds and tests the documentation</td><td>🟡 pending</td></tr>
</table>

**Review by hanfei1991 — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
@hanfei1991 we are using -Weverything, and there is -Wextra-semi.
Interesting why it didn't work.

**Comment by hanfei1991** [comment]
> @hanfei1991 we are using -Weverything, and there is -Wextra-semi. Interesting why it didn't work.

I checked CMake Files and didn't find -Weverything or -Wextra-semi , I also tried to add some extra ;;;;;; and it can compile successfully

**Comment by alexey-milovidov** [comment]
@hanfei1991 this is wrong and we have to fix the root cause.

**Comment by hanfei1991** [comment]
> @hanfei1991 this is wrong and we have to fix the root cause.

I was wrong about it. We did use the `-Weverything`. If I add some ;;; in side a function, there is a warning. But` function () {};;` is not treated as `extra-semi-stmt`.

**Comment by alexey-milovidov** [comment]
Thank you!

@bgaifullin, how did you find this case?

**Comment by bgaifullin** [comment]
I enabled option ‘-Wextra-semi’ for whole project , which also includes clickhouse as submodule.

**Comment by alexey-milovidov** [comment]
@bgaifullin, this is unclear. We enable the `-Wextra-semi` for ClickHouse, so how comes these warnings were not visible in the CI?

**Comment by hanfei1991** [comment]
@alexey-milovidov `-Weverything` contain both `-Wextra-semi-stmt` and `-Wextra-semi`, I added this two options in `cmake/warnings.cmake` but did not found the faults in this PR. I wonder how @bgaifullin did this. Where did you add this flag?

**Comment by bgaifullin** [comment]
I catch this on building my library, that includes files "src/Common/logger_useful.h" and "src/Interpreters/Cache/IFileCachePriority.h". Found that in "src/Interpreters/Cache/LRUFileCachePriority.cpp" also extra semicolon and remove it too.

**Comment by bgaifullin** [comment]
Hmm. Seems like option `-Wextra-semi` will be transformed to `-Wc++98-compat-extra-semi` because of combination of other compiler flags.
```
contrib/clickhouse/src/Common/logger_useful.h:18:104: error: extra ';' outside of a function is incompatible with C++98 [-Werror,-Wc++98-compat-extra-semi]
    [[maybe_unused]] const ::Poco::Logger * getLogger(const ::Poco::Logger * logger) { return logger; };
                                                                                                       ^
clickhouse/src/Common/logger_useful.h:19:126: error: extra ';' outside of a function is incompatible with C++98 [-Werror,-Wc++98-compat-extra-semi]
    [[maybe_unused]] const ::Poco::Logger * getLogger(const std::atomic<::Poco::Logger *> & logger) { return logger.load(); };
```

**Pull request merged**
