### PR TITLE
max_thread_pool_size setting for changing max Threads in Global Thread Pool

### PR DESCRIPTION
**Pull request by bharatnc**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- New Feature

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

`max_thread_pool_size` config for changing the maximum number of Threads in Global Thread Pool.

Detailed description / Documentation draft:

This PR makes the maximum number of threads in the Global Thread Pool configurable. Currently this value defaults to 10000 and is being set inside `ThreadPool.cpp`.

The setting for this option is `max_thread_pool_size` and is being added to the `config.xml` file and is loaded while returning a GlobalThreadPool instance.

Also adds the configuration to relevant tests and docs (en) have also been added.

**Addresses the issue:**  #7099

### CODE REVIEW

**Comment by bharatnc** [comment]
Can't seem to find the reason why `00092_obfuscator` fails consistently with all the tests. Any inputs? Cc: @alexey-milovidov @blinkov

**Review by akuzm — APPROVED** [review]

**Comment by tavplubix** [comment]
It's not false-positive, test fails because there is no instance of `Poco::Util::Application` in `clickhouse-obfuscator`. Some unit tests probably fail for same reason.

```
$ clickhouse-obfuscator --structure "URL String, Title String, SearchPhrase String" --input-format TSV --output-format TSV --seed hello < ${CLICKHOUSE_TMP}/data.tsv > ${CLICKHOUSE_TMP}/data1000.tsv
Training models
Poco::Exception. Code: 1000, e.code() = 0, e.displayText() = Null pointer: _pInstance in file "../contrib/poco/Util/include/Poco/Util/Application.h", line 457, Stack trace (when copying this message, always include the lines below):

0. /home/avtokmakov/ch/ClickHouse/build_debug/../contrib/libcxx/include/exception:129: std::exception::capture() @ 0x15cb1fe8 in /home/avtokmakov/ch/ClickHouse/build_debug/programs/clickhouse
1. /home/avtokmakov/ch/ClickHouse/build_debug/../contrib/libcxx/include/exception:109: std::exception::exception() @ 0x15cb1fb5 in /home/avtokmakov/ch/ClickHouse/build_debug/programs/clickhouse
2. /home/avtokmakov/ch/ClickHouse/build_debug/../contrib/poco/Foundation/src/Exception.cpp:27: Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x2190c1b3 in /home/avtokmakov/ch/ClickHouse/build_debug/programs/clickhouse
3. /home/avtokmakov/ch/ClickHouse/build_debug/../contrib/poco/Foundation/src/Exception.cpp:128: Poco::LogicException::LogicException(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x2190c9ad in /home/avtokmakov/ch/ClickHouse/build_debug/programs/clickhouse
4. /home/avtokmakov/ch/ClickHouse/build_debug/../contrib/poco/Foundation/src/Exception.cpp:130: Poco::NullPointerException::NullPointerException(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x2190d10d in /home/avtokmakov/ch/ClickHouse/build_debug/programs/clickhouse
5. /home/avtokmakov/ch/ClickHouse/build_debug/../contrib/poco/Foundation/src/Bugcheck.cpp:42: Poco::Bugcheck::nullPointer(char const*, char const*, int) @ 0x218ff8fd in /home/avtokmakov/ch/ClickHouse/build_debug/programs/clickhouse
6. /home/avtokmakov/ch/ClickHouse/build_debug/../contrib/poco/Util/include/Poco/Util/Application.h:457: Poco::Util::Application::instance() @ 0x15cf1581 in /home/avtokmakov/ch/ClickHouse/build_debug/programs/clickhouse
7. /home/avtokmakov/ch/ClickHouse/build_debug/../src/Common/ThreadPool.cpp:269: GlobalThreadPool::instance() @ 0x15cee03d in /home/avtokmakov/ch/ClickHouse/build_debug/programs/clickhouse
8. /home/avtokmakov/ch/ClickHouse/build_debug/../src/Common/ThreadPool.h:152: ThreadFromGlobalPool::ThreadFromGlobalPool<DB::ParallelParsingBlockInputStream::ParallelParsingBlockInputStream(DB::ParallelParsingBlockInputStream::Params const&)::'lambda'()>(DB::ParallelParsingBlockInputStream::ParallelParsingBlockInputStream(DB::ParallelParsingBlockInputStream::Params const&)::'lambda'()&&) @ 0x1dd97ca2 in /home/avtokmakov/ch/ClickHouse/build_debug/programs/clickhouse
9. /home/avtokmakov/ch/ClickHouse/build_debug/../src/DataStreams/ParallelParsingBlockInputStream.h:98: DB::ParallelParsingBlockInputStream::ParallelParsingBlockInputStream(DB::ParallelParsingBlockInputStream::Params const&) @ 0x1dd97810 in /home/avtokmakov/ch/ClickHouse/build_debug/programs/clickhouse
10. /home/avtokmakov/ch/ClickHouse/build_debug/../contrib/libcxx/include/memory:2214: std::__1::__compressed_pair_elem<DB::ParallelParsingBlockInputStream, 1, false>::__compressed_pair_elem<DB::ParallelParsingBlockInputStream::Params&, 0ul>(std::__1::piecewise_construct_t, std::__1::tuple<DB::ParallelParsingBlockInputStream::Params&>, std::__1::__tuple_indices<0ul>) @ 0x1dd97498 in /home/avtokmakov/ch/ClickHouse/build_debug/programs/clickhouse
11. /home/avtokmakov/ch/ClickHouse/build_debug/../contrib/libcxx/include/memory:2299: std::__1::__compressed_pair<std::__1::allocator<DB::ParallelParsingBlockInputStream>, DB::ParallelParsingBlockInputStream>::__compressed_pair<std::__1::allocator<DB::ParallelParsingBlockInputStream>&, DB::ParallelParsingBlockInputStream::Params&>(std::__1::piecewise_construct_t, std::__1::tuple<std::__1::allocator<DB::ParallelParsingBlockInputStream>&>, std::__1::tuple<DB::ParallelParsingBlockInputStream::Params&>) @ 0x1dd97185 in /home/avtokmakov/ch/ClickHouse/build_debug/programs/clickhouse
12. /home/avtokmakov/ch/ClickHouse/build_debug/../contrib/libcxx/include/memory:3569: std::__1::__shared_ptr_emplace<DB::ParallelParsingBlockInputStream, std::__1::allocator<DB::ParallelParsingBlockInputStream> >::__shared_ptr_emplace<DB::ParallelParsingBlockInputStream::Params&>(std::__1::allocator<DB::ParallelParsingBlockInputStream>, DB::ParallelParsingBlockInputStream::Params&) @ 0x1dd96e1a in /home/avtokmakov/ch/ClickHouse/build_debug/programs/clickhouse
13. /home/avtokmakov/ch/ClickHouse/build_debug/../contrib/libcxx/include/memory:4400: std::__1::enable_if<!(is_array<DB::ParallelParsingBlockInputStream>::value), std::__1::shared_ptr<DB::ParallelParsingBlockInputStream> >::type std::__1::make_shared<DB::ParallelParsingBlockInputStream, DB::ParallelParsingBlockInputStream::Params&>(DB::ParallelParsingBlockInputStream::Params&) @ 0x1dd948f0 in /home/avtokmakov/ch/ClickHouse/build_debug/programs/clickhouse
14. /home/avtokmakov/ch/ClickHouse/build_debug/../src/Formats/FormatFactory.cpp:190: DB::FormatFactory::getInput(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::ReadBuffer&, DB::Block const&, DB::Context const&, unsigned long, std::__1::function<void ()>) const @ 0x1dd916bb in /home/avtokmakov/ch/ClickHouse/build_debug/programs/clickhouse
15. /home/avtokmakov/ch/ClickHouse/build_debug/../src/Interpreters/Context.cpp:1903: DB::Context::getInputFormat(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::ReadBuffer&, DB::Block const&, unsigned long) const @ 0x1cbfa175 in /home/avtokmakov/ch/ClickHouse/build_debug/programs/clickhouse
16. /home/avtokmakov/ch/ClickHouse/build_debug/../programs/obfuscator/Obfuscator.cpp:1107: mainEntryClickHouseObfuscator(int, char**) @ 0x15ecbb4d in /home/avtokmakov/ch/ClickHouse/build_debug/programs/clickhouse
17. /home/avtokmakov/ch/ClickHouse/build_debug/../programs/main.cpp:324: main @ 0x15c9d385 in /home/avtokmakov/ch/ClickHouse/build_debug/programs/clickhouse
18. /build/glibc-OTsEL5/glibc-2.27/csu/../csu/libc-start.c:344: __libc_start_main @ 0x21b97 in /usr/lib/debug/lib/x86_64-linux-gnu/libc-2.27.so
19. _start @ 0x15c9d02a in /home/avtokmakov/ch/ClickHouse/build_debug/programs/clickhouse
 (version 20.5.1.1)
```

**Comment by bharatnc** [comment]
Thank you @akuzm for your help with fixing the failing test.

**Comment by akuzm** [comment]
> Thank you @akuzm for your help with fixing the failing test.

You're welcome.

'Yandex third-party checks' are broken for a different reason, will merge now.

**Pull request merged**
