### PR TITLE
Fix build type in packager

### PR DESCRIPTION
**Pull request by antonio2368**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Bring back https://github.com/ClickHouse/ClickHouse/pull/51679

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by robot-clickhouse** [comment]
This is an automated comment for commit 62afba24fb11761f67a98cbee85038077a3e4cd5 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/51771/62afba24fb11761f67a98cbee85038077a3e4cd5/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Comment by Felixoid** [comment]
Is the change for `test_keeper_map/test.py::test_keeper_map_without_zk` already merged?

And I am not sure what to do with upgrade checks

**Review by Felixoid — APPROVED** [review]

**Comment by antonio2368** [comment]
@Felixoid can you please check `BuilderBinRISCV64`

**Comment by Felixoid** [comment]
It misses the value in https://github.com/ClickHouse/ClickHouse/pull/51771/files#diff-8f5d1b66ee5a990f00850abe775dcf98c2043fabebdd21a6a35ac1e529138410R176

**Comment by antonio2368** [comment]
@Felixoid let's merge?

**Comment by Felixoid** [comment]
The related tests are successful, merging after the update

**Pull request merged**
