### PR TITLE
fix s3Cluster function returns NOT_FOUND_COLUMN_IN_BLOCK error

### LINKED ISSUE #43534: s3Cluster function returns NOT_FOUND_COLUMN_IN_BLOCK error
(you don't have to strictly follow this form)

**Describe the unexpected behaviour**
We are seeing errors like 
```
Received exception from server (version 22.10.2):
Code: 10. DB::Exception: Received from localhost:9000. DB::Exception: Not found column count() in block. There are only columns: COUNT(): While executing Remote. (NOT_FOUND_COLUMN_IN_BLOCK)
```

when trying to use **s3Cluster** function to query data using queries like: ```SELECT COUNT(*) FROM s3Cluster('cluster', 'https://...', ...)```

However **s3** function works fine.
 
* Which ClickHouse server version to use
22.11 and 22.10 are seeing this issue. 

**Expected behavior**
Expected s3Cluster function runs successfully.  

**Error message and/or stacktrace**
See description. 

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by xiedeyantu**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in official stable or prestable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
fix s3Cluster function returns NOT_FOUND_COLUMN_IN_BLOCK error. Closes #43534

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by xiedeyantu** [comment]
Hi @nickitat , Mergeable Check keep Waiting

**Comment by xiedeyantu** [comment]
Hi @nickitat, please review this pr.

**Comment by nickitat** [comment]
pls check failures of `test_s3_cluster/test.py::test_ambiguous_join`

```
E           helpers.client.QueryRuntimeException: Client failed! Return code: 96, stderr: Received exception from server (version 22.12.1):
E           Code: 352. DB::Exception: Received from 172.16.12.7:9000. DB::Exception: Received from s0_0_0:9000. DB::Exception: Column 'name' is ambiguous: While processing name = r.name. Stack trace:
E           
E           0. ./build_docker/../contrib/libcxx/include/exception:0: Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, int) @ 0x21d9e53e in /usr/bin/clickhouse
E           1. ./build_docker/../src/Common/Exception.cpp:77: DB::Exception::Exception(DB::Exception::MessageMasked const&, int, bool) @ 0x13becd5c in /usr/bin/clickhouse
E           2. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, int, bool) @ 0xbc8d563 in /usr/bin/clickhouse
E           3. ./build_docker/../src/Interpreters/CollectJoinOnKeysVisitor.cpp:0: DB::CollectJoinOnKeysMatcher::getTableForIdentifiers(std::__1::shared_ptr<DB::IAST> const&, bool, DB::CollectJoinOnKeysMatcher::Data const&) @ 0x1d114f27 in /usr/bin/clickhouse
E           4. ./build_docker/../src/Interpreters/CollectJoinOnKeysVisitor.cpp:0: DB::CollectJoinOnKeysMatcher::visit(DB::ASTFunction const&, std::__1::shared_ptr<DB::IAST> const&, DB::CollectJoinOnKeysMatcher::Data&) @ 0x1d115820 in /usr/bin/clickhouse
E           5. ./build_docker/../src/Interpreters/CollectJoinOnKeysVisitor.h:61: DB::InDepthNodeVisitor<DB::CollectJoinOnKeysMatcher, true, false, std::__1::shared_ptr<DB::IAST> const>::doVisit(std::__1::shared_ptr<DB::IAST> const&) @ 0x1d0ac04c in /usr/bin/clickhouse
E           6. ./build_docker/../src/Interpreters/InDepthNodeVisitor.h:0: DB::TreeRewriter::analyzeSelect(std::__1::shared_ptr<DB::IAST>&, DB::TreeRewriterResult&&, DB::SelectQueryOptions const&, std::__1::vector<DB::TableWithColumnNamesAndTypes, std::__1::allocator<DB::TableWithColumnNamesAndTypes>> const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>> const&, std::__1::shared_ptr<DB::TableJoin>) const @ 0x1d099156 in /usr/bin/clickhouse
E           7. ./build_docker/../src/Interpreters/InterpreterSelectQuery.cpp:0: DB::InterpreterSelectQuery::InterpreterSelectQuery(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context> const&, std::__1::optional<DB::Pipe>, std::__1::shared_ptr<DB::IStorage> const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>> const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::shared_ptr<DB::PreparedSets>)::$_2::operator()(bool) const @ 0x1ccedf7d in /usr/bin/clickhouse
E           8. ./build_docker/../src/Interpreters/InterpreterSelectQuery.cpp:0: DB::InterpreterSelectQuery::InterpreterSelectQuery(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context> const&, std::__1::optional<DB::Pipe>, std::__1::shared_ptr<DB::IStorage> const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>> const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::shared_ptr<DB::PreparedSets>) @ 0x1ccea886 in /usr/bin/clickhouse
E           9. ./build_docker/../contrib/libcxx/include/optional:260: DB::InterpreterSelectQuery::InterpreterSelectQuery(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context> const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>> const&) @ 0x1cce70e6 in /usr/bin/clickhouse
E           10. ./build_docker/../src/Interpreters/InterpreterSelectWithUnionQuery.cpp:251: DB::InterpreterSelectWithUnionQuery::buildCurrentChildInterpreter(std::__1::shared_ptr<DB::IAST> const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>> const&) @ 0x1cda675f in /usr/bin/clickhouse
E           11. ./build_docker/../src/Interpreters/InterpreterSelectWithUnionQuery.cpp:150: DB::InterpreterSelectWithUnionQuery::InterpreterSelectWithUnionQuery(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context>, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>> const&) @ 0x1cda3eb2 in /usr/bin/clickhouse
E           12. ./build_docker/../contrib/libcxx/include/__memory/unique_ptr.h:0: std::__1::__unique_if<DB::InterpreterSelectWithUnionQuery>::__unique_single std::__1::make_unique[abi:v15003]<DB::InterpreterSelectWithUnionQuery, std::__1::shared_ptr<DB::IAST>&, std::__1::shared_ptr<DB::Context>&, DB::SelectQueryOptions const&>(std::__1::shared_ptr<DB::IAST>&, std::__1::shared_ptr<DB::Context>&, DB::SelectQueryOptions const&) @ 0x1cc9f749 in /usr/bin/clickhouse
E           13. ./build_docker/../src/Interpreters/InterpreterFactory.cpp:0: DB::InterpreterFactory::get(std::__1::shared_ptr<DB::IAST>&, std::__1::shared_ptr<DB::Context>, DB::SelectQueryOptions const&) @ 0x1cc9e808 in /usr/bin/clickhouse
E           14. ./build_docker/../src/Interpreters/executeQuery.cpp:0: DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, DB::ReadBuffer*) @ 0x1d17851d in /usr/bin/clickhouse
E           15. ./build_docker/../src/Interpreters/executeQuery.cpp:1083: DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum) @ 0x1d175c6c in /usr/bin/clickhouse
E           16. ./build_docker/../src/Server/TCPHandler.cpp:0: DB::TCPHandler::runImpl() @ 0x1e2c3b86 in /usr/bin/clickhouse
E           17. ./build_docker/../src/Server/TCPHandler.cpp:1904: DB::TCPHandler::run() @ 0x1e2d7ac8 in /usr/bin/clickhouse
E           18. ./build_docker/../contrib/poco/Net/src/TCPServerConnection.cpp:57: Poco::Net::TCPServerConnection::start() @ 0x21bdd023 in /usr/bin/clickhouse
E           19. ./build_docker/../contrib/libcxx/include/__memory/unique_ptr.h:48: Poco::Net::TCPServerDispatcher::run() @ 0x21bdd893 in /usr/bin/clickhouse
E           20. ./build_docker/../contrib/poco/Foundation/src/ThreadPool.cpp:213: Poco::PooledThread::run() @ 0x21e37bda in /usr/bin/clickhouse
E           21. ./build_docker/../contrib/poco/Foundation/src/Thread.cpp:56: Poco::(anonymous namespace)::RunnableHolder::run() @ 0x21e35f90 in /usr/bin/clickhouse
E           22. ./build_docker/../contrib/poco/Foundation/include/Poco/SharedPtr.h:277: Poco::ThreadImpl::runnableEntry(void*) @ 0x21e345c8 in /usr/bin/clickhouse
E           23. __tsan_thread_start_func @ 0xbc01d67 in /usr/bin/clickhouse
E           24. ? @ 0x7f916192a609 in ?
E           25. __clone @ 0x7f916184f133 in ?
E           : While executing Remote. Stack trace:
E           
E           0. ./build_docker/../contrib/libcxx/include/exception:0: Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, int) @ 0x21d9e53e in /usr/bin/clickhouse
E           1. ./build_docker/../src/Common/Exception.cpp:77: DB::Exception::Exception(DB::Exception::MessageMasked const&, int, bool) @ 0x13becd5c in /usr/bin/clickhouse
E           2. ./build_docker/../contrib/libcxx/include/string:1499: DB::readException(DB::ReadBuffer&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, bool) @ 0x13c60807 in /usr/bin/clickhouse
E           3. ./build_docker/../contrib/libcxx/include/__memory/unique_ptr.h:714: DB::Connection::receiveException() const @ 0x1e1a6f29 in /usr/bin/clickhouse
E           4. ./build_docker/../src/Client/Connection.cpp:0: DB::Connection::receivePacket() @ 0x1e1af3ee in /usr/bin/clickhouse
E           5. ./build_docker/../src/Client/MultiplexedConnections.cpp:0: DB::MultiplexedConnections::receivePacketUnlocked(std::__1::function<void (int, Poco::Timespan, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&)>, bool) @ 0x1e1ecc75 in /usr/bin/clickhouse
E           6. ./build_docker/../contrib/libcxx/include/__functional/function.h:818: DB::MultiplexedConnections::receivePacket() @ 0x1e1ec6ec in /usr/bin/clickhouse
E           7. ./build_docker/../src/QueryPipeline/RemoteQueryExecutor.cpp:280: DB::RemoteQueryExecutor::read() @ 0x1ba70bd3 in /usr/bin/clickhouse
E           8. ./build_docker/../src/Processors/Sources/RemoteSource.cpp:0: DB::RemoteSource::tryGenerate() @ 0x1e6e36a2 in /usr/bin/clickhouse
E           9. ./build_docker/../contrib/libcxx/include/optional:344: DB::ISource::work() @ 0x1e32460a in /usr/bin/clickhouse
E           10. ./build_docker/../contrib/libcxx/include/list:588: DB::ExecutionThreadContext::executeTask() @ 0x1e34a913 in /usr/bin/clickhouse
E           11. ./build_docker/../src/Processors/Executors/PipelineExecutor.cpp:229: DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*) @ 0x1e33bb41 in /usr/bin/clickhouse
E           12. ./build_docker/../src/Processors/Executors/PipelineExecutor.cpp:0: void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PipelineExecutor::spawnThreads()::$_0>(DB::PipelineExecutor::spawnThreads()::$_0&&)::'lambda'(), void ()>>(std::__1::__function::__policy_storage const*) @ 0x1e33d3ec in /usr/bin/clickhouse
E           13. ./build_docker/../base/base/wide_integer_impl.h:774: ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x13cdbad1 in /usr/bin/clickhouse
E           14. ./build_docker/../contrib/libcxx/include/__memory/unique_ptr.h:302: void* std::__1::__thread_proxy[abi:v15003]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()>>(void*) @ 0x13ce0292 in /usr/bin/clickhouse
E           15. __tsan_thread_start_func @ 0xbc01d67 in /usr/bin/clickhouse
E           16. ? @ 0x7f916192a609 in ?
E           17. __clone @ 0x7f916184f133 in ?
E           . (AMBIGUOUS_COLUMN_NAME)
E           (query: SELECT l.name, r.value from s3Cluster(
E                   'cluster_simple', 
E                   'http://minio1:9001/root/data/{clickhouse,database}/*', 'minio', 'minio123', 'CSV', 
E                   'name String, value UInt32, polygon Array(Array(Tuple(Float64, Float64)))') as l
E               JOIN s3Cluster(
E                   'cluster_simple', 
E                   'http://minio1:9001/root/data/{clickhouse,database}/*', 'minio', 'minio123', 'CSV', 
E                   'name String, value UInt32, polygon Array(Array(Tuple(Float64, Float64)))') as r
E               ON l.name = r.name
E               )
```

**Comment by xiedeyantu** [comment]
@nickitat I have fixed.

**Review by nickitat — APPROVED** [review]
lgtm

**Comment by nickitat** [comment]
let's wait for rerun of stateless tests

**Comment by fishzhe** [comment]
Is there any chance to back this fix to impacted versions?

**Comment by nickitat** [comment]
> Is there any chance to back this fix to impacted versions?

for some reason this fix is not enough for 22.10 (and older I guess). it was backported in 22.11 and will be available with the next patch release.

**Pull request merged**
