### PR TITLE
Allow to provide the protocol version by HTTP clients to tune the compatibility of the Native output format.

### PR DESCRIPTION
**Pull request by genzgd**
Add client_protocol_revision to Context and NativeOutputFormat, set by an HTTP client parameter.  This allows HTTP clients using the NativeFormat to utilize updates/changes in the Native protocol as appropriate.

### Changelog category (leave one):
- New Feature

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
The new http parameter `client_protocol_version` allows setting a client protocol version for HTTP responses using the Native format.  https://github.com/ClickHouse/ClickHouse/issues/40397

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
Let's add Changelog and tests.

**Comment by alexey-milovidov** [comment]
@genzgd tests cannot even start unless the Changelog is provided.

**Comment by genzgd** [comment]
Yeah I wanted to actually add at least one http test :)

**Review by alexey-milovidov — APPROVED** [review]
Ok, but it was much better to use a functional test (.sh) instead of integration.

**Pull request merged**
