### PR TITLE
Lightweight delete

### PR DESCRIPTION
**Pull request by Enmk**
Changelog category (leave one):
- New Feature

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
Let's reuse UInt8 format without introducing any new formats for tombstones.

**Comment by antip00** [comment]
https://gist.github.com/antip00/881f02f407443b4860a8669c78743ffe

**Comment by zhangjmruc** [comment]
@alexey-milovidov @Enmk Hi Enmk, Alexey, would you please help to take a look at the pull request #35090? We can work together for the lightweight delete on merge tree.

**Comment by alexey-milovidov** [comment]
Superseded by #35090
@davenger is reviewing #35090

**Pull request closed without merging**
