### PR TITLE
Rebind ports and restart integration test if clash

### PR DESCRIPTION
**Pull request by ilejn**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Addresses https://github.com/ClickHouse/ClickHouse/issues/54753

get_free_port used in cluster.py is not 100% reliable, it is possible to have collisions especially if several tests are run in parallel.

This PR solves this issue in the most brutal possible way: make another attempt to get free ports if a collision is detected. This approach is taken deliberately because it should not cause any new issues.

### CODE REVIEW

**Comment by robot-ch-test-poll2** [comment]
*This is an automated comment for commit 91f517fd7abdd5d94fb643b10a7cfcae5b7d169f with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/55055/91f517fd7abdd5d94fb643b10a7cfcae5b7d169f/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>✅ success</td></tr>
<tbody>
</table>
</details>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>⏳ pending</td></tr>
<tbody>
</table>

**Comment by alexey-milovidov** [comment]
It caused some issues.

**Comment by ilejn** [comment]
> It caused some issues.

Probably fixed.
Errors in Stress and Upgrade tests looks unrelated but worrying, so I'll try to rebase to fresh master to ensure.

**Comment by alexey-milovidov** [comment]
Something strange with `disk_over_web_server`: https://s3.amazonaws.com/clickhouse-test-reports/55055/42b8b2618da5bbeed0bc346bfa8594625bc8398d/integration_tests__asan__analyzer__[5_6].html

**Comment by ilejn** [comment]
> Something strange with `disk_over_web_server`: [https://s3.amazonaws.com/clickhouse-test-reports/55055/42b8b2618da5bbeed0bc346bfa8594625bc8398d/integration_tests__asan__analyzer__[5_6].html](https://s3.amazonaws.com/clickhouse-test-reports/55055/42b8b2618da5bbeed0bc346bfa8594625bc8398d/integration_tests__asan__analyzer__%5B5_6%5D.html)

Issues with these tests are not rare https://play.clickhouse.com/play?user=play#c2VsZWN0IAp0ZXN0X25hbWUsIHB1bGxfcmVxdWVzdF9udW1iZXIsIHRlc3Rfc3RhdHVzLCBjaGVja19zdGFydF90aW1lCmZyb20gY2hlY2tzIHdoZXJlICcyMDIyLTEwLTAxJyA8PSBjaGVja19zdGFydF90aW1lIGFuZCB0ZXN0X25hbWUgbGlrZSAndGVzdF9kaXNrX292ZXJfd2ViX3NlcnZlciUnICBhbmQgdGVzdF9zdGF0dXMgaW4gKCdGQUlMJywgJ0ZMQUtZJywgJ0VSUk9SJykKb3JkZXIgYnkgY2hlY2tfc3RhcnRfdGltZTsg

**Comment by alexey-milovidov** [comment]
It's a question that needs investigation.

**Comment by ilejn** [comment]
Hello @alexey-milovidov , 
do you think that restart is generally acceptable approach?
If yes, can we go further with this PR?

**Comment by alexey-milovidov** [comment]
I didn't review this PR, but currently, there are five failed checks. We cannot proceed until we resolve this tech debt.
And if you don't want to wait while we are fixing these checks, you can help us by investigating and fixing them.

**Comment by ilejn** [comment]
> I didn't review this PR, but currently, there are five failed checks. We cannot proceed until we resolve this tech debt. And if you don't want to wait while we are fixing these checks, you can help us by investigating and fixing them.

I see. But this PR was created to resolve a failed check. We can create a deadlock putting it on hold ;)
Seriously speaking, I will try to look into disk_over_web_server thing, while I doubt that it is something trivial.

**Comment by ilejn** [comment]
> I didn't review this PR, but currently, there are five failed checks. We cannot proceed until we resolve this tech debt. And if you don't want to wait while we are fixing these checks, you can help us by investigating and fixing them.

Memory leak in test_checking_s3_blobs_paranoid/test.py::test_when_s3_connection_reset_by_peer_at_upload_is_retried[True] 
is already fixed by @azat in
https://github.com/ClickHouse/ClickHouse/commit/28f17bec96a521213360f41f29f1915b9e4393fb .

I was too lazy to check if code was changed between this crash and fresh master I used trying to understand what is going on ;)

**Comment by azat** [comment]
Interesting way to solve this, but kind of a hack I guess.
I was trying to fix this differently - https://github.com/ClickHouse/ClickHouse/pull/53266
But the problem is that tests uses containers via exposed ports, if this will be fixed instead, everything else is easy to fix.

Also I'm wondering will the test still be reported as `ERROR` because of https://github.com/ClickHouse/ClickHouse/pull/55261 ?

**Comment by ilejn** [comment]
> Interesting way to solve this, but kind of a hack I guess.

Agree.
I just called it "brutal" ;)

> I was trying to fix this differently - #53266 But the problem is that tests uses containers via exposed ports, if this will be fixed instead, everything else is easy to fix.

It is almost impossible to explain why we need to have these ports exposed, so we probably need not.

> Also I'm wondering will the test still be reported as `ERROR` because of #55261 ?

No clue.

**Comment by alexey-milovidov** [comment]
@thevar1able Please continue.

**Comment by azat** [comment]
Just my two cents, I still think that this way is error prone and hacky, instead, simply not listen on all interfaces will be enough, but this will require adjusting the users to use the IP of the container, but this should be trivial

**Pull request closed without merging**
