### PR TITLE
[test][integration] Attempt to break default database inference by setting an intercluster secret

### PR DESCRIPTION
**Pull request by tonickkozlov**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
...

> Information about CI checks: https://clickhouse.tech/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by tonickkozlov** [comment]
A bit of context of this change: I'm trying to reproduce an issue I've seen locally when using distributed tables.
Adding an intercluster secret seems to be breaking default database inference - not sure if that's intentional but it looks like a change in behaviour since 21.8.
What I'm seeing locally (and what I expect in CI) is the () test breaking with error
```
There is no table ``.`replicated` on server: node2:9000                                                                                        There is no table ``.`replicated` on server: node1:9000
```

**Comment by nvartolomei** [comment]
@mergifyio update

**Comment by alexey-milovidov** [comment]
@mergifyio update

**Comment by alexey-milovidov** [comment]
I don't see any relevant failures. Let's close?

**Comment by tonickkozlov** [comment]
Good point @alexey-milovidov , closing this now.

**Pull request closed without merging**
