### PR TITLE
Do not reset Annoy index during build-up with > 1 mark

### PR DESCRIPTION
**Pull request by xinhuitian**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix results of queries utilizing the Annoy index when the part has more than one mark.

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
A test needed.

**Comment by xinhuitian** [comment]
> A test needed.

@alexey-milovidov Added two test cases to check whether the index is correctly built. 

Also when adding the test, I found another bug in ApproximateNearestNeighborCondition constructor, which uses the global setting index_granularity to compute granule number, instead of using the specific setting of the corresponding table. So the granule number returned by MergeTreeIndexConditionAnnoy::getUsefulRanges method is not right if the table sets a different index_granularity different with global index_granularity setting.  

```
ApproximateNearestNeighborCondition::ApproximateNearestNeighborCondition(const SelectQueryInfo & query_info, ContextPtr context)
    : block_with_constants(KeyCondition::getBlockWithConstants(query_info.query, query_info.syntax_analyzer_result, context))
    , index_granularity(context->getMergeTreeSettings().index_granularity)
    , max_limit_for_ann_queries(context->getSettings().max_limit_for_ann_queries)
    , index_is_useful(checkQueryStructure(query_info))
{
    LOG_DEBUG(&Poco::Logger::get("ApproximateNearestNeighborCondition"), "index_granularity: {}", context->getMergeTreeSettings().index_granularity);
}
```
Create a table with index_granularity = 5
```
CREATE TABLE tab(id Int32, vector Tuple(Float32, Float32, Float32), INDEX annoy_index vector TYPE annoy() GRANULARITY 1) ENGINE = MergeTree ORDER BY id SETTINGS index_granularity = 5;

 INSERT INTO tab VALUES (1, (0.0, 0.0, 10.0)), (2, (0.0, 0.0, 10.5)), (3, (0.0, 0.0, 9.5)), (4, (0.0, 0.0, 9.7)), (5, (0.0, 0.0, 10.2)), (6, (10.0, 0.0, 0.0)), (7, (9.5, 0.0, 0.0)), (8, (9.7, 0.0, 0.0)), (9, (10.2, 0.0, 0.0)), (10, (10.5, 0.0, 0.0)), (11, (0.0, 10.0, 0.0)), (12, (0.0, 9.5, 0.0)), (13, (0.0, 9.7, 0.0)), (14, (0.0, 10.2, 0.0)), (15, (0.0, 10.5, 0.0));
```
Exec a query
```
SELECT *
FROM tab
WHERE L2Distance(vector, (0.0, 10.5, 0.0)) < 1.
LIMIT 3
```
Result:
```
# not correct, should return id 15
┌─id─┬─vector─────┐
│ 11 │ (0,10,0)   │
│ 13 │ (0,9.7,0)  │
│ 14 │ (0,10.2,0) │
└────┴────────────┘
```
get log:
```
ApproximateNearestNeighborCondition: index_granularity: 8192
```

**Comment by xinhuitian** [comment]
@alexey-milovidov the failed stateless tests are not related with this pr, and the Flaky check ASAN test failed with a dropping database timeout error, could you help to give some advice about how to fix this error?
```
02354_annoy_index | FAIL | 710.11
-- | -- | --
2023-06-27 08:25:29 Timeout dropping database test_vtheiq6r after test 
2023-06-27 08:25:29  
2023-06-27 08:25:29 stdout: 
2023-06-27 08:25:29  
2023-06-27 08:25:29  
2023-06-27 08:25:29 Settings used in the test: --max_insert_threads=6 --group_by_two_level_threshold=1 --group_by_two_level_threshold_bytes=15012015 --distributed_aggregation_memory_efficient=1 --fsync_metadata=1 --output_format_parallel_formatting=0 --input_format_parallel_parsing=1 --min_chunk_bytes_for_parallel_parsing=10628033 --max_read_buffer_size=888527 --prefer_localhost_replica=0 --max_block_size=89885 --max_threads=48 --optimize_or_like_chain=0 --optimize_read_in_order=0 --enable_multiple_prewhere_read_steps=0 --read_in_order_two_level_merge_threshold=100 --optimize_aggregation_in_order=1 --aggregation_in_order_max_block_bytes=44341962 --min_compress_block_size=1341063 --max_compress_block_size=1727505 --use_uncompressed_cache=0 --min_bytes_to_use_direct_io=10737418240 --min_bytes_to_use_mmap_io=10737418240 --local_filesystem_read_method=read --remote_filesystem_read_method=read --local_filesystem_read_prefetch=0 --remote_filesystem_read_prefetch=0 --allow_prefetched_read_pool_for_remote_filesystem=1 --filesystem_prefetch_max_memory_usage=128Mi --filesystem_prefetches_limit=0 --filesystem_prefetch_min_bytes_for_single_read_task=8Mi --filesystem_prefetch_step_marks=50 --filesystem_prefetch_step_bytes=0 --compile_expressions=0 --compile_aggregate_expressions=1 --compile_sort_description=0 --merge_tree_coarse_index_granularity=22 --optimize_distinct_in_order=1 --optimize_sorting_by_input_stream_properties=0 --http_response_buffer_size=4652867 --http_wait_end_of_query=False --enable_memory_bound_merging_of_aggregation_results=0 
2023-06-27 08:25:29  2023-06-27 08:25:29 Database: test_vtheiq6r


```

**Comment by alexey-milovidov** [comment]
These failures require investigation.

**Review by rschu1ze — APPROVED** [review]

**Comment by rschu1ze** [comment]
@xinhuitian Thanks a lot for the PR and sorry for the delay (I did not notice your fix). I rebased and made some cleanups. The fix itself is good.

About the other problem (bug in bug in `ApproximateNearestNeighborCondition` ctor): The code indeed currently only checks the global MergeTree settings (set via `config.xml`, [docs](https://clickhouse.com/docs/en/operations/settings/merge-tree-settings)) but not the per-table index_granularity (set via `SETTINGS` clause in `CREATE TABLE`). I did not find a simple way to fix this as the index knows nothing about the column it is created on. We would need to get the settings from `StorageMergeTree::getSettings`. For now, allow me to put a warning into the docs and ask my colleagues if they have an idea.

**Comment by xinhuitian** [comment]
> @xinhuitian Thanks a lot for the PR and sorry for the delay (I did not notice your fix). I rebased and made some cleanups. The fix itself is good.
> 
> About the other problem (bug in bug in `ApproximateNearestNeighborCondition` ctor): The code indeed currently only checks the global MergeTree settings (set via `config.xml`, [docs](https://clickhouse.com/docs/en/operations/settings/merge-tree-settings)) but not the per-table index_granularity (set via `SETTINGS` clause in `CREATE TABLE`). I did not find a simple way to fix this as the index knows nothing about the column it is created on. We would need to get the settings from `StorageMergeTree::getSettings`. For now, allow me to put a warning into the docs and ask my colleagues if they have an idea.

@rschu1ze could help to take a look at the hung error of 'Stateless tests flaky check (asan)' test case? No idea about the reason :joy:

**Comment by rschu1ze** [comment]
Needs merge from `master` and the same fix in new file `Storages/MergeTree/MergeTreeIndexUSearch.cpp`.

**Comment by xinhuitian** [comment]
> Needs merge from `master` and the same fix in new file `Storages/MergeTree/MergeTreeIndexUSearch.cpp`.

@rschu1ze  Updated, pls help to review again

**Pull request merged**
