### PR TITLE
Add missing setting max_estimated_execution_time in  SettingsChangesHistory

### PR DESCRIPTION
**Pull request by Avogar**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Fixes https://github.com/ClickHouse/ClickHouse/pull/58402#issuecomment-1904635126

### CODE REVIEW

**Comment by robot-ch-test-poll2** [comment]
*This is an automated comment for commit 35a3879c1f04984e04645a0eb3fed6f348719c21 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/59104/35a3879c1f04984e04645a0eb3fed6f348719c21/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/59104/35a3879c1f04984e04645a0eb3fed6f348719c21/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Review by Algunenano — APPROVED** [review]
Thanks a lot. I was about to revert the PR :smile:

**Comment by Avogar** [comment]
Builds are ok, let's merge

**Comment by jsc0218** [comment]
thanks for the fix, it was from one I reviewed.

**Pull request merged**
