### PR TITLE
Try fix crash when server startup with unavailable MySQL server

### PR DESCRIPTION
**Pull request by zhang2014**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Try fix crash when server startup with unavailable MySQL server & support drop MySQL database engine with unavailable MySQL server.

### CODE REVIEW

**Comment by zhang2014** [comment]
> Integration tests (asan) — Some exception occurred :(
> Integration tests (thread) — Some exception occurred :(

Unknown reason.

**Comment by tavplubix** [comment]
>Try fix crash when server startup with unavailable MySQL server & support drop MySQL database engine with unavailable MySQL server.

Could you please also add an integration test for this?

**Comment by zhang2014** [comment]
> Could you please also add an integration test for this?

Ok, I will add it .

**Comment by qoega** [comment]
@zhang2014 will you have time to return to this PR?

**Comment by alexey-milovidov** [comment]
Looks like this PR is abandoned.

**Pull request closed without merging**
