### PR TITLE
Revert "MergeTree FINAL optimization diagnostics and settings"

### PR DESCRIPTION
**Pull request by Algunenano**
Reverts ClickHouse/ClickHouse#59650

Breaks tests. Please reintroduce it properly and do not backport it unless it's fixing a bug (and then only backport the necessary changes)

### CODE REVIEW

**Comment by robot-ch-test-poll2** [comment]
*This is an automated comment for commit b5b7847036452f73f0e8d7ebab7af9fcb2497ccb with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/59702/b5b7847036452f73f0e8d7ebab7af9fcb2497ccb/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/59702/b5b7847036452f73f0e8d7ebab7af9fcb2497ccb/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Comment by kitaisreal** [comment]
> Reverts #59650
> 
> Breaks tests. Please reintroduce it properly and do not backport it unless it's fixing a bug (and then only backport the necessary changes)

Which tests does it break ?

We backport it because we need diagnostics to understand possible issues with FINAL and we also need settings to disable FINAL optimisations, because this can help with fixing bug.

**Comment by Algunenano** [comment]
> Which tests does it break ?

Not sure why you are asking instead of checking, but here: https://s3.amazonaws.com/clickhouse-test-reports/59650/c4846b661373dd59609583f2f5de79313d65a39d/upgrade_check__debug_.html

19 different failures in CI because of it.

> We backport it because we need diagnostics to understand possible issues with FINAL and we also need settings to disable FINAL optimisations, because this can help with fixing bug.

Maybe I've missed a bug report about FINAL, but there is no comment in the PR about it either. If we are backporting things like new settings into patch releases it should be obvious why they are necessary and they do need to appear in the changelog.

**Comment by kitaisreal** [comment]
> > Which tests does it break ?
> 
> Not sure why you are asking instead of checking, but here: https://s3.amazonaws.com/clickhouse-test-reports/59650/c4846b661373dd59609583f2f5de79313d65a39d/upgrade_check__debug_.html
> 
> 19 different failures in CI because of it.
> 
> > We backport it because we need diagnostics to understand possible issues with FINAL and we also need settings to disable FINAL optimisations, because this can help with fixing bug.
> 
> Maybe I've missed a bug report about FINAL, but there is no comment in the PR about it either. If we are backporting things like new settings into patch releases it should be obvious why they are necessary and they do need to appear in the changelog.

It did not break those tests, the automation does not properly work in cases you backport settings changes, check pull request we added them to 23.12 because I initially wanted to backport those pull request into 23.12.

I discussed this bug internally with @KochetovNicolai.

**Comment by tavplubix** [comment]
>It did not break those tests, the automation does not properly work in cases you backport settings changes, check pull request we added them to 23.12 because I initially wanted to backport those pull request into 23.12.

 - The check did not fail before your PR
 - The check has failed in your PR
 - The PR was merged without taking a look at failed checks (there are also 2 AST Fuzzer failures that is always worths attention)
 - The check fails in master and other PRs

So you have broken it (well, technically @KochetovNicolai, not you). Even if the automation does not properly work, then you or @KochetovNicolai should have fixed the automation or at least suppressed the check before merging the PR to avoid failing checks in master.

**Pull request merged**
