### PR TITLE
Fixed zh...statements/alter

### PR DESCRIPTION
**Pull request by ghost**
Changelog category (leave one):

- Documentation (changelog entry is not required)

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
...

Fix bugs when i check the zh document changes

> Information about CI checks: https://clickhouse.tech/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by kitaisreal** [comment]
@Mergifyio update

**Comment by cnmade** [comment]
@kitaisreal seems there some bug need to check

```

The self-hosted runner: i-04ffed7a3f2ac0e4a lost communication with the server. Verify the machine is running and has a healthy network connection. Anything in your workflow that terminates the runner process, starves it for CPU/Memory, or blocks its network access can cause this error.
```

and also this failed:

https://github.com/ClickHouse/ClickHouse/pull/34049

**Comment by cnmade** [comment]
This pull request is to resolved #34129

**Comment by cnmade** [comment]
@kitaisreal hello, may you please see this pull request?

**Review by kitaisreal — APPROVED** [review]

**Pull request merged**
