### PR TITLE
Strip debuginfo symbols from prql-compiler

### PR DESCRIPTION
**Pull request by aljazerzen**
Fix for https://github.com/PRQL/prql/issues/3768

### Changelog category (leave one):
- Build/Testing/Packaging Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
- Reduce the size of prql-compiler library

### CODE REVIEW

**Comment by aljazerzen** [comment]
I've also disabled `profile.release.debug`, since it is getting stripped anyway.

**Comment by robot-clickhouse-ci-1** [comment]
*This is an automated comment for commit fd15f2433fbb32bfbdfa807773e1490f40b4f391 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/56476/fd15f2433fbb32bfbdfa807773e1490f40b4f391/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td><a href="https://github.com/ClickHouse/ClickHouse/actions/runs/6802955503">✅ success</a></td></tr>
<tbody>
</table>
</details>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/56476/fd15f2433fbb32bfbdfa807773e1490f40b4f391/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Comment by nikitamikhaylov** [comment]
Hmm, looks like build failures are related to this change:
```
Nov 08 19:53:55 FAILED: src/unit_tests_dbms 
Nov 08 19:53:55 : && /usr/bin/clang++-17 --target=x86_64-linux-gnu --sysroot=/build/cmake/linux/../../contrib/sysroot/linux-x86_64/x86_64-linux-gnu/libc --gcc-toolchain=/build/cmake/linux/../../contrib/sysroot/linux-x86_64  -g -fno-omit-frame-pointer -DSANITIZER -fsanitize=memory -fsanitize-memory-use-after-dtor -fsanitize-memory-track-origins -fno-optimize-sibling-calls -fPIC -fpie -fdiagnostics-color=always -Xclang -fuse-ctor-homing -Wno-enum-constexpr-conversion -fsized-deallocation  -gdwarf-aranges -pipe -mssse3 -msse4.1 -msse4.2 -mpclmul -mpopcnt -fasynchronous-unwind-tables -ffile-prefix-map=/build=. -ftime-trace -falign-functions=32 -mbranches-within-32B-boundaries  -fdiagnostics-absolute-paths -fstrict-vtable-pointers -Wall -Wextra -Weverything -Wpedantic -Wno-zero-length-array -Wno-c++98-compat-pedantic -Wno-c++98-compat -Wno-c++20-compat -Wno-sign-conversion -Wno-implicit-int-conversion -Wno-implicit-int-float-conversion -Wno-ctad-maybe-unsupported -Wno-disabled-macro-expansion -Wno-documentation-unknown-command -Wno-double-promotion -Wno-exit-time-destructors -Wno-float-equal -Wno-global-constructors -Wno-missing-prototypes -Wno-missing-variable-declarations -Wno-padded -Wno-switch-enum -Wno-undefined-func-template -Wno-unused-template -Wno-vla -Wno-weak-template-vtables -Wno-weak-vtables -Wno-thread-safety-negative -Wno-enum-constexpr-conversion -Wno-unsafe-buffer-usage -O2 -g -DNDEBUG -O3 -g -gdwarf-4 --gcc-toolchain=/build/cmake/linux/../../contrib/sysroot/linux-x86_64 --ld-path=/usr/bin/ld.lld-17 -Wl,--no-export-dynamic -Wl,--gdb-index -Wl,--build-id=sha1 @CMakeFiles/unit_tests_dbms.rsp -o src/unit_tests_dbms  && :
Nov 08 19:53:55 ld.lld-17: error: duplicate symbol: __rg_oom
Nov 08 19:53:55 >>> defined at alloc.rs:351 (src/alloc.rs:351)
Nov 08 19:53:55 >>>            std-7f37ca7791d7978f.std.52b39858eb959e31-cgu.02.rcgu.o:(__rg_oom) in archive rust/BLAKE3/RelWithDebInfo/lib_ch_rust_blake3.a
Nov 08 19:53:55 >>> defined at std.61495d1acb96ddf9-cgu.02
Nov 08 19:53:55 >>>            std-31f8aa34c832a12e.std.61495d1acb96ddf9-cgu.02.rcgu.o:(.text.__rg_oom+0x0) in archive rust/prql/RelWithDebInfo/lib_ch_rust_prql.a
Nov 08 19:53:55 
Nov 08 19:53:55 ld.lld-17: error: duplicate symbol: __rdl_alloc
Nov 08 19:53:55 >>> defined at alloc.rs:376 (src/alloc.rs:376)
Nov 08 19:53:55 >>>            std-7f37ca7791d7978f.std.52b39858eb959e31-cgu.05.rcgu.o:(__rdl_alloc) in archive rust/BLAKE3/RelWithDebInfo/lib_ch_rust_blake3.a
Nov 08 19:53:55 >>> defined at std.61495d1acb96ddf9-cgu.05
Nov 08 19:53:55 >>>            std-31f8aa34c832a12e.std.61495d1acb96ddf9-cgu.05.rcgu.o:(.text.__rdl_alloc+0x0) in archive rust/prql/RelWithDebInfo/lib_ch_rust_prql.a
Nov 08 19:53:55 
Nov 08 19:53:55 ld.lld-17: error: duplicate symbol: __rdl_dealloc
Nov 08 19:53:55 >>> defined at alloc.rs:42 (src/sys/unix/alloc.rs:42)
Nov 08 19:53:55 >>>            std-7f37ca7791d7978f.std.52b39858eb959e31-cgu.05.rcgu.o:(__rdl_dealloc) in archive rust/BLAKE3/RelWithDebInfo/lib_ch_rust_blake3.a
Nov 08 19:53:55 >>> defined at std.61495d1acb96ddf9-cgu.05
Nov 08 19:53:55 >>>            std-31f8aa34c832a12e.std.61495d1acb96ddf9-cgu.05.rcgu.o:(.text.__rdl_dealloc+0x0) in archive rust/prql/RelWithDebInfo/lib_ch_rust_prql.a
Nov 08 19:53:55 
Nov 08 19:53:55 ld.lld-17: error: duplicate symbol: __rdl_realloc
Nov 08 19:53:55 >>> defined at alloc.rs:393 (src/alloc.rs:393)
Nov 08 19:53:55 >>>            std-7f37ca7791d7978f.std.52b39858eb959e31-cgu.05.rcgu.o:(__rdl_realloc) in archive rust/BLAKE3/RelWithDebInfo/lib_ch_rust_blake3.a
Nov 08 19:53:55 >>> defined at std.61495d1acb96ddf9-cgu.05
Nov 08 19:53:55 >>>            std-31f8aa34c832a12e.std.61495d1acb96ddf9-cgu.05.rcgu.o:(.text.__rdl_realloc+0x0) in archive rust/prql/RelWithDebInfo/lib_ch_rust_prql.a
Nov 08 19:53:55 
Nov 08 19:53:55 ld.lld-17: error: duplicate symbol: __rdl_alloc_zeroed
Nov 08 19:53:55 >>> defined at alloc.rs:408 (src/alloc.rs:408)
Nov 08 19:53:55 >>>            std-7f37ca7791d7978f.std.52b39858eb959e31-cgu.05.rcgu.o:(__rdl_alloc_zeroed) in archive rust/BLAKE3/RelWithDebInfo/lib_ch_rust_blake3.a
Nov 08 19:53:55 >>> defined at std.61495d1acb96ddf9-cgu.05
Nov 08 19:53:55 >>>            std-31f8aa34c832a12e.std.61495d1acb96ddf9-cgu.05.rcgu.o:(.text.__rdl_alloc_zeroed+0x0) in archive rust/prql/RelWithDebInfo/lib_ch_rust_prql.a
Nov 08 19:53:55 
Nov 08 19:53:55 ld.lld-17: error: duplicate symbol: rust_eh_personality
Nov 08 19:53:55 >>> defined at gcc.rs:251 (src/personality/gcc.rs:251)
Nov 08 19:53:55 >>>            std-7f37ca7791d7978f.std.52b39858eb959e31-cgu.05.rcgu.o:(rust_eh_personality) in archive rust/BLAKE3/RelWithDebInfo/lib_ch_rust_blake3.a
Nov 08 19:53:55 >>> defined at std.61495d1acb96ddf9-cgu.05
Nov 08 19:53:55 >>>            std-31f8aa34c832a12e.std.61495d1acb96ddf9-cgu.05.rcgu.o:(.text.rust_eh_personality+0x0) in archive rust/prql/RelWithDebInfo/lib_ch_rust_prql.a
Nov 08 19:53:55 
Nov 08 19:53:55 ld.lld-17: error: duplicate symbol: __rdl_oom
Nov 08 19:53:55 >>> defined at alloc.rs:409 (src/alloc.rs:409)
Nov 08 19:53:55 >>>            alloc-da4bd2943629ef21.alloc.4b7c7e39063d447c-cgu.0.rcgu.o:(__rdl_oom) in archive rust/BLAKE3/RelWithDebInfo/lib_ch_rust_blake3.a
Nov 08 19:53:55 >>> defined at alloc.ed7e5f807c824065-cgu.0
Nov 08 19:53:55 >>>            alloc-e1d420b919132c39.alloc.ed7e5f807c824065-cgu.0.rcgu.o:(.text.__rdl_oom+0x0) in archive rust/prql/RelWithDebInfo/lib_ch_rust_prql.a
Nov 08 19:53:55 
Nov 08 19:53:55 ld.lld-17: error: duplicate symbol: __rust_drop_panic
Nov 08 19:53:55 >>> defined at panicking.rs:60 (src/panicking.rs:60)
Nov 08 19:53:55 >>>            std-7f37ca7791d7978f.std.52b39858eb959e31-cgu.13.rcgu.o:(__rust_drop_panic) in archive rust/BLAKE3/RelWithDebInfo/lib_ch_rust_blake3.a
Nov 08 19:53:55 >>> defined at std.61495d1acb96ddf9-cgu.13
Nov 08 19:53:55 >>>            std-31f8aa34c832a12e.std.61495d1acb96ddf9-cgu.13.rcgu.o:(.text.__rust_drop_panic+0x0) in archive rust/prql/RelWithDebInfo/lib_ch_rust_prql.a
Nov 08 19:53:55 
Nov 08 19:53:55 ld.lld-17: error: duplicate symbol: __rust_foreign_exception
Nov 08 19:53:55 >>> defined at panicking.rs:68 (src/panicking.rs:68)
Nov 08 19:53:55 >>>            std-7f37ca7791d7978f.std.52b39858eb959e31-cgu.13.rcgu.o:(__rust_foreign_exception) in archive rust/BLAKE3/RelWithDebInfo/lib_ch_rust_blake3.a
Nov 08 19:53:55 >>> defined at std.61495d1acb96ddf9-cgu.13
Nov 08 19:53:55 >>>            std-31f8aa34c832a12e.std.61495d1acb96ddf9-cgu.13.rcgu.o:(.text.__rust_foreign_exception+0x0) in archive rust/prql/RelWithDebInfo/lib_ch_rust_prql.a
Nov 08 19:53:55 
Nov 08 19:53:55 ld.lld-17: error: duplicate symbol: rust_begin_unwind
Nov 08 19:53:55 >>> defined at panicking.rs:541 (src/panicking.rs:541)
Nov 08 19:53:55 >>>            std-7f37ca7791d7978f.std.52b39858eb959e31-cgu.13.rcgu.o:(rust_begin_unwind) in archive rust/BLAKE3/RelWithDebInfo/lib_ch_rust_blake3.a
Nov 08 19:53:55 >>> defined at std.61495d1acb96ddf9-cgu.13
Nov 08 19:53:55 >>>            std-31f8aa34c832a12e.std.61495d1acb96ddf9-cgu.13.rcgu.o:(.text.rust_begin_unwind+0x0) in archive rust/prql/RelWithDebInfo/lib_ch_rust_prql.a
Nov 08 19:53:55 
Nov 08 19:53:55 ld.lld-17: error: duplicate symbol: rust_panic
Nov 08 19:53:55 >>> defined at panicking.rs:754 (src/panicking.rs:754)
Nov 08 19:53:55 >>>            std-7f37ca7791d7978f.std.52b39858eb959e31-cgu.13.rcgu.o:(rust_panic) in archive rust/BLAKE3/RelWithDebInfo/lib_ch_rust_blake3.a
Nov 08 19:53:55 >>> defined at std.61495d1acb96ddf9-cgu.13
Nov 08 19:53:55 >>>            std-31f8aa34c832a12e.std.61495d1acb96ddf9-cgu.13.rcgu.o:(.text.rust_panic+0x0) in archive rust/prql/RelWithDebInfo/lib_ch_rust_prql.a
Nov 08 19:53:55 clang++-17: error: linker command failed with exit code 1 (use -v to see invocation)
Nov 08 19:53:56 [10342/10359] Linking CXX executable programs/clickhouse
Nov 08 19:53:56 FAILED: programs/clickhouse 
```

**Comment by aljazerzen** [comment]
To be honest, I don't know how this is compiled and packaged - I didn't even run it locally, since it was too much work.

As a blind guess, I'll now try adding back the `debug=true` and be optimistic about the implications.

If this fails, consider this PR just a hint saying "you should probably strip debug symbols" without telling you how to do it :D

**Comment by antaljanosbenjamin** [comment]
The build failure is the result of linking the rust standard library in both release and debug mode. Other Rust modules are compiled with `debug=true`, while the PRQL lib isn't. Therefore the linking fails because of duplicated symbols.

**Comment by alexey-milovidov** [comment]
#59306

**Pull request closed without merging**
