### PR TITLE
Partially backport #50408 to 23.3 to fix integration tests

### PR DESCRIPTION
**Pull request by Felixoid**
Original PR backport #50408

### CODE REVIEW

**Comment by robot-clickhouse** [comment]
*This is an automated comment for commit 6fb2fc0b8a0cbd354a6e3d02ac89047e33b8f75a with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/54720/6fb2fc0b8a0cbd354a6e3d02ac89047e33b8f75a/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Push to Dockerhub</td><td>The check for building and pushing the CI related docker images to docker hub</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

**Comment by Felixoid** [comment]
@tavplubix do you think we need to revert the related backport? It looks like the patch does not address the issues completely

**Comment by tavplubix** [comment]
Yes, it's totally fine to revert it

**Comment by Felixoid** [comment]
Ok, I'll do it in a separate PR

**Pull request closed without merging**
