### PR TITLE
What if we tighten limits for functional tests?

### PR DESCRIPTION
**Pull request by alexey-milovidov**
### Changelog category (leave one):
- CI Fix or Improvement (changelog entry is not required)

This pull request is a gift to @alesapin. After fixing https://github.com/ClickHouse/ClickHouse/pull/66908 I decided to solve the problem in a more fundamental way by limiting maximum memory usage in tests, so it won't happen again.

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Do not test
- [x]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
Probably won't work, because we also use the estimated number of rows to check for limits.

**Comment by robot-ch-test-poll2** [comment]
*This is an automated comment for commit 3b45916470affeb555ae20a4d557ea9de5075f50 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/66837/3b45916470affeb555ae20a4d557ea9de5075f50/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/66806/e74892bfaf4aa98654a6253a34bbeb3f1740de41/docs_check.html">✅ success</a></td></tr>
<tr><td>Fast test</td><td>Normally this is the first check that is ran for a PR. It builds ClickHouse and runs most of <a href="https://clickhouse.com/docs/en/development/tests#functional-tests">stateless functional tests</a>, omitting some. If it fails, further checks are not started until it is fixed. Look at the report to see which tests fail, then reproduce the failure locally as described <a href="https://clickhouse.com/docs/en/development/tests#functional-test-locally">here</a></td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/5611ef0d387e7c18a76dbcb1d1619d19ac60b501/fast_test.html">✅ success</a></td></tr>
<tr><td>Unit tests</td><td>Runs the unit tests for different release types</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/5611ef0d387e7c18a76dbcb1d1619d19ac60b501/unit_tests__release_.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Comment by alexey-milovidov** [comment]
It is promising, after some tweaks we can add these limits.

**Comment by alexey-milovidov** [comment]
Needs https://github.com/ClickHouse/ClickHouse/issues/66992

**Comment by alexey-milovidov** [comment]
Needs #67301.

**Review by CheSema — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
Needs https://github.com/ClickHouse/ClickHouse/pull/67590

**Comment by alexey-milovidov** [comment]
Needs #67699.

**Comment by alexey-milovidov** [comment]
https://github.com/ClickHouse/ClickHouse/issues/68425

**Comment by alexey-milovidov** [comment]
Needs #68508

**Pull request merged**
