### PR TITLE
Remove test `02151_hash_table_sizes_stats`

### LINKED ISSUE #54674: 02151_hash_table_sizes_stats is flaky
**Describe the bug**
The TC fails with timeout sometimes. [report link](https://s3.amazonaws.com/clickhouse-test-reports/54533/4cc013b9180d9efd7c58cc75c1e3929f2a2e90b0/stateless_tests__debug__[4_5].html)

[query to check TC status](https://play.clickhouse.com/play?user=play#c2VsZWN0IHRlc3RfbmFtZSwgdGVzdF9zdGF0dXMsIHRlc3RfZHVyYXRpb25fbXMgYXMgcywgY2hlY2tfbmFtZSBmcm9tIGNoZWNrcwp3aGVyZQogcyA+IDYwMDAwMCBhbmQKIHRlc3RfbmFtZSA9ICcwMjE1MV9oYXNoX3RhYmxlX3NpemVzX3N0YXRzJwphbmQgdGVzdF9zdGF0dXMgbGlrZSAnRiUnCiAgICAKCiA=)

### PR DESCRIPTION
**Pull request by alexey-milovidov**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

This closes https://github.com/ClickHouse/ClickHouse/issues/54674

### CODE REVIEW

**Comment by robot-ch-test-poll2** [comment]
*This is an automated comment for commit 81cfa0344a98378db417fb60f54d981cec745704 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/54961/81cfa0344a98378db417fb60f54d981cec745704/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>✅ success</td></tr>
<tbody>
</table>
</details>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>⏳ pending</td></tr>
<tbody>
</table>

**Comment by amosbird** [comment]
`02151_hash_table_sizes_stats_distributed.sh` still uses `02151_hash_table_sizes_stats.testcases` and this PR breaks shellcheck.

**Comment by azat** [comment]
And not only shellcheck actually, but the CI in general, since this test fails - https://github.com/ClickHouse/ClickHouse/pull/54969

**Comment by tavplubix** [comment]
Looks like the test was just too slow for debug builds. @nickitat, should we add the test back with `no-debug` tag?

**Comment by nickitat** [comment]
> Looks like the test was just too slow for debug builds. @nickitat, should we add the test back with `no-debug` tag?

I think the biggest "architectural" problem was that it called `flush logs` around 15 times I guess (twice for each subtest). I'll try to rework it and bring the test back

**Pull request merged**
