### PR TITLE
Lower PREWHERE log level

### PR DESCRIPTION
**Pull request by vdimir**
### Changelog category (leave one):

- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
- Log `PREWHERE` conditions with `Test` level

Motivation: When searching in `text_log,` you often filter `message` by a specific substring. However, if you run the same or a slightly modified query again, you'll get a large number of spam messages from the previous SELECT run on `text_log`, because the substring appears in where conditions as well, making it harder to work with logs.

### CODE REVIEW

**Comment by robot-ch-test-poll3** [comment]
*This is an automated comment for commit 286b0709d06af02b491906efc602924298695ed3 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/73116/286b0709d06af02b491906efc602924298695ed3/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

**Review by nickitat — APPROVED** [review]

**Comment by vdimir** [comment]
> Mergeable Check — failed: Integration tests (asan, old analyzer) [5/6]
> Integration tests (asan, old analyzer) [5/6] — fail: 1, passed: 554 [Details](https://s3.amazonaws.com/clickhouse-test-reports/73116/bdefff4e3e3ba6ea76c085466eb1f16c5044cc23/integration_tests__asan__old_analyzer__[5_6].html)

`#73096`

**Comment by SaltTan** [comment]
Looking in the log was the only way to find out which conditions are being moved to prewhere :(

**Comment by vdimir** [comment]
@SaltTan you may use `EXPLAIN PLAN actions = 1` to check out what have been pushed down

**Pull request merged**
