### PR TITLE
group_by_use_nulls strikes back

### LINKED ISSUE #62661: Analyzer: Column is not under aggregate function and not in GROUP BY keys.
```sql
set group_by_use_nulls = true;

EXPLAIN QUERY TREE
SELECT a, b
FROM numbers(3)
GROUP BY number as a, (number + number) as b WITH CUBE
ORDER BY a, b;
```

This query produces the following error:
```
Received exception from server (version 24.3.2):
Code: 215. DB::Exception: Received from localhost:9000. DB::Exception: Column number is not under aggregate function and not in GROUP BY keys. In query SELECT a, b FROM numbers(3) GROUP BY number AS a, number + number AS b WITH CUBE ORDER BY a ASC, b ASC. (NOT_AN_AGGREGATE)
(query: EXPLAIN QUERY TREE
SELECT a, b
FROM numbers(3)
GROUP BY number as a, (number + number) as b WITH CUBE
ORDER BY a, b;)
```

### PR DESCRIPTION
**Pull request by KochetovNicolai**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Closes https://github.com/ClickHouse/ClickHouse/issues/62661

### CODE REVIEW

**Comment by robot-clickhouse** [comment]
*This is an automated comment for commit 1f207de7a10dfc9c9b0ca76f8d62d55da6e04c61 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/62922/1f207de7a10dfc9c9b0ca76f8d62d55da6e04c61/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

**Comment by KochetovNicolai** [comment]
```
SELECT
    a,
    b,
    cramersVBiasCorrected(a, b)
FROM numbers(3)
GROUP BY
    number AS a,
    number + number AS b
    WITH CUBE
SETTINGS group_by_use_nulls = 1;
```

**Review by devcrafter — APPROVED** [review]

**Review by novikd — APPROVED** [review]
LGTM

BTW, I'd call it `Aliases strike back` :)

**Comment by KochetovNicolai** [comment]
AST fuzzer (asan) - unclear; no messages in log; the last query works fine locally
AST fuzzer (ubsan) - `SELECT arrayMap(x -> '.', range(number % 10)) AS k FROM remote('127.0.0.{2,3}', numbers(1e6)) GROUP BY GROUPING SETS ((k)) settings group_by_use_nulls=1`
Stress test (tsan)  - race in async inserts

**Comment by novikd** [comment]
#62661 seems to be working in the master. What does this PR fix?

**Comment by KochetovNicolai** [comment]
This PR just adds a test, and tries to fix all fuzzings on top.

**Comment by KochetovNicolai** [comment]
03145_non_loaded_projection_backup was flaky when merged:  https://s3.amazonaws.com/clickhouse-test-reports/63426/ba4f5f9b3fe74d44295633995033c9d484b8a9c6/stateless_tests_flaky_check__asan_.html
02479_mysql_connect_to_self is [flaky](https://play.clickhouse.com/play?user=play#U0VMRUNUIHB1bGxfcmVxdWVzdF9udW1iZXIsIGNoZWNrX3N0YXJ0X3RpbWUsIGNoZWNrX25hbWUsIHRlc3RfbmFtZSwgdGVzdF9zdGF0dXMsIGNoZWNrX3N0YXR1cywgcmVwb3J0X3VybApGUk9NIGNoZWNrcwpXSEVSRSAxCiAgICAtLUFORCBwdWxsX3JlcXVlc3RfbnVtYmVyID0gMAogICAgQU5EIHRlc3Rfc3RhdHVzICE9ICdTS0lQUEVEJwogICAgQU5EIHRlc3Rfc3RhdHVzICE9ICdPSycKICAgIEFORCBjaGVja19zdGF0dXMgIT0gJ3N1Y2Nlc3MnCiAgICBBTkQgdGVzdF9uYW1lIGxpa2UgJyUwMjQ3OV9teXNxbF9jb25uZWN0X3RvX3NlbGYlJwogICAgQU5EIGNoZWNrX3N0YXJ0X3RpbWUgPiBub3coKSAtIGludGVydmFsIDIgbW9udGgKT1JERVIgQlkgY2hlY2tfc3RhcnRfdGltZSBkZXNjLCBjaGVja19uYW1lLCB0ZXN0X25hbWU=) as well

**Pull request merged**
