### PR TITLE
Upgrade snappy to 1.1.10

### PR DESCRIPTION
**Pull request by taiyang-li**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Upgrade snappy to 1.1.10, clickhouse may benefit from it.

### CODE REVIEW

**Comment by robot-ch-test-poll3** [comment]
This is an automated comment for commit af81d9afc0808889416493ef684eb20b615287d4 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/53672/af81d9afc0808889416493ef684eb20b615287d4/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Comment by Tiaonmmn** [comment]
It results in compile failed when you use the following command :
```bash
cmake -D CMAKE_BUILD_TYPE=Release -D ENABLE_AVX512=ON ../ClickHouse/
```

```
[0/2] Re-checking globbed directories...
[1518/11433] Building CXX object contrib/snappy-cmake/CMakeFiles/_snappy.dir/__/snappy/snappy.cc.o
FAILED: contrib/snappy-cmake/CMakeFiles/_snappy.dir/__/snappy/snappy.cc.o
/usr/bin/ccache /usr/bin/clang++ --target=x86_64-linux-gnu --sysroot=/home/xxx/ClickHouse/cmake/linux/../../contrib/sysroot/linux-x86_64/x86_64-linux-gnu/libc -DHAVE_CONFIG_H -DSTD_EXCEPTION_HAS_STACK_TRACE=1 -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS -I/home/xxx/ClickHouse/base/glibc-compatibility/memcpy -isystem /home/xxx/ClickHouse/contrib/snappy -isystem /home/xxx/ck-build/contrib/snappy-cmake -isystem /home/xxx/ClickHouse/contrib/llvm-project/libcxx/include -isystem /home/xxx/ClickHouse/contrib/llvm-project/libcxxabi/include -isystem /home/xxx/ClickHouse/contrib/libunwind/include --gcc-toolchain=/home/xxx/ClickHouse/cmake/linux/../../contrib/sysroot/linux-x86_64 -std=c++20 -fdiagnostics-color=always -Wno-enum-constexpr-conversion -fsized-deallocation  -pipe -mssse3 -msse4.1 -msse4.2 -mpclmul -mpopcnt -mavx512f -mavx512bw -mavx512vl -fasynchronous-unwind-tables -ffile-prefix-map=/home/xxx/ClickHouse=. -falign-functions=32 -mbranches-within-32B-boundaries -fdiagnostics-absolute-paths -fstrict-vtable-pointers -w -O3 -DNDEBUG -std=c++2b   -D OS_LINUX -Werror -nostdinc++ -MD -MT contrib/snappy-cmake/CMakeFiles/_snappy.dir/__/snappy/snappy.cc.o -MF contrib/snappy-cmake/CMakeFiles/_snappy.dir/__/snappy/snappy.cc.o.d -o contrib/snappy-cmake/CMakeFiles/_snappy.dir/__/snappy/snappy.cc.o -c /home/xxx/ClickHouse/contrib/snappy/snappy.cc
/home/xxx/ClickHouse/contrib/snappy/snappy.cc:1061:3: error: unknown type name '__m256i'
  __m256i data = _mm256_lddqu_si256(static_cast<const __m256i *>(src));
  ^
/home/xxx/ClickHouse/contrib/snappy/snappy.cc:1061:55: error: unknown type name '__m256i'
  __m256i data = _mm256_lddqu_si256(static_cast<const __m256i *>(src));
                                                      ^
/home/xxx/ClickHouse/contrib/snappy/snappy.cc:1061:18: error: use of undeclared identifier '_mm256_lddqu_si256'; did you mean '_mm_lddqu_si128'?
  __m256i data = _mm256_lddqu_si256(static_cast<const __m256i *>(src));
                 ^~~~~~~~~~~~~~~~~~
                 _mm_lddqu_si128
/usr/lib64/clang/16/include/pmmintrin.h:38:1: note: '_mm_lddqu_si128' declared here
_mm_lddqu_si128(__m128i_u const *__p)
^
/home/xxx/ClickHouse/contrib/snappy/snappy.cc:1061:66: error: cannot initialize a parameter of type 'const __m128i_u *' with an lvalue of type 'const void *'
  __m256i data = _mm256_lddqu_si256(static_cast<const __m256i *>(src));
                                                                 ^~~
/usr/lib64/clang/16/include/pmmintrin.h:38:34: note: passing argument to parameter '__p' here
_mm_lddqu_si128(__m128i_u const *__p)
                                 ^
/home/xxx/ClickHouse/contrib/snappy/snappy.cc:1062:40: error: unknown type name '__m256i'
  _mm256_storeu_si256(reinterpret_cast<__m256i *>(dst), data);
                                       ^
/home/xxx/ClickHouse/contrib/snappy/snappy.cc:1065:49: error: unknown type name '__m256i'
    data = _mm256_lddqu_si256(static_cast<const __m256i *>(src) + 1);
                                                ^
/home/xxx/ClickHouse/contrib/snappy/snappy.cc:1065:65: error: arithmetic on a pointer to void
    data = _mm256_lddqu_si256(static_cast<const __m256i *>(src) + 1);
                                                           ~~~  ^
/home/xxx/ClickHouse/contrib/snappy/snappy.cc:1066:42: error: unknown type name '__m256i'
    _mm256_storeu_si256(reinterpret_cast<__m256i *>(dst) + 1, data);
                                         ^
8 errors generated.

```

**Comment by alexey-milovidov** [comment]
@Tiaonmmn, ok, but this is not the compile command that we use. You can fix it and send a follow-up PR.

**Comment by monchickey** [comment]
@Tiaonmmn The reason is that snappy does not enable SNAPPY_HAVE_X86_CRC32. Please edit contrib/snappy-cmake/CMakeLists.txt to add:
```cmake
if (ARCH_AMD64 AND (ENABLE_AVX OR ENABLE_AVX2 OR ENABLE_AVX512))
    set (SNAPPY_HAVE_X86_CRC32 1)
else ()
    set (SNAPPY_HAVE_X86_CRC32 0)
endif ()
```
Then start compilation again.

**Pull request merged**
