### PR TITLE
perf: switch *_log tables to Memory engine (attempt to reduce cache misses)

### PR DESCRIPTION
**Pull request by azat**
trace_log/query_log from performance tests shows (for
cases when prewarm query fails with timeout, 15sec) excessive
writeTraceInfo() in trace_log and QueryProfilerRuns in query_log, but
this is not the root cause of the timeout, but consequence.

Also query_log shows that on failures the following profile events has
significantly higher values:
- PerfLocalMemoryMisses (6.3x more)
- PerfLocalMemoryReferences (7x more)
- PerfDataTLBMisses (6.9x more)
- PerfInstructionTLBMisses (6.4x more)

During looking at performance tests logs I noticed that once the prewarm
query fails other server (left/right) was merging (MergeTree) something
in *_log tables.

But, using MergeTree for *_log in performance tests is useless, since
anyway environment for performance tests uses ramdrive.

And so MergeTree merges just increase overhead.

Eventually I expect that this should decrease extra memory referencing
and so this should decrease cache/TLB misses.

CI: https://clickhouse-test-reports.s3.yandex.net/30886/c504e0c08df7a926bb479a1d297f326f5c48a32f/performance_comparison/report.html#fail1

Changelog category (leave one):
- Not for changelog (changelog entry is not required)

*P.S. Marked as draft for now since I want to look at profile events for queries.*

Cc: @alexey-milovidov

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
Another option is `StripeLog` engine.

**Comment by azat** [comment]
@mergify update (an attempt to run perf tests on Intel Xeon Gold CPU)

**Comment by azat** [comment]
@mergify update (an attempt to run perf tests on Intel Xeon Gold CPU)

**Comment by azat** [comment]
@mergify update (an attempt to run perf tests on Intel Xeon Gold CPU)

**Comment by azat** [comment]
@mergify update (an attempt to run perf tests on Intel Xeon Gold CPU)

**Comment by azat** [comment]
Here are distribution of average `query_duration_ms` for queries (right - PR/left - master at that time):

PR|CPU|query_id|avg right|avg left
-|-|-|-|-
[this](https://clickhouse-test-reports.s3.yandex.net/31063/9e622b5add2bd501e1c08cb7a805a797ebce64ed/performance_comparison/report.html)|Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz|`%.prewarm0`|636|630
[31032](https://clickhouse-test-reports.s3.yandex.net/31032/fde8a3744b3ed09300be615515e1d48e811c954c/performance_comparison/report.html)|Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz|`%.prewarm0`|637|637
[31259](https://clickhouse-test-reports.s3.yandex.net/31259/10fa34c73ac068164d63f8ec63bbd49f738931df/performance_comparison/report.html)|Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz|`%.run0`|513|516
[30882](https://clickhouse-test-reports.s3.yandex.net/30882/54c89e0f0e9b7b18ab40e755805c115a462a6669/performance_comparison/report.html#fail1)|Intel(R) Xeon(R) Gold 6230 CPU @ 2.10GHz|`%.prewarm0`|1326|1249
[30886](https://clickhouse-test-reports.s3.yandex.net/30886/c504e0c08df7a926bb479a1d297f326f5c48a32f/performance_comparison/report.html#fail1)|Intel(R) Xeon(R) Gold 6230 CPU @ 2.10GHz|`%.prewarm0`|1453|1512
[30882](https://clickhouse-test-reports.s3.yandex.net/30882/54c89e0f0e9b7b18ab40e755805c115a462a6669/performance_comparison/report.html#fail1)|Intel(R) Xeon(R) Gold 6230 CPU @ 2.10GHz|`%.run0`|393|393

So the problem for prewarm queries (with profiler) is only with Gold CPU, but w/o profiler Gold CPU is faster.

And even though the patch does not changes anything, it still worth applying I guess, but the description should be changed.

**Review by alexey-milovidov — APPROVED** [review]

**Pull request merged**
