### PR TITLE
Fix memory accounting via HTTP interface

### LINKED ISSUE #11153: Memory limit (total) exceeded issues with wait_end_of_query=1
Using the version a2ed8267add1cfc28fa2ca17f7227a816921e7d7 in case I run a QUERY like "SELECT 1" in loop using `wait_end_of_query=1` after 7000 iterations all queries will fail with: 
```
DynamicQueryHandler: Code: 241, e.displayText() = DB::Exception: Memory limit (total) exceeded: would use 14.40 GiB (attempt to allocate chunk of 4198133 bytes), maximum: 14.40 GiB, Stack trace (when copying this message, always include the lines below):
``` 

If `wait_end_of_query`  is not specified the problem doesn't occur.

### PR DESCRIPTION
**Pull request by azat**
Changelog category (leave one):
- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix memory accounting via HTTP interface (can be significant with `wait_end_of_query=1`)

Fixes: #11153
Similar to: #11022

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
> Docs check — Found 1 errors

Broken in master @blinkov

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
Something wrong with `01091_num_threads` test.

**Comment by alexey-milovidov** [comment]
#9483

**Comment by alexey-milovidov** [comment]
But the way, this test is also flaky but it fails only occasionally.

**Comment by azat** [comment]
>But the way, this test is also flaky but it fails only occasionally.

I don't see the failure, but it may require some tuning

**Comment by azat** [comment]
> >But the way, this test is also flaky but it fails only occasionally.
>
>I don't see the failure, but it may require some tuning

@alexey-milovidov Ok, found, and fixed and now only 01091_num_threads fails.

**Comment by alexey-milovidov** [comment]
We have to ask @KochetovNicolai for help or maybe you can investigate?

**Comment by azat** [comment]
>We have to ask @KochetovNicolai for help or maybe you can investigate?

Interesting, fixed - 267a6c8639f3614bff3ff42385c2a1f7d7c35d41

P.S. Hm, I didn't look that it does not fails on upstream, egh.

**Comment by azat** [comment]
Now tests passed

**Pull request merged**
