### PR TITLE
Support Maps and Records, allow to insert null as default in Avro format

### LINKED ISSUE #18925: Add support of complex structures to Avro/AvroConfluent formats
**Use case**
There is currently no way to access the array of records in Avro. For example data:
`{"a": 1, "b": [{"c": 100, "d": "Q"}, {"c": 200, "d": "W"}]}` 
I can select field "a", but not field "b":
```
# clickhouse-local --query "CREATE TABLE T (a Nullable(Int64)) ENGINE = File(Avro, '/etc/a.avro'); select * from T;"
1
```
```
# clickhouse-local --query "CREATE TABLE T (a Nullable(Int64), b Array(String)) ENGINE = File(Avro, '/etc/a.avro'); select * from T;"
Code: 44, e.displayText() = DB::Exception: Type Array(String) is not compatible with Avro union:
[
    "null",
    {
        "type": "array",
        "items": {
            "type": "record",
            "namespace": "org.apache.nifi",
            "name": "bType",
            "fields": [
                {
                    "name": "c",
                    "type": [
                        "null",
                        "long"
                    ]
                },
                {
                    "name": "d",
                    "type": [
                        "null",
                        "string"
                    ]
                }
            ]
        }
    }
]: column b: While executing File (version 20.12.3.3 (official build))
```
example of Avro file - [a.zip](https://github.com/ClickHouse/ClickHouse/files/5795323/a.zip)

**Describe the solution you'd like**
It is possible to solve by converting non-root record to json or by implementation complex subcolumns (https://github.com/ClickHouse/ClickHouse/pull/17310) for Avro/AvroConfluent

### LINKED ISSUE #32899: About the Avro Map data structure is not unsupported in ClickHouse
In the project, I use kafka to insert data into clickhouse, which is undoubtedly very convenient and efficient, but because the data may involve field changes, it makes it very inconvenient for clickhouse to upgrade the data type compatible, so we decided Use AvroConfluent's data format, and use schema-registry for schema constraints.

When using AvroConfluent, I encountered a problem that the Map data structure is not compatible with the processing. After some inspection, I found that ClickHouse does not support processing the Map data structure in Avro.

So is it possible to support the processing of the Map data structure in Avro in ClickHouse? If it can’t be realized, can I ask the reason why it can’t be realized?

Looking forward to your answer, thank you very much!

## My environment

- Docker Version: 20.10.11
- ClickHouse Verseion: 21.11.7.9 (Standalone Mode)
- Kafka Version: 2.6.0 (Cluster Mode 3 brokers)
- Confluent Schema-Registry Version: 6.2.0

> My avro schema

``` json
{
  "name": "AccountRecord",
  "type": "record",
  "fields": [
    {
      "name": "account",
      "type": "string"
    },
    {
      "name": "age",
      "type": "int"
    },
    {
      "name": "createTime",
      "type": "long"
    },
    {
      "name": "currency",
      "type": {
        "type": "map",
        "values": "int"
      }
    }
  ]
}
```

> My json data
``` json
{
  "createTime":1639626783,
  "currency":{
    "RUB":9999,
    "CNY":9000,
    "EUR":800,
    "USD":500
  },
  "account": "1151f0b7-e562-480d-a193-a0a14572e32e",
  "age": 26
}
```

> My kafka engine table
``` sql
CREATE TABLE kafka_incompatible_map_account
(
    account     String,
    age         UInt8,
    createTime  UInt64,
    currency    Map(String, UInt32)
) ENGINE = Kafka
    SETTINGS  kafka_broker_list = '192.168.1.29:9092, 192.168.1.30:9092, 192.168.1.31:9092',
          kafka_topic_list = 'avro.incompatible.map.account',
          kafka_group_name = 'avro.incompatible.map.account.group.v1',
          kafka_format = 'AvroConfluent',
          kafka_num_consumers = 1;
```

> My MergeTree engine table
``` sql
CREATE TABLE t_incompatible_map_account
(
    account     String,
    age         UInt8,
    createTime  UInt64,
    currency    Map(String, UInt32)
) ENGINE = MergeTree()
    PARTITION BY toYYYYMMDD(toDateTime(createTime))
    ORDER BY createTime;
```

> My materialized view
``` sql
CREATE MATERIALIZED VIEW mv_incompatible_map_account TO t_incompatible_map_account
AS
SELECT account,
       age,
       createTime,
       currency
FROM  kafka_incompatible_map_account;
```

> My clickhouse-server.err.log
``` text
2021.12.16 12:48:47.906824 [ 125 ] {} <Error> void DB::StorageKafka::threadFunc(size_t): Code: 44. DB::Exception: Type Map(String, UInt32) is not compatible with Avro map:
{
    "type": "map",
    "values": "int"
}: column currency: while parsing Kafka message (topic: experiment.account.record, partition: 0, offset: 0)': While executing Kafka. (ILLEGAL_COLUMN), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x9b6c254 in /usr/bin/clickhouse
1. DB::AvroDeserializer::createDeserializeFn(std::__1::shared_ptr<avro::Node>, std::__1::shared_ptr<DB::IDataType const>) @ 0x131a554a in /usr/bin/clickhouse
2. DB::AvroDeserializer::createAction(DB::Block const&, std::__1::shared_ptr<avro::Node> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x131a77fb in /usr/bin/clickhouse
3. DB::AvroDeserializer::createAction(DB::Block const&, std::__1::shared_ptr<avro::Node> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x131a7cf2 in /usr/bin/clickhouse
4. DB::AvroDeserializer::AvroDeserializer(DB::Block const&, avro::ValidSchema, bool) @ 0x131a99a9 in /usr/bin/clickhouse
5. DB::AvroConfluentRowInputFormat::getOrCreateDeserializer(unsigned int) @ 0x131abe66 in /usr/bin/clickhouse
6. DB::AvroConfluentRowInputFormat::readRow(std::__1::vector<COW<DB::IColumn>::mutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::mutable_ptr<DB::IColumn> > >&, DB::RowReadExtension&) @ 0x131ab91b in /usr/bin/clickhouse
7. DB::IRowInputFormat::generate() @ 0x131c2648 in /usr/bin/clickhouse
8. DB::ISource::tryGenerate() @ 0x1315c675 in /usr/bin/clickhouse
9. DB::ISource::work() @ 0x1315c23a in /usr/bin/clickhouse
10. DB::StreamingFormatExecutor::execute() @ 0x13185aa2 in /usr/bin/clickhouse
11. DB::KafkaSource::generateImpl() @ 0x12bff68f in /usr/bin/clickhouse
12. DB::KafkaSource::generate() @ 0x12c01baf in /usr/bin/clickhouse
13. DB::ISource::tryGenerate() @ 0x1315c675 in /usr/bin/clickhouse
14. DB::ISource::work() @ 0x1315c23a in /usr/bin/clickhouse
15. DB::SourceWithProgress::work() @ 0x13373402 in /usr/bin/clickhouse
16. ? @ 0x13177e1b in /usr/bin/clickhouse
17. DB::PipelineExecutor::executeStepImpl(unsigned long, unsigned long, std::__1::atomic<bool>*) @ 0x13173dd1 in /usr/bin/clickhouse
18. DB::PipelineExecutor::executeImpl(unsigned long) @ 0x1317196f in /usr/bin/clickhouse
19. DB::PipelineExecutor::execute(unsigned long) @ 0x13171739 in /usr/bin/clickhouse
20. DB::CompletedPipelineExecutor::execute() @ 0x1316d70f in /usr/bin/clickhouse
21. DB::StorageKafka::streamToViews() @ 0x12bf59da in /usr/bin/clickhouse
22. DB::StorageKafka::threadFunc(unsigned long) @ 0x12bf3868 in /usr/bin/clickhouse
23. DB::BackgroundSchedulePoolTaskInfo::execute() @ 0x11f07cce in /usr/bin/clickhouse
24. DB::BackgroundSchedulePool::threadFunction() @ 0x11f0a6a7 in /usr/bin/clickhouse
25. ? @ 0x11f0b613 in /usr/bin/clickhouse
26. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x9bae317 in /usr/bin/clickhouse
27. ? @ 0x9bb1d1d in /usr/bin/clickhouse
28. start_thread @ 0x9609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
29. clone @ 0x122293 in /usr/lib/x86_64-linux-gnu/libc-2.31.so
 (version 21.11.7.9 (official build))
```

### LINKED ISSUE #37378: Nested AVRO structures support
Now [ClickHouse documentation](https://clickhouse.com/docs/en/interfaces/formats#data-format-avro) strictly says to us:
`Unsupported Avro data types: record (non-root), map`
but (woo-hoo!) nested structures already supported in CH.

Maybe today is good day to plan to support non-root Avro records in ClickHouse?

Our use-case for Avro records is exchange data through Kafka in AvroConfluent format, and, of course, sometimes we want to send complex structures with nested records, something like this Avro-schema:
```
{
	"type" : "record",
	"namespace" : "box.settings.update",
	"name" : "Settings",
	"fields" : [
		{"name" : "modified_ts", "type" : "long", "logicalType": "timestamp-millis"},
		{"name" : "client_id", "type" : "string"},
		{"name" : "box_id", "type" : "string"},
		{
			"name" : "config",
			"type" : {
				"type" : "record",
				"name" : "Configuration",
				"fields" : [
					{
						"name" : "visitors",
						"type" : {
							"type" : "array",
							"items" : {
								"name" : "VisitorsConfig",
								"type" : "record",
								"fields" : [
									{"name" : "measure_type", "type" : "string"},
									{"name" : "day_type", "type" : "string"},
									{"name" : "signal", "type" : "int"},
									{"name" : "duration_from", "type" : "int"},
									{"name" : "duration_to", "type" : "int"}
								]
							}
						}
					},
....
```

### PR DESCRIPTION
**Pull request by Avogar**
### Changelog category (leave one):
- New Feature

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Add support for Maps and Records in Avro format. Add new setting `input_format_avro_null_as_default ` that allow to insert null as default in Avro format.
Closes https://github.com/ClickHouse/ClickHouse/issues/18925
Closes https://github.com/ClickHouse/ClickHouse/issues/37378
Closes https://github.com/ClickHouse/ClickHouse/issues/32899

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]

**Comment by ivantopo** [comment]
Hey @Avogar, thank you so much for working on this!

I've been trying to use these nested records with a field that has an array of custom records as shown below:

```
{
  "namespace": "kamon.apm.storage.v1",
  "type": "record",
  "name": "SpansRow",
  "fields": [
    .......
    {"name": "links",           "type": { "type": "array", "items": {
      "type": "record",
      "name": "Link",
      "fields": [
        {"name": "trace_id",    "type": "string"},
        {"name": "span_id",     "type": "string"},
        {"name": "tag_keys",    "type": { "type": "array", "items": "string" }},
        {"name": "tag_values",  "type": { "type": "array", "items": "string" }}
      ]}}},
    ....
  ]
}
```

With the `links` fields defined like this in the Kafka Engine table:

```
  links             Nested(
    trace_id          String,
    span_id           String,
    tag_keys          Array(String),
    tag_values        Array(String)
  ),
```

And I keep getting this error:

```
2022.08.06 16:21:20.399915 [ 348 ] {2e038e53-bcc2-4869-ab2f-2ab298ba31ab} <Error> executeQuery: Code: 8. DB::Exception: Field links.trace_id not found in Avro schema: while parsing Kafka message (topic: ingestion_spans_1, partition: 11, offset: 696114)': While executing Kafka. (THERE_IS_NO_COLUMN) (version 22.7.1.2484 (official build)) (from 127.0.0.1:55570) (in query: select * from colossus.spans_topic limit 1 SETTINGS stream_like_engine_allow_direct_select=1;), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xba37dda in /usr/bin/clickhouse
1. DB::AvroDeserializer::AvroDeserializer(DB::Block const&, avro::ValidSchema, bool, bool) @ 0x17bdfa2c in /usr/bin/clickhouse
2. DB::AvroRowInputFormat::readPrefix() @ 0x17be0a1b in /usr/bin/clickhouse
3. DB::IRowInputFormat::generate() @ 0x17bfdaaf in /usr/bin/clickhouse
4. DB::ISource::tryGenerate() @ 0x17b8fb95 in /usr/bin/clickhouse
5. DB::ISource::work() @ 0x17b8f6e6 in /usr/bin/clickhouse
6. DB::StreamingFormatExecutor::execute() @ 0x17bb5c04 in /usr/bin/clickhouse
7. DB::KafkaSource::generateImpl() @ 0x16213f62 in /usr/bin/clickhouse
8. DB::KafkaSource::generate() @ 0x16216aef in /usr/bin/clickhouse
9. DB::ISource::tryGenerate() @ 0x17b8fb95 in /usr/bin/clickhouse
10. DB::ISource::work() @ 0x17b8f6e6 in /usr/bin/clickhouse
11. DB::ExecutionThreadContext::executeTask() @ 0x17babf0a in /usr/bin/clickhouse
12. DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*) @ 0x17ba0df0 in /usr/bin/clickhouse
13. DB::PipelineExecutor::executeImpl(unsigned long) @ 0x17b9fe64 in /usr/bin/clickhouse
14. DB::PipelineExecutor::execute(unsigned long) @ 0x17b9fbfd in /usr/bin/clickhouse
15. ? @ 0x17bafdd3 in /usr/bin/clickhouse
16. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xbb046a8 in /usr/bin/clickhouse
17. ? @ 0xbb07a3d in /usr/bin/clickhouse
18. ? @ 0x7f3427eff609 in ?
19. clone @ 0x7f3427e24133 in ?
```
I also tried using `Array(Tuple(...))` in the Kafka Engine table but didn't manage to make it work. Are arrays of records meant to work after this PR was merged? 

This is happening on ClickHouse 22.7.1.2484 and not sure whether I'm doing something wrong or this is not supported. I'll be happy to move this into a separate issue if it turns out to be a bug. Thanks!

**Comment by Avogar** [comment]
> This is happening on ClickHouse 22.7.1.2484 and not sure whether I'm doing something wrong or this is not supported. I'll be happy to move this into a separate issue if it turns out to be a bug. Thanks!

Hi! Thank you for youe comment, I will take a look

**Comment by Avogar** [comment]
Array of records is supported:
```
$ avro cat --print-schema data.avro
{
    "type": "record",
    "name": "row",
    "fields": [
        {
            "name": "arr",
            "type": {
                "type": "array",
                "items": {
                    "type": "record",
                    "name": "arr",
                    "fields": [
                        {
                            "name": "x",
                            "type": "int"
                        },
                        {
                            "name": "y",
                            "type": "string"
                        }
                    ]
                }
            }
        }
    ]
}
```
```
$ clickhouse-client -q "select * from file(data.avro)"
[(1,'123')]
$ clickhouse-client -q "desc file(data.avro)"
arr	Array(Tuple(x Int32, y String))
```
But there is a problem with Nested type, because by default we have setting `flatten_nested=true` and Nested type is transformed to separate columns with type `Array(...)`:
```
$ clickhouse-client -q "create table t (arr Nested(x UInt32, y String)) engine=Memory"
$ clickhouse-client -q "desc table t"
arr.x	Array(UInt32)
arr.y	Array(String)
```
So when we try to insert data from avro file we cannot find column with name `arr.x`:
```
$ cat data.avro | clickhouse-client -q "insert into t format Avro"
Code: 8. DB::Exception: Field arr.x not found in Avro schema: While executing AvroRowInputFormat: data for INSERT was parsed from stdin: (in query: insert into t format Avro). (THERE_IS_NO_COLUMN)
```
The same with type `Array(Tuple(x UInt32, y String))`:
```
$ clickhouse-client -q "create table t (arr Array(Tuple(x UInt32, y String))) engine=Memory"
$ clickhouse-client -q "desc table t"
arr.x	Array(UInt32)
arr.y	Array(String)
```
Actually, I don't know is it expected behaviour with Array of named Tuple, I will check it.
So, there are two different ways to handle it.
1) Disable setting `flatten_nested` while creating table:
```
clickhouse-client -q "create table t (arr Nested(x UInt32, y String)) engine=Memory" --flatten_nested=0
$ clickhouse-client -q "desc table t"
arr	Nested(x UInt32, y String)
$ cat data.avro | clickhouse-client -q "insert into t format Avro"
$ clickhouse-client -q "select * from t"
[(1,'123')]
```
2) Change code of input Avro format to handle such names with dots and process them as fields of Nested table. I will think how to do it properly

**Comment by ivantopo** [comment]
Hey @Avogar, thank you so much for sharing this! Exactly as you described, the issue was columns being flattened. I recreated my schema with `flatten_nested=0` and it worked exactly as expected!

**Comment by yusufozturk** [comment]
@Avogar in which release did you include this changes? We are testing in Altinity Cloud at the moment, but it doesn't work.

**Comment by ArtemiyNaumov** [comment]
@Avogar Hi, this topic is one of the few where the nested attributes for Avro format are discussed :)
So my only one option left is to ask here about my issue where I'm trying to deal with some complicated nested avro data, which is being read by my kafka engine table. Let's say, avro schema for messages looks like this:
```json
{
  "type" : "record",
  "name" : "Receipt",
  "namespace" : "some namespace",
  "fields" : [ {
    "name" : "id",
    "type" : [ "null", {
      "type" : "record",
      "name" : "id",
      "fields" : [ {
        "name" : "id",
        "type" : "string",
        "doc" : "Unique identificator"
      }, {
        "name" : "version",
        "type" : [ "null", "int" ],
        "doc" : "Document version",
        "default" : null
      }, {
        "name" : "creator",
        "type" : [ "null", "string" ],
        "doc" : "Document creator",
        "default" : null
      }, {
        "name" : "timestamp",
        "type" : [ "null", "string" ],
        "doc" : "Document creation timestamp",
        "default" : null
      } ]
    } ],
    "doc" : "Document identification",
    "default" : null
  }]
}
```
And I'm trying to read it with kafka engine table with the following ddl:
```sql
SET flatten_nested = 0;

CREATE TABLE default.test_kafka_table
(	
	id Tuple(Nested(
	    id String,
	    version Nullable(Int32),
	    creator Nullable(String),
	    timestamp Nullable(String)
	))
)
ENGINE Kafka()
SETTINGS
    kafka_broker_list = '<brokers>',
    kafka_topic_list = '<topic>',
    kafka_group_name = '<consumer-group>',
    kafka_format = 'AvroConfluent',
    format_avro_schema_registry_url = '<schema-registry>',
    kafka_handle_error_mode='stream';
```
But kafka engine table can't parse messages and throws an error about inconsistency in columns in tuple and in record:
`The number of leaves in record doesn't match the number of elements in tuple: column id: (at row 1)`
Why does it happen? Do I miss sth in table's DDL? Maybe my data types in DDL are wrong, but I described everything in accordance with [the docs](https://clickhouse.com/docs/en/interfaces/formats#data-format-avro)
I'm also aware that according to schema "id" column can be totally null, but in DDL I can't use stmt like id `Nullable(Tuple(Nested ...)))`

**Comment by Avogar** [comment]
Hi @ArtemiyNaumov!
It seems like your table definition is incorrect. As I can see from the Avro schema, it should be just `id Tuple(id Nullable(String), version Nullable(Int32), creator Nullable(String), timestamp Nullable(String))`. There is no need to use `Nested` type at all (you can think of `Nested` as just `Array(Tuple)`, and in Avro schema there is no arrays or nested tuples).

**Comment by ArtemiyNaumov** [comment]
@Avogar yeah, that seemed to work out! I finally managed to read topic without errors and reach messages' attributes. Thanks for your advice and quick response👍

**Pull request merged**
