### PR TITLE
remove part of misleading exception message

### LINKED ISSUE #19478: Part of exception message is misleading.
**Describe the issue**
```
SELECT xyz

Query id: 0c7d8017-4686-404c-9991-388d9a693e5f


0 rows in set. Elapsed: 0.003 sec. 

Received exception from server (version 21.2.1):
Code: 47. DB::Exception: Received from localhost:9000. DB::Exception: Missing columns: 'xyz' while processing query: 'SELECT xyz', required columns: 'xyz', maybe you meant: .
```

The fragment `maybe you meant: .` should not be present.

### PR DESCRIPTION
**Pull request by ucasfl**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):

- Not for changelog (changelog entry is not required)

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

closes #19478

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
I have to validate this message manually. It's suspected that it can output two consecutive whitespaces.

**Comment by ucasFL** [comment]
> I have to validate this message manually. It's suspected that it can output two consecutive whitespaces.

```
:) select xyz

SELECT xyz

Query id: 34565bc0-8d25-46bf-a835-fbf0b0031413


0 rows in set. Elapsed: 0.039 sec.

Received exception from server (version 21.2.1):
Code: 47. DB::Exception: Received from localhost:9000. DB::Exception: Missing columns: 'xyz' while processing query: 'SELECT xyz', required columns: 'xyz'.
```
it seems work well on my machine.

**Comment by alexey-milovidov** [comment]
Ok.

**Comment by alexey-milovidov** [comment]
@ucasFL 

```
SELECT * FROM system.asynchronous_metrics ORDER BY name

maybe you meant:  '['metric']' '['value']'.
```

There are three wrong things:
1. Double whitespace.
2. Lack of comma between items.
3. Bogus format - the items are wrapped into array of a single value for unknown reason.

Ideally it should look like this:
```
maybe you meant: 'metric', 'value'.
```

This variant is also Ok:
Ideally it should look like this:
```
maybe you meant: ['metric', 'value'].
```

**Comment by ucasFL** [comment]
> @ucasFL
> 
> ```
> SELECT * FROM system.asynchronous_metrics ORDER BY name
> 
> maybe you meant:  '['metric']' '['value']'.
> ```
> 
> There are three wrong things:
> 
> 1. Double whitespace.
> 2. Lack of comma between items.
> 3. Bogus format - the items are wrapped into array of a single value for unknown reason.
> 
> Ideally it should look like this:
> 
> ```
> maybe you meant: 'metric', 'value'.
> ```
> 
> This variant is also Ok:
> 
> ```
> maybe you meant: ['metric', 'value'].
> ```

Ok, I will fix it.

**Pull request merged**
