### PR TITLE
Fix function execution over const and LowCardinality with GROUP BY const for analyzer

### LINKED ISSUE #59684: Analyzer (experimental feature, not ready for production): failed assertion when using group by
```
milovidov@milovidov-desktop:~/work/ClickHouse/build_debug$ programs/clickhouse local --query "SELECT position(materialize(toNullable(toLowCardinality(''))), '', 1) GROUP BY GROUPING SETS ('') SETTINGS allow_experimental_analyzer = 1"
clickhouse: /home/milovidov/work/ClickHouse/src/Common/PODArray.h:380: const T &DB::PODArray<unsigned long, 4096, Allocator<false, false>, 63, 64>::operator[](ssize_t) const [T = unsigned long, initial_bytes = 4096, TAllocator = Allocator<false, false>, pad_right_ = 63, pad_left_ = 64]: Assertion `(n >= (static_cast<ssize_t>(pad_left_) ? -1 : 0)) && (n <= static_cast<ssize_t>(this->size()))' failed.
Aborted (core dumped)
```

### LINKED ISSUE #59779: [Analyzer] Logical error: 'Argument column 'Int32' size 0 doesn't match result column size 1 of function javaHash'
https://s3.amazonaws.com/clickhouse-test-reports/0/3c1c7bb824a65d436c1a0f0c99a16a4bc520da1e/ast_fuzzer__ubsan_.html

```
SELECT
    javaHash(toLowCardinality(materialize(-123)), toInt32(-123)),
    javaHash(toInt64(123)),
    javaHash(toInt64(12345678901))
GROUP BY javaHash(toInt32(-123))
SETTINGS allow_experimental_analyzer = 1
```

```
2024.02.08 21:27:35.829725 [ 540947 ] {3994b8fa-e25d-44ac-aa32-04603b106209} <Fatal> : Logical error: 'Argument column 'Int32' size 0 doesn't match result column size 1 of function javaHash'.
```

Does not trigger without the analyzer (You get `Code: 48. DB::Exception: Java hash is not combineable for multiple arguments. (NOT_IMPLEMENTED)` instead)

### LINKED ISSUE #59918: formatString: runtime error: addition of unsigned offset to X overflowed to Y
https://s3.amazonaws.com/clickhouse-test-reports/59908/4aa70c5b1271f41b62aa948964c625dd9fea66fa/ast_fuzzer__ubsan_.html

```sql
SELECT
    '|',
    toFixedString('42', toNullable(2)),
    concatWithSeparator('|', 'a', toFixedString('LowCardinality(Nullable(UInt32))', 32), concatWithSeparator('|', 'a', CAST('42', 'LowCardinality(Nullable(UInt32))')), CAST('42', 'LowCardinality(Nullable(UInt32))')) = toFixedString('a|42', 4)
GROUP BY 'a'
SETTINGS allow_suspicious_low_cardinality_types = 1, allow_experimental_analyzer = 1
```

### PR DESCRIPTION
**Pull request by azat**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix function execution over const and LowCardinality with GROUP BY const for analyzer

Consider the following example:

    SELECT concatWithSeparator('|', 'a', concatWithSeparator('|', CAST('x', 'LowCardinality(String)'))) GROUP BY 'a'

Under analyzer it fails, UBsan report:

    ==15121==WARNING: MemorySanitizer: use-of-uninitialized-value
      ...
      8 0x5555601880ed in void DB::FormatStringImpl::format<true, false>() /src/ch/clickhouse/src/Functions/formatString.h:125:21
      9 0x55556017aeb8 in void DB::FormatStringImpl::formatExecute<>() /src/ch/clickhouse/src/Functions/formatString.h:30:13
      10 0x555560196779 in DB::()::ConcatWithSeparatorImpl<>::executeImpl() const /src/ch/clickhouse/src/Functions/concatWithSeparator.cpp:151:9
      11 0x55555a2ad5b7 in DB::FunctionToExecutableFunctionAdaptor::executeImpl() const /src/ch/clickhouse/src/Functions/IFunctionAdaptor.h:21:26
      12 0x555584312297 in DB::IExecutableFunction::executeWithoutLowCardinalityColumns() const /src/ch/clickhouse/src/Functions/IFunction.cpp:249:15
      13 0x555584317640 in DB::IExecutableFunction::executeWithoutSparseColumns() const /src/ch/clickhouse/src/Functions/IFunction.cpp:283:24
      14 0x55558431bf5c in DB::IExecutableFunction::execute() const /src/ch/clickhouse/src/Functions/IFunction.cpp:380:16
      15 0x555587bf3e20 in DB::executeAction() /src/ch/clickhouse/src/Interpreters/ExpressionActions.cpp:613:60

    Uninitialized value was created by a heap allocation
      ...
      6 0x55558b1c1a05 in DB::ColumnString::reserve(unsigned long) /src/ch/clickhouse/src/Columns/ColumnString.cpp:494:13
      7 0x55558980095d in DB::prepareOutputBlockColumns() /src/ch/clickhouse/src/Interpreters/AggregationUtils.cpp:32:25

The problem is that during query analysis
(QueryAnalyzer::resolveFunction()), the return value of the function had been executed as LowCardinality(String), but the 'a' argument that is passed to the concatWithSeparator() is not-const, because it had been reused from the GROUP BY step, and this causes UB, since column 'a' does not have enough rows (it should have 2 rows, since LowCardinality always contains the default, while it has only 1).

So to address this we need to take column as-is for aggregation.

Cc: @kitaisreal 
Fixes: https://github.com/ClickHouse/ClickHouse/issues/59918
Fixes: https://github.com/ClickHouse/ClickHouse/issues/59684
Fixes: https://github.com/ClickHouse/ClickHouse/issues/59779

### CODE REVIEW

**Comment by robot-ch-test-poll4** [comment]
*This is an automated comment for commit 7c2b8c9e39c09ad1905cfbf7a3ab97c51205d4e1 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/59986/7c2b8c9e39c09ad1905cfbf7a3ab97c51205d4e1/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/59986/7c2b8c9e39c09ad1905cfbf7a3ab97c51205d4e1/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Comment by yakov-olkhovskiy** [comment]
I have another solution for this, but not sure it's correct
https://github.com/ClickHouse/ClickHouse/pull/60046
@azat could you please take a look?

**Review by novikd — APPROVED** [review]

**Comment by novikd** [comment]
AFAIU the tests fail because of `WITH TOTALS`. I think it's okay to just update reference files.

**Comment by azat** [comment]
Not all of them, need to take a more careful look.

**Comment by novikd** [comment]
@azat What do you mean? Both tests in `Fast tests` check are failed due to how we handle constants in TOTALS pocket.

**Comment by azat** [comment]
> What do you mean? Both tests in Fast tests check are failed due to how we handle constants in TOTALS pocket.

Yeah, you are right, I guess this comment was for some old failure, that had been fixed in [`b5c765c` (#59986)](https://github.com/ClickHouse/ClickHouse/pull/59986/commits/b5c765c804b21bff51a9b97d8a631c47af4ae01f)

Anyway, I've fixed the remaining tests, let's see.

**Comment by azat** [comment]
>ClickHouse build check — 18/19 artifact groups are OK

```
Mar 09 01:02:38 FAILED: src/CMakeFiles/dbms.dir/Functions/CastOverloadResolver.cpp.o 
Mar 09 01:02:38 LLVM ERROR: out of memory
```

- https://github.com/ClickHouse/ClickHouse/pull/61114

**Comment by azat** [comment]
Test failures **does related**

>Stateless tests (release, analyzer, s3, DatabaseReplicated) [2/4] — fail: 1, passed: 1557, skipped: 34

- `02579_fill_empty_chunk`

>Stateless tests (release, analyzer, s3, DatabaseReplicated) [3/4] — fail: 1, passed: 1484, skipped: 43

- `01056_predicate_optimizer_bugs`

Looking into it

**Comment by azat** [comment]
- `02579_fill_empty_chunk` - the problem is different behavior in analyzer, but analyzer is correct one

<details>

```sql
SELECT
    2 AS x,
    arrayJoin([NULL, NULL, NULL])
GROUP BY
    GROUPING SETS (
        (0),
        ([NULL, NULL, NULL]))
ORDER BY x ASC
SETTINGS allow_experimental_analyzer = 1, enable_positional_arguments = 0

Query id: 9b7f209d-f10a-4f35-9815-0c7fc76c9862

┌─x─┬─arrayJoin([NULL, NULL, NULL])─┐
│ 2 │ ᴺᵁᴸᴸ                          │
│ 2 │ ᴺᵁᴸᴸ                          │
│ 2 │ ᴺᵁᴸᴸ                          │
└───┴───────────────────────────────┘
┌─x─┬─arrayJoin([NULL, NULL, NULL])─┐
│ 2 │ ᴺᵁᴸᴸ                          │
│ 2 │ ᴺᵁᴸᴸ                          │
│ 2 │ ᴺᵁᴸᴸ                          │
└───┴───────────────────────────────┘

SELECT
    2 AS x,
    arrayJoin([NULL, NULL, NULL])
GROUP BY
    GROUPING SETS (
        (0),
        ([NULL, NULL, NULL]))
ORDER BY x ASC
SETTINGS allow_experimental_analyzer = 0, enable_positional_arguments = 0

Query id: 4ddcfaa0-6f06-45e6-aab1-96606536c536

┌─x─┬─arrayJoin([NULL, NULL, NULL])─┐
│ 2 │ ᴺᵁᴸᴸ                          │
│ 2 │ ᴺᵁᴸᴸ                          │
│ 2 │ ᴺᵁᴸᴸ                          │
└───┴───────────────────────────────┘
```

</details>

- `01056_predicate_optimizer_bugs` - the problem is that the const property is preserved and the filter does not work, but the original bug (https://github.com/ClickHouse/ClickHouse/issues/5682) was about predicate push down, so I've adjusted the test - [`0e9c648` (#59986)](https://github.com/ClickHouse/ClickHouse/pull/59986/commits/0e9c64899a5fe86f08d51ada8d5a779e516735fd)

**Comment by azat** [comment]
>Bugfix validation — New test(s) failed to reproduce a bug

- https://github.com/ClickHouse/ClickHouse/pull/61363

**Review by novikd — APPROVED** [review]

**Comment by tavplubix** [comment]
@novikd, @azat looks like this PR has introduced a crash that happens quite often in the CI:
[CI DB query](https://play.clickhouse.com/play?user=play#CldJVEgKICAgICcnIEFTIG5hbWVfc3Vic3RyLAogICAgOTAgQVMgaW50ZXJ2YWxfZGF5cywKICAgICgnU3RhdGVsZXNzIHRlc3RzIChhc2FuKScsICdTdGF0ZWxlc3MgdGVzdHMgKGFkZHJlc3MpJywgJ1N0YXRlbGVzcyB0ZXN0cyAoYWRkcmVzcywgYWN0aW9ucyknKSBBUyBiYWNrcG9ydF9hbmRfcmVsZWFzZV9zcGVjaWZpY19jaGVja3MKU0VMRUNUCiAgICB0b1N0YXJ0T2ZEYXkoY2hlY2tfc3RhcnRfdGltZSkgQVMgZCwKICAgIGNvdW50KCksCiAgICBncm91cFVuaXFBcnJheShwdWxsX3JlcXVlc3RfbnVtYmVyKSBBUyBwcnMsCiAgICBhbnkocmVwb3J0X3VybCkKRlJPTSBjaGVja3MKV0hFUkUgKChub3coKSAtIHRvSW50ZXJ2YWxEYXkoaW50ZXJ2YWxfZGF5cykpIDw9IGNoZWNrX3N0YXJ0X3RpbWUpIEFORCAocHVsbF9yZXF1ZXN0X251bWJlciBOT1QgSU4gKAogICAgU0VMRUNUIHB1bGxfcmVxdWVzdF9udW1iZXIgQVMgcHJuCiAgICBGUk9NIGNoZWNrcwogICAgV0hFUkUgKHBybiAhPSAwKSBBTkQgKChub3coKSAtIHRvSW50ZXJ2YWxEYXkoaW50ZXJ2YWxfZGF5cykpIDw9IGNoZWNrX3N0YXJ0X3RpbWUpIEFORCAoY2hlY2tfbmFtZSBJTiAoYmFja3BvcnRfYW5kX3JlbGVhc2Vfc3BlY2lmaWNfY2hlY2tzKSkKKSkgQU5EIChwb3NpdGlvbih0ZXN0X25hbWUsIG5hbWVfc3Vic3RyKSA+IDApIEFORCAodGVzdF9zdGF0dXMgSU4gKCdGQUlMJywgJ0VSUk9SJywgJ0ZMQUtZJykpIGFuZCB0ZXN0X2NvbnRleHRfcmF3IGxpa2UgJyVDb2x1bW5OdWxsYWJsZTo6Y2hlY2tDb25zaXN0ZW5jeSgpJScKR1JPVVAgQlkgZApPUkRFUiBCWSBkIERFU0MK)

Examples:
segfault: https://s3.amazonaws.com/clickhouse-test-reports/0/fd8fa63abc221532edbf300a47ff3dc246f51f8c/stress_test__asan_.html
use of uninitialized value: https://s3.amazonaws.com/clickhouse-test-reports/0/b8b977e99fefcedcd55900b3198f5a317c7f5090/stress_test__msan_.html

```
 [ 27510 ] {} <Fatal> BaseDaemon: ########## Short fault info ############
 [ 27510 ] {} <Fatal> BaseDaemon: (version 24.3.1.1 (official build), build id: 64BDB31C750E14EE0A031C85058ECC3C0F8E570F, git hash: fd8fa63abc221532edbf300a47ff3dc246f51f8c) (from thread 25045) Received signal 11
 [ 27510 ] {} <Fatal> BaseDaemon: Signal description: Segmentation fault
 [ 27510 ] {} <Fatal> BaseDaemon: Address: NULL pointer. Access: read. Unknown si_code.
 [ 27510 ] {} <Fatal> BaseDaemon: Stack trace: 0x000055f1e5667af4 0x000055f1e153efbf 0x000055f1e846615c 0x000055f1e83cce84 0x000055f1e83c5f5e 0x000055f1e83a9bdc 0x000055f1e83eb011 0x000055f1efe8280f 0x000055f1efe834b7 0x000055f1f029043c 0x000055f1f0289428 0x000055f1bfe8e91b 0x00007f4456ed0ac3 0x0000
 [ 27510 ] {} <Fatal> BaseDaemon: ########################################
 [ 27510 ] {} <Fatal> BaseDaemon: (version 24.3.1.1 (official build), build id: 64BDB31C750E14EE0A031C85058ECC3C0F8E570F, git hash: fd8fa63abc221532edbf300a47ff3dc246f51f8c) (from thread 25045) (query_id: e50d5b28-c713-444a-accb-7a3bce1b318a) (query: SELECT 12 AS n GROUP BY n WITH ROLLUP;) Received 
 [ 27510 ] {} <Fatal> BaseDaemon: Address: NULL pointer. Access: read. Unknown si_code.
 [ 27510 ] {} <Fatal> BaseDaemon: Stack trace: 0x000055f1e5667af4 0x000055f1e153efbf 0x000055f1e846615c 0x000055f1e83cce84 0x000055f1e83c5f5e 0x000055f1e83a9bdc 0x000055f1e83eb011 0x000055f1efe8280f 0x000055f1efe834b7 0x000055f1f029043c 0x000055f1f0289428 0x000055f1bfe8e91b 0x00007f4456ed0ac3 0x0000
 [ 27510 ] {} <Fatal> BaseDaemon: 3. ./build_docker/./src/Columns/ColumnNullable.cpp:786: DB::ColumnNullable::checkConsistency() const @ 0x000000002ff92af4
 [ 27510 ] {} <Fatal> BaseDaemon: 4. ./build_docker/./src/DataTypes/Serializations/SerializationNullable.cpp:117: DB::SerializationNullable::serializeBinaryBulkWithMultipleStreams(DB::IColumn const&, unsigned long, unsigned long, DB::ISerialization::SerializeBinaryBulkSettings&, std::shared_ptr<DB::
 [ 27510 ] {} <Fatal> BaseDaemon: 5.0. inlined from ./build_docker/./src/Formats/NativeWriter.cpp:64: DB::writeData(DB::ISerialization const&, COW<DB::IColumn>::immutable_ptr<DB::IColumn> const&, DB::WriteBuffer&, unsigned long, unsigned long)
 [ 27510 ] {} <Fatal> BaseDaemon: 5. ./build_docker/./src/Formats/NativeWriter.cpp:164: DB::NativeWriter::write(DB::Block const&) @ 0x0000000032d9115c
 [ 27510 ] {} <Fatal> BaseDaemon: 6. ./build_docker/./src/Server/TCPHandler.cpp:0: DB::TCPHandler::sendData(DB::Block const&) @ 0x0000000032cf7e84
 [ 27510 ] {} <Fatal> BaseDaemon: 7. ./build_docker/./src/Server/TCPHandler.cpp:1056: DB::TCPHandler::processOrdinaryQueryWithProcessors() @ 0x0000000032cf0f5e
 [ 27510 ] {} <Fatal> BaseDaemon: 8. ./build_docker/./src/Server/TCPHandler.cpp:0: DB::TCPHandler::runImpl() @ 0x0000000032cd4bdc
 [ 27510 ] {} <Fatal> BaseDaemon: 9. ./build_docker/./src/Server/TCPHandler.cpp:2331: DB::TCPHandler::run() @ 0x0000000032d16011
 [ 27510 ] {} <Fatal> BaseDaemon: 10. ./build_docker/./base/poco/Net/src/TCPServerConnection.cpp:57: Poco::Net::TCPServerConnection::start() @ 0x000000003a7ad80f
 [ 27510 ] {} <Fatal> BaseDaemon: 11.0. inlined from ./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:48: std::default_delete<Poco::Net::TCPServerConnection>::operator()[abi:v15000](Poco::Net::TCPServerConnection*) const
 [ 27510 ] {} <Fatal> BaseDaemon: 11.1. inlined from ./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:305: std::unique_ptr<Poco::Net::TCPServerConnection, std::default_delete<Poco::Net::TCPServerConnection>>::reset[abi:v15000](Poco::Net::TCPServerConnection*)
 [ 27510 ] {} <Fatal> BaseDaemon: 11.2. inlined from ./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:259: ~unique_ptr
 [ 27510 ] {} <Fatal> BaseDaemon: 11. ./build_docker/./base/poco/Net/src/TCPServerDispatcher.cpp:116: Poco::Net::TCPServerDispatcher::run() @ 0x000000003a7ae4b7
 [ 27510 ] {} <Fatal> BaseDaemon: 12. ./build_docker/./base/poco/Foundation/src/ThreadPool.cpp:0: Poco::PooledThread::run() @ 0x000000003abbb43c
 [ 27510 ] {} <Fatal> BaseDaemon: 13.0. inlined from ./base/poco/Foundation/include/Poco/SharedPtr.h:231: Poco::SharedPtr<Poco::Runnable, Poco::ReferenceCounter, Poco::ReleasePolicy<Poco::Runnable>>::get()
 [ 27510 ] {} <Fatal> BaseDaemon: 13.1. inlined from ./base/poco/Foundation/include/Poco/SharedPtr.h:139: Poco::SharedPtr<Poco::Runnable, Poco::ReferenceCounter, Poco::ReleasePolicy<Poco::Runnable>>::assign(Poco::Runnable*)
 [ 27510 ] {} <Fatal> BaseDaemon: 13.2. inlined from ./base/poco/Foundation/include/Poco/SharedPtr.h:180: Poco::SharedPtr<Poco::Runnable, Poco::ReferenceCounter, Poco::ReleasePolicy<Poco::Runnable>>::operator=(Poco::Runnable*)
 [ 27510 ] {} <Fatal> BaseDaemon: 13. ./base/poco/Foundation/src/Thread_POSIX.cpp:350: Poco::ThreadImpl::runnableEntry(void*) @ 0x000000003abb4428
 [ 27510 ] {} <Fatal> BaseDaemon: 14. asan_thread_start(void*) @ 0x000000000a7b991b
 [ 27510 ] {} <Fatal> BaseDaemon: 15. ? @ 0x00007f4456ed0ac3
 [ 27510 ] {} <Fatal> BaseDaemon: 16. ? @ 0x00007f4456f62850
 [ 27510 ] {} <Fatal> BaseDaemon: Integrity check of the executable successfully passed (checksum: 3DAB30269CD3E9BA6413BEC087983A67)
 [ 27510 ] {} <Fatal> BaseDaemon: Report this error to https://github.com/ClickHouse/ClickHouse/issues
 [ 27510 ] {} <Fatal> BaseDaemon: Changed settings: min_compress_block_size = 132786, max_compress_block_size = 1397473, max_block_size = 80170, max_insert_threads = 8, max_threads = 63, max_read_buffer_size = 844524, connect_timeout_with_failover_ms = 2000, connect_timeout_with_failover_secure_ms =
 [ 3405 ] {} <Fatal> Application: Child process was terminated by signal 11.
```

**Comment by tavplubix** [comment]
And some failures on the last commit in this PR are very suspicious:
AST fuzzer (tsan) — Received signal 11 - [Details](https://s3.amazonaws.com/clickhouse-test-reports/59986/0e9c64899a5fe86f08d51ada8d5a779e516735fd/ast_fuzzer__tsan_.html)
Stress test (debug) — Killed by signal (in clickhouse-server.log) - [Details](https://s3.amazonaws.com/clickhouse-test-reports/59986/0e9c64899a5fe86f08d51ada8d5a779e516735fd/stress_test__debug_.html)

**Comment by antonio2368** [comment]
@tavplubix most likely fixed with https://github.com/ClickHouse/ClickHouse/pull/61717

**Comment by clickgapai** [comment]
Hi @azat @novikd — while reviewing this PR I found the following:

- **Coverage gap:** GROUPING SETS branch of `analyzeAggregation` const-preservation has no structural assertion — https://github.com/ClickHouse/ClickHouse/pull/103856

Could you review the test PR and add the `can be tested` label if it looks good?
Happy to discuss — close anything that's wrong or already addressed.

**Pull request merged**
