### PR TITLE
Untangle setting headers

### PR DESCRIPTION
**Pull request by Algunenano**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
- Untangle setting headers

### Documentation entry for user-facing changes
x

This is a step towards private Setting* objects, which is a step itself towards Setting categories.

Massively reduces the number of affected files when SettingEnums.h / Settings.h / MergeSettings.h are changed. For example changing `SettingEnums.h` goes from affecting ~2500 files to ~650, and Settings.h goes from ~1500 to ~550. This helps massively developing anything that relates to settings, or adding new settings.

I'm merging this first since it's already affecting 440 files and it's only a refactor so far, but it's better to confirm everything is fine before doing additional, hundreds of, changes on top.

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Do not test
- [x]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-ch-test-poll3** [comment]
*This is an automated comment for commit 1b75b8f4eb49557d42443a35dca8a5119dfc4fa0 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/66404/1b75b8f4eb49557d42443a35dca8a5119dfc4fa0/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
The changes LGTM.

**Comment by alexey-milovidov** [comment]
@Algunenano, what do you think about this? https://github.com/ClickHouse/ClickHouse/issues/58797

**Comment by Algunenano** [comment]
> @Algunenano, what do you think about this? https://github.com/ClickHouse/ClickHouse/issues/58797

I'm planning on fixing it and hiding the object contents completely right after this PR. The idea is that the `Settings` objects will contain an array of `SettingFieldBaseClass` and most of the time we'd access a setting by calling `getUInt64(settingRef, "string")`.  I prefer not exposing `Settings::max_thread` as that allows to hide the implementation completely, it's worse for IDEs but much better when we do any change. With this we could add a new setting, or change it's value/description, compile just one file, link and we're done.

For the other 1%, we could have special functions (we already have some here and there)

**Comment by nikitamikhaylov** [comment]
@Algunenano `getUInt64(settingRef, "string")` looks like not a good design, because you can easily make a typo and will debug it for hours. About `Settings::max_thread`: you will not expose it, it will be completely the same as ErrorCodes or CurrentMetrics, but you will need to `export` them everywhere.

**Comment by Algunenano** [comment]
> @Algunenano getUInt64(settingRef, "string") looks like not a good design, because you can easily make a typo and will debug it for hours.
> About Settings::max_thread: you will not expose it

We could do for something like (using `MergeTreeSettings` because it's easier to see):

* Call
```
#include <Storages/MergeTree/MergeTreeSettingGetter.h>

namespace MergeTreeSettings
{
extern const int replicated_max_parallel_fetches_for_table;
}

getInt64(settingRef, MergeTreeSettings::max_partitions_to_read)
```

* `Storages/MergeTree/MergeTreeSettingGetter.h`: Would just have the forward reference for MergeTreeSettingsStruct and for the getters.

Does that makes more sense?

**Comment by nikitamikhaylov** [comment]
Yes, exactly. This is what was written in Alexey's issue I suppose 🤣

**Comment by Algunenano** [comment]
> But wait, why do we need to a forward reference? CurrentMetrics work without it. 

We are not passing, copying and modifying CurrentMetrics objects all the time. If everyone knows about Settings, everyone needs to know about BaseSettings and SettingEnums, and again adding a new setting or a value might involve rebuilding thousands of files. Most of the users never hold an object, just a reference, so it's more natural to not expose it.

**Comment by Algunenano** [comment]
Another reason to prefer forward declarations: Many times when we use objects, it's by mistake:  https://github.com/ClickHouse/ClickHouse/pull/66404/commits/56f497bf7f748bb36b187477e93195567b8fefdd. I should probably remove `getSettingsRef()`, make `getSettings()` return a const reference, and make explicit copies when needed.

**Comment by alexey-milovidov** [comment]
Yes, I'm in favor of this change. Maybe rename `getSettings` to `getSettingsCopy`?

**Pull request merged**
