### PR TITLE
Allow trailing commas in types with several items

### LINKED ISSUE #59023: Allow trailing comma in the list of Tuple's types
Examples:

```
Tuple(
    UInt64,
    String,
)
```

```
Tuple(
    x UInt64,
    y String,
)
```

### PR DESCRIPTION
**Pull request by AVMusorin**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Allow trailing commas in types with several items

```sql
SELECT (1, 'foo')::Tuple(a Int, b String,);
SELECT (1, 'foo')::Tuple(Int, String,);
SELECT (1, (2,'foo'))::Tuple(Int, Tuple(Int, String,),);
````

Closes: https://github.com/ClickHouse/ClickHouse/issues/59023

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by robot-ch-test-poll1** [comment]
*This is an automated comment for commit e0bef11716eb7f8ca2d559a2d621e14fc2f78fb5 with description of existing statuses. It's updated for the latest CI running*

[❌ Click here](https://s3.amazonaws.com/clickhouse-test-reports/59119/e0bef11716eb7f8ca2d559a2d621e14fc2f78fb5/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>❌ failure</td></tr>
<tbody>
</table>

**Comment by AVMusorin** [comment]
@yariks5s could you please take a look? Failed checks don't look related to this PR.

**Review by yariks5s — APPROVED** [review]

**Comment by yariks5s** [comment]
Could you please sync your branch with master?

**Comment by yariks5s** [comment]
Features requires adding some info to docs, so I think it's better to mark this PR as `improvement`

**Comment by yariks5s** [comment]
My apologies, I don't have the rights to sync your changes (to restart testing, because with the `pr-feature` label it was required to enhance docs), could you please do it again?

**Comment by AVMusorin** [comment]
No problem!

**Pull request merged**
