### PR TITLE
Added information about preconfigured roles in users.xml to the docs

### PR DESCRIPTION
**Pull request by pufit**
### Changelog category (leave one):
- Documentation (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Documentation for https://github.com/ClickHouse/ClickHouse/pull/50278

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by robot-ch-test-poll1** [comment]
*This is an automated comment for commit f49894f6446ce586d04add78c59b7bc0fc5c5f09 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/57837/f49894f6446ce586d04add78c59b7bc0fc5c5f09/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td><a href="https://github.com/ClickHouse/ClickHouse/actions/runs/7204493559">✅ success</a></td></tr>
<tbody>
</table>
</details>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/57837/f49894f6446ce586d04add78c59b7bc0fc5c5f09/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Comment by nikitamikhaylov** [comment]
@pufit What about Russian version of documentation?

**Comment by alexey-milovidov** [comment]
@nikitamikhaylov, We dgaf.

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
But if the translated page is outdated, we can replace it with the English page without translation.

**Pull request merged**
