### PR TITLE
[feature] A setting `http_response_headers`

### PR DESCRIPTION
**Pull request by GSokol**
- Implementing https://github.com/ClickHouse/ClickHouse/issues/59620
- Deprecating `content_type` setting (still supported).

### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Add `http_response_headers` setting to support custom response headers in custom HTTP handlers 

### Documentation entry for user-facing changes

- [x] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by GSokol** [comment]
I'm going to add tests and documentation for this as well...

**Comment by GSokol** [comment]
For some reason `clang-format` made huge changes.

**Comment by robot-ch-test-poll2** [comment]
*This is an automated comment for commit d54df9c0432060fb19054cd9c508227900c19253 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/63562/d54df9c0432060fb19054cd9c508227900c19253/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

**Comment by GSokol** [comment]
@CheSema, I guess, I need help: `test_mask_sensitive_info/test.py::test_create_table` is failing on my side as well. But error is wired and doesn't seam like related ti the stuff I've touched.

**Comment by GSokol** [comment]
I will try to revert extra styling changes.

**Comment by GSokol** [comment]
@CheSema, now `test_checking_s3_blobs_paranoid/test.py::test_query_is_canceled_with_inf_retries` failed, which, as I understand is some flaky one. So, I think, the PR is ready for review.

**Review by CheSema — APPROVED** [review]

**Pull request merged**
