### PR TITLE
Implement formatDateTime fractional second formatter

### PR DESCRIPTION
**Pull request by ltrk2**
Implements functionality requested in #33704.

### Changelog category (leave one):
- New Feature

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Implemented a fractional second formatter (`%f`) for formatDateTime.

### CODE REVIEW

**Comment by davenger** [comment]
Please add test cases were where fractional part starts with 0s (e.g. ".001") to make sure they are not lost.

**Comment by ltrk2** [comment]
@davenger great call, thanks!

**Comment by davenger** [comment]
Function toFractionalSecond() seems confusing: looks like the caller cannot interpret its return value without knowing the precision of the original value. It might be better to always return nanoseconds regardless of the original precision and name it toNanosecond() or add precision parameter and convert to the specified precision.

**Comment by ltrk2** [comment]
@davenger hmm.. that certainly is a valid point. I figured I'd just add it as a bonus. I'll drop that part for now, since I don't want to contribute something half-baked without a real use-case.

**Comment by rschu1ze** [comment]
@ltrk2 You will be interested in #43818 (which is almost merged). Do you think it is possible to implement the same format also for Joda style?

**Comment by ltrk2** [comment]
@rschu1ze looking at the patch it certainly is a possibility for `formatDateTimeInJodaSyntax`. As for what `fromUnixTimestampInJodaSyntax` should do if it encountered a fractional second formatter could be a matter of debate.

**Pull request merged**
