### PR TITLE
Enable musl and jemalloc for arm.

### PR DESCRIPTION
**Pull request by amosbird**
Can generate better arm packages.

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Category (leave one):
- Build/Testing/Packaging Improvement

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]

**Comment by amosbird** [comment]
Some findings when building and testing arm build.

-### gcc bugs 

1. capnp fails to compile
2. bit rotation

```
during RTL pass: expand
In file included from /data1/ClickHouse/src/dbms/src/Functions/bitRotateLeft.cpp:2:
/data1/ClickHouse/src/dbms/src/Functions/FunctionBinaryArithmetic.h: In static member function 'static void DB::BinaryOperationImplBase<A, B, Op, ResultType_>::vector_constant(DB::PaddedPODArray<T>&, B, DB::PaddedPODArray<ResultType_>&) [with A = unsigned char; B = long unsigned int; Op = DB::BitRotateLeftImpl<unsigned char, long unsigned int>; ResultType_ = long unsigned int]':
/data1/ClickHouse/src/dbms/src/Functions/FunctionBinaryArithmetic.h:73:13: internal compiler error: in expand_shift_1, at expmed.c:2635
   73 |             c[i] = Op::template apply<ResultType>(a[i], b);
      |             ^
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://bugs.gentoo.org/> for instructions.
[2848/3291] Building CXX object dbms/src/Functions/CMakeFiles/clickhouse_functions.dir/bitRotateRight.cpp.o
FAILED: dbms/src/Functions/CMakeFiles/clickhouse_functions.dir/bitRotateRight.cpp.o
/home/amos/gentoo/usr/bin/ccache /home/amos/gentoo/usr/bin/c++  -DBOOST_SYSTEM_NO_DEPRECATED -DLZ4_DISABLE_DEPRECATE_WARNINGS=1 -DPOCO_STATIC -DPOCO_UNBUNDLED_ZLIB -DWITH_GZFILEOP -DZLIB_COMPAT -Idbms/src/Functions/include -Idbms/src/Core/include -I/data1/ClickHouse/src/dbms/src -Idbms/src -I/data1/ClickHouse/src/libs/libcommon/include -Ilibs/libcommon/include -I/data1/ClickHouse/src/contrib/zlib-ng -Icontrib/zlib-ng -I/data1/ClickHouse/src/contrib/cityhash102/include -I/data1/ClickHouse/src/contrib/croaring -I/data1/ClickHouse/src/libs/libmysqlxx/include -I/data1/ClickHouse/src/contrib/mariadb-connector-c/include -Icontrib/mariadb-connector-c/include -I/data1/ClickHouse/src/libs/consistent-hashing -I/data1/ClickHouse/src/libs/consistent-hashing-sumbur -I/data1/ClickHouse/src/contrib/libfarmhash -I/data1/ClickHouse/src/contrib/murmurhash/include -isystem /data1/ClickHouse/src/contrib/libdivide -isystem /data1/ClickHouse/src/contrib/libmetrohash/src -isystem /data1/ClickHouse/src/contrib/sparsehash-c11 -isystem /data1/ClickHouse/src/contrib/base64/include -isystem /data1/ClickHouse/src/contrib/lz4/lib -isystem /data1/ClickHouse/src/contrib/h3/src/h3lib/include -isystem /data1/ClickHouse/src/contrib/rapidjson/include -isystem /data1/ClickHouse/src/contrib/pdqsort -isystem /data1/ClickHouse/src/contrib/libpcg-random/include -isystem /data1/ClickHouse/src/contrib/double-conversion -isystem /data1/ClickHouse/src/contrib/re2 -isystem /data1/ClickHouse/src/contrib/poco/Util/include -isystem /data1/ClickHouse/src/contrib/poco/Foundation/include -isystem /data1/ClickHouse/src/contrib/poco/XML/include -isystem /data1/ClickHouse/src/contrib/poco/JSON/include -isystem /data1/ClickHouse/src/contrib/boost -isystem /data1/ClickHouse/src/contrib/poco/Net/include -isystem contrib/re2_st -isystem /data1/ClickHouse/src/contrib/ssl/include -isystem contrib/h3/src/h3lib/include -fdiagnostics-color=always -fsized-deallocation  -pipe -march=native  -fno-omit-frame-pointer  -Wall  -Wnon-virtual-dtor -Wno-array-bounds -Wextra -Werror -Wshadow -O2 -g -DNDEBUG -O3    -D OS_LINUX -fno-tree-loop-distribute-patterns -g0 -std=c++17 -MD -MT dbms/src/Functions/CMakeFiles/clickhouse_functions.dir/bitRotateRight.cpp.o -MF dbms/src/Functions/CMakeFiles/clickhouse_functions.dir/bitRotateRight.cpp.o.d -o dbms/src/Functions/CMakeFiles/clickhouse_functions.dir/bitRotateRight.cpp.o -c /data1/ClickHouse/src/dbms/src/Functions/bitRotateRight.cpp
during RTL pass: expand
In file included from /data1/ClickHouse/src/dbms/src/Functions/bitRotateRight.cpp:2:
/data1/ClickHouse/src/dbms/src/Functions/FunctionBinaryArithmetic.h: In static member function 'static void DB::BinaryOperationImplBase<A, B, Op, ResultType_>::vector_constant(DB::PaddedPODArray<T>&, B, DB::PaddedPODArray<ResultType_>&) [with A = unsigned char; B = long unsigned int; Op = DB::BitRotateRightImpl<unsigned char, long unsigned int>; ResultType_ = long unsigned int]':
/data1/ClickHouse/src/dbms/src/Functions/FunctionBinaryArithmetic.h:73:13: internal compiler error: in expand_shift_1, at expmed.c:2635
   73 |             c[i] = Op::template apply<ResultType>(a[i], b);
      |             ^
Please submit a full bug report,
with preprocessed source if appropriate.
```

3. point_in_polygon
```
FAILED: dbms/src/Functions/CMakeFiles/clickhouse_functions.dir/pointInPolygon.cpp.o
/home/amos/gentoo/usr/bin/ccache /home/amos/gentoo/usr/bin/c++  -DBOOST_SYSTEM_NO_DEPRECATED -DLZ4_DISABLE_DEPRECATE_WARNINGS=1 -DPOCO_STATIC -DPOCO_UNBUNDLED_ZLIB -DWITH_GZFILEOP -DZLIB_COMPAT -Idbms/src/Functions/include -Idbms/src/Core/include -I/data1/ClickHouse/src/dbms/src -Idbms/src -I/data1/ClickHouse/src/libs/libcommon/include -Ilibs/libcommon/include -I/data1/ClickHouse/src/contrib/zlib-ng -Icontrib/zlib-ng -I/data1/ClickHouse/src/contrib/cityhash102/include -I/data1/ClickHouse/src/contrib/croaring -I/data1/ClickHouse/src/libs/libmysqlxx/include -I/data1/ClickHouse/src/contrib/mariadb-connector-c/include -Icontrib/mariadb-connector-c/include -I/data1/ClickHouse/src/libs/consistent-hashing -I/data1/ClickHouse/src/libs/consistent-hashing-sumbur -I/data1/ClickHouse/src/contrib/libfarmhash -I/data1/ClickHouse/src/contrib/murmurhash/include -isystem /data1/ClickHouse/src/contrib/libdivide -isystem /data1/ClickHouse/src/contrib/libmetrohash/src -isystem /data1/ClickHouse/src/contrib/sparsehash-c11 -isystem /data1/ClickHouse/src/contrib/base64/include -isystem /data1/ClickHouse/src/contrib/lz4/lib -isystem /data1/ClickHouse/src/contrib/h3/src/h3lib/include -isystem /data1/ClickHouse/src/contrib/rapidjson/include -isystem /data1/ClickHouse/src/contrib/pdqsort -isystem /data1/ClickHouse/src/contrib/libpcg-random/include -isystem /data1/ClickHouse/src/contrib/double-conversion -isystem /data1/ClickHouse/src/contrib/re2 -isystem /data1/ClickHouse/src/contrib/poco/Util/include -isystem /data1/ClickHouse/src/contrib/poco/Foundation/include -isystem /data1/ClickHouse/src/contrib/poco/XML/include -isystem /data1/ClickHouse/src/contrib/poco/JSON/include -isystem /data1/ClickHouse/src/contrib/boost -isystem /data1/ClickHouse/src/contrib/poco/Net/include -isystem contrib/re2_st -isystem /data1/ClickHouse/src/contrib/ssl/include -isystem contrib/h3/src/h3lib/include -fdiagnostics-color=always -fsized-deallocation  -pipe -march=native  -fno-omit-frame-pointer  -Wall  -Wnon-virtual-dtor -Wno-array-bounds -Wextra -Werror -Wshadow -O2 -g -DNDEBUG -O3    -D OS_LINUX -fno-tree-loop-distribute-patterns -g0 -std=c++17 -MD -MT dbms/src/Functions/CMakeFiles/clickhouse_functions.dir/pointInPolygon.cpp.o -MF dbms/src/Functions/CMakeFiles/clickhouse_functions.dir/pointInPolygon.cpp.o.d -o dbms/src/Functions/CMakeFiles/clickhouse_functions.dir/pointInPolygon.cpp.o -c /data1/ClickHouse/src/dbms/src/Functions/pointInPolygon.cpp
In file included from /data1/ClickHouse/src/dbms/src/Functions/pointInPolygon.cpp:2:
/data1/ClickHouse/src/dbms/src/Functions/GeoUtils.h: In member function 'void DB::GeoUtils::PointInPolygonWithGrid<CoordinateType>::buildGrid() [with CoordinateType = double]':
/data1/ClickHouse/src/dbms/src/Functions/GeoUtils.h:264:47: error: '*((void*)& box +8)' may be used uninitialized in this function [-Werror=maybe-uninitialized]
  264 |         CoordinateType y_min = min_corner.y() + row * cell_height;
/data1/ClickHouse/src/dbms/src/Functions/GeoUtils.h:270:51: error: 'box' may be used uninitialized in this function [-Werror=maybe-uninitialized]
  270 |             CoordinateType x_max = min_corner.x() + (col + 1) * cell_width;
cc1plus: all warnings being treated as errors
[29/306] Building CXX object dbms/src/Functions/CMakeFiles/clickhouse_functions.dir/sumburConsistentHash.cpp.o
ninja: build stopped: subcommand failed.
```
-### stateless tests with gcc build and ub build work almost well

```
2019-10-13 11:14:47 00120_join_and_group_by:                                                [ FAIL ] - result differs with reference:
2019-10-13 11:14:53 00823_capnproto_input:                                                  [ FAIL ] - return code 73
2019-10-13 11:14:58 00950_test_double_delta_codec:                                          [ FAIL ] - result differs with reference:
2019-10-13 11:16:09 00910_decimal_group_array_crash_3783:                                   [ FAIL ] - result differs with reference:
2019-10-13 11:16:11 00047_stored_aggregates_complex:                                        [ FAIL ] - result differs with reference:
2019-10-13 11:16:55 00963_achimbab:                                                         [ FAIL ] - result differs with reference:
2019-10-13 11:16:56 00411_long_accurate_number_comparison_float:                            [ FAIL ] - return code 255
2019-10-13 11:17:27 00500_point_in_polygon:                                                 [ FAIL ] - return code 46
2019-10-13 11:17:43 00974_query_profiler:                                                   [ FAIL ] - result differs with reference:
2019-10-13 11:18:37 00647_histogram:                                                        [ FAIL ] - result differs with reference:
2019-10-13 11:18:56 00500_point_in_polygon_bug:                                             [ FAIL ] - return code 46
2019-10-13 11:19:56 00232_format_readable_size:                                             [ FAIL ] - result differs with reference:
2019-10-13 11:20:00 00500_point_in_polygon_bug_2:                                           [ FAIL ] - return code 46
2019-10-13 11:21:18 00438_bit_rotate:                                                       [ FAIL ] - result differs with reference:
2019-10-13 11:21:35 00500_point_in_polygon_bug_3_linestring_rotation_precision:             [ FAIL ] - return code 46
2019-10-13 11:22:11 00906_low_cardinality_rollup:                                           [ FAIL ] - result differs with reference:
2019-10-13 11:22:22 00804_rollup_with_having:                                               [ FAIL ] - result differs with reference:
2019-10-13 11:24:02 00925_zookeeper_empty_replicated_merge_tree_optimize_final:             [ FAIL ] - return code 86
2019-10-13 11:24:08 00929_multi_match_edit_distance:                                        [ FAIL ] - return code 48
2019-10-13 11:24:24 00273_quantiles:                                                        [ FAIL ] - result differs with reference:
2019-10-13 11:24:59 00161_rounding_functions:                                               [ FAIL ] - result differs with reference:
```

- ### build variants work fine (tested shared build, static build, sanitize builds). Packaging scripts work fine. Performance tests work fine.

- ### stacktrace doesn't work, always getting `<Empty trace>`

**Comment by alexey-milovidov** [comment]
Related: https://github.com/ClickHouse/ClickHouse/issues/7302

**Comment by alexey-milovidov** [comment]
> gcc bugs

So, how did you build it? With newer version of gcc or with clang?

**Comment by amosbird** [comment]
> So, how did you build it? 

by blacklisting those functions and disabling unneeded features (capnp). I've already tested with gcc 8.3, 9.1, 9.2. I tried clang (ubsan build) without reverting the source changes. I'll try a full build with clang.

**Comment by amosbird** [comment]
Clang-9 builds fine, however, linking statically with external icu fails, same in https://github.com/ClickHouse/ClickHouse/issues/6460#issuecomment-536404533

**Pull request merged**
