### PR TITLE
Fix logical error from write-though cache from stress test

### LINKED ISSUE #40748: Logical error: File segment completion can be done only by downloader
https://s3.amazonaws.com/clickhouse-test-reports/0/7ce0afc0df38d999cacd4f036623a9ca0cc37a59/stress_test__address_.html

```
/var/log/clickhouse-server/clickhouse-server.err.log:2022.08.29 13:01:54.012908 [ 54477 ] {86af3f9a-abb3-4633-a4f2-9cdd1bdb2bd2::201403_5_21_1} <Fatal> : Logical error: 'File segment completion can be done only by downloader. (CallerId: None:54477, downloader id: '.
/var/log/clickhouse-server/clickhouse-server.err.log:2022.08.29 13:01:54.013410 [ 54855 ] {} <Fatal> BaseDaemon: ########################################
/var/log/clickhouse-server/clickhouse-server.err.log:2022.08.29 13:01:54.013449 [ 54855 ] {} <Fatal> BaseDaemon: (version 22.9.1.1 (official build), build id: D7D11DA29E4F6C3D7B41FF2C414FC50290922F79) (from thread 54477) (query_id: 86af3f9a-abb3-4633-a4f2-9cdd1bdb2bd2::201403_5_21_1) (query: ) Received signal Aborted (6)
/var/log/clickhouse-server/clickhouse-server.err.log:2022.08.29 13:01:54.013474 [ 54855 ] {} <Fatal> BaseDaemon: 
/var/log/clickhouse-server/clickhouse-server.err.log:2022.08.29 13:01:54.013508 [ 54855 ] {} <Fatal> BaseDaemon: Stack trace: 0x7effea96400b 0x7effea943859 0xdb37081 0xdb375bb 0xdd59f23 0x2c642b2c 0x2c64c55c 0x2c64cb62 0x2d9ec835 0x2d9ebef8 0x3199f76e 0x31cf2c28 0x31d0d9b1 0x31d0e952 0x31f88770 0x31aded87 0x31af292b 0x31ae5919 0x31ae4cfa 0x32235aab 0x31b0f008 0x31b126df 0xdc9c82d 0xdca2d6d 0xdc96fed 0xdc9f2a2 0x7effeab1b609 0x7effeaa40133
/var/log/clickhouse-server/clickhouse-server.err.log:2022.08.29 13:01:54.013541 [ 54855 ] {} <Fatal> BaseDaemon: 3. raise in ?
/var/log/clickhouse-server/clickhouse-server.err.log:2022.08.29 13:01:54.013557 [ 54855 ] {} <Fatal> BaseDaemon: 4. abort in ?
/var/log/clickhouse-server/clickhouse-server.err.log:2022.08.29 13:01:54.079498 [ 54855 ] {} <Fatal> BaseDaemon: 5. ./build_docker/../src/Common/Exception.cpp:40: DB::abortOnFailedAssertion(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2022.08.29 13:01:54.146018 [ 54855 ] {} <Fatal> BaseDaemon: 6.1. inlined from ./build_docker/../src/Common/Exception.cpp:63: DB::handle_error_code(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool, std::__1::vector<void*, std::__1::allocator<void*> > const&)
/var/log/clickhouse-server/clickhouse-server.err.log:2022.08.29 13:01:54.146067 [ 54855 ] {} <Fatal> BaseDaemon: 6. ./build_docker/../src/Common/Exception.cpp:70: DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2022.08.29 13:01:54.287529 [ 54855 ] {} <Fatal> BaseDaemon: 7.1. inlined from ../contrib/libcxx/include/string:1445: std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::__is_long() const
/var/log/clickhouse-server/clickhouse-server.err.log:2022.08.29 13:01:54.287573 [ 54855 ] {} <Fatal> BaseDaemon: 7.2. inlined from ../contrib/libcxx/include/string:2231: ~basic_string
/var/log/clickhouse-server/clickhouse-server.err.log:2022.08.29 13:01:54.287590 [ 54855 ] {} <Fatal> BaseDaemon: 7. ../src/Common/Exception.h:37: DB::Exception::Exception<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&>(int, fmt::v8::basic_format_string<char, fmt::v8::type_identity<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&>::type, fmt::v8::type_identity<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&>::type>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&) in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2022.08.29 13:01:54.328706 [ 54855 ] {} <Fatal> BaseDaemon: 8. ./build_docker/../src/Common/FileSegment.cpp:444: DB::FileSegment::completeWithState(DB::FileSegment::State) in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2022.08.29 13:01:54.373594 [ 54855 ] {} <Fatal> BaseDaemon: 9. ./build_docker/../src/Common/FileSegment.cpp:0: DB::FileSegmentRangeWriter::completeFileSegment(DB::FileSegment&) in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2022.08.29 13:01:54.398419 [ 54855 ] {} <Fatal> BaseDaemon: 10. ./build_docker/../src/Common/FileSegment.cpp:0: DB::FileSegmentRangeWriter::write(char const*, unsigned long, unsigned long, bool) in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2022.08.29 13:01:54.410849 [ 54855 ] {} <Fatal> BaseDaemon: 11. ./build_docker/../src/Disks/IO/CachedOnDiskWriteBufferFromFile.cpp:92: DB::CachedOnDiskWriteBufferFromFile::cacheData(char*, unsigned long) in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2022.08.29 13:01:54.428091 [ 54855 ] {} <Fatal> BaseDaemon: 12. ./build_docker/../src/Disks/IO/CachedOnDiskWriteBufferFromFile.cpp:74: DB::CachedOnDiskWriteBufferFromFile::nextImpl() in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2022.08.29 13:01:54.627928 [ 54855 ] {} <Fatal> BaseDaemon: 13.1. inlined from ../src/IO/BufferBase.h:39: DB::BufferBase::Buffer::begin() const
/var/log/clickhouse-server/clickhouse-server.err.log:2022.08.29 13:01:54.627977 [ 54855 ] {} <Fatal> BaseDaemon: 13.2. inlined from ../src/IO/WriteBuffer.h:60: DB::WriteBuffer::next()
/var/log/clickhouse-server/clickhouse-server.err.log:2022.08.29 13:01:54.627993 [ 54855 ] {} <Fatal> BaseDaemon: 13. ../src/IO/HashingWriteBuffer.h:64: DB::HashingWriteBuffer::nextImpl() in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2022.08.29 13:01:54.667716 [ 54855 ] {} <Fatal> BaseDaemon: 14.1. inlined from ../src/IO/BufferBase.h:39: DB::BufferBase::Buffer::begin() const
/var/log/clickhouse-server/clickhouse-server.err.log:2022.08.29 13:01:54.667760 [ 54855 ] {} <Fatal> BaseDaemon: 14.2. inlined from ../src/IO/WriteBuffer.h:60: DB::WriteBuffer::next()
/var/log/clickhouse-server/clickhouse-server.err.log:2022.08.29 13:01:54.667780 [ 54855 ] {} <Fatal> BaseDaemon: 14. ./build_docker/../src/Storages/MergeTree/MergeTreeDataPartWriterOnDisk.cpp:18: DB::MergeTreeDataPartWriterOnDisk::Stream::preFinalize() in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2022.08.29 13:01:54.747603 [ 54855 ] {} <Fatal> BaseDaemon: 15.1. inlined from ../contrib/libcxx/include/__memory/unique_ptr.h:284: std::__1::unique_ptr<DB::MergeTreeDataPartWriterOnDisk::Stream, std::__1::default_delete<DB::MergeTreeDataPartWriterOnDisk::Stream> >::operator->() const
/var/log/clickhouse-server/clickhouse-server.err.log:2022.08.29 13:01:54.747655 [ 54855 ] {} <Fatal> BaseDaemon: 15. ./build_docker/../src/Storages/MergeTree/MergeTreeDataPartWriterWide.cpp:563: DB::MergeTreeDataPartWriterWide::fillDataChecksums(DB::MergeTreeDataPartChecksums&) in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2022.08.29 13:01:54.829605 [ 54855 ] {} <Fatal> BaseDaemon: 16. ./build_docker/../src/Storages/MergeTree/MergeTreeDataPartWriterWide.cpp:601: DB::MergeTreeDataPartWriterWide::fillChecksums(DB::MergeTreeDataPartChecksums&) in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2022.08.29 13:01:54.879661 [ 54855 ] {} <Fatal> BaseDaemon: 17. ./build_docker/../src/Storages/MergeTree/MergedColumnOnlyOutputStream.cpp:0: DB::MergedColumnOnlyOutputStream::fillChecksums(std::__1::shared_ptr<DB::IMergeTreeDataPart>&, DB::MergeTreeDataPartChecksums&) in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2022.08.29 13:01:55.126134 [ 54855 ] {} <Fatal> BaseDaemon: 18.1. inlined from ../contrib/libcxx/include/__memory/shared_ptr.h:816: std::__1::shared_ptr<DB::MergeTask::GlobalRuntimeContext>::operator->() const
/var/log/clickhouse-server/clickhouse-server.err.log:2022.08.29 13:01:55.126178 [ 54855 ] {} <Fatal> BaseDaemon: 18. ./build_docker/../src/Storages/MergeTree/MergeTask.cpp:544: DB::MergeTask::VerticalMergeStage::finalizeVerticalMergeForOneColumn() const in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2022.08.29 13:01:55.425339 [ 54855 ] {} <Fatal> BaseDaemon: 19.1. inlined from ./build_docker/../src/Storages/MergeTree/MergeTask.cpp:0: DB::MergeTask::VerticalMergeStage::executeVerticalMergeForAllColumns() const
/var/log/clickhouse-server/clickhouse-server.err.log:2022.08.29 13:01:55.425397 [ 54855 ] {} <Fatal> BaseDaemon: 19.2. inlined from ../src/Storages/MergeTree/MergeTask.h:318: DB::MergeTask::VerticalMergeStage::subtasks::'lambda0'()::operator()() const
/var/log/clickhouse-server/clickhouse-server.err.log:2022.08.29 13:01:55.425430 [ 54855 ] {} <Fatal> BaseDaemon: 19.3. inlined from ../contrib/libcxx/include/type_traits:3640: decltype(static_cast<DB::MergeTask::VerticalMergeStage::subtasks::'lambda0'()&>(fp)()) std::__1::__invoke<DB::MergeTask::VerticalMergeStage::subtasks::'lambda0'()&>(DB::MergeTask::VerticalMergeStage::subtasks::'lambda0'()&)
/var/log/clickhouse-server/clickhouse-server.err.log:2022.08.29 13:01:55.425459 [ 54855 ] {} <Fatal> BaseDaemon: 19.4. inlined from ../contrib/libcxx/include/__functional/invoke.h:30: bool std::__1::__invoke_void_return_wrapper<bool, false>::__call<DB::MergeTask::VerticalMergeStage::subtasks::'lambda0'()&>(DB::MergeTask::VerticalMergeStage::subtasks::'lambda0'()&)
/var/log/clickhouse-server/clickhouse-server.err.log:2022.08.29 13:01:55.425486 [ 54855 ] {} <Fatal> BaseDaemon: 19.5. inlined from ../contrib/libcxx/include/__functional/function.h:230: std::__1::__function::__default_alloc_func<DB::MergeTask::VerticalMergeStage::subtasks::'lambda0'(), bool ()>::operator()()
/var/log/clickhouse-server/clickhouse-server.err.log:2022.08.29 13:01:55.425511 [ 54855 ] {} <Fatal> BaseDaemon: 19. ../contrib/libcxx/include/__functional/function.h:711: bool std::__1::__function::__policy_invoker<bool ()>::__call_impl<std::__1::__function::__default_alloc_func<DB::MergeTask::VerticalMergeStage::subtasks::'lambda0'(), bool ()> >(std::__1::__function::__policy_storage const*) in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2022.08.29 13:01:55.680245 [ 54855 ] {} <Fatal> BaseDaemon: 20.1. inlined from ../contrib/libcxx/include/__functional/function.h:843: std::__1::__function::__policy_func<bool ()>::operator()() const
/var/log/clickhouse-server/clickhouse-server.err.log:2022.08.29 13:01:55.680292 [ 54855 ] {} <Fatal> BaseDaemon: 20.2. inlined from ../contrib/libcxx/include/__functional/function.h:1184: std::__1::function<bool ()>::operator()() const
/var/log/clickhouse-server/clickhouse-server.err.log:2022.08.29 13:01:55.680308 [ 54855 ] {} <Fatal> BaseDaemon: 20. ./build_docker/../src/Storages/MergeTree/MergeTask.cpp:709: DB::MergeTask::VerticalMergeStage::execute() in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2022.08.29 13:01:55.944401 [ 54855 ] {} <Fatal> BaseDaemon: 21. ./build_docker/../src/Storages/MergeTree/MergeTask.cpp:0: DB::MergeTask::execute() in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2022.08.29 13:01:55.968796 [ 54855 ] {} <Fatal> BaseDaemon: 22. ./build_docker/../src/Storages/MergeTree/MergePlainMergeTreeTask.cpp:0: DB::MergePlainMergeTreeTask::executeStep() in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2022.08.29 13:01:56.002517 [ 54855 ] {} <Fatal> BaseDaemon: 23. ./build_docker/../src/Storages/MergeTree/MergeTreeBackgroundExecutor.cpp:157: DB::MergeTreeBackgroundExecutor<DB::MergeMutateRuntimeQueue>::routine(std::__1::shared_ptr<DB::TaskRuntimeData>) in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2022.08.29 13:01:56.038740 [ 54855 ] {} <Fatal> BaseDaemon: 24. ./build_docker/../src/Storages/MergeTree/MergeTreeBackgroundExecutor.cpp:0: DB::MergeTreeBackgroundExecutor<DB::MergeMutateRuntimeQueue>::threadFunction() in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2022.08.29 13:01:56.074525 [ 54855 ] {} <Fatal> BaseDaemon: 25. ../contrib/libcxx/include/__functional/function.h:0: ThreadPoolImpl<ThreadFromGlobalPool>::worker(std::__1::__list_iterator<ThreadFromGlobalPool, void*>) in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2022.08.29 13:01:56.114416 [ 54855 ] {} <Fatal> BaseDaemon: 26.1. inlined from ../src/Common/ThreadPool.h:188: operator()
/var/log/clickhouse-server/clickhouse-server.err.log:2022.08.29 13:01:56.114444 [ 54855 ] {} <Fatal> BaseDaemon: 26. ../contrib/libcxx/include/type_traits:3640: decltype(static_cast<void>(fp)()) std::__1::__invoke<ThreadFromGlobalPool::ThreadFromGlobalPool<void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>(void&&)::'lambda'()&>(void&&) in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2022.08.29 13:01:56.146102 [ 54855 ] {} <Fatal> BaseDaemon: 27. ../contrib/libcxx/include/__functional/function.h:0: ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2022.08.29 13:01:56.185335 [ 54855 ] {} <Fatal> BaseDaemon: 28.1. inlined from ../contrib/libcxx/include/__memory/unique_ptr.h:312: std::__1::unique_ptr<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>, std::__1::default_delete<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()> > >::reset(std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>*)
/var/log/clickhouse-server/clickhouse-server.err.log:2022.08.29 13:01:56.185380 [ 54855 ] {} <Fatal> BaseDaemon: 28.2. inlined from ../contrib/libcxx/include/__memory/unique_ptr.h:269: ~unique_ptr
/var/log/clickhouse-server/clickhouse-server.err.log:2022.08.29 13:01:56.185401 [ 54855 ] {} <Fatal> BaseDaemon: 28. ../contrib/libcxx/include/thread:295: void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()> >(void*) in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2022.08.29 13:01:56.185421 [ 54855 ] {} <Fatal> BaseDaemon: 29. ? in ?
/var/log/clickhouse-server/clickhouse-server.err.log:2022.08.29 13:01:56.185435 [ 54855 ] {} <Fatal> BaseDaemon: 30. clone in ?
/var/log/clickhouse-server/clickhouse-server.err.log:2022.08.29 13:01:56.965472 [ 54855 ] {} <Fatal> BaseDaemon: Integrity check of the executable successfully passed (checksum: 56C8838663E541D063B22CD67D009AAD)
/var/log/clickhouse-server/clickhouse-server.err.log:2022.08.29 13:02:14.265112 [ 54365 ] {} <Fatal> Application: Child process was terminated by signal 6.
```

### PR DESCRIPTION
**Pull request by kssenii**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in official stable or prestable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix logical error in write-through cache "File segment completion can be done only by downloader". Closes https://github.com/ClickHouse/ClickHouse/issues/40748.

### CODE REVIEW

**Review by vdimir — APPROVED** [review]
LGTM

Is it tricky to reproduce the failure in tests?

**Comment by kssenii** [comment]
> Is it tricky to reproduce the failure in tests?

Yes.

**Comment by alesapin** [comment]
Not so tricky:
https://s3.amazonaws.com/clickhouse-test-reports/36837/e0fab1fa118814f1a83b9bac79135a191441fa88/stress_test__address_.html
https://s3.amazonaws.com/clickhouse-test-reports/36837/e0fab1fa118814f1a83b9bac79135a191441fa88/stress_test__debug_.html
https://s3.amazonaws.com/clickhouse-test-reports/36837/e0fab1fa118814f1a83b9bac79135a191441fa88/stress_test__memory_.html
https://s3.amazonaws.com/clickhouse-test-reports/36837/e0fab1fa118814f1a83b9bac79135a191441fa88/stress_test__thread_.html
https://s3.amazonaws.com/clickhouse-test-reports/36837/e0fab1fa118814f1a83b9bac79135a191441fa88/stress_test__undefined_.html

**Comment by kssenii** [comment]
I meant tricky to make a stateless test which will at once reproduce without stress test.

**Comment by kssenii** [comment]
> Stateless tests (memory) [3/3] — Tests are not finished, fail: 3

Annoy
```
Saved preprocessed configuration to '/var/lib/clickhouse/preprocessed_configs/users.xml'.
==640==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x44d20d3d in void Annoy::(anonymous namespace)::two_means<float, Annoy::Kiss64Random, Annoy::Euclidean, Annoy::Minkowski::Node<unsigned long, float> >(std::__1::vector<Annoy::Minkowski::Node<unsigned long, float>*, std::__1::allocator<Annoy::Minkowski::Node<unsigned long, float>*> > const&, int, Annoy::Kiss64Random&, bool, Annoy::Minkowski::Node<unsigned long, float>*, Annoy::Minkowski::Node<unsigned long, float>*) build_docker/../contrib/annoy/src/annoylib.h:398:9
    #1 0x44d20d3d in void Annoy::Euclidean::create_split<unsigned long, float, Annoy::Kiss64Random>(std::__1::vector<Annoy::Minkowski::Node<unsigned long, float>*, std::__1::allocator<Annoy::Minkowski::Node<unsigned long, float>*> > const&, int, unsigned long, Annoy::Kiss64Random&, Annoy::Minkowski::Node<unsigned long, float>*) build_docker/../contrib/annoy/src/annoylib.h:773:5
```

**Comment by kssenii** [comment]
In last commit several checks are not finished and are not restarted, but last commit was just a merge with master + previous commit all checks are ok. So I will merge.

**Pull request merged**
