### PR TITLE
Cherry pick #59349 to 23.12: Add setting update_insert_deduplication_token_in_dependent_materialized_views to settings changes history

### PR DESCRIPTION
**Pull request by robot-clickhouse-ci-1**
Original pull-request #59349

This pull-request is a first step of an automated backporting.
It contains changes similar to calling `git cherry-pick` locally.
If you intend to continue backporting the changes, then resolve all conflicts if any.
Otherwise, if you do not want to backport them, then just close this pull-request.

The check results does not matter at this step - you can safely ignore them.

### Note

This pull-request will be merged automatically. Please, **do not merge it manually** (but if you accidentally did, nothing bad will happen).

#### If the PR was manually reopened after being closed

If this PR is stuck (i.e. not automatically merged after one day), check https://github.com/ClickHouse/ClickHouse/pull/59349 for `pr-backports-created` *label* and delete it.

Manually merging will do nothing. The `pr-backports-created` *label* prevents the original PR https://github.com/ClickHouse/ClickHouse/pull/59349 from being processed.

#### If the conflicts were resolved in a wrong way

If this cherry-pick PR is completely screwed by a wrong conflicts resolution, and you want to recreate it:

- delete the `pr-cherrypick` label from the PR
- delete this branch from the repository

You also need to check the original PR https://github.com/ClickHouse/ClickHouse/pull/59349 for `pr-backports-created`, and delete if it's presented there

### CODE REVIEW

**Comment by robot-ch-test-poll1** [comment]
Dear @KochetovNicolai, @kitaisreal, the PR is not updated for 1d24h1m25s. Please, either resolve the conflicts, or close it to finish the backport process of #59349

**Comment by robot-clickhouse-ci-1** [comment]
Dear @KochetovNicolai, @kitaisreal, the PR is not updated for 1d24h2m22s. Please, either resolve the conflicts, or close it to finish the backport process of #59349

**Comment by robot-ch-test-poll1** [comment]
Dear @KochetovNicolai, @kitaisreal, the PR is not updated for 1d24h57m48s. Please, either resolve the conflicts, or close it to finish the backport process of #59349

**Comment by robot-ch-test-poll** [comment]
Dear @KochetovNicolai, @kitaisreal, the PR is not updated for 1d24h59m55s. Please, either resolve the conflicts, or close it to finish the backport process of #59349

**Comment by robot-ch-test-poll** [comment]
Dear @KochetovNicolai, @kitaisreal, the PR is not updated for 1d24h59m48s. Please, either resolve the conflicts, or close it to finish the backport process of #59349

**Comment by robot-ch-test-poll2** [comment]
Dear @KochetovNicolai, @kitaisreal, the PR is not updated for 1d25h0m1s. Please, either resolve the conflicts, or close it to finish the backport process of #59349

**Comment by robot-ch-test-poll3** [comment]
Dear @KochetovNicolai, @kitaisreal, the PR is not updated for 1d24h59m55s. Please, either resolve the conflicts, or close it to finish the backport process of #59349

**Comment by robot-clickhouse** [comment]
Dear @KochetovNicolai, @kitaisreal, the PR is not updated for 1d24h0m47s. Please, either resolve the conflicts, or close it to finish the backport process of #59349

**Comment by robot-ch-test-poll3** [comment]
Dear @KochetovNicolai, @kitaisreal, the PR is not updated for 1d25h1m48s. Please, either resolve the conflicts, or close it to finish the backport process of #59349

**Comment by robot-clickhouse** [comment]
Dear @KochetovNicolai, @kitaisreal, the PR is not updated for 1d24h58m52s. Please, either resolve the conflicts, or close it to finish the backport process of #59349

**Comment by robot-clickhouse-ci-1** [comment]
Dear @KochetovNicolai, @kitaisreal, the PR is not updated for 1d24h58m39s. Please, either resolve the conflicts, or close it to finish the backport process of #59349

**Comment by robot-clickhouse** [comment]
Dear @KochetovNicolai, @kitaisreal, the PR is not updated for 1d24h59m49s. Please, either resolve the conflicts, or close it to finish the backport process of #59349

**Comment by robot-clickhouse** [comment]
Dear @KochetovNicolai, @kitaisreal, the PR is not updated for 1d24h0m2s. Please, either resolve the conflicts, or close it to finish the backport process of #59349

**Comment by robot-clickhouse-ci-1** [comment]
Dear @KochetovNicolai, @kitaisreal, the PR is not updated for 1d24h0m59s. Please, either resolve the conflicts, or close it to finish the backport process of #59349

**Comment by robot-ch-test-poll** [comment]
Dear @KochetovNicolai, @kitaisreal, the PR is not updated for 1d24h59m57s. Please, either resolve the conflicts, or close it to finish the backport process of #59349

**Comment by robot-clickhouse-ci-2** [comment]
Dear @KochetovNicolai, @kitaisreal, the PR is not updated for 1d25h0m49s. Please, either resolve the conflicts, or close it to finish the backport process of #59349

**Comment by robot-clickhouse-ci-2** [comment]
Dear @KochetovNicolai, @kitaisreal, the PR is not updated for 1d25h21m53s. Please, either resolve the conflicts, or close it to finish the backport process of #59349

**Comment by robot-ch-test-poll** [comment]
Dear @KochetovNicolai, @kitaisreal, the PR is not updated for 1d24h43m10s. Please, either resolve the conflicts, or close it to finish the backport process of #59349

**Comment by robot-ch-test-poll1** [comment]
Dear @KochetovNicolai, @kitaisreal, the PR is not updated for 1d24h25m48s. Please, either resolve the conflicts, or close it to finish the backport process of #59349

**Comment by robot-ch-test-poll4** [comment]
Dear @KochetovNicolai, @kitaisreal, the PR is not updated for 1d24h27m17s. Please, either resolve the conflicts, or close it to finish the backport process of #59349

**Pull request closed without merging**
