### PR TITLE
Fix ASTRenameQuery::clone

### PR DESCRIPTION
**Pull request by vdimir**
### Changelog category (leave one):

- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
...

### CODE REVIEW

**Comment by robot-ch-test-poll** [comment]
*This is an automated comment for commit 792bada386b88abb88d400805b3ae92898b6930b with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/61013/792bada386b88abb88d400805b3ae92898b6930b/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

**Review by Algunenano — COMMENTED** [review]
Duplicated with https://github.com/ClickHouse/ClickHouse/pull/60825. I like the extra tests, not sure about the code changes. WDYT?

**Comment by vdimir** [comment]
> Duplicated with https://github.com/ClickHouse/ClickHouse/pull/60825. I like the extra tests, not sure about the code changes. WDYT?

I can try to rebase after mentioned PR is merged and keep tests

**Comment by alexey-milovidov** [comment]
@vdimir, I didn't have time to check that PR, and neither did @devcrafter, please go ahead with yours.

**Comment by vdimir** [comment]
`cloneChildren` doesn't work because the list of `ASTRenameQuery`'s children is not maintained in correspondence with `elements`. Trying to fix...

**Review by Algunenano — APPROVED** [review]

**Pull request merged**
