### PR TITLE
Something is strange with the test about refreshable materialized views

### PR DESCRIPTION
**Pull request by alexey-milovidov**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

https://s3.amazonaws.com/clickhouse-test-reports/0/32d3ebf799f6ad34e4221feaf1322567484f82b2/stateless_tests__azure__asan__[3_3].html

https://s3.amazonaws.com/clickhouse-test-reports/65751/122c3ce1adb44ad6101f281c82b43269f015f099/stateless_tests__tsan__s3_storage__[3_3].html

Also, @al13n321 forgot to write a comment before "disabling log_comment", and I didn't understand and removed it.

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-ch-test-poll3** [comment]
*This is an automated comment for commit fab0bb6aa41c9deccb69666ae0d22559c0784121 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/66816/fab0bb6aa41c9deccb69666ae0d22559c0784121/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/66792/42ba3229b5484ebe29f4191cd5672433ba1f6588/docs_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Comment by alexey-milovidov** [comment]
Need to fix b.s. in RocksDB: https://s3.amazonaws.com/clickhouse-test-reports/66816/fab0bb6aa41c9deccb69666ae0d22559c0784121/stateless_tests__msan__[2_4].html

**Comment by alexey-milovidov** [comment]
Needs #66838

**Comment by alexey-milovidov** [comment]
Needs https://github.com/ClickHouse/ClickHouse/pull/66906

**Pull request merged**
