### PR TITLE
comment ssl file paths

### LINKED ISSUE #35552: 22.3 CertificateReloader comlains about missing files during start
```
<Debug> ConfigReloader: Loading config '/etc/clickhouse-server/config.xml'
<Debug> ConfigReloader: Loaded config '/etc/clickhouse-server/config.xml', performing update on configuration
<Information> Application: Setting max_server_memory_usage was set to 21.09 GiB (23.44 GiB available * 0.90 max_server_memory_usage_to_ram_ratio)
<Error> CertificateReloader: Cannot obtain modification time for certificate file /etc/clickhouse-server/server.crt, skipping update. errno: 2, strerror: No such file or directory
<Error> CertificateReloader: Cannot obtain modification time for key file /etc/clickhouse-server/server.key, skipping update. errno: 2, strerror: No such file or directory
<Debug> CertificateReloader: Initializing certificate reloader.
<Error> CertificateReloader: Poco::Exception. Code: 1000, e.code() = 0, SSL context exception: Error loading private key from file /etc/clickhouse-server/server.key: error:02000002:system library:OPENSSL_internal:No such file or directory (version 22.2.3.1)
```

I think need to comment by default

```
            <certificateFile>/etc/clickhouse-server/server.crt</certificateFile>
            <privateKeyFile>/etc/clickhouse-server/server.key</privateKeyFile>
```

### PR DESCRIPTION
**Pull request by ppecheux**
Changelog category (leave one):

- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
comment ssl file paths

> Information about CI checks: https://clickhouse.tech/docs/en/development/continuous-integration/

closes #35552

### CODE REVIEW

**Comment by nickitat** [comment]
I let myself move the "closes xxx" clause into the description, hope you wouldn't mind.

**Comment by den-crane** [comment]
it could be more complicated

```
 find . -type f -name '*config*'  -exec grep -H "/etc/clickhouse-server/server.crt" {} \;
./tests/integration/test_postgresql_protocol/configs/config.xml:             <!-- openssl req -subj "/CN=localhost" -new -newkey rsa:2048 -days 365 -nodes -x509 -keyout /etc/clickhouse-server/server.key -out /etc/clickhouse-server/server.crt -->
./tests/integration/test_postgresql_protocol/configs/config.xml:             <certificateFile>/etc/clickhouse-server/server.crt</certificateFile>
./tests/integration/test_config_yaml_main/configs/config.yaml:    certificateFile: /etc/clickhouse-server/server.crt
./tests/integration/test_https_replication/configs/config.xml:            <certificateFile>/etc/clickhouse-server/server.crt</certificateFile>
./tests/integration/test_mysql_protocol/configs/config.xml:            <!-- openssl req -subj "/CN=localhost" -new -newkey rsa:2048 -days 365 -nodes -x509 -keyout /etc/clickhouse-server/server.key -out /etc/clickhouse-server/server.crt -->
./tests/integration/test_mysql_protocol/configs/config.xml:            <certificateFile>/etc/clickhouse-server/server.crt</certificateFile>
./tests/integration/test_config_xml_full/configs/config.xml:            <!-- openssl req -subj "/CN=localhost" -new -newkey rsa:2048 -days 365 -nodes -x509 -keyout /etc/clickhouse-server/server.key -out /etc/clickhouse-server/server.crt -->
./tests/integration/test_config_xml_full/configs/config.xml:            <certificateFile>/etc/clickhouse-server/server.crt</certificateFile>
./tests/integration/test_config_corresponding_root/configs/config.xml:            <!-- openssl req -subj "/CN=localhost" -new -newkey rsa:2048 -days 365 -nodes -x509 -keyout /etc/clickhouse-server/server.key -out /etc/clickhouse-server/server.crt -->
./tests/integration/test_config_corresponding_root/configs/config.xml:            <certificateFile>/etc/clickhouse-server/server.crt</certificateFile>
./tests/integration/test_config_xml_main/configs/config.xml:            <certificateFile>/etc/clickhouse-server/server.crt</certificateFile>
./tests/integration/test_config_xml_yaml_mix/configs/config.xml:            <certificateFile>/etc/clickhouse-server/server.crt</certificateFile>
./tests/integration/test_config_yaml_full/configs/config.yaml:    certificateFile: /etc/clickhouse-server/server.crt
./programs/server/config.yaml.example:        # openssl req -subj "/CN=localhost" -new -newkey rsa:2048 -days 365 -nodes -x509 -keyout /etc/clickhouse-server/server.key -out /etc/clickhouse-server/server.crt
./programs/server/config.yaml.example:        certificateFile: /etc/clickhouse-server/server.crt
./programs/server/config.xml:            <!-- openssl req -subj "/CN=localhost" -new -newkey rsa:2048 -days 365 -nodes -x509 -keyout /etc/clickhouse-server/server.key -out /etc/clickhouse-server/server.crt -->
./programs/server/config.xml:            <certificateFile>/etc/clickhouse-server/server.crt</certificateFile>
./programs/keeper/keeper_config.xml:            <!-- openssl req -subj "/CN=localhost" -new -newkey rsa:2048 -days 365 -nodes -x509 -keyout /etc/clickhouse-server/server.key -out /etc/clickhouse-server/server.crt -->
```

**Comment by nickitat** [comment]
agree with den, let's comment out also the entry in `./programs/server/config.yaml.example`, configs under `tests/` should be left untouched IMO.

**Comment by nickitat** [comment]
@ppecheux sorry for bothering you, do you plan to finish this pr?

**Pull request closed without merging**
