### PR TITLE
DDL dictionaries Range fix

### LINKED ISSUE #7899: Dictionary DDL does not support DateTime ranges
Experimenting with dictionary DDL and noted that it doesn't support DateTime or non-Date numeric types (assume Date is UInt16) ranges in RANGE_HASHED layout.

Version: 19.18.1.1721 (testing)

Test:

Grab tests from 0_stateless/01018_ddl_dictionaries_special.sql. Modify Date columns for range hashed to DateTime:

```
DROP TABLE database_for_dict.table_for_dict;
CREATE TABLE database_for_dict.table_for_dict
(
  CountryID UInt64,
  StartDate DateTime,
  EndDate DateTime,
  Tax Float64
)
ENGINE = MergeTree()
ORDER BY CountryID;

INSERT INTO database_for_dict.table_for_dict VALUES(1, toDateTime('2019-05-05 00:00:00'), toDateTime('2019-05-20 23:59:59'), 0.33);
INSERT INTO database_for_dict.table_for_dict VALUES(1, toDateTime('2019-05-21 00:00:00'), toDateTime('2019-05-30 00:00:00'), 0.42);
INSERT INTO database_for_dict.table_for_dict VALUES(2, toDateTime('2019-05-21 00:00:00'), toDateTime('2019-05-30 00:00:00'), 0.46);

DROP DICTIONARY database_for_dict.dict1;
CREATE DICTIONARY database_for_dict.dict1
(
  CountryID UInt64,
  StartDate DateTime,
  EndDate DateTime,
  Tax Float64
)
PRIMARY KEY CountryID
SOURCE(CLICKHOUSE(HOST 'localhost' PORT 9000 USER 'default' TABLE 'table_for_dict' DB 'database_for_dict'))
LIFETIME(MIN 1 MAX 1000)
LAYOUT(RANGE_HASHED())
RANGE(MIN StartDate MAX EndDate);

SELECT dictGetFloat64('database_for_dict.dict1', 'Tax', toUInt64(1), toDateTime('2019-05-15 00:00:00'));
SELECT dictGetFloat64('database_for_dict.dict1', 'Tax', toUInt64(1), toDateTime('2019-05-29 00:00:00'));
SELECT dictGetFloat64('database_for_dict.dict1', 'Tax', toUInt64(2), toDateTime('2019-05-29 00:00:00'));
SELECT dictGetFloat64('database_for_dict.dict1', 'Tax', toUInt64(2), toDateTime('2019-05-31 00:00:00'));
```

Note will return 0/default for all columns instead of expected results as per Date variant of 0_stateless/01018_ddl_dictionaries_special.sql range_hashed.

### PR DESCRIPTION
**Pull request by alesapin**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Bug Fix

Changelog entry (up to few sentences, required except for Non-significant/Documentation categories):
Add ability to work with different types besides Date in RangeHashed external dictionary created from DDL query. Fixes https://github.com/ClickHouse/ClickHouse/issues/7899.

### CODE REVIEW

**Comment by alesapin** [comment]
We don't check consistency between types in table and dictionary even for ClickHouse source. So we can create a dictionary with `Date` types and table with `DateTime` types and get very confusing behavior.

**Comment by alesapin** [comment]
Fix is trivial, tests are OK (all failed are flaps).

**Comment by filimonov** [comment]
> We don't check consistency between types in table and dictionary even for ClickHouse source. So we can create a dictionary with `Date` types and table with `DateTime` types and get very confusing behavior.

Maybe that's also the reason of https://github.com/ClickHouse/ClickHouse/issues/8352

**Comment by vitlibar** [comment]
There is no need to backport it to 19.16 because 19.16 doesn't have dictionary DDL support.

**Pull request merged**
