### PR TITLE
`base64En/Decode64Url` --> `base64En/Decode64URL`

### PR DESCRIPTION
**Pull request by rschu1ze**
For consistency with the naming of [existing URL functions](https://clickhouse.com/docs/en/sql-reference/functions/url-functions), this PR renames `Url` to `URL` in `[try]Base64(En/De)codeUrl` functions.

I'll fix the changelog entry of #64991 which introduced these functions (they are not in any released version yet).

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by robot-ch-test-poll1** [comment]
*This is an automated comment for commit 643bfcfb8fd86a4e8736ca79c59ab8ef9ae4eb3c with description of existing statuses. It's updated for the latest CI running*

[❌ Click here](https://s3.amazonaws.com/clickhouse-test-reports/65760/643bfcfb8fd86a4e8736ca79c59ab8ef9ae4eb3c/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Style check</td><td>Runs a set of checks to keep the code style clean. If some of tests failed, see the related log from the report</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/65760/643bfcfb8fd86a4e8736ca79c59ab8ef9ae4eb3c/style_check.html">❌ failure</a></td></tr>
<tbody>
</table>

**Review by antaljanosbenjamin — APPROVED** [review]

**Comment by antaljanosbenjamin** [comment]
Please make sure this change also ends up on the `24.6` branch as it contains the original changes, but as far as I know we didn't make any releases of it. FYI @Algunenano

**Comment by rschu1ze** [comment]
`DocCheck` failed due to broken links.

I double-checked but could not find any broken links in this PR. Also, a local build of the docs (based on [clickhouse-docs](https://github.com/ClickHouse/clickhouse-docs)) was fine.

Will merge from `master` again.

**Comment by rschu1ze** [comment]
[This](https://github.com/ClickHouse/clickhouse-docs/commit/1be131601efcda133209ace016eec17b7a80ea7c) fixes (hopefully) the docs - that other commit is not included in the latest state.

Merging to get this one in before the release. The first batch of stateless tests was green, and the change is trivial.

**Pull request merged**
