### PR TITLE
Enable clang vtables optimization

### PR DESCRIPTION
**Pull request by kitaisreal**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Enable clang `-fstrict-vtable-pointers`, `-fwhole-program-vtables` compile options.

### CODE REVIEW

**Comment by qoega** [comment]
nice 👍 
```
2021-02-06 14:46:46 PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace.
2021-02-06 14:46:46 /lib/x86_64-linux-gnu/libLLVM-11.so.1(_ZN4llvm3sys15PrintStackTraceERNS_11raw_ostreamE+0x1f)[0x7f8fad13348f]
2021-02-06 14:46:46 /lib/x86_64-linux-gnu/libLLVM-11.so.1(_ZN4llvm3sys17RunSignalHandlersEv+0x50)[0x7f8fad1317f0]
2021-02-06 14:46:46 /lib/x86_64-linux-gnu/libLLVM-11.so.1(+0xaa6965)[0x7f8fad133965]
2021-02-06 14:46:46 /lib/x86_64-linux-gnu/libpthread.so.0(+0x153c0)[0x7f8fb16463c0]
2021-02-06 14:46:46 /lib/x86_64-linux-gnu/libLLVM-11.so.1(_ZNK4llvm10BasicBlock9getModuleEv+0x0)[0x7f8fad185060]
2021-02-06 14:46:46 /lib/x86_64-linux-gnu/libLLVM-11.so.1(+0x1835b86)[0x7f8fadec2b86]
2021-02-06 14:46:46 /lib/x86_64-linux-gnu/libLLVM-11.so.1(+0x182c62c)[0x7f8fadeb962c]
2021-02-06 14:46:46 /lib/x86_64-linux-gnu/libLLVM-11.so.1(_ZN4llvm22WholeProgramDevirtPass3runERNS_6ModuleERNS_15AnalysisManagerIS1_JEEE+0x90)[0x7f8fadeb7cb0]
2021-02-06 14:46:46 /lib/x86_64-linux-gnu/libLLVM-11.so.1(+0x2d58cbd)[0x7f8faf3e5cbd]
2021-02-06 14:46:46 /lib/x86_64-linux-gnu/libLLVM-11.so.1(_ZN4llvm11PassManagerINS_6ModuleENS_15AnalysisManagerIS1_JEEEJEE3runERS1_RS3_+0x4ee)[0x7f8fad26f60e]
2021-02-06 14:46:46 /lib/x86_64-linux-gnu/libLLVM-11.so.1(+0x1b20f45)[0x7f8fae1adf45]
2021-02-06 14:46:46 /lib/x86_64-linux-gnu/libLLVM-11.so.1(_ZN4llvm3lto11thinBackendERKNS0_6ConfigEjSt8functionIFSt10unique_ptrINS0_18NativeObjectStreamESt14default_deleteIS6_EEjEERNS_6ModuleERKNS_18ModuleSummaryIndexERKNS_9StringMapISt13unordered_setImSt4hashImESt8equal_toImESaImEENS_15MallocAllocatorEEERKNS_8DenseMapImPNS_18GlobalValueSummaryENS_12DenseMapInfoImEENS_6detail12DenseMapPairImSV_EEEERNS_9MapVectorINS_9StringRefENS_13BitcodeModuleENST_IS15_jNSW_IS15_EENSZ_IS15_jEEEESt6vectorISt4pairIS15_S16_ESaIS1C_EEEE+0x996)[0x7f8fae1afd36]
2021-02-06 14:46:46 /lib/x86_64-linux-gnu/libLLVM-11.so.1(+0x1b1d2e5)[0x7f8fae1aa2e5]
2021-02-06 14:46:46 /lib/x86_64-linux-gnu/libLLVM-11.so.1(+0x1b1ce52)[0x7f8fae1a9e52]
2021-02-06 14:46:46 /lib/x86_64-linux-gnu/libLLVM-11.so.1(+0xa56ecf)[0x7f8fad0e3ecf]
2021-02-06 14:46:46 /lib/x86_64-linux-gnu/libLLVM-11.so.1(+0xa3eea7)[0x7f8fad0cbea7]
2021-02-06 14:46:46 /lib/x86_64-linux-gnu/libpthread.so.0(+0x1247f)[0x7f8fb164347f]
2021-02-06 14:46:46 /lib/x86_64-linux-gnu/libLLVM-11.so.1(+0xa3ee40)[0x7f8fad0cbe40]
2021-02-06 14:46:46 /lib/x86_64-linux-gnu/libLLVM-11.so.1(+0xa56c9d)[0x7f8fad0e3c9d]
2021-02-06 14:46:46 /lib/x86_64-linux-gnu/libLLVM-11.so.1(+0xa5675e)[0x7f8fad0e375e]
2021-02-06 14:46:46 /lib/x86_64-linux-gnu/libstdc++.so.6(+0xd6d84)[0x7f8fac582d84]
2021-02-06 14:46:46 /lib/x86_64-linux-gnu/libpthread.so.0(+0x9609)[0x7f8fb163a609]
2021-02-06 14:46:46 /lib/x86_64-linux-gnu/libc.so.6(clone+0x43)[0x7f8fac272293]
2021-02-06 14:46:46 clang: error: unable to execute command: Segmentation fault (core dumped)
2021-02-06 14:46:46 clang: error: linker command failed due to signal (use -v to see invocation)
```

**Comment by alexey-milovidov** [comment]
> WholeProgramDevirtPass

At least it fails exactly where it's expected.

**Comment by alexey-milovidov** [comment]
Let's switch to llvm-12.

**Comment by alexey-milovidov** [comment]
Depends on #20495, #20499, #18205.

**Comment by alexey-milovidov** [comment]
@mergifyio update

**Review by alexey-milovidov — APPROVED** [review]

**Comment by amosbird** [comment]
Hmm, what do these optimizations improve?

**Comment by alexey-milovidov** [comment]
> -fstrict-vtable-pointers

> Enable optimizations based on the strict rules for overwriting polymorphic C++ objects, i.e. the vptr is invariant during an object’s lifetime. This enables better devirtualization. Turned off by default, because it is still experimental.

Good for loops with virtual calls.

> -fwhole-program-vtables

More devirtualization.

**Comment by alexey-milovidov** [comment]
This pull request is blocked by #30599.
And in general we need #30599.
Also makes sense to do #30598.

**Comment by alexey-milovidov** [comment]
@Mergifyio update

**Comment by alexey-milovidov** [comment]
This pull requests has been unblocked, now all builds succeed.

**Comment by alexey-milovidov** [comment]
For some reason, `reinterpret_as` queries become slower,
but I already observed that these queries are unstable in the performance test,
most likely it is unrelated.

And the overall change is less than 0.1%.

**Comment by alexey-milovidov** [comment]
Need to validate performance difference manually...

**Comment by alexey-milovidov** [comment]
Actually there is no reason how performance difference in `reinterpret_as` can be related.
Let's simply merge as this change is good from overall perspective...

**Pull request merged**
