### PR TITLE
Bump LLVM from 12 to 13

### PR DESCRIPTION
**Pull request by rschu1ze**
This upgrades LLVM from an old version to a slightly less old version. We are not going immediately to the most recent LLVM 15 because in that version the internal API changed and needs adjustment in ClickHouse, see https://github.com/ClickHouse/ClickHouse/pull/41519#issuecomment-1256033386.

The main achievement in this PR is that LLVM is now obtained from a true [fork of LLVM](https://github.com/ClickHouse/llvm-project) with minimal modifications (branch: "ClickHouse/releases/13.x", cf. [here](https://clickhouse.com/docs/en/development/contrib)) instead of a quite messy extracted source code upload with lots of modifications.

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by rschu1ze** [comment]
Update: Tests now look good, only the [ClickHouse Compatibility Check](https://s3.amazonaws.com/clickhouse-test-reports/41762/a5311fb9766dad4fd0e71d24cca4d24d913b7bc4/compatibility_check.html) fails. The problem is that after the LLVM upgrade, the ClickHouse binary expects symbols from glibc >= 2.27 whereas the minimum version should be 2.4. Readelf/nm/objdump couldn't resolve the libs containing these symbols, even in a Debug build. I am currently trying [linker map files](https://stackoverflow.com/questions/60990561/generate-map-file-with-clang-and-lld) to figure out the symbol users.

**Comment by rschu1ze** [comment]
It is not that llvm 13 suddenly started to use stuff from glibc 2.27. It is that the linker map file for llvm 12 shows that files base/glibc-compatibility/
- log2_data.cpp.o
- logf_data.cpp.o
- log2f_data.cpp.o
- pow_data.cpp.o
- powf_data.cpp.o
- exp_data.cpp.o
- exp2_data.cpp.o
are used to pull in symbols but that isn't the case for the llvm 13 build. Maybe something is wrong with the order of dependent libraries passed to the linker.

Interestingly, for both llvm 12 and llvm 13 builds, readelf shows all symbols from glibc (the too-recent-ones + all others) as "undefined". As far as I see, this means they are resolved at runtime, i.e. via dynamic linking. I didn't really expect that.

**Comment by rschu1ze** [comment]
Problem seems gone when applying https://github.com/ClickHouse/llvm/commit/778c297395b4a2dfd60e13969a0f9488bf2c16cf (which I forgot)

**Comment by rschu1ze** [comment]
@kitaisreal Would you like to have a look at this PR. Tests are still running but I expect them to be green.

Notes:
- Two small changes had to be made to the upstream 13.x branch: https://github.com/ClickHouse/llvm-project/pulls?q=is%3Apr+is%3Aclosed The diff of both PRs was already included in ClickHouse's LLVM 12.
- The embedded compiler is currently disabled when doing a shared library build (--> contrib/llvm-project-cmake/CMakeLists.txt, 1st line). In the existing LLVM 12 integration, the build option was ignored anyways, i.e. LLVM was build statically. It is generally possible to build a shared library but I would do that separately.
- Likewise, the embedded compiler is disabled on all platforms but x86 (this is already the case with LLVM 12). I plan to enable LLVM also for ARM but that will be separately.
- My code changes https://github.com/ClickHouse/ClickHouse/pull/41762/commits/3efd42ae2edeb624945d781ef2ca9a081533367f and https://github.com/ClickHouse/ClickHouse/pull/41762/commits/a5311fb9766dad4fd0e71d24cca4d24d913b7bc4 are not beautiful but a working workaround for now. See the corresponding commit msg.

Thanks!

**Comment by Algunenano** [comment]
I'm not sure if you've thought about it already, but if there is a subsequent update to LLVM 14 it'd be great to merge the libcxx and libcxxabi submodules into this new one, as both come from the same source repository originally. That way keeping everything in sync in the future will be simpler.

**Comment by rschu1ze** [comment]
@Algunenano Thanks, I didn't know that. Yes, I plan to upgrade to LLVM 14 once 13 is in and I'll check your proposal (it sounds feasible).

**Review by kitaisreal — APPROVED** [review]

**Pull request merged**
