### PR TITLE
[WIP] ISSUES-838 support compression with codec

### PR DESCRIPTION
**Pull request by zhang2014**
#838 
reference #2441

TODO:
- [x] ZSTD、LZ4、None Compression Codec
- [ ] Delta、LZHC、Multiple、XOR Compression Codec
- [ ] ALTER TABLE Compression Codec
- [ ] Support Codec for clickhouse-compressor
- [ ] Refactor tcp compression
- [ ] Support codec for other engine

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
How is it going?

**Comment by zhang2014** [comment]
@alexey-milovidov I will commit the first version within this week. Thank you for waiting.

**Comment by zhang2014** [comment]
@alexey-milovidov  Sorry for the delay. I will continue the work now. It has too much conflict : (

**Comment by alesapin** [comment]
@zhang2014 I'll take this task, because we need to merge it in two weeks. If you have some unfinished work please commit.

**Comment by zhang2014** [comment]
@alesapin Well, actually I just solved the conflict : ( 
That is my todo list hoping it can help you : )
- [ ] Support  Delta(UInt64) Codec
- [ ] Support ALTER TABLE xxx MODIFY COLUMN CODEC Delta(UInt64)
- [ ] Select Codec using the compression_setting & refactor compression_setting config
- [ ] Support for engines other than MergeTree

**Comment by zhang2014** [comment]
@alesapin Hopefully https://github.com/yandex/ClickHouse/pull/2586#issuecomment-446837620 didn't mislead you (In fact, what I want to express is that these unfinished plans will be helpful for your subsequent plans, for example, to help you understand my thoughts)  😄 

In order not to mislead you, I will continue to complete this todo list (If necessary)

**Comment by alesapin** [comment]
@zhang2014 Which problem you tried to fix with this commit https://github.com/yandex/ClickHouse/pull/2586/commits/b6af9490062f5d93fa3c781833d0469a62856957? ZSTD codec requires information about level only at compression stage. Decompression can be done without any information about level setting. On current master 
```
DETACH TABLE IF EXISTS test.compression_codec;
ATTACH TABLE IF NOT EXISTS test.compression_codec;
```
works without errors.

**Comment by zhang2014** [comment]
Implementation in #4052 #4054

**Pull request closed without merging**
