### PR TITLE
Try speedup build

### PR DESCRIPTION
**Pull request by 4ertus2**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Move extended types to own header 'common/extended_types.h', replace '#include <Core/Types.h>' with '#include <common/types.h>' if possible

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]
LGTM

**Comment by 4ertus2** [comment]
There's a questionable warning in gcc build described here https://gcc.gnu.org/bugzilla/show_bug.cgi?id=55776

**Comment by 4ertus2** [comment]
Fail in test_materialize_mysql_database/test.py::test_materialize_database_ddl_with_empty_transaction_8_0 is not ralated to bigints

**Comment by alexey-milovidov** [comment]
@zhang2014 @BohuTANG about MaterializeMySQL test ^

**Comment by BohuTANG** [comment]
From the out.log it seems that ClickHouse does not sync the MySQL binlog event but not sure the root cause.
By the way, I can't reproduce it on my pc.

**Comment by zhang2014** [comment]
@alexey-milovidov I will fix it.

**Comment by bobrik** [comment]
Is this going to be backported to v20.9?

**Comment by alexey-milovidov** [comment]
Most likely not, as it is not a bugfix.

**Pull request merged**
