### PR TITLE
insert UInt32 Hashvalue in reverse order on big endian machine

### PR DESCRIPTION
**Pull request by suzyw-w**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
...

Fix Hashvalue order on big endian machine
### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]

**Review by alexey-milovidov — CHANGES_REQUESTED** [review]
If it is needed for serialized state compatibility, let's do it on ser/de, as it will be more efficient.

**Comment by alexey-milovidov** [comment]
Please add a comment in the code with the motivation.

**Review by alexey-milovidov — APPROVED** [review]
Sounds reasonable, thank you!

**Comment by SuzyWangIBMer** [comment]
Can someone merge this in, please?

**Review by alexey-milovidov — APPROVED** [review]

**Pull request merged**
