### PR TITLE
Align connect timeout with aws sdk default

### PR DESCRIPTION
**Pull request by nickitat**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

https://github.com/aws/aws-sdk-cpp/blob/e3db71cf6d9a8750d22ceda2e0b258a012007418/src/aws-cpp-sdk-core/include/aws/core/client/ClientConfiguration.h#L126-L129

### CODE REVIEW

**Comment by nickitat** [comment]
as I see we manually set bigger value in `tests/config/config.d/storage_conf.xml`, but who knows...

**Review by alesapin — COMMENTED** [review]
Why you decided to change it?

**Comment by nickitat** [comment]
> Why you decided to change it?

https://pastila.nl/?0053b6a2/3afa85f26c150f7f062a7498f16dbb62

queries that over 10 sec get connection timeouts

**Review by alesapin — APPROVED** [review]
Agree, it doesn't make any sense to wait so long for connection (better to retry another proxy)

**Comment by alesapin** [comment]
I think test_merge_tree_s3_failover failures are related. Need to increase timeouts for this test.

**Review by alesapin — APPROVED** [review]

**Pull request merged**
