### PR TITLE
New analyzer: add duplicate distinct pass

### PR DESCRIPTION
**Pull request by JackyWoo**
### Changelog category (leave one):
- Performance Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Remove duplicate distinct if it's possible.

Example: SELECT DISTINCT c1 FROM (SELECT DISTINCT c1 FROM table);
Result: SELECT c1 FROM (SELECT DISTINCT c1 FROM table);

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by robot-ch-test-poll4** [comment]
This is an automated comment for commit 44d20904a57a9716709daecd0ccb9a6484d12a99 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/52304/44d20904a57a9716709daecd0ccb9a6484d12a99/ci_running.html)
The overall status of the commit is 🔴 failure

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🔴 failure</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Comment by devcrafter** [comment]
We have such optimization on query plan level. Please see setting `query_plan_remove_redundant_distinct`

**Comment by JackyWoo** [comment]
@devcrafter Thanks for the information. May I ask why you choose to do it in query plan level but not query tree level?

**Comment by devcrafter** [comment]
> @devcrafter Thanks for the information. May I ask why you choose to do it at query plan level but not query tree level?

Good question. It's done this way because views are not expanded on query tree level, but on query plan level. Consider this example - https://pastila.nl/?0063fdd0/fb948ad1b33ab14fc767bbff6a8053c1

As you can see, the query tree doesn't contain information about distinct in `tab_v` but the query plan does.

P.S. Your question helps discover a bug related to views and distinct deduplication - see fix https://github.com/ClickHouse/ClickHouse/pull/52438 (the example above done on clickhouse version with this fix)

**Comment by JackyWoo** [comment]
@devcrafter Thank you. I have investigated the source code, and it is indeed in the plan stage that the view is expanded. May I ask why you guys exapnd view in plan stage but not query rewrite stage?

If it is in plan stage,  maybe we should move more passes to plan stage.

Expacting for your replay.

**Comment by JackyWoo** [comment]
> @devcrafter Thank you. I have investigated the source code, and it is indeed in the plan stage that the view is expanded. May I ask why you guys exapnd view in plan stage but not query rewrite stage? Maybe it is better to expand it in query rewrite stage in generally.
> 
> As my understanding we should move all suquery related passes to plan stage, such as `CountDistinctPass`.
> 
> Expecting for your replay.

@kitaisreal Could you please pay attention to this issue?

**Comment by novikd** [comment]
> As my understanding we should move all suquery related passes to plan stage, such as CountDistinctPass.

Why? It doesn't depend on `StorageView`.

**Comment by JackyWoo** [comment]
Sorry `CountDistinctPass ` in deed does not depend `StorageView`, for it translate `TableNode` to `QueryNode` but not operate subquery and it is not a proper example.  I investigated all passes and did not find passes who operate subquery  directly.

**Pull request closed without merging**
