### PR TITLE
Disable cache oblivious large allocation alignment for jemalloc

### PR DESCRIPTION
**Pull request by azat**
During another round of looking at jemalloc I found this, let's try.

### Changelog category (leave one):
- Performance Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Disable cache oblivious large allocation alignment for jemalloc (This should reduce memory fragmentation slightly)

Refs: https://github.com/jemalloc/jemalloc/issues/1098#issuecomment-1593966446

*Note: marked as `Performance Improvement` to run more perf tests*

### CODE REVIEW

**Comment by robot-ch-test-poll1** [comment]
*This is an automated comment for commit 5e5bdfe4e8071a5e1f867d186adf9b5675e3c597 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/57951/5e5bdfe4e8071a5e1f867d186adf9b5675e3c597/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td><a href="https://github.com/ClickHouse/ClickHouse/actions/runs/7233487343">✅ success</a></td></tr>
<tbody>
</table>
</details>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/57951/5e5bdfe4e8071a5e1f867d186adf9b5675e3c597/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Comment by azat** [comment]
>Integration tests (asan) [1/4] — fail: 21, passed: 0

- CI is broken - https://github.com/ClickHouse/ClickHouse/pull/57952

**Comment by alexey-milovidov** [comment]
Performance didn't change, but the memory usage slightly decreased (5% less MemoryResident in one of four runs and around 10% less MemoryVirtual).

**Review by alexey-milovidov — APPROVED** [review]

**Comment by azat** [comment]
Yep, but it does not have peak/max rss, and this is the metric that I want to look at

**Review by alexey-milovidov — APPROVED** [review]

**Comment by azat** [comment]
> Performance didn't change

Actually it did change, usually nobody consider such performance results as significant, but I started to wonder...
In short - this optimization still makes difference, though there are not a lot of patterns in ClickHouse that rely on it I guess...
Anyway, here are some comments why - https://github.com/jemalloc/jemalloc/issues/1098#issuecomment-1865007427

Also I've reproduced this locally, it is hard to see the difference in profiler (due to too much noise from other places in ClickHouse), but I wrote a simple C program which shows the difference, with patched jemalloc it has more `L1-dcache-load-misses` and `dTLB-load-misses`

> but memory usage slightly decreased (5% less MemoryResident in one of four runs and around 10% less MemoryVirtual).

Since it actually do not change RSS a lot, I don't that it make sense. Let's just close it. But it was fun.

**Pull request closed without merging**
