### PR TITLE
Add setting aggregation_max_size_for_arena_chunk

### PR DESCRIPTION
**Pull request by nicelulu**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

For changelog. Remove if this is non-significant change.

Category (leave one):
- Improvement

Short description (up to few sentences):

When an element in the aggregate state is larger than the default 128M allocContinue falls into an infinite loop, you can increase the maximum chunk size that can be used in the aggregate.

Detailed description (optional):

For example
```
CREATE TABLE test.test_bitmap
(
    `dimension` String,
    `bitmap` AggregateFunction(groupBitmap, UInt32),
    `pt` Date
)
ENGINE = MergeTree
PARTITION BY toYYYYMMDD(pt)
ORDER BY dimension
SETTINGS index_granularity = 128
```
```
INSERT INTO test.test_bitmap SELECT
    'test1',
    groupBitmapState(toUInt32(number)),
    '2019-09-01'
FROM
(
    SELECT number
    FROM system.numbers
    WHERE number > 0
    LIMIT 100000000
)
```
```
INSERT INTO test.test_bitmap SELECT
    'test2',
    groupBitmapState(toUInt32(number)),
    '2019-09-01'
FROM
(
    SELECT number
    FROM system.numbers
    WHERE number > 0
    LIMIT 100
)
```
```
SELECT bitmapCardinality(bitmapAnd(b[1], b[2]))
FROM
(
    SELECT groupArray(bitmap) AS b
    FROM test.test_bitmap
    WHERE (dimension = 'test1') OR (dimension = 'test2')
)
```
The individual elements in the groupArray occupy more memory than the default 128MB chunk.

### CODE REVIEW

**Comment by akuzm** [comment]
Glancing over the code, I don't see an infinite loop, but the nextSize() logic looks broken in that it leads to a quadratic behavior when doing alignAlloc() beyond the linear_growth_threshold: we only allocate the size we need, which might be threshold + 8 bytes, then threshold + 16 bytes, etc., copying the entire chunk each time. We probably should round up to a mulitple of linear_growth_threshold instead.

I will look into this in more detail.

**Comment by nicelulu** [comment]
> Glancing over the code, I don't see an infinite loop, but the nextSize() logic looks broken in that it leads to a quadratic behavior when doing alignAlloc() beyond the linear_growth_threshold: we only allocate the size we need, which might be threshold + 8 bytes, then threshold + 16 bytes, etc., copying the entire chunk each time. We probably should round up to a mulitple of linear_growth_threshold instead.
> 
> I will look into this in more detail.

For example, assume that linear_growth_threshold is 100 bytes. The current node requires a total of 120 bytes. The 99 bytes in the chunk have been used from position 0 to position 99. Next time, 4 bytes need to be allocated again via allocContinue. At this time, addChunk will be added, and then the chun 0 of the previous chunk will be copied to the new chunk, but the new chunk will also be unable to allocate 4 bytes, so that it will loop indefinitely.

**Comment by akuzm** [comment]
The test case works fine for me:

```
SELECT bitmapCardinality(bitmapAnd(b[1], b[2]))
FROM 
(
    SELECT groupArray(bitmap) AS b
    FROM test.test_bitmap
    WHERE (dimension = 'test1') OR (dimension = 'test2')
)

┌─bitmapCardinality(bitmapAnd(arrayElement(b, 1), arrayElement(b, 2)))─┐
│                                                                  100 │
└──────────────────────────────────────────────────────────────────────┘

1 rows in set. Elapsed: 0.219 sec. 
```

What is the problem we are fixing?

**Comment by akuzm** [comment]
The case from the other PR works as well:

```
:) SELECT ignore(groupArray(number)) FROM (SELECT number FROM system.numbers LIMIT 73554433);

┌─ignore(groupArray(number))─┐
│                          0 │
└────────────────────────────┘

1 rows in set. Elapsed: 2.404 sec. Processed 73.60 million rows, 588.78 MB (30.61 million rows/s., 244.88 MB/s.) 
```

This is on v19.15.1.1310-testing.

**Comment by nicelulu** [comment]
> What is the problem we are fixing?

This case is because a pr modified the serialization method of bitmapData a few days ago.

**Comment by nicelulu** [comment]
```
SELECT groupArray(array)
FROM 
(
    SELECT groupArray(number) AS array
    FROM 
    (
        SELECT number
        FROM system.numbers 
        LIMIT 33554433
    ) 
) 
```
@akuzm You can try this case, it doesn't work well.

**Comment by nicelulu** [comment]
@akuzm You can try this pr https://github.com/yandex/ClickHouse/pull/6946 test case , it doesn't work well.
```
SELECT count(*)
FROM
(
    SELECT groupArray(ids)
    FROM test_groupArray
    WHERE name = 'test'
    GROUP BY name
)

→ Progress: 1.00 rows, 134.22 MB (4.83 rows/s., 648.22 MB/s.) Received exception from server (version 19.15.1):
Code: 241. DB::Exception: Received from localhost:9090. DB::Exception: Memory limit (for query) exceeded: would use 9.38 GiB (attempt to allocate chunk of 134217760 bytes), maximum: 9.31 GiB.
```
This query is expected to require far less than 9.31GB of memory.

**Comment by akuzm** [comment]
> @akuzm You can try this pr #6946 test case , it doesn't work well.

Yes, I can reproduce this. Could you test this fix: https://github.com/yandex/ClickHouse/pull/6951 , does it help? For me, it reduces memory usage, and the query requires less than 2 GB to complete.

**Comment by akuzm** [comment]
Fixed in #6951.

**Pull request closed without merging**
