### PR TITLE
Fix segfault in opentelemetry_span_log

### LINKED ISSUE #38221: Segfault in OpenTelemetrySpanLog
https://s3.amazonaws.com/clickhouse-test-reports/0/a60a55b83cfb7a7fb1a4a0bba2af19fb5595cb83/stress_test__undefined__actions_.html

https://pastila.nl/?004a4e1e/09b34dbc34738fc97635d5f7d9c84333

Related to #37837, #38032, #38157

### LINKED ISSUE #38402: 00974_query_profiler is flaky: queue is full for system log OpenTelemetrySpanLog
https://s3.amazonaws.com/clickhouse-test-reports/38265/59a14d2a509a45de46066bfc8e0a9ad3327d35a7/stateless_tests__release__s3_storage__actions_.html

```2022-06-24 13:48:56 00974_query_profiler:                                                   [ FAIL ] 7.79 sec. - having stderror: 
2022-06-24 13:48:56 [f81d5fb03293] 2022.06.24 13:48:53.155086 [ 41872 ] {7a8d82e9-236d-402f-aeca-4bf0fc6ce083} <Error> SystemLog (system.opentelemetry_span_log): Queue is full for system log 'DB::OpenTelemetrySpanLog' at 1539015
2022-06-24 13:48:56 
2022-06-24 13:48:56 stdout:
2022-06-24 13:48:56 0	0
2022-06-24 13:48:56 1
2022-06-24 13:48:56 10000000000	0
2022-06-24 13:48:56 1
2022-06-24 13:48:56 
```

See also https://github.com/ClickHouse/ClickHouse/pull/37837#discussion_r897812019

### PR DESCRIPTION
**Pull request by tavplubix**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in official stable or prestable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fixed segfault in `system.opentelemetry_span_log`

Fixes #38221
Fixes #38402
cc: @qoega

### CODE REVIEW

**Comment by tavplubix** [comment]
Hm, I though that incorrect code was initially introduced in #37837. This PR reverts it as well. 
I have not seen similar segfaults before recent changes in opentelemetry. So I want to return code to previous state that seemed to be correct (at least it did not cause tests failures).

**Comment by tavplubix** [comment]
> Master is not failing in stress and other tests.

Master (22.7) and 22.6 contain almost the same set of changes around opentelemetry (except #38814) and 22.6 crashes in BC check. Yes, it's a mystery why 22.7 with almost the same code does not crash and it has to be investigated. 

> I actually fixed one use case when number was stored instead of a String value

But what was the problem with storing numbers? All Fields were converted to Strings, so it should has worked fine with numbers. Why do you expect that changing `Array` to `Map` will fix the issue? 

Also revert of the initial PR fixes https://github.com/ClickHouse/ClickHouse/issues/38402 as well.

**Comment by qoega** [comment]
This line was incorrect before:
https://github.com/ClickHouse/ClickHouse/pull/38814/files#diff-ff8ad4aed4cf07fe29cb5344d2ab79bc24efd97d054aa112c3a05b5ab853cc44L319

**Comment by FrankChen021** [comment]
Oh my god, I just rebased my branch to the latest which contains the #38814 commit to resolve some conflicts, and now it's reverting.

I don't know if the reverts in the PR is temporary or permanent because I'm going to submit a PR(which has some conflicts with these reverts and this PR) which introduces tracing context propagation across threads to resolve some bugs. My patch has been running on our clusters for more than half a year.

**Comment by filimonov** [comment]
> Oh my god, I just rebased my branch to the latest which contains the #38814 commit to resolve some conflicts, and now it's reverting.
> 
> I don't know if the reverts in the PR is temporary or permanent because I'm going to submit a PR(which has some conflicts with these reverts and this PR) which introduces tracing context propagation across threads to resolve some bugs. My patch has been running on our clusters for more than half a year.

Revert the revert commit in your branch?

**Pull request closed without merging**
