### PR TITLE
Support complex data types for hive text format 

### PR DESCRIPTION
**Pull request by taiyang-li**
Changelog category (leave one):
- New Feature

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Support complicated data types for hive text format 
- map
- struct
- tuple
 
TODO 
- Support nested data types
- Support case-insensitive field names

### CODE REVIEW

**Comment by taiyang-li** [comment]
@nikitamikhaylov I'am ready for review now.

**Comment by taiyang-li** [comment]
The failure of fast test is strange: 
If I build clickhouse with Debug in fasttest, the issue in https://s3.amazonaws.com/clickhouse-test-reports/34645/d9e7af6400db22b1993b0adc4d2a0c354b8ab0af/fast_test__actions_/server.log  disappeared.

**Comment by taiyang-li** [comment]
@nikitamikhaylov  I met building issue in https://github.com/ClickHouse/ClickHouse/issues/34981   Stack size exceeds limit maybe caused by too mary settings

**Comment by taiyang-li** [comment]
Failed test irrelavent with this PR.

**Comment by taiyang-li** [comment]
failed stateless test: `00484_preferred_max_column_in_block_size_bytes` can't be reproduced with binary compiled with sanitizer=memory. See https://s3.amazonaws.com/clickhouse-test-reports/34645/34e511815f32e899389f9c49e66f00322f741a1b/stateless_tests__memory__actions__[2/3].html

**Comment by taiyang-li** [comment]
Failed stateless test : `01302_aggregate_state_exception_memory_leak` can't be reproduced with binary compiled with sanitizer=thread. See https://s3.amazonaws.com/clickhouse-test-reports/34645/34e511815f32e899389f9c49e66f00322f741a1b/stateless_tests__thread__actions__[2/3].html

**Comment by taiyang-li** [comment]
Failed integration test not related to this PR.

**Comment by taiyang-li** [comment]
@novikd  Any suggestions about it? Thanks!

**Comment by taiyang-li** [comment]
@alexey-milovidov  Can you review it if have time? Thanks

**Comment by tavplubix** [comment]
All changes related to hive are blocked by https://github.com/ClickHouse/ClickHouse/issues/43541 (the tests are temporarily disabled, so we cannot merge new features)

**Comment by alexey-milovidov** [comment]
Should we continue on this PR?

**Comment by taiyang-li** [comment]
> Should we continue on this PR?

I'd like to continue if you have time to review it. But PR https://github.com/ClickHouse/ClickHouse/pull/53443 has a higher priority in our team, Maybe we can finish it first ?

**Comment by taiyang-li** [comment]
It is deprecated. Let's close it.

**Pull request closed without merging**
