### PR TITLE
Add new profile events for queries with subqueries

### PR DESCRIPTION
**Pull request by azat**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Add new profile events for queries with subqueries (`QueriesWithSubqueries`/`SelectQueriesWithSubqueries`/`InsertQueriesWithSubqueries`)

### CODE REVIEW

**Comment by CheSema** [comment]
Well. I think it is a good PR. 
Could you implement `Queries` with proper explanation? After `SelectQueries`and `InsertQueries` could refer to the `Queries` as the same way as `SelectQuery`/`InsertQuery` refer to the `Query`.
Does it include subqueries as well? If so it deserves to be mentioned and tested.

**Comment by CheSema** [comment]
What happens if InterpreterSelectQueryAnalyzer runs instead when allow_experimental_analyzer is true?

**Comment by alexey-milovidov** [comment]
@azat ok, but the name is confusing. Let's rename it to something else, like SelectQueriesWithViews...

**Comment by azat** [comment]
>@azat ok, but the name is confusing. Let's rename it to something else, like SelectQueriesWithViews...

@alexey-milovidov Indeed, though this is not only about views, but subqueries as well, I think `SelectQueriesWithSubqueries` suits better.

> Could you implement Queries with proper explanation?

@CheSema Ok, let's do this to make it less transparent for user.

> Does it include subqueries as well? If so it deserves to be mentioned and tested.

Now it does (tests had been updated as well).

>What happens if InterpreterSelectQueryAnalyzer runs instead when allow_experimental_analyzer is true?

Good catch! Fixed.

**Comment by azat** [comment]
Test failures does not looks related:

>Stateless tests (release, analyzer) — fail: 4, passed: 5290, skipped: 19

- `02767_into_outfile_extensions_msan` - #50290 

>[AST fuzzer (ubsan) — Received signal -1](https://s3.amazonaws.com/clickhouse-test-reports/50204/2e347007a2d220f332e86cd985b2b5a41290cfa8/fuzzer_astfuzzerubsan/report.html)
>Integration tests (tsan) [6/6] — fail: 1, passed: 443, flaky: 0


```
2023.05.27 15:03:19.946601 [ 148 ] {} <Fatal> BaseDaemon: Code: 439. DB::Exception: Cannot schedule a task: no free thread (timeout=0) (threads=32, jobs=10000). (CANNOT_SCHEDULE_TASK), Stack trace (when copying this message, always include the lines below):
```

>[ClickHouse Integration Tests (release) [4/4](https://s3.amazonaws.com/clickhouse-test-reports/50204/2e347007a2d220f332e86cd985b2b5a41290cfa8/integration_tests__release__[4_4].html)

- `test_ssl_cert_authentication/test.py::test_https_non_ssl_auth` - [flaky](https://play.clickhouse.com/play?user=play#U0VMRUNUIGNoZWNrX25hbWUsIHRlc3RfbmFtZSwgcmVwb3J0X3VybApGUk9NIGNoZWNrcwpXSEVSRSAxCiAgICBBTkQgY2hlY2tfc3RhcnRfdGltZSA+PSBub3coKSAtIElOVEVSVkFMIDEgZGF5CiAgICAvL0FORCBwdWxsX3JlcXVlc3RfbnVtYmVyID0gMAogICAgQU5EIHRlc3Rfc3RhdHVzICE9ICdTS0lQUEVEJwogICAgQU5EIHRlc3RfbmFtZSBMSUtFICcldGVzdF9odHRwc19ub25fc3NsX2F1dGglJwogICAgQU5EIGNoZWNrX3N0YXR1cyAhPSAnc3VjY2VzcycKT1JERVIgQlkgY2hlY2tfbmFtZSwgdGVzdF9uYW1lLCBjaGVja19zdGFydF90aW1l)

[ClickHouse Stateless Tests (release, DatabaseReplicated) [2/4]](https://s3.amazonaws.com/clickhouse-test-reports/50204/2e347007a2d220f332e86cd985b2b5a41290cfa8/stateless_tests__release__databasereplicated__[2_4].html)

- `02125_many_mutations` - [flaky](https://play.clickhouse.com/play?user=play#U0VMRUNUIGNoZWNrX25hbWUsIHRlc3RfbmFtZSwgcmVwb3J0X3VybApGUk9NIGNoZWNrcwpXSEVSRSAxCiAgICBBTkQgY2hlY2tfc3RhcnRfdGltZSA+PSBub3coKSAtIElOVEVSVkFMIDEgZGF5CiAgICAvL0FORCBwdWxsX3JlcXVlc3RfbnVtYmVyID0gMAogICAgQU5EIHRlc3Rfc3RhdHVzICE9ICdTS0lQUEVEJwogICAgQU5EIHRlc3RfbmFtZSBMSUtFICclMDIxMjVfbWFueV9tdXRhdGlvbnMlJwogICAgQU5EIGNoZWNrX3N0YXR1cyAhPSAnc3VjY2VzcycKT1JERVIgQlkgY2hlY2tfbmFtZSwgdGVzdF9uYW1lLCBjaGVja19zdGFydF90aW1l)
- `02703_keeper_map_concurrent_create_drop`

>[ClickHouse Stress Test (msan)](https://s3.amazonaws.com/clickhouse-test-reports/50204/2e347007a2d220f332e86cd985b2b5a41290cfa8/stress_test__msan_.html)

```
elapsed:              1491.543326
query:                SELECT CounterID, quantileTiming(0.5)(SendTiming) AS qt, least(30000, quantileExact(0.5)(SendTiming)) AS qe, count() AS c, round(abs(qt - qe) / greatest(qt, qe) AS diff, 3) AS rounded_diff FROM test.hits WHERE SendTiming != -1 GROUP BY CounterID HAVING diff != 0 ORDER BY diff D
...
::__pthread_mutex_lock
./build_docker/./contrib/llvm-project/libcxx/src/mutex.cpp:39::std::__1::mutex::lock()
./build_docker/./contrib/llvm-project/libcxx/include/__mutex_base:0::DB::FileSegment::state() const
./build_docker/./src/Disks/IO/CachedOnDiskReadBufferFromFile.cpp:1011::DB::CachedOnDiskReadBufferFromFile::nextImplStep()
./build_docker/./src/Disks/IO/CachedOnDiskReadBufferFromFile.cpp:770::DB::CachedOnDiskReadBufferFromFile::nextImpl()
```

```
$ zstd -cd clickhouse-server.stress.log.zst | grep -F '[ 3347 ]' | head -n1
2023.05.27 15:13:32.065877 [ 3347 ] {42153e7f-c8d6-4c5c-ace6-829bdd7a52f4} <Test> ReadBufferFromRemoteFSGather: Reading from file: 00170_test/drx/advzchhrlwnogapbcjxocapaphdba (store/575/575b7ef0-5282-4ebb-9c45-59477d59bc62/201403_1_7_1/SendTiming.bin)
$ zstd -cd clickhouse-server.stress.log.zst | grep -F '[ 3347 ]' | tail -n1
2023.05.27 15:47:57.998183 [ 3347 ] {ad0fcc57-7e83-4754-b0dd-a6804494ce71} <Test> CachedOnDiskReadBufferFromFile: Key: 7bd7e731c5586ccb4581623965894460. Returning with 2 bytes, buffer position: 1643590 (offset: 0, predownloaded: 0), buffer available: 2, current range: [1254434, 2018644], file offset of buffer end: 1643592, impl offset: 1643592, file segment state: PARTIALLY DOWNLOADED NO CONTINUATION, current write offset: 1262022, read_type: REMOTE_FS_READ_BYPASS_CACHE, reading until position: 2018645, started with offset: 0, remaining ranges: [1254434, 2018644]
$ zstd -cd clickhouse-server.stress.log.zst | tail -n2
2023.05.27 15:47:58.000452 [ 35581 ] {11f95335-ebfe-4827-8871-42df91ea7323} <Test> CachedOnDiskReadBufferFromFile: Read 2 bytes, read type REMOTE_FS_READ_BYPASS_CACHE, position: 1635466, offset: 1635468, segment end: 2018644
2023.05.27 15:48:00.750074 [ 1662 ] {} <Information> Application: Child process exited normally with code 0.
```

Maybe it looks similar to #49714? cc @kssenii

**Pull request merged**
