### PR TITLE
MergeTree improve insert performance

### PR DESCRIPTION
**Pull request by kitaisreal**
Changelog category (leave one):
- Performance Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
MergeTree improve insert performance replacing std::stable_sort with pdqsort.

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
Is it a draft? I see that sort is replaced but there is no stable sort?

**Comment by alexey-milovidov** [comment]
We figured it out, it's awesome! But a comment needed.

**Comment by kitaisreal** [comment]
```sql
CREATE TABLE test_table (id UInt64, value UInt64) ENGINE=MergeTree ORDER BY id;
INSERT INTO test_table SELECT rand64(0), rand64(1) FROM system.numbers LIMIT 1500000;
```
Before optimization
```
0 rows in set. Elapsed: 4.522 sec. Processed 15.73 million rows, 125.83 MB (3.48 million rows/s., 27.82 MB/s.)
```

After optimization:
```
0 rows in set. Elapsed: 3.748 sec. Processed 15.73 million rows, 125.83 MB (4.20 million rows/s., 33.57 MB/s.)
```

**Comment by kitaisreal** [comment]
```sql
CREATE TABLE test_table (id UInt64, value1 UInt64, value2 UInt64, value3 UInt64) ENGINE=MergeTree ORDER BY id;
INSERT INTO test_table SELECT rand64(0), rand64(1), rand64(2), rand64(3) FROM system.numbers LIMIT 15000000;
```
Before optimization:
```
0 rows in set. Elapsed: 5.056 sec. Processed 15.73 million rows, 125.83 MB (3.11 million rows/s., 24.89 MB/s.)
```
After optimization:
```
0 rows in set. Elapsed: 4.269 sec. Processed 15.73 million rows, 125.83 MB (3.68 million rows/s., 29.47 MB/s.)
```

**Comment by kitaisreal** [comment]
Final performance results https://s3.amazonaws.com/clickhouse-test-reports/34750/b67f756a438b6896f65f1ab43f174901ccbc4f2c/performance_comparison__actions__[1/4]/report.html.
During insertion in merge tree, if primary key is integer columns, and this is most of the time and whole number of columns in merge tree are not so big, we win around 2-3 times in insertion speed for random data. For not random data pdqsort will work even better.
If there are a lot columns in table, we win around 15-20 percents because most of the time we will spend on columns permutation.
Also interesting case is string primary key, in case of it we spend most of the time on string comparison.

**Pull request merged**
