### PR TITLE
Fixed function ngrams when string contains utf8 characters

### PR DESCRIPTION
**Pull request by yandd**
Changelog category:
- Bug Fix (user-visible misbehaviour in official stable or prestable release)
  

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
* Fixed function ngrams when string contains utf8 characters

Detailed description / Documentation draft:
...

### CODE REVIEW

**Comment by vdimir** [comment]
Could you add test for problem cases?

**Comment by yandd** [comment]
> Could you add test for problem cases?

Added already.

**Comment by vdimir** [comment]
ref https://github.com/ClickHouse/ClickHouse/pull/29738#issuecomment-972819744

**Review by vdimir — APPROVED** [review]
lgtm

**Pull request merged**
