### PR TITLE
Analyzer: support join using column from select list

### PR DESCRIPTION
**Pull request by vdimir**
### Changelog category (leave one):

- Not for changelog (changelog entry is not required)

~~This PR is made on top and requires https://github.com/ClickHouse/ClickHouse/pull/59595~~ _(required PR is merged)_

### CODE REVIEW

**Comment by robot-ch-test-poll2** [comment]
*This is an automated comment for commit 0952004f6e290745919dc1c3d97d569ef2853b14 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/60182/0952004f6e290745919dc1c3d97d569ef2853b14/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/60182/0952004f6e290745919dc1c3d97d569ef2853b14/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Comment by vdimir** [comment]
Ref https://github.com/ClickHouse/ClickHouse/issues/56814

**Review by novikd — APPROVED** [review]
LGTM

**Comment by vdimir** [comment]
> ClickHouse special build check — 14/15 artifact groups are OK [Details](https://s3.amazonaws.com/clickhouse-test-reports/60182/a8885e361e1622741373eb3408b6b8063b709120/clickhouse_special_build_check/report.html)

https://github.com/ClickHouse/ClickHouse/issues/61593

**Pull request merged**
