### PR TITLE
Build ClickHouse for release with clang-11

### PR DESCRIPTION
**Pull request by alesapin**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Build/Testing/Packaging Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Now we use clang-11 for production ClickHouse build.

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
It does not work but the error looks different.
Maybe we need to disable ThinLTO for tools like `llvm-tblgen`?

**Comment by alesapin** [comment]
Surprisingly it was able to build on my machine after merge with master.

**Comment by alesapin** [comment]
Let's look at perf tests!

**Comment by alesapin** [comment]
Wow, functional tests failed in alter query.

**Review by alexey-milovidov — APPROVED** [review]

**Review by amosbird — APPROVED** [review]

**Comment by alesapin** [comment]
`test_distributed_over_live_view known` flaky test.

**Pull request merged**
