### PR TITLE
Update mysql.md

### PR DESCRIPTION
**Pull request by dkxiaohei**
Try to refine the translation of the Chinese version

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Documentation (changelog entry is not required)

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

...

Detailed description / Documentation draft:

...

By adding documentation, you'll allow users to try your new feature immediately, not when someone else will have time to document it later. Documentation is necessary for all features that affect user experience in any way. You can add brief documentation draft above, or add documentation right into your patch as Markdown files in [docs](https://github.com/ClickHouse/ClickHouse/tree/master/docs) folder.

If you are doing this for the first time, it's recommended to read the lightweight [Contributing to ClickHouse Documentation](https://github.com/ClickHouse/ClickHouse/tree/master/docs/README.md) guide first.

Information about CI checks: https://clickhouse.tech/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by dkxiaohei** [comment]
Sorry, I currently have no authority to add/edit labels to an issue in this project. Is there someone who can give me a hand? Thanks in advance!

**Comment by dkxiaohei** [comment]
I have no access to 'https://a.yandex-team.ru/review/1552413' due to my network condition. So I am not sure why the 2 checks failed. Is there someone or some document that I can turn to?

**Comment by alexey-milovidov** [comment]
@dkxiaohei They were unrelated internal checks. Thank you!

**Comment by dkxiaohei** [comment]
> @dkxiaohei They were unrelated internal checks. Thank you!

Thank you very much! This is my first PR ever. It is indeed encouraging.

**Pull request merged**
