### PR TITLE
Iterate list without index-based access

### PR DESCRIPTION
**Pull request by davenger**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
...

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Review by alesapin — APPROVED** [review]

**Review by alexey-milovidov — APPROVED** [review]

**Review by alexey-milovidov — CHANGES_REQUESTED** [review]
Add a test. Example:

```
clickhouse-local --config-file <(echo '<clickhouse>'; seq --format '<x>%g</x>' 1 1000000; echo '</clickhouse>';) --query 'SELECT 1'
```

**Comment by davenger** [comment]
@alexey-milovidov I added a test but had to decrease number of elements to 50K because of this issue in Poco https://github.com/pocoproject/poco/pull/3885.
Without the fix in Poco the Common.ConfigProcessorManyElements test took [4500 sec](https://s3.amazonaws.com/clickhouse-test-reports/43584/603ccf147b13ac4e1c995bb9f057ec2f495e670e/unit_tests__release-clang_/test_result.txt) in release build and [12500 sec](https://s3.amazonaws.com/clickhouse-test-reports/43584/603ccf147b13ac4e1c995bb9f057ec2f495e670e/unit_tests__tsan_/test_result.txt)  in TSAN build. I tried the fix in Poco locally and with it the test finished in 1 sec in release.

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
Interesting - the test (shell one) was totally ok on my machine.

**Comment by davenger** [comment]
Hmm... interesting.  I see the shell test being slow at this line https://github.com/ClickHouse/ClickHouse/blob/fix_config_child_list_iteration/src/Access/ExternalAuthenticators.cpp#L253

```
#0  0x000000001896a207 in std::__1::__tree_is_left_child[abi:v15003]<std::__1::__tree_node_base<void*>*>(std::__1::__tree_node_base<void*>*) (
    __x=0x7fffe76d2980) at ./contrib/libcxx/include/__tree:87
#1  std::__1::__tree_next_iter[abi:v15003]<std::__1::__tree_end_node<std::__1::__tree_node_base<void*>*>*, std::__1::__tree_node_base<void*>*>(std::__1::__tree_node_base<void*>*) (__x=0x7fffe76d2980) at ./contrib/libcxx/include/__tree:191
#2  std::__1::__tree_const_iterator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::__tree_node<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, void*>*, long>::operator++[abi:v15003]() (this=<optimized out>)
    at ./contrib/libcxx/include/__tree:932
#3  std::__1::__distance[abi:v15003]<std::__1::__tree_const_iterator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::__tree_node<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, void*>*, long> >(std::__1::__tree_const_iterator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::__tree_node<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, void*>*, long>, std::__1::__tree_const_iterator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::__tree_node<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, void*>*, long>, std::__1::input_iterator_tag)
    (__first=..., Python Exception <class 'ValueError'>: chr() arg not in range(0x110000)
__last=) at ./contrib/libcxx/include/__iterator/distance.h:34
#4  std::__1::distance[abi:v15003]<std::__1::__tree_const_iterator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::__tree_node<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, void*>*, long> >(std::__1::__tree_const_iterator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::__tree_node<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, void*>*, long>, std::__1::__tree_const_iterator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::__tree_node<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, void*>*, long>) (__first=..., Python Exception <class 'ValueError'>: chr() arg not in range(0x110000)
__last=)
    at ./contrib/libcxx/include/__iterator/distance.h:52
#5  std::__1::__tree<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >::__count_multi<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > (this=this@entry=0x7fffffffabc8, __k=...)
    at ./contrib/libcxx/include/__tree:2519
#6  0x0000000018969180 in std::__1::multiset<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >::count[abi:v15003](std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const (
    this=0x7fffffffabc8, __k=...) at ./contrib/libcxx/include/set:1390
#7  Poco::Util::XMLConfiguration::enumerate (this=<optimized out>, key=..., range=std::vector (length=50946, capacity=65536) = {...})
    at ./contrib/poco/Util/src/XMLConfiguration.cpp:279
#8  0x000000001895cb2e in Poco::Util::LayeredConfiguration::enumerate (this=<optimized out>, key="", range=std::vector (length=6, capacity=8) = {...})
    at ./contrib/poco/Util/src/LayeredConfiguration.cpp:189
#9  0x0000000018949078 in Poco::Util::AbstractConfiguration::keys (this=0x7ffff702c400, key="", range=std::vector (length=6, capacity=8) = {...})
    at ./contrib/poco/Util/src/AbstractConfiguration.cpp:335
#10 0x00000000148d3f58 in DB::ExternalAuthenticators::setConfiguration (this=0x7ffff7007d00, config=..., log=0x7ffff70c6380)
    at ./src/Access/ExternalAuthenticators.cpp:253
#11 0x0000000015154d9b in DB::Context::setExternalAuthenticatorsConfig (this=0x7fffe73e5000, config=...) at ./src/Interpreters/Context.cpp:854
#12 0x000000001080475e in DB::LocalServer::processConfig (this=0x7fffffffb3a0) at ./programs/local/LocalServer.cpp:564
#13 0x0000000010802cf4 in DB::LocalServer::main (this=0x7fffffffb3a0) at ./programs/local/LocalServer.cpp:419
#14 0x0000000018951446 in Poco::Util::Application::run (this=0x7fffffffb3a0) at ./contrib/poco/Util/src/Application.cpp:334
#15 0x0000000010809040 in mainEntryClickHouseLocal (argc=5, argv=0x7ffff713bde0) at ./programs/local/LocalServer.cpp:803
#16 0x000000000b869bb1 in main (argc_=<optimized out>, argv_=<optimized out>) at ./programs/main.cpp:482
```

**Comment by davenger** [comment]
Stateless tests (tsan) [5/5] - 01606_git_import is flaky

**Pull request merged**
