### PR TITLE
for compile libhdfs3 with support secure datanode data transfer

### PR DESCRIPTION
**Pull request by michael1589**
### Changelog category:
- New Feature

### Changelog entry :
Support hadoop secure datanode data transfer(dfs.data.transfer.protection=privacy). 

There're 2 parts need to modify. This is the last part. 
The first PR refer: 
https://github.com/ClickHouse/libhdfs3/pull/24

### CODE REVIEW

**Comment by kssenii** [comment]
Need to also update submodule because otherwise changes from https://github.com/ClickHouse/libhdfs3/pull/24 will not be applied. (go to contrib/libhdfs3 and pull latest commits to libhdfs, and then commit into this repo the update)

**Comment by michael1589** [comment]
> ClickHouse/libhdfs3#24

GET!

**Comment by michael1589** [comment]
@Mergifyio update

**Comment by kssenii** [comment]
This PR seems abandoned. I'll close it. Please reopen it, if you want to continue with it.

**Comment by MeenaRenganathan22** [comment]
@michael1589,

There is an associated PR in the libhdfs3 module which has been merged already. But this PR to update the submodule has been closed. 

Now, the libhdfs3 module has been updated to the latest commit. So, I'm facing issue in functional and integration test related with the HDFS. 

This is one of the PR that has been tested in the ClickHouse after updating the submodule. 
Any idea to resolve it?

**Pull request closed without merging**
