### PR TITLE
`uniqExact` state parallel merging for distributed queries

### PR DESCRIPTION
**Pull request by nickitat**
### Changelog category (leave one):
- Performance Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Large aggregation states of `uniqExact` will be merged in parallel in distrubuted queries.

### CODE REVIEW

**Comment by robot-ch-test-poll3** [comment]
*This is an automated comment for commit f1efb29a66a662f0c7af34ef317be4a734571bc1 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/59009/f1efb29a66a662f0c7af34ef317be4a734571bc1/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/59009/f1efb29a66a662f0c7af34ef317be4a734571bc1/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Review by alexey-milovidov — APPROVED** [review]

**Review by novikd — APPROVED** [review]
LGTM

**Comment by canhld94** [comment]
@nickitat great work! Do you plan to do same thing for `uniq`?

**Comment by compasses** [comment]
Hi, @nickitat , this  seems will have effect the preformance for with keys distinct count? like select count(distinct xxx) from yyy group by zzz. Since the merge stage, for group by won't pass the thread pool.

**Comment by nickitat** [comment]
> Hi, @nickitat , this seems will have effect the preformance for with keys distinct count? like select count(distinct xxx) from yyy group by zzz. Since the merge stage, for group by won't pass the thread pool.

i'm not sure i got the question right. this optimisation is meant only for aggregation without key because otherwise merging already parallelised between threads if we happen to have two-level aggregation

**Comment by compasses** [comment]
> > Hi, @nickitat , this seems will have effect the preformance for with keys distinct count? like select count(distinct xxx) from yyy group by zzz. Since the merge stage, for group by won't pass the thread pool.
> 
> i'm not sure i got the question right. this optimisation is meant only for aggregation without key because otherwise merging already parallelised between threads if we happen to have two-level aggregation

But, in  uniqueExact read will possible turn to two-level set, BTW, for count distinct, if some key has big distinct value the two-level set may help too. I think should support parallel merge for group by distinct.

**Pull request merged**
