### PR TITLE
Do not retry queries if container is down in integration tests

### PR DESCRIPTION
**Pull request by azat**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by robot-ch-test-poll1** [comment]
*This is an automated comment for commit 9cd0132e8807bf5dad0334b86da7e9398c7d8e64 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/60109/9cd0132e8807bf5dad0334b86da7e9398c7d8e64/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/60109/9cd0132e8807bf5dad0334b86da7e9398c7d8e64/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
@azat It failed: https://s3.amazonaws.com/clickhouse-test-reports/60109/834f090e0f8b3e61f9a5c989b12e1d55ddb5d358/integration_tests__asan_.html

**Comment by azat** [comment]
This PR is not related to the failures I will simply rebase.

**Comment by antonio2368** [comment]
This breaks `test_replicated_database/test.py::test_startup_without_zk` because you didn't add sleep after checking exception message
https://s3.amazonaws.com/clickhouse-test-reports/60109/0496d0f45fa6d07038a32de93f6f65ed02f0c971/integration_tests__asan_.html

**Comment by tavplubix** [comment]
Breaks `test_replicated_table_attach/test.py::test_startup_with_small_bg_pool_partitioned` as well. Thanks for reverting!

**Pull request merged**
