### PR TITLE
Fix config merge for an attributes

### LINKED ISSUE #9547: Unexpected behavior of config substitutions from ZooKeeper
I would like to use ZK as an optional storage for CH settings.
The idea is that I would put files with the 'default' settings on the server into /etc/clickhouse-server, and if I want to change something (probably temporarily) I would make the change in ZK.
I couldn't make this work though (I tested on 20.1.4.14).

1. without replace="true" CH does not even read ZK
```
/etc/clickhouse-server/users.d$  cat test.xml
<yandex>
<profiles>
    <default from_zk="/max_memory">
        <max_memory_usage>10000000001</max_memory_usage>
    </default>
</profiles>
</yandex>

ZK: create max_memory "<max_memory_usage>10000000002</max_memory_usage>"

preprocessed:
<yandex>
    <!-- Profiles of settings. -->
    <profiles>
        <!-- Default settings. -->
        <default>
            <!-- Maximum memory usage for processing single query, in bytes. -->
            <max_memory_usage>10000000001</max_memory_usage>
...
The znode is not even mentioned in the preprocessed file's header ('This file was generated automatically...').
```
2. With replace="true" CH deletes the whole section even if there is no znode in ZK.
It's easy to delete the whole profile or users section and this can lead to CH being unusable.
If the znode exists, the replace works a little strange:
```
/etc/clickhouse-server/users.d$  cat test.xml
<yandex>
<profiles>
    <default>
	    <max_memory_usage replace="true" from_zk="/max_memory">10000000001</max_memory_usage>
    </default>
</profiles>
</yandex>

ZK: set max_memory "10000000002"

preprocessed:
        <default>
            <!-- Maximum memory usage for processing single query, in bytes. -->
            <max_memory_usage>1000000000110000000002</max_memory_usage>
```

### LINKED ISSUE #46131: Environment variable substitution in configuration does not work if parameter already has a value
**Describe the unexpected behaviour**
I'm trying to override `mark_cache_size` parameter from a YAML override file with a reference to an environment variable. No matter if the environment variable is present or not, server always fails to start with an exception.

Also, preprocessed config only contains an empty node for `mark_cache_size` if override is present, instead of `<mark_cache_size from_env="CONFIG_MARK_CACHE_SIZE"></mark_cache_size>`.

**How to reproduce**
Run clickhouse server with the following configuration
```
➜  cmake-build-debug git:(620c977af4b) ✗ cat bug_config/config.xml
<clickhouse>
    <mark_cache_size>123451234</mark_cache_size>

    <logger>
        <level>trace</level>
        <console>true</console>
    </logger>

    <http_port>8123</http_port>
    <tcp_port>9000</tcp_port>
    <mysql_port>9004</mysql_port>

    <path>./</path>

    <mlock_executable>true</mlock_executable>

    <users>
        <default>
            <password/>

            <networks>
                <ip>::/0</ip>
            </networks>

            <profile>default</profile>
            <quota>default</quota>
            <access_management>1</access_management>
        </default>
    </users>

    <profiles>
        <default/>
    </profiles>

    <quotas>
        <default/>
    </quotas>
</clickhouse>
```
```
➜  cmake-build-debug git:(620c977af4b) ✗ cat bug_config/config.d/000-include.yaml
mark_cache_size:
  '@from_env': CONFIG_MARK_CACHE_SIZE
```

This results in the following preprocessed config:
```
➜  cmake-build-debug git:(620c977af4b) ✗ cat preprocessed_configs/config.xml
<!-- This file was generated automatically.
     Do not edit it: it is likely to be discarded and generated again before it's read next time.
     Files used to generate this file:
       ./bug_config/config.xml
       ./bug_config/config.d/000-include.yaml      -->

<clickhouse>
    <mark_cache_size/>

    <logger>
        <level>trace</level>
        <console>true</console>
    </logger>

    <http_port>8123</http_port>
    <tcp_port>9000</tcp_port>
    <mysql_port>9004</mysql_port>

    <path>./</path>

    <mlock_executable>true</mlock_executable>

    <users>
        <default>
            <password/>

            <networks>
                <ip>::/0</ip>
            </networks>

            <profile>default</profile>
            <quota>default</quota>
            <access_management>1</access_management>
        </default>
    </users>

    <profiles>
        <default/>
    </profiles>

    <quotas>
        <default/>
    </quotas>
</clickhouse>
```
**Expected behavior**

**Error message and/or stacktrace**
```
2023.02.07 18:51:06.160593 [ 1600754 ] {} <Error> Application: Poco::Exception. Code: 1000, e.code() = 0, Syntax error: Not a valid unsigned integer, Stack trace (when copying this message, always include the lines below):

0. /home/thevar1able/src/clickhouse/contrib/llvm-project/libcxx/include/exception:134: std::exception::capture() @ 0x19cd0922 in /home/thevar1able/src/clickhouse/cmake-build-debug/programs/clickhouse
1. /home/thevar1able/src/clickhouse/contrib/llvm-project/libcxx/include/exception:112: std::exception::exception[abi:v15000]() @ 0x19cd08ed in /home/thevar1able/src/clickhouse/cmake-build-debug/programs/clickhouse
2. /home/thevar1able/src/clickhouse/contrib/poco/Foundation/src/Exception.cpp:36: Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, int) @ 0x33b05e04 in /home/thevar1able/src/clickhouse/cmake-build-debug/programs/clickhouse
3. /home/thevar1able/src/clickhouse/contrib/poco/Foundation/src/Exception.cpp:145: Poco::RuntimeException::RuntimeException(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, int) @ 0x33b0916f in /home/thevar1able/src/clickhouse/cmake-build-debug/programs/clickhouse
4. /home/thevar1able/src/clickhouse/contrib/poco/Foundation/src/Exception.cpp:158: Poco::DataException::DataException(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, int) @ 0x33b0c08f in /home/thevar1able/src/clickhouse/cmake-build-debug/programs/clickhouse
5. /home/thevar1able/src/clickhouse/contrib/poco/Foundation/src/Exception.cpp:161: Poco::SyntaxException::SyntaxException(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, int) @ 0x33b0c7cf in /home/thevar1able/src/clickhouse/cmake-build-debug/programs/clickhouse
6. /home/thevar1able/src/clickhouse/contrib/poco/Foundation/src/NumberParser.cpp:132: Poco::NumberParser::parseUnsigned64(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, char) @ 0x33b5dadf in /home/thevar1able/src/clickhouse/cmake-build-debug/programs/clickhouse
7. /home/thevar1able/src/clickhouse/contrib/poco/Util/src/AbstractConfiguration.cpp:492: Poco::Util::AbstractConfiguration::parseUInt64(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) @ 0x33927eb3 in /home/thevar1able/src/clickhouse/cmake-build-debug/programs/clickhouse
8. /home/thevar1able/src/clickhouse/contrib/poco/Util/src/AbstractConfiguration.cpp:211: Poco::Util::AbstractConfiguration::getUInt64(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, unsigned long) const @ 0x33927f7e in /home/thevar1able/src/clickhouse/cmake-build-debug/programs/clickhouse
9. /home/thevar1able/src/clickhouse/programs/server/Server.cpp:1524: DB::Server::main(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>> const&) @ 0x2319b8fa in /home/thevar1able/src/clickhouse/cmake-build-debug/programs/clickhouse
10. /home/thevar1able/src/clickhouse/contrib/poco/Util/src/Application.cpp:334: Poco::Util::Application::run() @ 0x3393a012 in /home/thevar1able/src/clickhouse/cmake-build-debug/programs/clickhouse
11. /home/thevar1able/src/clickhouse/programs/server/Server.cpp:479: DB::Server::run() @ 0x23189ea9 in /home/thevar1able/src/clickhouse/cmake-build-debug/programs/clickhouse
12. /home/thevar1able/src/clickhouse/contrib/poco/Util/src/ServerApplication.cpp:611: Poco::Util::ServerApplication::run(int, char**) @ 0x3395c3b9 in /home/thevar1able/src/clickhouse/cmake-build-debug/programs/clickhouse
13. /home/thevar1able/src/clickhouse/programs/server/Server.cpp:200: mainEntryClickHouseServer(int, char**) @ 0x23186b0d in /home/thevar1able/src/clickhouse/cmake-build-debug/programs/clickhouse
14. /home/thevar1able/src/clickhouse/programs/main.cpp:482: main @ 0x19cb0b5a in /home/thevar1able/src/clickhouse/cmake-build-debug/programs/clickhouse
15. ? @ 0x7ffff7dd4290 in ?
16. __libc_start_main @ 0x7ffff7dd434a in ?
17. _start @ 0x19cb066e in /home/thevar1able/src/clickhouse/cmake-build-debug/programs/clickhouse
 (version 23.2.1.1)
```

### PR DESCRIPTION
**Pull request by pufit**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in official stable or prestable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix environment variable substitution in the configuration when a parameter already has a value. This closes https://github.com/ClickHouse/ClickHouse/issues/46131. This closes https://github.com/ClickHouse/ClickHouse/issues/9547.

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

https://github.com/ClickHouse/ClickHouse/issues/46131

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
Does it also fix https://github.com/ClickHouse/ClickHouse/issues/9547 ?

**Comment by pufit** [comment]
> Does it also fix #9547 ?

Yes, it should

**Comment by alexey-milovidov** [comment]
Requires #46149

**Review by nikitamikhaylov — APPROVED** [review]

**Comment by nikitamikhaylov** [comment]
Interesting what is wrong with integration tests?

**Comment by pufit** [comment]
Found this in the attributes map docstring. Probably this should fix asan integration tests.
```
A NamedNodeMap returned from a method must be released with a call to 
release() when no longer needed.
```

**Pull request merged**
