### PR TITLE
Add more settings for randomization

### PR DESCRIPTION
**Pull request by CurtizJ**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by CurtizJ** [comment]
```
02267_empty_arrays_read_reverse:

2022-07-09 19:59:29 [7a1c4e17c1ea] 2022.07.09 19:59:29.606132 [ 610 ] {55d19fac-ff4e-4b25-9d28-6342cfdab1c9}  executeQuery: Code: 32. DB::Exception: Attempt to read after eof: (while reading column a): (while reading from part /var/lib/clickhouse/store/96c/96cb1d15-dc73-4305-aeb2-5905e9acf60e/all_1_2_1/ from mark 0 with max_rows_to_read = 1000): While executing MergeTreeReverse. (ATTEMPT_TO_READ_AFTER_EOF) (version 22.7.1.1) (from [::1]:49770) (comment: 02267_empty_arrays_read_reverse.sql) (in query: SELECT * FROM t_02267 WHERE hasAll(a, ['x']) ORDER BY b DESC SETTINGS max_threads=1, max_block_size=1000;), Stack trace (when copying this message, always include the lines below):
2022-07-09 19:59:29 
2022-07-09 19:59:29 0. ./build_docker/../contrib/libcxx/include/exception:133: Poco::Exception::Exception(std::__1::basic_string, std::__1::allocator > const&, int) @ 0x37df7e89 in /usr/bin/clickhouse
2022-07-09 19:59:29 1. ./build_docker/../src/Common/Exception.cpp:69: DB::Exception::Exception(std::__1::basic_string, std::__1::allocator > const&, int, bool) @ 0xd9673ac in /usr/bin/clickhouse
2022-07-09 19:59:29 2. ./build_docker/../src/IO/VarInt.h:122: DB::throwReadAfterEOF() @ 0xd9242e8 in /usr/bin/clickhouse
2022-07-09 19:59:29 3. ./build_docker/../src/IO/VarInt.h:135: void DB::readVarUIntImpl(unsigned long&, DB::ReadBuffer&) @ 0xda63da0 in /usr/bin/clickhouse
2022-07-09 19:59:29 4. ./build_docker/../src/DataTypes/Serializations/SerializationString.cpp:122: void DB::deserializeBinarySSE2<4>(DB::PODArray, 15ul, 16ul>&, DB::PODArray, 15ul, 16ul>&, DB::ReadBuffer&, unsigned long) @ 0x2c334735 in /usr/bin/clickhouse
2022-07-09 19:59:29 5. ./build_docker/../src/DataTypes/Serializations/SerializationString.cpp:0: DB::SerializationString::deserializeBinaryBulk(DB::IColumn&, DB::ReadBuffer&, unsigned long, double) const @ 0x2c33350a in /usr/bin/clickhouse
2022-07-09 19:59:29 6. ./build_docker/../src/DataTypes/Serializations/ISerialization.cpp:0: DB::ISerialization::deserializeBinaryBulkWithMultipleStreams(COW::immutable_ptr&, unsigned long, DB::ISerialization::DeserializeBinaryBulkSettings&, std::__1::shared_ptr&, std::__1::unordered_map, std::__1::allocator >, COW::immutable_ptr, std::__1::hash, std::__1::allocator > >, std::__1::equal_to, std::__1::allocator > >, std::__1::allocator, std::__1::allocator > const, COW::immutable_ptr > > >*) const @ 0x2c20a635 in /usr/bin/clickhouse
2022-07-09 19:59:29 7. ./build_docker/../src/DataTypes/Serializations/SerializationArray.cpp:0: DB::SerializationArray::deserializeBinaryBulkWithMultipleStreams(COW::immutable_ptr&, unsigned long, DB::ISerialization::DeserializeBinaryBulkSettings&, std::__1::shared_ptr&, std::__1::unordered_map, std::__1::allocator >, COW::immutable_ptr, std::__1::hash, std::__1::allocator > >, std::__1::equal_to, std::__1::allocator > >, std::__1::allocator, std::__1::allocator > const, COW::immutable_ptr > > >*) const @ 0x2c228b6e in /usr/bin/clickhouse
2022-07-09 19:59:29 8. ./build_docker/../contrib/boost/boost/smart_ptr/intrusive_ptr.hpp:194: DB::MergeTreeReaderWide::readData(DB::NameAndTypePair const&, COW::immutable_ptr&, unsigned long, bool, unsigned long, unsigned long, std::__1::unordered_map, std::__1::allocator >, COW::immutable_ptr, std::__1::hash, std::__1::allocator > >, std::__1::equal_to, std::__1::allocator > >, std::__1::allocator, std::__1::allocator > const, COW::immutable_ptr > > >&, bool) @ 0x30625844 in /usr/bin/clickhouse
2022-07-09 19:59:29 9. ./build_docker/../src/Storages/MergeTree/MergeTreeReaderWide.cpp:122: DB::MergeTreeReaderWide::readRows(unsigned long, unsigned long, bool, unsigned long, std::__1::vector::immutable_ptr, std::__1::allocator::immutable_ptr > >&) @ 0x30622713 in /usr/bin/clickhouse
2022-07-09 19:59:29 10. ./build_docker/../src/Storages/MergeTree/MergeTreeRangeReader.cpp:102: DB::MergeTreeRangeReader::DelayedStream::finalize(std::__1::vector::immutable_ptr, std::__1::allocator::immutable_ptr > >&) @ 0x3179e7dd in /usr/bin/clickhouse
2022-07-09 19:59:29 11. ./build_docker/../src/Storages/MergeTree/MergeTreeRangeReader.cpp:0: DB::MergeTreeRangeReader::startReadingChain(unsigned long, std::__1::deque >&) @ 0x317ad714 in /usr/bin/clickhouse
2022-07-09 19:59:29 12. ./build_docker/../src/Storages/MergeTree/MergeTreeRangeReader.cpp:0: DB::MergeTreeRangeReader::read(unsigned long, std::__1::deque >&) @ 0x317a8b57 in /usr/bin/clickhouse
2022-07-09 19:59:29 13. ./build_docker/../src/Storages/MergeTree/MergeTreeRangeReader.cpp:0: DB::MergeTreeRangeReader::read(unsigned long, std::__1::deque >&) @ 0x317a897e in /usr/bin/clickhouse
2022-07-09 19:59:29 14. ./build_docker/../src/Storages/MergeTree/MergeTreeBaseSelectProcessor.cpp:310: DB::MergeTreeBaseSelectProcessor::readFromPartImpl() @ 0x3178358a in /usr/bin/clickhouse
2022-07-09 19:59:29 15. ./build_docker/../src/Storages/MergeTree/MergeTreeReverseSelectProcessor.cpp:0: DB::MergeTreeReverseSelectProcessor::readFromPart() @ 0x317edd6b in /usr/bin/clickhouse
2022-07-09 19:59:29 16. ./build_docker/../src/Storages/MergeTree/MergeTreeBaseSelectProcessor.cpp:0: DB::MergeTreeBaseSelectProcessor::generate() @ 0x31780e42 in /usr/bin/clickhouse
2022-07-09 19:59:29 17. ./build_docker/../src/Processors/Chunk.h:90: DB::ISource::tryGenerate() @ 0x30d7dfcf in /usr/bin/clickhouse
2022-07-09 19:59:29 18. ./build_docker/../src/Processors/ISource.cpp:0: DB::ISource::work() @ 0x30d7d15f in /usr/bin/clickhouse
2022-07-09 19:59:29 19. ./build_docker/../src/Processors/Executors/ExecutionThreadContext.cpp:0: DB::ExecutionThreadContext::executeTask() @ 0x30dc75fa in /usr/bin/clickhouse
2022-07-09 19:59:29 20. ./build_docker/../src/Processors/Executors/PipelineExecutor.cpp:222: DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic*) @ 0x30da9f73 in /usr/bin/clickhouse
2022-07-09 19:59:29 21. ./build_docker/../src/Processors/Executors/PipelineExecutor.cpp:0: DB::PipelineExecutor::executeImpl(unsigned long) @ 0x30da858f in /usr/bin/clickhouse
2022-07-09 19:59:29 22. ./build_docker/../contrib/libcxx/include/__memory/unique_ptr.h:284: DB::PipelineExecutor::execute(unsigned long) @ 0x30da79d0 in /usr/bin/clickhouse
2022-07-09 19:59:29 23. ./build_docker/../contrib/libcxx/include/atomic:939: void std::__1::__function::__policy_invoker::__call_impl(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'(), void ()> >(std::__1::__function::__policy_storage const*) @ 0x30dd194f in /usr/bin/clickhouse
2022-07-09 19:59:29 24. ./build_docker/../contrib/libcxx/include/__functional/function.h:0: ThreadPoolImpl::worker(std::__1::__list_iterator) @ 0xdaacc47 in /usr/bin/clickhouse
2022-07-09 19:59:29 25. ./build_docker/../contrib/libcxx/include/__memory/unique_ptr.h:312: void* std::__1::__thread_proxy >, void ThreadPoolImpl::scheduleImpl(std::__1::function, int, std::__1::optional)::'lambda0'()> >(void*) @ 0xdab4d7c in /usr/bin/clickhouse
2022-07-09 19:59:29 26. ? @ 0x7f9e59ccb609 in ?
2022-07-09 19:59:29 27. clone @ 0x7f9e59bf0133 in ?
2022-07-09 19:59:29 
2022-07-09 19:59:29 Received exception from server (version 22.7.1):
2022-07-09 19:59:29 Code: 32. DB::Exception: Received from localhost:9000. DB::Exception: Attempt to read after eof: (while reading column a): (while reading from part /var/lib/clickhouse/store/96c/96cb1d15-dc73-4305-aeb2-5905e9acf60e/all_1_2_1/ from mark 0 with max_rows_to_read = 1000): While executing MergeTreeReverse. (ATTEMPT_TO_READ_AFTER_EOF)
2022-07-09 19:59:29 (query: SELECT * FROM t_02267 WHERE hasAll(a, ['x'])
2022-07-09 19:59:29 ORDER BY b DESC
2022-07-09 19:59:29 SETTINGS max_threads=1, max_block_size=1000;)
2022-07-09 19:59:29 , result:
2022-07-09 19:59:29 
2022-07-09 19:59:29 
2022-07-09 19:59:29 
2022-07-09 19:59:29 stdout:
2022-07-09 19:59:29 
2022-07-09 19:59:29 
2022-07-09 19:59:29 Settings used in the test: --max_insert_threads=0 --group_by_two_level_threshold=100000 --group_by_two_level_threshold_bytes=50000000 --distributed_aggregation_memory_efficient=1 --fsync_metadata=0 --output_format_parallel_formatting=1 --input_format_parallel_parsing=0 --min_chunk_bytes_for_parallel_parsing=17933996 --max_read_buffer_size=884404 --prefer_localhost_replica=1 --max_block_size=88295 --max_threads=64 --optimize_or_like_chain=0 --optimize_read_in_order=1 --read_in_order_two_level_merge_threshold=79 --optimize_aggregation_in_order=0 --aggregation_in_order_max_block_bytes=42285344 --use_uncompressed_cache=1 --min_bytes_to_use_direct_io=0 --min_bytes_to_use_mmap_io=616353300 --local_filesystem_read_method=pread --remote_filesystem_read_method=threadpool --local_filesystem_read_prefetch=1 --remote_filesystem_read_prefetch=0 --compile_expressions=1 --compile_aggregate_expressions=0 --compile_sort_description=0
2022-07-09 19:59:29 
```

**Comment by UnamedRus** [comment]
Can we add `merge_tree_coarse_index_granularity` as well? 
I've seen stuck queries with value = 1 and `division by zero` crash with value = 0

**Comment by CurtizJ** [comment]
Let's run tests one more time.

**Comment by CurtizJ** [comment]
Failed test `01565_reconnect_after_client_error` is flaky with tsan: [link](https://play.clickhouse.com/play?user=play#c2VsZWN0IAp0b1N0YXJ0T2ZEYXkoY2hlY2tfc3RhcnRfdGltZSkgYXMgZCwKY291bnQoKSwgZ3JvdXBVbmlxQXJyYXkocHVsbF9yZXF1ZXN0X251bWJlciksIGFueShyZXBvcnRfdXJsKQpmcm9tIGNoZWNrcyB3aGVyZSAnMjAyMi0wMy0wMScgPD0gY2hlY2tfc3RhcnRfdGltZSBhbmQgY2hlY2tfbmFtZSBpbGlrZSAnJXRocmVhZCUnIGFuZCB0ZXN0X25hbWUgbGlrZSAnMDE1NjVfcmVjb25uZWN0X2FmdGVyX2NsaWVudF9lcnJvciUnIGFuZCB0ZXN0X3N0YXR1cyBpbiAoJ0ZBSUwnKSBncm91cCBieSBkIG9yZGVyIGJ5IGQgZGVzYw==)

**Comment by CurtizJ** [comment]
Stress tests:
`2022.07.15 19:41:05.212735 [ 1146265 ] {} <Error> MergeFromLogEntryTask: virtual bool DB::ReplicatedMergeMutateTaskBase::executeStep(): Code: 235. DB::Exception: Part 4_68_115_11 (state Active) already exists. (DUPLICATE_DATA_PART), Stack trace (when copying this message, always include the lines below):`
`2022.07.15 19:27:44.973945 [ 1317246 ] {} <Error> MutateFromLogEntryTask: virtual bool DB::ReplicatedMergeMutateTaskBase::executeStep(): Code: 16. DB::Exception: There is no column `s` in table. (NO_SUCH_COLUMN_IN_TABLE), Stack trace (when copying this message, always include the lines below):`

Most likely unrelated.

**Comment by CurtizJ** [comment]
No interesting test failures in last 3 check runs. Let's merge.

**Comment by CurtizJ** [comment]
> Is this failure related to new random settings?

Yes, 2 settings are required:
```
cat queries/1_stateful/00024_random_counters.sql | clickhouse-client -n --use_uncompressed_cache=1 --min_bytes_to_use_direct_io=1
...
Received exception from server (version 22.7.1):
Code: 33. DB::Exception: Received from localhost:9000. DB::Exception: Cannot read all data. Bytes read: 0. Bytes expected: 25.: (while reading column Sign): (while reading from part ./data/datasets/visits_v1/20140317_20140323_3_4_1/ from mark 204 with max_rows_to_read = 8192): While executing MergeTreeInOrder. (CANNOT_READ_ALL_DATA)
(query: SELECT uniq(UserID), sum(Sign) FROM datasets.visits_v1 WHERE CounterID = 33436573;)
```

**Pull request merged**
