### PR TITLE
Remove "locale"

### PR DESCRIPTION
**Pull request by alexey-milovidov**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by robot-ch-test-poll3** [comment]
This is an automated comment for commit 13ed528e0bb8e6d309075bd51dc1df3c93feb13b with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/49597/13ed528e0bb8e6d309075bd51dc1df3c93feb13b/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Comment by azat** [comment]
@alexey-milovidov does this affects performance somehow?

P.S. You forgot to update `ClickHouse/release/15.x` branch in LLVM fork.

**Comment by alexey-milovidov** [comment]
@azat 

> P.S. You forgot to update ClickHouse/release/15.x branch in LLVM fork.

I checked it, but the current commit points to somewhere else. It's better to create another branch.
We also should update LLVM to master.

**Comment by alexey-milovidov** [comment]
> does this affects performance somehow?

I expect it could improve the performance of some third-party libraries.

The main usage of the locale is to ask the C++ standard library: "please always use the C locale, don't stand in my way".
Everything else is pure garbage. I wanted to find some easy way to remove locales completely but didn't find it.

I'm also curious about how it is initialized but didn't have attention to check it.

**Comment by alexey-milovidov** [comment]
The motivation for this change is a bug in debug version of LLVM's libc++ - it tracked down to locales.
The easiest way is - to remove locales and forget about it.

**Pull request merged**
