### PR TITLE
Update Dockerfile

### PR DESCRIPTION
**Pull request by polozhevets**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

For changelog. Remove if this is non-significant change.

Category (leave one):
- New Feature
- Bug Fix
- Improvement
- Performance Improvement
- Backward Incompatible Change
- Build/Testing/Packaging Improvement
- Other

Short description (up to few sentences):

...

Detailed description (optional):

...

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
What is the purpose of this change?

**Comment by alesapin** [comment]
These variables are used inside release process. We cannot simply delete them.

**Comment by alexey-milovidov** [comment]
@alesapin

> ARG repository="deb http://repo.yandex.ru/clickhouse/deb/stable/ main/"

Maybe simply change repository to `testing`? Because `stable` doesn't have this version.

**Comment by alesapin** [comment]
Yes, it would be more correct, but this URL also used inside the release process. And also we don't have version `19.11.0` even in testing. I can make changes in the release script to fix this issues, but why somebody would like to build `clickhouse-server` image from our repo? What is the purpose?

**Comment by polozhevets** [comment]
> Yes, it would be more correct, but this URL also used inside the release process. And also we don't have version `19.11.0` even in testing. I can make changes in the release script to fix this issues, but why somebody would like to build `clickhouse-server` image from our repo? What is the purpose?

How to get the "latest" stable version and create more flexible config file?

**Comment by filimonov** [comment]
> How to get the "latest" stable version and create more flexible config file?

Do you mean ClickHouse config? You can just pass it 'from outside' as a volume.

Just like that 
```
docker run -v /path/to/my_config.xml:/etc/clickhouse-server/config.xml yandex/clickhouse-server:latest
```

**Comment by alexey-milovidov** [comment]
> And also we don't have version 19.11.0 even in testing.

We have 19.11 in https://repo.yandex.ru/clickhouse/deb/testing/main/

**Comment by filimonov** [comment]
> > And also we don't have version 19.11.0 even in testing.
> 
> We have 19.11 in https://repo.yandex.ru/clickhouse/deb/testing/main/

Yes. I've even installed that yesterday :) BTW: please remove those packages with prefix 2 from testing repo (OR add 2: to all of them).
```
clickhouse-server | 2:19.3.190 | http://repo.yandex.ru/clickhouse/deb/testing main/ Packages
clickhouse-server | 2:19.3.4.19 | http://repo.yandex.ru/clickhouse/deb/testing main/ Packages
```

**Comment by alesapin** [comment]
> And also we don't have version 19.11.0 even in testing.

We don't have exactly 19.11.0 version. We have 19.11.0.xxx versions.

**Comment by alexey-milovidov** [comment]
> please remove those packages with prefix 2 from testing repo (OR add 2: to all of them).

Removed.

**Pull request closed without merging**
