### PR TITLE
Avoid re-loading completion from the history file after each query

### PR DESCRIPTION
**Pull request by azat**
Changelog category (leave one):
- Other

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Avoid re-loading completion from the history file after each query (to avoid history overlaps with other client sessions)

By default replxx reload history from the file in
replxx::Replxx::history_save(), and this will overlaps current session
history with the history from other sessions, and this does not looks a
great idea (bash and other interpreters don't do this).

So to avoid this, use separate replxx::Replxx instance.

Refs: #11453

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
But when we save history from different clients, all histories should be saved.
(Bash and all readline-based tools that I know don't do that and it's a huge drawback).

**Comment by alexey-milovidov** [comment]
The code looks Ok.

**Comment by alexey-milovidov** [comment]
This is significant change for changelog, please edit the description accordingly.

**Comment by azat** [comment]
>(Bash and all readline-based tools that I know don't do that and).

By default, but can be enabled in bash:

```bash
shopt -s histappend
# or proper append ...
PROMPT_COMMAND='history -a'
```

>it's a huge drawback

Agree, bash is completely unusable w/o this

>This is significant change for changelog, please edit the description accordingly.

Ok

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
I usually have 10s of tabs with bash opened and I would prefer shared history on every server.
So, when I click on random tab and press "Up", I will see full history.

You said that according to your experience, it's not convenient for clickhouse-client... Ok but I don't understand why.

**Comment by azat** [comment]
>I usually have 10s of tabs with bash opened and I would prefer shared history on every server.
>So, when I click on random tab and press "Up", I will see full history.

You mean inter-server history?

>You said that according to your experience, it's not convenient for clickhouse-client... Ok but I don't understand why.

I'm running multiple instances of clickhouse-client that are for different things, and when I write something in one, I get the same query in another, that is not what I want (for me the history should be saved but should not be reloaded after each query execution)

Looks like you don't need/want this, then how about add an option for this?

**Comment by alexey-milovidov** [comment]
> Looks like you don't need/want this, then how about add an option for this?

No, option is too complex, no one will use it.
Let's proceed with your variant.

**Comment by azat** [comment]
Looks like `pr-not-for-changelog` label should be removed?

**Comment by alexey-milovidov** [comment]
After this PR client started to be extremely slow in debug build (about 0.5 seconds per query) in interactive mode. Revert?

**Comment by azat** [comment]
>After this PR client started to be extremely slow in debug build (about 0.5 seconds per query) in interactive mode. Revert?

@alexey-milovidov let me fix it in another way

**Comment by azat** [comment]
@alexey-milovidov How about ClickHouse-Extras/replxx#10 ? (After I will submit PR that uses this flag)

**Pull request merged**
