### PR TITLE
X-ClickHouse-Exception-Code in HTTP Header

### PR DESCRIPTION
**Pull request by millb**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- New Feature

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Added `X-ClickHouse-Exception-Code` HTTP header that is set if exception was thrown before sending data. This implements #4971.
...

Detailed description / Documentation draft:

...

By adding documentation, you'll allow users to try your new feature immediately, not when someone else will have time to document it later. Documentation is necessary for all features that affect user experience in any way. You can add brief documentation draft above, or add documentation right into your patch as Markdown files in [docs](https://github.com/ClickHouse/ClickHouse/tree/master/docs) folder.

If you are doing this for the first time, it's recommended to read the lightweight [Contributing to ClickHouse Documentation](https://github.com/ClickHouse/ClickHouse/tree/master/docs/README.md) guide first.

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]

**Comment by qoega** [comment]
@BayoNet lets add a place in docs with all headers list and explanation? Do we have a ticket for that?

**Comment by den-crane** [comment]
Not sure it's working. It's working sometimes.

```
echo 'SELECT sleep(1) from numbers(10) settings max_block_size=1' | curl -vvv 'http://localhost:8123/?max_execution_time=5&timeout_before_checking_execution_speed=2' --data-binary @-

< Keep-Alive: timeout=3
< X-ClickHouse-Summary: {"read_rows":"0","read_bytes":"0","written_rows":"0","written_bytes":"0","total_rows_to_read":"0"}
<
0
0
Code: 160, e.displayText() = DB::Exception: Estimated query execution time (6.680003333333334 seconds) is too long. Maximum: 5. Estimated rows to process: 10: While executing Numbers (version 21.7.1.6993 (official build))
* Connection #0 to host localhost left intact

**Comment by alexey-milovidov** [comment]
Let's simply revert this feature and forget that it existed?

**Comment by alexey-milovidov** [comment]
@den-crane HTTP headers cannot be sent after data.
In your example you have the data
```
0
0
```

**Comment by den-crane** [comment]
Ah, OK. I see.

**Pull request merged**
