### PR TITLE
Fix mod incorrect result on integer conversion

### LINKED ISSUE #52111: Unexpected result of mod
(you don't have to strictly follow this form)

**Describe the unexpected behaviour**
Unexpected result of mod on following SQLs.

**How to reproduce**
master version can reproduce the result:
`SELECT number+10 as a, mod(-21, a), pmod(-21,a) from numbers(1);`
Got result:
image

`select mod(-21, 10), pmod(-21, 10)`
image

**Expected behavior**
`select mod(-21, 10), pmod(-21, 10)` The result is right.

**Error message and/or stacktrace**

**Additional context**

### PR DESCRIPTION
**Pull request by zhanglistar**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix https://github.com/ClickHouse/ClickHouse/issues/52111
In this issue, we got different results of `mod(-21, 10)`, see the following pictures.
image
image
The reason is that the field `number` of numbers table is UInt64, -21 have type Int8, and -21 % 10 will occur conversion following c++ standard rules, that is -21 will be converted a big UInt64 integer leading the wrong result. From the user perspective, this result is wrong.
The fix is: if we encounter two different sign of integers, we covert the unsigned integer to next size of signed integer, and do mod operation.
Besides, we should handle big integer than 64 bits, indeed it performances not well.

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by robot-ch-test-poll4** [comment]
This is an automated comment for commit 4413b61eae977154e2dd9664b076913c7c0b5ec5 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/52110/4413b61eae977154e2dd9664b076913c7c0b5ec5/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Comment by alexey-milovidov** [comment]
The changelog entry is incomplete - it does not give a proper explanation to the user about what this PR has fixed.

**Comment by zhanglistar** [comment]
> The changelog entry is incomplete - it does not give a proper explanation to the user about what this PR has fixed.

@alexey-milovidov Proper explanation has been added. Please review.

**Comment by alexey-milovidov** [comment]
@zhanglistar The implementation is good. Let's update the test, and we can merge it.

**Comment by alexey-milovidov** [comment]
Also, we will mark it as a backward incompatible change just in case.

**Comment by alexey-milovidov** [comment]
Let's update the test.

**Comment by alexey-milovidov** [comment]
@zhanglistar Please update the test.

**Comment by zhanglistar** [comment]
@alexey-milovidov Sorry for late reply, I will do it now.

**Comment by alexey-milovidov** [comment]
The CI said that the test did not fail on the previous version.

**Comment by zhanglistar** [comment]
@alexey-milovidov I think that it's by design not a real bug, and fix may incur more complicate code and time. The SQL author needs to know what he is doing, so I close this PR.

**Pull request closed without merging**
