### PR TITLE
Remove obsolete `no-upgrade-check` tag

### PR DESCRIPTION
**Pull request by tavplubix**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

This tag became useless after https://github.com/ClickHouse/ClickHouse/pull/44879 because Upgrade check takes tests from the old branch

It's a bit confusing: https://github.com/ClickHouse/ClickHouse/pull/52892

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]

**Comment by tavplubix** [comment]
> So we want to add a tag no-upgrade-check to the test in previous release branch

There are no good reasons to want this (like for `no-stress` label). And if we really need to disable some test because it's broken, then we can add `disabled` or `no-debug, no-*san` labels.

We should not have merged the PR that introduced the compatibility issue (or at least should have reverted it immediately).

Another issue with `no-upgrade-check` is that we should remove that label from old tests after releasing a new version, but we never do it.

**Comment by KochetovNicolai** [comment]
Using `disabled` instead of `no-upgrade-check` is almost ok, except maybe we want to run the test anyway in normal checks (in release).

> Another issue with no-upgrade-check is that we should remove that label from old tests after releasing a new version, but we never do it.

Yes, it should be allowed only in release branches. Maybe we can fail a test in pr and master workflow if it has such a tag.

**Comment by tavplubix** [comment]
> Using disabled instead of no-upgrade-check is almost ok, except maybe we want to run the test anyway in normal checks (in release).

Yes, that's exactly why I also suggested `no-debug, no-*san`

**Comment by Avogar** [comment]
Adding any tag still requires to make a patch release to apply it in upgrade check. So the suggestion to use tests/builds from latest commit from release branch with builds is still valid

**Comment by tavplubix** [comment]
The first approach will not work. We backport fixes for crashes quite often, so release branches may contain some recently backported tests that reproduce a crash. And the latest release doesn't contain the corresponding patches yet. So we cannot use tests that are newer than server

**Comment by KochetovNicolai** [comment]
> The first approach will not work. 

What you mentioned is about point 2.
But it looks ok to use the last commit which has build. At least we won't wait for a new stable release, only for a new build.

**Comment by tavplubix** [comment]
Stateless tests flaky check (asan) - Test runs too long - OK

**Pull request merged**
