### PR TITLE
Update zlib-ng from 2.0.2 to 2.1.7

### LINKED ISSUE #63319: `zlib deflate failed, output buffer too small` error when writing a Parquet + GZIP file into S3 using the S3 table function
> Please make sure that the version you're using is still supported (you can find the list [here](https://github.com/ClickHouse/ClickHouse/blob/master/SECURITY.md#scope-and-supported-versions)).

> You have to provide the following information whenever possible.

Some of our customers have gotten the following error while trying to write a GZIP-compressed Parquet file to S3 using the S3 table function:

```
Code: 1002. DB::Exception: Error while writing a table: IOError: zlib deflate failed, output buffer too small. () (version 24.2.1.2248 (official build))
```

Multiple runs of the same query still produce the error.

**Does it reproduce on the most recent release?**

Have tested it in 24.2, working on a reproducer to try and test it against the latest release

**How to reproduce**

The query has the following shape:

```
INSERT INTO FUNCTION s3('https://test-sinks.s3.eu-west-3.amazonaws.com/rep_deflate/myfile.parquet', '[REDACTED]', '[REDACTED]', 'Parquet')
SELECT *
FROM <my_db>.<my_table AS t
SETTINGS output_format_parquet_compression_method = 'gzip'
```

Unfortunately so far we've been only able to reproduce it with queries against customer data that we can't provide, I'm trying to come up with a minimum reproducer that I can share

**Expected behavior**

The export works.

**Error message and/or stacktrace**

```
exception:                             Code: 1002. DB::Exception: Error while writing a table: IOError: zlib deflate failed, output buffer too small. () (version 24.2.1.2248 (official build))
stack_trace:                           0. ./build_docker/./src/Common/Exception.cpp:96: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000cf5565b
1. DB::Exception::Exception<String>(int, FormatStringHelperImpl<std::type_identity<String>::type>, String&&) @ 0x00000000078c7743
2. ./build_docker/./src/Processors/Formats/Impl/ParquetBlockOutputFormat.cpp:0: DB::ParquetBlockOutputFormat::writeRowGroup(std::vector<DB::Chunk, std::allocator<DB::Chunk>>) @ 0x00000000131c8b53
3. ./build_docker/./src/Processors/Formats/Impl/ParquetBlockOutputFormat.cpp:0: DB::ParquetBlockOutputFormat::consume(DB::Chunk) @ 0x00000000131c4d88
4. ./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:701: DB::IOutputFormat::write(DB::Block const&) @ 0x000000001303ebbf
5. ./build_docker/./src/Storages/StorageS3.cpp:0: DB::StorageS3Sink::consume(DB::Chunk) @ 0x0000000012685b57
6. ./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:701: DB::PartitionedSink::consume(DB::Chunk) @ 0x000000001236e7df
7. ./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:701: DB::SinkToStorage::onConsume(DB::Chunk) @ 0x000000001336d802
8. ./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:701: void std::__function::__policy_invoker<void ()>::__call_impl<std::__function::__default_alloc_func<DB::ExceptionKeepingTransform::work()::$_1, void ()>>(std::__function::__policy_storage const*) @ 0x000000001329dd2b
9. ./contrib/llvm-project/libcxx/include/__functional/function.h:848: ? @ 0x000000001329da3c
10. ./contrib/llvm-project/libcxx/include/__functional/function.h:818: ? @ 0x000000001329d113
11. ./build_docker/./src/Processors/Executors/ExecutionThreadContext.cpp:0: DB::ExecutionThreadContext::executeTask() @ 0x0000000013031afa
12. ./build_docker/./src/Processors/Executors/PipelineExecutor.cpp:273: DB::PipelineExecutor::executeStepImpl(unsigned long, std::atomic<bool>*) @ 0x0000000013028550
13. ./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:833: void std::__function::__policy_invoker<void ()>::__call_impl<std::__function::__default_alloc_func<DB::PipelineExecutor::spawnThreads()::$_0, void ()>>(std::__function::__policy_storage const*) @ 0x0000000013029638
14. ./base/base/../base/wide_integer_impl.h:810: ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::worker(std::__list_iterator<ThreadFromGlobalPoolImpl<false>, void*>) @ 0x000000000cff84e1
15. ./build_docker/./src/Common/ThreadPool.cpp:0: void std::__function::__policy_invoker<void ()>::__call_impl<std::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>(void&&)::'lambda'(), void ()>>(std::__function::__policy_storage const*) @ 0x000000000cffbd1a
16. ./base/base/../base/wide_integer_impl.h:810: void* std::__thread_proxy[abi:v15000]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void ThreadPoolImpl<std::thread>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>>(void*) @ 0x000000000cffab1e
17. ? @ 0x000071b496e94ac3
18. ? @ 0x000071b496f26850
```

**Additional context**

The error seems to be coming from zlib and there is very little information about it on the internet. Checking the code it seems that zlib does a wrong estimation of the buffer size to allocate? The only thing I've been able to find is this bug report from [Apache Arrow](https://github.com/apache/arrow/issues/2756) where the problem seems to be caused by an [older version of zlib](https://github.com/apache/arrow/issues/2756#issuecomment-429688129). Maybe it's a matter of upgrading?

### PR DESCRIPTION
**Pull request by al13n321**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Fixes https://github.com/ClickHouse/ClickHouse/issues/63319

https://github.com/ClickHouse/zlib-ng/pull/17 should be merged first

The actual fix appears to be https://github.com/zlib-ng/zlib-ng/pull/1071 - it simplifies the compressed-size-upper-bound estimate to stop trying to be clever and tight (the bug was that it was underestimated), and just overestimates by ~14%. Instead of cherry-picking it, this PR updates the whole library because I assume that's better (?). (From resolving conflicts I got the impression that there was some reasonable cleanup refactoring done there, so I'm guessing this library has not peaked yet!)

### CODE REVIEW

**Comment by robot-ch-test-poll4** [comment]
*This is an automated comment for commit 2f84cc7ac50d29dc79d3d450a67c085d7db10b70 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/64489/2f84cc7ac50d29dc79d3d450a67c085d7db10b70/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>A Sync</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>⏳ pending</td></tr>
<tbody>
</table>
<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

**Comment by rschu1ze** [comment]
PPC and FreeBSD builds are broken.

Side note and not blocking this PR: our zlib-ng fork, in particular branch `clickhouse-new` ([here](https://github.com/ClickHouse/zlib-ng/commits/clickhouse-new/)) has a quite messy history. We actually have a guideline for the integration of 3rd party libraries (I just updated it here: https://github.com/ClickHouse/ClickHouse/pull/64573). To clean this up, it is perhaps an option to create a branch `clickhouse/2.1.6` and pick the existing patches into it? To lower maintenance burden, we might also want to upstream these patches.

**Review by rschu1ze — APPROVED** [review]

**Comment by al13n321** [comment]
New contrib update PR: https://github.com/ClickHouse/zlib-ng/pull/17 that cherry-picks our patches onto a clean upstream. This PR points to that now.

**Comment by al13n321** [comment]
Waiting on https://github.com/ClickHouse/zlib-ng/pull/18 , plz review.

**Comment by rschu1ze** [comment]
> New contrib update PR: https://github.com/ClickHouse/zlib-ng/pull/17 that cherry-picks our patches onto a clean upstream. This PR points to that now.

Kind of unrelated to this PR: I count > 10 custom patches in zlib, going back to 2021. Sounds odd to me, we should contribute them back to upstream instead of dragging them from update to update ...

**Review by rschu1ze — APPROVED** [review]

**Pull request merged**
