### PR TITLE
Add settings to check hyperscan regexp length.

### PR DESCRIPTION
**Pull request by amosbird**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Add two settings `max_hyperscan_regexp_length` and `max_hyperscan_regexp_total_length` to prevent huge regexp being used in hyperscan related functions, such as `multiMatchAny`.

Detailed description / Documentation draft:
.

### CODE REVIEW

**Comment by amosbird** [comment]
```
2021-08-07 08:42:33 Code: 48. DB::Exception: Received from localhost:9000. DB::Exception: multi-search all indices is not implemented when hyperscan is off (is it x86 processor?): While processing multiMatchAllIndices('123', ['1']). (NOT_IMPLEMENTED)
```
But why only `multiMatchAllIndices` fails.

**Comment by alexey-milovidov** [comment]
Fast test does not build ClickHouse with Hyperscan.

**Comment by alexey-milovidov** [comment]
LGTM.

Please add the exception to docker/test/fasttest/run.sh

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
@mergifyio update

**Comment by gyuton** [comment]
Internal documentation ticket: DOCSUP-14089.

**Pull request merged**
