### PR TITLE
Reload stacktrace cache when symbol is reloaded.

### PR DESCRIPTION
**Pull request by amosbird**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Reload stacktrace cache when symbol is reloaded.

Detailed description / Documentation draft:
.

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]

**Review by alexey-milovidov — CHANGES_REQUESTED** [review]
The code is strange. We reuse `toStringStatic` function for two different purposes.

**Comment by alexey-milovidov** [comment]
Name clash:

```
Aug 28 04:16:54 ../src/Common/SymbolIndex.cpp: In static member function 'static void DB::SymbolIndex::reload()':
Aug 28 04:16:54 ../src/Common/SymbolIndex.cpp:478:15: error: the address of 'static void DB::SymbolIndex::reload()' will never be NULL [-Werror=address]
Aug 28 04:16:54   478 |     if (reload)
Aug 28 04:16:54       |               ^
```

**Comment by alexey-milovidov** [comment]
@mergifyio update

**Review by alexey-milovidov — APPROVED** [review]
Alright...

**Review by kitaisreal — APPROVED** [review]

**Pull request merged**
