### PR TITLE
Tests: Convert numeric to symbolic error codes

### PR DESCRIPTION
**Pull request by rschu1ze**
Numeric error codes in tests are an annoyance and they procreate via copy-paste. This PR converts them to human-readable error codes.

Generated with below script:

<details>

```sh
#!/bin/bash

declare -A mp
mp[0]=OK
mp[1]=UNSUPPORTED_METHOD
mp[2]=UNSUPPORTED_PARAMETER
... # <-- dump all of src/Common/ErrorCodes.cpp here

for i in "${!mp[@]}"
do
 echo "$i ${mp[$i]}"

 sed -i "s/\bserverError $i\b/serverError ${mp[$i]}/g" tests/queries/0_stateless/*.{sql,reference}
done
```

</details>

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by robot-ch-test-poll3** [comment]
*This is an automated comment for commit 4357d0b6c38c453d412ad9ccd5eddfb071cd5ed0 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/64635/4357d0b6c38c453d412ad9ccd5eddfb071cd5ed0/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>A Sync</td><td>If it fails, ask a maintainer for help</td><td>⏳ pending</td></tr>
<tbody>
</table>
<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

**Review by jkartseva — APPROVED** [review]
Same issue with stateful tests
```
$ pwd
/home/ubuntu/src/jkartseva/ClickHouse/tests/queries/1_stateful
$ find . -name '*.sql' -o -name '*.sh' | xargs egrep 'serverError [0-9]+'
./00175_counting_resources_in_subqueries.sql:SELECT 1 = (SELECT count() FROM test.hits WHERE NOT ignore(AdvEngineID)); -- { serverError 158 }
./00175_counting_resources_in_subqueries.sql:SELECT 1 IN (SELECT count() FROM test.hits WHERE NOT ignore(AdvEngineID)); -- { serverError 158 }
./00175_counting_resources_in_subqueries.sql:SELECT count() IN (SELECT count() FROM test.hits WHERE NOT ignore(AdvEngineID)) FROM test.hits WHERE NOT ignore(AdvEngineID); -- { serverError 158 }
./00175_counting_resources_in_subqueries.sql:SELECT count() FROM test.hits WHERE CounterID > (SELECT count() FROM test.hits WHERE NOT ignore(AdvEngineID)); -- { serverError 158 }
./00175_counting_resources_in_subqueries.sql:SELECT count() FROM test.hits WHERE CounterID < (SELECT count() FROM test.hits WHERE NOT ignore(AdvEngineID)); -- { serverError 158 }
./00091_prewhere_two_conditions.sql:SELECT uniq(URL) FROM test.hits WHERE toTimeZone(EventTime, 'Asia/Dubai') >= '2014-03-20 00:00:00' AND toTimeZone(EventTime, 'Asia/Dubai') < '2014-03-21 00:00:00'; -- { serverError 307 }
./00091_prewhere_two_conditions.sql:SELECT uniq(URL) FROM test.hits WHERE toTimeZone(EventTime, 'Asia/Dubai') >= '2014-03-20 00:00:00' AND URL != '' AND toTimeZone(EventTime, 'Asia/Dubai') < '2014-03-21 00:00:00'; -- { serverError 307 }
./00091_prewhere_two_conditions.sql:SELECT uniq(URL) FROM test.hits PREWHERE toTimeZone(EventTime, 'Asia/Dubai') >= '2014-03-20 00:00:00' AND URL != '' AND toTimeZone(EventTime, 'Asia/Dubai') < '2014-03-21 00:00:00'; -- { serverError 307 }
```

**Comment by jkartseva** [comment]
Also, 'clientError', e.g.:
```
./0_stateless/01715_table_function_view_fix.sql:SELECT view(SELECT 1); -- { clientError 62 }
./0_stateless/01715_tuple_insert_null_as_default.sql:INSERT INTO test_tuple VALUES ((NULL, 2)); -- { clientError 53 }
./0_stateless/01715_tuple_insert_null_as_default.sql:INSERT INTO test_tuple_nested_in_array VALUES ([(NULL, 1)]); -- { clientError 53 }
./0_stateless/01715_tuple_insert_null_as_default.sql:INSERT INTO test_tuple_nested_in_array_nested_in_tuple VALUES ( (NULL, [(NULL, 1)]) ); -- { clientError 53 }
./0_stateless/01715_tuple_insert_null_as_default.sql:INSERT INTO test_tuple_nested_in_map VALUES (map('test', (NULL, 1))); -- { clientError 53 }
./0_stateless/01715_tuple_insert_null_as_default.sql:INSERT INTO test_tuple_nested_in_map_nested_in_tuple VALUES ( (NULL, map('test', (NULL, 1))) ); -- { clientError 53 }
./0_stateless/01825_type_json_field.sql:INSERT INTO t_json_field VALUES (6, map(1, 2, 3, 4)); -- { clientError 53 }
```

**Comment by rschu1ze** [comment]
ClickHouse Stateless Tests Flaky Check (asan): `02454_disable_mergetree_with_lightweight_delete_column` and `01825_type_json_1` are flaky (error removing leftovers on disk). This is generally unrelated to this PR. I think the issue is caused by the way the flaky check works: It `checks if new added or modified tests are flaky [...]` (from https://github.com/ClickHouse/ClickHouse/pull/64635#issuecomment-2139458546) - The flaky-ness must have existed before this PR but nobody noticed.

A sync: Green

Lgtm, forcing MergeableCheck green.

**Comment by rschu1ze** [comment]
@jkartseva Thanks - I pushed follow-up for the places you noted [here](https://github.com/ClickHouse/ClickHouse/pull/64670).

**Pull request merged**
