### PR TITLE
Fixed parallel writes for S3 does not work

### PR DESCRIPTION
**Pull request by xiedeyantu**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in official stable or prestable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix checking whether s3 storage support parallel writes. It resulted in s3 parallel writes not working.

### CODE REVIEW

**Comment by kssenii** [comment]
> 02228_merge_tree_insert_memory_usage

Possibly related test failure, let's rerun the tests

**Comment by kssenii** [comment]
@Mergifyio update

**Comment by azat** [comment]
@xiedeyantu can you please write changelog entry in user terms? i.e. what changed for the user (AFAIU previously parallel writes for S3 does not work).

**Comment by xiedeyantu** [comment]
> @xiedeyantu can you please write changelog entry in user terms? i.e. what changed for the user (AFAIU previously parallel writes for S3 does not work).

ok, I will finish it.

**Comment by kssenii** [comment]
> Integration tests

```
>           fd_event_list = self._selector.poll(timeout)
E           Failed: Timeout >900.0s

/usr/lib/python3.8/selectors.py:415: Failed
```

**Pull request merged**
