### PR TITLE
Update clickhouse-test help section

### PR DESCRIPTION
**Pull request by xogoodnow**
Fixed a couple of linguistic errors.

Changelog category (leave one):

Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
Thank you! The current forms are also grammatically correct, so no changes are needed.

**Comment by xogoodnow** [comment]
Hi @alexey-milovidov,

I do not believe this is worth your time :), but in any case, the changes are valid.
"if you use not default ports" and "after current test finished" are  not correct.

Cheers

**Comment by robot-ch-test-poll** [comment]
*This is an automated comment for commit c86497831ec20f49dc5c0de69005415df0b68c22 with description of existing statuses. It's updated for the latest CI running*

[❌ Click here](https://s3.amazonaws.com/clickhouse-test-reports/63663/c86497831ec20f49dc5c0de69005415df0b68c22/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>❌ failure</td></tr>
<tbody>
</table>

**Comment by alexey-milovidov** [comment]
For my own education, if we write "if you use non-default ports" instead of "if you use not default ports," - will it be better?

**Comment by xogoodnow** [comment]
Hi @alexey-milovidov,
IMHO, 
"if you use non-default ports" is perfectly fine but 
"if you use not default ports" is grammatically incorrect.

Thank you for your time.
Cheers

**Pull request merged**
