### PR TITLE
Simplify binary locating in clickhouse-test

### PR DESCRIPTION
**Pull request by azat**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Since #39520 it can be simplified. Plus it fixes non descriptive error when there is no binary in PATH after #45283

### CODE REVIEW

**Review by vdimir — APPROVED** [review]
Why do we need `--client` option actually?

> `Path to clickhouse-client, this option is useless`


It's used only in couple of queries in clickhouse-test itself. Can't it be replaced with the binary?

**Comment by azat** [comment]
>Why do we need --client option actually?

Indeed, it can be removed. Rebased.

But I left the ability to use `clickhouse client` (but `clickhouse-client` will be preferable), since it is useful if you download a binary from CI (to avoid requiring creating symlinks)

**Comment by vdimir** [comment]
The only concern is that we can break someone's workflow or scripts if we remove options. I assumed we could leave them but not use values and print warnings.

**Comment by azat** [comment]
>The only concern is that we can break someone's workflow or scripts if we remove options. I assumed we could leave them but not use values and print warnings.

I doubt that someone uses it, and for me this option is pretty internal, and it is better to remove/break such things then keeping extra few lines of code for this.

But if you still feel that it is better to leave it, then OK, I can rebase (though you already did this...)

**Review by vdimir — APPROVED** [review]

**Review by alexey-milovidov — APPROVED** [review]

**Pull request merged**
