### PR TITLE
Cherry pick #71308 to 24.3: Added missing unescaping in named collections names. 

### PR DESCRIPTION
**Pull request by robot-clickhouse-ci-1**
Original pull-request #71308

This pull-request is a first step of an automated backporting.
It contains changes similar to calling `git cherry-pick` locally.
If you intend to continue backporting the changes, then resolve all conflicts if any.
Otherwise, if you do not want to backport them, then just close this pull-request.

The check results does not matter at this step - you can safely ignore them.

### Note

This pull-request will be merged automatically. Please, **do not merge it manually** (but if you accidentally did, nothing bad will happen).

#### If the PR was manually reopened after being closed

If this PR is stuck (i.e. not automatically merged after one day), check https://github.com/ClickHouse/ClickHouse/pull/71308 for `pr-backports-created` *label* and delete it.

Manually merging will do nothing. The `pr-backports-created` *label* prevents the original PR https://github.com/ClickHouse/ClickHouse/pull/71308 from being processed.

#### If the conflicts were resolved in a wrong way

If this cherry-pick PR is completely screwed by a wrong conflicts resolution, and you want to recreate it:

- delete the `pr-cherrypick` label from the PR
- delete this branch from the repository

You also need to check the original PR https://github.com/ClickHouse/ClickHouse/pull/71308 for `pr-backports-created`, and delete if it's presented there

### CODE REVIEW

**Comment by kssenii** [comment]
> Actually I managed to do it locally but I don't have access to push to pr. How can I send you the changes?

that would be helpful, thank you, may be just attach a git diff via [pastila](https://pastila.nl/) ?

**Comment by MikhailBurdukov** [comment]
https://pastila.nl/?008eaac6/4ab2c7c11e4e1b9569554e1fe011b9f9#FX9hxiyyNEej7HZuy7DRsA==

**Comment by robot-clickhouse-ci-2** [comment]
Dear @kssenii, the PR is not updated for 1d24h19m41s. Please, either resolve the conflicts, or close it to finish the backport process of #71308

**Comment by robot-ch-test-poll** [comment]
Dear @kssenii, the PR is not updated for 1d25h0m4s. Please, either resolve the conflicts, or close it to finish the backport process of #71308

**Comment by robot-ch-test-poll** [comment]
Dear @kssenii, the PR is not updated for 1d24h56m49s. Please, either resolve the conflicts, or close it to finish the backport process of #71308

**Comment by robot-ch-test-poll3** [comment]
Dear @kssenii, the PR is not updated for 1d24h45m6s. Please, either resolve the conflicts, or close it to finish the backport process of #71308

**Comment by Felixoid** [comment]
jfyi, it conflicts

**Comment by MikhailBurdukov** [comment]
@kssenii Ping

**Comment by kssenii** [comment]
Sorry, will do on Monday (currently on a short vacation)

**Comment by Felixoid** [comment]
Push it to https://github.com/ClickHouse/ClickHouse/pull/71765, please

**Pull request closed without merging**
