### PR TITLE
Analyzer Planner enable by default

### PR DESCRIPTION
**Pull request by kitaisreal**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by jrdi** [comment]
@kitaisreal do you think we can somehow help you here? We can start testing this branch in our CI environment, and see what raises but before wanted to make sure it's not too early to start doing so. What do you think?

btw, do you know if PRs are generating Docker images for each commit or something like this?

**Comment by jrdi** [comment]
We started running this branch in our CI environment, first error that it's raising is that queries to `system.zookeeper` are failing as follows:

```sql
SELECT *
FROM system.zookeeper
WHERE path = 'path'

Query id: 24da186e-f8ab-437f-822e-40430cc2f3ae


0 rows in set. Elapsed: 0.187 sec.

Received exception from server (version 23.2.1):
Code: 36. DB::Exception: Received from localhost:9000. DB::Exception: SELECT from system.zookeeper table must contain condition like path = 'path' or path IN ('path1','path2'...) or path IN (subquery) in WHERE clause unless `set allow_unrestricted_reads_from_keeper = 'true'`.. (BAD_ARGUMENTS)
```

When deactivating the analyzer everything works fine:

```sql
SELECT *
FROM system.zookeeper
WHERE path = 'path'
SETTINGS allow_experimental_analyzer = 0

Query id: 38167da5-23f8-4cd5-8be6-55a2b71fbfc1

Ok.

0 rows in set. Elapsed: 0.002 sec.
```

**Comment by robot-clickhouse-ci-1** [comment]
This is an automated comment for commit 6997066c97370a5ee1cb00eeace69d42945f1d53 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/45461/6997066c97370a5ee1cb00eeace69d42945f1d53/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Comment by alexey-milovidov** [comment]
We did it.

**Comment by handgunman** [comment]
There's a problem with the analyzer:
https://fiddle.clickhouse.com/268bdedc-33d9-43ea-b78a-68957a9a709e
https://github.com/ClickHouse/ClickHouse/issues/62820

**Pull request closed without merging**
