### PR TITLE
Add function runningConcurrency()

### PR DESCRIPTION
**Pull request by depressed-pho**
Given a series of beginning time and ending time of events, this function calculates concurrency of the events at each of the data point, that is, the beginning time.

Changelog category:
- New Feature

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
- Included in the pull request

Detailed description / Documentation draft:
- Included in the pull request

```text
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

### CODE REVIEW

**Comment by nikitamikhaylov** [comment]
@depressed-pho I don't understand what this functions returns given two dates. Could you please explain more properly?

**Comment by depressed-pho** [comment]
The input is a series of time span of some events, and the function counts how many events concurrently exists at each data point.

For simplicity we represent time as integers in the following diagram. I hope this helps:

```text
time        1  2  3  4  5  6  7  8  9
            <------->                   First input row
               <------------->          Second
                  <------->             Third
                                 <->    Fourth
concurrency |1 |2 |3 |2 |2 |1 |0 |1 |0
```

beginTime|endTime|runningConcurrency(beginTime, endTime)
---------|-------|--------------------------------------
1        |4      |1
2        |7      |2
3        |6      |3
8        |9      |1

**Comment by filimonov** [comment]
`maxIntersections` ? https://github.com/ClickHouse/ClickHouse/pull/2012 ?

**Comment by depressed-pho** [comment]
> `maxIntersections` ? #2012 ?

To be honest I didn't know `maxIntersections` has existed because it was undocumented and was only mentioned in the changelog. `maxIntersections` is an aggregate function which finds a single data point whose concurrency (the number of intersections) becomes the maximum. On the other hand, the proposed `runningConcurrency` returns concurrency for each data point without aggregating them.

**Comment by depressed-pho** [comment]
Amended the patch so that the function rejects Nullable arguments.

**Comment by depressed-pho** [comment]
Changed the error code. I didn't know LOGICAL_ERROR was handled in a special manner.

**Comment by depressed-pho** [comment]
Fixed the code so that the function at least doesn't crash when a constant column is passed.

**Comment by depressed-pho** [comment]
Now AST fuzzers are failing due to seemingly unrelated parts of the code base.

**Comment by nikitamikhaylov** [comment]
@depressed-pho For you to know we have some prototype of window functions at the moment.  Your function could be rewritten as following, for example.

```sql

select * from (
  select sum(_ut_2) over (order by _ut_1 ASC), _ut_2
  from (
     select untuple(arrayJoin([(begin, 1), (end, -1)]))
     from running_concurrency_test
  )
  order by _ut_1 ASC
)
where _ut_2 = 1
```

**Review by nikitamikhaylov — APPROVED** [review]

**Comment by nikitamikhaylov** [comment]
`ThreadSanitizer: thread leak` in Stress test is a known false-positive

**Pull request merged**
