### PR TITLE
Hipster's HTML

### PR DESCRIPTION
**Pull request by alexey-milovidov**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Slight improvement in the testing infrastructure.

### CODE REVIEW

**Comment by qoega** [comment]
1) Something new #44975
2) @Felixoid can you check that we did not mess up with the url and it was a problem with GH?
```
INFO:root:Getting URL with 5 tries and sleep 3 in between: https://api.github.com/repos/ClickHouse/ClickHouse/actions/runs/3852481060/jobs?per_page=100&page=1
INFO:root:Exception '502 Server Error: Bad Gateway for url: https://api.github.com/repos/ClickHouse/ClickHouse/actions/runs/3852481060/jobs?per_page=100&page=1' while getting, retry 1
INFO:root:Exception '502 Server Error: Bad Gateway for url: https://api.github.com/repos/ClickHouse/ClickHouse/actions/runs/3852481060/jobs?per_page=100&page=1' while getting, retry 2
INFO:root:Exception '502 Server Error: Bad Gateway for url: https://api.github.com/repos/ClickHouse/ClickHouse/actions/runs/3852481060/jobs?per_page=100&page=1' while getting, retry 3
INFO:root:Exception '502 Server Error: Bad Gateway for url: https://api.github.com/repos/ClickHouse/ClickHouse/actions/runs/3852481060/jobs?per_page=100&page=1' while getting, retry 4
Traceback (most recent call last):
  File "/home/ubuntu/actions-runner/_work/_temp/stateful_debug/ClickHouse/tests/ci/functional_test_check.py", line 338, in <module>
    report_url = upload_results(
  File "/home/ubuntu/actions-runner/_work/_temp/stateful_debug/ClickHouse/tests/ci/upload_result_helper.py", line 91, in upload_results
    GITHUB_JOB_URL(),
  File "/home/ubuntu/actions-runner/_work/_temp/stateful_debug/ClickHouse/tests/ci/env_helper.py", line 70, in GITHUB_JOB_URL
    GITHUB_JOB_ID()
  File "/home/ubuntu/actions-runner/_work/_temp/stateful_debug/ClickHouse/tests/ci/env_helper.py", line 47, in GITHUB_JOB_ID
    response = get_with_retries(
  File "/home/ubuntu/actions-runner/_work/_temp/stateful_debug/ClickHouse/tests/ci/build_download_helper.py", line 39, in get_with_retries
    raise Exception(exc)
Exception: 502 Server Error: Bad Gateway for url: https://api.github.com/repos/ClickHouse/ClickHouse/actions/runs/3852481060/jobs?per_page=100&page=1
INFO:root:Update Mergeable Check by Stateful tests (asan)
Error: Process completed with exit code 1.
```

**Comment by qoega** [comment]
Report for AST Fuzzer is unchanged

**Review by alesapin — COMMENTED** [review]
Please, make it optional🙏

**Comment by alexey-milovidov** [comment]
I also always prefer light themes, but many people prefer dark ones. I've made it optional.

**Comment by alexey-milovidov** [comment]
The HTML for AST Fuzzer will be unchanged - it uses a copy-paste methodology, and it will remain unique.

**Comment by Felixoid** [comment]
https://api.github.com/repos/ClickHouse/ClickHouse/actions/runs/3852481060/jobs?per_page=100&page=1

the url is correct and working. It's definitely on the GH side

I like the new reports BTW!

**Pull request merged**
