### PR TITLE
Fix join_use_nulls (by allowing ColumnConst to be Nullable)

### PR DESCRIPTION
**Pull request by azat**
Changelog category (leave one):
- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix join_use_nulls (by allowing ColumnConst to be Nullable)

Detailed description / Documentation draft:
stress tests founds [1]:

  [1]: https://clickhouse-test-reports.s3.yandex.net/0/7803a27e9931e055c6f19c280376001fa599c202/stress_test_(address).html#fail1

Closes: #27485
Closes: #27486
Fixes: #27217
Cc: @vdimir
Cc: @alexey-milovidov

*NOTE: worth adding `no-backport` since original PR hadn't landed in any official stable release yet*

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
How this change is viable?
We allow ColumnConst to contain ColumnNullable but not vice versa.
If we do this change - maybe it will introduce complications in other places.

**Comment by vdimir** [comment]
We can convert consts to full column in join https://github.com/ClickHouse/ClickHouse/pull/27516

**Comment by azat** [comment]
>We can convert consts to full column in join #27516

@vdimir That was my first idea, but then I though that this should be more generic (since ColumnNullable converts to full column if const already)

**Comment by azat** [comment]
Closed in favor of #27516

**Comment by alexey-milovidov** [comment]
@KochetovNicolai said:

> Нет, хранить ColumnConst внутри ColumnNullable категорически нельзя. У нас на это завязано столько кода, что невозможно будет отследить.
Да и идеалогически это не очень хорошо.

**Pull request closed without merging**
