### PR TITLE
Better logging in replication queue, fix flacky test

### PR DESCRIPTION
**Pull request by tavplubix**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Detailed description / Documentation draft:
Add queue entry name to logs, so it will be possible to grep log messages.
Drop tables in `00993_system_parts_race_condition_drop_zookeeper` concurrently to avoid situation, when there is the last active replica with a lot of entries in queue, but queue task sleeps due to many `part is lost forever` errors, and some query waits for tasks in queue to disappear.

### CODE REVIEW

**Review by alesapin — APPROVED** [review]
Much better logging :+1: 
But I don't understand why test fix helps. We will still have a replica that will dropped last?

**Comment by tavplubix** [comment]
> But I don't understand why test fix helps. We will still have a replica that will dropped last?

All replicas will become inactive, so do not wait for the last one to execute some queue entry, because the last replica will be dropped soon too.

**Comment by tavplubix** [comment]
```
Functional stateless tests (release, DatabaseOrdinary) - 01079_parallel_alter_add_drop_column_zookeeper - Timeout
Functional stateless tests (release, wide parts enabled) - 01079_parallel_alter_modify_zookeeper - Timeout
```
:(

Have no ideas of what is happening

**Comment by tavplubix** [comment]
Functional stateless tests - 00840_long_concurrent_select_and_drop_deadlock - known issue

**Pull request merged**
