### PR TITLE
tests: fix log_comment (extra quotes)

### PR DESCRIPTION
**Pull request by azat**
Cherry-pick: 9a297ce3b604561ebc97507fdc99bfda5df939db

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by azat** [comment]
@alesapin why you marked this as draft?

**Comment by azat** [comment]
Ok, I see, 01175_distributed_ddl_output_mode_long fails, fixed.

**Comment by azat** [comment]
@alesapin can you take a look? (this is pretty simple patch)

**Review by alesapin — APPROVED** [review]

**Comment by alesapin** [comment]
Msan fixed in https://github.com/ClickHouse/ClickHouse/pull/38117

**Comment by alesapin** [comment]
Tidy and stress look unrelated

**Pull request merged**
