### PR TITLE
Fix compatibility in replication

### LINKED ISSUE #9645: Broken replication after upgrading to  20.3.2.1
**Describe the bug or unexpected behaviour**
Broken replication after upgrading to  20.3.2.1

**How to reproduce**
* Which ClickHouse server version to use
`20.1.6.30` -> `20.3.2.1`

* `CREATE TABLE` statements for all tables involved
in version `20.1.6.30` (or before)
``` sql
create table tbl1 on cluster cluster (`eventDate` Date, id String )
ENGINE = ReplicatedMergeTree('/clickhouse/tables/{shard}/tbl1', '{replica}') PARTITION BY  tuple() ORDER BY (eventDate)
insert into tbl1 values ('2020-02-13', '1'), ('2020-02-13', '2');
alter table tbl1 delete where id ='2'
```
upgrade version to `20.3.2.1`. Look at err.logs. 

**Error message and/or stacktrace**
```
2020.03.13 14:47:28.183757 [ 4584 ] {} <Information> default.tbl1 (ReplicatedMergeTreeQueue): Loading 1 mutation entries: 0000000000 - 0000000000
2020.03.13 14:47:28.250097 [ 4584 ] {} <Error> default.tbl1 (ReplicatedMergeTreeRestartingThread): void DB::ReplicatedMergeTreeRestartingThread::run(): Code: 27, e.displayText() = DB::Exception: Cannot parse input: expected \nalter version:  at end of stream., Stack trace (when copying this message, always include the lines below):

0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x10278d1c in /usr/bin/clickhouse
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x8f02989 in /usr/bin/clickhouse
2. ? @ 0x8f3970b in /usr/bin/clickhouse
3. DB::assertString(char const*, DB::ReadBuffer&) @ 0x8f376fa in /usr/bin/clickhouse
4. DB::ReplicatedMergeTreeMutationEntry::parse(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >) @ 0xd8a3678 in /usr/bin/clickhouse
5. DB::ReplicatedMergeTreeQueue::updateMutations(std::__1::shared_ptr<zkutil::ZooKeeper>, std::__1::function<void (Coordination::WatchResponse const&)>) @ 0xd8cb131 in /usr/bin/clickhouse
6. DB::ReplicatedMergeTreeQueue::pullLogsToQueue(std::__1::shared_ptr<zkutil::ZooKeeper>, std::__1::function<void (Coordination::WatchResponse const&)>) @ 0xd8ccc5c in /usr/bin/clickhouse
7. DB::ReplicatedMergeTreeRestartingThread::tryStartup() @ 0xd8e90d8 in /usr/bin/clickhouse
8. DB::ReplicatedMergeTreeRestartingThread::run() @ 0xd8e99d8 in /usr/bin/clickhouse
9. DB::BackgroundSchedulePoolTaskInfo::execute() @ 0xce277c1 in /usr/bin/clickhouse
10. DB::BackgroundSchedulePool::threadFunction() @ 0xce27d9a in /usr/bin/clickhouse
11. ? @ 0xce27ed0 in /usr/bin/clickhouse
12. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x8f25b07 in /usr/bin/clickhouse
13. ? @ 0x8f2400f in /usr/bin/clickhouse
14. start_thread @ 0x76db in /lib/x86_64-linux-gnu/libpthread-2.27.so
15. clone @ 0x12188f in /lib/x86_64-linux-gnu/libc-2.27.so
 (version 20.3.2.1 (official build))
```

* Replication broken:

```sql
insert into tbl1 values ('2020-02-13', '3');
select count() from tbl1; 
-- 2
-- on replica:
select count() from tbl1
-- 1
```

### PR DESCRIPTION
**Pull request by alesapin**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix bug in a replication that doesn't allow replication to work if the user has executed mutations on the previous version. This fixes #9645.

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alesapin** [comment]
@alexey-milovidov With `format_version` update in log entry we became even more incompatible, than before. I can try to fix it without version update (with help of `checkString` like in MutationEntry), but the code will look strange because we have versions for this purpose. How we updated it from 3 to 4?

**Comment by alexey-milovidov** [comment]
> How we updated it from 3 to 4?

My guess is that the same issue has happeded but in 2017 people were not concerned about testing that downgrade is possible after upgrade.

**Comment by alexey-milovidov** [comment]
There is no way how it can be made compatible with old versions.
Theoretically, we can enable support for the new version of log entry and don't use it for half year. But it's not worth doing.

Instead, we can backport support for new version of log entry to a few older ClickHouse releases.

**Comment by alesapin** [comment]
Now it should be more compatible.

**Pull request merged**
