### PR TITLE
Custom default window frame for ntile function

### LINKED ISSUE #46763: NTILE is scary
**Describe the issue**

I can write this:
```
ntile(4) OVER (ORDER BY price DESC ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS quartile
```

But this does not work:
```
ntile(4) OVER (ORDER BY price DESC) AS quartile
```

While it works in MS SQL Server: https://learn.microsoft.com/en-us/sql/t-sql/functions/ntile-transact-sql?view=sql-server-ver16

### PR DESCRIPTION
**Pull request by vdimir**
### Changelog category (leave one):

- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Allow using `ntile` window function without explicit window frame definition: `ntile(3) OVER (ORDER BY a)`, close https://github.com/ClickHouse/ClickHouse/issues/46763

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by UnamedRus** [comment]
Also, similar thing for LAG / LEAD functions.

Currently in ClickHouse there is LagInFrame & LeadInFrame instead.

**Comment by vdimir** [comment]
@UnamedRus 

Do you mean to alias  `lag(number, 1) OVER (order by number)` to `lagInFrame(number, 1) OVER (order by number rows between unbounded preceding and unbounded following)` (as it mentioned in the doc) and restrict usage of `lag/lead` for other frames?

https://github.com/ClickHouse/ClickHouse/blob/d28b71e69d42f409e9e8abdfb67e3f848899dc46/docs/en/sql-reference/window-functions/index.md?plain=1#L21-L23

If I get correctly `lag/lead` are not implemented intentionally:

https://github.com/ClickHouse/ClickHouse/blob/d28b71e69d42f409e9e8abdfb67e3f848899dc46/src/Processors/Transforms/WindowTransform.cpp#L2432-L2448

**Comment by UnamedRus** [comment]
> Do you mean to alias lag(number, 1) OVER (order by number) to lagInFrame(number, 1) OVER (order by number rows between unbounded preceding and unbounded following) (as it mentioned in the doc)

Yes.

> and restrict usage of lag/lead for other frames?

May be also in case of some frame specified (ie `current row and current row`) 
> lag(number, 1) OVER (order by number rows between current row and current row)

Replace it with 
> lag(number, 1) OVER (order by number rows between unbounded preceding and unbounded following)
Or 
> lag(number, offset) OVER (order by number rows between offset preceding and current row)

Dunno what is more efficient.

**Comment by vdimir** [comment]
resolved a conflict

**Comment by robot-clickhouse** [comment]
This is an automated comment for commit ef9c3a3ca13b0d785536668cc9f2daedb7b2112c with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/49093/ef9c3a3ca13b0d785536668cc9f2daedb7b2112c/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Review by novikd — APPROVED** [review]

**Comment by vdimir** [comment]
> Stateless tests (release, wide parts enabled) — fail: 1, passed: 5283, skipped: 6 [Details](https://s3.amazonaws.com/clickhouse-test-reports/49093/ef9c3a3ca13b0d785536668cc9f2daedb7b2112c/stateless_tests__release__wide_parts_enabled_.html)

`01605_dictinct_two_level` [doesn't seem to be flaky](https://play.clickhouse.com/play?user=play#U0VMRUNUIHB1bGxfcmVxdWVzdF9udW1iZXIsIGNoZWNrX3N0YXJ0X3RpbWUsIGNoZWNrX25hbWUsIHRlc3RfbmFtZSwgdGVzdF9zdGF0dXMsIGNoZWNrX3N0YXR1cywgcmVwb3J0X3VybApGUk9NIGNoZWNrcwpXSEVSRSAxCiAgICAtLUFORCBwdWxsX3JlcXVlc3RfbnVtYmVyID0gMAogICAgQU5EIHRlc3Rfc3RhdHVzICE9ICdTS0lQUEVEJwogICAgQU5EIHRlc3Rfc3RhdHVzICE9ICdPSycKICAgIEFORCBjaGVja19zdGF0dXMgIT0gJ3N1Y2Nlc3MnCiAgICBBTkQgdGVzdF9uYW1lIGxpa2UgJyUwMTYwNV9kaWN0aW5jdF90d29fbGV2ZWwlJwpPUkRFUiBCWSBjaGVja19zdGFydF90aW1lIGRlc2MsIGNoZWNrX25hbWUsIHRlc3RfbmFtZQ==)

Tried to reproduce with changed settings (but without wide parts though) and didn't get a failure.

**Pull request merged**
