### PR TITLE
add zorder curve base

### PR DESCRIPTION
**Pull request by bakey**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):

- New Feature

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
    Continued work of PR #6286 
    Try to finish work of the zorder curve function  supporting

### CODE REVIEW

**Comment by bakey** [comment]
@alexey-milovidov

**Comment by bakey** [comment]
> Need to add functional tests that these functions work.

OK, I will add some tests later

**Comment by bakey** [comment]
> Example of using z-order Curve for index analysis.
> 
> Suppose we created a table with primary key by zCurve:
> 
> ```
> CREATE TABLE t (x UInt32, y UInt32) ENGINE = MergeTree ORDER BY zCurve(x, y)
> ```
> 
> Then we have sparse index on the values of `zCurve(x, y)`.
> Every granule contains the range of values `[z1, z2]` of `zCurve` function.
> 
> Suppose we have a query with conditions on `x` and `y`:
> 
> ```
> SELECT * FROM t WHERE x >= 10 AND x < 20 AND y = 30
> ```
> 
> To process this query efficiently we can derive
> from the range `[z1, z2]` the set of parallelograms of possible values of `x` and `y`.
> 
> And then analyze these parallelograms as usual.

I think  now we can use zCurve like this : select * from t where zCurve(x,y) >= zCurve(10, 20)。 But that's not so convenient and less understandable.
Should I add the support to analyse index in this same PR or open another new PR?

**Comment by kitaisreal** [comment]
@bakey index analyse can be added in separate pull request.

**Comment by alexey-milovidov** [comment]
Need to fix style:
```
2021-08-27 08:43:55 /build/obj-x86_64-linux-gnu/../src/Functions/zCurve.cpp:52:27: error: invalid case style for local variable 'EXP' [readability-identifier-naming,-warnings-as-errors]
2021-08-27 08:43:55             constexpr int EXP = 9, SZ = (sizeof(UInt32) << 3);
2021-08-27 08:43:55                           ^~~
2021-08-27 08:43:55                           exp
2021-08-27 08:43:55 /build/obj-x86_64-linux-gnu/../src/Functions/zCurve.cpp:52:36: error: invalid case style for local variable 'SZ' [readability-identifier-naming,-warnings-as-errors]
2021-08-27 08:43:55             constexpr int EXP = 9, SZ = (sizeof(UInt32) << 3);
2021-08-27 08:43:55                                    ^~
2021-08-27 08:43:55                                    sz
2021-08-27 08:43:55 /build/obj-x86_64-linux-gnu/../src/Functions/zCurve.cpp:53:30: error: invalid case style for local variable 'INF' [readability-identifier-naming,-warnings-as-errors]
2021-08-27 08:43:55             constexpr UInt32 INF = ((static_cast<UInt32>(1) << EXP) - 1) << (SZ - EXP);
2021-08-27 08:43:55                              ^~~
2021-08-27 08:43:55                              inf
2021-08-27 08:43:55 /build/obj-x86_64-linux-gnu/../src/Functions/zCurve.cpp:54:30: error: invalid case style for local variable 'NEG_INF' [readability-identifier-naming,-warnings-as-errors]
2021-08-27 08:43:55             constexpr UInt32 NEG_INF = (static_cast<UInt32>(1) << (SZ - EXP)) - 1;
2021-08-27 08:43:55                              ^~~~~~~
2021-08-27 08:43:55                              neg_inf
2021-08-27 08:43:55 /build/obj-x86_64-linux-gnu/../src/Functions/zCurve.cpp:70:27: error: invalid case style for local variable 'EXP' [readability-identifier-naming,-warnings-as-errors]
2021-08-27 08:43:55             constexpr int EXP = 11, SZ = (sizeof(UInt64) << 3);
2021-08-27 08:43:55                           ^~~
2021-08-27 08:43:55                           exp
2021-08-27 08:43:55 /build/obj-x86_64-linux-gnu/../src/Functions/zCurve.cpp:70:37: error: invalid case style for local variable 'SZ' [readability-identifier-naming,-warnings-as-errors]
2021-08-27 08:43:55             constexpr int EXP = 11, SZ = (sizeof(UInt64) << 3);
2021-08-27 08:43:55                                     ^~
2021-08-27 08:43:55                                     sz
2021-08-27 08:43:55 /build/obj-x86_64-linux-gnu/../src/Functions/zCurve.cpp:71:30: error: invalid case style for local variable 'INF' [readability-identifier-naming,-warnings-as-errors]
2021-08-27 08:43:55             constexpr UInt64 INF = ((static_cast<UInt64>(1) << EXP) - 1) << (SZ - EXP);
2021-08-27 08:43:55                              ^~~
2021-08-27 08:43:55                              inf
2021-08-27 08:43:55 /build/obj-x86_64-linux-gnu/../src/Functions/zCurve.cpp:72:30: error: invalid case style for local variable 'NEG_INF' [readability-identifier-naming,-warnings-as-errors]
2021-08-27 08:43:55             constexpr UInt64 NEG_INF = (static_cast<UInt64>(1) << (SZ - EXP)) - 1;
2021-08-27 08:43:55                              ^~~~~~~
2021-08-27 08:43:55                              neg_inf
```

**Comment by bakey** [comment]
@alexey-milovidov 
The lastest commit have pass most of the tests.
But the performance test said that still has some errors.I check the log, which seems like not related to this PR.
Would you help to review the performance result?

**Comment by alexey-milovidov** [comment]
Yes, perf test changes are unrelated.
So, this PR is ready for merge after review.

**Comment by bakey** [comment]
I will close this PR and submit a new PR base on the latest code of master trunk to resolve the test problem. @alexey-milovidov

**Comment by alexey-milovidov** [comment]
Now the tests are fixed (and the only red is `test_cte_distributed` that appears to be broken just now in master and unrelated to your changes).

**Comment by bakey** [comment]
I am working on the function of analysis index with zCurve. Will submit a new PR after this PR being merged

**Pull request closed without merging**
