### PR TITLE
Fix bug with wrong implementation in ZooKeeper API

### PR DESCRIPTION
**Pull request by alesapin**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Non-significant (changelog entry is not required)

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix `startNewSession` method in ZooKeeper API for non default ZooKeeper implementations.

### CODE REVIEW

**Comment by alesapin** [comment]
Previously, if TestKeeper session expires for some reason we will not be able to reconnect because `startNewSessions` doesn't pass implementation name to the constructor and use the default `"zookeeper".

**Review by alexey-milovidov — APPROVED** [review]
Ok.

PS. I'd also like to remove default parameters just in case, but it's not necessarily.

**Comment by alexey-milovidov** [comment]
And also the question: why TestKeeper session can be expired?

**Comment by alesapin** [comment]
> And also the question: why TestKeeper session can be expired?

I have connected to sever with GDB. After I have detached from server all sessions were expired and was not able to recover.

**Pull request merged**
