### PR TITLE
fix groupBitmapAnd function on distributed table

### PR DESCRIPTION
**Pull request by dmthuc**
Changelog category (leave one):
- Bug Fix (user-visible misbehaviour in official stable or prestable release)

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
fix groupBitmapAnd function on distributed table

Detailed description / Documentation draft:
Currently the function `groupBitmapAnd` function have bug when use with distributed table. The bug is already mentioned in issue https://github.com/ClickHouse/ClickHouse/issues/31102. When the distributed table have 2 shards. The remote shard have 1 row and the local shard doens't have data. The result will be empty set and it is not correct.
The reason is because the logic of the merge function in `AggregateFunctionGroupBitmap.h`. The `init` variable is not include in the serialize/deserialize process while its value is affect the result of merge function. In this case the `init` was true when it is at remote shard, but when come to the merging stage in the local shard its value reset to false.

The issue can be reproduce by the following query.
```
CREATE TABLE bitmap_column_expr_test2 on cluster two_shard_cluster
(
    tag_id String,
    z AggregateFunction(groupBitmap, UInt32)
)
ENGINE = MergeTree()
ORDER BY tag_id;


CREATE TABLE bitmap_column_expr_test2_dst on cluster two_shard_cluster
(
    tag_id String,
    z AggregateFunction(groupBitmap, UInt32)
)
ENGINE = Distributed(two_shard_cluster, currentDatabase(), 'bitmap_column_expr_test2');

# execute this query in 1 shard
INSERT INTO bitmap_column_expr_test2 VALUES ('tag1', bitmapBuild(cast([1,2,3,4,5,6,7,8,9,10] as Array(UInt32))));

# in the shard that has data execute this query
SELECT groupBitmapAnd(z) FROM bitmap_column_expr_test2_dst;
# the result will be
10

#in the shard that doesn't have data, execute the same select query
#the result will be 
0
```

image

> By adding documentation, you'll allow users to try your new feature immediately, not when someone else will have time to document it later. Documentation is necessary for all features that affect user experience in any way. You can add brief documentation draft above, or add documentation right into your patch as Markdown files in [docs](https://github.com/ClickHouse/ClickHouse/tree/master/docs) folder.

> If you are doing this for the first time, it's recommended to read the lightweight [Contributing to ClickHouse Documentation](https://github.com/ClickHouse/ClickHouse/tree/master/docs/README.md) guide first.

> Information about CI checks: https://clickhouse.tech/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by dmthuc** [comment]
Thank you for adding the label, but the `CheckLabels` are still failed because of `INFO:root:User 'dmthuc' is not trusted`. What can we do to solve this?

**Comment by novikd** [comment]
@Mergifyio update

**Comment by dmthuc** [comment]
There are some tests were not successful but I checked them they seems not related to the modification

**Comment by alexey-milovidov** [comment]
As the serialization format of this function changed, we need to introduce a new version for that.
Otherwise it's not backward compatible: https://github.com/ClickHouse/ClickHouse/pull/24820

**Review by alexey-milovidov — CHANGES_REQUESTED** [review]
Also need a test.

**Comment by dmthuc** [comment]
> As the serialization format of this function changed, we need to introduce a new version for that. Otherwise it's not backward compatible: #24820

Thank you for commenting. I have thought about backward compatible in this case so I would like to ask more about that. As I notice that this aggregation function is `groupBitmapAnd` function and it is only used `on air` and not used for create table. When create table we use `groupBitmap` function instead and I do not change to serialization/deserialization of the `groupBitmap` function so we would not have backward compatible issue when read/writing data on disk. But we still have backward compatible issues between two Clickhouse servers when they are communicate to each other and we have to introduce new version for that reason right?

> Also need a test.
You mean the test for this function on Distributed table right? And it seems to be integration test because as I know I can the stateless test doesn't support real cluster with 2 or more shards

**Comment by dmthuc** [comment]
There are some tests that were not successful but seem not related to my modification. BTW, I have a question. Is the check that have `(pull_request)` in the end, for example `CIGithubActions / StressTestMsan (pull_request)` is the check for my PR and the check that doesn't have it is the check for the original code?
image

**Comment by dmthuc** [comment]
I've just have found some place need to fix

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
Perfect, thank you!

**Pull request merged**
