### PR TITLE
Merging #14890

### PR DESCRIPTION
**Pull request by alexey-milovidov**
Changelog category (leave one):
- Not for changelog (changelog entry is not required)

#14890

### CODE REVIEW

**Comment by nikitamikhaylov** [comment]
Strange test failure, I will take a look.

**Comment by nikitamikhaylov** [comment]
I've removed backquotes from primary key column names.

**Review by nikitamikhaylov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
@nikitamikhaylov But the original intention of the PR https://github.com/ClickHouse/ClickHouse/pull/14890/files was to add backquotes.

**Comment by nikitamikhaylov** [comment]
> @nikitamikhaylov But the original intention of the PR https://github.com/ClickHouse/ClickHouse/pull/14890/files was to add backquotes.

Lol, I didn't noticed that. We investigate the problem more.

**Comment by nikitamikhaylov** [comment]
Merged in #15783

**Pull request closed without merging**
