### PR TITLE
Allow to include subcolumns in `DESCRIBE`  query

### PR DESCRIPTION
**Pull request by CurtizJ**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- New Feature

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Allow to include subcolumns of table columns into `DESCRIBE` query result (can be enabled by setting `describe_include_subcolumns`).

### CODE REVIEW

**Comment by CurtizJ** [comment]
Wiil be useful for #23932, because objects will be stored as tuples in tables and it will be inconvenient to check names and types of subcolumns if they are written in single `Tuple(col1 T1, col2 T2, ..., col_n T_n)`.

**Review by kssenii — APPROVED** [review]
LGTM

**Comment by CurtizJ** [comment]
@Mergifyio update

**Comment by gyuton** [comment]
Internal documentation ticket: DOCSUP-14793.

**Pull request merged**
