### PR TITLE
Rename ContextConstPtr to ContextPtr.

### PR DESCRIPTION
**Pull request by KochetovNicolai**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by nikitamikhaylov** [comment]
@KochetovNicolai Arcadia synchronization is broken in master because of the context related changes.. Please, note about this when you will merge this PR.

**Comment by KochetovNicolai** [comment]
@nikitamikhaylov I am fixing it right now.

**Comment by KochetovNicolai** [comment]
@mergifyio update

**Comment by KochetovNicolai** [comment]
@Mergifyio update

**Pull request merged**
