### PR TITLE
Fix `system.dropped_tables_parts` filtering by UUID

### PR DESCRIPTION
**Pull request by antaljanosbenjamin**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix incorrect results when filtering `system.dropped_tables_parts` using UUID.

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

---
### Modify your CI run:
**NOTE:** If your merge the PR with modified CI you **MUST KNOW** what you are doing
**NOTE:** Set desired options before CI starts or re-push after updates

#### Run only:
- [ ]  Integration tests
- [ ]  Integration tests (arm64)
- [ ]  Stateless tests (release)
- [ ]  Stateless tests (asan)
- [ ]  Stateful tests (release)
- [ ]  Stateful tests (asan)
- [ ]  No sanitizers
- [ ]  Tests with analyzer
- [ ]  Fast tests
- [ ]  Only package_debug build
- [ ]  Add your CI variant description here

#### CI options:
- [ ]  do not test (only style check)
- [ ]  disable merge-commit (no merge from master before tests)
- [ ]  disable CI cache (job reuse)

#### Only specified batches in multi-batch jobs:
- [ ]  1
- [ ]  2
- [ ]  3
- [ ]  4

Similar to #61479.

### CODE REVIEW

**Comment by robot-ch-test-poll2** [comment]
*This is an automated comment for commit 8db8b4c62a2466dacc02747e8b36c18cffdae8bc with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/61768/8db8b4c62a2466dacc02747e8b36c18cffdae8bc/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

**Comment by antaljanosbenjamin** [comment]
I think it works with the latest master, will merge it.

**Review by yariks5s — APPROVED** [review]

**Comment by antaljanosbenjamin** [comment]
I cannot figure out what happened with the  bugfix check. I will merge master again, to make sure I don't mess up anything with this PR.

**Comment by yariks5s** [comment]
> I cannot figure out what happened with the bugfix check.

I suppose that bugfix failed because the problem is probably fixed on the head or it is a rare bug. I've tried to reproduce the tests that you added to this PR and got the same result as it expected to be when fixed: 
https://fiddle.clickhouse.com/5bafc180-3aba-4a1f-af02-f304d3cda16f - 03010_read_system_parts_table_test
https://fiddle.clickhouse.com/29de68fc-1d37-4eb7-b21d-714f3db54e0c - 03019_filtering_system_dropped_tables_parts_by_uuid

**Comment by antaljanosbenjamin** [comment]
Actually I realized that `StorageSystemDroppedTablesParts` are not inheriting from `StorageSystemPartsBase`, but `StorageSystemParts`, so this fix is unnecessary.

**Pull request closed without merging**
