### PR TITLE
Fix inconsistent formatting for `GRANT CURRENT GRANTS`

### LINKED ISSUE #67651: Inconsistent AST formatting in `GRANT CURRENT GRANTS`
https://s3.amazonaws.com/clickhouse-test-reports/65277/fa6564dbe32033af3aa0693d07d1b9a645adfa40/integration_tests_flaky_check__asan_.html

### PR DESCRIPTION
**Pull request by pufit**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fixes https://github.com/ClickHouse/ClickHouse/issues/67651

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-clickhouse-ci-2** [comment]
*This is an automated comment for commit c50ef37a03438003c21076c5700d9c1f52c1c435 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/67653/c50ef37a03438003c21076c5700d9c1f52c1c435/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

**Review by alexey-milovidov — CHANGES_REQUESTED** [review]
Add a test.

**Comment by pufit** [comment]
> Add a test.

There is one already, and it's failing without this fix https://s3.amazonaws.com/clickhouse-test-reports/65277/fa6564dbe32033af3aa0693d07d1b9a645adfa40/integration_tests_flaky_check__asan_.html

**Comment by alexey-milovidov** [comment]
That test is from a pull request that is not merged yet.
Let's add a simple, functional test.

**Comment by arthurpassos** [comment]
> That test is from a pull request that is not merged yet. Let's add a simple, functional test.

Below should be enough, just tested locally

```
DROP USER IF EXISTS user_03214;

CREATE USER user_03214;

GRANT CURRENT GRANTS(NONE ON *.*) TO user_03214;
```

**Comment by alexey-milovidov** [comment]
Yes, see similar `*inconsistent_formatting*.sh` tests.

**Comment by pufit** [comment]
>That test is from a pull request that is not merged yet.

No, it's an old test https://github.com/ClickHouse/ClickHouse/blob/master/tests/integration/test_grant_and_revoke/test_with_table_engine_grant.py#L615
But I can add a simple .sh test nevertheless

**Review by alexey-milovidov — APPROVED** [review]
Ok, but tests didn't pass. They should be green.

**Comment by pufit** [comment]
`03002_part_log_rmt_fetch_merge_error ` - fixed here https://github.com/ClickHouse/ClickHouse/pull/67960

**Pull request merged**
