### PR TITLE
Fixed crash in MaterializedMySQL while using override + null field 

### PR DESCRIPTION
**Pull request by bakwc**
Fix for #54647

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fixed crash while using MaterializedMySQL with TABLE OVERRIDE that maps MySQL NULL field into ClickHouse not NULL field

### CODE REVIEW

**Comment by bakwc** [comment]
I will add integration tests for it.

**Comment by robot-ch-test-poll** [comment]
*This is an automated comment for commit bda40b5a98974a9d78ca055855215b01bba546dc with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/54649/bda40b5a98974a9d78ca055855215b01bba546dc/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>✅ success</td></tr>
<tbody>
</table>
</details>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>⏳ pending</td></tr>
<tbody>
</table>

**Comment by Avogar** [comment]
Please, merge your branch with master, for some reason CI didn't started. Also waiting for the test

**Review by alexey-milovidov — APPROVED** [review]

**Comment by Avogar** [comment]
Let's merge it without a test as an exception

**Pull request merged**
