### PR TITLE
[wip] experiment with unstable codec perf tests

### PR DESCRIPTION
**Pull request by akuzm**
Changelog category (leave one):
- Non-significant (changelog entry is not required)

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]
Ok but what is the main difference?

**Comment by akuzm** [comment]
> Ok but what is the main difference?

One less Block::mutateColumns() call -- you can see it in the perf test flamegraphs for, say, `codec_seq_UInt64_Delta`. I still have to wrap my head around this myself :)
A call to Block::getColumns() that I added can also be removed, so I'll continue.

The codecs_int tests seem to have improved: https://clickhouse-test-reports.s3.yandex.net/10340/ef80a3bac6b83947812893d98423cd27d18f1260/performance_comparison/all-queries.html#2.99
Current 15% sensitivity of our perftest is abysmal though, I really have to do something about that.

**Comment by akuzm** [comment]
https://github.com/ClickHouse/ClickHouse/pull/10340/files#diff-4571d47993d9a8ed40fd8c6c27de8ceaL15

The main offending line was this -- it just copied a block and then mutated all its columns, for no good reason.

**Comment by akuzm** [comment]
The tests were broken after merge with master and don't look related to this PR.

**Pull request merged**
