### PR TITLE
Part movements between shards improvements and cancel support

### PR DESCRIPTION
**Pull request by nvartolomei**
Follow up to #17871. Part of #13574. Supersedes #24585 due to a GitHub limitation.

Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by nvartolomei** [comment]
@alesapin this is net superior to what we have today in master. Re-wrote commit history to make it more meaningful.

**Review by alesapin — APPROVED** [review]
Ok, I'm still not sure about some details of Orchestrator. Let's merge because this feature is still experimental.

**Comment by alesapin** [comment]
Test failures unrelated to changes, but let's check one more time.

**Comment by alesapin** [comment]
@mergifyio update

**Comment by nvartolomei** [comment]
@alesapin anything I can help with getting this merged?

**Pull request merged**
