### PR TITLE
Fix filelog storage data paths

### PR DESCRIPTION
**Pull request by kssenii**
Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Change path for metadata of FileLog engine.

### CODE REVIEW

**Review by vdimir — COMMENTED** [review]
Will path of fs be the same? If not, is it backward compatible?

**Comment by kssenii** [comment]
> If not, is it backward compatible?

backward incompatible

**Comment by vdimir** [comment]
@kssenii so, can we check old path at startup and perform migrating, move files to new location to make server update easier?

**Comment by kssenii** [comment]
@Mergifyio update

**Review by vdimir — APPROVED** [review]

**Pull request merged**
