### PR TITLE
fix issue #18086

### PR DESCRIPTION
**Pull request by mis98zb**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

fix data type convert issue for mysql engine 
...

Detailed description / Documentation draft:

...

By adding documentation, you'll allow users to try your new feature immediately, not when someone else will have time to document it later. Documentation is necessary for all features that affect user experience in any way. You can add brief documentation draft above, or add documentation right into your patch as Markdown files in [docs](https://github.com/ClickHouse/ClickHouse/tree/master/docs) folder.

If you are doing this for the first time, it's recommended to read the lightweight [Contributing to ClickHouse Documentation](https://github.com/ClickHouse/ClickHouse/tree/master/docs/README.md) guide first.

Information about CI checks: https://clickhouse.tech/docs/en/development/continuous-integration/

### CODE REVIEW

**Review by abyss7 — CHANGES_REQUESTED** [review]
Do you have any test to highlight the issue?

**Comment by mis98zb** [comment]
> Do you have any test to highlight the issue?

For the return values from mysql, I used the sql in FetchTablesColumnsList.cpp to get the types from my prod env.
By this I get the type partten returns from mysql.

And for the code fix, I put the changed code snippet into a new c++17 project, and used those partten I've got for testing.
The code snippet worked as expected.

I failed to get all the submodules so as I couldn't compile the whole clickhouse and run it for testing.

**Comment by mis98zb** [comment]
btw, I don't know why `const auto type_end_pos = data_type.find_first_of("( ");` failed in style check.
Is this api forbidden?

**Comment by mis98zb** [comment]
> Do you have any test to highlight the issue?

oh! I got it. I'll write test case for this.

**Comment by mis98zb** [comment]
hi @abyss7
Finally mysql engine related test cases all passed.
Sorry for summiting so many times, :(

Currently the only one test case failed is test_cluster_copier/test_big_cluster.py::test_copy_simple, which throw an exception on teardown step:
`Exception: Sanitizer assert found in /ClickHouse/tests/integration/test_cluster_copier/_instances/docker.log for instance [31;1ms0_1_0_1`

Would you please to finger out what shall I do to complete this pull request?

**Comment by abyss7** [comment]
Everything is fine - I will take the final look.

**Comment by mis98zb** [comment]
Thank you.

Btw, I found several things during writing test:

- clickhouse client returns -1 for uint32 value 4294967295 while http channel return the exact value.
- currently test code cannot support null test, because clickhouse returns \N for null  with TSV format.
- clickhouse returns 0 for float value 0.0 while mysql returns 0.0 for it

the 1st one may be serious and need to be corrected.

**Pull request merged**
