### PR TITLE
Add gdb index to builds with debug info

### PR DESCRIPTION
**Pull request by alesapin**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

For changelog. Remove if this is non-significant change.

Category (leave one):
- Build/Testing/Packaging Improvement

Short description (up to few sentences):
Add gdb-index to clickhouse binary with debug info.

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]

**Comment by akuzm** [comment]
How much slower it is? I'd prefer to have some knob to turn it off.

Btw, tried setting up auto-building of indexes in gdb 8.3, and it didn't work for unknown reasons.

**Comment by amosbird** [comment]
I've heard we need `-gsplit-dwarf` or `-ggnu-pubnames ` to make `-Wl,-gdb-index` actually work

**Comment by alesapin** [comment]
With gcc we got huge performance degradation, stack top is always something like:
```
  52.11%  clickhouse          [.] _ZN2DB5Dwarf12LineNumberVM4stepERSt17basic_string_viewIcSt11char_traitsIcEE                                                                                                    
  36.90%  clickhouse          [.] _ZN2DB12_GLOBAL__N_14readIhEENSt9enable_ifIX8is_pod_vIT_EES3_E4typeERSt17basic_string_viewIcSt11char_traitsIcEE
   5.68%  clickhouse          [.] _ZN2DB5Dwarf12LineNumberVM11findAddressEmRNS0_4PathERm                                                         
   2.21%  clickhouse          [.] _ZN2DB5Dwarf16readAbbreviationERSt17basic_string_viewIcSt11char_traitsIcEERNS0_15DIEAbbreviationE
```

**Comment by alexey-milovidov** [comment]
> With gcc we got huge performance degradation, stack top is always something like

Ok. So, this "approved" to be closed.

**Review by proller — APPROVED** [review]

**Comment by alesapin** [comment]
latest commit doesn't affect anything

**Pull request merged**
