### PR TITLE
client: add a message on reconnect (under warning log level)

### PR DESCRIPTION
**Pull request by azat**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

This will make debugging tests easier, since sometimes it is possible
for server to hung for a few seconds, and this leads to client
reconnect, which can leave the query in backround, like in [1] ([2]).

  [1]: https://s3.amazonaws.com/clickhouse-test-reports/35865/0cb3770d104b5f673d1d0d1076ac3fd3619fee9e/stateless_tests__debug__actions__%5B2/3%5D.html
  [2]: https://github.com/ClickHouse/ClickHouse/pull/35865#issuecomment-1099516534

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]
FYI it is possible to enable full logging support in clickhouse-client similar to clickhouse-local.

**Comment by alexey-milovidov** [comment]
@mergifyio update after #36607.

**Comment by alexey-milovidov** [comment]
> Stress test (debug, actions) — Backward compatibility check: Fatal message in clickhouse-server.log (see bc_check_fatal_messages.txt) 

As expected (previous version has a bug).

**Comment by tavplubix** [comment]
@azat, it makes some tests flaky:
```
2022-05-02 13:11:43 01293_optimize_final_force:                                             [ FAIL ] 110.07 sec. - having stderror: 
2022-05-02 13:11:43 Connection lost. Reconnecting.
2022-05-02 13:11:43 
```
https://s3.amazonaws.com/clickhouse-test-reports/0/c95591f294362f6212c21b1e59d913cb2e85e7ed/stateless_tests__debug__actions__[1/3].html

**Comment by azat** [comment]
Yes, and this was the intention, w/o the test may fail with queries left after the test finished.
And the reason of this reconnects, usually, is that server is hung for few seconds, and this should not happen, I will take a look at this.

**Comment by azat** [comment]
Here is another such failure - https://s3.amazonaws.com/clickhouse-test-reports/36841/7cc64d40a6802df904a684d05e4a54ab5484ddfa/stateless_tests__debug__actions__[1/3].html (reported by @alexey-milovidov )

**Comment by tavplubix** [comment]
> Yes, and this was the intention, w/o the test may fail with queries left after the test finished. 

But it does not make any sense. Tests were flaky because they might leave some running queries. Now tests are flaky because of this warning message. Nothing changed, tests are still flaky.

Let's just disable (or even remove) this check then. As to me, it's not a problem if some queries left after a test for a short period of time.

**Comment by azat** [comment]
>But it does not make any sense. Tests were flaky because they might leave some running queries. Now tests are flaky because of this warning message. Nothing changed, tests are still flaky.

The difference is that now you are seeing the explicit reason, not just queries that was left.

>Let's just disable (or even remove) this check then. As to me, it's not a problem if some queries left after a test for a short period of time.

Usually it is not, but this check can catch something interesting.
Also if the client exited successfully, then no queries should left.

Actually after `is_all_data_sent` (#36816, #36767, #36649) had been added and it is checked by `clickhouse-test` this should not be a problem, so this reconnect message can be indeed reverted.
Let me take a look what server was doing (likely some tracing), and I will either revert this message or fix this in another way.

**Pull request merged**
