### PR TITLE
Added client_info validation to the query packet in TCPHandler.

### LINKED ISSUE #53503: Validate client_info in query message in TCP handler
**Describe the unexpected behavior.**
During a TCP session, the client authenticates as `Alice`,  with interface 'TCP' (set in `TCPHandler::makeSession()`) on the server side.

After session setup, the client sends `Protocol::Client::Query` packet, the TCP handler accepts it, and then **reads client_info**.

```cpp
    ClientInfo client_info = session->getClientInfo(); 
    if (client_tcp_protocol_version >= DBMS_MIN_REVISION_WITH_CLIENT_INFO)
        client_info.read(*in, client_tcp_protocol_version); 
```

This `client_info` is not validated and can differ from session->getClientInfo(). This client info can contain different interface, hostname, client_name and several other parameters.

**How to reproduce**
Connect to the ClickHouse server using the TCP protocol and authenticate.
Send a query packet with different ClientInfo

**Expected behavior**
The TCP handler verifies `ClientInfo` from the client if a session is started. `ClientInfo` must match. If it does not match, send an error to the client.

### PR DESCRIPTION
**Pull request by Demilivor**
Closes #53503 
Added client info validation to the query packet in TCPHandler. 
Used the same client name for the clickhouse-client, clickhouse-benchmark and Python tests.

### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Added client info validation to the query packet in TCPHandler.

### CODE REVIEW

**Comment by Demilivor** [comment]
Good time of day @tavplubix, could you please be the reviewer of this pull request and add the label `Can Be Tested?

**Comment by robot-ch-test-poll4** [comment]
This is an automated comment for commit c0a8e09c9d58e1638b71f1527adf9ef6ca53c9d6 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/53673/c0a8e09c9d58e1638b71f1527adf9ef6ca53c9d6/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Review by tavplubix — APPROVED** [review]

**Comment by tavplubix** [comment]
Integration tests (asan) [1/6] - https://github.com/ClickHouse/ClickHouse/issues/51464
Stateless tests (debug, s3 storage) [1/6] - https://github.com/ClickHouse/ClickHouse/pull/53309#issuecomment-1692177599

**Comment by Algunenano** [comment]
Requesting a revert here -> https://github.com/ClickHouse/ClickHouse/pull/53869

**Comment by rvasin** [comment]
The client information validation is a needed security feature. Maybe the solution could be to implement new option with working name: `validate_client_information` with default value `false`. So it will not break old clients.

**Comment by Algunenano** [comment]
> Maybe the solution could be to implement new option with working name: validate_client_information with default value false. So it will not break old clients.

I would be ok even if it's set to true by default, as long as I can set it to false during the upgrade procedure and enable once the whole cluster is upgraded.

**Comment by Demilivor** [comment]
> The client information validation is a needed security feature. Maybe the solution could be to implement new option with working name: `validate_client_information` with default value `false`. So it will not break old clients.

This is quite easy, I could add this option tomorrow and create a PR. I'd like client_info validation to be enabled by default.

**Comment by tavplubix** [comment]
Can we avoid adding a setting for this? Do I understand correctly that old versions of `clickhouse-client` use two client names (`ClickHouse` and `ClickHouse client`)? Maybe we can allow that kind of name mismatch (and automatically replace one with another)

**Comment by tavplubix** [comment]
However, the setting still makes sense for third-party clients

**Comment by Demilivor** [comment]
> Can we avoid adding a setting for this? Do I understand correctly that old versions of `clickhouse-client` use two client names (`ClickHouse` and `ClickHouse client`)? Maybe we can allow that kind of name mismatch (and automatically replace one with another)

Yes, you understand correctly.
`clickhouse-client` is not the only client for the ClickHouse, I looked into the [ClickHouse-cpp](https://github.com/ClickHouse/clickhouse-cpp) code, and it looks correct. It sends `ClickHouse client` on all queries and connection initiation. So it should work both with the old and new ClickHouse versions.

I was also thinking about just allowing `ClickHouse` + `ClickHouse client` combination, but I can't be sure that no other ClickHouse native TCP protocol clients sending different client_info exist.

**Comment by Demilivor** [comment]
Created PR https://github.com/ClickHouse/ClickHouse/pull/53673 making client info validation optional.

**Comment by canhld94** [comment]
It seems this change also breaks the protocol between old client and new server. I cannot use v23.7 client to send query to v23.8 server anymore.

**Comment by rvasin** [comment]
In #53907 we finally decided to set default value of `validate_tcp_client_information` to `false`. So it's not urgently needed to rewrite all clients.

**Comment by alexey-milovidov** [comment]
Could you please explain what it is for?
I don't understand from the changelog.

**Pull request merged**
