### PR TITLE
Optimize asArrowFile for ReadBufferFromHDFS

### PR DESCRIPTION
**Pull request by taiyang-li**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Optimize asArrowFile for ReadBufferFromHDFS, which avoid read the whole hdfs file into memory, since `ReadBufferFromHDFS` is seekable.  

Detailed description / Documentation draft:
Optimize asArrowFile for ReadBufferFromHDFS, which avoid read the whole hdfs file into memory, since `ReadBufferFromHDFS` is seekable.

### CODE REVIEW

**Comment by taiyang-li** [comment]
Slower case in performance test is irrelevant with this pr, that is strange..

**Comment by evillique** [comment]
It would be great to add a test for this :)

**Comment by taiyang-li** [comment]
> It would be great to add a test for this :)

Do we have some similar examples to refer to?

**Comment by evillique** [comment]
@Mergifyio update

**Comment by evillique** [comment]
@Mergifyio update

**Pull request closed without merging**
