### PR TITLE
Add documentation for `system.asynchronous_metrics`.

### LINKED ISSUE #7644: Document system.asynchronous_metrics
Defined in https://github.com/ClickHouse/ClickHouse/blob/master/dbms/src/Interpreters/AsynchronousMetrics.cpp

cc @alexey-milovidov 😄

### PR DESCRIPTION
**Pull request by alexey-milovidov**
### Changelog category (leave one):
- Improvement.

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
The `system.asynchronous_metrics` gets embedded documentation. This documentation is also exported to Prometheus. Fixed an error with the metrics about `cache` disks - they were calculated only for one arbitrary cache disk instead all of them. This closes #7644.

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
Preview: https://pastila.nl/?00014be2/bef19200f62e823a0f60254953baeb7e.md
Generated by the following query:
```
WITH replaceRegexpAll(metric LIKE '%.%' ? metric : replaceRegexpAll(metric, '_.+$', '_*name*'), '_?\d+$', '_*N*') AS title SELECT format('## {}\n\n{}\n', title, any(description)) FROM system.asynchronous_metrics GROUP BY title ORDER BY title FORMAT TSVRaw
```

**Comment by alexey-milovidov** [comment]
https://pastila.nl/?00014be2/6cb3dc5f2fc8f3c8ae55bd8a2ea39c2d.md

It includes only the docs for non-zero metrics.
For example, EDAC metrics are not displayed in this paste.

**Comment by alexey-milovidov** [comment]
> AST fuzzer (msan) — Logical error: 'Trying to get non existing mark 18446744073709551615, while size is 0'. 

This is related to Analyzer: https://github.com/ClickHouse/ClickHouse/issues/43204

**Comment by alexey-milovidov** [comment]
> Integration tests (tsan) [2/4] — fail: 2, passed: 542, flaky: 3 

@antonio2368 is fixing it in #43201.

**Comment by alexey-milovidov** [comment]
> Stress test (asan) — Backward compatibility check: Error message in clickhouse-server.log
Stress test (debug) — Backward compatibility check: Error message in clickhouse-server.log

@kssenii said it is going to be fixed in https://github.com/ClickHouse/ClickHouse/pull/43143.

**Comment by alexey-milovidov** [comment]
@KochetovNicolai flaky test https://s3.amazonaws.com/clickhouse-test-reports/43194/4012b46a87daa5ea375055674920205cc52bd5b4/stateless_tests__tsan__[1/3].html

**Review by kssenii — APPROVED** [review]

**Comment by kssenii** [comment]
> Integration tests (tsan) [2/4] — fail: 2, passed: 542, flaky: 3

`test_keeper_four_word_command/test.py::test_cmd_stat` cc @alesapin 
`test_merge_tree_s3/test.py::test_table_manipulations[node]` https://github.com/ClickHouse/ClickHouse/pull/43201

> Stress test (ubsan) 

`<Fatal> : Logical error: 'No column to rollback'.` https://github.com/ClickHouse/ClickHouse/issues/42740

**Pull request merged**
