### PR TITLE
Disable test_odbc_interaction for MSan build

### PR DESCRIPTION
**Pull request by vdimir**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]

**Comment by nikitamikhaylov** [comment]
Maybe also skip `test_bridge_dies_with_parent` for TSAN build ?

**Comment by vdimir** [comment]
> Maybe also skip `test_bridge_dies_with_parent` for TSAN build ?

It's already skipped, I only changed `return` to `pytest.skip` in this PR

https://github.com/ClickHouse/ClickHouse/blob/d3f4fb404a6da659ac2cf06e2d71fe05edf2db4b/tests/integration/test_odbc_interaction/test.py#L329-L333

**Comment by alexey-milovidov** [comment]
@vdimir It's about Address Sanitizer.

BTW, what is about Thread Sanitizer? How does it argue?

**Comment by vdimir** [comment]
> BTW, what is about Thread Sanitizer? How does it argue?

It's also flaky, we can disable it for TSan too.

<details>
<summary>query</summary>
```
SELECT
 check_name,
 test_name,
 test_status, 
 count(),
 min(check_start_time),
 max(check_start_time)
FROM `gh-data`.checks
WHERE
    test_status like 'F%' 
    AND test_name like 'test_odbc%'
    AND check_name like '%thread%'
    AND pull_request_number = 0
 AND check_start_time > now() - INTERVAL '10' day
GROUP BY check_name, test_name, test_status
LIMIT 50
;
```
</details>

```
┌─check_name─────────────────┬─test_name───────────────────────────────────────────────────┬─test_status─┬─count()─┬─min(check_start_time)─┬─max(check_start_time)─┐
│ Integration tests (thread) │ test_odbc_interaction/test.py::test_concurrent_queries      │ FLAKY       │       3 │   2021-04-20 03:02:31 │   2021-04-27 11:57:34 │
│ Integration tests (thread) │ test_odbc_interaction/test.py::test_many_connections        │ FLAKY       │       1 │   2021-04-20 02:00:36 │   2021-04-20 02:00:36 │
│ Integration tests (thread) │ test_odbc_interaction/test.py::test_bridge_dies_with_parent │ FLAKY       │      98 │   2021-04-18 13:01:38 │   2021-04-27 18:20:31 │
└────────────────────────────┴─────────────────────────────────────────────────────────────┴─────────────┴─────────┴───────────────────────┴───────────────────────┘
```

**Review by kitaisreal — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
@vdimir I don't understand the mechanics. Why the run under TSan triggers the error `Not a valid unsigned integer`?
Shouldn't it be investigated further?

**Comment by kitaisreal** [comment]
@alexey-milovidov we will investigate this futher.

**Comment by alexey-milovidov** [comment]
For the reference: we have investigated it *further* and fixed the issue.

**Pull request merged**
