### PR TITLE
Make system log engine customizable via config.

### PR DESCRIPTION
**Pull request by zlobober**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Add an option allowing to customize system log engine specification. Useful for internal CHYT project which does not want to store query log etc using MergeTree engine.

Changelog category (leave one):
- Non-significant (changelog entry is not required)

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
I've made two changes to your code:
1. Chaned 'custom_engine' to 'engine', because it is more simple.
2. Added a check to prevent unexpected configuration.

**Comment by azat** [comment]
Also example in config.xml will be great

**Comment by alexey-milovidov** [comment]
Yes. An example is strictly necessarily, because the usage of this setting is unintuitive :(
It's named engine but instead of just accept `TinyLog` it requires to write `ENGINE = TinyLog`.

I will add an example.

**Comment by zlobober** [comment]
Maybe it is a good idea to rename option to 'engine_line' or 'engine_specification'?

**Comment by azat** [comment]
Since `clickhouse-copier` has `engine`, I guess `engine` is fine

**Comment by alexey-milovidov** [comment]
Now it's Ok.

**Pull request merged**
