### PR TITLE
Control the execution period of clear old temporary directories by parameter

### PR DESCRIPTION
**Pull request by fastio**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Control the execution period of clear old temporary directories by parameter with default value. #26212 

Detailed description / Documentation draft:

Add the parameters to control the execution period of cleanup old temporary directories, pars, WALs, and mutations.

### CODE REVIEW

**Comment by fastio** [comment]
ping @nikitamikhaylov

**Comment by nikitamikhaylov** [comment]
@fastio Sorry, I have another huge PR and it may conflict with your. But I can merge it now...

**Comment by nikitamikhaylov** [comment]
@Mergifyio update

**Review by nikitamikhaylov — APPROVED** [review]

**Comment by gyuton** [comment]
Internal documentation ticket: DOCSUP-14458.

**Comment by gyfis** [comment]
@nikitamikhaylov Hi! Do you plan to backport this to the -stable and -lts versions (e.g. `v21.8.5.7-lts`)?

**Comment by alexey-milovidov** [comment]
No. It's not a bugfix - no need to backport.
If you need this feature - install release 21.9.

**Comment by gyfis** [comment]
> No. It's not a bugfix - no need to backport.
> If you need this feature - install release 21.9.

Thanks, appreciate the response! We had some issues with super slow restarts, empty parts et. co. on v21.8, and I thought this feature may help, however we settled on downgrading to v21.6 and we're good.

**Comment by den-crane** [comment]
@gyfis it's unrelated issue

**Comment by alexey-milovidov** [comment]
I don't know any related issues in 21.8. Will be good to know...
The version 21.8 is already installed in major of servers in Yandex (including Yandex Metrica) with no issues.

**Pull request merged**
