### PR TITLE
Enable compact parts by default for small parts

### PR DESCRIPTION
**Pull request by alexey-milovidov**
Changelog category (leave one):
- Performance Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Enable compact parts by default for small parts. This will allow to process frequent inserts slightly more efficiently (4..100 times).

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
Performance tests:

> merge_tree_many_partitions_2

Sped up two times.

> codecs...

Various difference.

**Comment by CurtizJ** [comment]
> > codecs...
> 
> Various difference.

It's unrelated, because compact parts doesn't support columns' special codecs. Need to force creation of wide parts in those tests.

**Comment by alexey-milovidov** [comment]
> compact parts don't support columns' special codecs

But why not?

**Comment by CurtizJ** [comment]
It's possible, but we have to write comressed block for every column in granule. Won't blocks too small? Also, in that case it will be possible to count per column sizes.

**Comment by alexey-milovidov** [comment]
Ok, I understand the reason.

**Comment by alexey-milovidov** [comment]
There are plans to use ClickHouse with high-latency filesystem (e.g. S3). For that case the users may want to enable 100% compact parts. And if codecs won't work, it's a huge drawback.

**Comment by alexey-milovidov** [comment]
@CurtizJ Do you want to take this PR?

**Comment by CurtizJ** [comment]
I want to finish #12183 first, and after it will be merged enable compact parts by default.

**Comment by CurtizJ** [comment]
I don't understand why huge part of test from skip list of check with enabled compact parts are skipping now in all checks. Skip list is unchanged in this PR.

**Comment by CurtizJ** [comment]
It's because of [code](https://github.com/ClickHouse/ClickHouse/blob/87b3984d1776545fa3bd05ec23317d556ef4bcfd/tests/clickhouse-test#L509-L516)in `clickhouse-test` script.

**Comment by CurtizJ** [comment]
```00926_adaptive_index_granularity_pk:                                    [ FAIL ] 670.21 sec. - Timeout!```

In this test a table with `index_granularity_bytes=40` is created, which leads to `index_granularity=1`. With compact parts this configuration is extremely inefficient, because of writing compressed block for every granule of column. It is not a regular case and performance tests didn't show regressions with default settings, when this behaviour was introduced and I think it's ok.

Maybe we need introduce a setting to allow set behaviour, when compressed block is written only when threshold is exceded.

**Comment by CurtizJ** [comment]
The same about `00804_test_alter_compression_codecs`.

**Comment by CurtizJ** [comment]
Other fixed tests checked some implementation defined things like checksums or number of files or hardcoded paths to files. Also some compatibility tests, which run cluster with different versions older than 20.3, were failed, because replication protocol is incompatible with such old versions, when polymorphic parts are used.
Didn't find any real bugs.

**Comment by alexey-milovidov** [comment]
@akuzm AST Fuzzer:
`2020-09-18 08:00:36 ERROR 404: Not Found.`

**Comment by alexey-milovidov** [comment]
@CurtizJ I suspect that this PR has broke integration tests:
https://github.com/ClickHouse/ClickHouse/commit/eb9ee723c37b0c616cd7d81a82982adb0fd94499 (look at this commit in master)

**Pull request merged**
