### PR TITLE
Prototype lighweight mutation for mergetree

### PR DESCRIPTION
**Pull request by zhangjmruc**
Changelog category (leave one):
- New Feature

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
prototype of implementation of lightweight delete and update for merge tree engine.

Description:
This pull request does similar work as #32774.

### CODE REVIEW

**Comment by antip00** [comment]
https://gist.github.com/antip00/8f27cb269aa0bf383079c61b96260fb1

**Comment by zhangjmruc** [comment]
I recreated your issue. Will check further and fix it.

> alter table au delete where id>50

> it does not work for me
> 
> create table au(id Int64, x Int64) engine=MergeTree order by id
> 
> insert into au select number % 10, number % 100 from numbers(10000)
> 
> alter table au delete where id>50
> 
> if you use alter delete with mutation_sync=1 or mutation_sync=2 then it breaks on alter delete
> 
> select count(*) from au
> 
> it is stuck for a few mins then exeption Exception on client: Code: 32. DB::Exception: Attempt to read after eof: while receiving packet from localhost:9000. (ATTEMPT_TO_READ_AFTER_EOF)
> 
> Connecting to localhost:9000 as user default. Code: 210. DB::NetException: Connection reset by peer, while reading from socket (127.0.0.1:9000). (NETWORK_ERROR)

**Comment by zhangjmruc** [comment]
> it does not work for me
> 
> create table au(id Int64, x Int64) engine=MergeTree order by id
> 
> insert into au select number % 10, number % 100 from numbers(10000)
> 
> alter table au delete where id>50
> 
> if you use alter delete with mutation_sync=1 or mutation_sync=2 then it breaks on alter delete
> 
> select count(*) from au
> 
> it is stuck for a few mins then exeption Exception on client: Code: 32. DB::Exception: Attempt to read after eof: while receiving packet from localhost:9000. (ATTEMPT_TO_READ_AFTER_EOF)
> 
> Connecting to localhost:9000 as user default. Code: 210. DB::NetException: Connection reset by peer, while reading from socket (127.0.0.1:9000). (NETWORK_ERROR)

Already fixed the issue.

**Comment by zhangjmruc** [comment]
@nikitamikhaylov The failing check is not related to this request. How to proceed?

**Comment by zhangjmruc** [comment]
@davenger Are you reviewing this pull request? Please let me know if you have any comment. Thank you for your time

**Comment by zhangjmruc** [comment]
Will split into lightweight delete and lightweight update.

**Comment by vkrot-innio** [comment]
@zhangjmruc , is there any ongoing progress / plans in lightweight deletes implementation? or is it abandoned?

**Pull request closed without merging**
