### PR TITLE
Rename arrayAUC to arrayROCAUC and add alias

### PR DESCRIPTION
**Pull request by emmanuelsdias**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
The existing `arrayAUC` function calculated the AUC for the ROC curve. The function was renamed to `arrayROCAUC` and `arrayAUC` was kept as an alias.

### Documentation entry for user-facing changes

- [X] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Run only fuzzers related jobs (libFuzzer fuzzers, AST fuzzers, etc.)
- [ ]  Exclude: AST fuzzers
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-clickhouse-ci-1** [comment]
*This is an automated comment for commit 12e6a39d489468dd2f0db06195f281268d6740c5 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/71910/12e6a39d489468dd2f0db06195f281268d6740c5/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Style check</td><td>Runs a set of checks to keep the code style clean. If some of tests failed, see the related log from the report</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/71910/12e6a39d489468dd2f0db06195f281268d6740c5/style_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Comment by emmanuelsdias** [comment]
> I'm not sure about naming. @alexey-milovidov WDYT?
> arrayRocAUC or arrayROCAUC. I agree that the first one is more readable but inconsistent.

Could you check this when you have some time, @alexey-milovidov? 
It would be nice to have this determined to use with the same formatting on the PR AUC (https://github.com/ClickHouse/ClickHouse/pull/72073)

**Comment by pufit** [comment]
After some discussions with @nikitamikhaylov, we came to the consensus that the name should be `arrayROCAUC` because otherwise, the naming is too inconsistent

**Comment by rschu1ze** [comment]
I'll integrate this PR into #72950.

**Pull request closed without merging**
