### PR TITLE
Merging #34372

### PR DESCRIPTION
**Pull request by nikitamikhaylov**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Merging #34372

### CODE REVIEW

**Comment by nikitamikhaylov** [comment]
@Mergifyio update

**Comment by nikitamikhaylov** [comment]
Wait for Docs Check

**Comment by qoega** [comment]
@nikitamikhaylov can you resolve conflict?

**Comment by alexey-milovidov** [comment]
@qoega I have resolved the conflict.

**Pull request merged**
