### PR TITLE
Cache thread name to avoid prctl(PR_GET_NAME) for query_log/text_log

### PR DESCRIPTION
**Pull request by azat**
Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
LGTM.

If you have any data about the improvement - please post it here.
(Currently the change looks unmotivated).

**Comment by azat** [comment]
>If you have any data about the improvement - please post it here.

@alexey-milovidov this is just to avoid extra syscalls for log entries.

**Comment by azat** [comment]
>Functional stateless tests (thread) — Timeout, fail: 0, passed: 1529, skipped: 6
>Integration tests (asan) — fail: 1, passed: 1573, flaky: 16
>Integration tests (release) — fail: 1, passed: 1574, flaky: 17
>Integration tests (thread) — fail: 3, passed: 1569, flaky: 20

Same issues in master

**Comment by azat** [comment]
>Stress test (undefined) — Hung check failed

```
Row 1:
elapsed:              1255.146479041
query:                INSERT INTO mutations_and_quorum1 VALUES
thread_ids:           [7563]
current_database:     test_7d91qg

Row 2:
elapsed:              954.579029778
query:                DROP DATABASE test_7d91qg
thread_ids:           [14177] 
```

Stack traces:

<details>

```
Thread 570 (Thread 0x7fbb99fdb700 (LWP 7563)):
#0  0x00007fc2105f97b1 in pthread_cond_timedwait@@GLIBC_2.3.2 () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x000000002037be52 in Poco::EventImpl::waitImpl (this=0x7fbe843d4b38, milliseconds=<optimized out>) at ../contrib/poco/Foundation/src/Event_POSIX.cpp:157
#2  0x000000001f32efa9 in Poco::Event::tryWait (this=0x7fbe843d4b38, milliseconds=137) at ../contrib/poco/Foundation/include/Poco/Event.h:110
#3  DB::ReplicatedMergeTreeSink::waitForQuorum (this=this@entry=0x7fbe700229d8, zookeeper=..., part_name=..., quorum_path=..., is_active_node_value=...) at ../src/Storages/MergeTree/ReplicatedMergeTreeSink.cpp:543
#4  0x000000001f32c5fb in DB::ReplicatedMergeTreeSink::commitPart (this=<optimized out>, this@entry=0x7fbe700229d8, zookeeper=..., part=..., block_id=...) at ../src/Storages/MergeTree/ReplicatedMergeTreeSink.cpp:503
#5  0x000000001f32608a in DB::ReplicatedMergeTreeSink::consume (this=<optimized out>, chunk=...) at ../src/Storages/MergeTree/ReplicatedMergeTreeSink.cpp:168
#6  0x000000001f53c75b in DB::ISink::work (this=0x7fbe700229d8) at ../src/Processors/ISink.cpp:47
#7  0x000000001e33f8a4 in DB::PushingToSinkBlockOutputStream::write (this=0x7fbe00691248, block=...) at ../src/DataStreams/PushingToSinkBlockOutputStream.h:40
#8  0x000000001e349d77 in DB::PushingToViewsBlockOutputStream::write (this=0x7fbe006956d8, block=...) at ../src/DataStreams/PushingToViewsBlockOutputStream.cpp:255
#9  0x000000001e345be2 in DB::AddingDefaultBlockOutputStream::write (this=<optimized out>, block=...) at ../src/DataStreams/AddingDefaultBlockOutputStream.cpp:25
#10 0x000000001e344c4f in DB::SquashingBlockOutputStream::finalize (this=this@entry=0x7fbe00138bc8) at ../src/DataStreams/SquashingBlockOutputStream.cpp:30
#11 0x000000001e3451a0 in DB::SquashingBlockOutputStream::writeSuffix (this=0x7fbe00138bc8) at ../src/DataStreams/SquashingBlockOutputStream.cpp:50
#12 0x000000001f4e23aa in DB::TCPHandler::processInsertQuery (this=this@entry=0x7fbe00141e50) at ../src/Server/TCPHandler.cpp:577
#13 0x000000001f4d6490 in DB::TCPHandler::runImpl (this=this@entry=0x7fbe00141e50) at ../src/Server/TCPHandler.cpp:299
#14 0x000000001f4f320d in DB::TCPHandler::run (this=0x7fbe00141e50) at ../src/Server/TCPHandler.cpp:1659
#15 0x00000000202ed3cc in Poco::Net::TCPServerConnection::start (this=0x7fbe843d4b90) at ../contrib/poco/Net/src/TCPServerConnection.cpp:43
#16 0x00000000202ed8ac in Poco::Net::TCPServerDispatcher::run (this=0x7fc13000b9b0) at ../contrib/poco/Net/src/TCPServerDispatcher.cpp:115
#17 0x00000000203d93ba in Poco::PooledThread::run (this=0x7fbe90416850) at ../contrib/poco/Foundation/src/ThreadPool.cpp:199
#18 0x00000000203d6f6c in Poco::ThreadImpl::runnableEntry (pThread=0x7fbe90416888) at ../contrib/poco/Foundation/src/Thread_POSIX.cpp:345
#19 0x00007fc2105f2609 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#20 0x00007fc210519293 in clone () from /lib/x86_64-linux-gnu/libc.so.6
```

</details>

Too large `insert_quorum_timeout`, should be fixed in #28540

**Comment by alexey-milovidov** [comment]
@mergifyio update

**Comment by azat** [comment]
>AST fuzzer (UBSan) — ../src/Processors/Transforms/WindowTransform.cpp:1699:54: runtime error: signed integer overflow: -9223372036854775808 - 1 cannot be represe

#28773

**Pull request merged**
