### PR TITLE
CI: Enable fuzzer job in Nightly workflow

### PR DESCRIPTION
**Pull request by maxknv**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
...

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by robot-ch-test-poll1** [comment]
*This is an automated comment for commit f0bcd9b69bd532d23ba86abd58589d4d3fc6c55b with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/72101/f0bcd9b69bd532d23ba86abd58589d4d3fc6c55b/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/567270afa8234ef2d9a0a31f61967d8c9edda849/docs_check.html">✅ success</a></td></tr>
<tr><td>Fast test</td><td>Normally this is the first check that is ran for a PR. It builds ClickHouse and runs most of <a href="https://clickhouse.com/docs/en/development/tests#functional-tests">stateless functional tests</a>, omitting some. If it fails, further checks are not started until it is fixed. Look at the report to see which tests fail, then reproduce the failure locally as described <a href="https://clickhouse.com/docs/en/development/tests#functional-test-locally">here</a></td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/b18fb82ed0c307019105068c588b0d08be27c7fa/fast_test.html">✅ success</a></td></tr>
<tr><td>Unit tests</td><td>Runs the unit tests for different release types</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/b18fb82ed0c307019105068c588b0d08be27c7fa/unit_tests__release_.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Comment by maxknv** [comment]
> have you launched it?

in progress https://github.com/ClickHouse/ClickHouse/actions/runs/11917275231/job/33211942434

**Comment by maxknv** [comment]
@yakov-olkhovskiy here is a report https://s3.amazonaws.com/clickhouse-test-reports/0/f0bcd9b69bd532d23ba86abd58589d4d3fc6c55b/libfuzzer_tests.html

**Review by Felixoid — APPROVED** [review]
looks solid

**Pull request merged**
