### PR TITLE
Testflows Extended Precision Data Type testing - Adding snapshots for output comparison.

### PR DESCRIPTION
**Pull request by MyroTk**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Not for changelog.

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
- Snapshots to check for consistent outputs.

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
@MyroTk Why TestFlows check is green before snapshots are added?

**Comment by MyroTk** [comment]
> 
> 
> @MyroTk Why TestFlows check is green before snapshots are added?
The snapshots are mostly used for checking the output of functions applied to max and min values, which sometimes cause overflow. Without the snapshots, the tests check that the overflow doesn't cause a crash. 

I didn't add snapshots at first because I thought there would be an issue with rounding, like in the previous PR, but it looks like it is fine.

**Comment by alexey-milovidov** [comment]
@mergifyio update

**Comment by MyroTk** [comment]
Testflows check is green. PR should be ready for merge.

**Pull request merged**
