### PR TITLE
alter copy partition

### PR DESCRIPTION
**Pull request by nikitamikhaylov**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- New Feature

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
This feature allows you to copy partition from one table (replicated or not) to another (replicated or not). Also it won't delete existing data in destination table. 
Needed for #9075

### CODE REVIEW

**Comment by nikitamikhaylov** [comment]
integration test doesn't work because i wrote wrong code

**Comment by qoega** [comment]
- Probably it is better rename it to APPEND, as it is closer to what operation does
- It would be great to add idempotency as INSERT does for same data. I don't want to check manually whether command was successful if my connection closed unexpectedly.

**Comment by nikitamikhaylov** [comment]
:sunglasses:

**Comment by nikitamikhaylov** [comment]
https://clickhouse.tech/docs/en/query_language/alter/#alter_attach-partition-from

**Pull request closed without merging**
