### PR TITLE
Docs: Remove obsolete comment about TPC-H Q19

### PR DESCRIPTION
**Pull request by rschu1ze**
@antaljanosbenjamin 

### Changelog category (leave one):
- Documentation (changelog entry is not required)

### CODE REVIEW

**Comment by antaljanosbenjamin** [comment]
I have to check if the pushdown actually happens though. I think my recently merged PR is just the first step towards it.

**Comment by robot-ch-test-poll3** [comment]
*This is an automated comment for commit af7e912426a8bfd20630763d67e1560459ee3e38 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/73150/af7e912426a8bfd20630763d67e1560459ee3e38/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Style check</td><td>Runs a set of checks to keep the code style clean. If some of tests failed, see the related log from the report</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/73150/af7e912426a8bfd20630763d67e1560459ee3e38/style_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Comment by rschu1ze** [comment]
Okay, let's put this PR on hold then.

**Comment by antaljanosbenjamin** [comment]
So with `optimize_extract_common_expressions = 1` the analyzer passes rewrite the query to the this:
```
SELECT sum(lineitem.l_extendedprice * (1 - lineitem.l_discount)) AS revenue,
FROM lineitem ALL
INNER JOIN part ON part.p_partkey = lineitem.l_partkey
WHERE part.p_size >= 1
  AND lineitem.l_shipmode IN ('AIR', 'AIR REG')
  AND lineitem.l_shipinstruct = 'DELIVER IN PERSON'
  AND 	(
			(
				part.p_brand = 'Brand#12'
				AND part.p_container IN ('SM CASE', 'SM BOX', 'SM PACK', 'SM PKG')
				AND lineitem.l_quantity >= 1
				AND lineitem.l_quantity <= _cast(11, 'UInt16')
				AND part.p_size <= 5
			)
			OR
			(
				part.p_brand = 'Brand#23'
				AND part.p_container IN ('MED BAG', 'MED BOX', 'MED PKG', 'MED PACK')
				AND lineitem.l_quantity >= 10
				AND lineitem.l_quantity <= _cast(20, 'UInt16')
				AND part.p_size <= 10
			)
			OR
			(	
				part.p_brand = 'Brand#34'
				AND part.p_container IN ('LG CASE', 'LG BOX', 'LG PACK', 'LG PKG')
				AND lineitem.l_quantity >= 20
				AND lineitem.l_quantity <= _cast(30, 'UInt16')
				AND part.p_size <= 15
			)
		)
```

**Comment by antaljanosbenjamin** [comment]
And this is how the plan looks like: https://pastila.nl/?000acc30/52ab6de82f2ee6171f7197f152321d57#D3er37H2IY02SJ6mvf8UxA==

So there are three possibilities regarding this part of the docs:

> As of October 2024, the query is extremely slow due to missing join predicate pushdown. Corresponding issue: https://github.com/ClickHouse/ClickHouse/issues/70802
>
> This alternative formulation works and was verified to return the reference results.

### Option 1
The first sentence (`query is extremely slow due to missing join predicate pushdown`) is correct and the alternative query doesn't work, thus the last sentence (`This alternative formulation works and was verified to return the reference results.`) is false.

### Option 2
The first sentence is false and the alternative query works, thus the slowness is not related to predicate pushdown, but more about planning joins.

### Option 3
I massively misunderstood something.

**Review by antaljanosbenjamin — APPROVED** [review]

**Comment by antaljanosbenjamin** [comment]
Yesterday I was probably tired. Technically the optimization is disabled by default, https://github.com/ClickHouse/ClickHouse/pull/71926 will turn it on by default. But I hope we will get that PR merged soon, so no need to revert this pr.

**Pull request merged**
