### PR TITLE
Improve reading from archives

### PR DESCRIPTION
**Pull request by antonio2368**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Added more supported compressions with `tar`.
Removed parallel reading from the same archive because the performance is much better without it. 

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by robot-clickhouse-ci-1** [comment]
This is an automated comment for commit 3c751b72ac305953456e066b55ed25f183feee06 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/53198/3c751b72ac305953456e066b55ed25f183feee06/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Comment by Avogar** [comment]
I went through the code of reading from archive and have some ideas to discuss:
I see in case of reading from archive in StorageFile we store paths to archives inside `paths_to_archive` and path to files inside archive in `paths` without expanding the globs (so we check files inside archives each read from storage). And I think it is quite inconvinien, and the code became compicated arout it (like using `paths` with single field with globs and creating regexp filter on each read). Maybe we can refactor this place a bit and for archives store a separate structure like map `archive -> list of files read from archive`? We can list files in archives on storage craetion, don't think it will cost a lot. 
Also there are some problems with schema inference:
1) DESCRIBE query doesn't work:
```
avogar-dev :) desc file('archive1.tar::data*.csv')

Received exception:
Code: 636. DB::Exception: Cannot extract table structure from CSV format file, because there are no files with provided path. You must specify table structure manually. (CANNOT_EXTRACT_TABLE_STRUCTURE)
```
2) During schema inference we are trying to infer schema only from the first file in arhive, so if we cannot do it, we fail instead of trying other files:
```
avogar-dev :) select * from file('archive1.tar::*.csv')

Received exception:
Code: 636. DB::Exception: Cannot extract table structure from CSV format file, file is empty. You can specify the structure manually: (in file/uri data1.csv). (CANNOT_EXTRACT_TABLE_STRUCTURE)

avogar-dev :) select * from file('archive1.tar::data2.csv')

┌─c1─┐
│ 42 │
└────┘

```

3) Schema inference from archives pollute schema cache. It stores schema by path inside archive (possibly with globs) and it can break schema inference for files inside other archives with same files (or even with files not from archive with same path).
```

avogar-dev :) select * from file('archive2.tar::data3.csv')

┌─c1─┐
│ 42 │
└────┘

avogar-dev :) select * from file('archive2.tar::*.csv')

┌─c1─┐
│ 42 │
└────┘
┌─c1─┐
│ 42 │
└────┘

avogar-dev :) select source from system.schema_inference_cache

┌─source────┐
│ data3.csv │
│ *.csv     │
└───────────┘

```

 But instead we should store inferred schema for each file in archive and add path to archive to the key in cache (so it will be smth like `/path/to/archive::path/to/file`

I don't think the original author of this feature will do it, so we can do it in this PR if you have time, or I can make it in a separate PR when I have time

**Comment by antonio2368** [comment]
@Avogar thanks for the detailed review!
Agree with all the points you mentioned, especially that it feels hacked around with how the variables are used.
I will make those changes, no worries but I'm just interested if I should make it as part of this PR because I'm not sure if I'll make it before the next release.
In this PR I primarily removed parallel reading from the same archive to have a good performance for this feature. 
If we are going to push this feature as part of this release I would like to merge this PR and continue with improvements in another PR. This feature already seems usable to me and really interesting to showcase.
But if you think it needs to be delayed I'm also okay with it, let's just not show the current master in the release webinar which can be really slow in some cases.
cc @alexey-milovidov

**Comment by alexey-milovidov** [comment]
Yes, let's make it before the release, which is scheduled on Aug 31st.

**Review by Avogar — APPROVED** [review]
LGTM, let's merge and fix remaining issues in the next PR

**Comment by antonio2368** [comment]
> Maybe we can refactor this place a bit and for archives store a separate structure like map archive -> list of files read from archive? We can list files in archives on storage creation, don't think it will cost a lot.

One downside I see for it is that if the archive gets changed, we won't be able to read new files. Are we okay with that?

**Comment by alexey-milovidov** [comment]
Yes, this is ok for me - changing archives is a very minor use-case.

**Comment by Avogar** [comment]
Ahh, so some archives doesn't support reading files by names, so we need to iterate through all files again while reading even if we already know all files we want to read?
I didn't think about it, so yes, my idea wan't so good. I think we can create a filter during StorageFile construction, but why do we need a mutex for it? The filter should not be changed after it's created

**Pull request merged**
