### PR TITLE
MaterializedPostgreSQL: remove back check

### PR DESCRIPTION
**Pull request by kssenii**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by robot-clickhouse-ci-2** [comment]
*This is an automated comment for commit f0747b7a6e041973856beb30752e319cf4220866 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/55297/f0747b7a6e041973856beb30752e319cf4220866/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td><a href="https://github.com/ClickHouse/ClickHouse/actions/runs/6441162816">✅ success</a></td></tr>
<tbody>
</table>
</details>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/55297/f0747b7a6e041973856beb30752e319cf4220866/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Comment by alexey-milovidov** [comment]
I don't understand the change - was the check incorrect?
If it was ok, why don't keep it?

**Review by alexey-milovidov — APPROVED** [review]
The diff LGTM.

**Comment by kssenii** [comment]
> I don't understand the change - was the check incorrect?
If it was ok, why don't keep it?

the check was correct in all cases except one: if we have TOAST values.

**Pull request merged**
