### PR TITLE
Jepsen label

### PR DESCRIPTION
**Pull request by Felixoid**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Jepsen test is in the concurrency group and cancels PR workflows frequently. We need to completely skip it when there's no label.

### CODE REVIEW

**Comment by Felixoid** [comment]
It's skipped when the label is omitted https://github.com/ClickHouse/ClickHouse/runs/7585161043?check_suite_focus=true

**Comment by Felixoid** [comment]
And it's here when the label is in place https://github.com/ClickHouse/ClickHouse/runs/7586024067?check_suite_focus=true

**Review by antonio2368 — APPROVED** [review]
beautiful

**Comment by antonio2368** [comment]
Let's merge this?

**Pull request merged**
