### PR TITLE
Revert "Merge pull request #57907 from azat/system.stack_trace-rt_tgsigqueueinfo"

### PR DESCRIPTION
**Pull request by alexey-milovidov**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Our CI is broken - I will try to revert anything suspicious.
See https://s3.amazonaws.com/clickhouse-test-reports/57964/61e5db9cd0e03c272dff0f7d00d686d9f9e95a83/stateless_tests__release_.html

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
CC @azat

**Comment by robot-ch-test-poll1** [comment]
*This is an automated comment for commit 2859ac08c9ed79149308200aabae09ddd65b44db with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/57974/2859ac08c9ed79149308200aabae09ddd65b44db/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td><a href="https://github.com/ClickHouse/ClickHouse/actions/runs/7242242236">✅ success</a></td></tr>
<tbody>
</table>
</details>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/57974/2859ac08c9ed79149308200aabae09ddd65b44db/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Comment by alexey-milovidov** [comment]
Wow, it helped!

> Stateless tests (release) — fail: 0, passed: 5936, skipped: 4

**Comment by azat** [comment]
Likely there are threads that blocks this signal, and the stack trace collecting in clickhouse-test simply contains "trash" data (though clickhouse-test has timeout for this query, but it is 30 seconds, and 60 retries, this is only half an hour, not 2 hours like you wrote)
Unlikely, but is there any chance that server logs could be obtained for that builds?

**Comment by azat** [comment]
Timeouts does not works correctly 100% there, while the query takes ~1min each (but still it is 1 hour not 2, whatever):

```sql
$ zstd -cdq clickhouse-server.log.zst | grep -F -a b7c4c147-903a-4eac-9a35-81f5b66844b0 | head -1
2023.12.17 00:19:10.969741 [ 418298 ] {b7c4c147-903a-4eac-9a35-81f5b66844b0} <Debug> executeQuery: (from [::1]:37706)  SELECT p.*, arrayStringConcat(groupArray('Thread ID ' || toString(s.thread_id) || '
$ zstd -cdq clickhouse-server.log.zst | grep -F -a b7c4c147-903a-4eac-9a35-81f5b66844b0 | wc -l
316
$ zstd -cdq clickhouse-server.log.zst | grep -F -a b7c4c147-903a-4eac-9a35-81f5b66844b0 | tail
2023.12.17 00:20:18.923769 [ 247423 ] {b7c4c147-903a-4eac-9a35-81f5b66844b0} <Debug> StorageSystemStackTrace: Cannot obtain a stack trace for thread 253368
2023.12.17 00:20:19.023949 [ 247423 ] {b7c4c147-903a-4eac-9a35-81f5b66844b0} <Debug> StorageSystemStackTrace: Cannot obtain a stack trace for thread 253764
2023.12.17 00:20:19.124121 [ 247423 ] {b7c4c147-903a-4eac-9a35-81f5b66844b0} <Debug> StorageSystemStackTrace: Cannot obtain a stack trace for thread 253767
2023.12.17 00:20:19.224288 [ 247423 ] {b7c4c147-903a-4eac-9a35-81f5b66844b0} <Debug> StorageSystemStackTrace: Cannot obtain a stack trace for thread 256029
2023.12.17 00:20:19.324463 [ 247423 ] {b7c4c147-903a-4eac-9a35-81f5b66844b0} <Debug> StorageSystemStackTrace: Cannot obtain a stack trace for thread 256209
2023.12.17 00:20:19.424646 [ 247423 ] {b7c4c147-903a-4eac-9a35-81f5b66844b0} <Debug> StorageSystemStackTrace: Cannot obtain a stack trace for thread 258973
2023.12.17 00:20:19.524816 [ 247423 ] {b7c4c147-903a-4eac-9a35-81f5b66844b0} <Debug> StorageSystemStackTrace: Cannot obtain a stack trace for thread 260059
2023.12.17 00:20:19.723426 [ 247423 ] {b7c4c147-903a-4eac-9a35-81f5b66844b0} <Debug> StorageSystemStackTrace: Cannot obtain a stack trace for thread 260060
2023.12.17 00:20:19.823598 [ 247423 ] {b7c4c147-903a-4eac-9a35-81f5b66844b0} <Debug> StorageSystemStackTrace: Cannot obtain a stack trace for thread 262086
2023.12.17 00:20:19.923797 [ 247423 ] {b7c4c147-903a-4eac-9a35-81f5b66844b0} <Debug> StorageSystemStackTrace: Cannot obtain a stack trace for thread 262088
```

**Pull request merged**
