### PR TITLE
Fix toStartOfInterval

### LINKED ISSUE #60366: toStartOfInterval returns wrong result when interval is in miliseconds
The following two queries return different values with Clickhouse server 24.1
`select toStartOfInterval(toDateTime64('2015-01-01 00:01:34', 9), interval 100000 MILLISECONDS)`
`select toStartOfInterval(toDateTime64('2015-01-01 00:01:34', 9), interval 100 second)`

https://fiddle.clickhouse.com/00959742-a277-4ff9-9c37-28315f3fbc53

The second version is correct.

This issue doesn't exist with 23.12 or prior version.

### PR DESCRIPTION
**Pull request by zvonand**
Fixes #60366. Follow-up #58557.

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
One more fix for toStartOfInterval returning wrong result for interval smaller than second.

### CODE REVIEW

**Comment by zvonand** [comment]
@alexey-milovidov could you please add a `can-be-tested`?

**Comment by robot-clickhouse-ci-1** [comment]
*This is an automated comment for commit 4e55f2c90dae6b3c52e6af0107993613cd8b563a with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/60763/4e55f2c90dae6b3c52e6af0107993613cd8b563a/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

**Comment by zvonand** [comment]
* Stateless tests (debug) [3/5]
  - `01508_partition_pruning_long` -- #60854
  - `02125_lz4_compression_bug` -- looks like server died: `DB::NetException: Connection reset by peer, while reading from socket ([::1]:60804). (NETWORK_ERROR) (version 24.3.1.1) (from [::1]:60804) (comment: 02125_lz4_compression_bug.sh) (in query: SELECT max(x) FROM file)`

* Stateless tests (tsan, s3 storage) [1/5] 
  - `02784_parallel_replicas_automatic_decision_join` -- #60625
* Stress test (debug)
* AST fuzzer (ubsan)

**Comment by zvonand** [comment]
@yariks5s looks like tests are OK. Take a look pls

**Pull request merged**
