### PR TITLE
Correct an exception message in src/Functions/nested.cpp

### PR DESCRIPTION
**Pull request by Alex-Cheng**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
The exception message indicates 'argument 1' which is 0-based, actually for users and consistency with other exception messages the index of argument in message should be 1-based. Thus 'argument 1' should be changed to 'argument 2'.

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
```
.examples{{"nested", "SELECT nested(['keys', 'values'], ['key_1', 'key_2'], ['value_1','value_2'])
```

Missing whitespace.

```
factory.registerFunction<FunctionNested>(FunctionDocumentation{
        .description=R"(
Returns the array of tuples from multiple arrays.
)",
        .examples{{"nested", "SELECT nested(['keys', 'values'], ['key_1', 'key_2'], ['value_1','value_2'])", ""}},
        .categories{"OtherFunctions"}
});
```

I don't understand this documentation.

Should the function be named `zip` like in other programming languages?
Should the function be named `zipWithNames`?

Why do we have to provide names as the first argument, instead of constructing an unnamed tuple, and then casting the result?

**Comment by Alex-Cheng** [comment]
> ```
> .examples{{"nested", "SELECT nested(['keys', 'values'], ['key_1', 'key_2'], ['value_1','value_2'])
> ```
> 
> Missing whitespace.
> 
> ```
> factory.registerFunction<FunctionNested>(FunctionDocumentation{
>         .description=R"(
> Returns the array of tuples from multiple arrays.
> )",
>         .examples{{"nested", "SELECT nested(['keys', 'values'], ['key_1', 'key_2'], ['value_1','value_2'])", ""}},
>         .categories{"OtherFunctions"}
> });
> ```
> 
> I don't understand this documentation.
> 
> Should the function be named `zip` like in other programming languages? Should the function be named `zipWithNames`?
> 
> Why do we have to provide names as the first argument, instead of constructing an unnamed tuple, and then casting the result?

I don't know the documentation. I just find an small error in the exception message and correct it.
image

**Comment by Alex-Cheng** [comment]
> > ```
> > .examples{{"nested", "SELECT nested(['keys', 'values'], ['key_1', 'key_2'], ['value_1','value_2'])
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Missing whitespace.
> > ```
> > factory.registerFunction<FunctionNested>(FunctionDocumentation{
> >         .description=R"(
> > Returns the array of tuples from multiple arrays.
> > )",
> >         .examples{{"nested", "SELECT nested(['keys', 'values'], ['key_1', 'key_2'], ['value_1','value_2'])", ""}},
> >         .categories{"OtherFunctions"}
> > });
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I don't understand this documentation.
> > Should the function be named `zip` like in other programming languages? Should the function be named `zipWithNames`?
> > Why do we have to provide names as the first argument, instead of constructing an unnamed tuple, and then casting the result?
> 
> I don't know the documentation. I just find an small error in the exception message and correct it. image

Anyway, the error in exception message is obvious. I think we should correct it anyway.

**Review by evillique — APPROVED** [review]

**Comment by robot-clickhouse** [comment]
This is an automated comment for commit e28a95d2ffe635b006d5e80c05e1f5b3946b26a3 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/51651/e28a95d2ffe635b006d5e80c05e1f5b3946b26a3/ci_running.html)
The overall status of the commit is 🔴 failure

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🔴 failure</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Comment by Alex-Cheng** [comment]
I just made a little change, why it is blocked by failure of checks?

**Comment by Alex-Cheng** [comment]
testcase `02360_send_logs_level_colors` failed but has nothing to do with my PR.

**Pull request merged**
