### PR TITLE
Add prefer_global_in_and_join setting

### PR DESCRIPTION
**Pull request by amosbird**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- New Feature

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Add a new boolean setting `prefer_global_in_and_join` which defaults all IN/JOIN as GLOBAL IN/JOIN.

Detailed description / Documentation draft:

.

### CODE REVIEW

**Comment by filimonov** [comment]
Can you clarify/highlight the difference with distributed_product_mode=global?

**Comment by amosbird** [comment]
> Can you clarify/highlight the difference with distributed_product_mode=global?

`distributed_product_mode` is to control the behavior when we see other distributed tables in a distributed query. However, it's not enough in some cases. For example, we have query serving nodes that contains local tables which are not suitable to distributed. We need to scatter the data on-the-fly with global in/join. Another use case of `prefer_global_in_and_join` is external tables. Some of our setups have all dimensional tables designed as engine MySQL, it would be nice to only query external sources once per query.

**Comment by alexey-milovidov** [comment]
I understand this scenario - this is reasonable.
Although I have some concerns about how well the setting will be understandable by users.

**Comment by alexey-milovidov** [comment]
I'm ok adding this setting but let's describe its usages as clear as possible.

**Comment by amosbird** [comment]
> I'm ok adding this setting but let's describe its usages as clear as possible (directly in Settings.h).

Yeah. I hope now the documentation is clear.

**Comment by sevirov** [comment]
Internal documentation ticket: DOCSUP-10514.

**Pull request merged**
