### PR TITLE
Avoid hangs of system.stack_trace by correctly prohibit parallel read from it

### PR DESCRIPTION
**Pull request by azat**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Prohibit parallel read from system.stack_trace (otherwise this will lead to hang of system.stack_trace table up to `storage_system_stack_trace_pipe_read_timeout_ms`)

Before rewriting system.stack_trace to handle max_block_size (in #54946)
parallel reading from system.stack_trace was prohibited, because this
could lead to hang of system.stack_trace table.

But that rewrite broke this guarantee, so let's fix it to avoid possible
hung.

Fixes: https://github.com/ClickHouse/ClickHouse/pull/54946 (cc @alexey-milovidov )

### CODE REVIEW

**Comment by robot-ch-test-poll1** [comment]
*This is an automated comment for commit 215cd90bed8af648c8c5354dae434aff4faddb78 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/57641/215cd90bed8af648c8c5354dae434aff4faddb78/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td><a href="https://github.com/ClickHouse/ClickHouse/actions/runs/7134451622">✅ success</a></td></tr>
<tbody>
</table>
</details>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/57641/215cd90bed8af648c8c5354dae434aff4faddb78/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Comment by alexey-milovidov** [comment]
Ok. Did you mean it was already prohibited, but then we made the `generate` function run multiple times, and this property was lost?

**Comment by azat** [comment]
> Did you mean it was already prohibited, but then we made the generate function run multiple times, and this property was lost?

Yes, it had been broken during adding support of max_block_size.

Actually the code looks complex, I think it could be simplified, I will submit another PR after this one (not to mix bug fixes with other changes).

**Comment by azat** [comment]
> [Integration tests (asan, analyzer) [1/6] — fail: 38, passed: 75]https://s3.amazonaws.com/clickhouse-test-reports/57641/2a850040a3ae38ee1392f90b14f5524318ca3a83/integration_tests__asan__analyzer__[1_6].html)

```
==================================== ERRORS ====================================
______________ ERROR at setup of test_allowed_databases[configs] _______________
[gw0] linux -- Python 3.10.12 /usr/bin/python3

request = <SubRequest 'test_cluster' for <Function test_allowed_databases[configs]>>

    @pytest.fixture(scope="module", params=["configs", "configs_secure"])
    def test_cluster(request):
        cluster = ClickHouseClusterWithDDLHelpers(__file__, request.param, request.param)
    
        try:
>           cluster.prepare()

test_distributed_ddl/test.py:19: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
test_distributed_ddl/cluster.py:64: in prepare
    self.pm_random_drops._add_rule(
helpers/network.py:94: in _add_rule
    _NetworkManager.get().add_iptables_rule(**rule)
helpers/network.py:156: in add_iptables_rule
    self._exec_run(cmd, privileged=True)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <helpers.network._NetworkManager object at 0x7fb62f674700>
cmd = ['iptables', '--wait', '-I', 'DOCKER-USER', '1', '-m', ...]
kwargs = {'privileged': True}, container = <Container: 27b1d483719d>
handle = {'Id': '3aaca46e2dbf426b7867b97e5d102fe8741ed2ae074a92f96d253e19766b1855'}
output = 'OCI runtime exec failed: exec failed: unable to start container process: exec: "iptables": executable file not found in $PATH: unknown\r\n'
```

**Comment by azat** [comment]
Test failures are not related:

>AST fuzzer (asan) — Logical error: 'Sorting column 1025_UInt16 wasn't found in the ActionsDAG's outputs. DAG:

- https://github.com/ClickHouse/ClickHouse/issues/57705

>ClickHouse Integration Tests (release) [2/4] for [PR #57641](https://github.com/ClickHouse/ClickHouse/pull/57641)

- `test_storage_kafka/test.py::test_system_kafka_consumers_rebalance`
- `test_dictionaries_update_and_reload/test.py::test_reload_while_loading`

>ClickHouse Stateful Tests (ubsan, ParallelReplicas) for [PR #57641](https://github.com/ClickHouse/ClickHouse/pull/57641)

- `00180_no_seek_avoiding_when_reading_from_cache`

```
2023.12.09 03:43:30.561814 [ 2852 ] {5b525c49-52da-4a1e-a37b-7b462324b7e9} <Fatal> : Logical error: 'file_offset_of_buffer_end <= read_until_position'.
```

- https://github.com/ClickHouse/ClickHouse/issues/57508

**Review by alexey-milovidov — APPROVED** [review]

**Pull request merged**
