### PR TITLE
#2 Added new tests for session_log and fixed the inconsistency between login and logout.

### PR DESCRIPTION
**Pull request by Demilivor**
Preivous PR was here:
https://github.com/ClickHouse/ClickHouse/pull/52958 Then the changes from PR were reverted here: https://github.com/ClickHouse/ClickHouse/pull/53247

Changes between this and the previous PR:
added the `no-debug `tag to the `02833_concurrrent_sessions` and `02835_drop_user_during_session` tests.
These tests require enough performance to run the required actions. I ran 100 times on my machine with the default build and got no failures.

------------------------------------------------------
Added several new tests for session_log and fixed the inconsistency of the session_log records between user login and logout.

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fixed the record inconsistency in session_log between login and logout.

Inconsistency comes from this behavior:
During a TCP session, the client authenticates as `Alice`,  with interface 'TCP' (set in `TCPHandler::makeSession()`) on the server side, and then server calls makeSessionContext() with this client_info.
After session setup, the client sends `Protocol::Client::Query` packet, the TCP handler accepts it, and then **reads client_info**.

```cpp
    ClientInfo client_info = session->getClientInfo(); 
    if (client_tcp_protocol_version >= DBMS_MIN_REVISION_WITH_CLIENT_INFO)
        client_info.read(*in, client_tcp_protocol_version); // <- overwrites interface,  hostname, client_name and several other parameters important for the session_log record.
```

`client_tcp_protocol_version >= DBMS_MIN_REVISION_WITH_CLIENT_INFO is true for our case`

This `client_info` is used for `Session::createQueryContext` and it can differ from session->getClientInfo().

Session::createQueryContext uses client info from `query_context` for the Login Success session log record.
Session::~Session uses client info from `Session::getClientInfo()`

This can lead to these results in the session log:
```
Login Success: User Alice, HTTP (from query_context) <- Some fields are overwritten by client_info.read() by some not-good clients.
Logout:  User Alice, TCP (from session_context)
```

This pull request forces using `Session::getClientInfo()` for login success and logout `session_log` records.

I think we should verify `client_info` from the client in `TCPHandler`. It should validate 'interface' at least, it should not be HTTP, GRPC, or other, host, client_name, and protocol versions also must match between session->getClientInfo() and received client_info.

### CODE REVIEW

**Comment by Demilivor** [comment]
Good day @tavplubix could you please be the reviewer in this PR?

Changes between this and the previous PR:
Added the `no-debug` tag to the `02833_concurrrent_sessions` and `02835_drop_user_during_session` tests.

**Comment by robot-clickhouse-ci-1** [comment]
This is an automated comment for commit d499f8030a34d5076c7a9fc97d94a5f04b2898d6 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/53255/d499f8030a34d5076c7a9fc97d94a5f04b2898d6/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Review by tavplubix — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
It failed: https://s3.amazonaws.com/clickhouse-test-reports/0/c3c41253281bd3fb7f9209ac9bb4482db6597d6f/integration_tests__asan__[2_6].html

**Comment by Demilivor** [comment]
This fail comes from `test_session_log/test.py::test_postgres_session`
```
>       conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
E       psycopg2.OperationalError: connection to server at "172.16.1.2", port 5433 failed: Connection refused
E       	Is the server running on that host and accepting TCP/IP connections?
```

Postgres connection is failed. ClickHouse server was not even involved in this, It did not even receive a query.  I don't see any related error in the clickhouse logs.

**Comment by Demilivor** [comment]
I can't guess why the connection from `py_sql` to ClickHouse failed, yet it always worked before (no changes in this test were made).

I want to avoid consuming the time of myself and other engineers to create new PRs, review them, and then revert them.
I consider my changes to be useful. Let's find a way out of this situation. I propose making several small pull requests instead of one pool request with bug fixes and tests:
1) 1 for bugfix without tests (all existing tests will continue to work)
2) One PR for each individual test, including `test_session_log/test.py::test_postgres_session`. I don't observe any bugs in the test code of `test_session_log/test.py::test_postgres_session`. This fail looks like a random, occasional error. But If you wish, I may not add this test at all, and PostgreSQL session log verification will not be tested.

**Comment by alexey-milovidov** [comment]
Yes, this will work. Let's submit fixes without unstable parts of the tests first.
It will not allow us to remove the warning about the session log, but we will get at least something.

**Comment by alexey-milovidov** [comment]
> This fail looks like a random, occasional error.

Random occasional errors exist in our infrastructure due to hardware failures in AWS, regional outages, and similar, but this is not the case.

**Comment by alexey-milovidov** [comment]
The test has failed four times over a short period:

| check_start_time | check_name | test_name | report_url |
|-:|:-|:-|:-|
| 2023-08-10 20:44:35 | Integration tests (asan) [2/6] | test_session_log/test.py::test_postgres_session | https://s3.amazonaws.com/clickhouse-test-reports/0/c3c41253281bd3fb7f9209ac9bb4482db6597d6f/integration_tests__asan__[2_6].html |
| 2023-08-10 20:46:19 | Integration tests (asan, analyzer) [2/6] | test_session_log/test.py::test_postgres_session | https://s3.amazonaws.com/clickhouse-test-reports/0/c3c41253281bd3fb7f9209ac9bb4482db6597d6f/integration_tests__asan__analyzer__[2_6].html |
| 2023-08-11 00:49:03 | Integration tests (asan, analyzer) [2/6] | test_session_log/test.py::test_postgres_session | https://s3.amazonaws.com/clickhouse-test-reports/0/fd7b92e90aab592594712b074a51ccd00bde5fd5/integration_tests__asan__analyzer__[2_6].html |
| 2023-08-11 00:52:07 | Integration tests (tsan) [2/6] | test_session_log/test.py::test_postgres_session | https://s3.amazonaws.com/clickhouse-test-reports/0/fd7b92e90aab592594712b074a51ccd00bde5fd5/integration_tests__tsan__[2_6].html |

https://play.clickhouse.com/play?user=play#U0VMRUNUIGNoZWNrX3N0YXJ0X3RpbWUsIGNoZWNrX25hbWUsIHRlc3RfbmFtZSwgcmVwb3J0X3VybApGUk9NIGNoZWNrcwpXSEVSRSBjaGVja19zdGFydF90aW1lID49IG5vdygpIC0gSU5URVJWQUwgMjQgSE9VUgogICAgQU5EIHB1bGxfcmVxdWVzdF9udW1iZXIgPSAwCiAgICBBTkQgdGVzdF9zdGF0dXMgIT0gJ1NLSVBQRUQnCiAgICBBTkQgdGVzdF9zdGF0dXMgTElLRSAnRiUnCiAgICBBTkQgY2hlY2tfc3RhdHVzICE9ICdzdWNjZXNzJwogICAgQU5EIHBvc2l0aW9uKHRlc3RfbmFtZSwgJ3Nlc3Npb25fbG9nJykgPiAwCk9SREVSIEJZIGNoZWNrX3N0YXJ0X3RpbWUKRk9STUFUIE1hcmtkb3du

**Comment by Demilivor** [comment]
Thanks for finding these failures. I Agree that something is wrong, I'm trying to figure it out right now, but I still have no clue why it happens. 4 Failures Is too many. 


Clickhouse definitely listens to PostgreSQL  `0.0.0.0:5433
```
2023.08.10 21:16:32.670516 [ 1 ] {} <Information> Application: Listening for PostgreSQL compatibility protocol: 0.0.0.0:5433
```


But in every log, I see the same error:
```
E       psycopg2.OperationalError: connection to server at "172.16.1.2", port 5433 failed: Connection refused
E        Is the server running on that host and accepting TCP/IP connections?
```
Clickhouse server logs do not contain anything that could help me find the root cause of the problem.

**Comment by Demilivor** [comment]
This is my test server log: [valid_log.txt](https://github.com/ClickHouse/ClickHouse/files/12318219/valid_log.txt)

When the Postgres connection is established, I see this message: 
`2023.08.10 04:29:48.123985 [ 10 ] {} <Trace> PostgreSQLHandlerFactory: PostgreSQL connection. Id: 0. Address: 172.16.1.1:62290`

This message might catch an eye, but it is always contained in the log:
`2023.08.10 04:29:46.845817 [ 8 ] {} <Information> TCPHandler: Client has not sent any data.` I don't think it relates to the PostgreSQL connection.

**Comment by Demilivor** [comment]
Thanks! I did not know that. I just launched my ` *sh` tests with thread fuzzer 10 times and got no fail (time increased more than 5 times with [default settings](https://github.com/ClickHouse/ClickHouse/blob/2389e0f0b68d03ecbb117745ed00c54979715ea7/docker/test/stateless/run.sh#L39-L61))

**Comment by Demilivor** [comment]
Bug fix PR:
https://github.com/ClickHouse/ClickHouse/pull/53302

**Comment by Demilivor** [comment]
Separate pull requests for each individual test:

- Added test for session_log using remote and mysql sessions https://github.com/ClickHouse/ClickHouse/pull/53304
- Added integration test for session_log using concurrrent GRPC/PostgreSQL/MySQL sessions https://github.com/ClickHouse/ClickHouse/pull/53305
- Added test for session_log using concurrrent TCP/HTTP/MySQL sessions https://github.com/ClickHouse/ClickHouse/pull/53306
- Added test for session_log dropping user/role/profile currently used in active session https://github.com/ClickHouse/ClickHouse/pull/53307

I will unmark those changes as 'DRAFT' after [bugfix PR](https://github.com/ClickHouse/ClickHouse/pull/53302) will be merged

**Comment by Demilivor** [comment]
ClickHouse several PostgreSQL tests broken:

https://github.com/ClickHouse/ClickHouse/blob/33763e7e50d283d2ad08b7e831c9494c9043ba2f/tests/analyzer_integration_broken_tests.txt#L98C6-L98C25

https://github.com/ClickHouse/ClickHouse/blob/33763e7e50d283d2ad08b7e831c9494c9043ba2f/tests/analyzer_integration_broken_tests.txt#L85

These tests use psycopg2 library for Postgres communication. For my purposes, it is not necessary to use it, but it is the easiest way to achieve my goal.

P.S. Another test, `max session for user` also uses this library:
https://github.com/ClickHouse/ClickHouse/blob/33763e7e50d283d2ad08b7e831c9494c9043ba2f/tests/integration/test_profile_max_sessions_for_user/test.py#L127-L133

I can rewrite the test using native PostgreSQL client `psql`.

**Pull request merged**
