### PR TITLE
Provide important performance hint max_rows_in_set

### PR DESCRIPTION
**Pull request by gauravphoenix**
this is important when global in queries return a large amount of data

Changelog category (leave one):
- Documentation (changelog entry is not required)

### CODE REVIEW

**Comment by kitaisreal** [comment]
@Mergifyio update

**Comment by kitaisreal** [comment]
https://github.com/Mergifyio update

**Comment by kitaisreal** [comment]
@Mergifyio update

**Comment by Felixoid** [comment]
@Mergifyio update

**Comment by kitaisreal** [comment]
https://github.com/Mergifyio update

**Comment by kitaisreal** [comment]
@Mergifyio update

**Review by kitaisreal — APPROVED** [review]

**Pull request merged**
