### PR TITLE
Enabling Kerberos Testflows tests

### PR DESCRIPTION
**Pull request by zvonand**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Build/Testing/Packaging Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Enabling Testflows tests for Kerberos support

Detailed description / Documentation draft:
Enabling Testflows tests for Kerberos support

### CODE REVIEW

**Comment by vitlibar** [comment]
@zvonand How's your progress with enabling the testflows tests? The PR seems abandoned...

**Comment by zvonand** [comment]
> @zvonand How's your progress with enabling the testflows tests? The PR seems abandoned...

WiP

**Comment by alexey-milovidov** [comment]
@zvonand These tests take 3210 seconds of time to run. Why it's needed?

**Comment by zvonand** [comment]
> @zvonand These tests take 3210 seconds of time to run. Why it's needed?

This is completely CICD's fault
They take about 30 seconds on all other runners, and one hour in yandex checks

Trying to figure out why, but still no luck

**Comment by vzakaznikov** [comment]
@zvonand,  let's experiment with either disabling host network (https://github.com/ClickHouse/ClickHouse/blob/master/tests/testflows/runner#L73) or creating a dedicated custom network between containers.

**Pull request merged**
