### PR TITLE
Fix file cache temporary file segment range in FileSegment::reserve

### PR DESCRIPTION
**Pull request by vdimir**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by vdimir** [comment]
Sorry, pushed wrong commit trying to rebase

**Comment by robot-ch-test-poll1** [comment]
*This is an automated comment for commit df8df5bd8ecbf449f117a3a72bbc98b8e6fbd453 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/55164/df8df5bd8ecbf449f117a3a72bbc98b8e6fbd453/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>✅ success</td></tr>
<tbody>
</table>
</details>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>⏳ pending</td></tr>
<tbody>
</table>

**Review by kssenii — APPROVED** [review]

**Comment by vdimir** [comment]
> Stress test (asan) — Killed by signal (in clickhouse-server.log) [Details](https://s3.amazonaws.com/clickhouse-test-reports/55164/c64e5e282c3e8d9fc91acb87d63955677046875b/stress_test__asan_.html)

> Stress test (msan) — Killed by signal (in clickhouse-server.log) [Details](https://s3.amazonaws.com/clickhouse-test-reports/55164/c64e5e282c3e8d9fc91acb87d63955677046875b/stress_test__msan_.html)

Looks like fix from https://github.com/ClickHouse/ClickHouse/pull/54514 is missing

https://github.com/ClickHouse/ClickHouse/blob/c64e5e282c3e8d9fc91acb87d63955677046875b/src/Processors/Transforms/MergeSortingPartialResultTransform.cpp

But stress test for partial result is enabled only in that PR too 🤔

**Comment by Algunenano** [comment]
It seems this should fix the flakiness of `FileCacheTest` ([example](https://s3.amazonaws.com/clickhouse-test-reports/55590/b9f8f2fc15e9fc21670182b5b7cb36cac6c6ba20/unit_tests__asan_.html)) but it's currently blocked by a temporal broken style in master. @vdimir Do you mind rebasing it please?

**Comment by kssenii** [comment]
No related failures:

> Integration tests (asan) [1/6] — fail: 2

test_zookeeper_config

> Integration tests (release) [2/4] — fail: 2

test_merge_tree_s3/test.py::test_s3_engine_heavy_write_check_mem

> Stateless tests (debug, s3 storage) [2/6] — fail: 1
Stateless tests (msan) [2/6] — fail: 1

02447_drop_database_replica

> Stress test (tsan)

https://github.com/ClickHouse/ClickHouse/issues/55041

**Pull request merged**
