### PR TITLE
Fix flakiness of test_keeper_s3_snapshot flakiness

### LINKED ISSUE #52059: test_keeper_s3_snapshot/test.py::test_s3_upload is flaky
Seems that this test is somewhat flaky when running under the analyzers:

<div id="data_div" style="box-sizing: border-box; margin: 1rem 0px 0px; border-radius: 0px; tab-size: 4;">

check_name | test_name | t | runs | failure_percentage
-- | -- | -- | -- | --
Integration tests (asan) [4/6] | test_keeper_s3_snapshot/test.py::test_s3_upload | 2023-07-09 00:00:00 | 25 | 4
Integration tests (tsan) [4/6] | test_keeper_s3_snapshot/test.py::test_s3_upload | 2023-07-04 00:00:00 | 10 | 10
Integration tests (tsan) [4/6] | test_keeper_s3_snapshot/test.py::test_s3_upload | 2023-07-09 00:00:00 | 25 | 4

Sample run: https://s3.amazonaws.com/clickhouse-test-reports/51160/dbdfc07790cec20af55e15515430028df3edc68c/integration_tests__release__[2_4].html

Looking at the logs it seems that flushing of the snapshots isn't sync (but keep in mind I haven't looked at the code) so it's possible that the test might be expecting something that might not have happened yet:

```
2023.07.10 10:32:03.272147 [ 198 ] {} <Information> KeeperSnapshotManagerS3: Successfully uploaded snapshot_100.bin.zstd to S3
2023.07.10 10:32:03.272152 [ 198 ] {} <Trace> WriteBufferFromS3: Close WriteBufferFromS3. Details: bucket snapshots, key snapshot_100.bin.zstd, total size 1046, count 0, hidden_size 0, offset 0, with pool: false, prefinalized true, finalized true.
2023.07.10 10:32:03.273556 [ 198 ] {} <Trace> WriteBufferFromS3: Close WriteBufferFromS3. Details: bucket snapshots, key .snapshot_100.bin.zstd_LOCK, total size 36, count 0, hidden_size 0, offset 0, with pool: false, prefinalized true, finalized true.
2023.07.10 10:32:03.402155 [ 234 ] {} <Information> RaftInstance: creating a snapshot for index 150
2023.07.10 10:32:03.402158 [ 234 ] {} <Information> RaftInstance: create snapshot idx 150 log_term 1
2023.07.10 10:32:03.402197 [ 234 ] {} <Debug> KeeperStateMachine: Creating snapshot 150
2023.07.10 10:32:03.402217 [ 234 ] {} <Debug> KeeperStateMachine: In memory snapshot 150 created, queueing task to flush to disk
2023.07.10 10:32:03.402254 [ 234 ] {} <Information> RaftInstance: create snapshot idx 150 log_term 1 done: 58 us elapsed
2023.07.10 10:32:03.404991 [ 195 ] {} <Debug> KeeperStateMachine: Created persistent snapshot 150 with path snapshot_150.bin.zstd
2023.07.10 10:32:03.404998 [ 195 ] {} <Trace> KeeperStateMachine: Clearing garbage after snapshot
2023.07.10 10:32:03.405002 [ 195 ] {} <Trace> KeeperStateMachine: Cleared garbage after snapshot
2023.07.10 10:32:03.405008 [ 195 ] {} <Information> RaftInstance: snapshot idx 150 log_term 1 created, compact the log store if needed
2023.07.10 10:32:03.405029 [ 198 ] {} <Information> KeeperSnapshotManagerS3: Will try to upload snapshot on snapshot_150.bin.zstd to S3
2023.07.10 10:32:03.538947 [ 234 ] {} <Information> RaftInstance: creating a snapshot for index 200
2023.07.10 10:32:03.538960 [ 234 ] {} <Information> RaftInstance: create snapshot idx 200 log_term 1
2023.07.10 10:32:03.538965 [ 234 ] {} <Debug> KeeperStateMachine: Creating snapshot 200
2023.07.10 10:32:03.538990 [ 234 ] {} <Debug> KeeperStateMachine: In memory snapshot 200 created, queueing task to flush to disk
2023.07.10 10:32:03.538999 [ 234 ] {} <Information> RaftInstance: create snapshot idx 200 log_term 1 done: 34 us elapsed
2023.07.10 10:32:03.541840 [ 195 ] {} <Debug> KeeperStateMachine: Created persistent snapshot 200 with path snapshot_200.bin.zstd
2023.07.10 10:32:03.541848 [ 195 ] {} <Trace> KeeperStateMachine: Clearing garbage after snapshot
2023.07.10 10:32:03.541851 [ 195 ] {} <Trace> KeeperStateMachine: Cleared garbage after snapshot
2023.07.10 10:32:03.541858 [ 195 ] {} <Information> RaftInstance: snapshot idx 200 log_term 1 created, compact the log store if needed
```

### PR DESCRIPTION
**Pull request by azat**
This is part of **"Why my PR is not merged?"** patch set series.

CI: https://s3.amazonaws.com/clickhouse-test-reports/51037/f48b07860b5b092a3cc23e5fb76a9665c7f89bae/integration_tests__tsan__[4_6].html

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Fixes: https://github.com/ClickHouse/ClickHouse/issues/52059

### CODE REVIEW

**Comment by robot-clickhouse** [comment]
This is an automated comment for commit 165670c02dcbf2406e2bae6ac80c49ba367b8ae1 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/52083/165670c02dcbf2406e2bae6ac80c49ba367b8ae1/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Comment by Algunenano** [comment]
This closes https://github.com/ClickHouse/ClickHouse/issues/52059

**Comment by azat** [comment]
@Algunenano thanks! Added `Fixes` tag

**Comment by Algunenano** [comment]
Thanks to you for actually fixing it :smile:

**Comment by azat** [comment]
>Integration tests flaky check (asan) — No flaky tests: error: 0, passed: 1, fail: 0, skipped: 0, flaky: 0, broken: 0, not_fail: 0

Looks OK

**Comment by azat** [comment]
>Stateless tests (release, DatabaseReplicated) [3/4] — fail: 1, passed: 1288, skipped: 34

- `02160_special_functions` - https://github.com/ClickHouse/ClickHouse/issues/42653

**Review by alexey-milovidov — APPROVED** [review]

**Pull request merged**
