### PR TITLE
Simplier serialization of last index column

### PR DESCRIPTION
**Pull request by alesapin**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by alesapin** [comment]
Related to https://github.com/ClickHouse/ClickHouse/issues/16548

**Comment by alesapin** [comment]
Unfortunately, we have quite a lot of usages of `serializeBinary/deserializeBinary` with `Field` argument:
https://github.com/ClickHouse/ClickHouse/blob/master/src/Storages/MergeTree/IMergeTreeDataPart.cpp#L52-L53
https://github.com/ClickHouse/ClickHouse/blob/master/src/Storages/MergeTree/MergeTreeIndexSet.cpp#L62
https://github.com/ClickHouse/ClickHouse/blob/master/src/Storages/MergeTree/MergeTreePartition.cpp#L137

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
@alesapin Not a lot... we can create temporary column and serialize/deserialize from it.
Looks like a simple change, maybe for next PR?

**Comment by alesapin** [comment]
Failed tests are well known

**Pull request merged**
