### PR TITLE
More robust website deployment

### PR DESCRIPTION
**Pull request by alexey-milovidov**
Changelog category (leave one):
- Documentation (changelog entry is not required)

Detailed description / Documentation draft:

Sometimes the list of changed files is calculated incorrectly. It's more easy to drop the cache for all files.

### CODE REVIEW

**Comment by blinkov** [comment]
It'll lead to unnecessary latency increases during work time at Moscow.

**Comment by alexey-milovidov** [comment]
@blinkov What kind of increase?

**Comment by blinkov** [comment]
It obviously depends on website visitor location on the globe and network connection quality along the way.

**Comment by alexey-milovidov** [comment]
@blinkov This task is still relevant.
We should either merge this pull request or you must propose an alternative solution.

**Comment by alexey-milovidov** [comment]
Continued in https://github.com/ClickHouse/ClickHouse/pull/13107.

**Pull request closed without merging**
