### PR TITLE
Force reanalysis if parallel replicas changed

### PR DESCRIPTION
**Pull request by Algunenano**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
- Force reanalysis of the query if parallel replicas isn't supported in a subquery.

### Documentation entry for user-facing changes

This is an ugly hack, but I couldn't find anything better. The alternative is making pretty much every visitor take a mutable context instead of a const one. As this is only for the current interpreters I think it's ok and we are better not doing a major refactor.

### CODE REVIEW

**Comment by robot-ch-test-poll3** [comment]
*This is an automated comment for commit d507884a1d905bc729682add414d5b4048bfa686 with description of existing statuses. It's updated for the latest CI running*

[❌ Click here](https://s3.amazonaws.com/clickhouse-test-reports/60362/d507884a1d905bc729682add414d5b4048bfa686/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td><a href="https://github.com/ClickHouse/ClickHouse/blob/master/.github/PULL_REQUEST_TEMPLATE.md?plain=1">❌ failure</a></td></tr>
<tbody>
</table>

**Comment by devcrafter** [comment]
Yet another repro - https://pastila.nl/?03d40981/156acba3acd994d82988d97f93d4105a#YAVCRzBrb4pc0OLfHcZvMw==

**Review by alexey-milovidov — APPROVED** [review]

**Comment by Algunenano** [comment]
This PR is doomed. It has hit pretty much all CI problems in these last 2 weeks :upside_down_face:. Rebasing once more

**Comment by Algunenano** [comment]
The fuzzer has detected an issue with parallel replicas. Probably not related to the changes but it needs to be investigated before merging

**Pull request merged**
