### PR TITLE
Precalculate values inside `HashTableGrower`

### PR DESCRIPTION
**Pull request by nickitat**
### Changelog category (leave one):
- Performance Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Optimized insertion and lookups in the HashTable.

### CODE REVIEW

**Comment by nickitat** [comment]
slowdowns do not reproduce on my machine. I suppose they are just random.
sumMap on arm seems to be [unstable](https://s3.amazonaws.com/clickhouse-test-reports/38096/c51b51c5398d4f7d93be09aa7acd72e4a57b3ee0/performance_comparison_aarch64_[1/4]/report.html).

**Comment by nickitat** [comment]
perf tests: [1](https://s3.amazonaws.com/clickhouse-test-reports/38413/abcefeeb417e0ad43ae144e7433cdc547f9a27e5/performance_comparison_[1/4]/report.html) [3](https://s3.amazonaws.com/clickhouse-test-reports/38413/abcefeeb417e0ad43ae144e7433cdc547f9a27e5/performance_comparison_[3/4]/report.html) [4](https://s3.amazonaws.com/clickhouse-test-reports/38413/abcefeeb417e0ad43ae144e7433cdc547f9a27e5/performance_comparison_[4/4]/report.html)

perf tests with alignment: [1](https://s3.amazonaws.com/clickhouse-test-reports/38413/95d413d7ec5f9081a4f5fa832944efb5a3c05941/performance_comparison_[1/4]/report.html) [3](https://s3.amazonaws.com/clickhouse-test-reports/38413/95d413d7ec5f9081a4f5fa832944efb5a3c05941/performance_comparison_[3/4]/report.html) [4](https://s3.amazonaws.com/clickhouse-test-reports/38413/95d413d7ec5f9081a4f5fa832944efb5a3c05941/performance_comparison_[4/4]/report.html)

there are few slowdowns caused apparently by increasing grower size:

0.271 | 0.338 | +1.246x | 0.246 | 0.246 | functions_with_hash_tables | 4 | select groupUniqArray(rand() % 100) from numbers(1000 * 1000) group by number / 1000 format Null
-- | -- | -- | -- | -- | -- | -- | --

1.194 | 1.383 | +1.157x | 0.157 | 0.157 | uniq | 11 | SELECT ClientIP AS k, uniqExact(UserID) FROM hits_100m_single GROUP BY k FORMAT Null
-- | -- | -- | -- | -- | -- | -- | --

both use HT with stack memory with `initial_size_degree = 4`.

**Comment by alexey-milovidov** [comment]
Let's check what's wrong with WITH FILL test.
It is definitely unrelated... but we can postpone merging this PR one or two days just to eliminate another flaky test more quickly.

**Review by alexey-milovidov — APPROVED** [review]
LGTM

**Pull request merged**
