### PR TITLE
tests: fix 01281_group_by_limit_memory_tracking flakiness

### PR DESCRIPTION
**Pull request by azat**
CI: https://s3.amazonaws.com/clickhouse-test-reports/41092/14d8f297d73f9f813c447474310fbfa0c5b18a0f/stateless_tests__debug__[2/3].html
Supersedes: #41113 (@nickitat )

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Review by nickitat — APPROVED** [review]
I'm not sure that making the query single-threaded is a better solution, but I also have nothing against it

**Comment by azat** [comment]
>[Stateless tests (debug, s3 storage) [3/3] — Tests are not finished, fail: 1, passed: 1362, skipped: 24]https://s3.amazonaws.com/clickhouse-test-reports/41178/88d55330428eeff52dd6ec21de4f867cd45c2ba7/stateless_tests__debug__s3_storage__[3/3].html)

- #38158

>[Stateless tests (debug, s3 storage) [1/3] — fail: 1, passed: 1465, skipped: 32](https://s3.amazonaws.com/clickhouse-test-reports/41178/88d55330428eeff52dd6ec21de4f867cd45c2ba7/stateless_tests__debug__s3_storage__[1/3].html)

- `00632_get_sample_block_cache` timeout

**Comment by azat** [comment]
>I'm not sure that making the query single-threaded is a better solution, but I also have nothing against it

For this particular test I think it is fine, since it is about memory consumption, more details can be found here #11022 
Actually while rewriting the test in #11119 it looses it's ability to reproduce the problem, will fix it.

**Comment by azat** [comment]
Test failures looks unrelated:

>[Integration tests (release) [2/2] — fail: 1, passed: 1133, flaky: 0](https://s3.amazonaws.com/clickhouse-test-reports/41178/9d485acb6b26df17fa9a51b8a147417f773bd033/integration_tests__release__[2/2].html)

- `test_cluster_copier/test.py::test_copy_with_recovering[False]` - #30399

>[Stateful tests (debug) — fail: 1, passed: 127, skipped: 2](https://s3.amazonaws.com/clickhouse-test-reports/41178/9d485acb6b26df17fa9a51b8a147417f773bd033/stateful_tests__debug_.html)

- `00168_parallel_processing_on_replicas_part_1` - timeout, x2, 1200 sec instead of 600

>[Stateless tests (debug, s3 storage) [2/3] — fail: 3, passed: 1437, skipped: 37](https://s3.amazonaws.com/clickhouse-test-reports/41178/9d485acb6b26df17fa9a51b8a147417f773bd033/stateless_tests__debug__s3_storage__[2/3].html)

- `01516_drop_table_stress_long` - timeout
- `01195_formats_diagnostic_info` - timeout
- `01085_max_distributed_connections` - timeout

**Pull request merged**
