### PR TITLE
unwind endless loop

### PR DESCRIPTION
**Pull request by azat**
Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
TBD

Detailed description / Documentation draft:
TBD

*NOTE: trace_log does not bloat in size, only 6-7x more (~30MB -> ~190MB)*

### CODE REVIEW

**Comment by alesapin** [comment]
Very strange idea to turn any `period` into 1 nanosecond.

**Comment by tavplubix** [comment]
> Very strange idea to turn any `period` into 1 nanosecond.

Why? We have protection from too low period
https://github.com/ClickHouse/ClickHouse/blob/f41cf281e4a29e9d703bde1e29c74a7433f1a208/src/Common/QueryProfiler.cpp#L107-L108
and
https://github.com/ClickHouse/ClickHouse/blob/f41cf281e4a29e9d703bde1e29c74a7433f1a208/src/Common/QueryProfiler.cpp#L39-L54

I suppose that the purpose of this PR is to investigate why the protection does not work sometimes causing livelocks.

(may be related to #29618)

**Comment by azat** [comment]
@mergify update

**Comment by azat** [comment]
It does not show any hungs after few iterations, closing (will try to reproduce it in another way)

**Pull request closed without merging**
