### PR TITLE
Turn on polymorphic parts for log tables

### PR DESCRIPTION
**Pull request by CurtizJ**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
System log tables now use polymorpic parts by default.

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
Ok, but what's wrong with stateful test?
There should be non-zero values in system.columns because test.hits table exists.

**Comment by alexey-milovidov** [comment]
Maybe you can also utilize our new feature - write `'10M'` for the setting value?

**Comment by alexey-milovidov** [comment]
Also you can remove custom index granularity because now we have adaptive granularity. It should work even better.

**Comment by CurtizJ** [comment]
> Ok, but what's wrong with stateful test?
> There should be non-zero values in system.columns because test.hits table exists.

See #9916

**Comment by alexey-milovidov** [comment]
Ok... but how it is related to changing the threshold of wide parts of system tables?

**Comment by CurtizJ** [comment]
Previously system tables were written in wide format and their column sizes were counted. Also only TSan check was affected, because it skips the only two tests, in which tables with adaptive granularity are created.

**Pull request merged**
