### PR TITLE
Use iterators instead of std::ranges

### PR DESCRIPTION
**Pull request by ltrk2**
Follow-up to #53760 as requested by @rschu1ze.

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Review by alexey-milovidov — DISMISSED** [review]
Use a `for` loop instead of `std::for_each`.

**Comment by robot-ch-test-poll1** [comment]
This is an automated comment for commit 547a2ccf86e18e6ec7a95ad4dfb284a55a980fd1 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/53893/547a2ccf86e18e6ec7a95ad4dfb284a55a980fd1/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Review by rschu1ze — APPROVED** [review]

**Review by rschu1ze — APPROVED** [review]

**Comment by rschu1ze** [comment]
Lgtm, thanks. I don't know the magic spell in GitHub to undo requested changes by other reviewers. Aleksey would need to approve/merge.

**Comment by yakov-olkhovskiy** [comment]
@rschu1ze maybe this one? :)
image

**Pull request merged**
