### PR TITLE
Fix ALL/DISTINCT as identifier in function arguments

### LINKED ISSUE #34826: can not alias name to 'all'
version 21.3.15.4.altinity+stable

sql
```
select 1 as all, if(all=0,1,0)
```

error log
```
ClickHouse exception, code: 62, host: 120.77.40.176, port: 8223; Code: 62, e.displayText() = DB::Exception: Syntax error: failed at position 23 ('=') (line 1, col 23): =0,1,0)
FORMAT TabSeparatedWithNamesAndTypes. Expected one of: EXTRACT, TIMESTAMPADD, TIMESTAMPDIFF, TIMESTAMP_DIFF, TRIM expression, lambda expression, expression with optional alias, number, logical-NOT expression, substitution, nullity checking, DATE_ADD, end of query, RIGHT, tuple, TIMESTAMP, literal, qualified asterisk, SELECT subquery, DATE_ADD expression, asterisk, EXTRACT expression, DATE, NULL, compound identifier, OpeningRoundBracket, string concatenation expression, logical-OR expression, identifier, MySQL-style global variable, element of expression with optional alias, array element expression, TIMESTAMP operator expression, element of expression, expression with prefix unary operator, DATE operator expression, list, delimited by operator of variable arity, DATE_DIFF, parenthesized expression, COLUMNS matcher, RIGHT expression, array, TRIM, DATE_DIFF expression, case, list of expressions, string literal, unary minus expression, INTERVAL operator expression, map, DATESUB, TIMESTAMPSUB, INTERVAL, expression with ternary operator, CASE, LEFT expression, LEFT, CAST, additive expression, logical-AND expression, SUBSTRING, list of elements, RTRIM, DATEDIFF, SUBSTRING expression, BETWEEN expression, NOT, function, DATEADD, DATE_SUB, tuple element expression, comparison expression, Arrow, collection of literals, TIMESTAMP_ADD, CAST expression, list, delimited by binary operators, DISTINCT, token, COLUMNS, TIMESTAMP_SUB, LTRIM, multiplicative expression (version 21.3.15.4.altinity+stable (altinity build))
```

I think the field ‘all’ is the system reserved keyword, so it failed.
It works with version 20.x

### PR DESCRIPTION
**Pull request by ucasfl**
Changelog category (leave one):

- Bug Fix (user-visible misbehaviour in official stable or prestable release)

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Fix `ALL/DISTINCT` as identifier in function arguments. Closes #34826.

### CODE REVIEW

**Comment by ucasfl** [comment]
https://github.com/ClickHouse/ClickHouse/blob/db69ab9d17d1bbb772cc8b2c18db33df6f7502ee/tests/queries/0_stateless/01390_remove_injective_in_uniq.sql#L21

This query is ambiguous, should we treat `distinct` as identifier or not?

A more suitable case:

```sql
with 1 as all select sum(all - plus(1, number)) from numbers(10)

WITH 1 AS `all`
SELECT sum(-(1 + number))
FROM numbers(10)

Query id: d1d6d0dc-3679-4e19-8518-55e4f0680799

┌─sum(negate(plus(1, number)))─┐
│                          -55 │
└──────────────────────────────┘

1 rows in set. Elapsed: 0.004 sec. 
```
@alexey-milovidov

**Comment by vdimir** [comment]
> This query is ambiguous, should we treat `distinct` as identifier or not?

I suppose no, until it's not `distinct` in quotes. If user will want to have identifier here -- just add quotes, otherwise distinct semantic is available. So main idea is to have option to use desired semantic.

**Comment by ucasfl** [comment]
> > This query is ambiguous, should we treat `distinct` as identifier or not?
> 
> I suppose no, until it's not `distinct` in quotes. If user will want to have identifier here -- just add quotes, otherwise distinct semantic is available. So main idea is to have option to use desired semantic.

So, do I need to fix the problem in #34826?

**Comment by vdimir** [comment]
I've checked with psql and it treats all as keyword by default and as identifier in quotes:

```
postgres=# select all-1 from (select 1 as all) as t;
 ?column? 
----------
       -1
(1 row)

postgres=# select "all"-1 from (select 1 as all) as t;
 ?column? 
----------
        0
(1 row)
```

In latest version we have same semantic, so let's support it like this, no need to fix

**Pull request closed without merging**
