### PR TITLE
Fix 01179_insert_values_semicolon test

### PR DESCRIPTION
**Pull request by azat**
Back in #19925 a check for reading data after semicolon had been added,
but after #40474 it does not work, the test does not show the problem
because of timeout does not work without stdin before (a more generic
fix for timeouts in expect tests I will submit later).

To make this test works, the only type that I can found that will work
right now is DateTime64, other types does use peeking, or even if they
do, they will fail while parsing the query as SQL expression.

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Cc: @tavplubix 
Cc: @alexey-milovidov

### CODE REVIEW

**Comment by azat** [comment]
>PullRequestCI / PerformanceComparisonX86-0 (pull_request) Failing after 58m

- #46641

**Comment by azat** [comment]
>PullRequestCI / PerformanceComparisonX86-0 (pull_request) Failing after 58m

- #46641

**Review by tavplubix — APPROVED** [review]

**Comment by tavplubix** [comment]
The test became flaky: [link](https://play.clickhouse.com/play?user=play#d2l0aCAKJyUwMTE3OV9pbnNlcnRfdmFsdWVzX3NlbWljb2xvbiUnIGFzIG5hbWVfcGF0dGVybiwKJyUlJyBhcyBjb250ZXh0X3BhdHRlcm4sCicyMDIyLTA5LTAxJyBhcyBzdGFydF9kYXRlLAooNDU0NjEpIGFzIG5vaXN5X3BycywKKCdTdGF0ZWxlc3MgdGVzdHMgKGFzYW4pJywgJ1N0YXRlbGVzcyB0ZXN0cyAoYWRkcmVzcyknLCAnU3RhdGVsZXNzIHRlc3RzIChhZGRyZXNzLCBhY3Rpb25zKScpIGFzIGJhY2twb3J0X2FuZF9yZWxlYXNlX3NwZWNpZmljX2NoZWNrcwpzZWxlY3QgCnRvU3RhcnRPZkRheShjaGVja19zdGFydF90aW1lKSBhcyBkLApjb3VudCgpLCAgZ3JvdXBVbmlxQXJyYXkocHVsbF9yZXF1ZXN0X251bWJlciksIGFueShyZXBvcnRfdXJsKQpmcm9tIGNoZWNrcyB3aGVyZSBzdGFydF9kYXRlIDw9IGNoZWNrX3N0YXJ0X3RpbWUgYW5kIHB1bGxfcmVxdWVzdF9udW1iZXIgbm90IGluIAooc2VsZWN0IHB1bGxfcmVxdWVzdF9udW1iZXIgYXMgcHJuIGZyb20gY2hlY2tzIHdoZXJlIHBybiE9MCBhbmQgc3RhcnRfZGF0ZSA8PSBjaGVja19zdGFydF90aW1lIGFuZCBjaGVja19uYW1lIGluIGJhY2twb3J0X2FuZF9yZWxlYXNlX3NwZWNpZmljX2NoZWNrcykgCmFuZCB0ZXN0X25hbWUgbGlrZSBuYW1lX3BhdHRlcm4gYW5kIHRlc3RfY29udGV4dF9yYXcgaWxpa2UgY29udGV4dF9wYXR0ZXJuCmFuZCBwdWxsX3JlcXVlc3RfbnVtYmVyIG5vdCBpbiBub2lzeV9wcnMKYW5kIHRlc3Rfc3RhdHVzIGluICgnRkFJTCcsICdGTEFLWScsICdmYWlsdXJlJykgZ3JvdXAgYnkgZCBvcmRlciBieSBkIGRlc2M=)

Hope https://github.com/ClickHouse/ClickHouse/pull/46779 will fix it.

**Comment by azat** [comment]
Yep, it will, the problem is actually in the test (but before this patch the status of test was simply wrong anyway).

**Comment by tavplubix** [comment]
Hm, actually the current behavior is really unexpected:
https://pastila.nl/?021a589c/34fa791d0ae15be61058db276ff2994d#qnAaGkmFvkQu9XnmbGzyww==

That's because `PeekableReadBuffer::hasUnreadData()` doesn't check the underlying buffer and returns false when the underlying buffer still has some pending data: https://pastila.nl/?0039331f/8c57227fa7b85e669acadd23a4f5e0c0#YCkwXgq3OhueXHdNORIpSA==

Maybe we should fix that

**Comment by zvonand** [comment]
> Maybe we should fix that

Well, maybe. Anyway, its kind of a silly thing that to test A we need B to have incorrect implementation :l

**Comment by azat** [comment]
>Maybe we should fix that

Yeah, it definitely should be fixed, but with DateTime64 it seems there is another bug - https://github.com/ClickHouse/ClickHouse/pull/55146/files#r1355577282

>Maybe this test can be omitted (removed) alongside my changes if it is not reproducible?

I think it will be better to fix `ValuesBlockInputFormat::readSuffix`

**Pull request merged**
