### PR TITLE
Something InterpreterSelectQueryAnalyzer::getSampleBlock

### PR DESCRIPTION
**Pull request by Michicosun**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
run interpreter with `only_analyze` flag in getSampleBlock method

### Documentation entry for user-facing changes

- [x] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
What exactly was fixed, and how? Why it shouldn't be included in the changelog?
Why don't provide an explanation in the comments inside the code?

**Comment by Michicosun** [comment]
> What exactly was fixed, and how? Why it shouldn't be included in the changelog? Why don't provide an explanation in the comments inside the code?

noticed, that interpreter was created from original select_query_info, instead of changed copy, that was made a line above like in the similar method.

**Comment by robot-ch-test-poll2** [comment]
*This is an automated comment for commit b117d8ed12f2f3839a03fc4882f5228ff7d010b5 with description of existing statuses. It's updated for the latest CI running*

[❌ Click here](https://s3.amazonaws.com/clickhouse-test-reports/56972/b117d8ed12f2f3839a03fc4882f5228ff7d010b5/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://github.com/ClickHouse/ClickHouse/blob/master/.github/PULL_REQUEST_TEMPLATE.md?plain=1">❌ failure</a></td></tr>
<tbody>
</table>

**Review by kitaisreal — APPROVED** [review]

**Comment by kitaisreal** [comment]
It just looks like typo. We should set `only_analyze` because that way we can avoid a lot of unnecessary stuff.

**Comment by alexey-milovidov** [comment]
@Michicosun let's merge with master to start tests.

**Pull request merged**
