### PR TITLE
WIP. Fixed the issue "Method create is not implemented for data type Function"

### LINKED ISSUE #8689: Method createColumn() is not implemented for data type Function((String, String) -> String)
test case:
```
SELECT
    arrayJoin AS kv_key
FROM system.query_log
ARRAY JOIN ProfileEvents.Names AS arrayJoin
PREWHERE has(arrayMap(key -> key, ProfileEvents.Names), 'Query')
WHERE arrayJoin = 'Query'
LIMIT 1
```

problem in PREWHERE section
```
Method createColumn() is not implemented for data type Function((String, String) -> String)
```
ClickHouse server version 19.17.4 revision 54428

problem similar with https://github.com/ClickHouse/ClickHouse/issues/7799

### PR DESCRIPTION
**Pull request by alexey-milovidov**
Changelog category (leave one):
- Bug Fix

Changelog entry (up to few sentences, required except for Non-significant/Documentation categories):
Fixed the issue "Method create is not implemented for data type Function". This fixes #8689

### CODE REVIEW

**Comment by orloffv** [comment]
Can I help u?

**Comment by alexey-milovidov** [comment]
It's strange that it's passed. I remember that I faced some issues. Let's merge with master and look again.

**Comment by orloffv** [comment]
I can write a test if needed

**Comment by alexey-milovidov** [comment]
@orloffv You have already written the test and it doesn't work for this PR.

**Comment by alexey-milovidov** [comment]
I'm not able to finish this task. Assigned to @4ertus2

**Comment by 4ertus2** [comment]
The logic is: we append prewhere actions and check thir sample block (and it has no function column), then we append array join actions (and there's no check after it) and then we append where actions (ant throws on its sample block check). So the checks theirself are OK. I don't think we should implement createColumn() functions to pass them. It's better to close this PR. I'll try to discover more and make solution passing the checks.

**Comment by alexey-milovidov** [comment]
Ok.

@orloffv The reason is that I tried to solve the issue with a simple patch without complete understanding of the underlying code.

**Pull request closed without merging**
