### PR TITLE
Check Decimal division overflow based on operands scale

### LINKED ISSUE #30341: Big Decimal can overflow without exception
**Describe what's wrong**

It's possible to get meaningless result after big decimal division.

**Does it reproduce on recent release?**

Yes. ClickHouse 21.11, 21.8

**How to reproduce**

ClickHouse 21.11

```
SELECT toDecimal128(1, 20) / toDecimal128(1, 20)

Query id: 080e9ddd-9060-4095-8752-3b24dca42bb3

┌─divide(toDecimal128(1, 20), toDecimal128(1, 20))─┐
│                           0.01318113592927845595 │
└──────────────────────────────────────────────────┘

- P from [ 19 : 38 ] - for Decimal128(S)

SELECT
    toDecimal128(1, 20) / toDecimal128(1, 20) AS a,
    toDecimal128(1, 19) / toDecimal128(1, 19) AS b

┌──────────────────────a─┬─b─┐
│ 0.01318113592927845595 │ 1 │
└────────────────────────┴───┘

SELECT
    [1, 1] AS vs,
    toDecimal128(vs[2], 12) / toDecimal128(vs[1], 12) AS frac_dec128_12,
    toDecimal128(vs[2], 24) / toDecimal128(vs[1], 24) AS frac_dec128_24a,
    toFloat64(vs[2]) / toFloat64(vs[1]) AS frac_float64

Query id: 6e0fc55d-14a7-4cab-9d03-ccee9200c6b1

┌─vs────┬─frac_dec128_12─┬────────────frac_dec128_24a─┬─frac_float64─┐
│ [1,1] │              1 │ 0.000000000018960114910927 │            1 │


SELECT toDecimal64(2, 12) / toDecimal64(2, 12)

Query id: 5e5681dd-9984-43c9-a317-e9e232cd12ed


0 rows in set. Elapsed: 0.003 sec.

Received exception from server (version 21.11.1):
Code: 407. DB::Exception: Received from localhost:9000. DB::Exception: Decimal math overflow: While processing toDecimal64(2, 12) / toDecimal64(2, 12). (DECIMAL_OVERFLOW)
```

**Expected behavior**

Exception most likely.

### PR DESCRIPTION
**Pull request by zvonand**
Fixes #30341. It doesn't fix all overflow cases possible in Decimal division

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in official stable or prestable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix Decimal division overflow, which can be detected based on operands scale

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
LGTM but a test needed.

**Comment by zvonand** [comment]
ping?

**Comment by devcrafter** [comment]
@zvonand Thanks for ping. I will check it soon

**Comment by devcrafter** [comment]
I guess we need to respect `check_decimal_overflow` setting here.

**Comment by devcrafter** [comment]
Sorry, did push to the branch wrong. Let's fix it tomorrow

**Comment by zvonand** [comment]
Ping_2? :)

**Comment by devcrafter** [comment]
@alexey-milovidov Please could you have a look?

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
LGTM but please check what is with UBSan.

**Comment by devcrafter** [comment]
Looks like UBSan failure related to connectivity issue
```
022.08.15 05:32:55.581334 [ 2700 ] {d54ddb80-c34e-4f26-bcf4-89d4601b3c99} <Error> executeQuery: Code: 24. DB::Exception: Cannot write to ostream at offset 134: While executing ParallelFormattingOutputFormat. (CANNOT_WRITE_TO_OSTREAM) (version 22.8.1.1) (from [::1]:46766) (in query: SELECT 'Running test stateless/02354_tuple_lowcardinality.sql from pid=896' ), Stack trace (when copying this message, always include the lines below):

0. ./build_docker/../contrib/libcxx/include/exception:133: Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) in /usr/bin/clickhouse
1. ./build_docker/../src/Common/Exception.cpp:69: DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) in /usr/bin/clickhouse
2. ./build_docker/../src/IO/WriteBufferFromOStream.cpp:0: DB::WriteBufferFromOStream::nextImpl() in /usr/bin/clickhouse
3. ./build_docker/../src/IO/BufferBase.h:39: DB::WriteBuffer::next() in /usr/bin/clickhouse
4. ./build_docker/../src/Server/HTTP/WriteBufferFromHTTPServerResponse.cpp:133: DB::WriteBufferFromHTTPServerResponse::nextImpl() in /usr/bin/clickhouse
5. ./build_docker/../src/IO/BufferBase.h:39: DB::WriteBuffer::next() in /usr/bin/clickhouse
6. ./build_docker/../src/Processors/Formats/Impl/ParallelFormattingOutputFormat.cpp:0: DB::ParallelFormattingOutputFormat::collectorThreadFunction(std::__1::shared_ptr<DB::ThreadGroupStatus> const&) in /usr/bin/clickhouse
7. ./build_docker/../src/Processors/Formats/Impl/ParallelFormattingOutputFormat.h:0: ThreadFromGlobalPool::ThreadFromGlobalPool<DB::ParallelFormattingOutputFormat::ParallelFormattingOutputFormat(DB::ParallelFormattingOutputFormat::Params)::'lambda'()>(DB::ParallelFormattingOutputFormat::ParallelFormattingOutputFormat(DB::ParallelFormattingOutputFormat::Params)::'lambda'()&&)::'lambda'()::operator()() in /usr/bin/clickhouse
8. ./build_docker/../contrib/libcxx/include/__functional/function.h:1157: ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) in /usr/bin/clickhouse
9. ./build_docker/../src/Common/ThreadPool.cpp:0: void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()> >(void*) in /usr/bin/clickhouse
10. ? in ?
11. clone in ?
```

**Pull request merged**
