### PR TITLE
Cherry pick #66395 to 23.8: Ignore subquery for IN in DDLLoadingDependencyVisitor

### PR DESCRIPTION
**Pull request by robot-ch-test-poll4**
Original pull-request #66395

This pull-request is a first step of an automated backporting.
It contains changes similar to calling `git cherry-pick` locally.
If you intend to continue backporting the changes, then resolve all conflicts if any.
Otherwise, if you do not want to backport them, then just close this pull-request.

The check results does not matter at this step - you can safely ignore them.

### Note

This pull-request will be merged automatically. Please, **do not merge it manually** (but if you accidentally did, nothing bad will happen).

#### If the PR was manually reopened after being closed

If this PR is stuck (i.e. not automatically merged after one day), check https://github.com/ClickHouse/ClickHouse/pull/66395 for `pr-backports-created` *label* and delete it.

Manually merging will do nothing. The `pr-backports-created` *label* prevents the original PR https://github.com/ClickHouse/ClickHouse/pull/66395 from being processed.

#### If the conflicts were resolved in a wrong way

If this cherry-pick PR is completely screwed by a wrong conflicts resolution, and you want to recreate it:

- delete the `pr-cherrypick` label from the PR
- delete this branch from the repository

You also need to check the original PR https://github.com/ClickHouse/ClickHouse/pull/66395 for `pr-backports-created`, and delete if it's presented there

### CODE REVIEW

**Comment by robot-clickhouse** [comment]
Dear @KochetovNicolai, @evillique, the PR is not updated for 1d24h0m41s. Please, either resolve the conflicts, or close it to finish the backport process of #66395

**Comment by robot-ch-test-poll1** [comment]
Dear @KochetovNicolai, @evillique, the PR is not updated for 1d24h59m56s. Please, either resolve the conflicts, or close it to finish the backport process of #66395

**Comment by robot-ch-test-poll3** [comment]
Dear @KochetovNicolai, @evillique, the PR is not updated for 1d24h0m9s. Please, either resolve the conflicts, or close it to finish the backport process of #66395

**Comment by robot-ch-test-poll3** [comment]
Dear @KochetovNicolai, @evillique, the PR is not updated for 1d24h59m48s. Please, either resolve the conflicts, or close it to finish the backport process of #66395

**Comment by robot-clickhouse-ci-1** [comment]
Dear @KochetovNicolai, @evillique, the PR is not updated for 1d25h1m57s. Please, either resolve the conflicts, or close it to finish the backport process of #66395

**Comment by robot-ch-test-poll** [comment]
Dear @KochetovNicolai, @evillique, the PR is not updated for 1d24h4m14s. Please, either resolve the conflicts, or close it to finish the backport process of #66395

**Comment by robot-ch-test-poll1** [comment]
Dear @KochetovNicolai, @evillique, the PR is not updated for 1d24h57m51s. Please, either resolve the conflicts, or close it to finish the backport process of #66395

**Comment by robot-ch-test-poll** [comment]
Dear @KochetovNicolai, @evillique, the PR is not updated for 1d25h11m16s. Please, either resolve the conflicts, or close it to finish the backport process of #66395

**Comment by robot-ch-test-poll4** [comment]
Dear @KochetovNicolai, @evillique, the PR is not updated for 1d24h54m6s. Please, either resolve the conflicts, or close it to finish the backport process of #66395

**Comment by robot-ch-test-poll4** [comment]
Dear @KochetovNicolai, @evillique, the PR is not updated for 1d24h51m43s. Please, either resolve the conflicts, or close it to finish the backport process of #66395

**Comment by robot-clickhouse** [comment]
Dear @KochetovNicolai, @evillique, the PR is not updated for 1d24h58m35s. Please, either resolve the conflicts, or close it to finish the backport process of #66395

**Comment by robot-clickhouse** [comment]
Dear @KochetovNicolai, @evillique, the PR is not updated for 1d25h0m12s. Please, either resolve the conflicts, or close it to finish the backport process of #66395

**Comment by robot-clickhouse** [comment]
Dear @KochetovNicolai, @evillique, the PR is not updated for 1d24h58m12s. Please, either resolve the conflicts, or close it to finish the backport process of #66395

**Comment by robot-ch-test-poll1** [comment]
Dear @KochetovNicolai, @evillique, the PR is not updated for 1d24h1m41s. Please, either resolve the conflicts, or close it to finish the backport process of #66395

**Comment by robot-clickhouse-ci-1** [comment]
Dear @KochetovNicolai, @evillique, the PR is not updated for 1d24h58m33s. Please, either resolve the conflicts, or close it to finish the backport process of #66395

**Comment by robot-clickhouse-ci-1** [comment]
Dear @KochetovNicolai, @evillique, the PR is not updated for 1d24h2m1s. Please, either resolve the conflicts, or close it to finish the backport process of #66395

**Comment by robot-ch-test-poll3** [comment]
Dear @KochetovNicolai, @evillique, the PR is not updated for 1d25h1m55s. Please, either resolve the conflicts, or close it to finish the backport process of #66395

**Comment by robot-ch-test-poll3** [comment]
Dear @KochetovNicolai, @evillique, the PR is not updated for 1d24h58m54s. Please, either resolve the conflicts, or close it to finish the backport process of #66395

**Comment by robot-ch-test-poll1** [comment]
Dear @KochetovNicolai, @evillique, the PR is not updated for 1d25h2m13s. Please, either resolve the conflicts, or close it to finish the backport process of #66395

**Comment by robot-ch-test-poll4** [comment]
Dear @KochetovNicolai, @evillique, the PR is not updated for 1d25h3m41s. Please, either resolve the conflicts, or close it to finish the backport process of #66395

**Comment by robot-clickhouse-ci-2** [comment]
Dear @KochetovNicolai, @evillique, the PR is not updated for 1d25h17m52s. Please, either resolve the conflicts, or close it to finish the backport process of #66395

**Comment by robot-ch-test-poll** [comment]
Dear @KochetovNicolai, @evillique, the PR is not updated for 1d24h1m56s. Please, either resolve the conflicts, or close it to finish the backport process of #66395

**Comment by robot-ch-test-poll4** [comment]
Dear @KochetovNicolai, @evillique, the PR is not updated for 1d24h46m45s. Please, either resolve the conflicts, or close it to finish the backport process of #66395

**Comment by robot-ch-test-poll1** [comment]
Dear @KochetovNicolai, @evillique, the PR is not updated for 1d24h3m58s. Please, either resolve the conflicts, or close it to finish the backport process of #66395

**Comment by robot-ch-test-poll2** [comment]
Dear @KochetovNicolai, @evillique, the PR is not updated for 1d24h1m38s. Please, either resolve the conflicts, or close it to finish the backport process of #66395

**Comment by robot-clickhouse-ci-1** [comment]
Dear @KochetovNicolai, @evillique, the PR is not updated for 1d24h40m42s. Please, either resolve the conflicts, or close it to finish the backport process of #66395

**Comment by robot-ch-test-poll1** [comment]
Dear @KochetovNicolai, @evillique, the PR is not updated for 1d24h0m0s. Please, either resolve the conflicts, or close it to finish the backport process of #66395

**Comment by robot-clickhouse-ci-2** [comment]
Dear @KochetovNicolai, @evillique, the PR is not updated for 1d24h0m45s. Please, either resolve the conflicts, or close it to finish the backport process of #66395

**Comment by robot-clickhouse-ci-1** [comment]
Dear @KochetovNicolai, @evillique, the PR is not updated for 1d24h59m48s. Please, either resolve the conflicts, or close it to finish the backport process of #66395

**Comment by robot-ch-test-poll4** [comment]
Dear @KochetovNicolai, @evillique, the PR is not updated for 1d24h0m27s. Please, either resolve the conflicts, or close it to finish the backport process of #66395

**Comment by robot-clickhouse-ci-2** [comment]
Dear @KochetovNicolai, @evillique, the PR is not updated for 1d24h59m49s. Please, either resolve the conflicts, or close it to finish the backport process of #66395

**Comment by robot-ch-test-poll4** [comment]
Dear @KochetovNicolai, @evillique, the PR is not updated for 1d24h0m27s. Please, either resolve the conflicts, or close it to finish the backport process of #66395

**Comment by robot-ch-test-poll** [comment]
Dear @KochetovNicolai, @evillique, the PR is not updated for 1d24h58m39s. Please, either resolve the conflicts, or close it to finish the backport process of #66395

**Comment by robot-clickhouse** [comment]
Dear @KochetovNicolai, @evillique, the PR is not updated for 1d24h0m16s. Please, either resolve the conflicts, or close it to finish the backport process of #66395

**Comment by robot-clickhouse** [comment]
Dear @KochetovNicolai, @evillique, the PR is not updated for 1d24h1m35s. Please, either resolve the conflicts, or close it to finish the backport process of #66395

**Comment by robot-ch-test-poll1** [comment]
Dear @KochetovNicolai, @evillique, the PR is not updated for 1d24h59m22s. Please, either resolve the conflicts, or close it to finish the backport process of #66395

**Comment by robot-clickhouse** [comment]
Dear @KochetovNicolai, @evillique, the PR is not updated for 1d24h12m49s. Please, either resolve the conflicts, or close it to finish the backport process of #66395

**Comment by robot-ch-test-poll3** [comment]
Dear @KochetovNicolai, @evillique, the PR is not updated for 1d24h48m4s. Please, either resolve the conflicts, or close it to finish the backport process of #66395

**Comment by robot-ch-test-poll4** [comment]
Dear @KochetovNicolai, @evillique, the PR is not updated for 1d24h21m33s. Please, either resolve the conflicts, or close it to finish the backport process of #66395

**Comment by robot-clickhouse-ci-1** [comment]
Dear @KochetovNicolai, @evillique, the PR is not updated for 1d24h37m3s. Please, either resolve the conflicts, or close it to finish the backport process of #66395

**Pull request closed without merging**
