### PR TITLE
Do not count AttachedTable for tables in information schema databases

### PR DESCRIPTION
**Pull request by serxa**
### Changelog category (leave one):
- CI Fix or Improvement (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
...

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-ch-test-poll2** [comment]
*This is an automated comment for commit 1225d50508ad0885dca3367b08c15f54c65b02f6 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/67187/1225d50508ad0885dca3367b08c15f54c65b02f6/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Style check</td><td>Runs a set of checks to keep the code style clean. If some of tests failed, see the related log from the report</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/67187/1225d50508ad0885dca3367b08c15f54c65b02f6/style_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Comment by serxa** [comment]
Problem was found by logging added in https://github.com/ClickHouse/ClickHouse/pull/67007
```
2024.07.25 17:13:27.499537 [ 1 ] {} <Test> DatabaseMemory(information_schema): Counting attached table schemata to database information_schema
2024.07.25 17:13:27.499779 [ 1 ] {} <Test> DatabaseMemory(information_schema): Counting attached table SCHEMATA to database information_schema
2024.07.25 17:13:27.500664 [ 1 ] {} <Test> DatabaseMemory(information_schema): Counting attached table tables to database information_schema
2024.07.25 17:13:27.500919 [ 1 ] {} <Test> DatabaseMemory(information_schema): Counting attached table TABLES to database information_schema
2024.07.25 17:13:27.501818 [ 1 ] {} <Test> DatabaseMemory(information_schema): Counting attached table views to database information_schema
2024.07.25 17:13:27.502112 [ 1 ] {} <Test> DatabaseMemory(information_schema): Counting attached table VIEWS to database information_schema
2024.07.25 17:13:27.504382 [ 1 ] {} <Test> DatabaseMemory(information_schema): Counting attached table columns to database information_schema
2024.07.25 17:13:27.505126 [ 1 ] {} <Test> DatabaseMemory(information_schema): Counting attached table COLUMNS to database information_schema
2024.07.25 17:13:27.506310 [ 1 ] {} <Test> DatabaseMemory(information_schema): Counting attached table key_column_usage to database information_schema
2024.07.25 17:13:27.506675 [ 1 ] {} <Test> DatabaseMemory(information_schema): Counting attached table KEY_COLUMN_USAGE to database information_schema
2024.07.25 17:13:27.507479 [ 1 ] {} <Test> DatabaseMemory(information_schema): Counting attached table referential_constraints to database information_schema
2024.07.25 17:13:27.507737 [ 1 ] {} <Test> DatabaseMemory(information_schema): Counting attached table REFERENTIAL_CONSTRAINTS to database information_schema
2024.07.25 17:13:27.508957 [ 1 ] {} <Test> DatabaseMemory(information_schema): Counting attached table statistics to database information_schema
2024.07.25 17:13:27.509374 [ 1 ] {} <Test> DatabaseMemory(information_schema): Counting attached table STATISTICS to database information_schema
2024.07.25 17:13:27.510142 [ 1 ] {} <Test> DatabaseMemory(INFORMATION_SCHEMA): Counting attached table schemata to database INFORMATION_SCHEMA
2024.07.25 17:13:27.510384 [ 1 ] {} <Test> DatabaseMemory(INFORMATION_SCHEMA): Counting attached table SCHEMATA to database INFORMATION_SCHEMA
2024.07.25 17:13:27.511241 [ 1 ] {} <Test> DatabaseMemory(INFORMATION_SCHEMA): Counting attached table tables to database INFORMATION_SCHEMA
2024.07.25 17:13:27.511541 [ 1 ] {} <Test> DatabaseMemory(INFORMATION_SCHEMA): Counting attached table TABLES to database INFORMATION_SCHEMA
2024.07.25 17:13:27.512491 [ 1 ] {} <Test> DatabaseMemory(INFORMATION_SCHEMA): Counting attached table views to database INFORMATION_SCHEMA
2024.07.25 17:13:27.512859 [ 1 ] {} <Test> DatabaseMemory(INFORMATION_SCHEMA): Counting attached table VIEWS to database INFORMATION_SCHEMA
2024.07.25 17:13:27.515167 [ 1 ] {} <Test> DatabaseMemory(INFORMATION_SCHEMA): Counting attached table columns to database INFORMATION_SCHEMA
2024.07.25 17:13:27.515998 [ 1 ] {} <Test> DatabaseMemory(INFORMATION_SCHEMA): Counting attached table COLUMNS to database INFORMATION_SCHEMA
2024.07.25 17:13:27.517225 [ 1 ] {} <Test> DatabaseMemory(INFORMATION_SCHEMA): Counting attached table key_column_usage to database INFORMATION_SCHEMA
2024.07.25 17:13:27.517607 [ 1 ] {} <Test> DatabaseMemory(INFORMATION_SCHEMA): Counting attached table KEY_COLUMN_USAGE to database INFORMATION_SCHEMA
2024.07.25 17:13:27.518414 [ 1 ] {} <Test> DatabaseMemory(INFORMATION_SCHEMA): Counting attached table referential_constraints to database INFORMATION_SCHEMA
2024.07.25 17:13:27.518719 [ 1 ] {} <Test> DatabaseMemory(INFORMATION_SCHEMA): Counting attached table REFERENTIAL_CONSTRAINTS to database INFORMATION_SCHEMA
2024.07.25 17:13:27.519959 [ 1 ] {} <Test> DatabaseMemory(INFORMATION_SCHEMA): Counting attached table statistics to database INFORMATION_SCHEMA
2024.07.25 17:13:27.520464 [ 1 ] {} <Test> DatabaseMemory(INFORMATION_SCHEMA): Counting attached table STATISTICS to database INFORMATION_SCHEMA
```

**Comment by alexey-milovidov** [comment]
Ok.

When checking the implementation, I had a thought - why do we make it so smart? Maybe add the CurrentMetric::Increment object into every IStorage instance, and don't bother the fact that it will count all system, temporary, and wrapper engines?

But as long as we fix it, it is good to me.

**Comment by serxa** [comment]
I had the same idea about increment object, it would be much safer. But current implementation works. Regarding smartness, at some point we have to check limits and now they rely on values of CurrentMetric, so anyway we have to take care of not counting (or subtracting) unnecessary tables/databases. I think it is good/simple enough now. We can leave it as is.

**Review by hanfei1991 — APPROVED** [review]

**Pull request merged**
