### PR TITLE
Introduce more fields for in-source function documentation

### PR DESCRIPTION
**Pull request by rschu1ze**
Related: #49222

1. renamed class `Documentation` to `FunctionDocumentation` as other database "objects" (settings, system tables, etc.) use different "templates" for documentation

2. made the class more fine-granular, instead of
- `Description`
- `Examples`
- `Categories`

we now have
- `Description`
- `Syntax`
- `Arguments`
- `Returned Value`
- `Examples`
- `Categories`.

This means more effort for the programmer but the generated documentation will look more uniform because more structural information is available. 

3. The new fields are also exposed in `system.functions` (but undocumented because they may change again in future)

@DanRoscigno 
@UnamedRus 

### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Split function-documentation into more fine-granular fields

### CODE REVIEW

**Comment by robot-ch-test-poll4** [comment]
This is an automated comment for commit 4a3b746140043c19625368c5ab9280b84fc637be with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/49300/4a3b746140043c19625368c5ab9280b84fc637be/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Review by hanfei1991 — COMMENTED** [review]
It looks cool! Is there a test to help me understand how the in-source documentation works?

**Comment by DanRoscigno** [comment]
> It looks cool! Is there a test to help me understand how the in-source documentation works?

This test finds the functions that do not have entries in system.functions:
[tests/queries/0_stateless/02415_all_new_functions_must_be_documented.sql](https://github.com/ClickHouse/ClickHouse/blob/master/tests/queries/0_stateless/02415_all_new_functions_must_be_documented.sql)

Here is how it is used now (by hand) [contrib writing guide](https://github.com/ClickHouse/clickhouse-docs/blob/main/contrib-writing-guide.md#grabbing-docs-from-system-tables)

In the future we plan to fill in the missing entries in the source and generate the docs in CI.  Adding the correct fields and the logic to populate the tables from the source are the first steps.

**Review by hanfei1991 — APPROVED** [review]

**Comment by UnamedRus** [comment]
What about Parameters column in addition to Arguments?

**Comment by DanRoscigno** [comment]
closes https://github.com/ClickHouse/ClickHouse/issues/8562

**Comment by rschu1ze** [comment]
System table `functions` now shows in column `arguments` a human-readable representation of the arguments similar to the one in the documentation, e.g.

```
- haystack: String in which the search is performed. String.
- needle: Substring to be searched. String.
```

> What about Parameters column in addition to Arguments?

Did you mean the argument type (e.g. "String")? This is currently part of `Documentation::description` which is admittedly not very clean (a separate field in class `Documentation` can be introduced in a separate PR).

**Comment by UnamedRus** [comment]
> Did you mean the argument type (e.g. "String")? This is currently part of Documentation::description which is admittedly not very clean (a separate field in class Documentation can be introduced in a separate PR).

Not exactly,

I'm talking about

quantile(0,9)(value)

Where 
value is argument
0.9 is parameter

**Comment by rschu1ze** [comment]
Interesting, haven't seen this syntax before, thanks! Makes for sure sense to have a field for that too.

I would nevertheless prefer to merge this PR as is because it is large and there is a risk of logical merge conflicts with other PRs. Also, this PR is technically about regular function docs whereas `quantile` is an aggregate function. I am sure there are even more "surprises" and things not covered yet in other function categories (think table functions, window functions, ...).

**Pull request merged**
