### PR TITLE
Backport #71626 to 24.3: Fix clickhouse-su to accept not only user/group names, but as well IDs

### PR DESCRIPTION
**Pull request by robot-clickhouse-ci-1**
Original pull-request https://github.com/ClickHouse/ClickHouse/pull/71626
Cherry-pick pull-request #71661

This pull-request is a last step of an automated backporting.
Treat it as a standard pull-request: look at the checks and resolve conflicts.
Merge it only if you intend to backport changes to the target branch, otherwise just close it.

### CODE REVIEW

**Comment by robot-ch-test-poll1** [comment]
*This is an automated comment for commit 88e6d39638fbe26bca53777b258cb168928dbeac with description of existing statuses. It's updated for the latest CI running*

[❌ Click here](https://s3.amazonaws.com/clickhouse-test-reports/71662/88e6d39638fbe26bca53777b258cb168928dbeac/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>ClickHouse build check</td><td>Builds ClickHouse in various configurations for use in further steps. You have to fix the builds that fail. Build logs often has enough information to fix the error, but you might have to reproduce the failure locally. The <b>cmake</b> options can be found in the build log, grepping for <b>cmake</b>. Use these options and follow the <a href="https://clickhouse.com/docs/en/development/build">general build process</a></td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/71662/88e6d39638fbe26bca53777b258cb168928dbeac/clickhouse_special_build_check/report.html">❌ failure</a></td></tr>
<tbody>
</table>

**Comment by Felixoid** [comment]
@azat could you help here? I don't see any rust-related code changed, but it fails https://github.com/ClickHouse/ClickHouse/actions/runs/11750250101/job/32738226268?pr=71662#step:8:11998

**Comment by azat** [comment]
I see that the `allocator-api2` is not pinned, and this causes troubles I guess, in this build

```
Nov 08 23:17:40   --> /rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/allocator-api2-0.2.19/src/stable/unique.rs:80:18
Nov 08 23:17:40    |
Nov 08 23:17:40 80 |         unsafe { self.pointer.as_ref() }
Nov 08 23:17:40    |                  ^^^^^^^^^^^^^^^^^^^^^
```

The build that is OK - https://github.com/ClickHouse/ClickHouse/actions/runs/11738913308/job/32702534911?pr=61995:

```
2024-11-08T08:59:07.2964186Z Nov 08 09:59:07    Compiling anyhow v1.0.93
2024-11-08T08:59:07.2965084Z Nov 08 09:59:07    Compiling allocator-api2 v0.2.18
2024-11-08T08:59:07.2970092Z Nov 08 09:59:07    Compiling ryu v1.0.18
```

This had been fixed already with `rust_vendor` https://github.com/ClickHouse/ClickHouse/pull/62297, but here the version should be pinned to make it work

**Comment by Felixoid** [comment]
should we backport the mentioned https://github.com/ClickHouse/ClickHouse/pull/62297 to make it resilient? Looks

**Comment by Felixoid** [comment]
Looks good, I'll try to rebase this PR on top of https://github.com/ClickHouse/ClickHouse/pull/71697

**Comment by Felixoid** [comment]
manually cherry-picker the commit 9c28c64adf04cd03711a846a17babd683dc2c002 from https://github.com/ClickHouse/ClickHouse/pull/67843 to have the integration tests fixed.

**Pull request merged**
