### PR TITLE
Enable per-query memory profiler (set to memory_profiler_step=4MiB) globally

### PR DESCRIPTION
**Pull request by azat**
Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Enable per-query memory profiler (set to memory_profiler_step=4MiB) globally

Detailed description / Documentation draft:
Let's see at performance tests. And yes, they should show the
difference, if any, since they uses clickhouse python driver, which does
not knows about default settings, so new server will have this setting
set, while old server - upstream/master, will not.

*NOTE: it is not an improvement, but it should be reflected in changelog, and there is no better category then `Improvement` for this patch*

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
Yes, this is an improvement :) People will get "always-on" memory profiling.

**Comment by azat** [comment]
>[Stress test (thread) — Killed by signal (in clickhouse-server.log)](https://clickhouse-test-reports.s3.yandex.net/29455/a218c3a28c769302acbe1b82568665eb7a012b16/stress_test_(thread).html#fail1)

<details>
```
+ zgrep -Fa ' <Fatal> ' /var/log/clickhouse-server/clickhouse-server.log /var/log/clickhouse-server/clickhouse-server.log.1 /var/log/clickhouse-server/clickhouse-server.log.2
/var/log/clickhouse-server/clickhouse-server.log.2:2021.09.28 02:43:21.780265 [ 488 ] {} <Fatal> BaseDaemon: (version 21.11.1.8225, build id: 1DD6D8D0F33AC58231DFBAC3854D1DF8FF3C59D2) (from thread 1650) Terminate called for uncaught exception:
/var/log/clickhouse-server/clickhouse-server.log.2:2021.09.28 02:43:21.787314 [ 488 ] {} <Fatal> BaseDaemon: Code: 24. DB::Exception: Cannot write to ostream at offset 2097152. (CANNOT_WRITE_TO_OSTREAM), Stack trace (when copying this message, always include the lines below):
/var/log/clickhouse-server/clickhouse-server.log.2:2021.09.28 02:43:21.787613 [ 488 ] {} <Fatal> BaseDaemon: 
/var/log/clickhouse-server/clickhouse-server.log.2:2021.09.28 02:43:21.788328 [ 488 ] {} <Fatal> BaseDaemon: 0. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/exception:0: Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x193253db in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.log.2:2021.09.28 02:43:21.790746 [ 488 ] {} <Fatal> BaseDaemon: 1. ./obj-x86_64-linux-gnu/../src/Common/Exception.cpp:59: DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x973313c in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.log.2:2021.09.28 02:43:21.791725 [ 488 ] {} <Fatal> BaseDaemon: 2. ./obj-x86_64-linux-gnu/../src/IO/WriteBufferFromOStream.cpp:0: DB::WriteBufferFromOStream::nextImpl() @ 0x983e9a5 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.log.2:2021.09.28 02:43:21.792772 [ 488 ] {} <Fatal> BaseDaemon: 3. ./obj-x86_64-linux-gnu/../src/IO/BufferBase.h:39: DB::WriteBufferFromHTTPServerResponse::nextImpl() @ 0x15e4c21c in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.log.2:2021.09.28 02:43:21.793168 [ 488 ] {} <Fatal> BaseDaemon: 4. ./obj-x86_64-linux-gnu/../src/IO/WriteBuffer.h:0: DB::WriteBuffer::write(char const*, unsigned long) @ 0x9719e2a in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.log.2:2021.09.28 02:43:21.793525 [ 488 ] {} <Fatal> BaseDaemon: 5. ./obj-x86_64-linux-gnu/../src/Compression/CompressedWriteBuffer.cpp:36: DB::CompressedWriteBuffer::nextImpl() @ 0x1449f7cd in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.log.2:2021.09.28 02:43:21.793806 [ 488 ] {} <Fatal> BaseDaemon: 6. ./obj-x86_64-linux-gnu/../src/IO/BufferBase.h:39: DB::CompressedWriteBuffer::~CompressedWriteBuffer() @ 0x1449fb0f in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.log.2:2021.09.28 02:43:21.794087 [ 488 ] {} <Fatal> BaseDaemon: 7. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:2615: std::__1::__shared_ptr_emplace<DB::CompressedWriteBuffer, std::__1::allocator<DB::CompressedWriteBuffer> >::__on_zero_shared() @ 0x15d5fa88 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.log.2:2021.09.28 02:43:21.794838 [ 488 ] {} <Fatal> BaseDaemon: 8. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:2518: DB::HTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&) @ 0x15dddd0a in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.log.2:2021.09.28 02:43:21.795569 [ 488 ] {} <Fatal> BaseDaemon: 9. ./obj-x86_64-linux-gnu/../src/Server/HTTP/HTTPServerConnection.cpp:0: DB::HTTPServerConnection::run() @ 0x15e45ec0 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.log.2:2021.09.28 02:43:21.797084 [ 488 ] {} <Fatal> BaseDaemon: 10. ./obj-x86_64-linux-gnu/../contrib/poco/Net/src/TCPServerConnection.cpp:57: Poco::Net::TCPServerConnection::start() @ 0x19240be3 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.log.2:2021.09.28 02:43:21.798128 [ 488 ] {} <Fatal> BaseDaemon: 11. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:1397: Poco::Net::TCPServerDispatcher::run() @ 0x192413f3 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.log.2:2021.09.28 02:43:21.798850 [ 488 ] {} <Fatal> BaseDaemon: 12. ./obj-x86_64-linux-gnu/../contrib/poco/Foundation/src/ThreadPool.cpp:213: Poco::PooledThread::run() @ 0x193c3116 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.log.2:2021.09.28 02:43:21.800690 [ 488 ] {} <Fatal> BaseDaemon: 13. ./obj-x86_64-linux-gnu/../contrib/poco/Foundation/src/Thread.cpp:56: Poco::(anonymous namespace)::RunnableHolder::run() @ 0x193c12f0 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.log.2:2021.09.28 02:43:21.801012 [ 488 ] {} <Fatal> BaseDaemon: 14. ./obj-x86_64-linux-gnu/../contrib/poco/Foundation/include/Poco/SharedPtr.h:277: Poco::ThreadImpl::runnableEntry(void*) @ 0x193bf9c8 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.log.2:2021.09.28 02:43:21.802092 [ 488 ] {} <Fatal> BaseDaemon: 15. __tsan_thread_start_func @ 0x965e94d in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.log.2:2021.09.28 02:43:21.802833 [ 488 ] {} <Fatal> BaseDaemon: 16. start_thread @ 0x9609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
```
</details>

#28604 

>[Stress test (undefined) — Server failed to start](https://clickhouse-test-reports.s3.yandex.net/29455/a218c3a28c769302acbe1b82568665eb7a012b16/stress_test_(undefined).html#fail1)

Looks like not enough time for starting the final server (after stressing)

**Comment by nikitamikhaylov** [comment]
@azat Look at `Terminate called for uncaught exception` in Stress test. I thought you fixed similar issue..

**Comment by azat** [comment]
I've already looked through CI checks BTW - https://github.com/ClickHouse/ClickHouse/pull/29455#issuecomment-928905677

**Review by nikitamikhaylov — APPROVED** [review]

**Comment by nikitamikhaylov** [comment]
> I've already looked through CI checks BTW - [#29455 (comment)](https://github.com/ClickHouse/ClickHouse/pull/29455#issuecomment-928905677)

Sorry..

**Pull request merged**
