### PR TITLE
Ldap role mapping deadlock fix

### LINKED ISSUE #22221: LDAP: changing groups for user makes Clickhouse fail to log in
**Describe the bug**
Clickhouse fails to log users after changing groups at LDAP for one user

**Does it reproduce on recent release?**
I've checked It on 21.2.5.5 and 21.3.4.25

**How to reproduce**
E.g. there is LDAP user *user_1* and there are two LDAP groups *role_1* and *role_2*, which are mapped to the Clickhouse roles with the same names. 
At the beginning *user_1* is only at *role_1* group
1. Log *user_1* in by clickhouse-client and check grants:
```
SHOW GRANTS

┌─GRANTS─────────────────────────────────────────┐
│ GRANT role1 TO user_1 │
└────────────────────────────────────────────────┘
```
2. Exclude *user_1* from *role_1* and assign him to the *role_2* group
3.  Try to log him in by clickhouse-client again. Login process  hangs forever. Also other users can't log in too.

**Expected behavior**
User will have updated grants after the re-login

**Error message and/or stacktrace**
I found no logs for that :(

**Additional context**
Clickhouse on CentOS, freeipa as a LDAP

### PR DESCRIPTION
**Pull request by traceon**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category:
- Bug Fix

Changelog entry:
- Fixed the deadlock that can happen during LDAP role (re)mapping, when LDAP group is mapped to a nonexistent local role

Detailed description:
- Caused by recursive execution paths that enter `MemoryAccessStorage` methods.
- Closes #22221

### CODE REVIEW

**Comment by traceon** [comment]
@vzakaznikov Should we add a test for this case?

1. the ldap server is configured as a user directory in clickhouse
2. typical role mapping is configured there, with a `clickhouse_` prefix
3. `user1` user exists only in ldap
4. `role1` role exists in clickhouse
5. `unknown` role **does not** exist in clickhouse
6. `user1` is a member of `clickhouse_role1` group in ldap initially
7. `user1` logs in successfully (`show grants` shows only `role1`), then logs out
8. `user1` also becomes a member of `clickhouse_unknown` group in ldap (clickhouse server process **is not** restarted during this)
9. `user1` should be able to log in successfully again (with `show grants` still showing only `role1`)

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
@mergifyio update

**Comment by alexey-milovidov** [comment]
@Mergifyio update

**Comment by vzakaznikov** [comment]
@traceon, see https://github.com/ClickHouse/ClickHouse/pull/25278/commits/33f270c2dceb4eab3522a61ef76de1f5d6126edf for the new test.

**Pull request merged**
