### PR TITLE
Fix EXPLAIN format for MySQL client

### PR DESCRIPTION
**Pull request by bohutang**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix explain query format overwrite by default, issue https://github.com/ClickHouse/ClickHouse/issues/12432

Detailed description / Documentation draft:

...

By adding documentation, you'll allow users to try your new feature immediately, not when someone else will have time to document it later. Documentation is necessary for all features that affect user experience in any way. You can add brief documentation draft above, or add documentation right into your patch as Markdown files in [docs](https://github.com/ClickHouse/ClickHouse/tree/master/docs) folder.

If you are doing this for the first time, it's recommended to read the lightweight [Contributing to ClickHouse Documentation](https://github.com/ClickHouse/ClickHouse/tree/master/docs/README.md) guide first.

### CODE REVIEW

**Comment by BohuTANG** [comment]
@KochetovNicolai 
May i have your review?

Cc @alexey-milovidov

**Comment by alexey-milovidov** [comment]
I'm Ok with this change.

It effectively removes default format for EXPLAIN query that was set in parser level. And I think we should not have done it this way, because default format can be also overriden in clickhouse-client config, in URL parameter, etc.

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
> Yandex synchronization check

Known issue.

**Comment by alexey-milovidov** [comment]
@KochetovNicolai Should backport to 20.6.

**Pull request merged**
