### PR TITLE
Add odbc-bridge library to macos builds

### PR DESCRIPTION
**Pull request by Felixoid**
### Changelog category (leave one):
- Build/Testing/Packaging Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Add clickhouse-odbc-bridge to the build.

---
### Modify your CI run:
**NOTE:** If your merge the PR with modified CI you **MUST KNOW** what you are doing
**NOTE:** Checked options will be applied if set before CI RunConfig/PrepareRunConfig step

#### Include tests (required builds will be added automatically):
- [ ]  Fast test
- [ ]  Integration Tests
- [ ]  Stateless tests
- [ ]  Stateful tests
- [ ]  Unit tests
- [ ]  Performance tests
- [ ]  All with ASAN
- [ ]  All with TSAN
- [ ]  All with Analyzer
- [x]  Build darwin
- [x]  Build darwin aarch64

#### Exclude tests:
- [ ]  Fast test
- [ ]  Integration Tests
- [ ]  Stateless tests
- [ ]  Stateful tests
- [ ]  Performance tests
- [ ]  All with ASAN
- [ ]  All with TSAN
- [ ]  All with MSAN
- [ ]  All with UBSAN
- [ ]  All with Coverage
- [ ]  All with Aarch64
- [ ]  Add your option here

#### Extra options:
- [ ]  do not test (only style check)
- [ ]  disable merge-commit (no merge from master before tests)
- [ ]  disable CI cache (job reuse)

#### Only specified batches in multi-batch jobs:
- [ ]  1
- [ ]  2
- [ ]  3
- [ ]  4

### CODE REVIEW

**Comment by robot-clickhouse** [comment]
*This is an automated comment for commit b5ae662fa3cb0059c6baafb851d36b2ce0fb8c6f with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/62704/b5ae662fa3cb0059c6baafb851d36b2ce0fb8c6f/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

**Comment by alexey-milovidov** [comment]
Do we need it?

**Comment by Felixoid** [comment]
See the linked discussion in https://github.com/ClickHouse/ClickHouse/issues/62703

**Comment by yakov-olkhovskiy** [comment]
let's say we need it if it can be done easily - MacOS is not our main platform but many people use it at least for evaluation, and odbc bridge is a nice to have feature for this....

**Comment by rschu1ze** [comment]
I think the builds fail because a platform-specific directory with config headers generated by the native build system is missing. For Linux, we have contrib/unixodbc-cmake/linux_x86_64, for Mac, there is no such directory.

**Comment by Felixoid** [comment]
How the odbc-bridge exists for arm64 though? https://s3.amazonaws.com/clickhouse-test-reports/0/ce5ea3b05afb18ef501bfb996d07545cd97dc615/clickhouse_build_check/report.html

**Comment by yakov-olkhovskiy** [comment]
Build fails because unixodbc was configured with autimake for linux. We don't have automake - it needs to be translated to cmake - will do later ..

**Pull request closed without merging**
