### PR TITLE
Backport #54430 to 23.3: reproduce and fix the bug in removeSharedRecursive

### PR DESCRIPTION
**Pull request by robot-ch-test-poll**
Original pull-request https://github.com/ClickHouse/ClickHouse/pull/54430
Cherry-pick pull-request #54521

This pull-request is a last step of an automated backporting.
Treat it as a standard pull-request: look at the checks and resolve conflicts.
Merge it only if you intend to backport changes to the target branch, otherwise just close it.

### CODE REVIEW

**Comment by robot-ch-test-poll4** [comment]
This is an automated comment for commit 3b6c0a3b3559c148b5d7cf32b85c9eae15bb9acd with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/54536/3b6c0a3b3559c148b5d7cf32b85c9eae15bb9acd/ci_running.html)
The overall status of the commit is 🟢 success

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>Push to Dockerhub</td><td>The check for building and pushing the CI related docker images to docker hub</td><td>🟢 success</td></tr>
</table>

**Comment by Felixoid** [comment]
@tavplubix this PR has broken integration tests completely https://s3.amazonaws.com/clickhouse-test-reports/54536/3b6c0a3b3559c148b5d7cf32b85c9eae15bb9acd/integration_tests__release_.html

**Comment by Felixoid** [comment]
I try to address it in https://github.com/ClickHouse/ClickHouse/pull/54720

**Comment by tavplubix** [comment]
Sorry, I thought it was some infrastructure issue. My bad, I should have checked the report.

It's okay to simply revert this backport

**Comment by Felixoid** [comment]
23.3 will remain for a long, it's better to backport changes from the master to have it compatible

Good thing, these mocks are in a separate module, so won't conflict with the existing one

**Pull request merged**
