### PR TITLE
Parquet filter pushdown

### LINKED ISSUE #23297: Parquet filter pushdown
Limit reads from parquet file, when filters exist:  similar https://drill.apache.org/docs/parquet-filter-pushdown/

### PR DESCRIPTION
**Pull request by al13n321**
### Changelog category (leave one):
- Performance Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Parquet filter pushdown. I.e. when reading Parquet files, row groups (chunks of the file) are skipped based on the WHERE condition and the min/max values in each column. In particular, if the file is roughly sorted by some column, queries that filter by a short range of that column will be much faster.

Closes https://github.com/ClickHouse/ClickHouse/issues/23297

### CODE REVIEW

**Comment by danthegoodman1** [comment]
I'd mark closes https://github.com/ClickHouse/ClickHouse/issues/23297

**Comment by liuneng1994** [comment]
I found on my re-implemented parquet reader that filters need to be pushed down to column decoder, especially for dictionary-encoded string columns.

**Comment by zhanglistar** [comment]
@al13n321 Clickhouse Arrow version lags two big versions of upstream, do you have plan to upgrade the version?

**Comment by al13n321** [comment]
> I found on my re-implemented parquet reader that filters need to be pushed down to column decoder, especially for dictionary-encoded string columns.

I don't understand, can you elaborate?

This PR just looks at column chunk statistics in the FileMetaData struct, then just skips row groups. No deeper integration with the decoder seems necessary. Do you mean one of these?:
 * We could also filter out individual pages based on page statistics. But that seems really difficult and not worthwhile.
 * Don't expand dictionary-encoded columns into full columns, keep them in memory as dictionary-encoded (ColumnLowCardinality) throughout the pipeline as much as possible. Kind of like if LowCardinality wasn't a type but just an internal detail of column representation. That would be nice. Seems unrelated to this task.
 * We could do PREWHERE on row groups, just like on merge tree granules. I.e. first decode the columns needed for PREWHERE, then evaluate the PREWHERE expression, and if all rows are rejected don't read+decode the rest of the columns. Can also skip individual pages based on the filter mask.

Btw, how's the reimplementation going? I'm looking forward to it!

**Comment by liuneng1994** [comment]
> > I found on my re-implemented parquet reader that filters need to be pushed down to column decoder, especially for dictionary-encoded string columns.
> 
> I don't understand, can you elaborate?
> 
> This PR just looks at column chunk statistics in the FileMetaData struct, then just skips row groups. No deeper integration with the decoder seems necessary. Do you mean one of these?:
> 
> * We could also filter out individual pages based on page statistics. But that seems really difficult and not worthwhile.
> * Don't expand dictionary-encoded columns into full columns, keep them in memory as dictionary-encoded (ColumnLowCardinality) throughout the pipeline as much as possible. Kind of like if LowCardinality wasn't a type but just an internal detail of column representation. That would be nice. Seems unrelated to this task.
> * We could do PREWHERE on row groups, just like on merge tree granules. I.e. first decode the columns needed for PREWHERE, then evaluate the PREWHERE expression, and if all rows are rejected don't read+decode the rest of the columns. Can also skip individual pages based on the filter mask.
> 
> Btw, how's the reimplementation going? I'm looking forward to it!

The second point is that I have implemented this method, but the performance is still not as good as the Velox Parquet reader, and it is still being investigated. The main gap here lies in the processing of the filter, and there is no gap in the performance of data decoding. There's an experimental PR here, and the code is ugly. https://github.com/oap-project/gluten/pull/1997/files

**Comment by liuneng1994** [comment]
RowGroup Filter and Page Filter rely on the physical order of the data and are hardly effective on benchmarks like TPCH

**Comment by danthegoodman1** [comment]
> We could do PREWHERE on row groups, just like on merge tree granules. I.e. first decode the columns needed for PREWHERE, then evaluate the PREWHERE expression, and if all rows are rejected don't read+decode the rest of the columns. Can also skip individual pages based on the filter mask.

IIUC then prewhere would not take effect on parquet pushdown, and would have to manually be implemented with nested subqueries in the current form of this PR?

**Comment by Avogar** [comment]
Can we add a performance test? (int `tests/performance`)

**Comment by Avogar** [comment]
Screenshot 2023-08-18 at 13 57 31

Nice!

**Review by Avogar — APPROVED** [review]

**Comment by al13n321** [comment]
`Performance Comparison` regressions seem spurious, except for this one:
```
SELECT WatchID FROM table_Parquet FORMAT Null
```
which now takes 3 ms instead of 2 ms. It's plausible that ~1ms is really how long the new filtering code takes (on a file with 133 columns and 1 row group), and I guess that's ok.

**Pull request merged**
