### PR TITLE
Collect logs for the system.text_log table even before it is initialized, to record the server startup

### LINKED ISSUE #50843: Collect logs for the system.text_log table even before it is initialized, to record the server startup.
**Use case**

I want to count on the system.text_log table for logs.
That's why I need all the logs there.

**Describe the solution you'd like**

Initialize the queue earlier and let it buffer the events before table initialization.

### PR DESCRIPTION
**Pull request by kardymonds**
Close https://github.com/ClickHouse/ClickHouse/issues/50843

- logic has not been changed;
- SystemLogBase logically is not needed, but seems like technically used for linking without TextLog;

### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Log messages are written to text_log from the beginning.

### CODE REVIEW

**Comment by robot-clickhouse-ci-1** [comment]
This is an automated comment for commit f153d6aa3c69b5d7a6e6df87ffdb84b1632e5abe with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/52113/f153d6aa3c69b5d7a6e6df87ffdb84b1632e5abe/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Comment by nikitamikhaylov** [comment]
Is it a duplicate of https://github.com/ClickHouse/ClickHouse/pull/51360 ? Seems like the problem was already fixed.

**Comment by rvasin** [comment]
> Is it a duplicate of #51360 ? Seems like the problem was already fixed.

No. It's not the duplicate.
As Azat explained https://github.com/ClickHouse/ClickHouse/pull/51360#issuecomment-1605678454 PR #51360 is not the complete solution to https://github.com/ClickHouse/ClickHouse/issues/50843

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
This is amazing!

**Pull request merged**
