### PR TITLE
Allow full range for var-int encoded integers

### LINKED ISSUE #51486: Catched `Logical error: 'Distributed task iterator is not initialized'.`
**Describe the bug**
A link to the report https://s3.amazonaws.com/clickhouse-test-reports/51478/5fdb19672bc443222560df00e0b76add05a1ad10/fuzzer_astfuzzerasan/report.html

**How to reproduce**
The query in the report is `SELECT number % NULL, NULL, sum(number) AS val FROM remote('127.0.0.{2,3}', numbers(toUInt64(-1))) GROUP BY number, number % 1023 WITH CUBE ORDER BY toUInt16(10) DESC NULLS LAST SETTINGS group_by_use_nulls = 1`

### PR DESCRIPTION
**Pull request by rschu1ze**
Resolves: #51486

Until now, it was illegal to encode 64-bit (unsigned) integers with
MSB=1, i.e. values > (1ULL<<63) - 1, as [var-int](https://en.wikipedia.org/wiki/Variable-length_quantity). In more detail, the
var-int code used by ClickHouse server and client spent at most 9 bytes
per value such that 9 * 7 = 63 bits could be encoded. Some 3rd party
clients (e.g. Rust clickhouse-rs) have the same limitation, whereas other
clients understand the full range (Python clickhouse-driver).

PRs #47608 and #48628 added sanity checks as asserts or exceptions
during var-int encoding on the server side. This was considered okay as
such huge integers so far occurred only during testing (usually fuzzing)
but not in practice.

Issue #51486 is a new fuzzing issue where the exception thrown from the
sanity check led to a half-baked progress packet and as a result, a
logical error / server crash.

The only fix which is not another bandaid is to allow the full range in
var-int coding. Clients will have to allow the full range too, a note
will be added to the changelog. (the alternative was to create another
protocol version but as var-int is used all over the place this was
considered infeasible.)

Review note: only this [commit](https://github.com/ClickHouse/ClickHouse/pull/51905/commits/271297823ae6abe82908220d1a540fbf0113f4d8) is relevant.

### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Var-int encoded integers (e.g. used by the native protocol) can now use the full 64-bit range. 3rd party clients are advised to update their var-int code accordingly.

### CODE REVIEW

**Comment by robot-ch-test-poll2** [comment]
This is an automated comment for commit 271297823ae6abe82908220d1a540fbf0113f4d8 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/51905/271297823ae6abe82908220d1a540fbf0113f4d8/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Review by alexey-milovidov — APPROVED** [review]

**Comment by Algunenano** [comment]
It's a really corner case but, isn't this breaking compatibility (for good reasons though)?

If a server with this change writes data (an aggregation state for example) containing a varint in the 2^63..2^64 range and that data is then read by an older server, the older server will read it incorrectly, right? I'm not saying this needs to be addressed, but if this is the case then it should be note that it might happen.

**Comment by azat** [comment]
Agree with @Algunenano I guess this PR at least should be marked as backward incompatible change.

**Comment by rschu1ze** [comment]
This PR is not backwards-incompatible in the sense that something which previously worked no longer works but to increase "visibility" when generating the changelog, I marked it as backward-incompatible. I'll close the automatically generated cherry-picks to older versions.

**Comment by azat** [comment]
At least this may help to driver developers, which may notice this change and update their drivers.

**Pull request merged**
