### PR TITLE
allow nulls in string field (mongodb dictionary)

### PR DESCRIPTION
**Pull request by gerasim13**
Если в поле содержится null запрос выкинет эксепшн.
Fix DB::Exception: Type mismatch, expected String, got type id = 10 for column product_id, e.what() = DB::Exception

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
Mostly Ok.

Now what is the result if there was null?
Is it a string with `null` or an empty string?

Does it make sense to use similar logic for other data types?

For MySQL and ODBC sources it will be default value for all data types (example: empty string for String):
```
            if (!value.isNull())
                insertValue(*columns[idx], description.types[idx], value);
            else
                insertDefaultValue(*columns[idx], *description.sample_columns[idx]);
```

Is the logic for MongoDB will be consistent with this behaviour?

**Comment by gerasim13** [comment]
In case when i receive string with null if i query document by objectid and there is no documents with supplied id, i'm happy (maybe becase it works and doesnt throw exception).

I tried to insert default value, but it doesnt work in my case. Every time this code throws exception
`Poco::Exception. Code: 1000, e.code() = 0, e.displayText() = Null pointer, e.what() = Null pointer`

```
                if (value.isNull() || value->type() == Poco::MongoDB::ElementTraits<Poco::MongoDB::NullValue>::TypeId)
                {
                    insertDefaultValue(*columns[idx], *description.sample_columns[idx]);
                }
                else
                {
                    insertValue(*columns[idx], description.types[idx], *value, name);
                }
```

I also make possible to query documents by ObjectId (not just retrieve objectid as string value), but i'm not sure in this solution:

```
                    /// Convert string to ObjectID
                    if (attr.second.injective)
                    {
                        String _str(get<String>((*key_columns[attr.first])[row_idx]));
                        Poco::MongoDB::ObjectId::Ptr _id(new Poco::MongoDB::ObjectId(_str));
                        key.add(attr.second.name, _id);
                    }
                    else
                    {
                        key.add(attr.second.name, get<String>((*key_columns[attr.first])[row_idx]));
                    }
```

I know that 'injective' doesn't mean that i can convert my string to another type, but i really need this logic.

**Comment by gerasim13** [comment]
sorry i think i found mistake in my code. i will push fixed version to my branche soon

**Comment by gerasim13** [comment]
i think i'm finish for now, but i think i need to rewrite mongo integration soon. the poco driver seems outdated. i cant to query my documents from view with poco.

**Comment by alexey-milovidov** [comment]
Almost Ok.

I can merge but without this change:
`if (_str.size() == 24) ...`
that looks weird.

`if (attr.second.injective)`
This also is very misleading.

You can invent special property of an attribute specifically to say that it is an object_id.
For example, `<key>...<attribute>... <is_object_id>true</is_object_id>`

**Comment by alexey-milovidov** [comment]
Thanks!

**Pull request merged**
