### PR TITLE
Rename directory monitor concept into background INSERT

### PR DESCRIPTION
**Pull request by azat**
### Changelog category (leave one):
- Backward Incompatible Change

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Rename directory monitor concept into background INSERT. All settings `*directory_monitor*` had been renamed to `distributed_background_insert*`. **Backward compatibility should be preserved** (since old settings had been added as an alias).

Rename the following query settings (with preserving backward compatibility, by keeping old name as an alias):
- `distributed_directory_monitor_sleep_time_ms` -> `distributed_background_insert_sleep_time_ms`
- `distributed_directory_monitor_max_sleep_time_ms` -> `distributed_background_insert_max_sleep_time_ms`
- `distributed_directory_monitor_batch` -> `distributed_background_insert_batch_inserts`
- `distributed_directory_monitor_split_batch_on_failure` -> `distributed_background_insert_split_batch_on_failure`
- `insert_distributed_sync` -> `distributed_foreground_insert`
- `insert_distributed_timeout` -> `distributed_background_insert_timeout`

*And also group all settings related to distributed INSERTs in one place in `Settings.h`*

Rename the following table settings (with preserving backward compatibility, by keeping old name as an alias):
- `monitor_batch_inserts` -> `background_insert_batch`
- `monitor_split_batch_on_failure` -> `background_insert_split_batch_on_failure`
- `directory_monitor_sleep_time_ms` -> `background_insert_sleep_time_ms`
- `directory_monitor_max_sleep_time_ms` -> `background_insert_max_sleep_time_ms`

_P.S. Marked as `Backward Incompatible Change` just to underling this change in changelog._

Follow-up for: #45491 (cc @tavplubix @hanfei1991 )

### CODE REVIEW

**Comment by robot-ch-test-poll3** [comment]
*This is an automated comment for commit fb6ffdbc52531b65bf7a90f50cc0fc2fcd8f488c with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/55978/fb6ffdbc52531b65bf7a90f50cc0fc2fcd8f488c/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td><a href="https://github.com/ClickHouse/ClickHouse/actions/runs/6628614520">✅ success</a></td></tr>
<tbody>
</table>
</details>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/55978/fb6ffdbc52531b65bf7a90f50cc0fc2fcd8f488c/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Comment by tavplubix** [comment]
> Rename directory monitor concept into async INSERT. 

Why? I understand that "directory monitor" exposes some internal name from code that a user should not know about, but:
 - the change is backward incompatible
 - "async insert" is confusing: we have another feature with the same name https://clickhouse.com/docs/en/optimize/asynchronous-inserts

**Comment by azat** [comment]
> the change is backward incompatible

Actually it should be 100% compatible, since old settings preserved as aliases for new ones, and there is a test for this.

> "async insert" is confusing: we have another feature with the same name [clickhouse.com/docs/en/optimize/asynchronous-inserts](https://clickhouse.com/docs/en/optimize/asynchronous-inserts)

But this in context of distributed, do you still think that they should not match?

**Comment by tavplubix** [comment]
> > the change is backward incompatible
> 
> Actually it should be 100% compatible, since old settings preserved as aliases for new ones, and there is a test for this.

Sorry, I don't notice that from the first glance. And we already have settings aliases (I didn't know that), so it doesn't introduce more complexity. Then it's okay if the test is not flaky :) 


> > "async insert" is confusing: we have another feature with the same name [clickhouse.com/docs/en/optimize/asynchronous-inserts](https://clickhouse.com/docs/en/optimize/asynchronous-inserts)
> 
> But this in context of distributed, do you still think that they should not match?

Yes, I think that the "distributed_" prefix doesn't make it less confusing

**Comment by azat** [comment]
> Yes, I think that the "distributed_" prefix doesn't make it less confusing

The problem is that there is old setting that named `insert_distributed_sync`, and if it not "sync" that it is "async".
Okay, let me think what could be done with the most hardest problem - naming...

**Comment by azat** [comment]
@tavplubix how about "background_insert"? It actually even better describe what internally happens.

**Comment by tavplubix** [comment]
Yep, sounds good

**Comment by azat** [comment]
>Upgrade check (tsan) — Logical error thrown (see clickhouse-server.log or logical_errors.txt)


```
/var/log/clickhouse-server/clickhouse-server.err.log:2023.11.01 02:49:04.648384 [ 1390 ] {} <Error> 75bc9495-20e3-44b8-ade3-4ac38b8717ee::all_0_5_3_14 (MergeFromLogEntryTask): virtual bool DB::ReplicatedMergeMutateTaskBase::executeStep(): Code: 49. DB::Exception: Invalid number of rows in Chunk column UInt64 position 5: expected 8192, got 5: While executing MergeTreeSequentialSource. (LOGICAL_ERROR), Stack trace (when copying this message, always include the lines below):
/var/log/clickhouse-server/clickhouse-server.err.log:2023.11.01 02:49:04.648459 [ 1390 ] {} <Error> MergeTreeBackgroundExecutor: Exception while executing background task {75bc9495-20e3-44b8-ade3-4ac38b8717ee::all_0_5_3_14}: Code: 49. DB::Exception: Invalid number of rows in Chunk column UInt64 position 5: expected 8192, got 5: While executing MergeTreeSequentialSource. (LOGICAL_ERROR), Stack trace (when copying this message, always include the lines below):
```

**Comment by tavplubix** [comment]
> > Upgrade check (tsan) — Logical error thrown (see clickhouse-server.log or logical_errors.txt)
> 
> ```
> /var/log/clickhouse-server/clickhouse-server.err.log:2023.11.01 02:49:04.648384 [ 1390 ] {} <Error> 75bc9495-20e3-44b8-ade3-4ac38b8717ee::all_0_5_3_14 (MergeFromLogEntryTask): virtual bool DB::ReplicatedMergeMutateTaskBase::executeStep(): Code: 49. DB::Exception: Invalid number of rows in Chunk column UInt64 position 5: expected 8192, got 5: While executing MergeTreeSequentialSource. (LOGICAL_ERROR), Stack trace (when copying this message, always include the lines below):
> /var/log/clickhouse-server/clickhouse-server.err.log:2023.11.01 02:49:04.648459 [ 1390 ] {} <Error> MergeTreeBackgroundExecutor: Exception while executing background task {75bc9495-20e3-44b8-ade3-4ac38b8717ee::all_0_5_3_14}: Code: 49. DB::Exception: Invalid number of rows in Chunk column UInt64 position 5: expected 8192, got 5: While executing MergeTreeSequentialSource. (LOGICAL_ERROR), Stack trace (when copying this message, always include the lines below):
> ```

https://github.com/ClickHouse/ClickHouse/issues/56202

**Review by tavplubix — APPROVED** [review]

**Pull request merged**
