### PR TITLE
Fix bitmapHasAny segment fault

### PR DESCRIPTION
**Pull request by yuzhichang**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Category (leave one):
- Bug Fix

Short description (up to few sentences):
Fix for https://github.com/yandex/ClickHouse/issues/5479

Detailed description (optional):
Bitmap aggregation functions work, however combination of bitmapHasAny  and scalar subquery causes segment fault.

```
CREATE TABLE trips ( \
  id UInt64, \
  vendor_id String, \
  pickup_datetime DateTime \
) engine=MergeTree() \
PARTITION BY toYYYYMM(pickup_datetime) \
ORDER BY (pickup_datetime, id);

INSERT INTO trips SELECT number, 'nj', '2019-01-01 00:00:00' FROM numbers(1,5);

-- fine
SELECT count(*)
FROM trips 
WHERE bitmapHasAny(
(
    SELECT groupBitmapState(id)
    FROM trips 
), bitmapBuild(CAST([1,2,3], 'Array(UInt64)')));

-- fine
SELECT count(*)
FROM trips 
WHERE bitmapHasAny(bitmapBuild([id]), bitmapBuild([id]));

-- error, server segment fault
SELECT count(*)
FROM trips 
WHERE bitmapHasAny(
(
    SELECT groupBitmapState(id)
    FROM trips 
), bitmapBuild([id]))
```

My change is: for ColumnConst, use the getData()[0] as the AggregateDataPtr.

### CODE REVIEW

**Comment by andyyzh** [comment]
Similar logic exists in FunctionBitmap and needs to be modified, thanks.

**Comment by yuzhichang** [comment]
@alexey-milovidov I don't think the failing tests are caused by my change. On my machine, they are failing without my change. What's the test setup on github?

**Comment by yuzhichang** [comment]
@andyyzh FunctionBitmap::executeBitmapData is bit different with FunctionBitmapCardinality::executeIntType. executeBitmapData() uses the first bitmap as the result. So if the first bitmap is ColumnConst, the server will segment fault.
```
-- error, server segment fault
SELECT count(*) FROM trips WHERE bitmapCardinality(bitmapAnd(bitmapBuild(CAST([1,2,3], 'Array(UInt32)')), bitmapBuild([id])))>0;
```

**Comment by alexey-milovidov** [comment]
>  I don't think the failing tests are caused by my change. On my machine, they are failing without my change. What's the test setup on github?

It was temporarily issue with our CI environment.

**Pull request merged**
