### PR TITLE
Keeper no lock on append_entries

### PR DESCRIPTION
**Pull request by zhanglistar**
Changelog category (leave one):
- Performance Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
According https://github.com/eBay/NuRaft/issues/209, there is no need to lock the mothod.

> Information about CI checks: https://clickhouse.tech/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by kitaisreal** [comment]
@Mergifyio update

**Review by kitaisreal — APPROVED** [review]
@zhanglistar make sense.

**Comment by kitaisreal** [comment]
@zhanglistar need to check this in our CI with thread sanitizer.

**Comment by zhanglistar** [comment]
> @zhanglistar make sense.

@kitaisreal Thanks for your review.

**Comment by zhanglistar** [comment]
@kitaisreal  The failed checks still are cassandra or mongodb, non-relation with my change.

**Pull request merged**
