### PR TITLE
Introduce tupleFlatten function.

### PR DESCRIPTION
**Pull request by amosbird**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- New Feature

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

tupleFlatten is a special function which can introduce new columns to the SELECT list by flattening a named tuple. 

For instance, 

```
table kv:  key int, v1 int, v2 int, v3 int, v4 int, v5 int

select key, tupleFlatten(argMax((* except (key),), v1)) from kv group by key

┌─key─┬─v1─┬─v2─┬─v3─┬─v4─┬─v5─┐
│   4 │ 10 │ 20 │ 10 │ 20 │ 30 │
│   3 │ 70 │ 20 │ 10 │ 20 │ 30 │
│   2 │ 11 │ 20 │ 10 │ 20 │ 30 │
│   5 │ 10 │ 20 │ 10 │ 20 │ 30 │
│   1 │ 20 │ 20 │ 10 │ 20 │ 30 │
│   6 │ 10 │ 20 │ 10 │ 20 │ 30 │
│   7 │ 18 │ 20 │ 10 │ 20 │ 30 │
│   8 │ 30 │ 20 │ 10 │ 20 │ 30 │
└─────┴────┴────┴────┴────┴────┘

```

Detailed description / Documentation draft:

TBD.

### CODE REVIEW

**Comment by hczhcz** [comment]
If I understand it right, `tupleFlatten` is more close to a horizontal version of `arrayJoin` for tuples (not an `arrayFlatten` for tuples).

**Comment by amosbird** [comment]
> If I understand it right, `tupleFlatten` is more close to a horizontal version of `arrayJoin` for tuples (not an `arrayFlatten` for tuples).

Exactly. BTW arrayJoin has a standard name called `unnested`.

**Comment by KochetovNicolai** [comment]
Segfault:
```
SELECT tupleFlatten(argMax(tuple(* EXCEPT(number)), number)) + 3
FROM 
(
    SELECT
        number,
        number + 1 AS n_1,
        number + 2
    FROM numbers(10)
)
GROUP BY number % 2

2020.10.16 15:35:16.314829 [ 17411 ] {} <Fatal> BaseDaemon: ########################################
2020.10.16 15:35:16.315015 [ 17411 ] {} <Fatal> BaseDaemon: (version 20.11.1.4937, build id: 4EAFD0F1E721500B) (from thread 17224) (query_id: 806ff0b2-68c0-410b-a3a7-06bf63bcd444) Received signal Segmentation fault (11)
2020.10.16 15:35:16.315105 [ 17411 ] {} <Fatal> BaseDaemon: Address: NULL pointer. Access: read. Address not mapped to object.
2020.10.16 15:35:16.315183 [ 17411 ] {} <Fatal> BaseDaemon: Stack trace: 0x929d054 0x929f9a5 0x929fe72 0xdbe3892 0xdc89526 0xdc8e8bd 0xdc65cba 0xdc65d31 0xdc65a46 0xdc6ccc6 0xdc726f3 0xdc1d114 0xdc18025 0xdc137ef 0xdc1228d 0xddc1124 0xdb90f87 0xdf19670 0xdf186dd 0xe5b7b16 0xe5c4807 0x10d9acbf 0x10d9c6ce 0x10ecd989 0x10ec98ba 0x7f58fa3da6db 0x7f58f9cf7a3f
2020.10.16 15:35:16.315333 [ 17411 ] {} <Fatal> BaseDaemon: 2. DB::FunctionOverloadResolverAdaptor::getReturnTypeWithoutLowCardinality(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&) const @ 0x929d054 in /home/nik-kochetov/test/20.11.1.4937/usr/bin/clickhouse
2020.10.16 15:35:16.315408 [ 17411 ] {} <Fatal> BaseDaemon: 3. DB::FunctionOverloadResolverAdaptor::getReturnType(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&) const @ 0x929f9a5 in /home/nik-kochetov/test/20.11.1.4937/usr/bin/clickhouse
2020.10.16 15:35:16.315487 [ 17411 ] {} <Fatal> BaseDaemon: 4. DB::FunctionOverloadResolverAdaptor::build(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&) const @ 0x929fe72 in /home/nik-kochetov/test/20.11.1.4937/usr/bin/clickhouse
2020.10.16 15:35:16.315576 [ 17411 ] {} <Fatal> BaseDaemon: 5. DB::ActionsDAG::addFunction(std::__1::shared_ptr<DB::IFunctionOverloadResolver> const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, bool) @ 0xdbe3892 in /home/nik-kochetov/test/20.11.1.4937/usr/bin/clickhouse
2020.10.16 15:35:16.315672 [ 17411 ] {} <Fatal> BaseDaemon: 6. DB::ScopeStack::addFunction(std::__1::shared_ptr<DB::IFunctionOverloadResolver> const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, bool) @ 0xdc89526 in /home/nik-kochetov/test/20.11.1.4937/usr/bin/clickhouse
2020.10.16 15:35:16.315748 [ 17411 ] {} <Fatal> BaseDaemon: 7. DB::ActionsMatcher::visit(DB::ASTFunction const&, std::__1::shared_ptr<DB::IAST> const&, DB::ActionsMatcher::Data&) @ 0xdc8e8bd in /home/nik-kochetov/test/20.11.1.4937/usr/bin/clickhouse
2020.10.16 15:35:16.315856 [ 17411 ] {} <Fatal> BaseDaemon: 8. DB::InDepthNodeVisitor<DB::ActionsMatcher, true, std::__1::shared_ptr<DB::IAST> const>::visit(std::__1::shared_ptr<DB::IAST> const&) @ 0xdc65cba in /home/nik-kochetov/test/20.11.1.4937/usr/bin/clickhouse
2020.10.16 15:35:16.315928 [ 17411 ] {} <Fatal> BaseDaemon: 9. DB::InDepthNodeVisitor<DB::ActionsMatcher, true, std::__1::shared_ptr<DB::IAST> const>::visit(std::__1::shared_ptr<DB::IAST> const&) @ 0xdc65d31 in /home/nik-kochetov/test/20.11.1.4937/usr/bin/clickhouse
2020.10.16 15:35:16.315988 [ 17411 ] {} <Fatal> BaseDaemon: 10. ? @ 0xdc65a46 in /home/nik-kochetov/test/20.11.1.4937/usr/bin/clickhouse
2020.10.16 15:35:16.316051 [ 17411 ] {} <Fatal> BaseDaemon: 11. DB::SelectQueryExpressionAnalyzer::appendSelect(DB::ExpressionActionsChain&, bool) @ 0xdc6ccc6 in /home/nik-kochetov/test/20.11.1.4937/usr/bin/clickhouse
2020.10.16 15:35:16.316128 [ 17411 ] {} <Fatal> BaseDaemon: 12. DB::ExpressionAnalysisResult::ExpressionAnalysisResult(DB::SelectQueryExpressionAnalyzer&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, bool, bool, bool, std::__1::shared_ptr<DB::FilterInfo> const&, DB::Block const&) @ 0xdc726f3 in /home/nik-kochetov/test/20.11.1.4937/usr/bin/clickhouse
2020.10.16 15:35:16.316219 [ 17411 ] {} <Fatal> BaseDaemon: 13. DB::InterpreterSelectQuery::getSampleBlockImpl() @ 0xdc1d114 in /home/nik-kochetov/test/20.11.1.4937/usr/bin/clickhouse
2020.10.16 15:35:16.316275 [ 17411 ] {} <Fatal> BaseDaemon: 14. ? @ 0xdc18025 in /home/nik-kochetov/test/20.11.1.4937/usr/bin/clickhouse
2020.10.16 15:35:16.316344 [ 17411 ] {} <Fatal> BaseDaemon: 15. DB::InterpreterSelectQuery::InterpreterSelectQuery(std::__1::shared_ptr<DB::IAST> const&, DB::Context const&, std::__1::shared_ptr<DB::IBlockInputStream> const&, std::__1::optional<DB::Pipe>, std::__1::shared_ptr<DB::IStorage> const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&) @ 0xdc137ef in /home/nik-kochetov/test/20.11.1.4937/usr/bin/clickhouse
2020.10.16 15:35:16.316420 [ 17411 ] {} <Fatal> BaseDaemon: 16. DB::InterpreterSelectQuery::InterpreterSelectQuery(std::__1::shared_ptr<DB::IAST> const&, DB::Context const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) @ 0xdc1228d in /home/nik-kochetov/test/20.11.1.4937/usr/bin/clickhouse
2020.10.16 15:35:16.316512 [ 17411 ] {} <Fatal> BaseDaemon: 17. DB::InterpreterSelectWithUnionQuery::InterpreterSelectWithUnionQuery(std::__1::shared_ptr<DB::IAST> const&, DB::Context const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) @ 0xddc1124 in /home/nik-kochetov/test/20.11.1.4937/usr/bin/clickhouse
2020.10.16 15:35:16.316633 [ 17411 ] {} <Fatal> BaseDaemon: 18. DB::InterpreterFactory::get(std::__1::shared_ptr<DB::IAST>&, DB::Context&, DB::QueryProcessingStage::Enum) @ 0xdb90f87 in /home/nik-kochetov/test/20.11.1.4937/usr/bin/clickhouse
2020.10.16 15:35:16.316696 [ 17411 ] {} <Fatal> BaseDaemon: 19. ? @ 0xdf19670 in /home/nik-kochetov/test/20.11.1.4937/usr/bin/clickhouse
2020.10.16 15:35:16.316767 [ 17411 ] {} <Fatal> BaseDaemon: 20. DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::Context&, bool, DB::QueryProcessingStage::Enum, bool) @ 0xdf186dd in /home/nik-kochetov/test/20.11.1.4937/usr/bin/clickhouse
2020.10.16 15:35:16.316854 [ 17411 ] {} <Fatal> BaseDaemon: 21. DB::TCPHandler::runImpl() @ 0xe5b7b16 in /home/nik-kochetov/test/20.11.1.4937/usr/bin/clickhouse
2020.10.16 15:35:16.316970 [ 17411 ] {} <Fatal> BaseDaemon: 22. DB::TCPHandler::run() @ 0xe5c4807 in /home/nik-kochetov/test/20.11.1.4937/usr/bin/clickhouse
2020.10.16 15:35:16.317039 [ 17411 ] {} <Fatal> BaseDaemon: 23. Poco::Net::TCPServerConnection::start() @ 0x10d9acbf in /home/nik-kochetov/test/20.11.1.4937/usr/bin/clickhouse
2020.10.16 15:35:16.317092 [ 17411 ] {} <Fatal> BaseDaemon: 24. Poco::Net::TCPServerDispatcher::run() @ 0x10d9c6ce in /home/nik-kochetov/test/20.11.1.4937/usr/bin/clickhouse
2020.10.16 15:35:16.317180 [ 17411 ] {} <Fatal> BaseDaemon: 25. Poco::PooledThread::run() @ 0x10ecd989 in /home/nik-kochetov/test/20.11.1.4937/usr/bin/clickhouse
2020.10.16 15:35:16.317282 [ 17411 ] {} <Fatal> BaseDaemon: 26. Poco::ThreadImpl::runnableEntry(void*) @ 0x10ec98ba in /home/nik-kochetov/test/20.11.1.4937/usr/bin/clickhouse
2020.10.16 15:35:16.317352 [ 17411 ] {} <Fatal> BaseDaemon: 27. start_thread @ 0x76db in /lib/x86_64-linux-gnu/libpthread-2.27.so
2020.10.16 15:35:16.317530 [ 17411 ] {} <Fatal> BaseDaemon: 28. /build/glibc-2ORdQG/glibc-2.27/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:97: __GI___clone @ 0x121a3f in /usr/lib/debug/lib/x86_64-linux-gnu/libc-2.27.so


```

**Comment by alexey-milovidov** [comment]
@amosbird @KochetovNicolai I suddenly remember that I wanted to name this function `untuple`.

Why?

Because tupleFlatten is too similar name to arrayFlatten. And arrayFlatten does deep flattening of arrays, like

`arrayFlatten([[[1], []], [[2, 3]]]) = [1, 2, 3]`
So, it's expected that tupleFlatten will work this way:
`arrayFlatten((1, (2, 3))) = (1, 2, 3)`
But the function implemented is completely different.

And the name `untuple` is very intuitive because the operation it does is the opposite to collection of elements in to tuple:
`SELECT 1, 'Hello'`
`SELECT tuple(1, 'Hello')`
`SELECT untuple(tuple(1, 'Hello'))`

**Comment by KochetovNicolai** [comment]
Closing after #16242

**Pull request closed without merging**
