### PR TITLE
Fix error in subquery operators

### LINKED ISSUE #51918: nullptr dereference in subquery operators
Originally logical error in the test, and a segmentation fault in Fiddle.

**Test:** https://s3.amazonaws.com/clickhouse-test-reports/51881/c7ccf23a24a7fb2bb1245b76fc9169649cd474c3/stateless_tests__debug__[5_5].html

**Fiddle:** https://fiddle.clickhouse.com/1e170d25-91cf-4730-918f-045a407efec5

**Logs:**
```[b302d84f6a02] 2023.07.07 02:04:23.262906 [ 326 ] <Fatal> BaseDaemon: ########################################
[b302d84f6a02] 2023.07.07 02:04:23.262972 [ 326 ] <Fatal> BaseDaemon: (version 23.6.1.1524 (official build), build id: 39AC174BEE13B59373FF7F29F65984557B4408B0, git hash: d1c7e13d08868cb04d3562dcced704dd577cb1df) (from thread 322) (query_id: c5d7191d-6a92-488f-a289-c961b19c9d3f) (query: SELECT '', ['\0'], [], singleValueOrNull(( SELECT '\0' ) ), [''];) Received signal Segmentation fault (11)
[b302d84f6a02] 2023.07.07 02:04:23.263002 [ 326 ] <Fatal> BaseDaemon: Address: 0x7f72dabdaff8. Access: read. Address not mapped to object.
[b302d84f6a02] 2023.07.07 02:04:23.263030 [ 326 ] <Fatal> BaseDaemon: Stack trace: 0x0000000010b23cae 0x0000000010b226b1 0x000000001313ca7f 0x000000001313c253 0x0000000014e9ece8 0x0000000014e9aac7 0x0000000014ca3bc9 0x0000000014c9a890 0x0000000014c9ba23 0x000000000e2d5be3 0x000000000e2d83f5 0x000000000e2d1a74 0x000000000e2d7281 0x00007f738746f609 0x00007f7387394133
[b302d84f6a02] 2023.07.07 02:04:23.263100 [ 326 ] <Fatal> BaseDaemon: 2. ? @ 0x0000000010b23cae in /usr/bin/clickhouse
[b302d84f6a02] 2023.07.07 02:04:23.263125 [ 326 ] <Fatal> BaseDaemon: 3. ? @ 0x0000000010b226b1 in /usr/bin/clickhouse
[b302d84f6a02] 2023.07.07 02:04:23.263146 [ 326 ] <Fatal> BaseDaemon: 4. ? @ 0x000000001313ca7f in /usr/bin/clickhouse
[b302d84f6a02] 2023.07.07 02:04:23.263191 [ 326 ] <Fatal> BaseDaemon: 5. DB::Aggregator::executeOnBlock(std::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn>>>, unsigned long, unsigned long, DB::AggregatedDataVariants&, std::vector<DB::IColumn const*, std::allocator<DB::IColumn const*>>&, std::vector<std::vector<DB::IColumn const*, std::allocator<DB::IColumn const*>>, std::allocator<std::vector<DB::IColumn const*, std::allocator<DB::IColumn const*>>>>&, bool&) const @ 0x000000001313c253 in /usr/bin/clickhouse
[b302d84f6a02] 2023.07.07 02:04:23.263223 [ 326 ] <Fatal> BaseDaemon: 6. DB::AggregatingTransform::consume(DB::Chunk) @ 0x0000000014e9ece8 in /usr/bin/clickhouse
[b302d84f6a02] 2023.07.07 02:04:23.263248 [ 326 ] <Fatal> BaseDaemon: 7. DB::AggregatingTransform::work() @ 0x0000000014e9aac7 in /usr/bin/clickhouse
[b302d84f6a02] 2023.07.07 02:04:23.263273 [ 326 ] <Fatal> BaseDaemon: 8. DB::ExecutionThreadContext::executeTask() @ 0x0000000014ca3bc9 in /usr/bin/clickhouse
[b302d84f6a02] 2023.07.07 02:04:23.263301 [ 326 ] <Fatal> BaseDaemon: 9. DB::PipelineExecutor::executeStepImpl(unsigned long, std::atomic<bool>*) @ 0x0000000014c9a890 in /usr/bin/clickhouse
[b302d84f6a02] 2023.07.07 02:04:23.263326 [ 326 ] <Fatal> BaseDaemon: 10. ? @ 0x0000000014c9ba23 in /usr/bin/clickhouse
[b302d84f6a02] 2023.07.07 02:04:23.263358 [ 326 ] <Fatal> BaseDaemon: 11. ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::worker(std::__list_iterator<ThreadFromGlobalPoolImpl<false>, void*>) @ 0x000000000e2d5be3 in /usr/bin/clickhouse
[b302d84f6a02] 2023.07.07 02:04:23.263392 [ 326 ] <Fatal> BaseDaemon: 12. void std::__function::__policy_invoker<void ()>::__call_impl<std::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>(void&&)::'lambda'(), void ()>>(std::__function::__policy_storage const*) @ 0x000000000e2d83f5 in /usr/bin/clickhouse
[b302d84f6a02] 2023.07.07 02:04:23.263419 [ 326 ] <Fatal> BaseDaemon: 13. ThreadPoolImpl<std::thread>::worker(std::__list_iterator<std::thread, void*>) @ 0x000000000e2d1a74 in /usr/bin/clickhouse
[b302d84f6a02] 2023.07.07 02:04:23.263436 [ 326 ] <Fatal> BaseDaemon: 14. ? @ 0x000000000e2d7281 in /usr/bin/clickhouse
[b302d84f6a02] 2023.07.07 02:04:23.263458 [ 326 ] <Fatal> BaseDaemon: 15. ? @ 0x00007f738746f609 in ?
[b302d84f6a02] 2023.07.07 02:04:23.263495 [ 326 ] <Fatal> BaseDaemon: 16. __clone @ 0x00007f7387394133 in ?
[b302d84f6a02] 2023.07.07 02:04:23.391920 [ 326 ] <Fatal> BaseDaemon: Integrity check of the executable successfully passed (checksum: 2CCE0342490FE96D02C1130FB4CA7EE2)
[b302d84f6a02] 2023.07.07 02:04:23.392087 [ 326 ] <Fatal> BaseDaemon: Report this error to https://github.com/ClickHouse/ClickHouse/issues
[b302d84f6a02] 2023.07.07 02:04:23.392184 [ 326 ] <Fatal> BaseDaemon: Changed settings: output_format_pretty_color = false, output_format_pretty_grid_charset = 'ASCII'
```

### PR DESCRIPTION
**Pull request by alexey-milovidov**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix the case when using subquery operators such as `1 = ALL (SELECT ...)` with nullable type, or the `singleValueOrNull` aggregate function can lead to nullptr dereference. This closes #51918.

### CODE REVIEW

**Comment by robot-clickhouse-ci-1** [comment]
This is an automated comment for commit 2246e86159824f9e658ca28ecb796295a1b8585c with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/51922/2246e86159824f9e658ca28ecb796295a1b8585c/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Review by evillique — APPROVED** [review]

**Comment by evillique** [comment]
AST Fuzzer [report](https://s3.amazonaws.com/clickhouse-test-reports/51922/2246e86159824f9e658ca28ecb796295a1b8585c/fuzzer_astfuzzerubsan/report.html) is probably worth looking into, wasn't able to reproduce on the latest master: https://fiddle.clickhouse.com/f3f2729d-8c3f-4173-af35-cb63c2c3115b

**Comment by alexey-milovidov** [comment]
@evillique I was able to reproduce it easily:

https://fiddle.clickhouse.com/f5a254f4-e699-4be7-93ba-f70bd51f7810

**Comment by alexey-milovidov** [comment]
```
SET use_hedged_requests = false, max_parallel_replicas = 3, cluster_for_parallel_replicas = 'parallel_replicas', allow_experimental_parallel_reading_from_replicas = 1, parallel_replicas_for_non_replicated_merge_tree = 1;

CREATE TABLE nested (x UInt8) ENGINE = MergeTree ORDER BY ();
INSERT INTO nested VALUES (1);

SELECT 1 FROM nested
GROUP BY 1 WITH ROLLUP
ORDER BY max((SELECT 1 WHERE 0));
```

**Pull request merged**
