### PR TITLE
Fix settings constraints

### PR DESCRIPTION
**Pull request by thevar1able**
### Changelog category (leave one):

- Bug Fix (user-visible misbehavior in official stable or prestable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
 Placing profile settings after profile settings constraints in the configuration file made constraints ineffective.

### CODE REVIEW

**Review by serxa — APPROVED** [review]
LGTM

**Comment by serxa** [comment]
integration test `test_backup_restore_on_cluster/test.py::test_replicated_database_async` failure looks unrelated:
```
>               raise AssertionError(
                    "'{}' != '{}'\n{}".format(
                        expectation_tsv,
                        val,
                        "\n".join(expectation_tsv.diff(val, n1="expectation", n2="query")),
                    )
                )
E               AssertionError: 'RESTORED' != 'RESTORE_FAILED	Code: 608. DB::Exception: Got error from node1:9000. DB::Exception: Couldn\'t restore table mydb.tbl on other node or sync it (elapsed 1.042499s): While creating table mydb.tbl. Stack trace:\n\n0. DB::Exception::Exception(DB::Exception::MessageMasked const&, int, bool) @ 0xd1f0f3a in /usr/bin/clickhouse\n1. ? @ 0x9f13df4 in /usr/bin/clickhouse\n2. DB::DatabaseReplicated::createTableRestoredFromBackup(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context>, std::__1::shared_ptr<DB::IRestoreCoordination>, unsigned long) @ 0x121860b3 in /usr/bin/clickhouse\n3. DB::RestorerFromBackup::createTable(DB::QualifiedTableName const&) @ 0x11dbbfe8 in /usr/bin/clickhouse\n4. DB::RestorerFromBackup::createTables() @ 0x11daf335 in /usr/bin/clickhouse\n5. DB::RestorerFromBackup::run(DB::RestorerFromBackup::Mode) @ 0x11da9b6c in /usr/bin/clickhouse\n6. DB::BackupsWorker::doRestore(std::__1::shared_ptr<DB::ASTBackupQuery> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, DB::BackupInfo const&, DB::RestoreSettings, std::__1::shared_ptr<DB::IRestoreCoordination>, std::__1::shared_ptr<DB::Context>, bool) @ 0x11d78400 in /usr/bin/clickhouse\n7. ? @ 0x11d7c373 in /usr/bin/clickhouse\n8. ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::worker(std::__1::__list_iterator<ThreadFromGlobalPoolImpl<false>, void*>) @ 0xd2bd74a in /usr/bin/clickhouse\n9. void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::scheduleImpl<void>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::\'lambda0\'()>(void&&)::\'lambda\'(), void ()>>(std::__1::__function::__policy_storage const*) @ 0xd2bff77 in /usr/bin/clickhouse\n10. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xd2b9eaa in /usr/bin/clickhouse\n11. ? @ 0xd2bef41 in /usr/bin/clickhouse\n12. ? @ 0x7fa4399db609 in ?\n13. clone @ 0x7fa439900133 in ?\n. (CANNOT_RESTORE_TABLE) (version 22.13.1.242)'
E               @@ -1 +1 @@
E               -RESTORED
E               +RESTORE_FAILED	Code: 608. DB::Exception: Got error from node1:9000. DB::Exception: Couldn\'t restore table mydb.tbl on other node or sync it (elapsed 1.042499s): While creating table mydb.tbl. Stack trace:\n\n0. DB::Exception::Exception(DB::Exception::MessageMasked const&, int, bool) @ 0xd1f0f3a in /usr/bin/clickhouse\n1. ? @ 0x9f13df4 in /usr/bin/clickhouse\n2. DB::DatabaseReplicated::createTableRestoredFromBackup(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context>, std::__1::shared_ptr<DB::IRestoreCoordination>, unsigned long) @ 0x121860b3 in /usr/bin/clickhouse\n3. DB::RestorerFromBackup::createTable(DB::QualifiedTableName const&) @ 0x11dbbfe8 in /usr/bin/clickhouse\n4. DB::RestorerFromBackup::createTables() @ 0x11daf335 in /usr/bin/clickhouse\n5. DB::RestorerFromBackup::run(DB::RestorerFromBackup::Mode) @ 0x11da9b6c in /usr/bin/clickhouse\n6. DB::BackupsWorker::doRestore(std::__1::shared_ptr<DB::ASTBackupQuery> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, DB::BackupInfo const&, DB::RestoreSettings, std::__1::shared_ptr<DB::IRestoreCoordination>, std::__1::shared_ptr<DB::Context>, bool) @ 0x11d78400 in /usr/bin/clickhouse\n7. ? @ 0x11d7c373 in /usr/bin/clickhouse\n8. ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::worker(std::__1::__list_iterator<ThreadFromGlobalPoolImpl<false>, void*>) @ 0xd2bd74a in /usr/bin/clickhouse\n9. void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::scheduleImpl<void>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::\'lambda0\'()>(void&&)::\'lambda\'(), void ()>>(std::__1::__function::__policy_storage const*) @ 0xd2bff77 in /usr/bin/clickhouse\n10. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xd2b9eaa in /usr/bin/clickhouse\n11. ? @ 0xd2bef41 in /usr/bin/clickhouse\n12. ? @ 0x7fa4399db609 in ?\n13. clone @ 0x7fa439900133 in ?\n. (CANNOT_RESTORE_TABLE) (version 22.13.1.242)
```

**Comment by nikitamikhaylov** [comment]
@serxa Could you please create an issue about this failure or fix it if you can?

**Comment by nikitamikhaylov** [comment]
And changelog entry is wrong. This is a bugfix

**Pull request merged**
