### PR TITLE
Update clickhouse-keeper.md

### PR DESCRIPTION
**Pull request by andycol**
fix the run command and add example

Changelog category (leave one):

- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by alesapin** [comment]
Quite strange change, what is the idea @andycol?

**Comment by andycol** [comment]
@alesapin So the reason i changed the doc is because in the doc it doesnt say about creating the symlink therefore its easier to just run the command with the space before keeper
unless you think we also add how to create the symlink?

**Comment by alexey-milovidov** [comment]
Symlink was added in recent versions.

**Comment by andycol** [comment]
> Symlink was added in recent versions.

on version 22.1.3.7 it is not there

**Review by alesapin — APPROVED** [review]

**Pull request merged**
