### PR TITLE
Detect output format by file exctension in clickhouse-client(local)

### LINKED ISSUE #48634: Detect output format by file exctension in clickhouse-local (and maybe in client also)
```
clickhouse local --query "SELECT * FROM table" < California.jsonl > California.parquet
```

Similar how we detect it for input format.

### PR DESCRIPTION
**Pull request by HowePa**
close #48634 
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Support detect output format by file exctension in `clickhouse-client` and `clickhouse-local`

### CODE REVIEW

**Comment by HowePa** [comment]
CC @Avogar

**Comment by robot-ch-test-poll1** [comment]
*This is an automated comment for commit 112c1efb7da2619cb67a48ff7fbe65ecea8e44a9 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/61036/112c1efb7da2619cb67a48ff7fbe65ecea8e44a9/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

**Review by Avogar — APPROVED** [review]

**Comment by vdimir** [comment]
> Integration tests (asan, analyzer) [1/6] fail: 1, passed: 419 [Details](https://s3.amazonaws.com/clickhouse-test-reports/61036/112c1efb7da2619cb67a48ff7fbe65ecea8e44a9/integration_tests__asan__analyzer__[1_6].html)

`test_input_format_parallel_parsing_memory_tracking/test.py::test_memory_tracking_total`

<details>
<summary>Details</summary>


```
        instance.exec_in_container(
            [
                "bash",
                "-c",
                "clickhouse local -q \"SELECT arrayStringConcat(arrayMap(x->toString(cityHash64(x)), range(1000)), ' ') from numbers(10000)\" > data.json",
            ]
        )
    
        for it in range(0, 20):
            # the problem can be triggered only via HTTP,
            # since clickhouse-client parses the data by itself.
>           assert (
                instance.exec_in_container(
                    [
                        "curl",
                        "--silent",
                        "--show-error",
                        "--data-binary",
                        "@data.json",
                        "http://127.1:8123/?query=INSERT%20INTO%20null%20FORMAT%20TSV",
                    ]
                )
                == ""
            ), f"Failed on {it} iteration"
E           AssertionError: Failed on 0 iteration
E           assert 'Code: 27. DB::Exception: Cannot parse input: expected \'\\n\' before: \'\\t"meta":\\n\\t[\\n\\t\\t{\\n\\t\\t\\t"name": "arrayStringConcat(arrayMap(lambda(tuple(x), toString(cityHash64(x))), range(1000)), \\\' \\\')",\\n\\t\\t\\t"type": "String"\\n\\t\\t}\\n\\t],\\n\\n\\t"data":\\n\\t[\\n\': (at row 2)\n: \nRow 1:\nColumn 0,   name: row, type: String, parsed text: "{"\n\nRow 2:\nColumn 0,   name: row, type: String, parsed text: <EMPTY>\nERROR: Tab found where line feed is expected. It\'s like your file has more columns than expected.\nAnd if your file has the right number of columns, maybe it has an unescaped tab in a value.\n\n: While executing ParallelParsingBlockInputFormat. (CANNOT_PARSE_INPUT_ASSERTION_FAILED) (version 24.3.1.726)\n' == ''
E             + Code: 27. DB::Exception: Cannot parse input: expected '\n' before: '\t"meta":\n\t[\n\t\t{\n\t\t\t"name": "arrayStringConcat(arrayMap(lambda(tuple(x), toString(cityHash64(x))), range(1000)), \' \')",\n\t\t\t"type": "String"\n\t\t}\n\t],\n\n\t"data":\n\t[\n': (at row 2)
E             + : 
E             + Row 1:
E             + Column 0,   name: row, type: String, parsed text: "{"
E             + 
E             + Row 2:
E             + Column 0,   name: row, type: String, parsed text: <EMPTY>
E             + ERROR: Tab found where line feed is expected. It's like your file has more columns than expected.
E             + And if your file has the right number of columns, maybe it has an unescaped tab in a value.
E             + 
E             + : While executing ParallelParsingBlockInputFormat. (CANNOT_PARSE_INPUT_ASSERTION_FAILED) (version 24.3.1.726)

```


</details>

**Comment by Avogar** [comment]
Fixed: https://github.com/ClickHouse/ClickHouse/pull/61322

**Pull request merged**
