### PR TITLE
Fix unexpected accurateCast from string to integer

### LINKED ISSUE #61117: `accurateCast` from String is not accurate.
```
milovidov-desktop :) SELECT accurateCast('1234', 'UInt8')

SELECT accurateCast('1234', 'UInt8')

Query id: 3ecf642d-c03e-4d35-9ccb-ec048ef42408

┌─accurateCast('1234', 'UInt8')─┐
│                           210 │
└───────────────────────────────┘
```

### PR DESCRIPTION
**Pull request by wudidapaopao**
Fix https://github.com/ClickHouse/ClickHouse/issues/61117
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix unexpected accurateCast from string to integer

```
SELECT accurateCast('1234', 'UInt8')
Before:
┌─accurateCast('1234', 'UInt8')─┐
│                           210 │
└───────────────────────────────┘

After:
Received exception from server (version 24.5.1):
Code: 6. DB::Exception: Received from localhost:9000. DB::Exception: Cannot parse string to type UInt8: In scope SELECT accurateCast('1234', 'UInt8'). (CANNOT_PARSE_TEXT)
```

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

<details>
    <summary>CI Settings</summary>

**NOTE:** If your merge the PR with modified CI you **MUST KNOW** what you are doing
**NOTE:** Checked options will be applied if set before CI RunConfig/PrepareRunConfig step

#### Run these jobs only (required builds will be added automatically):
- [ ]  Integration Tests
- [ ]  Stateless tests
- [ ]  Stateful tests
- [ ]  Unit tests
- [ ]  Performance tests
- [ ]  All with aarch64
- [ ]  All with ASAN
- [ ]  All with TSAN
- [ ]  All with Analyzer
- [ ]  All with Azure
- [ ]  Add your option here

#### Deny these jobs:
- [ ]  Fast test
- [ ]  Integration Tests
- [ ]  Stateless tests
- [ ]  Stateful tests
- [ ]  Performance tests
- [ ]  All with ASAN
- [ ]  All with TSAN
- [ ]  All with MSAN
- [ ]  All with UBSAN
- [ ]  All with Coverage
- [ ]  All with Aarch64

#### Extra options:
- [ ]  do not test (only style check)
- [ ]  disable merge-commit (no merge from master before tests)
- [ ]  disable CI cache (job reuse)

#### Only specified batches in multi-batch jobs:
- [ ]  1
- [ ]  2
- [ ]  3
- [ ]  4

</details>

### CODE REVIEW

**Comment by wudidapaopao** [comment]
@antaljanosbenjamin could you take a look when you have a chance? Thanks!
The failed test cases appear to be unrelated to the modifications.

**Review by antaljanosbenjamin — APPROVED** [review]
Looks good, however something is not good with the CI. Give me some time to figure it out.

**Comment by antaljanosbenjamin** [comment]
I merged master as current master looks much better than before.

**Comment by wudidapaopao** [comment]
It's unfortunate that there are still some failed cases, but it seems unrelated to this pr.

**Comment by antaljanosbenjamin** [comment]
- `test_checking_s3_blobs_paranoid/test.py::test_query_is_canceled_with_inf_retries` [flaky](https://play.clickhouse.com/play?user=play#U0VMRUNUIGNoZWNrX3N0YXJ0X3RpbWUsIGNoZWNrX25hbWUsIHRlc3RfbmFtZSwgdGVzdF9zdGF0dXMsIGNoZWNrX3N0YXR1cywgcmVwb3J0X3VybApGUk9NIGNoZWNrcwpXSEVSRSAxCiAgICBBTkQgcHVsbF9yZXF1ZXN0X251bWJlciA9IDAKICAgIEFORCB0ZXN0X3N0YXR1cyAhPSAnU0tJUFBFRCcKICAgIEFORCB0ZXN0X3N0YXR1cyAhPSAnT0snCiAgICBBTkQgY2hlY2tfc3RhdHVzICE9ICdzdWNjZXNzJwogICAgQU5EIHRlc3RfbmFtZSBpbGlrZSAnJXRlc3RfY2hlY2tpbmdfczNfYmxvYnNfcGFyYW5vaWQvdGVzdC5weTo6dGVzdF9xdWVyeV9pc19jYW5jZWxlZF93aXRoX2luZl9yZXRyaWVzJScKT1JERVIgQlkgY2hlY2tfc3RhcnRfdGltZSBkZXNjLCBjaGVja19uYW1lLCB0ZXN0X25hbWU=)
- `test_ssl_cert_authentication/test.py::test_native_wrong_cert` [flaky](https://play.clickhouse.com/play?user=play#U0VMRUNUIGNoZWNrX3N0YXJ0X3RpbWUsIGNoZWNrX25hbWUsIHRlc3RfbmFtZSwgdGVzdF9zdGF0dXMsIGNoZWNrX3N0YXR1cywgcmVwb3J0X3VybApGUk9NIGNoZWNrcwpXSEVSRSAxCiAgICBBTkQgcHVsbF9yZXF1ZXN0X251bWJlciA9IDAKICAgIEFORCB0ZXN0X3N0YXR1cyAhPSAnU0tJUFBFRCcKICAgIEFORCB0ZXN0X3N0YXR1cyAhPSAnT0snCiAgICBBTkQgY2hlY2tfc3RhdHVzICE9ICdzdWNjZXNzJwogICAgQU5EIHRlc3RfbmFtZSBpbGlrZSAnJXRlc3Rfc3NsX2NlcnRfYXV0aGVudGljYXRpb24vdGVzdC5weTo6dGVzdF9uYXRpdmVfd3JvbmdfY2VydCUnCk9SREVSIEJZIGNoZWNrX3N0YXJ0X3RpbWUgZGVzYywgY2hlY2tfbmFtZSwgdGVzdF9uYW1l)
- `Upgrade Check` failed because of unrelated settings
- `Stress test` is fixed by #64770

LGTM, forcing mergeable check.

**Comment by wudidapaopao** [comment]
> * `test_checking_s3_blobs_paranoid/test.py::test_query_is_canceled_with_inf_retries` [flaky](https://play.clickhouse.com/play?user=play#U0VMRUNUIGNoZWNrX3N0YXJ0X3RpbWUsIGNoZWNrX25hbWUsIHRlc3RfbmFtZSwgdGVzdF9zdGF0dXMsIGNoZWNrX3N0YXR1cywgcmVwb3J0X3VybApGUk9NIGNoZWNrcwpXSEVSRSAxCiAgICBBTkQgcHVsbF9yZXF1ZXN0X251bWJlciA9IDAKICAgIEFORCB0ZXN0X3N0YXR1cyAhPSAnU0tJUFBFRCcKICAgIEFORCB0ZXN0X3N0YXR1cyAhPSAnT0snCiAgICBBTkQgY2hlY2tfc3RhdHVzICE9ICdzdWNjZXNzJwogICAgQU5EIHRlc3RfbmFtZSBpbGlrZSAnJXRlc3RfY2hlY2tpbmdfczNfYmxvYnNfcGFyYW5vaWQvdGVzdC5weTo6dGVzdF9xdWVyeV9pc19jYW5jZWxlZF93aXRoX2luZl9yZXRyaWVzJScKT1JERVIgQlkgY2hlY2tfc3RhcnRfdGltZSBkZXNjLCBjaGVja19uYW1lLCB0ZXN0X25hbWU=)
> * `test_ssl_cert_authentication/test.py::test_native_wrong_cert` [flaky](https://play.clickhouse.com/play?user=play#U0VMRUNUIGNoZWNrX3N0YXJ0X3RpbWUsIGNoZWNrX25hbWUsIHRlc3RfbmFtZSwgdGVzdF9zdGF0dXMsIGNoZWNrX3N0YXR1cywgcmVwb3J0X3VybApGUk9NIGNoZWNrcwpXSEVSRSAxCiAgICBBTkQgcHVsbF9yZXF1ZXN0X251bWJlciA9IDAKICAgIEFORCB0ZXN0X3N0YXR1cyAhPSAnU0tJUFBFRCcKICAgIEFORCB0ZXN0X3N0YXR1cyAhPSAnT0snCiAgICBBTkQgY2hlY2tfc3RhdHVzICE9ICdzdWNjZXNzJwogICAgQU5EIHRlc3RfbmFtZSBpbGlrZSAnJXRlc3Rfc3NsX2NlcnRfYXV0aGVudGljYXRpb24vdGVzdC5weTo6dGVzdF9uYXRpdmVfd3JvbmdfY2VydCUnCk9SREVSIEJZIGNoZWNrX3N0YXJ0X3RpbWUgZGVzYywgY2hlY2tfbmFtZSwgdGVzdF9uYW1l)
> * `Upgrade Check` failed because of unrelated settings
> * `Stress test` is fixed by [Fix assert in IObjectStorageIteratorAsync #64770](https://github.com/ClickHouse/ClickHouse/pull/64770)
> 
> LGTM, forcing mergeable check.

@antaljanosbenjamin Thank you very much, this is my first PR contribution.

**Pull request merged**
