### PR TITLE
CLICKHOUSE-2375 Add interserver DNS retries

### LINKED ISSUE #45683: Distributed queries should failover in case of DNS error
```
Code: 198. DB::Exception: Not found address of host: c-caramel-gg-22-server-2.c-caramel-gg-22-server-headless.ns-caramel-gg-22.svc.cluster.local: While executing Remote. (DNS_ERROR) (version 22.13.1.24397 (official build))
```

**Use case**

Kubernetes, the usage of `clusterAllReplicas` table function with `SETTINGS skip_unavailable_shards = 1`

### PR DESCRIPTION
**Pull request by tonickkozlov**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Added retries on interserver DNS errors

This change is useful for clusters that undergo node replacements / topology changes from time to time.

While a node is being replaced/unavailable, its DNS record may disappear from an external DNS resolver. In the meantime other hosts may see the old topology and still try to connect the node using an old DNS name. Without this change it would lead to the client seeing DNS_ERRORs while other replicas of the node being replaced may be healthy. Closes https://github.com/ClickHouse/ClickHouse/issues/45683

### CODE REVIEW

**Comment by tavplubix** [comment]
See https://github.com/ClickHouse/ClickHouse/pull/41292

**Comment by tonickkozlov** [comment]
Makes sense, closing. Thanks for taking a look @tavplubix

**Comment by tavplubix** [comment]
Actually this PR is better than https://github.com/ClickHouse/ClickHouse/pull/41292, because it also adds a test, so I would prefer to close https://github.com/ClickHouse/ClickHouse/pull/41292 instead. The change looks useful, but the problem is that we cannot merge any of these PRs until `test_dns_cache/host_is_drop_from_cache_after_consecutive_failures` flakiness is investigated and fixed.

**Comment by coelho** [comment]
@tavplubix That deserves a separate issue & this should be merged ahead of time. As originally reported, this bug is still important as it completely breaks HA.

This patch is small enough to reason that either:
a) there is another bug that already exists, and this bugfix reveals that.
b) the test itself is flawed.

Unfortunately since my original PR I have not had time yet to look further other than a quick glance.

**Comment by Avogar** [comment]
I tried to investigate the problem with test `test_dns_cache/host_is_drop_from_cache_after_consecutive_failures`. Seems like there is no bug and test is just not good. It fails with the message that only 5 messages were found in log instead of 6, but when I download logs and grep the message, I see all 6. And as I can see from test logs, it couldn't find the first message from the log. I checked test code and found that function `wait_for_log_line` looks only last 100 lines by default. And after changes from this PR the amount of lines after first log message grows (because of more stacktraces of error messages after retries).
So, let's increase the amout of lines to check in `wait_for_log_line` in this PR, merge it and see if this test will be flaky.

**Comment by Slach** [comment]
@crakjie according to
https://github.com/ClickHouse/ClickHouse/commit/e84baa910617001134d10ad9ab0c2dd191fa14e8
image

currently 
this is only in master
so should be available in 23.2

**Pull request merged**
