### PR TITLE
Fix hashing functions with constant `GROUP BY`

### LINKED ISSUE #59779: [Analyzer] Logical error: 'Argument column 'Int32' size 0 doesn't match result column size 1 of function javaHash'
https://s3.amazonaws.com/clickhouse-test-reports/0/3c1c7bb824a65d436c1a0f0c99a16a4bc520da1e/ast_fuzzer__ubsan_.html

```
SELECT
    javaHash(toLowCardinality(materialize(-123)), toInt32(-123)),
    javaHash(toInt64(123)),
    javaHash(toInt64(12345678901))
GROUP BY javaHash(toInt32(-123))
SETTINGS allow_experimental_analyzer = 1
```

```
2024.02.08 21:27:35.829725 [ 540947 ] {3994b8fa-e25d-44ac-aa32-04603b106209} <Fatal> : Logical error: 'Argument column 'Int32' size 0 doesn't match result column size 1 of function javaHash'.
```

Does not trigger without the analyzer (You get `Code: 48. DB::Exception: Java hash is not combineable for multiple arguments. (NOT_IMPLEMENTED)` instead)

### PR DESCRIPTION
**Pull request by antonio2368**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Fix https://github.com/ClickHouse/ClickHouse/issues/59779

I'm really not familiar with this part of code but I can give some context.
The problem is `GROUP BY` which has constant expressions. It will be transformed into constant column with value `1`.
When we have in a query constant `1` we won't add it twice to the DAG AFAIU.
So when we have a query like this:
```
SELECT halfMD5(1, materialize(toLowCardinality(2))) GROUP BY (1, halfMD5(materialize(1))) settings allow_experimental_analyzer=1;
```
The `1` inside `halfMD5` and `GROUP BY 1` will be deduplicated.

`1` should be a constant column inside DAG but we just have `INPUT` because we don't send a column when we analyze `GROUP BY` (we set `nullptr` in `available_columns_after_aggregation`).

This causes problems down the line, e.g. optimizations aren't applied properly.

cc @novikd @KochetovNicolai you will probably know better

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by robot-ch-test-poll1** [comment]
*This is an automated comment for commit 7bd2b15ee61e3ff5c1d2bfb12f4a2e2749de4949 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/60184/7bd2b15ee61e3ff5c1d2bfb12f4a2e2749de4949/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/60184/7bd2b15ee61e3ff5c1d2bfb12f4a2e2749de4949/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Comment by Algunenano** [comment]
See https://github.com/ClickHouse/ClickHouse/pull/60046 and https://github.com/ClickHouse/ClickHouse/pull/59986. 3 fixes already :partying_face:

**Comment by antonio2368** [comment]
Ah it's the same fix but I didn't see it because it didn't reference the issue... :smiling_face_with_tear: 
I'll close the PR

**Comment by yakov-olkhovskiy** [comment]
@antonio2368 but we have a dilemma here - maybe you could review which solution is better:
https://github.com/ClickHouse/ClickHouse/pull/60046#pullrequestreview-1887185334

**Pull request closed without merging**
