### PR TITLE
Add setting `aggregate_functions_null_for_empty`

### LINKED ISSUE #10273: Add setting "aggregate_functions_null_for_empty"
This option will rewrite all aggregate functions in a query, adding `-OrNull` suffix to them.
This must be implemented via query rewrite (similar to `count_distinct_implementation` setting) to get consistent results for distributed queries.

Follow-up for #2509.

### PR DESCRIPTION
**Pull request by ucasfl**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- New Feature

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Add setting `aggregate_functions_null_for_empty`, this option will rewrite all aggregate functions in a query, adding -OrNull suffix to them. fix [10273](https://github.com/ClickHouse/ClickHouse/issues/10273)

Detailed description / Documentation draft:

...

By adding documentation, you'll allow users to try your new feature immediately, not when someone else will have time to document it later. Documentation is necessary for all features that affect user experience in any way. You can add brief documentation draft above, or add documentation right into your patch as Markdown files in [docs](https://github.com/ClickHouse/ClickHouse/tree/master/docs) folder.

If you are doing this for the first time, it's recommended to read the lightweight [Contributing to ClickHouse Documentation](https://github.com/ClickHouse/ClickHouse/tree/master/docs/README.md) guide first.

Information about CI checks: https://clickhouse.tech/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
It leads to 6x performance drop even if the argument is not nullable:

```
milovidov-desktop :) SELECT sum(number) FROM system.numbers

SELECT sum(number)
FROM system.numbers

Query id: 2f21a1b4-c469-4a0b-a8ed-e86efe2edd43

Cancelling query.
Ok.
Query was cancelled.

0 rows in set. Elapsed: 2.906 sec. Processed 8.84 billion rows, 70.74 GB (3.04 billion rows/s., 24.34 GB/s.) 

milovidov-desktop :) SELECT sumOrNull(number) FROM system.numbers

SELECT sumOrNull(number)
FROM system.numbers

Query id: 06dda4aa-9168-41fe-8d2d-63f7857e44fb

Cancelling query.
Ok.
Query was cancelled.

0 rows in set. Elapsed: 4.409 sec. Processed 2.20 billion rows, 17.59 GB (498.66 million rows/s., 3.99 GB/s.)
```

**Comment by alexey-milovidov** [comment]
Please cherry-pick this commit: c7618ea
I reordered the settings and removed some of the obsolete settings.

**Comment by alexey-milovidov** [comment]
It's tricky that the function `count` and `count(DISTINCT ...)` some other functions have to continue to return zero value when `aggregate_functions_null_for_empty` is enabled (if we aim for SQL compatibility), in contrast to countOrNull, uniqExactOrNull, etc...

**Comment by alexey-milovidov** [comment]
It is controlled by `AggregateFunctionProperties`.

**Comment by ucasFL** [comment]
> It's tricky that the function `count` and `count(DISTINCT ...)` and some other functions have to continue to return zero value when `aggregate_functions_null_for_empty` is enabled (if we aim for SQL compatibility), in contrast to countOrNull, uniqExactOrNull, etc...

So, what is the best way to resolve this?

**Comment by alexey-milovidov** [comment]
Look at the function properties in AggregateFunctionFactory and don't rewrite functions that should not return NULL.

**Comment by alexey-milovidov** [comment]
@ucasFL We forgot about one little thing...

For -State and -Merge functions we need to add -OrNull before, not after...
Need to check how it will work.

**Comment by ucasFL** [comment]
> @ucasFL We forgot about one little thing...
> 
> For -State and -Merge functions we need to add -OrNull before, not after...
> Need to check how it will work.

Maybe not only -State and -Merge, but also -If, -MergeState?

**Comment by alexey-milovidov** [comment]
Yes, `-MergeState` definitely.

About `-If` - let's check if the behaviour of -IfOrNull different with -OrNullIf.

**Comment by ucasFL** [comment]
```sql
SELECT sumIfOrNull(1, 0)

Query id: cfeae055-758d-4482-9cda-0ebac2bcca5f

┌─sumIfOrNull(1, 0)─┐
│                 0 │
└───────────────────┘
SELECT sumOrNullIf(1, 0)

Query id: eb9b740c-155e-46e4-9d44-5d67e6d2fb25

┌─sumOrNullIf(1, 0)─┐
│              ᴺᵁᴸᴸ │
└───────────────────┘

```
It's different.

**Comment by ucasFL** [comment]
And there may be multiple combinators in an aggregate function, such as `avgIfState`, `sumStateForEach`.  I think for aggregate functions with combinators, we shoule move -OrNull to the first when rewrite?

**Pull request merged**
