### PR TITLE
Some improvements in stress test

### PR DESCRIPTION
**Pull request by alesapin**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Now we will have a single archive for all stress logs. Also, fix run with database replicated.

### CODE REVIEW

**Comment by alesapin** [comment]
Any stress test run and it's ok to merge.

**Comment by alesapin** [comment]
@Mergifyio update

**Comment by alesapin** [comment]
` Marker check — All checks started `?

**Comment by alexey-milovidov** [comment]
Need to modify at least one another file for CI checks. 

If it will be named `stress.sh` instead of `stress` it will run automatically...

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
Maybe let's merge and then check in master.

**Pull request merged**
