### PR TITLE
Cherry pick #48572 to 22.8: Update CCTZ

### PR DESCRIPTION
**Pull request by robot-ch-test-poll2**
Original pull-request #48572

This pull-request is a first step of an automated backporting.
It contains changes like after calling a local command `git cherry-pick`.
If you intend to continue backporting this changes, then resolve all conflicts if any.
Otherwise, if you do not want to backport them, then just close this pull-request.

The check results does not matter at this step - you can safely ignore them.

### Note

This pull-request will be merged automatically as it reaches the mergeable state, **do not merge it manually**.

### If the PR was closed and then reopened

If it stuck, check #48572 for `pr-backports-created` and delete it if necessary. Manually merging will do nothing, since `pr-backports-created` prevents the original PR #48572 from being processed.

### CODE REVIEW

**Comment by robot-ch-test-poll3** [comment]
Dear @alexey-milovidov, the PR is not updated for 1d0h59m44s. Please, either resolve the conflicts, or close it to finish the backport process of #48572

**Comment by robot-clickhouse-ci-1** [comment]
Dear @alexey-milovidov, the PR is not updated for 1d1h0m0s. Please, either resolve the conflicts, or close it to finish the backport process of #48572

**Comment by robot-ch-test-poll2** [comment]
Dear @alexey-milovidov, the PR is not updated for 1d0h59m38s. Please, either resolve the conflicts, or close it to finish the backport process of #48572

**Comment by robot-clickhouse-ci-2** [comment]
Dear @alexey-milovidov, the PR is not updated for 1d0h0m8s. Please, either resolve the conflicts, or close it to finish the backport process of #48572

**Comment by robot-clickhouse** [comment]
Dear @alexey-milovidov, the PR is not updated for 1d0h59m12s. Please, either resolve the conflicts, or close it to finish the backport process of #48572

**Comment by robot-clickhouse-ci-1** [comment]
Dear @alexey-milovidov, the PR is not updated for 1d0h58m29s. Please, either resolve the conflicts, or close it to finish the backport process of #48572

**Comment by robot-ch-test-poll2** [comment]
Dear @alexey-milovidov, the PR is not updated for 1d0h2m44s. Please, either resolve the conflicts, or close it to finish the backport process of #48572

**Comment by robot-ch-test-poll2** [comment]
Dear @alexey-milovidov, the PR is not updated for 1d0h18m46s. Please, either resolve the conflicts, or close it to finish the backport process of #48572

**Comment by robot-ch-test-poll1** [comment]
Dear @alexey-milovidov, the PR is not updated for 1d0h39m11s. Please, either resolve the conflicts, or close it to finish the backport process of #48572

**Comment by robot-clickhouse** [comment]
Dear @alexey-milovidov, the PR is not updated for 1d1h7m1s. Please, either resolve the conflicts, or close it to finish the backport process of #48572

**Pull request merged**
