### PR TITLE
Add build with GCC

### PR DESCRIPTION
**Pull request by azat**
Changelog category (leave one):
- Not for changelog (changelog entry is not required)

This is just to ensure that build passes, and not for production use.

Cc: @alesapin 
Cc: @alexey-milovidov

### CODE REVIEW

**Comment by azat** [comment]
>[PullRequestCI / BuilderBinGCC (pull_request) Failing after 12m — BuilderBinGCC](https://github.com/ClickHouse/ClickHouse/runs/5507947804?check_suite_focus=true)

Now it shows all the errors that #35123 should address.

**Comment by azat** [comment]
>[PullRequestCI / BuilderBinGCC (pull_request) Successful in 29m — BuilderBinGCC](https://github.com/ClickHouse/ClickHouse/runs/5537851414?check_suite_focus=true)
>[Unit tests (release-gcc, actions) — fail: 0, passed: 10247](https://s3.amazonaws.com/clickhouse-test-reports/35204/c1b75f8d5183eebd09e227bf3b5930038697a80e/unit_tests__release-gcc__actions_.html)

Passed, but gcc was missing in the build report page - fixed.

**Comment by azat** [comment]
>[ClickHouse special build check (actions) — 7/7 builds are OK](https://s3.amazonaws.com/clickhouse-builds/35204/8394ec0d0b23d0bd3f89856d80c3d1acdfc89f89/clickhouse_special_build_check_(actions)/report.html)

Now it contains GCC.

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
@mergifyio update

**Comment by alexey-milovidov** [comment]
It's good that we have this build - it detected some trash that needs to be fixed.

**Comment by azat** [comment]
After some patches had been merged [gcc got SIGSEGV](https://github.com/ClickHouse/ClickHouse/runs/5708849627?check_suite_focus=true):

For example while compiling `src/CMakeFiles/dbms.dir/Interpreters/MySQL/InterpretersMySQLDDLQuery.cpp.o`:

Looks like the stack size was not enough:

```
0x00000000010978f2 in structural_comptypes (t1=0x7fde028c7dc8, t2=0x7fde028d1e70, strict=0) at ../../src/gcc/cp/typeck.c:1274                                                                                                                                                     
1274    ../../src/gcc/cp/typeck.c: No such file or directory.                                                                                                                                                                                                                     
(gdb) bt                                                                                                                                                                                                                                                                          
#0  0x00000000010978f2 in structural_comptypes (t1=0x7fde028c7dc8, t2=0x7fde028d1e70, strict=0) at ../../src/gcc/cp/typeck.c:1274                                                                                                                                                 
#1  0x00000000011c3f9d in comp_template_parms (parms1=<optimized out>, parms2=<optimized out>) at ../../src/gcc/cp/pt.c:3369                                                                                                                                                      
#2  0x0000000001097bd9 in structural_comptypes (t1=0x7fde028c7dc8, t2=0x7fde028d1e70, strict=<optimized out>) at ../../src/gcc/cp/typeck.c:1361                                                                                                                                   
#3  0x00000000011c3f9d in comp_template_parms (parms1=<optimized out>, parms2=<optimized out>) at ../../src/gcc/cp/pt.c:3369                                                                                                                                                      
...
(gdb) bt -10
#1397503 cp_parser_namespace_definition (parser=0x7fde27558da8) at ../../src/gcc/cp/parser.c:20481
#1397504 0x0000000000f838b1 in cp_parser_declaration (parser=0x7fde27558da8, prefix_attrs=<optimized out>) at ../../src/gcc/cp/parser.c:14146
#1397505 0x00000000014790a4 in cp_parser_toplevel_declaration (parser=0x7fde27558da8) at ../../src/gcc/cp/parser.c:14195
#1397506 cp_parser_translation_unit (parser=0x7fde27558da8) at ../../src/gcc/cp/parser.c:4942
#1397507 c_parse_file () at ../../src/gcc/cp/parser.c:45347
#1397508 0x0000000001466c7b in c_common_parse_file () at ../../src/gcc/c-family/c-opts.c:1218
#1397509 0x00000000014596ce in compile_file () at ../../src/gcc/toplev.c:457
#1397510 0x0000000001423429 in do_compile () at ../../src/gcc/toplev.c:2201
#1397511 toplev::main (this=this@entry=0x7ffd1194fdde, argc=<optimized out>, argv=<optimized out>) at ../../src/gcc/toplev.c:2340
#1397512 0x000000000142278c in main (argc=<optimized out>, argv=<optimized out>) at ../../src/gcc/main.c:39
```

**Comment by azat** [comment]
>Looks like the stack size was not enough:

Investigation details are here - https://github.com/ClickHouse/ClickHouse/pull/35204/commits/bf4df5c6bb6d51cc581edac91fac625223c117ab

GCC bug report is here - https://gcc.gnu.org/bugzilla/show_bug.cgi?id=105098

Also here are some fixes for libcxx that will be required for gcc-12 - https://reviews.llvm.org/D122598

**Pull request merged**
