### PR TITLE
Revert "Ignore parse failure of opentelemetry header"

### PR DESCRIPTION
**Pull request by nikitamikhaylov**
Reverts ClickHouse/ClickHouse#32116

### CODE REVIEW

**Comment by FrankChen021** [comment]
@nikitamikhaylov May I know why the PR #32116 was reverted?

**Comment by FrankChen021** [comment]
Could you explain why you reverts the PR? 

I'm going to open more PRs based on that PR. I don't want waste time on addressing any code conflicts.

**Comment by nikitamikhaylov** [comment]
@FrankChen021 No worries, I just some errors in master and thought that I broke something. I will merge it (and you will be the author of the commit)

**Comment by FrankChen021** [comment]
Thanks for the explanation.

**Pull request merged**
