### PR TITLE
Merging query cache.

### PR DESCRIPTION
**Pull request by alexey-milovidov**
Merging #8022 

Thoughts to be resolved:

```
+ DROP QUERY_CACHE -> SYSTEM DROP QUERY CACHE to be consistent with DROP MARK/UNCOMPRESSED/DNS... CACHE

+ <query_cache_min_lifetime>600</query_cache_min_lifetime> - remove

+ query_cache_memory_size -> query_cache_size to be consistent with mark_cache_size

+ CacheBlockInputStream -> BlocksBlockInputStream

Processors

use_experimental_local_query_cache -> highlight that it's used only for IN rhs.
use_experimental_distributed_query_cache -> highlight that it's the cache for results of distributed queries not the "distributed cache"

query_cache_max_size

UInt64 version; - add comments.

+ RENAME TABLE drop cache, rewrite to UUIDs - looks Ok.
+ dropQueryCache check all places

+ QueryResult::operator() - why need that?

getRefTables - does not account for subqueries?
rename method and type

tests/query_cache.cpp -> gtest

with_alias - check usage

virtual UInt64 getVersion() const { return 0; } - missing comments!!!

ReplicatedMergeTree and replication?

+ std::atomic<UInt64> data_version{9}; - extremely weird, typo?

increaseVersion(); on merge should be used only for non-trivial merge operations

change version on alter
```

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
It is mergeable but with current state has limited use - will keep under experimental flags for a while.

**Comment by achimbab** [comment]
@alexey-milovidov 
Hello. 
ClickHouse is a very good database, and I'm using it with a grateful regard.
I am longing for this PR.
My company extended ClickHouse cluster from 30 machines to 150 large machines to speed up our service. 
We expect to serve the user a faster one after the feature is merged.
Could you review this PR?
If any other problems in there, please let me know.
Thank you.

**Comment by achimbab** [comment]
@alexey-milovidov @amosbird @KochetovNicolai 
How are you doing well in this critical environment with COVID-19?
I would appreciate if you could share the status of this PR.

**Comment by alexey-milovidov** [comment]
@achimbab We are doing well, thank you!
This PR was not in high priority. But it's almost ready to merge.

**Comment by alexey-milovidov** [comment]
I have to clarify that I'm still afraid merging it because I'm not sure about the "version" interface for tables. We have to think more...

**Comment by achimbab** [comment]
@alexey-milovidov 
I appreciate your consideration.
Recently I had no time to think about it but I will retry shortly.

**Comment by alexey-milovidov** [comment]
We are going to implement query cache in slightly different way, so it can be enabled for all query results, not only for subqueries. This PR will be closed in favour of future implementation. I expect that it will come in 2021 Q2/Q3.

**Comment by achimbab** [comment]
@alexey-milovidov 
It's a good news to implement more general caching mechanism.
How about a different PR #18465? I want to know whether the PR #18465 can be applied to the ClickHouse or not.
Thank you.

**Pull request closed without merging**
