### PR TITLE
Reduce the number of clone operations during query interpretation

### PR DESCRIPTION
**Pull request by Algunenano**
### Changelog category (leave one):
- Performance Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
- Reduce the number of clone operations during query interpretation

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

References https://github.com/ClickHouse/ClickHouse/issues/39996 too

When running the perf test from #40065 you can see that quite a bit of time goes into copying the tree many times.

For example, in a single run of the query there are 1362 calls to `ASTSelectQuery::clone()` which take quite a bit of time:
```
+    6.12%     0.03%            95  TCPHandler  libclickhouse_parsers.so       [.] DB::ASTSelectQuery::clone                                                                                                                                                
+    5.83%     0.03%           125  TCPHandler  libclickhouse_parsers.so       [.] DB::ASTExpressionList::clone                                                                                                                                             
+    5.76%     0.13%           483  TCPHandler  libclickhouse_parsers.so       [.] DB::IAST::cloneChildren                                                                                                                                                  
+    4.77%     0.17%           624  TCPHandler  libclickhouse_parsers.so       [.] DB::ASTFunction::clone                                                                                                                                                   
+    4.55%     0.02%            68  TCPHandler  libclickhouse_parsers.so       [.] DB::ASTTablesInSelectQuery::clone                                                                                                                                        
+    4.54%     0.01%            37  TCPHandler  libclickhouse_parsers.so       [.] DB::ASTSubquery::clone                                                                                                                                                   
+    4.53%     0.02%            61  TCPHandler  libclickhouse_parsers.so       [.] DB::ASTTablesInSelectQueryElement::clone                                                                                                                                 
+    4.52%     0.01%            54  TCPHandler  libclickhouse_parsers.so       [.] DB::ASTSelectWithUnionQuery::clone                                                                                                                                       
+    4.48%     0.03%            98  TCPHandler  libclickhouse_parsers.so       [.] DB::ASTTableExpression::clone                                                                                                                                            
+    1.33%     0.09%           322  TCPHandler  libclickhouse_parsers.so       [.] DB::ASTIdentifier::clone                                                                                                                                                 
+    0.52%     0.01%            47  TCPHandler  libclickhouse_parsers.so       [.] DB::ASTLiteral::clone                                                                                                                                                    
     0.26%     0.02%            71  TCPHandler  libclickhouse_interpreters.so  [.] DB::ActionsDAG::clone
```

To start removing some of those calls, let's start by keeping a reference to the original query instead of cloning it. That reduces the number of calls to 690 (around half, still a lot):

```
+    3.24%     0.02%            57  TCPHandler  libclickhouse_parsers.so       [.] DB::ASTSelectQuery::clone
+    3.05%     0.02%            78  TCPHandler  libclickhouse_parsers.so       [.] DB::ASTExpressionList::clone
+    3.01%     0.07%           243  TCPHandler  libclickhouse_parsers.so       [.] DB::IAST::cloneChildren
+    2.50%     0.09%           321  TCPHandler  libclickhouse_parsers.so       [.] DB::ASTFunction::clone
+    2.37%     0.02%            54  TCPHandler  libclickhouse_parsers.so       [.] DB::ASTTablesInSelectQuery::clone
+    2.36%     0.01%            32  TCPHandler  libclickhouse_parsers.so       [.] DB::ASTSubquery::clone
+    2.36%     0.02%            57  TCPHandler  libclickhouse_parsers.so       [.] DB::ASTTablesInSelectQueryElement::clone
+    2.35%     0.01%            29  TCPHandler  libclickhouse_parsers.so       [.] DB::ASTSelectWithUnionQuery::clone
+    2.33%     0.02%            58  TCPHandler  libclickhouse_parsers.so       [.] DB::ASTTableExpression::clone
+    0.68%     0.05%           156  TCPHandler  libclickhouse_parsers.so       [.] DB::ASTIdentifier::clone
     0.28%     0.01%            33  TCPHandler  libclickhouse_parsers.so       [.] DB::ASTLiteral::clone
     0.28%     0.02%            72  TCPHandler  libclickhouse_interpreters.so  [.] DB::ActionsDAG::clone
```

In terms of performance it's around 1.06x faster:
* Before: `localhost:9000, queries 200, QPS: 9.378, RPS: 0.000, MiB/s: 0.000, result RPS: 9.378, result MiB/s: 0.003.`
* After: `localhost:9000, queries 200, QPS: 9.928, RPS: 0.000, MiB/s: 0.000, result RPS: 9.928, result MiB/s: 0.003.`

Ideally the copies should only happen when strictly necessary and I expect there should be a shared_ptr<const IAST> and not a const shared_ptr<IAST> to enforce this better, but let's wait until the new analyzer is in place before doing large changes.

### CODE REVIEW

**Comment by nickitat** [comment]
What is in top of perf report? If query slowed down 2 times there should be something more costly

**Comment by Algunenano** [comment]
> What is in top of perf report?

It's part of the output from perf (the linux tool). It says that in the first capture 6.12% of the cpu time was spent on DB::ASTSelectQuery::clone and its children, and only 0.03% on the function itself. In the second time, after the changes, it is only around 3%.

Looking at the test it seems that I missed something and some place is using or editing the AST. Doing these kind of changes without const is painful. Will look into it at some point

**Comment by alexey-milovidov** [comment]
Cloning has been added to avoid modification of the shared state.
Maybe it is still needed.

A better path would be to use `COW` for AST.

**Comment by Algunenano** [comment]
I've been looking at this and will need to investigate a bit more and come up with a better solution. The problem is that we don't keep a reference to the original query (as I was understanding by the `original_query` name :D) but to the original query **after** the CTE has been propagated, so the sets can be reused.

Changing that breaks https://github.com/ClickHouse/ClickHouse/pull/34650

**Comment by Algunenano** [comment]
Considering a different approach, I'm wondering if calling some visitors in every subquery isn't being extremely inefficient for the most part. In this case we are calling `ApplyWithAliasVisitor` and `ApplyWithAliasVisitor` which are global and recursive, but the same thing happens with many other optimizations that happen before execution.

I understand that many of the visitors (all of the ones that don't depend on settings, and maybe some of them that do) could be called just once on the main query only.

@kitaisreal is this something you have considered in the new analyzer? If not I'll explore this further.

**Comment by kitaisreal** [comment]
@Algunenano yes, in new Analyzer each visitor iterate only once. Also a lot of steps are simplified, and optimized. I tested joins recently and for 5 joins current optimizer spend around 300-350ms just analyzing query. In new analyzer it is performed in 50-60 ms. With increased numbers of joins it become even worse.

**Comment by Algunenano** [comment]
That sounds amazing. I'm going to close this PR then since the changes shouldn't be necessary and have a deeper look into the new analyzer.

**Pull request closed without merging**
