### PR TITLE
Upload to S3 compressed self-extracting clickhouse

### LINKED ISSUE #34755: Make `clickhouse` binary a self extracting executable.
**Use case**

1. More quick downloads but without the need of unpacking or installing any separate tools.
2. Include `odbc-bridge` and `library-bridge` in single-binary ClickHouse downloads despite the fact that they are separate binaries.
3. Maybe the size will be ok to always include debug info, even in .deb/.rpm packages.
4. It will also speed up cold start in the cloud.
5. #29378

**Describe the solution you'd like**

Compile a tool that can compress and decompress with ZSTD. It can use the official zstd framing format but not necessarily. It should support compression by blocks of size around 10..100 MiB (to avoid too high memory usage) and checksums. It should not depend on glibc version, and even better if it will be statically linked. Maybe two tools - one for compression and another for decompression.

Post-build rule will compress `clickhouse` (and possibly `clickhouse-odbc-bridge` and `clickhouse-jdbc-bridge`) binary into blob and then include it into the decompressor with `llvm-objcopy` as a custom ELF section (alternatively - maybe we can concatenate it after the decompressor binary).

Decompressor should check the free space in the current directory, decompress the content into temporary file with a similar name (like `clickhouse.tmp`), perform `fsync`, rename the current binary to a file with similar name (like `.compressed`), rename the decompressed binary to the original name, delete the compressed binary and run the decompressed binary with the same arguments.

If `clickhouse-odbc-bridge` and `clickhouse-odbc-bridge` binaries are present, they should be extracted into current directory and `clickhouse install` script should check if they are present.

**Describe alternatives you've considered**

There are existing specialized tools for compressing executables (like UPX). But zstd will do it better.

**Additional context**

A shortcut for `clickhouse install` in the decompressor can be implemented to avoid extra file copies (first into current directory then to the install destination like `/usr/bin`).

It makes sense to parallelize decompression.

### PR DESCRIPTION
**Pull request by yakov-olkhovskiy**
### Changelog category (leave one):
- New Feature

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Downloadable clickhouse executable is compressed self-extracting.

closes #34755

### CODE REVIEW

**Comment by yakov-olkhovskiy** [comment]
@Felixoid @alesapin please review and verify it's correct - I have no means to test it I guess...

**Comment by Felixoid** [comment]
What you changed is only one place, it's used for https://clickhouse.com/docs/en/getting-started/install#from-single-binary

What I feel after the reading the related ticket is that we want to use it in every place instead of `clickhouse` binaries in https://s3.amazonaws.com/clickhouse-builds/38653/12290dd644422becc0581f36a682fcb8e922321a/clickhouse_build_check_(actions)/report.html and https://s3.amazonaws.com/clickhouse-builds/38653/12290dd644422becc0581f36a682fcb8e922321a/clickhouse_special_build_check_(actions)/report.html, rignt?

**Comment by yakov-olkhovskiy** [comment]
@Felixoid yes, seems we want to use it everywhere - the last Alexey's comment:
https://github.com/ClickHouse/ClickHouse/pull/38447#discussion_r911505801
but maybe try it first? I'm afraid to break all deployments at once :)

**Comment by Felixoid** [comment]
It's rather other way around. The place you touched is not covered by ci checks. Better to use the self extracted exe everywhere and see what will break :-j

**Comment by alexey-milovidov** [comment]
Yes, I want to use it everywhere.

I've checked the current state.
> $ wget https://s3.amazonaws.com/clickhouse-builds/38653/12290dd644422becc0581f36a682fcb8e922321a/binary_release/clickhouse
--2022-07-04 04:48:25--  https://s3.amazonaws.com/clickhouse-builds/38653/12290dd644422becc0581f36a682fcb8e922321a/binary_release/clickhouse
Resolving s3.amazonaws.com (s3.amazonaws.com)... 52.217.108.86
Connecting to s3.amazonaws.com (s3.amazonaws.com)|52.217.108.86|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2224692736 (2.1G) [binary/octet-stream]
Saving to: ‘clickhouse.1’

Still 2.1G.

**Comment by yakov-olkhovskiy** [comment]
@Felixoid I'm merging this now - will create other PR for other packages.

**Comment by Felixoid** [comment]
But why? You merged the part that is not covered by CI

**Pull request merged**
