### PR TITLE
Try making Keeper in `DatabaseReplicated` tests more stable

### PR DESCRIPTION
**Pull request by antonio2368**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Seems like Keeper can be unstable in some of the stateless tests using 3-node setup (https://s3.amazonaws.com/clickhouse-test-reports/49732/8f3b3271d3fc8d174b7d5d5e912e9b70c886c96a/stateless_tests__release__databasereplicated__%5B4_4%5D.html)

Because of the strange gaps in communication (network related maybe?) we ended up in state where Keeper1 and Keeper2 both became leaders for short period of time and with that committed a config.

After that, Keeper3 initiated vote each time forcing Keeper1 and Keeper2 to reset their election timers. Vote fails because Keeper3 has less logs than both Keeper1 and Keeper2. Repeat this process 3 times.

A possible solution could be increasing the range for the election timeout (right now it’s 4-5s). If we set it to 2-5s maybe there will be a higher chance “correct” Keeper nodes will get a chance for leader election.

Keeper3:
```
113:2023.06.22 23:08:04.703331 [ 1388 ] {} <Information> RaftInstance: [VOTE INIT] my id 3, my role candidate, term 3, log idx 0, log term 0, priority (target 1 / mine 1)
127:2023.06.22 23:08:08.879667 [ 1394 ] {} <Information> RaftInstance: [VOTE INIT] my id 3, my role candidate, term 4, log idx 0, log term 0, priority (target 1 / mine 1)
141:2023.06.22 23:08:13.227426 [ 1402 ] {} <Information> RaftInstance: [VOTE INIT] my id 3, my role candidate, term 5, log idx 0, log term 0, priority (target 1 / mine 1)
156:2023.06.22 23:08:17.759869 [ 1401 ] {} <Information> RaftInstance: [VOTE INIT] my id 3, my role candidate, term 6, log idx 0, log term 0, priority (target 1 / mine 1)
```
Keeper2:
```
85:2023.06.22 23:07:59.581539 [ 1365 ] {} <Information> RaftInstance: [BECOME FOLLOWER] term 1
116:2023.06.22 23:08:04.833995 [ 1365 ] {} <Information> RaftInstance: [BECOME FOLLOWER] term 3
485:2023.06.22 23:08:09.008621 [ 1374 ] {} <Information> RaftInstance: [BECOME FOLLOWER] term 4
916:2023.06.22 23:08:13.315691 [ 1370 ] {} <Information> RaftInstance: [BECOME FOLLOWER] term 5
922:2023.06.22 23:08:13.315819 [ 1377 ] {} <Information> RaftInstance: election timeout while serving append entries, ignore it.
1093:2023.06.22 23:08:17.888896 [ 1367 ] {} <Information> RaftInstance: [BECOME FOLLOWER] term 6
```

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by robot-ch-test-poll** [comment]
This is an automated comment for commit 81f2d0c60274e9e268db667be97c8c93f47ae315 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/51473/81f2d0c60274e9e268db667be97c8c93f47ae315/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Review by tavplubix — APPROVED** [review]

**Comment by antonio2368** [comment]
Based on `00002_log_and_exception_messages_formatting`, seems like `trace` is too noisy?

**Comment by tavplubix** [comment]
Yes, 80% of all log messages are from nuraft now, it's too much

**Comment by tavplubix** [comment]
Now it's 62%, still too much. But if it's necessary, we can temporarily suppress the check in `00002_log_and_exception_messages_formatting`

**Comment by antonio2368** [comment]
DatabaseReplicated was okay again, I'll just revert back to `information` as I know what the problem is, larger log level was more for future problems but it's way too noisy.

**Pull request merged**
