### PR TITLE
Add alias for today(curdate/current_date) and now(current_timestamp)

### LINKED ISSUE #52101: A compatibility alias `CURRENT_TIMESTAMP`
**Use case**

`SELECT CURRENT_TIMESTAMP()`

**Describe the solution you'd like**

An alias for function `now`, case-insensitive as well.
Add it here: https://clickhouse.com/codebrowser/ClickHouse/src/Functions/now.cpp.html#140

Add `CURRENT_DATE` and `CURDATE` as aliases for `today`.

### PR DESCRIPTION
**Pull request by Lloyd-Pottiger**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Add alias for functions `today` (now available under the `curdate`/`current_date` names) and `now` (`current_timestamp`)

### Documentation entry for user-facing changes

- [x] Documentation is written (mandatory for new features)

close #52101

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by robot-clickhouse** [comment]
This is an automated comment for commit e4cbece6dd7ce2dfbb4f6a57345a6a57d3716aa8 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/52106/e4cbece6dd7ce2dfbb4f6a57345a6a57d3716aa8/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Comment by alexey-milovidov** [comment]
Ok, but we need a test for these aliases - that they all exist, they are case-insensitive, with both upper, lower, and mixed case supported, and the values are equal to the corresponding functions.

**Comment by alexey-milovidov** [comment]
Let's add an exception here: https://s3.amazonaws.com/clickhouse-test-reports/52106/e4cbece6dd7ce2dfbb4f6a57345a6a57d3716aa8/style_check/docs_spelling_output.txt

**Review by alexey-milovidov — APPROVED** [review]

**Comment by Lloyd-Pottiger** [comment]
@alexey-milovidov Seems those failed tests are not related to the changes of this pr 🤔

**Comment by alexey-milovidov** [comment]
Ok, and we have to fix them anyway.

**Comment by Lloyd-Pottiger** [comment]
@alexey-milovidov I think it is able to merge now

**Pull request merged**
