### PR TITLE
Add ability to ignore unknown keys in JSON object for named tuples

### PR DESCRIPTION
**Pull request by azat**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Add ability to ignore unknown keys in JSON object for named tuples (`input_format_json_ignore_unknown_keys_in_named_tuple`)

This can be useful in case your input JSON is complex, while you need only few fields in it.

This behaviour is controlled by the
input_format_json_ignore_unknown_keys_in_named_tuple setting name, that is turned OFF by default.

This will, almost, allow to parse `gharchive` dataset without `jq` (#15323, cc @alexey-milovidov). "almost" because of two things:
- Tuple cannot be `Nullable`, so such keys with Tuple type in ClickHouse cannot be `null` in JSON
- You cannot use `dot.dot` notation to extract columns for `file()` engine, only `tupleElement()` - #24607

But all of this complexity will gone after #36464

Cc: @Avogar

### CODE REVIEW

**Comment by azat** [comment]
Here are some numbers, but note, that this is a not correct comparison (clickhouse does not extract everything like jq, even though it parses everything anyway):

```sh
azat:.../datasets/gharchive$ time pigz -cd ./2023-01-26-10.ndjson.gz | clickhouse-local "${gharchive_settings[@]}" --structure="${gharchive_structure[*]}" -q 'select * from table' > /dev/null

real    0m1.191s
user    0m3.160s
sys     0m0.535s
azat:.../datasets/gharchive$ time pigz -cd ./2023-01-26-10.ndjson.gz | jq > /dev/null

real    0m16.350s
user    0m18.270s
sys     0m0.580s
```

Actually I thought that `jq` will be slower.

**Comment by azat** [comment]
Test failures does not looks related to me:

>Stress test (asan) — Backward compatibility check: Error message in clickhouse-server.log (see bc_check_error_messages.txt)
>Stress test (msan) — Backward compatibility check: Error message in clickhouse-server.log (see bc_check_error_messages.txt)

```
2023.01.27 14:34:04.277647 [ 506942 ] {} <Error> void DB::SystemLog<DB::PartLogElement>::flushImpl(const std::vector<LogElement> &, uint64_t) [LogElement = DB::PartLogElement]: Code: 252. DB::Exception: Too many parts (300 with average size of 11.72 KiB). Merges are processing significantly slower than inserts. (TOO_MANY_PARTS), Stack trace (when copying this message, always include the lines below):
```

>Stress test (ubsan) — Hung check failed


Memory pressure and lots of S3 stuff.

```
2023.01.27 13:39:32.206596 [ 1620 ] {} <Error> void DB::MergeTreeBackgroundExecutor<DB::MergeMutateRuntimeQueue>::routine(DB::TaskRuntimeDataPtr) [Queue = DB::MergeMutateRuntimeQueue]: Code: 241. DB::Exception: Memory limit (total) exceeded: would use 34.37 GiB (attempt to allocate chunk of 1960645 bytes), maximum: 34.29 GiB. OvercommitTracker decision: Memory overcommit isn't used. Waiting time or overcommit denominator are set to zero. (MEMORY_LIMIT_EXCEEDED), Stack trace (when copying this message, always include the lines below):
...
2023.01.27 13:33:28.998055 [ 1629 ] {1a8b3452-767a-4bda-80ed-1a809d088059::202301_126_213_1} <Debug> MergeTreeSequentialSource: Reading 2 marks from part 202301_139_139_0, total 349 rows starting from the beginning of the part
2023.01.27 13:33:28.998184 [ 1621 ] {3705bbe2-2806-48f0-ab6a-23cea22d469c::202301_203_217_1} <Debug> MergeTreeSequentialSource: Reading 2 marks from part 202301_206_206_0, total 121 rows starting from the beginning of the part
2023.01.27 13:33:28.998282 [ 1625 ] {c3aaaecf-1462-447d-9b21-dc868cac4d72::202301_370_382_1} <Debug> MergeTreeSequentialSource: Reading 2 marks from part 202301_381_381_0, total 164 rows starting from the beginning of the part
2023.01.27 13:33:28.998391 [ 1818 ] {} <Test> ReadBufferFromS3: Read S3 object. Bucket: test, Key: test/mwp/osldcchvxexhvzgxygcdsjmujdckm, Version: Latest, Range: 0-145
2023.01.27 13:33:28.998402 [ 1614 ] {c3aaaecf-1462-447d-9b21-dc868cac4d72::202301_321_369_1} <Debug> MergeTreeSequentialSource: Reading 2 marks from part 202301_349_349_0, total 426 rows starting from the beginning of the part
2023.01.27 13:33:28.998441 [ 1627 ] {c3aaaecf-1462-447d-9b21-dc868cac4d72::202301_202_301_1} <Debug> MergeTreeSequentialSource: Reading 2 marks from part 202301_271_271_0, total 25 rows starting from the beginning of the part
2023.01.27 13:33:28.998443 [ 1843 ] {} <Test> ReadBufferFromS3: Read S3 object. Bucket: test, Key: test/zta/najogoxqyalhtbznqjptgzzmhtiyy, Version: Latest, Range: 0-141
2023.01.27 13:33:28.998524 [ 1912 ] {} <Test> ReadBufferFromS3: Read S3 object. Bucket: test, Key: test/ocg/fkcfuvmmqbwaskjjzkwvbyofxbptu, Version: Latest, Range: 0-127
2023.01.27 13:33:28.998598 [ 1926 ] {} <Test> ReadBufferFromS3: Read S3 object. Bucket: test, Key: test/gcy/pawyvitxztjhhwhazoceeqyklupcj, Version: Latest, Range: 0-85
2023.01.27 13:33:28.998701 [ 1817 ] {} <Test> ReadBufferFromS3: Read S3 object. Bucket: test, Key: test/mxn/ngnubjfhdajexwqxybqpdxjbjxzqm, Version: Latest, Range: 0-89
2023.01.27 13:33:28.998743 [ 2041 ] {} <Test> ReadBufferFromS3: Read S3 object. Bucket: test, Key: test/ohx/jfcrsbpbqlrwjnogqbryqihtgebxc, Version: Latest, Range: 0-85
...
2023.01.27 13:40:07.858428 [ 1540 ] {} <Information> Application: Closed connections. But 14 remain. Tip: To increase wait time add to config: <shutdown_wait_unfinished>60</shutdown_wait_unfinished>
2023.01.27 13:40:07.858469 [ 1540 ] {} <Information> Application: Will shutdown forcefully.
2023.01.27 13:40:07.858560 [ 1818 ] {} <Test> ReadBufferFromS3: Read S3 object. Bucket: test, Key: test/kzu/rmucvmkfhxafmyqzqlfeonpummxdi, Version: Latest, Range: 0-130
2023.01.27 13:40:07.858832 [ 2021 ] {} <Test> ReadBufferFromS3: Read S3 object. Bucket: test, Key: test/ojv/qwcttcqgxogqohrfcrmtcpwczdgoc, Version: Latest, Range: 0-139
2023.01.27 13:40:10.236399 [ 1539 ] {} <Information> Application: Child process exited normally with code 0.
```

**Review by Avogar — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
> Tuple cannot be Nullable

Should `input_format_null_as_default` help?

**Comment by azat** [comment]
> Should input_format_null_as_default help?

Not always:

```sql
:) select * from format(JSONEachRow, 'payload Tuple(pull_request Tuple(merged_by Tuple(login Nullable(String))))', '{"payload" : {"pull_request": {"merged_by": null}}}') settings input_format_null_as_default=1

SELECT *
FROM format(JSONEachRow, 'payload Tuple(pull_request Tuple(merged_by Tuple(login Nullable(String))))', '{"payload" : {"pull_request": {"merged_by": null}}}')
SETTINGS input_format_null_as_default = 0

Query id: 9b45ccd3-30e8-4c29-94e6-a86729d277fc


0 rows in set. Elapsed: 0.006 sec.

Received exception:
Code: 117. DB::Exception: Unexpected number of elements in named tuple. Expected no more than 1 (consider enabling input_format_json_ignore_unknown_keys_in_named_tuple setting): (while reading the value of key payload): (at row 1)
: While executing ParallelParsingBlockInputFormat. (INCORRECT_DATA), Stack trace (when copying this message, always include the lines below):
```

But here is a patch - https://github.com/ClickHouse/ClickHouse/pull/46725/files#r1114294316

**Comment by azat** [comment]
>You cannot use dot.dot notation to extract columns for file() engine, only tupleElement() - https://github.com/ClickHouse/ClickHouse/issues/24607

And the second one is resolved with analyzer!

```sql
p620.local :) select payload.pull_request.merged_by.login from format(JSONEachRow, 'payload Tuple(pull_request Tuple(merged_by Tuple(login Nullable(String))))', '{"payload" : {"pull_request": {"merged_by": {"login": "azat"}}}}') settings input_format_json_ignore_unknown_keys_in_named_tuple=1

SELECT payload.pull_request.merged_by.login
FROM format(JSONEachRow, 'payload Tuple(pull_request Tuple(merged_by Tuple(login Nullable(String))))', '{"payload" : {"pull_request": {"merged_by": {"login": "azat"}}}}')
SETTINGS input_format_json_ignore_unknown_keys_in_named_tuple = 1

Query id: bcbf4fcd-00cf-4f08-aca5-03568c9ef149


0 rows in set. Elapsed: 0.564 sec.

Received exception:
Code: 47. DB::Exception: Missing columns: 'payload.pull_request.merged_by.login' while processing query: 'SELECT payload.pull_request.merged_by.login FROM format('JSONEachRow', 'payload Tuple(pull_request Tuple(merged_by Tuple(login Nullable(String))))', '{"payload" : {"pull_request": {"merged_by": {"login": "azat"}}}}') SETTINGS input_format_json_ignore_unknown_keys_in_named_tuple = 1', required columns: 'payload.pull_request.merged_by.login'. (UNKNOWN_IDENTIFIER)

p620.local :) select payload.pull_request.merged_by.login from format(JSONEachRow, 'payload Tuple(pull_request Tuple(merged_by Tuple(login Nullable(String))))', '{"payload" : {"merge_request": {"merged_by": {"login": "azat"}}}}') settings input_format_json_ignore_unknown_keys_in_named_tuple=1, allow_experimental_analyzer=1

SELECT payload.pull_request.merged_by.login
FROM format(JSONEachRow, 'payload Tuple(pull_request Tuple(merged_by Tuple(login Nullable(String))))', '{"payload" : {"merge_request": {"merged_by": {"login": "azat"}}}}')
SETTINGS input_format_json_ignore_unknown_keys_in_named_tuple = 1, allow_experimental_analyzer = 1

Query id: a77f9374-d808-48f3-8f0c-f00d6d39ba8a

┌─payload.pull_request.merged_by.login─┐
│ ᴺᵁᴸᴸ                                 │
└──────────────────────────────────────┘

1 row in set. Elapsed: 0.019 sec.
```

```sh
$ time clickhouse-local --file ./2023-01-26-10.ndjson.gz "${gharchive_settings[@]}" --structure="${gharchive_structure[*]}" -q 'select payload.pull_request.merged_by.login from table' --allow_experimental_analyzer=1 | wc -l
175693

real    0m8.350s
user    0m19.170s
sys     0m0.212s
```

**Comment by azat** [comment]
With `pigz` it is faster, because reading of gzip is always single threaded in ClickHouse

```sh
azat:.../datasets/gharchive {elapsed: 9s}$ time clickhouse-local --file ./2023-01-26-10.ndjson.gz "${gharchive_settings[@]}" --structure="${gharchive_structure[*]}" -q 'select payload.pull_request.merged_by.login from table' --allow_experimental_analyzer=1 | wc -l
175693

real    0m8.423s
user    0m19.963s
sys     0m0.229s
azat:.../datasets/gharchive {elapsed: 8s}$ time pigz -cd ./2023-01-26-10.ndjson.gz  | clickhouse-local "${gharchive_settings[@]}" --structure="${gharchive_structure[*]}" -q 'select payload.pull_request.merged_by.login from table' --allow_experimental_analyzer=1 | wc -l
175693

real    0m6.445s
user    0m19.535s
sys     0m0.612s
```

**Pull request merged**
