### PR TITLE
Fix for DateTime64 monotonicity

### PR DESCRIPTION
**Pull request by zvonand**
Small fix for #27005

### Changelog category (leave one):
- Performance Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix DateTime64 scanning all table without partitioning

### CODE REVIEW

**Comment by zvonand** [comment]
Ping?

**Comment by den-crane** [comment]
I don't see a test ?

**Comment by den-crane** [comment]
You can use `force_primary_key=1` and insert only 1 row in the table.

```sql
CREATE TABLE dt64_monot_test
(
    `date_time` DateTime64(3),
    `id` String
)
ENGINE = MergeTree
PARTITION BY toDate(date_time)
ORDER BY date_time;

insert into dt64_monot_test select toDateTime64('2020-01-01 00:00:00.000',3)+number , '' from numbers(10);

SELECT count()
FROM dt64_monot_test
WHERE toDateTime64(date_time, 3) >= toDateTime64('2020-01-01 00:00:00.000', 3)
SETTINGS force_primary_key = 1

seceived exception from server (version 22.7.2):
Code: 277. DB::Exception: Received from localhost:9000. DB::Exception: Primary key (date_time) is not used and setting 'force_primary_key' is set. (INDEX_NOT_USED)
```

It should pass without exception after your PR.

Also check that you did not break comparison between DateTime64 with different granularity

```sql
SELECT count() FROM dt64_monot_test 
WHERE toDateTime64(date_time,3) >= toDateTime64('2020-01-01 00:00:00.000001',6) settings force_primary_key=1;
┌─count()─┐
│       9 │
└─────────┘


SELECT count() FROM dt64_monot_test 
WHERE toDateTime64(date_time,3) <= toDateTime64('2020-01-01 00:00:00.000001',6) settings force_primary_key=1;
┌─count()─┐
│       1 │
└─────────┘

SELECT count() FROM dt64_monot_test 
WHERE toDateTime64(date_time,3) = toDateTime64('2020-01-01 00:00:00.000000',6) settings force_primary_key=1;
┌─count()─┐
│       1 │
└─────────┘

SELECT count() FROM dt64_monot_test 
WHERE toDateTime64(date_time,6) = toDateTime64('2020-01-01 00:00:00.000000',6) settings force_primary_key=1;
┌─count()─┐
│       1 │
└─────────┘
```

**Comment by den-crane** [comment]
Also check that result is the same for

```sql
SELECT
    '2020-01-01 00:00:00.000' AS a,
    '2020-01-01 00:00:00.000001' AS b,
    b > a AS str,
    toDateTime64(b, 6) > toDateTime64(a, 3) AS datetime64,
    toDateTime64(toDateTime64(b, 6), 3) > toDateTime64(a, 3) AS datetime64_1

Query id: c2220eb4-f7fe-45fa-b0e0-0002c4d90043

┌─a───────────────────────┬─b──────────────────────────┬─str─┬─datetime64─┬─datetime64_1─┐
│ 2020-01-01 00:00:00.000 │ 2020-01-01 00:00:00.000001 │   1 │          1 │            0 │
└─────────────────────────┴────────────────────────────┴─────┴────────────┴──────────────┘
```

**Comment by zvonand** [comment]
@den-crane is this really supposed to work?
> Also check that you did not break comparison between DateTime64 with different granularity
(and the following lines)

They have different precision -- no wonder I am getting an exception:
```sql
SELECT count()
FROM dt64_monot_test
WHERE toDateTime64(date_time, 3) >= toDateTime64('2020-01-01 00:00:00.000001', 6)
SETTINGS force_primary_key = 1

0 rows in set. Elapsed: 0.002 sec. 

Received exception from server (version 22.8.1):
Code: 277. DB::Exception: Received from localhost:9000. DB::Exception: Primary key (date_time) is not used and setting 'force_primary_key' is set. (INDEX_NOT_USED)
```

**Comment by den-crane** [comment]
>is this really supposed to work?

No, it does not.

**Comment by den-crane** [comment]
I wonder why this does not through an error (it cannot / should not use index, but it does not erroring)

```sql
drop table dt64_monot_test_string;
create table dt64_monot_test_string(date_time String, x String) Engine=MergeTree order by  date_time;
insert into dt64_monot_test_string select '2020-01-01 00:00', '' from numbers(1e7);
SELECT count() FROM dt64_monot_test_string WHERE toDateTime64(date_time,3) = '2020-01-01 00:00:00.000000000' settings force_index_by_date=1, force_primary_key=1;

┌─count()─┐
│       0 │
└─────────┘
1 row in set. Elapsed: 0.043 sec. Processed 10.00 million rows, 250.00 MB (234.34 million rows/s., 5.86 GB/s.)
```

**Comment by zvonand** [comment]
> I wonder why this does not throw an error

I don't see why it should

**Comment by den-crane** [comment]
`toDateTime64(<String>)` should not be monotonic and this query does a table fullscan, thus `force_index_by_date=1, force_primary_key=1;` should throw an error.

**Comment by orloffv** [comment]
it's same issue? https://github.com/ClickHouse/ClickHouse/issues/28087

**Comment by den-crane** [comment]
@orloffv it's not the same, they are not related.

This PR makes `toDateTime64(<DateTime64>)` monotonic.
https://github.com/ClickHouse/ClickHouse/issues/28087 needs `toDate(<DateTime64>)` to be monotonic.

**Comment by zvonand** [comment]
@den-crane are you making smth regarding this PR? Saw your PR. What concerns you do have now about this PR?

**Comment by den-crane** [comment]
>What concerns you do have now about this PR?

I don't have concerns. 
My PR is not important, don't worry.

**Comment by den-crane** [comment]
merged in https://github.com/ClickHouse/ClickHouse/pull/40219

**Pull request closed without merging**
