### PR TITLE
Bring back **garbage** dns tests

### LINKED ISSUE #51471: Flaky integration `test_host_regexp_multiple_ptr_records`
see [CIDB](https://play.clickhouse.com/play?user=play#c2VsZWN0IHB1bGxfcmVxdWVzdF9udW1iZXIgYXMgcHIsIGNoZWNrX3N0YXJ0X3RpbWUsIGNoZWNrX25hbWUsIHRlc3RfbmFtZSwgdGVzdF9zdGF0dXMgYXMgc3RhdHVzLCByZXBvcnRfdXJsCmZyb20gY2hlY2tzCndoZXJlIHRvRGF0ZShjaGVja19zdGFydF90aW1lKSA+ICcyMDIzLTA1LTI3JyBhbmQgdGVzdF9uYW1lIGxpa2UgJyV0ZXN0X2hvc3RfcmVnZXhwX211bHRpcGxlX3B0cl9yZWNvcmRzJScgYW5kIHN0YXR1cyBpbiAoJ0ZBSUwnLCAnRVJST1InLCAnRkxBS1knKQpvcmRlciBieSBjaGVja19zdGFydF90aW1lIGRlc2M=)

Sample reports: 
[one](https://s3.amazonaws.com/clickhouse-test-reports/50559/ddd8f6bba36b43339a7e7d45ae4f5181ebdba7a7/integration_tests__release__[3_4].html), [two](https://s3.amazonaws.com/clickhouse-test-reports/0/eb649873b379a29fec5584205558f70641f16bba/integration_tests__release__[3_4].html)

### PR DESCRIPTION
**Pull request by arthurpassos**
### Changelog category (leave one):
- Build/Testing/Packaging Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Three tests were failing / flaky:
1. test_host_regexp_multiple_ptr_records
2. test_host_regexp_multiple_ptr_records_concurrent
3. test_reverse_dns_query

Hard coding coredns version to `1.9.3` (latest version of coredns when these tests were introduced) fixed 1 and 2. The latter was failing because we relied on google dns, but that can fail sometimes. To fix this, I simply setup a DNS server for this test as well. It does not rely on 3rd party stuff anymore.

Closes https://github.com/ClickHouse/ClickHouse/issues/51471

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by arthurpassos** [comment]
@tavplubix @alexey-milovidov

**Review by alexey-milovidov — APPROVED** [review]

**Review by tavplubix — APPROVED** [review]

**Comment by robot-clickhouse-ci-2** [comment]
This is an automated comment for commit 9781a8cee9cb04d18b435bc8c8bef4cf34fd2a09 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/53286/9781a8cee9cb04d18b435bc8c8bef4cf34fd2a09/ci_running.html)
The overall status of the commit is 🔴 failure

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🔴 failure</td></tr>
</table>

**Comment by arthurpassos** [comment]
@tavplubix @alexey-milovidov I assume the failures are from *unrelated garbage*?

**Comment by alexey-milovidov** [comment]
@arthurpassos Sure. There was another "garbage" session_log:https://github.com/ClickHouse/ClickHouse/issues/51760

I've reverted it in a blink: https://github.com/ClickHouse/ClickHouse/pull/53255

But as long as we have some unrelated garbage, pull requests cannot be merged.
It's a requirement - make it 100% clean before merging.

**Comment by alexey-milovidov** [comment]
Also, @tavplubix pointed out that we will remove `test_tlsv1_3` and `test_zookeeper_config`.

**Comment by alexey-milovidov** [comment]
@arthurpassos 

```
E               compose.cli.verbose_proxy.proxy_callable: docker inspect_network <- ('roottesthostregexpmultipleptrrecords_default')
E               compose.network.ensure: Creating network "roottesthostregexpmultipleptrrecords_default" with driver "bridge"
E               compose.cli.verbose_proxy.proxy_callable: docker create_network <- (name='roottesthostregexpmultipleptrrecords_default', driver='bridge', options=None, ipam={'Driver': 'default', 'Config': [{'Subnet': '10.5.0.0/12', 'IPRange': None, 'Gateway': '10.5.1.1', 'AuxiliaryAddresses': None}, {'Subnet': '2001:3984:3989::/64', 'IPRange': None, 'Gateway': '2001:3984:3989::1', 'AuxiliaryAddresses': None}]}, internal=None, enable_ipv6=True, labels={'com.docker.compose.project': 'roottesthostregexpmultipleptrrecords', 'com.docker.compose.network': 'default', 'com.docker.compose.version': '1.29.2'}, attachable=True, check_duplicate=True)
E               compose.cli.errors.log_api_error: invalid network config:
E               invalid subnet 10.5.0.0/12: it should be 10.0.0.0/12
```

**Comment by alexey-milovidov** [comment]
Thank you! However, I really dislike ephemeral failures.

**Comment by qoega** [comment]
Actually it is not ephemeral, but is triggered by docker update, so we will need to fix tests that use dns to upgrade docker

**Comment by arthurpassos** [comment]
> Actually it is not ephemeral, but is triggered by docker update, so we will need to fix tests that use dns to upgrade docker

I don't quite follow. Are you saying that whenever you try to update the docker version, coredns related tests break? And only coredns related?

**Comment by qoega** [comment]
Yes. Here is PR with updated docker version
https://github.com/ClickHouse/ClickHouse/pull/66867

**Comment by arthurpassos** [comment]
> Yes. Here is PR with updated docker version #66867

Hm. We are using a pinned & old version of coredns, maybe upgrading it could do the trick? In any case, the current code does not work with latest version of coredns, so it'll have to be updated. Can you unpin the docker version on the PR and see if it fixes the subnet issue? If it does, I can spend some time on Monday trying to update the test code itself.

**Pull request merged**
