### PR TITLE
add user content-type overriding

### LINKED ISSUE #70399: User-provided HTTP headers in the URL engine should override the default ones, such as Content-Type.
```
$ ch
:) INSERT INTO FUNCTION url('http://localhost:5001/', JSONEachRow, 'x UInt8', headers('Content-Type' = 'upyachka')) SELECT 1
```

```
$ nc -l localhost 5001
POST / HTTP/1.1
Host: localhost
Transfer-Encoding: chunked
Content-Type: application/x-ndjson; charset=UTF-8
Content-Type: upyachka
Connection: Keep-Alive
Keep-Alive: timeout=30, max=1000

8
{"x":1}

0
```

Here you can see that the Content-Type header is duplicated.
This is what you need to fix - the user-provided header should replace the default one.

Please open another pull request.

_Originally posted by @alexey-milovidov in https://github.com/ClickHouse/ClickHouse/issues/65254#issuecomment-2394929986_

### PR DESCRIPTION
**Pull request by ortyomka**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Add ability to override Content-Type by user headers in the URL engine. 

url('http://localhost:5001/', JSONEachRow, 'x UInt8', headers('Content-Type' = 'my-own-type'))

Closes #70399

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Run only fuzzers related jobs (libFuzzer fuzzers, AST fuzzers, etc.)
- [ ]  Exclude: AST fuzzers
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by ortyomka** [comment]
```
$ ch
:) INSERT INTO FUNCTION url('http://localhost:5001/', JSONEachRow, 'x UInt8', headers('Content-Type' = 'upyachka')) SELECT 1
```

```
$nc -l localhost 5001
POST / HTTP/1.1
Host: localhost
Transfer-Encoding: chunked
Content-Type: upyachka
Connection: Keep-Alive
Keep-Alive: timeout=30, max=1000

8
{"x":1}

0

```

I tested it by hand, but I would like to write an autotest. I didn't find tests for url.

**Comment by ortyomka** [comment]
One drawback is that the 'Content-Type' header will be after all custom headers

**Review by alexey-milovidov — CHANGES_REQUESTED** [review]
Needs a test.

**Comment by alexey-milovidov** [comment]
> One drawback is that the 'Content-Type' header will be after all custom headers

This is ok.

**Comment by ortyomka** [comment]
I have added the test
@alexey-milovidov

**Review by alexey-milovidov — APPROVED** [review]

**Comment by robot-ch-test-poll2** [comment]
*This is an automated comment for commit 1deb16a929c20f17ec83fbc8200ae8c5680be211 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/70859/1deb16a929c20f17ec83fbc8200ae8c5680be211/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/fc31ec4404a319607893c8d2012317822f3fe964/docs_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Comment by ortyomka** [comment]
I don't know why, but the test cannot find a container with a mock server.
```
return non-zero code 1: Error response from daemon: No such container: roottesturlcontenttypeoverride-gw1-resolver-1
```

I don't see something special in another tests with mock servers. Could you suggest how to fix it?
@alexey-milovidov

**Comment by alexey-milovidov** [comment]
But there is a problem - this test was disabled, most likely after proven to be unstable.

**Comment by ortyomka** [comment]
Tests passed
@alexey-milovidov

**Review by alexey-milovidov — APPROVED** [review]

**Pull request merged**
