### PR TITLE
Optimize normalize_function_names settings, apply it for create/drop queries

### PR DESCRIPTION
**Pull request by taiyang-li**
Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Currently settings `normalize_function_names` has no affect on the normalization of create/drop query. This PR applies normalize_function_names for create/drop queries.

### CODE REVIEW

**Comment by evillique** [comment]
@Mergifyio update

**Comment by amosbird** [comment]
IIUC this PR might break backward compatibility in a way that tries to fix another backward incompatibility.

**Comment by zhanglistar** [comment]
> IIUC this PR might break backward compatibility in a way that tries to fix another backward incompatibility.

What's your advice? @amosbird

**Comment by taiyang-li** [comment]
This is an embarrasing pr which try to fix an incompatiable issue in another incompatiable way. Maybe it is better to keep current status,  close it now.

**Pull request closed without merging**
