### PR TITLE
Enable Thread Fuzzer in Stress test

### LINKED ISSUE #9816: Why does InsertedRows in system.events decrease?
Hi,
    We are monitoring the InsertedRows in system.events. We find this value decreases sometimes. How and why does it happen? Thanks.

### PR DESCRIPTION
**Pull request by alexey-milovidov**
Changelog category (leave one):
- Build/Testing/Packaging Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Enable Thread Fuzzer in Stress Test. Thread Fuzzer is ClickHouse feature that allows to test more permutations of thread scheduling and discover more potential issues. This closes #9813. This closes #9814. This closes #9515. This closes #9516.

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
@Mergifyio update

**Comment by alexey-milovidov** [comment]
@Mergifyio update

**Comment by alexey-milovidov** [comment]
@Mergifyio update

**Comment by alexey-milovidov** [comment]
@Mergifyio update

**Comment by alexey-milovidov** [comment]
Maybe #27734 will help.

**Comment by alexey-milovidov** [comment]
`Failed to wait RAFT initialization. (RAFT_ERROR)`

**Comment by alesapin** [comment]
Maybe just increase startup timeout.

**Comment by alesapin** [comment]
Still too slow to startup. Looks like NuRaft captures too many mutexes during the initial log commit.

**Comment by alexey-milovidov** [comment]
@Mergifyio update

**Comment by alexey-milovidov** [comment]
@Mergifyio update

**Comment by alexey-milovidov** [comment]
@Mergifyio update

**Comment by alexey-milovidov** [comment]
> Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/u/ucf/ucf_3.0038+nmu1_all.deb  Could not connect to archive.ubuntu.com:80 (2001:67c:1360:8001::23), connection timed out Could not connect to archive.ubuntu.com:80 (2001:67c:1360:8001::24), connection timed out

**Comment by alexey-milovidov** [comment]
@Mergifyio update

**Comment by alexey-milovidov** [comment]
@Mergifyio update

**Comment by alesapin** [comment]
@mergifyio update

**Comment by alesapin** [comment]
I still need to investigate why Keeper startup so slow.

**Comment by alesapin** [comment]
Ok, no related failures. Let's merge.

**Pull request merged**
