### PR TITLE
Revert BackgroundSchedulePool usage in Replicated tables

### PR DESCRIPTION
**Pull request by ztlpn**
Recently I've discovered a bug: after a replicated table is dropped, replication stops working. The reason is that the `BackgroundSchedulePool::TaskInfo::scheduleAfter()` method ignores the `deactivated` flag. I have also found a few other less critical defects:
* Notification of the `wakeup_event` condition variable is not properly synchronized with the predicate checks. This can lead to deadlocks.
* The `deactivated` flag in the `execute()` method is not checked under the mutex.
* Unclear semantics of the `schedule()` method – probably it should just schedule the task for background execution, why does the caller have to wait if the task is currently executing?

Overall the code is pretty complex and it is not immediately clear that it is correct. It also interacts with the most critical and bug-prone part of the code (replication) so probably there are more subtle bugs still lurking in the code. With that in mind I think that potential harm of the BackgroundSchedulePool patch outweighs potential benefits and propose to revert it.

cc @silviucpp

### CODE REVIEW

**Comment by silviucpp** [comment]
Hello @ztlpn,

I started to work on this because I have a scenario where I store 100k+ tables on a single node (a cloud solution)

And at this level clickhouse it's not working properly. there are over 600k threads only on the replication tables. And this threads are not IDLE most of the time as you might believe. They do lot of wake-ups even without any traffic.

I saw great improvement in CPU performance and also debugging (gdb) once I moved to a pool thread. So if you are still interested in this kind of changes I can look over all the bugs you send and try to figure out the problem:

Right now I'm not sure I understand all the issues you are trying to explain:
 
1. what are the steps that makes replication failing ?

2. BackgroundSchedulePool::TaskInfo::scheduleAfter() method ignores the deactivated flag
	
This shouldn't be a problem as time this function never schedules work itself. Just add an event in a queue that's dispatched after x seconds. In case the task was already removed. Once the delayed schedule thread will process this event will call the schedule function which will not do anything. 
	
3. Notification of the wakeup_event condition variable is not properly synchronized with the predicate checks. This can lead to deadlocks.

Do you have any scenario in mind ? because this event it's used only by delayExecutionThreadFunction to return from wait state when  a task is added or not. 
   
4. The deactivated flag in the execute() method is not checked under the mutex.

What mutex are you refering ? all calls inside BackgroundSchedulePool::TaskInfo are protected by std::lock_guard lock(mutex); Can you be more specific ?
   
5. Unclear semantics of the schedule() method – probably it should just schedule the task for background execution, why does the caller have to wait if the task is currently executing? 
   
   Good point - there is no point for caller in waiting for this

**Comment by alexey-milovidov** [comment]
@silviucpp Please don't be afraid.
Let me accept this revert and I will wait for your next PR, where you can add this feature back, with even more clear and understandable code. I appreciate the importance of this feature and I think that it should be merged anyway.

**Comment by silviucpp** [comment]
@alexey-milovidov I don't have any problem with this revert :) Important is to have this feature working :) 

I will appreciate some feedback on the questions I have in order to be able to start working on this again. And also et me know what else you think that we should change in order to make a better and clear code

**Comment by ztlpn** [comment]
Here are some details:

> what are the steps that makes replication failing ?

To reproduce the DROP TABLE bug, just create a single Replicated table and then drop it. During the drop the ReplicatedMergeTreeAlterThread task handle will get deactivated, but then the ZooKeeper watch will fire (because the table metadata node in ZK will be deleted) and the AlterThread task will be scheduled again. But the task will be unable to execute because it is deactivated. Therefore the delayed_thread will get stuck in an infinite loop.

> Do you have any scenario in mind ? because this event it's used only by delayExecutionThreadFunction to return from wait state when a task is added or not.

In the `delayExecutionThreadFunction()` we first check that there are no tasks, then release the mutex, then reaquire it and wait on the condition variable. If task is inserted and the condvar is notified after the mutex is released but before it is reacquired, the thread will get stuck (potentially forever) in the `wait()` call even if there are some tasks ready to be scheduled. I was easily able to produce deadlocks by inserting `sleep()` calls between the two critical sections.

> What mutex are you refering ? all calls inside BackgroundSchedulePool::TaskInfo are protected by std::lock_guard lock(mutex); Can you be more specific ?

Sorry, my mistake - not the `execute()` method, but the `deactivate()` method (line 69). Probably just a small oversight.

Sorry that I chose a pretty radical solution to these problems, but given the history of the code (one deadlock discovered by you and the two above problems discovered by me even before the code is put to any serious use), I deemed it too risky for this code to be deployed to the production installations of all ClickHouse users (yes, we have to think about all of you :)).

I understand that the code solves the real problem and sooner or later we will have to tackle it. But for such a critical part we should strive to make it so simple that there are obviously no bugs, as opposed to just ensuring that there are no obvious bugs (paraphrasing Tony Hoare). As a practical suggestion, I think we should to try to emulate the semantics of [boost::asio::strand](http://www.boost.org/doc/libs/1_66_0/doc/html/boost_asio/reference/io_context__strand.html), or just use it directly.

**Comment by silviucpp** [comment]
@ztlpn  I'll review again all your observations. delayExecutionThreadFunction is more or less inspired from BackgroundProcessingPool::threadFunction where we have more or less same locking logic. 

On a first look I cant spot why there works :)

**Comment by silviucpp** [comment]
@ztlpn I see the difference In backgroundprocessingpool it's used wake_event.wait_for(lock,
                    std::chrono::duration<double>(sleep_seconds
                        + std::uniform_real_distribution<double>(0, sleep_seconds_random_part)(rng)));

and in worst case the task is executed a bit later and won't block forever in case that event is missed.. I can do the same in delayExecutionThreadFunction but not sure if it's the best solution

**Comment by silviucpp** [comment]
@ztlpn The bug you discovered seems a regression from my fix with deadlock and zookeper. Anyway I started working on a fix and also I'll keep track of all observations you did

**Pull request merged**
