### PR TITLE
Support reading subcolumns from file/s3/hdfs/url/azureBlobStorage table functions

### PR DESCRIPTION
**Pull request by Avogar**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Support reading tuple subcolumns from file/s3/hdfs/url/azureBlobStorage table functions

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by robot-ch-test-poll1** [comment]
This is an automated comment for commit a2805f8f449053b655e3f3df741b98cf434d5629 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/51806/a2805f8f449053b655e3f3df741b98cf434d5629/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Comment by robot-ch-test-poll1** [comment]
This is an automated comment for commit a2805f8f449053b655e3f3df741b98cf434d5629 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/51806/a2805f8f449053b655e3f3df741b98cf434d5629/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Review by CurtizJ — APPROVED** [review]

**Comment by CurtizJ** [comment]
Unfortunately one more s3-like storage with copy paste code arrived yesterday :)

```
Aug 02 18:29:25 /build/src/Storages/S3Queue/StorageS3Queue.cpp:190:38: error: no member named 'checkIfFormatSupportsSubcolumns' in 'DB::FormatFactory'; did you mean 'checkIfFormatSupportsSubsetOfColumns'?
Aug 02 18:29:25     return FormatFactory::instance().checkIfFormatSupportsSubcolumns(configuration.format);
```

**Comment by tavplubix** [comment]
Looks like the changelog entry should have been "Backward Incompatible Change": https://github.com/ClickHouse/ClickHouse/issues/54792

**Comment by Avogar** [comment]
Hmm, but I moved these settings to `OBSOLETE_SETTINGS` section, so it should still recignise these settings. Or I misunderstood the usage of `OBSOLETE_SETTINGS`. Need to check

**Comment by Avogar** [comment]
Interesting:
```
avogar-dev :) set input_format_parquet_import_nested=1

SET input_format_parquet_import_nested = 1

Query id: afa0bf59-d04f-40ec-8908-2399e93dcdcb

Ok.

0 rows in set. Elapsed: 0.001 sec.

avogar-dev :) create table test (x UInt64) engine=File(Parquet) settings input_format_parquet_import_nested=1

CREATE TABLE test
(
    `x` UInt64
)
ENGINE = File(Parquet)
SETTINGS input_format_parquet_import_nested = 1

Query id: e1f59beb-ccef-4940-807e-36f22a656a03


0 rows in set. Elapsed: 0.003 sec.

Received exception:
Code: 115. DB::Exception: Unknown setting input_format_parquet_import_nested. (UNKNOWN_SETTING)

```

**Comment by taiyang-li** [comment]
@Avogar Why not pass subcolumns as header directly for columnar formats like ORC/Parquet to utilize possible subcolumn pruning. 

For example, if orc file schema is `a Tuple(x String, y Int64)`,  and we want to read `a.y` from corresponding file engine. Current implementation will pass `a` as header for `NativeORCBlockInputFormat`, which is obviously waste of IO for we do not need to read data of `a.x` in orc file.

**Comment by Avogar** [comment]
> Why not pass subcolumns as header directly for columnar formats like ORC/Parquet to utilize possible subcolumn pruning.

No reason, I just didn't implemented it. Will be good to do it

**Pull request merged**
