### PR TITLE
Add ability to set Distributed directory monitor settings via CREATE TABLE 

### PR DESCRIPTION
**Pull request by azat**
Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Add ability to set Distributed directory monitor settings via CREATE TABLE (i.e. `CREATE TABLE dist (key Int) Engine=Distributed(cluster, db, table) SETTINGS monitor_batch_inserts=1` and similar)

### CODE REVIEW

**Comment by nikitamikhaylov** [comment]
@Azat Please, take a look at `test_replicated_mutations/test.py::test_mutations` test failure.

**Comment by nikitamikhaylov** [comment]
@Mergifyio update

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
Stress test: #26393

**Comment by azat** [comment]
>@azat Please, take a look at test_replicated_mutations/test.py::test_mutations test failure.

#26461

**Pull request merged**
