### PR TITLE
Forward profile events to client

### LINKED ISSUE #26177: Forward profile events to client
Server should send to the client the data in form of collections of 
`host_name, thread_id, type, name, value` records.
type is either `increment` or `gauge`.

This data contains info from ProfileEvents (in form of increments) and from MemoryTracker (in form of gauge).
The data is sent at some intervals similarly to the `Progress` packets.

New type of packet will be introduced to send this data and it will be sent only to supporting clients (by checking the client version).

In distributed query processing, every server sends data about itself and also forwards all already received data from other servers. The server does not sum increments but only sends (forwards) them to the client. It also does not sum data neither by hosts or by threads. It is responsibility of the final client application (clickhouse-client or similar) to interpret and possibly sum increments. The gauges and increments are sent if they are non-zero.

The data will be used for the following purposes:
- display some metrics in clickhouse-client in realtime (e.g. total number of CPU cores participated in query processing will look cool and help for users of a cluster to maintain awareness of the vast amount of computing resources);
- extend quotas to allow arbitrary metrics to limit query complexity (imagine you want to limit the amount of page faults in 5 minutes interval for some user - not a practical use case but you've got the idea);
- a building block for #8449.

Note that all these data is already available in the `query_log` and `query_thread_log`.

**Additional notes**

Plain binary format will be used in native protocol for this data - similar to other packets in the protocol.

### PR DESCRIPTION
**Pull request by novikd**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- New Feature

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Send profile events from server to client. New packet type `ProfileEvents` was introduced. Closes #26177.

### CODE REVIEW

**Comment by nikitamikhaylov** [comment]
What will I see in case of distributed queries?

**Comment by alexey-milovidov** [comment]
This is how it's supposed to work, I did not read the PR though :)

**Comment by novikd** [comment]
All profile events are supposed to be forwarded to the client (You can see that in `RemoteQueryExecutor`). The client handles all the data. After this change it will compute number of threads, cores and memory used on all the hosts.

**Review by nikitamikhaylov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
The whole implementation is wrong.

`increment` values should send increments, not accumulated values.

**Pull request merged**
