### PR TITLE
Test differences between using materialize_ttl_recalculate_only=1/0

### PR DESCRIPTION
**Pull request by jrdi**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Changing 02129_add_column_add_ttl test to show the differences between using `materialize_ttl_recalculate_only=1/0`. AFAICS, the current test was not testing any difference in particular.

### CODE REVIEW

**Comment by den-crane** [comment]
I doubt that it's possible to test the differences between using materialize_ttl_recalculate_only=1/0

**Comment by jrdi** [comment]
> I doubt that it's possible to test the differences between using materialize_ttl_recalculate_only=1/0

I tested the approach locally, and it's working but I'm afraid (I guess for the same reasons than you) that the test could be a bit flaky.

Leaving that aside, do you think the current test (before my changes) was testing something valuable?

**Comment by den-crane** [comment]
Probably the author tried to test that nothing is changed.

Yes, I think your variant is better but I think it will be flaky.

I just tried to use

```sql
system stop ttl merges ttl_test_02129;
...
select name, active, delete_ttl_info_min, delete_ttl_info_max, rows from system.parts where table = 'ttl_test_02129' and database = currentDatabase() order by name;
```

no luck, I don't see how to make it less flaky.


https://github.com/ClickHouse/ClickHouse/issues/43376 TTL merge starts right after the `alter table  ttl_test_02129 modify TTL` (for a table with materialize_ttl_recalculate_only = 1)

**Comment by jrdi** [comment]
Stopping ttl merges is a good idea, after adding it I can't make the test to fail, so probably is not flake anymore. Did you manage to make it fail?

**Comment by den-crane** [comment]
```sql

cat a.sql
drop table if exists ttl_test_02129;

create table ttl_test_02129(a Int64, b String, d Date)
Engine=MergeTree partition by d order by a
settings min_bytes_for_wide_part = 0, min_rows_for_wide_part = 0, materialize_ttl_recalculate_only = 1;

insert into ttl_test_02129 select number, '', '2021-01-01' from numbers(10);
alter table ttl_test_02129 add column c Int64 settings mutations_sync=2;

insert into ttl_test_02129 select number, '', '2021-01-01', 1 from numbers(10);

alter table  ttl_test_02129 modify TTL (d + INTERVAL 1 MONTH) settings mutations_sync=2;

select name, active, delete_ttl_info_min, delete_ttl_info_max, rows from system.parts where table = 'ttl_test_02129' and database = currentDatabase() order by name;

 clickhouse-client -mn  < a.sql
┌─name─────────────┬─active─┬─delete_ttl_info_min─┬─delete_ttl_info_max─┬─rows─┐
│ 20210101_1_1_0   │      0 │ 1970-01-01 00:00:00 │ 1970-01-01 00:00:00 │   10 │
│ 20210101_1_1_0_3 │      1 │ 2021-02-01 00:00:00 │ 2021-02-01 00:00:00 │   10 │
│ 20210101_2_2_0   │      0 │ 1970-01-01 00:00:00 │ 1970-01-01 00:00:00 │   10 │
│ 20210101_2_2_0_3 │      1 │ 2021-02-01 00:00:00 │ 2021-02-01 00:00:00 │   10 │
└──────────────────┴────────┴─────────────────────┴─────────────────────┴──────┘
```

**Comment by jrdi** [comment]
Mind, the `WHERE` condition in the TTL clause. It's not a matter of stopping the merges or not but the conditional TTL.

```
❯ cat a.sql
drop table if exists ttl_test_02129;

create table ttl_test_02129(a Int64, b String, d Date)
Engine=MergeTree partition by d order by a
settings min_bytes_for_wide_part = 0, min_rows_for_wide_part = 0, materialize_ttl_recalculate_only = 1;

insert into ttl_test_02129 select number, '', '2021-01-01' from numbers(10);
alter table ttl_test_02129 add column c Int64 settings mutations_sync=2;

insert into ttl_test_02129 select number, '', '2021-01-01', 1 from numbers(10);

alter table  ttl_test_02129 modify TTL (d + INTERVAL 1 MONTH) WHERE c=1 settings mutations_sync=2;

select name, active, delete_ttl_info_min, delete_ttl_info_max, rows from system.parts where table = 'ttl_test_02129' and database = currentDatabase() order by name FORMAT PrettyCompact;
❯ cat a.sql | ./master/clickhouse client -h clickhouse-01 -mn
┌─name─────────────┬─active─┬─delete_ttl_info_min─┬─delete_ttl_info_max─┬─rows─┐
│ 20210101_1_1_0   │      0 │ 1970-01-01 00:00:00 │ 1970-01-01 00:00:00 │   10 │
│ 20210101_1_1_0_3 │      1 │ 1970-01-01 00:00:00 │ 1970-01-01 00:00:00 │   10 │
│ 20210101_2_2_0   │      0 │ 1970-01-01 00:00:00 │ 1970-01-01 00:00:00 │   10 │
│ 20210101_2_2_0_3 │      1 │ 1970-01-01 00:00:00 │ 1970-01-01 00:00:00 │   10 │
└──────────────────┴────────┴─────────────────────┴─────────────────────┴──────┘
```

Nevertheless, not matter if the `delete_ttl_info_min/max`, I think the current approach it's OK, and will work to test what we are willing to verify here.

**Review by den-crane — APPROVED** [review]

**Comment by jrdi** [comment]
Just updated from master to keep the branch updated. @den-crane do you think this can get merged?

**Comment by den-crane** [comment]
Yes, it can be/should be merged. 
But it can be merged by developers.
I can only approve it (and I already did).

**Review by vdimir — APPROVED** [review]

**Pull request merged**
