### PR TITLE
Fix Attaching a table with non-existent ZK path does not increase the ReadonlyReplica metric

### LINKED ISSUE #16045: Attaching a table with non-existent ZK path does not increase the ReadonlyReplica metric
```
ATTACH TABLE test_no_zk
(
    `i` Int8,
    `d` Date
)
ENGINE = ReplicatedMergeTree('no_zk', 'replica')
ORDER BY tuple()

Ok.

SHOW CREATE TABLE test_no_zk

┌─statement──────────────────────────────────┐
│ CREATE TABLE default.test_no_zk
(
    `i` Int8,
    `d` Date
)
ENGINE = ReplicatedMergeTree('no_zk', 'replica')
ORDER BY tuple()
SETTINGS index_granularity = 8192
└─────────────────────────────────────────────┘

INSERT INTO test_no_zk VALUES (1, today())

Received exception from server (version 20.9.3):
Code: 242. DB::Exception: Received from localhost:9000. DB::Exception: Table is in readonly mode (zookeeper path: /no_zk).

SELECT
    metric,
    value
FROM system.metrics
WHERE metric = 'ReadonlyReplica'

┌─metric──────────┬─value─┐
│ ReadonlyReplica │     0 │
└─────────────────┴───────┘
```

### PR DESCRIPTION
**Pull request by wzb5212**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix Attaching a table with non-existent ZK path does not increase the ReadonlyReplica metric, may be fix https://github.com/ClickHouse/ClickHouse/issues/16045

```
ATTACH TABLE test_no_zk UUID 'a50b7933-59b2-49ce-8db6-59da3c9b4413'
(
    `i` Int8,
    `d` Date
)
ENGINE = ReplicatedMergeTree('no_zk', 'replica')
ORDER BY tuple()

0 rows in set. Elapsed: 0.007 sec.

Row 1:
──────
database:                    test
table:                       test_no_zk
engine:                      ReplicatedMergeTree
is_leader:                   0
can_become_leader:           1
is_readonly:                 1
is_session_expired:          0
future_parts:                0
parts_to_check:              0
zookeeper_path:              /no_zk
replica_name:                replica
replica_path:                /no_zk/replicas/replica
columns_version:             -1
queue_size:                  0
inserts_in_queue:            0
merges_in_queue:             0
part_mutations_in_queue:     0
queue_oldest_time:           1970-01-01 08:00:00
inserts_oldest_time:         1970-01-01 08:00:00
merges_oldest_time:          1970-01-01 08:00:00
part_mutations_oldest_time:  1970-01-01 08:00:00
oldest_part_to_get:
oldest_part_to_merge_to:
oldest_part_to_mutate_to:
log_max_index:               0
log_pointer:                 0
last_queue_update:           1970-01-01 08:00:00
absolute_delay:              1681923781
total_replicas:              0
active_replicas:             0
lost_part_count:             0
last_queue_update_exception:
zookeeper_exception:         Code: 999. Coordination::Exception: /no_zk/log (No node). (KEEPER_EXCEPTION) (version 23.4.1.1)
replica_is_active:           {}

1 row in set. Elapsed: 0.006 sec.

SELECT *
FROM system.metrics
WHERE metric = 'ReadonlyReplica'

Query id: ff118b33-1835-49e9-8d23-aff67234e944

┌─metric──────────┬─value─┬─description────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ ReadonlyReplica │     1 │ Number of Replicated tables that are currently in readonly state due to re-initialization after ZooKeeper session loss or due to startup without ZooKeeper configured. │
└─────────────────┴───────┴────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
```

### CODE REVIEW

**Comment by den-crane** [comment]
please add a test

**Comment by wzb5212** [comment]
> please add a test

I added an integration test, please take a look.

**Comment by wzb5212** [comment]
@den-crane why check black failed? please take a look.

**Comment by wzb5212** [comment]
@den-crane some ci test failed , please take a look.

**Review by tavplubix — APPROVED** [review]

**Comment by tavplubix** [comment]
> some ci test failed , please take a look.

You can take a look yourself. There's a "Details" link for each failed check, it opens a report with a lost of failed tests and links to relevant logs. Also you can use our public CI database to check if some test is flaky/broken in master ([example](https://play.clickhouse.com/play?user=play#CldJVEgKICAgICcwMTY3Nl9jbGlja2hvdXNlX2NsaWVudF9hdXRvY29tcGxldGUnIEFTIG5hbWVfc3Vic3RyLAogICAgOTAgQVMgaW50ZXJ2YWxfZGF5cywKICAgICgnU3RhdGVsZXNzIHRlc3RzIChhc2FuKScsICdTdGF0ZWxlc3MgdGVzdHMgKGFkZHJlc3MpJywgJ1N0YXRlbGVzcyB0ZXN0cyAoYWRkcmVzcywgYWN0aW9ucyknKSBBUyBiYWNrcG9ydF9hbmRfcmVsZWFzZV9zcGVjaWZpY19jaGVja3MKU0VMRUNUCiAgICB0b1N0YXJ0T2ZEYXkoY2hlY2tfc3RhcnRfdGltZSkgQVMgZCwKICAgIGNvdW50KCksCiAgICBncm91cFVuaXFBcnJheShwdWxsX3JlcXVlc3RfbnVtYmVyKSBBUyBwcnMsCiAgICBhbnkocmVwb3J0X3VybCkKRlJPTSBjaGVja3MKV0hFUkUgKChub3coKSAtIHRvSW50ZXJ2YWxEYXkoaW50ZXJ2YWxfZGF5cykpIDw9IGNoZWNrX3N0YXJ0X3RpbWUpIEFORCAocHVsbF9yZXF1ZXN0X251bWJlciBOT1QgSU4gKAogICAgU0VMRUNUIHB1bGxfcmVxdWVzdF9udW1iZXIgQVMgcHJuCiAgICBGUk9NIGNoZWNrcwogICAgV0hFUkUgKHBybiAhPSAwKSBBTkQgKChub3coKSAtIHRvSW50ZXJ2YWxEYXkoaW50ZXJ2YWxfZGF5cykpIDw9IGNoZWNrX3N0YXJ0X3RpbWUpIEFORCAoY2hlY2tfbmFtZSBJTiAoYmFja3BvcnRfYW5kX3JlbGVhc2Vfc3BlY2lmaWNfY2hlY2tzKSkKKSkgQU5EIChwb3NpdGlvbih0ZXN0X25hbWUsIG5hbWVfc3Vic3RyKSA+IDApIEFORCAodGVzdF9zdGF0dXMgSU4gKCdGQUlMJywgJ0VSUk9SJywgJ0ZMQUtZJykpCkdST1VQIEJZIGQKT1JERVIgQlkgZCBERVNDCg==)). But these failures are not related to your changes, so it's okay.

Integration tests (asan) [3/6] - `test_backup_restore_on_cluster` is flaky - https://github.com/ClickHouse/ClickHouse/issues/45486
Stateless tests (release, analyzer) - it's a new check with new analyzer, and it's broken in master
Stateless tests (ubsan) [2/2] - `01676_clickhouse_client_autocomplete` is flaky

**Comment by wzb5212** [comment]
> > some ci test failed , please take a look.
> 
> You can take a look yourself. There's a "Details" link for each failed check, it opens a report with a lost of failed tests and links to relevant logs. Also you can use our public CI database to check if some test is flaky/broken in master ([example](https://play.clickhouse.com/play?user=play#CldJVEgKICAgICcwMTY3Nl9jbGlja2hvdXNlX2NsaWVudF9hdXRvY29tcGxldGUnIEFTIG5hbWVfc3Vic3RyLAogICAgOTAgQVMgaW50ZXJ2YWxfZGF5cywKICAgICgnU3RhdGVsZXNzIHRlc3RzIChhc2FuKScsICdTdGF0ZWxlc3MgdGVzdHMgKGFkZHJlc3MpJywgJ1N0YXRlbGVzcyB0ZXN0cyAoYWRkcmVzcywgYWN0aW9ucyknKSBBUyBiYWNrcG9ydF9hbmRfcmVsZWFzZV9zcGVjaWZpY19jaGVja3MKU0VMRUNUCiAgICB0b1N0YXJ0T2ZEYXkoY2hlY2tfc3RhcnRfdGltZSkgQVMgZCwKICAgIGNvdW50KCksCiAgICBncm91cFVuaXFBcnJheShwdWxsX3JlcXVlc3RfbnVtYmVyKSBBUyBwcnMsCiAgICBhbnkocmVwb3J0X3VybCkKRlJPTSBjaGVja3MKV0hFUkUgKChub3coKSAtIHRvSW50ZXJ2YWxEYXkoaW50ZXJ2YWxfZGF5cykpIDw9IGNoZWNrX3N0YXJ0X3RpbWUpIEFORCAocHVsbF9yZXF1ZXN0X251bWJlciBOT1QgSU4gKAogICAgU0VMRUNUIHB1bGxfcmVxdWVzdF9udW1iZXIgQVMgcHJuCiAgICBGUk9NIGNoZWNrcwogICAgV0hFUkUgKHBybiAhPSAwKSBBTkQgKChub3coKSAtIHRvSW50ZXJ2YWxEYXkoaW50ZXJ2YWxfZGF5cykpIDw9IGNoZWNrX3N0YXJ0X3RpbWUpIEFORCAoY2hlY2tfbmFtZSBJTiAoYmFja3BvcnRfYW5kX3JlbGVhc2Vfc3BlY2lmaWNfY2hlY2tzKSkKKSkgQU5EIChwb3NpdGlvbih0ZXN0X25hbWUsIG5hbWVfc3Vic3RyKSA+IDApIEFORCAodGVzdF9zdGF0dXMgSU4gKCdGQUlMJywgJ0VSUk9SJywgJ0ZMQUtZJykpCkdST1VQIEJZIGQKT1JERVIgQlkgZCBERVNDCg==)). But these failures are not related to your changes, so it's okay.
> 
> Integration tests (asan) [3/6] - `test_backup_restore_on_cluster` is flaky - #45486 Stateless tests (release, analyzer) - it's a new check with new analyzer, and it's broken in master Stateless tests (ubsan) [2/2] - `01676_clickhouse_client_autocomplete` is flaky

thanks.

**Pull request merged**
