### PR TITLE
Prevent conversion to Replicated if zookeeper path already exists

### PR DESCRIPTION
**Pull request by kirillgarbar**
Currently it is possible to convert MergeTree to replicated if table's path in zookeeper already exist. The conversion is not intended to add replicas to existing tables, so this may cause a lot of troubles. It is also possible to create two replicas with the exact same path like here https://github.com/ClickHouse/ClickHouse/issues/62905

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
It is forbidden to convert MergeTree to replicated if the zookeeper path for this table already exists

### CODE REVIEW

**Comment by robot-ch-test-poll3** [comment]
*This is an automated comment for commit 0ce90f4ef44a8c3f51e3bb57e810c5bef6e1f492 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/63670/0ce90f4ef44a8c3f51e3bb57e810c5bef6e1f492/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

**Review by serxa — APPROVED** [review]

**Comment by serxa** [comment]
Failed tests are related, PTAL

**Review by serxa — APPROVED** [review]

**Comment by tavplubix** [comment]
@kirillgarbar, @serxa, the new test is flaky: https://s3.amazonaws.com/clickhouse-test-reports/0/afc316b779890002dae82dc4b6d930da3683d55e/integration_tests__tsan__[1_6].html

**Comment by serxa** [comment]
Ouch, my bad, I merged it too early. Let's revert and resubmit please @kirillgarbar

**Comment by serxa** [comment]
I'm not sure what exactly went wrong in that test, but I see in log of ch2 node during server shutdown:
```
_instances_0/ch2/logs/clickhouse-server.log
586:2024.05.21 13:10:57.036820 [ 589 ] {} <Debug> MergeTreeBackgroundExecutor: Code: 236. DB::Exception: Storage is about to be deleted. Done active task as if it was aborted. (ABORTED)
```
And a crash on another node after that:
```
_instances_zk_path_0/ch1/logs/clickhouse-server.log
212:2024.05.21 13:11:19.475342 [ 1439 ] {} <Fatal> : Logical error: 'Found existing ZooKeeper path /clickhouse/'/modify_engine_zk_path/already_exists_1/1d501504-917e-4273-bac3-ad73c1a098b8 while trying to convert table `modify_engine_zk_path.already_exists_1` to replicated. Table will not be converted.'.
214:2024.05.21 13:11:19.475996 [ 1443 ] {} <Fatal> BaseDaemon: ########## Short fault info ############
215:2024.05.21 13:11:19.476117 [ 1443 ] {} <Fatal> BaseDaemon: (version 24.5.1.1 (official build), build id: AB9C611C4548E350E1B1A6BF27F2AE83D87B246E, git hash: afc316b779890002dae82dc4b6d930da3683d55e) (from thread 1439) Received signal 6
216:2024.05.21 13:11:19.476198 [ 1443 ] {} <Fatal> BaseDaemon: Signal description: Aborted
217:2024.05.21 13:11:19.476235 [ 1443 ] {} <Fatal> BaseDaemon:
218:2024.05.21 13:11:19.476322 [ 1443 ] {} <Fatal> BaseDaemon: Stack trace: 0x000055724dc326fd 0x000055724df5ea9b 0x00005572462008f6 0x0000557246200e16 0x00007f89c1dfd520 0x00007f89c1e519fd 0x00007f89c1dfd476 0x00007f89c1de37f3 0x00005572461ff4ff 0x000055724dbf49e5 0x000055724dbf56e4 0x00005572462807c0 0x0000557247b611e6 0x00005572553f0427 0x00005572553fa0c4 0x00005572553d1264 0x000055724dce143c 0x000055724dce5d43 0x000055724dce5c82 0x000055724dcdd604 0x000055724dce3b32 0x00005572461f8f2f 0x00007f89c1e4fac3 0x00007f89c1ee1850
219:2024.05.21 13:11:19.476404 [ 1443 ] {} <Fatal> BaseDaemon: ########################################
220:2024.05.21 13:11:19.476486 [ 1443 ] {} <Fatal> BaseDaemon: (version 24.5.1.1 (official build), build id: AB9C611C4548E350E1B1A6BF27F2AE83D87B246E, git hash: afc316b779890002dae82dc4b6d930da3683d55e) (from thread 1439) (no query) Received signal Aborted (6)
221:2024.05.21 13:11:19.476545 [ 1443 ] {} <Fatal> BaseDaemon:
222:2024.05.21 13:11:19.476575 [ 1443 ] {} <Fatal> BaseDaemon: Stack trace: 0x000055724dc326fd 0x000055724df5ea9b 0x00005572462008f6 0x0000557246200e16 0x00007f89c1dfd520 0x00007f89c1e519fd 0x00007f89c1dfd476 0x00007f89c1de37f3 0x00005572461ff4ff 0x000055724dbf49e5 0x000055724dbf56e4 0x00005572462807c0 0x0000557247b611e6 0x00005572553f0427 0x00005572553fa0c4 0x00005572553d1264 0x000055724dce143c 0x000055724dce5d43 0x000055724dce5c82 0x000055724dcdd604 0x000055724dce3b32 0x00005572461f8f2f 0x00007f89c1e4fac3 0x00007f89c1ee1850
223:2024.05.21 13:11:19.571998 [ 1443 ] {} <Fatal> BaseDaemon: 0.0. inlined from ./build_docker/./src/Common/StackTrace.cpp:349: StackTrace::tryCapture()
224:2024.05.21 13:11:19.572113 [ 1443 ] {} <Fatal> BaseDaemon: 0. ./build_docker/./src/Common/StackTrace.cpp:318: StackTrace::StackTrace(ucontext_t const&) @ 0x000000000ebc06fd
225:2024.05.21 13:11:19.835807 [ 1443 ] {} <Fatal> BaseDaemon: 1. ./build_docker/./src/Daemon/BaseDaemon.cpp:0: signalHandler(int, siginfo_t*, void*) @ 0x000000000eeeca9b
234:2024.05.21 13:11:28.282598 [ 1443 ] {} <Fatal> BaseDaemon: 2. __tsan::CallUserSignalHandler(__tsan::ThreadState*, bool, bool, int, __sanitizer::__sanitizer_siginfo*, void*) @ 0x000000000718e8f6
245:2024.05.21 13:11:36.070037 [ 1443 ] {} <Fatal> BaseDaemon: 3. sighandler(int, __sanitizer::__sanitizer_siginfo*, void*) @ 0x000000000718ee16
246:2024.05.21 13:11:36.070132 [ 1443 ] {} <Fatal> BaseDaemon: 4. ? @ 0x00007f89c1dfd520
247:2024.05.21 13:11:36.070175 [ 1443 ] {} <Fatal> BaseDaemon: 5. ? @ 0x00007f89c1e519fd
248:2024.05.21 13:11:36.070202 [ 1443 ] {} <Fatal> BaseDaemon: 6. ? @ 0x00007f89c1dfd476
249:2024.05.21 13:11:36.070227 [ 1443 ] {} <Fatal> BaseDaemon: 7. ? @ 0x00007f89c1de37f3
257:2024.05.21 13:11:43.819572 [ 1443 ] {} <Fatal> BaseDaemon: 8. ___interceptor_abort @ 0x000000000718d4ff
258:2024.05.21 13:11:43.981929 [ 1443 ] {} <Fatal> BaseDaemon: 9. ./build_docker/./src/Common/Exception.cpp:0: DB::abortOnFailedAssertion(String const&) @ 0x000000000eb829e5
259:2024.05.21 13:11:44.141828 [ 1443 ] {} <Fatal> BaseDaemon: 10. ./build_docker/./src/Common/Exception.cpp:0: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000eb836e4
270:2024.05.21 13:11:51.875207 [ 1443 ] {} <Fatal> BaseDaemon: 11. DB::Exception::Exception(PreformattedMessage&&, int) @ 0x000000000720e7c0
288:2024.05.21 13:11:59.653152 [ 1443 ] {} <Fatal> BaseDaemon: 12. DB::Exception::Exception<String&, String>(int, FormatStringHelperImpl<std::type_identity<String&>::type, std::type_identity<String>::type>, String&, String&&) @ 0x0000000008aef1e6
291:2024.05.21 13:11:59.939651 [ 1443 ] {} <Fatal> BaseDaemon: 13.0. inlined from ./build_docker/./src/Databases/DatabaseOrdinary.cpp:0: DB::setReplicatedEngine(DB::ASTCreateQuery*, std::shared_ptr<DB::Context const>)
292:2024.05.21 13:11:59.939748 [ 1443 ] {} <Fatal> BaseDaemon: 13. ./build_docker/./src/Databases/DatabaseOrdinary.cpp:160: DB::DatabaseOrdinary::convertMergeTreeToReplicatedIfNeeded(std::shared_ptr<DB::IAST>, DB::QualifiedTableName const&, String const&) @ 0x000000001637e427
298:2024.05.21 13:12:00.319213 [ 1443 ] {} <Fatal> BaseDaemon: 14.0. inlined from ./build_docker/./src/Databases/DatabaseOrdinary.cpp:0: operator()
299:2024.05.21 13:12:00.319291 [ 1443 ] {} <Fatal> BaseDaemon: 14.1. inlined from ./contrib/llvm-project/libcxx/include/__functional/invoke.h:394: ?
300:2024.05.21 13:12:00.319327 [ 1443 ] {} <Fatal> BaseDaemon: 14.2. inlined from ./contrib/llvm-project/libcxx/include/__functional/invoke.h:479: ?
301:2024.05.21 13:12:00.319361 [ 1443 ] {} <Fatal> BaseDaemon: 14.3. inlined from ./contrib/llvm-project/libcxx/include/__functional/function.h:235: ?
302:2024.05.21 13:12:00.319393 [ 1443 ] {} <Fatal> BaseDaemon: 14. ./contrib/llvm-project/libcxx/include/__functional/function.h:716: ? @ 0x00000000163880c4
315:2024.05.21 13:12:00.783183 [ 1443 ] {} <Fatal> BaseDaemon: 15.0. inlined from ./contrib/llvm-project/libcxx/include/__iterator/wrap_iter.h:100: std::__wrap_iter<std::pair<String, bool>*>::operator++[abi:v15000]()
316:2024.05.21 13:12:00.783260 [ 1443 ] {} <Fatal> BaseDaemon: 15.1. inlined from ./build_docker/./src/Databases/DatabaseOnDisk.cpp:671: operator()
317:2024.05.21 13:12:00.783298 [ 1443 ] {} <Fatal> BaseDaemon: 15.2. inlined from ./contrib/llvm-project/libcxx/include/__functional/invoke.h:394: ?
318:2024.05.21 13:12:00.783332 [ 1443 ] {} <Fatal> BaseDaemon: 15.3. inlined from ./contrib/llvm-project/libcxx/include/__functional/invoke.h:479: ?
319:2024.05.21 13:12:00.783363 [ 1443 ] {} <Fatal> BaseDaemon: 15.4. inlined from ./contrib/llvm-project/libcxx/include/__functional/function.h:235: ?
320:2024.05.21 13:12:00.783395 [ 1443 ] {} <Fatal> BaseDaemon: 15. ./contrib/llvm-project/libcxx/include/__functional/function.h:716: ? @ 0x000000001635f264
321:2024.05.21 13:12:00.940111 [ 1443 ] {} <Fatal> BaseDaemon: 16.0. inlined from ./base/base/../base/wide_integer_impl.h:817: bool wide::integer<128ul, unsigned int>::_impl::operator_eq<wide::integer<128ul, unsigned int>>(wide::integer<128ul, unsigned int> const&, wide::integer<128ul, unsigned int> const&)
322:2024.05.21 13:12:00.940224 [ 1443 ] {} <Fatal> BaseDaemon: 16.1. inlined from ./base/base/../base/wide_integer_impl.h:1491: bool wide::operator==<128ul, unsigned int, 128ul, unsigned int>(wide::integer<128ul, unsigned int> const&, wide::integer<128ul, unsigned int> const&)
323:2024.05.21 13:12:00.940281 [ 1443 ] {} <Fatal> BaseDaemon: 16.2. inlined from ./base/base/../base/strong_typedef.h:42: StrongTypedef<wide::integer<128ul, unsigned int>, DB::UUIDTag>::operator==(StrongTypedef<wide::integer<128ul, unsigned int>, DB::UUIDTag> const&) const
324:2024.05.21 13:12:00.940328 [ 1443 ] {} <Fatal> BaseDaemon: 16.3. inlined from ./src/Common/OpenTelemetryTraceContext.h:65: DB::OpenTelemetry::Span::isTraceEnabled() const
325:2024.05.21 13:12:00.940369 [ 1443 ] {} <Fatal> BaseDaemon: 16. ./build_docker/./src/Common/ThreadPool.cpp:464: ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::worker(std::__list_iterator<ThreadFromGlobalPoolImpl<false, true>, void*>) @ 0x000000000ec6f43c
326:2024.05.21 13:12:01.036998 [ 1443 ] {} <Fatal> BaseDaemon: 17. ./build_docker/./src/Common/ThreadPool.cpp:0: ThreadFromGlobalPoolImpl<false, true>::ThreadFromGlobalPoolImpl<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>(void&&)::'lambda'()::operator()() @ 0x000000000ec73d43
327:2024.05.21 13:12:01.188918 [ 1443 ] {} <Fatal> BaseDaemon: 18. ./contrib/llvm-project/libcxx/include/__functional/function.h:717: ? @ 0x000000000ec73c82
328:2024.05.21 13:12:01.292768 [ 1443 ] {} <Fatal> BaseDaemon: 19.0. inlined from ./base/base/../base/wide_integer_impl.h:817: bool wide::integer<128ul, unsigned int>::_impl::operator_eq<wide::integer<128ul, unsigned int>>(wide::integer<128ul, unsigned int> const&, wide::integer<128ul, unsigned int> const&)
329:2024.05.21 13:12:01.292867 [ 1443 ] {} <Fatal> BaseDaemon: 19.1. inlined from ./base/base/../base/wide_integer_impl.h:1491: bool wide::operator==<128ul, unsigned int, 128ul, unsigned int>(wide::integer<128ul, unsigned int> const&, wide::integer<128ul, unsigned int> const&)
330:2024.05.21 13:12:01.292922 [ 1443 ] {} <Fatal> BaseDaemon: 19.2. inlined from ./base/base/../base/strong_typedef.h:42: StrongTypedef<wide::integer<128ul, unsigned int>, DB::UUIDTag>::operator==(StrongTypedef<wide::integer<128ul, unsigned int>, DB::UUIDTag> const&) const
331:2024.05.21 13:12:01.292979 [ 1443 ] {} <Fatal> BaseDaemon: 19.3. inlined from ./src/Common/OpenTelemetryTraceContext.h:65: DB::OpenTelemetry::Span::isTraceEnabled() const
332:2024.05.21 13:12:01.293020 [ 1443 ] {} <Fatal> BaseDaemon: 19. ./build_docker/./src/Common/ThreadPool.cpp:464: ThreadPoolImpl<std::thread>::worker(std::__list_iterator<std::thread, void*>) @ 0x000000000ec6b604
333:2024.05.21 13:12:01.449913 [ 1443 ] {} <Fatal> BaseDaemon: 20.0. inlined from ./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:302: std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>::reset[abi:v15000](std::__thread_struct*)
334:2024.05.21 13:12:01.449999 [ 1443 ] {} <Fatal> BaseDaemon: 20.1. inlined from ./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:259: ~unique_ptr
335:2024.05.21 13:12:01.450037 [ 1443 ] {} <Fatal> BaseDaemon: 20.2. inlined from ./contrib/llvm-project/libcxx/include/tuple:265: ~__tuple_leaf
336:2024.05.21 13:12:01.450071 [ 1443 ] {} <Fatal> BaseDaemon: 20.3. inlined from ./contrib/llvm-project/libcxx/include/tuple:538: ~tuple
337:2024.05.21 13:12:01.450177 [ 1443 ] {} <Fatal> BaseDaemon: 20.4. inlined from ./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:48: std::default_delete<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void ThreadPoolImpl<std::thread>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>>::operator()[abi:v15000](std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void ThreadPoolImpl<std::thread>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>*) const
338:2024.05.21 13:12:01.450304 [ 1443 ] {} <Fatal> BaseDaemon: 20.5. inlined from ./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:305: std::unique_ptr<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void ThreadPoolImpl<std::thread>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>, std::default_delete<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void ThreadPoolImpl<std::thread>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>>>::reset[abi:v15000](std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void ThreadPoolImpl<std::thread>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>*)
339:2024.05.21 13:12:01.450350 [ 1443 ] {} <Fatal> BaseDaemon: 20.6. inlined from ./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:259: ~unique_ptr
340:2024.05.21 13:12:01.450402 [ 1443 ] {} <Fatal> BaseDaemon: 20. ./contrib/llvm-project/libcxx/include/thread:297: void* std::__thread_proxy[abi:v15000]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void ThreadPoolImpl<std::thread>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>>(void*) @ 0x000000000ec71b32
351:2024.05.21 13:12:09.227872 [ 1443 ] {} <Fatal> BaseDaemon: 21. __tsan_thread_start_func @ 0x0000000007186f2f
352:2024.05.21 13:12:09.227960 [ 1443 ] {} <Fatal> BaseDaemon: 22. ? @ 0x00007f89c1e4fac3
353:2024.05.21 13:12:09.227989 [ 1443 ] {} <Fatal> BaseDaemon: 23. ? @ 0x00007f89c1ee1850
354:2024.05.21 13:12:10.277188 [ 1443 ] {} <Fatal> BaseDaemon: Integrity check of the executable successfully passed (checksum: 58AF509A8485BC9B8D563D33B6BDFC49)
```

**Comment by kirillgarbar** [comment]
Logs show this message `No time left to shutdown. Process is still running. Will dump threads. (cluster.py:3882, wait_start_failed)`. Clickhouse was not killed in time and the exception is thrown while dumping threads with gdb, maybe due to clickhouse dying in the process.

**Pull request merged**
