### PR TITLE
Fix Exception: Password required for user default when drop partition of ReplicatedMergeTree table

### PR DESCRIPTION
**Pull request by viongpanzi**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

In our cluster, we have set password for the default user name. When we use default username to drop a partition of ReplicatedMergeTree table, sometimes we got the following exception:

```
Code: 194. DB::Exception: Received from localhost:9000, 127.0.0.1. DB::Exception: Received from host:9000, ip. DB::Exception: Password required for user default.

0. /home/clickhouse/clickhouse-current/bin/clickhouse-server(StackTrace::StackTrace()+0x16) [0x5c1e746]
1. /home/clickhouse/clickhouse-current/bin/clickhouse-server(DB::readException(DB::Exception&, DB::ReadBuffer&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)+0x337) [0x5c448a7]
2. /home/clickhouse/clickhouse-current/bin/clickhouse-server(DB::Connection::receiveException()+0x6f) [0x57580ef]
3. /home/clickhouse/clickhouse-current/bin/clickhouse-server(DB::Connection::receiveHello()+0x153) [0x57585d3]
4. /home/clickhouse/clickhouse-current/bin/clickhouse-server(DB::Connection::connect()+0x20b) [0x575ad7b]
5. /home/clickhouse/clickhouse-current/bin/clickhouse-server(DB::Connection::getServerRevision()+0x1a) [0x575b4fa]
6. /home/clickhouse/clickhouse-current/bin/clickhouse-server(DB::MultiplexedConnections::sendQuery(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long, DB::ClientInfo const*, bool)+0xd5b) [0x576c57b]
7. /home/clickhouse/clickhouse-current/bin/clickhouse-server(DB::RemoteBlockInputStream::sendQuery()+0x2fb) [0x49d6a3b]
8. /home/clickhouse/clickhouse-current/bin/clickhouse-server(DB::copyData(DB::IBlockInputStream&, DB::IBlockOutputStream&, std::atomic<bool>*)+0x24) [0x49dce24]
9. /home/clickhouse/clickhouse-current/bin/clickhouse-server(DB::StorageReplicatedMergeTree::sendRequestToLeaderReplica(std::shared_ptr<DB::IAST> const&, DB::Settings const&)+0xaad) [0x562e80d]
10. /home/clickhouse/clickhouse-current/bin/clickhouse-server(DB::StorageReplicatedMergeTree::dropPartition(std::shared_ptr<DB::IAST> const&, std::shared_ptr<DB::IAST> const&, bool, DB::Context const&)+0x55) [0x562fb45]
11. /home/clickhouse/clickhouse-current/bin/clickhouse-server(DB::InterpreterAlterQuery::execute()+0xeae) [0x598f45e]
12. /home/clickhouse/clickhouse-current/bin/clickhouse-server() [0x550f425]
13. /home/clickhouse/clickhouse-current/bin/clickhouse-server(DB::executeQuery(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, DB::Context&, bool, DB::QueryProcessingStage::Enum)+0x73) [0x55112c3]
14. /home/clickhouse/clickhouse-current/bin/clickhouse-server(DB::TCPHandler::runImpl()+0x499) [0x29b5c69]
15. /home/clickhouse/clickhouse-current/bin/clickhouse-server(DB::TCPHandler::run()+0x1c) [0x29b6eac]
16. /home/clickhouse/clickhouse-current/bin/clickhouse-server(Poco::Net::TCPServerConnection::start()+0xf) [0x5d92dbf]
17. /home/clickhouse/clickhouse-current/bin/clickhouse-server(Poco::Net::TCPServerDispatcher::run()+0x166) [0x5d93186]
``` 

The same exception will occur when truncate table of ReplicatedMergeTree.

According to the exception stack, we found that the context used in method StorageReplicatedMergeTree::sendRequestToLeaderReplica  does not contain the client_info, so we can not get current_user and current_password from the context : 
```
Connection connection(
        leader_address.host,
        leader_address.queries_port,
        leader_address.database,
        context.getClientInfo().current_user, context.getClientInfo().current_password, timeouts, "ClickHouse replica");
```

But the client_info actually is stored in the variable context outside the method StorageReplicatedMergeTree::sendRequestToLeaderReplica, so our solution is replacing the second parameter (called settings) with the context outside. And we test that is work.

### CODE REVIEW

**Comment by nicelulu** [comment]
https://github.com/yandex/ClickHouse/pull/3598
Maybe replica is different from the current server username and password.

**Comment by nicelulu** [comment]
I mean, this method is to send a request to the leader, so you should use the username and password of the leader server. Instead of executing the username and password of the current query server.

**Comment by nicelulu** [comment]
This method is to send a request to the leader, maybe the username and password of the leader server should be used. Instead of executing the username and password of the current query server.

**Comment by viongpanzi** [comment]
@nicelulu 

The following log is printed on the leader node:
```
0. /home/clickhouse/clickhouse-current/bin/clickhouse-server(StackTrace::StackTrace()+0x16) [0x5c1e746]
1. /home/clickhouse/clickhouse-current/bin/clickhouse-server(DB::Exception::Exception(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)+0x1f) [0x29a8a1f]
2. /home/clickhouse/clickhouse-current/bin/clickhouse-server() [0x298e1e1]
3. /home/clickhouse/clickhouse-current/bin/clickhouse-server(DB::SecurityManager::authorizeAndGetUser(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Poco::Net::IPAddress const&) const+0xb6) [0x54b01b6]
4. /home/clickhouse/clickhouse-current/bin/clickhouse-server(DB::Context::setUser(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Poco::Net::SocketAddress const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)+0x66) [0x5411e66]
5. /home/clickhouse/clickhouse-current/bin/clickhouse-server(DB::TCPHandler::receiveHello()+0x5c3) [0x29b3313]
6. /home/clickhouse/clickhouse-current/bin/clickhouse-server(DB::TCPHandler::runImpl()+0x1af) [0x29b597f]
7. /home/clickhouse/clickhouse-current/bin/clickhouse-server(DB::TCPHandler::run()+0x1c) [0x29b6eac]
8. /home/clickhouse/clickhouse-current/bin/clickhouse-server(Poco::Net::TCPServerConnection::start()+0xf) [0x5d92dbf]
9. /home/clickhouse/clickhouse-current/bin/clickhouse-server(Poco::Net::TCPServerDispatcher::run()+0x166) [0x5d93186]
10. /home/clickhouse/clickhouse-current/bin/clickhouse-server(Poco::PooledThread::run()+0x77) [0x5ea20a7]
11. /home/clickhouse/clickhouse-current/bin/clickhouse-server(Poco::ThreadImpl::runnableEntry(void*)+0x38) [0x5e9e068]
12. /home/clickhouse/clickhouse-current/bin/clickhouse-server() [0x652acef]
13. /lib64/libpthread.so.0(+0x7dc5) [0x7fcc50703dc5]
14. /lib64/libc.so.6(clone+0x6d) [0x7fcc4ff2873d]
```
The leader node will use the username and password configured on the machine to check those received from the connection.

If the username and password in the connection sent by follower node are both null, we still get the the same exception.

So I think it is the follower side problem.

Maybe better solusion is needed!

**Comment by viongpanzi** [comment]
This is my first submission, I wonder why the test didn't run？Is there anything wrong？

**Comment by alesapin** [comment]
Closed in favor of https://github.com/yandex/ClickHouse/pull/3598.

**Pull request closed without merging**
