### PR TITLE
fix csv format not support tuple

### PR DESCRIPTION
**Pull request by shuai-xu**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
fix csv write tuple in a wrong format and can not read it.

### Documentation entry for user-facing changes
Make csv format support write and read tuple.

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by shuai-xu** [comment]
When use csv, I found it got a wrong schema as bellow.
image

This pr fix it.

**Comment by robot-ch-test-poll4** [comment]
*This is an automated comment for commit 78873f7030e1b8745f35307f2ca89eb0ec178422 with description of existing statuses. It's updated for the latest CI running*

[❌ Click here](https://s3.amazonaws.com/clickhouse-test-reports/60994/78873f7030e1b8745f35307f2ca89eb0ec178422/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>❌ failure</td></tr>
<tbody>
</table>

**Review by yakov-olkhovskiy — COMMENTED** [review]
apparently we have the same issue with `tryDeserializeTextCSV`...

**Comment by shuai-xu** [comment]
> apparently we have the same issue with `tryDeserializeTextCSV`...

OK，I will take a look

**Comment by shuai-xu** [comment]
@yakov-olkhovskiy Can you help to review this pr?

**Review by yakov-olkhovskiy — APPROVED** [review]

**Pull request merged**
