### PR TITLE
Fixing hard coded timeouts in new live view tests.

### PR DESCRIPTION
**Pull request by vzakaznikov**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Build/Testing/Packaging Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fixing hard coded timeouts in new live view tests.

Detailed description / Documentation draft:
Fixing hard coded timeouts in new live view tests.

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
@vzakaznikov The same test has failed again.

**Comment by vzakaznikov** [comment]
> @vzakaznikov The same test has failed again.

It failed for a different reason. Looking into it.

**Comment by vzakaznikov** [comment]
@alexey-milovidov, pushed a fix. Let's see how it behaves this time.

**Comment by alexey-milovidov** [comment]
:+1:

**Comment by alexey-milovidov** [comment]
Still does not work.

**Comment by vzakaznikov** [comment]
> Still does not work.

Yes. I saw it. The clickhouse-server.log shows this exception. Do you think this is my bug?

**Comment by vzakaznikov** [comment]
@alexey-milovidov, I think I've beaten these tests into submission. Any way to re-run them a couple of more times?

**Comment by alexey-milovidov** [comment]
Ok. For unknown reason I don't see "debug" test runs. Will wait a bit more or re-run.

**Comment by vzakaznikov** [comment]
For some reason these debug runs did not start. I think the CI run needs to be restarted.

**Comment by vzakaznikov** [comment]
Last CI run shows that `Functional stateless tests (debug)` had no fails.

**Comment by alexey-milovidov** [comment]
Looks Ok.

**Pull request merged**
