### PR TITLE
Update s3queue.md to add experimental flag

### PR DESCRIPTION
**Pull request by melvynator**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Addex note about the experimental state
### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by robot-clickhouse** [comment]
*This is an automated comment for commit cbf0535468406e99536fe201a2fb6f297c0188cc with description of existing statuses. It's updated for the latest CI running*

[❌ Click here](https://s3.amazonaws.com/clickhouse-test-reports/55093/cbf0535468406e99536fe201a2fb6f297c0188cc/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>❌ failure</td></tr>
<tbody>
</table>

**Comment by qoega** [comment]
@melvynator PR description is important as it blocks CI when it is not correct. Updated that one for you

**Comment by melvynator** [comment]
Thanks @qoega

**Comment by qoega** [comment]
I think you need to touch something to restart CI.. I thought we can rerun it automatically after description was changed @Felixoid

**Comment by Felixoid** [comment]
Changing the description does not trigger the workflow. It was a flaw that could lead to running unauthorized code.

Although, adding label `can be tested` restarts the finished workflows

**Comment by Felixoid** [comment]
Excellent, we have a bug in the lambda, I'll take a look there. @yakov-olkhovskiy reported it today, so it's reproduced.

**Review by yakov-olkhovskiy — APPROVED** [review]

**Pull request merged**
