### PR TITLE
add SHA512_256 function

### PR DESCRIPTION
**Pull request by bharatnc**
### Changelog category (leave one):
- New Feature

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Add SHA512_256 function.

### Documentation entry for user-facing changes

- [x] Documentation is written (mandatory for new features)

Add SHA512_256 function for calculating sha512 hashes with digest length of 32.

Related to: #57591 cc: @alexey-milovidov

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]
Perfect.

**Comment by robot-ch-test-poll3** [comment]
*This is an automated comment for commit 2c1f57ba407f35fba4f902f020a720d716c74208 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/57645/2c1f57ba407f35fba4f902f020a720d716c74208/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td><a href="https://github.com/ClickHouse/ClickHouse/actions/runs/7136703816">✅ success</a></td></tr>
<tbody>
</table>
</details>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/57645/2c1f57ba407f35fba4f902f020a720d716c74208/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Comment by bharatnc** [comment]
> All new functions have to be documented inline in the code... and old functions as well.

I've added the inline documentation for SHA512_256. For the other hash functions, I'll do a follow up PR.

**Comment by bharatnc** [comment]
Doesn't build on s390x architecture https://s3.amazonaws.com/clickhouse-builds/PRs/57645/64ae04095406c93abd5974dfd63e1144249fab9e/binary_s390x/build_log.log

Will try to fix or at worst case avoid including the function for the s390x architecture.

**Review by alexey-milovidov — APPROVED** [review]
Looks good.

I see one failure with Analyzer (but Analyzer is in development, and we enabled fuzzing for it recently, so it produces a lot of errors).

Also, I will have to validate the performance - maybe this factory-method slows it down. But as the function is special, it will be acceptable anyway.

**Comment by alexey-milovidov** [comment]
The performance is slightly less, but not due to the factory method: https://pastila.nl/?00765cc5/aab0e57dc1d71400d502d69893e4f5de#4n5CP7HE3u5I1Dn+nieY3Q==

**Comment by bharatnc** [comment]
> Looks good.
> 
> I see one failure with Analyzer (but Analyzer is in development, and we enabled fuzzing for it recently, so it produces a lot of errors).

Oh perfect, thank you! Good to know, I was spending sometime trying to reproduce the fuzzer error locally to understand what's going on.

> The performance is slightly less, but not due to the factory method: https://pastila.nl/?00765cc5/aab0e57dc1d71400d502d69893e4f5de#4n5CP7HE3u5I1Dn+nieY3Q==

Yeah, I think that the performance shouldn't be that bad. Though, I noticed that the OpenSSL docs discourage the use of algorithm specific functions: https://www.openssl.org/docs/man1.1.1/man7/evp.html. We probably use them for performance reasons and I think they work perfectly well enough for our use cases.

> Although low-level algorithm specific functions exist for many algorithms their use is discouraged. They cannot be used with an ENGINE and ENGINE versions of new algorithms cannot be accessed using the low-level functions.

**Pull request merged**
