### PR TITLE
Better tests for protobuf format.

### PR DESCRIPTION
**Pull request by vitlibar**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category:
- Not for changelog

### CODE REVIEW

**Comment by nikitamikhaylov** [comment]
@vitlibar It seems that after this PR the build of utils is broken: 
```
cmake -DCMAKE_C_COMPILER=/usr/bin/clang -DCMAKE_CXX_COMPILER=/usr/bin/clang++ -DCMAKE_BUILD_TYPE=Debug -DPARALLEL_LINK_JOBS=12 -DPARALLEL_COMPILE_JOBS=56 -G Ninja ../../ClickHouse/

ninja: error: '/home/jakalletti/ClickHouse/ClickHouse/tests/queries/0_stateless/00825_protobuf_format.proto', needed by 'utils/test-data-generator/00825_protobuf_format.pb.cc', missing and no known rule to make it
```

With option `-DENABLE_UTILS=0` all works fine

**Comment by vitlibar** [comment]
> @vitlibar It seems that after this PR the build of utils is broken:
> 
> ```
> cmake -DCMAKE_C_COMPILER=/usr/bin/clang -DCMAKE_CXX_COMPILER=/usr/bin/clang++ -DCMAKE_BUILD_TYPE=Debug -DPARALLEL_LINK_JOBS=12 -DPARALLEL_COMPILE_JOBS=56 -G Ninja ../../ClickHouse/
> 
> ninja: error: '/home/jakalletti/ClickHouse/ClickHouse/tests/queries/0_stateless/00825_protobuf_format.proto', needed by 'utils/test-data-generator/00825_protobuf_format.pb.cc', missing and no known rule to make it
> ```
> 
> With option `-DENABLE_UTILS=0` all works fine

I forgot to delete this `test-data-generator`, I will fix that soon.

**Comment by alesapin** [comment]
ANTLR protobuf tests broken now? https://clickhouse-test-reports.s3.yandex.net/20968/2eecaee08dc1f52786527674d3e9263df846cdb1/functional_stateless_tests_(antlr_debug).html#fail1

**Comment by vitlibar** [comment]
> ANTLR protobuf tests broken now? https://clickhouse-test-reports.s3.yandex.net/20968/2eecaee08dc1f52786527674d3e9263df846cdb1/functional_stateless_tests_(antlr_debug).html#fail1

`skip_list.json` has been fixed in https://github.com/ClickHouse/ClickHouse/pull/21148

**Pull request merged**
