### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by cclauss**
### Changelog category (leave one):
- Documentation (changelog entry is not required)

### CODE REVIEW

**Review by kssenii — APPROVED** [review]

**Comment by robot-clickhouse** [comment]
This is an automated comment for commit 3d597a7d8edf902e30a924e91218e5f40365d7e5 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/54255/3d597a7d8edf902e30a924e91218e5f40365d7e5/ci_running.html)
The overall status of the commit is 🔴 failure

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>Docs Check</td><td>Builds and tests the documentation</td><td>🔴 failure</td></tr>
</table>

**Comment by Felixoid** [comment]
Hey-hey. This PR should have set the `do not test` label. It changes only markdown but did run the full CI two times

**Comment by kssenii** [comment]
> This PR should have set the do not test label

shouldn't the full run be automatically disabled if pr has label pr-documentation? I remember that it has always been so that if the pr changed only documentation - then only a small number of checks was run, at least it always was until recently.

**Comment by mkaynov** [comment]
There is a fix which address this issue [#54914](https://github.com/ClickHouse/ClickHouse/pull/54914)

**Pull request merged**
