### PR TITLE
Fix context lifetime for Y-shaped join.

### PR DESCRIPTION
**Pull request by KochetovNicolai**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix potential `Context has expired` error for Y-shaped JOIN. Was triggered in #71429

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Run only fuzzers related jobs (libFuzzer fuzzers, AST fuzzers, etc.)
- [ ]  Exclude: AST fuzzers
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-ch-test-poll3** [comment]
*This is an automated comment for commit 3156209d583e2eccf0bcb04d479e86b89d4b24ea with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/72735/3156209d583e2eccf0bcb04d479e86b89d4b24ea/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/b81ee27750c4520de6e6b979ce7d4f6a111cb8ea/docs_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Review by Algunenano — COMMENTED** [review]
Do we also need this in `joinPipelinesRightLeft`?

https://github.com/ClickHouse/ClickHouse/blob/3156209d583e2eccf0bcb04d479e86b89d4b24ea/src/QueryPipeline/QueryPipelineBuilder.cpp#L592-L596

**Comment by KochetovNicolai** [comment]
We have it
https://github.com/ClickHouse/ClickHouse/blob/420aa909a38c0ce656ec1f82f875cc32e414573c/src/QueryPipeline/QueryPipelineBuilder.cpp#L592

**Review by vdimir — APPROVED** [review]

**Review by Algunenano — APPROVED** [review]

**Comment by KochetovNicolai** [comment]
I cannot add a test because it is triggered with changes from https://github.com/ClickHouse/ClickHouse/pull/71429 only

**Pull request merged**
