### PR TITLE
Revert "Add `fromReadableSize` function"

### PR DESCRIPTION
**Pull request by rschu1ze**
Reverts ClickHouse/ClickHouse#64386

@Beetelbrox Your PR ClickHouse/ClickHouse#64386 is generally good but @alexey-milovidov asked for two changes:
- a single function for B, KB, MB, ... and B, KiB, MiB, ... units. I originally suggested separate functions (https://github.com/ClickHouse/ClickHouse/pull/64386#discussion_r1615292460) but there are good arguments for having only a single function (mostly ease-of-use).
- instead of `from*`, the function should be called `parse*` (similar to existing functions `formatDateTime` / `parseDateTime`).

Reverting to remove the two new functions before the v24.5 release today.

### CODE REVIEW

**Comment by robot-ch-test-poll** [comment]
*This is an automated comment for commit 48bd68a93e8c505e519820cf39a5b560f52b15da with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/64616/48bd68a93e8c505e519820cf39a5b560f52b15da/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>A Sync</td><td>If it fails, ask a maintainer for help</td><td>⏳ pending</td></tr>
<tbody>
</table>
<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

**Comment by Beetelbrox** [comment]
Hai @rschu1ze no probs! I'll open a separate PR with the proposed changes if it's OK with you.

Re: The `orNull` and `orZero` flavours, we do want to keep those right?

Thanks!

**Comment by rschu1ze** [comment]
@Beetelbrox Yes, let's keep `orNull` and `orZero` (there are equivalent variants for`parseDateTime`).

**Comment by Algunenano** [comment]
> Reverting to remove the two new functions before the v24.5 release today.

Just to clarify: This wasn't part of the 24.5 release to begin with. It was only present in master (so staged for 24.6)

**Pull request merged**
