### PR TITLE
add d3js based trace visualizer as gantt chart

### PR DESCRIPTION
**Pull request by serxa**
### Changelog category (leave one):
- New Feature

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Added open telemetry traces visualizing tool based on d3js

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
Please post here some screenshots as a teaser. It is truly wonderful!

**Comment by alexey-milovidov** [comment]
For minimized JS libraries we should do one of the following:
1. Replace with the links to cdnjs or jsdelivr or similar (with pinned version and integrity attribute).
2. Keep as is but put the links to the original non-minified sources in README, so it will be easy to regenerate or replace them.
3. Add JS build system (highly not recommended, because I have JS and CSS build systems).

**Comment by alexey-milovidov** [comment]
Let's make the changelog entry non-empty, as this can be advertised in the changelog.

**Comment by serxa** [comment]
> For minimized JS libraries we should do one of the following:
> 
> 1. Replace with the links to cdnjs or jsdelivr or similar (with pinned version and integrity attribute).
> 2. Keep as is but put the links to the original non-minified sources in README, so it will be easy to regenerate or replace them.
> 3. Add JS build system (highly not recommended, because I hate JS and CSS build systems).

The first one would not be self-contained, and I also do not like JS build systems as you do, so I would prefer the second option. 

Also there is an idea that all this is not usable as separate tool in utils/ folder, so I'm considering one of the following things to do in this PR:
1. Integrate this into `server/play.html` as generic way of visualising data from a table with columns: t1, t2, band, color, text as Gantt chart. Not directly related to tracing at all.
2. Integrate this into separate `server/trace.html` that will be dedicated to tracing and will keep all required queries inside, where you can see traces w/o any SQL. (Harder to implement, and actually can be a separate PR dedicated to tracing, leaving this PR as generic tool descriped in 1.)
3. Leave everything as is, but add README describing how to use it as an external tool separated from server.

@alexey-milovidov WDYT?

**Comment by alexey-milovidov** [comment]
Let's do it in two steps - first, merge this PR, then one of

> Integrate this into server/play.html as generic way of visualising data from a table with columns: t1, t2, band, color, text as Gantt chart. Not directly related to tracing at all.

Good, if it will be not very hard to integrate.

**Comment by serxa** [comment]
@alexey-milovidov I think this PR is ready to be merged (just the first step w/o integration into play UI)

**Review by nikitamikhaylov — APPROVED** [review]

**Comment by tavplubix** [comment]
@serxa, you forgot to take a look at failed tests before merging

**Pull request merged**
