### PR TITLE
fix transform with floating point key

### LINKED ISSUE #20460: Function 'transform' does not work properly for floating point keys.
https://clickhouse-test-reports.s3.yandex.net/19673/e7de5f34b1b3ae5d6d4e5d96ba0cd7c45acfb329/fuzzer_ubsan/server.log

**Describe the bug**
```
milovidov-desktop :) SELECT transform(number / 2, [0.5, 1.5], ['Hello', 'World'], '-') FROM numbers(10)

SELECT transform(number / 2, [0.5, 1.5], ['Hello', 'World'], '-')
FROM numbers(10)

Query id: f8c2646e-e234-41ae-85ef-7a452d4a2545

┌─transform(divide(number, 2), [0.5, 1.5], ['Hello', 'World'], '-')─┐
│ -                                                                 │
│ -                                                                 │
│ -                                                                 │
│ -                                                                 │
│ -                                                                 │
│ -                                                                 │
│ -                                                                 │
│ -                                                                 │
│ -                                                                 │
│ -                                                                 │
└───────────────────────────────────────────────────────────────────┘

10 rows in set. Elapsed: 0.003 sec. 

milovidov-desktop :) SELECT transform(number / 2, [1, 2], ['Hello', 'World'], '-') FROM numbers(10)

SELECT transform(number / 2, [1, 2], ['Hello', 'World'], '-')
FROM numbers(10)

Query id: 18b64dcf-983e-4653-a62b-5501e18314fd

┌─transform(divide(number, 2), [1, 2], ['Hello', 'World'], '-')─┐
│ -                                                             │
│ -                                                             │
│ Hello                                                         │
│ Hello                                                         │
│ World                                                         │
│ World                                                         │
│ -                                                             │
│ -                                                             │
│ -                                                             │
│ -                                                             │
└───────────────────────────────────────────────────────────────┘
```

### PR DESCRIPTION
**Pull request by ucasfl**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):

- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Fix function `transform` does not work properly for floating point keys. Closes #20460

Detailed description / Documentation draft:

cc @alexey-milovidov. This function works incorrect with floating point key, because when build cache, floating key is reinterpreted as `UInt64`, but does not reinterpret float value into `UInt64` on search.

### CODE REVIEW

**Comment by ucasFL** [comment]
Current fix may lead to another problem:
```
:) SELECT transform(number / 2, [1.0, 2.0], ['Hello', 'World'], '-') FROM numbers(10)

SELECT transform(number / 2, [1., 2.], ['Hello', 'World'], '-')
FROM numbers(10)

Query id: 8469547a-653a-4937-a2f2-0aa898618b07

┌─transform(divide(number, 2), [1., 2.], ['Hello', 'World'], '-')─┐
│ -                                                               │
│ -                                                               │
│ Hello                                                           │
│ -                                                               │
│ World                                                           │
│ -                                                               │
│ -                                                               │
│ -                                                               │
│ -                                                               │
│ -                                                               │
└─────────────────────────────────────────────────────────────────┘

:) SELECT transform(number / 2, [1, 2], ['Hello', 'World'], '-') FROM numbers(10)

SELECT transform(number / 2, [1, 2], ['Hello', 'World'], '-')
FROM numbers(10)

Query id: 37037e41-11ba-4254-a5c6-65d7987483e5

┌─transform(divide(number, 2), [1, 2], ['Hello', 'World'], '-')─┐
│ -                                                             │
│ -                                                             │
│ -                                                             │
│ -                                                             │
│ -                                                             │
│ -                                                             │
│ -                                                             │
│ -                                                             │
│ -                                                             │
│ -                                                             │
└───────────────────────────────────────────────────────────────┘
```
Since `reinterpreterAs(1.0, 'UInt64')` != `reinterpreterAs(1, 'UInt64')`.

**Comment by alexey-milovidov** [comment]
Yes, I also started patching and faced the same issue.

You can check my patch just in case:
[patch.txt](https://github.com/ClickHouse/ClickHouse/files/5978104/patch.txt)

**Comment by ucasFL** [comment]
> Yes, I also started patching and faced the same issue.
> 
> You can check my patch just in case:
> [patch.txt](https://github.com/ClickHouse/ClickHouse/files/5978104/patch.txt)

Your patch is good, I think I should close this pr.

**Comment by ucasFL** [comment]
For saving your time, I reopen this pr and update code with your patch^_^. @alexey-milovidov

**Comment by alexey-milovidov** [comment]
Thank you! It can be slightly incomplete but good to merge.

**Comment by ucasFL** [comment]
> Thank you! It can be slightly incomplete but good to merge.

No thanks! you are too kind!

BTW, which places need to be improved further?

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
If I remember correctly, it does not compare Float32 and Float64 correctly.

**Pull request merged**
