### PR TITLE
Remove Coverity from workflows, but leave in the code

### PR DESCRIPTION
**Pull request by alexey-milovidov**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

It stopped working a long time ago, but no one cares:
Screenshot_20230705_154046

### CODE REVIEW

**Comment by robot-ch-test-poll3** [comment]
This is an automated comment for commit 8d5ddcbd3094182b44b3641f11acf6ba788faaf7 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/51842/8d5ddcbd3094182b44b3641f11acf6ba788faaf7/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Review by nickitat — APPROVED** [review]

**Review by Felixoid — CHANGES_REQUESTED** [review]
As well `tetst/ci/ci_config.py`, `docker/packager/binary/*` and `docker/packager/packager`

There are a lot of code branches for coverity in those places

see `git grep -i coverity docker tests/ci`

**Comment by alexey-milovidov** [comment]
I'm ok deactivating it without complete removal.

**Review by Felixoid — APPROVED** [review]
Ok, let's then do it for now, and I won't mark it as done the CI backlogs

**Pull request merged**
