### PR TITLE
Fix access denied on opening file /var/lib/clickhouse/status in integration tests.

### PR DESCRIPTION
**Pull request by vitlibar**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category:
- Not for changelog

I was unable to run the integration tests using pytest without this change because the database directory for running a test (e.g. `/home/vitbar/work/ClickHouse/tests/integration/test_user_directories/_instances/node/database`) was created with wrong permissions. It was broken in https://github.com/ClickHouse/ClickHouse/pull/14619

### CODE REVIEW

**Comment by alesapin** [comment]
It shouldn't be related because `shutil.copytree` creates `dst` directory. What is more, it requires `dst` directory not exist: https://docs.python.org/2/library/shutil.html#shutil.copytree:
```
Recursively copy an entire directory tree rooted at src. The destination directory, named by dst, must not already exist; it will be created as well as missing parent directories.
```
Probably your change have to be placed in the `else` branch of `if self.clickhouse_path_dir is not None`.

**Comment by alesapin** [comment]
Can you show exact test which fails with the error?

**Comment by vitlibar** [comment]
> Can you show exact test which fails with the error?

I set `CLICKHOUSE_TESTS_SERVER_BIN_PATH`, `CLICKHOUSE_TESTS_CLIENT_BIN_PATH`, `CLICKHOUSE_TESTS_BASE_CONFIG_DIR` and then I ran `pytest -ss test_authentication/ -k test_authentication_pass` (the bug appeared with other tests too). It started and showed the following text:

```
Setup directory for instance: instance destroy_dirs: True
Copy common default production configuration from /home/vitbar/work/ClickHouse4/programs/server
Create directory for configuration generated in this helper
Create directory for common tests configuration
Copy common configuration from helpers
Generate and write macros file
Copy custom test config files [] to /home/vitbar/work/ClickHouse4/tests/integration/test_authentication/_instances/instance/configs/config.d
Setup database dir /home/vitbar/work/ClickHouse4/tests/integration/test_authentication/_instances/instance/database
Setup logs dir /home/vitbar/work/ClickHouse4/tests/integration/test_authentication/_instances/instance/logs
Env {} stored in /home/vitbar/work/ClickHouse4/tests/integration/test_authentication/_instances/instance/env_file
Entrypoint cmd: clickhouse server --config-file=/etc/clickhouse-server/config.xml --log-file=/var/log/clickhouse-server/clickhouse-server.log --errorlog-file=/var/log/clickhouse-server/clickhouse-server.err.log
('Trying to create ClickHouse instance by command %s', 'docker-compose --project-directory /home/vitbar/work/ClickHouse4/tests/integration/test_authentication --project-name vitbartestauthentication --file /home/vitbar/work/ClickHouse4/tests/integration/test_authentication/_instances/instance/docker_compose.yml up -d --no-recreate')
Creating network "vitbartestauthentication_default" with the default driver
Creating vitbartestauthentication_instance_1 ... done
ClickHouse instance created
Waiting for ClickHouse start...
Failed to start cluster: 
Instance `instance' failed to start. Container status: exited, logs: Processing configuration file '/etc/clickhouse-server/config.xml'.
Merging configuration file '/etc/clickhouse-server/conf.d/macros.xml'.
Merging configuration file '/etc/clickhouse-server/config.d/0_common_instance_config.xml'.
Include not found: clickhouse_remote_servers
Include not found: clickhouse_compression
Couldn't save preprocessed config to /var/lib/clickhouse/preprocessed_configs/config.xml: Access to file denied: /var/lib/clickhouse/preprocessed_configs
Logging trace to /var/log/clickhouse-server/clickhouse-server.log
Logging errors to /var/log/clickhouse-server/clickhouse-server.err.log
```

After that I opened `/var/log/clickhouse-server/clickhouse-server.err.log` and its contents was

```
2020.09.12 22:31:55.921957 [ 1 ] {} <Information> SentryWriter: Sending crash reports is disabled
2020.09.12 22:31:55.922266 [ 1 ] {} <Trace> Pipe: Pipe capacity is 1.00 MiB
2020.09.12 22:31:56.771480 [ 1 ] {} <Information> : Starting ClickHouse 20.10.1.1 with revision 54440, build id: 1C29AF814B12AA867431381BF45620D3CB4C2665, PID 1
2020.09.12 22:31:56.771715 [ 1 ] {} <Information> : Set OOM score adjustment to 555
2020.09.12 22:31:56.772488 [ 1 ] {} <Information> Application: starting up
2020.09.12 22:31:56.794616 [ 1 ] {} <Warning> Application: Server was built in debug mode. It will work slowly.
2020.09.12 22:31:56.801552 [ 1 ] {} <Information> Application: It looks like the process has no CAP_IPC_LOCK capability, binary mlock will be disabled. It could happen due to incorrect ClickHouse package installation. You could resolve the problem manually with 'sudo setcap cap_ipc_lock=+ep /usr/bin/clickhouse'. Note that it will not work on 'nosuid' mounted filesystems.
2020.09.12 22:31:56.801743 [ 1 ] {} <Warning> Application: Effective user of the process (1000) does not match the owner of the data (root).
2020.09.12 22:31:56.802359 [ 1 ] {} <Error> Application: DB::ErrnoException: Cannot open file /var/lib/clickhouse/status, errno: 13, strerror: Permission denied
2020.09.12 22:31:56.802430 [ 1 ] {} <Information> Application: shutting down
2020.09.12 22:31:56.802461 [ 1 ] {} <Debug> Application: Uninitializing subsystem: Logging Subsystem
2020.09.12 22:31:56.802704 [ 8 ] {} <Trace> BaseDaemon: Received signal -2
2020.09.12 22:31:56.802859 [ 8 ] {} <Information> BaseDaemon: Stop SignalListener thread
```

**Comment by vitlibar** [comment]
@alesapin I'm not sure this fix should be merged as is, it just allowed me to run integration tests.

**Comment by vitlibar** [comment]
> It shouldn't be related because `shutil.copytree` creates `dst` directory. What is more, it requires `dst` directory not exist: https://docs.python.org/2/library/shutil.html#shutil.copytree:
> 
> ```
> Recursively copy an entire directory tree rooted at src. The destination directory, named by dst, must not already exist; it will be created as well as missing parent directories.
> ```
> 
> Probably your change have to be placed in the `else` branch of `if self.clickhouse_path_dir is not None`.

Yeah, you're right. I've checked your change and it works.

**Pull request merged**
