### PR TITLE
use domain datatype for IPv4StringtoNum/IPStringv6toNum functions

### PR DESCRIPTION
**Pull request by fionera**
### Changelog category (leave one):
- Backward Incompatible Change

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
return domain values when using IPv4StringToNum or IPv6StringToNum

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
The functions `IPv4StringToNum`, `IPv6StringToNum` should convert to a number or a binary string - according to their names. We also cannot change them for compatibility reasons.

I think the `toIPv4`, `toIPv6` functions are good for what you want.

**Comment by fionera** [comment]
Ok I just noticed that the behaviour changed with the migration to domain data type. Previously one could use the returning data from these functions and use them in a column with the domain data type but now you have to cast the result.

**Comment by yakov-olkhovskiy** [comment]
```
ip-172-31-42-195.us-east-2.compute.internal :) create table tbl (ip IPv6) engine=Memory

CREATE TABLE tbl
(
    `ip` IPv6
)
ENGINE = Memory

Query id: e037b648-c75b-497d-99e9-3b4f433458cb

Ok.

0 rows in set. Elapsed: 0.002 sec.

ip-172-31-42-195.us-east-2.compute.internal :) insert into tbl values (IPv6StringToNum('::1'))

INSERT INTO tbl FORMAT Values

Query id: 7bee9ca0-1883-48d0-b396-23f7b38d0bad

Ok.

1 row in set. Elapsed: 0.009 sec.

ip-172-31-42-195.us-east-2.compute.internal :) select * from tbl

SELECT *
FROM tbl

Query id: b2d0411a-4e6c-4f3e-be40-ca9f33e5c738

┌─ip──┐
│ ::1 │
└─────┘

1 row in set. Elapsed: 0.005 sec.
```

**Comment by den-crane** [comment]
@fionera 

A while ago IPv4 and IPv6 types did not exist.

Clickhouse users use `IPv4StringToNum` and `IPv6StringToNum` to store IP addresses data in `UInt32` and `FixedString(16)` columns. So the output types of these functions should remain as is for backward compatibility

**Comment by fionera** [comment]
I have this function:
```
CREATE FUNCTION ParseAddress AS(Address) -> if(
    -- endsWith IPv6v4NullPadding
        endsWith(Address, repeat('\x00', 12)),
    -- prepend ::ffff:
        reinterpret(toFixedString(repeat('\x00', 10) || repeat('\xff', 2) || substr(Address, 1, 4), 16), 'IPv6'),
        Address
    );
    ```
    
    which I had to modify to this:
    ```
    CREATE FUNCTION ParseAddress AS(Address) -> if(
    -- endsWith IPv6v4NullPadding
        endsWith(reinterpret(Address, 'String'), repeat('\x00', 12)),
    -- prepend ::ffff:
        cast(toFixedString(repeat('\x00', 10) || repeat('\xff', 2) || substr(reinterpret(Address, 'String'), 1, 4), 16) as IPv6),
        Address
    );
    ```

**Comment by fionera** [comment]
I just noticed they have nothing todo with that but I cannot find the other UDF where I had this issue

**Comment by yakov-olkhovskiy** [comment]
@fionera what this function suppose to do and what's input type? seems unnecessary complicated to me...

**Comment by fionera** [comment]
The Input are bytes that are delivered via kafka encoded via protobuf. if it is a v4 address the data has 10x null bytes in front of the raw ip. I think this is the easiest way to get that into a valid v4-in-v6 address

**Pull request closed without merging**
