### PR TITLE
Fix trailing commas in `SELECT` clauses with aliases

### LINKED ISSUE #50998: Trailing commas in SELECT clauses aren't supported with aliases
Trailing commas was added recently (https://github.com/ClickHouse/ClickHouse/pull/48438) to support some cases, but it fails if the last expression contains an alias

Works:
```
Select
    sum(number) as s,
    number,
FROM numbers(10)
GROUP BY number
```

Works:
```
Select
    number,
    sum(number),
FROM numbers(10)
GROUP BY number
```

Doesn't work and gives a bad error:
```
Select
    number,
    sum(number) as s,
FROM numbers(10)
GROUP BY number
```

```
Syntax error: failed at position 47 ('numbers') (line 4, col 6):

Select
    number,
    sum(number) as s,
FROM numbers(10)
GROUP BY number

Expected one of: token, Dot, OR, AND, IS NULL, IS NOT NULL, BETWEEN, NOT BETWEEN, LIKE, ILIKE, NOT LIKE, NOT ILIKE, REGEXP, IN, NOT IN, GLOBAL IN, GLOBAL NOT IN, MOD, DIV, alias, AS, Comma, FROM, PREWHERE, WHERE, GROUP BY, WITH, HAVING, WINDOW, ORDER BY, LIMIT, OFFSET, SETTINGS, UNION, EXCEPT, INTERSECT, INTO OUTFILE, FORMAT, end of query
 ```

Refs https://github.com/ClickHouse/ClickHouse/issues/40192

### PR DESCRIPTION
**Pull request by AVMusorin**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix trailing commas in `SELECT` clauses with aliases

Closes: https://github.com/ClickHouse/ClickHouse/issues/50998

Follows: https://github.com/ClickHouse/ClickHouse/pull/59119, https://github.com/ClickHouse/ClickHouse/pull/52987

### CODE REVIEW

**Comment by robot-clickhouse-ci-2** [comment]
*This is an automated comment for commit 3b13768e3cec4793395239ba912ec80ffd7344c6 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/59236/3b13768e3cec4793395239ba912ec80ffd7344c6/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td><a href="https://github.com/ClickHouse/ClickHouse/actions/runs/7657666437/job/20869279475">✅ success</a></td></tr>
<tbody>
</table>
</details>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/59236/3b13768e3cec4793395239ba912ec80ffd7344c6/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Comment by alexey-milovidov** [comment]
Not a "bug fix".

**Comment by AVMusorin** [comment]
> It's been a while since the last commit, are you going to continue working on this pull request or I can close it?

Hi! I'm going to continue soon. Since I couldn't fix the issue from the first attempt and need more time to dig deeper.

**Comment by yariks5s** [comment]
`02676_trailing_commas` - is broken

**Comment by alexey-milovidov** [comment]
Let's ask for help from @evillique, he is an expert.

**Pull request closed without merging**
