### PR TITLE
Fix osx build

### PR DESCRIPTION
**Pull request by silviucpp**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Category (leave one):
- Build/Testing/Packaging Improvement

Short description (up to few sentences):

This PR it's fixing the compiling on OSX. It's work in progress as time the linking part is broken.

Using this PR the build on osx is fixed :

```
cmake .. -DCMAKE_CXX_COMPILER=`which g++-9` -DCMAKE_C_COMPILER=`which gcc-9` -DCMAKE_OSX_DEPLOYMENT_TARGET=10.12 -DCMAKE_BUILD_TYPE=Debug
```

Problem is that linking is broken because:

- `ld: unknown option: --no-undefined` generated because of:

```
# Make this extra-checks for correct library dependencies.
if (NOT SANITIZE)
    set (CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -Wl,--no-undefined")
    set (CMAKE_SHARED_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -Wl,--no-undefined")
endif ()
```

-  `--start-group` and `--end-group` aare not available on OSX. Those are used here:

```
add_library(global-group INTERFACE)
target_link_libraries(global-group INTERFACE
    -Wl,--start-group
    $<TARGET_PROPERTY:global-libs,INTERFACE_LINK_LIBRARIES>
    -Wl,--end-group
)
```

- syntax like: `-l:libstdc++.a -l:libstdc++fs.a` seems not working on OSX

```
target_link_libraries(global-libs INTERFACE -l:libstdc++.a -l:libstdc++fs.a) # Always link these libraries as static
```

Maybe somebody more familiar with ClickHouse cmake files can fix those easly than me.

### CODE REVIEW

**Comment by silviucpp** [comment]
On OSX `si_overrun` from `siginfo_t` is not available and I don't see similar functionality . Not sure if the fix I did in QueryProfiler is the proper one (just make sure that part is not executed on OSX). From what I understand that part is to make sure that in case the signals are called too frequently the performance is not affected too much.

**Comment by silviucpp** [comment]
@alexey-milovidov do you think somebody more familiar with the CMake files can help with fixing the linking process ?. I'll keep looking myself as well in the meantime.

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
Most of the changes are already prepared in #7028
Your PR also has some meaningful changes that are not in #7028
I can merge it when Linux builds will be finished (I have no Mac to check OS X build).
Only cross-compilation (that is implemented in #7028) will solve this problem.

PS. 
>  From what I understand that part is to make sure that in case the signals are called too frequently the performance is not affected too much.

Yes.

**Comment by silviucpp** [comment]
Ohh I didn't saw that you are already working on fixing this. You can get only the things that are not already covered in #7028 and close this one.

**Comment by alexey-milovidov** [comment]
#7028 is in progress. I will merge this first.

**Comment by abyss7** [comment]
That merge was very unexpected. I could just take missing changes to my PR.

**Comment by abyss7** [comment]
Anyway @silviucpp thanks for the nano-seconds sleep and pthread stack-size solutions!

**Pull request merged**
