### PR TITLE
Pasting improvement of clickhouse-client

### PR DESCRIPTION
**Pull request by amosbird**
Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Improve pasting performance and compatibility of clickhouse-client. This helps https://github.com/ClickHouse/ClickHouse/issues/35501

> Information about CI checks: https://clickhouse.tech/docs/en/development/continuous-integration/

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
https://github.com/Mergifyio update

**Comment by Felixoid** [comment]
@Mergifyio update

**Comment by alexey-milovidov** [comment]
@Mergifyio update

**Comment by alexey-milovidov** [comment]
GitHub was notoriously unstable these two days, let's try wait for checks.

**Pull request merged**
