### PR TITLE
Improve zookeeper path concatenation inside DDLWorker

### PR DESCRIPTION
**Pull request by bharatnc**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Improves the path concatenation of zookeeper paths inside DDLWorker.

Detailed description / Documentation draft:

This PR uses `std::filesystem::path`  for doing zookeeper path concatenation inside the DDLWorker instead of joining the paths adhoc using the `+` operator. 

The `std::filesystem::path` has been used to replace other similar adhoc concatenations in other parts of the code base as well, so leveraging it for uniformity.

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]
LGTM.

Using fs::path for ZooKeeper paths looks surprising at first glance... but actually it's natural.

**Comment by tavplubix** [comment]
I'm not sure if `std::filesystem:path` is suitable for paths in ZooKeeper, because ZooKeeper is actually not a filesystem. Some paths like `/q/../w`, `./file`, `/dir/` are fine in terms of `std::filesystem`, but all of them are invalid in terms of ZooKeeper.

Btw, which problem are you trying to solve?

**Comment by bharatnc** [comment]
> se ZooKeeper is actually not a filesystem

@tavplubix I agree that zk is not a filesystem & the general objective here is to just make the path concatenation more standardized using std::filesystem - like how it's being used few other places, for instance: https://github.com/ClickHouse/ClickHouse/pull/14558/files

**Comment by alexey-milovidov** [comment]
> are fine in terms of std::filesystem, but all of them are invalid in terms of ZooKeeper

AFAIK, unless we canonize the path, it will simply do concatenation with collapsing of slashes - should be safe.

**Pull request merged**
