### PR TITLE
Clean-up custom LLVM 15 patches

### PR DESCRIPTION
**Pull request by rschu1ze**
There are ongoing attempts to update LLVM from 15 to something newer (https://github.com/ClickHouse/ClickHouse/pull/66053, https://github.com/ClickHouse/ClickHouse/pull/47783). They suffer from the self-inflicted problem
- that ClickHouse's LLVM fork has a messy history which makes it hard to understand which fixes must be ported into newer versions,
- some of the fixes in the v15 fork were reverted because they became obsolete in the meantime

This PR
- is based on the latest v15 upstream state
- applies all needed patches (some were squashed to make things simpler), omits unneeded or reverted patches, and fixes the commit messages where they were too brief ("Test", "Better", etc. 😄)

The results is a short set of 15 custom patches https://github.com/ClickHouse/llvm-project/commits/ClickHouse/llvmorg-15.0.7/ .

Once this PR is in, we can attempt to forward-pick them into an LLVM 16 upgrade.

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by robot-ch-test-poll1** [comment]
*This is an automated comment for commit eb7ab5128d009fe89ef1994e2f32ea10bea900b1 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/66072/eb7ab5128d009fe89ef1994e2f32ea10bea900b1/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/9d79bd96250fb8ee9057343f02614db331172494/docs_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Comment by alexey-milovidov** [comment]
We should also have our own CMakeLists for LLVM. This is the last library (probably the hardest).
https://github.com/ClickHouse/llvm-project/commit/6f393d7a7d51a0990eeb392d14685d672a1d6d6f

**Review by alexey-milovidov — APPROVED** [review]

**Comment by zhanglistar** [comment]
@rschu1ze After updating version of LLVM-project, we can use more JIT on expression execution?

**Comment by rschu1ze** [comment]
@zhanglistar The set of functions that can be JITted is unrelated to the LLVM version. The primary reason to upgrade LLVM is to use features from a newer standard library (libcxx).

**Pull request merged**
