### PR TITLE
AVX vectorization of distance functions

### LINKED ISSUE #58096: `dotProduct` is not optimized for vector Similarity
## Background

Vector similarity is very popular right now, and ClickHouse has a few tutorials about this  [Source](https://clickhouse.com/blog/approximate-nearest-neighbour-ann-with-sql-powered-local-sensitive-hashing-lsh-random-projections). Regarding distances between vectors, they mention the most common ones:

- Euclidean distance
- Cosine distance

Captura de pantalla 2023-12-20 a las 21 01 10

But in my opinion dotProduct is a better replacement for cosineDistance because **is the same but faster**, let me explain...

## cosineDistance == dotProduct of L2 normalized vectors

`dotProduct` has a much cheaper computation than `cosineDistance`. But they produce different things.

download

However, **the dotProduct of the L2-normalized vectors** is mathematically the same that cosineDistance, but computationally cheaper because only the norm of the query verctor is computed at search time. The following formula illustrate this:

Captura de pantalla 2023-12-20 a las 21 30 29

>  L2 normalization is dividing (element-wise) the vector by its L2Norm. This produces the unit vector (vector lenght = 1) pointing to the same direction of the original vector.

## Poor performance of `dotProduct` in clickhouse now

Both `cosineDistance` and `dotProduct` exist in clickhouse. `dotProduct` should be faster, but currently is (~16x) slower .

```sql
WITH cosineDistance(img_emb, <query_emb>) AS score
SELECT id, score, caption
FROM laion
ORDER BY score DESC
LIMIT 3
# 3 rows in set. Elapsed: 0.535 sec. Processed 1.00 million rows, 2.13 GB (1.87 million rows/s., 3.98 GB/s.) Peak memory usage: 164.25 MiB.

WITH dotProduct(img_emb, <query_emb>) AS score
SELECT id, score, caption
FROM laion
ORDER BY score DESC
LIMIT 3
# 3 rows in set. Elapsed: 8.385 sec. Processed 1.00 million rows, 2.13 GB (119.31 thousand rows/s., 254.04 MB/s.) Peak memory usage: 420.67 MiB.
```

## Possible solution

I know projects like [SimSIMD](https://github.com/ashvardanian/SimSIMD) could help with this optimization.

### PR DESCRIPTION
**Pull request by rschu1ze**
Fixes: #58096

Vector search requires fast `L2Distance()` and `cosineDistance()` functions. The existing code relied on compiler auto-vectorization for SIMD.
(Side note: The code tried unrolling based on a fixed count of 4 elements at a time ([here](https://github.com/ClickHouse/ClickHouse/blob/22d09caea2fadce928094aac6ce902dc7f1c6933/src/Functions/array/arrayDistance.cpp#L378)). Depending on SIMD instruction set and result data type (`Float32`, `Float64`), this is not optimal. On the other hand, not unrolling at all regressed performance (#58940).)

This PR tries to make things faster with manual vectorization. To avoid combinatorial explosion, it focuses on
- the two most common input/output types `(Float32 x Float32) --> Float32` and `(Float64 x Float64) --> Float64` instead of 10 x 10 input types x 2 output types,
- const/non-const inputs instead of non-const/non-const inputs
- the two most common metrics L2 and cosine distance,
- the most powerful and convenient x86 SIMD instruction set (AVX-512F)

Performance test `norm_distance.xml` creates 80 mio arrays à 150 elements. Runtimes in second for query:

```sql
WITH
    (SELECT vec FROM vectors limit 1) AS const_vec
SELECT sum(dist)
FROM
    (SELECT <distance>(const_vec, vec) AS dist FROM vectors)

```

| | | auto-vectorized  | hand-vectorized | speedup |
| - | - | ------------- | ------------- | --- |
| Float32 | L2 | 0.61  | 0.57  | 1.07x |
| Float32 | cosine | 0.78  | 0.65  | 1.2x |
| Float64 | L2 | 1.15  | 0.99 | 1.16x |
| Float64 | cosine | 1.35  | 1.05 | 1.28x |

Not very impressive. I got slightly better results with speedups up to 1.56x on arrays with 600 elements (instead of 150).

Based on [this](https://stackoverflow.blog/2020/07/08/improving-performance-with-simd-intrinsics-in-three-use-cases/) and [this](https://stackoverflow.com/questions/45735679/euclidean-distance-using-intrinsic-instruction), I unrolled the intrinsics loop (https://github.com/ClickHouse/ClickHouse/pull/58866/commits/68d0f4e42161713f3b54de2069d894b1f84ed833) for a deeper pipeline. Didn't improve performance, so I rolled it [back](https://github.com/ClickHouse/ClickHouse/pull/58866/commits/68fc97089ec22d29b5d25df4e3865a22cf9701db) 😢

Tried to check what is going on with Intel Vtune, but did not manage to setup X- forwarding of the Vtune GUI over SSH from my Linux devserver to my Mac typewriter (should in theory be straightforward using XQuartz). Intel also no longer provides the Vtune viewer for Mac, and Vtune's terminal output in Linux is a mess. Then found out that `perf top` at least show assembly (but no memory access times). Output for the unrolled version:

image

Most time was spend in FMA, but since it should be [quite fast](https://www.intel.com/content/www/us/en/docs/intrinsics-guide/index.html#text=_mm512_fmadd_ps&ig_expand=3111) I think it was mostly waiting for memory. If someone has an idea how to improve further, please let me know.

The SIMD code is not terribly complicated, so even if the speedup is modest, we may merge this.

### Changelog category (leave one):
- Performance Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Vectorized distance functions used in vector search

### CODE REVIEW

**Comment by robot-ch-test-poll1** [comment]
*This is an automated comment for commit 0980c687867912fb3a60710240d7317345ceca19 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/58866/0980c687867912fb3a60710240d7317345ceca19/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/58866/0980c687867912fb3a60710240d7317345ceca19/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Comment by davenger** [comment]
Looks like norm_distance perf gets degraded:

https://s3.amazonaws.com/clickhouse-test-reports/58866/bc5dffa72ee82bde5681f74b8c53b91e3c8b5756/performance_comparison_[2_4]/report.html

https://s3.amazonaws.com/clickhouse-test-reports/58866/bc5dffa72ee82bde5681f74b8c53b91e3c8b5756/performance_comparison_[1_4]/report.html

**Comment by rschu1ze** [comment]
I believe the problem is that the arrays in the test have 10 elements.
With AVX-512, vectorization happens for 16 elements at a time, meaning that no vectorization happens at all whereas we previously (4 elements-at-a time) at least some batch processing happens.

**Comment by alexey-milovidov** [comment]
Add a test with typical vector sizes: 384, 768, 1536...

**Comment by nickitat** [comment]
0. to understand what we could get from optimising particular function we can compare query perf w/ and w/o it. the difference is the ceiling 
1. `perf` usually highlights bad `load`-s. I could try to repeat your experiment with `vtune` - previously it worked fine for me, would be sad if now it doesn't
2. anyway there is not much we could do about memory latency. only try to use different block sizes and see if there is a difference
3. apart from memory we want to optimise throughput. and there is two dimensions: width of instruction x pipeline parallelism. it might look obvious to choose avx512 because it is wider, but it is not so obvious for me because it is likely to cause down-clocking. so I'd try avx2 as well. speaking of pipeline parallelism we want all calculations to be as independent as possible and looking into this code I am a bit suspicious:
https://github.com/ClickHouse/ClickHouse/pull/58866/files#diff-d179ede38cb87027426950e96bb2cfe169ba3f96a7cd4bb5e6ebd944d294fdfeR105-R108
we collect all calculations in the same register (`sum`) and I'd assume that it might hurt parallelism. alternatively we could "unroll" calculations, e.g. do 2 or 4 sums into independent registers and then sum up them. not sure it will help at all, but imo worth trying
4. makes sense to carefully read assembly

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
Ok, but don't rush to close the task, because there was a complaint about the performance on ARM: https://github.com/ClickHouse/ClickHouse/issues/58096#issuecomment-1866195248

**Pull request merged**
