### PR TITLE
Pin requests to fix the integration tests

### PR DESCRIPTION
**Pull request by Felixoid**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix https://github.com/docker/docker-py/issues/3256

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: Normal Builds
- [ ]  Allow: Special Builds
- [ ]  Allow: All NOT Required Checks
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Do not test
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-clickhouse-ci-1** [comment]
*This is an automated comment for commit 231067b614d6cf1124ac00e74a551fe69c1aceea with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/65183/231067b614d6cf1124ac00e74a551fe69c1aceea/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Push to Dockerhub</td><td>The check for building and pushing the CI related docker images to docker hub</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

**Review by Algunenano — APPROVED** [review]

**Review by alexey-milovidov — APPROVED** [review]
That's really good, but we need to pin all libraries.

**Comment by Felixoid** [comment]
@Algunenano the two of four integration tests failed on dead runners, but the two that survived look promising.

Should it be merged, I think?

**Comment by Algunenano** [comment]
> Should it be merged, I think?

Yes, I think so. We'll need the change in all stable branches

**Comment by alexey-milovidov** [comment]
@Felixoid, tests have failed.

**Comment by Felixoid** [comment]
I hope somebody will fix failing tests. 

This PR fixing failing launch of integration tests

image
image
image

**Comment by Felixoid** [comment]
All the releases 24+ are not affected

**Pull request merged**
