### PR TITLE
Checking flaky stateless tests

### PR DESCRIPTION
**Pull request by alesapin**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by alesapin** [comment]
I'll manually run check after build and merge if everything is OK.

**Comment by alesapin** [comment]
image

**Comment by alesapin** [comment]
Waiting for normal stateless tests

**Comment by alesapin** [comment]
`01516_drop_table_stress` -- timeout cc @tavplubix

**Comment by tavplubix** [comment]
> `01516_drop_table_stress` -- timeout https://clickhouse-test-reports.s3.yandex.net/16261/b29cfa7f826566192478c77413ccca34e8a719ac/functional_stateless_tests_(memory).html#fail1

Funny race between async `DROP DATABASE` and `DROP TABLE SYNC`, fixed in #16127

**Review by tavplubix — APPROVED** [review]

**Comment by alesapin** [comment]
image

**Comment by alesapin** [comment]
Hooray, tests passed.

**Pull request merged**
