### PR TITLE
MADV_DONTNEED check in runtime for qemu (via patching jemalloc)

### PR DESCRIPTION
**Pull request by azat**
qemu does not support MADV_DONTNEED, and by not support it simply ignore
it (i.e. return 0 -- no error).

This issue has been "fixed" in #15590, however it just
terminates the process, and completely breaks clickhouse under qemu
(see also #15174).

But there is no need in such strong protection, we can stop using
madvise in jemalloc if MADV_DONTNEED does not work properly.
And this is what #18169 was tried to do (by override madvise), however
this will break sanitizers, at least TSAN and UBSAN.
The problem there is that sanitizers initialization code uses madvise
(and there is no way to turn this off with TSAN_OPTIONS) and overwritten
madvise function will have sanitizers traits (__tsan_func_entry), while
TSAN is not ready for this, and eventually it SIGSEGV.
Interesting thing is that in the recent clang-12, madvise was replaced
with direct syscall [1].

  [1]: https://github.com/llvm/llvm-project/commit/9f8c4039f202c4f8e8b820bce6f05039d53ea005

But it is better to make clickhouse compatible with clang < 12 too, so
instead of override madvise completely, the runtime check was moved into
the jemalloc code [2].

  [2]: https://github.com/ClickHouse-Extras/jemalloc/pull/1

Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Cc: @alexey-milovidov 

*P.S. I will keep this as draft for a couple of days, to wait for feedback from jemalloc maintainers*

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]

**Comment by azat** [comment]
>ClickHouse build check Pending — Started

Does the build hung? Or it will be started eventually?

**Comment by alexey-milovidov** [comment]
Performance: 7340839d6d

**Comment by alexey-milovidov** [comment]
> Functional stateless tests flaky check (address) — fail: 0, passed: 0, skipped: 100 

It's marked as failed due to "passed: 0", actually it's Ok.

**Comment by alexey-milovidov** [comment]
> Yandex ... check

Don't care.

**Comment by alexey-milovidov** [comment]
@azat I think it is ready to merge.

**Comment by azat** [comment]
>@azat I think it is ready to merge.

@alexey-milovidov this should be a correct fix, however I want to wait for the feedback from maintainers, so if i.e. there will some wish to implement it in a different way or some cosmetic changes would rebase the backported patch (to avoid further conflicts and similar issues)

So I'm suggesting wait for at least couple of work days (ideally week), and merge

**Comment by alexey-milovidov** [comment]
A link to upstream PR:  https://github.com/jemalloc/jemalloc/pull/2005

**Comment by alexey-milovidov** [comment]
@azat Let's add a reference to the description of upstream PR, like this:

`This change is needed for [ClickHouse](https://github.com/ClickHouse/ClickHouse/) to enable tests of [AArch64 builds under QEMU](https://github.com/ClickHouse/ClickHouse/issues/15174).`

**Comment by azat** [comment]
>@azat Let's add a reference to the description of upstream PR, like this:

Sure, done (although this does not show the whole problem - any program with jemalloc under qemu is broken now)

**Comment by alexey-milovidov** [comment]
> So I'm suggesting wait for at least couple of work days (ideally week), and merge

We can always change our mind later.

**Pull request merged**
