### PR TITLE
Disable some Dynamic tests under sanitizers, rewrite 03202_dynamic_null_map_subcolumn to sql

### LINKED ISSUE #67331: Test `03036_dynamic_read_subcolumns_compact_merge_tree` has failed
https://s3.amazonaws.com/clickhouse-test-reports/66506/da582fd2e9832aa5121feab4077119fea5d08ac2/stateless_tests__asan__[2_2].html

### PR DESCRIPTION
**Pull request by Avogar**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Splitting these tests didn't help, we can still see timeouts in sanitizers. Let's disable these tests under sanitizers and forget about them. Closes https://github.com/ClickHouse/ClickHouse/issues/67331

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-ch-test-poll2** [comment]
*This is an automated comment for commit c70bbe1d29288646a4c9897b57e9ff03acbc2052 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/67359/c70bbe1d29288646a4c9897b57e9ff03acbc2052/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Builds</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/67312/031c3aa5ebe2b36e778465bccc714cd8730ca7f2/builds/report.html">✅ success</a></td></tr>
<tr><td>ClickBench</td><td>Runs [ClickBench](https://github.com/ClickHouse/ClickBench/) with instant-attach table</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/67312/031c3aa5ebe2b36e778465bccc714cd8730ca7f2/clickbench__aarch64_.html">✅ success</a></td></tr>
<tr><td>Compatibility check</td><td>Checks that <b>clickhouse</b> binary runs on distributions with old libc versions. If it fails, ask a maintainer for help</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/67312/031c3aa5ebe2b36e778465bccc714cd8730ca7f2/compatibility_check__aarch64_.html">✅ success</a></td></tr>
<tr><td>Docker keeper image</td><td>The check to build and optionally push the mentioned image to docker hub</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/67312/031c3aa5ebe2b36e778465bccc714cd8730ca7f2/docker_keeper_image.html">✅ success</a></td></tr>
<tr><td>Docker server image</td><td>The check to build and optionally push the mentioned image to docker hub</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/67312/031c3aa5ebe2b36e778465bccc714cd8730ca7f2/docker_server_image.html">✅ success</a></td></tr>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/8e3d832ccdcdbf4d0a3225fff0e2602595f059a5/docs_check.html">✅ success</a></td></tr>
<tr><td>Install packages</td><td>Checks that the built packages are installable in a clear environment</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/67312/031c3aa5ebe2b36e778465bccc714cd8730ca7f2/install_packages__aarch64_.html">✅ success</a></td></tr>
<tr><td>Performance Comparison</td><td>Measure changes in query performance. The performance test report is described in detail <a href="https://github.com/ClickHouse/ClickHouse/tree/master/docker/test/performance-comparison#how-to-read-the-report">here</a>. In square brackets are the optional part/total tests</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/67312/031c3aa5ebe2b36e778465bccc714cd8730ca7f2/performance_comparison__release__[1_4]/report.html">✅ success</a></td></tr>
<tr><td>Stateful tests</td><td>Runs stateful functional tests for ClickHouse binaries built in various configurations -- release, debug, with sanitizers, etc</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/67312/031c3aa5ebe2b36e778465bccc714cd8730ca7f2/stateful_tests__aarch64_.html">✅ success</a></td></tr>
<tr><td>Unit tests</td><td>Runs the unit tests for different release types</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/67312/031c3aa5ebe2b36e778465bccc714cd8730ca7f2/unit_tests__asan_.html">✅ success</a></td></tr>
<tr><td>Upgrade check</td><td>Runs stress tests on server version from last release and then tries to upgrade it to the version from the PR. It checks if the new server can successfully startup without any errors, crashes or sanitizer asserts</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/67312/031c3aa5ebe2b36e778465bccc714cd8730ca7f2/upgrade_check__debug_.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
Ok. Do we have any simple logic tests for `Dynamic`, that are still enabled under sanitizers?

**Comment by Avogar** [comment]
Yes, we have a lot of other simple tests for Dynamic. But I also think I will write smallere versions of these tests and will allow them to run under sanitizers

**Comment by alexey-milovidov** [comment]
The test https://s3.amazonaws.com/clickhouse-test-reports/67701/090fb59194462324507d75f032aa803303c3e041/stateless_tests__aarch64_.html has failed without any sanitizers.

**Comment by alexey-milovidov** [comment]
https://github.com/ClickHouse/ClickHouse/issues/67721

**Pull request merged**
