### PR TITLE
Update SIMDJSON to the latest master

### LINKED ISSUE #9976: Consider upgrading to simdjson version 0.4.0
**Use case**

The latest versions of simdjson (0.3 and 0.4) bring significant performance improvements. One immediate benefit is that it runs on all 64-bit systems, no need to disable it on older hardware. It is also much faster. 

**Describe the solution you'd like**
I think you should upgrade to simdjson 0.3.

**Describe alternatives you've considered**
Sticking with an old version of the library.

**Additional context**
# Version 0.4 of simdjson is now available

Highlights

- Test coverage has been greatly improved and we have resolved many static-analysis warnings on different systems. 

New features:
- We added a fast (8GB/s) minifier that works directly on JSON strings.
- We added fast (10GB/s) UTF-8 validator that works directly on strings (any strings, including non-JSON). 
- The array and object elements have a constant-time size() method. 

Performance:
- Performance improvements to the API (type(), get<>()).
- The parse_many function (ndjson) has been entirely reworked. It now uses a single secondary thread instead of several new threads.
- We have introduced a faster UTF-8 validation algorithm (lookup3) for all kernels (ARM, x64 SSE, x64 AVX).

System support:
- C++11 support for older compilers and systems.
- FreeBSD support (and tests).
- We support the clang front-end compiler (clangcl) under Visual Studio.
- It is now possible to target ARM platforms under Visual Studio.
- The simdjson library will never abort or print to standard output/error.

# Version 0.3 of simdjson is now available

## Highlights

- **Multi-Document Parsing:** Read a bundle of JSON documents (ndjson) 2-4x faster than doing it  individually. [API docs](https://github.com/simdjson/simdjson/blob/master/doc/basics.md#newline-delimited-json-ndjson-and-json-lines) / [Design Details](https://github.com/simdjson/simdjson/blob/master/doc/parse_many.md)
- **Simplified API:** The API has been completely revamped for ease of use, including a new JSON  navigation API and fluent support for error code *and* exception styles of error handling with a  single API. [Docs](https://github.com/simdjson/simdjson/blob/master/doc/basics.md#the-basics-loading-and-parsing-json-documents)
- **Exact Float Parsing:** Now simdjson parses floats flawlessly *without* any performance loss (https://github.com/simdjson/simdjson/pull/558).
  [Blog Post](https://lemire.me/blog/2020/03/10/fast-float-parsing-in-practice/)
- **Even Faster:** The fastest parser got faster! With a [shiny new UTF-8 validator](https://github.com/simdjson/simdjson/pull/387)
  and meticulously refactored SIMD core, simdjson 0.3 is 15% faster than before, running at 2.5 GB/s   (where 0.2 ran at 2.2 GB/s).

## Minor Highlights

- Fallback implementation: simdjson now has a non-SIMD fallback implementation, and can run even on  very old 64-bit machines.
- Automatic allocation: as part of API simplification, the parser no longer has to be preallocated-it will adjust automatically when it encounters larger files.
- Runtime selection API: We've exposed simdjson's runtime CPU detection and implementation selection  as an API, so you can tell what implementation we detected and test with other implementations.
- Error handling your way: Whether you use exceptions or check error codes, simdjson lets you handle  errors in your style. APIs that can fail return simdjson_result<T>, letting you check the error  code before using the result. But if you are more comfortable with exceptions, skip the error code and cast straight to T, and exceptions will be thrown automatically if an error happens. Use the  same API either way!
- Error chaining: We also worked to keep non-exception error-handling short and sweet. Instead of  having to check the error code after every single operation, now you can *chain* JSON navigation calls like looking up an object field or array element, or casting to a string, so that you only  have to check the error code once at the very end.

### PR DESCRIPTION
**Pull request by alexey-milovidov**
Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Update SIMDJSON to the latest master. This fixes #9976.

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
01293_system_distribution_queue - reported @azat

**Comment by alexey-milovidov** [comment]
Performance tests have failed for reason, cannot merge.

**Comment by alexey-milovidov** [comment]
RapidJSON is accidentially get used instead of SIMDJSON.

**Comment by lemire** [comment]
Note that if you use the latest simdjson (0.4), then it works without SSE support. We have a fallback kernel. It is runs pretty much everywhere. You could simplify your setup quite a bit.

**Comment by alexey-milovidov** [comment]
@lemire Yes, I will remove RapidJSON and generic interface.

**Comment by vitlibar** [comment]
I made another PR https://github.com/ClickHouse/ClickHouse/pull/12423 to continue the work.

**Pull request closed without merging**
