### PR TITLE
Fix removing is_active node after re-creation

### PR DESCRIPTION
**Pull request by tavplubix**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by robot-clickhouse-ci-1** [comment]
*This is an automated comment for commit ec3b32bd8318d146f0fb984990138bc0cf63cacb with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/61105/ec3b32bd8318d146f0fb984990138bc0cf63cacb/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

**Comment by tavplubix** [comment]
@Felixoid yourpy is broken

**Comment by Felixoid** [comment]
Our `mypy` was updated yesterday morning

When the style check image is updated, unfortunately, it breaks stale PRs. Your is three days old since is based on https://github.com/ClickHouse/ClickHouse/commit/d93dd98b66ee8e44b0c99a0064fa68d98d93c7e9, see parent of https://github.com/ClickHouse/ClickHouse/commit/e2317477f7b95d07407db8def968d286aa9e270d

**Comment by tavplubix** [comment]
> it breaks stale PRs. Your is three days old 

I created this PR 5 hours ago. I thought we run CI on a result of merging PR's branch and master

**Comment by Felixoid** [comment]
> I created this PR 5 hours ago.

Correct, but the merge-base was https://github.com/ClickHouse/ClickHouse/commit/d93dd98b66ee8e44b0c99a0064fa68d98d93c7e9, a commit made on March 5th. The age of the PR itself is not so important

> I thought we run CI on a result of merging PR's branch and master

Yes, for 99% of the checks. The `Style check` is very special because we have auto-fixers there. We run it on top of the head branch, but the style check image is taken from the merge commit. This issue I'll try to brain-storm with @maxknv in https://github.com/ClickHouse/ClickHouse/pull/60408

**Review by alesapin — APPROVED** [review]

**Comment by tavplubix** [comment]
ClickHouse special build check - was broken in master
Integration tests (tsan) [4/6] - https://github.com/ClickHouse/ClickHouse/pull/59082
Integration tests flaky check (asan) - https://github.com/ClickHouse/ClickHouse/issues/39797

**Pull request merged**
