### PR TITLE
Fix broken multi-column aggregation on s390x

### PR DESCRIPTION
**Pull request by HarryLeeIBM**
The optimization implemented in [PR 55809](https://github.com/ClickHouse/ClickHouse/pull/55809) breaks aggregation of multiple columns on s390x due to the change of order of columns in intermediate results.

For example: 

`SELECT n, k FROM(SELECT number AS n, toFixedString(materialize('   '), 3) AS k FROM system.numbers LIMIT 1) GROUP BY n,k;`

The correct result should be:

```
   ┌─n─┬─k───┐
1. │ 0 │     │
   └───┴─────┘

```
But it gives wrong results:

```
   ┌───────────────────n─┬─k─┐
1. │ 2314885392840523776 │   │
   └─────────────────────┴───┘

```
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fixed broken multiple columns aggregation on s390x.

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: Normal Builds
- [ ]  Allow: Special Builds
- [ ]  Allow: All NOT Required Checks
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Do not test
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-ch-test-poll2** [comment]
*This is an automated comment for commit a7acc79fe5eb8def7509369e7d70bb6c8fcef295 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/65062/a7acc79fe5eb8def7509369e7d70bb6c8fcef295/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>A Sync</td><td>If it fails, ask a maintainer for help</td><td>⏳ pending</td></tr>
<tbody>
</table>
<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>Checks correctness of the PR's body</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

**Comment by alexey-milovidov** [comment]
This cannot be classified as a bugfix, because ClickHouse is not supported on s390x. I've removed the "bug fix" label. The PR is still ok, though.

**Comment by HarryLeeIBM** [comment]
@alexey-milovidov, thanks for taking care of this PR. Since the failed tests are not related to the fix, can it be merged? Thanks!

**Comment by alexey-milovidov** [comment]
> breaks aggression of multiple columns

There is no aggression in ClickHouse.

**Comment by alexey-milovidov** [comment]
First need to fix https://s3.amazonaws.com/clickhouse-test-reports/65062/7b089e9334595578abd25b868347c007f3880505/stateless_tests__debug__[1_5].html

**Comment by HarryLeeIBM** [comment]
> > breaks aggression of multiple columns
> 
> There is no aggression in ClickHouse.

Sorry for the typo, fixed.

**Comment by HarryLeeIBM** [comment]
> First need to fix [https://s3.amazonaws.com/clickhouse-test-reports/65062/7b089e9334595578abd25b868347c007f3880505/stateless_tests__debug__[1_5].html](https://s3.amazonaws.com/clickhouse-test-reports/65062/7b089e9334595578abd25b868347c007f3880505/stateless_tests__debug__%5B1_5%5D.html)

This test(02340_parts_refcnt_mergetree) passed in the last run. The last run has 02481_async_insert_race_long failure but it is not related to the fix(Code: 210. DB::NetException: Connection reset by peer).

**Comment by alexey-milovidov** [comment]
I will wait while @CurtizJ will fix this test.

**Review by yakov-olkhovskiy — APPROVED** [review]

**Comment by yakov-olkhovskiy** [comment]
failed tests seems unrelated
fix should not impact anyhow little endian functionality

**Pull request merged**
