### PR TITLE
WIP: add "stack clash" protection when possible

### PR DESCRIPTION
**Pull request by chipitsine**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

For changelog. Remove if this is non-significant change.

Category (leave one):
- Build/Testing/Packaging Improvement

Short description (up to few sentences):
add "stack clash" protection when compier supports it

Detailed description (optional):

inspired by http://www.opennet.ru/opennews/art.shtml?num=49931

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
What is the runtime penalty of this option?

**Comment by alexey-milovidov** [comment]
No difference in our CI, because we have no bulds with gcc8.

**Comment by chipitsine** [comment]
sorry, I'm somewhat busy.
will address this PR later

**Comment by alexey-milovidov** [comment]
This can be continued.

**Pull request closed without merging**
