### PR TITLE
[CH-31221] AWS S3 Object Version Specification

### LINKED ISSUE #31221: S3 Table Function Ignoring VersionId
Summary: S3 versionId is being ignored by the S3 table function

S3 has object versioning and for the object url to specify a version other than the latest the parameter "versionId=x" is added.

When querying on clickhouse with the S3 Table Function, the following is expected to select from the s3 object with versionId=testVersionId
`SELECT * FROM s3('https://s3.us-east-2.amazonaws.com/my-test-bucket-768/data.csv?versionId=testVersionId', 'CSV', 'column1 UInt32, column2 UInt32, column3 UInt32') LIMIT 2;`

Unfortunately it instead returns the latest. 

This has been reproduced on the following versions:
v21.8.4
v21.9.4.35 (latest)

This can be worked around by instead creating a signed url and using the url table function instead, however it would be preferable to not have to do that.

### PR DESCRIPTION
**Pull request by surahman**
Changelog category (leave one):
- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Extracts Version ID if present from the URI and adds a request to the AWS HTTP URI. Closes #31221.
- [x] Extract `Version ID` from URI if present and reassemble without it.
- [x] Configure `AWS HTTP URI` object with request.
- [x] Unit Tests: [`gtest_s3_uri`](https://github.com/ClickHouse/ClickHouse/blob/2340a6c6849ebc05a8efbf97ba8de3ff9dc0eff4/src/IO/tests/gtest_s3_uri.cpp)
- [x] Drop instrumentation commit.

### CODE REVIEW

**Comment by surahman** [comment]
@alexey-milovidov I am trying to generate tests for this PR but the mock HTTP server is running into issues when the URI is validated for the hostname.

```bash
SELECT *
FROM s3('http://127.0.1.1:33303/Key+', 'CSV', 'response TEXT')

Query id: 624275ad-3dfe-4b75-b64f-bb851c4f12e4


0 rows in set. Elapsed: 1.271 sec. 

Received exception from server (version 22.2.1):
Code: 36. DB::Exception: Received from localhost:9000. DB::Exception: Bucket or key name are invalid in S3 URI.. (BAD_ARGUMENTS)
```

I was wondering if get some insights into how this test is working?
https://github.com/ClickHouse/ClickHouse/blob/bc206ec423c4c5614572b18d5a61e12f80d55d19/tests/queries/0_stateless/01801_s3_cluster.sql#L4
Running this against a mock HTTP server would have been ideal

**Comment by surahman** [comment]
Consolidating what I have figured out:

The AWS API sends the `versionId` in the `GET` of an HTTP request.
[`SetVersionId`](https://github.com/aws/aws-sdk-cpp/blob/6e854b6a8bc7945f150c3a11551196bda341962a/aws-cpp-sdk-s3/include/aws/s3/model/GetObjectRequest.h#L766)
[Setting of parameter](https://github.com/aws/aws-sdk-cpp/blob/6e854b6a8bc7945f150c3a11551196bda341962a/aws-cpp-sdk-s3/source/model/GetObjectRequest.cpp#L99)
[`AddQueryStringParameter`](https://github.com/aws/aws-sdk-cpp/blob/6e854b6a8bc7945f150c3a11551196bda341962a/aws-cpp-sdk-core/source/http/URI.cpp#L360)
[`Aws::String m_queryString`](https://github.com/aws/aws-sdk-cpp/blob/6e854b6a8bc7945f150c3a11551196bda341962a/aws-cpp-sdk-core/include/aws/core/http/URI.h#L205)

Constructor for the `AWS::HTTP::URI` extracts the `Path` and `QueryString` as such:
[`URI::URI`](https://github.com/aws/aws-sdk-cpp/blob/9350e3d4dc0ed1c993c3cd501bb4ed40c115ed1a/aws-cpp-sdk-core/source/http/URI.cpp#L33)
[`URI::ParseURIParts`](https://github.com/aws/aws-sdk-cpp/blob/9350e3d4dc0ed1c993c3cd501bb4ed40c115ed1a/aws-cpp-sdk-core/source/http/URI.cpp#L426)

Something is wrong because this call results in only the `Path` being extracted and the `GetQueryString()` returns an empty string. I have confirmed this with logging and a debugger session.
https://github.com/ClickHouse/ClickHouse/blob/2cfe8578b7246404368c423306a7e200f5f6d6a7/src/IO/S3/PocoHTTPClient.cpp#L218

The `versionId=VersionID` has to be appended to the Poco URI manually. This should not be required as the AWS URI API has a routine that creates key-value pairs for the Query string:
[`URI::GetQueryStringParameters`](https://github.com/aws/aws-sdk-cpp/blob/6e854b6a8bc7945f150c3a11551196bda341962a/aws-cpp-sdk-core/source/http/URI.cpp#L279)

**Comment by surahman** [comment]
My suggestion to deal with this issue is to start at the right-hand side of the URI and search for the first `?` that is found using `rfind`. The query string itself cannot contain a `?` and the last `?` will denote the beginning of the query string. I would extract and append this string to the Poco URI instead of using the `GetQueryString`:
https://github.com/ClickHouse/ClickHouse/blob/2cfe8578b7246404368c423306a7e200f5f6d6a7/src/IO/S3/PocoHTTPClient.cpp#L219

I have tested and can confirm that this does append the query string to the Poco URI.

The bucket object naming conventions are [here](https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-keys.html).

**Comment by surahman** [comment]
@alexey-milovidov I finally had some time to look this over and I found that the [`URI`](https://github.com/ClickHouse/ClickHouse/blob/db69ab9d17d1bbb772cc8b2c18db33df6f7502ee/src/IO/S3Common.h#L63) data structure is correctly parsed and that the query string data is correctly contained within the `URI` - but not stored in a data member within the struct. The [`URI Constructor`](https://github.com/ClickHouse/ClickHouse/blob/db69ab9d17d1bbb772cc8b2c18db33df6f7502ee/src/IO/S3Common.cpp#L758) is called before the [HTTP Client Request](https://github.com/ClickHouse/ClickHouse/blob/db69ab9d17d1bbb772cc8b2c18db33df6f7502ee/src/IO/S3/PocoHTTPClient.cpp#L113). There is some code which is executed between the points where the `URI` is collected, the object constructed, and passed to the HTTP Client. This is where the query string part of the URI gets stripped out. I can confirm that the `Aws::Http::HttpRequest` does not contain the query string, so wherever this function is called is from where the query string gets removed.

Could someone please point me to the part of the codebase that handles the input to the parser and splits the URI out of the user-provided input? I can trace the path to the HTTP request from there.

**Comment by surahman** [comment]
This appears to extract the S3 Version ID from the buffer:
https://github.com/ClickHouse/ClickHouse/blob/1f92fb5b40c27271c73f023f873e29744d473a6a/src/Disks/S3/DiskS3.cpp#L393-L410

**Comment by surahman** [comment]
I am trying to locate the URI strings for the tests in `FunctionalStatelessTestReleaseS3` so that I can debug the current issue. I am able to provide and parse an S3 version ID in the query section of the URI without issue when testing locally.

<details><summary>Server Log</summary>

```bash
2022.02.26 16:35:15.481633 [ 451 ] {} <Warning> AWSClient: AWSErrorMarshaller: Encountered Unknown AWSError 'InvalidArgument': Invalid version id specified
2022.02.26 16:35:15.481653 [ 451 ] {} <Error> AWSClient: HTTP response code: 400
Resolved remote host IP address: 
Request ID: 16D783FDEEAC3D94
Exception name: InvalidArgument
Error message: Unable to parse ExceptionName: InvalidArgument Message: Invalid version id specified
13 response headers:
accept-ranges : bytes
connection : close
content-length : 352
content-security-policy : block-all-mixed-content
content-type : application/xml
date : Sun, 27 Feb 2022 02:35:15 GMT
no-gzip-compression : true
server : MinIO
strict-transport-security : max-age=31536000; includeSubDomains
vary : Accept-Encoding
x-amz-request-id : 16D783FDEEAC3D94
x-content-type-options : nosniff
x-xss-protection : 1; mode=block
```

</details>


<details><summary>Test: Release S3 Storage Actions</summary>

```bash
+ curl -v --silent http://localhost:11111
+ grep AccessDenied
<Error><Code>AccessDenied</Code><Message>Access Denied.</Message><Resource>/</Resource><RequestId>16D783FBFA1C9ED5</RequestId><HostId>5688c46b-b067-4346-8692-bc93fb54081d</HostId></Error>
```

```bash
API: GetObject(bucket=test, object=azvfnfoqjymjnhhqvidctnxnapdwoygk, versionId=test/)
Time: 02:35:13 UTC 02/27/2022
DeploymentID: 5688c46b-b067-4346-8692-bc93fb54081d
RequestID: 16D783FD7BF09816
RemoteHost: ::1
Host: localhost:11111
UserAgent: aws-sdk-cpp/1.8.121/S3/Linux/5.11.0-1022-aws x86_64 Clang/13.0.1
Error: invalid UUID length: 5 (uuid.invalidLengthError)
       4: cmd/object-api-options.go:103:cmd.getOpts()
       3: cmd/object-handlers.go:326:cmd.objectAPIHandlers.getObjectHandler()
       2: cmd/object-handlers.go:579:cmd.objectAPIHandlers.GetObjectHandler()
       1: net/http/server.go:2047:http.HandlerFunc.ServeHTTP()
```

</details>

**Comment by surahman** [comment]
@alesapin for some reason I do not seem to be able to trigger the PR Run builds anymore, could you please trigger it?

Pending the passing of all the PR Run tests, this should be ready for review. The only item outstanding is the debug instrumentation which is contained in a single droppable commit. I have left this in place for now in case I have not caught all the bugs and need to debug further.

The code can probably be tightened as I have been discovering where to make changes using stack traces in GDB/LLDB.

**Comment by surahman** [comment]
I do not believe the failing tests are associated with S3, and as such, the PR should now be ready for review.

__Failures:__
- Stateless Tests
  - 00850_global_join_dups
  - 00921_datetime64_compatibility_long
  - 01085_max_distributed_connections
  - 01195_formats_diagnostic_info
  - 01281_group_by_limit_memory_tracking

- Integration Tests (release, Actions)
  - test_postgresql_replica_database_engine_1/test.py::test_concurrent_transactions

**Review by serxa — APPROVED** [review]

**Pull request merged**
