### PR TITLE
Link boost::context library to clickhouse_common_io

### LINKED ISSUE #50381: Linker failed with 23.4, error: undefined symbol: make_fcontext
1. clang & cmake version
```
Ubuntu clang version 16.0.5 (++20230521064343+5729e63ac7b4-1~exp1~20230521184435.94)
cmake version 3.26.4
```

2.  code branch
```
commit edcd8ed14cd6f09a3056a9dac8c1329eb28df9f5 (HEAD -> 23.4, origin/23.4, coding/23.4)
Merge: cb2a4617e54 0ab664b7fbd
Author: Nikita Mikhaylov <mikhaylovnikitka@gmail.com>
Date:   Fri May 26 15:58:16 2023 +0200
```

3.  update submodule
```
git submodule sync
git submodule init
git submodule update -f
git submodule update --init -f
```

4. ninja detail information
```
FAILED: utils/config-processor/config-processor
: && /usr/bin/clang++-16 --target=x86_64-linux-gnu --sysroot=/code/ClickHouse/cmake/linux/../../contrib/sysroot/linux-x86_64/x86_64-linux-gnu/libc --gcc-toolchain=/code/ClickHouse/cmake/linux/../../contrib/sysroot/linux-x86_64 -std=c++20 -fdiagnostics-color=always -Xclang -fuse-ctor-homing -Wno-enum-constexpr-conversion -fsized-deallocation  -gdwarf-aranges -pipe -mssse3 -msse4.1 -msse4.2 -mpclmul -mpopcnt -fasynchronous-unwind-tables -ffile-prefix-map=/code/ClickHouse=. -falign-functions=32 -mbranches-within-32B-boundaries -fdiagnostics-absolute-paths -fstrict-vtable-pointers -Wall -Wextra -Wframe-larger-than=65536 -Weverything -Wpedantic -Wno-zero-length-array -Wno-c++98-compat-pedantic -Wno-c++98-compat -Wno-c++20-compat -Wno-sign-conversion -Wno-implicit-int-conversion -Wno-implicit-int-float-conversion -Wno-ctad-maybe-unsupported -Wno-disabled-macro-expansion -Wno-documentation-unknown-command -Wno-double-promotion -Wno-exit-time-destructors -Wno-float-equal -Wno-global-constructors -Wno-missing-prototypes -Wno-missing-variable-declarations -Wno-padded -Wno-switch-enum -Wno-undefined-func-template -Wno-unused-template -Wno-vla -Wno-weak-template-vtables -Wno-weak-vtables -Wno-thread-safety-negative -Wno-enum-constexpr-conversion -Wno-unsafe-buffer-usage -O2 -g -DNDEBUG -O3 -g -gdwarf-4  -fno-pie --gcc-toolchain=/code/ClickHouse/cmake/linux/../../contrib/sysroot/linux-x86_64 --ld-path=/code/ClickHouse/build_23.4/ld.lld -rdynamic -Wl,--gdb-index -Wl,--build-id=sha1 -no-pie -Wl,-no-pie    -Xlinker --no-undefined src/CMakeFiles/clickhouse_malloc.dir/Common/malloc.cpp.o utils/config-processor/CMakeFiles/config-processor.dir/config-processor.cpp.o -o utils/config-processor/config-processor  src/libclickhouse_new_delete.a  src/Common/Config/libclickhouse_common_config_no_zookeeper_log.a  src/Common/ZooKeeper/libclickhouse_common_zookeeper_no_log.a  src/libclickhouse_common_io.a  contrib/jemalloc-cmake/lib_jemalloc.a  contrib/gwpasan-cmake/lib_gwp_asan.a  base/widechar_width/libwidechar_width.a  contrib/dragonbox-cmake/lib_dragonbox_to_chars.a  contrib/boost-cmake/lib_boost_program_options.a  contrib/re2-cmake/libre2.a  contrib/re2-cmake/libre2_st.a  contrib/libcpuid-cmake/lib_cpuid.a  contrib/abseil-cpp/absl/strings/libabsl_cord.a  contrib/abseil-cpp/absl/strings/libabsl_cordz_info.a  contrib/abseil-cpp/absl/strings/libabsl_cord_internal.a  contrib/abseil-cpp/absl/strings/libabsl_cordz_functions.a  contrib/abseil-cpp/absl/strings/libabsl_cordz_handle.a  contrib/abseil-cpp/absl/hash/libabsl_hash.a  contrib/abseil-cpp/absl/hash/libabsl_city.a  contrib/abseil-cpp/absl/types/libabsl_bad_variant_access.a  contrib/abseil-cpp/absl/hash/libabsl_low_level_hash.a  contrib/abseil-cpp/absl/container/libabsl_raw_hash_set.a  contrib/abseil-cpp/absl/types/libabsl_bad_optional_access.a  contrib/abseil-cpp/absl/container/libabsl_hashtablez_sampler.a  contrib/abseil-cpp/absl/profiling/libabsl_exponential_biased.a  contrib/abseil-cpp/absl/synchronization/libabsl_synchronization.a  contrib/abseil-cpp/absl/debugging/libabsl_stacktrace.a  contrib/abseil-cpp/absl/synchronization/libabsl_graphcycles_internal.a  contrib/abseil-cpp/absl/debugging/libabsl_symbolize.a  contrib/abseil-cpp/absl/base/libabsl_malloc_internal.a  contrib/abseil-cpp/absl/debugging/libabsl_debugging_internal.a  contrib/abseil-cpp/absl/debugging/libabsl_demangle_internal.a  contrib/abseil-cpp/absl/time/libabsl_time.a  contrib/abseil-cpp/absl/strings/libabsl_strings.a  contrib/abseil-cpp/absl/base/libabsl_throw_delegate.a  contrib/abseil-cpp/absl/strings/libabsl_strings_internal.a  contrib/abseil-cpp/absl/base/libabsl_base.a  contrib/abseil-cpp/absl/base/libabsl_spinlock_wait.a  -lrt  contrib/abseil-cpp/absl/base/libabsl_raw_logging_internal.a  contrib/abseil-cpp/absl/base/libabsl_log_severity.a  contrib/abseil-cpp/absl/numeric/libabsl_int128.a  contrib/abseil-cpp/absl/time/libabsl_civil_time.a  contrib/abseil-cpp/absl/time/libabsl_time_zone.a  contrib/c-ares-cmake/lib_c-ares.a  contrib/aws-cmake/lib_aws.a  contrib/brotli-cmake/lib_brotli.a  contrib/snappy-cmake/lib_snappy.a  contrib/liburing-cmake/lib_liburing.a  contrib/minizip-ng-cmake/lib_minizip.a  contrib/zstd-cmake/lib_zstd.a  contrib/xz-cmake/lib_liblzma.a  contrib/bzip2-cmake/lib_bzip2.a  base/base/libcommon.a  contrib/boost-cmake/lib_boost_system.a  contrib/cityhash102/lib_cityhash.a  base/poco/NetSSL_OpenSSL/lib_poco_net_ssl.a  base/poco/Net/lib_poco_net.a  base/poco/Crypto/lib_poco_crypto.a  contrib/boringssl-cmake/lib_ssl.a  contrib/boringssl-cmake/lib_crypto.a  -lpthread  base/poco/Util/lib_poco_util.a  base/poco/JSON/lib_poco_json.a  base/poco/JSON/lib_poco_json_pdjson.a  contrib/replxx-cmake/lib_replxx.a  contrib/cctz-cmake/lib_cctz.a  -Wl,--whole-archive /code/ClickHouse/build_23.4/contrib/cctz-cmake/libtzdata.a -Wl,--no-whole-archive  contrib/fmtlib-cmake/lib_fmt.a  base/poco/XML/lib_poco_xml.a  base/poco/Foundation/lib_poco_foundation.a  contrib/double-conversion-cmake/lib_double-conversion.a  contrib/zlib-ng-cmake/lib_zlib.a  contrib/lz4-cmake/lib_lz4.a  base/poco/Foundation/lib_poco_foundation_pcre.a  base/poco/XML/lib_poco_xml_expat.a  src/Common/StringUtils/libstring_utils.a  contrib/yaml-cpp-cmake/lib_yaml_cpp.a  base/glibc-compatibility/libglibc-compatibility.a  base/glibc-compatibility/memcpy/libmemcpy.a  base/glibc-compatibility/libglibc-compatibility.a  base/glibc-compatibility/memcpy/libmemcpy.a  -Wl,--start-group  contrib/libcxx-cmake/libcxx.a  contrib/libcxxabi-cmake/libcxxabi.a  contrib/libunwind-cmake/libunwind.a  -Wl,--end-group  -nodefaultlibs /usr/lib/llvm-16/lib/clang/16/lib/linux/libclang_rt.builtins-x86_64.a  -lc -lm -lrt -lpthread -ldl && :
ld.lld-16: error: undefined symbol: make_fcontext
>>> referenced by fiber_fcontext.hpp:168 (./contrib/boost/boost/context/fiber_fcontext.hpp:168)
>>>               AsyncTaskExecutor.cpp.o:(DB::AsyncTaskExecutor::AsyncTaskExecutor(std::__1::unique_ptr<DB::AsyncTask, std::__1::default_delete<DB::AsyncTask>>)) in archive src/libclickhouse_common_io.a
>>> referenced by fiber_fcontext.hpp:168 (./contrib/boost/boost/context/fiber_fcontext.hpp:168)
>>>               AsyncTaskExecutor.cpp.o:(DB::AsyncTaskExecutor::createFiber()) in archive src/libclickhouse_common_io.a
>>> referenced by fiber_fcontext.hpp:168 (./contrib/boost/boost/context/fiber_fcontext.hpp:168)
>>>               AsyncTaskExecutor.cpp.o:(DB::AsyncTaskExecutor::restart()) in archive src/libclickhouse_common_io.a

ld.lld-16: error: undefined symbol: jump_fcontext
>>> referenced by fiber_fcontext.hpp:171 (./contrib/boost/boost/context/fiber_fcontext.hpp:171)
>>>               AsyncTaskExecutor.cpp.o:(DB::AsyncTaskExecutor::AsyncTaskExecutor(std::__1::unique_ptr<DB::AsyncTask, std::__1::default_delete<DB::AsyncTask>>)) in archive src/libclickhouse_common_io.a
>>> referenced by fiber_fcontext.hpp:171 (./contrib/boost/boost/context/fiber_fcontext.hpp:171)
>>>               AsyncTaskExecutor.cpp.o:(DB::AsyncTaskExecutor::createFiber()) in archive src/libclickhouse_common_io.a
>>> referenced by fiber_fcontext.hpp:279 (./contrib/boost/boost/context/fiber_fcontext.hpp:279)
>>>               AsyncTaskExecutor.cpp.o:(DB::AsyncTaskExecutor::resume()) in archive src/libclickhouse_common_io.a
>>> referenced 5 more times

ld.lld-16: error: undefined symbol: ontop_fcontext
>>> referenced by fiber_fcontext.hpp:251 (./contrib/boost/boost/context/fiber_fcontext.hpp:251)
>>>               AsyncTaskExecutor.cpp.o:(DB::AsyncTaskExecutor::AsyncTaskExecutor(std::__1::unique_ptr<DB::AsyncTask, std::__1::default_delete<DB::AsyncTask>>)) in archive src/libclickhouse_common_io.a
>>> referenced by fiber_fcontext.hpp:251 (./contrib/boost/boost/context/fiber_fcontext.hpp:251)
>>>               AsyncTaskExecutor.cpp.o:(DB::AsyncTaskExecutor::createFiber()) in archive src/libclickhouse_common_io.a
>>> referenced by fiber_fcontext.hpp:251 (./contrib/boost/boost/context/fiber_fcontext.hpp:251)
>>>               AsyncTaskExecutor.cpp.o:(DB::AsyncTaskExecutor::resume()) in archive src/libclickhouse_common_io.a
>>> referenced 11 more times
clang: error: linker command failed with exit code 1 (use -v to see invocation)
[3246/3284] Building CXX object src/AggregateFunctions/CMakeFiles/clickhouse_aggregate_functions.dir/AggregateFunctionSumMap.cpp.o
ninja: build stopped: subcommand failed.
[1]+  Done                    clear
```

### PR DESCRIPTION
**Pull request by marising**
### Changelog category (leave one):

- Build/Testing/Packaging Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Link `boost::context` library to `clickhouse_common_io`. This closes: #50381

### CODE REVIEW

**Comment by robot-ch-test-poll3** [comment]
This is an automated comment for commit 8ce56dfe4616dcaf2638ffc8f1ef7c35718fea06 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/50385/8ce56dfe4616dcaf2638ffc8f1ef7c35718fea06/ci_running.html)
The overall status of the commit is 🔴 failure

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🔴 failure</td></tr>
</table>

**Review by nikitamikhaylov — APPROVED** [review]

**Comment by marising** [comment]
> But we already link boost::context library to clickhouse_common_io: https://github.com/ClickHouse/ClickHouse/blob/master/src/CMakeLists.txt#L556

OK，branch 23.4 no link boost::context, branch master have it

**Comment by Avogar** [comment]
Did you try to build using clang-15? We started using clang-16 in 23.5 afaik

**Comment by marising** [comment]
> Did you try to build using clang-15? We started using clang-16 in 23.5 afaik

#50381

I build branch 23.4,  first use clang 15 and cmake 3.20, make error: undefined symbol: make_fcontext , then i update to clang version 16.0.5 and cmake version 3.26.4,  found the same error.

**Pull request merged**
