### PR TITLE
Update AggregatingTransform.cpp

### PR DESCRIPTION
**Pull request by markpapadakis**
Replaced redundant call to chunk.getNumRows() with local var.

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Not For Changelog

### CODE REVIEW

**Comment by amosbird** [comment]
Constant variables is usually unnecessary (compared to pointers and references).

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
LGTM

**Comment by markpapadakis** [comment]
This apparently failed because of PR description quality control issues(1) and because of the following build error which I don't really think it has anything at all to do with the proposed change(2)
image

Re: (1) should I close the PR and open a new one? Re: (2) is there something I should perhaps do to help with it?

**Comment by alexey-milovidov** [comment]
This is an "exotic" build type. Unfortunately, it was broken in master at this specific moment.

**Pull request merged**
