### PR TITLE
relax condition in test, remove unused counters

### PR DESCRIPTION
**Pull request by CheSema**
Fix flakiness like that 

https://d1k2gkhrlfqv31.cloudfront.net/clickhouse-test-reports-private/12793/787a9137df53d6c46f0b6f47ba21b23f49f8e749/stateless_tests__asan__distributed_cache__meta_storage_in_keeper__s3_storage__%5B1_3%5D.html

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
...

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Review by nickitat — APPROVED** [review]

**Comment by robot-ch-test-poll** [comment]
*This is an automated comment for commit 36468c528debe37bb6023a37d7ed9b93e7b56836 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/66730/36468c528debe37bb6023a37d7ed9b93e7b56836/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/4b0ef8edce0eca049bcdb8938fd9aecb0e8c2377/docs_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Comment by alexey-milovidov** [comment]
A few tests have failed after this change.

**Comment by CheSema** [comment]
> A few tests have failed after this change.

Not exactly. Server died. I did not find any logs for investigation.

**Comment by alexey-milovidov** [comment]
It didn't help: https://s3.amazonaws.com/clickhouse-test-reports/0/8735076fbf160cae62155c3cb9d3cb40f79fba00/stateless_tests__debug__s3_storage__[1_2].html

**Pull request merged**
