### PR TITLE
Temporarily disable sending logs from CI to the cloud

### PR DESCRIPTION
**Pull request by tavplubix**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

See https://github.com/ClickHouse/ClickHouse/issues/53408 and https://s3.amazonaws.com/clickhouse-test-reports/0/c85e2eca31949364172ee43df1f5bf5cac37824b/stateless_tests__debug__[5_5].html 

Also, @Felixoid has some concerns about this functionality

### CODE REVIEW

**Comment by robot-clickhouse** [comment]
This is an automated comment for commit 1a36532585c9c69fbcedd0ba393c955f0e46f54b with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/53488/1a36532585c9c69fbcedd0ba393c955f0e46f54b/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Comment by Felixoid** [comment]
I've submitted reworked system in #53491, let's see how it will work

Although, this would work too I think

**Comment by Felixoid** [comment]
I see, the issue you are referencing is completely different. Well, yes, this is much radical solution

**Comment by Felixoid** [comment]
just in case, my changes won't address things like hanging tables sending. But it should solve the issue with broken CI for external contributors

**Comment by azat** [comment]
I don't see actually how #53491 will help with the original problem, any clue?

**Comment by Felixoid** [comment]
It's fixing completely broken CI for external contributors. Now everything with CI logs just fails, because secrets aren't propagated to the PRs from forks

**Comment by azat** [comment]
The problem that I was referring here by "original" is that server shutdown takes too long.

>It's fixing completely broken CI for external contributors. Now everything with CI logs just fails, because secrets aren't propagated to the PRs from forks

Hm, I'm external contributor and CI more or less OK - #53501
And I do see needable check in the code - https://github.com/ClickHouse/ClickHouse/blob/ec7daed52fdc4bd56c37db89e1650623858e0eeb/docker/test/stateless/run.sh#L120
I remember that it was broken because of broken `sed`, that had been fixed in #53456

**Pull request closed without merging**
