### PR TITLE
add vscode settings to ignore

### PR DESCRIPTION
**Pull request by artpaul**

### CODE REVIEW

**Comment by vladimir-golovchenko** [comment]
@alexey-milovidov 

I think some IDE settings related to debugging should not be ignored.

Consider for example VSCode and settings for local debug (defined in *.vscode/launch.json*):

```json
{
    "version": "0.2.0",
    "configurations": [    
        {
            "name": "debugging of local ClickHouse server",
            "type": "cppdbg",
            "request": "attach",
            "program": "${workspaceFolder}/build/programs/clickhouse-server",
            "processId": "${command:pickProcess}",
            "MIMode": "gdb",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                },
                {
                    "description": "ignore SIGUSR1 signal",
                    "text": "handle SIGUSR1 nostop noprint pass"
                }
            ]            
        }
    ]
}
```

These config doesn't contain any user-specific settings and I think it can be commited to repo to ease live of begiiner developers.
Moreover I would mention it in official doc.

What do you think about it?

**Comment by alexey-milovidov** [comment]
I'm in doubt. There are large number of IDEs and adding all configs as top level files/directories does not seem viable.

**Comment by vladimir-golovchenko** [comment]
OK, I agree it is a bad practice.
What about describing it in the official doc?

**Comment by alexey-milovidov** [comment]
It will be good to have, let's do it.

**Comment by vladimir-golovchenko** [comment]
@alexey-milovidov  sorry to bother you again, 

do make sense to add any tools settings to separate folder *tools* as done in https://github.com/chromium/chromium/tree/master/tools (where there are settings for vscode, vim, sublime, etc.)?

**Comment by alexey-milovidov** [comment]
We don't have the folder `tools` right now, but let's add it as an experiment :)
If my collegues would not like it, we will just move files somewhere else.

**Pull request merged**
