### PR TITLE
ClickHouse's boringssl module updated to the official version of the FIPS compliant.

### PR DESCRIPTION
**Pull request by ghost**
Changelog category (leave one):
- Backward Incompatible Change

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Updated the BoringSSL module to the official FIPS compliant version. This makes ClickHouse FIPS compliant.

> Information about CI checks: https://clickhouse.tech/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by Meena-Renganathan** [comment]
Patches specifically for the boringssl module has not been applied. If we try to modify the boringssl module, then it breaks the FIPS validation. 

Please let us know any comments/suggestions.

**Comment by alexey-milovidov** [comment]
It does not build.

**Comment by Meena-Renganathan** [comment]
> It does not build.

I will check and fix it.

**Comment by Meena-Renganathan** [comment]
Addressing issue#[34238](https://github.com/ClickHouse/ClickHouse/issues/34238)

Pull request # [13](https://github.com/ClickHouse/boringssl/pull/13) has been raised to update the broingssl module in the ClickHouse/boringssl repository.

**Comment by Meena-Renganathan** [comment]
Hi @alexey-milovidov,

Build failed due to the latest boringssl module has not been fetched.

Now, the PR#[14](https://github.com/ClickHouse/boringssl/pull/14) has been merged into the ClickHouse/boringssl MergeWithUpstream branch. Build for this PR needs to be restarted. I'm not sure how to do that. 

Could you please help me in doing that?

**Comment by alexey-milovidov** [comment]
Empty commit is enough to restart the tests.

**Comment by alexey-milovidov** [comment]
You can reset the reference of the submodule to the branch.

**Comment by Meena-Renganathan** [comment]
Hi @alexey-milovidov,

Though the functional test has been completed successfully, the check is failing. Like in case of FunctionalStatelessTestAsan0, the log shows as below:

2022-04-19 18:50:44 
[2433](https://github.com/ClickHouse/ClickHouse/runs/6085912066?check_suite_focus=true#step:6:2433)
2022-04-19 18:50:44 247 tests passed. 3 tests skipped. 1256.72 s elapsed (MainProcess).

Not sure why the check is failing. It's not related with the PR change,

**Comment by Meena-Renganathan** [comment]
Reason for the failure of the test 01318_encrypt is the latest boringssl doesn't support AES 192 and 256 encrypt functions. We didn't modify the boringssl module because that breaks it's FIPS validation.

**Comment by Meena-Renganathan** [comment]
@alexey-milovidov, Please let us know your thoughts.

**Comment by alexey-milovidov** [comment]
@Meena-Renganathan The tests for `aes-192-cfb128` and `aes-256-cfb128` should be removed.

**Comment by Meena-Renganathan** [comment]
Hi @alexey-milovidov, 

Removed the tests and ensure the current failure in the pipeline has nothing to do with the changes.

Please review.

**Comment by alexey-milovidov** [comment]
The queries still present in performance test: https://s3.amazonaws.com/clickhouse-test-reports/35914/5b19d63426c27c0f95aec687a5ff341d060fa247/performance_comparison__actions__[1/4]/report.html

**Comment by alexey-milovidov** [comment]
Assertion failed in functional tests, need attention from @tavplubix

**Comment by alexey-milovidov** [comment]
There is a signal 11 (segfault) in stress test under thread sanitizer: https://s3.amazonaws.com/clickhouse-test-reports/35914/5b19d63426c27c0f95aec687a5ff341d060fa247/stress_test__thread__actions_/clickhouse-server.err.log

**Comment by Meena-Renganathan** [comment]
Hi @alexey-milovidov, Removed the corresponding tests from the performance.

I think all the other failures are not related with the changes.

Do I need to something else on my side?

**Comment by alexey-milovidov** [comment]
> Stress test (debug, actions)

Fixed in #36660

**Comment by alexey-milovidov** [comment]
@Meena-Renganathan 

We have failed integration tests for GRPC protocol.
And it can be related to the changes: https://s3.amazonaws.com/clickhouse-test-reports/35914/98543a9a3f9a55ed3874314be0e9349d4f494ad6/integration_tests__asan__actions__[1/3].html

**Comment by alexey-milovidov** [comment]
For test_postgresql_replica https://s3.amazonaws.com/clickhouse-test-reports/35914/98543a9a3f9a55ed3874314be0e9349d4f494ad6/integration_tests__thread__actions__[4/4].html
please merge with master.

**Comment by tavplubix** [comment]
> Assertion failed in functional tests, need attention from @tavplubix

It's something weird with `ReplicatedMergeTreePartCheckThread`/`BackgroundSchedulePool`. Part was not found because table was dropped:
```
zgrep -Fa "7d91ed72-abe8-49ac-a691-03368e9c7a28" clickhouse-server.log.gz
2022.04.25 17:46:43.749265 [ 42423 ] {7d91ed72-abe8-49ac-a691-03368e9c7a28} <Debug> executeQuery: (from [::1]:33606) (comment: 00993_system_parts_race_condition_drop_zookeeper.sh) DROP TABLE IF EXISTS alter_table_5;
2022.04.25 17:46:43.749685 [ 42423 ] {7d91ed72-abe8-49ac-a691-03368e9c7a28} <Trace> ContextAccess (default): Access granted: DROP TABLE ON test_ysj42p.alter_table_5
2022.04.25 17:46:43.749859 [ 42423 ] {7d91ed72-abe8-49ac-a691-03368e9c7a28} <Information> test_ysj42p.alter_table_5 (1e9d52a2-6c40-4403-96ba-a3dbe098c159): Stopped being leader
2022.04.25 17:46:43.750021 [ 42423 ] {7d91ed72-abe8-49ac-a691-03368e9c7a28} <Trace> test_ysj42p.alter_table_5 (ReplicatedMergeTreeRestartingThread): Restarting thread finished
2022.04.25 17:46:43.777143 [ 42423 ] {7d91ed72-abe8-49ac-a691-03368e9c7a28} <Trace> test_ysj42p.alter_table_5 (ReplicatedMergeTreeRestartingThread): Waiting for threads to finish
2022.04.25 17:46:44.251931 [ 42423 ] {7d91ed72-abe8-49ac-a691-03368e9c7a28} <Trace> test_ysj42p.alter_table_5 (ReplicatedMergeTreeRestartingThread): Threads finished
2022.04.25 17:46:44.252103 [ 42423 ] {7d91ed72-abe8-49ac-a691-03368e9c7a28} <Trace> test_ysj42p.alter_table_5 (PartMovesBetweenShardsOrchestrator): PartMovesBetweenShardsOrchestrator thread finished
2022.04.25 17:46:44.252666 [ 42423 ] {7d91ed72-abe8-49ac-a691-03368e9c7a28} <Debug> DatabaseCatalog: Waiting for table 1e9d52a2-6c40-4403-96ba-a3dbe098c159 to be finally dropped
2022.04.25 17:46:45.913229 [ 42423 ] {7d91ed72-abe8-49ac-a691-03368e9c7a28} <Debug> MemoryTracker: Peak memory usage (for query): 2.03 MiB.
```

```
zgrep -Fa "[ 577 " clickhouse-server.log.gz | tail -20
2022.04.25 17:46:43.693641 [ 577 ] {} <Debug> test_ysj42p.alter_table_5 (ReplicatedMergeTreeQueue): Pulled 1 entries to queue.
2022.04.25 17:46:43.707895 [ 577 ] {} <Trace> test_ysj42p.alter_table_5 (1e9d52a2-6c40-4403-96ba-a3dbe098c159): Will drop empty part 2_9_9_0
2022.04.25 17:46:43.708046 [ 577 ] {} <Trace> test_ysj42p.alter_table_5 (1e9d52a2-6c40-4403-96ba-a3dbe098c159): Will try to insert a log entry to DROP_RANGE for part 2_9_9_0
2022.04.25 17:46:43.936966 [ 577 ] {} <Debug> test_ysj42p.alter_table_5 (ReplicatedMergeTreeQueue): Pulling 1 entries to queue: log-0000000264 - log-0000000264
2022.04.25 17:46:43.988929 [ 577 ] {} <Test> test_ysj42p.alter_table_5 (ReplicatedMergeTreeQueue): Insert entry queue-0000000234 to queue with type DROP_RANGE with virtual parts []
2022.04.25 17:46:43.989123 [ 577 ] {} <Test> test_ysj42p.alter_table_5 (ReplicatedMergeTreeQueue): Removing part 4_9_9_0 from mutations (remove_part: true, remove_covered_parts: true)
2022.04.25 17:46:43.990081 [ 577 ] {} <Debug> test_ysj42p.alter_table_5 (ReplicatedMergeTreeQueue): Pulled 1 entries to queue.
2022.04.25 17:46:44.008230 [ 577 ] {} <Trace> test_ysj42p.alter_table_5 (1e9d52a2-6c40-4403-96ba-a3dbe098c159): Will drop empty part 2_10_10_0
2022.04.25 17:46:44.009371 [ 577 ] {} <Error> test_ysj42p.alter_table_5 (ReplicatedMergeTreeCleanupThread): void DB::ReplicatedMergeTreeCleanupThread::run(): Code: 242. DB::Exception: Table is in readonly mode (replica path: /clickhouse/tables/00993_system_parts_race_condition_drop_zookeeper_test_ysj42p/alter_table/replicas/r_5). (TABLE_IS_READ_ONLY), Stack trace (when copying this message, always include the lines below):
2022.04.25 17:46:44.009831 [ 577 ] {} <Trace> test_ysj42p.alter_table_5 (ReplicatedMergeTreeCleanupThread): Execution took 7824 ms.
2022.04.25 17:46:45.403144 [ 577 ] {} <Warning> test_ysj42p.alter_table_5 (ReplicatedMergeTreePartCheckThread): Checking part 2_14_14_0
2022.04.25 17:46:45.429485 [ 577 ] {} <Trace> test_ysj42p.alter_table_5 (ReplicatedMergeTreePartCheckThread): Part 2_14_14_0 in zookeeper: false, locally: false
2022.04.25 17:46:45.429634 [ 577 ] {} <Warning> test_ysj42p.alter_table_5 (ReplicatedMergeTreePartCheckThread): Checking if anyone has a part 2_14_14_0 or covering part.
2022.04.25 17:46:45.625933 [ 577 ] {} <Error> test_ysj42p.alter_table_5 (ReplicatedMergeTreePartCheckThread): No replica has part covering 2_14_14_0 and a merge is impossible: we didn't find smaller parts with either the same min block or the same max block.
2022.04.25 17:46:45.626190 [ 577 ] {} <Information> test_ysj42p.alter_table_5 (1e9d52a2-6c40-4403-96ba-a3dbe098c159): Going to replace lost part 2_14_14_0 with empty part
2022.04.25 17:46:45.626754 [ 577 ] {} <Debug> DiskLocal: Reserving 1.00 MiB on disk `default`, having unreserved 101.97 GiB.
2022.04.25 17:46:45.639383 [ 577 ] {} <Trace> MergedBlockOutputStream: filled checksums 2_14_14_0 (state Temporary)
2022.04.25 17:46:45.644938 [ 577 ] {} <Trace> test_ysj42p.alter_table_5 (1e9d52a2-6c40-4403-96ba-a3dbe098c159): Renaming temporary part tmp_empty_2_14_14_0 to 2_14_14_0.
2022.04.25 17:46:45.830598 [ 577 ] {} <Debug> test_ysj42p.alter_table_5 (1e9d52a2-6c40-4403-96ba-a3dbe098c159): Undoing transaction. Removing parts: 2_14_14_0.
2022.04.25 17:46:45.912366 [ 577 ] {} <Fatal> : Logical error: 'Part 2_14_14_0 (state PreActive) not found in data_parts'.
```

All table's threads must have been stopped at this moment
```
2022.04.25 17:46:44.251931 [ 42423 ] {7d91ed72-abe8-49ac-a691-03368e9c7a28} <Trace> test_ysj42p.alter_table_5 (ReplicatedMergeTreeRestartingThread): Threads finished
```
https://github.com/ClickHouse/ClickHouse/blob/118e94523c74461882f15e966208134884190520/src/Storages/MergeTree/ReplicatedMergeTreeRestartingThread.cpp#L377-L387
But `ReplicatedMergeTreePartCheckThread` (more precisely, the task in `BackgroundSchedulePool`) continued work for some reason (a bug in `BackgroundSchedulePool`?):
```
2022.04.25 17:46:45.403144 [ 577 ] {} <Warning> test_ysj42p.alter_table_5 (ReplicatedMergeTreePartCheckThread): Checking part 2_14_14_0
```

I have no ideas how is it possible, will try to debug.

**Comment by Meena-Renganathan** [comment]
> @Meena-Renganathan
> 
> We have failed integration tests for GRPC protocol. And it can be related to the changes: [https://s3.amazonaws.com/clickhouse-test-reports/35914/98543a9a3f9a55ed3874314be0e9349d4f494ad6/integration_tests__asan__actions__[1/3].html](https://s3.amazonaws.com/clickhouse-test-reports/35914/98543a9a3f9a55ed3874314be0e9349d4f494ad6/integration_tests__asan__actions__%5B1/3%5D.html)

Hi @alexey-milovidov,
After the merge with master, there is no failure observed in the GRPC integration test. I think all the other failures not related with the changes.

**Comment by tavplubix** [comment]
> Looks like there are no related failures and this PR is ready tada But let's also ask @tavplubix to take a look why Stateless tests with DatabaseReplicated timed out.

It's because the second `clickhouse-server` failed to start:
```
zgrep -Fa Error clickhouse-server1.log.gz
2022.04.28 18:46:54.564846 [ 1143 ] {} <Test> AWSClient: AWSErrorMarshaller: Error response is <?xml version="1.0"?>
<Error>
</Error>
2022.04.28 18:46:54.564861 [ 1143 ] {} <Warning> AWSClient: AWSErrorMarshaller: Encountered AWSError 'NoSuchKey': The specified key does not exist.
2022.04.28 18:46:54.564886 [ 1143 ] {} <Error> AWSClient: HTTP response code: 404
Error message: The specified key does not exist.
2022.04.28 18:46:54.565340 [ 478 ] {} <Error> virtual DB::WriteIndirectBufferFromRemoteFS::~WriteIndirectBufferFromRemoteFS(): Code: 499. DB::Exception: The specified key does not exist. (S3_ERROR), Stack trace (when copying this message, always include the lines below):
2022.04.28 18:46:54.565728 [ 478 ] {} <Error> void DB::IDiskRemote::Metadata::load(): Code: 107. DB::ErrnoException: Cannot open file /var/lib/clickhouse1/disks/s3_cache/test_acl, errno: 2, strerror: No such file or directory. (FILE_DOESNT_EXIST), Stack trace (when copying this message, always include the lines below):
2022.04.28 18:46:55.954715 [ 561 ] {} <Error> RaftInstance: failed to accept a rpc connection due to error 125
2022.04.28 18:47:19.480414 [ 478 ] {} <Error> Application: DB::Exception: Failed to read metadata file: test_acl
```

cc: @kssenii

**Comment by filimonov** [comment]
Reverted (see https://github.com/ClickHouse/ClickHouse/pull/38201#issuecomment-1385081146 )

**Pull request merged**
