### PR TITLE
Revert "Fix non joined stream structure "

### PR DESCRIPTION
**Pull request by alexey-milovidov**
Reverts ClickHouse/ClickHouse#27217

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
@azat It did not help.

**Comment by azat** [comment]
@alexey-milovidov But the failure is different (and stress tests had been passed).

**Comment by alexey-milovidov** [comment]
Should be fixed by https://github.com/ClickHouse/ClickHouse/pull/27516

**Comment by alexey-milovidov** [comment]
@vdimir Is the query above also fixed?

**Comment by vdimir** [comment]
> @vdimir Is the query above also fixed?

Yes, it works after merging #27516

**Pull request closed without merging**
