### PR TITLE
Fix bug on mutations with subcolumns of type JSON in predicates of UPDATE and DELETE queries.

### LINKED ISSUE #40990: Delete rows bug for JSON column type
clickhouse version 22.8
doesn't delete row from table using alter table delete command

create table query:
```
CREATE TABLE logs
(
    datetime DEFAULT now() Codec(DoubleDelta, LZ4),
    message JSON
)
ENGINE = MergeTree
order by datetime;
```

insert query:
```
INSERT INTO logs(message) VALUES ('{"a": 2, "b": { "c": 22, "d": [12, 122, 13] }, "f": "a"}');
```

delete query:
```
alter table logs delete where message.f = 'a';
```

error from select * from system.mutations;
```
Code: 47. DB::Exception: Missing columns: 'message.f' while processing query: 'SELECT count() WHERE (message.f = 'a') OR (message.f = 'a')', required columns: 'message.f', maybe you meant: ['message']. (UNKNOWN_IDENTIFIER) (version 22.3.8.40.altinitystable (altinity build))
```

### PR DESCRIPTION
**Pull request by VanDarkholme7**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Allow to use JSON subcolumns in predicates of UPDATE and DELETE queries.

TODO: This won't work when there are missing subcolumns in different shards. 

Fixes #40990.

### CODE REVIEW

**Comment by robot-ch-test-poll4** [comment]
This is an automated comment for commit f71e41f279f5ffea4bff1a5d1014e223c284ee01 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/53442/f71e41f279f5ffea4bff1a5d1014e223c284ee01/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Comment by VanDarkholme7** [comment]
@CurtizJ I wonder why most of the PullRequestCI checks were cancelled, is there something wrong?

**Comment by Felixoid** [comment]
@CurtizJ I've walked around and seen the strange canceled workflow. Did you press a manual approve after/before adding `can be tested`?

**Comment by CurtizJ** [comment]
@Felixoid 
Yes, I did.

**Comment by Felixoid** [comment]
Unfortunately, the lambda restarts the running workflow if it's already running when the `can be tested` is added. To do so, it cancels the current and then waits for its finish to restart. But because of nice and fast GH actions, from time to time, 2 minutes is not enough.

**Pull request closed without merging**
