### PR TITLE
Allow different types in avgWeighted. Allow avg and avgWeighed to operate on extended integral types.

### PR DESCRIPTION
**Pull request by myrrc**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Backward-incompatible change

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Allow using extended integer types (`Int128`, `Int256`, `UInt256`) in `avg` and `avgWeighted` functions. Also allow using different types (integer, decimal, floating point) for value and for weight in `avgWeighted` function. This is a backward-incompatible change: now the `avg` and `avgWeighted` functions always return `Float64` (as documented). Before this change the return type for `Decimal` arguments was also `Decimal`.

1. Allows to use different types in `avgWeighted()` if each is either integral, decimal, or floating-point.

**Example:**
Before PR e.g.:

```sql
SELECT avgWeighted(a, b) FROM 
(
    SELECT a, b
    FROM generateRandom('a Float32, b Float64')
    LIMIT 1
)
```

Results in
```
 DB::Exception: Different types Float32 and Float64 of arguments for aggregate function avgWeighted. 
```
After the query is valid.

2. Allows to use extended integral types (i.e. Int128, Int256,  UInt256) in `avg` and `avgWeighted`.

**Other changes made in this PR:**

- Added some comments to CMake files (avro and ssl).
- Added the -DUSE_UNWIND flag to recommended in CMake docs (as users usually want stack traces).
- Added the output of enabled ClickHouse modes in CMake.
- Removed is_POD from ColumnDecimal as all the wide integers may be safely placed into DecimalPaddedPODArray.
- Made some IDataType methods constexpr.
- Fixed some typos in clickhouse-test.
- Added the tests for avg and avgWeighted, corrected other test to reflect changed behaviour.
- Corrected the docs for the changed functions (always returning Float64, NaN if input is empty).
- Fixed some UBs in the wide int library, that lead to invalid computations.

**Warning!** This is a backward incompatible change. Now the `avg` and `avgWeighted` functions always return Float64 as a result (as in the docs), before this PR the return type for Decimal arguments was also Decimal.

If someone, despite to the docs, was using the result of avg as a Decimal, he would get a CAST error (as Float64 canot be implicitly converted to Decimal).

### CODE REVIEW

**Comment by myrrc** [comment]
00840_long_concurrent_select_and_drop_deadlock is flapping

**Comment by myrrc** [comment]
Depends on https://github.com/cerevra/int/pull/24 (error in UBSan in functional stateless tests and stress test (thread and undefined).

**Comment by myrrc** [comment]
01459_manual_write_to_replicas not related to the PR.

**Comment by myrrc** [comment]
This PR depends on  https://github.com/ClickHouse/ClickHouse/pull/16986/files

**Comment by myrrc** [comment]
Hi @akuzm, is there any news about the review?

**Comment by akuzm** [comment]
> Hi @akuzm, is there any news about the review?

Didn't have a chance too look at this last week because I was on support duty. Trying to reproduce the perf test failure now, without success.

**Comment by myrrc** [comment]
Something strange is happening with the performance tests in https://github.com/ClickHouse/ClickHouse/pull/17100 :
They show about 8x times slowdown on the patched ClickHouse server, which I can't reproduce.
Attaching my local perf.tests results.
[clean_test.txt](https://github.com/ClickHouse/ClickHouse/files/5555664/clean_test.txt)
[patched_perf.txt](https://github.com/ClickHouse/ClickHouse/files/5555666/patched_perf.txt)

**Comment by myrrc** [comment]
Looks like the main performance difference is because of `Memory` instead of `MergeTree` in the test.
Local perf tests after akuzm patch resemble the slowdown.
[clean_akuzm_perf.txt](https://github.com/ClickHouse/ClickHouse/files/5555841/clean_akuzm_perf.txt)
[patched_akuzm_perf.txt](https://github.com/ClickHouse/ClickHouse/files/5555842/patched_akuzm_perf.txt)

**Comment by myrrc** [comment]
Still trying to figure out why the CI thinks the perftests slowed down, here are the flamegraphs for the both of the servers.
[patched.svg.txt](https://github.com/ClickHouse/ClickHouse/files/5573618/patched.svg.txt)
[clean.svg.txt](https://github.com/ClickHouse/ClickHouse/files/5574044/clean.svg.txt)

**Comment by akuzm** [comment]
I can reproduce the slowdown for query no. 9 locally:
```
display-name	9	SELECT avgWeighted(num_u, num_u) FROM perf_avg FORMAT Null
prewarm	9	avg_weighted.query9.prewarm0	0	2.5509021282196045
prewarm	9	avg_weighted.query9.prewarm0	1	4.268539190292358
query	9	avg_weighted.query9.run0	0	2.552407741546631
query	9	avg_weighted.query9.run0	1	4.382078409194946
...
diff	9	2.4934298992156982	4.326869487762451	0.7353082551562634	1.1907701830216855e-11
```
I can also confirm these numbers with `clickhouse-client --time --query "SELECT avgWeighted(num_u, num_u) FROM perf_avg settings max_threads = 1"`


The query no. 5 just gives weirdly varying results, and `clickhouse-client --time` gives the same time for both servers. Will investigate.

**Review by jman1973 — APPROVED** [review]

**Comment by myrrc** [comment]
> I can reproduce the slowdown for query no. 9 locally:

The query 9 may be slowed down due to the conversion from Decimal into Float64: the unpatched version's output type with Decimal input was Decimal, now it's Float64 to keep everything consistent.

**Comment by myrrc** [comment]
So, the general query slowdown was because of perf.py bug.

**Comment by myrrc** [comment]
@akuzm Looks like all of the tests (excluding the typo in avg_weighted_long) have successfully passed.

**Review by akuzm — APPROVED** [review]
Everyting looks good now, but I have to fix tests in Arcadia before merging (because avg now returns float).

**Comment by akuzm** [comment]
Now we're having performance problems again: https://clickhouse-test-reports.s3.yandex.net/15419/1a9c3135291ef8c0b468c7bb58b08d886ae6f10d/performance_comparison/report.html#changes-in-performance

But before that it was OK and even improved, and the code didn't change: https://clickhouse-test-reports.s3.yandex.net/15419/b7e94b487c91674064b9e3bf7d59ed959953f586/performance_comparison/report.html#changes-in-performance

Not sure what's going on there, let's restart it the third time.

Meanwhile, I fixed the Arcadia build, and other test failures are not related.

**Comment by akuzm** [comment]
I looked at some flame graphs of the regression we've seen here https://clickhouse-test-reports.s3.yandex.net/15419/1a9c3135291ef8c0b468c7bb58b08d886ae6f10d/performance_comparison/report.html#changes-in-performance

They don't make sense, let's merge and observe how this test behaves.

**Comment by alexey-milovidov** [comment]
@myrrc @akuzm A bug has been introduced: #31768

**Pull request merged**
