### PR TITLE
Set compression method and level for backup writer

### LINKED ISSUE #45690: Clickhouse backup command doesn't respect compression_method parameter
**Describe what's wrong**

You can try passing any value of compression_method to BACKUP command and it accepts it.

```
5da01b1d39f3 :) BACKUP database datasets to Disk('backups', 'full-zstd.zip') SETTINGS compression_method='zstd';

BACKUP DATABASE datasets TO Disk('backups', 'full-zstd.zip') SETTINGS compression_method = 'zstd'

Query id: 877f473e-c24b-4393-af5f-a9e40d080e8a

┌─id───────────────────────────────────┬─status─────────┐
│ db5ffb4e-87cc-4839-a86f-61de23cb666c │ BACKUP_CREATED │
└──────────────────────────────────────┴────────────────┘

1 row in set. Elapsed: 53.706 sec.

5da01b1d39f3 :) select compressed_size from system.backups where id='db5ffb4e-87cc-4839-a86f-61de23cb666c';

SELECT compressed_size
FROM system.backups
WHERE id = 'db5ffb4e-87cc-4839-a86f-61de23cb666c'

Query id: 896df250-3a94-4fa9-b823-974a626fac5c

┌─compressed_size─┐
│      1421260924 │
└─────────────────┘
```

Passing random value of compression method also produces same size of backup.
```
5da01b1d39f3 :) BACKUP database datasets to Disk('backups', 'full-testing.zip') SETTINGS compression_method='foobar';

BACKUP DATABASE datasets TO Disk('backups', 'full-testing.zip') SETTINGS compression_method = 'foobar'

Query id: 0ff1c0cd-a5a9-44b4-885a-139f66a25549

┌─id───────────────────────────────────┬─status─────────┐
│ d5b97185-b086-45c6-82a2-98479776e373 │ BACKUP_CREATED │
└──────────────────────────────────────┴────────────────┘

1 row in set. Elapsed: 40.383 sec.

5da01b1d39f3 :) select compressed_size from system.backups where id='d5b97185-b086-45c6-82a2-98479776e373';

SELECT compressed_size
FROM system.backups
WHERE id = 'd5b97185-b086-45c6-82a2-98479776e373'

Query id: c3eaecfe-c02e-4758-974b-5114f7089bb7

┌─compressed_size─┐
│      1421260924 │
└─────────────────┘

1 row in set. Elapsed: 0.004 sec.
```
**Does it reproduce on recent release?**

Yes, I can reproduce this bug in v23.01 release.

**Expected behavior**

It should only allow certain values of compression_method which it supports.

### PR DESCRIPTION
**Pull request by chhetripradeep**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in official stable or prestable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Set compression method and level for backup Closes https://github.com/ClickHouse/ClickHouse/issues/45690

### Validation
Validated by taking backup

```
:) BACKUP DATABASE datasets TO Disk('backups', 'full-tttt.zip') SETTINGS compression_method = 'zstd'

┌─id───────────────────────────────────┬─status─────────┐
│ 05cb143a-e1a5-46c2-a0cd-3370d29739db │ BACKUP_CREATED │
└──────────────────────────────────────┴────────────────┘

:) BACKUP DATABASE datasets TO Disk('backups', 'full-ttttt.zip')

┌─id───────────────────────────────────┬─status─────────┐
│ ff2c6d58-e33a-4042-b181-ceb357b634f2 │ BACKUP_CREATED │
└──────────────────────────────────────┴────────────────┘

:) SELECT *
FROM system.backups
WHERE status = 'BACKUP_CREATED'
FORMAT Vertical

Row 1:
──────
..
uncompressed_size: 1834924338
compressed_size:   1421270417
..
Row 2:
──────
..
uncompressed_size: 1834924338
compressed_size:   1381649736
..

:) BACKUP DATABASE datasets TO Disk('backups', 'full-foobar.zip') SETTINGS compression_method = 'foobar'

Received exception from server (version 23.2.1):
Code: 642. DB::Exception: Received from localhost:9000. DB::Exception: Unknown compression method specified for a zip archive: foobar. (CANNOT_PACK_ARCHIVE)

❯ file full-tttt.zip
full-tttt.zip: Zip archive data, at least v4.5 to extract, compression method=Zstd

❯ file full-ttttt.zip
full-ttttt.zip: Zip archive data, at least v4.5 to extract, compression method=deflate

Also verified that those backup restoration is also working well.
````

cc @vitlibar

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]
The code LGTM, let's add a test.

**Comment by alexey-milovidov** [comment]
The new test did not pass.

**Comment by chhetripradeep** [comment]
Thank you for pointing it out. I am trying to get integration test running in local environment. I am looking into it.

**Comment by chhetripradeep** [comment]
The newly added test seems to be passing now:

Screenshot 2023-01-30 at 9 35 56 AM

**Comment by alexey-milovidov** [comment]
Something strange with `test_server_reload`

**Pull request merged**
