### PR TITLE
Use nfpm packager for archlinux packages

### PR DESCRIPTION
**Pull request by azat**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Use nfpm packager for archlinux packages

Since nfpm v2.20.0 it can build packages for archlinux [1].

  [1]: https://github.com/goreleaser/nfpm/pull/543

Something like this:

    $ mkdir -p /src/packages/root
    $ cmake -DCMAKE_INSTALL_PREFIX=/usr /src
    $ DESTDIR=/src/packages/root ninja install
    $ cd /src/packages
    $ ./build --archlinux

    $ root@s3:/src/packages# ./build --archlinux
    Current version is 22.10.1.1
    Building archlinux package for clickhouse-client.yaml
    using archlinux packager...
    created package: /src/clickhouse-client-22.10.1.1-1-x86_64.pkg.tar.zst
    ...

Cc: @Felixoid 
Follow-up for: #5719 (cc @excitoon)

_P.S. I think that very few people new about this packages for archlinux, and maybe even author do not use it, since it has `patchelf` to replace zlib dependency and some quirk for clang-7..._

### CODE REVIEW

**Comment by azat** [comment]
- [ClickHouse Push To Dockerhub Amd64](https://s3.amazonaws.com/clickhouse-test-reports/42349/36502270eb9f195dcd2dc8b350db9367c619f0f8/push_to_dockerhub_amd64.html) - #42351

**Comment by Felixoid** [comment]
I am not sure how we can use it, but never the less it's 146% more convenient way to have arch linux packages

**Comment by azat** [comment]
> I am not sure how we can use it

I don't think that somebody will uses it, but at least some code can be removed.

**Comment by azat** [comment]
>[packages: do not use type=config with directories](https://github.com/ClickHouse/ClickHouse/pull/42349/commits/af28937cac643b797f38692f42a08d4ea3132c34)

https://github.com/goreleaser/nfpm/issues/564

**Pull request merged**
