### PR TITLE
Dont use thread_local for complex types in apple clang (#1488)

### PR DESCRIPTION
**Pull request by proller**

### CODE REVIEW

**Comment by vavrusa** [comment]
This is probably nicer, I'll remove https://github.com/yandex/ClickHouse/pull/1473/commits/cbf1cff5bf8c43865364b8981a20a629416b82fc from my PR 👍

**Comment by vavrusa** [comment]
Just to make it clear, the only problem is with `extern thread_local` across compilation units (not sure what exactly triggers it, I'm suspecting LTO or something).

**Comment by alexey-milovidov** [comment]
This proposal forces to write `THREAD_LOCAL` instead of `thread_local` - unacceptable.

If LTO is the issue, better to disable LTO on Mac.
... or we can easily switch back to `__thread`.

**Comment by vavrusa** [comment]
@alexey-milovidov I'm not quite sure yet what's the issue. I couldn't reproduce it with a reduced test case (it build and links), with clickhouse it builds, but doesn't link (the variable symbol is missing). You can use my workaround for the time being, it's less intrusive https://github.com/yandex/ClickHouse/commit/cbf1cff5bf8c43865364b8981a20a629416b82fc

**Comment by proller** [comment]
maybe redefine thread_local for apple ?

**Comment by alexey-milovidov** [comment]
> it's less intrusive cbf1cff

That's Ok.

BTW I cannot find your commit.
%%
milovidov@milovidov-Pro-P30:~/work/ClickHouse$ git fetch --all
Fetching origin
milovidov@milovidov-Pro-P30:~/work/ClickHouse$ git show cbf1cff5bf8c43865364b8981a20a629416b82fc
fatal: bad object cbf1cff5bf8c43865364b8981a20a629416b82fc
%%

Probably you have removed it from your PR, but it was left in reflog in GitHub.

**Comment by vavrusa** [comment]
@alexey-milovidov I removed it in favour of this. I reopened a PR with just this commit: https://github.com/yandex/ClickHouse/pull/1499

**Comment by alexey-milovidov** [comment]
Ok.

**Pull request closed without merging**
