### PR TITLE
Fixed a bug with double move which corrupt original part

### PR DESCRIPTION
**Pull request by excitoon**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Bug Fix

Changelog entry (up to few sentences, required except for Non-significant/Documentation categories):

Fixed a bug with double move which corrupt original part.

### CODE REVIEW

**Comment by excitoon** [comment]
This fix shall be cherry-picked everywhere when possible.

**Comment by excitoon** [comment]
See https://github.com/ClickHouse/ClickHouse/pull/8422#issuecomment-574721155

**Comment by excitoon** [comment]
If we don't allow to move part back until `DeleteOnDestroy` happen then this is a correct solution.

**Review by alesapin — COMMENTED** [review]
Need test with long select and two `ALTER MOVE` to reproduce the problem. Also comment would be nice.

**Review by alexey-milovidov — APPROVED** [review]
Ok.

**Pull request merged**
