### PR TITLE
fix memory leak when exception happend during count distinct for null key

### PR DESCRIPTION
**Pull request by compasses**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix the memory leak for count distinct, when exception issued during group by single nullable key.

A simple reproduced case:
```
CREATE TABLE default.testnull
(
    `a` Nullable(String),
    `b` Nullable(String),
    `c` Nullable(String)
)
ENGINE = MergeTree
PARTITION BY tuple()
ORDER BY c
SETTINGS index_granularity = 8192

insert into default.testnull(b,c) select toString(rand64()) as b, toString(rand64()) as c from numbers(100000000)

select count(distinct b) from default.testnull group by a settings max_memory_usage = 5474836480;

```

each run will leak 5Gb memory.

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by Avogar** [comment]
Please, use the template PR description and choose the changelog entry. Also, a test is needed.

**Comment by compasses** [comment]
> Thank you for the PR! Please, use the template PR description and choose the changelog entry. Also, a test is needed.
Done, thanks.
But I have no idea add test to this, since it fix the memory leak, maybe could add test for some stable test?

**Comment by Avogar** [comment]
> But I have no idea add test to this, since it fix the memory leak, the test maybe no effect.

We run tests under address sanitizer, so it will have effect. We can add simple stateless sql test in folder `tests/queries/0_stateless/`. You can take `00332_quantile_timing_memory_leak.sql` as an example. The test can contain your example (but with less number of rows to make it fast enough):
```
-- Tags: no-fasttest

DROP TABLE IF EXISTS testnull;
CREATE TABLE testnull
(
    `a` Nullable(String),
    `b` Nullable(String),
    `c` Nullable(String)
)
ENGINE = MergeTree
PARTITION BY tuple()
ORDER BY c
SETTINGS index_granularity = 8192, allow_nullable_key=1;

INSERT INTO testnull(b,c) SELECT toString(rand64()) AS b, toString(rand64()) AS c FROM numbers(1000000)
SELECT count(distinct b) FROM testnull GROUP BY a  SETTINGS max_memory_usage = 54748364; -- {serverError MEMORY_LIMIT_EXCEEDED}

DROP TABLE testnull;
```

You can name it like `03214_count_distinct_null_key_memory_leak.sql` and add empty reference file `03214_count_distinct_null_key_memory_leak.reference` (empty because there is no output).

**Comment by robot-clickhouse-ci-2** [comment]
*This is an automated comment for commit 5a1f7318e68c1df4a0ebb66763ed363a7690260b with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/67171/5a1f7318e68c1df4a0ebb66763ed363a7690260b/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/e4bc7dea6141ee004efa706684c4108925159a4c/docs_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Comment by compasses** [comment]
> > But I have no idea add test to this, since it fix the memory leak, the test maybe no effect.
> 
> We run tests under address sanitizer, so it will have effect. We can add simple stateless sql test in folder `tests/queries/0_stateless/`. You can take `00332_quantile_timing_memory_leak.sql` as an example. The test can contain your example (but with less number of rows to make it fast enough):
> 
> ```sql
> -- Tags: no-fasttest
> 
> DROP TABLE IF EXISTS testnull;
> CREATE TABLE testnull
> (
>     `a` Nullable(String),
>     `b` Nullable(String),
>     `c` Nullable(String)
> )
> ENGINE = MergeTree
> PARTITION BY tuple()
> ORDER BY c
> SETTINGS index_granularity = 8192, allow_nullable_key=1;
> 
> INSERT INTO testnull(b,c) SELECT toString(rand64()) AS b, toString(rand64()) AS c FROM numbers(1000000)
> SELECT count(distinct b) FROM testnull GROUP BY a  SETTINGS max_memory_usage = 54748364; -- {serverError MEMORY_LIMIT_EXCEEDED}
> 
> DROP TABLE testnull;
> ```
> 
> You can name it like `03214_count_distinct_null_key_memory_leak.sql` and add empty reference file `03214_count_distinct_null_key_memory_leak.reference` (empty because there is no output).


Done, big thanks.

**Comment by compasses** [comment]
The test results are strange:

> 2024-07-31 01:30:50 The query succeeded but the server error '241' was expected (query: SELECT count(distinct b) FROM testnull GROUP BY a  SETTINGS max_memory_usage = 54748364; -- {serverError MEMORY_LIMIT_EXCEEDED}).

On my local test, it should always fail as expected. Do I need to do anything?

**Comment by Avogar** [comment]
> On my local test, it should always fail as expected. Do I need to do anything?

From the logs: `2024.07.31 01:30:50.371770 [ 9867 ] {b21e3a8f-67e3-48f6-83c5-ca6f88a3e91a} <Debug> MemoryTracker: Peak memory usage (for query): 41.35 MiB.`. So, let's just decrease the limit. Maybe something like `max_memory_usage =1000000` (1MB)

**Comment by compasses** [comment]
> > On my local test, it should always fail as expected. Do I need to do anything?
> 
> From the logs: `2024.07.31 01:30:50.371770 [ 9867 ] {b21e3a8f-67e3-48f6-83c5-ca6f88a3e91a} <Debug> MemoryTracker: Peak memory usage (for query): 41.35 MiB.`. So, let's just decrease the limit. Maybe something like `max_memory_usage =1000000` (1MB)

Got, and fixed, thanks.

**Review by Avogar — APPROVED** [review]

**Pull request merged**
