### PR TITLE
Improve insert retries on keeper session expiration

### PR DESCRIPTION
**Pull request by Algunenano**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
- Improve insert retries on keeper session expiration

### Documentation entry for user-facing changes
XXXXX

Removes `assertSessionIsNotExpired` since it's not necessary and counterproductive as it prevents keeper retries.

This is a stacktrace of a failed insert in production (`23.5.3.24`) due to a keeper leader change:

```
stack_trace:                           0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000e348c95 in /usr/bin/clickhouse
1. ? @ 0x000000000981db58 in /usr/bin/clickhouse
2. ? @ 0x0000000014b0aede in /usr/bin/clickhouse
3. DB::ReplicatedMergeTreeSinkImpl<false>::onFinish() @ 0x0000000014b194b0 in /usr/bin/clickhouse
4. ? @ 0x0000000014f3d91c in /usr/bin/clickhouse
5. DB::ExceptionKeepingTransform::work() @ 0x0000000014f3d2e4 in /usr/bin/clickhouse
6. DB::ExecutionThreadContext::executeTask() @ 0x0000000014d37d89 in /usr/bin/clickhouse
7. DB::PipelineExecutor::executeStepImpl(unsigned long, std::atomic<bool>*) @ 0x0000000014d2ea10 in /usr/bin/clickhouse
8. DB::PipelineExecutor::executeImpl(unsigned long) @ 0x0000000014d2df30 in /usr/bin/clickhouse
9. DB::PipelineExecutor::execute(unsigned long) @ 0x0000000014d2dbd1 in /usr/bin/clickhouse
10. DB::CompletedPipelineExecutor::execute() @ 0x0000000014d2c4dd in /usr/bin/clickhouse
11. DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, std::shared_ptr<DB::Context>, std::function<void (DB::QueryResultDetails const&)>, std::optional<DB::FormatSettings> const&) @ 0x0000000013ee210b in /usr/bin/clickhouse
12. DB::HTTPHandler::processQuery(DB::HTTPServerRequest&, DB::HTMLForm&, DB::HTTPServerResponse&, DB::HTTPHandler::Output&, std::optional<DB::CurrentThread::QueryScope>&) @ 0x0000000014c7ee35 in /usr/bin/clickhouse
13. DB::HTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&) @ 0x0000000014c830c4 in /usr/bin/clickhouse
14. DB::HTTPServerConnection::run() @ 0x0000000014cf2bf2 in /usr/bin/clickhouse
15. Poco::Net::TCPServerConnection::start() @ 0x0000000017c2fe34 in /usr/bin/clickhouse
16. Poco::Net::TCPServerDispatcher::run() @ 0x0000000017c31051 in /usr/bin/clickhouse
17. Poco::PooledThread::run() @ 0x0000000017dadd07 in /usr/bin/clickhouse
18. Poco::ThreadImpl::runnableEntry(void*) @ 0x0000000017dab73c in /usr/bin/clickhouse
19. start_thread @ 0x00000000000076db in /lib/x86_64-linux-gnu/libpthread-2.27.so
20. __clone @ 0x000000000012161f in /lib/x86_64-linux-gnu/libc-2.27.so
```

In this case there was no retries. Why? Because it didn't fail in the common place `ReplicatedMergeTreeSinkImpl::commitPart` and instead it failed in `::onFinish`.
Checking in `::onFinish` if the ZK session has expired is unnecessary as this will be handled in a much nicer way, with retries, once it reaches commitPart (via `finishDelayedChunk`).

For consistency I've also moved the ZK retries inside `checkQuorumPrecondition`. This way `::writeExistingPart` is also covered and doesn't need to check if the session has expired manually.

### CODE REVIEW

**Review by devcrafter — APPROVED** [review]

**Comment by Algunenano** [comment]
`Stateless tests (tsan) [5/5]` -> https://github.com/ClickHouse/ClickHouse/issues/53630. Should be fixed once https://github.com/ClickHouse/ClickHouse/pull/53631 lands

**Comment by Algunenano** [comment]
Need to check why `015_executable_user_defined_functions` is failing under TSAN's CI

**Comment by Algunenano** [comment]
> `Integration tests (tsan) [3/6] — fail: 1, passed: 192` > `test_storage_azure_blob_storage/test.py::test_read_from_not_existing_container`. The connection to Azure / Azurite failed. Unrelated.

@devcrafter I keep hitting different CI problems unrelated to the changes. Should I keep retrying and reporting or is this ok to be merged?

**Comment by devcrafter** [comment]
> > `Integration tests (tsan) [3/6] — fail: 1, passed: 192` > `test_storage_azure_blob_storage/test.py::test_read_from_not_existing_container`. The connection to Azure / Azurite failed. Unrelated.
> 
> @devcrafter I keep hitting different CI problems unrelated to the changes. Should I keep retrying and reporting or is this ok to be merged?

No need to. I'll wait for integration tests with TSAN and if it's ok, will merge it. Thanks for trying to figure out what's wrong with failed tests

**Comment by devcrafter** [comment]
The latest CI run was green except for one integration test (`test_storage_azure_blob_storage/test.py::test_read_from_not_existing_container`), - checked, the failure can't be related

**Pull request merged**
