### PR TITLE
Adding experimental 01900_alter_race_condition_stress.sh stateless test

### PR DESCRIPTION
**Pull request by vzakaznikov**
Changelog category (leave one):
- Not for changelog

### CODE REVIEW

**Comment by qoega** [comment]
fuzzer
 #24184

**Comment by alexey-milovidov** [comment]
@mergifyio update

**Comment by alexey-milovidov** [comment]
@Mergifyio update

**Comment by alexey-milovidov** [comment]
@Mergifyio update

**Comment by alexey-milovidov** [comment]
@vzakaznikov There is no description what this test is going to test and it is very difficult to read. Could you please explain?

**Comment by vzakaznikov** [comment]
> @vzakaznikov There is no description what this test is going to test and it is very difficult to read. Could you please explain?

This test was an attempt to reproduce an issue when we tried to alter column from string type to float with some rows having empty strings which caused intermittent test fails. When we first ran this test with thread fuzzer we found a race condition in RBAC. I don't think we need to add this test to stateless as is and I propose to close this PR.

**Pull request closed without merging**
