### PR TITLE
Improve performace for huge ast by direct-writing the column name for ASTLiteral 

### LINKED ISSUE #51224: IAST::getColumnName() may be very heavy
**Describe the situation**
Functions with prefix `get` are usually considered lightweight. However, the `IAST::getColumnName()` may be very heavy because it recursively calls virtual function `IAST::appendColumnName()`. When the AST tree is deep, the cost of recursively calling `IAST::appendColumnName()` is huge. In my practice, the cost would count half of the total elapsed time of running a big query.

**How to reproduce**
* Which ClickHouse server version to use
23.3

**Expected performance**
`IAST::getColumnName()` should be a light-weight function, as it is called many times and many places. It should not count half of total time.

Here is the dump of AST tree for my test big query.
[sql1.ast.txt](https://github.com/ClickHouse/ClickHouse/files/11816438/sql1.ast.txt)

### PR DESCRIPTION
**Pull request by frinkr**
### Changelog category (leave one):
- Performance Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Improve performance for huge query analysis. Fixes https://github.com/ClickHouse/ClickHouse/issues/51224

### CODE REVIEW

**Comment by frinkr** [comment]
We have some huge queries (3MB~13MB, generated by tools, with 15K literals) but small dataset, this PR improve the overall performance by ~20%.

**Comment by robot-ch-test-poll** [comment]
This is an automated comment for commit acddbb7c642c8847b623afc39bddbd48bb1a3c98 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/51469/acddbb7c642c8847b623afc39bddbd48bb1a3c98/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Review by evillique — APPROVED** [review]

**Comment by Algunenano** [comment]
Let's wait and see what the perf tests say, but if it's not obvious may I suggest adding a test similar to https://github.com/ClickHouse/ClickHouse/pull/43556/ (which is just a long query without data)?

**Comment by frinkr** [comment]
> Let's wait and see what the perf tests say, but if it's not obvious may I suggest adding a test similar to #43556 (which is just a long query without data)?

By huge, I mean **really** huge. The generated sql is 13M in plain text (sorry I can't post it here), and the count of literals & functions is 15K.

**Comment by frinkr** [comment]
Btw the dataset is 20K.

**Pull request merged**
