### PR TITLE
Enet protocol for replication

### PR DESCRIPTION
**Pull request by BoloniniD**
### Changelog category (leave one):
- New Feature

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Add Enet protocol as an alternative for TCP in replication.

### Documentation entry for user-facing changes

- [x] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by tavplubix** [comment]
> Add Enet protocol as an alternative for TCP in replication.

Could you provide more details, please? What are the advantages of that protocol? Why do we need it for replication? Do you have some benchmark results showing performance improvements?

**Comment by BoloniniD** [comment]
Currently, the implementation of replication through ENet is more of an experiment. This was proposed in #42194 along with pair of other protocols to try to speed up data transfer in an unreliable network environment. At the moment, there are no tests and comparisons of ENet performance inside replication algorithm, however, before merging this pull request, such tests are planned to be carried out to decide if this and other UDP-based protocols have advantages over default way or not.

**Comment by robot-clickhouse-ci-2** [comment]
This is an automated comment for commit a5e60902553f7326f9243781a02884bc850c1396 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/48326/a5e60902553f7326f9243781a02884bc850c1396/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Docs Check</td><td>Builds and tests the documentation</td><td>🟡 pending</td></tr>
</table>

**Comment by tavplubix** [comment]
Benchmarking did not show any performance improvements

**Pull request closed without merging**
