### PR TITLE
rabbitmq/kafka/filelog direct select allow only under setting, commit also under setting for select

### PR DESCRIPTION
**Pull request by kssenii**
Changelog category (leave one):
- Backward Incompatible Change

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Do not allow direct select for Kafka/RabbitMQ/FileLog. Can be enables by setting `stream_like_engine_allow_direct_select`. Direct select will be not allowed even if enabled by setting  in case there is attached materialized view. For Kafka and RabbitMQ direct select if allowed, will not commit massages by default. To enable commits with direct select user must use storage level setting `kafka{rabbitmq}_commit_on_select=1` (default `0`).
cc @filimonov

### CODE REVIEW

**Comment by tavplubix** [comment]
Should we change changelog category to "Backward Incompatible"?

Also I'm not familiar with Kafka, but Mikhail Filimonov told that even with disabled `commit_in_suffix` flag it will continue reading from new offset after SELECT. Is it expected?

**Comment by alesapin** [comment]
> Should we change changelog category to "Backward Incompatible"?
> 
> Also I'm not familiar with Kafka, but Mikhail Filimonov told that even with disabled `commit_in_suffix` flag it will continue reading from new offset after SELECT. Is it expected?

Probably we can just add tests for it?

**Comment by kssenii** [comment]
>>> Should we change changelog category to "Backward Incompatible"?

>>Also I'm not familiar with Kafka, but Mikhail Filimonov told that even with disabled commit_in_suffix flag it will continue reading from new offset after SELECT. Is it expected?

>Probably we can just add tests for it?

I discussed with Mikhail Filimonov and he said that after one more glance at code he thinks that these words:
> even with disabled commit_in_suffix flag it will continue reading from new offset after SELECT

are not true after all. And we discussed how to make it better in a different way, I just haven't returned to this pr yet..

**Review by tavplubix — APPROVED** [review]

**Comment by tavplubix** [comment]
Integration tests (release, actions) - test_storage_kerberized_kafka - `Direct select is not allowed. To enable use setting stream_like_engine_allow_direct_select` - need to update the test

**Comment by yangjinzheng** [comment]
use datagrip create clickhouse table consume kafka suggest java.io.IOException: Code: 620. DB::Exception: Direct select is not allowed. To enable use setting `stream_like_engine_allow_direct_select`. (QUERY_NOT_ALLOWED) why?

**Comment by kssenii** [comment]
> use datagrip create clickhouse table consume kafka suggest java.io.IOException: Code: 620. DB::Exception: Direct select is not allowed. To enable use setting stream_like_engine_allow_direct_select. (QUERY_NOT_ALLOWED) why?

just use SETTINGS stream_like_engine_allow_direct_select=1 if you need direct select to work or enable it globally for all queries by adding this to users config file.

**Pull request merged**
