### PR TITLE
Add test for changing column's type by performing ADD COLUMN + UPDATE + DROP COLUMN

### PR DESCRIPTION
**Pull request by vitlibar**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category:
- Not for changelog

### CODE REVIEW

**Review by alesapin — APPROVED** [review]
Actually this test doesn't cover any new cases, but more tests is better!

**Comment by alesapin** [comment]
https://clickhouse-test-reports.s3.yandex.net/14048/82c8f5671314c7d2a89eff59b135bf62f10d9262/functional_stateless_tests_(release).html#fail1 Failed due to `DROP` of column executed before mutation.

**Comment by alesapin** [comment]
`01393_benchmark_secure_port` :( not related to changes

**Comment by alexey-milovidov** [comment]
It's unclear how this result of `01393_benchmark_secure_port` even possible.
Someone sent interrupt signal to clickhouse-benchmark?

**Comment by alexey-milovidov** [comment]
Probably it because of slowdown, so clickhouse-benchmark has output one additional progress message.

**Comment by alexey-milovidov** [comment]
@alesapin https://github.com/ClickHouse/ClickHouse/pull/14066

**Pull request merged**
