### PR TITLE
Release pull request for branch 21.6

### PR DESCRIPTION
**Pull request by robot-ch-test-poll**
This PullRequest is part of ClickHouse release cycle. It's used by CI system only. Don't perform any changes with it.

### CODE REVIEW

**Review by 1999snehathete — APPROVED** [review]

**Comment by vdimir** [comment]
Failed tests on latest commit 677f817 that havn't failed on revious release 937130d 

```
SELECT current.* FROM (
    SELECT check_name, test_name, check_start_time, test_status
    FROM `gh-data`.checks
    WHERE (test_status like 'F%' OR test_status like 'ERROR%') 
        AND pull_request_number = 24357
        AND commit_sha like '677f817%'
) as current
ANTI JOIN (
    SELECT check_name, test_name, check_start_time, test_status
    FROM `gh-data`.checks
    WHERE (test_status like 'F%' OR test_status like 'ERROR%') 
        AND pull_request_number = 24357
        AND commit_sha like '937130d%'
) as prev
USING test_name
```


```
┌─check_name─────────────────────────┬─test_name─────────────────────────────────────────────────────────────────────────────────────┬────check_start_time─┬─test_status─┐
│ Functional stateless tests (debug) │ 00534_functions_bad_arguments4                                                                │ 2021-06-25 09:54:33 │ FAIL        │
│ Integration tests (asan)           │ test_backup_with_other_granularity/test.py::test_backup_from_old_version                      │ 2021-06-25 10:05:41 │ FAIL        │
│ Integration tests (asan)           │ test_backward_compatibility/test_aggregate_function_state_avg.py::test_backward_compatability │ 2021-06-25 10:05:41 │ FLAKY       │
│ Integration tests (asan)           │ test_ttl_replicated/test.py::test_ttl_compatibility[node_left2-node_right2-2]                 │ 2021-06-25 10:05:41 │ FAIL        │
│ Integration tests (asan)           │ test_ttl_replicated/test.py::test_ttl_double_delete_rule_returns_error                        │ 2021-06-25 10:05:41 │ FAIL        │
│ Integration tests (asan)           │ test_ttl_replicated/test.py::test_ttl_empty_parts                                             │ 2021-06-25 10:05:41 │ FAIL        │
│ Integration tests (asan)           │ test_ttl_replicated/test.py::test_ttl_many_columns                                            │ 2021-06-25 10:05:41 │ FAIL        │
│ Integration tests (asan)           │ test_ttl_replicated/test.py::test_ttl_table[DELETE]                                           │ 2021-06-25 10:05:41 │ FAIL        │
│ Integration tests (asan)           │ test_ttl_replicated/test.py::test_ttl_table[]                                                 │ 2021-06-25 10:05:41 │ FAIL        │
│ Integration tests (thread)         │ test_dictionaries_all_layouts_separate_sources/test_cassandra.py::test_simple[hashed]         │ 2021-06-25 10:07:42 │ FLAKY       │
│ Integration tests (release)        │ test_storage_kerberized_hdfs/test.py::test_cache_path                                         │ 2021-06-25 18:21:51 │ ERROR       │
│ Integration tests (release)        │ test_storage_kerberized_hdfs/test.py::test_prohibited                                         │ 2021-06-25 18:21:51 │ ERROR       │
│ Integration tests (release)        │ test_storage_kerberized_hdfs/test.py::test_read_table                                         │ 2021-06-25 18:21:51 │ ERROR       │
│ Integration tests (release)        │ test_storage_kerberized_hdfs/test.py::test_read_table_expired                                 │ 2021-06-25 18:21:51 │ ERROR       │
│ Integration tests (release)        │ test_storage_kerberized_hdfs/test.py::test_read_write_storage                                 │ 2021-06-25 18:21:51 │ ERROR       │
│ Integration tests (release)        │ test_storage_kerberized_hdfs/test.py::test_two_users                                          │ 2021-06-25 18:21:51 │ ERROR       │
│ Integration tests (release)        │ test_storage_kerberized_hdfs/test.py::test_write_storage_not_expired                          │ 2021-06-25 18:21:51 │ ERROR       │
│ Integration tests (release)        │ test_storage_kerberized_kafka/test.py::test_kafka_json_as_string                              │ 2021-06-25 18:21:51 │ ERROR       │
│ Integration tests (release)        │ test_storage_kerberized_kafka/test.py::test_kafka_json_as_string_no_kdc                       │ 2021-06-25 18:21:51 │ ERROR       │
│ Integration tests (release)        │ test_version_update/test.py::test_modulo_partition_key_after_update                           │ 2021-06-25 18:21:51 │ ERROR       │
└────────────────────────────────────┴───────────────────────────────────────────────────────────────────────────────────────────────┴─────────────────────┴─────────────┘
```

**Comment by CurtizJ** [comment]
Some integration tests failed with `Error processing tar file(exit status 1): write /usr/bin/clickhouse: no space left on device`. `test_cluster_copier` was broken also at previous release.

**Comment by akuzm** [comment]
The integration tests seem to be fixed in master, I'll release like this.

**Review by SNiTEBoBy — APPROVED** [review]
submit feedback and confirm merge

**Review by SNiTEBoBy — APPROVED** [review]
merPull request and change

**Pull request closed without merging**
