### PR TITLE
Fixed developer instruction

### PR DESCRIPTION
**Pull request by vladimir-golovchenko**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

**Changelog category**:

- Documentation (changelog entry is not required)

**Changelog entry**:

Applied the next changes to the developer docs:
- fixed misspelling links
- fixed the wrong link to Git Cheat Sheet
- fixed the wrong command to run clickhouse-client
- fixed the link to a list of tasks: it points to open issues marked as 'easy'
- actualized the versions of compilers and Standard Library.

### CODE REVIEW

**Comment by vladimir-golovchenko** [comment]
Could you approve that all changes are correct to I can propagate these changes to docs of other languages?

**Review by alexey-milovidov — APPROVED** [review]
All changes are correct, let's propagate them.

**Comment by vladimir-golovchenko** [comment]
@alexey-milovidov I updated the docs of other languages.

FYI the doc in Russian had already been updated and it is a little different from others in *clang* related sentence:

> Компилятор - `gcc`. На данный момент (август 2020), код собирается версией 9.3. (Также код может быть собран `clang` версий 10 и 9)

**Comment by alexey-milovidov** [comment]
We use clang-10 in CI but versions 9 and 8 are also seems to work.

**Pull request merged**
