### PR TITLE
Support sql cmd to connect specify zookeeper

### PR DESCRIPTION
**Pull request by mateng0915**
### Changelog category (leave one):
- New Feature

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Zookeeper / ClickHouse-Keeper is the key component  in ClickHouse Distributed System. And each CK server will establish to zookeeper node
image
And it connected with random method, so in some cases it will facing some zknode will have more connections, for instance zk02, it has 5 connections, but zk03 only have 1 connection, it will not cause problem, but when ck cluster has pressure, for instance if zookeeper has a lot of znodes ,and a lot of insert queries, zk02 will easily facing outstanding request full issue:

For avoid the zk node outstanding request is full, the best practice is control the number of connections between CK server and one zk node , Currently if one zk node was connected by too many ck servers, the method is restart ck server, and it has some possible to make this zk node connection become less. This is not efficient , and restart CK server is also bring the DB cluster unstable risk

So Design this system sql CMD

SYSTEM CONNECT TO INDEX $Index ZK as the sql interface to trigger the CK build a connection with specified zookeeper 

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by azat** [comment]
This looks like a very low-level API, and it will be inconvenient to use on big clusters, maybe re-balance should be done automatically?

For example provide `load_balancing` in `zookeeper` configuration with possible variants like `none` (default), and `least_used` (`least_connected`/...), and use [4LW](https://zookeeper.apache.org/doc/r3.4.8/zookeeperAdmin.html) `stat`/cons` (which is more light weight, also note that `keeper` should implement it too, right now it does, but it had been added only in #28981) to detect to which server the connection should go.

And provide some system query that will initiate this re-balance - `SYSTEM COORDINATOR REBALANCE` (since doing it on regular basis is not a good idea since this will mark tables read-only on reconnect)

**Comment by tavplubix** [comment]
> For example provide load_balancing in zookeeper configuration

We already have it, see https://github.com/ClickHouse/ClickHouse/pull/30325 (however, we don't have something similar to `least_used`)

**Comment by azat** [comment]
>We already have it, see https://github.com/ClickHouse/ClickHouse/pull/30325 (however, we don't have something similar to least_used)

Thanks! Yeah, forgot about it (I guess because it is not that interesting without `least_used` or similar:) )

**Comment by mateng0915** [comment]
Thx you guys comments, but becaus of currently the load balance settings doest not support hash method, currently the supported four lb method, can not avoid the problems what i just mentioned , @azat yes you are right about rebalance the whole cluster is better for big cluster
But In the prod env, sometimes, when one user insert a lot of data without using reasonable batch size , will easily to zk node increased dramatically, and at that time, some zk server, maybe the connections number is higher than others, for instance we have 5 zk serves

**Comment by mateng0915** [comment]
Thx @azat and @tavplubix 's comments
I think it is my fault did not describe this feature clearly , This feature is **not for whole cluster zk connection rebalance** @azat . This feature is provide an easy and accuracy to **solve hot replica issue**. 

Let me provide the scenario 
1. In the prod env, sometimes, may facing one shard (this shard contains two replica, replica01 and replica02)  one replica system load is very high (let us called this replica is replica01) and it will never decreased, Then we check the root cause, 
**We found the root cause is** : All the query dispatched to this replica , because of replica02 system.replication_queue is very large. Then we check the zookeeper status, we found the zk node which be  connected by replica02 the **outstading request full.**  
Solution about solve this : **we need make the replica02 connected to other ideal zookeeper**. So we restart replica02, to let it connect to other zookeeper.
Then we facing several status:
1.  restart is slower, especially when this replica contains a lot of data
2. restart maybe still connected to previously zookeeper node. 
3. connect to another zookeeper node, but that node is also in the status which easy facing outstanding request full. 
4. connect to one zookeeper node, that zookeeper node in the ideal status, can handle this replica's request
So as i mentioned we may facing these four cases. **so restart can not 100% make sure solve the problem that the prod env faced. Especially when this cluster unhealthy status happen in traffic Peak time**. **We have to try our best to shorten the unhealthy status**. We do not have too much time to restart the whole cluster, let the whole cluster rebalance. This will affected users for long time

So this feature is for solving this kind of issue

Thx

**Comment by azat** [comment]
>All the query dispatched to this replica

Because replica02 delay is greater then `max_replica_delay_for_distributed_queries` or what?

> because of replica02 system.replication_queue is very large

Because ZooKeeper is slow?

>Then we check the zookeeper status, we found the zk node which be connected by replica02 the outstading request full.

By the way ZooKeeper `stat` 4LW contains number of outstanding requests, so you may even implement `least_busy` or similar, that will check `Outstanding` from `stat` and connect to the node with the minimal number of requests.

> Solution about solve this : we need make the replica02 connected to other ideal zookeeper. So we restart replica02, to let it connect to other zookeeper.

But why some ZooKeeper replicas slower then the others? Do you use completely different hardware/setup/resources? I don't think that this is a good idea for coordinator.

>connect to one zookeeper node, that zookeeper node in the ideal status, can handle this replica's request

This can be solved by updating zookeeper configuration I guess (it should be applied without server restart), and remove "slow" nodes out of there, though this is not a good idea in general.

>So this feature is for solving this kind of issue

I understand that this solves the issue for you, however I think it is too low level and will not be used by other users.
And what I'm worrying about is that eventually it may get out of shape.

**Comment by azat** [comment]
>Do you use completely different hardware/setup/resources?

There is one more reason that I can think of - sometimes leader can have more load then followers, because it needs to serve writes, but:
- usually it should not be a problem, since for each write clickhouse has some reads (like listing parts in zookeeper while fetching parts and so on)
- you can disable leader from serving reads - [`leaderServes=no`](https://zookeeper.apache.org/doc/r3.3.3/zookeeperAdmin.html)

**Comment by mateng0915** [comment]
@azat  thx your comments


> > All the query dispatched to this replica
> 
> Because replica02 delay is greater then `max_replica_delay_for_distributed_queries` or what?
>  yes, we know that distributed table dispatch query will dispatch query to less delay replica
> > because of replica02 system.replication_queue is very large
>  
> Because ZooKeeper is slow?
> > > because  Zookeeper outstanding request is full, the reason about it is full, maybe zookeeper is slow, maybe this zookeeper receive too many request,  the reason this zookeeper node receive too many request maybe also has some different reason, for instance, if the at the same time user insert a lot of data, but did not use the reasonable batch size, and this data all send to one specify replica. Then cause zookeeper has too many write request (let assumption user using ReplicatedxxMergeTree)
> > Then we check the zookeeper status, we found the zk node which be connected by replica02 the outstading request full.
> 
> By the way ZooKeeper `stat` 4LW contains number of outstanding requests, so you may even implement `least_busy` or similar, that will check `Outstanding` from `stat` and connect to the node with the minimal number of requests.
> >> yes, our zookeeper monitor based on zk 4LW. This feature is for Micro adjust zookeeper connection
> > Solution about solve this : we need make the replica02 connected to other ideal zookeeper. So we restart replica02, to let it connect to other zookeeper.
> 
> But why some ZooKeeper replicas slower then the others? Do you use completely different hardware/setup/resources? I don't think that this is a good idea for coordinator.
> >> Maybe hardware is one reason , but in my live env, all zookeeper hardware is same, the reason i can give an example,  if  at the same time, one user insert a lot of data, but did not use the reasonable batch size, and this data all send to one specify replica. Then cause zookeeper has too many write request (let assumption user using ReplicatedxxMergeTree)
> > connect to one zookeeper node, that zookeeper node in the ideal status, can handle this replica's request
> 
> This can be solved by updating zookeeper configuration I guess (it should be applied without server restart), and remove "slow" nodes out of there, though this is not a good idea in general.
> >> Sure, definitely it can be solved updating zookeeper config, we did do this before, but that definitely not good operation method , because, for instance, we have 3 zookeeper, zk01,zk02,zk03, now i want it connect to zk03, so i have to remove zk01 and zk02 from the config file. If in the future, i forget to change back, what if zk03 shutdown? then all ReplicatedxxMergeTree table will be readonly
> > So this feature is for solving this kind of issue
> 
> I understand that this solves the issue for you, however I think it is too low level and will not be used by other users. And what I'm worrying about is that eventually it may get out of shape.
>>> I think it not only for me, all the DBA whole maintain the big ck  cluster and using zookeeper , they more or less in peak time will facing the problem what i just mentioned


@azat  Many thx your comments , very efficiency

**Comment by mateng0915** [comment]
> > Do you use completely different hardware/setup/resources?
> 
> There is one more reason that I can think of - sometimes leader can have more load then followers, because it needs to serve writes, but:
> 
> * usually it should not be a problem, since for each write clickhouse has some reads (like listing parts in zookeeper while fetching parts and so on)
> * you can disable leader from serving reads - [`leaderServes=no`](https://zookeeper.apache.org/doc/r3.3.3/zookeeperAdmin.html)

Yes, disable the zookeeper leader is a good way for optimize the zookeepr usage in ClickHouse scenario

**Comment by azat** [comment]
>yes, our zookeeper monitor based on zk 4LW. This feature is for Micro adjust zookeeper connection

Then why not to do this in the ClickHouse client itself?
And then you will not need you external "script", plus other users may also use the same and improve (if any).

**Comment by mateng0915** [comment]
> > yes, our zookeeper monitor based on zk 4LW. This feature is for Micro adjust zookeeper connection
> 
> Then why not to do this in the ClickHouse client itself? And then you will not need you external "script", plus other users may also use the same and improve (if any).

>> Firstly this is not client issue , this is because of the connection between  clickhouse-server  and zookeeper node, nothing related with clickhouse-client.  Secondly as the clickhouse DBA, our Database user maybe using a lot of different client to access ClickHouse DB, this can not be controled by client itself.

Thx @azat comments

**Comment by mateng0915** [comment]
> So just to summarize my proposal:
> 
> Implement two new load balancing algoritms based on `stat` 4LW output (make a request to each node, and use minimal according to load balancing to connect to):
> 
> ```
> <zookeeper>
>   <zookeeper_load_balancing>lead_used</zookeeper_load_balancing> 
>   <zookeeper_load_balancing>lead_requests</zookeeper_load_balancing> 
> </zookeeper>
> ```
> 
> And a command to do this manually, like `SYSTEM COORDINATOR RECONNECT/REBALANCE`

I think this is a good proposal , better design than my feature, i will push a new commit based on this proposal, thx @azat  Suggestion

**Pull request closed without merging**
