### PR TITLE
Analyzer support recursive CTEs

### PR DESCRIPTION
**Pull request by kitaisreal**
### Changelog category (leave one):
- New Feature

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Analyzer support recursive CTEs.

### CODE REVIEW

**Comment by robot-ch-test-poll3** [comment]
*This is an automated comment for commit 6afea0fca3909fcb444e5299ea0e9debcfc71cd7 with description of existing statuses. It's updated for the latest CI running*

[❌ Click here](https://s3.amazonaws.com/clickhouse-test-reports/62074/6afea0fca3909fcb444e5299ea0e9debcfc71cd7/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>❌ failure</td></tr>
<tbody>
</table>

**Comment by Algunenano** [comment]
TSAN is not happy: https://s3.amazonaws.com/clickhouse-test-reports/0/dffcc51b8389734c7476b6baafa15c3535ada8d7/ast_fuzzer__tsan_/stderr.log

Let's fix it or revert before making a new release

**Comment by kitaisreal** [comment]
> TSAN is not happy: https://s3.amazonaws.com/clickhouse-test-reports/0/dffcc51b8389734c7476b6baafa15c3535ada8d7/ast_fuzzer__tsan_/stderr.log
> 
> Let's fix it or revert before making a new release

I will try to make fix today.

**Comment by kitaisreal** [comment]
> TSAN is not happy: https://s3.amazonaws.com/clickhouse-test-reports/0/dffcc51b8389734c7476b6baafa15c3535ada8d7/ast_fuzzer__tsan_/stderr.log
> 
> Let's fix it or revert before making a new release

Here is fix https://github.com/ClickHouse/ClickHouse/pull/63125.

**Comment by clickgapai** [comment]
Hi @kitaisreal @alexey-milovidov — while reviewing this PR I found the following:

- **Coverage gap:** `SIZES_OF_COLUMNS_DOESNT_MATCH` for recursive CTE column-count mismatch is untested — https://github.com/ClickHouse/ClickHouse/pull/103973

Could you review the test PR and add the `can be tested` label if it looks good?
Happy to discuss — close anything that's wrong or already addressed.

**Pull request merged**
