### PR TITLE
Keep `LowCardinality` type in `tuple()` function

### LINKED ISSUE #37818: AST Fuzzer Logical error: 'Bad cast from type DB::ColumnString to DB::ColumnLowCardinality'.
https://s3.amazonaws.com/clickhouse-test-reports/37171/912e88c7fccf0cdf4c17e49379b78148a751338e/fuzzer_astfuzzerubsan,actions//report.html
```
2022.06.02 15:25:51.801941 [ 689 ] {} <Fatal> BaseDaemon: ########################################
2022.06.02 15:25:51.801977 [ 689 ] {} <Fatal> BaseDaemon: (version 22.6.1.1, build id: F9AB74DDDA135080) (from thread 177) (query_id: 0ce6475d-47af-4b29-98ad-3f5d36002da5) (query: SELECT DISTINCT toColumnTypeName(toLowCardinality(256)) FROM (SELECT DISTINCT toLowCardinality('1'), 1048575, toLowCardinality(256), number FROM remote('127.0.0.{1,2}', system.numbers) LIMIT 10)) Received signal Aborted (6)
2022.06.02 15:25:51.802001 [ 689 ] {} <Fatal> BaseDaemon: 
2022.06.02 15:25:51.802036 [ 689 ] {} <Fatal> BaseDaemon: Stack trace: 0x7f9ece09f03b 0x7f9ece07e859 0xfc74e8b 0xfc750e5 0x22b980a5 0x22b8e4b8 0x24df41be 0x24df3a5b 0x24db4756 0x24db0e1f 0x24da4210 0x24dc0f76 0x26c8e4cc 0x26c8e9a5 0x26e0cc07 0x26e0a4ec 0x7f9ece256609 0x7f9ece17b163
2022.06.02 15:25:51.802069 [ 689 ] {} <Fatal> BaseDaemon: 3. gsignal @ 0x7f9ece09f03b in ?
2022.06.02 15:25:51.802090 [ 689 ] {} <Fatal> BaseDaemon: 4. abort @ 0x7f9ece07e859 in ?
2022.06.02 15:25:51.818663 [ 689 ] {} <Fatal> BaseDaemon: 5. ./build_docker/../src/Common/Exception.cpp:47: DB::abortOnFailedAssertion(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0xfc74e8b in /workspace/clickhouse
2022.06.02 15:25:51.834294 [ 689 ] {} <Fatal> BaseDaemon: 6. ./build_docker/../src/Common/Exception.cpp:70: DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xfc750e5 in /workspace/clickhouse
2022.06.02 15:25:51.849319 [ 689 ] {} <Fatal> BaseDaemon: 7. ./build_docker/../src/Common/typeid_cast.h:0: DB::ColumnLowCardinality const& typeid_cast<DB::ColumnLowCardinality const&, DB::IColumn const>(DB::IColumn const&) @ 0x22b980a5 in /workspace/clickhouse
2022.06.02 15:25:51.864871 [ 689 ] {} <Fatal> BaseDaemon: 8. ./build_docker/../src/DataTypes/Serializations/SerializationLowCardinality.cpp:0: DB::SerializationLowCardinality::serializeBinaryBulkWithMultipleStreams(DB::IColumn const&, unsigned long, unsigned long, DB::ISerialization::SerializeBinaryBulkSettings&, std::__1::shared_ptr<DB::ISerialization::SerializeBinaryBulkState>&) const @ 0x22b8e4b8 in /workspace/clickhouse
2022.06.02 15:25:51.930875 [ 689 ] {} <Fatal> BaseDaemon: 11. ./build_docker/../src/Server/TCPHandler.cpp:1661: DB::TCPHandler::sendData(DB::Block const&) @ 0x24db4756 in /workspace/clickhouse
2022.06.02 15:25:51.954594 [ 289 ] {} <Error> DNSResolver: Cannot resolve host (127.0.0.1127.0.0.1127.0.0.2127.0.0.2), error 0: Host not found.
2022.06.02 15:25:51.972979 [ 689 ] {} <Fatal> BaseDaemon: 12.1. inlined from ./build_docker/../src/Server/TCPHandler.cpp:707: ~unique_lock
2022.06.02 15:25:51.973007 [ 689 ] {} <Fatal> BaseDaemon: 12. ../src/Server/TCPHandler.cpp:709: DB::TCPHandler::processOrdinaryQueryWithProcessors() @ 0x24db0e1f in /workspace/clickhouse
2022.06.02 15:25:51.996582 [ 289 ] {} <Error> DNSResolver: Cannot resolve host (127.0.0.2127.0.0.2), error 0: Host not found.
2022.06.02 15:25:52.010605 [ 689 ] {} <Fatal> BaseDaemon: 13. ./build_docker/../src/Server/TCPHandler.cpp:345: DB::TCPHandler::runImpl() @ 0x24da4210 in /workspace/clickhouse
2022.06.02 15:25:52.033423 [ 289 ] {} <Error> DNSResolver: Cannot resolve host (127.0.0.1127.0.0.1127.0.0.1127.0.0.2), error 0: Host not found.
2022.06.02 15:25:52.057841 [ 689 ] {} <Fatal> BaseDaemon: 14. ./build_docker/../src/Server/TCPHandler.cpp:1783: DB::TCPHandler::run() @ 0x24dc0f76 in /workspace/clickhouse
2022.06.02 15:25:52.062204 [ 689 ] {} <Fatal> BaseDaemon: 15. ./build_docker/../contrib/poco/Net/src/TCPServerConnection.cpp:57: Poco::Net::TCPServerConnection::start() @ 0x26c8e4cc in /workspace/clickhouse
2022.06.02 15:25:52.068998 [ 689 ] {} <Fatal> BaseDaemon: 16.1. inlined from ./build_docker/../contrib/libcxx/include/__memory/unique_ptr.h:54: std::__1::default_delete<Poco::Net::TCPServerConnection>::operator()(Poco::Net::TCPServerConnection*) const
2022.06.02 15:25:52.069028 [ 689 ] {} <Fatal> BaseDaemon: 16.2. inlined from ../contrib/libcxx/include/__memory/unique_ptr.h:315: std::__1::unique_ptr<Poco::Net::TCPServerConnection, std::__1::default_delete<Poco::Net::TCPServerConnection> >::reset(Poco::Net::TCPServerConnection*)
2022.06.02 15:25:52.069044 [ 689 ] {} <Fatal> BaseDaemon: 16.3. inlined from ../contrib/libcxx/include/__memory/unique_ptr.h:269: ~unique_ptr
2022.06.02 15:25:52.069059 [ 689 ] {} <Fatal> BaseDaemon: 16. ../contrib/poco/Net/src/TCPServerDispatcher.cpp:116: Poco::Net::TCPServerDispatcher::run() @ 0x26c8e9a5 in /workspace/clickhouse
2022.06.02 15:25:52.076082 [ 689 ] {} <Fatal> BaseDaemon: 17. ./build_docker/../contrib/poco/Foundation/src/ThreadPool.cpp:213: Poco::PooledThread::run() @ 0x26e0cc07 in /workspace/clickhouse
2022.06.02 15:25:52.083010 [ 689 ] {} <Fatal> BaseDaemon: 18.1. inlined from ./build_docker/../contrib/poco/Foundation/include/Poco/SharedPtr.h:156: Poco::SharedPtr<Poco::Runnable, Poco::ReferenceCounter, Poco::ReleasePolicy<Poco::Runnable> >::assign(Poco::Runnable*)
2022.06.02 15:25:52.083041 [ 689 ] {} <Fatal> BaseDaemon: 18.2. inlined from ../contrib/poco/Foundation/include/Poco/SharedPtr.h:208: Poco::SharedPtr<Poco::Runnable, Poco::ReferenceCounter, Poco::ReleasePolicy<Poco::Runnable> >::operator=(Poco::Runnable*)
2022.06.02 15:25:52.083056 [ 689 ] {} <Fatal> BaseDaemon: 18. ../contrib/poco/Foundation/src/Thread_POSIX.cpp:360: Poco::ThreadImpl::runnableEntry(void*) @ 0x26e0a4ec in /workspace/clickhouse
2022.06.02 15:25:52.083073 [ 689 ] {} <Fatal> BaseDaemon: 19. ? @ 0x7f9ece256609 in ?
2022.06.02 15:25:52.083091 [ 689 ] {} <Fatal> BaseDaemon: 20. __clone @ 0x7f9ece17b163 in ?
```

### LINKED ISSUE #39109: toLowCardinality in tuple doesn't work
`toLowCardinality` doesn't work with  `tuple`
```
SELECT tuple(toLowCardinality('1')) as x, toTypeName(x);
┌─x─────┬─toTypeName(tuple(toLowCardinality('1')))─┐
│ ('1') │ Tuple(String)                            │
└───────┴──────────────────────────────────────────┘
```

**How to reproduce**
* Which ClickHouse server version to use : 22.6.1 revision 54455.

### PR DESCRIPTION
**Pull request by CurtizJ**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in official stable or prestable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Keep `LowCardinality` type in `tuple()` function. Previously `LowCardinality` type was dropped and elements of created tuple had underlying type of `LowCardinality`.

Fixes #39109.
Fixes #37818.

### CODE REVIEW

**Review by antonio2368 — APPROVED** [review]

**Comment by Algunenano** [comment]
Could you please add tests using these types on (some) existing functions and aggregations? Most of them, if not all, don't support LowCardinality types and I'm not too confident the safeguards will be there.

**Comment by UnamedRus** [comment]
There is the same problem for arrays, can we have fix there as well?

**Comment by CurtizJ** [comment]
@[Algunenano](https://github.com/Algunenano) most of the functions will work correctly with `LowCardinality` because of `useDefaultImplementationForLowCardinalityColumns` . I think it will be good to have fuzzing for data types in tables and to test functions with unexpected types in that way.

**Comment by UnamedRus** [comment]
You already can have LowCardinality within arrays and tuples (and it's being used by many people):

```
SELECT toTypeName(CAST('[\'aaaa\']', 'Array(LowCardinality(String))')) AS d

Query id: edc4b7ab-e41a-4aa4-93b4-1facf617e4b9

┌─d─────────────────────────────┐
│ Array(LowCardinality(String)) │
└───────────────────────────────┘
```

Only problem is, it's not always keep LC trait.

**Comment by CurtizJ** [comment]
Integration tests: #39110.
Stateless tests: #39127.

**Pull request merged**
