### PR TITLE
Fix endless wait in replica clone

### PR DESCRIPTION
**Pull request by alesapin**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by alesapin** [comment]
Maybe it's better to remove this branch at all.

**Review by tavplubix — APPROVED** [review]
The fix LGTM, but I think it would be better to delete this code. It was needed for compatibility with versions older than 18.12

**Comment by alesapin** [comment]
> The fix LGTM, but I think it would be better to delete this code. It was needed for compatibility with versions older than 18.12

Ok, let's just delete it.

**Comment by alesapin** [comment]
No code -- no problems.

**Comment by qoega** [comment]
You should convert it do Backward incompatible change then. We should write it to changelog, even if we know it is a bad idea to have 18.x and 21.x nodes in cluster or update cluster with one step.

**Comment by alesapin** [comment]
> You should convert it do Backward incompatible change then. We should write it to changelog, even if we know it is a bad idea to have 18.x and 21.x nodes in cluster or update cluster with one step.

No, we shouldn't. It was just some kind of "optimization" for extremely rare case.

**Comment by alexey-milovidov** [comment]
+ the recommendation to upgrade from very old versions is to just upgrade all replicas at once (it eliminates the potential issue completely).

**Review by alexey-milovidov — APPROVED** [review]

**Pull request merged**
