### PR TITLE
Run cargo update to fix build with nightly

### LINKED ISSUE #51699: Build errors from rust
> Make sure that `git diff` result is empty and you've just pulled fresh master. Try cleaning up cmake cache. Just in case, official build instructions are published here: https://clickhouse.com/docs/en/development/build/

**Operating system**

> OS kind or distribution, specific version/release, non-standard kernel if any. If you are trying to build inside virtual machine, please mention it too.

WSL ubuntu 22.04 

**Cmake version**

3.26.3

**Ninja version**

1.10.1

**Compiler name and version**

clang++-16

**Full cmake and/or ninja output**

<details><summary>
    Finished dev [unoptimized + debuginfo] target(s) in 0.03s
   Compiling proc-macro2 v1.0.47
   Compiling num-integer v0.1.45
   Compiling cxx v1.0.83
   Compiling rayon v1.6.1
   Compiling env_logger v0.9.3
   Compiling link-cplusplus v1.0.7
error[E0422]: cannot find struct, variant or union type `LineColumn` in crate `proc_macro`
   --> /root/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-2eab394af869c8a2/proc-macro2-1.0.47/src/wrapper.rs:479:33
    |
479 |                 let proc_macro::LineColumn { line, column } = s.start();
    |                                 ^^^^^^^^^^ not found in `proc_macro`
    |
help: consider importing one of these items
    |
1   + use crate::LineColumn;
    |
1   + use crate::fallback::LineColumn;
    |
help: if you import `LineColumn`, refer to it directly
    |
479 -                 let proc_macro::LineColumn { line, column } = s.start();
479 +                 let LineColumn { line, column } = s.start();
    |

error[E0422]: cannot find struct, variant or union type `LineColumn` in crate `proc_macro`
   --> /root/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-2eab394af869c8a2/proc-macro2-1.0.47/src/wrapper.rs:496:33
    |
496 |                 let proc_macro::LineColumn { line, column } = s.end();
    |                                 ^^^^^^^^^^ not found in `proc_macro`
    |
help: consider importing one of these items
    |
1   + use crate::LineColumn;
    |
1   + use crate::fallback::LineColumn;
    |
help: if you import `LineColumn`, refer to it directly
    |
496 -                 let proc_macro::LineColumn { line, column } = s.end();
496 +                 let LineColumn { line, column } = s.end();
    |

error[E0635]: unknown feature `proc_macro_span_shrink`
  --> /root/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-2eab394af869c8a2/proc-macro2-1.0.47/src/lib.rs:92:30
   |
92 |     feature(proc_macro_span, proc_macro_span_shrink)
   |                              ^^^^^^^^^^^^^^^^^^^^^^

Some errors have detailed explanations: E0422, E0635.
For more information about an error, try `rustc --explain E0422`.
error: could not compile `proc-macro2` (lib) due to 3 previous errors
warning: build failed, waiting for other jobs to finish...

</details>

### PR DESCRIPTION
**Pull request by Algunenano**
### Changelog category (leave one):
- Build/Testing/Packaging Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
- Update cargo dependencies

### Documentation entry for user-facing changes

Closes https://github.com/ClickHouse/ClickHouse/issues/51699

Since https://github.com/ClickHouse/ClickHouse/pull/50541/ rust nightly is necessary, but building with a recent nightly is impossible because of old dependencies. Just update them.

### CODE REVIEW

**Comment by robot-ch-test-poll3** [comment]
This is an automated comment for commit 292eec247058c6020c48d0d4c3ebd27784fed466 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/51721/292eec247058c6020c48d0d4c3ebd27784fed466/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Review by alexey-milovidov — APPROVED** [review]

**Comment by Algunenano** [comment]
Test failures:
* `Stress test (ubsan)` -> OOM. It's odd because I don't see the server doing anything when it was killed. Not related to the changes.

**Comment by nikitamikhaylov** [comment]
`Stress test (ubsan) — OOM in dmesg` - what should I fix?

**Comment by alexey-milovidov** [comment]
@Algunenano, can we also pin Rust to whatever snapshot, git hash, etc... that works today, instead of "nightly"?

**Comment by Algunenano** [comment]
In theory it should be possible with something like:

```
$ cat rust/skim/rust-toolchain.toml
[toolchain]
channel = "nightly-2024-07-04"
```

This is how the [documentation says](https://rust-lang.github.io/rustup/overrides.html?highlight=rust-toolchain#the-toolchain-file) should work, but it doesn't. It didn't complain about me not having it installed and if I set it to a wrong date in the future it doesn't complain either. Maybe it has something to do with how corrosion picks up things.

Maybe we could document it without actually enforcing it.

**Pull request merged**
