### PR TITLE
Add SIMD support for uniquehashset which have better performance

### PR DESCRIPTION
**Pull request by zzachimed**
Co-authored-by: vesslanjin <jun.i.jin@intel.com>

Changelog category (leave one):

- Performance Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Add SIMD support for uniquehashset. And got 23% peformance boost in our google benchmark test in uniqhashset insert.

> Information about CI checks: https://clickhouse.tech/docs/en/development/continuous-integration/
Add SIMD support for uniquehashset. And got 23% peformance boost in our google benchmark test in uniqhashset insert.

### CODE REVIEW

**Comment by kitaisreal** [comment]
@zzachimed is there any difference with this pull request https://github.com/ClickHouse/ClickHouse/pull/34367 ?

**Comment by zzachimed** [comment]
@kitaisreal we do some tricky processing for previous algo in #34367 to make low level buff data distribution as same as the original algo.  Or it will casue some fast test case failed. cause that branch brokened . So i decide to create a new branch to deliver our new code.  
BTW: we found in" ClickHouse Special Build Check (actions) for [PR #34652](https://github.com/ClickHouse/ClickHouse/pull/34652)
link: https://s3.amazonaws.com/clickhouse-builds/34652/5dcced3fef89980ade6882236fa21caa565e79d3/clickhouse_special_build_check_(actions)/report.html
log: https://s3.amazonaws.com/clickhouse-builds/34652/5dcced3fef89980ade6882236fa21caa565e79d3/binary_tidy/build_log.log
that fail was caused by clang-tidy report:
Feb 16 17:06:34 error: invalid case style for type template parameter 'expr-type' [readability-identifier-naming,-warnings-as-errors]
but in our code and src project their has no template parameter like "expr-type" . we think this is clang-tidy bug . And also someone else already report to llvm offical site "https://bugs.llvm.org/show_bug.cgi?id=46752" . Could you help me to let that test go ?

**Comment by zzachimed** [comment]
@kitaisreal 
   my all ci case were passed except for case "ClickHouse Special Build Check" :
link :https://s3.amazonaws.com/clickhouse-builds/34652/0f61145134db6703d038b244d338fd60b2e953c9/clickhouse_special_build_check_(actions)/report.html
log: https://s3.amazonaws.com/clickhouse-builds/34652/0f61145134db6703d038b244d338fd60b2e953c9/binary_tidy/build_log.log

that fail was caused by clang-tidy report:
Feb 17 17:50:06 error: invalid case style for type template parameter 'expr-type' [readability-identifier-naming,-warnings-as-errors]
but in our code and src project their has no template parameter like "expr-type" . we think this is clang-tidy bug . And also someone else already report to llvm offical site "https://bugs.llvm.org/show_bug.cgi?id=46752" . 
Could you help me to let that test go ? verrrry thanks for your help.

**Comment by alexey-milovidov** [comment]
For some reason the difference in performance is not visible on performance tests.

**Comment by alexey-milovidov** [comment]
We need at least one query that will prove that the changes are beneficial.

**Comment by alexey-milovidov** [comment]
"google benchmark" a.k.a. calling function in a loop is not an appropriate performance test.

**Comment by alexey-milovidov** [comment]
We need to prove this performance improvement somehow...

**Comment by zzachimed** [comment]
> We need to prove this performance improvement somehow...
our peformance inprovement on hash finding happend some collision.  use SIMD operation can accelerate hash finding speed(in our benchmark unit test already proved this) . We also  did some end to end test  for offical SSB data sets(https://clickhouse.com/docs/zh/getting-started/example-datasets/star-schema/). in our test(sse2_v2 vs lastest master). our server cpu is icelake Intel(R) Xeon(R) Gold 6330 CPU @ 2.00GHz
server cmd : "/home/zhaozhou/Deliever_Clichhouse/rep/ClickHouse#numactl -C 0-27,56-83 ./clickhouse server"
client cmd:"/home/zhaozhou/Deliever_Clichhouse/rep/ClickHouse# for i in $(seq 1 400);do ./clickhouse client --max_memory_usage 200G --time --format=Null --query="select uniq(LO_SUPPLYCOST) from lineorder;";done 2>&1|awk -F : '{sum+=$1;print $1} END {print "AVG=",sum/NR}'"  
our test show in this ssb data set we can get about 0.6%-1%‘s performance boost.  I think if some datasets has more collision rate it will get more performance boost.

**Comment by taiyang-li** [comment]
I guess this pr may improve the performance of aggregate function: uniq ?  You can have a try, @zzachimed

**Comment by zzachimed** [comment]
> I guess this pr may improve the performance of aggregate function: uniq ? You can have a try, @zzachimed

@taiyang-li :
 Yes,  very thanks for your attention. This is reason that we try to opmitize this hotspot uniqhashset .

**Comment by zzachimed** [comment]
> > We need to prove this performance improvement somehow...
> > our peformance inprovement on hash finding happend some collision.  use SIMD operation can accelerate hash finding speed(in our benchmark unit test already proved this) . We also  did some end to end test  for offical SSB data sets(https://clickhouse.com/docs/zh/getting-started/example-datasets/star-schema/). in our test(sse2_v2 vs lastest master). our server cpu is icelake Intel(R) Xeon(R) Gold 6330 CPU @ 2.00GHz
> > server cmd : "/home/zhaozhou/Deliever_Clichhouse/rep/ClickHouse#numactl -C 0-27,56-83 ./clickhouse server"
> > client cmd:"/home/zhaozhou/Deliever_Clichhouse/rep/ClickHouse# for i in $(seq 1 400);do ./clickhouse client --max_memory_usage 200G --time --format=Null --query="select uniq(LO_SUPPLYCOST) from lineorder;";done 2>&1|awk -F : '{sum+=$1;print $1} END {print "AVG=",sum/NR}'"
> > our test show in this ssb data set we can get about 0.6%-1%‘s performance boost.  I think if some datasets has more collision rate it will get more performance boost.

@alexey-milovidov 👍  
    could you make it forward . in our unit test show 23% pefromance boost. And  seems no impact to current perfomance . and there has some pefromance boost for if  hash collission happens frequenctly in some condition .

**Comment by alexey-milovidov** [comment]
I'm checking on some queries on my AMD machine.

```
clickhouse-benchmark -i100 --query "SELECT uniq(UserID) FROM hits"
clickhouse-benchmark -i100 --query "SELECT CounterID, uniq(UserID) FROM hits GROUP BY CounterID ORDER BY 2 DESC LIMIT 10"
clickhouse-benchmark -i100 --query "SELECT uniq(WatchID) FROM hits"
clickhouse-benchmark -i100 --query "SELECT uniq(rand()) FROM numbers(10000000)"
clickhouse-benchmark -i100 --query "SELECT uniq(rand()) FROM numbers(100000000)"
clickhouse-benchmark -i100 --query "SELECT uniq(ClientIP) FROM hits"
clickhouse-benchmark -i100 --query "SELECT uniq(ClientIP) FROM hits" --max_threads 1
```

But performance is the same.

**Comment by alexey-milovidov** [comment]
I will check with the Star Schema Benchmark:

```
CREATE TABLE lineorder
(
    `LO_ORDERKEY` UInt32,
    `LO_LINENUMBER` UInt8,
    `LO_CUSTKEY` UInt32,
    `LO_PARTKEY` UInt32,
    `LO_SUPPKEY` UInt32,
    `LO_ORDERDATE` Date,
    `LO_ORDERPRIORITY` LowCardinality(String),
    `LO_SHIPPRIORITY` UInt8,
    `LO_QUANTITY` UInt8,
    `LO_EXTENDEDPRICE` UInt32,
    `LO_ORDTOTALPRICE` UInt32,
    `LO_DISCOUNT` UInt8,
    `LO_REVENUE` UInt32,
    `LO_SUPPLYCOST` UInt32,
    `LO_TAX` UInt8,
    `LO_COMMITDATE` Date,
    `LO_SHIPMODE` LowCardinality(String)
)
ENGINE = MergeTree
PARTITION BY toYear(LO_ORDERDATE)
ORDER BY (LO_ORDERDATE, LO_ORDERKEY)
```

```
INSERT INTO lineorder SELECT * FROM s3('https://clickhouse-public-datasets.s3.amazonaws.com/ssb/original/100/lineorder.tbl.xz', CSV);
```

**Comment by alexey-milovidov** [comment]
Your query:

```
clickhouse-benchmark -i100 --query "select uniq(LO_SUPPLYCOST) from lineorder"
```

No difference at all, neither with 1 or 64 threads.

Let's try with an Intel machine...

**Comment by alexey-milovidov** [comment]
> our test show in this ssb data set we can get about 0.6%-1%‘s performance boost. I think if some datasets has more collision rate it will get more performance boost.

Let's try to get anything that will show beyond a 1% performance boost.

**Comment by zzachimed** [comment]
> ok 👍  let's try it....

**Comment by alexey-milovidov** [comment]
Closing for now, but let's reopen if we can prove performance gains.

**Pull request closed without merging**
