### PR TITLE
Fix date32 out of range caused by uninitialized orc `DataBuffer`

### PR DESCRIPTION
**Pull request by taiyang-li**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix date32 out of range caused by uninitialized orc data. For more details, refer to https://github.com/apache/incubator-gluten/issues/7823

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Run only fuzzers related jobs (libFuzzer fuzzers, AST fuzzers, etc.)
- [ ]  Exclude: AST fuzzers
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-ch-test-poll1** [comment]
*This is an automated comment for commit c23dfa343155a7162b1bcf1f98080f5a08b92f7f with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/71500/c23dfa343155a7162b1bcf1f98080f5a08b92f7f/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/bdd18b35b29f6078b620c65a4f4d59853cfe5371/docs_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Comment by taiyang-li** [comment]
``` sql 
SET session_timezone = 'UTC';
SET engine_file_truncate_on_insert = 1;

insert into function file('03259.orc')
select
    number,
    if (number % 2 = 0, null, toDate32(number)) as date_field
    from numbers(10);

select date_field from file('03259.orc') order by number;

Received exception from server (version 24.11.1):
Code: 321. DB::Exception: Received from localhost:9001. DB::Exception: Input value 134219808 of a column "date_field" exceeds the range of type Date32: (in file/uri /data1/clickhouse_official/data/user_files/03259.orc): While executing ORCBlockInputFormat: While executing File. Stack trace:

0. ./contrib/llvm-project/libcxx/include/exception:141: std::exception::capture() @ 0x0000000017ae73eb
1. ./contrib/llvm-project/libcxx/include/exception:114: Poco::Exception::Exception(String const&, int) @ 0x0000000035aff565
2. ./build_gcc/./src/Common/Exception.cpp:109: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x0000000023ca362b
3. ./src/Common/Exception.h:110: DB::Exception::Exception(PreformattedMessage&&, int) @ 0x000000001796b236
4. ./src/Common/Exception.h:128: DB::Exception::Exception<int&, String const&>(int, FormatStringHelperImpl<std::type_identity<int&>::type, std::type_identity<String const&>::type>, int&, String const&) @ 0x0000000033589c0f
5. ./build_gcc/./src/Processors/Formats/Impl/NativeORCBlockInputFormat.cpp:1548: DB::ORCColumnToCHColumn::readColumnFromORCColumn(orc::ColumnVectorBatch const*, orc::Type const*, String const&, bool, std::shared_ptr<DB::IDataType const>) const @ 0x000000003356ece8
6. ./build_gcc/./src/Processors/Formats/Impl/NativeORCBlockInputFormat.cpp:1596: DB::ORCColumnToCHColumn::readColumnFromORCColumn(orc::ColumnVectorBatch const*, orc::Type const*, String const&, bool, std::shared_ptr<DB::IDataType const>) const @ 0x0000000033567418
7. ./build_gcc/./src/Processors/Formats/Impl/NativeORCBlockInputFormat.cpp:1887: DB::ORCColumnToCHColumn::orcColumnsToCHChunk(DB::Chunk&, std::unordered_map<String, std::pair<orc::ColumnVectorBatch const*, orc::Type const*>, std::hash<String>, std::equal_to<String>, std::allocator<std::pair<String const, std::pair<orc::ColumnVectorBatch const*, orc::Type const*>>>>&, unsigned long, DB::BlockMissingValues*) @ 0x00000000335653a3
8. ./build_gcc/./src/Processors/Formats/Impl/NativeORCBlockInputFormat.cpp:1130: DB::ORCColumnToCHColumn::orcTableToCHChunk(DB::Chunk&, orc::Type const*, orc::ColumnVectorBatch const*, unsigned long, DB::BlockMissingValues*) @ 0x000000003356230d
9. ./build_gcc/./src/Processors/Formats/Impl/NativeORCBlockInputFormat.cpp:1028: DB::NativeORCBlockInputFormat::read() @ 0x00000000335613a1
10. ./build_gcc/./src/Processors/Formats/IInputFormat.cpp:19: DB::IInputFormat::generate() @ 0x00000000333302b5
11. ./build_gcc/./src/Processors/ISource.cpp:139: DB::ISource::tryGenerate() @ 0x00000000332effb4
12. ./build_gcc/./src/Processors/ISource.cpp:108: DB::ISource::work() @ 0x00000000332ef5da
13. ./build_gcc/./src/Processors/Executors/ExecutionThreadContext.cpp:47: DB::ExecutionThreadContext::executeTask() @ 0x000000003331f720
14. ./build_gcc/./src/Processors/Executors/PipelineExecutor.cpp:289: DB::PipelineExecutor::executeStepImpl(unsigned long, std::atomic<bool>*) @ 0x000000003330a3c3
15. ./build_gcc/./src/Processors/Executors/PipelineExecutor.cpp:163: DB::PipelineExecutor::executeStep(std::atomic<bool>*) @ 0x00000000333099a3
16. ./build_gcc/./src/Processors/Executors/PullingPipelineExecutor.cpp:54: DB::PullingPipelineExecutor::pull(DB::Chunk&) @ 0x0000000033326f74
17. ./build_gcc/./src/Storages/StorageFile.cpp:1474: DB::StorageFileSource::generate() @ 0x000000003204acdf
18. ./build_gcc/./src/Processors/ISource.cpp:139: DB::ISource::tryGenerate() @ 0x00000000332effb4
19. ./build_gcc/./src/Processors/ISource.cpp:108: DB::ISource::work() @ 0x00000000332ef5da
20. ./build_gcc/./src/Processors/Executors/ExecutionThreadContext.cpp:47: DB::ExecutionThreadContext::executeTask() @ 0x000000003331f720
21. ./build_gcc/./src/Processors/Executors/PipelineExecutor.cpp:289: DB::PipelineExecutor::executeStepImpl(unsigned long, std::atomic<bool>*) @ 0x000000003330a3c3
22. ./build_gcc/./src/Processors/Executors/PipelineExecutor.cpp:255: void std::__function::__policy_invoker<void ()>::__call_impl<std::__function::__default_alloc_func<DB::PipelineExecutor::spawnThreads()::$_0, void ()>>(std::__function::__policy_storage const*) @ 0x000000003330bd09
23. ./contrib/llvm-project/libcxx/include/__functional/function.h:848: ? @ 0x0000000023edc39c
24. ./contrib/llvm-project/libcxx/include/__functional/invoke.h:359: ? @ 0x0000000023ee5c54
25. ./contrib/llvm-project/libcxx/include/__functional/function.h:848: ? @ 0x0000000023ed9b4f
26. ./contrib/llvm-project/libcxx/include/__functional/invoke.h:359: ? @ 0x0000000023ee0eea
27. ? @ 0x00007fb0f7da0609
28. ? @ 0x00007fb0f7cc7293
. (VALUE_IS_OUT_OF_RANGE_OF_DATA_TYPE)
```

**Comment by nickitat** [comment]
maybe we should zero-initialize all memory in `MemoryPool` to avoid such errors as a whole

**Review by yakov-olkhovskiy — APPROVED** [review]

**Comment by taiyang-li** [comment]
> maybe we should zero-initialize all memory in `MemoryPool` to avoid such errors as a whole?

It is not necessary option because it may bring performance degradation. In fact, PODArray in CH itself doesn't zero-initialize for internal buffer for similar reason. Let's wait and see if there are other issues caused by uninitialized orc `DataBuffer`.

**Comment by taiyang-li** [comment]
Failed https://s3.amazonaws.com/clickhouse-test-reports/71500/2cf8f54c5ba27f401408d573d2d4c142393a3699/bugfix_validation.html because it doesn't trigger exception every time.

**Comment by baibaichen** [comment]
@

> Failed https://s3.amazonaws.com/clickhouse-test-reports/71500/2cf8f54c5ba27f401408d573d2d4c142393a3699/bugfix_validation.html because it doesn't trigger exception every time.

@nickitat would we merge this pr?

**Pull request merged**
