### PR TITLE
Enable logical optimizer for LowCardinality regardless of short chain 

### PR DESCRIPTION
**Pull request by guowangy**
### Changelog category (leave one):
- Performance Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Always replace OR chain `expr = x1 OR ... OR expr = xN` to `expr IN (x1, ..., xN)` in case if `expr` is a `LowCardinality` column. Setting `optimize_min_equality_disjunction_chain_length` is ignored in this case.

For LowCardinality column, the dict is usually smaller and the index is relatively large. In most cases, even for chain length == 2, merging EQUALS-OR-chain as IN is better than converting each LowCardinality into full column individually. 

The patch set can have up to 8% performance gain in SSB (SF=100) query `3.3` and about 3% gain in query `3.4`, `4.1`.
(tested on Icelake: Xeon 8380 * 2 socket).

### CODE REVIEW

**Review by KochetovNicolai — CHANGES_REQUESTED** [review]
Code changes looks ok.

Please, add a test. `EXPLAIN SYNTAX` would be enough (maybe, perftest if you like).

**Comment by guowangy** [comment]
> Code changes looks ok.
> 
> Please, add a test. `EXPLAIN SYNTAX` would be enough (maybe, perftest if you like).

OK，I will add the tests.

**Comment by guowangy** [comment]
Hi @KochetovNicolai 
Both query test and perf test have been added. Please help to review.
Thanks

The unittest failure seems related to github api issue:
```
Exception: 429 Client Error: too many requests for url: https://api.github.com/repos/ClickHouse/ClickHouse/actions/runs/3510668725/jobs?per_page=100
```

**Review by guowangy — COMMENTED** [review]
@KochetovNicolai 
Both query test and perf test have been added. Please help to review.
It seems no way for me to change the "Changes requested" status, anyway, the code has been updated.

Thanks

**Review by KochetovNicolai — APPROVED** [review]

**Comment by KochetovNicolai** [comment]
Sorry for the long review. I should have merged it a long time ago.

**Comment by guowangy** [comment]
> Sorry for the long review. I should have merged it a long time ago.

Never mind. I really appreciate your time for reviewing my code :)

**Comment by alexey-milovidov** [comment]
@KochetovNicolai The code is wrong for many reasons. For example, it checks only the first argument.
What if the comparison has the form of `const = x` instead of `x = const`?
What if there is a mix of LowCardinality and non-LowCardinality types?

**Pull request merged**
