### PR TITLE
Add support for reloading client-side certificates

### LINKED ISSUE #43869: Support client certificate rotation
Similar to work done in #15765 which added support for reloading server certificates. Client certificates should also be dynamically reloaded when reloading the ClickHouse configuration. Our client certificates are short-lived and we'd prefer not having to restart `clickhouse-server` every time we rotate these client certificates. Thanks!

### PR DESCRIPTION
**Pull request by Romeo58rus**
### Changelog category (leave one):

- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Added the ability to reload client certificates in the same way as the procedure for reloading server certificates

Close #43869 

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Run only fuzzers related jobs (libFuzzer fuzzers, AST fuzzers, etc.)
- [ ]  Exclude: AST fuzzers
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
Needs a test.

**Comment by robot-ch-test-poll3** [comment]
*This is an automated comment for commit 89f4fe4f925d66172f0da9b161e0e577efdeb07a with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/70997/89f4fe4f925d66172f0da9b161e0e577efdeb07a/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/c737eabb9e79d3d8e0010111fef93effc90fa23c/docs_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Comment by Romeo58rus** [comment]
> Needs a test.
@alexey-milovidov 

Added a test that checks the reboot of client certificates to connect to Zookeeper - in the first iteration, a reboot occurs on a certificate with a CN that does not pass verification on the Zookeeper side, the expected behavior:
- [x] a message about certificate reloading in the Clickhouse log;
- [x] no connection to Zookeeper. 

In the second iteration, there is a reboot to a certificate with a valid CT, the expected behavior:
- [x] a message about certificate reloading in the Clockhouse log;
- [x] successful verification of the connection with Zookeeper.

The test passes successfully in CI, but Tests_2 behaves erratically.

**Comment by Romeo58rus** [comment]
@alexey-milovidov , @antonio2368
we need your help - the tests for the new functionality have been added and are working correctly, but it is not possible to pass PR tests, judging by the analysis of other tasks and the problem is not related to the added functionality, the tests are falling:

[Tests_2 / s (Integration tests (tsan), func-tester) / Integration tests (tsan)-2](https://github.com/ClickHouse/ClickHouse/actions/runs/11545145137/job/32133793806#logs)

[Tests_2 / s (Integration tests (aarch64), func-tester-aarch64) / Integration tests (aarch64)-1](https://github.com/ClickHouse/ClickHouse/actions/runs/11545145137/job/32133793193#logs)

(aarch64)-1((test)-2test_replicated_database/test.py::test_startup_without_zk
test_replicated_database/test.py::test_sync_replicas,

What should we do about it?

**Comment by antonio2368** [comment]
@Romeo58rus it's not related to your changes and it's fixed here https://github.com/ClickHouse/ClickHouse/pull/71103

**Comment by Romeo58rus** [comment]
> @Romeo58rus it's not related to your changes and it's fixed here #71103

@antonio2368 , thanks for the prompt response!

**Comment by Romeo58rus** [comment]
@alexey-milovidov , @antonio2368, hello! All tests in CI were successful, but Stateless tests has the Failed status. This solution is already successfully working in the PROD environment in our company, can we expect a merger, or does this require the status of "green ci"?

**Comment by Romeo58rus** [comment]
Unrelated failure :
Stateless tests (tsan, s3 storage) [2/3] - 00653_verification_monotonic_data_load - https://github.com/ClickHouse/ClickHouse/issues/68626

**Comment by Romeo58rus** [comment]
@alexey-milovidov , @antonio2368 
all tests were successful

**Comment by alexey-milovidov** [comment]
It failed: https://s3.amazonaws.com/clickhouse-test-reports/0/52a774aa3139f27783bc36ba1986b9c63cdf0c1b/integration_tests__asan__[1_4].html

**Comment by azat** [comment]
https://github.com/ClickHouse/ClickHouse/issues/77987

**Pull request merged**
