### PR TITLE
Fix disk using the same path

### LINKED ISSUE #29072: Server allows invalid storage configuration when two disks use the same path
If you create configuration file with two disks and specify that disks use the same path, and then create a policy that uses one of these disks then restarting server works and it is possible to create tables, insert and select from them, but on the next restart the server will not start if there are any files on disk.

**How to reproduce**
```xml
<yandex>
    <storage_configuration>
        <disks>
            <default>
                <keep_free_space_bytes>1024</keep_free_space_bytes>
            </default>
            <local1>
                <path>/home/antip/disk1/</path>
            </local1>
            <local2>
                <path>/home/antip/disk1/</path>
            </local2>
        </disks>
        <policies>
            <local1>
                <volumes>
                   <local_volume>
                        <disk>local1</disk>
                   </local_volume>
                </volumes>
            </local1>
        </policies>
    </storage_configuration>
</yandex>
```
```SQL
CREATE TABLE test
(
    ID Int32,
    Value String
)
ENGINE = MergeTree()
PARTITION BY ID
ORDER BY ID
SETTINGS storage_policy = 'local1'
```
```SQL
insert into test values (1, '1111')
```

Now restarting the server will not work.

* 21.10.1.7939 Clickhouse version

**Expected behavior**

Server shall not allow configuration when two or more disks use the same path.

**Errors**
```
ClickHouse client version 21.10.1.7939 (official build).
Connecting to localhost:9000 as user default.
Code: 210. DB::NetException: Connection refused (localhost:9000). (NETWORK_ERROR)
```

**Log**
```
<Error> Application: DB::Exception: Part `1_1_1_0` was found on disk `local2` which is not defined in the storage policy: Cannot attach table `default`.`test` from metadata file /var/lib/clickhouse/store/a1f/a1f83fde-e2be-44d7-a1f8-3fdee2be94d7/test.sql from query ATTACH TABLE default.test UUID 'bce3358a-0c4f-47c3-bce3-358a0c4f67c3' (`ID` Int32, `Value` String) ENGINE = MergeTree PARTITION BY ID ORDER BY ID SETTINGS storage_policy = 'local1', index_granularity = 8192: while loading database `default` from path /var/lib/clickhouse/metadata/default
```

### PR DESCRIPTION
**Pull request by zhongyuankai**
Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
fix disk using the same path, close #29072

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]

**Comment by kitaisreal** [comment]
@Mergifyio update

**Comment by zhongyuankai** [comment]
@alexey-milovidov  Integration test failed, it seems to be caused by parallel, can you suggest how to solve this problem?

**Comment by alexey-milovidov** [comment]
It is doing something wrong:

> Disk default and Disk default cannot have the same path (/var/lib/clickhouse/).

**Comment by alexey-milovidov** [comment]
Check what happens when configuration is updated.

**Comment by zhongyuankai** [comment]
> Check what happens when configuration is updated.

Thanks for the tip, it's fixed.

**Comment by zhongyuankai** [comment]
> Check what happens when configuration is updated.

@alexey-milovidov Thanks for the tip, it has been fixed.

**Comment by alesapin** [comment]
Tests Ok

**Pull request merged**
