### PR TITLE
Compression for Memory tables

### LINKED ISSUE #20093: Compression for Memory tables
Add very simple in-memory compression interface that works directly for columns.

Add method `IColumn::compress`. It returns either:
- `CompressedColumnPtr` that is `shared_ptr` of `ICompressedColumn`, that has the only method `virtual ColumnPtr decompress()`;
- `std::function<ColumnPtr()>` - a function object to get decompressed column back;

This method will take no parameters for compression but it can be extended later.

It should compress the whole buffers of columns as a single block with lz4. The usual compression interface with Read/Write buffers, support for checksums, etc. is not used.

Add support for SETTINGS clause for Memory table with the setting `compress = 0|1`.

The hypothesis is that compressed Memory tables will work faster on SELECTs by using less memory bandwidth.
Actually we already confirmed this hypothesis with MergeTree tables: they are compressed by default and it works faster than with disabled compression even if data is in memory and disk is not used.

### PR DESCRIPTION
**Pull request by alexey-milovidov**
Changelog category (leave one):
- Performance Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Add `compress` setting for `Memory` tables. If it's enabled the table will use less RAM. On some machines and datasets it can also work faster on SELECT, but it is not always the case. This closes #20093. Note: there are reasons why Memory tables can work slower than MergeTree: (1) lack of compression (2) static size of blocks (3) lack of indices and prewhere...

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
```
milovidov-desktop :) SELECT sum(x) FROM test_memory

SELECT sum(x)
FROM test_memory

Query id: 14833c4a-436f-40d6-8cce-f1a09db81158

┌─────sum(x)─┐
│ 1000000000 │
└────────────┘

1 rows in set. Elapsed: 0.140 sec. Processed 1.00 billion rows, 8.00 GB (7.13 billion rows/s., 57.04 GB/s.) 

milovidov-desktop :) SELECT sum(x) FROM test_memory_uncompressed

SELECT sum(x)
FROM test_memory_uncompressed

Query id: d11ce092-72a8-46c8-a75a-7275c45f1145

┌─────sum(x)─┐
│ 1000000000 │
└────────────┘

1 rows in set. Elapsed: 0.313 sec. Processed 1.00 billion rows, 8.00 GB (3.19 billion rows/s., 25.55 GB/s.) 
```

**Comment by alexey-milovidov** [comment]
There is up to 5 times improvement in perf tests.

**Comment by alexey-milovidov** [comment]
> 01396_inactive_replica_cleanup_nodes_zookeeper

Broken after merging NuRaft.

**Comment by alexey-milovidov** [comment]
https://github.com/ClickHouse/ClickHouse/issues/20494

**Comment by alexey-milovidov** [comment]
> AST fuzzer (ASan) — Received signal -3 

OOM

**Comment by alexey-milovidov** [comment]
I found another case how `MergeTree` tables can work better than `Memory` tables.

It happens due do dynamic block size selection.
Example:

```
milovidov-desktop :) SELECT avg(blockSize()) FROM test.hits_memory WHERE NOT ignore(URL)

SELECT avg(blockSize())
FROM test.hits_memory
WHERE NOT ignore(URL)

Query id: 6b374325-c2dc-4693-8927-da1bdcd92f35

┌──avg(blockSize())─┐
│ 65419.37380889436 │
└───────────────────┘

1 rows in set. Elapsed: 0.071 sec. Processed 8.87 million rows, 767.95 MB (124.56 million rows/s., 10.78 GB/s.) 

milovidov-desktop :) SELECT avg(blockSize()) FROM test.hits WHERE NOT ignore(URL)

SELECT avg(blockSize())
FROM test.hits
WHERE NOT ignore(URL)

Query id: c7d4073d-e360-4427-90dd-410241a74944

┌──avg(blockSize())─┐
│ 9279.622728591201 │
└───────────────────┘

1 rows in set. Elapsed: 0.054 sec. Processed 8.87 million rows, 767.95 MB (163.13 million rows/s., 14.12 GB/s.)

milovidov-desktop :) SELECT avg(length(URL)) FROM test.hits

SELECT avg(length(URL))
FROM test.hits

Query id: 653b288b-eac0-4aed-b5b7-a39390870930

┌──avg(length(URL))─┐
│ 77.54074297450794 │
└───────────────────┘

1 rows in set. Elapsed: 0.053 sec. Processed 8.87 million rows, 767.95 MB (165.86 million rows/s., 14.35 GB/s.)
```

**Comment by alexey-milovidov** [comment]
Experiment with compressing into arenas: https://github.com/ClickHouse/ClickHouse/compare/in-memory-compression-arenas?expand=1

**Comment by amosbird** [comment]
> I found another case how `MergeTree` tables can work better than `Memory` tables.
> 
> It happens due do dynamic block size selection.
> Example:

The example misses the result of `SELECT avg(length(URL)) FROM test.hits_memory`

**Comment by alexey-milovidov** [comment]
@amosbird If we lower block size to 8192 for this Memory table, query will be faster - about 30 ms if I remember correctly.

**Comment by alexey-milovidov** [comment]
This PR looks ready but I cannot enable compression by default:
- sometimes it improves performance sometimes not; it depends on queries, on the dataset and on specific server configurations.

**Pull request merged**
