### PR TITLE
Add missing workload identity changes

### PR DESCRIPTION
**Pull request by SmitaRKulkarni**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Adding changes from this PR (https://github.com/ClickHouse/ClickHouse/pull/57881/files)  missed in this PR  (https://github.com/ClickHouse/ClickHouse/pull/59767)

cc @kssenii @CurtizJ @alesapin

### CODE REVIEW

**Comment by robot-ch-test-poll1** [comment]
*This is an automated comment for commit 95932db17056a1c7b1ebc65fa269affd8004877d with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/65848/95932db17056a1c7b1ebc65fa269affd8004877d/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/2673a773c36f5e12b45e8c3b9b97b6cc3703afc1/docs_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Comment by CurtizJ** [comment]
It's already covered by #63636 which is ready to be merged. If it's required to backport this changes it's better to merge this PR, backport changes and then overwrite them by merging of refactoring. If it's not required to backport, it's better to just close this PR.

**Comment by alexey-milovidov** [comment]
Can it be tested?

**Comment by SmitaRKulkarni** [comment]
Closing this PR based on @CurtizJ comment that its covered in https://github.com/ClickHouse/ClickHouse/pull/63636
@alexey-milovidov Unfortunately its not straight forward to add test for workload identity in azurite. I tried some workaround no luck.

**Comment by SmitaRKulkarni** [comment]
On second thought, we should backport this otherwise 24.5 will be missing support for workload identity

**Pull request merged**
