### PR TITLE
Increase hash table max size for the uniqCombined() function non String types

### PR DESCRIPTION
**Pull request by azat**
Category (leave one):
- Improvement

Short description (up to few sentences):
Increase hash table max size to 2^14 for the uniqCombined() function for non-String types

Detailed description (optional):

This will give accurate result for uniqCombined() and non-String types
for cardinality up to 1<<14 (before this patch the accurate result was
for cardinality up to 1<<13).

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
It doesn't look correct:

```
For K = 17:

The size of HLL in bytes:
>>> 2 ** 17 * 6 / 8
98304

The size of hash tables with max 2^14 elements will contain 2^15 cells of 32bit size:
>>> 4 * 2 * 2 ** 14
131072

And this is greater than the size of HLL.
```

**Comment by alexey-milovidov** [comment]
How to validate:

```
SET max_memory_usage = 100000000;

SELECT intDiv(number, 16384) AS k, uniqCombined(number % 16384) FROM numbers(16384000) GROUP BY k;
```

Each state is using no more than 96KB.
Please add a test and check whether it fails after these modifications.

**Comment by azat** [comment]
>The size of hash table with max 2^14 elements will contain 2^15 cells of 32bit size:
>```
>>> 4 * 2 * 2 ** 14
>131072
>```

Hm, did not though about that fact that `HashTable<unsigned int>(1<<14)` != `HashTable<unsigned long>(1<<13)`

Also I checked this in debugger, and got this:

- `1<<13` with `String`: `getBufferSizeInBytes() == 131072`
- `1<<14` with `UInt32`: `getBufferSizeInBytes() == 262144`

That said that even for `String` hash table can be bigger then `HLL`

(If I did not missed anything)

**Comment by azat** [comment]
>SELECT intDiv(number, 16384) AS k, uniqCombined(number % 16384) FROM numbers(16384000) GROUP BY k;

And indeed, this one fails after the patch

**Comment by azat** [comment]
Hm, but don't we need care only about on-disk representation?

**Comment by alexey-milovidov** [comment]
> Also I checked this in debugger, and got this:
    1<<13 with String: getBufferSizeInBytes() == 131072
    1<<14 with UInt32: getBufferSizeInBytes() == 262144
That said that even for String hash table can be bigger then HLL

The hash table is resized when it is reached next power of two.
It should be of size 64K for 2^13 - 1 elements.

**Comment by alexey-milovidov** [comment]
> Hm, but don't we need care only about on-disk representation? (on disk it should not greater then 65546 bytes -- (1<<14)*4+8+2)

We care about memory size first. The size on disk (and the size of serialized state transferred over network; and how compressible it will be) also matters. But the sizes in memory must be aligned to each other.

**Comment by azat** [comment]
>resized when it is reached next power of two

Indeed

>It should be of size 64K for 2^13 - 1 elements.

So, the in-memory representation is also significant, and the size of the hash table should be reduced by one, instead of increased by the power of two?

**Comment by alexey-milovidov** [comment]
If it is resized and then after adding one next element, converted to HLL, it is waste of memory and CPU
and should be fixed.

**Comment by azat** [comment]
Okay, thanks, closing

**Comment by alexey-milovidov** [comment]
> Hm, but don't we need care only about on-disk representation? (on disk it should not greater then 65546 bytes -- (1<<14)*4+8+2)

The size is motivated by memory requirements.
On disk representation is a different story (it's less important scenario - AggregatingMergeTrees and external aggregation). BTW, data on disk is always compressed (but compression for UInt32 hash tables as well as HLLs is almost useless).

**Comment by alexey-milovidov** [comment]
Do you want to add my test just in case? :)

**Comment by azat** [comment]
>Do you want to add my test just in case? :)

Sure, along with fix for the `medium_set_size_max`

**Comment by azat** [comment]
>Do you want to add my test just in case? :)

Due to `HashTableGrower::increaseSize` makes `HashTable` grows twice power of two, before `2^23` using `2^13 - 1` does not changes anything, since the buffer grows as follow:
- 128
- 129 elements in hashtable -> 1024 # initial, but maxFill() allows only 128 items to be used, due to enormous load factor
- 513 element in hashtable -> 4096
- 2048 elements in hashtable -> 16384

So this can be fixed:
- replacing hashtable with i.e. sparse_hash_set
- replacing grower to fixed will use maximum memory even for small number of elements
- introduce another grower, that will grow by the power of 2

**Comment by azat** [comment]
>introduce another grower, that will grow by the power of 2

@alexey-milovidov something like #7236

**Comment by alexey-milovidov** [comment]
> replacing hashtable with i.e. sparse_hash_set

Not an option because it will become extremely slow.

> replacing grower to fixed will use maximum memory even for small number of elements

Not an option because it will defeat the whole point of combined data structure.
(It is needed for the typical case of GROUP BY huge amount of non-uniform distributed keys like URLs, search phrases, regions...)

> introduce another grower, that will grow by the power of 2

That's the right solution.

**Pull request closed without merging**
