### PR TITLE
Add support for MySQL `net_write_timeout` and `net_read_timeout` settings

### LINKED ISSUE #58553: MySQL compatibility: SET net_write_timeout
### Description
Required for AWS QuickSight SPICE import.

Sample query:

```sql
SET net_write_timeout = 60
```

### Expected behavior

Either ignored completely or translated to [send_timeout](https://clickhouse.com/docs/en/operations/settings/settings#connect-timeout-receive-timeout-send-timeout) (?)

See also: https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_net_write_timeout

### PR DESCRIPTION
**Pull request by slvrtrn**
Resolves https://github.com/ClickHouse/ClickHouse/issues/58553

Allows to use the following settings via MySQL interface:

```sql
SET NET_WRITE_TIMEOUT = X;
SET NET_READ_TIMEOUT = Y;
```

`net_write_timeout` is translated into the native `send_timeout` ClickHouse setting and, similarly, `net_read_timeout` into `receive_timeout`. These statements work regardless of the input query being upper or lower case.

Additionally, fixed an issue where changing MySQL `SQL_SELECT_LIMIT` setting was possible only if the entire statement was in upper case.

### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
MySQL interface gained support for `net_write_timeout` and `net_read_timeout` settings. `net_write_timeout` is translated into the native `send_timeout` ClickHouse setting and, similarly, `net_read_timeout` into `receive_timeout`. Fixed an issue where it was possible to set MySQL `sql_select_limit` setting only if the entire statement was in upper case.

### CODE REVIEW

**Comment by robot-ch-test-poll1** [comment]
*This is an automated comment for commit 204a291384430c88b5156cd7ea207c4cf2440640 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/58835/204a291384430c88b5156cd7ea207c4cf2440640/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/58835/204a291384430c88b5156cd7ea207c4cf2440640/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Review by alexey-milovidov — APPROVED** [review]
Ok.

A bit rough but in line with the existing code in MySQLHandler.

**Comment by alexey-milovidov** [comment]
Possible better solution will be:
- support all missing queries in ClickHouse's parser and interpreter (e.g., SHOW TABLE STATUS);
- introduce case-insensitive settings;
- introduce settings aliases;

**Comment by tavplubix** [comment]
It was merged without checking the CI status, and looks like it breaks `02967_mysql_settings_override`. Sorry, I have to revert this

**Comment by slvrtrn** [comment]
@tavplubix, thanks for the heads up; I will double-check what's up with `02967_mysql_settings_override` (it's actually a new one introduced in this PR).

**Pull request merged**
