### PR TITLE
Fix more dictGet ACL bypasses

### PR DESCRIPTION
**Pull request by joelynch**
An ACL bypass was fixed here https://github.com/ClickHouse/ClickHouse/pull/57362 for dictionary table function if you have `CREATE TEMPORARY TABLE` privilege.

However, I noticed that users with the SELECT privilege on a database can still access the data in the dictionary by querying the underlying table.

Is this intentional behaviour or should `dictGet` control all access to the data in the dictionary, even if the user has SELECT?

```sql
CREATE DICTIONARY IF NOT EXISTS my_dict
(
    id UInt64,
    value UInt64
)
PRIMARY KEY id
SOURCE(NULL())
LAYOUT(FLAT())
LIFETIME(MIN 0 MAX 1000);

-- should fail without dictGet but actually succeeds

SELECT * FROM my_dict;
```

### Changelog category (leave one):

- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Require `dictGet` privilege when accessing dictionaries via direct query or the `Dictionary` table engine.

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: Normal Builds
- [ ]  Allow: Special Builds
- [ ]  Allow: All NOT Required Checks
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Do not test
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-ch-test-poll1** [comment]
*This is an automated comment for commit 97572073cb4be716d3db4c17bd85b0996449a7c0 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/65359/97572073cb4be716d3db4c17bd85b0996449a7c0/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>A Sync</td><td>If it fails, ask a maintainer for help</td><td>⏳ pending</td></tr>
<tbody>
</table>
<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>Checks correctness of the PR's body</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

**Comment by joelynch** [comment]
It doesn't look to me like any of the CI failures are related.

**Comment by yariks5s** [comment]
Integration tests (aarch64) [5/6], Stateless tests (debug, s3 storage) [3/6], Stateless tests (debug, s3 storage) [6/6], Stateless tests (msan) [6/6], Stateless tests (tsan, s3 storage) [3/5] - can be not related


Stateless tests (debug) [5/5]  - looks suspicious

Could you please merge with master?

**Review by yariks5s — COMMENTED** [review]
Could you please write a separate test to reproduce this issue? Bugfix check complains that the tests that you changed haven't failed

**Comment by yariks5s** [comment]
So regarding the message above, I suggest testing the new bugfix separately from earlier tests (in the same or separate file), because we should not modify previous tests. Now the behavior of the previous test can be slightly modified by l.22: `GRANT SELECT, CREATE TEMPORARY TABLE ON *.* to ${username};`, what we should not really do.
Also, if you want to do all the tests in this one file, I would suggest adding something like `SELECT 'Testing the dictGet privileges;` before selecting the results of your tests. It would be easier to detect the problem then.

**Comment by joelynch** [comment]
okay I can put the new tests in a separate file.

**Review by yariks5s — COMMENTED** [review]
Bugfix check in the CI says that it could not validate a bug (the test without your changes passed without your changes)🙁

**Comment by joelynch** [comment]
> Bugfix check in the CI says that it could not validate a bug

I will rebase with this https://github.com/ClickHouse/ClickHouse/pull/66120 and see if that changes things.

**Comment by yariks5s** [comment]
Due to a Fatal error in tests, it's not possible to properly test this PR, I will notify you once the problem with the Fatal error is resolved, generally the PR looks good

**Comment by yariks5s** [comment]
@joelynch Could you please merge with master?

**Comment by yariks5s** [comment]
@joelynch I am sorry, may I ask you to merge one more time?🙂

**Review by yariks5s — APPROVED** [review]

**Pull request merged**
