### PR TITLE
Allow LowCardinality strings for ngrambf_v1/tokenbf_v1 indexes. Fixes #21865

### LINKED ISSUE #21865: Support LowCardinality strings in ngrambf_v1
Now it support only `String` and `FixedString`

https://github.com/ClickHouse/ClickHouse/blob/33aefa832b3c544934a757cc9d0e284252a1dd3e/src/Storages/MergeTree/MergeTreeIndexFullText.cpp#L809

Seems that `LowCardinality(String)` can be supported too, because we only use `column->getDataAt` to retrieve data and it will work on `LowCardinality(String)` in same way as for `String`
https://github.com/ClickHouse/ClickHouse/blob/33aefa832b3c544934a757cc9d0e284252a1dd3e/src/Storages/MergeTree/MergeTreeIndexFullText.cpp#L543
https://github.com/ClickHouse/ClickHouse/blob/33aefa832b3c544934a757cc9d0e284252a1dd3e/src/Storages/MergeTree/MergeTreeIndexFullText.cpp#L145

### PR DESCRIPTION
**Pull request by larspars**
Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Allow LowCardinality strings for ngrambf_v1/tokenbf_v1 indexes. Closes #21865.

I wanted to use LowCardinality(String) along with an ngrambf index. Issue #21865 suggests that LowCardinality(String) and LowCardinality(FixedString) can be accepted for ngrambf and tokenbf indexes, and that the check for allowable types can be simply begin to accept these types, and it should work. Here, I've simply loosened the type check, and added a test that exercises it. 

Compiling and running queries for LowCardinality(String) indexed by ngrambf/tokenbf seems to work fine.

That said, please don't assume that I know what I'm doing, I don't have much understanding of the various moving parts here. Someone who understands the codebase better should definitely look over these changes.

### CODE REVIEW

**Comment by kitaisreal** [comment]
@Mergifyio update

**Review by kitaisreal — APPROVED** [review]

**Comment by kitaisreal** [comment]
@Mergifyio update

**Comment by alexey-milovidov** [comment]
@Mergifyio update

**Review by kitaisreal — APPROVED** [review]

**Comment by kitaisreal** [comment]
Tests failures are unrelated.

**Pull request merged**
