### PR TITLE
CI config in repo

### PR DESCRIPTION
**Pull request by alesapin**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Build/Testing/Packaging Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Control CI builds configuration from the ClickHouse repository.

### CODE REVIEW

**Comment by qoega** [comment]
Does this PR test this file or it will be done separately?

**Comment by alesapin** [comment]
> Does this PR test this file or it will be done separately?

Yes, it checks this file, I'm waiting all checks to be started.

**Comment by filimonov** [comment]
Scripts defining sequence of building docker images & passing envs and other parameters.
Also some html report building scripts. 

- will you share those?

**Comment by alexey-milovidov** [comment]
Yes, we must share these scripts https://github.com/ClickHouse/ClickHouse/issues/10825

**Comment by alesapin** [comment]
tests started, so I'll merge.

**Pull request merged**
