### PR TITLE
Fix min_age_to_force_merge_on_partition_only

### LINKED ISSUE #72106: min_age_to_force_merge_on_partition_only does not merge down every partition
In this example, even though both `min_age_to_force_merge_on_partition_only` and `min_age_to_force_merge_seconds` are specified, some of the partitions are never merged down to a single part:
```sql
-- It has to be a ReplicatedMergeTree or SharedMergeTree 
CREATE TABLE t
(
    `x` int
)
ENGINE = ReplicatedMergeTree('/clickhouse/tables/{shard}/t', '{replica}')
PARTITION BY x % 5
ORDER BY tuple()
SETTINGS min_age_to_force_merge_on_partition_only = 1, min_age_to_force_merge_seconds = 1;

-- Run this twice or more to generate multiple parts per partition, could probably also use optimize_on_insert or manual values
INSERT INTO t SELECT * FROM generateRandom() LIMIT 10;
INSERT INTO t SELECT * FROM generateRandom() LIMIT 10;

-- Monitor parts
select partition, count() from system.parts where active and table = 't' group by all with totals order by partition;
```

There will always be at least one part that isn't merged down.

Looking at the logs, this keeps happening every minute (the sleep time between merge selections is 60s by default):
```sql
2024.11.19 18:09:54.046099 [ 1684759 ] {} <Trace> default.t (0e7f5c1d-7d6f-4373-b433-f2f9efa24e37) (MergerMutator): Checked 9 partitions, found 1 partitions with parts that may be merged: [-4] (max_total_size_to_merge=49450375168, merge_with_ttl_allowed=true)
...
2024.11.19 18:10:54.053824 [ 1684897 ] {} <Trace> default.t (0e7f5c1d-7d6f-4373-b433-f2f9efa24e37) (MergerMutator): Checked 9 partitions, found 1 partitions with parts that may be merged: [-4] (max_total_size_to_merge=49451085824, merge_with_ttl_allowed=true)
...
2024.11.19 18:11:54.065545 [ 1685012 ] {} <Trace> default.t (0e7f5c1d-7d6f-4373-b433-f2f9efa24e37) (MergerMutator): Checked 9 partitions, found 1 partitions with parts that may be merged: [-4] (max_total_size_to_merge=49446782976, merge_with_ttl_allowed=true)
```

It keeps trying to merge down the same partition even though this partition is already down to a single part. It never selects a partition that has several parts.

From what I can see, the code in `MergeTreeDataMergerMutator::getBestPartitionToOptimizeEntire` doesn't check whether a partition has more than one part, and the callers are giving it lists that include partitions with a single part:
https://github.com/ClickHouse/ClickHouse/blob/98f7681497c72bf9612b43763a816a837bf16680/src/Storages/MergeTree/MergeTreeDataMergerMutator.cpp#L619

### PR DESCRIPTION
**Pull request by cwurm**
Fixes https://github.com/ClickHouse/ClickHouse/issues/72106.

`min_age_to_force_merge_on_partition_only` can get stuck easily when it continually selects the same partition for merging, even though it's already merged down to a single part.

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix a bug where `min_age_to_force_merge_on_partition_only` was getting stuck trying to merge down the same partition repeatedly that was already merged to a single part and not merging partitions that had multiple parts.

### CODE REVIEW

**Comment by robot-ch-test-poll4** [comment]
*This is an automated comment for commit ab636cdf828d52dca7d272287dee957851e92ba9 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/72209/ab636cdf828d52dca7d272287dee957851e92ba9/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

**Review by antonio2368 — COMMENTED** [review]
Fix LGTM but flaky check failed for new test for some reason

**Comment by cwurm** [comment]
> Fix LGTM but flaky check failed for new test for some reason

Fixed it.

It failed again but doesn't say which test it was. `S3_ERROR No such key thrown` looks unrelated though.

**Comment by antonio2368** [comment]
Yes it's unrelated
Thanks for the fix

**Review by antonio2368 — APPROVED** [review]

**Pull request merged**
