### PR TITLE
Set encryption algorithm explicitly.

### PR DESCRIPTION
**Pull request by vitlibar**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category:
- Improvement

Changelog entry:
After https://github.com/ClickHouse/ClickHouse/pull/26377. Encryption algorithm now should be specified explicitly if it's not default (`aes_128_ctr`):

```
<disk_local_encrypted>
    <type>encrypted</type>
    <disk>disk_local</disk>
    <path>encrypted/</path>
    <algorithm>aes_192_ctr</algorithm>
    <key_hex>109105c600c12066f82f1a4dbb41a08e05c600c12066f82f</key_hex>
</disk_local_encrypted>
```

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
Ok, but why it's named `encryption`? Maybe `algorithm`?

**Comment by alexey-milovidov** [comment]
Ok.

Two more thoughts.

1. There can be a need for key rotation - using new keys over time.
Maybe we can add a field to the header (before IV) for key number.
It can be 64bit integer, default zero.
And user can provide more than one key in config.

2. It is reasonable to also identify encryption algorithm in the header.
It can be another 64bit field witn algorithm id.
The reasons is:
We can slightly change the details of the algorithm while preserving backward compatibility.
So, it is something like version.
But AES variant will be also written to this field just in case.

**Comment by vitlibar** [comment]
> Ok.
> 
> Two more thoughts.
> 
> 1. There can be a need for key rotation - using new keys over time.
>    Maybe we can add a field to the header (before IV) for key number.
>    It can be 64bit integer, default zero.
>    And user can provide more than one key in config.
> 2. It is reasonable to also identify encryption algorithm in the header.
>    It can be another 64bit field witn algorithm id.
>    The reasons is:
>    We can slightly change the details of the algorithm while preserving backward compatibility.
>    So, it is something like version.
>    But AES variant will be also written to this field just in case.

So instead of 16 bytes IV we're going to have 32 bytes header (8 bytes for encryption algorithm + 8 bytes for key number + 16 bytes for IV). We can treat the encryption algorithm as some kind of 
version, but anyway in the future it's better not to change the size of this header because currently we can calculate the size of non-encrypted data just by substracting the header's size from the size of an encrypted file.

**Comment by alexey-milovidov** [comment]
Yes, so let's change it to 32 bytes in advance.

**Comment by alexey-milovidov** [comment]
Let's change the header to 32 bytes just in case before anyone will start to use this feature :)

**Pull request merged**
