### PR TITLE
Lexer, ast, checksum and column specs fuzzers added

### PR DESCRIPTION
**Pull request by kyprizel**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Build/Testing/Packaging Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Adding fuzzers and preparing for oss-fuzz integration.

Detailed description / Documentation draft:
Fuzzers implemented for:
* AST parser (Select, Create)
* Lexer
* Column name deserializer
* Checksum deserializer
Dictionary for ast lexer generated.
Initial corpuses for column and checksum deserializers implemented.
Name convention for fuzzers changed ("_fuzzer" postifx in now used instead of "_fuzz").

### CODE REVIEW

**Comment by qoega** [comment]
Did you find any bugs while running new fuzzing tests?

Can you add README for other developers how to run fuzz tests? Actually we better add correct way to run fuzz tests as docs are outdated in this case https://clickhouse.tech/docs/en/development/tests/#fuzzing

You created dictionaries from system tables? Can you add corresponding queries/scripts to update them in future?

**Comment by kyprizel** [comment]
Dictionaries are generated from the source code and the scripts are not good enough to share.
Yes, I've found some vulnerabilities and they were fixed already.

Those fuzz tests are for "libfuzzer" engine and will let me add ClickHouse as a part of Google Oss-Fuzz project. I'll add the fuzzing documentation later.

**Comment by qoega** [comment]
If you need some help, fell free to contact us directly. Especially to add tests in CI.

**Comment by kyprizel** [comment]
Ok, added minimal documentation. Docker configuration for fuzzing will be in separate pull.

**Pull request merged**
