### PR TITLE
Enable clang-tidy in headers

### PR DESCRIPTION
**Pull request by rschu1ze**
Spend a good chunk of the day enabling clang-tidy in `src/` headers (see ".clang-tidy").

Notes:
- disabled check `-clang-analyzer-optin.performance.Padding` because it was overall too noisy and optimized padding is a microoptimization
- the majority of warnings were harmless, e.g. passing by-const-value instead of by-value, redundant `virtual` keyword when `override` or `final` are specified, missing `const` on getter functions, anonymous namespaces in headers, `.size() > 0` instead of `.contains()`
- some places revealed a possible misuse (did not find actual misuse), e.g. default arguments in virtual functions (please don't do that), variable use after moving from it (<-- hard to track for static analysis, it was a false positive)
- sometimes performance optimization were missing, e.g. intended pass-by-const-reference but the programmer forgot `&`, filling a vector in a loop but no `.reserve()` was called on the vector beforehand
- there were also some obscure warnings which I checked but then suppressed

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by robot-ch-test-poll1** [comment]
*This is an automated comment for commit b55eee1f58c133cbc991b84f6f7781def1d6131a with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/61406/b55eee1f58c133cbc991b84f6f7781def1d6131a/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

**Comment by rschu1ze** [comment]
I'll bet that within 24 hours, 5 files will be in merge conflict.

**Comment by qoega** [comment]
Fast test: https://s3.amazonaws.com/clickhouse-test-reports/61406/b55eee1f58c133cbc991b84f6f7781def1d6131a/fast_test.html
segmentation fault. Strange that we do not report it in pretty way
```
2024.03.14 21:50:34.791572 [ 178360 ] {} <Fatal> BaseDaemon: ########## Short fault info ############
2024.03.14 21:50:34.791611 [ 178360 ] {} <Fatal> BaseDaemon: (version 24.3.1.1, build id: 70FEAD72521FE4853A9F915995858878BF13B572, git hash: 906152a29d27b56b144e3a14444237245767ddd8) (from thread 177475) Received signal 11
2024.03.14 21:50:34.791637 [ 178360 ] {} <Fatal> BaseDaemon: Signal description: Segmentation fault
2024.03.14 21:50:34.791649 [ 178360 ] {} <Fatal> BaseDaemon: Address: NULL pointer. Access: read. Address not mapped to object.
2024.03.14 21:50:34.791660 [ 178360 ] {} <Fatal> BaseDaemon: Stack trace: 0x0000000007885ca8 0x0000000007a935df
2024.03.14 21:50:34.791667 [ 178360 ] {} <Fatal> BaseDaemon: ########################################
2024.03.14 21:50:34.791706 [ 178360 ] {} <Fatal> BaseDaemon: (version 24.3.1.1, build id: 70FEAD72521FE4853A9F915995858878BF13B572, git hash: 906152a29d27b56b144e3a14444237245767ddd8) (from thread 177475) (query_id: 8e427947-e24f-490e-a1c1-7927d6b25ceb) (query: SELECT * FROM (SELECT 1 as A, 2 as B) X
ALL LEFT JOIN (SELECT 3 as A, 2 as B) Y
USING (B);) Received signal Segmentation fault (11)
2024.03.14 21:50:34.791728 [ 178360 ] {} <Fatal> BaseDaemon: Address: NULL pointer. Access: read. Address not mapped to object.
2024.03.14 21:50:34.791744 [ 178360 ] {} <Fatal> BaseDaemon: Stack trace: 0x0000000007885ca8 0x0000000007a935df
```

**Review by alexey-milovidov — APPROVED** [review]
LGTM

**Comment by Algunenano** [comment]
> Strange that we do not report it in pretty way

Musl builds don't have good stacktraces, and fast tests are built with musl

**Comment by alexey-milovidov** [comment]
@Algunenano, this is incorrect: Musl builds are made with good stack traces. If it is no longer the case, it requires additional investigation.

**Comment by rschu1ze** [comment]
Sorry, need to merge from `master` again to include #61519.

**Comment by rschu1ze** [comment]
Tests in previous run were green, merge was only blocked by this build failure https://s3.amazonaws.com/clickhouse-builds/PRs/61406/0dff12694241d8c367f65b84a3f1e4d20ffcf7e3/binary_tidy/build_log.log due to `bugprone-forward-declaration-namespace`, I disabled it here https://github.com/ClickHouse/ClickHouse/pull/61406/commits/94a347cc419c2af101933d211d028771efd9e966

**Pull request merged**
