### PR TITLE
Implement neighbour() function

### PR DESCRIPTION
**Pull request by alex-krash**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

For changelog. Remove if this is non-significant change.

Category (leave one):

    New Feature

Short description (up to few sentences):
New function neighbour(value, offset[, default_value]). Allows to reach prev/next value within column. 

Detailed description (optional):
This function is a poor emulation of window function LEAD() http://www.sqltutorial.org/sql-window-functions/sql-lead/, without support for OVER() section. It can be applied to enrich the data from sorted sub-query.

Was unable to deal with #5867 , had to re-create branch

### CODE REVIEW

**Comment by alex-krash** [comment]
@alexey-milovidov , I've implemented everything in this function, as we discussed. Tried to make [test](https://github.com/yandex/ClickHouse/blob/ea9cf3a62f42f0ed48efe7baac2be46bfaa7ae5e/dbms/tests/queries/0_stateless/00957_neighbour.sql) as detailed, as possible.

**Comment by geldot** [comment]
The rest of Clickhouse uses US English spelling (materialize, color, center) rather than British English (materialise, colour, centre) so for consistency this function should probably be 'neighbor' without the 'u'

Not my preference, but mixing the two dialects gets confusing.

**Comment by alexey-milovidov** [comment]
@geldot That's right! I can fix it after merge.

**Comment by alexey-milovidov** [comment]
It doesn't work:

```
milovidov-Latitude-E7470 :) SELECT number, neighbor(number, number) FROM system.numbers LIMIT 10

SELECT 
    number, 
    neighbor(number, number)
FROM system.numbers
LIMIT 10

┌─number─┬─neighbor(number, number)─┐
│      0 │                        0 │
│      1 │                        2 │
│      2 │                        4 │
│      3 │                        6 │
│      4 │                        8 │
│      5 │     11936128518282651045 │
│      6 │                        0 │
│      7 │                        0 │
│      8 │                        0 │
│      9 │                        0 │
└────────┴──────────────────────────┘
```

**Comment by alexey-milovidov** [comment]
```
milovidov-Latitude-E7470 :) SELECT number, neighbor(number, number, 0) FROM system.numbers LIMIT 10

SELECT 
    number, 
    neighbor(number, number, 0)
FROM system.numbers
LIMIT 10

┌─number─┬─neighbor(number, number, 0)─┐
│      0 │                           0 │
│      1 │                           2 │
│      2 │                           4 │
│      3 │                           6 │
│      4 │                           8 │
│      5 │        11936128518282651045 │
│      6 │         6510615555426900570 │
│      7 │         6510615555426900570 │
│      8 │         6510615555426900570 │
│      9 │         6510615555426900570 │
└────────┴─────────────────────────────┘
```

**Comment by alexey-milovidov** [comment]
Fixed in master.

**Pull request merged**
