### PR TITLE
Add support for FixedString input to base64 functions

### PR DESCRIPTION
**Pull request by ltrk2**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Add support for FixedString input to base64 coding functions

### CODE REVIEW

**Comment by ltrk2** [comment]
@davenger thanks for noticing. I added some simple tests.

**Review by yakov-olkhovskiy — APPROVED** [review]
very good job on refactoring

**Comment by ltrk2** [comment]
@yakov-olkhovskiy thanks, I appreciate the feedback!

**Comment by ltrk2** [comment]
I can see that many builds are failing, but none of the logs contain any trace of an actual build process.

For example, [BuilderDebMsan](https://github.com/ClickHouse/ClickHouse/actions/runs/3377450536/jobs/5606749220#logs) consists of these lines only:
```
2022-11-02T12:39:37.8066026Z Requested labels: self-hosted, builder
2022-11-02T12:39:37.8066153Z Job defined at: ClickHouse/ClickHouse/.github/workflows/pull_request.yml@refs/pull/42285/merge
2022-11-02T12:39:37.8066205Z Waiting for a runner to pick up this job...
2022-11-02T13:01:30.4443083Z Job is about to start running on the runner: i-0ed7a1a53f2d08feb (organization)
```

@alexey-milovidov @yakov-olkhovskiy could you tell help me if these are just issues with the build environment, or is something actually wrong that I need to fix?

**Comment by yakov-olkhovskiy** [comment]
@ltrk2 don't worry, it's just slow, it should pick up eventually.

**Comment by ltrk2** [comment]
@yakov-olkhovskiy great, thank you!

**Pull request merged**
