### PR TITLE
Use clang-18 in CI

### PR DESCRIPTION
**Pull request by alexey-milovidov**
### Changelog category (leave one):
- Build/Testing/Packaging Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
ClickHouse is built with clang-18. A lot of new checks from clang-tidy-18 have been enabled.

### CODE REVIEW

**Comment by robot-ch-test-poll1** [comment]
*This is an automated comment for commit ee772aaf0f7a05fafb3fa286419148211362b0d6 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/60469/ee772aaf0f7a05fafb3fa286419148211362b0d6/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/60469/ee772aaf0f7a05fafb3fa286419148211362b0d6/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Comment by qoega** [comment]
Many new crashes:
- https://s3.amazonaws.com/clickhouse-test-reports/60469/ee772aaf0f7a05fafb3fa286419148211362b0d6/ast_fuzzer__debug_.html `SELECT dictGetOrDefault('range_hashed_dictionary', 'value', 1, toUInt64(materialize(toLowCardinality(6))), 'DefaultValue')`
- https://github.com/ClickHouse/ClickHouse/issues/60484
- Unit tests [ubsan](https://s3.amazonaws.com/clickhouse-test-reports/60469/ee772aaf0f7a05fafb3fa286419148211362b0d6/unit_tests__ubsan_.html) 
```
/build/src/Compression/CompressionCodecDoubleDelta.cpp:346:76: runtime error: negation of -2147483648 cannot be represented in type 'int'; cast to an unsigned type to negate this value to itself
    #0 0x55a5527297f5 in unsigned int DB::(anonymous namespace)::compressDataForType<unsigned int>(char const*, unsigned int, char*) build_docker/./src/Compression/CompressionCodecDoubleDelta.cpp:346:67
    #1 0x55a5527297f5 in DB::CompressionCodecDoubleDelta::doCompressData(char const*, unsigned int, char*) const build_docker/./src/Compression/CompressionCodecDoubleDelta.cpp:501:27
    #2 0x55a5527502ab in DB::ICompressionCodec::compress(char const*, unsigned int, char*) const build_docker/./src/Compression/ICompressionCodec.cpp:86:39
    #3 0x55a53f4c126a in void (anonymous namespace)::testTranscoding<(anonymous namespace)::NoOpTimer>((anonymous namespace)::NoOpTimer&, DB::ICompressionCodec&, (anonymous namespace)::CodecTestSequence const&, std::__1::optional<double>) build_docker/./src/Compression/tests/gtest_compressionCodec.cpp:469:39
    #4 0x55a53f4c126a in (anonymous namespace)::CodecTest::testTranscoding(DB::ICompressionCodec&) build_docker/./src/Compression/tests/gtest_compressionCodec.cpp:518:9
    #5 0x55a53f4c126a in (anonymous namespace)::CodecTest_TranscodingWithDataType_Test::TestBody() build_docker/./src/Compression/tests/gtest_compressionCodec.cpp:532:5
    #6 0x55a54bdc3070 in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) build_docker/./contrib/googletest/googletest/src/gtest.cc:2612:10
    #7 0x55a54bdc3070 in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) build_docker/./contrib/googletest/googletest/src/gtest.cc:2648:14
    #8 0x55a54bdc2f58 in testing::Test::Run() build_docker/./contrib/googletest/googletest/src/gtest.cc:2687:5
    #9 0x55a54bdc44e1 in testing::TestInfo::Run() build_docker/./contrib/googletest/googletest/src/gtest.cc:2836:11
    #10 0x55a54bdc55f4 in testing::TestSuite::Run() build_docker/./contrib/googletest/googletest/src/gtest.cc:3015:30
    #11 0x55a54bdd68cd in testing::internal::UnitTestImpl::RunAllTests() build_docker/./contrib/googletest/googletest/src/gtest.cc:5921:44
    #12 0x55a54bdd62b0 in bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) build_docker/./contrib/googletest/googletest/src/gtest.cc:2612:10
    #13 0x55a54bdd62b0 in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) build_docker/./contrib/googletest/googletest/src/gtest.cc:2648:14
    #14 0x55a54bdd6126 in testing::UnitTest::Run() build_docker/./contrib/googletest/googletest/src/gtest.cc:5485:10
    #15 0x55a53f3e9f0d in RUN_ALL_TESTS() build_docker/./contrib/googletest/googletest/include/gtest/gtest.h:2316:73
    #16 0x55a53f3e9f0d in main build_docker/./src/Common/tests/gtest_main.cpp:17:12
    #17 0x7f3e07723d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f) (BuildId: c289da5071a3399de893d2af81d6a30c62646e1e)
    #18 0x7f3e07723e3f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e3f) (BuildId: c289da5071a3399de893d2af81d6a30c62646e1e)
    #19 0x55a53f0700ed in _start (/unit_tests_dbms+0x182810ed) (BuildId: 3d46fcdc80582dbe6d3c3916a0377dc283d9153b)

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /build/src/Compression/CompressionCodecDoubleDelta.cpp:346:76 ```

**Comment by rschu1ze** [comment]
In `cmake/tools.cmake`, please raise `CLANG_MINIMUM_VERSION` to `17` (we want to stay compatible with the last 2 versions).

**Comment by alexey-milovidov** [comment]
RabbitMQ has a bug.

**Comment by kssenii** [comment]
> RabbitMQ has a bug.

Fixed in [9a82d62](https://github.com/ClickHouse/ClickHouse/pull/60469/commits/9a82d62b37b6ff5b3df170fa2bf40ff24c8da445). Also created a separate PR in order to be able to backport it https://github.com/ClickHouse/ClickHouse/pull/63515 if needed.

**Comment by alexey-milovidov** [comment]
clang-tidy has a bug: https://github.com/llvm/llvm-project/issues/91872

**Pull request merged**
