### PR TITLE
Support true UUID type for MongoDB engine

### PR DESCRIPTION
**Pull request by azat**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Support true UUID type for MongoDB engine

### CODE REVIEW

**Comment by robot-clickhouse-ci-1** [comment]
*This is an automated comment for commit f6dace8ef50df151366fd34585b6a7e4690b2473 with description of existing statuses. It's updated for the latest CI running*

[❌ Click here](https://s3.amazonaws.com/clickhouse-test-reports/66671/f6dace8ef50df151366fd34585b6a7e4690b2473/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Style check</td><td>Runs a set of checks to keep the code style clean. If some of tests failed, see the related log from the report</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/66671/f6dace8ef50df151366fd34585b6a7e4690b2473/style_check.html">❌ failure</a></td></tr>
<tbody>
</table>

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
@azat tests have failed.

**Comment by alexey-milovidov** [comment]
@azat, check and fix 02982_perf_introspection_for_inserts

**Comment by alexey-milovidov** [comment]
There are many failed tests here.

**Comment by azat** [comment]
>Integration tests (tsan) [5/6] — fail: 1, passed: 609

- https://github.com/ClickHouse/ClickHouse/issues/56686

>Integration tests flaky check (asan) — Failed tests found: error: 0, passed: 51, fail: 9, skipped: 0, broken: 0, not_fail: 0

```
E           Code: 57. DB::Exception: Received from 172.16.3.4:9000. DB::Exception: Table default.simple_mongo_table_2 already exists. Stack trace:
```

**Comment by azat** [comment]
>[AST fuzzer (debug) — Logical error: 'Inconsistent AST formatting: the query:](https://s3.amazonaws.com/clickhouse-test-reports/66671/e126d334087562c08e8432385c3e37ec7c9759f1/ast_fuzzer__debug_.html)

- https://github.com/ClickHouse/ClickHouse/pull/67774

>Integration tests flaky check (asan) — Failed tests found: error: 0, passed: 56, fail: 4, skipped: 0, broken: 0, not_fail: 0

Fixed - https://github.com/ClickHouse/ClickHouse/commit/a49924b3834d577827279f6278e5df21e3065035

>[AST fuzzer (ubsan) — /build/src/Functions/if.cpp:730:47: runtime error: downcast of address 0x7f6425978ca8 which does not point to an object of type 'const Da...](https://s3.amazonaws.com/clickhouse-test-reports/66671/e126d334087562c08e8432385c3e37ec7c9759f1/ast_fuzzer__ubsan_.html)

```
/build/src/Functions/if.cpp:730:47: runtime error: downcast of address 0x7f6425978ca8 which does not point to an object of type 'const DataTypeMap'	
```

- https://github.com/ClickHouse/ClickHouse/pull/67777

**Comment by azat** [comment]
Ci is green!

**Comment by maitruonggiang2912** [comment]
Thank you for your suggestion. I was able to resolve my issue with the UUID data type. However, I am encountering an issue with counting data when using the MongoDB Engine. Has anyone experienced this before? Please share your solution with me. Thanks.
https://github.com/ClickHouse/ClickHouse/issues/69060

**Pull request merged**
