### PR TITLE
Extend system.functions with in-source documentation

### PR DESCRIPTION
**Pull request by DanRoscigno**
End Goal:
- source code is the source of truth for docs
- reduce the burden on developers; when devs edit their code they edit the docs in the same file
- auto-generate docs in CI; when the code changes generate new markdown

Problem:
There are examples embedded in the source, but they are not being copied to the system tables 
when the `description` information is copied over.  This PR adds the embedded examples and
will be extended to add the rest of the available information.

Step 2 will be to increase the amount of embedded documentation by copying from the markdown
files into the source (so that the source is the source of truth for the docs)

Step 3 will be to automate the generation of the docs in CI

### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Copies embedded examples to a new field `example` in `system.functions` to supplement the field `description`

### CODE REVIEW

**Comment by rschu1ze** [comment]
[Test failures](https://s3.amazonaws.com/clickhouse-test-reports/49222/fb39dc3f19ca7780c12af3f1a664996fef44f30c/fast_test.html) are expected, this is because the output of the system view changed. I'll try to fix these tests locally.

**Comment by DanRoscigno** [comment]
This is great Robert, I had started to make a list of things to cover (syntax, etc.) and you have all of the ones I thought of plus more.  Thanks so much.

What is the NOLINT for on line 73?

**Comment by UnamedRus** [comment]
I like idea of https://github.com/ClickHouse/ClickHouse/issues/36023 issue for arguments (or signature) of functions.

Ie it will look like:

```
SELECT name, is_aggregate, case_insensitive, origin, arguments, argument_types FROM system.functions WHERE name = 'uniq' OR name = 'has' OR name = 'concat';
```
image

**Comment by DanRoscigno** [comment]
> I like idea of #36023 issue for arguments (or signature) of functions.
> 
> Ie it will look like:
> 
> ```
> SELECT name, is_aggregate, case_insensitive, origin, arguments, argument_types FROM system.functions WHERE name = 'uniq' OR name = 'has' OR name = 'concat';
> ```
> 
> image

Thanks @UnamedRus 

Would arguments and syntax provide the functionality that you asked for @sarah-mdv  

[`arguments`](https://github.com/ClickHouse/ClickHouse/blob/b6e65ddeffd7e2e8cb816db776ec965ddc7b9563/src/Common/Documentation.h#L56)

[`syntax`](https://github.com/ClickHouse/ClickHouse/blob/b6e65ddeffd7e2e8cb816db776ec965ddc7b9563/src/Common/Documentation.h#L53)

**Comment by rschu1ze** [comment]
A few thoughts:
- While this PR adds new columns to `system.functions`, these are deliberately not publicly documented for now ([here](https://clickhouse.com/docs/en/operations/system-tables/functions)), because it is not 100% clear yet which fields make the most sense, how they are populated and formatted in the system table.
- I generally like the idea of #36023. Using reflection to populate `system.functions` has a certain charm. Unfortunately, functions currently neither communicate their arguments (mandatory or optional) nor the datatypes of the arguments to the function factory which would be the most natural place to collect such information. Instead, arguments/datatypes are "implicitly" encoded individually for each function, making it infeasible to extract the information automatically (at least for now).
- This doesn't mean that there can or should not be a standardized way of instrumenting functions with signature "metadata" for use in reflection in future. Imho, this is orthogonal to this PR which focusses on documentation. E.g. we could have two columns - one human-readable and the other one machine-readable.
- About human-readable signature information (i.e. everything below [official function docs](https://clickhouse.com/docs/en/sql-reference/functions)): Documentation of the arguments and sometimes also of the return type need a description to be useful. So this information needs to be embedded in the source as well.

**Comment by DanRoscigno** [comment]
I have one more column to suggest, but I have to think about what it should be named.  Let me start with the problem statement:

Our settings documentation has settings that should be set in /etc/clickhouse/server/config.d/filename.xml, some that should be in a specific section of ...users.d/filename.xml, some that should be set on a session basis, and some that should be set in a user's profile in Cloud.  (are there more options?  I don't think so).  I think that we need a list of places/methods for configuring these settings.

Example, if you configure [max_concurrent_connections_for_all_users](https://github.com/ClickHouse/ClickHouse/issues/38357) in config.d, ClickHouse will not start.

Maybe the column is `configuration`?

**Comment by rschu1ze** [comment]
@DanRoscigno Completely agree. Note that docs for settings docs follow a different "template" than function docs. E.g. only the former has "default value" and "possible values" fields. Also, settings docs are exposed in a different system table ([this one](https://clickhouse.com/docs/en/operations/system-tables/settings)). I think we should build (in a separate PR) a second C++ `Documentation` class specifically tailored to the needs of settings documentation.

**Pull request merged**
