### PR TITLE
Fix clickhouse-su to accept not only user/group names, but as well IDs

### PR DESCRIPTION
**Pull request by Felixoid**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
When user/group is given as ID, the `clickhouse su` fails. This patch fixes it to accept `UID:GID` as well.
### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Run only fuzzers related jobs (libFuzzer fuzzers, AST fuzzers, etc.)
- [ ]  Exclude: AST fuzzers
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-ch-test-poll3** [comment]
*This is an automated comment for commit 2a9b72627bee782aac58114a8e6e902e8aee0763 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/71626/2a9b72627bee782aac58114a8e6e902e8aee0763/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/337ba49be007099b99fb69942ca955e7efcfcade/docs_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Comment by Felixoid** [comment]
Here how it's broken now:

```
# clickhouse su root:0 ls
Code: 36. DB::Exception: Group 0 is not found in the system. (BAD_ARGUMENTS) (version 24.9.2.42 (official build))
# clickhouse su 0:root ls
Code: 36. DB::Exception: User 0 is not found in the system. (BAD_ARGUMENTS) (version 24.9.2.42 (official build)
```

Fixes #42400, is related to #42270

**Comment by Felixoid** [comment]
Tested it as the following with the binary from [fast tests](https://s3.amazonaws.com/clickhouse-test-reports/71626/2a9b72627bee782aac58114a8e6e902e8aee0763/fast_test.html):

```
$ docker run -it --rm --volume ~/Downloads/clickhouse:/clickhouse ubuntu:20.04 bash
root@5a534c6ca845:/# /clickhouse su 0:0 ls
bin  boot  clickhouse  dev  etc  home  lib  lib32  lib64  libx32  media  mnt  opt  proc  root  run  sbin  srv  sys  tmp  usr  var
root@5a534c6ca845:/# /clickhouse su 0:root ls
bin  boot  clickhouse  dev  etc  home  lib  lib32  lib64  libx32  media  mnt  opt  proc  root  run  sbin  srv  sys  tmp  usr  var
root@5a534c6ca845:/# /clickhouse su root:0 ls
bin  boot  clickhouse  dev  etc  home  lib  lib32  lib64  libx32  media  mnt  opt  proc  root  run  sbin  srv  sys  tmp  usr  var
root@5a534c6ca845:/# /clickhouse su root:root ls
bin  boot  clickhouse  dev  etc  home  lib  lib32  lib64  libx32  media  mnt  opt  proc  root  run  sbin  srv  sys  tmp  usr  var
```

**Review by pufit — APPROVED** [review]

**Comment by Felixoid** [comment]
The broken [test_prometheus_protocols/test.py::test_64bit_id](https://play.clickhouse.com/play?user=play#ICAgIFNFTEVDVAogICAgICAgIHJlcG9ydF91cmwKICAgIEZST00gY2hlY2tzCiAgICBXSEVSRSAxCiAgICAgICAgQU5EIChoZWFkX3JlZiA9ICdtYXN0ZXInKQogICAgICAgIEFORCAodGVzdF9uYW1lID0gJ3Rlc3RfcHJvbWV0aGV1c19wcm90b2NvbHMvdGVzdC5weTo6dGVzdF82NGJpdF9pZCcpCiAgICAgICAgQU5EIHRvRGF0ZShjaGVja19zdGFydF90aW1lKSA9ICcyMDI0LTExLTA4Jw==) is broken in master. I am overriding `Mergeable Check` to not leave it to the next week.

**Comment by clickgapai** [comment]
Hi @Felixoid @pufit — while reviewing this PR I found the following:

- **Bug (P2):** Non-existent user/group names in `clickhouse-su` silently resolve to uid/gid 0 (root) instead of erroring — https://github.com/ClickHouse/ClickHouse/issues/104720

Happy to discuss — close anything that's wrong or already addressed.

**Pull request merged**
