### PR TITLE
Change the ReplicatedMergeTree to use a pool of threads.

### PR DESCRIPTION
**Pull request by silviucpp**
Basic idea is :

	- We add BackgroundSchedulePool which can execute a function at a specific point in time. Basically all tasks are added in a queue and precessed by worker threads.
	- The most important difference between this and BackgroundProcessingPool is that we have the guarantee that the same function is not executed from many workers in the same time
	- Each of the following classes instead starting a thread will register a task in BackgroundSchedulePool and when they need to run will call schedule or scheduleAfter(duration) functions

This commit is moving:

`ReplicatedMergeTreeAlterThread` and `ReplicatedMergeTreeCleanupThread` to `BackgroundSchedulePool` and reduce the number of threads used by each `ReplicatedMergeTree` to 4.

NOTE: I did a minimum number of changes to be much simple to review the code

### CODE REVIEW

**Comment by silviucpp** [comment]
@alexey-milovidov  looking to the code in the following function:

```c++
void ReplicatedMergeTreePartCheckThread::start()
{
    std::lock_guard<std::mutex> lock(start_stop_mutex);

    if (need_stop)
        need_stop = false;
    else
        thread = std::thread([this] { run(); });
}
```

I'm still wonder if it's a mistake or not the else branch .. I'm wonder if the correct version is not:

```c++
void ReplicatedMergeTreePartCheckThread::start()
{
    std::lock_guard<std::mutex> lock(start_stop_mutex);

    if (need_stop)
        need_stop = false;
    thread = std::thread([this] { run(); });
}
```

**Comment by alexey-milovidov** [comment]
Yes, this looks very suspicious. I will try to figure out.

**Comment by alexey-milovidov** [comment]
It looks correct.

`need_stop` set to true is "request to stop".
If requested to stop, we must wait for thread to finish.
When thread is finished, then request to stop is fulfilled and `need_stop` is set to false.

In method `start`, if the "request to stop" is active, we don't start thread and thus request to stop is fulfilled, and we set `need_stop` to false.

**Comment by silviucpp** [comment]
Hello @alexey-milovidov ,

So my notice is that start and end are protected by mutex so concurrent access it's out of discussion.

In start method need_stop can be true only in case stop was called two times in row. 
First time the thread being still alive thread.joinable() branch is executed and second time is not thread being dead already which result in need_stop = true.

Next start() will only put the flag to need_stop = false but wont be any thread that will run as time the thread was already finished and a new one is not created

What do you think ?
Silviu

Code looks a bit strange :)

**Comment by ztlpn** [comment]
Here is the problem this code is supposed to solve: there are two threads that concurrently start and stop the PartCheckThread - the RestartingThread and the AlterThread. Each of these threads alternates start() and stop() calls, but this is not true in general - we can have two stop() calls and then two start() calls. Now during the second stop() call the PartCheckThread is already stopped, but we need to remember the fact that we want it stopped and will restart it later. Later, during the first start() call of the two we see that the other thread wanted PartCheckThread to be in the stopped state so we do nothing except clearing the flag. The PartCheckThread will be started for real during the second start() call.

Note that if we would always launch the thread during the start() call, we could end up displacing an already running thread - that would result in std::terminate().

The code is not ideal and probably warrants a lengthy comment and a more descriptive name for the need_stop flag.

**Comment by silviucpp** [comment]
@ztlpn  thanks ! make sense now

**Comment by silviucpp** [comment]
@alexey-milovidov @ztlpn there are any tests I can run to check the replication functionality ? I did manual tests including restarting zookeper, replicas and data seems consistent on this branch that's using a pool of threads.

I'll write some tests to see how behaves with 100k tables that are writing in the same time but I was wonder if there is something I can already run

Thanks,
Silviu

**Comment by silviucpp** [comment]
@alexey-milovidov do you think you can run the integration tests and not available public tests on this branch ? I already rebased all the changes with last master and you can see now as a single commit. 

In the meantime I want to write some load tests with lot of tables writing in the same time to see how behaves

Silviu

**Comment by alexey-milovidov** [comment]
Yes. There is a chance I will do today.

**Comment by silviucpp** [comment]
@alexey-milovidov btw all tasks that are taking more than 50ms are logged (in order to monitor your concern with threads locked for long time)

Silviu

**Comment by alexey-milovidov** [comment]
Started doing review...

**Comment by alexey-milovidov** [comment]
BTW, I am adding modifications in `silviucpp-replicated_merge_tree_thread_pool` branch (you can merge with it if you will add more commits).

**Comment by silviucpp** [comment]
@alexey-milovidov ok great !!

**Comment by silviucpp** [comment]
@alexey-milovidov one thing I noticed during working on this is that the entire code in this are at least it's abusing of friend classes and break the encapsulation. Sometimes when you come from outside and try to read a code it's pretty hard to track where a variable is read/changed as time even if it's private it's used in lot of other classes.

**Comment by alexey-milovidov** [comment]
Yes, `StorageReplicatedMergeTree` and related classes have broken encapsulation. It because of `StorageReplicatedMergeTree` had became too large and we started to move some code out of it (`ReplicatedMergeTreeAlterThread`, `ReplicatedMergeTreeRestartingThread`, `ReplicatedMergeTreeQueue`, etc), but with no success of real separation: the code remains coupled.

**Comment by silviucpp** [comment]
I merged with your branch and also with master . Was a small conflict because of the resharding removed

**Comment by alexey-milovidov** [comment]
Mostly Ok.

There is still some dirty places:
- dependency from ZooKeeper to BackgroundSchedulePool;
- context of MergeSelectingThread in StorageReplicatedMergeTree.cpp (very dirty);
- naming of various Thread classes (need to be renamed to Task).

**Comment by alexey-milovidov** [comment]
Functional tests Ok.

**Comment by silviucpp** [comment]
@alexey-milovidov  Yes I agree with you on all 3 dirty places. 

I have no idea how we can fix 1 :) and 3 maybe it's better to do it when you knows are no longer other branches with changes in this are to make merges with less conflicts.

I'm happy that you integrated the changes

Have a nice day,
Silviu

**Comment by alexey-milovidov** [comment]
I am interested, what are the results of performance testing on your use cases.

I see the following advantages of the modification:
- gdb was starting too slow when using large number of Replicated tables;
- output of `t apply all bt` from gdb became more readable;
- sometimes the user had to increase ulimit;

**Pull request merged**
