### PR TITLE
Implement parallel and splittable bzip2 read buffer and apply it to file engine

### PR DESCRIPTION
**Pull request by taiyang-li**
### Changelog category (leave one):
- Performance Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
In hadoop, single bzip2 compressed file is splitted into serveral splits, and each task processes one split, which means Hadoop MR could process single bzip2 file in parallel, especially when the file is large. Refer to: https://issues.apache.org/jira/browse/HADOOP-4012  

This pr will do what hadoop had did.  

parallel decompress & non-parallel parsing
``` sql
./clickhouse local --allow_parallel_decompress=1 --max_download_buffer_size=2097152 --input_format_parallel_parsing=1               
SELECT *
FROM file('/data1/liyang/root/2.bz2', 'JSONEachRow')
FORMAT `Null`

Query id: 4d8444b4-6428-4140-b60c-9660f828c44a

Ok.

0 rows in set. Elapsed: 2.172 sec. Processed 130.82 thousand rows, 6.24 MB (60.22 thousand rows/s., 2.87 MB/s.)
Peak memory usage: 220.40 MiB.
```

parallel decompress & parallel parsing 
``` sql 
SELECT *
FROM file('/data1/liyang/root/2.bz2', 'JSONEachRow')
FORMAT `Null`

Query id: 979a4c5e-718a-446f-b37f-bbb885221baf

Ok.

0 rows in set. Elapsed: 2.377 sec. Processed 166.81 thousand rows, 78.10 MB (70.19 thousand rows/s., 32.86 MB/s.)
Peak memory usage: 237.50 MiB.
```

non-parallel decompress & parallel parsing
``` sql
SELECT *
FROM file('/data1/liyang/root/2.bz2', 'JSONEachRow')
FORMAT `Null`

Query id: cfe79912-9e81-45fe-b67f-f2c74447cea4

Ok.

0 rows in set. Elapsed: 5.782 sec. Processed 181.98 thousand rows, 14.08 MB (31.47 thousand rows/s., 2.44 MB/s.)
Peak memory usage: 139.68 MiB.
```

### CODE REVIEW

**Comment by robot-ch-test-poll3** [comment]
*This is an automated comment for commit c7775acabb83fc5c32834848532467665a2d5716 with description of existing statuses. It's updated for the latest CI running*

[❌ Click here](https://s3.amazonaws.com/clickhouse-test-reports/58743/c7775acabb83fc5c32834848532467665a2d5716/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>❌ failure</td></tr>
<tbody>
</table>

**Comment by alexey-milovidov** [comment]
Could you also please take this PR to finish? https://github.com/ClickHouse/ClickHouse/pull/36933

**Comment by taiyang-li** [comment]
> Could you also please take this PR to finish? #36933

I'd like to

**Comment by taiyang-li** [comment]
Some tests based on `src/IO/examples/read_buffer_splittable_bzip2.cpp` and command line tool `bunzip2`. 
Notice that:
- `decompressFromSplits` first split the whole bzip2 file into multiple splits, then decompresses each split serially using new added `SplittableBzip2ReadBuffer`
- `parallelDecompressFromSplits` first split the whole bzip2 file into multiple splits, then decompresses each split parallally using new added `ParallelBzip2ReadBuffer`
- `decompressFromFile` decompresses  the whole bzip2 file using original `Bzip2ReadBuffer`

## Decompress small bzip2 file with size = 15MB

```
decompressFromSplits cost 7.20827 seconds 
parallelDecompressFromSplits cost 1.62089 seconds  (parallel settings: max_split_bytes = 2MB, max_working_readers = 16)
decompressFromFile cost 6.48392 seconds
```

``` bash
$ time bunzip2 -k  2.bz2  
bunzip2 -k 2.bz2  6.30s user 0.14s system 99% cpu 6.441 total
```

parallelDecompressFromSplits speeds up bzip2 decompression performance by 4x in current case. 


## Decompress large bzip2 file with size = 1.9GB

```
parallelDecompressFromSplits cost 184.129 seconds (parallel settings: max_split_bytes = 10MB, max_working_readers = 4)
parallelDecompressFromSplits cost 85.2435 seconds (parallel settings: max_split_bytes = 10MB, max_working_readers = 16)
parallelDecompressFromSplits cost 63.2412 seconds (parallel settings: max_split_bytes = 10MB, max_working_readers = 32))
decompressFromFile cost 513.919 seconds
```

``` bash 
$ time bunzip2 -k  1.bz2 
bunzip2 -k 1.bz2  527.65s user 11.66s system 99% cpu 8:59.65 total
``` 
parallelDecompressFromSplits speeds up bzip2 decompression performance by 8.1x at most in current case.

**Comment by taiyang-li** [comment]
I found there is another parallel bzip2 compress/decompress tool, which could decompress .bz2 files faster than current implementation...  
```
$ time lbzip2 -k -d 1.bz2

lbzip2 -k -d 1.bz2  930.88s user 18.83s system 2590% cpu 36.668 total
```

```
parallelDecompressFromSplits cost 63.2412 seconds (parallel settings: max_split_bytes = 10MB, max_working_readers = 32))
```

**Comment by taiyang-li** [comment]
Errors in performance tests seem not related to this PR: https://s3.amazonaws.com/clickhouse-test-reports/58743/e23744108cf35c91103d7e7d1c8e852b2d19c150/performance_comparison_[1_4]/report.html

image



https://s3.amazonaws.com/clickhouse-test-reports/58743/e23744108cf35c91103d7e7d1c8e852b2d19c150/stateless_tests_flaky_check__asan_.html will be fixed. 




I don't known how to avoid below errors, need your help..
https://s3.amazonaws.com/clickhouse-test-reports/58743/e23744108cf35c91103d7e7d1c8e852b2d19c150/upgrade_check__debug_.html
image

**Comment by taiyang-li** [comment]
https://s3.amazonaws.com/clickhouse-test-reports/58743/f5caa6809030ce71d88c5da6a41e666c3aafcc5f/stateless_tests_flaky_check__asan_.html  

I'm confused about this failed test, need your help, @Algunenano : which log should I look at to solve it？

**Comment by taiyang-li** [comment]
Hope for your reviews, thanks very much!

**Comment by taiyang-li** [comment]
@alexey-milovidov  I'm trying to use another parallel gz/xz codec implementation based on https://github.com/mxmlnkn/rapidgzip, which is different from current implementation in https://github.com/ClickHouse/ClickHouse/pull/36933. It is not an easy work to plant rapidgzip to CH. 

Could you please review and merge this PR firstly? Thanks!

**Comment by taiyang-li** [comment]
@alexey-milovidov Hope for you reviews, thanks!

**Comment by taiyang-li** [comment]
@alexey-milovidov any comments? Thanks !

**Comment by divanik** [comment]
Hi, @taiyang-li. I will be glad to review your PR. Could you, please, merge master and resolve conflicts to relaunch the CI system? Thanks in advance!

**Comment by divanik** [comment]
@taiyang-li, could you explain, please, why we can't use bzip2 library and need our own implementation of bzip2 decompression in SplittableBzip2ReadBuffer.cpp?

**Comment by taiyang-li** [comment]
> @taiyang-li, could you explain, please, why we can't use bzip2 library and need our own implementation of bzip2 decompression in SplittableBzip2ReadBuffer.cpp?

In hadoop, single bzip2 compressed file is splitted into serveral splits, and each task processes one split, which means Hadoop MR could process single bzip2 file in parallel, especially when the file is large.  I implemented it in CH, expecting that it brings performance benefits for bzip decompression.

**Comment by divanik** [comment]
> In hadoop, single bzip2 compressed file is splitted into serveral splits, and each task processes one split, which means Hadoop MR could process single bzip2 file in parallel, especially when the file is large. I implemented it in CH, expecting that it brings performance benefits for bzip decompression.

Thank you for your response. I believe that this logic is too complex for our codebase. Could you please list all the reasons why we cannot use the code from bzip2 to solve this task? Perhaps we only need to add a small amount of code to the bzip2 library to resolve this issue?

**Comment by taiyang-li** [comment]
> > In hadoop, single bzip2 compressed file is splitted into serveral splits, and each task processes one split, which means Hadoop MR could process single bzip2 file in parallel, especially when the file is large. I implemented it in CH, expecting that it brings performance benefits for bzip decompression.
> 
> Thank you for your response. I believe that this logic is too complex for our codebase. Could you please list all the reasons why we cannot use the code from bzip2 to solve this task? Perhaps we only need to add a small amount of code to the bzip2 library to resolve this issue?



> > In hadoop, single bzip2 compressed file is splitted into serveral splits, and each task processes one split, which means Hadoop MR could process single bzip2 file in parallel, especially when the file is large. I implemented it in CH, expecting that it brings performance benefits for bzip decompression.
> 
> Thank you for your response. I believe that this logic is too complex for our codebase. Could you please list all the reasons why we cannot use the code from bzip2 to solve this task? Perhaps we only need to add a small amount of code to the bzip2 library to resolve this issue?

I thought about it before, but I found reusing bzip2 lib to implement splittable bzip2 read buffer is probably impossible. bzip2 lib was designed to read the whole file instead of single file split. And it maybe the reason why hadoop implement splittable bzip2 read buffer without original bzip2 lib.

**Comment by taiyang-li** [comment]
It seems that the feature is not needed in CH.  Close it.

**Comment by alexey-milovidov** [comment]
It could be ok, but it requires testing.
It is not a problem to have a custom implementation of bzip2 if it's single-core performance is comparable or exceeds the original bzip2.

**Comment by alexey-milovidov** [comment]
I see that performance is good - we need to check the code and merge it.

**Comment by taiyang-li** [comment]
> I see that performance is good - we need to check the code and merge it.

The performance speed up was caused by parallel reading from a single bzip2 compressed file. I'll continue the work if you like it

**Comment by alexey-milovidov** [comment]
This could be good, but we need a lot of effort to read the code...

**Pull request closed without merging**
