### PR TITLE
s390x weakhash32 support

### PR DESCRIPTION
**Pull request by suzyw-w**
### Changelog category (leave one):
- Build Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
crc32 fix for s390x

### CODE REVIEW

**Comment by yakov-olkhovskiy** [comment]
@SuzyWangIBMer the original implementation of the slicing-by-8 algorithm is released by Intel under BSD license - is this implementation somehow derived? we want to be sure it's a copyright clean I guess...
cc @alexey-milovidov

**Comment by SuzyWangIBMer** [comment]
> @SuzyWangIBMer the original implementation of the slicing-by-8 algorithm is released by Intel under BSD license - is this implementation somehow derived? we want to be sure it's copyright clean I guess... cc @alexey-milovidov

The implementation is from 
[crc32-s390x](https://github.com/linux-on-ibm-z/crc32-s390x), submit new commits to include it as submodule

**Comment by SuzyWangIBMer** [comment]
@yakov-olkhovskiy Hi, can you help take a look at why stress test failed?

**Comment by yakov-olkhovskiy** [comment]
seems unrelated

**Review by yakov-olkhovskiy — APPROVED** [review]

**Pull request merged**
