### PR TITLE
Update argmax.md and argmin.md

### PR DESCRIPTION
**Pull request by mikekytyzov**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Documentation (changelog entry is not required

...

Detailed description / Documentation draft:
Update en/ru documentation for argmin and argmax functions with actual example
...

By adding documentation, you'll allow users to try your new feature immediately, not when someone else will have time to document it later. Documentation is necessary for all features that affect user experience in any way. You can add brief documentation draft above, or add documentation right into your patch as Markdown files in [docs](https://github.com/ClickHouse/ClickHouse/tree/master/docs) folder.

If you are doing this for the first time, it's recommended to read the lightweight [Contributing to ClickHouse Documentation](https://github.com/ClickHouse/ClickHouse/tree/master/docs/README.md) guide first.

Information about CI checks: https://clickhouse.tech/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by kitaisreal** [comment]
Hello @mikekytyzov.
Documentation seems fine, what is the purpose of this change ?

**Comment by mikekytyzov** [comment]
@kitaisreal not really fine :) 

Current function accepts always only two args, but in the examples provided below it became with only one, what is not valid :)

**Comment by kitaisreal** [comment]
@mikekytyzov we added support for single tuple argument about two month ago.
Connected to ClickHouse server version 21.3.1 revision 54447.

```
CREATE TABLE salary (user String, salary UInt64) ENGINE=TinyLog;
INSERT INTO salary VALUES ('user', 5000), ('manager', 3000), ('worker', 1000);
SELECT argMax(user, salary), argMax(tuple(user, salary), salary), argMax(tuple(user, salary)) FROM salary;
```
```
┌─argMax(user, salary)─┬─argMax(tuple(user, salary), salary)─┬─argMax(tuple(user, salary))─┐
│ user                 │ ('user',5000)                       │ ('user',5000)               │
└──────────────────────┴─────────────────────────────────────┴─────────────────────────────┘
```

**Comment by mikekytyzov** [comment]
@kitaisreal Okay. Sorry, i did not saw it on 21.3.1 version. I was checking on little lower. Thanks :)

**Pull request closed without merging**
