### PR TITLE
[WIP] Refactoring AlterCommands

### PR DESCRIPTION
**Pull request by nikitamikhaylov**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):

- Non-significant (changelog entry is not needed)

#7533

### CODE REVIEW

**Comment by nvartolomei** [comment]
#8439

**Comment by alexey-milovidov** [comment]
@nvartolomei These are two independent refactorings :)

**Comment by nvartolomei** [comment]
@alexey-milovidov to me it looks like the other one also covers what this one intended to do with encapsulating alters within StorageInMemoryMetadata, but maybe I didn't pay enough attention.

**Comment by alexey-milovidov** [comment]
@alesapin said that this PR to be closed.

**Pull request closed without merging**
