### PR TITLE
[WIP] Simple row policies

### PR DESCRIPTION
**Pull request by vitlibar**
Changelog category:
- Improvement

Changelog entry:
Add a new kind of row policies named `simple`. Before this PR we had two kinds or row policies: `permissive` and `restrictive`.
A `simple` row policy adds a new filter on a table without any side-effects like it was for permissive and restrictive policies.

For example,

```
CREATE ROW POLICY p1 ON mydb.mytable FOR SELECT USING a=1 AS simple TO user1
```

adds a filter on `mydb.mytable` for user `user1` without any side-effects for other users. It means that `user1` will see only rows with `a=1`, and `user2` will be able to see any rows.

To compare that with `permissive` and `restrictive` policies: if there are any permissive or restrictive policies defined for a table then all row access should be defined via row policies, i.e. for example

```
CREATE ROW POLICY p1 ON mydb.mytable FOR SELECT USING a=1 AS permissive TO user1
```

makes a system where user `user1` will see only rows with `a=1`, and `user2` won't be able to see any rows.

### CODE REVIEW

**Comment by yakov-olkhovskiy** [comment]
LGTM
some relevant functional tests failed in CI, but I've tested manually and they seems fine

**Comment by yakov-olkhovskiy** [comment]
@vitlibar do we need some docs update btw?

**Review by yakov-olkhovskiy — APPROVED** [review]

**Comment by vitlibar** [comment]
I have a talk to @KochetovNicolai and he convinced me that we rather need another solution here based on `rbac_version` (which is going to be added in https://github.com/ClickHouse/ClickHouse/pull/35635), and not based on adding a new kind of row policy.

**Comment by vitlibar** [comment]
I've implemented a completely different approach in https://github.com/ClickHouse/ClickHouse/pull/36997

**Pull request closed without merging**
