### PR TITLE
Remove empty parts after they were pruned by TTL

### PR DESCRIPTION
**Pull request by CurtizJ**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Remove empty parts after they were pruned by TTL.

### CODE REVIEW

**Comment by CurtizJ** [comment]
Previously there was a hypotesis, that we can't drop any part from the middle of the list, because it will break merge algorithm. But I looked one more time to the related code and seems that it's ok. In `ReplicatedMergeTreeMergePredicate` there is a logic, that doesn't allow to assign merges to the range of parts if it has a gap beetween block number, and there are any virtual parts with block ranges from this gap (that meens, that parts in the gap are not present yet, but will apear later). If we completly remove part by `DROP_RANGE` entry in replication queue, no invariant will be broken, because now parts in one partition can have gaps in block numbers range.

**Comment by zhang2014** [comment]
👍

**Comment by kekekedeng** [comment]
@CurtizJ How is the progress? Seems waiting for review?

**Comment by CurtizJ** [comment]
It's not working in current implementation. I had some troubles with mutations in selection of parts to mutate. In general to implement this logic the such action as `DROP PART` is required. It's not easy due to algorithms of selection parts in merges and mutations. Also there is  another attempt to implement it #15511.

**Comment by CurtizJ** [comment]
Correct version #16895.

**Pull request closed without merging**
