### PR TITLE
Proper destruction order of AsyncLoader::Pool fields

### LINKED ISSUE #66052: [AsyncLoader.SimplePrioritization] use-of-uninitialized-value
https://s3.amazonaws.com/clickhouse-test-reports/66030/dd28947e827ff9264b45e0a8130b3b44a685c097/unit_tests__msan_.html

```
==19==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x5555939d3a68 in DB::AsyncLoader::canWorkerLive(DB::AsyncLoader::Pool&, std::__1::unique_lock<std::__1::mutex>&) build_docker/./src/Common/AsyncLoader.cpp:830:9
    #1 0x5555939d3a68 in DB::AsyncLoader::worker(DB::AsyncLoader::Pool&) build_docker/./src/Common/AsyncLoader.cpp:903:18
    #2 0x5555939d44ff in DB::AsyncLoader::spawn(DB::AsyncLoader::Pool&, std::__1::unique_lock<std::__1::mutex>&)::$_0::operator()() const build_docker/./src/Common/AsyncLoader.cpp:873:5
    #3 0x5555939d44ff in decltype(std::declval<DB::AsyncLoader::spawn(DB::AsyncLoader::Pool&, std::__1::unique_lock<std::__1::mutex>&)::$_0&>()()) std::__1::__invoke[abi:v15000]<DB::AsyncLoader::spawn(DB::AsyncLoader::Pool&, std::__1::unique_lock<std::__1::mutex>&)::$_0&>(DB::AsyncLoader::spawn(DB::AsyncLoader::Pool&, std::__1::unique_lock<std::__1::mutex>&)::$_0&) build_docker/./contrib/llvm-project/libcxx/include/__functional/invoke.h:394:23
    #4 0x5555939d44ff in void std::__1::__invoke_void_return_wrapper<void, true>::__call<DB::AsyncLoader::spawn(DB::AsyncLoader::Pool&, std::__1::unique_lock<std::__1::mutex>&)::$_0&>(DB::AsyncLoader::spawn(DB::AsyncLoader::Pool&, std::__1::unique_lock<std::__1::mutex>&)::$_0&) build_docker/./contrib/llvm-project/libcxx/include/__functional/invoke.h:479:9
    #5 0x5555939d44ff in std::__1::__function::__default_alloc_func<DB::AsyncLoader::spawn(DB::AsyncLoader::Pool&, std::__1::unique_lock<std::__1::mutex>&)::$_0, void ()>::operator()[abi:v15000]() build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:235:12
    #6 0x5555939d44ff in void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<DB::AsyncLoader::spawn(DB::AsyncLoader::Pool&, std::__1::unique_lock<std::__1::mutex>&)::$_0, void ()>>(std::__1::__function::__policy_storage const*) build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:716:16
    #7 0x555593d76d38 in std::__1::__function::__policy_func<void ()>::operator()[abi:v15000]() const build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:848:16
    #8 0x555593d76d38 in std::__1::function<void ()>::operator()() const build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:1187:12
    #9 0x555593d76d38 in ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::worker(std::__1::__list_iterator<ThreadFromGlobalPoolImpl<false, true>, void*>) build_docker/./src/Common/ThreadPool.cpp:462:13
    #10 0x555593d80e52 in void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()::operator()() const build_docker/./src/Common/ThreadPool.cpp:219:73
    #11 0x555593d80e52 in decltype(std::declval<void>()()) std::__1::__invoke[abi:v15000]<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()&>(void&&) build_docker/./contrib/llvm-project/libcxx/include/__functional/invoke.h:394:23
    #12 0x555593d80e52 in decltype(auto) std::__1::__apply_tuple_impl[abi:v15000]<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()&, std::__1::tuple<>&>(void&&, std::__1::tuple<>&, std::__1::__tuple_indices<...>) build_docker/./contrib/llvm-project/libcxx/include/tuple:1789:1
    #13 0x555593d80e52 in decltype(auto) std::__1::apply[abi:v15000]<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()&, std::__1::tuple<>&>(void&&, std::__1::tuple<>&) build_docker/./contrib/llvm-project/libcxx/include/tuple:1798:1
    #14 0x555593d80e52 in ThreadFromGlobalPoolImpl<false, true>::ThreadFromGlobalPoolImpl<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()>(void&&)::'lambda'()::operator()() build_docker/./src/Common/ThreadPool.h:251:13
    #15 0x555593d80c5e in decltype(std::declval<void>()()) std::__1::__invoke[abi:v15000]<ThreadFromGlobalPoolImpl<false, true>::ThreadFromGlobalPoolImpl<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()>(void&&)::'lambda'()&>(void&&) build_docker/./contrib/llvm-project/libcxx/include/__functional/invoke.h:394:23
    #16 0x555593d80c5e in void std::__1::__invoke_void_return_wrapper<void, true>::__call<ThreadFromGlobalPoolImpl<false, true>::ThreadFromGlobalPoolImpl<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()>(void&&)::'lambda'()&>(ThreadFromGlobalPoolImpl<false, true>::ThreadFromGlobalPoolImpl<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()>(void&&)::'lambda'()&) build_docker/./contrib/llvm-project/libcxx/include/__functional/invoke.h:479:9
    #17 0x555593d80c5e in std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<false, true>::ThreadFromGlobalPoolImpl<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()>(void&&)::'lambda'(), void ()>::operator()[abi:v15000]() build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:235:12
    #18 0x555593d80c5e in void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<false, true>::ThreadFromGlobalPoolImpl<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()>(void&&)::'lambda'(), void ()>>(std::__1::__function::__policy_storage const*) build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:716:16
    #19 0x555593d6eaa9 in std::__1::__function::__policy_func<void ()>::operator()[abi:v15000]() const build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:848:16
    #20 0x555593d6eaa9 in std::__1::function<void ()>::operator()() const build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:1187:12
    #21 0x555593d6eaa9 in ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) build_docker/./src/Common/ThreadPool.cpp:462:13
    #22 0x555593d7af30 in void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()::operator()() const build_docker/./src/Common/ThreadPool.cpp:219:73
    #23 0x555593d7af30 in decltype(std::declval<void>()()) std::__1::__invoke[abi:v15000]<void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()>(void&&) build_docker/./contrib/llvm-project/libcxx/include/__functional/invoke.h:394:23
    #24 0x555593d7af30 in void std::__1::__thread_execute[abi:v15000]<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()>(std::__1::tuple<void, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()>&, std::__1::__tuple_indices<...>) build_docker/./contrib/llvm-project/libcxx/include/thread:284:5
    #25 0x555593d7af30 in void* std::__1::__thread_proxy[abi:v15000]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()>>(void*) build_docker/./contrib/llvm-project/libcxx/include/thread:295:5
    #26 0x7ffff7e18ac2  (/lib/x86_64-linux-gnu/libc.so.6+0x94ac2) (BuildId: 962015aa9d133c6cbcfb31ec300596d7f44d3348)
    #27 0x7ffff7eaa84f  (/lib/x86_64-linux-gnu/libc.so.6+0x12684f) (BuildId: 962015aa9d133c6cbcfb31ec300596d7f44d3348)

  Member fields were destroyed
    #0 0x55555cb3662d in __sanitizer_dtor_callback_fields (/unit_tests_dbms+0x75e262d) (BuildId: d76611b276be448ca40ed83f1b888f71bea37d5c)
    #1 0x5555939d4de2 in std::__1::__tree<std::__1::__value_type<unsigned long, std::__1::shared_ptr<DB::LoadJob>>, std::__1::__map_value_compare<unsigned long, std::__1::__value_type<unsigned long, std::__1::shared_ptr<DB::LoadJob>>, std::__1::less<unsigned long>, true>, std::__1::allocator<std::__1::__value_type<unsigned long, std::__1::shared_ptr<DB::LoadJob>>>>::~__tree() build_docker/./contrib/llvm-project/libcxx/include/__tree:1038:56
    #2 0x5555939d4de2 in std::__1::__tree<std::__1::__value_type<unsigned long, std::__1::shared_ptr<DB::LoadJob>>, std::__1::__map_value_compare<unsigned long, std::__1::__value_type<unsigned long, std::__1::shared_ptr<DB::LoadJob>>, std::__1::less<unsigned long>, true>, std::__1::allocator<std::__1::__value_type<unsigned long, std::__1::shared_ptr<DB::LoadJob>>>>::~__tree() build_docker/./contrib/llvm-project/libcxx/include/__tree:1789:1
    #3 0x5555939d4de2 in std::__1::map<unsigned long, std::__1::shared_ptr<DB::LoadJob>, std::__1::less<unsigned long>, std::__1::allocator<std::__1::pair<unsigned long const, std::__1::shared_ptr<DB::LoadJob>>>>::~map[abi:v15000]() build_docker/./contrib/llvm-project/libcxx/include/map:1163:5
    #4 0x5555939d4de2 in DB::AsyncLoader::Pool::~Pool() build_docker/./src/Common/AsyncLoader.h:364:12
    #5 0x5555939bb9b4 in void std::__1::__destroy_at[abi:v15000]<DB::AsyncLoader::Pool, 0>(DB::AsyncLoader::Pool*) build_docker/./contrib/llvm-project/libcxx/include/__memory/construct_at.h:63:13
    #6 0x5555939bb9b4 in void std::__1::destroy_at[abi:v15000]<DB::AsyncLoader::Pool, 0>(DB::AsyncLoader::Pool*) build_docker/./contrib/llvm-project/libcxx/include/__memory/construct_at.h:88:5
    #7 0x5555939bb9b4 in void std::__1::allocator_traits<std::__1::allocator<DB::AsyncLoader::Pool>>::destroy[abi:v15000]<DB::AsyncLoader::Pool, void, void>(std::__1::allocator<DB::AsyncLoader::Pool>&, DB::AsyncLoader::Pool*) build_docker/./contrib/llvm-project/libcxx/include/__memory/allocator_traits.h:317:9
    #8 0x5555939bb9b4 in std::__1::vector<DB::AsyncLoader::Pool, std::__1::allocator<DB::AsyncLoader::Pool>>::__base_destruct_at_end[abi:v15000](DB::AsyncLoader::Pool*) build_docker/./contrib/llvm-project/libcxx/include/vector:833:9
    #9 0x5555939bb9b4 in std::__1::vector<DB::AsyncLoader::Pool, std::__1::allocator<DB::AsyncLoader::Pool>>::__clear[abi:v15000]() build_docker/./contrib/llvm-project/libcxx/include/vector:827:29
    #10 0x5555939bb9b4 in std::__1::vector<DB::AsyncLoader::Pool, std::__1::allocator<DB::AsyncLoader::Pool>>::~vector[abi:v15000]() build_docker/./contrib/llvm-project/libcxx/include/vector:436:9
    #11 0x5555939bb9b4 in DB::AsyncLoader::~AsyncLoader() build_docker/./src/Common/AsyncLoader.cpp:235:1
    #12 0x55555cf666c5 in AsyncLoaderTest::~AsyncLoaderTest() build_docker/./src/Common/tests/gtest_async_loader.cpp:46:8
    #13 0x55555cf666c5 in AsyncLoader_SimplePrioritization_Test::TestBody() build_docker/./src/Common/tests/gtest_async_loader.cpp:865:1
    #14 0x555575eabca0 in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) build_docker/./contrib/googletest/googletest/src/gtest.cc:2635:10
    #15 0x555575eabca0 in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) build_docker/./contrib/googletest/googletest/src/gtest.cc:2671:14
    #16 0x555575eab8fa in testing::Test::Run() build_docker/./contrib/googletest/googletest/src/gtest.cc:2710:5
    #17 0x555575eaeba1 in testing::TestInfo::Run() build_docker/./contrib/googletest/googletest/src/gtest.cc:2856:11
    #18 0x555575eb218d in testing::TestSuite::Run() build_docker/./contrib/googletest/googletest/src/gtest.cc:3034:30
    #19 0x555575ef0122 in testing::internal::UnitTestImpl::RunAllTests() build_docker/./contrib/googletest/googletest/src/gtest.cc:5964:44
    #20 0x555575eeefa0 in bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) build_docker/./contrib/googletest/googletest/src/gtest.cc:2635:10
    #21 0x555575eeefa0 in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) build_docker/./contrib/googletest/googletest/src/gtest.cc:2671:14
    #22 0x555575eeebe9 in testing::UnitTest::Run() build_docker/./contrib/googletest/googletest/src/gtest.cc:5543:10
    #23 0x55555d26bfc0 in RUN_ALL_TESTS() build_docker/./contrib/googletest/googletest/include/gtest/gtest.h:2334:73
    #24 0x55555d26bfc0 in main build_docker/./src/Common/tests/gtest_main.cpp:17:12
    #25 0x7ffff7dadd8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f) (BuildId: 962015aa9d133c6cbcfb31ec300596d7f44d3348)

SUMMARY: MemorySanitizer: use-of-uninitialized-value build_docker/./src/Common/AsyncLoader.cpp:830:9 in DB::AsyncLoader::canWorkerLive(DB::AsyncLoader::Pool&, std::__1::unique_lock<std::__1::mutex>&)
Exiting
```

cc @serxa

### PR DESCRIPTION
**Pull request by serxa**
Fixes https://github.com/ClickHouse/ClickHouse/issues/66052

The pool queue was destroyed before the thread pool and the worker could not terminate properly.

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
...

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-clickhouse-ci-2** [comment]
*This is an automated comment for commit d2d72794a14459e60be1c3a88d39440af1f7a8f9 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/66145/d2d72794a14459e60be1c3a88d39440af1f7a8f9/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Style check</td><td>Runs a set of checks to keep the code style clean. If some of tests failed, see the related log from the report</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/66145/d2d72794a14459e60be1c3a88d39440af1f7a8f9/style_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Review by alexey-milovidov — APPROVED** [review]

**Review by alexey-milovidov — APPROVED** [review]

**Comment by serxa** [comment]
@maxknv Could you help me find out what when wrong with build here? They seem to be all successful, but check has failed.

**Comment by maxknv** [comment]
> @maxknv Could you help me find out what when wrong with build here? They seem to be all successful, but check has failed.

They are not successful. tidy build has failed. it's seen in GH actions and in Builds report as well

**Comment by serxa** [comment]
Looks like I just missed "failure" for some reason. But I remember they all were "success". Okay, thank you!

The error looks unrelated:
```
/build/src/IO/BufferWithOwnMemory.h:73:9: error: 1 uninitialized field at the end of the constructor call [clang-analyzer-optin.cplusplus.UninitializedObject,-warnings-as-errors]
```

**Pull request merged**
