### PR TITLE
Fix BuildFuzzers

### PR DESCRIPTION
**Pull request by nickitat**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

I'm not a cmake expert, but works locally 🤷🏼

### CODE REVIEW

**Comment by robot-ch-test-poll2** [comment]
*This is an automated comment for commit ae5b47ba7f5f50976884e34302f9ea53a9cea984 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/65021/ae5b47ba7f5f50976884e34302f9ea53a9cea984/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>A Sync</td><td>If it fails, ask a maintainer for help</td><td>⏳ pending</td></tr>
<tbody>
</table>
<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>Checks correctness of the PR's body</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

**Comment by nickitat** [comment]
```
Jun 08 23:31:13 In file included from /build/contrib/libprotobuf-mutator/src/mutator.cc:27:
Jun 08 23:31:13 /build/contrib/libprotobuf-mutator/src/field_instance.h:195:34: error: 'syntax' is a private member of 'google::protobuf::FileDescriptor'
Jun 08 23:31:13   195 |            descriptor()->file()->syntax() ==
Jun 08 23:31:13       |                                  ^
Jun 08 23:31:13 /build/contrib/google-protobuf/src/google/protobuf/descriptor.h:1890:10: note: declared private here
Jun 08 23:31:13  1890 |   Syntax syntax() const;
Jun 08 23:31:13       |          ^
Jun 08 23:31:13 In file included from /build/contrib/libprotobuf-mutator/src/mutator.cc:27:
Jun 08 23:31:13 /build/contrib/libprotobuf-mutator/src/field_instance.h:196:42: error: 'SYNTAX_PROTO3' is a private member of 'google::protobuf::FileDescriptor'
Jun 08 23:31:13   196 |                protobuf::FileDescriptor::SYNTAX_PROTO3;
Jun 08 23:31:13       |                                          ^
Jun 08 23:31:13 /build/contrib/google-protobuf/src/google/protobuf/descriptor.h:1882:5: note: declared private here
Jun 08 23:31:13  1882 |     SYNTAX_PROTO3 = 3,
Jun 08 23:31:13       |     ^
Jun 08 23:31:13 /build/contrib/libprotobuf-mutator/src/mutator.cc:92:24: error: 'syntax' is a private member of 'google::protobuf::FileDescriptor'
Jun 08 23:31:13    92 |   return field.file()->syntax() == FileDescriptor::SYNTAX_PROTO3 &&
Jun 08 23:31:13       |                        ^
Jun 08 23:31:13 /build/contrib/google-protobuf/src/google/protobuf/descriptor.h:1890:10: note: declared private here
Jun 08 23:31:13  1890 |   Syntax syntax() const;
Jun 08 23:31:13       |          ^
Jun 08 23:31:13 /build/contrib/libprotobuf-mutator/src/mutator.cc:92:52: error: 'SYNTAX_PROTO3' is a private member of 'google::protobuf::FileDescriptor'
Jun 08 23:31:13    92 |   return field.file()->syntax() == FileDescriptor::SYNTAX_PROTO3 &&
Jun 08 23:31:13       |                                                    ^
Jun 08 23:31:13 /build/contrib/google-protobuf/src/google/protobuf/descriptor.h:1882:5: note: declared private here
Jun 08 23:31:13  1882 |     SYNTAX_PROTO3 = 3,
Jun 08 23:31:13       |     ^
Jun 08 23:31:13 4 errors generated.
```

**Review by alexey-milovidov — APPROVED** [review]

**Comment by rschu1ze** [comment]
Also needs something like `target_link_libraries(clickhouse PRIVATE -fprofile-instr-generate -fcoverage-mapping)`, otherwise the linker complains.

Trying this right now ...

**Comment by nickitat** [comment]
not sure what to do with this:

```
Jun 09 14:33:13 [5784/5787] Linking CXX executable programs/clickhouse
Jun 09 14:33:13 FAILED: programs/clickhouse 
Jun 09 14:33:13 : && /usr/bin/clang++-18 --target=x86_64-linux-gnu --sysroot=/build/cmake/linux/../../contrib/sysroot/linux-x86_64/x86_64-linux-gnu/libc --gcc-toolchain=/build/cmake/linux/../../contrib/sysroot/linux-x86_64 -nostdlib++ -fdiagnostics-color=always -Xclang -fuse-ctor-homing -Wno-enum-constexpr-conversion -fsized-deallocation  -gdwarf-aranges -pipe -mssse3 -msse4.1 -msse4.2 -mpclmul -mpopcnt -fasynchronous-unwind-tables -ffile-prefix-map=/build=. -ftime-trace -falign-functions=32 -mbranches-within-32B-boundaries -ffp-contract=off  -fdiagnostics-absolute-paths -fstrict-vtable-pointers -Wall -Wextra -Wframe-larger-than=65536 -Weverything -Wpedantic -Wno-zero-length-array -Wno-c++98-compat-pedantic -Wno-c++98-compat -Wno-c++20-compat -Wno-sign-conversion -Wno-implicit-int-conversion -Wno-implicit-int-float-conversion -Wno-ctad-maybe-unsupported -Wno-disabled-macro-expansion -Wno-documentation-unknown-command -Wno-double-promotion -Wno-exit-time-destructors -Wno-float-equal -Wno-global-constructors -W
Jun 09 14:33:13 ld.lld-18: error: undefined symbol: __llvm_profile_dump
Jun 09 14:33:13 >>> referenced by coverage.cpp:27 (./build_docker/./base/base/coverage.cpp:27)
Jun 09 14:33:13 >>>               coverage.cpp.o:(dumpCoverageReportIfPossible()) in archive base/base/libcommon.a
Jun 09 14:33:13 clang++-18: error: linker command failed with exit code 1 (use -v to see invocation)
Jun 09 14:33:13 [5785/5787] Linking CXX executable programs/server/fuzzers/tcp_protocol_fuzzer
Jun 09 14:33:13 FAILED: programs/server/fuzzers/tcp_protocol_fuzzer 
Jun 09 14:33:13 : && /usr/bin/clang++-18 --target=x86_64-linux-gnu --sysroot=/build/cmake/linux/../../contrib/sysroot/linux-x86_64/x86_64-linux-gnu/libc --gcc-toolchain=/build/cmake/linux/../../contrib/sysroot/linux-x86_64 -nostdlib++ -fdiagnostics-color=always -Xclang -fuse-ctor-homing -Wno-enum-constexpr-conversion -fsized-deallocation  -gdwarf-aranges -pipe -mssse3 -msse4.1 -msse4.2 -mpclmul -mpopcnt -fasynchronous-unwind-tables -ffile-prefix-map=/build=. -ftime-trace -falign-functions=32 -mbranches-within-32B-boundaries -ffp-contract=off  -fdiagnostics-absolute-paths -fstrict-vtable-pointers -Wall -Wextra -Wframe-larger-than=65536 -Weverything -Wpedantic -Wno-zero-length-array -Wno-c++98-compat-pedantic -Wno-c++98-compat -Wno-c++20-compat -Wno-sign-conversion -Wno-implicit-int-conversion -Wno-implicit-int-float-conversion -Wno-ctad-maybe-unsupported -Wno-disabled-macro-expansion -Wno-documentation-unknown-command -Wno-double-promotion -Wno-exit-time-destructors -Wno-float-equal -Wno-global-constructors -W
Jun 09 14:33:13 ld.lld-18: error: undefined symbol: __llvm_profile_dump
Jun 09 14:33:13 >>> referenced by coverage.cpp:27 (./build_docker/./base/base/coverage.cpp:27)
Jun 09 14:33:13 >>>               coverage.cpp.o:(dumpCoverageReportIfPossible()) in archive base/base/libcommon.a
Jun 09 14:33:13 clang++-18: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by rschu1ze** [comment]
That's what I meant ^^, working on a fix (and I'll also try to get rid of ugly generator expressions in CMake).

Side note: I wonder what caused the coverage build to fail. I did not find coverage-related PRs in the last days.

**Comment by nickitat** [comment]
> That's what I meant ^^

oh, sorry I missed that you're chasing exactly this linker error.

> I wonder what caused the coverage build to fail

🤷🏼

**Comment by nickitat** [comment]
Screenshot 2024-06-09 at 17 04 54

🎉

**Comment by rschu1ze** [comment]
Looks like the coverage build is green but the unit tests are now red. I excluded them and clickhouse-library-bridge from `WITH_COVERAGE` builds as [linking trick](https://github.com/ClickHouse/ClickHouse/pull/65021#issuecomment-2156508311) did somehow not work for them.

**Comment by rschu1ze** [comment]
> Side note: I wonder what caused the coverage build to fail. I did not find coverage-related PRs in the last days.

Looks like this PR broke the build: https://github.com/ClickHouse/ClickHouse/pull/64824

**Comment by yakov-olkhovskiy** [comment]
there is my draft PR dealing with this issue (along others) in fuzzers build - https://github.com/ClickHouse/ClickHouse/pull/61908
I'm not sure what the purpose of the offender PR was, but I believe my solution is correct, so maybe for whatever reason you want to enable this build probably take the fix from mine...

**Comment by rschu1ze** [comment]
Coverage tests fail unfortunately ... we'll go with https://github.com/ClickHouse/ClickHouse/pull/65041 for now.

**Comment by nickitat** [comment]
I think if the new build succeed - let's merge it as is. we haven't fixed all the issues, but I don't want to invest more in this neither I want to throw away our effort.

**Pull request closed without merging**
