### PR TITLE
Add very explicit logging on disk choice for fetch

### PR DESCRIPTION
**Pull request by alesapin**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

### CODE REVIEW

**Review by yakov-olkhovskiy — APPROVED** [review]

**Comment by alesapin** [comment]
Fast test reported https://github.com/ClickHouse/ClickHouse/issues/41679

**Review by yakov-olkhovskiy — APPROVED** [review]

**Comment by alesapin** [comment]
Fuzzers: https://github.com/ClickHouse/ClickHouse/issues/41745

**Comment by alesapin** [comment]
Stress asan: 
```
2022.09.23 21:58:05.028644 [ 389351 ] {} <Error> test_13.replicated_alter2 (ReplicatedMergeTreeAttachThread): Initialization failed. Error: Failed to create new nodes at /clickhouse/tables/test_13/test_00062/alter (Connection loss)
2022.09.23 21:58:05.028600 [ 389346 ] {} <Error> test_13.replicated_deduplicate_by_columns_r1 (ReplicatedMergeTreeAttachThread): Initialization failed. Error: Failed to create new nodes at /clickhouse/tables/test_13/test_01581/replicated_deduplicate (Connection loss)
2022.09.23 21:58:05.030073 [ 389348 ] {} <Error> test_13.replicated_deduplicate_by_columns_r2 (ReplicatedMergeTreeAttachThread): Initialization failed. Error: Failed to create new nodes at /clickhouse/tables/test_13/test_01581/replicated_deduplicate (Connection loss)
2022.09.23 21:58:05.048594 [ 389340 ] {} <Error> test_13.replicated_table_for_alter1 (ReplicatedMergeTreeAttachThread): Initialization failed. Error: Connection loss, path: /clickhouse/tables/test_00980_test_13/replicated_table_for_alter/metadata
```
It's ok I think.

**Comment by alesapin** [comment]
`Stress test (debug)` -- abort in `AsynchronousReadIndirectBufferFromRemoteFS` https://github.com/ClickHouse/ClickHouse/issues/41746

**Comment by alesapin** [comment]
stress msan -- OOM

**Comment by alesapin** [comment]
Stress ubsan -- `Unknown Index type 'annoy'.`

**Comment by alesapin** [comment]
Stress tsan -- backward compatibility need to be fixed with test for compressed marks.

**Pull request merged**
