### PR TITLE
Add total_bytes_with_inactive to system.tables

### PR DESCRIPTION
**Pull request by nauu**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Add total_bytes_with_inactive to system.tables to count the total bytes of inactive parts.

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Run only fuzzers related jobs (libFuzzer fuzzers, AST fuzzers, etc.)
- [ ]  Exclude: AST fuzzers
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-clickhouse-ci-2** [comment]
*This is an automated comment for commit c3c8f9d2ff3957311164ac410f2ae1e6d999d2d0 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/72690/c3c8f9d2ff3957311164ac410f2ae1e6d999d2d0/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/b81ee27750c4520de6e6b979ce7d4f6a111cb8ea/docs_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Review by jsc0218 — APPROVED** [review]

**Comment by nauu** [comment]
Some fast tests in merge check failed, but it is not relevant

**Comment by rschu1ze** [comment]
@jsc0218 @nauu Field `total_bytes_with_inactive` needs to be documented here: https://clickhouse.com/docs/en/operations/system-tables/tables

**Comment by rschu1ze** [comment]
@jsc0218 @nauu Thoughts about adding `total_bytes_with_inactive`:

1. Column names should be self-explaining and grammatically correct. Can we please rename this to `total_bytes_in_inactive_parts`?

2. It seems weird that a "negative" quantity (i.e. "inactive") is included in the system table but the "positive" quantity is not. Instead of `total_bytes_in_inactive_parts`, we should only include `total_bytes_in_active_parts`. In practice, this will be the more relevant quantity (as there will be zero inactive parts due to cleanup/deletion of them as time goes on).

3. Note that if we include `total_bytes_in_active_parts` instead, we don't need to include `total_bytes_in_inactive_parts` anymore as that computes implicitly as `total_bytes - total_bytes_in_active_parts`.

4. In fact, even without this PR, it is very easy for users to calculate the byte size of active and of inactive parts from `system.parts`. For the sake of simplicity and because of above argument that the number of inactive parts asymptodically approaches zero, we actually don't need new fields in `system.tables`.

**Comment by jsc0218** [comment]
Well, your argument is convincing. @rschu1ze

**Pull request merged**
