### PR TITLE
Fix bug for mapUpdate

### LINKED ISSUE #38547: Clickhouse crashes when using mapUpdate() and mapFilter()
Clickhouse segfaults and crashes when using `mapUpdate()` and `mapFilter()` together. 

## Clickhouse Version

ClickHouse 22.7.1.788 with revision 54464
OS name: Darwin, version: 20.6.0, architecture: arm64

### Create table

```
CREATE TABLE default.map_test
(
    `tags` Map(String, String),
    INDEX idx_tags_keys mapKeys(tags) TYPE tokenbf_v1(256, 2, 0) GRANULARITY 1,
    INDEX idx_tags_vals mapValues(tags) TYPE tokenbf_v1(256, 2, 0) GRANULARITY 1
)
ENGINE = MergeTree
PRIMARY KEY tags
ORDER BY tags
SETTINGS index_granularity = 8192
```

### Add data

I am able to reliably produce this behavior when there are five rows inserted. I do not observe this when there are fewer rows.

```
INSERT INTO map_test (tags) VALUES (map('fruit','apple','color','red'))
INSERT INTO map_test (tags) VALUES (map('fruit','apple','color','red'))
INSERT INTO map_test (tags) VALUES (map('fruit','apple','color','red'))
INSERT INTO map_test (tags) VALUES (map('fruit','apple','color','red'))
INSERT INTO map_test (tags) VALUES (map('fruit','apple','color','red'))
```

## The bug

Then, run this query:

```
SELECT
    mapUpdate(mapFilter((k, v) -> (k in ('fruit')), tags), map('season', 'autumn'))
FROM
    map_test
```

From here, the behavior is intermittent. The first time I run this, I receive a partially-correct result:

```
mapUpdate(mapFilter(lambda(tuple(k, v), in(k, 'fruit')), tags), map('season', 'autumn'))
--
{"fruit":"apple","season":"autumn"}
{"fruit":"apple"}
{"fruit":"apple"}
{"fruit":"apple"}
{"fruit":"apple"}
```

And this log:

```
<Debug> executeQuery: (from 127.0.0.1:59843) SELECT mapUpdate(mapFilter((k, v) -> (k in ('fruit')), tags), map('season', 'autumn')) FROM map_test (stage: Complete)
<Trace> ContextAccess (default): Access granted: SELECT(tags) ON default.map_test
<Trace> ContextAccess (default): Access granted: SELECT(tags) ON default.map_test
<Trace> InterpreterSelectQuery: FetchColumns -> Complete
<Debug> default.map_test (a9b090d0-31b7-4fb2-ba3a-92adb8062fd7) (SelectExecutor): Key condition: unknown
<Debug> default.map_test (a9b090d0-31b7-4fb2-ba3a-92adb8062fd7) (SelectExecutor): Selected 1/1 parts by partition key, 1 parts by primary key, 1/1 marks by primary key, 1 marks to read from 1 ranges
<Trace> MergeTreeInOrderSelectProcessor: Reading 1 ranges in order from part all_1_5_1, approx. 5 rows starting from 0
<Information> executeQuery: Read 5 rows, 310.00 B in 0.016847 sec., 296 rows/sec., 17.97 KiB/sec.
<Debug> DynamicQueryHandler: Done processing query
<Debug> MemoryTracker: Peak memory usage (for query): 3.99 MiB.
<Debug> MemoryTracker: Peak memory usage (for query): 3.99 MiB.
<Debug> HTTP-Session: ec8969c5-4b78-456c-9b3c-ccbcde51f848 Destroying unnamed session
```

When I run the same query again, Clickhouse crashes with a segfault. Here is the log:

```
<Debug> executeQuery: (from 127.0.0.1:59850) SELECT mapUpdate(mapFilter((k, v) -> (k in ('fruit')), tags), map('season', 'autumn')) FROM map_test (stage: Complete)
<Trace> ContextAccess (default): Access granted: SELECT(tags) ON default.map_test
<Trace> ContextAccess (default): Access granted: SELECT(tags) ON default.map_test
<Trace> InterpreterSelectQuery: FetchColumns -> Complete
<Debug> default.map_test (a9b090d0-31b7-4fb2-ba3a-92adb8062fd7) (SelectExecutor): Key condition: unknown
<Debug> default.map_test (a9b090d0-31b7-4fb2-ba3a-92adb8062fd7) (SelectExecutor): Selected 1/1 parts by partition key, 1 parts by primary key, 1/1 marks by primary key, 1 marks to read from 1 ranges
<Trace> MergeTreeInOrderSelectProcessor: Reading 1 ranges in order from part all_1_5_1, approx. 5 rows starting from 0
<Trace> BaseDaemon: Received signal 10
<Fatal> BaseDaemon: ########################################
<Fatal> BaseDaemon: (version 22.7.1.788 (official build), no build id) (from thread 7864088) (query_id: b6d2b6b9-0a93-4434-9b02-8457dfa29414) (query: SELECT mapUpdate(mapFilter((k, v) -> (k in ('fruit')), tags), map('season', 'autumn')) FROM map_test) Received signal Bus error: 10 (10)
<Fatal> BaseDaemon: Invalid address alignment.
<Fatal> BaseDaemon: Stack trace: 0x1991f2994
<Fatal> BaseDaemon: 0. 0x1991f2994
<Debug> DNSResolver: Updating DNS cache
<Debug> DNSResolver: Updated DNS cache
<Debug> DNSResolver: Updating DNS cache
<Debug> DNSResolver: Updated DNS cache
zsh: bus error  ./clickhouse server
```

## Expected behavior

I expect clickhouse to return the following:

{"fruit":"apple","season":"autumn"}
{"fruit":"apple","season":"autumn"}
{"fruit":"apple","season":"autumn"}
{"fruit":"apple","season":"autumn"}
{"fruit":"apple","season":"autumn"}

## Additional context

- When there is only 1 row in the table, I am not able to reproduce
- It usually takes 5+ rows of data to reliably reproduce
- Sometimes this crash occurs the first time I run the query, other times it takes 2-3 tries.

### PR DESCRIPTION
**Pull request by hexiaoting**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in official stable or prestable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix crash for `mapUpdate`, `mapFilter` functions when using with constant map argument. Closes https://github.com/ClickHouse/ClickHouse/issues/38547.

### CODE REVIEW

**Review by kitaisreal — APPROVED** [review]

**Comment by hexiaoting** [comment]
@kitaisreal Hi, I'm not familiar with the new PullRequestCI and cannot get the detail error information . Can you help me to get the details  about the error so that I can fix errors to make the CI pass? Thank you.

**Comment by kitaisreal** [comment]
@Mergifyio update

**Comment by kitaisreal** [comment]
@hexiaoting server crashed because it cannot run this test in previous version. Please extract this test in separate test file and add `-- Tags: no-backward-compatibility-check`.

**Comment by kitaisreal** [comment]
@Mergifyio update

**Pull request merged**
