### PR TITLE
Resolve #12098

### LINKED ISSUE #12098: 20.5 partial dictionary updates do not work if update_field is an expression
I use an expression as `update_field` because this feature is not implemented yet: https://github.com/ClickHouse/ClickHouse/issues/6084

20.5 generates an incorrect query in this case:
```WHERE `date_add(updated_date, interval 15 minute)` >= '2020-07-02 16:40:06'```

The exception:
```mysqlxx::BadQuery: Unknown column 'date_add(updated_date, interval 15 minute)' in 'where clause'```

The problem is here: 
https://github.com/ClickHouse/ClickHouse/blob/b81c66a03148afc02647df3c11aec40382329912/src/Dictionaries/ExternalQueryBuilder.cpp#L172
The change was introduced in this PR: https://github.com/ClickHouse/ClickHouse/pull/11079

### PR DESCRIPTION
**Pull request by myrrc**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Reverts change introduced in #11079 to resolve #12098.

### CODE REVIEW

**Review by alesapin — APPROVED** [review]
LGTM

**Comment by alexey-milovidov** [comment]
Ok, but why it was needed? @tavplubix ?

**Review by alexey-milovidov — APPROVED** [review]

**Comment by tavplubix** [comment]
> Ok, but why it was needed? @tavplubix ?

Column names in `WHERE` clause were not quoted, so I replaced `writeString` with `writeQuoted` in several places. This line was replaced by mistake.

**Review by tavplubix — APPROVED** [review]

**Comment by tavplubix** [comment]
However, it's probably better to quote `update_field` if it's not an expression.

**Pull request merged**
