### PR TITLE
Manual Backport #38731 to 22.3: Fix number of threads for pushing to views

### PR DESCRIPTION
**Pull request by azat**
This is a manual backport of #38731 to 22.3 branch, since there are conflicts in #38921

Original pull-request https://github.com/ClickHouse/ClickHouse/pull/38731
Cherry-pick pull-request https://github.com/ClickHouse/ClickHouse/pull/38921

Closes: #38921

### CODE REVIEW

**Comment by azat** [comment]
>[ClickHouse build check (actions) — 0/5 artifact groups are OK](https://s3.amazonaws.com/clickhouse-builds/0/5242a045f02b90670e83d2f36b18dab9c7b4c07e/clickhouse_build_check_(actions)/report.html)

```
Jul 15 10:55:19 /build.sh: line 35: cd: /build/programs/diagnostics: No such file or directory
```

- #39281

**Comment by azat** [comment]
@Felixoid can you please make CI start again?

**Comment by Felixoid** [comment]
JIC:

```
git checkout backport/22.3/38731
git remote add azat git@github.com:azat/ClickHouse.git
git pull azat views-max_insert_threads-22.3
git push backport/22.3/38731
```

**Comment by azat** [comment]
>[ClickHouse build check (actions) — 0/5 artifact groups are OK](https://s3.amazonaws.com/clickhouse-builds/0/98cebc78471b81f9c0a520de54b25a636c5927c8/clickhouse_build_check_(actions)/report.html)

```
Jul 17 12:32:43 + cmake --debug-trycompile --verbose=1 -DCMAKE_VERBOSE_MAKEFILE=1 -LA -DCMAKE_BUILD_TYPE=None -DSANITIZE= -DENABLE_CHECK_HEAVY_BUILDS=1 -DENABLE_TESTS=0 -DENABLE_UTILS=0 -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON -DCMAKE_AUTOGEN_VERBOSE=ON -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_INSTALL_SYSCONFDIR=/etc -DCMAKE_INSTALL_LOCALSTATEDIR=/var -DBUILD_STANDALONE_KEEPER=ON -DINSTALL_STRIPPED_BINARIES=ON -DCMAKE_C_COMPILER=clang-13 -DCMAKE_CXX_COMPILER=clang++-13 -DCLICKHOUSE_OFFICIAL_BUILD=1 ..
Jul 17 12:32:43 debug trycompile on
Jul 17 12:32:43 -- The C compiler identification is unknown
Jul 17 12:32:43 -- The CXX compiler identification is unknown
Jul 17 12:32:43 CMake Error at CMakeLists.txt:29 (project):
Jul 17 12:32:43   The CMAKE_C_COMPILER:
Jul 17 12:32:43 
Jul 17 12:32:43     clang-13
```

Now it cannot find clang-13, since it uses builder image that already switched to clang-14.
Just like I though it should use docker image for builds that was created for the specific release, like before, sadly but there are no such tags in the registry.

**Comment by Felixoid** [comment]
It was solved long time ago, the backport and release branches use the same image.. but I forgot to label it properly https://github.com/ClickHouse/ClickHouse/blob/master/tests/ci/pr_info.py#L185

**Comment by azat** [comment]
So, could you please restart the checks?

**Comment by Felixoid** [comment]
I've pushed `backport/**`, but it didn't work. Pushed it to your branch too

**Comment by Felixoid** [comment]
No, it just doesn't work. It must be `backport/*` branch and PR from it accordingly. Just create it, please ¯\\\_(ツ)_/¯

**Pull request closed without merging**
