### PR TITLE
Fix: sorted distinct with sparse columns

### LINKED ISSUE #52540: Null pointer DistinctSortedChunkTransform.cpp
In harmless PR https://github.com/ClickHouse/ClickHouse/pull/52315/

https://s3.amazonaws.com/clickhouse-test-reports/52315/265e1437a3a5c37b21aea8e8bf562a59fb818177/sqlancer__release_.html

Full log in stderr.zst file
```
2023.07.24 21:44:26.910187 [ 658 ] {} <Fatal> BaseDaemon: ########## Short fault info ############
2023.07.24 21:44:26.910223 [ 658 ] {} <Fatal> BaseDaemon: (version 23.7.1.2057, build id: BFEE3DC2FDFE502EBB31747727F93443BCB41810, git hash: 52e1d3c8e0e38acf177d0f7a3b94d40e53bbadf5) (from thread 391) Received signal 11
2023.07.24 21:44:26.910248 [ 658 ] {} <Fatal> BaseDaemon: Signal description: Segmentation fault
2023.07.24 21:44:26.910262 [ 658 ] {} <Fatal> BaseDaemon: Address: NULL pointer. Access: read. Unknown si_code.
2023.07.24 21:44:26.910277 [ 658 ] {} <Fatal> BaseDaemon: Stack trace: 0x0000000015457210 0x0000000015455e7d 0x0000000015456072 0x000000001138cdb0 0x00000000150ca0f2 0x00000000150e3fe9 0x00000000150dab50 0x00000000150dbce3 0x000000000e902c0f 0x000000000e90595c 0x000000000e8fe54f 0x000000000e904541 0x00007f41bb36db43 0x00007f41bb3ffa00
2023.07.24 21:44:26.910290 [ 658 ] {} <Fatal> BaseDaemon: ########################################
2023.07.24 21:44:26.910303 [ 658 ] {} <Fatal> BaseDaemon: (version 23.7.1.2057, build id: BFEE3DC2FDFE502EBB31747727F93443BCB41810, git hash: 52e1d3c8e0e38acf177d0f7a3b94d40e53bbadf5) (from thread 391) (query_id: 9e23d0a1-ef7e-4f5e-bfcf-08cd808c4c39) (query: SELECT DISTINCT t3.c0, t3.c1, t3.c0 FROM t3) Received signal Segmentation fault (11)
2023.07.24 21:44:26.910315 [ 658 ] {} <Fatal> BaseDaemon: Address: NULL pointer. Access: read. Unknown si_code.
2023.07.24 21:44:26.910327 [ 658 ] {} <Fatal> BaseDaemon: Stack trace: 0x0000000015457210 0x0000000015455e7d 0x0000000015456072 0x000000001138cdb0 0x00000000150ca0f2 0x00000000150e3fe9 0x00000000150dab50 0x00000000150dbce3 0x000000000e902c0f 0x000000000e90595c 0x000000000e8fe54f 0x000000000e904541 0x00007f41bb36db43 0x00007f41bb3ffa00
2023.07.24 21:44:26.942682 [ 658 ] {} <Fatal> BaseDaemon: 2.1. inlined from ./build_docker/./base/base/../base/StringRef.h:288: CRC32Hash::operator()(StringRef) const
2023.07.24 21:44:26.943340 [ 658 ] {} <Fatal> BaseDaemon: 2.2. inlined from ./build_docker/./src/Common/HashTable/HashTable.h:759: HashTable<StringRef, ClearableHashTableCell<StringRef, HashSetCellWithSavedHash<StringRef, DefaultHash<StringRef>, ClearableHashSetState>>, DefaultHash<StringRef>, HashTableGrowerWithPrecalculation<8ul>, Allocator<true>>::hash(StringRef const&) const
2023.07.24 21:44:26.943368 [ 658 ] {} <Fatal> BaseDaemon: 2.3. inlined from ./build_docker/./src/Common/HashTable/HashTable.h:1087: void HashTable<StringRef, ClearableHashTableCell<StringRef, HashSetCellWithSavedHash<StringRef, DefaultHash<StringRef>, ClearableHashSetState>>, DefaultHash<StringRef>, HashTableGrowerWithPrecalculation<8ul>, Allocator<true>>::emplace<DB::ArenaKeyHolder&>(DB::ArenaKeyHolder&, ClearableHashTableCell<StringRef, HashSetCellWithSavedHash<StringRef, DefaultHash<StringRef>, ClearableHashSetState>>*&, bool&)
2023.07.24 21:44:26.943395 [ 658 ] {} <Fatal> BaseDaemon: 2.4. inlined from ./build_docker/./src/Common/ColumnsHashingImpl.h:251: DB::ColumnsHashing::columns_hashing_impl::EmplaceResultImpl<void> DB::ColumnsHashing::columns_hashing_impl::HashMethodBase<DB::ColumnsHashing::HashMethodString<StringRef, void, true, false, false, false>, StringRef, void, false, false, false>::emplaceImpl<ClearableHashSetWithSavedHash<StringRef, DefaultHash<StringRef>, HashTableGrowerWithPrecalculation<8ul>, Allocator<true>>, DB::ArenaKeyHolder>(DB::ArenaKeyHolder&, ClearableHashSetWithSavedHash<StringRef, DefaultHash<StringRef>, HashTableGrowerWithPrecalculation<8ul>, Allocator<true>>&)
2023.07.24 21:44:26.943467 [ 658 ] {} <Fatal> BaseDaemon: 2.5. inlined from ./build_docker/./src/Common/ColumnsHashingImpl.h:170: DB::ColumnsHashing::columns_hashing_impl::EmplaceResultImpl<void> DB::ColumnsHashing::columns_hashing_impl::HashMethodBase<DB::ColumnsHashing::HashMethodString<StringRef, void, true, false, false, false>, StringRef, void, false, false, false>::emplaceKey<ClearableHashSetWithSavedHash<StringRef, DefaultHash<StringRef>, HashTableGrowerWithPrecalculation<8ul>, Allocator<true>>>(ClearableHashSetWithSavedHash<StringRef, DefaultHash<StringRef>, HashTableGrowerWithPrecalculation<8ul>, Allocator<true>>&, unsigned long, DB::Arena&)
2023.07.24 21:44:26.943488 [ 658 ] {} <Fatal> BaseDaemon: 2. ./build_docker/./src/Processors/Transforms/DistinctSortedChunkTransform.cpp:96: unsigned long DB::DistinctSortedChunkTransform::buildFilterForRange<DB::SetMethodString<ClearableHashSetWithSavedHash<StringRef, DefaultHash<StringRef>, HashTableGrowerWithPrecalculation<8ul>, Allocator<true>>>>(DB::SetMethodString<ClearableHashSetWithSavedHash<StringRef, DefaultHash<StringRef>, HashTableGrowerWithPrecalculation<8ul>, Allocator<true>>>&, DB::PODArray<char8_t, 4096ul, Allocator<false>, 63ul, 64ul>&, unsigned long, unsigned long) @ 0x0000000015457210 in /clickhouse
2023.07.24 21:44:26.968660 [ 658 ] {} <Fatal> BaseDaemon: 3.1. inlined from ./build_docker/./src/Processors/Transforms/DistinctSortedChunkTransform.cpp:80: unsigned long DB::DistinctSortedChunkTransform::ordinaryDistinctOnRange<false>(DB::PODArray<char8_t, 4096ul, Allocator<false>, 63ul, 64ul>&, unsigned long, unsigned long)
2023.07.24 21:44:26.968699 [ 658 ] {} <Fatal> BaseDaemon: 3. ./build_docker/./src/Processors/Transforms/DistinctSortedChunkTransform.cpp:184: DB::DistinctSortedChunkTransform::continueWithPrevRange(unsigned long, DB::PODArray<char8_t, 4096ul, Allocator<false>, 63ul, 64ul>&) @ 0x0000000015455e7d in /clickhouse
2023.07.24 21:44:26.996861 [ 658 ] {} <Fatal> BaseDaemon: 4. ./build_docker/./src/Processors/Transforms/DistinctSortedChunkTransform.cpp:0: DB::DistinctSortedChunkTransform::transform(DB::Chunk&) @ 0x0000000015456072 in /clickhouse
2023.07.24 21:44:27.024511 [ 658 ] {} <Fatal> BaseDaemon: 5.1. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/__utility/swap.h:35: std::enable_if<is_move_constructible<COW<DB::IColumn>::immutable_ptr<DB::IColumn>*>::value && is_move_assignable<COW<DB::IColumn>::immutable_ptr<DB::IColumn>*>::value, void>::type std::swap[abi:v15000]<COW<DB::IColumn>::immutable_ptr<DB::IColumn>*>(COW<DB::IColumn>::immutable_ptr<DB::IColumn>*&, COW<DB::IColumn>::immutable_ptr<DB::IColumn>*&)
2023.07.24 21:44:27.024548 [ 658 ] {} <Fatal> BaseDaemon: 5.2. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/vector:1950: std::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn>>>::swap(std::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn>>>&)
2023.07.24 21:44:27.024600 [ 658 ] {} <Fatal> BaseDaemon: 5.3. inlined from ./build_docker/./src/Processors/Chunk.h:64: DB::Chunk::swap(DB::Chunk&)
2023.07.24 21:44:27.024646 [ 658 ] {} <Fatal> BaseDaemon: 5. ./build_docker/./src/Processors/ISimpleTransform.h:33: DB::ISimpleTransform::transform(DB::Chunk&, DB::Chunk&) @ 0x000000001138cdb0 in /clickhouse
2023.07.24 21:44:27.041637 [ 658 ] {} <Fatal> BaseDaemon: 6. ./build_docker/./src/Processors/ISimpleTransform.cpp:99: DB::ISimpleTransform::work() @ 0x00000000150ca0f2 in /clickhouse
2023.07.24 21:44:27.047095 [ 658 ] {} <Fatal> BaseDaemon: 7.1. inlined from ./build_docker/./src/Processors/Executors/ExecutionThreadContext.cpp:0: DB::executeJob(DB::ExecutingGraph::Node*, DB::ReadProgressCallback*)
2023.07.24 21:44:27.047127 [ 658 ] {} <Fatal> BaseDaemon: 7. ./build_docker/./src/Processors/Executors/ExecutionThreadContext.cpp:92: DB::ExecutionThreadContext::executeTask() @ 0x00000000150e3fe9 in /clickhouse
2023.07.24 21:44:27.065542 [ 658 ] {} <Fatal> BaseDaemon: 8. ./build_docker/./src/Processors/Executors/PipelineExecutor.cpp:255: DB::PipelineExecutor::executeStepImpl(unsigned long, std::atomic<bool>*) @ 0x00000000150dab50 in /clickhouse
2023.07.24 21:44:27.083716 [ 658 ] {} <Fatal> BaseDaemon: 9.1. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:833: std::shared_ptr<DB::ThreadGroup>::operator bool[abi:v15000]() const
2023.07.24 21:44:27.083748 [ 658 ] {} <Fatal> BaseDaemon: 9.2. inlined from ./build_docker/./src/Processors/Executors/PipelineExecutor.cpp:332: operator()
2023.07.24 21:44:27.083767 [ 658 ] {} <Fatal> BaseDaemon: 9.3. inlined from ./build_docker/./base/base/../base/scope_guard.h:99: BasicScopeGuard<DB::PipelineExecutor::spawnThreads()::$_0::operator()() const::'lambda'()>::invoke()
2023.07.24 21:44:27.083785 [ 658 ] {} <Fatal> BaseDaemon: 9.4. inlined from ./build_docker/./base/base/../base/scope_guard.h:48: ~BasicScopeGuard
2023.07.24 21:44:27.083800 [ 658 ] {} <Fatal> BaseDaemon: 9.5. inlined from ./build_docker/./src/Processors/Executors/PipelineExecutor.cpp:351: operator()
2023.07.24 21:44:27.083826 [ 658 ] {} <Fatal> BaseDaemon: 9.6. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/__functional/invoke.h:394: decltype(std::declval<DB::PipelineExecutor::spawnThreads()::$_0&>()()) std::__invoke[abi:v15000]<DB::PipelineExecutor::spawnThreads()::$_0&>(DB::PipelineExecutor::spawnThreads()::$_0&)
2023.07.24 21:44:27.083847 [ 658 ] {} <Fatal> BaseDaemon: 9.7. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/__functional/invoke.h:479: void std::__invoke_void_return_wrapper<void, true>::__call<DB::PipelineExecutor::spawnThreads()::$_0&>(DB::PipelineExecutor::spawnThreads()::$_0&)
2023.07.24 21:44:27.083873 [ 658 ] {} <Fatal> BaseDaemon: 9.8. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:235: std::__function::__default_alloc_func<DB::PipelineExecutor::spawnThreads()::$_0, void ()>::operator()[abi:v15000]()
2023.07.24 21:44:27.083890 [ 658 ] {} <Fatal> BaseDaemon: 9. ./build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:716: void std::__function::__policy_invoker<void ()>::__call_impl<std::__function::__default_alloc_func<DB::PipelineExecutor::spawnThreads()::$_0, void ()>>(std::__function::__policy_storage const*) @ 0x00000000150dbce3 in /clickhouse
2023.07.24 21:44:27.103962 [ 658 ] {} <Fatal> BaseDaemon: 10.1. inlined from ./build_docker/./base/base/../base/wide_integer_impl.h:809: bool wide::integer<128ul, unsigned int>::_impl::operator_eq<wide::integer<128ul, unsigned int>>(wide::integer<128ul, unsigned int> const&, wide::integer<128ul, unsigned int> const&)
2023.07.24 21:44:27.103990 [ 658 ] {} <Fatal> BaseDaemon: 10.2. inlined from ./build_docker/./base/base/../base/wide_integer_impl.h:1482: bool wide::operator==<128ul, unsigned int, 128ul, unsigned int>(wide::integer<128ul, unsigned int> const&, wide::integer<128ul, unsigned int> const&)
2023.07.24 21:44:27.104008 [ 658 ] {} <Fatal> BaseDaemon: 10.3. inlined from ./build_docker/./base/base/../base/strong_typedef.h:42: StrongTypedef<wide::integer<128ul, unsigned int>, DB::UUIDTag>::operator==(StrongTypedef<wide::integer<128ul, unsigned int>, DB::UUIDTag> const&) const
2023.07.24 21:44:27.104024 [ 658 ] {} <Fatal> BaseDaemon: 10.4. inlined from ./build_docker/./src/Common/OpenTelemetryTraceContext.h:65: DB::OpenTelemetry::Span::isTraceEnabled() const
2023.07.24 21:44:27.104035 [ 658 ] {} <Fatal> BaseDaemon: 10. ./build_docker/./src/Common/ThreadPool.cpp:429: ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::worker(std::__list_iterator<ThreadFromGlobalPoolImpl<false>, void*>) @ 0x000000000e902c0f in /clickhouse
2023.07.24 21:44:27.120601 [ 658 ] {} <Fatal> BaseDaemon: 11.1. inlined from ./build_docker/./src/Common/ThreadPool.cpp:0: operator()
2023.07.24 21:44:27.120634 [ 658 ] {} <Fatal> BaseDaemon: 11.2. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/__functional/invoke.h:394: decltype(std::declval<void>()()) std::__invoke[abi:v15000]<ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>(void&&)::'lambda'()&>(void&&)
2023.07.24 21:44:27.120655 [ 658 ] {} <Fatal> BaseDaemon: 11.3. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/__functional/invoke.h:479: void std::__invoke_void_return_wrapper<void, true>::__call<ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>(void&&)::'lambda'()&>(ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>(void&&)::'lambda'()&)
2023.07.24 21:44:27.120677 [ 658 ] {} <Fatal> BaseDaemon: 11.4. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:235: std::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>(void&&)::'lambda'(), void ()>::operator()[abi:v15000]()
2023.07.24 21:44:27.120688 [ 658 ] {} <Fatal> BaseDaemon: 11. ./build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:716: void std::__function::__policy_invoker<void ()>::__call_impl<std::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>(void&&)::'lambda'(), void ()>>(std::__function::__policy_storage const*) @ 0x000000000e90595c in /clickhouse
2023.07.24 21:44:27.132855 [ 658 ] {} <Fatal> BaseDaemon: 12.1. inlined from ./build_docker/./base/base/../base/wide_integer_impl.h:809: bool wide::integer<128ul, unsigned int>::_impl::operator_eq<wide::integer<128ul, unsigned int>>(wide::integer<128ul, unsigned int> const&, wide::integer<128ul, unsigned int> const&)
2023.07.24 21:44:27.132881 [ 658 ] {} <Fatal> BaseDaemon: 12.2. inlined from ./build_docker/./base/base/../base/wide_integer_impl.h:1482: bool wide::operator==<128ul, unsigned int, 128ul, unsigned int>(wide::integer<128ul, unsigned int> const&, wide::integer<128ul, unsigned int> const&)
2023.07.24 21:44:27.132895 [ 658 ] {} <Fatal> BaseDaemon: 12.3. inlined from ./build_docker/./base/base/../base/strong_typedef.h:42: StrongTypedef<wide::integer<128ul, unsigned int>, DB::UUIDTag>::operator==(StrongTypedef<wide::integer<128ul, unsigned int>, DB::UUIDTag> const&) const
2023.07.24 21:44:27.132912 [ 658 ] {} <Fatal> BaseDaemon: 12.4. inlined from ./build_docker/./src/Common/OpenTelemetryTraceContext.h:65: DB::OpenTelemetry::Span::isTraceEnabled() const
2023.07.24 21:44:27.132923 [ 658 ] {} <Fatal> BaseDaemon: 12. ./build_docker/./src/Common/ThreadPool.cpp:429: ThreadPoolImpl<std::thread>::worker(std::__list_iterator<std::thread, void*>) @ 0x000000000e8fe54f in /clickhouse
2023.07.24 21:44:27.149597 [ 658 ] {} <Fatal> BaseDaemon: 13.1. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:302: std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>::reset[abi:v15000](std::__thread_struct*)
2023.07.24 21:44:27.149621 [ 658 ] {} <Fatal> BaseDaemon: 13.2. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:259: ~unique_ptr
2023.07.24 21:44:27.149632 [ 658 ] {} <Fatal> BaseDaemon: 13.3. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/tuple:265: ~__tuple_leaf
2023.07.24 21:44:27.149642 [ 658 ] {} <Fatal> BaseDaemon: 13.4. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/tuple:538: ~tuple
2023.07.24 21:44:27.149659 [ 658 ] {} <Fatal> BaseDaemon: 13.5. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:48: std::default_delete<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void ThreadPoolImpl<std::thread>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>>::operator()[abi:v15000](std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void ThreadPoolImpl<std::thread>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>*) const
2023.07.24 21:44:27.149678 [ 658 ] {} <Fatal> BaseDaemon: 13.6. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:305: std::unique_ptr<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void ThreadPoolImpl<std::thread>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>, std::default_delete<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void ThreadPoolImpl<std::thread>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>>>::reset[abi:v15000](std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void ThreadPoolImpl<std::thread>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>*)
2023.07.24 21:44:27.149694 [ 658 ] {} <Fatal> BaseDaemon: 13.7. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:259: ~unique_ptr
2023.07.24 21:44:27.149704 [ 658 ] {} <Fatal> BaseDaemon: 13. ./build_docker/./contrib/llvm-project/libcxx/include/thread:297: void* std::__thread_proxy[abi:v15000]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void ThreadPoolImpl<std::thread>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>>(void*) @ 0x000000000e904541 in /clickhouse
2023.07.24 21:44:27.149719 [ 658 ] {} <Fatal> BaseDaemon: 14. ? @ 0x00007f41bb36db43 in ?
2023.07.24 21:44:27.149729 [ 658 ] {} <Fatal> BaseDaemon: 15. ? @ 0x00007f41bb3ffa00 in ?
2023.07.24 21:44:27.149740 [ 658 ] {} <Fatal> BaseDaemon: Integrity check of the executable skipped because the reference checksum could not be read.
2023.07.24 21:44:27.149761 [ 658 ] {} <Fatal> BaseDaemon: This ClickHouse version is not official and should be upgraded to the official build.
2023.07.24 21:44:27.149841 [ 658 ] {} <Fatal> BaseDaemon: No settings were changed
```

```
2023.07.24 21:44:21.160501 [ 557 ] {82347ee9-b23d-4e41-9669-1299d93d5115} <Debug> executeQuery: (from 127.0.0.1:57110) CREATE DATABASE IF NOT EXISTS database9TLPDistinct (stage: Complete)
2023.07.24 21:44:22.169747 [ 416 ] {2e4cab1b-9af9-4d56-80e3-b6758c79c374} <Debug> executeQuery: (from 127.0.0.1:57094) CREATE TABLE IF NOT EXISTS database9TLPDistinct.t0 (c0 String, c1 Int32, c2 Int32) ENGINE = Memory()  (stage: Complete)
2023.07.24 21:44:22.181219 [ 416 ] {3543a8c4-688a-4479-a643-f4c4802b1e74} <Debug> executeQuery: (from 127.0.0.1:57094) CREATE TABLE IF NOT EXISTS database9TLPDistinct.t1 (c0 String) ENGINE = MergeTree() ORDER BY tuple() PARTITION BY c0 SETTINGS allow_suspicious_indices=1 (stage: Complete)
2023.07.24 21:44:22.195360 [ 557 ] {4e5400f8-df75-45bb-a879-1612fabb2eb1} <Debug> executeQuery: (from 127.0.0.1:57110) CREATE TABLE database9TLPDistinct.t2 (c0 Int32) ENGINE = Log()  (stage: Complete)
2023.07.24 21:44:22.206087 [ 557 ] {b1b809cc-949a-480f-a776-3745b079a0bb} <Debug> executeQuery: (from 127.0.0.1:57110) CREATE TABLE database9TLPDistinct.t3 (c0 Int32, c1 String, c2 Int32) ENGINE = MergeTree() ORDER BY c0 SETTINGS allow_suspicious_indices=1 (stage: Complete)
2023.07.24 21:44:22.224379 [ 556 ] {d5acf0d7-ef2d-4fc2-b1d6-a3a5d2b6b216} <Debug> executeQuery: (from 127.0.0.1:57086) CREATE TABLE IF NOT EXISTS database9TLPDistinct.t4 (c0 Int32, c1 String, c2 String) ENGINE = Log()  (stage: Complete)
```

### PR DESCRIPTION
**Pull request by devcrafter**
Fixes https://github.com/ClickHouse/ClickHouse/issues/52540

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fixes possible crashes in `DISTINCT` queries with enabled `optimize_distinct_in_order` and sparse columns

### CODE REVIEW

**Comment by robot-ch-test-poll2** [comment]
This is an automated comment for commit 22895c1d0d751fbbd1a55846f449a511e3e51189 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/53711/22895c1d0d751fbbd1a55846f449a511e3e51189/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Comment by devcrafter** [comment]
The report which clarified the crash - https://s3.amazonaws.com/clickhouse-test-reports/0/90e8069681efaad9fa64b854b66470856cea7b04/sqlancer__debug_.html 

Stack - https://pastila.nl/?000e6f9a/96c7175c42567ca7c0dbe46c78a6f049#6rJqrejLC+ixTDd1nL/THw==

**Comment by devcrafter** [comment]
Upgrade check failure - fixed in https://github.com/ClickHouse/ClickHouse/pull/53611

**Review by alexey-milovidov — APPROVED** [review]

**Comment by antonio2368** [comment]
This broke FastTest

**Pull request merged**
