### PR TITLE
Improve performance of ASOF JOIN

### PR DESCRIPTION
**Pull request by kitaisreal**
Changelog category (leave one):
- Performance Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Improve performance of ASOF JOIN if key is native integer.

### CODE REVIEW

**Review by Algunenano — COMMENTED** [review]
Pretty nice.

I tried a similar approach and separate the entries from the RowRefs and couldn't make it work (it was slower). That was before pushing the order and strictness into the template / class and not as parameters, and I didn't think of using RadixSort in some situations, so I'm eagerly waiting for the performance results.

**Review by nikitamikhaylov — APPROVED** [review]

**Comment by kitaisreal** [comment]
@Mergifyio update

**Comment by kitaisreal** [comment]
@Algunenano seems like performance result only 30 percent improvement. Splitting entries and row refs does not improve performance of default sort method, but for Radix it is great improvement because it need to allocate underlying array.

**Comment by Algunenano** [comment]
30% is great. Keep in mind that this is on top of the other optimization included for the next release:
- 1st query: was 1s, then 0.65, now 0.48
- 2nd query: was 0.53s, then 0.36, now 0.27

Overall, with the 2 changes together, it is 2x as fast as the previous release. The t-shirts might not say it anymore, but CH is fast 😄

**Pull request merged**
