### PR TITLE
Fix inconsistent behavior caused by `select_sequential_consistency` for optimized trivial count query and system.tables

### PR DESCRIPTION
**Pull request by haoch**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Fix inconsistent behavior caused by `select_sequential_consistency` for optimized trivial count query and system.tables.

Detailed description / Documentation draft:

We got the following error even with `select_sequential_consistency=0` (disabled), it's very confusing for clickhouse users. 

```
clickhouse-client :) SET select_sequential_consistency = 0

clickhouse-client :) SELECT count(*) from TABLE
Received exception from server (version 20.7.2):
Code: 289. DB::Exception: Received from localhost:9000. DB::Exception: Replica doesn't have part 20200928-0_23211_23211_0 which was successfully written to quorum of other replicas. Send query to another replica or disable 'select_sequential_consistency' setting.: While executing Tables.
```

The root cause is when `optimize_trivial_count_query=1`, trivial count query will call directly`StorageReplicatedMergeTree.totalRows() --> 
 getMaxAddedBlocks()` (with sequential consistency check) at: [StorageReplicatedMergeTree.cpp#getMaxAddedBlocks](https://github.com/ClickHouse/ClickHouse/blob/master/src/Storages/StorageReplicatedMergeTree.cpp#L3503-L3508)

The error will also happen when query `select total_rows, total_bytes system.tables`.

By adding documentation, you'll allow users to try your new feature immediately, not when someone else will have time to document it later. Documentation is necessary for all features that affect user experience in any way. You can add brief documentation draft above, or add documentation right into your patch as Markdown files in docs folder.

If you are doing this for the first time, it's recommended to read the lightweight Contributing to ClickHouse Documentation guide first.

The Information about CI checks: https://clickhouse.tech/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by amosbird** [comment]
It's better to provide a variant `totalRows()` without sequential consistency, and imitate the behavior of the `read()` method https://github.com/ClickHouse/ClickHouse/blob/master/src/Storages/StorageReplicatedMergeTree.cpp#L3529

**Comment by haoch** [comment]
@amosbird I agree, but it may require to change the IStorage interface, do you think it's ok?

**Comment by haoch** [comment]
In fact, we got another similar exceptions while executing `select total_rows from system.tables` caused by the similar problem. If we could change `totalRows` interface, it will be better and we could resolve the bug in  [`StorageSystemTables`](https://github.com/ClickHouse/ClickHouse/blob/master/src/Storages/System/StorageSystemTables.cpp#L433) as well.

**Comment by amosbird** [comment]
> but it may require to change the IStorage interface

Yes. It's reasonable to have the current query context passed into this method. Then you have the related settings available.

**Comment by haoch** [comment]
@amosbird I have added query context in `totalRows` and `totalBytes` which may cause the above problem and supported correct`select_sequential_consistency` behavior for these two methods used in query like `count(*)` and `system.tables`. Please help review it again.

**Review by amosbird — APPROVED** [review]

**Comment by haoch** [comment]
Thanks @amosbird for approval. I made one more small change to fix the compiling.

**Comment by amosbird** [comment]
@haoch missing tests. You can refer to https://github.com/ClickHouse/ClickHouse/blob/master/tests/queries/0_stateless/00732_quorum_insert_select_with_old_data_and_without_quorum_zookeeper.sql  and write a simple test to ensure it works.

**Comment by haoch** [comment]
@amosbird Added test case in `01513_count_without_select_sequence_consistency.sql`

**Comment by haoch** [comment]
@amosbird How could it pass these 3 checks?

- Description check — Changelog entry is empty
- Yandex synchronization check (only for Yandex employees)
- Yandex third-party checks (only for Yandex employees)

**Comment by amosbird** [comment]
> Description check — Changelog entry is empty

image

And it's fixed by @alesapin  .

> Yandex synchronization check (only for Yandex employees) ...

The PR is almost fine. Now it's waiting for an approve from someone in the yandex team.

**Comment by haoch** [comment]
Thanks @amosbird, there is  one integration test failed [test_reload_zookeeper/test.py::test_reload_zookeeper](https://clickhouse-test-reports.s3.yandex.net/15428/cc2cb76295bf490387a1f8231f60b5a03c8e1d38/integration_tests_(asan)/integration_run.3.txt.out.log):

```
        ## stop all zookeepers, table will be readonly
        cluster.stop_zookeeper_nodes(["zoo1", "zoo2", "zoo3"])
        with pytest.raises(QueryRuntimeException):
>           node.query("SELECT COUNT() FROM test_table")
E           Failed: DID NOT RAISE <class 'helpers.client.QueryRuntimeException'>
```

Do we really expect `select count()` will not work and throw an exception when the zookeeper is unavailable or table becomes read-only?

**Comment by haoch** [comment]
I think the integration test case [`test_reload_zookeeper`](https://github.com/ClickHouse/ClickHouse/tree/master/tests/integration/test_reload_zookeeper) needs a fix to ensure `select_sequential_consistency = 1` and `optimize_trivial_count_query=1` in `users.xml`: https://github.com/ClickHouse/ClickHouse/pull/15428/commits/76182694b0bc836d51a9ec470d0adea3456cc489, so that it could ganrantee `SELECT COUNT()` will help check zookeeper connection correctly.

**Comment by haoch** [comment]
**AST fuzzer** test failed due to `Logical error: 'Cannot sum Tuples'. Assertion `false' failed Received signal 6 Received signal Aborted (6)`: https://clickhouse-test-reports.s3.yandex.net/15428/cbf3af401d906a3b342f2b8cc54a7508e933d8ea/fuzzer/report.html#fail1

```
2020.10.04 14:21:39.201616 [ 97 ] {b365ab34-9e5d-4759-8923-fdc4b77293fd} <Debug> executeQuery: (from [::1]:59148) SELECT sumMapWithOverflow(arrayJoin([([1], [([1048577], NULL, [NULL, NULL])], [(arrayJoin([([], [NULL])]), [tuple([1, 65537, 65535])], NULL)], [NULL])]))
2020.10.04 14:21:39.217176 [ 97 ] {b365ab34-9e5d-4759-8923-fdc4b77293fd} <Trace> ContextAccess (default): Access granted: SELECT(dummy) ON system.one
2020.10.04 14:21:39.217620 [ 97 ] {b365ab34-9e5d-4759-8923-fdc4b77293fd} <Trace> InterpreterSelectQuery: FetchColumns -> Complete
2020.10.04 14:21:39.230525 [ 243 ] {b365ab34-9e5d-4759-8923-fdc4b77293fd} <Trace> AggregatingTransform: Aggregating
2020.10.04 14:21:39.230610 [ 243 ] {b365ab34-9e5d-4759-8923-fdc4b77293fd} <Trace> Aggregator: Aggregation method: without_key
2020.10.04 14:21:39.231082 [ 243 ] {b365ab34-9e5d-4759-8923-fdc4b77293fd} <Error> : Logical error: 'Cannot sum Tuples'.
clickhouse-server: ../src/Common/Exception.cpp:45: DB::Exception::Exception(const std::string &, int): Assertion `false' failed.
2020.10.04 14:21:39.231546 [ 64 ] {} <Trace> BaseDaemon: Received signal 6
2020.10.04 14:21:39.231977 [ 249 ] {} <Fatal> BaseDaemon: ########################################
2020.10.04 14:21:39.232586 [ 249 ] {} <Fatal> BaseDaemon: (version 20.10.1.4836, build id: 65362BD6FD343697) (from thread 243) (query_id: b365ab34-9e5d-4759-8923-fdc4b77293fd) Received signal Aborted (6)
2020.10.04 14:21:39.232771 [ 249 ] {} <Fatal> BaseDaemon: 
2020.10.04 14:21:39.232982 [ 249 ] {} <Fatal> BaseDaemon: Stack trace: 0x7f76f2100f47 0x7f76f21028b1 0x7f76f20f242a 0x7f76f20f24a2 0xfa41e8c 0x1005a10f 0x10059b41 0x100593c2 0x100dc43b 0x100dd3c6 0x1871d151 0x1871e377 0x1990aedb 0x199092f1 0x1963e38c 0x1963e2ef 0x1963e2ad 0x1963e25d 0x1963e22d 0x1963d38e 0xfa64475 0xfa63395 0x1963bca5 0x1963c499 0x1963aa10 0x19639ff6 0x1965477b 0x196546e2
2020.10.04 14:21:39.233362 [ 249 ] {} <Fatal> BaseDaemon: 4. /build/glibc-2ORdQG/glibc-2.27/signal/../sysdeps/unix/sysv/linux/raise.c:51: gsignal @ 0x3ef47 in /usr/lib/debug/lib/x86_64-linux-gnu/libc-2.27.so
2020.10.04 14:21:39.233634 [ 249 ] {} <Fatal> BaseDaemon: 5. /build/glibc-2ORdQG/glibc-2.27/stdlib/abort.c:81: __GI_abort @ 0x408b1 in /usr/lib/debug/lib/x86_64-linux-gnu/libc-2.27.so
2020.10.04 14:21:39.233880 [ 249 ] {} <Fatal> BaseDaemon: 6. /build/glibc-2ORdQG/glibc-2.27/assert/assert.c:89: __assert_fail_base @ 0x3042a in /usr/lib/debug/lib/x86_64-linux-gnu/libc-2.27.so
2020.10.04 14:21:39.234291 [ 249 ] {} <Fatal> BaseDaemon: 7. ? @ 0x304a2 in /usr/lib/debug/lib/x86_64-linux-gnu/libc-2.27.so
2020.10.04 14:21:39.234681 [ 249 ] {} <Fatal> BaseDaemon: 8. /build/obj-x86_64-linux-gnu/../src/Common/Exception.cpp:48: DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0xfa41e8c in /workspace/clickhouse
2020.10.04 14:21:39.237799 [ 249 ] {} <Fatal> BaseDaemon: 9. /build/obj-x86_64-linux-gnu/../src/Common/FieldVisitors.h:256: DB::FieldVisitorSum::operator()(DB::Tuple&) const @ 0x1005a10f in /workspace/clickhouse
2020.10.04 14:21:39.240815 [ 249 ] {} <Fatal> BaseDaemon: 10. /build/obj-x86_64-linux-gnu/../src/Core/Field.h:575: auto DB::Field::dispatch<DB::FieldVisitorSum, DB::Field&>(DB::FieldVisitorSum&&, DB::Field&) @ 0x10059b41 in /workspace/clickhouse
2020.10.04 14:21:39.243800 [ 249 ] {} <Fatal> BaseDaemon: 11. /build/obj-x86_64-linux-gnu/../src/Common/FieldVisitors.h:45: auto DB::applyVisitor<DB::FieldVisitorSum, DB::Field&>(DB::FieldVisitorSum&&, DB::Field&) @ 0x100593c2 in /workspace/clickhouse
2020.10.04 14:21:39.253047 [ 249 ] {} <Fatal> BaseDaemon: 12. /build/obj-x86_64-linux-gnu/../src/AggregateFunctions/AggregateFunctionSumMap.h:173: DB::AggregateFunctionMapBase<char8_t, DB::AggregateFunctionSumMap<char8_t, true, true>, DB::FieldVisitorSum, true, true>::add(char*, DB::IColumn const**, unsigned long, DB::Arena*) const @ 0x100dc43b in /workspace/clickhouse
2020.10.04 14:21:39.262249 [ 249 ] {} <Fatal> BaseDaemon: 13. /build/obj-x86_64-linux-gnu/../src/AggregateFunctions/IAggregateFunction.h:229: DB::IAggregateFunctionHelper<DB::AggregateFunctionSumMap<char8_t, true, true> >::addBatchSinglePlace(unsigned long, char*, DB::IColumn const**, DB::Arena*) const @ 0x100dd3c6 in /workspace/clickhouse
2020.10.04 14:21:39.303481 [ 249 ] {} <Fatal> BaseDaemon: 14. /build/obj-x86_64-linux-gnu/../src/Interpreters/Aggregator.cpp:624: DB::Aggregator::executeWithoutKeyImpl(char*&, unsigned long, DB::Aggregator::AggregateFunctionInstruction*, DB::Arena*) @ 0x1871d151 in /workspace/clickhouse
```

How could it be related?

**Comment by haoch** [comment]
@amosbird @alesapin Please review again if the PR is ready to merge.

**Comment by amosbird** [comment]
Sorry for the delay. We're aware of this issue https://github.com/ClickHouse/ClickHouse/issues/16108 and it's expected to be merged soon.

**Comment by haoch** [comment]
This PR included some unrelated changes, recreate another PR with clean code at https://github.com/ClickHouse/ClickHouse/pull/16309 cc: @amosbird

**Pull request closed without merging**
