### PR TITLE
Use a proper way to download packages from releases

### PR DESCRIPTION
**Pull request by Felixoid**
### Changelog category (leave one):
- Build/Testing/Packaging Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Get rid of custom code in `tests/ci/download_release_packages.py` and `tests/ci/get_previous_release_tag.py` to avoid issues after the https://github.com/ClickHouse/ClickHouse/pull/64759 is merged.

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All NOT Required Checks
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [x]  Exclude: Fast test
- [x]  Exclude: AST fuzzer
- [x]  Exclude: AST fuzzer
- [x]  Exclude: Unit Tests
- [x]  Exclude: Integration Tests
- [x]  Exclude: Stateless tests
- [x]  Exclude: Stateful tests
- [x]  Exclude: Performance tests
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with Aarch64
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
---
- [ ]  Do not test
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-ch-test-poll** [comment]
*This is an automated comment for commit ee386efc6e16c97c66bf1dce995934fcfbe1b01b with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/64848/ee386efc6e16c97c66bf1dce995934fcfbe1b01b/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>A Sync</td><td>If it fails, ask a maintainer for help</td><td>⏳ pending</td></tr>
<tbody>
</table>
<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>Checks correctness of the PR's body</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

**Comment by Felixoid** [comment]
It finally should work

```
root@5be2706cc9ae:/ClickHouse/tests/ci# echo 24.6.1.3077 | ./get_previous_release_tag.py | ./download_release_packages.py
INFO:root:Will download v24.5.1.1763-stable
INFO:root:Downloading from https://github.com/ClickHouse/ClickHouse/releases/download/v24.5.1.1763-stable/clickhouse-client_24.5.1.1763_amd64.deb to temp path previous_release_package_folder/clickhouse-client_24.5.1.1763_amd64.deb
INFO:root:Getting URL with 1 tries and sleep 3 in between: https://github.com/ClickHouse/ClickHouse/releases/download/v24.5.1.1763-stable/clickhouse-client_24.5.1.1763_amd64.deb
INFO:root:The file previous_release_package_folder/clickhouse-client_24.5.1.1763_amd64.deb already exists and have a proper size 50828
INFO:root:Downloading from https://github.com/ClickHouse/ClickHouse/releases/download/v24.5.1.1763-stable/clickhouse-common-static_24.5.1.1763_amd64.deb to temp path previous_release_package_folder/clickhouse-common-static_24.5.1.1763_amd64.deb
INFO:root:Getting URL with 1 tries and sleep 3 in between: https://github.com/ClickHouse/ClickHouse/releases/download/v24.5.1.1763-stable/clickhouse-common-static_24.5.1.1763_amd64.deb
INFO:root:The file previous_release_package_folder/clickhouse-common-static_24.5.1.1763_amd64.deb already exists and have a proper size 141955546
INFO:root:Downloading from https://github.com/ClickHouse/ClickHouse/releases/download/v24.5.1.1763-stable/clickhouse-keeper_24.5.1.1763_amd64.deb to temp path previous_release_package_folder/clickhouse-keeper_24.5.1.1763_amd64.deb
INFO:root:Getting URL with 1 tries and sleep 3 in between: https://github.com/ClickHouse/ClickHouse/releases/download/v24.5.1.1763-stable/clickhouse-keeper_24.5.1.1763_amd64.deb
INFO:root:The file previous_release_package_folder/clickhouse-keeper_24.5.1.1763_amd64.deb already exists and have a proper size 11319078
INFO:root:Downloading from https://github.com/ClickHouse/ClickHouse/releases/download/v24.5.1.1763-stable/clickhouse-library-bridge_24.5.1.1763_amd64.deb to temp path previous_release_package_folder/clickhouse-library-bridge_24.5.1.1763_amd64.deb
INFO:root:Getting URL with 1 tries and sleep 3 in between: https://github.com/ClickHouse/ClickHouse/releases/download/v24.5.1.1763-stable/clickhouse-library-bridge_24.5.1.1763_amd64.deb
INFO:root:The file previous_release_package_folder/clickhouse-library-bridge_24.5.1.1763_amd64.deb already exists and have a proper size 360460754
INFO:root:Downloading from https://github.com/ClickHouse/ClickHouse/releases/download/v24.5.1.1763-stable/clickhouse-odbc-bridge_24.5.1.1763_amd64.deb to temp path previous_release_package_folder/clickhouse-odbc-bridge_24.5.1.1763_amd64.deb
INFO:root:Getting URL with 1 tries and sleep 3 in between: https://github.com/ClickHouse/ClickHouse/releases/download/v24.5.1.1763-stable/clickhouse-odbc-bridge_24.5.1.1763_amd64.deb
INFO:root:The file previous_release_package_folder/clickhouse-odbc-bridge_24.5.1.1763_amd64.deb already exists and have a proper size 362261256
INFO:root:Downloading from https://github.com/ClickHouse/ClickHouse/releases/download/v24.5.1.1763-stable/clickhouse-server_24.5.1.1763_amd64.deb to temp path previous_release_package_folder/clickhouse-server_24.5.1.1763_amd64.deb
INFO:root:Getting URL with 1 tries and sleep 3 in between: https://github.com/ClickHouse/ClickHouse/releases/download/v24.5.1.1763-stable/clickhouse-server_24.5.1.1763_amd64.deb
INFO:root:The file previous_release_package_folder/clickhouse-server_24.5.1.1763_amd64.deb already exists and have a proper size 77924
```

**Comment by Felixoid** [comment]
No it's not

**Comment by Felixoid** [comment]
https://github.com/ClickHouse/ClickHouse/actions/runs/9395581369/job/25877562704?pr=64848#step:8:794 finally!

**Pull request merged**
