### PR TITLE
Set the schema as optional for path and pathFull function

### PR DESCRIPTION
**Pull request by YiuRULE**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

For changelog. Remove if this is non-significant change.

Category (leave one):
- Improvement

Short description (up to few sentences):

Followup PR for https://github.com/yandex/ClickHouse/pull/5045.
Applied similar changes for the function `path` and `pathFull` function, with making the schema as optional. (we don't need to do have `//` in the beginning of the URL and accept url like `www.example.com`)

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
It looks like `path` became 19% slower. Let's check it carefully with `clickhouse-benchmark` and think what we can do...

**Comment by YiuRULE** [comment]
Any news about this PR ? most of the changes who has been made was related to this PR https://github.com/ClickHouse/ClickHouse/pull/5045

**Comment by YiuRULE** [comment]
@Akazz Hi Akazz, did you had time to check a bit about this PR ? does I need to change something on my side ?

**Comment by alexey-milovidov** [comment]
We need to apply any sort of magic to make the function as fast as before.

**Comment by alexey-milovidov** [comment]
Continued in #10269
I have added your tests and slightly modified the code.
Let's look at performance tests...

**Comment by alexey-milovidov** [comment]
And sorry for the delay :joy_cat:

**Pull request closed without merging**
