### PR TITLE
WIP: basic rate() function

### PR DESCRIPTION
**Pull request by tsl-karlp**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

We have a use case for a basic `rate()` function, and we're wondering if someone could provide us with feedback.

We're not sure if we're using the internal Clickhouse API correctly.

Thank you!

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
API usage looks correct.

As I understand, this aggregate function takes leftmost and rightmost point (x, y) and returns a "slope" between them. This is all right. The only question is how useful it would be and whether "rate" is an appropriate name for it.

Examples:

When user wants to estimate "slope", "rate of growth", etc., it is usually better to make a linear regression. But proposed function only takes values of two marginal points and completely ignores other points. This still can be useful, but naming is the subject of doubt.

When user wants to calculate derivative, it will be not an aggregate function. Derivative have locality principle - it depends only on neighbourhood of a point.

Do you have any examples of this or related functions in other DBMS or math/statistical packages?

**Comment by tsl-karlp** [comment]
Thank you, @alexey-milovidov .  I agree, the name isn't right.   Does it have to be an  aggregate function to use with a `GROUP BY sensor_id`, for example?.  We have IoT use case where we have temperature readings, for example:


| sensor_id | time | battery_level |
| ------------- | ------------- | ------------- |
| 1 | 1536952113  | 20.2  |
| 1 | 1536955213  | 20.2  |
| 2 | 1536951313 | 16.2 |
| 2 | 1536952313 | 16.2 |
| 2 | 1536953313 | 16.3 |

We are envisioning  a query like:

`select sensor_id, rate(time, battery_level) from readings where time > toStartOfFifteenMinutes(time) group by sensor_id`

...to provide us a basic look at whether sensors are charging/discharging.

We can also write a  continuous slope / linear regression function, but we're not sure how how to model this with the Clickhouse API.  What's the best function to look at as an example?  What do you recommend?

**Comment by sundy-li** [comment]
I do think that [runningDifference](https://clickhouse.yandex/docs/en/query_language/functions/other_functions/#runningdifferencex) could meet your needs better than creating a new AggregateFunction rate.

Eg. 

```

SELECT
    number AS time,
    number * number AS level,
    runningDifference(level) / runningDifference(time) AS rate
FROM numbers(10)

```

**Comment by filimonov** [comment]
Also you can use combinations of max / min / argMax / argMin, like that:
```sql
SELECT
   sensor_id,
   max(time) - min(time) as time_difference_in_sec,
   argMax(battery_level,time) - argMin(battery_level,time) as battery_level_change,
  battery_level_change / time_difference_in_sec as rate
FROM table
WHERE  ...
GROUP BY sensor_id```

**Comment by alexey-milovidov** [comment]
We can merge it if we will find appropriate name.
`boundingBoxRatio`, `boundingRatio`, `boundaryRatio`, `minmaxSlope`...

**Comment by alexey-milovidov** [comment]
Do you know something similar in Matlab, R, Python, ...?

**Comment by alexey-milovidov** [comment]
I choose the name `boundingRatio`.

**Comment by alexey-milovidov** [comment]
@tsl-karlp Merged to master.

**Pull request merged**
