### PR TITLE
Fix crash in ParallelReadBuffer

### PR DESCRIPTION
**Pull request by Avogar**
### Changelog category (leave one):
- Bug Fix (user-visible misbehaviour in official stable or prestable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix crash in ParallelReadBuffer

> Information about CI checks: https://clickhouse.tech/docs/en/development/continuous-integration/

### CODE REVIEW

**Review by antonio2368 — APPROVED** [review]

**Comment by tavplubix** [comment]
Why not to make it `std::atomic_size_t`? Looks like the mutex is not needed for `active_working_reader` at all, because `fetch_add` and `fetch_sub` are enough. Also `readers_done` condvar is not really needed, because `std::atomic` supports `wait` and `notify_one`/`notify_all` since C++20.

**Comment by Avogar** [comment]
> Why not to make it `std::atomic_size_t`? Looks like the mutex is not needed for `active_working_reader` at all, because `fetch_add` and `fetch_sub` are enough. Also `readers_done` condvar is not really needed, because `std::atomic` supports `wait` and `notify_one`/`notify_all` since C++20.

I also thought about it, let's do this. Will create a new PR with it

**Comment by tavplubix** [comment]
@Avogar, you forgot to take a look at failed tests before merging.
Integration tests failures are related.
Now integration tests are broken in master and fail on every commit, so I'll revert.

**Comment by tavplubix** [comment]
https://play.clickhouse.com/play?user=play#c2VsZWN0IAp0b1N0YXJ0T2ZIb3VyKGNoZWNrX3N0YXJ0X3RpbWUpIGFzIGQsCmNvdW50KCksIGdyb3VwVW5pcUFycmF5KHB1bGxfcmVxdWVzdF9udW1iZXIpCmZyb20gY2hlY2tzIHdoZXJlICcyMDIyLTAzLTAxJyA8PSBjaGVja19zdGFydF90aW1lIGFuZCB0ZXN0X25hbWUgbGlrZSAndGVzdF9zdG9yYWdlX3MzL3Rlc3QucHk6OnRlc3RfcGFyYWxsZWxfcmVhZGluZ193aXRoX21lbW9yeV9saW1pdCcgYW5kIHRlc3Rfc3RhdHVzIGluICgnRkFJTCcsICdGTEFLWScsICdFUlJPUicpIGdyb3VwIGJ5IGQgb3JkZXIgYnkgZCBkZXNj

**Comment by Avogar** [comment]
> @Avogar, you forgot to take a look at failed tests before merging. Integration tests failures are related. Now integration tests are broken in master and fail on every commit, so I'll revert.

My fault, will fix, sorry.

**Pull request merged**
