### PR TITLE
Randomize disabled optimizations in CI

### PR DESCRIPTION
**Pull request by Algunenano**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Randomize these optimizations that are disabled by default. Do they work correctly? Should they be on instead? Let's see

### CODE REVIEW

**Comment by robot-ch-test-poll3** [comment]
*This is an automated comment for commit ade60b5b45283adddfcf166d5a5c865c7a4da16f with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/57315/ade60b5b45283adddfcf166d5a5c865c7a4da16f/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td><a href="https://github.com/ClickHouse/ClickHouse/actions/runs/7019301151">✅ success</a></td></tr>
<tbody>
</table>
</details>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/57315/ade60b5b45283adddfcf166d5a5c865c7a4da16f/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Comment by Algunenano** [comment]
So many red tests, which is both nice (detecting issues) and bad (detecting issues).

`00083_array_filter` failed because of optimize_functions_to_subcolumns -> https://github.com/ClickHouse/ClickHouse/issues/57326

Need time to review the rest of the failures

**Comment by novikd** [comment]
> Do they work correctly? Should they be on instead? Let's see

How random settings would help to understand that?

**Comment by Algunenano** [comment]
> How would random settings help to understand that?

Yeah, I should probably have started by enabling them by default first and then we could leave them random. I'll update and keep analyzing the errors to report bugs found

**Comment by Algunenano** [comment]
Much better results now, and by better I mean horrible :smile: Several crashes and sanitizer alerts. I'll start reporting

**Comment by Algunenano** [comment]
Failures:
* `Performance Comparison [1/4]`: Ignoring it for now, although the slowdown in `map_update` might be related (not sure if performance tests pick the randomness though).
* Stateful tests (aarch64): Failing in `00083_array_filter`, `00078_group_by_arrays` and `00013_sorting_of_nested` with `optimize_functions_to_subcolumns`, both with and without the analyzer. -> https://github.com/ClickHouse/ClickHouse/issues/57326
* Stateful tests SANITIZERS/DEBUG. Triggering the logical error in `00083_array_filter`, which then stops the server and kills the tests.
* `Stateless tests (aarch64) `. Hard crash (`signal 11`): Crash in 01825_type_json_in_other_types.sh. JSON + `optimize_functions_to_subcolumns` -> https://github.com/ClickHouse/ClickHouse/issues/57384 
* `ClickHouse Stateless Tests (asan) [1/4]`: Same problem.
* `ClickHouse Stateless Tests (asan) [2/4]`. Minor tweaks needed for `02498_analyzer_settings_push_down`.
* `ClickHouse Stateless Tests (asan) [3/4]`. Logical error when running `02565_update_empty_nested.sql` and `optimize_functions_to_subcolumns`.
*  `ClickHouse Stateless Tests (asan) [4/4]`: `02911_join_on_nullsafe_optimization.sql`, `01030_incorrect_count_summing_merge_tree` and `02892_orc_filter_pushdown` are all failing with `optimize_functions_to_subcolumns`too.

Before continuing it's pretty obvious that `optimize_functions_to_subcolumns` is not ready for usage, so I'll disable it and retry everything to analyzer only the other settings (which have shown no issues so far)

**Comment by Algunenano** [comment]
I'm removing the randomization of optimize_using_constraints and I expect the rest to be clean. I'm tempted to remove broken optimizations, at least for the old infra (not analyzer), but we can do that in other PRs if and when the proper fix is done.

**Comment by Algunenano** [comment]
Only unrelated (flaky) failures. I'll set the PR to only enable randomization of these settings for now, so at least we know they get usage continuosly and it's easier to decide whether to enable them by default or not

**Comment by Algunenano** [comment]
Changes look harmless so I'm merging.

**Pull request merged**
