### PR TITLE
Fix: creation of view with recursive CTE

### LINKED ISSUE #64754: Recursive CTE view creation exception.
When creating a view with recursive CTE, it give an exception wiht: Unknown table expression identifier....

**Does it reproduce on the most recent release?**
We are using version 24.4.1.2088
But testing with version 24.5.1 gives the same error

**How to reproduce**
Take the recursive CTE example from documentation and wrap it in the view:

```CREATE VIEW test_table_v 
  as 
WITH RECURSIVE test_table AS (
SELECT 1 AS number
 UNION ALL
SELECT number + 1 
  FROM test_table WHERE number < 100
)
SELECT sum(number) 
  FROM test_table
  ```

The same example can be tested here: https://fiddle.clickhouse.com/6e2c3c6b-ece9-466e-b2a4-a44caed06a9a

**Error message and/or stacktrace**

```Received exception from server (version 24.4.1):
Code: 60. DB::Exception: Received from localhost:9000. DB::Exception: Unknown table expression identifier 'default.test_table' in scope SELECT number + 1 FROM default.test_table WHERE number < 100. (UNKNOWN_TABLE)
(query: CREATE VIEW test_table_v 
  as 
WITH RECURSIVE test_table AS (
SELECT 1 AS number
 UNION ALL
SELECT number + 1 
  FROM test_table WHERE number < 100
)
SELECT sum(number) 
  FROM test_table)
```

The 'default.test_table' is not a table in `default` schema - it is a CTE and should not have any problems with creating a view.

### PR DESCRIPTION
**Pull request by yakov-olkhovskiy**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix creation of view with recursive CTE

fixes #64754

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-clickhouse** [comment]
*This is an automated comment for commit d83c0c1b3b189a78833afec5f87e7004b0f934e3 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/67587/d83c0c1b3b189a78833afec5f87e7004b0f934e3/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/62ba20a2771c2cefb94680fa73d1f38c866eed7a/docs_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Review by alexkats — APPROVED** [review]
Shouldn't it be backported to 24.7?

**Comment by pkit** [comment]
Looks incomplete. Will probably fail with multiple CTEs (one of them recursive).
See example in #64794
```sql
WITH RECURSIVE 
     task as (select number as task_id, number-1 as parent_id from numbers(10)),
     rtq AS (
     SELECT task_id, parent_id FROM  task as t WHERE t.parent_id = 1
       UNION ALL
     SELECT t.task_id, t.parent_id FROM task AS t, rtq as r WHERE t.parent_id = r.task_id
    )
SELECT count() FROM rtq;
```

**Comment by yakov-olkhovskiy** [comment]
02908_many_requests_to_system_replicas is flaky:
https://github.com/ClickHouse/ClickHouse/issues/67216

**Comment by clickgapai** [comment]
Hi @yakov-olkhovskiy @alexkats — while reviewing this PR I found the following:

- **Bug (P1):** `with_aliases` scope contamination causes table references to not be qualified in sibling UNION branches — https://github.com/ClickHouse/ClickHouse/issues/104972

Happy to discuss — close anything that's wrong or already addressed.

**Pull request merged**
