### PR TITLE
test for datetime64 monotonic #39864

### PR DESCRIPTION
**Pull request by den-crane**
test for datetime64 monotonic #39864

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
It failed. Maybe need to add ORDER BY or to use fixed time zone.

**Comment by den-crane** [comment]
I am working on it. 
I'm still trying to check / checking ideas that https://github.com/ClickHouse/ClickHouse/pull/39864 does not break anything.

**Comment by alexey-milovidov** [comment]
@kssenii `test_hive_query` has failed.

**Comment by tavplubix** [comment]
New test is flaky (probably because of randomized timezone in tests):
https://play.clickhouse.com/play?user=play#c2VsZWN0IAp0b1N0YXJ0T2ZEYXkoY2hlY2tfc3RhcnRfdGltZSkgYXMgZCwKY291bnQoKSwgIGdyb3VwVW5pcUFycmF5KHB1bGxfcmVxdWVzdF9udW1iZXIpLCBhbnkocmVwb3J0X3VybCkKZnJvbSBjaGVja3Mgd2hlcmUgJzIwMjItMDYtMDEnIDw9IGNoZWNrX3N0YXJ0X3RpbWUgYW5kIHRlc3RfbmFtZSBsaWtlICcwMjM3M19kYXRldGltZTY0X21vbm90b25pY2l0eSUnIGFuZCB0ZXN0X3N0YXR1cyBpbiAoJ0ZBSUwnLCAnRkxBS1knKSBncm91cCBieSBkIG9yZGVyIGJ5IGQgZGVzYw==

**Comment by den-crane** [comment]
@tavplubix  Probably is because of `02373_datetime64_monotonicity.sql` - it can be removed, because it tests nothing.

02373_datetime64_monotonicity1.sh -- is not flaky

**Comment by tavplubix** [comment]
Could you please make a PR that removes `02373_datetime64_monotonicity`? (and consider renaming `02373_datetime64_monotonicity1` to `02373_datetime64_monotonicity`)

**Pull request merged**
