### PR TITLE
SQL Fix for converting to denormalized "flat schema":

### PR DESCRIPTION
**Pull request by den-crane**
star_schema example fix for unsupported SQL

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
Ok, but I missed the moment when it started to be unsupported. 
@4ertus2 Why?

**Comment by 4ertus2** [comment]
It's better to save user from the errors of names misqualification until we make #4567

**Comment by den-crane** [comment]
hm. Actually I made a bad fix. It's still gives the error because of column names for CREATE TABLE. 

But 19.8.3
And * actually works

DESCRIBE TABLE
(
    SELECT *
    FROM lineorder AS l
    ANY INNER JOIN customer AS c ON c.C_CUSTKEY = l.LO_CUSTKEY
    ANY INNER JOIN supplier AS s ON s.S_SUPPKEY = l.LO_SUPPKEY
    ANY INNER JOIN part AS p ON p.P_PARTKEY = l.LO_PARTKEY
)

But still it will not allow create a new table because of column names with table aliases l.LO_ORDERKEY

**Comment by den-crane** [comment]
I'll test and make a new fix for star_schema.md

**Pull request merged**
