### PR TITLE
add quota type QUERY_SELECTS and QUERY_INSERTS

### PR DESCRIPTION
**Pull request by JackyWoo**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- New Feature

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Add quota type QUERY_SELECTS and QUERY_INSERTS.

* QUERY_SELECTS limit select queries
* QUERY_INSERTS limit insert queries.

This pr implement #19610

### CODE REVIEW

**Comment by JackyWoo** [comment]
Can anybody help. I just modify the English docs in “docs/en” folder. How can I modify other languages  conviniently?

**Comment by alexey-milovidov** [comment]
No need to modify other languages, english is enough.

**Comment by alexey-milovidov** [comment]
Need to adjust integration tests.

**Comment by alexey-milovidov** [comment]
The code LGTM.

**Comment by alexey-milovidov** [comment]
@vitlibar I think we can generalize Quotas further (after merging this PR) by allowing to use all the existing ProfileEvents. What do you think?

**Comment by JackyWoo** [comment]
Thanks. I will commit the integration test in a few days.

> @vitlibar I think we can generalize Quotas further (after merging this PR) by allowing to use all the existing ProfileEvents. What do you think?

As I understanding you mean add all ProfileEvents to quotas. In my opintion it will expand user contorls, but there are too many iterms which may cause user confusing and much of iterm quantization is difficult. So I think generalize Quotas for all ProfileEvents need to weigh carefully.

**Comment by alexey-milovidov** [comment]
> As I understanding you mean add all ProfileEvents to quotas.

Yes. For some profile events it does not make sense, but it's very tempting to add all of them "for free".
For example, we will be able to set up quota on disk IO, CPU in userspace, etc...

**Comment by JackyWoo** [comment]
Adding  disk IO, CPU in userspace, network bytes transferred etc... to quotas is excellent. What I am wondering is that why add all but not what we need.

**Comment by alexey-milovidov** [comment]
Code complexity / maintainability. We want some uniform approach to events, metrics, quotas, limits, resource sharing... This task is currently unsolved.

**Comment by JackyWoo** [comment]
Understand.

**Comment by JackyWoo** [comment]
Can any body help？CI check failed at functional test '01297_create_quota' which is ok in my local environment.

I checked the clickhouse server log and found that the test run more than one time in parallel, so the first sql  "create quota q1_01297" run more than one time wiout dropping.

Below is the clickhouse server log:

```
2021.02.02 12:55:37.961512 [ 149 ] {2fa8ab79-fe13-4092-bf40-2e584fdc603c} <Debug> executeQuery: (from [::1]:34966, using production parser) (comment: /usr/share/clickhouse-test/queries/0_stateless/01297_create_quota.sql) CREATE QUOTA q1_01297;
2021.02.02 12:55:37.963500 [ 246 ] {6b291a58-cc7f-4d22-a1ef-18da363ac552} <Debug> MemoryTracker: Peak memory usage (for query): 0.00 B.
2021.02.02 12:55:37.963719 [ 247 ] {c2013de7-80dd-4e10-9d7c-79418b02c647} <Debug> executeQuery: (from [::1]:34968, using production parser) (comment: /usr/share/clickhouse-test/queries/0_stateless/01297_create_quota.sql) CREATE QUOTA q1_01297;
2021.02.02 12:55:37.964490 [ 246 ] {} <Debug> TCPHandler: Processed in 0.006122562 sec.
2021.02.02 12:55:37.964586 [ 247 ] {c2013de7-80dd-4e10-9d7c-79418b02c647} <Trace> ContextAccess (default): Access granted: CREATE QUOTA ON *.*
2021.02.02 12:55:37.966607 [ 148 ] {7ecece65-d65f-459b-befb-16dd83031f2a} <Information> executeQuery: Read 1 rows, 1.00 B in 0.019312199 sec., 51 rows/sec., 51.78 B/sec.
2021.02.02 12:55:37.967679 [ 148 ] {7ecece65-d65f-459b-befb-16dd83031f2a} <Debug> MemoryTracker: Peak memory usage (for query): 0.00 B.
2021.02.02 12:55:37.967719 [ 246 ] {bd79afea-0191-46f1-aa7a-edb442177202} <Debug> executeQuery: (from [::1]:34972, using production parser) (comment: /usr/share/clickhouse-test/queries/0_stateless/01297_create_quota.sql) SELECT '-- default';
2021.02.02 12:55:37.968120 [ 247 ] {c2013de7-80dd-4e10-9d7c-79418b02c647} <Debug> MemoryTracker: Peak memory usage (for query): 0.00 B.
2021.02.02 12:55:37.969855 [ 148 ] {} <Debug> TCPHandler: Processed in 0.025452966 sec.
2021.02.02 12:55:37.980078 [ 247 ] {} <Debug> TCPHandler: Processed in 0.017733498 sec.
2021.02.02 12:55:37.981404 [ 246 ] {bd79afea-0191-46f1-aa7a-edb442177202} <Trace> ContextAccess (default): Access granted: SELECT(dummy) ON system.one
2021.02.02 12:55:37.981835 [ 148 ] {a83dba56-8986-4239-b10c-10c3129d9bd4} <Debug> executeQuery: (from [::1]:34964, using production parser) (comment: /usr/share/clickhouse-test/queries/0_stateless/01297_create_quota.sql) CREATE QUOTA q1_01297;
2021.02.02 12:55:37.982238 [ 246 ] {bd79afea-0191-46f1-aa7a-edb442177202} <Trace> InterpreterSelectQuery: FetchColumns -> Complete
2021.02.02 12:55:37.982666 [ 247 ] {942fdd6c-c930-4bac-8956-5f4a7fbcee94} <Debug> executeQuery: (from [::1]:34968, using production parser) (comment: /usr/share/clickhouse-test/queries/0_stateless/01297_create_quota.sql) SHOW CREATE QUOTA q1_01297;
2021.02.02 12:55:37.982865 [ 148 ] {a83dba56-8986-4239-b10c-10c3129d9bd4} <Trace> ContextAccess (default): Access granted: CREATE QUOTA ON *.*
2021.02.02 12:55:37.984082 [ 247 ] {942fdd6c-c930-4bac-8956-5f4a7fbcee94} <Trace> ContextAccess (default): Access granted: SHOW QUOTAS ON *.*
2021.02.02 12:55:37.999886 [ 246 ] {bd79afea-0191-46f1-aa7a-edb442177202} <Information> executeQuery: Read 1 rows, 1.00 B in 0.030080058 sec., 33 rows/sec., 33.24 B/sec.
2021.02.02 12:55:38.002799 [ 247 ] {942fdd6c-c930-4bac-8956-5f4a7fbcee94} <Debug> executeQuery: Query pipeline:
One

2021.02.02 12:55:38.003062 [ 246 ] {bd79afea-0191-46f1-aa7a-edb442177202} <Debug> MemoryTracker: Peak memory usage (for query): 0.00 B.
2021.02.02 12:55:38.003491 [ 148 ] {a83dba56-8986-4239-b10c-10c3129d9bd4} <Error> executeQuery: Code: 493, e.displayText() = DB::Exception: quota `q1_01297`: cannot insert because quota `q1_01297` already exists in local directory: Couldn't insert quota `q1_01297`. Successfully inserted: none (version 21.3.1.5885) (from [::1]:34964) (comment: /usr/share/clickhouse-test/queries/0_stateless/01297_create_quota.sql) (in query: CREATE QUOTA q1_01297;), Stack trace (when copying this message, always include the lines below):
```

**Comment by alexey-milovidov** [comment]
@JackyWoo Flaky check runs test in parallel just to ensure that we can run as many of our tests in parallel as possible.
But your test cannot be run in parallel for a reason. You need to add it here:
https://github.com/ClickHouse/ClickHouse/blob/in_memory_raft/tests/queries/skip_list.json#L318

**Comment by JackyWoo** [comment]
@alexey-milovidov need help

There are 3 CI checking failures. I tested with master compiled binary file in local which raise the same failures.  So I guess maybe the checking failures are not from my pr. 

What can I do  for the checking failures.

**Comment by JackyWoo** [comment]
@alexey-milovidov Please review the pr.

**Review by alexey-milovidov — APPROVED** [review]

**Pull request merged**
