### PR TITLE
Fix CAST Object to Object with Nullable subcolumns

### LINKED ISSUE #36558: CAST Object to Object with Nullable subcolumns doesn't work
I expect it should work:
```
:) select CAST(CAST('{"x" : 1}', 'Object(\'json\')'), 'Object(Nullable(\'json\'))')

SELECT CAST(CAST('{"x" : 1}', 'Object(\'json\')'), 'Object(Nullable(\'json\'))')

Query id: fb057b45-b72a-4d22-9b38-a3136cdf2465


0 rows in set. Elapsed: 0.002 sec.

Received exception from server (version 22.5.1):
Code: 53. DB::Exception: Received from localhost:9000. DB::Exception: Cast to Object can be performed only from flatten named Tuple, Map or String. Got: Object('json'): While processing CAST(CAST('{"x" : 1}', 'Object(\'json\')'), 'Object(Nullable(\'json\'))'). (TYPE_MISMATCH)
```

@CurtizJ what do you think?

### PR DESCRIPTION
**Pull request by awakeljw**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Allow to cast columns of type `Object(...)` to `Object(Nullable(...))`.

Closes #36558.

### CODE REVIEW

**Comment by awakeljw** [comment]
d

INSERT INTO t_object_convert SELECT 1, CAST(CAST('{"x" : 1}', 'Object(\'json\')'), 'Object(Nullable(\'json\'))');
INSERT INTO t_object_convert SELECT 2, CAST(CAST('{"y" : 2}', 'Object(\'json\')'), 'Object(Nullable(\'json\'))');

SELECT id, data, toTypeName(data) FROM t_object_convert ORDER BY id;

results is :
┌─id─┬─data──┬─toTypeName(data)──────┐
│  1 │ (1,0) │ Tuple(x Int8, y Int8) │
└────┴───────┴───────────────────────┘
┌─id─┬─data──┬─toTypeName(data)──────┐
│  2 │ (0,2) │ Tuple(x Int8, y Int8) │
└────┴───────┴───────────────────────┘

is it correct?

**Comment by awakeljw** [comment]
The test is blocked. can you let it run?@[yakov-olkhovskiy](https://github.com/yakov-olkhovskiy)

**Comment by yakov-olkhovskiy** [comment]
@awakeljw seems your test is failing:
```
2022-04-27 15:05:07 02287_type_object_convert:                                              [ FAIL ] 0.04 sec. - return code: 48
2022-04-27 15:05:07 [fa26e40990ce] 2022.04.27 15:05:07.795078 [ 116311 ] {bb9b03fb-6c2c-4fd8-95ee-e99dffcd0227} <Error> executeQuery: Code: 48. DB::Exception: To use data type Object with JSON format ClickHouse should be built with Simdjson or Rapidjson. (NOT_IMPLEMENTED) (version 22.5.1.1) (from [::1]:46678) (comment: 02287_type_object_convert.sql) (in query: CREATE TABLE t_object_convert(id UInt64, data Object(Nullable('JSON'))) Engine=Memory;), Stack trace (when copying this message, always include the lines below):
```

**Comment by awakeljw** [comment]
> @awakeljw seems your test is failing:
> 
> ```
> 2022-04-27 15:05:07 02287_type_object_convert:                                              [ FAIL ] 0.04 sec. - return code: 48
> 2022-04-27 15:05:07 [fa26e40990ce] 2022.04.27 15:05:07.795078 [ 116311 ] {bb9b03fb-6c2c-4fd8-95ee-e99dffcd0227} <Error> executeQuery: Code: 48. DB::Exception: To use data type Object with JSON format ClickHouse should be built with Simdjson or Rapidjson. (NOT_IMPLEMENTED) (version 22.5.1.1) (from [::1]:46678) (comment: 02287_type_object_convert.sql) (in query: CREATE TABLE t_object_convert(id UInt64, data Object(Nullable('JSON'))) Engine=Memory;), Stack trace (when copying this message, always include the lines below):
> ```

I have fixed it by adding no-fasttest tags in the header of test file.

**Comment by yakov-olkhovskiy** [comment]
seems fuzzer found something like:
```
CREATE TABLE t_object_convert(id UInt64, data Object('JSON')) Engine=Memory;

INSERT INTO t_object_convert SELECT 2, CAST(CAST('{"y" : 2}', 'Object(\'json\')'), 'Object(Nullable(\'json\'))');

SELECT data, toTypeName(data) FROM t_object_convert

┌─data─┬─toTypeName(data)─┐
│ (2)  │ Tuple(y Int8)    │
└──────┴──────────────────┘

SELECT data, toTypeName(data) FROM t_object_convert ORDER BY CAST('{"x" : 1}', 'Object(Nullable(\'json\'))') ASC

┌─data─┬─toTypeName(data)─┐
│ (2)  │ Tuple(y Int8)    │
└──────┴──────────────────┘

INSERT INTO t_object_convert SELECT 1, CAST('{"x" : 1}', 'Object(Nullable(\'json\'))');

SELECT data, toTypeName(data) FROM t_object_convert

┌─data─────┬─toTypeName(data)────────────────┐
│ (NULL,2) │ Tuple(x Nullable(Int8), y Int8) │
└──────────┴─────────────────────────────────┘
┌─data──┬─toTypeName(data)────────────────┐
│ (1,0) │ Tuple(x Nullable(Int8), y Int8) │
└───────┴─────────────────────────────────┘

SELECT data, toTypeName(data) FROM t_object_convert ORDER BY CAST('{"x" : 1}', 'Object(Nullable(\'json\'))') ASC

[ClickHouse-ubuntu] 2022.04.28 12:21:05.472267 [ 3999967 ] {a036468b-9554-40b3-83ba-ba377f8ea903} <Fatal> : Logical error: 'ColumnObject must be converted to ColumnTuple before use'.
```

**Comment by awakeljw** [comment]
> 
CREATE TABLE t_object_convert(id UInt64, data Object('JSON')) Engine=Memory;
INSERT INTO t_object_convert SELECT 1, CAST('{"x" : 1}', 'Object(\'json\')');
INSERT INTO t_object_convert SELECT 1, CAST('{"y" : 2}', 'Object(\'json\')');
SELECT data, toTypeName(data) FROM t_object_convert

SELECT
    data,
    toTypeName(data)
FROM t_object_convert

Query id: a9b944fa-4577-4e5c-ba72-22c09599b99b

┌─data──┬─toTypeName(data)──────┐
│ (0,2) │ Tuple(x Int8, y Int8) │
└───────┴───────────────────────┘
┌─data──┬─toTypeName(data)──────┐
│ (1,0) │ Tuple(x Int8, y Int8) │
└───────┴───────────────────────┘

2 rows in set. Elapsed: 0.002 sec.
SELECT data, toTypeName(data) FROM t_object_convert ORDER BY CAST('{"x" : 1}', 'Object(\'json\')') ASC
Received exception from server (version 22.4.1):
Code: 49. DB::Exception: Received from localhost:9000. DB::Exception: ColumnObject must be converted to ColumnTuple before use: While executing MergingSortedTransform. (LOGICAL_ERROR)

**Comment by awakeljw** [comment]
> seems fuzzer found something like:
> 
> ```
> CREATE TABLE t_object_convert(id UInt64, data Object('JSON')) Engine=Memory;
> 
> INSERT INTO t_object_convert SELECT 2, CAST(CAST('{"y" : 2}', 'Object(\'json\')'), 'Object(Nullable(\'json\'))');
> 
> SELECT data, toTypeName(data) FROM t_object_convert
> 
> ┌─data─┬─toTypeName(data)─┐
> │ (2)  │ Tuple(y Int8)    │
> └──────┴──────────────────┘
> 
> SELECT data, toTypeName(data) FROM t_object_convert ORDER BY CAST('{"x" : 1}', 'Object(Nullable(\'json\'))') ASC
> 
> ┌─data─┬─toTypeName(data)─┐
> │ (2)  │ Tuple(y Int8)    │
> └──────┴──────────────────┘
> 
> INSERT INTO t_object_convert SELECT 1, CAST('{"x" : 1}', 'Object(Nullable(\'json\'))');
> 
> SELECT data, toTypeName(data) FROM t_object_convert
> 
> ┌─data─────┬─toTypeName(data)────────────────┐
> │ (NULL,2) │ Tuple(x Nullable(Int8), y Int8) │
> └──────────┴─────────────────────────────────┘
> ┌─data──┬─toTypeName(data)────────────────┐
> │ (1,0) │ Tuple(x Nullable(Int8), y Int8) │
> └───────┴─────────────────────────────────┘
> 
> SELECT data, toTypeName(data) FROM t_object_convert ORDER BY CAST('{"x" : 1}', 'Object(Nullable(\'json\'))') ASC
> 
> [ClickHouse-ubuntu] 2022.04.28 12:21:05.472267 [ 3999967 ] {a036468b-9554-40b3-83ba-ba377f8ea903} <Fatal> : Logical error: 'ColumnObject must be converted to ColumnTuple before use'.
> ```
```

CREATE TABLE t_object_convert(id UInt64, data Object('JSON')) Engine=Memory;
INSERT INTO t_object_convert SELECT 1, CAST('{"x" : 1}', 'Object(\'json\')');
INSERT INTO t_object_convert SELECT 1, CAST('{"y" : 2}', 'Object(\'json\')');
SELECT data, toTypeName(data) FROM t_object_convert

SELECT
    data,
    toTypeName(data)
FROM t_object_convert

Query id: a9b944fa-4577-4e5c-ba72-22c09599b99b

┌─data──┬─toTypeName(data)──────┐
│ (0,2) │ Tuple(x Int8, y Int8) │
└───────┴───────────────────────┘
┌─data──┬─toTypeName(data)──────┐
│ (1,0) │ Tuple(x Int8, y Int8) │
└───────┴───────────────────────┘

2 rows in set. Elapsed: 0.002 sec.
SELECT data, toTypeName(data) FROM t_object_convert ORDER BY CAST('{"x" : 1}', 'Object(\'json\')') ASC
Received exception from server (version 22.4.1):
Code: 49. DB::Exception: Received from localhost:9000. DB::Exception: ColumnObject must be converted to ColumnTuple before use: While executing MergingSortedTransform. (LOGICAL_ERROR)

```

**Comment by yakov-olkhovskiy** [comment]
Logical error leads to abort - not sure it's reasonable for simple select...

**Comment by awakeljw** [comment]
> Logical error leads to abort - not sure it's reasonable for simple select... however it's maybe unrelated issue for this project - I'll check tomorrow...



> Logical error leads to abort - not sure it's reasonable for simple select... however it's maybe unrelated issue for this project - I'll check tomorrow...

If it is really a problem， i can continue to fix it.

**Comment by yakov-olkhovskiy** [comment]
Logical error is definitely not correct behavior - if such order by is not allowed it should be a proper non-fatal error.

**Comment by awakeljw** [comment]
I entirely agree with you, we could try to make conversion implicitly. Maybe we can take a new issue.

**Comment by yakov-olkhovskiy** [comment]
ok, let's address it in other issue

**Review by yakov-olkhovskiy — APPROVED** [review]
LGTM
error in fuzzer for object in ORDER BY seems directly unrelated and will be addressed in other issue

**Pull request merged**
