### PR TITLE
Update Client.cpp

### PR DESCRIPTION
**Pull request by George3d6**
Made a change so that the progress meter (%) is logged even when running the query on a remote host server.

### CODE REVIEW

**Comment by robot-metrika-test** [comment]
Can one of the admins verify this patch?

**Comment by alexey-milovidov** [comment]
Sorry, I don't understand the exact meaning of this modification.
The issue is that `terminal_size.ws_col` is too low or don't detected correctly?

**Comment by George3d6** [comment]
Sorry, the message was wrong. What I meant to say is that we would like to use the client programmatically, we capture the std::cerr and insert it in another stream, so it doesn't run in a standard tty/ptty with width&height.

If we add the --progress option when running in batch mode we are able to see some stats but is missing the advancement %, is ok to drop the advancembt bar, because bound to the phisical size of thw window but the xx% indicator can be kept (and for us is the most important stats!).

Btw the ability to have an estimation of the total time is GOLD!

**Comment by alexey-milovidov** [comment]
Ok, now I understand.

But if you select from a table that engine doesn't provide estimation of total rows (for example, table of Log engine), `progress.total_rows` will be zero and percent will be displayed as either 99% or nan.

So, in case when `progress.total_rows` is zero, you should not display any percent.

**Comment by George3d6** [comment]
Sorry, I didn't realize that, currently I'm not on my computer. I will do the mod tomorrow early morning and do the pull request again.

**Comment by George3d6** [comment]
Added the check, also added a check for the elapsed time so that the "%" will still render in sync with the progress bar. Also added the "progress.rows * 2 < progress.total_rows" check, though I'm not 100% sure on what problem that solves in the original if...

**Comment by George3d6** [comment]
Any updates on this ?

**Comment by alexey-milovidov** [comment]
Will merge today.

**Comment by alexey-milovidov** [comment]
Sorry, your code is wrong.
Percent doesn't shows if it is greater than 50.

Look at
```
if (show_progress_bar
	|| (width_of_progress_bar > 0
		&& progress.total_rows
		&& elapsed_ns > 500000000
		&& progress.rows * 2 < progress.total_rows))
{
	show_progress_bar = true;
```

**Comment by George3d6** [comment]
Sorry, I had a bit of a brainfart when writing the original, I'll add a similar `show_precentage_char` bool instead of removing `progress.rows * 2 < progress.total_rows` in order for the behavior to remain the same as before my commit + % still being outputed when there is no physical terminal.

**Pull request merged**
