### PR TITLE
Support non-const scale arguments in rounding functions

### LINKED ISSUE #50420: Function `round()` with non-const second arguments
```
SELECT round(materialize(1 / 3), materialize(3))

Query id: 8f1ccbc9-d25d-42ed-93f2-16ad73c0e35f


0 rows in set. Elapsed: 0.762 sec. 

Received exception:
Code: 44. DB::Exception: Argument at index 1 for function round must be constant. (ILLEGAL_COLUMN)
```

### PR DESCRIPTION
**Pull request by mgorshkov**
Closes #50420 
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
The second argument (scale) of functions `round()`, `roundBankers()`, `floor()`, `ceil()` and `trunc()` can now be non-const.

### CODE REVIEW

**Comment by mgorshkov** [comment]
@rschu1ze Could you please assign `can be tested` label to this PR?

**Comment by rschu1ze** [comment]
Done, thanks!

**Comment by robot-ch-test-poll** [comment]
*This is an automated comment for commit 830acd3a8927e49c94a4d82817a1364c4dfd0604 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/64798/830acd3a8927e49c94a4d82817a1364c4dfd0604/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>A Sync</td><td>If it fails, ask a maintainer for help</td><td>⏳ pending</td></tr>
<tbody>
</table>
<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

**Comment by mgorshkov** [comment]
@rschu1ze Can you please review this PR? The errors in the pipeline run are unrelated, as far as I can see.

**Comment by rschu1ze** [comment]
Thanks for the PR, sure, I'll check.

**Comment by rschu1ze** [comment]
It took me a while to understand what changed and why but the PR looks good to me:

Two remarks:
1. While reviewing, I made some adjustments to the docs (it was messy before your PR already), to the code (to make naming etc. consistent with the rest of the codebase), and minor changes to the test. I then found out I get a 403 permission error while pushing to the arenadata ClickHouse fork. It would be very nice if you could pick the head commit ("Some fixups") of [this branch](https://github.com/rschu1ze/ClickHouse/commits/rs-adqm-1892/) into your PR.

2. I thought that this code is too complex:

```cpp
else if (const auto scale_typed = checkAndGetColumn<ColVecScale>(scale_col))
            {
                const auto & in = col.getData();
                const auto & scale_data = scale_typed->getData();
                const size_t count = in.size();

                const T * end_in = in.data() + count;
                const T * __restrict p_in = in.data();
                const ScaleType * __restrict p_scale = scale_data.data();
                T * __restrict p_out = vec_res.data();

                while (p_in < end_in)
                {
                    [...[
                    if (raw_scale == 0)
                    {
                        size_t scale = 1;
                        FunctionRoundingImpl<ScaleMode::Zero>::applyOne(p_in, scale, p_out);
                    }
                   [...]
```

We should ideally not mess with pointers here but change `applyOne` to accept single input values / scale values (no pointers) per call. `applyOne` may then internally take the address of its inputs, i.e. compute its current parameters `in`/`out`.

**Review by rschu1ze — APPROVED** [review]

**Comment by rschu1ze** [comment]
The [AST Fuzzer](https://s3.amazonaws.com/clickhouse-test-reports/64798/7ce67265c70075009617c1b43700d351bf43a9ad/ast_fuzzer__debug_.html) ran into a crash caused by this PR:

Original query:

```sql
SELECT toFloat32((number - 10) / 10) AS x, round(x), roundBankers(x), floor(x), ceil(x, toUInt256(1)), trunc(x, materialize(1)) FROM system.numbers LIMIT 20
```

Simplified query:

```sql
SELECT materialize(10.1) AS x, ceil(x, toUInt256(123))
```

```
2024.06.06 09:07:52.913979 [ 3210412 ] {c944d07e-a202-4cba-aca3-45c3d197f5cd} <Trace> Planner: Query from stage FetchColumns to stage Complete
2024.06.06 09:07:52.915449 [ 3211065 ] {c944d07e-a202-4cba-aca3-45c3d197f5cd} <Fatal> : Logical error: 'Invalid Field get from type UInt256 to type Int64'.
2024.06.06 09:07:52.915756 [ 3210411 ] {} <Trace> BaseDaemon: Received signal 6
2024.06.06 09:07:52.915942 [ 3211087 ] {} <Fatal> BaseDaemon: ########## Short fault info ############
2024.06.06 09:07:52.915989 [ 3211087 ] {} <Fatal> BaseDaemon: (version 24.6.1.1, build id: D12787E029E8F5F9AAC04974DA768E551875745C, git hash: 7ce67265c70075009617c1b43700d351bf43a9ad) (from thread 3211065) Received signal 6
2024.06.06 09:07:52.916015 [ 3211087 ] {} <Fatal> BaseDaemon: Signal description: Aborted
2024.06.06 09:07:52.916032 [ 3211087 ] {} <Fatal> BaseDaemon:
2024.06.06 09:07:52.916061 [ 3211087 ] {} <Fatal> BaseDaemon: Stack trace: 0x000000000c79d74a 0x000000000c79d640 0x000000000cb85df1 0x00007e39f2045320 0x00007e39f209eb1d 0x00007e39f204526e 0x00007e39f20288ff 0x000000000c74a522 0x000000000c74a695 0x000000000c74ac40 0x0000000004e6d06a 0x0000000004e6a869 0x0000000004e8202d 0x0000000004e809c7 0x0000000004f10dfd 0x00000000054d6491 0x0000000005773594 0x0000000005770b6e 0x00000000054cf160 0x00000000056d4cc7 0x00000000054cd2b2
x00000000056d2a91 0x0000000005c8af62 0x0000000011fca1fa 0x0000000011fcb2de 0x0000000011fcc255 0x00000000135e4bb7 0x00000000135e3f47 0x00000000162f4208 0x000000000f2e4862 0x000000001612e492 0x000000001616dc03 0x000000001616d940 0x000000001614f861 0x000000001614fbeb 0x000000001614e895 0x000000001614dd82 0x0000000016174350 0x00000000161741bf 0x0000000016174135 0x0000000016174119 0x000000001617407d 0x0000000016173fd5 0x0000000016173e95 0x0000000016173e75
2024.06.06 09:07:52.916100 [ 3211087 ] {} <Fatal> BaseDaemon: ########################################
2024.06.06 09:07:52.916192 [ 3211087 ] {} <Fatal> BaseDaemon: (version 24.6.1.1, build id: D12787E029E8F5F9AAC04974DA768E551875745C, git hash: 7ce67265c70075009617c1b43700d351bf43a9ad) (from thread 3211065) (query_id: c944d07e-a202-4cba-aca3-45c3d197f5cd) (query: SELECT materialize(10.1) AS x, ceil(x, toUInt256(123))) Received signal Aborted (6)
2024.06.06 09:07:52.916252 [ 3211087 ] {} <Fatal> BaseDaemon:
2024.06.06 09:07:52.916297 [ 3211087 ] {} <Fatal> BaseDaemon: Stack trace: 0x000000000c79d74a 0x000000000c79d640 0x000000000cb85df1 0x00007e39f2045320 0x00007e39f209eb1d 0x00007e39f204526e 0x00007e39f20288ff 0x000000000c74a522 0x000000000c74a695 0x000000000c74ac40 0x0000000004e6d06a 0x0000000004e6a869 0x0000000004e8202d 0x0000000004e809c7 0x0000000004f10dfd 0x00000000054d6491 0x0000000005773594 0x0000000005770b6e 0x00000000054cf160 0x00000000056d4cc7 0x00000000054cd2b2
x00000000056d2a91 0x0000000005c8af62 0x0000000011fca1fa 0x0000000011fcb2de 0x0000000011fcc255 0x00000000135e4bb7 0x00000000135e3f47 0x00000000162f4208 0x000000000f2e4862 0x000000001612e492 0x000000001616dc03 0x000000001616d940 0x000000001614f861 0x000000001614fbeb 0x000000001614e895 0x000000001614dd82 0x0000000016174350 0x00000000161741bf 0x0000000016174135 0x0000000016174119 0x000000001617407d 0x0000000016173fd5 0x0000000016173e95 0x0000000016173e75
2024.06.06 09:07:52.930147 [ 3211087 ] {} <Fatal> BaseDaemon: 0. /data/ch5/src/Common/StackTrace.cpp:349: StackTrace::tryCapture() @ 0x000000000c79d74a
2024.06.06 09:07:52.942284 [ 3211087 ] {} <Fatal> BaseDaemon: 1. /data/ch5/src/Common/StackTrace.cpp:323: StackTrace::StackTrace(ucontext_t const&) @ 0x000000000c79d640
2024.06.06 09:07:52.965348 [ 3211087 ] {} <Fatal> BaseDaemon: 2. /data/ch5/src/Daemon/BaseDaemon.cpp:157: signalHandler(int, siginfo_t*, void*) @ 0x000000000cb85df1
2024.06.06 09:07:52.965400 [ 3211087 ] {} <Fatal> BaseDaemon: 3. ? @ 0x00007e39f2045320
2024.06.06 09:07:52.965449 [ 3211087 ] {} <Fatal> BaseDaemon: 4. ? @ 0x00007e39f209eb1d
2024.06.06 09:07:52.965496 [ 3211087 ] {} <Fatal> BaseDaemon: 5. ? @ 0x00007e39f204526e
2024.06.06 09:07:52.965541 [ 3211087 ] {} <Fatal> BaseDaemon: 6. ? @ 0x00007e39f20288ff
2024.06.06 09:07:52.980329 [ 3211087 ] {} <Fatal> BaseDaemon: 7. /data/ch5/src/Common/Exception.cpp:0: DB::abortOnFailedAssertion(String const&) @ 0x000000000c74a522
2024.06.06 09:07:52.994692 [ 3211087 ] {} <Fatal> BaseDaemon: 8. /data/ch5/src/Common/Exception.cpp:65: DB::handle_error_code(String const&, int, bool, std::vector<void*, std::allocator<void*>> const&) @ 0x000000000c74a695
2024.06.06 09:07:53.000151 [ 3211045 ] {} <Trace> AsynchronousMetrics: MemoryTracking: was 254.75 MiB, peak 254.75 MiB, free memory in arenas 0.00 B, will set to 331.25 MiB (RSS), difference: 76.49 MiB
2024.06.06 09:07:53.007402 [ 3211087 ] {} <Fatal> BaseDaemon: 9. /data/ch5/src/Common/Exception.cpp:105: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000c74ac40
2024.06.06 09:07:53.017819 [ 3211087 ] {} <Fatal> BaseDaemon: 10. /data/ch5/src/Common/Exception.h:95: DB::Exception::Exception(String&&, int, bool) @ 0x0000000004e6d06a
2024.06.06 09:07:53.027930 [ 3211087 ] {} <Fatal> BaseDaemon: 11. /data/ch5/src/Common/Exception.h:68: DB::Exception::Exception(PreformattedMessage&&, int) @ 0x0000000004e6a869
2024.06.06 09:07:53.039250 [ 3211087 ] {} <Fatal> BaseDaemon: 12. /data/ch5/src/Common/Exception.h:113: DB::Exception::Exception<DB::Field::Types::Which&, DB::Field::Types::Which const&>(int, FormatStringHelperImpl<std::type_identity<DB::Field::Types::Which&>::type, std::type_identity<DB::Field::Types::Which const&>::type>, DB::Field::Types::Which&, DB::Field::Types::Which const&) @ 0x0000000004e8202d
2024.06.06 09:07:53.049592 [ 3211087 ] {} <Fatal> BaseDaemon: 13. /data/ch5/src/Core/Field.h:886: DB::NearestFieldTypeImpl<std::decay<long>::type, void>::Type& DB::Field::get<long>() @ 0x0000000004e809c7
2024.06.06 09:07:53.076079 [ 3211087 ] {} <Fatal> BaseDaemon: 14. /data/ch5/src/Core/Field.h:467: auto const& DB::Field::get<long>() const @ 0x0000000004f10dfd
2024.06.06 09:07:53.155952 [ 3211087 ] {} <Fatal> BaseDaemon: 15. /data/ch5/src/Functions/FunctionsRound.h:504: DB::getScaleArg(DB::ColumnConst const*) @ 0x00000000054d6491
2024.06.06 09:07:53.238285 [ 3211087 ] {} <Fatal> BaseDaemon: 16. /data/ch5/src/Functions/FunctionsRound.h:532: COW<DB::IColumn>::immutable_ptr<DB::IColumn> DB::Dispatcher<double, (DB::RoundingMode)10, (DB::TieBreakingMode)0>::apply<wide::integer<256ul, unsigned int>>(DB::IColumn const*, DB::IColumn const*) @ 0x0000000005773594
2024.06.06 09:07:53.320245 [ 3211087 ] {} <Fatal> BaseDaemon: 17. /data/ch5/src/Functions/FunctionsRound.h:680: bool bool DB::FunctionRounding<DB::NameCeil, (DB::RoundingMode)10, (DB::TieBreakingMode)0>::executeImpl(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long) const::'lambda'(auto const&)::operator()<DB::TypePair<void, double>>(auto const&) const::'lambda'(auto const
)::operator()<DB::TypePair<void, wide::integer<256ul, unsigned int>>>(auto const&) const @ 0x0000000005770b6e
2024.06.06 09:07:53.407285 [ 3211087 ] {} <Fatal> BaseDaemon: 18. /data/ch5/src/Core/callOnTypeIndex.h:31: bool DB::callOnBasicType<void, true, false, false, false, bool DB::FunctionRounding<DB::NameCeil, (DB::RoundingMode)10, (DB::TieBreakingMode)0>::executeImpl(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long) const::'lambda'(auto const&)::operator()<DB::TypePair<void,
ouble>>(auto const&) const::'lambda'(auto const&)&>(DB::TypeIndex, bool DB::FunctionRounding<DB::NameCeil, (DB::RoundingMode)10, (DB::TieBreakingMode)0>::executeImpl(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long) const::'lambda'(auto const&)::operator()<DB::TypePair<void, double>>(auto const&) const::'lambda'(auto const&)&) @ 0x00000000054cf160
2024.06.06 09:07:53.480124 [ 3211087 ] {} <Fatal> BaseDaemon: 19. /data/ch5/src/Functions/FunctionsRound.h:685: bool DB::FunctionRounding<DB::NameCeil, (DB::RoundingMode)10, (DB::TieBreakingMode)0>::executeImpl(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long) const::'lambda'(auto const&)::operator()<DB::TypePair<void, double>>(auto const&) const @ 0x00000000056d4cc7
2024.06.06 09:07:53.565288 [ 3211087 ] {} <Fatal> BaseDaemon: 20. /data/ch5/src/Core/callOnTypeIndex.h:66: bool DB::callOnBasicType<void, true, true, true, false, DB::FunctionRounding<DB::NameCeil, (DB::RoundingMode)10, (DB::TieBreakingMode)0>::executeImpl(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long) const::'lambda'(auto const&)&>(DB::TypeIndex, DB::FunctionRounding<
B::NameCeil, (DB::RoundingMode)10, (DB::TieBreakingMode)0>::executeImpl(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long) const::'lambda'(auto const&)&) @ 0x00000000054cd2b2
2024.06.06 09:07:53.637755 [ 3211087 ] {} <Fatal> BaseDaemon: 21. /data/ch5/src/Functions/FunctionsRound.h:703: DB::FunctionRounding<DB::NameCeil, (DB::RoundingMode)10, (DB::TieBreakingMode)0>::executeImpl(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long) const @ 0x00000000056d2a91
```

The scale argument is of type UInt256 which does not support via `.get<Int64>` in `getScaleArg`. We should restrict scale arguments to types `(U)Int8` - `(U)Int64`. I'd have three requests:
- please adjust that in `getReturnTypeImpl`
- while at it, we could also use `FunctionArgumentDescriptors` / `validateFunctionArgumentTypes` (from "Functions/FunctionHelpers.h", see "Functions/makeDate.cpp" for a usage example) in `getReturnTypeImpl`.
- FInally, kindly add a test case for the crashing query to the new SQL test.

Besides that, the PR looked good.

Thanks!

**Comment by rschu1ze** [comment]
@mgorshkov Kindly merge from `master` again ([can't](https://github.com/ClickHouse/ClickHouse/pull/64798#issuecomment-2149575852) do that), the failure in FastTest is unrelated and has been fixed upstream, but it blocks CI to proceed.

**Comment by alexey-milovidov** [comment]
@rschu1ze sorry, this feature is not counted as done:

```
:) SELECT round(pi(), number) FROM numbers(10)

SELECT round(pi(), number)
FROM numbers(10)

Query id: 39ea0251-6b0c-49c1-8e21-5b3b9ad8f4e2


Elapsed: 0.023 sec. 

Received exception:
Code: 44. DB::Exception: Scale column must be const for const data column. (ILLEGAL_COLUMN)
```

**Comment by alexey-milovidov** [comment]
Thank you! I want to introduce this feature on the webinar - if we can submit a fix in a few hours, it will be included.

**Comment by rvasin** [comment]
Great news about webinar! Mikhail will fix it today.

**Comment by mgorshkov** [comment]
https://github.com/ClickHouse/ClickHouse/pull/65983

**Comment by mgorshkov** [comment]
@rschu1ze @alexey-milovidov Pls review the PR https://github.com/ClickHouse/ClickHouse/pull/65983

**Pull request merged**
