### PR TITLE
Fix incorrect queries in example

### PR DESCRIPTION
**Pull request by devcrafter**
### Changelog category (leave one):
- Documentation (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Setting `insert_deduplication_token`: fix incorrect queries in example

### CODE REVIEW

**Comment by tavplubix** [comment]
Hm, seems like it was supposed to work: https://github.com/ClickHouse/ClickHouse/pull/33776

**Comment by Avogar** [comment]
It doesn't work after https://github.com/ClickHouse/ClickHouse/pull/35883

**Comment by Avogar** [comment]
Actually, we can allow settings after `insert into ... values` because we can't confuse the settings with the data in this case. But I'm not sure that it's worth doing it

**Review by Avogar — APPROVED** [review]

**Comment by devcrafter** [comment]
Close #40140

**Pull request merged**
