### PR TITLE
Update Allocator.cpp

### PR DESCRIPTION
**Pull request by tigertv**
Removed several checks.

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

### CODE REVIEW

**Comment by tigertv** [comment]
Let's say, old_size is checked only once and not 3 times. I don't think the compiler will optimise it right.

**Comment by tigertv** [comment]
If it is assumed to be called not very frequently it doesn't mean you don't need the enchancement.
So If you don't need, then don't get it.

**Comment by filimonov** [comment]
@tigertv it's nice that you like to help open source project, but please stop fixing the things that are not broken :) "if it ain't broke don't fix it".

About performance improvements: the main concept behind each performance improvement is measurement, as a prove of speed up (otherwise you have a risk to slow down the code). So if you really want to try to make something faster you need to measure speed before and after. The proper way of measurement of code is benchmarks. So before your next improvement - please try to create some benchmark to prove that your changes give some advantages.

Those obvious 'optimizations' you're create don't speed up anything, because compilers also can do all that quite obvious things.

Also then you trying to "help" the compiler to make some optimization you can get to a situation then your code start being too sophisticated to compiler, and it can use bad optimization strategies because of that, and that can lead to slow down instead of speed up. So only benchmarks and proofed by measurement optimizations, please.

In projects with bigger codebase readability is very-very important to be errorproof. Making some code less readable for some theoretical and not proved speed up is mostly a very-very bad idea.

**Comment by tigertv** [comment]
@filimonov, 
OK. Ich verstehe das.

**Pull request closed without merging**
