### PR TITLE
Extended date time parsing

### PR DESCRIPTION
**Pull request by amosbird**
Accepting datetime string from 2000-1-1 1:2:3 to 2000-01-01 01:02:03.

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
I wonder, what is the main motivation for this change?

**Comment by amosbird** [comment]
The main purpose is to accept flexible datetime formats of data which I just received :-)

**Comment by alexey-milovidov** [comment]
What about performance tests?

If the performance decrease (at least 1%), it's important to choose, for what feature we will trade the performance.

For example, I am ready to trade few percent of performance to add support of parsing DateTime in full ISO 8601 format like `2017-12-28T15:01:29+00:00` and `2017-12-28T15:01:29Z`. This seems as much more relevant feature.

As next step, I consider adding switchable DateTime parsing. For example, what if you can choose (with settings) between simple and fast parsing and customizeable parsing with user-defined format? (And that user-defined format can include your case.)

**Comment by amosbird** [comment]
## Before this patch
```
QPS: 2.528, RPS: 257865127.011, MiB/s: 983.677, result RPS: 2.528, result MiB/s: 0.000.
0.000%  0.363 sec.
10.000% 0.369 sec.
20.000% 0.370 sec.
30.000% 0.372 sec.
40.000% 0.374 sec.
50.000% 0.377 sec.
60.000% 0.398 sec.
70.000% 0.414 sec.
80.000% 0.424 sec.
90.000% 0.441 sec.
95.000% 0.451 sec.
99.000% 0.467 sec.
99.900% 0.474 sec.
99.990% 0.475 sec.
```

## After this patch
```
Queries executed: 204.

QPS: 2.486, RPS: 253612596.672, MiB/s: 967.455, result RPS: 2.486, result MiB/s: 0.000.
0.000%  0.361 sec.
10.000% 0.370 sec.
20.000% 0.373 sec.
30.000% 0.375 sec.
40.000% 0.378 sec.
50.000% 0.402 sec.
60.000% 0.411 sec.
70.000% 0.424 sec.
80.000% 0.431 sec.
90.000% 0.444 sec.
95.000% 0.452 sec.
99.000% 0.457 sec.
99.900% 0.463 sec.
99.990% 0.464 sec.
```

It doesn't seem to have any performance impact.

> As next step, I consider adding switchable DateTime parsing. 

That sounds great!

**Comment by alexey-milovidov** [comment]
First step: #1884.
(Currently it doesn't change the default behaviour, only introduces a new function)

**Comment by krzyzakp** [comment]
@alexey-milovidov any chance to use function, which you introduced here? Would be super useful for us.

**Comment by alexey-milovidov** [comment]
I want to add a setting to switch between basic and "best effort" parsing in text formats.
This looks like relatively easy task but it's not in high priority right now.

**Comment by alexey-milovidov** [comment]
Now you can use setting
`SET date_time_input_format = 'best_effort'`
to enable extended DateTime parsing.

Notes:
- it doesn't affect the behaviour of type conversion functions;

**Pull request closed without merging**
