### PR TITLE
Optimize count from data in most formats, better work with _file/_path virtual columns

### LINKED ISSUE #44334: Parquet files should be able to count from metadata
**Describe the situation**
Paruqet file counting currently reads the entire file to count rows, where this can be done with the [parquet metatdata](https://parquet.apache.org/docs/file-format/metadata/)

**How to reproduce**

`ClickHouse local version 22.12.1.1752 (official build).`
```
SELECT count(*)
FROM file('*.parquet', 'Parquet')

Query id: 4dc914c1-b45a-4097-a111-c74c2efede3a

┌───count()─┐
│ 110000000 │
└───────────┘

1 row in set. Elapsed: 1.365 sec. Processed 105.69 million rows, 1.69 GB (77.43 million rows/s., 1.24 GB/s.)
```

**Expected performance**
Could be performed in ~16ms as DuckDB does:

```python
import duckdb
from time import time

con = duckdb.connect(database=':memory:')

con.execute('install parquet')
con.execute('load parquet')
print('done loading')

s = time()
con.execute('''
select count(*) from read_parquet('./*.parquet')
''')
e = time()
print(con.fetchall(), 'in', (e-s)*1000, 'ms')
```

```
@danthegoodman1 ➜ /workspaces/codespaces-blank $ python count.py 
done loading
[(110000000,)] in 16.06297492980957 ms
```

### PR DESCRIPTION
**Pull request by Avogar**
### Changelog category (leave one):
- Performance Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Optimize count from files in most input formats. Don't read actual data when only `_file/_path` columns are requested and just count the number of rows. Use filter on `_file/_path` before reading data in file/url/hdfs functions, fix issues with _path/_file virtual columns. Use cache for number of rows in files that checks file last modification time (just like schema inference cache). Optimize group by with all constant keys (optimizes queries like `select count() from file(...) group by _file/_path`).
Closes https://github.com/ClickHouse/ClickHouse/issues/44334

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by robot-ch-test-poll2** [comment]
This is an automated comment for commit 2e9b4575d94cfb67ce8fdb97ddcd43d280d744d2 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/53174/2e9b4575d94cfb67ce8fdb97ddcd43d280d744d2/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Comment by danthegoodman1** [comment]
> Use filter on _file/_path before reading data in file/url/hdfs functions

Just for clarity, and I believe this is the case, this is already implemented in the s3 table function correct?

**Comment by Avogar** [comment]
> Just for clarity, and I believe this is the case, this is already implemented in the s3 table function correct?

Yes, for s3 and azureBlobStorage it already worked. I also implemented it for file/url/hdfs

**Comment by Avogar** [comment]
I think I will split this PR into 4 separate PRs:
1) Apply filter by files in file/hdfs/url table engines + fixes around virtual coliumns + refactor to avoid code duplication
2) Faster count from all formats
3) Cache for number of rows
4) Group by constant keys optimization.

**Pull request closed without merging**
