### PR TITLE
Fix assertion in stress test

### LINKED ISSUE #62368: Logical error: `downgrade_candidates->size() > 0`
https://s3.amazonaws.com/clickhouse-test-reports/62266/578c4cfb9deeb023075695804f01ee100106115b/stress_test__debug_.html

```
[ 8759 ] {59f30a04-d6bd-4065-94b1-99fc3139d93d} <Fatal> : Logical error: \'downgrade_candidates->size() > 0\'.
 [ 76126 ] {} <Fatal> BaseDaemon: ########## Short fault info ############
 [ 76126 ] {} <Fatal> BaseDaemon: (version 24.4.1.434, build id: 54B12A70899A82B3BCF57E85DF8B099EAF260E26, git hash: da143359b4cba640330cd5df7eb71a7c97ad9d36) (from thread 8759) Received signal 6
 [ 76126 ] {} <Fatal> BaseDaemon: Signal description: Aborted
 [ 76126 ] {} <Fatal> BaseDaemon: 
 [ 76126 ] {} <Fatal> BaseDaemon: Stack trace: 0x00007f3f4d8989fc 0x00007f3f4d844476 0x00007f3f4d82a7f3 0x000000001303b0b4 0x000000001ba1f2da 0x000000001ba21035 0x000000001ba21c8e 0x000000001b9c8e17 0x00000000190a4c73 0x00000000190a48f9 0x000000000aeef02a 0x00000000190952da 0x000000001909521b 0x0000
 [ 76126 ] {} <Fatal> BaseDaemon: ########################################
 [ 76126 ] {} <Fatal> BaseDaemon: (version 24.4.1.434, build id: 54B12A70899A82B3BCF57E85DF8B099EAF260E26, git hash: da143359b4cba640330cd5df7eb71a7c97ad9d36) (from thread 8759) (query_id: 59f30a04-d6bd-4065-94b1-99fc3139d93d) (query: INSERT INTO hits_none SELECT Title FROM test.hits;) Received sign
 [ 76126 ] {} <Fatal> BaseDaemon: 
 [ 76126 ] {} <Fatal> BaseDaemon: Stack trace: 0x00007f3f4d8989fc 0x00007f3f4d844476 0x00007f3f4d82a7f3 0x000000001303b0b4 0x000000001ba1f2da 0x000000001ba21035 0x000000001ba21c8e 0x000000001b9c8e17 0x00000000190a4c73 0x00000000190a48f9 0x000000000aeef02a 0x00000000190952da 0x000000001909521b 0x0000
 [ 76126 ] {} <Fatal> BaseDaemon: 4. ? @ 0x00007f3f4d8989fc
 [ 76126 ] {} <Fatal> BaseDaemon: 5. ? @ 0x00007f3f4d844476
 [ 76126 ] {} <Fatal> BaseDaemon: 6. ? @ 0x00007f3f4d82a7f3
 [ 76126 ] {} <Fatal> BaseDaemon: 7. /build/src/Common/Exception.cpp:0: DB::abortOnFailedAssertion(String const&) @ 0x000000001303b0b4
 [ 76126 ] {} <Fatal> BaseDaemon: 8. /build/src/Interpreters/Cache/SLRUFileCachePriority.cpp:213: DB::SLRUFileCachePriority::collectCandidatesForEvictionInProtected(unsigned long, unsigned long, DB::FileCacheReserveStat&, DB::EvictionCandidates&, std::shared_ptr<DB::IFileCachePriority::Iterator>, St
 [ 76126 ] {} <Fatal> BaseDaemon: 9. /build/src/Interpreters/Cache/SLRUFileCachePriority.cpp:326: DB::SLRUFileCachePriority::increasePriority(DB::SLRUFileCachePriority::SLRUIterator&, DB::CachePriorityGuard::Lock const&) @ 0x000000001ba21035
 [ 76126 ] {} <Fatal> BaseDaemon: 10. /build/src/Interpreters/Cache/SLRUFileCachePriority.cpp:434: DB::SLRUFileCachePriority::SLRUIterator::increasePriority(DB::CachePriorityGuard::Lock const&) @ 0x000000001ba21c8e
 [ 76126 ] {} <Fatal> BaseDaemon: 11. /build/src/Interpreters/Cache/FileSegment.cpp:972: DB::FileSegment::increasePriority() @ 0x000000001b9c8e17
 [ 76126 ] {} <Fatal> BaseDaemon: 12. /build/src/Disks/IO/CachedOnDiskReadBufferFromFile.cpp:867: DB::CachedOnDiskReadBufferFromFile::nextImplStep() @ 0x00000000190a4c73
 [ 76126 ] {} <Fatal> BaseDaemon: 13. /build/src/Disks/IO/CachedOnDiskReadBufferFromFile.cpp:795: DB::CachedOnDiskReadBufferFromFile::nextImpl() @ 0x00000000190a48f9
 [ 76126 ] {} <Fatal> BaseDaemon: 14. /build/src/IO/ReadBuffer.h:70: DB::ReadBuffer::next() @ 0x000000000aeef02a
 [ 76126 ] {} <Fatal> BaseDaemon: 15. /build/src/Disks/IO/ReadBufferFromRemoteFSGather.cpp:209: DB::ReadBufferFromRemoteFSGather::readImpl() @ 0x00000000190952da
 [ 76126 ] {} <Fatal> BaseDaemon: 16. /build/src/Disks/IO/ReadBufferFromRemoteFSGather.cpp:181: DB::ReadBufferFromRemoteFSGather::nextImpl() @ 0x000000001909521b
 [ 76126 ] {} <Fatal> BaseDaemon: 17. /build/src/IO/ReadBuffer.h:70: DB::ReadBuffer::next() @ 0x000000000aeef02a
 [ 76126 ] {} <Fatal> BaseDaemon: 18. /build/src/Disks/IO/ThreadPoolRemoteFSReader.cpp:147: DB::ThreadPoolRemoteFSReader::execute(DB::IAsynchronousReader::Request, bool) @ 0x0000000018e566cf
 [ 76126 ] {} <Fatal> BaseDaemon: 19. /build/src/Disks/IO/ThreadPoolRemoteFSReader.cpp:115: DB::ThreadPoolRemoteFSReader::execute(DB::IAsynchronousReader::Request) @ 0x0000000018e56be4
 [ 76126 ] {} <Fatal> BaseDaemon: 20. /build/src/Disks/IO/AsynchronousBoundedReadBuffer.cpp:101: DB::AsynchronousBoundedReadBuffer::readSync(char*, unsigned long) @ 0x00000000190c9aa3
 [ 76126 ] {} <Fatal> BaseDaemon: 21. /build/src/Disks/IO/AsynchronousBoundedReadBuffer.cpp:218: DB::AsynchronousBoundedReadBuffer::nextImpl() @ 0x00000000190ca8af
 [ 76126 ] {} <Fatal> BaseDaemon: 22. /build/src/IO/ReadBuffer.h:70: DB::ReadBuffer::next() @ 0x000000000aeef02a
 [ 76126 ] {} <Fatal> BaseDaemon: 23.0. inlined from /build/src/IO/ReadBuffer.h:106: DB::ReadBuffer::eof()
 [ 76126 ] {} <Fatal> BaseDaemon: 23. /build/src/Compression/CompressedReadBufferBase.cpp:163: DB::CompressedReadBufferBase::readCompressedData(unsigned long&, unsigned long&, bool) @ 0x0000000019b30632
 [ 76126 ] {} <Fatal> BaseDaemon: 24. /build/src/Compression/CompressedReadBufferFromFile.cpp:22: DB::CompressedReadBufferFromFile::nextImpl() @ 0x0000000019b32851
 [ 76126 ] {} <Fatal> BaseDaemon: 25. /build/src/IO/ReadBuffer.h:70: DB::ReadBuffer::next() @ 0x000000000aeef02a
 [ 76126 ] {} <Fatal> BaseDaemon: 26.0. inlined from /build/src/IO/ReadBuffer.h:106: DB::ReadBuffer::eof()
 [ 76126 ] {} <Fatal> BaseDaemon: 26. /build/src/DataTypes/Serializations/SerializationString.cpp:160: void DB::deserializeBinarySSE2<4>(DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 63ul, 64ul>&, DB::PODArray<unsigned long, 4096ul, Allocator<false, false>, 63ul, 64ul>&, DB::ReadBuffer&, un
 [ 76126 ] {} <Fatal> BaseDaemon: 27. /build/src/DataTypes/Serializations/SerializationString.cpp:253: DB::SerializationString::deserializeBinaryBulk(DB::IColumn&, DB::ReadBuffer&, unsigned long, double) const @ 0x0000000019daaac2
 [ 76126 ] {} <Fatal> BaseDaemon: 28. /build/src/DataTypes/Serializations/ISerialization.cpp:146: DB::ISerialization::deserializeBinaryBulkWithMultipleStreams(COW<DB::IColumn>::immutable_ptr<DB::IColumn>&, unsigned long, DB::ISerialization::DeserializeBinaryBulkSettings&, std::shared_ptr<DB::ISerial
 [ 76126 ] {} <Fatal> BaseDaemon: 29. /build/src/Storages/MergeTree/MergeTreeReaderWide.cpp:379: DB::MergeTreeReaderWide::readData(DB::NameAndTypePair const&, std::shared_ptr<DB::ISerialization const> const&, COW<DB::IColumn>::immutable_ptr<DB::IColumn>&, unsigned long, bool, unsigned long, unsigned
 [ 76126 ] {} <Fatal> BaseDaemon: 30. /build/src/Storages/MergeTree/MergeTreeReaderWide.cpp:152: DB::MergeTreeReaderWide::readRows(unsigned long, unsigned long, bool, unsigned long, std::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn>>
 [ 76126 ] {} <Fatal> BaseDaemon: 31. /build/src/Storages/MergeTree/MergeTreeRangeReader.cpp:110: DB::MergeTreeRangeReader::DelayedStream::readRows(std::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn>>>&, unsigned long) @ 0x000000001cb
 [ 76126 ] {} <Fatal> BaseDaemon: 32. /build/src/Storages/MergeTree/MergeTreeRangeReader.cpp:184: DB::MergeTreeRangeReader::DelayedStream::finalize(std::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn>>>&) @ 0x000000001cb61c44
 [ 76126 ] {} <Fatal> BaseDaemon: 33. /build/src/Storages/MergeTree/MergeTreeRangeReader.cpp:296: DB::MergeTreeRangeReader::Stream::finalize(std::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn>>>&) @ 0x000000001cb62565
 [ 76126 ] {} <Fatal> BaseDaemon: 34. /build/src/Storages/MergeTree/MergeTreeRangeReader.cpp:1143: DB::MergeTreeRangeReader::startReadingChain(unsigned long, DB::MarkRanges&) @ 0x000000001cb6ce71
 [ 76126 ] {} <Fatal> BaseDaemon: 35. /build/src/Storages/MergeTree/MergeTreeRangeReader.cpp:1032: DB::MergeTreeRangeReader::read(unsigned long, DB::MarkRanges&) @ 0x000000001cb6b386
 [ 76126 ] {} <Fatal> BaseDaemon: 36. /build/src/Storages/MergeTree/MergeTreeReadTask.cpp:164: DB::MergeTreeReadTask::read(DB::MergeTreeReadTask::BlockSizeParams const&) @ 0x000000001cb9bd69
 [ 76126 ] {} <Fatal> BaseDaemon: 37. /build/src/Storages/MergeTree/MergeTreeSelectAlgorithms.h:38: DB::MergeTreeThreadSelectAlgorithm::readFromTask(DB::MergeTreeReadTask&, DB::MergeTreeReadTask::BlockSizeParams const&) @ 0x000000001da5a26c
 [ 76126 ] {} <Fatal> BaseDaemon: 38. /build/src/Storages/MergeTree/MergeTreeSelectProcessor.cpp:139: DB::MergeTreeSelectProcessor::read() @ 0x000000001cb96023
 [ 76126 ] {} <Fatal> BaseDaemon: 39. /build/src/Storages/MergeTree/MergeTreeSource.cpp:226: DB::MergeTreeSource::tryGenerate() @ 0x000000001daaf256
 [ 76126 ] {} <Fatal> BaseDaemon: 40. /build/src/Processors/ISource.cpp:108: DB::ISource::work() @ 0x000000001d1e0956
 [ 76126 ] {} <Fatal> BaseDaemon: 41. /build/src/Processors/Executors/ExecutionThreadContext.cpp:47: DB::executeJob(DB::ExecutingGraph::Node*, DB::ReadProgressCallback*) @ 0x000000001d21c823
 [ 76126 ] {} <Fatal> BaseDaemon: 42. /build/src/Processors/Executors/ExecutionThreadContext.cpp:95: DB::ExecutionThreadContext::executeTask() @ 0x000000001d21c560
 [ 76126 ] {} <Fatal> BaseDaemon: 43. /build/src/Processors/Executors/PipelineExecutor.cpp:273: DB::PipelineExecutor::executeStepImpl(unsigned long, std::atomic<bool>*) @ 0x000000001d1feb61
 [ 76126 ] {} <Fatal> BaseDaemon: 44. /build/src/Processors/Executors/PipelineExecutor.cpp:239: DB::PipelineExecutor::executeSingleThread(unsigned long) @ 0x000000001d1feef7
 [ 76126 ] {} <Fatal> BaseDaemon: Integrity check of the executable skipped because the reference checksum could not be read.
 [ 8759 ] {59f30a04-d6bd-4065-94b1-99fc3139d93d} <Fatal> : Logical error: \'downgrade_candidates->size() > 0\'.
```

### PR DESCRIPTION
**Pull request by kssenii**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Closes https://github.com/ClickHouse/ClickHouse/issues/62368.

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

---
### Modify your CI run:
**NOTE:** If your merge the PR with modified CI you **MUST KNOW** what you are doing
**NOTE:** Checked options will be applied if set before CI RunConfig/PrepareRunConfig step

#### Include tests (required builds will be added automatically):
- [ ]  Fast test
- [ ]  Integration Tests
- [ ]  Stateless tests
- [ ]  Stateful tests
- [ ]  Unit tests
- [ ]  Performance tests
- [ ]  All with ASAN
- [ ]  All with TSAN
- [ ]  All with Analyzer
- [ ]  Add your option here

#### Exclude tests:
- [ ]  Fast test
- [x]  Integration Tests
- [ ]  Stateless tests
- [ ]  Stateful tests
- [x]  Performance tests
- [ ]  All with ASAN
- [ ]  All with TSAN
- [ ]  All with MSAN
- [ ]  All with UBSAN
- [ ]  All with Coverage
- [ ]  All with Aarch64
- [ ]  Add your option here

#### Extra options:
- [ ]  do not test (only style check)
- [ ]  disable merge-commit (no merge from master before tests)
- [ ]  disable CI cache (job reuse)

#### Only specified batches in multi-batch jobs:
- [ ]  1
- [ ]  2
- [ ]  3
- [ ]  4

### CODE REVIEW

**Comment by robot-ch-test-poll1** [comment]
*This is an automated comment for commit 0ef2153d55c2477a33c40301c74e0682eba63d1a with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/62551/0ef2153d55c2477a33c40301c74e0682eba63d1a/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

**Review by alesapin — APPROVED** [review]

**Comment by alesapin** [comment]
Looks like it didn't help:https://s3.amazonaws.com/clickhouse-test-reports/62551/0ef2153d55c2477a33c40301c74e0682eba63d1a/stress_test__tsan_.html
```
 [ 7342 ] {d04b14a3-6093-44fc-a908-80cdeaa510c3} <Fatal> : Logical error: \'Cannot modify size limits to 15728640 in size and 3000000 in elements: not enough space freed. Current size: 31455976/31457280, elements: 30/3000000\'.
 [ 3189 ] {} <Fatal> Application: Child process was terminated by signal 6.
 [ 7342 ] {d04b14a3-6093-44fc-a908-80cdeaa510c3} <Fatal> : Logical error: \'Cannot modify size limits to 15728640 in size and 3000000 in elements: not enough space freed. Current size: 31455976/31457280, elements: 30/3000000\'.
 [ 3189 ] {} <Fatal> Application: Child process was terminated by signal 6.
```

**Comment by kssenii** [comment]
> Looks like it didn't help

It is a different assertion, fix is in https://github.com/ClickHouse/ClickHouse/pull/62555.

**Comment by kssenii** [comment]
> Stateful tests (asan) — fail: 1

00060_move_to_prewhere_and_sets

> Stateless tests (release, old analyzer, s3, DatabaseReplicated) [4/4] — fail: 1,

03093_bug37909_query_does_not_finish

> Stress test (tsan) — Found signal in gdb.log 

https://github.com/ClickHouse/ClickHouse/pull/62555

**Pull request merged**
