### PR TITLE
Fix several issues regarding PostgreSQL `array_ndims` usage.

### PR DESCRIPTION
**Pull request by ryanmjacobs**
### Changelog category:
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry:
Fix several issues regarding PostgreSQL `array_ndims` usage.

---

All of these modifications are related to the `array_ndims` call for detecting the array type + dimensions for PostgreSQL tables. We personally ran into three of these issues when trying to SELECT from our PostgreSQL view.

Failure examples:
```SQL
-- PostgreSQL

-- 1. Unquoted column identifier bug
CREATE VIEW case1 AS SELECT '{hello}'::TEXT[] as "Column With Spaces and Mixed Case";

-- 2. Cannot infer array dimensions because table is empty.
CREATE TABLE case2 (x TEXT[]);

-- 3. Cannot infer array dimensions because first row has NULL value for array.
-- (ClickHouse does not support Nullable(Array), so this PR just adds a better error message.)
CREATE TABLE case3 (x TEXT[]);
INSERT INTO case3 VALUES (NULL);
INSERT INTO case3 VALUES ('{ok}');

-- 4. Cannot infer array dimensions because first row has empty array (i.e. no dimension).
CREATE TABLE case4 (x TEXT[]);
INSERT INTO case4 VALUES ('{}');
```

## Modifications

1. **Properly quote column identifiers**.
The query to `array_ndims` used unquoted column identifiers, which breaks if the identifier contains mixed-case, spaces, etc. (The table name was already properly quoted and did not need to be fixed.)

2. **Handle empty tables that have array columns.**
  * Added the helper method `isTableEmpty` to quickly detect if a table is empty.
  * <strike>If the table is empty --> assume that array dimension = 1.
  * NOTE: I am not confident that this is the correct solution. It works for our team, because we don't ever anticipate having multi-dimension arrays. And if we do, we will ensure that the table is always populated with at least one row. I feel like most users are the same, but I am not sure if the database should be making these blind assumptions by default (even if it is 99% the case).</strike>
  * Throw a useful error message.

3. **Throw a more user friendly error when column value = `NULL` when calling `array_dims(column)`**
  Per the documentation, ClickHouse does not support `Nullable(Array(...))` values.
  If we encounter this in our code, we should throw an error warning the user.
  It took a while to decipher the original error:
```
DB::Exception: pqxx::conversion_error: Attempt to convert null to i.. Stack trace:
```
  I wanted a safer check, but I think that would require verifying a `NOT NULL` constraint OR
  running a full table-scan.

Our final solution was to add a `NOT NULL` constraint on our array column and replace any `NULL` arrays with the empty array `{}`. If the error was more clear, we would have figured it out sooner.

4. **Handle column value being the empty array `{}`**
In PostgreSQL, `array_ndims('{}'::TEXT[])` returns `NULL`, so this error occurs again (like in case 2):
```
DB::Exception: pqxx::conversion_error: Attempt to convert null to i.. Stack trace:
```
<strike>The solution is to make another assumption. Assume that array dimension = 1.
This solves our use cases. `COALESCE` is used in the code so that an empty array returns dimension = 1 instead of `NULL`; then `.as<int>()` works as expected instead of crashing.</strike>
Throw a useful error message.

---

We were affected by case 1, 3, and 4. We didn't encounter 2, but this PR handles it.

Related issues:
* https://github.com/ClickHouse/ClickHouse/issues/36772
* https://github.com/ClickHouse/ClickHouse/issues/43186
* https://github.com/ClickHouse/ClickHouse/issues/55464

---

We cherry-picked this commit onto our 23.10 database on Debian 12 and plan to use it in production.

### CODE REVIEW

**Comment by robot-clickhouse-ci-2** [comment]
*This is an automated comment for commit a90458eb65f3743f262df1241915d3046b163a26 with description of existing statuses. It's updated for the latest CI running*

[❌ Click here](https://s3.amazonaws.com/clickhouse-test-reports/57436/a90458eb65f3743f262df1241915d3046b163a26/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td><a href="https://github.com/ClickHouse/ClickHouse/actions/runs/7065290114">✅ success</a></td></tr>
<tbody>
</table>
</details>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/57436/a90458eb65f3743f262df1241915d3046b163a26/ci_running.html">❌ failure</a></td></tr>
<tbody>
</table>

**Comment by jsc0218** [comment]
Thanks for the detailed explanation. But IMHO, I feel "If the table is empty --> assume that array dimension = 1." is a strong assumption, personally would prefer other approch.

**Comment by ryanmjacobs** [comment]
@jsc0218 I agree with you 100%. I just needed something quick for our team to move forward.

Maybe the correct solution is a `SETTINGS` flag or something? I don't really know the ClickHouse codebase, but it would be nice if:

1. The errors thrown made sense.
2. The errors specified a hint for what flag to set to enable this "assumption" OR manually specify the array dimension for a column name.

It took me a while to track down the root cause, since we were hitting so many different issues.

---

I can split out issues 1 and 3, because I think those are separate bugs. Let me know.

**Comment by jsc0218** [comment]
> @jsc0218 I agree with you 100%. I just needed something quick for our team to move forward.
> 
> Maybe the correct solution is a `SETTINGS` flag or something? I don't really know the ClickHouse codebase, but it would be nice if:
> 
> 1. The errors thrown made sense.
> 2. The errors specified a hint for what flag to set to enable this "assumption" OR manually specify the array dimension for a column name.
> 
> It took me a while to track down the root cause, since we were hitting so many different issues.
> 
> I can split out issues 1 and 3 (described in the original post), because I think those are separate bugs. Let me know.

You can split out the for sure thing, and then we test and merge them. For the case of undetectable dimension, I would suggest to throw an error, because it is really from postgres that does support this special case.

**Comment by jsc0218** [comment]
@ryanmjacobs would you mind resolve the conflict since others touch the same line but giving a temporary solution. It should be easy to reslove.

**Comment by ryanmjacobs** [comment]
@jsc0218 How does it look to you now? I'm pretty happy with the current error handling in the PR. I ripped out all of the assumptions for dimensions=1 last week.

I'm not sure what needs to be fixed in the CI scripts -- I added some tests that should break `master` -- as recommended by the docs.

**Comment by ryanmjacobs** [comment]
@jsc0218 Looks like an unrelated test was failing?


https://s3.amazonaws.com/clickhouse-test-reports/57436/ca790b6eecade9f23a7cbbfaf755332182e263ce/ci_running.html

**Integration tests (release) [4/4]**
https://s3.amazonaws.com/clickhouse-test-reports/57436/ca790b6eecade9f23a7cbbfaf755332182e263ce/integration_tests__release__[4_4].html

```
=========================== short test summary info ============================
FAILED test_replicated_merge_tree_s3_zero_copy/test.py::test_drop_table - Exc...
```

**Comment by jsc0218** [comment]
thanks, merged.

**Pull request merged**
