### PR TITLE
Add mutation command `APPLY DELETED MASK`

### PR DESCRIPTION
**Pull request by CurtizJ**
### Changelog category (leave one):
- New Feature

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Added a new mutation command `ALTER TABLE <table> APPLY DELETED MASK`, which allows to enforce applying of mask written by lightweight delete and to remove rows marked as deleted from disk.

Part of  #56728.

### CODE REVIEW

**Comment by robot-ch-test-poll4** [comment]
*This is an automated comment for commit 7fbe7462b68bc7c7a6c8145d0f8612424b17550a with description of existing statuses. It's updated for the latest CI running*

[❌ Click here](https://s3.amazonaws.com/clickhouse-test-reports/57433/7fbe7462b68bc7c7a6c8145d0f8612424b17550a/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs Check</td><td>Builds and tests the documentation</td><td>❌ failure</td></tr>
<tbody>
</table>

**Comment by davenger** [comment]
@CurtizJ could you please give an example scenario with WHERE clause?
Looks like it is not covered by tests.

**Comment by CurtizJ** [comment]
@davenger 
I removed this case because it appeared to be pointless. I'll update the changelog entry.

**Comment by davenger** [comment]
Please see one comment. Otherwise LGTM. Also Doc check suggests that the new command needs to be documented.

**Review by davenger — APPROVED** [review]

**Pull request merged**
