### PR TITLE
Revert "Add a setting max_execution_time_leaf to limit the execution time on shard for distributed query"

### LINKED ISSUE #56685: `02896_memory_accounting_for_user` is flaky
https://s3.amazonaws.com/clickhouse-test-reports/56489/44eb73980f1c4bb42e57915d633794715d55e3c4/stateless_tests__tsan__[3_5].html

CI DB: [link](https://play.clickhouse.com/play?user=play#CldJVEgKICAgICcwMjg5Nl9tZW1vcnlfYWNjb3VudGluZ19mb3JfdXNlcicgQVMgbmFtZV9zdWJzdHIsCiAgICA5MCBBUyBpbnRlcnZhbF9kYXlzLAogICAgKCdTdGF0ZWxlc3MgdGVzdHMgKGFzYW4pJywgJ1N0YXRlbGVzcyB0ZXN0cyAoYWRkcmVzcyknLCAnU3RhdGVsZXNzIHRlc3RzIChhZGRyZXNzLCBhY3Rpb25zKScpIEFTIGJhY2twb3J0X2FuZF9yZWxlYXNlX3NwZWNpZmljX2NoZWNrcwpTRUxFQ1QKICAgIHRvU3RhcnRPZkRheShjaGVja19zdGFydF90aW1lKSBBUyBkLAogICAgY291bnQoKSwKICAgIGdyb3VwVW5pcUFycmF5KHB1bGxfcmVxdWVzdF9udW1iZXIpIEFTIHBycywKICAgIGFueShyZXBvcnRfdXJsKQpGUk9NIGNoZWNrcwpXSEVSRSAoKG5vdygpIC0gdG9JbnRlcnZhbERheShpbnRlcnZhbF9kYXlzKSkgPD0gY2hlY2tfc3RhcnRfdGltZSkgQU5EIChwdWxsX3JlcXVlc3RfbnVtYmVyIE5PVCBJTiAoCiAgICBTRUxFQ1QgcHVsbF9yZXF1ZXN0X251bWJlciBBUyBwcm4KICAgIEZST00gY2hlY2tzCiAgICBXSEVSRSAocHJuICE9IDApIEFORCAoKG5vdygpIC0gdG9JbnRlcnZhbERheShpbnRlcnZhbF9kYXlzKSkgPD0gY2hlY2tfc3RhcnRfdGltZSkgQU5EIChjaGVja19uYW1lIElOIChiYWNrcG9ydF9hbmRfcmVsZWFzZV9zcGVjaWZpY19jaGVja3MpKQopKSBBTkQgKHBvc2l0aW9uKHRlc3RfbmFtZSwgbmFtZV9zdWJzdHIpID4gMCkgQU5EICh0ZXN0X3N0YXR1cyBJTiAoJ0ZBSUwnLCAnRVJST1InLCAnRkxBS1knKSkKR1JPVVAgQlkgZApPUkRFUiBCWSBkIERFU0MK)

### PR DESCRIPTION
**Pull request by tavplubix**
Reverts ClickHouse/ClickHouse#51823

cc: @Avogar, @canhld94

Fixes https://github.com/ClickHouse/ClickHouse/issues/56685

### CODE REVIEW

**Comment by robot-clickhouse** [comment]
*This is an automated comment for commit 0622379ec7079174bc0f1f34c27eff9ea5cb0721 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/56702/0622379ec7079174bc0f1f34c27eff9ea5cb0721/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td><a href="https://github.com/ClickHouse/ClickHouse/actions/runs/6855211930">✅ success</a></td></tr>
<tbody>
</table>
</details>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/56702/0622379ec7079174bc0f1f34c27eff9ea5cb0721/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Comment by Avogar** [comment]
I actually doubt that this PR caused the problem for 2 reasons:
1) This PR just introduces new setting that is not used by default, so no new logic applies when this setting is not used.
2) This test `02896_memory_accounting_for_user.sh` was added a day before it failed in the commit from this PR, so probably it was just on of ther first commits that run this test with some specific randomized settings that caused the timeout.

I will find what settings caused the timeout, try to fix it and revert this PR

**Comment by Avogar** [comment]
Actually, the test itself is long (runs for 2 minutes wothout random settings) and there are several settings that can affect its time: `max_block_size/output_format_parallel_formatting/input_format_parallel_parsing/min_chunk_bytes_for_parallel_parsing/max_read_buffer_size`. And also the time depends on the load to server. So, I think we should make the test faster or disable random settings for this test (or both). @nickitat this is your test, WDYT?

**Comment by nickitat** [comment]
let's try #56709

**Comment by canhld94** [comment]
I share the same view as @Avogar. The logic changes only modify distributed query code path, but `02896_memory_accounting_for_user.sh` doesn't touch distributed table.

**Comment by tavplubix** [comment]
Ah, sorry, it looked extremely suspicious because the test failed in that PR, and then started to fail in master after that PR was merged. And it was merged without a comment about failed tests

**Comment by Avogar** [comment]
> And it was merged without a comment about failed tests

Yeah, it was my fault, I will pay more attention to it, thanks.

**Comment by tavplubix** [comment]
Don't worry, I should have checked it more carefully before reverting

**Pull request merged**
