### PR TITLE
Bump boost to 1.81

### PR DESCRIPTION
**Pull request by rschu1ze**
See https://github.com/ClickHouse/boost/pull/39

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by robot-clickhouse-ci-2** [comment]
This is an automated comment for commit 44df7b6427a5010abee393f32836a2caf7c9ee7e with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/53679/44df7b6427a5010abee393f32836a2caf7c9ee7e/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Comment by rschu1ze** [comment]
Strange error in BuilderDebDebug:

https://github.com/ClickHouse/ClickHouse/actions/runs/5940486464/job/16110602709?pr=53679

https://s3.amazonaws.com/clickhouse-builds/PRs/53679/47b841ccd684f9f617384725c7f06a458c4829c7/package_debug/build_log.log

```
Aug 22 15:46:40 [559/11560] Building CXX object contrib/vectorscan-cmake/CMakeFiles/_vectorscan.dir/__/vectorscan/src/nfagraph/ng_prune.cpp.o
Aug 22 15:46:40 FAILED: contrib/vectorscan-cmake/CMakeFiles/_vectorscan.dir/__/vectorscan/src/nfagraph/ng_prune.cpp.o 
Aug 22 15:46:40 prlimit --as=10000000000 --data=5000000000 --cpu=1000 /usr/bin/sccache /usr/bin/clang++-16 --target=x86_64-linux-gnu --sysroot=/build/cmake/linux/../../contrib/sysroot/linux-x86_64/x86_64-linux-gnu/libc -DBOOST_ASIO_HAS_STD_INVOKE_RESULT=1 -DBOOST_ASIO_STANDALONE=1 -DSTD_EXCEPTION_HAS_STACK_TRACE=1 -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS -I/build/contrib/vectorscan-cmake/amd64 -I/build/base/glibc-compatibility/memcpy -isystem /build/contrib/vectorscan-cmake/common -isystem /build/contrib/vectorscan/include -isystem /build/contrib/vectorscan/src -isystem /build/contrib/llvm-project/libcxx/include -isystem /build/contrib/llvm-project/libcxxabi/include -isystem /build/contrib/libunwind/include -isystem /build/contrib/boost --gcc-toolchain=/build/cmake/linux/../../contrib/sysroot/linux-x86_64 -fdiagnostics-color=always -Xclang -fuse-ctor-homing -Wno-enum-constexpr-conversion -fsized-deallocation  -gdwarf-aranges -pipe -mssse3 -msse4.1 -msse4.2 -mpclmul -mpopcnt -fasynchronous-unwind-tables -ftime-trace -falign-functions=32 -mbranches-within-32B-boundaries -fdiagnostics-absolute-paths -fstrict-vtable-pointers -w -g -O0 -g -gdwarf-4  -D_LIBCPP_DEBUG=0 -std=c++2b   -D OS_LINUX -fno-sanitize=undefined -O2 -fno-strict-aliasing -fno-omit-frame-pointer -fvisibility=hidden -Werror -nostdinc++ -MD -MT contrib/vectorscan-cmake/CMakeFiles/_vectorscan.dir/__/vectorscan/src/nfagraph/ng_prune.cpp.o -MF contrib/vectorscan-cmake/CMakeFiles/_vectorscan.dir/__/vectorscan/src/nfagraph/ng_prune.cpp.o.d -o contrib/vectorscan-cmake/CMakeFiles/_vectorscan.dir/__/vectorscan/src/nfagraph/ng_prune.cpp.o -c /build/contrib/vectorscan/src/nfagraph/ng_prune.cpp
Aug 22 15:46:40 In file included from /build/contrib/vectorscan/src/nfagraph/ng_prune.cpp:34:
Aug 22 15:46:40 In file included from /build/contrib/vectorscan/src/nfagraph/ng_dominators.h:38:
Aug 22 15:46:40 In file included from /build/contrib/vectorscan/src/nfagraph/ng_holder.h:42:
Aug 22 15:46:40 In file included from /build/contrib/vectorscan/src/util/charreach.h:40:
Aug 22 15:46:40 In file included from /build/contrib/vectorscan/src/util/bitfield.h:44:
Aug 22 15:46:40 In file included from /build/contrib/boost/boost/dynamic_bitset.hpp:15:
Aug 22 15:46:40 In file included from /build/contrib/boost/boost/dynamic_bitset/dynamic_bitset.hpp:53:
Aug 22 15:46:40 In file included from /build/contrib/boost/boost/functional/hash/hash.hpp:6:
Aug 22 15:46:40 In file included from /build/contrib/boost/boost/container_hash/hash.hpp:17:
Aug 22 15:46:40 /build/contrib/boost/boost/container_hash/is_described_class.hpp:10:10: fatal error: 'boost/describe/bases.hpp' file not found
Aug 22 15:46:40 #include <boost/describe/bases.hpp>
Aug 22 15:46:40          ^~~~~~~~~~~~~~~~~~~~~~~~~~
Aug 22 15:46:40 1 error generated.
```

Compilation worked locally with the exact CMake invocation as in CI. Merging from master once more.

**Comment by rschu1ze** [comment]
@nikitamikhaylov Since you reviewed the [boost 1.80 update](https://github.com/ClickHouse/ClickHouse/pull/53625), would you also like to review this boost 1.81 update? Nothing interesting is happening in this PR (except the sparse checkout issue).

**Comment by baibaichen** [comment]
Would you upgade to 1.83? It incluides [boost::concurrent_flat_map](https://bannalia.blogspot.com/2023/07/inside-boostconcurrentflatmap.html), it would be useful.

**Comment by rschu1ze** [comment]
At some point yes, but let's get this PR in first 😄

**Review by davenger — APPROVED** [review]

**Pull request merged**
