### PR TITLE
stop trying to add `-j` to the variable, it simply doesnt work

### PR DESCRIPTION
**Pull request by kreuzerkrieg**
Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
- Do not prepend THREADS_COUNT with -j to avoid additional prepending in subprocesses

Detailed description / Documentation draft:
Since debhelper may invoke `rules` recursively we may get `-j-jX` instead of just `-jX`
So, just stop trying to add `-j` and use it directly in the command line

### CODE REVIEW

**Review by Felixoid — APPROVED** [review]
Let's wait for builds and merge :+1:

**Comment by Felixoid** [comment]
@kreuzerkrieg 

>  Changelog entry required for category 'Improvement'

Please, add `Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md): ...` before `Detailed description`

**Comment by kreuzerkrieg** [comment]
> **fixed**

it still complains about the description check

**Comment by Felixoid** [comment]
@mergifyio Update it please

**Comment by kreuzerkrieg** [comment]
@Mergifyio refresh

**Comment by Felixoid** [comment]
@Mergifyio update

**Comment by Felixoid** [comment]
https://s3.amazonaws.com/clickhouse-builds/32844/8f90b9b8e7df88ddfc3b887f7af7a2f4bb2234e3/clickhouse_build_check_(actions)/report.html and https://clickhouse-builds.s3.yandex.net/32844/8f90b9b8e7df88ddfc3b887f7af7a2f4bb2234e3/clickhouse_build_check/report.html are green, merging!

**Comment by kreuzerkrieg** [comment]
> https://s3.amazonaws.com/clickhouse-builds/32844/8f90b9b8e7df88ddfc3b887f7af7a2f4bb2234e3/clickhouse_build_check_(actions)/report.html and https://clickhouse-builds.s3.yandex.net/32844/8f90b9b8e7df88ddfc3b887f7af7a2f4bb2234e3/clickhouse_build_check/report.html are green, merging!

Yay!!!

**Pull request merged**
