### PR TITLE
Upgrade librdkafka to RC8

### PR DESCRIPTION
**Pull request by simPod**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Category:

Other
Short description (up to few sentences):

Upgrade librdkafka to RC8

Following this https://github.com/yandex/ClickHouse/pull/4636 same motivation

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
There is undefined configuration macro, you should update `librdkafka-cmake`.
(See `ClickHouse build check`)

**Review by alexey-milovidov — CHANGES_REQUESTED** [review]
.

**Comment by simPod** [comment]
@alexey-milovidov is there a way I can launch CI locally / myself somehow?

**Comment by alexey-milovidov** [comment]
For this case, you just need to build ClickHouse locally - that should be easy.
There is also `docker/builder` directory - it will build ClickHouse in Docker.

**Comment by simPod** [comment]
I'm able to build locally on macos but there's a bug in library :/

**Comment by simPod** [comment]
I'm able to build on macos but will try docker. Thanks

**Comment by alexey-milovidov** [comment]
Thank you!

**Pull request merged**
