### PR TITLE
Switch to libcxx / libcxxabi from LLVM 14

### LINKED ISSUE #32018: libcxx 13 compatibility
Currently it's impossible to build ClickHouse with libcxx 13, which happens to be the standard library bundled with the recommended compiler. It's understood that you should use the provided one, but at some point that will be updated too so since I had some issues I decided to give it a try and see what break.

Tested with local libc++ (from llvm 13.0.0):

```
CC=clang CXX=clang++ cmake .. -DUSE_INTERNAL_LIBCXX_LIBRARY=False -DDISABLE_HERMETIC_BUILD=ON
```

The problems come from internal dependencies that are using result_of. This was deprecated in C++17, removed in C++20 and dropped from libc++ in v13.

* Abseil
  - Issue: https://github.com/abseil/abseil-cpp/issues/649
  - Fixed in https://github.com/abseil/abseil-cpp/commit/e19260fd7dbef881492fd73891e0be5bd4a09b95
  - Available in 20211102.0
  - ClickHouse-Extras/abseil-cpp uses lts_20202_02_25 with a patch and some backports. Both are unnecessary if switched to the upstram/lts_2021_03_24 branch. Switching the submodule to point to the official repo would be an option.

* Arrow
  - Issue https://github.com/apache/arrow/pull/10814
  - Fixed in https://github.com/apache/arrow/commit/4c02c6d7ffae6f8580aa9e7f42336cfa561d357e
  - Available in 6.0.0dev+
  - Updating to upstream apache-arrow-6.0.1 works. Patches from ClickHouse-Extras: remove submodules and add Uri::host_and_port() which doesn't seem to be used anymore.
  - Needs adapting the cmake file and some changes in the callers. I've done some changes but it seems to be missing some objects (complains about ipc).

* Boost ASIO
  - The library uses it's internal way of detecting what invoke method to use (asio/detail/config.hpp).
  - Fixed in https://github.com/boostorg/asio/commit/58050a2036ad8e2d67b9ecfc9caa4eddec92fdac
  - Available in boost-1.78.0.beta1 (no stable version released yet)
  - Applying the patch (https://github.com/boostorg/asio/commit/58050a2036ad8e2d67b9ecfc9caa4eddec92fdac.patch) over the current ClickHouse-Extras fork fixes it.

* Boost Fiber/Context/Config
  - Uses Context with result_of because BOOST_NO_CXX17_STD_INVOKE is defined.
  - BOOST_NO_CXX17_STD_INVOKE is defined in boost/config/stdlib/libcpp.hpp
  - Fixed also some time ago (multiple changes)
  - Replacing boost/config with current master one (all the files, not just libcpp.hpp) fixes the issue.

* Boost format
  - Different issue. This time with allocators
  - Issue: https://github.com/boostorg/format/issues/67
  - Fixed in https://github.com/boostorg/format/commit/5884c3d8140cdcd2d1bef374fcc216244d5faaa5 -> Boost 1.74.0+
  - Applying the patch (https://github.com/boostorg/format/commit/5884c3d8140cdcd2d1bef374fcc216244d5faaa5.patch) works.

* S2
  - Uses it's own internal absl which has the same issue.
  - Fixed pretty recently (https://github.com/google/s2geometry/pull/169) by requiring an external abseil
  - Should be updated and use the contrib/absl for building
  - Haven't tested that it works, i've disabled it with `ENABLE_S2_GEOMETRY=OFF` for now.

IMO the actions points would be:
* Push `lts_2021_03_24` branch to ClickHouse-Extras/abseil-cpp or change remote to upstream.
* Push `apache-arrow-6.0.1` branch to ClickHouse-Extras/arrow. Add a commit to remote submodules (if we want it).
* Get arrow to link and work with 6.0.1. Should require only changes here.
* Update ClickHouse-Extras/s2 to a version with off tree abseil.
* Get S2 to build with contrib/abseil.
* Either update boost to a newer version (like 1.76 + ASIO patch) or apply all 3 patches individually.

I'll try to get this done locally as long as nobody says it shouldn't be done or something but, when it all works, I'll need help pushing new branches / patches into the submodules.

### PR DESCRIPTION
**Pull request by Algunenano**
Changelog category (leave one):
- Build/Testing/Packaging Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
- Switch to libcxx / libcxxabi from LLVM 14.

> Information about CI checks: https://clickhouse.tech/docs/en/development/continuous-integration/

- Minor changes to hyperscan to make it compatible.
- Does not update contrib/llvm (for the embedded compiler and cross build?).

Related to https://github.com/ClickHouse/ClickHouse/pull/34754
Closes https://github.com/ClickHouse/ClickHouse/issues/32018

### CODE REVIEW

**Comment by Algunenano** [comment]
This seems to be hitting some issue with the filesystems.

Example triggering some issues:
```
./tests/clickhouse-test 00836_indices_alter.sql --test-runs 100 -j10
```


After a few runs:
```
00836_indices_alter:                                                    [ OK ]
00836_indices_alter:                                                    [ FAIL ] - return code: 61
[Mordor] 2022.02.25 16:04:40.584594 [ 440228 ] {219f8499-e653-4692-85c9-dace928fbeba} <Error> executeQuery: Code: 573. DB::ErrnoException: Cannot add new descriptor to epoll, errno: 22, strerror: Invalid argument. (EPOLL_ERROR) (version 22.3.1.1) (from [::1]:56846) (comment: 00836_indices_alter.sql) (in query: INSERT INTO minmax_idx VALUES ), Stack trace (when copying this message, always include the lines below):

0. ./build_msan/./contrib/libcxx/include/exception:0: Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x4b876027 in /mnt/ch/ClickHouse/build_msan/programs/clickhouse
1. ./build_msan/./src/Common/Exception.cpp:58: DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xb4c7db9 in /mnt/ch/ClickHouse/build_msan/programs/clickhouse
2. ./build_msan/./src/Common/Exception.h:93: DB::ErrnoException::ErrnoException(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, int, std::__1::optional<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > const&) @ 0xb4dba9e in /mnt/ch/ClickHouse/build_msan/programs/clickhouse
3. ./build_msan/./src/Common/Exception.cpp:0: DB::throwFromErrno(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, int) @ 0xb4cc065 in /mnt/ch/ClickHouse/build_msan/programs/clickhouse
4. ./build_msan/./src/Common/Epoll.cpp:0: DB::Epoll::add(int, void*) @ 0x3a826703 in /mnt/ch/ClickHouse/build_msan/programs/clickhouse
5. ./build_msan/./src/Processors/Executors/PollingQueue.cpp:0: DB::PollingQueue::PollingQueue() @ 0x407ee840 in /mnt/ch/ClickHouse/build_msan/programs/clickhouse
6. ./build_msan/./src/Processors/Executors/ExecutorTasks.h:35: DB::PipelineExecutor::PipelineExecutor(std::__1::vector<std::__1::shared_ptr<DB::IProcessor>, std::__1::allocator<std::__1::shared_ptr<DB::IProcessor> > >&, DB::QueryStatus*) @ 0x407b24a7 in /mnt/ch/ClickHouse/build_msan/programs/clickhouse
7. ./build_msan/./contrib/libcxx/include/__memory/allocation_guard.h:66: std::__1::shared_ptr<DB::PipelineExecutor> std::__1::make_shared<DB::PipelineExecutor, std::__1::vector<std::__1::shared_ptr<DB::IProcessor>, std::__1::allocator<std::__1::shared_ptr<DB::IProcessor> > >&, DB::QueryStatus*&, void>(std::__1::vector<std::__1::shared_ptr<DB::IProcessor>, std::__1::allocator<std::__1::shared_ptr<DB::IProcessor> > >&, DB::QueryStatus*&) @ 0x3a7ccdcc in /mnt/ch/ClickHouse/build_msan/programs/clickhouse
8. ./build_msan/./src/Processors/Executors/PushingPipelineExecutor.cpp:0: DB::PushingPipelineExecutor::start() @ 0x4080ab1b in /mnt/ch/ClickHouse/build_msan/programs/clickhouse
9. ./build_msan/./src/Server/TCPHandler.cpp:0: DB::TCPHandler::processInsertQuery() @ 0x406557f4 in /mnt/ch/ClickHouse/build_msan/programs/clickhouse
10. ./build_msan/./src/Server/TCPHandler.cpp:0: DB::TCPHandler::runImpl() @ 0x4063ef48 in /mnt/ch/ClickHouse/build_msan/programs/clickhouse
11. ./build_msan/./src/Server/TCPHandler.cpp:0: DB::TCPHandler::run() @ 0x406871f9 in /mnt/ch/ClickHouse/build_msan/programs/clickhouse
12. ./build_msan/./contrib/poco/Net/src/TCPServerConnection.cpp:57: Poco::Net::TCPServerConnection::start() @ 0x4b30ca9c in /mnt/ch/ClickHouse/build_msan/programs/clickhouse
13. ./build_msan/./contrib/libcxx/include/__memory/unique_ptr.h:312: Poco::Net::TCPServerDispatcher::run() @ 0x4b30df1c in /mnt/ch/ClickHouse/build_msan/programs/clickhouse
14. ./build_msan/./contrib/poco/Foundation/src/ThreadPool.cpp:0: Poco::PooledThread::run() @ 0x4ba3b1c4 in /mnt/ch/ClickHouse/build_msan/programs/clickhouse
15. ./build_msan/./contrib/poco/Foundation/src/Thread.cpp:56: Poco::(anonymous namespace)::RunnableHolder::run() @ 0x4ba36440 in /mnt/ch/ClickHouse/build_msan/programs/clickhouse
16. ./build_msan/./contrib/poco/Foundation/include/Poco/SharedPtr.h:277: Poco::ThreadImpl::runnableEntry(void*) @ 0x4ba32101 in /mnt/ch/ClickHouse/build_msan/programs/clickhouse
17. ? @ 0x7f97ba7ea5c2 in ?
18. clone @ 0x7f97ba86f584 in ?
```

Need to find out if this is an existing bug that's uncovered / made worse by the update, or an issue introduced by the update itself.

**Comment by Algunenano** [comment]
Updating llvm-14 branch to bring a `Fix double file closing in std::filesystem::remove_all()` from https://reviews.llvm.org/D120453. This seems to fix the obvious failing tests locally.

**Comment by Algunenano** [comment]
@Mergifyio update

**Comment by Algunenano** [comment]
This is pretty much done but I'm waiting for LLVM to do a final release, since I'd rather have the final commit and not an RC version in the submodule.

**Comment by Algunenano** [comment]
Rebasing the PR with master and updating the libraries to llvmorg-14.0.0. There are just minor changes that shouldn't matter (internal cmake stuff), so once it's green I'll create the PRs to update the 3 libraries (libcxx, libcxx-abi and hyperscan)

**Comment by Algunenano** [comment]
@Mergifyio update

**Comment by Algunenano** [comment]
@Mergifyio update

**Comment by Algunenano** [comment]
@Mergifyio update

**Comment by Algunenano** [comment]
Created the 3 prs:
* [libcxx](https://github.com/ClickHouse/libcxx/pull/12)
* [libcxx-abi](https://github.com/ClickHouse/libcxxabi/pull/4)
* [hyperscan](https://github.com/ClickHouse/hyperscan/pull/5)

Once merged, I can stop using my submodules and this can move forward.

**Comment by alexey-milovidov** [comment]
@Algunenano Repositories for submodules are updated.

**Comment by Algunenano** [comment]
Thanks a lot. I've removed my forks from the submodules and updated them.

**Pull request merged**
