### PR TITLE
Update zstd to 1.3.1

### PR DESCRIPTION
**Pull request by hnakamur**
First of all, thanks for creating and sharing a great software like ClickHouse!

This is a pull request for updating zstd from 1.1.0 to 1.3.1.

I looked at https://github.com/facebook/zstd/blob/dev/NEWS
and noticed there are many improvements from 1.1.0 to 1.3.1.
The most import change is the license changed to dual license of BSD and GPLv2 (The old license was BSD + PATENTS file).

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

### CODE REVIEW

**Comment by robot-metrika-test** [comment]
Can one of the admins verify this patch?

**Comment by robot-metrika-test** [comment]
Can one of the admins verify this patch?

**Comment by alexey-milovidov** [comment]
Thanks!

**Comment by hnakamur** [comment]
Thanks for merging!

**Comment by alexey-milovidov** [comment]
Actually you updated to version 1.3.0, not 1.3.1.
https://github.com/yandex/ClickHouse/commit/17edcdec96b01d988e749f44c4be0194f8546aee

**Comment by hnakamur** [comment]
Oh, I'm sorry.
I noticed you fixed my mistake at https://github.com/yandex/ClickHouse/commit/17edcdec96b01d988e749f44c4be0194f8546aee
Thanks!

**Pull request merged**
