### PR TITLE
Remove addBatchSinglePlaceFromInterval

### PR DESCRIPTION
**Pull request by Algunenano**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
...

### Documentation entry for user-facing changes

The implementation was exactly the same as `addBatchSinglePlace` since https://github.com/ClickHouse/ClickHouse/pull/35111

### CODE REVIEW

**Comment by robot-clickhouse-ci-2** [comment]
*This is an automated comment for commit 56b5277662371e1bb7aa2853815c4ab94214cec2 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/57258/56b5277662371e1bb7aa2853815c4ab94214cec2/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td><a href="https://github.com/ClickHouse/ClickHouse/actions/runs/7004736501">✅ success</a></td></tr>
<tbody>
</table>
</details>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/57258/56b5277662371e1bb7aa2853815c4ab94214cec2/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Review by davenger — APPROVED** [review]

**Comment by Algunenano** [comment]
This is bonkers. It seems something is going on with `optimize_aggregation_in_order`:

Without `optimize_aggregation_in_order` everything seems fine:
```
SELECT
    count() AS `all`,
    countIf((WatchID % 2) = 0) AS even,
    countIf((WatchID % 2) != 0) AS odd,
    even + odd AS count_count,
    sumIf(CAST('1', 'UInt256'), (WatchID % 2) = 0) AS sum_even,
    sumIf(CAST('1', 'UInt256'), (WatchID % 2) != 0) AS sum_odd,
    sum_even + sum_odd AS sum_count
FROM test.hits
GROUP BY CounterID
ORDER BY count() DESC
LIMIT 1
SETTINGS group_by_two_level_threshold = 74648, group_by_two_level_threshold_bytes = 50000000, max_block_size = 57412, optimize_aggregation_in_order = 0

Query id: 77927ffd-9d3f-4973-ba4a-b533bdc73212

Row 1:
──────
all:         523264
even:        261874
odd:         261390
count_count: 523264
sum_even:    261874
sum_odd:     261390
sum_count:   523264

1 row in set. Elapsed: 0.028 sec. Processed 8.87 million rows, 106.49 MB (320.96 million rows/s., 3.85 GB/s.)
Peak memory usage: 86.04 MiB.
```

As you can see count() == countIf(even) + countIf(odd) == sumIf(1, even) + sumIf(odd)


Now, with `optimize_aggregation_in_order = 1`:

```
SELECT
    count() AS `all`,
    countIf((WatchID % 2) = 0) AS even,
    countIf((WatchID % 2) != 0) AS odd,
    even + odd AS count_count,
    sumIf(CAST('1', 'UInt256'), (WatchID % 2) = 0) AS sum_even,
    sumIf(CAST('1', 'UInt256'), (WatchID % 2) != 0) AS sum_odd,
    sum_even + sum_odd AS sum_count
FROM test.hits
GROUP BY CounterID
ORDER BY count() DESC
LIMIT 1
SETTINGS group_by_two_level_threshold = 74648, group_by_two_level_threshold_bytes = 50000000, max_block_size = 57412, optimize_aggregation_in_order = 1

Query id: ddbc3112-a549-41ec-b541-eb67c51866d2

Row 1:
──────
all:         523264
even:        402010
odd:         401758
count_count: 803768
sum_even:    261620
sum_odd:     261644
sum_count:   523264

1 row in set. Elapsed: 0.094 sec. Processed 8.87 million rows, 106.49 MB (94.65 million rows/s., 1.14 GB/s.)
Peak memory usage: 79.81 MiB.
```

Numbers are totally wrong. count(even) + count(odd) is counting 800k (vs 523k) and the number of even / odds counted by sum doesn't match the other one.


To confirm: sum(if(1, condition)) != sumIf(1, condition) with `optimize_aggregation_in_order=1`:

```
SELECT
    count() AS `all`,
    sum(If((WatchID % 2) = 0, 1, 0)) AS sum_if_even,
    sum(If((WatchID % 2) = 1, 1, 0)) AS sum_if_odd,
    sum_if_even + sum_if_odd AS sum_if_count,
    sumIf(1, (WatchID % 2) = 0) AS sum_even,
    sumIf(1, (WatchID % 2) != 0) AS sum_odd
FROM test.hits
GROUP BY CounterID
ORDER BY count() DESC
LIMIT 1
SETTINGS group_by_two_level_threshold = 74648, group_by_two_level_threshold_bytes = 50000000, max_block_size = 57412, optimize_aggregation_in_order = 1, optimize_rewrite_aggregate_function_with_if = 0

Query id: 3c070d75-d139-4a89-8b50-2b3bed605bcd

Row 1:
──────
all:          523264
sum_if_even:  261874
sum_if_odd:   261390
sum_if_count: 523264
sum_even:     261620
sum_odd:      261644

1 row in set. Elapsed: 0.022 sec. Processed 8.87 million rows, 106.49 MB (394.55 million rows/s., 4.73 GB/s.)
Peak memory usage: 23.26 MiB.
```

(I disabled `optimize_rewrite_aggregate_function_with_if` to be able to compare)

**Comment by Algunenano** [comment]
Unsurprisingly it works fine without the changes, so I'm missing something

**Comment by Algunenano** [comment]
Of course I was missing something: 1 bugs in countIf() and another one in sumIf(), also introduced in #35111.

Not only I'm unhappy about how long these bugs have been there without being triggered, but how close we were to putting them into production. We only caught them because there is a JIT test that happened to randomly triggered this path (because it didn't use JIT!)

**Comment by Algunenano** [comment]
* `Stateless tests (debug) [2/5]` -> https://github.com/ClickHouse/ClickHouse/issues/56256
* `Performance Comparison [3/4] `. There are "Run Errors" in a couple of tests (`destroy_aggregate_states` and `decimal_aggregates`), both failing with `Unexpected EOF while reading bytes`. Tested them locally and they run fine

**Pull request merged**
