### PR TITLE
Add llvm-12/clang-12 packager in docker images

### PR DESCRIPTION
**Pull request by qoega**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

...

Detailed description / Documentation draft:

...

By adding documentation, you'll allow users to try your new feature immediately, not when someone else will have time to document it later. Documentation is necessary for all features that affect user experience in any way. You can add brief documentation draft above, or add documentation right into your patch as Markdown files in [docs](https://github.com/ClickHouse/ClickHouse/tree/master/docs) folder.

If you are doing this for the first time, it's recommended to read the lightweight [Contributing to ClickHouse Documentation](https://github.com/ClickHouse/ClickHouse/tree/master/docs/README.md) guide first.

Information about CI checks: https://clickhouse.tech/docs/en/development/continuous-integration/

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
It looks like lld-12 is selected for build with clang-11 and it does not work: https://clickhouse-builds.s3.yandex.net/20499/b79680b8711753a0def52617c74e75202584ed44/clickhouse_build_check/build_log_896821990_1613383537.txt

**Comment by abyss7** [comment]
> It looks like lld-12 is selected for build with clang-11 and it does not work: https://clickhouse-builds.s3.yandex.net/20499/b79680b8711753a0def52617c74e75202584ed44/clickhouse_build_check/build_log_896821990_1613383537.txt

What problem was inside this log?

**Comment by abyss7** [comment]
I've managed to build server locally, but it has problems with PHDR cache code (debug+shared+ASAN build):

> ==42067==ERROR: AddressSanitizer: global-buffer-overflow on address 0x0000005034fc at pc 0x0000004ae8a7 bp 0x7fff598bbbf0 sp 0x7fff598bb3b8
READ of size 8 at 0x0000005034fc thread T0
    #0 0x4ae8a6 in __asan_memcpy (/home/ilezhankin/gh/ch/build/debug-shared-address/programs/clickhouse+0x4ae8a6)
    #1 0x7f0fbcedc3f3 in unsigned long unalignedLoad<unsigned long>(void const*) /home/ilezhankin/gh/ch/build/debug-shared-address/../../base/common/../common/unaligned.h:11:5
    #2 0x7f0fbcedabae in SipHash::update(char const*, unsigned long) /home/ilezhankin/gh/ch/build/debug-shared-address/../../src/Common/SipHash.h:113:28
    #3 0x7f0fbbe50cf1 in callback(dl_phdr_info*, unsigned long, void*) /home/ilezhankin/gh/ch/build/debug-shared-address/../../src/Common/getHashOfLoadedBinary.cpp:21:18
    #4 0x7f0fba35f579 in dl_iterate_phdr /home/ilezhankin/gh/ch/build/debug-shared-address/../../base/common/phdr_cache.cpp:74:18
    #5 0x7f0fbbe50aae in getHashOfLoadedBinary() /home/ilezhankin/gh/ch/build/debug-shared-address/../../src/Common/getHashOfLoadedBinary.cpp:32:5
    #6 0x7f0fbbe50e70 in getHashOfLoadedBinaryHex() /home/ilezhankin/gh/ch/build/debug-shared-address/../../src/Common/getHashOfLoadedBinary.cpp:39:20
    #7 0x7f0fbc86cefb in DB::Server::main(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) /home/ilezhankin/gh/ch/build/debug-shared-address/../../programs/server/Server.cpp:471:41
    #8 0x7f0fb9cb42ff in Poco::Util::Application::run() /home/ilezhankin/gh/ch/build/debug-shared-address/../../contrib/poco/Util/src/Application.cpp:334:8
    #9 0x7f0fbc863a6a in DB::Server::run() /home/ilezhankin/gh/ch/build/debug-shared-address/../../programs/server/Server.cpp:343:25
    #10 0x7f0fb9d34313 in Poco::Util::ServerApplication::run(int, char**) /home/ilezhankin/gh/ch/build/debug-shared-address/../../contrib/poco/Util/src/ServerApplication.cpp:611:9
    #11 0x7f0fbc85fe55 in mainEntryClickHouseServer(int, char**) /home/ilezhankin/gh/ch/build/debug-shared-address/../../programs/server/Server.cpp:135:20
    #12 0x4e368f in main /home/ilezhankin/gh/ch/build/debug-shared-address/../../programs/main.cpp:368:12
    #13 0x7f0fb7a10bf6 in __libc_start_main /build/glibc-S9d2JN/glibc-2.27/csu/../csu/libc-start.c:310
    #14 0x434299 in _start (/home/ilezhankin/gh/ch/build/debug-shared-address/programs/clickhouse+0x434299)
> 
> 0x0000005034fc is located 36 bytes to the left of global variable '<string literal>' defined in '../../programs/main.cpp:306:9' (0x503520) of size 50
  '<string literal>' is ascii string 'Instruction check fail. The CPU does not support '
> 0x0000005034fc is located 0 bytes to the right of global variable '<string literal>' defined in '../../programs/main.cpp:298:9' (0x5034e0) of size 28
  '<string literal>' is ascii string 'Can not set signal handler

**Comment by abyss7** [comment]
Static build looks fine.

**Comment by alexey-milovidov** [comment]
> I've managed to build server locally, but it has problems with PHDR cache code (debug+shared+ASAN build):

`getHashOfLoadedBinary` can be simply disabled for shared build.

**Comment by alexey-milovidov** [comment]
> What problem was inside this log?

Don't remember, let's restart builds.

**Comment by qoega** [comment]
This PR was continued in #20495

**Pull request closed without merging**
