### PR TITLE
Add postgresql engine docs

### PR DESCRIPTION
**Pull request by Slach**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Documentation (changelog entry is not required)

@kssenii look to https://github.com/ClickHouse/ClickHouse/pull/21078

### CODE REVIEW

**Comment by kssenii** [comment]
@Slach. Now in master `docs check` is also broken: https://clickhouse-test-reports.s3.yandex.net/20991/2b401cfa7c1f2886f40bc77f37ee4b38b86c5eae/docs_check.html#fail1 (but will be fixed). But there are only 2 broken links in master. And `docs check` in this PR finds much more, it means something is wrong with the links in this PR. May be just remove the links?

**Comment by Slach** [comment]
@kssenii let try to figure it out again
https://clickhouse-test-reports.s3.yandex.net/21220/fd2d0a236a6850ec14b1674344af602b574bb125/docs_check/docs_output.txt

```
INFO:root:Tag <a href="#../../sql-reference/table-functions/jdbc/">JDBC</a>
INFO:root:Link to nowhere: #../../sql-reference/table-functions/jdbc/
INFO:root:Tag <a href="#../../../engines/table-engines/integrations/">Движки таблиц для интеграции</a>
INFO:root:Link to nowhere: #../../../engines/table-engines/integrations/
WARNING:root:Found 212 duplicate anchor points
ERROR:root:Found 2 links to nowhere in ru
```

look to the source
`Движки таблиц для интеграции` contains is only one place

https://github.com/Slach/ClickHouse/blame/add_postgresql_engine_docs/docs/ru/engines/table-engines/special/index.md#L12
```
-   [Движки таблиц для интеграции](../../../engines/table-engines/integrations/index.md).
```

it CAN"T be relative `href="#../../"`
and it exists in code from Aug 2020
and it not related to my PR
and it already SAME on `master`

and the second broken link`sql-reference/table-functions/jdbc`
this text just not exists in `docs` folder in my branch and in master the same tate
image

who can help us to figure out why doc check generate wrong relative "nowhere" link instead of right and use some obslete copy of *.md files instead of use actual?

**Comment by kssenii** [comment]
> and the second broken linksql-reference/table-functions/jdbc
this text just not exists in docs folder in my branch and in master the same state

This is really strange. 

@alexey-milovidov , do you know why `docs check` fails on links not added in this pr? Seems really unrelated to changes. Can I merge? There just came another postgres doc pr. I think this pr should be merged first.

**Comment by Slach** [comment]
@alexey-milovidov 
I also run 
`docs/tools/build.py --lang ru --verbose`
and doesn't see any "nowhere" errors inside my branch

**Comment by kssenii** [comment]
@Slach, look https://github.com/ClickHouse/ClickHouse/pull/21268#issuecomment-787106299

**Comment by alexey-milovidov** [comment]
Maybe rebase will help.

**Comment by alexey-milovidov** [comment]
It did not.

**Comment by alexey-milovidov** [comment]
> it CAN"T be relative href="#../../"

It is related to one of the ugly hacks in documentation build process.
See `def concatenate(lang, docs_path, single_page_file, nav)` in `single_page.py`
and `def test_single_page(input_path, lang)` in `test.py`.

The original author of this code cannot help us anymore and we have to rely on our own.
I will try to rewrite this code.

**Comment by alexey-milovidov** [comment]
> Docs check — Docs check passed

Finally.

**Comment by Slach** [comment]
great work, thanks a lot

**Pull request merged**
