### PR TITLE
Do not acquire read locks in system.tables if possible

### PR DESCRIPTION
**Pull request by Algunenano**
### Changelog category (leave one):
- Performance Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
- Avoid acquiring read locks in system.tables if possible

> Information about CI checks: 

Draft because:
- I have no idea why this optimization was only applied to Lazy database engines since it seems it's applicable to all of them.
- Need to review carefully (or somebody help) again the columns to make sure these don't depend on the table object (thus they don't need a read lock).
- Need to make sure not having a lock doesn't have unintended consequences or the other columns. For example, to get `dependencies_database` we use the database catalog so it doesn't appear to require locking the table, but maybe it does for other reasons.
- Need to add some tests.

Tested with a dumb script that creates 2000 tables and 1000 MVs:
```bash
#!/bin/bash

clickhouse client --query "CREATE DATABASE IF NOT EXISTS test_dependencies";
__query()
{
    clickhouse client -d test_dependencies --query "$1"
}

for i in {1..1000}
do
    __query "CREATE TABLE source${i} (a Int64) ENGINE=MergeTree() ORDER BY a"
    __query "CREATE TABLE target${i} (a Int64) ENGINE=MergeTree() ORDER BY a"
    __query "CREATE MATERIALIZED VIEW mv${i} TO target${i} AS Select * FROM source${i}"
done

# clickhouse client --query "DROP DATABASE test_dependencies SYNC";
```

And a query like this to access dependencies:
```sql
SELECT database, name
              FROM
              system.tables
              WHERE
              (database, name) IN
                  (
                      SELECT _table.1 as database, _table.2 as table
                      FROM
                      (
                          SELECT arrayJoin(arrayZip(dependencies_database, dependencies_table)) as _table
                          FROM system.tables
                          WHERE database = 'test_dependencies' AND name = 'source1'
                      )
                  )
```
 
 Before the patch: 61 ContextLock / 3175 RWLockAcquiredReadLocks
 With the patch: 60 ContextLock / 4 RWLockAcquiredReadLocks
 

 Although with https://github.com/ClickHouse/ClickHouse/pull/41145 acquiring these locks is less painful (since the most common exclusive locks are gone), it's still better to limit the contention.

### CODE REVIEW

**Comment by tavplubix** [comment]
Seems like it was intended to protect from concurrent ALTER, DROP or RENAME. ALTERs do not acquire exclusive lock since 20.3, so it's out of the scope.

> why this optimization was only applied to Lazy database engines

Maybe because Lazy database can contain `*Log` tables only and `*Log` tables cannot be altered. But they can be truncated, dropped or renamed, so most likely this optimization was just incorrect.

Questionable columns are:
 - `data_paths` can be changed by RENAME if an Ordinary database is involved, so we need the lock
 - `metadata_modification_time` will be 0 the table was dropped concurrently, but it's okay
 - `create_table_query` (as well as `engine_full`, `as_select`) requires access to metadata file that can be removed by concurrent DROP/RENAME, but seems like it's not a problem because `tryGetCreateTableQuery` does not throw

Safe columns are:
 - `*_key`, `comment` and everything that we fill from `metadata_snapshot`
 - `total_rows`, `total_bytes`, `lifetime_rows`, `lifetime_bytes`, because they can be changed by INSERT 
 - everything related to dependencies (synchronized in DatabaseCatalog)
 - `has_own_data`, it's usually constant

**Comment by Algunenano** [comment]
Hi  @tavplubix. I was on holidays so sorry for the delay and thanks a lot for the comments.

> Safe columns are:
> *_key, comment and everything that we fill from metadata_snapshot

AFAICS this would be the opposite. We get the `metadata_snapshot` from `table` and we only get `table` if we get a shared lock on it, so they wouldn't be safe, right?

> total_rows, total_bytes, lifetime_rows, lifetime_bytes, because they can be changed by INSERT

Same as above. To get these columns we use the `table` StoragePtr which is only available with the lock.

> everything related to dependencies (synchronized in DatabaseCatalog)

Yes.

> has_own_data, it's usually constant

It also needs the metadata snapshot, which again depends on `table`.


I'll add comments to all safe columns to note why the are "safe" to use unlocked and move the PR to ready for review.

**Comment by tavplubix** [comment]
We don't need the lock to use `StoragePtr`. It's only required for calling some methods like `read`, `write`, `rename`, `truncate`, and similar methods that may touch data on disk.

**Comment by Algunenano** [comment]
I've reviewed all the columns after the comments to confirm and it seems that yeah, data_paths seem to be the only instance not fully protected. My notes: 

```c++
    static const std::set<std::string> columns_without_lock = {
        "database", // Input parameter
        "name", // Input parameter
        "uuid", // Input parameter
        "engine", // Unaffected by changes
        "is_temporary", // Static
        // "data_paths", // UNSAFE: Can change on RENAME with Ordinary database engine
        "metadata_path", // database->getObjectMetadataPath is safe (won't throw on drop)
        "metadata_modification_time", // database->getObjectMetadataModificationTime is safe (won't throw on drop)
        "dependencies_database", // Sync internally in the DatabaseCatalog
        "dependencies_table", // Sync internally in the DatabaseCatalog
        "create_table_query", // database->tryGetCreateTableQuery No except (returns nullptr)
        "engine_full", // database->tryGetCreateTableQuery No except (returns nullptr)
        "as_select", // database->tryGetCreateTableQuery No except (returns nullptr)
        "partition_key", // Uses metadata_snapshot
        "sorting_key", // Uses metadata_snapshot
        "primary_key", // Uses metadata_snapshot
        "sampling_key", // Uses metadata_snapshot
        "storage_policy", // Sync internally via storage_policies_mutex
        "total_rows", // Thread safe (multiple implementations)
        "total_bytes", // Thread safe (multiple implementations)
        "lifetime_rows", // Atomic variable (StorageBuffer::Writes)
        "lifetime_bytes", // Atomic variable (StorageBuffer::Writes)
        "comment", // Uses metadata_snapshot
        "has_own_data", // Unaffected by changes
        "loading_dependencies_database", // Uses metadata_snapshot
        "loading_dependencies_table", // Uses metadata_snapshot
        "loading_dependent_database", // Uses metadata_snapshot
        "loading_dependent_table" // Uses metadata_snapshot
    };
```

Based on this we could remove the lock completely and leave it only on data_paths

**Comment by Algunenano** [comment]
Let's see what the CI thinks, specially tsan.

**Comment by Algunenano** [comment]
Seems fine

**Review by tavplubix — APPROVED** [review]

**Pull request merged**
