### PR TITLE
CollapsingMergeTree: Merge rows with invalid sign values as is

### PR DESCRIPTION
**Pull request by cwurm**
Currently, parts containing rows with sign column values that are not `1` or `-1` in a CollapsingMergeTree can never be merged. Merge attempts will be made forever but will always fail with an exception. When this happens, there does not seem to be a way to resolve it. For example, a mutation trying to drop the offending rows might never execute because merges are scheduled before mutations and keep the parts locked. See https://github.com/ClickHouse/ClickHouse/issues/70964 for an example.

By default, `optimize_on_insert` is on and will prevent inserting any rows with invalid sign column values. But I have increasingly seen this setting turned off to speed up inserts, and in fact, I've seen broken CollapsingMergeTree tables in the wild.

This change allows merges of parts with invalid sign column values to proceed by preserving the invalid rows as they are and ignoring them for the purposes of the collapsing algorithm. Instead, a warning will be printed in the logs, similar to what currently already happens when the number of state and cancel rows is unbalanced.

The data will still be incorrect, but at least the user will have a chance to notice and fix it without discarding the entire table.

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Allow merging of rows with invalid sign column values in CollapsingMergeTree tables.

### CODE REVIEW

**Comment by robot-clickhouse-ci-1** [comment]
*This is an automated comment for commit 09da54f8a7eed79bb7785ccb6bd55e12581f8f4f with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/73864/09da54f8a7eed79bb7785ccb6bd55e12581f8f4f/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/73846/20a5aa15c1af2c8971ffeb08d254a6c5243f3a87/docs_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Comment by alexey-milovidov** [comment]
How could we preserve the current behavior of exception on insert?

**Comment by cwurm** [comment]
> How could we preserve the current behavior of exception on insert?

Good point. I've added a parameter in `MergeTreeDataWriter` and added a test for this case.

**Review by alexey-milovidov — APPROVED** [review]
LGTM

**Comment by cwurm** [comment]
Test failures were caused by vertical merges. I fixed it and added a test.

**Pull request merged**
