### PR TITLE
support for CREATE OR REPLACE VIEW

### PR DESCRIPTION
**Pull request by bgranvea**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

For changelog. Remove if this is non-significant change.

Category:
- Improvement

Short description (up to few sentences):
Support for CREATE OR REPLACE VIEW. Allow to create a view or set a new definition in a single statement.

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
The implementation looks almost Ok.
The flag `or_replace_view` looks too specific but Ok for now.

Does it work for materialized views? (I don't see a check for it in the test.)
If it is permitted for materialized views, there will be an issue with replicated materialized views (a typical case). When we drop replicated table only a replica is dropped. When we create replicated table again, it will add new replica, check the structure with existing replicas and download all data. The structure of replicated materialized view cannot be changed with `CREATE OR REPLACE` query.

Resolution: we should explicitly disable support for materialized views and add negative test to check for it. (To create negative test, use `-- { serverError ... }` comment, see examples in other tests).

**Comment by alexey-milovidov** [comment]
I see that it is already checked: https://github.com/yandex/ClickHouse/pull/4654/files#diff-b7f2297ee277fecc56911861bae15818R442

The only remaining step is to add a negative test...

**Comment by alexey-milovidov** [comment]
I'll add it.

**Comment by alexey-milovidov** [comment]
Ocassionally, we have no simple way to test for presence of syntax errors.

**Comment by alexey-milovidov** [comment]
But your test is slightly incorrect:

```
milovidov-Latitude-E7470 :) CREATE VIEW test.t ( next_number UInt64) AS SELECT number + 1 FROM system.numbers

CREATE VIEW test.t
(
    next_number UInt64
) AS
SELECT number + 1
FROM system.numbers 

Ok.

0 rows in set. Elapsed: 0.011 sec. 

milovidov-Latitude-E7470 :) SELECT * FROM test.t LIMIT 10

SELECT *
FROM test.t 
LIMIT 10

Received exception from server (version 19.5.1):
Code: 10. DB::Exception: Received from localhost:9000, 127.0.0.1. DB::Exception: Not found column next_number in block. There are only columns: .
```

**Comment by bgranvea** [comment]
I've excluded materialized views because it is like this in other databases and I think it makes sense to consider MV more like a standard table because of the associated storage.

Anyway, thank you for taking care of the changes.

**Pull request merged**
