### PR TITLE
Normalize performance tests 2

### PR DESCRIPTION
**Pull request by alexey-milovidov**
Changelog category (leave one):
- Build/Testing/Packaging Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Enable performance test that was not working.

It's a shame that some of our tests were not working and no one cares.
It has happened at https://github.com/ClickHouse/ClickHouse/issues/6478

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
TODO: enable all `long` tests.
All tests exist for reason and we cannot simply skip them.

**Comment by akuzm** [comment]
> It's a shame that some of our tests were not working and no one cares.

If no one cared they wouldn't work at all, so I think you're exaggerating.

> It has happened at #6478

It happened long before that -- hits_1000m, nyc_taxi and other tables were never downloaded, and the old performance test silently ignored all errors. See here for example:
https://clickhouse-test-reports.s3.yandex.net/0/2a9e2ab45c4fede9436591efc4f4472ed54a5fb3/performance_test/comparison_min_time_gcc_9.html

I supported this behavior, so the tests that don't have a required table are ignored with a message (yes, I know it's a very bad message). Both 1000m and taxi datasets are well into hundreds of gigabytes, probably these tests are meant for manual testing and not for every commit?

**Comment by akuzm** [comment]
> I supported this behavior, so the tests that don't have a required table are ignored with a message (yes, I know it's a very bad message). 

```
2019.10.19 07:40:08.738542 <Information> PerformanceTestSuite: Preconditions for test 'nyc_taxi' are not fullfilled, skip run
```

Looks like this behavior was deliberate in the old tests as well.

**Comment by alexey-milovidov** [comment]
Many queries from `agg_functions_min_max_any` are "unstable".
Don't see the reason why - they are just usual simple SELECT queries from a table with data.

**Comment by akuzm** [comment]
> Many queries from `agg_functions_min_max_any` are "unstable".
> Don't see the reason why - they are just usual simple SELECT queries from a table with data.

Looking at the metrics, it's the usual thing with page faults.

**Pull request merged**
