### PR TITLE
Remove the usage of Analyzer setting in the client

### LINKED ISSUE #51532: [Master] CLI suggestions are broken when connecting to older ClickHouse releases
AFAIK it only affects master (unreleased)

I'm not sure how common of a scenario this is (it is in my local setup), but if you use ClickHouse master (23.6) client to connect to an old release (like 22.8) the suggestions won't work because the query used to retrieve them is invalid.

```
$ ch_client_prod-02
ClickHouse client version 23.6.1.1.
Connecting to clickhouse-02:59000 as user default.
Connected to ClickHouse server version 22.8.11 revision 54460.

ClickHouse server version is older than ClickHouse client. It may indicate that the server is out of date and can be upgraded.

Warnings:
 * Linux transparent hugepages are set to "always". Check /sys/kernel/mm/transparent_hugepage/enabled

Cannot load data for command line suggestions: Code: 115. DB::Exception: Received from clickhouse-02:59000. DB::Exception: Unknown setting allow_experimental_analyzer: Maybe you meant ['allow_experimental_map_type','allow_experimental_geo_types']. (UNKNOWN_SETTING) (version 23.6.1.1)
production-02 :) Select version();

SELECT version()

Query id: aed1b84d-99d7-41ab-81b0-ab0380ec5a2c

┌─version()──┐
│ 22.8.11.15 │
└────────────┘

1 row in set. Elapsed: 0.001 sec. 
```

It seems this was introduced in https://github.com/ClickHouse/ClickHouse/pull/50605 because of https://github.com/ClickHouse/ClickHouse/issues/50669. Since this in hardcoded in the CLI you can't try to change/disable the behaviour in any way.

 cc @hanfei1991

### PR DESCRIPTION
**Pull request by alexey-milovidov**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

This closes #51532

### CODE REVIEW

**Comment by robot-ch-test-poll3** [comment]
This is an automated comment for commit 0c697b920fa529fcd10ab2802828c35c44878c46 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/51578/0c697b920fa529fcd10ab2802828c35c44878c46/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Comment by hanfei1991** [comment]
CI will fail if we remove it

**Comment by alexey-milovidov** [comment]
Compatibility with old server versions (production scenario) is more important than Analyzer (a new feature in development).

**Comment by tavplubix** [comment]
@alexey-milovidov, this PR breaks CI. And backports will break tests in release branches as well.

> Compatibility with old server versions (production scenario) is more important than Analyzer (a new feature in development).

Anyway, we should not merge PRs that break tests (even tests for experimental features) because:
 - It will fail in every PR now. And everyone will have to check what failed and why. That's annoying.
 - Eventually nobody will even try to take a look at `Stateless tests (release, analyzer)`, so this check will become completely broken.

cc: @novikd

**Pull request merged**
