### PR TITLE
Add info about acquired space in cache to not enough space error

### PR DESCRIPTION
**Pull request by vdimir**
### Changelog category (leave one):

- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
...

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by robot-ch-test-poll3** [comment]
This is an automated comment for commit 27de340b1a7b4a2e1b219fde33f5fbc595cc00c0 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/51537/27de340b1a7b4a2e1b219fde33f5fbc595cc00c0/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
@vdimir the integration test has to be updated.

**Comment by alexey-milovidov** [comment]
@vdimir, please resolve the conflict.

**Comment by alexey-milovidov** [comment]
Only one test remains, CC @SmitaRKulkarni

**Comment by alexey-milovidov** [comment]
Ok, the test fixed: #52855

**Review by alexey-milovidov — APPROVED** [review]

**Pull request merged**
