### PR TITLE
docs/aggregate-functions: fix window description for windowFunnel

### PR DESCRIPTION
**Pull request by jinghancc**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Documentation (changelog entry is not required)

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

...

Detailed description / Documentation draft:
This PR fixes doc description of parameter `window` for ClickHouse aggregate function `windowFunnel`.

Previously, `window` was described as time interval between adjacent conditions, but actually it is the time interval between first condition and last condition.

Now, we change the description to reflect the fact.
`timestamp of cond1 <= timestamp of cond2 <= ... <= timestamp of condN <= timestamp of cond1 + window`

Related issue: 
https://github.com/ClickHouse/ClickHouse/issues/21849
https://github.com/ClickHouse/ClickHouse/issues/21833
...

By adding documentation, you'll allow users to try your new feature immediately, not when someone else will have time to document it later. Documentation is necessary for all features that affect user experience in any way. You can add brief documentation draft above, or add documentation right into your patch as Markdown files in [docs](https://github.com/ClickHouse/ClickHouse/tree/master/docs) folder.

If you are doing this for the first time, it's recommended to read the lightweight [Contributing to ClickHouse Documentation](https://github.com/ClickHouse/ClickHouse/tree/master/docs/README.md) guide first.

Information about CI checks: https://clickhouse.tech/docs/en/development/continuous-integration/

### CODE REVIEW

**Review by sundy-li — APPROVED** [review]

**Comment by jinghancc** [comment]
@filimonov do you mind taking a look?

**Comment by vdimir** [comment]
Maybe it is better to write it explicitly, like you write in description '_it is the time interval between first condition and last condition_.' ?
Also do we need to change doc for `sequenceMatch`? It's in linked issue, but there is not changes in `sequenceMatch` doc

**Review by vdimir — APPROVED** [review]

**Comment by jinghancc** [comment]
@vdimir Thanks for taking a look at this PR, I have updated the document. This issue is not related to `sequenceMatch`, I mentioned that issue because @filimonov mentioned using `windowFunnel` for my use case, and then I found out the document of `windowFunnel` is wrong.

**Comment by gyuton** [comment]
Internal documentation ticket: DOCSUP-8181.

**Pull request merged**
