### PR TITLE
Update tests' docker containers

### PR DESCRIPTION
**Pull request by Felixoid**
### Changelog category (leave one):
- Build/Testing/Packaging Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Update Ubuntu version in docker containers

### CODE REVIEW

**Comment by robot-clickhouse-ci-2** [comment]
This is an automated comment for commit 662152dddc1280023ba04956f6f0d0c2d2b96785 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/51180/662152dddc1280023ba04956f6f0d0c2d2b96785/ci_running.html)
The overall status of the commit is 🔴 failure

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>AST fuzzer</td><td>Runs randomly generated queries to catch program errors. The build type is optionally given in parenthesis. If it fails, ask a maintainer for help</td><td>🔴 failure</td></tr>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>ClickHouse Keeper Jepsen</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>🟢 success</td></tr>
<tr><td>ClickHouse build check</td><td>Builds ClickHouse in various configurations for use in further steps. You have to fix the builds that fail. Build logs often has enough information to fix the error, but you might have to reproduce the failure locally. The <b>cmake</b> options can be found in the build log, grepping for <b>cmake</b>. Use these options and follow the <a href="https://clickhouse.com/docs/en/development/build">general build process</a></td><td>🟢 success</td></tr>
<tr><td>Compatibility check</td><td>Checks that <b>clickhouse</b> binary runs on distributions with old libc versions. If it fails, ask a maintainer for help</td><td>🟢 success</td></tr>
<tr><td>Docker image for servers</td><td>The check to build and optionally push the mentioned image to docker hub</td><td>🟢 success</td></tr>
<tr><td>Fast test</td><td>Normally this is the first check that is ran for a PR. It builds ClickHouse and runs most of <a href="https://clickhouse.com/docs/en/development/tests#functional-tests">stateless functional tests</a>, omitting some. If it fails, further checks are not started until it is fixed. Look at the report to see which tests fail, then reproduce the failure locally as described <a href="https://clickhouse.com/docs/en/development/tests#functional-test-locally">here</a></td><td>🟢 success</td></tr>
<tr><td>Flaky tests</td><td>Checks if new added or modified tests are flaky by running them repeatedly, in parallel, with more randomization. Functional tests are run 100 times with address sanitizer, and additional randomization of thread scheduling. Integrational tests are run up to 10 times. If at least once a new test has failed, or was too long, this check will be red. We don't allow flaky tests, read <a href="https://clickhouse.com/blog/decorating-a-christmas-tree-with-the-help-of-flaky-tests/">the doc</a></td><td>🟢 success</td></tr>
<tr><td>Install packages</td><td>Checks that the built packages are installable in a clear environment</td><td>🟢 success</td></tr>
<tr><td>Integration tests</td><td>The integration tests report. In parenthesis the package type is given, and in square brackets are the optional part/total tests</td><td>🔴 failure</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
<tr><td>Performance Comparison</td><td>Measure changes in query performance. The performance test report is described in detail <a href="https://github.com/ClickHouse/ClickHouse/tree/master/docker/test/performance-comparison#how-to-read-the-report">here</a>. In square brackets are the optional part/total tests</td><td>🟢 success</td></tr>
<tr><td>Push to Dockerhub</td><td>The check for building and pushing the CI related docker images to docker hub</td><td>🟢 success</td></tr>
<tr><td>SQLancer</td><td>Fuzzing tests that detect logical bugs with <a href="https://github.com/sqlancer/sqlancer">SQLancer</a> tool</td><td>🟢 success</td></tr>
<tr><td>Sqllogic</td><td>Run clickhouse on the <a href="https://www.sqlite.org/sqllogictest">sqllogic</a> test set against sqlite and checks that all statements are passed</td><td>🟢 success</td></tr>
<tr><td>Stateful tests</td><td>Runs stateful functional tests for ClickHouse binaries built in various configurations -- release, debug, with sanitizers, etc</td><td>🟢 success</td></tr>
<tr><td>Stateless tests</td><td>Runs stateless functional tests for ClickHouse binaries built in various configurations -- release, debug, with sanitizers, etc</td><td>🔴 failure</td></tr>
<tr><td>Stress test</td><td>Runs stateless functional tests concurrently from several clients to detect concurrency-related errors</td><td>🟢 success</td></tr>
<tr><td>Style Check</td><td>Runs a set of checks to keep the code style clean. If some of tests failed, see the related log from the report</td><td>🟢 success</td></tr>
<tr><td>Unit tests</td><td>Runs the unit tests for different release types</td><td>🟢 success</td></tr>
<tr><td>Upgrade check</td><td>Runs stress tests on server version from last release and then tries to upgrade it to the version from the PR. It checks if the new server can successfully startup without any errors, crashes or sanitizer asserts</td><td>🟢 success</td></tr>
</table>

**Comment by Felixoid** [comment]
The issue with mysql-odbc is addressed by using the recent version. Now the integration tests with sanitizers are the issue.

**Review by qoega — APPROVED** [review]
I checked everything except cgroups v2 cpp code.

**Comment by Felixoid** [comment]
> I checked everything except cgroups v2 cpp code.

@serxa checked it in #51478

**Comment by Felixoid** [comment]
Mark it as `Draft` to not have it merged silently at night

**Comment by tavplubix** [comment]
It breaks integration tests, let's revert

**Pull request merged**
