### PR TITLE
ALTER PRIMARY KEY

### PR DESCRIPTION
**Pull request by amosbird**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- New Feature

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Allow changing primary key of existing tables.  https://github.com/ClickHouse/ClickHouse/issues/147  https://github.com/ClickHouse/ClickHouse/issues/2210   https://github.com/ClickHouse/ClickHouse/issues/7052

Detailed description / Documentation draft:
.

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
Abandoned.

**Comment by javisantana** [comment]
Why did you decide to close this one? (not against it but asking to understand the reasons and alternatives)

**Comment by alexey-milovidov** [comment]
No visible progress in two years.

**Comment by alexey-milovidov** [comment]
We still have an intent to introduce ALTER PRIMARY KEY, though.

**Comment by alexey-milovidov** [comment]
> Alexey Milovidov, [20-07-2021 12:46]
Yes, as we discussed - new parts are written with different primary key, old parts are unchanged. There will be ranges of parts with different primary key. Parts can be merged only within these ranges. When doing SELECT, we collect all the ranges with different primary keys and apply KeyCondition separately. There can be multiple pipelines that will be processed independently.

**Pull request closed without merging**
