### PR TITLE
Address some usability issues with INTO OUTFILE usage.

### LINKED ISSUE #50707: Bad usability of exception messages when a file already exists in INTO OUTFILE
**Describe the issue**
```
milovidov-desktop :) SELECT * FROM numbers(10) INTO OUTFILE 'numbers.tsv'

SELECT *
FROM numbers(10)
INTO OUTFILE 'numbers.tsv'

Query id: 4512f761-2b36-4a25-9ccd-22982a17eb64

Ok.
Exception on client:
Code: 76. DB::Exception: Code: 76. DB::ErrnoException: Cannot open file numbers.tsv, errno: 17, strerror: File exists. (CANNOT_OPEN_FILE) (version 23.5.1.1). (CANNOT_OPEN_FILE)
```

1. It prints Ok, but then prints the exception message.
2. It prints `Code: 76.` and `Exception` twice.
3. It prints `CANNOT_OPEN_FILE` twice.
4. It does not suggest the usage of the `APPEND` syntax.

### PR DESCRIPTION
**Pull request by alekar**
Closes #50707. 

TODO

- [x] This still prints 'Ok.' and then throws exception because of where the check is run.
 
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
-  Suggest using `APPEND` or `TRUNCATE` for `INTO OUTFILE` when file exists.

### CODE REVIEW

**Comment by robot-ch-test-poll1** [comment]
This is an automated comment for commit 3f9ded7b13c8ecb4c7923a3409443f4491c92c9b with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/50950/3f9ded7b13c8ecb4c7923a3409443f4491c92c9b/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Comment by alekar** [comment]
```
Manass-MacBook-Pro.local :) SELECT * FROM numbers(10) INTO OUTFILE 'numbers.tsv'

SELECT *
FROM numbers(10)
INTO OUTFILE 'numbers.tsv'

Query id: 5290ec85-93de-41ea-b43e-d40d6533946f

Exception on client:
Code: 504. DB::Exception: File numbers.tsv exists, consider using APPEND or TRUNCATE. (FILE_ALREADY_EXISTS)
```

**Comment by evillique** [comment]
Stateless tests `02050_clickhouse_client_local_exception` and `02346_into_outfile_and_stdout` fail in the Fast test check ([report](https://s3.amazonaws.com/clickhouse-test-reports/50950/508e4906c08bf3e3c5a80335d5573cc38974b7e1/fast_test.html))

**Comment by alekar** [comment]
@evillique some of the changes needed to the tests are a result of moving the checks to before sending it to the server. He we don't catch and rethrow the exception as `LocalFormatError`. Should be fixed now.

**Review by evillique — APPROVED** [review]

**Comment by evillique** [comment]
Test failures are unrelated.

**Pull request merged**
