### PR TITLE
WITH FILL by sorting prefix

### PR DESCRIPTION
**Pull request by devcrafter**
### Changelog category (leave one):
- New Feature

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
`WITH FILL` modifier groups filling by sorting prefix. Controlled by `use_with_fill_by_sorting_prefix` setting (enabled by default). Related to https://github.com/ClickHouse/ClickHouse/issues/33203#issuecomment-1418736794.

### Documentation entry for user-facing changes

- [x] Documentation is written (mandatory for new features)

### CODE REVIEW

**Comment by robot-clickhouse-ci-1** [comment]
This is an automated comment for commit 0f9271a34979fe44a31e4a950a0823b4f3ff3338 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/49503/0f9271a34979fe44a31e4a950a0823b4f3ff3338/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Docs Check</td><td>Builds and tests the documentation</td><td>🟡 pending</td></tr>
</table>

**Comment by devcrafter** [comment]
@CurtizJ I want to add more tests and walkthrough the code one more time. But another pair of eyes already would be helpful

**Review by CurtizJ — COMMENTED** [review]
In general LGMT, but some strange segfault has been found in last CI check. However, I'm not sure that it's related to this PR.

**Comment by devcrafter** [comment]
Will check the crash [here](https://s3.amazonaws.com/clickhouse-test-reports/49503/e9c86527b0244c1094496d7242220b8cb53a7386/fast_test.html). Now will restart CI

**Pull request merged**
