### PR TITLE
Keeper imports incremental rehash data structure to support billions nodes

### PR DESCRIPTION
**Pull request by zhanglistar**
Changelog category (leave one):
- Performance Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
In the current implementation of  `SnapshotableHashTable`, the rehash process of `using IndexMap = HashMap<StringRef, Mapped>; IndexMap map;` can take about several seconds if there are ten millions elements in map, resulting an operation time out. 
The change is designing an incremental rehash hash table using two HashTable with robin hood hash table as inner data structure. robin hood hash table: https://github.com/martinus/robin-hood-hashing.

Effect: 
client command: `./utils/keeper-bench/keeper-bench --host=127.0.0.1:12183 -c 64 --generator=create_small_data`
It can insert billions of keys until running out of host memory.

master version:
operation time out at 30 millions nodes and commit process took 9s+.
Pasted Graphic 4

> Information about CI checks: https://clickhouse.tech/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by zhanglistar** [comment]
read:` ./utils/keeper-bench/keeper-bench --host=127.0.0.1:12183 -c 64 --generator=get_small_data`
new verion:
image

master version(7d01516202152c8d60d4fed6b72dad67357d337f):
image

**Comment by zhanglistar** [comment]
write: `./utils/keeper-bench/keeper-bench --host=127.0.0.1:12183 -c 64 --generator=create_small_data`
new version:
Pasted Graphic

master version:

**Comment by alesapin** [comment]
@kitaisreal maybe you can help me to review this PR.

**Comment by zhanglistar** [comment]
> 

@kitaisreal Thanks for your review. 
Yes I thought two level hash maps before, but it also have the long rehash problem, say one slot hash map is full and need to do rehash which copy all the elements to another bigger hash map, that could take long time if there are billions elements. 
So like redis, I design an incremental rehash data structure based on robin hood hash table. The rehash process is like this: if original hash table(say h0) is full, then reclaim a new hash table(say h1) with two capacity of h0, and insert elements to only h1, erase elements to h0 and h1, find will in h0 and h1. And in every operation, we try to move batch elements(say 100) from h0 to h1 until h0 is empty. The cost is that during rehash process, the operation time is a little longer than only on hash table. But we can always write to the incremental rehash data structure until host memory is running out. And there is no timed out operations occuring in the current implementation which may causes system untable.

**Comment by alexey-milovidov** [comment]
@kitaisreal Let's continue on this pull request...

**Comment by alexey-milovidov** [comment]
@kitaisreal One month passed without review, let's reassign.

**Comment by zhanglistar** [comment]
While I think maybe supporting billions of nodes is not a critical thing for now, So I close this PR first.

**Pull request closed without merging**
