### PR TITLE
Updated Brown University dataset example

### PR DESCRIPTION
**Pull request by DanRoscigno**
### Changelog category (leave one):

- Documentation (changelog entry is not required)

Please check query 3.5, I had this error:
```
DB::Exception: Expected ALL or DISTINCT in SelectWithUnion query, because setting (union_default_mode) is empty:
```

I edited query 3.5 and changed:
```
.
.
.
UNION
SELECT DISTINCT device_name,
       device_type,
       device_floor,
       'SUMMER'
```

to

```
UNION DISTINCT
SELECT DISTINCT device_name,
       device_type,
       device_floor,
       'SUMMER'
```

but I am not sure if I should have removed `DISTINCT` from the `SELECT` and made it:
```
UNION DISTINCT
SELECT  device_name,
       device_type,
       device_floor,
       'SUMMER'
```

### CODE REVIEW

**Comment by DanRoscigno** [comment]
Here is the result of query 3.5 (after I switched to UNION DISTINCT):
```sql
WITH temperature AS
    (
        SELECT
            dt,
            device_name,
            device_type,
            device_floor
        FROM
        (
            SELECT
                dt,
                hr,
                device_name,
                device_type,
                device_floor,
                AVG(event_value) AS temperature_hourly_avg
            FROM
            (
                SELECT
                    CAST(log_time, 'DATE') AS dt,
                    toHour(log_time) AS hr,
                    device_name,
                    device_type,
                    device_floor,
                    event_value
                FROM mgbench.logs3
                WHERE event_type = 'temperature'
            ) AS r
            GROUP BY
                dt,
                hr,
                device_name,
                device_type,
                device_floor
        ) AS s
        GROUP BY
            dt,
            device_name,
            device_type,
            device_floor
        HAVING (MAX(temperature_hourly_avg) - MIN(temperature_hourly_avg)) >= 25.
    )
SELECT DISTINCT
    device_name,
    device_type,
    device_floor,
    'WINTER'
FROM temperature
WHERE (dt >= toDate('2018-12-01')) AND (dt < toDate('2019-03-01'))
UNION DISTINCT
SELECT DISTINCT
    device_name,
    device_type,
    device_floor,
    'SUMMER'
FROM temperature
WHERE (dt >= toDate('2019-06-01')) AND (dt < toDate('2019-09-01'))

Query id: 3625080f-b462-4792-acb8-d6787749dbce

┌─device_name────┬─device_type─┬─device_floor─┬─'WINTER'─┐
│ front_left_1   │ door        │            1 │ SUMMER   │
│ balcony_5      │ door        │            5 │ SUMMER   │
│ balcony_3      │ door        │            3 │ SUMMER   │
│ front_center_1 │ door        │            1 │ SUMMER   │
│ front_right_1  │ door        │            1 │ SUMMER   │
└────────────────┴─────────────┴──────────────┴──────────┘
┌─device_name────┬─device_type─┬─device_floor─┬─'WINTER'─┐
│ balcony_5      │ door        │            5 │ WINTER   │
│ loading_dock_1 │ door        │            1 │ WINTER   │
│ balcony_3      │ door        │            3 │ WINTER   │
│ front_right_1  │ door        │            1 │ WINTER   │
│ front_left_1   │ door        │            1 │ WINTER   │
│ front_center_1 │ door        │            1 │ WINTER   │
└────────────────┴─────────────┴──────────────┴──────────┘
```

**Comment by alexey-milovidov** [comment]
@DanRoscigno 

I keep all the queries for the Brown University Benchmark unmodified.
This is needed to make the benchmark results 100% trustworthy: we run queries as is.

The `union_default_mode` for this benchmark is set to 'distinct', because it is how SQL standard works.

No need to add DISTINCT to the internal queries.

ClickHouse has `union_default_mode` to unspecified because most of the users tend to write UNION incorrectly (when they actually need UNION ALL). So, ClickHouse has more sane defaults than typical SQL DBMS.

**Comment by alexey-milovidov** [comment]
Here is the full disclosure of benchmark run: https://github.com/crottyan/mgbench/pull/8
Unfortunately, the author - Andrew Crotty @crottyan stopped to maintain it, so, I've made a fork:
https://github.com/alexey-milovidov/mgbench

We can put this fork into ClickHouse org.
The mgbench is quite good - the data and queries are realistic. Although the dataset size is very small, most of the queries run under 5ms, which makes the databases with in-memory indexes like Hyper in favor. It's good that ClickHouse is either on the first place or on the second place after Hyper in this benchmark.

**Review by alexey-milovidov — CHANGES_REQUESTED** [review]
.

**Comment by alexey-milovidov** [comment]
If we let to modify the queries and change the column types, we will be first with a huge margin. But it's not 100% fair :)

**Comment by DanRoscigno** [comment]
Thank you @alexey-milovidov 
 
> The `union_default_mode` for this benchmark is set to 'distinct', because it is how SQL standard works.

I do not see this in the page, I will add it.

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
> Unfortunately, the author - Andrew Crotty @crottyan stopped to maintain it

I withdraw my words, it continues to be maintained!

**Pull request merged**
