### PR TITLE
Remove peak memory usage from the final message in the client

### PR DESCRIPTION
**Pull request by alexey-milovidov**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by robot-clickhouse** [comment]
This is an automated comment for commit 3928f7ef460f4f4603ceaa065733ac0a7ebc4d16 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/52598/3928f7ef460f4f4603ceaa065733ac0a7ebc4d16/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Comment by den-crane** [comment]
@alexey-milovidov How do you check the memory usage for queries which runs for 10 minutes?

```
SELECT uniq(number) FROM numbers(100000000.) GROUP BY number % 11111 LIMIT 1


Peak memory usage (for query) 1.36 GiB.
```

**Comment by avadheshsengar** [comment]
Which version of clickhouse it is ?

**Comment by alexey-milovidov** [comment]
This is a fixup after https://github.com/ClickHouse/ClickHouse/pull/51946 that was not present in any of the releases.

**Comment by novikd** [comment]
@den-crane What's the problem to use `system.query_log`?

**Comment by den-crane** [comment]
@novikd you don't understand. Basically I execute 50% of queries under `sent_logs_level='debug'` because I want to see peak memory usage. 
Likely now I am I have that clickhouse-client which has this feature. I am happy now.

>What's the problem to use system.query_log?

Try to look into system.query_log instead of looking on query statistics after each query for elapsed time for example.

**Comment by siradjev** [comment]
I guess it needs to stay, unless the max memory usage of the query is always be printed out in the end as requested in #44805 ? Live statistics is not really a replacement for printout after query completion/cancellation.

**Pull request merged**
