### PR TITLE
doc: add PGO information

### PR DESCRIPTION
**Pull request by zamazan4ik**
### Changelog category (leave one):
- Documentation (changelog entry is not required)

### Documentation entry for user-facing changes

- [x] Documentation is written (mandatory for new features)

As discussed in https://github.com/ClickHouse/clickhouse-docs/issues/1392 with this PR I propose adding information about PGO results on ClickHouse to the documentation.

I added documentation only for the English language. Feel free to translate it into Russian and Chinese if necessary. If you think some wording or other things should be changed/rephrased/extended - please let me know.

Also, I have no experience with the ClickHouse documentation infrastructure so maybe I missed some stuff.

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]

**Comment by robot-clickhouse-ci-2** [comment]
This is an automated comment for commit e05f5ad5ac225eaaa2c3662c49182b1c581bfda5 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/52877/e05f5ad5ac225eaaa2c3662c49182b1c581bfda5/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Comment by alexey-milovidov** [comment]
Thank you!

Sorry for one unrelated question, but this could be interesting for someone who knows compiler-related tools. I have a pull request https://github.com/ClickHouse/ClickHouse/pull/34160 that has a big perspective - it will allow dynamic tracing and fault injection. But currently, the simple example does not work. Maybe you could help :)

**Comment by zamazan4ik** [comment]
To clarify - maybe I did something wrong in my PR. Right now the page with PGO is available on the site - https://clickhouse.com/docs/en/operations/optimizing-performance/profile-guided-optimization . But I cannot find the page in the sidebar, and the built-in search in the documentation also cannot find the page about PGO.

Did I miss something to do?

**Comment by alexey-milovidov** [comment]
Yes, I've also noticed it. Let's try to make it by analogy with other pages here:
Screenshot_20230802_131551

**Comment by zamazan4ik** [comment]
Is there a way to render the pages locally to check the results before the push? Or maybe I can check it somehow on CI before the merge to the master branch? Smth like `https://my_custom_branch.clickhouse.com/docs`. E.g. Vector has such an option: https://master.vector.dev/

**Pull request merged**
