### PR TITLE
Decrease default timeouts for S3 and HTTP requests

### PR DESCRIPTION
**Pull request by al13n321**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
* Decreased default timeouts for S3 from 30 seconds to 3 seconds, and for other HTTP from 180 seconds to 30 seconds.

Changes:
 * Use longer timeout for CompleteMultipartUploadRequest. This allows decreasing the main timeout without running into https://github.com/ClickHouse/ClickHouse/pull/42321
 * Decreased `url()` default timeout from 180 to 30 seconds.
 * Decreased S3 default `request_timeout_ms` from 30 to 3 seconds, for both S3 disks and S3 table function and storage.
 * Added setting `s3_request_timeout_ms`.

Tested manually by hacking minio to sleep when sending reply. (It was surprisingly easy: the code seems not too crazy, Go compiles pretty fast, and Go debugger seems nice too. Did you know you can ask GPT-4: "In minio, what source code file handles S3 GetObject requests?", and it knows the answer? How crazy is that!)

### CODE REVIEW

**Comment by robot-ch-test-poll** [comment]
This is an automated comment for commit 55fc46522237e24333b6433d76623439597510a0 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/51171/55fc46522237e24333b6433d76623439597510a0/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Comment by UnamedRus** [comment]
Need to confirm, that it will not affect https://github.com/ClickHouse/ClickHouse/pull/42321 issue

IE 'Complete Multipart Upload' can take loong time for other s3 implementations

**Comment by al13n321** [comment]
Ah, it was long for a reason, ok.

Then I guess we have to use different settings for different requests. Which makes sense to do anyway, but is inconvenient because settings are passed to S3 library when S3 client is created, and the same client can be used for different things. Rethinking.

**Comment by alexey-milovidov** [comment]
Connect timeout should be as low as 100ms (and ideally performed concurrently to multiple endpoints at once).
The timeout for receiving the full HTTP response can be set to a high value,
but the socket receive timeout should be low - not higher than one second for read requests, ideally starting from something like 100ms.

For the "complete multipart upload" requests, AWS S3 is avoiding socket timeout by sending whitespaces periodically, but other implementations may not do it.

**Comment by al13n321** [comment]
> For the "complete multipart upload" requests, AWS S3 is avoiding socket timeout by sending whitespaces periodically, but other implementations may not do it.

That's every 10 seconds in minio: https://github.com/minio/minio/pull/7198/files . I assume it's not much shorter in S3. So the CompleteMultipartUploadRequest HTTP request will need separate long receive timeout. That should be fine.

> 100ms

Do we want such aggressive timeouts by default for everyone, or should we set them low in configs in the cloud? I'd be afraid to go below 500ms in the public version because people may go cross-region or have slow internet connection.

Ideally we would have aggressive initial timeout, then exponentially increase it with retries. This is difficult without getting rid of the S3 library, because the library doesn't tell our HTTP client which attempt it is. And/or we can pick the timeout based on max latency of previous successful requests that are similar to this request (same domain and S3 API method?). This seems independent of getting rid of S3 library. Maybe I'll try this.

**Comment by alexey-milovidov** [comment]
It's unnecessary to set it as low by default - let's try it first...

**Comment by alexey-milovidov** [comment]
> Ideally we would have aggressive initial timeout, then exponentially increase it with retries.

Yes, this is what I expect as well :)

**Comment by alexey-milovidov** [comment]
I imagine we can use the S3 library for authentication, but then get the credentials, or the prepared HTTP request, and send it manually.

**Review by alexey-milovidov — APPROVED** [review]

**Comment by TimonSP** [comment]
> Decreased url() default timeout from 180 to 30 seconds.

It brings a lot of problem for us, sometime it is required to have long timeout here
use-cases are decribed here https://github.com/ClickHouse/clickhouse-java/issues/1550
also it is hard to reconfigure as far as can be changed only for default profile see https://github.com/ClickHouse/ClickHouse/issues/64731

**Pull request merged**
