### PR TITLE
Return passed number for numbers with MSB set in roundUpToPowerOfTwoOrZero()

### PR DESCRIPTION
**Pull request by azat**
Found with AST-based query fuzzer.

Changelog category (leave one):
- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Return passed number for numbers with MSB set in roundUpToPowerOfTwoOrZero()

Otherwise roundUpToPowerOfTwoOrZero() will return 0 for then, and this will cause 0 memory allocated and eventually SIGSEGV, like in [1].
    
  [1]: https://clickhouse-test-reports.s3.yandex.net/13201/5eaf39d3faf0abdd425cca9b7ee5778b06aad716/fuzzer/fuzzer.log#fail1

P.S. I've verified the callers and looks like the only place where the number can be enormously large is `PODArray` and after this patch it should fail with `CANNOT_ALLOCATE_MEMORY`/`MEMORY_LIMIT_EXCEEDED` instead of silently fail and fail with SIGSEGV after

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
> Yandex synchronization check

Fixed in #13238

**Review by alexey-milovidov — APPROVED** [review]
Also should add the limit on string size in `repeat` function
(we have similar limits in other functions).

Can be implemented in another PR.

**Comment by alexey-milovidov** [comment]
I have edited the code because there were no whitespaces around operators and it was difficult to read due to unclear operator precendence. https://github.com/ClickHouse/ClickHouse/pull/13234/commits/ae572c3a7e643837408bde5846cb50a1ff47e70a

**Comment by alexey-milovidov** [comment]
> test_adaptive_granularity/test.py::test_version_update_two_nodes

No good: #12508

**Comment by alexey-milovidov** [comment]
Performance test does not look good, need investigation.

**Comment by azat** [comment]
This patch should not affect this, let see:

> SELECT \'simdjson-12\', count() FROM zeros(1000000) WHERE NOT ignore(JSONExtractFloat(materialize(\'{"sparam":{"nested_1":"test_string","nested_2":"test_2"}, "nparam":8495, "fparam":{"nested_1":91.15,"nested_2":[334, 89.05, 1000.01]}, "bparam":false}\'), \'fparam\', \'nested_2\', -2))

`pthread_cond_timedwait (filtered by script)` +5%

> simdjson-7
> simdjson-5

same

Let's trigger perf tests one more time

**Comment by alexey-milovidov** [comment]
e823dd9 was wrong.

**Comment by azat** [comment]
>Performance — 3 errors, 1 too long, 3 faster, 1 slower, 241 unstable

3 errors, but I see only 2:

decimal_aggregates | decimal_aggregates-err.log:clickhouse_driver.errors.ServerException: Code: 407.
-- | --
decimal_aggregates | decimal_aggregates-err.log:DB::Exception: Decimal math overflow: While executing ConvertingAggregatedToChunksTransform. Stack trace:

1 too long, there are similar issues for other PRs (although the query is different, @akuzm are perf tests unstable or is it me overlooked?)
1 slower, also saw this in one PR

**Comment by alexey-milovidov** [comment]
The only slower test is just an outlier.

**Comment by alexey-milovidov** [comment]
Two integration test failures are unrelated but has to be investigated later:

test_adaptive_granularity/test.py::test_version_update_two_nodes | FAIL
test_version_update_after_mutation/test.py::test_mutate_and_upgrade | FAIL

**Comment by akuzm** [comment]
> > Performance — 3 errors, 1 too long, 3 faster, 1 slower, 241 unstable
> 
> 3 errors, but I see only 2:
> 
> decimal_aggregates	decimal_aggregates-err.log:clickhouse_driver.errors.ServerException: Code: 407.
> decimal_aggregates	decimal_aggregates-err.log:DB::Exception: Decimal math overflow: While executing ConvertingAggregatedToChunksTransform. Stack trace:
> 1 too long, there are similar issues for other PRs (although the query is different, @akuzm are perf tests unstable or is it me overlooked?)
> 1 slower, also saw this in one PR

This is some query from synthetic_hardware_benchmark that is too slow (it is a red cell in Test Times table). I probably have to add another table that lists all the errors, so that they are easier to find.

**Comment by azat** [comment]
>Also should add the limit on string size in repeat function

Already done in #13500

**Pull request merged**
