### PR TITLE
Add idempotent retries of updating the replica queue in ZooKeeper

### PR DESCRIPTION
**Pull request by ztlpn**

### CODE REVIEW

**Comment by silviucpp** [comment]
Hello,

Looking to this PR doesn't seems 100 % correct. Now we moved the ReplicationMergeTree to not use any longer dedicated threads per table and instead a pool of threads. 

And in this PR if I understand correctly it's inserted an infinite loop:

```
for (size_t num_tries = 0; ; ++num_tries)
```

Which blocks the thread until zookeper operation succeeds. I'm wonder if instead doing this you can schedule this operation in pool for later execution until completes

Silviu

**Comment by ztlpn** [comment]
@silviucpp yes you are right... The code will become much more convoluted though – we would need to save the fact that we must retry the ZooKeeper operation on the next iteration somewhere in the object state and then have two branches of code based on whether we should retry or not.

In fact the problem is present in a milder form for all blocking operations. E.g. if a thread is stuck waiting for a response from ZooKeeper (that could be tens of seconds), it doesn't do any useful work and just occupies a slot in the thread pool. That is why I am not a fan of using a thread pool for the replication tasks. It would work great if we converted all operations to async style, but that's a lot of work.

**Comment by silviucpp** [comment]
@ztlpn what we need to convert to async is the zookeeper interaction, from what I see it's the only one that can block the threads for long time

**Comment by alexey-milovidov** [comment]
Probably the simpliest solution is to mark queue as dirty and re-initialize it in next iteration.

**Comment by silviucpp** [comment]
Problem https://github.com/yandex/ClickHouse/issues/1546 seems not fixed by this patch

**Comment by ztlpn** [comment]
@alexey-milovidov good idea, will do.

@silviucpp yes, it is another bug. Still, it is a good thing that you have reviewed this patch :)

**Pull request merged**
