### PR TITLE
BLAKE3 hash function documentation

### PR DESCRIPTION
**Pull request by BoloniniD**
### Changelog category (leave one):
- Documentation (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Added BLAKE3 to hash-function list

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by BoloniniD** [comment]
Documentation for #33435 hash function

**Comment by alexey-milovidov** [comment]
One change is required, see Telegram.

**Review by rfraposa — APPROVED** [review]

**Comment by rfraposa** [comment]
Sorry! I didn't see Alexey's comment until after I merged the PR. I am reverting now

**Comment by alexey-milovidov** [comment]
@rfraposa This documentation is totally ok but it is about the feature that is still in development.

**Pull request merged**
