### PR TITLE
Support GROUP BY ALL

### LINKED ISSUE #37631: GROUP BY ALL
**Use case**

`GROUP BY ALL` is equivalent to listing all the SELECT-ed columns that are not expressions of the aggregate functions.

**Describe the solution you'd like**

Add it to the Parser and AST, then substitute the columns somewhere around ExpressionAnalyzer.

**Caveats**

Usual optimizations like removing injective functions and removing deterministic functions of other columns should work.

### PR DESCRIPTION
**Pull request by taofengliu**
### Changelog category (leave one):
- New Feature

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
close: #37631

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by taofengliu** [comment]
Can this PR be merged? @vdimir

**Comment by taofengliu** [comment]
@vdimir @alexey-milovidov Can I have some comments?

**Comment by taofengliu** [comment]
Ready for review

**Comment by taofengliu** [comment]
CI failure seems not caused by my changes, right?@vdimir

**Comment by alexey-milovidov** [comment]
Note: in presence of the `arrayJoin` function, the behavior is implementation defined.

**Comment by taofengliu** [comment]
> Note: in presence of the `arrayJoin` function, the behavior is implementation defined.

@alexey-milovidov Do you mean we need a special treatment for `arrayJoin` ? How to do that?

**Review by vdimir — COMMENTED** [review]
Probably it's better to implement it on top of the query tree https://github.com/ClickHouse/ClickHouse/pull/31796 (not merged yet). Sorry that I haven't checked it earlier. I assumed that it would be a small change in the parser. Still, it requires some context about what kinds of entities we have in select (column identifiers, functions, aggregate functions, etc.)

**Comment by taofengliu** [comment]
> Probably it's better to implement it on top of the query tree #31796 (not merged yet). Sorry that I haven't checked it earlier. I assumed that it would be a small change in the parser. Still, it requires some context about what kinds of entities we have in select (column identifiers, functions, aggregate functions, etc.)

So should I implement this feature on the basis of #31796，after it is merged? @vdimir

**Comment by alexey-milovidov** [comment]
> @alexey-milovidov Do you mean we need a special treatment for arrayJoin ? How to do that?

No, it's totally ok. The current implementation will GROUP BY the arguments of `arrayJoin` and this is ok.

**Comment by taofengliu** [comment]
So 
`SELECT substring(s, 1, 10), substring(concat(s,"string"), 1, count(b)) FROM table GROUP BY ALL` 
will expand as 
`SELECT substring(s, 1, 10), substring(concat(s,"string"), 1, count(b)) FROM table GROUP BY s` 
but not 
`SELECT substring(s, 1, 10), substring(concat(s,"string"), 1, count(b)) FROM table GROUP BY substring(s, 1, 10), concat(s,"string")`
right?
We only avoid extracting arguments from the functions when they don't contain aggregate functions inside, but still extracting when there are aggregate functions inside?
Do you think `SELECT substring(s, 1, 10), substring(concat(s,"string"), 1, count(b)) FROM table GROUP BY substring(s, 1, 10), concat(s,"string")` is better?
@alexey-milovidov

**Comment by taofengliu** [comment]
Updated. The current behavior is described in the document.
Does this suit your idea? @alexey-milovidov

**Comment by taofengliu** [comment]
I don't know why `02459_group_by_all`'s result differs with the reference I produced in my local environment.
The order of the first query results is different.

**Comment by taofengliu** [comment]
Is it necessary to modify the new added analyzer for GROUP BY ALL?

**Comment by alexey-milovidov** [comment]
Yes, we should add the support in Analyzer as well.
It should not be difficult. If there will be some difficulties, we will help!

**Comment by taofengliu** [comment]
Need to start CI. It is `waiting for status to be reported`@alexey-milovidov

**Comment by vdimir** [comment]
> Need to start CI

Done

**Comment by taofengliu** [comment]
Can't the CI start automatically after new commit?

**Comment by alexey-milovidov** [comment]
It should start automatically unless CI scripts are modified. Nevertheless, I've pushed the button.

**Comment by taofengliu** [comment]
Two queries failed in `AST Fuzzer` and led to unfinished CI:
`SELECT '', count(1048576) FROM ttl__fuzz_8 GROUP BY if((a % NULL) = NULL, today() - NULL, toDate((a % 1025) = NULL)) WITH CUBE WITH TOTALS;`
`SELECT count() > 0 FROM parallel_replicas;`

The first query also fails with the code in master branch using `allow_experimental_analyzer = 1`, so I guess it is not caused by my change.
The second query seems also not related with my change.

And I can not find more information about other failures.
Could you please have a look on my code and the failed tests?@alexey-milovidov

**Comment by vdimir** [comment]
> Could you please have a look on my code and the failed tests?

I'll check soon

**Comment by taofengliu** [comment]
`SELECT b, count('65535'), 3.4028234663852886e38 FROM group_by_all GROUP BY ALL WITH ROLLUP WITH TOTALS`
fails, but
`SELECT b, count('65535'), 3.4028234663852886e38 FROM group_by_all GROUP BY b WITH ROLLUP WITH TOTALS;`
also fails.

`SELECT substring(substring(a, c + NULL, NULL), 3, count(9223372036854775806)) FROM group_by_all__fuzz_46 GROUP BY ALL WITH TOTALS`
fails, but
`SELECT substring(substring(a, c + NULL, NULL), 3, count(9223372036854775806)) FROM group_by_all__fuzz_46 GROUP BY substring(a, c + NULL, NULL) WITH TOTALS`
also fails.

There are also some other failures like these.

**Comment by taofengliu** [comment]
Seems the same failure in `AST Fuzzer` as before, maybe not caused by my code.

**Comment by alexey-milovidov** [comment]
Yes, all fuzzers found this error. This is suspicious.

**Comment by taofengliu** [comment]
It seems the previous bugs found in fuzzers has been fixed.
But a new bug found in fuzzer and it is not caused by my code.

**Comment by alexey-milovidov** [comment]
I'm checking timeouts in debug tests: https://s3.amazonaws.com/clickhouse-test-reports/42265/66f101e451754e76a1ecfd4d518a1f55b6086eea/stateless_tests__debug__[2/5].html

One of the tests is very simple: `array_zip`. But it looks like throwing an exception took three minutes:
https://pastila.nl/?024a9586/fd2e9e2b67282aa36fdc0793524b1ca1

The reason might be in the enabled fsync_metadata option, and a randomized test for DDL queries running in parallel.
But it's unclear how better to avoid this issue:
- stop randomizing fsync_metadata setting;
- change disk type for runners?

**Comment by alexey-milovidov** [comment]
@Felixoid has changed the disk type from `gp2` to `gp3`, so it should be better.

**Comment by Felixoid** [comment]
Just in case, it will take some time to refresh all instances. All new instances will be with gp3

**Comment by alexey-milovidov** [comment]
@tavplubix About the messages with unexpected parts:
https://s3.amazonaws.com/clickhouse-test-reports/42265/66f101e451754e76a1ecfd4d518a1f55b6086eea/stress_test__debug_/bc_check_error_messages.txt
Should we wait for the change from @CheSema for better parts deletion?

**Review by alexey-milovidov — APPROVED** [review]

**Pull request merged**
