### PR TITLE
Use `--filter` to reduce checkout time

### PR DESCRIPTION
**Pull request by Felixoid**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Reduce checkout time and traffic by skipping blobs and trees, the idea is taken from https://github.blog/2020-12-21-get-up-to-speed-with-partial-clone-and-shallow-clone/

### CODE REVIEW

**Comment by robot-ch-test-poll1** [comment]
*This is an automated comment for commit ca5cbf7c6e31497c5e44471201bfd168c5a9759d with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/54857/ca5cbf7c6e31497c5e44471201bfd168c5a9759d/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>✅ success</td></tr>
<tbody>
</table>
</details>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>⏳ pending</td></tr>
<tbody>
</table>

**Comment by Felixoid** [comment]
Previous
image

After "fix"
image

Pathetic...

**Comment by Felixoid** [comment]
THere are still questions to performance tests, so I leave it for a night

**Comment by Felixoid** [comment]
There are some failed tests, but everything related (the whole PR + perf tests) work, so I am merging it after the builds are done

**Pull request merged**
