### PR TITLE
Update zstd to v1.5.0

### PR DESCRIPTION
**Pull request by Algunenano**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Update zstd to v1.5.0

Detailed description / Documentation draft:

Some quick numbers using `zstd_buffers`:

Before:
```bash
$ while true; do ./src/IO/tests/zstd_buffers; done
Writing done. Elapsed: 0.48 s., 164.97 MB/s
Reading done. Elapsed: 0.25 s., 316.82 MB/s
Writing done. Elapsed: 0.49 s., 160.66 MB/s
Reading done. Elapsed: 0.25 s., 316.77 MB/s
Writing done. Elapsed: 0.46 s., 171.20 MB/s
Reading done. Elapsed: 0.25 s., 317.26 MB/s
Writing done. Elapsed: 0.46 s., 171.27 MB/s
Reading done. Elapsed: 0.25 s., 313.80 MB/s
Writing done. Elapsed: 0.46 s., 170.76 MB/s
Reading done. Elapsed: 0.25 s., 314.39 MB/s
Writing done. Elapsed: 0.49 s., 160.28 MB/s
Reading done. Elapsed: 0.25 s., 317.85 MB/s
Writing done. Elapsed: 0.49 s., 160.01 MB/s
Reading done. Elapsed: 0.25 s., 317.37 MB/s
Writing done. Elapsed: 0.46 s., 170.56 MB/s
Reading done. Elapsed: 0.25 s., 317.49 MB/s
Writing done. Elapsed: 0.47 s., 169.36 MB/s
Reading done. Elapsed: 0.25 s., 317.42 MB/s
Writing done. Elapsed: 0.46 s., 169.87 MB/s
Reading done. Elapsed: 0.25 s., 317.91 MB/s
Writing done. Elapsed: 0.46 s., 169.95 MB/s
Reading done. Elapsed: 0.25 s., 317.43 MB/s
Writing done. Elapsed: 0.50 s., 157.39 MB/s
Reading done. Elapsed: 0.25 s., 317.66 MB/s
Writing done. Elapsed: 0.46 s., 169.80 MB/s
Reading done. Elapsed: 0.25 s., 316.74 MB/s
Writing done. Elapsed: 0.47 s., 169.57 MB/s
Reading done. Elapsed: 0.25 s., 313.84 MB/s
Writing done. Elapsed: 0.47 s., 168.08 MB/s
Reading done. Elapsed: 0.25 s., 313.79 MB/s
Writing done. Elapsed: 0.47 s., 168.99 MB/s
Reading done. Elapsed: 0.25 s., 315.68 MB/s
Writing done. Elapsed: 0.46 s., 171.22 MB/s
Reading done. Elapsed: 0.25 s., 317.09 MB/s
Writing done. Elapsed: 0.46 s., 171.06 MB/s
Reading done. Elapsed: 0.25 s., 317.60 MB/s
Writing done. Elapsed: 0.46 s., 170.91 MB/s
Reading done. Elapsed: 0.25 s., 317.35 MB/s
Writing done. Elapsed: 0.46 s., 171.10 MB/s
Reading done. Elapsed: 0.25 s., 317.30 MB/s
Writing done. Elapsed: 0.49 s., 160.00 MB/s
Reading done. Elapsed: 0.25 s., 314.62 MB/s
Writing done. Elapsed: 0.47 s., 168.49 MB/s
Reading done. Elapsed: 0.25 s., 317.50 MB/s
```

Max read: 317.85  MB/s
Max write: 171.22 MB/s

Rebuild libzstd.so:
```
$ ldd ./src/IO/tests/zstd_buffers | grep zstd
        libzstd.so => /mnt/ch/ClickHouse/build_clion/contrib/zstd-cmake/libzstd.so (0x00007fc8ff85c000)
$ ninja contrib/zstd-cmake/libzstd.so
```

After:
```bash
$ while true; do ./src/IO/tests/zstd_buffers; done
Writing done. Elapsed: 0.49 s., 162.39 MB/s
Reading done. Elapsed: 0.23 s., 340.44 MB/s
Writing done. Elapsed: 0.49 s., 160.95 MB/s
Reading done. Elapsed: 0.23 s., 343.83 MB/s
Writing done. Elapsed: 0.49 s., 161.15 MB/s
Reading done. Elapsed: 0.23 s., 342.01 MB/s
Writing done. Elapsed: 0.46 s., 170.04 MB/s
Reading done. Elapsed: 0.23 s., 342.01 MB/s
Writing done. Elapsed: 0.46 s., 170.40 MB/s
Reading done. Elapsed: 0.23 s., 341.92 MB/s
Writing done. Elapsed: 0.46 s., 171.34 MB/s
Reading done. Elapsed: 0.23 s., 343.60 MB/s
Writing done. Elapsed: 0.46 s., 170.88 MB/s
Reading done. Elapsed: 0.23 s., 343.54 MB/s
Writing done. Elapsed: 0.50 s., 157.04 MB/s
Reading done. Elapsed: 0.23 s., 343.80 MB/s
Writing done. Elapsed: 0.46 s., 170.34 MB/s
Reading done. Elapsed: 0.23 s., 343.81 MB/s
Writing done. Elapsed: 0.46 s., 170.44 MB/s
Reading done. Elapsed: 0.23 s., 343.22 MB/s
Writing done. Elapsed: 0.46 s., 171.03 MB/s
Reading done. Elapsed: 0.23 s., 343.15 MB/s
Writing done. Elapsed: 0.46 s., 170.03 MB/s
Reading done. Elapsed: 0.23 s., 343.00 MB/s
Writing done. Elapsed: 0.46 s., 170.27 MB/s
Reading done. Elapsed: 0.23 s., 343.17 MB/s
```

Max read: 343.83 MB/s
Max write: 171.34 MB/s

Similar writing speed. 8-10% better reading speed.

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
Thank you! But the calculation looks wrong.

```
Max read: 317.85 MB/s
Max write: 343.83 MB/s
```

I did not believe in two times performance improvement of writes and checked manually all the rows in "after":
```
Writing done. Elapsed: 0.49 s., 162.39 MB/s
Writing done. Elapsed: 0.49 s., 160.95 MB/s
Writing done. Elapsed: 0.49 s., 161.15 MB/s
Writing done. Elapsed: 0.46 s., 170.04 MB/s
Writing done. Elapsed: 0.46 s., 170.40 MB/s
Writing done. Elapsed: 0.46 s., 171.34 MB/s
Writing done. Elapsed: 0.46 s., 170.88 MB/s
Writing done. Elapsed: 0.50 s., 157.04 MB/s
Writing done. Elapsed: 0.46 s., 170.34 MB/s
Writing done. Elapsed: 0.46 s., 170.44 MB/s
Writing done. Elapsed: 0.46 s., 171.03 MB/s
Writing done. Elapsed: 0.46 s., 170.03 MB/s
Writing done. Elapsed: 0.46 s., 170.27 MB/s
```

Max is 171.34 MB/s. (Before: Max write: 171.22 MB/s)

**Comment by alexey-milovidov** [comment]
Nevertheless, it is good to merge :)

**Comment by alexey-milovidov** [comment]
Ok, I see this is just a copy-paste error. Should read as:

Max read: 343.83 MB/s
Max write: 171.34 MB/s

**Comment by alexey-milovidov** [comment]
8-10% better reading speed is impressive.

**Comment by Algunenano** [comment]
> Ok, I see this is just a copy-paste error. Should read as:
> Max read: 343.83 MB/s
> Max write: 171.34 MB/s

Yes, sorry. I'll edit the comment  for any future readers. The only improvement (in this test) is on reading speed.

**Pull request merged**
