### PR TITLE
Unconditionally convert `system` database to `Atomic`

### PR DESCRIPTION
**Pull request by tavplubix**
### Changelog category (leave one):
- Backward Incompatible Change

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
If `system` database has `Ordinary` engine, it will be automatically converted to `Atomic` on server startup even if `allow_deprecated_database_ordinary` was enabled.

### CODE REVIEW

**Comment by robot-ch-test-poll2** [comment]
This is an automated comment for commit f02607959f494a9e4f63ab590836a3a2f2aa54eb with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/54374/f02607959f494a9e4f63ab590836a3a2f2aa54eb/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
@tavplubix the changes are good, but the tests have failed.

**Comment by alexey-milovidov** [comment]
@tavplubix it failed.

**Comment by alexey-milovidov** [comment]
Upgrade check has failed.

**Comment by filimonov** [comment]
right now system database is not upgraded to Atomic even if convert_ordinary_to_atomic flag is set (which is silly) but  allow_deprecated_database_ordinary = 1.

**Comment by filimonov** [comment]
Related https://github.com/ClickHouse/ClickHouse/pull/39933

**Pull request closed without merging**
