### PR TITLE
Cherry pick #55336 to 23.8: Review #51946 and partially revert it

### PR DESCRIPTION
**Pull request by robot-ch-test-poll3**
Original pull-request #55336

This pull-request is a first step of an automated backporting.
It contains changes like after calling a local command `git cherry-pick`.
If you intend to continue backporting this changes, then resolve all conflicts if any.
Otherwise, if you do not want to backport them, then just close this pull-request.

The check results does not matter at this step - you can safely ignore them.

### Note

This pull-request will be merged automatically as it reaches the mergeable state, **do not merge it manually**.

### If the PR was closed and then reopened

If it stuck, check https://github.com/ClickHouse/ClickHouse/pull/55336 for `pr-backports-created` and delete it if necessary. Manually merging will do nothing, since `pr-backports-created` prevents the original PR https://github.com/ClickHouse/ClickHouse/pull/55336 from being processed.

If you want to recreate the PR: delete the `pr-cherrypick` label and delete this branch.
You may also need to delete the `pr-backports-created` label from the original PR.

### CODE REVIEW

**Comment by robot-ch-test-poll4** [comment]
Dear @alexey-milovidov, the PR is not updated for 1d0h50m35s. Please, either resolve the conflicts, or close it to finish the backport process of #55336

**Comment by robot-clickhouse-ci-2** [comment]
Dear @alexey-milovidov, the PR is not updated for 1d0h0m53s. Please, either resolve the conflicts, or close it to finish the backport process of #55336

**Comment by robot-ch-test-poll1** [comment]
Dear @alexey-milovidov, the PR is not updated for 1d0h0m14s. Please, either resolve the conflicts, or close it to finish the backport process of #55336

**Comment by bkuschel** [comment]
@alexey-milovidov any change we could get this merged?

**Comment by robot-ch-test-poll1** [comment]
Dear @alexey-milovidov, the PR is not updated for 1d0h56m52s. Please, either resolve the conflicts, or close it to finish the backport process of #55336

**Comment by robot-clickhouse** [comment]
Dear @alexey-milovidov, the PR is not updated for 1d0h1m28s. Please, either resolve the conflicts, or close it to finish the backport process of #55336

**Comment by robot-ch-test-poll1** [comment]
Dear @alexey-milovidov, the PR is not updated for 1d1h2m4s. Please, either resolve the conflicts, or close it to finish the backport process of #55336

**Comment by robot-ch-test-poll3** [comment]
Dear @alexey-milovidov, the PR is not updated for 1d0h55m50s. Please, either resolve the conflicts, or close it to finish the backport process of #55336

**Comment by robot-clickhouse-ci-2** [comment]
Dear @alexey-milovidov, the PR is not updated for 1d0h47m55s. Please, either resolve the conflicts, or close it to finish the backport process of #55336

**Comment by robot-clickhouse** [comment]
Dear @alexey-milovidov, the PR is not updated for 1d0h1m48s. Please, either resolve the conflicts, or close it to finish the backport process of #55336

**Comment by robot-ch-test-poll4** [comment]
Dear @alexey-milovidov, the PR is not updated for 1d1h1m53s. Please, either resolve the conflicts, or close it to finish the backport process of #55336

**Comment by robot-ch-test-poll** [comment]
Dear @alexey-milovidov, the PR is not updated for 1d0h58m3s. Please, either resolve the conflicts, or close it to finish the backport process of #55336

**Comment by robot-ch-test-poll3** [comment]
Dear @alexey-milovidov, the PR is not updated for 1d0h58m18s. Please, either resolve the conflicts, or close it to finish the backport process of #55336

**Comment by robot-clickhouse-ci-2** [comment]
Dear @alexey-milovidov, the PR is not updated for 1d0h0m51s. Please, either resolve the conflicts, or close it to finish the backport process of #55336

**Comment by alexey-milovidov** [comment]
@den-crane, this is an example of why you shouldn't so aggressively insist on merging https://www.linkedin.com/feed/update/urn:li:activity:7090076204552065024/

**Pull request closed without merging**
