### PR TITLE
Fix: USearch deserialize

### PR DESCRIPTION
**Pull request by davvard**
### Changelog category:
- Not For Changelog

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]

**Comment by robot-ch-test-poll4** [comment]
This is an automated comment for commit 9190fb2ba337ccd802dfa80562912fe3992e68b3 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/53876/9190fb2ba337ccd802dfa80562912fe3992e68b3/ci_running.html)
The overall status of the commit is 🔴 failure

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🔴 failure</td></tr>
</table>

**Comment by skeptrunedev** [comment]
Excited to test this :rocket:

**Comment by rschu1ze** [comment]
The undefined behavior sanitizer (ubsan) complains in the AST Fuzzer CI check ([here](https://s3.amazonaws.com/clickhouse-test-reports/53876/4c78c088472b0033bf6bf380ebf52b797bf820f9/fuzzer_astfuzzerubsan/report.html), check file "server.log.zst"):

```
/build/contrib/usearch/include/usearch/index.hpp:860:21: runtime error: null pointer passed as argument 1, which is declared to never be null
/build/cmake/linux/../../contrib/sysroot/linux-x86_64/x86_64-linux-gnu/libc/usr/include/string.h:60:62: note: nonnull attribute specified here

    #0 0x563c31e817d3 in unum::usearch::growing_hash_set_gt<unsigned int, unum::usearch::hash_gt<unsigned int>, unum::usearch::aligned_allocator_gt<char, 64ul>>::clear() build_docker/./contrib/usearch/include/usearch/index.hpp:860:9
    #1 0x563c31e817d3 in unsigned long unum::usearch::index_gt<float, unsigned long, unsigned int, unum::usearch::aligned_allocator_gt<char, 64ul>, unum::usearch::memory_mapping_allocator_gt<64ul>>::search_for_one_<char const*&, unum::usearch::index_dense_gt<unsigned long,
    > unsigned int>::metric_proxy_t&, unum::usearch::dummy_prefetch_t&>(char const*&, unum::usearch::index_dense_gt<unsigned long, unsigned int>::metric_proxy_t&, unum::usearch::dummy_prefetch_t&, unsigned long, short, short, unum::usearch::index_gt<float, unsigned long,
    > unsigned int, unum::usearch::aligned_allocator_gt<char, 64ul>, unum::usearch::memory_mapping_allocator_gt<64ul>>::context_t&) const build_docker/./contrib/usearch/include/usearch/index.hpp:3321:16
    #2 0x563c31e9a53f in void unum::usearch::index_gt<float, unsigned long, unsigned int, unum::usearch::aligned_allocator_gt<char, 64ul>, unum::usearch::memory_mapping_allocator_gt<64ul>>::connect_node_across_levels_<char const*&, unum::usearch::index_dense_gt<unsigned long,
    > unsigned int>::metric_proxy_t&, unum::usearch::dummy_prefetch_t&>(char const*&, unum::usearch::index_dense_gt<unsigned long, unsigned int>::metric_proxy_t&, unum::usearch::dummy_prefetch_t&, unsigned long, unsigned long, short, short, unum::usearch::index_update_config_t
    > const&, unum::usearch::index_gt<float, unsigned long, unsigned int, unum::usearch::aligned_allocator_gt<char, 64ul>, unum::usearch::memory_mapping_allocator_gt<64ul>>::context_t&) build_docker/./contrib/usearch/include/usearch/index.hpp:3165:36
    #3 0x563c31e9a045 in unum::usearch::index_gt<float, unsigned long, unsigned int, unum::usearch::aligned_allocator_gt<char, 64ul>, unum::usearch::memory_mapping_allocator_gt<64ul>>::add_result_t unum::usearch::index_gt<float, unsigned long, unsigned int, unum::usearch::
    > aligned_allocator_gt<char, 64ul>, unum::usearch::memory_mapping_allocator_gt<64ul>>::add<char const*&, unum::usearch::index_dense_gt<unsigned long, unsigned int>::metric_proxy_t&, unum::usearch::index_gt<float, unsigned long, unsigned int, unum::usearch::
    > aligned_allocator_gt<char, 64ul>, unum::usearch::memory_mapping_allocator_gt<64ul>>::add_result_t unum::usearch::index_dense_gt<unsigned long, unsigned int>::add_<float>(unsigned long, float const*, unsigned long, bool, std::__1::function<bool (char const*, unsigned long,
    > char*)> const&)::'lambda'(unum::usearch::member_ref_gt<unsigned long>)&, unum::usearch::dummy_prefetch_t>(unsigned long, float&&, unum::usearch::index_dense_gt<unsigned long, unsigned int>::metric_proxy_t&, unum::usearch::index_update_config_t, unum::usearch::
    > index_gt<float, unsigned long, unsigned int, unum::usearch::aligned_allocator_gt<char, 64ul>, unum::usearch::memory_mapping_allocator_gt<64ul>>::add_result_t unum::usearch::index_dense_gt<unsigned long, unsigned int>::add_<float>(unsigned long, float const*, unsigned
    > long, bool, std::__1::function<bool (char const*, unsigned long, char*)> const&)::'lambda'(unum::usearch::member_ref_gt<unsigned long>)&, unum::usearch::dummy_prefetch_t&&) build_docker/./contrib/usearch/include/usearch/index.hpp:2340:9
    #4 0x563c31e99350 in unum::usearch::index_gt<float, unsigned long, unsigned int, unum::usearch::aligned_allocator_gt<char, 64ul>, unum::usearch::memory_mapping_allocator_gt<64ul>>::add_result_t unum::usearch::index_dense_gt<unsigned long, unsigned int>::add_<float>(unsigned
    > long, float const*, unsigned long, bool, std::__1::function<bool (char const*, unsigned long, char*)> const&) build_docker/./contrib/usearch/include/usearch/index_dense.hpp:1710:16
    #5 0x563c31e9748f in unum::usearch::index_dense_gt<unsigned long, unsigned int>::add(unsigned long, float const*, unsigned long, bool) build_docker/./contrib/usearch/include/usearch/index_dense.hpp:589:129
    #6 0x563c31e9748f in DB::MergeTreeIndexAggregatorUSearch<(unum::usearch::metric_kind_t)101>::update(DB::Block const&, unsigned long*, unsigned long) build_docker/./src/Storages/MergeTree/MergeTreeIndexUSearch.cpp:171:34
    #7 0x563c31d77016 in DB::MergeTreeDataPartWriterOnDisk::calculateAndSerializeSkipIndices(DB::Block const&, std::__1::vector<DB::Granule, std::__1::allocator<DB::Granule>> const&) build_docker/./src/Storages/MergeTree/MergeTreeDataPartWriterOnDisk.cpp:326:42
```

This doesn't exactly seem related to this PR but it would need to be fixed anyways, otherwise the same error will show up in other PRs's tests.

@davvard: Like to check? Thanks!

**Comment by ashvardanian** [comment]
@rschu1ze, good catch! I have released a new version that fixes this issue. `cppreference` has no mention of `nonnull` attribute. I guess it depends on the specific version of LibC used. Please fetch v2.0.2. Thanks!

**Pull request merged**
