### PR TITLE
Add system.projections table

### PR DESCRIPTION
**Pull request by jrdi**
### Changelog category (leave one):
- New Feature

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Adding `system.projections` table to track available projections.

### Documentation entry for user-facing changes

- [x] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Run only fuzzers related jobs (libFuzzer fuzzers, AST fuzzers, etc.)
- [ ]  Exclude: AST fuzzers
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-ch-test-poll1** [comment]
*This is an automated comment for commit cf58ce217a34296c7e3332e0fe147f51fb885959 with description of existing statuses. It's updated for the latest CI running*

[❌ Click here](https://s3.amazonaws.com/clickhouse-test-reports/68901/cf58ce217a34296c7e3332e0fe147f51fb885959/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Style check</td><td>Runs a set of checks to keep the code style clean. If some of tests failed, see the related log from the report</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/68901/cf58ce217a34296c7e3332e0fe147f51fb885959/style_check.html">❌ failure</a></td></tr>
<tbody>
</table>

**Comment by jrdi** [comment]
Thanks for the comments @kssenii. They are already fixed.

The only tests failing are `Performance Comparison (release) [1/4]`, which is unrelated to this PR changes.

**Review by kssenii — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
@jrdi @kssenii It's inconsistent that `system.tables` has information about table size in rows/bytes, while `system.projections` does not.

**Comment by jrdi** [comment]
> @jrdi @kssenii It's inconsistent that `system.tables` has information about table size in rows/bytes, while `system.projections` does not.

I thought it was not very relevant for the purpose of this table. I can add the extra information.

**Comment by alexey-milovidov** [comment]
@jrdi, thanks! Yes, it will be useful in practice and consistent with system.tables.

**Pull request merged**
