### PR TITLE
Stateless test to validate projections work after attach

### PR DESCRIPTION
**Pull request by arthurpassos**
### Changelog category (leave one):
- Build/Testing/Packaging Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Add test that validates projections still work after attach partition

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by arthurpassos** [comment]
`02888_attach_partition_from_different_tables` already validates the projections must match

**Comment by robot-clickhouse** [comment]
*This is an automated comment for commit ae9765244b1fd7dfcdc462666ea5084d52bbdd58 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/60415/ae9765244b1fd7dfcdc462666ea5084d52bbdd58/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/60415/ae9765244b1fd7dfcdc462666ea5084d52bbdd58/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Comment by arthurpassos** [comment]
> * `Stateless tests (release) `: Should be fixed in master now.
> * `Stateless tests (release, analyzer, s3, DatabaseReplicated) [3/4]` -> Related to the new test and the analyzer

MIssed that failure, any ideas on how to fix this?

> 2024-02-27 15:59:21 -Expression ((Projection + Before ORDER BY))
2024-02-27 15:59:21 +Expression ((Project names + Projection))
2024-02-27 15:59:21    Filter
2024-02-27 15:59:21      ReadFromMergeTree (user_name_projection)

**Comment by Algunenano** [comment]
If both results are correct (haven't checked but they appear to be ok), then it's best to add both queries individually: one with `allow_experimental_analyzer=0` and one with `allow_experimental_analyzer=1`.

**Comment by Algunenano** [comment]
Test

**Pull request merged**
