### PR TITLE
SYNTAX_ERROR instead of BAD_ARGUMENTS on no_password among other authentication types

### PR DESCRIPTION
**Pull request by arthurpassos**
**OLD**

```
arthur :) CREATE USER user2 IDENTIFIED WITH plaintext_password by '1', no_password;

CREATE USER user2 IDENTIFIED WITH plaintext_password BY '1' no_password

Query id: bb84a68c-29bb-4f7d-bcf3-5dd79a32d742


Elapsed: 0.261 sec. 

Received exception from server (version 24.11.1):
Code: 36. DB::Exception: Received from localhost:9000. DB::Exception: Authentication method 'no_password' cannot co-exist with other authentication methods. (BAD_ARGUMENTS)
```

**NEW**

```
arthur :) CREATE USER user2 IDENTIFIED WITH plaintext_password by '1', no_password;

CREATE USER user2 IDENTIFIED WITH plaintext_password BY '1' no_password

Query id: 4042b576-dfad-4aa9-ad36-791238a636c4


Elapsed: 0.342 sec. 

Received exception from server (version 24.11.1):
Code: 62. DB::Exception: Received from localhost:9000. DB::Exception: Syntax error: failed at position 62 ('no_password'): no_password;. Expected one of: PLAINTEXT_PASSWORD, SHA256_PASSWORD, DOUBLE_SHA1_PASSWORD, LDAP, KERBEROS, SSL_CERTIFICATE, BCRYPT_PASSWORD, SSH_KEY, HTTP, JWT, SHA256_HASH, DOUBLE_SHA1_HASH, BCRYPT_HASH, BY, end of query. (SYNTAX_ERROR)

```
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
More consistent exception message when parsing no_password authentication type among other authentication methods

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Run only fuzzers related jobs (libFuzzer fuzzers, AST fuzzers, etc.)
- [ ]  Exclude: AST fuzzers
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by arthurpassos** [comment]
I ran the 03174_multi_auth tests locally, all green

**Comment by robot-ch-test-poll1** [comment]
*This is an automated comment for commit 139e2d4b1ea7ed84f82fb5d513d3b2820408c4d6 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/71783/139e2d4b1ea7ed84f82fb5d513d3b2820408c4d6/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/d38bd0df0aa277f4ec33b58f6832e45de596525c/docs_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Comment by pufit** [comment]
Why though? The previous exception message was nice, and you could clearly understand the problem.

**Comment by arthurpassos** [comment]
> Why though? The previous exception message was nice, and you could clearly understand the problem.

Consistency, but I don't have a strong opinion.

I was writing a blog article about the feature and realized sometimes `SYNTAX_ERRORR` is thrown, and sometimes `BAD_ARGUMENTS`.

I am ok with closing this PR if you feel it's better the way it is right now

**Pull request closed without merging**
