### PR TITLE
Fix `Unexpected merged part intersects drop range`

### PR DESCRIPTION
**Pull request by alesapin**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix a rare bug in `DROP PART` which can lead to the error `Unexpected merged part intersects drop range`.

### CODE REVIEW

**Comment by alesapin** [comment]
Example https://clickhouse-test-reports.s3.yandex.net/27680/1a3b72fa09b63be64e6e3ff734279fd01997ba33/functional_stateless_tests_(debug).html#fail1

**Review by tavplubix — APPROVED** [review]

**Comment by alesapin** [comment]
For an unknown reason, the table drop query hung. The only message in logs is:
```
2021.08.18 14:53:22.419145 [ 19048 ] {} <Trace> HTTPCommon: Failed communicating with d1c6e00f4c42 with error 'Received error from remote server /?endpoint=DataPartsExchange%3A%2Ftest%2F01154_move_partition_long_test_b7sdwo%2Fdst%2Freplicas%2F2&part=2_302_302_0&client_protocol_version=7&compress=false. HTTP status code: 500 Internal Server Error, body: Code: 232. DB::Exception: No part 2_302_302_0 in table. (NO_SUCH_DATA_PART), Stack trace (when copying this message, always include the lines below):
```
So, it's also a bug, but another bug.

**Comment by alesapin** [comment]
> For an unknown reason in `Functional stateless tests (ubsan) `, the table drop query hung. The only message in logs is:
> 
> ```
> 2021.08.18 14:53:22.419145 [ 19048 ] {} <Trace> HTTPCommon: Failed communicating with d1c6e00f4c42 with error 'Received error from remote server /?endpoint=DataPartsExchange%3A%2Ftest%2F01154_move_partition_long_test_b7sdwo%2Fdst%2Freplicas%2F2&part=2_302_302_0&client_protocol_version=7&compress=false. HTTP status code: 500 Internal Server Error, body: Code: 232. DB::Exception: No part 2_302_302_0 in table. (NO_SUCH_DATA_PART), Stack trace (when copying this message, always include the lines below):
> ```
> 
> So, it's also a bug, but another bug.

"Some replace ranges may stuck..."

**Comment by alesapin** [comment]
Intergration 
```
=================================== FAILURES ===================================
_______________________ test_simple_crud_requests[False] _______________________
[gw2] linux -- Python 3.8.10 /usr/bin/python3

started_cluster = <helpers.cluster.ClickHouseCluster object at 0x7f6f9e1003d0>
create_snapshots = False

    @pytest.mark.parametrize(
        ('create_snapshots'),
        [
            True, False
        ]
    )
    def test_simple_crud_requests(started_cluster, create_snapshots):
        restart_and_clear_zookeeper()
    
>       genuine_connection = get_genuine_zk()

test_keeper_zookeeper_converter/test.py:137: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
test_keeper_zookeeper_converter/test.py:70: in get_genuine_zk
    _genuine_zk_instance.start()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <kazoo.client.KazooClient object at 0x7f6f9c1c1670>, timeout = 15

    def start(self, timeout=15):
        """Initiate connection to ZK.
    
        :param timeout: Time in seconds to wait for connection to
                        succeed.
        :raises: :attr:`~kazoo.interfaces.IHandler.timeout_exception`
                 if the connection wasn't established within `timeout`
                 seconds.
    
        """
        event = self.start_async()
        event.wait(timeout=timeout)
        if not self.connected:
            # We time-out, ensure we are disconnected
            self.stop()
            self.close()
>           raise self.handler.timeout_exception("Connection time-out")
E           kazoo.handlers.threading.KazooTimeoutError: Connection time-out
```

**Pull request merged**
