### PR TITLE
Add a setting to specify s3 disk is read only.

### PR DESCRIPTION
**Pull request by bianpengyuan**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Added a new setting `readonly` which can be used to specify a s3 disk is read only. It can be useful to create a table with read only `s3_plain` type disk.

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by robot-ch-test-poll4** [comment]
*This is an automated comment for commit 32816d7e7ee1f424b42f7692652e1cb62555c0a8 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/57977/32816d7e7ee1f424b42f7692652e1cb62555c0a8/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td><a href="https://github.com/ClickHouse/ClickHouse/actions/runs/7243528680">✅ success</a></td></tr>
<tbody>
</table>
</details>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/57977/32816d7e7ee1f424b42f7692652e1cb62555c0a8/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Comment by bianpengyuan** [comment]
@alexey-milovidov can we merge this?

**Comment by alexey-milovidov** [comment]
Ok. I have renamed it from `s3_read_only` to `readonly`.
Removed `s3_`, because it is inside the options for s3, do it is redundant, and other options do not have this prefix.
Imagine tomorrow we will add it for Azure, and it would be nice if the option were named in the same way.
Renamed `read_only` to `readonly` because we have other contexts like query-level settings or RBAC, where readonly is written this way.
There are no tests. I am thinking - would it be alright to merge without tests...

**Comment by alexey-milovidov** [comment]
We can add a test. We will need to create a bucket in Minio, create a readonly role and check that then the table is created.
Check other integration tests that use Minio.

**Comment by bianpengyuan** [comment]
> We can add a test. We will need to create a bucket in Minio, create a readonly role and check that then the table is created. Check other integration tests that use Minio.

@alexey-milovidov I am trying to add an integration test, but I don't know how to generate test data in s3 which you can use `s3_plain` disk to attach with. Could you give me some pointer? Thanks!

**Comment by bianpengyuan** [comment]
> Create a MergeTree table, then copy its contents on disk to S3.

I am having a hard time to make this work. I added a WIP test here: https://github.com/ClickHouse/ClickHouse/pull/57977/files#diff-ddff13e969a22d1be4f913ae946c7e7846b3be463285605693ade27d917111f1. Problem is that when I attach table with copied merge tree data, there is no data part can be found. For some reason, when disk is loading, it only loads format version file, but not data part folder here: https://github.com/ClickHouse/ClickHouse/blob/85b149395a31d674729089438b518e329e871341/src/Storages/MergeTree/MergeTreeData.cpp#L1673

Are we sure that this approach works, or I am missing something? I compared with the working example, looks like we don't have `.index` file in the mergetree folder.. Could that be the reason?

**Comment by alexey-milovidov** [comment]
There are `web` and `s3_plain` disk types, and they are different.

The `s3_plain` disk type does not require any extra files; it reflects the directory structure one-to-one, but it requires that the underlying storage supports the "list directory" operation.

The `web` disk type does not expect that the underlying storage supports the "list directory" operation; instead, it makes it available using extra `.index` files.

> looks like we don't have .index file in the mergetree folder.

So, s3_plain does not need `.index` files.

**Comment by bianpengyuan** [comment]
Thanks @alexey-milovidov for the guidance! I make the integration test work, which is basically the flow we'd like to have. Problem is that [minio python library](https://min.io/docs/minio/linux/developers/python/API.html#) does not support adding new user, so it seems not possible to really test access bucket with a readonly user.. Let me know if the current test is good enough or we should explore how to make it really read only.

**Review by alexey-milovidov — APPROVED** [review]
I think it's ok, let's keep the test as is.

The style check has failed due to Python's "black" formatter - it is a small annoyance, just run `black .` near the code.

**Pull request merged**
