### PR TITLE
Remove duplicate_order_by_and_distinct optimization

### PR DESCRIPTION
**Pull request by devcrafter**
Remove `duplicate_order_by_and_distinct` optimization, - it was replaced by `remove_redundant_distinct` and `remove_redundant_sorting` optimizations

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by tavplubix** [comment]
But the `duplicate_order_by_and_distinct` setting is still there, and we still have some code that uses it. Should we remove that code too?

**Comment by devcrafter** [comment]
> But the `duplicate_order_by_and_distinct` setting is still there, and we still have some code that uses it. Should we remove that code too?

Yes, it can be done, but in separate PR and probably better after analyzer will be enabled by default.

**Comment by tavplubix** [comment]
But it does not seem to be related to new analyzer at all. It's some old optimization in old analyzer, and it's replaced by other optimizations, so looks like we can simply remove it.

**Comment by devcrafter** [comment]
Yes, the old optimization is not related to the analyzer. But I would prefer `remove_redundant*` optimizations be tested a bit overtime. For example, some bug was found with enabled analyzer.

**Comment by robot-ch-test-poll** [comment]
This is an automated comment for commit 79f53f428bc3df80326d9f419e48cf7ca9dddba3 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/47135/79f53f428bc3df80326d9f419e48cf7ca9dddba3/ci_running.html)
The overall status of the commit is 🟢 success

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟢 success</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Review by KochetovNicolai — APPROVED** [review]

**Pull request merged**
