### PR TITLE
Support function arrayElementOrNull

### PR DESCRIPTION
**Pull request by taiyang-li**
### Changelog category (leave one):
- New Feature

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Support function arrayElementOrNull. It returns null if array index is out of range or map key not found. 

```  sql
SELECT arrayElementOrNull([1, 2, 3], 4)

Query id: d4d51db9-4b1c-461c-80ad-c07ccad94354

   ┌─arrayElementOrNull([1, 2, 3], 4)─┐
1. │                             ᴺᵁᴸᴸ │
   └──────────────────────────────────┘

1 row in set. Elapsed: 0.002 sec. 

SELECT arrayElementOrNull(map(1, 2, 3, 4), 4)

Query id: 77eedb7c-ac31-45ac-88d8-9427be78eb90

   ┌─arrayElementOrNull(map(1, 2, 3, 4), 4)─┐
1. │                                   ᴺᵁᴸᴸ │
   └────────────────────────────────────────┘

1 row in set. Elapsed: 0.002 sec. 


```

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [x]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Run only fuzzers related jobs (libFuzzer fuzzers, AST fuzzers, etc.)
- [ ]  Exclude: AST fuzzers
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by den-crane** [comment]
How about to add arrayElementOrDefault as well?

* https://github.com/ClickHouse/ClickHouse/issues/46092

**Comment by taiyang-li** [comment]
> How about to add arrayElementOrDefault as well? Please?
> 
> * [arrayElementOrDefault / arrayElementOrNull #46092](https://github.com/ClickHouse/ClickHouse/issues/46092)


the old implementation is actually arrayElementOrDefault

**Comment by den-crane** [comment]
OrDefault in a sense of `dictGetOrDefault` returns the value passed as the `default_value_expr` parameter.

```
arrayElementOrDefault (array, index, defaulvalue ) -- if index element is not in the array, return defaulvalue.
arrayElementOrDefault (map, key, defaulvalue ) -- if key is not in the map, return defaulvalue.
```

```
select  arrayElementOfDefault(['a','b','c','d'], 42, 'notFound') 
--
notFound
```

**Comment by taiyang-li** [comment]
@den-crane It requires more work to implement `arrayElementOrDefault` than `arrayElementOrNull`.  I'd like to finish `arrayElementOrNull` first. And `arrayElementOrDefault`  will be implemented in another PR.

**Comment by taiyang-li** [comment]
@den-crane @alexey-milovidov could you please help review this PR? Thanks!

**Review by alexkats — APPROVED** [review]
lgtm, sorry it took some time to review

**Comment by franz101** [comment]
Love this feature so much, when will this be released? It's in head but not in Release v24.3.12.75-lts afaik

**Comment by den-crane** [comment]
@franz101 new features are never backported. It will be available only in 24.10+

**Comment by franz101** [comment]
makes sense, meant v24.9.... Very excited for 24.10, incredible work

**Pull request merged**
