### PR TITLE
Add hints for enum names

### LINKED ISSUE #17112: Hints for Enum names and column names based on Levenshtein distance.
**Use case**
Provide "Did you mean: ..." with nearest matches when user made a typo in Enum name or column name.

**Describe the solution you'd like**
See `NamePrompter.h`

### PR DESCRIPTION
**Pull request by ucasfl**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):

- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Add hints for Enum names. Closes #17112

### CODE REVIEW

**Comment by ucasFL** [comment]
```
:) SELECT CAST('Helo' AS Enum('Hello' = 1, 'World' = 2))

SELECT CAST('Helo', 'Enum(\'Hello\' = 1, \'World\' = 2)')

Query id: c963ddd6-1db7-4841-9257-b90fbdbdc5e4


0 rows in set. Elapsed: 0.002 sec. 

Received exception from server (version 21.6.1):
Code: 36. DB::Exception: Received from localhost:9000. DB::Exception: Unknown element 'Helo' for enum, may be you meant: ['Hello']: While processing CAST('Helo', 'Enum(\'Hello\' = 1, \'World\' = 2)').
```

**Review by alexey-milovidov — COMMENTED** [review]
LGTM. Let's also add sh test that will check that hints are present in the exception message.

**Comment by alexey-milovidov** [comment]
Ok. Also I see that the commit message has strange characters: `â�”â�`
Could you please push --force with another commit message?

**Review by alexey-milovidov — APPROVED** [review]

**Comment by ucasFL** [comment]
> Ok. Also I see that the commit message has strange characters: `â�”â�`
> Could you please push --force with another commit message?

Ok.

**Pull request merged**
