### PR TITLE
New ISO8601 year modificators for formatDateTime() function

### PR DESCRIPTION
**Pull request by vivarum**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Added support for `%g` (two digit ISO year) and `%G` (four digit ISO year) substitutions in `formatDateTime` function.

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
I've added NOLINT to skip clang-tidy check about function names.

**Comment by alexey-milovidov** [comment]
> Yandex synchronization check (only for Yandex employees)

Our collegues has found a bug in this check. Actually everything is Ok, will merge.

**Comment by AnaUvarova** [comment]
Hi, please help me understand what is the difference between %y, %Y and %g, %G?

**Comment by alexey-milovidov** [comment]
https://en.wikipedia.org/wiki/ISO_week_date#Relation_with_the_Gregorian_calendar

**Comment by AnaUvarova** [comment]
@vivarum Hi! Could you please share some cases of usage for this function?

**Comment by vivarum** [comment]
> @vivarum Hi! Could you please share some cases of usage for this function?

You can have a look on the original issue, probably it can give some background: https://github.com/ClickHouse/ClickHouse/issues/4023

**Comment by AnaUvarova** [comment]
> > @vivarum Hi! Could you please share some cases of usage for this function?
> 
> You can have a look on the original issue, probably it can give some background: #4023

Thank you.

**Pull request merged**
