### PR TITLE
Improve memory usage during memory efficient merging of aggregation results

### PR DESCRIPTION
**Pull request by nickitat**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Improved memory usage during memory efficient merging of aggregation results.

### CODE REVIEW

**Comment by nickitat** [comment]
before:
```
│ 2022-07-20 14:16:53.850883 │ Read 1262710172 rows, 161.51 GiB in 145.098296318 sec., 8702446 rows/sec., 1.11 GiB/sec.                                                                                                                                                                   │
│ 2022-07-20 14:16:54.935494 │ Peak memory usage (for query): 52.38 GiB.                                                                                                                                                                                                                  │
│ 2022-07-20 14:16:54.935524 │ Processed in 146.18336455 sec.                                       
```                                                                                                                                                                             

after:
```
│ 2022-07-20 18:40:10.936872 │ Read 1262710172 rows, 161.39 GiB in 148.293407688 sec., 8514944 rows/sec., 1.09 GiB/sec. │
│ 2022-07-20 18:40:12.089139 │ Peak memory usage (for query): 22.17 GiB.                                                │
│ 2022-07-20 18:40:12.089167 │ Processed in 149.44610334 sec.                                                           │
```

It happens because `SortingAggregatedTransform` in some (distributed external aggr) cases was able to buffer up to 100+ buckets inside it.

**Comment by larryluogit** [comment]
@nickitat I tested the PR using my original query with 16 threads. The query still uses >24G memory. I uploaded a log for your reference.

**Comment by larryluogit** [comment]
I build your branch and tested it with my query.
The peak memory of my query is `Peak memory usage (for query): 21.96 GiB.`
It slightly better, but still more than double of 9.5G when run the query against standalone server.
Perhaps, this changes fixed a different issue. What's your test query look like?

**Comment by larryluogit** [comment]
Hi @nickitat , thank you for looking into this issue. I know you're still working on the fix.
I tested your latest change. Peak memory of my query on initiator node drops to 19.43G.
```
[clickhouse02] 2022.07.25 18:55:03.004874 [ 45 ] {29c4a0e3-590a-42fb-9bb6-3cddc9dc635f} <Debug> MemoryTracker: Peak memory usage (for query): 9.85 GiB.

[clickhouse01] 2022.07.25 18:55:04.704590 [ 45 ] {3e44afd4-edbf-4c92-babc-6c8e32a91acd} <Debug> MemoryTracker: Peak memory usage (for query): 19.43 GiB.
```
The following are some of my observations.

- clickhouse02 is a worker node holding 50% of the data, but it uses the same amount of memory as processing the entire data in standalone server. I thought it should use 50% of memory the standalone server consumes.
- clickhouse01 is the initiator node. considering the initiator node processes it's own local data (50%) and the entire aggregation results concurrently, I can understand if the initiator node uses 1.5 times of memory that standalone server would use. Standalone servers consumes 9.5G in this case. I would expect the initiator node consumes <15G to process the query.

Does my expectation make sense to you? I can generate traces if you need it.

**Comment by nickitat** [comment]
@larryluogit looking into this query

``` sql
SELECT I.ServerIP, I.ServerHostName, I.DBUserName, I.ClientID, I.ServiceName, I.SourceProgram, VO.Verb, VO.Object, sum(TotalCount) AS Total FROM nested.INSTANCE_FLAT I ARRAY JOIN VerbObj AS VO WHERE I.PeriodStartUTC >= '2022-04-05 00:00:00' AND I.PeriodStartUTC <= '2022-04-08 00:00:00' AND VO.Verb IN ( 'cat','hat', 'came', 'back', 'said', 'the', 'fish', 'look', 'at', 'that', 'you', 'bent', 'our', 'new', 'rake', 'gyre','gimble','wabe','mimsy','were','borogoves' ) GROUP BY I.ServerIP, I.ServerHostName, I.DBUserName, I.ClientID, I.ServiceName, I.SourceProgram, VO.Verb, VO.Object ORDER BY Total DESC LIMIT 100
```

my impression is that x2 consumption is reasonable. you merge twice more buckets simultaneously and despite that local aggregation may have less data to process in your new setup, it now deals with non-finalized columns which keep memory arenas which preallocates more memory in advance for efficiency (now it should consume less memory, but anyway). it is especially true for aggregations with methods like `serialized` (when strings are used in group by key e.g.) and it is your case. shortly, I don't see now a room for significant improvement. my suggestion for your case is eighter to use ~twice less **merging** threads (I wouldn't expect significant slowdown) or to increase memory limit ~twice.

---

I use the following table:
``` sql
CREATE TABLE t
(
    `a` UInt64,
    `b` String,
    `c` FixedString(100)
)
ENGINE = MergeTree
ORDER BY tuple()
```

and my query is:
``` SQL
SELECT
    a,
    b,
    c,
    sum(a) AS s
FROM remote('127.0.0.{1,2}', default, t)
GROUP BY
    a,
    b,
    c
SETTINGS max_bytes_before_external_group_by = '10G', max_memory_usage = '200G', aggregation_memory_efficient_merge_threads = 16
FORMAT `Null`
```

**Comment by larryluogit** [comment]
Thanks for the insights. 

The worker node seems use x2 memory comparing to the amount of data it needs to process. Is this the same reason that worker node also
“now deals with non-finalized columns which keep memory arenas which preallocates more memory in advance for efficiency”?

We need to estimate memory limit when deploying cluster. Memory limit might need to be x2 in a 2 shards cluster. What could happen if the data is spread among more shards? Will the initiator node use less than x2 memory if it holds less data, e.g. 10%?

**Comment by nickitat** [comment]
> Is this the same reason that worker node also

yeap

> Will the initiator node use less than x2 memory if it holds less data, e.g. 10%?

local aggregation on initiator will definitely consume less

btw, in logs I see that your query consumed 23.5G with 8 threads. how much it consumed with 16? does this value changed after applying patch from this pr?

**Comment by larryluogit** [comment]
without your change:
8 threads:
```
[clickhouse02] 2022.07.14 23:31:30.763233 [ 44 ] {565a5d18-4116-45f7-946f-3c837712de21[0m} <Debug MemoryTracker[0m: Peak memory usage (for query): 22.25 GiB.
[clickhouse01] 2022.07.14 23:31:32.732742 [ 46 ] {f489c61-ac28-462f-9008-d39a94088cc6[0m} <Debug  MemoryTracker[0m: Peak memory usage (for query): 23.55 GiB.
```

With your change:
16 threads:
```
[clickhouse02] 2022.07.25 18:55:03.004874 [ 45 ] {29c4a0e3-590a-42fb-9bb6-3cddc9dc635f} <Debug> MemoryTracker: Peak memory usage (for query): 9.85 GiB.
[clickhouse01] 2022.07.25 18:55:04.704590 [ 45 ] {3e44afd4-edbf-4c92-babc-6c8e32a91acd} <Debug> MemoryTracker: Peak memory usage (for query): 19.43 GiB.
```

8 threads:
```
[clickhouse02] 2022.07.26 16:12:59.074983 [ 45 ] {6390dfd7-ed7d-46a2-aed6-05f0603dfd15} <Debug> MemoryTracker: Peak memory usage (for query): 9.40 GiB.
[clickhouse01] 2022.07.26 16:13:00.886341 [ 45 ] {beac825f-6f09-4f3e-a131-d74ec651a347} <Debug> MemoryTracker: Peak memory usage (for query): 10.90 GiB.
```

I don't have the number for 16 threads without your change because it keeps OOM. I'll try again to get that number.

**Comment by HeenaBansal2009** [comment]
This condition will always returns false since  expect_several_chunks_for_single_bucket_per_source  is false and not setting true anywhere else in code. What will happen when last_bucket_number[input_num] == current_bucket; https://github.com/ClickHouse/ClickHouse/blob/master/src/Processors/Transforms/MergingAggregatedMemoryEfficientTransform.cpp#L167

And 
I believe we should set finished =false in this condition block as well.
https://github.com/ClickHouse/ClickHouse/blob/master/src/Processors/Transforms/MergingAggregatedMemoryEfficientTransform.cpp#L190

And 
Whenever we are adding chunk to chunk_map here(https://github.com/ClickHouse/ClickHouse/blob/master/src/Processors/Transforms/MergingAggregatedMemoryEfficientTransform.cpp#L196) , we can set read_from_input[num_input]= true and this can be checked as well here https://github.com/ClickHouse/ClickHouse/blob/master/src/Processors/Transforms/MergingAggregatedMemoryEfficientTransform.cpp#L184 

@nickitat What do you suggest ?

**Comment by nickitat** [comment]
@HeenaBansal2009 I will try to look closely into this code, but from the first glance it looks ok for me

**Comment by HeenaBansal2009** [comment]
@nickitat , 
I am just curios about the comment in your functional test 
`select memory_usage < 4 * 1024 * 1024 * 1024 -- whole aggregation state of local aggregation uncompressed is 5.8G`

I understand 5.8GB is uncompressed data spilled to disk on each shard. 
However , Just curios about the value (4*1024*1024*1024) is calculated?

**Comment by nickitat** [comment]
> @nickitat , I am just curios about the comment in your functional test `select memory_usage < 4 * 1024 * 1024 * 1024 -- whole aggregation state of local aggregation uncompressed is 5.8G`
> 
> I understand 5.8GB is uncompressed data spilled to disk on each shard. However , Just curios about the value (4_1024_1024*1024) is calculated?

I just took the actual consumption from logs and added some extra amount to be sure that the test wouldn't be flaky.

**Comment by HeenaBansal2009** [comment]
> > @nickitat , I am just curios about the comment in your functional test `select memory_usage < 4 * 1024 * 1024 * 1024 -- whole aggregation state of local aggregation uncompressed is 5.8G`
> > I understand 5.8GB is uncompressed data spilled to disk on each shard. However , Just curios about the value (4_1024_1024*1024) is calculated?
> 
> I just took the actual consumption from logs and added some extra amount to be sure that the test wouldn't be flaky.

@nickitat , Thanks for the response. I would like to know if by any chance we can predict the approx memory usage based on the local aggregation data and max_threads and aggregate states.  it would be easier for us to set approx max_memory usage correctly beforehand.

**Comment by nickitat** [comment]
> based on the local aggregation data and max_threads and aggregate states

it sounds very complex imo. maybe just set the limit to `x2 + eps` of the single-node query consumption?

**Comment by larryluogit** [comment]
@nickitat Thank you for your expertise and efforts. Memory consumption of this query is reduced more than 100% with your changes.
We have a deployment scenario that customer has a more constrained system and periodically runs challenging reporting queries. In this case, we need to relax the in-memory results requirement assuming one accepts the query time tradeoffs. This is similar to the tradeoffs one accepts for the other spillage mechanisms.
I understand we can set aggregation_memory_efficient_merge_threads to 1 to reduce memory consumption. 

I was wondering whether there are other improvements we could pursue.  For example:
Is it feasible to set the number of buckets per query?
For additive aggregation functions (e.g. sum in this query), is there room to optimize non-finalized columns?

You might have better ideas to push the limit. We can work on any ideas under your guidance.

**Comment by nickitat** [comment]
> Is it feasible to set the number of buckets per query?

unfortunately, the number 256 is hardcoded in the sources. maybe you could build CH by yourself with other number of buckets. it is up to you to decide, if it worth the hassle.

> I was wondering whether there are other improvements we could pursue. For example: Is it feasible to set the number of buckets per query? For additive aggregation functions (e.g. sum in this query), is there room to optimize non-finalized columns?

we plan to try to implement a merging algorithm that wouldn't depend on the total aggregation size. it would be a general solution to the problem.

**Review by KochetovNicolai — APPROVED** [review]

**Comment by tavplubix** [comment]
New test `02354_distributed_with_external_aggregation_memory_usage` fails in debug build:
https://play.clickhouse.com/play?user=play#c2VsZWN0IAp0b1N0YXJ0T2ZEYXkoY2hlY2tfc3RhcnRfdGltZSkgYXMgZCwKY291bnQoKSwgZ3JvdXBVbmlxQXJyYXkocHVsbF9yZXF1ZXN0X251bWJlciksIGdyb3VwVW5pcUFycmF5KGNoZWNrX25hbWUpLCBhbnkocmVwb3J0X3VybCkKZnJvbSBjaGVja3Mgd2hlcmUgJzIwMjItMDYtMDEnIDw9IGNoZWNrX3N0YXJ0X3RpbWUgYW5kIHRlc3RfbmFtZSBsaWtlICclMDIzNTRfZGlzdHJpYnV0ZWRfd2l0aF9leHRlcm5hbF9hZ2dyZWdhdGlvbl9tZW1vcnlfdXNhZ2UlJyBhbmQgdGVzdF9zdGF0dXMgaW4gKCdGQUlMJykgZ3JvdXAgYnkgZCBvcmRlciBieSBkIGRlc2M=

**Pull request merged**
