### PR TITLE
add toIntXXOrDefault and toUUIDOrDefault functions

### PR DESCRIPTION
**Pull request by taiyang-li**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- New Feature

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
- Add Function `toUUIDOrDefault`, `toUInt8/16/32/64/256OrDefault`, `toInt8/16/32/64/128/256OrDefault`, which enables user defining default value(not null) when string parsing is failed

Detailed description / Documentation draft:
- Add Function `toUUIDOrDefault`, `toUInt8/16/32/64/256OrDefault`, `toInt8/16/32/64/128/256OrDefault`, which enables user defining default value(not null) when string parsing is failed

For example:
``` text
> SELECT toInt64OrDefault('123123', cast('-1' as Int64)), toInt8OrDefault('123qwe123', cast('-1' as Int8)); 

SELECT
    toInt64OrDefault('123123', CAST('-1', 'Int64')),
    toInt8OrDefault('123qwe123', CAST('-1', 'Int8'))

Query id: 80d6db8c-83f3-4080-bdbc-aa5cce8b2584

┌─toInt64OrDefault('123123', CAST('-1', 'Int64'))─┬─toInt8OrDefault('123qwe123', CAST('-1', 'Int8'))─┐
│                                          123123 │                                               -1 │
└─────────────────────────────────────────────────┴──────────────────────────────────────────────────┘

1 rows in set. Elapsed: 0.014 sec. 
```

TODO 
- Implement `toXXXOrDefault` function for Datetypes: `Date`, `DateTime`, `DateTime64`, `Decimal`

### CODE REVIEW

**Comment by kitaisreal** [comment]
@taiyang-li currently functions conversions file is too complex and we do not want to add additional functionality before it will be easier to maintain. 
From my perspective it would be better to rewrite this function as composition of accurateCastOrNull and if result is null use default value. What do you think ?

**Comment by taiyang-li** [comment]
OK. I will add this feature to `accurateCastOrNull `

**Comment by kitaisreal** [comment]
@taiyang-li actually I mean separate function that will call accurate cast or null. And if in result column we see nullable row then we replace It with default value.

**Comment by taiyang-li** [comment]
I got what you mean, thanks

**Comment by kitaisreal** [comment]
Will merge to temporary branch cast_to_value_or_default and create pull request for merge with master https://github.com/ClickHouse/ClickHouse/pull/23028.

**Pull request merged**
