### PR TITLE
Add restore setting "restore_broken_parts_as_detached"

### PR DESCRIPTION
**Pull request by vitlibar**
### Changelog category:
- Improvement

### Changelog entry:
Added restore setting `restore_broken_parts_as_detached`: if it's true the RESTORE process won't stop on broken parts while restoring, instead all the broken parts will be copied to the `detached` folder with the prefix `broken-from-backup'. If it's false the RESTORE process will stop on the first broken part (if any). The default value is false.

Added backup setting `check_parts`: If it's true the BACKUP process will check that parts are not broken before putting them into a backup. The default value is true.

Before this PR a single broken part added to a backup could make the entire table non-restorable.

### CODE REVIEW

**Comment by robot-ch-test-poll4** [comment]
This is an automated comment for commit 86361480164b6ed569f041f1ffb9d8e9dd2ac9c3 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/53877/86361480164b6ed569f041f1ffb9d8e9dd2ac9c3/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Comment by vitlibar** [comment]
I decided to change my solution in this PR, will update the PR soon. Please don't review it now, review it later :)

**Comment by vitlibar** [comment]
> I decided to change my solution in this PR, will update the PR soon. Please don't review it now, review it later :)

done, please review it now :)

**Review by pufit — APPROVED** [review]
LGTM!

**Pull request merged**
