### PR TITLE
Inline convertDecimals

### PR DESCRIPTION
**Pull request by Algunenano**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
...

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

Comes from https://github.com/ClickHouse/ClickHouse/pull/34544. For GCC to work with the attribute you need to also declare the function `inline`, otherwise you get an error like:

```
In file included from ../src/Functions/FunctionsConversion.h:12,
                 from ../src/Interpreters/ActionsDAG.cpp:7:
../src/DataTypes/DataTypesDecimal.h:140:46: error: ‘always_inline’ function might not be inlinable [-Werror=attributes]
  140 | ALWAYS_INLINE typename ToDataType::FieldType convertDecimals(const typename FromDataType::FieldType & value, UInt32 scale_from, UInt32 scale_to)
      |
```

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]

**Comment by Algunenano** [comment]
@Mergifyio update

**Comment by alexey-milovidov** [comment]
test_hive_query failed.

**Comment by kitaisreal** [comment]
@Algunenano performance tests does not show any differences. logical_functions_medium are unstable.

**Comment by Algunenano** [comment]
@Mergifyio update

**Pull request closed without merging**
