### PR TITLE
Fix mysql replication optional metadata ignore

### LINKED ISSUE #14251: MaterializeMySQLSyncThread DB::Exception: Packet payload is not fully read
**Describe the bug**
I got below error message when data replication is in progress, after then data replication has stopped and the DB is not accessible (detach and attach not work), I'm wondering what does the error message mean?

```
2020.08.30 11:43:28.441220 [ 105102 ] {} <Error> MaterializeMySQLSyncThread: Code: 99, e.displayText() = DB::Exception: Packet payload is not fully read. Stopped after 38 bytes, while 89 bytes are in buffer., Stack trace (when copying this message, always include the lines below):

0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x1a7d7400 in /usr/bin/clickhouse
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0xff8f78d in /usr/bin/clickhouse
2. ? @ 0x1738ea80 in /usr/bin/clickhouse
3. DB::MySQLProtocol::PacketEndpoint::tryReceivePacket(DB::MySQLProtocol::IMySQLReadPacket&, unsigned long) @ 0x1739b497 in /usr/bin/clickhouse
4. DB::MySQLClient::readOneBinlogEvent(unsigned long) @ 0x17398b01 in /usr/bin/clickhouse
5. DB::MaterializeMySQLSyncThread::synchronization(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x173707a0 in /usr/bin/clickhouse
6. ? @ 0x17370ba6 in /usr/bin/clickhouse
7. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xffbf517 in /usr/bin/clickhouse
8. ? @ 0xffbdb53 in /usr/bin/clickhouse
9. start_thread @ 0x7dd5 in /usr/lib64/libpthread-2.17.so
10. clone @ 0xfdead in /usr/lib64/libc-2.17.so
 (version 20.8.1.4474 (official build))
2020.08.30 11:43:30.346747 [ 104909 ] {cc04190d-a6a4-44bc-b9f2-b04e14129ee9} <Error> executeQuery: Code: 99, e.displayText() = DB::Exception: Packet payload is not fully read. Stopped after 38 bytes, while 89 bytes are in buffer. (version 20.8.1.4474 (official build)) (from 10.99.4.75:44904) (in query: SELECT COUNT(*) FROM rs_monitor.done_jobs FORMAT TabSeparatedWithNamesAndTypes;), Stack trace (when copying this message, always include the lines below):

0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x1a7d7400 in /usr/bin/clickhouse
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0xff8f78d in /usr/bin/clickhouse
2. ? @ 0x1738ea80 in /usr/bin/clickhouse
3. DB::MySQLProtocol::PacketEndpoint::tryReceivePacket(DB::MySQLProtocol::IMySQLReadPacket&, unsigned long) @ 0x1739b497 in /usr/bin/clickhouse
4. DB::MySQLClient::readOneBinlogEvent(unsigned long) @ 0x17398b01 in /usr/bin/clickhouse
5. DB::MaterializeMySQLSyncThread::synchronization(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x173707a0 in /usr/bin/clickhouse
6. ? @ 0x17370ba6 in /usr/bin/clickhouse
7. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xffbf517 in /usr/bin/clickhouse
8. ? @ 0xffbdb53 in /usr/bin/clickhouse
9. start_thread @ 0x7dd5 in /usr/lib64/libpthread-2.17.so
10. clone @ 0xfdead in /usr/lib64/libc-2.17.so

2020.08.30 11:43:30.347066 [ 104909 ] {cc04190d-a6a4-44bc-b9f2-b04e14129ee9} <Error> DynamicQueryHandler: Code: 99, e.displayText() = DB::Exception: Packet payload is not fully read. Stopped after 38 bytes, while 89 bytes are in buffer., Stack trace (when copying this message, always include the lines below):

0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x1a7d7400 in /usr/bin/clickhouse
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0xff8f78d in /usr/bin/clickhouse
2. ? @ 0x1738ea80 in /usr/bin/clickhouse
3. DB::MySQLProtocol::PacketEndpoint::tryReceivePacket(DB::MySQLProtocol::IMySQLReadPacket&, unsigned long) @ 0x1739b497 in /usr/bin/clickhouse
4. DB::MySQLClient::readOneBinlogEvent(unsigned long) @ 0x17398b01 in /usr/bin/clickhouse
5. DB::MaterializeMySQLSyncThread::synchronization(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x173707a0 in /usr/bin/clickhouse
6. ? @ 0x17370ba6 in /usr/bin/clickhouse
7. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xffbf517 in /usr/bin/clickhouse
8. ? @ 0xffbdb53 in /usr/bin/clickhouse
9. start_thread @ 0x7dd5 in /usr/lib64/libpthread-2.17.so
10. clone @ 0xfdead in /usr/lib64/libc-2.17.so
 (version 20.8.1.4474 (official build))
2020.08.30 11:43:38.036083 [ 104908 ] {c2ba4822-a889-496b-a167-9171b896ebb1} <Error> executeQuery: Code: 99, e.displayText() = DB::Exception: Packet payload is not fully read. Stopped after 38 bytes, while 89 bytes are in buffer. (version 20.8.1.4474 (official build)) (from 10.99.4.75:44906) (in query: SELECT * FROM rs_monitor.done_jobs ORDER BY id DESC FORMAT TabSeparatedWithNamesAndTypes;), Stack trace (when copying this message, always include the lines below):

0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x1a7d7400 in /usr/bin/clickhouse
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0xff8f78d in /usr/bin/clickhouse
2. ? @ 0x1738ea80 in /usr/bin/clickhouse
3. DB::MySQLProtocol::PacketEndpoint::tryReceivePacket(DB::MySQLProtocol::IMySQLReadPacket&, unsigned long) @ 0x1739b497 in /usr/bin/clickhouse
4. DB::MySQLClient::readOneBinlogEvent(unsigned long) @ 0x17398b01 in /usr/bin/clickhouse
5. DB::MaterializeMySQLSyncThread::synchronization(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x173707a0 in /usr/bin/clickhouse
6. ? @ 0x17370ba6 in /usr/bin/clickhouse
7. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xffbf517 in /usr/bin/clickhouse
8. ? @ 0xffbdb53 in /usr/bin/clickhouse
9. start_thread @ 0x7dd5 in /usr/lib64/libpthread-2.17.so
10. clone @ 0xfdead in /usr/lib64/libc-2.17.so

2020.08.30 11:43:38.036391 [ 104908 ] {c2ba4822-a889-496b-a167-9171b896ebb1} <Error> DynamicQueryHandler: Code: 99, e.displayText() = DB::Exception: Packet payload is not fully read. Stopped after 38 bytes, while 89 bytes are in buffer., Stack trace (when copying this message, always include the lines below):

0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x1a7d7400 in /usr/bin/clickhouse
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0xff8f78d in /usr/bin/clickhouse
2. ? @ 0x1738ea80 in /usr/bin/clickhouse
3. DB::MySQLProtocol::PacketEndpoint::tryReceivePacket(DB::MySQLProtocol::IMySQLReadPacket&, unsigned long) @ 0x1739b497 in /usr/bin/clickhouse
4. DB::MySQLClient::readOneBinlogEvent(unsigned long) @ 0x17398b01 in /usr/bin/clickhouse
5. DB::MaterializeMySQLSyncThread::synchronization(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x173707a0 in /usr/bin/clickhouse
6. ? @ 0x17370ba6 in /usr/bin/clickhouse
7. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xffbf517 in /usr/bin/clickhouse
8. ? @ 0xffbdb53 in /usr/bin/clickhouse
9. start_thread @ 0x7dd5 in /usr/lib64/libpthread-2.17.so
10. clone @ 0xfdead in /usr/lib64/libc-2.17.so
 (version 20.8.1.4474 (official build))
2020.08.30 11:45:11.352646 [ 104907 ] {f91d2659-1d7f-4869-941b-01216b4238b1} <Error> executeQuery: Code: 99, e.displayText() = DB::Exception: Packet payload is not fully read. Stopped after 38 bytes, while 89 bytes are in buffer. (version 20.8.1.4474 (official build)) (from 10.99.4.75:59228) (in query: select * from job_summary;), Stack trace (when copying this message, always include the lines below):

0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x1a7d7400 in /usr/bin/clickhouse
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0xff8f78d in /usr/bin/clickhouse
2. ? @ 0x1738ea80 in /usr/bin/clickhouse
3. DB::MySQLProtocol::PacketEndpoint::tryReceivePacket(DB::MySQLProtocol::IMySQLReadPacket&, unsigned long) @ 0x1739b497 in /usr/bin/clickhouse
4. DB::MySQLClient::readOneBinlogEvent(unsigned long) @ 0x17398b01 in /usr/bin/clickhouse
5. DB::MaterializeMySQLSyncThread::synchronization(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x173707a0 in /usr/bin/clickhouse
6. ? @ 0x17370ba6 in /usr/bin/clickhouse
7. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xffbf517 in /usr/bin/clickhouse
8. ? @ 0xffbdb53 in /usr/bin/clickhouse
9. start_thread @ 0x7dd5 in /usr/lib64/libpthread-2.17.so
10. clone @ 0xfdead in /usr/lib64/libc-2.17.so

2020.08.30 11:45:11.353144 [ 104907 ] {} <Error> ServerErrorHandler: Code: 99, e.displayText() = DB::Exception: Packet payload is not fully read. Stopped after 38 bytes, while 89 bytes are in buffer., Stack trace (when copying this message, always include the lines below):

0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x1a7d7400 in /usr/bin/clickhouse
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0xff8f78d in /usr/bin/clickhouse
2. ? @ 0x1738ea80 in /usr/bin/clickhouse
3. DB::MySQLProtocol::PacketEndpoint::tryReceivePacket(DB::MySQLProtocol::IMySQLReadPacket&, unsigned long) @ 0x1739b497 in /usr/bin/clickhouse
4. DB::MySQLClient::readOneBinlogEvent(unsigned long) @ 0x17398b01 in /usr/bin/clickhouse
5. DB::MaterializeMySQLSyncThread::synchronization(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x173707a0 in /usr/bin/clickhouse
6. ? @ 0x17370ba6 in /usr/bin/clickhouse
7. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xffbf517 in /usr/bin/clickhouse
8. ? @ 0xffbdb53 in /usr/bin/clickhouse
9. start_thread @ 0x7dd5 in /usr/lib64/libpthread-2.17.so
10. clone @ 0xfdead in /usr/lib64/libc-2.17.so
 (version 20.8.1.4474 (official build))
```

### PR DESCRIPTION
**Pull request by bohutang**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fixed "Packet payload is not fully read" error in `MaterializeMySQL` database engine.

Detailed description / Documentation draft:
Close https://github.com/ClickHouse/ClickHouse/issues/14251 https://github.com/ClickHouse/ClickHouse/issues/14572
...

By adding documentation, you'll allow users to try your new feature immediately, not when someone else will have time to document it later. Documentation is necessary for all features that affect user experience in any way. You can add brief documentation draft above, or add documentation right into your patch as Markdown files in [docs](https://github.com/ClickHouse/ClickHouse/tree/master/docs) folder.

If you are doing this for the first time, it's recommended to read the lightweight [Contributing to ClickHouse Documentation](https://github.com/ClickHouse/ClickHouse/tree/master/docs/README.md) guide first.

Information about CI checks: https://clickhouse.tech/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by BohuTANG** [comment]
Cc @alexey-milovidov CI is unhappy

**Comment by BohuTANG** [comment]
@alexey-milovidov ping for a review

**Comment by tavplubix** [comment]
Could you please some description of what is the reason of such errors and how is it fixed? Is it possible to add an integration test?

**Comment by BohuTANG** [comment]
Hi,

https://github.com/ClickHouse/ClickHouse/issues/14251 and https://github.com/ClickHouse/ClickHouse/issues/14572 are all caused by the `ignore` length.

This crash is not easily to reproduce, and I don't think integration testing will work.

How to reproduce the problem:
On the mysql side, each transaction writes 500 records and lasts for a few minutes, it maybe happen or maybe not.

Script is here:
https://gist.github.com/BohuTANG/55cac003a358eb70adce5923be0ee60d

By analysis, the problem should be that mysql is sending different event structure than usual in some cases, i am not sure why, but this fix works, I've been running  the reproduce script and the problem no longer occurs.

**Review by tavplubix — APPROVED** [review]

**Pull request merged**
