### PR TITLE
MySQL: Delay disconnection of mysqlxx::Pool::Entry until refcount==0

### PR DESCRIPTION
**Pull request by valbok**
If Entry::disconnect() is called, it is removed from its pool and underlying mysqlxx::Connection is disconnected.

Since Entry objects are copyable and some of them could be alive when disconnect() is called which would lead to undefined behavior.

Suggesting to disconnect it when the last object is being destroyed.

### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
- Fixed crash when mysqlxx::Pool::Entry is used after it was disconnected.

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
How can we test this? Does it reproduce with MySQL table function/engine?

**Comment by robot-clickhouse** [comment]
This is an automated comment for commit d891c4c9a218784d1717710a676b3a132339b14b with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/52063/d891c4c9a218784d1717710a676b3a132339b14b/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Comment by valbok** [comment]
> How can we test this? Does it reproduce with MySQL table function/engine?

Also applicable for MySQL.

    auto mysql_pool = mysqlxx::Pool(configuration.database, configuration.host, configuration.username, 
    configuration.password, configuration.port);
    auto entry = pool.get();
    auto copy = entry;
    entry.disconnect(); // <<< this removes from the pool and disconnects the underlying mysqlxx::Connection
    ...
    copy->query("SQL").execute(); // << this will fail since it is already disconnected, and the driver memory is cleared "memset(driver.get(), 0, sizeof(*driver));"
    // and Query::execute() should fail: 
           MYSQL* mysql_driver = conn->getDriver();  /// driver is empty
           if (mysql_real_query(mysql_driver, query.data(), query.size()))

**Review by alexey-milovidov — APPROVED** [review]
LGTM.

Ok, let's proceed without a test.

**Review by alexey-milovidov — APPROVED** [review]

**Pull request merged**
