### PR TITLE
Activated a bunch of LLVM 12/13/14 clang-tidy warnings

### PR DESCRIPTION
**Pull request by rschu1ze**
Omitted new checks which produce too many matches or which are controversial (e.g. readability-identifier-length).

New checks (descriptions taken from official docs):

- misc-misleading-bidirectional + misc-misleading-identifier

  Detects potential attack as described in the Trojan Source attack

- modernize-macro-to-enum

  Replaces groups of adjacent macros with an unscoped anonymous enum

- modernize-shrink-to-fit

  Replace copy and swap tricks on shrinkable containers with the
  shrink_to_fit() method call

- modernize-use-transparent-functors

  Prefer transparent functors to non-transparent ones

- modernize-use-uncaught-exceptions

  This check will warn on calls to std::uncaught_exception and replace
  them with calls to std::uncaught_exceptions (uncaught_exception was
  deprecated with C++17)

- performance-no-int-to-ptr

  Diagnoses every integer to pointer cast

- readability-duplicate-include

  Looks for duplicate includes and removes them

- readability-redundant-preprocessor

  Finds potentially redundant preprocessor directives

- bugprone-lambda-function-name

  Checks for attempts to get the name of a function from within a lambda
  expression

- bugprone-redundant-branch-condition

  Finds condition variables in nested if statements that were also
  checked in the outer if statement and were not changed

- bugprone-shared-ptr-array-mismatch

  Finds initializations of C++ shared pointers to non-array type that
  are initialized with an array

- bugprone-stringview-nullptr

  Checks for various ways that the const CharT* constructor of
  std::basic_string_view can be passed a null argument and replaces them
  with the default constructor in most cases

- bugprone-suspicious-memory-comparison

  Finds potentially incorrect calls to memcmp() based on properties of
  the arguments

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Review by qoega — APPROVED** [review]

**Comment by rschu1ze** [comment]
@Mergifyio update

**Comment by rschu1ze** [comment]
Hmm, 01268_procfs_metrics in fasttest failed but the failure is known in master. Looks like this prevented other builds/tests to start. Will merge from master again, maybe we'll have more luck then.

**Comment by rschu1ze** [comment]
@Mergifyio update

**Review by alexey-milovidov — APPROVED** [review]

**Comment by rschu1ze** [comment]
@Mergifyio update

**Pull request merged**
