### PR TITLE
Fix WITH FILL: Invalid number of rows in Chunk

### LINKED ISSUE #57609: WITH FILL: Invalid number of rows in Chunk column Nullable(UInt32)
**Describe the bug**
https://s3.amazonaws.com/clickhouse-test-reports/57467/b4966b980ee3f63e9aed0b310b5a745114e97801/fuzzer_astfuzzertsan/report.html

### PR DESCRIPTION
**Pull request by vdimir**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
* Fix possible `LOGICAL_ERROR` with duplicate columns in `ORDER BY ... WITH FILL`

close https://github.com/ClickHouse/ClickHouse/issues/57609

### CODE REVIEW

**Comment by robot-ch-test-poll2** [comment]
*This is an automated comment for commit 37a534325f3c49cfb608dcdfb28d15138fb4a0fc with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/72387/37a534325f3c49cfb608dcdfb28d15138fb4a0fc/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/72381/856f73a7c26bceeeda7a28ddaf54ec84d993b861/docs_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Comment by divanik** [comment]
One thing bothers me. It is a:
```
SELECT
    1 AS a,
    2 AS b
ORDER BY
    a ASC,
    a DESC,
    b ASC WITH FILL TO 10

Query id: 43ef4e40-f332-4b0d-8d9d-af59003bca6a

   ┌─a─┬─b─┐
1. │ 1 │ 2 │
   └───┴───┘
   ┌─a─┬─b─┐
2. │ 1 │ 3 │
3. │ 1 │ 4 │
4. │ 1 │ 5 │
5. │ 1 │ 6 │
6. │ 1 │ 7 │
7. │ 1 │ 8 │
8. │ 1 │ 9 │
   └───┴───┘

8 rows in set. Elapsed: 0.003 sec.
```

I can't say for sure if this behavior is expected. Just to throw away contradicting sort condition, I mean

**Comment by vdimir** [comment]
@divanik Yes, I see your point.

However, I’m not sure how it affects the query because I don't see that we use the direction in `FillingTransform` at all. Also, it seems to be more about how `ORDER BY` handles such cases rather than `WITH FILL`.

For `ORDER BY` sorting by `a DESC` doesn't change the ordering (basically it's the same as `ORDER BY a, -a`), so the second sorting column has the same values within the equality ranges of the first one.

For example, the query returns the same result even without the patch from this PR: https://fiddle.clickhouse.com/d1829f87-d93e-4586-a835-a3b3caf552c8.

I'll experiment a bit with such corner cases. Also, please let me know if you find a case where the result indeed differs from the current behavior or is unexpected.

**Comment by divanik** [comment]
> @divanik Yes, I see your point.
> 
> However, I’m not sure how it affects the query because I don't see that we use the direction in `FillingTransform` at all. Also, it seems to be more about how `ORDER BY` handles such cases rather than `WITH FILL`.
> 
> For `ORDER BY` sorting by `a DESC` doesn't change the ordering (basically it's the same as `ORDER BY a, -a`), so the second sorting column has the same values within the equality ranges of the first one.
> 
> For example, the query returns the same result even without the patch from this PR: https://fiddle.clickhouse.com/d1829f87-d93e-4586-a835-a3b3caf552c8.
> 
> I'll experiment a bit with such corner cases. Also, please let me know if you find a case where the result indeed differs from the current behavior or is unexpected.

Yeap. Thanks for clarifying. Now I understand why I have such an output on my query. I will think about it a bit more if there are any other interesting cases

**Comment by vdimir** [comment]
> Integration tests (tsan) [1/6] — fail: 1, passed: 528 [Details](https://s3.amazonaws.com/clickhouse-test-reports/72387/37a534325f3c49cfb608dcdfb28d15138fb4a0fc/integration_tests__tsan__[1_6].html)

`#72357`

> Stateless tests (tsan) [4/4] — Server died, fail: 13, passed: 375, skipped: 6 [Details](https://s3.amazonaws.com/clickhouse-test-reports/72387/37a534325f3c49cfb608dcdfb28d15138fb4a0fc/stateless_tests__tsan__[4_4].html)

> Stateless tests (tsan, s3 storage) [3/3] — Timeout expired [Details](https://s3.amazonaws.com/clickhouse-test-reports/72387/37a534325f3c49cfb608dcdfb28d15138fb4a0fc/stateless_tests__tsan__s3_storage__[3_3].html)

`#72392`

> Stateful tests (asan) — fail: 1, passed: 136, skipped: 1 [Details](https://s3.amazonaws.com/clickhouse-test-reports/72387/37a534325f3c49cfb608dcdfb28d15138fb4a0fc/stateful_tests__asan_.html)

Asan report from cleint (?)

**Pull request merged**
