### PR TITLE
Support more conditions in JOIN ON section for `hash` join

### PR DESCRIPTION
**Pull request by vdimir**
### Changelog category (leave one):
- New Feature

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
* Support non-equi conditions involving left and right table for `INNER` and `LEFT` _hash_ join _in analyzer_

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by vdimir** [comment]
Some test cases are not handled, but minimal functionality is implemented to review this PR.

**Comment by robot-ch-test-poll3** [comment]
This is an automated comment for commit 059ffd4d12c3800ebcda22f99a110dc2593a522a with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/46479/059ffd4d12c3800ebcda22f99a110dc2593a522a/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Docs Check</td><td>Builds and tests the documentation</td><td>🟡 pending</td></tr>
</table>

**Comment by vdimir** [comment]
> Stateless tests flaky check (asan) — fail: 35, passed: 66 [Details](https://s3.amazonaws.com/clickhouse-test-reports/46479/40236d0d2bdab0c0e993791abb9d627544135cc8/stateless_tests_flaky_check__asan_.html)

Timeout, will split test to short and long part.

**Comment by vdimir** [comment]
@devcrafter maybe you also want to take a look?

**Comment by fancyqlx** [comment]
hi, i wonder know the status of this feature, will it be continue?

**Comment by fancyqlx** [comment]
@vdimir hi, have you tested the performance of this feature? which of the following sql is faster in this feature？
`select sum(id) from table_a as a join table_b as b on 1 where a.key = b.key and a.id > b.id`
vs
`select sum(id) from test_a as a join table_b as b on a.key = b.key and a.id > b.id`

**Comment by vdimir** [comment]
> hi, have you tested the performance of this feature? which of the following sql is faster in this feature？
> select sum(id) from table_a as a join table_b as b on 1 where a.key = b.key and a.id > b.id
> vs
> select sum(id) from test_a as a join table_b as b on a.key = b.key and a.id > b.id

This implementation is not really optimized. However, it should be faster than cross join, so I'd say second query

**Comment by fancyqlx** [comment]
@vdimir hi, I have tested the two join sqls, here is my result. non-equi join takes more time than cross join. did I do something wrong? or there is going to be further optimization?

`CREATE TABLE default.test_join
(
    `p_date` Date,
    `id` Int32
)
ENGINE = MergeTree
PARTITION BY p_date
ORDER BY id
SETTINGS index_granularity = 8192;

insert into test_join select '2023-01-01', number from numbers(100000);

set allow_experimental_analyzer = 1;

SELECT sum(id)
FROM
(
    SELECT *
    FROM test_join
    LIMIT 10000
) AS a
INNER JOIN
(
    SELECT *
    FROM test_join
    LIMIT 10000
) AS b ON 1
WHERE (a.p_date = b.p_date) AND (a.id > b.id);

SELECT sum(id)
FROM
(
    SELECT *
    FROM test_join
    LIMIT 10000
) AS a
INNER JOIN
(
    SELECT *
    FROM test_join
    LIMIT 10000
) AS b ON (a.p_date = b.p_date) AND (a.id > b.id);`

image
image

**Comment by fancyqlx** [comment]
I can give some findings for optimization,  from my testing, joinWithExtraConditions and getRowFromBlockck is too heavy. i optimized joinWithExtraConditions according to FilterTranfrom, it save me 30% time.

**Comment by vdimir** [comment]
@fancyqlx it'll be appreciated. You may push to a branch in your fork and give a link, I'll cherry pick changes

**Comment by fancyqlx** [comment]
@vdimir hi, for left inequal-join, i find there is the case that we add missing right table value but it does not satisfy the inequal condition. for the following case, the first row, a.id = 0, b.id = 0, but we have condition a.id > b.id. So I think we need to first add missing default values then evaluate the inequal-condition expression?
`
CREATE TABLE default.test_join
(
    p_date Date,
    id Int32
)
ENGINE = MergeTree
PARTITION BY p_date
ORDER BY id
SETTINGS index_granularity = 8192;

CREATE TABLE default.test_join_2
(
    p_date Date,
    id Int32
)
ENGINE = MergeTree
PARTITION BY p_date
ORDER BY id
SETTINGS index_granularity = 8192;

insert into test_join select '2023-01-01', number from numbers(10);

insert into test_join_2 values ('2023-01-01', 1), ('2023-01-01', 1), ('2023-01-01', 2), ('2023-01-01', 2);

SELECT *
FROM test_join AS a
LEFT JOIN test_join_2 AS b ON (a.p_date = b.p_date) AND (a.id > b.id);

`

image

**Comment by zhanglistar** [comment]
@vdimir Why not go on? Any other plan? Thanks.

**Comment by vdimir** [comment]
This implementation is too ad-hoc and pretty slow, need to revise it

**Pull request closed without merging**
