### PR TITLE
Performance check build AVX

### PR DESCRIPTION
**Pull request by kitaisreal**
Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Check performance with AVX instructions enabled.

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
@kitaisreal what's the point of reopening?
AVX (1) only works for floats, so it hardly gives anything for ClickHouse.

**Comment by kitaisreal** [comment]
@Mergifyio update

**Comment by kitaisreal** [comment]
@Mergifyio update

**Comment by rschu1ze** [comment]
@Mergifyio update

**Comment by rschu1ze** [comment]
01103_check_cpu_instructions_at_startup.sh failed not surprisingly. I addressed it in #39000 (just because I don't have rights to push to @kitaisreal's fork).

**Comment by rschu1ze** [comment]
This PR is continued in https://github.com/ClickHouse/ClickHouse/pull/39000 --> closing for housekeeping reasons.

**Pull request closed without merging**
