### PR TITLE
Fix `02497_trace_events_stress_long`

### PR DESCRIPTION
**Pull request by antonio2368**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

https://s3.amazonaws.com/clickhouse-test-reports/0/b542fe364ae877aafb365a7b5dddfdefa444b4f5/stateless_tests__release__databaseordinary_.html

Could've also ignored just `is killed in pending state. (QUERY_WAS_CANCELLED)` but don't see a reason why would we forcefully quit the threads and kill queries because they don't seem too heavy.

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by robot-clickhouse-ci-2** [comment]
This is an automated comment for commit e0f737f363e08de8c028b0d3eac1908ed3193758 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/52279/e0f737f363e08de8c028b0d3eac1908ed3193758/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alesapin** [comment]
Flaky check ok, release ok. Let's merge

**Review by alesapin — APPROVED** [review]

**Comment by antonio2368** [comment]
> Flaky check ok

```
02497_trace_events_stress_long:                                         [ SKIPPED ] 0.00 sec. - not running for current build
```

**Comment by azat** [comment]
@antonio2368 maybe you will be interested, it is still flaky sometimes - https://s3.amazonaws.com/clickhouse-test-reports/50424/da93c5c84ce7eaa01a15dfe1d1dce1adfc2dc3c7/stateless_tests__aarch64_.html

**Comment by antonio2368** [comment]
@azat thanks for pinging
the failed test doesn't include the fix https://github.com/ClickHouse/ClickHouse/blob/da93c5c84ce7eaa01a15dfe1d1dce1adfc2dc3c7/tests/queries/0_stateless/02497_trace_events_stress_long.sh

**Comment by antonio2368** [comment]
Okay, I think you are right, will take a look

**Pull request merged**
