### PR TITLE
Fix filtering by Uint8 greater than 127

### LINKED ISSUE #19756: Suspected bug in ColumnArray::updatePermutation method
**Describe the bug**
https://clickhouse-test-reports.s3.yandex.net/19702/c74631c650b42e4d107254a03bd82c2c2913039b/fuzzer_msan/server.log

Most likely introduced here: #11006

### PR DESCRIPTION
**Pull request by CurtizJ**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix filtering by UInt8 greater than 127.

Fixes #19756.

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
Filtering by values not equal to 0 and 1 was implementation specific.
I don't understand how it is related to ORDER BY multiple columns with Array column.

**Comment by CurtizJ** [comment]
It's because of `arrayFilter`. Filtering data and offsets was inconsistent
https://github.com/ClickHouse/ClickHouse/blob/10160e5adf77e0ec0182e0c46a6688780abb5824/src/Functions/array/arrayFilter.cpp#L56-L63.

**Comment by alexey-milovidov** [comment]
Ok, I see. Let's wait for perf tests - hope it will not introduce performance regressions. Now the logic is better.
Otherwise we can make it consistent without changing the logic of filtering.

**Comment by alexey-milovidov** [comment]
Wow, it's passed!

**Pull request merged**
