### PR TITLE
Fix potential race condition of totalBytesWithInactive

### PR DESCRIPTION
**Pull request by nauu**
### Changelog category (leave one):

- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
...

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Run only fuzzers related jobs (libFuzzer fuzzers, AST fuzzers, etc.)
- [ ]  Exclude: AST fuzzers
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-ch-test-poll1** [comment]
*This is an automated comment for commit 07edab7245a6b425b5d805d49d2834b6ea186f1c with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/72919/07edab7245a6b425b5d805d49d2834b6ea186f1c/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/1e6a0ab07499b529472bae448b4edc948df3ca6f/docs_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Review by Michicosun — APPROVED** [review]
Why not just use getDataPartsVectorForInternalUsage as in a normal MergeTree?

**Comment by nauu** [comment]
> getDataPartsVectorForInternalUsage

getDataPartsStateRange is more straightforward , because I only need the outdate parts without any additional operations.

**Review by jsc0218 — APPROVED** [review]

**Comment by jsc0218** [comment]
Sorry I would close this pr as another related one is reverted and the comment [here](https://github.com/ClickHouse/ClickHouse/pull/72690#issuecomment-2529607617).

**Pull request closed without merging**
