### PR TITLE
ISSUES-16574 try fix remote query failure when using 'if' suffix aggregate function 

### LINKED ISSUE #16231: -If combinator and NULLs
Clickhouse version: 20.9.2 revision 54439

```SQL
SELECT
    sumMapIf([1], [1], nullIf(number, 3) > 0) AS col1,
    countIf(1, nullIf(number, 3) > 0) AS col2,
    sumIf(1, nullIf(number, 3) > 0) AS col3
FROM numbers(1, 5)
```

`col1` is expected to be `([1],[4])` as NULLs must be skipped
`col3` value is expected to be the same as `col2`'s as the condition part is identical and both should return `4`

in fact we get the following values:
```
┌─col1──────┬─col2─┬─col3─┐
│ ([1],[5]) │    4 │    5 │
└───────────┴──────┴──────┘
```

as a workaround one can wrap the condition part with `coalesce(..., 0)`

### LINKED ISSUE #16574: Wrong behavior for sumIf with non-nullable first argument and nullable second argument
https://github.com/ClickHouse/ClickHouse/pull/13964 introduced following tricky bug. It does not appear on versions before mentioned PR.

Listing below uses environment for tests (test_cluster_two_shards is a cluster consisting of two copies of local shard).

When making a distributed query, subj leads to the following error:
`
Code: 42. DB::Exception: Received from localhost:59000. DB::Exception: Aggregate function sum requires single argument: while receiving packet from 127.0.0.2:59000: While executing Remote.
`

```
max42-dev.sas.yp-c.yandex.net :) create table T(a Nullable(Int64)) engine = Memory()                                                                                                                                                          
                                                                                                                                                                                                                                              
CREATE TABLE T                                                                                                                                                                                                                                
(                                                                                                                                                                                                                                             
    `a` Nullable(Int64)                                                                                                                                                                                                                       
)                                                                                                                                                                                                                                             
ENGINE = Memory()                                                                                                                                                                                                                             
                                                                                                                                                                                                                                              
Ok.                                                                                                                                                                                                                                           

0 rows in set. Elapsed: 0.004 sec.

max42-dev.sas.yp-c.yandex.net :) insert into T values (1), (2), (3), (4), (5)

INSERT INTO T VALUES

Ok.

5 rows in set. Elapsed: 0.004 sec.

max42-dev.sas.yp-c.yandex.net :) create table default.DT as default.T engine = Distributed(test_cluster_two_shards, default, T)                                                                                                               
                                                                                                                                                                                                                                              
CREATE TABLE default.DT AS default.T                                                                                                                                                                                                          
ENGINE = Distributed(test_cluster_two_shards, default, T)                                                                                                                                                                                     
                                                                                                                                                                                                                                              
Ok.                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                              
0 rows in set. Elapsed: 0.005 sec.                                                                                                                                                                                                            
                                                                                                                                                                                                                                              
max42-dev.sas.yp-c.yandex.net :) select sumIf(42, (a % 2) = 0) from DT

SELECT sumIf(42, (a % 2) = 0)
FROM DT

→ Progress: 5.00 rows, 45.00 B (46.77 rows/s., 420.89 B/s.)
Received exception from server (version 20.8.1):
Code: 42. DB::Exception: Received from localhost:59000. DB::Exception: Aggregate function sum requires single argument: while receiving packet from 127.0.0.2:59000: While executing Remote.

0 rows in set. Elapsed: 0.107 sec.

max42-dev.sas.yp-c.yandex.net :) select sumIf(42, (a % 2) = 0) from T

SELECT sumIf(42, (a % 2) = 0)
FROM T

┌─sumIf(42, equals(modulo(a, 2), 0))─┐
│                                 84 │
└────────────────────────────────────┘

1 rows in set. Elapsed: 0.005 sec.

```

Reproduces on clickhouse client and clickhouse server from Arcadia since r7258384 (including current trunk version).

### PR DESCRIPTION
**Pull request by zhang2014**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
fixes #16574 
fixes #16231
fix remote query failure when using 'if' suffix aggregate function

### CODE REVIEW

**Comment by zhang2014** [comment]
> select sumIf(42, toNullable(toInt64(1))) from DT
I'm not sure if I should fix this. because the second argument type is not UInt8

**Comment by zhang2014** [comment]
CC: @KochetovNicolai

**Comment by KochetovNicolai** [comment]
> I'm not sure if I should fix this. because the second argument type is not UInt8

Agree. It is expected.

**Comment by zhang2014** [comment]
AST fuzzer — Assertion `V && "PHI node got a null value!"' failed -- looks unrelated
test_https_replication/test.py::test_replication_after_partition -- looks unrelated
test_distributed_ddl_parallel/test.py::test_two_in_parallel_two_queued -- looks unrelated

**Comment by alexey-milovidov** [comment]
One test has failed.

**Comment by zhang2014** [comment]
@alexey-milovidov This is correct?
``` text
SELECT NULL > 0

Query id: a792cf05-c316-425b-a2a1-1368790b3ace

┌─greater(NULL, 0)─┐
│ ᴺᵁᴸᴸ             │
└──────────────────┘

```

**Comment by zhang2014** [comment]
test have been added in https://github.com/ClickHouse/ClickHouse/pull/16592/commits/85ed639f8e74fc992e30b3c618bec5db43386125 from @KochetovNicolai

**Comment by zhang2014** [comment]
> Performance — 2 errors, 1 too long, 8 faster, 91 unstable

Some queries have unexpected duration    - unrelated
The test 'read_in_order_many_parts' is too slow to run as a whole. Investigate whether the create and fill queries can be sped up    - unrelated

**Comment by KochetovNicolai** [comment]
Also #16588 may be affected

**Review by KochetovNicolai — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
@KochetovNicolai The fix was not backported to 20.8:
```
$ clickhouse-client 
ClickHouse client version 21.1.1.5646.
Connecting to localhost:9000 as user default.
Connected to ClickHouse server version 20.8.12 revision 54438.

ClickHouse server version is older than ClickHouse client. It may indicate that the server is out of date and can be upgraded.

milovidov-desktop :) SELECT sumIf(toNullable(1), 1) FROM remote('127.0.0.{1,2}', system.one)

SELECT sumIf(toNullable(1), 1)
FROM remote('127.0.0.{1,2}', system.one)

Query id: fa832274-69c1-4686-9d47-230c2c5ba23c

→ Progress: 1.00 rows, 1.00 B (9.79 rows/s., 9.79 B/s.) 
Received exception from server (version 20.8.12):
Code: 42. DB::Exception: Received from localhost:9000. DB::Exception: Aggregate function sum requires single argument: while receiving packet from 127.0.0.2:9000: While executing Remote. 

0 rows in set. Elapsed: 0.133 sec.
```

**Comment by alexey-milovidov** [comment]
Looks like #18806.

**Pull request merged**
