### PR TITLE
Revert "Handle logs from rocksdb by ClickHouse internal logging (and enable debug rocksdb logging on CI)"

### PR DESCRIPTION
**Pull request by Algunenano**
Reverts ClickHouse/ClickHouse#64856

It should not have been merged

### CODE REVIEW

**Comment by robot-clickhouse-ci-2** [comment]
*This is an automated comment for commit 881cb2b305157459aa5bc94a8526d6ac9528f19f with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/65012/881cb2b305157459aa5bc94a8526d6ac9528f19f/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>A Sync</td><td>If it fails, ask a maintainer for help</td><td>⏳ pending</td></tr>
<tbody>
</table>
<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>Checks correctness of the PR's body</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

**Comment by alexey-milovidov** [comment]
@Algunenano, builds have failed and "A Sync" didn't finish.

**Comment by azat** [comment]
Hey @Algunenano. What was the problem with the original PR?

**Comment by Algunenano** [comment]
> Hey @Algunenano. What was the problem with the original PR?

It was merged without reviewing the private CI, which was broken by the changes.

**Pull request closed without merging**
