### PR TITLE
Download ccache if not exists in builds

### PR DESCRIPTION
**Pull request by alesapin**
Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by daveguest15** [comment]
Hiay

**Comment by alesapin** [comment]
@mergifyio update

**Comment by alesapin** [comment]
@mergifyio update

**Comment by alesapin** [comment]
@mergifyio update

**Comment by alesapin** [comment]
@mergifyio update

**Comment by alesapin** [comment]
@mergifyio update

**Comment by alesapin** [comment]
Ok, cache works + added release build.

**Comment by alesapin** [comment]
https://s3.amazonaws.com/clickhouse-builds/31227/8881886d1c2f9e0341a9b11292222e3244f3b842/clickhouse_build_check_(actions)/report.html

**Pull request merged**
