### PR TITLE
Remove H1 anchor tags from docs

### PR DESCRIPTION
**Pull request by rfraposa**
### Changelog category (leave one):
- Documentation (changelog entry is not required)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

Docusaurus was picking up the H1-level anchor tags as the <meta description>, which didn't look right when sharing /docs links on social media platforms.

### CODE REVIEW

**Comment by blinkov** [comment]
@rfraposa those were anchors for `clickhouse.com/docs/en/whatever/#that-thing-you-are-deleting`, thus there's a risk of introducing broken links, but it might have already happened on Docusaurus migration.

**Comment by blinkov** [comment]
mkdocs also could generate them, but there's no standard way to do it, so there's no way to guarantee that the current tool and the next tool will do it similarly. IIRC some of them were fixated in source files from pre-mkdocs era (or maybe previous mkdocs major release) to avoid breaking inbound links.

**Comment by rfraposa** [comment]
Either way - the current setup is not good, and removing the anchors fixes the meta tags without breaking anything.

**Comment by rfraposa** [comment]
And FWIW - the only anchors I removed were H1, which were only at the top of the pages. Any hyperlinks to hose anchors would still work fine.

**Review by DanRoscigno — APPROVED** [review]
LGTM, just heading anchors and whitespace.

**Pull request merged**
