### PR TITLE
Merging #11769 (Rank Correlation Spearman)

### PR DESCRIPTION
**Pull request by nikitamikhaylov**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- New Feature

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Added an aggregate function RankCorrelationSpearman which simply computes a rank correlation coefficient. Continuation of #11769

### CODE REVIEW

**Comment by nikitamikhaylov** [comment]
Test failures seems not related to changes in this PR.

**Comment by compasses** [comment]
@nikitamikhaylov hi, just want to know the background of the function rankCorr, cause I found a similar function corr.  So what's the difference between them and how I choose them, thanks.

**Comment by nikitamikhaylov** [comment]
> @nikitamikhaylov hi, just want to know the background of the function rankCorr, cause I found a similar function corr.  So what's the difference between them and how I choose them, thanks. 

It is too complex to explain here. It is better to read some articles. Note, corr is the Pearson correlation coefficient and rankCorr is the Spearman correlation coefficient. read about their differences. https://en.m.wikipedia.org/wiki/Correlation_and_dependence

**Comment by compasses** [comment]
@nikitamikhaylov Got it, thank you very much.

**Pull request merged**
