### PR TITLE
Rearrange sensitive data masker unit test

### PR DESCRIPTION
**Pull request by suzyw-w**
The following test failed on s390x and power platform:

> [  FAILED  ] Common.SensitiveDataMasker

The last two scenario out of the three try-catch scenario, checked against bad regexp, always come back failed.
Tried switch orders, the last two block always failed. Suspect this to be a **gtest** issue. 

Hence I re-created the same scenario in source code in src/Common/examples/test.cpp
The test result comes back with expected output. Please see the following log:

> masker.wipseSensitiveData, 5
> x = --a--   --b-- cccc --a-- *****
> masker.wipeSensitivedata(x) 3
> x is ----a----   ----b---- cccc ----a---- *****
> masker2.wipeSensitiveData 3
> query: SELECT id FROM mysql('localhost:3308', 'database', 'table', 'root', '******') WHERE ssn='000-00-0000' or email='hidden@hidden.test'
> Error SensitiveDataMasker: cannot compile re2: **, error: no argument for repetition operator: *. Look at https://github.com/google/re2/wiki/Syntax for reference.
> Error 427
> maskerbad.rulesCount: 0
> maskerbad.wipeSensitiveData: 0
> query_masking_rules configuration contains more than one rule named 'test'.
> query_masking_rules configuration, rule 'test' has no <regexp> node or <regexp> is empty.
> SensitiveDataMasker: cannot compile re2: ())(, error: unexpected ): ())(. Look at https://github.com/google/re2/wiki/Syntax for reference.: while adding query masking rule 'test'.

Hence it concludes that SensitiveDataMasker is working as expected. This pr is to addressed to avoid this gtest related issue.

### Changelog category (leave one):
- Testing Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
...
Work around for sensitive data masker unit test on power platform. 

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]
I don't understand the changes, but as long as they are relevant only to your platform, let's merge.

**Comment by alexey-milovidov** [comment]
Our continuous integration system found that your pull request description does not conform.

**Comment by bkuschel** [comment]
@alexey-milovidov can we merge this one?

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
@SuzyWangIBMer @bkuschel 

Cannot merge with failed tests.

**Pull request merged**
