### PR TITLE
Improve json sql functions by resuing `GeneratorJSONPath`

### PR DESCRIPTION
**Pull request by lgbo-ustc**
### Changelog category (leave one):
- Performance Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Improve JSON SQL functions by reusing `GeneratorJSONPath`. Since there are several `make_shared` in `GenerateorJSONPath`'s constructor, it has bad performance.

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by robot-ch-test-poll1** [comment]
*This is an automated comment for commit 1b44cc2a51e5fb1143c5f70b0cc06e628a460ed7 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/54735/1b44cc2a51e5fb1143c5f70b0cc06e628a460ed7/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>✅ success</td></tr>
<tbody>
</table>
</details>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>⏳ pending</td></tr>
<tbody>
</table>

**Review by antaljanosbenjamin — CHANGES_REQUESTED** [review]
Could you please update the changelog entry? You wrote an good changelog entry into the title and put the reasoning into the changelog entry. Unfortunately the title will not be included in the changelog as far as I know. Apart from that, the PR looks good.

Did you tested the performance with any of the performance tests? If you used a new query, maybe you can include that in our performance tests.

**Comment by lgbo-ustc** [comment]
> Could you please update the changelog entry? You wrote an good changelog entry into the title and put the reasoning into the changelog entry. Unfortunately the title will not be included in the changelog as far as I know. Apart from that, the PR looks good.
> 
> Did you tested the performance with any of the performance tests? If you used a new query, maybe you can include that in our performance tests.

Yes, serveral existing test cover the performance test.
image

**Review by antaljanosbenjamin — APPROVED** [review]
I modified the changelog item by adding the title of the PR to it, hope you don't mind.

**Pull request merged**
