### PR TITLE
Remove export of dynamic symbols

### LINKED ISSUE #43933: Azure AD based ssh extention poisons ClickHouse with preloaded shared library
```bash
$ clickhouse-client -h 127.0.0.1 --port 9000 -q 'show databases'
INFORMATION_SCHEMA
default
information_schema
system
Aborted (core dumped)
```

This also happens when just connecting an interactive session and disconnecting with ctrl+d.

**Does it reproduce on recent release?**

This is the latest release I get on Ubuntu 22.04

**How to reproduce**

Clickhouse Version:
```
$ clickhouse-client --version
ClickHouse client version 22.11.2.30 (official build).
```

Platform: 
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.1 LTS
Release:	22.04
Codename:	jammy
```
```
$ uname -r
5.15.0-1024-azure
```

**Error message and/or stacktrace**

```
$ gdb --args clickhouse-client -h 127.0.0.1 --port 9000 -q 'show databases'
GNU gdb (Ubuntu 12.1-0ubuntu1~22.04) 12.1
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from clickhouse-client...
(No debugging symbols found in clickhouse-client)
(gdb) r
Starting program: /usr/bin/clickhouse-client -h 127.0.0.1 --port 9000 -q show\ databases
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fb5e7206640 (LWP 1123636)]
[New Thread 0x7fb5e6a05640 (LWP 1123637)]
[New Thread 0x7fb5e6204640 (LWP 1123638)]
INFORMATION_SCHEMA
default
information_schema
system
[Thread 0x7fb5e7206640 (LWP 1123636) exited]
[Thread 0x7fb5e6204640 (LWP 1123638) exited]
[Thread 0x7fb5e6a05640 (LWP 1123637) exited]

Thread 1 "clickhouse-clie" received signal SIGSEGV, Segmentation fault.
0x00000000170a008c in free_default ()
(gdb) bt
#0  0x00000000170a008c in free_default ()
#1  0x00007fb5e7a8d07b in ?? () from /lib/x86_64-linux-gnu/libldap-2.5.so.0
#2  0x00007fb5eaeb424e in _dl_fini () at ./elf/dl-fini.c:142
#3  0x00007fb5eacb4495 in __run_exit_handlers (status=0, listp=0x7fb5eae88838 <__exit_funcs>, run_list_atexit=run_list_atexit@entry=true, run_dtors=run_dtors@entry=true) at ./stdlib/exit.c:113
#4  0x00007fb5eacb4610 in __GI_exit (status=<optimized out>) at ./stdlib/exit.c:143
#5  0x00007fb5eac98d97 in __libc_start_call_main (main=main@entry=0x7daf740 <main>, argc=argc@entry=7, argv=argv@entry=0x7fff30cf4368) at ../sysdeps/nptl/libc_start_call_main.h:74
#6  0x00007fb5eac98e40 in __libc_start_main_impl (main=0x7daf740 <main>, argc=7, argv=0x7fff30cf4368, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fff30cf4358) at ../csu/libc-start.c:392
#7  0x0000000007ab13ee in _start ()
```

**Additional context**

I can produce a core dump if necessary.

### PR DESCRIPTION
**Pull request by alexey-milovidov**
### Changelog category (leave one):
- Build/Testing/Packaging Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Don't expose symbols from ClickHouse binary to dynamic linker. It might fix #43933.

Note: there is a chance stack traces will become worse. But the symbol names should be able to resolve from the static symbol table if we are keeping it.

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
`getResource` failed, needs a fix.

**Comment by alexey-milovidov** [comment]
It was broken by the code for Illumos.

**Comment by robot-ch-test-poll1** [comment]
This is an automated comment for commit acac50f13350f9b72d0fac403dbcb5408562a3a1 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/47475/acac50f13350f9b72d0fac403dbcb5408562a3a1/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Comment by alexey-milovidov** [comment]
It allows to save 22% of the binary size:
```
milovidov@milovidov-desktop:~/work/ClickHouse/build$ ls -l programs/clickhouse programs/clickhouse-no-export-dynamic
-rwxrwxr-x 1 milovidov milovidov 484630112 jul  5 02:29 programs/clickhouse
-rwxrwxr-x 1 milovidov milovidov 378422688 jul  5 02:29 programs/clickhouse-no-export-dynamic
```

**Comment by alexey-milovidov** [comment]
We need to make `getResource` faster.

**Comment by zhanglistar** [comment]
@alexey-milovidov Any updates here? This is a good feature gluten project also wants, we want to reduce the library size.

**Comment by alexey-milovidov** [comment]
@zhanglistar I'm in the progress of

> We need to make `getResource` faster.

https://github.com/ClickHouse/ClickHouse/issues/52228

**Pull request merged**
