### PR TITLE
Cleanup for #12999. NFC

### PR DESCRIPTION
**Pull request by akuzm**
Cleanup with no functional changes in preparation for semicolon-terminated VALUES #12999

Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]
LGTM

**Comment by alexey-milovidov** [comment]
Fuzz test must be investigated.

**Comment by alexey-milovidov** [comment]
It's #12172.

**Comment by alexey-milovidov** [comment]
Performance test must be investigated.

**Comment by alexey-milovidov** [comment]
I don't see how the performance of array creation can be affected but it should be checked before merge.

**Comment by akuzm** [comment]
Fuzzer failure is the arrayElement nullable arg problem, already fixed.

**Comment by akuzm** [comment]
SQL-fuzzy failure: https://github.com/ClickHouse/ClickHouse/issues/13335

**Pull request merged**
