### PR TITLE
Flexible configuration for disks

### PR DESCRIPTION
**Pull request by kssenii**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Allow to configure any kind of object storage with any kind of metadata type.

### CODE REVIEW

**Comment by robot-clickhouse** [comment]
*This is an automated comment for commit 653d48a552a66cec3bf50f8e9af67c9868826aab with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/58357/653d48a552a66cec3bf50f8e9af67c9868826aab/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/58357/653d48a552a66cec3bf50f8e9af67c9868826aab/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Comment by CheSema** [comment]
Can you give me a hint what is `getBasePath()`?

**Comment by kssenii** [comment]
> Can you give me a hint what is getBasePath()?

I removed it.

**Review by CheSema — APPROVED** [review]

**Comment by kssenii** [comment]
> Integration tests (tsan) [6/6] — fail: 1

test_storage_kafka/test.py::test_system_kafka_consumers_rebalance_mv

**Comment by danthegoodman1** [comment]
@alexey-milovidov will docs be added for this soon? I didnt' see any in the PR and this certainly should be in the docs

**Comment by danthegoodman1** [comment]
image
even just having this and explaining what the different metadata types do would be useful

**Comment by tbragin** [comment]
@danthegoodman1 good point about docs. We plan to add more to this feature, so we were planning to document it after additional enhancements, but the feature is already useful in its current state, so we can start now. A PR has been opened, we would love your thoughts, if you have time to take a look: https://github.com/ClickHouse/ClickHouse/pull/60024 

cc @justindeguzman as well

**Comment by danthegoodman1** [comment]
@tbragin I'll go through that and see what comments I can offer

**Pull request merged**
