### PR TITLE
Show server error code name in clickhouse client

### PR DESCRIPTION
**Pull request by vdimir**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Show server error code name in client

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
We can also do it in more generic way: include the name of the error code in exception message.

`Code: 395. DB::Exception: Received from localhost:9000. DB::Exception: Value passed to 'throwIf' function is non zero: While processing throwIf(1).`

`Code: 395. DB::Exception: Received from localhost:9000. DB::Exception: Value passed to 'throwIf' function is non zero: While processing throwIf(1). (FUNCTION_THROW_IF_VALUE_IS_NON_ZERO)`

**Comment by vdimir** [comment]
@alexey-milovidov 
> We can also do it in more generic way: include the name of the error code in exception message.

You mean to only to change order not to break tests?

**Comment by alexey-milovidov** [comment]
> You mean to only to change order not to break tests?

I mean, add it to the place where exception messages are formed: getCurrentExceptionMessage, etc.
(And also, yes - add the name at the end to avoid breaking of 3rd party scripts).

**Comment by alexey-milovidov** [comment]
#26172

**Pull request closed without merging**
