### PR TITLE
Bump abseil to latest HEAD

### PR DESCRIPTION
**Pull request by rschu1ze**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by robot-ch-test-poll2** [comment]
*This is an automated comment for commit da91dd64283de30172fca6cd30df4c711d291b44 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/65048/da91dd64283de30172fca6cd30df4c711d291b44/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>A Sync</td><td>If it fails, ask a maintainer for help</td><td>⏳ pending</td></tr>
<tbody>
</table>
<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>Checks correctness of the PR's body</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

**Comment by Algunenano** [comment]
You should be able to remove this line with absl HEAD -> https://github.com/ClickHouse/ClickHouse/blob/305bc7a910b6de57a566f12b83f75ff7a871ff14/.clang-tidy#L40

**Comment by rschu1ze** [comment]
> You should be able to remove this line with absl HEAD ->
> 
> https://github.com/ClickHouse/ClickHouse/blob/305bc7a910b6de57a566f12b83f75ff7a871ff14/.clang-tidy#L40

Good catch, let me try ...

**Review by alexey-milovidov — APPROVED** [review]

**Comment by rschu1ze** [comment]
Unfortunately, the s390x build broke due to a compiler error ([build log](https://s3.amazonaws.com/clickhouse-builds/PRs/65048/1f17ddc6fe35be95736b448ebb3b73123c034196/binary_s390x/build_log.log)).

I was able to bisect the bad commit in abseil and opened a bug at Clang: https://github.com/llvm/llvm-project/issues/95119

To unblock this PR, I also changed abseil from upstream to ClickHouse's [fork](https://github.com/ClickHouse/abseil-cpp) where the bad commit is reverted.

**Comment by rschu1ze** [comment]
ClickHouse Integration Tests (aarch64) [5/6]: #64451
ClickHouse Stateless Tests (tsan, S3 Storage) [4/5]: #65014
ClickHouse Stress Test (ubsan): https://github.com/ClickHouse/ClickHouse/issues/65043
ClickHouse Upgrade Check (debug): new settings not reflected in setting history

**Pull request merged**
