### PR TITLE
update cppkafka to v0.4.1

### PR DESCRIPTION
**Pull request by ilejn**
Update cppkafka to v0.4.1 because it has https://github.com/mfontanini/cppkafka/pull/309 .

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by robot-clickhouse-ci-2** [comment]
*This is an automated comment for commit 1fb31681cc0f0d7649a254e92e8c5738022af2f3 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/61119/1fb31681cc0f0d7649a254e92e8c5738022af2f3/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

**Comment by alexey-milovidov** [comment]
@ilejn, it failed: https://s3.amazonaws.com/clickhouse-test-reports/61119/1fb31681cc0f0d7649a254e92e8c5738022af2f3/integration_tests__tsan__[6_6].html

**Comment by ilejn** [comment]
> @ilejn, it failed: [https://s3.amazonaws.com/clickhouse-test-reports/61119/1fb31681cc0f0d7649a254e92e8c5738022af2f3/integration_tests__tsan__[6_6].html](https://s3.amazonaws.com/clickhouse-test-reports/61119/1fb31681cc0f0d7649a254e92e8c5738022af2f3/integration_tests__tsan__%5B6_6%5D.html)

Not sure that the issue caused by this very PR, but it is a good opportunity to fix it anyway.

Alexey @alexey-milovidov could you advise, if absence of line numbers in sanitizer output https://s3.amazonaws.com/clickhouse-test-reports/61119/1fb31681cc0f0d7649a254e92e8c5738022af2f3/integration_tests__tsan__[6_6]/integration_run_parallel4_0.log is a transient issue, or we have to live with what we have?

It looks like
```
E           Exception: Sanitizer assert found for instance ==================
E           WARNING: ThreadSanitizer: data race (pid=1)
E             Read of size 8 at 0x7b78001d8158 by thread T991 (mutexes: read M0, write M1, write M2):
E               #0 <null> <null> (clickhouse+0x70a28b7) (BuildId: 2646132dae43f32a80fa2dc0c01e6609d8cb97b0)
E               #1 <null> <null> (clickhouse+0x1d509edb) (BuildId: 2646132dae43f32a80fa2dc0c01e6609d8cb97b0)
E               #2 <null> <null> (clickhouse+0x1d50862b) (BuildId: 2646132dae43f32a80fa2dc0c01e6609d8cb97b0)
E               #3 <null> <null> (clickhouse+0x1d5d732a) (BuildId: 2646132dae43f32a80fa2dc0c01e6609d8cb97b0)
E               #4 <null> <null> (clickhouse+0x1d504389) (BuildId: 2646132dae43f32a80fa2dc0c01e6609d8cb97b0)
E               #5 <null> <null> (clickhouse+0x1d5ecf1b) (BuildId: 2646132dae43f32a80fa2dc0c01e6609d8cb97b0)
E               #6 <null> <null> (clickhouse+0x70a6b8e) (BuildId: 2646132dae43f32a80fa2dc0c01e6609d8cb97b0)
E           
E             Previous write of size 8 at 0x7b78001d8158 by thread T990:
E               #0 <null> <null> (clickhouse+0x1d4f00bd) (BuildId: 2646132dae43f32a80fa2dc0c01e6609d8cb97b0)
E               #1 <null> <null> (clickhouse+0x1d4eb7fe) (BuildId: 2646132dae43f32a80fa2dc0c01e6609d8cb97b0)
E               #2 <null> <null> (clickhouse+0x1d4e4fb9) (BuildId: 2646132dae43f32a80fa2dc0c01e6609d8cb97b0)
E               #3 <null> <null> (clickhouse+0x1d5ecf1b) (BuildId: 2646132dae43f32a80fa2dc0c01e6609d8cb97b0)
E               #4 <null> <null> (clickhouse+0x70a6b8e) (BuildId: 2646132dae43f32a80fa2dc0c01e6609d8cb97b0)
```

**Comment by ilejn** [comment]
Probably this is https://github.com/ClickHouse/ClickHouse/issues/60443 AKA https://github.com/ClickHouse/ClickHouse/issues/60939

**Comment by alexey-milovidov** [comment]
@ilejn, Remove TSan suppressions, and fix the root cause issue in rdkafka.

**Comment by ilejn** [comment]
> @ilejn, Remove TSan suppressions, and fix the root cause issue in rdkafka.

Alexey @alexey-milovidov , this is (most likely) https://github.com/confluentinc/librdkafka/issues/4625 .

I think that we have to fix it in our fork as well.

**Comment by azat** [comment]
>Probably this is https://github.com/ClickHouse/ClickHouse/issues/60443 AKA https://github.com/ClickHouse/ClickHouse/issues/60939

It is

>Remove TSan suppressions, and fix the root cause issue in rdkafka

Initially it had been done as suppression to give the upstream time to review the patches, but maybe they are too slow, then it is OK to backport https://github.com/confluentinc/librdkafka/pull/4630

**Comment by ilejn** [comment]
> > Probably this is #60443 AKA #60939
> 
> It is
> 
> > Remove TSan suppressions, and fix the root cause issue in rdkafka
> 
> Initially it had been done as suppression to give the upstream time to review the patches, but maybe they are too slow, then it is OK to backport [confluentinc/librdkafka#4630](https://github.com/confluentinc/librdkafka/pull/4630)

They are slow indeed.
I think that chances that someone in upstream come up with more elegant/better solution are not high.

**Comment by alexey-milovidov** [comment]
@ilejn, we we use cppkafka if there is something here?: https://github.com/confluentinc/librdkafka/tree/master/src-cpp

**Comment by alexey-milovidov** [comment]
PS. I don't know why there are no symbols in integration tests.

**Comment by ilejn** [comment]
> @ilejn, we we use cppkafka if there is something here?: https://github.com/confluentinc/librdkafka/tree/master/src-cpp

No clue. 
May be @filimonov can shed some light?

**Comment by azat** [comment]
Indeed the symbolizer is broken, and here is a fix - https://github.com/ClickHouse/ClickHouse/pull/61147

And AFAICS the suppressions does not without symbolizer, so everything was expected.

**Comment by filimonov** [comment]
> @ilejn, we we use cppkafka if there is something here?: https://github.com/confluentinc/librdkafka/tree/master/src-cpp

It's quite ugly c++98 wrapper (created by non c++ guy or very-very long ago). Almost as good / bad as using pure c interface.

Cppkafka is quite simple c++14 wrapper on the top of librdkafka. Not maintained well.

There is one more wrapper on top of librdkafka now in cpp+17 standard  (i didn't try that, seems bit more alive) - see https://github.com/morganstanley/modern-cpp-kafka?tab=readme-ov-file#why-its-here

**Comment by ilejn** [comment]
Errors/failures:
01459_manual_write_to_replicas_quorum (stateless)
02784_parallel_replicas_automatic_decision_join (stateless)
test_materialized_mysql_database/test.py::test_select_without_columns_8_0 (integration, tsan)
UBSAN finding
```
/build/base/poco/Net/src/TCPServerDispatcher.cpp:126:30: runtime error: member access within address 0x555598718bd0 which does not point to an object of type 'Poco::Net::TCPServerDispatcher'

 invalid vptr
 
    #0 0x55558b7e3973 in Poco::Net::TCPServerDispatcher::run() build_docker/./base/poco/Net/src/TCPServerDispatcher.cpp:126:30
    #1 0x55558ba1528f in Poco::PooledThread::run() build_docker/./base/poco/Foundation/src/ThreadPool.cpp:188:14
    #2 0x55558ba10390 in Poco::ThreadImpl::runnableEntry(void*) build_docker/./base/poco/Foundation/src/Thread_POSIX.cpp:335:27
    #3 0x7ffff7e17ac2  (/lib/x86_64-linux-gnu/libc.so.6+0x94ac2) (BuildId: c289da5071a3399de893d2af81d6a30c62646e1e)
    #4 0x7ffff7ea984f  (/lib/x86_64-linux-gnu/libc.so.6+0x12684f) (BuildId: c289da5071a3399de893d2af81d6a30c62646e1e)
```    
AST fuzzer with MSAN - not sure that I understand what happened.

All issues are not relevant, thread sanitizer error about kafka is gone because symbolizer is fixed by https://github.com/ClickHouse/ClickHouse/pull/61147

**Comment by alexey-milovidov** [comment]
@ilejn This is a blocker:
```
    #0 0x55558b7e3973 in Poco::Net::TCPServerDispatcher::run() build_docker/./base/poco/Net/src/TCPServerDispatcher.cpp:126:30
    #1 0x55558ba1528f in Poco::PooledThread::run() build_docker/./base/poco/Foundation/src/ThreadPool.cpp:188:14
    #2 0x55558ba10390 in Poco::ThreadImpl::runnableEntry(void*) build_docker/./base/poco/Foundation/src/Thread_POSIX.cpp:335:27
    #3 0x7ffff7e17ac2  (/lib/x86_64-linux-gnu/libc.so.6+0x94ac2) (BuildId: c289da5071a3399de893d2af81d6a30c62646e1e)
    #4 0x7ffff7ea984f  (/lib/x86_64-linux-gnu/libc.so.6+0x12684f) (BuildId: c289da5071a3399de893d2af81d6a30c62646e1e)

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /build/base/poco/Net/src/TCPServerDispatcher.cpp:126:30 in 
[Inferior 1 (process 19) exited with code 01]
```

If it is fixed in master, let's merge with the master.

**Comment by ilejn** [comment]
None of the issues seems to be related to this PR, namely

- riscv64 build failure
- 01508_partition_pruning_long stateless test (happened in https://github.com/ClickHouse/ClickHouse/pull/61524 as well)
- 02782_uniq_exact_parallel_merging_bug (timeout, happened in https://github.com/ClickHouse/ClickHouse/pull/61524 as well)
- 01459_manual_write_to_replicas (timeout, happened in https://github.com/ClickHouse/ClickHouse/pull/61524 as well)
- 01171_mv_select_insert_isolation_long (timeout, happened in https://github.com/ClickHouse/ClickHouse/pull/59531 as well)
- stress test MSAN
```
/var/log/clickhouse-server/clickhouse-server.err.log:2024.03.20 03:14:33.332216 [ 4567 ] {5d2d1418-aa08-41f5-92e2-5286511e08d8} <Fatal> : Logical error: 'Unexpected return type from equals. Expected Nullable. Got UInt8'.
/var/log/clickhouse-server/clickhouse-server.err.log:2024.03.20 03:14:57.643164 [ 3176 ] {} <Fatal> Application: Child process was terminated by signal 6.
```

**Pull request merged**
