### PR TITLE
Resubmit #48821

### PR DESCRIPTION
**Pull request by kssenii**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Reverted revert of https://github.com/ClickHouse/ClickHouse/pull/48821

### CODE REVIEW

**Comment by robot-ch-test-poll2** [comment]
This is an automated comment for commit e2a45261086f2405b57b7779ec06ef2d500882f3 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/51208/e2a45261086f2405b57b7779ec06ef2d500882f3/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Comment by kssenii** [comment]
A lot of integration tests failed with errors like 
```
>           raise subprocess.CalledProcessError(exit_code, cmd)
E           subprocess.CalledProcessError: Command '['iptables', '--wait', '-I', 'DOCKER-USER', '1', '-p', 'tcp', '-s', '172.16.2.2', '-d', '172.16.2.3', '-j', 'DROP']' returned non-zero exit status 1.
```
also this feature is tested only with stateless tests, so I assume ok to merge.

**Comment by kssenii** [comment]
> Integration tests (release) [4/4] 

test_table_function_redis

> Stateless tests (asan) [2/4] — fail: 1

02434_cancel_insert_when_client_dies
```
==15059==Unable to get registers from thread 14964.
```

**Comment by kssenii** [comment]
> Integration tests (release) [2/4] 

test_storage_rabbitmq

**Pull request merged**
