### PR TITLE
Convert skip_list .json into first line comments

### PR DESCRIPTION
**Pull request by vitlibar**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category:
- Build/Testing/Packaging Improvement

Changelog entry:
Convert `skip_list .json` into first line comments.

Now instead of `skip_list.json` we have tags in the first line of each test file.
The tags control which tests will be skipped. The tags line looks like this:

```
-- Tags: no-asan, no-debug
-- Tag no-asan was added here because ...

SELECT 1; -- here the rest of the test
```

The tags line  contains comma-separated list of tags. The tags line can be omitted.
The tags line must be the first line, with only exception when the first line is a shebang - in this case the tags line is the second line.

List of supported tags:

```
disabled - test is disabled
no-asan - test should be skipped when running with sanitizer
no-msan
no-tsan
no-ubsan
no-debug - test should be skipped when running with this type of build
no-release
no-unbundled
no-fasttest - test is not one of the fast tests
no-replicated-database - test should be skipped with the type of build when the test database is Replicated
no-ordinary-database - test should be skipped with the type of build when the default database type is Ordinary
no-parallel / sequential - test should not be run in parallel with other tests
long / race / deadlock - test takes more time to run
replica / zookeeper - requires zookeeper to run
shard / distributed / global - shard-related test (requires clickhouse-server to listen 127.0.0.2 127.0.0.3)
```

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
Maybe also make `--testmode` and `--use-tags` by default and remove these options from clickhouse-client?

**Comment by vitlibar** [comment]
> Maybe also make `--testmode` and `--use-tags` by default and remove these options from clickhouse-client?

I've removed `--use-tags`.

`--testmode` seems to be useful cause it allows clickhouse-client not to spend CPU in release on test hints and test tags.

**Comment by vitlibar** [comment]
The failures don't seem to be related.

**Comment by alexey-milovidov** [comment]
Need to also update the documentation: https://clickhouse.tech/docs/en/development/tests/#functional-tests

**Pull request merged**
