### PR TITLE
Fix oss-fuzz build

### PR DESCRIPTION
**Pull request by nickitat**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Do not test
- [x]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-ch-test-poll** [comment]
*This is an automated comment for commit 109bd52296550f506b14134b934c6eb8fd3ec094 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/67235/109bd52296550f506b14134b934c6eb8fd3ec094/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

**Comment by nickitat** [comment]
pr to upstream https://github.com/google/oss-fuzz/pull/12283

**Comment by nickitat** [comment]
@nikitamikhaylov would you mind to check this one too?

**Comment by nikitamikhaylov** [comment]
@nickitat Sure!

**Review by nikitamikhaylov — APPROVED** [review]

**Comment by nickitat** [comment]
`AST fuzzer (ubsan)` - https://github.com/ClickHouse/ClickHouse/issues/65967
`Stateless tests (tsan) [4/4]` - https://github.com/ClickHouse/ClickHouse/issues/37686

**Pull request merged**
