### PR TITLE
Fix backup restore path for AzureBlobStorage

### PR DESCRIPTION
**Pull request by SmitaRKulkarni**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix backup restore path for AzureBlobStorage to include specified blob path

cc @vitlibar @bianpengyuan

### CODE REVIEW

**Comment by robot-ch-test-poll2** [comment]
*This is an automated comment for commit 33c0ac5cc6e1befca39f54a2fccfaf8f6eb8ed0c with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/62447/33c0ac5cc6e1befca39f54a2fccfaf8f6eb8ed0c/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

**Review by vitlibar — APPROVED** [review]

**Review by bianpengyuan — APPROVED** [review]
:heart:

**Comment by SmitaRKulkarni** [comment]
Unrelated failures:
AST fuzzer (tsan) - Logical error: 'Cannot capture column 2 because it has incompatible type: got Nullable(UInt8), but UInt8 is expected.'.
Performance Comparison [1/4]
Stateless tests (ubsan) [2/2] - DB::NetException: I/O error: Broken pipe, while writing to socket

**Comment by tavplubix** [comment]
Looks like `test_backup_restore_azure_blob_storage` became flaky after this PR: [CI DB](https://play.clickhouse.com/play?user=play#CldJVEgKICAgICd0ZXN0X2JhY2t1cF9yZXN0b3JlX2F6dXJlX2Jsb2Jfc3RvcmFnZScgQVMgbmFtZV9zdWJzdHIsCiAgICA5MCBBUyBpbnRlcnZhbF9kYXlzLAogICAgKCdTdGF0ZWxlc3MgdGVzdHMgKGFzYW4pJywgJ1N0YXRlbGVzcyB0ZXN0cyAoYWRkcmVzcyknLCAnU3RhdGVsZXNzIHRlc3RzIChhZGRyZXNzLCBhY3Rpb25zKScpIEFTIGJhY2twb3J0X2FuZF9yZWxlYXNlX3NwZWNpZmljX2NoZWNrcwpTRUxFQ1QKICAgIHRvU3RhcnRPZkRheShjaGVja19zdGFydF90aW1lKSBBUyBkLAogICAgY291bnQoKSwKICAgIGdyb3VwVW5pcUFycmF5KHB1bGxfcmVxdWVzdF9udW1iZXIpIEFTIHBycywKICAgIGFueShyZXBvcnRfdXJsKQpGUk9NIGNoZWNrcwpXSEVSRSAoKG5vdygpIC0gdG9JbnRlcnZhbERheShpbnRlcnZhbF9kYXlzKSkgPD0gY2hlY2tfc3RhcnRfdGltZSkgQU5EIChwdWxsX3JlcXVlc3RfbnVtYmVyIE5PVCBJTiAoCiAgICBTRUxFQ1QgcHVsbF9yZXF1ZXN0X251bWJlciBBUyBwcm4KICAgIEZST00gY2hlY2tzCiAgICBXSEVSRSAocHJuICE9IDApIEFORCAoKG5vdygpIC0gdG9JbnRlcnZhbERheShpbnRlcnZhbF9kYXlzKSkgPD0gY2hlY2tfc3RhcnRfdGltZSkgQU5EIChjaGVja19uYW1lIElOIChiYWNrcG9ydF9hbmRfcmVsZWFzZV9zcGVjaWZpY19jaGVja3MpKQopKSBBTkQgKHBvc2l0aW9uKHRlc3RfbmFtZSwgbmFtZV9zdWJzdHIpID4gMCkgQU5EICh0ZXN0X3N0YXR1cyBJTiAoJ0ZBSUwnLCAnRVJST1InLCAnRkxBS1knKSkKR1JPVVAgQlkgZApPUkRFUiBCWSBkIERFU0MK)

**Comment by clickgapai** [comment]
Hi @SmitaRKulkarni @vitlibar @bianpengyuan — while reviewing this PR I found the following:

- **Bug (P2):** `BackupWriterAzureBlobStorage::copyFile` writes destination outside `blob_path`, leaking blobs to container root — https://github.com/ClickHouse/ClickHouse/issues/104059

Happy to discuss — close anything that's wrong or already addressed.

**Pull request merged**
