### PR TITLE
Fix: allow IPv6 for bloom filter

### LINKED ISSUE #54162: ngram bloomfilter index based on IPv6 type breaks in v23.3
**Describe the unexpected behaviour**
We are trying to upgrade from v22.3-lts to v23.3-lts. This is when we noticed that v23.3 wasn't happy with ngram bloom filter indices we had defined on IPv6 type.

**How to reproduce**

- v22.3: https://fiddle.clickhouse.com/623b1437-2ad7-4803-b33f-8793d3e9a87e
- v23.3: https://fiddle.clickhouse.com/9eaef7e1-c306-45d2-bffa-1cd359337a87

* Which ClickHouse server version to use: v23.3-lts
* Queries to run that lead to unexpected result
```
DROP TABLE IF EXISTS table1;
CREATE TABLE table1 (foo IPv6, INDEX fooIndex foo TYPE ngrambf_v1(8,512,3,0) GRANULARITY 1) ENGINE = MergeTree() ORDER BY foo;
DETACH table table1;
ATTACH TABLE table1;
DROP TABLE table1;
```
**Expected behavior**
 I would ideally expect this to behave the same as is behaves in v22.3-lts.

**Error message and/or stacktrace**
```
Received exception from server (version 23.3.8):
Code: 80. DB::Exception: Received from localhost:9000. DB::Exception: Ngram and token bloom filter indexes can only be used with column types `String`, `FixedString`, `LowCardinality(String)`, `LowCardinality(FixedString)`, `Array(String)` or `Array(FixedString)`. (INCORRECT_QUERY)
(query: CREATE TABLE table1 (foo IPv6, INDEX fooIndex foo TYPE ngrambf_v1(8,512,3,0) GRANULARITY 1) ENGINE = MergeTree() ORDER BY foo;)
```
**Additional context**

I think the issue here is that IPv6 used to be based on `FixedString(16)` if I recall correctly. But since `v23.3`, it looks like it's now based on IPv6 native type: `https://github.com/ClickHouse/ClickHouse/pull/43221` (which seems to have an underlying type of UInt128). 

What could be the possible fix/approach here for the upgrade since this change looks backwards incompatible.

Thank you in advance for taking a look at my issue.

### PR DESCRIPTION
**Pull request by yakov-olkhovskiy**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Allow IPv6 for bloom filter, backward compatibility issue.

closes #54162

### CODE REVIEW

**Comment by robot-ch-test-poll3** [comment]
This is an automated comment for commit a3216c78ef4121bdc2f6c53e46af7a9bcd61c076 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/54200/a3216c78ef4121bdc2f6c53e46af7a9bcd61c076/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Review by alexey-milovidov — CHANGES_REQUESTED** [review]
Missing tests.

**Comment by ywangtht** [comment]
The title of this bug is misleading. 
It fixed the skip index of ngrambf_v1 but not for general bloom_filter of IPv6 type.
See bug: https://github.com/ClickHouse/ClickHouse/issues/58885

**Comment by yakov-olkhovskiy** [comment]
@ywangtht the title is correct - the issue was that IPv6 wasn't allowed for bloom filter manifesting as an error on `CREATE TABLE ...` as `Code: 80. DB::Exception: ... Ngram and token bloom filter indexes can only be used with column types ...`. You just hit different, though maybe related, issue...

**Pull request merged**
