### PR TITLE
Minor: replaced expression with LEGACY_MAX_LEVEL

### PR DESCRIPTION
**Pull request by Enmk**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Non-functional change: just replaced expression with appropriate constant.

### CODE REVIEW

**Comment by robot-clickhouse-ci-2** [comment]
*This is an automated comment for commit 0dbd569b50828003dc6a55af56717dab92054d8f with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/61268/0dbd569b50828003dc6a55af56717dab92054d8f/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

**Review by yakov-olkhovskiy — APPROVED** [review]

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
@Enmk, please merge with the master branch.

**Comment by alexey-milovidov** [comment]
@Enmk we have fixed this test: https://s3.amazonaws.com/clickhouse-test-reports/61268/01a54d91b2b173b9cbdb94e1f8601657fddf8677/stateless_tests__release__old_analyzer__s3__databasereplicated__[2_4].html

Could you please merge with the master branch again?

**Comment by alexey-milovidov** [comment]
@Enmk, currently, it is not mergeable. Could you please merge with the master branch?

**Pull request merged**
