### PR TITLE
Fix test "02494_query_cache_drop.sql"

### PR DESCRIPTION
**Pull request by CurtizJ**
Reverts ClickHouse/ClickHouse#45912

### CODE REVIEW

**Comment by CurtizJ** [comment]
Test `02494_query_cache_drop_cache` is broken in master.

**Comment by rschu1ze** [comment]
Thanks, I'll check ... (as far as I remember, the test was locally green when I merged)

**Comment by rschu1ze** [comment]
Can reproduce the issue locally. It happens if the new test "02494_query_cache_squash_partial_results" (introduced with #45912) runs immediately prior to "02494_query_cache_drop_cache", apparently I did not run this combination locally :/

If it is okay, I'd push a commit in this PR which fixes this instead of rolling everything back.

**Comment by rschu1ze** [comment]
I am technically not the author of this PR which implies that I can approve and merge it :sunglasses: (fast test + the functional tests which ran are green)

**Review by rschu1ze — APPROVED** [review]

**Pull request merged**
