### PR TITLE
Partial fix of clang build stack unwinding (omit-frame-pointer)

### PR DESCRIPTION
**Pull request by amosbird**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Non-significant (changelog entry is not required)

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Follow up https://github.com/ClickHouse/ClickHouse/pull/8151

Needed by https://github.com/ClickHouse/ClickHouse/pull/10585

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
Tests have passed, let's look at the performance...

**Comment by alexey-milovidov** [comment]
Yes, it gives one percent more :)
Let's also compare all combined together...

**Comment by alexey-milovidov** [comment]
Now it looks like that gcc and clang are on-par.
Let's see what will change after update to clang-10.

And we should make more careful test with `performance-test`.

**Comment by alexey-milovidov** [comment]
https://raw.githubusercontent.com/ClickHouse/ClickHouse/5a5d64eb90cb877009b576f7d66a56656d7154f2/website/benchmark_gcc_clang.html

**Comment by amosbird** [comment]
hmm, even though that page has `<!DOCTYPE html>` but it is still opened as raw text

**Comment by alexey-milovidov** [comment]
Just download and open directly.

**Comment by alexey-milovidov** [comment]
I have published these benchmarks on the website: https://presentations.clickhouse.tech/original_website/benchmark_gcc_clang.html

Note that this is just some noisy results, not like real performance tests.

**Comment by alexey-milovidov** [comment]
We have to revert again because it reproduces in some other places:

```
$ clickhouse-client --host 1.1.1.1
ClickHouse client version 20.5.1.1.
Connecting to 1.1.1.1:9000 as user default.
terminating with uncaught exception of type DB::NetException: Timeout: connect timed out: 1.1.1.1:9000 (1.1.1.1:9000)
Aborted (core dumped)
```

**Comment by amosbird** [comment]
I think I've figured out some pattern of this unwinding failure:

It's related to exceptions thrown in ctor and created by std::make_unique or std::make_shared. However I cannot create a minimal test case to reproduce...

**Pull request merged**
