### PR TITLE
Add global flags to base/ libraries

### PR DESCRIPTION
**Pull request by Algunenano**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
...

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

Attempt to fix https://github.com/ClickHouse/ClickHouse/pull/42866#discussion_r1017067793

The only way I could find to use the global flags when building these libraries was to "link" them with the global interface, which has the `-Werror` flag.

This turned:
```
/usr/bin/ccache /usr/lib/ccache/bin/clang --target=x86_64-linux-gnu --sysroot=/mnt/ch/ClickHouse/cmake/linux/../../contrib/sysroot/linux-x86_64/x86_64-linux-gnu/libc -DHAS_RESERVED_IDENTIFIER -I/mnt/ch/ClickHouse/base/glibc-compatibility/libcxxabi -I/mnt/ch/ClickHouse/base/glibc-compatibility/musl/x86_64 --gcc-toolchain=/mnt/ch/ClickHouse/cmake/linux/../../contrib/sysroot/linux-x86_64 -fdiagnostics-color=always -Xclang -fuse-ctor-homing  -gdwarf-aranges -pipe -mssse3 -msse4.1 -msse4.2 -mpclmul -mpopcnt -fasynchronous-unwind-tables -falign-functions=32 -mbranches-within-32B-boundaries  -fdiagnostics-absolute-paths -fexperimental-new-pass-manager -fomit-frame-pointer -g -O0 -g -gdwarf-4 -fno-inline    -D OS_LINUX -Wno-unused-command-line-argument -Wno-unused-but-set-variable -Wno-builtin-requires-header -std=gnu11 -MD -MT base/glibc-compatibility/CMakeFiles/glibc-compatibility.dir/musl/getentropy.c.o -MF base/glibc-compatibility/CMakeFiles/glibc-compatibility.dir/musl/getentropy.c.o.d -o base/glibc-compatibility/CMakeFiles/glibc-compatibility.dir/musl/getentropy.c.o -c /mnt/ch/ClickHouse/base/glibc-compatibility/musl/getentropy.c
```

Into:
```
/usr/bin/ccache /usr/lib/ccache/bin/clang --target=x86_64-linux-gnu --sysroot=/mnt/ch/ClickHouse/cmake/linux/../../contrib/sysroot/linux-x86_64/x86_64-linux-gnu/libc -DHAS_RESERVED_IDENTIFIER -DSTD_EXCEPTION_HAS_STACK_TRACE=1 -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS -I/mnt/ch/ClickHouse/base/glibc-compatibility/libcxxabi -I/mnt/ch/ClickHouse/base/glibc-compatibility/musl/x86_64 -I/mnt/ch/ClickHouse/base/glibc-compatibility/memcpy -isystem /mnt/ch/ClickHouse/contrib/libcxx/include -isystem /mnt/ch/ClickHouse/contrib/libcxxabi/include -isystem /mnt/ch/ClickHouse/contrib/libunwind/include --gcc-toolchain=/mnt/ch/ClickHouse/cmake/linux/../../contrib/sysroot/linux-x86_64 -fdiagnostics-color=always -Xclang -fuse-ctor-homing  -gdwarf-aranges -pipe -mssse3 -msse4.1 -msse4.2 -mpclmul -mpopcnt -fasynchronous-unwind-tables -falign-functions=32 -mbranches-within-32B-boundaries  -fdiagnostics-absolute-paths -fexperimental-new-pass-manager -fomit-frame-pointer -g -O0 -g -gdwarf-4 -fno-inline    -D OS_LINUX -Wno-unused-command-line-argument -Wno-unused-but-set-variable -Wno-builtin-requires-header -Werror -std=gnu11 -MD -MT base/glibc-compatibility/CMakeFiles/glibc-compatibility.dir/musl/getentropy.c.o -MF base/glibc-compatibility/CMakeFiles/glibc-compatibility.dir/musl/getentropy.c.o.d -o base/glibc-compatibility/CMakeFiles/glibc-compatibility.dir/musl/getentropy.c.o -c /mnt/ch/ClickHouse/base/glibc-compatibility/musl/getentropy.c
```

The new / second build has the extra flags from the global interface:
* -isystem /mnt/ch/ClickHouse/contrib/libcxx/include
* -isystem /mnt/ch/ClickHouse/contrib/libcxxabi/include -isystem /mnt/ch/ClickHouse/contrib/libunwind/include
* -DSTD_EXCEPTION_HAS_STACK_TRACE=1
* -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS
* -Werror

So it'd have prevented #43065:
```
[1/1] /usr/bin/ccache /usr/lib/ccache/bin/clang --target=x86_64-linux-gnu --sysroot=/mnt/ch/ClickHouse/cmake/linux/../../contrib/sysroot/linux-x86_64/x86_64-linux-gnu/libc -DHAS_RESERVED_IDENTIFIER -DSTD_EXCEPTION_HAS_STACK_TRACE=1 -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS -I/mnt/ch/ClickHouse/base/glibc-compatibility/libcxxabi -I/mnt/ch/ClickHouse/base/glibc-compatibility/musl/x86_64 -I/mnt/ch/ClickHouse/base/glibc-compatibility/memcpy -isystem /mnt/ch/ClickHouse/contrib/libcxx/include -isystem /mnt/ch/ClickHouse/contrib/libcxxabi/include -isystem /mnt/ch/ClickHouse/contrib/libunwind/include --gcc-toolchain=/mnt/ch/ClickHouse/cmake/linux/../../contrib/sysroot/linux-x86_64  -g -fno-omit-frame-pointer -DSANITIZER -fsanitize=memory -fsanitize-memory-use-after-dtor -fsanitize-memory-track-origins -fno-optimize-sibling-calls -fsanitize-blacklist=/mnt/ch/ClickHouse/tests/msan_suppressions.txt -fdiagnostics-color=always -Xclang -fuse-ctor-homing  -gdwarf-aranges -pipe -mssse3 -msse4.1 -msse4.2 -mpclmul -mpopcnt -fasynchronous-unwind-tables -ffile-prefix-map=/mnt/ch/ClickHouse=. -falign-functions=32 -mbranches-within-32B-boundaries  -fdiagnostics-absolute-paths -fexperimental-new-pass-manager -fomit-frame-pointer -O2 -g -DNDEBUG -O3 -g -gdwarf-4    -D OS_LINUX -Wno-unused-command-line-argument -Wno-unused-but-set-variable -Wno-builtin-requires-header -Werror -std=gnu11 -MD -MT base/glibc-compatibility/CMakeFiles/glibc-compatibility.dir/musl/getauxval.c.o -MF base/glibc-compatibility/CMakeFiles/glibc-compatibility.dir/musl/getauxval.c.o.d -o base/glibc-compatibility/CMakeFiles/glibc-compatibility.dir/musl/getauxval.c.o -c /mnt/ch/ClickHouse/base/glibc-compatibility/musl/getauxval.c
FAILED: base/glibc-compatibility/CMakeFiles/glibc-compatibility.dir/musl/getauxval.c.o 
/usr/bin/ccache /usr/lib/ccache/bin/clang --target=x86_64-linux-gnu --sysroot=/mnt/ch/ClickHouse/cmake/linux/../../contrib/sysroot/linux-x86_64/x86_64-linux-gnu/libc -DHAS_RESERVED_IDENTIFIER -DSTD_EXCEPTION_HAS_STACK_TRACE=1 -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS -I/mnt/ch/ClickHouse/base/glibc-compatibility/libcxxabi -I/mnt/ch/ClickHouse/base/glibc-compatibility/musl/x86_64 -I/mnt/ch/ClickHouse/base/glibc-compatibility/memcpy -isystem /mnt/ch/ClickHouse/contrib/libcxx/include -isystem /mnt/ch/ClickHouse/contrib/libcxxabi/include -isystem /mnt/ch/ClickHouse/contrib/libunwind/include --gcc-toolchain=/mnt/ch/ClickHouse/cmake/linux/../../contrib/sysroot/linux-x86_64  -g -fno-omit-frame-pointer -DSANITIZER -fsanitize=memory -fsanitize-memory-use-after-dtor -fsanitize-memory-track-origins -fno-optimize-sibling-calls -fsanitize-blacklist=/mnt/ch/ClickHouse/tests/msan_suppressions.txt -fdiagnostics-color=always -Xclang -fuse-ctor-homing  -gdwarf-aranges -pipe -mssse3 -msse4.1 -msse4.2 -mpclmul -mpopcnt -fasynchronous-unwind-tables -ffile-prefix-map=/mnt/ch/ClickHouse=. -falign-functions=32 -mbranches-within-32B-boundaries  -fdiagnostics-absolute-paths -fexperimental-new-pass-manager -fomit-frame-pointer -O2 -g -DNDEBUG -O3 -g -gdwarf-4    -D OS_LINUX -Wno-unused-command-line-argument -Wno-unused-but-set-variable -Wno-builtin-requires-header -Werror -std=gnu11 -MD -MT base/glibc-compatibility/CMakeFiles/glibc-compatibility.dir/musl/getauxval.c.o -MF base/glibc-compatibility/CMakeFiles/glibc-compatibility.dir/musl/getauxval.c.o.d -o base/glibc-compatibility/CMakeFiles/glibc-compatibility.dir/musl/getauxval.c.o -c /mnt/ch/ClickHouse/base/glibc-compatibility/musl/getauxval.c
/mnt/ch/ClickHouse/base/glibc-compatibility/musl/getauxval.c:105:9: error: implicit declaration of function '__msan_unpoison' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        __msan_unpoison(&aux, sizeof(aux));
        ^
1 error generated.
ninja: build stopped: subcommand failed.
```

### CODE REVIEW

**Comment by azat** [comment]
Looks like it will be easy to forget it in newer files, maybe something like this will better?

```cmake
# Override try_compile() to always pass -Wno-error, to avoid breaking some checks.
macro(try_compile)
    _try_compile(${ARGV} CMAKE_FLAGS "-DCOMPILE_DEFINITIONS:STRING=-Wno-error")
endmacro()
```

The only problem with overriding builtins is that it is undocumented feature, and there are [some issues with it](https://gitlab.kitware.com/cmake/cmake/-/issues/23482).

**Comment by Algunenano** [comment]
Uhmm, now that I look into it the problem is that `link_libraries(global-group)` is declared after including `(cmake/XXXXX/default_libs.cmake)` so those libs don't get the flags, as it only works for those included after.

I'll try switching `link_libraries` around to see if that builds fine.

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
Can we also address this? https://github.com/ClickHouse/ClickHouse/issues/12447

**Comment by Algunenano** [comment]
> Can we also address this? https://github.com/ClickHouse/ClickHouse/issues/12447

I've tried and now if you manually enable openssl by removing the if:
```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 47e9413258..e14db923fb 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -497,11 +497,11 @@ enable_testing() # Enable for tests without binary
 
 option(ENABLE_EXTERNAL_OPENSSL "This option is insecure and not recommended for any occasions. If it is enabled, it allows building with alternative OpenSSL library. By default, ClickHouse is using BoringSSL, which is better. Do not use this option." OFF)
 
-if (ENABLE_EXTERNAL_OPENSSL)
+#if (ENABLE_EXTERNAL_OPENSSL)
     message (STATUS "Build and uses OpenSSL library instead of BoringSSL. This is strongly discouraged. Your build of ClickHouse will be unsupported.")
     set(ENABLE_SSL 1)
     target_compile_options(global-group INTERFACE "-Wno-deprecated-declarations")
-endif ()
+#endif ()
 
 # when installing to /usr - place configs to /etc but for /usr/local place to /usr/local/etc
 if (CMAKE_INSTALL_PREFIX STREQUAL "/usr")
```

Now you get a fatal error:
```
CMake Error at CMakeLists.txt:632 (message):
  Found global flags disabling warnings (-Wno) in:
  -Werror;-Wno-deprecated-declarations


-- Configuring incomplete, errors occurred!
See also "/mnt/ch/ClickHouse/build_test_wno/CMakeFiles/CMakeOutput.log".
See also "/mnt/ch/ClickHouse/build_test_wno/CMakeFiles/CMakeError.log"
```

I'm not sure if this is exactly what you want but this is what I could do with cmake. If it isn't then I can remove the commit and we can leave the ticket for the future.

**Comment by alexey-milovidov** [comment]
Looks like what we need, although I'm not completely sure.
The most frequent error was when someone defined the `-w` flag for an external library with PUBLIC instead of PRIVATE.
Does it cover this scenario?

Don't worry about OpenSSL, as we don't support it.

**Comment by Algunenano** [comment]
The error in the build seems valid:
```
Nov 10 13:27:24 CMake Error: The inter-target dependency graph contains the following strongly connected component (cycle):
Nov 10 13:27:24   "unwind" of type SHARED_LIBRARY
Nov 10 13:27:24     depends on "cxx" (weak)
Nov 10 13:27:24     depends on "cxxabi" (weak)
Nov 10 13:27:24   "cxxabi" of type SHARED_LIBRARY
Nov 10 13:27:24     depends on "cxx" (weak)
Nov 10 13:27:24     depends on "unwind" (weak)
Nov 10 13:27:24   "cxx" of type SHARED_LIBRARY
Nov 10 13:27:24     depends on "cxxabi" (weak)
Nov 10 13:27:24     depends on "unwind" (weak)
Nov 10 13:27:24 At least one of these targets is not a STATIC_LIBRARY.  Cyclic dependencies are allowed only among static libraries.
Nov 10 13:27:24 CMake Generate step failed.  Build files cannot be regenerated correctly.
Nov 10 13:27:24 -- Cache values
```

I'll have a look

**Comment by alexey-milovidov** [comment]
Ok. Grep of `compile_commands.json` in CI will work.

**Comment by azat** [comment]
>Ok. Grep of compile_commands.json in CI will work.

Seems that this can be done with cmake - #43275

**Pull request merged**
