### PR TITLE
May be fix s3 tests

### PR DESCRIPTION
**Pull request by kssenii**
Changelog category (leave one):
- Not for changelog (changelog entry is not required)

s3 tests with latest master pass locally, but also docker minio image was updated 2 days ago -- exactly when s3 tests started failing so may be this will fix it.
Error it failed with:
`AWSErrorMarshaller: Encountered AWSError 'InternalError': We encountered an internal error, please try again`

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
Please add a comment.

**Comment by kssenii** [comment]
Flacky test in fast test
```
2021-10-05 11:55:21 01293_show_clusters:                                                    [ FAIL ] - result differs with reference: 
2021-10-05 11:55:21 --- /ClickHouse/tests/queries/0_stateless/01293_show_clusters.reference	2021-10-05 11:48:11.528451962 +0300
2021-10-05 11:55:21 +++ /ClickHouse/tests/queries/0_stateless/01293_show_clusters.stdout	2021-10-05 11:55:21.602094392 +0300
2021-10-05 11:55:21 @@ -1,2 +1,2 @@
2021-10-05 11:55:21  test_shard_localhost
2021-10-05 11:55:21 -test_shard_localhost	1	1	1	localhost	::1	9000	1	default		0	0	0
2021-10-05 11:55:21 +test_shard_localhost	1	1	1	localhost	::1	9000	1	default		0	1	41
```

**Comment by kssenii** [comment]
@Mergifyio update

**Comment by kssenii** [comment]
some s3 tests failed for different reason
```
subprocess.TimeoutExpired: Command '['docker-compose', '--env-file', 
'/ClickHouse/tests/integration/test_s3_with_https/_instances_0/.env', '--project-name', 'roottests3withhttps', '--file', 
'/compose/docker_compose_minio.yml', 'up', '-d']' timed out after 300 seconds
```

But the same happened to rabbitmq
```
 subprocess.TimeoutExpired: Command '['docker-compose', '--env-file', '/ClickHouse/tests/integration/test_storage_rabbitmq/_instances_0/.env', '--project-name', 'rootteststoragerabbitmq', '--file', 
'/ClickHouse/tests/integration/test_storage_rabbitmq/_instances_0/instance/docker-compose.yml', '--file', 
'/compose/docker_compose_rabbitmq.yml', 'up', '-d', '--no-recreate']' timed out after 300 seconds
```

and mysql 
```
subprocess.TimeoutExpired: Command '['docker-compose', '--env-file', '/ClickHouse/tests/integration/test_storage_mysql/_instances_0/.env', '--project-name', 'rootteststoragemysql', '--file', '/ClickHouse/tests/integration/test_storage_mysql/_instances_0/node1/docker-compose.yml', '--file', '/compose/docker_compose_mysql.yml', '--file', '/ClickHouse/tests/integration/test_storage_mysql/_instances_0/node2/docker-compose.yml', '--file', '/compose/docker_compose_mysql_cluster.yml', '--file', 
'/ClickHouse/tests/integration/test_storage_mysql/_instances_0/node3/docker-compose.yml', 'up', '-d', '--no-recreate']'
 timed out after 300 seconds
```

and postgresql 
```
subprocess.TimeoutExpired: Command '['docker-compose', '--env-file', '/ClickHouse/tests/integration/test_storage_postgresql/_instances_0/.env', '--project-name', 'rootteststoragepostgresql', '--file', '/ClickHouse/tests/integration/test_storage_postgresql/_instances_0/node1/docker-compose.yml', '--file', '/compose/docker_compose_postgres.yml', '--file', 
'/ClickHouse/tests/integration/test_storage_postgresql/_instances_0/node2/docker-compose.yml', '--file', 
'/compose/docker_compose_postgres_cluster.yml', 'up', '-d', '--no-recreate']'
 timed out after 300 seconds
```
so it is a common issue happened yesterday..

btw I triggered flacky check for s3 tests and now thay successed though previously some of them were constantly failing in master `Integration tests flaky check (asan) — No flaky tests: fail: 0, error: 0, passed: 13` so may be makes sence to merge this pr now.

**Comment by kssenii** [comment]
@Mergifyio update

**Pull request merged**
