### PR TITLE
Enable profiling for linker

### PR DESCRIPTION
**Pull request by alexey-milovidov**
### Changelog category (leave one):
- Build/Testing/Packaging Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Tracing data of the linker invocations will be sent to the CI database in ClickHouse Cloud.

### CODE REVIEW

**Comment by robot-clickhouse-ci-2** [comment]
*This is an automated comment for commit 5d81080e3108510ba0cd20883bc83fa9ed2ca7e5 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/56725/5d81080e3108510ba0cd20883bc83fa9ed2ca7e5/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td><a href="https://github.com/ClickHouse/ClickHouse/actions/runs/6860758604">✅ success</a></td></tr>
<tbody>
</table>
</details>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/56725/5d81080e3108510ba0cd20883bc83fa9ed2ca7e5/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Review by nikitamikhaylov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
It does not work.

I tried to try different ways to use it, but nothing works: https://pastila.nl/?00039fdd/c1c679b3a8ffa99f35d17b55a613a70b#rA1sOHmiV2C3H6w7pct/wA==

**Comment by alexey-milovidov** [comment]
I found the reason - the linker names these files differently:

```
milovidov@milovidov-desktop:~/work/tmp$ clang++ -ftime-trace -fuse-ld=lld --ld-path=/usr/local/bin/ld.lld -Wl,--time-trace test.cpp
milovidov@milovidov-desktop:~/work/tmp$ ls -l
total 24
-rwxrwxr-x 1 milovidov milovidov 5848 nov 15 07:39 a.out
-rw-rw-r-- 1 milovidov milovidov 4537 nov 15 07:39 a.out.time-trace
-rw-rw-r-- 1 milovidov milovidov 2886 nov 15 07:39 a-test.json
-rw-r--r-- 1 milovidov milovidov   25 nov 15 07:37 test.cpp
```

What a shame for LLVM compiler infrastructure :(

**Comment by alexey-milovidov** [comment]
Ok: https://pastila.nl/?0004d133/7e753eaa65f4d8924147f57874b79143#9XwNVfBhwc9ZBBuN7uvkMA==

**Comment by Alex-Cheng** [comment]
How can I use it in my local development environment? I am suffering from slow linking time for RelWithDebInfo build and want to find the root cause.

**Comment by alexey-milovidov** [comment]
@Alex-Cheng 

with
```
cmake -D ENABLE_BUILD_PROFILING=1
```

**Pull request merged**
