### PR TITLE
Cherrypick Context lock contention fix into 23.8

### PR DESCRIPTION
**Pull request by kitaisreal**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by kitaisreal** [comment]
Related to https://github.com/ClickHouse/ClickHouse/pull/55236.

**Comment by kssenii** [comment]
Isn't it a too big change to be backported? It is not a bug fix, but we backport only bug fixes. Also CI already found a race because of these changes https://s3.amazonaws.com/clickhouse-test-reports/55252/c57a92f5fcdf2b131ebbcc6758260399e8ca976d/stress_test__tsan_/stderr.log

**Comment by kitaisreal** [comment]
> Isn't it a too big change to be backported? It is not a bug fix, but we backport only bug fixes. Also CI already found a race because of these changes https://s3.amazonaws.com/clickhouse-test-reports/55252/c57a92f5fcdf2b131ebbcc6758260399e8ca976d/stress_test__tsan_/stderr.log

Currently Context internals are suboptimal and must be refactored.
Pull request fixes issue with ClickHouse scalability. Without this fix in 23.8 it is impossible to vertically scale ClickHouse instance to fully utilize available resources. For example even for 1000 concurrent queries per second there is noticeable degradation and almost 2 times slowdown.
I will fix race.

**Comment by kitaisreal** [comment]
We also need to back port https://github.com/ClickHouse/ClickHouse/pull/55260 with this changes. I will double check all other suspicious places where we used `callOnce` initialization.

**Comment by alexey-milovidov** [comment]
It looks dangerous to backport.

**Comment by alexey-milovidov** [comment]
If a customer needs this change, they should install a new version.

**Pull request closed without merging**
