### PR TITLE
(docs) Remove async_metric_log event_time_microseconds

### PR DESCRIPTION
**Pull request by RoryCrispin**
event_time_microseconds was removed from the
system.asynchronous_metric_log in
https://github.com/ClickHouse/ClickHouse/pull/36360

### Changelog category (leave one):
- Documentation (changelog entry is not required)

### CODE REVIEW

**Comment by robot-clickhouse-ci-1** [comment]
This is an automated comment for commit c9a26d43c5b053c3e5a0898e382c0405a4ecf4a6 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/51778/c9a26d43c5b053c3e5a0898e382c0405a4ecf4a6/ci_running.html)
The overall status of the commit is 🔴 failure

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🔴 failure</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Review by alexey-milovidov — APPROVED** [review]

**Comment by RoryCrispin** [comment]
@alexey-milovidov I don't have write access so will hand this over for you to merge

**Comment by DanRoscigno** [comment]
@Felixoid FYI: This one did not auto-merge for some reason.

**Comment by Felixoid** [comment]
It doesn't automerge in case of changes after the approval. It's by design

**Pull request merged**
