### PR TITLE
Additional check in MergeTreeReadPool

### PR DESCRIPTION
**Pull request by kssenii**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by kssenii** [comment]
Hm, judging by the failed fast test after I added an assertion, looks like we pass intersecting ranges to MergeTreeReadPool and as a result we will read some data more than once :/
```
DB::Exception: Received from localhost:9000. DB::Exception: Intersecting mark ranges are not allowed, it is a bug! First range (60, 61), second range (60, 61)
```

**Comment by nikitamikhaylov** [comment]
Can we put this check under `#ifndef NDEBUG` and merge once the bug will be fixed?

**Comment by nikitamikhaylov** [comment]
@kssenii Probably we just compare an element to itself? We can add this check to the `operator <`

**Comment by kssenii** [comment]
> @kssenii Probably we just compare an element to itself? We can add this check to the operator <

you are right, thank you

**Comment by nikitamikhaylov** [comment]
All failed integration tests failures are known.

**Review by nikitamikhaylov — APPROVED** [review]

**Pull request merged**
