### PR TITLE
tzdata tiny fixes

### PR DESCRIPTION
**Pull request by filimonov**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Build/Testing/Packaging Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Expose version of embedded tzdata via TZDATA_VERSION in system.build_options,

Detailed description / Documentation draft:
Also update tzdata before clickhouse build to avoid packaging with obsolete tzdata (just in case). (better #13623)
Related: #10425

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]

**Comment by filimonov** [comment]
That is wrong. The tzdata files are picked from cctz distribution, not from system.

**Comment by filimonov** [comment]
https://github.com/ClickHouse/ClickHouse/blob/c7a6a18a758f8491f4773a990ae60a1ae0f53b73/contrib/cctz-cmake/CMakeLists.txt#L595

**Comment by filimonov** [comment]
BTW list of timezone packaged is not full...

**Comment by bharatnc** [comment]
> BTW list of timezone packaged is not full...

@filimonov I'm curious about:

1. the whereabouts of the list of timezones and where it's located.
2. and how the list is being packaged into the Clickhouse binary.

Would you be able to point me towards 1 & 2?

**Comment by filimonov** [comment]
@bharatnc please check follow up PR https://github.com/ClickHouse/ClickHouse/pull/13648

Timezones are taken from tzdb included (see contrib/cct/testdata) and added to clickhouse binary using objcopy

**Comment by bharatnc** [comment]
> @bharatnc please check follow up PR #13648
> 
> Timezones are taken from tzdb (see contrib/cct/testdata) and added to clickhouse binary using objcopy

:+1: thanks, clearer to me now!

**Pull request closed without merging**
