### PR TITLE
Mysqlxx mutualize connection of external MySQL dictionaries

### PR DESCRIPTION
**Pull request by clemrodriguez**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

For changelog. Remove if this is non-significant change.

Category:
- Improvement

Short description:
For external MySQL dictionaries, mutualize MySQL connection pool to "share" them among dictionaries.
The aim is to reduce total number of MySQL connections.
It is related to issue #893 and goes forward pull request #5395 (and clone of #5438 PR)

...

Detailed description:
In our context we use many External MySQL dictionaries, they are not frequently updated. As each connection consumes resources on the MySQL server side, we would like to reduce the total number of opened ones. So we would like to mutualize them, the pool will re-use MySQL closed connections to feed connection consumers (External Dictionaries).

To do so:
- we added a bool parameter share_connection in external dictionary definition dictionary.xml (at same level as db or table), if its value is true it forces connection closure after usage.
- modified MySQLDictionarySource to consider the dictionary parameter (share_connection) with default value = false (previous behavior) and force close connection if set to true. It prevents connection famine pattern.
- create a class called PoolFactory in libmysqlxx. It is a singleton storing PoolWithFailOver associated to a dictionary configuration. If a dictionary is declared having a shareable connection, then this class will generate a "connection name" based on "user@host:port/db".
- if an external dictionary request similar shareable connection they will share the pool
- modified ExternalDictionariesLoader class to reset PoolFactory map when receiving SYSTEM RELOAD DICTIONARY | DICTIONARIES

### CODE REVIEW

**Comment by clemrodriguez** [comment]
Hi,
This PR has a bug, that I need to fix. Could you, please wait before reviewing it.
Regards.

**Comment by clemrodriguez** [comment]
Hi,
This PR can be tested. Previous mentioned bug was fixed (see last commits).
Regards

**Comment by clemrodriguez** [comment]
Hi,
Once again (see #5438), I polluted the history logs for this PR due to a rebase : code was conflicting as master had several new commits and refactoring.
As it is pending since a while, would you prefer that I close it and reopen a new one ?
Regards.

**Comment by alexey-milovidov** [comment]
@clemrodriguez Sorry for the delay. Yes, it's better to open a new PR.

**Pull request closed without merging**
