### PR TITLE
Make the Replxx client history size configurable

### LINKED ISSUE #62102: History in clickhouse-client is limited to 1000 entries.
It is sad, and I didn't expect that.
Make it at least 1,000,000 entries or unlimited.

### PR DESCRIPTION
**Pull request by jirislav**
Resolves https://github.com/ClickHouse/ClickHouse/issues/62102

### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Make the Replxx client history size configurable

### Documentation entry for user-facing changes

- [x] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Run only fuzzers related jobs (libFuzzer fuzzers, AST fuzzers, etc.)
- [ ]  Exclude: AST fuzzers
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-clickhouse-ci-1** [comment]
*This is an automated comment for commit bb1d77ab3f8109f1682bab7596df5d2523e8b3f5 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/71014/bb1d77ab3f8109f1682bab7596df5d2523e8b3f5/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Style check</td><td>Runs a set of checks to keep the code style clean. If some of tests failed, see the related log from the report</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/71014/bb1d77ab3f8109f1682bab7596df5d2523e8b3f5/style_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Review by alexey-milovidov — APPROVED** [review]
Thanks! This is what we need.
But `int` sounds suspicious. Let's change to `UInt32`.
If replxx accepts `int`, do static_cast.

**Review by alexey-milovidov — CHANGES_REQUESTED** [review]
.

**Comment by jirislav** [comment]
> But int sounds suspicious. Let's change to UInt32.

Point taken, PTAL.

**Review by vdimir — APPROVED** [review]
Awesome work on this PR! Thanks for your contribution.
I only added a test for the new flag, if you don't mind

**Comment by jirislav** [comment]
> I only added a test for the new flag, if you don't mind

Not at all, thanks!

**Review by alexey-milovidov — APPROVED** [review]

**Comment by vdimir** [comment]
Seems my test is a bit flaky, I'll debug it and add in a separate PR

**Pull request merged**
