### PR TITLE
Initialize text_log earlier to capture table startup messages

### PR DESCRIPTION
**Pull request by azat**
While I was investigating some issues, I noticed that messages from table startup are not appears in system.text_log due to too late initialization.

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Initialize text_log earlier to capture table startup messages

### CODE REVIEW

**Comment by robot-ch-test-poll** [comment]
This is an automated comment for commit 5d43a64112711b339b82b1c0e8df7882546a1a3c with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/51360/5d43a64112711b339b82b1c0e8df7882546a1a3c/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Comment by nikitamikhaylov** [comment]
This rabbit hole might be deep...

**Comment by alexey-milovidov** [comment]
Does it solve #50843?

**Review by alexey-milovidov — APPROVED** [review]

**Comment by azat** [comment]
> Does it solve https://github.com/ClickHouse/ClickHouse/issues/50843?

No, it only allows to capture logs after system.text_log started, and since it starts before user tables, it will allow to collect only logs from those tables initialization and after.

**Comment by azat** [comment]
>Performance Comparison [4/4] — Errors while building the report.

- #51362

**Review by alexey-milovidov — APPROVED** [review]

**Comment by kardymonds** [comment]
If anyone has time, please take a look at the draft pull request https://github.com/ClickHouse/ClickHouse/pull/52113 to to write message to  text_log from the beginning. There is not finished (oop for SystemLogQueue, but this is working)

**Pull request merged**
