### PR TITLE
Try to improve the performance of ColumnNullable type

### PR DESCRIPTION
**Pull request by zhanglistar**
### Changelog category (leave one):
- Performance Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Try to improve the performance of Nullable type by adding a flag has_null to do short circuit on `ColumnNullable::isNullAt` which is hot function.
> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Review by yakov-olkhovskiy — COMMENTED** [review]
Overall this improvement maybe sensible with possible SSE optimization if we often want to evaluate if column has nulls - it's not a big improvement for the isNullAt I think, besides I'm not sure we want to pay for it with instantiation speed... maybe lazy evaluation can be better option...
@KochetovNicolai what do you think?

**Comment by zhanglistar** [comment]
> 

@yakov-olkhovskiy Thanks for your review. There is another optimization to use bitmap instead of array of uint8 for better space and cache locality.

**Comment by KochetovNicolai** [comment]
Unfortunately this PR does not cover all the cases where null map can be changed.
Example:
https://github.com/ClickHouse/ClickHouse/blob/62debf42b4d23bc9bd58047e454ac5bd46dc7afe/src/Processors/Sources/MySQLSource.cpp#L319

The general issue is that ColumnNullable does not protect it's null mask. External code can call `getNullMapColumn` or `getNullMapData` and change it.
We ca't have such kind of optimizations till such methods are removed (which could be hard).

**Comment by zhanglistar** [comment]
@KochetovNicolai Yes, you are right, I realized this problems. And I try to work on this.

**Comment by zhanglistar** [comment]
That's really lots of work to do, I think it's too low ROI, so I give up on this PR.

**Pull request closed without merging**
