### PR TITLE
Replace "-" in keys for the prometheus exporter

### LINKED ISSUE #27799: AsyncMetrics are not in Prometheus format
**Describe the issue**
We've updated from 21.3.4.25 to 21.8.3.44 and Prometheus metrics are broken now.

According to [official Prometheus documentation](https://prometheus.io/docs/concepts/data_model/#metric-names-and-labels),
> The metric name specifies the general feature of a system that is measured (e.g. http_requests_total - the total number of HTTP requests received). It may contain ASCII letters and digits, as well as underscores and colons. It must match the regex [a-zA-Z_:][a-zA-Z0-9_:]*.

Here is the list of bad names:

```
# TYPE ClickHouseAsyncMetrics_BlockInFlightOps_dm-1 gauge
# TYPE ClickHouseAsyncMetrics_BlockDiscardTime_dm-1 gauge
# TYPE ClickHouseAsyncMetrics_BlockReadTime_dm-1 gauge
# TYPE ClickHouseAsyncMetrics_BlockDiscardMerges_dm-1 gauge
# TYPE ClickHouseAsyncMetrics_BlockReadMerges_dm-1 gauge
# TYPE ClickHouseAsyncMetrics_BlockDiscardOps_dm-1 gauge
# TYPE ClickHouseAsyncMetrics_BlockWriteOps_dm-1 gauge
# TYPE ClickHouseAsyncMetrics_BlockReadOps_dm-1 gauge
# TYPE ClickHouseAsyncMetrics_BlockReadBytes_dm-1 gauge
# TYPE ClickHouseAsyncMetrics_BlockWriteBytes_dm-1 gauge
# TYPE ClickHouseAsyncMetrics_BlockQueueTime_dm-1 gauge
# TYPE ClickHouseAsyncMetrics_BlockWriteTime_dm-1 gauge
# TYPE ClickHouseAsyncMetrics_BlockActiveTime_dm-1 gauge
# TYPE ClickHouseAsyncMetrics_BlockWriteMerges_dm-1 gauge
# TYPE ClickHouseAsyncMetrics_BlockDiscardBytes_dm-1 gauge
```

### PR DESCRIPTION
**Pull request by azat**
Changelog category (leave one):
- Bug Fix (user-visible misbehaviour in official stable or prestable release)

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Replace "-" in keys for the prometheus exporter

Fixes: #27799

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
Integration test has failed.

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
The code LGTM.

**Review by alexey-milovidov — CHANGES_REQUESTED** [review]
Need to update the test.

**Comment by azat** [comment]
Actually the patch is wrong, and the issue had been already fixed in #26140

**Pull request closed without merging**
