### PR TITLE
Enable using constants from with and select in aggregate function parameters.

### LINKED ISSUE #10945: groupArray(max_size)(col) with max_size defined in WITH clause
**Describe the unexpected behaviour**
When using groupArray function with max_size parameter defined as constant in WITH clause got error message:
`Code: 47, e.displayText() = DB::Exception: Missing columns: 'max_size' while processing query: 'WITH 1 AS max_size SELECT groupArray(max_size)(col) FROM (SELECT 1 AS col UNION ALL SELECT 2)', required columns: 'col' 'max_size', source columns: 'col' (version 20.3.8.53 (official build))`

**How to reproduce**
ClickHouse server version 20.3.8.53
```
with 1 as max_size
select groupArray(max_size)(col) from (
select 1 as col
UNION ALL
select 2
)
```

**Expected behavior**
It would be nice to have this function accept max_size parameter as defined in WITH clause.

### PR DESCRIPTION
**Pull request by abel-cheng**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- New Feature

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Enable using constants from with and select in aggregate function parameters. Close  [#10945](https://github.com/ClickHouse/ClickHouse/issues/10945)

Detailed description / Documentation draft:
Enable using constants from with and select in aggregate function parameters.
detail is in [#10945](https://github.com/ClickHouse/ClickHouse/issues/10945)

### CODE REVIEW

**Comment by kitaisreal** [comment]
@abel-cheng please add tests.

**Comment by akuzm** [comment]
I will temporarely close this PR because it somehow references a non-existent commit that breaks our CI. Will investigate and reopen tomorrow. In the meantime please feel free to continue working on it.

**Comment by akuzm** [comment]
@mergifyio update

**Comment by alexey-milovidov** [comment]
Looks like it's a bug of GitHub. I can see this commits here:

https://github.com/abel-cheng/ClickHouse/commit/476b066668d3d19bdbc8f70ab7abae4a139387f5
https://github.com/abel-cheng/ClickHouse/commit/ec0ee2cecf87e3dd72aca9992d304b65e8d6d9db

**Comment by alexey-milovidov** [comment]
This is definitely a bug in GitHub database.

The commits were unavailable.
I created another pull request with the same commits: https://github.com/ClickHouse/ClickHouse/pull/27541
Then the commits became available in this PR as well.

Also there were many issues with GitHub API today (it returned HTTP 500).
Unfortunately, GitHub is very unreliable (there is around one episode of downtime every month).

**Comment by alexey-milovidov** [comment]
https://www.githubstatus.com/history

> Incident with GitHub Actions, API Requests, Git Operations, Issues, Microsoft Teams Integration, GitHub Packages, GitHub Pages, Pull Requests, Slack Integration, and Webhooks
This incident has been resolved.
Aug 10, 15:16 - 16:57 UTC

**Review by kitaisreal — APPROVED** [review]

**Review by kitaisreal — APPROVED** [review]

**Pull request merged**
