### PR TITLE
Do only merging of sorted blocks on initiator with distributed_group_by_no_merge=2

### PR DESCRIPTION
**Pull request by azat**
Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Do only merging of sorted blocks on initiator with distributed_group_by_no_merge

Detailed description / Documentation draft:
When `distributed_group_by_no_merge=2` is used (or when
`optimize_distributed_group_by_sharding_key` takes place), remote servers
will do full `ORDER BY`, so initiator can skip this step and do only merge
of ordered blocks.

### CODE REVIEW

**Comment by azat** [comment]
>AST fuzzer (debug) — Logical error: 'Trying to get name of not a column: SelectWithUnionQuery'.

#20342

>Marker check Pending — Starting checks (No special conditions apply)

Hanged

>Integration tests (release) — fail: 1, passed: 1123, error: 0

```
test_materialize_mysql_database/test.py::test_select_without_columns_8_0[clickhouse_node1]
```

Not related

**Comment by alexey-milovidov** [comment]
@zhang2014 @BohuTANG Could you please take a look at the failure of MaterializeMySQL test?

**Review by alexey-milovidov — APPROVED** [review]

**Comment by azat** [comment]
>@zhang2014 @BohuTANG Could you please take a look at the failure of MaterializeMySQL test?

In the meantime let's preserve mysql logs - #21016

**Comment by zhang2014** [comment]
> @zhang2014 @BohuTANG Could you please take a look at the failure of MaterializeMySQL test?
>> In the meantime let's preserve mysql logs - #21016

It looks like `SYSTEM STOP MERGE` was not implemented. I'm trying to fix it.

**Comment by alexey-milovidov** [comment]
@azat The test is flaky: https://clickhouse-test-reports.s3.yandex.net/22561/36b03b27401afcf0b0ee704c827a1f89d377e50e/functional_stateless_tests_(memory).html#fail1

**Comment by azat** [comment]
>@azat The test is flaky: https://clickhouse-test-reports.s3.yandex.net/22561/36b03b27401afcf0b0ee704c827a1f89d377e50e/functional_stateless_tests_(memory).html#fail1

@alexey-milovidov Not really, the problem is in settings for default user, anyway had been already fixed in 278ad443e4aeae800e960d83c811c3d7568efbc3 (by @vitlibar )

**Pull request merged**
