### PR TITLE
Ecloud EOS Storage support

### PR DESCRIPTION
**Pull request by xleoken**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Improve S3 compatible, add Ecloud EOS storage support.

### Description

https://ecloud.10086.cn/portal/product/eos

Refer:
Huawei: https://github.com/ClickHouse/ClickHouse/pull/29511
Aliyun: https://github.com/ClickHouse/ClickHouse/pull/31286

Throw exception when query from eos
```
SELECT count()
FROM s3('https://xxxxx.eos.jinan-4.cmecloud.cn/data/trips_*.csv.lz4', 'xxxxx', 'xxxx', 'CSV')

Query id: c3f0fa30-3981-45f5-a72d-742a88ceac7c


Elapsed: 0.037 sec. 

Received exception:
Code: 499. DB::Exception: Could3 not list objects in bucket 'data' with prefix 'trips_', S3 exception: `NoSuchKey`, message: ''. (S3_ERROR)
```

After patch
```
SELECT count()
FROM s3('https://xxxxx.eos.jinan-4.cmecloud.cn/trips_*.csv.lz4', 'xxxxx', 'xxxxx', 'CSV')

Query id: d42bfbbd-a021-4a72-9628-f6782ba1d3cc

┌─count()─┐
│       1 │
└─────────┘

1 row in set. Elapsed: 0.031 sec. 

```

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Review by kssenii — APPROVED** [review]

**Comment by robot-clickhouse** [comment]
*This is an automated comment for commit e7efe966ee8aa3aed2736b09b538b2cfd0ec9294 with description of existing statuses. It's updated for the latest CI running*

[❌ Click here](https://s3.amazonaws.com/clickhouse-test-reports/58786/e7efe966ee8aa3aed2736b09b538b2cfd0ec9294/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td><a href="https://github.com/ClickHouse/ClickHouse/blob/master/.github/PULL_REQUEST_TEMPLATE.md?plain=1">❌ failure</a></td></tr>
<tbody>
</table>

**Comment by xleoken** [comment]
Thanks @kssenii

**Comment by xleoken** [comment]
I create a public read test dataset in eos storage.
```
trips_0.csv.lz4
trips_1.csv.lz4
trips_2.csv.lz4

SELECT count()
FROM s3('https://bigdata.eos.jinan-4.cmecloud.cn/test/trips_*.csv.lz4', 'CSV')

Query id: cf0c474a-0f71-4168-8b96-5fc69ab2ee59

┌─count()─┐
│    1000 │
└─────────┘

1 row in set. Elapsed: 3.058 sec. Processed 1.00 thousand rows, 33.00 B (327.01 rows/s., 10.79 B/s.)
Peak memory usage: 114.87 KiB.
```

hi @kssenii take a look when free, thanks, cc @alexey-milovidov

**Comment by Algunenano** [comment]
@xleoken Please fix the PR description / initial message to follow the template. Otherwise the code won't be tested and can't be merged

**Comment by xleoken** [comment]
Thank you for your reminding. @Algunenano

**Comment by kssenii** [comment]
> Integration tests (tsan) [6/6] — fail: 1

test_storage_kafka/test.py::test_system_kafka_consumers_rebalance_mv

**Pull request merged**
