### PR TITLE
Support bitmap64 feature

### PR DESCRIPTION
**Pull request by andyyzh**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- New Feature

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Add bitmap64 feature

Detailed description / Documentation draft:
If Uint64 is specified in the table creation statement, roaringbitmap64 is used
For example:
AggregateFunction( groupBitmap, **UInt64** )

If uint32 is specified, roaringbitmap32 is used
For example:
AggregateFunction( groupBitmap, **UInt32** )

Compatible with previous bitmap functions.

Fix this issue:  #7962

### CODE REVIEW

**Comment by andyyzh** [comment]
@amosbird  Take time to have a look, on version 20.8 is work.

**Comment by amosbird** [comment]
depends on https://github.com/RoaringBitmap/CRoaring/pull/277

**Comment by andyyzh** [comment]
@amosbird  Great work, thank you!

**Comment by nikitamikhaylov** [comment]
Merged in #18475

**Pull request closed without merging**
