### PR TITLE
Fix alter key when materialized column passed

### PR DESCRIPTION
**Pull request by alesapin**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Add ability to set `MATERIALIZED` default type for primary key columns and columns with secondary indices.

### CODE REVIEW

**Comment by KochetovNicolai** [comment]
Test for secondary index is needed too.

**Comment by alesapin** [comment]
> Test for secondary index is needed too.

It's just here https://github.com/ClickHouse/ClickHouse/pull/11786/files#diff-1b07ab8c26f5b3c84e792c167eb85d84R78

**Comment by KochetovNicolai** [comment]
Funny thing, but we can't unmaterialize column back:
```
:) desc ttt

DESCRIBE TABLE ttt

┌─name─┬─type───┬─default_type─┬─default_expression─┬─comment─┬─codec_expression─┬─ttl_expression─┐
│ x    │ UInt32 │ MATERIALIZED │ 3                  │         │                  │                │
│ y    │ UInt32 │              │                    │         │                  │                │
└──────┴────────┴──────────────┴────────────────────┴─────────┴──────────────────┴────────────────┘

2 rows in set. Elapsed: 0.002 sec. 

:) alter table ttt modify column x UInt32

ALTER TABLE ttt
    MODIFY COLUMN `x` UInt32


Ok.

0 rows in set. Elapsed: 0.015 sec. 

:) desc ttt

DESCRIBE TABLE ttt

┌─name─┬─type───┬─default_type─┬─default_expression─┬─comment─┬─codec_expression─┬─ttl_expression─┐
│ x    │ UInt32 │ MATERIALIZED │ 3                  │         │                  │                │
│ y    │ UInt32 │              │                    │         │                  │                │
└──────┴────────┴──────────────┴────────────────────┴─────────┴──────────────────┴────────────────┘

2 rows in set. Elapsed: 0.002 sec. 
```

**Comment by KochetovNicolai** [comment]
It's good to have any test with data :)

**Comment by alesapin** [comment]
> Funny thing, but we can't unmaterialize column back:
> 
> ```
> :) desc ttt
> 
> DESCRIBE TABLE ttt
> 
> ┌─name─┬─type───┬─default_type─┬─default_expression─┬─comment─┬─codec_expression─┬─ttl_expression─┐
> │ x    │ UInt32 │ MATERIALIZED │ 3                  │         │                  │                │
> │ y    │ UInt32 │              │                    │         │                  │                │
> └──────┴────────┴──────────────┴────────────────────┴─────────┴──────────────────┴────────────────┘
> 
> 2 rows in set. Elapsed: 0.002 sec. 
> 
> :) alter table ttt modify column x UInt32
> 
> ALTER TABLE ttt
>     MODIFY COLUMN `x` UInt32
> 
> 
> Ok.
> 
> 0 rows in set. Elapsed: 0.015 sec. 
> 
> :) desc ttt
> 
> DESCRIBE TABLE ttt
> 
> ┌─name─┬─type───┬─default_type─┬─default_expression─┬─comment─┬─codec_expression─┬─ttl_expression─┐
> │ x    │ UInt32 │ MATERIALIZED │ 3                  │         │                  │                │
> │ y    │ UInt32 │              │                    │         │                  │                │
> └──────┴────────┴──────────────┴────────────────────┴─────────┴──────────────────┴────────────────┘
> 
> 2 rows in set. Elapsed: 0.002 sec. 
> ```

Yes, it's quite sad, you have to type `ALTER TABLE .. MODIFY COLUMN name Type DEFAULT 0`. I think we need a query which allows to remove column/table modifiers, like `ALTER TABLE .. MODIFY COLUMN name REMOVE DEFAULT` or `ALTER TABLE ... MODIFY COLUMN ... REMOVE TTL` or `ALTER TABLE REMOVE TTL`.

**Review by KochetovNicolai — APPROVED** [review]

**Pull request merged**
