### PR TITLE
Split `CastOverloadResolver` translation unit

### PR DESCRIPTION
**Pull request by alexey-milovidov**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Add the function `toUInt128OrZero`, which was missed by mistake (the mistake is related to https://github.com/ClickHouse/ClickHouse/pull/945). The compatibility aliases `FROM_UNIXTIME` and `DATE_FORMAT` (they are not ClickHouse-native and only exist for MySQL compatibility) have been made case insensitive, as expected for SQL-compatibility aliases.

### CODE REVIEW

**Comment by robot-ch-test-poll3** [comment]
*This is an automated comment for commit c67e8d5d73a6ac1647a023740a859e739d6ab2ee with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/61114/c67e8d5d73a6ac1647a023740a859e739d6ab2ee/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

**Comment by alexey-milovidov** [comment]
```
SELECT
    toDate(check_start_time),
    pull_request_number = 61114 AS my_change,
    min(size) AS s,
    bar(s, 0, 50000000, 80)
FROM binary_sizes
WHERE (file = 'build_docker/src/Functions/CMakeFiles/clickhouse_functions_obj.dir/FunctionsConversion.cpp.o') AND (check_name = 'binary_release') AND (date >= (today() - 10))
GROUP BY ALL
ORDER BY ALL ASC

Query id: 214a9874-ae7c-4fc3-9703-1128bc735a97

┌─toDate(check_start_time)─┬─my_change─┬────────s─┬─bar(min(size), 0, 50000000, 80)─┐
│               2024-03-05 │         0 │ 16479848 │ ██████████████████████████▎     │
│               2024-03-06 │         0 │ 16479848 │ ██████████████████████████▎     │
│               2024-03-07 │         0 │ 15850016 │ █████████████████████████▎      │
│               2024-03-08 │         0 │ 15861520 │ █████████████████████████▍      │
│               2024-03-09 │         0 │ 15861520 │ █████████████████████████▍      │
│               2024-03-09 │         1 │ 10874488 │ █████████████████▍              │
│               2024-03-10 │         0 │ 15861520 │ █████████████████████████▍      │
│               2024-03-10 │         1 │ 10666464 │ █████████████████               │
│               2024-03-11 │         0 │ 15861520 │ █████████████████████████▍      │
│               2024-03-12 │         0 │ 15868096 │ █████████████████████████▍      │
│               2024-03-12 │         1 │ 10673704 │ █████████████████               │
│               2024-03-13 │         0 │ 15868096 │ █████████████████████████▍      │
└──────────────────────────┴───────────┴──────────┴─────────────────────────────────┘
```

**Comment by alexey-milovidov** [comment]
```
SELECT
    toDate(check_start_time),
    pull_request_number = 61114 AS my_change,
    min(size) AS s,
    bar(s, 0, 100000000, 80)
FROM binary_sizes
WHERE (file = 'build_docker/src/CMakeFiles/dbms.dir/Functions/CastOverloadResolver.cpp.o') AND (check_name = 'binary_release') AND (date >= (today() - 10))
GROUP BY ALL
ORDER BY ALL ASC

Query id: fc0fa5e9-c68d-41b0-bcf3-9742fdd7bee2

┌─toDate(check_start_time)─┬─my_change─┬────────s─┬─bar(min(size), 0, 100000000, 80)────────────────────────────────┐
│               2024-03-05 │         0 │ 77986408 │ ██████████████████████████████████████████████████████████████▍ │
│               2024-03-06 │         0 │ 77986528 │ ██████████████████████████████████████████████████████████████▍ │
│               2024-03-07 │         0 │ 76107128 │ ████████████████████████████████████████████████████████████▉   │
│               2024-03-08 │         0 │ 76190872 │ ████████████████████████████████████████████████████████████▉   │
│               2024-03-09 │         0 │ 76193888 │ ████████████████████████████████████████████████████████████▉   │
│               2024-03-09 │         1 │   985136 │ ▊                                                               │
│               2024-03-10 │         0 │ 76193888 │ ████████████████████████████████████████████████████████████▉   │
│               2024-03-10 │         1 │   985168 │ ▊                                                               │
│               2024-03-11 │         0 │ 76193888 │ ████████████████████████████████████████████████████████████▉   │
│               2024-03-12 │         0 │ 76271016 │ █████████████████████████████████████████████████████████████   │
│               2024-03-12 │         1 │   985168 │ ▊                                                               │
│               2024-03-13 │         0 │ 76272000 │ █████████████████████████████████████████████████████████████   │
└──────────────────────────┴───────────┴──────────┴─────────────────────────────────────────────────────────────────┘
```

**Comment by antonio2368** [comment]
Tidy build fails because of these changes

**Pull request merged**
