### PR TITLE
Remove dead list watches from TestKeeperStorage

### PR DESCRIPTION
**Pull request by alesapin**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix dead list watches removal for TestKeeperStorage.

### CODE REVIEW

**Comment by alesapin** [comment]
`01600_remerge_sort_lowered_memory_bytes_ratio` -- known to be flaky.

**Comment by alesapin** [comment]
Wow, the error stress tsan is stable.

**Comment by alesapin** [comment]
Cannot reproduce the error locally, but hope the latest commit will help.

**Comment by alesapin** [comment]
Fixed!

**Comment by alesapin** [comment]
Stress OK, let's merge with master to check one more time

**Comment by alesapin** [comment]
Two times success.

**Comment by alesapin** [comment]
Let's try one more time

**Review by nikitamikhaylov — APPROVED** [review]

**Pull request merged**
