### PR TITLE
Unflake and speed up `01676_clickhouse_client_autocomplete`

### PR DESCRIPTION
**Pull request by thevar1able**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

---
### Modify your CI run:
**NOTE:** If your merge the PR with modified CI you **MUST KNOW** what you are doing
**NOTE:** Checked options will be applied if set before CI RunConfig/PrepareRunConfig step

#### Include tests (required builds will be added automatically):
- [ ]  Fast test
- [ ]  Integration Tests
- [ ]  Stateless tests
- [ ]  Stateful tests
- [ ]  Unit tests
- [ ]  Performance tests
- [ ]  All with ASAN
- [ ]  All with TSAN
- [ ]  All with Analyzer
- [ ]  Add your option here

#### Exclude tests:
- [ ]  Fast test
- [ ]  Integration Tests
- [ ]  Stateless tests
- [ ]  Stateful tests
- [ ]  Performance tests
- [ ]  All with ASAN
- [ ]  All with TSAN
- [ ]  All with MSAN
- [ ]  All with UBSAN
- [ ]  All with Coverage
- [ ]  All with Aarch64
- [ ]  Add your option here

#### Extra options:
- [ ]  do not test (only style check)
- [ ]  disable merge-commit (no merge from master before tests)
- [ ]  disable CI cache (job reuse)

#### Only specified batches in multi-batch jobs:
- [ ]  1
- [ ]  2
- [ ]  3
- [ ]  4

### CODE REVIEW

**Comment by robot-clickhouse-ci-1** [comment]
*This is an automated comment for commit 8053f98d62d657e0f622bac332fdff0690888aeb with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/62209/8053f98d62d657e0f622bac332fdff0690888aeb/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

**Comment by thevar1able** [comment]
Before:

```
2024-04-04 17:19:58 01676_clickhouse_client_autocomplete:                                   [ OK ] 66.81 sec.
```

After:
```
2024-04-04 13:37:25 01676_clickhouse_client_autocomplete:                                   [ OK ] 4.77 sec.
```

**Comment by Avogar** [comment]
It's faster, but it's damn flacky 😅: https://s3.amazonaws.com/clickhouse-test-reports/62209/1caaec66cbdb8153a5e05b25aa63624166603282/stateless_tests_flaky_check__asan_.html

**Comment by thevar1able** [comment]
@Avogar Thanks, I saw that, didn't have time yet to make another pass. The original version is flaky too, I also didn't understand why it needs to send `\t` character three times (I removed `send -- \t` from the loop and tried to reproduce the behavior) before the completion triggers :confused:

**Comment by thevar1able** [comment]
Not flaky anymore https://github.com/ClickHouse/ClickHouse/actions/runs/8621459567/job/23634199521?pr=62209
Although still times out on debug build for some reason :eyes: https://github.com/ClickHouse/ClickHouse/actions/runs/8621459567/job/23634194972?pr=62209

**Comment by thevar1able** [comment]
Still not too bad (from aarch64 run)

```
2024-04-10 06:07:42 01676_clickhouse_client_autocomplete:                                   [ OK ] 6.94 sec.
```

**Review by Avogar — APPROVED** [review]
LGTM

**Pull request merged**
