### PR TITLE
Temporarily remove a feature that doesn't work

### PR DESCRIPTION
**Pull request by tavplubix**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

I've found a few bugs that I missed when reviewing, and the tests didn't catch these bugs because tests were too trivial.
So I'm reverting it for now and will re-implement it properly later.

TODO detailed description

### CODE REVIEW

**Comment by robot-clickhouse-ci-2** [comment]
*This is an automated comment for commit 77e4b0c8d909baea75c7701a77f9cb0ee30db3ca with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/59688/77e4b0c8d909baea75c7701a77f9cb0ee30db3ca/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/59688/77e4b0c8d909baea75c7701a77f9cb0ee30db3ca/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Review by alexey-milovidov — APPROVED** [review]

**Comment by arthurpassos** [comment]
What is it exactly that it is not working? Can I fix it?

**Comment by vzakaznikov** [comment]
@tavplubix, could you please elaborate on the bugs that you have found?
> I've found a few bugs that I missed when reviewing, and the tests didn't catch these bugs because tests were too trivial.

**Comment by tavplubix** [comment]
> @tavplubix, could you please elaborate on the bugs that you have found?

Sure, I'm sorry for not providing more details in the PR description when creating the PR. Although, it's a draft and there's `TODO detailed description` (yesterday I was trying to fix it til late, but gave up and created this PR).

---

I've approved and merged https://github.com/ClickHouse/ClickHouse/pull/39507 by mistake because I got tired of "@tavplubix ping" messages. So I didn't review it carefully before merging and was hoping that the code was mostly okay after previous iterations of review (it wasn't) and that the tests would catch major bugs (they don't). 

---

The problem is here: https://github.com/ClickHouse/ClickHouse/blob/33f6940214282a9ec5908b6fd265f9e3962dad34/src/Storages/StorageReplicatedMergeTree.cpp#L7886-L7965

It initializes `partition_id` with **source partition id** and then uses it for the **destination table** in `getFakePartCoveringAllPartsInPartition` and `makeDummyDropRangeForMovePartitionOrAttachPartitionFrom`. It's absolutely wrong. And we cannot trivially initialize it with the destination partition id because it's calculated later in the loop for each part:
https://github.com/ClickHouse/ClickHouse/blob/33f6940214282a9ec5908b6fd265f9e3962dad34/src/Storages/StorageReplicatedMergeTree.cpp#L7965

Also, the loop assigns new ids to the same `partition_id` variable, and this variable is still used after the loop. It's also funny that if `src_all_parts` is empty, then `partition_id` will keep the wrong value after the loop...

There's a lot of confusion between source and destination partition id in the code, and no chance it could work.

And there are only two trivial tests for REPLACE PARTITION: https://github.com/ClickHouse/ClickHouse/blob/799a94081ba7587ec47d85554bdbb458ffb1436d/tests/queries/0_stateless/02456_test_attach_partition_different_partition_exp.sql#L459-L485

Both of them don't test anything at all because:
 - in both tests, sorce and destination tables have the same `PARTITION BY`
 - both tables are empty in the first one, so ALTER is no-op
 - source table is empty in the second one, so it doesn't test that parts are copied from source to destination
 - both tests check `MergeTree` and don't check `ReplicatedMergeTree` (but there's the same problem in `MergeTree` and the tests don't catch it either)

---

Another problem:
There's a `sync_new_files` argument in `cloneWithDistinctPartitionExpression`, but there's only one place where this function is called from: https://github.com/ClickHouse/ClickHouse/blob/33f6940214282a9ec5908b6fd265f9e3962dad34/src/Storages/MergeTree/MergeTreeData.cpp#L7100-L7115
(I could argue about unnecessary abstractions, over-decomposition, and few-lines-functions that are called only once, but it's not the point)
It just passes `false` unconditionally (so [this](https://github.com/ClickHouse/ClickHouse/blob/87d493533c8f08ce67c571ee644263f887b0fb86/src/Storages/MergeTree/MergeTreeDataPartCloner.cpp#L50-L51) is never executed; was supposed to be controlled by `fsync_after_insert`)

Yes, this one is trivial to fix, but since I didn't review it carefully, I don't know how many other issues there are.

---

The worst part is that there's no setting like `allow_experimental_alter_partition_with_different_key` (My bad, I should have asked to add it)

---

I'm sorry for merging https://github.com/ClickHouse/ClickHouse/pull/39507 prematurely without proper review. I will try to re-implement this feature and add it back when I have time.

**Comment by alexey-milovidov** [comment]
What if we will try a simpler variant of this feature: allow to attach parts into a table with no (empty) partition key?

**Comment by arthurpassos** [comment]
If I understand correctly, there are 4 issues:

1. `partition_id` mess on ReplicatedMergeTree
2. replace partition tests
3. `sync_new_files`
4. experimental feature setting

2-4 should be easy to fix, one is trickier. Would you accept a PR if I fix all of those?

**Comment by vzakaznikov** [comment]
Thanks, @tavplubix, for providing the details! When you refer to bugs, it seems like most of the issues that you've identified are internal to the implementation code. Do you have a specific functional test scenario that you've found which does not work with this implementation?

**Comment by tavplubix** [comment]
@vzakaznikov, are you kidding? Please try any non-trivial REPLACE PARTITION

**Comment by arthurpassos** [comment]
@tavplubix I am trying to fix those issues locally. Would you review the PR with these fixes?

I have one question regarding `replace` and empty source partition. If source partition is empty and the destination partition expression is different, there is no way to calculate the destination partition id. What do you think it's best to do in this case? Throw exception or simply ignore?

**Comment by tavplubix** [comment]
> partition_id mess on ReplicatedMergeTree

Mess on non-replicated MergeTree as well

Also, I would avoid few-lines-functions that are called only once and instead use extract-method-technique for its main purpose: avoid code duplication 

> Would you accept a PR if I fix all of those?

Yes, but please make sure you have tested everything and looked through the diff in the PR (self-review is very helpful sometimes) before pinging reviewers.

> I have one question regarding replace and empty source partition. If source partition is empty and the destination partition expression is different, there is no way to calculate the destination partition id. What do you think it's best to do in this case? Throw exception or simply ignore?

It's a good question and the most interesting part. I think for REPLACE/MOVE, throwing an exception is much better. For ATTACH, ignoring is slightly better. But we can also consider changing the query syntax and require specifying both partition ids (like `ATTACH/REPLACE/MOVE PARTITION ID 'src' AS 'dst'`)

> I was not kidding. It is not evident from the user's perspective that the ATTACH code is shared with the REPLACE code, and therefore, at least in our internal testing, we focused on the ATTACH functionality.

ClickHouse is not a black box and we are not users. When you touch code that is clearly shared, you should make sure that you don't break other usecases.

Also, we have MOVE PARTITION TO TABLE (this feature was merged by mistake a long time ago, but it was too late to remove when we figured this out). Unfortunately, it was implemented by copy-pasting `StorageMergeTree::replacePartitionFrom` to `StorageMergeTree::movePartitionToTable`. But it uses `checkStructureAndGetMergeTreeData` too, and the check for exact match of partition keys was removed from `checkStructureAndGetMergeTreeData`. So here's another issue: `StorageMergeTree::replacePartitionFrom` works with different partition keys, but works incorrectly.

**Pull request merged**
