### PR TITLE
Implement functions findClusterIndex and findClusterValue.

### PR DESCRIPTION
**Pull request by mfridental**
findClusterIndex(x, centroids_array) - find index of element in centroids_array with the value nearest to x
findClusterValue(x, centroids_array) - find value of element in centroids_array with the value nearest to x

Types:
findClusterIndex(T, Array(T)) -> UInt64
findClusterValue(T, Array(T)) -> T

T can be any numeric type.

Example:
SELECT findClusterValue(income, [20000, 40000, 65000, 120000, 250000]) as IncomeCategory
FROM Survey

### CODE REVIEW

**Comment by robot-metrika-test** [comment]
Can one of the admins verify this patch?

**Comment by alexey-milovidov** [comment]
Missing test.
Look at `dbms/tests/queries` directory.

**Comment by alexey-milovidov** [comment]
I still would like to have a test in our repository.
Because otherwise we could eventually break this function.

**Comment by mfridental** [comment]
Yes, will add it asap, currently I'm very busy with other things. Hope to have time this week.

**Pull request merged**
