### PR TITLE
[RFC] Support WebTerminal client for ClickHouse

### PR DESCRIPTION
**Pull request by zhang2014**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- New Feature

Changelog entry:

Support WebTerminal Client for ClickHouse server.

Detailed description:

I'm not sure if this is useful for ClickHouse(we can discuss it), but I implemented it first (although the code quality was a bit poor :( )
## Effect picture ：
image

## Motivation :
- Online Demo
- Users using Windows or OSX system
- Server in some VPC networks 
- Some scenarios where TCP ports cannot be exposed

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
> I'm not sure if this is useful for ClickHouse

Yes, it is useful!
We are interested in web playground for exploration of ClickHouse. And this feature will help a lot.

**Comment by geldot** [comment]
Alternative approach:

On the server side, expose clickhouse-client via `Poco.Net.WebSocket` as a protocol upgrade just after [authentication](https://github.com/ClickHouse/ClickHouse/blob/master/programs/server/HTTPHandler.cpp#L544).

On the browser side, use the existing [xtermjs](https://github.com/xtermjs/xterm.js) and [xterm-addon-attach](https://xtermjs.org/docs/api/addons/attach/) or any terminal that supports standard WebSockets:

```javascript
import { Terminal } from 'xterm';
import { AttachAddon } from 'xterm-addon-attach';

const term = new Terminal();
const socket = new WebSocket('wss://http://localhost:8123/?user=someuser&password=mypassword&interactive=1');
const attachAddon = new AttachAddon(socket);

// Attach the socket to term
term.loadAddon(attachAddon);
```

The benefit is that the implementation will be lighter/less code to maintain because authentication and sessions are already handled through a well-known code path in via existing ClickHouse HTTP support and WebSocket upgrade, also less security exposure, and less to document for users.

It also simplifies the client-side developer experience by supporting standard components without the need for form submissions, long-polling or JQuery. Docker, VS Code and other projects are using this nowadays.

The experience is also improved for the end user because they get the full `clickhouse-client` experience including tab completion.

**Comment by alexey-milovidov** [comment]
@zhang2014 I agree with @geldot.
The current implementation duplicates half of clickhouse-client logic and half of HTTPHandler logic.
It is quite well engineered, but we can do it a more simple way...
What if we send and receive terminal commands between the server and client directly?

Example: as we already implemented basic syntax highlighting in clickhouse-client, we want for it to be available in web terminal automatically.

PS. This feature is useful and it is appreciated.
As of now, we already have [play web UI](https://gh-api.clickhouse.tech/play?user=play) but I will be happy to also see clickhouse-client interface exposed via web terminal - it's good for demo purposes :)

**Comment by zhang2014** [comment]
@alexey-milovidov I agree with @geldot too. 
> PS. This feature is useful and it is appreciated.
As of now, we already have play web UI but I will be happy to also see clickhouse-client interface exposed via web terminal - it's good for demo purposes :)
(Also it's ok to just close this task if you don't want to bother).

This task is very interesting and I still want to continue(But it's not high priority).

**Comment by alexey-milovidov** [comment]
@zhang2014, thank you for the PR! Finished in https://github.com/ClickHouse/ClickHouse/pull/100277.

**Pull request closed without merging**
