### PR TITLE
DOCSUP-4737: Fixed columns syntax

### PR DESCRIPTION
**Pull request by olgarev**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category:
- Documentation

### CODE REVIEW

**Comment by olgarev** [comment]
@qoega Can you review this one, pls?

**Review by alexey-milovidov — CHANGES_REQUESTED** [review]
Any expression with column matcher or transformers applicable.

**Comment by olgarev** [comment]
@alexey-milovidov Thanks for comment. I think, I will wait for #17231 translated to add links to SELECT modifiers.

**Comment by olgarev** [comment]
@alexey-milovidov Hi, I think, it will be better not to wait for the russian translation. Instead, I'll ask to insert the links as soon as the text is translated. 
Will you review this again, pls? I made the changes you requested.

**Comment by alexey-milovidov** [comment]
LGTM. I removed `or COLUMNS` fragment because it can confuse reader.

**Review by alexey-milovidov — APPROVED** [review]

**Pull request merged**
