### PR TITLE
Better dynamic disk configuration

### PR DESCRIPTION
**Pull request by kssenii**
### Changelog category (leave one):
- Backward Incompatible Change

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
If a dynamic disk contains a name, it should be specified as `disk = disk(name = 'disk_name'`, ...) in disk function arguments. In previous version it could be specified as `disk = disk_<disk_name>(...)`, which is no longer supported.

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]

**Comment by robot-ch-test-poll** [comment]
This is an automated comment for commit b683477b2034aaa3a5af7e21795d4a928cd1a719 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/52820/b683477b2034aaa3a5af7e21795d4a928cd1a719/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Review by alexey-milovidov — APPROVED** [review]

**Comment by tavplubix** [comment]
@alexey-milovidov, it breaks Upgrade check, and it even was found by the CI: https://s3.amazonaws.com/clickhouse-test-reports/52820/b683477b2034aaa3a5af7e21795d4a928cd1a719/upgrade_check__msan_.html 

But then it randomly happened to pass after updating the branch and restarting all tests. We should not just restart CI without checking previous failures

**Comment by kssenii** [comment]
@tavplubix, as I understand upgrade check will fix automatically be fixed once backport of this PR to 23.7 is merged? (I merged it one hour ago)

**Comment by tavplubix** [comment]
> upgrade check will fix automatically be fixed once backport of this PR to 23.7 is merged? 

No, it requires new patch-release

**Pull request merged**
