### PR TITLE
Enable keeper fault injection for inserts in functional tests

### PR DESCRIPTION
**Pull request by devcrafter**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Follow up #42607 #43122

### CODE REVIEW

**Comment by SmitaRKulkarni** [comment]
Some stress tests fail with 'Cannot start clickhouse-server', could this be related to the change ?

**Comment by devcrafter** [comment]
@tavplubix is this PR valid way to enable ZK fault injections for inserts in tests?

**Comment by tavplubix** [comment]
Yep, it looks valid

**Comment by devcrafter** [comment]
Test failures:
- `test_consistent_parts_after_clone_replica/test.py::test_inconsistent_parts_if_drop_while_replica_not_active` - cluster failed to start for a reason
- `test_read_only_table/test.py::test_restart_zookeeper` - can be non-deterministic, - we hardly can guarantee that server'll reconnect in 5 secs timeout to another keeper node (despite doing our best), technically, I guess we only can measure the time after which we can successfully execute INSERT:
```
        # ClickHouse should +- immediately reconnect to another zookeeper node
        cluster.stop_zookeeper_nodes([node1_zk])
        time.sleep(5)
    
        for table_id in range(NUM_TABLES):
>           node1.query(
                f"INSERT INTO test_table_{table_id} VALUES (6), (7), (8), (9), (10);"
            )
```
The simplest we can do - is to increase timeout. A bit more sophisticated - retries for inserts on test side. We could use keeper retries on insert as well, but then we need to get from query_log time to execute the query - it'll make the test more complicated. @tavplubix  WDYT?

**Comment by devcrafter** [comment]
> `time.sleep(5)` never works, we should replace it with something like `node.query_with_retry`

Fixed in #43326

**Pull request merged**
