### PR TITLE
Add and check system.mutations for database filter

### PR DESCRIPTION
**Pull request by azat**
Changelog category (leave one):
- Not for changelog (changelog entry is not required)

*Note: this PR includes #27303, since otherwise there will be conflicts*

### CODE REVIEW

**Comment by azat** [comment]
>Functional stateless tests flaky check (address) — Timeout, fail: 64, passed: 4

Requires #27214

**Comment by nikitamikhaylov** [comment]
@azat So I need to merge #27303 first ? Or simply merge only this PR?

**Comment by azat** [comment]
>@azat So I need to merge #27303 first ? Or simply merge only this PR?

Both options is OK (since this PR includes it, and commits are identical)

**Comment by nikitamikhaylov** [comment]
@azat And what about 01079_parallel_alter_modify_zookeeper_long ? Maybe remove it from parallel execution?

**Comment by azat** [comment]
>@azat And what about 01079_parallel_alter_modify_zookeeper_long ? Maybe remove it from parallel execution?

Exclude tests from parallel runs may hide some possible issues, so I would try to fix it first, instead of excluding it from parallel run.
I can look into it separately or as a part of this pr.
But anyway this is not related to this change.

**Comment by nikitamikhaylov** [comment]
> But anyway this is not related to this change.
I know. This is because you added changes to this test. I mean, it's worth paying attention to it.

**Pull request merged**
