### PR TITLE
translate comments

### PR DESCRIPTION
**Pull request by f1yegor**

### CODE REVIEW

**Comment by robot-metrika-test** [comment]
Can one of the admins verify this patch?

**Comment by alexey-milovidov** [comment]
Wow! Just great.

**Comment by alexey-milovidov** [comment]
Some comments have zero width spaces. Will remove.

**Comment by alexey-milovidov** [comment]
```
find dbms -name '*.h' -or -name '*.cpp' | xargs grep -l $'\xe2\x80\x8b' | xargs sed -i 's/'$'\xe2\x80\x8b''//g'
```

https://github.com/yandex/ClickHouse/commit/f24df4b648f352c068b3a3f9102e07d1969e1ab4

**Pull request merged**
