### PR TITLE
Devirtualize serialize call in AggregateFunction

### PR DESCRIPTION
**Pull request by alesapin**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Run only fuzzers related jobs (libFuzzer fuzzers, AST fuzzers, etc.)
- [ ]  Exclude: AST fuzzers
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-ch-test-poll3** [comment]
*This is an automated comment for commit e80920ecd19ed6601fb9e6126a824f41dac8e722 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/72556/e80920ecd19ed6601fb9e6126a824f41dac8e722/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/a38700e5d1d0507873449e1c9d30e198f4c16920/docs_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Review by alexey-milovidov — APPROVED** [review]
Looks good. Add a performance test?

**Comment by alesapin** [comment]
I was naive, for some reason doesn't work.

**Comment by alesapin** [comment]
@alexey-milovidov I see no performance noticeable improvements in my local env. But I think it's still make sense to merge?

And of course Nikita is right, most perf we can get from de-serialize .

**Comment by alexey-milovidov** [comment]
It should be visible when we serialize many small aggregate states, e.g., `max`.
A synthetic test could include the `initializeAggregation` function.

**Comment by alesapin** [comment]
Almost all aggregate functions are `final` so devirtualization doesn't give any benefits. But we still have some examples like `avg`. With this function I've managed to get very small improvement, like 11.3 seconds for query in test VS 12.3 in master.

**Comment by alesapin** [comment]
This change https://github.com/ClickHouse/ClickHouse/pull/72556/commits/1d0caf1c906f359b90ed7c6a266417a463cfbe34 gives x5 performance improvement for test, but possibly it's wrong.

**Comment by alesapin** [comment]
Lol
image

**Review by CurtizJ — APPROVED** [review]

**Comment by clickgapai** [comment]
Hi @alesapin @alexey-milovidov @CurtizJ — while reviewing this PR I found the following:

- **Bug (P2):** `updateHashFast` missing `version` parameter causes hash inconsistency for versioned aggregate functions — https://github.com/ClickHouse/ClickHouse/issues/104805

Happy to discuss — close anything that's wrong or already addressed.

**Pull request merged**
