### PR TITLE
Revert "Revert "Mark select() as harmful function""

### PR DESCRIPTION
**Pull request by devcrafter**
Reverts ClickHouse/ClickHouse#57195

### CODE REVIEW

**Comment by robot-ch-test-poll3** [comment]
*This is an automated comment for commit 17f4205027fe106f11973cc3f6361e71f116edcf with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/57370/17f4205027fe106f11973cc3f6361e71f116edcf/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td><a href="https://github.com/ClickHouse/ClickHouse/actions/runs/7038095994">✅ success</a></td></tr>
<tbody>
</table>
</details>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/57370/17f4205027fe106f11973cc3f6361e71f116edcf/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Comment by devcrafter** [comment]
`select()` usage:
```
src/IO/ReadBufferFromFileDescriptor.cpp
src/Client/LineReader.cpp
base/poco/Foundation/src/DirectoryWatcher.cpp
```
```
contrib/replxx
contrib/libpqxx
contrib/google-protobuf
contrib/cyrus-sasl
contrib/boringssl
contrib/boost/boost/asio/
```

**Comment by alexey-milovidov** [comment]
We can also substitute a hardened version of the `select` function.

**Comment by devcrafter** [comment]
> We can also substitute a hardened version of the `select` function.

Do you mean introducing `select()` in `glibc-compatibility` layer with explicit checks on number of descriptors in `select()` and `FD_SET/...' macros?

**Comment by devcrafter** [comment]
UBSan report - https://s3.amazonaws.com/clickhouse-test-reports/57370/17f4205027fe106f11973cc3f6361e71f116edcf/fuzzer_astfuzzerubsan/report.html

**Comment by alexey-milovidov** [comment]
Yes, if a complete removal will be hard.

**Pull request closed without merging**
