### PR TITLE
Show MaterializeMySQL tables in system.parts

### PR DESCRIPTION
**Pull request by stigsb**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Show MaterializeMySQL tables in `system.parts`

Detailed description / Documentation draft:

### CODE REVIEW

**Comment by stigsb** [comment]
This is somewhat of a kludge, but so far I have not found a cleaner way to fix this without more refactoring.

**Comment by stigsb** [comment]
Fixed the build failure (Yandex CI builds without -DENABLE_MYSQL, apparently)

**Comment by stigsb** [comment]
Fixed integration test (failed if system_parts_test database already existed, counted all parts and not just active).

**Review by tavplubix — APPROVED** [review]

**Comment by stigsb** [comment]
@tavplubix is there anything else I need to do before this PR is ready for merge?

**Pull request merged**
