### PR TITLE
Revert "Revert "Refactoring of Server.h: Isolate server management from other logic""

### PR DESCRIPTION
**Pull request by rschu1ze**
This PR reverts #64425 which is a revert of #64132.

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by robot-clickhouse-ci-2** [comment]
*This is an automated comment for commit 1a3ec8b21708cd64092f6f3f014cbc479f47896c with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/64447/1a3ec8b21708cd64092f6f3f014cbc479f47896c/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>A Sync</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>⏳ pending</td></tr>
<tbody>
</table>
<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

**Comment by rschu1ze** [comment]
Blocked by https://github.com/ClickHouse/ClickHouse/pull/64551

**Comment by rschu1ze** [comment]
@TTPO100AJIEX This PR (Server.cpp) is in utter merge conflict hell. I tried to fix it, failed after messing with the build for 30 minutes, and now need to move on to more pressing tasks. If you like to continue with this refactoring, kindly resolve the conflicts and force-push a new commit or push on top of the current commit. Thanks.

**Comment by TTPO100AJIEX** [comment]
> @TTPO100AJIEX This PR (Server.cpp) is in utter merge conflict hell. I tried to fix it, failed after messing with the build for 30 minutes, and now need to move on to more pressing tasks. If you like to continue with this refactoring, kindly resolve the conflicts and force-push a new commit or push on top of the current commit. Thanks.

@rschu1ze I could not push to your repository. Created a new PR with a revert. Take a look, please: https://github.com/ClickHouse/ClickHouse/pull/64599

**Comment by rschu1ze** [comment]
Merci, I'll check.

**Pull request closed without merging**
