### PR TITLE
Tiny build changes

### PR DESCRIPTION
**Pull request by azat**
- build: switch llvm to -std=gnu++17
- build: use -Wno-c++2a-compat over -Wno-c++20-compat (since -std=c++2a), for parsers from #11298 
- require clang-11 for building debian package in d/control (it is used for production builds, and it is kind of strange that it does not required by the debian manifests)
- ThinLTO provides its own parallel linking, limit to 2 in case of ThinLTO
- re-enable jobs limits (has been disabled in #11298, @abyss7 please let me know if that was done on purpose I will drop this patch)

Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]
LGTM

**Comment by azat** [comment]
01561_Date_and_DateTime64_comparision - already reported https://github.com/ClickHouse/ClickHouse/pull/17895#issuecomment-742101261

It does not work at this time of day...

**Comment by azat** [comment]
Can someone mark with force-tests label?

**Comment by azat** [comment]
Since the culprit was reverted, rebased against upstream/master

**Pull request merged**
