### PR TITLE
Add intel AMX checking

### PR DESCRIPTION
**Pull request by omgronny**
### Changelog category (leave one):
- Not for changelog

### CODE REVIEW

**Comment by antaljanosbenjamin** [comment]
I checked the flags based on this: https://cdrdv2-public.intel.com/790021/architecture-instruction-set-extensions-programming-reference.pdf

**Review by antaljanosbenjamin — COMMENTED** [review]
Do you have any specific goal with these extensions, or you just added them to have them?

**Comment by robot-ch-test-poll** [comment]
*This is an automated comment for commit c9bb02d8a0114c1ffe646b759d6fabe9dc4ea8f0 with description of existing statuses. It's updated for the latest CI running*

[❌ Click here](https://s3.amazonaws.com/clickhouse-test-reports/58617/c9bb02d8a0114c1ffe646b759d6fabe9dc4ea8f0/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>❌ failure</td></tr>
<tbody>
</table>

**Comment by qoega** [comment]
Build failed
```
2024-01-09 11:19:53 /ClickHouse/src/Common/TargetSpecific.cpp:43:13: error: enumeration values 'AMXBF16', 'AMXTILE', and 'AMXINT8' not handled in switch [-Werror,-Wswitch]
```

**Comment by omgronny** [comment]
> Do you have any specific goal with these extensions, or you just added them to have them?

For purposes of #48831

**Review by alexey-milovidov — APPROVED** [review]
LGTM

**Review by antaljanosbenjamin — APPROVED** [review]

**Review by alexey-milovidov — APPROVED** [review]

**Pull request merged**
