### PR TITLE
test to check what happen with tests if allow_experimental_projection_optimization is enabled

### PR DESCRIPTION
**Pull request by den-crane**
Do not merge.

we observe that allow_experimental_projection_optimization impacts tables/queries without projections.

Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by den-crane** [comment]
> > we observe that allow_experimental_projection_optimization impacts tables/queries without projections.
> 
> Yes. After #26286 every merge tree table will have a virtual projection.

we experience it with 21.9, some queries fail.

**Comment by amosbird** [comment]
Looks quite problematic. Will investigate.

**Comment by den-crane** [comment]
https://github.com/ClickHouse/ClickHouse/issues/30146

**Comment by amosbird** [comment]
https://github.com/ClickHouse/ClickHouse/pull/30293

Will fix other issues in subsequent PRs.

**Comment by amosbird** [comment]
01748_partition_id_pruning     https://github.com/ClickHouse/ClickHouse/pull/30310

**Comment by amosbird** [comment]
https://github.com/ClickHouse/ClickHouse/pull/34305

**Pull request closed without merging**
