### PR TITLE
Apply patch from #13859

### PR DESCRIPTION
**Pull request by KochetovNicolai**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
MemoryTracking support for FreeBSD. Patch from #13859

### CODE REVIEW

**Comment by KochetovNicolai** [comment]
Looks like we also need `kvm` and `elf` at least

**Comment by alexey-milovidov** [comment]
By the way, why procfs does not give expected results? According to man page, the format is the same...

**Comment by urgordeadbeef** [comment]
> By the way, why procfs does not give expected results? According to man page, the format is the same...

https://wiki.freebsd.org/AvoidingLinuxisms

**Comment by alexey-milovidov** [comment]
> Don't record timestamps in the critical path of the app if it also works without (getting timestamps may be slow, depending on the accuracy of timestamps in the OS). If you have to get timestamps, determine how precise they have to be and use an API, which is documented to just deliver the needed precision. 

Does it have something like vdso, so clock_gettime with CLOCK_MONOTONIC will be not too slow?

**Comment by alexey-milovidov** [comment]
If the required files in procfs are in fact compatible with Linux in recent versions of FreeBSD (we target versions 11+), we will prefer using it instead of using two different APIs under ifdef - just to keep code smaller...

**Comment by alexey-milovidov** [comment]
I've read this memo and found this

> A number of simple syscalls (for example gettimeofday, getpid) are much faster on Linux than on any other operating system due to caching and the vsyscall performance optimizations. Do not rely on them being cheap in performance-critical applications. In general, try hard to avoid syscalls if at all possible. 

may be a concern. We use clock_gettime quite extensively (not very extensively, though). Need to test for performance...

**Comment by alexey-milovidov** [comment]
PS. Could you please provide a link to FreeBSD image that is bootable under QEMU and has virtual network driver + ssh?
I know that Vagrant does it, but it does not work in our CI for some reason...

**Comment by olevole** [comment]
> PS. Could you please provide a link to FreeBSD image that is bootable under QEMU and has virtual network driver + ssh?
> I know that Vagrant does it, but it does not work in our CI for some reason...

Official FreeBSD images: https://download.freebsd.org/ftp/releases/VM-IMAGES/12.1-RELEASE/amd64/Latest/    ( DHCP by default + root without password via terminal ).

Unofficial (+ cloud-init ) images, for example can be used from here: https://bsd-cloud-image.org/

**Comment by olevole** [comment]
> @urgordeadbeef it's only allowed to use libraries from `contrib`, no system/package provided libraries are possible.
> This is needed because FreeBSD build is cross-compiled.

libprocstat/kvm is part of the FreeBSD kernel. As far as I understand, the contrib/ can only contain userland 3rd-party deps.
From my point of view, we should use a platform-specific syscall as the behavior of this code will not be obvious when the FreeBSD version changes (or when Clickhouse is run in a jail/container that is different version from the host system).

PS: BTW, does CH build for macOS platform the same way?
PS2: I can test the patch and apply at the FreeBSD port level if this patch is suitable for 20.7.2.30 - ( https://repology.org/project/clickhouse/versions - currently I am a maintainer of CH for FreeBSD ;-)

**Comment by ssotik** [comment]
Thank. Helped for me.

**Comment by olevole** [comment]
There have been several reports from FreeBSD Clickhouse users about this issue. The patches fix the problem and are applied now at the FreeBSD ports level: https://svnweb.freebsd.org/ports?view=revision&revision=548207 for 20.7.2.30 ( https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=249205 ).

Hope to see it upstreamed, thanks!

**Comment by alexey-milovidov** [comment]
Actually we can apply this patch as is if we will copy the relevant headers and libraries to our cross-compile toolchain.
BTW, why don't continue to use procfs? I found that it is not mounted by default, but there are many tools that still require procfs, so it should likely to be mounted on the server? Maybe we can require mounting procfs as an installation step?

**Comment by olevole** [comment]
> BTW, why don't continue to use procfs? I found that it is not mounted by default, but there are many tools that still require procfs, so it should likely to be mounted on the server? Maybe we can require mounting procfs as an installation step?

Actually yes - I can add an appropriate post-install message for http://man.freebsd.org/procfs/5 in FreeBSD port (package), but unfortunately /proc/%d/statm is Linux-only. In FreeBSD it is available through http://man.freebsd.org/linprocfs/5 but linprocfs available ( as /proc) for Linux binaries (Linuxulator) ;-)

I've tried to take a quick look at various projects and everyone here uses information from sysctl or  http://man.freebsd.org/kvm/3:

https://gist.github.com/wolfspider/33174be531b51287fbfb3b084baf766c
https://svnweb.freebsd.org/ports/head/games/openbor/files/patch-source_ramlib_ram.c?revision=508692&view=markup#l182
https://github.com/netdata/netdata/blob/master/collectors/freebsd.plugin/freebsd_sysctl.c#L193

So my guess is that if it helps make Clickhouse a more cross/multi-platform product (I still don't know how things are on MacOS and Windows), it should be handled depending on the OS.

**Comment by alexey-milovidov** [comment]
`sysctl` variant should be Ok.

**Comment by alexey-milovidov** [comment]
This PR was abandoned. 
The variant with `sysctl` is still considered and should be implemented in another PR.

**Comment by olevole** [comment]
@alexey-milovidov thanks for closing ;-). Is there a new Issue/PR so that we can link and track the solution?

At the moment, I cannot update the https://www.freshports.org/databases/clickhouse port without these fixes.
There have been several reports/feedback from different people about this issue, so you can be sure clickhouse is being used on freebsd

**Pull request closed without merging**
