### PR TITLE
Update arrow submodule head for parquet endian issue for s390x

### PR DESCRIPTION
**Pull request by rschu1ze**
This is really https://github.com/ClickHouse/ClickHouse/pull/53807 but under my name. All credits to to @HarryLeeIBM . I only reason I pushed this PR is because I didn't have technical permissions in HarryLeeIBM's fork and the discussion got a bit complicated.

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by robot-ch-test-poll3** [comment]
This is an automated comment for commit 69fd85ea73017640424c4999270303a297503132 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/53814/69fd85ea73017640424c4999270303a297503132/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Comment by HarryLeeIBM** [comment]
@rschu1ze, I found this PR is still in Draft, could you convert it to "Open" and let it build? Thanks!

**Comment by rschu1ze** [comment]
@HarryLeeIBM Sorry for the delay. Just pushed your PR again, let's see what CI says.

**Comment by rschu1ze** [comment]
@HarryLeeIBM Lots of tests fail :-( Would you like to check? Thanks.

**Comment by HarryLeeIBM** [comment]
@rschu1ze, the fix broke some functional tests. Could you please rollback the [PR 41](https://github.com/ClickHouse/arrow/pull/41) in submodule so that it won't affect the submodule? In the meanwhile, I will do more investigation on this. Thanks!

**Comment by rschu1ze** [comment]
@HarryLeeIBM Dn't worry, as long as this PR is open, there are no unintended side effects of any type. This PR is based on this submodule branch: https://github.com/ClickHouse/arrow/commits/clickhouse/release-11.0 (feel free to make PRs (e.g. reverts / fixes) against `release-11.0`)

**Comment by Avogar** [comment]
I am going to update arrow to `release-13.0.0`, so I created separate branch for it and I will make it default branch in our fork, please, make PRs to this branch

**Comment by rschu1ze** [comment]
Just for reference wrt. https://github.com/ClickHouse/ClickHouse/pull/53814#issuecomment-1725909321: #54800

**Comment by rschu1ze** [comment]
@HarryLeeIBM Feel free to continue, I'll close this one for now.

**Pull request closed without merging**
