### PR TITLE
keeper connection mode in doc file not work

### PR DESCRIPTION
**Pull request by cw5121**
### Changelog category (leave one):
- Documentation (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
- none

### CODE REVIEW

**Comment by jsc0218** [comment]
Sorry, I don't understand your pr, since your doc change is one thing, and while your changelog entry is another thing.

**Comment by cw5121** [comment]
> Sorry, I don't understand your pr, since your doc change is one thing, and while your changelog entry is another thing.

sorry，I delete the changelog entry. When I use clickhouse-keepe-client.md guideline "clickhouse-keeper-client -h localhost:8181" to connect, it aborted, change to "clickhouse-keeper-client -h localhost -p 8181" OK.

**Comment by jsc0218** [comment]
> > Sorry, I don't understand your pr, since your doc change is one thing, and while your changelog entry is another thing.
> 
> Sorry，I deleted the misleading changelog entry. When I use clickhouse-keeper-client.md guideline "clickhouse-keeper-client -h localhost:8181" to connect, it aborted, change to "clickhouse-keeper-client -h localhost -p 8181" OK.

Would you mind to refine your description of your change, I got confused again as in your change is. 9181, in your description is 8181.

**Comment by cw5121** [comment]
> > > Sorry, I don't understand your pr, since your doc change is one thing, and while your changelog entry is another thing.
> > 
> > 
> > Sorry，I deleted the misleading changelog entry. When I use clickhouse-keeper-client.md guideline "clickhouse-keeper-client -h localhost:8181" to connect, it aborted, change to "clickhouse-keeper-client -h localhost -p 8181" OK.
> 
> Would you mind to refine your description of your change, I got confused again as in your change is. 9181, in your description is 8181.

Sorry, I reorganized the description：

1. use "-h localhost:9181" followed doc is aborted.

```
root@c64618ba15d1:~# ./clickhouse-keeper-client -h localhost:9181
getservbyname
Aborted
```

2. use "-h localhost -p 9181" is ok.
 ```
root@c64618ba15d1:~# ./clickhouse-keeper-client -h localhost -p 9181
Connected to ZooKeeper at 127.0.0.1:9181 with session_id 20
Keeper feature flag FILTERED_LIST: enabled
Keeper feature flag MULTI_READ: enabled
Keeper feature flag CHECK_NOT_EXISTS: disabled
Keeper feature flag CREATE_IF_NOT_EXISTS: disabled
/ :)
```

**Comment by robot-clickhouse-ci-1** [comment]
*This is an automated comment for commit 4b26a08318b44e7367262f200017a05749480b42 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/58449/4b26a08318b44e7367262f200017a05749480b42/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td><a href="https://github.com/ClickHouse/ClickHouse/actions/runs/7418771900/job/20278023325">✅ success</a></td></tr>
<tbody>
</table>
</details>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/58449/4b26a08318b44e7367262f200017a05749480b42/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Pull request merged**
