### PR TITLE
Allow LD_PRELOAD for Research Reasons

### PR DESCRIPTION
**Pull request by jalalmostafa**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
The draft pull request is just to use the CI system to test some research ideas.  It does need to be merged.

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### CODE REVIEW

**Comment by jalalmostafa** [comment]
@Algunenano I know. The draft pull request is just to use the CI system to test some research ideas.
I already discussed this with @alexey-milovidov 
I would be grateful if you re-open.

**Comment by Algunenano** [comment]
It would have been much simpler to explain it in the PR itself

**Comment by robot-ch-test-poll** [comment]
*This is an automated comment for commit 105d6054b1a2439baa7e9b6d6bf86d4f9113a51e with description of existing statuses. It's updated for the latest CI running*

[❌ Click here](https://s3.amazonaws.com/clickhouse-test-reports/60761/105d6054b1a2439baa7e9b6d6bf86d4f9113a51e/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td><a href="https://github.com/ClickHouse/ClickHouse/blob/master/.github/PULL_REQUEST_TEMPLATE.md?plain=1">❌ failure</a></td></tr>
<tbody>
</table>

**Comment by alexey-milovidov** [comment]
Yes, this is just to obtain a build for further testing.

**Comment by alexey-milovidov** [comment]
None of the builds succeed due to:

```
Mar 05 02:59:38 /build/programs/main.cpp:292:6: error: unused function 'checkHarmfulEnvironmentVariables' [-Werror,-Wunused-function]
Mar 05 02:59:38   292 | void checkHarmfulEnvironmentVariables(char ** argv)
```

**Pull request closed without merging**
