### PR TITLE
Fix for Load job failed JSON exception

### LINKED ISSUE #65154: Load job "system.part_log" failed JSON exception: error: 1 unexpected end of data
**Describe what's wrong**

broken serialization.json can prevent ClickHouse from starting, instead of marking part as broken

https://github.com/ClickHouse/ClickHouse/blob/bd45a366f7d42bd50dd90283c4992a69894ae674/src/Storages/MergeTree/IMergeTreeDataPart.cpp#L1605

### PR DESCRIPTION
**Pull request by MikhailBurdukov**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix the case when serialization.json in part is broken and clickhouse-server can't start.  Resolves #65154  

### Comments 
This issue isn't presented in masteras it has been fixed by another PR(#62306).  Im not sure that we should backporting it because it's quite large. Also i will made a PR with test-only in the master.
### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Review by yariks5s — CHANGES_REQUESTED** [review]
image
tests didn't start because you merge not into master. You can backport it to the previous versions if you want. Moreover, 24.3 is LTS so tests should be passed for those actions

**Comment by MikhailBurdukov** [comment]
> You can backport it to the previous versions if you want. 

The problem is that this fix already presented in the master. 
https://github.com/ClickHouse/ClickHouse/blob/0c9ed351eff0965c5c395a5d25b873bde48fd4f4/src/Storages/MergeTree/checkDataPart.cpp#L100-L110

It was introduced in  #62306  and description/changes not really related to bug which we're trying to fix. 
But if it is hard to run tests in PR for non-master branch, can we backport  #62306 then? wdyt?

**Comment by yariks5s** [comment]
@MikhailBurdukov Original PR should be backported to 24.3, I've put a label on it

**Comment by yariks5s** [comment]
Backported

**Pull request closed without merging**
