### PR TITLE
Added Multiquery support to HTTP interface

### PR DESCRIPTION
**Pull request by jcdang**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

- New Feature

Short description (up to few sentences):
Added multiquery support via HTTP.

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
Could you please also add a test?
You can use `.sh` test. Similar tests are located in `dbms/tests/queries/0_stateless`.

**Comment by alexey-milovidov** [comment]
Ok. And we need `reference` file for the test. It is just stdout:
`00936_multiquery_http.sh > 00936_multiquery_http.reference`

**Comment by alexey-milovidov** [comment]
Three tests have failed.

**Comment by alex-krash** [comment]
This functionality is inconsistent, cause it allows to send queries with different output format, and with different type (select/insert/alter). This will lead to trash output.

**Comment by filimonov** [comment]
It's a bit contoversional as give no feedback per query, and behaviour of http status and headers related to progress / summary is not clear.

I don't think it will have any advantages comparing to multiple queries in single connection in one http keepalive session.

So i afraid that users will tend to use that multiquery by default, and afterthat will get to the point when output of some particupar query should not be ignored and another ugly hacks/fixes to get such a feedback will be requested.

**Comment by filimonov** [comment]
@jcdang did you try http keepalive as an alternative?

**Comment by filimonov** [comment]
Also lot of clients like jdbc / odbc get an base url as a connection conguration. If that base url will contain `multiquery` it will lead to unpredicable results.

**Comment by jcdang** [comment]
@alex-krash Agreed.  Garbage in, garbage out.

@filimonov The use case that I'm trying to handle is where there are ~350 of processing queries that need to be ran sequentially and I don't care about the output until the end.  At the end I would ideally make a separate request to get the output.  A keepalive session will not prevent the roundtrip latency.

These are roughly the numbers:
4s through multiquery clickhouse-client local machine
7s through http on the local machine
20s through http on a remote machine

If the JDBC/ODBC issue is a real concern, we could make it part of the header or post multipart post body.

**Comment by jcdang** [comment]
@filimonov Does this alleviate your connection configuration concern?

**Comment by kalexmills** [comment]
Seems like a beneficial improvement to the code base for handling batch requests more efficiently. What would maintainers need to see in order to accept this PR?

**Comment by filimonov** [comment]
Please check the discussion in the issue before merging.
Maybe some less attractive name for the flag / feature  should be chosen?

**Comment by MrBuddyCasino** [comment]
Could this be useful for migrations? CH executes them very fast, but the number of migrations is always growing, and avoiding many roundtrips might safe us time for executing integration tests.

**Comment by akuzm** [comment]
What I gather from a cursory read of the discussion is that this functionality is controversial and that we should work on #6294 first, and then reconsider.

@filimonov @jcdang is this OK with you?

**Comment by jcdang** [comment]
@akuzm We can close this issue.   The company I work for has decided to maintain a forked version of clickhouse.

**Pull request closed without merging**
