### PR TITLE
Fix PartialSortingTransform by expanding column to full

### PR DESCRIPTION
**Pull request by azat**
Changelog category (leave one):
- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix PartialSortingTransform by expanding column to full

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
@KochetovNicolai I thought PartialSortingTransform should leave const columns as is. Otherwise we will have performance degradation. Also look at MSan test.

**Comment by KochetovNicolai** [comment]
> PartialSortingTransform should leave const columns as is
It's true. The problem should have been in pipeline itself.

**Comment by KochetovNicolai** [comment]
Msan points to `DB::StringEqualsImpl<false>::string_vector_string_vector`. I think I've seen it before. Can't get the reason why it happened.

**Comment by qoega** [comment]
@KochetovNicolai have you tried to build with with `CXXFLAGS='-ggdb -fno-omit-frame-pointer -fsanitize-memory-track-origins=2'`?

**Comment by alexey-milovidov** [comment]
The issue was accidentially fixed in #8929

**Pull request closed without merging**
