### PR TITLE
to #34890_fix_input_format_null_as_default_bug

### LINKED ISSUE #34890: input_format_null_as_default does not work for DEFAULT expressions
```sql
CREATE TABLE t
(   a Float32 DEFAULT 100,
    b Float64 DEFAULT a
) ENGINE = Memory

SET input_format_null_as_default = 1;

INSERT INTO t(b) VALUES (null);
DB::Exception: Not found column a in block.
```

Though if a passed as null, it works
```sql
INSERT INTO t(a,b) VALUES (null,null);
OK

select * from t;
┌───a─┬───b─┐
│ 100 │ 100 │
└─────┴─────┘
```

### PR DESCRIPTION
**Pull request by zzsmdfj**
Changelog category (leave one):
- Bug Fix (user-visible misbehaviour in official stable or prestable release)

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
fix issue：input_format_null_as_default does not work for DEFAULT expressions 
 Closes  https://github.com/ClickHouse/ClickHouse/issues/34890

### CODE REVIEW

**Comment by zzsmdfj** [comment]
@mergify

**Comment by Avogar** [comment]
@Mergifyio update

**Review by Avogar — APPROVED** [review]

**Comment by zzsmdfj** [comment]
fixed failed test: 02205_ephemeral_1, can test be triggered again?

**Comment by Avogar** [comment]
@Mergifyio update

**Pull request merged**
