### PR TITLE
Update zlib-ng

### PR DESCRIPTION
**Pull request by alexey-milovidov**
Changelog category (leave one):
- Build/Testing/Packaging Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Update `zlib-ng` to the latest version. This is needed to run "clusterfuzz" (it is doing by Eldar Zaitov).

Note: accidentially made `rebase` instead of `merge` in submodule repository. Old versions would not find the old referenced commit and has to be updated also.

Upd: I have restored the old branch here: https://github.com/ClickHouse-Extras/zlib-ng/commits/develop-old

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
This library can be way better for level 1: http://www.libslz.org/

**Comment by alexey-milovidov** [comment]
Also worth looking to https://github.com/ebiggers/libdeflate.
It has incompatible with zlib interface, but it's actually better (allows to avoid useless memory copy into sliding window).

**Comment by azat** [comment]
@alexey-milovidov any progress on this one?
This is required for gcc10 build, due to incorrect `static_ltree` declaration:

```
ld.lld: error: duplicate symbol: static_ltree                                                                                            
>>> defined at trees.h:6 (../contrib/zlib-ng/trees.h:6)                                                                                  
>>>            trees.c.o:(static_ltree) in archive contrib/zlib-ng/libzlib.a                                                             
>>> defined at deflate_quick.c:168 (../contrib/zlib-ng/arch/x86/deflate_quick.c:168)                                                     
>>>            deflate_quick.c.o:(.rodata+0x0) in archive contrib/zlib-ng/libzlib.a                                                      
collect2: error: ld returned 1 exit status                                                                                               
ninja: build stopped: subcommand failed. 
```

**Comment by alexey-milovidov** [comment]
@azat No progress.
zlib-ng library is completely broken in level 1 (deflate_quick).

There was a bug that I had to fix manually: https://github.com/zlib-ng/zlib-ng/issues/494
The issue is closed but the bug appeared again and has to be debugged.

**Comment by alexey-milovidov** [comment]
Note that zlib and brotli has deficient interface that implies unnecessary data copying (into sliding window).
It's rather stupid to use "fast" zlib with that interface.

**Comment by azat** [comment]
>@azat No progress.
>zlib-ng library is completely broken in level 1 (deflate_quick).

Got it. Then how about the referenced temporary fix? https://github.com/ClickHouse-Extras/zlib-ng/pull/2 (and submodule will need to be updated)

**Comment by alexey-milovidov** [comment]
@azat We've implemented it here: #22359
The old bug in zlib-ng was fixed.

**Pull request closed without merging**
