### PR TITLE
Write parts with level 1 if `optimize_on_insert` is enabled

### LINKED ISSUE #72710: Create part with level 1 if `optimize_on_insert` is enabled
**Use case**

Use optimizations of merges and queries with `FINAL` that have an assumption that keys are unique in parts with levels >= 1 (e.g. `split_parts_ranges_into_intersecting_and_non_intersecting_final`).

**Describe the solution you'd like**

If `optimize_on_insert` is enabled write part with level 1 instead of 0 because it doesn't contain duplicates. Otherwise the work for optimizing data which is done on insert is kind of useless.

### PR DESCRIPTION
**Pull request by CurtizJ**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Write parts with level 1 if `optimize_on_insert` is enabled. It allows to use several optimizations of queries with `FINAL` for freshly written parts. 

Resolves #72710.

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Run only fuzzers related jobs (libFuzzer fuzzers, AST fuzzers, etc.)
- [ ]  Exclude: AST fuzzers
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-ch-test-poll** [comment]
*This is an automated comment for commit c5a546401dcc7251d9cc9ee30c0281a78d75d081 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/73132/c5a546401dcc7251d9cc9ee30c0281a78d75d081/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/df235c39a782e582c3fc8feec3c8239822e058c1/docs_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Comment by CurtizJ** [comment]
A bug with `SAMPLE` and `FINAL`: `Not found column intHash32(UserID)` (#72498).

**Review by Avogar — APPROVED** [review]

**Comment by CurtizJ** [comment]
Requires #73682.

**Comment by clickgapai** [comment]
Hi @CurtizJ @Avogar — while reviewing this PR I found the following:

- **Bug (P2):** ATTACH of a foreign level>0 duplicate-key part into a non-Ordinary MergeTree preserves the level, so FINAL silently returns duplicates — https://github.com/ClickHouse/ClickHouse/issues/109674

Happy to discuss — close anything that's wrong or already addressed.

**Pull request merged**
