### PR TITLE
Fix filtering parts with indexHint for non analyzer

### PR DESCRIPTION
**Pull request by azat**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix filtering parts with indexHint for non analyzer

Fixes: #54185 (cc @KochetovNicolai )

### CODE REVIEW

**Comment by robot-clickhouse-ci-1** [comment]
This is an automated comment for commit ce540c27f335de39ff0c69c3bf9184f03b029120 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/54449/ce540c27f335de39ff0c69c3bf9184f03b029120/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Comment by azat** [comment]
>Bugfix validate check — Changed tests don't reproduce the bug

- #54185 is not included into any release yet.

**Comment by azat** [comment]
Can  someone take a look at this please?

**Review by Avogar — APPROVED** [review]

**Comment by azat** [comment]
Oh, this is actually newly added tests from #54541

**Pull request merged**
