### PR TITLE
Fix debug assert when using grouping WITH ROLLUP and LowCardinality types 

### LINKED ISSUE #46335: Unknown column: if(equals(plus(...))) bug TPC-DS
**Describe what's wrong**

23.2

```sql
SELECT key_a + key_b as d, rank() OVER () as f FROM (SELECT rand() % 10 as key_a, rand(1) % 5 as key_b, number  FROM numbers(100)) GROUP BY rollup(key_a,key_b) ORDER BY  case when d = 0 then key_a end;

Code: 47. DB::Exception: Unknown column: if(equals(plus(key_a, key_b), 0), key_a, NULL), there are only columns __grouping_set, key_a, key_b, plus(key_a, key_b). (UNKNOWN_IDENTIFIER)

SELECT key_a + key_b as d, rank() OVER (PARTITION BY key_a + key_b) as f FROM (SELECT rand() % 10 as key_a, rand(1) % 5 as key_b, number  FROM numbers(100)) GROUP BY rollup(key_a,key_b) ORDER BY  case when d = 0 then key_a end;

Code: 47. DB::Exception: Unknown column: if(equals(plus(key_a, key_b), 0), key_a, NULL), there are only columns __grouping_set, key_a, key_b, plus(key_a, key_b). (UNKNOWN_IDENTIFIER)

 SELECT grouping(key_a) + grouping(key_b) as d, rank() OVER (PARTITION BY grouping(key_a) + grouping(key_b), case when grouping(key_b) = 0 then key_a end) as f FROM (SELECT rand() % 10 as key_a, rand(1) % 5 as key_b, number  FROM numbers(100)) GROUP BY rollup(key_a,key_b) ORDER BY  case when d = 0 then key_a end;

Received exception:
Code: 47. DB::Exception: Unknown column: if(equals(plus(grouping(key_a), grouping(key_b)), 0), key_a, NULL), there are only columns __grouping_set, key_a, key_b, grouping(key_a), grouping(key_b), plus(grouping(key_a), grouping(key_b)), 0, equals(grouping(key_b), 0), NULL, if(equals(grouping(key_b), 0), key_a, NULL). (UNKNOWN_IDENTIFIER)
```

**Does it reproduce on recent release?**

Yes, 23.2

**Expected behavior**

Query works

**Error message and/or stacktrace**

```sql
Received exception from server (version 23.2.1):
Code: 47. DB::Exception: Received from localhost:9000. DB::Exception: Unknown column: if(equals(plus(grouping(i_category), grouping(i_class)), 0), i_category, NULL), there are only columns __grouping_set, i_category, i_class, sum(ws_net_paid), grouping(i_category), grouping(i_class), plus(grouping(i_category), grouping(i_class)), 0, equals(grouping(i_class), 0), NULL, if(equals(grouping(i_class), 0), i_category, NULL). (UNKNOWN_IDENTIFIER)
(query: select   
    sum(ws_net_paid) as total_sum
   ,i_category
   ,i_class
   ,grouping(i_category)+grouping(i_class) as lochierarchy
   ,rank() over (
    partition by grouping(i_category)+grouping(i_class),
    case when grouping(i_class) = 0 then i_category end 
    order by sum(ws_net_paid) desc) as rank_within_parent
 from
    web_sales
   ,date_dim       d1
   ,item
 where
    d1.d_month_seq between 1212 and 1212+11
 and d1.d_date_sk = ws_sold_date_sk
 and i_item_sk  = ws_item_sk
 group by rollup(i_category,i_class)
 order by
   lochierarchy desc,
   case when lochierarchy = 0 then i_category end,
   rank_within_parent
 LIMIT 100;)
```

### LINKED ISSUE #62953: [Analyzer] Logical error: 'Function xxHash64(groupingForGroupingSets(__grouping_set, __table1.id), _CAST(1048577, 'Nullable(UInt32)')) expects 1 argument to have LowCardinality(UInt64) type but receives UInt64 after running GroupingFunctionsResolvePass pass'.
There is no stacktrace unfortunately 

https://s3.amazonaws.com/clickhouse-test-reports/62925/7530dd57f112c58a626a5fa653340c7aea34ec94/ast_fuzzer__msan_.html

### PR DESCRIPTION
**Pull request by Algunenano**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
- Fix debug assert when using grouping WITH ROLLUP and LowCardinality types

### Documentation entry for user-facing changes

Closes #46335
Closes https://github.com/ClickHouse/ClickHouse/issues/62953

### CODE REVIEW

**Comment by robot-ch-test-poll4** [comment]
*This is an automated comment for commit f15ee477ebb6fe030e0581b2f8b31b289f816f52 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/63398/f15ee477ebb6fe030e0581b2f8b31b289f816f52/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

**Comment by nikitamikhaylov** [comment]
`03146_tcp_ds_grouping.sql` -> `03146_`**tpc**`_ds_grouping.sql` ?

**Review by nikitamikhaylov — APPROVED** [review]

**Comment by Algunenano** [comment]
The fuzzer is detecting problems:
```
SELECT grouping(key_a) + grouping(key_b) AS d
FROM
(
    SELECT
        rand() % 10 AS key_a,
        rand(toLowCardinality(1)) % 5 AS key_b,
        number
    FROM numbers(100)
)
GROUP BY
    key_a,
    key_b
    WITH ROLLUP
```

```
Logical error: 'Function groupingForRollup(__grouping_set, __table1.key_a) + groupingForRollup(__grouping_set, __table1.key_b) expects 2 argument to have LowCardinality(UInt64) type but receives UInt64 after running GroupingFunctionsResolvePass pass'.	
```

**Comment by Algunenano** [comment]
Changing the PR to a bugfix to address the issue detected by the fuzzer and also close https://github.com/ClickHouse/ClickHouse/issues/62953

Basically the problem is that we change `grouping(key)` into `groupingForRollup(key, __grouping_set)` and when the key is a low cardinality column, this means changing the result from LC to not LC (because the second column is not LC). Initially I fixed it by adding a cast, but returning LC from `grouping` doesn't make sense to begin with, so I'm going to change it there instead.

**Review by novikd — APPROVED** [review]

**Review by nikitamikhaylov — APPROVED** [review]

**Pull request merged**
