### PR TITLE
Fix toHour-like conversion functions' monotonicity when optional time zone argument is passed

### LINKED ISSUE #59992: Request WHERE toHour(stamp, 'America/NewYork')  is not consistent with the result of toHour(stamp)
Hello guys,

Using CH (23.9.2.56)

I have a really weird behavior on my ReplicatedMergeTree table (requested through a distributed table).
So I have a table like Table (stamp DateTime('UTC'), clicks UInt64),
And when I :
```
SELECT toHour(stamp, 'America/New_York'), sum(clicks)
FROM mytable
WHERE toDate(stamp, 'America/New_York') = '2024-02-01'
GROUP BY ALL;
```
I get something like (the numbers are made up, but it is a huge traffic table)

|  stamp(America/NewYork) | clicks  |
|---|---|
|  0 |  34   |
|  1 |   45  |
|  2 |  60  |
|  ... |   ... |
|  7 |   207 |
|  8 |   213 |

At 7AM (NY time) for example I get : sum(clicks) => 207.

But when I do a more precise request like just adding  AND toHour(stamp, 'America/NewYork') = 7:
```
SELECT toHour(stamp, 'America/New_York'), sum(clicks)
FROM mytable
WHERE toDate(stamp, 'America/New_York') = '2024-02-01'
AND toHour(stamp, 'America/New_York') = 7 
GROUP BY ALL;
```

I Have a different result like sum(clicks) => 93 :

|  stamp(America/NewYork) | clicks  |
|---|---|
|  7 |  93   |

But If I remove the 'America/New_York' and do the request in UTC time (7AM = 12 PM) the result stay consistent.

```
SELECT toHour(stamp, 'America/New_York'), sum(clicks)
FROM mytable
WHERE toDate(stamp, 'America/New_York') = '2024-02-01'
AND toHour(stamp) = 12 
GROUP BY ALL;
```

**How to reproduce**

Using Using CH (23.9.2.56)

- CREATE TABLE db.table_local ON CLUSTER '{cluster}'
(
    `stamp` DateTime('UTC'),
    ..... a lot of others column ....
    `clicks` UInt64 
)
ENGINE = ReplicatedMergeTree
PARTITION BY toDate(stamp)

-  CREATE TABLE db.table_local ON CLUSTER '{cluster}'
(
    `stamp` DateTime('UTC'),
    ..... a lot of others column ....
    `clicks` UInt64 
)
ENGINE = Distributed('db', 'db', 'table', rand())

- send a lot of request (some millions)
- then request playing on the where with the toHour function

**Expected behavior**

The data should be consistent using toHour(stamp, 'someplace') and without the someplace

### PR DESCRIPTION
**Pull request by amosbird**
Fixes #59992

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix toHour-like conversion functions' monotonicity when optional time zone argument is passed.

### CODE REVIEW

**Comment by robot-ch-test-poll** [comment]
*This is an automated comment for commit 1df0613156c79d7a1f4b5a87f65d0ff5c9f0a9e9 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/60264/1df0613156c79d7a1f4b5a87f65d0ff5c9f0a9e9/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/60264/1df0613156c79d7a1f4b5a87f65d0ff5c9f0a9e9/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Comment by alexey-milovidov** [comment]
@amosbird 

Do you know, why

> New test(s) failed to reproduce a bug

**Comment by amosbird** [comment]
No idea. Let's see if rebase helps.

**Comment by alexey-milovidov** [comment]
Requires https://github.com/ClickHouse/ClickHouse/pull/66460

**Comment by alexey-milovidov** [comment]
@amosbird could you please merge with the master branch as the fix https://github.com/ClickHouse/ClickHouse/pull/66460 was merged?

**Comment by alexey-milovidov** [comment]
Builds didn't finish, and we need to fix it first.

**Comment by amosbird** [comment]
It seems working.

**Review by alexey-milovidov — APPROVED** [review]

**Comment by clickgapai** [comment]
Hi @amosbird @alexey-milovidov — while reviewing this PR I found the following:

- **Coverage gap:** `FunctionWithOptionalConstArg::getMonotonicityForRange` DateTime64-with-timezone branch in `KeyCondition.cpp` is untested — https://github.com/ClickHouse/ClickHouse/pull/103883

Could you review the test PR and add the `can be tested` label if it looks good?
Happy to discuss — close anything that's wrong or already addressed.

**Pull request merged**
