### PR TITLE
fix_JSON_searchField

### PR DESCRIPTION
**Pull request by aletik-ru**
### Changelog category (leave one):
- Not for changelog

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Added field name length check. Fixes the wrong behaviour when the search field is the first part of the existing field name.

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by qoega** [comment]
Can you add a test with case that worked incorrectly?

**Comment by aletik256** [comment]
> Can you add a test with case that worked incorrectly?

Yes, I can. Where is the best place for adding the test?

**Comment by arthurpassos** [comment]
> > Can you add a test with case that worked incorrectly?
> 
> Yes, I can. Where is the best place for adding the test?

Is this a bug you can observe on user visible APIs (e.g [JSON functions](https://clickhouse.com/docs/en/sql-reference/functions/json-functions/)). If so, I would suggest adding stateless tests. All you need is a `.sql` file and a `.reference` file. Check: https://clickhouse.com/docs/en/development/tests/#adding-a-new-test

**Comment by CheSema** [comment]
The code definitely has a bug, it is obvious. Such bug is hard to find, thank a lot!

However I have checked the behaviour of function here https://clickhouse.com/docs/en/sql-reference/functions/json-functions. I'm unable to trigger the bug. According to the code those functions use different realisation.

That class (base/base/JSON.h) is not used in json format data in sql or user tables. As I see it is a class with some internal use cases. CH uses it when parse responses from other systems in json format. And that seemed dangerous too, for sure.

So the test in that case would be a different one. Here unit-tests are useful: https://clickhouse.com/docs/en/development/tests#unit-tests.

As soon as there is no way to trigger bug by user, please, change the category in description. It is still a bug, but it is not "user-visible misbehavior". If I'm wrong, please provide some information in any form, I will help you to arrange a proper test.

**Review by CheSema — APPROVED** [review]

**Comment by aletik256** [comment]
> The code definitely has a bug, it is obvious. Such bug is hard to find, thank a lot!
> 
> However I have checked the behaviour of those functions: https://clickhouse.com/docs/en/sql-reference/functions/json-functions. I'm unable to trigger the bug. According to the code those functions use different realisation.
> 
> That class (base/base/JSON.h) is not used in json format data in sql or user tables. As I see it is a class with some internal use cases. CH uses it when parse responses from other systems in json format. And that seemed dangerous too, for sure.
> 
> So the test in that case would be a different one. Here unit-tests are useful: https://clickhouse.com/docs/en/development/tests#unit-tests.
> 
> As soon as there is no way to trigger bug by user, please, change the category in description. It is still a bug, but it is not "user-visible misbehavior". If I'm wrong, please provide some information in any form, I will help you to arrange a proper test.

I've changed the category.

**Review by CheSema — APPROVED** [review]

**Pull request merged**
