### PR TITLE
Return and fix 01600_parts_states_metrics_long test

### PR DESCRIPTION
**Pull request by yakov-olkhovskiy**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Returning 01600_parts_states_metrics_long test with fix.
The essence of failure of this test was delayed delete of parts of dropped tables. The cure is to account parts of dropped but not yet deleted tables using `system.dropped_tables_parts` table introduced by #58038

### CODE REVIEW

**Comment by robot-ch-test-poll1** [comment]
*This is an automated comment for commit 93c362a803ff924f4176f6cd8483c08d731ccb59 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/58748/93c362a803ff924f4176f6cd8483c08d731ccb59/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/58748/93c362a803ff924f4176f6cd8483c08d731ccb59/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Review by hanfei1991 — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
Failed with analyzer.

**Comment by yakov-olkhovskiy** [comment]
yes, I see, trying to figure it out... maybe it's beyond repair after all - it's highly dependent on other tests running on the same server...

**Comment by alexey-milovidov** [comment]
It's ok to drop it.

**Comment by yakov-olkhovskiy** [comment]
I talked to @KochetovNicolai regarding this issue - it's probable that this tests fails because we have issue with other hanging test in analyzer. So let's wait we fix all issues with analyzer and probably then revive this test. For now I'm moving it to WIP.

**Review by alexey-milovidov — APPROVED** [review]

**Pull request merged**
