### PR TITLE
[docs/faq] Does ClickHouse support multi-region replication?

### PR DESCRIPTION
**Pull request by blinkov**
Changelog category (leave one):

- Documentation (changelog entry is not required)

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
> Collecting lunr[languages]==0.5.8
  Downloading lunr-0.5.8-py2.py3-none-any.whl (2.3 MB)

We don't use Lunr anymore.

**Comment by alexey-milovidov** [comment]
> WARNING:mkdocs.structure.pages:Documentation file 'faq/operations/index.md' contains a link to 'faq/operations/multi-region-replication.md' which is not found in the documentation files.
WARNING:mkdocs.structure.pages:Documentation file 'faq/operations/index.md' contains a link to 'faq/operations/multi-region-replication.md' which is not found in the documentation files.

**Comment by blinkov** [comment]
> We don't use Lunr anymore.
IIRC it's a mandatory dependency of the main library that builds docs (mkdocs).

> WARNING:mkdocs.structure.pages:Documentation file 'faq/operations/index.md' contains a link to 'faq/operations/multi-region-replication.md' which is not found in the documentation files.
> WARNING:mkdocs.structure.pages:Documentation file 'faq/operations/index.md' contains a link to 'faq/operations/multi-region-replication.md' which is not found in the documentation files.
I've just pushed lost symlinks, which will probably help.

**Comment by alexey-milovidov** [comment]
Strange, it did not help.

**Comment by blinkov** [comment]
yeah, did that in a hurry and hasn't double-checked, a second attempt pushed

**Pull request merged**
