### PR TITLE
Fix limit and offset settings for secondary queries.

### LINKED ISSUE #58918: `system.settings` values for `limit` and `offset` are incorrect with the analyzer
On the latest master version, when using the experimental analyzer, `limit` changes are not reflected in the `system.settings` table. 

Additionally, `offset` is marked as `changed`, while we were not explicitly modifying it via `SET`.

```
SET allow_experimental_analyzer = 1
SET limit = 100

SELECT
    name,
    value
FROM system.settings
WHERE changed

┌─name────────────────────────────┬─value──┐
│ allow_experimental_analyzer     │ 1      │
│ limit                           │ 0      │
│ offset                          │ 0      │
└─────────────────────────────────┴────────┘
```

Default behavior:

```
SET limit = 100

SELECT
    name,
    value
FROM system.settings
WHERE changed

┌─name───────────────────────────┬─value──┐
│ limit                          │ 100    │
└────────────────────────────────┴────────┘
```

### PR DESCRIPTION
**Pull request by yakov-olkhovskiy**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix - for all secondary queries limit and offset should be reset in context. Table system.setting should take values from query context.

closes #58918

### CODE REVIEW

**Comment by robot-ch-test-poll2** [comment]
*This is an automated comment for commit 39147922c9b23c412f85dab737e20b9283689c11 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/59018/39147922c9b23c412f85dab737e20b9283689c11/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/59018/39147922c9b23c412f85dab737e20b9283689c11/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Comment by alexey-milovidov** [comment]
@yakov-olkhovskiy It is intended to work this way. You can change it, but it should be labeled as a backward incompatible change and we should add a compatibility setting.

**Review by alexey-milovidov — CHANGES_REQUESTED** [review]
Test needed.

**Comment by yakov-olkhovskiy** [comment]
@alexey-milovidov yes, I already somehow investigated this - the test which is failing seems to indicate that it was intended at least at some point, but I find it inconsistent - we have context itself, then query context, session context and global context within - I don't exactly understand what the difference then and the usage seems inconsistent - I want to discuss it with the team to decide how we want it...

**Comment by alexey-milovidov** [comment]
Yes, I also checked... the reason I tell is because I remember how, and why I've added this table :)

So, when it was developed, the intent was to show the settings effective for this particular query from `system.settings`.
The motivation is - these are the most "deep" settings, that we can get. They include the most overrides possible, so it is like the most information that we can show.

Then I checked the docs, and it stated that it shows session-level settings, which is surprising. Maybe it was lost when the docs were written.

I don't mind changing this behavior, so your change is good for me.
But what is the problem with Analyzer?

**Comment by yakov-olkhovskiy** [comment]
In analyzer we calculate effective limit and offset as a query expression and put it into query tree, and remove from setting to prevent further interference:
https://github.com/ClickHouse/ClickHouse/blob/master/src/Analyzer/QueryTreeBuilder.cpp#L247-L249

Of course this problem can be addressed differently - instead removing from settings I can find further interference and prevent it... I think it's a better approach than changing meaning of system.settings. Will do this.

**Comment by alexey-milovidov** [comment]
A test has failed.

**Pull request closed without merging**
