### PR TITLE
It looks like GitHub have improved the code owners feature

### PR DESCRIPTION
**Pull request by blinkov**
Changelog category (leave one):
- Non-significant (changelog entry is not required)

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]
Ok if all of the following conditions are met:
- it will not assign people randomly;
- it will not prevent merging PRs without review.

**Comment by blinkov** [comment]
Well, it's supposed to "load balance" reviews across the team.

**Comment by alexey-milovidov** [comment]
You have already tried it with "pull request assigner" bot, that was proven to be harmful and was removed.

**Comment by alexey-milovidov** [comment]
It was assigning issues for random people. Assignees get unnoticed or decided to not disrupt from their tasks while other developers just skipped the PR as it's already assigned. Then after a months, pull request becomes abandoned.

**Pull request closed without merging**
