### PR TITLE
Keep config in context to avoid Application singleton usages

### PR DESCRIPTION
**Pull request by vadimskipin**
In a hosted scenario I have no Application instance available.
So I would like to rework code to use Context::getConfigRef() instead of Application::instance()::config()
Also I have found that isLocalAddress function uses tcp_port setting - it looks strange to me.

### CODE REVIEW

**Comment by robot-metrika-test** [comment]
Can one of the admins verify this patch?

**Comment by robot-metrika-test** [comment]
Can one of the admins verify this patch?

**Comment by alexey-milovidov** [comment]
You can have many clickhouse-servers on the same host, that listen to different ports.
And the address with different port is not local - if you send a query to that address, the query will be received by another instance of clickhouse-server.

**Review by alexey-milovidov — CHANGES_REQUESTED** [review]
.

**Comment by alexey-milovidov** [comment]
You should also use `getConfigRef` in all places, where configuration is used and `Context` is available.

**Pull request merged**
