### PR TITLE
Adding system warnings 26039

### LINKED ISSUE #26039: `system.warnings` table and warnings in `clickhouse-client`
The server should have a shared array of warning messages.
You can put it simply as `std::vector<std::string>` in `ContextShared`.

There should be a method to add a new warning.
This method will print a log message and also add the warning to the list.
Warnings are not persisted (the list is empty on server startup and will be filled at runtime).

A system table `system.warnings` should be created. Reading from this table will return all the warnings.
(See `IStorageSystemOneBlock` and its usages). The table structure is one column `message String`.

When `clickhouse-client` is connected to the server in interactive mode, it should do `SELECT message FROM system.warnings` (simple synchronous query) and if there are warnings, print them in form of `Warning: message...` each on separate line. If the table does not exist on server or if query cannot execute by another reason, catch exception and ignore it.

It will be used for #18794
Example: if server was build in debug mode, print a warning about it in client.

PS. Not every log message with warning level goes to `system.warnings`. The `system.warnings` is only for special kinds of warnings that we are going to collect.

### PR DESCRIPTION
**Pull request by FArthur-cmd**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category:
- Improvement

Changelog entry:
- Add `system.warnings` table to collect warnings about server configuration.

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]
Ok but comments are not descriptive enough. I will add comments.

**Comment by alexey-milovidov** [comment]
You've missed the task about displaying warnings in `clickhouse-client`.

**Comment by alexey-milovidov** [comment]
29e8b783ba

**Comment by nikitamikhaylov** [comment]
Arcadia is broken, I will fix.

**Pull request merged**
