### PR TITLE
Persistent coordination log storage

### PR DESCRIPTION
**Pull request by alesapin**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Just the most straightforward way.

### CODE REVIEW

**Comment by alesapin** [comment]
No reconnects, no errors with ZK... why fasttest fails https://gist.github.com/alesapin/6293fdb422961968c530cc34e8a9d926?

**Comment by alesapin** [comment]
Seems like https://github.com/ClickHouse/ClickHouse/pull/20627 is the reason.

**Comment by alesapin** [comment]
Ok, seems like disks in CI slightly slower than on my machine.

**Comment by alesapin** [comment]
```
2021-02-18 17:26:57 00992_system_parts_race_condition_zookeeper:                            [ FAIL ] 11.28 sec. - having stderror:
2021-02-18 17:26:57 [96825df77e83] 2021.02.18 17:26:57.042652 [ 113751 ] {1464e8b1-93ac-44b7-8a31-fcce5e5a34e4} <Error> zkutil::EphemeralNodeHolder::~EphemeralNodeHolder(): Cannot remove /clickhouse/tables/default.alter_table/replicas/r1/is_active: : Code: 999, e.displayText() = Coordination::Exception: Connection loss, path: /clickhouse/tables/default.alter_table/replicas/r1/is_active, Stack trace (when copying this message, always include the lines below):
2021-02-18 17:26:57 
2021-02-18 17:26:57 0. Coordination::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Coordination::Error, int) @ 0xfb21ad3 in /usr/lib/debug/.build-id/97/de40b1b3d03b1f66f6688519c3df227079bdf8.debug
2021-02-18 17:26:57 1. Coordination::Exception::Exception(Coordination::Error, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0xfb2212e in /usr/lib/debug/.build-id/97/de40b1b3d03b1f66f6688519c3df227079bdf8.debug
2021-02-18 17:26:57 2. zkutil::EphemeralNodeHolder::~EphemeralNodeHolder() @ 0x8742b97 in /usr/lib/debug/.build-id/97/de40b1b3d03b1f66f6688519c3df227079bdf8.debug
2021-02-18 17:26:57 3. DB::ReplicatedMergeTreeRestartingThread::partialShutdown() @ 0xf6ee421 in /usr/lib/debug/.build-id/97/de40b1b3d03b1f66f6688519c3df227079bdf8.debug
2021-02-18 17:26:57 4. DB::ReplicatedMergeTreeRestartingThread::shutdown() @ 0xf6f28fa in /usr/lib/debug/.build-id/97/de40b1b3d03b1f66f6688519c3df227079bdf8.debug
2021-02-18 17:26:57 5. DB::StorageReplicatedMergeTree::shutdown() @ 0xf3400de in /usr/lib/debug/.build-id/97/de40b1b3d03b1f66f6688519c3df227079bdf8.debug
2021-02-18 17:26:57 6. DB::InterpreterDropQuery::executeToTableImpl(DB::ASTDropQuery const&, std::__1::shared_ptr<DB::IDatabase>&, StrongTypedef<DB::UInt128, DB::UUIDTag>&) @ 0xed2a30e in /usr/lib/debug/.build-id/97/de40b1b3d03b1f66f6688519c3df227079bdf8.debug
2021-02-18 17:26:57 7. DB::InterpreterDropQuery::executeToTable(DB::ASTDropQuery const&) @ 0xed28e46 in /usr/lib/debug/.build-id/97/de40b1b3d03b1f66f6688519c3df227079bdf8.debug
2021-02-18 17:26:57 8. DB::InterpreterDropQuery::execute() @ 0xed28949 in /usr/lib/debug/.build-id/97/de40b1b3d03b1f66f6688519c3df227079bdf8.debug
2021-02-18 17:26:57 9. DB::executeQueryImpl(char const*, char const*, DB::Context&, bool, DB::QueryProcessingStage::Enum, bool, DB::ReadBuffer*) @ 0xf0b1e7d in /usr/lib/debug/.build-id/97/de40b1b3d03b1f66f6688519c3df227079bdf8.debug
2021-02-18 17:26:57 10. DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::Context&, bool, DB::QueryProcessingStage::Enum, bool) @ 0xf0b07b3 in /usr/lib/debug/.build-id/97/de40b1b3d03b1f66f6688519c3df227079bdf8.debug
2021-02-18 17:26:57 11. DB::TCPHandler::runImpl() @ 0xf7fca3d in /usr/lib/debug/.build-id/97/de40b1b3d03b1f66f6688519c3df227079bdf8.debug
2021-02-18 17:26:57 12. DB::TCPHandler::run() @ 0xf80edf9 in /usr/lib/debug/.build-id/97/de40b1b3d03b1f66f6688519c3df227079bdf8.debug
2021-02-18 17:26:57 13. Poco::Net::TCPServerConnection::start() @ 0x11eb5fff in /usr/lib/debug/.build-id/97/de40b1b3d03b1f66f6688519c3df227079bdf8.debug
2021-02-18 17:26:57 14. Poco::Net::TCPServerDispatcher::run() @ 0x11eb7a11 in /usr/lib/debug/.build-id/97/de40b1b3d03b1f66f6688519c3df227079bdf8.debug
2021-02-18 17:26:57 15. Poco::PooledThread::run() @ 0x11feed79 in /usr/lib/debug/.build-id/97/de40b1b3d03b1f66f6688519c3df227079bdf8.debug
2021-02-18 17:26:57 16. Poco::ThreadImpl::runnableEntry(void*) @ 0x11feabda in /usr/lib/debug/.build-id/97/de40b1b3d03b1f66f6688519c3df227079bdf8.debug
2021-02-18 17:26:57 17. start_thread @ 0x9609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
2021-02-18 17:26:57 18. __clone @ 0x122293 in /usr/lib/x86_64-linux-gnu/libc-2.31.so
2021-02-18 17:26:57  (version 21.3.1.6057)
2021-02-18 17:26:57 [96825df77e83] 2021.02.18 17:26:57.043550 [ 113751 ] {1464e8b1-93ac-44b7-8a31-fcce5e5a34e4} <Error> zkutil::EphemeralNodeHolder::~EphemeralNodeHolder(): Cannot remove /clickhouse/tables/default.alter_table/leader_election/leader_election-0000000000: : Code: 999, e.displayText() = Coordination::Exception: Session expired (Session expired), Stack trace (when copying this message, always include the lines below):
2021-02-18 17:26:57 
2021-02-18 17:26:57 0. Coordination::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Coordination::Error, int) @ 0xfb21ad3 in /usr/lib/debug/.build-id/97/de40b1b3d03b1f66f6688519c3df227079bdf8.debug
2021-02-18 17:26:57 1. Coordination::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Coordination::Error) @ 0xfb21d52 in /usr/lib/debug/.build-id/97/de40b1b3d03b1f66f6688519c3df227079bdf8.debug
2021-02-18 17:26:57 2. Coordination::ZooKeeper::pushRequest(Coordination::ZooKeeper::RequestInfo&&) @ 0xfb66743 in /usr/lib/debug/.build-id/97/de40b1b3d03b1f66f6688519c3df227079bdf8.debug
2021-02-18 17:26:57 3. Coordination::ZooKeeper::remove(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, std::__1::function<void (Coordination::RemoveResponse const&)>) @ 0xfb673c9 in /usr/lib/debug/.build-id/97/de40b1b3d03b1f66f6688519c3df227079bdf8.debug
2021-02-18 17:26:57 4. zkutil::ZooKeeper::removeImpl(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0xfb289c6 in /usr/lib/debug/.build-id/97/de40b1b3d03b1f66f6688519c3df227079bdf8.debug
2021-02-18 17:26:57 5. zkutil::EphemeralNodeHolder::~EphemeralNodeHolder() @ 0x8742b2d in /usr/lib/debug/.build-id/97/de40b1b3d03b1f66f6688519c3df227079bdf8.debug
2021-02-18 17:26:57 6. zkutil::LeaderElection::~LeaderElection() @ 0xf3bb734 in /usr/lib/debug/.build-id/97/de40b1b3d03b1f66f6688519c3df227079bdf8.debug
2021-02-18 17:26:57 7. DB::StorageReplicatedMergeTree::exitLeaderElection() @ 0xf379849 in /usr/lib/debug/.build-id/97/de40b1b3d03b1f66f6688519c3df227079bdf8.debug
2021-02-18 17:26:57 8. DB::ReplicatedMergeTreeRestartingThread::partialShutdown() @ 0xf6ee796 in /usr/lib/debug/.build-id/97/de40b1b3d03b1f66f6688519c3df227079bdf8.debug
2021-02-18 17:26:57 9. DB::ReplicatedMergeTreeRestartingThread::shutdown() @ 0xf6f28fa in /usr/lib/debug/.build-id/97/de40b1b3d03b1f66f6688519c3df227079bdf8.debug
2021-02-18 17:26:57 10. DB::StorageReplicatedMergeTree::shutdown() @ 0xf3400de in /usr/lib/debug/.build-id/97/de40b1b3d03b1f66f6688519c3df227079bdf8.debug
2021-02-18 17:26:57 11. DB::InterpreterDropQuery::executeToTableImpl(DB::ASTDropQuery const&, std::__1::shared_ptr<DB::IDatabase>&, StrongTypedef<DB::UInt128, DB::UUIDTag>&) @ 0xed2a30e in /usr/lib/debug/.build-id/97/de40b1b3d03b1f66f6688519c3df227079bdf8.debug
2021-02-18 17:26:57 12. DB::InterpreterDropQuery::executeToTable(DB::ASTDropQuery const&) @ 0xed28e46 in /usr/lib/debug/.build-id/97/de40b1b3d03b1f66f6688519c3df227079bdf8.debug
2021-02-18 17:26:57 13. DB::InterpreterDropQuery::execute() @ 0xed28949 in /usr/lib/debug/.build-id/97/de40b1b3d03b1f66f6688519c3df227079bdf8.debug
2021-02-18 17:26:57 14. DB::executeQueryImpl(char const*, char const*, DB::Context&, bool, DB::QueryProcessingStage::Enum, bool, DB::ReadBuffer*) @ 0xf0b1e7d in /usr/lib/debug/.build-id/97/de40b1b3d03b1f66f6688519c3df227079bdf8.debug
2021-02-18 17:26:57 15. DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::Context&, bool, DB::QueryProcessingStage::Enum, bool) @ 0xf0b07b3 in /usr/lib/debug/.build-id/97/de40b1b3d03b1f66f6688519c3df227079bdf8.debug
2021-02-18 17:26:57 16. DB::TCPHandler::runImpl() @ 0xf7fca3d in /usr/lib/debug/.build-id/97/de40b1b3d03b1f66f6688519c3df227079bdf8.debug
2021-02-18 17:26:57 17. DB::TCPHandler::run() @ 0xf80edf9 in /usr/lib/debug/.build-id/97/de40b1b3d03b1f66f6688519c3df227079bdf8.debug
2021-02-18 17:26:57 18. Poco::Net::TCPServerConnection::start() @ 0x11eb5fff in /usr/lib/debug/.build-id/97/de40b1b3d03b1f66f6688519c3df227079bdf8.debug
2021-02-18 17:26:57 19. Poco::Net::TCPServerDispatcher::run() @ 0x11eb7a11 in /usr/lib/debug/.build-id/97/de40b1b3d03b1f66f6688519c3df227079bdf8.debug
2021-02-18 17:26:57 20. Poco::PooledThread::run() @ 0x11feed79 in /usr/lib/debug/.build-id/97/de40b1b3d03b1f66f6688519c3df227079bdf8.debug
2021-02-18 17:26:57 21. Poco::ThreadImpl::runnableEntry(void*) @ 0x11feabda in /usr/lib/debug/.build-id/97/de40b1b3d03b1f66f6688519c3df227079bdf8.debug
2021-02-18 17:26:57 22. start_thread @ 0x9609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
2021-02-18 17:26:57 23. __clone @ 0x122293 in /usr/lib/x86_64-linux-gnu/libc-2.31.so
2021-02-18 17:26:57  (version 21.3.1.6057)
```
too slow.

**Comment by alesapin** [comment]
Reproduced on network HDD.

**Comment by alesapin** [comment]
```
        node2.query("INSERT INTO ordinary.t1 SELECT number FROM numbers(10)")
    
        node1.query("SYSTEM SYNC REPLICA ordinary.t1", timeout=10)
        node3.query("SYSTEM SYNC REPLICA ordinary.t1", timeout=10)
    
>       assert node1.query("SELECT COUNT() FROM ordinary.t1") == "10\n"
E       AssertionError: assert '0\n' == '10\n'
E         - 10
E         ? -
E         + 0

```
???

**Comment by alesapin** [comment]
```
2021.02.19 01:53:32.947332 [ 15 ] {12b069f3-4315-439c-8135-86ca0aba55da} <Debug> executeQuery: (from 172.19.0.1:33412, using production parser) SYSTEM SYNC REPLICA ordinary.t1
2021.02.19 01:53:32.947690 [ 15 ] {12b069f3-4315-439c-8135-86ca0aba55da} <Trace> ContextAccess (default): Access granted: SYSTEM SYNC REPLICA ON ordinary.t1
2021.02.19 01:53:32.947751 [ 15 ] {12b069f3-4315-439c-8135-86ca0aba55da} <Trace> InterpreterSystemQuery: Synchronizing entries in replica's queue with table's log and waiting for it to become empty
2021.02.19 01:53:32.949691 [ 15 ] {12b069f3-4315-439c-8135-86ca0aba55da} <Trace> InterpreterSystemQuery: SYNC REPLICA ordinary.t1: OK
2021.02.19 01:53:32.950022 [ 15 ] {12b069f3-4315-439c-8135-86ca0aba55da} <Debug> MemoryTracker: Peak memory usage (for query): 0.00 B.

2021.02.19 01:53:33.722337 [ 66 ] {} <Debug> ordinary.t1 (ReplicatedMergeTreeQueue): Pulled 1 entries to queue.
2021.02.19 01:53:33.722462 [ 66 ] {} <Trace> ordinary.t1 (StorageReplicatedMergeTree::queueUpdatingTask): Execution took 574 ms.
2021.02.19 01:53:33.724126 [ 99 ] {} <Debug> ordinary.t1: Fetching part all_0_0_0 from /clickhouse/t1/replicas/2
2021.02.19 01:53:33.725220 [ 99 ] {} <Trace> ReadWriteBufferFromHTTP: Sending request to http://node2:9009/?endpoint=DataPartsExchange%3A%2Fclickhouse%2Ft1%2Freplicas%2F2&part=all_0_0_0&client_protocol_version=5&compress=false
2021.02.19 01:53:33.728150 [ 99 ] {} <Debug> DiskLocal: Reserving 1.00 MiB on disk `default`, having unreserved 1.26 TiB.
2021.02.19 01:53:33.730410 [ 99 ] {} <Trace> ordinary.t1: Renaming temporary part tmp_fetch_all_0_0_0 to all_0_0_0.

2021.02.19 01:53:33.807765 [ 15 ] {} <Debug> TCPHandler: Connected ClickHouse client version 21.3.0, revision: 54447, user: default.
2021.02.19 01:53:33.817888 [ 15 ] {51863343-387b-4089-b247-cfa7c7d99a28} <Debug> executeQuery: (from 172.19.0.1:33424, using production parser) SELECT COUNT() FROM ordinary.t1
2021.02.19 01:53:33.819034 [ 15 ] {51863343-387b-4089-b247-cfa7c7d99a28} <Trace> ContextAccess (default): Access granted: SELECT(value) ON ordinary.t1
2021.02.19 01:53:33.819245 [ 15 ] {51863343-387b-4089-b247-cfa7c7d99a28} <Trace> InterpreterSelectQuery: WithMergeableState -> Complete
2021.02.19 01:53:33.820840 [ 98 ] {51863343-387b-4089-b247-cfa7c7d99a28} <Trace> MergingAggregatedTransform: Reading blocks of partially aggregated data.
2021.02.19 01:53:33.820949 [ 98 ] {51863343-387b-4089-b247-cfa7c7d99a28} <Trace> MergingAggregatedTransform: Read 1 blocks of partially aggregated data, total 1 rows.
2021.02.19 01:53:33.821031 [ 98 ] {51863343-387b-4089-b247-cfa7c7d99a28} <Trace> Aggregator: Merging partially aggregated single-level data.
2021.02.19 01:53:33.821074 [ 98 ] {51863343-387b-4089-b247-cfa7c7d99a28} <Trace> Aggregator: Merged partially aggregated single-level data.
2021.02.19 01:53:33.821106 [ 98 ] {51863343-387b-4089-b247-cfa7c7d99a28} <Trace> Aggregator: Converting aggregated data to blocks
2021.02.19 01:53:33.821226 [ 98 ] {51863343-387b-4089-b247-cfa7c7d99a28} <Trace> Aggregator: Converted aggregated data to blocks. 1 rows, 8.00 B in 6.2915e-05 sec. (15894.460780418023 rows/sec., 124.18 KiB/sec.)
2021.02.19 01:53:33.821811 [ 15 ] {51863343-387b-4089-b247-cfa7c7d99a28} <Information> executeQuery: Read 1 rows, 4.01 KiB in 0.003801457 sec., 263 rows/sec., 1.03 MiB/sec.
2021.02.19 01:53:33.821908 [ 15 ] {51863343-387b-4089-b247-cfa7c7d99a28} <Debug> MemoryTracker: Peak memory usage (for query): 0.00 B.
2021.02.19 01:53:33.822274 [ 15 ] {} <Debug> TCPHandler: Processed in 0.005285772 sec.
2021.02.19 01:53:33.823486 [ 15 ] {} <Debug> TCPHandler: Done processing connection.

2021.02.19 01:53:33.875001 [ 99 ] {} <Debug> ordinary.t1: Fetched part all_0_0_0 from /clickhouse/t1/replicas/2
```

**Comment by alesapin** [comment]
Actually, timeouts caused by the bad implementation of NuKeeperTCPHandler.

**Comment by alesapin** [comment]
Tests look OK, but for sure I'll make several runs (and cleanup code a little bit).

**Comment by alesapin** [comment]
For some reason, it takes more than a minute to start from the log with 854461 entries.... A similar amount of records on my machine takes about 10-20 seconds even with address sanitizer...

**Comment by alesapin** [comment]
Functional stateless tests (release, DatabaseReplicated)
`Cannot allocate block number in ZooKeeper: Coordination::Exception: Connection loss` :(

**Comment by alesapin** [comment]
Tests Ok, but I don't understand why we have extremely rare `Connection loss`. Will try to investigate.

**Comment by alesapin** [comment]
Just found that it's not a problem with StateMachine or LogStore. Very rarely for some reason commit inside nuraft requires several seconds:
```
2021.02.24 12:32:20.068311 [ 15934 ] {} <Debug> NuKeeperTCPHandler: Finished 785
2021.02.24 12:32:20.068445 [ 15991 ] {} <Debug> NuKeeperStateMachine: Processing request 787
2021.02.24 12:32:20.068485 [ 15991 ] {} <Debug> NuKeeperStateMachine: DONE Processing request 787
2021.02.24 12:32:20.068536 [ 15934 ] {} <Debug> NuKeeperTCPHandler: Received 789
2021.02.24 12:32:20.068549 [ 15934 ] {} <Debug> NuKeeperTCPHandler: Finished 786
2021.02.24 12:32:20.068597 [ 15991 ] {} <Debug> NuKeeperStateMachine: Processing request 788
2021.02.24 12:32:20.068632 [ 15991 ] {} <Debug> NuKeeperStateMachine: DONE Processing request 788
2021.02.24 12:32:20.068682 [ 15934 ] {} <Debug> NuKeeperTCPHandler: Received 790
2021.02.24 12:32:20.068696 [ 15934 ] {} <Debug> NuKeeperTCPHandler: Finished 787
2021.02.24 12:32:20.068731 [ 15991 ] {} <Debug> NuKeeperStateMachine: Processing request 789
2021.02.24 12:32:20.068762 [ 15991 ] {} <Debug> NuKeeperStateMachine: DONE Processing request 789
2021.02.24 12:32:20.068816 [ 15934 ] {} <Debug> NuKeeperTCPHandler: Received 791
2021.02.24 12:32:20.068830 [ 15934 ] {} <Debug> NuKeeperTCPHandler: Finished 788
2021.02.24 12:32:20.068854 [ 15991 ] {} <Debug> NuKeeperStateMachine: Processing request 790
2021.02.24 12:32:20.068890 [ 15991 ] {} <Debug> NuKeeperStateMachine: DONE Processing request 790
2021.02.24 12:32:20.068939 [ 15934 ] {} <Debug> NuKeeperTCPHandler: Received 792
2021.02.24 12:32:20.068951 [ 15934 ] {} <Debug> NuKeeperTCPHandler: Finished 789
<...>
??? What is going on here?
It's important that the timer (`7000107 us`) start after entry appended to the log store.
<...>
2021.02.24 12:32:27.069070 [ 15994 ] {} <Warning> RaftInstance: [NOT OK] commit_ret_cv 802 wake up (7000107 us), return value (nil), result code -2
2021.02.24 12:32:27.069160 [ 15994 ] {} <Information> RaftInstance: leadership is still valid
2021.02.24 12:32:27.069296 [ 15991 ] {} <Debug> NuKeeperStateMachine: Processing request 791
2021.02.24 12:32:27.069336 [ 15991 ] {} <Debug> NuKeeperStateMachine: DONE Processing request 791
2021.02.24 12:32:27.069356 [ 15991 ] {} <Debug> NuKeeperStateMachine: Processing request 792
2021.02.24 12:32:27.069514 [ 15991 ] {} <Debug> NuKeeperStateMachine: DONE Processing request 792
2021.02.24 12:32:27.089966 [ 15934 ] {} <Information> NuKeeperTCPHandler: Got exception processing session #2: Code: 159, e.displayText() = DB::Exception: Cannot push request to queue within operation timeout, Stack trace (when copying this message, always include the lines below):
```

**Comment by alesapin** [comment]
Ahh 7 seconds is my operation timeout.

**Comment by alesapin** [comment]
third-party -- not related
ANTLR debug -- not related, broken in https://github.com/ClickHouse/ClickHouse/pull/20968

**Comment by alesapin** [comment]
Ok, let's merge and see what will happen.

**Comment by lddlww** [comment]
does this feature（NuRaft）can be used in the newest version？，if is，how can i config？

**Pull request merged**
