### PR TITLE
Bump `llvm-project` to 18.x

### PR DESCRIPTION
**Pull request by nikitamikhaylov**
Currently `llvm-project` submodule points to a commit from this branch https://github.com/ClickHouse/llvm-project/pull/44
Previous attempt was here https://github.com/ClickHouse/ClickHouse/pull/47783

### Changelog category (leave one):
- Build/Testing/Packaging Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
The internal dependency LLVM is bumped from 16 to 18. 

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Do not test
- [x]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-ch-test-poll3** [comment]
*This is an automated comment for commit 8f548178144db5a35c42b15b83de4bbb366aee36 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/66053/8f548178144db5a35c42b15b83de4bbb366aee36/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Style check</td><td>Runs a set of checks to keep the code style clean. If some of tests failed, see the related log from the report</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/66053/8f548178144db5a35c42b15b83de4bbb366aee36/style_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Comment by nikitamikhaylov** [comment]
Notes: 
- The `llvm::Optional` class was removed from LLVM codebase in this commit https://github.com/llvm/llvm-project/commit/397f2e9ebee8d8e45547e90dd05228d7f965df67. I just replaced it with `std::optional` and looks like everything is Ok.
- I've also submitted a PR to the upstream of a `pocketfft` lib https://github.com/mreineck/pocketfft/pull/18

Two things remain unsolved: 
- We need to patch RocksDB to make in compilable with new libcxx. Hopefully it will be done as a part of https://github.com/ClickHouse/ClickHouse/pull/66216
- We need to rework our JIT implementation. Most of the headers we including don't exist right now CC @kitaisreal

**Comment by nikitamikhaylov** [comment]
Depends on: https://github.com/ClickHouse/ClickHouse/pull/69654

**Comment by nikitamikhaylov** [comment]
Performance comparision reports: [1](https://s3.amazonaws.com/clickhouse-test-reports/66053/b0941e6a7967c1f410e473a98101a76532c9e00c/performance_comparison__release__[1_4]/report.html), [2](https://s3.amazonaws.com/clickhouse-test-reports/66053/b0941e6a7967c1f410e473a98101a76532c9e00c/performance_comparison__release__[2_4]/report.html), [3](https://s3.amazonaws.com/clickhouse-test-reports/66053/b0941e6a7967c1f410e473a98101a76532c9e00c/performance_comparison__release__[3_4]/report.html), [4](https://s3.amazonaws.com/clickhouse-test-reports/66053/b0941e6a7967c1f410e473a98101a76532c9e00c/performance_comparison__release__[4_4]/report.html)
**Slowndowns**: jit_large_requests - `87%`, float_formatting - `21%`, jit_small_requests - `49%`, schema_inference_text_formats - `15%`
**Speadups**: json_type - `20%`, parse_illegal_datetime - `40%`. 

Results more or less the same as for LLVM-16. Slowdown in float formatting is concerning.

**Review by Algunenano — APPROVED** [review]

**Comment by Algunenano** [comment]
The JIT slowdown is noticeable but not a blocker. The float_formatting only affects small integers (integers have their own code pass) so we should investigate it at some point, but not a blocker either. Let's update

**Comment by nikitamikhaylov** [comment]
I've checked and there were some other failures of the `test_many_mutations` [in another PRs](https://play.clickhouse.com/play?user=play#U0VMRUNUIGNoZWNrX25hbWUsIHRlc3RfbmFtZSwgcmVwb3J0X3VybApGUk9NIGNoZWNrcwpXSEVSRSAxCiAgICBBTkQgY2hlY2tfc3RhcnRfdGltZSA+PSBub3coKSAtIElOVEVSVkFMIDE0NCBIT1VSCiAgICBBTkQgdGVzdF9zdGF0dXMgIT0gJ1NLSVBQRUQnCiAgICBBTkQgKHRlc3Rfc3RhdHVzIExJS0UgJ0YlJyBPUiB0ZXN0X3N0YXR1cyBMSUtFICdFJScpIAogICAgQU5EIGNoZWNrX3N0YXR1cyAhPSAnc3VjY2VzcycKICAgIEFORCB0ZXN0X25hbWUgSUxJS0UgJyUwMjEyNV9tYW55X211dGF0aW9ucyUnCk9SREVSIEJZIGNoZWNrX25hbWUsIHRlc3RfbmFtZSwgY2hlY2tfc3RhcnRfdGltZQ==). I will override the check for now and merge.

**Comment by taiyang-li** [comment]
> The JIT slowdown is noticeable but not a blocker. The float_formatting only affects small integers (integers have their own code pass) so we should investigate it at some point, but not a blocker either. Let's update

@Algunenano Do you known why performance is slower after upgrade llvm from 18.x. I found similar performance regressions in Gluten with JIT enabled.

**Comment by Algunenano** [comment]
AFAIK we haven't investigated neither of the slowdowns.

**Comment by rschu1ze** [comment]
Let's see if #73957 helps.

**Pull request merged**
