### PR TITLE
Update NuRaft

### PR DESCRIPTION
**Pull request by alesapin**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
@mergifyio update

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
@Mergifyio update

**Comment by alesapin** [comment]
```
2021.06.02 14:29:59.234118 [ 331 ] {} <Error> test_9.dst (d5bc0a00-7af9-44ff-95bc-0a007af9b4ff): ReplicatedMergeTreeQueue::SelectedEntryPtr DB::StorageReplicatedMergeTree::selectQueueEntry(): Code: 49, e.displayText() = DB::Exception: Tagging already tagged future part 1_47_47_0. This is a bug., Stack trace (when copying this message, always include the lines below):
```

**Comment by alesapin** [comment]
No related failures.

**Pull request merged**
