### PR TITLE
Optimize roaring bitmaps in inverted index

### PR DESCRIPTION
**Pull request by HarryLeeIBM**
This PR is to optimizes the representation (internal container types) of roaring bitmaps used by posting lists of inverted indexes before writing them into disks. This can significantly reduce the size of the index for repetitive data.

The fix was proposed In #38667 by @juppylm.

Before the fix,  our internal test database which contains server logs  has one bin file with the size 264M and generates 472M .gin_post posting list file. After the fix, the same bin file only generates 94M posting list file which is 5 times smaller. Note that for those database which contains less repetitive data, the size reduction is not very significant. For example, the hacker news database only reduces about 2-5% of posting list file sizes.

The performance of index building and queries are not affected by the fix, however some slightly speed-ups can be observed in general.

### Changelog category (leave one):
- Performance Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Posting lists in inverted indexes are now optimized to use the smallest possible representation for internal bitmaps. Depending on the repetitiveness of the data, this may significantly reduce the space consumption of inverted indexes.

### CODE REVIEW

**Comment by HarryLeeIBM** [comment]
@rschu1ze, could you review this fix for full text search, thanks!

**Comment by robot-ch-test-poll1** [comment]
*This is an automated comment for commit 71adb052eee3385a07d8603fa0df0ea229194e07 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/55069/71adb052eee3385a07d8603fa0df0ea229194e07/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>✅ success</td></tr>
<tbody>
</table>
</details>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>⏳ pending</td></tr>
<tbody>
</table>

**Comment by evillique** [comment]
Did not look into this PR in particular, but to keep in mind: recently https://github.com/ClickHouse/ClickHouse/pull/52842 using similar optimization was merged and reverted because of the ThreadSanitizer (resubmitted in https://github.com/ClickHouse/ClickHouse/pull/55044).

**Comment by rschu1ze** [comment]
> Did not look into this PR in particular, but to keep in mind: recently a PR #52842 with a similar optimization was merged and reverted because of the ThreadSanitizer (resubmitted in #55044).

The problem in the other PR was that the roaring bitmap is already in use, i.e. concurrently being modified (`runOptimize()`) and read. The CRoaring library provides no synchronization, the caller needs to take care of it. #55044 solves this by making a copy of the bitmap before optimizing it.

As far as I see, `GinIndexPostingsBuilder::serialize()` is called when the bitmap is not visible to queries yet, so there can't be races.

**Pull request merged**
