### PR TITLE
tests: capture dmesg in integration tests

### PR DESCRIPTION
**Pull request by azat**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

This is to get more details for issues like:
- #41776

### CODE REVIEW

**Comment by azat** [comment]
Looks like [it works](https://s3.amazonaws.com/clickhouse-test-reports/44535/69fadd21933b02e09ec73e689273d6250eb73c31/integration_tests__asan__[1/6]/runner_get_all_tests.log):

```
[Fri Dec 23 17:07:39 2022] docker0: port 1(vethcf1ecbf) entered blocking state
[Fri Dec 23 17:07:39 2022] docker0: port 1(vethcf1ecbf) entered disabled state
```

**Review by alexey-milovidov — APPROVED** [review]

**Comment by nikitamikhaylov** [comment]
@azat @alexey-milovidov It doesn't work at all. Revert? 
```
ubuntu@ip-10-1-13-116:~/ClickHouse/ClickHouse/tests/integration$ ./runner "-ss test_keeper_multinode_simple/test.py::test_follower_restart"
2022-12-27 15:29:42,927 [ 3833977 ] INFO : ClickHouse root is not set. Will use /home/ubuntu/ClickHouse/ClickHouse (runner:41, check_args_and_update_paths)
2022-12-27 15:29:42,927 [ 3833977 ] INFO : Cases dir is not set. Will use /home/ubuntu/ClickHouse/ClickHouse/tests/integration (runner:89, check_args_and_update_paths)
2022-12-27 15:29:42,927 [ 3833977 ] INFO : src dir is not set. Will use /home/ubuntu/ClickHouse/ClickHouse/src (runner:96, check_args_and_update_paths)
2022-12-27 15:29:42,927 [ 3833977 ] INFO : base_configs_dir: /home/ubuntu/ClickHouse/ClickHouse/programs/server/, binary: /home/ubuntu/ClickHouse/build/programs/clickhouse, cases_dir: /home/ubuntu/ClickHouse/ClickHouse/tests/integration  (runner:98, check_args_and_update_paths)
clickhouse_integration_tests_volume
dmesg: klogctl failed: Operation not permitted
Traceback (most recent call last):
  File "./runner", line 417, in <module>
    subprocess.check_call("dmesg --clear", shell=True)
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'dmesg --clear' returned non-zero exit status 1.

```

**Comment by azat** [comment]
It looks like you don't have privileges for this command inside your container, although it works on CI.

I guess the fix for you will be to wrap this commands with `sudo`.

**Comment by alesapin** [comment]
`> I guess the fix for you will be to wrap this commands with sudo.`

**Comment by azat** [comment]
>must work without sudo. @nikitamikhaylov, please consider reverting

@alesapin it cannot work without `sudo`, you cannot clear dmesg buffer (`SYSLOG_ACTION_CLEAR`) without `CAP_SYSLOG`, this is simply prohibited.
You are against collecting dmesg for integration tests?

If so, there are other places where the same command is used:
- https://github.com/ClickHouse/ClickHouse/blob/ac162a2c490821c43fdbd499482bcadb40160586/docker/test/stress/run.sh#L7
- https://github.com/ClickHouse/ClickHouse/blob/ac162a2c490821c43fdbd499482bcadb40160586/docker/test/stress/run.sh#L570

So consider removing it too then.

**Comment by azat** [comment]
>you cannot clear dmesg buffer (SYSLOG_ACTION_CLEAR) without CAP_SYSLOG, this is simply prohibited.

https://github.com/torvalds/linux/blob/1b929c02afd37871d5afb9d498426f83432e71c2/kernel/printk/printk.c#L611

**Comment by alexey-milovidov** [comment]
@azat Let's make it degrade gracefully if the capability is unavailable - it can print an information message but not fail.

**Comment by azat** [comment]
@alexey-milovidov OK, actually simply moving it into another script (that is executed only by CI) will work too - #44667

**Comment by alesapin** [comment]
@azat I'm not against collecting them in CI. But scripts which contributors use locally should never require `sudo`.

**Pull request merged**
