### PR TITLE
Make Schema inference works for CREATE AS SELECT

### LINKED ISSUE #47599: Schema inference for INSERT SELECT should also work for CREATE AS SELECT
```
milovidov-desktop :) CREATE TABLE `01902_db`.t (`n` Int8) ENGINE = MergeTree ORDER BY n AS SELECT * FROM generateRandom() LIMIT 10;

CREATE TABLE `01902_db`.t
(
    `n` Int8
)
ENGINE = MergeTree
ORDER BY n AS
SELECT *
FROM generateRandom()
LIMIT 10

Query id: 2003bf93-4643-4dca-8319-5eb562190805


0 rows in set. Elapsed: 0.047 sec. 

Received exception:
Code: 636. DB::Exception: Table function 'generateRandom' was used without structure argument but structure could not be determined automatically. Please, provide structure manually. (CANNOT_EXTRACT_TABLE_STRUCTURE)
```

### PR DESCRIPTION
**Pull request by ucasfl**
### Changelog category (leave one):

- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Make Schema inference works for `CREATE AS SELECT`. Closes https://github.com/ClickHouse/ClickHouse/issues/47599.

### CODE REVIEW

**Review by pufit — APPROVED** [review]

**Comment by pufit** [comment]
We have some concerns about why the performance build report failed. I will temporarily revert this pr

**Comment by pufit** [comment]
@ucasfl I found a query that was broken by this commit query. It can be reproduced like this:

`cat mock_data.tsv`
```
UserName	Age	Tags
String	Int8	Map(String, UInt64)
user127	20	{'test': 123}
user405	43	{'test': 123}
user902	43	{'test': 123}
```

```
CREATE VIEW users AS SELECT * FROM file('mock_data.tsv', TSVWithNamesAndTypes);
```

```
CREATE TABLE users_output ENGINE File(TSV, 'output.tsv')
AS
WITH (SELECT groupUniqArrayArray(mapKeys(Tags))
      FROM users) AS unique_tags
SELECT UserName, length(unique_tags)
FROM users;
```

The last query will result in an error
```
Code: 47. DB::Exception: Received from localhost:9000. DB::Exception: Unknown column: Tags, there are only columns : While processing (SELECT groupUniqArrayArray(mapKeys(Tags)) FROM users) AS unique_tags. (UNKNOWN_IDENTIFIER)
```

**Comment by ucasfl** [comment]
> 

I reproduce this at the first time run, but then can not reproduce anymore.

**Comment by ucasfl** [comment]
> @ucasfl I found a query that was broken by this commit. It can be reproduced like this:
> 
> `cat mock_data.tsv`
> 
> ```
> UserName	Age	Tags
> String	Int8	Map(String, UInt64)
> user127	20	{'test': 123}
> user405	43	{'test': 123}
> user902	43	{'test': 123}
> ```
> 
> ```
> CREATE VIEW users AS SELECT * FROM file('mock_data.tsv', TSVWithNamesAndTypes);
> ```
> 
> ```
> CREATE TABLE users_output ENGINE File(TSV, 'output.tsv')
> AS
> WITH (SELECT groupUniqArrayArray(mapKeys(Tags))
>       FROM users) AS unique_tags
> SELECT UserName, length(unique_tags)
> FROM users;
> ```
> 
> The last query will result in an error
> 
> ```
> Code: 47. DB::Exception: Received from localhost:9000. DB::Exception: Unknown column: Tags, there are only columns : While processing (SELECT groupUniqArrayArray(mapKeys(Tags)) FROM users) AS unique_tags. (UNKNOWN_IDENTIFIER)
> ```

Although the change makes the query above does not work. However, even without the change, the query also does not work if we first create table `users_output`, then execute:
```sql
INSERT INTO users_output 
WITH (SELECT groupUniqArrayArray(mapKeys(Tags))
      FROM users) AS unique_tags
SELECT UserName, length(unique_tags);
FROM users;

Code: 47. DB::Exception: Received from localhost:9000. DB::Exception: Unknown column: Tags, there are only columns : While processing (SELECT groupUniqArrayArray(mapKeys(Tags)) FROM users) AS unique_tags. (UNKNOWN_IDENTIFIER)
```

**Pull request merged**
