### PR TITLE
Every MergeTree setting must have documentation

### PR DESCRIPTION
**Pull request by alexey-milovidov**
### Changelog category (leave one):
- Build/Testing/Packaging Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Enforce documentation for every MergeTree setting.

### CODE REVIEW

**Review by davenger — APPROVED** [review]

**Comment by tavplubix** [comment]
Let's also add similar check for `system.settings` (unfortunately, we already have 18 settings without description, but at least new ones will not be added):
```
SELECT name FROM system.settings WHERE length(description) < 10 AND name NOT IN ('receive_timeout','send_timeout','parallel_replicas_count','parallel_replica_offset','insert_quorum_timeout','preferred_block_size_bytes','max_rows_to_group_by','max_bytes_before_external_group_by','max_rows_to_sort','max_bytes_to_sort','max_bytes_before_external_sort','max_execution_time','max_columns_to_read','max_temporary_columns','max_temporary_non_const_columns','max_subquery_depth','max_pipeline_depth','read_from_filesystem_cache_if_exists_otherwise_bypass_cache');
```

**Comment by davenger** [comment]
In stateless tests with UBSAN the server seem to have hung for around 50 sec:
https://s3.amazonaws.com/clickhouse-test-reports/40648/8ee6e8718804367eb0bca71dca8d3bbc4760ee10/stateless_tests__ubsan_/clickhouse-server.err.log
```
2022.08.26 11:57:19.149072 [ 704 ] {} <Warning> test_ialj2o.test_inserts (167b672b-51b3-4760-a69b-db0bc7dc12f2): /var/lib/clickhouse/store/167/167b672b-51b3-4760-a69b-db0bc7dc12f2/tmp_insert_8_9_9_0/ is in use (by merge/mutation/INSERT) (consider increasing temporary_directories_lifetime setting)
2022.08.26 11:58:11.069690 [ 3173 ] {02366_5} <Error> executeQuery: Code: 210. DB::NetException: I/O error: Broken pipe, while writing to socket ([::1]:47026). (NETWORK_ERROR) (version 22.9.1.1) (from [::1]:47026) (comment: 02366_cancel_write_into_file.sh) (in query: insert into function file('02366_data_5.jsonl') select range(number % 1000) from numbers(100000) settings output_format_parallel_formatting=1), Stack trace (when copying this message, always include the lines below):
```
and tests timed out
https://s3.amazonaws.com/clickhouse-test-reports/40648/8ee6e8718804367eb0bca71dca8d3bbc4760ee10/stateless_tests__ubsan_/runlog.log
```
2022-08-26 11:57:13 02363_mapupdate_improve:                                                [ OK ] 0.24 sec.
2022-08-26 11:57:14 02362_part_log_merge_algorithm:                                         [ OK ] 0.80 sec.
2022-08-26 11:57:44 02360_small_notation_h_for_hour_interval:                               [ FAIL ] 0.00 sec. - server died
2022-08-26 11:57:44 Server does not respond to health check 
```
Maybe related to #40611

**Comment by tavplubix** [comment]
Sorry, I missed another PR https://github.com/ClickHouse/ClickHouse/pull/40644

**Comment by davenger** [comment]
Created #40669 for the failure in stress. It's not related to the changes in this PR

**Pull request merged**
