### PR TITLE
Bump gRPC to v1.54.3

### PR DESCRIPTION
**Pull request by rschu1ze**
See #56059

(this PR will accumulate multiple version bumps, cf. https://github.com/ClickHouse/ClickHouse/pull/56059#pullrequestreview-1701362162)

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by robot-ch-test-poll** [comment]
*This is an automated comment for commit 015e29b006bf09bbd1605316f3f8650a442129ad with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/56543/015e29b006bf09bbd1605316f3f8650a442129ad/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td><a href="https://github.com/ClickHouse/ClickHouse/actions/runs/6816542219">✅ success</a></td></tr>
<tbody>
</table>
</details>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/56543/015e29b006bf09bbd1605316f3f8650a442129ad/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Comment by rschu1ze** [comment]
@Algunenano The PR jumps from v1.47 to v1.54. Like to review/approve?

**Review by alexey-milovidov — APPROVED** [review]

**Comment by rschu1ze** [comment]
Thanks, I took the freedom and fixed this oversight in your reverting PR #56671. I can only assume that package `libsystemd-devel` is installed in CI ... (with respect to your local build, I am admittedly a bit confused that CMake did not decide to simply omit the systemd dependency - it rather failed at compile time).

**Comment by Algunenano** [comment]
Probably it's the other way around. The systemd devel files are present in my system and not in CI, so in my system it tries to include files that won't be accessible (because of sysroot).

**Pull request merged**
