### PR TITLE
Fix comment in config.xml

### LINKED ISSUE #66319: part_log is enabled by default
**Describe the issue**
The `part_log` in enabled by default.
The file mentions to uncomment the block if needed, but the comment-finish tag is wrongly place.
https://github.com/ClickHouse/ClickHouse/blob/master/programs/server/config.xml#L1135

**How to reproduce**
* Which ClickHouse server version to use: latest

**Expected behavior**
Proper setting to disable part_log.

### PR DESCRIPTION
**Pull request by den-crane**
closes: #66319

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by robot-ch-test-poll1** [comment]
*This is an automated comment for commit fa41b131a9dc13bb7c93680554224c5ba72d06a2 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/66338/fa41b131a9dc13bb7c93680554224c5ba72d06a2/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/4a7e81a9fef3ffb79ab3afb16b570f2960455323/docs_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Review by Algunenano — APPROVED** [review]

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
We have to merge https://github.com/ClickHouse/ClickHouse/pull/66107 first, otherwise this pull request is not mergeable.

**Comment by alexey-milovidov** [comment]
@den-crane, there was an unbalanced whitespace in your modification. I fixed it.

**Comment by alexey-milovidov** [comment]
@Algunenano, please fix the tests in the private repository. Otherwise this pull request is not mergeable.

**Comment by alexey-milovidov** [comment]
This PR has failed tests. Closing in favor of https://github.com/ClickHouse/ClickHouse/pull/67428

**Pull request closed without merging**
