### PR TITLE
Try update protobuf to 3.17.3

### PR DESCRIPTION
**Pull request by qoega**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Updated protobuf to 3.17.3. Changelogs are available on https://github.com/protocolbuffers/protobuf/releases

Detailed description / Documentation draft:

...

By adding documentation, you'll allow users to try your new feature immediately, not when someone else will have time to document it later. Documentation is necessary for all features that affect user experience in any way. You can add brief documentation draft above, or add documentation right into your patch as Markdown files in [docs](https://github.com/ClickHouse/ClickHouse/tree/master/docs) folder.

If you are doing this for the first time, it's recommended to read the lightweight [Contributing to ClickHouse Documentation](https://github.com/ClickHouse/ClickHouse/tree/master/docs/README.md) guide first.

Information about CI checks: https://clickhouse.tech/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
What is the motivation for this update?

**Comment by qoega** [comment]
> What is the motivation for this update?

Minimize commits that present in Extras but not yet in upstream. Some changes collapse but in some cases I'm going to detect cases where we have not sent changes to upstream.
And in general newer versions of contrib libraries should have less bugs and issues. For example hombrew team tries to forbid  vendoring due to possible security flaws that can remain in vendored libraries and fixes in main repository.

**Comment by qoega** [comment]
@Mergifyio rebase

**Comment by qoega** [comment]
FYI to debug errors in QEMU there is special integration with remote gdb: `-g PORT` waits gdb to attach.
```
qemu-x86_64-static -g 1234 -cpu qemu64  /home/qoega/release-ch/output/binary/clickhouse --query "SELECT 1"
```

In gdb you can see
```
(gdb) target remote localhost:1234
Remote debugging using localhost:1234
warning: No executable has been specified and target does not support
determining executable automatically.  Try using the "file" command.
0x0000004000802090 in ?? ()
(gdb) file /home/qoega/release-ch/output/binary/clickhouse
A program is being debugged already.
Are you sure you want to change the file? (y or n) y
Reading symbols from /home/qoega/release-ch/output/binary/clickhouse...done.
(gdb) c
Continuing.

Program received signal SIGILL, Illegal instruction.
0x00000000114eda3d in base_extent_bump_alloc_post (base=0x4001c000c0, extent=<optimized out>, gap_size=<optimized out>, addr=0x4001c000c0, size=2048)
    at ../contrib/jemalloc/src/base.c:211
211	../contrib/jemalloc/src/base.c: No such file or directory.
(gdb) bt
#0  0x00000000114eda3d in base_extent_bump_alloc_post (base=0x4001c000c0, extent=<optimized out>, gap_size=<optimized out>, addr=0x4001c000c0, size=2048)
    at ../contrib/jemalloc/src/base.c:211
#1  base_new (tsdn=<optimized out>, ind=0, extent_hooks=<optimized out>) at ../contrib/jemalloc/src/base.c:389
#2  0x00000000114d1948 in base_boot (tsdn=0x0) at ../contrib/jemalloc/src/base.c:512
#3  malloc_init_hard_a0_locked () at ../contrib/jemalloc/src/jemalloc.c:1507
#4  0x00000000114d698a in malloc_init_hard () at ../contrib/jemalloc/src/jemalloc.c:1736
#5  0x00000000114d0434 in malloc_init () at ../contrib/jemalloc/src/jemalloc.c:223
#6  nallocx (size=64, flags=0) at ../contrib/jemalloc/src/jemalloc.c:3611
#7  0x0000000009064f30 in Memory::getActualAllocationSize (size=64) at ../src/Common/new_delete.cpp:52
#8  Memory::trackMemory (size=64) at ../src/Common/new_delete.cpp:60
#9  operator new (size=64) at ../src/Common/new_delete.cpp:92
#10 0x0000000014de5201 in google::protobuf::internal::ShutdownData::get () at ../contrib/protobuf/src/google/protobuf/message_lite.cc:564
#11 google::protobuf::internal::OnShutdownRun (f=0x14dc01c0 <google::protobuf::internal::DestroyString(void const*)>,
    arg=0x1608d528 <google::protobuf::internal::fixed_address_empty_string>) at ../contrib/protobuf/src/google/protobuf/message_lite.cc:582
#12 0x0000000014dc021f in google::protobuf::internal::OnShutdownDestroyString (ptr=<optimized out>)
    at ../contrib/protobuf/src/google/protobuf/generated_message_util.h:203
#13 google::protobuf::internal::InitProtobufDefaultsImpl () at ../contrib/protobuf/src/google/protobuf/generated_message_util.cc:76
#14 google::protobuf::internal::InitProtobufDefaultsSlow () at ../contrib/protobuf/src/google/protobuf/generated_message_util.cc:84
#15 0x0000000014ebae72 in google::protobuf::internal::InitProtobufDefaults () at ../contrib/protobuf/src/google/protobuf/generated_message_util.h:96
#16 google::protobuf::(anonymous namespace)::AddDescriptorsImpl (table=0x15c6cd30 <descriptor_table_orc_5fproto_2eproto>)
    at ../contrib/protobuf/src/google/protobuf/generated_message_reflection.cc:2756
#17 google::protobuf::(anonymous namespace)::AddDescriptors (table=0x15c6cd30 <descriptor_table_orc_5fproto_2eproto>)
    at ../contrib/protobuf/src/google/protobuf/generated_message_reflection.cc:2778
#18 0x0000000009063b4d in __libc_csu_init ()
#19 0x0000004001086b88 in ?? ()
#20 0x0000000000000000 in ?? ()
```

**Comment by alexey-milovidov** [comment]
@mergifyio update

**Review by alexey-milovidov — APPROVED** [review]

**Pull request merged**
