### PR TITLE
Update xxhash to v0.8.2

### PR DESCRIPTION
**Pull request by shubhamranjan**
### Changelog category (leave one):
- Not for changelog

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Update xxHash to v0.8.2 which has [various fixes and improvements on multiple platforms](https://github.com/Cyan4973/xxHash/tree/v0.8.2)

---
### Modify your CI run:
**NOTE:** If your merge the PR with modified CI you **MUST KNOW** what you are doing
**NOTE:** Set desired options before CI starts or re-push after updates

#### Run only:
- [ ]  Integration tests
- [ ]  Integration tests (arm64)
- [ ]  Stateless tests (release)
- [ ]  Stateless tests (asan)
- [ ]  Stateful tests (release)
- [ ]  Stateful tests (asan)
- [ ]  No sanitizers
- [ ]  Tests with analyzer
- [ ]  Fast tests
- [ ]  Only package_debug build
- [ ]  Add your CI variant description here

#### CI options:
- [ ]  do not test (only style check)
- [ ]  disable merge-commit (no merge from master before tests)
- [ ]  disable CI cache (job reuse)

#### Only specified batches in multi-batch jobs:
- [ ]  1
- [ ]  2
- [ ]  3
- [ ]  4

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
What exactly does it mean, "chore"?

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
The category "Improvement" was incorrect, because nothing was improved.

**Comment by robot-clickhouse** [comment]
*This is an automated comment for commit e2974c9f4bba796d70195b9e2081499d127e8f24 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/61838/e2974c9f4bba796d70195b9e2081499d127e8f24/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

**Comment by shubhamranjan** [comment]
Thanks @alexey-milovidov .
Chore is usually referred to as a routine task for maintenance like dependency updates.

Ref: https://www.conventionalcommits.org/en/v1.0.0/

The upstream library mentioned improvements in changelog, so I thought it might fit here. I will take care of a correct category next time.

**Comment by franz101** [comment]
> What exactly does it mean, "chore"?

cleaning the house is a weekly chore for example

**Pull request merged**
