### PR TITLE
Add JSON fuzzer

### PR DESCRIPTION
**Pull request by CurtizJ**
### Changelog category (leave one):
- Build/Testing/Packaging Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Added simple JSON fuzzer, which fuzzes the structure of json documents: randomly adds, removes and renames keys and changes types of the values and the  values themselves. It's intended to be used to generates data for testing recently added type `Object`.

### CODE REVIEW

**Comment by CurtizJ** [comment]
The fuzzer still requires some work on it, but already one bug was found with its help #35960.

**Comment by qoega** [comment]
Probably it is good to merge it already?

**Comment by qoega** [comment]
>Probably it is good to merge it already?

How about to do it this year @CurtizJ? :)

**Comment by CurtizJ** [comment]
It's mostly useless now. Maybe it's worth to merge it when I'll continue working on JSON type.

**Pull request closed without merging**
