### PR TITLE
Update MsgPack format

### PR DESCRIPTION
**Pull request by Avogar**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Remove converting ColumnFixedString to FixedString in MsgPack fromat and add performance test.
https://github.com/ClickHouse/ClickHouse/pull/9889

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
(test pending)

**Review by alexey-milovidov — APPROVED** [review]

**Comment by Avogar** [comment]
I've noticed that MsgPack input format is too slow, after some research I've found that msgpack::unpack make a copy of parsed object by default, I'll fix it soon.

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
Something is still wrong in performance test.

**Comment by Avogar** [comment]
It's really strange... I successfully ran this test locally (corresponding to https://github.com/ClickHouse/ClickHouse/blob/master/docker/test/performance-comparison/performance_comparison.md#run-a-single-test-on-the-already-configured-servers).

**Comment by Avogar** [comment]
@alexey-milovidov 
After a small research I've found that similar errors have already occured:
https://github.com/mymarilyn/clickhouse-driver/issues/121
https://stackoverflow.com/questions/57786801/testing-containers-and-clickhouse-driver-errorunexpected-eof-while-reading-byte

For this reason I can suggest that problem is not in MsgPackInputFormat, but I could be wrong. Can someone help with it?

**Comment by akuzm** [comment]
> @alexey-milovidov
> After a small research I've found that similar errors have already occured:
> [mymarilyn/clickhouse-driver#121](https://github.com/mymarilyn/clickhouse-driver/issues/121)
> https://stackoverflow.com/questions/57786801/testing-containers-and-clickhouse-driver-errorunexpected-eof-while-reading-byte
> 
> For this reason I can suggest that problem is not in MsgPackInputFormat, but I could be wrong. Can someone help with it?

Probably adding `format Null` to the test queries can help. I'll do it now.

**Comment by alexey-milovidov** [comment]
@akuzm It didn't.

**Comment by alexey-milovidov** [comment]
I'll merge this PR without addition to perf test...

**Pull request merged**
