### PR TITLE
[types] Add BFloat16 with Float32 wrapper

### PR DESCRIPTION
**Pull request by shaprunovk**
### Changelog category (leave one):
- New Feature

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
BFloat16 type support add

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)
Motivation: https://github.com/ClickHouse/ClickHouse/issues/44206

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by darkleaf** [comment]
Could I convert an existing column of type Float32 to BFloat16?

**Comment by shaprunovk** [comment]
> Could I convert an existing column of type Float32 to BFloat16?

Still in progress, but when it's ready you will be able to

**Comment by Alex-Cheng** [comment]
I am wondering that why the PR is closed without merging. The feature brougt by the PR is useful for vector database.

**Comment by rschu1ze** [comment]
Let's re-open it.

We can continue if @shaprunovk provides
- a note if this PR is actually in a review-able state,
- a note what changed and what the implications and trade-offs the implementation has,
- SQL tests for everything that changed,
- end-user documentation.

**Pull request closed without merging**
