### PR TITLE
Documentation: add Ibis project to the integrations section

### PR DESCRIPTION
**Pull request by kszucs**
### Changelog category (leave one):
- Documentation (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
...

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

The [pandahouse](https://github.com/kszucs/pandahouse) library is not maintained anymore (I'm the author). We have been focusing on the development of the [Ibis framework](https://github.com/ibis-project/ibis) which is a dataframe-like frontend for various compute engines and databases, including ClickHouse (using clickhouse-connect and the pyarrow format). 

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
Is it intentional that Pandahouse is removed?

**Review by alexey-milovidov — APPROVED** [review]

**Comment by kszucs** [comment]
It is, I'm not actively maintaining it anymore. 

Thanks for merging!

**Comment by alexey-milovidov** [comment]
Sorry, could you please resubmit with https://s3.amazonaws.com/clickhouse-test-reports/0/0e25042671a756a0172ac4e0e13dfd315e032bf7/style_check/docs_spelling_output.txt ?

**Comment by kszucs** [comment]
Resubmitted in https://github.com/ClickHouse/ClickHouse/pull/53371

**Pull request merged**
