### PR TITLE
Fix data race in Join

### PR DESCRIPTION
**Pull request by alexey-milovidov**
Changelog category (leave one):
- Not for changelog

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Data race was possible when JOIN was used with subquery containing WITH TOTALS.

Detailed description / Documentation draft:
https://clickhouse-test-reports.s3.yandex.net/19442/ccf332ea7e459a28c6d05b90d2783aad831b91ea/fuzzer_tsan/server.log

I asked @KochetovNicolai about why totals can be accessed and set concurrently and get the answer that it should not happen. Let's make code safe even before Nicolay will investigate it further.

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
Help wanted from @KochetovNicolai

**Comment by KochetovNicolai** [comment]
Query: `SELECT (-2, 2), ccc FROM (SELECT NULL AS ccc UNION ALL SELECT * FROM (SELECT 2 AS ccc) ANY INNER JOIN (SELECT 7 AS ccc) USING (ccc)) WHERE ccc > NULL format TSV` (actually, it does not contain totals)

Graph.
graphviz

Note: totals are always calculated if there is JOIN. Because we do not check if right table can or cannot have `WITH TOTALS`.

Assumption about what's happening:
1. We start executing query
2. `FilterTransform` applies optimization for `WHERE ccc > NULL` and decide not to read more data
3. Totals are allowed to be executed, and at the same time `JoiningTransform` continue it's execution.

Probably, `DelayedPortsProcessor` should check if all output ports are closed beforehand.
But avoiding data race in join may be useful anyway.

**Comment by chenziliang** [comment]
This graph is very useful for triaging. May i ask if it is automatically generated or by manual ? Thanks

**Comment by KochetovNicolai** [comment]
@chenziliang this graph is automatically generated. You can get graphviz output using `explain pipeline graph = 1, compact = 0 select ...` (it won't have last output format, however).

**Comment by chenziliang** [comment]
> @chenziliang this graph is automatically generated. You can get graphviz output using `explain pipeline graph = 1, compact = 0 select ...` (it won't have last output format, however).

Thanks a lot

**Comment by alexey-milovidov** [comment]
The bug was fixed in another PR.

**Pull request closed without merging**
