### PR TITLE
Reduce `clickhouse/unit-test` size 6 times

### PR DESCRIPTION
**Pull request by Felixoid**
### Changelog category (leave one):
- Build/Testing/Packaging Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Decrease the `unit-test` image a few times.

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: Normal Builds
- [ ]  Allow: Special Builds
- [ ]  Allow: All NOT Required Checks
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Do not test
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by Felixoid** [comment]
Now the image is being downloaded for 5 minutes

```
Tue, 11 Jun 2024 13:59:56 GMT INFO:root:Pulling image clickhouse/unit-test:22b2ad2d762f - start
Tue, 11 Jun 2024 14:04:32 GMT INFO:root:Pulling image clickhouse/unit-test:22b2ad2d762f - done
```

And is 1.65GB

**Comment by Felixoid** [comment]
When was the last time you saw an image of losing weight almost 7 times?

image

**Comment by Felixoid** [comment]
Canceled the workflow; unit tests finished successfully. Waiting for the sync

**Comment by Felixoid** [comment]
Ready for review, easy one!

**Review by nikitamikhaylov — APPROVED** [review]

**Comment by Felixoid** [comment]
@maxknv the cherry-pick script still put `pr-backports-created`. Looks like it's from the private repo, so this must not be set there

**Pull request merged**
