### PR TITLE
Follow up to #19516

### PR DESCRIPTION
**Pull request by abyss7**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Other

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix some points from this comment https://github.com/ClickHouse/ClickHouse/pull/19516#issuecomment-782047840

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
A test for `max_uri_size` needed.

**Comment by alexey-milovidov** [comment]
Also please check other settings and places in code about uri vs. url. If we're already using url everywhere, maybe it's better to name the setting `max_url_length` even if it's more old fashioned.

**Comment by abyss7** [comment]
> Also please check other settings and places in code about uri vs. url. If we're already using url everywhere, maybe it's better to name the setting `max_url_length` even if it's more old fashioned.

I found a sole setting with an 'url` in its name: `M(URI, format_avro_schema_registry_url)`, also in code it's not that widely used either. I suggest to leave the name as it is.

**Comment by alexey-milovidov** [comment]
Ok.

**Comment by alexey-milovidov** [comment]
> Stress test (thread) — Fatal message in clickhouse-server.log 

OOM

**Comment by alexey-milovidov** [comment]
Integration:

```
e = HTTPError('409 Client Error: Conflict for url: http+docker://localhost/v1.41/containers/5b28247074bad9b7697d6dc1e780be3645ad2b7a34f437196bc3e10293cc09fa/exec',)

    def create_api_error_from_http_exception(e):
        """
        Create a suitable APIError from requests.exceptions.HTTPError.
        """
        response = e.response
        try:
            explanation = response.json()['message']
        except ValueError:
            explanation = (response.content or '').strip()
        cls = APIError
        if response.status_code == 404:
            if explanation and ('No such image' in str(explanation) or
                                'not found: does not exist or no pull access'
                                in str(explanation) or
                                'repository does not exist' in str(explanation)):
                cls = ImageNotFound
            else:
                cls = NotFound
>       raise cls(e, response=response, explanation=explanation)
E       docker.errors.APIError: 409 Client Error for http+docker://localhost/v1.41/containers/5b28247074bad9b7697d6dc1e780be3645ad2b7a34f437196bc3e10293cc09fa/exec: Conflict ("Container 5b28247074bad9b7697d6dc1e780be3645ad2b7a34f437196bc3e10293cc09fa is not running")
```

No idea what does it mean.

**Comment by alexey-milovidov** [comment]
Server failed to start with:

```
Caught exception while loading metadata: Code: 36, e.displayText() = DB::Exception: Dictionary (`test_01676.dict`) not found: While processing CAST(dictGet('test_01676.dict', 'value', x) AS y_tmp_alter17144938244732776432, 'UInt64') AS y: default expression and column type are incompatible.: Cannot attach table `test_01676`.`table` from metadata file /var/lib/clickhouse/store/060/0604aada-1fbb-4a1c-8325-99d4a6e56caf/table.sql from query ATTACH TABLE test_01676.table UUID '56e67de3-8f59-403c-baed-e7a44aef814a' (`x` UInt64, `y` UInt64 DEFAULT dictGet('test_01676.dict', 'value', x)) ENGINE = MergeTree ORDER BY tuple() SETTINGS index_granularity = 8192: while loading database `test_01676` from path /var/lib/clickhouse/metadata/test_01676
```

**Comment by alexey-milovidov** [comment]
@abyss7 Now the following remains:
- get rid of `ostream` when writing result;
- check if zero copy data reading is possible in `HTTPChunkedReadBuffer`.

**Comment by gyuton** [comment]
Internal documentation ticket: DOCSUP-8495.

**Pull request merged**
