### PR TITLE
JOIN filter push down right stream filled crash fix

### PR DESCRIPTION
**Pull request by kitaisreal**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by robot-ch-test-poll4** [comment]
*This is an automated comment for commit e2ff2f8a1fd2a660208111b6ba83849b24fefc5d with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/62624/e2ff2f8a1fd2a660208111b6ba83849b24fefc5d/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

**Comment by baibaichen** [comment]
For [line 248](https://github.com/ClickHouse/ClickHouse/blame/b6cfba33f196d03be7dd10f848d37580b37d1d8a/src/Processors/QueryPlan/Optimizations/filterPushDown.cpp#L248), do you think it is right?  In case of FilledJoinStep, `sizeof(child->getInputStreams()) == 1` which menas `left_stream_input_header == right_stream_input_header`

```cpp
const auto & right_stream_input_header = child->getInputStreams().back().header;
```

`allow_push_down_to_right` may fix crash, but the current implementation would fail at collecting equivalent set.  when there is a filter on right column, e.g.

```sql
select * from t1, t2 where t1.id= t2.id and t2.id > 100
````

In this case, I guess there is no optimaztion, but it should be transformed to:

```sql
select * from t1, t2 where t1.id= t2.id and t1.id > 100
````

**Review by vdimir — APPROVED** [review]
👍

**Comment by kitaisreal** [comment]
> For [line 248](https://github.com/ClickHouse/ClickHouse/blame/b6cfba33f196d03be7dd10f848d37580b37d1d8a/src/Processors/QueryPlan/Optimizations/filterPushDown.cpp#L248), do you think it is right? In case of FilledJoinStep, `sizeof(child->getInputStreams()) == 1` which menas `left_stream_input_header == right_stream_input_header`
> 
> ```c++
> const auto & right_stream_input_header = child->getInputStreams().back().header;
> ```
> 
> `allow_push_down_to_right` may fix crash, but the current implementation would fail at collecting equivalent set. when there is a filter on right column, e.g.
> 
> ```sql
> select * from t1, t2 where t1.id= t2.id and t2.id > 100
> ```
> 
> In this case, I guess there is no optimaztion, but it should be transformed to:
> 
> ```sql
> select * from t1, t2 where t1.id= t2.id and t1.id > 100
> ```

Yes, it is expected that optimization will not work with FilledJoin for now.

**Pull request merged**
