### PR TITLE
krb5 + cyrus-sasl + kerberized kafka

### PR DESCRIPTION
**Pull request by ilejn**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- New Feature

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Support Kerberos authentication in Kafka, using `krb5` and `cyrus-sasl` libraries.

Detailed description / Documentation draft:

Kafka is Kerberos aware now,
krb5 library and cyrus-sasl (AKA libsasl2) added to contrib to make it possible.

kafka/security_protocol section should be added to config.xml

By adding documentation, you'll allow users to try your new feature immediately, not when someone else will have time to document it later. Documentation is necessary for all features that affect user experience in any way. You can add brief documentation draft above, or add documentation right into your patch as Markdown files in [docs](https://github.com/ClickHouse/ClickHouse/tree/master/docs) folder.

If you are doing this for the first time, it's recommended to read the lightweight [Contributing to ClickHouse Documentation](https://github.com/ClickHouse/ClickHouse/tree/master/docs/README.md) guide first.

### CODE REVIEW

**Comment by filimonov** [comment]
Any progress with the integration test?

**Comment by traceon** [comment]
Have you checked that, in the generated header files (at least for Linux), the set of enabled flags is compatible with those that would be enabled if you generated/configured the libs in a typical Ubuntu and CentOS/RedHat, and the oldest Ubuntu being 14? Will the libs be enabled in macOS and FreeBSD builds? Will the generated headers work for such builds? For AArch64 Linux?

**Comment by akonyaev90** [comment]
I'm not sure if we can check the assembly on all the above systems at all.

**Comment by traceon** [comment]
Ubuntu 8.04
CentOS 5
FreeBSD 11

**Comment by ilejn** [comment]
> Have you checked that, in the generated header files (at least for Linux), the set of enabled flags is compatible with those that would be enabled if you generated/configured the libs in a typical Ubuntu and CentOS/RedHat, and the oldest Ubuntu being 14? Will the libs be enabled in macOS and FreeBSD builds? Will the generated headers work for such builds? For AArch64 Linux?
krb5 support is disabled for any platform but Linux.
Regarding ubuntu 14, no, it was not tested.

**Comment by traceon** [comment]
Ubuntu 8.04
CentOS 5
FreeBSD 11

The binary of ClickHouse is generally expected to work in at least these versions. No need to build ClickHouse there, but the hardcoded config headers of third-party libs should enable/disable features in a way that will produce a binary that is runnable on at least these versions of the systems

**Comment by traceon** [comment]
And, in case of aarch64 Linux, they are built and run in a relatively recent Ubuntu.

**Comment by traceon** [comment]
In case of macOS, no lower limit that I know of, but a working build with those libs enabled would be nice to have too.

**Comment by ilejn** [comment]
> Ubuntu 8.04
> CentOS 5
> FreeBSD 11
> 
> The binary of ClickHouse is generally expected to work in at least these versions. No need to build ClickHouse there, but the hardcoded config headers of third-party libs should enable/disable features in a way that will produce a binary that is runnable on at least these versions of the systems

As far as I understand, running against Ubuntu 12 is a part of tests, so it is Ok.
For non-Linux nothing changed.

**Comment by acmnu** [comment]
@traceon Could you please provide a document with exact list of supported OS and Distros?

**Comment by traceon** [comment]
From what I know:

ClickHouse must be buildable on:
- all oses/distros/arches/configs from CI (can be verified by looking at CI checks on PR)

ClickHouse must be runnable on:
- all os/distros/arches from CI (can be verified by looking at CI checks on PR)
- Ubuntu 8.04 x86_64 and above
- CentOS 5 x86_64 and above
- FreeBSD 11 x86_64 and above

The exact table of platforms and configurations available at `ClickHouse build check > Details` in the list of PR checks. CI environments include Ubuntu 19.10 with various versions of GCC and Clang, x86_64 and aarch64, as well as FreeBSD and macOS.

All being said, the functionality/lib can be restricted to some well-defined subset of target platforms and configurations. It is just that nothing should be broken anywhere.

**Comment by ilejn** [comment]
@traceon we willingly check the thing against any platform/os, while I am not sure that I understand what is wrong with CI tests that are already passed.
In https://clickhouse-test-reports.s3.yandex.net/12771/ff92812ac57d59e9c43cc90b93c0048630304ebe/compatibility_check.html one can see that centos:5 and ubuntu:12.04 marked as "OK". 
Must we check against 8.04 which is not listed?
What else?
Thanks.

**Comment by traceon** [comment]
@ilejn I am not saying there is anything wrong with tests or the code. Just what is the state of the codebase should be in before and after this PR is merged.

Also, the rule of thumb for any new functionality - it should be covered with at least some tests, that show that the changes actually have some positive effect.

I am very enthusiastic about this PR, that's why I try to cover as many blind spots as possible.

**Comment by ilejn** [comment]
@traceon I agree that we need an integration test that covers new functionality (and it will be done).
I agree that added functionality should be available on all platforms and I suggest doing this outside of this PR.
I don't quite follow you regarding other points. Could you list platforms/OSes/whatever [not covered by passed CI tests] to ensure that the system is buildable and runnable?

**Comment by traceon** [comment]
> ClickHouse must be runnable on:
> 
>    - ...
>    - Ubuntu 8.04 x86_64 and above (when built on **any** x86_64 Linux and linked statically with third-parties and runtime)
>    - CentOS 5 x86_64 and above (when built on **any** x86_64 Linux and linked statically with third-parties and runtime)
>    - FreeBSD 11 x86_64 and above

@ilejn These three cases are not covered in CI, I believe.

Also, could you please formally list all platforms+configurations where the libs will be enabled, in the description?

**Comment by ilejn** [comment]
@traceon , Ok, we can ignore https://clickhouse-test-reports.s3.yandex.net/12771/ff92812ac57d59e9c43cc90b93c0048630304ebe/compatibility_check.html (e.g. because we do not know what "OK" means) and ensure that the branch is
* runnable on  Ubuntu 8.04 x86_64 when built on Ubuntu 20.04
* runnable on  CentOS 5 x86_64 when built on Ubuntu 20.04
* runnable on  FreeBSD 11 x86_64 when build on some_recent_FreeBSD
Is it enough from your point of view? 
If not, what should be done?

**Comment by traceon** [comment]
Sounds good to me.

**Review by alexey-milovidov — APPROVED** [review]
LGTM, let's add a test and merge.

**Comment by acmnu** [comment]
@traceon If we have a number of OS to support, do we have a build and post build test on CI for such OS? I am wondering why we need to check it by hands?

**Comment by traceon** [comment]
@acmnu not all target platforms are covered in CI right now.

**Comment by alexey-milovidov** [comment]
No, you don't have to support anything that is not covered by CI.
You don't have to test any other OS by hand.
If CI is green, we will merge it :)

And now only the test remain.

**Comment by alexey-milovidov** [comment]
Kafka support is currently disabled on FreeBSD x86_64 and Linux AArch64.

**Comment by alexey-milovidov** [comment]
You can see the logs of all builds here: https://clickhouse-builds.s3.yandex.net/12771/ff92812ac57d59e9c43cc90b93c0048630304ebe/clickhouse_build_check/report.html

**Comment by filimonov** [comment]
It looks like it supersedes https://github.com/ClickHouse/ClickHouse/pull/5253 
And most probably librdkafka don't need libgsasl anymore.

**Pull request merged**
