### PR TITLE
Fix attach MV in Atomic database

### PR DESCRIPTION
**Pull request by tavplubix**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fixed `Table .inner_id... doesn't exist` error when selecting from Materialized View after detaching it from Atomic database and attaching back. 

Detailed description / Documentation draft:
The issue introduced in #21535, 21.4 is affected.

### CODE REVIEW

**Comment by tavplubix** [comment]
Stress test (thread) - segfault on `_exit`

**Comment by tavplubix** [comment]
Stress test (undefined) - #23084
Yandex synchronization check - broken in master

**Review by nikitamikhaylov — APPROVED** [review]

**Comment by r3b-fish** [comment]
@tavplubix Can you include it into 21.3? I've caught this problem for 21.3.11 version. Many thanks

**Comment by tavplubix** [comment]
> @tavplubix Can you include it into 21.3? I've caught this problem for 21.3.11 version. Many thanks

The problem appeared in 21.4 after 3c0f5a57ec6506b18636a1e8137325c800960ea5 was merged. Probably you caught another problem. Could you please create issue with detailed bug report?

**Review by HeenaBansal2009 — COMMENTED** [review]
The attach mv is throwing error in case last attach mv was  unsuccesful/threw exception for any reasons with same  inner UUID.

Steps to reproduce:  Tetscase :  tests/queries/0_stateless/01153_attach_mv_uuid.sql
Update the line#29 - modify UUID 'e15f3ab5-6cae-4df3-b879-f40deafd82c2' to 3bd68e3c-2693-4352-ad66-a66eba9e345e. and execute the test - It should throw exception which is expected , table cannot point to itself. 

- Now execute the actual test case after removing  updations, it will fail with error - TABLE already exist with datastore/3bd68e3c-2693-4352-ad66-a66eba9e345e

**Pull request merged**
