### PR TITLE
Add missing UInt128 (UUID) field visitors

### PR DESCRIPTION
**Pull request by simPod**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

TBH, I have just a little idea what I have done here but I tried to address those https://github.com/yandex/ClickHouse/issues/1770, https://github.com/yandex/ClickHouse/issues/2611

It is not possible to use UUID in WHERE condition. I tried to implement it but need help with that. Not sure if the way I have tried to do this is the right way and whether I should continue, until I resolve all errors or whether it needs another solution.

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
That looks mostly correct.

Only few issues remain:
1. I cannot find implementation of `FieldVisitorToString` for `UInt128`. That will likely require some effort.
2. Comparison (less/greater) operators for UInt128 may work even with your implementation (that returns false when comparing with other integer type) but it will confuse index when user write something like `x > 1` where x is UInt128. Better to provide correct implementation from the beginning.

**Review by alexey-milovidov — CHANGES_REQUESTED** [review]
.

**Comment by simPod** [comment]
1) it's implemented in https://github.com/yandex/ClickHouse/blob/master/dbms/src/Functions/FunctionsCoding.h#L893, cannot it be somehow leveraged?
2) hm, I'm afraid I'm out of skill for that, first time editing C code. Maybe someone can cherrypick and continue the work here?

**Comment by alexey-milovidov** [comment]
The implementation is still incomplete, but it is better than nothing and now #2611 is fixed.

**Pull request merged**
