### PR TITLE
Simplify init script

### PR DESCRIPTION
**Pull request by alexey-milovidov**
Changelog category (leave one):
- Build/Testing/Packaging Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Simplify Sys/V init script.

### CODE REVIEW

**Comment by alesapin** [comment]
A very strange thing happened in docker while binary installed using clickhouse install:
```
root@click:/# whoami
root
root@click:/# ls -laF /usr/bin/clickhouse
-r-xr-xr-x 1 root root 299278344 Oct 20 17:00 /usr/bin/clickhouse*
root@click:/# /usr/bin/clickhouse
bash: /usr/bin/clickhouse: Operation not permitted
root@click:/# chmod 777 /usr/bin/clickhouse
chmod: changing permissions of '/usr/bin/clickhouse': Operation not permitted
root@click:/# ls -la /usr/bin/clickhouse.old  
-rwxr-xr-x 1 root root 299278344 Oct 19 15:58 /usr/bin/clickhouse.old
root@click:/# chattr -R +i /usr/bin/clickhouse
root@click:/# /usr/bin/clickhouse
bash: /usr/bin/clickhouse: Operation not permitted
root@click:/# cp /usr/bin/clickhouse /usr/bin/clickhouse1
root@click:/# /usr/bin/clickhouse1
Use one of the following commands:
clickhouse local [args] 
clickhouse client [args] 
clickhouse benchmark [args] 
clickhouse server [args] 
clickhouse extract-from-config [args] 
clickhouse compressor [args] 
clickhouse format [args] 
clickhouse copier [args] 
clickhouse obfuscator [args] 
clickhouse install [args] 
clickhouse start [args] 
clickhouse stop [args] 
clickhouse status [args] 
clickhouse restart [args] 
root@click:/# chmod -R 777 /usr/bin/
chmod: changing permissions of '/usr/bin/clickhouse': Operation not permitted
```

**Comment by alexey-milovidov** [comment]
```
Alexey Milovidov, [20.10.20 19:28]
[In reply to Alexander Sapin]
Capabilities.

Alexey Milovidov, [20.10.20 19:28]
Если Docker не имеет capabilities, а бинарник имеет fs атрибут с capabilities, то ядро ОС отказывается его запускать.

Alexey Milovidov, [20.10.20 19:28]
cp сбрасывает эти атрибуты.
```

**Comment by alexey-milovidov** [comment]
We need to incorporate a check that capabilities are working (we have this check in init script).

**Comment by alexey-milovidov** [comment]
I'll do it.

**Comment by alexey-milovidov** [comment]
Wow, it's fixed.

**Pull request merged**
