### PR TITLE
FastFloat library integration

### PR DESCRIPTION
**Pull request by kitaisreal**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- New Feature

Mentioned in https://github.com/ClickHouse/ClickHouse/issues/16746.

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Use https://github.com/lemire/fast_float to parse floating point numbers.

### CODE REVIEW

**Comment by kitaisreal** [comment]
@alexey-milovidov after investigation and trying different tactics it seems that our implementation is good enough to not be replaced.
I forked library benchmark repository https://github.com/kitaisreal/simple_fastfloat_benchmark added our implementation https://github.com/kitaisreal/simple_fastfloat_benchmark/tree/master/ffloat (I removed db dependencies and wrapped in std::from_chars). After running benchmarks:
```
~/Documents/simple_fastfloat_benchmark/data$ ./run_bench.sh
File: canada.txt
# read 111126 lines
volume = 1.93374 MB
fastfloat                               :   788.73 MB/s (+/- 2.6 %)    45.33 Mfloat/s
ffloat                                  :   649.93 MB/s (+/- 2.9 %)    37.35 Mfloat/s
File: mesh.txt
# read 73019 lines
volume = 0.536009 MB
fastfloat                               :   543.85 MB/s (+/- 7.5 %)    74.09 Mfloat/s
ffloat                                  :   492.17 MB/s (+/- 8.6 %)    67.05 Mfloat/s
File: numbers10.tsv
# read 10000 lines
volume = 0.749475 MB
fastfloat                               :   537.89 MB/s (+/- 1.5 %)     7.18 Mfloat/s
ffloat                                  :  1001.78 MB/s (+/- 2.6 %)    13.37 Mfloat/s
File: numbers1.tsv
# read 10000 lines
volume = 0.0370884 MB
fastfloat                               :   358.27 MB/s (+/- 3.2 %)    96.60 Mfloat/s
ffloat                                  :   420.52 MB/s (+/- 4.6 %)   113.38 Mfloat/s
File: numbers2.tsv
# read 10000 lines
volume = 0.00953674 MB
fastfloat                               :    97.91 MB/s (+/- 9.6 %)   102.67 Mfloat/s
ffloat                                  :   123.82 MB/s (+/- 5.5 %)   129.84 Mfloat/s
File: numbers3.tsv
# read 10000 lines
volume = 0.0466156 MB
fastfloat                               :   353.91 MB/s (+/- 6.1 %)    75.92 Mfloat/s
ffloat                                  :   273.33 MB/s (+/- 28.7 %)    58.63 Mfloat/s
File: numbers4.tsv
# read 10000 lines
volume = 0.159668 MB
fastfloat                               :   644.22 MB/s (+/- 4.5 %)    40.35 Mfloat/s
ffloat                                  :   723.07 MB/s (+/- 3.6 %)    45.29 Mfloat/s
File: numbers5.tsv
# read 10000 lines
volume = 0.166648 MB
fastfloat                               :   662.02 MB/s (+/- 5.0 %)    39.73 Mfloat/s
ffloat                                  :   549.47 MB/s (+/- 3.9 %)    32.97 Mfloat/s
File: numbers6.tsv
# read 10000 lines
volume = 0.164088 MB
fastfloat                               :   779.12 MB/s (+/- 5.7 %)    47.48 Mfloat/s
ffloat                                  :   586.74 MB/s (+/- 4.2 %)    35.76 Mfloat/s
File: numbers7.tsv
# read 10000 lines
volume = 0.202391 MB
fastfloat                               :   802.09 MB/s (+/- 5.7 %)    39.63 Mfloat/s
ffloat                                  :   585.11 MB/s (+/- 4.1 %)    28.91 Mfloat/s
File: numbers8.tsv
# read 10000 lines
volume = 0.190425 MB
fastfloat                               :   616.12 MB/s (+/- 22.8 %)    32.36 Mfloat/s
ffloat                                  :   523.45 MB/s (+/- 1.9 %)    27.49 Mfloat/s
File: numbers9.tsv
# read 10000 lines
volume = 0.739889 MB
fastfloat                               :   450.72 MB/s (+/- 1.8 %)     6.09 Mfloat/s
ffloat                                  :  1315.71 MB/s (+/- 2.2 %)    17.78 Mfloat/s
```
Seems like our implementation better prepared for long integers. It is important that this is natural interface for the library. When I integrated it in our code, we have a problem with case when part of the double is before buffer eof() and part of the double is after. I moved this into slow path, it seems like a big performance penalty.
After running our benchmarks using read_float_perf:
```
~/Documents/simple_fastfloat_benchmark/data$ ./run_float_perf.sh
File: canada.txt
Fast parse:
Read in 0.005112386 sec, 398.98 MiB/sec, result = -1265531.108883936
Fast parse with fast float:
Read in 0.003949107 sec, 516.50 MiB/sec, result = -1265531.108883936
File: mesh.txt
Fast parse:
Read in 0.001611012 sec, 375.94 MiB/sec, result = 15401544847793.945
Fast parse with fast float:
Read in 0.001584565 sec, 382.22 MiB/sec, result = 15401544847793.945
File: numbers10.tsv
Fast parse:
Read in 0.001238018 sec, 613.09 MiB/sec, result = 4.7152462480420073e42
Fast parse with fast float:
Read in 0.001787954 sec, 424.51 MiB/sec, result = 4.7152462480420073e42
File: numbers1.tsv
Fast parse:
Read in 0.000143075 sec, 325.88 MiB/sec, result = 49995000
Fast parse with fast float:
Read in 0.000172441 sec, 270.38 MiB/sec, result = 49995000
File: numbers2.tsv
Fast parse:
Read in 0.000086215 sec, 221.23 MiB/sec, result = 45000
Fast parse with fast float:
Read in 0.000155976 sec, 122.28 MiB/sec, result = 45000
File: numbers3.tsv
Fast parse:
Read in 0.000283894 sec, 197.79 MiB/sec, result = 49995
Fast parse with fast float:
Read in 0.000210597 sec, 266.63 MiB/sec, result = 49995
File: numbers4.tsv
Fast parse:
Read in 0.000303751 sec, 557.05 MiB/sec, result = 92140704191895290000
Fast parse with fast float:
Read in 0.000403999 sec, 418.82 MiB/sec, result = 92140704191895290000
File: numbers5.tsv
Fast parse:
Read in 0.000452072 sec, 389.73 MiB/sec, result = 21574771604078.355
Fast parse with fast float:
Read in 0.000420278 sec, 419.21 MiB/sec, result = 21574771604078.355
File: numbers6.tsv
Fast parse:
Read in 0.000425745 sec, 407.81 MiB/sec, result = 433667.1503822466
Fast parse with fast float:
Read in 0.000395998 sec, 438.45 MiB/sec, result = 433667.1503822466
File: numbers7.tsv
Fast parse:
Read in 0.000551018 sec, 384.61 MiB/sec, result = 9.838779301758295e-15
Fast parse with fast float:
Read in 0.000443136 sec, 478.24 MiB/sec, result = 9.838779301758295e-15
File: numbers8.tsv
Fast parse:
Read in 0.000564376 sec, 354.31 MiB/sec, result = 6.383256477037832e112
Fast parse with fast float:
Read in 0.000460129 sec, 434.58 MiB/sec, result = 6.383256477037832e112
File: numbers9.tsv
Fast parse:
Read in 0.001087419 sec, 689.18 MiB/sec, result = 1.1604469425489605e82
Fast parse with fast float:
Read in 0.00188841 sec, 396.86 MiB/sec, result = 1.1604469425489605e82
```
Probably slow path can be optimized. What do you think ?

**Comment by alexey-milovidov** [comment]
We can have a shortcut when enough number of digits fits in buffer - similar to `readDateTimeTextImpl`/`readDateTimeTextFallback`.

About performance comparison... I see that sometimes fastfloat is better sometimes it's worse.
But it is 100% precise and our implementation is precise up to 1 bit for Float32 and slightly worse for Float64.

Let's first replace the `readFloatTextPrecise`.
Then we can quickly test by switching default implementation from "fast" to "precise".

And then maybe we can introduce some changes in fastfloat to make it always faster...

**Comment by alexey-milovidov** [comment]
PS. The ability to parse floats that are actually integers as fast as possible is very valuable... because users often use floats for everything and "everything" is integers most of the times.

**Comment by kitaisreal** [comment]
@alexey-milovidov conditionally replaced precise parsing with fast_float library.
Benchmarks
```
~/Documents/simple_fastfloat_benchmark/data$ ./run_float_perf.sh
File: canada.txt
Parse presice:
Read in 0.01694127 sec, 120.40 MiB/sec, result = -1265531.108883936
Fast parse with fast float:
Read in 0.00368945 sec, 552.85 MiB/sec, result = -1265531.108883936
File: mesh.txt
Parse presice:
Read in 0.004869441 sec, 124.38 MiB/sec, result = 15401544847793.945
Fast parse with fast float:
Read in 0.001626553 sec, 372.35 MiB/sec, result = 15401544847793.945
File: numbers10.tsv
Parse presice:
Read in 0.002662068 sec, 285.12 MiB/sec, result = 4.7152462480420073e42
Fast parse with fast float:
Read in 0.001853542 sec, 409.49 MiB/sec, result = 4.7152462480420073e42
File: numbers1.tsv
Parse presice:
Read in 0.000662005 sec, 70.43 MiB/sec, result = 49995000
Fast parse with fast float:
Read in 0.000202383 sec, 230.38 MiB/sec, result = 49995000
File: numbers2.tsv
Parse presice:
Read in 0.000576887 sec, 33.06 MiB/sec, result = 45000
Fast parse with fast float:
Read in 0.000172666 sec, 110.46 MiB/sec, result = 45000
File: numbers3.tsv
Parse presice:
Read in 0.000663645 sec, 84.61 MiB/sec, result = 49995
Fast parse with fast float:
Read in 0.000224175 sec, 250.48 MiB/sec, result = 49995
File: numbers4.tsv
Parse presice:
Read in 0.001676668 sec, 100.92 MiB/sec, result = 92140704191895290000
Fast parse with fast float:
Read in 0.000481196 sec, 351.63 MiB/sec, result = 92140704191895290000
File: numbers5.tsv
Parse presice:
Read in 0.001717569 sec, 102.58 MiB/sec, result = 21574771604078.355
Fast parse with fast float:
Read in 0.00044318 sec, 397.55 MiB/sec, result = 21574771604078.355
File: numbers6.tsv
Parse presice:
Read in 0.001637656 sec, 106.02 MiB/sec, result = 433667.1503822466
Fast parse with fast float:
Read in 0.000448926 sec, 386.76 MiB/sec, result = 433667.1503822466
File: numbers7.tsv
Parse presice:
Read in 0.00181053 sec, 117.05 MiB/sec, result = 9.838779301758295e-15
Fast parse with fast float:
Read in 0.000426369 sec, 497.05 MiB/sec, result = 9.838779301758295e-15
File: numbers8.tsv
Parse presice:
Read in 0.001830192 sec, 109.26 MiB/sec, result = 6.383256477037832e112
Fast parse with fast float:
Read in 0.000507464 sec, 394.04 MiB/sec, result = 6.383256477037832e112
File: numbers9.tsv
Parse presice:
Read in 0.002712182 sec, 276.32 MiB/sec, result = 1.1604469425489605e82
Fast parse with fast float:
Read in 0.001903037 sec, 393.81 MiB/sec, result = 1.1604469425489605e82
```
Related to slow path optimization, my current implementation seems like an optimal solution, I tried several different ones, but only way we can make it faster is to allocate this buffer on stack with some fixed limit MAX_LENGTH, like it is done for precise parsing but from my perspective this can lead to errors and from performance point we can go with dynamic buffer.

**Comment by kitaisreal** [comment]
Also we need to wait until https://github.com/lemire/fast_float/pull/24 will be merged, because currently we will have problems on CI with ODR violations.

**Comment by alexey-milovidov** [comment]
Ok. BTW, do you have Telegram? Could you please contact me at @milovidov_an?

**Comment by kitaisreal** [comment]
@alexey-milovidov Yes. contacted you.

**Comment by lemire** [comment]
1. The `fast_float` library has not been optimized for parsing integer values. It is not a difficult case and we could do better. I was unaware that people cared for this case, but the arguments that you are raising are good. Of course, one must be mindful that 64-bit floats can't represent all 64-bit integers. 

2. The true value of a library like `fast_float` is to offer *exact* parsing (down to the smallest bit). If that is not important to you, you can go even faster...

**Comment by alexey-milovidov** [comment]
> The true value of a library like fast_float is to offer exact parsing (down to the smallest bit). If that is not important to you, you can go even faster...

It depends on how faster we can go with slightly less precise result. If it can be two times faster, we would like to keep imprecise variant by default. If 1.5 times - maybe better to always use precise implementation.

**Comment by lemire** [comment]
@alexey-milovidov This is very reasonable.

My belief is that once you have optimized the correct function (for example, fast_float), you can be well within the 1.5x factor. I could be wrong. If I am wrong, I'd be interested in finding that out.

**Comment by kitaisreal** [comment]
@alexey-milovidov should we make this default replacement for our precise formatting ? Without introducing conditional cmake variable ```USE_FAST_FLOAT``` ?

**Comment by alexey-milovidov** [comment]
Yes, let's make it the default unconditionally (at least for precise parsing).

**Comment by lemire** [comment]
Version 0.2.0 of fast_float is out:

https://github.com/lemire/fast_float/releases/tag/v0.2.0

Release notes:

- Support for Big Endian systems
- Build with pedantic flags under GNU GCC without warnings
- More standard compliant handling of problematic strings (issue19)

**Comment by kitaisreal** [comment]
@alexey-milovidov this AST fuzzer and Testflows check is the reason in this branch, or rebase with master should fix that ?

**Comment by lemire** [comment]
I am not expecting problems with fast_float, but if you do find an issue, please let me know. I will be glad to investigate.

**Comment by lemire** [comment]
We just published version 0.3.0:

- Better support for 32-bit systems 
- Removed iostream dependency 
- The algorithmic fast paths are more common
- Adopted slightly faster SWAR code

The repository moved to https://github.com/fastfloat/fast_float

**Comment by kitaisreal** [comment]
@alexey-milovidov changed submodule to new fast float repository. Also updated float precise parsing implementation to use fast_float by default.

**Review by alexey-milovidov — APPROVED** [review]

**Pull request merged**
