### PR TITLE
Add more tests for modulo of division of negative number

### PR DESCRIPTION
**Pull request by hexiaoting**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Not for changelog

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Enlarge signed type for modulo function when operator includes signed type. related issue: https://github.com/ClickHouse/ClickHouse/issues/20052
eg : Int32 % UInt8 returns Int32

### CODE REVIEW

**Comment by zhangjmruc** [comment]
Do we need to limit the fix to cases where type A is signed and type B is usigned?

**Comment by hexiaoting** [comment]
It seems that my result is wrong?
@zhangjmruc 
-199 % 200 should be 1 ? 
-199 % -200 should be -199 ?

**Comment by alexey-milovidov** [comment]
@hexiaoting I am preparing the same fix at this time.
It looks like this:

```
-/** Division with remainder you get a number with the same number of bits as in divisor.
-    */
+/** Division with remainder you get a number with the same number of bits as in divisor,
+  * or larger in case of signed type.
+  */
 template <typename A, typename B> struct ResultOfModulo
 {
-    using Type0 = typename Construct<is_signed_v<A> || is_signed_v<B>, false, sizeof(B)>::Type;
+    static constexpr bool result_is_signed = is_signed_v<A> || is_signed_v<B>;
+    /// If modulo of division can yield negative number, we need larger type to accomodate it.
+    /// Example: toInt32(-199) % toUInt8(200) will return -199 that does not fit in Int8, only in Int16.
+    static constexpr size_t size_of_result = result_is_signed ? nextSize(sizeof(B)) : sizeof(B);
+    using Type0 = typename Construct<result_is_signed, false, size_of_result>::Type;
```

(more comments and different logic)

Could you please review and add my fix,
we will keep your test and merge your PR.

**Comment by alexey-milovidov** [comment]
@hexiaoting It is slightly more complicated because different programming languages and database may use different definitions of modulo of division.

In most of mathematical applications, the result of modulo of division by x always falls into [0, x).
`-1 % 100 = 99`

But there is also "T-divison", where `-x % y = -(x % y)`.
`-1 % 100 = -1`

Examples:

```
$ python
Python 2.7.18 (default, Aug  4 2020, 11:16:42) 
[GCC 9.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> -1 % 100
99
```

```
$ node
> -1 % 100
-1
```

```
$ perl -e 'print -1 % 100'
99
```

```
$ php -r 'echo -1 % 100;'
-1
```

```
Go:

package main

import (
	"fmt"
)

func main() {
	fmt.Println("Hello, playground {}", -1 % 100)
}

Hello, playground {} -1
```

C++
```
$ clang++ -xc++ -include iostream - <<< "int main() { std::cerr << (-1 % 100) << '\n'; }" && ./a.out
-1
```

SQLite:
http://sqlfiddle.com/#!5/0a28f18/33

PostgreSQL:
http://sqlfiddle.com/#!17/0a28f/375

Rust:
```
fn main() {
    println!("{}", -1 % 100);
}

-1
```
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=2115d16866200015e6b6281e4e31325e

SQL standard:
no idea

ClickHouse:
Should use whatever has the most efficient implementation on modern CPUs.

**Comment by hexiaoting** [comment]
@alexey-milovidov You are so nice, Thank you very much. I will add your fix into my pr.

**Comment by alexey-milovidov** [comment]
I just merged my PR (and also I applied one change to it). You can either: - close; - rebase to master so we can merge more tests.

**Comment by hexiaoting** [comment]
@alexey-milovidov   I have added more tests.

**Review by alexey-milovidov — APPROVED** [review]

**Pull request merged**
