### PR TITLE
Increase the threshold of smt/none_smt to improve the performance

### PR DESCRIPTION
**Pull request by jiebinn**
Current threshold of smt/none_smt is 32. I have tuned the performance with Clickbench on 80x2 vCPUs system. If the total vCPUs is larger than 64, the performance would be better without smt. The patch means that while the vCPUs of system is between 32 and 64, we may still use smt to improve the performance.

image

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/jiebinsu/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/jiebinsu/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

  | Geomean of Clickbench |  
-- | -- | --
number of vCPUs | use_vCPUs | use_physical_cores | use_physical_cores/use_vCPUs
16 | 5.79 | 4.71 | 81.3%
32 | 8.38 | 7.40 | 88.3%
48 | 9.48 | 8.81 | 93.0%
64 | 9.93 | 9.76 | 98.2%
80 | 9.63 | 10.25 | 106.3%
96 | 10.13 | 10.92 | 107.9%
112 | 10.28 | 11.59 | 112.7%
128 | 10.46 | 12.00 | 114.7%
144 | 10.42 | 12.09 | 116.0%
160 | 10.60 | 11.93 | 112.5%

</body>

</html>

### Changelog category (leave one):
- Performance Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Increase the threshold of smt/none_smt to improve the performance

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Run only fuzzers related jobs (libFuzzer fuzzers, AST fuzzers, etc.)
- [ ]  Exclude: AST fuzzers
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by nickitat** [comment]
i have some troubles reading this data. shouldn't we aim for lower geomean? and it looks that using physical cores is beneficial for smaller number of cpus, which contradicts https://github.com/jiebinn/ClickHouse/blob/getNumberOfPhysicalCPUCores/src/Common/getNumberOfPhysicalCPUCores.cpp#L177-L178

**Comment by qoega** [comment]
It looks as finetuning for ClickBench of some hardware.
I can recommend to convert this constant to a server setting so user can tune it for their system/workload and we can check it easily for same binary/hardware for more test scenarios

**Comment by jiebinn** [comment]
> i have some troubles reading this data. shouldn't we aim for lower geomean? and it looks that using physical cores is beneficial for smaller number of cpus, which contradicts https://github.com/jiebinn/ClickHouse/blob/getNumberOfPhysicalCPUCores/src/Common/getNumberOfPhysicalCPUCores.cpp#L177-L178

No, we're trying to get higher QPS for the 43 queries, which means higher geometric mean of these queries. Using physical cores will benefit the performance in large core system(core # >= 64).

**Comment by jiebinn** [comment]
> It looks as finetuning for ClickBench of some hardware. I can recommend to convert this constant to a server setting so user can tune it for their system/workload and we can check it easily for same binary/hardware for more test scenarios
I agree with that and that's a good idea. I have verified the data on two different systems. Maybe we could also update the default value.

**Comment by jiebinn** [comment]
@nickitat I have attached the snapshot and sorry for the convenience.
image
image

**Comment by nickitat** [comment]
1. i don't mind if we update the default. previously afaiu we also changed this default based on very limited amount of observations. now we have at least some data.
2. i also think that it will be better to make it controllable by a server-wide setting

**Comment by robot-ch-test-poll3** [comment]
*This is an automated comment for commit ea190fa699ec770c1c56467ebe3c62265afad53b with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/69548/ea190fa699ec770c1c56467ebe3c62265afad53b/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/69432/6f9d1631e26bbb0263962c6d50c65e9ee2be561a/docs_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Comment by jiebinn** [comment]
> 1. i don't mind if we update the default. previously afaiu we also changed this default based on very limited amount of observations. now we have at least some data.
> 2. i also think that it will be better to make it controllable by a server-wide setting

Sure. Thanks for your suggestion.

**Comment by jiebinn** [comment]
CI passed. @nickitat Could you help to review the PR?

**Review by alexey-milovidov — CHANGES_REQUESTED** [review]
The function name `getNumberOfPhysicalCPUCoresImpl` became incorrect (even before this pull request). Let @nickitat think on how to deal with it.

**Comment by alexey-milovidov** [comment]
Overall, it is a very obscure feature, with a high chance of being forgotten and unused. Maybe just not do it?

**Comment by alexey-milovidov** [comment]
The testing is valuable and the results are interesting!

I think the added code is not worth it, that's why we have to close it.

**Comment by jiebinn** [comment]
Hi @alexey-milovidov , based on the testing data, could we just change the default value from 32 to 64 and keep the other the same?

**Comment by alexey-milovidov** [comment]
Yes, let's change to 64.

**Comment by jiebinn** [comment]
Thanks, I will submit another PR for that.

**Comment by jiebinn** [comment]
> Thanks, I will submit another PR for that.

https://github.com/ClickHouse/ClickHouse/pull/70111

**Comment by nickitat** [comment]
> The function name `getNumberOfPhysicalCPUCoresImpl` became incorrect (even before this pull request). Let @nickitat think on how to deal with it.

lets rename it ) https://github.com/ClickHouse/ClickHouse/pull/70130

**Pull request closed without merging**
