### PR TITLE
Strict parsing in keeper client

### PR DESCRIPTION
**Pull request by alexey-milovidov**
### Changelog category (leave one):
- Backward Incompatible Change

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
`clickhouse-keeper-client` will only accept paths in string literals, such as `ls '/hello/world'`, not bare strings such as `ls /hello/world`.

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-clickhouse-ci-1** [comment]
*This is an automated comment for commit a447a25a9d779693e329cd743309b067a5ab1c00 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/65494/a447a25a9d779693e329cd743309b067a5ab1c00/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Cloud fork sync (only for ClickHouse Inc. employees)</td><td>If it fails, ask a maintainer for help</td><td>⏳ pending</td></tr>
<tbody>
</table>
<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>Checks correctness of the PR's body</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

**Review by antonio2368 — APPROVED** [review]
I guess it's a good way to find out if people are using `keeper-client` inside their scripts

**Comment by pufit** [comment]
Autocompletion won't work if we start the path with `'`. Also, we can turn on `skip_insignificant` here https://github.com/ClickHouse/ClickHouse/blob/master/programs/keeper-client/KeeperClient.cpp#L285 and remove all `ParserToken{TokenType::Whitespace}.ignore(pos);`.

**Comment by pufit** [comment]
Also, I'm wondering how difficult it will be to convert `ls foo` to `ls 'foo` automatically when hitting autocompletion in the interactive mode.

**Comment by azat** [comment]
Does anybody going to fix the completion?

**Comment by azat** [comment]
BTW have you considered to relax the parsing, allow old syntax? Since otherwise completion will be tricky, it will insert `'` which is always annoying, and also you will need to support two types of completion with `'` and without

**Comment by azat** [comment]
@pufit any updates? this makes client unusable

**Comment by larry-cdn77** [comment]
> but WHY it was needed? lot of users will break their scripts and will add unnecessary quoting ;(

I was curious about the motivation too only because it makes the basic commands such as ls inconsistent with ZooKeeper CLI

**Comment by alexey-milovidov** [comment]
This allowed us to find bugs in the implementation of Delta Lake table engine: https://github.com/ClickHouse/ClickHouse/pull/52503

**Comment by azat** [comment]
OK, here is initial support for completion that brings the power of keeper-client back (at least for me) - https://github.com/ClickHouse/ClickHouse/pull/78151

**Comment by Slach** [comment]
@azat god safe you ;)

**Pull request merged**
