### PR TITLE
Fix 03002_part_log_rmt_fetch_mutate_error flakiness

### PR DESCRIPTION
**Pull request by azat**
CI: https://s3.amazonaws.com/clickhouse-test-reports/61973/6cfd5b2165970a65a551117fe58e4b9d22237b8c/stateless_tests__debug__s3_storage__[3_6].html

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

#### CI Settings (Only check the boxes if you know what you are doing):
- [x]  Allow: Stateless tests

### CODE REVIEW

**Comment by robot-clickhouse-ci-1** [comment]
*This is an automated comment for commit 5d01a2f7c8b41244ecad2cbf2c7f5ed7e6113cc9 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/64887/5d01a2f7c8b41244ecad2cbf2c7f5ed7e6113cc9/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>A Sync</td><td>If it fails, ask a maintainer for help</td><td>⏳ pending</td></tr>
<tbody>
</table>
<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>Checks correctness of the PR's body</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

**Comment by azat** [comment]
>Integration tests (asan, old analyzer) [2/6] — fail: 1, passed: 393

- https://github.com/ClickHouse/ClickHouse/pull/64901

**Review by alesapin — APPROVED** [review]

**Comment by azat** [comment]
>Stateless tests (release) — fail: 1, passed: 6632, skipped: 13

- https://github.com/ClickHouse/ClickHouse/pull/64912

**Comment by azat** [comment]
@alesapin does it waits something from my side?

**Comment by azat** [comment]
@alexey-milovidov that is sad that instead of merging this PR the test was completely removed - https://github.com/ClickHouse/ClickHouse/pull/66823

Closed in favor of https://github.com/ClickHouse/ClickHouse/pull/67113

**Pull request closed without merging**
