### PR TITLE
Many fixes for CI [2]

### PR DESCRIPTION
**Pull request by nikitamikhaylov**
### Changelog category (leave one):
- Build/Testing/Packaging Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Making our CI even better.

### CODE REVIEW

**Comment by robot-clickhouse** [comment]
This is an automated comment for commit 557f433dfdb12209b002ecc76711ccb6bdea8e4f with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/51494/557f433dfdb12209b002ecc76711ccb6bdea8e4f/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Review by alexey-milovidov — APPROVED** [review]

**Comment by qoega** [comment]
- https://github.com/ClickHouse/ClickHouse/issues/51512
- https://github.com/ClickHouse/ClickHouse/pull/51434#issuecomment-1610948320
- 01293_optimize_final_force too slow with asan?  https://s3.amazonaws.com/clickhouse-test-reports/51494/1ed104417a2cb49fc3c677d9193e2b676de95d77/stateless_tests_flaky_check__asan_.html

**Review by alexey-milovidov — APPROVED** [review]

**Comment by antaljanosbenjamin** [comment]
The failing `test_ssl_cert_authentication` tests are not the same tests, but very similar ones that I fixed in https://github.com/ClickHouse/ClickHouse/pull/51434. I made same changes for the `tests_ssl_cert_authentication` tests in https://github.com/ClickHouse/ClickHouse/pull/51520.

**Comment by tavplubix** [comment]
Stress test (tsan)  - deadlock in ZooKeeper client (something new)

Postprocessed stacktraces: https://pastila.nl/?0006a09d/105f119a91f8d71dfcc5905927b7696e

The most interesting: https://pastila.nl/?00d51a61/2c0baf81d0bda74c1648feb3e35468bb

**Comment by qoega** [comment]
Screenshot 2023-06-30 at 00 58 37

**Comment by tavplubix** [comment]
@qoega, the Mergeable Check was green because some checks were still in progress

**Pull request merged**
