### PR TITLE
Remove `mmap/mremap/munmap` from Allocator.h

### PR DESCRIPTION
**Pull request by alesapin**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

### CODE REVIEW

**Comment by robot-ch-test-poll** [comment]
This is an automated comment for commit fcffe2b5a22a29e4821072df5dc3f716d3308b95 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/51686/fcffe2b5a22a29e4821072df5dc3f716d3308b95/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Comment by alesapin** [comment]
Perf improvement is noticeable. I'll  remove mmap from Allocator.

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alesapin** [comment]
After merge tons of tests are broken :(

**Comment by qoega** [comment]
Interesting failure. It is unrelated?

https://s3.amazonaws.com/clickhouse-test-reports/51686/a9978471eefbd517a37a39ccf3f22073552615c2/stress_test__tsan_.html
```
WARNING: ThreadSanitizer: signal-unsafe call inside of a signal (pid=43283)
    #0 malloc <null> (clickhouse+0xdc8da1c) (BuildId: 0c9f899fddcdb2e506f3bc8b126f3620f7fe4d9d)
    #1 __cxa_thread_atexit_impl build_docker/./contrib/llvm-project/libcxxabi/src/cxa_thread_atexit.cpp:121:42 (clickhouse+0x29024e46) (BuildId: 0c9f899fddcdb2e506f3bc8b126f3620f7fe4d9d)
    #2 __cxa_thread_atexit build_docker/./contrib/llvm-project/libcxxabi/src/cxa_thread_atexit.cpp:136:14 (clickhouse+0x290250c0) (BuildId: 0c9f899fddcdb2e506f3bc8b126f3620f7fe4d9d)
    #3 __cxx_global_var_init.6 build_docker/./src/Common/Exception.cpp (clickhouse+0x1606b052) (BuildId: 0c9f899fddcdb2e506f3bc8b126f3620f7fe4d9d)
    #4 thread-local initialization routine for DB::Exception::thread_frame_pointers build_docker/./src/Common/Exception.cpp (clickhouse+0x1606b052)
    #5 thread-local wrapper routine for DB::Exception::thread_frame_pointers CRC.cpp (clickhouse+0xdd22bbd) (BuildId: 0c9f899fddcdb2e506f3bc8b126f3620f7fe4d9d)
    #6 signalHandler(int, siginfo_t*, void*) build_docker/./src/Daemon/BaseDaemon.cpp:157:23 (clickhouse+0x16399653) (BuildId: 0c9f899fddcdb2e506f3bc8b126f3620f7fe4d9d)
    #7 __tsan::CallUserSignalHandler(__tsan::ThreadState*, bool, bool, int, __sanitizer::__sanitizer_siginfo*, void*) crtstuff.c (clickhouse+0xdc9773f) (BuildId: 0c9f899fddcdb2e506f3bc8b126f3620f7fe4d9d)
    #8 DB::abortOnFailedAssertion(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) build_docker/./src/Common/Exception.cpp:50:5 (clickhouse+0x16063fa8) (BuildId: 0c9f899fddcdb2e506f3bc8b126f3620f7fe4d9d)
    #9 DB::paranoidCheckForCoveredPartsInZooKeeperOnStart(DB::StorageReplicatedMergeTree const*, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>> const&, StrongTypedef<unsigned int, DB::MergeTreeDataFormatVersionTag>, Poco::Logger*) build_docker/./src/Storages/StorageReplicatedMergeTree.cpp:1303:13 (clickhouse+0x20721af3) (BuildId: 0c9f899fddcdb2e506f3bc8b126f3620f7fe4d9d)
    #10 DB::StorageReplicatedMergeTree::checkParts(bool) build_docker/./src/Storages/StorageReplicatedMergeTree.cpp:1313:5 (clickhouse+0x20721af3)
    #11 DB::ReplicatedMergeTreeAttachThread::runImpl() build_docker/./src/Storages/MergeTree/ReplicatedMergeTreeAttachThread.cpp:176:13 (clickhouse+0x21044ee9) (BuildId: 0c9f899fddcdb2e506f3bc8b126f3620f7fe4d9d)
    #12 DB::ReplicatedMergeTreeAttachThread::run() build_docker/./src/Storages/MergeTree/ReplicatedMergeTreeAttachThread.cpp:50:13 (clickhouse+0x210422c5) (BuildId: 0c9f899fddcdb2e506f3bc8b126f3620f7fe4d9d)
    #13 DB::ReplicatedMergeTreeAttachThread::ReplicatedMergeTreeAttachThread(DB::StorageReplicatedMergeTree&)::$_0::operator()() const build_docker/./src/Storages/MergeTree/ReplicatedMergeTreeAttachThread.cpp:19:82 (clickhouse+0x21045ec1) (BuildId: 0c9f899fddcdb2e506f3bc8b126f3620f7fe4d9d)
    #14 decltype(std::declval<DB::ReplicatedMergeTreeAttachThread::ReplicatedMergeTreeAttachThread(DB::StorageReplicatedMergeTree&)::$_0&>()()) std::__1::__invoke[abi:v15000]<DB::ReplicatedMergeTreeAttachThread::ReplicatedMergeTreeAttachThread(DB::StorageReplicatedMergeTree&)::$_0&>(DB::ReplicatedMergeTreeAttachThread::ReplicatedMergeTreeAttachThread(DB::StorageReplicatedMergeTree&)::$_0&) build_docker/./contrib/llvm-project/libcxx/include/__functional/invoke.h:394:23 (clickhouse+0x21045ec1)
    #15 void std::__1::__invoke_void_return_wrapper<void, true>::__call<DB::ReplicatedMergeTreeAttachThread::ReplicatedMergeTreeAttachThread(DB::StorageReplicatedMergeTree&)::$_0&>(DB::ReplicatedMergeTreeAttachThread::ReplicatedMergeTreeAttachThread(DB::StorageReplicatedMergeTree&)::$_0&) build_docker/./contrib/llvm-project/libcxx/include/__functional/invoke.h:479:9 (clickhouse+0x21045ec1)
    #16 std::__1::__function::__default_alloc_func<DB::ReplicatedMergeTreeAttachThread::ReplicatedMergeTreeAttachThread(DB::StorageReplicatedMergeTree&)::$_0, void ()>::operator()[abi:v15000]() build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:235:12 (clickhouse+0x21045ec1)
    #17 void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<DB::ReplicatedMergeTreeAttachThread::ReplicatedMergeTreeAttachThread(DB::StorageReplicatedMergeTree&)::$_0, void ()>>(std::__1::__function::__policy_storage const*) build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:716:16 (clickhouse+0x21045ec1)
    #18 std::__1::__function::__policy_func<void ()>::operator()[abi:v15000]() const build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:848:16 (clickhouse+0x1e28a414) (BuildId: 0c9f899fddcdb2e506f3bc8b126f3620f7fe4d9d)
    #19 std::__1::function<void ()>::operator()() const build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:1187:12 (clickhouse+0x1e28a414)
    #20 DB::BackgroundSchedulePoolTaskInfo::execute() build_docker/./src/Core/BackgroundSchedulePool.cpp:104:9 (clickhouse+0x1e28a414)
    #21 DB::BackgroundSchedulePool::threadFunction() build_docker/./src/Core/BackgroundSchedulePool.cpp:302:19 (clickhouse+0x1e28d72d) (BuildId: 0c9f899fddcdb2e506f3bc8b126f3620f7fe4d9d)
    #22 DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, char const*)::$_0::operator()() const build_docker/./src/Core/BackgroundSchedulePool.cpp:168:79 (clickhouse+0x1e28e005) (BuildId: 0c9f899fddcdb2e506f3bc8b126f3620f7fe4d9d)
    #23 decltype(std::declval<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, char const*)::$_0&>()()) std::__1::__invoke[abi:v15000]<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, char const*)::$_0&>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, char const*)::$_0&) build_docker/./contrib/llvm-project/libcxx/include/__functional/invoke.h:394:23 (clickhouse+0x1e28e005)
    #24 decltype(auto) std::__1::__apply_tuple_impl[abi:v15000]<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, char const*)::$_0&, std::__1::tuple<>&>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, char const*)::$_0&, std::__1::tuple<>&, std::__1::__tuple_indices<>) build_docker/./contrib/llvm-project/libcxx/include/tuple:1789:1 (clickhouse+0x1e28e005)
    #25 decltype(auto) std::__1::apply[abi:v15000]<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, char const*)::$_0&, std::__1::tuple<>&>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, char const*)::$_0&, std::__1::tuple<>&) build_docker/./contrib/llvm-project/libcxx/include/tuple:1798:1 (clickhouse+0x1e28e005)
    #26 ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, char const*)::$_0>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, char const*)::$_0&&)::'lambda'()::operator()() build_docker/./src/Common/ThreadPool.h:242:13 (clickhouse+0x1e28e005)
    #27 decltype(std::declval<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, char const*)::$_0>()()) std::__1::__invoke[abi:v15000]<ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, char const*)::$_0>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, char const*)::$_0&&)::'lambda'()&>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, char const*)::$_0&&) build_docker/./contrib/llvm-project/libcxx/include/__functional/invoke.h:394:23 (clickhouse+0x1e28e005)
    #28 void std::__1::__invoke_void_return_wrapper<void, true>::__call<ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, char const*)::$_0>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, char const*)::$_0&&)::'lambda'()&>(ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, char const*)::$_0>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, char const*)::$_0&&)::'lambda'()&) build_docker/./contrib/llvm-project/libcxx/include/__functional/invoke.h:479:9 (clickhouse+0x1e28e005)
    #29 std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, char const*)::$_0>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, char const*)::$_0&&)::'lambda'(), void ()>::operator()[abi:v15000]() build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:235:12 (clickhouse+0x1e28e005)
    #30 void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, char const*)::$_0>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, char const*)::$_0&&)::'lambda'(), void ()>>(std::__1::__function::__policy_storage const*) build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:716:16 (clickhouse+0x1e28e005)
    #31 std::__1::__function::__policy_func<void ()>::operator()[abi:v15000]() const build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:848:16 (clickhouse+0x16188346) (BuildId: 0c9f899fddcdb2e506f3bc8b126f3620f7fe4d9d)
    #32 std::__1::function<void ()>::operator()() const build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:1187:12 (clickhouse+0x16188346)
    #33 ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) build_docker/./src/Common/ThreadPool.cpp:427:13 (clickhouse+0x16188346)
    #34 void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()::operator()() const build_docker/./src/Common/ThreadPool.cpp:180:73 (clickhouse+0x1618e4f1) (BuildId: 0c9f899fddcdb2e506f3bc8b126f3620f7fe4d9d)
    #35 decltype(std::declval<void>()()) std::__1::__invoke[abi:v15000]<void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()>(void&&) build_docker/./contrib/llvm-project/libcxx/include/__functional/invoke.h:394:23 (clickhouse+0x1618e4f1)
    #36 void std::__1::__thread_execute[abi:v15000]<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()>(std::__1::tuple<void, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()>&, std::__1::__tuple_indices<>) build_docker/./contrib/llvm-project/libcxx/include/thread:284:5 (clickhouse+0x1618e4f1)
    #37 void* std::__1::__thread_proxy[abi:v15000]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()>>(void*) build_docker/./contrib/llvm-project/libcxx/include/thread:295:5 (clickhouse+0x1618e4f1)

SUMMARY: ThreadSanitizer: signal-unsafe call inside of a signal (/usr/bin/clickhouse+0xdc8da1c) (BuildId: 0c9f899fddcdb2e506f3bc8b126f3620f7fe4d9d) in malloc
==================
```

**Comment by alesapin** [comment]
@qoega Agree, failure is interesting, but no, it cannot be related.

**Comment by mrxotey** [comment]
Seems this relates to https://github.com/ClickHouse/ClickHouse/issues/51826
Could you please apply this patch to LTS versions?

**Comment by alexey-milovidov** [comment]
@mrxotey not related anyhow.

**Comment by cangyin** [comment]
Could you please explain the idea of removing mmap from Allocator.h a bit ? I think the original design of using mmap to increase performance of allocating  large  memory blocks is good. So why now it is discarded ? Thanks very much.

**Comment by alexey-milovidov** [comment]
The threshold of 64 MB was not large enough.

**Comment by alesapin** [comment]
Annd let's merge. Just bad pick of tests in current run?

**Comment by nickitat** [comment]
Screenshot 2023-07-24 at 12 50 41

there are clearly a number of degraded queries in aggregation. checks are marked red. why do we still merge such pr-s?

**Comment by alesapin** [comment]
@nickitat  @alexey-milovidov Why this pull request was reverted? I've merged it because our performance tests are unstable and we pick them randomly for each run. It was third time I've rerun them which showed this red crosses:
First run:
https://s3.amazonaws.com/clickhouse-test-reports/51686/0fb660e146cb8a1b5f907439352a67a9aec2b846/performance_comparison_[1_4]/report.html
https://s3.amazonaws.com/clickhouse-test-reports/51686/0fb660e146cb8a1b5f907439352a67a9aec2b846/performance_comparison_[2_4]/report.html
https://s3.amazonaws.com/clickhouse-test-reports/51686/0fb660e146cb8a1b5f907439352a67a9aec2b846/performance_comparison_[3_4]/report.html
https://s3.amazonaws.com/clickhouse-test-reports/51686/0fb660e146cb8a1b5f907439352a67a9aec2b846/performance_comparison_[4_4]/report.html
Average speedup: 1.4%
Second run:
https://s3.amazonaws.com/clickhouse-test-reports/51686/f28003a7bdd1064723ffa1be513c1c631a3fe186/performance_comparison_[1_4]/report.html
https://s3.amazonaws.com/clickhouse-test-reports/51686/f28003a7bdd1064723ffa1be513c1c631a3fe186/performance_comparison_[2_4]/report.html
https://s3.amazonaws.com/clickhouse-test-reports/51686/f28003a7bdd1064723ffa1be513c1c631a3fe186/performance_comparison_[3_4]/report.html
https://s3.amazonaws.com/clickhouse-test-reports/51686/f28003a7bdd1064723ffa1be513c1c631a3fe186/performance_comparison_[4_4]/report.html
Average speedup: 1.425%
Third run:
https://s3.amazonaws.com/clickhouse-test-reports/51686/16d8631e01f460d3073c5ff89a9481e9a2f2bbee/performance_comparison_[1_4]/report.html
https://s3.amazonaws.com/clickhouse-test-reports/51686/16d8631e01f460d3073c5ff89a9481e9a2f2bbee/performance_comparison_[2_4]/report.html
https://s3.amazonaws.com/clickhouse-test-reports/51686/16d8631e01f460d3073c5ff89a9481e9a2f2bbee/performance_comparison_[3_4]/report.html
https://s3.amazonaws.com/clickhouse-test-reports/51686/16d8631e01f460d3073c5ff89a9481e9a2f2bbee/performance_comparison_[4_4]/report.html
Average speedup: 0.3% (insignificant)

**Pull request merged**
