### PR TITLE
Fix Keeper with `force_sync = false`

### PR DESCRIPTION
**Pull request by antonio2368**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by antonio2368** [comment]
@alesapin seems it's fixed 🤔

**Comment by antonio2368** [comment]
From`-rw-r----- 1 ubuntu ubuntu 1048576 Mar  7 17:26 changelog_500001_600000.bin.zstd`, size of the incorrect changelog is exactly the buffer size for WriteBuffer which should mean that we didn't write to disk when we should.
So now I'm even more confused why the fix didn't help... Maybe I missed a place.

**Comment by antonio2368** [comment]
I'm an idiot... The tests that still failed are upgrade checks where the problematic part happens when we run a stress test on OLD version, so my fix isn't applied there. Good thing I didn't spend TOO much time debugging it...
I tried inserting the data in Keeper and forcefully terminating it and each time data persisted and the fix makes sense. cc @tavplubix if you would like to review/verify.

**Review by alesapin — APPROVED** [review]

**Comment by antonio2368** [comment]
> We can replace the config for the old version

Do you mean patch it unconditionally and then remove it when we release a new version?

**Comment by tavplubix** [comment]
> Do you mean patch it unconditionally and then remove it when we release a new version?

Yep

**Review by alesapin — APPROVED** [review]

**Pull request merged**
