### PR TITLE
Add logs and metrics about rejected connections in Poco

### PR DESCRIPTION
**Pull request by tavplubix**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Added logs and metrics for rejected connections (where there are not enough resources)

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-clickhouse-ci-2** [comment]
*This is an automated comment for commit 2bd1e16e11c2e3e70059049ecac152cba35c1160 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/66410/2bd1e16e11c2e3e70059049ecac152cba35c1160/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

**Comment by tavplubix** [comment]
Builds — 34/35 artifact groups are OK - clang-tidy was broken in master

**Review by serxa — APPROVED** [review]

**Comment by serxa** [comment]
Metrics are good, but maybe we should just get rid of refused connections in TCPServerDispatcher if it does not work properly now?  I did not investigate how it is handled right now, but maybe handle the number of concurrent sessions somewhere down the road where we have better control? Is take a connection and throwing it later a good option?

**Comment by tavplubix** [comment]
> maybe we should just get rid of refused connections in TCPServerDispatcher

The problem is that we have one thread per connection, and we have a shared thread pool with max_connections=1024 threads for all interfaces: https://github.com/ClickHouse/ClickHouse/blob/a339dd020f97e0e31d20e97966aa18c6afb4c3c0/programs/server/Server.cpp#L880-L882

So we cannot handle more than 1024 incoming connections, and the only thing we can do when we get more is to reject new connections (well, we could add them to the queue, but see the comment added in the PR).

I'm not sure if we should do it in another place; if we have to reject connections, then it's better to do it as early as possible.

**Pull request merged**
