### PR TITLE
Revert "Revert "Fixed wrong python test name pattern""

### PR DESCRIPTION
**Pull request by Felixoid**
Reverts  ClickHouse/ClickHouse#53929

Original changes from #53713

The tests are broken for a long and didn't work for some reason. See the [query](https://play.clickhouse.com/play?user=play#U0VMRUNUICogRlJPTSBjaGVja3MgCldIRVJFIDEKICAgIEFORCB0b0RhdGUoY2hlY2tfc3RhcnRfdGltZSkgQkVUV0VFTiB0b0RhdGUoJzIwMjMtMDgtMjQnKSBBTkQgdG9EYXRlKCcyMDIzLTA4LTI4JykKICAgIEFORCBwdWxsX3JlcXVlc3RfbnVtYmVyID0gMAogICAgQU5EIHRlc3RfbmFtZSBJTiAoJ3Rlc3RfY29tcG9zYWJsZV9wcm90b2NvbHMvdGVzdC5weTo6dGVzdF9jb25uZWN0aW9ucycsICd0ZXN0X2NvbmN1cnJlbnRfYmFja3Vwc19zMy90ZXN0LnB5Ojp0ZXN0X2NvbmN1cnJlbnRfYmFja3VwcycpCk9SREVSIEJZIGNoZWNrX3N0YXJ0X3RpbWU=)

### CODE REVIEW

**Comment by robot-ch-test-poll3** [comment]
This is an automated comment for commit a11af06c0021efdb1085f0288ca0cff69a3d63e9 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/54043/a11af06c0021efdb1085f0288ca0cff69a3d63e9/ci_running.html)
The overall status of the commit is 🔴 failure

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🔴 failure</td></tr>
</table>

**Comment by Felixoid** [comment]
Tests test_composable_protocols/test.py::test_connections and test_concurrent_backups_s3/test.py::test_concurrent_backups should be fixed before the merge

**Comment by Demilivor** [comment]
I'm going to fix `test_composable_protocols/test.py::test_connections` in scope of https://github.com/ClickHouse/ClickHouse/pull/53907

**Comment by Felixoid** [comment]
Disable more broken tests, and broken analyzer tests

**Comment by Felixoid** [comment]
Stress test [assertion](https://s3.amazonaws.com/clickhouse-test-reports/54043/c7e058fa6e017a7539e702f87dd7b94d8c53c797/stress_test__tsan_.html) is the same as in [master](https://s3.amazonaws.com/clickhouse-test-reports/0/a0d25fdd543eb61bf8a70d12549565794d334ffd/stress_test__tsan_.html)

**Comment by Felixoid** [comment]
Stateless tests are in [master](https://play.clickhouse.com/play?user=play#U0VMRUNUICogRlJPTSBjaGVja3MgCldIRVJFIDEKICAgIEFORCB0b0RhdGUoY2hlY2tfc3RhcnRfdGltZSkgPiB0b0RhdGUoJzIwMjMtMDgtMjknKQogICAgQU5EIHRlc3RfbmFtZSA9ICcwMTQxNF9tdXRhdGlvbnNfYW5kX2Vycm9yc196b29rZWVwZXInCiAgICBBTkQgdGVzdF9zdGF0dXMgPSAnRkFJTCcKICAgIEFORCBjaGVja19zdGF0dXMgPSAnZmFpbHVyZScKT1JERVIgQlkgY2hlY2tfc3RhcnRfdGltZQ==)

**Pull request merged**
