### PR TITLE
Bugfix/local multiquery parameter

### LINKED ISSUE #54428: clickhouse-client and clickhouse-local behave differently with multiquery statements
Inconsistent behavior (but not a big deal), reported in https://github.com/ClickHouse/ClickHouse/pull/50357#discussion_r1211260100:

```base
/.clickhouse-client  -q "select 1; select 2"
-- Code: 62. DB::Exception: Syntax error (Multi-statements are not allowed): failed at position 9 (end of query): ; select 2. . (SYNTAX_ERROR)

./clickhouse-local   -q "select 1; select 2;"
1
2
```

`clickhouse-local` understands `--multiquery`, so this might be a (minor) bug and not by design. Otherwise, we can just document the behavior.

### PR DESCRIPTION
**Pull request by bakam412**
Fixes:  #54428

### Changelog category (leave one):
- Bug Fix

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
clickhouse-local now expects parameter "--multiquery" (or: "-n") when multiple queries separated by semicolon are passed after "--query" (or: "-q"). This makes the behavior consistent with clickhouse-client.

### CODE REVIEW

**Comment by robot-ch-test-poll3** [comment]
This is an automated comment for commit 0cb619b8165d603144d77b420d197c2929842003 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/54498/0cb619b8165d603144d77b420d197c2929842003/ci_running.html)
The overall status of the commit is 🔴 failure

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🔴 failure</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Comment by Avogar** [comment]
I see we use multiqueries in performance tests, we can add `--multiquery` option to `clickhouse-local` in perf tests scripts. You can find them in dir `docker/test/performance-comparison` (I guess the main script we should look at is `compare.sh`)

**Comment by bakam412** [comment]
> I see we use multiqueries in performance tests, we can add `--multiquery` option to `clickhouse-local` in perf tests scripts. You can find them in dir `docker/test/performance-comparison` (I guess the main script we should look at is `compare.sh`)

Ok, I have submitted the new changes. Please grant me CI execution permission. Thank you.

**Comment by bakam412** [comment]
@Avogar Please grant me CI execution permission. Thank you.

**Review by Avogar — APPROVED** [review]

**Comment by rschu1ze** [comment]
@bakam412 Thanks for the fix. Yet someone who reads the changelog entry will have no clue in which way the difference between "clickhouse-client" and "clickhouse-local" was resolved, and if #54428 is resolved (it is still open). Kindly adjust the PR message - thanks!

**Comment by bakam412** [comment]
> @bakam412 Thanks for the fix. Yet someone who reads the changelog entry will have no clue in which way the difference between "clickhouse-client" and "clickhouse-local" was resolved, and if #54428 is fixed (it is still open). Kindly adjust the PR message - thanks!
> 
> EDIT: Fixed it.

ok. I have already adjusted the PR message

**Pull request merged**
