### PR TITLE
Allow parsing Date as DateTime and DateTime64

### PR DESCRIPTION
**Pull request by alexey-milovidov**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Allow parsing Date as DateTime and DateTime64. This implements the enhancement proposed in #36949.

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
Performance tests ok.

**Review by davenger — APPROVED** [review]

**Comment by thgruiz** [comment]
got some errors about this (trying to send a Unix timestamp with nano precision on a JSON field with 
`insert into db_name.table_name FORMAT JSONEachRow {"timestamp": "1687890970.208194001"}`

and this code helped me figure out why, thanks!

It is still impossible to use the DateTime64 precision with this kind of inserts, from what I can see. Am I right?

**Comment by den-crane** [comment]
@thgruiz open an issue. It's unclear what do you mean.

```sql
create table A (timestamp DateTime64(9)) Engine=Memory;

insert into A format JSONEachRow {"timestamp": "1687890970.208194001"}
;

select * from A;
┌─────────────────────timestamp─┐
│ 2023-06-27 18:36:10.208194001 │
└───────────────────────────────┘
```

**Comment by thgruiz** [comment]
@den-crane Thanks for the response (and sorry for the delay)

Indeed, my comment is missing information: on clickhouse-client it works, on other connectors dont.

Those queries on your example can run fine on the clickhouse-client, but using other drivers (like the java native one, or in a lab on clickhouse client web interface) it does not work.


So it seems that depending on where you execute the query, there is an error on the parser

The odd thing is that looking on tcpdump the exact same query is sent by the driver...

**Comment by den-crane** [comment]
@thgruiz here is exactly the same with JDBC

Screenshot 2023-07-11 at 2 46 02 PM

**Comment by thgruiz** [comment]
hum... thats odd
just did that on a cloud instance:

image

**Comment by den-crane** [comment]
@thgruiz in examples the semicolon `;` at the next line deliberately.
Ask cloud support. We don't support cloud here.

**Comment by den-crane** [comment]
https://fiddle.clickhouse.com/325a768e-cb3f-471d-8f88-c2608b56da04

**Comment by thgruiz** [comment]
@den-crane, Just a feedback on this (and maybe more info for anyone in the future).

In my ignorance, I thought the problem may be related to the code on this PR, but based on the reply I got from the cloud support it clearly was not the case:


The 'date_time_input_format' variable has a major part in this.

1) the user we connect on clickhouse when in console.clickhouse.cloud is 'sql-console:<your-cloud-account-e-mail>' and the settings of date_time_input_format defaults to 'best_effort'. With this scenario I was unable to use the insert 'insert into A format JSONEachRow {"timestamp": "1687890970.208194001"};' (note: the semicolon on the same line or on the next line give the same result

2) when the setting was changed to 'basic' with this query, the insert is done ok:

ALTER USER 'sql-console:<your-cloud-account-e-mail>' SETTINGS date_time_input_format = 'basic', async_insert = 1;


and here comes the fun part:

3) when using clickhouse-client, the user is 'default' (not 'sql-console:<your-cloud-account-e-mail>') and the date_time_input_format is  'best_effort', too, but the insert works. So it seems that the user does not matter, only the settings and from where the query cames from.


4) on https://fiddle.clickhouse.com/ the date_time_input_format is 'basic', that's why it works I think...

That does not make sense, the cloud support team is still looking into it.

**Pull request merged**
