### PR TITLE
Make the query planner respect LIMIT BY in remote queries

### PR DESCRIPTION
**Pull request by kvap**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

### Category
Bug Fix

### Short description
Distributed queries with both `LIMIT BY` and `LIMIT` are processed incorrectly. The planner does not add the `LimitBy` step to the first stage of the pipeline (i.e. on the remote side).

### Detailed description
Normally when you specify both `LIMIT BY` and `LIMIT` the `LimitBy` operation goes first in the pipeline, and then `Limit`. But in the distributed case the query interpreter only inserts the `Limit` operation. This leads to incorrect results.

For example, suppose we have a table `t` that has these data:
```
+----------------+
| a       b      |
+----------------+
| hello   world  |
| hello   galaxy |
| goodbye world  |
| goodbye galaxy |
+----------------+
```

Then the following query is expected to return two rows:
```sql
:) SELECT a, b FROM t LIMIT 1 BY a LIMIT 2
hello, world
goodbye, world
```
That works as expected, first the `LimitBy` kicks in, leaving only those two rows, then the `Limit`.

But if table `t` is remote, then the remote side first preforms `Limit`, which keeps only rows with `hello`, and then the local side does `LimitBy`, and you get just one row.

This PR makes the SelectQueryInterpreter add the `LimitBy` operation to the remote pipeline just before the `Limit`.

### CODE REVIEW

**Comment by kvap** [comment]
cc @bocharov @twalwyn @Dorokhov

**Review by bocharov — APPROVED** [review]

**Review by alexey-milovidov — APPROVED** [review]

**Comment by nvartolomei** [comment]
@alexey-milovidov can we please stage this to 19.1.* as well?

**Comment by nvartolomei** [comment]
@4ertus2 thanks!

**Comment by alexey-milovidov** [comment]
Did you mean @KochetovNicolai? https://github.com/yandex/ClickHouse/pull/4556

**Comment by nvartolomei** [comment]
Yes. <3

**Pull request merged**
