### PR TITLE
Update zlib-ng to latest commit

### PR DESCRIPTION
**Pull request by bkuschel**
Several fixes including ability to debug on Power.

### Changelog category (leave one):
- Build/Testing/Packaging Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Update to latest zlib-ng

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by CheSema** [comment]
asan problem -- https://github.com/ClickHouse/ClickHouse/issues/41500
https://s3.amazonaws.com/clickhouse-test-reports/42463/4645d465b12013d99d88956020034cbfa47d9455/stateless_tests__asan__[2/2]/stderr.log

**Comment by alexey-milovidov** [comment]
https://github.com/ClickHouse/ClickHouse/issues/42637

**Comment by CheSema** [comment]
thread sanitizer log
<details>
<summary><b>StackTrace</b></summary>

WARNING: ThreadSanitizer: data race (pid=1)
  Atomic write of size 4 at 0x7f89eb673540 by main thread (mutexes: write M0, write M1):
    #0 int std::__1::__cxx_atomic_fetch_add<int>(std::__1::__cxx_atomic_base_impl<int>*, int, std::__1::memory_order) build_docker/../contrib/libcxx/include/atomic:1003:12 (clickhouse+0x20deba43) (BuildId: 6af1fb37fdeff8f4465ca972a35a5806873a31ee)
    #1 std::__1::__atomic_base<int, true>::fetch_add(int, std::__1::memory_order) build_docker/../contrib/libcxx/include/atomic:1687:17 (clickhouse+0x20deba43)
    #2 absl::lts_20211102::synchronization_internal::Waiter::Post() build_docker/../contrib/abseil-cpp/absl/synchronization/internal/waiter.cc:110:14 (clickhouse+0x20deba43)
    #3 AbslInternalPerThreadSemPost_lts_20211102 build_docker/../contrib/abseil-cpp/absl/synchronization/internal/per_thread_sem.cc:73:64 (clickhouse+0x20deb0fd) (BuildId: 6af1fb37fdeff8f4465ca972a35a5806873a31ee)
    #4 absl::lts_20211102::synchronization_internal::PerThreadSem::Post(absl::lts_20211102::base_internal::ThreadIdentity*) build_docker/../contrib/abseil-cpp/absl/synchronization/internal/per_thread_sem.h:107:3 (clickhouse+0x20de5bcc) (BuildId: 6af1fb37fdeff8f4465ca972a35a5806873a31ee)
    #5 absl::lts_20211102::Mutex::IncrementSynchSem(absl::lts_20211102::Mutex*, absl::lts_20211102::base_internal::PerThreadSynch*) build_docker/../contrib/abseil-cpp/absl/synchronization/mutex.cc:566:3 (clickhouse+0x20de5bcc)
    #6 absl::lts_20211102::Mutex::Wakeup(absl::lts_20211102::base_internal::PerThreadSynch*) build_docker/../contrib/abseil-cpp/absl/synchronization/mutex.cc:1156:3 (clickhouse+0x20de5bcc)
    #7 absl::lts_20211102::Mutex::UnlockSlow(absl::lts_20211102::SynchWaitParams*) build_docker/../contrib/abseil-cpp/absl/synchronization/mutex.cc:2321:19 (clickhouse+0x20deac30) (BuildId: 6af1fb37fdeff8f4465ca972a35a5806873a31ee)
    #8 absl::lts_20211102::Mutex::Unlock() build_docker/../contrib/abseil-cpp/absl/synchronization/mutex.cc:1712:11 (clickhouse+0x20de7b4e) (BuildId: 6af1fb37fdeff8f4465ca972a35a5806873a31ee)
    #9 gpr_mu_unlock build_docker/../contrib/grpc/src/core/lib/gpr/sync_abseil.cc:60:39 (clickhouse+0x20bdf5b9) (BuildId: 6af1fb37fdeff8f4465ca972a35a5806873a31ee)
    #10 grpc_core::(anonymous namespace)::ThreadInternalsPosix::Start() build_docker/../contrib/grpc/src/core/lib/gprpp/thd_posix.cc:168:5 (clickhouse+0x20be367f) (BuildId: 6af1fb37fdeff8f4465ca972a35a5806873a31ee)
    #11 grpc_core::Thread::Start() build_docker/../contrib/grpc/src/core/lib/gprpp/thd.h:132:14 (clickhouse+0x20a18110) (BuildId: 6af1fb37fdeff8f4465ca972a35a5806873a31ee)
    #12 start_timer_thread_and_unlock() build_docker/../contrib/grpc/src/core/lib/iomgr/timer_manager.cc:93:11 (clickhouse+0x20a18110)
    #13 start_threads() build_docker/../contrib/grpc/src/core/lib/iomgr/timer_manager.cc:293:5 (clickhouse+0x20a17ba5) (BuildId: 6af1fb37fdeff8f4465ca972a35a5806873a31ee)
    #14 grpc_timer_manager_init() build_docker/../contrib/grpc/src/core/lib/iomgr/timer_manager.cc:311:3 (clickhouse+0x20a17ba5)
    #15 grpc_iomgr_start() build_docker/../contrib/grpc/src/core/lib/iomgr/iomgr.cc:69:27 (clickhouse+0x209ee4d3) (BuildId: 6af1fb37fdeff8f4465ca972a35a5806873a31ee)
    #16 grpc_init build_docker/../contrib/grpc/src/core/lib/surface/init.cc:165:5 (clickhouse+0x20a51470) (BuildId: 6af1fb37fdeff8f4465ca972a35a5806873a31ee)
    #17 grpc::internal::GrpcLibrary::init() build_docker/../contrib/grpc/include/grpcpp/impl/grpc_library.h:34:26 (clickhouse+0x2091dfd3) (BuildId: 6af1fb37fdeff8f4465ca972a35a5806873a31ee)
    #18 grpc::GrpcLibraryCodegen::GrpcLibraryCodegen(bool) build_docker/../contrib/grpc/include/grpcpp/impl/codegen/grpc_library.h:45:15 (clickhouse+0x208f4819) (BuildId: 6af1fb37fdeff8f4465ca972a35a5806873a31ee)
    #19 grpc::CompletionQueue::CompletionQueue(grpc_completion_queue_attributes const&) build_docker/../contrib/grpc/include/grpcpp/impl/codegen/completion_queue.h:240:3 (clickhouse+0x208f4819)
    #20 grpc::ServerCompletionQueue::ServerCompletionQueue(grpc_cq_completion_type, grpc_cq_polling_type, grpc_experimental_completion_queue_functor*) build_docker/../contrib/grpc/include/grpcpp/impl/codegen/completion_queue.h:436:9 (clickhouse+0x2092447b) (BuildId: 6af1fb37fdeff8f4465ca972a35a5806873a31ee)
    #21 grpc::ServerBuilder::AddCompletionQueue(bool) build_docker/../contrib/grpc/src/cpp/server/server_builder.cc:73:41 (clickhouse+0x2092447b)
    #22 DB::GRPCServer::start() build_docker/../src/Server/GRPCServer.cpp:1871:21 (clickhouse+0x1cbbb4c7) (BuildId: 6af1fb37fdeff8f4465ca972a35a5806873a31ee)
    #23 DB::ProtocolServerAdapter::GRPCServerAdapterImpl::start() build_docker/../src/Server/ProtocolServerAdapter.cpp:47:42 (clickhouse+0x1cc4f7c3) (BuildId: 6af1fb37fdeff8f4465ca972a35a5806873a31ee)
    #24 DB::ProtocolServerAdapter::start() build_docker/../src/Server/ProtocolServerAdapter.h:29:26 (clickhouse+0xb657ff0) (BuildId: 6af1fb37fdeff8f4465ca972a35a5806873a31ee)
    #25 DB::Server::main(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>> const&) build_docker/../programs/server/Server.cpp:1780:24 (clickhouse+0xb657ff0)
    #26 Poco::Util::Application::run() build_docker/../contrib/poco/Util/src/Application.cpp:334:8 (clickhouse+0x1fffabfd) (BuildId: 6af1fb37fdeff8f4465ca972a35a5806873a31ee)
    #27 DB::Server::run() build_docker/../programs/server/Server.cpp:467:25 (clickhouse+0xb644da3) (BuildId: 6af1fb37fdeff8f4465ca972a35a5806873a31ee)
    #28 Poco::Util::ServerApplication::run(int, char**) build_docker/../contrib/poco/Util/src/ServerApplication.cpp:611:9 (clickhouse+0x2001a116) (BuildId: 6af1fb37fdeff8f4465ca972a35a5806873a31ee)
    #29 mainEntryClickHouseServer(int, char**) build_docker/../programs/server/Server.cpp:182:20 (clickhouse+0xb642274) (BuildId: 6af1fb37fdeff8f4465ca972a35a5806873a31ee)
    #30 main build_docker/../programs/main.cpp:449:12 (clickhouse+0xb63fe6c) (BuildId: 6af1fb37fdeff8f4465ca972a35a5806873a31ee)

  Previous write of size 8 at 0x7f89eb673540 by thread T197:
    #0 mmap <null> (clickhouse+0xb5ee1d3) (BuildId: 6af1fb37fdeff8f4465ca972a35a5806873a31ee)
    #1 absl::lts_20211102::base_internal::DoAllocWithArena(unsigned long, absl::lts_20211102::base_internal::LowLevelAlloc::Arena*) build_docker/../contrib/abseil-cpp/absl/base/internal/low_level_alloc.cc:562:21 (clickhouse+0x20e1d962) (BuildId: 6af1fb37fdeff8f4465ca972a35a5806873a31ee)
    #2 absl::lts_20211102::base_internal::LowLevelAlloc::Alloc(unsigned long) build_docker/../contrib/abseil-cpp/absl/base/internal/low_level_alloc.cc:606:18 (clickhouse+0x23a4b7fa) (BuildId: 6af1fb37fdeff8f4465ca972a35a5806873a31ee)
    #3 absl::lts_20211102::synchronization_internal::NewThreadIdentity() build_docker/../contrib/abseil-cpp/absl/synchronization/internal/create_thread_identity.cc:113:24 (clickhouse+0x20deb48e) (BuildId: 6af1fb37fdeff8f4465ca972a35a5806873a31ee)
    #4 absl::lts_20211102::synchronization_internal::CreateThreadIdentity() build_docker/../contrib/abseil-cpp/absl/synchronization/internal/create_thread_identity.cc:129:45 (clickhouse+0x20deb48e)
    #5 absl::lts_20211102::synchronization_internal::GetOrCreateCurrentThreadIdentity() build_docker/../contrib/abseil-cpp/absl/synchronization/internal/create_thread_identity.h:51:12 (clickhouse+0x20de93b9) (BuildId: 6af1fb37fdeff8f4465ca972a35a5806873a31ee)
    #6 absl::lts_20211102::Synch_GetPerThread() build_docker/../contrib/abseil-cpp/absl/synchronization/mutex.cc:538:30 (clickhouse+0x20de93b9)
    #7 absl::lts_20211102::Synch_GetPerThreadAnnotated(absl::lts_20211102::Mutex*) build_docker/../contrib/abseil-cpp/absl/synchronization/mutex.cc:546:23 (clickhouse+0x20de93b9)
    #8 absl::lts_20211102::CondVar::WaitCommon(absl::lts_20211102::Mutex*, absl::lts_20211102::synchronization_internal::KernelTimeout) build_docker/../contrib/abseil-cpp/absl/synchronization/mutex.cc:2550:25 (clickhouse+0x20de93b9)
    #9 absl::lts_20211102::CondVar::Wait(absl::lts_20211102::Mutex*) build_docker/../contrib/abseil-cpp/absl/synchronization/mutex.cc:2594:3 (clickhouse+0x20de95c2) (BuildId: 6af1fb37fdeff8f4465ca972a35a5806873a31ee)
    #10 gpr_cv_wait build_docker/../contrib/grpc/src/core/lib/gpr/sync_abseil.cc:85:43 (clickhouse+0x20bdf720) (BuildId: 6af1fb37fdeff8f4465ca972a35a5806873a31ee)
    #11 grpc_core::Executor::ThreadMain(void*) build_docker/../contrib/grpc/src/core/lib/iomgr/executor.cc:231:7 (clickhouse+0x209ed078) (BuildId: 6af1fb37fdeff8f4465ca972a35a5806873a31ee)
    #12 grpc_core::(anonymous namespace)::ThreadInternalsPosix::ThreadInternalsPosix(char const*, void (*)(void*), void*, bool*, grpc_core::Thread::Options const&)::'lambda'(void*)::operator()(void*) const build_docker/../contrib/grpc/src/core/lib/gprpp/thd_posix.cc:140:27 (clickhouse+0x20be381d) (BuildId: 6af1fb37fdeff8f4465ca972a35a5806873a31ee)
    #13 grpc_core::(anonymous namespace)::ThreadInternalsPosix::ThreadInternalsPosix(char const*, void (*)(void*), void*, bool*, grpc_core::Thread::Options const&)::'lambda'(void*)::__invoke(void*) build_docker/../contrib/grpc/src/core/lib/gprpp/thd_posix.cc:110:25 (clickhouse+0x20be381d)

  Mutex M0 (0x7fffbf97cc88) created at:
    #0 pthread_mutex_lock <null> (clickhouse+0xb5dc8ba) (BuildId: 6af1fb37fdeff8f4465ca972a35a5806873a31ee)
    #1 std::__1::__libcpp_mutex_lock(pthread_mutex_t*) build_docker/../contrib/libcxx/include/__threading_support:303:10 (clickhouse+0x239fcf19) (BuildId: 6af1fb37fdeff8f4465ca972a35a5806873a31ee)
    #2 std::__1::mutex::lock() build_docker/../contrib/libcxx/src/mutex.cpp:33:14 (clickhouse+0x239fcf19)
    #3 std::__1::lock_guard<std::__1::mutex>::lock_guard(std::__1::mutex&) build_docker/../contrib/libcxx/include/__mutex_base:91:27 (clickhouse+0xb65753b) (BuildId: 6af1fb37fdeff8f4465ca972a35a5806873a31ee)
    #4 DB::Server::main(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>> const&) build_docker/../programs/server/Server.cpp:1680:29 (clickhouse+0xb65753b)
    #5 Poco::Util::Application::run() build_docker/../contrib/poco/Util/src/Application.cpp:334:8 (clickhouse+0x1fffabfd) (BuildId: 6af1fb37fdeff8f4465ca972a35a5806873a31ee)
    #6 DB::Server::run() build_docker/../programs/server/Server.cpp:467:25 (clickhouse+0xb644da3) (BuildId: 6af1fb37fdeff8f4465ca972a35a5806873a31ee)
    #7 Poco::Util::ServerApplication::run(int, char**) build_docker/../contrib/poco/Util/src/ServerApplication.cpp:611:9 (clickhouse+0x2001a116) (BuildId: 6af1fb37fdeff8f4465ca972a35a5806873a31ee)
    #8 mainEntryClickHouseServer(int, char**) build_docker/../programs/server/Server.cpp:182:20 (clickhouse+0xb642274) (BuildId: 6af1fb37fdeff8f4465ca972a35a5806873a31ee)
    #9 main build_docker/../programs/main.cpp:449:12 (clickhouse+0xb63fe6c) (BuildId: 6af1fb37fdeff8f4465ca972a35a5806873a31ee)

  Mutex M1 (0x000025236668) created at:
    #0 __tsan_mutex_create <null> (clickhouse+0xb60901f) (BuildId: 6af1fb37fdeff8f4465ca972a35a5806873a31ee)
    #1 absl::lts_20211102::Mutex::Mutex() build_docker/../contrib/abseil-cpp/absl/synchronization/mutex.h:935:3 (clickhouse+0x20bdf4ed) (BuildId: 6af1fb37fdeff8f4465ca972a35a5806873a31ee)
    #2 gpr_mu_init build_docker/../contrib/grpc/src/core/lib/gpr/sync_abseil.cc:46:12 (clickhouse+0x20bdf4ed)
    #3 do_basic_init() build_docker/../contrib/grpc/src/core/lib/surface/init.cc:73:3 (clickhouse+0x20a5151d) (BuildId: 6af1fb37fdeff8f4465ca972a35a5806873a31ee)
    #4 decltype(std::declval<void (*&)()>()()) absl::lts_20211102::base_internal::Callable::Invoke<void (*&)()>(void (*&)()) build_docker/../contrib/abseil-cpp/absl/base/internal/invoke.h:153:12 (clickhouse+0x20bdf8b7) (BuildId: 6af1fb37fdeff8f4465ca972a35a5806873a31ee)
    #5 decltype(Invoker<void (*&)()>::type::Invoke(std::declval<void (*&)()>())) absl::lts_20211102::base_internal::invoke<void (*&)()>(void (*&)()) build_docker/../contrib/abseil-cpp/absl/base/internal/invoke.h:180:10 (clickhouse+0x20bdf8b7)
    #6 void absl::lts_20211102::base_internal::CallOnceImpl<void (*&)()>(std::__1::atomic<unsigned int>*, absl::lts_20211102::base_internal::SchedulingMode, void (*&)()) build_docker/../contrib/abseil-cpp/absl/base/call_once.h:178:5 (clickhouse+0x20bdf8b7)
    #7 void absl::lts_20211102::call_once<void (*&)()>(absl::lts_20211102::once_flag&, void (*&)()) build_docker/../contrib/abseil-cpp/absl/base/call_once.h:210:5 (clickhouse+0x20bdf83b) (BuildId: 6af1fb37fdeff8f4465ca972a35a5806873a31ee)
    #8 gpr_once_init build_docker/../contrib/grpc/src/core/lib/gpr/sync_abseil.cc:113:3 (clickhouse+0x20bdf83b)
    #9 grpc_init build_docker/../contrib/grpc/src/core/lib/surface/init.cc:130:3 (clickhouse+0x20a512e1) (BuildId: 6af1fb37fdeff8f4465ca972a35a5806873a31ee)
    #10 grpc::internal::GrpcLibrary::init() build_docker/../contrib/grpc/include/grpcpp/impl/grpc_library.h:34:26 (clickhouse+0x2091dfd3) (BuildId: 6af1fb37fdeff8f4465ca972a35a5806873a31ee)
    #11 grpc::GrpcLibraryCodegen::GrpcLibraryCodegen(bool) build_docker/../contrib/grpc/include/grpcpp/impl/codegen/grpc_library.h:45:15 (clickhouse+0x208f4819) (BuildId: 6af1fb37fdeff8f4465ca972a35a5806873a31ee)
    #12 grpc::CompletionQueue::CompletionQueue(grpc_completion_queue_attributes const&) build_docker/../contrib/grpc/include/grpcpp/impl/codegen/completion_queue.h:240:3 (clickhouse+0x208f4819)
    #13 grpc::ServerCompletionQueue::ServerCompletionQueue(grpc_cq_completion_type, grpc_cq_polling_type, grpc_experimental_completion_queue_functor*) build_docker/../contrib/grpc/include/grpcpp/impl/codegen/completion_queue.h:436:9 (clickhouse+0x2092447b) (BuildId: 6af1fb37fdeff8f4465ca972a35a5806873a31ee)
    #14 grpc::ServerBuilder::AddCompletionQueue(bool) build_docker/../contrib/grpc/src/cpp/server/server_builder.cc:73:41 (clickhouse+0x2092447b)
    #15 DB::GRPCServer::start() build_docker/../src/Server/GRPCServer.cpp:1871:21 (clickhouse+0x1cbbb4c7) (BuildId: 6af1fb37fdeff8f4465ca972a35a5806873a31ee)
    #16 DB::ProtocolServerAdapter::GRPCServerAdapterImpl::start() build_docker/../src/Server/ProtocolServerAdapter.cpp:47:42 (clickhouse+0x1cc4f7c3) (BuildId: 6af1fb37fdeff8f4465ca972a35a5806873a31ee)
    #17 DB::ProtocolServerAdapter::start() build_docker/../src/Server/ProtocolServerAdapter.h:29:26 (clickhouse+0xb657ff0) (BuildId: 6af1fb37fdeff8f4465ca972a35a5806873a31ee)
    #18 DB::Server::main(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>> const&) build_docker/../programs/server/Server.cpp:1780:24 (clickhouse+0xb657ff0)
    #19 Poco::Util::Application::run() build_docker/../contrib/poco/Util/src/Application.cpp:334:8 (clickhouse+0x1fffabfd) (BuildId: 6af1fb37fdeff8f4465ca972a35a5806873a31ee)
    #20 DB::Server::run() build_docker/../programs/server/Server.cpp:467:25 (clickhouse+0xb644da3) (BuildId: 6af1fb37fdeff8f4465ca972a35a5806873a31ee)
    #21 Poco::Util::ServerApplication::run(int, char**) build_docker/../contrib/poco/Util/src/ServerApplication.cpp:611:9 (clickhouse+0x2001a116) (BuildId: 6af1fb37fdeff8f4465ca972a35a5806873a31ee)
    #22 mainEntryClickHouseServer(int, char**) build_docker/../programs/server/Server.cpp:182:20 (clickhouse+0xb642274) (BuildId: 6af1fb37fdeff8f4465ca972a35a5806873a31ee)
    #23 main build_docker/../programs/main.cpp:449:12 (clickhouse+0xb63fe6c) (BuildId: 6af1fb37fdeff8f4465ca972a35a5806873a31ee)

  Thread T197 'default-executo' (tid=204, running) created by main thread at:
    #0 pthread_create <null> (clickhouse+0xb5bebdd) (BuildId: 6af1fb37fdeff8f4465ca972a35a5806873a31ee)
    #1 grpc_core::(anonymous namespace)::ThreadInternalsPosix::ThreadInternalsPosix(char const*, void (*)(void*), void*, bool*, grpc_core::Thread::Options const&) build_docker/../contrib/grpc/src/core/lib/gprpp/thd_posix.cc:109:10 (clickhouse+0x20be3353) (BuildId: 6af1fb37fdeff8f4465ca972a35a5806873a31ee)
    #2 grpc_core::Thread::Thread(char const*, void (*)(void*), void*, bool*, grpc_core::Thread::Options const&) build_docker/../contrib/grpc/src/core/lib/gprpp/thd_posix.cc:186:15 (clickhouse+0x20be3353)
    #3 grpc_core::Executor::SetThreading(bool) build_docker/../contrib/grpc/src/core/lib/iomgr/executor.cc:165:9 (clickhouse+0x209ec965) (BuildId: 6af1fb37fdeff8f4465ca972a35a5806873a31ee)
    #4 grpc_core::Executor::Init() build_docker/../contrib/grpc/src/core/lib/iomgr/executor.cc:98:25 (clickhouse+0x209edbd5) (BuildId: 6af1fb37fdeff8f4465ca972a35a5806873a31ee)
    #5 grpc_core::Executor::InitAll() build_docker/../contrib/grpc/src/core/lib/iomgr/executor.cc:400:58 (clickhouse+0x209edbd5)
    #6 grpc_iomgr_init() build_docker/../contrib/grpc/src/core/lib/iomgr/iomgr.cc:60:3 (clickhouse+0x209ee3a5) (BuildId: 6af1fb37fdeff8f4465ca972a35a5806873a31ee)
    #7 grpc_init build_docker/../contrib/grpc/src/core/lib/surface/init.cc:149:5 (clickhouse+0x20a5137f) (BuildId: 6af1fb37fdeff8f4465ca972a35a5806873a31ee)
    #8 grpc::internal::GrpcLibrary::init() build_docker/../contrib/grpc/include/grpcpp/impl/grpc_library.h:34:26 (clickhouse+0x2091dfd3) (BuildId: 6af1fb37fdeff8f4465ca972a35a5806873a31ee)
    #9 grpc::GrpcLibraryCodegen::GrpcLibraryCodegen(bool) build_docker/../contrib/grpc/include/grpcpp/impl/codegen/grpc_library.h:45:15 (clickhouse+0x208f4819) (BuildId: 6af1fb37fdeff8f4465ca972a35a5806873a31ee)
    #10 grpc::CompletionQueue::CompletionQueue(grpc_completion_queue_attributes const&) build_docker/../contrib/grpc/include/grpcpp/impl/codegen/completion_queue.h:240:3 (clickhouse+0x208f4819)
    #11 grpc::ServerCompletionQueue::ServerCompletionQueue(grpc_cq_completion_type, grpc_cq_polling_type, grpc_experimental_completion_queue_functor*) build_docker/../contrib/grpc/include/grpcpp/impl/codegen/completion_queue.h:436:9 (clickhouse+0x2092447b) (BuildId: 6af1fb37fdeff8f4465ca972a35a5806873a31ee)
    #12 grpc::ServerBuilder::AddCompletionQueue(bool) build_docker/../contrib/grpc/src/cpp/server/server_builder.cc:73:41 (clickhouse+0x2092447b)
    #13 DB::GRPCServer::start() build_docker/../src/Server/GRPCServer.cpp:1871:21 (clickhouse+0x1cbbb4c7) (BuildId: 6af1fb37fdeff8f4465ca972a35a5806873a31ee)
    #14 DB::ProtocolServerAdapter::GRPCServerAdapterImpl::start() build_docker/../src/Server/ProtocolServerAdapter.cpp:47:42 (clickhouse+0x1cc4f7c3) (BuildId: 6af1fb37fdeff8f4465ca972a35a5806873a31ee)
    #15 DB::ProtocolServerAdapter::start() build_docker/../src/Server/ProtocolServerAdapter.h:29:26 (clickhouse+0xb657ff0) (BuildId: 6af1fb37fdeff8f4465ca972a35a5806873a31ee)
    #16 DB::Server::main(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>> const&) build_docker/../programs/server/Server.cpp:1780:24 (clickhouse+0xb657ff0)
    #17 Poco::Util::Application::run() build_docker/../contrib/poco/Util/src/Application.cpp:334:8 (clickhouse+0x1fffabfd) (BuildId: 6af1fb37fdeff8f4465ca972a35a5806873a31ee)
    #18 DB::Server::run() build_docker/../programs/server/Server.cpp:467:25 (clickhouse+0xb644da3) (BuildId: 6af1fb37fdeff8f4465ca972a35a5806873a31ee)
    #19 Poco::Util::ServerApplication::run(int, char**) build_docker/../contrib/poco/Util/src/ServerApplication.cpp:611:9 (clickhouse+0x2001a116) (BuildId: 6af1fb37fdeff8f4465ca972a35a5806873a31ee)
    #20 mainEntryClickHouseServer(int, char**) build_docker/../programs/server/Server.cpp:182:20 (clickhouse+0xb642274) (BuildId: 6af1fb37fdeff8f4465ca972a35a5806873a31ee)
    #21 main build_docker/../programs/main.cpp:449:12 (clickhouse+0xb63fe6c) (BuildId: 6af1fb37fdeff8f4465ca972a35a5806873a31ee)

SUMMARY: ThreadSanitizer: data race build_docker/../contrib/libcxx/include/atomic:1003:12 in int std::__1::__cxx_atomic_fetch_add<int>(std::__1::__cxx_atomic_base_impl<int>*, int, std::__1::memory_order)
==================
ThreadSanitizer: reported 1 warnings

</details>

Test has started to fail at master since 16.09.2022

https://play.clickhouse.com/play?user=play#c2VsZWN0IAp0b1N0YXJ0T2ZIb3VyKGNoZWNrX3N0YXJ0X3RpbWUpIGFzIGQsCmNvdW50KCksICBncm91cFVuaXFBcnJheShwdWxsX3JlcXVlc3RfbnVtYmVyKSwgIGFueShyZXBvcnRfdXJsKQpmcm9tIGNoZWNrcyB3aGVyZSAnMjAyMi0wNi0wMScgPD0gY2hlY2tfc3RhcnRfdGltZSBhbmQgdGVzdF9uYW1lIGxpa2UgJyV0ZXN0X2NhbmNlbF93aGlsZV9nZW5lcmF0aW5nX291dHB1dCUnIGFuZCB0ZXN0X3N0YXR1cyBpbiAoJ0ZBSUwnLCAnRkxBS1knKSBncm91cCBieSBkIG9yZGVyIGJ5IGQgZGVzYw==


At that time we switched to llvm-15 https://github.com/ClickHouse/ClickHouse/pull/41046
Started to see some failures with address sanitizer https://github.com/ClickHouse/ClickHouse/issues/41500

**Comment by CheSema** [comment]
thread sanitizer thread leak
similar stack as in https://github.com/ClickHouse/ClickHouse/issues/42583

**Comment by CheSema** [comment]
memory sanitizer 
https://s3.amazonaws.com/clickhouse-test-reports/42463/8a56beb74a4e7cc454d050772909cbbedcbfc8b6/stress_test__msan_/gdb.log

it seems as we do a lot of work at shutdown with high contention
https://github.com/ClickHouse/ClickHouse/issues/41831

**Pull request merged**
