### PR TITLE
Additional higher order functions to work with arrays

### PR DESCRIPTION
**Pull request by astudnev**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

I added couple functions to work with arrays, as i found no way to implement the functionality using the provided array functions.

1) cumulative sum with limit ( if acc value less than 0, zero is accumulated ). Ideal solution would be to implement a reduce function, which accepts 2 parameters - array and accumulating value, but i fail to program so far

2)  difference between values in array. This could be implemented using mapArray and couple other functions, but this will be nice to do in one call

### CODE REVIEW

**Comment by VadimPE** [comment]
Hi
1) Could you add tests, please? (You can see examples [here](https://github.com/yandex/ClickHouse/tree/master/dbms/tests/queries/0_stateless) and tutorial [here](https://github.com/yandex/ClickHouse/blob/master/docs/en/development/tests.md) )
2) Delete ci/default-config from your pr.

**Review by VadimPlh — COMMENTED** [review]
Hi, thanks for your PR!
1) Could you add tests, please? (You can see examples [here](https://github.com/yandex/ClickHouse/tree/master/dbms/tests/queries/0_stateless) and tutorial [here](https://github.com/yandex/ClickHouse/blob/master/docs/en/development/tests.md) )
2) Delete ci/default-config from your pr.
3) Please, add info about new functions to the beginning of the file.
4) On this simple test `SELECT arrayDifference([0, 100, 2])` result is [0,100,18446744073709551518]. I think the result of `arrayDifference()` should always be a sign.

**Comment by alexey-milovidov** [comment]
Do you have a time to do the required modifications?

**Comment by VadimPE** [comment]
#3009 Fix

**Pull request closed without merging**
