### PR TITLE
Revert "Revert "[experiment] maybe fix warnings in integration tests""

### PR DESCRIPTION
**Pull request by alesapin**
Reverts ClickHouse/ClickHouse#12011

### CODE REVIEW

**Comment by alesapin** [comment]
Now it's possible to test images in PR, so let's try again.

**Review by blinkov — APPROVED** [review]

**Comment by alesapin** [comment]
Ok, the error reproduces. Let's try to fix it.

**Comment by alexey-milovidov** [comment]
Still reproduces.

**Comment by alexey-milovidov** [comment]
Does not help.

**Pull request closed without merging**
