### PR TITLE
Add hints for HTTP handlers

### PR DESCRIPTION
**Pull request by rmarduga**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Add hints to HTTP handlers to help users avoid misspellings. For example, if a user mistakenly writes `/dashboad` instead of `/dashboard`, they will now get a hint that /dashboard is the correct handler.

This change will improve the user experience by making it easier for users to find the correct handlers.

See also #47662

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by robot-ch-test-poll1** [comment]
This is an automated comment for commit 3d4412421df0ecbbe4778f2c86641f30d4677352 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/53110/3d4412421df0ecbbe4778f2c86641f30d4677352/ci_running.html)
The overall status of the commit is 🔴 failure

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🔴 failure</td></tr>
</table>

**Review by CurtizJ — COMMENTED** [review]
In general OK.

**Comment by alexey-milovidov** [comment]
@rmarduga Why closed?

**Comment by rmarduga** [comment]
Prepared another PR #53248 that includes all of the changes in one.

**Review by CurtizJ — APPROVED** [review]

**Pull request merged**
