### PR TITLE
Allow query profiler period to be longer than 4 seconds

### PR DESCRIPTION
**Pull request by al13n321**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

It was limited to UINT32_MAX, and quietly overflowed if a bigger value was specified.

(Use case: set period to a very big number and trigger the signal manually in a debugger, to debug stack unwinding in signal handler at a particular address.)

### CODE REVIEW

**Comment by robot-ch-test-poll3** [comment]
*This is an automated comment for commit 51a2930b852bacfa7f91e1cc40004b5817e81129 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/65255/51a2930b852bacfa7f91e1cc40004b5817e81129/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>A Sync</td><td>If it fails, ask a maintainer for help</td><td>⏳ pending</td></tr>
<tbody>
</table>
<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>Checks correctness of the PR's body</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
```
QueryProfiler.cpp
Jun 14 04:45:27 /build/src/Common/QueryProfiler.cpp:180:85: error: consider replacing 'long' with 'int64' [google-runtime-int,-warnings-as-errors]
Jun 14 04:45:27   180 |     struct timespec interval{.tv_sec = time_t(period / TIMER_PRECISION), .tv_nsec = long(period % TIMER_PRECISION)};
Jun 14 04:45:27       |                                                                                     ^
Jun 14 04:45:27 /build/src/Common/QueryProfiler.cpp:181:88: error: consider replacing 'long' with 'int64' [google-runtime-int,-warnings-as-errors]
Jun 14 04:45:27   181 |     struct timespec offset{.tv_sec = time_t(period_rand / TIMER_PRECISION), .tv_nsec = long(period_rand % TIMER_PRECISION)};
Jun 14 04:45:27       |                                                                                        ^
```

**Comment by alexey-milovidov** [comment]
@al13n321, please check what is wrong with the failing test here.

**Comment by alexey-milovidov** [comment]
@al13n321, we need to fix this flaky test.

**Comment by alexey-milovidov** [comment]
@al13n321, the test "parallel_mv" was temporarily broken in the master; please update.

**Comment by alexey-milovidov** [comment]
@al13n321, tests have failed.

**Pull request merged**
