### PR TITLE
Fix bug with nested short-circuit functions

### LINKED ISSUE #38040: If statement not working correctly with decrypt function
Hi, I'm trying to filter by a encrypted column depending on a condition, but if statement is not working correctly and seems that the column is decrypted with both algorithms before checking the if statement. The table is partitioned by datetime, and it's only failing when datetime filters are also applied to the query. 

Here's an example:

`SELECT count()
FROM data_table
WHERE (if(has(array, 'a'), decrypt('aes-256-gcm', encrypted_column, 'key', 'iv'), decrypt('aes-256-cfb128', encrypted_column, 'key')) = 'value1') AND (datetime >= toDateTime('2022-06-14 05:35:36')) AND (datetime < toDateTime('2022-06-14 05:45:36'))`

The error is the following: 

`DB::Exception: Encrypted data is smaller than the size of additional data for AEAD mode, cannot decrypt.`

Which ClickHouse server version to use
21.12.3.32

### PR DESCRIPTION
**Pull request by Avogar**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in official stable or prestable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix bug with nested short-circuit functions that led to execution of arguments even if condition is false.
Closes https://github.com/ClickHouse/ClickHouse/issues/38040

### CODE REVIEW

**Comment by Avogar** [comment]
@Mergifyio update

**Comment by Avogar** [comment]
@Mergifyio update

**Review by nickitat — APPROVED** [review]
pls, check Stress test (undefined, actions) — Killed by signal (in clickhouse-server.log)

**Comment by Avogar** [comment]
Stress test failure - https://github.com/ClickHouse/ClickHouse/issues/38220

**Pull request merged**
