### PR TITLE
independent registration of database engines

### PR DESCRIPTION
**Pull request by bharatnc**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Allow registering database engines independently.

Rewrite DatabaseFactory to allow registering each database engine independently.

Related to #56557 and previously #9136

### CODE REVIEW

**Comment by robot-ch-test-poll1** [comment]
*This is an automated comment for commit de2b0e645f8e1f3be4f648505467606edd8e7278 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/58365/de2b0e645f8e1f3be4f648505467606edd8e7278/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/58365/de2b0e645f8e1f3be4f648505467606edd8e7278/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Review by alexey-milovidov — APPROVED** [review]
This looks perfect!

**Comment by bharatnc** [comment]
As a follow up, I was thinking of adding a table called `system.database_engines` which can fetch all the currently available and registered database engines from the factory instance (idea is similar to `system.table_engines`).

**Comment by alexey-milovidov** [comment]
@bharatnc, Yes, it will be very useful.

**Pull request merged**
