### PR TITLE
Clear Kafka's buffer if an invalid message is found.

### PR DESCRIPTION
**Pull request by bopohaa**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Category:
- Bug Fix

Short description:

Clearing the data buffer from the previous read operation that was completed with an error

Detailed description:

Problems may be due to incorrectly formed messages in the Kafka stream or due to inconsistency of the message scheme with the table schema in the database (such as inconsistency between the types of UInt and Int)

### CODE REVIEW

**Comment by bopohaa** [comment]
Perhaps this error is described in these tasks.
https://github.com/yandex/ClickHouse/issues/5957
https://github.com/yandex/ClickHouse/issues/4616
https://github.com/yandex/ClickHouse/issues/2480

**Comment by abyss7** [comment]
Thank you for the fix - will review it tomorrow in more detail

**Comment by alexey-milovidov** [comment]
@abyss7 Tomorrow?

**Comment by alexey-milovidov** [comment]
Today?

**Comment by alexey-milovidov** [comment]
@abyss7 ?

**Review by alexey-milovidov — APPROVED** [review]

**Pull request merged**
