### PR TITLE
Fix scalars create as select

### PR DESCRIPTION
**Pull request by KochetovNicolai**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by robot-clickhouse-ci-2** [comment]
*This is an automated comment for commit 920ba121febb0cb5f823d4b4d3897e4079bf1fcf with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/61998/920ba121febb0cb5f823d4b4d3897e4079bf1fcf/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

**Review by nickitat — APPROVED** [review]
lgtm

**Comment by KochetovNicolai** [comment]
ast fuzzer https://github.com/ClickHouse/ClickHouse/pull/62046

**Comment by KochetovNicolai** [comment]
Stateless tests (tsan) https://github.com/ClickHouse/ClickHouse/pull/62059

**Comment by clickgapai** [comment]
Hi @KochetovNicolai @nickitat — while reviewing this PR I found the following:

- **Coverage gap:** Multi-column scalar subquery in `CREATE TABLE/VIEW AS WITH (SELECT ...)` — only_analyze tuple branch is untested — https://github.com/ClickHouse/ClickHouse/pull/103965

Could you review the test PR and add the `can be tested` label if it looks good?
Happy to discuss — close anything that's wrong or already addressed.

**Pull request merged**
