### PR TITLE
Aquahash

### PR DESCRIPTION
**Pull request by olevino**
### Changelog category (leave one):
- New Feature

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Added new 128-bit hash function - AquaHash128

> Information about CI checks: https://clickhouse.tech/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by serxa** [comment]
cmake for split build is broken and looks like contrib/aquahash does not build with our gcc build yet

**Comment by serxa** [comment]
@mergifyio update

**Comment by serxa** [comment]
Darwin does not build, iirc it was okay before merging master. I'll rerun test just to be sure.

**Comment by serxa** [comment]
there is also issue with split build: `CMake Error: CMake can not determine linker language for target: aquahash`

**Comment by serxa** [comment]
GCC build is disabled currently, so there is no more problem with it.

**Comment by alexey-milovidov** [comment]
Abandoned.

**Pull request closed without merging**
