### PR TITLE
Parse tuples of tuples as literals

### PR DESCRIPTION
**Pull request by CurtizJ**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Performance Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Improved performance of queries with explicitly defined sets at right side of IN operator and tuples in the left side.

Detailed description / Documentation draft:
Addition to #9740.

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
Performance test is broken because the query is very long but @akuzm said that the target query speed up 75% with statistical confidence.

**Comment by qoega** [comment]
```
2020-04-21 02:55:39 00306_insert_values_and_expressions:                                    [ FAIL ] 0.64 sec. - return code 134
2020-04-21 02:55:39 Logical error: 'Unexpected literal type inside Array: Array(UInt8). It's a bug'.
2020-04-21 02:55:39 clickhouse-client: ../src/Common/Exception.cpp:40: DB::Exception::Exception(const std::string &, int): Assertion `false' failed.
2020-04-21 02:55:39 Aborted (core dumped)
```

**Comment by alexey-milovidov** [comment]
Waiting for fix of performance test by @akuzm

**Comment by akuzm** [comment]
> Waiting for fix of performance test by @akuzm

No need to wait -- download test results, open set_index-report.tsv, see that the query improved. The layout is exactly the same as for the table with changed performance -- time old, time new, difference in%, quantiles of randomization distribution (5%, 50%, 95%, 99%). The difference we observed is bigger than RD(99%), that means only a 1% chance to observe such value if the performance was the same. So probably the performance has changed. No confidence interval for the magnitude of change, yet. But given that it is a difference of medians of 13 or something runs, it should be representative enough.

The problem with long query name is fixed in master, by the way.

**Pull request merged**
