### PR TITLE
remove `metadata_version` ZooKeeper node creation from RMT restarting thread

### PR DESCRIPTION
**Pull request by mstetsyuk**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Remove the metadata_version ZooKeeper node creation from RMT restarting thread. The only scenario where we need to create this node is when the user updated from a version earlier than 20.4 straight to one later than 24.10. ClickHouse does not support upgrades that span more than a year, so we should throw an exception and ask the user to update gradually, instead of creating the node.

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Run only fuzzers related jobs (libFuzzer fuzzers, AST fuzzers, etc.)
- [ ]  Exclude: AST fuzzers
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-ch-test-poll1** [comment]
*This is an automated comment for commit 52fe2f18b08fdaff1d93abf2730096676eb55228 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/71385/52fe2f18b08fdaff1d93abf2730096676eb55228/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/57fde54f100785d9ffd54e2c9d572a9660884927/docs_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Comment by pamarcos** [comment]
@mstetsyuk could you please provide some context on why this is needed now?

**Comment by mstetsyuk** [comment]
@pamarcos, as discussed [here](https://github.com/ClickHouse/ClickHouse/pull/70297#discussion_r1824895558
), I've decided to make this change in a separate PR so that the main PR could be backported.

**Review by pamarcos — APPROVED** [review]
The removal of the code is fine, but I find the CHANGELOG entry hard to understand, so it's probably also hard to understand for others. For instance, there's no mention at all that the recovery of `metadata_version` has been removed only for ClickHouse versions older than 20.4

**Comment by mstetsyuk** [comment]
@pamarcos, understood, added a bit more context

**Pull request merged**
