### PR TITLE
ignore weak symbol under mac because it must be defined

### PR DESCRIPTION
**Pull request by ghost**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Build/Testing/Packaging Improvement

Detailed description / Documentation draft:
weak symbol in macos must be defined, which is opposite to linux.
it works for dbms/programs/main.cpp where inside_main is declaired but not for other main classes such as dbms/src/DataStreams/tests/collapsing_sorted_stream.cpp or unit tests.

### CODE REVIEW

**Comment by qoega** [comment]
Can you show how you reproduce problem without fix? I would check it on Mac

**Comment by huiwangcs** [comment]
@qoega you can run `dbms/src/DataStreams/tests/collapsing_sorted_stream.cpp` to check

**Comment by alexey-milovidov** [comment]
The fix looks Ok, but I cannot find `-U` flag in `man ld` or `man gold`.
Let's check - if the CI build will run (it is using `lld` linker), it's fine.

**Comment by alexey-milovidov** [comment]
Build is Ok.

**Pull request merged**
