### PR TITLE
CH local: Treat localhost:port as a remote database

### LINKED ISSUE #26712: clickhouse-local remote() fails with localhost on default port
**Describe the bug**

With a clickhouse server running on local at the default port (9000), this should work:
```
$ clickhouse-local -q "SELECT * FROM remote('127.0.0.1:9000', 'system.parts') LIMIT 3;"
Code: 60, e.displayText() = DB::Exception: Table system.parts doesn't exist (version 21.7.2.7 (official build))
```

Note that no tables can be accessed, not just system.parts.

**Does it reproduce on recent release?**

Yes, 21.7.2.7

**How to reproduce**

* Start a clickhouse server at default port
* Make any query with clickhouse-local to the clickhouse server using the `remote` function

**Expected behavior**

Clickhouse-local should be able to access it, just like clickhouse-client can with the same query.

**Additional context**

The problem only happens when using localhost and the default port. Starting the server at other port works.

The issue seems to be caused by incorrectly treating the address as local instead of as remote. We are working on a PR to fix it.

### PR DESCRIPTION
**Pull request by Algunenano**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Backward Incompatible Change

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Under clickhouse-local, always treat local addresses with a port as remote.

Detailed description / Documentation draft:

Before this change localhost:default_port would be treated as a self-connection, while now it will try to connect to a remote database. Connections to local addresses without port will still be considered local.

For example:
`remote('localhost', 'system.tables'` -> Self
`remote('127.0.0.1', 'system.tables')` -> Self
`remote('127.0.0.1:9000', 'system.tables')` -> External

Note that this only affects clickhouse-local.

I'm considering it a backward incompatible change since there was a test checking the old behaviour.

Closes https://github.com/ClickHouse/ClickHouse/issues/26712

### CODE REVIEW

**Comment by akuzm** [comment]
I think we already have logic for this -- all localhost IPs except .1 are treated as remote.

```clickhouse-local -q "SELECT * FROM remote('127.0.0.2', 'system.parts') LIMIT 3;"```

Is this sufficient?

**Comment by Algunenano** [comment]
> Is this sufficient?

What do you think @davidmanzanares? One issue it doesn't cover would be using `localhost:9000` or `myinternalhost.domain:9000`.

**Comment by davidmanzanares** [comment]
Oh, I didn't know about that.

Yes, for me it is sufficient. Although, personally, I think @Algunenano 's behavior is less error prone.

**Comment by Algunenano** [comment]
Added a commit to ignore a ASAN warning (not an error, it's just saying that it can't handle some things) which is already ignored in other places like stress tests.

**Review by akuzm — APPROVED** [review]

**Comment by akuzm** [comment]
The tests are flaky/broken in master.

**Pull request merged**
