### PR TITLE
system log tables support COMMENT

### LINKED ISSUE #33768: clickhouse server can not start up when set comment for query_log
**Describe the unexpected behaviour**
clickhouse server(22.1.1.2542) can not start up when set comment for query_log
**How to reproduce**
add comment for query_log in config.xml
```
<query_log>
<database>system</database>
<table>query_log</table>
             <engine>ENGINE = MergeTree PARTITION BY (event_date)    
                          ORDER BY (event_time) 
                          TTL event_date + INTERVAL 14 DAY DELETE
                          SETTINGS ttl_only_drop_parts=1                              
                          COMMENT 'xxx'
             </engine>
</query_log>
```
restart clickhouse-server:
2022.01.18 23:07:04.861218 [ 3415373 ] {} <Error> Application: Caught exception while loading metadata: Code: 62. DB::Exception: Syntax error (Storage to create table for query_log): failed at position 259 ('COMMENT') (line 5, col 31): COMMENT 'xxx'
             . Expected end of query. (SYNTAX_ERROR), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xa82bc3a in /usr/bin/clickhouse
1. DB::parseQueryAndMovePosition(DB::IParser&, char const*&, char const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, unsigned long, unsigned long) @ 0x14d6169f in /usr/bin/clickhouse
2. DB::SystemLogs::SystemLogs(std::__1::shared_ptr<DB::Context const>, Poco::Util::AbstractConfiguration const&) @ 0x13b996bb in /usr/bin/clickhouse
3. DB::Context::initializeSystemLogs() @ 0x134ac6af in /usr/bin/clickhouse
4. DB::Server::main(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) @ 0xa8b4b9d in /usr/bin/clickhouse
5. Poco::Util::Application::run() @ 0x17471aa6 in /usr/bin/clickhouse
6. DB::Server::run() @ 0xa8a71d1 in /usr/bin/clickhouse
7. mainEntryClickHouseServer(int, char**) @ 0xa8a4787 in /usr/bin/clickhouse
8. main @ 0xa825fea in /usr/bin/clickhouse
9. __libc_start_main @ 0x7f3e9d62f0b3 in ?
10. _start @ 0xa6acfae in /usr/bin/clickhouse
 (version 22.1.1.2542)

**Expected behavior**
Clickhouse server should be up when set comment for query_log. 
21.8 is ok.

### PR DESCRIPTION
**Pull request by xuyatian**
closes: https://github.com/ClickHouse/ClickHouse/issues/33768
Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
system log tables support COMMENT

> Information about CI checks: https://clickhouse.tech/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by kitaisreal** [comment]
@xuyatian it is not a bug fix, but improvement.

**Comment by xuyatian** [comment]
> @xuyatian it is not a bug fix, but improvement.

I see, changed to Improvement.

**Comment by kitaisreal** [comment]
@Mergifyio update

**Review by alexey-milovidov — APPROVED** [review]
The code LGTM.

**Comment by alexey-milovidov** [comment]
@kitaisreal has strong objections to merging this PR.

**Comment by kitaisreal** [comment]
Implemented in #34536.

**Pull request closed without merging**
