### PR TITLE
Acquire zero-copy shared lock before moving a part 

### PR DESCRIPTION
**Pull request by aalexfvk**
Acquiring zero-copy shared lock *after* moving part can lead to the following error if ZK is unavailable. After this error part remains on the destination disk without set shared zero-copy lock, which can end up with a data loss.

This PR proposes acquiring shared zero-copy lock *before* renaming cloned part on the disk and handle a few related fails.

```
Part 1725865200_11_19_1 was not fetched, we are the first who move it to another disk, so we will copy it       
[...]
Lock is lost, because session was expired. Path: /clickhouse/zero_copy/zero_copy_s3/9439ab61-2151-4ee6-8abe-0b0190ed3228/1725865200_11_19_1/part_exclusive_lock, message: sas-kb7npfrp4rp7heq0.db.yandex.net    zkutil::Lock    
[...]
Exception while executing background task {9439ab61-2151-4ee6-8abe-0b0190ed3228::lambda}: Code: 999. Coordination::Exception: Coordination error: Connection loss. (KEEPER_EXCEPTION), Stack trace (when copying this message, always include the lines below):\
\
0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000c624af7 in /usr/bin/clickhouse\
1. DB::Exception::Exception<char const*>(int, FormatStringHelperImpl<std::type_identity<char const*>::type>, char const*&&) @ 0x000000000af7875c in /usr/bin/clickhouse\
2. Coordination::Exception::Exception(Coordination::Error) @ 0x00000000137d6b87 in /usr/bin/clickhouse\
3. zkutil::ZooKeeper::tryMulti(std::vector<std::shared_ptr<Coordination::Request>, std::allocator<std::shared_ptr<Coordination::Request>>> const&, std::vector<std::shared_ptr<Coordination::Response>, std::allocator<std::shared_ptr<Coordination::Response>>>&) @ 0x00000000137e2962 in /usr/bin/clickhouse\
4. Coordination::Error DB::ZooKeeperWithFaultInjection::access<false, true, 1, DB::ZooKeeperWithFaultInjection::tryMulti(std::vector<std::shared_ptr<Coordination::Request>, std::allocator<std::shared_ptr<Coordination::Request>>> const&, std::vector<std::shared_ptr<Coordination::Response>, std::allocator<std::shared_ptr<Coordination::Response>>>&)::\'lambda\'(), Coordination::Error>(char const*, String const&, DB::ZooKeeperWithFaultInjection::tryMulti(std::vector<std::shared_ptr<Coordination::Request>, std::allocator<std::shared_ptr<Coordination::Request>>> const&, std::vector<std::shared_ptr<Coordination::Response>, std::allocator<std::shared_ptr<Coordination::Response>>>&)::\'lambda\'(), DB::ZooKeeperWithFaultInjection::FaultCleanupTypeImpl<Coordination::Error>::Type, std::function<void ()>) @ 0x0000000010ff3d8b in /usr/bin/clickhouse\
5. DB::ZooKeeperWithFaultInjection::tryMulti(std::vector<std::shared_ptr<Coordination::Request>, std::allocator<std::shared_ptr<Coordination::Request>>> const&, std::vector<std::shared_ptr<Coordination::Response>, std::allocator<std::shared_ptr<Coordination::Response>>>&) @ 0x0000000010ff3345 in /usr/bin/clickhouse\
6. DB::StorageReplicatedMergeTree::createZeroCopyLockNode(std::shared_ptr<DB::ZooKeeperWithFaultInjection> const&, String const&, int, bool, String const&, std::unordered_set<String, std::hash<String>, std::equal_to<String>, std::allocator<String>> const&) @ 0x0000000012850029 in /usr/bin/clickhouse\
7. DB::StorageReplicatedMergeTree::lockSharedData(DB::IMergeTreeDataPart const&, std::shared_ptr<DB::ZooKeeperWithFaultInjection> const&, bool, std::optional<DB::HardlinkedFiles>) const @ 0x0000000012851d1c in /usr/bin/clickhouse\
8. DB::StorageReplicatedMergeTree::lockSharedData(DB::IMergeTreeDataPart const&, bool, std::optional<DB::HardlinkedFiles>) const @ 0x00000000127ac9b9 in /usr/bin/clickhouse\
9. DB::MergeTreeData::swapActivePart(std::shared_ptr<DB::IMergeTreeDataPart const>, DB::DataPartsLock&) @ 0x0000000012c2a6a5 in /usr/bin/clickhouse\
10. DB::MergeTreePartsMover::swapClonedPart(DB::MergeTreePartsMover::TemporaryClonedPart&) const @ 0x0000000012d8774a in /usr/bin/clickhouse\
11. DB::MergeTreeData::moveParts(std::shared_ptr<DB::MergeTreeData::CurrentlyMovingPartsTagger> const&, bool) @ 0x0000000012c63d82 in /usr/bin/clickhouse\
12. bool std::__function::__policy_invoker<bool ()>::__call_impl<std::__function::__default_alloc_func<DB::MergeTreeData::scheduleDataMovingJob(DB::BackgroundJobsAssignee&)::$_0, bool ()>>(std::__function::__policy_storage const*) @ 0x0000000012c88152 in /usr/bin/clickhouse\
13. DB::ExecutableLambdaAdapter::executeStep() @ 0x00000000128834b2 in /usr/bin/clickhouse\
14. DB::MergeTreeBackgroundExecutor<DB::RoundRobinRuntimeQueue>::threadFunction() @ 0x0000000012bce0c0 in /usr/bin/clickhouse\
15. ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::worker(std::__list_iterator<ThreadFromGlobalPoolImpl<false>, void*>) @ 0x000000000c7036de in /usr/bin/clickhouse\
16. void std::__function::__policy_invoker<void ()>::__call_impl<std::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::\'lambda0\'()>(void&&)::\'lambda\'(), void ()>>(std::__function::__policy_storage const*) @ 0x000000000c70719c in /usr/bin/clickhouse\
17. void* std::__thread_proxy[abi:v15000]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void ThreadPoolImpl<std::thread>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::\'lambda0\'()>>(void*) @ 0x000000000c7059e4 in /usr/bin/clickhouse\
18. start_thread @ 0x00000000000076db in /lib/x86_64-linux-gnu/libpthread-2.27.so\
19. ? @ 0x000000000012161f in /lib/x86_64-linux-gnu/libc-2.27.so\
```

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Acquiring zero-copy shared lock before moving a part to zero-copy disk to prevent possible data loss if Keeper is unavailable.

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Run only fuzzers related jobs (libFuzzer fuzzers, AST fuzzers, etc.)
- [ ]  Exclude: AST fuzzers
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Review by vdimir — APPROVED** [review]
Looks reasonable to me, but probably someone more familiar with zero-copy could take a look

**Comment by robot-clickhouse** [comment]
*This is an automated comment for commit 57ceeb4a63535b184512ef0bc92d3332dafe6414 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/71845/57ceeb4a63535b184512ef0bc92d3332dafe6414/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/d38bd0df0aa277f4ec33b58f6832e45de596525c/docs_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Comment by aalexfvk** [comment]
@vdimir Hello! `test_storage_s3/test_invalid_env_credentials.py::test_with_invalid_environment_credentials` does not look like related, in my view. Is it a known problem ?

**Comment by vdimir** [comment]
Hm, I can't find many failures of this tests in [CI DB](https://play.clickhouse.com/play?user=play#CldJVEgKICAgIGZhbHNlIGFzIG9ubHlfbWFzdGVyClNFTEVDVCAqCkZST00gKApTRUxFQ1QKICAgIHB1bGxfcmVxdWVzdF9udW1iZXIgYXMgcHJudW0sCiAgICBzdWJzdHIoY29tbWl0X3NoYSwgMSw5KSBhcyBzaGEsCiAgICByb3VuZCh0ZXN0X2R1cmF0aW9uX21zIC8gMTAwMCwgMikgYXMgZHVyLAogICAgY2hlY2tfc3RhcnRfdGltZSwKICAgIGZvcm1hdFJlYWRhYmxlVGltZURlbHRhKGludERpdihub3coKSAtIGNoZWNrX3N0YXJ0X3RpbWUsIDM2MDApICogMzYwMCkgYXMgYWdvLAogICAgY2hlY2tfbmFtZSwKICAgIHRlc3RfbmFtZSwKICAgIHJlcG9ydF91cmwKRlJPTSBjaGVja3MKV0hFUkUgMQogICAgQU5EIGNoZWNrX3N0YXJ0X3RpbWUgPj0gbm93KCkgLSBJTlRFUlZBTCA3IERBWQogICAgQU5EIChwdWxsX3JlcXVlc3RfbnVtYmVyID0gMCBPUiBub3Qgb25seV9tYXN0ZXIpCiAgICBBTkQgdGVzdF9zdGF0dXMgIT0gJ1NLSVBQRUQnCiAgICBBTkQgdGVzdF9zdGF0dXMgTElLRSAnRiUnCiAgICBBTkQgY2hlY2tfc3RhdHVzICE9ICdzdWNjZXNzJwopCldIRVJFIHRlc3RfbmFtZSBsaWtlICcldGVzdF9zdG9yYWdlX3MzL3Rlc3RfaW52YWxpZF9lbnZfY3JlZGVudGlhbHMucHklJwpPUkRFUiBCWSBjaGVja19zdGFydF90aW1lIERFU0MsIGNoZWNrX25hbWUsIHRlc3RfbmFtZQ==). But indeed doesn't look related, I'll rerun CI and I'll take a look on logs of this failure in the meantime

**Comment by aalexfvk** [comment]
It looks like `test_backup_restore_on_cluster/test.py::test_tables_dependency` was encountered in other PRs.

**Comment by aalexfvk** [comment]
@vdimir Is it possible to backport this changes ? Or it is too vast.

**Comment by vdimir** [comment]
I'll add the label and then let's see on backport PRs state. Are any particular versions are crucial?
Now I need to fix `CH Inc sync` first to merge this PR

**Comment by aalexfvk** [comment]
At least LTS actual versions 24.3, 24.8

**Comment by vdimir** [comment]
@aalexfvk could you please skim trough backports and check if I resolved conflicts properly. 
Especially I doubt about `else if (wait_for_move_if_zero_copy)`

https://github.com/ClickHouse/ClickHouse/pull/72141/files#diff-b7d33a7abda5f3365d5e4fb58ca98b756f6401372b2e2d5eb449a2bd3444fb5eL7813

**Comment by aalexfvk** [comment]
> @aalexfvk could you please skim trough backports and check if I resolved conflicts properly. Especially I doubt about `else if (wait_for_move_if_zero_copy)`
> 
> https://github.com/ClickHouse/ClickHouse/pull/72141/files#diff-b7d33a7abda5f3365d5e4fb58ca98b756f6401372b2e2d5eb449a2bd3444fb5eL7813

I've reviewed. All is OK.

**Comment by vdimir** [comment]
@aalexfvk could you please check `test_move_shared_lock_fail_keeper_unavailable`, it's a bit [flaky in the CI](https://play.clickhouse.com/play?user=play#CldJVEgKICAgIGZhbHNlIGFzIG9ubHlfbWFzdGVyClNFTEVDVCAqCkZST00gKApTRUxFQ1QKICAgIHB1bGxfcmVxdWVzdF9udW1iZXIgYXMgcHJudW0sCiAgICBzdWJzdHIoY29tbWl0X3NoYSwgMSw5KSBhcyBzaGEsCiAgICByb3VuZCh0ZXN0X2R1cmF0aW9uX21zIC8gMTAwMCwgMikgYXMgZHVyLAogICAgY2hlY2tfc3RhcnRfdGltZSwKICAgIGZvcm1hdFJlYWRhYmxlVGltZURlbHRhKGludERpdihub3coKSAtIGNoZWNrX3N0YXJ0X3RpbWUsIDM2MDApICogMzYwMCkgYXMgYWdvLAogICAgY2hlY2tfbmFtZSwKICAgIHRlc3RfbmFtZSwKICAgIHJlcG9ydF91cmwKRlJPTSBjaGVja3MKV0hFUkUgMQogICAgQU5EIGNoZWNrX3N0YXJ0X3RpbWUgPj0gbm93KCkgLSBJTlRFUlZBTCA3IERBWQogICAgQU5EIChwdWxsX3JlcXVlc3RfbnVtYmVyID0gMCBPUiBub3Qgb25seV9tYXN0ZXIpCiAgICBBTkQgdGVzdF9zdGF0dXMgIT0gJ1NLSVBQRUQnCiAgICBBTkQgdGVzdF9zdGF0dXMgTElLRSAnRiUnCiAgICBBTkQgY2hlY2tfc3RhdHVzICE9ICdzdWNjZXNzJwopCldIRVJFIHRlc3RfbmFtZSBsaWtlICcldGVzdF9tb3ZlX3NoYXJlZF9sb2NrX2ZhaWxfa2VlcGVyX3VuYXZhaWxhYmxlJScKT1JERVIgQlkgY2hlY2tfc3RhcnRfdGltZSBERVNDLCBjaGVja19uYW1lLCB0ZXN0X25hbWUKRk9STUFUIE1hcmtkb3duCg==)

<details>
<summary>CI Reports</summary>


| prnum | sha | dur | check_start_time | ago | check_name | test_name | report_url |
|-:|:-|-:|-:|:-|:-|:-|:-|
| 72262 | e27428634 | 15.26 | 2024-11-22 15:11:44 | 2 hours | Integration tests (aarch64) [6/6] | test_s3_zero_copy_replication/test.py::test_move_shared_lock_fail_keeper_unavailable | https://s3.amazonaws.com/clickhouse-test-reports/72262/e274286348d32ea34999a270fcc56131db4d768c/integration_tests__aarch64__[6_6].html |
| 72259 | bef6f9269 | 16.75 | 2024-11-22 13:28:30 | 3 hours | Integration tests (asan, old analyzer) [1/6] | test_s3_zero_copy_replication/test.py::test_move_shared_lock_fail_keeper_unavailable | https://s3.amazonaws.com/clickhouse-test-reports/72259/bef6f926994640e1683b46c563d1174c348c2673/integration_tests__asan__old_analyzer__[1_6].html |
| 72229 | d67f2644c | 12.5 | 2024-11-21 23:57:26 | 17 hours | Integration tests (aarch64) [6/6] | test_s3_zero_copy_replication/test.py::test_move_shared_lock_fail_keeper_unavailable | https://s3.amazonaws.com/clickhouse-test-reports/72229/d67f2644cf73eef27d1b9a771962d4db42ddf4fa/integration_tests__aarch64__[6_6].html |
| 71598 | 5183d4226 | 15.13 | 2024-11-21 18:30:08 | 22 hours | Integration tests (aarch64) [6/6] | test_s3_zero_copy_replication/test.py::test_move_shared_lock_fail_keeper_unavailable | https://s3.amazonaws.com/clickhouse-test-reports/71598/5183d42261b539805142bb5a21b3a911f8b77d91/integration_tests__aarch64__[6_6].html |
| 65401 | ddb8f3d57 | 29.28 | 2024-11-21 16:39:32 | 1 day | Integration tests (tsan) [1/6] | test_s3_zero_copy_replication/test.py::test_move_shared_lock_fail_keeper_unavailable | https://s3.amazonaws.com/clickhouse-test-reports/65401/ddb8f3d57f8112748ce1f8bab858997b5d1c8f77/integration_tests__tsan__[1_6].html |
| 0 | e0f8b8d35 | 15.69 | 2024-11-21 09:05:29 | 1 day and 8 hours | Integration tests (asan, old analyzer) [1/6] | test_s3_zero_copy_replication/test.py::test_move_shared_lock_fail_keeper_unavailable | https://s3.amazonaws.com/clickhouse-test-reports/0/e0f8b8d35107f96002d8c7d31026f75f44a3fa1c/integration_tests__asan__old_analyzer__[1_6].html |
| 72123 | 287aeba8e | 17.89 | 2024-11-20 23:54:32 | 1 day and 17 hours | Integration tests (tsan) [4/6] | test_s3_zero_copy_replication/test.py::test_move_shared_lock_fail_keeper_unavailable | https://s3.amazonaws.com/clickhouse-test-reports/72123/287aeba8eb81bf52d70246a43adf302ed01af533/integration_tests__tsan__[4_6].html |
| 0 | 64ea850e5 | 12.29 | 2024-11-20 15:38:29 | 2 days and 1 hour | Integration tests (aarch64) [6/6] | test_s3_zero_copy_replication/test.py::test_move_shared_lock_fail_keeper_unavailable | https://s3.amazonaws.com/clickhouse-test-reports/0/64ea850e5bc22899e5d6870e5523e1a821c12263/integration_tests__aarch64__[6_6].html |
| 72126 | e68011e8f | 16.82 | 2024-11-20 11:08:57 | 2 days and 6 hours | Integration tests (asan, old analyzer) [2/6] | test_s3_zero_copy_replication/test.py::test_move_shared_lock_fail_keeper_unavailable | https://s3.amazonaws.com/clickhouse-test-reports/72126/e68011e8f59894a240c04c18d283aba05cd5d6cc/integration_tests__asan__old_analyzer__[2_6].html |


</details>


Fails with:

<details><summary>Error message</summary>
```
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <helpers.cluster.ClickHouseInstance object at 0x7f83b49e1600>
sql = "ALTER TABLE table_test_move_shared_lock_fail_keeper_unavailable MOVE PARTITION '2024-10-23' TO VOLUME 'external'"
stdin = None, timeout = None, settings = None, user = None, password = None
database = None, host = None, ignore_error = False, retry_count = 20
sleep_time = 0.5
check_callback = <function ClickHouseInstance.<lambda> at 0x7f83b4abf7f0>

    def query_with_retry(
        self,
        sql,
        stdin=None,
        timeout=None,
        settings=None,
        user=None,
        password=None,
        database=None,
        host=None,
        ignore_error=False,
        retry_count=20,
        sleep_time=0.5,
        check_callback=lambda x: True,
    ):
        # logging.debug(f"Executing query {sql} on {self.name}")
        result = None
        exception_msg = ""
        for i in range(retry_count):
            try:
                result = self.query(
                    sql,
                    stdin=stdin,
                    timeout=timeout,
                    settings=settings,
                    user=user,
                    password=password,
                    database=database,
                    host=host,
                    ignore_error=ignore_error,
                )
                if check_callback(result):
                    return result
                time.sleep(sleep_time)
            except QueryRuntimeException as ex:
                exception_msg = f"{type(ex).__name__}: {str(ex)}"
                # Container is down, this is likely due to server crash.
                if "No route to host" in str(ex):
                    raise
                time.sleep(sleep_time)
            except Exception as ex:
                # logging.debug("Retry {} got exception {}".format(i + 1, ex))
                exception_msg = f"{type(ex).__name__}: {str(ex)}"
                time.sleep(sleep_time)
    
        if result is not None:
            return result
>       raise Exception(f"Can't execute query {sql}\n{exception_msg}")
E       Exception: Can't execute query ALTER TABLE table_test_move_shared_lock_fail_keeper_unavailable MOVE PARTITION '2024-10-23' TO VOLUME 'external'
E       QueryRuntimeException: Client failed! Return code: 223, stderr: Received exception from server (version 24.11.1):
E       Code: 479. DB::Exception: Received from 172.16.4.9:9000. DB::Exception: All parts of partition '1729641600' are already on volume 'external'. Stack trace:
E       
E       0. ./contrib/llvm-project/libcxx/include/exception:141: Poco::Exception::Exception(String const&, int) @ 0x0000000036b2bfb4
E       1. ./build_docker/./src/Common/Exception.cpp:109: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000001b495c69
E       2. DB::Exception::Exception(PreformattedMessage&&, int) @ 0x000000000aec5625
E       3. ./src/Common/Exception.h:129: DB::Exception::Exception<String&, String const&>(int, FormatStringHelperImpl<std::type_identity<String&>::type, std::type_identity<String const&>::type>, String&, String const&) @ 0x000000001baa683a
E       4. ./build_docker/./src/Storages/MergeTree/MergeTreeData.cpp:5401: DB::MergeTreeData::movePartitionToVolume(std::shared_ptr<DB::IAST> const&, String const&, bool, std::shared_ptr<DB::Context const>) @ 0x000000002ea7242c
E       5. ./build_docker/./src/Storages/MergeTree/MergeTreeData.cpp:5530: DB::MergeTreeData::alterPartition(std::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::vector<DB::PartitionCommand, std::allocator<DB::PartitionCommand>> const&, std::shared_ptr<DB::Context const>) @ 0x000000002ea753bb
E       6. ./build_docker/./src/Interpreters/InterpreterAlterQuery.cpp:245: DB::InterpreterAlterQuery::executeToTable(DB::ASTAlterQuery const&) @ 0x000000002a75d247
E       7. ./build_docker/./src/Interpreters/InterpreterAlterQuery.cpp:80: DB::InterpreterAlterQuery::execute() @ 0x000000002a758cf1
E       8. ./build_docker/./src/Interpreters/executeQuery.cpp:1366: DB::executeQueryImpl(char const*, char const*, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum, DB::ReadBuffer*) @ 0x000000002b7cfe59
E       9. ./build_docker/./src/Interpreters/executeQuery.cpp:1533: DB::executeQuery(String const&, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum) @ 0x000000002b7c88a5
E       10. ./build_docker/./src/Server/TCPHandler.cpp:654: DB::TCPHandler::runImpl() @ 0x000000002f776dad
E       11. ./build_docker/./src/Server/TCPHandler.cpp:2586: DB::TCPHandler::run() @ 0x000000002f7a6733
E       12. ./build_docker/./base/poco/Net/src/TCPServerConnection.cpp:40: Poco::Net::TCPServerConnection::start() @ 0x0000000036d09b4f
E       13. ./build_docker/./base/poco/Net/src/TCPServerDispatcher.cpp:115: Poco::Net::TCPServerDispatcher::run() @ 0x0000000036d0a737
E       14. ./build_docker/./base/poco/Foundation/src/ThreadPool.cpp:205: Poco::PooledThread::run() @ 0x0000000036c0c4bc
E       15. ./base/poco/Foundation/src/Thread_POSIX.cpp:335: Poco::ThreadImpl::runnableEntry(void*) @ 0x0000000036c06608
E       16. asan_thread_start(void*) @ 0x000000000ae78059
E       17. ? @ 0x00007f8eaa154ac3
E       18. ? @ 0x00007f8eaa1e6850
E       . (UNKNOWN_DISK)
E       (query: ALTER TABLE table_test_move_shared_lock_fail_keeper_unavailable MOVE PARTITION '2024-10-23' TO VOLUME 'external')
```
</details>

**Pull request merged**
