### PR TITLE
Optional secured communication between ClickHouse and Zookeeper

### PR DESCRIPTION
**Pull request by xzkostyan**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- New Feature

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Optional secured communication between ClickHouse and Zookeeper

Solves https://github.com/ClickHouse/ClickHouse/issues/10174.

We need options `ssl.keyStore.location`, `ssl.keyStore.password` and `ssl.trustStore.location`, `ssl.trustStore.password` for communication with client (ClickHouse) over SSL.

These options are available from Zookeeper version 3.5.2.

Official zookeeper docker image have no SSL does not provide flexible customization of these options. However you always can pass whole `zoo.cfg`  instead of generating it in entrypoint.

For testing you can use pre-built image `xzkostyan/zookeeper:3.5.7-ssl`:

```
docker pull xzkostyan/zookeeper:3.5.7-ssl
```

Or build custom zookeeper image with files listed below:

```
docker build -f Dockerfile . -t zookeeper-ssl
```

Dockerfile

```
FROM openjdk:11-jre-slim

ENV ZOO_CONF_DIR=/conf \
    ZOO_DATA_DIR=/data \
    ZOO_DATA_LOG_DIR=/datalog \
    ZOO_LOG_DIR=/logs \
    ZOO_TICK_TIME=2000 \
    ZOO_INIT_LIMIT=5 \
    ZOO_SYNC_LIMIT=2 \
    ZOO_AUTOPURGE_PURGEINTERVAL=0 \
    ZOO_AUTOPURGE_SNAPRETAINCOUNT=3 \
    ZOO_MAX_CLIENT_CNXNS=60 \
    ZOO_STANDALONE_ENABLED=true \
    ZOO_ADMINSERVER_ENABLED=true \
    ZOO_SERVER_CNXN_FACTORY=org.apache.zookeeper.server.NettyServerCnxnFactory

# Add a user with an explicit UID/GID and create necessary directories
RUN set -eux; \
    groupadd -r zookeeper --gid=1000; \
    useradd -r -g zookeeper --uid=1000 zookeeper; \
    mkdir -p "$ZOO_DATA_LOG_DIR" "$ZOO_DATA_DIR" "$ZOO_CONF_DIR" "$ZOO_LOG_DIR"; \
    chown zookeeper:zookeeper "$ZOO_DATA_LOG_DIR" "$ZOO_DATA_DIR" "$ZOO_CONF_DIR" "$ZOO_LOG_DIR"

# Install required packges
RUN set -eux; \
    apt-get update; \
    DEBIAN_FRONTEND=noninteractive \
    apt-get install -y --no-install-recommends \
        ca-certificates \
        dirmngr \
        gosu \
        gnupg \
        netcat \
        wget; \
    rm -rf /var/lib/apt/lists/*; \
# Verify that gosu binary works
    gosu nobody true

ARG GPG_KEY=3D296268A36FACA1B7EAF110792D43153B5B5147
ARG SHORT_DISTRO_NAME=zookeeper-3.5.7
ARG DISTRO_NAME=apache-zookeeper-3.5.7-bin

# Download Apache Zookeeper, verify its PGP signature, untar and clean up
RUN set -eux; \
    ddist() { \
        local f="$1"; shift; \
        local distFile="$1"; shift; \
        local success=; \
        local distUrl=; \
        for distUrl in \
            'https://www.apache.org/dyn/closer.cgi?action=download&filename=' \
            https://www-us.apache.org/dist/ \
            https://www.apache.org/dist/ \
            https://archive.apache.org/dist/ \
        ; do \
            if wget -q -O "$f" "$distUrl$distFile" && [ -s "$f" ]; then \
                success=1; \
                break; \
            fi; \
        done; \
        [ -n "$success" ]; \
    }; \
    ddist "$DISTRO_NAME.tar.gz" "zookeeper/$SHORT_DISTRO_NAME/$DISTRO_NAME.tar.gz"; \
    ddist "$DISTRO_NAME.tar.gz.asc" "zookeeper/$SHORT_DISTRO_NAME/$DISTRO_NAME.tar.gz.asc"; \
    export GNUPGHOME="$(mktemp -d)"; \
    gpg --keyserver ha.pool.sks-keyservers.net --recv-key "$GPG_KEY" || \
    gpg --keyserver pgp.mit.edu --recv-keys "$GPG_KEY" || \
    gpg --keyserver keyserver.pgp.com --recv-keys "$GPG_KEY"; \
    gpg --batch --verify "$DISTRO_NAME.tar.gz.asc" "$DISTRO_NAME.tar.gz"; \
    tar -zxf "$DISTRO_NAME.tar.gz"; \
    mv "$DISTRO_NAME/conf/"* "$ZOO_CONF_DIR"; \
    rm -rf "$GNUPGHOME" "$DISTRO_NAME.tar.gz" "$DISTRO_NAME.tar.gz.asc"; \
    chown -R zookeeper:zookeeper "/$DISTRO_NAME"

WORKDIR $DISTRO_NAME
VOLUME ["$ZOO_DATA_DIR", "$ZOO_DATA_LOG_DIR", "$ZOO_LOG_DIR"]

EXPOSE 2181 2281 2888 3888 8080

ENV PATH=$PATH:/$DISTRO_NAME/bin \
    ZOOCFGDIR=$ZOO_CONF_DIR

COPY docker-entrypoint.sh /
ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["zkServer.sh", "start-foreground"]
```

docker-entrypoint.sh

```bash
#!/bin/bash

set -e

# Allow the container to be started with `--user`
if [[ "$1" = 'zkServer.sh' && "$(id -u)" = '0' ]]; then
    chown -R zookeeper "$ZOO_DATA_DIR" "$ZOO_DATA_LOG_DIR" "$ZOO_LOG_DIR" "$ZOO_CONF_DIR"
    exec gosu zookeeper "$0" "$@"
fi

# Generate the config only if it doesn't exist
if [[ ! -f "$ZOO_CONF_DIR/zoo.cfg" ]]; then
    CONFIG="$ZOO_CONF_DIR/zoo.cfg"
    {
        echo "dataDir=$ZOO_DATA_DIR" 
        echo "dataLogDir=$ZOO_DATA_LOG_DIR"

        echo "tickTime=$ZOO_TICK_TIME"
        echo "initLimit=$ZOO_INIT_LIMIT"
        echo "syncLimit=$ZOO_SYNC_LIMIT"

        echo "autopurge.snapRetainCount=$ZOO_AUTOPURGE_SNAPRETAINCOUNT"
        echo "autopurge.purgeInterval=$ZOO_AUTOPURGE_PURGEINTERVAL"
        echo "maxClientCnxns=$ZOO_MAX_CLIENT_CNXNS"
        echo "standaloneEnabled=$ZOO_STANDALONE_ENABLED"
        echo "admin.enableServer=$ZOO_ADMINSERVER_ENABLED"
    } >> "$CONFIG"
    if [[ -z $ZOO_SERVERS ]]; then
      ZOO_SERVERS="server.1=localhost:2888:3888;2181"
    fi

    for server in $ZOO_SERVERS; do
        echo "$server" >> "$CONFIG"
    done

    if [[ -n $ZOO_4LW_COMMANDS_WHITELIST ]]; then
        echo "4lw.commands.whitelist=$ZOO_4LW_COMMANDS_WHITELIST" >> "$CONFIG"
    fi

    if [[ -n $ZOO_SSL_QUORUM ]]; then
        {
            echo "sslQuorum=$ZOO_SSL_QUORUM"
            echo "serverCnxnFactory=$ZOO_SERVER_CNXN_FACTORY"
            echo "ssl.quorum.keyStore.location=$ZOO_SSL_QUORUM_KEYSTORE_LOCATION"
            echo "ssl.quorum.keyStore.password=$ZOO_SSL_QUORUM_KEYSTORE_PASSWORD"
            echo "ssl.quorum.trustStore.location=$ZOO_SSL_QUORUM_TRUSTSTORE_LOCATION"
            echo "ssl.quorum.trustStore.password=$ZOO_SSL_QUORUM_TRUSTSTORE_PASSWORD"
        } >> "$CONFIG"
    fi

    if [[ -n $ZOO_PORT_UNIFICATION ]]; then
        echo "portUnification=$ZOO_PORT_UNIFICATION" >> "$CONFIG"
    fi

    if [[ -n $ZOO_SECURE_CLIENT_PORT ]]; then
        {
            echo "secureClientPort=$ZOO_SECURE_CLIENT_PORT"
            echo "serverCnxnFactory=$ZOO_SERVER_CNXN_FACTORY"
            echo "ssl.keyStore.location=$ZOO_SSL_KEYSTORE_LOCATION"
            echo "ssl.keyStore.password=$ZOO_SSL_KEYSTORE_PASSWORD"
            echo "ssl.trustStore.location=$ZOO_SSL_TRUSTSTORE_LOCATION"
            echo "ssl.trustStore.password=$ZOO_SSL_TRUSTSTORE_PASSWORD"
        } >> "$CONFIG"
    fi

    if [[ -n $ZOO_CLIENT_PORT_UNIFICATION ]]; then
        echo "client.portUnification=$ZOO_CLIENT_PORT_UNIFICATION" >> "$CONFIG"
    fi
fi

# Write myid only if it doesn't exist
if [[ ! -f "$ZOO_DATA_DIR/myid" ]]; then
    echo "${ZOO_MY_ID:-1}" > "$ZOO_DATA_DIR/myid"
fi

exec "$@"
```

Generate client certificate for ClickHouse

```
openssl req -subj "/CN=clickhouse" -new -newkey rsa:2048 -days 365 -nodes -x509 -keyout /etc/clickhouse-server/client.key -out /etc/clickhouse-server/client.crt
```

Generate keystore for Zookeeper

```
keytool -genkeypair -alias zookeeper -keyalg RSA -validity 365 -keysize 2048 -dname "cn=zookeeper" -keypass password -keystore zookeeper.p12 -storepass password -deststoretype pkcs12
```

Export certificate from Zookeeper keystore

```
openssl pkcs12 -in zookeeper.p12 -nokeys -out zookeeper.crt -password pass:password
```

Add ClickHouse certificate to Zookeeper trusted store

```
keytool -importcert -alias zookeeper -file /etc/clickhouse-server/client.crt -keystore truststore.p12 -storepass password -noprompt -deststoretype pkcs12
```

Run docker container
```
docker run --hostname test -p 2281:2281 -p 2181:2181 -v /mnt/docker/zookeeper-certs/:/certs -e ZOO_SSL_KEYSTORE_LOCATION=/certs/zookeeper.p12 -e ZOO_SSL_KEYSTORE_PASSWORD=password -e ZOO_SSL_TRUSTSTORE_LOCATION=/certs/truststore.p12 -e ZOO_SSL_TRUSTSTORE_PASSWORD=password -e ZOO_SECURE_CLIENT_PORT=2281 zookeeper-ssl 
```

You have two options how to handle custom certificate verification on ClickHouse-side:

1) Turn off certificate verification.

Client section in config.xml will look like:

```xml
        <client>
            <certificateFile>/etc/clickhouse-server/client.crt</certificateFile>
            <privateKeyFile>/etc/clickhouse-server/client.key</privateKeyFile>
            <loadDefaultCAFile>true</loadDefaultCAFile>
            <cacheSessions>true</cacheSessions>
            <disableProtocols>sslv2,sslv3</disableProtocols>
            <preferServerCiphers>true</preferServerCiphers>
            <verificationMode>none</verificationMode> 
            <invalidCertificateHandler>
                <name>RejectCertificateHandler</name>
            </invalidCertificateHandler>
        </client>
```

2) Add zookeeper.crt to trusted certificates:

```
sudo cp zookeeper.crt /usr/local/share/ca-certificates/zookeeper.crt
sudo update-ca-certificates
```

Client section in config.xml will look like:

```xml
        <client>
            <certificateFile>/etc/clickhouse-server/client.crt</certificateFile>
            <privateKeyFile>/etc/clickhouse-server/client.key</privateKeyFile>
            <loadDefaultCAFile>true</loadDefaultCAFile>
            <cacheSessions>true</cacheSessions>
            <disableProtocols>sslv2,sslv3</disableProtocols>
            <preferServerCiphers>true</preferServerCiphers>
            <invalidCertificateHandler>
                <name>RejectCertificateHandler</name>
            </invalidCertificateHandler>
        </client>
```

Add zookeeper to ClickHouse config with some cluster and macros:

```xml
<yandex>
    <zookeeper>
        <node>
            <host>localhost</host>
            <port>2281</port>
            <secure>1</secure>
        </node>
    </zookeeper>
</yandex>
```

Start `clickhouse-server`. In logs you should see:

```
<Trace> ZooKeeper: initialized, hosts: secure://localhost:2281
```

Prefix `secure://` indicates that connection is secured by SSL.

To ensure traffic is encrypted run tcpdump on secured port:

```
tcpdump -i any dst port 2281 -nnXS
```

And query in `clickhouse-client`

```sql
SELECT * FROM system.zookeeper WHERE path = '/';
```

On unencrypted connection you will see in tcpdump output something like this

```
..../zookeeper/q
uota.
```

On encrypted connection you should not see this.

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]
The code LGTM... if it works :)

**Comment by alexey-milovidov** [comment]
Minor issue with the list of libraries to link with test util:
https://clickhouse-builds.s3.yandex.net/10184/c9542b66018bc2e0ca124572642af364f627ebcb/build_log_650442673_1586564198.txt

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
Test has passed.

**Comment by adevyatova** [comment]
Internal documentation ticket: DOCSUP-12872

**Pull request merged**
