### PR TITLE
Run three nodes with Replicated database and NuKeeper in CI

### PR DESCRIPTION
**Pull request by tavplubix**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Detailed description / Documentation draft:
Depends on #22274

### CODE REVIEW

**Comment by alesapin** [comment]
Looks like with `force_fsync` NuKeeper doesn't work properly on sandbox HDDs.

**Comment by tavplubix** [comment]
`01396_inactive_replica_cleanup_nodes_zookeeper` - need fix test
`01149_zookeeper_mutation_stuck_after_replace_partition` - something strange happened, test is probably flaky
`01079_parallel_alter_add_drop_column_zookeeper` - Timeout - DDLWorker hung due to `All connection tries failed while connecting to ZooKeeper`
`01018_ddl_dictionaries_concurrent_requrests` - database `test_ha0hh4` was not created due to `Coordination::Exception: Operation timeout, path: /clickhouse`
`00992_system_parts_race_condition_zookeeper_long` - `Coordination::Exception: Operation timeout, path: /test/clickhouse/db/default/log/query-0000000032`
`00965_set_index_string_functions` - database `test_1jv5ht` was not created - `Coordination::Exception: Operation timeout, path: /clickhouse`
`00732_quorum_insert_lost_part_zookeeper` - ` Replica doesn't have part 20181115_0_0_0 which was successfully written to quorum of other replicas. Send query to another replica or disable 'select_sequential_consistency' setting` - seems like part was written to another replica

**Comment by tavplubix** [comment]
Functional stateless tests (release, DatabaseReplicated) — fail: 0, passed: 2781, skipped: 105
Functional stateful tests (release, DatabaseReplicated) — fail: 0, passed: 108, skipped: 3

**Comment by tavplubix** [comment]
00652_replicated_mutations_default_database_zookeeper - seems like `SETTINGS` clause does not work with `ALTER` query
00620_optimize_on_nonleader_replica_zookeeper - need `SYSTEM SYNC REPLICA rename1` before the first select

**Comment by tavplubix** [comment]
Functional stateless tests (release, DatabaseReplicated) — fail: 0, passed: 2784, skipped: 107 
Functional stateful tests (release, DatabaseReplicated) — fail: 0, passed: 108, skipped: 3

**Comment by alesapin** [comment]
Need to merge with  #22274.

**Comment by tavplubix** [comment]
Functional stateful tests (release, DatabaseReplicated) — fail: 0, passed: 109, skipped: 3 
Functional stateless tests (release, DatabaseReplicated) — fail: 0, passed: 2812, skipped: 107

**Review by alesapin — APPROVED** [review]

**Comment by alesapin** [comment]
Waiting for tests.

**Comment by alesapin** [comment]
Need to fix flaky check?

**Pull request merged**
