### PR TITLE
Mongo Atlas URI Support

### PR DESCRIPTION
**Pull request by manish53**
I have already pulled request in poco c++ github project to include ssl enable uri support.
### Poco-MongoDB update for atlas uri :
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en
Here are the files in which modifications are made in order to connect to mongo atlas through uri. In latest version of poco uri support for ssl is not there hence i've implemented securesocketstream for ssl support.

**Poco Pull request link** :
https://github.com/pocoproject/poco/pull/2701

### For **ClickHouse** :

**### MongoDBDictionarySource.cpp**

auto  getConnection(const std::string & host,UInt16 port,const std::string & uri){   
    if(uri.empty()){
       //cout << "Getting connection with IP:PORT format.";
       auto conn= std::make_shared<Poco::MongoDB::Connection>(host, port);
       return conn;
    }
    else {
       //cout << "Getting connection with URI format.";
       Poco::MongoDB::Connection::SocketFactory SF;
       auto conn= std::make_shared<Poco::MongoDB::Connection>(uri,SF);
       return conn;
    }
}

std::string getDB(const std::string & tempuri){
  if(tempuri.empty()){
      return tempuri;
  }
  else {
      Poco::URI theURI(tempuri);
      std::string databaseName = theURI.getPath();
      if (!databaseName.empty() && databaseName[0] == '/') databaseName.erase(0, 1);
      if (databaseName.empty()) databaseName = "admin";
      return databaseName;
  }
}

MongoDBDictionarySource::MongoDBDictionarySource(
    const DictionaryStructure & dict_struct,
    const std::string & host,
    UInt16 port,
    const std::string & user,
    const std::string & password,
    const std::string & method,
    const std::string & db,
    const std::string & collection,
    const std::string & uri,
    const Block & sample_block)
    : dict_struct{dict_struct}
    , host{host}
    , port{port}
    , user{user}
    , password{password}
    , method{method}
    , db{db}
    , collection{collection}
    , uri{uri}
    , sample_block{sample_block}
    /*, connection{std::make_shared<Poco::MongoDB::Connection>(host, port)}*/
    , connection{getConnection(host,port,uri)}
{
      if (uri.empty())
      {
  #    if POCO_VERSION >= 0x01070800
           Poco::MongoDB::Database poco_db(db);
           if (!poco_db.authenticate(*connection, user, password, method.empty() ? Poco::MongoDB::Database::AUTH_SCRAM_SHA1 : method))
              throw Exception("Cannot authenticate in MongoDB, incorrect user "+user+" or password "+password, ErrorCodes::MONGODB_CANNOT_AUTHENTICATE);
  #    else
        Poco::MongoDB::Database poco_db();
        poco_db.authenticate(*connection, db, user, password);
  #    endif
      }
}

MongoDBDictionarySource::MongoDBDictionarySource(
    const DictionaryStructure & dict_struct,
    const Poco::Util::AbstractConfiguration & config,
    const std::string & config_prefix,
    Block & sample_block)
    : MongoDBDictionarySource(
          dict_struct,
          config.getString(config_prefix + ".host",""),
          **config.getUInt(config_prefix + ".port",0),**
          config.getString(config_prefix + ".user", ""),
          config.getString(config_prefix + ".password", ""),
          config.getString(config_prefix + ".method", ""),
          **config.getString(config_prefix + ".db", getDB(config.getString(config_prefix + ".uri",""))),**
          config.getString(config_prefix + ".collection"),
	  **config.getString(config_prefix + ".uri",""),**
          sample_block)
{
}

MongoDBDictionarySource::MongoDBDictionarySource(const MongoDBDictionarySource & other)
    : MongoDBDictionarySource{other.dict_struct,
                              other.host,
                              other.port,
                              other.user,
                              other.password,
                              other.method,
                              other.db,
                              other.collection,
			      **other.uri,**
                              other.sample_block}
{
}

### **MongoDBDictionarySource.h**

 const DictionaryStructure & dict_struct,
        const std::string & host,
        UInt16 port,
        const std::string & user,
        const std::string & password,
        const std::string & method,
        const std::string & db,
        const std::string & collection,
        **const std::string & uri,**
        const Block & sample_block);

/*** Please update poco for clickhouse so that uri support can be enable**/

### CODE REVIEW

**Comment by alesapin** [comment]
You can ignore test fails until you resolve conflicts.

**Comment by vitlibar** [comment]
@manish53 You've created two more similar PRs:
https://github.com/yandex/ClickHouse/pull/5387
https://github.com/yandex/ClickHouse/pull/5388
Which of your three PRs is ready to review?

**Comment by vitlibar** [comment]
Can you please provide more detailed description what you're implementing here? Currently it doesn't look very clear. Maybe some links would help. What's Mongo URI?

**Comment by manish53** [comment]
@vitlibar #5387,#5388 are created with patch files which shows where i've made changes as compared to this PR where all code are put in one go.

**Comment by manish53** [comment]
In mongo atlas for connection purpose atlas provide a connection string which consist of db's username,password,cluster info etc. In order to connect through this connection string(uri) to atlas, clickhouse needed to support such url form. This support is added here with ssl/non-ssl support.

**Comment by blinkov** [comment]
@manish53 there are still some conflicts, are you going to fix them?

**Comment by manish53** [comment]
> @manish53 there are still some conflicts, are you going to fix them?

I didn't modified those files which are listed as conflicts, so can't resolved it.

**Comment by blinkov** [comment]
@manish53 try to merge with upstream master and push again

**Comment by manish53** [comment]
> @manish53 try to merge with upstream master and push again

Should i merge those files with alesapin-master? I am new in github so please ellaborate more what should i do to make this PR usefull.

**Comment by blinkov** [comment]
@manish53 `git pull git@github.com:yandex/ClickHouse.git master`

**Comment by alexey-milovidov** [comment]
Looks like #5387 is the right PR.

**Pull request closed without merging**
