### PR TITLE
Rework SELECT from Distributed optimizations

### PR DESCRIPTION
**Pull request by azat**
Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Apply `LIMIT` on the shards for queries like `SELECT * FROM dist ORDER BY key LIMIT 10` w/ `distributed_push_down_limit=1`. Avoid running `Distinct`/`LIMIT BY` steps for queries like `SELECT DISTINCT shading_key FROM dist ORDER BY key`.
Now `distributed_push_down_limit` is respected by `optimize_distributed_group_by_sharding_key` optimization.

**Next step will be enabling `distributed_push_down_limit` by default - #27104.**

Cc: @DimasKovas

### CODE REVIEW

**Comment by azat** [comment]
@alexey-milovidov maybe you can take a look please?

**Comment by azat** [comment]
Rebased on top of upstream/master

**Comment by azat** [comment]
>Integration tests (asan) — fail: 48, passed: 572, flaky: 0
>Integration tests (release) — fail: 48, passed: 81, flaky: 0
>Integration tests (thread) — fail: 48, passed: 682, flaky: 0

Known problem with test_storage_rabbitmq - #26826

**Comment by azat** [comment]
@alexey-milovidov just a friendly reminder that this is ready for review.

**Review by alexey-milovidov — APPROVED** [review]

**Pull request merged**
