### PR TITLE
Don't interrupt copyData() used inside Kafka materialized views

### PR DESCRIPTION
**Pull request by abyss7**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

For changelog. Remove if this is non-significant change.

Category (leave one):
- Bug Fix

Short description (up to few sentences):
Fix Kafka messages duplication problem on normal server restart.

Description for developers:
With Materialized Views in use the `copyData()` may get cancelled before calling `ReadSuffix()` which leads to uncommitted messages. Don't cancel `copyData()` execution at all, but add cancellation to the Kafka Read Buffer. Also drop additional buffering introduced by `InterpreterInsertQuery` - it also leads to a lesser correspondance between committed offsets and really written messages.

### CODE REVIEW

**Comment by abyss7** [comment]
Should fix #6414

**Comment by alexey-milovidov** [comment]
Is this the reason for duplicates after a normal restart?

**Comment by alexey-milovidov** [comment]
Please write a description for changelog that is appropriate for users (rather than developers).

**Comment by abyss7** [comment]
> Is this the reason for duplicates after a normal restart?

It's a very probable reason, but I'm still trying to reproduce it.

**Comment by abyss7** [comment]
> Please write a description for changelog that is appropriate for users (rather than developers).

Ok, sure

**Review by alexey-milovidov — APPROVED** [review]
Ok.

**Pull request merged**
