### PR TITLE
PR template fix to include ci fix category

### PR DESCRIPTION
**Pull request by maxknv**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
...

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by robot-ch-test-poll4** [comment]
*This is an automated comment for commit 30a5bb11429f208f2a5670c32238bf8adbbd932a with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/60461/30a5bb11429f208f2a5670c32238bf8adbbd932a/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/60461/30a5bb11429f208f2a5670c32238bf8adbbd932a/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Comment by Felixoid** [comment]
Should we close it in favor of #60457?

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
Looks good to me.

> Should we close it in favor of https://github.com/ClickHouse/ClickHouse/pull/60457?

I see it is a single step from that PR.

**Comment by Felixoid** [comment]
No, it's the step that now is breaking the whole CI w/o that changes. I think these lines https://github.com/ClickHouse/ClickHouse/blob/master/.github/PULL_REQUEST_TEMPLATE.md?plain=1#L1-L6 don't highlight the issue clear enough

**Pull request merged**
