### PR TITLE
Rename setting

### PR DESCRIPTION
**Pull request by 4ertus2**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Rename `optimize_arithmetic_operations_in_agr_func`

### CODE REVIEW

**Comment by 4ertus2** [comment]
Related #11288

**Comment by alexey-milovidov** [comment]
The new name means that this setting is intended for all arithmetic-related optimizations?
But as of now it have very specific use - move arithmetic operations out of aggregate functions if they are commutative with aggregation.

**Comment by 4ertus2** [comment]
> The new name means that this setting is intended for all arithmetic-related optimizations?

Yes. The idea is we need several cummulative settings for AST optimizer. Not a setting per optimization but a setting per group of optimizations. Generally we have to support optimizers settings forever cause they could make queries slower in some cases. Alternative is to support one setting with optimizer version.

**Comment by alexey-milovidov** [comment]
The name "optimize arithmetic"... suggests something more simple.
For example, the user may think that it will perform basic peephole optimizations on associativity, for example, transform:

`x + 1 + 2`

to

`x + (1 + 2)`

But it does something more sophisticated.
That's why I think that this setting should have explicit name.

**Review by alexey-milovidov — APPROVED** [review]

**Pull request merged**
