### PR TITLE
Support for DWARF-5 in in house DWARF parser

### PR DESCRIPTION
**Pull request by azat**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Support for DWARF-5 in in house DWARF parser

I have to do this, since I have libraries compiled with DWARF5 (i.e.
glibc).

ClickHouse changes:
- use camel_case
- add NOLINT
- avoid using folly:: (use std:: instead)
- avoid using boost:: (use std:: instead)

<details>

```
azat:.../ch/clickhouse-upstream (DWARF-5)$ readelf --debug-dump=info /lib/libc.so.6  | grep -A2 'Compilation Unit @' | head
  Compilation Unit @ offset 0x0:
   Length:        0x4d2 (32-bit)
   Version:       5
--
  Compilation Unit @ offset 0x4d6:
   Length:        0x23a1 (32-bit)
   Version:       5
--
  Compilation Unit @ offset 0x287b:
   Length:        0x39c3 (32-bit)
```

</details>

Refs: https://github.com/facebook/folly/commit/490b287ca37031ebf8ef6ef936231c70253ba442
Refs: #35405
Refs: #34777
Refs: #37479

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
BTW, We also include LLVM and can use DWARF parser and symbolizer directly from there.

**Comment by azat** [comment]
>BTW, We also include LLVM and can use DWARF parser and symbolizer directly from there.

Indeed. I though about this, but decided to update the folly's implementation for now, and separately look at llvm's, in the long-term I think it is good step, however I'm afraid that it may be slower (or will not have "fast" interface), but this should be verified first.

**Comment by azat** [comment]
Basically it looks OK, parser works, and binary indeed uses DWARF-5.

>[Stress test (thread) — Killed by signal (in clickhouse-server.log)]()

SIGTRAP, and cannot reproduce.

<details>

```
/var/log/clickhouse-server/clickhouse-server.err.log:2022.08.28 01:05:40.494222 [ 3952 ] {} <Fatal> BaseDaemon: ########################################
/var/log/clickhouse-server/clickhouse-server.err.log:2022.08.28 01:05:40.494532 [ 3952 ] {} <Fatal> BaseDaemon: (version 22.9.1.1, build id: CD78D142CE05E6500B0AA37F0BC1986580EFB8BD) (from thread 1750) (query_id: 4ae06517-cac9-4b59-9f39-e09d36465a70) (query: SELECT * FROM remote('ThisHostNameDoesNotExistSoItShouldFail', system, one)) Received signal Trace/breakpoint trap (5)
/var/log/clickhouse-server/clickhouse-server.err.log:2022.08.28 01:05:40.494673 [ 3952 ] {} <Fatal> BaseDaemon: 
/var/log/clickhouse-server/clickhouse-server.err.log:2022.08.28 01:05:40.494898 [ 3952 ] {} <Fatal> BaseDaemon: Stack trace: 0x7fb739cde09f 0x7fb739bfa928 0x7fb739cdd60a 0x7fb739bf98c1 0x7fb739bfa928 0x7fb739bfa9f3 0x7fb739bf99f5 0x7fb739bdd6ac 0x7fb739bddf59 0x7fb739b9e375 0x7fb739b9ff59 0xb505405 0x1fc60cec 0xb6899e6 0xb688905 0xb688c85 0xb689535 0x1ad1a080 0x1ad1b211 0x1ad302b8 0x1ad2fe61 0x1ad24d5b 0x19d608f4 0x19d5bfcb 0x1a103b60 0x1ad3faff 0x1b636f40 0x1b592a4b 0x1b5915c6 0x1b5f6b3f 0x1b5f49cb 0x1b53c4c9 0x1b53b54d 0x1b987014 0x1b984acc 0x1c9455c6 0x1c9590a8 0x1fcad803 0x1fcae073 0x1ff05a1a
/var/log/clickhouse-server/clickhouse-server.err.log:2022.08.28 01:05:40.495227 [ 3952 ] {} <Fatal> BaseDaemon: 5. ? in ?
/var/log/clickhouse-server/clickhouse-server.err.log:2022.08.28 01:05:40.495410 [ 3952 ] {} <Fatal> BaseDaemon: 6. _dl_catch_exception in ?
/var/log/clickhouse-server/clickhouse-server.err.log:2022.08.28 01:05:40.495520 [ 3952 ] {} <Fatal> BaseDaemon: 7. ? in ?
/var/log/clickhouse-server/clickhouse-server.err.log:2022.08.28 01:05:40.495631 [ 3952 ] {} <Fatal> BaseDaemon: 8. ? in ?
/var/log/clickhouse-server/clickhouse-server.err.log:2022.08.28 01:05:40.495766 [ 3952 ] {} <Fatal> BaseDaemon: 9. _dl_catch_exception in ?
/var/log/clickhouse-server/clickhouse-server.err.log:2022.08.28 01:05:40.495887 [ 3952 ] {} <Fatal> BaseDaemon: 10. _dl_catch_error in ?
/var/log/clickhouse-server/clickhouse-server.err.log:2022.08.28 01:05:40.496018 [ 3952 ] {} <Fatal> BaseDaemon: 11. __libc_dlopen_mode in ?
/var/log/clickhouse-server/clickhouse-server.err.log:2022.08.28 01:05:40.496136 [ 3952 ] {} <Fatal> BaseDaemon: 12. ? in ?
/var/log/clickhouse-server/clickhouse-server.err.log:2022.08.28 01:05:40.496228 [ 3952 ] {} <Fatal> BaseDaemon: 13. __nss_lookup_function in ?
/var/log/clickhouse-server/clickhouse-server.err.log:2022.08.28 01:05:40.496352 [ 3952 ] {} <Fatal> BaseDaemon: 14. ? in ?
/var/log/clickhouse-server/clickhouse-server.err.log:2022.08.28 01:05:40.496463 [ 3952 ] {} <Fatal> BaseDaemon: 15. getaddrinfo in ?
/var/log/clickhouse-server/clickhouse-server.err.log:2022.08.28 01:06:01.245890 [ 675 ] {} <Fatal> Application: Child process was terminated by signal 5.
/var/log/clickhouse-server/clickhouse-server.stress.log:2022.08.28 01:05:40.494222 [ 3952 ] {} <Fatal> BaseDaemon: ########################################
/var/log/clickhouse-server/clickhouse-server.stress.log:2022.08.28 01:05:40.494532 [ 3952 ] {} <Fatal> BaseDaemon: (version 22.9.1.1, build id: CD78D142CE05E6500B0AA37F0BC1986580EFB8BD) (from thread 1750) (query_id: 4ae06517-cac9-4b59-9f39-e09d36465a70) (query: SELECT * FROM remote('ThisHostNameDoesNotExistSoItShouldFail', system, one)) Received signal Trace/breakpoint trap (5)
/var/log/clickhouse-server/clickhouse-server.stress.log:2022.08.28 01:05:40.494673 [ 3952 ] {} <Fatal> BaseDaemon: 
/var/log/clickhouse-server/clickhouse-server.stress.log:2022.08.28 01:05:40.494898 [ 3952 ] {} <Fatal> BaseDaemon: Stack trace: 0x7fb739cde09f 0x7fb739bfa928 0x7fb739cdd60a 0x7fb739bf98c1 0x7fb739bfa928 0x7fb739bfa9f3 0x7fb739bf99f5 0x7fb739bdd6ac 0x7fb739bddf59 0x7fb739b9e375 0x7fb739b9ff59 0xb505405 0x1fc60cec 0xb6899e6 0xb688905 0xb688c85 0xb689535 0x1ad1a080 0x1ad1b211 0x1ad302b8 0x1ad2fe61 0x1ad24d5b 0x19d608f4 0x19d5bfcb 0x1a103b60 0x1ad3faff 0x1b636f40 0x1b592a4b 0x1b5915c6 0x1b5f6b3f 0x1b5f49cb 0x1b53c4c9 0x1b53b54d 0x1b987014 0x1b984acc 0x1c9455c6 0x1c9590a8 0x1fcad803 0x1fcae073 0x1ff05a1a
/var/log/clickhouse-server/clickhouse-server.stress.log:2022.08.28 01:05:40.495227 [ 3952 ] {} <Fatal> BaseDaemon: 5. ? in ?
/var/log/clickhouse-server/clickhouse-server.stress.log:2022.08.28 01:05:40.495410 [ 3952 ] {} <Fatal> BaseDaemon: 6. _dl_catch_exception in ?
/var/log/clickhouse-server/clickhouse-server.stress.log:2022.08.28 01:05:40.495520 [ 3952 ] {} <Fatal> BaseDaemon: 7. ? in ?
/var/log/clickhouse-server/clickhouse-server.stress.log:2022.08.28 01:05:40.495631 [ 3952 ] {} <Fatal> BaseDaemon: 8. ? in ?
/var/log/clickhouse-server/clickhouse-server.stress.log:2022.08.28 01:05:40.495766 [ 3952 ] {} <Fatal> BaseDaemon: 9. _dl_catch_exception in ?
/var/log/clickhouse-server/clickhouse-server.stress.log:2022.08.28 01:05:40.495887 [ 3952 ] {} <Fatal> BaseDaemon: 10. _dl_catch_error in ?
/var/log/clickhouse-server/clickhouse-server.stress.log:2022.08.28 01:05:40.496018 [ 3952 ] {} <Fatal> BaseDaemon: 11. __libc_dlopen_mode in ?
/var/log/clickhouse-server/clickhouse-server.stress.log:2022.08.28 01:05:40.496136 [ 3952 ] {} <Fatal> BaseDaemon: 12. ? in ?
/var/log/clickhouse-server/clickhouse-server.stress.log:2022.08.28 01:05:40.496228 [ 3952 ] {} <Fatal> BaseDaemon: 13. __nss_lookup_function in ?
/var/log/clickhouse-server/clickhouse-server.stress.log:2022.08.28 01:05:40.496352 [ 3952 ] {} <Fatal> BaseDaemon: 14. ? in ?
/var/log/clickhouse-server/clickhouse-server.stress.log:2022.08.28 01:05:40.496463 [ 3952 ] {} <Fatal> BaseDaemon: 15. getaddrinfo in ?
/var/log/clickhouse-server/clickhouse-server.stress.log:2022.08.28 01:06:01.245890 [ 675 ] {} <Fatal> Application: Child process was terminated by signal 5.
```

</details>

>[Stateless tests (debug) [1/3] — fail: 0, passed: 1470, skipped: 13, unknown: 1](https://s3.amazonaws.com/clickhouse-test-reports/40710/444acb96c8891ac8518f8d1710ba782409eece96/stateless_tests__debug__[1/3].html)

- `02346_position_countsubstrings_zero_byte` timeout on `CREATE DATABASE` - and this is confirmed by logs

>[Stress test (undefined) — Backward compatibility check: Error message in clickhouse-server.log (see bc_check_error_messages.txt)](https://s3.amazonaws.com/clickhouse-test-reports/40710/444acb96c8891ac8518f8d1710ba782409eece96/stress_test__undefined_.html)

- Real OOM

>[ClickHouse special build check — 6/7 artifact groups are OK](https://s3.amazonaws.com/clickhouse-builds/40710/444acb96c8891ac8518f8d1710ba782409eece96/clickhouse_special_build_check/report.html)

Expected failure of `clang-tidy`, fixed.

**Review by alexey-milovidov — APPROVED** [review]

**Comment by azat** [comment]
>[Stress test (debug) — Backward compatibility check: OOM killer (or signal 9) in clickhouse-server.log](https://s3.amazonaws.com/clickhouse-test-reports/40710/e03870bc8ba10037b25ef1fcd7a1e2c906ff79bb/stress_test__debug_.html)

Real OOM

>[Stress test (undefined) — Backward compatibility check: Error message in clickhouse-server.log (see bc_check_error_messages.txt)](https://s3.amazonaws.com/clickhouse-test-reports/40710/e03870bc8ba10037b25ef1fcd7a1e2c906ff79bb/stress_test__undefined_.html)

Real OOM

**Comment by tavplubix** [comment]
The failure with SIGTRAP was probably related, there are tons of similar failures in master since this PR was merged

**Pull request merged**
