### PR TITLE
FREEZE TABLE

### LINKED ISSUE #7785: ALTER TABLE FREEZE should return snapshot ID as result
Running `ALTER TABLE FREEZE` currently does not return the incremental snapshot ID. I can only get it from the `./shadow/increment.txt` file:

```
localhost :) ALTER TABLE stats FREEZE

ALTER TABLE stats
    FREEZE


Ok.

0 rows in set. Elapsed: 0.018 sec.
```
Assuming there are multiple processes making snapshots, I would like to know the snapshot ID when issuing the FREEZE query. Otherwise I can not be sure, which snapshot was the one that I issued.

What I would like to see:
```
localhost :) ALTER TABLE stats FREEZE

ALTER TABLE stats
    FREEZE

┌─snapshot_id─┐
│           3 │
└─────────────┘

1 rows in set. Elapsed: 0.001 sec.
```

Alternatively, also the 'outcome' could be reported (ok, error, ...) in the result.

### PR DESCRIPTION
**Pull request by nvartolomei**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- New Feature

Changelog entry (up to few sentences, required except for Non-significant/Documentation categories):

`FREEZE TABLE [db.]name [PARTITION partition_expr] [WITH NAME custom_dir]` returning snapshot id.

Detailed description (optional):

Possible solution to #7785. While implementing this discovered `ALTER TABLE ... FREEZE ... WITH NAME` syntax which with a random unique string can be used as a workaround.

Closes #7785.

### CODE REVIEW

**Review by alexey-milovidov — CHANGES_REQUESTED** [review]
It will be good to add tests.

**Comment by nvartolomei** [comment]
Might be useful to return something like table below? Especially for cases with multiple volumes.


|shadow|part name|path to part|
|--------|----------|------------|
|***increment** or **name** (if WITH NAME)*|*part name*|*path*|

**Comment by nvartolomei** [comment]
See https://github.com/nvartolomei/ClickHouse/pull/1/files for example.

**Comment by alexey-milovidov** [comment]
@blinkov Your bot has made chaotic changes.

**Pull request closed without merging**
