### PR TITLE
Bump protobuf to v3.19.6

### PR DESCRIPTION
**Pull request by rschu1ze**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by robot-clickhouse-ci-2** [comment]
*This is an automated comment for commit 666f854b2771631f18d1325b9f03bde776a1146b with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/55963/666f854b2771631f18d1325b9f03bde776a1146b/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td><a href="https://github.com/ClickHouse/ClickHouse/actions/runs/6625374256">✅ success</a></td></tr>
<tbody>
</table>
</details>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/55963/666f854b2771631f18d1325b9f03bde776a1146b/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Review by Algunenano — COMMENTED** [review]
What's the reasoning for bumping to v3.19.3 and not v3.19.6 or v3.24.3?

**Comment by rschu1ze** [comment]
Thanks, I somehow missed that there were minor releases after v3.19.3. Okay, let me change this to v3.19.6.

I am deliberately incrementing the versions by major releases (i.e. not jumping directly to v3.24). They change quite a lot between releases and being able to look at the changes in a *single* major release (instead of changes in N releases) is helpful in case something breaks.

**Comment by Algunenano** [comment]
I'd prefer a larger bump (and then backtrack if something fails), specially since this requires updating submodules with every PR, but it's your call.

**Review by Algunenano — APPROVED** [review]

**Pull request merged**
