### PR TITLE
Yet another refactoring

### PR DESCRIPTION
**Pull request by CurtizJ**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by robot-ch-test-poll3** [comment]
This is an automated comment for commit 612173e734fc72d86640e8e0c9da3eb3967e079a with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/50257/612173e734fc72d86640e8e0c9da3eb3967e079a/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Comment by CurtizJ** [comment]
A test `00834_kill_mutation` has failed, but looks like it's [flaky](https://play.clickhouse.com/play?user=play#U0VMRUNUIGNoZWNrX3N0YXJ0X3RpbWUsIHB1bGxfcmVxdWVzdF9udW1iZXIsIGNoZWNrX25hbWUsIHRlc3RfbmFtZSwgcmVwb3J0X3VybApGUk9NIGNoZWNrcwpXSEVSRSBjaGVja19uYW1lIExJS0UgJ1N0YXRlJScKICAgIEFORCBwdWxsX3JlcXVlc3RfbnVtYmVyID0gMAogICAgQU5EIHRlc3RfbmFtZSA9ICcwMDgzNF9raWxsX211dGF0aW9uJwogICAgQU5EIGNoZWNrX3N0YXJ0X3RpbWUgPj0gbm93KCkgLSBJTlRFUlZBTCA0IHdlZWsKICAgIEFORCB0ZXN0X3N0YXR1cyAhPSAnU0tJUFBFRCcKICAgIEFORCB0ZXN0X3N0YXR1cyBMSUtFICdGJScKICAgIEFORCBjaGVja19zdGF0dXMgIT0gJ3N1Y2Nlc3MnCk9SREVSIEJZIGNoZWNrX25hbWUsIHRlc3RfbmFtZSwgY2hlY2tfc3RhcnRfdGltZQ==)

**Review by alesapin — APPROVED** [review]

**Comment by alesapin** [comment]
`test_store_cleanup_disk_s3` -- https://github.com/ClickHouse/ClickHouse/issues/48691

**Comment by alesapin** [comment]
`01443_merge_truncate_long` -- https://github.com/ClickHouse/ClickHouse/issues/50294

**Comment by alesapin** [comment]
Tsan assertion https://github.com/ClickHouse/ClickHouse/issues/50295

**Comment by alesapin** [comment]
Performance comparison -- fails on master

**Comment by alesapin** [comment]
`analyzer` -- sorry I don't understand why it complain about 2 failed tests in this case:
image

**Pull request merged**
