### PR TITLE
Suppress false positive memleak in OpenSSL, pt. II

### LINKED ISSUE #67624: LeakSanitizer: detected memory leaks in OpenSSL (again)
https://s3.amazonaws.com/clickhouse-test-reports/0/453ee52f866027d66f80e0b316c685dcdfd127a6/stress_test__asan_/run.log

Check the logs at the end:

Multiple similar reports:
```
=================================================================
==61299==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 48 byte(s) in 1 object(s) allocated from:
    #0 0x55764d4bf4cf in malloc (/usr/bin/clickhouse+0xa8844cf) (BuildId: e1b56ac6b8ca3ae83128353e15ac1fee025f9f7b)
    #1 0x55767b4f239e in CRYPTO_malloc build_docker/./contrib/openssl/crypto/mem.c:202:11
    #2 0x55767b4f239e in CRYPTO_zalloc build_docker/./contrib/openssl/crypto/mem.c:222:11
    #3 0x55767b54c0af in EVP_RAND_CTX_new build_docker/./contrib/openssl/crypto/evp/evp_rand.c:353:11
    #4 0x55767b54eedb in rand_new_drbg build_docker/./contrib/openssl/crypto/rand/rand_lib.c:665:11
    #5 0x55767b54e37b in RAND_get0_private build_docker/./contrib/openssl/crypto/rand/rand_lib.c:827:16
    #6 0x55767b54e24f in RAND_priv_bytes_ex build_docker/./contrib/openssl/crypto/rand/rand_lib.c:356:12
    #7 0x55767b2435f8 in SSL_CTX_new_ex build_docker/./contrib/openssl/ssl/ssl_lib.c:4016:13
    #8 0x5576768958e6 in Poco::Net::Context::createSSLContext() build_docker/./base/poco/NetSSL_OpenSSL/src/Context.cpp
    #9 0x5576768924f4 in Poco::Net::Context::init(Poco::Net::Context::Params const&) build_docker/./base/poco/NetSSL_OpenSSL/src/Context.cpp:233:2
    #10 0x557676892315 in Poco::Net::Context::Context(Poco::Net::Context::Usage, Poco::Net::Context::Params const&) build_docker/./base/poco/NetSSL_OpenSSL/src/Context.cpp:55:2

Direct leak of 48 byte(s) in 1 object(s) allocated from:
    #0 0x55764d4bf4cf in malloc (/usr/bin/clickhouse+0xa8844cf) (BuildId: e1b56ac6b8ca3ae83128353e15ac1fee025f9f7b)
    #1 0x55767b4f239e in CRYPTO_malloc build_docker/./contrib/openssl/crypto/mem.c:202:11
    #2 0x55767b4f239e in CRYPTO_zalloc build_docker/./contrib/openssl/crypto/mem.c:222:11
    #3 0x55767b54c0af in EVP_RAND_CTX_new build_docker/./contrib/openssl/crypto/evp/evp_rand.c:353:11
    #4 0x55767b54eedb in rand_new_drbg build_docker/./contrib/openssl/crypto/rand/rand_lib.c:665:11
    #5 0x55767b54e37b in RAND_get0_private build_docker/./contrib/openssl/crypto/rand/rand_lib.c:827:16
    #6 0x55767b54e24f in RAND_priv_bytes_ex build_docker/./contrib/openssl/crypto/rand/rand_lib.c:356:12
    #7 0x55767b2435f8 in SSL_CTX_new_ex build_docker/./contrib/openssl/ssl/ssl_lib.c:4016:13
    #8 0x5576773459bd in ossl_connect_common openssl.c
    #9 0x557677338d23 in ssl_cf_connect vtls.c
    #10 0x55767723a91f in cf_setup_connect connect.c
```

### PR DESCRIPTION
**Pull request by rschu1ze**
Resolves #67624
Resolves https://github.com/ClickHouse/clickhouse-private/issues/12878

This is a continuation of #65125 - this PR fixes `RAND_get0_private` whereas the previous PR fixed `RAND_get0_public` (aka. the function right above ^^).

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by robot-ch-test-poll1** [comment]
*This is an automated comment for commit 4581b381e4970338eb721c6445d05946ce0eea00 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/65863/4581b381e4970338eb721c6445d05946ce0eea00/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/65120/0dd4735e07319295cf52043bf9fd1fd71f0fc1ea/docs_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Comment by tavplubix** [comment]
How is it possible to have a false-positive lsan report about memory leak? Should we report a bug to https://github.com/google/sanitizers/issues?

**Comment by tavplubix** [comment]
I'm not sure if lsan handles _exit properly, maybe we should add asan here:
https://github.com/ClickHouse/ClickHouse/blob/b4ecbbf22469cd4a827aec1cd604b3ea900a26e1/base/base/safeExit.cpp#L9-L19

**Review by hanfei1991 — APPROVED** [review]

**Comment by Algunenano** [comment]
@rschu1ze we need this :wink: There are several reported `testing` tickets related to it

**Comment by rschu1ze** [comment]
I will need to clarify with upstream if this is a false positive or not. Since there are some tickets related to this open, let's get this in for now.

**Comment by rschu1ze** [comment]
Timeouts are fixed in `master`, merging again.

**Comment by rschu1ze** [comment]
I unintentionally included this fix already here: https://github.com/ClickHouse/ClickHouse/pull/69341

**Pull request closed without merging**
