### PR TITLE
Update test_user_valid_until/test.py

### PR DESCRIPTION
**Pull request by tavplubix**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by robot-ch-test-poll** [comment]
*This is an automated comment for commit dba3cac9561824fa41595e2152421708c8ddf9f0 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/58432/dba3cac9561824fa41595e2152421708c8ddf9f0/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/58432/dba3cac9561824fa41595e2152421708c8ddf9f0/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Comment by tavplubix** [comment]
However, I don't understand what this code checks if "Time only is not supported" 
https://github.com/ClickHouse/ClickHouse/blob/0998b0bbc740f26fccd0d01f23014b40c75b6359/tests/integration/test_user_valid_until/test.py#L78-L84

cc: @evillique

**Comment by evillique** [comment]
https://github.com/ClickHouse/ClickHouse/pull/58409

**Comment by evillique** [comment]
> However, I don't understand what this code checks if "Time only is not supported"

It was added as a TODO, but I kind of forgot about it, will look into it

**Pull request closed without merging**
