### PR TITLE
Fix debug symbols in packages

### PR DESCRIPTION
**Pull request by azat**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix debug symbols in packages

- before: usr/lib/debug/usr/bin/clickhouse.debug/clickhouse.debug
- after : usr/lib/debug/usr/bin/clickhouse.debug

Note, clickhouse_make_empty_debug_info_for_nfpm() is fine.

Fixes: #35533 (cc @Felixoid )

### CODE REVIEW

**Comment by azat** [comment]
Before

```
Reading symbols from clickhouse-server...

warning: the debug information found in "/usr/lib/debug//usr/bin/clickhouse.debug" does not match "/usr/bin/clickhouse" (CRC mismatch).

(No debugging symbols found in clickhouse-server)
```

But even after this patch:

```
Reading symbols from /usr/lib/debug//usr/bin/clickhouse.debug...
(No debugging symbols found in /usr/lib/debug//usr/bin/clickhouse.debug)
```

And it is pretty small in compare to the previous debug symbols:

```
# ls -lh /usr/lib/debug/.build-id/01/8c328bd4858d67.debug
-rw-r--r-- 1 root root 454M Feb 10 08:10 /usr/lib/debug/.build-id/01/8c328bd4858d67.debug
root@s1:/# ls -alh /usr/lib/debug//usr/bin/clickhouse.debug
-rw-r--r-- 1 root root 110M May 20 04:21 /usr/lib/debug//usr/bin/clickhouse.debug
```

**Comment by Felixoid** [comment]
It's fixed in master, rebase or merge it, please

**Comment by azat** [comment]
>Need to take a look.

There was a wrong type, `Release` over `RelWithDebInfo`

**Comment by azat** [comment]
>[Integration tests (thread, actions) [3/4] — fail: 116, passed: 0, flaky: 0](https://s3.amazonaws.com/clickhouse-test-reports/37379/6b7dd76fac2358137fecbf1a468b30898b23524d/integration_tests__thread__actions__[3/4].html)

```
E               ERROR: for main_node  Get "https://registry-1.docker.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
E               
E               ERROR: for dictionary_node  Get "https://registry-1.docker.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
E               Get "https://registry-1.docker.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
E               Get "https://registry-1.docker.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```

**Review by alexey-milovidov — APPROVED** [review]

**Pull request merged**
