### PR TITLE
Send string columns to mysql client as utf8

### PR DESCRIPTION
**Pull request by yurriy**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
After recent changes mysql client started to print binary strings in hex thereby making them not readable (#9032). The workaround in ClickHouse is to mark string columns as utf8, which is not always, but usually the case.

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
Integration test has failed for reason?

**Comment by yurriy** [comment]
> Integration test has failed for reason?

Yes, I noticed the failures, but had no time until today to reproduce and fix them.

**Comment by yurriy** [comment]
It seems that the failures in the last check are not caused by this patch

**Comment by alexey-milovidov** [comment]
> test_polymorphic_parts/test.py::test_polymorphic_parts_diff_versions | ERROR

Yes, it's unrelated.

> test_storage_mysql/test.py::test_table_function | FAILED

Need to dig into it...

**Comment by alexey-milovidov** [comment]
Yes, it's known issue that happened to appear on master.

**Comment by alexey-milovidov** [comment]
Thank you!

**Pull request merged**
