### PR TITLE
Upgrade python packages for doc tools

### PR DESCRIPTION
**Pull request by LAL2211**
Changelog category (leave one):
Not for changelog (changelog entry is not required)

Changed requirements.txt

### CODE REVIEW

**Comment by LAL2211** [comment]
Changelog category (leave one):
Not for changelog (changelog entry is not required)

**Comment by alexey-milovidov** [comment]
What is the purpose of this change? Do we really need to upgrade Python packages and for what reason?

**Comment by alexey-milovidov** [comment]
`livereload==2.6.3` - in fact, "live reload" does not work for our documentation, maybe better to remove it instead of changing version?

**Comment by LAL2211** [comment]
> `livereload==2.6.3` - in fact, "live reload" does not work for our documentation, maybe better to remove it instead of changing version?

sure! will try to remove it and check for the build. thank you

**Comment by LAL2211** [comment]
> `livereload==2.6.3` - in fact, "live reload" does not work for our documentation, maybe better to remove it instead of changing version?

Are you sure do you want me to take it?

**Comment by alexey-milovidov** [comment]
Ok, let's simply merge this PR.
But you need to sign a CLA.

**Comment by alexey-milovidov** [comment]
Let's wait 5 days for CLA signature or close.

**Pull request closed without merging**
