### PR TITLE
More verbose errors on 00002_log_and_exception_messages_formatting

### PR DESCRIPTION
**Pull request by Algunenano**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
...

### Documentation entry for user-facing changes

Try returning a list of errors / messages to review when `00002_log_and_exception_messages_formatting` fails.

### CODE REVIEW

**Comment by robot-ch-test-poll2** [comment]
*This is an automated comment for commit bfc7e8c0e66e8465c3ee047ac07b58154ef5ef50 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/58037/bfc7e8c0e66e8465c3ee047ac07b58154ef5ef50/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td><a href="https://github.com/ClickHouse/ClickHouse/actions/runs/7264144154">✅ success</a></td></tr>
<tbody>
</table>
</details>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/58037/bfc7e8c0e66e8465c3ee047ac07b58154ef5ef50/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Comment by Algunenano** [comment]
Rebased after https://github.com/ClickHouse/ClickHouse/pull/58012. @tavplubix maybe you want to have a look

**Review by vdimir — APPROVED** [review]
Is there a commit in this PR where the check intentionally broken, to see how it looks like?

**Comment by Algunenano** [comment]
Some examples from this PR:
* https://s3.amazonaws.com/clickhouse-test-reports/58037/4f0877e1b50aef2c167b91f623ffc6b5e3d8636e/stateless_tests__release__s3_storage__[1_2].html
* https://s3.amazonaws.com/clickhouse-test-reports/58037/4f0877e1b50aef2c167b91f623ffc6b5e3d8636e/stateless_tests_flaky_check__asan_.html

**Comment by tavplubix** [comment]
We have the diagnostics printed here (https://github.com/ClickHouse/ClickHouse/blob/291567a5b208524dfe8af940ae6c64a1cbc10c05/tests/clickhouse-test#L2220), but it's much more convenient to have it right in the test output, thank you!

**Comment by Algunenano** [comment]
* Stateless tests flaky check (asan). Test is considered flaky because executing the test multiple times in a row is not what's expected to be covered by it in a normal scenario (which is purely for CI execution). Merging

**Pull request merged**
