### PR TITLE
Slightly better code with projections

### PR DESCRIPTION
**Pull request by CurtizJ**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
We discussed this code with @alesapin - why it is unreasonably complex, and why the replication protocol should be aware of projections at all, instead of simply transferring an arbitrary set of files under a directory.

We found no reason for it.

Maybe we can rewrite it to drop all this complexity?
If it will break replication across different versions, it's ok.

**Comment by CurtizJ** [comment]
I see only one point. During fetching to regular disk we calculate checksums and check them with provided checksums of part in the end of fetch. For projections it's done in a [special way](https://github.com/ClickHouse/ClickHouse/blob/88f3db911504a8b8fba8a624370add57600c10bb/src/Storages/MergeTree/DataPartsExchange.cpp#L983-L984).

**Comment by alexey-milovidov** [comment]
Ok.

**Comment by CurtizJ** [comment]
Fuzzer: couldn't reproduce:

```sql

SELECT
    ([9223372036854775806], 10, NULL),
    name
FROM system.parts_columns
WHERE untuple((NULL, -1, NULL))
ORDER BY
    1024 ASC,
    (tuple('3'), ([9223372036854775806], 100, 3, materialize(NULL)), [10], untuple((NULL, 65535, NULL)), materialize([NULL, NULL, NULL, NULL, NULL])) DESC NULLS FIRST,
    [7] ASC NULLS LAST

Query id: de4953a4-17af-4c79-9794-cf807a4c586e


0 rows in set. Elapsed: 0.002 sec. 

Received exception from server (version 22.11.1):
Code: 46. DB::Exception: Received from localhost:9000. DB::Exception: Unknown function untuple. Maybe you meant: ['tuple']: While processing untuple((NULL, -1, NULL)). (UNKNOWN_FUNCTION)
```

ASan: stack-use-after-scope is known.

**Pull request merged**
