### PR TITLE
Dictionary rename fix

### PR DESCRIPTION
**Pull request by kitaisreal**
Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by tavplubix** [comment]
Could you please explain what does it fix and add a test if possible?

**Comment by kitaisreal** [comment]
@tavplubix it is just inconsistency, external loader use loadable name for logs, and if we modify dictionary id we should also modify loadable name. Also if we modify dictionary id, we must return loadable name by value, instead of reference to avoid race conditions.

**Comment by tavplubix** [comment]
AFAIK we never modify it, because it's easier to reload dictionary with new internal name (in the case when a dictionary from Ordinary database is renamed) then to change internal name, but ok.

**Review by tavplubix — APPROVED** [review]

**Comment by kitaisreal** [comment]
@tavplubix we modify it only in case of Atomic, but it does not appear to be an issue because for logs we use UUID.

**Comment by kitaisreal** [comment]
Currently better to make such fix for consistency.

**Pull request merged**
