### PR TITLE
Refactor explain estimate to enable other storages to use it 

### PR DESCRIPTION
**Pull request by taiyang-li**
Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Refactor explain estimate to enable select queries from other storages(Hive) showing estimate information.

### CODE REVIEW

**Comment by taiyang-li** [comment]
Only show selected rows/marks/parts is not enough when estimating selecting query from mergetree.   Do you think it is proper if we shows all the statstics in `ReadFromMergeTree::AnalysisResult`

**Comment by taiyang-li** [comment]
Now `explain estimate` works like this: 

image

**Comment by taiyang-li** [comment]
`explain estimate` hive select query like this: 
image

**Review by novikd — APPROVED** [review]

**Comment by novikd** [comment]
LGTM, but needs tests to be fixed.

**Comment by taiyang-li** [comment]
> LGTM, but needs tests to be fixed.

Ok. it will be fixed soon.

**Comment by taiyang-li** [comment]
> 

done

**Comment by taiyang-li** [comment]
@novikd  Failed tests seem not related to this pr.

**Comment by taiyang-li** [comment]
@novikd  Do you have time to check it again. Thanks!

**Comment by robot-clickhouse-ci-1** [comment]
This is an automated comment for commit bfc79392d88b51d7a99d2a7dbb8693dd9c398386 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/35827/bfc79392d88b51d7a99d2a7dbb8693dd9c398386/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Comment by den-crane** [comment]
It should be marked as "Backward Incompatible Change".
It breaks at least my application, which uses `Explain estimate` to worn user about query complexity and sends query to background.

**Comment by taiyang-li** [comment]
> It should be marked as "Backward Incompatible Change". It breaks at least my application, which uses `Explain estimate` to warn a user about query complexity and sends query to background automagically (application expects columns `┌─database─┬─table──────┬─parts─┬──rows─┬─marks─┐`).

I see..  I'll close this pr if you think this feature is not worth of the cost of Backward Incompatible Change

**Comment by taiyang-li** [comment]
> > It should be marked as "Backward Incompatible Change". It breaks at least my application, which uses `Explain estimate` to warn a user about query complexity and sends query to background automagically (application expects columns `┌─database─┬─table──────┬─parts─┬──rows─┬─marks─┐`).
> 
> I see.. I'll close this pr if you think this feature is not worth of the cost of Backward Incompatible Change

No reply..  Let's forget this PR.

**Pull request closed without merging**
