### PR TITLE
Run more tests in SQLancer

### PR DESCRIPTION
**Pull request by qoega**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

...

Detailed description / Documentation draft:

...

By adding documentation, you'll allow users to try your new feature immediately, not when someone else will have time to document it later. Documentation is necessary for all features that affect user experience in any way. You can add brief documentation draft above, or add documentation right into your patch as Markdown files in [docs](https://github.com/ClickHouse/ClickHouse/tree/master/docs) folder.

If you are doing this for the first time, it's recommended to read the lightweight [Contributing to ClickHouse Documentation](https://github.com/ClickHouse/ClickHouse/tree/master/docs/README.md) guide first.

Information about CI checks: https://clickhouse.tech/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
Are they published in checks?

**Comment by qoega** [comment]
They will be published. Currently check status will be green, but individual test results will be written to CI database correctly.
And it is currently not committed and I run them manually for debug purposes.

**Comment by alexey-milovidov** [comment]
> Testflows check — Timeout :( 

This is unreliable third-party check, @vzakaznikov

**Comment by qoega** [comment]
only docker build should be tested in this PR.

**Pull request merged**
