### PR TITLE
strict aliasing via C++20's char8_t

### PR DESCRIPTION
**Pull request by amosbird**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Performance Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Overall performance improvement (in range of 5%..200% for affected queries) by ensuring even more strict aliasing.

Continuation of https://github.com/ClickHouse/ClickHouse/pull/7592 . Let's see if we have performance improvements. IIRC, last time there were only some regressions, with no improv at all.

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
secure, shard_secure - temporarily broken in CI.

**Comment by alexey-milovidov** [comment]
Performance difference is real.

Most representative queries:

`SELECT bitCount(toUInt8(number)) FROM system.numbers`
- 25% better;

`WITH number AS x SELECT sum(x < 1 ? 1 : (x < 5 ? 2 : 3)) FROM system.numbers`
- 40% better;

`SELECT count() FROM (SELECT range(number % 100) FROM system.numbers limit 10000000)`
- 3 times better.

**Comment by alexey-milovidov** [comment]
> SELECT count() FROM (SELECT range(number % 100) FROM system.numbers limit 10000000)
3 times better.

The difference is because after switching from unsigned char to char8_t, the function `FunctionRange::executeInternal` started to be vectorized.

**Comment by alexey-milovidov** [comment]
For `WITH number AS x SELECT sum(x < 1 ? 1 : (x < 5 ? 2 : 3)) FROM system.numbers`
the difference in generated code looks like this:

```
       │43b:┌─ mov    0x10(%r13),%rdx                                                                                                                                                                                                   ▒
  6.06 │    │  movzbl (%rdx,%rax,1),%ecx                                                                                                                                                                                                ▒
  4.55 │    │  mov    0x10(%rbp),%rdx      !!!                                                                                                                                                                                             ▒
 21.21 │    │  mov    %cl,(%rdx,%rax,1)                                                                                                                                                                                                 ▒
  1.52 │    │  add    $0x1,%rax                                                                                                                                                                                                         ▒
       │    │  cmp    %rax,%r14                                                                                                                                                                                                         ▒
  1.52 │    │  je     a80e2b0 <bool DB::FunctionIf::executeTyped<unsigned char, unsigned char>(DB::ColumnVector<unsigned char> const*, 2b0                                                                                              ▒
  3.03 │    │  mov    0x10(%r12),%rdx      !!!                                                                                                                                                                                             ▒
 10.61 │    │  cmpb   $0x0,(%rdx,%rax,1)                                                                                                                                                                                                ▒
  9.09 │    └──je     a80e43b <bool DB::FunctionIf::executeTyped<unsigned char, unsigned char>(DB::ColumnVector<unsigned char> const*, 43b                                                                                              ▒

vs.

       │456:┌─ mov    0x10(%r12),%rsi                                                                                                                                                                                                   ▒
 38.46 │    │  movzbl (%rsi,%rax,1),%esi                                                                                                                                                                                                ▒
 21.15 │    │  mov    %sil,(%rcx,%rax,1)                                                                                                                                                                                                ▒
       │    │  add    $0x1,%rax                                                                                                                                                                                                         ▒
       │    │  cmp    %rax,%r14                                                                                                                                                                                                         ▒
  1.92 │    │  je     197                                                                                                                                                                                                               ▒
 36.54 │    │  cmpb   $0x0,(%rdx,%rax,1)                                                                                                                                                                                                ▒
       │    └──je     456                                                                                                                                                                                                               ▒
```

two extra movs. The difference is clearly attributed to strict aliasing.

**Comment by alexey-milovidov** [comment]
Congratulations! It is a clear win!

**Comment by taiyang-li** [comment]
> For `WITH number AS x SELECT sum(x < 1 ? 1 : (x < 5 ? 2 : 3)) FROM system.numbers` the difference in generated code looks like this:
> 
> ```
>        │43b:┌─ mov    0x10(%r13),%rdx                                                                                                                                                                                                   ▒
>   6.06 │    │  movzbl (%rdx,%rax,1),%ecx                                                                                                                                                                                                ▒
>   4.55 │    │  mov    0x10(%rbp),%rdx      !!!                                                                                                                                                                                             ▒
>  21.21 │    │  mov    %cl,(%rdx,%rax,1)                                                                                                                                                                                                 ▒
>   1.52 │    │  add    $0x1,%rax                                                                                                                                                                                                         ▒
>        │    │  cmp    %rax,%r14                                                                                                                                                                                                         ▒
>   1.52 │    │  je     a80e2b0 <bool DB::FunctionIf::executeTyped<unsigned char, unsigned char>(DB::ColumnVector<unsigned char> const*, 2b0                                                                                              ▒
>   3.03 │    │  mov    0x10(%r12),%rdx      !!!                                                                                                                                                                                             ▒
>  10.61 │    │  cmpb   $0x0,(%rdx,%rax,1)                                                                                                                                                                                                ▒
>   9.09 │    └──je     a80e43b <bool DB::FunctionIf::executeTyped<unsigned char, unsigned char>(DB::ColumnVector<unsigned char> const*, 43b                                                                                              ▒
> 
> vs.
> 
>        │456:┌─ mov    0x10(%r12),%rsi                                                                                                                                                                                                   ▒
>  38.46 │    │  movzbl (%rsi,%rax,1),%esi                                                                                                                                                                                                ▒
>  21.15 │    │  mov    %sil,(%rcx,%rax,1)                                                                                                                                                                                                ▒
>        │    │  add    $0x1,%rax                                                                                                                                                                                                         ▒
>        │    │  cmp    %rax,%r14                                                                                                                                                                                                         ▒
>   1.92 │    │  je     197                                                                                                                                                                                                               ▒
>  36.54 │    │  cmpb   $0x0,(%rdx,%rax,1)                                                                                                                                                                                                ▒
>        │    └──je     456                                                                                                                                                                                                               ▒
> ```
> 
> two extra movs. The difference is clearly attributed to strict aliasing.

@alexey-milovidov just curious, how is the report generated?

**Comment by taiyang-li** [comment]
I found `Int8` has the same alias issue with the `UInt8` before. `Int8`'s underlying type is `signed char`, which may prevent compiler from  optimizing loops which process `Int8` data.

``` cpp

template <typename T>
struct slice
{
    T * data;
};

template <typename T>
NO_INLINE auto BitOrProcess(slice<T> & d)
{
    for (auto i = 0u; i < 65536; ++i)
        d.data[i] |= T(0xaa);
}

template <typename T>
void initSlice(slice<T> & d)
{
    d.data = new T[65536];
    for (auto i = 0u; i < 65536; ++i)
        d.data[i] = T(std::rand());
}

template <typename T>
void finalizeSlice(slice<T> & d)
{
    delete[] d.data;
}

template <typename T>
void BM_BitOrProcess(benchmark::State & state)
{
    slice<T> d;
    initSlice(d);

    for (auto _ : state)
    {
        BitOrProcess(d);
        benchmark::DoNotOptimize(d);
    }
}

BENCHMARK_TEMPLATE(BM_BitOrProcess, char8_t);
BENCHMARK_TEMPLATE(BM_BitOrProcess, int8_t);
BENCHMARK_TEMPLATE(BM_BitOrProcess, uint8_t);
```

``` 
2024-01-26 17:29:36.315 <Warning> SignalHandler: LD_PRELOAD is not set, SignalHandler is disabled
2024-01-26T17:29:36+08:00
Running ./build_gcc/utils/extern-local-engine/tests/benchmark_local_engine
Run on (32 X 2100 MHz CPU s)
CPU Caches:
  L1 Data 32 KiB (x16)
  L1 Instruction 32 KiB (x16)
  L2 Unified 1024 KiB (x16)
  L3 Unified 11264 KiB (x2)
Load Average: 5.34, 5.37, 5.41
-------------------------------------------------------------------
Benchmark                         Time             CPU   Iterations
-------------------------------------------------------------------
BM_BitOrProcess<char8_t>       2813 ns         2813 ns       248994
BM_BitOrProcess<int8_t>       51343 ns        51343 ns        13706
BM_BitOrProcess<uint8_t>      51194 ns        51192 ns        13637
```

**Comment by alexey-milovidov** [comment]
@taiyang-li, It was generated by `sudo perf top`

**Comment by alexey-milovidov** [comment]
@taiyang-li 

> I found Int8 has the same alias issue with the UInt8 before.

Yes, it is a known problem. If we find any compiler's provided type, even something clang-specific, to declare Int8 with strict aliasing, we will use it.

If there is no such type, you can create a feature request to Clang/LLVM and link to this issue.

**Comment by taiyang-li** [comment]
> @taiyang-li 
> 
> > I found Int8 has the same alias issue with the UInt8 before.
> 
> Yes, it is a known problem. If we find any compiler's provided type, even something clang-specific, to declare Int8 with strict aliasing, we will use it.
> 
> If there is no such type, you can create a feature request to Clang/LLVM and link to this issue.
> 
> And if you want to threaten them a little, say that if they don't do it, we will rewrite ClickHouse in Rust :laughing: 

Thanks for explaination. The more I looked into CH, the more interesting optimizations I found. It is awesome!

**Comment by Algunenano** [comment]
> If there is no such type, you can create a feature request to Clang/LLVM and link to this issue.

> And if you want to threaten them a little, say that if they don't do it, we will rewrite ClickHouse in Rust 😆

I don't want to stop any rewrite, but we could consider _BitInt types:
```
using Int8 = signed _BitInt(8);
using UInt8 = unsigned _BitInt(8);
```

```
BM_BitOrProcess<char8_t>        853 ns          852 ns       682960
BM_BitOrProcess<int8_t>       11103 ns        11097 ns        57078
BM_BitOrProcess<uint8_t>      11118 ns        11111 ns        58527
BM_BitOrProcess<Int8>           852 ns          851 ns       695647
BM_BitOrProcess<UInt8>          852 ns          851 ns       820978
```

**Comment by alexey-milovidov** [comment]
@Algunenano This is what we need, please try it!

**Comment by Algunenano** [comment]
Let's see what CI thinks: https://github.com/ClickHouse/ClickHouse/pull/59485

**Pull request merged**
