### PR TITLE
Dashboard: sticky header

### PR DESCRIPTION
**Pull request by alexey-milovidov**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
The Advanced dashboard now has controls always visible on scrolling. This allows you to add a new chart without scrolling up.

### CODE REVIEW

**Comment by robot-ch-test-poll4** [comment]
*This is an automated comment for commit 4b69440e5801bba92cf1f0683519a25a8d4ded6d with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/60692/4b69440e5801bba92cf1f0683519a25a8d4ded6d/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

**Comment by alexey-milovidov** [comment]
https://github.com/ClickHouse/ClickHouse/pull/60426

**Comment by Felixoid** [comment]
@serxa could it be why dashboards with multiple [values](https://play.clickhouse.com/dashboard#N4IgFg9gzgLiBc4YwA5XgegygNgQwE8A6AYxwEsSBrSAVygFNSIBbEAGhHoYCcERchDiACOtXuQZQEAbVAxyMHA34AhcgDs8PAgAIARrXI4AJtM5jeBfgGUAogBk7AYQAqAHQ26YEGzG0wAPIAZgCSGjC8AG54OAAUsAEMJgD6eDDsuqEAcq52AEoAagCCDrrAPBC0GiYAElU86ACq4TAAzABMAL4AVABsAAy6ALI5TXkAlPDwOa66xTa6dDzsnrpaLAy6eFAGRqYpGwyrXnhRAOZxJKy4DJGp6boAtLqJPPdpMBPzi2fnKQpNp4AGL5QLDXQmBjBPC0HAwIgAdwgPCowRwEERKQAVhB9FBPAB1WoFOxLHbFHDxfD6Bg4KCZGQAckYOGCT0gsGSTMyTMMxihPCZAF1vsVsgARNZvD6PVR2VyEux2bLlYKVFjwPw8TTnLrzSXlHxamA6jR6g1SryJGD0XQAXl0TOuLFu9yZlrW1w0ZHo5AgXkdLNoJBIUigHvFVt0PAYKGgihReiDzgo1Hq3AwqcoVAzjEjkrWcXjUEU-o0cSOvNU+0F6g0TO+KN0JbLAcreE21drT30mm0BEbE08AHEwU0AAq6VQATSWDUy-IOR08gXyEoK07ny0yfwB5E2ug3Nmci9rh07Ki67HkimU-AlDD7eC8S7MwksOlsjhcHi8Pj8AIQlaaJYgSfx3mST5MlmAoSjKCoqhqDNGngFoIk6XpBhGMZJmmWYfnnWgVmlXBFFUAhCTARQpBQPAww7LsAEYJhkJjhW2XY3wvLs1j+K4bmUWUYGeV4IOEsVfgufcgQ0UFwUhaFYXhJEUTRDEsVxfEiRJfIyTACkqTiGk6QZXRmVZdlOXdXk314EUxULa1xKguUFSVFU1Q1E0zQtKMjQgHzdX1KNpX8W1diDF03W5T0vG9X1SwDB0nSgEMwygCM4pjOMEx8HQUqZbN0yqRgszTXNSoYAto2LPLy0Y44nRrAVeEffRG10ZtWwUdsq2ans6OoPBzmqiZhw0MdAknLciJWPYBR4hhV3XTdZzm3dpMBLZj1PBbl0vEBr1vJQVEQYEdhgVwpDgCxxC-RB7CcNxvF8cTgIiUD4hlVyMiyXI4NKcpKmqOoGmaVpMP6IZRmycY7CmGZckIndPH46KhN+0SfoeL5CL3bbdHVVhFJhOEEWRVF0UxHE8QJDRiVJckoEpak8FpelGRZOkrOgGynTsoVRWynHPmndzlVVYBic1bVgstAKgvNEKnLE9I7SiwS7li0L4oDRLy0KtLQ3DGq1ljHqk0K4rKszG282q7Keoa-qmQu2BrtgRtR3HKd1uWFaN3yWbliO4VODonhO2keBQBB5Dwf4Ji+gADmEGX+A6AYOg6J4mNzgYmOEHxM+zgAWPOmKeDoi+vEBGG0EgwBST9rEen8XoUU7Mlb3R5IhKACC5FgiBMHYwH0CBtDMXRGb0yFx8n6fCsCKJokkREmWEEh6B8FhyAAL2SBBTXELogA) aren't readable at all?

**Comment by serxa** [comment]
> Or it's rather another PR? https://github.com/ClickHouse/ClickHouse/pull/60391
Yes, That PR changed colors. And I did not test the dark theme there while reviewing...

**Comment by serxa** [comment]
I checked 24.4.1.1323. And it works just find for me (after https://github.com/ClickHouse/ClickHouse/pull/60391)
Screenshot 2024-05-06 at 12 18 05

**Pull request merged**
