### PR TITLE
Fix bug with Throttler and query speed estimation

### LINKED ISSUE #5732: max_execution_speed doesn't seem to work as expected
#4430 introduced two new settings:
* max_execution_speed 
* max_execution_speed_bytes

Both of which should be very useful in a multi tenant environment, especially as a poor's man non-conserving query prioritization.

When progressImpl is called it checks current execution speed and if it higher than set in settings it sleeps, thus introducing back-pressure to executing threads. (?)

It doesn't seem to work when running aggregations (`SELECT count()...`) over a cluster (a distributed table). These limits are checked only on the executor node on a progress packet arrival, even though the thread that checked the limit sleeps, the back-pressure is not propagated to leaf nodes as these have no data to push to executor until the whole query is finished.

cc @zhang2014

### LINKED ISSUE #6228: max_execution_speed setting does not work if SAMPLE is used
CC @zhang2014 

```
example.yandex.ru :) SET max_execution_speed = 1000000

SET max_execution_speed = 1000000

Ok.

0 rows in set. Elapsed: 0.001 sec. 

example.yandex.ru :) SELECT ...

1 rows in set. Elapsed: 10.360 sec. Processed 318.26 million rows, 57.65 GB (30.72 million rows/s., 5.56 GB/s.)
```

### LINKED ISSUE #11297: The setting max_execution_speed does not work at all.
**Describe the bug**

```
SET max_execution_speed = 1000000;
SELECT count() FROM system.numbers;
```

### PR DESCRIPTION
**Pull request by alexey-milovidov**
Changelog category (leave one):
- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix bug when query speed estimation can be incorrect and the limit of `min_execution_speed` may not work or work incorrectly if the query is throttled by `max_network_bandwidth`, `max_execution_speed` or `priority` settings. Change the default value of `timeout_before_checking_execution_speed` to non-zero, because otherwise the settings `min_execution_speed` and `max_execution_speed` have no effect. This fixes #11297. This fixes #5732. This fixes #6228. Usability improvement: avoid concatenation of exception message with progress bar in `clickhouse-client`.

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
Broken in https://github.com/ClickHouse/ClickHouse/pull/7181

**Comment by alexey-milovidov** [comment]
The issue https://github.com/ClickHouse/ClickHouse/issues/6417 is not relevant to this bug but has to be checked again. No more relevant issues found on GitHub.

**Comment by alexey-milovidov** [comment]
>  Stress test (thread) — Sanitizer assert (in stderr.log)

Actually it's OOM on Sandbox server (misleading message).

**Comment by alexey-milovidov** [comment]
Note: this bugfix will be backported.

But the only line that needs to be backported is:
https://github.com/ClickHouse/ClickHouse/pull/11296/files#diff-70721e41703630a99a23b52236158e68R56

**Comment by alexey-milovidov** [comment]
Here is the only commit that has to be backported: https://github.com/ClickHouse/ClickHouse/pull/11296/commits/9d39fc6dcbc49b8a6b187a30fb7a5354229efc76

**Comment by KochetovNicolai** [comment]
@alexey-milovidov you should not add tags before bugfix is backported. Otherwise release script will think that you have already done it manually.

**Pull request merged**
