### PR TITLE
Don't count unused arena bytes as read_bytes in AggregateFunction types

### LINKED ISSUE #48606: Extremely large read bytes reported when reading columns of AggregateFunction type
Create a dumb (don't expect it to make sense) table with an AggregateFunction type:

```sql
CREATE TABLE test_read_bytes (number Int64, `id` AggregateFunction(argMax, String, DateTime64(3)))
Engine=MergeTree()
ORDER BY tuple()
AS
Select number, argMaxState(number::String, now()::DateTime64(3))
from numbers(200000)
group by number;
```

Check the parts:
```
SELECT
    part_type,
    rows,
    bytes_on_disk,
    data_compressed_bytes,
    data_uncompressed_bytes
FROM system.parts
WHERE table = 'test_read_bytes'

Query id: d357fae0-02a0-4c35-85e7-6a2247c2ff9c

┌─part_type─┬───rows─┬─bytes_on_disk─┬─data_compressed_bytes─┬─data_uncompressed_bytes─┐
│ Wide      │ 200000 │       2195749 │               2194495 │                 5488890 │
└───────────┴────────┴───────────────┴───────────────────────┴─────────────────────────┘
```

And columns:

```
SELECT
    database,
    table,
    column,
    formatReadableSize(sum(column_data_compressed_bytes) AS size) AS compressed,
    formatReadableSize(sum(column_data_uncompressed_bytes) AS usize) AS uncompressed,
    round(usize / size, 2) AS compr_ratio,
    sum(rows) AS rows_cnt,
    round(usize / rows_cnt, 2) AS avg_row_size
FROM system.parts_columns
WHERE (active = 1) AND (table = 'test_read_bytes')
GROUP BY
    database,
    table,
    column
    WITH TOTALS
ORDER BY size DESC

Query id: e826e3b4-2eb1-4977-966e-d97cdce87630

┌─database─┬─table───────────┬─column─┬─compressed─┬─uncompressed─┬─compr_ratio─┬─rows_cnt─┬─avg_row_size─┐
│ default  │ test_read_bytes │ id     │ 1.28 MiB   │ 3.71 MiB     │        2.89 │   200000 │        19.44 │
│ default  │ test_read_bytes │ number │ 831.00 KiB │ 1.53 MiB     │        1.88 │   200000 │            8 │
└──────────┴─────────────────┴────────┴────────────┴──────────────┴─────────────┴──────────┴──────────────┘

Totals:
┌─database─┬─table─┬─column─┬─compressed─┬─uncompressed─┬─compr_ratio─┬─rows_cnt─┬─avg_row_size─┐
│          │       │        │ 2.09 MiB   │ 5.23 MiB     │         2.5 │   400000 │        13.72 │
└──────────┴───────┴────────┴────────────┴──────────────┴─────────────┴──────────┴──────────────┘

2 rows in set. Elapsed: 0.010 sec. 
````

The column number takes ~0.8MB compressed and 1.5MB uncompressed. If I read it all in a simple query:

```
SELECT sum(number)
FROM test_read_bytes

Query id: 615d9db9-1304-44b7-9132-35e0b56929d0

┌─sum(number)─┐
│ 19999900000 │
└─────────────┘

SELECT
    read_rows,
    formatReadableSize(read_bytes)
FROM system.query_log
WHERE (query_id = '615d9db9-1304-44b7-9132-35e0b56929d0') AND (type > 1)

Query id: cc0e13a6-a2e1-41c5-9eb5-40bc8027bf4c

Row 1:
──────
read_rows:                      200000
formatReadableSize(read_bytes): 1.53 MiB

1 row in set. Elapsed: 0.006 sec. Processed 13.19 thousand rows, 818.03 KB (2.12 million rows/s., 131.17 MB/s.)
``` 

We can see that the read_bytes reported by query_log, progress events, summary headers, etc. is 1.53MB which is the same as the uncompressed data. Expected.

On the other hand, if now we read the other column (type `AggregateFunction(argMax, String, DateTime64(3))`):

```
Mordor :) Select argMaxMerge(id) from test_read_bytes;

SELECT argMaxMerge(id)
FROM test_read_bytes

Query id: f2da4403-82c5-4a4e-8596-492216b50456

┌─argMaxMerge(id)─┐
│ 46156           │
└─────────────────┘

1 row in set. Elapsed: 0.022 sec. Processed 200.00 thousand rows, 25.11 MB (9.08 million rows/s., 1.14 GB/s.)

Mordor :) Select read_rows, formatReadableSize(read_bytes) from system.query_log where query_id = 'f2da4403-82c5-4a4e-8596-492216b50456' and type > 1 \G

SELECT
    read_rows,
    formatReadableSize(read_bytes)
FROM system.query_log
WHERE (query_id = 'f2da4403-82c5-4a4e-8596-492216b50456') AND (type > 1)

Query id: 5c523d46-ce5d-45ca-8c4e-d8499983d617

Row 1:
──────
read_rows:                      200000
formatReadableSize(read_bytes): 23.95 MiB

1 row in set. Elapsed: 0.004 sec. Processed 13.20 thousand rows, 818.28 KB (3.16 million rows/s., 195.75 MB/s.)
```

The reported read bytes is almost 24MB, that is 6x more than the size of the uncompressed files for that column.

Looking at the code the different between the expectation and the reported bytes comes from the fact that `read_bytes` has absolutely nothing to do with bytes read from disk (or anywhere else) and instead it's the bytes the column occupies in memory after being read. As this `AggregateFunction` reserves space in memory as part of its internal arena, it reports way more read bytes than expected.

For the example above CH does several reads:
* 49152 rows => 49152 * 8 + Arena 4190208 = 4583424 "read bytes"
* 8192 rows => 8192 * 8 + Arena 1044480 = 1110016 "read bytes" ==> 18 times
* 3392 rows => 3392 * 8 + Arena 520192 = 547328 "read bytes"

No idea why it does 20 reads of 2 different sizes, that doesn't look great but it doesn't seem to matter. The sum of the memory usage is 25111040 bytes => 23,947 MB.

So while I understand now where the number comes from, it doesn't seem very appropriate to return this value as read_bytes.

I see several ways forward:
* Leave it as is and improve the documentation.
* Report truly read bytes (uncompressed but also including other generators like table views, CTEs, etc)
* Change ColumnAggregateFunction and other column types to only report **used** memory and not memory reserved for arenas or containers but currently unused. When you want all the memory IColumn already has `allocatedBytes()`
* Don't use IColumn::byteSize() to report read_bytes progress and use something else. Not sure what.

Thoughts?

### PR DESCRIPTION
**Pull request by Algunenano**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
- In AggregateFunction types, don't count unused arena bytes as `read_bytes`.

### Documentation entry for user-facing changes

Several changes:
- Reduce a bit the dependencies over the Arena.h header (to make it a bit faster to iterate, but not much).
- Add a new member in Arena to differentiate between allocated bytes (pre-allocated in the Arena or wasted in holes) and reserved_bytes (bytes requested via allocations to the arena).
- Change `ColumnAggregateFunction` to use reserved_bytes() when reporting the column `::byteSize()`, leaving `allocatedBytes()` the same. This allows more precise reporting of read_bytes when working with these column types.

Closes https://github.com/ClickHouse/ClickHouse/issues/48606

### CODE REVIEW

**Comment by Algunenano** [comment]
All green. I didn't know this was possible

**Comment by Algunenano** [comment]
It'd be great if somebody could review this

* Failures: `Integration tests (tsan) [3/6]` hdfs failed to start

**Comment by alexey-milovidov** [comment]
"Reserved" bytes sounds misleading.

It is expected that it means something similar to std::vector::**reserve** and std::vector::capacity, but the meaning is the opposite.

What do you think about renaming it to "used" bytes?

**Comment by Algunenano** [comment]
> What do you think about renaming it to "used" bytes?

Makes sense to me. I've changed it in the PR

**Pull request merged**
