### PR TITLE
Translate zh/engines/database-engines/materialized-mysql: translate t…

### PR DESCRIPTION
**Pull request by ghost**
Changelog category (leave one):
- Documentation (changelog entry is not required)

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
…o zh and update index.md

### CODE REVIEW

**Comment by kitaisreal** [comment]
@Mergifyio update

**Comment by cnmade** [comment]
@kitaisreal hello, can this merge request be done

**Comment by cnmade** [comment]
I fixed the wrong translate file affect. it's no problem i think now.

**Comment by cnmade** [comment]
@kitaisreal  can this pull request be done?

**Review by kitaisreal — APPROVED** [review]

**Pull request merged**
