### PR TITLE
ActionsDAG: fix wrong optimization

### LINKED ISSUE #47317: HAVING returning no result
```
CREATE TABLE t1 (c0 Int32, PRIMARY KEY (c0)) ENGINE=MergeTree;
INSERT INTO t1 VALUES (1554690688);
```

```
SELECT MIN(t1.c0)
FROM t1
GROUP BY
    (-sign(cos(t1.c0))) * (-max2(t1.c0, t1.c0 / t1.c0)),
    t1.c0 * t1.c0,
    sign(-exp(-t1.c0))
SETTINGS aggregate_functions_null_for_empty = 1, enable_optimize_predicate_expression = 0

Query id: 53d13f67-8069-48ce-b614-6c04da2dba07

┌────MIN(c0)─┐
│ 1554690688 │
└────────────┘

1 row in set. Elapsed: 0.035 sec.
```
Original report:
```
SELECT MIN(t1.c0)
FROM t1
GROUP BY
    (-sign(cos(t1.c0))) * (-max2(t1.c0, t1.c0 / t1.c0)),
    t1.c0 * t1.c0,
    sign(-exp(-t1.c0))
HAVING -(-(MIN(t1.c0) + MIN(t1.c0))) AND (pow('{b' > '-657301241', log(-1004522121)) IS NOT NULL)
UNION ALL
SELECT MIN(t1.c0)
FROM t1
GROUP BY
    (-sign(cos(t1.c0))) * (-max2(t1.c0, t1.c0 / t1.c0)),
    t1.c0 * t1.c0,
    sign(-exp(-t1.c0))
HAVING NOT (-(-(MIN(t1.c0) + MIN(t1.c0))) AND (pow('{b' > '-657301241', log(-1004522121)) IS NOT NULL))
UNION ALL
SELECT MIN(t1.c0)
FROM t1
GROUP BY
    (-sign(cos(t1.c0))) * (-max2(t1.c0, t1.c0 / t1.c0)),
    t1.c0 * t1.c0,
    sign(-exp(-t1.c0))
HAVING (-(-(MIN(t1.c0) + MIN(t1.c0))) AND (pow('{b' > '-657301241', log(-1004522121)) IS NOT NULL)) IS NULL
SETTINGS aggregate_functions_null_for_empty = 1, enable_optimize_predicate_expression = 0

Query id: b229fc66-42a6-4240-8374-48a3b5c5d8b5

Ok.

0 rows in set. Elapsed: 0.143 sec.
```
Simplified bug:
`-(-(MIN(t1.c0) + MIN(t1.c0))) AND (pow('{b' > '-657301241', log(-1004522121)) IS NOT NULL)` is 1 when computed outside HAVING, when we add it there it returns nothing:
```
SELECT
    MIN(t1.c0),
    -(-(MIN(t1.c0) + MIN(t1.c0))) AND (pow('{b' > '-657301241', log(-1004522121)) IS NOT NULL) AS f
FROM t1
GROUP BY c0
HAVING -(-(MIN(t1.c0) + MIN(t1.c0))) AND (pow('{b' > '-657301241', log(-1004522121)) IS NOT NULL)

0 rows in set. Elapsed: 0.040 sec.
```

If I just add `true AND` in HAVING it is fixed
```
SELECT
    MIN(t1.c0),
    -(-(MIN(t1.c0) + MIN(t1.c0))) AND (pow('{b' > '-657301241', log(-1004522121)) IS NOT NULL) AS f
FROM t1
GROUP BY c0
HAVING true AND -(-(MIN(t1.c0) + MIN(t1.c0))) AND (pow('{b' > '-657301241', log(-1004522121)) IS NOT NULL)

┌────MIN(c0)─┬─f─┐
│ 1554690688 │ 1 │
└────────────┴───┘

1 row in set. Elapsed: 0.043 sec.
```

### PR DESCRIPTION
**Pull request by aiven-sal**
Casting larger intergers to UInt8 can change the condition. e.g.
256 cast to UInt8 is 0, but it should be interpreted as true.

Closes #47317

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in official stable or prestable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fixed some optimizations that could change the result of some conditions.

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by qoega** [comment]
Why it is important for large ints? When it can be incorrect? Like 2^n overflowed to 0? Can you add such example, because I thought our integer type comparison should work like `x != 0`

**Comment by qoega** [comment]
@KochetovNicolai WDYT to throw this optimization?

**Comment by robot-ch-test-poll3** [comment]
This is an automated comment for commit 647472ed46d77e7c12e0571f18d8cab791cd8ece with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/47584/647472ed46d77e7c12e0571f18d8cab791cd8ece/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Review by SmitaRKulkarni — APPROVED** [review]
LGTM

**Pull request merged**
