### PR TITLE
Make Poco HTTP Server zero-copy again

### PR DESCRIPTION
**Pull request by abyss7**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Performance Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Partially reimplement HTTP server to make it making less copies of incoming and outgoing data. It gives up to 1.5 performance improvement on inserting long records over HTTP.

### CODE REVIEW

**Comment by abyss7** [comment]
Fuzzer (debug): #20046

**Comment by abyss7** [comment]
Arcadian build is fine: check the link

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
Ok.

1. Finally we can increase the 16KB limit on URL size. We can make it in next PR after merge.
2. The code in HTTP directory is based on Poco. We should put README.md file for attribution.
3. There can be dead code (unused methods) there (like sendFile). We can review and remove these methods.
4. `while (in.read(ch) && !Poco::Ascii::isSpace(ch) && method.size() <= MAX_METHOD_LENGTH) method += ch;` - we can introduce "limited read until" in ReadHelpers.
5. `catch (Poco::Net::NoMessageException &)` - const.
6. `void stopAll(bool abortCurrent = false);` - variable name is out of style.
7. `wrapReadBufferReference` maybe just return std::unique_ptr in `request.getStream()`.
8. Sending responses still involving ostream. Decided to address it in subsequent PR.

**Comment by filimonov** [comment]
Why creating copy not changing the poco itself? (we already have a list of own patches to poco). 

Not easy to see the diff with the current poco version.

Is there some chances to push that into the poco upstream?

**Comment by alexey-milovidov** [comment]
No chance.

The whole purpose of this patch is to replace iostreams to Read/WriteBuffers.

**Comment by alexey-milovidov** [comment]
Also we are looking into perspective to also rewrite TCPServer.

**Comment by alexey-milovidov** [comment]
@filimonov See https://github.com/ClickHouse/ClickHouse/issues/8441#issuecomment-782591531

**Comment by abyss7** [comment]
> Why creating copy not changing the poco itself? (we already have a list of own patches to poco).
> 
> Not easy to see the diff with the current poco version.
> 
> Is there some chances to push that into the poco upstream?

At lease now we can remove our unused patches from Poco - for simpler upstream update in the future.

**Comment by filimonov** [comment]
Cool. Thanks, now it's crear. Makes 100% sense.

**Pull request merged**
