### PR TITLE
Add option `--show-whitespaces-in-diff` to clickhouse-test

### PR DESCRIPTION
**Pull request by vdimir**
### Changelog category (leave one):

- Not for changelog (changelog entry is not required)

Some times reference differs from output only because of white spaces (e.g. string column with empty value as a last column

```bash
rg -l '\t$' ./tests/queries/0_stateless/*.reference | wc -l
264
```

which is difficult to see)

Perhaps it's worth only adding `$` in the end of the line, but in this PR all tabs replaced as well. So not sure should we use `cat -te` or `cat -e`

### CODE REVIEW

**Comment by robot-clickhouse** [comment]
*This is an automated comment for commit bb10bdfb2c2daa63a230f08bece03d9e27ad5b92 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/57870/bb10bdfb2c2daa63a230f08bece03d9e27ad5b92/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td><a href="https://github.com/ClickHouse/ClickHouse/actions/runs/7210953521">✅ success</a></td></tr>
<tbody>
</table>
</details>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/57870/bb10bdfb2c2daa63a230f08bece03d9e27ad5b92/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Comment by rschu1ze** [comment]
Putting a `$` behind *every* line is a bit aggressive to me, perhaps we can put it only at the end of lines which are empty or end with whitespace. But either alternative would be fine for me.

**Review by novikd — APPROVED** [review]

**Comment by vdimir** [comment]
I'm changing it to display `$` only in lines that ends with whitespace, but it also may confuse why some lines have extra character and some doesn't

```
--- /home/ubuntu/ClickHouseA/tests/queries/0_stateless/00001_select_1.reference 2023-12-27 14:13:39.458028687 +0000
+++ /home/ubuntu/ClickHouseA/tests/queries/0_stateless/00001_select_1.stdout    2023-12-27 14:13:42.498046662 +0000
@@ -1,2 +1,2 @@
-1
+1      $
        1
```

**Comment by vdimir** [comment]
Since we made it not too aggressive, perhaps it's worth to enable by default?

**Pull request merged**
