### PR TITLE
Fixed wrong python test name pattern

### PR DESCRIPTION
**Pull request by Demilivor**
It looks like the integration tests on Github are not running correctly.
Let's take a look at [ClickHouse Integration Tests (release) 1/4 for PR #52658](https://s3.amazonaws.com/clickhouse-test-reports/52658/cfa06725cced936845b3777fa1cddb808d536598/integration_tests__release__%5B1_4%5D.html)
Let's select the [integration_run_parallel0_0.log](https://s3.amazonaws.com/clickhouse-test-reports/52658/cfa06725cced936845b3777fa1cddb808d536598/integration_tests__release__%5B1_4%5D/integration_run_parallel0_0.log) run, in which 100 tests.
It ended with an error.

`Command 'docker run --rm --name clickhouse_integration_tests_ce9d65 ... returned non-zero exit status 5.`
The tests that should have been run in this run, for example

```
test_allowed_client_hosts/test.py::test_allowed_host
test_allowed_client_hosts/test.py::test_denied_host
```

`test_disabled_access_control_improvements/test_row_policy.py::test_dcl_users_with_policies_from_users_xml`
cannot be found in the integration test run report.
There is another run with same error [integration_run_parallel0_0.log](https://s3.amazonaws.com/clickhouse-test-reports/52658/cfa06725cced936845b3777fa1cddb808d536598/integration_tests__release__%5B3_4%5D/integration_run_parallel0_0.log) in [ClickHouse Integration Tests (release ) 3/4 for PR #52658](https://s3.amazonaws.com/clickhouse-test-reports/52658/cfa06725cced936845b3777fa1cddb808d536598/integration_tests__release__%5B3_4%5D.html)
So roughly 200 integration tests are never run through Github CI.

Runner plan includes strings like:
```
        SETUP    F dst_node_addrs (fixtures used: started_cluster)[('10.5.172.10', '2001:3984:3989::1:1000')]
```

grep by `::` will capture this line, but it's not a valid test.

Using `::test` grep pattern should fixing the issue

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by robot-ch-test-poll3** [comment]
This is an automated comment for commit ab006fcd092541140328396a0be7a9ff1d424143 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/53713/ab006fcd092541140328396a0be7a9ff1d424143/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Comment by rvasin** [comment]
@Felixoid there is a bug in CI script related to grepping the test names. Could you please take a look?

**Comment by Felixoid** [comment]
I am not familiar with the script. What is expected and what's wrong?

**Review by azat — APPROVED** [review]
LGTM

BTW maybe you can also fix test's report, so that if the command failed (like in the description) all tests will be marked as broken?

**Comment by Demilivor** [comment]
What `_get_all_tests` function does: Returns a list of all tests.

Expected result:
Returns all existing and valid test names. 

Actual result:
A list with test names contains names like `10.5.172.10`, `2001:3984:3989::1:1000` (`grep '::'` finds such strings).

the function `_get_all_tests`
receives all the tests by
`./tests/integration/runner --binary build/programs/clickhouse -- --setup-plan`

It generates such a report [test_plan.txt](https://github.com/ClickHouse/ClickHouse/files/12448974/test_plan.txt). The file contains strings like `2001:3984:3989::1:1000`
Then the `_get_all_tests` function does `grep -F '::'`. `2001:3984:3989::1:1000` matches search condition. 
so `_get_all_tests` function includes the `2001:3984:3989::1:1000` string into list of all tests.

Finally, the runner will try to execute `2001:3984:3989::1:1000` test and will fail.

What the fix from this PR does is:
Instead of grep grep '::'` it does `grep '::test'`. Then `2001:3984:3989::1:1000` will not match.
The `::test` pattern is valid because all pytest tests must follow the name convention with 'test' at the beginning of the function name (see https://www.skill2lead.com/pytest/pytest-naming-conventions.php#:~:text=File%20name%20should%20start%20with,which%20is%20actually%20looks%20like.)


> BTW maybe you can also fix test's report, so that if the command failed (like in the description) all tests will be marked as broken?

Could You please guide me on how I can do that?

**Comment by Felixoid** [comment]
Ok, thank you for clarifying what's going on there.

I'd suggest using commit https://github.com/ClickHouse/ClickHouse/commit/05715c7d523e2e95464f15f94d4c15b8bc7567ad as it gets rid of unnecessary grep, sed, and other hard-to-read shell staff, and parses the full output log file

**Review by Felixoid — CHANGES_REQUESTED** [review]
https://github.com/ClickHouse/ClickHouse/commit/05715c7d523e2e95464f15f94d4c15b8bc7567ad contains changes to apply, but I can't push them to the fork

**Comment by Demilivor** [comment]
Thanks for suggestion,

I merged it into the branch. + changed '::' into '::test' search string:

```py
or "::test" not in line # test names contain '::test'
```

**Comment by Felixoid** [comment]
`::test` is an unnecessary change. All lines with IP addresses start with spaces. And I am not sure if _every_ test starts with `test_`. So I'd rather roll it back.

**Comment by Demilivor** [comment]
All PyTest tests must follow the naming [convention](https://www.skill2lead.com/pytest/pytest-naming-conventions.php).
So "::test" must match every test.

**Review by Felixoid — APPROVED** [review]

**Comment by tavplubix** [comment]
@Felixoid, you forgot to check the CI status before merging. Sorry, but I have to revert this PR

**Comment by Felixoid** [comment]
I couldn't imagine how a fixed function to get the test names would break the tests. Let's see if the revert will help

**Comment by tavplubix** [comment]
> I couldn't imagine how a fixed function to get the test names would break the tests. 

It doesn't matter, we must check all failures (including unrelated ones) before merging. Feel free to ask someone if you don't know how/what to check.

However, I'm 99% sure it's related. Check this [query](https://play.clickhouse.com/play?user=play#CldJVEgKICAgICd0ZXN0X2NvbmN1cnJlbnRfYmFja3Vwc19zMy90ZXN0LnB5Ojp0ZXN0X2NvbmN1cnJlbnRfYmFja3VwcycgQVMgbmFtZV9zdWJzdHIsCiAgICA5MCBBUyBpbnRlcnZhbF9kYXlzLAogICAgKCdTdGF0ZWxlc3MgdGVzdHMgKGFzYW4pJywgJ1N0YXRlbGVzcyB0ZXN0cyAoYWRkcmVzcyknLCAnU3RhdGVsZXNzIHRlc3RzIChhZGRyZXNzLCBhY3Rpb25zKScpIEFTIGJhY2twb3J0X2FuZF9yZWxlYXNlX3NwZWNpZmljX2NoZWNrcwpTRUxFQ1QKICAgIHRvU3RhcnRPZkhvdXIoY2hlY2tfc3RhcnRfdGltZSkgQVMgZCwKICAgIGNvdW50KCksCiAgICBncm91cFVuaXFBcnJheShwdWxsX3JlcXVlc3RfbnVtYmVyKSBBUyBwcnMsCiAgICBhbnkocmVwb3J0X3VybCkKRlJPTSBjaGVja3MKV0hFUkUgKChub3coKSAtIHRvSW50ZXJ2YWxEYXkoaW50ZXJ2YWxfZGF5cykpIDw9IGNoZWNrX3N0YXJ0X3RpbWUpIEFORCAocHVsbF9yZXF1ZXN0X251bWJlciBOT1QgSU4gKAogICAgU0VMRUNUIHB1bGxfcmVxdWVzdF9udW1iZXIgQVMgcHJuCiAgICBGUk9NIGNoZWNrcwogICAgV0hFUkUgKHBybiAhPSAwKSBBTkQgKChub3coKSAtIHRvSW50ZXJ2YWxEYXkoaW50ZXJ2YWxfZGF5cykpIDw9IGNoZWNrX3N0YXJ0X3RpbWUpIEFORCAoY2hlY2tfbmFtZSBJTiAoYmFja3BvcnRfYW5kX3JlbGVhc2Vfc3BlY2lmaWNfY2hlY2tzKSkKKSkgQU5EIChwb3NpdGlvbih0ZXN0X25hbWUsIG5hbWVfc3Vic3RyKSA+IDApIEFORCAodGVzdF9zdGF0dXMgSU4gKCdGQUlMJywgJ0VSUk9SJywgJ0ZMQUtZJykpCkdST1VQIEJZIGQKT1JERVIgQlkgZCBERVNDCg==). The test was not really flaky, but then it failed two times in a row in this PR, and started to fail everywhere after this PR was merged.

**Comment by Felixoid** [comment]
You are right, but not completely

The tests are somehow completely [missed](https://play.clickhouse.com/play?user=play#U0VMRUNUICogRlJPTSBjaGVja3MgCldIRVJFIDEKICAgIEFORCB0b0RhdGUoY2hlY2tfc3RhcnRfdGltZSkgPSB0b0RhdGUoJzIwMjMtMDgtMjknKQogICAgQU5EIGNvbW1pdF9zaGEgSU4gKCc0NjRjNDlmZGNiMjAxZjVkZWFlN2E0NzZmOWZiM2QwODVlMDAyZjUxJywnMjVlZGE3ZjM1OGJmZDY0ZTRiZmIzZjA3Y2QxZjUzYzA5MjM3MmNmZCcpCiAgICBBTkQgdGVzdF9uYW1lIElOICgndGVzdF9jb21wb3NhYmxlX3Byb3RvY29scy90ZXN0LnB5Ojp0ZXN0X2Nvbm5lY3Rpb25zJywgJ3Rlc3RfY29uY3VycmVudF9iYWNrdXBzX3MzL3Rlc3QucHk6OnRlc3RfY29uY3VycmVudF9iYWNrdXBzJykKT1JERVIgQlkgY2hlY2tfc3RhcnRfdGltZQ==)

There are fully finished [asan](https://s3.amazonaws.com/clickhouse-test-reports/0/464c49fdcb201f5deae7a476f9fb3d085e002f51/ci_running.html) tests.

**Comment by Demilivor** [comment]
> The tests are somehow completely [missed](https://play.clickhouse.com/play?user=play#U0VMRUNUICogRlJPTSBjaGVja3MgCldIRVJFIDEKICAgIEFORCB0b0RhdGUoY2hlY2tfc3RhcnRfdGltZSkgPSB0b0RhdGUoJzIwMjMtMDgtMjknKQogICAgQU5EIGNvbW1pdF9zaGEgSU4gKCc0NjRjNDlmZGNiMjAxZjVkZWFlN2E0NzZmOWZiM2QwODVlMDAyZjUxJywnMjVlZGE3ZjM1OGJmZDY0ZTRiZmIzZjA3Y2QxZjUzYzA5MjM3MmNmZCcpCiAgICBBTkQgdGVzdF9uYW1lIElOICgndGVzdF9jb21wb3NhYmxlX3Byb3RvY29scy90ZXN0LnB5Ojp0ZXN0X2Nvbm5lY3Rpb25zJywgJ3Rlc3RfY29uY3VycmVudF9iYWNrdXBzX3MzL3Rlc3QucHk6OnRlc3RfY29uY3VycmVudF9iYWNrdXBzJykKT1JERVIgQlkgY2hlY2tfc3RhcnRfdGltZQ==)

I think these tests were added to parallel test runner by this PR.
At least `test_composable_protocols/test.py::test_connections` should fail, but it does not run here:
https://github.com/ClickHouse/ClickHouse/pull/53673 

I will fix this test

**Pull request merged**
