### PR TITLE
Use DFA algorithm for sequenceMatch without `(?t)`.

### PR DESCRIPTION
**Pull request by LeoErcolanelli**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

For changelog. Remove if this is non-significant change.

Category (leave one):
- Improvement

## Short description (up to few sentences):
Add an optional parameter to `sequenceMatch` and `sequenceCount` in order to temporary lift the hard-coded limit on the number of iterations.

## Detailed description (optional):
As of today the constant [sequence_match_max_iterations](https://github.com/yandex/ClickHouse/blob/master/dbms/src/AggregateFunctions/AggregateFunctionSequenceMatch.h#L135) sets an arbitrary limit on the number of iterations supported by `sequenceMatch` and `sequenceCount`. In certain cases, making this limit configurable may be desirable ([current opened issue](https://github.com/yandex/ClickHouse/issues/2399)).

In order to do so, a new parameter has been added to those two functions. The fact that the parameter is optional and default to the previous hard-coded value makes this change backward compatible.

I think going for a query setting would have been cleaner but I've found no way to access the query settings from within the implementation of function. If such a way exists, I'll gladly modify the PR in order to interact with the settings rather than an optional parameter.

Let me know if anything is to be changed !

### CODE REVIEW

**Comment by filimonov** [comment]
Maybe it would be better just to that to a user level settings instead of passing that back and forward with every function call?

**Comment by ercolanelli-leo** [comment]
@filimonov Thanks a lot for the quick answer!

I will have a look at all the resources you linked.
In the meantime, regarding the use of a user level setting, how do you go on passing the value of the setting down to the implementation of the function ? It looks like today none of the functions do that yet.

**Comment by filimonov** [comment]
Yep, looks like context is not passed to Aggregate functions while being available in regular functions. Maybe it was done like that by intent? @alexey-milovidov ?

**Comment by ercolanelli-leo** [comment]
@filimonov I gave a try at passing the context down to the `AggregateFunctions` however I encounter 1 issue and I think your greater knowledge of the code base will be of help.

Changing the definition of `AggregateFunctionCreator` in order to accept an additional `Context` argument is pretty straightforward. The issue starts right after:

- `DataTypeAggregateFunction`'s creator function uses `AggregateFunctionFactory::get()` in order to return the `DataType`.

- Because `AggregateFunctionFactory::get()` now take a `Context` it means that `DataTypeFactory` also has to in order for `DataTypeAggregateFunction` to have access to the context.

- This bubbles up everywhere as anything using `DataTypeFactory` has to have access to Context.

I started implementing passing down a Context wherever it's needed but the the diff will be quite big, and I wonder if there is not a clever way of doing it.

What I observed is that `DataTypeFunction` doesn't actually registers itself to the DataTypeFactory, argument's type checking is done mostly in `FunctionArrayMapped.h` and `ActionsVisitor.cpp`. This would effectively break the dependency between `AggregateFunctionFactory` and `DataTypeFactory`. Do you think this is feasible?

**Comment by alexey-milovidov** [comment]
> Yep, looks like context is not passed to Aggregate functions (while being available in regular functions). Maybe it was done like that by intent? @alexey-milovidov ?

No, it just was not needed yet. You can pass a Context to AggregateFunctionFactory.

**Comment by alexey-milovidov** [comment]
@ercolanelli-leo 

`DataTypeAggregateFunction` is a full featured data type that can be stored in tables, manipulated in various ways. In contrast, `DataTypeFunction` is used only to represent temporary value for lambda expression.

You see that adding dependancy on `Context` for `AggregateFunction` is difficult... so, better don't do it.

**Comment by ercolanelli-leo** [comment]
@alexey-milovidov Thanks a lot for the detailed reply!

Regarding the upper bound, I understand from your message that 1 billion would be a suitable upper bound. I'll be adding a check for this upper bound in my PR.

Regarding the algorithm itself. The fact that the backtracking is sub-optimal is also something that I thought of, until I tried to implement a DFA approach.
Even though the supported patterns are really simple, the `(?t)` make it non-trivial for the algorithm to be implemented with a FSM approach. There is maybe a way to support this construct while keeping a linear complexity but I didn't get to find it; if you do I'll be happy to work on the implementation!
What I can do, though, is to implement the DFA approach if no `(?t)` constructs are present inside the pattern, would it be something that interests you?

**Comment by filimonov** [comment]
Still have doubts if such a change introduce something.  If we will allow to parametrize max_itertations in a range (1 million...1 billion) some users will still have an impression that this limit is synthetic (and that's true) and they  will be sure that 'for their one particular case' it should be extended to N+1 billion case, and they 'are ok to wait'.

May be it's better to consider an option to make it configurable in server config (it's ok to expect that all servers in a cluster will have the same settings).

I agree that the best would be to improve algorithm.

**Comment by ercolanelli-leo** [comment]
If we want to pass the Context down to the aggregating function I actually have a commit ready. It's a rather big change and I am not sure if I went with the best solution. If you wish I can push the commit on this branch for you to see.

**Comment by filimonov** [comment]
> If we want to pass the Context down to the aggregating function I actually have a commit ready. 

No. As @alexey-milovidov said it's not the best idea. 
But beside user level config, there is also a server config - config.xml (from poco config() ).

I think it's worth to try to improve the performance irst.

I din't dig into that, but it looks like you can just try to preprocess the sequence of events with simple DFA just to collect / filter out only needed events, ignoring time conditions at the begining, and each time when last condition is satisfied - check the time conditions (if any) back inside filtered sequence (with backticks).  

So your DFA an collect sometimg like: all events matching first condition and their offset since sequence start, all the events matching second condition which appears AFTER first match of first conditions and their offsets since sequence start, etc. When you get to last condition you need to check times inside that filtered sequence.

**Comment by alexey-milovidov** [comment]
Let's merge this PR first.

**Comment by alexey-milovidov** [comment]
Can you also use `dfa_match` if possible for `sequenceCount`?

**Comment by alexey-milovidov** [comment]
PS. With DFA we process every event just once. We can avoid events accumulation in aggregate function state, and process DFA completely in streaming fashion. We can implement it in subsequent PR.

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
PS. If the number of states is small (for example, 16), we can use extremely efficient implementation based on table lookup (for every combination of active states).

**Pull request merged**
