### PR TITLE
JIT for compare functions

### PR DESCRIPTION
**Pull request by taiyang-li**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Jit for compare functions, may improve performance, I'm not sure.

### CODE REVIEW

**Comment by robot-ch-test-poll3** [comment]
This is an automated comment for commit 17ff7453388f7f3b33afbf4b1ade82a468d4d1f9 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/53775/17ff7453388f7f3b33afbf4b1ade82a468d4d1f9/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Comment by taiyang-li** [comment]
@kitaisreal do you have time to review it?  BTW, I met crash issue when I open compilation for functions `and` and `or`, I'm new to JIT, do you know any background information about it! Thanks!

**Comment by taiyang-li** [comment]
Some learning materials for JIT, just for recording: 
- Getting started with llvm core libs: https://getting-started-with-llvm-core-libraries-zh-cn.readthedocs.io/zh_CN/latest/index.html
- LLVM IR to C: https://github.com/JuliaHubOSS/llvm-cbe
- Compile LLVM IR: https://alive2.llvm.org/ce/
- LLVM IR Reference: https://llvm.org/docs/LangRef.html

**Comment by kitaisreal** [comment]
We disabled JIT for compare functions, because there is bug in LLVM 15 that lead to crash https://github.com/ClickHouse/ClickHouse/issues/50323.
We need to migrate to LLVM 17, but our CHJIT implementation relies on a lot of interfaces that gets deprecated.
Maybe we can compile compare functions and detect that there are no "if" or "multiIf" function in ExpressionJIT.
I also plan to start migration to LLVM 17, but not sure when.

**Comment by taiyang-li** [comment]
> We disabled JIT for compare functions, because there is bug in LLVM 15 that lead to crash #50323. We need to migrate to LLVM 17, but our CHJIT implementation relies on a lot of interfaces that gets deprecated. Maybe we can compile compare functions and detect that there are no "if" or "multiIf" function in ExpressionJIT. I also plan to start migration to LLVM 17, but not sure when.

Thanks for explaination. I'll close this PR temporarily.

**Pull request closed without merging**
