### PR TITLE
fix "no description for the check yet, please add it in..." in github CI

### PR DESCRIPTION
**Pull request by Blargian**
For Fast tests the description is not visible and instead displays `There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS`. See screenshot below:

---

Screenshot from 2024-01-25 20-47-22

---

I can't actually test this from my side but I think the issue is the naming of `Fast test` instead of `Fast tests` (plural) for the lambda in `ci_config.py` as the check description is present. 

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by robot-ch-test-poll4** [comment]
*This is an automated comment for commit d8f0a442523bb4fd8a8bf3ad86357adf25eed2bc with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/59240/d8f0a442523bb4fd8a8bf3ad86357adf25eed2bc/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/59240/d8f0a442523bb4fd8a8bf3ad86357adf25eed2bc/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Comment by Blargian** [comment]
Ironically, with fast tests failing on this pull request the description now shows up correctly...  

image

**Comment by Algunenano** [comment]
Please update with master/HEAD.

**Comment by Blargian** [comment]
Solved with #59395, closing this.

**Pull request closed without merging**
