### PR TITLE
Update check-large-objects.sh to be language neutral

### PR DESCRIPTION
**Pull request by wudanzy**
The previous implementation uses `total` keyword to filter out lines that contains the total size of objects under a directory. But when the OS uses other language, it fails to filter out that line, so the script would fail. 

This implementation changes the script to match only lines that contains object file by their extension. This implementation would be language neutral.

### Changelog category (leave one):
- Not for changelog

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Update check-large-objects.sh to be language neutral

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by wudanzy** [comment]
Seems like I need to ask for approval if I am asked to sign a CLA, according to my Company's policy. I need to figure that out.

**Review by alexey-milovidov — APPROVED** [review]

**Comment by robot-clickhouse** [comment]
*This is an automated comment for commit fc9efeddf77dc76981ccbad263566911994d33a2 with description of existing statuses. It's updated for the latest CI running*

[❌ Click here](https://s3.amazonaws.com/clickhouse-test-reports/61130/fc9efeddf77dc76981ccbad263566911994d33a2/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>❌ failure</td></tr>
<tbody>
</table>

**Comment by wudanzy** [comment]
I see there are two checks failed, because I need 'can be tested' label. But since this PR is very small, I think it would be fine to skip those tests.

**Comment by wudanzy** [comment]
I see that two fuzzy test failed, is there a guideline for debugging fuzzy test? How can we know which query caused the error?

Logical error: 'Unexpected return type from equals. Expected Nullable. Got UInt8'.

**Comment by wudanzy** [comment]
Seems like the detailed error is here:

Error on processing query 'SELECT s FROM buffer_table1__fuzz_25 PREWHERE x = materialize(1)': Received from localhost:9000. DB::Exception: Illegal types of arguments (Array(Nullable(Float64)), UInt8) of function equals: While processing x = materialize(1). Stack trace:

0. /build/contrib/llvm-project/libcxx/include/exception:141: std::exception::capture() @ 0x000000000aa1f582
1. /build/contrib/llvm-project/libcxx/include/exception:116: std::exception::exception[abi:v15000]() @ 0x000000000aa1f54d
2. /build/base/poco/Foundation/src/Exception.cpp:27: Poco::Exception::Exception(String const&, int) @ 0x00000000233b6c60
3. /build/src/Common/Exception.cpp:94: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x0000000013687dce
4. /build/src/Common/Exception.h:90: DB::Exception::Exception(String&&, int, bool) @ 0x000000000aa1450a
5. /build/src/Common/Exception.h:109: DB::Exception::Exception<String, String, String>(int, FormatStringHelperImpl<std::type_identity<String>::type, std::type_identity<String>::type, std::type_identity<String>::type>, String&&, String&&, String&&) @ 0x000000000ab4ad88
6. /build/src/Functions/FunctionsComparison.h:1186: DB::FunctionComparison<DB::EqualsOp, DB::NameEquals>::getReturnTypeImpl(std::vector<std::shared_ptr<DB::IDataType const>, std::allocator<std::shared_ptr<DB::IDataType const>>> const&) const @ 0x000000000d8297b7
7. /build/src/Functions/IFunction.h:524: DB::IFunction::getReturnTypeImpl(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&) const @ 0x000000000aa18a8c
8. /build/src/Functions/IFunctionAdaptors.h:134: DB::FunctionToOverloadResolverAdaptor::getReturnTypeImpl(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&) const @ 0x000000000aa119f0
9. /build/src/Functions/IFunction.cpp:489: DB::IFunctionOverloadResolver::getReturnTypeWithoutLowCardinality(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&) const @ 0x00000000193f1707
10. /build/src/Functions/IFunction.cpp:435: DB::IFunctionOverloadResolver::getReturnType(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&) const @ 0x00000000193f1156
11. /build/src/Functions/IFunction.cpp:450: DB::IFunctionOverloadResolver::build(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&) const @ 0x00000000193f1761
12. /build/src/Interpreters/ActionsDAG.cpp:243: DB::ActionsDAG::addFunction(std::shared_ptr<DB::IFunctionOverloadResolver> const&, std::vector<DB::ActionsDAG::Node const*, std::allocator<DB::ActionsDAG::Node const*>>, String) @ 0x000000001ad008ff
13. /build/src/Interpreters/ActionsVisitor.cpp:644: DB::ScopeStack::addFunction(std::shared_ptr<DB::IFunctionOverloadResolver> const&, std::vector<String, std::allocator<String>> const&, String) @ 0x000000001afd44e7
14. /build/src/Interpreters/ActionsVisitor.h:181: DB::ActionsMatcher::Data::addFunction(std::shared_ptr<DB::IFunctionOverloadResolver> const&, std::vector<String, std::allocator<String>> const&, String) @ 0x000000001afe0ce1
15. /build/src/Interpreters/ActionsVisitor.cpp:1318: DB::ActionsMatcher::visit(DB::ASTFunction const&, std::shared_ptr<DB::IAST> const&, DB::ActionsMatcher::Data&) @ 0x000000001afd9ccf
16. /build/src/Interpreters/ActionsVisitor.cpp:703: DB::ActionsMatcher::visit(std::shared_ptr<DB::IAST> const&, DB::ActionsMatcher::Data&) @ 0x000000001afd49b7
17. /build/src/Interpreters/InDepthNodeVisitor.h:71: DB::InDepthNodeVisitor<DB::ActionsMatcher, true, false, std::shared_ptr<DB::IAST> const>::doVisit(std::shared_ptr<DB::IAST> const&) @ 0x000000001afcaca0
18. /build/src/Interpreters/InDepthNodeVisitor.h:61: void DB::InDepthNodeVisitor<DB::ActionsMatcher, true, false, std::shared_ptr<DB::IAST> const>::visitImplMain<false>(std::shared_ptr<DB::IAST> const&) @ 0x000000001afcae81                                19. /build/src/Interpreters/InDepthNodeVisitor.h:53: void DB::InDepthNodeVisitor<DB::ActionsMatcher, true, false, std::shared_ptr<DB::IAST> const>::visitImpl<false>(std::shared_ptr<DB::IAST> const&) @ 0x000000001afcac2a
20. /build/src/Interpreters/InDepthNodeVisitor.h:33: DB::InDepthNodeVisitor<DB::ActionsMatcher, true, false, std::shared_ptr<DB::IAST> const>::visit(std::shared_ptr<DB::IAST> const&) @ 0x000000001afa9285                                                    21. /build/src/Interpreters/ExpressionAnalyzer.cpp:484: DB::ExpressionAnalyzer::getRootActions(std::shared_ptr<DB::IAST> const&, bool, std::shared_ptr<DB::ActionsDAG>&, bool) @ 0x000000001af95c5d                                                            22. /build/src/Interpreters/ExpressionAnalyzer.cpp:1181: DB::SelectQueryExpressionAnalyzer::appendPrewhere(DB::ExpressionActionsChain&, bool) @ 0x000000001af9c957
23. /build/src/Interpreters/ExpressionAnalyzer.cpp:1917: DB::ExpressionAnalysisResult::ExpressionAnalysisResult(DB::SelectQueryExpressionAnalyzer&, std::shared_ptr<DB::StorageInMemoryMetadata const> const&, bool, bool, bool, std::shared_ptr<DB::FilterDAGInfo> const&, std::shared_ptr<DB::FilterDAGInfo> const&, DB::Block const&) @ 0x000000001afa2db4                                                                                                                                                                 24. /build/src/Interpreters/InterpreterSelectQuery.cpp:1040: DB::InterpreterSelectQuery::getSampleBlockImpl() @ 0x000000001bf39b24
25. /build/src/Interpreters/InterpreterSelectQuery.cpp:780: DB::InterpreterSelectQuery::InterpreterSelectQuery(std::shared_ptr<DB::IAST> const&, std::shared_ptr<DB::Context> const&, std::optional<DB::Pipe>, std::shared_ptr<DB::IStorage> const&, DB::SelectQueryOptions const&, std::vector<String, std::allocator<String>> const&, std::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::shared_ptr<DB::PreparedSets>)::$_0::operator()(bool) const @ 0x000000001bf2fbbe
26. /build/src/Interpreters/InterpreterSelectQuery.cpp:790: DB::InterpreterSelectQuery::InterpreterSelectQuery(std::shared_ptr<DB::IAST> const&, std::shared_ptr<DB::Context> const&, std::optional<DB::Pipe>, std::shared_ptr<DB::IStorage> const&, DB::SelectQueryOptions const&, std::vector<String, std::allocator<String>> const&, std::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::shared_ptr<DB::PreparedSets>) @ 0x000000001bf2ae3b
27. /build/src/Interpreters/InterpreterSelectQuery.cpp:212: DB::InterpreterSelectQuery::InterpreterSelectQuery(std::shared_ptr<DB::IAST> const&, std::shared_ptr<DB::Context> const&, DB::SelectQueryOptions const&, std::vector<String, std::allocator<String>> const&) @ 0x000000001bf266c6
28. /build/contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:714: std::__unique_if<DB::InterpreterSelectQuery>::__unique_single std::make_unique[abi:v15000]<DB::InterpreterSelectQuery, std::shared_ptr<DB::IAST> const&, std::shared_ptr<DB::Context>&, DB::SelectQueryOptions&, std::vector<String, std::allocator<String>> const&>(std::shared_ptr<DB::IAST> const&, std::shared_ptr<DB::Context>&, DB::SelectQueryOptions&, std::vector<String, std::allocator<String>> const&) @ 0x000000001c0ccdc1             29. /build/src/Interpreters/InterpreterSelectWithUnionQuery.cpp:255: DB::InterpreterSelectWithUnionQuery::buildCurrentChildInterpreter(std::shared_ptr<DB::IAST> const&, std::vector<String, std::allocator<String>> const&) @ 0x000000001c0ca129
30. /build/src/Interpreters/InterpreterSelectWithUnionQuery.cpp:153: DB::InterpreterSelectWithUnionQuery::InterpreterSelectWithUnionQuery(std::shared_ptr<DB::IAST> const&, std::shared_ptr<DB::Context>, DB::SelectQueryOptions const&, std::vector<String, std::allocator<String>> const&) @ 0x000000001c0c95a5                                                                                                                                                                                                             31. /build/contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:714: std::__unique_if<DB::InterpreterSelectWithUnionQuery>::__unique_single std::make_unique[abi:v15000]<DB::InterpreterSelectWithUnionQuery, std::shared_ptr<DB::IAST>&, std::shared_ptr<DB::Context> const&, DB::SelectQueryOptions const&>(std::shared_ptr<DB::IAST>&, std::shared_ptr<DB::Context> const&, DB::SelectQueryOptions const&) @ 0x000000001c0d0d54
Fuzzing step 505 out of 1000

SELECT s
FROM buffer_table1__fuzz_2
PREWHERE x = materialize(1)

**Comment by wudanzy** [comment]
I can't reproduce the bug by the following:

```
CREATE TABLE merge_tree_table1 (`s` LowCardinality(String), x UInt32) ENGINE = MergeTree ORDER BY x settings index_granularity = 1;
CREATE TABLE buffer_table1 ( `s` String , x UInt32) ENGINE = Buffer(currentDatabase(), 'merge_tree_table1', 16, 10, 60, 10, 1000, 1048576, 2097152);
insert into merge_tree_table1 values ('a', 1);
SELECT s FROM buffer_table1 PREWHERE x = materialize(1);
```
Hi Alexey, any insights?

**Comment by wudanzy** [comment]
Hello, shall we merge this by hand? This PR is very trivial.

**Pull request merged**
