### PR TITLE
Function for generate an uuid v4

### PR DESCRIPTION
**Pull request by YiuRULE**
Propose a function implementation for create an UUID V4 on server side.

The name of the function is `generateUUIDV4`, doesn't take any argument and his return type is an UUID.

Some example case :
`SELECT generateUUIDV4` => `f4a8d299-3032-40dc-a19c-ceaf6d2fb336`

The purpose of this function is to use mostly as a default value.

```
CREATE TABLE test IF NOT EXIST (
    uuid UUID DEFAULT generateUUIDV4(),
    data String
) Engine = Memory;

INSERT INTO test (data) VALUES('test1');
INSERT INTO test (data) VALUES('test2');
INSERT INTO test (data) VALUES('test3');
INSERT INTO test (data) VALUES('test4');
INSERT INTO test (data) VALUES('test5');
INSERT INTO test (data) VALUES('test6');
```

`SELECT data, uuid FROM test;`

```
test1, 368693a3-deea-42da-9de9-21782cc8d1c6
test2, 9eb2f472-6f63-4d1f-ab0b-0e4bfdf7b515
test3, 2dab3f49-5716-48e5-94b4-8fa5fb6d141c
test4, e1ae40e7-0258-4337-a4e2-eae69a05666b
test5, e8306243-eefd-407c-a92b-10165028dddc
test6, d7b78961-14ce-4cf4-9b72-5fd54fec246d 
```

The implementation of UUID follow the [RFC 4122](https://tools.ietf.org/html/rfc4122#section-4.4)

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

### CODE REVIEW

**Comment by robot-metrika-test** [comment]
Can one of the admins verify this patch?

**Comment by robot-metrika-test** [comment]
Can one of the admins verify this patch?

**Comment by alexey-milovidov** [comment]
Mostly Ok.

1. I prefer the function to be named with lowercase `v`: `generateUUIDv4`.
Because in similar abbreviations, `v` is also traditionally in lowercase. Examples: `IPv4`, `IPv6`.

2. Method `RandImpl::execute` now assumes, that sizeof(T) divide sizeof(ReturnType). This looks unnatural. We could do better. For example, `RandImpl::execute` should take `ReturnType * output, size_t output_size` parameters... and no template required. And also you could extract this method and implement both `RandImpl` and `Rand64Impl` on top of it, to avoid code duplication.

**Comment by alexey-milovidov** [comment]
PS. Also you could use name `generateRandomUUID` instead of `generateUUIDv4`. This will clearly state the type of UUID algorithm. This is up to your choice, `generateUUIDv4` is also Ok :)

**Comment by YiuRULE** [comment]
Ok, should be could now. :)

I let the name `generateUUIDv4` because some library who encapsulate UUID V4 use some components of the UUID V4 algorithm (for determine the version). Name it `generateRandomUUID` can be a little ambiguous because we can think than every bits of the UUID are random, who it's not totally the case on UUID V4. :)

**Comment by alexey-milovidov** [comment]
Ok, thanks!

**Pull request merged**
