### PR TITLE
Add a test for a bug in Apache Arrow

### PR DESCRIPTION
**Pull request by alexey-milovidov**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Merging #51309.

### CODE REVIEW

**Comment by robot-ch-test-poll2** [comment]
This is an automated comment for commit 7561a4a1061338bc28676fbc8c22ac5b995b9365 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/52797/7561a4a1061338bc28676fbc8c22ac5b995b9365/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Comment by Avogar** [comment]
I totally forgot about it, my fault...
Will check today/tomorrow

**Comment by alexey-milovidov** [comment]
At least the test passed.
The flaky check is also ok, because this query can be slow with thread fuzzer.

**Comment by alexey-milovidov** [comment]
Waiting for @KochetovNicolai to fix "Pipeline stuck".

**Comment by alexey-milovidov** [comment]
@Avogar, the tests still aborts in the debug build.

**Comment by alexey-milovidov** [comment]
Apache Arrow still has a bug.

**Comment by alexey-milovidov** [comment]
@Avogar, There is still a bug in Apache Arrow.

**Comment by Avogar** [comment]
https://github.com/ClickHouse/ClickHouse/pull/61720

**Comment by Avogar** [comment]
Fixed and added this test in https://github.com/ClickHouse/ClickHouse/pull/61720

**Pull request closed without merging**
