### PR TITLE
Check for large translation units

### PR DESCRIPTION
**Pull request by alexey-milovidov**
### Changelog category (leave one):
- Build/Testing/Packaging Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Add automatic check that there are no large translation units.

### CODE REVIEW

**Comment by robot-clickhouse** [comment]
*This is an automated comment for commit 96f73139b63d38a92e9e35db49b1c0158a1f164f with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/56559/96f73139b63d38a92e9e35db49b1c0158a1f164f/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td><a href="https://github.com/ClickHouse/ClickHouse/actions/runs/6821035028">✅ success</a></td></tr>
<tbody>
</table>
</details>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/56559/96f73139b63d38a92e9e35db49b1c0158a1f164f/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Comment by alexey-milovidov** [comment]
`master` will not pass this test:
```
$ find . -name '*.o' | xargs wc -c | grep -v total | sort -rn | awk '{ if ($1 > 50000000) print }'
 125689544 ./src/CMakeFiles/dbms.dir/Functions/CastOverloadResolver.cpp.o
 100549336 ./src/CMakeFiles/dbms.dir/Interpreters/ActionsDAG.cpp.o
  98302640 ./src/CMakeFiles/dbms.dir/Storages/MergeTree/KeyCondition.cpp.o
  95536880 ./src/AggregateFunctions/CMakeFiles/clickhouse_aggregate_functions.dir/AggregateFunctionSumMap.cpp.o
  94321616 ./src/CMakeFiles/dbms.dir/Storages/MergeTree/MergeTreeSplitPrewhereIntoReadSteps.cpp.o
  93257952 ./src/CMakeFiles/dbms.dir/Interpreters/castColumn.cpp.o
  85277984 ./src/AggregateFunctions/CMakeFiles/clickhouse_aggregate_functions.dir/AggregateFunctionMax.cpp.o
  85232088 ./src/AggregateFunctions/CMakeFiles/clickhouse_aggregate_functions.dir/AggregateFunctionMin.cpp.o
  82691448 ./src/Dictionaries/CMakeFiles/clickhouse_dictionaries.dir/RangeHashedDictionaryComplex.cpp.o
  73833704 ./src/CMakeFiles/dbms.dir/Interpreters/Aggregator.cpp.o
  66955752 ./src/Dictionaries/CMakeFiles/clickhouse_dictionaries.dir/RangeHashedDictionarySimple.cpp.o
  60911880 ./src/AggregateFunctions/CMakeFiles/clickhouse_aggregate_functions.dir/AggregateFunctionUniqCombined.cpp.o
  59093976 ./src/AggregateFunctions/CMakeFiles/clickhouse_aggregate_functions.dir/AggregateFunctionAvgWeighted.cpp.o
  55090640 ./src/AggregateFunctions/CMakeFiles/clickhouse_aggregate_functions.dir/AggregateFunctionUniq.cpp.o
```

But after my changes in https://github.com/ClickHouse/ClickHouse/pull/56350 it will pass:

```
$ find . -name '*.o' | xargs wc -c | grep -v total | sort -rn | awk '{ if ($1 > 50000000) print }'
 125689544 ./src/CMakeFiles/dbms.dir/Functions/CastOverloadResolver.cpp.o
  85277984 ./src/AggregateFunctions/CMakeFiles/clickhouse_aggregate_functions.dir/AggregateFunctionMax.cpp.o
  85232088 ./src/AggregateFunctions/CMakeFiles/clickhouse_aggregate_functions.dir/AggregateFunctionMin.cpp.o
  82541592 ./src/Dictionaries/CMakeFiles/clickhouse_dictionaries.dir/RangeHashedDictionaryComplex.cpp.o
  73833704 ./src/CMakeFiles/dbms.dir/Interpreters/Aggregator.cpp.o
  66799920 ./src/Dictionaries/CMakeFiles/clickhouse_dictionaries.dir/RangeHashedDictionarySimple.cpp.o
  55090640 ./src/AggregateFunctions/CMakeFiles/clickhouse_aggregate_functions.dir/AggregateFunctionUniq.cpp.o
  52814272 ./src/AggregateFunctions/CMakeFiles/clickhouse_aggregate_functions.dir/AggregateFunctionUniqCombined.cpp.o
```

**Review by Algunenano — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
Strange - it passed. Probably we have a wrong option set in CMakeLists.

**Comment by alexey-milovidov** [comment]
Now it works!

**Pull request merged**
