### PR TITLE
Fix create materialized view with MaterializedPostgreSQL

### LINKED ISSUE #38671: Replication from PostgreSQL to CL with MaterializedPostgreSQL database engine stopped after materialized view created
When create materialized view on ClickHouse table in materialized PostgreSQL database, replication process not update or insert data into this table. After remove MV, replication resumes, but data losses. 

ClickHouse version: 22.6.1.1399
Postgres version: PostgreSQL 12.11 (Ubuntu 12.11-0ubuntu0.20.04.1)

**Postgres:**

```
CREATE TABLE test.test_table (
	id int4 NOT NULL,
	val int4 NOT NULL,
	CONSTRAINT tt_pk PRIMARY KEY (id)
);
INSERT INTO test.test_table
(id, val)
VALUES(1, 1);

INSERT INTO test.test_table
(id, val)
VALUES(2, 2);

SELECT * FROM test.test_table;

id|val|
--+---+
 1|  1|
 2|  2|

```

**ClickHouse:**

```
CREATE DATABASE mpsql_test 
ENGINE = MaterializedPostgreSQL
 ( 
   'localhost:5432', 'test_db', 'postgres', 'postgres'
 )
 SETTINGS
   materialized_postgresql_schema = 'test',
   materialized_postgresql_tables_list = 'test_table';

SHOW TABLES FROM mpsql_test;

name      |
----------+
test_table|

SELECT * FROM mpsql_test.test_table;

id|val|
--+---+
 1|  1|
 2|  2|

```
**Postgres:**

```
INSERT INTO test.test_table
(id, val)
VALUES(3, 3);

SELECT * FROM test.test_table;

id|val|
--+---+
 1|  1|
 2|  2|
 3|  3|

```
**ClickHouse:**

```
SELECT * FROM mpsql_test.test_table;

id|val|
--+---+
 1|  1|
 2|  2|
 3|  3|

CREATE DATABASE test_db;

CREATE MATERIALIZED VIEW test_db.test_view
ENGINE = MergeTree()
ORDER BY (id)
AS SELECT * from mpsql_test.test_table;

SELECT * FROM test_db.test_view;
id|val|
--+---+


```
**Postgres:**

```
INSERT INTO test.test_table
(id, val)
VALUES(4, 4);

INSERT INTO test.test_table
(id, val)
VALUES(5, 5);

SELECT * FROM test.test_table;
id|val|
--+---+
 1|  1|
 2|  2|
 3|  3|
 4|  4|
 5|  5|

```
**ClickHouse:**

```
SELECT * FROM mpsql_test.test_table;
id|val|
--+---+
 1|  1|
 2|  2|
 3|  3|

DROP VIEW test_db.test_view;

SELECT * FROM mpsql_test.test_table;
id|val|
--+---+
 1|  1|
 2|  2|
 3|  3|

```
**Postgres:**

```
INSERT INTO test.test_table
(id, val)
VALUES(6, 6);

INSERT INTO test.test_table
(id, val)
VALUES(7, 7);

SELECT * FROM test.test_table;
id|val|
--+---+
 1|  1|
 2|  2|
 3|  3|
 4|  4|
 5|  5|
 6|  6|
 7|  7|

```
**ClickHouse:**

```
SELECT * FROM mpsql_test.test_table;

id|val|
--+---+
 1|  1|
 2|  2|
 3|  3|
 6|  6|
 7|  7|

```

### PR DESCRIPTION
**Pull request by maksim-buren**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in official stable or prestable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix usage of materialized view with MaterializedPostgreSQL replication (an experimental feature). Closes #38671

### CODE REVIEW

**Comment by tavplubix** [comment]
Thanks for your contribution! Unfortunately, many tests for MaterializedPostgreSQL are currently disabled (see https://github.com/ClickHouse/ClickHouse/issues/38677, https://github.com/ClickHouse/ClickHouse/issues/36898). We cannot merge changes affecting fragile code without tests, so we have to wait for tests to be enabled back. I'll convert this PR to draft for now and we will merge it later when other issues are addressed.

**Comment by VargasM** [comment]
Hey!. Is any update on this PR? I'm having this problem. What other strategy can we use when we have this issue?

**Comment by alexsis71** [comment]
Hello! Fix don't push into main branch. Some trouble with tests, more than half year.
I've to use postgres fdw to clickhouse for inserts and CH drivers to Pg for reads.
Also, I've to use PG Timescale DB jobs feature for monitoring changes in temp table with updates. Inserts and updates has status field and pushed into CH versioning mergetree table.
________________________________
От: JimenaV ***@***.***>
Отправлено: вторник, 31 января 2023 г., 02:02
Кому: ClickHouse/ClickHouse ***@***.***>
Копия: alexsis71 ***@***.***>; Manual ***@***.***>
Тема: Re: [ClickHouse/ClickHouse] Fix create materialized view with MaterializedPostgreSQL (PR #40807)


Hey!. Is any update on this PR? I'm having this problem. What other strategy can we use when we have this issue?

**Comment by kssenii** [comment]
> Please note that some tests are still disabled:
https://github.com/ClickHouse/ClickHouse/blob/master/tests/integration/test_storage_postgresql_replica/test.py#L3-L8

Ok, Indeed I missed this suit of tests when fixing them, but I think two other suits of tests which are now fixed is enough to merge this PR.

**Comment by kssenii** [comment]
> Integration tests flaky check (asan) — No flaky tests: error: 0, passed: 8

and all other integration tests finished and passed

**Review by kssenii — APPROVED** [review]

**Pull request merged**
