### PR TITLE
Documentation correction for units for block size, plus some additional context for storage system recommendations

### PR DESCRIPTION
**Pull request by thomoco**
Changelog category (leave one):
- Documentation (changelog entry is not required)

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Documentation correction for units for block size, plus some additional context for storage system recommendations

Detailed description / Documentation draft:
A block size of 1024 bytes (1KB) is sufficient for most RAID configurations. A block size range of 1KB to 16KB is common across many storage system vendors or DBMS.

> By adding documentation, you'll allow users to try your new feature immediately, not when someone else will have time to document it later. Documentation is necessary for all features that affect user experience in any way. You can add brief documentation draft above, or add documentation right into your patch as Markdown files in [docs](https://github.com/ClickHouse/ClickHouse/tree/master/docs) folder.

> If you are doing this for the first time, it's recommended to read the lightweight [Contributing to ClickHouse Documentation](https://github.com/ClickHouse/ClickHouse/tree/master/docs/README.md) guide first.

> Information about CI checks: https://clickhouse.tech/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
It's not a mistake. We run production servers with 1024K chunk.

```
$ cat /proc/mdstat
Personalities : [linear] [multipath] [raid0] [raid1] [raid6] [raid5] [raid4] [raid10] 
md2 : active raid6 sdg3[6] sdf3[5] sde3[4] sdh3[7] sdd3[3] sdc3[2] sdb3[1] sda3[0]
      93653729280 blocks super 1.2 level 6, 1024k chunk, algorithm 2 [8/8] [UUUUUUUU]
      
md1 : active raid10 sdg2[6] sdf2[5] sdh2[7] sdd2[3] sde2[4] sdc2[2] sdb2[1] sda2[0]
      62881792 blocks super 1.2 512K chunks 2 far-copies [8/8] [UUUUUUUU]
```

Everything works as expected (e.g. sequential read speed is 8 times the speed of one disk).

Maybe lower chunk size actually can be better to improve parallelism of small sequential reads.

Although I don't remember any drawbacks of smaller chunk size.
Maybe CPU usage on writes will increase due to higher bookkeeping in stripe cache.

**Comment by alexey-milovidov** [comment]
1 KB would be definitely wrong as large disks has 4K sector size.

**Comment by thomoco** [comment]
Are you sure the chunk size is not referring to the RAID stripe size? This I think is different than the block size. What is the average file size in a ClickHouse datastore?

**Comment by alexey-milovidov** [comment]
Large chunk size does not lead to wasted space.

RAID is implemented on block device level (a `md` block device on top of other block devices, like `sda1, sda2...`).
Filesystem is implemented on top of the block device.

RAID is unaware of a filesystem (and can work without any filesystem at all) and filesystem is unaware of RAID
(with the exception of ZFS that has it's own integrated RAID).

So, every file can span multiple chunks or one chunk can contain data for multiple files.

`$ sudo find /var/lib/clickhouse/data -type f | xargs -L1000 sudo wc -c | awk '{ print $1 }' | clickhouse-local --structure 'size UInt64' --query 'SELECT avg(size) FROM table'`

The average file size is 73 MB.

**Comment by alexey-milovidov** [comment]
After discussion, we have agreed that large chunk size is bad for small writes (like random writes).
As we are doing writes with mostly 1MiB size, the default 64K should be better (as the full stripe size will be chunk size * number of disks).

**Comment by den-crane** [comment]
BTW, I use `mdadm --create /dev/md0 --level=10 --layout=f2 --chunk=1M --bitmap=internal --bitmap-chunk=128M ...`
Do we have some benchmark which I can use to test ingestion performance with different chunk sizes ?

**Comment by alexey-milovidov** [comment]
> Do we have some benchmark which I can use to test ingestion performance with different chunk sizes ?

No, we don't. Our continuous integration perf testing only covers reads.
Recreating RAID will be cumbersome... So, what we have is to just choose some reasonable value.

**Review by alexey-milovidov — APPROVED** [review]

**Pull request merged**
