### PR TITLE
Format and cleanup imports form all *.py integration test files

### PR DESCRIPTION
**Pull request by bharatnc**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Build/Testing/Packaging Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Reformat and cleanup code in all integration test *.py files.

Detailed description / Documentation draft:

.This PR formats all the `*.py` files found under the `tests/integration`
folder. It also reorders the imports and cleans up a bunch of unused
imports.

The formatting also takes care of other things like wrapping lines and
fixing spaces and indents such that the tests look more readable.

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
Ok. BTW, what tool did you use to do it?

**Review by alexey-milovidov — APPROVED** [review]

**Comment by bharatnc** [comment]
Just relied on CLion: 

image

Takes care of standard python formatting adhering to pep8 standards.

**Comment by alexey-milovidov** [comment]
Ok. (BTW, I'm not a Python developer) We can find some linter/formatter that we can apply automatically.
PS. Also there is a need to convert everything to Python 3.

**Comment by bharatnc** [comment]
> Ok. (BTW, I'm not a Python developer) We can find some linter/formatter that we can apply automatically.
> PS. Also there is a need to convert everything to Python 3.

Do we have a ticket tracking the work for this? I can probably take a stab at Python 2 -> 3 and also perhaps a linter that checks the formatting.

**Comment by alexey-milovidov** [comment]
Not yet. Just created: https://github.com/ClickHouse/ClickHouse/issues/14886

**Pull request merged**
