### PR TITLE
Maybe not GWPAsan by default

### PR DESCRIPTION
**Pull request by antonio2368**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

It can have a major impact on realloc.
It still can be useful IMO but as an opt-in feature.

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Run only fuzzers related jobs (libFuzzer fuzzers, AST fuzzers, etc.)
- [ ]  Exclude: AST fuzzers
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-ch-test-poll** [comment]
*This is an automated comment for commit cb4eedec061fe9edba9352b80db0d632f1b5323e with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/71174/cb4eedec061fe9edba9352b80db0d632f1b5323e/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/f2b67b78615f6fd393980b25cda30ac81f231a27/docs_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Comment by alexey-milovidov** [comment]
What was the impact?

PS. I'm a proponent of having GWP-ASan by default, but if it is not possible, ok to disable it.

**Comment by antonio2368** [comment]
> What was the impact?

If GWPAsan samples allocation that is getting reallocated, it degrades to alloc -> memcpy -> free which can be too much if we are extending huge allocations.
E.g. it caused major slowdown for dictionary loading.

Maybe if we solve that issue we can enable it back again but I'm not confident anymore until we take a closer look.

**Review by CheSema — APPROVED** [review]

**Comment by CheSema** [comment]
I suggest to try the following solution with realloc. 
if memory does not belong to GWP, then do not switch allocator on realloc. Then the decision about which allocator should be used for the object would be made on the first allocation.
And may be do not even try to allocate big area with GWP, because reallocation would be expensive.
All that are just ideas how to overcome the issue in general, it is not applicable to this PR.

**Pull request merged**
