### PR TITLE
Fix flakiness of async insert tests due to adaptive timeout

### LINKED ISSUE #47866: Functional tests for async inserts are flaky
02015_async_inserts_5 - https://s3.amazonaws.com/clickhouse-test-reports/0/5add1e1b2e9439abe7fe2ed0052ef91cf9c2ad54/stateless_tests__tsan__[3/3].html
02015_async_inserts_1 - https://s3.amazonaws.com/clickhouse-test-reports/0/00c05f7f8b8f11bcb9c11e54c9bec6b77932933f/stateless_tests__tsan__[3/3].html
02481_async_insert_race_long - https://s3.amazonaws.com/clickhouse-test-reports/47770/1073c7f3c942949d1f5de6956fab9b3bcde8b34b/stateless_tests__debug__s3_storage__[6/6].html
02187_async_inserts_all_formats - https://s3.amazonaws.com/clickhouse-test-reports/46085/886b5309632eb2b2d9b2d5122b1a492bbdf82e09/stateless_tests__tsan__[2/5].html 

See CI DB: [link](https://play.clickhouse.com/play?user=play#d2l0aCAKJzAlYXN5bmNfaW5zZXJ0JScgYXMgbmFtZV9wYXR0ZXJuLAonJSUnIGFzIGNvbnRleHRfcGF0dGVybiwKJzIwMjItMTItMDEnIGFzIHN0YXJ0X2RhdGUsCig0NTQ2MSkgYXMgbm9pc3lfcHJzLAooJ1N0YXRlbGVzcyB0ZXN0cyAoYXNhbiknLCAnU3RhdGVsZXNzIHRlc3RzIChhZGRyZXNzKScsICdTdGF0ZWxlc3MgdGVzdHMgKGFkZHJlc3MsIGFjdGlvbnMpJykgYXMgYmFja3BvcnRfYW5kX3JlbGVhc2Vfc3BlY2lmaWNfY2hlY2tzCnNlbGVjdCAKdG9TdGFydE9mRGF5KGNoZWNrX3N0YXJ0X3RpbWUpIGFzIGQsCmNvdW50KCksICBncm91cFVuaXFBcnJheShwdWxsX3JlcXVlc3RfbnVtYmVyKSwgZ3JvdXBVbmlxQXJyYXkodGVzdF9uYW1lKSwgYW55KHJlcG9ydF91cmwpCmZyb20gY2hlY2tzIHdoZXJlIHN0YXJ0X2RhdGUgPD0gY2hlY2tfc3RhcnRfdGltZSBhbmQgcHVsbF9yZXF1ZXN0X251bWJlciBub3QgaW4gCihzZWxlY3QgcHVsbF9yZXF1ZXN0X251bWJlciBhcyBwcm4gZnJvbSBjaGVja3Mgd2hlcmUgcHJuIT0wIGFuZCBzdGFydF9kYXRlIDw9IGNoZWNrX3N0YXJ0X3RpbWUgYW5kIGNoZWNrX25hbWUgaW4gYmFja3BvcnRfYW5kX3JlbGVhc2Vfc3BlY2lmaWNfY2hlY2tzKSAKYW5kIHRlc3RfbmFtZSBsaWtlIG5hbWVfcGF0dGVybiBhbmQgdGVzdF9jb250ZXh0X3JhdyBpbGlrZSBjb250ZXh0X3BhdHRlcm4gYW5kIHRlc3RfY29udGV4dF9yYXcgbm90IGxpa2UgJyVDYW5ub3RTZW5kUmVxdWVzdCUnCmFuZCBwdWxsX3JlcXVlc3RfbnVtYmVyIG5vdCBpbiBub2lzeV9wcnMKYW5kIHRlc3Rfc3RhdHVzIGluICgnRkFJTCcsICdGTEFLWScsICdmYWlsdXJlJykgZ3JvdXAgYnkgZCBvcmRlciBieSBkIGRlc2M=)

### PR DESCRIPTION
**Pull request by Algunenano**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix flakiness of async insert tests due to adaptive timeout

The problem is that when adaptive timeouts are active (by default) the first insert might be immediate if the queue had been used before and has been unused for more than `async_insert_busy_timeout_max_ms` (which is possible). Disabling adaptive timeouts disables this immediate push.

Closes https://github.com/ClickHouse/ClickHouse/issues/47866 (we can open different tickets for other issues, as most of the reports are now old or incorrect)

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-ch-test-poll4** [comment]
*This is an automated comment for commit e91c4b2e057323fc2eba16317dbcb210eedd0cab with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/66771/e91c4b2e057323fc2eba16317dbcb210eedd0cab/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Builds</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/52b03eb776423a1d2ee847051ab0d9433e383540/builds/report.html">✅ success</a></td></tr>
<tr><td>ClickBench</td><td>Runs [ClickBench](https://github.com/ClickHouse/ClickBench/) with instant-attach table</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/52b03eb776423a1d2ee847051ab0d9433e383540/clickbench__aarch64_.html">✅ success</a></td></tr>
<tr><td>Compatibility check</td><td>Checks that <b>clickhouse</b> binary runs on distributions with old libc versions. If it fails, ask a maintainer for help</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/52b03eb776423a1d2ee847051ab0d9433e383540/compatibility_check__aarch64_.html">✅ success</a></td></tr>
<tr><td>Docker keeper image</td><td>The check to build and optionally push the mentioned image to docker hub</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/52b03eb776423a1d2ee847051ab0d9433e383540/docker_keeper_image.html">✅ success</a></td></tr>
<tr><td>Docker server image</td><td>The check to build and optionally push the mentioned image to docker hub</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/52b03eb776423a1d2ee847051ab0d9433e383540/docker_server_image.html">✅ success</a></td></tr>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/b1b5123a6ab1262bab2c9849a1233e38189f686b/docs_check.html">✅ success</a></td></tr>
<tr><td>Install packages</td><td>Checks that the built packages are installable in a clear environment</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/52b03eb776423a1d2ee847051ab0d9433e383540/install_packages__aarch64_.html">✅ success</a></td></tr>
<tr><td>Integration tests</td><td>The integration tests report. In parenthesis the package type is given, and in square brackets are the optional part/total tests</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/52b03eb776423a1d2ee847051ab0d9433e383540/integration_tests__aarch64__[1_6].html">✅ success</a></td></tr>
<tr><td>Stateful tests</td><td>Runs stateful functional tests for ClickHouse binaries built in various configurations -- release, debug, with sanitizers, etc</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/52b03eb776423a1d2ee847051ab0d9433e383540/stateful_tests__aarch64_.html">✅ success</a></td></tr>
<tr><td>Unit tests</td><td>Runs the unit tests for different release types</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/52b03eb776423a1d2ee847051ab0d9433e383540/unit_tests__asan_.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Review by nikitamikhaylov — APPROVED** [review]

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
It's strange to see "tests are not finished". I see no fatal errors in the log, and no failed tests.
I checked the script, `process_functions_tests_result.py`, and it happens when there is no `All tests have finished` message in the log. There is, indeed, no such message. Let's check further...

**Comment by alexey-milovidov** [comment]
The message is also explicitly deleted in case of timeout:
`docker/test/stateless/run.sh`:
https://github.com/ClickHouse/ClickHouse/pull/66790

**Comment by alexey-milovidov** [comment]
Exit code 143 means signal 15, "terminate".

**Comment by alexey-milovidov** [comment]
Funny, but we have yet another timeout inside a function:

```
timeout -k 60m -s TERM --preserve-status 140m  clickhouse-test --testname --shard --zookeeper --check-zookeeper-session --hung-check --print-time \
         --no-drop-if-fail --test-runs "$NUM_TRIES" "${ADDITIONAL_OPTIONS[@]}" 2>&1 \
    | ts '%Y-%m-%d %H:%M:%S' \
    | tee -a test_output/test_result.txt
```

Which sends terminate.

**Comment by alexey-milovidov** [comment]
Almost surely, it is https://github.com/ClickHouse/ClickHouse/pull/66783

**Comment by alexey-milovidov** [comment]
@Algunenano Not fixed: https://github.com/ClickHouse/ClickHouse/issues/67298

**Pull request merged**
