### PR TITLE
Change Hash Join's hasher from  CRC32 Hash to Default Hash

### PR DESCRIPTION
**Pull request by Alex-Cheng**
### Changelog category (leave one):
- Performance Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Change the hasher of Hash Join from CRC32 to Default(Murmur hash), because the CRC32's lower 24 bits have many collisions.

### Details
The huge number of collisions occured in HashTable is discovered by a test data from my QA team. 

The test data is here. [hash_map_crc32_conflict_test_data.txt](https://github.com/ClickHouse/ClickHouse/files/11752104/hash_map_crc32_conflict_test_data.txt)

The issue can be reproduced by using it in Join table engine(leverage Hash Join functionality) or using it as `B` in join query `A left join B` with join algorithem being `hash`. 

#### Collision observation
image

#### Performance consideration
The CRC32 Hash is faster than Default Hash. In my test, for 100M times hash computation, the performance is:
- CRC32 costs 0.4s
- Default Hash costs 1.4s

However, considering far lesser collisions, we should choose the Default Hash, as insertion my test data into a HashTable with CRC32 hangs almost foreever because of collisions. 

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
What is the dataset?

**Comment by robot-clickhouse-ci-2** [comment]
This is an automated comment for commit 66aa0a11d4409e8214ba3d798971231aa9ffb87c with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/51014/66aa0a11d4409e8214ba3d798971231aa9ffb87c/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Comment by Alex-Cheng** [comment]
> What is the dataset?

You could get the dataset by 
[hash_map_crc32_conflict_test_data.txt](https://github.com/ClickHouse/ClickHouse/files/11767826/hash_map_crc32_conflict_test_data.txt)

**Comment by Alex-Cheng** [comment]
Why do I got "CI running is pending - no special conditions apply“？

**Comment by UnamedRus** [comment]
DefaultHash64 is really bad for certain data types (UUID) https://github.com/ClickHouse/ClickHouse/issues/34425#issuecomment-1039074117

**Comment by Alex-Cheng** [comment]
> DefaultHash64 is really bad for certain data types (UUID) [#34425 (comment)](https://github.com/ClickHouse/ClickHouse/issues/34425#issuecomment-1039074117)

If DefaultHash is bad, and CRC32 hash have similar low 24 bits in my test data(high 8-bits varies), how about doing cycle-shift-left for the bits of CRC32 to produce the places for inserting new data into hashtable?

**Comment by Alex-Cheng** [comment]
Some tests are failed but not related to my changes.

**Comment by Alex-Cheng** [comment]
> DefaultHash64 is really bad for certain data types (UUID) [#34425 (comment)](https://github.com/ClickHouse/ClickHouse/issues/34425#issuecomment-1039074117)

UUID is 128 bit data, and I changed the hash for UInt32 and UInt64, so it won't affect UUID.

**Comment by Alex-Cheng** [comment]
@alexey-milovidov  It is my first time to contribute to CH, so I may be lack of some knowledge. I am wondering that what is the gap of getting the PR merged. Shall I do something else to get the PR qualified enough for merging?

**Comment by alexey-milovidov** [comment]
We have to review it. It is currently not have been reviewed.

**Pull request closed without merging**
