### PR TITLE
Reduce the number of read rows from `system.numbers`

### LINKED ISSUE #59418: numbers(xx) read more rows, than it was before
**Describe the situation**
Just not to forget.
https://github.com/ClickHouse/ClickHouse/pull/50909#issuecomment-1869094989

**How to reproduce**
https://fiddle.clickhouse.com/87861a7b-30c4-45c2-862e-07cdfb63588d
23.11
```
	"rows_before_limit_at_least": 65409,

	"statistics":
	{
		"elapsed": 0.002581122,
		"rows_read": 65409,
		"bytes_read": 523272
	}
```
https://fiddle.clickhouse.com/29e9744f-0726-4f2c-97c7-4a8362eac102

23.10
```
	"rows_before_limit_at_least": 3,

	"statistics":
	{
		"elapsed": 0.002170152,
		"rows_read": 3,
		"bytes_read": 24
	}
```

### PR DESCRIPTION
**Pull request by JackyWoo**
### Changelog category (leave one):

- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Reduce the number of read rows from `system.numbers`. Fixes #59418.

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by robot-ch-test-poll** [comment]
*This is an automated comment for commit 1ad004249481abb7d0b8b523abdc3744ba518320 with description of existing statuses. It's updated for the latest CI running*

[❌ Click here](https://s3.amazonaws.com/clickhouse-test-reports/60546/1ad004249481abb7d0b8b523abdc3744ba518320/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td><a href="https://github.com/ClickHouse/ClickHouse/blob/master/.github/PULL_REQUEST_TEMPLATE.md?plain=1">❌ failure</a></td></tr>
<tbody>
</table>

**Review by antaljanosbenjamin — COMMENTED** [review]
The changes looks reasonable, however I don't understand why the issue happens only with the `WHERE a = '1'` filter. Could you please explain it in a few words?

**Comment by JackyWoo** [comment]
`ReadFromSystemNumbersStep` will choose `source` which will generate numbers. There are 2 `sources` `NumbersSource` and `NumbersRangedSource`. `NumbersRangedSource` has high priority.

`NumbersRangedSource` is based on `KeyCondition`, but `KeyCondition` can not pase expression like `toString(number) = '1'`.  So `NumbersSource` is used.

**Comment by JackyWoo** [comment]
@antaljanosbenjamin maybe the failed test `01603_insert_select_too_many_parts ` is flaky

**Comment by antaljanosbenjamin** [comment]
It seems like the test is flaky. However as it reads from `system.numbers`, let me verify that it didn't get worse.

**Comment by antaljanosbenjamin** [comment]
It looks good. I will have a look at the whole CI and merge the PR if everything adds up.

**Comment by antaljanosbenjamin** [comment]
So there is some small issue regarding syncing the changes to our private fork, give me some time to fix it. This means the PR will be merged today or tomorrow.

**Comment by antaljanosbenjamin** [comment]
Marking "Mergeable check" green manually because the failed tests are not related.

**Review by antaljanosbenjamin — APPROVED** [review]

**Pull request merged**
