### PR TITLE
Upgrade librdkafka to 1.9.2 with some patches

### PR DESCRIPTION
**Pull request by antaljanosbenjamin**
### Changelog category (leave one):
- Build/Testing/Packaging Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Upgrade `librdkafka` to `1.9.2` (with some patches).

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Run only fuzzers related jobs (libFuzzer fuzzers, AST fuzzers, etc.)
- [ ]  Exclude: AST fuzzers
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by antaljanosbenjamin** [comment]
cc @ilejn @rschu1ze

**Comment by robot-ch-test-poll3** [comment]
*This is an automated comment for commit ed771b7aaab0b3ef67d7dc4b484c2aef2f9ff3ca with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/69558/ed771b7aaab0b3ef67d7dc4b484c2aef2f9ff3ca/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/69432/6f9d1631e26bbb0263962c6d50c65e9ee2be561a/docs_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Comment by rschu1ze** [comment]
Looks like it could work. I probably would have
- checked which files in the current librdkafka fork (1.6.1 if I am not mistaken) are patched by which PRs. This is not trivial to know as in the past they repeatedly merged upstream `master` into the fork and older custom patches are still in but not immediately clear. This step could be done by diff-ing the current v1.6.1 in the fork repo against upstream v1.6.1.
- then I would probably have created `ClickHouse/v1.6.1` and pick relevant fixes on top, and pushed that to upstream
- the bump the versions incrementally, creating `ClickHosue/vx.x.x` versions and re-pushing relevant fixes on top in every iteration. Incremental upgrades makes it easier to identify the cause when something breaks (e.g. the upstream changelog can help).

Anyways, if this PR works, everything is alright 😄

**Review by rschu1ze — APPROVED** [review]

**Comment by antaljanosbenjamin** [comment]
I think with librdkafka the incremental upgrade would be hard. The reasons:
1. We renamed fundamental functions (e.g.: `mtx_lock` and similar function), so basically we would have crazy amount of conflicts
2. There were several patches that were cherry-picked from the original repo from newer versions. This would also mean conflicts

Therefore I pulled the 1.9.2 branch from the original repo and then [renamed](https://github.com/ClickHouse/librdkafka/commit/5f5e2e58de110d6def3707018061af9afa338a02) the functions again (the commands use to rename the functions are in the commit messages) and cherry picked four merge commits that are relevant:
- https://github.com/ClickHouse/librdkafka/commit/b08a70478bf84098ae2001cb834fa9c1991f5199: we don't use lz4 from librdkafka, but let's patch it against known CVE
- https://github.com/ClickHouse/librdkafka/commit/4e760ab49f85db1d1441a2645353fdff992bc34e: to make clang happy
- https://github.com/ClickHouse/librdkafka/commit/a71086dad883ca19084304b7a8ad7fa2d4e23b8b: fixes a datarace
- https://github.com/ClickHouse/librdkafka/commit/b5d5f2d5a2bde1802eb26b1624c0b1bfd441cd3b: fixes another data race

**Comment by antaljanosbenjamin** [comment]
Closing because `1.9.2` is not a good version for us, for reasoning please check https://github.com/ClickHouse/ClickHouse/issues/65297#issuecomment-2357915240

**Pull request closed without merging**
