### PR TITLE
Remove useless logging from ExternalLoader.

### PR DESCRIPTION
**Pull request by vitlibar**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Non-significant

On server shutdown multiple messages `Configuration of reloadable objects has changed` were printed, this PR fixes that.

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
I don't understant why there were huge number of messages on shutdown...

**Comment by alexey-milovidov** [comment]
Is it because I have large number of configuration files for dictionaries?

**Comment by alexey-milovidov** [comment]
But configuration is not changed on shutdown. So, what's the reason I have these messages at all?

**Comment by vitlibar** [comment]
> Is it because I have large number of configuration files for dictionaries?

It was because you have large number of databases. Any database is attached to ExternalLoader as a repository of configurations of external dictionaries (even for databases which don't contain any dictionaries). On shutdown all databases are detached and each detach is considered by ExternalLoader as possible change of configurations and those messages were written for each detach. This PR changes ExternalLoader so it will write a message only when the configuration is actually changed, detaching a database without external dictionaries will not be logged by ExternalLoader anymore.

**Review by alexey-milovidov — APPROVED** [review]

**Pull request merged**
