### PR TITLE
add omitted library for building clickhouse

### PR DESCRIPTION
**Pull request by darky**

### CODE REVIEW

**Comment by robot-metrika-test** [comment]
Can one of the admins verify this patch?

**Comment by alexey-milovidov** [comment]
We have removed glib long time ago:

commit 60a14f5bc46810c1a9175db687ce7112bc7d213e
Author: Alexey Milovidov <milovidov@yandex-team.ru>
Date:   Sat Jan 21 05:35:10 2017 +0300

    Removed glib from build instructions [#CLICKHOUSE-2].

commit e4ff740ef156c5e44d610fa5b531bd2a2c796d31
Author: Alexey Milovidov <milovidov@yandex-team.ru>
Date:   Sat Jan 21 05:32:31 2017 +0300

    Removed usage of glib [#CLICKHOUSE-2].

```
milovidov@milovidov-Latitude-E7470:~/work/ClickHouse$ find . -name '*.h' -or -name '*.cpp' | xargs grep glib2
milovidov@milovidov-Latitude-E7470:~/work/ClickHouse$
```

**Comment by darky** [comment]
It's very strange, because build process ended with error, where need to install *libglib2.0-dev*
version - v1.1.54198-stable
Kubuntu 17.04
Error on this step: https://github.com/yandex/ClickHouse/blob/master/doc/build.md#run-release-script

**Comment by proller** [comment]
we forgot to remove libglib2.0-dev from https://github.com/yandex/ClickHouse/blob/master/debian/control#L6
fix - 
https://github.com/yandex/ClickHouse/commit/dd90a43d900f37d813524dbe3de4ef9eff494556

**Pull request closed without merging**
