### PR TITLE
[Feature]Support manage node status in zookeeper

### PR DESCRIPTION
**Pull request by marising**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Background:
#21574  
If one replica shut down, the ddl operation on cluster will never succeed. 

Changelog category (leave one):
- New Feature

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Increase the node status field and store the node status in ZooKeeper. The node can be paused and started by the CLUSTER PAUSE/START NODE command. DDL operation will ignore the pause node, but it will also excute the DDL queue after it is started.

Detailed description / Documentation draft:

Add the field status to the system.clusters table, 1 means ACTIVED, 2 means PAUSED.

The node status can be managed through SQL syntax: ```CLUSTER PAUSE/START NODE node:port ON CLUSTER xxx.```

When the node hardware or process fails, the node can be suspended by command CLUSTER PAUSE NODE NODE:PORT, DDL query can be executed successfully, and restart after the node is repaired.
```
LOCAL :) CLUSTER PAUSE NODE xx.xxx.24.118:9755 ON CLUSTER DevTest;

CLUSTER PAUSE NODE `xx.xxx.24.118`:`9755`

Query id: 012aa74d-ee92-4c89-b444-3d32df36f943

┌─host──────────┬─port─┬─status─┬─error─┬─num_hosts_remaining─┬─num_hosts_active─┐
│ xx.xxx.24.118 │ 9855 │      0 │       │                   1 │                0 │
│ xx.xxx.24.118 │ 9655 │      0 │       │                   0 │                0 │
└───────────────┴──────┴────────┴───────┴─────────────────────┴──────────────────┘

2 rows in set. Elapsed: 0.104 sec.

LOCAL :) select * from system.clusters where cluster='DevTest';

SELECT *
FROM system.clusters
WHERE cluster = 'DevTest'

Query id: cf3bb8eb-c59e-448a-9810-d0b77af81235

┌─cluster─┬─shard_num─┬─shard_weight─┬─replica_num─┬─host_name─────┬─host_address──┬─port─┬─status─┬─is_local─┬─user────┬─default_database─┬─errors_count─┬─slowdowns_count─┬─estimated_recovery_time─┐
│ DevTest │         1 │            1 │           1 │ xx.xxx.24.118 │ xx.xxx.24.118 │ 9655 │      1 │        1 │ default │                  │            0 │               0 │                       0 │
│ DevTest │         2 │            1 │           1 │ xx.xxx.24.118 │ xx.xxx.24.118 │ 9755 │      2 │        0 │ default │                  │            0 │               0 │                       0 │
│ DevTest │         3 │            1 │           1 │ xx.xxx.24.118 │ xx.xxx.24.118 │ 9855 │      1 │        0 │ default │                  │            0 │               0 │                       0 │
└─────────┴───────────┴──────────────┴─────────────┴───────────────┴───────────────┴──────┴────────┴──────────┴─────────┴──────────────────┴──────────────┴─────────────────┴─────────────────────────┘

3 rows in set. Elapsed: 0.002 sec.

LOCAL :) CREATE database test ON CLUSTER DevTest;

CREATE DATABASE test ON CLUSTER DevTest

Query id: 8bd5aa16-4dbf-444f-b295-d05d5cab2651

┌─host──────────┬─port─┬─status─┬─error─┬─num_hosts_remaining─┬─num_hosts_active─┐
│ xx.xxx.24.118 │ 9855 │      0 │       │                   1 │                0 │
│ xx.xxx.24.118 │ 9655 │      0 │       │                   0 │                0 │
└───────────────┴──────┴────────┴───────┴─────────────────────┴──────────────────┘

2 rows in set. Elapsed: 0.104 sec.

LOCAL :) show databases;

SHOW DATABASES

Query id: 57ec6a89-ecf4-4f7a-8899-e685b900a36b

┌─name────┐
│ default │
│ system  │
│ test    │
└─────────┘

3 rows in set. Elapsed: 0.001 sec.
```

If there are other situations where you need to connect the node directly through the IP and port, you can also judge based on the status of the node.

By adding documentation, you'll allow users to try your new feature immediately, not when someone else will have time to document it later. Documentation is necessary for all features that affect user experience in any way. You can add brief documentation draft above, or add documentation right into your patch as Markdown files in [docs](https://github.com/ClickHouse/ClickHouse/tree/master/docs) folder.

If you are doing this for the first time, it's recommended to read the lightweight [Contributing to ClickHouse Documentation](https://github.com/ClickHouse/ClickHouse/tree/master/docs/README.md) guide first.

Information about CI checks: https://clickhouse.tech/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by UnamedRus** [comment]
Does it make sense to expand `CLUSTER PAUSE NODE` command, so such node would not participate in new Distributed queries?

It would make easier to gracefully remove nodes without affecting any running query.

**Comment by marising** [comment]
> Does it make sense to expand `CLUSTER PAUSE NODE` command, so such node would not participate in new Distributed queries?
> 
> It would make easier to gracefully remove nodes without affecting any running query.

Distributed query is guaranteed by the load_balancing mechanism. If a replica node fails or the process stops, it can skip these nodes.

At present, i only deal with the judgment of the node status by DDL operations is processed. Whether to skip the paused node for distributed queries or other background tasks, this can be improved later, I feel that it is up to the individual module developers to judge.

**Comment by marising** [comment]
@tavplubix do you have a time to review this pr? 

I saw the test exception of Functional stateful tests and Integration tests has nothing to do with my changes.

**Comment by tavplubix** [comment]
Thank you for this attempt to improve usability of ON CLUSTER queries and sorry it took so long to answer.

If I understand correctly, the main purpose of this PR is to avoid `Watching task ... is executing longer than distributed_ddl_task_timeout ...` error when some node in cluster is not available. But I'm not sure if ti's a suitable solution, because it may be inconvenient to mark unavailable nodes manually by executing PAUSE/START queries. Possibly it would be a bit better solution to create some ephemeral node in ZooKeeper on initialization of DDLWorker and use it to determine if host is available or not when waiting for query to finish on all hosts (but it does not cover all cases when `Watching task ... ` error can happen). Another solution is to implement adaptive timeouts. For example, if query is finished on 90% of hosts in a cluster, we can suppose that remaining 10% of hosts are not available and do not wait for them (but it does not cover all cases too and should be implemented very carefully).

Another questionable thing is syntax of the queries. `CLUSTER PAUSE/START NODE` may look like a real cluster management feature for user, but actually it just creates/removes a node in ZooKeeper to manually mark some host as unavailable. The proper design and implementation of cluster management is a hard task and it requires further reflection and discussion, but we did not think it over yet.

Btw, do you know about `distributed_ddl_output_mode` setting? If it's set to `null_status_on_timeout`, then ON CLUSTER query does not throw exception on timeout exceeded, it just returns NULL status for unfinished hosts instead. There are also `never_throw` mode, it disables rethrowing errors from hosts in addition to disabling `Watching task ... ` error.

**Comment by marising** [comment]
Thank you @tavplubix  for your reply, I will explain my thoughts below.

1. The biggest problem we currently encounter is that the node is unavailable due to hardware failure, such as a disk or network card failure. At this time, the execution of DDL will fail. As you said, there are many optional optimization solutions. In some cases, the DDL operation is slow or is Other large DDL operations are blocked, such as deleting a table with a large amount of data. This unavailability is temporary and can be avoided by optimizing the DDL logic. But the situation I described is that the node is clear and unavailable for a long time, so it is a better choice for the node to go offline first, and the server hardware needs to spend several hours to repair it back online or replace a new machine.

2. Currently, the configuration file management node is not very convenient, the node changes, the configuration file needs to be modified and distributed to many nodes, so the SQL of `CLUSTER PAUSE/START NODE` is a quick way to go offline and online nodes. Improve the efficiency of maintaining the cluster.

3. Whether a node needs a state is a question that needs to be discussed. Currently, a node has only two states, either active or offline. Whether some intermediate states are needed, clearly define how various queries and tasks are executed in this state, nodes are active and nodes can provide services to the outside world, I understand that they are two concepts. For example, the node is in the cluster, but its data or metadata is incomplete, and cannot provide external services at this time; or the node temporarily fails and needs to be repaired and cannot provide services; or the node needs to go offline and the data needs to be migrated. This is similar to a node state machine. 

Therefore, node state management not only solves the problem of DDL failure, but also makes node maintenance simple. At the same time, the node state introduced may be the basis for other work.

**Comment by tavplubix** [comment]
> The first step is to set the state manually, and the next step can be an automated method.

I don't think that manual maintenance of host status in a distributed system is a good idea. Because unexpected sudden failures are inevitable, and such failures should be handled automatically. And it can be easily done with ephemeral node which indicates host status.

> distributed_ddl_output_mode set to null_status_on_timeout can solve the problem of slow ddl execution and timeout, but the node down and causes the timeout, the metadata of this node may be different from other nodes.

Yes, but it also will be different if this node was marked as unavailable with `CLUSTER PAUSE/START`.

> In addition, node failures must be handled when writing data to the node to the local table

But, as you write above, 

> Distributed query is guaranteed by the load_balancing mechanism. If a replica node fails or the process stops, it can skip these nodes.
> At present, i only deal with the judgment of the node status by DDL operations is processed. Whether to skip the paused node for distributed queries or other background tasks, this can be improved later, I feel that it is up to the individual module developers to judge.

so `CLUSTER PAUSE/START` queries work only with `DDLWorker` and slightly improve usability of `ON CLUSTER` queries by avoiding timeouts, but it does not handle node failures when writing data, because it's handled by another mechanism. However, I'm not sure if we should take node status into account when working with `Distributed` tables or we should rely on load balancing mechanism instead.

> ... If use the CLUSTER command, only need PAUSE NODE and START NODE, which is very simple.

Not precisely, modification of cluster configuration files affects all places where cluster can be used  (I mean `Distributed` tables and `ON CLUSTER` queries) and `CLUSTER` command does not. So it's not the same things to change a config and to execute a `CLUSTER` command. 

I understand, that `CLUSTER PAUSE/START` could be just a first step in implementation of cluster management, but, as I mention above, 

> The proper design and implementation of cluster management is a hard task and it requires further reflection and discussion, but we did not think it over yet.

so I don't think that we should do first steps without having some plans and understanding where are we going.

**Comment by marising** [comment]
Whether a centralized node state management is needed in a distributed system, I am not sure, but before doing host status management, I refer to the following two products.

1. According to Snowflake’s paper, http://pages.cs.wisc.edu/~yxy/cs764-f20/papers/snowflake.pdf,
`Cloud Services: The “brain” of the system. This layer is a collection of services that manage virtual warehouses, queries, transactions, and all the metadata that goes around that: database schemas, access control information, encryption keys, usage statistics and so forth.`

2. Another product is Doris, which has a FrontEnd service that manages BackEnd, metadata, data blocks, transactions, etc. The node management is like: 
http://doris.apache.org/master/en/sql-reference/sql-statements/Administration/ALTER%20SYSTEM.html#description

Centralized metadata management has its convenience. It can maintain clusters and hosts, manage metadata to avoid metadata inconsistencies between shards and replicas, store INSERT transactions, manage data part and replica information, but there are also some side effects such as performance issues , You can think about it comprehensively.

**Pull request closed without merging**
