### PR TITLE
Fix replication protocol backward incompatibility.

### PR DESCRIPTION
**Pull request by alesapin**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix replication protocol incompatibility introduced in #8598.

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
> Integration tests (release) Pending — Started 
> Stress test (address) Pending — Started 

Did not finished in about 10 hours.

**Comment by CurtizJ** [comment]
Looks like compatability is fixed for replication from new version to old, but not the opposite case. Is it possible to fix fetching parts from old to new version?

**Comment by alesapin** [comment]
I'll cherry-pick it to 19.17 and 19.16 manually.

**Comment by alesapin** [comment]
Tests are OK.

**Comment by oik741** [comment]
Could you guys release 19.17 branch with this fix?
Can't proceed with upgrade to 20.x because of broken replication =(

**Pull request merged**
