### PR TITLE
Upgrade openSSL to  v3.0.10

### PR DESCRIPTION
**Pull request by bhavnajindal**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Test ran
- 02041_openssl_hash_functions_test

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
ClickHouse does not use OpenSSL and therefore isn't affected by any of its CVEs.

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
This is still passable.

**Comment by bhavnajindal** [comment]
@alexey-milovidov Could this PR be marked `can be tested`

**Comment by alexey-milovidov** [comment]
@bhavnajindal, ClickHouse does not use OpenSSL, so testing won't do anything.

**Comment by alexey-milovidov** [comment]
The changelog category and entry are wrong because this PR is essentially a no-op.

**Comment by robot-ch-test-poll2** [comment]
This is an automated comment for commit 6406043294bdf4763d93988db922a5a2c1ce61e8 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/53756/6406043294bdf4763d93988db922a5a2c1ce61e8/ci_running.html)
The overall status of the commit is 🔴 failure

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🔴 failure</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Comment by bhavnajindal** [comment]
I have fixed the changeling category. 
@alexey-milovidov could you please merge this PR

**Pull request merged**
