### PR TITLE
Do not leave any queries after test finish (and add a check into clickhouse-test)

### PR DESCRIPTION
**Pull request by azat**
Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by azat** [comment]
Any clue on why CI did not started any checks?

**Comment by azat** [comment]
>[Integration tests (asan, actions) [1/3] — fail: 1, passed: 654, flaky: 0](https://s3.amazonaws.com/clickhouse-test-reports/34924/66cbb468eb6990b74ef4d08beefbe48d32bf4bd5/integration_tests__asan__actions__[1/3].html)

- #34989

>[Stateless tests (thread, actions) [1/3] — fail: 2, passed: 1278, skipped: 11](https://s3.amazonaws.com/clickhouse-test-reports/34924/66cbb468eb6990b74ef4d08beefbe48d32bf4bd5/stateless_tests__thread__actions__[1/3].html)

```
2022-03-01 06:39:43 WARNING: ThreadSanitizer: signal-unsafe call inside of a signal (pid=2975)
```

- #34988

**Comment by azat** [comment]
>[PullRequestCI / FunctionalStatelessTestMsan1 (pull_request) Failing after 1s — FunctionalStatelessTestMsan1](https://github.com/ClickHouse/ClickHouse/runs/5421809524?check_suite_focus=true)

```
Error: No space left on device : '/home/ubuntu/actions-runner/_diag/Worker_20220304-115922-utc.log'
```

>[Stress test (debug, actions) — Killed by signal (in clickhouse-server.log)](https://s3.amazonaws.com/clickhouse-test-reports/34924/4cef19f134f79ca043ecf7d2d3c44607bb66e64d/stress_test__debug__actions_.html)
>[Stress test (undefined, actions) — Fatal message in clickhouse-server.log](https://s3.amazonaws.com/clickhouse-test-reports/34924/4cef19f134f79ca043ecf7d2d3c44607bb66e64d/stress_test__undefined__actions_.html)

- #34963

>[Stateless tests flaky check (address, actions) — Timeout, fail: 0, passed: 367](https://s3.amazonaws.com/clickhouse-test-reports/34924/4cef19f134f79ca043ecf7d2d3c44607bb66e64d/stateless_tests_flaky_check__address__actions_.html)

- Timeout is OK

**Comment by azat** [comment]
After #34092 had been merged, there can be few tests failures in fast-test, can someone add `force-test` label please?

**Comment by azat** [comment]
@mergify update

**Comment by azat** [comment]
>Stress test (debug, actions) — Hung check failed
>Stress test (memory, actions) — Hung check failed
>Stress test (thread, actions) — Hung check failed
>Stress test (undefined, actions) — Hung check failed

```
Code: 27. DB::ParsingException: Cannot parse input: expected 'eof' before: '--allow_repeated_settings'. (CANNOT_PARSE_INPUT_ASSERTION_FAILED)
```

- https://github.com/ClickHouse/ClickHouse/pull/35073#issuecomment-1059794335

**Comment by azat** [comment]
>[Stateless tests flaky check (address, actions) — Timeout, fail: 0, passed: 396](https://s3.amazonaws.com/clickhouse-test-reports/34924/95d46f71202c0f121812f74240c403d36a41afb5/stateless_tests_flaky_check__address__actions_.html)

- Timeout - OK

>[Stateless tests (release, DatabaseReplicated, actions) [2/2] — fail: 1, passed: 1886, skipped: 43](https://s3.amazonaws.com/clickhouse-test-reports/34924/95d46f71202c0f121812f74240c403d36a41afb5/stateless_tests__release__databasereplicated__actions__[2/2].html)
>[Stateless tests (ubsan, actions) — fail: 1, passed: 3851, skipped: 17](https://s3.amazonaws.com/clickhouse-test-reports/34924/95d46f71202c0f121812f74240c403d36a41afb5/stateless_tests__ubsan__actions_.html)

- `02015_async_inserts_stress_long` - timeout, let's try with `no-parallel` tag.

**Comment by azat** [comment]
>[Stateless tests flaky check (address, actions) — Timeout, fail: 0, passed: 401](https://s3.amazonaws.com/clickhouse-test-reports/34924/d28963d6958fc2efdb75c7219244abbb835ec77e/stateless_tests_flaky_check__address__actions_.html)

- Timeout - OK

>[Stateless tests (debug, actions) [2/3] — fail: 1, passed: 1284, skipped: 18](https://s3.amazonaws.com/clickhouse-test-reports/34924/d28963d6958fc2efdb75c7219244abbb835ec77e/stateless_tests__debug__actions__[2/3].html)

- `01059_window_view_event_hop_watch_strict_asc` looks unrelated

@alexey-milovidov may you can take a look now please?

**Comment by azat** [comment]
@alexey-milovidov friendly ping

**Review by alexey-milovidov — APPROVED** [review]

**Comment by azat** [comment]
This PR hits a bash bug (that had been fixed in bash 5.1), you may find details in this gist - https://gist.github.com/azat/affbda3f8c6b5c38648d4ab105777d88

**Pull request merged**
