### PR TITLE
COS (Tencent Cloud Object Storage) integration

### PR DESCRIPTION
**Pull request by fastio**
To allow import and export to COS.

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- New Feature

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Integration with [COS](https://intl.cloud.tencent.com/product/cos).

Detailed description / Documentation draft:

COS is fully compatible with S3's API, In addition to URI style. 
Add new table function and storage engine to access COS.

For example, create table with COSN engine.
```
CREATE TABLE c2 (
    a UInt32, 
    b String,
    c String
) ENGINE=COSN('http://hk-123456789.cos.ap-hongkong.myqcloud.com/test.dat','xxx','xxx','CSV')
```

### CODE REVIEW

**Comment by fastio** [comment]
@alexey-milovidov Thanks for your review for #12307 
Follow your suggestion：
* new function name;
* some flags for URI parsing.

I open a new RP, and close the old one #12307

**Review by alexey-milovidov — COMMENTED** [review]
We can lower the code size further by simply registering StorageS3 and TableFunctionS3 under two different names (without implementing a separate classes).

**Comment by fastio** [comment]
@alexey-milovidov  Thank you for review. 

> We can lower the code size further by simply registering StorageS3 and TableFunctionS3 under two different names (without implementing a separate classes).

I have removed the classes you mentioned.

**Comment by alexey-milovidov** [comment]
Ok. Now we have to fix Style check and Build checks.

**Comment by alexey-milovidov** [comment]
Another question - do you feel that it's necessary to have a separate name for this storage / table function?
Maybe if `s3` will just magically support COS is also Ok?

**Comment by fastio** [comment]
> Another question - do you feel that it's necessary to have a separate name for this storage / table function?
> Maybe if s3 will just magically support COS is also Ok?

We have integrated COS with Appache/Hive,Spark,Alluxio,HDFS etc.
Our customers are familiar with keyword COS, and using it on other systems.
Nowadays, more and more users of ClickHouse in Tencent Cloud want to import/export data from COS.
It's better to provide consistent way of usage as other platforms(Hive, Spark, Aluxio, HDFS).

Thanks.

**Comment by alexey-milovidov** [comment]
Ok.

**Review by alexey-milovidov — APPROVED** [review]

**Pull request merged**
