### PR TITLE
Watch for certificate files updates in ConfigReloader

### PR DESCRIPTION
**Pull request by myrrc**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Update certificates when they change without the need to manually SYSTEM RELOAD CONFIG

### CODE REVIEW

**Comment by robot-ch-test-poll1** [comment]
This is an automated comment for commit 062b1c464c2961672dc23cc85c6226431f1c44f3 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/52030/062b1c464c2961672dc23cc85c6226431f1c44f3/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Comment by myrrc** [comment]
Things to consider: path to certificate changed, needs updating from inside the reloader itself.

**Comment by myrrc** [comment]
Another (better option) -- run an update callback on configReloader creation having lvalue ref to the reloader, and move certificateReloader inside configReloader callbacks everywhere. Will update PR tomorrow

**Review by alexey-milovidov — APPROVED** [review]
LGTM.
It does not have a test. Let's proceed without a test (but you agree that the feature can be broken or removed)

**Comment by wlzywang** [comment]
CA file is not reloaded

**Pull request merged**
