### PR TITLE
construct query_start_time & query_start_time_microseconds from the same timespec

### PR DESCRIPTION
**Pull request by bharatnc**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Construct `query_start_time` and `query_start_time_microseconds` from the same timespec.

Detailed description / Documentation draft:

This PR ensures that the `query_start_time` and the `query_start_time_microseconds` fields are both constructed from the same timespec, such that both the times are equal upto the precision of a second.

Also improve the functional test for the `query_start_time_microseconds` field for the `system.query_log` and `system.query_thread_log tables`.

Relates to: #9800

### CODE REVIEW

**Comment by bharatnc** [comment]
cc: @alesapin

**Comment by bharatnc** [comment]
cc: @tavplubix - while changes in this PR are partly covered by PR #14760 - made quick changes to construct `query_start_time` and `query_start_time_microseconds` from the same timespec with tests.

**Review by tavplubix — APPROVED** [review]

**Comment by bharatnc** [comment]
Related to #4821

**Comment by bharatnc** [comment]
Also relevant to: #14252

**Pull request merged**
