### PR TITLE
Add fuzzer for `executeQuery` function

### PR DESCRIPTION
**Pull request by nikitamikhaylov**
Changelog category (leave one):

- Not for changelog (changelog entry is not required)

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

### CODE REVIEW

**Comment by nikitamikhaylov** [comment]
Also need to update dictionary (include all new functions, key words and datatypes)

**Comment by alexey-milovidov** [comment]
Let's make an example, how to run it with stateless tests as a dictionary.

**Comment by nikitamikhaylov** [comment]
Something like this$
```
cd /ClickHouse/ClickHouse/tests/fuzz
mkdir execute_query_fuzzer.in
cp ../queries/0_stateless/*.sql execute_query_fuzzer.in/
cp ../queries/1_stateful/*.sql execute_query_fuzzer.in/

$BUILD_DIRECTORY/src/Interpreters/fuzzers/execute_query_fuzzer -dict=all.dict execute_query_fuzzer.in/
```

**Comment by nikitamikhaylov** [comment]
Faced with broken exceptions during local testing. Need to test proper fuzzer binary from CI.

**Comment by nikitamikhaylov** [comment]
Only build check is important and it is green

**Pull request merged**
