### PR TITLE
Kill runner when integration tests fail to pre-pull

### PR DESCRIPTION
**Pull request by Felixoid**
### Changelog category (leave one):
- CI Fix or Improvement (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Add function `kill_ci_runner`. Kill runner when pre-pull failed.

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Run only fuzzers related jobs (libFuzzer fuzzers, AST fuzzers, etc.)
- [ ]  Exclude: AST fuzzers
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-clickhouse-ci-2** [comment]
*This is an automated comment for commit 8d5babf65fe78449e1bf3e3979f3fb7d09d18708 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/69557/8d5babf65fe78449e1bf3e3979f3fb7d09d18708/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Builds</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/bbcde1991099ea0c65306003abab51758e0d0410/builds/report.html">✅ success</a></td></tr>
<tr><td>ClickBench</td><td>Runs [ClickBench](https://github.com/ClickHouse/ClickBench/) with instant-attach table</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/bbcde1991099ea0c65306003abab51758e0d0410/clickbench__aarch64_.html">✅ success</a></td></tr>
<tr><td>Compatibility check</td><td>Checks that <b>clickhouse</b> binary runs on distributions with old libc versions. If it fails, ask a maintainer for help</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/bbcde1991099ea0c65306003abab51758e0d0410/compatibility_check__aarch64_.html">✅ success</a></td></tr>
<tr><td>Docker keeper image</td><td>The check to build and optionally push the mentioned image to docker hub</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/bbcde1991099ea0c65306003abab51758e0d0410/docker_keeper_image.html">✅ success</a></td></tr>
<tr><td>Docker server image</td><td>The check to build and optionally push the mentioned image to docker hub</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/bbcde1991099ea0c65306003abab51758e0d0410/docker_server_image.html">✅ success</a></td></tr>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/69432/6f9d1631e26bbb0263962c6d50c65e9ee2be561a/docs_check.html">✅ success</a></td></tr>
<tr><td>Fast test</td><td>Normally this is the first check that is ran for a PR. It builds ClickHouse and runs most of <a href="https://clickhouse.com/docs/en/development/tests#functional-tests">stateless functional tests</a>, omitting some. If it fails, further checks are not started until it is fixed. Look at the report to see which tests fail, then reproduce the failure locally as described <a href="https://clickhouse.com/docs/en/development/tests#functional-test-locally">here</a></td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/bbcde1991099ea0c65306003abab51758e0d0410/fast_test.html">✅ success</a></td></tr>
<tr><td>Install packages</td><td>Checks that the built packages are installable in a clear environment</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/bbcde1991099ea0c65306003abab51758e0d0410/install_packages__aarch64_.html">✅ success</a></td></tr>
<tr><td>Stateful tests</td><td>Runs stateful functional tests for ClickHouse binaries built in various configurations -- release, debug, with sanitizers, etc</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/bbcde1991099ea0c65306003abab51758e0d0410/stateful_tests__aarch64_.html">✅ success</a></td></tr>
<tr><td>Stateless tests</td><td>Runs stateless functional tests for ClickHouse binaries built in various configurations -- release, debug, with sanitizers, etc</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/bbcde1991099ea0c65306003abab51758e0d0410/stateless_tests__debug__[1_2].html">✅ success</a></td></tr>
<tr><td>Stress test</td><td>Runs stateless functional tests concurrently from several clients to detect concurrency-related errors</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/bbcde1991099ea0c65306003abab51758e0d0410/stress_test__debug_.html">✅ success</a></td></tr>
<tr><td>Unit tests</td><td>Runs the unit tests for different release types</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/bbcde1991099ea0c65306003abab51758e0d0410/unit_tests__asan_.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Comment by Felixoid** [comment]
The instance continues working after the runner is killed for ~ 10 minute

```
# Runner removal

Failed: Removing runner from the server
Runner "i-0d69aa69e91d3ff08" is still running a job"
Runner is working with pid 654695, checking the metadata in background
The runner is launched 635 seconds ago and still hasn't received a job
Attempt to delete the runner for a graceful shutdown

# Runner removal

Does not exist. Skipping Removing runner from the server
√ Removed .credentials
√ Removed .runner

Runner didn't launch or have assigned jobs after 635 seconds, shutting down
Going to terminate the runner's instance and decrease asg capacity
```

Not sure yet if:
- it's fine
- how to address it

**Comment by Felixoid** [comment]
How it looks when the pre-pull docker killed 5 times on the runner:

```
The Compose file '/ClickHouse/tests/integration/compose/docker_compose_prometheus.yml' is invalid because:
services.prometheus_reader.expose is invalid: should be of the format 'PORT[/PROTOCOL]'
services.prometheus_writer.expose is invalid: should be of the format 'PORT[/PROTOCOL]'
Traceback (most recent call last):
  File "/home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/tests/integration/./runner", line 503, in <module>
    subprocess.check_call(cmd_pre_pull, shell=True)
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'docker run   --rm --name clickhouse_integration_tests_20wl4o --privileged --dns-search='.' --volume=/home/ubuntu/actions-runner/_work/_temp/test/build/clickhouse-odbc-bridge:/clickhouse-odbc-bridge --volume=/home/ubuntu/actions-runner/_work/_temp/test/build/clickhouse:/clickhouse --volume=/home/ubuntu/actions-runner/_work/_temp/test/build/clickhouse-library-bridge:/clickhouse-library-bridge --volume=/home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/programs/server:/clickhouse-config --volume=/home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/tests/integration:/ClickHouse/tests/integration --volume=/home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/utils/backupview:/ClickHouse/utils/backupview --volume=/home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/utils/grpc-client/pb2:/ClickHouse/utils/grpc-client/pb2 --volume=/run:/run/host:ro --volume=clickhouse_integration_tests_volume:/var/lib/docker -e DOCKER_DOTNET_CLIENT_TAG=11de0b29a15d -e DOCKER_HELPER
INFO:root:docker-compose pull failed: Command 'cd /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/tests/integration && timeout --signal=KILL 1h ./runner --disable-net-host --old-analyzer --docker-compose-images-tags=clickhouse/dotnet-client:11de0b29a15d --docker-compose-images-tags=clickhouse/integration-helper:634724fd9222 --docker-compose-images-tags=clickhouse/integration-test:2d0a5b22f529  --docker-image-version=04ae28e242f0 --docker-compose-images-tags=clickhouse/kerberized-hadoop:5105c1c1cfaa --docker-compose-images-tags=clickhouse/kerberos-kdc:310561e6eb75 --docker-compose-images-tags=clickhouse/mysql-golang-client:a63320938f8d --docker-compose-images-tags=clickhouse/mysql-java-client:807c80c2c10c --docker-compose-images-tags=clickhouse/mysql-js-client:d7dd5dbc48a5 --docker-compose-images-tags=clickhouse/mysql-php-client:99abb5178265 --docker-compose-images-tags=clickhouse/nginx-dav:b55ac9cd7519 --docker-compose-images-tags=clickhouse/postgresql-java-client:f81480176616 --docker-compose-images-
ERROR:root:Pulling images failed for 5 attempts. Will fail the worker.
Error: Pulling images failed for 5 attempts. Will fail the worker.
ERROR:ci_utils:Sleeping 5 seconds and killing all possible processes from following:
 54294: (python3)
 54293: (sh)
 54292: (python3)
 54291: (bash)
 54039: (Runner.Worker)
 54019: (Runner.Listener)
 54015: (run-helper.sh)
 54011: (run.sh)
 54009: (sudo)
 1430: (bash)
 1424: (cloud-init)
 1: (systemd)
```

in https://github.com/ClickHouse/ClickHouse/actions/runs/10831894388/job/30060973215?pr=69557

**Comment by Felixoid** [comment]
We faced the issue with dockerhub proxy again, let's have this fuse in the code base to at least restart the failing jobs automatically

**Pull request merged**
