### PR TITLE
Format prometheus metric name

### LINKED ISSUE #31863: Prometheus does not show metrics.
(you don't have to strictly follow this form)

**Describe the unexpected behaviour**
Prometheus does not show metrics.

**How to reproduce**
* Which ClickHouse server version to use  21.8
* Set network interface name to `irbr0-nic`
* Set up prometheus and clickhouse 
* Send some query to clickhouse
* Then no metircs appears

**Expected behavior**
There should be metics like `ClickHouseAsyncMetrics_NetworkSendBytes_virbr0-nic`.

### PR DESCRIPTION
**Pull request by JackyWoo**
Changelog category (leave one):

- Improvement

Prometheus metric name should meet constraint `\[a-zA-Z_:\]\[a-zA-Z0-9_:\]\*` 
Detailed in https://prometheus.io/docs/practices/naming/

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

- Format prometheus metric name in `PrometheusMetricsWriter` before sending.

This pr will close #31863

### CODE REVIEW

**Review by vdimir — COMMENTED** [review]
Looks like `replaceInvalidChars` and `toPrometheusMetricName` do aprrox same thing. Can we combine all validation/correction stuff in one function?

Also need test (you can modify existing https://github.com/ClickHouse/ClickHouse/blob/master/tests/integration/test_prometheus_endpoint/test.py)

**Comment by JackyWoo** [comment]
Almost the same thing, will close this pr.

**Comment by vdimir** [comment]
@JackyWoo 
But what about the issue https://github.com/ClickHouse/ClickHouse/issues/31863 ? Does it reproduce on master or only on previous versions?

**Comment by JackyWoo** [comment]
I tested in 21.8, I will test it in master later.

**Pull request closed without merging**
