### PR TITLE
Support set orc reader time zone name

### PR DESCRIPTION
**Pull request by KevinyhZou**
### Changelog category (leave one):
- Improvement
 
### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Rename setting `input_format_orc_read_use_writer_time_zone` to `input_format_orc_reader_timezone` and allow the user to set the reader timezone.

### Documentation entry for user-facing changes

In pr : https://github.com/ClickHouse/ClickHouse/pull/66025, we introduce a settings `input_format_orc_read_use_writer_time_zone` to fix when read orc file, make the reader use writer timezone, not always use `GMT`.  But sometimes the reader timezone should be different from writer timezone,  like in `Asia/Shanghai`  read a file that was written by `America/Los_Angeles`,  then the reader timezone should be set 'Asia/Shanghai', and the orc reader would convert the timestamp from  `America/Los_Angeles` to `Asia/Shanghai`. So we introduce a setting `input_format_orc_reader_timezone` to replace the old setting `input_format_orc_read_use_writer_time_zone` to allow users to set the reader timezone by themselves, to solve this problem. and the default value still keeps `GMT`.

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-clickhouse-ci-2** [comment]
*This is an automated comment for commit 4096c13c4e222bd2795ef8d7998fb61ba4158b69 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/67175/4096c13c4e222bd2795ef8d7998fb61ba4158b69/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Style check</td><td>Runs a set of checks to keep the code style clean. If some of tests failed, see the related log from the report</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/67175/4096c13c4e222bd2795ef8d7998fb61ba4158b69/style_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Comment by Avogar** [comment]
`input_format_orc_read_use_writer_time_zone` was already added to `24.7` release branch, we will need to baclport this change to it

**Comment by KevinyhZou** [comment]
ok

**Comment by Avogar** [comment]
New test is flaky - I guess because of randomizing `session_timezone` in tests?

**Comment by KevinyhZou** [comment]
done @Avogar

**Pull request merged**
