### PR TITLE
Bump ICU from v70 to v75

### PR DESCRIPTION
**Pull request by rschu1ze**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by robot-ch-test-poll4** [comment]
*This is an automated comment for commit c803fbfca17d9a4e689630e9bce42531031f009d with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/66474/c803fbfca17d9a4e689630e9bce42531031f009d/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/ad21a9307fc1d0715388923d8f1e490a7bd9bebe/docs_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Comment by alexey-milovidov** [comment]
Check icudata as well.

**Comment by rschu1ze** [comment]
Sure.

Motivation was https://github.com/ClickHouse/ClickHouse/pull/65761 where I noticed our ICU is outdated.

**Comment by rschu1ze** [comment]
Note to myself: https://github.com/ClickHouse/icudata/pull/2

**Comment by MBkkt** [comment]
@rschu1ze Is this update correct?

> # These lists of sources were generated from build log of the original ICU build system (configure + make).

icu added some new files in `common/` between 70 and 75

**Comment by rschu1ze** [comment]
@MBkkt At least the linker did not complain about missing symbols. I would be very happy if you send a PR which adds the missing files (+ then ping me). Otherwise, I can do it once I am back from vacation.

**Comment by rschu1ze** [comment]
@MBkkt https://github.com/ClickHouse/ClickHouse/pull/69240

**Pull request merged**
