### PR TITLE
Fix integration tests report parser

### PR DESCRIPTION
**Pull request by alesapin**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Review by novikd — APPROVED** [review]

**Comment by alesapin** [comment]
@mergifyio update

**Comment by alexey-milovidov** [comment]
Need to merge with master after #36337.

**Comment by alexey-milovidov** [comment]
@mergifyio update

**Comment by alesapin** [comment]
`test_input_format_parallel_parsing_memory_tracking/test.py::test_memory_tracking_total` -- I don't understand why this test fails from time to time with thread sanitizer. In my local setup, it always consumes less than 500 MB of memory, but the limit is 4 Gb.

**Pull request merged**
