### PR TITLE
Replace make_pair()/make_tuple() by pair()/tuple()

### PR DESCRIPTION
**Pull request by rschu1ze**
Both make_*() helpers were obsoleted by C++17 class template argumentdeduction (CTAD).

In some contexts, we can even use initialization list syntax, i.e.

`std::make_pair("hello", "world")` --> `std::pair("hello", "world")` --> `{"hello", "world"}`

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by qoega** [comment]
And how to check it later?
We need to add it to codestyle at least. Is there a linter for make_pair?

**Comment by rschu1ze** [comment]
make_pair/make_tuple vs. pair/tuple is only a stylistic w/o performance implication, so I would rather not reject commits which use the former.

Unfortunately, clang-tidy has no corresponding checks, and obviously there are also no compiler warnings. Don't know of other linters which could help here. Actually a simple grep for make_pair/make_tuple would do the trick and in my previous company this was done when checking something in. If such a grep check exists in CH, please let me know. Otherwise, I'd be fine with not adding a further check.

**Comment by qoega** [comment]
You can add Grep based check to style-check. With description that points to docs with our style guide. It will help and will be quiet verbose.

**Comment by qoega** [comment]
Here for example
https://github.com/ClickHouse/ClickHouse/blob/master/utils/check-style/check-style

**Comment by rschu1ze** [comment]
That was what I was looking for, tnx. Will extend that script.

**Comment by rschu1ze** [comment]
@Mergifyio update

**Review by alesapin — CHANGES_REQUESTED** [review]
These changes don't look good to me. There are a lot of new things in C++, but we 100% don't want to force people to use all of them. Of course, things like `std::auto_ptr` must be banned because it's deprecated by the standard and dangerous, but this case is absolutely not the same. `std::make_pair` and `std::make_tuple` are not deprecated, at list at cppreference.com and cplusplus.com. People used to use them and they have no perf/memory penalty compared with constructors.

I agree with the docs improvements (I didn't know it before). Changes in code are questionable, but prohibiting people to use absolutely valid, non-deprecated construction in code is 100% harm.

**Comment by alesapin** [comment]
BTW, looks like GCC agree with me:
```
May 06 07:59:56 FAILED: src/CMakeFiles/clickhouse_common_io.dir/Common/ThreadPool.cpp.o 
May 06 07:59:56 prlimit --as=10000000000 --data=10000000000 --cpu=1000 /usr/bin/ccache /usr/bin/g++-11  -DAWS_SDK_VERSION_MAJOR=1 -DAWS_SDK_VERSION_MINOR=7 -DAWS_SDK_VERSION_PATCH=231 -DBOOST_ASIO_HAS_STD_INVOKE_RESULT=1 -DBOOST_ASIO_STANDALONE=1 -DENABLE_MULTITARGET_CODE=1 -DENABLE_OPENSSL_ENCRYPTION -DLZ4_DISABLE_DEPRECATE_WARNINGS=1 -DMZ_COMPAT_VERSION=110 -DPOCO_ENABLE_CPP11 -DPOCO_HAVE_FD_EPOLL -DPOCO_OS_FAMILY_UNIX -DSTD_EXCEPTION_HAS_STACK_TRACE=1 -DUNALIGNED_OK -DWITH_COVERAGE=0 -DWITH_GZFILEOP -DX86_64 -DZLIB_COMPAT -Iincludes/configs -I../src -Isrc -Isrc/Core/include -I../base/glibc-compatibility/memcpy -I../contrib/jemalloc-cmake/include -I../base/widechar_width -I../base/base/.. -Ibase/base/.. -I../contrib/cctz/include -I../base/pcg-random/. -I../contrib/miniselect/include -I../contrib/zstd/lib -I../contrib/lz4/lib -I../contrib/minizip-ng -I../contrib/minizip-ng-cmake -isystem ../contrib/libcxx/include -isystem ../contrib/libcxx/src -isystem ../contrib/libcxxabi/include -isystem ../contrib/libunwind/include -isystem ../contrib/cityhash102/include -isystem ../contrib/boost -isystem ../contrib/poco/Net/include -isystem ../contrib/poco/Foundation/include -isystem ../contrib/poco/NetSSL_OpenSSL/include -isystem ../contrib/poco/Crypto/include -isystem ../contrib/boringssl/include -isystem ../contrib/poco/Util/include -isystem ../contrib/poco/JSON/include -isystem ../contrib/poco/XML/include -isystem ../contrib/replxx/include -isystem ../contrib/fmtlib-cmake/../fmtlib/include -isystem ../contrib/magic_enum/include -isystem ../contrib/double-conversion -isystem ../contrib/dragonbox/include -isystem ../contrib/re2 -isystem contrib/re2-cmake -isystem ../contrib/zlib-ng -isystem contrib/zlib-ng-cmake -isystem ../contrib/libcpuid -isystem ../contrib/pdqsort -isystem ../contrib/xz/src/liblzma/api -isystem ../contrib/aws-c-common/include -isystem ../contrib/aws-c-event-stream/include -isystem ../contrib/aws/aws-cpp-sdk-s3/include -isystem ../contrib/aws/aws-cpp-sdk-core/include -isystem contrib/aws-s3-cmake/include -isystem ../contrib/azure/sdk/core/azure-core/inc -isystem ../contrib/azure/sdk/identity/azure-identity/inc -isystem ../contrib/azure/sdk/storage/azure-storage-common/inc -isystem ../contrib/azure/sdk/storage/azure-storage-blobs/inc -isystem ../contrib/brotli/c/include -isystem ../contrib/snappy -isystem contrib/snappy-cmake -isystem ../contrib/msgpack-c/include -isystem ../contrib/fast_float/include -isystem ../contrib/bzip2 -isystem contrib/bzip2 -fdiagnostics-color=always -fsized-deallocation -fcoroutines  -pipe -mssse3 -msse4.1 -msse4.2 -mpclmul -mpopcnt -fasynchronous-unwind-tables -ffile-prefix-map=/build=. -falign-functions=32   -Wall  -Wextra -Wframe-larger-than=65536 -O2 -g -DNDEBUG -O3 -g -gdwarf-4  -fno-pie   -D OS_LINUX -fno-tree-loop-distribute-patterns -Wbool-compare -Wcast-align -Wcast-qual -Wdelete-incomplete -Wdisabled-optimization -Wduplicated-cond -Wenum-compare -Winit-self -Wlogical-not-parentheses -Wlogical-op -Wmaybe-uninitialized -Wmisleading-indentation -Wmissing-include-dirs -Wnon-virtual-dtor -Wno-return-local-addr -Wodr -Wold-style-cast -Wplacement-new=2 -Wpointer-arith -Wredundant-decls -Wreorder -Wshadow -Wshift-negative-value -Wsized-deallocation -Wsizeof-array-argument -Wsizeof-pointer-memaccess -Wsuggest-override -Wswitch-bool -Wtautological-compare -Wtrampolines -Wunused -Wundef -Wvector-operation-performance -Wzero-as-null-pointer-constant -Wno-sequence-point -Wno-stringop-overflow -Wno-error=class-memaccess -Wno-error=free-nonheap-object -Wno-error=nonnull -Werror -nostdinc++ -pthread -std=gnu++2a -MD -MT src/CMakeFiles/clickhouse_common_io.dir/Common/ThreadPool.cpp.o -MF src/CMakeFiles/clickhouse_common_io.dir/Common/ThreadPool.cpp.o.d -o src/CMakeFiles/clickhouse_common_io.dir/Common/ThreadPool.cpp.o -c ../src/Common/ThreadPool.cpp
May 06 07:59:56 g++-11: internal compiler error: Segmentation fault signal terminated program cc1plus
May 06 07:59:56 Please submit a full bug report,
May 06 07:59:56 with preprocessed source if appropriate.
May 06 07:59:56 See <file:///usr/share/doc/gcc-11/README.Bugs> for instructions.
May 06 07:59:56 [8057/10316] Building CXX object src/CMakeFiles/clickhouse_common_io.dir/IO/ReadBufferFromPocoSocket.cpp.o
May 06 07:59:57 [8058/10316] Building CXX object src/CMakeFiles/clickhouse_common_io.dir/IO/TimeoutSetter.cpp.o
May 06 07:59:57 [8059/10316] Building CXX object src/CMakeFiles/clickhouse_common_io.dir/IO/SnappyWriteBuffer.cpp.o
May 06 07:59:58 [8060/10316] Building CXX object src/CMakeFiles/clickhouse_common_io.dir/IO/WithFileName.cpp.o
May 06 07:59:58 [8061/10316] Building CXX object src/CMakeFiles/clickhouse_common_io.dir/IO/Progress.cpp.o
May 06 07:59:58 [8062/10316] Building CXX object src/CMakeFiles/clickhouse_common_io.dir/Common/SystemLogBase.cpp.o
May 06 07:59:58 FAILED: src/CMakeFiles/clickhouse_common_io.dir/Common/SystemLogBase.cpp.o 
May 06 07:59:58 prlimit --as=10000000000 --data=10000000000 --cpu=1000 /usr/bin/ccache /usr/bin/g++-11  -DAWS_SDK_VERSION_MAJOR=1 -DAWS_SDK_VERSION_MINOR=7 -DAWS_SDK_VERSION_PATCH=231 -DBOOST_ASIO_HAS_STD_INVOKE_RESULT=1 -DBOOST_ASIO_STANDALONE=1 -DENABLE_MULTITARGET_CODE=1 -DENABLE_OPENSSL_ENCRYPTION -DLZ4_DISABLE_DEPRECATE_WARNINGS=1 -DMZ_COMPAT_VERSION=110 -DPOCO_ENABLE_CPP11 -DPOCO_HAVE_FD_EPOLL -DPOCO_OS_FAMILY_UNIX -DSTD_EXCEPTION_HAS_STACK_TRACE=1 -DUNALIGNED_OK -DWITH_COVERAGE=0 -DWITH_GZFILEOP -DX86_64 -DZLIB_COMPAT -Iincludes/configs -I../src -Isrc -Isrc/Core/include -I../base/glibc-compatibility/memcpy -I../contrib/jemalloc-cmake/include -I../base/widechar_width -I../base/base/.. -Ibase/base/.. -I../contrib/cctz/include -I../base/pcg-random/. -I../contrib/miniselect/include -I../contrib/zstd/lib -I../contrib/lz4/lib -I../contrib/minizip-ng -I../contrib/minizip-ng-cmake -isystem ../contrib/libcxx/include -isystem ../contrib/libcxx/src -isystem ../contrib/libcxxabi/include -isystem ../contrib/libunwind/include -isystem ../contrib/cityhash102/include -isystem ../contrib/boost -isystem ../contrib/poco/Net/include -isystem ../contrib/poco/Foundation/include -isystem ../contrib/poco/NetSSL_OpenSSL/include -isystem ../contrib/poco/Crypto/include -isystem ../contrib/boringssl/include -isystem ../contrib/poco/Util/include -isystem ../contrib/poco/JSON/include -isystem ../contrib/poco/XML/include -isystem ../contrib/replxx/include -isystem ../contrib/fmtlib-cmake/../fmtlib/include -isystem ../contrib/magic_enum/include -isystem ../contrib/double-conversion -isystem ../contrib/dragonbox/include -isystem ../contrib/re2 -isystem contrib/re2-cmake -isystem ../contrib/zlib-ng -isystem contrib/zlib-ng-cmake -isystem ../contrib/libcpuid -isystem ../contrib/pdqsort -isystem ../contrib/xz/src/liblzma/api -isystem ../contrib/aws-c-common/include -isystem ../contrib/aws-c-event-stream/include -isystem ../contrib/aws/aws-cpp-sdk-s3/include -isystem ../contrib/aws/aws-cpp-sdk-core/include -isystem contrib/aws-s3-cmake/include -isystem ../contrib/azure/sdk/core/azure-core/inc -isystem ../contrib/azure/sdk/identity/azure-identity/inc -isystem ../contrib/azure/sdk/storage/azure-storage-common/inc -isystem ../contrib/azure/sdk/storage/azure-storage-blobs/inc -isystem ../contrib/brotli/c/include -isystem ../contrib/snappy -isystem contrib/snappy-cmake -isystem ../contrib/msgpack-c/include -isystem ../contrib/fast_float/include -isystem ../contrib/bzip2 -isystem contrib/bzip2 -fdiagnostics-color=always -fsized-deallocation -fcoroutines  -pipe -mssse3 -msse4.1 -msse4.2 -mpclmul -mpopcnt -fasynchronous-unwind-tables -ffile-prefix-map=/build=. -falign-functions=32   -Wall  -Wextra -Wframe-larger-than=65536 -O2 -g -DNDEBUG -O3 -g -gdwarf-4  -fno-pie   -D OS_LINUX -fno-tree-loop-distribute-patterns -Wbool-compare -Wcast-align -Wcast-qual -Wdelete-incomplete -Wdisabled-optimization -Wduplicated-cond -Wenum-compare -Winit-self -Wlogical-not-parentheses -Wlogical-op -Wmaybe-uninitialized -Wmisleading-indentation -Wmissing-include-dirs -Wnon-virtual-dtor -Wno-return-local-addr -Wodr -Wold-style-cast -Wplacement-new=2 -Wpointer-arith -Wredundant-decls -Wreorder -Wshadow -Wshift-negative-value -Wsized-deallocation -Wsizeof-array-argument -Wsizeof-pointer-memaccess -Wsuggest-override -Wswitch-bool -Wtautological-compare -Wtrampolines -Wunused -Wundef -Wvector-operation-performance -Wzero-as-null-pointer-constant -Wno-sequence-point -Wno-stringop-overflow -Wno-error=class-memaccess -Wno-error=free-nonheap-object -Wno-error=nonnull -Werror -nostdinc++ -pthread -std=gnu++2a -MD -MT src/CMakeFiles/clickhouse_common_io.dir/Common/SystemLogBase.cpp.o -MF src/CMakeFiles/clickhouse_common_io.dir/Common/SystemLogBase.cpp.o.d -o src/CMakeFiles/clickhouse_common_io.dir/Common/SystemLogBase.cpp.o -c ../src/Common/SystemLogBase.cpp
May 06 07:59:58 g++-11: internal compiler error: Segmentation fault signal terminated program cc1plus
May 06 07:59:58 Please submit a full bug report,
May 06 07:59:58 with preprocessed source if appropriate.
May 06 07:59:58 See <file:///usr/share/doc/gcc-11/README.Bugs> for instructions.
May 06 07:59:59 [8063/10316] Building CXX object src/CMakeFiles/clickhouse_common_io.dir/IO/ReadBufferFromEncryptedFile.cpp.o
May 06 08:00:00 [8064/10316] Building CXX object src/CMakeFiles/clickhouse_common_io.dir/IO/ReadBufferFromAzureBlobStorage.cpp.o
May 06 08:00:00 [8065/10316] Building CXX object contrib/llvm/llvm/lib/Bitcode/Reader/CMakeFiles/LLVMBitReader.dir/BitcodeReader.cpp.o
May 06 08:00:01 [8066/10316] Building CXX object src/CMakeFiles/clickhouse_common_io.dir/IO/ReadBufferFromFile.cpp.o
May 06 08:00:01 [8067/10316] Building CXX object contrib/llvm/llvm/lib/Target/X86/CMakeFiles/LLVMX86CodeGen.dir/X86DomainReassignment.cpp.o
May 06 08:00:01 [8068/10316] Building CXX object contrib/llvm/llvm/lib/Target/X86/CMakeFiles/LLVMX86CodeGen.dir/X86PadShortFunction.cpp.o
May 06 08:00:01 [8069/10316] Building CXX object src/CMakeFiles/clickhouse_common_io.dir/IO/ReadBufferFromFileDescriptor.cpp.o
May 06 08:00:01 [8070/10316] Building CXX object src/CMakeFiles/clickhouse_common_io.dir/IO/SnappyReadBuffer.cpp.o
May 06 08:00:01 [8071/10316] Building CXX object src/CMakeFiles/clickhouse_common_io.dir/IO/WriteBufferFromEncryptedFile.cpp.o
May 06 08:00:02 [8072/10316] Building CXX object src/CMakeFiles/clickhouse_common_io.dir/IO/ReadBufferFromS3.cpp.o
May 06 08:00:02 [8073/10316] Building CXX object src/CMakeFiles/clickhouse_common_io.dir/IO/ParallelReadBuffer.cpp.o
May 06 08:00:02 [8074/10316] Building CXX object src/CMakeFiles/clickhouse_common_io.dir/IO/WithFileSize.cpp.o
May 06 08:00:04 [8075/10316] Building CXX object src/CMakeFiles/dbms.dir/Disks/IO/ThreadPoolReader.cpp.o
May 06 08:00:04 [8076/10316] Building CXX object src/CMakeFiles/clickhouse_common_io.dir/IO/ReadHelpers.cpp.o
May 06 08:00:05 [8077/10316] Building CXX object src/CMakeFiles/clickhouse_common_io.dir/IO/S3Common.cpp.o
May 06 08:00:06 [8078/10316] Building CXX object programs/client/CMakeFiles/clickhouse-client-lib.dir/Client.cpp.o
May 06 08:00:06 FAILED: programs/client/CMakeFiles/clickhouse-client-lib.dir/Client.cpp.o 
May 06 08:00:06 prlimit --as=10000000000 --data=10000000000 --cpu=1000 /usr/bin/ccache /usr/bin/g++-11  -DAWS_SDK_VERSION_MAJOR=1 -DAWS_SDK_VERSION_MINOR=7 -DAWS_SDK_VERSION_PATCH=231 -DBOOST_ASIO_HAS_STD_INVOKE_RESULT=1 -DBOOST_ASIO_STANDALONE=1 -DCARES_STATICLIB -DENABLE_OPENSSL_ENCRYPTION -DPOCO_ENABLE_CPP11 -DPOCO_HAVE_FD_EPOLL -DPOCO_OS_FAMILY_UNIX -DSTD_EXCEPTION_HAS_STACK_TRACE=1 -DUNALIGNED_OK -DWITH_COVERAGE=0 -DWITH_GZFILEOP -DX86_64 -DZLIB_COMPAT -Iincludes/configs -I../base/glibc-compatibility/memcpy -I../src -Isrc -Isrc/Core/include -I../base/base/.. -Ibase/base/.. -I../contrib/cctz/include -I../base/pcg-random/. -I../contrib/miniselect/include -I../contrib/zstd/lib -I../contrib/libfarmhash -I../src/Common/mysqlxx/. -Icontrib/grpc/third_party/cares/cares -I../contrib/grpc/third_party/cares/cares -I../contrib/libmetrohash/src -I../contrib/murmurhash/include -I../base/readpassphrase/. -isystem ../contrib/libcxx/include -isystem ../contrib/libcxx/src -isystem ../contrib/libcxxabi/include -isystem ../contrib/libunwind/include -isystem ../contrib/boost -isystem ../contrib/cityhash102/include -isystem ../contrib/poco/Net/include -isystem ../contrib/poco/Foundation/include -isystem ../contrib/poco/NetSSL_OpenSSL/include -isystem ../contrib/poco/Crypto/include -isystem ../contrib/boringssl/include -isystem ../contrib/poco/Util/include -isystem ../contrib/poco/JSON/include -isystem ../contrib/poco/XML/include -isystem ../contrib/replxx/include -isystem ../contrib/fmtlib-cmake/../fmtlib/include -isystem ../contrib/magic_enum/include -isystem ../contrib/double-conversion -isystem ../contrib/dragonbox/include -isystem ../contrib/re2 -isystem contrib/re2-cmake -isystem ../contrib/zlib-ng -isystem contrib/zlib-ng-cmake -isystem ../contrib/pdqsort -isystem ../contrib/xz/src/liblzma/api -isystem ../contrib/aws-c-common/include -isystem ../contrib/aws-c-event-stream/include -isystem ../contrib/aws/aws-cpp-sdk-s3/include -isystem ../contrib/aws/aws-cpp-sdk-core/include -isystem contrib/aws-s3-cmake/include -isystem ../contrib/azure/sdk/core/azure-core/inc -isystem ../contrib/azure/sdk/identity/azure-identity/inc -isystem ../contrib/azure/sdk/storage/azure-storage-common/inc -isystem ../contrib/azure/sdk/storage/azure-storage-blobs/inc -isystem ../contrib/snappy -isystem contrib/snappy-cmake -isystem ../contrib/msgpack-c/include -isystem ../contrib/fast_float/include -isystem ../contrib/abseil-cpp -isystem ../contrib/consistent-hashing -isystem ../contrib/llvm/llvm/include -isystem contrib/llvm/llvm/include -isystem ../contrib/croaring/cpp -isystem ../contrib/croaring/include -isystem ../contrib/NuRaft/include -isystem contrib/mariadb-connector-c-cmake/include-public -isystem ../contrib/mariadb-connector-c/include -isystem ../contrib/mariadb-connector-c/libmariadb -isystem src/Server/grpc_protos -isystem ../contrib/grpc/include -isystem ../contrib/protobuf/src -isystem ../contrib/s2geometry/src -isystem ../contrib/AMQP-CPP/include -isystem ../contrib/AMQP-CPP -isystem ../contrib/libuv/include -isystem ../contrib/sqlite-amalgamation -isystem ../contrib/rocksdb/include -isystem ../contrib/libpqxx/include -isystem ../contrib/libpq -isystem ../contrib/libpq/include -isystem ../contrib/libstemmer_c/include -isystem ../contrib/wordnet-blast -isystem ../contrib/lemmagen-c/include -fdiagnostics-color=always -fsized-deallocation -fcoroutines  -pipe -mssse3 -msse4.1 -msse4.2 -mpclmul -mpopcnt -fasynchronous-unwind-tables -ffile-prefix-map=/build=. -falign-functions=32   -Wall  -Wextra -Wframe-larger-than=65536 -O2 -g -DNDEBUG -O3 -g -gdwarf-4  -fno-pie   -D OS_LINUX -Wbool-compare -Wcast-align -Wcast-qual -Wdelete-incomplete -Wdisabled-optimization -Wduplicated-cond -Wenum-compare -Winit-self -Wlogical-not-parentheses -Wlogical-op -Wmaybe-uninitialized -Wmisleading-indentation -Wmissing-include-dirs -Wnon-virtual-dtor -Wno-return-local-addr -Wodr -Wold-style-cast -Wplacement-new=2 -Wpointer-arith -Wredundant-decls -Wreorder -Wshadow -Wshift-negative-value -Wsized-deallocation -Wsizeof-array-argument -Wsizeof-pointer-memaccess -Wsuggest-override -Wswitch-bool -Wtautological-compare -Wtrampolines -Wunused -Wundef -Wvector-operation-performance -Wzero-as-null-pointer-constant -Wno-sequence-point -Wno-stringop-overflow -Wno-error=class-memaccess -Wno-error=free-nonheap-object -Wno-error=nonnull -Werror -nostdinc++ -pthread -std=gnu++2a -MD -MT programs/client/CMakeFiles/clickhouse-client-lib.dir/Client.cpp.o -MF programs/client/CMakeFiles/clickhouse-client-lib.dir/Client.cpp.o.d -o programs/client/CMakeFiles/clickhouse-client-lib.dir/Client.cpp.o -c ../programs/client/Client.cpp
May 06 08:00:06 g++-11: internal compiler error: Segmentation fault signal terminated program cc1plus
May 06 08:00:06 Please submit a full bug report,
May 06 08:00:06 with preprocessed source if appropriate.
May 06 08:00:06 See <file:///usr/share/doc/gcc-11/README.Bugs> for instructions.
May 06 08:00:08 [8079/10316] Building CXX object src/CMakeFiles/dbms.dir/Disks/IO/CachedReadBufferFromRemoteFS.cpp.o
May 06 08:00:08 [8080/10316] Building CXX object programs/static-files-disk-uploader/CMakeFiles/clickhouse-static-files-disk-uploader-lib.dir/static-files-disk-uploader.cpp.o
May 06 08:00:08 [8081/10316] Building CXX object src/CMakeFiles/dbms.dir/Disks/IO/ReadIndirectBufferFromRemoteFS.cpp.o
May 06 08:00:09 [8082/10316] Building CXX object src/CMakeFiles/clickhouse_common_io.dir/IO/WriteBufferFromAzureBlobStorage.cpp.o
May 06 08:00:09 [8083/10316] Building CXX object src/CMakeFiles/dbms.dir/Disks/IO/ReadBufferFromWebServer.cpp.o
May 06 08:00:09 [8084/10316] Building CXX object src/CMakeFiles/dbms.dir/AggregateFunctions/AggregateFunctionCount.cpp.o
May 06 08:00:10 [8085/10316] Building CXX object programs/keeper-converter/CMakeFiles/clickhouse-keeper-converter-lib.dir/KeeperConverter.cpp.o
May 06 08:00:10 [8086/10316] Building CXX object src/CMakeFiles/dbms.dir/Disks/IO/ReadBufferFromRemoteFSGather.cpp.o
May 06 08:00:11 [8087/10316] Building CXX object src/CMakeFiles/dbms.dir/Disks/IO/AsynchronousReadIndirectBufferFromRemoteFS.cpp.o
May 06 08:00:11 [8088/10316] Building CXX object programs/keeper/CMakeFiles/clickhouse-keeper-lib.dir/Keeper.cpp.o
May 06 08:00:12 [8089/10316] Building CXX object programs/compressor/CMakeFiles/clickhouse-compressor-lib.dir/Compressor.cpp.o
May 06 08:00:12 [8090/10316] Building CXX object src/CMakeFiles/dbms.dir/Storages/Hive/HiveSettings.cpp.o
May 06 08:00:12 [8091/10316] Building CXX object programs/git-import/CMakeFiles/clickhouse-git-import-lib.dir/git-import.cpp.o
May 06 08:00:16 [8092/10316] Building CXX object programs/install/CMakeFiles/clickhouse-install-lib.dir/Install.cpp.o
May 06 08:00:18 [8093/10316] Building CXX object programs/benchmark/CMakeFiles/clickhouse-benchmark-lib.dir/Benchmark.cpp.o
May 06 08:00:18 ninja: build stopped: subcommand failed.
```

**Comment by alexey-milovidov** [comment]
About this change - I don't care at all.
I don't think it improves anything.

I agree with @alesapin that style check should not be added.

There is zero value in this pull request.
We can merge it to avoid losing the work you've already done.

But as long as gcc cannot compile the code, we cannot merge this PR,
we need to either get rid of gcc (this is a valid option but this PR is a too weak motivation for it)
or to fix / close this PR.

**Comment by alexey-milovidov** [comment]
We can also use this PR to debug and fix our CI checks.
Let's use this PR as a playground for fixing unrelated check failures like
> Integration tests (release, actions) [1/2] — Invalid check_status.tsv 

and merge it when it is 100% green.

**Comment by rschu1ze** [comment]
Effort to create this PR was minimal (mostly search-and-replace). I did it to familiarize myself with CH's build and GitHub and I don't mind if it is merged or not. Also promise it will be the last one of the "trivial" PRs 😄

Agree with Alexey that we should not disable GCC because of this PR. While I like the readability of the new forms, hunting + working around compiler bugs is mostly wasted work ...

Therefore, I guess it makes most sense to keep the doc changes (style.md) and throw the rest away. I'd look into the integration test failures separately.

**Comment by alesapin** [comment]
FYI: https://github.com/ClickHouse/ClickHouse/pull/37018

**Pull request merged**
