### PR TITLE
weather data

### PR DESCRIPTION
**Pull request by gingerwizard**
Docs for weather noaa data

### Changelog category (leave one):

- Documentation (changelog entry is not required)

### CODE REVIEW

**Comment by robot-clickhouse-ci-2** [comment]
*This is an automated comment for commit 1dacfc53ff97fbab6ee349c6df27b3ad2f9df1e8 with description of existing statuses. It's updated for the latest CI running*

[❌ Click here](https://s3.amazonaws.com/clickhouse-test-reports/58767/1dacfc53ff97fbab6ee349c6df27b3ad2f9df1e8/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td><a href="https://github.com/ClickHouse/ClickHouse/blob/master/.github/PULL_REQUEST_TEMPLATE.md?plain=1">❌ failure</a></td></tr>
<tbody>
</table>

**Review by alexey-milovidov — APPROVED** [review]

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
@gingerwizard need to add exceptions to the spell check.

**Comment by alexey-milovidov** [comment]
Something is wrong with the spell check.

**Comment by alexey-milovidov** [comment]
@gingerwizard tests have failed.

**Comment by gingerwizard** [comment]
k i think ive fixed, apologies @alexey-milovidov i didnt see the previous comment.

**Comment by alexey-milovidov** [comment]
It's ridiculous, but the docs check is still failing...

**Comment by gingerwizard** [comment]
and we try again...

**Comment by gingerwizard** [comment]
Seems like we have some unrelated failures @alexey-milovidov spell-check issues finally resolved.

**Pull request merged**
