### PR TITLE
Update gcc build to gcc-12

### PR DESCRIPTION
**Pull request by alesapin**
### Changelog category (leave one):
- Build/Testing/Packaging Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Update gcc build (non release) to gcc-12.

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alesapin** [comment]
````May 08 11:50:40 + cmake --debug-trycompile --verbose=1 -DCMAKE_VERBOSE_MAKEFILE=1 -LA -DCMAKE_BUILD_TYPE=None -DSANITIZE= -DENABLE_CHECK_HEAVY_BUILDS=1 -DCMAKE_C_COMPILER=gcc-12 -DCMAKE_CXX_COMPILER=g++-12 ..
May 08 11:50:40 CMake Error: Unknown argument --verbose=1debug trycompile on```
bug in new cmake?

**Comment by rschu1ze** [comment]
CMake is invoked in file `docker/packager/binary/build.sh`

```
# Build everything                                                                                                                                                               
cmake --debug-trycompile --verbose=1 -DCMAKE_VERBOSE_MAKEFILE=1 -LA "-DCMAKE_BUILD_TYPE=$BUILD_TYPE" "-DSANITIZE=$SANITIZER" -DENABLE_CHECK_HEAVY_BUILDS=1 "${CMAKE_FLAGS[@]}" ..
```

In this PR, Ubuntu was upgraded from 20.4 to 21.4. This upgraded CMake from 3.16 to 3.22. On my local system, I have CMake 3.23 and it does *not* recognize --verbose:

```
~/repos/ClickHouse2/build (clangtidies) $ cmake --verbose -GNinja ..
CMake Error: Unknown argument --verbose
CMake Error: Run 'cmake --help' for all supported options.
```

This is strange but more or less equivalent to the error in the CI build. I was thinking maybe the CMake guys removed --verbose, so I checked the release notes of v 3.17-3.22 but they don't mention anything about --verbose. Can't tell if --verbose works on an old (3.16) CMake.

Anyways, we also pass `-DCMAKE_VERBOSE_MAKEFILE=1` which has the same effect as --verbose according to CMakes documentation:

```
--verbose, -v

    Enable verbose output - if supported - including the build commands to be executed.

    This option can be omitted if [VERBOSE](https://cmake.org/cmake/help/latest/envvar/VERBOSE.html#envvar:VERBOSE) environment variable or CMAKE_VERBOSE_MAKEFILE cached variable is set.
```

Source: https://cmake.org/cmake/help/v3.16/manual/cmake.1.html

So removing `--verbose` should do the trick.

**Comment by alesapin** [comment]
Perfect, new gcc is unable to build our libcxx:
```
May 09 09:58:27 prlimit --as=10000000000 --data=10000000000 --cpu=1000 /usr/bin/ccache /usr/bin/g++-12 -DLIBCXX_BUILDING_LIBCXXABI -DSTD_EXCEPTION_HAS_STACK_TRACE=1 -D_LIBCPP_BUILDING_LIBRARY -isystem /build/contrib/libcxx/include -isystem /build/contrib/libcxx/src -isystem /build/contrib/libcxxabi/include -isystem /build/contrib/libunwind/include -fdiagnostics-color=always -fsized-deallocation -fcoroutines  -pipe -mssse3 -msse4.1 -msse4.2 -mpclmul -mpopcnt -fasynchronous-unwind-tables -ffile-prefix-map=/build=. -falign-functions=32   -Wall  -O2 -g -DNDEBUG -O3 -g -gdwarf-4    -D OS_LINUX -nostdinc++ -w -std=gnu++20 -MD -MT contrib/libcxx-cmake/CMakeFiles/cxx.dir/__/libcxx/src/condition_variable.cpp.o -MF contrib/libcxx-cmake/CMakeFiles/cxx.dir/__/libcxx/src/condition_variable.cpp.o.d -o contrib/libcxx-cmake/CMakeFiles/cxx.dir/__/libcxx/src/condition_variable.cpp.o -c /build/contrib/libcxx/src/condition_variable.cpp
May 09 09:58:27 In file included from ../contrib/libcxx/include/system_error:151,
May 09 09:58:27                  from ../contrib/libcxx/include/__mutex_base:17,
May 09 09:58:27                  from ../contrib/libcxx/include/condition_variable:110,
May 09 09:58:27                  from ../contrib/libcxx/src/condition_variable.cpp:13:
May 09 09:58:27 ../contrib/libcxx/include/string:727:13: error: anonymous struct with base classes
May 09 09:58:27   727 |             : __padding<value_type>
May 09 09:58:27       |             ^
```

**Comment by alesapin** [comment]
https://gcc.gnu.org/gcc-12/changes.html

Anonymous structs with bases are now rejected: https://gcc.gnu.org/git/?p=gcc.git;a=commitdiff;h=3ead06c1

**Comment by alesapin** [comment]
Anonymous structs are quite popular in our libcxx:
```
    struct __short
    {
        value_type __data_[__min_cap];
        struct
            : __padding<value_type>
        {
            unsigned char __size_;
        };
    };
```

**Comment by alesapin** [comment]
Probably we have to update libcxx, because now they get rid of this: https://github.com/llvm/llvm-project/blob/main/libcxx/include/string#L736-L747.

**Comment by alesapin** [comment]
Lol: https://github.com/llvm/llvm-project/commit/c3d0205ee771edbee287b389699eab70b3670ecf

**Comment by alesapin** [comment]
@azat You're always one step ahead
image

**Comment by alesapin** [comment]
Depends on https://github.com/ClickHouse/libcxx/pull/13

**Comment by azat** [comment]
@alesapin AFAIR there were more issues, but let's see if the build will pass, maybe they were fixed when before releasing gcc 12

**Comment by alesapin** [comment]
```
May 09 11:11:59 ../contrib/libcxx/include/__memory/unique_ptr.h:503:26: error: '__chash' may be used uninitialized [-Werror=maybe-uninitialized]
May 09 11:11:59   503 |     return __ptr_.first()[__i];
May 09 11:11:59       |            ~~~~~~~~~~~~~~^
May 09 11:11:59 In file included from ../contrib/libcxx/include/unordered_map:520,
May 09 11:11:59                  from ../src/Core/SettingsFields.h:10,
May 09 11:11:59                  from ../src/Core/SettingsEnums.h:3,
May 09 11:11:59                  from ../src/Common/ThreadStatus.h:3,
May 09 11:11:59                  from ../src/Common/CurrentThread.h:4,
May 09 11:11:59                  from ../src/Common/logger_useful.h:8,
May 09 11:11:59                  from ../src/Common/scope_guard_safe.h:4,
May 09 11:11:59                  from ../programs/client/Client.cpp:8:
May 09 11:11:59 ../contrib/libcxx/include/__hash_table: In member function 'virtual void DB::Client::readArguments(int, char**, DB::ClientBase::Arguments&, std::__1::vector<std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >&, std::__1::vector<std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >&)':
May 09 11:11:59 ../contrib/libcxx/include/__hash_table:2066:12: note: '__chash' was declared here
May 09 11:11:59  2066 |     size_t __chash;
May 09 11:11:59       |            ^~~~~~~
```
Still not fixed: https://github.com/llvm/llvm-project/blame/main/libcxx/include/__hash_table#L2069?

**Comment by alesapin** [comment]
Best error message:
```
May 09 18:28:43 In member function 'std::__1::__function::__policy_func<_Rp(_ArgTypes ...)>& std::__1::__function::__policy_func<_Rp(_ArgTypes ...)>::operator=(std::__1::__function::__policy_func<_Rp(_ArgTypes ...)>&&) [with _Rp = std::__1::shared_ptr<Aws::Utils::Crypto::HMACFactory>; _ArgTypes = {}]',
May 09 18:28:43     inlined from 'std::__1::function<_Rp(_ArgTypes ...)>& std::__1::function<_Rp(_ArgTypes ...)>::operator=(std::__1::function<_Rp(_ArgTypes ...)>&&) [with _Rp = std::__1::shared_ptr<Aws::Utils::Crypto::HMACFactory>; _ArgTypes = {}]' at ../contrib/libcxx/include/__functional/function.h:1149:10,
May 09 18:28:43     inlined from 'Aws::CryptoOptions& Aws::CryptoOptions::operator=(Aws::CryptoOptions&&)' at ../contrib/aws/aws-cpp-sdk-core/include/aws/core/Aws.h:90:12,
May 09 18:28:43     inlined from 'Aws::SDKOptions& Aws::SDKOptions::operator=(Aws::SDKOptions&&)' at ../contrib/aws/aws-cpp-sdk-core/include/aws/core/Aws.h:190:12,
May 09 18:28:43     inlined from 'DB::S3::ClientFactory::ClientFactory()' at ../src/IO/S3Common.cpp:693:39:
May 09 18:28:43 ../contrib/libcxx/include/__functional/function.h:821:9: error: '<unnamed>.Aws::SDKOptions::cryptoOptions.Aws::CryptoOptions::sha256HMACFactory_create_fn.std::__1::function<std::__1::shared_ptr<Aws::Utils::Crypto::HMACFactory>()>::__f_.std::__1::__function::__policy_func<std::__1::shared_ptr<Aws::Utils::Crypto::HMACFactory>()>::__buf_' is used uninitialized [-Werror=uninitialized]
May 09 18:28:43   821 |         __buf_ = __f.__buf_;
May 09 18:28:43       |         ^~~~~~
May 09 18:28:43 ../src/IO/S3Common.cpp: In constructor 'DB::S3::ClientFactory::ClientFactory()':
May 09 18:28:43 ../src/IO/S3Common.cpp:693:39: note: '<anonymous>' declared here
May 09 18:28:43   693 |         aws_options = Aws::SDKOptions{};
```

**Comment by alexey-milovidov** [comment]
I see that gcc is removed from the CI, so this PR is no longer relevant.

**Comment by rschu1ze** [comment]
Hm, what is GCCs status then?
a) GCC is *officially unsupported*
b) GCC is *without official support*, i.e. "use it at your own risk" similar to AppleClang and Darwin.

a) means that a ton of ugly special cases can be removed from the build scripts. Also, portability of code between compilers is IMHO not such a big concern anymore than 5 years ago as both Clang's and GCC's C++20 support is very good. So I would vote for a).

**Comment by alesapin** [comment]
Installed gcc-12 locally yesterday -- will try to fix when I'll have time.

**Comment by alesapin** [comment]
AWS SDK builds successfully on my GCC version. Probably we have some not-so-fresh versions in ubuntu...

**Comment by Algunenano** [comment]
> AWS SDK builds successfully on my GCC version.

Tested locally with `gcc version 12.1.0 (GCC)` and it fails with the same message as the CI:
```
In member function ‘std::__1::__function::__policy_func<_Rp(_ArgTypes ...)>& std::__1::__function::__policy_func<_Rp(_ArgTypes ...)>::operator=(std::__1::__function::__policy_func<_Rp(_ArgTypes ...)>&&) [with _Rp = std::__1::shared_ptr<Aws::Utils::Logging::LogSystemInterface>; _ArgTypes = {}]’,
    inlined from ‘std::__1::function<_Rp(_ArgTypes ...)>& std::__1::function<_Rp(_ArgTypes ...)>::operator=(std::__1::function<_Rp(_ArgTypes ...)>&&) [with _Rp = std::__1::shared_ptr<Aws::Utils::Logging::LogSystemInterface>; _ArgTypes = {}]’ at /mnt/ch/ClickHouse/contrib/libcxx/include/__functional/function.h:1149:10,
    inlined from ‘Aws::LoggingOptions& Aws::LoggingOptions::operator=(Aws::LoggingOptions&&)’ at /mnt/ch/ClickHouse/contrib/aws/aws-cpp-sdk-core/include/aws/core/Aws.h:22:12,
    inlined from ‘Aws::SDKOptions& Aws::SDKOptions::operator=(Aws::SDKOptions&&)’ at /mnt/ch/ClickHouse/contrib/aws/aws-cpp-sdk-core/include/aws/core/Aws.h:190:12,
    inlined from ‘DB::S3::ClientFactory::ClientFactory()’ at /mnt/ch/ClickHouse/src/IO/S3Common.cpp:693:39:
/mnt/ch/ClickHouse/contrib/libcxx/include/__functional/function.h:821:9: error: ‘<unnamed>.Aws::SDKOptions::loggingOptions.Aws::LoggingOptions::logger_create_fn.std::__1::function<std::__1::shared_ptr<Aws::Utils::Logging::LogSystemInterface>()>::__f_.std::__1::__function::__policy_func<std::__1::shared_ptr<Aws::Utils::Logging::LogSystemInterface>()>::__buf_’ is used uninitialized [-Werror=uninitialized]
  821 |         __buf_ = __f.__buf_;
```

I don't see any newer tag upstream. OTOH, if you remove `-Werror` it builds but obviously that's plainly wrong.

**Comment by alexey-milovidov** [comment]
I don't mind removing gcc altogether.
It makes sense because we don't test gcc builds for correctness, but the possibility to build with gcc can mislead developers.

**Comment by alesapin** [comment]
```
gcc --version   
gcc (GCC) 12.1.0
Copyright (C) 2022 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
```
➜  build git:(update_to_gcc_12) ✗ ninja clickhouse
[0/2] Re-checking globbed directories...
[1/1] cd /home/alesapin/code/cpp/ClickHouse/build/contrib/avro-cmake && /usr/bin/cmake -E make_directory /home/alesapin/code/cpp/ClickHouse/build/...eate_symlink /home/alesapin/code/cpp/ClickHouse/contrib/avro/lang/c++/api /home/alesapin/code/cpp/ClickHouse/build/contrib/avro-cmake/include/avro
```
```
alesapin-workstation :) select * from system.build_options;

SELECT *
FROM system.build_options

Query id: bec2c21b-990f-48c9-a29c-b2351db63030

┌─name──────────────────────┬─value───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ VERSION_FULL              │ ClickHouse 22.6.1.1                                                                                                                                                                                                                 │
│ VERSION_DESCRIBE          │ v22.6.1.1-testing                                                                                                                                                                                                                   │
│ VERSION_INTEGER           │ 22006001                                                                                                                                                                                                                            │
│ SYSTEM                    │ Linux                                                                                                                                                                                                                               │
│ VERSION_GITHASH           │ df0cb0620985eb5ec59760cc76f7736e5b6209bb                                                                                                                                                                                            │
│ VERSION_REVISION          │ 54463                                                                                                                                                                                                                               │
│ VERSION_DATE              │                                                                                                                                                                                                                                     │
│ BUILD_TYPE                │ Debug                                                                                                                                                                                                                               │
│ SYSTEM_PROCESSOR          │ x86_64                                                                                                                                                                                                                              │
│ CMAKE_VERSION             │ 3.23.1                                                                                                                                                                                                                              │
│ C_COMPILER                │ /usr/bin/gcc                                                                                                                                                                                                                        │
│ C_COMPILER_VERSION        │ 12.1.0                                                                                                                                                                                                                              │
│ CXX_COMPILER              │ /usr/bin/g++                                                                                                                                                                                                                        │
│ CXX_COMPILER_VERSION      │ 12.1.0                                                                                                                                                                                                                              │
│ C_FLAGS                   │  -fdiagnostics-color=always  -pipe -mssse3 -msse4.1 -msse4.2 -mpclmul -mpopcnt -fasynchronous-unwind-tables -falign-functions=32  -g -O0 -g -gdwarf-4 -fno-inline                                                                   │
│ CXX_FLAGS                 │  -fdiagnostics-color=always -fsized-deallocation -fcoroutines  -pipe -mssse3 -msse4.1 -msse4.2 -mpclmul -mpopcnt -fasynchronous-unwind-tables -falign-functions=32 -Wall -Wextra -g -O0 -g -gdwarf-4 -fno-inline  -D_LIBCPP_DEBUG=0 │
│ LINK_FLAGS                │  -fuse-ld=lld -rdynamic -Wl,--gdb-index -Wl,--build-id=sha1 -no-pie -Wl,-no-pie                                                                                                                                                     │
│ BUILD_COMPILE_DEFINITIONS │                                                                                                                                                                                                                                     │
│ STATIC                    │ ON                                                                                                                                                                                                                                  │
│ SPLIT_BINARY              │                                                                                                                                                                                                                                     │
│ USE_EMBEDDED_COMPILER     │ 1                                                                                                                                                                                                                                   │
│ USE_GLIBC_COMPATIBILITY   │ ON                                                                                                                                                                                                                                  │
│ USE_JEMALLOC              │ ON                                                                                                                                                                                                                                  │
│ USE_UNWIND                │ ON                                                                                                                                                                                                                                  │
│ USE_ICU                   │ 1                                                                                                                                                                                                                                   │
│ USE_H3                    │ 1                                                                                                                                                                                                                                   │
│ USE_MYSQL                 │ 1                                                                                                                                                                                                                                   │
│ USE_RDKAFKA               │ 1                                                                                                                                                                                                                                   │
│ USE_CAPNP                 │ 1                                                                                                                                                                                                                                   │
│ USE_BASE64                │ 1                                                                                                                                                                                                                                   │
│ USE_HDFS                  │ 1                                                                                                                                                                                                                                   │
│ USE_SNAPPY                │ 1                                                                                                                                                                                                                                   │
│ USE_PARQUET               │ 1                                                                                                                                                                                                                                   │
│ USE_PROTOBUF              │ 1                                                                                                                                                                                                                                   │
│ USE_BROTLI                │ 1                                                                                                                                                                                                                                   │
│ USE_SSL                   │ 1                                                                                                                                                                                                                                   │
│ USE_HYPERSCAN             │ ON                                                                                                                                                                                                                                  │
│ USE_SIMDJSON              │ 1                                                                                                                                                                                                                                   │
│ USE_ODBC                  │ 1                                                                                                                                                                                                                                   │
│ USE_GRPC                  │ 1                                                                                                                                                                                                                                   │
│ USE_LDAP                  │ 1                                                                                                                                                                                                                                   │
│ TZDATA_VERSION            │ 2022a                                                                                                                                                                                                                               │
│ USE_KRB5                  │ 1                                                                                                                                                                                                                                   │
│ USE_FILELOG               │ 1                                                                                                                                                                                                                                   │
│ USE_BZIP2                 │ 1                                                                                                                                                                                                                                   │
│ USE_AMQPCPP               │ 1                                                                                                                                                                                                                                   │
│ USE_ROCKSDB               │ 1                                                                                                                                                                                                                                   │
│ USE_NURAFT                │ 1                                                                                                                                                                                                                                   │
│ USE_NLP                   │ 1                                                                                                                                                                                                                                   │
│ USE_SQLITE                │ 1                                                                                                                                                                                                                                   │
│ USE_LIBPQXX               │ 1                                                                                                                                                                                                                                   │
│ USE_AZURE_BLOB_STORAGE    │ 1                                                                                                                                                                                                                                   │
│ USE_AWS_S3                │ 1                                                                                                                                                                                                                                   │
│ USE_CASSANDRA             │ 1                                                                                                                                                                                                                                   │
│ USE_YAML_CPP              │ 1                                                                                                                                                                                                                                   │
│ CLICKHOUSE_SPLIT_BINARY   │                                                                                                                                                                                                                                     │
│ USE_SENTRY                │ 1                                                                                                                                                                                                                                   │
│ USE_DATASKETCHES          │ 1                                                                                                                                                                                                                                   │
│ USE_AVRO                  │ 1                                                                                                                                                                                                                                   │
│ USE_ARROW                 │ 1                                                                                                                                                                                                                                   │
│ USE_ORC                   │ 1                                                                                                                                                                                                                                   │
│ USE_MSGPACK               │ 1                                                                                                                                                                                                                                   │
│ GIT_HASH                  │ 200f6bd0ede121e1bf0e530a4dc45e7331751362                                                                                                                                                                                            │
│ GIT_BRANCH                │ update_to_gcc_12                                                                                                                                                                                                                    │
│ GIT_DATE                  │ 2022-05-29 13:16:28 +0000                                                                                                                                                                                                           │
│ GIT_COMMIT_SUBJECT        │ Merge branch 'master' into update_to_gcc_12                                                                                                                                                                                         │
└───────────────────────────┴─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

66 rows in set. Elapsed: 0.007 sec. 
```

**Comment by alesapin** [comment]
Tried release build and looks like it's broken (bugs in gcc). But it's still find several strange lines. I think it's better to make gcc build debug only for now.

**Comment by alesapin** [comment]
We are not ready to ubuntu 22.04 and gcc-12 cannot compile our code in release. Will close this PR.

**Comment by alexey-milovidov** [comment]
Ok, but why we are not ready for Ubuntu 22.04?

**Pull request closed without merging**
