### PR TITLE
Inline threshold optimizations

### PR DESCRIPTION
**Pull request by danlark1**
Changelog category (leave one):
- Performance Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
First commit is to increase the inline threshold.
Next commits will improve queries by inlining for those who have shown better performance.
This way we will not increase the compile time and binary size and optimize the program.

### CODE REVIEW

**Comment by kitaisreal** [comment]
@Mergifyio update

**Comment by danlark1** [comment]
https://github.com/Mergifyio update

**Comment by alexey-milovidov** [comment]
```
2022-02-12 14:20:10 prlimit --as=10000000000 --data=5000000000 --cpu=1000 /usr/bin/ccache /usr/bin/clang++-13 --target=x86_64-linux-gnu --sysroot=/build/cmake/linux/../../contrib/sysroot/linux-x86_64/x86_64-linux-gnu/libc  -DAWS_SDK_VERSION_MAJOR=1 -DAWS_SDK_VERSION_MINOR=7 -DAWS_SDK_VERSION_PATCH=231 -DBOOST_ASIO_STANDALONE=1 -DCARES_STATICLIB -DENABLE_OPENSSL_ENCRYPTION -DHAS_RESERVED_IDENTIFIER -DPOCO_ENABLE_CPP11 -DPOCO_HAVE_FD_EPOLL -DPOCO_OS_FAMILY_UNIX -DSTD_EXCEPTION_HAS_STACK_TRACE=1 -DUNALIGNED_OK -DWITH_COVERAGE=0 -DWITH_GZFILEOP -DX86_64 -DZLIB_COMPAT -Iincludes/configs -I../base/glibc-compatibility/memcpy -I../src -Isrc -Isrc/Core/include -I../base/base/.. -Ibase/base/.. -I../contrib/cctz/include -I../base/pcg-random/. -I../contrib/miniselect/include -I../contrib/zstd/lib -I../src/Common/mysqlxx/. -Icontrib/grpc/third_party/cares/cares -I../contrib/grpc/third_party/cares/cares -isystem ../contrib/libcxx/include -isystem ../contrib/libcxxabi/include -isystem ../contrib/libunwind/include -isystem ../contrib/llvm/llvm/include -isystem contrib/llvm/llvm/include -isystem ../contrib/abseil-cpp -isystem ../contrib/croaring/cpp -isystem ../contrib/croaring/include -isystem ../contrib/cityhash102/include -isystem ../contrib/boost -isystem ../contrib/poco/Net/include -isystem ../contrib/poco/Foundation/include -isystem ../contrib/poco/NetSSL_OpenSSL/include -isystem ../contrib/poco/Crypto/include -isystem ../contrib/boringssl/include -isystem ../contrib/poco/Util/include -isystem ../contrib/poco/JSON/include -isystem ../contrib/poco/XML/include -isystem ../contrib/replxx/include -isystem ../contrib/fmtlib-cmake/../fmtlib/include -isystem ../contrib/magic_enum/include -isystem ../contrib/double-conversion -isystem ../contrib/dragonbox/include -isystem ../contrib/re2 -isystem contrib/re2-cmake -isystem ../contrib/zlib-ng -isystem contrib/zlib-ng-cmake -isystem ../contrib/pdqsort -isystem ../contrib/xz/src/liblzma/api -isystem ../contrib/aws-c-common/include -isystem ../contrib/aws-c-event-stream/include -isystem ../contrib/aws/aws-cpp-sdk-s3/include -isystem ../contrib/aws/aws-cpp-sdk-core/include -isystem contrib/aws-s3-cmake/include -isystem ../contrib/azure/sdk/core/azure-core/inc -isystem ../contrib/azure/sdk/identity/azure-identity/inc -isystem ../contrib/azure/sdk/storage/azure-storage-common/inc -isystem ../contrib/azure/sdk/storage/azure-storage-blobs/inc -isystem ../contrib/snappy -isystem contrib/snappy-cmake -isystem ../contrib/msgpack-c/include -isystem ../contrib/fast_float/include -isystem ../contrib/NuRaft/include -isystem contrib/mariadb-connector-c-cmake/include-public -isystem ../contrib/mariadb-connector-c/include -isystem ../contrib/mariadb-connector-c/libmariadb -isystem src/Server/grpc_protos -isystem ../contrib/grpc/include -isystem ../contrib/protobuf/src -isystem ../contrib/s2geometry/src -isystem ../contrib/AMQP-CPP/include -isystem ../contrib/AMQP-CPP -isystem ../contrib/libuv/include -isystem ../contrib/sqlite-amalgamation -isystem ../contrib/rocksdb/include -isystem ../contrib/libpqxx/include -isystem ../contrib/libpq -isystem ../contrib/libpq/include -isystem ../contrib/libstemmer_c/include -isystem ../contrib/wordnet-blast -isystem ../contrib/lemmagen-c/include -isystem ../contrib/consistent-hashing -isystem ../contrib/datasketches-cpp/common/include -isystem ../contrib/datasketches-cpp/theta/include --gcc-toolchain=/build/cmake/linux/../../contrib/sysroot/linux-x86_64 --gcc-toolchain=/build/cmake/linux/../../contrib/sysroot/linux-x86_64 -std=c++20  -g -fno-omit-frame-pointer -DSANITIZER -fsanitize=address -fsanitize-address-use-after-scope -fdiagnostics-color=always -Xclang -fuse-ctor-homing -fsized-deallocation  -gdwarf-aranges -pipe -mssse3 -msse4.1 -msse4.2 -mpclmul -mpopcnt -fasynchronous-unwind-tables -ffile-prefix-map=/build=. -falign-functions=32   -Wall -Wno-unused-command-line-argument  -fdiagnostics-absolute-paths -fstrict-vtable-pointers -fexperimental-new-pass-manager -mllvm -inline-threshold=1000 -Wextra -Wpedantic -Wno-vla-extension -Wno-zero-length-array -Wno-c11-extensions -Weverything -Wno-c++98-compat-pedantic -Wno-c++98-compat -Wno-c99-extensions -Wno-conversion -Wno-ctad-maybe-unsupported -Wno-deprecated-dynamic-exception-spec -Wno-disabled-macro-expansion -Wno-documentation-unknown-command -Wno-double-promotion -Wno-exit-time-destructors -Wno-float-equal -Wno-global-constructors -Wno-missing-prototypes -Wno-missing-variable-declarations -Wno-nested-anon-types -Wno-packed -Wno-padded -Wno-shift-sign-overflow -Wno-sign-conversion -Wno-switch-enum -Wno-undefined-func-template -Wno-unused-template -Wno-vla -Wno-weak-template-vtables -Wno-weak-vtables -O2 -g -DNDEBUG -O3  -fno-pie   -D OS_LINUX -Werror -nostdinc++ -std=gnu++2a -MD -MT src/AggregateFunctions/CMakeFiles/clickhouse_aggregate_functions.dir/AggregateFunctionSumMap.cpp.o -MF src/AggregateFunctions/CMakeFiles/clickhouse_aggregate_functions.dir/AggregateFunctionSumMap.cpp.o.d -o src/AggregateFunctions/CMakeFiles/clickhouse_aggregate_functions.dir/AggregateFunctionSumMap.cpp.o -c ../src/AggregateFunctions/AggregateFunctionSumMap.cpp
2022-02-12 14:20:10 LLVM ERROR: out of memory
2022-02-12 14:20:10 Allocation failed
2022-02-12 14:20:10 PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace, preprocessed source, and associated run script.
2022-02-12 14:20:10 Stack dump:
2022-02-12 14:20:10 0.	Program arguments: /usr/bin/clang++-13 --target=x86_64-linux-gnu --sysroot=../contrib/sysroot/linux-x86_64/x86_64-linux-gnu/libc --gcc-toolchain=/build/cmake/linux/../../contrib/sysroot/linux-x86_64 --gcc-toolchain=/build/cmake/linux/../../contrib/sysroot/linux-x86_64 -std=c++20 -g -fno-omit-frame-pointer -fsanitize=address -fsanitize-address-use-after-scope -fdiagnostics-color=always -Xclang -fuse-ctor-homing -fsized-deallocation -gdwarf-aranges -pipe -mssse3 -msse4.1 -msse4.2 -mpclmul -mpopcnt -fasynchronous-unwind-tables -ffile-prefix-map=/build=. -falign-functions=32 -Wall -Wno-unused-command-line-argument -fdiagnostics-absolute-paths -fstrict-vtable-pointers -fexperimental-new-pass-manager -mllvm -inline-threshold=1000 -Wextra -Wpedantic -Wno-vla-extension -Wno-zero-length-array -Wno-c11-extensions -Weverything -Wno-c++98-compat-pedantic -Wno-c++98-compat -Wno-c99-extensions -Wno-conversion -Wno-ctad-maybe-unsupported -Wno-deprecated-dynamic-exception-spec -Wno-disabled-macro-expansion -Wno-documentation-unknown-command -Wno-double-promotion -Wno-exit-time-destructors -Wno-float-equal -Wno-global-constructors -Wno-missing-prototypes -Wno-missing-variable-declarations -Wno-nested-anon-types -Wno-packed -Wno-padded -Wno-shift-sign-overflow -Wno-sign-conversion -Wno-switch-enum -Wno-undefined-func-template -Wno-unused-template -Wno-vla -Wno-weak-template-vtables -Wno-weak-vtables -O2 -g -O3 -fno-pie -std=gnu++2a -Werror -DAWS_SDK_VERSION_MAJOR=1 -DAWS_SDK_VERSION_MINOR=7 -DAWS_SDK_VERSION_PATCH=231 -DBOOST_ASIO_STANDALONE=1 -DCARES_STATICLIB -DENABLE_OPENSSL_ENCRYPTION -DHAS_RESERVED_IDENTIFIER -DPOCO_ENABLE_CPP11 -DPOCO_HAVE_FD_EPOLL -DPOCO_OS_FAMILY_UNIX -DSTD_EXCEPTION_HAS_STACK_TRACE=1 -DUNALIGNED_OK -DWITH_COVERAGE=0 -DWITH_GZFILEOP -DX86_64 -DZLIB_COMPAT -Iincludes/configs -I../base/glibc-compatibility/memcpy -I../src -Isrc -Isrc/Core/include -I../base/base/.. -Ibase/base/.. -I../contrib/cctz/include -I../base/pcg-random/. -I../contrib/miniselect/include -I../contrib/zstd/lib -I../src/Common/mysqlxx/. -Icontrib/grpc/third_party/cares/cares -I../contrib/grpc/third_party/cares/cares -isystem ../contrib/libcxx/include -isystem ../contrib/libcxxabi/include -isystem ../contrib/libunwind/include -isystem ../contrib/llvm/llvm/include -isystem contrib/llvm/llvm/include -isystem ../contrib/abseil-cpp -isystem ../contrib/croaring/cpp -isystem ../contrib/croaring/include -isystem ../contrib/cityhash102/include -isystem ../contrib/boost -isystem ../contrib/poco/Net/include -isystem ../contrib/poco/Foundation/include -isystem ../contrib/poco/NetSSL_OpenSSL/include -isystem ../contrib/poco/Crypto/include -isystem ../contrib/boringssl/include -isystem ../contrib/poco/Util/include -isystem ../contrib/poco/JSON/include -isystem ../contrib/poco/XML/include -isystem ../contrib/replxx/include -isystem ../contrib/fmtlib-cmake/../fmtlib/include -isystem ../contrib/magic_enum/include -isystem ../contrib/double-conversion -isystem ../contrib/dragonbox/include -isystem ../contrib/re2 -isystem contrib/re2-cmake -isystem ../contrib/zlib-ng -isystem contrib/zlib-ng-cmake -isystem ../contrib/pdqsort -isystem ../contrib/xz/src/liblzma/api -isystem ../contrib/aws-c-common/include -isystem ../contrib/aws-c-event-stream/include -isystem ../contrib/aws/aws-cpp-sdk-s3/include -isystem ../contrib/aws/aws-cpp-sdk-core/include -isystem contrib/aws-s3-cmake/include -isystem ../contrib/azure/sdk/core/azure-core/inc -isystem ../contrib/azure/sdk/identity/azure-identity/inc -isystem ../contrib/azure/sdk/storage/azure-storage-common/inc -isystem ../contrib/azure/sdk/storage/azure-storage-blobs/inc -isystem ../contrib/snappy -isystem contrib/snappy-cmake -isystem ../contrib/msgpack-c/include -isystem ../contrib/fast_float/include -isystem ../contrib/NuRaft/include -isystem contrib/mariadb-connector-c-cmake/include-public -isystem ../contrib/mariadb-connector-c/include -isystem ../contrib/mariadb-connector-c/libmariadb -isystem src/Server/grpc_protos -isystem ../contrib/grpc/include -isystem ../contrib/protobuf/src -isystem ../contrib/s2geometry/src -isystem ../contrib/AMQP-CPP/include -isystem ../contrib/AMQP-CPP -isystem ../contrib/libuv/include -isystem ../contrib/sqlite-amalgamation -isystem ../contrib/rocksdb/include -isystem ../contrib/libpqxx/include -isystem ../contrib/libpq -isystem ../contrib/libpq/include -isystem ../contrib/libstemmer_c/include -isystem ../contrib/wordnet-blast -isystem ../contrib/lemmagen-c/include -isystem ../contrib/consistent-hashing -isystem ../contrib/datasketches-cpp/common/include -isystem ../contrib/datasketches-cpp/theta/include -DSANITIZER -DNDEBUG -D OS_LINUX -nostdinc++ -c -o src/AggregateFunctions/CMakeFiles/clickhouse_aggregate_functions.dir/AggregateFunctionSumMap.cpp.o ../src/AggregateFunctions/AggregateFunctionSumMap.cpp
2022-02-12 14:20:10 1.	<eof> parser at end of file
2022-02-12 14:20:10 2.	Code generation
2022-02-12 14:20:10 Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
2022-02-12 14:20:10 /lib/x86_64-linux-gnu/libLLVM-13.so.1(_ZN4llvm3sys15PrintStackTraceERNS_11raw_ostreamEi+0x31)[0x7faa12e55791]
2022-02-12 14:20:10 /lib/x86_64-linux-gnu/libLLVM-13.so.1(_ZN4llvm3sys17RunSignalHandlersEv+0x50)[0x7faa12e53940]
2022-02-12 14:20:10 /lib/x86_64-linux-gnu/libLLVM-13.so.1(_ZN4llvm3sys15CleanupOnSignalEm+0x100)[0x7faa12e54e20]
2022-02-12 14:20:10 /lib/x86_64-linux-gnu/libLLVM-13.so.1(+0xcd9035)[0x7faa12d99035]
2022-02-12 14:20:10 /lib/x86_64-linux-gnu/libpthread.so.0(+0x153c0)[0x7faa1b71d3c0]
2022-02-12 14:20:10 /lib/x86_64-linux-gnu/libc.so.6(gsignal+0xcb)[0x7faa11b8e18b]
2022-02-12 14:20:10 /lib/x86_64-linux-gnu/libc.so.6(abort+0x12b)[0x7faa11b6d859]
2022-02-12 14:20:10 /lib/x86_64-linux-gnu/libLLVM-13.so.1(_ZN4llvm22report_bad_alloc_errorEPKcb+0x9e)[0x7faa12da5c7e]
2022-02-12 14:20:10 /lib/x86_64-linux-gnu/libLLVM-13.so.1(+0xce5cd2)[0x7faa12da5cd2]
2022-02-12 14:20:10 /lib/x86_64-linux-gnu/libstdc++.so.6(_Znwm+0x33)[0x7faa11f53dc3]
2022-02-12 14:20:10 /lib/x86_64-linux-gnu/libLLVM-13.so.1(_ZNSt6vectorIN4llvm18ELFRelocationEntryESaIS1_EE17_M_realloc_insertIJRKS1_EEEvN9__gnu_cxx17__normal_iteratorIPS1_S3_EEDpOT_+0x98)[0x7faa141464a8]
2022-02-12 14:20:10 /lib/x86_64-linux-gnu/libLLVM-13.so.1(+0x2085169)[0x7faa14145169]
2022-02-12 14:20:10 /lib/x86_64-linux-gnu/libLLVM-13.so.1(_ZN4llvm11MCAssembler6layoutERNS_11MCAsmLayoutE+0x4f8)[0x7faa1415c2f8]
2022-02-12 14:20:10 /lib/x86_64-linux-gnu/libLLVM-13.so.1(_ZN4llvm11MCAssembler6FinishEv+0x37)[0x7faa1415c517]
2022-02-12 14:20:10 /lib/x86_64-linux-gnu/libLLVM-13.so.1(_ZN4llvm13MCELFStreamer10finishImplEv+0xcc)[0x7faa14178ddc]
2022-02-12 14:20:10 /lib/x86_64-linux-gnu/libLLVM-13.so.1(_ZN4llvm10MCStreamer6FinishENS_5SMLocE+0x57)[0x7faa141979d7]
2022-02-12 14:20:10 /lib/x86_64-linux-gnu/libLLVM-13.so.1(_ZN4llvm10AsmPrinter14doFinalizationERNS_6ModuleE+0x16c1)[0x7faa13602dc1]
2022-02-12 14:20:10 /lib/x86_64-linux-gnu/libLLVM-13.so.1(_ZN4llvm13FPPassManager14doFinalizationERNS_6ModuleE+0x31)[0x7faa12f8fb21]
2022-02-12 14:20:10 /lib/x86_64-linux-gnu/libLLVM-13.so.1(_ZN4llvm6legacy15PassManagerImpl3runERNS_6ModuleE+0x4a2)[0x7faa12f8a5f2]
2022-02-12 14:20:10 /lib/x86_64-linux-gnu/libclang-cpp.so.13(+0x195c6de)[0x7faa199516de]
2022-02-12 14:20:10 /lib/x86_64-linux-gnu/libclang-cpp.so.13(_ZN5clang17EmitBackendOutputERNS_17DiagnosticsEngineERKNS_19HeaderSearchOptionsERKNS_14CodeGenOptionsERKNS_13TargetOptionsERKNS_11LangOptionsEN4llvm9StringRefEPNSE_6ModuleENS_13BackendActionESt10unique_ptrINSE_17raw_pwrite_streamESt14default_deleteISK_EE+0x1264)[0x7faa1994b6d4]
2022-02-12 14:20:10 /lib/x86_64-linux-gnu/libclang-cpp.so.13(+0x1c1aa60)[0x7faa19c0fa60]
2022-02-12 14:20:10 /lib/x86_64-linux-gnu/libclang-cpp.so.13(_ZN5clang8ParseASTERNS_4SemaEbb+0x244)[0x7faa18be5854]
2022-02-12 14:20:10 /lib/x86_64-linux-gnu/libclang-cpp.so.13(_ZN5clang13CodeGenAction13ExecuteActionEv+0xa1)[0x7faa19c0c251]
2022-02-12 14:20:10 /lib/x86_64-linux-gnu/libclang-cpp.so.13(_ZN5clang14FrontendAction7ExecuteEv+0x56)[0x7faa1a450726]
2022-02-12 14:20:10 /lib/x86_64-linux-gnu/libclang-cpp.so.13(_ZN5clang16CompilerInstance13ExecuteActionERNS_14FrontendActionE+0x2c6)[0x7faa1a3cb106]
2022-02-12 14:20:10 /lib/x86_64-linux-gnu/libclang-cpp.so.13(_ZN5clang25ExecuteCompilerInvocationEPNS_16CompilerInstanceE+0x696)[0x7faa1a4c3596]
2022-02-12 14:20:10 /usr/bin/clang++-13(_Z8cc1_mainN4llvm8ArrayRefIPKcEES2_Pv+0x929)[0x413189]
2022-02-12 14:20:10 /usr/bin/clang++-13[0x4111a6]
2022-02-12 14:20:10 /lib/x86_64-linux-gnu/libclang-cpp.so.13(+0x20d4012)[0x7faa1a0c9012]
2022-02-12 14:20:10 /lib/x86_64-linux-gnu/libLLVM-13.so.1(_ZN4llvm20CrashRecoveryContext9RunSafelyENS_12function_refIFvvEEE+0xdd)[0x7faa12d98d8d]
2022-02-12 14:20:10 /lib/x86_64-linux-gnu/libclang-cpp.so.13(_ZNK5clang6driver10CC1Command7ExecuteEN4llvm8ArrayRefINS2_8OptionalINS2_9StringRefEEEEEPNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPb+0x140)[0x7faa1a0c88f0]
2022-02-12 14:20:10 /lib/x86_64-linux-gnu/libclang-cpp.so.13(_ZNK5clang6driver11Compilation14ExecuteCommandERKNS0_7CommandERPS3_+0x190)[0x7faa1a09c2a0]
2022-02-12 14:20:10 /lib/x86_64-linux-gnu/libclang-cpp.so.13(_ZNK5clang6driver11Compilation11ExecuteJobsERKNS0_7JobListERN4llvm15SmallVectorImplISt4pairIiPKNS0_7CommandEEEE+0x8a)[0x7faa1a09c68a]
2022-02-12 14:20:10 /lib/x86_64-linux-gnu/libclang-cpp.so.13(_ZN5clang6driver6Driver18ExecuteCompilationERNS0_11CompilationERN4llvm15SmallVectorImplISt4pairIiPKNS0_7CommandEEEE+0xfe)[0x7faa1a0b186e]
2022-02-12 14:20:10 /usr/bin/clang++-13(main+0x2473)[0x4109e3]
2022-02-12 14:20:10 /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3)[0x7faa11b6f0b3]
2022-02-12 14:20:10 /usr/bin/clang++-13(_start+0x2e)[0x40e23e]
2022-02-12 14:20:10 clang: error: clang frontend command failed with exit code 134 (use -v to see invocation)
2022-02-12 14:20:10 Ubuntu clang version 13.0.1-++20220120110924+75e33f71c2da-1~exp1~20220120231001.58
2022-02-12 14:20:10 Target: x86_64-unknown-linux-gnu
2022-02-12 14:20:10 Thread model: posix
2022-02-12 14:20:10 InstalledDir: /usr/bin
2022-02-12 14:20:10 clang: note: diagnostic msg: 
2022-02-12 14:20:10 ********************
2022-02-12 14:20:10 
2022-02-12 14:20:10 PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
2022-02-12 14:20:10 Preprocessed source(s) and associated run script(s) are located at:
2022-02-12 14:20:10 clang: note: diagnostic msg: /tmp/AggregateFunctionSumMap-a8a9ca.cpp
2022-02-12 14:20:10 clang: note: diagnostic msg: /tmp/AggregateFunctionSumMap-a8a9ca.sh
2022-02-12 14:20:10 clang: note: diagnostic msg: 
2022-02-12 14:20:10 
2022-02-12 14:20:10 ********************
```

**Comment by alexey-milovidov** [comment]
Compilation of some translation units exceeded 5 GB.

**Review by alexey-milovidov — APPROVED** [review]
The changes LGTM.
Inlining SipHash looks very reasonable.

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
gcc cannot inline one of the functions.

@danlark1 Please vote here if we should remove support for gcc altogether.

**Comment by danlark1** [comment]
Force inline in src/DataTypes/DataTypesDecimal.h is kinda important for DecimalAggregation to remove division, see comment above

If GCC cannot build it, I guess nothing we can do, or suppress the warning

I am very much in favor of removing GCC completely, however, this might be bad for users who build ClickHouse as we pose more and more restrictions on them. And GCC might give opportunities to build for weird architectures

**Comment by Algunenano** [comment]
> gcc cannot inline one of the functions

I don't know if it's the same issue, but there are places were `ALWAYS_INLINE` had to be accompanied by `inline` to avoid similar errors.

**Comment by alexey-milovidov** [comment]
https://s3.amazonaws.com/clickhouse-test-reports/34544/8e8faa3180db605995f9653b0910434875ab90ba/stress_test__debug__actions_/fatal_messages.txt

@vitlibar will take care of it.

**Comment by alexey-milovidov** [comment]
SipHash64 improved a lot
Screenshot_20220508_152540

Let's merge.

@Algunenano @danlark1 let's submit a subsequent pull request.

**Comment by Algunenano** [comment]
> @Algunenano @danlark1 let's submit a subsequent pull request.

https://github.com/ClickHouse/ClickHouse/pull/37019 Tested `inline ALWAYS_INLINE typename` locally and it works, let's see what the CI thinks.

**Pull request merged**
