### PR TITLE
Fix sumIf rewrite

### LINKED ISSUE #33603: DB::Exception: Unknown function sumIF: While processing t, sumIF(n, 0)
```sql
SELECT sumIF(1, 0)

Query id: 3a3db9bd-b0ad-4d2f-bd8b-39daeda0546c

┌─countIf(0)─┐
│          0 │
└────────────┘

1 rows in set. Elapsed: 0.244 sec. 
```
is OK.

```sql
CREATE TABLE agg
ENGINE = AggregatingMergeTree
ORDER BY tuple() AS
SELECT
    t,
    sumIF(n, 0)
FROM data
GROUP BY t

Query id: f47b729e-c574-4978-b565-aa805b7b896f


0 rows in set. Elapsed: 0.009 sec. 

Received exception from server (version 21.13.1):
Code: 46. DB::Exception: Received from localhost:9000. DB::Exception: Unknown function sumIF: While processing t, sumIF(n, 0). (UNKNOWN_FUNCTION)
```

### PR DESCRIPTION
**Pull request by ucasfl**
Changelog category (leave one):

- Not for changelog (changelog entry is not required)

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Closes #33603.

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]

**Comment by ucasfl** [comment]
Does this PR have other problem need to fix? @alexey-milovidov

**Comment by alexey-milovidov** [comment]
No, but I have to look at the failed functional tests.

**Comment by alexey-milovidov** [comment]
https://s3.amazonaws.com/clickhouse-test-reports/33677/1cdadbd250a37821a8f3ce176e22f05acaa176e9/stateless_tests__debug__actions__[3/3].html

These failures are either flaky tests or infrastructure failures.
But we are aiming for absolute zero of flaky tests. And we are almost there:
https://clickhouse.com/blog/en/2021/tests-visualization/

So, I cannot just leave it.

**Comment by ucasfl** [comment]
@Mergifyio update.

**Pull request merged**
