### PR TITLE
Enable black back

### PR DESCRIPTION
**Pull request by Felixoid**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Black was disabled in PR #61125 while experimenting. Bring it back

### CODE REVIEW

**Comment by robot-ch-test-poll4** [comment]
*This is an automated comment for commit a02e966aec08d4bb948f561c6d112e527e256304 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/61159/a02e966aec08d4bb948f561c6d112e527e256304/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

**Comment by maxknv** [comment]
back to black

**Comment by Felixoid** [comment]
https://youtu.be/8QW80st14Kg it belongs here

**Comment by maxknv** [comment]
i was referring another track, but this one also nice :)

**Pull request merged**
