### PR TITLE
ISSUES-14231 fix wrong lexer in MaterializeMySQL database engine dump stage

### LINKED ISSUE #14231: MaterializeMySQL not support number started column name
**Describe the bug**

Table schema:
> mysql> show create table name\G
> 
> *************************** 1. row ***************************
>        Table: name
> Create Table: CREATE TABLE `name` (
>   `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
>   `username` varchar(40) DEFAULT NULL,
>   `1m_10m` smallint(6) DEFAULT NULL,
>   PRIMARY KEY (`id`)
> ) ENGINE=InnoDB AUTO_INCREMENT=178 DEFAULT CHARSET=latin1

When doing DB creation:

>  CREATE DATABASE clickhouse_test ENGINE = MaterializeMySQL('192.168.153.132:3306', 'clickhouse_test', 'root', 'password');

Got error message:

> Code: 62. DB::Exception: Received from 192.168.153.132:9000. DB::Exception: Syntax error: failed at position 80 ('1m_10m'): 1m_10m) VALUES. Wrong number.

### PR DESCRIPTION
**Pull request by zhang2014**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
fixes #14231 
 fix wrong lexer in MaterializeMySQL database engine dump stage

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]

**Comment by zhang2014** [comment]
Compatible with the MySQL Identifier(https://dev.mysql.com/doc/refman/8.0/en/identifiers.html)

**Comment by zhang2014** [comment]
@alexey-milovidov 
How to get `AST fuzzer — Received signal 6` server logs?

**Comment by alexey-milovidov** [comment]
Performance test Ok.

**Comment by alexey-milovidov** [comment]
Unfortunately, AST Fuzzer check does not give server logs... Currently the only way to figure out what's happening is to copy-paste one of the last queries and execute them with the server built in debug mode (when assertions and extra runtime checks are enabled). @akuzm

**Comment by akuzm** [comment]
> Unfortunately, AST Fuzzer check does not give server logs... Currently the only way to figure out what's happening is to copy-paste one of the last queries and execute them with the server built in debug mode (when assertions and extra runtime checks are enabled). @akuzm

For now, replace `fuzzer.log` with `server.log` in the link. I'll add a proper report page.

**Comment by zhang2014** [comment]
What should I do for this PR?

**Comment by alexey-milovidov** [comment]
Nothing is remaining. We need to classify this fuzzer failure. It usually find some already existing issues in corner cases.
The PR is Ok.

**Comment by alexey-milovidov** [comment]
https://github.com/ClickHouse/ClickHouse/issues/13981

**Comment by liangli1213** [comment]
@alexey-milovidov , when will be next build available? I'm now using 20.8.1.4474, I'm waiting for the fix in new build.

**Pull request merged**
