### PR TITLE
Fix assert in SpanHolder::finish() with fibers

### LINKED ISSUE #49178: 02585_query_status_deadlock is flaky
```
clickhouse-server: /build/src/Common/OpenTelemetryTraceContext.cpp:144: void DB::OpenTelemetry::SpanHolder::finish(): Assertion `current_thread_trace_context.span_id == span_id' failed.
```
 in stderr.log (maybe it is connected somehow)

https://s3.amazonaws.com/clickhouse-test-reports/0/80c1a4ed88fad4e1a2679d19920eaa3ff63699ea/stateless_tests__debug__[1/5].html
and
https://s3.amazonaws.com/clickhouse-test-reports/0/6f5945175c60b1b25ac2ee7504079ee288f160ba/stateless_tests__debug__[1/5].html

https://play.clickhouse.com/play?user=play#U0VMRUNUIHB1bGxfcmVxdWVzdF9udW1iZXIsIGNoZWNrX3N0YXJ0X3RpbWUsIGNoZWNrX25hbWUsIHRlc3RfbmFtZSwgdGVzdF9zdGF0dXMsIGNoZWNrX3N0YXR1cywgcmVwb3J0X3VybApGUk9NIGNoZWNrcwpXSEVSRSAxCiAgICAtLUFORCBwdWxsX3JlcXVlc3RfbnVtYmVyID0gMAogICAgQU5EIHRlc3Rfc3RhdHVzICE9ICdTS0lQUEVEJwogICAgQU5EIHRlc3Rfc3RhdHVzICE9ICdPSycKICAgIEFORCBjaGVja19zdGF0dXMgIT0gJ3N1Y2Nlc3MnCiAgICBBTkQgdGVzdF9uYW1lIGxpa2UgJyUwMjU4NV9xdWVyeV9zdGF0dXNfZGVhZGxvY2slJwpPUkRFUiBCWSBjaGVja19zdGFydF90aW1lIGRlc2MsIGNoZWNrX25hbWUsIHRlc3RfbmFtZQ==

### LINKED ISSUE #49185: Abort in `OpenTelemetry::SpanHolder::finish()`
https://s3.amazonaws.com/clickhouse-test-reports/0/80c1a4ed88fad4e1a2679d19920eaa3ff63699ea/stateless_tests__debug__[1/5].html

Looks like "terminate called for uncaught exception", but it may be an assertion as well:
```
2023.04.26 06:58:46.054529 [ 2883 ] {} <Fatal> BaseDaemon: ########################################
2023.04.26 06:58:46.054949 [ 2883 ] {} <Fatal> BaseDaemon: (version 23.4.1.1 (official build), build id: E3E0936B36CD53B684EE940C52D363CE775999A6) (from thread 1412) (query_id: b4c077e1-1807-463c-aaad-7d4959637aa2) (query: kill query where query_id = 'test_pzkratru_test_02585_query_to_kill_id_1' sync) Received signal Aborted (6)
2023.04.26 06:58:46.055147 [ 2883 ] {} <Fatal> BaseDaemon: 
2023.04.26 06:58:46.055344 [ 2883 ] {} <Fatal> BaseDaemon: Stack trace: 0x7f7207c6300b 0x7f7207c42859 0x7f7207c42729 0x7f7207c53fd6 0x22eb0ca4 0x22eb0eb9 0x2d2ed7a6 0x2d0f47ea 0x2d12325d 0x2d1230fe 0x2a3b45c1 0x2a3b3fb6 0x2a3d1682 0x2a3d0398 0x2a3d02c8 0x2a3d0288 0x2a3d01be 0x2a3d003d
2023.04.26 06:58:46.055570 [ 2883 ] {} <Fatal> BaseDaemon: 4. gsignal @ 0x7f7207c6300b in ?
2023.04.26 06:58:46.055756 [ 2883 ] {} <Fatal> BaseDaemon: 5. abort @ 0x7f7207c42859 in ?
2023.04.26 06:58:46.055895 [ 2883 ] {} <Fatal> BaseDaemon: 6. ? @ 0x7f7207c42729 in ?
2023.04.26 06:58:46.056115 [ 2883 ] {} <Fatal> BaseDaemon: 7. ? @ 0x7f7207c53fd6 in ?
2023.04.26 06:58:46.134479 [ 2883 ] {} <Fatal> BaseDaemon: 8. /build/src/Common/OpenTelemetryTraceContext.cpp:0: DB::OpenTelemetry::SpanHolder::finish() @ 0x22eb0ca4 in /usr/bin/clickhouse
2023.04.26 06:58:46.233511 [ 2883 ] {} <Fatal> BaseDaemon: 9. /build/src/Common/OpenTelemetryTraceContext.cpp:170: DB::OpenTelemetry::SpanHolder::~SpanHolder() @ 0x22eb0eb9 in /usr/bin/clickhouse
2023.04.26 06:58:46.349611 [ 2883 ] {} <Fatal> BaseDaemon: 10. /build/src/Processors/Executors/PipelineExecutor.cpp:134: DB::PipelineExecutor::execute(unsigned long) @ 0x2d2ed7a6 in /usr/bin/clickhouse
2023.04.26 06:58:46.592244 [ 2883 ] {} <Fatal> BaseDaemon: 11. /build/src/Client/Connection.cpp:869: DB::Connection::sendExternalTablesData(std::vector<std::unique_ptr<DB::ExternalTableData, std::default_delete<DB::ExternalTableData>>, std::allocator<std::unique_ptr<DB::ExternalTableData, std::default_delete<DB::ExternalTableData>>>>&) @ 0x2d0f47ea in /usr/bin/clickhouse
2023.04.26 06:58:46.792386 [ 2883 ] {} <Fatal> BaseDaemon: 12. /build/src/Client/HedgedConnections.cpp:106: DB::HedgedConnections::sendExternalTablesData(std::vector<std::vector<std::unique_ptr<DB::ExternalTableData, std::default_delete<DB::ExternalTableData>>, std::allocator<std::unique_ptr<DB::ExternalTableData, std::default_delete<DB::ExternalTableData>>>>, std::allocator<std::vector<std::unique_ptr<DB::ExternalTableData, std::default_delete<DB::ExternalTableData>>, std::allocator<std::unique_ptr<DB::ExternalTableData, std::default_delete<DB::ExternalTableData>>>>>>&)::$_2::operator()(DB::HedgedConnections::ReplicaState&) const @ 0x2d12325d in /usr/bin/clickhouse
2023.04.26 06:58:46.980880 [ 2883 ] {} <Fatal> BaseDaemon: 13. /build/src/Client/HedgedConnections.cpp:111: DB::HedgedConnections::sendExternalTablesData(std::vector<std::vector<std::unique_ptr<DB::ExternalTableData, std::default_delete<DB::ExternalTableData>>, std::allocator<std::unique_ptr<DB::ExternalTableData, std::default_delete<DB::ExternalTableData>>>>, std::allocator<std::vector<std::unique_ptr<DB::ExternalTableData, std::default_delete<DB::ExternalTableData>>, std::allocator<std::unique_ptr<DB::ExternalTableData, std::default_delete<DB::ExternalTableData>>>>>>&) @ 0x2d1230fe in /usr/bin/clickhouse
2023.04.26 06:58:47.196219 [ 2883 ] {} <Fatal> BaseDaemon: 14. /build/src/QueryPipeline/RemoteQueryExecutor.cpp:701: DB::RemoteQueryExecutor::sendExternalTables() @ 0x2a3b45c1 in /usr/bin/clickhouse
2023.04.26 06:58:47.426912 [ 2883 ] {} <Fatal> BaseDaemon: 15. /build/src/QueryPipeline/RemoteQueryExecutor.cpp:269: DB::RemoteQueryExecutor::sendQueryUnlocked(DB::ClientInfo::QueryKind, std::function<void (int, Poco::Timespan, DB::AsyncEventTimeoutType, String const&, unsigned int)>) @ 0x2a3b3fb6 in /usr/bin/clickhouse
2023.04.26 06:58:47.507256 [ 2883 ] {} <Fatal> BaseDaemon: 16. /build/src/QueryPipeline/RemoteQueryExecutorReadContext.cpp:39: DB::RemoteQueryExecutorReadContext::Task::run(std::function<void (int, Poco::Timespan, DB::AsyncEventTimeoutType, String const&, unsigned int)>, std::function<void ()>) @ 0x2a3d1682 in /usr/bin/clickhouse
2023.04.26 06:58:47.567867 [ 2883 ] {} <Fatal> BaseDaemon: 17. /build/src/Common/AsyncTaskExecutor.cpp:88: DB::AsyncTaskExecutor::Routine::operator()(boost::context::fiber&&) @ 0x2a3d0398 in /usr/bin/clickhouse
2023.04.26 06:58:47.629997 [ 2883 ] {} <Fatal> BaseDaemon: 18. /build/contrib/llvm-project/libcxx/include/__functional/invoke.h:394: decltype(std::declval<DB::AsyncTaskExecutor::Routine&>()(std::declval<boost::context::fiber>())) std::__invoke[abi:v15000]<DB::AsyncTaskExecutor::Routine&, boost::context::fiber>(DB::AsyncTaskExecutor::Routine&, boost::context::fiber&&) @ 0x2a3d02c8 in /usr/bin/clickhouse
2023.04.26 06:58:47.691781 [ 2883 ] {} <Fatal> BaseDaemon: 19. /build/contrib/llvm-project/libcxx/include/__functional/invoke.h:531: std::invoke_result<DB::AsyncTaskExecutor::Routine&, boost::context::fiber>::type std::invoke<DB::AsyncTaskExecutor::Routine&, boost::context::fiber>(DB::AsyncTaskExecutor::Routine&, boost::context::fiber&&) @ 0x2a3d0288 in /usr/bin/clickhouse
2023.04.26 06:58:47.752637 [ 2883 ] {} <Fatal> BaseDaemon: 20. /build/contrib/boost/boost/context/fiber_fcontext.hpp:140: boost::context::detail::fiber_record<boost::context::fiber, FiberStack&, DB::AsyncTaskExecutor::Routine>::run(void*) @ 0x2a3d01be in /usr/bin/clickhouse
2023.04.26 06:58:47.814377 [ 2883 ] {} <Fatal> BaseDaemon: 21. /build/contrib/boost/boost/context/fiber_fcontext.hpp:80: void boost::context::detail::fiber_entry<boost::context::detail::fiber_record<boost::context::fiber, FiberStack&, DB::AsyncTaskExecutor::Routine>>(boost::context::detail::transfer_t) @ 0x2a3d003d in /usr/bin/clickhouse
2023.04.26 06:58:51.300496 [ 2883 ] {} <Fatal> BaseDaemon: Integrity check of the executable successfully passed (checksum: 2824BEEE901BA995655CF98FC401E68C)
2023.04.26 06:58:54.565147 [ 658 ] {} <Fatal> Application: Child process was terminated by signal 6.
```

May be related to https://github.com/ClickHouse/ClickHouse/pull/47667
cc: @FrankChen021, @nickitat

### PR DESCRIPTION
**Pull request by Avogar**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix assert in SpanHolder::finish() with fibers by making thread local variable fiber local.
Closes https://github.com/ClickHouse/ClickHouse/issues/49185
Closes https://github.com/ClickHouse/ClickHouse/issues/49178

### CODE REVIEW

**Comment by qoega** [comment]
Check this one as well, please

@
https://s3.amazonaws.com/clickhouse-test-reports/0/5629d73bdbb5d321f7cd49c8c3b0e3a39d6ab1d4/stress_test__tsan_.html

```
2023-05-08 18:01:35 Thread 607 "TCPHandler" received signal SIGSEGV, Segmentation fault.
2023-05-08 18:01:35 [Switching to Thread 0x7fd0cdbfe700 (LWP 2629)]
2023-05-08 18:01:35 0x0000555ed2edc77d in __tsan::ThreadContext::OnFinished() ()
2023-05-08 18:01:35 #0  0x0000555ed2edc77d in __tsan::ThreadContext::OnFinished() ()
2023-05-08 18:01:35 No symbol table info available.
2023-05-08 18:01:35 #1  0x0000555ed2e47a9c in __sanitizer::ThreadRegistry::FinishThread(unsigned int) ()
2023-05-08 18:01:35 No symbol table info available.
2023-05-08 18:01:35 #2  0x0000555ed2edc4fb in __tsan::ThreadFinish(__tsan::ThreadState*) ()
2023-05-08 18:01:35 No symbol table info available.
2023-05-08 18:01:35 #3  0x0000555ed2edcd20 in __tsan::FiberDestroy(__tsan::ThreadState*, unsigned long, __tsan::ThreadState*) ()
2023-05-08 18:01:35 No symbol table info available.
2023-05-08 18:01:35 #4  0x0000555ee366ad55 in boost::context::detail::fiber_activation_record::~fiber_activation_record (this=0x7fcf83df4b00) at ./contrib/boost/boost/context/fiber_ucontext.hpp:121
2023-05-08 18:01:35 No locals.
2023-05-08 18:01:35 #5  0x0000555ee366acc0 in boost::context::detail::fiber_capture_record<boost::context::fiber, FiberStack&, DB::AsyncTaskExecutor::Routine>::destroy (p=0x7fcf83df4b00) at ./contrib/boost/boost/context/fiber_ucontext.hpp:255
2023-05-08 18:01:35         salloc = {stack_size = <optimized out>, page_size = 4096, static default_stack_size = 327680}
2023-05-08 18:01:35         sctx = {size = 331776, sp = 0x7fcf83df5000}
2023-05-08 18:01:35 #6  boost::context::detail::fiber_capture_record<boost::context::fiber, FiberStack&, DB::AsyncTaskExecutor::Routine>::deallocate (this=0x7fcf83df4b00) at ./contrib/boost/boost/context/fiber_ucontext.hpp:269
2023-05-08 18:01:35 No locals.
2023-05-08 18:01:35 #7  0x0000555ee366a699 in boost::context::fiber::~fiber (this=0x7b4803387188) at ./contrib/boost/boost/context/fiber_ucontext.hpp:450
2023-05-08 18:01:35 No locals.
2023-05-08 18:01:35 #8  DB::AsyncTaskExecutor::~AsyncTaskExecutor (this=<optimized out>) at ./src/Common/AsyncTaskExecutor.h:59
2023-05-08 18:01:35 No locals.
2023-05-08 18:01:35 #9  0x0000555ee62014d0 in DB::ConnectionEstablisherAsync::~ConnectionEstablisherAsync (this=0x7b4803387180) at ./src/Client/ConnectionEstablisher.h:57
2023-05-08 18:01:35 No locals.
2023-05-08 18:01:35 #10 0x0000555ee620bf5a in DB::ConnectionEstablisherAsync::~ConnectionEstablisherAsync (this=0x7b4803387180) at ./src/Client/ConnectionEstablisher.h:57
2023-05-08 18:01:35 No locals.
2023-05-08 18:01:35 #11 0x0000555ee621801d in std::__1::default_delete<DB::ConnectionEstablisherAsync>::operator()[abi:v15000](DB::ConnectionEstablisherAsync*) const (this=0x7b2000f03f00, __ptr=0x7b4803387180) at ./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:48
2023-05-08 18:01:35 No locals.
2023-05-08 18:01:35 #12 std::__1::unique_ptr<DB::ConnectionEstablisherAsync, std::__1::default_delete<DB::ConnectionEstablisherAsync> >::reset[abi:v15000](DB::ConnectionEstablisherAsync*) (this=0x7b2000f03f00, __p=0x0) at ./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:305
2023-05-08 18:01:35         __tmp = 0x7b4803387180
2023-05-08 18:01:35 #13 std::__1::unique_ptr<DB::ConnectionEstablisherAsync, std::__1::default_delete<DB::ConnectionEstablisherAsync> >::~unique_ptr[abi:v15000]() (this=0x7b2000f03f00) at ./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:259
2023-05-08 18:01:35 No locals.
2023-05-08 18:01:35 #14 DB::HedgedConnectionsFactory::ReplicaStatus::~ReplicaStatus (this=0x7b2000f03f00) at ./src/Client/HedgedConnectionsFactory.h:37
2023-05-08 18:01:35 No locals.
2023-05-08 18:01:35 #15 std::__1::__destroy_at[abi:v15000]<DB::HedgedConnectionsFactory::ReplicaStatus, 0>(DB::HedgedConnectionsFactory::ReplicaStatus*) (__loc=0x7b2000f03f00) at ./contrib/llvm-project/libcxx/include/__memory/construct_at.h:63
2023-05-08 18:01:35 No locals.
2023-05-08 18:01:35 #16 std::__1::destroy_at[abi:v15000]<DB::HedgedConnectionsFactory::ReplicaStatus, 0>(DB::HedgedConnectionsFactory::ReplicaStatus*) (__loc=0x7b2000f03f00) at ./contrib/llvm-project/libcxx/include/__memory/construct_at.h:88
2023-05-08 18:01:35 No locals.
2023-05-08 18:01:35 #17 std::__1::allocator_traits<std::__1::allocator<DB::HedgedConnectionsFactory::ReplicaStatus> >::destroy[abi:v15000]<DB::HedgedConnectionsFactory::ReplicaStatus, void, void>(std::__1::allocator<DB::HedgedConnectionsFactory::ReplicaStatus>&, DB::HedgedConnectionsFactory::ReplicaStatus*) (__p=0x7b2000f03f00) at ./contrib/llvm-project/libcxx/include/__memory/allocator_traits.h:317
2023-05-08 18:01:35 No locals.
2023-05-08 18:01:35 #18 std::__1::vector<DB::HedgedConnectionsFactory::ReplicaStatus, std::__1::allocator<DB::HedgedConnectionsFactory::ReplicaStatus> >::__base_destruct_at_end[abi:v15000](DB::HedgedConnectionsFactory::ReplicaStatus*) (this=0x7b6401911380, __new_last=0x7b2000f03f00) at ./contrib/llvm-project/libcxx/include/vector:833
2023-05-08 18:01:35         __soon_to_be_end = 0x7b2000f03f00
2023-05-08 18:01:35 #19 std::__1::vector<DB::HedgedConnectionsFactory::ReplicaStatus, std::__1::allocator<DB::HedgedConnectionsFactory::ReplicaStatus> >::__clear[abi:v15000]() (this=0x7b6401911380) at ./contrib/llvm-project/libcxx/include/vector:827
2023-05-08 18:01:35 No locals.
2023-05-08 18:01:35 #20 std::__1::vector<DB::HedgedConnectionsFactory::ReplicaStatus, std::__1::allocator<DB::HedgedConnectionsFactory::ReplicaStatus> >::~vector[abi:v15000]() (this=0x7b6401911380) at ./contrib/llvm-project/libcxx/include/vector:436
2023-05-08 18:01:35 No locals.
2023-05-08 18:01:35 #21 DB::HedgedConnectionsFactory::~HedgedConnectionsFactory (this=0x7b6401911308) at ./src/Client/HedgedConnectionsFactory.cpp:54
2023-05-08 18:01:35 No locals.
2023-05-08 18:01:35 #22 0x0000555ee6213e46 in DB::HedgedConnections::~HedgedConnections (this=this@entry=0x7b6401911300) at ./src/Client/HedgedConnections.h:29
2023-05-08 18:01:36 No locals.
2023-05-08 18:01:36 #23 0x0000555ee6213e9a in DB::HedgedConnections::~HedgedConnections (this=0x7b6401911300) at ./src/Client/HedgedConnections.h:29
2023-05-08 18:01:36 No locals.
2023-05-08 18:01:36 #24 0x0000555ee3656825 in std::__1::default_delete<DB::IConnections>::operator()[abi:v15000](DB::IConnections*) const (this=<optimized out>, __ptr=0x7b6401911300) at ./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:48
2023-05-08 18:01:36 No locals.
```

**Comment by Avogar** [comment]
> Check this one as well, please

Sure, I already saw it. Actually, it looks like a bug in tsan itself.
```
ThreadSanitizer: CHECK failed: tsan_interceptors_posix.cpp:1987 "((thr->slot)) != (0)" (0x0, 0x0) (tid=2629)
```
The same check as in https://github.com/ClickHouse/ClickHouse/issues/37910, but commented that it should be fixed in clang-15. @tavplubix maybe you canadd something?

**Review by alexey-milovidov — APPROVED** [review]

**Comment by tavplubix** [comment]
> Actually, it looks like a bug in tsan itself.

I'm not sure

> The same check as in https://github.com/ClickHouse/ClickHouse/issues/37910

The stacktrace is different, it's another issue. https://github.com/ClickHouse/ClickHouse/issues/37910 was related to signal handling in tsan, see https://github.com/google/sanitizers/issues/1541. And now there are no signals but SIGSEGV:

```
2023-05-08 18:01:35 Thread 607 "TCPHandler" received signal SIGSEGV, Segmentation fault.
2023-05-08 18:01:35 [Switching to Thread 0x7fd0cdbfe700 (LWP 2629)]
2023-05-08 18:01:35 0x0000555ed2edc77d in __tsan::ThreadContext::OnFinished() ()
2023-05-08 18:01:35 #0  0x0000555ed2edc77d in __tsan::ThreadContext::OnFinished() ()
2023-05-08 18:01:35 No symbol table info available.
2023-05-08 18:01:35 #1  0x0000555ed2e47a9c in __sanitizer::ThreadRegistry::FinishThread(unsigned int) ()
2023-05-08 18:01:35 No symbol table info available.
2023-05-08 18:01:35 #2  0x0000555ed2edc4fb in __tsan::ThreadFinish(__tsan::ThreadState*) ()
2023-05-08 18:01:35 No symbol table info available.
2023-05-08 18:01:35 #3  0x0000555ed2edcd20 in __tsan::FiberDestroy(__tsan::ThreadState*, unsigned long, __tsan::ThreadState*) ()
2023-05-08 18:01:35 No symbol table info available.
2023-05-08 18:01:35 #4  0x0000555ee366ad55 in boost::context::detail::fiber_activation_record::~fiber_activation_record (this=0x7fcf83df4b00) at ./contrib/boost/boost/context/fiber_ucontext.hpp:121
2023-05-08 18:01:35 No locals.
2023-05-08 18:01:35 #5  0x0000555ee366acc0 in boost::context::detail::fiber_capture_record<boost::context::fiber, FiberStack&, DB::AsyncTaskExecutor::Routine>::destroy (p=0x7fcf83df4b00) at ./contrib/boost/boost/context/fiber_ucontext.hpp:255
2023-05-08 18:01:35         salloc = {stack_size = <optimized out>, page_size = 4096, static default_stack_size = 327680}
2023-05-08 18:01:35         sctx = {size = 331776, sp = 0x7fcf83df5000}
2023-05-08 18:01:35 #6  boost::context::detail::fiber_capture_record<boost::context::fiber, FiberStack&, DB::AsyncTaskExecutor::Routine>::deallocate (this=0x7fcf83df4b00) at ./contrib/boost/boost/context/fiber_ucontext.hpp:269
2023-05-08 18:01:35 No locals.
2023-05-08 18:01:35 #7  0x0000555ee366a699 in boost::context::fiber::~fiber (this=0x7b4803387188) at ./contrib/boost/boost/context/fiber_ucontext.hpp:450
2023-05-08 18:01:35 No locals.
2023-05-08 18:01:35 #8  DB::AsyncTaskExecutor::~AsyncTaskExecutor (this=<optimized out>) at ./src/Common/AsyncTaskExecutor.h:59
2023-05-08 18:01:35 No locals.
2023-05-08 18:01:35 #9  0x0000555ee62014d0 in DB::ConnectionEstablisherAsync::~ConnectionEstablisherAsync (this=0x7b4803387180) at ./src/Client/ConnectionEstablisher.h:57
2023-05-08 18:01:35 No locals.
2023-05-08 18:01:35 #10 0x0000555ee620bf5a in DB::ConnectionEstablisherAsync::~ConnectionEstablisherAsync (this=0x7b4803387180) at ./src/Client/ConnectionEstablisher.h:57
2023-05-08 18:01:35 No locals.
... (the remaining frames are not so interesting)
```

> ThreadSanitizer: CHECK failed

AFAIR, this check may fail when tsan gets an unexpected synchronous signal. So this check has failed because of SIGSEGV (tsan tried to handle it but failed). Let's try to find where exactly it got segfault (we don't have line numbers in the stacktrace, but we have [disasm](https://pastila.nl/?037185ef/ec080fb636db532b3666876d3c6e4533) with the instruction pointer):
```
   0x0000555ed2edc760 <+496>:	cmpq   $0x0,0x8(%rax)
   0x0000555ed2edc765 <+501>:	je     0x555ed2edc9ce <_ZN6__tsan13ThreadContext10OnFinishedEv+1118>
   0x0000555ed2edc76b <+507>:	mov    0x0(%r13),%rsi
   0x0000555ed2edc76f <+511>:	mov    0xa081c0(%rsi),%rbx
   0x0000555ed2edc776 <+518>:	lea    0x18(%rax),%rbp

        INode* next = after->next_;
   0x0000555ed2edc77a <+522>:	mov    (%rbx),%rdx
        n->next_ = next;
=> 0x0000555ed2edc77d <+525>:	mov    %rdx,0x18(%rax)
        n->prev_ = after;
   0x0000555ed2edc781 <+529>:	mov    %rbx,0x20(%rax)
        next->prev_ = n;
   0x0000555ed2edc785 <+533>:	mov    %rbp,0x8(%rdx)
        after->next_ = n;
   0x0000555ed2edc789 <+537>:	mov    %rbp,(%rbx)
        size_++;
   0x0000555ed2edc78c <+540>:	incq   0xa081c8(%rsi)

   0x0000555ed2edc793 <+547>:	mov    0x8(%rax),%rdx
   0x0000555ed2edc797 <+551>:	lea    -0x8(%rdx),%rax
   0x0000555ed2edc79b <+555>:	cmp    %rcx,%rdx
   0x0000555ed2edc79e <+558>:	mov    %rax,%rdx
   0x0000555ed2edc7a1 <+561>:	cmove  %r8,%rdx
   0x0000555ed2edc7a5 <+565>:	mov    %rdx,0xd8(%r15)
   0x0000555ed2edc7ac <+572>:	test   %rdx,%rdx
   0x0000555ed2edc7af <+575>:	jne    0x555ed2edc760 <_ZN6__tsan13ThreadContext10OnFinishedEv+496>
```

Looks like it represents [this](https://github.com/ClickHouse/llvm-project/blob/8246b2e156568c31e71e16cbaf4c14d316e7c06e/compiler-rt/lib/tsan/rtl/tsan_rtl_thread.cpp#L258) loop with [`IList::Push`](https://github.com/ClickHouse/llvm-project/blob/f821a55c5e7847edd0b3bf70543b318d6bcbcd0a/compiler-rt/lib/tsan/rtl/tsan_ilist.h#L92) inlined. It got segfault on attempt to read `(%rbx)` (`=>` points to the next instruction), or, on attempt to dereference `after` [here](https://github.com/ClickHouse/llvm-project/blob/f821a55c5e7847edd0b3bf70543b318d6bcbcd0a/compiler-rt/lib/tsan/rtl/tsan_ilist.h#L96), where `after` is [`node_.prev_`](https://github.com/ClickHouse/llvm-project/blob/f821a55c5e7847edd0b3bf70543b318d6bcbcd0a/compiler-rt/lib/tsan/rtl/tsan_ilist.h#L88). Also, `after = rbx = 0x7fd136abb018`, looks like something on a stack.

So, seems like the list was corrupted somehow. How it could happen:
1. There's a bug in the list implementation in tsan
2. There's a race condition in tsan, so the list was accessed concurrently 
3. ClickHouse (or boost) has corrupted the memory
4. Something else

1 and 2 are unlikely, so I would say it's 3 or 4. It's a bit suspicious that it involves `FiberDestroy`, and it provides a caller some access to tsan internals (and ability to break something), need to check it more carefully

**Comment by tavplubix** [comment]
> `=>` points to the next instruction

Sorry, I was mistaken, actually it points to the faulty instruction (because it was not executed and `rip` was not updated). So actually it crashed on attempt to execute `mov    %rdx,0x18(%rax)`, that is `n->next_ = next;`, where `n` is `trace.local_head->trace_parts`, and `n = rax = 0x555ee361e12f`.

It's interesting that it must have executed `cmpq   $0x0,0x8(%rax)` (or `mov    0x8(%rax),%rdx`) successfully to get here, so it can read from that address, but cannot write. And yes, `n = rax = 0x555ee361e12f` looks like an address of some executable code:
```
2023-05-08 18:02:34 rax            0x555ee361e12f      93866030129455
2023-05-08 18:02:34 rbp            0x555ee361e147      0x555ee361e147 <LZ4::decompress(char const*, char*, unsigned long, unsigned long, LZ4::PerformanceStatistics&)+295>
```
Btw, a similar address (`begin_pos = 0x555ee361ecf6`) can be found in stacktraces with local variables:
```
2023-05-08 18:01:49 Thread 818 (Thread 0x7fd0341f2700 (LWP 3198)):
2023-05-08 18:01:49 #0  0x0000555ed2e40a1a in __sanitizer::FutexWait(__sanitizer::atomic_uint32_t*, unsigned int) ()
2023-05-08 18:01:49 No symbol table info available.
2023-05-08 18:01:49 #1  0x0000555ed2e41ada in __sanitizer::Semaphore::Wait() ()
2023-05-08 18:01:49 No symbol table info available.
2023-05-08 18:01:49 #2  0x0000555ed2ec8450 in __tsan::TraceSwitchPartImpl(__tsan::ThreadState*) ()
2023-05-08 18:01:49 No symbol table info available.
2023-05-08 18:01:49 #3  0x0000555ed2ecbbd4 in __tsan::RestartUnalignedMemoryAccess(__tsan::ThreadState*, unsigned long, unsigned long, unsigned long, unsigned long) ()
2023-05-08 18:01:49 No symbol table info available.
2023-05-08 18:01:49 #4  0x0000555eea2c4cc8 in CityHash_v1_0_2::WeakHashLen32WithSeeds (s=0x7fcf57936c89 "et/?C+\"51\036", a=<optimized out>, b=3758122850392140791) at ./contrib/cityhash102/src/city.cc:176
2023-05-08 18:01:49 No locals.
2023-05-08 18:01:49 #5  CityHash_v1_0_2::CityHash128WithSeed (s=<optimized out>, len=36291, seed=...) at ./contrib/cityhash102/src/city.cc:319
2023-05-08 18:01:49         v = {first = 6215661365088335101, second = 7514665944893769875}
2023-05-08 18:01:49         w = <optimized out>
2023-05-08 18:01:49         x = 116711906202103773
2023-05-08 18:01:49         y = 3758122850392140791
2023-05-08 18:01:49         z = 11219653876939658002
2023-05-08 18:01:49         tail_done = <optimized out>
2023-05-08 18:01:49 #6  0x0000555eea2c5363 in CityHash_v1_0_2::CityHash128 (s=s@entry=0x7fcf57931f19 "\202\323\332", len=len@entry=56019) at ./contrib/cityhash102/src/city.cc:356
2023-05-08 18:01:49 No locals.
2023-05-08 18:01:49 #7  0x0000555ee35a2542 in DB::validateChecksum (data=data@entry=0x7fcf57931f19 "\202\323\332", size=size@entry=56019, expected_checksum=...) at ./src/Compression/CompressedReadBufferBase.cpp:44
2023-05-08 18:01:49         message = warning: can't find linker symbol for virtual table for `DB::WriteBufferFromOwnString' value
2023-05-08 18:01:49 warning:   found `__tsan::RestartUnalignedMemoryAccess(__tsan::ThreadState*, unsigned long, unsigned long, unsigned long, unsigned long)' instead
2023-05-08 18:01:49 {<DB::detail::StringHolder> = {value = {static __endian_factor = 1, __r_ = {<std::__1::__compressed_pair_elem<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::__rep, 0, false>> = {__value_ = {{__l = {__data_ = 0x7fd1a4c3cee8 "\004\004`\317\036\066\356Uj\317!^\317\017", __size_ = 140528614231914, __cap_ = 140528614231914, __is_long_ = 0}, __s = {__data_ = "\350\316\303\244\321\177\000\000j\317!^\317\177\000\000j\317!^\317\177", __padding_ = 0x7fd0341e8137 "", __size_ = 0 '\000', __is_long_ = 0 '\000'}, __r = {__words = {140538389188328, 140528614231914, 140528614231914}}}}}, <std::__1::__compressed_pair_elem<std::__1::allocator<char>, 1, true>> = {<std::__1::allocator<char>> = {<std::__1::__non_trivial_if<true, std::__1::allocator<char> >> = {<No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}, static npos = 18446744073709551615}}, <DB::WriteBufferFromVector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >> = {<DB::WriteBuffer> = {<DB::BufferBase> = {pos = 0x8 <error: Cannot access memory at address 0x8>, bytes = 6191946043637105668, working_buffer = {begin_pos = 0x555ee361ecf6 <LZ4::(anonymous namespace)::decompressImpl<8ul, true>(char const*, char*, unsigned long, unsigned long)+1142> "\017(\205p\377\377\377A\017\021\004$I\203\304\020I\203\307\376u\304H\213E\220H9E\270L\213m\210\017\204\302\373\377\377f\220\351&\377\377\377\350\326\321\210\357\363A\017o\f$L\215\065\211\065B\352H\213]\300\363A\017o\004\336f\017\070", end_pos = 0x555ed2ecbbd4 <__tsan::RestartUnalignedMemoryAccess(__tsan::ThreadState*, unsigned long, unsigned long, unsigned long, unsigned long)+36> "\213\023\205\322\017\210\364\004"}, internal_buffer = {begin_pos = 0x1 <error: Cannot access memory at address 0x1>, end_pos = 0x55ee361ec6300404 <error: Cannot access memory at address 0x55ee361ec6300404>}, padded = 99}, _vptr$WriteBuffer = 0x555ed2ecbbd4 <__tsan::RestartUnalignedMemoryAccess(__tsan::ThreadState*, unsigned long, unsigned long, unsigned long, unsigned long)+36>, finalized = 236}, vector = @0x0, static initial_size = 32, static size_multiplier = 2}, <No data fields>}
2023-05-08 18:01:49         calculated_checksum = <optimized out>
2023-05-08 18:01:49         difference = <optimized out>
2023-05-08 18:01:49         message_hardware_failure = <optimized out>
2023-05-08 18:01:49         flip_bit = <optimized out>
2023-05-08 18:01:49 #8  0x0000555ee35a1fe4 in DB::CompressedReadBufferBase::readCompressedData (this=<optimized out>, size_decompressed=<optimized out>, size_compressed_without_checksum=@0x7fd0341e83f8: 56019, always_copy=<optimized out>) at ./src/Compression/CompressedReadBufferBase.cpp:200
2023-05-08 18:01:49         checksum = {first = 14730044498646389939, second = 9361948234867992799}
2023-05-08 18:01:49         checksum_in = <incomplete type>
2023-05-08 18:01:49         header_size = 9 '\t'
2023-05-08 18:01:49         additional_size_at_the_end_of_buffer = <optimized out>
2023-05-08 18:01:49 #9  0x0000555ee35a4525 in DB::CompressedReadBufferFromFile::nextImpl (this=0x7b34005f70b0) at ./src/Compression/CompressedReadBufferFromFile.cpp:22
```

**Pull request merged**
