### PR TITLE
Fix exception in RemoteQueryExecutor when user does not exist locally

### LINKED ISSUE #72756: secureRemote: There is no user `demo` in user directories: While executing Remote.
If I try this query on at least `ClickHouse local version 24.11.1.2557` until the current version, I get this error:

```
SELECT *
FROM remoteSecure('sql-clickhouse.clickhouse.com', 'uk.uk_price_paid', 'demo')
LIMIT 10
```

```
Received exception from server (version 24.12.1):
Code: 192. DB::Exception: Received from localhost:9000. DB::Exception: There is no user `demo` in user directories: While executing Remote. (UNKNOWN_USER)
```

It works on `ClickHouse client version 24.11.1.1113 (official build).`

### PR DESCRIPTION
**Pull request by zvonand**
Closes #72756

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix exception thrown in RemoteQueryExecutor when user does not exist locally

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Run only fuzzers related jobs (libFuzzer fuzzers, AST fuzzers, etc.)
- [ ]  Exclude: AST fuzzers
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by zvonand** [comment]
@Algunenano could you please put a can-be-tested here?

**Comment by robot-clickhouse-ci-2** [comment]
*This is an automated comment for commit 8515b7b1045a94841efa9acf8b2baa8bc69671a8 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/72759/8515b7b1045a94841efa9acf8b2baa8bc69671a8/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/d7acd3db933815f1805372c48ac21f7283254000/docs_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Comment by pufit** [comment]
Please add a test that reproduces the error

**Review by yariks5s — APPROVED** [review]

**Comment by zvonand** [comment]
@yariks5s do you know what is bugfix validation and why it is failing? it does not like the tests are the issue:
```
_____________ ERROR at setup of test_push_role_to_other_nodes[4-5] _____________
[gw0] linux -- Python 3.10.12 /usr/bin/python3

    @pytest.fixture(scope="module", autouse=True)
    def ldap_cluster():
        try:
>           cluster.start()

test_ldap_external_user_directory/test.py:34: 
```
It is failing at start-up

**Comment by yariks5s** [comment]
This situation seems not ok, but I don't know the root cause yet, will try to dig it up more

**Comment by yariks5s** [comment]
I see similar errors in other PRs that were ignored, let's do the same :)

**Pull request merged**
