### PR TITLE
Remove disk restart proxy and disk decorator

### PR DESCRIPTION
**Pull request by alesapin**
### Changelog category (leave one):
- Backward Incompatible Change

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Remove query `SYSTEM RESTART DISK`.

### CODE REVIEW

**Comment by alesapin** [comment]
image

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alesapin** [comment]
I'm not sure about removing it from parser. Inside RBAC we can have serialized queries....

**Comment by alexey-milovidov** [comment]
Ok, let it be a no-op query.

**Review by nikitamikhaylov — APPROVED** [review]

**Comment by azat** [comment]
Were there any issues with this query? In other words what was the motivation for removal?

**Comment by canhld94** [comment]
> Were there any issues with this query? In other words what was the motivation for removal?

Same question here. See no harm for this query.
But imo implementation with `*DiskProxy` is an overkill. May be creating a new disk selector is enough.

**Pull request merged**
