### PR TITLE
Fix crash in not equi join on

### LINKED ISSUE #14627: Debug assertion: Wrong columns assign in RIGHT|FULL JOIN: UInt8 UInt16
```sql
SELECT foo.a
FROM 
(
    SELECT 
        NULL AND 3,
        NULL AS a,
        1 AS b
) AS foo
RIGHT JOIN 
(
    SELECT 
        ((inf AND NULL) AND ((NULL AND 65537) AND 257 AND NULL) AND NULL) AND 256 AND NULL AND ((NULL AND NULL) AND 257 AND NULL) AND NULL AND NULL,
        1024 AS b
) AS bar ON (and(and(-1)) AND NULL) AND (NULL AND '0.0000001025' AND NULL) AND (((((((100 AND NULL AND NULL) AND NULL) AND NULL AND ((1 AND NULL) AND (NULL AND NULL) AND NULL) AND NULL) AND 65536) AND 100.0000991821289) AND 1) = foo.b)
ORDER BY foo.a ASC

```

```bash
2020.09.09 15:48:33.643572 [ 60548 ] {65cdeea3-71f7-42f0-8d56-698941ebbd79} <Error> : Logical error: 'Wrong columns assign in RIGHT|FULL JOIN: UInt8 UInt16'.
clickhouse: ../src/Common/Exception.cpp:45: DB::Exception::Exception(const std::string &, int): Assertion `false' failed.
2020.09.09 15:48:33.644418 [ 60468 ] {} <Trace> BaseDaemon: Received signal 6
2020.09.09 15:48:33.644693 [ 60554 ] {} <Fatal> BaseDaemon: ########################################
2020.09.09 15:48:33.645050 [ 60554 ] {} <Fatal> BaseDaemon: (version 20.8.1.1, build id: A74DBD0D50188A47) (from thread 60548) (query_id: 65cdeea3-71f7-42f0-8d56-698941ebbd79) Received signal Aborted (6)
2020.09.09 15:48:33.645207 [ 60554 ] {} <Fatal> BaseDaemon: 
2020.09.09 15:48:33.645433 [ 60554 ] {} <Fatal> BaseDaemon: Stack trace: 0x7f3c6898818b 0x7f3c68967859 0x7f3c68967729 0x7f3c68978f36 0x25ca81c1 0x30509c06 0x2fe8c890 0x2fe8bfa5 0x2f8c265d 0x31169691 0x30e9ad67 0x31169343 0x30ef7d4c 0x30ef7caf 0x30ef7c6d 0x30ef7c1d 0x30ef7bed 0x30ef6d4e 0x25ccb0f5 0x25cca015 0x30ef5665 0x30ef5e59 0x30ef9fac 0x30ef9f0d 0x30ef9ed1 0x30ef9ea2 0x30ef9d9c 0x30ef9d2d
2020.09.09 15:48:33.647723 [ 60554 ] {} <Fatal> BaseDaemon: 4. /build/glibc-YYA7BZ/glibc-2.31/signal/../sysdeps/unix/sysv/linux/raise.c:51: __GI_raise @ 0x4618b in /usr/lib/debug/lib/x86_64-linux-gnu/libc-2.31.so
2020.09.09 15:48:33.648423 [ 60554 ] {} <Fatal> BaseDaemon: 5. /build/glibc-YYA7BZ/glibc-2.31/stdlib/abort.c:81: __GI_abort @ 0x25859 in /usr/lib/debug/lib/x86_64-linux-gnu/libc-2.31.so
2020.09.09 15:48:33.649163 [ 60554 ] {} <Fatal> BaseDaemon: 6. /build/glibc-YYA7BZ/glibc-2.31/intl/loadmsgcat.c:509: _nl_load_domain.cold @ 0x25729 in /usr/lib/debug/lib/x86_64-linux-gnu/libc-2.31.so
2020.09.09 15:48:33.649476 [ 60554 ] {} <Fatal> BaseDaemon: 7. ? @ 0x36f36 in /usr/lib/debug/lib/x86_64-linux-gnu/libc-2.31.so
2020.09.09 15:48:33.649769 [ 60554 ] {} <Fatal> BaseDaemon: 8. /home/jakalletti/ClickHouse/ClickHouse/build-clang-debug/../src/Common/Exception.cpp:48: DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x25ca81c1 in /home/jakalletti/ClickHouse/ClickHouse/build-clang-debug/programs/clickhouse
2020.09.09 15:48:33.689845 [ 60554 ] {} <Fatal> BaseDaemon: 9. /home/jakalletti/ClickHouse/ClickHouse/build-clang-debug/../src/Interpreters/join_common.cpp:392: DB::NotJoined::addRightColumns(DB::Block&, std::__1::vector<COW<DB::IColumn>::mutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::mutable_ptr<DB::IColumn> > >&) const @ 0x30509c06 in /home/jakalletti/ClickHouse/ClickHouse/build-clang-debug/programs/clickhouse
2020.09.09 15:48:33.739602 [ 60554 ] {} <Fatal> BaseDaemon: 10. /home/jakalletti/ClickHouse/ClickHouse/build-clang-debug/../src/Interpreters/HashJoin.cpp:1321: DB::NonJoinedBlockInputStream::createBlock() @ 0x2fe8c890 in /home/jakalletti/ClickHouse/ClickHouse/build-clang-debug/programs/clickhouse
2020.09.09 15:48:33.789678 [ 60554 ] {} <Fatal> BaseDaemon: 11. /home/jakalletti/ClickHouse/ClickHouse/build-clang-debug/../src/Interpreters/HashJoin.cpp:0: DB::NonJoinedBlockInputStream::readImpl() @ 0x2fe8bfa5 in /home/jakalletti/ClickHouse/ClickHouse/build-clang-debug/programs/clickhouse
2020.09.09 15:48:33.823090 [ 60554 ] {} <Fatal> BaseDaemon: 12. /home/jakalletti/ClickHouse/ClickHouse/build-clang-debug/../src/DataStreams/IBlockInputStream.cpp:57: DB::IBlockInputStream::read() @ 0x2f8c265d in /home/jakalletti/ClickHouse/ClickHouse/build-clang-debug/programs/clickhouse
2020.09.09 15:48:33.869041 [ 60554 ] {} <Fatal> BaseDaemon: 13. /home/jakalletti/ClickHouse/ClickHouse/build-clang-debug/../src/Processors/Sources/SourceFromInputStream.cpp:145: DB::SourceFromInputStream::generate() @ 0x31169691 in /home/jakalletti/ClickHouse/ClickHouse/build-clang-debug/programs/clickhouse
2020.09.09 15:48:33.912618 [ 60554 ] {} <Fatal> BaseDaemon: 14. /home/jakalletti/ClickHouse/ClickHouse/build-clang-debug/../src/Processors/ISource.cpp:48: DB::ISource::work() @ 0x30e9ad67 in /home/jakalletti/ClickHouse/ClickHouse/build-clang-debug/programs/clickhouse
2020.09.09 15:48:33.957535 [ 60554 ] {} <Fatal> BaseDaemon: 15. /home/jakalletti/ClickHouse/ClickHouse/build-clang-debug/../src/Processors/Sources/SourceFromInputStream.cpp:97: DB::SourceFromInputStream::work() @ 0x31169343 in /home/jakalletti/ClickHouse/ClickHouse/build-clang-debug/programs/clickhouse
2020.09.09 15:48:34.002818 [ 60554 ] {} <Fatal> BaseDaemon: 16. /home/jakalletti/ClickHouse/ClickHouse/build-clang-debug/../src/Processors/Executors/PipelineExecutor.cpp:78: DB::executeJob(DB::IProcessor*) @ 0x30ef7d4c in /home/jakalletti/ClickHouse/ClickHouse/build-clang-debug/programs/clickhouse
2020.09.09 15:48:34.046606 [ 60554 ] {} <Fatal> BaseDaemon: 17. /home/jakalletti/ClickHouse/ClickHouse/build-clang-debug/../src/Processors/Executors/PipelineExecutor.cpp:95: DB::PipelineExecutor::addJob(DB::ExecutingGraph::Node*)::$_0::operator()() const @ 0x30ef7caf in /home/jakalletti/ClickHouse/ClickHouse/build-clang-debug/programs/clickhouse
2020.09.09 15:48:34.091207 [ 60554 ] {} <Fatal> BaseDaemon: 18. /home/jakalletti/ClickHouse/ClickHouse/build-clang-debug/../contrib/libcxx/include/type_traits:3519: decltype(std::__1::forward<DB::PipelineExecutor::addJob(DB::ExecutingGraph::Node*)::$_0&>(fp)()) std::__1::__invoke<DB::PipelineExecutor::addJob(DB::ExecutingGraph::Node*)::$_0&>(DB::PipelineExecutor::addJob(DB::ExecutingGraph::Node*)::$_0&) @ 0x30ef7c6d in /home/jakalletti/ClickHouse/ClickHouse/build-clang-debug/programs/clickhouse
2020.09.09 15:48:34.135256 [ 60554 ] {} <Fatal> BaseDaemon: 19. /home/jakalletti/ClickHouse/ClickHouse/build-clang-debug/../contrib/libcxx/include/__functional_base:349: void std::__1::__invoke_void_return_wrapper<void>::__call<DB::PipelineExecutor::addJob(DB::ExecutingGraph::Node*)::$_0&>(DB::PipelineExecutor::addJob(DB::ExecutingGraph::Node*)::$_0&) @ 0x30ef7c1d in /home/jakalletti/ClickHouse/ClickHouse/build-clang-debug/programs/clickhouse
2020.09.09 15:48:34.179108 [ 60554 ] {} <Fatal> BaseDaemon: 20. /home/jakalletti/ClickHouse/ClickHouse/build-clang-debug/../contrib/libcxx/include/functional:1540: std::__1::__function::__alloc_func<DB::PipelineExecutor::addJob(DB::ExecutingGraph::Node*)::$_0, std::__1::allocator<DB::PipelineExecutor::addJob(DB::ExecutingGraph::Node*)::$_0>, void ()>::operator()() @ 0x30ef7bed in /home/jakalletti/ClickHouse/ClickHouse/build-clang-debug/programs/clickhouse
2020.09.09 15:48:34.222482 [ 60554 ] {} <Fatal> BaseDaemon: 21. /home/jakalletti/ClickHouse/ClickHouse/build-clang-debug/../contrib/libcxx/include/functional:1714: std::__1::__function::__func<DB::PipelineExecutor::addJob(DB::ExecutingGraph::Node*)::$_0, std::__1::allocator<DB::PipelineExecutor::addJob(DB::ExecutingGraph::Node*)::$_0>, void ()>::operator()() @ 0x30ef6d4e in /home/jakalletti/ClickHouse/ClickHouse/build-clang-debug/programs/clickhouse
2020.09.09 15:48:34.224242 [ 60554 ] {} <Fatal> BaseDaemon: 22. /home/jakalletti/ClickHouse/ClickHouse/build-clang-debug/../contrib/libcxx/include/functional:1867: std::__1::__function::__value_func<void ()>::operator()() const @ 0x25ccb0f5 in /home/jakalletti/ClickHouse/ClickHouse/build-clang-debug/programs/clickhouse
2020.09.09 15:48:34.224544 [ 60554 ] {} <Fatal> BaseDaemon: 23. /home/jakalletti/ClickHouse/ClickHouse/build-clang-debug/../contrib/libcxx/include/functional:2473: std::__1::function<void ()>::operator()() const @ 0x25cca015 in /home/jakalletti/ClickHouse/ClickHouse/build-clang-debug/programs/clickhouse
2020.09.09 15:48:34.268480 [ 60554 ] {} <Fatal> BaseDaemon: 24. /home/jakalletti/ClickHouse/ClickHouse/build-clang-debug/../src/Processors/Executors/PipelineExecutor.cpp:559: DB::PipelineExecutor::executeStepImpl(unsigned long, unsigned long, std::__1::atomic<bool>*) @ 0x30ef5665 in /home/jakalletti/ClickHouse/ClickHouse/build-clang-debug/programs/clickhouse
2020.09.09 15:48:34.311235 [ 60554 ] {} <Fatal> BaseDaemon: 25. /home/jakalletti/ClickHouse/ClickHouse/build-clang-debug/../src/Processors/Executors/PipelineExecutor.cpp:472: DB::PipelineExecutor::executeSingleThread(unsigned long, unsigned long) @ 0x30ef5e59 in /home/jakalletti/ClickHouse/ClickHouse/build-clang-debug/programs/clickhouse
2020.09.09 15:48:34.355083 [ 60554 ] {} <Fatal> BaseDaemon: 26. /home/jakalletti/ClickHouse/ClickHouse/build-clang-debug/../src/Processors/Executors/PipelineExecutor.cpp:729: DB::PipelineExecutor::executeImpl(unsigned long)::$_4::operator()() const @ 0x30ef9fac in /home/jakalletti/ClickHouse/ClickHouse/build-clang-debug/programs/clickhouse
2020.09.09 15:48:34.400146 [ 60554 ] {} <Fatal> BaseDaemon: 27. /home/jakalletti/ClickHouse/ClickHouse/build-clang-debug/../contrib/libcxx/include/type_traits:3525: decltype(std::__1::forward<DB::PipelineExecutor::executeImpl(unsigned long)::$_4 const&>(fp)()) std::__1::__invoke_constexpr<DB::PipelineExecutor::executeImpl(unsigned long)::$_4 const&>(DB::PipelineExecutor::executeImpl(unsigned long)::$_4 const&) @ 0x30ef9f0d in /home/jakalletti/ClickHouse/ClickHouse/build-clang-debug/programs/clickhouse
2020.09.09 15:48:34.444150 [ 60554 ] {} <Fatal> BaseDaemon: 28. /home/jakalletti/ClickHouse/ClickHouse/build-clang-debug/../contrib/libcxx/include/tuple:1415: decltype(auto) std::__1::__apply_tuple_impl<DB::PipelineExecutor::executeImpl(unsigned long)::$_4 const&, std::__1::tuple<> const&>(DB::PipelineExecutor::executeImpl(unsigned long)::$_4 const&, std::__1::tuple<> const&, std::__1::__tuple_indices<>) @ 0x30ef9ed1 in /home/jakalletti/ClickHouse/ClickHouse/build-clang-debug/programs/clickhouse

```

### PR DESCRIPTION
**Pull request by 4ertus2**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix crash in case of not equi-join ON expression in RIGH|FULL JOIN.

Fixes #14627
Related to #8802

### CODE REVIEW

**Comment by 4ertus2** [comment]
The problem with PR is distributed queries expects ON with `_shard_num` working
```
SELECT * FROM a JOIN b ON _shard_num = b.shard_num
```

**Review by alexey-milovidov — APPROVED** [review]

**Comment by PHaroZ** [comment]
Hi,

This PR breaks a lots of queries in my app : queries like
```sql
SELECT
	t.value,
	i18n.title
FROM
	aTable t
	LEFT ANY JOIN aTable_i18n i18n
	          ON i18n.ref_id = t.id AND i18n.lang = 'en'
```

Is it really what you wanted or it's an unexpected side-effect ?

**Comment by vlauzeckas** [comment]
yes, new version of clickhouse corrupts number of queries:

`SELECT * FROM (SELECT NULL AS a, 1 AS b) AS foo
RIGHT JOIN (SELECT 1024 AS b) AS bar
ON 1 = foo.b;` 

throws error:  Not equi-join ON expression: 1 = b. No columns in one of equality side.: While processing 1 = b 

whats wrong in joining on value=column? works in any other database

**Comment by jobosk** [comment]
I believe this fix has broken "equi join" using strings, like this:

image

Forcing me to move those ON conditions to the WHERE:

image

**Comment by vdimir** [comment]
@jobosk Seems that it's different case. 

Now conditions that is not in the form `t1.col1 = t2.col2` where `t1` and `t2` different tables is not supported, except case of `INNER` join (for such cases conditions moved to `WHERE` on query processing, see https://github.com/ClickHouse/ClickHouse/issues/18720). Conditions that depends on one table in `ON` and `WHERE` sections have slightly different semantic (see https://github.com/ClickHouse/ClickHouse/pull/19685#discussion_r570924525).

We considered to support such conditions in `ON` section, but now there's no ETA for this. I'll create an issue.

**Comment by jobosk** [comment]
> @jobosk Seems that it's different case.
> 
> Now conditions that is not in the form `t1.col1 = t2.col2` where `t1` and `t2` different tables is not supported, except case of `INNER` join (for such cases conditions moved to `WHERE` on query processing, see #18720). Conditions that depends on one table in `ON` and `WHERE` sections have slightly different semantic (see [#19685 (comment)](https://github.com/ClickHouse/ClickHouse/pull/19685#discussion_r570924525)).
> 
> We considered to support such conditions in `ON` section, but now there's no ETA for this. I'll create an issue.
> 
> UPD: _Comment by @jobosk to that I answered had been deleted from this thread_

Sorry! I deleted my comment after updating to 21.3.2.5, and not having an issue with that version I assumed it was fixed afterwards. Didn't see your reply, the page must've been cached.

For anyone who wonders what it was about: I had a problem after migrating to server v21.1.7.1 using conditions like r1.col1 = 'string' in the ON section of my JOIN.

Since I deleted my comment and don't have access to the code right now, I'm not sure wether it was an INNER JOIN and it was indeed a problem with that version later fixed, or if wasn't, in which case I'm not really sure why it does work with later versions. I'll let you know as soon as I have access to the code.

**Pull request merged**
