### PR TITLE
fix docs anchor

### LINKED ISSUE #24060: When anchor is used, it's hidden behind header on documentation pages
(you don't have to strictly follow this form)

**Describe the issue**
When an anchor is used, the page is scrolled too much and the relevant place hidden by gray header row. For example, https://clickhouse.tech/docs/en/operations/settings/settings/#cancel-http-readonly-queries-on-client-close: only `Default value: 0` is visible to me

**Additional context**
Browser: Firefox 88.0-1 on Arch linux

### PR DESCRIPTION
**Pull request by cmsxbc**
Changelog category (leave one):
- Documentation (changelog entry is not required)

Detailed description / Documentation draft:
Close #24060

Using [scroll-margin-top](https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-margin-top), which should work on all modern browsers.

Limit to hardware, I have tested on:

- Firefox 95 on Linux 
- Chromium 96 on Linux
- Chrome 93 on Linux
- Edge 96 on Windows
- Edge 45 on Android 11 (single page)
- Chrome 96 on iOS 14.8 (single page)
- Safari on iOS 14.8 (single page)

If any other compatibles are required, I need help for test environments.

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
@mergifyio update

**Review by vdimir — APPROVED** [review]
Great job!

**Comment by alexey-milovidov** [comment]
Looks like this pull request enabled animation in the main menu.
We have strict no amination policy in our website.
Let's check if revert will help.

**Comment by cmsxbc** [comment]
> Looks like this pull request enabled animation in the main menu. We have strict no amination policy in our website. Let's check if revert will help.

Are you talking about animation when clicking on the left sidecar?

**Comment by alexey-milovidov** [comment]
Yes.

**Comment by alexey-milovidov** [comment]
Maybe it is not so bad, but I have a pet peeve on animations.

**Comment by cmsxbc** [comment]
> Maybe it is not so bad, but I have a pet peeve on animations.

No, it's ok. I can guarantee what I do will not cause animations.0 0 The animation seems to cause by bootstrap.js or some other framework. I'd like to help you find the reason.

And it's ok to revert to verify this. It's your code anyway.

**Pull request merged**
