### PR TITLE
Don't add metadata_version file if it doesn't exist

### PR DESCRIPTION
**Pull request by alesapin**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Not for changelog since it wasn't released yet.

### CODE REVIEW

**Review by tavplubix — APPROVED** [review]

**Comment by tavplubix** [comment]
Integration tests failures are suspicious

**Comment by alesapin** [comment]
100% related

**Comment by robot-clickhouse-ci-2** [comment]
This is an automated comment for commit b5589fcbfc0f6a993a24598fb6fc10e923528db7 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/49146/b5589fcbfc0f6a993a24598fb6fc10e923528db7/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Comment by alesapin** [comment]
How I did it :(((

**Comment by alesapin** [comment]
Wait for integration tests only

**Comment by alesapin** [comment]
Okay, passed tests enough

**Pull request merged**
