### PR TITLE
Fix calculating loading dependencies

### LINKED ISSUE #39416: RESTORE can't recognize source table during restore materialized view
**Describe what's wrong**
I can't restore MATERIALIZED VIEW if source table doesn't exists in system

**Does it reproduce on recent release?**
Yes, 22.7.x docker image `clickhouse/clickhouse-server:head`

**How to reproduce**

*/etc/clickhouse-server/config.d/backup_storage_configuration.xml*
```xml
<clickhouse>
    <storage_configuration>
        <disks>
            <backups>
              <send_metadata>true</send_metadata>
              <type>s3</type>
              <endpoint>http://minio:9000/clickhouse/backups/</endpoint>
              <access_key_id>access-key</access_key_id>
              <secret_access_key>it-is-my-super-secret-key</secret_access_key>
              <!-- to avoid unnecessary disk space allocations -->
              <cache_enabled>false</cache_enabled>
            </backups>
        </disks>
    </storage_configuration>
    <backups>
        <allowed_disk>backups</allowed_disk>
    </backups>
    <merge_tree>
        <allow_remote_fs_zero_copy_replication>1</allow_remote_fs_zero_copy_replication>
    </merge_tree>
</clickhouse>

```

```sql
DROP DATABASE IF EXISTS `_test.ДБ_atomic_` SYNC;
CREATE DATABASE `_test.ДБ_atomic_` ENGINE = Atomic;

CREATE TABLE `_test.ДБ_atomic_`.mv_src_table UUID 'a06c0bae-95f1-4b55-a94a-25f121020844' (`id` UInt64) ENGINE = ReplicatedMergeTree('/clickhouse/tables/_test.ДБ_atomic_/mv_src_table', 'replica1') ORDER BY id SETTINGS index_granularity = 8192;

CREATE TABLE `_test.ДБ_atomic_`.mv_dst_table UUID 'b9498dba-0a2f-4a9a-99f4-30c7add40d79' (`id` UInt64) ENGINE = ReplicatedMergeTree('/clickhouse/tables/_test.ДБ_atomic_/mv_dst_table', 'replica1') ORDER BY id SETTINGS index_granularity = 8192;

CREATE MATERIALIZED VIEW `_test.ДБ_atomic_`.mv_max_with_dst UUID 'aa5fcc4a-db19-4d94-a8f2-f4157fa330e0' TO `_test.ДБ_atomic_`.mv_dst_table (`id` UInt64) AS SELECT max(id) AS id FROM `_test.ДБ_atomic_`.mv_src_table;
 
BACKUP TABLE `_test.ДБ_atomic_`.`mv_dst_table`, TABLE `_test.ДБ_atomic_`.`mv_max_with_dst`, TABLE `_test.ДБ_atomic_`.`mv_src_table` TO Disk('backups','test_backup');

DROP TABLE `_test.ДБ_atomic_`.mv_max_with_dst SYNC;
DROP TABLE `_test.ДБ_atomic_`.mv_src_table SYNC;
DROP TABLE `_test.ДБ_atomic_`.mv_dst_table SYNC;

RESTORE TABLE `_test.ДБ_atomic_`.`mv_src_table`, TABLE `_test.ДБ_atomic_`.`mv_dst_table`, TABLE `_test.ДБ_atomic_`.`mv_max_with_dst` FROM Disk('backups','test_backup');

```

**Expected behavior**
successfulls BACKUP and RESTORE 

**Actual behavior**
RESTORE failed

**Error message and/or stacktrace**
```
Received exception from server (version 22.7.1):
Code: 60. DB::Exception: Received from localhost:9000. DB::Exception: Table `_test.ДБ_atomic_`.mv_src_table doesn't exist: While creating table `_test.ДБ_atomic_`.mv_max_with_dst. (UNKNOWN_TABLE)
```

**Additional logs**

```
2022.07.20 10:49:31.756384 [ 273 ] {9089bd20-0499-45ad-be4f-f4f2f2a7fff3} <Debug> executeQuery: (from 127.0.0.1:43012) RESTORE TABLE `_test.ДБ_atomic_`.`mv_src_table`, TABLE `_test.ДБ_atomic_`.`mv_dst_table`, TABLE `_test.ДБ_atomic_`.`mv_max_with_dst` FROM Disk('backups','test_backup'); (stage: Complete)
2022.07.20 10:49:31.767383 [ 273 ] {9089bd20-0499-45ad-be4f-f4f2f2a7fff3} <Trace> RestorerFromBackup: Will use paths in backup: "/"
2022.07.20 10:49:31.767478 [ 273 ] {9089bd20-0499-45ad-be4f-f4f2f2a7fff3} <Trace> RestorerFromBackup: Finding tables in backup
2022.07.20 10:49:31.799127 [ 273 ] {9089bd20-0499-45ad-be4f-f4f2f2a7fff3} <Information> RestorerFromBackup: Will restore 0 databases and 3 tables
2022.07.20 10:49:31.799364 [ 273 ] {9089bd20-0499-45ad-be4f-f4f2f2a7fff3} <Trace> ContextAccess (default): Access granted: CREATE TABLE ON `_test.ДБ_atomic_`.mv_dst_table
2022.07.20 10:49:31.799532 [ 273 ] {9089bd20-0499-45ad-be4f-f4f2f2a7fff3} <Trace> ContextAccess (default): Access granted: CREATE VIEW ON `_test.ДБ_atomic_`.mv_max_with_dst
2022.07.20 10:49:31.799586 [ 273 ] {9089bd20-0499-45ad-be4f-f4f2f2a7fff3} <Trace> ContextAccess (default): Access granted: CREATE TABLE ON `_test.ДБ_atomic_`.mv_src_table
2022.07.20 10:49:31.799648 [ 273 ] {9089bd20-0499-45ad-be4f-f4f2f2a7fff3} <Trace> RestorerFromBackup: Creating databases
2022.07.20 10:49:31.799700 [ 273 ] {9089bd20-0499-45ad-be4f-f4f2f2a7fff3} <Trace> RestorerFromBackup: Creating tables
2022.07.20 10:49:31.799848 [ 273 ] {9089bd20-0499-45ad-be4f-f4f2f2a7fff3} <Trace> RestorerFromBackup: Creating table `_test.ДБ_atomic_`.mv_dst_table: CREATE TABLE IF NOT EXISTS `_test.ДБ_atomic_`.mv_dst_table (`id` UInt64) ENGINE = ReplicatedMergeTree('/clickhouse/tables/_test.ДБ_atomic_/mv_dst_table', 'replica1') ORDER BY id SETTINGS index_granularity = 8192
2022.07.20 10:49:31.814877 [ 273 ] {9089bd20-0499-45ad-be4f-f4f2f2a7fff3} <Debug> `_test.ДБ_atomic_`.mv_dst_table (31ffb8f2-2bc7-43d6-b2cf-63ad4d65b541): Loading data parts
2022.07.20 10:49:31.815647 [ 273 ] {9089bd20-0499-45ad-be4f-f4f2f2a7fff3} <Debug> `_test.ДБ_atomic_`.mv_dst_table (31ffb8f2-2bc7-43d6-b2cf-63ad4d65b541): There are no data parts
2022.07.20 10:49:31.845224 [ 273 ] {9089bd20-0499-45ad-be4f-f4f2f2a7fff3} <Debug> `_test.ДБ_atomic_`.mv_dst_table (31ffb8f2-2bc7-43d6-b2cf-63ad4d65b541): Creating table /clickhouse/tables/_test.ДБ_atomic_/mv_dst_table
2022.07.20 10:49:31.916176 [ 273 ] {9089bd20-0499-45ad-be4f-f4f2f2a7fff3} <Information> `_test.ДБ_atomic_`.mv_dst_table (31ffb8f2-2bc7-43d6-b2cf-63ad4d65b541): Became leader
2022.07.20 10:49:31.916506 [ 335 ] {} <Debug> `_test.ДБ_atomic_`.mv_dst_table (ReplicatedMergeTreeRestartingThread): Activating replica.
2022.07.20 10:49:31.934077 [ 335 ] {} <Trace> `_test.ДБ_atomic_`.mv_dst_table (ReplicatedMergeTreeQueue): Initializing parts in queue
2022.07.20 10:49:31.937040 [ 335 ] {} <Trace> `_test.ДБ_atomic_`.mv_dst_table (ReplicatedMergeTreeQueue): Queue initialized
2022.07.20 10:49:31.937135 [ 335 ] {} <Debug> `_test.ДБ_atomic_`.mv_dst_table (ReplicatedMergeTreeQueue): Loading queue from /clickhouse/tables/_test.ДБ_atomic_/mv_dst_table/replicas/replica1/queue
2022.07.20 10:49:31.939898 [ 335 ] {} <Debug> `_test.ДБ_atomic_`.mv_dst_table (ReplicatedMergeTreeQueue): Having 0 queue entries to load, 0 entries already loaded.
2022.07.20 10:49:31.948325 [ 335 ] {} <Trace> `_test.ДБ_atomic_`.mv_dst_table (ReplicatedMergeTreeQueue): Loaded queue

2022.07.20 10:49:31.973356 [ 273 ] {9089bd20-0499-45ad-be4f-f4f2f2a7fff3} <Trace> RestorerFromBackup: Creating table `_test.ДБ_atomic_`.mv_max_with_dst: CREATE MATERIALIZED VIEW IF NOT EXISTS `_test.ДБ_atomic_`.mv_max_with_dst TO `_test.ДБ_atomic_`.mv_dst_table (`id` UInt64) AS SELECT max(id) AS id FROM `_test.ДБ_atomic_`.mv_src_table
2022.07.20 10:49:31.981195 [ 273 ] {9089bd20-0499-45ad-be4f-f4f2f2a7fff3} <Error> BackupsWorker: Failed to restore from backup Disk('backups', 'test_backup'): Code: 60. DB::Exception: Table `_test.ДБ_atomic_`.mv_src_table doesn't exist: While creating table `_test.ДБ_atomic_`.mv_max_with_dst. (UNKNOWN_TABLE), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xba29d5a in /usr/bin/clickhouse
1. DB::DatabaseCatalog::getTableImpl(DB::StorageID const&, std::__1::shared_ptr<DB::Context const>, std::__1::optional<DB::Exception>*) const @ 0x165ed6ea in /usr/bin/clickhouse
2. DB::DatabaseCatalog::getTable(DB::StorageID const&, std::__1::shared_ptr<DB::Context const>) const @ 0x165f48cb in /usr/bin/clickhouse
3. DB::JoinedTables::getLeftTableStorage() @ 0x16bea625 in /usr/bin/clickhouse
4. DB::InterpreterSelectQuery::InterpreterSelectQuery(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context> const&, std::__1::optional<DB::Pipe>, std::__1::shared_ptr<DB::IStorage> const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, DB::SubqueryForSet, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, DB::SubqueryForSet> > >, std::__1::unordered_map<DB::PreparedSetKey, std::__1::shared_ptr<DB::Set>, DB::PreparedSetKey::Hash, std::__1::equal_to<DB::PreparedSetKey>, std::__1::allocator<std::__1::pair<DB::PreparedSetKey const, std::__1::shared_ptr<DB::Set> > > >) @ 0x16b6963f in /usr/bin/clickhouse
5. DB::InterpreterSelectQuery::InterpreterSelectQuery(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context> const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) @ 0x16b683b7 in /usr/bin/clickhouse
6. DB::InterpreterSelectWithUnionQuery::buildCurrentChildInterpreter(std::__1::shared_ptr<DB::IAST> const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) @ 0x16bb7da6 in /usr/bin/clickhouse
7. DB::InterpreterSelectWithUnionQuery::InterpreterSelectWithUnionQuery(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context>, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) @ 0x16bb5a74 in /usr/bin/clickhouse
8. DB::InterpreterCreateQuery::createTable(DB::ASTCreateQuery&) @ 0x16ada441 in /usr/bin/clickhouse
9. DB::InterpreterCreateQuery::execute() @ 0x16ae4a60 in /usr/bin/clickhouse
10. DB::DatabaseWithOwnTablesBase::createTableRestoredFromBackup(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context>, std::__1::shared_ptr<DB::IRestoreCoordination>, unsigned long) @ 0x16222d68 in /usr/bin/clickhouse
11. DB::RestorerFromBackup::createTable(DB::QualifiedTableName const&) @ 0x15dfdd00 in /usr/bin/clickhouse
12. DB::RestorerFromBackup::createTables() @ 0x15ddbefb in /usr/bin/clickhouse
13. DB::RestorerFromBackup::run(DB::RestorerFromBackup::Mode) @ 0x15dd8104 in /usr/bin/clickhouse
14. ? @ 0x15d8fd08 in /usr/bin/clickhouse
15. DB::BackupsWorker::startRestoring(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context>) @ 0x15d8c57d in /usr/bin/clickhouse
16. DB::BackupsWorker::start(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context>) @ 0x15d8b0ab in /usr/bin/clickhouse
17. DB::InterpreterBackupQuery::execute() @ 0x16b45fc2 in /usr/bin/clickhouse
18. ? @ 0x16ea0457 in /usr/bin/clickhouse
19. DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum) @ 0x16e9d895 in /usr/bin/clickhouse
```

### PR DESCRIPTION
**Pull request by vitlibar**
### Changelog category (leave one):
- Improvement

### Changelog entry:
Fix calculating loading dependencies for tables and dictionaries. This PR fixes https://github.com/ClickHouse/ClickHouse/issues/39416

### CODE REVIEW

**Comment by tavplubix** [comment]
Dependency between MV and its source/target tables is not a loading dependency. Currently we can successfully load MV, source and target tables independently in parallel and there's no reason to introduce loading dependency between them. It would be better to introduce another kind of dependencies between tables for this ("restore dependency" or "create dependency" (see #37081) or "referential integrity dependency" (see #38326)).

**Comment by Slach** [comment]
@vitlibar @TabaMojj @nikitamikhaylov any progress?

**Comment by vitlibar** [comment]
> @vitlibar @TabaMojj @nikitamikhaylov any progress?

I'm still going to finish this PR.

**Comment by vitlibar** [comment]
The work will be finished in https://github.com/ClickHouse/ClickHouse/pull/43834

**Pull request closed without merging**
