### PR TITLE
Remove branchy code in filter operation with a better implementation …

### PR DESCRIPTION
**Pull request by vesslanjin**
Optimize-column-string-filter-perf

Co-authored-by: Zhu Jasper <jasper.zhu@intel.com>

Changelog category (leave one):
* Performance Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
* Remove branchy code in filter operation with a better implementation with popcnt/ctz which have better performance

Detailed description / Documentation draft:

This optimization is to optimize filter operation in `ColumnFixedString`, `ColumnVector`, `ColumnCommon`, where we observed huge branch misprediction (as much as 10% on micro-benchmark) because the value in `filt_pos` is quite random. 
The optimized code removed the branch code by directly use of `ctz`, and we see much better performance on filtering
E.g. in `ColumnFixedString` with fixed buffer (n) size less than 32Bytes, it has more than 1.8X better on microbenchmark call filter only.
Larger fixed buffer size may have more bound on `memcpy` hence improvement by this optimization will be smaller

End to end test based on queries: 

Q1: `SELECT SearchPhrase FROM hits_100m_obfuscated WHERE SearchPhrase != '' ORDER BY EventTime, SearchPhrase LIMIT 10`

Q2: `SELECT SearchPhrase FROM hits_100m_obfuscated WHERE SearchPhrase != '' ORDER BY SearchPhrase LIMIT 10`

| Test      | Baseline   | optimized  | perf improvement |
| --------- | ---------- | ---------- | ---------------- |
|Q1         | 15.04ms    | 14.13ms    | 6.4%             |
|Q2         | 12.27ms    | 11.76ms    | 4.3%           |

Detailed Performance report 
[Performance report from CI](https://clickhouse-test-reports.s3.yandex.net/29881/3940382c2f4e84c17eb7b9ff8819eca1a1bc579d/performance_comparison/report.html)

update with DCO

Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

### CODE REVIEW

**Review by vdimir — COMMENTED** [review]
Great! Most of comments is white-space changes too keep style consistent with other code, and only couple ones is substantive comments.

**Review by vdimir — APPROVED** [review]
Thank you for your changes!

I think we do not need `#if defined(__POPCNT__)` anymore, because we removed `__builtin_popcount`, I'm going to remove this lines, wait build in CI and merge.

**Comment by vesslanjin** [comment]
@vdimir  hi Vdimir, I've just learn I don't have the authority to sign CLA, and I've added the DCO in the PR. Can you pls remove the CLA sign for me?  sorry ~

**Comment by alexey-milovidov** [comment]
@vesslanjin This comment is enough to withdraw your CLA.

**Comment by vesslanjin** [comment]
> @vesslanjin This comment is enough to withdraw your CLA.

thanks a lot Alexey.

**Pull request merged**
