### PR TITLE
random optimize_trivial_insert_select for tests

### PR DESCRIPTION
**Pull request by max-vostrikov**
test randomised optimize_trivial_insert_select

### Changelog category (leave one):
- CI Fix or Improvement (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
...

### Documentation entry for user-facing changes

- [x] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [x]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Run only fuzzers related jobs (libFuzzer fuzzers, AST fuzzers, etc.)
- [ ]  Exclude: AST fuzzers
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-clickhouse** [comment]
*This is an automated comment for commit 1cf4eac3b90d9a50fdb2b5c46de30040e63b46d0 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/68529/1cf4eac3b90d9a50fdb2b5c46de30040e63b46d0/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Style check</td><td>Runs a set of checks to keep the code style clean. If some of tests failed, see the related log from the report</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/68529/1cf4eac3b90d9a50fdb2b5c46de30040e63b46d0/style_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Comment by yariks5s** [comment]
Strangely, I don't even see any stateless tests in the list of tests that were run

**Comment by yariks5s** [comment]
> Strangely, I don't even see any stateless tests in the list of tests that were run

ah, the problem was in CI settings in the description of the PR. Will change it now and re-trigger the CI.

**Comment by max-vostrikov** [comment]
after some investigation, there were multiple problems with this one. Closing instead

**Pull request closed without merging**
