### PR TITLE
refine code in MergeTreeData::loadDataParts to avoid parsing WAL file as data part

### PR DESCRIPTION
**Pull request by fuwhu**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one): 
- Not for changelog (changelog entry is not required)

refine code in MergeTreeData::loadDataParts to avoid parsing WAL file as data part

### CODE REVIEW

**Comment by CurtizJ** [comment]
Fuzzer: #18793

**Review by CurtizJ — APPROVED** [review]
Ok.

**Comment by fuwhu** [comment]
> Fuzzer error: #18793

How shall i fix this error or just leave it as it is?

**Comment by CurtizJ** [comment]
Leave it as is. In fuzz check all queries are being fuzzed and sometimes it finds random errors, which are not related to PR changes.

**Pull request merged**
