### PR TITLE
some perf test script improvements

### PR DESCRIPTION
**Pull request by akuzm**
Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
@mergifyio update

**Comment by alexey-milovidov** [comment]
> test_distributed_queries_stress

WTF

**Comment by alexey-milovidov** [comment]
@akuzm I have no idea why
> joins_in_memory

timed out.

**Comment by akuzm** [comment]
```
2021.06.06 20:24:41.235761 [ 184 ] {joins_in_memory.query9.prewarm0} <Debug> executeQuery: (from [::1]:51590, using production parser) SELECT COUNT() FROM ints l LEFT JOIN ints r USING i64,i32,i16,i8 WHERE i32 = 20042 settings query_plan_filter_push_down = 0
...
2021.06.06 20:24:42.469517 [ 7403 ] {joins_in_memory.query9.prewarm0} <Trace> Aggregator: Merging aggregated data
2021.06.06 20:29:59.744157 [ 184 ] {joins_in_memory.query9.prewarm0} <Information> TCPHandler: Client has dropped the connection, cancel the query.
```

The prewarm run with enabled query profiler is timing out. This also happens in master, likely some libunwind problem.

**Pull request merged**
