### PR TITLE
Add system.dropped_tables_projection_parts_columns (and respect dropped projection parts in 01600_parts_states_metrics_long)

### PR DESCRIPTION
**Pull request by azat**
**Blocked by: https://github.com/ClickHouse/ClickHouse/pull/68521**

### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Add system.dropped_tables_projection_parts_columns

This is **mostly for tests**, since dropped projection parts could be another source of the `01600_parts_states_metrics_long` failures

Refs: https://github.com/ClickHouse/ClickHouse/issues/68255

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
Does it make any sense to the user?
Why don't just delete the test `01600_parts_states_metrics_long` instead?

**Comment by alexey-milovidov** [comment]
I'm against weird tables.

**Comment by robot-clickhouse-ci-2** [comment]
*This is an automated comment for commit 8c5e19b9bef0524c211ad900b1f907ed96539215 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/68522/8c5e19b9bef0524c211ad900b1f907ed96539215/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/67bbe6fe98c41958067bf68370232a0eb24af1f7/docs_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Comment by azat** [comment]
Agree.
Couple of thoughts here.

Maybe `system.dropped_tables_parts` should also be removed? The purpose AFAIU is indeed to track this counter - https://github.com/ClickHouse/ClickHouse/pull/58038#issuecomment-1866771302 (cc @yakov-olkhovskiy )

Or/and maybe partitions parts should not have different tables, and instead be a column in `system.parts`? Though this will complicate the code slightly so not sure that this is a good idea.

**Comment by yakov-olkhovskiy** [comment]
I think the information about deleted but not yet physically removed parts maybe still useful, and ideologically it's not good when we have no idea about physically present data...

**Comment by azat** [comment]
For this purpose I guess `system.dropped_tables` should be enough

**Comment by yakov-olkhovskiy** [comment]
`system.dropped_tables` only contains metadata info, not physical data info - I think we have to keep symmetry - we have `system.tables` and `system.parts` - so we want to have `system.dropped_tables` and `system.dropped_tables_parts`

**Comment by alexey-milovidov** [comment]
This table is complex to reason about, and if it is needed only for tests, it is better not to have it.

**Pull request closed without merging**
