### PR TITLE
Improve the opentelemetry span logs for INSERT on distributed table

### PR DESCRIPTION
**Pull request by FrankChen021**
Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
- Improve the opentelemetry span logs for INSERT operation on distributed table

## Description

INSERT on distributed table invovles data insert on local node or remote nodes. It's crucial to know which nodes are scheduled to handle the INSERT on local tables. For such key execution path, the distributed tracing feature is very useful to provide us these information for problem addressing.

But current span logs does not give us these informations. For example:

If the data is written to the same node where the initial query is executed,
image

current span logs only shows the initial query and does not know how this distributed table INSERT is scheduled.

And this is span logs for an INSERT in asynchronous way, the spans logs on remote servers are missing due to internal trace context propagation problem. It's not able for users to get know which remote server is scheduled to execute the INSERT query on local table.

image

## Solution

1. In this PR, some spans logs are added to the execution flows of INSERT on distributed table, such as `writeSync`, `writeToLocal`, `writeToShard` so that it's very clear from the span logs that how such query is scheduled among different nodes.

2. INSERT query on local table is also logged in the span log

3. Also, for async written on remote servers, this PR fixes the trace context propagation so that the remote ClickHouse can receive right trace context so that the tracing on the remote is enabled and the span logs on the remote can be correctly linked together with the span logs on the original node.

4. this PR also deletes a span log from `InterpreterSelectQuery::getSampleBlockImpl` because this span is not important and may cause lots of this  span in logs when the INSERT query invovles many MVs. 

## Result

After this PR, the span logs looks like:

- write to local node under `insert_distributed_sync=1`
image

- write to remote node under `insert_distributed_sync=1`
image

- write to local in async way which means `insert_distributed_sync=0`
image

- write to remote in async way which means `insert_distributed_sync=0`
image

### CODE REVIEW

**Comment by nikitamikhaylov** [comment]
@Mergifyio update

**Comment by FrankChen021** [comment]
Hi @nikitamikhaylov , any opinions on this PR?

**Comment by FrankChen021** [comment]
Seems like that the failed check has nothing to do with the changes in this PR. 

@nikitamikhaylov Let me know if you have any comments. I'm going to open another PR to resolve trace context propagation problem which relies some changes on this PR. So I hope this PR could be merged as soon as possible.

**Review by nikitamikhaylov — APPROVED** [review]

**Comment by FrankChen021** [comment]
Thank you @nikitamikhaylov

**Pull request merged**
