### PR TITLE
Support backup/restore for MaterializedPostgreSQL

### LINKED ISSUE #44252: BACKUP doesn't work with database engine MaterializedPostgreSQL
**Describe what's wrong**
PostgreSQL
```bash
echo 'CREATE DATABASE ch_pgsql_repl' | PGPASSWORD=root psql -v ON_ERROR_STOP=1 -U root

CREATE DATABASE

echo "CREATE TABLE t1 (id BIGINT PRIMARY KEY, s VARCHAR(255)); INSERT INTO t1(id, s) VALUES(1,'s1'),(2,'s2'),(3,'s3')" | PGPASSWORD=root psql -v ON_ERROR_STOP=1 -U root -d ch_pgsql_repl

CREATE TABLE
INSERT 0 3
```

ClickHouse
```sql
CREATE DATABASE ch_pgsql_repl ENGINE=MaterializedPostgreSQL('pgsql:5432','ch_pgsql_repl','root','root') 
SETTINGS materialized_postgresql_allow_automatic_update = 1, materialized_postgresql_schema = 'public';

SHOW TABLES FROM ch_pgsql_repl;
┌─name─┐
│ t1   │
└──────┘

BACKUP DATABASE ch_pgsql_repl TO File('ch_pgsql_repl.zip');
Query id: d9df1341-64dd-4335-88c4-ad55e99c7854
// query stuck
```
tail -f /var/log/clickhouse-server/clickhouse-server.err.log
inifinte messages
```
 <Warning> BackupEntriesCollector: DB::Exception: Table ch_pgsql_repl.t1 were created or changed its definition during scanning
```

`KILL QUERY WHERE query_id='d9df1341-64dd-4335-88c4-ad55e99c7854'` also doesn't work
**Does it reproduce on recent release?**
Yes, tested on Head and 22.11

**Expected behavior**
Successful backup, Inside database we just have `ReplacingMergeTree(_version)` table

### PR DESCRIPTION
**Pull request by kssenii**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Support backup/restore for MaterializedPostgreSQL. Closes https://github.com/ClickHouse/ClickHouse/issues/44252.

### CODE REVIEW

**Comment by robot-clickhouse** [comment]
*This is an automated comment for commit 9cd09131d4d428d5d2e263d7d697c1b64f05f728 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/57789/9cd09131d4d428d5d2e263d7d697c1b64f05f728/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td><a href="https://github.com/ClickHouse/ClickHouse/actions/runs/7184130283">✅ success</a></td></tr>
<tbody>
</table>
</details>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/57789/9cd09131d4d428d5d2e263d7d697c1b64f05f728/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Comment by Slach** [comment]
@kssenii god bles you ;)

**Comment by alexey-milovidov** [comment]
@Slach "bless" with two "s".

**Comment by Slach** [comment]
@alexey-milovidov you will burn in the hel, gramanazi

**Comment by jpchev** [comment]
@alexey-milovidov why has this been closed? It was a fix for https://github.com/ClickHouse/ClickHouse/issues/44252

**Comment by alexey-milovidov** [comment]
It was unfinished. Ok to reopen.

**Comment by jpchev** [comment]
> It was unfinished. Ok to reopen.

@kssenii possible to reopen this PR?

**Pull request closed without merging**
