### PR TITLE
ISSUES-320 Fix rewrite expression

### LINKED ISSUE #320: Cannot select column from view
After create this view:

```
CREATE TABLE Test (
    createdDate Date,
    str String,
    key Enum8('A' = 0, 'B' = 1, 'ALL' = 2),
    a Int64
)
 ENGINE = MergeTree(createdDate, str, 8192);


CREATE VIEW TestView AS
    SELECT str, key, sumIf(a, 0) AS sum
    FROM Test
    GROUP BY str, key
    
    UNION ALL
    
    SELECT str AS str, CAST('ALL' AS Enum8('A' = 0, 'B' = 1, 'ALL' = 2)) AS key, sumIf(a, 0) AS sum
    FROM Test
    GROUP BY str
```

I try to select any column, eg:

`SELECT str FROM TestView`

And receive this exception:

```
Received exception from server:
Code: 47. DB::Exception: Received from localhost:9000, 127.0.0.1. DB::Exception: Unknown column: 0, there are only columns str, a. 
```

### PR DESCRIPTION
**Pull request by zhang2014**
fix #320 
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
autotests

**Comment by zhang2014** [comment]
Would you please let me see the details of the error? for example: "https://travis-ci.org/apache/incubator-servicecomb-saga/builds/329913893?utm_source=github_status&utm_medium=notification"

**Comment by alexey-milovidov** [comment]
stateless.00195_shard_union_all_and_global_in
stateless.00506_global_in_union

**Comment by zhang2014** [comment]
@alexey-milovidov please help review the changes

**Comment by alexey-milovidov** [comment]
Thanks.

Minor modifications:
https://github.com/yandex/ClickHouse/commit/75fb48c94c2b33b4fe9610e5e072a3c8c486be72
https://github.com/yandex/ClickHouse/commit/03adf79fdca7de5d8aeceee2abacd82262758ea1

**Pull request merged**
