### PR TITLE
Don't run ASAN unit tests under gdb

### LINKED ISSUE #60559: UnitTest LeakSanitizer  might not work?
ClickHouse Unit ASAN test employs gdb to print the call stack 
```
gdb -q  -ex 'set print inferior-events off' -ex 'set confirm off' -ex 'set print thread-events off' -ex run -ex bt -ex quit --args ./src/unit_tests_dbms --gtest_output='json:test_output/test_result.json' | tee test_output/test_result.txt
```

But at the end of report it says:
```
2024-02-28T18:12:36.9058897Z ==19==LeakSanitizer has encountered a fatal error.
2024-02-28T18:12:36.9060319Z ==19==HINT: For debugging, try setting environment variable LSAN_OPTIONS=verbosity=1:log_threads=1
2024-02-28T18:12:36.9060591Z ==19==HINT: LeakSanitizer does not work under ptrace (strace, gdb, etc)
2024-02-28T18:12:36.9713998Z [Inferior 1 (process 19) exited with code 01]
```

It appears that LeakSanitizer didn't function correctly. Is this behavior expected, or am I misunderstanding something?

Also, 
https://github.com/ClickHouse/ClickHouse/blob/0ad0344dc78d761a20acad2a0b285c79dc4287e5/src/Common/tests/gtest_lsan.cpp#L17

gtest_lsan might work because ASSERT_EXIT utilizes fork() to execute. So it can not detect it.

### PR DESCRIPTION
**Pull request by Algunenano**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Don't run ASAN unit tests under gdb.

LeakSanitizer does not work under gdb. Closes https://github.com/ClickHouse/ClickHouse/issues/60559

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-clickhouse-ci-2** [comment]
*This is an automated comment for commit 4e9761acf93a58a93186f59d3ad083fd438329dc with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/67622/4e9761acf93a58a93186f59d3ad083fd438329dc/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Builds</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/67619/91014e2e013bf4c8c067b8a436c761d0a18a8dc5/builds/report.html">✅ success</a></td></tr>
<tr><td>ClickBench</td><td>Runs [ClickBench](https://github.com/ClickHouse/ClickBench/) with instant-attach table</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/c0bd2120c89a4c71820e4d4d4b5d0c0a9dc66042/clickbench__aarch64_.html">✅ success</a></td></tr>
<tr><td>Compatibility check</td><td>Checks that <b>clickhouse</b> binary runs on distributions with old libc versions. If it fails, ask a maintainer for help</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/c0bd2120c89a4c71820e4d4d4b5d0c0a9dc66042/compatibility_check__aarch64_.html">✅ success</a></td></tr>
<tr><td>Docker keeper image</td><td>The check to build and optionally push the mentioned image to docker hub</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/c0bd2120c89a4c71820e4d4d4b5d0c0a9dc66042/docker_keeper_image.html">✅ success</a></td></tr>
<tr><td>Docker server image</td><td>The check to build and optionally push the mentioned image to docker hub</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/c0bd2120c89a4c71820e4d4d4b5d0c0a9dc66042/docker_server_image.html">✅ success</a></td></tr>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td>✅ success</td></tr>
<tr><td>Fast test</td><td>Normally this is the first check that is ran for a PR. It builds ClickHouse and runs most of <a href="https://clickhouse.com/docs/en/development/tests#functional-tests">stateless functional tests</a>, omitting some. If it fails, further checks are not started until it is fixed. Look at the report to see which tests fail, then reproduce the failure locally as described <a href="https://clickhouse.com/docs/en/development/tests#functional-test-locally">here</a></td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/bf98336819d167f0c64c5ea868a5c7a4f52ca348/fast_test.html">✅ success</a></td></tr>
<tr><td>Install packages</td><td>Checks that the built packages are installable in a clear environment</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/c0bd2120c89a4c71820e4d4d4b5d0c0a9dc66042/install_packages__aarch64_.html">✅ success</a></td></tr>
<tr><td>Stateful tests</td><td>Runs stateful functional tests for ClickHouse binaries built in various configurations -- release, debug, with sanitizers, etc</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/c0bd2120c89a4c71820e4d4d4b5d0c0a9dc66042/stateful_tests__aarch64_.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Comment by nikitamikhaylov** [comment]
Should we do the same for Stress tests?

**Comment by Algunenano** [comment]
> 
Should we do the same for Stress tests?

Probably. And we should fail when we detect them too: https://github.com/ClickHouse/ClickHouse/issues/67624. I'll have a look

**Comment by Algunenano** [comment]
Still no failure from CI, even though the process is crashing:
```
SUMMARY: AddressSanitizer: 503296 byte(s) leaked in 7864 allocation(s).
timeout: the monitored command dumped core
/run.sh: line 27:     7 Aborted                 timeout 40m ./unit_tests_dbms --gtest_output='json:test_output/test_result.json'
         8 Done                    | tee test_output/test_result.txt
```

**Comment by Algunenano** [comment]
Failures in fuzzer: CI problem. It reused builds from an old commit and CI scripts from a new one, and there is a difference in settings

**Pull request merged**
