### PR TITLE
Check changed server configuration with higher precision

### LINKED ISSUE #53276: Configuration is not reloaded if changed too fast
**Describe the issue**
ClickHouse only reloads config file if the modification time changes. This is detected with `FS::getModificationTime`, which only has a resolution of one second. This means ClickHouse may miss changes if they happen within the same seconds as the previous change.

### PR DESCRIPTION
**Pull request by mkmkme**
Closes #53276

Previously it used `FS::getModificationTime` which has only a second precision. This caused an issue in some cases where the configuration has been changed more frequently than once per second, and the change wasn't propagated. This commit fixes that issue.

### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Changes of the server configuration are now detected with high precision (milliseconds and less).

### CODE REVIEW

**Comment by mkmkme** [comment]
I can't assign a reviewer to this PR, so pinging @rschu1ze via the message :)

**Comment by robot-ch-test-poll2** [comment]
This is an automated comment for commit 021c6077253adb65145ac16c59911e72f8fbba26 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/54065/021c6077253adb65145ac16c59911e72f8fbba26/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Review by rschu1ze — APPROVED** [review]

**Comment by rschu1ze** [comment]
Merged from `master`. Let's see if that helps.

**Comment by mkmkme** [comment]
Failure in `01099_operators_date_and_timestamp` also doesn't seem related (although a bit fishy). I couldn't reproduce it locally.

**Comment by rschu1ze** [comment]
@mkmkme [CI stats](https://play.clickhouse.com/play?user=play#c2VsZWN0IHB1bGxfcmVxdWVzdF9udW1iZXIgYXMgcHIsIGNoZWNrX3N0YXJ0X3RpbWUsIGNoZWNrX25hbWUsIHRlc3RfbmFtZSwgdGVzdF9zdGF0dXMgYXMgc3RhdHVzLCByZXBvcnRfdXJsCmZyb20gY2hlY2tzCndoZXJlIHRvRGF0ZShjaGVja19zdGFydF90aW1lKSA+ICcyMDIzLTA4LTE1JyBhbmQgdGVzdF9uYW1lIGxpa2UgJyUwMTA5OV9vcGVyYXRvcnNfZGF0ZV9hbmRfdGltZXN0YW1wJScgYW5kIHN0YXR1cyA9PSAnRkFJTCcKb3JkZXIgYnkgY2hlY2tfc3RhcnRfdGltZSBkZXNj) are useful to check if a test fails also elsewhere.

**Comment by mkmkme** [comment]
Oh, neat! Thanks!

**Pull request merged**
