### PR TITLE
JSON output for EXPLAIN

### PR DESCRIPTION
**Pull request by KochetovNicolai**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- New Feature

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Add setting `json` (boolean, 0 by default) for `EXPLAIN PLAN` query. When enabled, query output will be a single `JSON` row. It is recommended to use `TSVRaw` format to avoid unnecessary escaping.

The result JSON is a tree representing query plan. Every query plan node is a dictionary which always has keys `Node Type` and `Plans`. `Node Type` is a string with step name. `Plans` is an array with child step descriptions.  Other optional keys may be added depending on node type and settings.

Example:
```sql
EXPLAIN json = 1, description = 0
SELECT 1
UNION ALL
SELECT 2
FORMAT TSVRaw

Query id: fd9b3666-ffc2-4aec-a308-4ec1295811cc

[
  {
    "Plan": {
      "Node Type": "Union",
      "Plans": [
        {
          "Node Type": "Expression",
          "Plans": [
            {
              "Node Type": "SettingQuotaAndLimits",
              "Plans": [
                {
                  "Node Type": "ReadFromStorage"
                }
              ]
            }
          ]
        },
        {
          "Node Type": "Expression",
          "Plans": [
            {
              "Node Type": "SettingQuotaAndLimits",
              "Plans": [
                {
                  "Node Type": "ReadFromStorage"
                }
              ]
            }
          ]
        }
      ]
    }
  }
]
```

With `description = 1`, `Description` key is added to step:
```json
{
  "Node Type": "ReadFromStorage",
  "Description": "SystemOne"
}
```

With `header = 1`, `Header` key is added to step as an array of columns:
```sql
explain json = 1, description = 0, header = 1 select 1, 2 + dummy


"Plan": {
  "Node Type": "Expression",
  "Header": [
    {
      "Name": "1",
      "Type": "UInt8"
    },
    {
      "Name": "plus(2, dummy)",
      "Type": "UInt16"
    }
  ]
```

With `indexes = 1`, `Indexes` key is added. It contains an array of used indexes. Each index is described as JSON with key `Type` (a string `MinMax`, `Partition`, `PrimaryKey` or `Skip`), and optional keys:
* `Name` is an index name (for now, is used only for `Skip` index)
* `Keys` is an array of columns used by index
* `Condition` is a string with condition used
* `Description` is an index (for now, is used only for `Skip` index)
* `Initial Parts` is a number of parts before index is applied
* `Selected Parts` is a number of parts after index is applied
* `Initial Granules`  is a number of granules before index is applied
* `Selected Granules`is a number of granules after index is applied

Example:
```
"Node Type": "ReadFromMergeTree",
"Indexes": [
  {
    "Type": "MinMax",
    "Keys": ["y"],
    "Condition": "(y in [1, +inf))",
    "Initial Parts": 5,
    "Selected Parts": 4,
    "Initial Granules": 12,
    "Selected Granules": 11
  },
  {
    "Type": "Partition",
    "Keys": ["y", "bitAnd(z, 3)"],
    "Condition": "and((bitAnd(z, 3) not in [1, 1]), and((y in [1, +inf)), (bitAnd(z, 3) not in [1, 1])))",
    "Initial Parts": 4,
    "Selected Parts": 3,
    "Initial Granules": 11,
    "Selected Granules": 10
  },
  {
    "Type": "PrimaryKey",
    "Keys": ["x", "y"],
    "Condition": "and((x in [11, +inf)), (y in [1, +inf)))",
    "Initial Parts": 3,
    "Selected Parts": 2,
    "Initial Granules": 10,
    "Selected Granules": 6
  },
  {
    "Type": "Skip",
    "Name": "t_minmax",
    "Description": "minmax GRANULARITY 2",
    "Initial Parts": 2,
    "Selected Parts": 1,
    "Initial Granules": 6,
    "Selected Granules": 2
  },
  {
    "Type": "Skip",
    "Name": "t_set",
    "Description": "set GRANULARITY 2",
    "Initial Parts": 1,
    "Selected Parts": 1,
    "Initial Granules": 2,
    "Selected Granules": 1
  }
]
```

With `actions = 1`, added keys depend on step type.

```sql
EXPLAIN json = 1, actions = 1, header = 1, description = 0
SELECT quantile(0.2)(number), sumIf(number, number > 0) from numbers(2) group by number, number + 1 FORMAT TSVRaw


"Node Type": "Aggregating",
"Keys": ["number", "plus(number, 1)"],
"Aggregates": [
  {
    "Name": "quantile(0.2)(number)",
    "Function": {
      "Name": "quantile",
      "Parameters": ["0.2"],
      "Argument Types": ["UInt64"],
      "Result Type": "Float64"
    },
    "Arguments": ["number"],
    "Argument Positions": [0]
  },
  {
    "Name": "sumIf(number, greater(number, 0))",
    "Function": {
      "Name": "sumIf",
      "Argument Types": ["UInt64", "UInt8"],
      "Result Type": "UInt64"
    },
    "Arguments": ["number", "greater(number, 0)"],
    "Argument Positions": [0, 2]
  }
]
```

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
Submodule is unneeded.

**Comment by alexey-milovidov** [comment]
> Support FORMAT JSON for EXPLAIN PLAN query. Now, EXPLAIN with specified format other than JSON will throw exception (for old clients FORMAT is ignored). Omit FORMAT to get human-readable output.

But this logic is unorthogonal.

**Comment by KochetovNicolai** [comment]
> But this logic is unorthogonal.

I though that it is better to remove `json = 1` setting and use `FORMAT JSON` instead of.
As we discussed, it does not seem so useful to get json in json or json in xml.

**Comment by KochetovNicolai** [comment]
@Mergify update

**Comment by akuzm** [comment]
I thought you'd use Fields, they (almost) can be serialized to JSON and now we have Map type. Not that I'm against having a separate JSON representation, at least it doesn't have any dependencies.

Do I get it right that we have to write all the explain functions twice now, for WriteBuffer and for JSON? Maybe we can implement the former in terms of the latter?

**Comment by KochetovNicolai** [comment]
> I thought you'd use Fields, they (almost) can be serialized to JSON

Yes, almost. But I don't like the idea to make Field JSON serializable. Filed is already very complicated. Also, it is not very convenient to create huge field which represents JSON (also, can it support map?).

> Do I get it right that we have to write all the explain functions twice now, for WriteBuffer and for JSON? Maybe we can implement the former in terms of the latter?

I had the same idea. However, it is not clear how to get good human-readable EXPLAIN from JSON.
How can we get
```
        PrimaryKey
          Keys: 
            x
            y
          Condition: and((x in [11, +inf)), (y in [1, +inf)))
          Parts: 2/3
          Granules: 6/10
```
from
```json
{
       "Type": "PrimaryKey",
       "Keys": ["x", "y"],
       "Condition": "and((x in [11, +inf)), (y in [1, +inf)))",
       "Initial Parts": 3,
       "Selected Parts": 2,
       "Initial Granules": 10,
       "Selected Granules": 6
}
```
?

**Comment by sevirov** [comment]
Internal documentation ticket: DOCSUP-9041.

**Pull request merged**
