### PR TITLE
[WIP] Bump jemalloc to 5.2.1

### PR DESCRIPTION
**Pull request by azat**
Changelog category (leave one):
- Not for changelog (changelog entry is not required)

This is an experiment with newer jemalloc, I saw the issues that it introduces (#9558), but I have some ideas about the culprit (marked few patches for myself), but first I want to check plain 5.2.1

#### contrib notes

- `contrib/jemalloc-cmake/include_linux_x86_64/jemalloc/*.h` has been moved to `contrib/jemalloc-cmake/include/jemalloc/` (since there is 0 arch specific code, and besides they were out of sync between two arches) -- this patch goes first and can be picked regardless this PR

#### upstream vs contrib

- `_GNU_SOURCE` - moved from the headers into cmake `target_compile_options(jemalloc PRIVATE -D_GNU_SOURCE)`
- `JEMALLOC_OVERRIDE___POSIX_MEMALIGN` has been disabled
- `JEMALLOC_PURGE_MADVISE_FREE` has bee enabled (like in upstream)
- `JEMALLOC_HAVE_SECURE_GETENV` has been disabled
- `oversize_threshold` has been disabled

Changelog

<details>

```
* 5.2.1 (August 5, 2019)

  This release is primarily about Windows.  A critical virtual memory leak is
  resolved on all Windows platforms.  The regression was present in all releases
  since 5.0.0.

  Bug fixes:
  - Fix a severe virtual memory leak on Windows.  This regression was first
    released in 5.0.0.  (@Ignition, @j0t, @frederik-h, @davidtgoldblatt,
    @interwq)
  - Fix size 0 handling in posix_memalign().  This regression was first released
    in 5.2.0.  (@interwq)
  - Fix the prof_log unit test which may observe unexpected backtraces from
    compiler optimizations.  The test was first added in 5.2.0.  (@marxin,
    @gnzlbg, @interwq)
  - Fix the declaration of the extent_avail tree.  This regression was first
    released in 5.1.0.  (@zoulasc)
  - Fix an incorrect reference in jeprof.  This functionality was first released
    in 3.0.0.  (@prehistoric-penguin)
  - Fix an assertion on the deallocation fast-path.  This regression was first
    released in 5.2.0.  (@yinan1048576)
  - Fix the TLS_MODEL attribute in headers.  This regression was first released
    in 5.0.0.  (@zoulasc, @interwq)

  Optimizations and refactors:
  - Implement opt.retain on Windows and enable by default on 64-bit.  (@interwq,
    @davidtgoldblatt)
  - Optimize away a branch on the operator delete[] path.  (@mgrice)
  - Add format annotation to the format generator function.  (@zoulasc)
  - Refactor and improve the size class header generation.  (@yinan1048576)
  - Remove best fit.  (@djwatson)
  - Avoid blocking on background thread locks for stats.  (@oranagra, @interwq)

* 5.2.0 (April 2, 2019)

  This release includes a few notable improvements, which are summarized below:
  1) improved fast-path performance from the optimizations by @djwatson; 2)
  reduced virtual memory fragmentation and metadata usage; and 3) bug fixes on
  setting the number of background threads.  In addition, peak / spike memory
  usage is improved with certain allocation patterns.  As usual, the release and
  prior dev versions have gone through large-scale production testing.

  New features:
  - Implement oversize_threshold, which uses a dedicated arena for allocations
    crossing the specified threshold to reduce fragmentation.  (@interwq)
  - Add extents usage information to stats.  (@tyleretzel)
  - Log time information for sampled allocations.  (@tyleretzel)
  - Support 0 size in sdallocx.  (@djwatson)
  - Output rate for certain counters in malloc_stats.  (@zinoale)
  - Add configure option --enable-readlinkat, which allows the use of readlinkat
    over readlink.  (@davidtgoldblatt)
  - Add configure options --{enable,disable}-{static,shared} to allow not
    building unwanted libraries.  (@Ericson2314)
  - Add configure option --disable-libdl to enable fully static builds.
    (@interwq)
  - Add mallctl interfaces:
        + opt.oversize_threshold (@interwq)
        + stats.arenas.<i>.extent_avail (@tyleretzel)
        + stats.arenas.<i>.extents.<j>.n{dirty,muzzy,retained} (@tyleretzel)
        + stats.arenas.<i>.extents.<j>.{dirty,muzzy,retained}_bytes
          (@tyleretzel)

  Portability improvements:
  - Update MSVC builds.  (@maksqwe, @rustyx)
  - Workaround a compiler optimizer bug on s390x.  (@rkmisra)
  - Make use of pthread_set_name_np(3) on FreeBSD.  (@trasz)
  - Implement malloc_getcpu() to enable percpu_arena for windows.  (@santagada)
  - Link against -pthread instead of -lpthread.  (@paravoid)
  - Make background_thread not dependent on libdl.  (@interwq)
  - Add stringify to fix a linker directive issue on MSVC.  (@daverigby)
  - Detect and fall back when 8-bit atomics are unavailable.  (@interwq)
  - Fall back to the default pthread_create if dlsym(3) fails.  (@interwq)

  Optimizations and refactors:
  - Refactor the TSD module.  (@davidtgoldblatt)
  - Avoid taking extents_muzzy mutex when muzzy is disabled.  (@interwq)
  - Avoid taking large_mtx for auto arenas on the tcache flush path.  (@interwq)
  - Optimize ixalloc by avoiding a size lookup.  (@interwq)
  - Implement opt.oversize_threshold which uses a dedicated arena for requests
    crossing the threshold, also eagerly purges the oversize extents.  Default
    the threshold to 8 MiB.  (@interwq)
  - Clean compilation with -Wextra.  (@gnzlbg, @jasone)
  - Refactor the size class module.  (@davidtgoldblatt)
  - Refactor the stats emitter.  (@tyleretzel)
  - Optimize pow2_ceil.  (@rkmisra)
  - Avoid runtime detection of lazy purging on FreeBSD.  (@trasz)
  - Optimize mmap(2) alignment handling on FreeBSD.  (@trasz)
  - Improve error handling for THP state initialization.  (@jsteemann)
  - Rework the malloc() fast path.  (@djwatson)
  - Rework the free() fast path.  (@djwatson)
  - Refactor and optimize the tcache fill / flush paths.  (@djwatson)
  - Optimize sync / lwsync on PowerPC.  (@chmeeedalf)
  - Bypass extent_dalloc() when retain is enabled.  (@interwq)
  - Optimize the locking on large deallocation.  (@interwq)
  - Reduce the number of pages committed from sanity checking in debug build.
    (@trasz, @interwq)
  - Deprecate OSSpinLock.  (@interwq)
  - Lower the default number of background threads to 4 (when the feature
    is enabled).  (@interwq)
  - Optimize the trylock spin wait.  (@djwatson)
  - Use arena index for arena-matching checks.  (@interwq)
  - Avoid forced decay on thread termination when using background threads.
    (@interwq)
  - Disable muzzy decay by default.  (@djwatson, @interwq)
  - Only initialize libgcc unwinder when profiling is enabled.  (@paravoid,
    @interwq)


  Bug fixes (all only relevant to jemalloc 5.x):
  - Fix background thread index issues with max_background_threads.  (@djwatson,
    @interwq)
  - Fix stats output for opt.lg_extent_max_active_fit.  (@interwq)
  - Fix opt.prof_prefix initialization.  (@davidtgoldblatt)
  - Properly trigger decay on tcache destroy.  (@interwq, @amosbird)
  - Fix tcache.flush.  (@interwq)
  - Detect whether explicit extent zero out is necessary with huge pages or
    custom extent hooks, which may change the purge semantics.  (@interwq)
  - Fix a side effect caused by extent_max_active_fit combined with decay-based
    purging, where freed extents can accumulate and not be reused for an
    extended period of time.  (@interwq, @mpghf)
  - Fix a missing unlock on extent register error handling.  (@zoulasc)

  Testing:
  - Simplify the Travis script output.  (@gnzlbg)
  - Update the test scripts for FreeBSD.  (@devnexen)
  - Add unit tests for the producer-consumer pattern.  (@interwq)
  - Add Cirrus-CI config for FreeBSD builds.  (@jasone)
  - Add size-matching sanity checks on tcache flush.  (@davidtgoldblatt,
    @interwq)

  Incompatible changes:
  - Remove --with-lg-page-sizes.  (@davidtgoldblatt)

  Documentation:
  - Attempt to build docs by default, however skip doc building when xsltproc
    is missing. (@interwq, @cmuellner)

* 5.1.0 (May 4, 2018)
```

</details>

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
> JEMALLOC_PURGE_MADVISE_FREE

Does it perform a test in runtime that this feature is available in kernel?

**Comment by azat** [comment]
>Does it perform a test at runtime that this feature is available in kernel?

No (will take this into account, thanks)

**Comment by azat** [comment]
>Does it perform a test at runtime that this feature is available in kernel?

Actually it does

https://github.com/jemalloc/jemalloc/blob/6cdac3c573de86c8d59d69fca8f1778bdbec25e0/src/pages.c#L661-L662

>Performance — 2 faster, 205 slower, 137 unstable, 3 errors

This, is how performance tests looks after upgrading to 5.2.1

>Performance — 1 faster, 159 unstable, 7 errors

This, is how it looks now (basically after disabling `oversize_threshold`/`huge_threshold`)

@alexey-milovidov @akuzm I guess hits looks more or less ok? (I saw similar reports in some PRs, i.e. lots of unstable tests)
Then I'm going to cleanup this PR to for merging (there are some bits that can be analyzed, that can be related to #11121 , but I would prefer to do this separately).

Also about `POPCNT`, this cannot be checked like other instructions, since `malloc` will be called ealier, qemu does provides `POPCNT` but only in conjuction with `ssse3,sse4.1,sse4.2`, i.e.:

```shell
$ qemu-x86_64-static -cpu qemu64,+popcnt,+ssse3,+sse4.1,+sse4.2 $(which clickhouse-client) --query "SELECT 1" 2>&1 
1
$ qemu-x86_64-static -cpu qemu64,+popcnt,+ssse3,+sse4.1 $(which clickhouse-client) --query "SELECT 1" 2>&1 
qemu: uncaught target signal 6 (Aborted) - core dumped
Aborted (core dumped)
```

So this change makes that instruction check code pretty useless, is it useful?
That said that, I think that it can be written in that way, that it will be called before malloc, but it will be way more complex, does it worth it?

**Comment by azat** [comment]
Previous HEAD's:
- 461fea813705038d930ad779b019497795fc4915 - stock 5.2.1
- b8b58dd62c7ebf53465907ebb2975ea6edf9754e and 4e3a43db93d71398f4087a645a0aa515a29deea1 - few patches reverted, slower
- 3adda87acfeb9202b41dc56fae07ec8568fc0fcc - mostly the same as latest
- dee04567b8f91fca08a483565e3255cc80a9e6b7 -- latest

(will rebase with push --force)

**Comment by alexey-milovidov** [comment]
> So this change makes that instruction check code pretty useless, is it useful?

Yes, it is very useful because it provides good diagnostics for user. How it is possible to call it before malloc? Maybe it's worth it.

**Comment by azat** [comment]
>Yes, it is very useful because it provides good diagnostics for user. How it is possible to call it before malloc? Maybe it's worth it.

I though about changing [entry point](http://www.scoberlin.de/content/media/http/informatik/gcc_docs/ld_3.html#SEC10), but it will work only on linux (at least what I wanted to do).

But...

>qemu does provides POPCNT but only in conjuction with ssse3,sse4.1,sse4.2, i.e.:

Actually I guess that with bundled build instructions check will be executed before, but even if it so now, it may be changed one day...

**Comment by alexey-milovidov** [comment]
I see that it works perfectly, so we can leave this test.

**Review by alexey-milovidov — APPROVED** [review]
Let's fix style check and merge.

**Comment by azat** [comment]
>Let's fix style check and merge.

Not sure that I know what is the error (and every time I would mistaken the CI will be triggered, sigh), I guess some missing whitespace, but style check is not verbose

**Comment by alexey-milovidov** [comment]
You can edit `check-style` script if you like.

**Comment by azat** [comment]
>You can edit check-style script if you like.

Thanks! Didn't know that this was in repo (and never searched for it).
The style check issue had been found and fixed.

**Pull request merged**
