### PR TITLE
add table system.database_engines

### PR DESCRIPTION
**Pull request by bharatnc**
### Changelog category (leave one):
- New Feature

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Add table `system.database_engines`.

### Documentation entry for user-facing changes

- [x] Documentation is written (mandatory for new features)

Add `system.database_engines` that lists all the available database engines. Follow up for #58365 and related to #56557.
cc: @alexey-milovidov 

**Note:** These database engines currently don't expose any features specifically (like the table engines do). So, I'm starting with the name column alone. We can add additional columns to enrich the table as needed.
```
:) SELECT *
FROM system.database_engines
WHERE name in ('Atomic', 'Lazy', 'Ordinary');

SELECT *
FROM system.database_engines
WHERE name IN ('Atomic', 'Lazy', 'Ordinary')

Query id: 116fba9f-c036-4cd1-9474-158faf6689ed

┌─name─────┐
│ Ordinary │
│ Atomic   │
│ Lazy     │
└──────────┘
```

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by robot-ch-test-poll3** [comment]
*This is an automated comment for commit 00b5e28d6ae169b4712d046e0244649bc88092e5 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/58390/00b5e28d6ae169b4712d046e0244649bc88092e5/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/58390/00b5e28d6ae169b4712d046e0244649bc88092e5/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Review by alexey-milovidov — APPROVED** [review]
Amazing, thank you!

**Comment by alexey-milovidov** [comment]
Probably the only remaining factory is `InterpreterFactory`. Maybe also system tables.
If we make them in a similar way to other factories, there will be also a chance for embedded documentation.

**Comment by bharatnc** [comment]
> Probably the only remaining factory is `InterpreterFactory`. Maybe also system tables. If we make them in a similar way to other factories, there will be also a chance for embedded documentation.

@alexey-milovidov sure that sounds good. I will follow up with PRs for those next.

**Pull request merged**
