### PR TITLE
Fix  `parallel_view_processing=0` and `view_duration_ms` in views log

### LINKED ISSUE #33961: parallel_view_processing=0 is does not work with INSERT INTO table VALUES
Comes from https://github.com/ClickHouse/ClickHouse/pull/33951#discussion_r791027950

```
CREATE TABLE a (a Int64) ENGINE=Memory;
CREATE TABLE b (a Int64) ENGINE=Memory;
CREATE MATERIALIZED VIEW mv1 TO b AS Select sleep(1) as a FROM a;
CREATE MATERIALIZED VIEW mv2 TO b AS Select sleep(1) as a FROM a;
CREATE MATERIALIZED VIEW mv3 TO b AS Select sleep(1) as a FROM a;
CREATE MATERIALIZED VIEW mv4 TO b AS Select sleep(1) as a FROM a;
CREATE MATERIALIZED VIEW mv5 TO b AS Select sleep(1) as a FROM a;
CREATE MATERIALIZED VIEW mv6 TO b AS Select sleep(1) as a FROM a;
CREATE MATERIALIZED VIEW mv7 TO b AS Select sleep(1) as a FROM a;
CREATE MATERIALIZED VIEW mv8 TO b AS Select sleep(1) as a FROM a;
CREATE MATERIALIZED VIEW mv9 TO b AS Select sleep(1) as a FROM a;
CREATE MATERIALIZED VIEW mv10 TO b AS Select sleep(1) as a FROM a;
```

```
INSERT INTO a SELECT * FROM system.one;
```
Takes 10 seconds as expected.

```
INSERT INTO a VALUES(1);
```
Takes 1 second, which is unexpected and means that the MVs are being executed in parallel even though `parallel_view_processing == 0`.

Fails for 21.11+

### LINKED ISSUE #34061: query_views_log view_duration_ms is always 0
```sql
CREATE TABLE IF NOT EXISTS a (a Int64) ENGINE=Memory;
CREATE TABLE IF NOT EXISTS b (a Int64) ENGINE=Memory;
CREATE MATERIALIZED VIEW IF NOT EXISTS mv1 TO b AS Select sleepEachRow(0.1) as a FROM a;
CREATE MATERIALIZED VIEW IF NOT EXISTS mv2 TO b AS Select sleepEachRow(0.1) as a FROM a;
CREATE MATERIALIZED VIEW IF NOT EXISTS mv3 TO b AS Select sleepEachRow(0.1) as a FROM a;
CREATE MATERIALIZED VIEW IF NOT EXISTS mv4 TO b AS Select sleepEachRow(0.1) as a FROM a;
CREATE MATERIALIZED VIEW IF NOT EXISTS mv5 TO b AS Select sleepEachRow(0.1) as a FROM a;

-- INSERT USING VALUES
INSERT INTO a VALUES(1);
SYSTEM FLUSH LOGS;

SELECT query_duration_ms >= 500
FROM system.query_log
WHERE
      current_database = currentDatabase()
  AND event_date >= yesterday()
  AND query LIKE '-- INSERT USING VALUES%'
  AND type = 'QueryFinish'
LIMIT 1;

WITH
(
    SELECT initial_query_id
    FROM system.query_log
    WHERE
            current_database = currentDatabase()
      AND event_date >= yesterday()
      AND query LIKE '-- INSERT USING VALUES%'
    LIMIT 1
) AS q_id
SELECT view_duration_ms >= 100
FROM system.query_views_log
WHERE initial_query_id = q_id;
```

This should return all 1's for the views since they are taking at the very least 100 ms to execute. Nevertheless, for 21.11+ all view_duration_ms are 0.

* 21.9.4.35: OK
* 21.10.4.26: OK
* 21.11.5.33: KO
* 21.12.2.17: KO
* 22.1.3.7: KO

### PR DESCRIPTION
**Pull request by Algunenano**
Changelog category (leave one):
- Bug Fix (user-visible misbehaviour in official stable or prestable release)

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
- Fixes `parallel_view_processing=0` not working when inserting into a table using `VALUES`.
- Fixes `view_duration_ms` in the `query_views_log` not being set correctly for materialized views.

> Information about CI checks: https://clickhouse.tech/docs/en/development/continuous-integration/

I'm not 100% sure about the first fix. It works and it makes sense but I feel I'm missing something since now there are 2 places where the limits are set (here and in InterpreterInsertQuery::execute() in some cases).

Both issues come from the large refactor done in 21.11, so they only affect 21.11+
cc @KochetovNicolai 
Closes https://github.com/ClickHouse/ClickHouse/issues/34061
Closes https://github.com/ClickHouse/ClickHouse/issues/33961

### CODE REVIEW

**Comment by novikd** [comment]
@Mergifyio update

**Review by novikd — APPROVED** [review]

**Comment by novikd** [comment]
> ClickHouse special build check (actions) — 6/7 builds are OK

Broken in master

> Stateless tests (debug, actions) [1/3] — fail: 1, passed: 1257, skipped: 9

Broken in master

**Comment by alexey-milovidov** [comment]
https://github.com/Mergifyio update

**Comment by alexey-milovidov** [comment]
@Mergifyio update

**Comment by Algunenano** [comment]
The 2 broken test seems unrelated:
* Integration tests (release, actions) [2/2] -> test_postgresql_replica_database_engine_1/test.py::test_abrupt_connection_loss_while_heavy_replication
* Style Check complains about .github/workflows/tags_stable.yml

Does this need anything else to get merged? I can break it into 2 PRs if you want to.

**Comment by alexey-milovidov** [comment]
Yes, it was approved by @novikd 11 days ago but looks like he forget to merge.

**Pull request merged**
