### PR TITLE
Fix 01161_all_system_tables

### PR DESCRIPTION
**Pull request by antonio2368**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Based on the [logs](https://s3.amazonaws.com/clickhouse-test-reports/36439/04e3356d509ea3e562e3455f1ca7f0c4cbf652e5/stateless_tests__release__databasereplicated__actions__[2/2].html) the mistake seems to be related to parallel execution of the test.

The strange part was that it already had `no-parallel` tag but based on the `clickhouse-test` code it needs to be either first line or instantly after shebang.

cc @kssenii (you added the tag so you're probably aware how test works in detail)

> Information about CI checks: https://clickhouse.tech/docs/en/development/continuous-integration/

### CODE REVIEW

**Review by kssenii — APPROVED** [review]
thanks! I did not know that.

Though I think it will make this test much less flaky, but still it can fail very rarely (as there still remains one case when it can fail even with no-parallel but very rarely), I am trying to fix it in another PR now.

**Review by tavplubix — CHANGES_REQUESTED** [review]
Is there any reason why not to run this test in parallel? It's typical stress-test with empty reference file, it's trying to reproduce some race condition/segfault/etc. I'd prefer to revert #36175, find actual reason of test flakiness and fix it.

**Comment by kssenii** [comment]
> Is there any reason why not to run this test in parallel? It's typical stress-test with empty reference file, it's trying to reproduce some race condition/segfault/etc. I'd prefer to revert https://github.com/ClickHouse/ClickHouse/pull/36175, find actual reason of test flakiness and fix it.

I will anyway fix the actual reason of test flakiness, it is known. Was going to make a separate test just for this case when it should fail stably.

**Comment by antonio2368** [comment]
In the logs above what happened was that calling `SELECT * FROM system.clusters` while they are created in parallel is unreliable causing some Errors to be logged.

**Comment by tavplubix** [comment]
> In the logs above what happened was that calling `SELECT * FROM system.clusters` while they are created in parallel is unreliable causing some Errors to be logged.

Yep, I see, the query has actually succeed, it just logged some (expected) error:
```
zgrep -Fa "66639b6b-3d47-4ded-95d3-1ff34bda1ce6" clickhouse-server.log.gz
2022.04.21 19:09:38.843187 [ 98372 ] {66639b6b-3d47-4ded-95d3-1ff34bda1ce6} <Debug> executeQuery: (from [::1]:36662) (comment: 01161_all_system_tables.sh) SELECT * FROM system.clusters LIMIT 10000 FORMAT Null
2022.04.21 19:09:38.843593 [ 98372 ] {66639b6b-3d47-4ded-95d3-1ff34bda1ce6} <Trace> ContextAccess (default): Access granted: SELECT(cluster, shard_num, shard_weight, replica_num, host_name, host_address, port, is_local, user, default_database, errors_count, slowdowns_count, estimated_recovery_time) ON system.clusters
2022.04.21 19:09:38.844650 [ 98372 ] {66639b6b-3d47-4ded-95d3-1ff34bda1ce6} <Error> virtual void DB::StorageSystemClusters::fillData(DB::MutableColumns &, DB::ContextPtr, const DB::SelectQueryInfo &) const: Code: 254. DB::Exception: No replicas of database test_588xfi found. It's possible if the first replica is not fully created yet or if the last replica was just dropped or due to logical error. (NO_ACTIVE_REPLICAS), Stack trace (when copying this message, always include the lines below):
2022.04.21 19:09:38.844793 [ 98372 ] {66639b6b-3d47-4ded-95d3-1ff34bda1ce6} <Trace> InterpreterSelectQuery: FetchColumns -> Complete
2022.04.21 19:09:38.846001 [ 98372 ] {66639b6b-3d47-4ded-95d3-1ff34bda1ce6} <Information> executeQuery: Read 30 rows, 3.75 KiB in 0.002767625 sec., 10839 rows/sec., 1.32 MiB/sec.
2022.04.21 19:09:38.846103 [ 98372 ] {66639b6b-3d47-4ded-95d3-1ff34bda1ce6} <Debug> MemoryTracker: Peak memory usage (for query): 2.03 MiB.
```

**Comment by tavplubix** [comment]
Fast test (actions) - `Table system.dict1 doesn't exist` - lol, it's because `01129_dict_get_join_lose_constness.sql` creates a dictionary in `system` database. But usually tests should not do so.

**Comment by antonio2368** [comment]
> Fast test (actions) - Table system.dict1 doesn't exist - lol, it's because 01129_dict_get_join_lose_constness.sql creates a dictionary in system database. But usually tests should not do so.

Doesn't this prove how easy it is to make this test unstable again?
I get that it's a stress test but based on the tables it's querying maybe it's better to write in a more controlled env (no parallel or integration test).

**Comment by tavplubix** [comment]
> > Fast test (actions) - Table system.dict1 doesn't exist - lol, it's because 01129_dict_get_join_lose_constness.sql creates a dictionary in system database. But usually tests should not do so.
> 
> Doesn't this prove how easy it is to make this test unstable again? I get that it's a stress test but based on the tables it's querying maybe it's better to write in a more controlled env (no parallel or integration test).

Functional tests should not create any tables in `system` database and I don't know why `01129_dict_get_join_lose_constness` does, maybe its author was too lazy to create a database for dictionary or they was trying to avoid a kind of "Server failed to start" error in Stress test (not relevant anymore). Anyway it means that `01129_dict_get_join_lose_constness` is "bad" test and `01161_all_system_tables` with parallel run found that "bad" test. But it makes sense to leave at least one test that creates something in `system` database.

Also I realized that the correct way to fix `Table system.dict1 doesn't exist` is to add `no-parallel` tag to `01129_dict_get_join_lose_constness`, because a test should be marked as `no-parallel` if it changes some global state or uses not unique names. I will update it.

**Comment by tavplubix** [comment]
Stress tests - Backward compatibility check - segfault in `JoinToSubqueryTransformMatcher::visit` - broken in master, already fixed

**Review by tavplubix — APPROVED** [review]

**Pull request merged**
