### PR TITLE
Enable memory tracking for insert queries

### PR DESCRIPTION
**Pull request by abyss7**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Enable memory tracking for insert queries

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
> Enable memory tracking for insert queries

But memory tracking always worked for INSERT queries. At least changelog entry is incorrect.

**Comment by alexey-milovidov** [comment]
I understand that it is something about query profiler.

But the root cause that query profiler doesn't work is different and it is still the case in HTTPHandler.

**Comment by alexey-milovidov** [comment]
> Thread name cannot be longer than 15 bytes

https://clickhouse-test-reports.s3.yandex.net/8804/631c1b55c6d2b87bd26cfc6b805d8af238a0cf2e/functional_stateless_tests_(debug)/clickhouse-server.log

**Comment by abyss7** [comment]
@KochetovNicolai already told me that my approach is wrong - will reimplement this.

**Pull request closed without merging**
