### PR TITLE
Fixed IPv4CIDRToRange/IPv6CIDRToRange functions to accept const IP-column values

### PR DESCRIPTION
**Pull request by vladimir-golovchenko**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category:
- Bug Fix

Changelog entry:
* Fixed IPv4CIDRToRange/IPv6CIDRToRange functions to accept const IP-column values
* Added tests to cover cases with Const first column.

### CODE REVIEW

**Comment by vladimir-golovchenko** [comment]
Related issue: https://github.com/ClickHouse/ClickHouse/issues/11245.

**Comment by vladimir-golovchenko** [comment]
@nikitamikhaylov @nikitamikhaylov could you check this PR?

**Comment by nikitamikhaylov** [comment]
> @nikitamikhaylov could you check this PR?

Of course, but I am a little bit busy this week.

**Comment by nikitamikhaylov** [comment]
Merged in neighboring PR.

**Comment by VitalyVPinchuk** [comment]
Hello @vladimir-golovchenko 
Could you send me a message via email, please?

**Pull request closed without merging**
