### PR TITLE
Add auto-vectorization for BinaryOperation

### PR DESCRIPTION
**Pull request by jiebinn**
### Changelog category (leave one):
- Performance Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Enable auto-vectorization for binary operations such as `+` and `*`. On a 2 x 80 vCPUs system with ClickBench, Q29 becomes 5% faster, and the total runtime of 43 queries improved by 1.6%.

### CODE REVIEW

**Comment by robot-ch-test-poll3** [comment]
*This is an automated comment for commit c57ccf3d0564cf9be44a56b42d6ff8bf34b6a620 with description of existing statuses. It's updated for the latest CI running*

[❌ Click here](https://s3.amazonaws.com/clickhouse-test-reports/57343/c57ccf3d0564cf9be44a56b42d6ff8bf34b6a620/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td><a href="https://github.com/ClickHouse/ClickHouse/actions/runs/7029391647">✅ success</a></td></tr>
<tbody>
</table>
</details>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/57343/c57ccf3d0564cf9be44a56b42d6ff8bf34b6a620/ci_running.html">❌ failure</a></td></tr>
<tbody>
</table>

**Comment by rschu1ze** [comment]
> Enable auto-vectorization for binary operations such as + and *. On a 2 x 80 vCPUs system with ClickBench, Q29 becomes 5% faster, and the total runtime of 43 queries improved by 1.6%.

Just out of curiosity, do you know which specific SIMD instructions (e.g. up to AVX2) the "2 x 80 vCPU" system in your measurements supported?

**Comment by jiebinn** [comment]
> > Enable auto-vectorization for binary operations such as + and *. On a 2 x 80 vCPUs system with ClickBench, Q29 becomes 5% faster, and the total runtime of 43 queries improved by 1.6%.
> 
> Just out of curiosity, do you know which specific SIMD instructions (e.g. up to AVX2) the "2 x 80 vCPU" system in your measurements supported?

For annotate of the perf hotspot `void DB::impl_::BinaryOperation<short, char8_t, DB::PlusImpl<short, char8_t>, int>::process<(DB::impl_::OpCase)2>(short const*, char8_t const*, int*, unsigned long, DBchar8_t, 4096ul, Allocator<false, false>, 63ul, 64ul> const*)`, ClickHouse will use the default SSE instruction "pmovsxwd" and xmm register. But with the auto-vectorization , it will have AVX512F instruction "vpmovsxwd" and zmm register instead.

**Comment by kitaisreal** [comment]
Duplicate of https://github.com/ClickHouse/ClickHouse/pull/54011. For such small performance improvement probably does not make sense to introduce so many specializations.

**Comment by rschu1ze** [comment]
Good point, thanks.

Results are indeed mixed again:
- https://s3.amazonaws.com/clickhouse-test-reports/57343/c57ccf3d0564cf9be44a56b42d6ff8bf34b6a620/performance_comparison_[1_4]/report.html
- https://s3.amazonaws.com/clickhouse-test-reports/57343/c57ccf3d0564cf9be44a56b42d6ff8bf34b6a620/performance_comparison_[2_4]/report.html
- https://s3.amazonaws.com/clickhouse-test-reports/57343/c57ccf3d0564cf9be44a56b42d6ff8bf34b6a620/performance_comparison_[3_4]/report.html

Some queries become faster, some slower ...

1.6% better runtime for all ClickBench queries is also negligible (almost a rounding error). So yes, I also tend to not merge this PR.

**Pull request closed without merging**
