### PR TITLE
Remove POCO_CLICKHOUSE_PATCH

### PR DESCRIPTION
**Pull request by azat**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Remove POCO_CLICKHOUSE_PATCH

It is not possible to use unbundled poco for a long time ago.

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
https://github.com/ClickHouse/ClickHouse/issues/42691

**Comment by alexey-milovidov** [comment]
https://s3.amazonaws.com/clickhouse-test-reports/43146/953457de281d1167f51d91de9c3ca8df32780b30/stateless_tests__asan__[2/2]/stderr.log

https://github.com/llvm/llvm-project/issues/58633#issuecomment-1295925901

**Comment by alexey-milovidov** [comment]
> Backward compatibility check

What is there?

>  OOM killer (or signal 9)

Why?

>  Failed to parse the report. 

Why?

**Comment by azat** [comment]
>[Performance Comparison Aarch64 [1/4] — Failed to parse the report.](https://s3.amazonaws.com/clickhouse-test-reports/43146/953457de281d1167f51d91de9c3ca8df32780b30/performance_comparison_aarch64_[1/4]/compare.log)

Looks like container got KILLed, and not [retried](https://github.com/ClickHouse/ClickHouse/actions/runs/3440634706/jobs/5745779272)

```
INFO:root:Check is already finished according to github status, exiting
```

>[Stress test (msan) — OOM killer (or signal 9) in clickhouse-server.log](https://s3.amazonaws.com/clickhouse-test-reports/43146/953457de281d1167f51d91de9c3ca8df32780b30/stress_test__msan_.html)

Either it is hang in MSan:

<details>

```
2022.11.11 10:24:00.259550 [ 922 ] {b3cb99b8-5347-4377-9e48-c015e2edc6a3::201403_1_8_1} <Test> CachedObjectStorage-s3_cache(S3ObjectStorage): Caching file `00170_test/kgn/vmfeolmyeilvhiamjhzqeopuefqnz` to `s3_cache/871/871dd175a247ac323b6385cc34ce005e` with key 871dd175a247ac323b6385cc34ce005e
# NOTE: I assume that this delay in messages can be due to gdb attaching
2022.11.11 10:24:12.878048 [ 953 ] {} <Warning> test.visits (b3cb99b8-5347-4377-9e48-c015e2edc6a3): /var/lib/clickhouse/disks/s3_disk/store/b3c/b3cb99b8-5347-4377-9e48-c015e2edc6a3/tmp_merge_201403_1_8_1/ is in use (by merge/mutation/INSERT) (consider increasing temporary_directories_lifetime setting)
2022.11.11 10:24:12.878278 [ 836 ] {} <Test> KeeperTCPHandler: Polling socket for session 2 took 15951 ms
2022.11.11 10:24:12.878375 [ 836 ] {} <Trace> KeeperTCPHandler: Received heartbeat for session #2
2022.11.11 10:24:12.878406 [ 873 ] {} <Test> virtual Coordination::ZooKeeperRequest::~ZooKeeperRequest(): Processing of request xid=-2 took 15952 ms
2022.11.11 10:24:13.356005 [ 825 ] {} <Fatal> Application: Child process was terminated by signal 9 (KILL). If it is not done by 'forcestop' command or manually, the possible cause is OOM Killer (see 'dmesg' and look at the '/var/log/kern.log' for the details).
```

```
2022-11-11 10:24:12 Thread 1 (Thread 0x7fc275038d40 (LWP 826)):
2022-11-11 10:24:12 #0  0x00007fc275317b41 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
2022-11-11 10:24:12 #1  0x000000000be84c7c in __msan::MsanAllocate(__sanitizer::StackTrace*, unsigned long, unsigned long, bool) ()
2022-11-11 10:24:12 #2  0x000000000be84ba6 in __msan::msan_malloc(unsigned long, __sanitizer::StackTrace*) ()
2022-11-11 10:24:12 #3  0x000000000be8e88f in malloc ()
2022-11-11 10:24:12 #4  0x0000000027996d2d in Allocator<false, false>::allocNoTrack (this=<optimized out>, size=1048639, alignment=255) at ../src/Common/Allocator.h:227
2022-11-11 10:24:12 #5  0x0000000027ba018e in Allocator<false, false>::alloc (this=0x710000059848, size=1048639, alignment=<optimized out>) at ../src/Common/Allocator.h:96
2022-11-11 10:24:12 #6  DB::Memory<Allocator<false, false> >::alloc (this=0x710000059848, new_size=1048576) at ../src/IO/BufferWithOwnMemory.h:130
2022-11-11 10:24:12 #7  0x0000000027baa830 in DB::Memory<Allocator<false, false> >::Memory (this=0x710000059848, size_=1048576, alignment_=0) at ../src/IO/BufferWithOwnMemory.h:49
2022-11-11 10:24:12 #8  DB::BufferWithOwnMemory<DB::SeekableReadBuffer>::BufferWithOwnMemory (this=0x710000059800, size=<optimized out>, existing_memory=<optimized out>, alignment=<optimized out>) at ../src/IO/BufferWithOwnMemory.h:157
2022-11-11 10:24:12 #9  DB::ReadBufferFromFileBase::ReadBufferFromFileBase (this=0x710000059800, buf_size=1048576, existing_memory=0x0, alignment=0, file_size_=...) at ../src/IO/ReadBufferFromFileBase.cpp:20
2022-11-11 10:24:12 #10 0x000000003e8c37ed in DB::ReadBufferFromFileDescriptor::ReadBufferFromFileDescriptor (fd_=-1, buf_size=1048576, existing_memory=0x0, alignment=0, file_size_=..., this=<optimized out>) at ../src/IO/ReadBufferFromFileDescriptor.h:37
2022-11-11 10:24:12 #11 DB::ReadBufferFromFileDescriptorPRead::ReadBufferFromFileDescriptorPRead (fd_=-1, buf_size=1048576, existing_memory=0x0, alignment=0, file_size_=..., this=<optimized out>) at ../src/IO/ReadBufferFromFileDescriptor.h:84
2022-11-11 10:24:12 #12 DB::ReadBufferFromFilePReadWithDescriptorsCache::ReadBufferFromFilePReadWithDescriptorsCache (this=<optimized out>, this@entry=0x710000059800, file_name_=..., buf_size=buf_size@entry=1048576, flags=flags@entry=524288, existing_memory=existing_memory@entry=0x0, alignment=0, file_size_=...) at ../src/IO/ReadBufferFromFile.h:92
2022-11-11 10:24:12 #13 0x000000003e8c1fca in std::__1::make_unique[abi:v15003]<DB::ReadBufferFromFilePReadWithDescriptorsCache, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long&, int&, char*&, unsigned long&, std::__1::optional<unsigned long>&>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long&, int&, char*&, unsigned long&, std::__1::optional<unsigned long>&) (__args=<optimized out>, __args=<optimized out>, __args=<optimized out>, __args=<optimized out>, __args=<optimized out>, __args=<optimized out>) at ../contrib/libcxx/include/__memory/unique_ptr.h:714
2022-11-11 10:24:12 #14 DB::createReadBufferFromFileBase(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::ReadSettings const&, std::__1::optional<unsigned long>, std::__1::optional<unsigned long>, int, char*, unsigned long)::$_0::operator()(unsigned long, int) const (this=this@entry=0x7ffd3389cb70, buffer_size=1048576, actual_flags=actual_flags@entry=524288) at ../src/Disks/IO/createReadBufferFromFileBase.cpp:76
2022-11-11 10:24:12 #15 0x000000003e8c1427 in DB::createReadBufferFromFileBase (filename=..., settings=..., read_hint=..., file_size=..., flags=524288, existing_memory=<optimized out>, alignment=<optimized out>) at ../src/Disks/IO/createReadBufferFromFileBase.cpp:161
2022-11-11 10:24:12 #16 0x00000000405634df in DB::DiskLocal::readFile (this=<optimized out>, path=..., settings=..., read_hint=..., file_size=...) at ../src/Disks/DiskLocal.cpp:370
2022-11-11 10:24:12 #17 0x000000004077f5dc in DB::MetadataStorageFromDisk::readFileToString (this=this@entry=0x70e000027378, path=...) at ../src/Disks/ObjectStorages/MetadataStorageFromDisk.cpp:75
2022-11-11 10:24:12 #18 0x000000004077ffcc in DB::MetadataStorageFromDisk::readMetadataUnlocked (this=0x70e000027378, path=...) at ../src/Disks/ObjectStorages/MetadataStorageFromDisk.cpp:92
2022-11-11 10:24:12 #19 0x00000000407a9c95 in DB::UnlinkMetadataFileOperation::execute (this=0x7040001281c0, metadata_lock=...) at ../src/Disks/ObjectStorages/MetadataStorageFromDiskTransactionOperations.cpp:313
2022-11-11 10:24:12 #20 0x0000000040783213 in DB::MetadataStorageFromDiskTransaction::commit (this=0x7050005817a8) at ../src/Disks/ObjectStorages/MetadataStorageFromDisk.cpp:186
2022-11-11 10:24:12 #21 0x0000000040632ae6 in DB::DiskObjectStorageTransaction::commit (this=0x707000716908) at ../src/Disks/ObjectStorages/DiskObjectStorageTransaction.cpp:738
2022-11-11 10:24:12 #22 0x00000000405b14e9 in DB::DiskObjectStorage::removeSharedFiles (this=<optimized out>, files=..., keep_all_batch_data=false, file_names_remove_metadata_only=...) at ../src/Disks/ObjectStorages/DiskObjectStorage.cpp:267
2022-11-11 10:24:12 #23 0x0000000046c81a4f in DB::DataPartStorageOnDisk::clearDirectory (this=this@entry=0x708000606298, dir=..., can_remove_shared_data=true, names_not_to_remove=..., checksums=..., skip_directories=..., is_temp=<optimized out>, state=DB::MergeTreeDataPartState::Deleting, log=0x7040000dfc80, is_projection=<optimized out>) at ../src/Storages/MergeTree/DataPartStorageOnDisk.cpp:349
2022-11-11 10:24:12 #24 0x0000000046c784c0 in DB::DataPartStorageOnDisk::remove(std::__1::function<DB::CanRemoveDescription ()>&&, DB::MergeTreeDataPartChecksums const&, std::__1::list<DB::IDataPartStorage::ProjectionChecksums, std::__1::allocator<DB::IDataPartStorage::ProjectionChecksums> >, bool, DB::MergeTreeDataPartState, Poco::Logger*) (this=0x708000606298, can_remove_callback=..., checksums=..., projections=..., is_temp=<optimized out>, state=state@entry=DB::MergeTreeDataPartState::Deleting, log=0x7040000dfc80) at ../src/Storages/MergeTree/DataPartStorageOnDisk.cpp:301
2022-11-11 10:24:12 #25 0x0000000046dc3df6 in DB::IMergeTreeDataPart::remove (this=0x71900083cc18) at ../src/Storages/MergeTree/IMergeTreeDataPart.cpp:1670
2022-11-11 10:24:12 #26 0x0000000046fc9b8e in DB::MergeTreeData::clearPartsFromFilesystemImpl (this=this@entry=0x71e000db6020, parts_to_remove=..., part_names_succeed=<optimized out>, part_names_succeed@entry=0x7ffd3389dfc0) at ../src/Storages/MergeTree/MergeTreeData.cpp:1974
2022-11-11 10:24:12 #27 0x0000000046fc8145 in DB::MergeTreeData::clearPartsFromFilesystem (this=this@entry=0x71e000db6020, parts=..., throw_on_error=true, parts_failed_to_delete=parts_failed_to_delete@entry=0x0) at ../src/Storages/MergeTree/MergeTreeData.cpp:1915
2022-11-11 10:24:12 #28 0x0000000046fc791e in DB::MergeTreeData::clearOldPartsFromFilesystem (this=0x71e000db6020, force=true) at ../src/Storages/MergeTree/MergeTreeData.cpp:1882
2022-11-11 10:24:12 #29 0x000000004798a9cd in DB::StorageMergeTree::shutdown (this=0x71e000db6020) at ../src/Storages/StorageMergeTree.cpp:200
2022-11-11 10:24:12 #30 0x00000000405028f2 in DB::IStorage::flushAndShutdown (this=0x71e000db6020) at ../src/Storages/IStorage.h:534
2022-11-11 10:24:12 #31 DB::DatabaseWithOwnTablesBase::shutdown (this=0x713000247f58) at ../src/Databases/DatabasesCommon.cpp:293
2022-11-11 10:24:12 #32 0x0000000041c5cf62 in DB::DatabaseCatalog::shutdownImpl (this=0x71b000002300) at ../src/Interpreters/DatabaseCatalog.cpp:198
2022-11-11 10:24:12 #33 0x0000000041c736bf in DB::DatabaseCatalog::shutdown () at ../src/Interpreters/DatabaseCatalog.cpp:685
2022-11-11 10:24:12 #34 0x0000000041aa5c50 in DB::ContextSharedPart::shutdown (this=0x723000003800) at ../src/Interpreters/Context.cpp:441
2022-11-11 10:24:12 #35 0x0000000041a81552 in DB::Context::shutdown (this=<optimized out>) at ../src/Interpreters/Context.cpp:2992
2022-11-11 10:24:12 #36 0x0000000027ce62cf in DB::Server::main(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&)::$_10::operator()() const (this=0x7ffd3389ff20) at ../programs/server/Server.cpp:1476
2022-11-11 10:24:12 #37 BasicScopeGuard<DB::Server::main(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&)::$_10>::invoke() (this=0x7ffd3389ff20) at ../base/base/scope_guard.h:99
2022-11-11 10:24:12 #38 BasicScopeGuard<DB::Server::main(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&)::$_10>::~BasicScopeGuard() (this=this@entry=0x7ffd3389ff20) at ../base/base/scope_guard.h:48
2022-11-11 10:24:12 #39 0x0000000027cc53e2 in DB::Server::main (this=0x7ffd338a0410) at ../programs/server/Server.cpp:1839
2022-11-11 10:24:12 #40 0x0000000053d17596 in Poco::Util::Application::run (this=0x7ffd338a0410) at ../contrib/poco/Util/src/Application.cpp:334
2022-11-11 10:24:12 #41 0x0000000027c82299 in DB::Server::run (this=0x7ffd338a0410) at ../programs/server/Server.cpp:469
2022-11-11 10:24:12 #42 0x0000000053d78a5b in Poco::Util::ServerApplication::run (this=0x7ffd338a0410, argc=6, argv=0x70300001fcb0) at ../contrib/poco/Util/src/ServerApplication.cpp:611
2022-11-11 10:24:12 #43 0x0000000027c77eac in mainEntryClickHouseServer (argc=6, argv=0x70300001fcb0) at ../programs/server/Server.cpp:187
2022-11-11 10:24:12 #44 0x000000000bee58e8 in main (argc_=<optimized out>, argv_=<optimized out>) at ../programs/main.cpp:482
```

</details>

Or, increasing timeout after SIGTERM may help - #43277

**Comment by azat** [comment]
>Backward compatibility check

- #39174

**Pull request merged**
