### PR TITLE
Fix optimize_skip_unused_shards with JOINs

### LINKED ISSUE #15995: Exception when using optimize_skip_unused_shards = 1
We have this query
```
SELECT sum(if(inner_distributed.id != 0, 1, 0)) AS total,
       inner_distributed.date            as date
FROM outer_distributed AS outer_distributed FINAL
         LEFT JOIN (SELECT inner_distributed.outer_id  AS outer_id,
                           inner_distributed.id          AS id,
                           inner_distributed.date AS date
                    FROM inner_distributed AS inner_distributed FINAL
                    WHERE inner_distributed.organization_id = 15078) AS inner_distributed
                   ON inner_distributed.outer_id = outer_distributed.id
WHERE outer_distributed.organization_id = 15078
  AND date != toDate('1970-01-01')
GROUP BY date
ORDER BY date DESC
    SETTINGS distributed_product_mode = 'local', optimize_skip_unused_shards = 1
```
When run it produces an exception `Code: 47. DB::Exception: Received from localhost:9000. DB::Exception: Missing columns: 'date' while processing query`

However if we remove `optimize_skip_unused_shards` it runs without problems.

We are using version 20.9.3

### PR DESCRIPTION
**Pull request by azat**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix optimize_skip_unused_shards with JOINs (when the query contains some filters for the JOINed tables)

In case of JOIN query may contains conditions for other tables, while optimize_skip_unused_shards was pretty dumb and failed to skip such columns.

Fix this by removing JOIN before applying this optimization.

Fixes: #15995

### CODE REVIEW

**Comment by azat** [comment]
Can someone take a look please?

**Comment by azat** [comment]
Kind ping, looks like this got lost

**Review by alexey-milovidov — APPROVED** [review]

**Comment by azat** [comment]
Test failures are not related (and they failed in upstream/master as well):

>Integration tests (asan) [5/6] — fail: 36, passed: 389, flaky: 0

- `test_storage_s3`

```
>       raise Exception("Can't wait Minio to start")
E       Exception: Can't wait Minio to start
```

>Integration tests (tsan) [1/6] — fail: 2, passed: 356, flaky: 0

- `test_ttl_replicated/test.py::test_ttl_alter_delete[test_ttl_alter_delete_replicated]` - `Coordination::Exception: Connection loss, path: /clickhouse/test_replicated_ttl_alter_delete/replicas/1/queue/queue-0000000001`

- `test_rename_column/test.py::test_rename_with_parallel_slow_insert` - `Wrong column name. Cannot find column `foo2` to rename`

**Comment by alexey-milovidov** [comment]
Tests have failed.

**Comment by alexey-milovidov** [comment]
@azat let's investigate and fix the unrelated tests.

**Comment by azat** [comment]
Ok, though it sometimes kind of a chicken and egg problem...

>Integration tests (tsan) [4/6] — fail: 2, passed: 273, flaky: 0

- `test_keeper_restore_from_snapshot/test_disk_s3.py::test_recover_from_snapshot_with_disk_s3` - #52013 - fix [`3c18a18` (#51448)](https://github.com/ClickHouse/ClickHouse/pull/51448/commits/3c18a181c997f1f43e759d72eeadcc5d4f35142d)
- `test_keeper_s3_snapshot/test.py::test_s3_upload` - #52083

I will not look at analyzer tests for now.

**Comment by azat** [comment]
Actually the newly added test SIGSEGV server with analyzer, will take a look

**Comment by azat** [comment]
Ok, for now I simply disabled it for analyzer, since there are lots of other tests that fails because of optimize_skip_unused_shards does not work with analyzer (actually not simply "it does not work" but instead it crashes the server). Will take a look separately into this.

**Review by alexey-milovidov — APPROVED** [review]

**Comment by azat** [comment]
>Stateless tests (release) — Tests are not finished, fail: 7, passed: 2165, skipped: 2

```
2023.07.22 04:41:57.459845 [ 181544 ] {} <Fatal> BaseDaemon: ########## Short fault info ############
2023.07.22 04:41:57.459919 [ 181544 ] {} <Fatal> BaseDaemon: (version 23.7.1.1798, build id: A5A79B1F75944A5EA4A97E49C08C4254090245A2, git hash: a5bcbd834ef2e8f859bd15ef6ef084c13484fd69) (from thread 55667) Received signal 11
2023.07.22 04:41:57.460422 [ 181544 ] {} <Fatal> BaseDaemon: Signal description: Segmentation fault
2023.07.22 04:41:57.460437 [ 181544 ] {} <Fatal> BaseDaemon: Address: 0x7ef6a99ea440. Access: read. Address not mapped to object.
2023.07.22 04:41:57.460446 [ 181544 ] {} <Fatal> BaseDaemon: Stack trace: 0x0000000014e264fd 0x0000000014e2931e 0x0000000014e41f10 0x0000000014e43c68 0x000000001318b5c3
2023.07.22 04:41:57.460452 [ 181544 ] {} <Fatal> BaseDaemon: ########################################
2023.07.22 04:41:57.460490 [ 181544 ] {} <Fatal> BaseDaemon: (version 23.7.1.1798, build id: A5A79B1F75944A5EA4A97E49C08C4254090245A2, git hash: a5bcbd834ef2e8f859bd15ef6ef084c13484fd69) (from thread 55667) (query_id: 5de596ad-96bb-4853-a96f-3a5d4fbbc3aa) (query: -- these are just in case
2023.07.22 04:41:57.460530 [ 181544 ] {} <Fatal> BaseDaemon: Address: 0x7ef6a99ea440. Access: read. Address not mapped to object.
2023.07.22 04:41:57.460573 [ 181544 ] {} <Fatal> BaseDaemon: Stack trace: 0x0000000014e264fd 0x0000000014e2931e 0x0000000014e41f10 0x0000000014e43c68 0x000000001318b5c3
2023.07.22 04:41:57.504883 [ 181544 ] {} <Fatal> BaseDaemon: 2.1. inlined from ./build_docker/./src/Common/CurrentThread.cpp:95: DB::CurrentThread::getGroup()
2023.07.22 04:41:57.504926 [ 181544 ] {} <Fatal> BaseDaemon: 2. ./build_docker/./src/Client/Connection.cpp:194: DB::Connection::connect(DB::ConnectionTimeouts const&) @ 0x0000000014e264fd in /usr/lib/debug/usr/bin/clickhouse.debug
2023.07.22 04:41:57.551269 [ 181544 ] {} <Fatal> BaseDaemon: 3. ./build_docker/./src/Client/Connection.cpp:434: DB::Connection::getServerRevision(DB::ConnectionTimeouts const&) @ 0x0000000014e2931e in /usr/lib/debug/usr/bin/clickhouse.debug
2023.07.22 04:41:57.556879 [ 181544 ] {} <Fatal> BaseDaemon: 4. ./build_docker/./src/Client/ConnectionEstablisher.cpp:0: DB::ConnectionEstablisher::run(PoolWithFailoverBase<DB::IConnectionPool>::TryResult&, String&) @ 0x0000000014e41f10 in /usr/lib/debug/usr/bin/clickhouse.debug
2023.07.22 04:41:57.563450 [ 181544 ] {} <Fatal> BaseDaemon: 5. ./build_docker/./src/Client/ConnectionEstablisher.cpp:129: DB::ConnectionEstablisherAsync::Task::run(std::function<void (int, Poco::Timespan, DB::AsyncEventTimeoutType, String const&, unsigned int)>, std::function<void ()>) @ 0x0000000014e43c68 in /usr/lib/debug/usr/bin/clickhouse.debug
2023.07.22 04:41:57.567055 [ 181544 ] {} <Fatal> BaseDaemon: 6.1. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:818: ~__policy_func
2023.07.22 04:41:57.567081 [ 181544 ] {} <Fatal> BaseDaemon: 6.2. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:1174: ~function
2023.07.22 04:41:57.567089 [ 181544 ] {} <Fatal> BaseDaemon: 6.3. inlined from ./build_docker/./src/Common/AsyncTaskExecutor.cpp:84: DB::AsyncTaskExecutor::Routine::operator()(std::function<void ()>)
2023.07.22 04:41:57.567104 [ 181544 ] {} <Fatal> BaseDaemon: 6.4. inlined from ./build_docker/./src/Common/Fiber.h:70: Fiber::RoutineImpl<DB::AsyncTaskExecutor::Routine>::operator()(boost::context::fiber&&)
2023.07.22 04:41:57.567134 [ 181544 ] {} <Fatal> BaseDaemon: 6.5. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/__functional/invoke.h:394: decltype(std::declval<Fiber::RoutineImpl<DB::AsyncTaskExecutor::Routine>&>()(std::declval<boost::context::fiber>())) std::__invoke[abi:v15000]<Fiber::RoutineImpl<DB::AsyncTaskExecutor::Routine>&, boost::context::fiber>(Fiber::RoutineImpl<DB::AsyncTaskExecutor::Routine>&, boost::context::fiber&&)
2023.07.22 04:41:57.567161 [ 181544 ] {} <Fatal> BaseDaemon: 6.6. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/__functional/invoke.h:531: std::invoke_result<Fiber::RoutineImpl<DB::AsyncTaskExecutor::Routine>&, boost::context::fiber>::type std::invoke<Fiber::RoutineImpl<DB::AsyncTaskExecutor::Routine>&, boost::context::fiber>(Fiber::RoutineImpl<DB::AsyncTaskExecutor::Routine>&, boost::context::fiber&&)
2023.07.22 04:41:57.567184 [ 181544 ] {} <Fatal> BaseDaemon: 6.7. inlined from ./build_docker/./contrib/boost/boost/context/fiber_fcontext.hpp:140: boost::context::detail::fiber_record<boost::context::fiber, FiberStack&, Fiber::RoutineImpl<DB::AsyncTaskExecutor::Routine>>::run(void*)
2023.07.22 04:41:57.567196 [ 181544 ] {} <Fatal> BaseDaemon: 6. ./build_docker/./contrib/boost/boost/context/fiber_fcontext.hpp:80: void boost::context::detail::fiber_entry<boost::context::detail::fiber_record<boost::context::fiber, FiberStack&, Fiber::RoutineImpl<DB::AsyncTaskExecutor::Routine>>>(boost::context::detail::transfer_t) @ 0x000000001318b5c3 in /usr/lib/debug/usr/bin/clickhouse.debug
2023.07.22 04:41:57.567212 [ 181544 ] {} <Fatal> BaseDaemon: Integrity check of the executable skipped because the reference checksum could not be read.
2023.07.22 04:45:51.336105 [ 181544 ] {} <Fatal> BaseDaemon: This ClickHouse version is not official and should be upgraded to the official build.
2023.07.22 04:45:51.336421 [ 181544 ] {} <Fatal> BaseDaemon: Changed settings: min_compress_block_size = 485474, max_compress_block_size = 2709195, max_block_size = 70920, max_insert_threads = 9, max_threads = 49, max_read_buffer_size = 882071, connect_timeout_with_failover_ms = 2000, connect_timeout_with_failover_secure_ms = 3000, idle_connection_timeout = 36000, s3_check_objects_after_upload = true, stream_like_engine_allow_direct_select = true, replication_wait_for_inactive_replica_timeout = 30, compile_sort_description = false, group_by_two_level_threshold = 132797, enable_memory_bound_merging_of_aggregation_results = false, allow_nonconst_timezone_arguments = true, input_format_parallel_parsing = false, min_chunk_bytes_for_parallel_parsing = 3183790, merge_tree_coarse_index_granularity = 2, min_bytes_to_use_direct_io = 10737418240, min_bytes_to_use_mmap_io = 10737418240, log_queries = true, insert_quorum_timeout = 60000, http_wait_end_of_query = true, http_response_buffer_size = 2361003, fsync_metadata = true, http_send_timeout = 60., http_receive_timeout = 60., opentelemetry_start_trace_probability = 0.10000000149011612, max_untracked_memory = 1048576, memory_profiler_step = 1048576, log_comment = '01752_distributed_query_sigsegv.sql', send_logs_level = 'fatal', aggregation_in_order_max_block_bytes = 43690721, read_in_order_two_level_merge_threshold = 58, database_atomic_wait_for_drop_and_detach_synchronously = true, local_filesystem_read_method = 'io_uring', local_filesystem_read_prefetch = true, async_insert_busy_timeout_ms = 5000, enable_filesystem_cache = true, enable_filesystem_cache_on_write_operations = true, load_marks_asynchronously = true, allow_prefetched_read_pool_for_remote_filesystem = true, allow_prefetched_read_pool_for_local_filesystem = false, filesystem_prefetch_min_bytes_for_single_read_task = 16777216, filesystem_prefetch_max_memory_usage = 67108864, insert_keeper_max_retries = 20, insert_keeper_fault_injection_probability = 0.009999999776482582, optimize_distinct_in_order = false
2023.07.22 04:45:55.591346 [ 715 ] {} <Fatal> Application: Child process was terminated by signal 11.
```

- https://github.com/ClickHouse/ClickHouse/issues/51780

**Comment by azat** [comment]
>Integration tests (tsan) [5/6] — fail: 2, passed: 434

- `test_replicated_database` - #52490
- `test_memory_profiler_min_max_borders` - #52492

**Pull request merged**
