### PR TITLE
Update `query_masking_rules` when reloading the config

### LINKED ISSUE #56449: Make `query_masking_rules` reloadable without restart of a server
**Use case**

Currently, if you want to redact new things, you have to restart the clickhouse server to apply the new masking rules. It would be great to be able to take new redacting rules into use without need to restart the server.

**Additional context**

The change seems to be quite simple, so if you think it's OK to be propagated, I would like to implement it myself (I have been poking into that yesterday and I think code-wise it should be pretty much ready).

### PR DESCRIPTION
**Pull request by mkmkme**
Fixes #56449.

`query_masking_rules` are taken into account upon server start and redact the log entries. However, its changes are currently not being taken into account on config reload. In order to change this setting, you have to restart the server. This commit fixes that by adding checking this setting for changes as well.

### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Update `query_masking_rules` when reloading the config (#56449)

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]

**Comment by robot-ch-test-poll4** [comment]
*This is an automated comment for commit d4301fdd3d4017b459ce292eedf94543e363aeb0 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/56573/d4301fdd3d4017b459ce292eedf94543e363aeb0/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td><a href="https://github.com/ClickHouse/ClickHouse/actions/runs/6823856736">✅ success</a></td></tr>
<tbody>
</table>
</details>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/56573/d4301fdd3d4017b459ce292eedf94543e363aeb0/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Comment by alexey-milovidov** [comment]
Tests have failed.

**Comment by mkmkme** [comment]
Not sure why the integration test failed (but I have a suspicion about it, I'll double-check with this run).
With the latest commit, thread sanitizer should be happy.

**Comment by mkmkme** [comment]
Will try to run the stress tests locally to see why they failed

**Comment by mkmkme** [comment]
Noticed there were some changes related to CI in `master`. Updated the branch to take these changes.

**Comment by mkmkme** [comment]
Okay, so, it seems that stateless test failing is irrelevant. And I'll fix the integration test now.

**Comment by mkmkme** [comment]
Fixed the test. Now everything should be fine.

**Comment by alexey-milovidov** [comment]
Sorry, reverted: https://github.com/ClickHouse/ClickHouse/issues/57892

**Comment by mkmkme** [comment]
Thanks for letting me know! I'll try to fix the data race

**Comment by mkmkme** [comment]
@alexey-milovidov I created https://github.com/ClickHouse/ClickHouse/pull/57993. Could you take a look?

**Pull request merged**
