### PR TITLE
Workload classification for merges and mutations

### LINKED ISSUE #63211: Workload classification for merges and mutations
There is a setting `workload` that allows to specify how a query should be classified for resource consumption (only IO resources at the moment). We need a way to specify the `workload` setting for merges and mutations.

**Use case**

1. This will enable users to specify how queries and merges share IO. https://clickhouse.com/docs/en/operations/workload-scheduling#hierarchy.
2. Setting different `workload` for different tables provides a way to prioritize merges of specific tables.
3. Setting different `workload` for merges and mutations provides a way to prioritize one over another.

**Describe the solution you'd like**
Add a server and a merge tree settings `merge_workload` and `mutation_workload`.

### PR DESCRIPTION
**Pull request by serxa**
Fixes https://github.com/ClickHouse/ClickHouse/issues/63211

### Changelog category (leave one):
- New Feature

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Added `merge_workload` and `mutation_workload` settings to regulate how resources are utilized and shared between merges, mutations and other workloads.

### Documentation entry for user-facing changes

- [X] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

<details>
    <summary>Modify your CI run</summary>

**NOTE:** If your merge the PR with modified CI you **MUST KNOW** what you are doing
**NOTE:** Checked options will be applied if set before CI RunConfig/PrepareRunConfig step

#### Include tests (required builds will be added automatically):
- [ ]  Fast test
- [ ]  Integration Tests
- [ ]  Stateless tests
- [ ]  Stateful tests
- [ ]  Unit tests
- [ ]  Performance tests
- [ ]  All with ASAN
- [ ]  All with TSAN
- [ ]  All with Analyzer
- [ ]  All with Azure
- [ ]  Add your option here

#### Exclude tests:
- [ ]  Fast test
- [ ]  Integration Tests
- [ ]  Stateless tests
- [ ]  Stateful tests
- [ ]  Performance tests
- [ ]  All with ASAN
- [ ]  All with TSAN
- [ ]  All with MSAN
- [ ]  All with UBSAN
- [ ]  All with Coverage
- [ ]  All with Aarch64
- [ ]  Add your option here

#### Extra options:
- [ ]  do not test (only style check)
- [ ]  disable merge-commit (no merge from master before tests)
- [ ]  disable CI cache (job reuse)

#### Only specified batches in multi-batch jobs:
- [ ]  1
- [ ]  2
- [ ]  3
- [ ]  4

</details>

### CODE REVIEW

**Comment by robot-clickhouse** [comment]
*This is an automated comment for commit 580577d362f9236a2b21a74c7e7f015d9fbac441 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/64061/580577d362f9236a2b21a74c7e7f015d9fbac441/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

**Review by alesapin — APPROVED** [review]
LGTM

**Comment by Avogar** [comment]
Test `03036_dynamic_read_subcolumns` was failing in master. It's already fixed so I updated the branch with recent changes to avoid its failing in the CI

**Comment by serxa** [comment]
`02152_http_external_tables_memory_tracking` - flaky. And I fixed and merged "A sync" PR, but for some reason it is still shown as:
```
A Sync — Failed to merge into the sync PR, manual merge required. Job ID:26329772398
```
So I'll force mergeable check now.

**Pull request merged**
