### PR TITLE
fix flaky 02864_statistics_uniq

### PR DESCRIPTION
**Pull request by hanfei1991**
1. DROP STATISTICS should not run if there is same statistics materializing
2. should set mutations_sync = 1 in the test

### Changelog category (leave one):
- CI Fix or Improvement (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
...

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-ch-test-poll4** [comment]
*This is an automated comment for commit bcdbb4ce08fc8088e0f08a903ae2ee5d87c528cd with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/65599/bcdbb4ce08fc8088e0f08a903ae2ee5d87c528cd/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Cloud fork sync (only for ClickHouse Inc. employees)</td><td>If it fails, ask a maintainer for help</td><td>⏳ pending</td></tr>
<tbody>
</table>
<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>Checks correctness of the PR's body</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

**Review by yariks5s — COMMENTED** [review]
> Distributed DDL task /clickhouse/task_queue/ddl/query-0000000971 is not finished on 1 of 3 hosts (1 of them are currently executing the task, 0 are inactive). They are going to execute the query in background. Was waiting for 120.352808482 seconds, which is longer than distributed_ddl_task_timeout. (TIMEOUT_EXCEEDED)


↑ failed test can be related to the current topic

**Comment by hanfei1991** [comment]
@yariks5s it seems like being flaky for a long while : https://s3.amazonaws.com/clickhouse-test-reports/0/3f58fcb26b5f6211342938e4fffccc9a5d141152/stateless_tests__release__old_analyzer__s3__databasereplicated__[2_4].html here is the master ci

**Review by yariks5s — APPROVED** [review]

**Comment by yariks5s** [comment]
Did adding the `mutations_sync = 1;` parameter cause the test to fail before?

**Comment by hanfei1991** [comment]
by default `mutation_sync` = 0, which means we did not `materialize statistics`. It's possible that before we actually do materialize, the statisitcs has been dropped, which cause every mutation hangs, so we need to:

1. do not hang when such error happens, when we choose do materialize async, we should raise error when doing drop.
2. set `mutation_sync = 1` to make test execute `meterialize statistics` completely sync

**Comment by hanfei1991** [comment]
`01526_client_start_and_exit` failed due to executing create table too slow (I guess). maybe I can try to fix it too

**Comment by clickgapai** [comment]
Hi @hanfei1991 @yariks5s — while reviewing this PR I found the following:

- **Bug (P2):** `checkDropOrRenameCommandDoesntAffectInProgressMutations` doesn't detect conflict between `DROP STATISTICS` and `MATERIALIZE STATISTICS ALL` — https://github.com/ClickHouse/ClickHouse/issues/104894

Happy to discuss — close anything that's wrong or already addressed.

**Pull request merged**
