### PR TITLE
WIP: Add syntax highlighting

### PR DESCRIPTION
**Pull request by kuskarov**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- New Feature

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Added syntax highligting to clickhouse-client using ReplXX

Detailed description / Documentation draft:

Syntax is highlighted using Lexer. Input query is passed to Lexer and each token has its own color.

By adding documentation, you'll allow users to try your new feature immediately, not when someone else will have time to document it later. Documentation is necessary for all features that affect user experience in any way. You can add brief documentation draft above, or add documentation right into your patch as Markdown files in [docs](https://github.com/ClickHouse/ClickHouse/tree/master/docs) folder.

If you are doing this for the first time, it's recommended to read the lightweight [Contributing to ClickHouse Documentation](https://github.com/ClickHouse/ClickHouse/tree/master/docs/README.md) guide first.

### CODE REVIEW

**Comment by qoega** [comment]
Converted to draft for now.

**Comment by vkingnew** [comment]
syntax highligting to clickhouse-client using ReplXX，this function,cloud you give a demo to show it ?

**Comment by alexey-milovidov** [comment]
@vkingnew This PR is already merged and basic syntax highlighting is available since 20.5 release.

**Comment by alexey-milovidov** [comment]
This PR implements syntax highlighting based on tokens (lexer).
I also have another PR (not merged) with advanced syntax highlighting.

**Comment by vkingnew** [comment]
syntax highligting  this functions how use？

**Comment by alexey-milovidov** [comment]
@vkingnew

Do I understand your question correctly?

Q: How to enable syntax highlighting in ClickHouse?
A: It is available and enabled since ClickHouse version 20.5.

**Pull request merged**
