### PR TITLE
clickhouse version adds a branch logo to more clearly display the current version

### PR DESCRIPTION
**Pull request by guoxiaolongzte**
eg 1:
Current master version:23.10.1.1,
We can change it to 23.10.1.1_branch_version.

eg 2:
[23.3 ]https://github.com/ClickHouse/ClickHouse/tree/v23.3.14.78-lts  tag version:23.3.14.1, it from autogenerated_versions.txt, we use this tag for code development management, and the branch name is master_ClickHouse_v23.314.78-lts
We can change it to23.3.14.1_master_ClickHouse_ v23.314.78-lts, this makes it very clear. 
Of course, we provide the switch ENABLE_ BRANCH_ VERSION

This is a very important feature.
We will customize the same version with some company-customized functions or incorporate some new ClickHouse features or meet some of our business's regular needs. We will release it multiple times. We will not frequently update the ClickHouse open source version frequently. Over time, In addition, we may have dozens of ClickHouse clusters online. Maybe we don’t know which branch packages the online version of a certain cluster. But if there is this function, I can clearly locate which branch the online ClickHouse is packaged through. Versions and branches are packaged and released.
We can query via select version() or clickhouse-server --version.

### Changelog category (leave one):
- Build/Testing/Packaging Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
clickhouse version adds a branch logo to more clearly display the current version

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by robot-clickhouse-ci-2** [comment]
*This is an automated comment for commit f17ef979dbe3b3219c75a48cd69e0592c747f7ff with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/56041/f17ef979dbe3b3219c75a48cd69e0592c747f7ff/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td><a href="https://github.com/ClickHouse/ClickHouse/actions/runs/6652467063">✅ success</a></td></tr>
<tbody>
</table>
</details>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/56041/f17ef979dbe3b3219c75a48cd69e0592c747f7ff/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Comment by alexey-milovidov** [comment]
It's not clear whether we need this.

**Comment by guoxiaolongzte** [comment]
> It's not clear whether we need this.
This is a very important feature.
We will customize the same version with some company-customized functions or incorporate some new ClickHouse features or meet some of our business's regular needs. We will release it multiple times. We will not frequently update the ClickHouse open source version frequently. Over time, In addition, we may have dozens of ClickHouse clusters online. Maybe we don’t know which branch packages the online version of a certain cluster. But if there is this function, I can clearly locate which branch the online ClickHouse is packaged through. Versions and branches are packaged and released.
We can query via select version() or clickhouse-server --version.

**Comment by rschu1ze** [comment]
It is possible to get the branch name already today: https://fiddle.clickhouse.com/75b731b2-63a8-425c-bb08-7555e139f8e5

**Comment by guoxiaolongzte** [comment]
> It is possible to get the branch name already today: https://fiddle.clickhouse.com/75b731b2-63a8-425c-bb08-7555e139f8e5

why ？
root@28f72aac02fe:~/v23.3.14.78-lts/ClickHouse/build/programs# **./clickhouse-local --query "SELECT * FROM system.build_options WHERE name LIKE 'VERSION_FULL%'"
VERSION_FULL    ClickHouse 23.3.14.1**

root@28f72aac02fe:~/v23.3.14.78-lts/ClickHouse# git log
commit c8f4ba52c65d2a2ee4ec58c5e44accfb26b6e535 (HEAD, tag: v23.3.14.78-lts)
Merge: c652cd6f31f 419c49728eb
Author: robot-clickhouse-ci-1 <118761991+robot-clickhouse-ci-1@users.noreply.github.com>
Date:   Fri Oct 13 00:17:33 2023 +0200

    Merge pull request #55565 from ClickHouse/backport/23.3/55062

    Backport #55062 to 23.3: Prevent attaching parts from tables with different projections or indices



and 

**https://fiddle.clickhouse.com/a96798e3-36cc-4c4f-803d-df6dc1add11a**

**Comment by guoxiaolongzte** [comment]
I proactively compiled it using cmake and ninja. Your package was typed by CI, and the problem may have arisen here. Let me analyze it.

**Pull request closed without merging**
