### PR TITLE
Try out bigger inline threshold in clang release

### PR DESCRIPTION
**Pull request by danlark1**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Performance Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Try out clang inline threshold 1000

Detailed description / Documentation draft:
Let's try out inline threshold 1000 to see the binary size, compilation times and performance gains. Also it might show some places where inlining is crucial and we can manually write force inlines.

### CODE REVIEW

**Comment by danlark1** [comment]
Nothing interesting, let's try out experimental-new-pass-manager

**Comment by danlark1** [comment]
[ThinLTO 0.5%](https://clickhouse-test-reports.s3.yandex.net/15595/b3fa86191e4f85ad3ff4d72d6370d56b80be868c/performance_comparison/report.html#fail1)
[ThinLTO + fexperimental-pass-manager 1%](https://clickhouse-test-reports.s3.yandex.net/15577/0d505e389912460fac14f6d906655b14d5dd0c04/performance_comparison/report.html#fail1)

**Comment by alexey-milovidov** [comment]
4% will pay for 7 minutes and +450 MB binary size :)

**Comment by alexey-milovidov** [comment]
PS. I cannot understand the reason for MSan error :(

**Comment by danlark1** [comment]
> PS. I cannot understand the reason for MSan error :(

100% unrelated flap

**Pull request closed without merging**
