### PR TITLE
Make higher order functions constexpr

### PR DESCRIPTION
**Pull request by alexey-milovidov**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Higher-order functions with constant arrays and constant captured arguments will return constants.

### CODE REVIEW

**Comment by robot-clickhouse-ci-2** [comment]
*This is an automated comment for commit 03278bf3178c6b7bcbb6da6510e4f3e7ff94d2a4 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/58400/03278bf3178c6b7bcbb6da6510e4f3e7ff94d2a4/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/58400/03278bf3178c6b7bcbb6da6510e4f3e7ff94d2a4/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Comment by alexey-milovidov** [comment]
It was enabled only for Analyzer.

However, I found that even with Analyzer, the constant folding of lambda functions is incomplete.

**Comment by alexey-milovidov** [comment]
@Felixoid, this is not a bugfix. This is a complex and risky change, which implements a new feature.
Backporting it would be reckless.

**Comment by Felixoid** [comment]
hmm, ok, what then should we do with 24.8?

24.3 is almost at the end of life, but the August release will be alive for another 8 months.

**Pull request merged**
