### PR TITLE
youtube questions

### PR DESCRIPTION
**Pull request by gingerwizard**
### Changelog category (leave one):
- Documentation (changelog entry is not required)

Some questions compiled for youtube dataset.

### CODE REVIEW

**Review by rfraposa — APPROVED** [review]
Brilliant - thanks!

**Review by alexey-milovidov — APPROVED** [review]

**Comment by rfraposa** [comment]
@gingerwizard - I'm realizing your queries that were added to this doc do not run as-is. 

For example:

```
SELECT
    toStartOfMonth(upload_date) AS month,
    countIf(has_subtitles) / count() AS percent_subtitles,
    percent_subtitles - any(percent_subtitles) OVER (ORDER BY month ASC ROWS BETWEEN 1 PRECEDING AND 1 PRECEDING) AS previous
FROM youtube
WHERE (month >= '2007-01-01') AND (month < '2014-12-02')
GROUP BY month
ORDER BY month ASC;
```

throws this:

```
"Code: 43. DB::Exception: Illegal type String of argument of function toStartOfMonth. Should be Date, Date32, DateTime or DateTime64: While processing toStartOfMonth(upload_date) AS month. (ILLEGAL_TYPE_OF_ARGUMENT) (version 22.13.1.24495 (official build))\n"
```

Plus, you have a discussion about subtitles spiking in 2009, but your query filters on the years 2015 - 2021.  

I may revert this until we get the new queries cleaned up - I can't get them to run easily...

**Comment by rfraposa** [comment]
Actually - only a few of them failed, so I just deleted those for now here: https://github.com/ClickHouse/ClickHouse/pull/48265

**Comment by alexey-milovidov** [comment]
@rfraposa if you have date as String, it is a mistake in the schema.

**Comment by rfraposa** [comment]
I have it as a `Date`, but Dale must have used a string. And converting strings to dates does not work on every row - which gets caught nicely during ingest, but parsing errors during a query are not as nice.

**Comment by gingerwizard** [comment]
```
CREATE TABLE default.youtube
(
    `id` String,
    `url` String,
    `fetch_date` DateTime,
    `upload_date_str` String,
    `upload_date` Date,
    `title` String,
    `uploader_id` LowCardinality(String),
    `uploader` LowCardinality(String),
    `uploader_sub_count` Int32,
    `is_age_limit` Bool,
    `view_count` Int64,
    `like_count` Int32,
    `dislike_count` Int32,
    `is_crawlable` Bool,
    `is_live_content` Bool,
    `has_subtitles` Bool,
    `is_ads_enabled` Bool,
    `is_comments_enabled` Bool,
    `description` String CODEC(ZSTD(3)),
    `rich_metadata` Array(Map(String, String)),
    `super_titles` Array(Map(String, String)),
    `uploader_badges` Enum8('' = 0, 'Official Artist Channel' = 1, 'Verified' = 2),
    `video_badges` LowCardinality(String)
)
ENGINE = ReplicatedMergeTree('/clickhouse/tables/{uuid}/{shard}', '{replica}')
ORDER BY (toStartOfMonth(upload_date), uploader)
```

play schema @rfraposa

**Comment by gingerwizard** [comment]
All queries run against https://sql.clickhouse.com/play

**Comment by gingerwizard** [comment]
@rfraposa you schema has as String https://clickhouse.com/docs/en/getting-started/example-datasets/youtube-dislikes

**Comment by rfraposa** [comment]
Ah sorry! I was looking at the Amazon reviews dataset. I will fix now... 🤦

**Pull request merged**
