### PR TITLE
Seperate max_execution_time and max_estimated_execution_time

### PR DESCRIPTION
**Pull request by zhangyifan27**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Adding a setting `max_estimated_execution_time` to separate `max_execution_time` and `max_estimated_execution_time`.

### Documentation entry for user-facing changes

- [x] Documentation is written (mandatory for new features)

Related issue https://github.com/ClickHouse/ClickHouse/issues/12169

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by zhangyifan27** [comment]
Related issue #12169

**Comment by robot-clickhouse** [comment]
*This is an automated comment for commit 621eacaff7b94fee940609c4fa015c771a9c2a0d with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/58402/621eacaff7b94fee940609c4fa015c771a9c2a0d/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/58402/621eacaff7b94fee940609c4fa015c771a9c2a0d/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Comment by qoega** [comment]
Fail in 02896_max_execution_time_with_break_overflow_mode seems related.

**Comment by zhangyifan27** [comment]
> Fail in 02896_max_execution_time_with_break_overflow_mode seems related.

I test it by running `tests/clickhouse-test 02896_max_execution_time_with_break_overflow_mode` locally and it passed. I have no idea why it failed with a timeout error.

**Comment by zhangyifan27** [comment]
It seems that the failure only occurs in 'Stateless tests (release, analyzer)', but doesn't occur in 'Stateless tests (release)'. Is there any difference between them?

**Comment by jsc0218** [comment]
thanks for the fix, and other failed tests are irrelevant I think.

**Comment by tavplubix** [comment]
@jsc0218, it breaks Upgrade Check: https://s3.amazonaws.com/clickhouse-test-reports/39507/fe1e326701b0566881dc7d51793125a911faa07e/upgrade_check__debug_.html

**Comment by jsc0218** [comment]
> @jsc0218, it breaks Upgrade Check: https://s3.amazonaws.com/clickhouse-test-reports/39507/fe1e326701b0566881dc7d51793125a911faa07e/upgrade_check__debug_.html

fixed in https://github.com/ClickHouse/ClickHouse/pull/59104

**Comment by azat** [comment]
Maybe `max_estimated_execution_time` should inherits the value of the `max_execution_time` if `max_estimated_execution_time` is not changed?

**Pull request merged**
