### PR TITLE
Fix filtering by virtual columns with OR filter in query

### LINKED ISSUE #54779: WHERE-clause with two ORs doesn't evaluate to true
**What's wrong**

Hello. We encountered a regression in some of our queries after upgrading Clickhouse from 23.7 to 23.8. Now, inside a WHERE-clause a three-literal or-clause doesn't get evaluated right if two of the clauses are always false and one is sometimes true.

**Does it reproduce on recent release?**

Every release starting with 23.8

**How to reproduce**

```
CREATE TABLE or_bug (column_1 UInt8) ENGINE=MergeTree ORDER BY column_1;

INSERT INTO TABLE or_bug VALUES (0), (1);

SELECT * FROM or_bug WHERE (column_1 = 1) OR false OR false;

Ok.

0 rows in set. Elapsed: 0.001 sec.
```

Same behavior with fiddle (using versions >= 23.8): https://fiddle.clickhouse.com/424f3fbf-58db-4b3a-b1c8-f4a287a9bf05

**Expected behavior**

Clickhouse should (and did with 23.7) instead return

```
┌─column_1─┐
│        1 │
└───────────
```

**Additional context**

Note that this doesn't happen with `ENGINE=Memory` and only happens with two times "OR false", not one or three times "OR false".

### LINKED ISSUE #55288: Can't get query result with mutiple OR 0 = 1  conditions
**Describe what's wrong**

Can't get result with mutiple false OR conditions

**Does it reproduce on recent release?**
yes

**How to reproduce**

* Which ClickHouse server version to use
the latest TLS  23.8.3.48

* `CREATE TABLE` statements for all tables involved
 ```
CREATE TABLE default.forms
(
    `form_id` FixedString(24),
    `text_field` String
)
ENGINE = MergeTree
PRIMARY KEY form_id
ORDER BY form_id
```
* Sample data for all these tables
```
insert into forms values ('5840ead423829c1eab29fa97','this is a test');
```
* Queries to run that lead to unexpected result
```
 select * from forms where text_field like '%this%' or 0 = 1 or 0 = 1  ;
```
**Expected behavior**
Above query should able to get same result as below query
```
select * from forms where text_field like '%this%' or 0 = 1 ;
```

### PR DESCRIPTION
**Pull request by azat**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix filtering by virtual columns with OR filter in query (`_part*` filtering for `MergeTree`, `_path`/`_file` for various `File`/`HDFS`/... engines, `_table` for `Merge`)

The problem with the initial implementation #52653 was:
- OR can have multiple arguments
- It simply not correct to assume that if there are two arguments this is OK.
  Consider the following example:

    "WHERE (column_not_from_partition_by = 1) OR false OR false"

  Will be converted to:

    "WHERE false OR false"

And it will simply read nothing.

Yes, we could apply some optimization for bool, but this will not always
work, since to optimize things like "0 = 1" we need to execute it.

And the only way I see to handle this correctly (with ability to ignore
some expressions during filtering) is to make is_constant() function return
has it use something from the input block, so that we can be sure, that
we have something sensible, and not just "false".

Plus we cannot simply ignore the difference of the input and output
arguments of handling OR, we need to add always-true (1/true) if the
size is different, since otherwise it could break invariants (see
comment in the code).

P.S. analyzer does not have this bug, since it execute expression as
whole, and this is what filterBlockWithQuery() should do actually
instead, but this will be a more complex patch.

Fixes: https://github.com/ClickHouse/ClickHouse/pull/52653 (cc @alexey-milovidov )
Fixes: https://github.com/ClickHouse/ClickHouse/issues/54779 (cc @slanderous-mambo )
Fixes: https://github.com/ClickHouse/ClickHouse/issues/55288

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]

**Comment by robot-clickhouse-ci-2** [comment]
*This is an automated comment for commit 109e56e80816200e03582f02edc3354c04bee975 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/55418/109e56e80816200e03582f02edc3354c04bee975/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td><a href="https://github.com/ClickHouse/ClickHouse/actions/runs/6458105672">✅ success</a></td></tr>
<tbody>
</table>
</details>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/55418/109e56e80816200e03582f02edc3354c04bee975/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Comment by den-crane** [comment]
probably it should fix https://github.com/ClickHouse/ClickHouse/issues/55288 as well

**Comment by azat** [comment]
>Stateless tests (tsan) [5/5] — Tests are not finished, fail: 7, passed: 236, skipped: 1

- #55626

**Comment by azat** [comment]
Test failures looks unrelated now

**Comment by alexey-milovidov** [comment]
> FIXME: Got an API for which error does not match any expected type!!!

Is it possible to replace Docker with Podman?

**Comment by azat** [comment]
>Is it possible to replace Docker with Podman?

AFAIR I thought about this and it wasn't that easy, and you are right - likely it can be fixed that way (even though they use some common libraries unlikely this could be related in this particular case), but it also can have some podman-related issues that will pops up in CI.

Maybe it will be simpler to find the problem in the docker itself, or maybe updating it will be enough...

**Comment by antonio2368** [comment]
@azat it looks like `test_system_merges` were related, it's consistently failing after this PR was merged

**Comment by alexey-milovidov** [comment]
Revert it.

**Comment by azat** [comment]
@antonio2368 you are right.

That was over optimistic from my side to assume that my fix for this test https://github.com/ClickHouse/ClickHouse/pull/55627 addresses this problems, however the problem was completely different, since after my patch `x OR 1` simply does not execute `x`, and so `sleep` did not even executed.

So I've resubmitted it here - https://github.com/ClickHouse/ClickHouse/pull/55678 with a fix for the test.

Also note, that this PR had been already backported, while your revert had not, so you need to apply only the test hunk from the resubmit (and to avoid conflicts you need to apply https://github.com/ClickHouse/ClickHouse/pull/55627 first).

**Pull request merged**
