### PR TITLE
Saturate negative unix timestamp to zero instead of overflow

### LINKED ISSUE #3470: SELECT toDateTime('1970-01-01 00:00:00') -> 1970-01-01 06:28:16 for time zone other than UTC
Selecting when time zone is not UTC shows wrong (1970-01-01 06:28:16) datetime.

`ClickHouse client version 18.14.10.
Connecting to localhost:9000.
Connected to ClickHouse server version 18.14.10 revision 54409.

blade8.lab.bulb.hr :) SELECT toDateTime('1970-01-01 00:00:00')

SELECT toDateTime('1970-01-01 00:00:00')

┌─toDateTime('1970-01-01 00:00:00')─┐
│               1970-01-01 06:28:16 │
└───────────────────────────────────┘

1 rows in set. Elapsed: 0.011 sec.`

### LINKED ISSUE #4172: Datetime condition returns inconsistent result
```
select * from reporting_events where device_id = 2 and ts >= '1970-01-01 00:00:00';

SELECT *
FROM reporting_events 
WHERE (device_id = 2) AND (ts >= '1970-01-01 00:00:00')

Ok.

0 rows in set. Elapsed: 0.004 sec.
```

Now, adding 1 day to the string `1970-01-01 00:00:00` and make it `1970-01-02 00:00:00`

```
select * from reporting_events where device_id = 2 and ts >= '1970-01-02 00:00:00';

SELECT *
FROM reporting_events 
WHERE (device_id = 2) AND (ts >= '1970-01-02 00:00:00')

┌─id─┬─device_id─┬──────────────────ts─┬─event_hashcode─┬─type─┬─description─┬─is_resolved─┬─resolved_by─┬─────────resolved_at─┬─resolved_comment─┐
│ 40 │         2 │ 2019-01-28 18:17:08 │      613812780 │    4 │             │           0 │             │ 0000-00-00 00:00:00 │                  │
└────┴───────────┴─────────────────────┴────────────────┴──────┴─────────────┴─────────────┴─────────────┴─────────────────────┴──────────────────┘
┌─id─┬─device_id─┬──────────────────ts─┬─event_hashcode─┬─type─┬─description─┬─is_resolved─┬─resolved_by─┬─────────resolved_at─┬─resolved_comment─┐
│ 39 │         2 │ 2019-01-28 18:17:08 │    -1958892973 │    0 │             │           0 │             │ 0000-00-00 00:00:00 │                  │
└────┴───────────┴─────────────────────┴────────────────┴──────┴─────────────┴─────────────┴─────────────┴─────────────────────┴──────────────────┘

2 rows in set. Elapsed: 0.005 sec. 
```

```
CREATE TABLE reporting_events (
  id UInt64,
  device_id UInt32,
  ts DateTime DEFAULT now(),
  event_hashcode Int32,
  type UInt8,
  description String,
  is_resolved UInt8,
  resolved_by String,
  resolved_at DateTime,
  resolved_comment String
)
ENGINE = MergeTree()
PARTITION BY toYYYYMM(ts)
ORDER BY (device_id, ts, event_hashcode, type);
```

I found a similar issue - https://github.com/yandex/ClickHouse/issues/2596. However, comparison result seems wrong to me. How it should be handled if this is expected?

### PR DESCRIPTION
**Pull request by alexey-milovidov**
Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Avoid overflow in parsing of DateTime values that will lead to negative unix timestamp in their timezone (for example, `1970-01-01 00:00:00` in Moscow). Saturate to zero instead. This fixes #3470. This fixes #4172.

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
@akuzm Performance test showed "2 faster, 20 slower" in queries without related code paths.

**Comment by alexey-milovidov** [comment]
>  Yandex synchronization check (only for Yandex employees) Pending — error, check will be restarted

False claim, the check was not restarted, CC @exprmntr.

**Comment by alexey-milovidov** [comment]
Ok, probably it is because I did not merge with master and performance of master was improved.
@akuzm Why it is not merged with master before running tests?

**Comment by akuzm** [comment]
> Ok, probably it is because I did not merge with master and performance of master was improved.
> @akuzm Why it is not merged with master before running tests?

It's more complicated -- it choose the master for comparison that is newer than the master it was merged to before build, because the perf test task cloned the repository later, when it was merged to a newer master on github... I have an idea for a fix, will try.

**Comment by alexey-milovidov** [comment]
Performance test Ok.

**Pull request merged**
