### PR TITLE
WIP - manipulate the DataDog DDSketch in ClickHouse

### PR DESCRIPTION
**Pull request by moming00**
### Changelog category:
- New Feature

### Changelog entry:
Add a new data type DDSketch(Float32) represent a DDSketch object. For more information on ddsketch, see [computing accurate percentiles with ddsketch](https://www.datadoghq.com/blog/engineering/computing-accurate-percentiles-with-ddsketch/).

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

Here is the designed usage:
```sql
CREATE TABLE NetTrafficMonitor(`timestamp` DateTime64(3, 'Asia'), `sendLatency` Float64) ENGINE = Memory;
CREATE TABLE TestSketch(`name` String, `timestamp` DateTime64(3, 'Asia'), `sketch` NULLABLE(DDSketch(0.01))) ENGINE = Memory;

# Build a sketch object
WITH thetime = toDateTime64('2022-01-01 10:20:30.999', 3)
INSERT INTO TestSketch
    SELECT 'sendLatency', thetime, ddsketchBuild(0.01, sendLatency) FROM NetTrafficMonitor WHERE timestamp < thetime;

WITH thetime = toDateTime64('2020-01-01 10:20:30.999', 3)
INSERT INTO TestSketch
    SELECT 'sendLatency', thetime, ddsketchBuildIf(0.01, sendLatency, timestamp < thetime) FROM NetTrafficMonitor;

# Query quantiles
SELECT ddsketchQuery(sketch, 0.5) From TestSketch Where name = 'sendLatency';

# Get element total count
Select ddsketchCount(sketch) From TestSketch Where name = 'sendLatency';

# Get average
Select ddsketchAverage(sketch) From TestSketch Where name = 'sendLatency';

# Sketch add array of elements with corresponding multiplier specified
WITH tmp AS (SELECT count() AS a, sendLatency AS b FROM NetTrafficMonitor WHERE timestamp >= now() group by sendLatency),
tmp1 AS (SELECT groupArray(a) AS arrayA, groupArray(b) AS arrayB FROM tmp)
UPDATE sketch = ddsketchAddSingle(sketch, tmp1.arrayA, tmp1.arrayB) FROM TestSketch WHERE name = 'sendLatency';

# Sketch merge
SELECT ddsketchQuery(ddsketchMerge(sketch), 0.95) FROM TestSketch 
    WHERE timestamp BETWEEN toDateTime64('2022-01-01 10:20:30.999', 3) AND toDateTime64('2023-01-01 10:20:30.999', 3);
```

DDSketch object will be stored as protobuf encoded binary string in ClickHouse.
Please refer to the ddsketch.md and ddsketch-functions.md for the detailed design notes.

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by moming00** [comment]
@alexey-milovidov Could you help review the design notes and see if I'm on the right direction? Any inputs will be much appreciated.

**Comment by moming00** [comment]
Here is the ddsketch library will be used with related sketch operations, and the benchmark data in the README: https://github.com/moming00/ddsketch-cpp

**Comment by evillique** [comment]
Sorry for the late response. I'm not particularly familiar with DDLSketch and wanted to ask some questions regarding your proposal:
1. Why do we need a separate type for DDSketch? What exactly do we store in this column after we insert a value? 
2. How does aggregation works with DDSketch typed column?
3. Can we implement the DDSketch percentile aggregation function without introducing a new DDSketch type?

**Comment by alexey-milovidov** [comment]
I strongly suggest implementing it without adding a new data type.

**Comment by moming00** [comment]
> I strongly suggest implementing it without adding a new data type.

thanks alexey for the input. We will need to find out a solution to avoid the mentioned cons, also because of other tasks with higher priority, close the PR for now.

**Comment by yandooo** [comment]
It's indeed an interesting initiative. 
Our implementation uses basic Clickhouse primitives storing DDsketch data in separate columns. There is a special UDF build to query quantile, merge (support for Window Views and Materialized views aggregations), convert to Prometheus histograms, and support function to support SLO (aka "90% of requests < 500 ms", etc.).
The biggest disadvantage for UDF is serialization/deserialization between processes + transferring data through reading stdin. It adds significant latency for certain high sketch data volume merge operations + sometimes crashes the Clickhouse server (https://github.com/ClickHouse/ClickHouse/issues/43825).
Ideally, UDF can be ported to C++ codebase and don't require adding custom times (possible to pass relative errors paras as functions inputs)

**Pull request closed without merging**
