### PR TITLE
Support keeper failures in quorum check

### PR DESCRIPTION
**Pull request by Algunenano**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
- Support keeper failures in quorum check

### Documentation entry for user-facing changes

Keep removing unhandled cases of keeper failures.

### CODE REVIEW

**Comment by robot-clickhouse** [comment]
*This is an automated comment for commit 03468508974755c4f7308a4812616c613a09bfee with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/57986/03468508974755c4f7308a4812616c613a09bfee/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td><a href="https://github.com/ClickHouse/ClickHouse/actions/runs/7247698410">✅ success</a></td></tr>
<tbody>
</table>
</details>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/57986/03468508974755c4f7308a4812616c613a09bfee/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Comment by Algunenano** [comment]
Looks like I need to also bring the changes to ZookeeperRetries (so the failures/loops can be shared). On it

**Comment by Algunenano** [comment]
Failures:
* `Stateless tests (debug) [5/5]`: `02833_local_with_dialect`. Already fixed in https://github.com/ClickHouse/ClickHouse/pull/58046
* `Stateless tests flaky check (asan) `: Long test timeout (`01509_parallel_quorum_and_merge_long`).

**Comment by Algunenano** [comment]
@hanfei1991 Can this be merged?

**Review by hanfei1991 — APPROVED** [review]
LGTM

**Comment by Algunenano** [comment]
Failures:
* `Integration tests (asan, analyzer) [6/6] `: Flaky https://github.com/ClickHouse/ClickHouse/issues/57651
* `Stateless tests flaky check (asan)`: `01459_manual_write_to_replicas_quorum_detach_attach` failed once in `TABLE_IS_READ_ONLY` because the initialization of the table failed (`Initialization failed, table will remain readonly. Error: Code: 231. DB::Exception: The local set of parts of table test_2bi465ad.r4 doesn't look like the set of parts in ZooKeeper: 1.00 rows of 1.00 total rows in filesystem are suspicious. There are 1 uncovered unexpected parts with 1 rows (0 of them is not just-written with 0 rows), 0 missing parts (with 0 blocks), 0 covered unexpected parts (with 0 rows). (TOO_MANY_UNEXPECTED_DATA_PARTS)`). Same error as https://github.com/ClickHouse/ClickHouse/issues/57651
* Upgrade failures, related to `Wrong number of engine arguments` due to is_deleted removal.

**Pull request merged**
