### PR TITLE
Do not set PR status label

### PR DESCRIPTION
**Pull request by vdimir**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Review by novikd — APPROVED** [review]

**Comment by robot-ch-test-poll** [comment]
*This is an automated comment for commit 357bf3ce3c68325b43721c4b3a7926d6588677a6 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/54799/357bf3ce3c68325b43721c4b3a7926d6588677a6/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>✅ success</td></tr>
<tbody>
</table>
</details>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>⏳ pending</td></tr>
<tbody>
</table>

**Comment by tavplubix** [comment]
Let's also remove "pr-status-❌"

**Comment by vdimir** [comment]
Should we delete existing labels automatically or don't bother leaving the code for that?

**Comment by Felixoid** [comment]
We'll remove them manually after some time. Otherwise we could cause vzdrzhni in existing PRs

**Pull request merged**
