### PR TITLE
Fix race condition in ZooKeeperImpl

### PR DESCRIPTION
**Pull request by ghost**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Category (leave one):
- Bug Fix

Short description (up to few sentences):

ZooKeeperImpl tries to concurrently join send_thread/receive_thread from two different threads.

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
Could you please describe the scenario that reproduces the issue?
The fix looks too heavyweight. We need to understand the root cause of the issue.

**Comment by pavel-belikov** [comment]
pthread_cond_wait and pthread_cond_destroy were call on the same conditional variable. The main thread was unwinding stack and called ~ZooKeeperImpl, the receiveThread got exception and called finalize.

Stacktrace:

```
Thread 6 (Thread 0x7fe39cd03bc0 (LWP 629694)):
#0  0x00007fe39c4d1404 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x0000000003103f22 in Poco::EventImpl::waitImpl (this=0x7fe39b41f398)
#2  0x0000000003269f36 in wait (this=0x7fe39b41f3cc)
#3  join (this=0x7fe39b42d5a0)
#4  Coordination::ZooKeeper::~ZooKeeper (this=0x7fe39b42d280)
#5  0x000000000326b11e in Coordination::ZooKeeper::~ZooKeeper (this=0x7fe39b42d280)
#6  0x0000000002dfd50e in __release_shared (this=0x7fe39b41d340)
#7  __release_shared (this=0x7fe39b41d340)
#8  ~shared_ptr (this=0x7fe39b4bcde0)
#9  ~ZooKeeperHolder (this=0x7fe39b4bcdb8)
#10 std::__y1::__shared_ptr_emplace<zk::ZooKeeperHolder, std::__y1::allocator<zk::ZooKeeperHolder> >::__on_zero_shared (this=0x7fe39b4bcda0)
#11 0x0000000002dfd3fa in __release_shared (this=0x7fe39b4bcda0)
#12 __release_shared (this=0x7fe39b4bcda0)
#13 ~shared_ptr (this=<optimized out>)
#14 NDaemon::BaseDaemonApplication::~BaseDaemonApplication (this=0x7ffe6a92fab8)

Thread 4 (Thread 0x7fe3977fe700 (LWP 629701)):
#0  0x00007fe39c4d12a9 in pthread_cond_destroy@@GLIBC_2.3.2 () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x0000000003103ec2 in Poco::EventImpl::~EventImpl (this=0x7fe39b41f398)
#2  0x000000000326a631 in __release_shared (this=0x7fe39b41f380)
#3  __release_shared (this=0x7fe39b41f380)
#4  ~shared_ptr (this=<optimized out>)
#5  reset (this=0x7fe3977fc988)
#6  join (this=0x7fe3977fc988)
#7  Coordination::ZooKeeper::finalize (this=<optimized out>, error_send=false, error_receive=true)
#8  0x000000000326e02b in Coordination::ZooKeeper::receiveThread (this=<optimized out>)
#9  0x0000000003271fa4 in operator() (this=<optimized out>)
```

**Comment by alexey-milovidov** [comment]
We have discussed that this fix is an overkill that is too far from the root cause of this issue and we need to fix it in another way.

**Comment by alexey-milovidov** [comment]
We have failed to finish this PR.

**Pull request closed without merging**
