### PR TITLE
Fix Distributed queries finishing (avoid connection resets)

### PR DESCRIPTION
**Pull request by azat**
Changelog category (leave one):
- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Avoid unnecessary network errors for remote queries which may be cancelled while execution, like queries with `LIMIT`.

- Do not try to send query if it was already canceled
- Explicitly finish the remote query (in case of not all data was read, i.e. in case of LIMIT) to avoid connection resets
- Add a test that checks lack of NETWORK_ERROR in this case (since you will not get error for the query, because the state will be reseted too late, and it you can see it only in server logs)

Related failures of the 01247_optimize_distributed_group_by_sharding_key should be fixed by this patches:
- https://clickhouse-test-reports.s3.yandex.net/16996/0dfc18249d08ddea5bb1c9dd214b7101efdd181f/functional_stateless_tests_flaky_check_(address).html#fail1
- https://clickhouse-test-reports.s3.yandex.net/16993/d1f52dc72d417580c4088cf3880593176416bea2/functional_stateless_tests_(ubsan).html#fail1
- https://clickhouse-test-reports.s3.yandex.net/16853/185f886812639ea70f15529b096aafdc92e3efad/functional_stateless_tests_(thread).html#fail1

### CODE REVIEW

**Comment by azat** [comment]
@KochetovNicolai according to git blame you are the original author, can you please take a look?

**Review by KochetovNicolai — APPROVED** [review]
Looks like this pr fixes possible race on `RemoteQueryExecutor::was_cancelled`, which made possible `RemoteQueryExecutor::read` call happen after `RemoteQueryExecutor::cancel`. This could cause extra unnecessary network error.

**Comment by KochetovNicolai** [comment]
`Yandex third-party checks` was broken in master.
Ignore timeouts in ci.

**Comment by azat** [comment]
Hm, intersting, this does not fixes the 01247_optimize_distributed_group_by_sharding_key completely, [here](https://clickhouse-test-reports.s3.yandex.net/16845/48645eae33fad648b2f7295ccd7d4a3143d3608e/functional_stateless_tests_(release,_databaseordinary).html#fail1) it failed again, but `clickhouse-server.log` does not have relevant part of the log already (due to rotation)

I'll give it some thought

**Pull request merged**
