### PR TITLE
Fix function if with FixedString arguments of different sizes

### LINKED ISSUE #11362: Bad cast from type DB::IColumn* to DB::ColumnFixedString*.
```
/4/ :) SELECT if(number % 2, toFixedString(toString(number), 2), toFixedString(toString(-number), 65535)) FROM system.numbers LIMIT 10

Code: 368. DB::Exception: Received from localhost:9000. DB::Exception: Bad cast from type DB::IColumn* to DB::ColumnFixedString*. Stack trace:
```

### PR DESCRIPTION
**Pull request by alexey-milovidov**
Changelog category (leave one):
- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix wrong result and potential crash when invoking function `if` with arguments of type `FixedString` with different sizes. This fixes #11362.

### CODE REVIEW

**Comment by abyss7** [comment]
You forgot to fix old test: 00197_if_fixed_string

**Comment by alexey-milovidov** [comment]
@abyss7 The old test is perfectly correct but the code in this PR was wrong.

**Comment by alexey-milovidov** [comment]
> Performance

Not Ok.

**Comment by alexey-milovidov** [comment]
It is strange that I cannot reproduce performance regression on my today clang release build.

**Comment by alexey-milovidov** [comment]
> SELECT count() FROM test.hits WHERE NOT ignore(least(URL, Referer))

This test result is unrelated.

**Comment by alexey-milovidov** [comment]
> SELECT arraySlice(arrayFill(x -> ((x % 2) >= 2), range(100000000)), 1, 10) FORMAT Null

This neither.

**Comment by alexey-milovidov** [comment]
> SELECT count() FROM test.hits WHERE NOT ignore(rand() % 2 ? URL : Referer)

Function names in profiles are absolutely the same.

**Comment by alexey-milovidov** [comment]
@akuzm Performance test showed misleading result and delayed the fix for 5 days.

**Pull request merged**
