### PR TITLE
Remove useless setting experimental_query_deduplication_send_all_part_uuids

### PR DESCRIPTION
**Pull request by nvartolomei**
This setting made sense for testing deduplication before part movement was actually implemented.

allow_experimental_query_deduplication setting is enough and code is covered by test_part_moves_between_shards

Changelog category (leave one):

- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by nvartolomei** [comment]
cc @xjewer

**Comment by xjewer** [comment]
lgtm, since your part movement scenario covers query deduplication logic

**Review by novikd — APPROVED** [review]

**Comment by nvartolomei** [comment]
Failures seem unrelated.

**Comment by novikd** [comment]
@Mergifyio update

**Comment by novikd** [comment]
> Stress test (undefined, actions) — Server failed to start

Unrelated

**Pull request merged**
