### PR TITLE
Fix possible race on shutdown wait

### PR DESCRIPTION
**Pull request by serxa**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Review by evillique — APPROVED** [review]

**Review by alexey-milovidov — APPROVED** [review]
Is it the case when waiting for the shutdown was called concurrently? Why?

**Comment by tavplubix** [comment]
AFAIU there's no way to call it concurrently. I guess it's a race with `updateServers` called from `ConfigReloader` or other weird stuff, so it may indicate incorrect order of deinitialization

**Comment by alexey-milovidov** [comment]
But I don't see this mutex in updateServers.

**Comment by evillique** [comment]
We take this mutex before calling `updateServers()`:
https://github.com/ClickHouse/ClickHouse/blob/4e099086cdb17b005f5f857dc5079e66c6fc67a9/programs/server/Server.cpp#L1288-L1289

**Comment by tavplubix** [comment]
So, what was the race condition? Config reloader must be stopped before waiting for remaining connections:
https://github.com/ClickHouse/ClickHouse/blob/07191ce10d7f9e32e1f5a3ab3fbe6259f3a1a763/programs/server/Server.cpp#L1800-L1803

**Comment by serxa** [comment]
Well, there may be no race condition indeed. That's why it is called fix "possible" race condition. It just looked inconsistent to `servers` variable. It also relies on facts like config reloaded order. Tsan didn't found anything suspicious, it was just me reading the code

**Comment by serxa** [comment]
I mean race with `servers_to_start_before_tables`

**Pull request merged**
