### PR TITLE
fix toMinute function to handle special timezone

### PR DESCRIPTION
**Pull request by keen-wolf**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
fix toMinute function to handle special timezone correctly

Detailed description / Documentation draft:
As noticed in tests of [#PR:19962](https://github.com/ClickHouse/ClickHouse/pull/19962) , when meet special time zone such as 'Australia/Lord_Howe' whose DST offset isn’t whole hour aligned, the toDateTime or toString functions which will print the DateTime String incorrectly with the minutes part disordered. The cause is discovered through code analysis that when upper DateTime type related functions want to display datetime in String, they will call DB::DataTypeDateTime::serializeText who will finally call toMinute to generate the minutes part, but for uncovering the situations with non-whole hour aligned offset they will print the wrong string. This bug is fixed by take these special cases in account.

attached are call stacks, the simple test before and after this bugfix...
callstack
wrong
right

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]
LGTM

**Comment by alexey-milovidov** [comment]
@keen-wolf Let's continue?

**Comment by keen-wolf** [comment]
> @keen-wolf Let's continue?
Sorry for the late reply! Just came back from the holiday.

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
Ok.

Btw,

> ClickHouse build check Pending — 0/16 builds finished 

This check has hit GitHub "unicorn" page.

**Pull request merged**
