### PR TITLE
Fixed incorrect settings order.

### PR DESCRIPTION
**Pull request by nikitamikhaylov**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fixed incorrect settings order `max_parser_depth` and `max_parser_backtracks`. 

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Run only fuzzers related jobs (libFuzzer fuzzers, AST fuzzers, etc.)
- [ ]  Exclude: AST fuzzers
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-clickhouse-ci-1** [comment]
*This is an automated comment for commit cccf03d8f77ed6fe08cc1afe56fa7868bb228b28 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/71498/cccf03d8f77ed6fe08cc1afe56fa7868bb228b28/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/bdd18b35b29f6078b620c65a4f4d59853cfe5371/docs_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Review by yakov-olkhovskiy — APPROVED** [review]

**Comment by Algunenano** [comment]
We are not going to be able to merge this assert, since it's an ok definition -> https://s3.amazonaws.com/clickhouse-test-reports/71498/3f22f01e8abe27040c2bab5bbb5f41a2f16f5cc8/stateless_tests__debug__[2_2].html

OTOH it's already found a bug, so let's wait until everything runs to see if anything else pops up

**Comment by nikitamikhaylov** [comment]
@Algunenano I think we can modify the test and set `max_parser_depth` there to 1000001 instead of 1000000 and write a comment there. Since it is only for debug build, I think it does make sense and we should have more of such checks.

**Comment by Algunenano** [comment]
I changed the tests but I thought of a better way to support valid settings values. My main fear was that since these values are ok and can be changed by the client, we could be triggering this sanity check on valid runs of CI/test, fuzzers, etc and generate noise. I think  https://github.com/ClickHouse/ClickHouse/pull/71498/commits/3b44aa32e717e75c564c7bd3a41e8be2a1f2589a should handle that

**Comment by Algunenano** [comment]
It did not work for some reason (https://s3.amazonaws.com/clickhouse-test-reports/71498/3b44aa32e717e75c564c7bd3a41e8be2a1f2589a/stateless_tests__debug__[2_2].html)

**Comment by nikitamikhaylov** [comment]
Maybe we don't call `doSettingsSanityCheckClamp` in client?

**Pull request merged**
