### PR TITLE
fix: split lttb bucket strategy, first bucket and last bucket should only contain single point

### LINKED ISSUE #56762: The last two points of largestTriangleThreeBuckets (lttb) have a large x-axis gap
ClickHouse version:
23.10.3.5

https://fiddle.clickhouse.com/9f7212b8-f033-4bae-aa0e-439d939782b6

```sql
CREATE TABLE lttb_test
(
    x UInt32,
    y UInt32
) ENGINE = MergeTree ORDER BY x;

INSERT INTO lttb_test (x, y) SELECT (number + 1) AS x, (x % 1000) AS y FROM numbers(9999);

SELECT 
  arrayJoin(lttb(1000)(x, y)) AS point, 
  tupleElement(point, 1) AS point_x, 
  point_x - neighbor(point_x, -1) AS point_x_diff_with_previous_row 
FROM lttb_test LIMIT 990, 10;
```

Result:
```sql
┌─point──────┬─point_x─┬─point_x_diff_with_previous_row─┐
│ (8911,911) │    8911 │                              9 │
│ (8920,920) │    8920 │                              9 │
│ (8929,929) │    8929 │                              9 │
│ (8938,938) │    8938 │                              9 │
│ (8947,947) │    8947 │                              9 │
│ (8956,956) │    8956 │                              9 │
│ (8965,965) │    8965 │                              9 │
│ (8974,974) │    8974 │                              9 │
│ (8991,991) │    8991 │                             17 │
│ (9999,999) │    9999 │                           1008 │ <-- The last two points have a large x-axis gap
└────────────┴─────────┴────────────────────────────────┘

```
Plotting a line graph using X and Y of lttb yields the following results. Maybe we can make the x-axis sampling a little more even.
image

### PR DESCRIPTION
**Pull request by wxybear**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
modify the bucket strategy of lttb function, first bucket only contain first point, last bucket only contain last point, other bucket size is (point_size - 2) / (bucket_num - 2)

Fixes #56762 
The old strategy splits n buckets of the same size, but ignores the the points in the front and back buckets(only the first or last one is used instead)

### CODE REVIEW

**Comment by robot-clickhouse-ci-1** [comment]
*This is an automated comment for commit 2547ea84e547e901330cc80261bb4da408f06462 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/57003/2547ea84e547e901330cc80261bb4da408f06462/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td><a href="https://github.com/ClickHouse/ClickHouse/actions/runs/6933197589">✅ success</a></td></tr>
<tbody>
</table>
</details>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/57003/2547ea84e547e901330cc80261bb4da408f06462/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Comment by wxybear** [comment]
this is just an initial PR to deal with this issue. I will refine code, verify and add tests this week, it may be a little slower :)

**Comment by wxybear** [comment]
hi @nickitat , please review this change

**Comment by nickitat** [comment]
could you pls add this test case: https://github.com/ClickHouse/ClickHouse/issues/56762#issue-1993225684

**Review by nickitat — APPROVED** [review]
pls fix the test

**Review by nickitat — APPROVED** [review]

**Pull request merged**
