### PR TITLE
Fix optimize_distributed_group_by_sharding_key for query with OFFSET only

### PR DESCRIPTION
**Pull request by azat**
Changelog category (leave one):
- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
- Fix optimize_distributed_group_by_sharding_key for query with OFFSET only

### CODE REVIEW

**Comment by azat** [comment]
>Functional stateless tests flaky check (address) — fail: 1, passed: 119

Should be fixed with #17006

**Comment by azat** [comment]
Can someone set force test label please?

**Comment by azat** [comment]
Rebased against upstream/master to fix tests

**Comment by azat** [comment]
@abyss7 should I take care and do rebase against upstream/master? Or you did not looked yet?

**Review by abyss7 — APPROVED** [review]
That's my bad, that I hadn't mark it as approved earlier.

**Comment by abyss7** [comment]
> @abyss7 should I take care and do rebase against upstream/master? Or you did not looked yet?

You should rebase and if everything is ok, I will merge.

**Comment by azat** [comment]
>You should rebase and if everything is ok, I will merge.

Ok, thanks, rebased

**Comment by azat** [comment]
>ClickHouse build check — 14/15 builds are OK

```
Unable to find image 'yandex/clickhouse-deb-builder:latest' locally
docker: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit.
```

**Pull request merged**
