### PR TITLE
Support type `Object` inside `JSON*` functions 

### LINKED ISSUE #37302: JSON type usability
case 1:

```sql
SET allow_experimental_object_type = 1;

CREATE TABLE test
(
    `json` Object('JSON'),
    `id` String MATERIALIZED json.id
)
ENGINE = MergeTree
ORDER BY tuple()

Query id: 75ede050-5296-49a3-8239-88ae76c72017


0 rows in set. Elapsed: 0.000 sec. 

Received exception:
Code: 47. DB::Exception: Missing columns: 'json.id' while processing query: '_CAST(json.id AS id_tmp_alter7102224081829085004, 'String') AS id, id_tmp_alter7102224081829085004', required columns: 'json.id' 'json.id': default expression and column type are incompatible. (UNKNOWN_IDENTIFIER)
```

case 2:

```sql
SET allow_experimental_object_type = 1;
CREATE TABLE test(  `json` Object('JSON') ) ENGINE = MergeTree ORDER BY tuple();

CREATE MATERIALIZED VIEW test2 engine=MergeTree ORDER BY tuple() AS SELECT json.id, json FROM test;

# Code: 47. DB::Exception: Missing columns: 'json.id' while processing query: 'SELECT json.id, json FROM _local.test', required columns: 'json.id' 'json', maybe you meant: ['json']. (UNKNOWN_IDENTIFIER), Stack trace (when copying this message, always include the lines below):
```

case 3: 

```sql
SET allow_experimental_object_type = 1;
CREATE TABLE test(  `json` Object('JSON') ) ENGINE = Null ORDER BY tuple();

Received exception:
Code: 44. DB::Exception: Cannot create table with column of type Object, because storage Null doesn't support dynamic subcolumns. (ILLEGAL_COLUMN), Stack trace (when copying this message, always include the lines below):
```

### PR DESCRIPTION
**Pull request by CurtizJ**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Support columns of type `Object` inside `JSON*` functions.

Resolves #37302.

### CODE REVIEW

**Comment by CurtizJ** [comment]
Logical error in fuzzer doesn't reproduce now:

```
SELECT JSONExtract('\0', 'LowCardinality(String)')
GROUP BY
    GROUPING SETS (
        (JSONExtractRaw(NULL, '1025')),
        (JSONExtract(CAST('{"a": "hello", "b": [-100, 200.0, 300]}', 'Object(\'json\')'), NULL, JSONExtractRaw(NULL, '-0.01'), 'LowCardinality(String)')),
        (CAST('{"a": "hello", "b": [-100, 200.0, 300]}', 'Object(\'json\')')),
        (JSONExtract('', 'LowCardinality(String)')))

Query id: aa94ef45-38be-49ea-bd9d-d703733b5008


0 rows in set. Elapsed: 0.004 sec. 

Received exception from server (version 22.11.1):
Code: 48. DB::Exception: Received from localhost:9000. DB::Exception: ColumnObject must be converted to ColumnTuple before use: While executing AggregatingTransform. (NOT_IMPLEMENTED)
```

`NOT_IMPLEMENTED` is thrown, because of aggregation by column of type `Object`, which is ok for now.

**Comment by Avogar** [comment]
Is it ready for review or require some work? I am asking because it's still a draft but there were no changes quite a long time

**Comment by CurtizJ** [comment]
This task is on hold currently. I want to make `Object` type to have `Nullable` subcolumns by default and add support of `Nullable` result in `JSON*` functions. Otherwise the result of these functions may be unexpected for users.

**Comment by alexey-milovidov** [comment]
As we are going to rewrite the Object type, this PR is no longer relevant.

**Pull request closed without merging**
