### PR TITLE
Default input and output formats that can be overriden by --input-format and --output-format.

### LINKED ISSUE #30631: Option `--format` for `clickhouse-local` should set both input and output formats.
`clickhouse-local` can take three options: `--input-format`, `--output-format` and `--format`.
Currently the `--format` option only sets the output format.

Let's make it set default input and output formats that can be overriden by `--input-format` and `--output-format`.

### PR DESCRIPTION
**Pull request by taiyang-li**
Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Default input and output formats that can be overriden by --input-format and --output-format. Close https://github.com/ClickHouse/ClickHouse/issues/30631

### CODE REVIEW

**Comment by taiyang-li** [comment]
@alexey-milovidov  formats in clickhouse-local is quite a mess, I don't known what you expected in issue: https://github.com/ClickHouse/ClickHouse/issues/30631.  Pls reply me if any other changes is needed.

**Comment by Avogar** [comment]
Your changes are enought. But also need to add a test for it. You can see exaples of tests in directory `tests/queries/0_stateless/` (you can grep by `CLICKHOUSE_LOCAL` to see tests on clickhouse-local)

**Comment by taiyang-li** [comment]
> 

Ok, I will try

**Comment by taiyang-li** [comment]
done

**Comment by taiyang-li** [comment]
Failed tests not related to this pr .

**Review by Avogar — APPROVED** [review]

**Pull request merged**
