### PR TITLE
Add functions fileExists and fileInc

### PR DESCRIPTION
**Pull request by decaseal**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- New Feature

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Add functions fileExists and fileInc

- fileExists(x) - returns 1 if and only if a file or directory exists.
- fileInc(x) - read integer from file, increment it and write it down. Create file with '0' if it doesn't exist. Returns incremented integer.

### CODE REVIEW

**Comment by decaseal** [comment]
Sorry for these mistakes, but I'm not a C++ developer and I have no errors during build on my machine. 

How can i fix error:
`reference to stack memory associated with local variable 'argument_types' returned`

In the function:
```c++
const DataTypes & getArgumentTypes() const override
{
    DataTypes argument_types(1);
    argument_types[0] = std::make_shared<DataTypeString>();

    return argument_types;
}
```
?

**Comment by alexey-milovidov** [comment]
`argument_types` is temporary variable, when control flow exit from function, it is destroyed, and the returning reference becomes automatically invalid.

**Comment by Slach** [comment]
@decaseal  maybe `fileIncrement` instead of `fileInc` (i read it as file include) will more mental name?

**Comment by decaseal** [comment]
Decided to refuse to add these functions

**Pull request closed without merging**
