### PR TITLE
Fix UB.

### PR DESCRIPTION
**Pull request by amosbird**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Category (leave one):
- Bug Fix

Short description (up to few sentences):

Fix UB in StorageMerge.

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
What is the mechanics of this change?
Why we can capture references in LazyBlockInputStream?

**Comment by amosbird** [comment]
> Why we can capture references in LazyBlockInputStream?

I assume you mean why we can't?

Because those references will be invalid upon the first read attempt of the  `LazyBlockInputStream` .

**Comment by alexey-milovidov** [comment]
Ok.

**Comment by alexey-milovidov** [comment]
Do you have a test case that fails under ASan or UBSan?

**Pull request merged**
