### PR TITLE
Add support of dates from year 1900 to 2299 for Date32 and DateTime64

### LINKED ISSUE #28216: Extend range of Datetime64 and Date32
Not long ago, I submitted a pull request for Date32（https://github.com/ClickHouse/ClickHouse/pull/25774）, in order to solve the problem of too small date range, but for some banking systems, there are still data dates before 1925. I want to extend the existing date range, for example to 1900.

I want to know if this approach can be accepted by the community.

### PR DESCRIPTION
**Pull request by rvasin**
### Changelog category (leave one):
- Backwards Incompatible Change

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Extended range of Date32 and DateTime64 to support dates from the year 1900 to 2299. In previous versions, the supported interval was only from the year 1925 to 2283. The implementation is using the proleptic Gregorian calendar (which is conformant with [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601):2004 (clause 3.2.1 The Gregorian calendar)) instead of accounting for historical transitions from the Julian to the Gregorian calendar. This change affects implementation-specific behavior for out-of-range arguments. E.g. if in previous versions the value of `1899-01-01` was clamped to `1925-01-01`, in the new version it will be clamped to `1900-01-01`. It changes the behavior of rounding with `toStartOfInterval` if you pass `INTERVAL 3 QUARTER` up to one quarter because the intervals are counted from an implementation-specific point of time. Closes #28216, improves #38393.

### CODE REVIEW

**Comment by qoega** [comment]
Backwards incompatible change? Can you change behavior based on server setting?

**Comment by rvasin** [comment]
> Backwards incompatible change? Can you change behavior based on server setting?

This is no options on server settings to change range back to 1925 ... 2283 because I removed the mask as explained for variant 2 in the issue #38393

**Comment by rvasin** [comment]
While technically it's possible to implement an option like support_old_ext_range to support old (current) range 1925..2283 in current approach (without using the mask). But this will add many check conditions and it will complicate the things.

**Comment by rvasin** [comment]
Could someone please assign a label to PR? So I could see the results of CI tests.

**Comment by alexey-milovidov** [comment]
@qoega 

> Backwards incompatible change? Can you change behavior based on server setting?

I'm afraid it's not possible.

As we simply make the range wider, while it can lead to some incompatibilities, but only in some unusual scenarios, where the code relied on implementation-defined clamping or wraparound.

**Comment by alexey-milovidov** [comment]
@rvasin the tests need to be updated: https://s3.amazonaws.com/clickhouse-test-reports/39425/0b102c6d1ffeeeae79c3f50a522288367a567a46/fast_test__actions_.html

**Comment by rvasin** [comment]
> @rvasin the tests need to be updated: https://s3.amazonaws.com/clickhouse-test-reports/39425/0b102c6d1ffeeeae79c3f50a522288367a567a46/fast_test__actions_.html
Yes, I know. I am working on the tests right now.

**Comment by rvasin** [comment]
@alexey-milovidov Could you please comment on results of Performance Comparison tests? 

What I see there is no slowdown in tests related to date/time functions.

In fact: Performance Comparison [3/4]  
`SELECT * FROM hits_100m_single WHERE CounterID IN (152220, 168777, 149234, 149234) ORDER BY CounterID DESC, EventDate DESC LIMIT 100`
It's even -1.117x faster in implementation of current PR.
But I could not find other date/time related tests with huge faster/slower rates.

**Comment by ilejn** [comment]
To me, 
degradation of queries like 'SELECT count() FROM numbers(50000000) WHERE NOT ignore(toDate('2017-01-01') + number % 1000 + rand() % 10 AS t, toRelativeDayNum(t))' from
https://s3.amazonaws.com/clickhouse-test-reports/39425/ac2a42cfb0f68252d0fb2fcf8b17ec70949c5566/performance_comparison_[4/4]/report.html 
is meaningful and must be investigated further.

**Comment by rvasin** [comment]
@ilejn for this query taken from the performance test:

`SELECT count() FROM numbers(50000000) WHERE NOT ignore(toDate('2017-01-01') + number % 1000 + rand() % 10 AS t, toRelativeDayNum(t))`

I built CH in release mode PR version and version from master (from which PR branch was started).
The build machine is 52 core Ubuntu server running on Yandex Cloud.
I did:
1. start CH
2. start CH client
3. in CH client execute the query above 6 times.
4. close CH client
5. stop CH server.
So I repeated it about 3 times for PR version of CH and for master version of CH. The results (query run time in seconds) are in the table:

PR version | Master version
-- | --
0.413 | 0.150
0.412 | 0.152
0.410 | 0.221
0.179 | 0.179
0.147 | 0.145
0.146 | 0.148

You see that PR version first time query run is about 0.4 seconds and then it goes to 0.14 and all further runs it's executed 0.14 seconds. 

For master version it the first run is usually 0.15 or 0.22 and then it also goes to 0.14 for all future runs.
I don't know how to explain it. As I said: I closed CH server, started it again. And the results are about the same as displayed on the table. And in "log run" any variant runs the query in about 0.14 secs. 
I think the performance test "fetches" this behavior. It's like it "considers" the master version runs it in 0.22 and  PR version runs it in 0.4. Hence it has 80% slowdown. 
Maybe the test should run the query about 20 times. In this case the average query run time will be about 0.14 or 0.15 for each of variants.
I did not look in the details of the performance test yet. I will explore it in details later on.

**Comment by ilejn** [comment]
Thanks @rvasin , very interesting.
Looks like the investigation can be not as simple and comfortable as I thought, but it is required anyway.
We see serious degradation in some circumstances, and the same can be experienced by CH users in real life.

I do not have a consistent explanation but the first things comes to my mind is LUT is now larger than L2 cache.
May be someone else have a better guess.

Could you by the way disable JIT and rerun the test https://clickhouse.com/docs/en/operations/settings/settings/#compile-expressions ?

**Comment by alexey-milovidov** [comment]
@ilejn for real queries it does not matter how big is LUT, only the size of the actively used part of it matters.

**Comment by alexey-milovidov** [comment]
We can check query metrics of the individual queries, there is the possibility to enable CPU hardware counters:
- add CAP_SYS_ADMIN for clickhouse binary;
- enable `metrics_perf_events_enabled` setting.

Also, performance test can give pictures with automatically generated comparisons for the most changed metrics, but I forgot how to get them.

**Comment by alexey-milovidov** [comment]
How do the observations change if you pin clickhouse-server to a single CPU core?

**Comment by rvasin** [comment]
@alexey-milovidov I am on vacation from 1st to 7th August. I also don't think that it's related to L2 cache. I discussed with @ilejn which "plan of actions" could be to find out the performance degradation. So after my return from vacation on 8th August I will try single-core, enable metrics and other recommendations.

**Comment by alexey-milovidov** [comment]
Interesting stuff: https://github.com/dotnet/runtime/pull/72712/files
Note: at first glance, it is applicable only for dates, not datetimes, and a lookup table is better.

**Comment by rvasin** [comment]
@alexey-milovidov and @ilejn I found the reason of performance degradation of some tests. It's not related at all to L2 cache or new LUT size.

In fact in this PR I implemented two things:
1. Extended LUT range to 1900..2299 by removing the mask usage. 
2. Improved AddDays/SubtructDays and AddWeeks/SubtructWeeks near boundaries.

The performance degradation is related only to the second improvement. If I revert back the  AddDays/SubtructDays logic then the first improvement (extended range) work the same speed as the master.

So what should I do? Maybe trim the second improvement from current PR and implement it as a separate PR? 
In fact I already improved the performance in the latest commit. 

In previous commit if I run in PR version the query used in the performance test with

`SELECT count() FROM numbers(5000000000) WHERE NOT ignore(toDate('2017-01-01') + number % 1000 + rand() % 10 AS t, toRelativeDayNum(t))`

I added 2 zeros for numbers() to run it longer.
First run: 34.4 secs, second run 34.4 secs, third run 34 secs, 4th run 11.7 seconds, 5th run and so on: 11.7 secs.

If I run the query from master branch the run time:
First run: 12.4 secs, second run 12.4 secs, third run 12 secs, 4th run 11.7 seconds, 5th run and so on: 11.7 secs.

In fact in this query we add numbers to Date:
toDate('2017-01-01') + number % 1000 + rand() % 10

In master branch we have:
src/Functions/FunctionDateOrDateTimeAddInterval.h
```
struct AddDaysImpl:
//...
    static inline NO_SANITIZE_UNDEFINED UInt16 execute(UInt16 d, Int64 delta, const DateLUTImpl &, UInt16 = 0)
    {
        return d + delta;
    }
```

There is no range check. For example in master:

`SELECT toDate('1970-01-01') - 2`

```
┌─minus(toDate('1970-01-01'), 2)─┐
│                     2149-06-05 │
└────────────────────────────────┘
```
While it should return 1970-01-01. So I corrected it by adding the function:
```
static UInt16 normalizeDayNum(Int64 d)
{
    if (d < 0)
        return 0;
    if (d > 65535)
        return 65535;
    return static_cast<UInt16>(d);
}

```
and in the previous commit it was called  this way:

```
struct AddDaysImpl:
//...
    static inline NO_SANITIZE_UNDEFINED UInt16 execute(UInt16 d, Int64 delta, const DateLUTImpl &, UInt16 = 0)
    {
        return DateLUT::instance().normalizeDayNum(d + delta);
    }
```

Calling as DateLUT::instance() was the reason of slow down. If I put back: 
`return d + delta;`
then in PR branch with extended date it also works the same speed 12.4 secs as in master branch.

I tried to find the fastest way to clamp/limit range of d + delta to 0..65535
There is the interesting [discussion](https://codereview.stackexchange.com/questions/6502/fastest-way-to-clamp-an-integer-to-the-range-0-255).

I tried the using the mask this way:
`return (d + delta) & 0xffff;`
Speed it the the same 12.5 secs as in master. The usage of the mask was also suggested in the discussion but as Also mentioned - the mask protect the upper limit but it does not protect from lower limit (negative numbers). 

Then I used clamp functions from std and boost and also the branching methods. I put methods here:

```
// return static_cast<UInt16>(std::clamp(d + delta, 0L, 65535L));

// return static_cast<UInt16>(boost::algorithm::clamp(d + delta, 0L, 65535L));

/*
Int64 r = d + delta;
if (unlikely(r < 0))
    return 0;
if (unlikely(r > 65535))
    return 65535;
return static_cast<UInt16>(r);
*/

/*
Int64 r = d + delta;
if (unlikely(r < 0)) r = 0;
if (unlikely(r > 65535)) r = 65535;
return static_cast<UInt16>(r);
*/

/*
Int64 r = d + delta;
r = r > 65535 ? 65535 : r;
return r < 0 ? 0 : r;
*/
```
Surprisingly but all these methods give about the same performance:
 
First run: 14.8 secs, second run 14.8  secs, third run 14.0 secs, 4th run 11.7 seconds, 5th run and so on: 11.7 secs.
So using if (unlikely()) is not faster than using std::clamp(). 

Thus in the latest commit I decided to use std::clamp().
Please checkout the current performance tests fro [example](https://s3.amazonaws.com/clickhouse-test-reports/39425/96598e35743aa83e3ac31cc4776190543671f1d1/performance_comparison_aarch64_[3/4]/report.html)  for date_time_short test there is about 17% slow down. 
In fact if we compare the first runs: 
(14.8-12.4)*100/12.4 = 19%  
But 4th and all next runs gives the same 11.7 secs for any variant. And again this is only for tests with addDays/Weeks, subtructDays/Weeks. All LUT index arithmetic is about the same speed.  

Also note: if we consider the current implementation of struct AddHoursImpl:
```
    static inline NO_SANITIZE_UNDEFINED UInt32 execute(UInt32 t, Int64 delta, const DateLUTImpl &, UInt16 = 0)
    {
        return t + delta * 3600;
    }
```
There is still no limiting of range. The same is true for AddMinutesImpl, AddSecondsImpl. Should the limiting of range to 0..65535 be used to these structs too?

Second note: 
Some execute() methods of struct AddDaysImpl and AddWeeksImpl call for example:
```
    static inline NO_SANITIZE_UNDEFINED UInt32 execute(UInt32 t, Int64 delta, const DateLUTImpl & time_zone, UInt16 = 0)
    {
        return time_zone.addDays(t, delta);
    }
```
The limiting to 0..65 is done there in time_zone.addDays by calling findIndex() which does about the same thing:
```
   inline LUTIndex findIndex(Time t) const
    {
      // .... skip ...

        if (guess < 0)
            return LUTIndex(0);
        if (guess >= DATE_LUT_SIZE)
            return LUTIndex(DATE_LUT_SIZE - 1);
```
So there is already some kind of "performance degradation" taken into account by using the branching logic inside findIndex(). It's only when execute() is called without time_zone parameter the master branch uses `return d + delta;`

Please advice what should do in current situation:
1. In AddDaysImpl revert back to `return d + delta;` As result in current PR we will benefit from having the extended range 1900..2299 at the same speed as in master.
2. or we keep using std:clamp of similar in AddDaysImpl and others AddPERIODImpl to limit the range and as the result we have the performance degradation of about 18%.

**Comment by ilejn** [comment]
I've tried to benchmark normalizeDayNum via quickbench https://quick-bench.com/q/gSrrRikIlfAo4S2Nb9EzrqLWqKE . Totally pointless: there is no difference. But funny.
Still don't understand the performance difference between runs, branch predictor hardly can work in such way.

**Comment by alexey-milovidov** [comment]
Let's remove clamping and merge this PR.

**Comment by rvasin** [comment]
@alexey-milovidov In the latest commit I removed the clamping and corrected one functional test. 
I see on the performance tests there is no slowdown of date/time related functions/queries. There is even a small speedup like:
[datetime_comparison](https://s3.amazonaws.com/clickhouse-test-reports/39425/537ba613dcc5c2f23f5763f894dcbe2b9823d32d/performance_comparison_[1/4]/report.html)  -1.023x

and

[date_time_64](https://s3.amazonaws.com/clickhouse-test-reports/39425/537ba613dcc5c2f23f5763f894dcbe2b9823d32d/performance_comparison_aarch64_[1/4]/report.html) -1.108x 

and



[order_by_read_in_order](https://s3.amazonaws.com/clickhouse-test-reports/39425/537ba613dcc5c2f23f5763f894dcbe2b9823d32d/performance_comparison_aarch64_[3/4]/report.html)
SELECT * FROM hits_100m_single ORDER BY (CounterID, EventDate) LIMIT 100
Relative difference  -0.135

**Comment by rvasin** [comment]
> I've tried to benchmark normalizeDayNum via quickbench https://quick-bench.com/q/gSrrRikIlfAo4S2Nb9EzrqLWqKE . Totally pointless: there is no difference. But funny. Still don't understand the performance difference between runs, branch predictor hardly can work in such way.

@ilejn  Using the same web site I created performance test: branch vs clamp. The results are equivalent. See the test https://quick-bench.com/q/Frk4eSwmdj7wi9EazQP5ePtUlJ4

**Comment by den-crane** [comment]
>4th run 11.7 seconds, 5th run and so on: 11.7 secs.

Are you aware about JIT compiler?

```sql
select name , value from system.settings where name like '%comp%exp%';
┌─name──────────────────────────────────────┬─value─┐
│ compile_expressions                       │ 1     │
│ min_count_to_compile_expression           │ 3     │
│ compile_aggregate_expressions             │ 1     │
│ min_count_to_compile_aggregate_expression │ 3     │
└───────────────────────────────────────────┴───────┘
```

Just try 

```
set compile_expressions=0;
or
set compile_expressions=1, min_count_to_compile_expression=1;
```

it compiles this math I guess ` + (number % 1000)) + (rand() % 10)`
```

**Comment by alexey-milovidov** [comment]
I've edited the changelog.

**Comment by alexey-milovidov** [comment]
@rvasin Please check if my changelog entry is correct.

**Comment by rvasin** [comment]
> @rvasin Please check if my changelog entry is correct.

@alexey-milovidov I confirm your changelog entry is correct. Thank you for updating it.

**Comment by rvasin** [comment]
> > 4th run 11.7 seconds, 5th run and so on: 11.7 secs.
> 
> Are you aware about JIT compiler? It starts to work after `min_count_to_compile_expression=3`
@den-crane  I know about JIT but I did not know about `min_count_to_compile_expression=3` .  Thank you for noticing it. Probably that is what causes such behavior in sequential runs of the same query. 

I remember several days ago @ilejn also suggested  to  set compile_expressions=0
And I did it (without adding two additional zeros to the query which provides more 'stability') so I noticed the difference in execution time. But I could not evaluate it because I switched to something else in development. 

So I will try different combinations  set compile_expressions=0 or 
compile_expressions=1 and min_count_to_compile_expression=1

**Comment by loyd** [comment]
In CH 22.10.2.11:
```
CREATE TABLE test (date Date32) ENGINE = MergeTree ORDER BY date;

INSERT INTO test_time__date32.test(date) VALUES ('1900-01-02'), ('1969-01-01'), ('1970-01-01'), ('2000-01-01')

SELECT
    date,
    toString(date),
    toInt32(date)
FROM test;

Query id: 1553ccf1-1071-4648-923e-4a2d0b953b82

┌───────date─┬─toString(date)─┬─toInt32(date)─┐
│ 1925-01-01 │ 1925-01-01     │        -16436 │
│ 1969-01-01 │ 1969-01-01     │          -365 │
│ 1970-01-01 │ 1970-01-01     │             0 │
│ 2000-01-01 │ 2000-01-01     │         10957 │
└────────────┴────────────────┴───────────────┘
```

In docs: `Stored in four bytes as the number of days since 1925-01-01` before PR and `Stored in four bytes as the number of days since 1900-01-01`. But actually, it's stored as the number of days since `1970` in both cases, innit?

It's important to note because it affects Native/RowBinary formats.

**Comment by alexey-milovidov** [comment]
@loyd Yes, the documentation is incorrect.

Should be: Stored as a signed 32-bit integer in native byte order with the value representing the days since 1970-01-01 (0 represents 1970-01-01 and negative values represent the days before 1970).

**Comment by loyd** [comment]
@alexey-milovidov 

Stored in `native`, ok. But does it convert to LE while sending using Native/RowBinary formats? Because now, I rely on LE encoding in RowBinary deserialization in my CH client library. Should I somehow (how?) detect the server's byte order and use another deserializer for it?

**Comment by alexey-milovidov** [comment]
ClickHouse does not currently support any big-endian architectures,
the way how it will work for big-endian is undecided.

**Pull request merged**
