### PR TITLE
Fix parsing booleans in settings

### PR DESCRIPTION
**Pull request by vitlibar**
### Changelog category:
- Improvement

### Changelog entry:
Distinguish booleans and integers while parsing values for custom settings:
```
SET custom_a = true;
SET custom_b = 1;
```

Also this PR fixes a logical error in debug mode when `BACKUP ... ASYNC` is used, for example:
```
Logical error: 'Inconsistent AST formatting: the query:
BACKUP TABLE tbl TO Disk('backups', '03032_async_backup_restore_test_ih29tdhx') SETTINGS async = true
Was parsed and formatted back as:
BACKUP TABLE tbl TO Disk('backups', '03032_async_backup_restore_test_ih29tdhx') SETTINGS async = 1'
```

### CODE REVIEW

**Comment by robot-ch-test-poll1** [comment]
*This is an automated comment for commit ba5064291466d7a21a960604d742a3e956f225c2 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/62206/ba5064291466d7a21a960604d742a3e956f225c2/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

**Comment by yakov-olkhovskiy** [comment]
while it seems to be a proper fix, I think it still should be implicitly convertible - according to tests we rely on this a lot...

**Comment by vitlibar** [comment]
All the test failures seem unrelated:
- [00014_filtering_arrays](https://s3.amazonaws.com/clickhouse-test-reports/62206/ade0a311cf25869f84adddb8739491095b91ea89/stateful_tests__msan_.html) - see [issue 62258](https://github.com/ClickHouse/ClickHouse/issues/62258)
- [00062_loyalty](https://s3.amazonaws.com/clickhouse-test-reports/62206/ade0a311cf25869f84adddb8739491095b91ea89/stateful_tests__msan__parallelreplicas_.html) - see [issue 62252](https://github.com/ClickHouse/ClickHouse/issues/62252)
- [AST fuzzer (asan): Logical error: 'numbers_storage.step != UInt64{0}'](https://s3.amazonaws.com/clickhouse-test-reports/62206/ade0a311cf25869f84adddb8739491095b91ea89/ast_fuzzer__asan_.html) - see [issue 62413](https://github.com/ClickHouse/ClickHouse/pull/62413)

**Comment by vitlibar** [comment]
> while it seems to be a proper fix, I think it still should be implicitly convertible - according to tests we rely on this a lot...

done!

**Comment by vitlibar** [comment]
@yakov-olkhovskiy please take a look

**Review by yakov-olkhovskiy — APPROVED** [review]

**Pull request merged**
