### PR TITLE
Fixed test failures when running clickhouse-server on different host

### PR DESCRIPTION
**Pull request by Enmk**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Category (leave one):
- Build/Testing/Packaging Improvement

Short description (up to few sentences):
Further improvement of the docker-based test machinery
...

Detailed description (optional):
### test_runner.sh
* Multi-stage builds for test-runner and server to allow putting packages directory anywhere
* Option to skip re-building docker images (useful for testing along with mounting local test-files to the test-runner container)
### Fixed Test:
* Tests that were connecting to localhost rather than to CLICKHOUSE_HOST

    * 00354_host_command_line_option
    * 00646_url_engine
* Tests that were not ensuring that certain option is set:
   
    * 00838_unique_index
    * 00838_minmax_index

* Tests that were trying to write extra data to the readonly directory rather than to CLICKHOUSE_TMP:

    * 00634_performance_introspection_and_logging
    * 00634_logging_shard
### Clickhouse-test
* Fixed clickhouse-test error reporting when diff contains non-ascii characters
* more detailed error reporting for internal errors
...

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
Need to fix up "00646_url_engine" test.

**Comment by alexey-milovidov** [comment]
Still waiting for test fix.

**Review by alexey-milovidov — CHANGES_REQUESTED** [review]
.

**Comment by Enmk** [comment]
> .

Sorry for delay, it should be fixed now.

**Pull request merged**
