### PR TITLE
Use part splitter to optimize aggregation in order

### PR DESCRIPTION
**Pull request by CurtizJ**
### Changelog category (leave one):
- Performance Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Optimized aggregation in order of primary key (setting `optimize_aggregation_in_order`) for non-intersecting ranges of data parts.

### Details:
The idea and the implementation is taken from #58120.

### CODE REVIEW

**Comment by robot-clickhouse** [comment]
*This is an automated comment for commit 5b6c2fd056ab12feeee57fe7509c573528ab9dd2 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/58442/5b6c2fd056ab12feeee57fe7509c573528ab9dd2/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/58442/5b6c2fd056ab12feeee57fe7509c573528ab9dd2/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Comment by CurtizJ** [comment]
Some synthetic test:
```sql
CREATE TABLE test_table (id UInt64, value String) ENGINE=MergeTree ORDER BY id SETTINGS index_granularity = 8192;
INSERT INTO test_table SELECT number, number FROM numbers(50000000);
OPTIMIZE TABLE test_table FINAL;
```

This PR without `optimize_aggregation_in_order`:
 
```
clickhouse benchmark <<< "SELECT id, min(value) FROM test_table GROUP BY id FORMAT Null" --cumulative --optimize_aggregation_in_order 0
```

```
Queries executed: 10.

localhost:9000, queries: 10, QPS: 0.745, RPS: 37261075.388, MiB/s: 880.477, result RPS: 0.000, result MiB/s: 0.000.

0.000%          1.169 sec.
10.000%         1.184 sec.
20.000%         1.190 sec.
30.000%         1.193 sec.
40.000%         1.201 sec.
50.000%         1.203 sec.
60.000%         1.203 sec.
70.000%         1.211 sec.
80.000%         1.218 sec.
90.000%         1.275 sec.
95.000%         1.312 sec.
99.000%         1.312 sec.
99.900%         1.312 sec.
99.990%         1.312 sec.
```

This PR with `optimize_aggregation_in_order`:
 
```
clickhouse benchmark <<< "SELECT id, min(value) FROM test_table GROUP BY id FORMAT Null" --cumulative --optimize_aggregation_in_order 1
```

```
Queries executed: 12.

localhost:9000, queries: 12, QPS: 1.908, RPS: 95393858.115, MiB/s: 2254.150, result RPS: 0.000, result MiB/s: 0.000.

0.000%          0.446 sec.
10.000%         0.457 sec.
20.000%         0.472 sec.
30.000%         0.481 sec.
40.000%         0.484 sec.
50.000%         0.498 sec.
60.000%         0.501 sec.
70.000%         0.503 sec.
80.000%         0.506 sec.
90.000%         0.507 sec.
95.000%         0.507 sec.
99.000%         0.517 sec.
99.900%         0.517 sec.
99.990%         0.517 sec.
```

Master with `optimize_aggregation_in_order`:
```
clickhouse benchmark <<< "SELECT id, min(value) FROM test_table GROUP BY id FORMAT Null" --cumulative --optimize_aggregation_in_order 1
```

```
Queries executed: 4.

localhost:9000, queries: 4, QPS: 0.146, RPS: 7320479.881, MiB/s: 172.982, result RPS: 0.000, result MiB/s: 0.000.

0.000%          5.688 sec.
10.000%         5.688 sec.
20.000%         5.781 sec.
30.000%         5.781 sec.
40.000%         5.781 sec.
50.000%         5.802 sec.
60.000%         5.802 sec.
70.000%         5.802 sec.
80.000%         5.802 sec.
90.000%         5.927 sec.
95.000%         5.927 sec.
99.000%         5.927 sec.
99.900%         5.927 sec.
99.990%         5.927 sec.
```

**Comment by CurtizJ** [comment]
Now we can implement specializations in `AggregatingInOrderTransform` and probably get about x2 speedup more.

**Comment by UnamedRus** [comment]
Memory usage for both `optimize_aggregation_in_order=1` and `optimize_aggregation_in_order=0`, probably even more interesting than query time.

**Pull request closed without merging**
