### PR TITLE
Fix typo in variable name use_leagcy_max_level

### PR DESCRIPTION
**Pull request by wiledusc**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fixed typo: from `use_leagcy_max_level` to `use_legacy_max_level`

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by robot-clickhouse** [comment]
*This is an automated comment for commit 4f30ac72a1ef01f7c783c192639933e32d2f0397 with description of existing statuses. It's updated for the latest CI running*

[❌ Click here](https://s3.amazonaws.com/clickhouse-test-reports/61545/4f30ac72a1ef01f7c783c192639933e32d2f0397/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>❌ failure</td></tr>
<tbody>
</table>

**Review by qoega — APPROVED** [review]

**Comment by wiledusc** [comment]
@qoega  I believe the CI failures are not related to these changes. Can it be merged?

**Comment by qoega** [comment]
We will check all this failures first and then merge.

**Comment by serxa** [comment]
build `clang-17-riscv64` failed with (not related to the change):
```
Mar 19 09:28:53 sccache: warning: The server looks like it shut down unexpectedly, compiling locally instead
Mar 19 09:28:53 sccache: Compile terminated by signal 9
Mar 19 09:28:53 ninja: build stopped: subcommand failed.
```
And fuzzers found two unrelated problems: https://github.com/ClickHouse/ClickHouse/issues/61624 https://github.com/ClickHouse/ClickHouse/issues/61623

**Comment by serxa** [comment]
@wiledusc Could you please merge master into your branch to rerun CI

**Comment by clickgapai** [comment]
Hi @wiledusc @serxa @qoega — while reviewing this PR I found the following:

- **Coverage gap:** `MergeTreePartInfo::tryParsePartName` LEGACY_MAX_LEVEL normalization branch untested — https://github.com/ClickHouse/ClickHouse/pull/103933

Could you review the test PR and add the `can be tested` label if it looks good?
Happy to discuss — close anything that's wrong or already addressed.

**Pull request merged**
