### PR TITLE
Don't prefetch parts with no rows

### PR DESCRIPTION
**Pull request by antonio2368**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Don't prefetch parts for vertical merges if part has no rows.

If we try to read empty source parts, merges will fail because empty files will be deserialized leading to an error.
When no prefetch is done, we have a check in `generate` that prevents reading from empty parts:
```cpp
if (!isCancelled() && current_row < data_part->rows_count)
```
I'm not sure how to make a test :thinking: 

cc @CurtizJ 

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Run only fuzzers related jobs (libFuzzer fuzzers, AST fuzzers, etc.)
- [ ]  Exclude: AST fuzzers
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-ch-test-poll1** [comment]
*This is an automated comment for commit 57fa4239e5fc1254dc38fb153fd4b4c4f9dd6b08 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/70452/57fa4239e5fc1254dc38fb153fd4b4c4f9dd6b08/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/70289/f056c6c2e51d3241412a58878af63b284ec78a5f/docs_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Comment by davenger** [comment]
> I'm not sure how to make a test 

CREATE TABLE with settings to force vertical merge: `enable_vertical_merge_algorithm = 1, vertical_merge_algorithm_min_rows_to_activate = 1, vertical_merge_algorithm_min_bytes_to_activate = 1, vertical_merge_algorithm_min_columns_to_activate = 1, min_rows_for_wide_part = 1, min_bytes_for_wide_part = 1`, 
INSERT some rows, then ALTER DELETE all of them, then insert more rows and do OPTIMIZE?

**Comment by antonio2368** [comment]
> > I'm not sure how to make a test
> 
> CREATE TABLE with settings to force vertical merge: `enable_vertical_merge_algorithm = 1, vertical_merge_algorithm_min_rows_to_activate = 1, vertical_merge_algorithm_min_bytes_to_activate = 1, vertical_merge_algorithm_min_columns_to_activate = 1, min_rows_for_wide_part = 1, min_bytes_for_wide_part = 1`, INSERT some rows, then ALTER DELETE all of them, then insert more rows and do OPTIMIZE?

The problem is mostly how to prevent dropping the part before I try to merge them with OPTIMIZE.
Most likely I need to just increase the timeout for it, I'll try creating something.

**Comment by CurtizJ** [comment]
> The problem is mostly how to prevent dropping the part before I try to merge them with OPTIMIZE.

You can disable table setting `remove_empty_parts`.

**Review by CurtizJ — APPROVED** [review]

**Pull request merged**
