### PR TITLE
Add constexpr

### PR DESCRIPTION
**Pull request by zhanglistar**
### Changelog category (leave one):
- Not For Changelog

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Add constexpr.

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by devcrafter** [comment]
@zhanglistar please could you allow committing to your branch? I'd upload a fix

**Comment by zhanglistar** [comment]
> @zhanglistar please could you allow committing to your branch? I'd upload a fix

@devcrafter Sorry we are using org. account to submit this PR, it does not support this feature. Could you issue a PR to this branch? I will merge it manually.

**Review by devcrafter — APPROVED** [review]
LGTM, let's wait all the tests

**Comment by devcrafter** [comment]
@Felixoid AFAIU, [ClangTidy job](https://github.com/ClickHouse/ClickHouse/actions/runs/3589988320/jobs/6076350590) wasn't able to complete in 6h and was cancelled. It makes `Mergeable Check` red, so PR can't be merged. Any suggestion?

**Comment by Felixoid** [comment]
@devcrafter a few ways to solve the problem:

- restart all failed/one particular job in workflow
- ask admin for force merge (the least preferable)
- Manually mark the status as OK with a proper comment (see pinned messages in dev-ci channel):

> the command `gh api repos/ClickHouse/ClickHouse/statuses/{{commit}} -X POST -F state=pending -F description="Manually unset to rerun" -F context="{{failed status name}}"` will mark the failed status name as pending, and rerun helper will consider it as non-finished. It should help with tests like integration and functional

**Comment by alexey-milovidov** [comment]
Change to "not for changelog", because constexpr does not improve performance when a variable is already a compile-time constant.

**Pull request merged**
