### PR TITLE
[Documentation]Translate the TTL part of MergeTree in the document into Chinese

### PR DESCRIPTION
**Pull request by nauu**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Documentation

Changelog entry (up to few sentences, required except for Non-significant/Documentation categories):

docs/zh/operations/table_engines/mergetree.md 

Detailed description (optional):

I translate the TTL part of MergeTree in the document into Chinese

### CODE REVIEW

**Comment by sundy-li** [comment]
LGTM

**Review by sundy-li — APPROVED** [review]
LGTM

**Comment by sundy-li** [comment]
@nauu  BTW, there's a tool in `ClickHouse/docs/tools/easy_edit.sh`, we shall use it for tracking docs update.

**Comment by nauu** [comment]
@sundy-li sun thats so useful , thx.

**Pull request merged**
