### PR TITLE
Introduce select_only_one_part_with_min_block_per_partition

### PR DESCRIPTION
**Pull request by sylph-eu**
### Changelog category (leave one):
- New Feature

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Introduce `select_only_one_part_with_min_block_per_partition` setting to select only one most tenured part per partition.

This setting helps to improve performance of `SELECT` queries against a continuously **upserted** table. Consider the problem of having a `ReplacingMergeTree` table that receives plenty of new rows, as well as plenty of updates of existing rows. The latter scenario is quite common for data originated from OLTP technologies (Postgres, MySQL, etc), via CDC solution.

A common solution is to use `ReplacingMergeTree` table and `SELECT .. FINAL` statements to ensure that data snapshot is consistent (e.g. no duplicates). However, even despite recent optimizations of `FINAL` modifier, it still remains slow when table is not fully optimized. The latter is quite common if upsert traffic is continuous: there's no "peace" time for the table to fully optimize itself.

As an alternative I propose this setting that picks only the most "tenured" part per partition, in a assumption that table is regularly optimized via `OPTIMIZE TABLE .. FINAL` or via `min_age_to_force_merge_seconds` setting. The change looks for the part with minimum block number and "cuts off" all other parts in the partition. This greatly improves performance of `SELECT ..[FINAL]` queries at a cost of working with "obsolete" data in the table. However the latter trade-off is acceptable for very large tables (tens/hundreds TiBs) whose full reconcilation takes hours/days anyway.

Please also see #62839 for more information.

### Documentation entry for user-facing changes

- [X ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

---
### Modify your CI run:
**NOTE:** If your merge the PR with modified CI you **MUST KNOW** what you are doing
**NOTE:** Checked options will be applied if set before CI RunConfig/PrepareRunConfig step

#### Include tests (required builds will be added automatically):
- [ ]  Fast test
- [ ]  Integration Tests
- [ ]  Stateless tests
- [ ]  Stateful tests
- [ ]  Unit tests
- [ ]  Performance tests
- [ ]  All with ASAN
- [ ]  All with TSAN
- [ ]  All with Analyzer
- [ ]  Add your option here

#### Exclude tests:
- [ ]  Fast test
- [ ]  Integration Tests
- [ ]  Stateless tests
- [ ]  Stateful tests
- [ ]  Performance tests
- [ ]  All with ASAN
- [ ]  All with TSAN
- [ ]  All with MSAN
- [ ]  All with UBSAN
- [ ]  All with Coverage
- [ ]  All with Aarch64
- [ ]  Add your option here

#### Extra options:
- [ ]  do not test (only style check)
- [ ]  disable merge-commit (no merge from master before tests)
- [ ]  disable CI cache (job reuse)

#### Only specified batches in multi-batch jobs:
- [ ]  1
- [ ]  2
- [ ]  3
- [ ]  4

### CODE REVIEW

**Comment by UnamedRus** [comment]
Now ClickHouse is smart enough to split ranges of PK into which are not intersecting across parts (so uniq keys) and which are intersecting (can have duplicates)

So, theoretically you can include all non intersecting in query, which will increase amount of data visible to query.

**Comment by sylph-eu** [comment]
> So, theoretically you can include all non intersecting in query, which will increase amount of data visible to query.

I don't think this is the case of heavy upsert traffic (the primary use case that was always preventing larger adoption of ClickHouse, at least in my experience). If certain partition is continuously updated AND optimized, there will eventually be a "core" part and a series of new parts of lower levels, probably merged with one another. But there's still no guarantee that all PKs in the "core" part do not intersect with any other "younger" part.

The purpose of this functionality is to touch only the "core" part.

**Comment by UnamedRus** [comment]
> If certain partition is continuously updated AND optimized, there will eventually be a "core" part and a series of new parts of lower levels, probably merged with one another.

It would be really nice to split this partition by range of non intersecting PK keys, so effectively reduce size (and duration) of merge.

But, it doesnt fit well into ClickHouse model, expect if you will do partitioning by `(toYYYYMM(ts), cityHash64(pk) % 4)`, which is not ideal

**Comment by sylph-eu** [comment]
> It would be really nice to split this partition by range of non intersecting PK keys, so effectively reduce size (and duration) of merge.

Probably, but that likely mean sub-partitioning. An idea that hasn't yet been implemented in ClickHouse (I may be wrong here). 

> But, it doesnt fit well into ClickHouse model, expect if you will do partitioning by (toYYYYMM(ts), cityHash64(pk) % 4), which is not ideal

It is indeed not ideal, but other solutions are even worse (e.g. Pinot's way). I have high hopes with regard to this change because it was always a struggle to demonstrate "regular" ClickHouse performance on live dataset from MySQL (OLTP traffic). With this change all tools are in place to build a solution that can "sit" on CDC pipeline and serve fast OLAP queries on a snapshot. Forced optimization, control over "age" of unmerged parts, etc can be easily done externally already. 

Speaking of sharding, there're two ways to define partitioning:
 - Indeed `cityHash(PK) % partition_count`. We have to do that if original PK/schema from OLTP DB doesn't have a "birth date": an immutable timestamp that accompanies PK or is a part of PK itself.
 - If, however, there's such a timestamp, it may form partitioning (`PARTITION BY toYYYYMM(birth_date)`), this reducing the scope of a merge.

**Comment by sylph-eu** [comment]
Rebased.

**Comment by sylph-eu** [comment]
@nikitamikhaylov , @alexey-milovidov , could you leave your feedback on whether this feature is acceptable?

**Comment by alexey-milovidov** [comment]
I'm highly doubtful about this change. I understand the motivation behind it. But at the same time, I see it as a complex, expert-level feature that is difficult to reason about. Maybe there is a way to provide something similar in a more universal way? Adding one rarely used setting will be a liability for us.

**Comment by sylph-eu** [comment]
> I'm highly doubtful about this change. I understand the motivation behind it. But at the same time, I see it as a complex, expert-level feature that is difficult to reason about. Maybe there is a way to provide something similar in a more universal way? Adding one rarely used setting will be a liability for us.

I agree that this is an expert-level feature that overrides default part selection and expects respective override of a merge algorithm. However, ClickHouse already offers a wide range of features to "fine-tune" its behavior, and keeps adding them with every release. The advantage of this setting is that it "unlocks" a wide range of use-cases where ClickHouse is coupled with an OLTP technology (either via CDC pipeline or directly (aka HTAP)). This is something which haven't yet been solved for a large update volume, so there's a problem adopting ClickHouse to demonstrate superior cost efficiency and performance (e.g. over Pinot). If this or similar feature "makes through", it's fairly easy to popularise recommended configuration via an article/blog/benchmark.

There's a tool already that allows controllable table optimization (I mean `min_age_to_force_merge_seconds` setting), so an ability to execute against a "snapshot" seems to be a natural addition.

Please let me know how you see more universal solution as I have some time reserved this quarter to work on it. I can also share more information on how final solution can look.

**Comment by sylph-eu** [comment]
Thanks a lot for your feedback! I guess this functionality (the proposed one or an alternative) is going to be beneficial for a ClickHouse community, so it makes sense to make an additional effort in finding one :) Let me put additional context what I would like to achieve.

Some things I'm going to write below are obvious for anyone familiar to the matter, but it may be helpful to see all the challenges and approach to determine the best possible solution.

## Use Case

ClickHouse can efficiently be used as a presentation layer for data. It's efficient and cheap (in terms of hardware cost per a unit of data volume), therefore it makes economic sense to use it for the matter.
Given a persistent and durable storage like e.g. DataWarehouse (DWH) or OLTP database (MySQL, Postgres, CockroachDB), ClickHouse can (continuously) be updated with recent changes to serve analytical queries. 

From design perspective it looks somewhat as follows:

```
   # 1. OLTP + OLAP access. Data is delivered via an optional CDC pipeline to ClickHouse, where it's ingested & projected to configured presentation.
   (USER) --OLTP-queries---> [OLTP DataSource] -> (Optional: CDC + Kafka/Else + Ingester) -> [ClickHouse]
     |                                                                                     |
     +------------------------------------OLAP-queries-------------------------------------+

   # 2. Ingestion from DWH. ETL tool is responsible for performing queries, joining data, and delivering the end view to ClickHouse.
   (DWH/DataLake Table 1) -----data---------+
                                        [ETL Tool]---data-view---> [ClickHouse] <---- (USER)
   (DWH/DataLake Table 2) -----data---------+
```

In both use-cases there's a need to update existing snapshot in-place:
 - to support incremental updates of data (upserts/deletes).
 - to implement schema evolution of either Source-of-Truth (SoT) technology (OLTP/DWH) or projected view (user-case 2). For example, for use-case 2, adding a new column in the joined table will require all data in ClickHouse to be overwritten.


## Problem

Given use-cases above, an implementation with ClickHouse shall meet the following requirements:
1. support access to a consistent snapshot of the data from SoT
2. support continuous in-place data updates. It's common to have entire dataset overwritten at regular intervals.
3. preserve stable query performance at all times

Requirements 1 & 2 can now be solved with the usage of `ReplacingMergeTree` engine, accompanied by `FINAL` modifer and optional `OPTIMIZE TABLE .. FINAL` runs. However it's hard to achieve stable query performance with RMT & FINAL in ClickHouse due to colocation of write and read traffic on the nodes. By default an insertion into ClickHouse produces a part that has to merged-in/optimized at query time, which in turn spoils a bunch of caches (OS & CH), requires CPU time & large amounts of memory, and finally amplifies IO (it's becoming a major challenge in a cloud setup with managed disks). Our benchmarks show that even a slight ingestion traffic into ClickHouse can decrease the performance of queries with `FINAL` by a factor of 10-20.

Probably it's worth describing how Pinot does it (it appears to be a natural open-source competitor in the field), to compare why ClickHouse-based solution may be more benefitial. 
Pinot introduces the notion of Hybrid table: a table (view) that consists of 2 tables: REALTIME one for continuous updates and OFFLINE for historical data. Therefore having a hybrid table `test`, the latter in fact consists of `test_OFFLINE` and `test_REALTIME` tables.

These two types of tables implement upsert support differently:
 - `test_REALTIME` reads a continuous stream of events from e.g. Kafka and maintains a bunch of (Java) hashmaps in memory, so that for every unique PK it can locate the latest received version. Obviously the capacity of UPSERTed volume is limited to the heap size. Upon exceeding the limit it goes OOM.
 - `test_OFFLINE` expects external ingestor to "optimize"/de-duplicate 1+ segments (parts) and atomically replace existing ones with the new ones (to form so called "segment lineage"). Replacement is, therefore, possible only at a segment level.
At query time Pinot queries both tables and merges the results.

With open-source ClickHouse it's possible to support (full) upserts cheaper:
 1. One `ReplacingMergeTree` table, no need to split between two. Less resources, less complexity.
 2. No need to allocate sizable RAM volume to keep results in memory as ClickHouse is a disk-based system. Again less resources.
 3. No need for dedicated ingester as data can be merged in-place. This is simpler to maintain.


### Solution 1: Cloud native system

This is the architecture where an object storage becomes the SoT location for data. Therefore, naturally it comes with a possibility to decoupe read & write traffic, thus allowing the latter to be done outside of the query engine.
This is not an option for ClickHouse as `SharedMergeTree` hasn't been open-sourced. Also Byconity implementation wasn't mature enough at the time we tested it.

### Solution 2: Isolate read & write traffic on a node

Likely this can be done by routing the ingestion into intermediate tables, optimizing them in-place, and swapping parts between "write" and "read" tables. 
This approach comes at a cost of excessive complexity though. In a replicated setup (any production system requires one) there will be a need in non-trivial control plane to coordinate ingestion/updates, maintain metadata snapshot, support coordinated schema evolution across all involved parts (tables, views, etc). Eventually it will remind a lose implementation of Solution 1 above.

### Solution 3: Avoid merges in FINAL, read from an optimized snapshot

Try to get rid of merges from a hot (query) path. This approach doesn't eliminate the cost of having non-read traffic on the same node, but makes queries way cheaper. With RMT ClickHouse normally doesn't consume a lof of resources, therefore with
certain overprovisioning it can serve queries at acceptable speed despite background processing. 

To avoid merges in FINAL we need to ensure that only 1 part per partition is read. Alternatively, ClickHouse could check that parts are disjoint in terms of primary keys (this is not happening now in `ReadFromMergeTree::doNotMergePartsAcrossPartitionsFinal()`). 

To achieve 1 part per partition one can e.g. configure a cron job to run `OPTIMIZE TABLE .. FINAL SETTINGS optimize_skip_merged_partitions=1`, or configure `min_age_to_force_merge_seconds` on a table.

If table has time to optimize itself fully, then no new functionality is needed. Otherwise we need a way to filter-out parts that haven't yet been optimized/merged-in. #62839 explores the options based on views, but their performance is not guaranteed (e.g. they're slow with experimental analyzer, so there's a chance that something else may break).

This PR suggests blindly picking 1 oldest part per partition and leaving the rest to external monitoring. If optimization job falls back, it's becoming an operational issue/incident, although stale data will be delivered fast.

Alternatively, we may allow queries (via new setting) to specify maximum age of the part to be included in the query. Again, if optimization job falls behind, data will not be stale, but performance will likely suffer.

## Concerns

Now let me try to address concerns from the comment above & slack conversation.

### Maximum part size

It can indeed become a problem if partitioning is not done right and/or data volume is excessive. However, this is not a **new** problem. Any existing solution that relies on RMT and FINAL have to be aware of maximum possible part size and maintain resources (disk space) accordingly. Potentially ClickHouse can implement sub-partitioning (partitioning within a partition) or dynamic partitioning (split of existing partitions), but I cannot judge if it in the plans. Also I haven't noticed any checks for disjoint parts on read-path though (can be wrong here).

Practically, I see that currently default max part limit is set to 150GiB (after compression), which is a good reserve if data partitioned right. Also, a necessity to have free disk space to ensure LSM is working fine is not a new operational practice.

@alexey-milovidov , Do you see that limitation (until better partitioning is implemented) as a blocker for the proposed schema?

### Managing data age

Here we have to traditionally choose between performance or consistency. Say "max age" is calculated as the age of "the second" active part in the partition (if partition has just 1 part it's ommitted).

I see two aproaches here:
 - force max allowed age of data. This way we choose consistency and require a query with `FINAL` to include more than 1 part if optimization job falls behind configured "max age". This way results are always acceptable (queried data is not older than "max age"), but performance may bounce. In terms of implementation there could be a new setting: `select_include_parts_older_than_seconds=120`.
 - report factual age of data after the query (as metadata). Always pick only one part per partition, but report max("max age") as a metadata for query result. It's up to the clients to decide whether to accept the results then. I can look if this PR can be extended with metadata delivery.

On top of the above, users may include a time-based cut-off predicate to further filter out "newer" data.

### Dependent aggregating materialized views

The problem here is that upsert/deletes of a "core" RMT table is not correctly propagated to dependent (via MV) table with aggregating engine. Rows of the core table, once aggregated, cannot be correctly rolled back to consider the updates. 
This is again not a new problem. It's caused by the fact that MVs propagates only a newly inserted chunk of data, but has no possibility to dynamically recalculate entire partition from scratch (given that core and dependent tables share the same partitioning expression).

## Conclusion

I'd like to have a guidance on what's preferred way (if any) to implement reading from snapshot. As I said I have some time this quarter to try making it happen. Please let me know what you think.

**Comment by UnamedRus** [comment]
Just an idea from slightly different perspective.
What if ClickHouse will have in memory per part cache of "outdated" rows. (it will not be persisted)
It will be populated during normal `SELECT FINAL` queries.
Each cache entry for particular part will include  max-min granula numbers(which it covers), "version" column(which represents latest block_number it was tested) 

So, basically
```
struct PartCache {
        struct CacheEntry[]
}

struct CacheEntry {
     int min_granula_num
     int max_granula_num
     int max_block_number
     int outdated_rows[]
}
```

cache entries could be split in 2, if for example new SELECT FINAL queries includes new_max_granule_number > min_granula_num from another, but doesn't include max_granula_num from it. So it will produce 2 entries:
`new_min_granula_number...new_max_granule_number`  with `new_max_block_number`
And
`new_max_granule_number+1..max_granula_num ` with `old_max_block_number`

**Comment by sylph-eu** [comment]
> Basically, it will act as cache for vertical SELECT FINAL implementation, so ClickHouse could skip part of reading ORDER BY columns for some granules ranges

It's a good complementary effort to make `SELECT .. FINAL` faster, it can be implemented as a separate improvement. 
Just want to note that in this PR I'd like to find a way to make `SELECT .. [FINAL]` performance stable and predictable, to ensure certain SLO's are met in a production setup.

@alexey-milovidov , could you comment on the second proposed approach? Or share your vision?

**Comment by nikitamikhaylov** [comment]
I like the approach with `select_include_parts_older_than_seconds`, we can obtain the information about part creation time either from filesystem or from [Zoo]Keeper and depending on it decide whether a part goes to a snapshot used for SELECTs or not.

**Comment by sylph-eu** [comment]
Thanks @nikitamikhaylov , I'll create a separate PR and will close this one then.

**Comment by sylph-eu** [comment]
I've looked at the matter a bit closer, the strategy with `select_include_parts_older_than_seconds` will require the introduction of additional part metadata field `min_block_modification_time` to track the modification time of an old merged part that contributed min_block to the current higher-level part. Not sure whether this approach will be approved.

Please let me know if you have an additional feedback on this PR.

**Comment by nikitamikhaylov** [comment]
@sylph-eu Looks like we don't have another option, but to introduce this metadata field.

**Comment by sylph-eu** [comment]
Thanks @nikitamikhaylov . I'll try to see what it will take to implement metadata field.

**Pull request closed without merging**
