### PR TITLE
Add FreeBSD AIO support.

### PR DESCRIPTION
**Pull request by vitlibar**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

https://github.com/yandex/ClickHouse/issues/4302

Category (leave one):
- Improvement

Short description (up to few sentences):
Implemented AIO support for FreeBSD.

### CODE REVIEW

**Comment by proller** [comment]
```
../dbms/src/IO/AIO.cpp: In function 'int io_getevents(int, long int, long int, kevent*, timespec*)':
../dbms/src/IO/AIO.cpp:123:32: warning: parameter 'min_nr' set but not used [-Wunused-but-set-parameter]
 int io_getevents(int ctx, long min_nr, long max_nr, struct kevent * events, struct timespec * timeout)
                           ~~~~~^~~~~~
../dbms/src/IO/AIO.cpp: In constructor 'AIOContext::AIOContext(unsigned int)':
../dbms/src/IO/AIO.cpp:130:37: warning: parameter 'nr_events' set but not used [-Wunused-but-set-parameter]
 AIOContext::AIOContext(unsigned int nr_events)
                        ~~~~~~~~~~~~~^~~~~~~~~

```

**Comment by proller** [comment]
```
../dbms/src/IO/WriteBufferAIO.cpp:202:32: warning: use of old-style cast [-Wold-style-cast]
    bytes_written = aio_return((struct aiocb *)event.udata);
                               ^               ~~~~~~~~~~~
1 warning generated.
[1093/1771] Building CXX object dbms/CMakeFiles/clickhouse_common_io.dir/src/IO/ReadBufferAIO.cpp.o
[1094/1771] Building CXX object dbms/CMakeFiles/clickhouse_common_io.dir/src/IO/AIOContextPool.cpp.o
../dbms/src/IO/AIOContextPool.cpp:98:41: warning: use of old-style cast [-Wold-style-cast]
        it->second.set_value(aio_return((struct aiocb *)event.udata));
                                        ^               ~~~~~~~~~~~
1 warning generated.

```

**Comment by proller** [comment]
```
../dbms/src/IO/AIO.cpp:115:6: warning: variable 'r' may be uninitialized when used here [-Wconditional-uninitialized]
        if (r < 0) {
            ^
../dbms/src/IO/AIO.cpp:93:10: note: initialize the variable 'r' to silence this warning
    int r;
         ^
          = 0

../dbms/src/IO/AIOContextPool.cpp:98:41: warning: use of old-style cast [-Wold-style-cast]
        it->second.set_value(aio_return((struct aiocb *)event.udata));
                                        ^               ~~~~~~~~~~~

../dbms/src/IO/WriteBufferAIO.cpp:202:32: warning: use of old-style cast [-Wold-style-cast]
    bytes_written = aio_return((struct aiocb *)event.udata);
                               ^               ~~~~~~~~~~~

```

**Comment by alexey-milovidov** [comment]
Missing changelog.

**Pull request merged**
