### PR TITLE
Add proper escaping for DDL OpenTelemetry context serialization

### PR DESCRIPTION
**Pull request by azat**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Add proper escaping for DDL OpenTelemetry context serialization

Before you was able to break the format by using "\n" or "\t", that will
simply lead to DDL hang, because DDLWorker will simply log the error and
do nothing more:

    <Error> DDLWorker: Cannot parse DDL task query-0000000056: Incorrect task format. Will try to send error status: Code: 27. DB::ParsingException: Cannot parse input: expected '\n' before: 'bar\n1\n'. (CANNOT_PARSE_INPUT_ASSERTION_FAILED) (version 23.5.1.1)

Fix this by adding proper escaping.

And also add a proper test that indeed check `\n`.

Follow-up for: #41484 (@FrankChen021 )

_Note: to enable this feature you need to manually set `distributed_ddl_entry_format_version=4`, I guess there were not a lot of such users, and even less, who uses symbols that should be escaped in `tracestate`_

### CODE REVIEW

**Comment by robot-clickhouse-ci-2** [comment]
This is an automated comment for commit 82054d40a56645e2386452bd4828805d5b4c3a23 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/50045/82054d40a56645e2386452bd4828805d5b4c3a23/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Comment by FrankChen021** [comment]
what kind of client generates `tracestate` that contains the `\n`?

**Comment by azat** [comment]
>what kind of client generates tracestate that contains the \n?

This is just possible, and serialization/deserialization should not be broken by this.

**Comment by FrankChen021** [comment]
If it's only possible, I'm curious how did you find out this problem? by reviewing code?

**Comment by azat** [comment]
>If it's only possible, I'm curious how did you find out this problem? by reviewing code?

@alexey-milovidov found it here https://github.com/ClickHouse/ClickHouse/pull/50015#discussion_r1199511676

**Comment by FrankChen021** [comment]
Thank you @azat for the info

**Review by serxa — APPROVED** [review]

**Comment by serxa** [comment]
ClickHouse Stateless Tests (release, DatabaseReplicated) [1/4] — `02735_system_zookeeper_connection`

**Pull request merged**
