### PR TITLE
Improve behaviour of conversion into Date for boundary value 65535

### LINKED ISSUE #43370: toDate conversion does not match Date column conversion
**Describe the unexpected behaviour**
Using `toDate(integer`) returns a different value than inserting the same integer into a Date column.

**How to reproduce**
* Which ClickHouse server version to use
ClickHouse server version 22.8.6 revision 54460
```
clickhouse1 :) select toDate(65535)

SELECT toDate(65535)

Query id: 11870fad-31b0-4822-8d16-05ee9ef7d13e

┌─toDate(65535)─┐
│    2149-06-06 │
└───────────────┘

clickhouse1 :) create table y (z Date) engine=Memory

CREATE TABLE y
(
    `z` Date
)
ENGINE = Memory

Query id: c4436573-c4da-4c22-a48c-401adb935a39

Ok.

0 rows in set. Elapsed: 0.005 sec. 

clickhouse1 :) insert into y values (65535)

INSERT INTO y FORMAT Values

Query id: e8d58889-de37-4d51-abfd-107893ace403

Ok.

1 row in set. Elapsed: 0.005 sec. 

clickhouse1 :) select * from y

SELECT *
FROM y

Query id: e2bff938-211c-4c05-97f9-3e74bf34261f

┌──────────z─┐
│ 1970-01-01 │
└────────────┘

1 row in set. Elapsed: 0.003 sec. 
```

### PR DESCRIPTION
**Pull request by jh0x**
#43370 describes a bit weird behaviour when dealing with column of `Date` type 

For `Date` (underlying `UInt16`) we have:
> Supported range of values: `[1970-01-01, 2149-06-06]`.

I think the behaviour after the fix is more consistent.

I'm not sure if the provided solution is the best though.

Closes #43370

### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Improve behaviour of conversion into Date for boundary value 65535 (2149-06-06)

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]

**Comment by antonio2368** [comment]
`02540_date_column_consistent_insert_behaviour` became flaky after this

https://play.clickhouse.com/play?user=play#c2VsZWN0IGNoZWNrX3N0YXJ0X3RpbWUsIHB1bGxfcmVxdWVzdF9udW1iZXIsIHJlcG9ydF91cmwKZnJvbSBjaGVja3MgCndoZXJlICcyMDIzLTAxLTAxJyA8PSBjaGVja19zdGFydF90aW1lIGFuZCB0ZXN0X25hbWUgbGlrZSAnJTAyNTQwX2RhdGVfY29sdW1uX2NvbnNpc3RlbnRfaW5zZXJ0X2JlaGF2aW91ciUnIGFuZCB0ZXN0X3N0YXR1cyBpbiAoJ0ZBSUwnLCAnRkxBS1knLCAnRVJST1InKSAKZ3JvdXAgYnkgMSwgMiwgMwpvcmRlciBieSAx

**Comment by antonio2368** [comment]
@jh0x can you please check the test and resubmit the PR? Sorry for the revert but the test failed too often.

**Comment by qoega** [comment]
Locally there was another time zone and it worked in last CI run just because of luck. In CI we use random tz and it start to fail

**Comment by jh0x** [comment]
@antonio2368 Sorry for the trouble. I shall have a look at this.

@qoega Thank you for the hint - this seems to be the issue indeed. When using e.g. `TZ=Australia/Brisbane` I can see it failing. Failures are on `65536` values which are converted using the `time_zone.toDayNum` - so I suspect I need to rewrite the test part a bit.

**Pull request merged**
