### PR TITLE
Enable ThreadFuzzer with random sleeps

### PR DESCRIPTION
**Pull request by alexey-milovidov**
Changelog category (leave one):
- Non-significant (changelog entry is not required)

Detailed description / Documentation draft:
Not intended for merge. Only to run CI tests and catch a fire.

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
`performance_introspection_and_logging` - failed as it should.

**Comment by alexey-milovidov** [comment]
Another race condition found:
https://clickhouse-test-reports.s3.yandex.net/9515/aed0bf1654c31bfb5bf62deb48e329ed4036a2e3/functional_stateless_tests_(thread)/stderr.log

**Comment by qoega** [comment]
@Mergifyio update

**Comment by nikitamikhaylov** [comment]
@Mergifyio update

**Comment by qoega** [comment]
@Mergifyio update

**Comment by alexey-milovidov** [comment]
@Mergifyio update

**Comment by alexey-milovidov** [comment]
@Mergifyio update

**Comment by alexey-milovidov** [comment]
@Mergifyio update

**Comment by alexey-milovidov** [comment]
@mergifyio update

**Pull request closed without merging**
