### PR TITLE
Enable JIT compilation for aggregation without key

### LINKED ISSUE #41461: Fix JIT for GROUP BY wtihout keys
Right now the server will crash, so the code disables it:
- https://github.com/ClickHouse/ClickHouse/blob/76aaecf1aa096d22b7d35f65a4c6cb2e0525e254/src/Interpreters/Aggregator.cpp#L1433-L1440 (added by @kitaisreal in #27574)
- https://github.com/ClickHouse/ClickHouse/blob/76aaecf1aa096d22b7d35f65a4c6cb2e0525e254/src/Interpreters/JIT/compileFunction.cpp#L742-L745 (added by @azat in #41046, for details please see https://github.com/ClickHouse/ClickHouse/pull/41046/commits/ba4174402a47512c298e4f3f7804cc772f2802a6)

### PR DESCRIPTION
**Pull request by kitaisreal**
### Changelog category (leave one):
- Performance Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Enable JIT compilation for aggregation without key. Closes #41461.

### CODE REVIEW

**Comment by robot-ch-test-poll4** [comment]
This is an automated comment for commit 6005a3baa0ddf1550476206561583e8fd838b336 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/53757/6005a3baa0ddf1550476206561583e8fd838b336/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
@kitaisreal, all ok, but we need to update one test - add rounding.

**Comment by alexey-milovidov** [comment]
This is good, but one test has failed.

**Comment by alexey-milovidov** [comment]
Continued in #58440.

**Pull request closed without merging**
