### PR TITLE
Fix build for AppleClang

### PR DESCRIPTION
**Pull request by dmthuc**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category:
- Not for changelog (changelog entry is not required)

Detailed description:
Fix build on master branch for internal **capnproto** library when build with Clang.  This issue have been discussed in here https://github.com/capnproto/capnproto/issues/815. The problem is that lib **capnproto** unable to build with flag **fchar8_t** on .So to fix it, I disable this flag when build this library with clang.

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
It is possible to disable `-fchar8_t` flag only for CapNProto rather than globally.

**Comment by alexey-milovidov** [comment]
See `contrib/capnproto-cmake/CMakeLists.txt`

**Comment by alexey-milovidov** [comment]
With similar `target_compile_options` that we have at the bottom of this file.

**Comment by dmthuc** [comment]
Thank you, I will try it

**Review by alexey-milovidov — APPROVED** [review]

**Pull request merged**
