### PR TITLE
Fix parallel final stuck

### LINKED ISSUE #11636: Master: pipeline stuck
```
CREATE TABLE pipeline_stuck ( `id` String, `val` SimpleAggregateFunction(anyLast, String), INDEX ind val TYPE bloom_filter() GRANULARITY 1 ) ENGINE = AggregatingMergeTree() ORDER BY id ;
insert into pipeline_stuck select toString(number%100), toString(number) from numbers(10000000);
select * from pipeline_stuck final limit 10;
select * from pipeline_stuck final where val = '9999900';
alter table pipeline_stuck drop index ind;
select * from pipeline_stuck final where val = '9999900';
```

### PR DESCRIPTION
**Pull request by KochetovNicolai**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix possible `Pipeline stuck` for selects with parallel `FINAL`. Fixes #11636

### CODE REVIEW

**Comment by KochetovNicolai** [comment]
Please don't merge it until perftests result.

**Comment by KochetovNicolai** [comment]
`01269_create_with_null` fails but doesn't seem to be caused by this pr changes.

**Comment by alexey-milovidov** [comment]
@KochetovNicolai But it fails in all test runs?

**Comment by KochetovNicolai** [comment]
Now tests are fine.

**Review by alexey-milovidov — APPROVED** [review]

**Pull request merged**
