### PR TITLE
Try random container name in integration tests runner

### PR DESCRIPTION
**Pull request by tavplubix**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

I hope it will fix failures like this:
```
2022-06-14 18:06:22,850 [ 811394 ] INFO : Unknown image clickhouse/integration-helper (runner:246, <module>)
Error response from daemon: Cannot kill container: 6f3d71a319b8: tried to kill container, but did not receive an exit event
docker: Error response from daemon: Conflict. The container name "/clickhouse_integration_tests" is already in use by container "6f3d71a319b8435af3c1b198f0bbc785da5f3895f54f4cdbaa8753d7ed538890". You have to remove (or rename) that container to be able to reuse that name.
See 'docker run --help'.
Traceback (most recent call last):
  File "./runner", line 316, in <module>
    subprocess.check_call(cmd, shell=True)
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
```

### CODE REVIEW

**Comment by alesapin** [comment]
Integration tests passed?

**Comment by tavplubix** [comment]
> Integration tests passed?

Yes, as you can see

**Comment by tavplubix** [comment]
And there is one flaky test: test_storage_s3/test.py::test_seekable_formats_url, cc: @kssenii 
https://s3.amazonaws.com/clickhouse-test-reports/38107/2297708032b6cac56879c73876359e84c0827ac7/integration_tests__release__actions__[1/2].html

**Comment by tavplubix** [comment]
ClickHouse special build check (actions) - #38098
Stateless tests (memory, actions) [3/3] - #38117
Stateless tests (thread, actions) [1/3] - timeouts - tests with tsan are broken
Stress test (undefined, actions) - `No replica has part covering ... and a merge is impossible`, `Part ... is lost forever` - looks like suppressions are missing - #38131

**Review by alesapin — APPROVED** [review]

**Pull request merged**
