### PR TITLE
Fix Test File Name Type

### PR DESCRIPTION
**Pull request by jsc0218**
Fix a test filename typo
### Changelog category (leave one):
- Build/Testing/Packaging Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix a test filename typo

### CODE REVIEW

**Comment by robot-ch-test-poll4** [comment]
*This is an automated comment for commit 16f664edcecaf896a6bee7b76b365fb1a9ba6195 with description of existing statuses. It's updated for the latest CI running*

[❌ Click here](https://s3.amazonaws.com/clickhouse-test-reports/57272/16f664edcecaf896a6bee7b76b365fb1a9ba6195/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td><a href="https://github.com/ClickHouse/ClickHouse/actions/runs/7009202025">✅ success</a></td></tr>
<tbody>
</table>
</details>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/57272/16f664edcecaf896a6bee7b76b365fb1a9ba6195/ci_running.html">❌ failure</a></td></tr>
<tbody>
</table>

**Review by evillique — APPROVED** [review]

**Comment by jsc0218** [comment]
@evillique would you mind take a look why 01104_distributed_numbers_test failed, where in stderr "Include not found: networks", while I just changed another test file name, which seems quite irrelavent to the issue.

**Comment by evillique** [comment]
@jsc0218 It is a known issue: https://github.com/ClickHouse/ClickHouse/issues/56256

**Comment by evillique** [comment]
You can rebase/merge with a fresh master and just merge right after that because it does not really affect any code, so there is no need for it to be tested (especially for the second time).

**Pull request merged**
