### PR TITLE
Revert "Merge pull request #64425 from ClickHouse/revert-64132-refactor-protocol-server"

### PR DESCRIPTION
**Pull request by TTPO100AJIEX**
This reverts commit ac4ea3e32b6cbd8a392582ec7027e8e503d302a3, reversing changes made to 7a552f5b06f36b05f4728546f587daf91c437f5a.
Replaces https://github.com/ClickHouse/ClickHouse/pull/64447

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by robot-ch-test-poll1** [comment]
*This is an automated comment for commit f63aaf0e38f2c169b6ff9129725fe0a185a4eb46 with description of existing statuses. It's updated for the latest CI running*

[❌ Click here](https://s3.amazonaws.com/clickhouse-test-reports/64599/f63aaf0e38f2c169b6ff9129725fe0a185a4eb46/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>A Sync</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>⏳ pending</td></tr>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td><a href="https://github.com/ClickHouse/ClickHouse/blob/master/.github/PULL_REQUEST_TEMPLATE.md?plain=1">❌ failure</a></td></tr>
<tbody>
</table>

**Comment by TTPO100AJIEX** [comment]
@rschu1ze Failed tests do not seem related to the changes. Could you merge, please?

**Comment by rschu1ze** [comment]
There are a ton of further merge conflicts in the internal repository. Need to work on other stuff right now, will check later.

**Comment by rschu1ze** [comment]
Sorry for the delay. It took me 2.5 hours to resolve the conflicts in the internal repo 😢. Things compile now, but I still need to checked if really nothing broke.

**Comment by rschu1ze** [comment]
Unfortunately, some tests in the internal repo failed. Also, this [other PR](https://github.com/ClickHouse/ClickHouse/pull/64889) will conflict with the work 😢 Suggest to wait till the other PR is merged, then I'll re-try.

**Comment by TTPO100AJIEX** [comment]
@rschu1ze https://github.com/ClickHouse/ClickHouse/pull/64889 seems to have been merged. Could you please try to merge this and, finally, https://github.com/ClickHouse/ClickHouse/pull/64413 again?

**Comment by rschu1ze** [comment]
@TTPO100AJIEX Kindly fix the merge conflicts in this PR first, thanks.

**Comment by TTPO100AJIEX** [comment]
@rschu1ze Done. One of the builds has failed, but it does not seem related to the changes. Could you please restart the check?
> Jul 14 14:39:59 FAILED: src/Functions/CMakeFiles/clickhouse_functions_obj.dir/pointInEllipses.cpp.o 
> Jul 14 14:39:59 FAILED: src/Functions/CMakeFiles/clickhouse_functions_obj.dir/parseTimeDelta.cpp.o

**Comment by rschu1ze** [comment]
@TTPO100AJIEX Thanks for rebasing again. There are unfortunately still lots of conflicts in the internal repo. Question: Would it be possible to chop this large refactoring into smaller but still self-contained PRs, e.g. with 200 LOC each?

**Comment by TTPO100AJIEX** [comment]
I think it should be fairly simple to take out the deleted code from Server.cpp, which causes the most issues. I will try to do that.

**Comment by TTPO100AJIEX** [comment]
@rschu1ze Should be better now. I will clean up the old functions separately after this is merged.

**Comment by TTPO100AJIEX** [comment]
@rschu1ze Could you please have a look? Thanks

**Comment by rschu1ze** [comment]
Everyone is working on stabilizing CI tests at the moment, expect some delay, sorry.

**Comment by TTPO100AJIEX** [comment]
@rschu1ze Rebased again and squashed the commits. Could you please finally merge the PR? This is taking too long...

**Comment by TTPO100AJIEX** [comment]
@rschu1ze Rebased again. Could you please have a look?

**Pull request closed without merging**
