### PR TITLE
Bump minizip-ng to a sane version

### PR DESCRIPTION
**Pull request by amosbird**
### Changelog category (leave one):
- Build/Testing/Packaging Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Bump minizip-ng to a sane version, or else old git won't be able to address dangling remote ref. https://github.com/ClickHouse/ClickHouse/issues/35656

The old commit sits in the middle of a PR https://github.com/zlib-ng/minizip-ng/pull/609/commits/6cffc951851620e0fac1993be75e4713c334de03

> Information about CI checks: https://clickhouse.tech/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
@mergifyio update

After #36337

**Comment by alexey-milovidov** [comment]
Waiting for #36361 and #36363 to be merged.

**Comment by alesapin** [comment]
Hung in cache test.

**Comment by alesapin** [comment]
@Mergifyio update

**Comment by alexey-milovidov** [comment]
Stress test - #36660

**Comment by alexey-milovidov** [comment]
Stateless test - something from @azat 

@mergifyio update

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
We still have something strange from @azat: https://s3.amazonaws.com/clickhouse-test-reports/36295/314d553ab14d30df7508814513506ec09c7c7061/stateless_tests__debug__actions__[1/3].html

**Comment by azat** [comment]
>We still have something strange from @azat: [https://s3.amazonaws.com/clickhouse-test-reports/36295/314d553ab14d30df7508814513506ec09c7c7061/stateless_tests__debug__actions__[1/3].html](https://s3.amazonaws.com/clickhouse-test-reports/36295/314d553ab14d30df7508814513506ec09c7c7061/stateless_tests__debug__actions__%5B1/3%5D.html)

This run does not includes #36649

**Comment by alexey-milovidov** [comment]
@mergifyio update

**Comment by alexey-milovidov** [comment]
@azat https://s3.amazonaws.com/clickhouse-test-reports/36295/314d553ab14d30df7508814513506ec09c7c7061/stateless_tests__debug__actions__[1/3].html even after merge with master.

**Comment by azat** [comment]
>@azat [https://s3.amazonaws.com/clickhouse-test-reports/36295/314d553ab14d30df7508814513506ec09c7c7061/stateless_tests__debug__actions__[1/3].html](https://s3.amazonaws.com/clickhouse-test-reports/36295/314d553ab14d30df7508814513506ec09c7c7061/stateless_tests__debug__actions__%5B1/3%5D.html) even after merge with master

No, this is the run w/o that PR merged, there is no stateless tests results after the merge yet.

**Pull request merged**
