### PR TITLE
Use random timezone in stateless and stateful tests

### LINKED ISSUE #5098: GraphiteMergeTree: use time zone of the data type for rounding.
Current behaviour:

GraphiteMergeTree uses server time zone to perform rounding.
For example, if the server is run with Moscow time, rounding to midnight will be done in Moscow time.

Desired behaviour:

Use time zone specified in DateTime data type `DateTime('UTC')`.

### LINKED ISSUE #12439: Run tests in CI with random time zone.
To make it less reliable.

CC @alesapin

### PR DESCRIPTION
**Pull request by alesapin**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Now we ran stateful and stateless tests in random timezones. Fixes #12439. Reading String as DateTime and writing DateTime as String in Protobuf format now respect timezone. Reading UInt16 as DateTime in Arrow and Parquet formats now treat it as Date and then converts to DateTime with respect to DateTime's timezone, because Date is serialized in Arrow and Parquet as UInt16. GraphiteMergeTree now respect time zone for rounding of times. Fixes #5098. Author: @alexey-milovidov.

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]

**Comment by qoega** [comment]
Now we have to fix them :)

**Comment by qoega** [comment]
Blocked by https://github.com/ClickHouse/ClickHouse/issues/24128

**Comment by alexey-milovidov** [comment]
Finally #5098 is needed.

**Comment by alexey-milovidov** [comment]
Stress test: https://github.com/ClickHouse/ClickHouse/pull/24194#issuecomment-886133456

**Comment by alexey-milovidov** [comment]
> 01098_msgpack_format

Another exception from parallel runs.

**Pull request merged**
