### PR TITLE
Revert "Revert "Fix AWS ECS""

### PR DESCRIPTION
**Pull request by Avogar**
Reverts ClickHouse/ClickHouse#65361

### CODE REVIEW

**Comment by robot-clickhouse-ci-2** [comment]
*This is an automated comment for commit 4817657375a37c374eb4be72793cba434c16a815 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/65362/4817657375a37c374eb4be72793cba434c16a815/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>A Sync</td><td>If it fails, ask a maintainer for help</td><td>⏳ pending</td></tr>
<tbody>
</table>
<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>Checks correctness of the PR's body</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

**Comment by Algunenano** [comment]
Keep in mind that https://s3.amazonaws.com/clickhouse-test-reports/0/a29babcb611411ff7ee4edbbd4135ca0d1e45280/stateless_tests__tsan__s3_storage__[1_5].html was probably related to this PR before it was reverted (data race in CH local)

**Comment by Avogar** [comment]
@alexey-milovidov can you check the data race in your test?

**Comment by alexey-milovidov** [comment]
Looks like a bug in AWS SDK (the second one in a row). I will take a look.

**Comment by alexey-milovidov** [comment]
https://github.com/aws/aws-sdk-cpp/pull/3013

**Comment by Sharu95** [comment]
Man things are moving fast in these PRs, appreciate the effort and pace here 🚀 Also saw the cpp PR was merged in https://github.com/aws/aws-sdk-cpp/pull/3013 💎

**Comment by Sharu95** [comment]
Was just wondering if there were any updates on this? 😄

**Comment by alexey-milovidov** [comment]
It is in progress, I am doing it in between of other pull request.
Hold tight :)

**Comment by jakedaleweb** [comment]
Hello 👋 how's this coming along? anything we can do to help?

**Comment by alexey-milovidov** [comment]
@jakedaleweb, There were no updates past week.
Have a good day. Cheers, Alexey.

**Comment by jakedaleweb** [comment]
@alexey-milovidov thanks for the update, I really appreciate your communication on this PR.

Is this blocked by another PR on a project somewhere else? Or is is a matter of finding time to work on it?

Apologies if I am coming off as pushy, but getting this working is make-or-break for my implementation of Clickhouse which I am really keen to keep moving on.

**Comment by jakedaleweb** [comment]
Hi, just trying to get a pulse on this one as it will inform the route I take for my work. Is there likely to be a resolution on this in days, weeks, months?

Again, not trying to be pushy! 😅

**Comment by jakedaleweb** [comment]
FYI have managed to work around this https://github.com/ClickHouse/ClickHouse/issues/33771#issuecomment-2287856016

**Comment by Sharu95** [comment]
@alexey-milovidov, any deployed releases with this fix?

**Comment by alexey-milovidov** [comment]
The release builds are ready:
```
curl https://clickhouse.com/ | sh
```

**Comment by Sharu95** [comment]
Thanks @alexey-milovidov! I was using the Docker server version, it works with the `head` tag, but experienced issues with `24.7.4.51`. When I did the curl, it seems like the version was different, so I assume its just the docker release that is different

**Comment by alexey-milovidov** [comment]
It is from 24.9 (which is currently in pre-release).

**Pull request merged**
