### PR TITLE
Parse and store opentelemetry trace-id in big-endian order

### PR DESCRIPTION
**Pull request by FrankChen021**
Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
- Parse and store OpenTelemetry trace-id in big-endian order

Detailed description / Documentation draft:

ClickHouse now parses the trace id from the opentelemetry HTTP `traceparent` in little end order, which is counterintuitive for users to search the trace in the span log or export the  span log to other system by using URL engine. Users are always struggling dealing with the incorrect string order of the trace id which are stored in ClickHouse and upstream applications.

Let's take an example.

By giving the trace id as **5ff09c5da8c64a1db6c94a073bf0c426**

image

However, when we check the records stored in the opentelementry_span_log table, we can see that the trace id is displayed as **6c94a073bf0c426-5ff09c5da8c64a1db**. Note that the first 16 characters and the last 16 characters are in wrong order with the input id.

image

It's not able for us to link the span logs with upstreaming application's together because of the wrong string order.

## Analysis
Current code uses `readHex` function to parse the trace id. It does parse the string from head of the string to tail as if it treats the input in big-endian order.

But the problem is, it uses a multiply operator `x *= 16` to calculate the value.

image

For the trace id, its underlying data type is `UInt128`, which is actually an array of two `UInt64`. This `UInt128` overrides the `operator *` that it puts the higher 64 bit at index 1 of the array, the lower 64 bit at index 0 of the array.

image

This is why we see the query result of trace id' string order is reversed.

## The implementation of UUIDStringToNum
Actually, the current function `UUIDStringToNum` treats the input string as big-endian order. That means, the index 0 at the underlying UInt64 array stores the higher 64 bit, while the index 1 stores the lower 64 bits. 

This is a correct behavior that it uses totally different string parse logic that differs from the `readHex` function above.
image

## Changes
So, in this PR, I changed the parse logic of trace id, to treat it as big-endian order and stores it as big-endian order, like `UUIDStringToNum` has done.

And original `readHex` is replaced by some `unhex` functions to eliminate code duplication. 
Note that `unhexUInt<128>` is not used to parse trace id because it also stores the higher 64-bits at index 1 of underlying UInt64 array.

After this change, the trace_id that are stored in the span log is in the right string order with input, so that we can easily link the records together by this trace_id.

image

image

### CODE REVIEW

**Comment by evillique** [comment]
@Mergifyio update

**Comment by evillique** [comment]
@Mergifyio update

**Comment by evillique** [comment]
Test `01455_opentelemetry_distributed` is currently failing and needs a correction

**Comment by FrankChen021** [comment]
Now the failures in Integration tests are related to PostgreSQL, they have nothing to do with the changes in this PR.
```
FAILED test_storage_postgresql/test.py::test_concurrent_queries - AssertionEr...
FAILED test_storage_postgresql_replica/test.py::test_clickhouse_restart - Fai...
```

**Comment by FrankChen021** [comment]
Hey @evillique , what should I do now?

**Review by evillique — APPROVED** [review]

**Pull request merged**
