### PR TITLE
Update contribe/orc in .gitmodules

### PR DESCRIPTION
**Pull request by santrancisco**
### Description

I want to start clearing some dependabot alerts - Checked with @Felixoid and for these forked modules, the following steps are necessary to make sure nothing breaks:

- Created a new branch -  https://github.com/ClickHouse/orc/tree/sync_upstream
- Synced the branch with upstream https://github.com/apache/orc 
- Make pull request to ClickHouse/ClickHouse - Checking out submodule and make commits - git 101 lesson from Misha: NOT to change .gitmodule file directly 😆 

### Changelog category (leave one):

- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by robot-ch-test-poll4** [comment]
This is an automated comment for commit a1ad0a5cedfa03fbc690d551a3ba9847648a8ac0 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/50920/a1ad0a5cedfa03fbc690d551a3ba9847648a8ac0/ci_running.html)
The overall status of the commit is 🔴 failure

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🔴 failure</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Comment by nickitat** [comment]
apparently you need to fix our custom cmake for this project. do you need help with that?

**Review by alexey-milovidov — APPROVED** [review]

**Comment by santrancisco** [comment]
> apparently you need to fix our custom cmake for this project. do you need help with that?

Yes please - sorry for adding another task to your plate - it's probably quicker for you to resolve this and I can learn from it than me monkey this up 😓

**Comment by nickitat** [comment]
> > apparently you need to fix our custom cmake for this project. do you need help with that?
> 
> Yes please - sorry for adding another task to your plate - it's probably quicker for you to resolve this and I can learn from it than me monkey this up 😓

this patch should be enough to fix:

``` make
diff --git a/contrib/arrow-cmake/CMakeLists.txt b/contrib/arrow-cmake/CMakeLists.txt
index 16198887075..5fe942d1cd0 100644
--- a/contrib/arrow-cmake/CMakeLists.txt
+++ b/contrib/arrow-cmake/CMakeLists.txt
@@ -116,43 +116,79 @@ configure_file("${ORC_SOURCE_SRC_DIR}/Adaptor.hh.in" "${ORC_BUILD_INCLUDE_DIR}/A
 # ARROW_ORC + adapters/orc/CMakefiles
 set(ORC_SRCS
         "${CMAKE_CURRENT_BINARY_DIR}/orc_proto.pb.h"
-        "${ORC_SOURCE_SRC_DIR}/sargs/ExpressionTree.cc"
-        "${ORC_SOURCE_SRC_DIR}/sargs/Literal.cc"
-        "${ORC_SOURCE_SRC_DIR}/sargs/PredicateLeaf.cc"
-        "${ORC_SOURCE_SRC_DIR}/sargs/SargsApplier.cc"
-        "${ORC_SOURCE_SRC_DIR}/sargs/SearchArgument.cc"
-        "${ORC_SOURCE_SRC_DIR}/sargs/TruthValue.cc"
-        "${ORC_SOURCE_SRC_DIR}/Exceptions.cc"
-        "${ORC_SOURCE_SRC_DIR}/OrcFile.cc"
-        "${ORC_SOURCE_SRC_DIR}/Reader.cc"
+        "${ORC_ADDITION_SOURCE_DIR}/orc_proto.pb.cc"
+        "${ORC_SOURCE_SRC_DIR}/Adaptor.cc"
+        "${ORC_SOURCE_SRC_DIR}/Adaptor.hh.in"
+        "${ORC_SOURCE_SRC_DIR}/BlockBuffer.cc"
+        "${ORC_SOURCE_SRC_DIR}/BlockBuffer.hh"
+        "${ORC_SOURCE_SRC_DIR}/BloomFilter.cc"
+        "${ORC_SOURCE_SRC_DIR}/BloomFilter.hh"
+        "${ORC_SOURCE_SRC_DIR}/Bpacking.hh"
+        "${ORC_SOURCE_SRC_DIR}/BpackingDefault.cc"
+        "${ORC_SOURCE_SRC_DIR}/BpackingDefault.hh"
         "${ORC_SOURCE_SRC_DIR}/ByteRLE.cc"
+        "${ORC_SOURCE_SRC_DIR}/ByteRLE.hh"
+        "${ORC_SOURCE_SRC_DIR}/CMakeLists.txt"
         "${ORC_SOURCE_SRC_DIR}/ColumnPrinter.cc"
         "${ORC_SOURCE_SRC_DIR}/ColumnReader.cc"
+        "${ORC_SOURCE_SRC_DIR}/ColumnReader.hh"
         "${ORC_SOURCE_SRC_DIR}/ColumnWriter.cc"
+        "${ORC_SOURCE_SRC_DIR}/ColumnWriter.hh"
         "${ORC_SOURCE_SRC_DIR}/Common.cc"
         "${ORC_SOURCE_SRC_DIR}/Compression.cc"
+        "${ORC_SOURCE_SRC_DIR}/Compression.hh"
+        "${ORC_SOURCE_SRC_DIR}/ConvertColumnReader.cc"
+        "${ORC_SOURCE_SRC_DIR}/ConvertColumnReader.hh"
+        "${ORC_SOURCE_SRC_DIR}/CpuInfoUtil.cc"
+        "${ORC_SOURCE_SRC_DIR}/CpuInfoUtil.hh"
+        "${ORC_SOURCE_SRC_DIR}/Dispatch.hh"
+        "${ORC_SOURCE_SRC_DIR}/Exceptions.cc"
         "${ORC_SOURCE_SRC_DIR}/Int128.cc"
         "${ORC_SOURCE_SRC_DIR}/LzoDecompressor.cc"
+        "${ORC_SOURCE_SRC_DIR}/LzoDecompressor.hh"
         "${ORC_SOURCE_SRC_DIR}/MemoryPool.cc"
+        "${ORC_SOURCE_SRC_DIR}/Murmur3.cc"
+        "${ORC_SOURCE_SRC_DIR}/Murmur3.hh"
+        "${ORC_SOURCE_SRC_DIR}/Options.hh"
+        "${ORC_SOURCE_SRC_DIR}/OrcFile.cc"
         "${ORC_SOURCE_SRC_DIR}/RLE.cc"
+        "${ORC_SOURCE_SRC_DIR}/RLE.hh"
+        "${ORC_SOURCE_SRC_DIR}/RLEV2Util.cc"
+        "${ORC_SOURCE_SRC_DIR}/RLEV2Util.hh"
         "${ORC_SOURCE_SRC_DIR}/RLEv1.cc"
+        "${ORC_SOURCE_SRC_DIR}/RLEv1.hh"
+        "${ORC_SOURCE_SRC_DIR}/RLEv2.hh"
+        "${ORC_SOURCE_SRC_DIR}/Reader.cc"
+        "${ORC_SOURCE_SRC_DIR}/Reader.hh"
         "${ORC_SOURCE_SRC_DIR}/RleDecoderV2.cc"
         "${ORC_SOURCE_SRC_DIR}/RleEncoderV2.cc"
-        "${ORC_SOURCE_SRC_DIR}/RLEV2Util.cc"
+        "${ORC_SOURCE_SRC_DIR}/SchemaEvolution.cc"
+        "${ORC_SOURCE_SRC_DIR}/SchemaEvolution.hh"
         "${ORC_SOURCE_SRC_DIR}/Statistics.cc"
+        "${ORC_SOURCE_SRC_DIR}/Statistics.hh"
         "${ORC_SOURCE_SRC_DIR}/StripeStream.cc"
+        "${ORC_SOURCE_SRC_DIR}/StripeStream.hh"
         "${ORC_SOURCE_SRC_DIR}/Timezone.cc"
+        "${ORC_SOURCE_SRC_DIR}/Timezone.hh"
         "${ORC_SOURCE_SRC_DIR}/TypeImpl.cc"
+        "${ORC_SOURCE_SRC_DIR}/TypeImpl.hh"
+        "${ORC_SOURCE_SRC_DIR}/Utils.hh"
         "${ORC_SOURCE_SRC_DIR}/Vector.cc"
         "${ORC_SOURCE_SRC_DIR}/Writer.cc"
-        "${ORC_SOURCE_SRC_DIR}/Adaptor.cc"
-        "${ORC_SOURCE_SRC_DIR}/BloomFilter.cc"
-        "${ORC_SOURCE_SRC_DIR}/Murmur3.cc"
-        "${ORC_SOURCE_SRC_DIR}/BlockBuffer.cc"
-        "${ORC_SOURCE_SRC_DIR}/wrap/orc-proto-wrapper.cc"
         "${ORC_SOURCE_SRC_DIR}/io/InputStream.cc"
+        "${ORC_SOURCE_SRC_DIR}/io/InputStream.hh"
         "${ORC_SOURCE_SRC_DIR}/io/OutputStream.cc"
-        "${ORC_ADDITION_SOURCE_DIR}/orc_proto.pb.cc"
+        "${ORC_SOURCE_SRC_DIR}/io/OutputStream.hh"
+        "${ORC_SOURCE_SRC_DIR}/sargs/ExpressionTree.cc"
+        "${ORC_SOURCE_SRC_DIR}/sargs/ExpressionTree.hh"
+        "${ORC_SOURCE_SRC_DIR}/sargs/Literal.cc"
+        "${ORC_SOURCE_SRC_DIR}/sargs/PredicateLeaf.cc"
+        "${ORC_SOURCE_SRC_DIR}/sargs/PredicateLeaf.hh"
+        "${ORC_SOURCE_SRC_DIR}/sargs/SargsApplier.cc"
+        "${ORC_SOURCE_SRC_DIR}/sargs/SargsApplier.hh"
+        "${ORC_SOURCE_SRC_DIR}/sargs/SearchArgument.cc"
+        "${ORC_SOURCE_SRC_DIR}/sargs/SearchArgument.hh"
+        "${ORC_SOURCE_SRC_DIR}/sargs/TruthValue.cc"
         )
```

**Comment by santrancisco** [comment]
Hmmm it's still broken but looking at the log and apache orc code  it seems they have a problem here...

https://github.com/apache/orc/blob/f2c191f9653a5ddbca016e024ca0fb61508f5eeb/c%2B%2B/src/CpuInfoUtil.cc#L475

ArchParseUserSimdLevel is only defined when CPUINFO_ARCH_X86 is set. :-/

**Comment by santrancisco** [comment]
Almost there - the folks looking after apache orc added support for ARMs which cleaned up most of the failed workflow except for powerpc build. i'm asking them for help to add this architect to their build as well. Once they merge the fix, i will update our local fork and merge this pull.

**Review by Felixoid — APPROVED** [review]

**Pull request merged**
