### PR TITLE
Fix race in UDF (follow up)

### PR DESCRIPTION
**Pull request by azat**
Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix race in UDF (follow up for #28211)

*NOTE: maybe it should be marked as `Bug fix` since release branch had been already forked? (and in this case #28211 should also be backported)*

Follow-up for: #28211
Cc: @kitaisreal 
CI: https://clickhouse-test-reports.s3.yandex.net/28396/af3c528dcb58ecbd2493147e7e4d9c3a006713c2/stress_test_(thread).html#fail1

### CODE REVIEW

**Review by alesapin — APPROVED** [review]
Reported it in the internal chat 30 minutes ago...

**Comment by alesapin** [comment]
@mergifyio update

**Comment by alexey-milovidov** [comment]
Yes, it should be backported to 21.9.

**Comment by alesapin** [comment]
How kafka tests related to changes?

**Review by kitaisreal — APPROVED** [review]

**Comment by kitaisreal** [comment]
@alesapin it is broken in master.

**Pull request merged**
