### PR TITLE
Fix small value DateTime64 constant folding in nested subquery for remote

### LINKED ISSUE #50868: Querying ReplicatedSummingMergeTree table through Distribution table with condition on `DateTime64` column with lesser/greater than subquery result returns results only from single shard
**Describe what's wrong**

When querying a table using `ReplicatedSummingMergeTree` engine through Distributed table with condition on `DateTime64` column with lesser/greater than subquery results ClickHouse returns results only from single shard.

Example query:

`select * from gl_test.test_smt_d tsd where dt64 > (select toDateTime64(0, 3, 'UTC'));`

> Not reproducable in [https://fiddle.clickhouse.com/](https://fiddle.clickhouse.com/) as at least two shard are needed and ability to connect with specific one

**Does it reproduce on recent release?**

Unknown I have only access to version `22.8.17.17` 

**How to reproduce**

ClickHouse installation with at least 2 shards.

```sql
create database gl_test ON CLUSTER '{cluster}' ENGINE = Atomic();

-- drop table gl_test.test_smt ON CLUSTER '{cluster}' sync
CREATE TABLE gl_test.test_smt ON CLUSTER '{cluster}' (
    id String,
    dt DateTime('UTC'),
    dt64 DateTime64(3, 'UTC'),
    val Int32
    ) ENGINE ReplicatedSummingMergeTree('/clickhouse/tables/{shard}/gl_test/test_smt', '{replica}', (val))
    PARTITION BY toYYYYMM(dt)
    ORDER BY (cityHash64(id), toDate(dt), val)
    PRIMARY KEY (cityHash64(id), toDate(dt));

-- drop table gl_test.test_smt_d ON CLUSTER '{cluster}' sync
CREATE TABLE gl_test.test_smt_d ON CLUSTER '{cluster}' AS gl_test.test_smt
    ENGINE = Distributed('{cluster}', 'gl_test', test_smt, cityHash64(id));

-- Insert directly to single shard (Alternatively insert using distributed table but then make sure to switch connection to a shard where row is not present)
INSERT INTO gl_test.test_smt
(id, dt, dt64, val)
VALUES('abc', toDateTime(1686036919, 'UTC'), toDateTime64(1686036919.123, 3, 'UTC'), 1);

-- Verify row was inserted
select * from gl_test.test_smt;
-- Expected: 1 row present / Actual: 1 row present

-- Connect to second shard

-- Verify row is not present
select * from gl_test.test_smt;
-- Expected: 0 row present / Actual: 0 row present

-- Verify row can be fetched using distributed table
select * from gl_test.test_smt_d;
-- Expected: 1 row present / Actual: 1 row present

-- Query with condition
select * from gl_test.test_smt_d tsd where dt64 > toDateTime64(0, 3, 'UTC');
-- Expected: 1 row present / Actual: 1 row present

-- Wrap condition in subquery
select * from gl_test.test_smt_d tsd where dt64 > (select toDateTime64(0, 3, 'UTC'));
-- [FAIL] Expected: 1 row present / Actual: 0 row present
```

**Expected behavior**

`select * from gl_test.test_smt_d tsd where dt64 > (select toDateTime64(0, 3, 'UTC'));` will return row from second shard

**Error message and/or stacktrace**

N/A

**Additional context**

I have also tested with different conditional operator and with different column types:

```sql
-- Query with = DateTime64
select * from gl_test.test_smt_d tsd where dt64 = (select toDateTime64(1686036919.123, 3, 'UTC'));
-- [PASS] Expected: 1 row present / Actual: 1 row present

-- Query with DateTime in subquery
select * from gl_test.test_smt_d tsd where dt64 > (select toDateTime(0, 'UTC'));
-- [PASS] Expected: 1 row present / Actual: 1 row present

-- Query with Int32 in subquery
select * from gl_test.test_smt_d tsd where val > (select 0);
-- [PASS] Expected: 1 row present / Actual: 1 row present
```

I have also tested with `ReplicatedMergeTree` engine:

```sql
-- drop table gl_test.test_smt_2 ON CLUSTER '{cluster}' sync
CREATE TABLE gl_test.test_smt_2 ON CLUSTER '{cluster}' (
    id String,
    dt DateTime('UTC'),
    dt64 DateTime64(3, 'UTC'),
    val Int32
    ) ENGINE ReplicatedMergeTree('/clickhouse/tables/{shard}/gl_test/test_smt_2', '{replica}')
    PARTITION BY toYYYYMM(dt)
    ORDER BY (cityHash64(id), toDate(dt), val)
    PRIMARY KEY (cityHash64(id), toDate(dt));

-- drop table gl_test.test_smt_2_d ON CLUSTER '{cluster}' sync
CREATE TABLE gl_test.test_smt_2_d ON CLUSTER '{cluster}' AS gl_test.test_smt_2
    ENGINE = Distributed('{cluster}', 'gl_test', test_smt, cityHash64(id));

INSERT INTO gl_test.test_smt_2
(id, dt, dt64, val)
VALUES('abc', toDateTime(1686036919, 'UTC'), toDateTime64(1686036919.123, 3, 'UTC'), 1);

-- Connect to second shard

-- Verify row is not present
select * from gl_test.test_smt_2;
-- Expected: 0 row present / Actual: 0 row present

-- Verify row can be fetched using distributed table
select * from gl_test.test_smt_2_d;
-- Expected: 1 row present / Actual: 1 row present

-- Query with subquery
select * from gl_test.test_smt_2_d tsd where dt64 > (select toDateTime64(0, 3, 'UTC'));
-- [PASS] Expected: 1 row present / Actual: 1 row present
```

### PR DESCRIPTION
**Pull request by shiyer7474**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fixes https://github.com/ClickHouse/ClickHouse/issues/50868. Small DateTime64 constant values returned by a nested subquery inside a distributed query were wrongly transformed to Nulls, thus causing errors and possible incorrect query results. 

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Run only fuzzers related jobs (libFuzzer fuzzers, AST fuzzers, etc.)
- [ ]  Exclude: AST fuzzers
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by shiyer7474** [comment]
Related :-
PR https://github.com/ClickHouse/ClickHouse/pull/67920 
Issue https://github.com/ClickHouse/ClickHouse/issues/66773

Current PR handles the case of nested subquery inside a remote/distributed query. A nested subquery requires additional check for `Nullable `type in `ConstantNode::toASTImpl()` (the `Nullable `type's inner type could be `DateTime64`). For reference, below is example of AST serialization of nested subquery containing a DateTime64  constant folded value

```
select *, (select toDateTime64(0, 3)) from remote('127.0.0.1', system.one) settings prefer_localhost_replica=0;
|
v
"SELECT `__table1`.`dummy` AS `dummy`, _CAST('0', 'Nullable(DateTime64(0,3))') AS `_subquery_1
` FROM `system`.`one` AS `__table1`"

```

**Comment by robot-clickhouse-ci-2** [comment]
*This is an automated comment for commit b82c231886f2496c01b288a138663c4d430fc7b2 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/68323/b82c231886f2496c01b288a138663c4d430fc7b2/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/3cc2f01df51983092785c0dd503ab64f9e2e8b1f/docs_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Comment by shiyer7474** [comment]
Analyzed the test failures in latest run, they should not be related to this PR :

```
2024-08-19 11:26:18 03221_s3_imds_decent_timeout:                                           [ FAIL ] 7.26 sec.
2024-08-19 18:27:54 01624_soft_constraints:                                                 [ FAIL ] 27.37 sec.
2024-08-19 18:30:56 01290_max_execution_speed_distributed:                                  [ FAIL ] 4.02 sec.
2024-08-19 18:32:27 00653_verification_monotonic_data_load:                                 [ FAIL ] 600.05 sec.
2024-08-19 18:41:46 02944_variant_as_common_type:                                           [ FAIL ] 2.34 sec.
```

Not clear what happened in this test suite -
[**Tests_2 / s (AST fuzzer (asan), fuzzer-unit-tester) / AST fuzzer (asan]**
```

2024-08-19 17:48:42	 + fuzzer_exit_code=143
2024-08-19 17:48:42	 + echo 'Fuzzer exit code is 143'
2024-08-19 17:48:42	 Fuzzer exit code is 143
2024-08-19 17:48:42	 + for _ in {1..100}
2024-08-19 17:48:42	 + clickhouse-client --query 'SELECT 1'
2024-08-19 17:48:46	 1
2024-08-19 17:48:46	 + server_died=0
2024-08-19 17:48:46	 + break
2024-08-19 17:48:46	 + server_exit_code=0
2024-08-19 17:48:46	 + wait 169
2024-08-19 17:48:46	 + stop_server
2024-08-19 17:48:46	 + clickhouse-client --query 'select elapsed, query from system.processes'
2024-08-19 17:48:46	 ch/docker/test/fuzzer/run-fuzzer.sh: line 324: wait: pid 169 is not a child of this shell
2024-08-19 17:48:46	 + server_exit_code=127
2024-08-19 17:48:46	 + echo 'Server exit code is 127'
2024-08-19 17:48:46	 Server exit code is 127
2024-08-19 17:48:46	 + task_exit_code=143
2024-08-19 17:48:46	 + '[' 0 == 1 ']'
2024-08-19 17:48:46	 + '[' 143 == 143 ']'
2024-08-19 17:48:46	 + task_exit_code=0
2024-08-19 17:48:46	 + echo success
2024-08-19 17:48:46	 + echo OK
2024-08-19 17:48:46	 + test -f 'core.*'
2024-08-19 17:48:46	 + dmesg -T
2024-08-19 17:48:46	 + rg -q -F -e 'Out of memory: Killed process' -e 'oom_reaper: reaped process' -e oom-kill:constraint=CONSTRAINT_NONE
2024-08-19 17:48:46	 + :
2024-08-19 17:48:46	 
2024-08-19 17:48:46	 real	30m25.472s
2024-08-19 17:48:46	 user	1m28.159s
2024-08-19 17:48:46	 sys	0m19.928s
2024-08-19 17:48:46	 + CORE_LINK=
2024-08-19 17:48:46	 + '[' -f core.zst ']'
2024-08-19 17:48:46	 + sed -n '/<Fatal>/,/^$/p' server.log
2024-08-19 17:48:46	 + awk '/<Fatal>/ || !/^20/'
2024-08-19 17:48:46	 0.005477	select elapsed, query from system.processes
2024-08-19 17:48:46	 + clickhouse stop
2024-08-19 17:48:50	 + FATAL_LINK=
2024-08-19 17:48:50	 + '[' -s fatal.log ']'
2024-08-19 17:48:50	 + dmesg -T
2024-08-19 17:48:50	 + zstd --threads=0 --rm server.log
2024-08-19 17:48:52	 
                                                                               
Read :  0 / 452 MB ==>  0%
                                                                               
Read : 16 / 452 MB ==>  4%
                                                                               
Read : 40 / 452 MB ==>  5%
                                                                               
Read : 56 / 452 MB ==>  5%
                                                                               
Read : 72 / 452 MB ==>  5%
                                                                               
Read : 96 / 452 MB ==>  4%
                                                                               
Read : 112 / 452 MB ==>  4%
                                                                               
Read : 136 / 452 MB ==>  5%
                                                                               
Read : 152 / 452 MB ==>  4%
                                                                               
Read : 176 / 452 MB ==>  4%
                                                                               
Read : 192 / 452 MB ==>  4%
                                                                               
Read : 208 / 452 MB ==>  4%
                                                                               
Read : 224 / 452 MB ==>  4%
                                                                               
Read : 232 / 452 MB ==>  4%
                                                                               
Read : 256 / 452 MB ==>  4%
                                                                               
Read : 272 / 452 MB ==>  4%zstd: error 27 : Read error : Incomplete read : 474095811 / 474087142 B 
2024-08-19 17:48:52	 
2024-08-19 17:48:52	 real	32m3.128s
2024-08-19 17:48:52	 user	1m39.666s
2024-08-19 17:48:52	 sys	0m30.047s
2024-08-19 17:48:53	 /var/run/clickhouse-server/clickhouse-server.pid file exists and contains pid = 169.
2024-08-19 17:48:53	 The process with pid = 169 is running.
2024-08-19 17:48:53	 Sent terminate signal to process with pid 169.
2024-08-19 17:48:53	 Waiting for server to stop
2024-08-19 17:48:53	 /var/run/clickhouse-server/clickhouse-server.pid file exists and contains pid = 169.
2024-08-19 17:48:53	 The process with pid = 169 is running.
2024-08-19 17:48:53	 Waiting for server to stop
2024-08-19 17:48:53	 /var/run/clickhouse-server/clickhouse-server.pid file exists and contains pid = 169.
2024-08-19 17:48:53	 The process with pid = 169 is running.
2024-08-19 17:48:53	 Waiting for server to stop
2024-08-19 17:48:53	 /var/run/clickhouse-server/clickhouse-server.pid file exists and contains pid = 169.
2024-08-19 17:48:53	 The process with pid = 169 is running.
2024-08-19 17:48:53	 Waiting for server to stop
2024-08-19 17:48:53	 /var/run/clickhouse-server/clickhouse-server.pid file exists and contains pid = 169.
2024-08-19 17:48:53	 The process with pid = 169 is running.
2024-08-19 17:48:53	 Waiting for server to stop
2024-08-19 17:48:53	 /var/run/clickhouse-server/clickhouse-server.pid file exists and contains pid = 169.
2024-08-19 17:48:53	 The process with pid = 169 is running.
2024-08-19 17:48:53	 Waiting for server to stop
2024-08-19 17:48:53	 Found pid = 169 in the list of running processes.
2024-08-19 17:48:53	 The process with pid = 169 is running.
2024-08-19 17:48:53	 Waiting for server to stop
2024-08-19 17:48:53	 Found pid = 1462 in the list of running processes.
2024-08-19 17:48:53	 The process with pid = 1462 is running.
2024-08-19 17:48:53	 Waiting for server to stop
2024-08-19 17:48:53	 Now there is no clickhouse-server process.
2024-08-19 17:48:53	 Server stopped
2024-08-19 17:48:53	 + date
2024-08-19 17:48:53	 Mon Aug 19 05:48:53 PM CEST 2024
2024-08-19 17:48:53	 + sleep 10
2024-08-19 17:49:03	 + jobs
2024-08-19 17:49:03	 + pstree -aspgT
2024-08-19 17:49:03	 bash,1,1 -cset -o pipefail     && cd /workspace     && timeout -s 9 1h /run-fuzzer.sh 2>&1 | ts "$(printf '%%Y-%%m-%%d %%H:%%M:%%S
2024-08-19 17:49:03	   |-run-fuzzer.sh,1442,7 ch/docker/test/fuzzer/run-fuzzer.sh
2024-08-19 17:49:03	   |   `-pstree,1470,7 -aspgT
2024-08-19 17:49:03	   |-tee,9,1 main.log
2024-08-19 17:49:03	   `-ts,8,1 /usr/bin/ts %Y-%m-%d %H:%M:%S\011
INFO:root:Run failed
INFO:root:Result: 'success', 'OK'
Run action done for: [AST fuzzer (asan)]
{}
Error: The operation was canceled.
```

@Avogar Please recommend next step. Can the `AST Fuzzer (ASAN) `be rerun?

**Comment by shiyer7474** [comment]
3 of test failures have been reported earlier  :-

https://github.com/ClickHouse/ClickHouse/issues/67769
https://github.com/ClickHouse/ClickHouse/issues/68579

**Comment by shiyer7474** [comment]
Investigating timeout failure in 00653_verification_monotonic_data_load in :

https://github.com/ClickHouse/ClickHouse/issues/68626

**Comment by shiyer7474** [comment]
Current Status : The 5 Stateless test failures are seen by other PRs also and are flaky tests.  Regarding possible error in "AST fuzzer (asan)", cause is not clear and hopefully should be clear in rerun.

**Comment by shiyer7474** [comment]
For "AST fuzzer (asan)", I see similar run.log on the latest master commit -
https://github.com/ClickHouse/ClickHouse/commit/054b38d4ebeabc33010fb532766f937af2d44c03
https://github.com/ClickHouse/ClickHouse/actions/runs/10478594231/job/29031501110

```
2024-08-20 23:53:19	 + fuzzer_exit_code=143
2024-08-20 23:53:19	 + echo 'Fuzzer exit code is 143'
2024-08-20 23:53:19	 Fuzzer exit code is 143
2024-08-20 23:53:19	 + for _ in {1..100}
2024-08-20 23:53:19	 + clickhouse-client --query 'SELECT 1'
2024-08-20 23:53:19	 1
2024-08-20 23:53:19	 + server_died=0
2024-08-20 23:53:19	 + break
2024-08-20 23:53:19	 + server_exit_code=0
2024-08-20 23:53:19	 + wait 172
2024-08-20 23:53:19	 + stop_server
2024-08-20 23:53:19	 ch/docker/test/fuzzer/run-fuzzer.sh: line 324: wait: pid 172 is not a child of this shell
2024-08-20 23:53:19	 + server_exit_code=127
2024-08-20 23:53:19	 + clickhouse-client --query 'select elapsed, query from system.processes'
2024-08-20 23:53:19	 + echo 'Server exit code is 127'
2024-08-20 23:53:19	 Server exit code is 127
2024-08-20 23:53:19	 + task_exit_code=143
2024-08-20 23:53:19	 + '[' 0 == 1 ']'
2024-08-20 23:53:19	 + '[' 143 == 143 ']'
2024-08-20 23:53:19	 + task_exit_code=0
2024-08-20 23:53:19	 + echo success
2024-08-20 23:53:19	 + echo OK
2024-08-20 23:53:19	 + test -f 'core.*'
2024-08-20 23:53:19	 + dmesg -T
2024-08-20 23:53:19	 + rg -q -F -e 'Out of memory: Killed process' -e 'oom_reaper: reaped process' -e oom-kill:constraint=CONSTRAINT_NONE
2024-08-20 23:53:19	 + :
2024-08-20 23:53:19	 
2024-08-20 23:53:19	 real	30m26.998s
2024-08-20 23:53:19	 user	6m7.908s
2024-08-20 23:53:19	 sys	0m35.591s
2024-08-20 23:53:19	 + CORE_LINK=
2024-08-20 23:53:19	 + '[' -f core.zst ']'
2024-08-20 23:53:19	 + sed -n '/<Fatal>/,/^$/p' server.log
2024-08-20 23:53:19	 + awk '/<Fatal>/ || !/^20/'
2024-08-20 23:53:19	 0.004502	select elapsed, query from system.processes
2024-08-20 23:53:19	 + clickhouse stop
2024-08-20 23:53:21	 + FATAL_LINK=
2024-08-20 23:53:21	 + '[' -s fatal.log ']'
2024-08-20 23:53:21	 + dmesg -T
2024-08-20 23:53:21	 + zstd --threads=0 --rm server.log
2024-08-20 23:53:22	 
                                                                               
Read :  0 / 1288 MB ==>  0%
                                                                               
Read : 332 / 1288 MB ==>  2%
                                                                               
Read : 746 / 1288 MB ==>  2%
                                                                               
Read : 1171 / 1288 MB ==>  2%zstd: error 27 : Read error : Incomplete read : 1351485955 / 1351484431 B 
2024-08-20 23:53:22	 
2024-08-20 23:53:22	 real	31m54.314s
2024-08-20 23:53:22	 user	6m27.256s
2024-08-20 23:53:22	 sys	0m44.719s
2024-08-20 23:53:27	 /var/run/clickhouse-server/clickhouse-server.pid file exists and contains pid = 172.
2024-08-20 23:53:27	 The process with pid = 172 is running.
2024-08-20 23:53:27	 Sent terminate signal to process with pid 172.
2024-08-20 23:53:27	 Waiting for server to stop
2024-08-20 23:53:27	 /var/run/clickhouse-server/clickhouse-server.pid file exists and contains pid = 172.
2024-08-20 23:53:27	 The process with pid = 172 is running.
2024-08-20 23:53:27	 Waiting for server to stop
2024-08-20 23:53:27	 /var/run/clickhouse-server/clickhouse-server.pid file exists and contains pid = 172.
2024-08-20 23:53:27	 The process with pid = 172 is running.
2024-08-20 23:53:27	 Waiting for server to stop
2024-08-20 23:53:27	 /var/run/clickhouse-server/clickhouse-server.pid file exists and contains pid = 172.
2024-08-20 23:53:27	 The process with pid = 172 is running.
2024-08-20 23:53:27	 Waiting for server to stop
2024-08-20 23:53:27	 /var/run/clickhouse-server/clickhouse-server.pid file exists and contains pid = 172.
2024-08-20 23:53:27	 The process with pid = 172 is running.
2024-08-20 23:53:27	 Waiting for server to stop
2024-08-20 23:53:27	 /var/run/clickhouse-server/clickhouse-server.pid file exists and contains pid = 172.
2024-08-20 23:53:27	 The process with pid = 172 is running.
2024-08-20 23:53:27	 Waiting for server to stop
2024-08-20 23:53:27	 /var/run/clickhouse-server/clickhouse-server.pid file exists and contains pid = 172.
2024-08-20 23:53:27	 The process with pid = 172 is running.
2024-08-20 23:53:27	 Waiting for server to stop
2024-08-20 23:53:27	 /var/run/clickhouse-server/clickhouse-server.pid file exists and contains pid = 172.
2024-08-20 23:53:27	 The process with pid = 172 is running.
2024-08-20 23:53:27	 Waiting for server to stop
2024-08-20 23:53:27	 Found pid = 1454 in the list of running processes.
2024-08-20 23:53:27	 The process with pid = 1454 is running.
2024-08-20 23:53:27	 Waiting for server to stop
2024-08-20 23:53:27	 Now there is no clickhouse-server process.
2024-08-20 23:53:27	 Server stopped
2024-08-20 23:53:28	 + date
2024-08-20 23:53:28	 Tue Aug 20 11:53:28 PM CEST 2024
2024-08-20 23:53:28	 + sleep 10
2024-08-20 23:53:38	 + jobs
2024-08-20 23:53:38	 + pstree -aspgT
2024-08-20 23:53:38	 bash,1,1 -cset -o pipefail     && cd /workspace     && timeout -s 9 1h /run-fuzzer.sh 2>&1 | ts "$(printf '%%Y-%%m-%%d %%H:%%M:%%S
2024-08-20 23:53:38	   |-run-fuzzer.sh,1436,7 ch/docker/test/fuzzer/run-fuzzer.sh
2024-08-20 23:53:38	   |   `-pstree,1462,7 -aspgT
2024-08-20 23:53:38	   |-tee,9,1 main.log
2024-08-20 23:53:38	   `-ts,8,1 /usr/bin/ts %Y-%m-%d %H:%M:%S\011
INFO:root:Run failed
INFO:root:Result: 'success', 'OK'
Run action done for: [AST fuzzer (asan)]
{}
```

**Review by Avogar — APPROVED** [review]

**Pull request merged**
