### PR TITLE
Update 01459_manual_write_to_replicas_quorum_detach_attach.sh

### PR DESCRIPTION
**Pull request by tavplubix**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
...

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Run only fuzzers related jobs (libFuzzer fuzzers, AST fuzzers, etc.)
- [ ]  Exclude: AST fuzzers
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-ch-test-poll** [comment]
*This is an automated comment for commit b3e7b0ee11aaf0d8d4b30d4c131f9cb305eb254f with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/69903/b3e7b0ee11aaf0d8d4b30d4c131f9cb305eb254f/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/b858595e54081fedae17bc5a6785bcb4a7794dc2/docs_check.html">✅ success</a></td></tr>
<tr><td>Unit tests</td><td>Runs the unit tests for different release types</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/d87788ec92be11a2bb11f112faadca5f44d1a775/unit_tests__release_.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Review by novikd — APPROVED** [review]

**Comment by tavplubix** [comment]
```
1238589:2024.10.01 03:58:21.552899 [ 29201 ] {0241284c-abe2-45ec-a2c3-bd12481973d0} <Debug> executeQuery: (from [::1]:56376) (comment: 01459_manual_write_to_replicas_quorum_detach_attach.sh) INSERT INTO r2 SELECT 0 (stage: Complete)
1238592:2024.10.01 03:58:21.612036 [ 29201 ] {0241284c-abe2-45ec-a2c3-bd12481973d0} <Trace> Planner: Query to stage Complete
1238594:2024.10.01 03:58:21.617802 [ 29201 ] {0241284c-abe2-45ec-a2c3-bd12481973d0} <Trace> Planner: Query from stage FetchColumns to stage Complete
1238607:2024.10.01 03:58:21.660435 [ 9911 ] {0241284c-abe2-45ec-a2c3-bd12481973d0} <Trace> test_520j53lr.r2 (ebc7fd6f-8bf1-4eed-860a-43814bca4a9d): Trying to reserve 1.00 MiB using storage policy from min volume index 0
1238608:2024.10.01 03:58:21.660959 [ 9911 ] {0241284c-abe2-45ec-a2c3-bd12481973d0} <Trace> DiskLocal: Reserved 1.00 MiB on local disk `default`, having unreserved 123.91 GiB.
1238610:2024.10.01 03:58:21.668372 [ 9911 ] {0241284c-abe2-45ec-a2c3-bd12481973d0} <Trace> MergedBlockOutputStream: filled checksums all_1_1_0 (state Temporary)
1238611:2024.10.01 03:58:21.669747 [ 9911 ] {0241284c-abe2-45ec-a2c3-bd12481973d0} <Debug> test_520j53lr.r2 (ebc7fd6f-8bf1-4eed-860a-43814bca4a9d) (Replicated OutputStream): Wrote block with ID 'all_15750675237126622245_16364948779787000140', 1 rows (quorum 3 of 6 replicas)
1238632:2024.10.01 03:58:21.768455 [ 9911 ] {0241284c-abe2-45ec-a2c3-bd12481973d0} <Trace> test_520j53lr.r2 (ebc7fd6f-8bf1-4eed-860a-43814bca4a9d): Renaming temporary part tmp_insert_all_1_1_0 to all_1_1_0 with tid (1, 1, 00000000-0000-0000-0000-000000000000).
1238640:2024.10.01 03:58:21.783545 [ 9911 ] {0241284c-abe2-45ec-a2c3-bd12481973d0} <Debug> test_520j53lr.r2 (ebc7fd6f-8bf1-4eed-860a-43814bca4a9d): Undoing transaction (1, 1, 00000000-0000-0000-0000-000000000000). Removing parts: all_1_1_0.
1238648:2024.10.01 03:58:21.804458 [ 29201 ] {0241284c-abe2-45ec-a2c3-bd12481973d0} <Error> executeQuery: Code: 286. DB::Exception: Another quorum insert has been already started. (UNSATISFIED_QUORUM_FOR_PREVIOUS_WRITE) (version 24.10.1.890 (official build)) (from [::1]:56376) (comment: 01459_manual_write_to_replicas_quorum_detach_attach.sh) (in query: INSERT INTO r2 SELECT 0), Stack trace (when copying this message, always include the lines below):
1238674:2024.10.01 03:58:21.808450 [ 29201 ] {0241284c-abe2-45ec-a2c3-bd12481973d0} <Error> TCPHandler: Code: 286. DB::Exception: Another quorum insert has been already started. (UNSATISFIED_QUORUM_FOR_PREVIOUS_WRITE), Stack trace (when copying this message, always include the lines below):
1238699:2024.10.01 03:58:21.809476 [ 29201 ] {0241284c-abe2-45ec-a2c3-bd12481973d0} <Debug> TCPHandler: Processed in 0.332448836 sec.
1238700:2024.10.01 03:58:21.810948 [ 29201 ] {0241284c-abe2-45ec-a2c3-bd12481973d0} <Debug> MemoryTracker: Peak memory usage (for query): 3.08 MiB.
```

```
1245303:2024.10.01 03:58:39.535305 [ 65227 ] {7a0cd0e5-84d8-4fd9-900b-ca0d402f712a} <Trace> test_520j53lr.r2 (ebc7fd6f-8bf1-4eed-860a-43814bca4a9d): Starting up table
1245304:2024.10.01 03:58:39.536160 [ 1024 ] {} <Debug> test_520j53lr.r2 (ebc7fd6f-8bf1-4eed-860a-43814bca4a9d): Loading 1 unexpected data parts
1245305:2024.10.01 03:58:39.536856 [ 3050 ] {} <Trace> test_520j53lr.r2 (ebc7fd6f-8bf1-4eed-860a-43814bca4a9d): Loading unexpected part all_1_1_0 from disk default
1245307:2024.10.01 03:58:39.539150 [ 1024 ] {} <Debug> test_520j53lr.r2 (ebc7fd6f-8bf1-4eed-860a-43814bca4a9d): Loaded 1 unexpected data parts
1245462:2024.10.01 03:58:39.994508 [ 1141 ] {} <Debug> test_520j53lr.r2 (ebc7fd6f-8bf1-4eed-860a-43814bca4a9d): Uncovered unexpected parts: all_1_1_0. Restorable unexpected parts: . Missing parts: . Covered unexpected parts: . Expected parts: .
1245463:2024.10.01 03:58:39.995414 [ 1141 ] {} <Error> test_520j53lr.r2 (ReplicatedMergeTreeAttachThread): Initialization failed, table will remain readonly. Error: Code: 231. DB::Exception: The local set of parts of table test_520j53lr.r2 (ebc7fd6f-8bf1-4eed-860a-43814bca4a9d) doesn't look like the set of parts in ZooKeeper: 1.00 rows of 1.00 total rows in filesystem are suspicious. There are 1 uncovered unexpected parts with 1 rows (0 of them is not just-written with 0 rows), 0 missing parts (with 0 blocks), 0 covered unexpected parts (with 0 rows). (TOO_MANY_UNEXPECTED_DATA_PARTS), Stack trace (when copying this message, always include the lines below):

```

```
1345932:2024.10.01 04:08:20.004128 [ 29202 ] {77a439bc-33e5-48e2-a657-80c8c25aff4a} <Error> TCPHandler: Code: 242. DB::Exception: Table is in readonly mode (replica path: /clickhouse/tables/01459_manual_write_to_replicas_quorum_detach_attach_test_520j53lr/r/replicas/r2). (TABLE_IS_READ_ONLY), Stack trace (when copying this message, always include the lines below):
1345993:2024.10.01 04:08:20.404922 [ 29202 ] {5b71de67-0f5f-423c-b21f-020b8f6446c2} <Error> executeQuery: Code: 242. DB::Exception: Table is in readonly mode (replica path: /clickhouse/tables/01459_manual_write_to_replicas_quorum_detach_attach_test_520j53lr/r/replicas/r2). (TABLE_IS_READ_ONLY) (version 24.10.1.890 (official build)) (from [::1]:46906) (comment: 01459_manual_write_to_replicas_quorum_detach_attach.sh) (in query: SYSTEM SYNC REPLICA r2;), Stack trace (when copying this message, always include the lines below):
1346015:2024.10.01 04:08:20.407546 [ 29202 ] {5b71de67-0f5f-423c-b21f-020b8f6446c2} <Error> TCPHandler: Code: 242. DB::Exception: Table is in readonly mode (replica path: /clickhouse/tables/01459_manual_write_to_replicas_quorum_detach_attach_test_520j53lr/r/replicas/r2). (TABLE_IS_READ_ONLY), Stack trace (when copying this message, always include the lines below):
1346049:2024.10.01 04:08:20.786069 [ 29202 ] {7fea70cf-2bf7-424f-8825-64d5e924e908} <Error> executeQuery: Code: 242. DB::Exception: Table is in readonly mode (replica path: /clickhouse/tables/01459_manual_write_to_replicas_quorum_detach_attach_test_520j53lr/r/replicas/r2). (TABLE_IS_READ_ONLY) (version 24.10.1.890 (official build)) (from [::1]:46920) (comment: 01459_manual_write_to_replicas_quorum_detach_attach.sh) (in query: SYSTEM SYNC REPLICA r2;), Stack trace (when copying this message, always include the lines below):
1346071:2024.10.01 04:08:20.792204 [ 29202 ] {7fea70cf-2bf7-424f-8825-64d5e924e908} <Error> TCPHandler: Code: 242. DB::Exception: Table is in readonly mode (replica path: /clickhouse/tables/01459_manual_write_to_replicas_quorum_detach_attach_test_520j53lr/r/replicas/r2). (TABLE_IS_READ_ONLY), Stack trace (when copying this message, always include the lines below):
1346132:2024.10.01 04:08:21.216755 [ 29202 ] {14fddb19-c40b-4e1e-8979-ddbcc181ca3a} <Error> executeQuery: Code: 242. DB::Exception: Table is in readonly mode (replica path: /clickhouse/tables/01459_manual_write_to_replicas_quorum_detach_attach_test_520j53lr/r/replicas/r2). (TABLE_IS_READ_ONLY) (version 24.10.1.890 (official build)) (from [::1]:46922) (comment: 01459_manual_write_to_replicas_quorum_detach_attach.sh) (in query: SYSTEM SYNC REPLICA r2;), Stack trace (when copying this message, always include the lines below):
1346157:2024.10.01 04:08:21.218890 [ 29202 ] {14fddb19-c40b-4e1e-8979-ddbcc181ca3a} <Error> TCPHandler: Code: 242. DB::Exception: Table is in readonly mode (replica path: /clickhouse/tables/01459_manual_write_to_replicas_quorum_detach_attach_test_520j53lr/r/replicas/r2). (TABLE_IS_READ_ONLY), Stack trace (when copying this message, always include the lines below):
1346209:2024.10.01 04:08:21.595563 [ 29202 ] {763191eb-95f7-4e29-b046-54154909814a} <Error> executeQuery: Code: 242. DB::Exception: Table is in readonly mode (replica path: /clickhouse/tables/01459_manual_write_to_replicas_quorum_detach_attach_test_520j53lr/r/replicas/r2). (TABLE_IS_READ_ONLY) (version 24.10.1.890 (official build)) (from [::1]:46934) (comment: 01459_manual_write_to_replicas_quorum_detach_attach.sh) (in query: SYSTEM SYNC REPLICA r2;), Stack trace (when copying this message, always include the lines below):
1346232:2024.10.01 04:08:21.601522 [ 29202 ] {763191eb-95f7-4e29-b046-54154909814a} <Error> TCPHandler: Code: 242. DB::Exception: Table is in readonly mode (replica path: /clickhouse/tables/01459_manual_write_to_replicas_quorum_detach_attach_test_520j53lr/r/replicas/r2). (TABLE_IS_READ_ONLY), Stack trace (when copying this message, always include the lines below):
1346265:2024.10.01 04:08:21.985195 [ 29202 ] {5a6defda-589e-4e6d-8620-6c673e6050b7} <Error> executeQuery: Code: 242. DB::Exception: Table is in readonly mode (replica path: /clickhouse/tables/01459_manual_write_to_replicas_quorum_detach_attach_test_520j53lr/r/replicas/r2). (TABLE_IS_READ_ONLY) (version 24.10.1.890 (official build)) (from [::1]:46936) (comment: 01459_manual_write_to_replicas_quorum_detach_attach.sh) (in query: SYSTEM SYNC REPLICA r2;), Stack trace (when copying this message, always include the lines below):
1346287:2024.10.01 04:08:21.992740 [ 29202 ] {5a6defda-589e-4e6d-8620-6c673e6050b7} <Error> TCPHandler: Code: 242. DB::Exception: Table is in readonly mode (replica path: /clickhouse/tables/01459_manual_write_to_replicas_quorum_detach_attach_test_520j53lr/r/replicas/r2). (TABLE_IS_READ_ONLY), Stack trace (when copying this message, always include the lines below):
1346336:2024.10.01 04:08:22.400790 [ 29202 ] {2de2b992-4ba7-48ee-9c13-56adee864143} <Error> executeQuery: Code: 242. DB::Exception: Table is in readonly mode (replica path: /clickhouse/tables/01459_manual_write_to_replicas_quorum_detach_attach_test_520j53lr/r/replicas/r2). (TABLE_IS_READ_ONLY) (version 24.10.1.890 (official build)) (from [::1]:46952) (comment: 01459_manual_write_to_replicas_quorum_detach_attach.sh) (in query: SYSTEM SYNC REPLICA r2;), Stack trace (when copying this message, always include the lines below):
1346358:2024.10.01 04:08:22.402689 [ 29202 ] {2de2b992-4ba7-48ee-9c13-56adee864143} <Error> TCPHandler: Code: 242. DB::Exception: Table is in readonly mode (replica path: /clickhouse/tables/01459_manual_write_to_replicas_quorum_detach_attach_test_520j53lr/r/replicas/r2). (TABLE_IS_READ_ONLY), Stack trace (when copying this message, always include the lines below):

```

**Comment by tavplubix** [comment]
Well, the fix is wrong

**Comment by alexey-milovidov** [comment]
It didn't help.

**Pull request closed without merging**
