### PR TITLE
Improve workflow jobs

### PR DESCRIPTION
**Pull request by Felixoid**
Changelog category (leave one):
- Build/Testing/Packaging Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
- Create a global ENV per job
- Clean CCACHE after a build is over

Detailed description / Documentation draft:

### CODE REVIEW

**Review by alesapin — APPROVED** [review]

**Comment by alesapin** [comment]
```
The workflow is not valid. .github/workflows/main.yml (Line: 45, Col: 18): Unrecognized named-value: 'runner'. Located at position 1 within expression: runner.temp
```

**Comment by qoega** [comment]
btw, why native env: is bad?

**Comment by Felixoid** [comment]
> btw, why native env: is bad?

It's not preserved through steps and set only for the current step

On other hand, `${{ runner }}` context is not available on the job level.

`We have two APIs: one is deprecated, another one is under heavy development`

**Review by alesapin — APPROVED** [review]

**Comment by alesapin** [comment]
Let's merge, some checks of each type passed.

**Pull request merged**
