### PR TITLE
Translate playground page in ru locale to russian

### PR DESCRIPTION
**Pull request by savinmikhail**
### Changelog category (leave one):
- Documentation (changelog entry is not required)

This doc in 'ru' locale was written in english, I added translation

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]

**Comment by savinmikhail** [comment]
@alexey-milovidov , hi!
Please, help me with CI, it said:
INFO:root:PRs by untrusted users need the 'can be tested' label - please contact a member of the core team

**Comment by robot-ch-test-poll1** [comment]
*This is an automated comment for commit e74892bfaf4aa98654a6253a34bbeb3f1740de41 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/66806/e74892bfaf4aa98654a6253a34bbeb3f1740de41/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Style check</td><td>Runs a set of checks to keep the code style clean. If some of tests failed, see the related log from the report</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/66806/e74892bfaf4aa98654a6253a34bbeb3f1740de41/style_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Comment by savinmikhail** [comment]
@alexey-milovidov , thanks. But now the [Check ready for merge](https://github.com/ClickHouse/ClickHouse/actions/runs/10026210217/job/27712609270?pr=66806) job failed with 
```bash
WARNING: Failed status [Cloud fork sync (only for ClickHouse Inc. employees)], [pending]
```
What can I do about it?

**Comment by alexey-milovidov** [comment]
Nothing, it is a problem for @maxknv, and he is fixing it in https://github.com/ClickHouse/ClickHouse/pull/66822

**Pull request merged**
