### PR TITLE
Improve logging around replicated merges

### PR DESCRIPTION
**Pull request by Algunenano**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Improve logging around replicated merges

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

Add the part id to `MergeFromLogEntryTask` so that logs like these:

```
2022.07.14 06:49:38.081937 [ 363 ] {} <Trace> MergeFromLogEntryTask: Executing log entry to merge parts 2022_0_255_51, 2022_256_256_0, 2022_257_257_0, 2022_258_258_0, 2022_259_259_0, 2022_260_260_0 to 2022_0_260_52
2022.07.14 06:49:38.081957 [ 363 ] {} <Debug> MergeFromLogEntryTask: Don't have all parts (at least part 2022_260_260_0 is missing) for merge 2022_0_260_52; will try to fetch it instead
```

Become something like:
```
2022.07.14 14:12:23.780132 [ 287349 ] {} <Trace> 317b2a80-8cdc-429b-9428-da0dca1f74b9::2022_0_24_9 (MergeFromLogEntryTask): Executing log entry to merge parts 2022_0_23_8, 2022_24_24_0 to 2022_0_24_9
```

This is closer to other logs and include the unique id of the table, which is helpful when there are multiple merges happening which can be confusing because the part names are not unique.

It also adds it to the memory usage log.

Was: `MemoryTracker: Peak memory usage Mutate/Merge: 43.69 MiB.`
Now: `MemoryTracker: Peak memory usage to apply mutate/merge in 7fb924a0-a9fa-4322-9c0e-65f199fac85b::202207_2280_2354_38: 12.38 MiB.`

Finally, since the `template <class Callback>` was getting in the way of moving the constructor to `MergeFromLogEntryTask.cpp` and was useless as there was only one type of callback used, I've replaced it with `IExecutableTask::TaskResultCallback`.

### CODE REVIEW

**Comment by Algunenano** [comment]
Something broke, likely due to the `Callback` change. I'll look into it.

**Comment by Algunenano** [comment]
Build seems broken in master (should be fixed by https://github.com/ClickHouse/ClickHouse/pull/39288)

**Comment by Algunenano** [comment]
@Mergifyio update

**Review by tavplubix — APPROVED** [review]

**Comment by tavplubix** [comment]
Integration tests - #39564
Stress test (address, actions) - #37664

**Pull request merged**
