### PR TITLE
Fix filtering by virtual columns with OR filter in query (resubmit)

### LINKED ISSUE #54779: WHERE-clause with two ORs doesn't evaluate to true
**What's wrong**

Hello. We encountered a regression in some of our queries after upgrading Clickhouse from 23.7 to 23.8. Now, inside a WHERE-clause a three-literal or-clause doesn't get evaluated right if two of the clauses are always false and one is sometimes true.

**Does it reproduce on recent release?**

Every release starting with 23.8

**How to reproduce**

```
CREATE TABLE or_bug (column_1 UInt8) ENGINE=MergeTree ORDER BY column_1;

INSERT INTO TABLE or_bug VALUES (0), (1);

SELECT * FROM or_bug WHERE (column_1 = 1) OR false OR false;

Ok.

0 rows in set. Elapsed: 0.001 sec.
```

Same behavior with fiddle (using versions >= 23.8): https://fiddle.clickhouse.com/424f3fbf-58db-4b3a-b1c8-f4a287a9bf05

**Expected behavior**

Clickhouse should (and did with 23.7) instead return

```
┌─column_1─┐
│        1 │
└───────────
```

**Additional context**

Note that this doesn't happen with `ENGINE=Memory` and only happens with two times "OR false", not one or three times "OR false".

### LINKED ISSUE #55288: Can't get query result with mutiple OR 0 = 1  conditions
**Describe what's wrong**

Can't get result with mutiple false OR conditions

**Does it reproduce on recent release?**
yes

**How to reproduce**

* Which ClickHouse server version to use
the latest TLS  23.8.3.48

* `CREATE TABLE` statements for all tables involved
 ```
CREATE TABLE default.forms
(
    `form_id` FixedString(24),
    `text_field` String
)
ENGINE = MergeTree
PRIMARY KEY form_id
ORDER BY form_id
```
* Sample data for all these tables
```
insert into forms values ('5840ead423829c1eab29fa97','this is a test');
```
* Queries to run that lead to unexpected result
```
 select * from forms where text_field like '%this%' or 0 = 1 or 0 = 1  ;
```
**Expected behavior**
Above query should able to get same result as below query
```
select * from forms where text_field like '%this%' or 0 = 1 ;
```

### PR DESCRIPTION
**Pull request by azat**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix filtering by virtual columns with OR filter in query (_part* filtering for MergeTree, _path/_file for various File/HDFS/... engines, _table for Merge)

The problem with the initial implementation #52653 was:
- OR can have multiple arguments
- It simply not correct to assume that if there are two arguments this is OK.
  Consider the following example:

    "WHERE (column_not_from_partition_by = 1) OR false OR false"

  Will be converted to:

    "WHERE false OR false"

And it will simply read nothing.

Yes, we could apply some optimization for bool, but this will not always
work, since to optimize things like "0 = 1" we need to execute it.

And the only way to make handle this correctly (with ability to ignore
some commands during filtering) is to make is_constant() function return
has it use something from the input block, so that we can be sure, that
we have some sensible, and not just "false".

Plus we cannot simply ignore the difference of the input and output
arguments of handling OR, we need to add always-true (1/true) if the
size is different, since otherwise it could break invariants (see
comment in the code).

P.S. analyzer does not have this bug, since it execute expression as
whole, and this is what filterBlockWithQuery() should do actually
instead, but this will be a more complex patch.

Resubmits: #55418 (due to the test failure it got reverted, this had been addressed in this PR, see last patch) (cc @alexey-milovidov )
Reverts: #55657 (cc @antonio2368 )
Fixes: https://github.com/ClickHouse/ClickHouse/issues/54779 (cc @slanderous-mambo )
Fixes: https://github.com/ClickHouse/ClickHouse/issues/55288 (cc @allen12921)

### CODE REVIEW

**Comment by robot-ch-test-poll1** [comment]
*This is an automated comment for commit b0fbd798089033f03208822a0b750dc1406b039b with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/55678/b0fbd798089033f03208822a0b750dc1406b039b/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td><a href="https://github.com/ClickHouse/ClickHouse/actions/runs/6534709104">✅ success</a></td></tr>
<tbody>
</table>
</details>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/55678/b0fbd798089033f03208822a0b750dc1406b039b/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Comment by azat** [comment]
>Stateless tests (release) — fail: 1, passed: 5739, skipped: 5

- `00002_log_and_exception_messages_formatting` -  @tavplubix zero exceptions had been changed, maybe you will be interested

**Comment by alexey-milovidov** [comment]
@azat a test has failed.

**Comment by azat** [comment]
@alexey-milovidov it is unrelated (see the comment above)

**Pull request merged**
