### PR TITLE
Release pull request for branch 23.8

### PR DESCRIPTION
**Pull request by alexey-milovidov**
This PullRequest is a part of ClickHouse release cycle. It is used by CI system only. Do not perform any changes with it.

### CODE REVIEW

**Comment by robot-ch-test-poll2** [comment]
This is an automated comment for commit d6d170554b77045d051bef82fb3777ed960b2233 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/54187/d6d170554b77045d051bef82fb3777ed960b2233/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Push to Dockerhub</td><td>The check for building and pushing the CI related docker images to docker hub</td><td>🟢 success</td></tr>
</table>

**Comment by Felixoid** [comment]
The fix for kazoo 6f1fbdb5ca30f608bc2038068934cb314a95fa4f is manually cherry-picked from #59337

**Comment by Felixoid** [comment]
I am creating the release from [a278225](https://github.com/ClickHouse/ClickHouse/pull/54187/commits/a278225bba98c092a9b8101e6c02836bbc4d030b) after the builds are finished. Then, the breaking changes made in https://github.com/ClickHouse/ClickHouse/pull/60646 should be fixed

**Comment by Algunenano** [comment]
Pushed the fix for #60646

**Pull request closed without merging**
