### PR TITLE
Rewrite ColumnMap to support dynamic subcolumns

### PR DESCRIPTION
**Pull request by yuzhichang**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Rewrite ColumnMap to support dynamic subcolumns. This is incompatible with existing ColumnMap data. 

```
SET allow_experimental_map_type = 1;

CREATE TABLE test_map (
  dt Date,
  prices Map(Float64)
) ENGINE = MergeTree
ORDER BY dt;

INSERT INTO test_map(dt, prices) VALUES ('2020-01-01', {'banana': 4.2, 'pear': 3.2}), ('2020-01-02', {'apple': 8.3});
SELECT * FROM test_map;
┌─────────dt─┬─prices──────────────────────────────────┐
│ 2020-01-01 │ {'apple':NULL,'banana':4.2,'pear':3.2}  │
│ 2020-01-02 │ {'apple':8.3,'banana':NULL,'pear':NULL} │
└────────────┴─────────────────────────────────────────┘

INSERT INTO test_map(dt, prices) VALUES ('2020-01-09', {'banana': 4.3, 'pear': 3.3, 'apple': 8.4});
SELECT * FROM test_map;
┌─────────dt─┬─prices────────────────────────────────┐
│ 2020-01-09 │ {'apple':8.4,'banana':4.3,'pear':3.3} │
└────────────┴───────────────────────────────────────┘
┌─────────dt─┬─prices──────────────────────────────────┐
│ 2020-01-01 │ {'apple':NULL,'banana':4.2,'pear':3.2}  │
│ 2020-01-02 │ {'apple':8.3,'banana':NULL,'pear':NULL} │
└────────────┴─────────────────────────────────────────┘

// insert rows with new keys
INSERT INTO test_map(dt, prices) VALUES ('2020-01-05', {'mango': 4.3}), ('2020-01-06', {'orange': 8.4});
SELECT * FROM test_map;
┌─────────dt─┬─prices────────────────────────────────┐
│ 2020-01-09 │ {'apple':8.4,'banana':4.3,'pear':3.3} │
└────────────┴───────────────────────────────────────┘
┌─────────dt─┬─prices──────────────────────┐
│ 2020-01-05 │ {'mango':4.3,'orange':NULL} │
│ 2020-01-06 │ {'mango':NULL,'orange':8.4} │
└────────────┴─────────────────────────────┘
┌─────────dt─┬─prices──────────────────────────────────┐
│ 2020-01-01 │ {'apple':NULL,'banana':4.2,'pear':3.2}  │
│ 2020-01-02 │ {'apple':8.3,'banana':NULL,'pear':NULL} │
└────────────┴─────────────────────────────────────────┘

SELECT dt, prices['apple'] FROM test_map ORDER BY dt;
┌─────────dt─┬─arrayElement(prices, 'apple')─┐
│ 2020-01-01 │                          ᴺᵁᴸᴸ │
│ 2020-01-02 │                           8.3 │
└────────────┴───────────────────────────────┘
┌─────────dt─┬─arrayElement(prices, 'apple')─┐
│ 2020-01-05 │                          ᴺᵁᴸᴸ │
│ 2020-01-06 │                          ᴺᵁᴸᴸ │
└────────────┴───────────────────────────────┘
┌─────────dt─┬─arrayElement(prices, 'apple')─┐
│ 2020-01-09 │                           8.4 │
└────────────┴───────────────────────────────┘

SELECT mapBuild('apple', number, 'banana', number * 2, 'pear', number * 3) AS map FROM numbers(3);
┌─map─────────────────────────────┐
│ {'apple':0,'banana':0,'pear':0} │
│ {'apple':1,'banana':2,'pear':3} │
│ {'apple':2,'banana':4,'pear':6} │
└─────────────────────────────────┘


SELECT CAST((['apple', 'banana', 'pear'], [1.0, 2.0, 3.0]), 'Map(Float64)') AS map;
┌─map─────────────────────────────┐
│ {'apple':1,'banana':2,'pear':3} │
└─────────────────────────────────┘


```

Known issues:
- ColumnMap doesn't work with `Log` and `TinyLog` engines due to it's unable to enumerate dynamic streams.
- ColumnMap doesn't support `RENAME` since MergeTreeDataMergerMutator::collectFilesForRenames() doesn't have a IColumn to enumerate its dynamic streams.
- Some stateless test cases are annotated with `FIXME(map)`: `00825_protobuf_format_map.sh`, `01550_create_map_type.sql`, `01651_map_functions.sql`.

### CODE REVIEW

**Comment by yuzhichang** [comment]
@alexey-milovidov, @vitlibar, @CurtizJ This PR is almost ready for merge. Please have someone review it.

**Review by CurtizJ — COMMENTED** [review]
Seems that your solution works only in limited cases. The main problem is that for efficient reading separate map's keys we need to treat them as separate subcolumns and ask storages to read them. Also we need to determine names and types of all queried columns and subcolumns at query analysis stage. There is no mechanism in `StorageInMemoryMetadata` to do that in case of dynamic subcolumns. We are going to implement the support of dynamic subcolumns soon (see #17623 (Nested and semistructured data)). Technically, for type `Map` it's easier to implement that, than for general case of dynamic subcolumns (because type for all values is the same), but still it's not done and it would be better to have one generic implementation for all cases.

In your solution  in case of `MergeTree` with wide parts, in which every key should be written to own file, you can successfully write keys, but will fail to read them later. It can be proven by following example:
```sql
CREATE TABLE t (m Map(Int)) ENGINE = MergeTree ORDER BY tuple() SETTINGS min_bytes_for_wide_part = 0;
INSERT INTO t VALUES ({'a' : 1, 'b' : 2});
SELECT * FROM t;

┌─m───────────────────┐
│ {'a':NULL,'b':NULL} │
└─────────────────────┘

SELECT m['a'] FROM t;

┌─arrayElement(m, 'a')─┐
│                 ᴺᵁᴸᴸ │
└──────────────────────┘
```

It happens because we try to read column with name `m`, but fail and then fill values by defaults. 

Also, it's not a ClickHouse way to make implicit conversaion to `Nullable`, because this type requires some overhead. If users want to use `Nullable` they should to set it explicitly.

Maybe we can hold this PR, until some support of dynamic subcolumns will be implemented?

**Comment by yuzhichang** [comment]
I'm excited to see more generic design from you. Do you think I can help on some part of that?

**Comment by CurtizJ** [comment]
When it will be introduced, I think, you can continue with this PR and help with `Map` type.

**Pull request closed without merging**
