### PR TITLE
Fix ccache [4.0, 4.2) (RULE_LAUNCH_COMPILE/RULE_LAUNCH_LINK was incorrect)

### PR DESCRIPTION
**Pull request by azat**
Before the compilation contains ccache twice:

    env -u SOURCE_DATE_EPOCH /usr/bin/ccache prlimit --as=10000000000 --data=5000000000 --cpu=600 /usr/bin/ccache /usr/bin/clang++-11

So remove ccache from RULE_LAUNCH_COMPILE/RULE_LAUNCH_LINK

Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by azat** [comment]
>ClickHouse build check — 13/14 builds are OK

#28846

**Comment by alexey-milovidov** [comment]
master: 0:04:33 | clickhouse
this PR: 0:16:46 | clickhouse

Need clarifications.

**Review by alexey-milovidov — CHANGES_REQUESTED** [review]
.

**Comment by azat** [comment]
> master: 0:04:33 | clickhouse
> this PR: 0:16:46 | clickhouse
>
> Need clarifications.

- pr submitted at 2021-09-10 8:47 MSK
- [build](https://clickhouse-builds.s3.yandex.net/28845/ba7918886f79afa549c6e3bcf9b8f7beb89937df/clickhouse_build_check/build_1631254493.out.log) started at 2021-09-10 9:14 MSK
- [build](https://clickhouse-builds.s3.yandex.net/0/25a27978e6c09ecb691a98068ec4497a589fee73/clickhouse_build_check/build_1631227114.out.log) for the base commit in upstream/master (25a27978e6c09ecb691a98068ec4497a589fee73) finished at 2021-09-10 01:38 MSK
- docker images are the same
- VERSION_STRING had been changed (this patch - 21.11.1.8045, base commit - 21.11.1.8044), but I don't see that it should affects ~1533 units.
- also there is some difference in ccache `stats updated` (for this PR before compiling - `Fri Sep 10 00:33:35 2021`, for the commit in upstream/master after build - `Thu Sep  9 22:42:43 2021`)

So I don't see how it is possible, maybe ccache cache had been overwritten from another build? Or maybe artifacts wasn't copied yet? (Actually the commit in upstream/master was 5b61e6275b3f5abf22a34d7867efad3674ec0c6c, but that was documentation, and even though it does not run build check, maybe it doing something with the ccache cache (i.e. fasttest build overrides them)?)

<details>

```
Sep 10 06:31:37 + ccache --show-stats
Sep 10 06:31:37 cache directory                     /ccache
Sep 10 06:31:37 primary config                      /ccache/ccache.conf
Sep 10 06:31:37 secondary config      (readonly)    /etc/ccache.conf
Sep 10 06:31:37 stats updated                       Fri Sep 10 06:31:29 2021
Sep 10 06:31:37 stats zeroed                        Fri Sep 10 06:16:50 2021
Sep 10 06:31:37 cache hit (direct)                  7363
Sep 10 06:31:37 cache hit (preprocessed)              21
Sep 10 06:31:37 cache miss                          1533 <!--
Sep 10 06:31:37 cache hit rate                     82.81 %
Sep 10 06:31:37 called for link                      415
Sep 10 06:31:37 called for preprocessing             228
Sep 10 06:31:37 unsupported code directive             1
Sep 10 06:31:37 no input file                         46
Sep 10 06:31:37 cleanups performed                     4
Sep 10 06:31:37 files in cache                     44979
Sep 10 06:31:37 cache size                          13.6 GB
Sep 10 06:31:37 max cache size                      15.0 GB
```

</details>

But this should be related, since you have ccache 3.7 on CI and this patch does not affect it.

**Comment by alexey-milovidov** [comment]
Need help from @alesapin

**Comment by alexey-milovidov** [comment]
@mergifyio update

**Comment by alesapin** [comment]
It cannot be related to changes. And I see that cache is used almost all the times. Let's merge to master and revert if something went wrong.

**Review by alesapin — APPROVED** [review]

**Pull request merged**
