### PR TITLE
Fix vanilla GCC compilation in macOS

### PR DESCRIPTION
**Pull request by traceon**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category:
- Not for changelog

Changelog entry:
- None

Detailed description:
- Various fixes that make compilation pass in macOS when a vanilla (Homebrew's) GCC is used as a compiler

### CODE REVIEW

**Comment by abyss7** [comment]
What is a purpose for GCC support on MacOS? We don't check it in our CI and it will break eventually.
Also @alexey-milovidov I don't think that it's a good idea to make changes to submodules just for compliance with GCC+Darwin compilability - we'll have to maintain those changes in future when doing merges with upstream, without possibility to check if they still build.

**Comment by traceon** [comment]
@abyss7 any macos build breaks eventually as far as compilation is considered, because cross-compiling for macos is far from reproducing the real environment - you can see that by looking at the trend of the reported issues for mac compilation. The purpose for this PR is mainly to make sure that the code is portable again. At least until next time.

**Comment by traceon** [comment]
Also, vanilla clang in macos is just equally unpopular and marginal as gcc.

**Comment by abyss7** [comment]
> Also, vanilla clang in macos is just equally unpopular and marginal as gcc.

Yes, I know, that's why we suggest to use LLVM based version in our instruction.

**Comment by abyss7** [comment]
> because cross-compiling for macos is far from reproducing the real environment - you can see that by looking at the trend of the reported issues for mac compilation.

That is unfortunate and unexpected in some way. The most of issues I saw relates to Apple Clang, which we don't support. Can you point out any example of difference in compilation on real Darwin vs cross-build using LLVM Clang?

**Comment by traceon** [comment]
> Yes, I know, that's why we suggest to use LLVM based version in our instruction.

By "vanilla" I mean exactly LLVM, usually installed through Homebrew package manager. In macOS, the native considered to be AppleClang.

**Comment by traceon** [comment]
> Can you point out any example of difference in compilation on real Darwin vs cross-build using LLVM Clang?

There are many of them, one that comes to my mind first is `mig` (Mach Interface Generator) not available in Linux, required for Kerberos compilation under mac. There are many discrepancies in things that can be formally compiled too. It is strange that you recommend (if you do) such cross-compiled binary for production use.

**Comment by traceon** [comment]
So a solution to inability to cover all platforms seems to be sticking to writing portable code, and building it in a portable way. This PR is improvement on that front.

**Comment by abyss7** [comment]
> There are many of them, one that comes to my mind first is `mig` (Mach Interface Generator) not available in Linux, required for Kerberos compilation under mac. There are many discrepancies in things that can be formally compiled too. It is strange that you recommend (if you do) such cross-compiled binary for production use.

I don't recommend to use cross-compiled binary - that's not the point. I just don't pay too much attention to current situation about MacOS problems, but I'm interested to find out if there is something fundamentally wrong with our cross-build: because it costs us some computational resources.

The point is - to stick with a single supported way of building Darwin version of ClickHouse, which we can afford to test with our CI. Right now if there are any discrepancies between cross-build and native build with vanilla (LLVM) Clang, then it's worth an effort to eliminate them - and not just try to maintain some custom builds without CI support.

> By "vanilla" I mean exactly LLVM, usually installed through Homebrew package manager. In macOS, the native considered to be AppleClang.

Now I got your point - you were referring to LLVM-version as an unpopular one.

**Comment by traceon** [comment]
> The point is - to stick with a single supported way of building Darwin version of ClickHouse, which we can afford to test with our CI.

I don't think anyone will every try cross-compiling for macOS on their own, if any other way of building it natively exist. People will rather report a problem as an issue in github, than resort to cross-compiling. In this sense, the coverage that is in the CI right now doesn't really cover most of the use cases.

If you are serious about supporting macOS build, it makes sense to have a normal macOS system and make AppleClang build, as the most "native" one.

**Comment by abyss7** [comment]
> I don't think anyone will ever try cross-compiling for macOS on their own, if any other way of building it natively exist. People will rather report a problem as an issue in github, than resort to cross-compiling. In this sense, the coverage that is in the CI right now doesn't really cover most of the use cases.

Still, I don't recommend people to resort from native build to cross build - we just want to have an automated support of at least a vanilla Clang+Darwin build by means of our cross-build. If someone tells us that LLVM Clang build doesn't work on real MacOS, but our CI is "green" - that's the problem. But if you try to make some fixes for your custom build - that's pointless, because it will eventually break. I don't mind to merge your current fixes - we can't even test them - but the whole idea doesn't sound good.

> If you are serious about supporting macOS build, it makes sense to have a normal macOS system and make AppleClang build, as the most "native" one.

Actually, that's the real possibility in not-so-distant future.

**Comment by alexey-milovidov** [comment]
I agree - these fixes will eventually break and we cannot support them.
But this PR is still good to merge. At least to make more developers happy.
The amount of harm (unsupported modifications in libraries) is minimal and it's easy to revert if needed.

**Comment by alexey-milovidov** [comment]
> AST fuzzer (UBSan) — ../src/Common/FieldVisitors.h:193:22: runtime error: 3.40282e+38 is outside the range of representable values of type 'unsigned long' 

#22943

**Review by alexey-milovidov — APPROVED** [review]

**Pull request merged**
