### PR TITLE
(feature) Use Map data type for system logs tables

### LINKED ISSUE #18698: Use Map data type for system logs tables.
**Use case**
For `Settings` and `ProfileEvents` fields in `query_log` and `query_thread_log`.
So you don't have to write `ProfileEvents.Values[indexOf(ProfileEvents.Names, 'FileOpen')]` anymore.
It should work as `ProfileEvents['FileOpen']`.

**Implementation**
Just replace the type.
No need to worry about compatibility.

### PR DESCRIPTION
**Pull request by sundy-li**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Backward Incompatible Change

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Backward Incompatible Change:
- Use Map data type for system logs tables (system.query_log, system.query_thread_log, system.processes, system.OpenTelemetrySpanLog).
These tables will be auto created with new datatypes, old queries maybe incompatible.

Detailed description / Documentation draft:

...

closes #18698

### CODE REVIEW

**Comment by sundy-li** [comment]
Some tests use `WHERE has(ProfileEvents.Names, 'OSCPUVirtualTimeMicroseconds')`.
we can change it to `ProfileEvents['OSCPUVirtualTimeMicroseconds'] > 0`.

But I think we should add `mapContains(map, key)` function first.

**Comment by alexey-milovidov** [comment]
Ok, let's add this function.

**Comment by hexiaoting** [comment]
> Ok, let's add this function.

added. https://github.com/ClickHouse/ClickHouse/pull/18788

**Comment by alexey-milovidov** [comment]
@sundy-li Let's change the tests and continue.

**Comment by sundy-li** [comment]
> @sundy-li Let's change the tests and continue.

Ok， after #18788 is merged.

**Comment by qoega** [comment]
Looks great! But later we should not forget to add backward incompatible change to changelog if we change default behavior for this tables. Am I right that old behavior without enabled new flag will no longer br checked in tests after this PR?

**Comment by sundy-li** [comment]
> Looks great! But later we should not forget to add backward incompatible change to changelog if we change default behavior for this tables. Am I right that old behavior without enabled new flag will no longer br checked in tests after this PR?

No, old behavior will not be compatible after this PR, because we already change the datatype to Map. It's for system tables. It's global, but `allow_experimental_map_type` is for each separated queries.

**Comment by sundy-li** [comment]
Failed tests are not related, ready to review. cc @alexey-milovidov @qoega

**Comment by alexey-milovidov** [comment]
Test failures are related somehow: https://clickhouse-test-reports.s3.yandex.net/18762/0d2d2dc2ed06ea70274a384846e2d421ea0f0b9e/functional_stateless_tests_flaky_check_(address).html#fail1

**Comment by sundy-li** [comment]
continue in #23934

**Pull request closed without merging**
