### PR TITLE
Map type serializeTextJSON never uses spark output format

### PR DESCRIPTION
**Pull request by zhanglistar**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Since `composed_data_type_output_format_mode=spark` only is for display text, it should not be used in `serializeTextJSON`, which may affect`toJSONString`. For example:
`SELECT toJSONString(map('key1', 1, 'key2', 2)) SETTINGS composed_data_type_output_format_mode = 'spark';`
Output:
`{"key1" -> 1, "key2" -> 2}`
Which is an invalid json string.

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing)

All builds in Builds_1 and Builds_2 stages are always mandatory
and will run independently of the checks below:

- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64
- [ ]  Exclude: All with release
- [ ]  Exclude: All with debug
---
- [ ]  Run only fuzzers related jobs (libFuzzer fuzzers, AST fuzzers, etc.)
- [ ]  Exclude: AST fuzzers
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-ch-test-poll** [comment]
*This is an automated comment for commit a399b53b27219f907b22dfac251adc0c2d52f7f8 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/73845/a399b53b27219f907b22dfac251adc0c2d52f7f8/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/a9c1f9e08c236e9ad30d694d9daa970b526d08d7/docs_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Comment by zhanglistar** [comment]
@vitlibar Please take a look if you have time, thanks.

**Review by alexey-milovidov — CHANGES_REQUESTED** [review]
Looks ugly, because it can negatively affect performance.

**Comment by zhanglistar** [comment]
> Looks ugly, because it can negatively affect performance.

@alexey-milovidov OK, we process this diff outside, and help to revert https://github.com/ClickHouse/ClickHouse/pull/70957.

**Pull request closed without merging**
