### PR TITLE
Fix memory leak of aggregate function states

### PR DESCRIPTION
**Pull request by azat**
Changelog category (leave one):
- Not for changelog

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix memory leak of aggregate function states

Fixes: #19407
Cc: @templarzq 
Cc: @alexey-milovidov (this also looks significant for upcoming release)

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
I have missed #19407, maybe @CurtizJ can help to review the fix?

**Comment by templarzq** [comment]
yes,there are mem leaks if not all of the data are copied.

**Comment by alexey-milovidov** [comment]
I will temporarily revert #19407 so we can make the next release without a fear.

**Comment by azat** [comment]
>I will temporarily revert #19407 so we can make the next release without a fear.

Sounds reasonable (and just FYI that PR introduces pretty huge leak, if aggregate functions is in use, so this looks like a major problem)

**Comment by alexey-milovidov** [comment]
The question is - how to improve our CI to detect these kind of issues automatically.

**Comment by alexey-milovidov** [comment]
#21024

**Comment by azat** [comment]
>The question is - how to improve our CI to detect these kind of issues automatically.

Indeed, by some reason ASan does not detect this leak, it may be related to #937

I've found one case when gcc-10 ASan does find leak, while clang-11/12 doesn't:

```c
#include <cstdlib>

int main(int argc, char ** argv)
{
        int * foo = static_cast<int *>(malloc(sizeof(int)));
        if (reinterpret_cast<unsigned long>(foo) > 0xffff)
                *foo = 2;
        else
                *foo = 3;
        return (*foo == 2);
}
```

```
$ clang++-11 -g3 -fno-omit-frame-pointer -fsanitize=address -O0 -o /tmp/test23 /tmp/test23.cpp; /tmp/test23
$ g++-10 -g3 -fno-omit-frame-pointer -fsanitize=address -O0 -o /tmp/test23 /tmp/test23.cpp; /tmp/test23

=================================================================
==11340==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 4 byte(s) in 1 object(s) allocated from:
    #0 0x7f0842ca9e8f in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x55ab535f818d in main /tmp/test23.cpp:5
    #2 0x7f0842a63e0a in __libc_start_main ../csu/libc-start.c:308

SUMMARY: AddressSanitizer: 4 byte(s) leaked in 1 allocation(s).
```

I'm trying to compile with ASan and gcc-10, but there are some issues

**Comment by azat** [comment]
>I'm trying to compile with ASan and gcc-10, but there are some issues

gcc10 also does not find anything

**Comment by alexey-milovidov** [comment]
@azat So, this PR rendered irrelevant, but let's commit the test if it makes sense.

**Comment by alexey-milovidov** [comment]
But it does not trigger anything in CI, so it does not make sense.

**Comment by azat** [comment]
>But it does not trigger anything in CI, so it does not make sense.

Yes, since this PR contains fix too, and it will not trigger any issue in upstream too since the original problem had been reverted, but maybe it still worth adding this test.

**Pull request closed without merging**
