### PR TITLE
Implement L2 Squared Distance and Norm for array and tuples.

### PR DESCRIPTION
**Pull request by julianzq**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Added L2 Squared distance and norm for both arrays and tuples.

Created as requested by @alexey-milovidov in PR #38259 (AVX implementation for L2 distances).

Those new functions are consistent with the other norm and distance functions for tuples and arrays.

The motivation for this PR is to be consistent with popular vector libraries like FAISS which avoid using square root when computing L2 as there is no practical need for it when comparing distances.

### CODE REVIEW

**Comment by israelg99** [comment]
Seems like the failing tests are flaky.

**Comment by israelg99** [comment]
@davenger This should be a straightforward PR, but it would be great if you can check out https://github.com/ClickHouse/ClickHouse/pull/38259 (AVX L2 distance) so we can discuss on how to integrate it into our current distance functions.

**Comment by davenger** [comment]
@israelg99 we just found an issue with the stress tests: they were failing to start for several hours, then timed out and didn't report this a failure.
I'm waiting for this fix #38680 to restart the tests.

**Comment by israelg99** [comment]
@davenger sounds good

**Comment by davenger** [comment]
@mergifyio update

**Review by davenger — APPROVED** [review]

**Pull request merged**
