### PR TITLE
Fix invalid memory access in BLAKE3 (Rust)

### LINKED ISSUE #57810: MSan: use-of-uninitialized-value in FunctionStringHashFixedString<DB::ImplBLAKE3>
https://s3.amazonaws.com/clickhouse-test-reports/57749/5abeadf20fbe3f3697d60504ae6ae53b9f653900/fuzzer_astfuzzermsan/report.html

**Describe the bug**
MSan warning - https://pastila.nl/?00113157/a95e8c835463f215fcdc9883103e8368#EjjE1lcyaeOHX5AkrJGaJA==

```
SELECT
    'a\0aaaaaaaaaaa\0a012345789,.!aaaaa\0aaaaaaaaaaa\0a012345789,.!aaaaa\0aaaaaaaaaaa\0a012345789,.!aaaaa\0aaaaaaaaaaa\0a012345789,.!aaaaa\0aaaaaaaaaaa\0a012345789\0.!aaaaa\0aaaaaaaaaaa\0a012345789,.!aaaaa\0aaaaaaaaaaa\0a012345789,.!aaaaa\0aaaaaaaaaaa\0a012345789,.!aaaa',
    lowerUTF8(hex(BLAKE3(BLAKE3('\0est_1')), hex(BLAKE3('')), BLAKE3(''), BLAKE3('test_1test_1test_1test_1test_1tes\nt_1test_1test_1test_1test_1test_1test_1test_1test_\0test_1test_1'), BLAKE3('test_3'), BLAKE3('')), '' AS str) = str,
    lowerUTF8(str) = str
```

### PR DESCRIPTION
**Pull request by Algunenano**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
- Fix invalid memory access in BLAKE3

### Documentation entry for user-facing changes

If you don't control your sizes, you get invalid memory accesses (for FixedString that aren't NULL terminated).

Closes https://github.com/ClickHouse/ClickHouse/issues/57810
PS: Look mum, I'm a rust developer.

### CODE REVIEW

**Comment by robot-clickhouse-ci-2** [comment]
*This is an automated comment for commit 3343d59f8025edb75e58a710d2147694979ea978 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/57876/3343d59f8025edb75e58a710d2147694979ea978/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td><a href="https://github.com/ClickHouse/ClickHouse/actions/runs/7212646708">✅ success</a></td></tr>
<tbody>
</table>
</details>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/57876/3343d59f8025edb75e58a710d2147694979ea978/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Comment by Algunenano** [comment]
Failures:
* `Bugfix validate check` -> It reproduces via MSAN.
* `AST fuzzer (ubsan)` -> Investigating
* `Integration tests (asan) [3/4] ` -> `test_storage_hdfs` leak. Already fixed in master (https://github.com/ClickHouse/ClickHouse/pull/57860)
* `Integration tests (asan) [4/4]` -> `test_storage_azure_blob_storage` -> https://github.com/ClickHouse/ClickHouse/pull/57895
* `Integration tests (release) [4/4]` -> `test_storage_azure_blob_storage` again
* `Integration tests (tsan) [6/6]` -> `test_postgresql_replica_database_engine_1/test.py::test_many_concurrent_queries`. Already fixed in master (https://github.com/ClickHouse/ClickHouse/pull/57863)

**Comment by alexey-milovidov** [comment]
Thank you!

FYI, the BLAKE3 integration was in Rust only to introduce Rust to the build system.
But we don't require it to be in Rust, and it is actually unreasonable.
After we have other code in Rust, the initial motivation no longer matters.
There is BLAKE3 implementation inside LLVM, and also another library for it.

**Comment by Algunenano** [comment]
Let's try removing it then -> https://github.com/ClickHouse/ClickHouse/pull/57994

**Pull request merged**
