### PR TITLE
Avx enablement

### PR DESCRIPTION
**Pull request by rschu1ze**
### Changelog category (leave one):
- Build/Testing/Packaging Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Prebuild ClickHouse x86 binaries now require support for AVX instructions, i.e. a CPU not older than Intel Sandy Bridge / AMD Bulldozer, both released in 2011

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]

**Comment by rschu1ze** [comment]
Some queries, e.g. `SELECT sum(toFloat32(number)) FROM numbers(100000000)` became slower after enabling AVX, for this particular query by ca. 30%. I could also reproduce the regression locally. Tried to investigate using "perf" but then found out that my EC2 instance type "c6i.8xlarge" doesn't support Intel Hardware Performance Counters [0]. Getting myself one of the instance types ("c5.9xlarge") where performance counters are supposedly enabled.

[0] https://oavdeev.github.io/posts/vpmu_support_z1d/

**Comment by rschu1ze** [comment]
After some quite painful investigation using perf & lldd, I think I found the problem (at least one of them ...). Clang's auto-vectorized cast-to-Float32 code (FunctionsConversion.h) is slower when AVX is enabled. Float64 is interestingly not affected.

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
Ok. There is no improvement in performance, but let's merge just to move forward.

**Comment by alexey-milovidov** [comment]
There is at least one complaint: #40437
Let's revert, because the advantages are currently zero.

**Pull request merged**
