### PR TITLE
Find and replace every occurrence of CONDITION_PLACEHOLDER_TO_REPLACE_VALUE 

### PR DESCRIPTION
**Pull request by ivanov17andrey**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Using a dictionary with `update_field` and explicitly provided `{condition}` replace every occurrence, not the first one only.

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

---
### Modify your CI run:
**NOTE:** If your merge the PR with modified CI you **MUST KNOW** what you are doing
**NOTE:** Checked options will be applied if set before CI RunConfig/PrepareRunConfig step

#### Include tests (required builds will be added automatically):
- [ ]  Fast test
- [ ]  Integration Tests
- [ ]  Stateless tests
- [ ]  Stateful tests
- [ ]  Unit tests
- [ ]  Performance tests
- [ ]  All with ASAN
- [ ]  All with TSAN
- [ ]  All with Analyzer
- [ ]  Add your option here

#### Exclude tests:
- [ ]  Fast test
- [ ]  Integration Tests
- [ ]  Stateless tests
- [ ]  Stateful tests
- [ ]  Performance tests
- [ ]  All with ASAN
- [ ]  All with TSAN
- [ ]  All with MSAN
- [ ]  All with UBSAN
- [ ]  All with Coverage
- [ ]  All with Aarch64
- [ ]  Add your option here

#### Extra options:
- [ ]  do not test (only style check)
- [ ]  disable merge-commit (no merge from master before tests)
- [ ]  disable CI cache (job reuse)

#### Only specified batches in multi-batch jobs:
- [ ]  1
- [ ]  2
- [ ]  3
- [ ]  4

### CODE REVIEW

**Comment by ivanov17andrey** [comment]
In the case of subselects, I want to filter source data, not the result, otherwise it spends more resources.

What I need to use:
```
CREATE OR REPLACE DICTIONARY marketdata.prices_eth_dict
    (
    Address_Hash UInt64,
    Price_Time DateTime,
    Price_Time_End DateTime,
    Price_Amount Float32
    )
    PRIMARY KEY Address_Hash
    SOURCE (CLICKHOUSE(
         USER '${CLICKHOUSE_USER}' PASSWORD '${CLICKHOUSE_PASSWORD}'
         update_field 'Price_Time'
         QUERY 'SELECT Address_Hash,
                       Price_Time,
                       Price_Time_End,
                       Price_Amount
                FROM (SELECT Address_Hash,
                             Price_Time,
                             Price_Time + INTERVAL ${DICTIONARY_TOP_TOKENS_PRICE_LIFESPAN} AS Price_Time_End,
                             toFloat32(Price_Amount) AS Price_Amount,
                             toStartOfInterval(Price_Time, INTERVAL ${DICTIONARY_TOP_TOKENS_PRICE_INTERVAL}) AS Price_Time_Interval
                      FROM marketdata.prices_eth
                      WHERE Address_Hash = cityHash64(\'\')
                            OR Address_Hash = cityHash64(\'dac17f958d2ee523a2206206994597c13d831ec7\')
                            OR Address_Hash = cityHash64(\'b8c77482e45f1f44de1745f52c74426c631bdd52\')
                            OR Address_Hash = cityHash64(\'ae7ab96520de3a18e5e111b5eaab095312d7fe84\')
                            OR Address_Hash = cityHash64(\'a0b86991c6218b36c1d19d4a2e9eb0ce3606eb48\')
                            OR Address_Hash = cityHash64(\'95ad61b0a150d79219dcf64e1e6cc01f0b64c4ce\')
                            OR Address_Hash = cityHash64(\'582d872a1b094fc48f5de31d3b73f2d9be47def1\')
                            OR Address_Hash = cityHash64(\'514910771af9ca656af840dff83e8264ecf986ca\')
                            OR Address_Hash = cityHash64(\'2260fac5e5542a773aa44fbcfedf7c193bc2c599\')
                            OR Address_Hash = cityHash64(\'7d1afa7b718fb893db30a3abc0cfc608aacfebb0\')
                      UNION ALL
                      SELECT Address_Hash,
                             Price_Time,
                             Price_Time + INTERVAL ${DICTIONARY_REGULAR_TOKENS_PRICE_LIFESPAN} AS Price_Time_End,
                             toFloat32(Price_Amount) AS Price_Amount,
                             toStartOfInterval(Price_Time, INTERVAL ${DICTIONARY_REGULAR_TOKENS_PRICE_INTERVAL}) AS Price_Time_Interval
                      FROM marketdata.prices_eth
                      WHERE Address_Hash != cityHash64(\'\')
                            AND Address_Hash != cityHash64(\'dac17f958d2ee523a2206206994597c13d831ec7\')
                            AND Address_Hash != cityHash64(\'b8c77482e45f1f44de1745f52c74426c631bdd52\')
                            AND Address_Hash != cityHash64(\'ae7ab96520de3a18e5e111b5eaab095312d7fe84\')
                            AND Address_Hash != cityHash64(\'a0b86991c6218b36c1d19d4a2e9eb0ce3606eb48\')
                            AND Address_Hash != cityHash64(\'95ad61b0a150d79219dcf64e1e6cc01f0b64c4ce\')
                            AND Address_Hash != cityHash64(\'582d872a1b094fc48f5de31d3b73f2d9be47def1\')
                            AND Address_Hash != cityHash64(\'514910771af9ca656af840dff83e8264ecf986ca\')
                            AND Address_Hash != cityHash64(\'2260fac5e5542a773aa44fbcfedf7c193bc2c599\')
                            AND Address_Hash != cityHash64(\'7d1afa7b718fb893db30a3abc0cfc608aacfebb0\')
                )
                WHERE {condition}
                ORDER BY Price_Time
                LIMIT 1 BY (Price_Time_Interval, Address_Hash)
    '
         ))
    LIFETIME (MIN ${DICTIONARY_LIFETIME_MIN} MAX ${DICTIONARY_LIFETIME_MAX})
    LAYOUT (RANGE_HASHED(RANGE_LOOKUP_STRATEGY 'max'))
    RANGE (MIN Price_Time MAX Price_Time_End);
```

What I want:
```
CREATE OR REPLACE DICTIONARY marketdata.prices_eth_dict
    (
    Address_Hash UInt64,
    Price_Time DateTime,
    Price_Time_End DateTime,
    Price_Amount Float32
    )
    PRIMARY KEY Address_Hash
    SOURCE (CLICKHOUSE(
         USER '${CLICKHOUSE_USER}' PASSWORD '${CLICKHOUSE_PASSWORD}'
         update_field 'Price_Time'
         QUERY 'SELECT Address_Hash,
                       Price_Time,
                       Price_Time_End,
                       Price_Amount
                FROM (SELECT Address_Hash,
                             Price_Time,
                             Price_Time + INTERVAL ${DICTIONARY_TOP_TOKENS_PRICE_LIFESPAN} AS Price_Time_End,
                             toFloat32(Price_Amount) AS Price_Amount,
                             toStartOfInterval(Price_Time, INTERVAL ${DICTIONARY_TOP_TOKENS_PRICE_INTERVAL}) AS Price_Time_Interval
                      FROM marketdata.prices_eth
                      WHERE (Address_Hash = cityHash64(\'\')
                            OR Address_Hash = cityHash64(\'dac17f958d2ee523a2206206994597c13d831ec7\')
                            OR Address_Hash = cityHash64(\'b8c77482e45f1f44de1745f52c74426c631bdd52\')
                            OR Address_Hash = cityHash64(\'ae7ab96520de3a18e5e111b5eaab095312d7fe84\')
                            OR Address_Hash = cityHash64(\'a0b86991c6218b36c1d19d4a2e9eb0ce3606eb48\')
                            OR Address_Hash = cityHash64(\'95ad61b0a150d79219dcf64e1e6cc01f0b64c4ce\')
                            OR Address_Hash = cityHash64(\'582d872a1b094fc48f5de31d3b73f2d9be47def1\')
                            OR Address_Hash = cityHash64(\'514910771af9ca656af840dff83e8264ecf986ca\')
                            OR Address_Hash = cityHash64(\'2260fac5e5542a773aa44fbcfedf7c193bc2c599\')
                            OR Address_Hash = cityHash64(\'7d1afa7b718fb893db30a3abc0cfc608aacfebb0\'))
                        AND {condition}
                      UNION ALL
                      SELECT Address_Hash,
                             Price_Time,
                             Price_Time + INTERVAL ${DICTIONARY_REGULAR_TOKENS_PRICE_LIFESPAN} AS Price_Time_End,
                             toFloat32(Price_Amount) AS Price_Amount,
                             toStartOfInterval(Price_Time, INTERVAL ${DICTIONARY_REGULAR_TOKENS_PRICE_INTERVAL}) AS Price_Time_Interval
                      FROM marketdata.prices_eth
                      WHERE (Address_Hash != cityHash64(\'\')
                            AND Address_Hash != cityHash64(\'dac17f958d2ee523a2206206994597c13d831ec7\')
                            AND Address_Hash != cityHash64(\'b8c77482e45f1f44de1745f52c74426c631bdd52\')
                            AND Address_Hash != cityHash64(\'ae7ab96520de3a18e5e111b5eaab095312d7fe84\')
                            AND Address_Hash != cityHash64(\'a0b86991c6218b36c1d19d4a2e9eb0ce3606eb48\')
                            AND Address_Hash != cityHash64(\'95ad61b0a150d79219dcf64e1e6cc01f0b64c4ce\')
                            AND Address_Hash != cityHash64(\'582d872a1b094fc48f5de31d3b73f2d9be47def1\')
                            AND Address_Hash != cityHash64(\'514910771af9ca656af840dff83e8264ecf986ca\')
                            AND Address_Hash != cityHash64(\'2260fac5e5542a773aa44fbcfedf7c193bc2c599\')
                            AND Address_Hash != cityHash64(\'7d1afa7b718fb893db30a3abc0cfc608aacfebb0\'))
                         AND {condition}
                )
                ORDER BY Price_Time
                LIMIT 1 BY (Price_Time_Interval, Address_Hash)
    '
         ))
    LIFETIME (MIN ${DICTIONARY_LIFETIME_MIN} MAX ${DICTIONARY_LIFETIME_MAX})
    LAYOUT (RANGE_HASHED(RANGE_LOOKUP_STRATEGY 'max'))
    RANGE (MIN Price_Time MAX Price_Time_End);
```

What I receive if I use what I want:
```
[2024-04-05 21:53:17] Code: 62. DB::Exception: Syntax error: failed at position 3108 ('}') (line 40, col 39): }
[2024-04-05 21:53:17] )
[2024-04-05 21:53:17] ORDER BY Price_Time
[2024-04-05 21:53:17] LIMIT 1 BY (Price_Time_Interval, Address_Hash)
[2024-04-05 21:53:17] . Expected colon between name and type: while executing 'FUNCTION dictGet('marketdata.prices_eth_dict' :: 6, 'Price_Amount' :: 7, cityHash64(lower(hex(Currency_SmartContract))) :: 8, Block_Time : 1) -> dictGet('dev_marketdata.prices_eth_dict', 'Price_Amount', cityHash64(lower(hex(Currency_SmartContract))), Block_Time) Float32 : 10'. (SYNTAX_ERROR) (version 23.7.5.30 (official build))
```

Also when I try to use it without explicit `{condition}` dictionary loads well but on every next update It throws an error 
```
Code: 62. DB::Exception: Syntax error: failed at position 3156 ('WHERE') (line 43, col 6): WHERE Price_Time >= '2024-04-05 18:59:02';. Expected one of: OR, AND, IS NULL, IS NOT NULL, BETWEEN, NOT BETWEEN, LIKE, ILIKE, NOT LIKE, NOT ILIKE, REGEXP, IN, NOT IN, GLOBAL IN, GLOBAL NOT IN, MOD, DIV, alias, AS, token, Comma, FETCH, LIMIT, SETTINGS, UNION, EXCEPT, INTERSECT, INTO OUTFILE, FORMAT, end of query. (SYNTAX_ERROR) (version 23.7.5.30 (official build))
```

**Comment by robot-ch-test-poll** [comment]
*This is an automated comment for commit 8f252dc0328b4ee80b8713cb10fcd3021d56b66b with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/62355/8f252dc0328b4ee80b8713cb10fcd3021d56b66b/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

**Review by kitaisreal — APPROVED** [review]

**Comment by ivanov17andrey** [comment]
Do I need to do anything else?

**Comment by alexey-milovidov** [comment]
Ok, but needs a test.

**Comment by alexey-milovidov** [comment]
The code does not build.

**Comment by alexey-milovidov** [comment]
Ok, but it needs a test.

**Comment by alexey-milovidov** [comment]
Abandoned.

**Pull request closed without merging**
