### PR TITLE
[experiment] maybe fix warnings in integration tests

### PR DESCRIPTION
**Pull request by blinkov**
Changelog category (leave one):
- Not for changelog.

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
It is unclear did it help or not.

**Comment by alesapin** [comment]
Checked manually. It woks.

**Review by alesapin — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
@blinkov This PR failed in Description check:
```
Changelog entry is not found.
```

You have to either provide the description for changelog or choose "Not for changelog".
I will fix this mistake for you.

**Comment by alexey-milovidov** [comment]
FYI This PR breaks integration tests in master.

**Pull request merged**
