### PR TITLE
Fix incorrect character counting in PositionImpl::vectorVector

### PR DESCRIPTION
**Pull request by heymind**
Reproducible example:
```
SELECT positionUTF8('你', '', 3)

Query id: 7e07636f-e75d-4398-856c-f825a9122dc6

   ┌─positionUTF8('你', '', 3)─┐
1. │                         0 │
   └───────────────────────────┘

1 row in set. Elapsed: 0.001 sec. 
```
But
```
SELECT positionUTF8(materialize('你'), materialize(''), materialize(3))

Query id: 3be928b8-8b3a-4416-8128-b2bbd7c069fd

   ┌─positionUTF8(materialize('你'), materialize(''), materialize(3))─┐
1. │                                                                3 │
   └──────────────────────────────────────────────────────────────────┘

1 row in set. Elapsed: 0.001 sec. 
```
It should yield the same result regardless of materialize.
This is because ‘你’ is a multi-byte UTF-8 character, but we count its length in bytes in ::vectorVector, whereas other variants do not have this counting issue.

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
- Fix incorrect character counting in PositionImpl::vectorVector

### Documentation entry for user-facing changes
nothing

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Run only fuzzers related jobs (libFuzzer fuzzers, AST fuzzers, etc.)
- [ ]  Exclude: AST fuzzers
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Review by alexey-milovidov — CHANGES_REQUESTED** [review]
Needs a test.

**Comment by robot-ch-test-poll1** [comment]
*This is an automated comment for commit f158c0346c1409645a33f1f0537b442f424be04b with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/71003/f158c0346c1409645a33f1f0537b442f424be04b/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/c737eabb9e79d3d8e0010111fef93effc90fa23c/docs_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Comment by heymind** [comment]
> Needs a test.

Which file is preferred for adding the test case?

I've added a simple test case at the end of 00233_position_function_family. However, I'm not sure if this is the most appropriate location.

**Review by alexey-milovidov — APPROVED** [review]
LGTM, thank you!

**Pull request merged**
