### PR TITLE
Add test issue #23430

### LINKED ISSUE #23430: After the Kafka engine table is deleted, the materialized view cannot consume the Kafka data and submit the offset according to the original construction model. The offset will only be submitted when the Kafka table is queried by select
(you don't have to strictly follow this form)

**Describe the bug**
After the Kafka engine table is deleted, the materialized view cannot consume the Kafka data and submit the offset according to the original construction model. The offset will only be submitted when the Kafka table is queried by select

**Does it reproduce on recent release?**
20.11.3.3

**How to reproduce**
* Clickhouse 20.11.3.3

**Step**
1. Create Kafka Table

```sql
CREATE TABLE IF NOT EXISTS olap_kafka_transform_local ON CLUSTER ck_cluster_1
(
    `id` String,
    `dt` String,
    `cc_level1` String,
    `cc_level2` String,
    `cc_level3` String,
    `app_id` UInt32
) ENGINE = Kafka
    SETTINGS
    kafka_broker_list = 'xxxxxxx',
    kafka_topic_list = 'olap_consume_offline',
    kafka_group_name = 'olap_consume_offline_ck_cluster_1',
    kafka_format = 'JSONEachRow',
    kafka_num_consumers = 6,
    kafka_max_block_size = 20000,
    kafka_skip_broken_messages = 1048577;;
```

2. delete kafka engine table

```sql
drop table olap_kafka_transform_local ON CLUSTER ck_cluster_1;
```

3. Recreate Kafka table
4. Problems recur

**Expected behavior**

**Error message and/or stacktrace**

**Additional context**

### PR DESCRIPTION
**Pull request by filimonov**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Closes #23430 (can't reproduce)

Detailed description / Documentation draft:

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
It failed in 44th run.

**Comment by filimonov** [comment]
> It failed in 44th run.

Looks like some env issed.

Test setup stage failed - the first line which creates a topic. So it's for sure not something related to the tested logic / scenario itself.


docker.log ends suddenly just before that (it should be much longer). Maybe Docker daemon died?

```
=================================== FAILURES ===================================
_______________________ test_kafka_recreate_kafka_table ________________________
[gw0] linux -- Python 3.8.5 /usr/bin/python3

kafka_cluster = <helpers.cluster.ClickHouseCluster object at 0x7f5512e55610>

    @pytest.mark.timeout(180)
    def test_kafka_recreate_kafka_table(kafka_cluster):
        '''
            Checks that materialized view work properly after dropping and recreating the Kafka table.
        '''
>       admin_client = KafkaAdminClient(bootstrap_servers="localhost:9092")

test_storage_kafka/test.py:1288: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/usr/local/lib/python3.8/dist-packages/kafka/admin/client.py:208: in __init__
    self._client = KafkaClient(metrics=self._metrics,
/usr/local/lib/python3.8/dist-packages/kafka/client_async.py:244: in __init__
    self.config['api_version'] = self.check_version(timeout=check_timeout)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <kafka.client_async.KafkaClient object at 0x7f5505ba3f70>, node_id = None
timeout = 2.0, strict = False

    def check_version(self, node_id=None, timeout=2, strict=False):
        """Attempt to guess the version of a Kafka broker.
    
        Note: It is possible that this method blocks longer than the
            specified timeout. This can happen if the entire cluster
            is down and the client enters a bootstrap backoff sleep.
            This is only possible if node_id is None.
    
        Returns: version tuple, i.e. (0, 10), (0, 9), (0, 8, 2), ...
    
        Raises:
            NodeNotReadyError (if node_id is provided)
            NoBrokersAvailable (if node_id is None)
            UnrecognizedBrokerVersion: please file bug if seen!
            AssertionError (if strict=True): please file bug if seen!
        """
        self._lock.acquire()
        end = time.time() + timeout
        while time.time() < end:
    
            # It is possible that least_loaded_node falls back to bootstrap,
            # which can block for an increasing backoff period
            try_node = node_id or self.least_loaded_node()
            if try_node is None:
                self._lock.release()
>               raise Errors.NoBrokersAvailable()
E               kafka.errors.NoBrokersAvailable: NoBrokersAvailable

/usr/local/lib/python3.8/dist-packages/kafka/client_async.py:900: NoBrokersAvailable
------------------------------ Captured log call -------------------------------
DEBUG    kafka.admin.client:client.py:192 Starting KafkaAdminClient with configuration: {'bootstrap_servers': 'localhost:9092'}
DEBUG    kafka.metrics.metrics:metrics.py:156 Added sensor with name connections-closed
DEBUG    kafka.metrics.metrics:metrics.py:156 Added sensor with name connections-created
DEBUG    kafka.metrics.metrics:metrics.py:156 Added sensor with name select-time
DEBUG    kafka.metrics.metrics:metrics.py:156 Added sensor with name io-time
DEBUG    kafka.client:client_async.py:374 Initiating connection to node bootstrap-0 at localhost:9092
DEBUG    kafka.metrics.metrics:metrics.py:156 Added sensor with name bytes-sent-received
DEBUG    kafka.metrics.metrics:metrics.py:156 Added sensor with name bytes-sent
DEBUG    kafka.metrics.metrics:metrics.py:156 Added sensor with name bytes-received
DEBUG    kafka.metrics.metrics:metrics.py:156 Added sensor with name request-latency
DEBUG    kafka.metrics.metrics:metrics.py:156 Added sensor with name node-bootstrap-0.bytes-sent
DEBUG    kafka.metrics.metrics:metrics.py:156 Added sensor with name node-bootstrap-0.bytes-received
DEBUG    kafka.metrics.metrics:metrics.py:156 Added sensor with name node-bootstrap-0.latency
DEBUG    kafka.conn:conn.py:368 <BrokerConnection node_id=bootstrap-0 host=localhost:9092 <disconnected> [unspecified None]>: creating new socket
DEBUG    kafka.conn:conn.py:374 <BrokerConnection node_id=bootstrap-0 host=localhost:9092 <disconnected> [IPv6 ('::1', 9092, 0, 0)]>: setting socket option (6, 1, 1)
INFO     kafka.conn:conn.py:380 <BrokerConnection node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
INFO     kafka.conn:conn.py:1205 Probing node bootstrap-0 broker version
ERROR    kafka.conn:conn.py:418 Connect attempt to <BrokerConnection node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]> returned error 111. Disconnecting.
INFO     kafka.conn:conn.py:919 <BrokerConnection node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
DEBUG    kafka.conn:conn.py:368 <BrokerConnection node_id=bootstrap-0 host=localhost:9092 <disconnected> [IPv6 ('::1', 9092, 0, 0)]>: creating new socket
DEBUG    kafka.conn:conn.py:374 <BrokerConnection node_id=bootstrap-0 host=localhost:9092 <disconnected> [IPv6 ('::1', 9092, 0, 0)]>: setting socket option (6, 1, 1)
INFO     kafka.conn:conn.py:380 <BrokerConnection node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
ERROR    kafka.conn:conn.py:418 Connect attempt to <BrokerConnection node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]> returned error 111. Disconnecting.
INFO     kafka.conn:conn.py:919 <BrokerConnection node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
DEBUG    kafka.conn:conn.py:368 <BrokerConnection node_id=bootstrap-0 host=localhost:9092 <disconnected> [IPv6 ('::1', 9092, 0, 0)]>: creating new socket
DEBUG    kafka.conn:conn.py:374 <BrokerConnection node_id=bootstrap-0 host=localhost:9092 <disconnected> [IPv4 ('127.0.0.1', 9092)]>: setting socket option (6, 1, 1)
INFO     kafka.conn:conn.py:380 <BrokerConnection node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
ERROR    kafka.conn:conn.py:418 Connect attempt to <BrokerConnection node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]> returned error 111. Disconnecting.
INFO     kafka.conn:conn.py:919 <BrokerConnection node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
DEBUG    kafka.conn:conn.py:896 <BrokerConnection node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: reconnect backoff 0.056145348109735635 after 1 failures
````

docker.log  ends up suddenly. 
```
mfilimonov@laptop-5591:~/workspace/ClickHouse/kafka-failover/test_storage_kafka/_instances$ tail -n 10 docker.log 
kafka1_1           | [2021-06-03 20:13:30,218] INFO [GroupCoordinator 1]: Stabilized group format_tests_4_stream_TSVWithNamesAndTypes generation 1 (__consumer_offsets-17) (kafka.coordinator.group.GroupCoordinator)
kafka1_1           | [2021-06-03 20:13:30,220] INFO [GroupCoordinator 1]: Assignment received from leader for group format_tests_4_stream_TSVWithNamesAndTypes for generation 1 (kafka.coordinator.group.GroupCoordinator)
kafka1_1           | [2021-06-03 20:13:30,855] INFO [GroupCoordinator 1]: Stabilized group format_tests_4_stream_Native generation 1 (__consumer_offsets-9) (kafka.coordinator.group.GroupCoordinator)
kafka1_1           | [2021-06-03 20:13:30,858] INFO [GroupCoordinator 1]: Assignment received from leader for group format_tests_4_stream_Native for generation 1 (kafka.coordinator.group.GroupCoordinator)
kafka1_1           | [2021-06-03 20:13:31,495] INFO [GroupCoordinator 1]: Stabilized group format_tests_4_stream_RowBinary generation 1 (__consumer_offsets-11) (kafka.coordinator.group.GroupCoordinator)
kafka1_1           | [2021-06-03 20:13:31,497] INFO [GroupCoordinator 1]: Assignment received from leader for group format_tests_4_stream_RowBinary for generation 1 (kafka.coordinator.group.GroupCoordinator)
kafka1_1           | [2021-06-03 20:13:32,148] INFO [GroupCoordinator 1]: Stabilized group format_tests_4_stream_RowBinaryWithNamesAndTypes generation 1 (__consumer_offsets-13) (kafka.coordinator.group.GroupCoordinator)
kafka1_1           | [2021-06-03 20:13:32,150] INFO [GroupCoordinator 1]: Assignment received from leader for group format_tests_4_stream_RowBinaryWithNamesAndTypes for generation 1 (kafka.coordinator.group.GroupCoordinator)
kafka1_1           | [2021-06-03 20:13:32,779] INFO [GroupCoordinator 1]: Stabilized group format_tests_4_stream_ORC generation 1 (__consumer_offsets-20) (kafka.coordinator.group.GroupCoordinator)
kafka1_1           | [2021-06-03 20:13:32,781] INFO [GroupCoordinator 1]: Assignment received from leader for group format_tests_4_stream_ORC for generation 1 (kafka.coordinator.group.GroupCoordinator)
```

**Comment by filimonov** [comment]
OK. Maybe failure is related to the refactorings of integration tests that were just merged.

**Comment by alexey-milovidov** [comment]
@mergifyio update

**Comment by alexey-milovidov** [comment]
Still not ok.

**Comment by filimonov** [comment]
Missed some small api changes introduced in https://github.com/ClickHouse/ClickHouse/commit/872e36c207f5ed96f97883cb974038474160c84d#diff-8129a3b04ff2293c2d89b35395be9ef49918cdafd4420a745d05733b00979646L86-R100 and merged just before that pr

**Comment by filimonov** [comment]
@Mergifyio update

**Comment by filimonov** [comment]
No related failures.

**Pull request merged**
