### PR TITLE
fix storage join settings with persistency

### LINKED ISSUE #31680: Persistent setting of Join table
В документации для таблицы типа Join есть перечень настроек, которые можно указать при создании, в частности join_any_take_last_row и persistent, при одновременном использовании возникает ошибка создания таблицы.

Ошибка Code: 115. DB::Exception: Unknown setting join_any_take_last_row: for storage Join. (UNKNOWN_SETTING) (version 21.11.4.14 (official build))
>create table internal.lookup (key UInt64, value UInt64) engine = Join(any, left, key)
settings join_any_take_last_row = 1, persistent = 0;

Значения параметров и их очередность не играет роли.

Однако если указать только один любой из этих двух параметр, то все работает.

Комбинации с другими настройками работают, пока не добавишь persistent
>create table internal.lookup (key UInt64, value UInt64) engine = Join(any, left, key)
settings
join_use_nulls = 0,
max_rows_in_join = 0,
max_bytes_in_join = 0,
join_overflow_mode = 'throw',
join_any_take_last_row = 0;

При добавлении persistent начинает ругаться на Unknown setting любого из указанных параметров.

### PR DESCRIPTION
**Pull request by cmsxbc**
Changelog category (leave one):
- Bug Fix (user-visible misbehaviour in official stable or prestable release)

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix CREATE TABLE of Join Storage with multiply settings contains persistency. Close #31680 

Detailed description / Documentation draft:
Close #31680

### CODE REVIEW

**Comment by cmsxbc** [comment]
@Mergifyio update

**Comment by cmsxbc** [comment]
@Mergifyio update

**Comment by cmsxbc** [comment]
I have no idea why the test on GithubActions Failed... I cannot retrieve executioni info....

**Comment by vdimir** [comment]
> I have no idea why the test on GithubActions Failed... I cannot retrieve executioni info....

I suppose because of spot instances in aws

**Review by vdimir — APPROVED** [review]

**Pull request merged**
