### PR TITLE
Detach threads from thread group

### PR DESCRIPTION
**Pull request by tavplubix**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

It is supposed to fix issues like https://github.com/ClickHouse/ClickHouse/issues/43737, https://github.com/ClickHouse/ClickHouse/issues/43120, https://github.com/ClickHouse/ClickHouse/issues/37649

### CODE REVIEW

**Comment by tavplubix** [comment]
Okay, it does not break anything (at least in an obvious way), and generally, the changes make sense.
Explanation: https://github.com/ClickHouse/ClickHouse/issues/43737#issuecomment-1329182997

**Review by antonio2368 — APPROVED** [review]
Makes sense to me, it's more correct for sure.
Found only one questionable place which wasn't covered with this PR:
- `BackgroundShcedulePool` calls `attachTo` inside `attachToThreadGroup` method and I don't see any detach calls

**Comment by tavplubix** [comment]
AFAIK threads are never detached from BackgroundSchedulePool until server shutdown, so I guess it's not an issue. But let's add it for consistency.

**Comment by tavplubix** [comment]
AST fuzzer (tsan) - https://github.com/ClickHouse/ClickHouse/issues/43204
Stateless tests (debug, s3 storage) [6/6] - it's funny - a bug from 2015 - https://github.com/ClickHouse/ClickHouse/pull/43847
Stateless tests (tsan) [4/5] - https://github.com/ClickHouse/ClickHouse/issues/43659
Stress test (tsan) - https://github.com/ClickHouse/ClickHouse/issues/37664

**Comment by tavplubix** [comment]
I hate Mergeable Check (and spot instances)

**Pull request merged**
