### PR TITLE
replace std::tuple with std::variant

### PR DESCRIPTION
**Pull request by amosbird**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

### CODE REVIEW

**Comment by amosbird** [comment]
I don't follow. You mean we cannot use `std::variant` since we had that double assignment code existing?

**Comment by alexey-milovidov** [comment]
```
milovidov@milovidov-Pro-P30:~/work/ClickHouse$ cat test.cpp
#include <variant>

int main()
{
    std::variant<int, float> x;
    std::get<float>(x) = 1.1;
    return std::get<float>(x);
}
milovidov@milovidov-Pro-P30:~/work/ClickHouse$ g++-7 -O0 -std=c++17 test.cpp
milovidov@milovidov-Pro-P30:~/work/ClickHouse$ ./a.out 
terminate called after throwing an instance of 'std::bad_variant_access'
  what():  Unexpected index
```

**Comment by amosbird** [comment]
> And also you don't need a unique_ptr.

std::variant cannot get rid of all `unique_ptr` wrappers as ComplexKeyCacheDictionary uses  `ContainerType = Value[]; ` which doesn't handle ownerships.

**Comment by alexey-milovidov** [comment]
Yes.

**Pull request merged**
