### PR TITLE
AggregateFunctions: implemented topK(n)

### LINKED ISSUE #633: what happen in error: field ‘_ctx’ has incomplete type ‘EVP_CIPHER_CTX {aka evp_cipher_ctx_st}’
```
/data/clickhouse_install/off_line_install/ClickHouse/contrib/libpoco/Crypto/src/CipherImpl.cpp:80:21: error: field ‘_ctx’ has incomplete type ‘EVP_CIPHER_CTX {aka evp_cipher_ctx_st}’
   EVP_CIPHER_CTX    _ctx;
                     ^~~~
In file included from /usr/local/include/openssl/crypto.h:31:0,
                 from /data/clickhouse_install/off_line_install/ClickHouse/contrib/libpoco/Crypto/include/Poco/Crypto/OpenSSLInitializer.h:26,
                 from /data/clickhouse_install/off_line_install/ClickHouse/contrib/libpoco/Crypto/include/Poco/Crypto/CipherKeyImpl.h:24,
                 from /data/clickhouse_install/off_line_install/ClickHouse/contrib/libpoco/Crypto/include/Poco/Crypto/CipherKey.h:24,
                 from /data/clickhouse_install/off_line_install/ClickHouse/contrib/libpoco/Crypto/include/Poco/Crypto/CipherImpl.h:25,
                 from /data/clickhouse_install/off_line_install/ClickHouse/contrib/libpoco/Crypto/src/CipherImpl.cpp:17:
/usr/local/include/openssl/ossl_typ.h:90:16: note: forward declaration of ‘EVP_CIPHER_CTX {aka struct evp_cipher_ctx_st}’
 typedef struct evp_cipher_ctx_st EVP_CIPHER_CTX;
                ^~~~~~~~~~~~~~~~~
cc1plus: warning: unrecognized command line option ‘-Wno-for-loop-analysis’
cc1plus: warning: unrecognized command line option ‘-Wno-unused-local-typedef’
cc1plus: warning: unrecognized command line option ‘-Wno-unused-private-field’
make[2]: *** [contrib/libpoco/Crypto/CMakeFiles/PocoCrypto.dir/src/CipherImpl.cpp.o] Error 1
make[1]: *** [contrib/libpoco/Crypto/CMakeFiles/PocoCrypto.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

```

I make Clickhouse is this error.

### PR DESCRIPTION
**Pull request by vavrusa**
Hi,

I took a stab at implementing #294 and would appreciate some help finishing this.

So this implements a new function for approximate computation of the most frequent entries using
Filtered Space Saving with a merge step adapted from Parallel Space Saving paper.

It works better for cases where GROUP BY x is impractical due to high cardinality of x, such as top IP addresses or top search queries, the example can be seen in the added test. For low cardinality sets it's about half the speed of `uniq()` as it has to do more work inherently (and the implementation could be better).

Now the questions:

- [ ] I'm not sure about is lifetime of `StringRef`s in the generic variant of the aggregation function, it's inserted into arena for compound keys so I assume that's bad as it will grow infinitely?
- [ ] Currently it uses extra vector for storing alpha, it'd be better to reuse the array backing the hashtable but `HashTable` is not addressable by slot number, would it be okay to add it?
- [ ] The 3ef8882 fixes #633, is it okay to backport it to make newer distros happy?

### CODE REVIEW

**Comment by robot-metrika-test** [comment]
Can one of the admins verify this patch?

**Comment by alexey-milovidov** [comment]
Thank you for implementing this feature! It will be very useful for our cases too.
I just started with this pull request...

Answers:

You understand correctly: `Arena` only grows, and individual values cannot be removed to save space. When values in `SpaceSaving` replace each other, memory allocated for previous values will be wasted in `Arena`. We have `ArenaWithFreeLists` to allow reclaiming memory, but aggregation is using plain `Arena`s to store aggregation states and to allow allocation of additional memory.

Possible workarounds:

1. Allocate memory not in `Arena`, but using usual `new`/`delete` or `malloc`/`free`; it has following drawbacks: 1. More difficult to account memory usage with `MemoryTracker` (you need to call it explicitly). 2. Memory overhead from allocator (usually, allocated memory is rounded up to some size class). 3. Less efficient memory allocation (high CPU cost of many of small allocations and deallocations).

Nevertheless, you already allocate additional memory out of Arena, as `HashMap` in `SpaceSaving` do so. 

Also please note, that `HashMap` by default preallocate quite a big chunk of memory, and for typical case of many small aggregation states, you should replace `Grower` template parameter. For examples, see usage of `HashSet` in `uniqExact` or `groupUniqArray` aggregate function.

2. Slightly rewrite aggregation code to use `ArenaWithFreeLists` instead of `Arena` and pass `ArenaWithFreeLists` inside `IAggregateFunction` methods. The main challenge is to do in with zero-cost, when memory reclamation is not used. This seems possible.

**Comment by alexey-milovidov** [comment]
I have merged this PR, because it is almost Ok right now, and it will be more convenient for further development.

**Comment by alexey-milovidov** [comment]
I just have read the article and started testing...
Currently, memory usage for this function is not bounded, because elements never deleted from hash table. For example, we have 1 GiB memory usage for query: 
```
SELECT topK(number) FROM system.numbers
```
after processed 100 million of rows.

I will look further, what we will do...

**Comment by vavrusa** [comment]
I think the first problem is that hash table size is not decremented when the cell is zeroed, so it keeps growing. I'll redo it to move elements instead of removing and inserting.

**Pull request merged**
