### PR TITLE
Add sha512 hash functions

### PR DESCRIPTION
**Pull request by zhanglistar**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Add function `SHA512`.

### CODE REVIEW

**Comment by zhanglistar** [comment]
https://github.com/ClickHouse/ClickHouse/issues/27806

**Comment by qoega** [comment]
Tests are needed

**Review by alexey-milovidov — APPROVED** [review]

**Comment by zhanglistar** [comment]
> Tests are needed

Tests added.

**Comment by qoega** [comment]
Please add 02012_sha512_fixedstring to skip list for fast test there
https://github.com/ClickHouse/ClickHouse/blob/master/docker/test/fasttest/run.sh#L305

**Comment by zhanglistar** [comment]
> Please add 02012_sha512_fixedstring to skip list for fast test there
> https://github.com/ClickHouse/ClickHouse/blob/master/docker/test/fasttest/run.sh#L305

Done.

**Comment by zhanglistar** [comment]
> Tests are needed

Why docs alert?

**Comment by zhanglistar** [comment]
@qoega  why docs check and push to dockerhub fail?

**Comment by qoega** [comment]
We saw problems with canonical server. I'll try to restart checks

**Comment by zhanglistar** [comment]
> We saw problems with canonical server. I'll try to restart checks

Can merge?

**Pull request merged**
