### PR TITLE
Add max/peak RSS into system.asynchronous_metrics

### PR DESCRIPTION
**Pull request by azat**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Add max/peak RSS (`MemoryResidentMax`) into system.asynchronous_metrics

Will be useful for perf tests (at least), since if some queries became memory greedy this will not be reflected (because memory will be freed by the time of compare).

### CODE REVIEW

**Comment by robot-clickhouse** [comment]
*This is an automated comment for commit 6fd32d92d0cadbdc96381b3e8b2d9869ecf6ffd5 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/58095/6fd32d92d0cadbdc96381b3e8b2d9869ecf6ffd5/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td><a href="https://github.com/ClickHouse/ClickHouse/actions/runs/7280009748">✅ success</a></td></tr>
<tbody>
</table>
</details>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/58095/6fd32d92d0cadbdc96381b3e8b2d9869ecf6ffd5/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Comment by UnamedRus** [comment]
I also dream of https://github.com/ClickHouse/ClickHouse/issues/57381, it probably will be even more useful than peak RSS both for CI and analysis of system.query_log

**Comment by azat** [comment]
I always thought about system.asynchronous_metrics as an internal metrics, and I event didn't knew that they are documented, but since this is indeed true, sure let's document them.

As for the changelog entry the same thoughts, but since at least you wrote about this, I will adjust it.

**Review by alexey-milovidov — APPROVED** [review]
Perfect :)

**Pull request merged**
