### PR TITLE
Fix delta test in unbundled mode

### PR DESCRIPTION
**Pull request by alesapin**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Non-significant (changelog entry is not required)

### CODE REVIEW

**Comment by alesapin** [comment]
I think zstd version in ubuntu 19:04 was updated, so we faced a problem  https://github.com/facebook/zstd/issues/1148#issuecomment-391496583. But I'm not sure that we should change default level in our code https://github.com/clickhouse/ClickHouse/blob/master/dbms/src/Compression/CompressionCodecZSTD.h#L14.

**Comment by alexey-milovidov** [comment]
It's strange if we have used level 3 before.
Our intention is to use more lightweight level as default.

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alesapin** [comment]
> It's strange if we have used level 3 before.
> Our intention is to use more lightweight level as default.

No, we have used level 1, and for some reason, it works the same as level 3 in our contrib and ubuntu 18.04. In ubuntu 19.10 we have different behavior for level 1and level 2. Seems like our version backward incompatible.

**Comment by alexey-milovidov** [comment]
> Functional stateless tests (unbundled)

Fixed.

**Pull request merged**
