### PR TITLE
[WIP] ALTER RENAME COLUMN integration tests.

### PR DESCRIPTION
**Pull request by vzakaznikov**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Build/Testing/Packaging Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Adding integration tests for new ALTER RENAME COLUMN query.

Detailed description / Documentation draft:
Current stateless tests for ALTER RENAME COLUMN are not enough to fully verify the new functionality. Adding integration tests to check behavior in a more realistic environment.

### CODE REVIEW

**Comment by vzakaznikov** [comment]
@alesapin, could you please look at these tests? I've tried to simplify but even a simple `test_rename_parallel_same_node` does not work for me. Seems like we have a problem with renames done in parallel.

**Comment by alesapin** [comment]
Fix for the found bug is here https://github.com/ClickHouse/ClickHouse/pull/10659. You can cherry-pick this commit into your branch.

**Comment by vzakaznikov** [comment]
@alesapin thanks, the `test_rename_parallel_same_node` test now passes with your fix applied to the current master. However, when I try to run all the tests inside the `test_rename_column` the server crashes with the exception below.

```
2020.05.05 04:41:12.874286 [ 73 ] {} <Fatal> BaseDaemon: ########################################
2020.05.05 04:41:12.874411 [ 73 ] {} <Fatal> BaseDaemon: (version 20.5.1.1) (from thread 35) (no query) Received signal Segmentation fault (11).
2020.05.05 04:41:12.874471 [ 73 ] {} <Fatal> BaseDaemon: Address: NULL pointer. Access: read. Unknown si_code.
2020.05.05 04:41:12.874526 [ 73 ] {} <Fatal> BaseDaemon: Stack trace: 0x7f947d9ce981 0x948e051 0x1021b2d3 0x1021a946 0x1021a8dc 0xdabe303 0xdabd34c 0xdaa8a43
2020.05.05 04:41:12.874659 [ 73 ] {} <Fatal> BaseDaemon: 3. abort @ 0x25981 in /usr/lib/x86_64-linux-gnu/libc-2.30.so
2020.05.05 04:41:12.875431 [ 73 ] {} <Fatal> BaseDaemon: 4. /home/user/github/ClickHouse_vzakaznikov/build/../base/daemon/BaseDaemon.cpp:0: terminate_handler() @ 0x948e051 in /usr/bin/clickhouse
2020.05.05 04:41:12.879071 [ 73 ] {} <Fatal> BaseDaemon: 5. /home/user/github/ClickHouse_vzakaznikov/build/../contrib/libcxxabi/src/cxa_handlers.cpp:61: std::__terminate(void (*)()) @ 0x1021b2d3 in /usr/bin/clickhouse
2020.05.05 04:41:12.882512 [ 73 ] {} <Fatal> BaseDaemon: 6. /home/user/github/ClickHouse_vzakaznikov/build/../contrib/libcxxabi/src/cxa_exception.cpp:152: ? @ 0x1021a946 in /usr/bin/clickhouse
2020.05.05 04:41:12.885907 [ 73 ] {} <Fatal> BaseDaemon: 7. /home/user/github/ClickHouse_vzakaznikov/build/../contrib/libcxxabi/src/cxa_exception.cpp:283: ? @ 0x1021a8dc in /usr/bin/clickhouse
2020.05.05 04:41:12.888053 [ 73 ] {} <Fatal> BaseDaemon: 8. /home/user/github/ClickHouse_vzakaznikov/build/../src/Common/ZooKeeper/ZooKeeperImpl.cpp:886: Coordination::ZooKeeper::connect(std::__1::vector<Coordination::ZooKeeper::Node, std::__1::allocator<Coordination::ZooKeeper::Node> > const&, Poco::Timespan) @ 0xdabe303 in /usr/bin/clickhouse
2020.05.05 04:41:12.889097 [ 73 ] {} <Fatal> BaseDaemon: 9. /home/user/github/ClickHouse_vzakaznikov/build/../contrib/libcxx/include/string:1426: Coordination::ZooKeeper::ZooKeeper(std::__1::vector<Coordination::ZooKeeper::Node, std::__1::allocator<Coordination::ZooKeeper::Node> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Poco::Timespan, Poco::Timespan, Poco::Timespan) @ 0xdabd34c in /usr/bin/clickhouse
2020.05.05 04:41:12.890441 [ 73 ] {} <Fatal> BaseDaemon: 10. /home/user/github/ClickHouse_vzakaznikov/build/../contrib/libcxx/include/memory:3028: std::__1::__unique_if<Coordination::ZooKeeper>::__unique_single std::__1::make_unique<Coordination::ZooKeeper, std::__1::vector<Coordination::ZooKeeper::Node, std::__1::allocator<Coordination::ZooKeeper::Node> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, char const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Poco::Timespan, Poco::Timespan, Poco::Timespan>(std::__1::vector<Coordination::ZooKeeper::Node, std::__1::allocator<Coordination::ZooKeeper::Node> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, char const*&&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Poco::Timespan&&, Poco::Timespan&&, Poco::Timespan&&) @ 0xdaa8a43 in /usr/bin/clickhouse
```

**Comment by alesapin** [comment]
Trace is not complete and I cannot reproduce this segfault:
```
collected 4 items                                                                                                                                                                                                                              
test_rename_column/test.py ....                                                                                                            [100%]
```
I'll make an empty commit into your PR to trigger CI.

**Comment by vzakaznikov** [comment]
Interesting. For me the crash is reproduces every other run. That short trace is all I get in the log.
For example, here is another one. Let's see what CI shows.
```
2020.05.05 14:12:36.659326 [ 8 ] {} <Trace> BaseDaemon: Received signal 11
2020.05.05 14:12:36.659673 [ 71 ] {} <Fatal> BaseDaemon: ########################################
2020.05.05 14:12:36.659821 [ 71 ] {} <Fatal> BaseDaemon: (version 20.5.1.1) (from thread 34) (no query) Received signal Segmentation fault (11).
2020.05.05 14:12:36.659906 [ 71 ] {} <Fatal> BaseDaemon: Address: NULL pointer. Access: read. Unknown si_code.
2020.05.05 14:12:36.660004 [ 71 ] {} <Fatal> BaseDaemon: Stack trace: 0x7fddcd946981 0x948e051 0x1021b2d3 0x1021a946 0x1021a8dc 0xdabe303 0xdabd34c 0xdaa8a43
2020.05.05 14:12:36.660171 [ 71 ] {} <Fatal> BaseDaemon: 3. abort @ 0x25981 in /usr/lib/x86_64-linux-gnu/libc-2.30.so
2020.05.05 14:12:36.660998 [ 71 ] {} <Fatal> BaseDaemon: 4. /home/user/github/ClickHouse_vzakaznikov/build/../base/daemon/BaseDaemon.cpp:0: terminate_handler() @ 0x948e051 in /usr/bin/clickhouse
2020.05.05 14:12:36.665224 [ 71 ] {} <Fatal> BaseDaemon: 5. /home/user/github/ClickHouse_vzakaznikov/build/../contrib/libcxxabi/src/cxa_handlers.cpp:61: std::__terminate(void (*)()) @ 0x1021b2d3 in /usr/bin/clickhouse
2020.05.05 14:12:36.669362 [ 71 ] {} <Fatal> BaseDaemon: 6. /home/user/github/ClickHouse_vzakaznikov/build/../contrib/libcxxabi/src/cxa_exception.cpp:152: ? @ 0x1021a946 in /usr/bin/clickhouse
2020.05.05 14:12:36.673346 [ 71 ] {} <Fatal> BaseDaemon: 7. /home/user/github/ClickHouse_vzakaznikov/build/../contrib/libcxxabi/src/cxa_exception.cpp:283: ? @ 0x1021a8dc in /usr/bin/clickhouse
2020.05.05 14:12:36.674377 [ 71 ] {} <Fatal> BaseDaemon: 8. /home/user/github/ClickHouse_vzakaznikov/build/../src/Common/ZooKeeper/ZooKeeperImpl.cpp:886: Coordination::ZooKeeper::connect(std::__1::vector<Coordination::ZooKeeper::Node, std::__1::allocator<Coordination::ZooKeeper::Node> > const&, Poco::Timespan) @ 0xdabe303 in /usr/bin/clickhouse
2020.05.05 14:12:36.675357 [ 71 ] {} <Fatal> BaseDaemon: 9. /home/user/github/ClickHouse_vzakaznikov/build/../contrib/libcxx/include/string:1426: Coordination::ZooKeeper::ZooKeeper(std::__1::vector<Coordination::ZooKeeper::Node, std::__1::allocator<Coordination::ZooKeeper::Node> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Poco::Timespan, Poco::Timespan, Poco::Timespan) @ 0xdabd34c in /usr/bin/clickhouse
2020.05.05 14:12:36.676797 [ 71 ] {} <Fatal> BaseDaemon: 10. /home/user/github/ClickHouse_vzakaznikov/build/../contrib/libcxx/include/memory:3028: std::__1::__unique_if<Coordination::ZooKeeper>::__unique_single std::__1::make_unique<Coordination::ZooKeeper, std::__1::vector<Coordination::ZooKeeper::Node, std::__1::allocator<Coordination::ZooKeeper::Node> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, char const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Poco::Timespan, Poco::Timespan, Poco::Timespan>(std::__1::vector<Coordination::ZooKeeper::Node, std::__1::allocator<Coordination::ZooKeeper::Node> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, char const*&&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Poco::Timespan&&, Poco::Timespan&&, Poco::Timespan&&) @ 0xdaa8a43 in /usr/bin/clickhouse
```

**Comment by alexey-milovidov** [comment]
Maybe it is related to https://github.com/ClickHouse/ClickHouse/pull/10625

**Comment by vzakaznikov** [comment]
> Maybe it is related to #10625

Yes, maybe. I will re-build using GCC instead of clang.

**Comment by vzakaznikov** [comment]
Confirmed that there is no issue when using GCC9.

**Pull request closed without merging**
