### PR TITLE
Use raw pointers in AST fields

### PR DESCRIPTION
**Pull request by nikitamikhaylov**
### Changelog category (leave one):
- Build/Testing/Packaging Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Don't use smart pointers for fields in any AST. Instead store the smart pointer in the children list only. This is needed for https://github.com/ClickHouse/ClickHouse/pull/61533

### CODE REVIEW

**Comment by robot-ch-test-poll4** [comment]
*This is an automated comment for commit 78ed9d84539346ff3411856ec1f64be099cf3350 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/61559/78ed9d84539346ff3411856ec1f64be099cf3350/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

**Comment by amosbird** [comment]
Alternatively we can always use shared pointers and get rid of the children array, and add methods to iterate over children. Managing the consistency of raw pointers and ast children is painful, and we have adopted several different approaches in different AST implementations, e.g ASTSelect uses a map.

**Comment by vdimir** [comment]
In `QueryTree` every child node is stored in `children` vector and access to specific node is done via getter/setter method (that can also apply cast if concrete type is known). It requires lot's of boilerplate though to specify each getter/setter (each one can also be const/and mutable).

https://github.com/ClickHouse/ClickHouse/blob/9cd7e6155c7027baccd6dc5380d0813db94b03cc/src/Analyzer/QueryNode.h#L253-L364

**Comment by nikitamikhaylov** [comment]
@amosbird My goal is to unify the approach on how to manage AST and think about a way how to restrict all other ones.

**Pull request closed without merging**
