### PR TITLE
Experiment building jemalloc with profiling support for all builds to see how it impacts performance tests

### PR DESCRIPTION
**Pull request by nvartolomei**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Build/Packaging/Testing Improvement

Changelog entry:
Build `jemalloc` with support for [heap profiling](https://github.com/jemalloc/jemalloc/wiki/Use-Case%3A-Heap-Profiling).

Information about CI checks: https://clickhouse.tech/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by nvartolomei** [comment]
@akuzm what do you think about performance results? Any reasons not to have profiling available in default build?

**Comment by nvartolomei** [comment]
If I understand correctly CH's memory profiler is working only on query level. If we could use it for global server profiling then this wouldn't be really needed.

**Comment by akuzm** [comment]
> @akuzm what do you think about performance results? Any reasons not to have profiling available in default build?

The main problem we had with always-on embedded profiler was unstable query run times, which lead to false positives. Maybe it's less bad for embedded memory profiling or profiling with `jemalloc`. I'll try to calculate some metrics for this later, assigned myself not to forget.

@azat has a lot of experience with jemalloc, so maybe he has something to say.

In the meantime, maybe you can experiment with embedded memory profiler? The setting goes here: https://github.com/ClickHouse/ClickHouse/blob/master/docker/test/performance-comparison/config/users.d/perf-comparison-tweaks-users.xml#L4
IIRC it works for queries only, but in perf tests, there are not so many allocations in background. What exactly are you trying to profile, some merges?

It also may be interesting to add collecting the jemalloc results to the perf test scripts, so that we can see what it found. This should go somewhere here: https://github.com/ClickHouse/ClickHouse/blob/master/docker/test/performance-comparison/compare.sh#L305
IDK where jemalloc puts them, maybe they ended up in `output.7z` already...

You can do this in this PR, just don't force push, or it will be hard to find the old perf test data.

**Comment by alexey-milovidov** [comment]
> If I understand correctly CH's memory profiler is working only on query level.

We have global profiler as well, see `memory_profiler_*` in config.xml.

**Comment by nvartolomei** [comment]
@akuzm the goal is not to have always on profiling but instead have the jemalloc built with profiling support to allow end user to enable when needed without having to recompile clickhouse. 

I didn't enable profiling in this PR, just changed the a build flag to include build jemalloc with profiling support.

**Comment by akuzm** [comment]
> I didn't enable profiling in this PR, just changed the a build flag to include build jemalloc with profiling support.

I don't see any changes in performance, so probably we can merge this. We would prefer people using the builtin profiler, but another one doesn't hurt.

**Review by azat — APPROVED** [review]
>@azat has a lot of experience with jemalloc, so maybe he has something to say.

I think it worth enabling it in default build, since:
- right now memory allocated via malloc() (i.e. librdkafka and other C libraries) is not tracked by clickhouse
- it does not have significant overhead until enabled
- and plus jemalloc profiler is builtin in some distros by default (i.e. debian)

And just as a reminder, clickhouse uses mmap() internally and those will not be accounted by jemalloc profiler.

**Pull request merged**
