### PR TITLE
CLICKHOUSE-2724: website refactoring

### PR DESCRIPTION
**Pull request by blinkov**

### CODE REVIEW

**Comment by robot-metrika-test** [comment]
Can one of the admins verify this patch?

**Comment by alexey-milovidov** [comment]
1. We need to replace Telegram logo with something reasonable.
2. The page looks bad when browser window resized to 2560 pixels horizontally. Need to specify max-width.
3. ClickHouse and menu items on top must be aligned on same line at bottom.
4. Padding at right of top menu items should be more.
5. Padding from logo on left, top, bottom should be same.
6. Logo and "ClickHouse" are bad aligned to each other. Better to make "ClickHouse" exactly the same vertical size as the logo.
7. "ClickHouse is an free" - why "an free" and not "a free"?
8. "Quick start" and "Learn more" buttons: padding at left should be slightly less than at right, because now it is visually more due to arrow.

**Comment by alexey-milovidov** [comment]
9. Colors are too contrast/oppressive. Need to be more smooth.

**Comment by alexey-milovidov** [comment]
10. Quick start and main message above is not aligned vertically (top, bottom lines) with items at right.

**Comment by alexey-milovidov** [comment]
11. Filling "Fault tolerant" item with dark-gray is not motivated.

**Comment by alexey-milovidov** [comment]
12. "Use cases" using too small font size and outweight near elements.

**Comment by alexey-milovidov** [comment]
13. Contacts menu item is using animation. I don't like animation.

**Comment by blinkov** [comment]
1-2 done.

3 — the idea was to align them on middle line, not bottom. Tuned a bit.

4-8 done.

9 — colors are from logo and Yandex brand, we shouldn't invent our own. Though there was one shade of gray slightly darker than in original to be more readable — reverted this.

10 — done.

11-13 — the slow scroll is not just random animation, it gives user an opportunity to get a glympse of page content while scrolling. If something catches his/her eye (like those different styled blocks or images) maybe he/she will return there instead of just closing the website — in the end there's more time spent on website and more chance to remember something about it.

**Comment by robot-metrika-test** [comment]
Can one of the admins verify this patch?

**Comment by robot-metrika-test** [comment]
Can one of the admins verify this patch?

**Pull request closed without merging**
