### PR TITLE
Draft: Regular functions for time series analysis

### PR DESCRIPTION
**Pull request by LordVoldebug**
### Changelog category (leave one):
- New Feature

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Implementation of several regular functions for time series analysis.

Forecasters:

Signature:

methodName(series, number_to_predict, params, [fill_gaps]) -> Array[values]
methodName(series, times, times_to_predict, params, [fill_gaps]) -> Array[values]

seriesHolt
seriesAdditiveDamped
seriesMultiplicativeDamped
seriesHoltWintersMultiplicative
seriesHoltWintersAdditive
seriesHoltWintersDamped

Stationarity test:

seriesKPSS(series) -> KPSS value

Smoothing functions:

Signature: f(Array) -> Array
seriesEMA
seriesKaufmansAMA

seriesWindowMax
seriesWindowMin
seriesWindowSum
seriesWindowStandardDeviation

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

<details>
    <summary>Modify your CI run</summary>

**NOTE:** If your merge the PR with modified CI you **MUST KNOW** what you are doing
**NOTE:** Checked options will be applied if set before CI RunConfig/PrepareRunConfig step

#### Include tests (required builds will be added automatically):
- [ ]  Fast test
- [ ]  Integration Tests
- [ ]  Stateless tests
- [ ]  Stateful tests
- [ ]  Unit tests
- [ ]  Performance tests
- [ ]  All with ASAN
- [ ]  All with TSAN
- [ ]  All with Analyzer
- [ ]  All with Azure
- [ ]  Add your option here

#### Exclude tests:
- [ ]  Fast test
- [ ]  Integration Tests
- [ ]  Stateless tests
- [ ]  Stateful tests
- [ ]  Performance tests
- [ ]  All with ASAN
- [ ]  All with TSAN
- [ ]  All with MSAN
- [ ]  All with UBSAN
- [ ]  All with Coverage
- [ ]  All with Aarch64
- [ ]  Add your option here

#### Extra options:
- [ ]  do not test (only style check)
- [ ]  disable merge-commit (no merge from master before tests)
- [ ]  disable CI cache (job reuse)

#### Only specified batches in multi-batch jobs:
- [ ]  1
- [ ]  2
- [ ]  3
- [ ]  4

</details>

### CODE REVIEW

**Comment by robot-clickhouse-ci-2** [comment]
*This is an automated comment for commit fcb9f78be641fcc8c059c60c07b0ff578b6f24dd with description of existing statuses. It's updated for the latest CI running*

[❌ Click here](https://s3.amazonaws.com/clickhouse-test-reports/64240/fcb9f78be641fcc8c059c60c07b0ff578b6f24dd/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>❌ failure</td></tr>
<tbody>
</table>

**Comment by rschu1ze** [comment]
@LordVoldebug A silly question to begin with ... exponential smoothing needs to "see" the entire time series to produce a forecast (let's leave aside the point that with increasing smoothing factor, historical values become less relevant). Similarly, window-based functions need to see the N last values. Since query processing in ClickHouse is based on chunks and the chunks are processed in random order (not consecutively), how is this problem addressed in this PR?

**Comment by LordVoldebug** [comment]
Those are regular functions, not aggregate functions, and as far as i understood from the codebase and co

> @LordVoldebug A silly question to begin with ... exponential smoothing needs to "see" the entire time series to produce a forecast (let's leave aside the point that with increasing smoothing factor, historical values become less relevant). Similarly, window-based functions need to see the N last values. Since query processing in ClickHouse is based on chunks and the chunks are processed in random order (not consecutively), how is this problem addressed in this PR?


This was one of the first questions i faced myself while working on this.

Implemented functions are regular functions which accept arrays; not aggregate functions, and as far as i understood from the codebase and common sense, at the point where we are already given an array the order is fixed (if it is not, there are many functions that would not work...).

And when we need to extract data from the table to an Array, we can use functions like groupArray.  In groupArray there is such string in documentation:

https://clickhouse.com/docs/en/sql-reference/aggregate-functions/reference/grouparray


```In some cases, you can still rely on the order of execution. This applies to cases when SELECT comes from a subquery that uses ORDER BY if the subquery result is small enough.```

So it seems to be ok for most cases. Of course, those functions could have been implemented as aggregate functions, but i thought that the less functions with non strict guarantees, the better.

**Comment by rschu1ze** [comment]
Okay, that makes sense, thanks. There were similar considerations in earlier PRs that implement time series functions as regular functions, e.g. [here](https://github.com/ClickHouse/ClickHouse/pull/56171).

It is still not clear to me what is the best way to implement this. One could argue that "horizontalizing" the data into arrays is an unnecessary step. But that's something to discuss separately, it does not take away from your work (thanks for pushing the PR).

**Comment by UnamedRus** [comment]
I actually think, that implementing them as window (or aggregate) functions make sense. 
As WINDOW definition can have strict guarantees about ordering. 

BTW
> In some cases, you can still rely on the order of execution. This applies to cases when SELECT comes from a subquery that uses ORDER BY if the subquery result is small enough.

Applies for all aggregate functions, not only groupArray.
BTW, there are aggregate functions which internally build array of ts, value and do actual processing only after all data is consumed and sorted windowFunnel for example

**Pull request closed without merging**
