### PR TITLE
part log profile events

### PR DESCRIPTION
**Pull request by nvartolomei**
### Changelog category (leave one):
- New Feature

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Expose ProfileEvents counters in system.part_log

> Information about CI checks: https://clickhouse.tech/docs/en/development/continuous-integration/

---

Supersedes #34314

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
@novikd No review in a month, let's reassign.
@nvartolomei please fix conflicts.

**Comment by nvartolomei** [comment]
Unfortunately I’m not able to work on this in the near future and don’t
know anyone who could help. I’m fine to abandon/close the PR if you aren’t
interested either.

**Comment by alexey-milovidov** [comment]
The changes are not trivial but also not very complex. Maybe there is a chance to finish this PR.

**Comment by bharatnc** [comment]
I have cherry-picked the commits into `https://github.com/ClickHouse/ClickHouse/pull/38614`.
I will incorporate the changes suggested in: `https://github.com/ClickHouse/ClickHouse/pull/34314` and open it up for review so that it can be reviewed and merged.

**Pull request closed without merging**
