### PR TITLE
OpenTelemetry is not production-ready (yet)

### PR DESCRIPTION
**Pull request by alexey-milovidov**
### Changelog category (leave one):
- New Feature

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
The support for OpenTelemetry is production-ready.

CC @akuzm

### CODE REVIEW

**Comment by robot-clickhouse** [comment]
This is an automated comment for commit e7abb7f06964411509b73035251e218ded30f4ed with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/50023/e7abb7f06964411509b73035251e218ded30f4ed/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Docs Check</td><td>Builds and tests the documentation</td><td>🟡 pending</td></tr>
</table>

**Comment by tavplubix** [comment]
It's not: https://github.com/ClickHouse/ClickHouse/issues/49244

Also, it still crashes sometimes: https://github.com/ClickHouse/ClickHouse/issues/49185

**Comment by alexey-milovidov** [comment]
@tavplubix, we have no protection by a feature flag for this feature, and we use it in production.
The items described in the task is more like a wish-list for advancing the feature support.

**Comment by alexey-milovidov** [comment]
So, if you are think it is not production ready, you should introduce a feature flag, and disable it by default.

**Comment by FrankChen021** [comment]
@alexey-milovidov Before annoucing this feature as production ready, I think we should standardize the attribute names first, or it would cause backward compatibility  problem.

**Comment by alexey-milovidov** [comment]
@tavplubix advised not making it production-ready.

**Pull request closed without merging**
