### PR TITLE
Forbid invocations of `dlopen`

### PR DESCRIPTION
**Pull request by alexey-milovidov**
### Changelog category (leave one):
- Build/Testing/Packaging Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Don't allow `dlopen` in the main ClickHouse binary, because it is harmful and insecure. We don't use it. But it can be used by some libraries for the implementation of "plugins". We absolutely discourage the ancient technique of loading 3rd-party uncontrolled dangerous libraries into the process address space, because it is insane.

### CODE REVIEW

**Review by ghost — APPROVED** [review]
LGTM

**Comment by alexey-milovidov** [comment]
@zjpedu WTF

**Comment by alexey-milovidov** [comment]
#41450

**Comment by alexey-milovidov** [comment]
Tested manually:

```
milovidov-desktop :) SELECT trap('dlopen')

SELECT trap('dlopen')

Query id: 8d84a802-78c0-45fa-b99e-87fccdddc67d


0 rows in set. Elapsed: 0.003 sec. 

Received exception from server (version 22.9.1):
Code: 375. DB::Exception: Received from localhost:9000. DB::Exception: Cannot dlopen: (ClickHouse does not allow dynamic library loading): While processing trap('dlopen'). (CANNOT_DLOPEN)
```

**Pull request merged**
