### PR TITLE
Slightly better memory usage in `AsynchronousBoundedReadBuffer`

### PR DESCRIPTION
**Pull request by CurtizJ**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by CurtizJ** [comment]
In my example:
```
CREATE TABLE default.t_s3_normal
(
    `id` UInt64,
    `col0` String,
    `col1` String,
    `col2` String,
    `col3` String,
    `col4` String,
    `col5` String,
    `col6` String,
    `col7` String,
    `col8` String,
    `col9` String,
    `col10` String,
    `col11` String,
    `col12` String,
    `col13` String,
    `col14` String,
    `col15` String,
    `col16` String,
    `col17` String,
    `col18` String,
    `col19` String,
    `col20` String,
    `col21` String,
    `col22` String,
    `col23` String,
    `col24` String,
    `col25` String,
    `col26` String,
    `col27` String,
    `col28` String,
    `col29` String
)
ENGINE = MergeTree
ORDER BY id
SETTINGS storage_policy = 's3_cache', enable_vertical_merge_algorithm = 0, index_granularity = 8192
```

Before:
``` sql
SELECT count() FROM t_s3_normal WHERE NOT ignore(*)
```
```
1 row in set. Elapsed: 0.758 sec. Processed 10.00 million rows, 8.78 GB (13.19 million rows/s., 11.58 GB/s.)
Peak memory usage: 1.69 GiB.
```

After:
```sql
SELECT count() FROM t_s3_normal WHERE NOT ignore(*)
```

```
┌──count()─┐
│ 10000000 │
└──────────┘

1 row in set. Elapsed: 0.906 sec. Processed 10.00 million rows, 8.78 GB (11.04 million rows/s., 9.69 GB/s.)
Peak memory usage: 1.56 GiB.
```

130 MiB less.

**Comment by robot-ch-test-poll1** [comment]
*This is an automated comment for commit 182d1c08b8c1bc28d17b64858e4a4376bea27bce with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/59354/182d1c08b8c1bc28d17b64858e4a4376bea27bce/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/59354/182d1c08b8c1bc28d17b64858e4a4376bea27bce/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Comment by CurtizJ** [comment]
In my example:

```sql
CREATE TABLE default.t_s3_normal
(
    `id` UInt64,
    `col0` String,
    `col1` String,
    `col2` String,
    `col3` String,
    `col4` String,
    `col5` String,
    `col6` String,
    `col7` String,
    `col8` String,
    `col9` String,
    `col10` String,
    `col11` String,
    `col12` String,
    `col13` String,
    `col14` String,
    `col15` String,
    `col16` String,
    `col17` String,
    `col18` String,
    `col19` String,
    `col20` String,
    `col21` String,
    `col22` String,
    `col23` String,
    `col24` String,
    `col25` String,
    `col26` String,
    `col27` String,
    `col28` String,
    `col29` String
)
ENGINE = MergeTree
ORDER BY id
SETTINGS storage_policy = 's3_cache', enable_vertical_merge_algorithm = 0, index_granularity = 8192
```

Before:
```sql
SELECT count()
FROM t_s3_normal
WHERE NOT ignore(*)
```
```
Query id: fec77400-5ff6-4e2b-be3d-6e52942caf16

┌──count()─┐
│ 10000000 │
└──────────┘

1 row in set. Elapsed: 0.784 sec. Processed 10.00 million rows, 8.78 GB (12.76 million rows/s., 11.21 GB/s.)
Peak memory usage: 1.68 GiB.
```

After:
```sql
SELECT count()
FROM t_s3_normal
WHERE NOT ignore(*)
```
```
Query id: 255f2a2b-51ac-486e-a861-03340c8e4912

┌──count()─┐
│ 10000000 │
└──────────┘

1 row in set. Elapsed: 0.775 sec. Processed 10.00 million rows, 8.78 GB (12.91 million rows/s., 11.33 GB/s.)
Peak memory usage: 1.57 GiB.
```

110 MiB less

**Review by jsc0218 — APPROVED** [review]

**Comment by nickitat** [comment]
since the set of objects to read in `impl` is constant, am I right that the idea is only to allocate lazily?

**Review by alexey-milovidov — APPROVED** [review]

**Comment by CurtizJ** [comment]
@nickitat the idea is that we don't need `prefetech_buffer` and `memory` simultaneously and we can allocate only one of them.

**Pull request merged**
