### PR TITLE
Improvement of Materialize TTL

### PR DESCRIPTION
**Pull request by lthaooo**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
   improve Materialize TTL by recalculating ttl.txt only without actual ttl action

Detailed description / Documentation draft:
  When we execute ALTER MODIFY TTL query with materialize_ttl_after_modify = true (by default),
a MATERIALIZE_TTL mutation will be invoked to remove expired data and recalculate ttl.txt in all parts. 

  This will cause large amount of r/w io because most of the data not expired. Maybe we just need to recalculate ttl.txt and copy all columns by hardlinks.

  And some time later, expired data will be drop lightly during merge with ttl_only_drop_parts = true

#20338 
#26316 
#26319

### CODE REVIEW

**Comment by lthaooo** [comment]
i forgot to modify test cases about ttl

**Comment by lthaooo** [comment]
I have finished testing. There were still some fail test cases, but they seem to have nothing to do with this PR.
@alesapin

**Comment by lthaooo** [comment]
can anyone review this PR ?

**Comment by lthaooo** [comment]
Hi, could you assign someone else to  review this PR @alexey-milovidov

**Comment by alesapin** [comment]
> Hi, could you assign someone else to review this PR @alexey-milovidov

Sorry, I was on vacation. I'll make a review soon.

**Comment by alesapin** [comment]
@mergifyio update

**Review by alesapin — APPROVED** [review]

**Comment by FrankChen021** [comment]
I got a question. 

If `materialize_ttl_recalculate_only=1` is applied, the materialized ttl mutation will create a copy of all old parts and update the ttl.txt for the new parts. If there's a very large table, for example already taking 40% size of whole disk, modifying TTL will cause the disk consumption up to 80%, under such case the whole disk might be exhausted considering other tables consumption.

By default the old parts will be deleted from the system after 480 seconds(controlled by `old_parts_lifetime`), during this 8 minutes, the system might be out of disk and can't accept new inserts.

Do you have any suggestion in such case? If it's possible to delete old part immediately once its corresponding mutation is finished? @lthaooo @alesapin

**Comment by lthaooo** [comment]
> I got a question.
> 
> If `materialize_ttl_recalculate_only=1` is applied, the materialized ttl mutation will create a copy of all old parts and update the ttl.txt for the new parts. If there's a very large table, for example already taking 40% size of whole disk, modifying TTL will cause the disk consumption up to 80%, under such case the whole disk might be exhausted considering other tables consumption.
> 
> By default the old parts will be deleted from the system after 480 seconds(controlled by `old_parts_lifetime`), during this 8 minutes, the system might be out of disk and can't accept new inserts.
> 
> Do you have any suggestion in such case? If it's possible to delete old part immediately once its corresponding mutation is finished? 

If materialize_ttl_recalculate_only=1  is applied, only columns in TTL expression will be copied, other columns will be hard linked
@FrankChen021

**Comment by FrankChen021** [comment]
Hi @lthaooo Thanks for the response. 

I checked the directory again, all columns are not hard linked. The `20221109_15_15_0_18` is the new part while the other is an old part.

image

Did I miss sth?

**Comment by FrankChen021** [comment]
Oh, the part_type of my table is compact. That's the reason.

**Pull request merged**
