### PR TITLE
Add isort to the style checking for python files

### PR DESCRIPTION
**Pull request by Felixoid**
### Changelog category (leave one):
- CI Fix or Improvement (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
`isort` is a simple import sorter for the python to comply [pep-8](https://peps.python.org/pep-0008/#imports) requirements. It will allow to decrease conflicts during sync and beautify the code. The import block is divided into three sub-blocks: `standard library` -> `third-party libraries` -> `local imports` -> `.local imports`. Each sub-block is ordered alphabetically with sub-sub-blocks `import X` -> `from X import Y`.

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [x]  Exclude Timeouting flaky tests, they all changed
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Run only fuzzers related jobs (libFuzzer fuzzers, AST fuzzers, etc.)
- [ ]  Exclude: AST fuzzers
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by Felixoid** [comment]
The actual changes are added in https://github.com/ClickHouse/ClickHouse/pull/70038/commits/5ebd4b2bd75eac4946f5a262cd4ca0777aa89ebd

**Comment by robot-ch-test-poll** [comment]
*This is an automated comment for commit 5ebd4b2bd75eac4946f5a262cd4ca0777aa89ebd with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/70038/5ebd4b2bd75eac4946f5a262cd4ca0777aa89ebd/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Push to Dockerhub</td><td>The check for building and pushing the CI related docker images to docker hub</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/70038/5ebd4b2bd75eac4946f5a262cd4ca0777aa89ebd/push_to_dockerhub_aarch64.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Comment by Felixoid** [comment]
Yeeeeeah! Autofix works https://github.com/ClickHouse/ClickHouse/pull/70038/commits/ed9907f31c226f8bde06b25960fab371122f05e7

**Comment by Felixoid** [comment]
Flaky tests are disabled for the PR. They will fail, since a lot of them are changed

**Comment by maxknv** [comment]
what is the point of this autofixer?

**Comment by Felixoid** [comment]
It organizes imports into ordered blocks.

1. Reduces conflicts
2. looks nice

image
image
image

**Comment by maxknv** [comment]
> It organizes imports into ordered blocks.
> 
> 1. Reduces conflicts
If you work in the same file with someone you are likely to have conflicts with or without auto sorting of "imports"

> 2. looks nice
Sorted imports looks nicer, agree. CI stumbling on unexpected auto commits - does not.

**Comment by Felixoid** [comment]
> CI stumbling over unexpected auto commits - no.

People should just consider sorted imports a requirement for the code. It's lovely that we have a tool to automate this toil.

**Review by pufit — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
Thanks. To be honest, I don't care about it at all. But I'm not a Python engineer, so I think this change is ok to have.

**Pull request merged**
