### PR TITLE
[DOC] Add support for signed arguments in range() #43333

### PR DESCRIPTION
**Pull request by wineternity**
### Changelog category (leave one):
- Documentation (changelog entry is not required)

Related to #43333

### CODE REVIEW

**Comment by wineternity** [comment]
hi @CheSema , the related document for function range() need to be changed, please help check.

**Comment by CheSema** [comment]
@hanfei1991 Hi, coud you please look at this? I am limited with g-translate with chinese. :)

**Comment by wineternity** [comment]
@hanfei1991, hi, could you help review?

**Review by hanfei1991 — APPROVED** [review]
LGTM

**Pull request merged**
