### PR TITLE
Datasketches support (cmake part)

### PR DESCRIPTION
**Pull request by pingyu**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- New Feature (datasketches support in clickhouse #14893)

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Support ThetaSketch to do set operations.

Detailed description / Documentation draft:
Support ThetaSketch to do set operations, including union, intersection, and difference.

### CODE REVIEW

**Comment by dengc367** [comment]
Great Job, who can merge it, and start to use the set function with `datasketches` library.

**Comment by alexey-milovidov** [comment]
There is a strange recursive submodule somewhere:
```
../../wjakob/clang-cindex-python3
```

**Comment by alexey-milovidov** [comment]
I will make a fork to ClickHouse-Extras and remove the recursive submodule.

**Review by alexey-milovidov — APPROVED** [review]
Now LGTM.

**Pull request merged**
