### PR TITLE
Add DataTypeMap support LowCardinality and FixedString type

### PR DESCRIPTION
**Pull request by hexiaoting**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Support `LowCardinality` and `FixedString` keys/values for `Map` type.

Detailed description / Documentation draft:
related to  issue: https://github.com/ClickHouse/ClickHouse/issues/21406

### CODE REVIEW

**Review by KochetovNicolai — APPROVED** [review]
LGTM
Does `Map(LowCardinality(String), LowCardinality(String))` store columns in LC format?

**Comment by KochetovNicolai** [comment]
Does not look like a fix. We may not have local replica at all.

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
@mergifyio update

**Comment by gyuton** [comment]
Internal documentation ticket: DOCSUP-11584.

**Pull request merged**
