### PR TITLE
Fix bug in pooled sessions and host ip change

### PR DESCRIPTION
**Pull request by alesapin**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

For changelog. Remove if this is non-significant change.

Category (leave one):

- Bug Fix

Short description (up to few sentences):
Fixed error when replication connection pool doesn't retry to resolve host, even when DNS cache was dropped.

### CODE REVIEW

**Comment by alesapin** [comment]
Performance fail is inconsistent.

**Comment by alesapin** [comment]
Fixes https://github.com/yandex/ClickHouse/issues/5287.

**Comment by abraithwaite** [comment]
Thanks!  I'm glad you found a way that doesn't get rid of the DNS cache.

I'm curious, does this affect or relate to #5508 that Alexey opened?

I noticed that this requires `getSession` be called to reset the host IP.  Are we certain that clickhouse does that everywhere before using session pools?

If it's done everywhere now, are you concerned that down the line a subsystem might call `getSession` only once for some reason?

In any case, thanks for the fix!  We look forward to trying this in our own clusters.

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alesapin** [comment]
Session pool is used only for replication:  https://github.com/yandex/ClickHouse/blob/master/dbms/src/Storages/MergeTree/DataPartsExchange.cpp#L190. It doesn't affect related https://github.com/yandex/ClickHouse/issues/5508.

**Pull request merged**
