### PR TITLE
Allow using cluster, clusterAllReplicas, remote, and remoteSecure without table name

### PR DESCRIPTION
**Pull request by LiuYangkuan**
issue #50808 

### Changelog category (leave one):
- New Feature

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Allow using cluster, clusterAllReplicas, remote, remoteRaw and remoteSecure without table name in  issue #50808.

### Documentation entry for user-facing changes

- [x] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by robot-ch-test-poll** [comment]
This is an automated comment for commit 394cd77cd12f4692cb3f8c3e2ea0dac0367be5a2 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/50848/394cd77cd12f4692cb3f8c3e2ea0dac0367be5a2/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Docs Check</td><td>Builds and tests the documentation</td><td>🟡 pending</td></tr>
</table>

**Comment by alexey-milovidov** [comment]
Ok, but I highly doubt the need for `remoteRaw`. The existence of an additional function increases complexity.
Maybe we can get away with something simpler?

**Comment by LiuYangkuan** [comment]
> 

Another solution for the problem of incompatible settings between different version servers, is providing a user level settings to reset these incompatible settings.

**Comment by LiuYangkuan** [comment]
> Ok, but I highly doubt the need for `remoteRaw`. The existence of an additional function increases complexity. Maybe we can get away with something simpler?

@alexey-milovidov This PR only implement issue #50808, please review it.
 The problem of incompatible settings between servers with different versions will be submit another PR using a query settings.

**Review by alexey-milovidov — APPROVED** [review]

**Review by alexey-milovidov — APPROVED** [review]

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
```
Jul 27 10:17:21         if ((!is_cluster_function && args.size() < 1) || args.size() > max_args)
Jul 27 10:17:21                                      ^~~~~~~~~~~~~~~
Jul 27 10:17:21                                      args.empty()
Jul 27 10:17:21 /build/contrib/abseil-cpp/absl/container/inlined_vector.h:266:8: note: method 'InlinedVector'::empty() defined here
Jul 27 10:17:21   bool empty() const noexcept { return !size(); }
Jul 27 10:17:21        ^
Jul 27 10:17:21 /build/src/TableFunctions/TableFunctionRemote.cpp:136:17: error: the 'empty' method should be used to check for emptiness instead of 'size' [readability-container-size-empty,-warnings-as-errors]
Jul 27 10:17:21             if (args.size() > 0)
Jul 27 10:17:21                 ^~~~~~~~~~~~~~~
Jul 27 10:17:21                 !args.empty()
```

**Comment by alexey-milovidov** [comment]
@LiuYangkuan, it requires minor changes.

**Comment by alexey-milovidov** [comment]
I've fixed this error.

**Review by alexey-milovidov — APPROVED** [review]

**Pull request merged**
