### PR TITLE
Replace remove-erase idiom by C++20 erase()/erase_if()

### PR DESCRIPTION
**Pull request by rschu1ze**
- makes the code less verbose while being as efficient

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
Thank you! LGTM.

I've added "can be tested" label to run tests. But it did not start the tests.
Two options exists:
1. Make an empty commit (or merge with master) then the tests will be triggered.
2. Wait for @Felixoid who is the expert in CI infrastructure and can figure out why tests did not run.

He also made a nice picture being overwhelmed by my complaints about the behavior of "can be tested" label:

sticker

**Comment by alexey-milovidov** [comment]
> test_storage_postgresql_replica

Let's check if it is fixed in master. @mergifyio update

**Comment by alexey-milovidov** [comment]
Integration test `test_storage_postgresql_replica` has failed, need help from @kssenii

**Comment by kssenii** [comment]
> Integration test test_storage_postgresql_replica has failed, need help from @kssenii

https://github.com/ClickHouse/ClickHouse/pull/36631 (temporarily)

**Pull request merged**
