### PR TITLE
Reduce shared ptr atomic update contention in pipe node creation.

### PR DESCRIPTION
**Pull request by jiebinn**
### Changelog category (leave one):
- Performance Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Reduce shared ptr atomic update contention in pipe node creation.

### CODE REVIEW

**Comment by jiebinn** [comment]
This is a draft patch, which could help to work around the performance issue in shared_ptr atomic update contention.

The former performance [patch](https://github.com/ClickHouse/ClickHouse/pull/57853) could have a big performance improvement on Clickbench Q29. I have tested the performance of Q29 on 160 vCPUs system and this patch will have 10x QPS gain. However, I have found that the QPS does not scale as the CPU cores increase.
image

**Comment by jiebinn** [comment]
Hi @alexey-milovidov , the atomic lock contention of DataType shared_ptr problem is happened in frontend compiling stage. Do you think that it will affect real customer workload? If that's important for real customer workload, then we might need to put effort on that. I have summarized three possible directions to mitigate the lock contention issue. But we need to know which is the right way. Do you have any good idea?

**Comment by nickitat** [comment]
@jiebinn thank you for looking at this.
I think here we're trying to address too niche case (when we have so many functions to calculate) and there is clear and clean solution for this.
ATST I think it makes a lot of sense to analyse scalability bottlenecks.

**Comment by jiebinn** [comment]
@nickitat Agree with that. The future server CPUs have more and more cores. I will keep to resolve scalability performance issue, especially at high core count.

**Pull request closed without merging**
