### PR TITLE
Fix memory leak in registerDiskS3

### PR DESCRIPTION
**Pull request by Jokser**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fixed memory leak in registerDiskS3

Detailed description / Documentation draft:
Memory leak in registerDiskS3 that was found here https://github.com/ClickHouse/ClickHouse/pull/11029#issuecomment-630641497 is fixed.
Improved S3 proxy resolver error handling and usability

### CODE REVIEW

**Comment by azat** [comment]
@Jokser Maybe test with unavailable S3 worth adding? (that triggers the initial issue)

**Comment by alexey-milovidov** [comment]
+1, let's add a test that can reproduce the leak before this change (no need to validate it, just let's add this test case).

**Comment by alesapin** [comment]
This leak can be detected with `test_replicated_merge_tree_s3/test.py::test_insert_select_replicated` (can be found on current master).

**Comment by azat** [comment]
>Thie leak issue can be detected with test_replicated_merge_tree_s3/test.py::test_insert_select_replicated (can be found on current master).

@alesapin AFAIU it will trigger the issue only when s3 (minio) will not be available, am I missing something?

For example [this](https://clickhouse-test-reports.s3.yandex.net/11048/e8a13842afc9e40c3a693d983d1edb1830ac2dcc/integration_tests_(asan).html) build does not have this patch and successfully passes (And the problem that the leak happens [only on abnormal shutdown](https://github.com/ClickHouse/ClickHouse/issues/10775#issuecomment-631045758))

**Pull request merged**
