### PR TITLE
build fix

### PR DESCRIPTION
**Pull request by Vxider**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
What exactly does it fix?

**Comment by Vxider** [comment]
build fails when trying to use SettingsChanges::changes()  due to ctor deduction failure

**Comment by alexey-milovidov** [comment]
What build exactly and for what reason?
We have build check in CI and all supported builds have passed: https://clickhouse-builds.s3.yandex.net/6509/c52a34fd15bc834ab40c8ef91ee281a89d58e2b3/report.html

**Comment by Vxider** [comment]
The build check is passed because this function is not called in ClickHouse. Build the following example with g++-8 will encounter the error.

```
#include <iostream>
#include <vector>

using namespace std;

using String = std::string;

struct SettingChange {
    String name;
    int value;
};

using SettingsChanges = std::vector<SettingChange>;

int main() {
    String name= "test";
    int value = 0;
    SettingsChanges found_changes;
    found_changes.emplace_back(name, value);
    return 0;
}
```

Error:

```
/usr/local/Cellar/gcc@8/8.3.0/include/c++/8.3.0/ext/new_allocator.h:136:4: error: no matching function for call to 'SettingChange::SettingChange(std::__cxx11::basic_string<char>&, int&)'
  { ::new((void *)__p) _Up(std::forward<_Args>(__args)...); }
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
test.cpp:8:8: note: candidate: 'SettingChange::SettingChange()'
```

**Comment by alexey-milovidov** [comment]
Thank you!

**Pull request merged**
