### PR TITLE
Retry NoMessageException in DataPartsExchange

### LINKED ISSUE #4047: Poco::Exception. Code: 1000, e.code() = 0
Using docker clickhouse-server:latest

After upgrade - we have many error-log entries such as:

2019.01.14 02:24:10.831297 [ 17 ] {} <Error> graphite.metrics_lr (StorageReplicatedMergeTree): DB::StorageReplicatedMergeTree::queueTask()::<lambda(DB::StorageReplicatedMergeTree::LogEntryPtr&)>: Poco::Exception. Code: 1000, e.code() = 0, e.displayText() = No message received, e.what() = No message received
2019.01.14 02:24:20.916719 [ 7 ] {} <Error> graphite.metrics_lr (StorageReplicatedMergeTree): DB::StorageReplicatedMergeTree::queueTask()::<lambda(DB::StorageReplicatedMergeTree::LogEntryPtr&)>: Poco::
Exception. Code: 1000, e.code() = 0, e.displayText() = No message received, e.what() = No message received

2019.01.14 02:24:26.813686 [ 4 ] {} <Error> graphite.data_lr (StorageReplicatedMergeTree): DB::StorageReplicatedMergeTree::queueTask()::<lambda(DB::StorageReplicatedMergeTree::LogEntryPtr&)>: Poco::Exception. Code: 1000, e.code() = 0, e.displayText() = No message received, e.what() = No message received

2019.01.14 02:24:32.580035 [ 16 ] {} <Error> graphite.data_lr (StorageReplicatedMergeTree): DB::StorageReplicatedMergeTree::queueTask()::<lambda(DB::StorageReplicatedMergeTree::LogEntryPtr&)>: Poco::Exception. Code: 1000, e.code() = 0, e.displayText() = No message received, e.what() = No message received

### PR DESCRIPTION
**Pull request by nvartolomei**
If a connection from connection pool is idle for too long the server
will try to close it, leaving the socket in CLOSE-WAIT state. As there
is no connection manager that will poll connections to check if they are
still alive there is a chance that we'll get a connection in this state
out of the pool. Writing to a socket in CLOSE-WAIT can succeed, and
Poco's test for keep alive timeout doesn't seem to work correctly.

Solution: retry this error until we succeed. Poco will create new
connections for us.
Alternative solution: Try to peek one byte from connection before
returning it from the pool, may look cleaner, but there is still a very
low chance of connection getting closed by the time we try to read from
it.

strace example:

```
218921 sendto(546, "POST /?endpoint=DataPartsExchang"..., 207, 0, NULL, 0 <unfinished ...>
218921 <... sendto resumed> )           = 207
218921 recvfrom(546,  <unfinished ...>
218921 <... recvfrom resumed> "", 4096, 0, NULL, NULL) = 0
218921 close(546 <unfinished ...>
218921 <... close resumed> )            = 0
218921 write(2, "2019.03.28 18:01:54.082307 [ 27 "..., 315 <unfinished ...>
```

and log message:

```
2019.03.28 18:01:54.082307 [ 27 ] {} <Error> table_name (StorageReplicatedMergeTree): DB::StorageReplicatedMergeTree::queueTask()::<lambda(DB::StorageReplicatedMergeTree::LogEntryPtr&)>: Poco::Exception. Code: 1000, e.code() = 0, e.displayText() = No message received, e.what() = No message received
```

Closes #4047.

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

### CODE REVIEW

**Comment by nvartolomei** [comment]
Didn't have time to test, feel free to update PR and merge it as it fits.

**Comment by nvartolomei** [comment]
Another alternative solution would be to make underlying class smarter and retry this error for idempotent requests as most http clients do and use GET for data exchange.

**Comment by alesapin** [comment]
@nvartolomei Do you have any ideas how to reproduce this problem in test?

**Comment by alesapin** [comment]
Also I don't understand why this (implemented) solution will help:
```
retry this error until we succeed. Poco will create new
connections for us.
```
We will not create new Poco sessions if session for this `schema://URI:port` is already in pool https://github.com/yandex/ClickHouse/blob/master/dbms/src/IO/HTTPCommon.cpp#L149-L153. 
Maybe you've observed a case when pool was not completely filled?
```
If a connection from connection pool is idle for too long the server
will try to close it, leaving the socket in CLOSE-WAIT state.
```
Maybe I don't understand correctly, but isn't it the main function of `HTTP keep-alive` to avoid such situation? Is Poco's implementation completely wrong?

**Comment by nvartolomei** [comment]
> We will not create new Poco sessions if session for this schema://URI:port is already in pool

We don't have to. [receiveResponse](https://github.com/ClickHouse-Extras/poco/blob/d0271f990869b7f23dac4bb2ee0c127cf815f077/Net/src/HTTPClientSession.cpp#L279) closes the connection on exception.

If we get the same http session from the pool. [sendRequest creates a new connection](https://github.com/ClickHouse-Extras/poco/blob/d0271f990869b7f23dac4bb2ee0c127cf815f077/Net/src/HTTPClientSession.cpp#L201) if underlying socket is closed or keep alive is timeout is expired.

> Maybe you've observed a case when pool was not completely filled?

The pool is filled.

> Isn't it the main function of HTTP keep-alive to avoid such situation? Is Poco's implementation completely wrong?

From my understanding keep-alive on server side will keep the connection open for keep-alive timeout, but close it after that. Poco implementation seems fine.

> Do you have any ideas how to reproduce this problem in test?

Not really.

**Comment by nvartolomei** [comment]
One thing that is missing: not respecting the timeouts in this `for (;;)` loop. If for some reason the server goes rogue we won't have a clear error in logs and replication_queue table.

**Comment by alesapin** [comment]
```From my understanding keep-alive on server side will keep the connection open for keep-alive timeout, but close it after that. Poco implementation seems fine.```

Our default `keep_alive_timeout` is 3 seconds https://github.com/yandex/ClickHouse/blob/master/dbms/programs/server/config.xml#L88 for Interserver handler https://github.com/yandex/ClickHouse/blob/master/dbms/programs/server/InterserverIOHTTPHandler.cpp#L65. If we will reuse session from pool which is idle for more than 3 seconds we should receive `No message received` error. 

I performed experiment:
1) Added debug prints to Pool, just to be sure that we reuse session:
```
--- a/dbms/src/Common/PoolBase.h
+++ b/dbms/src/Common/PoolBase.h
@@ -113,11 +113,15 @@ public:
         {
             for (auto & item : items)
                 if (!item->in_use)
+                {
+                    LOG_INFO(&Logger::get("POOL"), "reusing old session");
                     return Entry(*item);
+                }
 
             if (items.size() < max_items)
             {
                 ObjectPtr object = allocObject();
+                LOG_INFO(&Logger::get("POOL"), "allocating new session");
                 items.emplace_back(std::make_shared<PooledObject>(object, *this));
                 return Entry(*items.back());
             }
```
2) Setup replicated table on two clickhouse-servers.
3) Filled pool with inserts.
3) Sleep for 5 minutes.
4) Perform single insert on one of nodes, log:
```
2019.03.29 12:50:43.706506 [ 10 ] {} <Information> POOL: reusing old session
2019.03.29 12:50:43.706556 [ 10 ] {} <Trace> ReadWriteBufferFromHTTP: Sending request to http://node3:9009/?endpoint=DataPartsExchange%3A%2Fclickhouse%2Ftables%2Ftest2%2Freplicated%2Freplicas%2Fnode3&part=20170617_0_0_0&compress=false
2019.03.29 12:50:43.721914 [ 10 ] {} <Trace> default.test_table (Data): Renaming temporary part tmp_fetch_20170617_0_0_0 to 20170617_0_0_0.
2019.03.29 12:50:43.724646 [ 10 ] {} <Debug> default.test_table (StorageReplicatedMergeTree): Fetched part 20170617_0_0_0 from /clickhouse/tables/test2/replicated/replicas/node3
2019.03.29 12:50:53.804169 [ 46 ] {} <Trace> TCPHandlerFactory: TCP Request. Address: 172.24.0.1:36346
2019.03.29 12:50:53.804698 [ 46 ] {} <Debug> TCPHandler: Connected ClickHouse client version 19.5.0, revision: 54417, user: default.
```

**Comment by alesapin** [comment]
Don't merge please, I'm investigation the issue.

**Comment by alesapin** [comment]
Better fix https://github.com/yandex/ClickHouse/pull/4856.

**Comment by nvartolomei** [comment]
@alesapin I'd argue that this is still needed (in one form or another) and #4856 is just a hack to make it work for that specific use case. This exception would still be generated if one ClickHouse server for one reason or another has different keep alive settings, or as I mentioned in #4856 because of clock drifts.

**Pull request closed without merging**
