### PR TITLE
Use src_type for conversion in KeyCondition

### LINKED ISSUE #6287: Select DateTime less Date doesn't work
Comparison DateTime and Date in SELECT doesn't work
When I limit DateTime from below it works normally. But limit on top - doesn't work
Select

### PR DESCRIPTION
**Pull request by oandrew**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Make use of `src_type` for correct type conversion in key conditions. Fixes #6287

Detailed description / Documentation draft:
Make use of `src_type` for correct type conversion in key conditions
Fixes #6287 ?

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
Do you want to add a test?

**Comment by oandrew** [comment]
It might be worth investigating why it was working for  `>` and broken for  `<`  condition

**Comment by oandrew** [comment]
@alexey-milovidov  tests look good

**Review by CurtizJ — APPROVED** [review]
LGTM

**Comment by CurtizJ** [comment]
> It might be worth investigating why it was working for `>` and not working for `<` condition

It was, because in case of `>` `KeyCondition` considers to read granule, because it thinks that its any value is greater than date value and then data is filtered properly, but in case of `<`  granule was skipped at all.

**Pull request merged**
