### PR TITLE
Add `current_user` alias

### PR DESCRIPTION
**Pull request by yariks5s**
Added `current_user` as a compatibility alias for MySQL.
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Added `current_user` function as a compatibility alias for MySQL.

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

---
### Modify your CI run:
**NOTE:** If your merge the PR with modified CI you **MUST KNOW** what you are doing
**NOTE:** Set desired options before CI starts or re-push after updates

#### Run only:
- [ ]  Integration tests
- [ ]  Integration tests (arm64)
- [x]  Stateless tests (release)
- [ ]  Stateless tests (asan)
- [ ]  Stateful tests (release)
- [ ]  Stateful tests (asan)
- [ ]  No sanitizers
- [x]  Tests with analyzer
- [ ]  Fast tests
- [ ]  Only package_debug build
- [ ]  Add your CI variant description here

#### CI options:
- [ ]  do not test (only style check)
- [ ]  disable merge-commit (no merge from master before tests)
- [ ]  disable CI cache (job reuse)

#### Only specified batches in multi-batch jobs:
- [ ]  1
- [ ]  2
- [ ]  3
- [ ]  4

### CODE REVIEW

**Comment by robot-ch-test-poll1** [comment]
*This is an automated comment for commit 5c082a8cc52dfeeadeec89bcc38ef17d10c4855b with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/61770/5c082a8cc52dfeeadeec89bcc38ef17d10c4855b/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

**Comment by alexey-milovidov** [comment]
Add a test.

**Comment by johnnymatthews** [comment]
Don't forget to add docs to https://clickhouse.com/docs/en/sql-reference/functions/other-functions#currentUser.

**Review by johnnymatthews — APPROVED** [review]
Approving the docs section of this PR. I'll leave it to the engineers to approve the actual code.

**Review by alexey-milovidov — APPROVED** [review]

**Comment by yariks5s** [comment]
The current test turned out to be flaky. I will just add a test that `current_user() = currentUser()` instead and will check the root cause of this strange behavior in one of the next PRs.

**Pull request merged**
