### PR TITLE
Documentation/Installation: Fixed bug in the example of using apt-key

### PR DESCRIPTION
**Pull request by SevaCode**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
1. Need to make it consistent with the instruction on https://clickhouse.yandex/
2. Check that it works on Ubuntu Precise (Docker).

**Comment by SevaCode** [comment]
> What does this change mean?
> Why it doesn't work without this change?

Description of  **--keyserver** option from `man gpg`

```
       --keyserver name
              This option is deprecated - please use the --keyserver in ‘dirmngr.conf’ instead.

              Use  name as your keyserver. This is the server that --receive-keys, --send-keys, and --search-keys will communicate with to receive keys from, send keys to, and search for keys on. The
              format of the name is a URI: `scheme:[//]keyservername[:port]' The scheme is the type of keyserver: "hkp" for the HTTP (or compatible) keyservers, "ldap" for  the  LDAP  keyservers,  or
              "mailto"  for  the Graff email keyserver. Note that your particular installation of GnuPG may have other keyserver types available as well. Keyserver schemes are case-insensitive. After
              the keyserver name, optional keyserver configuration options may be provided. These are the same as the global --keyserver-options from below, but apply only  to  this  particular  key‐
              server.

              Most  keyservers  synchronize with each other, so there is generally no need to send keys to more than one server. The keyserver hkp://keys.gnupg.net uses round robin DNS to give a dif‐
              ferent keyserver each time you use it.

```

**scheme** is mandatory.
**port** is optional, but the default port is 11371, not 80.

**Comment by alexey-milovidov** [comment]
Ok. I have checked that it works fine on old system (Ubuntu 12.04).

**Comment by alexey-milovidov** [comment]
Do we need to also modify `website/index.html`?

**Comment by SevaCode** [comment]
> Do we also need to modify `website/index.html`?

Done.

**Pull request merged**
