### PR TITLE
Added support for schema inference for `hdfsCluster` [2]

### PR DESCRIPTION
**Pull request by nikitamikhaylov**
Changelog category (leave one):

- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Added support for schema inference for `hdfsCluster`.

> Information about CI checks: https://clickhouse.tech/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by qoega** [comment]
@mergifyio update

**Comment by Dstiers11091** [comment]
Click

Derek stiers

**Comment by nikitamikhaylov** [comment]
@Mergifyio update

**Comment by tavplubix** [comment]
Hadoop prints trash to tests log:
```
2022-06-27 05:21:29 00345_index_accurate_comparison:                                        [ OK ] 0.49 sec.
2022-06-27 05:21:30 00338_replicate_array_of_strings:                                       [ OK ] 0.40 sec.
2022-06-27 05:21:30,369 INFO BlockStateChange: BLOCK* processReport 0x84a5eff10894cd08: from storage DS-834c86df-9f25-4de0-8ec5-8423664e7325 node DatanodeRegistration(127.0.0.1:46163, datanodeUuid=016cf04d-2f4d-42ca-bab3-54945fbe4d25, infoPort=32843, infoSecurePort=0, ipcPort=46049, storageInfo=lv=-57;cid=testClusterID;nsid=575950195;c=1656328155273), blocks: 0, hasStaleStorage: false, processing time: 1 msecs, invalidatedBlocks: 0
2022-06-27 05:21:30,369 INFO BlockStateChange: BLOCK* processReport 0x84a5eff10894cd08: from storage DS-13c69541-a384-4aaf-a268-c07b7ad093c4 node DatanodeRegistration(127.0.0.1:46163, datanodeUuid=016cf04d-2f4d-42ca-bab3-54945fbe4d25, infoPort=32843, infoSecurePort=0, ipcPort=46049, storageInfo=lv=-57;cid=testClusterID;nsid=575950195;c=1656328155273), blocks: 0, hasStaleStorage: false, processing time: 0 msecs, invalidatedBlocks: 0
2022-06-27 05:21:30,370 INFO datanode.DataNode: Successfully sent block report 0x84a5eff10894cd08 to namenode: localhost/127.0.0.1:12222,  containing 2 storage report(s), of which we sent 2. The reports had 0 total blocks and used 1 RPC(s). This took 0 msecs to generate and 2 msecs for RPC and NN processing. Got back one command: FinalizeCommand/5.
2022-06-27 05:21:30,370 INFO datanode.DataNode: Got finalize command for block pool BP-1330783287-172.17.0.2-1656328155273
2022-06-27 05:21:30 00331_final_and_prewhere:                                               [ OK ] 0.48 sec.
2022-06-27 05:21:30 00339_parsing_bad_arrays:                                               [ OK ] 1.06 sec.
2022-06-27 05:21:31 00320_between:                                                          [ OK ] 0.32 sec.
2022-06-27 05:21:31 00411_long_accurate_number_comparison_int4:                             [ OK ] 11.45 sec.
```
https://s3.amazonaws.com/clickhouse-test-reports/38344/da52780cb5a76377d3d6eb52c93752a8c946fe14/stateless_tests__thread__actions__[3/3]/runlog.log

**Pull request merged**
