### PR TITLE
Adding support to save clickhouse server logs in TestFlows check

### PR DESCRIPTION
**Pull request by vzakaznikov**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Build/Testing/Packaging Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Adding support to save clickhouse server logs in TestFlows check

Detailed description / Documentation draft:
Adding support to save clickhouse server logs in TestFlows check

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
@mergifyio update

**Comment by qoega** [comment]
```
clickhouse_testflows_tests_volume
Can't start docker daemon, timeout exceeded.
mv: cannot stat '/place/sandbox-data/tasks/8/1/979363318/ClickhouseSource/ClickHouse/tests/testflows/check_status.tsv': No such file or directory
mv: cannot stat '/place/sandbox-data/tasks/8/1/979363318/ClickhouseSource/ClickHouse/tests/testflows/test_results.tsv': No such file or directory
Running testflows container as: 'docker run --net=host  --rm --name clickhouse_testflows_tests --privileged --volume=/place/sandbox-data/tasks/8/1/979363318/clickhouse-odbc-bridge:/clickhouse-odbc-bridge --volume=/place/sandbox-data/tasks/8/1/979363318/clickhouse:/clickhouse         --volume=/place/sandbox-data/tasks/8/1/979363318/ClickhouseSource/ClickHouse/programs/server:/clickhouse-config --volume=/place/sandbox-data/tasks/8/1/979363318/ClickhouseSource/ClickHouse:/ClickHouse --volume=clickhouse_testflows_tests_volume:/var/lib/docker -e TESTFLOWS_OPTS='' yandex/clickhouse-testflows-runner:24504-86f4e3aeafbd27ffc3e38aa6acd8e74178c6ac69 '.
cp: cannot stat 'results.json': No such file or directory
```

**Comment by vzakaznikov** [comment]
> ```
> clickhouse_testflows_tests_volume
> Can't start docker daemon, timeout exceeded.
> mv: cannot stat '/place/sandbox-data/tasks/8/1/979363318/ClickhouseSource/ClickHouse/tests/testflows/check_status.tsv': No such file or directory
> mv: cannot stat '/place/sandbox-data/tasks/8/1/979363318/ClickhouseSource/ClickHouse/tests/testflows/test_results.tsv': No such file or directory
> Running testflows container as: 'docker run --net=host  --rm --name clickhouse_testflows_tests --privileged --volume=/place/sandbox-data/tasks/8/1/979363318/clickhouse-odbc-bridge:/clickhouse-odbc-bridge --volume=/place/sandbox-data/tasks/8/1/979363318/clickhouse:/clickhouse         --volume=/place/sandbox-data/tasks/8/1/979363318/ClickhouseSource/ClickHouse/programs/server:/clickhouse-config --volume=/place/sandbox-data/tasks/8/1/979363318/ClickhouseSource/ClickHouse:/ClickHouse --volume=clickhouse_testflows_tests_volume:/var/lib/docker -e TESTFLOWS_OPTS='' yandex/clickhouse-testflows-runner:24504-86f4e3aeafbd27ffc3e38aa6acd8e74178c6ac69 '.
> cp: cannot stat 'results.json': No such file or directory
> ```

Interesting, but why?

**Comment by vzakaznikov** [comment]
The error comes from https://github.com/ClickHouse/ClickHouse/blob/master/docker/test/testflows/runner/dockerd-entrypoint.sh#L12

**Comment by vzakaznikov** [comment]
PR is ready to be merged. Now TestFlows check report containers clickhouse_logs.tar.gz file with server logs for each test module.

For example, https://clickhouse-test-reports.s3.yandex.net/24504/ba1c118f27ff1ae872183128dc864a66a8c7b067/testflows_check.html.

**Pull request merged**
