### PR TITLE
Fix description for filtering sets in `full_sorting_merge` join

### PR DESCRIPTION
**Pull request by ttanay**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix description for filtering sets in full_sorting_merge join

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

An `EXPLAIN PIPELINE` when using `full_sorting_merge` produced: 
```

┌─explain────────────────────────────────────────────────────────────┐  
│ (Expression)                                                       │  
│ ExpressionTransform _ 8                                            │  
│   (Join)                                                           │  
│   MergeJoinTransform 2 _ 1                                         │  
│     (Sorting)                                                      │  
│     MergingSortedTransform 3 _ 1                                   │  
│       MergeSortingTransform _ 3                                    │  
│         (CreateSetAndFilterOnTheFlyStep)                           │  
│         ReadHeadBalancedProcessor 4 _ 4                            │  
│         Description: Create set and filter Left joined stream      │  
│           FilterBySetOnTheFlyTransform _ 3                         │  
│           Description: Create set and filter Left joined stream    │  
│             CreatingSetsOnTheFlyTransform _ 3                      │  
│             Description: Create set and filter Left joined stream  │  
│               (Expression)                                         │  
│               ExpressionTransform _ 3                              │  
│                 (ReadFromMergeTree)                                │  
│                 MergeTreeThread _ 3 0 _ 1                          │  
│     (Sorting)                                                      │  
│     MergingSortedTransform 3 _ 1                                   │  
│       MergeSortingTransform _ 3                                    │  
│         (CreateSetAndFilterOnTheFlyStep)                           │  
│         ReadHeadBalancedProcessor 4 _ 4                            │  
│         Description: Create set and filter Right joined stream     │  
│           FilterBySetOnTheFlyTransform _ 3                         │  
│           Description: Create set and filter Right joined stream   │  
│             CreatingSetsOnTheFlyTransform _ 3                      │  
│             Description: Create set and filter Right joined stream │  
│               (Expression)                                         │  
│               ExpressionTransform _ 3                              │  
│                 (ReadFromMergeTree)                                │  
│                 MergeTreeThread _ 3 0 _ 1                          │  
└────────────────────────────────────────────────────────────────────┘  
  ```

The description of the `ReadHeadBalancedProcessor` and `FilterBySetOnTheFlyTransform` was the same as the `CreatingSetsOnTheFlyTransform`.

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
A test needed.

**Comment by ttanay** [comment]
Hi @alexey-milovidov 
Modified an existing test that tested the same codepath to also test the description.

**Comment by robot-ch-test-poll3** [comment]
This is an automated comment for commit a163eb79686d06608364372c5f6fdfb1022d44f7 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/51329/a163eb79686d06608364372c5f6fdfb1022d44f7/ci_running.html)
The overall status of the commit is 🔴 failure

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🔴 failure</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Review by nickitat — APPROVED** [review]

**Comment by ttanay** [comment]
Thanks for the approval @nickitat! 
5 checks are marked as failed. However, the checks seemed to have [passed](https://github.com/ClickHouse/ClickHouse/pull/51329/checks) after a few tries. 
Can this be merged?

**Review by alexey-milovidov — APPROVED** [review]

**Comment by tavplubix** [comment]
From cpp-dev channel in Slack: https://clickhousedb.slack.com/archives/CUDSPUJ68/p1691483511750599

> I have a simple PR - [Fix description for filtering sets in ](https://github.com/ClickHouse/ClickHouse/pull/51329)full_sorting_merge[ join](https://github.com/ClickHouse/ClickHouse/pull/51329). It is already approved by 2 maintainers.
However, one Integration test has failed(Integration tests (tsan) [3/6]: [test_restore_replica/test.py::test_restore_replica_sequential](https://s3.amazonaws.com/clickhouse-test-reports/51329/2741300585de0e28b0cfc270379074037606fe00/integration_tests__tsan__[3_6]/integration_run_parallel1_0.log)).
This appears to be an unrelated error. Can someone please confirm that it is a flaky test and is unrelated to my change?

Yes, it's an unrelated flaky test, it's fixed in https://github.com/ClickHouse/ClickHouse/pull/53119. This PR can be merged.

**Comment by ttanay** [comment]
> From cpp-dev channel in Slack: https://clickhousedb.slack.com/archives/CUDSPUJ68/p1691483511750599
> 
> > I have a simple PR - [Fix description for filtering sets in ](https://github.com/ClickHouse/ClickHouse/pull/51329)full_sorting_merge[ join](https://github.com/ClickHouse/ClickHouse/pull/51329). It is already approved by 2 maintainers.
> > However, one Integration test has failed(Integration tests (tsan) [3/6]: [test_restore_replica/test.py::test_restore_replica_sequential](https://s3.amazonaws.com/clickhouse-test-reports/51329/2741300585de0e28b0cfc270379074037606fe00/integration_tests__tsan__%5B3_6%5D/integration_run_parallel1_0.log)).
> > This appears to be an unrelated error. Can someone please confirm that it is a flaky test and is unrelated to my change?
> 
> Yes, it's an unrelated flaky test, it's fixed in #53119. This PR can be merged.

Thank you @tavplubix!

**Pull request merged**
