### PR TITLE
Merge #10000 (sumMap for Tuple argument)

### PR DESCRIPTION
**Pull request by akuzm**
This PR improves #10000

Changelog category (leave one):
- Non-significant (changelog entry is not required)

### CODE REVIEW

**Comment by akuzm** [comment]
@ildus So I continued the thing I mentioned about statically dispatching on argument type, and also cleaned up the code a bit. Surprisingly, the last perf test shows that the performance improved even for the non-tuple version (this is for the penultimate commit from this PR, see https://clickhouse-test-reports.s3.yandex.net/10559/73398a3e171bac30003112c31bc215f716e4720e/performance_comparison/report.html). I think we can review and merge this updated version.

**Comment by ildus** [comment]
That's just awesome. In my benchmarks tuple version works even faster now, and I see performance improvement about 60%.

**Comment by akuzm** [comment]
Good to know, I'll merge it then.

**Comment by ildus** [comment]
Thank you

**Pull request merged**
