### PR TITLE
Print warning during old directories cleanup in MergeTree only if it is old

### PR DESCRIPTION
**Pull request by azat**
Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Fixes: #28760

### CODE REVIEW

**Comment by azat** [comment]
>[CIGithubActions / StressTestDebug (pull_request) Failing after 2m — StressTestDebug](https://github.com/ClickHouse/ClickHouse/runs/4169444589?check_suite_focus=true)

https://github.com/ClickHouse/ClickHouse/pull/30952/files#r746984670

**Comment by azat** [comment]
>Conflicting files
>src/Storages/MergeTree/MergeTreeData.cpp

Conflicts with #31180, rebased.

**Comment by azat** [comment]
>[AST fuzzer (UBSan) — Exception::Exception<std::__1::basic_string_view<char, std::__1::char_traits<char> >, DB::Field::Types::Which const&>(int, std::__1::basic_s](https://clickhouse-test-reports.s3.yandex.net/31259/a49e10c78860a451ff9cc39df6049c88234d507a/fuzzer_tsan/report.html)

- #31324

**Comment by azat** [comment]
[AST fuzzer (debug, actions) — Assertion `!isGlobalContext() || getApplicationType() == ApplicationType::LOCAL' failed]()

- #31333

>Integration tests (asan) — fail: 8, passed: 1744, flaky: 0
>[Integration tests (release) — fail: 8, passed: 1745, flaky: 1](https://clickhouse-test-reports.s3.yandex.net/31259/10fa34c73ac068164d63f8ec63bbd49f738931df/integration_tests_(release).html#fail1)
>Integration tests (thread) — fail: 8, passed: 1741, flaky: 4

- `test_storage_rabbitmq` - #31316 
- `test_storage_kafka/test.py::test_kafka_insert_avro` - #31387
- `test_storage_kerberized_kafka/test.py::test_kafka_json_as_string_no_kdc` - flaky (#14265, cc @ilejn)

**Review by alesapin — APPROVED** [review]

**Comment by ilejn** [comment]
No ideas yet how test_kafka_json_as_string_no_kdc can be run in parallel reliably.

**Pull request merged**
