### PR TITLE
Revert "Revert "SQL syntax for workload and resource management""

### PR DESCRIPTION
**Pull request by serxa**
Reverts ClickHouse/ClickHouse#71251

### CODE REVIEW

**Comment by robot-ch-test-poll1** [comment]
*This is an automated comment for commit 2760f283a1c54351c3103e4a9ce6556b06009149 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/71266/2760f283a1c54351c3103e4a9ce6556b06009149/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Style check</td><td>Runs a set of checks to keep the code style clean. If some of tests failed, see the related log from the report</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/71266/2760f283a1c54351c3103e4a9ce6556b06009149/style_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Comment by serxa** [comment]
> Unit tests (release) — No output log

https://github.com/ClickHouse/ClickHouse/issues/71278

**Comment by serxa** [comment]
> Unit tests (msan) — No output log

I cannot understand what went wrong here, almost no output, seem that unittest binary was not built or something like that happened:
```
"/./unit_tests_dbms": not in executable format: file format not recognized
```
https://s3.amazonaws.com/clickhouse-test-reports/71266/2760f283a1c54351c3103e4a9ce6556b06009149/unit_tests__msan_.html

cc @maxknv

**Comment by serxa** [comment]
Only flaky test failures as in the original [PR](https://github.com/ClickHouse/ClickHouse/pull/69187). Private sync is now okay. I will force merge.

**Pull request merged**
