### PR TITLE
Try fix IfAggCombinator with NullAggCombinator

### PR DESCRIPTION
**Pull request by zhang2014**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Conditional aggregate functions (for example: `avgIf`, `sumIf`, `maxIf`)  should return `NULL` when miss rows and use nullable arguments

Detailed description / Documentation draft:
```sql
-- Value nullable
SELECT anyIf(CAST(number, 'Nullable(UInt8)'), number = 3) AS a, toTypeName(a) FROM numbers(2);
-- Value and condition nullable
SELECT anyIf(number, number = 3) AS a, toTypeName(a) FROM (SELECT CAST(number, 'Nullable(UInt8)') AS number FROM numbers(2));
-- Condition nullable
SELECT anyIf(CAST(number, 'UInt8'), number = 3) AS a, toTypeName(a) FROM (SELECT CAST(number, 'Nullable(UInt8)') AS number FROM numbers(2));
```

### CODE REVIEW

**Comment by zhang2014** [comment]
`Performance — 3 errors, 3 too long, 7 faster, 10 slower, 679 unstable` unrelated this PR.

**Comment by zhang2014** [comment]
Ping...

**Comment by alexey-milovidov** [comment]
Changelog entry does not state what bug was present and what was changed.

I will edit by myself...

**Comment by zhang2014** [comment]
> Changelog entry does not state what bug was present and what was changed.
>
>I will edit by myself...

Done.

**Review by alexey-milovidov — APPROVED** [review]

**Pull request merged**
