### PR TITLE
Remove useless code in ReplicatedMergeTreeRestartingThread

### PR DESCRIPTION
**Pull request by alexey-milovidov**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

The code from 2015 is no longer relevant, because session restore is impossible in our ZooKeeper client.

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
+ agree. Waiting ephemeral node to disappear looks to be more safe.
And let's add the host name to the seed.

**Comment by alexey-milovidov** [comment]
Could you please takeover this branch?

**Comment by tavplubix** [comment]
Stateful tests (address, actions) - `cannot copy extracted data for './usr/bin/clickhouse' to '/usr/bin/clickhouse.dpkg-new': failed to write (No space left on device)` - something's wrong with CI infrastructure, cc: @Felixoid 
Stateful tests (memory, actions) - same
Integration tests (asan, actions) [1/3] - test_polymorphic_parts - `Ephemeral node /clickhouse/tables/test/shard5/sync_table/replicas/0/is_active still exists after 6s`, it's because client's and server's configs are inconsistent, will fix configs and update exception message
Integration tests (asan, actions) [2/3] - `Get "https://registry-1.docker.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)`
Integration tests (release, actions) [1/2] - same
Stress test (memory, actions) - OOM

**Comment by Felixoid** [comment]
Please, rebase it on / merge master into the branch, please. It's the easiest way to have the issue fixed for now.

> Btw, why do we put all compose-files into integration-tests-runner image?

Can't really say, didn't dig into them yet.

**Comment by alexey-milovidov** [comment]
@mergifyio update

**Comment by tavplubix** [comment]
Tests will fail anyway because of the bug in Keeper described above

**Comment by alexey-milovidov** [comment]
@Mergifyio update

**Comment by alesapin** [comment]
Related: https://github.com/ClickHouse/ClickHouse/pull/37824

**Comment by tavplubix** [comment]
And now it makes sense to merge with master and restart tests

**Comment by tavplubix** [comment]
@Mergifyio update

**Pull request merged**
