### PR TITLE
gcc10/cmake build fixes

### PR DESCRIPTION
**Pull request by azat**
Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Cc: @alexey-milovidov 
Cc: @abyss7

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]

**Comment by azat** [comment]
Right now the problem is double-conversion, it is included in arrow with a slash, I've removed this patch.
FWIW arrow since 0.16 has double-conversion included (right now the version is 0.15, latest is 0.17), any objections on just upgrading it to 0.17? (in a separate PR of course)

**Comment by alexey-milovidov** [comment]
No objections, let's upgrade.
And also the author of Arrow has said that it does not need flatbuffers anymore.

**Comment by azat** [comment]
>No objections, let's upgrade.

https://github.com/ClickHouse/ClickHouse/pull/12181

>And also the author of Arrow has said that it does not need flatbuffers anymore.

Actually they requires flatbuffers, but do not requires flatc compiler, since it is shipped with pre-generated headers.

**Comment by azat** [comment]
@alexey-milovidov friendly ping (pinging because build fixes requires rebase of other things on top of them to compile locally, and rebase against upstream for submitting)

**Comment by alexey-milovidov** [comment]
> Performance — 1 faster, 4 slower, 190 unstable 

Because there was performance improvement in master yesterday in #12196

**Pull request merged**
