### PR TITLE
Fix StorageURL forgetting headers on server restart

### PR DESCRIPTION
**Pull request by al13n321**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fixed URL and S3 engines losing the `headers` argument on server restart.

URL table with `headers` argument used to lose that argument on restart (i.e. before the restart it was sending requests with the headers, after restart - without the headers).

That's because arg parsing code was inadvertently removing the argument from the AST:
```
:) create table a (x Int64) engine URL('https://example.com/', CSV, headers('foo' = 'bar'))

CREATE TABLE a
(
    `x` Int64
)
ENGINE = URL('https://example.com/', CSV, headers('foo' = 'bar'))

Query id: 948d59db-9fbd-491e-9aef-29edc9f492af

Ok.

0 rows in set. Elapsed: 0.003 sec. 

:) show create a

SHOW CREATE TABLE a

Query id: d2796f60-cb9a-499e-88b8-4d8607ec8a04

┌─statement────────────────────────────────────────────────────────────────────────┐
│ CREATE TABLE default.a
(
    `x` Int64
)
ENGINE = URL('https://example.com/', 'CSV') │
└──────────────────────────────────────────────────────────────────────────────────┘

1 row in set. Elapsed: 0.001 sec. 

```

### CODE REVIEW

**Comment by robot-clickhouse-ci-2** [comment]
*This is an automated comment for commit 0eb72c6c1f4be25910ca5158593d085194d72a13 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/58933/0eb72c6c1f4be25910ca5158593d085194d72a13/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/58933/0eb72c6c1f4be25910ca5158593d085194d72a13/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Review by antonio2368 — APPROVED** [review]

**Comment by tavplubix** [comment]
> arg parsing code was inadvertently removing the argument from the AST

I guess it was supposed to hide secret headers containing credentials/tokens. Does `SHOW CREATE` show secrets now?

**Comment by al13n321** [comment]
SHOW CREATE shows `headers` now, doesn't show the S3 "secret_access_key":
```
SHOW CREATE TABLE a
                                                                             
Query id: 1241e920-7ac9-4707-b697-12fa7f0fcf06                                                                                                             
                                                                                                                                                           
┌─statement──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ CREATE TABLE default.a          
(
    `n` UInt64,                                                                                                                                                                                                                                                                                                        
    `s` String
)             
ENGINE = S3('http://172.31.8.116:11111/temp/t.parquet', 'minioadmin', '[HIDDEN]', headers('a' = 'b')) │
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
```
---
Maybe it was for hiding secrets, I didn't consider that. If so, it wasn't very good at it: some instances of this copy-pasted code did put headers back into the AST after processing other arguments. E.g. for the s3() table function the headers showed up the server log, like this:
```
<Debug> executeQuery: (from 127.0.0.1:56876) SELECT count() FROM s3('http://172.31.8.116:11111/temp/t.parquet', 'minioadmin', '[HIDDEN]', headers('a' = 'b')) (stage: Complete)
```
---
Should we do the `'[HIDDEN]'` thing for all `headers`?
```
headers('login' = '[HIDDEN]', 'password' = '[HIDDEN]')
```
Or only if the name contains something like "key", "pass", "pw", "secret", "token", "access", etc? Or add a setting for it?

**Comment by tavplubix** [comment]
The question was about headers, not about the S3 "secret_access_key". The URL engine is not only for S3. Examples:
```
CREATE TABLE proxy
(
    `query` String
)
ENGINE = URL('http://localhost:8123/query, headers('X-ClickHouse-User' = 'username', 'X-ClickHouse-Key' = 'MySecretPassword'))

CREATE TABLE url
(
    `json` String
)
ENGINE = URL('http://api.example.com/handler_name, headers('Authorization' = 'Bearer my-secret-token'))
```

> Maybe it was for hiding secrets

I'm pretty sure it was (there's no good reason for removing headers besides that), but we can also ask @kssenii just in case

> Should we do the '[HIDDEN]' thing for all headers?

It's the safest option. We used to remove all headers from AST, so let's start with hiding all headers

**Comment by al13n321** [comment]
https://github.com/ClickHouse/ClickHouse/pull/59787

**Pull request merged**
