### PR TITLE
Test/insert deduplication token materialized views

### PR DESCRIPTION
**Pull request by den-crane**
Test that insert_deduplication_token allows to make idempotent insertion into materialized views

Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by den-crane** [comment]
No idea what is it

```
2022-02-17 20:32:20 Received exception from server (version 22.3.1):
2022-02-17 20:32:20 Code: 49. DB::Exception: Received from localhost:9000. DB::Exception: Cannot add ZooKeeper operation because query is executed. It's a bug.. (LOGICAL_ERROR)
2022-02-17 20:32:20 (query: truncate test_mv_b;)
2022-02-17 20:32:20 , result:
2022-02-17 20:32:20 
2022-02-17 20:32:20 deduplicate_blocks_in_dependent_materialized_views=0, insert_deduplication_token = no, results inconsitent
2022-02-17 20:32:20 18	18	9	18
2022-02-17 20:32:20 deduplicate_blocks_in_dependent_materialized_views=1, insert_deduplication_token = no, results inconsitent
2022-02-17 20:32:20 
2022-02-17 20:32:20 stdout:
2022-02-17 20:32:20 deduplicate_blocks_in_dependent_materialized_views=0, insert_deduplication_token = no, results inconsitent
2022-02-17 20:32:20 18	18	9	18
2022-02-17 20:32:20 deduplicate_blocks_in_dependent_materialized_views=1, insert_deduplication_token = no, results inconsitent
2022-02-17 20:32:20 
2022-02-17 20:32:20 
```


And Flaky 
```
2022-02-17 20:50:18 02124_insert_deduplication_token_materialized_views:                    [ FAIL ] 172.44 sec. - Test runs too long (> 60s). Make it faster.
```
I can move it to integration to test only once?

**Comment by alexey-milovidov** [comment]
This PR is not ready for merge, but it successfully found a bug.
@devcrafter please help.

**Comment by alexey-milovidov** [comment]
@kitaisreal no visible activity in this PR.

**Comment by devcrafter** [comment]
> This PR is not ready for merge, but it successfully found a bug. @devcrafter please help.
I'll try to look into it

**Comment by devcrafter** [comment]
@Mergifyio update

**Comment by den-crane** [comment]
@Mergifyio update

**Comment by devcrafter** [comment]
It's known issue, see #33747

**Comment by den-crane** [comment]
@Mergifyio update

**Comment by den-crane** [comment]
it seems now stress test fails because test is too long (>60s), though the test is very simple and only creates and truncates 3 tables. 

I can mark it as a long test if needed.

**Comment by devcrafter** [comment]
We can mark the test as long or make it faster to avoid such an error:
```
022-05-09 14:23:16 02124_insert_deduplication_token_materialized_views:                    [ FAIL ] 62.96 sec. - Test runs too long (> 60s). Make it faster.
```

Do we really need to create `test_mv_c`? it's the same as `test_mv_a`

**Comment by den-crane** [comment]
>Do we really need to create test_mv_c? it's the same as test_mv_a

That is complicated question. It's my old test from 3 years ago.
Initially mat.view were processed in alphabetical order. So the idea was that _C should be skipped if _B failed and _A succeed. Now it's not relevant. I'll check it.

**Comment by alexey-milovidov** [comment]
Just in case - somewhat duplicate and somewhat unnecessary functional tests are ok for us.

**Comment by devcrafter** [comment]
@Mergifyio update

**Comment by devcrafter** [comment]
@Mergifyio update

**Review by alexey-milovidov — APPROVED** [review]

**Pull request merged**
