### PR TITLE
Run on Android, take two

### PR DESCRIPTION
**Pull request by akuzm**
Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]

**Comment by akuzm** [comment]
```
akuzm@akuzm-nix:~/ch4$ readelf -h ~/Downloads/clickhouse
ELF Header:
  Magic:   7f 45 4c 46 02 01 01 00 00 00 00 00 00 00 00 00 
  Class:                             ELF64
  Data:                              2's complement, little endian
  Version:                           1 (current)
  OS/ABI:                            UNIX - System V
  ABI Version:                       0
  Type:                              EXEC (Executable file)
  Machine:                           AArch64
  Version:                           0x1
  Entry point address:               0x7c86000
  Start of program headers:          64 (bytes into file)
  Start of section headers:          1462537592 (bytes into file)
  Flags:                             0x0
  Size of this header:               64 (bytes)
  Size of program headers:           56 (bytes)
  Number of program headers:         12
  Size of section headers:           64 (bytes)
  Number of section headers:         43
  Section header string table index: 41
```

Wrong type still.

**Comment by akuzm** [comment]
```
/system/bin/linker64 $(readlink -f ./clickhouse)
error: "....clickhouse": executable's TLS segment is underaligned: alignment is 16, needs to be at least 64 for ARM 64 Bionic
Aborted
```

It still won't run on Android, and this one doesn't look like it's easy to fix. Apparently the fix was reverted from clang, and the Android toolchain uses some hack that adds extra section of suitable size to change the TLS alignment. See here: https://reviews.llvm.org/rZORG18bfb2b0f9fa1931af73cc9b05a1424573b8141d

**Comment by alexey-milovidov** [comment]
I see that the discussion is about `lld` linked.
What happens if we will use `gold` or other linked from some dedicated android toolchain?

**Comment by akuzm** [comment]
> I see that the discussion is about `lld` linker.
> What happens if we will use `gold` or other linker from some dedicated android toolchain?

Android toolchain is going to help, but it's taking too long already, maybe next time. I'll merge this one now, because it's a definite improvement (the build failure is CI problem).

**Comment by akuzm** [comment]
> the build failure is CI problem
Oh wait, it's not, it really failed...

**Comment by akuzm** [comment]
> > the build failure is CI problem
> 
> Oh wait, it's not, it really failed...

```
[1/2] /usr/bin/clang-10   -fdiagnostics-color=always  -gdwarf-aranges -pipe -msse4.1 -msse4.2 -mpopcnt  -Wall -Wno-unused-command-line-argument  -fdiagnostics-absolute-paths -Werror -fPIC -o CMakeFiles/cmTC_6b80e.dir/CheckIncludeFile.c.o   -c CheckIncludeFile.c
[2/2] : && /usr/bin/clang-10 -fdiagnostics-color=always  -gdwarf-aranges -pipe -msse4.1 -msse4.2 -mpopcnt  -Wall -Wno-unused-command-line-argument  -fdiagnostics-absolute-paths -Werror -fPIC  -fuse-ld=lld -rdynamic -Wl,--gdb-index -Wl,--no-undefined -Wl,-pie   -rdynamic CMakeFiles/cmTC_6b80e.dir/CheckIncludeFile.c.o  -o cmTC_6b80e   && :
FAILED: cmTC_6b80e 
: && /usr/bin/clang-10 -fdiagnostics-color=always  -gdwarf-aranges -pipe -msse4.1 -msse4.2 -mpopcnt  -Wall -Wno-unused-command-line-argument  -fdiagnostics-absolute-paths -Werror -fPIC  -fuse-ld=lld -rdynamic -Wl,--gdb-index -Wl,--no-undefined -Wl,-pie   -rdynamic CMakeFiles/cmTC_6b80e.dir/CheckIncludeFile.c.o  -o cmTC_6b80e   && :
ld.lld: error: can't create dynamic relocation R_X86_64_32 against symbol: __TMC_END__ in readonly segment; recompile object files with -fPIC or pass '-Wl,-z,notext' to allow text relocations in the output
>>> defined in /usr/bin/../lib/gcc/x86_64-linux-gnu/9/crtend.o
>>> referenced by crtstuff.c
>>>               /usr/bin/../lib/gcc/x86_64-linux-gnu/9/crtbegin.o:(.text+0x1)
```

Not sure what it means. It feels like just a waste of time by this point, closing.

**Pull request closed without merging**
