### PR TITLE
Skip merged partitions for `min_age_to_force_merge_seconds` merges

### LINKED ISSUE #47094: min_age_to_force_merge_seconds remerges already merged data forever
```
create table test( A Int64, D Date) Engine=MergeTree partition by D order by A 
settings min_age_to_force_merge_seconds=600, min_age_to_force_merge_on_partition_only=1;
insert into test select number, toDate('2022-02-01') + number / 10 from numbers(100);

select name, rows, active, modification_time from system.parts where table = 'test' and database = 'default';

┌─name─────────────┬─rows─┬─active─┬───modification_time─┐
│ 20220201_1_1_0   │   10 │      1 │ 2023-03-01 15:57:12 │
│ 20220201_11_11_0 │   10 │      1 │ 2023-03-01 15:57:13 │
│ 20220202_2_2_0   │   10 │      1 │ 2023-03-01 15:57:12 │
│ 20220202_12_12_0 │   10 │      1 │ 2023-03-01 15:57:13 │
│ 20220203_3_3_0   │   10 │      1 │ 2023-03-01 15:57:12 │
│ 20220203_13_13_0 │   10 │      1 │ 2023-03-01 15:57:13 │
│ 20220204_4_4_0   │   10 │      1 │ 2023-03-01 15:57:12 │
│ 20220204_14_14_0 │   10 │      1 │ 2023-03-01 15:57:13 │
│ 20220205_5_5_0   │   10 │      1 │ 2023-03-01 15:57:12 │
│ 20220205_15_15_0 │   10 │      1 │ 2023-03-01 15:57:13 │
│ 20220206_6_6_0   │   10 │      1 │ 2023-03-01 15:57:12 │
│ 20220206_16_16_0 │   10 │      1 │ 2023-03-01 15:57:13 │
│ 20220207_7_7_0   │   10 │      1 │ 2023-03-01 15:57:12 │
│ 20220207_17_17_0 │   10 │      1 │ 2023-03-01 15:57:13 │
│ 20220208_8_8_0   │   10 │      1 │ 2023-03-01 15:57:12 │
│ 20220208_18_18_0 │   10 │      1 │ 2023-03-01 15:57:13 │
│ 20220209_9_9_0   │   10 │      1 │ 2023-03-01 15:57:12 │
│ 20220209_19_19_0 │   10 │      1 │ 2023-03-01 15:57:13 │
│ 20220210_10_10_0 │   10 │      1 │ 2023-03-01 15:57:12 │
│ 20220210_20_20_0 │   10 │      1 │ 2023-03-01 15:57:13 │
└──────────────────┴──────┴────────┴─────────────────────┘


--- merged, expected
select name, partition, rows, active, modification_time, now() -modification_time  from system.parts where table = 'test';
┌─name─────────────┬─partition──┬─rows─┬─active─┬───modification_time─┬─minus(now(), modification_time)─┐
│ 20220201_1_1_0   │ 2022-02-01 │   10 │      0 │ 2023-03-01 15:57:12 │                             702 │
│ 20220201_1_11_1  │ 2022-02-01 │   20 │      1 │ 2023-03-01 16:08:17 │                              37 │
│ 20220201_11_11_0 │ 2022-02-01 │   10 │      0 │ 2023-03-01 15:57:13 │                             701 │
│ 20220202_2_2_0   │ 2022-02-02 │   10 │      0 │ 2023-03-01 15:57:12 │                             702 │
│ 20220202_2_12_1  │ 2022-02-02 │   20 │      1 │ 2023-03-01 16:08:17 │                              37 │
│ 20220202_12_12_0 │ 2022-02-02 │   10 │      0 │ 2023-03-01 15:57:13 │                             701 │
│ 20220203_3_3_0   │ 2022-02-03 │   10 │      0 │ 2023-03-01 15:57:12 │                             702 │
│ 20220203_3_13_1  │ 2022-02-03 │   20 │      1 │ 2023-03-01 16:08:17 │                              37 │
│ 20220203_13_13_0 │ 2022-02-03 │   10 │      0 │ 2023-03-01 15:57:13 │                             701 │
│ 20220204_4_4_0   │ 2022-02-04 │   10 │      0 │ 2023-03-01 15:57:12 │                             702 │
│ 20220204_4_14_1  │ 2022-02-04 │   20 │      1 │ 2023-03-01 16:08:17 │                              37 │
│ 20220204_14_14_0 │ 2022-02-04 │   10 │      0 │ 2023-03-01 15:57:13 │                             701 │
│ 20220205_5_5_0   │ 2022-02-05 │   10 │      0 │ 2023-03-01 15:57:12 │                             702 │
│ 20220205_5_15_1  │ 2022-02-05 │   20 │      1 │ 2023-03-01 16:08:17 │                              37 │
│ 20220205_15_15_0 │ 2022-02-05 │   10 │      0 │ 2023-03-01 15:57:13 │                             701 │
│ 20220206_6_6_0   │ 2022-02-06 │   10 │      0 │ 2023-03-01 15:57:12 │                             702 │
│ 20220206_6_16_1  │ 2022-02-06 │   20 │      1 │ 2023-03-01 16:08:17 │                              37 │
│ 20220206_16_16_0 │ 2022-02-06 │   10 │      0 │ 2023-03-01 15:57:13 │                             701 │
│ 20220207_7_7_0   │ 2022-02-07 │   10 │      0 │ 2023-03-01 15:57:12 │                             702 │
│ 20220207_7_17_1  │ 2022-02-07 │   20 │      1 │ 2023-03-01 16:08:17 │                              37 │
│ 20220207_17_17_0 │ 2022-02-07 │   10 │      0 │ 2023-03-01 15:57:13 │                             701 │
│ 20220208_8_8_0   │ 2022-02-08 │   10 │      0 │ 2023-03-01 15:57:12 │                             702 │
│ 20220208_8_18_1  │ 2022-02-08 │   20 │      1 │ 2023-03-01 16:08:17 │                              37 │
│ 20220208_18_18_0 │ 2022-02-08 │   10 │      0 │ 2023-03-01 15:57:13 │                             701 │
│ 20220209_9_9_0   │ 2022-02-09 │   10 │      0 │ 2023-03-01 15:57:12 │                             702 │
│ 20220209_9_19_1  │ 2022-02-09 │   20 │      1 │ 2023-03-01 16:08:17 │                              37 │
│ 20220209_19_19_0 │ 2022-02-09 │   10 │      0 │ 2023-03-01 15:57:13 │                             701 │
│ 20220210_10_10_0 │ 2022-02-10 │   10 │      0 │ 2023-03-01 15:57:12 │                             702 │
│ 20220210_10_20_1 │ 2022-02-10 │   20 │      1 │ 2023-03-01 16:08:17 │                              37 │
│ 20220210_20_20_0 │ 2022-02-10 │   10 │      0 │ 2023-03-01 15:57:13 │                             701 │
└──────────────────┴────────────┴──────┴────────┴─────────────────────┴─────────────────────────────────┘

-- merged again, what for?
select name, partition, rows, active, modification_time, now() -modification_time age, round(age / 60)  from system.parts where table = 'test';
┌─name─────────────┬─partition──┬─rows─┬─active─┬───modification_time─┬─age─┬─round(divide(minus(now(), modification_time), 60))─┐
│ 20220201_1_11_1  │ 2022-02-01 │   20 │      0 │ 2023-03-01 16:08:17 │ 608 │                                                 10 │
│ 20220201_1_11_2  │ 2022-02-01 │   20 │      1 │ 2023-03-01 16:18:18 │   7 │                                                  0 │
│ 20220202_2_12_1  │ 2022-02-02 │   20 │      0 │ 2023-03-01 16:08:17 │ 608 │                                                 10 │
│ 20220202_2_12_2  │ 2022-02-02 │   20 │      1 │ 2023-03-01 16:18:18 │   7 │                                                  0 │
│ 20220203_3_13_1  │ 2022-02-03 │   20 │      0 │ 2023-03-01 16:08:17 │ 608 │                                                 10 │
│ 20220203_3_13_2  │ 2022-02-03 │   20 │      1 │ 2023-03-01 16:18:18 │   7 │                                                  0 │
│ 20220204_4_14_1  │ 2022-02-04 │   20 │      0 │ 2023-03-01 16:08:17 │ 608 │                                                 10 │
│ 20220204_4_14_2  │ 2022-02-04 │   20 │      1 │ 2023-03-01 16:18:18 │   7 │                                                  0 │
│ 20220205_5_15_1  │ 2022-02-05 │   20 │      0 │ 2023-03-01 16:08:17 │ 608 │                                                 10 │
│ 20220205_5_15_2  │ 2022-02-05 │   20 │      1 │ 2023-03-01 16:18:18 │   7 │                                                  0 │
│ 20220206_6_16_1  │ 2022-02-06 │   20 │      0 │ 2023-03-01 16:08:17 │ 608 │                                                 10 │
│ 20220206_6_16_2  │ 2022-02-06 │   20 │      1 │ 2023-03-01 16:18:18 │   7 │                                                  0 │
│ 20220207_7_17_1  │ 2022-02-07 │   20 │      0 │ 2023-03-01 16:08:17 │ 608 │                                                 10 │
│ 20220207_7_17_2  │ 2022-02-07 │   20 │      1 │ 2023-03-01 16:18:18 │   7 │                                                  0 │
│ 20220208_8_18_1  │ 2022-02-08 │   20 │      0 │ 2023-03-01 16:08:17 │ 608 │                                                 10 │
│ 20220208_8_18_2  │ 2022-02-08 │   20 │      1 │ 2023-03-01 16:18:18 │   7 │                                                  0 │
│ 20220209_9_19_1  │ 2022-02-09 │   20 │      0 │ 2023-03-01 16:08:17 │ 608 │                                                 10 │
│ 20220209_9_19_2  │ 2022-02-09 │   20 │      1 │ 2023-03-01 16:18:18 │   7 │                                                  0 │
│ 20220210_10_20_1 │ 2022-02-10 │   20 │      0 │ 2023-03-01 16:08:17 │ 608 │                                                 10 │
│ 20220210_10_20_2 │ 2022-02-10 │   20 │      1 │ 2023-03-01 16:18:18 │   7 │                                                  0 │
└──────────────────┴────────────┴──────┴────────┴─────────────────────┴─────┴────────────────────────────────────────────────────┘
```

### PR DESCRIPTION
**Pull request by antonio2368**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in official stable or prestable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Skip merged partitions for merges triggered by `min_age_to_force_merge_seconds` with `min_age_to_force_merge_on_partition_only` set to `true`.

Fix https://github.com/ClickHouse/ClickHouse/issues/47094

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by den-crane** [comment]
I don't see any reason to merge already merged partition even if `min_age_to_force_merge_on_partition_only=0`

**Comment by antonio2368** [comment]
@den-crane that already works because we don't pick ranges with a single part with `SimpleMergeSelector`

**Comment by den-crane** [comment]
> @den-crane that already works because we don't pick ranges with a single part with `SimpleMergeSelector`

I see. I was confused by false user's report.

**Review by SmitaRKulkarni — APPROVED** [review]
LGTM

**Pull request merged**
