### PR TITLE
String optimized IN operator

### PR DESCRIPTION
**Pull request by amosbird**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Performance Improvement

Changelog entry (up to few sentences, required except for Non-significant/Documentation categories):

Enable SSO for IN operator. Improvements varies from 4% -  **257%** . Should be merged after https://github.com/ClickHouse/ClickHouse/pull/7662

<details>

```
before:

[
{
    "hostname": "201.nobida.cn",
    "main_metric": "rows_per_second",
    "num_cores": 20,
    "num_threads": 40,
    "path": "/data/ClickHouse/src/dbms/tests/performance/string_set.xml",
    "ram": 134765342720,
    "runs": [
        {
            "bytes_per_second": 368044422.809631,
            "memory_usage": 0,
            "min_time": 0.504000,
            "quantiles": {
                "0.1": 0.528337,
                "0.2": 0.531904,
                "0.3": 0.532189,
                "0.4": 0.532633,
                "0.5": 0.533234,
                "0.6": 0.533937,
                "0.7": 0.535373,
                "0.8": 0.537885,
                "0.9": 0.543382,
                "0.95": 0.559287,
                "0.99": 0.572012,
                "0.999": 0.574875,
                "0.9999": 0.575161
            },
            "queries_per_second": 1.868023,
            "query": "SELECT 1 FROM hits_10m_words WHERE word IN (SELECT word FROM hits_10m_words) FORMAT Null",
            "query_index": 0,
            "rows_per_second": 17866550.375103,
            "total_time": 5.353253
        },
        {
            "bytes_per_second": 213019833.991382,
            "memory_usage": 0,
            "min_time": 0.168000,
            "quantiles": {
                "0.1": 0.174986,
                "0.2": 0.175882,
                "0.3": 0.176110,
                "0.4": 0.176196,
                "0.5": 0.176206,
                "0.6": 0.176356,
                "0.7": 0.176592,
                "0.8": 0.177023,
                "0.9": 0.178620,
                "0.95": 0.179009,
                "0.99": 0.179320,
                "0.999": 0.179391,
                "0.9999": 0.179398
            },
            "queries_per_second": 5.683125,
            "query": "SELECT 1 FROM strings WHERE short IN (SELECT short FROM strings) FORMAT Null",
            "query_index": 1,
            "rows_per_second": 11366249.309358,
            "total_time": 1.759595
        },
        {
            "bytes_per_second": 820697966.529802,
            "memory_usage": 0,
            "min_time": 0.296000,
            "quantiles": {
                "0.1": 0.296521,
                "0.2": 0.297664,
                "0.3": 0.298108,
                "0.4": 0.299864,
                "0.5": 0.301401,
                "0.6": 0.302371,
                "0.7": 0.308462,
                "0.8": 0.321663,
                "0.9": 0.325565,
                "0.95": 0.326139,
                "0.99": 0.326597,
                "0.999": 0.326701,
                "0.9999": 0.326711
            },
            "queries_per_second": 3.259396,
            "query": "SELECT 1 FROM strings WHERE long IN (SELECT long FROM strings) FORMAT Null",
            "query_index": 2,
            "rows_per_second": 6518792.776396,
            "total_time": 3.068053
        },
        {
            "bytes_per_second": 659477358.614271,
            "memory_usage": 0,
            "min_time": 0.211000,
            "quantiles": {
                "0.1": 0.217720,
                "0.2": 0.218711,
                "0.3": 0.219188,
                "0.4": 0.219451,
                "0.5": 0.219546,
                "0.6": 0.219585,
                "0.7": 0.219762,
                "0.8": 0.220638,
                "0.9": 0.222671,
                "0.95": 0.223015,
                "0.99": 0.223290,
                "0.999": 0.223352,
                "0.9999": 0.223358
            },
            "queries_per_second": 4.559482,
            "query": "SELECT 1 FROM strings WHERE short IN (SELECT long FROM strings) FORMAT Null",
            "query_index": 3,
            "rows_per_second": 9118963.382797,
            "total_time": 2.193232
        },
        {
            "bytes_per_second": 795195777.826913,
            "memory_usage": 0,
            "min_time": 0.180000,
            "quantiles": {
                "0.1": 0.180861,
                "0.2": 0.180992,
                "0.3": 0.181240,
                "0.4": 0.181383,
                "0.5": 0.181457,
                "0.6": 0.181559,
                "0.7": 0.181659,
                "0.8": 0.182019,
                "0.9": 0.183562,
                "0.95": 0.184427,
                "0.99": 0.185119,
                "0.999": 0.185275,
                "0.9999": 0.185290
            },
            "queries_per_second": 5.497809,
            "query": "SELECT 1 FROM strings WHERE long IN (SELECT short FROM strings) FORMAT Null",
            "query_index": 4,
            "rows_per_second": 10995618.098846,
            "total_time": 1.818906
        },
        {
            "bytes_per_second": 490171004.709044,
            "memory_usage": 0,
            "min_time": 0.227000,
            "quantiles": {
                "0.1": 0.227895,
                "0.2": 0.228227,
                "0.3": 0.228404,
                "0.4": 0.228643,
                "0.5": 0.229939,
                "0.6": 0.232367,
                "0.7": 0.236146,
                "0.8": 0.244028,
                "0.9": 0.260872,
                "0.95": 0.274031,
                "0.99": 0.284559,
                "0.999": 0.286927,
                "0.9999": 0.287164
            },
            "queries_per_second": 4.180450,
            "query": "SELECT 1 FROM hits_10m_words WHERE word IN (SELECT short FROM strings) FORMAT Null",
            "query_index": 5,
            "rows_per_second": 24172229.506384,
            "total_time": 2.392087
        },
        {
            "bytes_per_second": 704963554.841534,
            "memory_usage": 0,
            "min_time": 0.296000,
            "quantiles": {
                "0.1": 0.298237,
                "0.2": 0.302659,
                "0.3": 0.305543,
                "0.4": 0.313259,
                "0.5": 0.320942,
                "0.6": 0.326171,
                "0.7": 0.331032,
                "0.8": 0.334841,
                "0.9": 0.335255,
                "0.95": 0.335929,
                "0.99": 0.336468,
                "0.999": 0.336589,
                "0.9999": 0.336601
            },
            "queries_per_second": 3.141423,
            "query": "SELECT 1 FROM hits_10m_words WHERE word IN (SELECT long FROM strings) FORMAT Null",
            "query_index": 6,
            "rows_per_second": 18164362.378296,
            "total_time": 3.183271
        }
    ],
    "server_version": "19.17.1",
    "test_name": "string_set",
    "time": "2019-11-15 13:44:31"
}
]

after:

[
{
    "hostname": "201.nobida.cn",
    "main_metric": "rows_per_second",
    "num_cores": 20,
    "num_threads": 40,
    "path": "/data/ClickHouse/src/dbms/tests/performance/string_set.xml",
    "ram": 134765342720,
    "runs": [
        {
            "bytes_per_second": 750032587.982162,
            "memory_usage": 0,
            "min_time": 0.234000,
            "quantiles": {
                "0.1": 0.235263,
                "0.2": 0.236501,
                "0.3": 0.260768,
                "0.4": 0.272356,
                "0.5": 0.273470,
                "0.6": 0.273806,
                "0.7": 0.274289,
                "0.8": 0.275151,
                "0.9": 0.275650,
                "0.95": 0.276382,
                "0.99": 0.276968,
                "0.999": 0.277100,
                "0.9999": 0.277114
            },
            "queries_per_second": 3.806818,
            "query": "SELECT 1 FROM hits_10m_words WHERE word IN (SELECT word FROM hits_10m_words) FORMAT Null",
            "query_index": 0,
            "rows_per_second": 36409993.429199,
            "total_time": 2.626866
        },
        {
            "bytes_per_second": 421376603.673944,
            "memory_usage": 0,
            "min_time": 0.086000,
            "quantiles": {
                "0.1": 0.087440,
                "0.2": 0.087720,
                "0.3": 0.087931,
                "0.4": 0.088338,
                "0.5": 0.088798,
                "0.6": 0.089121,
                "0.7": 0.089310,
                "0.8": 0.089853,
                "0.9": 0.091500,
                "0.95": 0.091639,
                "0.99": 0.091751,
                "0.999": 0.091776,
                "0.9999": 0.091778
            },
            "queries_per_second": 11.242588,
            "query": "SELECT 1 FROM strings WHERE short IN (SELECT short FROM strings) FORMAT Null",
            "query_index": 1,
            "rows_per_second": 22485175.911391,
            "total_time": 0.889475
        },
        {
            "bytes_per_second": 856529664.863820,
            "memory_usage": 0,
            "min_time": 0.285000,
            "quantiles": {
                "0.1": 0.286660,
                "0.2": 0.287500,
                "0.3": 0.289618,
                "0.4": 0.290466,
                "0.5": 0.290766,
                "0.6": 0.293492,
                "0.7": 0.298719,
                "0.8": 0.302457,
                "0.9": 0.302960,
                "0.95": 0.303917,
                "0.99": 0.304682,
                "0.999": 0.304854,
                "0.9999": 0.304871
            },
            "queries_per_second": 3.402104,
            "query": "SELECT 1 FROM strings WHERE long IN (SELECT long FROM strings) FORMAT Null",
            "query_index": 2,
            "rows_per_second": 6804207.668950,
            "total_time": 2.939358
        },
        {
            "bytes_per_second": 746751865.914899,
            "memory_usage": 0,
            "min_time": 0.161000,
            "quantiles": {
                "0.1": 0.176888,
                "0.2": 0.180039,
                "0.3": 0.185353,
                "0.4": 0.188428,
                "0.5": 0.197290,
                "0.6": 0.206214,
                "0.7": 0.207605,
                "0.8": 0.208463,
                "0.9": 0.208792,
                "0.95": 0.209183,
                "0.99": 0.209496,
                "0.999": 0.209566,
                "0.9999": 0.209573
            },
            "queries_per_second": 5.163454,
            "query": "SELECT 1 FROM strings WHERE short IN (SELECT long FROM strings) FORMAT Null",
            "query_index": 3,
            "rows_per_second": 10326907.888733,
            "total_time": 1.936688
        },
        {
            "bytes_per_second": 1742085478.735176,
            "memory_usage": 0,
            "min_time": 0.071000,
            "quantiles": {
                "0.1": 0.071377,
                "0.2": 0.075928,
                "0.3": 0.077123,
                "0.4": 0.080181,
                "0.5": 0.084667,
                "0.6": 0.087885,
                "0.7": 0.089688,
                "0.8": 0.091361,
                "0.9": 0.091777,
                "0.95": 0.091907,
                "0.99": 0.092010,
                "0.999": 0.092034,
                "0.9999": 0.092036
            },
            "queries_per_second": 12.045739,
            "query": "SELECT 1 FROM strings WHERE long IN (SELECT short FROM strings) FORMAT Null",
            "query_index": 4,
            "rows_per_second": 24091478.166118,
            "total_time": 0.830169
        },
        {
            "bytes_per_second": 615174037.596330,
            "memory_usage": 0,
            "min_time": 0.173000,
            "quantiles": {
                "0.1": 0.176009,
                "0.2": 0.177864,
                "0.3": 0.178359,
                "0.4": 0.184781,
                "0.5": 0.191961,
                "0.6": 0.195286,
                "0.7": 0.196534,
                "0.8": 0.200416,
                "0.9": 0.210032,
                "0.95": 0.210666,
                "0.99": 0.211174,
                "0.999": 0.211288,
                "0.9999": 0.211300
            },
            "queries_per_second": 5.246600,
            "query": "SELECT 1 FROM hits_10m_words WHERE word IN (SELECT short FROM strings) FORMAT Null",
            "query_index": 5,
            "rows_per_second": 30336933.722313,
            "total_time": 1.905996
        },
        {
            "bytes_per_second": 890828866.077839,
            "memory_usage": 0,
            "min_time": 0.221000,
            "quantiles": {
                "0.1": 0.233963,
                "0.2": 0.237790,
                "0.3": 0.239276,
                "0.4": 0.243009,
                "0.5": 0.252586,
                "0.6": 0.262455,
                "0.7": 0.266897,
                "0.8": 0.269071,
                "0.9": 0.271810,
                "0.95": 0.271943,
                "0.99": 0.272049,
                "0.999": 0.272073,
                "0.9999": 0.272075
            },
            "queries_per_second": 3.969930,
            "query": "SELECT 1 FROM hits_10m_words WHERE word IN (SELECT long FROM strings) FORMAT Null",
            "query_index": 6,
            "rows_per_second": 22954961.635582,
            "total_time": 2.518936
        }
    ],
    "server_version": "19.18.1",
    "test_name": "string_set",
    "time": "2019-11-15 13:45:11"
}
]

```
</details>

### CODE REVIEW

**Comment by akuzm** [comment]
I only briefly looked at the PR, so a superficial question: when do we need iteration over hash table in the Set?

The reason I'm asking is that I hope we can avoid the `forEachCell` changes, because they are somewhat complicated.

**Comment by amosbird** [comment]
Not for now, but maybe used for https://github.com/ClickHouse/ClickHouse/pull/7755  .  Also `forEachCell` is used in Join.

The reason that this pr contains such changes is because it's based on https://github.com/ClickHouse/ClickHouse/pull/7662 (and there are two separate commits here)  .

**Comment by abyss7** [comment]
@amosbird what's with this PR? Description says to merge after #7662 which is closed.

**Comment by amosbird** [comment]
It's based on the foreach iterator of hash tables. It might be implemented differently though. I'll take another look some time later...

**Comment by abyss7** [comment]
Do you have any news?

**Comment by amosbird** [comment]
@abyss7 I just took another look and it seems this PR doesn't give much ROI. I'll close it and find another way.

**Pull request closed without merging**
