### PR TITLE
Report high-level function and data types test coverage

### LINKED ISSUE #40593: Check what components are not covered by tests
After functional tests are finished, run the following query:

```
SELECT name FROM system.functions WHERE NOT is_aggregate AND origin = 'System' AND alias_to = ''
AND name NOT IN (SELECT arrayJoin(used_functions) FROM system.query_log)
ORDER BY name
```

This will give you a list of functions not covered by tests.

Check it for every component that is tracked in system.query_log:

```
used_aggregate_functions
used_aggregate_function_combinators
used_database_engines
used_data_type_families
used_dictionaries
used_formats
used_functions
used_storages
used_table_functions
```

### PR DESCRIPTION
**Pull request by alexey-milovidov**
### Changelog category (leave one):
- Build/Testing/Packaging Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Calculate and report SQL function coverage in tests. This does not close #40593.

### CODE REVIEW

**Comment by azat** [comment]
>This does not close https://github.com/ClickHouse/ClickHouse/issues/40593.

Note, that github does not handle "not close", and will close it instead :)

**Comment by alexey-milovidov** [comment]
The following functions were not covered by tests:

```
2022-08-26 05:34:49 accurate_Cast
2022-08-26 05:34:49 accurate_CastOrNull
2022-08-26 05:34:49 addressToLine
2022-08-26 05:34:49 addressToLineWithInlines
2022-08-26 05:34:49 lemmatize
2022-08-26 05:34:49 modelEvaluate
2022-08-26 05:34:49 regionHierarchy
2022-08-26 05:34:49 regionIn
2022-08-26 05:34:49 regionToArea
2022-08-26 05:34:49 regionToCity
2022-08-26 05:34:49 regionToContinent
2022-08-26 05:34:49 regionToCountry
2022-08-26 05:34:49 regionToDistrict
2022-08-26 05:34:49 regionToName
2022-08-26 05:34:49 regionToPopulation
2022-08-26 05:34:49 regionToTopContinent
2022-08-26 05:34:49 synonyms
2022-08-26 05:34:49 toDecimal128OrDefault
2022-08-26 05:34:49 toDecimal256OrDefault
2022-08-26 05:34:49 toDecimal32OrDefault
2022-08-26 05:34:49 toDecimal64OrDefault
```

**Comment by alexey-milovidov** [comment]
Now we need to add suppressions, make non-zero exit code, and the tests for some of these functions.

**Comment by alexey-milovidov** [comment]
#40682

**Comment by alexey-milovidov** [comment]
#40683

**Comment by alexey-milovidov** [comment]
#40684

**Comment by alexey-milovidov** [comment]
#40685

**Comment by alexey-milovidov** [comment]
#40686

**Comment by alexey-milovidov** [comment]
addressToLine, addressToLineWithInlines - these functions don't work: #36797

**Comment by alexey-milovidov** [comment]
https://github.com/ClickHouse/ClickHouse/issues/40706

**Pull request merged**
