### PR TITLE
ISSUES-8370 add canonical type name for alias type

### PR DESCRIPTION
**Pull request by zhang2014**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Improvement

Changelog entry (up to few sentences, required except for Non-significant/Documentation categories):
TODO

Detailed description (optional):
#8370
TODO

### CODE REVIEW

**Comment by zhang2014** [comment]
Currently should have broken all alias type usage, because the client might not know the alias of types.

 We should probably add a setting to keep it compatible? for example: `use_canonical_type_name_to_format` ?

**Comment by alexey-milovidov** [comment]
> because the client might not know the alias of types

It's about all the clients that use Native format?

> We should probably add a setting to keep it compatible?

Maybe we can do it in a different way:
- do not use custom names inside DataType objects; use canonical names as before;
- save user-specified names somewhere in the table and return them in DESC TABLE and SHOW CREATE TABLE;

**Comment by zhang2014** [comment]
> It's about all the clients that use Native format ?

I checked it again. It will affect XML, TabSeparated, Native, JSON output formats and ODBC Driver.

> Maybe we can do it in a different way:
> 
> - do not use custom names inside DataType objects; use canonical names as before;
> - save user-specified names somewhere in the table and return them in DESC TABLE and SHOW CREATE TABLE;

This can lead to some incorrect error messages. can we accept that ? 

``` SQL
CREATE TABLE test(x BIGINT) ENGINE = Memory;

SELECT MD5(x) FROM test; -- Illegal type UInt64 of argument of function MD5

SELECT toTypename(CAST(x, 'TINYINT')) FROM test; -- currently return UInt8, But might expect TINYINT?

```

**Comment by alexey-milovidov** [comment]
> Ok, we can store them in ColumnDescription, but we may need to accept the following case, can we accept that?

Yes, we're Ok to save type aliases only in `SHOW CREATE TABLE`, `DESC TABLE` and `system.columns`, but we should return our canonical names in all formats (Native, JSON, etc...)

**Comment by alexey-milovidov** [comment]
No setting needed.

**Comment by alexey-milovidov** [comment]
Let's continue :)

**Comment by zhang2014** [comment]
> Yes, we're Ok to save type aliases only in SHOW CREATE TABLE, DESC TABLE and system.columns, but we should return our canonical names in all formats (Native, JSON, etc...)

Ok, I try to finish it

**Comment by alexey-milovidov** [comment]
Need to rebase on master and open another PR when it will be more ready.

**Pull request closed without merging**
