### PR TITLE
Detect io_uring in tests

### PR DESCRIPTION
**Pull request by azat**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Sometimes CI may not have it - https://s3.amazonaws.com/clickhouse-test-reports/60153/ef4a9e8ff99848a5c9e9f7336af24eb5ec259c18/stateless_tests__tsan__[2_5].html

### CODE REVIEW

**Comment by robot-clickhouse-ci-1** [comment]
*This is an automated comment for commit 7cac8037b699562e88c5959b8f589d4b7021c6a7 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/60373/7cac8037b699562e88c5959b8f589d4b7021c6a7/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/60373/7cac8037b699562e88c5959b8f589d4b7021c6a7/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
@azat We updated to the new AMI in AWS, which does not enable uring by default.
We should either find a way to enable it (probably with some sysctl), or remove uring from the codebase as we lose the way to test it, and every untested feature is the same as nonexistent.

**Comment by Felixoid** [comment]
The AMI is deployed in https://github.com/ClickHouse/ClickHouse/pull/60316/files

I've spun a test on some fresh host, and here's the result:

```
$ curl -O https://s3.amazonaws.com/clickhouse-builds/24.2/32607cc7967712890d6dd53cf82a409876bcf459/package_tsan/clickhouse -s
$ chmod +x clickhouse && ./clickhouse local -q "select * from file('/dev/null', 'LineAsString')" --storage_file_read_method io_uring
Decompressing the binary.....................
$ echo $?
0
```

I am not sure if the AMI is a reason here.

**Comment by Felixoid** [comment]
For example, here's the failing test https://s3.amazonaws.com/clickhouse-test-reports/0/f70d4d9372e02790c7c585a41862b70efc0b6fd4/stateless_tests__tsan__[1_5].html

I open the job and see the machine type [m6i.4xlarge](https://github.com/ClickHouse/ClickHouse/actions/runs/8019976450/job/21918253105#step:2:7). And the host with the same type works.

I run then the same in the same [container](https://github.com/ClickHouse/ClickHouse/actions/runs/8019976450/job/21918253105#step:8:104)

```
$ docker run -v ~/clickhouse:/clickhouse clickhouse/stateless-test:238cad023c02 /clickhouse local -q "select * from file('/dev/null', 'LineAsString')" --storage_file_read_method io_uring && echo OK || echo FAILED
OK
```

It's very strange, and I am open to ideas

**Comment by nickitat** [comment]
what are the chances that we're getting a kernel < 5.6?)

**Comment by Felixoid** [comment]
> what are the chances that we're getting a kernel < 5.6?) I found this code in lib tests: [axboe/liburing@3508db9](https://github.com/axboe/liburing/commit/3508db90d8cbd70e998bdeb5e0ddad1a9f577004)

I'd say 0.00000...1%

```
$ uname -a
Linux ip-172-31-3-162 6.5.0-1014-aws #14~22.04.1-Ubuntu SMP Thu Feb 15 19:20:45 UTC 2024 aarch64 aarch64 aarch64 GNU/Linux
$ uname -a
Linux ip-172-31-10-141 6.5.0-1014-aws #14~22.04.1-Ubuntu SMP Thu Feb 15 15:27:06 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by nickitat** [comment]
I'm not 100% sure since not all checks are finished, but seems to work: https://github.com/ClickHouse/ClickHouse/pull/60383#issuecomment-1963071684

**Comment by azat** [comment]
```
$ curl -O https://s3.amazonaws.com/clickhouse-builds/24.2/32607cc7967712890d6dd53cf82a409876bcf459/package_tsan/clickhouse -s
$ chmod +x clickhouse && ./clickhouse local -q "select * from file('/dev/null', 'LineAsString')" --storage_file_read_method io_uring
```

@Felixoid this does not work without this PR

**Comment by Felixoid** [comment]
What I've tried to show is that I can't reproduce the issue, unfortunately

**Comment by azat** [comment]
Indeed, because you were trying binary without this PR, while this PR two things:
- `storage_file_read_method=io_uring` for `clickhouse-local`
- detection of io_uring via this in `clickhouse-test`

**Comment by Felixoid** [comment]
And that's what works:

```
ubuntu@ip-172-31-70-76:~$ curl -O https://s3.amazonaws.com/clickhouse-builds/24.2/648e6ec5a63f777c5c44405d45574aaebf77142b/package_release/clickhouse -s
ubuntu@ip-172-31-70-76:~$ chmod +x clickhouse && ./clickhouse local -q "select * from file('/dev/null', 'LineAsString')" --storage_file_read_method io_uring
Decompressing the binary.................
ubuntu@ip-172-31-70-76:~$ echo $?
0
ubuntu@ip-172-31-70-76:~$ docker run --security-opt seccomp=unconfined -v ~/clickhouse:/clickhouse clickhouse/stateless-test:238cad023c02 /clickhouse local -q "select * from file('/dev/null', 'LineAsString')" --storage_file_read_method io_uring && echo OK || echo FAILED
OK
ubuntu@ip-172-31-70-76:~$ docker run -v ~/clickhouse:/clickhouse clickhouse/stateless-test:238cad023c02 /clickhouse local -q "select * from file('/dev/null', 'LineAsString')" --storage_file_read_method io_uring && echo OK || echo FAILED
Code: 1. DB::Exception: io_uring is not supported by this system: While executing File. (UNSUPPORTED_METHOD)
FAILED
```

**Comment by Felixoid** [comment]
And here's the PR implementing it https://github.com/moby/moby/pull/46762

**Comment by Algunenano** [comment]
I'm going to backport this change to other public releases, as otherwise the CI there is completely broken

**Pull request merged**
