### PR TITLE
Fix if, multiIf's nullable bug.

### PR DESCRIPTION
**Pull request by janplus**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

For changelog. Remove if this is non-significant change.

Category (leave one):
- Improvement
- Backward Incompatible Change

Short description (up to few sentences):
The `if`, `multiIf` functions should not rely on the condition's Nullable, but should only rely on the branches.

You may check the MySQL & Postgresql's results here:
http://sqlfiddle.com/#!9/25e4d/4
http://sqlfiddle.com/#!17/486b3/3

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
That's great!

**Comment by alexey-milovidov** [comment]
Although it doesn't seem logical for me.

**Comment by janplus** [comment]
Hmm, the data analyst in my company reported this bug to me. I also double checked this logic, and found that MySQL, Postgresql, IBM DB2 all leverage the same logic, so I decide to behave the same way.

**Comment by alexey-milovidov** [comment]
> Hmm, the data analyst in my company reported this bug to me. I also double checked this logic, and found that MySQL, Postgresql, IBM DB2 all leverage the same logic, so I decide to behave the same way.

This is the right decision, thank you!

**Pull request merged**
