### PR TITLE
Bug fix explain ast with parameterized view

### PR DESCRIPTION
**Pull request by SmitaRKulkarni**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Updated to check inside explain ast for create parameterized view statement

### CODE REVIEW

**Comment by robot-ch-test-poll4** [comment]
*This is an automated comment for commit d6c63e07ce97932bdfcf7baa5ab76bd9c1fee85b with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/56004/d6c63e07ce97932bdfcf7baa5ab76bd9c1fee85b/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td><a href="https://github.com/ClickHouse/ClickHouse/actions/runs/6637698673">✅ success</a></td></tr>
<tbody>
</table>
</details>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/56004/d6c63e07ce97932bdfcf7baa5ab76bd9c1fee85b/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Review by novikd — APPROVED** [review]

**Comment by SmitaRKulkarni** [comment]
Unrelated failures : 
[integration_tests__release__[2_4].html] - test_storage_kafka/test.py
Integration tests (release) [4/4] - test_default_compression_codec
test_backward_compatibility  - https://github.com/ClickHouse/ClickHouse/issues/56108
Stateless tests (release, analyzer) - 00992_system_parts_race_condition_zookeeper_long
https://github.com/ClickHouse/ClickHouse/pull/55645#issuecomment-1771523275

**Comment by Felixoid** [comment]
What has failed related to the docker issues?

**Comment by novikd** [comment]
@Felixoid what do you mean?

**Comment by Felixoid** [comment]
> test_backward_compatibility - #56108

I mean this

**Pull request merged**
