### PR TITLE
Excludes views from syncing in MaterializeMySQL

### PR DESCRIPTION
**Pull request by cfroystad**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
MaterializeMySQL (experimental feature). Make Clickhouse to be able to replicate MySQL databases containing views without failing. This is accomplished by ignoring the views.
...

Detailed description / Documentation draft:

Since a MySQL view is simply a different representation of the underlying tables, won't be replicated to ClickHouse. 
...

### CODE REVIEW

**Comment by cfroystad** [comment]
See [issue#20205](https://github.com/ClickHouse/ClickHouse/issues/20205)

**Comment by cfroystad** [comment]
As far as I can see, non of the test failures are related to the changes in this PR. Please correct me if I'm wrong 🙂

**Comment by abyss7** [comment]
It would be great if you add your own integration test for this improvement.

**Comment by cfroystad** [comment]
@abyss7 Good point! I should of course have done that from the start. I've added an integration test for the initial replication. Note: due to some system trouble on my part, I've been unable to test the integration test programmatically, but it's representative of the issue which caused ClickHouse to crash/stop replicating before the change.

**Comment by cfroystad** [comment]
Is there any way to get the output of the test (given that I'm currently unable to get the test environment running locally)?

At first glance, I'm unable to see what makes the tests fail when the identical operation works when executed manually... Any guidance would be greatly appreciated!

**Comment by cfroystad** [comment]
Sorry, @abyss7, but I've been staring myself blind at the test failures and am likely missing something obvious. Could you point me in the right direction?

**Comment by abyss7** [comment]
> Sorry, @abyss7, but I've been staring myself blind at the test failures and am likely missing something obvious. Could you point me in the right direction?

Can't figure out the exact reason either, but I suggest that the output format may be inappropriate for `assert` - I fixed it like in other tests. Hope it works.

**Comment by cfroystad** [comment]
Thanks for the help!

As far as I can see (though I've been wrong before), the remaining failures and flakiness is unrelated to this change.

**Pull request merged**
