### PR TITLE
Add element on SpaceSaving set if the last element has a lower value compared to the last one

### PR DESCRIPTION
**Pull request by YiuRULE**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

**Category (leave one):**
- Bug Fix

**Short description (up to few sentences):**

Proposal for change the SavingSpace set behavior to remove the last element if the new element have a bigger weight. #5833

**Detailed description (optional):**

The undocumented function `topKWeighted` had a problem when we weren't able to fit all keys to memory, who give quite bad approximation, for example

```
DROP TABLE IF EXISTS test.insert_number_query;

CREATE TABLE test.insert_number_query (
    record UInt32
) Engine = Log;

INSERT INTO test.insert_number_query SELECT * from system.numbers LIMIT 100000;
```

```
SELECT topKWeighted(5)(record, record)
FROM test.insert_number_query 

┌─topKWeighted(5)(record, record)─┐
│ [46,45,44,43,42]                │
└─────────────────────────────────┘
```

Instead of

```
SELECT topKWeighted(5)(record, record)
FROM test.insert_number_query 

┌─topKWeighted(5)(record, record)─┐
│ [99999,99998,99997,99996,99995] │
└─────────────────────────────────┘
```

It was due than the Set was originally created in mind to count the maximum number of occurrence for the function `topK`. Who need to treat one element, with one element, and with increment the internal count one by one.

However as the topKWeighted "emulate" with the weight that the element was already present N times, it doesn't make sense to keep last element if the new element is virtually more present.

expected result now
```
SELECT topKWeighted(5)(record, record)
FROM test.insert_number_query 

┌─topKWeighted(5)(record, record)─┐
│ [99999,99998,99997,99996,99995] │
└─────────────────────────────────┘
```

However, this PR still give an approximation, the result can be different, however it give a better approximation.

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
Could you please also add a test?

**Comment by YiuRULE** [comment]
Ok thanks, I added a test where it's currently fail on the current master version, but work on this version

**Comment by alexey-milovidov** [comment]
And one final thought: could you please add a comment before
```
if (increment > min->count)
```
to explain this part of code?

**Comment by YiuRULE** [comment]
Done :)

**Comment by alexey-milovidov** [comment]
Thank you!

**Pull request merged**
