### PR TITLE
Reduce virtual function call in column map

### PR DESCRIPTION
**Pull request by taiyang-li**
### Changelog category (leave one):
- Performance Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Reduce virtual function call in column map

### CODE REVIEW

**Comment by taiyang-li** [comment]
Let's wait for performance report.

**Comment by robot-clickhouse-ci-1** [comment]
*This is an automated comment for commit c074de419f0cf2dd5f20cdffc4973b96238075b0 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/60121/c074de419f0cf2dd5f20cdffc4973b96238075b0/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/60121/c074de419f0cf2dd5f20cdffc4973b96238075b0/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Comment by rschu1ze** [comment]
In general, I'd consider this a rather unbeautiful micro-optimization (sorry, just thinking aloud)
- for batch operations a single virtual all is amortized by other costs
- for point operations one could argue that it is better to adjust the calling code to not do point operations at all and/or add batch APIs to `IColumn` to do the job on multiple rows.

So, unless there is a nice speedup in performance tests, my preference would be to not merge this PR.

**Comment by taiyang-li** [comment]
> In general, I'd consider this a rather unbeautiful micro-optimization (sorry, just thinking aloud)
> 
> * for batch operations a single virtual all is amortized by other costs
> * for point operations one could argue that it is better to adjust the calling code to not do point operations at all and/or add batch APIs to `IColumn` to do the job on multiple rows.
> 
> So, unless there is a nice speedup in performance tests, my preference would be to not merge this PR.

I had the same considerations with you. Let's wait ci and see.

**Comment by rschu1ze** [comment]
@taiyang-li Like to merge from master again? (I don't have permissions to push to your fork, otherwise I would have done that by myself)

**Pull request closed without merging**
