### PR TITLE
2R: Fix: respect skip_unavailable_shards with parallel replicas

### LINKED ISSUE #53594: Parallel replicas with distributed queries mistakenly skipping unavailable shards.
When you run a query with `allow_experimental_parallel_reading_from_replicas`, it should silently skip unavailable replicas, but shouldn't skip unavailable shards (when no replicas for a shard is available), unless it is explicitly turned on by the `skip_unavailable_shards` setting.

For example, a cluster with multiple shards, each of one replica appears when you query `FROM clusterAllReplicas(...)`

### PR DESCRIPTION
**Pull request by devcrafter**
Reverts #54189 which reverts #53904 which fixes #53594

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by robot-ch-test-poll4** [comment]
This is an automated comment for commit d7076ab017f58835e5e6fadf3d6321fcb4cae2d1 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/54213/d7076ab017f58835e5e6fadf3d6321fcb4cae2d1/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
One test has failed.

**Comment by devcrafter** [comment]
> One test has failed.

Analyzer has issues with distributed queries with sorting. It'll be addressed separately

**Comment by devcrafter** [comment]
@rschu1ze There is a failing fuzz test with inverted-index, is it known, or we should create an issue? See https://s3.amazonaws.com/clickhouse-test-reports/54213/82135cd847238841ebfdc0e78e3de9c90ed489b6/fuzzer_astfuzzerdebug/report.html

**Pull request merged**
