### PR TITLE
Adding TLS Log system table.

### PR DESCRIPTION
**Pull request by tonickkozlov**
system.tls_log contains information about client certificates received by ClickHouse server during TLS handshakes. Useful for improving observability of certificate-based authentication.

### Changelog category (leave one):
- New Feature

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Added a new table system.tls_log to improve observability of certificates used by clients.

### Documentation entry for user-facing changes

- [x] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Run only fuzzers related jobs (libFuzzer fuzzers, AST fuzzers, etc.)
- [ ]  Exclude: AST fuzzers
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-ch-test-poll3** [comment]
*This is an automated comment for commit d75b4ea895b93f47588654a57c5df8279173da1a with description of existing statuses. It's updated for the latest CI running*

[❌ Click here](https://s3.amazonaws.com/clickhouse-test-reports/70754/d75b4ea895b93f47588654a57c5df8279173da1a/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Style check</td><td>Runs a set of checks to keep the code style clean. If some of tests failed, see the related log from the report</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/70754/d75b4ea895b93f47588654a57c5df8279173da1a/style_check.html">❌ failure</a></td></tr>
<tbody>
</table>

**Comment by tonickkozlov** [comment]
@marco-vb Thank you for your help with this change. I think I found a more elegant solution to tracking rejected tls connections - please take a look if you're interested.

**Comment by victor-perov** [comment]
Great work! Thanks @tonickkozlov and @marco-vb!

**Comment by marco-vb** [comment]
> @marco-vb Thank you for your help with this change. I think I found a more elegant solution to tracking rejected tls connections - please take a look if you're interested.

@tonickkozlov thanks for letting me know about this! Great work!

**Comment by CheSema** [comment]
Hi!
I wish to discuss some points here: the volume of the logs and its value.
I had in my mind the case then some one constantly with high rate are connecting to a server.
In that case we do not what to spend a lot of cpu and storage for such events. Otherwise we are vulnerable to such misbehave cases.
What is the point to log the same certs for the errors?

My proposal. Lets make it robust in case of misbehave.
It could be done by limiting the number of error logs records in some time frame. Lets say we log in time frame of 10 seconds only error records with unique certs and the number of errors in a previous frame with that cert.

**Comment by alexey-milovidov** [comment]
No activity, closing.

**Pull request closed without merging**
