### PR TITLE
Apply parallel download for Hive and reuse hdfsBuilder and hdfsFs objects

### PR DESCRIPTION
**Pull request by taiyang-li**
### Changelog category (leave one):
- Performance Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Apply parallel download for Hive

### CODE REVIEW

**Comment by antonio2368** [comment]
LGTM

Have you tested out the performance changes with more threads?

**Comment by taiyang-li** [comment]
> LGTM
> 
> Have you tested out the performance changes with more threads?

@kssenii  I have tested parallel download for Hive query. I's strange that query with parallel download is even slower than query without it.  

Here is the test results:

``` 
Query: select count(1) from indigo_zhangxin8_imolive_sabc_day  where day = '2022-05-01'
Environment: local cache is disabled, default max_download_buffer_size(10mb). There are 27 files under hive partition day=2022-05-01, range of file size: [0.4mb, 1gb] 

![image](https://user-images.githubusercontent.com/8181003/167357207-f2438e24-56bc-4a55-81cc-42e5a8283474.png)
 

threads = 1  
1 rows in set. Elapsed: 32.569 sec. Processed 211.88 million rows, 24.19 GB (6.51 million rows/s., 742.63 MB/s.)
1 rows in set. Elapsed: 54.800 sec. Processed 211.88 million rows, 24.19 GB (3.87 million rows/s., 441.36 MB/s.)
1 rows in set. Elapsed: 27.761 sec. Processed 211.88 million rows, 24.19 GB (7.63 million rows/s., 871.24 MB/s.) 

threads = 4  
1 rows in set. Elapsed: 42.580 sec. Processed 211.88 million rows, 24.19 GB (4.98 million rows/s., 568.02 MB/s.) 
1 rows in set. Elapsed: 46.860 sec. Processed 211.88 million rows, 24.19 GB (4.52 million rows/s., 516.15 MB/s.)
1 rows in set. Elapsed: 46.700 sec. Processed 211.88 million rows, 24.19 GB (4.54 million rows/s., 517.92 MB/s.)

threads = 16  
1 rows in set. Elapsed: 38.809 sec. Processed 211.88 million rows, 24.19 GB (5.46 million rows/s., 623.21 MB/s.)
1 rows in set. Elapsed: 34.431 sec. Processed 211.88 million rows, 24.19 GB (6.15 million rows/s., 702.45 MB/s.)
1 rows in set. Elapsed: 71.334 sec. Processed 211.88 million rows, 24.19 GB (2.97 million rows/s., 339.06 MB/s.) 
```

**Comment by antonio2368** [comment]
@taiyang-li yes that seems too much (4 * 27), try limiting in the same way as for the `StorageURL`:
https://github.com/ClickHouse/ClickHouse/blob/master/src/Storages/StorageURL.cpp#L615

**Comment by taiyang-li** [comment]
> @taiyang-li yes that seems too much (4 * 27 threads), try limiting in the same way as for the `StorageURL`: https://github.com/ClickHouse/ClickHouse/blob/master/src/Storages/StorageURL.cpp#L615

@antonio2368 I'll try. Thank you very much.

**Comment by taiyang-li** [comment]
@antonio2368  I set `num_threads =1` in hard code way to disable parallelism between hive files. Here is test results:
```
threads = 1 
1 rows in set. Elapsed: 288.415 sec. Processed 211.88 million rows, 24.19 GB (734.62 thousand rows/s., 83.86 MB/s.)
1 rows in set. Elapsed: 339.417 sec. Processed 211.88 million rows, 24.19 GB (624.24 thousand rows/s., 71.26 MB/s.  

threads = 16
1 rows in set. Elapsed: 202.142 sec. Processed 211.88 million rows, 24.19 GB (1.05 million rows/s., 119.65 MB/s.)
1 rows in set. Elapsed: 197.592 sec. Processed 211.88 million rows, 24.19 GB (1.07 million rows/s., 122.41 MB/s.)

threads = 32
1 rows in set. Elapsed: 193.060 sec. Processed 211.88 million rows, 24.19 GB (1.10 million rows/s., 125.28 MB/s.) 
1 rows in set. Elapsed: 194.953 sec. Processed 211.88 million rows, 24.19 GB (1.09 million rows/s., 124.06 MB/s.)
```

**Comment by antonio2368** [comment]
It looks like it works.
We still need the logic like in StorageURL so we don't destroy the current multi-file parallelism.

**Comment by taiyang-li** [comment]
@antonio2368  I will finish it later. And I think I found the reason why parallel download in hive is not as efficient as in s3.  

image

**Comment by antonio2368** [comment]
Just a small comment, HDFS API seems much more complex than pure URL/S3. For the latter, we can control the download itself which is what we are trying to accelerate with parallelism but HDFS seems to abstract everything and already provide some optimisations hidden behind the abstractions.

I assume to gain some improvements you would need to a tighter integration with the HDFS, but this just a guess.

**Comment by taiyang-li** [comment]
> I assume to gain some improvements you would need to a tighter integration with the HDFS, but this just a guess.

Yes, I will try.

**Comment by taiyang-li** [comment]
After optimization by reuse HDFS FS and Builder objects. Query duration is more stable, than that in previous test results. Notice that query is generally faster when max_download_threads = 4. 
```
threads = 1
1 rows in set. Elapsed: 31.528 sec. Processed 211.88 million rows, 24.19 GB (6.72 million rows/s., 767.15 MB/s.)
1 rows in set. Elapsed: 32.711 sec. Processed 211.88 million rows, 24.19 GB (6.48 million rows/s., 739.41 MB/s.)
1 rows in set. Elapsed: 32.949 sec. Processed 211.88 million rows, 24.19 GB (6.43 million rows/s., 734.06 MB/s.)

threads = 4 
1 rows in set. Elapsed: 27.680 sec. Processed 211.88 million rows, 24.19 GB (7.65 million rows/s., 873.80 MB/s.)
1 rows in set. Elapsed: 34.128 sec. Processed 211.88 million rows, 24.19 GB (6.21 million rows/s., 708.71 MB/s.)
1 rows in set. Elapsed: 34.852 sec. Processed 211.88 million rows, 24.19 GB (6.08 million rows/s., 693.97 MB/s.)

threads = 16 
1 rows in set. Elapsed: 41.970 sec. Processed 211.88 million rows, 24.19 GB (5.05 million rows/s., 576.28 MB/s.)
1 rows in set. Elapsed: 39.558 sec. Processed 211.88 million rows, 24.19 GB (5.36 million rows/s., 611.41 MB/s.)
1 rows in set. Elapsed: 32.521 sec. Processed 211.88 million rows, 24.19 GB (6.52 million rows/s., 743.71 MB/s.)
``` 

Metrics `HDFSReadInitializeMicroseconds`, which means the time cost of ReadBufferFromHDFSImpl initialization, is

**Comment by taiyang-li** [comment]
Metrics `HDFSReadInitializeMicroseconds`, which means the time cost of ReadBufferFromHDFSImpl initialization. It is much lesser after reusing HDFS FS and Builder objects. 

Before optimization:
|  Metric  |  Duration(us) with max_download_threads = 1  | Duration(us) with max_download_threads = 16 | 
|  --- | ---  | --- | 
| HDFSReadInitializeMicroseconds | 1475596  |  131203364 | 
| HDFSReadInitialize  | 26 | 1227 |
| Average initialize time  | 57ms | 107ms | 
| HDFSReadExecuteMicroseconds | 128561065 | 218803691 |
| HDFSReadExecute | 98143  | 98097 | 
| Average read time | 1.3ms | 2.2 ms |  
| HDFSReadCloseMicroseconds | 2985 | 1318973 | 
| HDFSReadClose |  26 | 1227 | 
| Average close time |   0.11ms | 1.1ms |  

After optimization

**Comment by antonio2368** [comment]
@taiyang-li on which machine have you tested it out?
Too many threads isn't always good if the machine doesn't have many cores, maybe that explains 16 threads.

**Comment by taiyang-li** [comment]
> @taiyang-li on which machine have you tested it out? Too many threads isn't always good if the machine doesn't have many cores, maybe that explains 16 threads.

Intel(R) Xeon(R) Silver 4110 CPU @ 2.10GHz

**Comment by taiyang-li** [comment]
Besides reusing HDFS FS and Builder objects, we try reusing HDFS File objects. The test result is terrible, because hdfs seek in `ReadBufferFromHDFSImpl::ReadBufferFromHDFSImpl` took too much time when max_download_threads > 1 after reusing HDFS File object.  


```
threads = 1
1 rows in set. Elapsed: 31.959 sec. Processed 211.88 million rows, 24.19 GB (6.63 million rows/s., 756.79 MB/s.)
1 rows in set. Elapsed: 31.083 sec. Processed 211.88 million rows, 24.19 GB (6.82 million rows/s., 778.14 MB/s.)
1 rows in set. Elapsed: 38.498 sec. Processed 211.88 million rows, 24.19 GB (5.50 million rows/s., 628.25 MB/s.)

threads = 4 
1 rows in set. Elapsed: 42.592 sec. Processed 211.88 million rows, 24.19 GB (4.97 million rows/s., 567.86 MB/s.)
1 rows in set. Elapsed: 38.424 sec. Processed 211.88 million rows, 24.19 GB (5.51 million rows/s., 629.46 MB/s.)
1 rows in set. Elapsed: 39.176 sec. Processed 211.88 million rows, 24.19 GB (5.41 million rows/s., 617.38 MB/s.)

thread=16: too slow to finish query in a few minutes.   
```

h

**Comment by taiyang-li** [comment]
@kssenii  @antonio2368  I didn't see any obvious performance benefit from parallel downloading from HDFS.  I will close it, thank you for your reviewing.

**Pull request closed without merging**
