### PR TITLE
Speed up iota (filling array with consecutive numbers)

### PR DESCRIPTION
**Pull request by Algunenano**
### Changelog category (leave one):
- Performance Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
- Speed up iota calls (filling array with consecutive numbers)

Affects many places where we need this kind of function.

I decided to only implement SSE42 (which was the default/baseline in official builds) and AVX2 (which gives 1.4x as much performance as SSE42) as I didn't see any improvement in introducing AVX512F or AVX512BW.

Here are the benchmarks I did:

```
clickhouse benchmark --port 49000 --timelimit 10 -q "SELECT * FROM numbers(50000000) format Null";
```

* 23.10.1.1976 official build: localhost:49000, queries: 1149, QPS: 114.765, RPS: 5742591296.002, MiB/s: 43812.495, result RPS: 0.000, result MiB/s: 0.000.
* Master: localhost:49000, queries: 1128, QPS: 112.582, RPS: 5629122754.909, MiB/s: 42946.798, result RPS: 0.000, result MiB/s: 0.000.
* Changes SSE42: localhost:49000, queries: 1120, QPS: 111.864, RPS: 5593191769.538, MiB/s: 42672.667, result RPS: 0.000, result MiB/s: 0.000.
* Changes AVX2: localhost:49000, queries: 1501, QPS: 149.953, RPS: 7497625872.771, MiB/s: 57202.346, result RPS: 0.000, result MiB/s: 0.000.
* Changes AVX512F: localhost:49000, queries: 1480, QPS: 147.832, RPS: 7391576269.195, MiB/s: 56393.252, result RPS: 0.000, result MiB/s: 0.000.
* Changes AVX512BW: localhost:49000, queries: 1486, QPS: 148.394, RPS: 7419700525.981, MiB/s: 56607.823, result RPS: 0.000, result MiB/s: 0.000.

Other affected functions are:
* `rowNumberInBlock`
* `arraySort`
* Anything that uses permutations (`ORDER BY`)

### CODE REVIEW

**Comment by robot-ch-test-poll2** [comment]
*This is an automated comment for commit 87eb18eb748f58e3cfbfe96d03124f3b0e04b7ef with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/58271/87eb18eb748f58e3cfbfe96d03124f3b0e04b7ef/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/58271/87eb18eb748f58e3cfbfe96d03124f3b0e04b7ef/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Review by alexey-milovidov — APPROVED** [review]

**Comment by Algunenano** [comment]
Turns out that when working on min for non numeric types I noticed that `getPermutationImpl` could use a similar improvement. Let's move this new `iota` to somewhere where it can be used in more places.

**Comment by Algunenano** [comment]
To check:
* Darwin builds: It seems that `unsigned long` does not match any of `UInt8, UInt32, UInt64`. OSX hates developers. I'll look for an alternative to declare it conditionally.
* Review the negative change in performance.

**Comment by alexey-milovidov** [comment]
@Algunenano, Mac OS defines uint64_t as unsigned long long instead of unsigned long.

**Comment by Algunenano** [comment]
Fixed the OSX build and verified locally that indeed a couple of tests were slower with the changes. I couldn't see why and it went away as soon as I rebased the branch with master, so let's see what it says now.

**Pull request merged**
