### PR TITLE
Remove noise from unit tests

### PR DESCRIPTION
**Pull request by alexey-milovidov**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Unit tests vomit a ton of garbage, see https://s3.amazonaws.com/clickhouse-test-reports/66457/0c82dc91f07b29ba503d7579c7d3ebecba532b73/unit_tests__tsan_/run.log - remove it.

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-clickhouse** [comment]
*This is an automated comment for commit a61304508f07694354c1f698ad8c8c6ba5b65edc with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/66501/a61304508f07694354c1f698ad8c8c6ba5b65edc/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/1c24085d5b3773ec0634d34b1f74fc520f41e2f9/docs_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Review by jkartseva — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
Needs #66771

**Comment by alexey-milovidov** [comment]
Needs https://github.com/ClickHouse/ClickHouse/pull/66783

**Comment by alexey-milovidov** [comment]
This query cannot parse:

`SELECT 1 WHERE lambda(tuple(x), lambda(lambda(tuple(x), x + (x -> (x + 1, 1)), 1, x + 1, 1) + 1, (lambda(materialize(1), tuple(x), x + 1, 1), x)), x + plus(x + (x -> (x + (x -> (x + 1, x -> (x + 1), 1)), 1)), 1, x, lambda(x + (x -> plus(x)), toUInt256(1), tuple(x), x + 1, 1), 1), toUInt256(1))`

**Comment by alexey-milovidov** [comment]
Fixed in #66819

**Pull request merged**
