### PR TITLE
Fix 00223_shard_distributed_aggregation_memory_efficient with analyzer

### PR DESCRIPTION
**Pull request by KochetovNicolai**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by robot-ch-test-poll** [comment]
*This is an automated comment for commit 624b3a6dbe198eb3c125fe37593b8c22b82c78f8 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/61649/624b3a6dbe198eb3c125fe37593b8c22b82c78f8/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

**Review by novikd — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
No.

```
milovidov-desktop :) select now64(9), now64(9), now64(9)

SELECT
    now64(9),
    now64(9),
    now64(9)

Query id: 5b291c55-3331-4560-9346-766459c64c88

┌──────────────────────now64(9)─┬──────────────────────now64(9)─┬──────────────────────now64(9)─┐
│ 2024-03-21 02:38:28.330617011 │ 2024-03-21 02:38:28.330617011 │ 2024-03-21 02:38:28.330617011 │
└───────────────────────────────┴───────────────────────────────┴───────────────────────────────┘

1 row in set. Elapsed: 0.001 sec. 

milovidov-desktop :) SET allow_experimental_analyzer = 1

SET allow_experimental_analyzer = 1

Query id: 8cfa33bc-6776-46a7-96b9-2284d0019071

Ok.

0 rows in set. Elapsed: 0.000 sec. 

milovidov-desktop :) select now64(9), now64(9), now64(9)

SELECT
    now64(9),
    now64(9),
    now64(9)

Query id: 7f2309c7-ba11-4b44-a076-88a0c43636e3


Elapsed: 0.019 sec. 

Received exception:
Code: 352. DB::Exception: Block structure mismatch in (columns with identical name must have identical structure) stream: different values of constants in column 'now64(9)': actual: '1710985124.920258824', expected: '1710985124.920284072'. (AMBIGUOUS_COLUMN_NAME)
```

**Review by alexey-milovidov — CHANGES_REQUESTED** [review]
.

**Comment by KochetovNicolai** [comment]
@alexey-milovidov now it works
```
SELECT
    now64(9),
    now64(8),
    now64(9)
SETTINGS allow_experimental_analyzer = 1

Query id: d32923b9-c162-4be1-83f1-39aa1248ec04

┌──────────────────────now64(9)─┬─────────────────────now64(8)─┬──────────────────────now64(9)─┐
│ 2024-03-21 18:17:19.252108713 │ 2024-03-21 18:17:19.25213193 │ 2024-03-21 18:17:19.252108713 │
└───────────────────────────────┴──────────────────────────────┴───────────────────────────────┘
```

(but please do not merge before tests with analyzer pass)

**Review by alexey-milovidov — APPROVED** [review]

**Pull request merged**
