### PR TITLE
Fix bug that vector similarity index does not work for cosine distance

### PR DESCRIPTION
**Pull request by ucasfl**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix a bug that the vector similarity index (currently experimental) was not utilized when used with cosine distance as distance function.

### CODE REVIEW

**Comment by robot-ch-test-poll** [comment]
*This is an automated comment for commit c5b92413cac091c4e28acb5160b89fcabc37a853 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/69090/c5b92413cac091c4e28acb5160b89fcabc37a853/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

**Comment by ucasfl** [comment]
It's not bug somehow, it works accidentally before: distance function become `Unknown` when using `cosineDistance`.

**Review by rschu1ze — APPROVED** [review]

**Comment by rschu1ze** [comment]
Interesting, looking at the predecessor of the vector similarity index ([here](https://github.com/ClickHouse/ClickHouse/pull/63675/files#diff-8b1145b4d1ae819fb9e37d520808692ac4565d3354a7f8f80a2da619505d0a11)), cosine distances actually _never_ worked :)

Regarding the function declarations, they are a remnant of the removed support for (obscure) WHERE-type ANN queries ([commit](https://github.com/ClickHouse/ClickHouse/pull/63675/commits/40bed3e20fb309150263771ccddb82822948d474)).

**Comment by rschu1ze** [comment]
Stateless tests (release, old analyzer, s3, DatabaseReplicated) [1/2]: #69316

Performance Comparison (release) [4/4] and : Unrelated

AST Fuzzer debug: #69317

**Pull request merged**
