### PR TITLE
Pipeline Trace

### PR DESCRIPTION
**Pull request by TianyouLi**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Add support for trace pipeline prepare & execution time

- Motivation: Improve the observability of pipeline execution behavior and cost, to help understand the software and hardware platform bottleneck, thus make the performance tuning and optimization more easier for sophisticated queries under large scale systems with many cores. Combining the 'EXPLAIN PIPELINE' feature which decribed the static information about the query pipeline, by collecting the pipeline execution trace at runtime, we can create a view contains useful inforamtion like when each processor starts, how long it tooks, and which thread it scheduled, etc. Furthermore, visualization tool could be created with those traces to give a more intuitive impression to the users.

- Parameters: 'trace_pipeline' flag could be used to turn on/off pipeline tracing. 

- Example use: 
1. select count(distinct(CLID)) from test.hits settings trace_pipeline=1
1. select * from system.pipeline_trace_log where query_id='2fe37fe3-d884-4c7d-8091-0a845bcc5fe1'
1. it could be visualized, eg https://github.com/TianyouLi/clickhouse-pipeline-trace-log-visualization

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by robot-ch-test-poll4** [comment]
*This is an automated comment for commit 40f7d88d3d74ad6c2ab60c36f5aa33a2825bfaef with description of existing statuses. It's updated for the latest CI running*

[❌ Click here](https://s3.amazonaws.com/clickhouse-test-reports/56897/40f7d88d3d74ad6c2ab60c36f5aa33a2825bfaef/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://github.com/ClickHouse/ClickHouse/blob/master/.github/PULL_REQUEST_TEMPLATE.md?plain=1">❌ failure</a></td></tr>
<tbody>
</table>

**Review by vdimir — COMMENTED** [review]
Thank you for the PR!

Could you please check out `system.processors_profile_log` from https://github.com/ClickHouse/ClickHouse/pull/34355 and give a short summary on how this feature correlates with that one?

**Comment by qoega** [comment]
>useful inforamtion like when each processor starts, how long it tooks, and which thread it scheduled, etc. 

This information can be obtained via [opentelemetry_span_log](https://clickhouse.com/docs/en/operations/system-tables/opentelemetry_span_log) when you collect data for your query with `opentelemetry_trace_processors=1`.

**Comment by TianyouLi** [comment]
> Thank you for the PR!
> 
> Could you please check out `system.processors_profile_log` from #34355 and give a short summary on how this feature correlates with that one?

Thanks for the comments instantly, appreciated. Sorry for late response across weekend. I've tried the processor_profile_log and here are the view based on my limited knowledge, please correct me if my understanding is wrong or insufficiently supporting this improvement: 
1. the processors_profile_log has aggregated value for each processors with same processorid, so it would be hard for someone to bread down for the same processor with same processorid but executed multiple times;
2. no thread id associated, so it would be not feasible to understand which processor executed on which thread, thus little chance to diagnose with other tools like perf sched

Based on above, and not to add some changes to break the compatibility of existing one, this improvement was submitted for review. Thanks.

**Comment by TianyouLi** [comment]
> > useful inforamtion like when each processor starts, how long it tooks, and which thread it scheduled, etc.
> 
> This information can be obtained via [opentelemetry_span_log](https://clickhouse.com/docs/en/operations/system-tables/opentelemetry_span_log) when you collect data for your query with `opentelemetry_trace_processors=1`.

Thanks, actually the span log looks promising to me from the code where indicates a lot of useful information already included, eg the thread id and start timestamp; while I was failed to enable it by supplying the 'opentelemetry_trace_processors=1' and the config.xml. From the server start log, the opentelemetry_span_log seems created, but the table did not exist in system db and no data populated for the queries... It would be very helpful if I can follow the instructions to further check any mistakes on my setup. 

image

image

image

**Comment by qoega** [comment]
@TianyouLi You need to enable tracing for a query not in SETTING sessions of a query, but earlier. For example make SET in session or in url if you use HTTP. 

Here is a small guide how to use it

```
How to collect and draw your query trace

1. Enable trace collection 
SET opentelemetry_trace_processors=1;
SET opentelemetry_start_trace_probability=1;

2. For ClickHouse Cloud you set your queryid in this query

WITH 'e4de11cd-5dcd-415a-ac80-a5bfdb43c5b5' AS my_query_id
                  SELECT
                      concat(substring(hostName(), length(hostName()), 1), leftPad(greatest(attribute['clickhouse.thread_id'], attribute['thread_number']), 5, '0')) AS group,
                      operation_name,
                      start_time_us,
                      finish_time_us,
                      sipHash64(operation_name) AS color,
                      attribute
                  FROM clusterAllReplicas('default', 'system', 'opentelemetry_span_log')
                  WHERE trace_id IN (
                      SELECT trace_id
                      FROM clusterAllReplicas('default', 'system', 'opentelemetry_span_log')
                      WHERE (attribute['clickhouse.query_id']) = my_query_id
                  ) AND operation_name !='query' AND operation_name not like 'Query%'
                  ORDER BY
                      hostName() ASC, group ASC,
                      parent_span_id ASC,
                      start_time_us ASC
                  INTO OUTFILE 'trace.json'
                  FORMAT JSON
                  SETTINGS output_format_json_named_tuples_as_objects = 1

For locally running ClickHouse

WITH '6f1e0ef1-9876-4224-be40-14ebfa3ab48b' AS my_query_id
SELECT
    concat(substring(hostName(), length(hostName()), 1), leftPad(greatest(attribute['clickhouse.thread_id'], attribute['thread_number']), 5, '0')) AS group,
    operation_name,
    start_time_us,
    finish_time_us,
    sipHash64(operation_name) AS color,
    attribute
FROM system.opentelemetry_span_log
WHERE (trace_id IN (
    SELECT trace_id
    FROM system.opentelemetry_span_log
    WHERE (attribute['clickhouse.query_id']) = my_query_id
)) AND (operation_name != 'query') AND (operation_name NOT LIKE 'Query%')
ORDER BY
    hostName() ASC,
    group ASC,
    parent_span_id ASC,
    start_time_us ASC
INTO OUTFILE 'trace.json'
FORMAT JSON
SETTINGS output_format_json_named_tuples_as_objects = 1

3. Open in browser clickhouse/utils/trace-visualizer/index.html  And load your file into it
```

**Comment by TianyouLi** [comment]
> @TianyouLi You need to enable tracing for a query not in SETTING sessions of a query, but earlier. For example make SET in session or in url if you use HTTP.
> 
> Here is a small guide how to use it
> 

Appreciated for your instructions. It works like a charm as the figure shows below:) thanks. Allow me to spend some time to get more understanding and then get back to you see if any gap still there based on the needs.  

image

**Comment by TianyouLi** [comment]
Thanks @qoega and @vdimir for the time to review and instructions provided. Close this PR as opentelemetry_trace_log feature looks fullfil the needs(if not, I will create a new PR to enhance it). Appreciated for all your help!

**Pull request closed without merging**
