### PR TITLE
Add jemalloc support fro s390x

### PR DESCRIPTION
**Pull request by bkuschel**
Add support for jemalloc to s390x. Not using jemalloc actually causes memory issues.

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by robot-ch-test-poll2** [comment]
This is an automated comment for commit b79e7e2e617ffc59692f208b6c26bbcaee900ab8 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/51186/b79e7e2e617ffc59692f208b6c26bbcaee900ab8/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Review by alexey-milovidov — APPROVED** [review]

**Comment by bkuschel** [comment]
@alexey-milovidov test failures seem unrelated, can we merge this?

**Comment by alexey-milovidov** [comment]
No way. First, we'll fix all the failures, then return to this PR.

**Comment by bkuschel** [comment]
These failures are not related to this PR, correct?

**Comment by larryluogit** [comment]
@alexey-milovidov this is all clean now. Can it be merged?

**Comment by alexey-milovidov** [comment]
@bkuschel @larryluogit, you need to add s390x to CI to speed up the processing of your pull requests.
See https://github.com/ClickHouse/ClickHouse/pull/31398 as an example.

**Comment by larryluogit** [comment]
@alexey-milovidov thanks for the example. We are working on adding s390x now.

**Pull request merged**
