### PR TITLE
Do not overallocate when creating PODArray with given size

### PR DESCRIPTION
**Pull request by akuzm**
Another part of #12278

Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
AFAIR it gives huge performance degradation.

**Review by alexey-milovidov — APPROVED** [review]
I like this change if it would have no regressions.

**Comment by akuzm** [comment]
Looks like there are 
no significant performance changes https://clickhouse-test-reports.s3.yandex.net/13589/d42dbfce987a7510bb69139eb6e8e099a3f3c0df/performance_comparison/report.html

The memory usage change CDF has some interesting negative tail now.The median is still almost 0, probably because we don't have many queries that are influenced by this optimization:
cumulative-memory_usage

I think it's OK to merge.

**Comment by akuzm** [comment]
For the future reference, another CDF I've built yesterday for a case that doesn't have any memory usage changes: https://github.com/ClickHouse/ClickHouse/pull/13491#issuecomment-671505818

**Pull request merged**
