### PR TITLE
Fix ConcurrentBoundedQueue::emplace() return value in case of finished queue

### PR DESCRIPTION
**Pull request by azat**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Cc: @kitaisreal

### CODE REVIEW

**Comment by azat** [comment]
>[Performance Comparison [1/4] — Errors while building the report.](https://s3.amazonaws.com/clickhouse-test-reports/44881/a2f17d2d9100294acf30a5b43cb81aff026ef10b/performance_comparison_[1/4]/report.html)

Performance tests are broken, and errors is not detected (looks like should be fixed by #44867)

**Comment by Felixoid** [comment]
The tests themself are supposed to be fixed in https://github.com/ClickHouse/ClickHouse/pull/44876

**Comment by azat** [comment]
>The tests themself are supposed to be fixed in https://github.com/ClickHouse/ClickHouse/pull/44876

Funny, I haven't found it, because of the typo in the subject.

**Review by kitaisreal — APPROVED** [review]

**Comment by antonio2368** [comment]
@azat `test_keeper_snapshot_on_exit/test.py::test_snapshot_on_exit` failure seems to be related to this

**Pull request merged**
