### PR TITLE
Everything should work on AArch64

### PR DESCRIPTION
**Pull request by alexey-milovidov**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by robot-ch-test-poll** [comment]
*This is an automated comment for commit 96b81d27b8da898d413621b1409440d6a0fcc612 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/58061/96b81d27b8da898d413621b1409440d6a0fcc612/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td><a href="https://github.com/ClickHouse/ClickHouse/actions/runs/7271135958">✅ success</a></td></tr>
<tbody>
</table>
</details>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/58061/96b81d27b8da898d413621b1409440d6a0fcc612/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Comment by alexey-milovidov** [comment]
Step 1: #60807

**Comment by al13n321** [comment]
Couldn't reproduce the 02892_orc_filter_pushdown failure locally on mac os. But in CI it failed 5/5 times on ARM and 0/39184 times on non-ARM, so it's not flaky: https://play.clickhouse.com/play?user=play#U0VMRUNUCiAgICB0ZXN0X3N0YXR1cywKICAgIHBvc2l0aW9uKGNoZWNrX25hbWUsICdhYXJjaDY0JykgPiAwIGFzIGFybSwKICAgIG1pbihwdWxsX3JlcXVlc3RfbnVtYmVyKSBhcyBwcjEsCiAgICBtYXgocHVsbF9yZXF1ZXN0X251bWJlcikgYXMgcHIyLAogICAgY291bnQoKQpGUk9NIGNoZWNrcwpXSEVSRSBub3coKSAtIHRvSW50ZXJ2YWxEYXkoOTApIDw9IGNoZWNrX3N0YXJ0X3RpbWUgYW5kIHBvc2l0aW9uKHRlc3RfbmFtZSwgJzAyODkyX29yY19maWx0ZXJfcHVzaGRvd24nKSA+IDAKZ3JvdXAgYnkgYWxsCg==

**Comment by rschu1ze** [comment]
My other PR #63675 removes Annoy (in favor of USearch). All exclusions `no-cpu-aarch64` in 02354_vector_search*.sql are removed by the other PR.

**Comment by alexey-milovidov** [comment]
I doubt about the complete removal of Annoy, because at lease one big, nice company is successfully using it...
But Annoy is a simple algorithm - we can rewrite the library.

**Comment by rschu1ze** [comment]
If you look at vector search extensions in other relational and vector DBs, you find HNSW in almost all systems, and Annoy only rarely implemented. From what I read, Annoy doesn't work great with high dimensionality. This was the main reason to remove it.

Actually, #63675 provides a generic "vector similarity" index and the algorithms is specified like this:

```sql
CREATE TABLE tab (id Int32, vec Array(Float32), INDEX vec_idx(vec) TYPE vector_similarity('hnsw', 'L2Distance'));
```

So if we want, we can add it back, perhaps implemented from scratch.

**Comment by alexey-milovidov** [comment]
Ah, ok. Let's remove it for now. Possibly add it back later.
At least the data could be re-indexed.

**Comment by al13n321** [comment]
https://github.com/ClickHouse/ClickHouse/pull/64563 for 02892_orc_filter_pushdown.

**Comment by alexey-milovidov** [comment]
Only Annoy and Intel QPL are not going to be supported.

**Pull request closed without merging**
