### PR TITLE
Fix shutdown in GRPCServer

### LINKED ISSUE #65622: GRPCServer gets stuck on server shutdown
The server is shutting down and gets stuck forever:
```
...
2024.06.24 17:54:28.810538 [ 883030 ] {} <Debug> KeeperLogStore: Shutting down Changelog
2024.06.24 17:54:28.810555 [ 883621 ] {} <Test> KeeperLogStore: Flushing 0 logs
2024.06.24 17:54:28.810810 [ 883622 ] {} <Information> KeeperLogStore: Raft server is not set in LogStore.
2024.06.24 17:54:28.811517 [ 883030 ] {} <Debug> KeeperSnapshotManagerS3: Shutting down KeeperSnapshotManagerS3
2024.06.24 17:54:28.811648 [ 883030 ] {} <Information> KeeperSnapshotManagerS3: KeeperSnapshotManagerS3 shut down
2024.06.24 17:54:28.811726 [ 883030 ] {} <Debug> KeeperDispatcher: Dispatcher shut down
2024.06.24 17:54:28.814086 [ 883030 ] {} <Debug> Application: Destroyed global context.
2024.06.24 17:54:28.817363 [ 883030 ] {} <Information> Application: Waiting for background threads

```

config: https://pastila.nl/?0031341e/94cf03cdbce4314587c7618ad506af99#0e81BR9RGhzYwiKPvYJa6g==
stacktraces: https://pastila.nl/?00013fcd/e1201462b1cd5c6d146c739e398b65a1#LPxpYcAYTZbEUt/4k4XPkA==

The main thread is waiting for 
```
Thread 7 (Thread 0x7ff213c3c6c0 (LWP 884412) "GRPCServerQueue"):
#0  __syscall () at /home/tavplubix/ch/ClickHouse/base/glibc-compatibility/musl/x86_64/syscall.s:14
#1  0x0000000028a56484 in epoll_pwait (fd=68, ev=0x299f7ad4 <g_epoll_set+4>, cnt=100, to=-1, sigs=0x0) at /home/tavplubix/ch/ClickHouse/base/glibc-compatibility/musl/epoll.c:27
#2  0x0000000028a5650e in epoll_wait (fd=68, ev=0x299f7ad4 <g_epoll_set+4>, cnt=100, to=-1) at /home/tavplubix/ch/ClickHouse/base/glibc-compatibility/musl/epoll.c:36
#3  0x0000000026627c43 in do_epoll_wait (ps=0x7ff37ee6ddc8, deadline=...) at /home/tavplubix/ch/ClickHouse/contrib/grpc/src/core/lib/iomgr/ev_epoll1_linux.cc:723
#4  0x00000000266259a7 in pollset_work (ps=0x7ff37ee6ddc8, worker_hdl=0x0, deadline=...) at /home/tavplubix/ch/ClickHouse/contrib/grpc/src/core/lib/iomgr/ev_epoll1_linux.cc:1038
#5  0x0000000026623bd0 in pollset_work (pollset=0x7ff37ee6ddc8, worker=0x0, deadline=...) at /home/tavplubix/ch/ClickHouse/contrib/grpc/src/core/lib/iomgr/ev_posix.cc:249
#6  0x0000000026634b8d in grpc_pollset_work (pollset=0x7ff37ee6ddc8, worker=0x0, deadline=...) at /home/tavplubix/ch/ClickHouse/contrib/grpc/src/core/lib/iomgr/pollset.cc:48
#7  0x000000002673ee34 in cq_next (cq=0x7ff37ee6dc00, deadline=..., reserved=0x0) at /home/tavplubix/ch/ClickHouse/contrib/grpc/src/core/lib/surface/completion_queue.cc:1050
#8  0x000000002673de8a in grpc_completion_queue_next (cq=0x7ff37ee6dc00, deadline=..., reserved=0x0) at /home/tavplubix/ch/ClickHouse/contrib/grpc/src/core/lib/surface/completion_queue.cc:1128
#9  0x000000002636e895 in grpc::CompletionQueue::AsyncNextInternal (this=0x7ff37e3a3100, tag=0x7ff213c2bb50, ok=0x7ff213c2bb5f, deadline=...) at /home/tavplubix/ch/ClickHouse/contrib/grpc/src/cpp/common/completion_queue_cc.cc:146
#10 0x000000001f96ddbd in grpc::CompletionQueue::Next (this=0x7ff37e3a3100, tag=0x7ff213c2bb50, ok=0x7ff213c2bb5f) at /home/tavplubix/ch/ClickHouse/contrib/grpc/include/grpcpp/completion_queue.h:182
#11 0x000000001f96dce2 in DB::GRPCServer::Runner::run (this=0x7ff37e27c6e0) at /home/tavplubix/ch/ClickHouse/src/Server/GRPCServer.cpp:1849
#12 0x000000001f96daa5 in DB::GRPCServer::Runner::start()::{lambda()#1}::operator()() const (this=0x7ff213c2bca0) at /home/tavplubix/ch/ClickHouse/src/Server/GRPCServer.cpp:1755
#13 0x000000001f96da75 in std::__1::__invoke[abi:v15000]<DB::GRPCServer::Runner::start()::{lambda()#1}&>(DB::GRPCServer::Runner::start()::{lambda()#1}&) (__f=...) at /home/tavplubix/ch/ClickHouse/contrib/llvm-project/libcxx/include/__functional/invoke.h:394
#14 0x000000001f96da59 in std::__1::__apply_tuple_impl[abi:v15000]<DB::GRPCServer::Runner::start()::{lambda()#1}&, std::__1::tuple<>&>(DB::GRPCServer::Runner::start()::{lambda()#1}&, std::__1::tuple<>&, std::__1::__tuple_indices<>) (__f=..., __t=...) at /home/tavplubix/ch/ClickHouse/contrib/llvm-project/libcxx/include/tuple:1789
#15 0x000000001f96d9bd in std::__1::apply[abi:v15000]<DB::GRPCServer::Runner::start()::{lambda()#1}&, std::__1::tuple<>&>(DB::GRPCServer::Runner::start()::{lambda()#1}&, std::__1::tuple<>&) (__f=..., __t=...) at /home/tavplubix/ch/ClickHouse/contrib/llvm-project/libcxx/include/tuple:1798
#16 0x000000001f96d8df in ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::GRPCServer::Runner::start()::{lambda()#1}&>(DB::GRPCServer::Runner::start()::{lambda()#1}&)::{lambda()#1}::operator()() (this=0x7ff380515700) at /home/tavplubix/ch/ClickHouse/src/Common/ThreadPool.h:251
--Type <RET> for more, q to quit, c to continue without paging--
#17 0x000000001f96d775 in std::__1::__invoke[abi:v15000]<ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::GRPCServer::Runner::start()::{lambda()#1}&>(DB::GRPCServer::Runner::start()::{lambda()#1}&)::{lambda()#1}&>(DB::GRPCServer::Runner::start()::{lambda()#1}&) (__f=...) at /home/tavplubix/ch/ClickHouse/contrib/llvm-project/libcxx/include/__functional/invoke.h:394
#18 0x000000001f96d755 in std::__1::__invoke_void_return_wrapper<void, true>::__call<ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::GRPCServer::Runner::start()::{lambda()#1}&>(DB::GRPCServer::Runner::start()::{lambda()#1}&)::{lambda()#1}&>(ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::GRPCServer::Runner::start()::{lambda()#1}&>(DB::GRPCServer::Runner::start()::{lambda()#1}&)::{lambda()#1}&) (__args=...) at /home/tavplubix/ch/ClickHouse/contrib/llvm-project/libcxx/include/__functional/invoke.h:479
#19 0x000000001f96d735 in std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::GRPCServer::Runner::start()::{lambda()#1}&>(DB::GRPCServer::Runner::start()::{lambda()#1}&)::{lambda()#1}, void ()>::operator()[abi:v15000]() (this=0x7ff380515700) at /home/tavplubix/ch/ClickHouse/contrib/llvm-project/libcxx/include/__functional/function.h:235
#20 0x000000001f96d700 in std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::GRPCServer::Runner::start()::{lambda()#1}&>(DB::GRPCServer::Runner::start()::{lambda()#1}&)::{lambda()#1}, void ()> >(std::__1::__function::__policy_storage const*) (__buf=0x7ff213c2c290) at /home/tavplubix/ch/ClickHouse/contrib/llvm-project/libcxx/include/__functional/function.h:716
#21 0x00000000126bd216 in std::__1::__function::__policy_func<void ()>::operator()[abi:v15000]() const (this=0x7ff213c2c290) at /home/tavplubix/ch/ClickHouse/contrib/llvm-project/libcxx/include/__functional/function.h:848
#22 0x00000000126bce75 in std::__1::function<void ()>::operator()() const (this=0x7ff213c2c290) at /home/tavplubix/ch/ClickHouse/contrib/llvm-project/libcxx/include/__functional/function.h:1187
#23 0x00000000140df9b2 in ThreadPoolImpl<std::__1::thread>::worker (this=0x7ff48da3d480, thread_it=...) at /home/tavplubix/ch/ClickHouse/src/Common/ThreadPool.cpp:462
#24 0x00000000140e8211 in ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::{lambda()#2}::operator()() const (this=0x7ff26ba0cf88) at /home/tavplubix/ch/ClickHouse/src/Common/ThreadPool.cpp:219
#25 0x00000000140e81b5 in std::__1::__invoke[abi:v15000]<ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::{lambda()#2}>(ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::{lambda()#2}&&) (__f=...) at /home/tavplubix/ch/ClickHouse/contrib/llvm-project/libcxx/include/__functional/invoke.h:394
#26 0x00000000140e817d in std::__1::__thread_execute[abi:v15000]<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::{lambda()#2}>(std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::{lambda()#2}>&, std::__1::__tuple_indices<>) (__t=...) at /home/tavplubix/ch/ClickHouse/contrib/llvm-project/libcxx/include/thread:284
#27 0x00000000140e7f4f in std::__1::__thread_proxy[abi:v15000]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::{lambda()#2}> >(void*) (__vp=0x7ff26ba0cf80) at /home/tavplubix/ch/ClickHouse/contrib/llvm-project/libcxx/include/thread:295
#28 0x00007ff48e9601cf in ?? () from /usr/lib/libc.so.6
#29 0x00007ff48e9e16ec in ?? () from /usr/lib/libc.so.6
```
which got stuck here:
https://github.com/ClickHouse/ClickHouse/blob/a05fccf8cc92f30ee27618ee067697613bc7ade1/src/Server/GRPCServer.cpp#L1849

### PR DESCRIPTION
**Pull request by vitlibar**
### Changelog category:
- Bug Fix

### Changelog entry:
Fix a possible hanging in `GRPCServer` during shutdown.
This PR fixes https://github.com/ClickHouse/ClickHouse/issues/65622

### CODE REVIEW

**Comment by robot-ch-test-poll4** [comment]
*This is an automated comment for commit e8701dc4e4b1893dbe507d5180f8367a6d4b7689 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/66061/e8701dc4e4b1893dbe507d5180f8367a6d4b7689/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/3b459634f52ff8244b2123ef9ade80f3d5a5a1d4/docs_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Review by thevar1able — APPROVED** [review]

**Comment by thevar1able** [comment]
Maybe we should add a test?

**Comment by vitlibar** [comment]
> Maybe we should have a test for this case?

done

**Comment by vitlibar** [comment]
Failed tests:
- [Stateless tests (debug): 02232_allow_only_replicated_engine](https://s3.amazonaws.com/clickhouse-test-reports/66061/87dda31a2c234a7596b661ad5d63f74f3124ea25/stateless_tests__debug__[1_5].html) - <jemalloc>: /build/contrib/jemalloc/src/decay.c:92: Failed assertion: "nstime_compare(&decay->epoch, new_time) <= 0" - similar to https://github.com/ClickHouse/ClickHouse/issues/66029.
- [Stateless tests (debug, s3 storage): 01541_max_memory_usage_for_user_long](https://s3.amazonaws.com/clickhouse-test-reports/66061/87dda31a2c234a7596b661ad5d63f74f3124ea25/stateless_tests__debug__s3_storage__[6_6].html) - <jemalloc>: /build/contrib/jemalloc/src/decay.c:92: Failed assertion: "nstime_compare(&decay->epoch, new_time) <= 0" - similar to https://github.com/ClickHouse/ClickHouse/issues/66029.
- [AST fuzzer (debug) — Logical error: 'Inconsistent AST formatting](https://s3.amazonaws.com/clickhouse-test-reports/66061/87dda31a2c234a7596b661ad5d63f74f3124ea25/ast_fuzzer__debug_.html) - already known, see https://github.com/ClickHouse/ClickHouse/issues/62227#issuecomment-2209064120

**Comment by tavplubix** [comment]
> Maybe we should have a test for this case?

Stress tests would test it automatically if we had functional tests for grpc. See also https://github.com/ClickHouse/ClickHouse/pull/39359#issuecomment-1188296170

**Comment by vitlibar** [comment]
> Stress tests would test it automatically if we had functional tests for grpc.

gRPC protocol needs to be enabled in the server configuration. It seems we don't use it widely enough to enable it for all our stateless tests.

**Comment by tavplubix** [comment]
> > Stress tests would test it automatically if we had functional tests for grpc.
> 
> gRPC protocol needs to be enabled in the server configuration. It seems we don't use it widely enough to enable it for all our stateless tests.

Why not? It will not affect other functional tests. And AFAIK we have MySQL protocol enabled in functional tests, for example. Let's just enable gRPC. It's easy to add a config for stateless tests: https://github.com/ClickHouse/ClickHouse/blob/d06d2a69db53007991d6e8387f0eff6447ac3fd8/tests/config/install.sh

**Pull request merged**
