### PR TITLE
Fix small typo in Dictionary source loader

### PR DESCRIPTION
**Pull request by seandhaynes**
### Changelog category: 

Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix small typo in Dictionary source loader

### Documentation entry for user-facing changes
Not required (just a small typo)

### CODE REVIEW

**Comment by robot-ch-test-poll4** [comment]
*This is an automated comment for commit 500c3fe0fcb197f7d8b2f0a6148480727015acf1 with description of existing statuses. It's updated for the latest CI running*

[❌ Click here](https://s3.amazonaws.com/clickhouse-test-reports/62320/500c3fe0fcb197f7d8b2f0a6148480727015acf1/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>❌ failure</td></tr>
<tbody>
</table>

**Comment by divanik** [comment]
Hi, @seandhaynes. Thank you for your contribution to ClickHouse. Could you, please, bring into line description to this PR with [these requirements](https://github.com/ClickHouse/ClickHouse/blob/master/.github/PULL_REQUEST_TEMPLATE.md)

**Comment by seandhaynes** [comment]
> Hi, @seandhaynes. Thank you for your contribution to ClickHouse. Could you, please, bring into line description to this PR with [these requirements](https://github.com/ClickHouse/ClickHouse/blob/master/.github/PULL_REQUEST_TEMPLATE.md)

Thank you, @divanik . I've updated the description, but please do let me know if you would like me to include anything else. Thanks again!

**Comment by seandhaynes** [comment]
Thank you, @divanik !

**Pull request merged**
