### PR TITLE
Set version of tzlocal to 2.1

### PR DESCRIPTION
**Pull request by vitlibar**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category:
- Not for changelog

This PR must fix issues with integration tests and testflows tests:

```
test_dictionaries_all_layouts_separate_sources/test_cassandra.py:
AttributeError: 'backports.zoneinfo.ZoneInfo' object has no attribute 'localize'
```

```
/clickhouse/datetime64 extended range:
ModuleNotFoundError: No module named 'pytz'
```

### CODE REVIEW

**Comment by alesapin** [comment]
Maybe explicitly install `pytz`?

**Review by alesapin — APPROVED** [review]

**Comment by vitlibar** [comment]
> Maybe explicitly install `pytz`?

No, that won't help because in addition to the dependency on `pytz` there are also other changes in `tzlocal`, for example our code calls the function `tzlocal.get_localzone()` which returns instances of different types in `tzlocal 2.1` and `tzlocal 3.0`.

**Comment by alesapin** [comment]
> > Maybe explicitly install `pytz`?
> 
> No, that won't help because in addition to the dependency on `pytz` there are also other changes in `tzlocal`, for example our code calls the function `tzlocal.get_localzone()` which returns instances of different types in `tzlocal 2.1` and `tzlocal 3.0`.

Yes, it's clear to me, but explicit `pytz` install will be more obvious. Let's install both `pytz` and `tzlocal` of the required version?

**Review by alesapin — APPROVED** [review]

**Comment by alesapin** [comment]
`Error response from daemon: Dockerfile parse error line 83: unknown instruction: REDIS`???

**Review by alexey-milovidov — APPROVED** [review]

**Pull request merged**
