### PR TITLE
Introduce Code of Conduct using default GitHub template

### PR DESCRIPTION
**Pull request by blinkov**
Changelog category (leave one):
- Documentation (changelog entry is not required)

### CODE REVIEW

**Review by qoega — APPROVED** [review]

**Review by alesapin — APPROVED** [review]

**Review by alexey-milovidov — CHANGES_REQUESTED** [review]
.

**Comment by alexey-milovidov** [comment]
If we will start introducing code of conduct, there will be too high pressure to add something more and more into it. We have to apply something different.

**Comment by blinkov** [comment]
@alexey-milovidov why? it's just a common template and I don't see any reason to change it in foreseeable future

**Comment by alexey-milovidov** [comment]
> it's just a common template and I don't see any reason to change it in foreseeable future

That's exactly what I'm worried.

**Comment by blinkov** [comment]
@alexey-milovidov "there will be too high pressure to add something more and more into it" and "I don't see any reason to change it in foreseeable future" are completely opposite, so what exactly you are worried about?

**Comment by alexey-milovidov** [comment]
You just copy-pasted the recommended code of conduct. But you did not reviewed all the words in this text. It does not look like that we really have to adopt this code of conduct. It is not motivated enough. Actually there is no demand for code of conduct at all. There was no discussions and no alternatives were considered. This is not the way to go.

PS. I understand that you have added it only because of this:
Screenshot_20200316_135013

But please don't make the potentially disruptive changes only because of some fancy check marks on GitHub.

**Comment by alexey-milovidov** [comment]
Closed for internal discussion.

**Comment by alexey-milovidov** [comment]
Closed for internal discussion.

**Comment by alexey-milovidov** [comment]
Closed for internal discussion.

**Comment by alexey-milovidov** [comment]
.

**Comment by alexey-milovidov** [comment]
That's a good choice: http://nocodeofconduct.com/

**Comment by alexey-milovidov** [comment]
Please go and read all the comments and discussions from the first page of https://hn.algolia.com/?q=code+of+conduct before we proceed.

**Comment by alexey-milovidov** [comment]
.

**Pull request closed without merging**
