### PR TITLE
Added failing tests about "max_rows_to_sort" setting.

### PR DESCRIPTION
**Pull request by alexey-milovidov**
Changelog category (leave one):
- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fixed error with "max_rows_to_sort" limit.

Continuation of #4385

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
@KochetovNicolai It triggets "Pipeline stuck".

**Comment by alexey-milovidov** [comment]
Some checks did not finish.

**Comment by KochetovNicolai** [comment]
LGTM, but why not to let me review it before merge?

**Comment by alexey-milovidov** [comment]
I'm too eager.

**Pull request merged**
