### PR TITLE
Functions MySQL compatibility

### PR DESCRIPTION
**Pull request by dankondr**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

**Changelog category (leave one):**
- Improvement

**Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):**

Improve MySQL compatibility

**Detailed description / Documentation draft:**

Added MySQL compatibility aliases:

Function name | Added aliases
--------------- | ---------------
isNull | ISNULL
hex | HEX
toHour | HOUR
toMinute | MINUTE
toSecond | SECOND
base64Encode | TO_BASE64
base64Decode | FROM_BASE64
toDayOfYear | DAYOFYEAR
toDayOfWeek | DAYOFWEEK
toDayOfMonth | DAYOFMONTH, DAY
toMonth | MONTH
toYear | YEAR
toDate | DATE
toQuarter | QUARTER
FunctionIPv6NumToString | INET6_NTOA
FunctionIPv6StringToNum | INET6_ATON
FunctionIPv4NumToString | INET_NTOA
FunctionIPv4StringToNum | INET_ATON
repeat | REPEAT

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
BTW, IN is already supported as operator, and as I know, there is no function form of IN in MySQL.

**Comment by alexey-milovidov** [comment]
Does EXTRACT have the same order and meaning of arguments?

**Comment by alexey-milovidov** [comment]
Also need to add tests (to show at least that these forms of functions exist), see tests/queries/0_stateless/

**Comment by dankondr** [comment]
> BTW, IN is already supported as operator, and as I know, there is no function form of IN in MySQL.

> Does EXTRACT have the same order and meaning of arguments?

My bad. Reverting.

**Comment by filimonov** [comment]
Please add also:
toMonth  => MONTH 
toYear  => YEAR 

to close https://github.com/ClickHouse/ClickHouse/issues/19557

**Comment by olgarev** [comment]
@alexey-milovidov Does this PR need a `docs-alert` tag, to document the aliases?

**Comment by alexey-milovidov** [comment]
Yes.

**Pull request merged**
