### PR TITLE
Move FunctionsJSON implementation to header file

### PR DESCRIPTION
**Pull request by DimasKovas**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
...

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by DimasKovas** [comment]
Motivation: we use this implementation for yson functions in CHYT, so we need it in .h file:
https://github.com/ytsaurus/ytsaurus/blob/main/yt/yt/library/clickhouse_functions/yson_extract.cpp#L209

For ClickHouse itself this change is no-op.

**Comment by DimasKovas** [comment]
For proper diff it is easier to look at commits separately. Have no idea why final diff does not show that I just moved the file.

**Comment by rschu1ze** [comment]
Relying on the fact that code in a technically unrelated project (ClickHouse) lives in a header file is fragile and questionable. What if someone moves the code back in a few weeks? Ytsaurus will break (again) ...

**Comment by DimasKovas** [comment]
> What if someone moves the code back in a few weeks? Ytsaurus will break (again)

We (as a CH customer) will try to work out this question with the ClickHouse team through a customer support protocol. But for now we are ready to bring new PRs with fixes if somethings is broken again.

**Comment by rschu1ze** [comment]
For reference, the same code move was done in YTSaurus' fork of ClickHouse: https://github.com/DimasKovas/ClickHouse/pull/1

I am totally good with doing that in the fork but I am still skeptical about contributing this back to upstream ClickHouse. Just curious to understand, why can YTSaurus not \#include the JSON function headers and compile the corresponding source file using it's own build description (CMake?).

As a compromise, maybe you could move only the declarations into the header? (please add a source comment with an explanation why that was done). You will then still be able to instantiate the templates with your own stuff (if that is what YTSaurus is doing)

**Comment by DimasKovas** [comment]
>the same code move was done in YTSaurus' fork of ClickHouse: https://github.com/DimasKovas/ClickHouse/pull/1

DimasKovas/ClickHouse is not an YTsaurus's fork. I merged this branch to test_merge_branch in my own fork just to make sure that code blame is not broken after this move (because github diff for this pr shows that I removed and added the whole code, which is not true, as you can see if you look at every commit separately).

In YTsaurus we use ClickHouse as a library. We don't want to maintain a ClickHouse fork, because it takes a lot of effort to resolve conflicts while fetching new changes from the original ClickHouse repository.

> As a compromise, maybe you could move only the declarations into the header? You will then still be able to instantiate the templates with your own stuff.

No, because we use JSON*Impl template classes and parametrize them with our own parser for yson-format (format similar to json, so we just reuse the implementation for json functions). For a template instantiation we need its definition.

**Comment by vitlibar** [comment]
@DimasKovas If I understood correctly you don't need the whole `FunctionsJSON.cpp` to be in a header, you need only the `FunctionJSONHelpers` template. If so, let's move to a header only this template, and let's give that header a different name.

**Comment by DimasKovas** [comment]
> you need only the FunctionJSONHelpers template

No. We need almost all JSON*Impl templates as well.

Let me explain, for every JSON* function we have a similar YSON* function, which utilizes the same JSON*Impl template, but is parametrized with a parser for yson format. So we need not all, but **most** of the code from this file.

And actually, I see that most of the functions now are implemented the same way - an implementation lives in a .h file, and there is only a function registration in .cpp file.

Examples:
https://github.com/ClickHouse/ClickHouse/blob/master/src/Functions/FunctionSQLJSON.cpp
https://github.com/ClickHouse/ClickHouse/blob/master/src/Functions/FunctionShowCertificate.cpp
https://github.com/ClickHouse/ClickHouse/blob/master/src/Functions/FunctionToDecimalString.cpp
https://github.com/ClickHouse/ClickHouse/blob/master/src/Functions/FunctionsBitmap.cpp
https://github.com/ClickHouse/ClickHouse/blob/master/src/Functions/FunctionsEmbeddedDictionaries.cpp
https://github.com/ClickHouse/ClickHouse/blob/master/src/Functions/addDays.cpp
And so on...

I don't understand why FunctionsJSON should be special and live only in .cpp file. Since this .h file is included only once, there is absolutely no difference in compile time and etc.

And one more point - I don't want to "steal" the blame for those functions - just moving the file perfectly solves this problem.

**Comment by vitlibar** [comment]
> And actually, I see that most of the functions now are implemented the same way - an implementation lives in a .h file, and there is only a function registration in .cpp file.

OK, it seems there is nothing wrong with this template class to be in the header file.

**Review by vitlibar — APPROVED** [review]

**Comment by vitlibar** [comment]
The test failures seem unrelated to this PR's changes

**Pull request merged**
