### PR TITLE
Change timezone in stateless tests

### PR DESCRIPTION
**Pull request by alexey-milovidov**
Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
Tests for historical time most likely have to be adjusted.

**Comment by qoega** [comment]
Still interested? Or leave it as it is?

**Comment by alexey-milovidov** [comment]
Yes, this is still relevant.

**Comment by alexey-milovidov** [comment]
@mergifyio update

**Pull request merged**
