### PR TITLE
modification retention function

### PR DESCRIPTION
**Pull request by nicelulu**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

For changelog. Remove if this is non-significant change.

Category (leave one):
- Bug Fix

Short description (up to few sentences):
If a row satisfies both the first and NTH condition, only the first satisfied condition is added to the data state. Now all conditions that satisfy in a row of data are added to the data state.

### CODE REVIEW

**Comment by nicelulu** [comment]
https://github.com/yandex/ClickHouse/issues/5108

**Comment by nicelulu** [comment]
Performance will be worse. Or we need to say that a row of data cannot satisfy both the first and NTH conditions.

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
Please add description for changelog.

**Comment by nicelulu** [comment]
> Please add description for changelog.

Do I need to add code comments?

**Comment by alexey-milovidov** [comment]
Now everything is perfect, thank you!

**Pull request merged**
