### PR TITLE
Cherry pick #65505 to 23.8: Final does not respect read in order

### PR DESCRIPTION
**Pull request by robot-ch-test-poll2**
Original pull-request #65505

This pull-request is a first step of an automated backporting.
It contains changes similar to calling `git cherry-pick` locally.
If you intend to continue backporting the changes, then resolve all conflicts if any.
Otherwise, if you do not want to backport them, then just close this pull-request.

The check results does not matter at this step - you can safely ignore them.

### Note

This pull-request will be merged automatically. Please, **do not merge it manually** (but if you accidentally did, nothing bad will happen).

#### If the PR was manually reopened after being closed

If this PR is stuck (i.e. not automatically merged after one day), check https://github.com/ClickHouse/ClickHouse/pull/65505 for `pr-backports-created` *label* and delete it.

Manually merging will do nothing. The `pr-backports-created` *label* prevents the original PR https://github.com/ClickHouse/ClickHouse/pull/65505 from being processed.

#### If the conflicts were resolved in a wrong way

If this cherry-pick PR is completely screwed by a wrong conflicts resolution, and you want to recreate it:

- delete the `pr-cherrypick` label from the PR
- delete this branch from the repository

You also need to check the original PR https://github.com/ClickHouse/ClickHouse/pull/65505 for `pr-backports-created`, and delete if it's presented there

### CODE REVIEW

**Comment by robot-ch-test-poll1** [comment]
Dear @KochetovNicolai, @jkartseva, the PR is not updated for 1d24h0m49s. Please, either resolve the conflicts, or close it to finish the backport process of #65505

**Comment by robot-ch-test-poll** [comment]
Dear @KochetovNicolai, @jkartseva, the PR is not updated for 1d24h1m43s. Please, either resolve the conflicts, or close it to finish the backport process of #65505

**Comment by robot-ch-test-poll3** [comment]
Dear @KochetovNicolai, @jkartseva, the PR is not updated for 1d24h55m23s. Please, either resolve the conflicts, or close it to finish the backport process of #65505

**Comment by robot-ch-test-poll2** [comment]
Dear @KochetovNicolai, @jkartseva, the PR is not updated for 1d25h1m22s. Please, either resolve the conflicts, or close it to finish the backport process of #65505

**Comment by robot-ch-test-poll3** [comment]
Dear @KochetovNicolai, @jkartseva, the PR is not updated for 1d24h59m49s. Please, either resolve the conflicts, or close it to finish the backport process of #65505

**Comment by robot-ch-test-poll3** [comment]
Dear @KochetovNicolai, @jkartseva, the PR is not updated for 1d24h59m25s. Please, either resolve the conflicts, or close it to finish the backport process of #65505

**Comment by robot-clickhouse-ci-1** [comment]
Dear @KochetovNicolai, @jkartseva, the PR is not updated for 1d24h1m32s. Please, either resolve the conflicts, or close it to finish the backport process of #65505

**Comment by robot-clickhouse-ci-2** [comment]
Dear @KochetovNicolai, @jkartseva, the PR is not updated for 1d24h58m32s. Please, either resolve the conflicts, or close it to finish the backport process of #65505

**Comment by robot-ch-test-poll1** [comment]
Dear @KochetovNicolai, @jkartseva, the PR is not updated for 1d25h3m28s. Please, either resolve the conflicts, or close it to finish the backport process of #65505

**Comment by robot-ch-test-poll1** [comment]
Dear @KochetovNicolai, @jkartseva, the PR is not updated for 1d24h55m47s. Please, either resolve the conflicts, or close it to finish the backport process of #65505

**Comment by robot-ch-test-poll3** [comment]
Dear @KochetovNicolai, @jkartseva, the PR is not updated for 1d24h59m44s. Please, either resolve the conflicts, or close it to finish the backport process of #65505

**Comment by robot-ch-test-poll2** [comment]
Dear @KochetovNicolai, @jkartseva, the PR is not updated for 1d24h0m58s. Please, either resolve the conflicts, or close it to finish the backport process of #65505

**Comment by robot-ch-test-poll1** [comment]
Dear @KochetovNicolai, @jkartseva, the PR is not updated for 1d25h2m48s. Please, either resolve the conflicts, or close it to finish the backport process of #65505

**Comment by robot-ch-test-poll1** [comment]
Dear @KochetovNicolai, @jkartseva, the PR is not updated for 1d24h55m37s. Please, either resolve the conflicts, or close it to finish the backport process of #65505

**Comment by robot-ch-test-poll1** [comment]
Dear @KochetovNicolai, @jkartseva, the PR is not updated for 1d24h0m51s. Please, either resolve the conflicts, or close it to finish the backport process of #65505

**Comment by robot-clickhouse-ci-2** [comment]
Dear @KochetovNicolai, @jkartseva, the PR is not updated for 1d24h1m35s. Please, either resolve the conflicts, or close it to finish the backport process of #65505

**Comment by robot-ch-test-poll** [comment]
Dear @KochetovNicolai, @jkartseva, the PR is not updated for 1d24h0m22s. Please, either resolve the conflicts, or close it to finish the backport process of #65505

**Comment by robot-ch-test-poll2** [comment]
Dear @KochetovNicolai, @jkartseva, the PR is not updated for 1d25h5m46s. Please, either resolve the conflicts, or close it to finish the backport process of #65505

**Comment by robot-clickhouse-ci-1** [comment]
Dear @KochetovNicolai, @jkartseva, the PR is not updated for 1d24h0m51s. Please, either resolve the conflicts, or close it to finish the backport process of #65505

**Comment by robot-clickhouse-ci-1** [comment]
Dear @KochetovNicolai, @jkartseva, the PR is not updated for 1d24h3m17s. Please, either resolve the conflicts, or close it to finish the backport process of #65505

**Comment by robot-clickhouse-ci-1** [comment]
Dear @KochetovNicolai, @jkartseva, the PR is not updated for 1d25h17m9s. Please, either resolve the conflicts, or close it to finish the backport process of #65505

**Comment by robot-ch-test-poll4** [comment]
Dear @KochetovNicolai, @jkartseva, the PR is not updated for 1d24h46m40s. Please, either resolve the conflicts, or close it to finish the backport process of #65505

**Comment by robot-ch-test-poll4** [comment]
Dear @KochetovNicolai, @jkartseva, the PR is not updated for 1d24h10m34s. Please, either resolve the conflicts, or close it to finish the backport process of #65505

**Comment by robot-ch-test-poll1** [comment]
Dear @KochetovNicolai, @jkartseva, the PR is not updated for 1d24h37m11s. Please, either resolve the conflicts, or close it to finish the backport process of #65505

**Comment by robot-ch-test-poll1** [comment]
Dear @KochetovNicolai, @jkartseva, the PR is not updated for 1d24h3m6s. Please, either resolve the conflicts, or close it to finish the backport process of #65505

**Comment by robot-ch-test-poll2** [comment]
Dear @KochetovNicolai, @jkartseva, the PR is not updated for 1d24h58m8s. Please, either resolve the conflicts, or close it to finish the backport process of #65505

**Comment by robot-clickhouse-ci-2** [comment]
Dear @KochetovNicolai, @jkartseva, the PR is not updated for 1d24h55m35s. Please, either resolve the conflicts, or close it to finish the backport process of #65505

**Comment by robot-clickhouse** [comment]
Dear @KochetovNicolai, @jkartseva, the PR is not updated for 1d24h1m42s. Please, either resolve the conflicts, or close it to finish the backport process of #65505

**Comment by robot-ch-test-poll1** [comment]
Dear @KochetovNicolai, @jkartseva, the PR is not updated for 1d24h58m15s. Please, either resolve the conflicts, or close it to finish the backport process of #65505

**Comment by robot-ch-test-poll3** [comment]
Dear @KochetovNicolai, @jkartseva, the PR is not updated for 1d24h1m30s. Please, either resolve the conflicts, or close it to finish the backport process of #65505

**Comment by robot-ch-test-poll1** [comment]
Dear @KochetovNicolai, @jkartseva, the PR is not updated for 1d25h0m0s. Please, either resolve the conflicts, or close it to finish the backport process of #65505

**Comment by robot-ch-test-poll** [comment]
Dear @KochetovNicolai, @jkartseva, the PR is not updated for 1d24h58m30s. Please, either resolve the conflicts, or close it to finish the backport process of #65505

**Comment by robot-clickhouse** [comment]
Dear @KochetovNicolai, @jkartseva, the PR is not updated for 1d24h1m56s. Please, either resolve the conflicts, or close it to finish the backport process of #65505

**Comment by robot-ch-test-poll1** [comment]
Dear @KochetovNicolai, @jkartseva, the PR is not updated for 1d24h1m4s. Please, either resolve the conflicts, or close it to finish the backport process of #65505

**Comment by robot-clickhouse-ci-2** [comment]
Dear @KochetovNicolai, @jkartseva, the PR is not updated for 1d24h58m35s. Please, either resolve the conflicts, or close it to finish the backport process of #65505

**Comment by robot-ch-test-poll1** [comment]
Dear @KochetovNicolai, @jkartseva, the PR is not updated for 1d24h58m58s. Please, either resolve the conflicts, or close it to finish the backport process of #65505

**Comment by robot-ch-test-poll3** [comment]
Dear @KochetovNicolai, @jkartseva, the PR is not updated for 1d24h0m48s. Please, either resolve the conflicts, or close it to finish the backport process of #65505

**Comment by robot-clickhouse-ci-2** [comment]
Dear @KochetovNicolai, @jkartseva, the PR is not updated for 1d24h18m14s. Please, either resolve the conflicts, or close it to finish the backport process of #65505

**Comment by robot-clickhouse** [comment]
Dear @KochetovNicolai, @jkartseva, the PR is not updated for 1d24h59m41s. Please, either resolve the conflicts, or close it to finish the backport process of #65505

**Comment by robot-clickhouse-ci-2** [comment]
Dear @KochetovNicolai, @jkartseva, the PR is not updated for 1d24h58m5s. Please, either resolve the conflicts, or close it to finish the backport process of #65505

**Comment by robot-clickhouse-ci-1** [comment]
Dear @KochetovNicolai, @jkartseva, the PR is not updated for 1d25h0m21s. Please, either resolve the conflicts, or close it to finish the backport process of #65505

**Comment by robot-clickhouse-ci-2** [comment]
Dear @KochetovNicolai, @jkartseva, the PR is not updated for 1d24h0m7s. Please, either resolve the conflicts, or close it to finish the backport process of #65505

**Comment by robot-ch-test-poll4** [comment]
Dear @KochetovNicolai, @jkartseva, the PR is not updated for 1d24h4m46s. Please, either resolve the conflicts, or close it to finish the backport process of #65505

**Comment by robot-ch-test-poll** [comment]
Dear @KochetovNicolai, @jkartseva, the PR is not updated for 1d24h3m9s. Please, either resolve the conflicts, or close it to finish the backport process of #65505

**Comment by robot-ch-test-poll4** [comment]
Dear @KochetovNicolai, @jkartseva, the PR is not updated for 1d24h49m35s. Please, either resolve the conflicts, or close it to finish the backport process of #65505

**Comment by robot-clickhouse** [comment]
Dear @KochetovNicolai, @jkartseva, the PR is not updated for 1d24h0m43s. Please, either resolve the conflicts, or close it to finish the backport process of #65505

**Comment by robot-ch-test-poll3** [comment]
Dear @KochetovNicolai, @jkartseva, the PR is not updated for 1d24h59m21s. Please, either resolve the conflicts, or close it to finish the backport process of #65505

**Comment by robot-ch-test-poll2** [comment]
Dear @KochetovNicolai, @jkartseva, the PR is not updated for 1d25h3m9s. Please, either resolve the conflicts, or close it to finish the backport process of #65505

**Comment by robot-ch-test-poll1** [comment]
Dear @KochetovNicolai, @jkartseva, the PR is not updated for 1d24h2m43s. Please, either resolve the conflicts, or close it to finish the backport process of #65505

**Comment by robot-ch-test-poll3** [comment]
Dear @KochetovNicolai, @jkartseva, the PR is not updated for 1d24h56m22s. Please, either resolve the conflicts, or close it to finish the backport process of #65505

**Comment by robot-ch-test-poll3** [comment]
Dear @KochetovNicolai, @jkartseva, the PR is not updated for 1d24h58m55s. Please, either resolve the conflicts, or close it to finish the backport process of #65505

**Comment by robot-ch-test-poll3** [comment]
Dear @KochetovNicolai, @jkartseva, the PR is not updated for 1d24h0m9s. Please, either resolve the conflicts, or close it to finish the backport process of #65505

**Comment by robot-ch-test-poll4** [comment]
Dear @KochetovNicolai, @jkartseva, the PR is not updated for 1d25h0m51s. Please, either resolve the conflicts, or close it to finish the backport process of #65505

**Comment by robot-clickhouse-ci-1** [comment]
Dear @KochetovNicolai, @jkartseva, the PR is not updated for 1d25h0m19s. Please, either resolve the conflicts, or close it to finish the backport process of #65505

**Pull request closed without merging**
