### PR TITLE
Extend `Interval` support with unary and binary operations

### PR DESCRIPTION
**Pull request by kothiga**
### Changelog category (leave one):
- New Feature

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Introduced a new function for finding the difference between two DateTime64 objects. Expanded binary operations between Interval datatypes to include division and modulo. 

### Documentation entry for user-facing changes

This PR reworks the interval datatype to support date time difference operations. For example 

``` sql
select dateTime64Diff(toDateTime64('2022-11-23 09:26:37.123456789', 9), toDateTime64('2022-01-01', 0)); --> 28200397123456789
select dateTime64Diff(toDateTime64('2022-01-01', 0), toDateTime64('2022-11-23 09:26:37.123456789', 9)); --> -28200397123456789
```

we can find the difference between two `DateTime64` objects to arrive at the interval (represented in nanoseconds) between them. 

Various binary operations have been implemented for the interval datatype (see `02455_interval.sql` for the complete listing). Now, operations such as the following will execute as follows

``` sql
select (toIntervalNanosecond(2500) / toIntervalNanosecond(1000)) as i, toTypeName(i); --> 2.5	Nullable(Float64)
select (toIntervalNanosecond(2500) % toIntervalNanosecond(1000)) as i, toTypeName(i); --> 500	Nullable(IntervalNanosecond)
select toIntervalNanosecond(1000) / 0; --> \N
select toIntervalNanosecond(1000) / toIntervalNanosecond(0); --> inf
select intDiv(toIntervalNanosecond(2500), toIntervalNanosecond(1000)) as i, toTypeName(i); --> 2	Nullable(Int64)
select intDivOrZero(toIntervalNanosecond(2500), toIntervalNanosecond(0)) as i, toTypeName(i); --> 0	Nullable(Int64)
select moduloOrZero(toIntervalNanosecond(2500), toIntervalNanosecond(0)) as i, toTypeName(i); --> 0	Nullable(IntervalNanosecond)
```

As well, the following unary and conversion operations have been implemented for the interval datatype

``` sql
select -toIntervalNanosecond(1000) as i, toTypeName(i); --> -1000	IntervalNanosecond
select sign(toIntervalNanosecond(-1000)) as i, toTypeName(i); --> -1	Int8
select toFloat64(toIntervalNanosecond(1000)); --> 1000
select toInt64(toIntervalNanosecond(1000)); --> 1000
```

While modifying various function implementations, we adjusted the static Booleans to be a standard 

``` cpp
static constexpr bool
```

form, as the usage of `const constexpr` and `constexpr const` are redundant. If this is in fact necessary or unwanted, we can revert those changes.

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by yariks5s** [comment]
Ref. #56738

**Comment by jkartseva** [comment]
Hello,
New features require documentation, please update [date-time-functions.md](https://github.com/ClickHouse/ClickHouse/blob/master/docs/en/sql-reference/functions/date-time-functions.md).
Checking for documentation for new features occurs very early in the test workflow, so there is no point in approving the run without it.

**Comment by kothiga** [comment]
> Hello, New features require documentation, please update [date-time-functions.md](https://github.com/ClickHouse/ClickHouse/blob/master/docs/en/sql-reference/functions/date-time-functions.md). Checking for documentation for new features occurs very early in the test workflow, so there is no point in approving the run without it.

No problem. Documentation added 😁

**Comment by robot-ch-test-poll4** [comment]
*This is an automated comment for commit 7b3a26a97099f1d2fc8da9fb6323903495e63cb3 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/59123/7b3a26a97099f1d2fc8da9fb6323903495e63cb3/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td><a href="https://github.com/ClickHouse/ClickHouse/actions/runs/7672009456/job/20913052471">✅ success</a></td></tr>
<tbody>
</table>
</details>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/59123/7b3a26a97099f1d2fc8da9fb6323903495e63cb3/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Comment by jkartseva** [comment]
Why `dateDiff` doesn't work for this purpose?

``` sql
SELECT dateDiff('microseconds', toDateTime64('2023-12-31', 3, 'UTC'), toDateTime64('2024-01-01', 3, 'America/Los_Angeles'))
```

```
┌─dateDiff('microseconds', toDateTime64('2023-12-31', 3, 'UTC'), toDateTime64('2024-01-01', 3, 'America/Los_Angeles'))─┐
│                                                                                                         115200000000 │
└──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
```

**Comment by kothiga** [comment]
Hi @jkartseva , apologies for the delay in resolving the broken tests. I am now back working on this.

> Why `dateDiff` doesn't work for this purpose?

> Also, what would be the need for nanosecond units?

Nanoseconds are a useful datatype for storing processing speeds and data transfer rates. Currently, `dateDiff` doesn't support nanoseconds, however, I can look to expand the existing implementation to support this and remove the `dateTime64Diff` implementation.

**Comment by jkartseva** [comment]
@kothiga

System timers are based on jiffies, and the number of jiffies in seconds is typically within 100 to 1000, depending on the platform.
 E.g., on my platform:
```
$ grep 'CONFIG_HZ=' /boot/config-$(uname -r)
CONFIG_HZ=250
```
In other words, the time between system timer interrupts is in the order of milliseconds.

Precision down to nanoseconds would probably make sense if the ClickHouse stack operated solely in kernel space... 

In user space though, ns units would fall within a margin of error. Modern latency numbers, for reference: https://colin-scott.github.io/personal_website/research/interactive_latency.html

Sorry, I don't see a practical need for this PR since microseconds and larger units are already covered by the `dateDiff` function.

**Comment by kothiga** [comment]
Sorry, maybe I can better clarify what the primary purpose of this PR is. This change has less to do with the addition of `dateTime64Diff` and more with the rework and extension of the `Interval` data types. Here, we expand the available unary and binary operations for `Interval`.

As well, the benefit of extending `dateDiff` to nanoseconds is supporting operations between operands of type `DateTime64` down to the nanosecond-level in case of `DateTime64(9)`. This is to say, that it's less about measuring things in nanoseconds, and instead about storing arbitrary data as `DateTime64`.

I have updated the title of the PR to better reflect this, and as mentioned before, can work towards removing `dateTime64Diff` in favor of the singular `dateDiff` that supports nanoseconds.

**Comment by alexey-milovidov** [comment]
`dateDiff` with nanosecond interval makes sense.
I see no need to introduce another function, `dateTime64Diff`.

Nanosecond intervals make sense for compatibility and convenience.
It is possible to get nanosecond-precision values from external data sources,
it is also possible to measure the time with the precision of tens of ns and use it in computations.

Extended arithmetic operations on intervals make sense.

**Comment by kothiga** [comment]
Hi @jkartseva, sorry for the delays. I am going to close this PR to maintain it as a reference and instead open separate PRs that are more focused. The first of which is https://github.com/ClickHouse/ClickHouse/pull/61409 and focuses on the discussed implementation of extending `dateDiff` to support nanoseconds.

The reason for separating this is I need some time to reevaluate the rework to the interval data type, as there are various incompatibilities with the use of nullable in various contexts.

**Pull request closed without merging**
