### PR TITLE
Do not use clickhouse-test.deb in stateless CI checks

### PR DESCRIPTION
**Pull request by qoega**
Changelog category (leave one):
- Build/Testing/Packaging Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
clickhouse-test.deb is not used in stateless CI checks.

Repo is checked out anyway and it is easier to use repo locally and not support this deb packages in CI.

> Information about CI checks: https://clickhouse.tech/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
Let's also remove `clickhouse-test` package altogether,
because I don't really like debian packages.

**Comment by qoega** [comment]
@MergifyIo update

**Comment by qoega** [comment]
> Let's also remove `clickhouse-test` package altogether,
It is the next step. And stateful tests.

**Comment by qoega** [comment]
@mergifyio update

**Pull request merged**
