### PR TITLE
Fix join on tuple with NULLs

### LINKED ISSUE #67493: LEFT SEMI JOIN doesn't work with tuple(NULL) = tuple(NULL)
**Describe what's wrong**

Difference in behavior with new analyzer + SEMI JOIN + tuple(NULL) = tuple(NULL)

```
SELECT '============WRONG';

SELECT a.key FROM (SELECT NULL AS key UNION ALL SELECT '1' as key) as a LEFT SEMI JOIN (SELECT NULL AS key UNION ALL SELECT '1' as key) as b ON tuple(a.key) = tuple(b.key) SETTINGS allow_experimental_analyzer=1;

┌─key─┐
│ 1   │
└─────┘

SELECT '============CORRECT WITH IS NOT DISTINCT FROM';

SELECT a.key FROM (SELECT NULL AS key UNION ALL SELECT '1' as key) as a LEFT SEMI JOIN (SELECT NULL AS key UNION ALL SELECT '1' as key) as b ON a.key IS NOT DISTINCT FROM b.key  SETTINGS allow_experimental_analyzer=1;

┌─key──┐
│ ᴺᵁᴸᴸ │
└──────┘
┌─key─┐
│ 1   │
└─────┘

SELECT '============CORRECT WITHOUT ANALYZER';
SELECT a.key FROM (SELECT NULL AS key UNION ALL SELECT '1' as key) as a LEFT SEMI JOIN (SELECT NULL AS key UNION ALL SELECT '1' as key) as b ON tuple(a.key) = tuple(b.key) SETTINGS allow_experimental_analyzer=0;

┌─key──┐
│ ᴺᵁᴸᴸ │
└──────┘
┌─key─┐
│ 1   │
└─────┘

SELECT '============CORRECT WITH LEFT ANY JOIN';
SELECT a.key FROM (SELECT NULL AS key UNION ALL SELECT '1' as key) as a LEFT ANY JOIN (SELECT NULL AS key UNION ALL SELECT '1' as key) as b ON tuple(a.key) = tuple(b.key) SETTINGS allow_experimental_analyzer=1;

┌─key──┐
│ ᴺᵁᴸᴸ │
└──────┘
┌─key─┐
│ 1   │
└─────┘
```
https://fiddle.clickhouse.com/eb997e30-f01c-4035-99dd-c8f91a3503e8

**Does it reproduce on the most recent release?**

Yes

@vdimir, do you have any idea? AFAIK behavior should match as isNotDistinctFrom is implemented via tuples
https://github.com/ClickHouse/ClickHouse/pull/53755#issuecomment-1717623464

### PR DESCRIPTION
**Pull request by vdimir**
### Changelog category (leave one):

- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
* Fix join on tuple with NULLs: Some queries with the new analyzer and `NULL` inside the tuple in the `JOIN ON` section returned incorrect results.

Close https://github.com/ClickHouse/ClickHouse/issues/67493

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-ch-test-poll** [comment]
*This is an automated comment for commit c4d1d52f87152fbfb47cd14ebb62a277fa54d7b1 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/67538/c4d1d52f87152fbfb47cd14ebb62a277fa54d7b1/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/363988206511c75777f77178cde566e027db373b/docs_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Review by evillique — APPROVED** [review]

**Comment by vdimir** [comment]
> Integration tests (asan, old analyzer) [5/6] — fail: 4, passed: 611 [Details](https://s3.amazonaws.com/clickhouse-test-reports/67538/59e51de6f8df35a0df0e08e8b3aacd3ba40c4cbd/integration_tests__asan__old_analyzer__[5_6].html)

https://github.com/ClickHouse/ClickHouse/pull/67035#issuecomment-2261571340

**Comment by vdimir** [comment]
> Upgrade check (debug) — Changed settings are not reflected in settings changes history (see changed_settings.txt) [Details](https://s3.amazonaws.com/clickhouse-test-reports/67538/dafddd9def63b11053d0071c6d2527880195370e/upgrade_check__debug_.html)

Upgrade check is fixed on master

**Comment by vdimir** [comment]
> AST fuzzer (ubsan) — Logical error: 'Expected the argument №7 ('toLowCardinality(materialize(32_UInt8))' of type UInt8) to have 0 rows, but it has 1'. [Details](https://s3.amazonaws.com/clickhouse-test-reports/67538/b39392fc15d8f48aa855f2e3ac730448e4514507/ast_fuzzer__ubsan_.html)

https://github.com/ClickHouse/ClickHouse/issues/67330

> Upgrade check (debug) — Changed settings are not reflected in settings changes history (see changed_settings.txt [Details](https://s3.amazonaws.com/clickhouse-test-reports/67538/b39392fc15d8f48aa855f2e3ac730448e4514507/upgrade_check__debug_.html)

https://github.com/ClickHouse/ClickHouse/pull/67524

> Performance Comparison (release) [1/4] — Failed to parse the report. [Details](https://s3.amazonaws.com/clickhouse-test-reports/67538/b39392fc15d8f48aa855f2e3ac730448e4514507/performance_comparison__release__[1_4].html)

Server even haven't started with 

<details>
<summary>Details</summary>

```
2024.08.02 14:35:42.122220 [ 1171 ] {} <Error> Application: Caught exception while loading metadata: Code: 33. DB::Exception: Cannot read all data. Bytes read: 0. Bytes expected: 4.
: While checking access for disk backups: Cannot parse definition from metadata file /workspace/right/db/store/cb7/cb71667d-b5b3-478b-9d61-6449b768f5b7/trace_log.sql. (CANNOT_READ_A
LL_DATA), Stack trace (when copying this message, always include the lines below):

0. ./build_docker/./src/Common/Exception.cpp:111: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000d7a485b
1. DB::Exception::Exception(PreformattedMessage&&, int) @ 0x0000000007b60fac
2. DB::Exception::Exception<unsigned long&, String>(int, FormatStringHelperImpl<std::type_identity<unsigned long&>::type, std::type_identity<String>::type>, unsigned long&, String&&
) @ 0x0000000007e3dd8b
3. DB::ReadBuffer::readStrict(char*, unsigned long) @ 0x0000000007e3dce9
4. ./contrib/llvm-project/libcxx/include/string:1499: DB::IDisk::checkAccessImpl(String const&) @ 0x0000000010fc598c
5. ./build_docker/./src/Disks/DiskLocal.cpp:0: DB::DiskLocal::checkAccessImpl(String const&) @ 0x0000000010fb4796
6. ./contrib/llvm-project/libcxx/include/string:1499: DB::IDisk::startup(std::shared_ptr<DB::Context const>, bool) @ 0x0000000010fc4e6d
7. ./contrib/llvm-project/libcxx/include/string:1499: std::shared_ptr<DB::IDisk> std::__function::__policy_invoker<std::shared_ptr<DB::IDisk> (String const&, Poco::Util::AbstractCon
figuration const&, String const&, std::shared_ptr<DB::Context const>, std::map<String, std::shared_ptr<DB::IDisk>, std::less<String>, std::allocator<std::pair<String const, std::sha
red_ptr<DB::IDisk>>>> const&, bool, bool)>::__call_impl<std::__function::__default_alloc_func<DB::registerDiskLocal(DB::DiskFactory&, bool)::$_0, std::shared_ptr<DB::IDisk> (String 
const&, Poco::Util::AbstractConfiguration const&, String const&, std::shared_ptr<DB::Context const>, std::map<String, std::shared_ptr<DB::IDisk>, std::less<String>, std::allocator<s
td::pair<String const, std::shared_ptr<DB::IDisk>>>> const&, bool, bool)>>(std::__function::__policy_storage const*, String const&, Poco::Util::AbstractConfiguration const&, String 
const&, std::shared_ptr<DB::Context const>&&, std::map<String, std::shared_ptr<DB::IDisk>, std::less<String>, std::allocator<std::pair<String const, std::shared_ptr<DB::IDisk>>>> co
nst&, bool, bool) (.llvm.3071567665338546219) @ 0x0000000010fb9d7a
8. ./contrib/llvm-project/libcxx/include/__functional/function.h:0: ? @ 0x0000000010fbb071
9. ./build_docker/./src/Disks/DiskSelector.cpp:57: DB::DiskSelector::initialize(Poco::Util::AbstractConfiguration const&, String const&, std::shared_ptr<DB::Context const>, std::fun
ction<bool (Poco::Util::AbstractConfiguration const&, String const&, String const&)>) @ 0x0000000010fbe7df
10. ./contrib/llvm-project/libcxx/include/__functional/function.h:818: ? @ 0x0000000011135afd
11. ./build_docker/./src/Interpreters/Context.cpp:4485: DB::Context::getStoragePolicySelector(std::lock_guard<std::mutex>&) const @ 0x0000000011114342
12. ./build_docker/./src/Interpreters/Context.cpp:4418: DB::Context::getStoragePolicy(String const&) const @ 0x00000000111360eb
13. ./build_docker/./src/Databases/DatabaseOrdinary.cpp:147: DB::DatabaseOrdinary::convertMergeTreeToReplicatedIfNeeded(std::shared_ptr<DB::IAST>, DB::QualifiedTableName const&, String const&) @ 0x0000000010e4219d
14. ./build_docker/./src/Databases/DatabaseOrdinary.cpp:0: void std::__function::__policy_invoker<void (String const&)>::__call_impl<std::__function::__default_alloc_func<DB::DatabaseOrdinary::loadTablesMetadata(std::shared_ptr<DB::Context const>, DB::ParsedTablesMetadata&, bool)::$_0, void (String const&)>>(std::__function::__policy_storage const*, String const&) @ 0x0000000010e4c6a9
15. ./contrib/llvm-project/libcxx/include/__iterator/wrap_iter.h:100: void std::__function::__policy_invoker<void ()>::__call_impl<std::__function::__default_alloc_func<DB::DatabaseOnDisk::iterateMetadataFiles(std::shared_ptr<DB::Context const>, std::function<void (String const&)> const&) const::$_1, void ()>>(std::__function::__policy_storage const*) @ 0x0000000010e2eaaa
16. ./base/base/../base/wide_integer_impl.h:817: ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::worker(std::__list_iterator<ThreadFromGlobalPoolImpl<false, true>, void*>) @ 0x000000000d862549
17. ./build_docker/./src/Common/ThreadPool.cpp:0: void std::__function::__policy_invoker<void ()>::__call_impl<std::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<false, true>::ThreadFromGlobalPoolImpl<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>(void&&)::'lambda'(), void ()>>(std::__function::__policy_storage const*) @ 0x000000000d866691
18. ./base/base/../base/wide_integer_impl.h:817: void* std::__thread_proxy[abi:v15007]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void ThreadPoolImpl<std::thread>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>>(void*) @ 0x000000000d865409
19. ? @ 0x00007fedafb1fac3
20. ? @ 0x00007fedafbb1850
 (version 24.8.1.1022)
```

</details>

**Pull request merged**
