### PR TITLE
Consistent AWS timeouts

### PR DESCRIPTION
**Pull request by excitoon**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Fixed a bug with unlimited wait for auxiliary AWS requests.

### CODE REVIEW

**Comment by excitoon** [comment]
Related: #21852

**Comment by excitoon** [comment]
Failed tests are unrelated.

**Review by nikitamikhaylov — CHANGES_REQUESTED** [review]
BTW, where was the bug? And why these changes fix it?

**Comment by excitoon** [comment]
@nikitamikhaylov the bug was in few places (not sure if I found every one), for example in `S3CredentialsProviderChain`:
```
                /// EC2MetadataService throttles by delaying the response so the service client should set a large read timeout.
                /// EC2MetadataService delay is in order of seconds so it only make sense to retry after a couple of seconds.
                aws_client_configuration.connectTimeoutMs = 1000;
                aws_client_configuration.requestTimeoutMs = 1000;
                aws_client_configuration.retryStrategy = std::make_shared<Aws::Client::DefaultRetryStrategy>(1, 1000);

                auto ec2_metadata_client = std::make_shared<Aws::Internal::EC2MetadataClient>(aws_client_configuration);
                auto config_loader = std::make_shared<Aws::Config::EC2InstanceProfileConfigLoader>(ec2_metadata_client);

                AddProvider(std::make_shared<Aws::Auth::InstanceProfileCredentialsProvider>(config_loader));
                LOG_INFO(logger, "Added EC2 metadata service credentials provider to the provider chain.");
```

It uses "default" parameters to set timeouts.

Also, in `Aws::Internal::MakeDefaultHttpResourceClientConfiguration()` (this code shall not be used right now):
```
            // EC2MetadataService throttles by delaying the response so the service client should set a large read timeout.
            // EC2MetadataService delay is in order of seconds so it only make sense to retry after a couple of seconds.
            res.connectTimeoutMs = 1000;
            res.requestTimeoutMs = 1000;
            res.retryStrategy = Aws::MakeShared<DefaultRetryStrategy>(RESOURCE_CLIENT_CONFIGURATION_ALLOCATION_TAG, 1, 1000);

            return res;
```

**Review by nikitamikhaylov — APPROVED** [review]

**Pull request merged**
