### PR TITLE
`ALTER TABLE ... MATERIALIZE COLUMN`

### PR DESCRIPTION
**Pull request by excitoon**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- New Feature

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
ALTER TABLE ... MATERIALIZE COLUMN.

Progress on #18187

### CODE REVIEW

**Comment by excitoon** [comment]
It is not that easy to skip rewriting column if there is no value

**Comment by excitoon** [comment]
I think it is nearly impossible.

**Comment by alesapin** [comment]
> I think it is nearly impossible.

But why? Just add one more check to `isStorageTouchedByMutations`?

**Comment by excitoon** [comment]
Yeah, totally!

**Comment by excitoon** [comment]
@filimonov @alesapin We may want to have possibility to re-materialize column, even if it partially materialized.

What about:
```
MATERIALIZE COLUMN xxx FORCE
```
?

**Comment by filimonov** [comment]
> @filimonov @alesapin We may want to have possibility to re-materialize column, even if it is partially materialized.

Yes, I can imagine some scenarios for that. 

> What about:
> 
> ```
> MATERIALIZE COLUMN xxx FORCE
> ```
> 
> ?

I'm not the best at naming things, but ok for me :)

From English-grammar POV it should be 'forcibly', but 'force' is simpler. One more option is to create smth like `REMATERIALIZE COLUMN xxx`.

**Comment by excitoon** [comment]
Or existing `FINAL`

**Comment by alexey-milovidov** [comment]
Need to fix PVS-Studio report.

**Comment by excitoon** [comment]
@alesapin Because `isStorageByMutation` receives list of commands, and another command can invalidate the result (making it `true`). I'm heading towards separate `FINAL` functionality to another PR now.

**Comment by excitoon** [comment]
@Mergifybot rebase

**Comment by excitoon** [comment]
@Mergifyio rebase

**Comment by excitoon** [comment]
@Mergifyio rebase

**Comment by excitoon** [comment]
@alexey-milovidov @alesapin Can someone of you step in as a reviewer?

**Review by alesapin — APPROVED** [review]

**Comment by alesapin** [comment]
Ok, should work as expected.

**Comment by gyuton** [comment]
Internal documentation ticket: DOCSUP-14538.

**Pull request merged**
