### PR TITLE
Feature/mask mysql db engine password

### PR DESCRIPTION
**Pull request by TCeason**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Mask MySQL Database Engine's password when execute `SHOW CREATE DATABASE/TABLE`.

### CODE REVIEW

**Comment by tavplubix** [comment]
Looks like a particular case of #23424

**Comment by TCeason** [comment]
> Looks like a particular case of #23424

Yes, I see it. But I think if not config in xml, the password should also be mask.

**Comment by TCeason** [comment]
I see this pr #23424 is closed. So how can we do next? @tavplubix Could you review this or maybe I can make a patch to mine repo?

**Comment by tavplubix** [comment]
Generic solution will be implemented in scope of #28367

**Comment by TCeason** [comment]
> Generic solution will be implemented in scope of #28367

👍🏻

**Comment by alexey-milovidov** [comment]
What to do with this PR?

Two options:
- close;
- extend this to table engines, including PostgreSQL and MongoDB and also dictionaries from MySQL, PostgreSQL, MongoDB and Redis and Cassandra.

**Pull request closed without merging**
