### PR TITLE
Fix `CREATE TABLE AS` query with default expression

### LINKED ISSUE #64385: Modifying column with default expression in copied table (using AS) affects source table
**Describe the unexpected behaviour**

Basically the flow:

- creating a new table with a default expression using CREATE TABLE AS from another table
- renaming the columns in the new table with DEFAULT expression modifies the DEFAULT expression in old table and INSERT fails

**How to reproduce**
https://fiddle.clickhouse.com/9d48b670-e2b6-4f53-9e8e-6153023bd88c

```
create table src_table (
    _time DateTime default fromUnixTimestamp(sipTimestamp)
  , sipTimestamp UInt64
)
engine = MergeTree
order by _time
;

insert into src_table(sipTimestamp) select toUnixTimestamp(toDateTime('2024-05-20 09:00:00'));

create table copied_table as src_table;

alter table copied_table
    rename column `sipTimestamp` to `timestamp`
;

select '----------------------------------------';
select '---- "show create table" shows no change';
show create table src_table format TabSeparatedRaw;
select '----------------------------------------';
select '---- "system.columns" shows default was modified in src table and it should not, only in copied_table';
select name, default_expression from system.columns where table = 'src_table' format PrettyCompactMonoBlock;
select '----------------------------------------';
select '---- insert fails because "_time" default expression has changed';
insert into src_table(sipTimestamp) select toUnixTimestamp(toDateTime('2024-05-20 09:00:00'));

Missing columns: 'timestamp' while processing query: '_CAST(fromUnixTimestamp(timestamp), 'DateTime') AS _time', required columns: 'timestamp' 'timestamp'. (UNKNOWN_IDENTIFIER)
(query: insert into src_table(sipTimestamp) select toUnixTimestamp(toDateTime('2024-05-20 09:00:00'));)

```

* Which ClickHouse server version to use

Tested in latest

**Expected behavior**
Insert should work

**Error message and/or stacktrace**
```
Missing columns: 'timestamp' while processing query: '_CAST(fromUnixTimestamp(timestamp), 'DateTime') AS _time', required columns: 'timestamp' 'timestamp'. (UNKNOWN_IDENTIFIER)
(query: insert into src_table(sipTimestamp) select toUnixTimestamp(toDateTime('2024-05-20 09:00:00'));)
```

### PR DESCRIPTION
**Pull request by CurtizJ**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fixed `CREATE TABLE AS` queries for tables with default expressions.

Fixes #64385.

<details>
    <summary>CI Settings</summary>

**NOTE:** If your merge the PR with modified CI you **MUST KNOW** what you are doing
**NOTE:** Checked options will be applied if set before CI RunConfig/PrepareRunConfig step
- [ ]  Allow: Integration Tests
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Unit tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All with aarch64
- [ ]  Allow: All with ASAN
- [ ]  Allow: All with TSAN
- [ ]  Allow: All with Analyzer
- [ ]  Allow: All with Azure
- [ ]  Allow: Add your option here
---
- [ ]  Exclude: Fast test
- [ ]  Exclude: Integration Tests
- [ ]  Exclude: Stateless tests
- [ ]  Exclude: Stateful tests
- [ ]  Exclude: Performance tests
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN
- [ ]  Exclude: All with MSAN
- [ ]  Exclude: All with UBSAN
- [ ]  Exclude: All with Coverage
- [ ]  Exclude: All with Aarch64
---
- [ ]  do not test (only style check)
- [ ]  disable merge-commit (no merge from master before tests)
- [ ]  disable CI cache (job reuse)
- [ ]  allow: batch 1 for multi-batch jobs
- [ ]  allow: batch 2
- [ ]  allow: batch 3
- [ ]  allow: batch 4, 5 and 6
</details>

### CODE REVIEW

**Comment by robot-ch-test-poll** [comment]
*This is an automated comment for commit a0e820e7f4ff00295be69e7e26f612838e1a95fa with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/64455/a0e820e7f4ff00295be69e7e26f612838e1a95fa/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>A Sync</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>⏳ pending</td></tr>
<tbody>
</table>
<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

**Review by SmitaRKulkarni — APPROVED** [review]
LGTM

**Comment by SmitaRKulkarni** [comment]
Unrelated fail in fast test, looks like its fixed in master

**Comment by CurtizJ** [comment]
The failure of test was related.

**Comment by lesandie** [comment]
Hi! Is it going to be backported to 24.3 LTS?

**Comment by CurtizJ** [comment]
@lesandie

Yes, it will be backported.

**Pull request merged**
