### PR TITLE
clickhouse-copier add check drop partition

### PR DESCRIPTION
**Pull request by sunny19930321**
Changelog category (leave one):
- Not For Changelog

Description:
check clickhouse-copier all shard drop partition are  successfully executed

### CODE REVIEW

**Comment by nikitamikhaylov** [comment]
@Mergifyio update

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
The logic looks correct.

There is no test for this change, but it will be challenging to write - we can skip it.

**Comment by robot-ch-test-poll1** [comment]
This is an automated comment for commit 67e355558eb659b8ebeca1601c7c55e418b91d06 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/35263/67e355558eb659b8ebeca1601c7c55e418b91d06/ci_running.html)
The overall status of the commit is 🔴 failure

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🔴 failure</td></tr>
<tr><td>Docs Check</td><td>Builds and tests the documentation</td><td>🟡 pending</td></tr>
</table>

**Comment by alexey-milovidov** [comment]
> New Feature
check clickhouse-copier all shard drop partition are successfully executed

This is not a new feature.

**Pull request merged**
