### PR TITLE
support construct map from {} expression

### PR DESCRIPTION
**Pull request by taiyang-li**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
I noticed that currently clickhouse doesn't support construct map column from `{}` expression. So I make this PR.

Detailed description / Documentation draft:
I noticed that currently clickhouse doesn't support construct map column from `{}` expression. So I make this PR.

### CODE REVIEW

**Comment by qoega** [comment]
Do you know if there are some standards or implementations in another SQL databases?

**Comment by taiyang-li** [comment]
> Do you know if there are some standards or implementations in another SQL databases?

@qoega Havn't refer to other SQL database implementations yet.  Just because in clickhouse you can construct array value from expression like `[1, 2, 3, 4]` ,  I think it maybe reasonable to construct a map value from expression like `{1: 2, 3: 4}`, which have the same style with many other languages like Python/C++/Go.

**Comment by taiyang-li** [comment]
Failed tests look like irrelevant to my changes.

**Comment by taiyang-li** [comment]
@alexey-milovidov Can you give me some advice about this PR?

**Comment by akuzm** [comment]
@CurtizJ do you remember what we decided about this syntax? I vaguely recall there was some conflict with the query parameters, and we decided to postpone it...

**Comment by CurtizJ** [comment]
Yes, there is conflict with syntax parametrized queries. 
Example: `$CLICKHOUSE_CLIENT --param_test 'Hello, world' --query 'SELECT {test:String}'`

**Comment by taiyang-li** [comment]
> Yes, there is conflict with syntax of parametrized queries.
> Example: `$CLICKHOUSE_CLIENT --param_test 'Hello, world' --query 'SELECT {test:String}'`

That is embarrassing, I didn't expect that...

**Comment by amosbird** [comment]
> > Yes, there is conflict with syntax of parametrized queries.
> > Example: `$CLICKHOUSE_CLIENT --param_test 'Hello, world' --query 'SELECT {test:String}'`
> 
> That is embarrassing, I didn't expect that...

I think this feature is still worth having. We can extend it a little bit to something like `select map{1:2, 3:4}` . It's syntactically better than `select map(1, 2, 3, 4)` and somehow more consistent with `insert into values ({1:2, 3:4)`

**Comment by alexey-milovidov** [comment]
Let's postpone it but keep it in mind.

**Pull request closed without merging**
