### PR TITLE
Fix CSV read while the end of line is CR(\r)

### PR DESCRIPTION
**Pull request by KevinyhZou**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
While read data from a csv format file, and at end of line is'\r' , which not followed by '\n', then we will enconter the exception as below
```
Cannot parse CSV format: found \r (CR) not followed by \n (LF). Line must end by \n (LF) or \r\n (CR LF) or \n\r.: 
```
In clickhouse, the csv end of line must be \n or \r\n or \n\r,  so the \r must be followed by \n , but in some suitation, the csv input data is abnormal, like above, \r is at end of line.

So I think we can improve csv reader by allow CR(\r) at end of line

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
Test needed.

**Comment by CheSema** [comment]
I do not follow the logic. Could you explain it a bit more?

What I understand from your explanation that the file has actually wrong format or simply file is broken. 
You are introducing one more flag to ignore such cases. However, that path is endless. Lets imagine that the file ends with the sequence '\rA'. Yes, just symbol 'A' after the '\r'. With your flag 'input_format_csv_crlf_end_of_line=true' such error would be just muted. I do not sure that it is ring here.

To better understand the cases and its combination, please, provide the tests set. Then we will see the example what is correct and what is not correct file with different flags.

**Comment by KevinyhZou** [comment]
Hello, the suitation is: the csv file has some abnormal data, which the end of line is \r, in clickhouse, the end of csv line should be \r\n or \n or \n\r,   so the exception throws when `skipEndOfLine`  as \r is not followed by \n.

So I want to make a config `input_format_csv_allow_cr_end_of_line`,  if encounter \r at the end when `skipEndOfLine`, the just take it as normal.  and  Unit tests is added.

Sorry for late reply, please help to have a reivew, thanks . @CheSema

**Comment by KevinyhZou** [comment]
cc @CheSema

**Comment by robot-ch-test-poll2** [comment]
*This is an automated comment for commit f64f475084c7af6770a9ee6acb9ecea72082d325 with description of existing statuses. It's updated for the latest CI running*

[❌ Click here](https://s3.amazonaws.com/clickhouse-test-reports/54340/f64f475084c7af6770a9ee6acb9ecea72082d325/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td><a href="https://github.com/ClickHouse/ClickHouse/actions/runs/6664360574">✅ success</a></td></tr>
<tbody>
</table>
</details>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/54340/f64f475084c7af6770a9ee6acb9ecea72082d325/ci_running.html">❌ failure</a></td></tr>
<tbody>
</table>

**Comment by KevinyhZou** [comment]
please add the `can be tested` label @CheSema

**Comment by KevinyhZou** [comment]
cc @CheSema

**Comment by CheSema** [comment]
02891_input_csv_cr_end_of_line failed
https://s3.amazonaws.com/clickhouse-test-reports/54340/91f17cc2683ee77770c27c9bb46533ba84abee48/fast_test.html

**Comment by KevinyhZou** [comment]
The failed case if fixed @CheSema

**Comment by CheSema** [comment]
Integration asan 
test_multiple_tables_streaming_sync - https://github.com/ClickHouse/ClickHouse/issues/55090

stateless debug
02152_http_external_tables_memory_tracking - https://github.com/ClickHouse/ClickHouse/issues/53215

stateles msan
01104_distributed_numbers_test - https://github.com/ClickHouse/ClickHouse/issues/56256

**Review by CheSema — APPROVED** [review]

**Comment by Avogar** [comment]
The changes from this PR are not enough to fully support `\r` at end of line for CSV format. There are 2 more places where we should check for the new setting and single `\r`:
1) In method `skipRow()` for correct fast count for such CSV files: 
https://github.com/ClickHouse/ClickHouse/blob/dc12111ed1b888cf7c25a47affc446d4a7a6fb1b/src/Processors/Formats/Impl/CSVRowInputFormat.cpp#L167-L175
2) In file segmentation engine for correct parallel parsing for such CSV files:
https://github.com/ClickHouse/ClickHouse/blob/dc12111ed1b888cf7c25a47affc446d4a7a6fb1b/src/Processors/Formats/Impl/CSVRowInputFormat.cpp#L561-L568

**Comment by KevinyhZou** [comment]
> The changes from this PR are not enough to fully support `\r` at end of line for CSV format. There are 2 more places where we should check for the new setting and single `\r`:
> 
> 1. In method `skipRow()` for correct fast count for such CSV files:
>    https://github.com/ClickHouse/ClickHouse/blob/dc12111ed1b888cf7c25a47affc446d4a7a6fb1b/src/Processors/Formats/Impl/CSVRowInputFormat.cpp#L167-L175
> 2. In file segmentation engine for correct parallel parsing for such CSV files:
>    https://github.com/ClickHouse/ClickHouse/blob/dc12111ed1b888cf7c25a47affc446d4a7a6fb1b/src/Processors/Formats/Impl/CSVRowInputFormat.cpp#L561-L568

OK, I will look into this. Thanks for remind

**Pull request merged**
