### PR TITLE
Release pull request for branch 21.8

### PR DESCRIPTION
**Pull request by robot-ch-test-poll**
This PullRequest is part of ClickHouse release cycle. It's used by CI system only. Don't perform any changes with it.

### CODE REVIEW

**Comment by vdimir** [comment]
Checks for [`3b2d037` (#26176)](https://github.com/ClickHouse/ClickHouse/pull/26176/commits/3b2d037411cfec5e868211bfd79a4cec0ff0a0e3):

> Integration tests (asan) — fail: 1, passed: 1542, flaky: 1 

* `test_cluster_copier/test.py::test_copy_with_recovering[True] - flaky in master

* `test_prometheus_endpoint/test.py::test_prometheus_endpoint` - https://github.com/ClickHouse/ClickHouse/pull/26140 not merged, __should merge?__

> Integration tests (release) — fail: 1, passed: 1542, flaky: 3 

* `test_MemoryTracking/test.py::test_tcp_multiple_sessions` - flaky in master

* __???__ `test_keeper_zookeeper_converter/test.py::test_multi_and_failed_requests` - only 2 failures in master during last week

* `test_library_bridge/test.py::test_load_ids` - flaky in master

* `test_storage_kafka/test.py::test_kafka_consumer_hang2` - flaky in master

**Comment by alexey-milovidov** [comment]
https://github.com/ClickHouse/ClickHouse/pull/26140

You can do manual backport. It is not necessarily for release.

**Comment by vitlibar** [comment]
Known problems with integration tests (e81d7e54fda0cfd4c82b516ab4186a320436c99e):
`test_library_bridge/test.py::test_load_ids` (fixed https://github.com/ClickHouse/ClickHouse/pull/27383)
`test_prometheus_endpoint/test.py::test_prometheus_endpoint` (fixed https://github.com/ClickHouse/ClickHouse/pull/26140)

**Comment by Felixoid** [comment]
We have a problem here with releasing for sure...

**Pull request closed without merging**
