### PR TITLE
Add -q option to curl requests to disable .curlrc use on developer servers

### PR DESCRIPTION
**Pull request by qoega**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Not for changelog

Detailed description / Documentation draft:

Add -q option to curl requests to disable .curlrc use on developer servers

By adding documentation, you'll allow users to try your new feature immediately, not when someone else will have time to document it later. Documentation is necessary for all features that affect user experience in any way. You can add brief documentation draft above, or add documentation right into your patch as Markdown files in [docs](https://github.com/ClickHouse/ClickHouse/tree/master/docs) folder.

If you are doing this for the first time, it's recommended to read the lightweight [Contributing to ClickHouse Documentation](https://github.com/ClickHouse/ClickHouse/tree/master/docs/README.md) guide first.

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
It can be embedded in `${CLICKHOUSE_CURL}`

**Comment by qoega** [comment]
I thought about it also, but is seems less explicit. If you think it is OK, I'll try.

**Comment by alexey-milovidov** [comment]
I think it's better. Don't have to always keep it in mind writing new tests.

**Comment by alexey-milovidov** [comment]
And I don't see any reason why any test wants to avoid the usage of this option.

**Comment by qoega** [comment]
rerun tests for ✅,  but previous one looks not related

**Review by alexey-milovidov — APPROVED** [review]

**Pull request merged**
