### PR TITLE
See impact of DISABLE_OMIT_FRAME_POINTER (take 2)

### PR DESCRIPTION
**Pull request by Algunenano**
### Changelog category (leave one):
- Build/Testing/Packaging Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
- Enable frame pointers

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

---
### Modify your CI run:
**NOTE:** If your merge the PR with modified CI you **MUST KNOW** what you are doing
**NOTE:** Checked options will be applied if set before CI RunConfig/PrepareRunConfig step

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Do not test
- [x]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [x]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-clickhouse** [comment]
*This is an automated comment for commit cdf9dcc0f5ac80b2b05b85ee70743d3c06620e88 with description of existing statuses. It's updated for the latest CI running*

[❌ Click here](https://s3.amazonaws.com/clickhouse-test-reports/62724/cdf9dcc0f5ac80b2b05b85ee70743d3c06620e88/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td><a href="https://github.com/ClickHouse/ClickHouse/blob/master/.github/PULL_REQUEST_TEMPLATE.md?plain=1">❌ failure</a></td></tr>
<tbody>
</table>

**Comment by alexey-milovidov** [comment]
Up to 40% slower.

**Comment by Algunenano** [comment]
I was talking with @serxa that we might want to look into the slower queries and try to understand why and see if we can address it somehow (maybe adding / removing inline directives or reorganizing the code). It would be great to enable frame pointers if we could reduce its performance impact to something acceptable.

**Comment by serxa** [comment]
Yes, I would like to help with this investigation

**Comment by Algunenano** [comment]
I expect https://github.com/ClickHouse/ClickHouse/pull/61661/ will help with the worse cases, as int_parsing will change from dozens of small functions to a large bigger one. I'll update this PR to re-evaluate once that's merged

**Comment by Algunenano** [comment]
In general it's 1-2% slower. But there are some corner cases where it's 40% slower, which is too much. I'll try to go into specific queries over 10% and see what can be done. I expect that the overhead might be related to having too many too small functions (so the frame pointer update happens too often).

**Comment by Algunenano** [comment]
Seems each case will be different. I suspect of the perf impact of `ImplementationSelector` for several of them (used in UUIDv4 or rand()). We could try removing these "adaptors" and always use dynamic dispatch. One less feature to support.

**Comment by alexey-milovidov** [comment]
Then how will you do optimization with Bayesian Bandits?

**Comment by Algunenano** [comment]
> Then how will you do optimization with Bayesian Bandits?

If we remove it and they become faster (without frame pointers), then we won't deal with bandits (as we don't deal with them in 99% of the code). We will instead dispatch directly to the fastest implementation (per benchmarks) every time.

**Comment by Algunenano** [comment]
WIP for rand():
  * Implemented an AVX512BW version (additional to the existing AVX2 version).
  * Removed the selector based on statistics in favor of dynamic dispatch based on arch support only
  * Pending: Verify randomness is equivalent in all 3 versions.
  * Pending: Verify perf diff with and without frame pointers after the changes.

**Comment by Algunenano** [comment]
> Pending: Verify randomness is equivalent in all 3 versions.
The test already did that for me and detected an issue.

> Pending: Verify perf diff with and without frame pointers after the changes.
Equivalent AFAICT.

New changes:
* Removed ImplementationSelector from generateUUID4 in favor of dynamic dispatch.
* Removed ImplementationSelector from FunctionHashing.h. As far as I could see, it was mostly useless. Using multitarget code when the heavy lifting is done by external functions (e.g `CityHash_v1_0_2::CityHash64`) is useless.

Let's see what some new perf runs say.

My current main concern is the mod (`%`) function. It seems there might be a higher impact of using frame pointers there because we use multiple calls indirections to get to the final function and those calls use memory (not just dispatching):
```
     DB::FunctionToExecutableFunctionAdaptor::executeImpl(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const                                                   ▒
     DB::FunctionBinaryArithmeticWithConstants<DB::ModuloImpl, DB::NameModulo, false, true, false>::executeImpl(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) co▒
     DB::FunctionBinaryArithmetic<DB::ModuloImpl, DB::NameModulo, false, true, false>::executeImpl(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const          ▒
     DB::FunctionBinaryArithmetic<DB::ModuloImpl, DB::NameModulo, false, true, false>::executeImpl2(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, DB::PODArray<c▒
     bool DB::FunctionBinaryArithmetic<DB::ModuloImpl, DB::NameModulo, false, true, false>::castType<DB::FunctionBinaryArithmetic<DB::ModuloImpl, DB::NameModulo, false, true, false>::castBothTypes<DB::FunctionBinaryArithmetic<DB::ModuloImpl, DB::NameModulo, false, true, false>::e▒
     bool DB::FunctionBinaryArithmetic<DB::ModuloImpl, DB::NameModulo, false, true, false>::castType<DB::FunctionBinaryArithmetic<DB::ModuloImpl, DB::NameModulo, false, true, false>::castBothTypes<DB::FunctionBinaryArithmetic<DB::ModuloImpl, DB::NameModulo, false, true, false>::e▒
     COW<DB::IColumn>::immutable_ptr<DB::IColumn> DB::FunctionBinaryArithmetic<DB::ModuloImpl, DB::NameModulo, false, true, false>::executeNumeric<DB::DataTypeNumber<unsigned long>, DB::DataTypeNumber<unsigned short> >(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocat▒
     DB::(anonymous namespace)::ModuloByConstantImpl<unsigned long, unsigned short>::vectorConstant(unsigned long const*, unsigned short, unsigned short*, unsigned long)                                                                                                               ▒
```

**Comment by serxa** [comment]
Maybe add a few force inline-s?

**Pull request closed without merging**
