### PR TITLE
fix some mutation bug

### PR DESCRIPTION
**Pull request by zhang2014**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Category:
- Bug Fix

Detailed description:
- [x] refer to max_expanded_ast_elements when select mutation commands
- [x] truncate should remove mutation

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
Something is wrong with your own test.

**Comment by zhang2014** [comment]
@alexey-milovidov The tests was wrong. Can you help me see what happened? I can't open these links.

**Comment by alexey-milovidov** [comment]
Sorry, I forgot about this PR. Will take a look.

**Comment by alexey-milovidov** [comment]
I understand the idea and the code looks Ok. Could you please merge with master?

**Comment by alexey-milovidov** [comment]
It is slightly incorrectly merged:

```
2019.08.29 08:46:45.606915 [ 174 ] {} <Fatal> BaseDaemon: ########################################
2019.08.29 08:46:45.607293 [ 174 ] {} <Fatal> BaseDaemon: (version 19.14.1.1207) (from thread 36) Received signal Segmentation fault (11).
2019.08.29 08:46:45.607567 [ 174 ] {} <Fatal> BaseDaemon: Address: NULL pointer. Access: read. Address not mapped to object.
2019.08.29 08:46:45.607749 [ 174 ] {} <Fatal> BaseDaemon: Stack trace: 0x16b34a21 0x16b39bed 0x16e71ddd 0x16e73209 0x16e7918c 0x16e78f91 0x16fb67b6 0x16fb4bbe 0x16fb5bbc 0x16fb5b81 0x16fb5b41 0x16fb5ad5 0x16fb5a96 0x16fb59c7 0x16fb5711 0xf330396 0xf343a16 0xf34ae2b 0xf34ade1 0xf34ad31 0xf34acf9 0xf34acb9 0xf34ab0d 0x194b1d70 0x7f70272e16db 0x7f7026bfe88f
2019.08.29 08:46:45.608981 [ 100 ] {} <Information> TCPHandler: Done processing connection.
2019.08.29 08:46:45.626856 [ 174 ] {} <Fatal> BaseDaemon: 4. 0x16b34a21 DB::MutationsInterpreter::prepareQueryAffectedAST() const /build/obj-x86_64-linux-gnu/../dbms/src/Interpreters/MutationsInterpreter.cpp:481
2019.08.29 08:46:45.645726 [ 174 ] {} <Fatal> BaseDaemon: 5. 0x16b39bed DB::MutationsInterpreter::evaluateCommandsSize() /build/obj-x86_64-linux-gnu/../dbms/src/Interpreters/MutationsInterpreter.cpp:500
2019.08.29 08:46:45.665524 [ 174 ] {} <Fatal> BaseDaemon: 6. 0x16e71ddd DB::StorageMergeTree::tryMutatePart() /build/obj-x86_64-linux-gnu/../dbms/src/Storages/StorageMergeTree.cpp:683
2019.08.29 08:46:45.685495 [ 174 ] {} <Fatal> BaseDaemon: 7. 0x16e73209 DB::StorageMergeTree::backgroundTask() /build/obj-x86_64-linux-gnu/../dbms/src/Storages/StorageMergeTree.cpp:799
2019.08.29 08:46:45.705392 [ 174 ] {} <Fatal> BaseDaemon: 8. 0x16e7918c DB::StorageMergeTree::startup()::$_0::operator()() const /build/obj-x86_64-linux-gnu/../dbms/src/Storages/StorageMergeTree.cpp:104
2019.08.29 08:46:45.725457 [ 174 ] {} <Fatal> BaseDaemon: 9. 0x16e78f91 std::_Function_handler<DB::BackgroundProcessingPoolTaskResult (), DB::StorageMergeTree::startup()::$_0>::_M_invoke(std::_Any_data const&) /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/std_function.h:285
2019.08.29 08:46:45.745704 [ 174 ] {} <Fatal> BaseDaemon: 10. 0x16fb67b6 std::function<DB::BackgroundProcessingPoolTaskResult ()>::operator()() const /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/std_function.h:690
2019.08.29 08:46:45.765831 [ 174 ] {} <Fatal> BaseDaemon: 11. 0x16fb4bbe DB::BackgroundProcessingPool::threadFunction() /build/obj-x86_64-linux-gnu/../dbms/src/Storages/MergeTree/BackgroundProcessingPool.cpp:203
2019.08.29 08:46:45.785988 [ 174 ] {} <Fatal> BaseDaemon: 12. 0x16fb5bbc DB::BackgroundProcessingPool::BackgroundProcessingPool(int)::$_0::operator()() const /build/obj-x86_64-linux-gnu/../dbms/src/Storages/MergeTree/BackgroundProcessingPool.cpp:70
2019.08.29 08:46:45.806140 [ 174 ] {} <Fatal> BaseDaemon: 13. 0x16fb5b81 void std::__invoke_impl<void, DB::BackgroundProcessingPool::BackgroundProcessingPool(int)::$_0 const&>(std::__invoke_other, DB::BackgroundProcessingPool::BackgroundProcessingPool(int)::$_0 const&) /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/invoke.h:60
2019.08.29 08:46:45.826463 [ 174 ] {} <Fatal> BaseDaemon: 14. 0x16fb5b41 std::__invoke_result<DB::BackgroundProcessingPool::BackgroundProcessingPool(int)::$_0 const&>::type std::__invoke<DB::BackgroundProcessingPool::BackgroundProcessingPool(int)::$_0 const&>(DB::BackgroundProcessingPool::BackgroundProcessingPool(int)::$_0 const&) /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/invoke.h:95
2019.08.29 08:46:45.846685 [ 174 ] {} <Fatal> BaseDaemon: 15. 0x16fb5ad5 decltype(auto) std::__apply_impl<DB::BackgroundProcessingPool::BackgroundProcessingPool(int)::$_0 const&, std::tuple<> const&>(DB::BackgroundProcessingPool::BackgroundProcessingPool(int)::$_0 const&, std::tuple<> const&, std::integer_sequence<unsigned long>) /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/tuple:1684
2019.08.29 08:46:45.866831 [ 174 ] {} <Fatal> BaseDaemon: 16. 0x16fb5a96 decltype(auto) std::apply<DB::BackgroundProcessingPool::BackgroundProcessingPool(int)::$_0 const&, std::tuple<> const&>(DB::BackgroundProcessingPool::BackgroundProcessingPool(int)::$_0 const&, std::tuple<> const&) /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/tuple:1694
2019.08.29 08:46:45.886987 [ 174 ] {} <Fatal> BaseDaemon: 17. 0x16fb59c7 ThreadFromGlobalPool::ThreadFromGlobalPool<DB::BackgroundProcessingPool::BackgroundProcessingPool(int)::$_0>(DB::BackgroundProcessingPool::BackgroundProcessingPool(int)::$_0&&)::{lambda()#1}::operator()() const /build/obj-x86_64-linux-gnu/../dbms/src/Common/ThreadPool.h:151
2019.08.29 08:46:45.907149 [ 174 ] {} <Fatal> BaseDaemon: 18. 0x16fb5711 std::_Function_handler<void (), ThreadFromGlobalPool::ThreadFromGlobalPool<DB::BackgroundProcessingPool::BackgroundProcessingPool(int)::$_0>(DB::BackgroundProcessingPool::BackgroundProcessingPool(int)::$_0&&)::{lambda()#1}>::_M_invoke(std::_Any_data const&) /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/std_function.h:302
2019.08.29 08:46:45.907484 [ 174 ] {} <Fatal> BaseDaemon: 19. 0xf330396 std::function<void ()>::operator()() const /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/std_function.h:690
2019.08.29 08:46:45.907736 [ 174 ] {} <Fatal> BaseDaemon: 20. 0xf343a16 ThreadPoolImpl<std::thread>::worker(std::_List_iterator<std::thread>) /build/obj-x86_64-linux-gnu/../dbms/src/Common/ThreadPool.cpp:221
2019.08.29 08:46:45.908247 [ 174 ] {} <Fatal> BaseDaemon: 21. 0xf34ae2b ThreadPoolImpl<std::thread>::scheduleImpl<void>(std::function<void ()>, int, std::optional<unsigned long>)::{lambda()#3}::operator()() const /build/obj-x86_64-linux-gnu/../dbms/src/Common/ThreadPool.cpp:102
2019.08.29 08:46:45.908745 [ 174 ] {} <Fatal> BaseDaemon: 22. 0xf34ade1 void std::__invoke_impl<void, ThreadPoolImpl<std::thread>::scheduleImpl<void>(std::function<void ()>, int, std::optional<unsigned long>)::{lambda()#3}>(std::__invoke_other, ThreadPoolImpl<std::thread>::scheduleImpl<void>(std::function<void ()>, int, std::optional<unsigned long>)::{lambda()#3}&&) /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/invoke.h:60
2019.08.29 08:46:45.909442 [ 174 ] {} <Fatal> BaseDaemon: 23. 0xf34ad31 std::__invoke_result<ThreadPoolImpl<std::thread>::scheduleImpl<void>(std::function<void ()>, int, std::optional<unsigned long>)::{lambda()#3}>::type std::__invoke<ThreadPoolImpl<std::thread>::scheduleImpl<void>(std::function<void ()>, int, std::optional<unsigned long>)::{lambda()#3}>(ThreadPoolImpl<std::thread>::scheduleImpl<void>(std::function<void ()>, int, std::optional<unsigned long>)::{lambda()#3}&&, (std::__invoke_result&&)...) /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/invoke.h:95
2019.08.29 08:46:45.909946 [ 174 ] {} <Fatal> BaseDaemon: 24. 0xf34acf9 void std::thread::_Invoker<std::tuple<ThreadPoolImpl<std::thread>::scheduleImpl<void>(std::function<void ()>, int, std::optional<unsigned long>)::{lambda()#3}> >::_M_invoke<0ul>(std::_Index_tuple<0ul>) /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/thread:244
2019.08.29 08:46:45.910491 [ 174 ] {} <Fatal> BaseDaemon: 25. 0xf34acb9 std::thread::_Invoker<std::tuple<ThreadPoolImpl<std::thread>::scheduleImpl<void>(std::function<void ()>, int, std::optional<unsigned long>)::{lambda()#3}> >::operator()() /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/thread:251
2019.08.29 08:46:45.910983 [ 174 ] {} <Fatal> BaseDaemon: 26. 0xf34ab0d std::thread::_State_impl<std::thread::_Invoker<std::tuple<ThreadPoolImpl<std::thread>::scheduleImpl<void>(std::function<void ()>, int, std::optional<unsigned long>)::{lambda()#3}> > >::_M_run() /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/thread:195
2019.08.29 08:46:45.935714 [ 174 ] {} <Fatal> BaseDaemon: 27. 0x194b1d70 execute_native_thread_routine /usr/lib/debug/usr/bin/clickhouse
2019.08.29 08:46:45.935942 [ 174 ] {} <Fatal> BaseDaemon: 28. 0x7f70272e16db start_thread /lib/x86_64-linux-gnu/libpthread-2.27.so
2019.08.29 08:46:45.936133 [ 174 ] {} <Fatal> BaseDaemon: 29. 0x7f7026bfe88f __clone /lib/x86_64-linux-gnu/libc-2.27.so
```

**Pull request merged**
