### PR TITLE
Autocompletion support for users in client

### PR DESCRIPTION
**Pull request by azat**
Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
It does not work:

```
$ clickhouse-client 
ClickHouse client version 20.5.1.1.
Connecting to localhost:9000 as user default.
Connected to ClickHouse server version 20.5.1 revision 54435.

milovidov-desktop :) Cannot load data for command line suggestions: Code: 497, e.displayText() = DB::Exception: Received from localhost:9000. DB::Exception: default: Not enough privileges. To execute this query it's necessary to have the grant SHOW USERS ON *.*. (version 20.5.1.1)
```

Revert before fix...

**Comment by alexey-milovidov** [comment]
I will add a test.

**Comment by azat** [comment]
>It does not work:

This can be fixed by installing `<access_management>1</access_management>` in `users.xml`, not the desired way? (cc @vitlibar )

**Comment by azat** [comment]
Another option is to execute this query separately and ignore access denied error

**Comment by alexey-milovidov** [comment]
Yes, it is the desired way, but it's still not enabled by default, and it will not be enabled for old servers,
so the new client will get an error communicating with old server.

**Comment by alexey-milovidov** [comment]
@vitlibar Why don't make the `system.users` table accessible if there is no access_management?
It effectively means that everything is allowed, so it should be allowed to see the list of users.

**Comment by vitlibar** [comment]
> @vitlibar Why don't make the `system.users` table accessible if there is no access_management?
> It effectively means that everything is allowed, so it should be allowed to see the list of users.

I don't think we should allow every user to know other users' names.
Maybe `system.users` should show only the current user's info when `access_management = 0` without throwing exception. Also we can provide another option `show_access` in `users.xml` which will enable readonly access to access management.

**Comment by alexey-milovidov** [comment]
> I don't think we should allow every user to know other users' names.

This is Ok when access management is turned off.
This info is already available in SHOW PROCESSLIST and query_log.

> Also we can provide another option show_access in users.xml which will enable readonly access to access management.

This complication is not really needed.

**Pull request merged**
