### PR TITLE
Fix RIGHT and FULL JOIN with LowCardinality

### LINKED ISSUE #9601: 19.16+ Exception in FULL JOIN on a LowCardinality column
How to reproduce:
```
CREATE TABLE left 
(
  lc   LowCardinality(String)
)
ENGINE = Memory;

CREATE TABLE right 
(
  lc   LowCardinality(String)
)
ENGINE = Memory;

insert into right values ('FNRNaHOZUErO');

SELECT * FROM left FULL JOIN right USING (lc)
```
19.13.7
```
┌─lc───────────┐
│ FNRNaHOZUErO │
└──────────────┘
1 rows in set. Elapsed: 0.002 sec.
```
19.16.14
Received exception from server (version 19.16.14):
Code: 241. DB::Exception: Received from localhost:9000. DB::Exception: Memory limit (for query) exceeded: would use 128.00 TiB (attempt to allocate chunk of 140737488355544 bytes), maximum: 47.03 GiB.

20.1.6
Exception on client:
Code: 271. DB::Exception: Data compressed with different methods, given method byte 69, previous method byte 82: while receiving packet from localhost:9000

### PR DESCRIPTION
**Pull request by 4ertus2**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix RIGHT and FULL JOIN with LowCardinality in JOIN keys.

Detailed description / Documentation draft:
Another patch for column representation conflicts (const, nullable, lowcard) in JOINs.

Closes #9601

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
A test has failed on one of builds. Maybe add ORDER BY?

**Comment by qoega** [comment]
```
2020-03-12 01:35:30 01049_join_low_card_bug:                                                [ FAIL ] 0.30 sec. - return code 171
2020-03-12 01:35:30 [38476f3e3f57] 2020.03.12 01:35:30.869228 [ 550 ] {8584001a-a744-404c-87b3-2d59e0cfe08b} <Error> executeQuery: Code: 171, e.displayText() = DB::Exception: Cannot convert column `toTypeName(r.lc)` because it is constant but values of constants are different in source and result (version 20.3.1.2618) (from [::1]:35504) (in query: SELECT l.lc, r.lc, toTypeName(l.lc), toTypeName(r.lc) FROM l_lc AS l RIGHT JOIN r USING (lc)), Stack trace (when copying this message, always include the lines below):
2020-03-12 01:35:30 
2020-03-12 01:35:30 0. /build/obj-x86_64-linux-gnu/../contrib/poco/Foundation/src/Exception.cpp:27: Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x1027503c in /usr/lib/debug/usr/bin/clickhouse
2020-03-12 01:35:30 1. /build/obj-x86_64-linux-gnu/../dbms/src/Common/Exception.cpp:33: DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x8f069a9 in /usr/lib/debug/usr/bin/clickhouse
2020-03-12 01:35:30 2. /build/obj-x86_64-linux-gnu/../contrib/libcxx/include/string:2134: DB::ConvertingBlockInputStream::ConvertingBlockInputStream(DB::Context const&, std::__1::shared_ptr<DB::IBlockInputStream> const&, DB::Block const&, DB::ConvertingBlockInputStream::MatchColumnsMode) (.cold) @ 0xcee9cd4 in /usr/lib/debug/usr/bin/clickhouse
2020-03-12 01:35:30 3. /build/obj-x86_64-linux-gnu/../contrib/libcxx/include/type_traits:3696: DB::InterpreterSelectQuery::unifyStreams(DB::InterpreterSelectQuery::Pipeline&, DB::Block) @ 0xcf4fbde in /usr/lib/debug/usr/bin/clickhouse
2020-03-12 01:35:30 4. /build/obj-x86_64-linux-gnu/../contrib/libcxx/include/map:1090: DB::InterpreterSelectQuery::executeWithMultipleStreams(DB::QueryPipeline&) @ 0xcf5f375 in /usr/lib/debug/usr/bin/clickhouse
2020-03-12 01:35:30 5. /build/obj-x86_64-linux-gnu/../contrib/libcxx/include/vector:1532: DB::InterpreterSelectWithUnionQuery::executeWithMultipleStreams(DB::QueryPipeline&) @ 0xd154fe0 in /usr/lib/debug/usr/bin/clickhouse
2020-03-12 01:35:30 6. /build/obj-x86_64-linux-gnu/../contrib/libcxx/include/vector:662: DB::InterpreterSelectWithUnionQuery::execute() @ 0xd15529a in /usr/lib/debug/usr/bin/clickhouse
2020-03-12 01:35:30 7. /build/obj-x86_64-linux-gnu/../dbms/src/Interpreters/executeQuery.cpp:328: DB::executeQueryImpl(char const*, char const*, DB::Context&, bool, DB::QueryProcessingStage::Enum, bool, DB::ReadBuffer*, bool) @ 0xd3544e7 in /usr/lib/debug/usr/bin/clickhouse
2020-03-12 01:35:30 8. /build/obj-x86_64-linux-gnu/../dbms/src/Interpreters/executeQuery.cpp:572: DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::Context&, bool, DB::QueryProcessingStage::Enum, bool, bool) @ 0xd35704d in /usr/lib/debug/usr/bin/clickhouse
2020-03-12 01:35:30 9. /build/obj-x86_64-linux-gnu/../dbms/programs/server/TCPHandler.cpp:249: DB::TCPHandler::runImpl() @ 0x8fe2d39 in /usr/lib/debug/usr/bin/clickhouse
2020-03-12 01:35:30 10. /build/obj-x86_64-linux-gnu/../dbms/programs/server/TCPHandler.cpp:1240: DB::TCPHandler::run() @ 0x8fe3c4c in /usr/lib/debug/usr/bin/clickhouse
2020-03-12 01:35:30 11. /build/obj-x86_64-linux-gnu/../contrib/poco/Net/src/TCPServerConnection.cpp:57: Poco::Net::TCPServerConnection::start() @ 0xe029c47 in /usr/lib/debug/usr/bin/clickhouse
2020-03-12 01:35:30 12. /build/obj-x86_64-linux-gnu/../contrib/libcxx/include/atomic:856: Poco::Net::TCPServerDispatcher::run() @ 0xe02a0ad in /usr/lib/debug/usr/bin/clickhouse
2020-03-12 01:35:30 13. /build/obj-x86_64-linux-gnu/../contrib/poco/Foundation/include/Poco/Mutex_STD.h:132: Poco::PooledThread::run() @ 0x102ff33f in /usr/lib/debug/usr/bin/clickhouse
2020-03-12 01:35:30 14. /build/obj-x86_64-linux-gnu/../contrib/poco/Foundation/include/Poco/AutoPtr.h:205: Poco::ThreadImpl::runnableEntry(void*) @ 0x102fb388 in /usr/lib/debug/usr/bin/clickhouse
2020-03-12 01:35:30 15. /build/obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:2615: void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void* (*)(void*), Poco::ThreadImpl*> >(void*) @ 0x102fcc29 in /usr/lib/debug/usr/bin/clickhouse
2020-03-12 01:35:30 16. start_thread @ 0x76db in /lib/x86_64-linux-gnu/libpthread-2.27.so
2020-03-12 01:35:30 17. __clone @ 0x12188f in /lib/x86_64-linux-gnu/libc-2.27.so
2020-03-12 01:35:30 
2020-03-12 01:35:30 Received exception from server (version 20.3.1):
2020-03-12 01:35:30 Code: 171. DB::Exception: Received from localhost:9000. DB::Exception: Cannot convert column `toTypeName(r.lc)` because it is constant but values of constants are different in source and result. 
```

**Comment by 4ertus2** [comment]
All test queries return 1 row so no ORDER BY needed. The trouble is in ConvertingBlockInputStream that founds inconsistency between result data (LowCard<String> column) and header (String column). In fact it's inconsistency of `toTypeName()` calculated on intermediate data and final header. We have LowCard<String> data after joins but final projection has String.

**Comment by 4ertus2** [comment]
I've materialized column in test to pass it: `toTypeName(r.lc)` -> `toTypeName(materialize(r.lc))`
It looks like it's another error out of JOIN scope.

**Pull request merged**
