### PR TITLE
Release pull request for branch 24.2

### PR DESCRIPTION
**Pull request by alexey-milovidov**
This PullRequest is a part of ClickHouse release cycle. It is used by CI system only. Do not perform any changes with it.

### CODE REVIEW

**Comment by alifirat** [comment]
Do you know when this patch version will be released?

**Comment by alifirat** [comment]
Hi @alexey-milovidov why closing this PR means?

**Comment by alexey-milovidov** [comment]
No longer supported.

**Comment by alexey-milovidov** [comment]
https://github.com/ClickHouse/ClickHouse/blob/master/SECURITY.md

**Comment by alifirat** [comment]
So no more patch release on the 24.2? 😞

**Comment by alexey-milovidov** [comment]
Maybe it makes sense to make the last release of 24.2?

**Comment by alifirat** [comment]
It will be very cool to do that 🙏

**Pull request closed without merging**
