### PR TITLE
Optimize single part projection materialization

### LINKED ISSUE #31669: Projection size after materialize projection
`alter table z materialize projection` builds a projection with the size is much bigger than the size after insertion or merge.

```sql
create table z(pk Int64, d Date, id UInt64, c UInt64) Engine=MergeTree partition by d order by pk;

insert into z  select number, today(), intDiv (number, 1000000), 1 from numbers(100000000);
optimize table z final;

alter table z add projection pp (select id, sum(c) group by id);
alter table z materialize projection pp settings mutations_sync=1;

insert into z  select number, today()+1, intDiv (number, 1000000), 1 from numbers(100000000);

SELECT
    database,
    table,
    name,
    partition,
    formatReadableSize(sum(data_compressed_bytes) AS size) AS compressed,
    formatReadableSize(sum(data_uncompressed_bytes) AS usize) AS uncompressed,
    round(usize / size, 2) AS compr_rate,
    sum(rows) AS rows,
    count() AS part_count
FROM system.projection_parts
WHERE (table = 'z') AND active
GROUP BY
    database,
    table,
    name,
    partition
ORDER BY size DESC;

┌─database─┬─table─┬─name─┬─partition──┬─compressed─┬─uncompressed─┬─compr_rate─┬─rows─┬─part_count─┐
│ dw       │ z     │ pp   │ 2021-11-23 │ 2.22 KiB   │ 28.80 KiB    │      12.97 │ 1843 │          1 │ 1843 rows after materialize
│ dw       │ z     │ pp   │ 2021-11-24 │ 820.00 B   │ 1.63 KiB     │       2.03 │  104 │          5 │ 104 rows after insert
└──────────┴───────┴──────┴────────────┴────────────┴──────────────┴────────────┴──────┴────────────┘

optimize table z final;

┌─database─┬─table─┬─name─┬─partition──┬─compressed─┬─uncompressed─┬─compr_rate─┬─rows─┬─part_count─┐
│ dw       │ z     │ pp   │ 2021-11-23 │ 475.00 B   │ 1.56 KiB     │       3.37 │  100 │          1 │
│ dw       │ z     │ pp   │ 2021-11-24 │ 475.00 B   │ 1.56 KiB     │       3.37 │  100 │          1 │
└──────────┴───────┴──────┴────────────┴────────────┴──────────────┴────────────┴──────┴────────────┘
```

### PR DESCRIPTION
**Pull request by amosbird**
Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Optimize single part projection materialization. This closes https://github.com/ClickHouse/ClickHouse/issues/31669

Detailed description / Documentation draft:
.

### CODE REVIEW

**Review by novikd — COMMENTED** [review]
Add a test?

**Comment by amosbird** [comment]
Done

**Review by novikd — APPROVED** [review]

**Comment by novikd** [comment]
Needs to resolve conflicts for merge

**Comment by novikd** [comment]
> AST fuzzer (debug, actions) — Task failed: $?=210 

Known issue in master

> Integration tests (release, actions) [2/2] — fail: 100, passed: 809, flaky: 0

#32985 should fix it

> Integration tests (thread, actions) [2/4] — fail: 60, passed: 401, flaky: 1

Same

> PVS Studio (actions) — PVS report failed to build 

Must be OK in master

**Pull request merged**
