### PR TITLE
Add query progress to table zookeeper

### LINKED ISSUE #48491: Unrestricted reads from `system.zookeeper` table should provide progress bar.
**Describe the issue**
```
ip-172-31-1-68.eu-central-1.compute.internal :) SELECT
                                                    count()
                                                FROM system.zookeeper
                                                WHERE path LIKE '%/_objects/%' AND name == '.data';

SELECT count()
FROM system.zookeeper
WHERE (path LIKE '%/_objects/%') AND (name = '.data')

Query id: 79d7d11b-de64-485a-9016-b39d06e12815

   Timeout exceeded while receiving data from server. Waited for 300 seconds, timeout is 300 seconds.
Cancelling query.
client_loop: send disconnect: Broken pipe
```

### PR DESCRIPTION
**Pull request by JackyWoo**
This PR tries to fix #48491
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Add query progress to table zookeeper

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

---
### Modify your CI run:
**NOTE:** If your merge the PR with modified CI you **MUST KNOW** what you are doing
**NOTE:** Checked options will be applied if set before CI RunConfig/PrepareRunConfig step

#### Include tests (required builds will be added automatically):
- [ ]  Fast test
- [ ]  Integration Tests
- [ ]  Stateless tests
- [ ]  Stateful tests
- [ ]  Unit tests
- [ ]  Performance tests
- [ ]  All with ASAN
- [ ]  All with TSAN
- [ ]  All with Analyzer
- [ ]  Add your option here

#### Exclude tests:
- [ ]  Fast test
- [ ]  Integration Tests
- [ ]  Stateless tests
- [ ]  Stateful tests
- [ ]  Performance tests
- [ ]  All with ASAN
- [ ]  All with TSAN
- [ ]  All with MSAN
- [ ]  All with UBSAN
- [ ]  All with Coverage
- [ ]  All with Aarch64
- [ ]  Add your option here

#### Extra options:
- [ ]  do not test (only style check)
- [ ]  disable merge-commit (no merge from master before tests)
- [ ]  disable CI cache (job reuse)

#### Only specified batches in multi-batch jobs:
- [ ]  1
- [ ]  2
- [ ]  3
- [ ]  4

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]
LGTM

**Comment by robot-ch-test-poll4** [comment]
*This is an automated comment for commit b2b9706ba2408b3fea5c2f2782e60ef0cb26127c with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/62152/b2b9706ba2408b3fea5c2f2782e60ef0cb26127c/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

**Comment by JackyWoo** [comment]
@alexey-milovidov The failed test cases seem to be flaky.

**Comment by alexey-milovidov** [comment]
Ok, we will wait when the tests are fixed.

**Comment by JackyWoo** [comment]
@alexey-milovidov The previous flaky tests are all green. But found failed stress test which may be not caused by this PR.

**Review by alexey-milovidov — APPROVED** [review]

**Pull request merged**
