### PR TITLE
Update comment about mismatching checksums

### PR DESCRIPTION
**Pull request by tavplubix**
Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
@mergifyio update

**Comment by tavplubix** [comment]
Stateless tests (memory, actions) [2/3] - `01514_parallel_formatting` - `select count() from tsv; -- engine File(TSV)` was executing too slow:
```
2022.03.26 17:41:38.055075 [ 8026 ] {d5daf26f-6c86-4f36-8d6e-b2e1c97444bb} <Debug> executeQuery: (from [::1]:56650) (comment: 01514_parallel_formatting.sql) select count() from tsv;
2022.03.26 17:41:38.063081 [ 8026 ] {d5daf26f-6c86-4f36-8d6e-b2e1c97444bb} <Trace> ContextAccess (default): Access granted: SELECT(a) ON test_et40kj.tsv
2022.03.26 17:41:38.064551 [ 8026 ] {d5daf26f-6c86-4f36-8d6e-b2e1c97444bb} <Trace> InterpreterSelectQuery: FetchColumns -> Complete
2022.03.26 17:41:38.071709 [ 1395 ] {d5daf26f-6c86-4f36-8d6e-b2e1c97444bb} <Trace> ParallelParsingInputFormat: Parallel parsing is used
2022.03.26 17:42:18.810516 [ 1395 ] {d5daf26f-6c86-4f36-8d6e-b2e1c97444bb} <Trace> AggregatingTransform: Aggregating
2022.03.26 17:42:18.810715 [ 1395 ] {d5daf26f-6c86-4f36-8d6e-b2e1c97444bb} <Trace> Aggregator: Aggregation method: without_key
2022.03.26 17:52:52.211080 [ 1395 ] {d5daf26f-6c86-4f36-8d6e-b2e1c97444bb} <Debug> AggregatingTransform: Aggregated. 20000000 to 1 rows (from 152.59 MiB) in 674.144160523 sec. (29667.245 rows/sec., 231.78 KiB/sec.)
2022.03.26 17:52:52.211312 [ 1395 ] {d5daf26f-6c86-4f36-8d6e-b2e1c97444bb} <Trace> Aggregator: Merging aggregated data
2022.03.26 17:52:52.214769 [ 8026 ] {d5daf26f-6c86-4f36-8d6e-b2e1c97444bb} <Information> executeQuery: Read 20000000 rows, 152.59 MiB in 674.159273487 sec., 29666 rows/sec., 231.77 KiB/sec.
2022.03.26 17:52:52.217584 [ 8026 ] {d5daf26f-6c86-4f36-8d6e-b2e1c97444bb} <Debug> MemoryTracker: Peak memory usage (for query): 195.17 MiB.
```
Maybe related to #35615


Stateless tests (release, actions) - `01062_window_view_event_hop_watch_asc` looks flaky, cc: @Vxider, @kssenii 
Stateless tests (release, wide parts enabled, actions) - `02180_group_by_lowcardinality` - probably `order by` is missing in test, but it looks weird 
Stateless tests (thread, actions) [1/3] - `01532_primary_key_without_order_by_zookeeper` - #35657
Stateless tests (thread, actions) [3/3] - `02122_parallel_formatting` - Timeout, looks like test is too long and 600s is not enough sometimes, cc: @Avogar 
Stateless tests (ubsan, actions) -  `01514_parallel_formatting` - the same as the first one

**Comment by Avogar** [comment]
> Stateless tests (thread, actions) [3/3] - 02122_parallel_formatting - Timeout, looks like test is too long and 600s is not enough sometimes, cc: @Avogar

I guess it's because of `--max_read_buffer_size=1`. Will use constant value for this setting in this test

**Comment by tavplubix** [comment]
> > Stateless tests (thread, actions) [3/3] - 02122_parallel_formatting - Timeout, looks like test is too long and 600s is not enough sometimes, cc: @Avogar
> 
> I guess it's because of `--max_read_buffer_size=1`. Will use constant value for this setting in this test

I suppose that we have too many tests that will not work correctly with small buffers. See also https://github.com/ClickHouse/ClickHouse/issues/35615. Let's change distribution function for this setting, so buffers will never be that small.

**Pull request merged**
