### PR TITLE
Add LZ4F compression codec

### PR DESCRIPTION
**Pull request by hczhcz**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- New Feature

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Add LZ4F compression codec

Detailed description / Documentation draft:

[LZ4 Frame format](https://github.com/lz4/lz4/blob/dev/doc/lz4_Frame_format.md)

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
What is the point to have LZ4 frame format if it will be wrapped into our own frame format and the final file will be incompatible with LZ4?

**Comment by hczhcz** [comment]
@alexey-milovidov 
LZ4F is slightly faster in decompression on our servers. I am wondering if it actually works.

**Comment by alexey-milovidov** [comment]
> LZ4F is slightly faster in decompression on our servers. I am wondering if it actually works.

It should not be related to the framing format.

**Comment by alexey-milovidov** [comment]
BTW, it's very difficult to say confidently that it is faster.

We test on various datasets: integers, strings, small and large, highly and low compressable.
And on different CPU models: there are multiple differencies on what will be actually faster.

https://habr.com/en/company/yandex/blog/457612/

**Pull request closed without merging**
