### PR TITLE
Cherry pick #63353 to 24.2: Fix logical error during SELECT query after ALTER in rare case

### PR DESCRIPTION
**Pull request by robot-clickhouse-ci-1**
Original pull-request #63353

This pull-request is a first step of an automated backporting.
It contains changes similar to calling `git cherry-pick` locally.
If you intend to continue backporting the changes, then resolve all conflicts if any.
Otherwise, if you do not want to backport them, then just close this pull-request.

The check results does not matter at this step - you can safely ignore them.

### Note

This pull-request will be merged automatically. Please, **do not merge it manually** (but if you accidentally did, nothing bad will happen).

#### If the PR was manually reopened after being closed

If this PR is stuck (i.e. not automatically merged after one day), check https://github.com/ClickHouse/ClickHouse/pull/63353 for `pr-backports-created` *label* and delete it.

Manually merging will do nothing. The `pr-backports-created` *label* prevents the original PR https://github.com/ClickHouse/ClickHouse/pull/63353 from being processed.

#### If the conflicts were resolved in a wrong way

If this cherry-pick PR is completely screwed by a wrong conflicts resolution, and you want to recreate it:

- delete the `pr-cherrypick` label from the PR
- delete this branch from the repository

You also need to check the original PR https://github.com/ClickHouse/ClickHouse/pull/63353 for `pr-backports-created`, and delete if it's presented there

### CODE REVIEW

**Comment by robot-ch-test-poll4** [comment]
Dear @alesapin, @KochetovNicolai, the PR is not updated for 1d24h56m26s. Please, either resolve the conflicts, or close it to finish the backport process of #63353

**Comment by robot-ch-test-poll3** [comment]
Dear @alesapin, @KochetovNicolai, the PR is not updated for 1d24h7m25s. Please, either resolve the conflicts, or close it to finish the backport process of #63353

**Comment by robot-clickhouse** [comment]
Dear @alesapin, @KochetovNicolai, the PR is not updated for 1d24h53m27s. Please, either resolve the conflicts, or close it to finish the backport process of #63353

**Comment by robot-clickhouse-ci-1** [comment]
Dear @alesapin, @KochetovNicolai, the PR is not updated for 1d24h58m52s. Please, either resolve the conflicts, or close it to finish the backport process of #63353

**Comment by robot-clickhouse-ci-1** [comment]
Dear @alesapin, @KochetovNicolai, the PR is not updated for 1d25h1m26s. Please, either resolve the conflicts, or close it to finish the backport process of #63353

**Comment by robot-clickhouse-ci-1** [comment]
Dear @alesapin, @KochetovNicolai, the PR is not updated for 1d24h1m3s. Please, either resolve the conflicts, or close it to finish the backport process of #63353

**Comment by robot-ch-test-poll1** [comment]
Dear @alesapin, @KochetovNicolai, the PR is not updated for 1d24h59m37s. Please, either resolve the conflicts, or close it to finish the backport process of #63353

**Comment by robot-ch-test-poll4** [comment]
Dear @alesapin, @KochetovNicolai, the PR is not updated for 1d24h58m38s. Please, either resolve the conflicts, or close it to finish the backport process of #63353

**Comment by robot-clickhouse-ci-2** [comment]
Dear @alesapin, @KochetovNicolai, the PR is not updated for 1d24h1m46s. Please, either resolve the conflicts, or close it to finish the backport process of #63353

**Comment by robot-ch-test-poll2** [comment]
Dear @alesapin, @KochetovNicolai, the PR is not updated for 1d24h59m43s. Please, either resolve the conflicts, or close it to finish the backport process of #63353

**Comment by robot-ch-test-poll2** [comment]
Dear @alesapin, @KochetovNicolai, the PR is not updated for 1d24h55m43s. Please, either resolve the conflicts, or close it to finish the backport process of #63353

**Comment by robot-clickhouse-ci-1** [comment]
Dear @alesapin, @KochetovNicolai, the PR is not updated for 1d24h0m48s. Please, either resolve the conflicts, or close it to finish the backport process of #63353

**Comment by robot-clickhouse-ci-1** [comment]
Dear @alesapin, @KochetovNicolai, the PR is not updated for 1d24h0m25s. Please, either resolve the conflicts, or close it to finish the backport process of #63353

**Comment by robot-ch-test-poll2** [comment]
Dear @alesapin, @KochetovNicolai, the PR is not updated for 1d24h59m35s. Please, either resolve the conflicts, or close it to finish the backport process of #63353

**Comment by robot-ch-test-poll2** [comment]
Dear @alesapin, @KochetovNicolai, the PR is not updated for 1d25h1m3s. Please, either resolve the conflicts, or close it to finish the backport process of #63353

**Comment by robot-ch-test-poll** [comment]
Dear @alesapin, @KochetovNicolai, the PR is not updated for 1d24h58m43s. Please, either resolve the conflicts, or close it to finish the backport process of #63353

**Comment by robot-ch-test-poll** [comment]
Dear @alesapin, @KochetovNicolai, the PR is not updated for 1d24h0m20s. Please, either resolve the conflicts, or close it to finish the backport process of #63353

**Pull request closed without merging**
