### PR TITLE
ISSUES-863 support predicate push down

### PR DESCRIPTION
**Pull request by zhang2014**
#863 
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

### CODE REVIEW

**Comment by zhang2014** [comment]
@KochetovNicolai @alexey-milovidov Can you give me some advice about this issue.

**Comment by zhang2014** [comment]
I don't know how to write test for this `Pull Request`

**Comment by alexey-milovidov** [comment]
Basic idea of implementation:

Look at expression in WHERE and PREWHERE.
(This should be done after expansion of aliases.)

It can be an AND of multiple elements or not. In latter case it is considered as single element.
In first case, you should consider cases when you have single AND function
`and(a, b, c...)` or a chain of nested functions: `and(a, and(b, c))`...
Then you should look at each of elements in condition (`a`, `b`, `c`).

For each element, you should check, that it is dependent only on columns from a subquery and constants. If that's true, this element is considered for push-down.

Then look at what kind of subquery do you have.
It can be single SELECT or UNION ALL.

For each SELECT we should decide, if the condition can be pushed-down.

If SELECT contains LIMIT or LIMIT BY or WITH TOTALS or FINAL, the condition cannot be pushed-down.

If SELECT contains GROUP BY, and condition is depend only on aggregation keys, the consition can be pushed to WHERE. Otherwise, the condition can be pushed to HAVING.

If you have multiple SELECTs with UNION ALL, there are multiple cases:
When condition cannot be pushed at all.
When condition can be pushed to all of SELECTs.
When condition can be pushed to some SELECTs but cannot be pushed to some other SELECTs.

In second case, you should push condition to all SELECTs and remove it from the outer query.
In third case, you should push conditions to some SELECTs but also leave it in outer query.

When adding conditions, take care to create new WHERE/HAVING expression if there was no such expressions before, or adding condition as an element of AND chain. When removing conditions, take care to remove WHERE/PREWHERE if all conditions was moved.

How to test:

Create a table of type MergeTree. Use settings `force_primary_key` and `max_rows_to_read` to check if the key was used. We expect, that when condition is pushed to subquery, the primary key will be used and number of rows will be limited.

Please take a look to other tests that use `force_primary_key`.

**Comment by zhang2014** [comment]
Sorry for the delay, I plan to continue this task after #2260

**Comment by tobad357** [comment]
@zhang2014 don't be sorry, I'm very grateful your even working on it :)

**Comment by zhang2014** [comment]
@alexey-milovidov @KochetovNicolai @vavrusa Almost done, Could help review this? 
BTW Sorry for the delay : )

**Comment by alexey-milovidov** [comment]
TODO: verify that all test passed when the setting is enabled globally.

**Comment by zhang2014** [comment]
@alexey-milovidov There are some problems with the current implementation.
### Can't work
```SQL 
SELECT * FROM (SELECT * FROM test.test) WHERE id = 1; 
```
### Unexpected results
``` SQL
SELECT * FROM (SELECT  id, 'S' AS name FROM test.test_join_1) AS a ALL LEFT JOIN (SELECT id, 'S' AS name FROM test.test_join_2) AS b USING name WHERE b.id  = 1;
```
I'm trying to fix it.

**Comment by alexey-milovidov** [comment]
FYI, there is an issue with a query that `clickhouse-client` send to obtain info for autocomplete:

```
SELECT DISTINCT arrayJoin(extractAll(name, '[\\w_]{2,}')) AS res
FROM 
(
    SELECT name
    FROM system.functions 
    UNION ALL
    SELECT name
    FROM system.table_engines 
    UNION ALL
    SELECT name
    FROM system.formats 
    UNION ALL
    SELECT name
    FROM system.table_functions 
    UNION ALL
    SELECT name
    FROM system.data_type_families 
    UNION ALL
    SELECT concat(func.name, comb.name)
    FROM system.functions AS func 
    CROSS JOIN system.aggregate_function_combinators AS comb 
    WHERE is_aggregate
    UNION ALL
    SELECT name
    FROM system.databases 
    LIMIT 10000
    UNION ALL
    SELECT DISTINCT name
    FROM system.tables 
    LIMIT 10000
    UNION ALL
    SELECT DISTINCT name
    FROM system.columns 
    LIMIT 10000
) 
WHERE notEmpty(res)

Received exception from server (version 18.12.1):
Code: 47. DB::Exception: Received from localhost:9000, 127.0.0.1. DB::Exception: Unknown identifier: concat(func.name, comb.name).
```

**Pull request merged**
