### PR TITLE
Support interserver credential rotation

### PR DESCRIPTION
**Pull request by johnskopis**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

...

Detailed description / Documentation draft:

...

By adding documentation, you'll allow users to try your new feature immediately, not when someone else will have time to document it later. Documentation is necessary for all features that affect user experience in any way. You can add brief documentation draft above, or add documentation right into your patch as Markdown files in [docs](https://github.com/ClickHouse/ClickHouse/tree/master/docs) folder.

If you are doing this for the first time, it's recommended to read the lightweight [Contributing to ClickHouse Documentation](https://github.com/ClickHouse/ClickHouse/tree/master/docs/README.md) guide first.

Information about CI checks: https://clickhouse.tech/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by johnskopis** [comment]
fixes #14106

**Comment by filimonov** [comment]
"johnskopis wants to merge 1 commit into ClickHouse:19.18"  

Can you do the same to master branch please? 19.18 was never released and is not supported.

**Comment by johnskopis** [comment]
> "johnskopis wants to merge 1 commit into ClickHouse:19.18"
> 
> Can you do the same to master branch please? 19.18 was never released and is not supported.

Sure. FWIW I developed against 19.13 and picked what I thought was highest version in v19.x series.

**Comment by johnskopis** [comment]
v20 pr: https://github.com/ClickHouse/ClickHouse/pull/14113

**Comment by johnskopis** [comment]
Closing in favor of PR against master

**Pull request closed without merging**
