### PR TITLE
Speedup insert performance of vector similarity index by parallelization

### PR DESCRIPTION
**Pull request by ucasfl**
### Changelog category (leave one):

- Performance Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Speedup insert performance with vector similarity index by adding data to vector index parallel

Insert 50k rows vector with 768 dimension:

Before:
```
50000 rows in set. Elapsed: 107.843 sec. Processed 50.00 thousand rows, 482.50 MB (463.64 rows/s., 4.47 MB/s.) Peak memory usage: 338.34 MiB.
```

After:
```
50000 rows in set. Elapsed: 12.377 sec. Processed 50.00 thousand rows, 482.50 MB (4.04 thousand rows/s., 38.98 MB/s.) Peak memory usage: 338.34 MiB.
```

### CODE REVIEW

**Comment by robot-ch-test-poll2** [comment]
*This is an automated comment for commit cf12e3924f51fd08c884519352a46495412a771a with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/69493/cf12e3924f51fd08c884519352a46495412a771a/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/db42cf12fd0e7a54b9a63118b21c300eddb7970e/docs_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Review by rschu1ze — COMMENTED** [review]
@ucasfl Cool, thanks. You "re-discovered" a performance optimization that the previous Annoy indexes had (setting "max_threads_for_annoy_index_creation", in [this commit](https://github.com/ClickHouse/ClickHouse/pull/63675/commits/218421c255cadbe65406e6a040d05942cc4efc3e#diff-aa3c979016a9f8c6ab5a51560411afa3f4cef55d34c899a2b1e7aff38aca4076) where Annoy indexes were removed) :-)

The previous optimization had the problem that it spawned N threads per each merge. With M merges going on at the same time, one had N x M extra threads. Is it right that with your optimization, the number of threads for Usearch index creation is globally fixed?

Another possible optimization: Usearch uses the HNSW algorithm. Right now, the merge re-builds a usearch index on the result part from scratch by indexing the rows of the first and the second part. This is inefficient, as HNSW supports adding new rows to an existing index, reducing construction time by 1/2 on average. `MergeTreeIndexAggregatorVectorSimilarity::update` currently only receives row values, to re-cycle the HNSW index of merged parts (ideally of the biggest part), we'd need a custom-built interface which passes in either a usearch index or a MergeTreeIndexVectorSimilarity. So if you like to have a look at this, it would be great, otherwise I can also check.

**Comment by ucasfl** [comment]
>The previous optimization had the problem that it spawned N threads per each merge. With M merges going on at the same time, one had N x M extra threads. Is it right that with your optimization, the number of threads for Usearch index creation is globally fixed?

It could be globally fixed if we create a global thread pool for Usearch index creation.

**Comment by rschu1ze** [comment]
> It could be globally fixed if we create a global thread pool for Usearch index creation.

Let's do that.

**Comment by ucasfl** [comment]
> > It could be globally fixed if we create a global thread pool for Usearch index creation.
> 
> Let's do that.

The pool size should be a server setting or something else?

**Review by rschu1ze — APPROVED** [review]

**Comment by rschu1ze** [comment]
Thanks @ucasfl The PR looks good to me!

**Comment by rschu1ze** [comment]
Stateless tests (tsan) [1/4]: #49156

**Pull request merged**
