### PR TITLE
Pre-fault pages when allocating memory with mmap().

### PR DESCRIPTION
**Pull request by akuzm**
Otherwise, each page is faulted in on the first write acess, which
negatively affects performance by repeatedly interrupting hot loops.

Category (leave one):
- Performance Improvement

Let's see if it influences the performance tests at all. From what I've seen in perf reports, the aggregation should be affected by a couple percent.

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
Please merge with master for performance test to run.

**Comment by akuzm** [comment]
The regressions are bigger than improvements. The biggest are in queries that materialize constant columns. Since we can overallocate memory for columns by a large margin, populating it does more harm than good. Maybe we should populate only for arenas, which use smaller chunks.

**Comment by alexey-milovidov** [comment]
You can populate only for hash tables (adding a flag similar to `clear_memory_`).

**Comment by alexey-milovidov** [comment]
(at least it should fix performance regression for AMD)

**Comment by amosbird** [comment]
Not sure how the POPULATE flag works. But via memory page touching, pre fault can be parallelized

**Comment by akuzm** [comment]
Looking at the performance test results, many DISTINCT queries show an improvement of 5-10%, while some GROUP BY queries regress. The most regressing one is `SELECT URL, count() AS PageViews FROM hits_100m_single WHERE CounterID = 34 AND EventDate >= '2013-07-01' AND EventDate <= '2013-07-31' AND NOT Refresh AND IsLink AND NOT IsDownload GROUP BY URL ORDER BY PageViews DESC LIMIT 1000` shows the most regression (x1.15). I compared it to master with clickhouse-benchmark. The pre-fault version is marginally faster, but this difference is deep below the noise:

Version|Queries/second| Spread = q(0.95)-q(0.05)
--- | --- | ---
MAP_POPULATE |20.63 |2.64
Normal| 20.37 |3.64

I rebased to ce73e17ff660aa8ee62aff5bbd4e7e859cfdec12 which is used as performance test reference now, so that we can compare better.

**Comment by akuzm** [comment]
```
select count(*), count(distinct URL) FROM hits_100m_single WHERE CounterID = 34 AND EventDate >= '2013-07-01' AND EventDate <= '2013-07-31' AND NOT Refresh AND IsLink AND NOT IsDownload;

┌─count()─┬─uniqExact(URL)─┐
│   47740 │          15628 │
└─────────┴────────────────┘
```

Just in case, checked that this query has a non-empty aggregation set.

**Comment by akuzm** [comment]
I was able to reproduce the improvement for DISTINCT that we see in CI performance test (median QPS for 7 runs of 137 seconds, the runs with different server versions are interleaved):
```
SELECT DISTINCT URL, ngramDistanceUTF8(URL, 'как дела') AS distance FROM hits_100m_single ORDER BY distance ASC LIMIT 50

┏━━━━━━━━━━━━━━━┳━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━┓
┃ version       ┃ count() ┃ median qps ┃ spread ┃
┡━━━━━━━━━━━━━━━╇━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━┩
│ ./ch-prefault │       7 │      0.199 │  0.001 │
├───────────────┼─────────┼────────────┼────────┤
│ ./ch-master   │       7 │      0.185 │  0.001 │
└───────────────┴─────────┴────────────┴────────┘
```

**Comment by akuzm** [comment]
No meaningful changes for hll12:
```
SELECT 1 AS k, uniqHLL12(UserID) FROM hits_100m_single GROUP BY k

┏━━━━━━━━━━━━━━━┳━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━┓
┃ version       ┃ count() ┃ median qps ┃ spread ┃
┡━━━━━━━━━━━━━━━╇━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━┩
│ ./ch-prefault │       7 │     12.652 │   1.11 │
├───────────────┼─────────┼────────────┼────────┤
│ ./ch-master   │       7 │     12.713 │  0.931 │
└───────────────┴─────────┴────────────┴────────┘
```

**Comment by akuzm** [comment]
Also seeing a marginal improvement for `SELECT SearchEngineID AS k, uniqExact(UserID) FROM hits_100m_single GROUP BY k`  (0.58 vs 0.56 qps).

Will merge this now as discussed offline, because we are seeing slight improvements, no regressions and the rationale sounds correct.

**Pull request merged**
