### PR TITLE
Fix live view no users thread

### PR DESCRIPTION
**Pull request by vzakaznikov**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en
--

* Bug fix to avoid a crash in the LIVE VIEW no users thread
* Re-enable live view tests.

Unfortunately, I could not find a way to avoid using thread detach() as it would require
additional functionality outside of the LIVE VIEW table. The problem is that dropping a table removes the last reference to the table
and table destructor is called if no more references are present.
If we hold a reference to the table in the no users thread then it will also call table
destructor on exit and therefore destructor can't join the thread as it will deadlock.

A potential solution is instead of dropping the table in the thread is to add the table to some "will be dropped list". That list would then be cleaned up by some other background task that is running outside the lifespan of the table.

### CODE REVIEW

**Comment by vzakaznikov** [comment]
Hi @KochetovNicolai, I can't seem to enable allow_experimental_live_view option for tests. 
Do you know how it can be enabled? I've tried modifying dbms/tests/server-test.xml and 
dbms/tests/clickhouse-client.xml but both attempts did not work. Thanks.

**Comment by alexey-milovidov** [comment]
@vzakaznikov Just enable it in every `.sql` test by
`SET allow_experimental_live_view = 1`
and in every `.sh` test by `--allow_experimental_live_view 1` option for clickhouse-client.

**Comment by alexey-milovidov** [comment]
There are still some issues with LIVE VIEWs:

```
2019.09.01 23:28:44.803583 [ 2476 ] {} <Fatal> BaseDaemon: ########################################
2019.09.01 23:28:44.803678 [ 2476 ] {} <Fatal> BaseDaemon: (version 19.14.1.1232) (from thread 2072) Received signal Segmentation fault (11).
2019.09.01 23:28:44.803748 [ 2476 ] {} <Fatal> BaseDaemon: Address: NULL pointer. Access: read. Address not mapped to object.
2019.09.01 23:28:44.803829 [ 2476 ] {} <Fatal> BaseDaemon: Stack trace: 0x133ce51c 0x133c0b6d 0x121ed282 0x121cfdeb 0x1219f134 0x12564fef 0x125654c0 0x12915cd0 0x12913eaa 0x777d798 0x779aee3 0x1401bf6f 0x1401cc09 0x14f18c25 0x14f138ae 0x14f1736e 0x7f2d3b06e6db 0x7f2d3a98b88f
2019.09.01 23:28:44.811798 [ 2476 ] {} <Fatal> BaseDaemon: 3. 0x133ce51c std::__1::__compressed_pair_elem<DB::BlocksBlockInputStream, 1, false>::__compressed_pair_elem<std::__1::shared_ptr<std::__1::shared_ptr<std::__1::vector<DB::Block, std::__1::allocator<DB::Block> > > >&, DB::Block&&, 0ul, 1ul>(std::__1::piecewise_construct_t, std::__1::tuple<std::__1::shared_ptr<std::__1::shared_ptr<std::__1::vector<DB::Block, std::__1::allocator<DB::Block> > > >&, DB::Block&&>, std::__1::__tuple_indices<0ul, 1ul>) /build/obj-x86_64-linux-gnu/../dbms/src/DataStreams/BlocksBlockInputStream.h:0
2019.09.01 23:28:44.816461 [ 2476 ] {} <Fatal> BaseDaemon: 4. 0x133c0b6d DB::StorageLiveView::read(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, DB::SelectQueryInfo const&, DB::Context const&, DB::QueryProcessingStage::Enum, unsigned long, unsigned int) /build/obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:0
2019.09.01 23:28:44.826266 [ 2476 ] {} <Fatal> BaseDaemon: 5. 0x121ed282 void DB::InterpreterSelectQuery::executeFetchColumns<DB::InterpreterSelectQuery::Pipeline>(DB::QueryProcessingStage::Enum, DB::InterpreterSelectQuery::Pipeline&, std::__1::shared_ptr<DB::SortingInfo> const&, std::__1::shared_ptr<DB::PrewhereInfo> const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) /build/obj-x86_64-linux-gnu/../dbms/src/Interpreters/InterpreterSelectQuery.cpp:1492
2019.09.01 23:28:44.832953 [ 2476 ] {} <Fatal> BaseDaemon: 6. 0x121cfdeb void DB::InterpreterSelectQuery::executeImpl<DB::InterpreterSelectQuery::Pipeline>(DB::InterpreterSelectQuery::Pipeline&, std::__1::shared_ptr<DB::IBlockInputStream> const&) /build/obj-x86_64-linux-gnu/../dbms/src/Interpreters/InterpreterSelectQuery.cpp:0
2019.09.01 23:28:44.836213 [ 2476 ] {} <Fatal> BaseDaemon: 7. 0x1219f134 DB::InterpreterSelectQuery::executeWithMultipleStreams() /build/obj-x86_64-linux-gnu/../dbms/src/Interpreters/InterpreterSelectQuery.cpp:0
2019.09.01 23:28:44.839268 [ 2476 ] {} <Fatal> BaseDaemon: 8. 0x12564fef DB::InterpreterSelectWithUnionQuery::executeWithMultipleStreams() /build/obj-x86_64-linux-gnu/../dbms/src/Interpreters/InterpreterSelectWithUnionQuery.cpp:0
2019.09.01 23:28:44.842386 [ 2476 ] {} <Fatal> BaseDaemon: 9. 0x125654c0 DB::InterpreterSelectWithUnionQuery::execute() /build/obj-x86_64-linux-gnu/../contrib/libcxx/include/vector:662
2019.09.01 23:28:44.845423 [ 2476 ] {} <Fatal> BaseDaemon: 10. 0x12915cd0 DB::executeQueryImpl(char const*, char const*, DB::Context&, bool, DB::QueryProcessingStage::Enum, bool) /build/obj-x86_64-linux-gnu/../dbms/src/Interpreters/executeQuery.cpp:247
2019.09.01 23:28:44.848363 [ 2476 ] {} <Fatal> BaseDaemon: 11. 0x12913eaa DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::Context&, bool, DB::QueryProcessingStage::Enum, bool) /build/obj-x86_64-linux-gnu/../dbms/src/Interpreters/executeQuery.cpp:489
2019.09.01 23:28:44.848614 [ 2476 ] {} <Fatal> BaseDaemon: 12. 0x777d798 DB::TCPHandler::runImpl() /build/obj-x86_64-linux-gnu/../dbms/programs/server/TCPHandler.cpp:0
2019.09.01 23:28:44.850499 [ 2476 ] {} <Fatal> BaseDaemon: 13. 0x779aee3 DB::TCPHandler::run() /build/obj-x86_64-linux-gnu/../dbms/programs/server/TCPHandler.cpp:0
2019.09.01 23:28:44.854449 [ 2476 ] {} <Fatal> BaseDaemon: 14. 0x1401bf6f Poco::Net::TCPServerConnection::start() /build/obj-x86_64-linux-gnu/../contrib/poco/Net/src/TCPServerConnection.cpp:57
2019.09.01 23:28:44.858461 [ 2476 ] {} <Fatal> BaseDaemon: 15. 0x1401cc09 Poco::Net::TCPServerDispatcher::run() /build/obj-x86_64-linux-gnu/../contrib/libcxx/include/atomic:1036
2019.09.01 23:28:44.862736 [ 2476 ] {} <Fatal> BaseDaemon: 16. 0x14f18c25 Poco::PooledThread::run() /build/obj-x86_64-linux-gnu/../contrib/poco/Foundation/include/Poco/Mutex_STD.h:132
2019.09.01 23:28:44.867136 [ 2476 ] {} <Fatal> BaseDaemon: 17. 0x14f138ae Poco::ThreadImpl::runnableEntry(void*) /build/obj-x86_64-linux-gnu/../contrib/poco/Foundation/include/Poco/SharedPtr.h:256
2019.09.01 23:28:44.871777 [ 2476 ] {} <Fatal> BaseDaemon: 18. 0x14f1736e void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void* (*)(void*), Poco::ThreadImpl*> >(void*) /build/obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:2648
2019.09.01 23:28:44.871848 [ 2476 ] {} <Fatal> BaseDaemon: 19. 0x7f2d3b06e6db start_thread /lib/x86_64-linux-gnu/libpthread-2.27.so
2019.09.01 23:28:44.871911 [ 2476 ] {} <Fatal> BaseDaemon: 20. 0x7f2d3a98b88f clone /lib/x86_64-linux-gnu/libc-2.27.so
```

https://clickhouse-test-reports.s3.yandex.net/6764/ba1c70add055df4fe76f1c30c516f1dfbf6923b3/stress_test_(address).html

**Comment by alexey-milovidov** [comment]
I have no idea what happens inside LIVE VIEW (why we need double shared_ptr, etc.)

```
{
    /// add user to the blocks_ptr
    std::shared_ptr<BlocksPtr> stream_blocks_ptr = blocks_ptr;
    {
        std::lock_guard lock(mutex);
        if (!(*blocks_ptr))
        {
            if (getNewBlocks())
                condition.notify_all();
        }
    }
    return { std::make_shared<BlocksBlockInputStream>(stream_blocks_ptr, getHeader()) };
}
```

But it looks like a trivial nullptr dereference of `stream_blocks_ptr`.

**Comment by alexey-milovidov** [comment]
I have to temporarily disable all LIVE VIEW tests because we need to be 100% green to discover real issues, but I expect it is possible to fix ASAP.

**Comment by alexey-milovidov** [comment]
Also please look at the PVS-Studio report: https://clickhouse-test-reports.s3.yandex.net/0/4155771106f9313610875e84cfdc2233cef10115/pvs_studio_report/pvs-studio-html-report/sources/LiveViewEventsBlockInputStream.h_31.html#ln217

**Pull request merged**
