### PR TITLE
Fix integration test for RocksDB

### PR DESCRIPTION
**Pull request by alexey-milovidov**
Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
#29347

**Comment by alexey-milovidov** [comment]
@azat See the "Remove trash" commits. I have no idea why these tests are flaky and I need your help.

**Comment by azat** [comment]
>@azat See the "Remove trash" commits. I have no idea why these tests are flaky and I need your help.

The problem here is that the server crashed after restart, so the problem is real and it is in the server (precisely in rocksdb) not in tests, will take a look.

**Comment by azat** [comment]
The problem had been fixed in https://github.com/facebook/rocksdb/commit/c4a503f3dfc297dadaf0912dbeb801bb1059b5eb

**Comment by azat** [comment]
The fix is here - #29393

**Pull request merged**
