### PR TITLE
[TEST] Do not use mmap for memory allocation directly, entrust this to jemalloc

### PR DESCRIPTION
**Pull request by azat**
Recently I've noticed that mmap()+munmap()+memory dependencies takes more time them processing the block (default max_block_size), so let's try to rely on jemalloc completely.

Note, this is just for running perf tests, and not for upstream for now, since there are other issues with doing all allocation via jemalloc directly (at least one them is memory fragmentation).

Refs: #46416

### Changelog category (leave one):
- Performance Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
[TEST] Do not use mmap for memory allocation directly, entrust this to jemalloc

Cc: @nickitat

### CODE REVIEW

**Comment by nickitat** [comment]
interesting to check those queries that from the first glance shouldn't be affected
e.g.

0.593 | 0.156 | -3.798x | -0.737 | 0.736 | random_string | 2 | SELECT count() FROM zeros(1000000) WHERE NOT ignore(randomString(1000))
-- | -- | -- | -- | -- | -- | -- | --

**Comment by azat** [comment]
Actually this is indeed was the query that was affected when I was testing my crazy idea - #45654 

It looks like it simply waits for the memory more time, not the allocation, but simply when processing block, since the code for the function was the same, but the instruction that moves to the memory eats way more time.

I'm going to look through the perf tests deeply later.

**Comment by baibaichen** [comment]
> I'm going to look through the perf tests deeply later.

@azat any progress?

**Comment by azat** [comment]
jemalloc slightly slower under some workload, in particular - huge realloc, since jemalloc do not use mremap (added in https://github.com/jemalloc/jemalloc/pull/139 but reverted in https://github.com/jemalloc/jemalloc/commit/e2deab7a751c8080c2b2cdcfd7b11887332be1bb), while ClickHouse does.

So without mremap support in jemalloc it will be slower under some workload, and hence it cannot be used as the only allocator in ClickHouse.

I will take a look later into jemalloc (or maybe it worth to try something else).

In the meantime maybe tuning MMAP_THRESHOLD is not a completely crazy idea - #46416

**Pull request closed without merging**
