### PR TITLE
Fix applying settings for FORMAT on the client

### PR DESCRIPTION
**Pull request by azat**
### Changelog category (leave one):
- Backward Incompatible Change

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix applying settings for FORMAT on the client

Previously the following query does not works correctly:

    SELECT number FROM numbers(5) SETTINGS output_format_json_array_of_rows = 1 FORMAT JSONEachRow

While this one works OK:

    SELECT number FROM numbers(5) FORMAT JSONEachRow SETTINGS output_format_json_array_of_rows = 1

The problem is in which AST those settings are stored, use the logic as executeQuery() has to apply them:

  https://github.com/ClickHouse/ClickHouse/blob/c83f701696451c5bbd856d5f5503ba1553388e5d/src/Interpreters/executeQuery.cpp#L467-L497

Note, the only problem should be with the settings for FORMAT, since client applies thoes settings (and formats) locally w/o server, while in case of i.e. HTTP it will be applied on the server and everything will works fine.

Refs: #45880 (cc @tavplubix @m1khal3v)
Follow-up for: #12480

### CODE REVIEW

**Comment by azat** [comment]
And now you can see the "reason" why it was written that way, after this patch the following query changes their behavior:

```sh
$ echo 'Custom true' | clickhouse-local -q "SELECT * FROM file('/dev/stdin', 'TSV', 'bool Bool') settings bool_true_representation='Custom true'"
Custom true
```

Before this PR `clickhouse-client`/`clickhouse-local` does not apply `SETTINGS` clause on the client side, but server does applies it, and so the server correctly parse `Custom true` as `Bool(true)`, and so client outputs `true`

But, **with this PR now client interpret `bool_true_representation` setting too, and that's why it outputs `Custom true` instead of `true` because this setting applies for both sides: deserialization and serialization.**

Also here are few other variants *without this patch, that may looks odd*:

```sh
$ echo 'Custom true' | ch local -q "SELECT * FROM file('/dev/stdin', 'TSV', 'bool Bool') format TSV settings bool_true_representation='Custom true'"
Custom true

$ echo 'Custom true' | ch local -q "SELECT * FROM file('/dev/stdin', 'TSV', 'bool Bool')" --bool_true_representation='Custom true'
Custom true
```

**Comment by azat** [comment]
@tavplubix @Avogar or maybe @alexey-milovidov maybe you have some thoughts on this?

To me it looks odd that `SETTINGS` in one place, works differently.
Maybe there should be some setting like `format_settings_context='none|both|serialization|deserilization' (or input/output)`?

**Review by tavplubix — APPROVED** [review]
I like the new behavior more than the old one, thank you!

**Comment by tavplubix** [comment]
I think we can simply update the tests

**Comment by azat** [comment]
>I think we can simply update the tests

I am a bit worried about serialization vs deserialization. But OK, let's try.

**Comment by tavplubix** [comment]
Integration tests (asan) [3/6] - https://github.com/ClickHouse/ClickHouse/issues/45437

**Pull request merged**
