### PR TITLE
MultiVersion: change mutex to lock-free

### PR DESCRIPTION
**Pull request by k-morozov**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
- MultiVersion: replace lock_guard to atomic op

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by k-morozov** [comment]
Current version of MultiVersion uses std::lock_guard. I suppose that there are 2 ways to improve:
1. std::shared_lock for get / std::unique_lock for set.
2. use std::atomic<std::shared_ptr<T>>.
As far as I can tell there is no support the second way for clang (https://en.cppreference.com/w/cpp/compiler_support/20) althought we can use std::atomic_load/std::atomic_store even thought it is deprecated in C++20.

**Comment by rschu1ze** [comment]
Funny, I thought about doing the same when I read the code a couple of days.

**Comment by rschu1ze** [comment]
Let's first check if there is any impact on performance tests.

>     1. std::shared_lock for get / std::unique_lock for set.
> 
>     2. use std::atomic<std::shared_ptr>.
>        As far as I can tell there is no support the second way for clang (https://en.cppreference.com/w/cpp/compiler_support/20) althought we can use std::atomic_load/std::atomic_store even thought it is deprecated in C++20.

The second one looks like the way forward but since Clang doesn't support it (and ClickHouse theoretically supports building with past three Clang versions) a TODO comment would be fine.

**Review by rschu1ze — APPROVED** [review]

**Comment by rschu1ze** [comment]
Performance results look okay.

ClickHouse Integration Tests (tsan) [6/6]: #46056

ClickHouse Stateless Tests (release, Wide Parts Enabled):
- 00002_log_and_exception_messages_formatting: Failed because the database log was a bit more noisy than usual in this run.

**Comment by k-morozov** [comment]
> Performance results look okay.

@rschu1ze could you share the link of perfomance results pls? can't find where is it.

**Comment by rschu1ze** [comment]
https://s3.amazonaws.com/clickhouse-test-reports/46057/ff051629044833667e3ebc65655d39f3921bb49a/performance_comparison_[2/4]/report.html

https://s3.amazonaws.com/clickhouse-test-reports/46057/ff051629044833667e3ebc65655d39f3921bb49a/performance_comparison_[3/4]/report.html

https://s3.amazonaws.com/clickhouse-test-reports/46057/ff051629044833667e3ebc65655d39f3921bb49a/performance_comparison_[4/4]/report.html

https://s3.amazonaws.com/clickhouse-test-reports/46057/ff051629044833667e3ebc65655d39f3921bb49a/performance_comparison_[1/4]/report.html

**Pull request merged**
