### PR TITLE
Throw UNSUPPORTED_METHOD for static storages

### PR DESCRIPTION
**Pull request by vdimir**
### Changelog category (leave one):

- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
* Static storages (such as DiskWeb) throws `UNSUPPORTED_METHOD` error on write attempt instead of `TABLE_IS_READ_ONLY`

In other places `TABLE_IS_READ_ONLY` may indicate some non-healthy replica state, while having read only `web` disk is expected. Any ~objectives~ objections?

### CODE REVIEW

**Comment by robot-ch-test-poll1** [comment]
*This is an automated comment for commit d0ad81b9a05bdb690c948d23125f0aab48326180 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/61376/d0ad81b9a05bdb690c948d23125f0aab48326180/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

**Comment by nikitamikhaylov** [comment]
No objectives, throwing an exception with error codes `TABLE_IS_READONLY` will also increase the counter in `system.errors` which will be confusing.

**Comment by Algunenano** [comment]
> Any objectives?
> No objectives

Objection, your honor. :smile:

`UNSUPPORTED_METHOD` seems better to me, since `TABLE_IS_READONLY` is mostly used for situations where the table is usually RW

**Review by kssenii — APPROVED** [review]

**Comment by vdimir** [comment]
Need to adjust tests that expect specific error code

**Pull request closed without merging**
