### PR TITLE
Fix cctz linking with dirty hack

### PR DESCRIPTION
**Pull request by alesapin**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Build/Testing/Packaging Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Now parts of linker command for `cctz` library will not be shuffled with other libraries.

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]

**Comment by qoega** [comment]
```
FAILED: base/common/tests/date_lut2 
: && /usr/bin/ccache /usr/bin/clang++-10  -fdiagnostics-color=always -std=c++2a -fsized-deallocation  -gdwarf-aranges -pipe -msse4.1 -msse4.2 -mpopcnt   -Wall -Wno-unused-command-line-argument  -fdiagnostics-absolute-paths -Werror -Wextra -Wpedantic -Wno-vla-extension -Wno-zero-length-array -Wcomma -Wconditional-uninitialized -Wcovered-switch-default -Wdeprecated -Wembedded-directive -Wempty-init-stmt -Wextra-semi-stmt -Wextra-semi -Wgnu-case-range -Winconsistent-missing-destructor-override -Wnewline-eof -Wold-style-cast -Wrange-loop-analysis -Wredundant-parens -Wreserved-id-macro -Wshadow-field -Wshadow-uncaptured-local -Wshadow -Wstring-plus-int -Wundef -Wunreachable-code-return -Wunreachable-code -Wunused-exception-parameter -Wunused-macros -Wunused-member-function -Wzero-as-null-pointer-constant -Weverything -Wno-c++98-compat-pedantic -Wno-c++98-compat -Wno-c99-extensions -Wno-conversion -Wno-ctad-maybe-unsupported -Wno-deprecated-dynamic-exception-spec -Wno-disabled-macro-expansion -Wno-documentation-unknown-command -Wno-double-promotion -Wno-exit-time-destructors -Wno-float-equal -Wno-global-constructors -Wno-missing-prototypes -Wno-missing-variable-declarations -Wno-nested-anon-types -Wno-packed -Wno-padded -Wno-return-std-move-in-c++11 -Wno-shift-sign-overflow -Wno-sign-conversion -Wno-switch-enum -Wno-undefined-func-template -Wno-unused-template -Wno-vla -Wno-weak-template-vtables -Wno-weak-vtables -O2 -g -DNDEBUG -O3  -fno-pie  -fuse-ld=lld -rdynamic -Wl,--gdb-index -Wl,--no-undefined -Wl,-no-pie   -rdynamic src/CMakeFiles/clickhouse_malloc.dir/Common/malloc.cpp.o base/common/tests/CMakeFiles/date_lut2.dir/date_lut2.cpp.o  -o base/common/tests/date_lut2  src/libclickhouse_new_delete.a base/common/libcommon.a -ldl src/libclickhouse_common_io.a base/common/libcommon.a contrib/FastMemcpy/libFastMemcpy.a contrib/poco-cmake/Net/SSL/lib_poco_net_ssl.a contrib/poco-cmake/Net/lib_poco_net.a contrib/poco-cmake/Crypto/lib_poco_crypto.a contrib/poco-cmake/Util/lib_poco_util.a contrib/poco-cmake/JSON/lib_poco_json.a contrib/poco-cmake/JSON/lib_poco_json_pdjson.a contrib/poco-cmake/XML/lib_poco_xml.a contrib/poco-cmake/XML/lib_poco_xml_expat.a contrib/replxx-cmake/libreplxx.a contrib/fmtlib-cmake/libfmt.a contrib/cctz-cmake/libcctz.a -Wl,--whole-archive contrib/cctz-cmake/libtzdata.a -Wl,--no-whole-archive contrib/cityhash102/libcityhash.a contrib/boost-cmake/libboost_system_internal.a contrib/poco-cmake/Foundation/lib_poco_foundation.a contrib/poco-cmake/Foundation/lib_poco_foundation_pcre.a src/Common/StringUtils/libstring_utils.a base/widechar_width/libwidechar_width.a contrib/double-conversion-cmake/libdouble-conversion.a contrib/ryu-cmake/libryu.a contrib/re2/libre2.a contrib/re2_st/libre2_st.a contrib/libcpuid-cmake/libcpuid.a contrib/boost-cmake/libboost_program_options_internal.a contrib/croaring/libroaring.a contrib/libhdfs3-cmake/libhdfs3.a contrib/libgsasl/liblibgsasl.a contrib/libxml2-cmake/liblibxml2.a contrib/zlib-ng/libzlib.a contrib/protobuf/libprotobuf.a -pthread contrib/aws-s3-cmake/libaws_s3.a contrib/aws-s3-cmake/libaws_s3_checksums.a contrib/curl-cmake/libcurl.a contrib/openssl-cmake/libssl.a contrib/openssl-cmake/libcrypto.a contrib/brotli-cmake/libbrotli.a contrib/jemalloc-cmake/libjemalloc.a -Wl,--start-group base/glibc-compatibility/libglibc-compatibility.a contrib/libcxx-cmake/libcxx.a contrib/libcxxabi-cmake/libcxxabi.a contrib/libunwind-cmake/libunwind.a -Wl,--end-group -nodefaultlibs /usr/lib/llvm-10/lib/clang/10.0.1/lib/linux/libclang_rt.builtins-x86_64.a  -lc -lm -lrt -lpthread -ldl && :
clang: error: no such file or directory: 'contrib/cctz-cmake/libtzdata.a'
```

**Comment by alesapin** [comment]
Waiting only for build.

**Comment by alexey-milovidov** [comment]
Also need to add the suffix for debug build, so the library will be named `libcctzd.a`.

**Comment by alexey-milovidov** [comment]
PS. I don't know why we need this suffix, probably it's better to get rid of it.

**Comment by alesapin** [comment]
Let's try combination of OBJECT library and INTERFACE linking.

**Comment by alesapin** [comment]
> Let's try combination of OBJECT library and INTERFACE linking.

It doesn't work.

**Comment by alesapin** [comment]
Build passed!

**Pull request merged**
