### PR TITLE
Blind performance fix of read_in_order_many_parts

### PR DESCRIPTION
**Pull request by alesapin**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Performance Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Improved performance of merges assignment in MergeTree table engines. Shouldn't be visible for the user.

### CODE REVIEW

**Comment by alesapin** [comment]
Actually I cannot reproduce this error locally without a heavy background process like build. Perf top in bad case:
```
    17.52%    17.52%  BackgrProcPool   libm-2.27.so        [.] __log1p
    10.33%    10.33%  BackgrProcPool   clickhouse_clang    [.] DB::SimpleMergeSelector::select
     6.13%     6.13%  BackgrProcPool   clickhouse_clang    [.] DB::MergeTreeDataMergerMutator::selectPartsToMerge
     6.03%     0.03%  QueryPipelineEx  [kernel.kallsyms]   [k] entry_SYSCALL_64_after_hwframe
```

**Comment by alexey-milovidov** [comment]
`log1p` is needed for better precision of `log(1 + x)` expression for very small x.
But in our code we don't need it because x is integer.

Could you also try to replace log1p to log(1 + x) to see what will change? (and add a comment)

**Review by alexey-milovidov — COMMENTED** [review]
`double mapPiecewiseLinearToUnit`
- make static?

**Comment by alesapin** [comment]
Good idea, but let's look at performance tests without any additional changes.

**Comment by alesapin** [comment]
Didn't help:
```
create  1       3.8490941524505615      OPTIMIZE TABLE mt_100_parts FINAL
create  0       3.725403070449829       OPTIMIZE TABLE mt_100_parts FINAL
create  0       154.7758858203888       OPTIMIZE TABLE mt_1000_parts FINAL
create  1       160.87323808670044      OPTIMIZE TABLE mt_1000_parts FINAL
```

**Comment by alesapin** [comment]
> `double mapPiecewiseLinearToUnit`
> 
>     * make static?

It's already in the anonymous namespace.

**Comment by alesapin** [comment]
On my local machine (without thin lto):
```
create  0       26.846017122268677      INSERT INTO mt_100_parts SELECT number, rand() % 10000, rand() FROM numbers_mt(100000000)
create  0       71.50743651390076       INSERT INTO mt_1000_parts SELECT number, rand() % 10000, rand() FROM numbers_mt(100000000)
create  0       4.320169448852539       OPTIMIZE TABLE mt_100_parts FINAL
create  0       5.594881296157837       OPTIMIZE TABLE mt_1000_parts FINAL
```

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
Did not help.

**Comment by alesapin** [comment]
Actually it helps, but not too much:
```
create  1       22.754340648651123      INSERT INTO mt_100_parts SELECT number, rand() % 10000, rand() FROM numbers_mt(100000000)
create  0       23.076173067092896      INSERT INTO mt_100_parts SELECT number, rand() % 10000, rand() FROM numbers_mt(100000000)
create  1       41.58436679840088       INSERT INTO mt_1000_parts SELECT number, rand() % 10000, rand() FROM numbers_mt(100000000)
create  0       42.422518730163574      INSERT INTO mt_1000_parts SELECT number, rand() % 10000, rand() FROM numbers_mt(100000000)
create  1       3.769554615020752       OPTIMIZE TABLE mt_100_parts FINAL
create  0       3.7436928749084473      OPTIMIZE TABLE mt_100_parts FINAL
create  1       106.91889381408691      OPTIMIZE TABLE mt_1000_parts FINAL
create  0       161.07886576652527      OPTIMIZE TABLE mt_1000_parts FINAL
```

**Comment by alesapin** [comment]
Now I cannot reproduce anything even with concurrent clickhouse build.

**Comment by alesapin** [comment]
Still doesn't help:
```
create  1       23.091315507888794      INSERT INTO mt_100_parts SELECT number, rand() % 10000, rand() FROM numbers_mt(100000000)
create  0       23.331719875335693      INSERT INTO mt_100_parts SELECT number, rand() % 10000, rand() FROM numbers_mt(100000000)
create  1       42.945871353149414      INSERT INTO mt_1000_parts SELECT number, rand() % 10000, rand() FROM numbers_mt(100000000)
create  0       43.1971480846405        INSERT INTO mt_1000_parts SELECT number, rand() % 10000, rand() FROM numbers_mt(100000000)
create  1       3.8705220222473145      OPTIMIZE TABLE mt_100_parts FINAL
create  0       3.787457227706909       OPTIMIZE TABLE mt_100_parts FINAL
create  1       123.40444660186768      OPTIMIZE TABLE mt_1000_parts FINAL
create  0       171.27474737167358      OPTIMIZE TABLE mt_1000_parts FINAL
```

**Comment by alesapin** [comment]
```
    20.39%    20.39%  BackgrProcPool   clickhouse          [.] DB::SimpleMergeSelector::select                                                                                                                       
    15.64%    15.64%  BackgrProcPool   clickhouse          [.] log                                                                                                                                                   
     7.33%     7.33%  BackgrProcPool   clickhouse          [.] DB::MergeTreeDataMergerMutator::selectPartsToMerge                                                                                                    
     5.82%     5.82%  BackgrProcPool   clickhouse          [.] DB::MergingSortedAlgorithm::mergeImpl<DB::SortingHeap<DB::SortCursor> >                                                                               
+    5.31%     0.04%  BackgrProcPool   [kernel.kallsyms]   [k] entry_SYSCALL_64_after_hwframe                                                                                                                        
     5.28%     5.28%  BackgrProcPool   clickhouse          [.] std::__1::__function::__func<DB::StorageMergeTree::merge(bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > c
+    5.25%     0.06%  BackgrProcPool   [kernel.kallsyms]   [k] do_syscall_64                                                                                                                                         
     4.74%     4.74%  BackgrProcPool   clickhouse          [.] std::__1::__tuple_less<5ul>::operator()<std::__1::tuple<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, 
     3.53%     3.53%  BackgrProcPool   clickhouse          [.] DB::IMergeTreeDataPart::shallParticipateInMerges                                                                                                      
     3.20%     3.20%  BackgrProcPool   clickhouse          [.] DB::MergeTreeData::getTotalActiveSizeInBytes                                                                                                          
     3.17%     3.17%  BackgrProcPool   clickhouse          [.] std::__1::__merge<DB::MergeTreeData::LessDataPart&, boost::multi_index::detail::bidir_node_iterator<boost::multi_index::detail::ordered_index_node<boo
     3.01%     3.01%  BackgrProcPool   clickhouse          [.] DB::IVolume::getDisk                                                                                                                                  
```

**Comment by alesapin** [comment]
Annotated SimpleMergeSelector::select 
https://gist.github.com/alesapin/f3180cca7b7a2fe42d2d9c6eeedbd0e4

**Comment by alesapin** [comment]
```
create  0       3.7996957302093506      OPTIMIZE TABLE mt_100_parts FINAL
create  1       3.7263293266296387      OPTIMIZE TABLE mt_100_parts FINAL
create  1       4.377586126327515       OPTIMIZE TABLE mt_1000_parts FINAL
create  0       147.31911087036133      OPTIMIZE TABLE mt_1000_parts FINAL
```
ok in new version

**Review by alexey-milovidov — APPROVED** [review]

**Pull request merged**
