### PR TITLE
merge_max_block_size in settings

### PR DESCRIPTION
**Pull request by 4ertus2**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Category (leave one):
- Improvement

Short description (up to few sentences):
Add merge_max_block_size setting to MergeTreeSettings

### CODE REVIEW

**Comment by 4ertus2** [comment]
closes #5034

**Comment by alexey-milovidov** [comment]
`No space left on device.` - infrastructure issue, @alesapin

**Review by alexey-milovidov — CHANGES_REQUESTED** [review]
Why it's named `default_merge_block_size` instead of `merge_max_block_size`?

**Comment by 4ertus2** [comment]
> Why it's named `default_merge_block_size` instead of `merge_max_block_size`?

Fixed

**Review by alexey-milovidov — APPROVED** [review]

**Comment by BayoNet** [comment]
@4ertus2  What user cases does this setting cover?

**Pull request merged**
