### PR TITLE
Remove testmode option, enable it unconditionally

### PR DESCRIPTION
**Pull request by kssenii**
Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Remove testmode option, enable it unconditionally

### CODE REVIEW

**Review by KochetovNicolai — APPROVED** [review]

**Comment by kssenii** [comment]
@Mergifyio update

**Comment by alexey-milovidov** [comment]
@KochetovNicolai let's continue.

**Comment by KochetovNicolai** [comment]
It's ok to me, there are still a few test which fail for reason

**Comment by kssenii** [comment]
> Stateless tests (release, DatabaseReplicated, actions) [1/2] — fail: 1

--  01165_lost_part_empty_partition (`DB::Exception: Received from localhost:9000. DB::Exception: Existing table metadata in ZooKeeper differs in partition key expression. Stored in ZooKeeper (query: create table rmt1 (n UInt8, m Int32, d Date, t DateTime) engine=ReplicatedMergeTree('/test/01165/{database}/rmt', '1') order by n partition by (n, m, d, t);)`) -- not related as even no test hints in this query

> Stateless tests (aarch64, actions) — fail: 3

-- failed tests also do not even contain test hints - not related

**Pull request merged**
