### PR TITLE
replace back clickhouse su with sudo -u in start command

### PR DESCRIPTION
**Pull request by ekonkov**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Replace back `clickhouse su` command with `sudo -u` in start in order to respect limits in `/etc/security/limits.conf`.

----
Limits configured in `/etc/security/limits.d` are not respected by `clickhouse su` command. See below. Propose to revert back to old command and use new command only in docker-related stuff as intended.

```
root@localhost.com:~# sudo -u clickhouse /bin/bash -c "ulimit -Hn"
1048576
root@localhost.com:~# /usr/bin/clickhouse su clickhouse /bin/bash -c "ulimit -Hn"
1048576
root@localhost.com:~#
root@localhost.com:~# ulimit -n 10500
root@localhost.com:~# ulimit -Hn
10500
root@localhost.com:~# sudo -u clickhouse /bin/bash -c "ulimit -Hn"
1048576
root@localhost.com:~# /usr/bin/clickhouse su clickhouse /bin/bash -c "ulimit -Hn"
10500
root@localhost.com:~#

root@localhost.com:~# cat /etc/security/limits.d/*
clickhouse soft nofile 1048576
clickhouse hard nofile 1048576
www-data soft nofile 102400
www-data hard nofile 102400
mysql soft nofile 1048576
mysql hard nofile 1048576
mysql soft memlock -1
mysql hard memlock -1
root soft nofile 1048576
root hard nofile 1048576
root soft memlock -1
root hard memlock -1
* soft nofile 1048576
* hard nofile 1048576
* soft memlock -1
* hard memlock -1
root@localhost.com:~#
```

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
There are some troubles with sudo in Docker.

**Comment by ekonkov** [comment]
I understand there are sudo-related issues with Docker, but as far as I understand `clickhouse su` [used in Docker](https://github.com/ClickHouse/ClickHouse/blob/master/docker/server/entrypoint.sh#L175) as [intended](https://github.com/ClickHouse/ClickHouse/blob/master/programs/su/su.cpp#L21-L28). This patch affects only the way how clickhouse-server start on hardware server [by init system](https://github.com/ClickHouse/ClickHouse/blob/master/packages/clickhouse-server.init#L79).

Please reconsider this patch. It should fix support case number 00001430.

**Comment by alexey-milovidov** [comment]
Need to add a comment in the code.

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
> Run Check — Changelog category is empty

**Comment by ekonkov** [comment]
Are there any problems with this PR?
@alexey-milovidov

**Comment by KochetovNicolai** [comment]
test_disks_app_func_ls was broken on master at the moment of last check. Unrelated.

**Comment by alexey-milovidov** [comment]
This PR is absolutely wrong.

The `sudo` tool can:
- not exist in the system;
- be unnecessarily complex (run JavaScript plugins, make network requests).

`sudo` is intended for users, not programs. We should not use it.

**Comment by ekonkov** [comment]
Hi Alexey, 

I totally agree with you.

But replacement should respect limits in ```/etc/security/limits.conf```.

**Pull request merged**
