### PR TITLE
Ensure that llvm-symbolizer is used for symbolizing sanitizer reports

### PR DESCRIPTION
**Pull request by azat**
Since you don't want to fallback to addr2line:

    # addr2line
    $ time /bin/test
    set_flag_impl: Success
    set_flag_if: Success
    /usr/bin/addr2line: DWARF error: invalid or unhandled FORM value: 0x23
    ==================
    WARNING: ThreadSanitizer: data race (pid=18)
    ...
    real    3m8.580s
    user    0m21.967s
    sys     0m40.628s

    # llvm-symbolizer
    $ time ./test
    set_flag_impl: Success
    set_flag_if: Success
    ==================
    WARNING: ThreadSanitizer: data race (pid=24884)
    real    0m0.028s
    user    0m0.003s
    sys     0m0.006s

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by robot-ch-test-poll4** [comment]
*This is an automated comment for commit 84c2b2c5f6275cf088c48d32856bb0873411b0ea with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/66495/84c2b2c5f6275cf088c48d32856bb0873411b0ea/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/63186/b1fd7868e507263152dda28b5efafdf0959629e7/docs_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
@azat, any idea why builds barely started in 7 hours?

**Comment by alexey-milovidov** [comment]
@azat, everything has failed.

**Comment by antonio2368** [comment]
@azat there was an issue with Azure setup which explains all the failures, can you merge with master to restart the tests?

**Comment by alexey-milovidov** [comment]
@azat, tests have failed.

**Comment by azat** [comment]
Lots of issue had been fixed, let's rebase

>Stress test (tsan) — Found signal in gdb.log

- https://github.com/ClickHouse/ClickHouse/pull/66722

> Stress test (debug) — Hung check failed, possible deadlock found (see hung_check.log)

- https://github.com/ClickHouse/ClickHouse/pull/67751

**Comment by azat** [comment]
Ci is green

**Pull request merged**
