### PR TITLE
Fix BSONEachRow parallel parsing when document size is invalid

### PR DESCRIPTION
**Pull request by Avogar**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in official stable or prestable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix BSONEachRow parallel parsing when document size is invalid

### CODE REVIEW

**Review by serxa — APPROVED** [review]
LGTM

**Comment by tavplubix** [comment]
> Stateless tests flaky check (asan) — fail: 5

Sorry, I have to revert this. 

CI DB: [link](https://play.clickhouse.com/play?user=play#d2l0aCAKJyUwMjU4OV9ic29uX2ludmFsaWRfZG9jdW1lbnRfc2l6ZSUnIGFzIG5hbWVfcGF0dGVybiwKJyUlJyBhcyBjb250ZXh0X3BhdHRlcm4sCicyMDIyLTA2LTAxJyBhcyBzdGFydF9kYXRlLAooNDU0NjEpIGFzIG5vaXN5X3BycywKKCdTdGF0ZWxlc3MgdGVzdHMgKGFzYW4pJywgJ1N0YXRlbGVzcyB0ZXN0cyAoYWRkcmVzcyknLCAnU3RhdGVsZXNzIHRlc3RzIChhZGRyZXNzLCBhY3Rpb25zKScpIGFzIGJhY2twb3J0X2FuZF9yZWxlYXNlX3NwZWNpZmljX2NoZWNrcwpzZWxlY3QgCnRvU3RhcnRPZkRheShjaGVja19zdGFydF90aW1lKSBhcyBkLApjb3VudCgpLCAgZ3JvdXBVbmlxQXJyYXkocHVsbF9yZXF1ZXN0X251bWJlciksIGFueShyZXBvcnRfdXJsKQpmcm9tIGNoZWNrcyB3aGVyZSBzdGFydF9kYXRlIDw9IGNoZWNrX3N0YXJ0X3RpbWUgYW5kIHB1bGxfcmVxdWVzdF9udW1iZXIgbm90IGluIAooc2VsZWN0IHB1bGxfcmVxdWVzdF9udW1iZXIgYXMgcHJuIGZyb20gY2hlY2tzIHdoZXJlIHBybiE9MCBhbmQgc3RhcnRfZGF0ZSA8PSBjaGVja19zdGFydF90aW1lIGFuZCBjaGVja19uYW1lIGluIGJhY2twb3J0X2FuZF9yZWxlYXNlX3NwZWNpZmljX2NoZWNrcykgCmFuZCB0ZXN0X25hbWUgbGlrZSBuYW1lX3BhdHRlcm4gYW5kIHRlc3RfY29udGV4dF9yYXcgaWxpa2UgY29udGV4dF9wYXR0ZXJuCmFuZCBwdWxsX3JlcXVlc3RfbnVtYmVyIG5vdCBpbiBub2lzeV9wcnMKYW5kIHRlc3Rfc3RhdHVzIGluICgnRkFJTCcsICdGTEFLWScsICdmYWlsdXJlJykgZ3JvdXAgYnkgZCBvcmRlciBieSBkIGRlc2M=)

**Comment by Avogar** [comment]
> Sorry, I have to revert this.

Didn't noticed that failure, my fault. Thanks for reverting! I will fix it.

**Comment by Avogar** [comment]
Oh, it's because of settings randomization (`max_threads=2` and no parallel parsing was used).

**Pull request merged**
