### PR TITLE
Integrate with maxminddb

### LINKED ISSUE #50299: integration with maxmind database
https://github.com/maxmind/libmaxminddb  

MaxMindDB is a database format and API (Application Programming Interface) designed to provide efficient and accurate geolocation data. Developed by MaxMind, this database is commonly used for IP geolocation, which helps in identifying the geographic location of an IP address. MaxMindDB is often used in applications such as fraud detection, content customization, traffic analysis, and digital rights management.

### PR DESCRIPTION
**Pull request by taiyang-li**
### Changelog category (leave one):
- New Feature

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Integrate with maxminddb, close https://github.com/ClickHouse/ClickHouse/issues/50299

### CODE REVIEW

**Comment by robot-clickhouse-ci-2** [comment]
This is an automated comment for commit 3346cb63386bf698df0bc82e91a72002ef847c6e with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/50304/3346cb63386bf698df0bc82e91a72002ef847c6e/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Docs Check</td><td>Builds and tests the documentation</td><td>🟡 pending</td></tr>
</table>

**Comment by alexey-milovidov** [comment]
I see that it is unused in this pull request (only added to the build system).

**Comment by taiyang-li** [comment]
> I see that it is unused in this pull request (only added to the build system).

I will add usage of maxminddb soon.

**Comment by taiyang-li** [comment]
@alexey-milovidov do you have time to review this pr, thanks!

**Comment by alexey-milovidov** [comment]
Ok, but it does not build:

> Sun 06 11:00:04 /build/src/Storages/MaxMindDB/utils.h:114:28: error: Potential leak of memory pointed to by 'key' [clang-analyzer-unix.Malloc,-warnings-as-errors]

Let's make checks green, then I will ask team mates who want to review.

**Comment by alexey-milovidov** [comment]
Adding a C library and a table engine is way too much of a liability. But it should be possible to integrate with the existing methods, such as the `ip_trie` dictionary.

**Pull request closed without merging**
