### PR TITLE
fix antlr insertStmt for issue 63657

### PR DESCRIPTION
**Pull request by zzyReal666**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
- Support INSERT with VALUES in the ANTLR syntax file

image

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

<details>
    <summary>Modify your CI run</summary>

**NOTE:** If your merge the PR with modified CI you **MUST KNOW** what you are doing
**NOTE:** Checked options will be applied if set before CI RunConfig/PrepareRunConfig step

#### Include tests (required builds will be added automatically):
- [ ]  Fast test
- [ ]  Integration Tests
- [ ]  Stateless tests
- [ ]  Stateful tests
- [ ]  Unit tests
- [ ]  Performance tests
- [ ]  All with ASAN
- [ ]  All with TSAN
- [ ]  All with Analyzer
- [ ]  All with Azure
- [ ]  Add your option here

#### Exclude tests:
- [ ]  Fast test
- [ ]  Integration Tests
- [ ]  Stateless tests
- [ ]  Stateful tests
- [ ]  Performance tests
- [ ]  All with ASAN
- [ ]  All with TSAN
- [ ]  All with MSAN
- [ ]  All with UBSAN
- [ ]  All with Coverage
- [ ]  All with Aarch64
- [ ]  Add your option here

#### Extra options:
- [ ]  do not test (only style check)
- [ ]  disable merge-commit (no merge from master before tests)
- [ ]  disable CI cache (job reuse)

#### Only specified batches in multi-batch jobs:
- [ ]  1
- [ ]  2
- [ ]  3
- [ ]  4

</details>

### CODE REVIEW

**Comment by nikitamikhaylov** [comment]
@zzyReal666 FYI this file is not being used in ClickHouse anyhow and already outdated.

**Comment by robot-ch-test-poll** [comment]
*This is an automated comment for commit 4701431ee89192444f9f08555617d9960af409f8 with description of existing statuses. It's updated for the latest CI running*

[❌ Click here](https://s3.amazonaws.com/clickhouse-test-reports/63811/4701431ee89192444f9f08555617d9960af409f8/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td><a href="https://github.com/ClickHouse/ClickHouse/blob/master/.github/PULL_REQUEST_TEMPLATE.md?plain=1">❌ failure</a></td></tr>
<tbody>
</table>

**Comment by zzyReal666** [comment]
> @zzyReal666 FYI this file is outdated and not being used in ClickHouse anyhow (we have our own lexer/parser and failed to integrate with ANTLR).
> 
> BTW, what is the name of the app you are using to with ANTLR rules?

- First of all ,I clearly understand that Antlr is not used in ClickHouse itself. As issue 63657 https://github.com/ClickHouse/ClickHouse/issues/63657
- Is this file(g4) no longer accepting updates?
- As for the app that can graphically display the ANTLR rules, it is actually a plug-in for the IDE. IDE named 'Clion',for C and C++,plugin named 'ANTLR v4'.

image
image

**Comment by Algunenano** [comment]
> Is this file(g4) no longer accepting updates?

We do accept updates. Thanks!

**Review by Algunenano — APPROVED** [review]

**Pull request merged**
