### PR TITLE
ISSUES-4006 try fix materialize mysql database integration test

### PR DESCRIPTION
**Pull request by zhang2014**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Detailed description / Documentation draft:
https://github.com/ClickHouse/ClickHouse/issues/12508#issuecomment-674507363

### CODE REVIEW

**Comment by zhang2014** [comment]
Update Log:

2020.08.16 12:32:14.507164 [ 36 ] {f8cd8773-f5b3-42ca-b464-0e45a3fd419e} <Debug> executeQuery: (from 172.19.0.1:46302) SELECT * FROM test_database.test_table_2 ORDER BY id FORMAT TSV
2020.08.16 12:32:14.507624 [ 36 ] {f8cd8773-f5b3-42ca-b464-0e45a3fd419e} <Trace> ContextAccess (default): Access granted: SELECT(add_column_2, id, add_column_1, add_column_3, add_column_4) ON test_database.test_table_2
2020.08.16 12:32:14.507730 [ 36 ] {f8cd8773-f5b3-42ca-b464-0e45a3fd419e} <Debug> test_database.test_table_2 (SelectExecutor): Key condition: unknown
2020.08.16 12:32:14.507743 [ 36 ] {f8cd8773-f5b3-42ca-b464-0e45a3fd419e} <Debug> test_database.test_table_2 (SelectExecutor): MinMax index condition: unknown
2020.08.16 12:32:14.507754 [ 36 ] {f8cd8773-f5b3-42ca-b464-0e45a3fd419e} <Trace> test_database.test_table_2 (SelectExecutor): Not using primary index on part 0_1_1_0
2020.08.16 12:32:14.507764 [ 36 ] {f8cd8773-f5b3-42ca-b464-0e45a3fd419e} <Debug> test_database.test_table_2 (SelectExecutor): Selected 1 parts by date, 1 parts by key, 1 marks by primary key, 1 marks to read from 1 ranges
2020.08.16 12:32:14.507801 [ 36 ] {f8cd8773-f5b3-42ca-b464-0e45a3fd419e} <Trace> MergeTreeSelectProcessor: Reading 1 ranges from part 0_1_1_0, approx. 8192 rows starting from 0
2020.08.16 12:32:14.508741 [ 36 ] {f8cd8773-f5b3-42ca-b464-0e45a3fd419e} <Trace> InterpreterSelectQuery: FetchColumns -> Complete
2020.08.16 12:32:14.510762 [ 74 ] {f8cd8773-f5b3-42ca-b464-0e45a3fd419e} <Debug> MergingSortedTransform: Merge sorted 3 blocks, 2 rows in 0 sec.

2020.08.16 12:35:50.628051 [ 36 ] {f8cd8773-f5b3-42ca-b464-0e45a3fd419e} <Information> executeQuery: Read 2 rows, 58.00 B in 216.120814259 sec., 0 rows/sec., 0.27 B/sec.
2020.08.16 12:35:50.628149 [ 36 ] {f8cd8773-f5b3-42ca-b464-0e45a3fd419e} <Debug> MemoryTracker: Peak memory usage (for query): 0.00 B.

**Comment by tavplubix** [comment]
Btw, what is the reason of test failure? Seems like `SELECT` query hangs until connection to MySQL is lost, but I don't understand how selecting from internal MergeTree is related to background replication thread.

**Comment by zhang2014** [comment]
@tavplubix 
I'm not sure what the reason for this failure. I've run 100 times this test in my env(so far I've run 30 times and not found failure.) I will wait  run test result. maybe we could comment the relevant SELECT first?

**Comment by tavplubix** [comment]
For unknown reason it fails only in CI environment, I cannot reproduce the failure on my machine too. I've disabled the test in master to suppress annoying failures in other PRs.

**Review by tavplubix — APPROVED** [review]
Ok, looks like it's fixed

**Comment by zhang2014** [comment]
Ok,  I will keep observing after merged.

**Pull request merged**
