### PR TITLE
Create ch/chc/chl symlinks by cmake as well (for develop mode)

### PR DESCRIPTION
**Pull request by azat**
Before, they had been created only by install target.

Follow-up for: #56634 (cc @alexey-milovidov )

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by robot-clickhouse-ci-2** [comment]
*This is an automated comment for commit c5bf722ee2d2b50d1b0691112b769e3e67612214 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/58609/c5bf722ee2d2b50d1b0691112b769e3e67612214/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/58609/c5bf722ee2d2b50d1b0691112b769e3e67612214/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Review by SmitaRKulkarni — APPROVED** [review]
LGTM

**Comment by azat** [comment]
It will be in conflict with another cmake cleanup, so can someone take a look? This patch should be pretty straightforward.

**Comment by alexey-milovidov** [comment]
We are trying to do as little as possible with CMake - it is too powerful, and we want to deliberately ignore 99.99% of what CMake offers. Interesting, why do we need to create symlinks with CMake?

**Comment by azat** [comment]
At least it is useful for development.

**Pull request merged**
