### PR TITLE
Try to stabilize test 02346_full_text_search.sql

### PR DESCRIPTION
**Pull request by rschu1ze**
Failure, e.g. https://s3.amazonaws.com/clickhouse-test-reports/0/f3fa3d868cb9957eeca6b5d5fd653234f5db5b45/stateless_tests__release__databaseordinary_.html :

    "Cannot quickly remove directory /var/lib/clickhouse/data/test_ggwgonnk/tab/delete_tmp_all_1_1_0 by removing files; fallback to recursive removal. Reason: Code: 566. DB::ErrnoException: Cannot rmdir /var/lib/clickhouse/data/test_ggwgonnk/tab/delete_tmp_all_1_1_0, errno: 39, strerror: Directory not empty. (CANNOT_RMDIR) (version 23.2.1.1427 (official build))"

The issue did not reproduce in a local debug or release builds.

I noticed that it happens only with "DatabaseOrdinary" test profiles: https://play.clickhouse.com/play?user=play#U0VMRUNUIGNoZWNrX3N0YXJ0X3RpbWUsIGNoZWNrX25hbWUsIHRlc3RfbmFtZSwgcmVwb3J0X3VybApGUk9NIGNoZWNrcwpXSEVSRSBjaGVja19zdGFydF90aW1lID49IG5vdygpIC0gSU5URVJWQUwgOTYgSE9VUgogICAgQU5EIHB1bGxfcmVxdWVzdF9udW1iZXIgPSAwCiAgICBBTkQgdGVzdF9zdGF0dXMgIT0gJ1NLSVBQRUQnCiAgICBBTkQgdGVzdF9zdGF0dXMgTElLRSAnRiUnCiAgICBBTkQgY2hlY2tfc3RhdHVzICE9ICdzdWNjZXNzJwogICAgQU5EIHBvc2l0aW9uKHRlc3RfbmFtZSwgJzAyMzQ2X2Z1bGxfdGV4dF9zZWFyY2gnKSA+IDAKT1JERVIgQlkgY2hlY2tfc3RhcnRfdGltZQ==

"Ordinary" databases were deprecated in ca. 2020 and nowadays can no longer be created unless a special setting is on.

There is actually a fallback path (recursive removal) and I am not sure why this is logged as "error" instead of "warning".

For now disabling 02346_full_text_search for ordinary databases.

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Review by devcrafter — APPROVED** [review]

**Comment by tavplubix** [comment]
Should we disable this feature with Ordinary engine then?

**Comment by tavplubix** [comment]
Hm, probably the same issue happens with Atomic databases as well, but we don't see it because the error is logged by a background thread, so `clickouse-test` cannot notice it.

**Review by tavplubix — CHANGES_REQUESTED** [review]
Need more info about the issue, see the comments above

**Comment by tavplubix** [comment]
Probably some file related to indexes was not added to `MergeTreeDataPartChecksums::files` for some reason

**Comment by rschu1ze** [comment]
Hmm, good points. Yes, the inverted index adds extra files to the persistence. Let me try a real fix...

**Comment by rschu1ze** [comment]
The immediate problem is solved in a bit hacky way. I did not find a more natural place where the checksums are populated.

**Review by tavplubix — APPROVED** [review]
Okay for a hotfix

**Comment by tavplubix** [comment]
> where the checksums are populated.

See `loadColumnsChecksumsIndexes`, `fillSkipIndicesChecksums`, and places like `finalizeMutatedPart`

**Pull request merged**
