### PR TITLE
In memory coordination inside ClickHouse

### PR DESCRIPTION
**Pull request by alesapin**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by alesapin** [comment]
Current state, investigating issues with races on the connection in NuRaft https://github.com/eBay/NuRaft/issues/169.

**Comment by alesapin** [comment]
Wow, test is flaky. node2 lost one part (`all_2_2_0` inserted on `node3`):
```
>       assert node2.query("SELECT COUNT() FROM t2") == "510\n"
E       AssertionError: assert '410\n' == '510\n'
E         - 510
E         ? ^
E         + 410
E         ? ^
```
For some reason, there are no messages about this part `node2` log. `node1` fetched this part from `node3`.
```
Fetching part all_2_2_0 from /clickhouse/t2/replicas/3
```
 but `node2` just ignored it while successfully fetched the next parts.

```
Fetching part all_5_5_0 from /clickhouse/t2/replicas/3
```

**Comment by alesapin** [comment]
Things to do:

- [ ] Track session expiration on the leader in the background.
- [ ] Don't reset client connection immediately if no leader is alive. Wait for some time (< operation timeout).
- [ ] Don't parse responses multiple times (not important now).
- [ ] Change Storage lock from `std::mutex` to `std::shared_mutex`.
- [ ] Take raft parameters from config (with sane defaults).

**Comment by alesapin** [comment]
> Wow, test is flaky. node2 lost one part (`all_2_2_0` inserted on `node3`):
> 
> ```
> >       assert node2.query("SELECT COUNT() FROM t2") == "510\n"
> E       AssertionError: assert '410\n' == '510\n'
> E         - 510
> E         ? ^
> E         + 410
> E         ? ^
> ```
> 
> For some reason, there are no messages about this part `node2` log. `node1` fetched this part from `node3`.
> 
> ```
> Fetching part all_2_2_0 from /clickhouse/t2/replicas/3
> ```
> 
> but `node2` just ignored it while successfully fetched the next parts.
> 
> ```
> Fetching part all_5_5_0 from /clickhouse/t2/replicas/3
> ```
> 
> data
> 
> ```
> $ ls  test_testkeeper_multinode/_instances/node1/database/store/2e2/2e22af4c-a5da-4c63-8d92-d2e69fbc9d55/
> all_0_5_1  detached  format_version.txt
> $ ls test_testkeeper_multinode/_instances/node2/database/store/5f6/5f625ee2-6977-4955-a0b5-9a892f14f95d/
> all_0_0_0  all_1_1_0  all_3_3_0  all_4_4_0  all_5_5_0  detached  format_version.txt
> $ ls test_testkeeper_multinode/_instances/node3/database/store/2c5/2c5bf2e5-cbf9-4935-afda-c76bab05db6f
> all_0_5_1  detached  format_version.txt
> ```

This is possible in the case of an unstable network with ZooKeeper and frequent calls of `SYSTEM RESTART REPLICA`. The situation is so rare, that it's better to fix the test than clickhouse code.

**Comment by alesapin** [comment]
image
Finally!

**Comment by alesapin** [comment]
`01674_executable_dictionary_implicit_key` not related to changes.

**Comment by alesapin** [comment]
One of 100 runs of `test_testkeeper_multinode` with thread sanitizer had timed out. Strange in logs:
```
[11:05:00]alesap@click:~/.../ClickHouse/tests/integration$ grep '5ae61917-0a22-48de-8cdd-3b341c83ae69' test_testkeeper_multinode/_instances/node2/logs/clickhouse-server.log
2021.02.04 00:39:48.171294 [ 11 ] {5ae61917-0a22-48de-8cdd-3b341c83ae69} <Debug> executeQuery: (from 192.168.64.1:39662, using production parser) ATTACH TABLE t1
2021.02.04 00:39:48.172009 [ 11 ] {5ae61917-0a22-48de-8cdd-3b341c83ae69} <Trace> ContextAccess (default): Access granted: CREATE TABLE ON default.t1
2021.02.04 00:42:34.452282 [ 11 ] {5ae61917-0a22-48de-8cdd-3b341c83ae69} <Trace> ZooKeeper: Initialized, hosts: node3:9181,node2:9181,node1:9181
2021.02.04 00:42:34.456738 [ 11 ] {5ae61917-0a22-48de-8cdd-3b341c83ae69} <Debug> default.t1 (fb649005-450c-4c44-89df-8f907847b063): Loading data parts
2021.02.04 00:42:34.458449 [ 11 ] {5ae61917-0a22-48de-8cdd-3b341c83ae69} <Debug> default.t1 (fb649005-450c-4c44-89df-8f907847b063): Loaded data parts (1 items)
2021.02.04 00:42:34.483679 [ 11 ] {5ae61917-0a22-48de-8cdd-3b341c83ae69} <Trace> default.t1 (ReplicatedMergeTreeRestartingThread): Restarting thread finished
2021.02.04 00:42:34.483773 [ 11 ] {5ae61917-0a22-48de-8cdd-3b341c83ae69} <Trace> default.t1 (ReplicatedMergeTreeRestartingThread): Waiting for threads to finish
2021.02.04 00:42:34.483875 [ 11 ] {5ae61917-0a22-48de-8cdd-3b341c83ae69} <Trace> default.t1 (ReplicatedMergeTreeRestartingThread): Threads finished
2021.02.04 00:42:34.742994 [ 11 ] {5ae61917-0a22-48de-8cdd-3b341c83ae69} <Debug> MemoryTracker: Peak memory usage (for query): 4.00 MiB.
```
No errors in logs, but for some reason, this query took about 3 minutes.

**Comment by alesapin** [comment]
Realized during refactoring that watches from non-leader host doesn't work...

**Comment by alesapin** [comment]
Looks like lock?
```
| | | 155  0x0000000015b4fd18 in Poco::ThreadImpl::runnableEntry at /home/alesap/code/cpp/ClickHouse/contrib/poco/Foundation/src/Thread_POSIX.cpp:345
| | | | 55   0x0000000015b51510 in Poco::(anonymous namespace)::RunnableHolder::run at /home/alesap/code/cpp/ClickHouse/contrib/poco/Foundation/src/Thread.cpp:55
| | | | | 55   0x0000000015b52f72 in Poco::PooledThread::run at /home/alesap/code/cpp/ClickHouse/contrib/poco/Foundation/src/ThreadPool.cpp:199
| | | | | | 49   0x00000000159eaa2f in Poco::Net::TCPServerDispatcher::run at /home/alesap/code/cpp/ClickHouse/contrib/poco/Net/src/TCPServerDispatcher.cpp:112
| | | | | | | 48   0x00000000159ea303 in Poco::Net::TCPServerConnection::start at /home/alesap/code/cpp/ClickHouse/contrib/poco/Net/src/TCPServerConnection.cpp:43
| | | | | | | | 48   0x0000000012dfbbaa in DB::NuKeeperTCPHandler::run at /home/alesap/code/cpp/ClickHouse/src/Server/NuKeeperTCPHandler.cpp:257
| | | | | | | | | 48   DB::NuKeeperTCPHandler::runImpl at /home/alesap/code/cpp/ClickHouse/src/Server/NuKeeperTCPHandler.cpp:335
| | | | | | | | | | 48   0x0000000012dfc53f in DB::NuKeeperStorageDispatcher::getSessionID at /home/alesap/code/cpp/ClickHouse/src/Coordination/NuKeeperStorageDispatcher.h:76
| | | | | | | | | | | 48   DB::NuKeeperServer::getSessionID at /home/alesap/code/cpp/ClickHouse/src/Coordination/NuKeeperServer.cpp:201
| | | | | | | | | | | | 48   0x00000000130f0346 in std::__1::lock_guard<std::__1::mutex>::lock_guard at /home/alesap/code/cpp/ClickHouse/contrib/libcxx/include/__mutex_base:91
| | | | | | | | | | | | | 48   std::__1::mutex::lock at /home/alesap/code/cpp/ClickHouse/contrib/libcxx/src/mutex.cpp:33
| | | | | | | | | | | | | | 48   0x0000000017b8795a in std::__1::__libcpp_mutex_lock at /home/alesap/code/cpp/ClickHouse/contrib/libcxx/include/__threading_support:405
| | | | | | | | | | | | | | | 48   0x0000000008b08e69 in pthread_mutex_lock ()
| | | | | | | | | | | | | | | | 48   0x00007f0264e1e0a3 in pthread_mutex_lock () from target:/lib/x86_64-linux-gnu/libpthread.so.0
| | | | | | | | | | | | | | | | | 48   0x00007f0264e26110 in __lll_lock_wait () from target:/lib/x86_64-linux-gnu/libpthread.so.0

| | | | | | | | | | 35   _ZNSt3__110__function16__policy_invokerIFvvEE11__call_implINS0_20__default_alloc_funcIZN20ThreadFromGlobalPoolC1IZN2DB25NuKeeperStorageDispatcher10initializeERKN4Poco4Util21AbstractConfigurationEE3$_0JEEEOT_DpOT0_EUlvE_S2_EEEEvPKNS0_16__policy_storageE at /home/alesap/code/cpp/ClickHouse/contrib/libcxx/include/functional:2089
| | | | | | | | | | | 1    _ZNSt3__110__function20__default_alloc_funcIZN20ThreadFromGlobalPoolC1IZN2DB25NuKeeperStorageDispatcher10initializeERKN4Poco4Util21AbstractConfigurationEE3$_0JEEEOT_DpOT0_EUlvE_FvvEEclEv at /home/alesap/code/cpp/ClickHouse/contrib/libcxx/include/functional:1608
| | | | | | | | | | | | 1    _ZNSt3__128__invoke_void_return_wrapperIvE6__callIJRZN20ThreadFromGlobalPoolC1IZN2DB25NuKeeperStorageDispatcher10initializeERKN4Poco4Util21AbstractConfigurationEE3$_0JEEEOT_DpOT0_EUlvE_EEEvDpOT_ at /home/alesap/code/cpp/ClickHouse/contrib/libcxx/include/__functional_base:348
| | | | | | | | | | | | | 1    _ZNSt3__18__invokeIRZN20ThreadFromGlobalPoolC1IZN2DB25NuKeeperStorageDispatcher10initializeERKN4Poco4Util21AbstractConfigurationEE3$_0JEEEOT_DpOT0_EUlvE_JEEEDTclclsr3std3__1E7forwardISB_Efp_Espclsr3std3__1E7forwardISD_Efp0_EEESC_SF_ at /home/alesap/code/cpp/ClickHouse/contrib/libcxx/include/type_traits:3676
| | | | | | | | | | | | | | 1    _ZZN20ThreadFromGlobalPoolC1IZN2DB25NuKeeperStorageDispatcher10initializeERKN4Poco4Util21AbstractConfigurationEE3$_0JEEEOT_DpOT0_ENUlvE_clEv at /home/alesap/code/cpp/ClickHouse/src/Common/ThreadPool.h:178
| | | | | | | | | | | | | | | 1    std::__1::apply<DB::NuKeeperStorageDispatcher::initialize(Poco::Util::AbstractConfiguration const&)::$_0(std::__1::tuple<>&)&> at /home/alesap/code/cpp/ClickHouse/contrib/libcxx/include/tuple:1424
| | | | | | | | | | | | | | | | 1    _ZNSt3__118__apply_tuple_implIRZN2DB25NuKeeperStorageDispatcher10initializeERKN4Poco4Util21AbstractConfigurationEE3$_0RNS_5tupleIJEEEJEEEDcOT_OT0_NS_15__tuple_indicesIJXspT1_EEEE at /home/alesap/code/cpp/ClickHouse/contrib/libcxx/include/tuple:1415
| | | | | | | | | | | | | | | | | 1    _ZNSt3__118__invoke_constexprIRZN2DB25NuKeeperStorageDispatcher10initializeERKN4Poco4Util21AbstractConfigurationEE3$_0JEEEDTclclsr3std3__1E7forwardIT_Efp_Espclsr3std3__1E7forwardIT0_Efp0_EEEOSA_DpOSB_ at /home/alesap/code/cpp/ClickHouse/contrib/libcxx/include/type_traits:3682
| | | | | | | | | | | | | | | | | | 1    0x0000000013121a01 in DB::NuKeeperStorageDispatcher::initialize(Poco::Util::AbstractConfiguration const&)::$_0::operator()() const at /home/alesap/code/cpp/ClickHouse/src/Coordination/NuKeeperStorageDispatcher.cpp:173
| | | | | | | | | | | | | | | | | | | 1    0x000000001311cc9d in DB::NuKeeperStorageDispatcher::processingThread at /home/alesap/code/cpp/ClickHouse/src/Coordination/NuKeeperStorageDispatcher.cpp:35
| | | | | | | | | | | | | | | | | | | | 1    0x00000000130ee68d in DB::NuKeeperServer::putRequest at /home/alesap/code/cpp/ClickHouse/src/Coordination/NuKeeperServer.cpp:158
| | | | | | | | | | | | | | | | | | | | | 1    0x00000000158c7896 in nuraft::raft_server::append_entries at /home/alesap/code/cpp/ClickHouse/contrib/NuRaft/src/handle_user_cmd.cxx:79
| | | | | | | | | | | | | | | | | | | | | | 1    nuraft::raft_server::send_msg_to_leader at /home/alesap/code/cpp/ClickHouse/contrib/NuRaft/src/handle_user_cmd.cxx:192
| | | | | | | | | | | | | | | | | | | | | | | 1    0x00000000158c6f2a in nuraft::cmd_result<std::__1::shared_ptr<nuraft::buffer>, std::__1::shared_ptr<std::exception> >::get at /home/alesap/code/cpp/ClickHouse/contrib/NuRaft/include/libnuraft/async.hxx:263
| | | | | | | | | | | | | | | | | | | | | | | | 1    std::__1::condition_variable::wait at /home/alesap/code/cpp/ClickHouse/contrib/libcxx/src/condition_variable.cpp:44
| | | | | | | | | | | | | | | | | | | | | | | | | 1    0x0000000017b039c8 in std::__1::__libcpp_condvar_wait at /home/alesap/code/cpp/ClickHouse/contrib/libcxx/include/__threading_support:436
| | | | | | | | | | | | | | | | | | | | | | | | | | 1    0x0000000008aec561 in pthread_cond_wait ()
| | | | | | | | | | | | | | | | | | | | | | | | | | | 1    0x0000000008aec674 in cond_wait(__tsan::ThreadState*, unsigned long, __tsan::ScopedInterceptor*, int (*)(void*, void*, void*), void*, void*, void*) ()
| | | | | | | | | | | | | | | | | | | | | | | | | | | | 1    0x0000000008b59e05 in __tsan::call_pthread_cancel_with_cleanup(int (*)(void*, void*, void*), void*, void*, void*, void (*)(void*), void*) ()
| | | | | | | | | | | | | | | | | | | | | | | | | | | | | 1    0x00007f0264e22376 in pthread_cond_wait@@GLIBC_2.3.2 () from target:/lib/x86_64-linux-gnu/libpthread.so.0
```

**Comment by alesapin** [comment]
Actually not a deadlock, but sometimes it takes a gigantic amount of time (about 5-15 min or so)  to respond to a simple request. Seems like it happens when the node decides to send a request to the leader but the leader changes to this node before the request finishes.

**Comment by alesapin** [comment]
Ok, now the error is clear to me.
We send a request to the leader, https://github.com/eBay/NuRaft/blob/master/src/handle_user_cmd.cxx#L188, and wait without any timeouts: https://github.com/eBay/NuRaft/blob/master/src/handle_user_cmd.cxx#L192. In my test, we blockade the former leader for a long time and wait until alive nodes will choose the new one. But this request will wait for the blocked leader until it will be unblocked. Probably we have to introduce timeouts here.

**Comment by alesapin** [comment]
It should help https://github.com/ClickHouse-Extras/NuRaft/pull/5.

**Comment by alesapin** [comment]
> Realized during refactoring that watches from non-leader host doesn't work...

Fixed

**Comment by alesapin** [comment]
Ok, now the ugliest part is the startup process. NuRaft requires one server (future leader) to add other servers (future followers) to the RAFT quorum. Other servers just wait until they receive a request to join. Now I just choose one of the servers (based on priority or lexicographical order) and other servers just wait with hardcoded timeouts. But if something wrong happened with a potential leader then `quorum` will be never build and clickhouse will refuse to startup.

Probably for now I can leave it as is because it starts up in tests without problems.

**Comment by alesapin** [comment]
Todo: implement `sync` request:
https://github.com/python-zk/kazoo/blob/master/kazoo/protocol/serialization.py#L263-L271
https://github.com/apache/zookeeper/blob/master/zookeeper-jute/src/main/resources/zookeeper.jute#L179-L184
https://zookeeper.apache.org/doc/r3.4.2/api/org/apache/zookeeper/ZooKeeper.html#sync(java.lang.String,%20org.apache.zookeeper.AsyncCallback.VoidCallback,%20java.lang.Object)

**Comment by alesapin** [comment]
> Todo: implement `sync` request:
> https://github.com/python-zk/kazoo/blob/master/kazoo/protocol/serialization.py#L263-L271
> https://github.com/apache/zookeeper/blob/master/zookeeper-jute/src/main/resources/zookeeper.jute#L179-L184
> https://zookeeper.apache.org/doc/r3.4.2/api/org/apache/zookeeper/ZooKeeper.html#sync(java.lang.String,%20org.apache.zookeeper.AsyncCallback.VoidCallback,%20java.lang.Object)

Done
some tests (https://github.com/phunt/zk-smoketest):
```
$ PYTHONPATH=lib.linux-x86_64-2.6 LD_LIBRARY_PATH=lib.linux-x86_64-2.6 ./zk-smoketest.py --servers="localhost:9181"
Connecting to localhost:9181
Connected in 4 ms, handle is 0
Connecting to localhost:9181
Connected in 1 ms, handle is 1
Connecting to localhost:9181
Connected in 3 ms, handle is 0
Smoke test successful
$ PYTHONPATH=lib.linux-x86_64-2.6 LD_LIBRARY_PATH=lib.linux-x86_64-2.6 ./zk-latencies.py --servers="localhost:9181"
Connecting to localhost:9181
Connected in 4 ms, handle is 0
Testing latencies on server localhost:9181 using asynchronous calls
created   10000 permanent znodes  in   2223 ms (0.222387 ms/op 4496.671911/sec)
set       10000           znodes  in   2158 ms (0.215887 ms/op 4632.046780/sec)
get       10000           znodes  in    698 ms (0.069868 ms/op 14312.705513/sec)
deleted   10000 permanent znodes  in   2152 ms (0.215295 ms/op 4644.787545/sec)
created   10000 ephemeral znodes  in   2546 ms (0.254640 ms/op 3927.111208/sec)
watched   10000           znodes  in   2124 ms (0.212452 ms/op 4706.954408/sec)
deleted   10000 ephemeral znodes  in   2662 ms (0.266280 ms/op 3755.443947/sec)
notif     10000           watches in      0 ms (included in prior)
Latency test complete
```

**Comment by alesapin** [comment]
Todo: simplify startup

**Comment by alesapin** [comment]
> Todo: simplify startup

done

**Comment by alesapin** [comment]
https://github.com/ClickHouse/ClickHouse/pull/20175

**Comment by alesapin** [comment]
`test_materialize_mysql_database/test.py::test_clickhouse_killed_while_insert_5_7[clickhouse_node1]`
`test_materialize_mysql_database/test.py::test_clickhouse_killed_while_insert_8_0[clickhouse_node1]`
cc @zhang2014

**Comment by alesapin** [comment]
```
2021.02.12 14:20:58.800988 [ 17728 ] {de3e7894-b401-4f7d-8530-90cd5ab06682} <Debug> executeQuery: (from [::1]:45792, using production parser) (comment: /usr/share/clickhouse-test/queries/0_stateless/01520_client_print_query_id.expect) SELECT * FROM numbers(34599)
2021.02.12 14:20:58.916484 [ 17728 ] {de3e7894-b401-4f7d-8530-90cd5ab06682} <Trace> ContextAccess (default): Access granted: CREATE TEMPORARY TABLE ON *.*
2021.02.12 14:20:59.071980 [ 17728 ] {de3e7894-b401-4f7d-8530-90cd5ab06682} <Trace> InterpreterSelectQuery: FetchColumns -> Complete
2021.02.12 14:21:10.708202 [ 17728 ] {de3e7894-b401-4f7d-8530-90cd5ab06682} <Information> executeQuery: Read 34599 rows, 270.30 KiB in 11.876294055 sec., 2913 rows/sec., 22.76 KiB/sec.
2021.02.12 14:22:10.506261 [ 17728 ] {de3e7894-b401-4f7d-8530-90cd5ab06682} <Debug> DynamicQueryHandler: Done processing query
2021.02.12 14:22:18.238037 [ 375 ] {} <Fatal> BaseDaemon: (version 21.3.1.5996, build id: 8DBCED54529C989F7AD4D991F51410774D55DE6C) (from thread 17728) Terminate called for uncaught exception:
2021.02.12 14:22:18.811071 [ 18134 ] {} <Fatal> BaseDaemon: ########################################
2021.02.12 14:22:18.878935 [ 18134 ] {} <Fatal> BaseDaemon: (version 21.3.1.5996, build id: 8DBCED54529C989F7AD4D991F51410774D55DE6C) (from thread 17728) (query_id: de3e7894-b401-4f7d-8530-90cd5ab06682) Received signal Aborted (6)
2021.02.12 14:22:18.943148 [ 18134 ] {} <Fatal> BaseDaemon: 
2021.02.12 14:22:19.007073 [ 18134 ] {} <Fatal> BaseDaemon: Stack trace: 0x7f109932018b 0x7f10992ff859 0x8bb33ae 0x8e301dd 0x17dac8c4 0x17dac7c7 0x8c3fe0b 0x8d552c5 0x8d552ea 0x11a29914 0x11a2a2ca 0x12f96092 0x12f8c65e 0x12f84300 0x15b84110 0x15bc0913 0x15bc103f 0x15d29a12 0x15d27fb0 0x15d267b8 0x8badbad 0x7f10994d5609 0x7f10993fc293
2021.02.12 14:22:19.255998 [ 18134 ] {} <Fatal> BaseDaemon: 5. raise @ 0x4618b in /usr/lib/x86_64-linux-gnu/libc-2.31.so
2021.02.12 14:22:19.270203 [ 18134 ] {} <Fatal> BaseDaemon: 6. abort @ 0x25859 in /usr/lib/x86_64-linux-gnu/libc-2.31.so
2021.02.12 14:22:50.108918 [ 370 ] {} <Fatal> Application: Child process was terminated by signal 6.
```
Not related to changes

**Comment by alesapin** [comment]
No related failures, going to merge today or tomorrow.

**Comment by sundy-li** [comment]
> test_materialize_mysql_database

cc @zhang2014

**Comment by azat** [comment]
>Not related to changes

```
Code: 24, e.displayText() = DB::Exception: Cannot write to ostream at offset 262994, Stack trace (when copying this message, always include the lines below):
```

This came from #19451
I have some ideas, but let's improve diagnostics in stress tests first #20462

**Comment by azat** [comment]
>2021.02.12 14:22:18.238037 [ 375 ] {} <Fatal> BaseDaemon: (version 21.3.1.5996, build id: 8DBCED54529C989F7AD4D991F51410774D55DE6C) (from thread 17728) Terminate called for uncaught exception:

@alesapin should be fixed in #20464

**Comment by TisonKun** [comment]
commit 57c9b6c864d10909e74cd02e9ba4c90cd4487339 belongs to this pull request excludes darwin(macOS) from running ClickHouse with

```
<Error> Application: DB::Exception: ClickHouse server built without NuRaft library. Cannot use internal coordination.
```

it is intended? If so, is there a plan to fix?

**Comment by alesapin** [comment]
> commit [57c9b6c](https://github.com/ClickHouse/ClickHouse/commit/57c9b6c864d10909e74cd02e9ba4c90cd4487339) belongs to this pull request excludes darwin(macOS) from running ClickHouse with
> 
> ```
> <Error> Application: DB::Exception: ClickHouse server built without NuRaft library. Cannot use internal coordination.
> ```
> 
> it is intended? If so, is there a plan to fix?

Yes, it's intended. I think we will fix it after linux version will be completely ready.

**Comment by TisonKun** [comment]
@alesapin where does the original incompatibility come from? NuRaft itself is compatible with OSX.

**Comment by TisonKun** [comment]
> > commit [57c9b6c](https://github.com/ClickHouse/ClickHouse/commit/57c9b6c864d10909e74cd02e9ba4c90cd4487339) belongs to this pull request excludes darwin(macOS) from running ClickHouse with
> > ```
> > <Error> Application: DB::Exception: ClickHouse server built without NuRaft library. Cannot use internal coordination.
> > ```
> > 
> > 
> > it is intended? If so, is there a plan to fix?
> 
> Yes, it's intended. I think we will fix it after linux version will be completely ready.

@alesapin locally replace ulong / size_t inherited from nuraft with `nuraft::ulong` make it compiled on OS_DARWIN. Notice that you're actively working on this topic, maybe you can take it into consideration.

**Comment by alesapin** [comment]
> > > commit [57c9b6c](https://github.com/ClickHouse/ClickHouse/commit/57c9b6c864d10909e74cd02e9ba4c90cd4487339) belongs to this pull request excludes darwin(macOS) from running ClickHouse with
> > > ```
> > > <Error> Application: DB::Exception: ClickHouse server built without NuRaft library. Cannot use internal coordination.
> > > ```
> > > 
> > > 
> > > it is intended? If so, is there a plan to fix?
> > 
> > 
> > Yes, it's intended. I think we will fix it after linux version will be completely ready.
> 
> @alesapin locally replace ulong / size_t inherited from nuraft with `nuraft::ulong` make it compiled on OS_DARWIN. Notice that you're actively working on this topic, maybe you can take it into consideration.

Yes, but it's not the only problem -- in TCP server handler I use `epoll` for incoming connections which is not available on non-linux Unix systems. I've replaced it with `poll`, but probably it will work worse.

The current development stage is still a prototype, but I can fix OS_DARWIN build if you need it.

**Comment by TisonKun** [comment]
@alesapin I'll appreciate it if you fix that. Either fix the type issue, the epoll issue and possible others, or disable NuKeeper module for OS_DARWIN for now.

**Comment by alesapin** [comment]
> @alesapin I'll appreciate it if you fix that. Either fix the type issue, the epoll issue and possible others, or disable NuKeeper module for OS_DARWIN for now.

But it's already disabled? https://github.com/ClickHouse/ClickHouse/blob/master/src/CMakeLists.txt#L197-L199

**Comment by TisonKun** [comment]
https://github.com/ClickHouse/ClickHouse/blob/36c178c0231a073fdb3f75ca52a85ba9e4fbea7e/programs/server/Server.cpp#L872-L874

You're right. I should use the term "run", normally running on OS_DARWIN. However, if it is an significant burden over prototyping, it's ok we give another pass later for the fix.

**Pull request merged**
