### PR TITLE
Too big translation unit in `Aggregator`

### PR DESCRIPTION
**Pull request by lgbo-ustc**
### Changelog category (leave one):
- Build/Testing/Packaging Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
...
Too big translation unit in `Aggregator`.

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by Algunenano** [comment]
Let's wait until https://github.com/ClickHouse/ClickHouse/pull/61171 is processed

**Review by alexey-milovidov — APPROVED** [review]

**Comment by robot-ch-test-poll2** [comment]
*This is an automated comment for commit 5f1991fbef2f959f1d55c62194d948814d199fa9 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/61211/5f1991fbef2f959f1d55c62194d948814d199fa9/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

**Comment by alexey-milovidov** [comment]
One warning from clang-tidy:

```
Mar 13 16:15:19 /build/src/Interpreters/AggregatedDataVariants.cpp:21:23: error: using decl 'LastElementCacheStats' is unused [misc-unused-using-decls,-warnings-as-errors]
Mar 13 16:15:19    21 | using ColumnsHashing::LastElementCacheStats;
```

**Comment by lgbo-ustc** [comment]
There is an error
```
2024.03.14 03:12:46.433923 [ 296 ] {d8adc3e5-c160-43b5-9b12-19493462806d} <Fatal> : Logical error: 'Inconsistent     AST formatting: the query:SELECT ((('a', 10) AS x).1) = toFixedString('a', 1) FROM remote('127.0.0.{1,2,3}', numbers(2))
Was parsed and formatted back as:SELECT (tuple(('a', 10) AS x).1) = toFixedString('a', 1) FROM remote('127.0.0.{1,2,3}', numbers(2))'
```

**Pull request merged**
