### PR TITLE
KeeperDispatcher: remove reductant lock as the ConcurrentBoundedQueue is thread-safe

### PR DESCRIPTION
**Pull request by frinkr**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
KeeperDispatcher: remove reductant lock as the ConcurrentBoundedQueue is thread-safe

### CODE REVIEW

**Comment by robot-clickhouse** [comment]
This is an automated comment for commit 36fbc22b16553022de022115efac7986828f8a75 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/51766/36fbc22b16553022de022115efac7986828f8a75/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Comment by alexey-milovidov** [comment]
Redundant or reluctant?

**Comment by antonio2368** [comment]
At first looks okay, but didn't have a chance to give it a proper look and thought.

**Review by antonio2368 — APPROVED** [review]

**Comment by antonio2368** [comment]
Failures look related https://s3.amazonaws.com/clickhouse-test-reports/51766/5cb2cf418828d956d0bd99770e0fb32fbe867c3f/integration_tests__release__[2_4].html

**Comment by antonio2368** [comment]
@frinkr the same test failed again in 2 different runs for some reason and I'm trying to understand why. 
`test_keeper_session/test.py::test_session_close_shutdown`

Seems related as the test should be stable and doesn't fail so often in general.

**Pull request merged**
