### PR TITLE
Continue of #42008, rewrite countDistinctIf with count_distinct_implementation

### LINKED ISSUE #30642: countDistinctIf with Date use much more memory than UInt16
**Describe the situation**
countDistinctIf with Date datatype use more memory than UInt16

**How to reproduce**
ClickHouse version 21.11

```
SELECT countDistinctIf(materialize(toUInt16(today())), 1)
FROM numbers_mt(100000000)
GROUP BY number % 1000000
FORMAT `Null`

Peak memory usage (for query): 1.51 GiB.

0 rows in set. Elapsed: 2.465 sec. Processed 100.00 million rows, 800.00 MB (40.57 million rows/s., 324.57 MB/s.)

SELECT countDistinctIf(materialize(today()), 1)
FROM numbers_mt(100000000)
GROUP BY number % 1000000
FORMAT `Null`

Peak memory usage (for query): 4.51 GiB.

0 rows in set. Elapsed: 4.455 sec. Processed 100.00 million rows, 800.00 MB (22.44 million rows/s., 179.56 MB/s.)
```

**Expected performance**
Speed and memory usage should be  the same as for UInt16

### PR DESCRIPTION
**Pull request by ucasfl**
### Changelog category (leave one):
- New Feature

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Add setting `rewrite_count_distinct_if_with_count_distinct_implementation` to rewrite `countDistinctIf` with `count_distinct_implementation`. Closes #30642.

### Documentation entry for user-facing changes

- [x] Documentation is written (mandatory for new features)

### CODE REVIEW

**Comment by ucasfl** [comment]
@alexey-milovidov Hi, could you take a look at this, it should be ok.

**Comment by kitaisreal** [comment]
It is already implemented in migration pull request, and it cannot be implemented in CustomizeFunctionsPass, because there are potential issues with multiple arguments https://github.com/ClickHouse/ClickHouse/pull/45461/files#diff-377c0cb9048fe3fe24b9501a4d6fdadde00a04c75a162f705de66cadeb654d9cR4745.
Better to remove analyzer implementation, and wait until https://github.com/ClickHouse/ClickHouse/pull/45461 will be merged.
Related to AST optimization, we can merge it.

**Comment by alexey-milovidov** [comment]
We can continue; just leave only the non-analyzer implementation.

**Comment by robot-ch-test-poll4** [comment]
This is an automated comment for commit c4a86c148adf5f4830050222950ac2e65b9ac11b with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/46051/c4a86c148adf5f4830050222950ac2e65b9ac11b/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Docs Check</td><td>Builds and tests the documentation</td><td>🟡 pending</td></tr>
</table>

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
@ucasfl HDFS has failed: https://s3.amazonaws.com/clickhouse-test-reports/46051/5af3689a8f15c8c9767d56e7201b73b5fe2460ba/integration_tests__asan__[3_6].html

It is probably unrelated to your PR, but has to be investigated.

**Comment by ucasfl** [comment]
Why the ci don't run atomatically anymore?

**Review by alexey-milovidov — APPROVED** [review]

**Comment by ucasfl** [comment]
All green finally!

**Pull request merged**
