### PR TITLE
Remove `arrayFold`

### LINKED ISSUE #57458: position function behaves incorrectly when used with arrayFold
**Describe what's wrong**

`position` function behaves incorrectly when used with `arrayFold` - fails to search string. I've verified all other intermediate states of `arrayFold` and other functions used are correct.

https://fiddle.clickhouse.com/80adfdb5-f671-4d8a-bb27-49d6fdfdada7

`position` function seems to fail string search and return 0 (substring not found).

**Does it reproduce on recent release?**

Confirmed on 23.10.3.1 on server as well as clickhouse-local

**How to reproduce**

refer to clickhouse fiddle - has a minimal reproducible setup

**Expected behavior**

It should return the correct position of the substring.

**Additional context**

I am using the nix version of clickhouse but seeing it's also reproducible on fiddle, I don't think that's relevant to the issue.

---
*offtopic: I spent multiple hours figuring out why it isn't working. If you're wondering how I found this bug, I was trying to solve this years' advent of code with clickhouse - helps to learn a lot of the cool functions ClickHouse offers! (also I'm slightly deranged).*

### LINKED ISSUE #57816: arrayFold of arrayIntersect segfault
This little query breaks clickhouse. It works on arm64 macos local, it works on amd64 linux server, it works on fresh installed version.

```
$ clickhouse local
ClickHouse local version 23.12.1.457 (official build).

air.local :) SELECT arrayFold(acc, x -> arrayIntersect(acc, x), [['qwe', 'asd'], ['qwe','asde']], [])

SELECT arrayFold((acc, x) -> arrayIntersect(acc, x), [['qwe', 'asd'], ['qwe', 'asde']], [])

Query id: 660a9bd1-2975-49b8-ba29-35bcfce5901c

Abort trap: 6
```

### PR DESCRIPTION
**Pull request by alexey-milovidov**
### Changelog category (leave one):
- Backward Incompatible Change

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Remove function `arrayFold` because it has a bug. This closes #57816. This closes #57458.

### CODE REVIEW

**Comment by robot-clickhouse-ci-1** [comment]
*This is an automated comment for commit 15dc0ed610998b847cb0752f5721c55d538fb629 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/57836/15dc0ed610998b847cb0752f5721c55d538fb629/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td><a href="https://github.com/ClickHouse/ClickHouse/actions/runs/7204162014">✅ success</a></td></tr>
<tbody>
</table>
</details>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/57836/15dc0ed610998b847cb0752f5721c55d538fb629/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Comment by Strate** [comment]
??? I have used it already to calculate marketing funnels (much more complex things that could be calculated with windowFunnel and other array functions). Will this function be implemented again?

**Comment by rschu1ze** [comment]
@Strate I am currently working on fixing the issues and will bring the function back.

**Comment by alexey-milovidov** [comment]
If a code is not memory-safe, it should be removed (and burned).
But actually, the intention is to fix the error.

**Pull request merged**
