### PR TITLE
Apply `ALTER TABLE ON CLUSTER MOVE PARTITION TO DISK|VOLUME` to all replicas.

### PR DESCRIPTION
**Pull request by lzydmxy**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
- Apply `ALTER TABLE table_name ON CLUSTER cluster MOVE PARTITION|PART partition_expr TO DISK|VOLUME 'disk_name'` to all replicas. Because `ALTER TABLE t MOVE` is not replicated.

### CODE REVIEW

**Review by tavplubix — APPROVED** [review]
Thanks! It would be great to add a test, but seems like it has to be an integration test, so it will be too complex.

**Comment by tavplubix** [comment]
CI did not start for some reason, let's restart it

**Comment by lzydmxy** [comment]
> but seems like it has to be an integration test, so it will be too complex.
OK, I will try it.

**Comment by lzydmxy** [comment]
@tavplubix  Please review when you have a chance   : )

**Comment by qoega** [comment]
https://s3.amazonaws.com/clickhouse-test-reports/46402/ccf87a6afd1fa93ea6ad8fe454ee27edd75c73ef/style_check.html
> /ClickHouse/tests/integration/test_move_partition_to_disk_on_cluster/__init__.py should exist for every integration test

**Comment by lzydmxy** [comment]
> https://s3.amazonaws.com/clickhouse-test-reports/46402/ccf87a6afd1fa93ea6ad8fe454ee27edd75c73ef/style_check.html
> 
> > /ClickHouse/tests/integration/test_move_partition_to_disk_on_cluster/**init**.py should exist for every integration test

Thanks! I forgot to add `__init__.py`.

**Comment by tavplubix** [comment]
Stress test (msan) - `Logical error: \'Operation `write` can be done only by downloader` - broken in master
Stress test (tsan) - there's a chance that it's fixed by https://github.com/ClickHouse/ClickHouse/pull/46384 
Stress test (ubsan) - `Logical error: \'Cache usage is not allowed` - broken in master

**Pull request merged**
