### PR TITLE
GroupArrayIntersect aggregate function

### PR DESCRIPTION
**Pull request by Lirikl**
### Changelog category (leave one):
- New Feature

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
add GroupArrayIntersect(array_column) function which aggregates column of array type into array consting of unique elements which are present in every array of column

### CODE REVIEW

**Comment by robot-ch-test-poll4** [comment]
This is an automated comment for commit c002a522f6db50e0527e91dd6585a6a2e999d827 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/49862/c002a522f6db50e0527e91dd6585a6a2e999d827/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Docs Check</td><td>Builds and tests the documentation</td><td>🟡 pending</td></tr>
</table>

**Comment by alexey-milovidov** [comment]
Missing tests.

**Comment by alexey-milovidov** [comment]
The code should be moved to .cpp entirely.

**Comment by yariks5s** [comment]
Will close this PR because groupArrayIntersect is implemented in #59598.

**Pull request closed without merging**
