### PR TITLE
Cherry pick #47246 to 23.2: Change the behavior of formatter %M in function formatDateTime() from minutes to month name

### PR DESCRIPTION
**Pull request by robot-ch-test-poll2**
Original pull-request #47246

This pull-request is a first step of an automated backporting.
It contains changes like after calling a local command `git cherry-pick`.
If you intend to continue backporting this changes, then resolve all conflicts if any.
Otherwise, if you do not want to backport them, then just close this pull-request.

The check results does not matter at this step - you can safely ignore them.

### Note

This pull-request will be merged automatically as it reaches the mergeable state, **do not merge it manually**.

### If the PR was closed and then reopened

If it stuck, check #47246 for `pr-backports-created` and delete it if necessary. Manually merging will do nothing, since `pr-backports-created` prevents the original PR #47246 from being processed.

### CODE REVIEW

**Comment by robot-clickhouse-ci-2** [comment]
Dear @antonio2368, @rschu1ze, the PR is not updated for 1d0h58m7s. Please, either resolve the conflicts, or close it to finish the backport process of #47246

**Comment by robot-ch-test-poll** [comment]
Dear @antonio2368, @rschu1ze, the PR is not updated for 1d0h59m43s. Please, either resolve the conflicts, or close it to finish the backport process of #47246

**Comment by robot-ch-test-poll1** [comment]
Dear @antonio2368, @rschu1ze, the PR is not updated for 1d0h1m53s. Please, either resolve the conflicts, or close it to finish the backport process of #47246

**Comment by robot-clickhouse** [comment]
Dear @antonio2368, @rschu1ze, the PR is not updated for 1d0h58m15s. Please, either resolve the conflicts, or close it to finish the backport process of #47246

**Comment by rschu1ze** [comment]
Sorry for not updating this PR for "1d0h58m15s" 😉 

v23.2 is vulnerable of #47291 and should receive this fix. The problem is that there are far too many conflicts to continue with this autogenerated PR (the code was refactored heavily in newer code states ...). I'll do the backport manually in #48631

**Comment by Felixoid** [comment]
don't forget about the note
image

**Comment by rschu1ze** [comment]
Removed label `pr-backports-created` from #47246. Let's see what happens 😄

**Pull request merged**
