### PR TITLE
Add formats translate

### PR DESCRIPTION
**Pull request by sundy-li**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

@blinkov 
1. Add formats.md translation.
2. Add some titles in `toc_zh.yml `
3.  Improve some css style in zh, cause Chinese not performs well in `yandex` font.

### CODE REVIEW

**Comment by blinkov** [comment]
@sundy-li there's too much copy-paste in `custom_zh.css` + we have pretty specific guidelines on fonts, but it'll try to do something about it separately.

**Comment by sundy-li** [comment]
@blinkov  

I am using macos 10.14 Mojave.

Tthe font browser currently using is 
    `font-family: "Yandex Sans Text Web", Arial, sans-serif;`

As you can see
image

As you can see, The looks a little light, and may influence our user reading.

This may looks better.
image

**Comment by blinkov** [comment]
@sundy-li on the screen that's not the actual font that is used, scroll to the bottom of this menu, the relevant section is called "Rendered fonts".

**Comment by sundy-li** [comment]
@blinkov  yeah,  `Rendered fonts` is 
```
Rendered Fonts
PingFang SC—Local file(75 glyphs)
Yandex Sans Text Web—Network resource(66 glyphs)
```

**Comment by blinkov** [comment]
@sundy-li I think I've figured it out: there was a setting in CSS that made all fonts lighter than default, but Yandex Sans ignores it for some reason while this PingFang SC is affected.

**Pull request merged**
