### PR TITLE
ISSUES-2553 add offset parameter to numbers

### PR DESCRIPTION
**Pull request by zhang2014**
#2535 
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
You didn't provide any motivation for this change.
So I have to guess, is it any useful.

At first glance, it seems completely useless,
because the user can always write
```
SELECT number + 10 FROM numbers(123)
```
instead of
```
SELECT number FROM numbers(10, 123)
```
and proposed change will only make query language more heavy.

It's also non obvious (without reading the docs), what does `numbers(n, m)` means:
- offset and limit;
- range begin and end, including end;
- range begin and end, not including end.

But finally I found at least some possible motivation for your change (but I leave it for you).

**Comment by zhang2014** [comment]
Sorry, I didn't introduce motivation.

> At first glance, it seems completely useless, 
> because the user can always write
> SELECT number + 10 FROM numbers(123)
> instead of
> SELECT number FROM numbers(10, 123)
> and proposed change will only make query language more heavy.

You are right, but 
- `SELECT number + 10 AS a, number + 10 AS b ... number + 10 AS n ...` is complicated.
- `numbers(10, 123)` can always be rewritten as `SELECT number FROM system.numbers LIMIT 10,123` but it's always more efficient

**Comment by filimonov** [comment]
1) I doubt tgat performance of numbers table can be a bottleneck in some real scenarios.
2) you can simplyfy such a selects using `WITH` clause like 
```sql
with number + 10 as number2
select number2 as a, number2 as b ...```
3) may be it would be better to introduce range/enumerate table function which will support all data types customizable init value and customizable increment step? Like classic `for` keyword in programming languages? For example ```select mondays from enumerate(toDate('2018-08-25'), x -> x <= toDate('2018-12-31'), x -> x + INTERVAL 7 DAYS)```

**Comment by zhang2014** [comment]
> I doubt tgat performance of numbers table can be a bottleneck in some real scenarios.
Yes, if you use `LIMIT m, n` you will have unnecessary wait offset, and if you use `number + m ... LIMIT n` you will have unnecessary operations, like '+'
> you can simplyfy such a selects using WITH clause like
That's great
> may be it would be better to introduce range/enumerate table function which will support all data types customizable init value and customizable increment step? Like classic for keyword in programming languages? For example select mondays from enumerate(toDate('2018-08-25'), x -> x <= toDate('2018-12-31'), x -> x + INTERVAL 7 DAYS)
Good idea, but the implementation is complicated, but I'll try : )

**Pull request merged**
