### PR TITLE
Fix 02404_memory_bound_merging with analyzer.

### PR DESCRIPTION
**Pull request by KochetovNicolai**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by robot-ch-test-poll1** [comment]
*This is an automated comment for commit 7d13a76767ccfb62771fd1f75de336ba85ce1785 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/56419/7d13a76767ccfb62771fd1f75de336ba85ce1785/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td><a href="https://github.com/ClickHouse/ClickHouse/actions/runs/6785838824">✅ success</a></td></tr>
<tbody>
</table>
</details>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/56419/7d13a76767ccfb62771fd1f75de336ba85ce1785/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Review by nickitat — APPROVED** [review]
lgtm

**Comment by KochetovNicolai** [comment]
https://github.com/ClickHouse/ClickHouse/issues/56043

**Comment by Algunenano** [comment]
It's not fixed https://s3.amazonaws.com/clickhouse-test-reports/0/6652ee2e529e38eabec2026038855b55ee9fd155/stateless_tests__release__analyzer_.html

**Comment by nickitat** [comment]
let me just remove the old merging method (Alexey agreed)

**Comment by nickitat** [comment]
> let me just remove the old merging method (Alexey agreed)

plan failed miserably, because grouping sets work only with it #43989

**Pull request merged**
