### PR TITLE
Add a way to skip fast tests

### PR DESCRIPTION
**Pull request by Felixoid**
Changelog category (leave one):
- Build/Testing/Packaging Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Add skip-fast-test label for PRs to skip FastTest completely. It will save some time for us in cases where we are 100% sure that the code is not changed.

### CODE REVIEW

**Comment by vdimir** [comment]
I should used it in https://github.com/ClickHouse/ClickHouse/pull/35124 in the same way (there label checked in python script)

**Review by vdimir — APPROVED** [review]

**Comment by Felixoid** [comment]
@vdimir be careful, there is an additional job needed to check if the needed job is skipped. Otherwise every dependent job is skipped as well

**Comment by Felixoid** [comment]
Ok, I am stuck and asking for help: https://github.community/t/continue-workflow-on-skipped-job/238682

**Comment by Felixoid** [comment]
I am closing it for now. THe main problem here is waiting for the host. The running time 10 minutes is not so significant now. See https://github.com/ClickHouse/ClickHouse/pull/35413

**Pull request closed without merging**
