### PR TITLE
Reintroduce 03002_part_log_rmt_fetch_*_error tests without flakiness and less time

### PR DESCRIPTION
**Pull request by azat**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Reverts: #66823 (cc @alexey-milovidov )

### CODE REVIEW

**Comment by robot-ch-test-poll4** [comment]
*This is an automated comment for commit e42eeb984f77cdd5e83edfdeea2551b3c55334c8 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/67113/e42eeb984f77cdd5e83edfdeea2551b3c55334c8/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td>✅ success</td></tr>
<tr><td>Unit tests</td><td>Runs the unit tests for different release types</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/6851ccffb8a9d154a1e735b0b059c63f54227eaf/unit_tests__release_.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Comment by azat** [comment]
>Stateless tests (release) — Some queries hung, fail: 1, passed: 6807, skipped: 6

```
2024.07.26 02:33:23.424663 [ 890 ] {} <Warning> Application: Child process was stopped by signal 19.
```

This is SIGSTOP, and it is likely a gdb issue, #66494

**Comment by azat** [comment]
CI is green

**Comment by qoega** [comment]
It is still flaky:
https://s3.amazonaws.com/clickhouse-test-reports/67511/881d57a7644057b586e4cdb95ebb8785d912d4c5/stateless_tests__msan__%5B3_4%5D.html

**Comment by azat** [comment]
Will be fixed in https://github.com/ClickHouse/ClickHouse/pull/67960

**Pull request merged**
