### PR TITLE
ISSUES-15883 try fix collate name

### PR DESCRIPTION
**Pull request by zhang2014**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix collate name & charset name parser and support `length = 0`  for string type

### CODE REVIEW

**Comment by zhang2014** [comment]
reference: https://github.com/mysql/mysql-server/blob/8.0/sql/sql_yacc.yy#L7131

**Comment by zhang2014** [comment]
Fixes: https://github.com/ClickHouse/ClickHouse/issues/15883#issuecomment-708932203

**Comment by zhang2014** [comment]
CC: @tavplubix

**Review by tavplubix — APPROVED** [review]

**Comment by tavplubix** [comment]
AST fuzzer - #16081
Performance - unrelated

**Pull request merged**
