### PR TITLE
Revert "Fix `tryBase64Decode()` with invalid input"

### LINKED ISSUE #56969: test_backward_compatibility/test_functions.py::test_string_functions is flaky
at master 
https://s3.amazonaws.com/clickhouse-test-reports/0/0e8d966747fb99317f74290df807ee978e0ba329/integration_tests__release__[4_4].html

stats
https://play.clickhouse.com/play?user=play#c2VsZWN0IAp0b1N0YXJ0T2ZIb3VyKGNoZWNrX3N0YXJ0X3RpbWUpIGFzIGQsCmNvdW50KCksICBncm91cFVuaXFBcnJheShwdWxsX3JlcXVlc3RfbnVtYmVyKSwgIGFueShyZXBvcnRfdXJsKQpmcm9tIGNoZWNrcyB3aGVyZSAnMjAyMy0wMS0wMScgPD0gY2hlY2tfc3RhcnRfdGltZSBhbmQgdGVzdF9uYW1lIGxpa2UgJyV0ZXN0X2JhY2t3YXJkX2NvbXBhdGliaWxpdHkvdGVzdF9mdW5jdGlvbnMucHk6OnRlc3Rfc3RyaW5nX2Z1bmN0aW9ucyUnIGFuZCB0ZXN0X3N0YXR1cyBpbiAoJ0ZBSUwnLCAnRkxBS1knKSBncm91cCBieSBkIG9yZGVyIGJ5IGQgZGVzYw==

Start to flak after https://github.com/ClickHouse/ClickHouse/pull/56913

### PR DESCRIPTION
**Pull request by antonio2368**
Reverts ClickHouse/ClickHouse#56913

Fix https://github.com/ClickHouse/ClickHouse/issues/56969

### CODE REVIEW

**Comment by robot-clickhouse-ci-2** [comment]
*This is an automated comment for commit cd3801456c27312a486e7ce70bb62ce2b7ed7fe3 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/56973/cd3801456c27312a486e7ce70bb62ce2b7ed7fe3/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td><a href="https://github.com/ClickHouse/ClickHouse/actions/runs/6921359009">✅ success</a></td></tr>
<tbody>
</table>
</details>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/56973/cd3801456c27312a486e7ce70bb62ce2b7ed7fe3/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
@antonio2368 You can instead remove this function from the list of functions checked for backward incompatible changes.

**Comment by antonio2368** [comment]
@alexey-milovidov I just wanted a quick merge so master is not broken
There is a PR with real fix https://github.com/ClickHouse/ClickHouse/pull/56975
Should we merge this instantly and have a complete resubmit or just close this and wait for the PR with fix to pass CI?

**Comment by rschu1ze** [comment]
(Didn't test #56975 as integration tests are usually a hassle to set up but I am pretty sure that the fix fixes the issue :-) )

**Pull request closed without merging**
