### PR TITLE
Speedup MIN/MAX for non numeric types

### PR DESCRIPTION
**Pull request by Algunenano**
### Changelog category (leave one):
- Performance Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
- Speedup MIN/MAX for non numeric types

### Documentation entry for user-facing changes

...

Continuation of https://github.com/ClickHouse/ClickHouse/pull/58231, bringing some ideas from https://github.com/ClickHouse/ClickHouse/pull/40633 but with some extra changes. The idea is:

* Not null / Not if: Get the column permutation LIMIT 1 and use that. Simple as that. Reuses code, improvements there will improve min/max automagically.
* Nullable | If: Tested using the permutation (then iterating until the first not null && if found) but it was slower than doing it manually.

In both cases the important part is to avoid copying anything from the block until we know what's the min/max of that block, and only then we compare with the aggregation state. That and removing lots of extra overhead of `SingleValueData*`.

Because who doesn't want to get max(tuple) 30x faster?

### CODE REVIEW

**Comment by robot-clickhouse** [comment]
*This is an automated comment for commit 8a90f12dc9974c543d65a72653b565758c7e128c with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/58334/8a90f12dc9974c543d65a72653b565758c7e128c/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/58334/8a90f12dc9974c543d65a72653b565758c7e128c/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Comment by Avogar** [comment]
The code LGTM, but maybe worth adding a performance test that will show the improvement? Don't see any improvements in current performance tests. Also see one test became slower:
Screenshot 2023-12-29 at 16 35 53

**Comment by Algunenano** [comment]
Few changes:
* Added perf test for min/max tuple, which is the most common generic type to be used in these functions. The common case is to keep multiple columns from the min row (alternative to doing multiple argMin/argMax with the same sorting column).
* Renamed findNumeric to findExtreme and the implementation to a .cpp file, so you can depend on it without depending on the implementation.
* Ignored numeric types from the now default implementation so they keep using the old one. It's likely that we could have a better findExtreme for non native numbers (long integers, Decimals) but this is not the PR to do it.

**Comment by Algunenano** [comment]
To check:
* Clang tidy build (need to add a NOLINT to the macro)
* Check why the perf improvement didn't show. It seems the specific test did not run, but I need to confirm.

**Review by Avogar — APPROVED** [review]

**Comment by Algunenano** [comment]
Finally: image

**Pull request merged**
