### PR TITLE
Update MergeTree.md

### PR DESCRIPTION
**Pull request by dreamerfable**
Update all content in this article，fix wrong formats, fix wrong translation, unified description of main concept, remove deprecated content,add the new features.

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
Documentation (changelog entry is not required)

Detailed description / Documentation draft:
fix wrong formats, like redundant Tabs
fix wrong translation, like translate part to partition
fix some wrong links to improve user experience
replace the old sql template with the new version, it's pretty important
change some confusingly word
unify the translation of main concept, like tranlation of 'DATA PART'
remove deprecated content
add some description to make it more understandability
add the translation of new features , like "Using Multiple Block Devices for Data Storage" ,"function support" and so on
...

### CODE REVIEW

**Comment by blinkov** [comment]
@dreamerfable there're some broken links:
```
WARNING:mkdocs.structure.pages:Documentation file 'engines/table-engines/mergetree-family/mergetree.md' contains a link to 'sql-reference/statements/alter/index.md' which is not found in the documentation files.
WARNING:mkdocs.structure.pages:Documentation file 'engines/table-engines/mergetree-family/mergetree.md' contains a link to 'sql-reference/statements/alter/partition.md' which is not found in the documentation files.
WARNING:mkdocs.structure.pages:Documentation file 'engines/table-engines/mergetree-family/mergetree.md' contains a link to 'sql-reference/statements/alter/index.md' which is not found in the documentation files.
WARNING:mkdocs.structure.pages:Documentation file 'engines/table-engines/mergetree-family/mergetree.md' contains a link to 'sql-reference/statements/alter/partition.md' which is not found in the documentation files.
WARNING:mkdocs.structure.pages:Documentation file 'engines/table-engines/mergetree-family/mergetree.md' contains a link to 'sql-reference/statements/alter/partition.md' which is not found in the documentation files.
```

**Comment by dreamerfable** [comment]
> @dreamerfable there're some broken links:
> 
> ```
> WARNING:mkdocs.structure.pages:Documentation file 'engines/table-engines/mergetree-family/mergetree.md' contains a link to 'sql-reference/statements/alter/index.md' which is not found in the documentation files.
> WARNING:mkdocs.structure.pages:Documentation file 'engines/table-engines/mergetree-family/mergetree.md' contains a link to 'sql-reference/statements/alter/partition.md' which is not found in the documentation files.
> WARNING:mkdocs.structure.pages:Documentation file 'engines/table-engines/mergetree-family/mergetree.md' contains a link to 'sql-reference/statements/alter/index.md' which is not found in the documentation files.
> WARNING:mkdocs.structure.pages:Documentation file 'engines/table-engines/mergetree-family/mergetree.md' contains a link to 'sql-reference/statements/alter/partition.md' which is not found in the documentation files.
> WARNING:mkdocs.structure.pages:Documentation file 'engines/table-engines/mergetree-family/mergetree.md' contains a link to 'sql-reference/statements/alter/partition.md' which is not found in the documentation files.
> ```

Hi there，I copy these links from the en version . I find the file which contains these links has not be created in zh version. I can't translate that article at this time, So could you please tell me which is the better choice for now, change these links point to the en version or change these links to this ariticle ?

**Comment by blinkov** [comment]
@dreamerfable likely for zh version that content is currently located in `sql-reference/statements/alter.md`, you can link there.

**Comment by dreamerfable** [comment]
@blinkov ok, I changed wrong links. thanks.

**Review by blinkov — APPROVED** [review]

**Pull request merged**
