### PR TITLE
Use LLVM 16

### PR DESCRIPTION
**Pull request by alexey-milovidov**
### Changelog category (leave one):
- Build/Testing/Packaging Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
ClickHouse starts to use LLVM (and Clang, LLD, and other tools) version 16 instead of 15.

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
@Felixoid It needs updates for Woboq Code Browser.

**Comment by tavplubix** [comment]
Please remove this as well: https://github.com/ClickHouse/ClickHouse/blob/8c6cf28c01ea2428bad31de0efd7e26c0b99e767/docker/test/stress/run.sh#L23-L24

**Comment by azat** [comment]
@alexey-milovidov any news on this one?

**Comment by alexey-milovidov** [comment]
@azat Woboq Codebrowser has to be updated. There is no progress, and your help will be very appreciated.

**Comment by azat** [comment]
@alexey-milovidov here is a PR made on top of yours, that pushing it forward - #49678

**Pull request closed without merging**
