### PR TITLE
Backport #62297 to 24.3: Vendor rust dependencies

### PR DESCRIPTION
**Pull request by robot-ch-test-poll**
Original pull-request https://github.com/ClickHouse/ClickHouse/pull/62297
Cherry-pick pull-request #71696

This pull-request is a last step of an automated backporting.
Treat it as a standard pull-request: look at the checks and resolve conflicts.
Merge it only if you intend to backport changes to the target branch, otherwise just close it.

### CODE REVIEW

**Comment by Felixoid** [comment]
Let's see if it will fix the issue with building in https://github.com/ClickHouse/ClickHouse/pull/71662

**Comment by robot-ch-test-poll4** [comment]
*This is an automated comment for commit 3df1541ffcd8d1847a65ec76859c5f0b22fc6d14 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/71697/3df1541ffcd8d1847a65ec76859c5f0b22fc6d14/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Push to Dockerhub</td><td>The check for building and pushing the CI related docker images to docker hub</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/71697/3df1541ffcd8d1847a65ec76859c5f0b22fc6d14/push_to_dockerhub_aarch64.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Comment by Felixoid** [comment]
The build is fixed, but there are failing integration tests. Maybe the https://github.com/ClickHouse/ClickHouse/pull/71662 will fix them. Then I'll merge all together

**Comment by Felixoid** [comment]
Tests are fixed in https://github.com/ClickHouse/ClickHouse/pull/71662. Merging it for a proper history

**Pull request merged**
