### PR TITLE
Rebuild projection for merges that reduces rows

### LINKED ISSUE #24778: Projections inconsistent results for ReplacingMergeTree/CollapsingMergeTree
```sql
drop table if exists tp;

create table tp (type Int32, eventcnt UInt64,
projection p (select sum(eventcnt), type group by type)) 
engine = ReplacingMergeTree order by type;

insert into tp select number%3, 1 from numbers(3);
insert into tp select number%3, 2 from numbers(3);

optimize table tp final;

set allow_experimental_projection_optimization = 0, force_optimize_projection = 0;

select sum(eventcnt) eventcnt, type
from tp
group by type
┌─eventcnt─┬─type─┐
│        2 │    0 │
│        2 │    2 │
│        2 │    1 │
└──────────┴──────┘

set allow_experimental_projection_optimization = 1, force_optimize_projection = 1;

select sum(eventcnt) eventcnt, type
from tp
group by type
┌─eventcnt─┬─type─┐
│        3 │    0 │
│        3 │    2 │
│        3 │    1 │
└──────────┴──────┘
```

### PR DESCRIPTION
**Pull request by ardenwick**
Some merging modes can reduce number of rows during merges, where some deleted data in the parent part will still live in projections. So just rebuild all the projections for these modes.

- CollapsingMergeTree
- ReplacingMergeTree
- VersionedCollapsingMergeTree
- `OPTIMIZE DEDUPLICATE`
- `OPTIMIZE CLEANUP`

Trying to close #24778

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Rebuild projection for merges that reduce number of rows

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

---
### Modify your CI run:
**NOTE:** If your merge the PR with modified CI you **MUST KNOW** what you are doing
**NOTE:** Checked options will be applied if set before CI RunConfig/PrepareRunConfig step

#### Include tests (required builds will be added automatically):
- [ ]  Fast test
- [ ]  Integration Tests
- [ ]  Stateless tests
- [ ]  Stateful tests
- [ ]  Unit tests
- [ ]  Performance tests
- [ ]  All with ASAN
- [ ]  All with TSAN
- [ ]  All with Analyzer
- [ ]  Add your option here

#### Exclude tests:
- [ ]  Fast test
- [ ]  Integration Tests
- [ ]  Stateless tests
- [ ]  Stateful tests
- [ ]  Performance tests
- [ ]  All with ASAN
- [ ]  All with TSAN
- [ ]  All with MSAN
- [ ]  All with UBSAN
- [ ]  All with Coverage
- [ ]  All with Aarch64
- [ ]  Add your option here

#### Extra options:
- [ ]  do not test (only style check)
- [ ]  disable merge-commit (no merge from master before tests)
- [ ]  disable CI cache (job reuse)

#### Only specified batches in multi-batch jobs:
- [ ]  1
- [ ]  2
- [ ]  3
- [ ]  4

### CODE REVIEW

**Comment by robot-ch-test-poll1** [comment]
*This is an automated comment for commit 4072c7f457c632d2b00c4ce531fff1b65aaa74cb with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/62364/4072c7f457c632d2b00c4ce531fff1b65aaa74cb/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

**Comment by cangyin** [comment]
Hi, the code is ready for review.

**Comment by amosbird** [comment]
@nikitamikhaylov Sure. Will take a look in this week.

**Comment by nikitamikhaylov** [comment]
Hello @amosbird! I hope things are going well...

**Comment by amosbird** [comment]
@nikitamikhaylov I'm progressing a bit slowly, but it's on track. Will continue this week.

**Comment by jsc0218** [comment]
@cangyin thanks for the contribution, would you mind update this pr to resolve the conflicts, so it is easy to review. Later, after this [pr](https://github.com/ClickHouse/ClickHouse/pull/66672) is merged, we can add rebuild option to this pr? we can follow the logics of this [requirement](https://github.com/ClickHouse/ClickHouse/issues/24778#issuecomment-2228641469).

**Comment by Slach** [comment]
;) heh, is this feature anounces in 24.8 release, will it merged before release?

**Comment by jsc0218** [comment]
have some sync problem, should be merged after the release.

**Pull request merged**
