### PR TITLE
Tests visualizer better

### PR DESCRIPTION
**Pull request by DimaAmega**
Changelog category (leave one):
- Not for changelog

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
### fix tool to visualize flaky tests in web browser:
* better error handling
* added preloader animation for ajax requests (the rotating clickhouse logo 😄)
* better tooltip css style
* better async/await js sintax for asynchronous operations 
* little bit code refactor

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]
LGTM, thank you!

But white shadow and round corner look a bit off for me.
Screenshot_20220107_203958

I prefer it as it was before.
What do you think? If it's alright from your standpoint, let's merge as is.

**Comment by alexey-milovidov** [comment]
Do you know why round corners are *not quite* round, at least on Firefox, Linux, Kubuntu, not-hi-DPI display?

Screenshot_20220107_204319

**Comment by DimaAmega** [comment]
What do you think about that style?
image

**Comment by alexey-milovidov** [comment]
If we also remove shadow, it will be perfect.
This white shadow is very unnatural.

**Comment by DimaAmega** [comment]
> If we also remove shadow, it will be perfect. This white shadow is very unnatural.

done)

**Comment by alexey-milovidov** [comment]
Here is explanation, why rounded corners are wrong: https://alexbourt.medium.com/use-gamma-everywhere-da027d9dc82f

**Comment by DimaAmega** [comment]
> Do you know why round corners are _not quite_ round, at least on Chromium, Linux, Kubuntu, not-hi-DPI display?
> 
> Screenshot_20220107_204319

@alexey-milovidov, Actually, i believe that's all because of linux 😄  (there are no problem on mac os)
On my ubuntu 20.04 it looks the same (pixelated). But if i change scale (using `CTRL`-`+`) It looks nice
I think it will be the same in your case

**Comment by alexey-milovidov** [comment]
Yes, it can be somewhere between the web browser and the underlying system code for renering.
The problem is not only in the size of pixels, but in the fact that the corners appear consistently darker than the edges (someone is performing rasterization without gamma correction).
And if you use Mac Book, or most of modern laptops, they have higher resolution and individual pixels cannot be seen.

**Comment by DimaAmega** [comment]
Yes, I agree

**Pull request merged**
