### PR TITLE
ActionsDAG::split can't make sure that "Execution of first then second parts on block is equivalent to execution of initial DAG.". Fix it

### PR DESCRIPTION
**Pull request by taiyang-li**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
`ActionsDAG::split` can't make sure that "Execution of first then second parts on block is equivalent to execution of initial DAG.", which is declared in comments. It was found by gluten: https://github.com/oap-project/gluten/issues/4723. I believe it was introduced by recent pr: https://github.com/ClickHouse/ClickHouse/pull/58554  cc @KochetovNicolai @baibaichen  

This PR fix it.

### CODE REVIEW

**Comment by taiyang-li** [comment]
Consider original actions_dag is 
```
0 : INPUT () (no column) Nullable(Int64) l_orderkey
1 : INPUT () (no column) Nullable(Int64) l_suppkey
2 : ARRAY JOIN (3) (no column) Nullable(String) assumeNotNull(ifNull(array(l_returnflag,l_linestatus),[]_0))
3 : INPUT () (no column) Array(Nullable(String)) assumeNotNull(ifNull(array(l_returnflag,l_linestatus),[]_0))
Output nodes: 0 1 2
Project input: 0
Projected output: 0
```  

If split_nodes is 2, then original actions_dag is splitted into two parts by current implementation. The first part is 
```
0 : INPUT () (no column) Array(Nullable(String)) assumeNotNull(ifNull(array(l_returnflag,l_linestatus),[]_0))
1 : ARRAY JOIN (0) (no column) Nullable(String) assumeNotNull(ifNull(array(l_returnflag,l_linestatus),[]_0))
Output nodes: 1
Project input: 0
Projected output: 0
```

The second part is 
```
0 : INPUT () (no column) Nullable(Int64) l_orderkey
1 : INPUT () (no column) Nullable(Int64) l_suppkey
2 : INPUT () (no column) Nullable(String) assumeNotNull(ifNull(array(l_returnflag,l_linestatus),[]_0))
Output nodes: 0 1 2
Project input: 0
Projected output: 0
```  

The split result is obviously wrong because there is only 1 output nodes in the first part, but the second part requires 3 input nodes.

**Comment by robot-clickhouse-ci-2** [comment]
*This is an automated comment for commit 1f20030df06646eb103da8a716fefe1548383bdd with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/60206/1f20030df06646eb103da8a716fefe1548383bdd/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/60206/1f20030df06646eb103da8a716fefe1548383bdd/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Comment by baibaichen** [comment]
@taiyang-li thanks!

**Comment by alexey-milovidov** [comment]
I need help from @KochetovNicolai - it is difficult for me to understand this change + it might need a test.

**Comment by baibaichen** [comment]
@KochetovNicolai, any comments

**Comment by taiyang-li** [comment]
@KochetovNicolai Hope for your reviews, thanks!

**Comment by baibaichen** [comment]
@KochetovNicolai 

Any Comments?

**Comment by taiyang-li** [comment]
@KochetovNicolai 
Any comments?

**Comment by Algunenano** [comment]
I'm seeing https://github.com/ClickHouse/ClickHouse/pull/58554 as the cause of some production errors. While I minimize a test case I've created a new PR with these changes so it's updated with master and CI starts verifying them -> https://github.com/ClickHouse/ClickHouse/pull/61458

**Comment by taiyang-li** [comment]
@Algunenano Thanks for your attention. Since you had created a new PR, I'll close current PR.

**Comment by Algunenano** [comment]
Let's look for a reproducer and a test to see how and when this is necessary as it breaks tests (loads files unnecessarily) so it will require more changes.

**Comment by taiyang-li** [comment]
> Let's look for a reproducer and a test to see how and when this is necessary as it breaks tests (loads files unnecessarily) so it will require more changes.

ok, I'll try.

**Pull request closed without merging**
