### PR TITLE
Try to devirtualize format reader in RowInputFormatWithNamesAndTypes 

### PR DESCRIPTION
**Pull request by taiyang-li**
### Changelog category (leave one):
- Performance Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Try to devirtualize format reader in RowInputFormatWithNamesAndTypes, and see if it could bring some performance improvement. 

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [x]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Run only fuzzers related jobs (libFuzzer fuzzers, AST fuzzers, etc.)
- [ ]  Exclude: AST fuzzers
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-ch-test-poll4** [comment]
*This is an automated comment for commit 92a9b29b45c254e670fe9f67114b5af890bfb5cb with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/68437/92a9b29b45c254e670fe9f67114b5af890bfb5cb/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Style check</td><td>Runs a set of checks to keep the code style clean. If some of tests failed, see the related log from the report</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/68437/92a9b29b45c254e670fe9f67114b5af890bfb5cb/style_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Review by Avogar — APPROVED** [review]

**Comment by Avogar** [comment]
Not all tests were run, I see you modified `CI Settings`. Let's don't change them and push another commit to restart the CI

**Comment by taiyang-li** [comment]
> Not all tests were run, I see you modified `CI Settings`. Let's don't change them and push another commit to restart the CI

done.

**Comment by taiyang-li** [comment]
image
 
@Avogar it didn't make sense that those unrelated perf tests suddenly turned out to be slower...  Should I trigger the CI again?

**Pull request merged**
