### PR TITLE
Forbid Dynamic/Variant types in min/max functions to avoid confusion

### PR DESCRIPTION
**Pull request by Avogar**
### Changelog category (leave one):
- Backward Incompatible Change

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Forbid Dynamic/Variant types in min/max functions to avoid confusion

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Run only fuzzers related jobs (libFuzzer fuzzers, AST fuzzers, etc.)
- [ ]  Exclude: AST fuzzers
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-clickhouse** [comment]
*This is an automated comment for commit 75cbf0ca9a832b4b3d8950f544ca770ecfd27d24 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/71761/75cbf0ca9a832b4b3d8950f544ca770ecfd27d24/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/71730/5aa9e64070cda74b65fa6cb639e2c83cd1abee67/docs_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Review by serxa — APPROVED** [review]

**Comment by tavplubix** [comment]
Should we update the changelog entry to "Backward incompatible change"? Also, since the change was backported, we should update changelogs for old releases

**Comment by Avogar** [comment]
> Should we update the changelog entry to "Backward incompatible change"?

I see in the changelog we used `Experimental feature` entry for this PR, maybe it's ok? Or better to make it `Backward incompatible change`?

> Also, since the change was backported, we should update changelogs for old releases

Should I just move this entry to the 24.8 changelog?

**Comment by tavplubix** [comment]
Hm, yes, we can break compatibility of experimental features, so it's ok. It still would be nice to highlight this change somehow, but I don't think we currently have a way to do it

**Comment by clickgapai** [comment]
Hi @Avogar @serxa — while reviewing this PR I found the following:

- **Bug (P2):** Nested Dynamic/Variant in Tuple/Array bypasses min/max type validation — https://github.com/ClickHouse/ClickHouse/issues/104747

Happy to discuss — close anything that's wrong or already addressed.

**Pull request merged**
