### PR TITLE
Replace weak reference count to select query context with strong one in StorageObjectStorageSource

### PR DESCRIPTION
**Pull request by divanik**
### Changelog category:
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
We encountered problem that sometimes link to Context in a Source dies earlier than Source itself, which leads to logical error. In this we replace weak_ptr to context to shared_ptr to prevent this. 

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Run only fuzzers related jobs (libFuzzer fuzzers, AST fuzzers, etc.)
- [ ]  Exclude: AST fuzzers
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-ch-test-poll4** [comment]
*This is an automated comment for commit be7a3bbf6edc3f72fed747a577e92915c557cb71 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/72746/be7a3bbf6edc3f72fed747a577e92915c557cb71/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Style check</td><td>Runs a set of checks to keep the code style clean. If some of tests failed, see the related log from the report</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/72746/be7a3bbf6edc3f72fed747a577e92915c557cb71/style_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Comment by nickitat** [comment]
> sometimes
do we know anything more specific about such cases? in general such issues might be caused for example by lack of proper cancellation of some asynchronous requests. are we sure that there are no real issues?

**Comment by divanik** [comment]
> in general such issues might be caused for example by lack of proper cancellation of some asynchronous requests. are we sure that there are no real issues in `StorageObjectStorageSource` implementation?

I don't know how to verify this except by trying to reproduce error in alert where I met this bug. I stopped investigating the corresponding alert when I understood how the bug could be fixed.

**Review by nickitat — APPROVED** [review]

**Comment by nickitat** [comment]
> how the particular bug could be fixed

again, in general, such fixes could introduce cyclic dependency and memory leak. but tests are green and we could rely on sanitisers.

**Pull request merged**
