### PR TITLE
Refactor merge join transform

### PR DESCRIPTION
**Pull request by Alex-Cheng**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Refactor the `MergeJoinTransform` code:
1. left_map -> left_or_right_map , because in some cases the variable is right map.
2. `std::vector<FullMergeJoinCursorPtr>` -> `std::array<FullMergeJoinCursorPtr, 2>`  , because the container should contain exactly  two elements, i.e. left and right.
3. add an assert to declare that the `cursors` container has two elements.

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]

**Comment by robot-ch-test-poll3** [comment]
*This is an automated comment for commit d5d3cf0e9d0eed5af9589b7f7572115eef431e2f with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/55007/d5d3cf0e9d0eed5af9589b7f7572115eef431e2f/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>✅ success</td></tr>
<tbody>
</table>
</details>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>⏳ pending</td></tr>
<tbody>
</table>

**Comment by alexey-milovidov** [comment]
@Alex-Cheng tests have failed.

**Comment by Alex-Cheng** [comment]
some tests are still failed and seems not be related to my PR. Shall I re-run CI/CD by updating the PR?

**Comment by Alex-Cheng** [comment]
`test_merge_tree_s3/test.py::test_s3_engine_heavy_write_check_mem` seems to be a flacky test.

**Comment by Alex-Cheng** [comment]
`test_checking_s3_blobs_paranoid/test.py::test_query_is_canceled_with_inf_retries` seems to be a flacky.

**Comment by Alex-Cheng** [comment]
image
These failed tests also seems to be a flacky as it is not related to the PR.

**Comment by alexey-milovidov** [comment]
Please update to master.

**Comment by Alex-Cheng** [comment]
> Please update to master.

OK. I have updated now.

**Pull request merged**
