### PR TITLE
Integration tests volume

### PR DESCRIPTION
**Pull request by Felixoid**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Follow up for https://github.com/ClickHouse/ClickHouse/pull/38107

Without it, a new volume is created for each run:

```
/var/lib/docker/volumes# du -hscx * | sort -h
0	backingFsBlockDev
56K	metadata.db
324K	clickhouse_integration_tests_7t4u84_volume
324K	clickhouse_integration_tests_duwt4b_volume
324K	clickhouse_integration_tests_lcitao_volume
324K	clickhouse_integration_tests_mfjky5_volume
1.3G	clickhouse_integration_tests_auk9pw_volume
1.4G	clickhouse_integration_tests_98g5f6_volume
1.4G	clickhouse_integration_tests_q6j1d9_volume
1.5G	clickhouse_integration_tests_0j6336_volume
1.5G	clickhouse_integration_tests_0o9sbm_volume
1.5G	clickhouse_integration_tests_1fevjp_volume
1.5G	clickhouse_integration_tests_l8uozu_volume
1.5G	clickhouse_integration_tests_z2wfos_volume
1.5G	clickhouse_integration_tests_z9ev8u_volume
.......
4.9G	clickhouse_integration_tests_k3gxee_volume
5.3G	clickhouse_integration_tests_rn5rp2_volume
5.4G	clickhouse_integration_tests_vhxeyg_volume
5.5G	clickhouse_integration_tests_2j15ug_volume
5.7G	clickhouse_integration_tests_2r206k_volume
6.3G	clickhouse_integration_tests_adgavp_volume
6.7G	clickhouse_integration_tests_ridcxh_volume
8.3G	clickhouse_integration_tests_dzcd5z_volume
9.4G	clickhouse_integration_tests_rzwdn1_volume
160G	total
```

### CODE REVIEW

**Review by qoega — COMMENTED** [review]
How it will help then? You will get error that volume is used. Probably just 'docker volume prune'?

**Comment by Felixoid** [comment]
The original idea was a reusable volume, and it's 100% fine to have it consistent.

And it doesn't harm to have it mounted in multiple containers:

```
[felixoid@felix-carbon Completion]$ docker run --rm -d --volume=test:/mounted ubuntu:20.04 sleep 100
1f7c9121716b2bb2cbbe019b2a539cdf2019615353314d56f23aff5a18ea4712
[felixoid@felix-carbon Completion]$ docker run --rm -d --volume=test:/mounted ubuntu:20.04 sleep 100
86e63efa8081543ef0edc926a98b7b51137527433d2ba190c08dbb7d3ada9314
[felixoid@felix-carbon Completion]$ docker run --rm -d --volume=test:/mounted ubuntu:20.04 sleep 100
e776c2020d5f8ba3340c7cfec31540e5b832ac8d137d466fd6b8dfdaa85ebbe5
[felixoid@felix-carbon Completion]$ docker run --rm -d --volume=test:/mounted ubuntu:20.04 sleep 100
ad028e9750d8dee7e11616a8274bc4f161e7611c771eb130fc4589a202f022e4
[felixoid@felix-carbon Completion]$ docker ps -a
CONTAINER ID   IMAGE          COMMAND       CREATED         STATUS         PORTS     NAMES
ad028e9750d8   ubuntu:20.04   "sleep 100"   2 seconds ago   Up 1 second              serene_williamson
e776c2020d5f   ubuntu:20.04   "sleep 100"   2 seconds ago   Up 1 second              sharp_galois
86e63efa8081   ubuntu:20.04   "sleep 100"   3 seconds ago   Up 2 seconds             nice_clarke
1f7c9121716b   ubuntu:20.04   "sleep 100"   4 seconds ago   Up 3 seconds             angry_jang
[felixoid@felix-carbon Completion]$ docker volume ls
DRIVER    VOLUME NAME
local     test
```

**Comment by qoega** [comment]
>And it doesn't harm to have it mounted in multiple containers:

We can try, but there may be next level of hard to debug issues if tests will use something common.

**Review by tavplubix — APPROVED** [review]

**Comment by tavplubix** [comment]
However, previous formatting was much more readable as to me.

**Pull request merged**
