### PR TITLE
Fix 68239 sample n

### LINKED ISSUE #68239: SAMPLE n (n is integer) doesn't work
**Describe what's wrong**

SAMPLE n (Here n is a sufficiently large integer) doesn't work

I can't use reproducer because SAMPLE n works only with huge number of rows (100k+)

**Does it reproduce on the most recent release?**

Yes, including head build at the moment of creating this issue

**How to reproduce**

* clickhouse version is 24.6 or 24.7
* Non-default settings - no
* `CREATE TABLE` statement:
```
    CREATE TABLE IF NOT EXISTS table_name
    (
        id UInt64
    )
    ENGINE = MergeTree()
    ORDER BY cityHash64(id)
    SAMPLE BY cityHash64(id);
```

* Insert 10M records with random id (random is mandatory)
* Queries to run that lead to an unexpected result:
```
SELECT count() FROM (
	SELECT * FROM table_name SAMPLE 1_000_000
)
```
It returns 10,000,000, but should approximately 1,000,000

**Expected behavior**

According to the docs: The query is executed on a sample of at least n rows (but not significantly more than this)
It should return not significantly more than this 1,000,000

**Additional context**

On version 23.5 and below it works As I expected
SAMPLE k (k is between 0 and 1) - works the same way as before

### PR DESCRIPTION
**Pull request by denis-hananein**
### Changelog category:
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry:
Fix #68239 SAMPLE n where n is an integer. 

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Run only fuzzers related jobs (libFuzzer fuzzers, AST fuzzers, etc.)
- [ ]  Exclude: AST fuzzers
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by denis-hananein** [comment]
I used reproducible example from this comment https://github.com/ClickHouse/ClickHouse/issues/68239#issuecomment-2289383208 ([fiddle](https://fiddle.clickhouse.com/102031f7-00ed-4597-b4e3-da8e9237d1f7)). 

Results on my local build:
```
./programs/clickhouse client --queries-file ./test.sql
50000000
50
50
50
50
```

**Review by alexey-milovidov — COMMENTED** [review]
Needs a test.

**Comment by denis-hananein** [comment]
> Needs a test.

will an integration test with an output check `n / 2 <= n <= n + n / 2` be fine?

**Comment by alexey-milovidov** [comment]
Yes. Most of the tests are located in `tests/queries/0_stateless` - we can call them "functional tests"
(to not be confused with the `integration` directory, which contains heavy integration tests).

**Review by hanfei1991 — APPROVED** [review]

**Comment by robot-clickhouse-ci-1** [comment]
*This is an automated comment for commit 3ff97813f44d7bfb0561560d27164f4c680d5901 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/68499/3ff97813f44d7bfb0561560d27164f4c680d5901/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/68497/9dee9ecfb4adee4cff099f13afe61bdc2c38170e/docs_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Comment by hanfei1991** [comment]
unrelated broken ci test `00653_verification_monotonic_data_load` (in private)

**Comment by denis-hananein** [comment]
@hanfei1991, should I merge master into my branch, or is it enough to just wait for the CI to re-run?

**Comment by hanfei1991** [comment]
@denis-hananein we can wait. I will take care of it. Thanks!

**Pull request merged**
