### PR TITLE
Remove unread data limit from PeekableReadBuffer

### LINKED ISSUE #18690: PeekableReadBuffer: Memory limit exceed when inserting data by HTTP (20.8)
Error started to appear after migrated 19.9 -> 20.8

Settings
<input_format_parallel_parsing>0</input_format_parallel_parsing>
and
<input_format_values_interpret_expressions>0</input_format_values_interpret_expressions>

do not help

```
2021.01.03 08:01:15.601198 [ 1968 ] {b4472a5e-e463-4852-a0ed-efd90fae6393} <Error> DynamicQueryHandler: Code: 241, e.displayText() = DB::Exception: PeekableReadBuffer: Memory limit exceed, Stack trace (when copying this message, always include the lines below):

0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x18cd2050 in /usr/bin/clickhouse
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0xe63232d in /usr/bin/clickhouse
2. ? @ 0x164be2e2 in /usr/bin/clickhouse
3. DB::PeekableReadBuffer::peekNext() @ 0x164bd633 in /usr/bin/clickhouse
4. DB::PeekableReadBuffer::nextImpl() @ 0x164bd978 in /usr/bin/clickhouse
5. void DB::readQuotedStringInto<true, DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 15ul, 16ul> >(DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 15ul, 16ul>&, DB::ReadBuffer&) @ 0xe67e4f5 in /usr/bin/clickhouse
6. DB::DataTypeString::deserializeTextQuoted(DB::IColumn&, DB::ReadBuffer&, DB::FormatSettings const&) const @ 0x156445a4 in /usr/bin/clickhouse
7. DB::ValuesBlockInputFormat::readRow(std::__1::vector<COW<DB::IColumn>::mutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::mutable_ptr<DB::IColumn> > >&, unsigned long) @ 0x16597b4b in /usr/bin/clickhouse
8. DB::ValuesBlockInputFormat::generate() @ 0x165982cd in /usr/bin/clickhouse
9. DB::ISource::work() @ 0x163e821b in /usr/bin/clickhouse
10. DB::InputStreamFromInputFormat::readImpl() @ 0x163ab46d in /usr/bin/clickhouse
11. DB::IBlockInputStream::read() @ 0x155611cd in /usr/bin/clickhouse
12. DB::InputStreamFromASTInsertQuery::readImpl() @ 0x15973f79 in /usr/bin/clickhouse
13. DB::IBlockInputStream::read() @ 0x155611cd in /usr/bin/clickhouse
14. DB::copyData(DB::IBlockInputStream&, DB::IBlockOutputStream&, std::__1::atomic<bool>*) @ 0x1558415e in /usr/bin/clickhouse
15. DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, DB::Context&, std::__1::function<void (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)>) @ 0x15d06285 in /usr/bin/clickhouse
16. DB::HTTPHandler::processQuery(DB::Context&, Poco::Net::HTTPServerRequest&, HTMLForm&, Poco::Net::HTTPServerResponse&, DB::HTTPHandler::Output&) @ 0x16344c69 in /usr/bin/clickhouse
17. DB::HTTPHandler::handleRequest(Poco::Net::HTTPServerRequest&, Poco::Net::HTTPServerResponse&) @ 0x1634871b in /usr/bin/clickhouse
18. Poco::Net::HTTPServerConnection::run() @ 0x18bb1df3 in /usr/bin/clickhouse
19. Poco::Net::TCPServerConnection::start() @ 0x18bf000b in /usr/bin/clickhouse
20. Poco::Net::TCPServerDispatcher::run() @ 0x18bf0728 in /usr/bin/clickhouse
21. Poco::PooledThread::run() @ 0x18d6ee36 in /usr/bin/clickhouse
22. Poco::ThreadImpl::runnableEntry(void*) @ 0x18d6a230 in /usr/bin/clickhouse
23. start_thread @ 0x7494 in /lib/x86_64-linux-gnu/libpthread-2.24.so
24. clone @ 0xe8aff in /lib/x86_64-linux-gnu/libc-2.24.so
 (version 20.8.11.17 (official build))

```

### PR DESCRIPTION
**Pull request by tavplubix**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fixed `PeekableReadBuffer: Memory limit exceed` error when inserting data with huge strings. Fixes #18690

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
We can write sh test that hits previous limit - just in case.

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
Unit test has to be updated.

**Comment by alexey-milovidov** [comment]
> test_ttl_replicated/test.py::test_ttl_empty_parts

Fixed in master.

**Comment by tavplubix** [comment]
AST fuzzer - #19108
Functional stateless tests (ANTLR debug) - `Logical error: 'Incomplete granules are not allowed while blocks are granules size...` - known issue

**Pull request merged**
