### PR TITLE
Fix HTTP compressors finalization

### PR DESCRIPTION
**Pull request by yakov-olkhovskiy**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix HTTP compressors. Follow-up #58475

Manifests as <Fatal> error when HTTP request includes `compress=1&enable_http_compression=1` along with HTTP header `Accept-Encoding`:
```
curl -vv -d 'SELECT 1,2,3,42' -H 'Accept-Encoding: bz2' -X POST 'http://localhost:8123/?compress=1&enable_http_compression=1'
```
```
2024.01.16 00:09:02.684543 [ 1820868 ] {f7ca0e8c-6df8-4041-8277-1633b1c497bc} <Fatal> : Logical error: 'false && "WriteBuffer is not finalized in destructor."'.
2024.01.16 00:09:02.685075 [ 1820867 ] {} <Trace> BaseDaemon: Received signal 6
2024.01.16 00:09:02.685770 [ 1822771 ] {} <Fatal> BaseDaemon: ########## Short fault info ############
2024.01.16 00:09:02.685889 [ 1822771 ] {} <Fatal> BaseDaemon: (version 24.1.1.1, build id: 340551B33BEA709A0808F0761D6096F813A3209C, git hash: 61889faabd72dcf6199389df581e2
2d0c4cb8a8f) (from thread 1820868) Received signal 6
2024.01.16 00:09:02.685980 [ 1822771 ] {} <Fatal> BaseDaemon: Signal description: Aborted
2024.01.16 00:09:02.686026 [ 1822771 ] {} <Fatal> BaseDaemon:
2024.01.16 00:09:02.686129 [ 1822771 ] {} <Fatal> BaseDaemon: Stack trace: 0x00007f1c2ee969fc 0x00007f1c2ee42476 0x00007f1c2ee287f3 0x000000001390d55f 0x00000000139c8e78 0x
00000000139ca2d4 0x0000000016dc56d4 0x0000000016dd4174 0x0000000016dd4199 0x0000000016dc4894 0x000000001dc9578a 0x000000000aa24bd4 0x000000000aa24b79 0x0000000013d0aeec 0x0
00000001ddb7151 0x000000001ddab074 0x000000001de5abc7 0x000000002328bf59 0x000000002328c79c 0x0000000023461594 0x000000002345e33a 0x000000002345d03e 0x00007f1c2ee94ac3 0x00
007f1c2ef26850
2024.01.16 00:09:02.686227 [ 1822771 ] {} <Fatal> BaseDaemon: ########################################
2024.01.16 00:09:02.686299 [ 1822771 ] {} <Fatal> BaseDaemon: (version 24.1.1.1, build id: 340551B33BEA709A0808F0761D6096F813A3209C, git hash: 61889faabd72dcf6199389df581e2
2d0c4cb8a8f) (from thread 1820868) (query_id: f7ca0e8c-6df8-4041-8277-1633b1c497bc) (query: SELECT 1,2,3,42) Received signal Aborted (6)
2024.01.16 00:09:02.686352 [ 1822771 ] {} <Fatal> BaseDaemon:
2024.01.16 00:09:02.686428 [ 1822771 ] {} <Fatal> BaseDaemon: Stack trace: 0x00007f1c2ee969fc 0x00007f1c2ee42476 0x00007f1c2ee287f3 0x000000001390d55f 0x00000000139c8e78 0x
00000000139ca2d4 0x0000000016dc56d4 0x0000000016dd4174 0x0000000016dd4199 0x0000000016dc4894 0x000000001dc9578a 0x000000000aa24bd4 0x000000000aa24b79 0x0000000013d0aeec 0x0
00000001ddb7151 0x000000001ddab074 0x000000001de5abc7 0x000000002328bf59 0x000000002328c79c 0x0000000023461594 0x000000002345e33a 0x000000002345d03e 0x00007f1c2ee94ac3 0x00
007f1c2ef26850
2024.01.16 00:09:02.686497 [ 1822771 ] {} <Fatal> BaseDaemon: 4. ? @ 0x00007f1c2ee969fc in ?
2024.01.16 00:09:02.686551 [ 1822771 ] {} <Fatal> BaseDaemon: 5. ? @ 0x00007f1c2ee42476 in ?
2024.01.16 00:09:02.686605 [ 1822771 ] {} <Fatal> BaseDaemon: 6. ? @ 0x00007f1c2ee287f3 in ?
2024.01.16 00:09:02.785902 [ 1822771 ] {} <Fatal> BaseDaemon: 7. /home/ubuntu/ClickHouse-insjoin/src/Common/Exception.cpp:0: DB::abortOnFailedAssertion(String const&) @ 0x0
00000001390d55f in /home/ubuntu/ClickHouse-insjoin/build_debug/programs/clickhouse
2024.01.16 00:09:02.814179 [ 1822771 ] {} <Fatal> BaseDaemon: 8. /home/ubuntu/ClickHouse-insjoin/src/IO/WriteBuffer.cpp:28: DB::WriteBuffer::~WriteBuffer() @ 0x00000000139c
8e78 in /home/ubuntu/ClickHouse-insjoin/build_debug/programs/clickhouse
2024.01.16 00:09:02.849031 [ 1822771 ] {} <Fatal> BaseDaemon: 9. /home/ubuntu/ClickHouse-insjoin/src/IO/BufferWithOwnMemory.h:150: DB::BufferWithOwnMemory<DB::WriteBuffer>:
:~BufferWithOwnMemory() @ 0x00000000139ca2d4 in /home/ubuntu/ClickHouse-insjoin/build_debug/programs/clickhouse
2024.01.16 00:09:02.897046 [ 1822771 ] {} <Fatal> BaseDaemon: 10. /home/ubuntu/ClickHouse-insjoin/src/IO/WriteBufferDecorator.h:18: DB::WriteBufferDecorator<DB::BufferWithO
wnMemory<DB::WriteBuffer>>::~WriteBufferDecorator() @ 0x0000000016dc56d4 in /home/ubuntu/ClickHouse-insjoin/build_debug/programs/clickhouse
2024.01.16 00:09:02.922463 [ 1822771 ] {} <Fatal> BaseDaemon: 11. /home/ubuntu/ClickHouse-insjoin/src/IO/Bzip2WriteBuffer.cpp:36: DB::Bzip2WriteBuffer::~Bzip2WriteBuffer()
@ 0x0000000016dd4174 in /home/ubuntu/ClickHouse-insjoin/build_debug/programs/clickhouse
2024.01.16 00:09:02.947788 [ 1822771 ] {} <Fatal> BaseDaemon: 12. /home/ubuntu/ClickHouse-insjoin/src/IO/Bzip2WriteBuffer.cpp:36: DB::Bzip2WriteBuffer::~Bzip2WriteBuffer()
@ 0x0000000016dd4199 in /home/ubuntu/ClickHouse-insjoin/build_debug/programs/clickhouse
2024.01.16 00:09:02.994841 [ 1822771 ] {} <Fatal> BaseDaemon: 13. /home/ubuntu/ClickHouse-insjoin/contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:49: std::default
_delete<DB::WriteBuffer>::operator()[abi:v15000](DB::WriteBuffer*) const @ 0x0000000016dc4894 in /home/ubuntu/ClickHouse-insjoin/build_debug/programs/clickhouse
2024.01.16 00:09:03.003885 [ 1821503 ] {} <Trace> AsynchronousMetrics: MemoryTracking: was 588.97 MiB, peak 593.00 MiB, free memory in arenas 131.96 MiB, will set to 726.07
 MiB (RSS), difference: 137.09 MiB
2024.01.16 00:09:03.633403 [ 1822771 ] {} <Fatal> BaseDaemon: 14. /home/ubuntu/ClickHouse-insjoin/contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:263: std::__shar
ed_ptr_pointer<DB::WriteBuffer*, std::default_delete<DB::WriteBuffer>, std::allocator<DB::WriteBuffer>>::__on_zero_shared() @ 0x000000001dc9578a in /home/ubuntu/ClickHouse-
insjoin/build_debug/programs/clickhouse
2024.01.16 00:09:03.722939 [ 1822771 ] {} <Fatal> BaseDaemon: 15. /home/ubuntu/ClickHouse-insjoin/contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:175: std::__shar
ed_count::__release_shared[abi:v15000]() @ 0x000000000aa24bd4 in /home/ubuntu/ClickHouse-insjoin/build_debug/programs/clickhouse
2024.01.16 00:09:03.812244 [ 1822771 ] {} <Fatal> BaseDaemon: 16. /home/ubuntu/ClickHouse-insjoin/contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:215: std::__shar
ed_weak_count::__release_shared[abi:v15000]() @ 0x000000000aa24b79 in /home/ubuntu/ClickHouse-insjoin/build_debug/programs/clickhouse
2024.01.16 00:09:03.908493 [ 1822771 ] {} <Fatal> BaseDaemon: 17. /home/ubuntu/ClickHouse-insjoin/contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:703: std::shared
_ptr<DB::WriteBuffer>::~shared_ptr[abi:v15000]() @ 0x0000000013d0aeec in /home/ubuntu/ClickHouse-insjoin/build_debug/programs/clickhouse
2024.01.16 00:09:04.003828 [ 1821503 ] {} <Trace> AsynchronousMetrics: MemoryTracking: was 726.07 MiB, peak 726.07 MiB, free memory in arenas 132.00 MiB, will set to 827.82
 MiB (RSS), difference: 101.75 MiB
2024.01.16 00:09:04.124539 [ 1822771 ] {} <Fatal> BaseDaemon: 18. /home/ubuntu/ClickHouse-insjoin/src/Server/HTTPHandler.h:47: DB::HTTPHandler::Output::~Output() @ 0x000000
001ddb7151 in /home/ubuntu/ClickHouse-insjoin/build_debug/programs/clickhouse
2024.01.16 00:09:04.326570 [ 1822771 ] {} <Fatal> BaseDaemon: 19. /home/ubuntu/ClickHouse-insjoin/src/Server/HTTPHandler.cpp:1131: DB::HTTPHandler::handleRequest(DB::HTTPSe
rverRequest&, DB::HTTPServerResponse&, StrongTypedef<unsigned long, ProfileEvents::EventTag> const&) @ 0x000000001ddab074 in /home/ubuntu/ClickHouse-insjoin/build_debug/pro
grams/clickhouse
2024.01.16 00:09:04.352564 [ 1822771 ] {} <Fatal> BaseDaemon: 20. /home/ubuntu/ClickHouse-insjoin/src/Server/HTTP/HTTPServerConnection.cpp:70: DB::HTTPServerConnection::run
() @ 0x000000001de5abc7 in /home/ubuntu/ClickHouse-insjoin/build_debug/programs/clickhouse
2024.01.16 00:09:04.375774 [ 1822771 ] {} <Fatal> BaseDaemon: 21. /home/ubuntu/ClickHouse-insjoin/base/poco/Net/src/TCPServerConnection.cpp:43: Poco::Net::TCPServerConnecti
on::start() @ 0x000000002328bf59 in /home/ubuntu/ClickHouse-insjoin/build_debug/programs/clickhouse
2024.01.16 00:09:04.405781 [ 1822771 ] {} <Fatal> BaseDaemon: 22. /home/ubuntu/ClickHouse-insjoin/base/poco/Net/src/TCPServerDispatcher.cpp:115: Poco::Net::TCPServerDispatc
her::run() @ 0x000000002328c79c in /home/ubuntu/ClickHouse-insjoin/build_debug/programs/clickhouse
2024.01.16 00:09:04.438307 [ 1822771 ] {} <Fatal> BaseDaemon: 23. /home/ubuntu/ClickHouse-insjoin/base/poco/Foundation/src/ThreadPool.cpp:188: Poco::PooledThread::run() @ 0
x0000000023461594 in /home/ubuntu/ClickHouse-insjoin/build_debug/programs/clickhouse
2024.01.16 00:09:04.468876 [ 1822771 ] {} <Fatal> BaseDaemon: 24. /home/ubuntu/ClickHouse-insjoin/base/poco/Foundation/src/Thread.cpp:46: Poco::(anonymous namespace)::Runna
bleHolder::run() @ 0x000000002345e33a in /home/ubuntu/ClickHouse-insjoin/build_debug/programs/clickhouse
2024.01.16 00:09:04.498020 [ 1822771 ] {} <Fatal> BaseDaemon: 25. /home/ubuntu/ClickHouse-insjoin/base/poco/Foundation/src/Thread_POSIX.cpp:335: Poco::ThreadImpl::runnableE
ntry(void*) @ 0x000000002345d03e in /home/ubuntu/ClickHouse-insjoin/build_debug/programs/clickhouse
2024.01.16 00:09:04.498109 [ 1822771 ] {} <Fatal> BaseDaemon: 26. ? @ 0x00007f1c2ee94ac3 in ?
2024.01.16 00:09:04.498179 [ 1822771 ] {} <Fatal> BaseDaemon: 27. ? @ 0x00007f1c2ef26850 in ?
2024.01.16 00:09:04.498252 [ 1822771 ] {} <Fatal> BaseDaemon: Integrity check of the executable skipped because the reference checksum could not be read.
2024.01.16 00:09:04.498322 [ 1822771 ] {} <Information> SentryWriter: Not sending crash report
2024.01.16 00:09:04.498397 [ 1822771 ] {} <Fatal> BaseDaemon: This ClickHouse version is not official and should be upgraded to the official build.
```

### CODE REVIEW

**Comment by robot-ch-test-poll2** [comment]
*This is an automated comment for commit fcd4297d20114ed98c68e460147c1e287e5742ef with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/58846/fcd4297d20114ed98c68e460147c1e287e5742ef/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/58846/fcd4297d20114ed98c68e460147c1e287e5742ef/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Comment by alexey-milovidov** [comment]
Please add a test.

PS. It does not seem right to call finalize in destructor. The ideal flow is when you call finalize explicitly before the call to the destructor, or, if you didn't, the destructor ignores the data.

But this change is also ok for me.

**Comment by antonio2368** [comment]
This is reverting work done by @CheSema in https://github.com/ClickHouse/ClickHouse/pull/50395

**Comment by novikd** [comment]
I agree with @antonio2368 I think it's better to find where buffers should call `finalize` and do it explicitly.

**Comment by CheSema** [comment]
> if you didn't, the destructor ignores the data.

You are understand right what would happen. That could lead to data loss. 

> But this change is also ok for me.

I don't think that it is could ever be ok.

**Comment by yakov-olkhovskiy** [comment]
@CheSema I would argue that it's not always practical to not utilize destructor for the exact purpose destructor exists - for example if we use temporary object or some cases of exception processing. Data loss is rather signifier of incorrect objects' ownership, lack of proper objects' initialization and similar issues. Though I agree that in this particular case it's better to add explicit finalization, overall if we have a case when finalization in destructor leads to data loss or data corruption - there is a deeper problem worth of investigation and proper fix.

**Comment by CheSema** [comment]
> @CheSema I would argue that it's not always practical to not utilize destructor for the exact purpose destructor exists - for example if we use temporary object or some cases of exception processing. Data loss is rather signifier of incorrect objects' ownership, lack of proper objects' initialization and similar issues. Though I agree that in this particular case it's better to add explicit finalization, overall if we have a case when finalization in destructor leads to data loss or data corruption - there is a deeper problem worth of investigation and proper fix.

I do not argue here at all. 
Using d-tor is OK. Mute the error which could be thrown at finalization -- not OK. There is nothing to argue about.

There is a deep problem -- we use buffers API to write a file. All this task/conversation is a consequences of that problem.

**Comment by yakov-olkhovskiy** [comment]
>Mute the error which could be thrown at finalization -- not OK.
It's not muted - it's reported in catch. I understand the concern of having finalize in destructor can encourage ppl to neglect explicit finalization, but maybe it shouldn't outweigh the usefulness of this...

**Comment by yakov-olkhovskiy** [comment]
@CheSema @novikd could you please expedite review? so I could merge it as CI finish - ppl need it ASAP

**Review by alexey-milovidov — APPROVED** [review]

**Pull request merged**
