### PR TITLE
AvroConfluent integration test

### PR DESCRIPTION
**Pull request by oandrew**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Integration Test

Continuation of #8717

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
@alesapin `No module named confluent.schemaregistry.client`

**Comment by oandrew** [comment]
I'm guessing CI doesn't  build new `yandex/clickhouse-integration-tests-runner` image from Dockerfile i.e. someone needs to build and publish it manually

**Comment by alexey-milovidov** [comment]
Yes, I asked @alesapin for this reason.

**Comment by oandrew** [comment]
Looks like the image has been updated - the test is passing now

**Comment by alesapin** [comment]
Performance not related.

**Pull request merged**
