### PR TITLE
[WIP] Added a test for another possible deadlock scenario in RWLock

### PR DESCRIPTION
**Pull request by Akazz**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

For changelog. Remove if this is non-significant change.

Category (leave one):
- Improvement

Short description (up to few sentences):
A potential deadlock scenario with locking a table recursively for _Read_ by a background thread while some concurrent thread is trying to lock the same table for _Write_

### CODE REVIEW

**Comment by Akazz** [comment]
Threads stalling in a typical mutual DL
```
#2  __pthread_cond_wait (cond=0x7f44cec00030, mutex=0x7f44d179ee90) at pthread_cond_wait.c:655
#3  0x00005605da61bf5c in std::condition_variable::wait(std::unique_lock<std::mutex>&) ()
#4  0x00005605d98a524e in std::condition_variable::wait<DB::RWLockImpl::getLock(DB::RWLockImpl::Type, const String&)::<lambda()> >(std::unique_lock<std::mutex> &, DB::RWLockImpl::<lambda()>) (
    this=0x7f44cec00030, __lock=..., __p=...) at /usr/include/c++/8/condition_variable:99
#5  0x00005605d98a4dd3 in DB::RWLockImpl::getLock (this=0x7f44d179ee80, type=DB::RWLockImpl::Write, query_id=...) at ../dbms/src/Common/RWLock.cpp:183
#6  0x00005605d3c982a6 in Common_RWLock_Deadlock_WRWR_Test::<lambda()>::operator()(void) const (__closure=0x7f44d24af7c8) at ../dbms/src/Common/tests/gtest_rw_lock.cpp:193

```

```
#2  __pthread_cond_wait (cond=0x7f44cf000090, mutex=0x7f44d179ee90) at pthread_cond_wait.c:655
#3  0x00005605da61bf5c in std::condition_variable::wait(std::unique_lock<std::mutex>&) ()
#4  0x00005605d98a524e in std::condition_variable::wait<DB::RWLockImpl::getLock(DB::RWLockImpl::Type, const String&)::<lambda()> >(std::unique_lock<std::mutex> &, DB::RWLockImpl::<lambda()>) (
    this=0x7f44cf000090, __lock=..., __p=...) at /usr/include/c++/8/condition_variable:99
#5  0x00005605d98a4dd3 in DB::RWLockImpl::getLock (this=0x7f44d179ee80, type=DB::RWLockImpl::Read, query_id=...) at ../dbms/src/Common/RWLock.cpp:183

```

**Comment by alexey-milovidov** [comment]
What is the status of this PR? Why don't we see the hang in unit tests in CI? Is it already fixed and can be merged?

**Comment by Akazz** [comment]
This test challenges race condition in destructor of our `RWLockImpl::LockHolder`. After #6854  the chance of the race here decreased somewhat.

This test needs to be revisited to get consistent failures with the current implementation of `RWLockImpl::LockHolder`. I suggest we hold this PR until `RWLockImpl::LockHolder` is no longer based on `shared_ptr`

**Comment by alexey-milovidov** [comment]
Ivan Blinkov has assigned this PR by mistake.
He has written a script that assigns pull requests randomly but he has failed.

**Pull request closed without merging**
