### PR TITLE
Cancel merges before renaming a system log table

### PR DESCRIPTION
**Pull request by tavplubix**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

See https://github.com/ClickHouse/ClickHouse/issues/47040#issuecomment-1660033856

### CODE REVIEW

**Comment by robot-ch-test-poll1** [comment]
This is an automated comment for commit 9ed8e2ee73f9aa5927d316932f6950ac427f814a with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/52858/9ed8e2ee73f9aa5927d316932f6950ac427f814a/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Review by vdimir — APPROVED** [review]
What are the pitfalls associated with merges during rename? Do we produce parts that are not valid, only to be thrown away after renaming?
Do we stop merges when renaming other tables?

**Comment by tavplubix** [comment]
It's for `Ordinary` database, RENAME changes data path on disk, so we should not touch table data concurrently. We use RWLocks to avoid race conditions.

**Comment by tavplubix** [comment]
Upgrade check (tsan) - https://github.com/ClickHouse/ClickHouse/issues/51586

**Pull request merged**
