### PR TITLE
Fix query formatting in Performance test

### PR DESCRIPTION
**Pull request by alexey-milovidov**
Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
@azat If you know Python, please suggest what will be better solution.

**Comment by azat** [comment]
>@azat If you know Python, please suggest what will be better solution.

Can you give me a link to the bad report/

**Comment by alexey-milovidov** [comment]
@azat Every report is bad:

**Comment by alexey-milovidov** [comment]
Not fixed :cry: 

Screenshot_20211125_045740

**Comment by akuzm** [comment]
I'd pass the query text through `clickhouse-format` in the `perf.py` script before it even runs it, and format to single line. At least this should help with `\n`.

If you want to fix it in `report.py`, you have to fix every place where query text is read, i.e. each table separately.

**Comment by Algunenano** [comment]
You can trick python to do the job with something like https://github.com/ClickHouse/ClickHouse/pull/31780 I'm not sure if all the corner cases are covered, but at least it fixes the obvious ones.

**Pull request closed without merging**
