### PR TITLE
More strict coverage flush.

### PR DESCRIPTION
**Pull request by alesapin**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Build/Testing/Packaging Improvement

Changelog entry (up to few sentences, required except for Non-significant/Documentation categories):
Add coverage file flush for clickhouse-server when std::atexit is not called. Also slightly improved logging in stateless tests with coverage.

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
Stress test: @Enmk issue with function `now64`.

**Comment by alesapin** [comment]
it doesn't help :(

**Comment by alesapin** [comment]
Don't merge.

**Comment by alesapin** [comment]
Ohh, tried to fix known issue https://github.com/ClickHouse/ClickHouse/issues/8233. Our server doesn't correctly stop after full functional stateless tests run, so we don't have `.profraw` coverage file. @Akazz investigating the issue. 

This pull request can be merged.

**Pull request merged**
