### PR TITLE
Add docs for Meilisearch

### PR DESCRIPTION
**Pull request by DanRoscigno**
### Changelog category (leave one):
- Documentation (changelog entry is not required)

...

### CODE REVIEW

**Comment by DanRoscigno** [comment]
@kssenii please advise on the meiliMatch query, it is not working for me.

**Comment by DanRoscigno** [comment]
I noticed that you revived this @alexey-milovidov .  The integration partially worked on Meilisearch version 0.27 -- only the most basic query, specifically select count(), worked.  No queries at all worked on 0.28.

**Comment by alexey-milovidov** [comment]
What is the reason queries did not work?
If it is easy to fix, we can fix it.
If not, let's remove this integration altogether.

**Comment by kssenii** [comment]
As I see by integration tests which run in CI every day - not only select count() should work:
https://github.com/ClickHouse/ClickHouse/blob/41a3536227ea10720a4b419287522b03c2e29d6b/tests/integration/test_storage_meilisearch/test.py#L185-L188
https://github.com/ClickHouse/ClickHouse/blob/41a3536227ea10720a4b419287522b03c2e29d6b/tests/integration/test_storage_meilisearch/test.py#L658-L668
https://github.com/ClickHouse/ClickHouse/blob/41a3536227ea10720a4b419287522b03c2e29d6b/tests/integration/test_storage_meilisearch/test.py#L818-L853
though I did not check it outside of integration tests myself, but it seems - if it is able to run in our integration tests then it should work as well outside.

**Comment by DanRoscigno** [comment]
Thanks @kssenii At the time I started working on this, version 0.27 of Meilisearch worked for a simple "select count()".  It did not work for anything else with clickhouse-client.  If the test passed, it may be because of the way the tests communicate with Meilisearch using python, I do not know.  When we spoke about this last year we could not figure out how to escape the queries in clickhouse-client, maybe you know how to do this now?

As of version 0.28 of Meilisearch no queries worked, they failed with an error about attributesToRetrieve.  I believe this is the error that version 0.28 returned (this is the error returned from version 1.0 of Meilisearch released 3 days ago):
```
Received exception from server (version 22.13.1):
Code: 656. DB::Exception: Received from localhost:9000. DB::Exception: Unknown parameter `attributesToRetrieve`: expected one of `offset`, `limit`, `fields`: While executing MeiliSearchSource. (MEILISEARCH_EXCEPTION)
```

**Comment by DanRoscigno** [comment]
PR to [update the test docker compose file](https://github.com/ClickHouse/ClickHouse/pull/46221)

**Comment by kssenii** [comment]
> When we spoke about this last year we could not figure out how to escape the queries in clickhouse-client, maybe you know how to do this now?

Not sure, need to check myself then, but normally it should be fine with one `\` or two `\\` or none, no other option.

About meilisearch version. In out integration tests we use `27.0`:
https://github.com/ClickHouse/ClickHouse/blob/282695e7e73e634a5b06e606127820b627fd715c/docker/test/integration/runner/compose/docker_compose_meili.yml#L1-L15
May be try with the same docker image?
And if it works with `27.0` and not with other versions, then we must fix it.

**Comment by DanRoscigno** [comment]
I tested with the docker compose using 0.27.0, only select count() works, the escaping I could not figure out.

**Comment by DanRoscigno** [comment]
I will look back at the release webinar slides, I know that the escaping that Alexey used in the webinar was different.

**Comment by DanRoscigno** [comment]
I switched back to Meilisearch 0.27.0, and this escaping works `meiliMatch($$ "q"="abaca" $$)`, which gets transformed into:
```sql
SELECT count()
FROM movies_table
WHERE meiliMatch(' "q" = "abaca" ')
```

 Once ClickHouse can be made to integrate with Meilisearch version 1.0, then I will work on documenting the integration.

**Comment by kssenii** [comment]
> I tested with the docker compose using 0.27.0, only select count() works

which error you get in other cases?

**Comment by DanRoscigno** [comment]
using Meilisearch 0.28.0:

```
SELECT COUNT()
FROM movies_table2

Query id: 3f1935d0-d280-418e-94f8-c17890c4028b


0 rows in set. Elapsed: 0.002 sec. 

Received exception from server (version 22.7.1):
Code: 656. DB::Exception: Received from localhost:9000. DB::Exception: Query deserialize error: unknown field `attributesToRetrieve`, expected one of `offset`, `limit`, `fields`: While executing MeiliSearchSource. (MEILISEARCH_EXCEPTION)
```

**Comment by kssenii** [comment]
>  >I tested with the docker compose using 0.27.0, only select count() works

> which error you get in other cases?

I was asking about version 0.27, which error do you get when you query not only select count()?

**Comment by DanRoscigno** [comment]
For 0.27.0 using the escaping `$$ ` meiliMatch() works in clickhouse-local.  I did not try working out the queries with sorting or filtering as I do not have time to invest in testing this that extensively this week.  Once ClickHouse works with Meilisearch 1.0 I will work on the docs using the filtering and sorting commands in the Meilisearch docs.  All the details on escaping are in our slack conversation from July 2022.  I think we were missing a space between the `$$` and the query to be passed to Meilisearch. 

For 0.27.0 this works:
```sql
SELECT count()
          FROM movies_table
          WHERE meiliMatch($$ "q" = "abaca" $$)
```
```
┌─count()─┐
│       8 │
└─────────┘

1 row in set. Elapsed: 0.005 sec. 
```

I tried this to set the sortable and filterable attrs:
```
curl \
  -X PATCH 'http://localhost:7700/indexes/movies/settings' \
  -H 'Content-Type: application/json' -H 'Authorization: Bearer password' \
  --data-binary '{
    "filterableAttributes": [
      "release_date"
    ],
    "sortableAttributes": [
      "release_date"
    ]
  }'
```

but still seeing:
```
SELECT *
FROM movies_table
WHERE meiliMatch(' "q"="abaca" ', ' "sort"=["release_date:asc"] ', ' "filter"="release_date < 700000000" ')
FORMAT JSONEachRow
SETTINGS output_format_json_quote_64bit_integers = 0

Query id: 8a6df31e-4572-43f3-8eac-a1f70d88e0ff


0 rows in set. Elapsed: 0.003 sec. 

Received exception from server (version 22.13.1):
Code: 656. DB::Exception: Received from localhost:9000. DB::Exception: "message":"Attribute `release_date` is not filterable. This index does not have configured filterable attributes.\n1:13 release_date < 700000000": While executing MeiliSearchSource. (MEILISEARCH_EXCEPTION)
```

**Comment by DanRoscigno** [comment]
@kssenii I suspect that this commit will shed some light on the problem with 0.28.0 and above:
https://github.com/meilisearch/meilisearch/commit/ddad6cc0691de278becdc04b47033d2267dd3c44

**Comment by DanRoscigno** [comment]
@kssenii are you fixing this, or should I close this?

**Comment by kssenii** [comment]
Please don't close, looking at meilisearch is in my queue of what I need to do, haven't got to it yet. Will try to do this week.

**Comment by DanRoscigno** [comment]
Thanks so much! If I can help, ping me!

**Pull request closed without merging**
