### PR TITLE
Support content_type in HTTP handler config

### LINKED ISSUE #34531: A setting `content_type` to force specified `Content-Type` in output.
I want to add a `predefined_query_handler` to serve a single JSON from my query.
For example

```xml
<rule>
      <url>/my/url</url>
      <methods>GET</methods>
      <handler>
        <type>predefined_query_handler</type>
        <query>select '{"my": "json"}' format JSONAsString</query>
      </handler>
    </rule>
```

I can use `RawBLOB` but it sets up Content-Type 'text/plain' instead of 'application/json'.
I think JSONAsString should also work with output.

### PR DESCRIPTION
**Pull request by nic11**
Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Added support for specifying `content_type` in predefined and static HTTP handler config.

> Information about CI checks: https://clickhouse.tech/docs/en/development/continuous-integration/

Closes #34531

### CODE REVIEW

**Comment by kitaisreal** [comment]
@Mergifyio update

**Review by kitaisreal — CHANGES_REQUESTED** [review]
@nic11 need to add integration test same as `test_http_handlers_config`.

**Review by alexey-milovidov — COMMENTED** [review]
The code LGTM.

**Comment by LGDHuaOPER** [comment]
I have a question. Why do I add `http_handlers > rule` configuration in config.xml, then I exec `curl localhost:8123` or `curl localhost:8123/replicas_status`, it made the following error:
550AC34ECE7B64EBC8325B007F1EC20E

The http_handlers rule is:
image

Thanks!

**Pull request merged**
