### PR TITLE
Doc change. Added links to other doc articles (distributed.md)

### PR DESCRIPTION
**Pull request by den-crane**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en
Category (leave one):
- Documentation

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]

**Comment by den-crane** [comment]
I don't see a problem with Check. Maybe it's a false positive. Please merge it. I'll fix it later if real issue after rendering into HTML.

**Comment by blinkov** [comment]
> I don't see a problem with Check. Maybe it's a false positive. Please merge it. I'll fix it later if real issue after rendering into HTML.

@den-crane this might be a bug in docs build scripts, but if we just merge there will be no rendered html to check, it'll just stop releasing new versions until this is fixed

**Comment by den-crane** [comment]
OK. I'll try to change `access_rights` link. 

INFO:root:Tag <a href="#../access_rights/">Access rights</a>
INFO:root:Link to nowhere: #../access_rights/

**Comment by blinkov** [comment]
I'd try something like ../../operations/access_rights.md

**Comment by den-crane** [comment]
> I'd try something like ../../operations/access_rights.md

Thank you. I had the same idea.

**Pull request merged**
