### PR TITLE
Table CREATE DROP Poco::Logger memory leak fix

### LINKED ISSUE #57931: Suspected memory leak in 23.8
Migrated from https://github.com/ClickHouse/ClickHouse/issues/54483 as a separate issue, since we are not using Kafka.

**Describe the unexpected behaviour**

Using ClickHouse 23.8.2.7. Memory increases with database usage, apparently a memory leak. After restarting memory is reduced drastically, then starts climbing up again at around 300 MB / day.

image

**How to reproduce**
* Which ClickHouse server version to use: ClickHouse 23.8.2.7
* One particular database has a somewhat non-standard usage: it receives a lot of inserts but they usually last for less than a minute, it is a sort of internal cache. There we see memory usage raising at around 700 MB / day. But we see the same effect in other ClickHouse servers with the same version, less pronounced (300 MB / day). Memory is always released upon restart.

**Expected behavior**

Since no new data is being stored we would expect that the database should recycle memory internally without having to restart it.

**Additional context**

All queries run on a particular instance that is using ~19 GB right now. Merges, as requested by @antaljanosbenjamin:
```
SELECT
    formatReadableSize(memory_usage),
    *
FROM system.merges

Ok.

0 rows in set. Elapsed: 0.001 sec. 
```

Memory stats, as requested by @azat:
```
WITH
    (
        SELECT sum(CAST(value, 'UInt64'))
        FROM system.metrics
        WHERE metric = 'MemoryTracking'
    ) AS memory_tracked_,
    (
        SELECT sum(total_bytes)
        FROM system.tables
        WHERE engine IN ('Join', 'Memory', 'Buffer', 'Set')
    ) AS memory_tables_,
    (
        SELECT sum(CAST(value, 'UInt64'))
        FROM system.asynchronous_metrics
        WHERE metric LIKE '%CacheBytes'
    ) AS memory_caches_,
    (
        SELECT sum(CAST(memory_usage, 'UInt64'))
        FROM system.processes
    ) AS memory_processes_,
    (
        SELECT sum(CAST(memory_usage, 'UInt64'))
        FROM system.merges
    ) AS memory_merges_,
    (
        SELECT sum(bytes_allocated)
        FROM system.dictionaries
    ) AS memory_dictionaries_,
    (
        SELECT sum(primary_key_bytes_in_memory_allocated)
        FROM system.parts
    ) AS memory_primary_keys_
SELECT
    assumeNotNull(memory_tracked_) AS memory_tracked,
    assumeNotNull(memory_tables_) AS memory_tables,
    assumeNotNull(memory_caches_) AS memory_caches,
    assumeNotNull(memory_processes_) AS memory_processes,
    assumeNotNull(memory_merges_) AS memory_merges,
    assumeNotNull(memory_dictionaries_) AS memory_dictionaries,
    assumeNotNull(memory_primary_keys_) AS memory_primary_keys
FORMAT Vertical

Row 1:
──────
memory_tracked:      19684595772
memory_tables:       0
memory_caches:       4538334048
memory_processes:    175800
memory_merges:       0
memory_dictionaries: 0
memory_primary_keys: 2427744
```

and more:
```
SELECT
    metric,
    value
FROM system.asynchronous_metrics
WHERE metric LIKE '%jemalloc%'

┌─metric───────────────────────────────────┬────────value─┐
│ jemalloc.epoch                           │      1507330 │
│ jemalloc.arenas.all.pactive              │      4466147 │
│ jemalloc.background_thread.num_runs      │            0 │
│ jemalloc.active                          │  18293338112 │
│ jemalloc.retained                        │ 286359556096 │
│ jemalloc.arenas.all.pmuzzy               │         3687 │
│ jemalloc.allocated                       │  18102287104 │
│ jemalloc.background_thread.num_threads   │            0 │
│ jemalloc.metadata_thp                    │            0 │
│ jemalloc.arenas.all.muzzy_purged         │   6963334478 │
│ jemalloc.arenas.all.dirty_purged         │  11647316965 │
│ jemalloc.mapped                          │  19758575616 │
│ jemalloc.metadata                        │   1241636848 │
│ jemalloc.resident                        │  19578085376 │
│ jemalloc.background_thread.run_intervals │            0 │
│ jemalloc.arenas.all.pdirty               │        14069 │
└──────────────────────────────────────────┴──────────────┘
```

Memory allocated:

```
SELECT
    *,
    allocations - deallocations AS active_allocations,
    size * active_allocations AS allocated_bytes
FROM system.jemalloc_bins
WHERE allocated_bytes > 0
ORDER BY allocated_bytes DESC

┌─index─┬─large─┬──────size─┬─allocations─┬─deallocations─┬─active_allocations─┬─allocated_bytes─┐
│    12 │     0 │       256 │  1964164752 │    1934402605 │           29762147 │      7619109632 │
│     4 │     0 │        64 │  8765929776 │    8725048938 │           40880838 │      2616373632 │
│     5 │     0 │        80 │  2965546952 │    2933024532 │           32522420 │      2601793600 │
│    11 │     0 │       224 │   850928924 │     839491604 │           11437320 │      2561959680 │
│     2 │     0 │        32 │  7006726704 │    6965106953 │           41619751 │      1331832032 │
│    91 │     1 │ 234881024 │           1 │             0 │                  1 │       234881024 │
│     6 │     0 │        96 │  5682488087 │    5680410878 │            2077209 │       199412064 │
│     7 │     0 │       112 │  1402413732 │    1401220491 │            1193241 │       133642992 │
[...]
```

Please let us know what else we can do to diagnose the issue. Thanks!

### LINKED ISSUE #58496: Tracking the memory leak problem
After I upgrade clickhouse from 21.8 to 22.8.21.38 lts,I encountered memory leak.The clickhouse process memory keep growing observably about 1GB per day,and release memory after restart server.
I had checked all metrics about clickhouse follow this: [who-ate-my-memory](https://kb.altinity.com/altinity-kb-setup-and-maintenance/altinity-kb-who-ate-my-memory/)
``` text
caches
primary keys in memory
merge memory
memory engines
``` 
All those matrics are have low memory useage.Then I found jemalloc memory was similar to clickhouse instance memory,those are three jemalloc metrics:
``` text
jemalloc.resident
jemalloc.active
jemalloc.allocated
```
So,I try to gather the clickhouse memory using jemalloc profiling tools in my test environment.
Turn on jemalloc profile and start clickhouse like this:
``` bash
export MALLOC_CONF=background_thread:true,prof:true,prof_leak:true,lg_prof_sample:17,lg_prof_interval:32,prof_final:true,prof_prefix:/data/jemalloc/jeprof
export CLICKHOUSE_WATCHDOG_ENABLE=0

nohup /usr/bin/clickhouse-server --config=/etc/clickhouse-server/config.xml &
```

Then show memory with jeprof tool, the two heap files have 24 hours interval:
``` bash
/usr/local/jemalloc-521/bin/jeprof /usr/bin/clickhouse --base=/data/jemalloc/jeprof.36298.2172.i2172.heap /data/jemalloc/jeprof.36298.15994.i15994.heap
```
the top command output:
``` text
(jeprof) top
Total: 272.1 MB
    99.4  36.5%  36.5%    105.3  38.7% std::__1::__tree::__emplace_unique_key_args
    98.0  36.0%  72.6%    198.2  72.8% Poco::Logger::unsafeGet
    19.4   7.1%  79.7%     56.2  20.6% DB::SerializationArray::enumerateStreams
    16.3   6.0%  85.7%    -19.5  -7.2% boost::multi_index::detail::ordered_index_impl::insert_
    13.0   4.8%  90.4%     16.0   5.9% boost::multi_index::detail::hashed_index::insert_
    11.3   4.1%  94.6%     19.2   7.0% std::__1::__hash_table::__emplace_unique_key_args
     7.0   2.6%  97.1%     35.1  12.9% std::__1::__hash_table::__rehash
     5.5   2.0%  99.2%      5.6   2.1% std::__1::vector::__emplace_back_slow_path
     4.9   1.8% 101.0%      6.9   2.5% DB::DataTypeArray::doGetDefaultSerialization
     3.0   1.1% 102.1%      3.0   1.1% boost::multi_index::detail::hashed_index::unchecked_rehash
```
According to the output, Is it possible to state that these two lines leak memory?
``` text
    99.4  36.5%  36.5%    105.3  38.7% std::__1::__tree::__emplace_unique_key_args
    98.0  36.0%  72.6%    198.2  72.8% Poco::Logger::unsafeGet
```
And how to do it?

### PR DESCRIPTION
**Pull request by kitaisreal**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Table CREATE DROP `Poco::Logger` memory leak fix. Closes #57931. Closes #58496.

### CODE REVIEW

**Comment by kitaisreal** [comment]
Check https://github.com/ClickHouse/ClickHouse/pull/58830#issuecomment-1892417587.
After 1000 tables created and dropped.

Total:
```
SELECT formatReadableSize(sum(size)) AS total_size, count() AS count FROM system.memory_dump_log
WHERE event_time = '2024-01-12 21:52:53'

┌─total_size─┬─count─┐
│ 53.75 MiB  │ 50350 │
└────────────┴───────┘
```

Total by memory leaked by `Poco::Logger::unsafeGet`:
```
SELECT
    formatReadableSize(sum(total_size)),
    sum(total_count) AS total_count
FROM
(
    SELECT
        substring(leak_function, 1, 50),
        sum(total_size) AS total_size,
        sum(count) AS total_count
    FROM
    (
        SELECT
            traces[index + 1] AS leak_function,
            total_size,
            count
        FROM
        (
            SELECT
                trace,
                arrayMap(x -> demangle(addressToSymbol(x)), trace) AS traces,
                indexOf(traces, 'Poco::Logger::get(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&)') AS index,
                arrayStringConcat(traces, '\n') AS trace_string,
                sum(size) AS total_size,
                count() AS count
            FROM system.memory_dump_log
            WHERE (event_time = '2024-01-15 18:16:49') AND (trace_string LIKE '%Poco::Logger::unsafeGet%')
            GROUP BY trace
            HAVING count > 1000
            ORDER BY count DESC
        )
    )
    GROUP BY leak_function
)

┌─formatReadableSize(sum(total_size))─┬─total_count─┐
│ 0.00 B                              │           0 │
└─────────────────────────────────────┴─────────────┘

1 row in set. Elapsed: 0.968 sec. Processed 57.34 thousand rows, 10.73 MB (59.24 thousand rows/s., 11.09 MB/s.)
Peak memory usage: 70.45 MiB.
```

**Comment by robot-ch-test-poll4** [comment]
*This is an automated comment for commit 546e7da7bc8befb912d49f3cf4c4d140bc6640f2 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/58831/546e7da7bc8befb912d49f3cf4c4d140bc6640f2/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/58831/546e7da7bc8befb912d49f3cf4c4d140bc6640f2/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Review by KochetovNicolai — APPROVED** [review]

**Comment by marcio-absmartly** [comment]
@kitaisreal thanks for this!
Hoping it will be backported to 23.8 :)

**Comment by KochetovNicolai** [comment]
There is no way this PR will be backported anywhere. Sorry.

**Comment by filimonov** [comment]
BTW, do you know what triggered that to start happening? (it was reported as the regression after the upgrade). 

Maybe that can be related? https://github.com/ClickHouse/ClickHouse/pull/39227

**Review by KochetovNicolai — APPROVED** [review]

**Comment by baibaichen** [comment]
@kitaisreal 

I'm a bit curious that this PR can solve memory leaks, IIUC, `Logger`'s lifecycle is determined by `_PLoggerMap`. I didn't see` Logger::destory` being called outside of `LoggerDelete`, since `makeLoggerPtr` will increase internal counter of the `Logger`.

```c++
inline LoggerPtr makeLoggerPtr(Logger & logger)
{
    logger.duplicate();
    return std::shared_ptr<Logger>(&logger, LoggerDeleter());
}
```

**Comment by kitaisreal** [comment]
> @kitaisreal
> 
> I'm a bit curious that this PR can solve memory leaks, IIUC, `Logger`'s lifecycle is determined by `_PLoggerMap`. I didn't see` Logger::destory` being called outside of `LoggerDelete`, since `makeLoggerPtr` will increase internal counter of the `Logger`.
> 
> ```c++
> inline LoggerPtr makeLoggerPtr(Logger & logger)
> {
>     logger.duplicate();
>     return std::shared_ptr<Logger>(&logger, LoggerDeleter());
> }
> ```

I already noticed the issue, and we are working on it.
The fix is trivial, if during get we created logger first time do not call duplicate.
But we noticed that in cases like this:
```
LOG_TRACE(getLogger("MergedBlockOutputStream"), "filled checksums {}", new_part->getNameWithState());
``` 
it can be unsafe to delete logger, because it also destroyes underlying channel and this can be unexpected.

**Comment by baolinhuang** [comment]
I am wondering what scenario would trigger this memory leak problem.

We encountered a similar issue and it appears to be caused by this issue. But drop/create has not been executed.

image

**Comment by kitaisreal** [comment]
> I am wondering what scenario would trigger this memory leak problem.
> 
> We encountered a similar issue and it appears to be caused by this issue. But drop/create has not been executed.
> 
> image

Leak was always triggered when in ClickHouse you created `Poco::Logger` because they never were freed. But most of the time `Poco::Logger` was created with static string and lifetime of Logger was equal to lifetime of ClickHouse process. But when you create `Poco::Logger` with non static string name (for example to specify specific table name or specify merge name), lifetime of such `Poco::Logger` is equal to lifetime of table or merge, and after table is dropped or merge is executed `Poco::Logger` is not needed anymore but it will never be destroyed. Example in `MergeFromLogEntryTask` after fix:
```
MergeFromLogEntryTask::MergeFromLogEntryTask(
    ReplicatedMergeTreeQueue::SelectedEntryPtr selected_entry_,
    StorageReplicatedMergeTree & storage_,
    IExecutableTask::TaskResultCallback & task_result_callback_)
    : ReplicatedMergeMutateTaskBase(
        getLogger(
            storage_.getStorageID().getShortName() + "::" + selected_entry_->log_entry->new_part_name + " (MergeFromLogEntryTask)"),
        storage_,
        selected_entry_,
        task_result_callback_)
    , rng(randomSeed())
{
}
```

**Pull request merged**
