### PR TITLE
Userspace page cache again

### PR DESCRIPTION
**Pull request by al13n321**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

https://github.com/ClickHouse/ClickHouse/pull/53770 , but maybe it'll compile this time.

### CODE REVIEW

**Comment by robot-clickhouse-ci-1** [comment]
*This is an automated comment for commit 227e3b58067ebaabc281673601408fedd135a5a2 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/60552/227e3b58067ebaabc281673601408fedd135a5a2/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

**Comment by al13n321** [comment]
The failed test is flaky: https://github.com/ClickHouse/ClickHouse/issues/60625

**Comment by Algunenano** [comment]
Breaks tests. The changes were added to the 24.2 history

**Comment by alexey-milovidov** [comment]
TSan has found an issue.

**Pull request merged**
