### PR TITLE
[benchmark] Add short option back for port

### LINKED ISSUE #59442: Short option for port missing in clickhouse-benchmark
**Version:** v23.12, but also in master.

clickhouse-benchmark used to support a short option for port (-p). That no longer works:

```
clickhouse-benchmark -p
std::exception. Code: 1001, type: boost::wrapexcept<boost::program_options::unknown_option>, e.what() = unrecognised option '-p', Stack trace (when copying this message, always include the lines below):
 
0. ./obj-x86_64-linux-gnu/../contrib/llvm-project/libcxx/include/exception:134: std::logic_error::logic_error(std::logic_error const&) @ 0x15d7edb0 in clickhouse/obj-x86_64-linux-gnu/programs/clickhouse
1. ./obj-x86_64-linux-gnu/../contrib/boost/boost/program_options/errors.hpp:94: boost::program_options::error_with_option_name::error_with_option_name(boost::program_options::error_with_option_name const&) @ 0xed0fb19 in clickhouse/obj-x86_64-linux-gnu/programs/clickhouse
2. ./obj-x86_64-linux-gnu/../contrib/boost/boost/exception/exception.hpp:234: boost::wrapexcept<boost::program_options::unknown_option>::wrapexcept(boost::program_options::unknown_option const&) @ 0x15037d94 in clickhouse/obj-x86_64-linux-gnu/programs/clickhouse
3. ./obj-x86_64-linux-gnu/../contrib/boost/boost/throw_exception.hpp:162: void boost::throw_exception<boost::program_options::unknown_option>(boost::program_options::unknown_option const&) @ 0x150361ff in clickhouse/obj-x86_64-linux-gnu/programs/clickhouse
4. ./obj-x86_64-linux-gnu/../contrib/boost/libs/program_options/src/cmdline.cpp:0: boost::program_options::detail::cmdline::finish_option(boost::program_options::basic_option<char>&, std::vector<String, std::allocator<String>>&, std::vector<boost::function1<std::vector<boost::program_options::basic_option<char>, std::allocator<boost::program_options::basic_option<char>>>, std::vector<String, std::allocator<String>>&>, std::allocator<boost::function1<std::vector<boost::program_options::basic_option<char>, std::allocator<boost::program_options::basic_option<char>>>, std::vector<String, std::allocator<String>>&>>> const&) @ 0x15035b27 in clickhouse/obj-x86_64-linux-gnu/programs/clickhouse
5. ./obj-x86_64-linux-gnu/../contrib/llvm-project/libcxx/include/vector:537: boost::program_options::detail::cmdline::run() @ 0x15031c07 in clickhouse/obj-x86_64-linux-gnu/programs/clickhouse
6. ./obj-x86_64-linux-gnu/../contrib/llvm-project/libcxx/include/vector:1318: boost::program_options::basic_command_line_parser<char>::run() @ 0xed3cc81 in clickhouse/obj-x86_64-linux-gnu/programs/clickhouse
7. ./obj-x86_64-linux-gnu/../contrib/boost/boost/function/function_template.hpp:870: boost::program_options::basic_parsed_options<char> boost::program_options::parse_command_line<char>(int, char const* const*, boost::program_options::options_description const&, int, boost::function1<std::pair<String, String>, String const&>) @ 0xed2866c in clickhouse/obj-x86_64-linux-gnu/programs/clickhouse
8. ./obj-x86_64-linux-gnu/../programs/benchmark/Benchmark.cpp:0: mainEntryClickHouseBenchmark(int, char**) @ 0xed24561 in 
```

Seems like we accidentally removed it in 5cc78febdedac6612e869547f95d12452be45a25

Docs still show it as an option: https://clickhouse.com/docs/en/operations/utilities/clickhouse-benchmark

I can't think of a reason why we would have removed it other that it being too ambiguous, so we should probably add it back.

### PR DESCRIPTION
**Pull request by seandhaynes**
Closes https://github.com/ClickHouse/ClickHouse/issues/59442

Looks like it may have accidentally been removed in 5cc78febdedac6612e869547f95d12452be45a25

I can't think of a reason why unless it was seen as too ambiguous, but the docs still say it's valid: https://clickhouse.com/docs/en/operations/utilities/clickhouse-benchmark

So going to add it back

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Adding back the short version for `port` option for benchmark that was removed in 5cc78febdedac6612e869547f95d12452be45a25

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### CODE REVIEW

**Review by yariks5s — COMMENTED** [review]
We have `-u` as the `user` setting, wouldn't it be confusing if we use `-p` for port and not for password?

**Comment by robot-clickhouse-ci-2** [comment]
*This is an automated comment for commit 935661eaff69073d17f3fb34ba0c3d903f1319e6 with description of existing statuses. It's updated for the latest CI running*

[❌ Click here](https://s3.amazonaws.com/clickhouse-test-reports/59441/935661eaff69073d17f3fb34ba0c3d903f1319e6/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td><a href="https://github.com/ClickHouse/ClickHouse/blob/master/.github/PULL_REQUEST_TEMPLATE.md?plain=1">❌ failure</a></td></tr>
<tbody>
</table>

**Comment by alexey-milovidov** [comment]
`clickhouse-client` does not have this option.
Either we add it to every tool or to none.

**Comment by seandhaynes** [comment]
Thanks @alexey-milovidov @yariks5s . Leaving it as it is sounds good on that basis. I'm happy to make a small PR to update the docs.

**Comment by alexey-milovidov** [comment]
Thank you! Let's update the docs. Looking forward to the PR with the docs update.

**Pull request closed without merging**
