### PR TITLE
Improve count if rewrite

### PR DESCRIPTION
**Pull request by taiyang-li**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
```
sumIf(123, cond) -> 123 * countIf(1, cond) 
sum(if(cond, 123, 0)) -> 123 * countIf(cond)
sum(if(cond, 0, 123)) -> 123 * countIf(not(cond))
```

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by zhanglistar** [comment]
How much improve?

**Comment by Algunenano** [comment]
There are cases where this changes the result:

```
:) Select sumIf(NaN, number > 10) from numbers(10);

SELECT sumIf(nan, number > 10)
FROM numbers(10)

Query id: 3610ba57-4d00-41d7-b2ca-da2c31937b02

┌─sumIf(nan, greater(number, 10))─┐
│                               0 │
└─────────────────────────────────┘

1 row in set. Elapsed: 0.004 sec. 

:) Select NaN * countIf(number > 10) from numbers(10);

SELECT nan * countIf(number > 10)
FROM numbers(10)

Query id: b9158e73-bb1c-49e3-8e56-f555637c6d63

┌─multiply(nan, countIf(greater(number, 10)))─┐
│                                         nan │
└─────────────────────────────────────────────┘

1 row in set. Elapsed: 0.009 sec. 
```

**Comment by taiyang-li** [comment]
> How much improve?

Query: `SELECT sum(if(number % 2 == 0, 123, 0)) FROM numbers(1000000000)`
Before: 1 rows in set. Elapsed: 1.233 sec. Processed 1.00 billion rows, 8.00 GB (810.95 million rows/s., 6.49 GB/s.)
After: 1 rows in set. Elapsed: 1.076 sec. Processed 1.00 billion rows, 8.00 GB (929.22 million rows/s., 7.43 GB/s.)

**Comment by taiyang-li** [comment]
> 

@Algunenano Please notice that 
`Select sumIf(NaN, number > 10) from numbers(10);` won't be rewritten to `Select NaN * countIf(number > 10) from numbers(10);` 
Because NaN's type is not UInt64 or Int64.

**Comment by Avogar** [comment]
@taiyang-li please look at the Fuzzer failures, they look related to the changes

**Comment by taiyang-li** [comment]
> @taiyang-li please look at the Fuzzer failures, they look related to the changes

@Avogar Thanks for reminding. They are fixed now.

**Comment by Avogar** [comment]
It will be great if you will add the same implementation in the new analyzer. See `src/Analyzer/Passes/SumIfToCountIfPass.cpp`

**Comment by taiyang-li** [comment]
> It will be great if you will also add the same implementation in the new analyzer. See `src/Analyzer/Passes/SumIfToCountIfPass.cpp`

Done.

**Comment by taiyang-li** [comment]
@Avogar Do you have time to reivew again? Thanks very much.

**Comment by Avogar** [comment]
Sorry for long response, I was on vacation. let me review it now

**Review by Avogar — APPROVED** [review]

**Pull request merged**
