### PR TITLE
Polish english doc

### PR DESCRIPTION
**Pull request by romainneutron**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Documentation (changelog entry is not required)

This is a pull-request that polishes the English documentation (avoid short syntax, fix some typos, reword some sentences).
Any feedback is appreciated.

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
Thank you!

BTW, what tools did you use to do it?

**Comment by alexey-milovidov** [comment]
PS. `don't` -> `do not` - this change does not feel any better or worse for me.

**Comment by romainneutron** [comment]
@alexey-milovidov Thanks for your fast feedback. I'm using grammarly. This is a first batch, there are some room available for more improvement.

**Comment by romainneutron** [comment]
@alexey-milovidov Some part of this PR have also been done just with my eyes :D

**Pull request merged**
