### PR TITLE
hints for column names

### PR DESCRIPTION
**Pull request by fastio**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Hints for column names. #17112

Detailed description / Documentation draft:

### CODE REVIEW

**Review by nikitamikhaylov — APPROVED** [review]

**Comment by nikitamikhaylov** [comment]
@fastio  The only remark - please do not reformat the code. Git blame will become inconsistent. And these changes are not relevant to the subject of this PR. If you want to reformat code somehow, please, open another PR.

**Comment by fastio** [comment]
> @fastio The only remark - please do not reformat the code here. Git blame will become inconsistent. And these changes are not relevant to the subject of this PR. If you want to reformat code somehow, please, open another PR.

Thanks, I got it.

**Comment by alexey-milovidov** [comment]
@fastio 

```
2020.12.15 16:44:02.408249 [ 10671 ] {} <Fatal> BaseDaemon: Address: NULL pointer. Access: read. Address not mapped to object.
2020.12.15 16:44:02.408407 [ 10671 ] {} <Fatal> BaseDaemon: Stack trace: 0x1a88e374 0x1a886245 0x1a8898ba 0x1aaeade5 0x1aaeb3f7 0x1aee1e5f 0x1aef09db 0x1aef095b 0x1aef08fb 0x1aeefa2d 0x1ab2971b 0x1ab26846 0x1ab20880 0x1a2e3c62 0x1a2e2b76 0x1a2e51a5 0x1a8e6609 0x1a8e507a 0x1b3987b9 0x1b3a3c58 0x1f3862ec 0x1f386af0 0x1f4c8e73 0x1f4c5dad 0x1f4c4c38 0x7f8f4bac1669 0x7f8f4b9e92b3
2020.12.15 16:44:02.456210 [ 10671 ] {} <Fatal> BaseDaemon: 4. /build/obj-x86_64-linux-gnu/../src/Common/NamePrompter.h:102: DB::IHints<1ul, DB::IStorage>::getHints(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const @ 0x1a88e374 in /usr/bin/clickhouse
```

**NamePrompter.h:102**

**Comment by fastio** [comment]
> @fastio
> 
> ```
> 2020.12.15 16:44:02.408249 [ 10671 ] {} <Fatal> BaseDaemon: Address: NULL pointer. Access: read. Address not mapped to object.
> 2020.12.15 16:44:02.408407 [ 10671 ] {} <Fatal> BaseDaemon: Stack trace: 0x1a88e374 0x1a886245 0x1a8898ba 0x1aaeade5 0x1aaeb3f7 0x1aee1e5f 0x1aef09db 0x1aef095b 0x1aef08fb 0x1aeefa2d 0x1ab2971b 0x1ab26846 0x1ab20880 0x1a2e3c62 0x1a2e2b76 0x1a2e51a5 0x1a8e6609 0x1a8e507a 0x1b3987b9 0x1b3a3c58 0x1f3862ec 0x1f386af0 0x1f4c8e73 0x1f4c5dad 0x1f4c4c38 0x7f8f4bac1669 0x7f8f4b9e92b3
> 2020.12.15 16:44:02.456210 [ 10671 ] {} <Fatal> BaseDaemon: 4. /build/obj-x86_64-linux-gnu/../src/Common/NamePrompter.h:102: DB::IHints<1ul, DB::IStorage>::getHints(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const @ 0x1a88e374 in /usr/bin/clickhouse
> ```
> 
> **NamePrompter.h:102**

@alexey-milovidov Thanks.

**Review by alexey-milovidov — APPROVED** [review]

**Pull request merged**
