### PR TITLE
Fix uninitialized memory in functions multiSearch* with empty array

### LINKED ISSUE #27169: Msan on multiSearchFirstPositionCaseInsensitive (from 00746_sql_fuzzy.sh)
Reproduced on current master:

```
SELECT multiSearchFirstPositionCaseInsensitive('\0', enabledRoles());
```

https://clickhouse-test-reports.s3.yandex.net/27078/cc0c3a90336f7527209e2be8d00089db8b9c2697/functional_stateless_tests_(memory).html

Logs mirrored to:
http://transfer.sh/1QoOQ3m/stderr.log
http://transfer.sh/LJPpZ/clickhouse-server.log (only Fatal and queryid `cf20e9a5-a9df-4f32-8c2c-d7d535dd64e0`)

### PR DESCRIPTION
**Pull request by vdimir**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
- Fix uninitialized memory in functions `multiSearch*` with empty array, close #27169

### CODE REVIEW

**Review by kitaisreal — APPROVED** [review]

**Comment by vdimir** [comment]
Seems that fill actually required only with empty input array. So, alternatively we can use `resize` without fill, but fill if no iterations are made.
@kitaisreal What do you think?

```diff
        auto searcher = Impl::createMultiSearcherInBigHaystack(needles);
        const size_t haystack_string_size = haystack_offsets.size();
-       res.resize_fill(haystack_string_size);
+       res.resize(haystack_string_size);
        size_t iteration = 0;
        while (searcher.hasMoreToSearch())
        {
            size_t prev_offset = 0;
            for (size_t j = 0; j < haystack_string_size; ++j)
            {
                const auto * haystack = &haystack_data[prev_offset];
                const auto * haystack_end = haystack + haystack_offsets[j] - prev_offset - 1;
                /// hasMoreToSearch traverse needles in increasing order
                if (iteration == 0 || res[j] == 0)
                    res[j] = searcher.searchOneFirstIndex(haystack, haystack_end);
                prev_offset = haystack_offsets[j];
            }
            ++iteration;
        }
+       if (iteration == 0)
+           std::fill(res.begin(), res.end(), 0);
```

**Comment by kitaisreal** [comment]
@vdimir resize_fill seems easier to understand and there is no performance penalty with current solution.

**Comment by kitaisreal** [comment]
@vdimir it seems that 00233_position_function_family test performance affected ?

**Comment by vdimir** [comment]
> @vdimir it seems that 00233_position_function_family test performance affected ?

Let's try version with `resize` and `fill` only for empty array

**Comment by alexey-milovidov** [comment]
> resize_fill seems easier to understand and there is no performance penalty with current solution.

@kitaisreal I'm against doing excessive fill just in case.

**Comment by vdimir** [comment]
Maybe we didn't have `Functional stateless tests flaky check (address)` when `00233_position_function_family` was added? Seems that slowdown in this check is not connected with changes.

**Comment by alexey-milovidov** [comment]
Yes, the flaky check was added only recently. And also it has artificial slowdown.

**Review by alexey-milovidov — APPROVED** [review]

**Pull request merged**
