### PR TITLE
Fixed session_log related tests race condition on logout

### PR DESCRIPTION
**Pull request by Demilivor**
Relate  to #67767

This PR contains similar changes as PR https://github.com/ClickHouse/ClickHouse/pull/67779

In other tests

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by Demilivor** [comment]
@alexey-milovidov Please review these similar changes to your PR: https://github.com/ClickHouse/ClickHouse/pull/67779

**Review by alexey-milovidov — APPROVED** [review]

**Comment by robot-clickhouse** [comment]
*This is an automated comment for commit 6897178c41286fd3d4f3064ad8e2c716d12e002f with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/67785/6897178c41286fd3d4f3064ad8e2c716d12e002f/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Unit tests</td><td>Runs the unit tests for different release types</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/1e194596106c727ab3731cc74eab6759969f275d/unit_tests__release_.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Comment by Demilivor** [comment]
Flaky check failed:
https://s3.amazonaws.com/clickhouse-test-reports/67785/6897178c41286fd3d4f3064ad8e2c716d12e002f/integration_tests_flaky_check__asan_.html

Could you help me please understand why? 
It looks like the flaky check runs the same tests in parallel using a **single python fixture**. The test is not ready for that.

I see `# Tags: no-parallel` in some of tests, maybe I should add it to the test?

**Comment by Demilivor** [comment]
Update: 
I added `test_session_log` to the `tests/integration/parallel_skip.json` list. I hope that will help.

**Comment by Demilivor** [comment]
The test failed again, and the output looks the same as before. It seems that the same fixture is used to run several tests in parallel.

How can I run a flaky check manually?

**Comment by Demilivor** [comment]
I reproduced the flaky check result by this command:
`sudo ./tests/integration/runner "test_session_log" --count 5 --parallel 1  --binary build/programs/clickhouse` - All test runs use a single module-level fixture.

I don't know how to disallow running the test within single fixture. So tomorrow I will rework the test a bit to make it work with parallel run of test cases and pass with `--count 5`

**Comment by Demilivor** [comment]
Update:
1) Fixed session log parallel/sequenced test work. Now each test case creates it's own user. That allows to run tests in sequence using a single fixture.
2) Reduced code duplication

**Pull request merged**
