### PR TITLE
add Docker builder image

### PR DESCRIPTION
**Pull request by miolini**
Hey!

I hope this Docker image will help other contributors to make developing great again.

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
Great, thanks!

**Comment by IvanJobs** [comment]
@miolini  is there any guide for how to use this docker build image?

**Comment by Slach** [comment]
@IvanJobs 
this image need for build clickhouse-server from sources inside docker, under ubuntu 14.04 (why? ;)
for use them 
just make following commands
```
git clone  https://github.com/yandex/ClickHouse.git ./clickhouse-server
cd ./clickhouse-server/docker/builder
make build
```

**Comment by imissyouso** [comment]
Error response from daemon: pull access denied for yandex/clickhouse-builder, repository does not exist or may require 'docker login'.

**Pull request merged**
