### PR TITLE
Fix branch for anchore/scan-action (master -> main)

### PR DESCRIPTION
**Pull request by stigsb**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Build/Testing/Packaging Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Update `anchore/scan-action@main` workflow action (was moved from master)

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]
Ok. I wondered why it's not working but actually did not care much.

**Review by alexey-milovidov — CHANGES_REQUESTED** [review]
It did not started to work after the changes.

**Comment by alexey-milovidov** [comment]
```
Warning: Unexpected input(s) 'image-reference', 'dockerfile-path', valid inputs are ['image', 'path', 'debug', 'fail-build', 'grype-version', 'acs-report-enable', 'severity-cutoff']
Run anchore/scan-action@main
  with:
    image-reference: localbuild/testimage:latest
    dockerfile-path: docker/server/Dockerfile
    acs-report-enable: true
    fail-build: true
    debug: false
    severity-cutoff: medium
Error: At least one source for scanning needs to be provided. Available options are: image, and path
```

**Comment by alexey-milovidov** [comment]
```
Run actions/upload-artifact@v1.0.0
Error: Path does not exist /home/runner/work/ClickHouse/ClickHouse/anchore-reports/
Error: Exit code 1 returned from process: file name '/home/runner/runners/2.274.2/bin/Runner.PluginHost', arguments 'action "GitHub.Runner.Plugins.Artifact.PublishArtifact, Runner.Plugins"'.
```

**Comment by alexey-milovidov** [comment]
@stigsb we can either continue and fix it or just remove the action (both variants Ok).

**Comment by stigsb** [comment]
@alexey-milovidov works now - I removed the `fail-build: true`, but can put it back if you want the build to fail if issues are found (could create a lot of noise).

**Comment by alexey-milovidov** [comment]
Thank you!
Here is the result:

Screenshot_20201221_225330

These are vulnerabilities from Ubuntu image.
ClickHouse itself does not have any dependencies.

**Comment by alexey-milovidov** [comment]
We prepared Alpine image if you are concerned:
https://github.com/ClickHouse/ClickHouse/blob/master/docker/server/Dockerfile.alpine

Also we prepared an example to show that ClickHouse can work on bare Linux kernel (without any images):
https://github.com/ClickHouse/ClickHouse/tree/master/docker/bare

**Pull request merged**
