### PR TITLE
fix replaceRegexpAll bug

### PR DESCRIPTION
**Pull request by Joeywzr**
Changelog category (leave one):

- Bug Fix (user-visible misbehaviour in official stable or prestable release)

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
fix replaceRegexpAll bug

Detailed description / Documentation draft:
#30245

> By adding documentation, you'll allow users to try your new feature immediately, not when someone else will have time to document it later. Documentation is necessary for all features that affect user experience in any way. You can add brief documentation draft above, or add documentation right into your patch as Markdown files in [docs](https://github.com/ClickHouse/ClickHouse/tree/master/docs) folder.

> If you are doing this for the first time, it's recommended to read the lightweight [Contributing to ClickHouse Documentation](https://github.com/ClickHouse/ClickHouse/tree/master/docs/README.md) guide first.

> Information about CI checks: https://clickhouse.tech/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by den-crane** [comment]
I would add test for replaceRegexpAll as well. One day `trim` can be reworked with using Regex. Then your test will stop to check replaceRegexpAll.

**Comment by Joeywzr** [comment]
> I would add test for replaceRegexpAll as well. One day `trim` can be reworked with using Regex. Then your test will stop to check replaceRegexpAll.

OK.

**Review by vdimir — APPROVED** [review]
Great catch!

**Comment by alexey-milovidov** [comment]
@vdimir 

> fix replaceRegexpAll bug

This is not a good changelog entry.

**Pull request merged**
