### PR TITLE
Randomize settings related to in-order read/aggregation

### PR DESCRIPTION
**Pull request by azat**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Real issues that had been found with this randomization

- [x] [`01710_aggregate_projections`](https://s3.amazonaws.com/clickhouse-test-reports/36914/0cf9d32a0f4b4d989dbcc27e4f615a73ebb8be45/stateless_tests__memory__actions__[3/3].html) - #37342
- [x] [`01630_simple_aggregate_function_in_summing_merge_tree`](https://s3.amazonaws.com/clickhouse-test-reports/36914/0cf9d32a0f4b4d989dbcc27e4f615a73ebb8be45/stateless_tests__aarch64__actions_.html)
  - #37050 
  - #37046 
- [x] `GROUPING SETS` - #37542

### CODE REVIEW

**Comment by azat** [comment]
Tests found two real issues:
- 01710_aggregate_projections
- 01630_simple_aggregate_function_in_summing_merge_tree
On it

**Comment by azat** [comment]
Now `GROUPING SETS` is broken

**Comment by azat** [comment]
No green. Can someone take a look please?

**Comment by azat** [comment]
Rebased to fix conflicts.

**Comment by azat** [comment]
@alexey-milovidov maybe you can take a look?

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
@mergifyio update

**Comment by alexey-milovidov** [comment]
> Stateless tests (thread, actions) [1/3] — Some tests restarted, fail: 1, passed: 1397, skipped: 11

Bug in TSan: https://github.com/google/sanitizers/issues/1540

**Comment by alexey-milovidov** [comment]
> /usr/share/clickhouse-test/queries/0_stateless/01174_select_insert_isolation.sh: line 1: wait_for: No record of process 139332

Bug in bash, CC @azat

**Comment by azat** [comment]
>/usr/share/clickhouse-test/queries/0_stateless/01174_select_insert_isolation.sh: line 1: wait_for: No record of process 139332
>Bug in bash

- part of the test that produces this error had #37822
- details about this bug (that had been fixed in bash 5.1+) - https://gist.github.com/azat/affbda3f8c6b5c38648d4ab105777d88?permalink_comment_id=4201858#gistcomment-4201858

**Pull request merged**
