### PR TITLE
Log async insert flush queries into to system.query_log and system.processes

### LINKED ISSUE #50720: Async insert flush query not present in query_log and query_views_log
When using async_query you can see all buffered queries in the query_log:

```sql
SELECT
    count(),
    groupArrayDistinct(flush_query_id),
    groupArrayDistinct(query_id)
FROM system.asynchronous_insert_log
WHERE (flush_query_id = '3170cdc1-224f-4c2c-9113-c29150f18963') AND (event_date = today())

Query id: 2a9a07fb-f290-40b5-b8fc-20ba871950d9

Row 1:
──────
count():                            17
groupArrayDistinct(flush_query_id): ['3170cdc1-224f-4c2c-9113-c29150f18963']
groupArrayDistinct(query_id):       ['4c52dfa9-ab49-4883-a7db-219ddf6c35e6','f3352493-4919-4ea4-ba5d-27a3f1e68d29','c605b00c-9e39-47e1-aa6a-e13288bad75a','46d6838f-8cde-4088-b807-a68758a5c182','c1d05836-46b3-4b0c-91fc-a9ab021e83d7','b3c2d301-81c6-40f6-9004-263d84c8c11f','e1743521-a151-4c49-a207-17c7cfbd954a','05f00de6-dcf7-4d9d-82ae-a6fa4909adeb','16f63626-99fc-48fa-8519-97a8363f50be','8a9f3154-8737-426d-884f-795072925cd3','bfd96388-8db2-4535-bfa8-558314c35ec1','21a40655-1c09-47f3-b971-cc0f204f1089','c6284fe5-9d4f-4c16-9587-df9aa058e6ed','23abd108-fc5a-426d-8305-18968dbba5a8','989605d4-2bfd-4003-b11b-d958430bf6ac','343a368e-dfb7-44bb-94a3-5d3ffec73f49','93632b01-3dfa-4b2d-9c12-ec3f5c76c36b']
```

```sql
SELECT
    count(),
    sum(written_rows),
    sum(written_bytes)
FROM system.query_log
WHERE (query_id IN ['4c52dfa9-ab49-4883-a7db-219ddf6c35e6', 'f3352493-4919-4ea4-ba5d-27a3f1e68d29', 'c605b00c-9e39-47e1-aa6a-e13288bad75a', '46d6838f-8cde-4088-b807-a68758a5c182', 'c1d05836-46b3-4b0c-91fc-a9ab021e83d7', 'b3c2d301-81c6-40f6-9004-263d84c8c11f', 'e1743521-a151-4c49-a207-17c7cfbd954a', '05f00de6-dcf7-4d9d-82ae-a6fa4909adeb', '16f63626-99fc-48fa-8519-97a8363f50be', '8a9f3154-8737-426d-884f-795072925cd3', 'bfd96388-8db2-4535-bfa8-558314c35ec1', '21a40655-1c09-47f3-b971-cc0f204f1089', 'c6284fe5-9d4f-4c16-9587-df9aa058e6ed', '23abd108-fc5a-426d-8305-18968dbba5a8', '989605d4-2bfd-4003-b11b-d958430bf6ac', '343a368e-dfb7-44bb-94a3-5d3ffec73f49', '93632b01-3dfa-4b2d-9c12-ec3f5c76c36b']) AND (type > 1) AND (event_date = today())

Query id: 8348dfba-006c-4921-b1f1-2892f989c4e4

┌─count()─┬─sum(written_rows)─┬─sum(written_bytes)─┐
│      17 │                 0 │                  0 │
└─────────┴───────────────────┴────────────────────┘
```

Those insert queries are not reporting written rows, or written bytes because are not being executed as they arrive but are buffered, and flushed asynchronously. 

You can get written bytes from `asynchronous_insert_log` or from `AsyncInsertBytes` in `ProfileEvents`, that's not a big deal. The issue is that we lose all the matviews observability.

Trying to get some extra information from the `flush_query_id` we see that there are no records:

```sql
SELECT *
FROM system.query_log
WHERE (query_id = '3170cdc1-224f-4c2c-9113-c29150f18963') AND (type > 1) AND (event_date = today())

Query id: f50f0117-90ea-41d2-bfe0-c14084f3411f

Ok.

0 rows in set. Elapsed: 0.788 sec. Processed 3.11 million rows, 8.06 GB (3.95 million rows/s., 10.23 GB/s.)
```

What's the reason for not having `flush_query_id` into `query_log`, and `query_views_log`? Is this something can be included?

### PR DESCRIPTION
**Pull request by Algunenano**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
- Log async insert flush queries into to system.query_log

### Documentation entry for user-facing changes

Flush queries for async inserts (the queries that do the final push of data) are now logged in the system.query_log where they appear as `query_kind = 'AsyncInsertFlush'`.

These flush queries also now appear in system.processes and can be killed as any normal insert, but they don't count towards the limits for max concurrent queries.

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

Closes https://github.com/ClickHouse/ClickHouse/issues/50720

### CODE REVIEW

**Comment by robot-clickhouse-ci-1** [comment]
This is an automated comment for commit 13910919c23124ccdf8969b0d8d435584bd65a02 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/51160/13910919c23124ccdf8969b0d8d435584bd65a02/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Comment by Algunenano** [comment]
* `Integration tests (asan) [1/6] ` -> https://github.com/ClickHouse/ClickHouse/issues/50543
* `ClickHouse Stress Test (ubsan)` -> https://github.com/ClickHouse/ClickHouse/issues/50468

I'll keep an eye on the rest of the tests as they advance, but I think this is ok to review now.

**Comment by Algunenano** [comment]
Failed tests are all unrelated:

* Integration tests (asan) [4/6] — fail: 1, passed: 266, flaky: 0
  test_multiple_disks/test.py::test_start_stop_moves[replicated] -> https://github.com/ClickHouse/ClickHouse/issues/45404	
* Integration tests (release) [3/4] — fail: 1, passed: 558, flaky: 0
  test_alter_moving_garbage/test.py::test_create_table[False-True] -> https://github.com/ClickHouse/ClickHouse/issues/51342
* Integration tests (release) [4/4] — fail: 1, passed: 425, flaky: 0
  test_ssl_cert_authentication/test.py::test_https_non_ssl_auth	-> https://github.com/ClickHouse/ClickHouse/issues/49400
* Integration tests (tsan) [4/6] — fail: 1, passed: 266, flaky: 0
  test_multiple_disks/test.py::test_start_stop_moves[replicated] -> https://github.com/ClickHouse/ClickHouse/issues/45404
* Mergeable Check -> No idea. Can't see
* Stateless tests (tsan, s3 storage) [4/5] — fail: 2, passed: 1013, skipped: 21
  02481_parquet_list_monotonically_increasing_offsets timeout
  01605_adaptive_granularity_block_borders timeout -> https://github.com/ClickHouse/ClickHouse/issues/50681

**Comment by Algunenano** [comment]
PR is clean and ready for review. Updating with master for the sake of keeping it close to HEAD

**Comment by Algunenano** [comment]
Failure in unrelated test -> https://github.com/ClickHouse/ClickHouse/issues/52059

**Comment by alexey-milovidov** [comment]
> Flush queries for async inserts (the queries that do the final push of data) are not logged

"are not logged" -> are now logged.

**Comment by alexey-milovidov** [comment]
I've asked @CurtizJ to review.

**Review by nikitamikhaylov — APPROVED** [review]

**Comment by lesandie** [comment]
This is a nice add @Algunenano thanks for this!. Am I right into assuming this cannot be backported to LTS 22.8?

because:
- There is no way to relate `part_log` with `asynchronous_insert_log query_id/flush_query_id` you need to go to `query_log`
- Table `async_insert_log` shows up the `query_id` and `flush_query_id`  of each async insert.
- `query_id` from `asynchronous_insert_log` shows up in the `system.query_log` as type = 'QueryStart'  but the same 
- `query_id` does not show up in the `query_id` column of the `system.part_log`.
- The `query_id` column in the `part_log` is the identifier of the INSERT query that created a data part, and it seems it is for sync INSERTS but not for asyncs.

**Comment by Algunenano** [comment]
>  Am I right into assuming this cannot be backported to LTS 23.3?

Impossible is nothing, but yes, features aren't backported.

> The query_id column in the part_log is the identifier of the INSERT query that created a data part, and it seems it is for sync INSERTS but not for asyncs.

This one is a bug but it should be easily fixable. I'll send the fix.

**Pull request merged**
