### PR TITLE
Fail performance comparison on errors in the report

### LINKED ISSUE #34763: Performance tests should always turn red if there are "Run errors"
[Run Errors](https://s3.amazonaws.com/clickhouse-test-reports/33057/5a8cf3ac98808dadf125068a33ed9c622998a484/performance_comparison__actions__[4/4]/report.html#run-errors)

### PR DESCRIPTION
**Pull request by Felixoid**
Changelog category (leave one):
- Build/Testing/Packaging Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fail performance comparison on errors in the report

Fixes #34763

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
@mergifyio update

**Comment by alexey-milovidov** [comment]
@kitaisreal It is still not fixed, see https://s3.amazonaws.com/clickhouse-test-reports/0/e30b0c5d57826b8951d936e5601b8a8291c9cae1/performance_comparison__actions__[3/4]/report.html

**Comment by alexey-milovidov** [comment]
@Mergifyio update

**Comment by alexey-milovidov** [comment]
> Performance Comparison (actions) [1/4] — 4 errors, 1 too long, 1 faster, 2 slower, 5 unstable
Performance Comparison (actions) [3/4] — 2 errors, 1 too long, 1 slower, 1 unstable

@kitaisreal It is still not ready. Need to fix perf test.

**Comment by kitaisreal** [comment]
@alexey-milovidov almost finished, will fix.

**Comment by alexey-milovidov** [comment]
Let's check if the errors are fixed. @mergifyio update

**Comment by alexey-milovidov** [comment]
@kitaisreal looks like it is not finished.
@Mergifyio update

**Comment by alexey-milovidov** [comment]
@Mergifyio update

**Comment by alexey-milovidov** [comment]
Still not ready:

Performance Comparison (actions) [1/4] — 17 errors, 1 too long, 5 faster, 2 slower, 11 unstable
Performance Comparison (actions) [2/4] — 4 errors, 4 too long, 2 faster, 1 slower, 4 unstable
Performance Comparison (actions) [3/4] — 3 errors, 3 faster, 2 slower
Performance Comparison (actions) [4/4] — 4 errors, 2 faster, 1 slower, 1 unstable

**Comment by alexey-milovidov** [comment]
@kitaisreal looks like it is not finished.

**Comment by alexey-milovidov** [comment]
@kitaisreal It is not fixed.

**Comment by alexey-milovidov** [comment]
@kitaisreal waiting for your fixes.

**Comment by azat** [comment]
What with cases like [this one](https://s3.amazonaws.com/clickhouse-test-reports/35111/269603381c74e308e8506c735cec6cf86806c42b/performance_comparison__actions__[1/4]/compare.log), looks like it had been killed? Or maybe the report hadn't been updated after retry?

**Comment by azat** [comment]
BTW maybe such a lot of unstability are due to now performance tests do not uses ramfs/tmpfs now? (4eb2dee857cee45 / #31467, cc @alesapin )
Also which disks VMs for perf tests have?

**Comment by alexey-milovidov** [comment]
@mergifyio update

**Comment by alexey-milovidov** [comment]
@azat First step is to avoid errors like incorrect tests.

**Comment by alexey-milovidov** [comment]
@mergifyio update after #36769

**Comment by alexey-milovidov** [comment]
Almost ready.

**Comment by alexey-milovidov** [comment]
@mergifyio update

**Comment by alexey-milovidov** [comment]
@mergifyio update

**Comment by alexey-milovidov** [comment]
@Felixoid I have fixed all the errors, but it failes also on "slowed down" and "unstable" queries which is not indended in this pull request.

**Comment by Felixoid** [comment]
the messages show:

```
7 errors, 2 faster, 6 slower, 7 unstable 
6 errors, 2 faster, 1 slower, 6 unstable 
```

It complains about them

**Comment by Felixoid** [comment]
To get an idea, what is treated as errors, search for error_tests in the file https://github.com/ClickHouse/ClickHouse/blob/master/docker/test/performance-comparison/report.py

I guess, what we want is to get rid of these lines, right? https://github.com/ClickHouse/ClickHouse/blob/master/docker/test/performance-comparison/report.py#L652-L660

Ignore unstable and slowed-down tests in the message as well

**Comment by Felixoid** [comment]
@alexey-milovidov it looks like we're good to go!

**Pull request merged**
