### PR TITLE
Set jemalloc `tcache_max=128KB`

### PR DESCRIPTION
**Pull request by nickitat**
### Changelog category (leave one):
- Performance Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Default size of per-thread allocator cache (32KB) is raised to 128KB.

---

Improves performance of `detectLanguage*` 🎉  

0.216 | 0.156 | -1.383x | -0.278 | 0.277 | classification | 1 | SELECT detectLanguageMixed(SearchPhrase) FROM hits_100m_single LIMIT 10000000 FORMAT Null
-- | -- | -- | -- | -- | -- | -- | --
0.214 | 0.161 | -1.33x | -0.249 | 0.248 | classification | 0 | SELECT detectLanguage(SearchPhrase) FROM hits_100m_single LIMIT 10000000 FORMAT Null

### CODE REVIEW

**Comment by robot-clickhouse** [comment]
This is an automated comment for commit 21a35990e55d65e9d0a633bd2041336e12f7f35f with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/52501/21a35990e55d65e9d0a633bd2041336e12f7f35f/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Comment by nickitat** [comment]
nothing seems to change

**Comment by nickitat** [comment]
slowdowns happen in jemalloc's `large_ralloc`

**Comment by alexey-milovidov** [comment]
One performance test showed a significant slowdown: https://s3.amazonaws.com/clickhouse-test-reports/52501/4a5c93b7f1f5d52432d264a1d63356d8731507e5/performance_comparison_aarch64_[1_4]/report.html

**Comment by nickitat** [comment]
ok

**Pull request closed without merging**
