### PR TITLE
Fix highlighting numbers does not work for Nullable

### LINKED ISSUE #61993: Highlighting numbers does not work for Nullable

### PR DESCRIPTION
**Pull request by skyoct**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
closes #61993

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

---
### Modify your CI run:
**NOTE:** If your merge the PR with modified CI you **MUST KNOW** what you are doing
**NOTE:** Checked options will be applied if set before CI RunConfig/PrepareRunConfig step

#### Include tests (required builds will be added automatically):
- [ ]  Fast test
- [ ]  Integration Tests
- [ ]  Stateless tests
- [ ]  Stateful tests
- [ ]  Unit tests
- [ ]  Performance tests
- [ ]  All with ASAN
- [ ]  All with TSAN
- [ ]  All with Analyzer
- [ ]  Add your option here

#### Exclude tests:
- [ ]  Fast test
- [ ]  Integration Tests
- [ ]  Stateless tests
- [ ]  Stateful tests
- [ ]  Performance tests
- [ ]  All with ASAN
- [ ]  All with TSAN
- [ ]  All with MSAN
- [ ]  All with UBSAN
- [ ]  All with Coverage
- [ ]  All with Aarch64
- [ ]  Add your option here

#### Extra options:
- [ ]  do not test (only style check)
- [ ]  disable merge-commit (no merge from master before tests)
- [ ]  disable CI cache (job reuse)

#### Only specified batches in multi-batch jobs:
- [ ]  1
- [ ]  2
- [ ]  3
- [ ]  4

### CODE REVIEW

**Comment by robot-ch-test-poll4** [comment]
*This is an automated comment for commit 51ca8a0c5ab64064539073d3e6e1e4ea594ef944 with description of existing statuses. It's updated for the latest CI running*

[❌ Click here](https://s3.amazonaws.com/clickhouse-test-reports/62378/51ca8a0c5ab64064539073d3e6e1e4ea594ef944/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td><a href="https://github.com/ClickHouse/ClickHouse/blob/master/.github/PULL_REQUEST_TEMPLATE.md?plain=1">❌ failure</a></td></tr>
<tbody>
</table>

**Comment by skyoct** [comment]
> @alexey-milovidov Hi, Can you help me answer the following questions?
> 
> 1. What is the meaning of the `Sparse`? I couldn't find specific documentation.
> 2. How should multiple layers of nesting be handled, for example: `toLowCardinality(toNullable(toNullable(toUInt64(-1))))`? Is there an existing method to retrieve the content of the innermost layer?

@alexey-milovidov Hi, Can you help me with this question?

**Comment by rschu1ze** [comment]
@skyoct Thanks for working on this.

> What is the meaning of the Sparse? I couldn't find specific documentation.

Please see https://clickhouse.com/blog/clickhouse-release-23-07

> How should multiple layers of nesting be handled, for example: `toLowCardinality(toNullable(toNullable(toUInt64(-1))))`? Is there an existing method to retrieve the content of the innermost layer?

There is a bunch of methods like `convertToFullColumnIfConst` and `recursiveRemoveSparse` for that, please see at the end of src/Processors/Chunk.h. I don't think that `Nullable` can be converted to non-`Nullable`, you would need to check for each value of `ColumnNullable` if it is nullable (see the corresponding header).

More thoughts:
- it is unfortunately bad habit in the ClickHouse repository that people write commit messages like "fix" and "better". Let's stop this and write [reasonable commit messages](https://cbea.ms/git-commit/) instead.
- in the PR message, please don't only state that something was fixed but also *how it was fixed* (e.g. why it was broken, how it was fixed, what possible side effects of the fix exist, etc.). Otherwise me (as a reviewer) need to read tons of code, understand what could possibly gone wrong, then read the PR and check how it fixes what could possibly could have gone wrong. A clear PR message makes reviews a lot easier.
- Setting `output_format_pretty_highlight_digit_groups` in [the original PR](https://github.com/ClickHouse/ClickHouse/pull/61802/files) was unfortunately not documented in the [docs](https://clickhouse.com/docs/en/operations/settings/settings). It would be great if you could do that as well.
- src/Core/Settings.h contains two blocks of settings starting with `output_format_pretty_*`. It's cosmetic but it would be great if you could change this to one single block as well.
- A test with different affected output formats (all `Pretty*` formats as far as I see) and different data types would be needed.

**Comment by rschu1ze** [comment]
No activity :-/

**Comment by skyoct** [comment]
@rschu1ze I am very sorry, but I had to interrupt this PR due to some issues in the past. I will continue to complete it.

**Comment by rschu1ze** [comment]
Sounds good, feel free to make a new PR and ping me, so I can check. Thanks!

**Pull request closed without merging**
