### PR TITLE
Analyzer: fix row policy

### PR DESCRIPTION
**Pull request by novikd**
### Changelog category (leave one):

- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by robot-ch-test-poll4** [comment]
This is an automated comment for commit 5baadf796e7554ce3fd524fedcaccb409a456900 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/53170/5baadf796e7554ce3fd524fedcaccb409a456900/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Comment by novikd** [comment]
The last integration test with row_policy fails with a non-ready set. I hope #53162 will fix it.

**Review by alexey-milovidov — APPROVED** [review]
Wow!

**Comment by KochetovNicolai** [comment]
https://github.com/ClickHouse/ClickHouse/pull/53162 will not fix it :(

**Comment by novikd** [comment]
@KochetovNicolai `test_row_policy_filter_with_subquery` fails with `Logical error: 'Not-ready Set is passed as the second argument for function 'in''.`

**Comment by KochetovNicolai** [comment]
Not waiting for tests cause no code was changed in the last commit.

**Pull request merged**
