### PR TITLE
No OpenTelemetry log in 00974_query_profiler

### LINKED ISSUE #38402: 00974_query_profiler is flaky: queue is full for system log OpenTelemetrySpanLog
https://s3.amazonaws.com/clickhouse-test-reports/38265/59a14d2a509a45de46066bfc8e0a9ad3327d35a7/stateless_tests__release__s3_storage__actions_.html

```2022-06-24 13:48:56 00974_query_profiler:                                                   [ FAIL ] 7.79 sec. - having stderror: 
2022-06-24 13:48:56 [f81d5fb03293] 2022.06.24 13:48:53.155086 [ 41872 ] {7a8d82e9-236d-402f-aeca-4bf0fc6ce083} <Error> SystemLog (system.opentelemetry_span_log): Queue is full for system log 'DB::OpenTelemetrySpanLog' at 1539015
2022-06-24 13:48:56 
2022-06-24 13:48:56 stdout:
2022-06-24 13:48:56 0	0
2022-06-24 13:48:56 1
2022-06-24 13:48:56 10000000000	0
2022-06-24 13:48:56 1
2022-06-24 13:48:56 
```

See also https://github.com/ClickHouse/ClickHouse/pull/37837#discussion_r897812019

### PR DESCRIPTION
**Pull request by qoega**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
...

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

Closes #38402

### CODE REVIEW

**Review by tavplubix — CHANGES_REQUESTED** [review]
The problem is not that `00974_query_profiler` writes into `opentelemetry_span_log`, the real problem is that a query may write too many rows in `opentelemetry_span_log`, so queue overflows and loses some spans.

**Comment by FrankChen021** [comment]
To be honest, adding span logs to processors is not a good idea. It would introduce lots of span logs for some complex queries, and most of span logs are not meaningful due to very short time duration. I once added such span logs for pipelines in an earlier version, but found that there were too many logs which were overwhelming, so we gave such attempt.

Even if we want to keep span logs for processors, I would like to suggest that adding an extra setting to control whether the span logs for processors should be enabled. By default it should be false.

**Comment by qoega** [comment]
>The problem is not that 00974_query_profiler writes into opentelemetry_span_log, the real problem is that a query may write too many rows in opentelemetry_span_log, so queue overflows and loses some spans.

I don't consider it a problem. Telemetry is not a critical system. You don't stop execution if FS is slow and you can't flush all logs to it.

**Comment by serxa** [comment]
Agree that we have to switch all heavy tracing by default. But actually if it is turned ON it would be not good to lose tracing data. This way tool gets unusable. It's better to slow down something or at least remember fact of losing tracing data (not sure if it is possible at all). If we are going to slow down query executing due to tracing, ideally we have to measure how long execution was blocked due to it (maybe new ProfileEvent?). Again, tool will be unusable if we cannot tell the difference: either we have problem with the tool itself or with the query being traced.

**Comment by FrankChen021** [comment]
For distributed tracing, it's first goal is to show how a query is executed in a cluster, how many sub-queries it forks, on which node these queries are execute, and how long each sub-query takes.

In reality, many complex queries forks sub-queries, from the distributed tracing's side, I think it's OK to show us the bottleneck at the query level. If we do want to dig out which processor slows one query, we can execute this query again by turning on some switch to ask for more detail logs.

Also, I'm working on a patch on our own branch to skip saving those span logs who have no children spans and whose duration is lower than a setting. By this way, we can save lots of space and ignore unuseful span logs.

**Comment by qoega** [comment]
Here is a setting to not collect spans for Processors.
https://github.com/ClickHouse/ClickHouse/pull/39170

**Comment by qoega** [comment]
>It's better to slow down something or at least remember fact of losing tracing data (not sure if it is possible at all).

You can see that this test is flaky test exactly because we show error that we were not able to store all traces. So it is not a case.

>2022-06-24 13:48:56 [f81d5fb03293] 2022.06.24 13:48:53.155086 [ 41872 ] {7a8d82e9-236d-402f-aeca-4bf0fc6ce083} <Error> SystemLog (system.opentelemetry_span_log): Queue is full for system log 'DB::OpenTelemetrySpanLog' at 1539015

We can see that only really slow test triggered this overflow. There is no reason to trace queries in this case. You can see that test is disabled in all slow scenarios:
`-- Tags: no-tsan, no-asan, no-ubsan, no-msan, no-debug, no-fasttest, no-cpu-aarch64`

**Comment by tavplubix** [comment]
> You can see that this test is flaky test exactly because we show error that we were not able to store all traces. So it is not a case.

Not precisely, it just prints error to server log on `SYSTEM FLUSH LOGS` query and this error is sent to client because we use `send_logs_level='warning'` in tests (default value is `'fatal'`). You will never know about this error if you do not run `SYSTEM FLUSH LOGS` and do not read all errors from text log (nobody does).

>  We can see that only really slow test triggered this overflow. There is no reason to trace queries in this case. You can see that test is disabled in all slow scenarios:
> -- Tags: no-tsan, no-asan, no-ubsan, no-msan, no-debug, no-fasttest, no-cpu-aarch64

No, it's disabled in this scenarios for completely different reason, not because something is slow. Query profiler does not work with sanitizers at all and may work unstably with low values of profiling periods in debug build. It has to be investigated why is it disabled in Fast Test (see the comment in the test). It's disabled on aarch64, because we had some issues with libunwind, but now we can try to enable it.

**Pull request closed without merging**
