### PR TITLE
Fix progress bar jumping near 50%

### LINKED ISSUE #34324: 22.1: progress bar is jumping forward when around 50%
**Describe the issue**
Maybe it's a bug in my implementation of #33271

**How to reproduce**
Run some long query and look carefully with full attention.

### PR DESCRIPTION
**Pull request by alexey-milovidov**
Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
In previous versions the progress bar in clickhouse-client can jump forward near 50% for no reason. This closes #34324

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
Draft, because I did not check it yet.

**Comment by vdimir** [comment]
It *almost* work (with https://github.com/ClickHouse/ClickHouse/pull/34774/commits/4b992fcec31fd61f8144274dbce10037c815684e) but doesn't fit to width a bit at the end 

[asciicast](https://asciinema.org/a/aDrj5B17o5NDpcLE6VOGK9wLR)

**Comment by vdimir** [comment]
Like that [`6f15160` (#34774)](https://github.com/ClickHouse/ClickHouse/pull/34774/commits/6f151608f562c3d1f7d27cb55dd802e740bed2ca) ?

[asciicast](https://asciinema.org/a/dzeliDfJTJMoG7SvmFpP0mGJN)

**Comment by vdimir** [comment]
Like that [`394b727` (#34774)](https://github.com/ClickHouse/ClickHouse/pull/34774/commits/394b727a91ab3b4154283b1c3f897a655c46e879) ?

[asciicast](https://asciinema.org/a/OETbhifu9GDyFkOkRjZ581r2i)

**Review by vdimir — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
Please wait, I did not even try to run it.

**Comment by alexey-milovidov** [comment]
I did not notice your edits, so I've made an alternative code: #34801
Now we have to compare...

By the way, in the last video I see that "CPU" is truncated at right.

**Comment by alexey-milovidov** [comment]
@vdimir Is it ok that I made my edits in another PR and to close this?

**Pull request closed without merging**
