### PR TITLE
Fix build with unbundled Poco

### PR DESCRIPTION
**Pull request by azat**
Changelog category (leave one):
- Non-significant (changelog entry is not required)

Refs: #10396
Cc: @abyss7

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
I see that unbundled build is already Ok: https://clickhouse-builds.s3.yandex.net/10396/0f4dc8329ebd4e6f6ff097aa101cae8d6caa7950/report.html

What we should add to our CI to check your use case?

**Review by alexey-milovidov — APPROVED** [review]
Changes are LGTM.

**Comment by azat** [comment]
>What we should add to our CI to check your use case?

Basically I'm using unbundled + shared + split (with some quirks for my particular env), so this is should be smth like:

```sh
docker/packager/packager --unbundled --split-binary
```

P.S. That will be great!

**Comment by alexey-milovidov** [comment]
@alesapin What do you think?

**Comment by azat** [comment]
Any news?

**Pull request merged**
