### PR TITLE
Update StorageMemory.cpp

### PR DESCRIPTION
**Pull request by markpapadakis**
StorageMemory::read() would sometimes ignore some blocks. This implementation is somewhat more straightforward and likely more performant (no more `std::advance()` calls).

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Bug Fix
- Performance Improvement

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
I don't understand, why it can ignore some blocks?

**Comment by alexey-milovidov** [comment]
In new implementation you are using `step` variable. But looks like it will give less uniform distribution of data between threads.
Suppose we have 9 blocks and 5 threads...

**Comment by markpapadakis** [comment]
@alexey-milovidov Good point about the distribution specifics. Give me a minute for an alternative implementation.

**Comment by markpapadakis** [comment]
@alexey-milovidov 
```cpp
Pipe StorageMemory::read(
    const Names &             column_names,
    const StorageMetadataPtr &metadata_snapshot,
    const SelectQueryInfo & /*query_info*/,
    const Context & /*context*/,
    QueryProcessingStage::Enum /*processed_stage*/,
    size_t /*max_block_size*/,
    unsigned num_streams) {
        metadata_snapshot->check(column_names, getVirtuals(), getStorageID());

        std::lock_guard   lock(mutex);
        const std::size_t size = data.size();

        if (num_streams > size) {
                num_streams = size;
        }

        Pipes             pipes;
        const std::size_t step = std::max<std::size_t>(1, size / num_streams);
        auto              rem  = size - step * num_streams;
        auto              it   = data.begin();

        for (const auto end = data.end(); it != end;) {
                auto        upto            = it;
                std::size_t i               = 0;
                auto        normalized_step = step;

                if (rem) {
                        ++normalized_step;
                        --rem;
                }

                do {
                        ++upto;
                        ++i;
                } while (upto != end && i < normalized_step);

                pipes.emplace_back(std::make_shared<MemorySource>(column_names, it, upto, *this, metadata_snapshot));
                it = upto;
        }

        return Pipe::unitePipes(std::move(pipes));
}
```

**Comment by alexey-milovidov** [comment]
Now the code becomes over-complicated that makes changes not worth doing.
I'll try to apply the idea in https://github.com/ClickHouse/ClickHouse/pull/14056

**Comment by alexey-milovidov** [comment]
It's still unclear if there was any bug.

**Comment by markpapadakis** [comment]
@alexey-milovidov apologies for the confusion. It happened for me once -- I tried to track it down and it was a matter of ignoring a block, which led to this partial rewrite. 
If you are going to use this implementation/alternative, you should update `MemorySource` as well like so:
- is_finished is no longer necessary
- [first, last] because [first, last) i.e last is not inclusive
- generate() becomes

```cpp
Chunk generate() override {
        if (current == last) {
                return {};
        }

        const Block &src = *(current++);
        Columns      columns;

        columns.reserve(column_names.size());

        /// Add only required columns to `res`.
        for (const auto &name : column_names) {
                columns.emplace_back(src.getByName(name).column);
        }

        return Chunk(std::move(columns), src.rows());
}
```


Thank you, and, again, apologies for the confusion.

**Comment by alexey-milovidov** [comment]
It's not possible to make last not inclusive, because it will lead to race condition on parallel insertions:
- it may point to the `end` of list;
- `end` is not invalidated on insertions;
- but `end` is always points to end regardless of new inserted elements;
- so the last range will "extend" concurrently on parallel inserts.

https://clickhouse-test-reports.s3.yandex.net/0/9cac8a7244063d2092ad25d45502611e18d3749c/stress_test_(thread)/stderr.log
https://github.com/ClickHouse/ClickHouse/pull/13416
https://github.com/ClickHouse/ClickHouse/pull/13858

**Comment by alexey-milovidov** [comment]
Is it a chance that the bug you have encountered is the same as described above?
(It was fixed in master.)

**Comment by markpapadakis** [comment]
@alexey-milovidov I think it's very likely that was the culprit.
Thank you, Alexey

**Pull request closed without merging**
