### PR TITLE
Calculate only required columns in system.detached_parts

### LINKED ISSUE #45177: `system.detached_parts` calculates `bytes_on_disk` unconditionally
https://github.com/ClickHouse/ClickHouse/pull/42303#discussion_r1067042215

### PR DESCRIPTION
**Pull request by kssenii**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Closes https://github.com/ClickHouse/ClickHouse/issues/45177.

### CODE REVIEW

**Review by tavplubix — APPROVED** [review]

**Comment by kssenii** [comment]
> Stateless tests (tsan, s3 storage) [3/5] — Tests are not finished, fail: 1

did not find anything in logs... stderr is empty, nothing in runlog, and in clickhouse-server.log only `<Fatal> Application: Child process was terminated by signal 9 (KILL). If it is not done by 'forcestop' command or manually, the possible cause is OOM Killer (see 'dmesg' and look at the '/var/log/kern.log' for the details).`

**Comment by tavplubix** [comment]
> > Stateless tests (tsan, s3 storage) [3/5] — Tests are not finished, fail: 1
> 
> did not find anything in logs... stderr is empty, nothing in runlog, and in clickhouse-server.log only `<Fatal> Application: Child process was terminated by signal 9 (KILL). If it is not done by 'forcestop' command or manually, the possible cause is OOM Killer (see 'dmesg' and look at the '/var/log/kern.log' for the details).`

Looks like OOM. It [may be related](https://play.clickhouse.com/play?user=play#d2l0aCAKJyUwMjE1MV9oYXNoX3RhYmxlX3NpemVzX3N0YXRzX2Rpc3RyaWJ1dGVkJScgYXMgbmFtZV9wYXR0ZXJuLAonMjAyMi0wOS0wMScgYXMgc3RhcnRfZGF0ZQpzZWxlY3QgCnRvU3RhcnRPZkRheShjaGVja19zdGFydF90aW1lKSBhcyBkLApjb3VudCgpLCAgZ3JvdXBVbmlxQXJyYXkocHVsbF9yZXF1ZXN0X251bWJlciksICBhbnkocmVwb3J0X3VybCkKZnJvbSBjaGVja3Mgd2hlcmUgc3RhcnRfZGF0ZSA8PSBjaGVja19zdGFydF90aW1lIGFuZCBwdWxsX3JlcXVlc3RfbnVtYmVyIG5vdCBpbiAKKHNlbGVjdCBwdWxsX3JlcXVlc3RfbnVtYmVyIGFzIHBybiBmcm9tIGNoZWNrcyB3aGVyZSBwcm4hPTAgYW5kIHN0YXJ0X2RhdGUgPD0gY2hlY2tfc3RhcnRfdGltZSBhbmQgY2hlY2tfbmFtZSBpbiAoJ1N0YXRlbGVzcyB0ZXN0cyAoYXNhbiknLCAnU3RhdGVsZXNzIHRlc3RzIChhZGRyZXNzKScsICdTdGF0ZWxlc3MgdGVzdHMgKGFkZHJlc3MsIGFjdGlvbnMpJykpIAphbmQgdGVzdF9uYW1lIGxpa2UgbmFtZV9wYXR0ZXJuIAphbmQgdGVzdF9zdGF0dXMgaW4gKCdGQUlMJywgJ0ZMQUtZJykgZ3JvdXAgYnkgZCBvcmRlciBieSBkIGRlc2M=) to https://github.com/ClickHouse/ClickHouse/pull/44455

@nickitat, could you please take a look?

**Comment by nickitat** [comment]
doesn't seem related. test actually didn't finished:
```
483769:2023.01.11 16:04:00.560851 [ 6290 ] {test_earik289_hash_table_sizes_stats_2400525607} <Trace> Aggregator: Merging aggregated data
483770:2023.01.11 16:04:00.561030 [ 6290 ] {test_earik289_hash_table_sizes_stats_2400525607} <Trace> Aggregator: Statistics updated for key=15678390843594786382: new sum_of_sizes=1000005, median_size=200001
```
but OOM happened 7 minutes later ...

**Comment by tavplubix** [comment]
> doesn't seem related

According to the query I attached above, at the first time it failed like this in https://github.com/ClickHouse/ClickHouse/pull/44455 and then it started to fail in other PRs after https://github.com/ClickHouse/ClickHouse/pull/44455 was merged on 2023-01-09. 

> test actually didn't finished

Yep, it means that OOM happened during the execution of that query (but yes, it's not clear why there are no log messages before OOM)

**Pull request merged**
