### PR TITLE
Support of Nullable types in MySQL tables

### PR DESCRIPTION
**Pull request by edonin**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

For changelog. Remove if this is non-significant change.

Category (leave one):
- New Feature

Currently, ClickHouse is not able to read null from mysql tables (every null are converted into the default value for each column types). I try to add this.

Moreover, I need to extend the integration tests for adding this feature, but I did not figure yet how they work.

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
Clarification: it was already supported for MySQL table engine if you specify Nullable types explicitly.
See https://github.com/yandex/ClickHouse/pull/3362#issuecomment-429184331

This pull request adds support for Nullable types in `mysql` table function (type inference from mysql tables).
I'd like to put this feature under setting (with enabled value by default).

**Comment by alexey-milovidov** [comment]
@edonin Could you please add a setting `external_tables_use_nulls`?

**Comment by edonin** [comment]
So, you are totally right :
This pull request adds support for Nullable types in `mysql` table function (type inference from mysql tables).
A new setting has been added called 'external_tables_use_nulls' (enable by default)  for disabling this null management (currently used only in mysql function).

TODO: integration tests

**Comment by alexey-milovidov** [comment]
Ok.

But I will rename the setting because I just realized that "external tables" can be confused with "external data for query processing".

**Pull request merged**
