### PR TITLE
Fix ORDER BY optimization in case of GROUPING SETS

### LINKED ISSUE #37401: grouping sets + order by (column `time` is not under aggregate)
```sql
SELECT toStartOfHour(time) AS timex, id, count()
FROM
(
    SELECT
        concat('id', toString(number % 3)) AS id,
        toDateTime('2020-01-01') + (number * 60) AS time
    FROM numbers(100)
)
GROUP BY
    GROUPING SETS ( (timex, id), (timex))
ORDER BY timex ASC;

Received exception from server (version 22.5.1):
Code: 215. DB::Exception: Received from localhost:9000. 
DB::Exception: Column `time` is not under aggregate function and not in GROUP BY: 
While processing time ASC. (NOT_AN_AGGREGATE)
```

### PR DESCRIPTION
**Pull request by novikd**
### Changelog category (leave one):

- Bug Fix (user-visible misbehavior in official stable or prestable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Fix optimization of monotonous functions in ORDER BY clause in presence of GROUPING SETS. Fixes #37401

### CODE REVIEW

**Comment by nickitat** [comment]
could you elaborate: now optimizations won't be applied and we will sort by `toStartOfHour(time)`?

**Comment by nickitat** [comment]
> No, optimization still can be applied. The problem was that in case of GROUPING SETS GROUP BY clause was incorrectly analyzed and that led to applying of the optimization even when it's not correct. In test before fix `timex` alias was expanded to `toStartOfHour(time)` and this optimization removed `toStartOfHour` call. But that's not correct, because we don't have column `time` in header.

for me it looks like now optimizations won't be applied and we will sort by toStartOfHour(time) :)

**Review by nickitat — APPROVED** [review]

**Comment by novikd** [comment]
@Mergifyio update

**Comment by novikd** [comment]
> Stress test (memory, actions) — Backward compatibility check: OOM killer (or signal 9)
> Stress test (undefined, actions) — Backward compatibility check: Server failed to start

Unrelated

**Pull request merged**
