### PR TITLE
Parallel replicas: use local plan for local replica by default

### PR DESCRIPTION
**Pull request by devcrafter**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Enable `parallel_replicas_local_plan` by default. Building a full-fledged local plan on the query initiator improves parallel replicas performance with less resource consumption, provides opportunities to apply more query optimizations.

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Run only fuzzers related jobs (libFuzzer fuzzers, AST fuzzers, etc.)
- [ ]  Exclude: AST fuzzers
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-clickhouse-ci-2** [comment]
*This is an automated comment for commit c13d8178db3e65f6cc7ad8ee167cc84e607a1858 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/70171/c13d8178db3e65f6cc7ad8ee167cc84e607a1858/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/70160/2f4518fa66d4baa425fa6ef8479cb8f6debb369d/docs_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Comment by nickitat** [comment]
pls add explanation why we're ready now to enable it by default. you could refer to #69884, maybe smth else. and imo it deserves to be in changelog.

**Comment by devcrafter** [comment]
> pls add explanation why we're ready now to enable it by default. you could refer to #69884, maybe smth else. and imo it deserves to be in changelog.

We're not ready yet, but it worth it to have this PR for reference and some CI runs with the enabled setting. I'll mention dependencies here

**Comment by devcrafter** [comment]
Current known dependencies for enabling `parallel_replicas_local_plan'
- [ ] https://github.com/ClickHouse/ClickHouse/pull/70173

**Pull request merged**
