### PR TITLE
Fix typo in ActionsDag

### PR DESCRIPTION
**Pull request by liuneng1994**
Fix link to pattern syntax

fix typo

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [X]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Run only fuzzers related jobs (libFuzzer fuzzers, AST fuzzers, etc.)
- [ ]  Exclude: AST fuzzers
---
- [x]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Review by hanfei1991 — APPROVED** [review]

**Comment by hanfei1991** [comment]
Hi @liuneng1994 thanks for contribution

Don't delete CI checkboxes in the pr description next time, so that I can ignore the useless tests for the PR.

**Comment by liuneng1994** [comment]
> Hi @liuneng1994 thanks for contribution
> 
> Don't delete CI checkboxes in the pr description next time, so that I can ignore the useless tests for the PR.

ok

**Comment by hanfei1991** [comment]
@liuneng1994 interesting that we have similar github user id pattern :)

**Comment by robot-clickhouse** [comment]
*This is an automated comment for commit f7fda2471cba5f5e975cef247f10060084734fcb with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/69086/f7fda2471cba5f5e975cef247f10060084734fcb/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

**Pull request merged**
