### PR TITLE
Update libhdfs3 version 

### PR DESCRIPTION
**Pull request by taiyang-li**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix checking error caused by uninitialized class members 

related pr: https://github.com/ClickHouse/libhdfs3/pull/46

### CODE REVIEW

**Comment by robot-ch-test-poll** [comment]
This is an automated comment for commit e6535b1f875931d46421166897a2a912b6b8a17d with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/51418/e6535b1f875931d46421166897a2a912b6b8a17d/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Comment by taiyang-li** [comment]
@kssenii  can you merge this pr, it only updates the libhdfs3 version.

**Comment by kssenii** [comment]
Screenshot 2023-06-27 at 13 01 16

I cannot merge ^, please update the branch and I will be able to merge before mergeable check starts.

**Comment by taiyang-li** [comment]
Do we have some way to force merge this pr, the fix is obvious, and it is easily reproduced in hadoop ec cluster.

**Comment by kssenii** [comment]
Please update the branch.

**Comment by kssenii** [comment]
no related failures: 

> Integration tests (asan) [4/6] — fail: 1

test_multiple_disks

> Integration tests (release) [1/4] — fail: 1

test_keeper_map

**Comment by kssenii** [comment]
@taiyang-li , checks not passed, so merging is blocked, I cannot force merge, only Alexey can.

Though I can merge in an interval when the branch is updated and checks did not start yet. But your branch is protected from maintainer's commits, so I cannot update your branch myself.

**Comment by taiyang-li** [comment]
> @taiyang-li , checks not passed, so merging is blocked, I cannot force merge, only Alexey can.
> 
> Though I can merge in an interval when the branch is updated and checks did not start yet. But your branch is protected from maintainer's commits, so I cannot update your branch myself.

I updated branch again,  let's wait and see the ci result

**Review by kssenii — APPROVED** [review]

**Pull request merged**
