### PR TITLE
Remove unused files that confuse developers #26913

### PR DESCRIPTION
**Pull request by alexey-milovidov**
Changelog category (leave one):
- Not for changelog (changelog entry is not required)

See #26913.

It was someone's "personal" scripts. They are not used by CI.
Maybe they was used in official Debian packaging process long time ago.

### CODE REVIEW

**Comment by qoega** [comment]
Probably it is a part of CTest.

**Comment by alexey-milovidov** [comment]
1. We don't use CTest.
2. This file is unused according to `grep`.

**Comment by nikitamikhaylov** [comment]
@alexey-milovidov File `tests/clickhouse-server.xml` is used in Arcadia to execute our tests there. You can see in [history](https://github.com/ClickHouse/ClickHouse/commits/master/tests/clickhouse-test-server) that this file was deleted by azat@, but returned back by me. If we want to completely remove Arcadia from our lives, we can delete it :)

**Comment by alexey-milovidov** [comment]
Ok, I've added a comment to it.

It would be better:
- to move these sort of files to some dedicated attic that no one will look;
- name them accordingly, like `arcadia-server-config.xml`.

**Pull request merged**
