### PR TITLE
Utilize `ngrambf` and `tokenbf` indexes by function `match()`

### LINKED ISSUE #56939: Add support for bloom filter based indexes for `match`/`REGEXP`
- We have bloom-filter-based skip indexes `ngrambf_v1`/`tokenbf_v1`.
- These indexes are supported by many operators/functions, including `like()`/`has()`/`hasToken()`,
see https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/mergetree#functions-support
- `match()` function has no optimizations related to bloom-filter-based skip indexes

Use case: user specifies a complex regexp in a `match()` predicate and it is not obvious that performance can be improved if user will add additional `has` condition before `match`.

To implement this: get a list of "required" substrings from the regexp, i.e. strings that are present in every matching string (see `OptimizedRegularExpression::analyze()`), then query the skip indexes with these substrings.

### PR DESCRIPTION
**Pull request by lingtaolf**
Fixes  #56939

### Changelog category (leave one):
- Performance Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
The evaluation of function `match()` now utilizes skipping indices `ngrambf_v1` and `tokenbf_v1`.

### CODE REVIEW

**Comment by robot-ch-test-poll1** [comment]
*This is an automated comment for commit 3bd7505a836a2181bc0aa92cb344a9c34f581c07 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/57882/3bd7505a836a2181bc0aa92cb344a9c34f581c07/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td><a href="https://github.com/ClickHouse/ClickHouse/actions/runs/7217722863">✅ success</a></td></tr>
<tbody>
</table>
</details>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/57882/3bd7505a836a2181bc0aa92cb344a9c34f581c07/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Comment by lingtaolf** [comment]
@rschu1ze Hi, could you help review the code ? Thx!

**Comment by rschu1ze** [comment]
@lingtaolf Sure, I am checking right now.

**Review by rschu1ze — APPROVED** [review]

**Comment by rschu1ze** [comment]
@lingtaolf This PR is ready to merge (thanks again). What would be great (but totally optional) is if you could apply similar changes to MergeTreeIndexInverted.cpp (aka. the inverted index). But if you don't have time, I can also do that by myself.

**Comment by lingtaolf** [comment]
> @lingtaolf This PR is ready to merge (thanks again). What would be great (but totally optional) is if you could apply similar changes to MergeTreeIndexInverted.cpp aka. the inverted index. But if you don't have time, I can also do that by myself.

@rschu1ze Thanks for reviewing, and I will try it to MergeTreeIndexInverted.

**Comment by lingtaolf** [comment]
@rschu1ze Some tests fail, do we need to fix them ?

**Comment by rschu1ze** [comment]
@lingtaolf It would be great to merge `master` into this PR (some of the failures are fixed upstream). This [failure](https://s3.amazonaws.com/clickhouse-test-reports/57882/6df2548417c46023aff87339f53691501380b48a/stateless_tests__release__analyzer_.html) is however related. To reproduce + fix this, please enable the new analyzer with `SET allow_experimental_analyzer = 1;` (as SQL statement at the beginning of the test) and re-run the test.

**Comment by lingtaolf** [comment]
> @lingtaolf It would be great to merge `master` into this PR (some of the failures are fixed upstream). This [failure](https://s3.amazonaws.com/clickhouse-test-reports/57882/6df2548417c46023aff87339f53691501380b48a/stateless_tests__release__analyzer_.html) is however related. To reproduce + fix this, please enable the new analyzer with `SET allow_experimental_analyzer = 1;` (as SQL statement at the beginning of the test) and re-run the test.

@rschu1ze I've tried to add add `SET allow_experimental_analyzer = 1;` statement at the beginning of the tests, but this test run successfully on my computer.

**Comment by lingtaolf** [comment]
> @lingtaolf It would be great to merge `master` into this PR (some of the failures are fixed upstream). This [failure](https://s3.amazonaws.com/clickhouse-test-reports/57882/6df2548417c46023aff87339f53691501380b48a/stateless_tests__release__analyzer_.html) is however related. To reproduce + fix this, please enable the new analyzer with `SET allow_experimental_analyzer = 1;` (as SQL statement at the beginning of the test) and re-run the test.

@rschu1ze Done !

**Comment by lingtaolf** [comment]
@rschu1ze Please check if this pr can be merged. If it's ok , I will start implementing it on the inverted index

**Comment by rschu1ze** [comment]
Sorry for the delay (was out due to Christmas holiday). While the analyzer is still experimental, we need to test the old path and the analyzer path. I made a small test adjustment and will merge the PR afterwards.

**Comment by qoega** [comment]
It is a great feature. We need to update docs as well! 
https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/mergetree#token-bloom-filter

**Pull request merged**
