### PR TITLE
tests: make 01600_parts_states_metrics_long better

### PR DESCRIPTION
**Pull request by azat**
- better bash
- HTTP protocol cannot handle multiple queries fix this
- decrease number of retries (this should be ok after no-parallel) to print final debug info

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Refs: https://github.com/ClickHouse/ClickHouse/issues/68255 (cc @antaljanosbenjamin)

### CODE REVIEW

**Comment by robot-ch-test-poll3** [comment]
*This is an automated comment for commit a0f617c6cc06cd80ecbb485965f6b7e7763be18c with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/68265/a0f617c6cc06cd80ecbb485965f6b7e7763be18c/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Builds</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/ae5223854f71361a4cafdd6bafad3e2cc770432b/builds/report.html">✅ success</a></td></tr>
<tr><td>ClickBench</td><td>Runs [ClickBench](https://github.com/ClickHouse/ClickBench/) with instant-attach table</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/ae5223854f71361a4cafdd6bafad3e2cc770432b/clickbench__aarch64_.html">✅ success</a></td></tr>
<tr><td>Compatibility check</td><td>Checks that <b>clickhouse</b> binary runs on distributions with old libc versions. If it fails, ask a maintainer for help</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/ae5223854f71361a4cafdd6bafad3e2cc770432b/compatibility_check__aarch64_.html">✅ success</a></td></tr>
<tr><td>Docker keeper image</td><td>The check to build and optionally push the mentioned image to docker hub</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/ae5223854f71361a4cafdd6bafad3e2cc770432b/docker_keeper_image.html">✅ success</a></td></tr>
<tr><td>Docker server image</td><td>The check to build and optionally push the mentioned image to docker hub</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/ae5223854f71361a4cafdd6bafad3e2cc770432b/docker_server_image.html">✅ success</a></td></tr>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/40382451a291896c13e4fae57aed2b761563d10e/docs_check.html">✅ success</a></td></tr>
<tr><td>Install packages</td><td>Checks that the built packages are installable in a clear environment</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/ae5223854f71361a4cafdd6bafad3e2cc770432b/install_packages__aarch64_.html">✅ success</a></td></tr>
<tr><td>Integration tests</td><td>The integration tests report. In parenthesis the package type is given, and in square brackets are the optional part/total tests</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/ae5223854f71361a4cafdd6bafad3e2cc770432b/integration_tests__aarch64__[1_6].html">✅ success</a></td></tr>
<tr><td>Stateful tests</td><td>Runs stateful functional tests for ClickHouse binaries built in various configurations -- release, debug, with sanitizers, etc</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/ae5223854f71361a4cafdd6bafad3e2cc770432b/stateful_tests__aarch64_.html">✅ success</a></td></tr>
<tr><td>Unit tests</td><td>Runs the unit tests for different release types</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/ae5223854f71361a4cafdd6bafad3e2cc770432b/unit_tests__asan_.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Review by antaljanosbenjamin — APPROVED** [review]

**Comment by antaljanosbenjamin** [comment]
Thanks @azat, great work again!

**Comment by antaljanosbenjamin** [comment]
The cloud sync failed because of unrelated reasons, once the fix is merged in private, I will handle the sync PR.

**Comment by alexey-milovidov** [comment]
@azat, it isn't any better: https://s3.amazonaws.com/clickhouse-test-reports/0/f2e9d31cb34989362231679514802256dfd8bbbe/stateless_tests__tsan__s3_storage__[2_4].html

**Pull request merged**
