### PR TITLE
Performance check build AVX2

### PR DESCRIPTION
**Pull request by kitaisreal**
Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Check performance with AVX2 instructions enabled.

### CODE REVIEW

**Comment by kitaisreal** [comment]
@Mergifyio update

**Comment by kitaisreal** [comment]
@Mergifyio update

**Comment by kitaisreal** [comment]
@Mergifyio update

**Comment by kitaisreal** [comment]
@Mergifyio update

**Comment by kitaisreal** [comment]
@Mergifyio update

**Comment by kitaisreal** [comment]
@Mergifyio update

**Comment by kitaisreal** [comment]
@Mergifyio update

**Comment by alexey-milovidov** [comment]
Abandoned, conflicts with master.

**Pull request closed without merging**
