### PR TITLE
Deprecate the `metadata_cache` feature

### LINKED ISSUE #39197: Parts metadata cache and failing mutation
https://s3.amazonaws.com/clickhouse-test-reports/0/2079699f7542527d62cbaed828940d54b0ca00a2/stress_test__undefined__actions_.html

BC check in Stress Tests sometimes fail with 
```
2022.07.13 10:26:18.097238 [ 1051250 ] {} <Error> MutateFromLogEntryTask: virtual bool DB::ReplicatedMergeMutateTaskBase::executeStep(): Code: 47. DB::Exception: Missing columns: 'v3' while processing query: 'v3, k, v1, v2, p', required columns: 'v3' 'k' 'v1' 'v2' 'p', maybe you meant: ['v1','k','v1','v2','p']. (UNKNOWN_IDENTIFIER), Stack trace (when copying this message, always include the lines below):
2022.07.13 10:26:18.098966 [ 1051240 ] {} <Error> MutateFromLogEntryTask: virtual bool DB::ReplicatedMergeMutateTaskBase::executeStep(): Code: 47. DB::Exception: Missing columns: 'v3' while processing query: 'v3, k, v1, v2, p', required columns: 'v3' 'k' 'v1' 'v2' 'p', maybe you meant: ['v1','k','v1','v2','p']. (UNKNOWN_IDENTIFIER), Stack trace (when copying this message, always include the lines below):
2022.07.13 10:26:18.101742 [ 1051251 ] {} <Error> MutateFromLogEntryTask: virtual bool DB::ReplicatedMergeMutateTaskBase::executeStep(): Code: 47. DB::Exception: Missing columns: 'v3' while processing query: 'v3, k, v1, v2, p', required columns: 'v3' 'k' 'v1' 'v2' 'p', maybe you meant: ['v1','k','v1','v2','p']. (UNKNOWN_IDENTIFIER), Stack trace (when copying this message, always include the lines below):
```
i.e. some mutation cannot be executed (slightly related to #39174). This mutation was started by the test `01233_check_table_with_metadata_cache`. Logs:
by table id: https://pastila.nl/?024eb85d/65a0e50dba5aafb52d0ecec2cf2d5737
by query ids: https://pastila.nl/?002a7f2e/7505e0215864bbb1ea3da78c4a0151db

The second mutation (`MODIFY TTL` + implicit `MATERIALIZE TTL`) is trying to read from column that was dropped by the first mutation (`DROP COLUMN v3`). The error persists after server restart, so I suppose metadata was corrupted. Probably not metadata itself, but metadata cache. 

cc: @taiyang-li, @CurtizJ

### PR DESCRIPTION
**Pull request by alexey-milovidov**
### Changelog category (leave one):
- Backward Incompatible Change

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Deprecate the metadata cache feature. It is experimental and we have never used it. The feature is dangerous: #51182. Remove the `system.merge_tree_metadata_cache` system table. The metadata cache is still available in this version but will be removed soon. This closes #39197.

### CODE REVIEW

**Comment by robot-ch-test-poll2** [comment]
This is an automated comment for commit 8b1cd9fcec4408933d537bd1b74a382884d7b52f with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/51303/8b1cd9fcec4408933d537bd1b74a382884d7b52f/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Review by nikitamikhaylov — APPROVED** [review]

**Comment by pufit** [comment]
I've returned metadata_cache.xml into the configs, so the upgrade check should finish properly. After that, we can remove this config once and for all.

**Comment by eumenide** [comment]
@alexey-milovidov 
Hi, i've douted that do merge_tree_metadata_cache settings and use_metadata_cache=1 when creating tables mean the same thing?
This feature is used to speed up loading CH, if it's removed, how can we solve the slow loading of CH?

**Comment by alexey-milovidov** [comment]
The latest ClickHouse versions have parallel metadata loading to speed up the start-up time.
You can also enable asynchronous tables loading in the configuration file.

**Pull request merged**
