### PR TITLE
Parallelise pipeline after `CubeStep`

### PR DESCRIPTION
**Pull request by nickitat**
### Changelog category (leave one):
- Performance Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Pipeline is now parallelised after `CubeStep` (group by queries with `WITH CUBE`) to ensure parallelism of the subsequent transforms.

---

I don't see any big blockers for that. Maybe few tests will require updates. As soon as tests are fixed will fix a couple of similar places too.

### CODE REVIEW

**Comment by robot-clickhouse-ci-1** [comment]
*This is an automated comment for commit 5dddbbbbb140da2b7f902a34e88f37c050383459 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/60467/5dddbbbbb140da2b7f902a34e88f37c050383459/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/60467/5dddbbbbb140da2b7f902a34e88f37c050383459/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Comment by nickitat** [comment]
`AST fuzzer (asan)` - #57705 
`AST fuzzer (debug)` - #57705
`AST fuzzer (msan)` - #57705
`AST fuzzer (ubsan)` - #57705

**Comment by nickitat** [comment]
need to check why perf tests were unhappy

**Comment by alexey-milovidov** [comment]
@nickitat, please resolve conflicts.

**Pull request closed without merging**
