### PR TITLE
Revert "Revert "Fix bug on mutations with subcolumns of type JSON in predicates of UPDATE and DELETE queries.""

### PR DESCRIPTION
**Pull request by VanDarkholme7**
Reverts #54063

Original from #53677 

### Changelog category (leave one):
- Bug Fix 

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix failed stateless tests, `00992_system_parts_race_condition_zookeeper_long` and `00002_log_and_exception_messages_formatting` should be able to pass.

### CODE REVIEW

**Comment by VanDarkholme7** [comment]
Please add CAN BE TESTED label @CurtizJ @tavplubix

**Comment by VanDarkholme7** [comment]
Please add CAN BE TESTED label to check if it works. @CurtizJ  @tavplubix

**Comment by robot-ch-test-poll2** [comment]
This is an automated comment for commit c754c7cc90dd5bb7f92910c71692f1c71f97bd22 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/54112/c754c7cc90dd5bb7f92910c71692f1c71f97bd22/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Comment by VanDarkholme7** [comment]
`test_storage_azure_blob_storage/test.py::test_schema_inference_cache`
`test_server_reload/test.py::test_change_grpc_port`
`test_server_reload/test.py::test_remove_grpc_port`
Didn't reproduce these failed tests, it seems they are not related, please take a look. @CurtizJ

**Comment by VanDarkholme7** [comment]
All checks are passed, please take a look. @CurtizJ @tavplubix

**Pull request closed without merging**
