### PR TITLE
Fix: missing conversion in IN operator with parallel replicas

### PR DESCRIPTION
**Pull request by devcrafter**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Incorrect query result with parallel replicas (distribute queries as well) when `IN` operator contains conversion to Decimal(). The bug was introduced with the new analyzer.

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-clickhouse-ci-1** [comment]
*This is an automated comment for commit d1c45662e8560177eb1e90d5ad159b58ff396f44 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/67234/d1c45662e8560177eb1e90d5ad159b58ff396f44/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

**Comment by alexey-milovidov** [comment]
Tests have to be updated.

**Comment by alexey-milovidov** [comment]
Still does not match.

**Review by novikd — APPROVED** [review]
LGTM, but I guess @KochetovNicolai may have some concerns. Let's merge only after he approves the PR.

**Comment by devcrafter** [comment]
AST fuzzer (debug) [failure](https://s3.amazonaws.com/clickhouse-test-reports/67234/866a2a86917f95cecf9da139ef3a80baa1a1fde4/ast_fuzzer__debug_.html) - known issue https://github.com/ClickHouse/ClickHouse/issues/67330

**Comment by devcrafter** [comment]
`Stateful tests (tsan)` failure - https://github.com/ClickHouse/ClickHouse/issues/67010

**Comment by novikd** [comment]
@devcrafter Do we need to backport it?

**Comment by aalexfvk** [comment]
@devcrafter Could you create a public backport of this PR ? At least in 24.8

**Pull request merged**
