### PR TITLE
Improve woboq codebrowser pipeline

### PR DESCRIPTION
**Pull request by Felixoid**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by robot-ch-test-poll2** [comment]
This is an automated comment for commit 0f93c8963087c9628e8328401178778e2f5b3bf3 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/49701/0f93c8963087c9628e8328401178778e2f5b3bf3/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Comment by Felixoid** [comment]
I failed to produce a proper report for a called workflow, it doesn't have a way to receive a proper `GITHUB_JOB_URL` https://github.com/actions/runner/issues/2577

It as well prevents us from moving to reusable workflows, suddenly

**Comment by Felixoid** [comment]
Ok, the report looks [fixed](https://s3.amazonaws.com/clickhouse-test-reports/49701/f512cb748ec20441df63fb21cbd0740e96e97dea/woboq_build.html) somehow now.

The final launch with full running, and then merging it today

**Comment by Felixoid** [comment]
https://s3.amazonaws.com/clickhouse-test-reports/49701/4dcdcf4c11b5604f1c5d3121c9c6fea3e957b605/woboq_build.html

The run succeeded, I am rebasing it, waiting for the style check, and merging.

**Pull request merged**
