### PR TITLE
add line number in logs

### PR DESCRIPTION
**Pull request by taiyang-li**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
- Append source file line number to logged messages

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
Could you please provide an example of how does it look?

**Comment by filimonov** [comment]
Will it work w/o debug symbols installed?

**Comment by alexey-milovidov** [comment]
> Will it work w/o debug symbols installed?

Yes.

**Comment by taiyang-li** [comment]
> Could you please provide an example of how does it look?

Log will like this: 
```
2020.07.07 10:27:13.964506 [ 3816 ] {} <Information> TCPHandler[372]: Processed in 0.007 sec.
```

**Review by azat — COMMENTED** [review]
There is also another place - https://github.com/ClickHouse/ClickHouse/blob/488a8cbc9fc15d5f2fde70e6cff17521fc195c1d/src/DataStreams/InternalTextLogsRowOutputStream.cpp#L96

But, is it really useful? I doubt that there are duplicated log messages on different lines

**Comment by taiyang-li** [comment]
> There is also another place -
> 
> https://github.com/ClickHouse/ClickHouse/blob/488a8cbc9fc15d5f2fde70e6cff17521fc195c1d/src/DataStreams/InternalTextLogsRowOutputStream.cpp#L96
> 
> But, is it really useful? I doubt that there are duplicated log messages on different lines

When SET send_logs_level = 'trace' ,  logs will be printed out in clickhouse-client cmdline.

**Comment by alexey-milovidov** [comment]
It is strange that we will show line number without a file name.

**Comment by alexey-milovidov** [comment]
Also it does not look pretty:
```
<Trace> AccessRightsContext (default)[112]: Access granted: 
```

(whitespaces are not balanced)

**Comment by alexey-milovidov** [comment]
`2020.07.07 10:27:13.960542 [ 3816 ] {45a4d70e-6236-4930-b2d3-0908551c179b} <Trace> AccessRightsContext (default)`

Maybe this will be better?

`2020.07.07 10:27:13.960542 [ 3816 ] {45a4d70e-6236-4930-b2d3-0908551c179b} StorageReplicatedMergeTree.cpp:42 <Trace> AccessRightsContext (default)`

**Comment by taiyang-li** [comment]
Done.

**Comment by filimonov** [comment]
@taiyang-li can you explait why it is needed? it will increase the log sizes significantly, will brake the log parsers some people use, it would be ok if there is a good motivation for that.

I can't see it right now (you easely can find the file & line number by greping the source code by message feagmentl)

**Comment by taiyang-li** [comment]
@filimonov greping by message keyword will not be very convenient when the message keyword is very common. Print source file and line number would help you find the source code more directly, and the new added part to the log is short.

**Comment by azat** [comment]
>greping by message keyword will not be very convenient when the message keyword is very common

But are not too much of common messages, and this PR will increase logs messages for all of them.
Maybe the log format should be done configurable? i.e.

``xml
<yandex>
  <logger>
    ..
    <format>...</format>
  </logger>
</yandex>
```

**Comment by azat** [comment]
>when the message keyword is very common

It is not that common (yes this does not 100% correct but shows the picture, plus some of logging messages contains different log source):

```
# alias gg='git grep'
$ gg '\<LOG_' src base programs | awk -F'"' '{print $(NF-1)}' | sort | uniq -c | sort -nr | head
      9 PerfEvents # this is incorrect, since it is source/logger name not the message itself
      7 Request URI: {}
      4 Table {} is already finished removing by another replica right now
      4 src/Databases/DatabaseAtomic.cpp:        LOG_WARNING(log, getCurrentExceptionMessage(true));
      4 src/Client/Connection.cpp:        LOG_DEBUG(log_wrapper.get(),
      4 loadAll {}
      4 
      3 Waiting for threads to finish
      3 Task {} has already been executed by replica ({}) of the same shard.
      3 src/Storages/StorageReplicatedMergeTree.cpp:                LOG_INFO(log, e.displayText());
```

That said that maybe it is better to make the messages less common?

**Comment by taiyang-li** [comment]
ok, maybe it is better to find source code by grep.

**Comment by alexey-milovidov** [comment]
@azat 

> Maybe the log format should be done configurable?

Yes, it will be better to add configurable log format. It should support proper escaping (for example - to get correct JSON). Ideally we can allow to specify custom format name for log (including JSONEachRow, TSV and Template) and allow to specify template string for `Template` format. It will format the same data that we have in `system.text_log` table.

But how we can deal with colors?

**Comment by azat** [comment]
>But how we can deal with colors?

Add some format string for this? i.e. `%(cb)%(priority)%(ce)` (`cb` stands for color begin, `ce` stands for color end)
But this will be not that simple to parse (since priority has it's own set of colors), then maybe simply `%(priority)s` - no colors, `%(priority)c` - colored (or even something more sophisticated `%colored(priority)`), or even just use one global switch

**Comment by alexey-milovidov** [comment]
@azat 

I want it to reuse our formats and their settings. So, format Template can be used for this purpose (and any other format as well).

Maybe we can add some fields like `query_id_color String`, `thread_id_color String`, ... , `color_end String` that the user can use to highlight logs.

Then we have two options:
- make these fields empty if output not to terminal;
- split configuration of the format when output is terminal and not terminal.

These fields are also inconvenient when the user wants to output all fields.

**Pull request closed without merging**
