### PR TITLE
Mask azure connection string sensitive info

### PR DESCRIPTION
**Pull request by alexkats**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Mask azure connection string sensitive info

<details><summary>CI</summary>

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Run only fuzzers related jobs (libFuzzer fuzzers, AST fuzzers, etc.)
- [ ]  Exclude: AST fuzzers
---
- [ ]  Do not test
- [x]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

</details>

### CODE REVIEW

**Comment by alexkats** [comment]
Issues not addressed in this PR: #69571

**Comment by robot-clickhouse-ci-2** [comment]
*This is an automated comment for commit 95dcbc07ee6c27dff0c40ffd31765444afa1a848 with description of existing statuses. It's updated for the latest CI running*

[❌ Click here](https://s3.amazonaws.com/clickhouse-test-reports/69570/95dcbc07ee6c27dff0c40ffd31765444afa1a848/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Style check</td><td>Runs a set of checks to keep the code style clean. If some of tests failed, see the related log from the report</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/69570/95dcbc07ee6c27dff0c40ffd31765444afa1a848/style_check.html">❌ failure</a></td></tr>
<tbody>
</table>

**Comment by yakov-olkhovskiy** [comment]
this becoming a mess
I'm trying to unify it
@alexkats let's put this PR on hold for a while

**Comment by yakov-olkhovskiy** [comment]
https://github.com/ClickHouse/ClickHouse/pull/69615
it's ugly, but it's best I could invent...

**Review by yakov-olkhovskiy — APPROVED** [review]

**Pull request merged**
