### PR TITLE
Fix build without liburing (-DENABLE_LIBRARIES=OFF)

### PR DESCRIPTION
**Pull request by azat**
The code for uioring simply checks for if OS is Linux, however this is not enough, it should check for `ENABLE_LIBURING` [1], so pass through this to the config header and use it.

   [1]: https://github.com/ClickHouse/ClickHouse/blob/0c13870eb1b1778c2dbbe4f8a32763e1df63cf76/contrib/liburing-cmake/CMakeLists.txt#L7

https://github.com/ClickHouse/ClickHouse/blob/0c13870eb1b1778c2dbbe4f8a32763e1df63cf76/contrib/liburing-cmake/CMakeLists.txt#L7

Follow-up for: #38456 (cc @sauliusvl )

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by nickitat** [comment]
would be useful to provide this link: https://github.com/ClickHouse/ClickHouse/blob/master/contrib/liburing-cmake/CMakeLists.txt#L1

**Comment by azat** [comment]
@nickitat where? in the PR description?

**Review by alexey-milovidov — APPROVED** [review]

**Comment by nickitat** [comment]
> @nickitat where? in the PR description?

for example.

**Review by nickitat — APPROVED** [review]

**Comment by azat** [comment]
Test failures looks unrelated:

- `test_cluster_copier` - #30399

Could be closed if #45997 will be merged first.

**Comment by azat** [comment]
This has been already fixed in #46088 (@rschu1ze ). Closing.

**Pull request closed without merging**
