### PR TITLE
Reduce external sorting memory usage on large table and speed up sorting

### PR DESCRIPTION
**Pull request by liuneng1994**
When the data is externally sorted, multiple temporary files will be generated according to max_bytes_before_external_sort, and these files will be merged at the same time during the merge. In the following example, there will be about 144 files. When merging, 144 blocks will be read at the same time. Each block is about 150MB and requires about 21.5GB of memory. Limit the total memory size of blocks in the temporary file by introducing prefer_merge_sort_block_bytes. , which can prevent the memory overhead during merging from being proportional to the number of columns, significantly reducing memory usage.

Test case
``` sql
create table test_order ( val00 Int64, val01 Int64, val02 Int64, val03 Int64, val04 Int64, val05 Int64, val06 Int64, val07 Int64, val08 Int64, val09 Int64, val10 Int64, val11 Int64, val12 Int64, val13 Int64, val14 Int64, val15 Int64, val16 Int64, val17 Int64, val18 Int64, val19 Int64, val20 Int64, val21 Int64, val22 Int64, val23 Int64, val24 Int64, val25 Int64, val26 Int64, val27 Int64, val28 Int64, val29 Int64, val30 Int64, val31 Int64, val32 Int64, val33 Int64, val34 Int64, val35 Int64, val36 Int64, val37 Int64, val38 Int64, val39 Int64, val40 Int64, val41 Int64, val42 Int64, val43 Int64, val44 Int64, val45 Int64, val46 Int64, val47 Int64, val48 Int64, val49 Int64, val50 Int64, val51 Int64, val52 Int64, val53 Int64, val54 Int64, val55 Int64, val56 Int64, val57 Int64, val58 Int64, val59 Int64, val60 Int64, val61 Int64, val62 Int64, val63 Int64, val64 Int64, val65 Int64, val66 Int64, val67 Int64, val68 Int64, val69 Int64, val70 Int64, val71 Int64, val72 Int64, val73 Int64, val74 Int64, val75 Int64, val76 Int64, val77 Int64, val78 Int64, val79 Int64, val80 Int64, val81 Int64, val82 Int64, val83 Int64, val84 Int64, val85 Int64, val86 Int64, val87 Int64, val88 Int64, val89 Int64, val90 Int64, val91 Int64, val92 Int64, val93 Int64, val94 Int64, val95 Int64, val96 Int64, val97 Int64, val98 Int64, val99 Int64, val100 Int64, val101 Int64, val102 Int64, val103 Int64, val104 Int64, val105 Int64, val106 Int64, val107 Int64, val108 Int64, val109 Int64, val110 Int64, val111 Int64, val112 Int64, val113 Int64, val114 Int64, val115 Int64, val116 Int64, val117 Int64, val118 Int64, val119 Int64, val120 Int64, val121 Int64, val122 Int64, val123 Int64, val124 Int64, val125 Int64, val126 Int64, val127 Int64, val128 Int64, val129 Int64, val130 Int64, val131 Int64, val132 Int64, val133 Int64, val134 Int64, val135 Int64, val136 Int64, val137 Int64, val138 Int64, val139 Int64, val140 Int64, val141 Int64, val142 Int64, val143 Int64, val144 Int64, val145 Int64, val146 Int64, val147 Int64, val148 Int64, val149 Int64, val150 Int64, val151 Int64, val152 Int64, val153 Int64, val154 Int64, val155 Int64, val156 Int64, val157 Int64, val158 Int64, val159 Int64, val160 Int64, val161 Int64, val162 Int64, val163 Int64, val164 Int64, val165 Int64, val166 Int64, val167 Int64, val168 Int64, val169 Int64, val170 Int64, val171 Int64, val172 Int64, val173 Int64, val174 Int64, val175 Int64, val176 Int64, val177 Int64, val178 Int64, val179 Int64, val180 Int64, val181 Int64, val182 Int64, val183 Int64, val184 Int64, val185 Int64, val186 Int64, val187 Int64, val188 Int64, val189 Int64, val190 Int64, val191 Int64, val192 Int64, val193 Int64, val194 Int64, val195 Int64, val196 Int64, val197 Int64, val198 Int64, val199 Int64, val200 Int64, val201 Int64, val202 Int64, val203 Int64, val204 Int64, val205 Int64, val206 Int64, val207 Int64, val208 Int64, val209 Int64, val210 Int64, val211 Int64, val212 Int64, val213 Int64, val214 Int64, val215 Int64, val216 Int64, val217 Int64, val218 Int64, val219 Int64, val220 Int64, val221 Int64, val222 Int64, val223 Int64, val224 Int64, val225 Int64, val226 Int64, val227 Int64, val228 Int64, val229 Int64, val230 Int64, val231 Int64, val232 Int64, val233 Int64, val234 Int64, val235 Int64, val236 Int64, val237 Int64, val238 Int64, val239 Int64, val240 Int64, val241 Int64, val242 Int64, val243 Int64, val244 Int64, val245 Int64, val246 Int64, val247 Int64, val248 Int64, val249 Int64, val250 Int64, val251 Int64, val252 Int64, val253 Int64, val254 Int64, val255 Int64, val256 Int64, val257 Int64, val258 Int64, val259 Int64, val260 Int64, val261 Int64, val262 Int64, val263 Int64, val264 Int64, val265 Int64, val266 Int64, val267 Int64, val268 Int64, val269 Int64, val270 Int64, val271 Int64, val272 Int64, val273 Int64, val274 Int64, val275 Int64, val276 Int64, val277 Int64, val278 Int64, val279 Int64, val280 Int64, val281 Int64, val282 Int64, val283 Int64, val284 Int64, val285 Int64, val286 Int64, val287 Int64, val288 Int64, val289 Int64, val290 Int64, val291 Int64, val292 Int64, val293 Int64, val294 Int64, val295 Int64, val296 Int64, val297 Int64, val298 Int64, val299 Int64 ) engine = MergeTree order by tuple();
 insert into test_order select number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number from numbers(12000000);
```

max_bytes_before_external_sort=200000000
```
SELECT *
FROM test_order
ORDER BY val00 ASC
SETTINGS max_bytes_before_external_sort = 200000000
FORMAT `Null`

Query id: c7e91233-c000-4117-8255-3c9037dde978

↑ Progress: 11.92 million rows, 28.60 GB (49.17 thousand rows/s., 118.00 MB/s.) (0.0 CPU, 3.41 GB RAM)████████████████████████████████████████████████████████████████████████████████████████████████████████████████ 99%^Cancelling query.
Ok.
Query was cancelled.

0 rows in set. Elapsed: 242.583 sec. Processed 11.92 million rows, 28.60 GB (49.13 thousand rows/s., 117.90 MB/s.)
Peak memory usage: 5.42 GiB.

```
too slow

max_bytes_before_external_sort=200000000,prefer_merge_sort_block_bytes=10000000 
```
SELECT *
FROM test_order
ORDER BY val00 ASC
SETTINGS max_bytes_before_external_sort = 200000000, prefer_merge_sort_block_bytes = 10000000
FORMAT `Null`

Query id: a89db50b-acd5-4a81-853c-3a08996c9936

Ok.

0 rows in set. Elapsed: 15.565 sec. Processed 11.92 million rows, 28.60 GB (765.64 thousand rows/s., 1.84 GB/s.)
Peak memory usage: 11.76 GiB.

```
15.5s peak mem 11.76GB

max_bytes_before_external_sort=200000000,prefer_merge_sort_block_bytes=5000000
```
SELECT *
FROM test_order
ORDER BY val00 ASC
SETTINGS max_bytes_before_external_sort = 200000000, prefer_merge_sort_block_bytes = 5000000
FORMAT `Null`

Query id: 4f43e3b9-8f1a-4390-bace-f450dd0fb52b

Ok.

0 rows in set. Elapsed: 16.581 sec. Processed 12.00 million rows, 28.80 GB (723.77 thousand rows/s., 1.74 GB/s.)
Peak memory usage: 7.99 GiB.
```
a little slower, less memory usage

### Changelog category (leave one):
- Performance Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Add a new configuration`prefer_merge_sort_block_bytes` to control the memory usage and speed up sorting 2 times when merging when there are many columns.

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by robot-clickhouse-ci-2** [comment]
*This is an automated comment for commit cade316c95ca2c78d500b9ee3a475defc40f1d76 with description of existing statuses. It's updated for the latest CI running*

[❌ Click here](https://s3.amazonaws.com/clickhouse-test-reports/62904/cade316c95ca2c78d500b9ee3a475defc40f1d76/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>❌ failure</td></tr>
<tbody>
</table>

**Comment by liuneng1994** [comment]
@nickitat Hi.
Is there any good method or example to add performance test cases to this situation? It will only work when the number of columns is large and the amount of data is large (a certain number of temporary files can be generated), and new configuration items need to be applied.  Regular performance test cases have time limits, and historical versions will also run incorrectly because there is no corresponding configuration.

**Comment by liuneng1994** [comment]
image

**Comment by nickitat** [comment]
```
❯ cat output-89/external_sort_wide_table-err.log
Traceback (most recent call last):
  File "/workspace/right/scripts/perf.py", line 430, in <module>
    res = c.execute(
  File "/usr/local/lib/python3.10/dist-packages/clickhouse_driver/client.py", line 267, in execute
    rv = self.process_ordinary_query(
  File "/usr/local/lib/python3.10/dist-packages/clickhouse_driver/client.py", line 453, in process_ordinary_query
    return self.receive_result(with_column_types=with_column_types,
  File "/usr/local/lib/python3.10/dist-packages/clickhouse_driver/client.py", line 117, in receive_result
    return result.get_result()
  File "/usr/local/lib/python3.10/dist-packages/clickhouse_driver/result.py", line 50, in get_result
    for packet in self.packet_generator:
  File "/usr/local/lib/python3.10/dist-packages/clickhouse_driver/client.py", line 133, in packet_generator
    packet = self.receive_packet()
  File "/usr/local/lib/python3.10/dist-packages/clickhouse_driver/client.py", line 150, in receive_packet
    raise packet.exception
clickhouse_driver.errors.ServerException: Code: 159.
external_sort_wide_table.query0.run0: DB::Exception: Timeout exceeded: elapsed 15.02975745 seconds, maximum: 15. Stack trace:

0. ./build_docker/./src/Common/Exception.cpp:101: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000be55c08
1. DB::Exception::Exception(PreformattedMessage&&, int) @ 0x00000000078cf27c
2. ./contrib/llvm-project/libcxx/include/vector:434: DB::Exception::Exception<double, double>(int, FormatStringHelperImpl<std::type_identity<double>::type, std::type_identity<double>::type>, double&&, double&&) @ 0x000000000ed41ca8
3. ./build_docker/./src/QueryPipeline/ExecutionSpeedLimits.cpp:0: DB::ExecutionSpeedLimits::checkTimeLimit(Stopwatch const&, DB::OverflowMode) const @ 0x000000000ed41a6c
4. ./build_docker/./src/Processors/Executors/PipelineExecutor.cpp:198: DB::PipelineExecutor::finalizeExecution() @ 0x0000000010c06d40
5. ./build_docker/./src/Processors/Executors/PipelineExecutor.cpp:132: DB::PipelineExecutor::execute(unsigned long, bool) @ 0x0000000010c06ac8
6. ./build_docker/./src/Processors/Executors/PullingAsyncPipelineExecutor.cpp:0: void std::__function::__policy_invoker<void ()>::__call_impl<std::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'(), void ()>>(std::__function::__policy_storage const*) @ 0x0000000010c145dc
7. ./base/base/../base/wide_integer_impl.h:817: void* std::__thread_proxy[abi:v15000]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void ThreadPoolImpl<std::thread>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>>(void*) @ 0x000000000befa0e4
8. ? @ 0x000000000007d5c8
9. ? @ 0x00000000000e5edc

Test external_sort_wide_table failed with error code 1
```

**Comment by liuneng1994** [comment]
> lgtm
> 
> I suggest to just drop the perf test, because most likely it won't be stable anyway. so its value is questionable.



> lgtm
> 
> I suggest to just drop the perf test, because most likely it won't be stable anyway. so its value is questionable.

done

**Review by nickitat — APPROVED** [review]

**Pull request merged**
