### PR TITLE
Less backtracking in the parser

### PR DESCRIPTION
**Pull request by alexey-milovidov**
### Changelog category (leave one):
- Performance Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
The query parser now works faster for queries with a large number of nested SELECT subqueries in the case of syntax error.

### CODE REVIEW

**Comment by robot-ch-test-poll2** [comment]
*This is an automated comment for commit b41d64ed7ed6b090f43d29f54996bb8c2d3e50d6 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/61504/b41d64ed7ed6b090f43d29f54996bb8c2d3e50d6/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

**Comment by maxknv** [comment]
Dear @alexey-milovidov, this PR hasn't been updated for a while. Will you continue working on it? If not, please close it. Otherwise, ignore this message.

**Comment by alexey-milovidov** [comment]
I will try.

**Comment by alexey-milovidov** [comment]
Not possible.

SELECT subquery can be inside a Tuple or a parenthesized expression with operators:

```
select ((select 1) + 1);
select ((select 1), 2);
```

As long as we parse Tuple in a different way than operators and involve backtracking, we cannot put a greedy position after SELECT.

**Pull request closed without merging**
