### PR TITLE
Sessions and default database support in MySQL wire protocol

### PR DESCRIPTION
**Pull request by yurriy**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Category (leave one):
- Improvement

Short description (up to few sentences):
Creating a new session in each MySQL connection. Using default database from config.xml, if it is not specified by client. #5476

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]
Great! PS. Did you check (manually) that the user settings (e. g. `max_memory_usage` specified in `users.xml`) work?

**Comment by yurriy** [comment]
> Great! PS. Did you check (manually) that the user settings (e. g. `max_memory_usage` specified in `users.xml`) work?

No, the last thing to do from #5646 is implementing user settings. I was going to make them separately.

**Comment by alexey-milovidov** [comment]
If I remember correctly, `setUser` will be enough?

**Comment by yurriy** [comment]
> If I remember correctly, `setUser` will be enough?

Also replacing strings by PODArray, which uses MemoryTracker.

**Comment by nshah14285** [comment]
I have installed clickhouse 19.10.1.688 version. As per project requirement, I have to connect to clickhouse database from MYSQL client, so I tried below command

`mysql --protocol tcp -h localhost -P 9000 -u default --password -e "CREATE DATABASE x;"`

and

`mysql --protocol tcp -h localhost -P 9000 default -u default --password -e "CREATE DATABASE x;"`

and also tried to connect from node application but it gets hang and after some time receive below error 

> 653008 [ 41 ] {} <Error> ServerErrorHandler: Code: 209, e.displayText() = DB::NetException: Timeout exceeded while reading from socket (127.0.0.1:47000), Stack trace:

Could you please tell how to connect.


Thanks,
Nishit Shah

**Comment by yurriy** [comment]
> I have installed clickhouse 19.10.1.688 version. As per project requirement, I have to connect to clickhouse database from MYSQL client, so I tried below command
> 
> `mysql --protocol tcp -h localhost -P 9000 -u default --password -e "CREATE DATABASE x;"`
> 
> and
> 
> `mysql --protocol tcp -h localhost -P 9000 default -u default --password -e "CREATE DATABASE x;"`
> 
> and also tried to connect from node application but it gets hang and after some time receive below error
> 
> > 653008 [ 41 ] {}  ServerErrorHandler: Code: 209, e.displayText() = DB::NetException: Timeout exceeded while reading from socket (127.0.0.1:47000), Stack trace:
> 
> Could you please tell how to connect.
> 
> Thanks,
> Nishit Shah

Probably you are trying to connect to a native protocol server, which listens 9000 port by default. To be able to connect using mysql, you should add <mysql_port>9000</mysq_port> to [config.xml](https://github.com/yandex/ClickHouse/blob/master/dbms/programs/server/config.xml#L17).

**Comment by nshah14285** [comment]
After adding <mysql_port>9004</mysql_port> to config.xml getting below error

> 2019.06.20 10:36:49.893219 [ 37 ] {} <Error> ConfigReloader: Error loading config from '/etc/clickhouse-server/config.xml': Poco::Exception. Code: 1000, e.code() = 0, e.displayText() = SAXParseException: **Tag mismatch** in '/etc/clickhouse-server/config.xml', line 18 column 22 (version 19.10.1.688 (official build))

**Comment by nshah14285** [comment]
Thanks.
It's working now.

**Comment by nshah14285** [comment]
I am able to connect ClickHouse from mysql client but when I tried to connect from node application using [MYSQL](https://www.npmjs.com/package/mysql) module it throws an error

> max_packet_size: 0
character_set: !
user: default
auth_response length: 20
auth_response: ;t#3
                   �O1�cfk�Xkva�
database: test
auth_plugin_name: 
2019.06.20 13:32:35.000536 [ 41 ] {} <Error> MySQLHandler: DB::Exception: Required capability: CLIENT_PLUGIN_AUTH.


Thanks

**Comment by yurriy** [comment]
> I am able to connect ClickHouse from mysql client but when I tried to connect from node application using [MYSQL](https://www.npmjs.com/package/mysql) module it throws an error
> 
[MYSQL](https://www.npmjs.com/package/mysql) library does not support authentication plugins other than mysql_native_password, which makes it impossible to use it with ClickHouse now. We will add tests for this client when either [this](https://github.com/mysqljs/mysql/issues/1758) or [this](https://github.com/mysqljs/mysql/pull/2233) is merged.

**Pull request merged**
