### PR TITLE
ddlworker max entry metric

### PR DESCRIPTION
**Pull request by amosbird**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Export current max ddl entry executed by DDLWorker. It's useful to check if DDLWorker hangs somewhere.

Detailed description / Documentation draft:

None.

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
There is no test, but it's not necessarily for just one metric.

**Comment by amosbird** [comment]
> There is no test, but it's not necessarily for just one metric.

Tests should be added)

**Comment by amosbird** [comment]
@alesapin ... why would these simple `on cluster` statements time out?

**Comment by alexey-milovidov** [comment]
AFAIK Distributed DDL only work when every server has its own hostname.

**Comment by amosbird** [comment]
> AFAIK Distributed DDLs only work when every server has its own hostname.

But it works when I run fasttest docker image locally. It also works when running the test with hosted clickhouse.

**Comment by alexey-milovidov** [comment]
Anyway, you can exclude it from the fast test.

**Comment by amosbird** [comment]
Test failure seems unrelated.

**Pull request merged**
