### PR TITLE
external_aggregation_fix for big endian machines

### PR DESCRIPTION
**Pull request by saitama951**
The external aggregation test was failing on s390x because incorrect hashing in TwoTevelStringAggregation. 

Fix:
* make bit shifts according to endianess

### Changelog category (leave one):
Not For Changelog

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
* Fixed Functional Test  00284_external_aggregation

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
@saitama951, you need to add s390x to CI to speed up the processing of your pull requests.
See https://github.com/ClickHouse/ClickHouse/pull/31398 as an example.

**Comment by saitama951** [comment]
@alexey-milovidov The team is working on  the CI.

**Review by alexey-milovidov — APPROVED** [review]

**Comment by robot-ch-test-poll1** [comment]
This is an automated comment for commit f8787508ec4d0725cb915d66b947ac89a9029694 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/51280/f8787508ec4d0725cb915d66b947ac89a9029694/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Comment by saitama951** [comment]
@alexey-milovidov fixed the code style issues. I think it's good to merge now.

**Review by alexey-milovidov — APPROVED** [review]

**Pull request merged**
