### PR TITLE
tests: attempt to fix 02340_parts_refcnt_mergetree flakiness

### PR DESCRIPTION
**Pull request by azat**
I'm not sure that this was the case, but I don't see any other reasons for now.

I've also looked at the logs and trace_log, and did not noticed anything interesting.

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by robot-ch-test-poll3** [comment]
*This is an automated comment for commit 5a3b151cdfdba8615f031823ecafecbc3d8bc4d1 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/63684/5a3b151cdfdba8615f031823ecafecbc3d8bc4d1/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

**Comment by azat** [comment]
It was still flaky in - https://s3.amazonaws.com/clickhouse-test-reports/63684/5a3b151cdfdba8615f031823ecafecbc3d8bc4d1/stateless_tests_flaky_check__asan_.html

So I rewrote it:
- remove some rudiments (sleep is not executed for dry run anymore)
- make it works faster (1sec instead of 12)
- and added `system stop pulling replication log` in attempt to fix flakiness

**Comment by azat** [comment]
BTW I saw this in logs:

```
2024.05.13 10:54:28.089868 [ 1299 ] {} <Error> system.transactions_info_log_sender.DistributedInsertQueue.default: Code: 252. DB::Exception: Received from kng4alm55c.us-east-2.aws.clickhouse-staging.com:9440. DB::Exception: Too many parts (3001 with average size of 3.62 MiB) in table 'default.transactions_info_log_5852137309122097457 (3f98963d-4747-43f3-9c4b-d6a871c6de46)'. Merges are processing significantly slower than inserts. Stack trace:
```

Maybe you will want to tune your cluster for logs

**Comment by alesapin** [comment]
@azat isn't this test is terribly complex and unreliable by design? Maybe it make sense to convert to unit test? Maybe it's to remove it at all?

**Comment by azat** [comment]
> Isn't this test is terribly complex and unreliable by design?

Maybe

> Maybe it make sense to convert to unit test?

It is not that easy to write a unit test for MergeTree, but one day...

> Maybe it's to remove it at all?

I don't like this idea, since the problem was real and it was annoying (https://github.com/ClickHouse/ClickHouse/pull/37913/), yes, right now the pipeline is completely different, but still.

Anyway let's make at least this attempt.

**Pull request merged**
