### PR TITLE
Add positional read in libhdfs3

### PR DESCRIPTION
**Pull request by M1eyu2018**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Add positional pread in libhdfs3.
If you want to call positional read in libhdfs3, use the hdfsPread function in hdfs.h as follows.
`tSize hdfsPread(hdfsFS fs, hdfsFile file, void * buffer, tSize length, tOffset position);`

### CODE REVIEW

**Comment by M1eyu2018** [comment]
@alexey-milovidov, @tavplubix, Please review this PR for "positional read" feature in libhdfs3. Thank you very much.

**Comment by M1eyu2018** [comment]
@tavplubix This workflow requires approval from a maintainer. Can you help me?

**Comment by tavplubix** [comment]
@M1eyu2018, see the comment from [clickhouse-ci](https://github.com/apps/clickhouse-ci) bot.
It's already approved, CI doesn't start due to incorrect PR description

**Comment by M1eyu2018** [comment]
@tavplubix I have modified PR description. Is it correct? And how to make CI rerun again?

**Comment by alexey-milovidov** [comment]
@M1eyu2018, why closing?

**Comment by M1eyu2018** [comment]
@alexey-milovidov 
I fixed a bug in the latest libhdfs3 PR https://github.com/ClickHouse/libhdfs3/pull/57
I want to rerun this PR again after the latest libhdfs3 PR is merged.
Please review the latest libhdfs3 PR as soon as possible.

**Comment by M1eyu2018** [comment]
@alexey-milovidov，this PR is OK? There're some failing checks. which checks need to fix?

**Comment by alexey-milovidov** [comment]
@M1eyu2018, it is a problem with Docker: https://github.com/moby/moby/pull/46762
We fixed it. Please update with master.

**Comment by alexey-milovidov** [comment]
Please change from "New Feature" to something else, e.g. Improvement or Not For Changelog.
It does not let to merge it as a "New Feature" without the documentation about user-facing changes.

**Comment by M1eyu2018** [comment]
@alexey-milovidov 
The CI run has stopped? How to solve it? I have updated master.

**Comment by alexey-milovidov** [comment]
The Fast Test has failed.

**Comment by M1eyu2018** [comment]
@alexey-milovidov
The CI run is OK this time？

**Comment by M1eyu2018** [comment]
@tavplubix hi, can you review this PR?

**Comment by tavplubix** [comment]
> If you want to call positional read in libhdfs3, use the hdfsPread function in hdfs.h as follows.
> tSize hdfsPread(hdfsFS fs, hdfsFile file, void * buffer, tSize length, tOffset position);

@M1eyu2018, but we do not call it like this in ClickHouse, so this change is basically useless. Also:
 - it's not covered by tests
 - the changelog entry is not user-readable

**Comment by M1eyu2018** [comment]
> > If you want to call positional read in libhdfs3, use the hdfsPread function in hdfs.h as follows.
> > tSize hdfsPread(hdfsFS fs, hdfsFile file, void * buffer, tSize length, tOffset position);
> 
> @M1eyu2018, but we do not call it like this in ClickHouse, so this change is basically useless. Also:
> 
> * it's not covered by tests
> * the changelog entry is not user-readable
@tavplubix How to make the changelog entry user-readable?

**Pull request merged**
