### PR TITLE
Fix Merge table engine with FINAL and PREWHERE

### LINKED ISSUE #35307: Using Merge table engine and FINAL, columns specified in PREWHERE clause and not specified in SELECT section produces error
**Describe the unexpected behavior**
When using MaterializedMySQL database engine and Merge table engine, columns specified in `WHERE` clause and not specified in `SELECT` section produces error:
```
Code: 10. DB::Exception: Received from localhost:9000. DB::Exception: Not found column column2 in block. (NOT_FOUND_COLUMN_IN_BLOCK)
```

**How to reproduce**

versions:
MySQL: Ver 8.0.28 for Linux on x86_64 (MySQL Community Server - GPL)
ClickHouse: ClickHouse server version 22.2.2.1

In MySQL:
```
create database db4;

CREATE TABLE db4.table_1 (
    id INT,
    column1 VARCHAR(10),
    column2 VARCHAR(10),
	PRIMARY KEY (`id`),
	KEY `table_1_column2_index` (`column2`)
) ENGINE = InnoDB;

insert into db4.table_1 
(id, column1,column2) 
VALUES 
(1, 'abc', 'def');


CREATE TABLE db4.table_2 (
    id INT,
    column1 VARCHAR(10),
    column2 VARCHAR(10),
	PRIMARY KEY (`id`),
	KEY `table_2_column2_index` (`column2`)
) ENGINE = InnoDB;

insert into db4.table_2 
(id, column1, column2) 
VALUES 
(2, 'uvw','xyz');
```

In ClickHouse:
```
set allow_experimental_database_materialized_mysql = 1;
CREATE DATABASE db4_mysql ENGINE = MaterializedMySQL('192.168.1.248:3306', 'db4', 'clickhouse_user', 'ClickHouse_123');

create database db5_merge;

CREATE TABLE db5_merge.merge_table
 as db4_mysql.table_1
     ENGINE = Merge('db4_mysql', '^table_\\d+$');
```

**Expected behavior**
query should be able to be executed with a different column specified than what is in `WHERE` clause:
```
ch_env_2 :) select column1 from db5_merge.merge_table where column2 = 'def';

SELECT column1
FROM db5_merge.merge_table
WHERE column2 = 'def'

Query id: 72c41db0-9006-4200-bbbb-d626aa1a9d9b

┌─column1─┐
│ abc     │
└─────────┘

1 rows in set. Elapsed: 0.038 sec.
```

**Error message and/or stacktrace**
```
ch_env_2 :) select column1 from db5_merge.merge_table where column2 = 'def';

SELECT column1
FROM db5_merge.merge_table
WHERE column2 = 'def'

Query id: f93bb8d4-8586-4b4f-8b6d-e1c2bc04b114


0 rows in set. Elapsed: 0.011 sec.

Received exception from server (version 22.2.2):
Code: 10. DB::Exception: Received from localhost:9000. DB::Exception: Not found column column2 in block. (NOT_FOUND_COLUMN_IN_BLOCK)
```

**Additional context**
Found the current behavior and workarounds:
1.  add the column that you would like to use in the where clause to the `SELECT` portion if the query.
2. remove the index key from the column you'd like to use in the `WHERE` portion of the query.

thanks.

### PR DESCRIPTION
**Pull request by canhld94**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in official stable or prestable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
- Fix following issues:
  - When underlying table doesn't support FINAL, selecting from Merge table engine should throw exception.
  - Using Merge table engine and FINAL, columns specified in PREWHERE clause and not specified in SELECT section produces error #35307.

Close #35307 

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by serxa** [comment]
Style check complains about `ErrorCodes::SAMPLING_NOT_SUPPORTED is defined but not used in file /ClickHouse/src/Storages/StorageMerge.cpp`

**Comment by canhld94** [comment]
> Style check complains about `ErrorCodes::SAMPLING_NOT_SUPPORTED is defined but not used in file /ClickHouse/src/Storages/StorageMerge.cpp`

I will fix it tomorrow. If we use `InterpreterSelectQuery`, no need to explicitly check if storage support sampling here anymore.

**Comment by canhld94** [comment]
@serxa More context about this PR: in current implementation, depending on the storage engine, we directly invoke `IStorage::read` or use `InterpreterSelectQuery` to build the query plan. It has lead to some issues before (e.g. Merge Table Engine does not use the indexes of tables. #40014) as well as some issues I listed above. Considering that we have some important logic and optimization in `InterpreterSelectQuery`, I think we can unify all branch to only use `InterpreterSelectQuery`. This way we can remove all storage engine check, as it will be done in `InterpreterSelectQuery`.

**Comment by canhld94** [comment]
Not simple as I though...

**Comment by serxa** [comment]
Yes, looks like there are more things to deal with (00717_merge_and_distributed test):
```
2022-11-01 13:40:34 Code: 49. DB::Exception: Received from localhost:9000. DB::Exception: Block structure mismatch in Merge Storage: different types:
2022-11-01 13:40:34 date Date UInt16(size = 0), value UInt64 UInt64(size = 0)
2022-11-01 13:40:34 date Date UInt16(size = 0), value Int64 Int64(size = 0). (LOGICAL_ERROR)
2022-11-01 13:40:34 (query: SELECT * FROM merge(currentDatabase(), 'test_s64_distributed|test_u64_distributed') WHERE value = 1;)
```

**Comment by alexey-milovidov** [comment]
@cangyin Please reopen or create a new PR when it is ready.

**Pull request closed without merging**
