### PR TITLE
Backport #46282 to 22.3: Allow vertical merges from compact to wide parts [2]

### PR DESCRIPTION
**Pull request by robot-ch-test-poll3**
Original pull-request #46282
Cherry-pick pull-request #46341

This pull-request is a last step of an automated backporting.
Treat it as a standard pull-request: look at the checks and resolve conflicts.
Merge it only if you intend to backport changes to the target branch, otherwise just     close it.

### CODE REVIEW

**Comment by tavplubix** [comment]
@KochetovNicolai, it has broken integration tests in 22.3

**Comment by alexey-milovidov** [comment]
Why do we backport "performance improvement"?

**Comment by tavplubix** [comment]
> Why do we backport "performance improvement"?

Because it's okay to backport everything that we want to, see https://github.com/ClickHouse/ClickHouse/pull/45883#issuecomment-1413894820

**Comment by alexey-milovidov** [comment]
We should want to backport as little as possible.

**Pull request merged**
