### PR TITLE
Fix race in `GraceHashJoin`

### LINKED ISSUE #72175: Grace hash join wrong results with `max_joined_block_size_rows`
See failures of `02275_full_sort_join_long` in the [CI](https://play.clickhouse.com/play?user=play#CldJVEgKICAgIGZhbHNlIGFzIG9ubHlfbWFzdGVyClNFTEVDVCAqCkZST00gKApTRUxFQ1QKICAgIHB1bGxfcmVxdWVzdF9udW1iZXIgYXMgcHJudW0sCiAgICBzdWJzdHIoY29tbWl0X3NoYSwgMSw5KSBhcyBzaGEsCiAgICByb3VuZCh0ZXN0X2R1cmF0aW9uX21zIC8gMTAwMCwgMikgYXMgZHVyLAogICAgY2hlY2tfc3RhcnRfdGltZSwKICAgIGZvcm1hdFJlYWRhYmxlVGltZURlbHRhKGludERpdihub3coKSAtIGNoZWNrX3N0YXJ0X3RpbWUsIDM2MDApICogMzYwMCkgYXMgYWdvLAogICAgY2hlY2tfbmFtZSwKICAgIHRlc3RfbmFtZSwKICAgIHJlcG9ydF91cmwKRlJPTSBjaGVja3MKV0hFUkUgMQogICAgQU5EIGNoZWNrX3N0YXJ0X3RpbWUgPj0gbm93KCkgLSBJTlRFUlZBTCA3IERBWQogICAgQU5EIChwdWxsX3JlcXVlc3RfbnVtYmVyID0gMCBPUiBub3Qgb25seV9tYXN0ZXIpCiAgICBBTkQgdGVzdF9zdGF0dXMgIT0gJ1NLSVBQRUQnCiAgICBBTkQgdGVzdF9zdGF0dXMgTElLRSAnRiUnCiAgICBBTkQgY2hlY2tfc3RhdHVzICE9ICdzdWNjZXNzJwopCldIRVJFIHRlc3RfbmFtZSBsaWtlICclMDIyNzVfZnVsbF9zb3J0X2pvaW5fbG9uZyUnCk9SREVSIEJZIGNoZWNrX3N0YXJ0X3RpbWUgREVTQywgY2hlY2tfbmFtZSwgdGVzdF9uYW1l)

Small repro:

```SQL
#!/usr/bin/env -S ${HOME}/clickhouse-client --queries-file

DROP TABLE IF EXISTS t0;
DROP TABLE IF EXISTS t1;

CREATE TABLE t0 (x UInt64) ENGINE = MergeTree ORDER BY x;
INSERT INTO t0 SELECT number from numbers(20);

CREATE TABLE t1 (x UInt64) ENGINE = MergeTree ORDER BY x;
INSERT INTO t1 SELECT number from numbers(5, 20);

SET max_joined_block_size_rows = 1;
SET grace_hash_join_initial_buckets = 2;
SET join_algorithm = 'grace_hash';

SELECT sum(x), count() FROM t0 JOIN t1 USING x;

```

### PR DESCRIPTION
**Pull request by nickitat**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fixed data race in `GraceHashJoin` as the result of which some rows might be missing in the join output.

Fixes: #72175

Close #72224

### CODE REVIEW

**Comment by robot-ch-test-poll4** [comment]
*This is an automated comment for commit d0078186b3b87a3cb21e8a60a624820e631e362e with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/72233/d0078186b3b87a3cb21e8a60a624820e631e362e/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/288edbf35ad6daed9eed26901a5625689fb32680/docs_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Comment by alexey-milovidov** [comment]
Add a test that could potentially, at least sometimes, reproduce the error.
Change the category and write a changelog entry.

**Comment by vdimir** [comment]
> Add a test that could potentially, at least sometimes, reproduce the error. Change the category and write a changelog entry.

We have test for the case issue found by `02275_full_sort_join_long`. It reproduces not too often because `grace_hash_join_initial_buckets` is not randomized, I'm fixing it in https://github.com/ClickHouse/ClickHouse/pull/72178

As for change-log entry, it's a bug introduced in unreleased version

**Review by vdimir — APPROVED** [review]

**Comment by nickitat** [comment]
> > Add a test that could potentially, at least sometimes, reproduce the error. Change the category and write a changelog entry.
> 
> We have test for the case issue found by `02275_full_sort_join_long`. It reproduces not too often because `grace_hash_join_initial_buckets` is not randomized, I'm fixing it in #72178
> 
> As for change-log entry, it's a bug introduced in unreleased version

I've added your repro from #72175 as a test.

**Comment by nickitat** [comment]
`Stress test (debug) - #72125

**Pull request merged**
