### PR TITLE
Enable CodeQL security scanner

### PR DESCRIPTION
**Pull request by blinkov**
Changelog category (leave one):
- Build/Testing/Packaging Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Daily check by [GitHub CodeQL](https://securitylab.github.com/tools/codeql) security analysis tool that looks for [CWE](https://cwe.mitre.org/). 

Detailed description / Documentation draft:
On ClickHouse fork found 175 instances of 7 different [CWE](https://cwe.mitre.org/) (including `contrib`). Takes 10+ hours, so can't be run frequently.

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
> On ClickHouse fork found 175 instances of 7 different CWE (including contrib).

Could you please post a list of them here?

**Comment by blinkov** [comment]
@alexey-milovidov no, security issues are not supposed to be published before fixes.

**Comment by alexey-milovidov** [comment]
@blinkov You can publish all of them here without any worries.

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
@blinkov If it is not possible to disable scanning of subdirectories (contrib), you should create an issue in the repository of "CodeQL security scanner" with a link to this PR.

**Comment by alexey-milovidov** [comment]
Screenshot_20200705_011740

**Comment by alexey-milovidov** [comment]
CodeQL is useful, one bug has been found: #12138

**Pull request merged**
