### PR TITLE
Implement HasAll specialization for SSE and AVX2

### PR DESCRIPTION
**Pull request by youennL-cs**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

_Changelog category_:
- Improvement

_Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md)_:
As talked in [issue 27025](https://github.com/ClickHouse/ClickHouse/issues/27025), there is an improvement of the HasAll function using SIMD instruction (SSE and AVX2).
Gtest tests have also been added.

_Detailed description / Documentation draft_:
It still require some discussion, mainly about copy/paste code. Should I continue to copy paste (int and unsigned int are strictly identical but cast is impossible)
Second thing to discuss is I fail to execute with AVX2. I follow what exist, it compiles and all but doesn't execute on my machine even if I can run AVX2 instructions. I missed something but I don't know what.

### CODE REVIEW

**Comment by kitaisreal** [comment]
@youennL-cs could you please add some performance test to show difference ?

**Comment by youennL-cs** [comment]
We already show some performances improvement in the [issue 27025](https://github.com/ClickHouse/ClickHouse/issues/27025). 
As the function was extracted to benchmark the performance of this particular feature, I understand that could you want more. That's why we are working on adding performance tests inside Clickhouse.

**Comment by youennL-cs** [comment]
@kitaisreal Update
four performance tests have been added : tests/performance/hasAll_simd_int{8,16,32,64}.xml
Can you please take a look.

P.S: I don't know why  the push to dockerhub failed and we cannot access to the details.

**Comment by youennL-cs** [comment]
Hi @kitaisreal,
Is it possible to have help to fix the Ci pipeline ?
It always fails during stateless tests raising an 'Illegal Operand'.
These tests seams passed when I disabled AVX2 (only sse4.2 remained).

I suspect the machine which run the tests not having AVX2 available and raising an 'illegal operand' while the binary has been generated with  the "-mavx2" option.

Maybe the option is wrongly propagated/passed at the compile/link time. 
Can you tell me if I have done something wrong in the CmakeList ?
Thanks

**Comment by youennL-cs** [comment]
**update**
Hi @kitaisreal,
we still need help to review the code and fix the pipeline. 
Can you help us, please ?

**Comment by kitaisreal** [comment]
@Mergifyio update

**Comment by youennL-cs** [comment]
Hello @kitaisreal, 
Two things: 
The first thing is that Mergify tool "needs the author permission to update the base branch of the pull request." However, even if I'l administrator of the fork, I'm not the creator and I haven't any visible check box to authorize Mergify as he would like. So, I update/rebase the branch myself. It should now be synchronised with the last commit of master.
The second thing is that, apparently, I lost the "can be tested" label, and tests are not executed at all. Can you do something please ?

**Comment by youennL-cs** [comment]
Hi, 
in order to help any people that would want to understand/review this PR that is not aware Intel SIMD programation and for posterity there is a complete explanation with an example of the version SSE4.2 with int32. 

First, let's start by the basics. For the records, what we're explaining here is for Intel CPUs and may not be fully valid for ARM/AMD CPUs.
[Here](https://www.intel.com/content/www/us/en/docs/intrinsics-guide/index.html) you can find a documentation on all functions that I could badly explain; if you want to understand it better or use it for your own project.
All functions have the same structure: _mm(256/512)_<op>_<dataType>
start with **_mm**, if register are bigger you will add 256 or 512 to indicate that you're using 256b/523b register.
Then **_<your op>_**, 
and finish with the data type: **_{ps, pd, epi{8,16,32,64}, etc}** .

As you may know your data can be set at different level of your memory (Disk, RAM, L3, L2, L1). The deeper you go the more data you can fit but the more expensive it is. In contrary, the closer you're to the CPU the faster it is.
In addition of these level, you also have something even closer to the CPU, registers. 
These registers are very limited, in term of number and size. 
According to your CPU, registers have different size from 128b to 512b. 
These registers are able to execute a Single Instruction on Multiple Data (SIMD). 
Intel implement functions to manipulate them named, SSE (Streaming SIMD Extension), and that's what I will present today. But also, Advance Vector eXtension (AVX) to manipulate 256b and 512b vectors. My example is based on SSE4.2 with register of 128b. Since we have 128b and we are working with int (32b) we can load 4 elements by register. When we are working with int16 we can load 8 elements, etc. 


As example I'm using  the [SSE4.2 version for int32](https://github.com/ClickHouse/ClickHouse/pull/27653/files#diff-10793e519015aff12d5f627bf79ab9ce79d1bbde16d694f983c974b0b5b23410R477) (so 4 element by register)
and there is the algo:
for j in second:
  secReg = load unaligned 4 elements (since we are not sure to have aligned arrays)
  SBM = create the bitmask (SDB second_bitmak) from the nullmap
  for i in first :
    firstReg = load unaligned 4 elements (since we are not sure to have aligned arrays)
    FBM = create the bitmask (FDB first_bitmak) from the nullmap
    nextVersionOfFBM = 
 8. OR(
 7.  OR(
 5.     OR(
 1.      ANDNOT(SBM, cmpe(i, j)) // ANDNOT : A and (not B)) / cmpe compare equality return 0xF if element is equal (element by element),
 2.      ANDNOT(shuffle(SBM, 1), cmpe(i, shuffle(j, 1))) // shuffle swap element here by one element so [3,2,1,0] become [2,1,0,3]
       )
 6.    OR ( 
 3.     ANDNOT(shuffle(SBM, 2), cmpe(i, shuffle(j, 3))) // shuffle do [3,2,1,0] become [1,0,3,2]
 4.     ANDNOT(shuffle(SBM, 3), cmpe(i, shuffle(j, 3))) // shuffle do [3,2,1,0] become [0,3,2,1]
       )
    ),
    FBM
  )
  
  Let's take first = [1,2,3,N] ; second = [1, 6, N, 8, 3, 2, 1, 4]; where N correspond to a null element in the null map and F = 0xFFFF (full of ones)
  So we have 4 registers: 
  secReg = [N, 3, 2, 1].     firstReg = [8, N, 6, 1]
  SBM = [F, 0, 0, 0].      FBM = [0, 0, F, 0]
  
1.  cmpe([8,N,6,1], [N,3,2,1]) = [0,0,0,F]                        ANDNOT([0,F,0,0]) = [0,0,0,F] // such as even there is a 3 behind the N of the second array, the bitmask mask it and filter this element)
2. cmpe([N,6,1,8], [N,3,2,1]) = [0,0,0,0] /*shuffle-1*/  ANDNOT([F,0,0,0]) = [0,0,0,0]
5. OR ([0,0,0,F], [0,0,0,0]) = [0,0,0,F]
3. cmpe([6,1,8,N], [N,3,2,1]) = [0,0,0,0] /*shuffle-2*/  ANDNOT([0,0,0,F]) = [0,0,0,0]
4. cmpe([1,8,N,6], [N,3,2,1]) = [0,0,0,0] /*shuffle-3*/  ANDNOT([0,0,F,0]) = [0,0,0,0]
6. OR ([0,0,0,0], [0,0,0,0]) = [0,0,0,0]
7. OR ([0,0,0,F], [0,0,0,0]) = [0,0,0,F]
8. OR ([0,0,0,F], [F,0,0,0]) = [F, 0, 0, F] // OR between compute and previous SBM
.
-- Step 2 : firstReg = [4, 1, 2, 3] FBM = [0, 0, 0, 0]
1.  cmpe([4,1,2,3], [N,3,2,1]) = [0,0,F,0]                        ANDNOT([0,0,0,0]) = [0,0,F,0]
2. cmpe([1,2,3,4], [N,3,2,1]) = [0,0,0,0] /*shuffle-1*/  ANDNOT([0,0,0,0]) = [0,0,0,0]
5. OR ([0,0,F,0], [0,0,0,0]) = [0,0,F,0]
3. cmpe([2,3,4,1], [N,3,2,1]) = [0,F,0,F] /*shuffle-2*/  ANDNOT([0,0,0,0]) = [0,F,0,F]
4. cmpe([3,4,1,2], [N,3,2,1]) = [0,0,0,0] /*shuffle-3*/  ANDNOT([0,0,0,0]) = [0,0,0,0]
6. OR ([0,0,F,0], [0,0,0,0]) = [0,0,F,0]
7. OR ([0,F,0,F], [0,0,F,0]) = [0,F,F,F]
8. OR ([0,F,F,F], [F, 0, 0, F]) = [F, F, F, F] // OR between compute and previous SBM
SBM is full of ones for each element so all elements have been found we can stop. 
-- END EXAMPLE

Remaining loops are added for first and second loops to do what's remains because not all arrays can be divided by 4.
Hope this example help anyone who was not aware of this PR. 
We choose to compact all function otherwise the compile mess up the assembly code generated and it become slower.

Same idea is applied for int8, int16, int64 and for AVX (256b by register).
That's why it seems to be a very big code to review but you need to only understand one version to get the other ones.
Hope that explanation was useful for at least someone, otherwise it's just for the posterity :)

**Comment by youennL-cs** [comment]
UP

**Comment by kitaisreal** [comment]
@youennL-cs need to rebase with master to fix conflicts.

**Comment by kitaisreal** [comment]
@Mergifyio update

**Comment by kitaisreal** [comment]
@youennL-cs can similar optimization be implemented for AVX256 ?

**Comment by youennL-cs** [comment]
> @youennL-cs can similar optimization be implemented for AVX256 ?

It's already the case, you can look from L130 in [src/Functions/GatherUtils/sliceHasImplAnyAll.h](https://github.com/ClickHouse/ClickHouse/pull/27653/files#diff-10793e519015aff12d5f627bf79ab9ce79d1bbde16d694f983c974b0b5b23410R130https://github.com/ClickHouse/ClickHouse/pull/27653/files#diff-10793e519015aff12d5f627bf79ab9ce79d1bbde16d694f983c974b0b5b23410R130)
I use SSE4.2 in my example because it simply the example and reduce the number of lines but I implemented both.

If you mean AXV512, yes it could. 
At the beginning we estimated that we should start by implementing SSE4.2 and AVX2 only for now and maybe AVX512 later, due to the number of lines for the PR.

Same For now it only handle int but we would like also manage unsigned afterward (or in this PR, since functions will not change).

**Comment by kitaisreal** [comment]
@youennL-cs could you add implementation for all integer types Int8, Int16, Int32, Int64, UInt8, UInt16, UInt32, UInt64, and also for AVX256, AVX512. I actually check that we have such infrastructure for dynamic dispatch, so I will help with integrating it into our code base, so CI will check code.

**Comment by youennL-cs** [comment]
First, ok, so I added UInt in addition of Int (8, 16, 32, 64), in an ugly way (copy paste since functions are exactly the same, we compare bits so doesn't matter how they're composed while they're composed in the same way). 
I do that because cast seems not authorized in the code - crash at compile time due to a compilation flag.
Should I let it as it is or do you have a better idea ? 

Second, since the API for AVX512 is a little bit different from SSE and AVX256; I would propose to raise a second PR on it when this one will be accepted. It will take me a little bit of time to adapt the code/algo with avx512 functions. 
For now, machines with AVX512 will still benefit from AVX256; so it's still a win for everyone.

**Comment by youennL-cs** [comment]
Hello @kitaisreal, 
I confirm that the AVX512 version is more complicated since API functions change their signatures it becomes way harder to implement the same thing and currently I don't see way to do to continue to scale performances compare to SSE and AVX2.
As I said, AVX512 machine still take advantage of what is done for SSE4.2 and AVX2. 
So, I will propose to keep this PR as it is - managing Int and UInt from 8 to 64bits for SSE4.2 and AVX2.
Could you now help me to integrate it to your code base and to make the dynamic dispatch on your infrastructure ? 
Thanks in advance.

**Comment by kitaisreal** [comment]
@youennL-cs sure, will merge it into temporary branch, apply dynamic dispatch and merge into master.

**Comment by youennL-cs** [comment]
Thanks.
Don't forget that there is an option in the CMakeList: `option(ENABLE_AVX2 ... OFF)` which disable AVX2 by default (as advice in one of your [previous message](https://github.com/ClickHouse/ClickHouse/pull/27653#issuecomment-949539939). 
Does it impact the dynamic dispatch ? should I remove it or change anything else somewhere else ?

**Comment by kitaisreal** [comment]
@youennL-cs it okay, compiler can enable AVX2, AVX512 for some specific function, without enabling it in CMakeLists.

**Comment by youennL-cs** [comment]
Ok but the code expect a macro to be define (defined in the CMakeList when enable)
Example: https://github.com/ClickHouse/ClickHouse/pull/27653/files#diff-10793e519015aff12d5f627bf79ab9ce79d1bbde16d694f983c974b0b5b23410R130 which expect `ENABLE_AVX2` to be ON to compile the code.
AVX2 version is only running when `__AVX2__` and `ENABLE_AVX2` are ON. The first one is enable by the compiler, but it was the problem initially that's why I added the second one which must be enabled at compile time.

**Comment by youennL-cs** [comment]
Hi @kitaisreal , 
I'm coming back to know the status of the process; and if I need to do anything about enabling SSE and or AVX2 and or more.  (due to the cmake option option(ENABLE_AVX2 ... OFF)) as explained in my previous message. 

Moreover I'm not sure about one of your previous [message](https://github.com/ClickHouse/ClickHouse/pull/27653#issuecomment-1029888426); do you will do that, or should I do it somehow ?

**Comment by kitaisreal** [comment]
@youennL-cs I will do that. No additional actions are required from your side. I see performance improvements, now we just need to wrap it in our dynamic dispatch infrastructure.

**Comment by youennL-cs** [comment]
Great :) thanks for the information !

**Comment by kitaisreal** [comment]
Merging in temporary branch, then will merge in master.

**Pull request merged**
