### PR TITLE
Histogram function did not work correctly when called for Distributed table

### PR DESCRIPTION
**Pull request by olegkv**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

For changelog. 
Category (leave one):
- Bug Fix

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
Can you provide a test with
```
SELECT ... FROM remote('127.0.0.{1,2}')
```
?

`remote('127.0.0.{1,2}')` is to make a distributed query with single server.

**Review by alexey-milovidov — APPROVED** [review]

**Comment by olegkv** [comment]
@alexey-milovidov
I am not sure how to make remote('127.0.0.{1,2}') merge two different result sets - it merges queries from same table.
So, I created test table with engine=memory and added two different insert queries, one for 127.0.0.1, other for 127.0.0.2. After that, it is easy to make remote() merge two different histograms.

**Comment by alexey-milovidov** [comment]
> I am not sure how to make remote('127.0.0.{1,2}') merge two different result sets - it merges queries from same table.

It is possible with `randConstant` function. It will give you a constant expression that is random for each remote query. It's a little bit tricky. There are a few examples in tests...

> So, I created test table with engine=memory and added two different insert queries, one for 127.0.0.1, other for 127.0.0.2. After that, it is easy to make remote() merge two different histograms.

It is almost what we need, but I don't see how it is supposed to work: both remote queries will process full content of test table. Does the test fail before the fix?

**Comment by olegkv** [comment]
> It is possible with `randConstant` function. It will give you a constant expression that is random for each remote query. It's a little bit tricky. There are a few examples in tests...

I tried to use rand() but the problem is that I don't know what rand generates in each of two cases,
and, as a result, I would not know what numbers to write to .reference file. As a result, I thought it would be more clear to hard code all numbers.

> It is almost what we need, but I don't see how it is supposed to work: both remote queries will process full content of test table. Does the test fail before the fix?

Yes, currently, last row is 117 **99** 92, not 117 199 92. 
To reproduce the bug, you should run query in such way that it first runs on node where upper_bound it larger and then result is merged with smaller upper_bound. 
If you run it first on node where upper_bound is smaller, bug will not appear.
That's why I made two queries one for {127.0.0.{1,2}} and other for 127.0.0.{2,1} to make sure merges happen in both orders and bug (if exists) is visible anyway.

**Comment by alexey-milovidov** [comment]
`histogram` function is non-deterministic when data is processed in random order (in multiple threads). And the test is incorrect.

**Comment by alexey-milovidov** [comment]
`merge` function can be tested without distributed queries.

**Comment by olegkv** [comment]
-histogram function may be non deterministic, but its upper bound is deterministic and this is where the bug was.
-I've changed the test to check upper-bound only, I don't know how to test merge without running distributed query..

**Comment by olegkv** [comment]
I guess even if the test checks upper bound only, it can still give false positive results, if order of execution is favorable (smaller upper_bound first, then merge with larger upper_bound).

**Comment by alexey-milovidov** [comment]
Merged. I also has changed a test to force specific order of merging.

**Pull request merged**
