### PR TITLE
Integration tests: fix ports clashing problem

### PR DESCRIPTION
**Pull request by fm4v**
`get_free_port`, which is called in `ClickHouseInstance` to obtain ports for docker containers, could return the same port because it is not bound instantly. Port conflicts can occur between pytest-xdist workers and even in a single thread. Fix this by:
- Allocate a pool of 50 free unique ports to each pytest-xdist worker
- In each process, sequentially allocate these ports from the pool

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
...

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [x]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Do not test
- [x]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-ch-test-poll2** [comment]
*This is an automated comment for commit a64e625f0ba20751f929222bd49aaf1295ff15ed with description of existing statuses. It's updated for the latest CI running*

[❌ Click here](https://s3.amazonaws.com/clickhouse-test-reports/67672/a64e625f0ba20751f929222bd49aaf1295ff15ed/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Style check</td><td>Runs a set of checks to keep the code style clean. If some of tests failed, see the related log from the report</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/67672/a64e625f0ba20751f929222bd49aaf1295ff15ed/style_check.html">❌ failure</a></td></tr>
<tbody>
</table>

**Comment by azat** [comment]
@fm4v maybe you will be interested in fixing this problem completely, something like this https://github.com/ClickHouse/ClickHouse/pull/53266 ?

**Comment by Avogar** [comment]
> something like this https://github.com/ClickHouse/ClickHouse/pull/53266 ?

Maybe I am wrong, but we cannot avoid specifying host port for kafka because of `KAFKA_ADVERTISED_LISTENERS`:
https://github.com/ClickHouse/ClickHouse/blob/3a7842ce05c2f20d907f8c7ac79906ff34121717/tests/integration/compose/docker_compose_kafka.yml#L22

At least, I couldn't understand how we can do it

**Comment by azat** [comment]
Why can't we simply use `kafka:9092`? And I'm not sure how it works right now, but maybe kafka will require own network to avoid overlaps in this case

Another idea is to create kafka not for each test, but globally

**Pull request merged**
