### PR TITLE
ISSUES-4006 support decimal data type for MaterializedMySQL

### LINKED ISSUE #14157: DB::Exception: Unsupported type Decimal(13, 4) when using MaterializeMySQL
It seems MaterializeMySQL doesn't support Decimal data type when doing replication.

### PR DESCRIPTION
**Pull request by zhang2014**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- New Feature

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Support decimal data type for MaterializedMySQL

#4006 fixes #14157

### CODE REVIEW

**Comment by dengc367** [comment]
Who can review this issue, I need this issue to test the MaterializeMySQL. @4ertus2

**Comment by zhang2014** [comment]
> Integration tests (release) — fail: 1, passed: 814, error: 0
> Performance — Errors while building the report.

test failure unrelated this pr.

**Comment by zhang2014** [comment]
`AST fuzzer — Assertion `(n >= (static_cast<ssize_t>(pad_left_) ? -1 : 0)) && (n <= static_cast<ssize_t>(this->size()))' failed`

test failure unrelated this pr.

**Comment by tavplubix** [comment]
`Yandex third-party checks` - unrelated (broken in master)

**Review by tavplubix — APPROVED** [review]

**Comment by tavplubix** [comment]
Maybe change changelog category to "Improvement" or "New feature"? The entry "Support decimal data type for MaterializedMySQL" doesn't look like a bugfix.

**Comment by zhang2014** [comment]
> Maybe change changelog category to "Improvement" or "New feature"? The entry "Support decimal data type for MaterializedMySQL" doesn't look like a bugfix.

Done.

**Pull request merged**
