### PR TITLE
Inline gather utils

### PR DESCRIPTION
**Pull request by KochetovNicolai**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Try to shrink binary a little bit

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
Anonymous namespace - :+1: 
About inlining - didn't get the reasoning why it will help.

**Comment by alexey-milovidov** [comment]
Both inlining + anonymous namespace - to lower the size of symbol table and debug info?

**Comment by KochetovNicolai** [comment]
> Both inlining + anonymous namespace - to lower the size of symbol table and debug info?

Yes. With inlining some function names are removed from debug info.

In total it saves just ~100M for my local build, however.

**Comment by azat** [comment]
It will be interesting to see will it helps to reduce build time for gcc10, or the problem wasn't with the amount of debug symbols.

**Comment by KochetovNicolai** [comment]
Inlining slowed build time of `GatherUtils` up to 2 times. I've reverted it.

**Comment by KochetovNicolai** [comment]
Not waiting for other tests.

**Pull request merged**
