### PR TITLE
Make tests with window view less bad

### PR DESCRIPTION
**Pull request by tavplubix**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Review by kssenii — APPROVED** [review]

**Review by alexey-milovidov — APPROVED** [review]

**Comment by tavplubix** [comment]
Stateless tests flaky check (asan) - tests are still flaky, but at least they do timeout not

@kssenii, should we try to apply [this](https://github.com/ClickHouse/ClickHouse/commit/f3958819e1e2675ac6077fabd8c8331b8f3e4c89) fix to all tests?

**Comment by tavplubix** [comment]
01054_window_view_proc_tumble_to is still flaky :(

**Comment by kssenii** [comment]
> Stateless tests flaky check (asan) — fail: 0

yay

> Integration tests (tsan) [4/6] — fail: 1

test_s3_cluster/test.py::test_parallel_distributed_insert_select_with_schema_inference

**Comment by tavplubix** [comment]
Stress test (ubsan) - https://github.com/ClickHouse/ClickHouse/issues/45372

**Pull request merged**
