### PR TITLE
Many rows in totals

### LINKED ISSUE #12460: clickhouse-client: Got 2 in totals chunk, expected 1
```
/4/ :) SELECT arrayJoin([1, 2])  GROUP BY 1 WITH TOTALS FORMAT JSON

{
	"meta":
	[
		{
			"name": "arrayJoin([1, 2])",
			"type": "UInt8"
		}
	],

	"data":
	[
		{
			"arrayJoin([1, 2])": 1
		},
		{
			"arrayJoin([1, 2])": 2
		}← Progress: 0.00 rows, 0.00 B (0.00 rows/s., 0.00 B/s.) Logical error: 'Got 2 in totals chunk, expected 1'.
clickhouse-client: /home/akuzm/ch4/ch/src/Common/Exception.cpp:45: DB::Exception::Exception(const std::string &, int): Assertion `false' failed.
Aborted (core dumped)
```

### PR DESCRIPTION
**Pull request by KochetovNicolai**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Fix #12460

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]
Ok.

The result can be also surprising after array join with empty array.

**Comment by tavplubix** [comment]
Now most formats cut totals block to one row, but `Pretty` do not and it may print multiple rows. Maybe always print only the first row of totals block?

**Comment by KochetovNicolai** [comment]
> Now most formats cut totals block to one row, but Pretty do not and it may print multiple rows. Maybe always print only the first row of totals block?

Yes, I had the same idea. However, it cause backward incompatibility.
Probably, it is not significant and we can easily brake it.  @alexey-milovidov what do you think?

**Comment by alexey-milovidov** [comment]
What incompatibility is possible?

**Comment by KochetovNicolai** [comment]
Output result for queries like in test will be different in `Pretty` format (single totals rows instead of many).
I suppose, it was working that way for a log time .

**Comment by alexey-milovidov** [comment]
I's Ok to break.

**Review by tavplubix — APPROVED** [review]

**Pull request merged**
