### PR TITLE
Fix race for description in MemoryTracker.

### PR DESCRIPTION
**Pull request by KochetovNicolai**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Not for changelog (changelog entry is not required)

https://clickhouse-test-reports.s3.yandex.net/11171/4c5324600b6c847009da083d185d97a9c425b0f6/stress_test_(thread)/stderr.log

### CODE REVIEW

**Review by nikitamikhaylov — APPROVED** [review]

**Review by alexey-milovidov — APPROVED** [review]

**Comment by KochetovNicolai** [comment]
Stress should be fixed in #11264

**Comment by nikitamikhaylov** [comment]
This PR should be backported to 20.3

**Comment by alexey-milovidov** [comment]
@nikitamikhaylov It's not a bugfix and no bug was present. Not necessary to backport (only to fulfill tests).

**Comment by nikitamikhaylov** [comment]
> @nikitamikhaylov It's not a bugfix and no bug was present. Not necessary to backport (only to fulfill tests).

But it fixes the data race... 
I am kinda perfectionist, want the tests and builds in LTS branch to be green except some

**Comment by nikitamikhaylov** [comment]
Backported manually in 06784ed

**Pull request merged**
