### PR TITLE
Cherry pick #63097 to 23.8: Fix incorrect judgement of of monotonicity of function abs

### PR DESCRIPTION
**Pull request by robot-ch-test-poll3**
Original pull-request #63097

This pull-request is a first step of an automated backporting.
It contains changes similar to calling `git cherry-pick` locally.
If you intend to continue backporting the changes, then resolve all conflicts if any.
Otherwise, if you do not want to backport them, then just close this pull-request.

The check results does not matter at this step - you can safely ignore them.

### Note

This pull-request will be merged automatically. Please, **do not merge it manually** (but if you accidentally did, nothing bad will happen).

#### If the PR was manually reopened after being closed

If this PR is stuck (i.e. not automatically merged after one day), check https://github.com/ClickHouse/ClickHouse/pull/63097 for `pr-backports-created` *label* and delete it.

Manually merging will do nothing. The `pr-backports-created` *label* prevents the original PR https://github.com/ClickHouse/ClickHouse/pull/63097 from being processed.

#### If the conflicts were resolved in a wrong way

If this cherry-pick PR is completely screwed by a wrong conflicts resolution, and you want to recreate it:

- delete the `pr-cherrypick` label from the PR
- delete this branch from the repository

You also need to check the original PR https://github.com/ClickHouse/ClickHouse/pull/63097 for `pr-backports-created`, and delete if it's presented there

### CODE REVIEW

**Comment by robot-ch-test-poll1** [comment]
Dear @alexey-milovidov, the PR is not updated for 1d24h55m49s. Please, either resolve the conflicts, or close it to finish the backport process of #63097

**Comment by robot-clickhouse** [comment]
Dear @alexey-milovidov, the PR is not updated for 1d24h1m0s. Please, either resolve the conflicts, or close it to finish the backport process of #63097

**Comment by robot-clickhouse-ci-2** [comment]
Dear @alexey-milovidov, the PR is not updated for 1d24h0m58s. Please, either resolve the conflicts, or close it to finish the backport process of #63097

**Comment by robot-clickhouse-ci-2** [comment]
Dear @alexey-milovidov, the PR is not updated for 1d24h1m1s. Please, either resolve the conflicts, or close it to finish the backport process of #63097

**Comment by robot-clickhouse** [comment]
Dear @alexey-milovidov, the PR is not updated for 1d24h56m46s. Please, either resolve the conflicts, or close it to finish the backport process of #63097

**Comment by robot-ch-test-poll** [comment]
Dear @alexey-milovidov, the PR is not updated for 1d24h1m17s. Please, either resolve the conflicts, or close it to finish the backport process of #63097

**Comment by robot-ch-test-poll** [comment]
Dear @alexey-milovidov, the PR is not updated for 1d25h0m1s. Please, either resolve the conflicts, or close it to finish the backport process of #63097

**Comment by robot-ch-test-poll** [comment]
Dear @alexey-milovidov, the PR is not updated for 1d24h0m4s. Please, either resolve the conflicts, or close it to finish the backport process of #63097

**Comment by robot-ch-test-poll** [comment]
Dear @alexey-milovidov, the PR is not updated for 1d24h0m5s. Please, either resolve the conflicts, or close it to finish the backport process of #63097

**Comment by robot-clickhouse-ci-2** [comment]
Dear @alexey-milovidov, the PR is not updated for 1d24h0m5s. Please, either resolve the conflicts, or close it to finish the backport process of #63097

**Comment by robot-ch-test-poll2** [comment]
Dear @alexey-milovidov, the PR is not updated for 1d24h59m53s. Please, either resolve the conflicts, or close it to finish the backport process of #63097

**Comment by robot-clickhouse** [comment]
Dear @alexey-milovidov, the PR is not updated for 1d24h59m50s. Please, either resolve the conflicts, or close it to finish the backport process of #63097

**Comment by robot-clickhouse-ci-1** [comment]
Dear @alexey-milovidov, the PR is not updated for 1d25h0m23s. Please, either resolve the conflicts, or close it to finish the backport process of #63097

**Comment by robot-clickhouse-ci-1** [comment]
Dear @alexey-milovidov, the PR is not updated for 1d24h0m14s. Please, either resolve the conflicts, or close it to finish the backport process of #63097

**Comment by robot-ch-test-poll3** [comment]
Dear @alexey-milovidov, the PR is not updated for 1d24h57m27s. Please, either resolve the conflicts, or close it to finish the backport process of #63097

**Comment by robot-clickhouse-ci-1** [comment]
Dear @alexey-milovidov, the PR is not updated for 1d24h0m42s. Please, either resolve the conflicts, or close it to finish the backport process of #63097

**Comment by robot-ch-test-poll4** [comment]
Dear @alexey-milovidov, the PR is not updated for 1d24h0m52s. Please, either resolve the conflicts, or close it to finish the backport process of #63097

**Comment by robot-clickhouse** [comment]
Dear @alexey-milovidov, the PR is not updated for 1d24h58m8s. Please, either resolve the conflicts, or close it to finish the backport process of #63097

**Comment by robot-ch-test-poll3** [comment]
Dear @alexey-milovidov, the PR is not updated for 1d24h57m38s. Please, either resolve the conflicts, or close it to finish the backport process of #63097

**Comment by robot-clickhouse-ci-1** [comment]
Dear @alexey-milovidov, the PR is not updated for 1d24h59m38s. Please, either resolve the conflicts, or close it to finish the backport process of #63097

**Comment by robot-ch-test-poll4** [comment]
Dear @alexey-milovidov, the PR is not updated for 1d25h2m11s. Please, either resolve the conflicts, or close it to finish the backport process of #63097

**Comment by robot-ch-test-poll3** [comment]
Dear @alexey-milovidov, the PR is not updated for 1d24h57m26s. Please, either resolve the conflicts, or close it to finish the backport process of #63097

**Comment by robot-ch-test-poll2** [comment]
Dear @alexey-milovidov, the PR is not updated for 1d24h0m18s. Please, either resolve the conflicts, or close it to finish the backport process of #63097

**Comment by robot-ch-test-poll2** [comment]
Dear @alexey-milovidov, the PR is not updated for 1d24h3m3s. Please, either resolve the conflicts, or close it to finish the backport process of #63097

**Comment by robot-clickhouse** [comment]
Dear @alexey-milovidov, the PR is not updated for 1d24h57m47s. Please, either resolve the conflicts, or close it to finish the backport process of #63097

**Pull request closed without merging**
