### PR TITLE
[CANCELED] Ability to preserve user for distributed queries

### LINKED ISSUE #6843: Adding "use 'initial_user' option" to user specification in cluster definition
**Use case**
We use `max_memory_usage_for_user` option to limit the memory usage in order not to allow a single user to occupy a large amount of memory (to maintain availability).
However, the cluster uses another user, defined in cluster definition, instead of query `initial_user`, therefore the memory limitation only works for the initial server.

https://clickhouse.yandex/docs/en/operations/table_engines/distributed/

**Describe the solution you'd like**
One solution to this problem is to add a boolean option, `use_initial_user_if_possible` under cluster name, which means "use `initial_user` to connect to other shards if possible."
It can be something like:

```xml
 <remote_servers>
     <logs>
+        <!-- Optional. Use initial_user (if possible) instead of user specified here. Default: false (use specified user) -->
+        <use_initial_user_if_possible>true</use_initial_user_if_possible>
         <shard>
             <!-- Optional. Shard weight when writing data. Default: 1. -->
             <weight>1</weight>
 ...
```

pros:
- can be used with little change in configuration

cons:
- how can clickhouse-server know the password for `initial_user`? (it may be hashed in `users.xml`)
  - simply "use specified user/pass" when the password of initial_user is hashed in users.xml, otherwise use initial_user with its password, can be possible.

**Describe alternatives you've considered**
I have no better ideas.
(Writing down the "if-else" statements that determine which user to use in XML can be also possible, which seems much more complex.)

**Additional context**
Many batch processes access to our ClickHouse cluster.
We want to reject any memory-consuming (>32GiB) operations/users because such query can damage the availability of other users/batches.
However, we currently can only limit the memory_usage on the initial server, and usage on other shards are not limited (unless that user also connects to it directly).

### PR DESCRIPTION
**Pull request by azat**
Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Preserve initial_user for Distributed queries if user was not specified in remote_servers

Fixes: #6843

### CODE REVIEW

**Comment by filimonov** [comment]
Related:
https://github.com/ClickHouse/ClickHouse/issues/9751 
https://github.com/ClickHouse/ClickHouse/pull/8926

**Comment by abyss7** [comment]
It doesn't look good in some cases.
- What to do if the propagated user is not defined on the whole cluster?
- How to handle situations when incoming connection to the initiator is secured, but outcoming is not?
- How to provide backward compatibility for current production clusters where all the settings and contraints are properly defined for 'default' user only? Especially for the 1st case.

Also, it's won't work, if we implement any other authentication options. So it may be a temporary solution for now.

My suggestion is to put this behavior behind config option like `<propagate_plain_user_password>1</propagate_plain_user_password>`.

**Review by abyss7 — CHANGES_REQUESTED** [review]
Put the new behavior under some config option.

**Review by abyss7 — CHANGES_REQUESTED** [review]
Also you should make sure, that a raw password isn't stored in RAM on the long-term basis, i.e. it should be sent to remote and then erased immediately from memory.

**Comment by azat** [comment]
> How to handle situations when incoming connection to the initiator is secured, but outcoming is not?

This PR does not changes this, am I missing something?

> How to provide backward compatibility for current production clusters where all the settings and contraints are properly defined for 'default' user only? Especially for the 1st case.

Agree, backward compatibility should be defined.
I went without for two reasons, simplicity (forgot to mark this PR as RFC, egh) and https://github.com/ClickHouse/ClickHouse/issues/6843#issuecomment-528889610 misread

> Also, it's won't work, if we implement any other authentication options. So it may be a temporary solution for now.

Yes, and like @filimonov noted that there can be some issues for kerberos/LDAP (since they requires some keys IIRC).

> Also you should make sure, that a raw password isn't stored in RAM on the long-term basis, i.e. it should be sent to remote and then erased immediately from memory.

But it is already stored in the `ClientInfo`, does it that significant? (`Context::setUser`)

Actually there is another way to go, suggested by @filimonov in #9751 
And looks like it will resolve all the issues (and remove extra reconnect), any thoughts on this?

**Comment by abyss7** [comment]
> > How to handle situations when incoming connection to the initiator is secured, but outcoming is not?
> 
> This PR does not changes this, am I missing something?
>
Yes, but AFAIK current implementation never re-sends passwords.
 
> > Also you should make sure, that a raw password isn't stored in RAM on the long-term basis, i.e. it should be sent to remote and then erased immediately from memory.
> 
> But it is already stored in the `ClientInfo`, does it that significant? (`Context::setUser`)
> 
Actually yes, so it's not getting worse.

> Actually there is another way to go, suggested by @filimonov in #9751
> And looks like it will resolve all the issues (and remove extra reconnect), any thoughts on this?

Do you plan to continue this PR anyway, or will postpone it?

**Comment by azat** [comment]
>Do you plan to continue this PR anyway, or will postpone it?

Sure, I will continue (marked as draft to avoid attracting extra attention until it will be reworked/fixed)

Right now I have two options:
- just introduce options to make it backward compatible (simple)
- introduce proxy/impersonate users (as suggested in #9751, any cons for it?), but it will require more time

Proxy user does not have mentioned limitations, but it looks a little bit oversized for this kind of support, I guess I will try it and see how it will looks eventually

**Comment by azat** [comment]
>Also, it's won't work, if we implement any other authentication options. So it may be a temporary solution for now.

Actually the same thing is used in `StorageReplicatedMergeTree::sendRequestToLeaderReplica`

**Pull request closed without merging**
