### PR TITLE
Update to libunwind 8.1.7

### PR DESCRIPTION
**Pull request by al13n321**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

https://github.com/ClickHouse/libunwind/pull/28

In hopes that it'll fix some bugs that cause segfaults, although AFAICT fixes neither of the bugs in https://github.com/ClickHouse/libunwind/pull/27

### CODE REVIEW

**Comment by robot-clickhouse-ci-1** [comment]
*This is an automated comment for commit 424224b2023fbdc72993f83e19f0dd7c6ff0b84b with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/65509/424224b2023fbdc72993f83e19f0dd7c6ff0b84b/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Cloud fork sync (only for ClickHouse Inc. employees)</td><td>If it fails, ask a maintainer for help</td><td>⏳ pending</td></tr>
<tbody>
</table>
<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>Checks correctness of the PR's body</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
@al13n321, need to fix the tests.

**Comment by alexey-milovidov** [comment]
Builds have failed.

**Comment by alexey-milovidov** [comment]
@al13n321, it failed.

**Comment by alexey-milovidov** [comment]
@al13n321, jemalloc has failed:
```
2024-07-05 02:03:10 <jemalloc>: /build/contrib/jemalloc/src/decay.c:92: Failed assertion: "nstime_compare(&decay->epoch, new_time) <= 0"
```

**Comment by alexey-milovidov** [comment]
@al13n321, it failed entirely and miserably.

**Pull request merged**
