### PR TITLE
Build fuzzers with clang-tidy

### PR DESCRIPTION
**Pull request by nikitamikhaylov**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):

- Not for changelog (changelog entry is not required)

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
Maybe @KochetovNicolai can fix `Logical error: 'ColumnUnique can't contain null values.'.`?

**Comment by nikitamikhaylov** [comment]
@alexey-milovidov Merge? I moved all fuzzers to separate directory, also moved some methods from `CompressionFactory.cpp` to `CompressionFactoryAdditions.cpp`, because they depends on DataTypes. Deleted `YAML_fuzzer`, because it doesn't work at all. This all is needed to properly resurrect ClickHouse continuous fuzzing fuzzing via OSS-Fuzz https://github.com/google/oss-fuzz/pull/6255

**Review by alexey-milovidov — APPROVED** [review]
LGTM

**Comment by nikitamikhaylov** [comment]
Last commit contains only style related things.

**Pull request merged**
