### PR TITLE
Move conditions with columns from PK to the end of PREWHERE chain

### PR DESCRIPTION
**Pull request by davenger**
### Changelog category (leave one):
- Performance Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
The idea is that conditions with PK columns are likely to be used in PK analysis and will not contribute much more to PREWHERE filtering

### CODE REVIEW

**Comment by robot-ch-test-poll** [comment]
This is an automated comment for commit 278b1e9e4af947f78683bb6d2d635db077729b10 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/51958/278b1e9e4af947f78683bb6d2d635db077729b10/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Review by nickitat — APPROVED** [review]
lgtm, but I'd love to see a benchmark over a real table (at least ClickBench run)

**Comment by davenger** [comment]
@nickitat here are ClickBench results https://pastila.nl/?000b1ba6/c2b445d46b4b7e269b0be94efcf97c7f.html
They don't show much difference between 'Move PK columns' ON and OFF. Maybe it's worth looking more into it.
Meanwhile do you think it makes sense to merge multi-stage PREWHERE PR https://github.com/ClickHouse/ClickHouse/pull/46365 first? The current PR has all commits from it because there is not much sense whithout `move_all_conditions_to_prewhere=1`.

**Comment by nickitat** [comment]
> do you think it makes sense to merge multi-stage PREWHERE PR #46365 first?

yep

**Review by alexey-milovidov — APPROVED** [review]

**Pull request merged**
