### PR TITLE
Remove redundant content in Linux build docs

### PR DESCRIPTION
**Pull request by rschu1ze**
The same information about split builds existed twice in the document. This change merges both places into one.

Changelog category (leave one):
- Documentation (changelog entry is not required)

### CODE REVIEW

**Comment by rschu1ze** [comment]
This is my first pull request, please don't beat me :-) Kindly let me know what else I need to do to adhere to the official contribution process.

**Comment by rschu1ze** [comment]
CheckLabels says: "INFO:root:User 'rschu1ze' is not trusted". Am I able to fix that by myself?

**Comment by Algunenano** [comment]
> CheckLabels says: "INFO:root:User 'rschu1ze' is not trusted". Am I able to fix that by myself?

This is expected. For security reasons only the PRs of core contributors or trusted users run the CI automatically. Once a core contributor has the chance of reviewing it they can tag it as safe and the CI will run.

**Comment by alesapin** [comment]
@mergifyio update

**Review by alexey-milovidov — APPROVED** [review]

**Pull request merged**
