### PR TITLE
Disable parallel replicas JOIN with CTE (not analyzer)

### PR DESCRIPTION
**Pull request by Algunenano**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
- Disable parallel replicas JOIN with CTE (not analyzer)

### Documentation entry for user-facing changes

Disable parallel replicas when doing a JOIN between a mergetree and a CTE. It never worked correctly. In the best case you get a missing table error or an exception due to mixing different tables, in the worse case you read from different tables than expected and get an incorrect result.

Partially reverts / reimplements https://github.com/ClickHouse/ClickHouse/pull/58133 cc @devcrafter 

The analyzer already has a better implementation.

### CODE REVIEW

**Comment by robot-clickhouse** [comment]
*This is an automated comment for commit 8dfa6084f6e00b4a449788faeef6469c9722fb13 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/59239/8dfa6084f6e00b4a449788faeef6469c9722fb13/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/59239/8dfa6084f6e00b4a449788faeef6469c9722fb13/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Review by amsterdam-office-chromebox — APPROVED** [review]

**Comment by Algunenano** [comment]
Failures is unrelated

**Review by devcrafter — APPROVED** [review]

**Comment by devcrafter** [comment]
@Algunenano It looks there is an issue with the code - https://s3.amazonaws.com/clickhouse-test-reports/59375/35d133947432fe2bfb901beba2678bdd40c71826/ast_fuzzer__ubsan_/report.html

**Comment by Algunenano** [comment]
> It looks there is an issue with the code

Thank you! Adding a patch to fix it

**Pull request merged**
