### PR TITLE
V19.17.5.18 macos clang

### PR DESCRIPTION
**Pull request by kmatt**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Bug Fix
- Documentation

Changelog entry (up to few sentences, required except for Non-significant/Documentation categories):

- Remove unsupported compiler flag on Clang / macOS (-Wno-ctad-maybe-unsupported)
- Update build docs for Clang / macOS

Addresses:

- #7995
- #7546 
- #5765

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
Could you please rebase these changes on top of master?

**Comment by alexey-milovidov** [comment]
Or I can simply cherry-pick these two commits:
https://github.com/ClickHouse/ClickHouse/pull/8132/commits/1c3210c15c67b161a0d8925c00392764bd1b0142
https://github.com/ClickHouse/ClickHouse/pull/8132/commits/74eb874b04e66a75201c7b93228345abeddf12cc

**Comment by kmatt** [comment]
> Could you please rebase these changes on top of master?

@alexey-milovidov I will rebase. Best to close this and generate a new PR ?

**Comment by kmatt** [comment]
Replaced with #8148

**Pull request closed without merging**
