### PR TITLE
Fix missed entries in system.part_log in case of fetch preferred over merges/mutations

### PR DESCRIPTION
**Pull request by azat**
The NEED_PREPARE do not call part_log_writer() before.

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by robot-ch-test-poll** [comment]
*This is an automated comment for commit eaed8ad8497af593ef6dbd893f8365def61ff2f9 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/60659/eaed8ad8497af593ef6dbd893f8365def61ff2f9/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
Is it difficult to write a test? I recall there are settings that could be used to make fetches preferred over merges most of the time.

**Comment by azat** [comment]
Added a test for mutations and merges (and also the patch did not work properly, this had been fixed as well)

**Comment by azat** [comment]
>PullRequestCI / FunctionalStatelessTestFlakyCheck / Stateless tests flaky check (asan) (pull_request) Failing after 22s

- https://github.com/ClickHouse/ClickHouse/pull/60694

**Comment by azat** [comment]
Lots of unrelated failures, will do a rebase

**Comment by azat** [comment]
>Fast test — fail: 1, passed: 5101, skipped: 1102

New test is broken after https://github.com/ClickHouse/ClickHouse/pull/58845

**Comment by azat** [comment]
>Stateless tests (aarch64) — fail: 1, passed: 6177, skipped: 24
>Stateless tests (asan) [1/4] — fail: 1, passed: 1556, skipped: 15

- https://github.com/ClickHouse/ClickHouse/pull/61253

**Review by alexey-milovidov — APPROVED** [review]

**Pull request merged**
