### PR TITLE
Throw memory limit exceptions to avoid OOM in some places

### PR DESCRIPTION
**Pull request by alesapin**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by robot-clickhouse-ci-2** [comment]
*This is an automated comment for commit 04d885b570325b1e66bf0c7c13d4732b4d9340ec with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/61132/04d885b570325b1e66bf0c7c13d4732b4d9340ec/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

**Comment by alesapin** [comment]
Found several cases in production:
```
Row 1:
──────
s:          6.95 GiB
trace_text: ./build_docker/./src/Common/MemoryTracker.cpp:100: AllocationTrace::onAllocImpl(void*, unsigned long) const
./src/Common/AllocationTrace.h:0: operator new(unsigned long)
./contrib/llvm-project/libcxx/include/__split_buffer:577: std::__1::deque<unsigned long, std::__1::allocator<unsigned long>>::__add_back_capacity()
./contrib/llvm-project/libcxx/include/__split_buffer:88: DB::ExecutingGraph::updateNode(unsigned long, std::__1::queue<DB::ExecutingGraph::Node*, std::__1::deque<DB::ExecutingGraph::Node*, std::__1::allocator<DB::ExecutingGraph::Node*>>>&, std::__1::queue<DB::ExecutingGraph::Node*, std::__1::deque<DB::ExecutingGraph::Node*, std::__1::allocator<DB::ExecutingGraph::Node*>>>&)
./build_docker/./src/Processors/Executors/PipelineExecutor.cpp:292: DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*)
./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:833: void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<DB::PipelineExecutor::spawnThreads()::$_0, void ()>>(std::__1::__function::__policy_storage const*)
./base/base/../base/wide_integer_impl.h:809: ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::worker(std::__1::__list_iterator<ThreadFromGlobalPoolImpl<false>, void*>)
./build_docker/./src/Common/ThreadPool.cpp:0: void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()>(void&&)::'lambda'(), void ()>>(std::__1::__function::__policy_storage const*)
./base/base/../base/wide_integer_impl.h:809: void* std::__1::__thread_proxy[abi:v15000]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()>>(void*)
: 
: 

Row 2:
──────
s:          6.67 GiB
trace_text: ./build_docker/./src/Common/MemoryTracker.cpp:100: AllocationTrace::onAllocImpl(void*, unsigned long) const
./src/Common/AllocationTrace.h:0: operator new(unsigned long)
./contrib/llvm-project/libcxx/include/__split_buffer:577: std::__1::deque<DB::ExecutingGraph::Node*, std::__1::allocator<DB::ExecutingGraph::Node*>>::__add_back_capacity()
./contrib/llvm-project/libcxx/include/deque:1170: DB::ExecutingGraph::updateNode(unsigned long, std::__1::queue<DB::ExecutingGraph::Node*, std::__1::deque<DB::ExecutingGraph::Node*, std::__1::allocator<DB::ExecutingGraph::Node*>>>&, std::__1::queue<DB::ExecutingGraph::Node*, std::__1::deque<DB::ExecutingGraph::Node*, std::__1::allocator<DB::ExecutingGraph::Node*>>>&)
./build_docker/./src/Processors/Executors/PipelineExecutor.cpp:292: DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*)
./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:833: void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<DB::PipelineExecutor::spawnThreads()::$_0, void ()>>(std::__1::__function::__policy_storage const*)
./base/base/../base/wide_integer_impl.h:809: ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::worker(std::__1::__list_iterator<ThreadFromGlobalPoolImpl<false>, void*>)
./build_docker/./src/Common/ThreadPool.cpp:0: void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()>(void&&)::'lambda'(), void ()>>(std::__1::__function::__policy_storage const*)
./base/base/../base/wide_integer_impl.h:809: void* std::__1::__thread_proxy[abi:v15000]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()>>(void*)
: 
: 



Query id: 558c8f1e-e0f2-49ac-a859-9ad9ece05449

Row 1:
──────
median(size):        7753992
quantile(0.9)(size): 14263067.2
count():             77
s:                   631.34 MiB
trace_text:          ./build_docker/./src/Common/MemoryTracker.cpp:263: MemoryTracker::allocImpl(long, bool, MemoryTracker*, double)
./build_docker/./src/Common/MemoryTracker.cpp:0: MemoryTracker::allocImpl(long, bool, MemoryTracker*, double)
./src/Common/CurrentMemoryTracker.cpp:59: operator new(unsigned long)
./contrib/llvm-project/libcxx/include/new:246: void std::__1::vector<DB::Chunk, std::__1::allocator<DB::Chunk>>::__push_back_slow_path<DB::Chunk>(DB::Chunk&&)
./contrib/llvm-project/libcxx/include/vector:537: DB::MergeSortingTransform::consume(DB::Chunk)
./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:701: DB::SortingTransform::work()
./build_docker/./src/Processors/Executors/ExecutionThreadContext.cpp:0: DB::ExecutionThreadContext::executeTask()
./build_docker/./src/Processors/Executors/PipelineExecutor.cpp:273: DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*)
./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:833: void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<DB::PipelineExecutor::spawnThreads()::$_0, void ()>>(std::__1::__function::__policy_storage const*)
./base/base/../base/wide_integer_impl.h:809: ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::worker(std::__1::__list_iterator<ThreadFromGlobalPoolImpl<false>, void*>)
./build_docker/./src/Common/ThreadPool.cpp:0: void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()>(void&&)::'lambda'(), void ()>>(std::__1::__function::__policy_storage const*)
./base/base/../base/wide_integer_impl.h:809: void* std::__1::__thread_proxy[abi:v15000]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()>>(void*)
: 
:
```

**Comment by alesapin** [comment]
^ I understand that this trace doesn't 100% mean that queue was huge, maybe we had a lot of allocations and consequent deallocations. But this query failed with OOM killer, and this place still looks very suspicious -- better to add check, this code is good and should be ready for exceptions.

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
An integration test has failed.

**Comment by alesapin** [comment]
`> An integration test has failed.`
Fixed in https://github.com/ClickHouse/ClickHouse/pull/61136

**Comment by alesapin** [comment]
`insert_select_too_many_parts`: https://play.clickhouse.com/play?user=play#U0VMRUNUIGNoZWNrX25hbWUsIHB1bGxfcmVxdWVzdF9udW1iZXIsIHRlc3RfbmFtZSwgcmVwb3J0X3VybApGUk9NIGNoZWNrcwpXSEVSRSAxCiAgICBBTkQgY2hlY2tfc3RhcnRfdGltZSA+PSBub3coKSAtIElOVEVSVkFMIDk2IEhPVVIKICAgCiAgICBBTkQgdGVzdF9zdGF0dXMgIT0gJ1NLSVBQRUQnCiAgICBBTkQgdGVzdF9zdGF0dXMgTElLRSAnRiUnCiAgICBBTkQgY2hlY2tfc3RhdHVzICE9ICdzdWNjZXNzJwogICAgQU5EIHRlc3RfbmFtZSBpbGlrZSAnJTAxNjAzX2luc2VydF9zZWxlY3RfdG9vX21hbnlfcGFydHMlJwpPUkRFUiBCWSBjaGVja19uYW1lLCB0ZXN0X25hbWUsIGNoZWNrX3N0YXJ0X3RpbWU=

**Comment by alesapin** [comment]
`02784_parallel_replicas_automatic_decision_join:` https://play.clickhouse.com/play?user=play#U0VMRUNUIGNoZWNrX25hbWUsIHB1bGxfcmVxdWVzdF9udW1iZXIsIHRlc3RfbmFtZSwgcmVwb3J0X3VybApGUk9NIGNoZWNrcwpXSEVSRSAxCiAgICBBTkQgY2hlY2tfc3RhcnRfdGltZSA+PSBub3coKSAtIElOVEVSVkFMIDk2IEhPVVIKICAgCiAgICBBTkQgdGVzdF9zdGF0dXMgIT0gJ1NLSVBQRUQnCiAgICBBTkQgdGVzdF9zdGF0dXMgTElLRSAnRiUnCiAgICBBTkQgY2hlY2tfc3RhdHVzICE9ICdzdWNjZXNzJwogICAgQU5EIHRlc3RfbmFtZSBpbGlrZSAnJTAyNzg0X3BhcmFsbGVsX3JlcGxpY2FzX2F1dG9tYXRpY19kZWNpc2lvbl9qb2luJScKT1JERVIgQlkgY2hlY2tfbmFtZSwgdGVzdF9uYW1lLCBjaGVja19zdGFydF90aW1l

**Comment by alesapin** [comment]
`00002_log_and_exception_messages_formatting:` https://play.clickhouse.com/play?user=play#U0VMRUNUIGNoZWNrX25hbWUsIHB1bGxfcmVxdWVzdF9udW1iZXIsIHRlc3RfbmFtZSwgcmVwb3J0X3VybApGUk9NIGNoZWNrcwpXSEVSRSAxCiAgICBBTkQgY2hlY2tfc3RhcnRfdGltZSA+PSBub3coKSAtIElOVEVSVkFMIDk2IEhPVVIKICAgCiAgICBBTkQgdGVzdF9zdGF0dXMgIT0gJ1NLSVBQRUQnCiAgICBBTkQgdGVzdF9zdGF0dXMgTElLRSAnRiUnCiAgICBBTkQgY2hlY2tfc3RhdHVzICE9ICdzdWNjZXNzJwogICAgQU5EIHRlc3RfbmFtZSBpbGlrZSAnJTAwMDAyX2xvZ19hbmRfZXhjZXB0aW9uX21lc3NhZ2VzX2Zvcm1hdHRpbmclJwpPUkRFUiBCWSBjaGVja19uYW1lLCB0ZXN0X25hbWUsIGNoZWNrX3N0YXJ0X3RpbWU=

**Pull request merged**
