### PR TITLE
MergeTree full support for S3

### PR DESCRIPTION
**Pull request by Jokser**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
MergeTree full support for DiskS3

Detailed description / Documentation draft:
All I/O operations in MergeTree are reworked using IDisk.
MergeTree works with S3 as the main storage. Merges and mutations work as well.
DiskS3 can be used in storage policy as cold or primary storage.
Background processing pool settings are now configurable.

### CODE REVIEW

**Comment by filimonov** [comment]
> Merges and mutations work as well.

But suboptimal for now as i understand (copy instead of hardlink). 

What is with renames?

**Comment by Jokser** [comment]
> > Merges and mutations work as well.
> 
> But suboptimal for now as i understand (copy instead of hardlink).
> 
> What is with renames?

Yes. Hardlinks will be implemented in the next PR.
Renaming works as well, will add a test for that.

**Comment by filimonov** [comment]
> Renaming works as well, will add a test for that.

For folders? I remember there was some issues on using MergeTree on fuse because directory rename is considered as instant/atomic op. (it is not on s3

**Comment by Jokser** [comment]
> > Renaming works as well, will add a test for that.
> 
> For folders? I remember there was some issues on using MergeTree on fuse because directory rename is considered as instant/atomic op. (it is not on s3

Directory renaming in DiskS3 just renames directory on local FS where metadata files are located.

**Pull request merged**
