### PR TITLE
Lower block sizes and look what will happen

### PR DESCRIPTION
**Pull request by alexey-milovidov**
Changelog category (leave one):
- Performance Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Lower memory usage for some operations up to 2 times.

#9248

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
> Performance — 13 faster, 2 slower, 209 unstable 

It is a clear win.

But paradoxically, most of queries that become faster have fixed block_size specified in SETTINGS clause. @akuzm

**Comment by alexey-milovidov** [comment]
MemoryResident

**Comment by azat** [comment]
>But paradoxically, most of the queries that become faster have fixed block_size specified in SETTINGS clause.

This is interesting.

I got one query from perf tests, replaced hits_10m_single with hits_100m_obfuscated, and got this:

- clickhouse.orig (from upstream/master): with adjusted block-size to take the padding into account it is indeed faster

  - `max_block_size=65505`: QPS ~190
  - `max_block_size=32K`: QPS ~190
  - `max_block_size=65535`: QPS ~145

<details>

```
$ clickhouse-benchmark --delay 0 --timelimit 60 --max_block_size=65505 <<<'SELECT MobilePhoneModel FROM hits_100m_obfuscated ORDER BY MobilePhoneModel LIMIT 65535'
Queries executed: 182.
localhost:9000, queries 182, QPS: 3.024, RPS: 302401482.254, MiB/s: 2662.674, result RPS: 198178.811, result MiB/s: 1.701.
0.000%          0.266 sec.
10.000%         0.300 sec.
90.000%         0.366 sec.
99.990%         0.427 sec.

$ clickhouse-benchmark --delay 0 --timelimit 60 --max_block_size=65535 <<<'SELECT MobilePhoneModel FROM hits_100m_obfuscated ORDER BY MobilePhoneModel LIMIT 65535'
Queries executed: 145.
localhost:9000, queries 145, QPS: 2.407, RPS: 240680326.362, MiB/s: 2119.213, result RPS: 157729.852, result MiB/s: 1.354.

0.000%          0.357 sec.
10.000%         0.377 sec.
90.000%         0.468 sec.
99.990%         0.508 sec.

$ clickhouse-benchmark --delay 0 --timelimit 60 --max_block_size=$(( (1<<15)-1 )) <<<'SELECT MobilePhoneModel FROM hits_100m_obfuscated ORDER BY MobilePhoneModel LIMIT 65535'
Stopping launch of queries. Requested time limit is exhausted.
Queries executed: 192.

localhost:9000, queries 192, QPS: 3.183, RPS: 318304281.384, MiB/s: 2802.699, result RPS: 208600.711, result MiB/s: 1.790.

0.000%          0.272 sec.
10.000%         0.291 sec.
90.000%         0.340 sec.
99.990%         0.398 sec.
```

</details>

- clickhouse.patched (from this PR): same results (more or less)

So after looking into the query_log from the perf tests, it seems that the settings was not applied, @akuzm is my understanding correct?

<details>

```
QueryFinish     2020-07-12      2020-07-12 06:22:38     2020-07-12 06:22:38     142     10000000        809446113       0       0       65535   5242880 976889652       SELECT URL FROM hits_10m_single ORDER BY URL LIMIT 65535 format Null settings max_block_size = 65536    0
                       1       default string_sort.query36.prewarm0    ::1     42924   default string_sort.query36.prewarm0    ::1     42924   1       root    linux-ubuntu-14-04-trusty       ClickHouse python-driver        54429   18      10      3       0               
        54436   [330,413,376,411,405,377,383,400,391,379,396,389,395,385,374,387,375,407,397,382,393,402,401,378,403,390,410,386,404,412,399,408,394,346,388,381,406,398,409,384,392,380]       ['Query','SelectQuery','FileOpen','Seek','ReadBufferFromFileDescriptorRead','ReadBufferFromFileDescriptorReadBytes','ReadCompressedBytes','CompressedReadBufferBlocks','CompressedReadBufferBytes','IOBufferAllocs','IOBufferAllocBytes','MarkCacheHits','MarkCacheMisses','CreatedReadBufferOrdinary','DiskReadElapsedMicroseconds','NetworkReceiveElapsedMicroseconds','NetworkSendElapsedMicroseconds','SelectedParts','SelectedRanges','SelectedMarks','ContextLock','RWLockAcquiredReadLocks','RealTimeMicroseconds','UserTimeMicroseconds','SystemTimeMicroseconds','SoftPageFaults','OSCPUWaitMicroseconds','OSCPUVirtualTimeMicroseconds','OSReadChars','OSWriteChars','PerfCpuCycles','PerfInstructions','PerfCacheReferences','PerfCacheMisses','PerfBranchInstructions','PerfBranchMisses','PerfBusCycles','PerfRefCpuCycles','PerfCpuClock','PerfTaskClock','PerfContextSwitches','PerfCpuMigrations','PerfMinEnabledTime','PerfMinEnabledRunningTime','PerfDataTLBReferences','PerfDataTLBMisses','PerfInstructionTLBReferences','PerfInstructionTLBMisses']       [1,1,40,38,161,165036436,146703330,1297,730293710,79,63162603,38,1,40,196010,13,120,1,1,1221,109,1,5835538,3120000,512000,124653,1052,3611753,165164142,96725,9965128944,14374846049,94380676,36256324,2481040444,100679571,89309200,7504243760,3604514125,3604513835,287,7,3604424459,3433757425,3717942336,580077,251464,282501]      ['use_uncompressed_cache','load_balancing','log_queries','query_profiler_real_time_period_ns','query_profiler_cpu_time_period_ns','metrics_perf_events_enabled','max_memory_usage','allow_introspection_functions']     ['0','random','1','10000000','0','1','10000000000','1']
```

(there should be `max_block_size` in settings array)

</details>

P.S. I've looked through the code and looks like `DEFAULT_BLOCK_SIZE` is not used directly (at least for the query above), only via `max_block_size`

P.P.S query with default max_block_size written explicitly in perf tests looks odd

**Review by azat — APPROVED** [review]
LGTM

**Comment by alexey-milovidov** [comment]
> P.S. I've looked through the code and looks like DEFAULT_BLOCK_SIZE is not used directly (at least for the query above), only via max_block_size

Yes, I have also checked it.

> So after looking into the query_log from the perf tests, it seems that the settings was not applied

But this simple test passes:
```
SELECT DISTINCT blockSize() FROM numbers(1000000) SETTINGS max_block_size = 10000
```

**Comment by azat** [comment]
>But this simple test passes:

Yep clickhouse-client everything works, and the query does contain the setting in the query_log.

I think here is the issue, perf tests uses clickhouse-driver in python, which just sends the query and this is not enough for this setting.
While clickhouse-client parse the settings from the query and send them in the protocol, that's why it works with the client.

**Comment by alexey-milovidov** [comment]
This also works fine:

```
$ curl http://localhost:8123/ --data-binary "SELECT DISTINCT blockSize() FROM numbers(1000000) SETTINGS max_block_size = 10000"
10000
```

**Comment by azat** [comment]
>which just sends the query and this is not enough for this setting.

The problem is in ASTQueryWithOutput, when it is used (i.e. when FORMAT is passed) then SETTINGS are not applied:

```
$ curl http://localhost:8123/ --data-binary "SELECT DISTINCT blockSize() FROM numbers(1000000) SETTINGS max_block_size = 10000 FORMAT CSV"                                                                                         
10000
$ curl http://localhost:8123/ --data-binary "SELECT DISTINCT blockSize() FROM numbers(1000000) FORMAT CSV SETTINGS max_block_size = 10000"                                                                                          
65536
16960
```

But again clickhouse-client is ok, since it parse the query

**Comment by azat** [comment]
>The problem is in ParserQueryWithOutput, when it is used (i.e. when FORMAT is passed) then SETTINGS after FORMAT are not applied:

AFAIU this is the intention, but looks tricky, maybe worth adding them to the ASTSelectQuery too after parsing from ParserQueryWithOutput?

**Comment by alexey-milovidov** [comment]
> AFAIU this is the intention, but looks tricky

I don't remember any intentions about that.

**Comment by alexey-milovidov** [comment]
> Performance — 15 faster, 215 unstable 

Wow, it has passed.

**Comment by alexey-milovidov** [comment]
@akuzm Could you please provide a number - what is "overall" (aggregated) change in performance across all tests?
(usually it is geomean across all queries, but geomean of geomeans of queries of tests is probably better).

**Comment by akuzm** [comment]
> @akuzm Could you please provide a number - what is "overall" (aggregated) change in performance across all tests?
> (usually it is geomean across all queries, but geomean of geomeans of queries of tests is probably better).

Will do, but it's probably going too be too noisy. I liked the cumulative distribution function plot for query time change, like this one: https://github.com/ClickHouse/ClickHouse/pull/11993#issuecomment-650976162
Maybe I'll try to add graphs like these as well.

**Comment by azat** [comment]
> > AFAIU this is the intention, but looks tricky, maybe worth adding them to the ASTSelectQuery too after parsing from ParserQueryWithOutput?
>
> I don't remember any intentions about that.

@alexey-milovidov so here is an RFC - #12480 (at least it will run tests and perf-tests with SETTINGS after FORMAT interpreted)

**Comment by alexey-milovidov** [comment]
@akuzm 
> Will do, but it's probably going to be too noisy.

When we had our old performance tests, average difference larger than 2% have always indicated significant changes.

**Comment by alexey-milovidov** [comment]
Example: https://github.com/ClickHouse/ClickHouse/pull/8311

**Comment by alexey-milovidov** [comment]
BTW, Cumulative graph is great.

**Pull request merged**
