### PR TITLE
Add parquet support (With contrib/*)

### PR DESCRIPTION
**Pull request by proller**
Contains https://github.com/yandex/ClickHouse/pull/2427

### CODE REVIEW

**Comment by proller** [comment]
NOTES:
1. fail in unbundled mode woth old double-cosnversion:
FAILED: contrib/arrow-cmake/CMakeFiles/arrow_static.dir/__/arrow/cpp/src/arrow/csv/converter.cc.o 
/usr/bin/g++-7  -DBOOST_SYSTEM_NO_DEPRECATED -Icontrib/arrow-cmake -I../contrib/arrow/cpp/src -I../contrib/arrow-cmake/cpp/src -isystem ../contrib/boost -fdiagnostics-color=always  -pipe -msse4.1 -msse4.2 -mpopcnt  -fno-omit-frame-pointer  -Wall  -Wnon-virtual-dtor -no-pie -Wno-old-style-cast -Wno-unused-function -Wno-unused-variable -Wno-unused-but-set-variable -Wno-unused-result -Wno-deprecated-declarations -Wno-non-virtual-dtor -Wno-maybe-uninitialized -Wno-format -Wno-misleading-indentation -Wno-implicit-fallthrough -Wno-class-memaccess -std=c++1z -O2 -g -DNDEBUG -O3    -std=c++1z -MD -MT contrib/arrow-cmake/CMakeFiles/arrow_static.dir/__/arrow/cpp/src/arrow/csv/converter.cc.o -MF contrib/arrow-cmake/CMakeFiles/arrow_static.dir/__/arrow/cpp/src/arrow/csv/converter.cc.o.d -o contrib/arrow-cmake/CMakeFiles/arrow_static.dir/__/arrow/cpp/src/arrow/csv/converter.cc.o -c ../contrib/arrow/cpp/src/arrow/csv/converter.cc
In file included from ../contrib/arrow/cpp/src/arrow/csv/converter.cc:30:0:
../contrib/arrow/cpp/src/arrow/util/parsing.h:123:51: error: 'ALLOW_CASE_INSENSIBILITY' is not a member of 'double_conversion::StringToDoubleConverter'
       double_conversion::StringToDoubleConverter::ALLOW_CASE_INSENSIBILITY;
                                                   ^~~~~~~~~~~~~~~~~~~~~~~~
cc1plus: warning: unrecognized command line option '-Wno-class-memaccess'

**Comment by alexey-milovidov** [comment]
I kindly ask to squash all your commits but to keep all commits of @luc1ph3r as separate items (unsquashed).

**Comment by andyyzh** [comment]
When will this feature be released?

**Comment by alexey-milovidov** [comment]
@andyyzh
This PR will be prepared for merging (most of commits will be squashed). Then the feature will be evaluated, PR will be merged to master and the next stable version of ClickHouse will be released. It may take a few weeks.

**Comment by proller** [comment]
https://github.com/yandex/ClickHouse/commit/e20c77e4c6f9d8326c387fd0a2833ed959bf1658

**Comment by alexey-milovidov** [comment]
Superseded by #4448

**Pull request closed without merging**
