### PR TITLE
Update MaterializedMySQLSyncThread.cpp

### PR DESCRIPTION
**Pull request by kolya7k**
mysql 8.3.0+ doesn't have log_bin_use_v1_row_events variable

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]

**Comment by robot-ch-test-poll1** [comment]
*This is an automated comment for commit af103c8c9d776939555c26bdc44a452b0467541d with description of existing statuses. It's updated for the latest CI running*

[❌ Click here](https://s3.amazonaws.com/clickhouse-test-reports/62793/af103c8c9d776939555c26bdc44a452b0467541d/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td><a href="https://github.com/ClickHouse/ClickHouse/blob/master/.github/PULL_REQUEST_TEMPLATE.md?plain=1">❌ failure</a></td></tr>
<tbody>
</table>

**Comment by Slach** [comment]
@kolya7k thanks you for your efforts

**Comment by alexey-milovidov** [comment]
> PR Check — Changelog category is empty

**Comment by alexey-milovidov** [comment]
Changelog category is empty

**Comment by alexey-milovidov** [comment]
@kolya7k it couldn't be merged due to the failed changelog check.

**Comment by alexey-milovidov** [comment]
@Slach, if you want to help, open another pull request with the same changes.

**Comment by Slach** [comment]
@kolya7k let's close this PR

**Pull request closed without merging**
