### PR TITLE
Set defaults_for_omitted_fields to true for hive text format

### PR DESCRIPTION
**Pull request by taiyang-li**
### Changelog category (leave one):
- Not for changelog

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Add tests for hive engine null_as_default

### CODE REVIEW

**Comment by robot-ch-test-poll3** [comment]
This is an automated comment for commit 5c67c5fd2640521121c7ebcf782d368f194cc6e1 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/49486/5c67c5fd2640521121c7ebcf782d368f194cc6e1/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Comment by taiyang-li** [comment]
@alexey-milovidov the hive tests need your review, thanks.

**Review by alexey-milovidov — APPROVED** [review]
I don't understand the changes in a few minutes, but let's merge just in case.

**Comment by alexey-milovidov** [comment]
@taiyang-li, it shows some conflicts. Let's resolve and then merge quickly.

**Comment by taiyang-li** [comment]
> @taiyang-li, it shows some conflicts. Let's resolve and then merge quickly.

I tried to solve the conflicts. But I found someone had delete integration test `test_hive_query`...

**Comment by alexey-milovidov** [comment]
@taiyang-li, the tests for Hive were flaky, and we don't use Hive, so we cannot fix them.
But it could still be alright to merge this PR.

**Comment by taiyang-li** [comment]
> @taiyang-li, the tests for Hive were flaky, and we don't use Hive, so we cannot fix them. But it could still be alright to merge this PR.

But the files this PR wants to change had been deleted from CH, like `tests/integration/test_hive_query`. Do you mean adding them to CH again ?

**Comment by taiyang-li** [comment]
> Let's add the change in one file, and omit the changes in tests.

done

**Review by alexey-milovidov — APPROVED** [review]

**Pull request merged**
