### PR TITLE
Replace old _shard_num implementation with shardNum() function

### PR DESCRIPTION
**Pull request by azat**
Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Replace `_shard_num` via constants (from #7624) with `shardNum()` function (from #27020), to avoid possible issues (like those that had been found in #16947)

Detailed description / Documentation draft:
This patch changes the behavior of _shard_num slightly for nested distributed tables,
now it returns nested shard number, but this should be minor.

Cc: @amosbird

### CODE REVIEW

**Comment by amosbird** [comment]
Yeah, functions are better than literals.

One test is broken.

```
SELECT 'remote(Distributed)';
SELECT _shard_num, key FROM remote('127.0.0.1', currentDatabase(), dist_2) order by _shard_num, key;
```

It seems the `shardNum()` answer is more reasonable : The definition of shard_num should be related to the related main table only without inheritance.

**Comment by azat** [comment]
>[Stateless tests (release, wide parts enabled, actions) — fail: 1, passed: 3718, skipped: 2](https://s3.amazonaws.com/clickhouse-test-reports/33392/1e9904555a482f3fb586a3174b5e42335db51678/stateless_tests__release__wide_parts_enabled__actions_.html)

- https://github.com/ClickHouse/ClickHouse/pull/33300#discussion_r781865970

**Comment by azat** [comment]
@alexey-milovidov can you please take a look?

**Review by KochetovNicolai — APPROVED** [review]

**Comment by KochetovNicolai** [comment]
I can't describe how I love this change.

**Comment by KochetovNicolai** [comment]
@mergifyio update

**Comment by azat** [comment]
>[Integration tests (release, actions) [2/2] — fail: 1, passed: 950, flaky: 0](https://s3.amazonaws.com/clickhouse-test-reports/33392/ad146a67ff5d03bfe2c1609d06ab421c718c7a4b/integration_tests__release__actions__[2/2].html)

- `test_consistent_parts_after_clone_replica` - #34057

**Pull request merged**
