### PR TITLE
Add bytes_uncompressed to system.part_log

### PR DESCRIPTION
**Pull request by jrdi**
### Changelog category (leave one):

- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Add `bytes_uncompressed` for all `system.part_log` entries. Also fixes values for merges since `(*merge_entry)->bytes_written_uncompressed` doesn't seem to report the right value.

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]
Looks perfect, thank you!

**Comment by robot-clickhouse-ci-1** [comment]
*This is an automated comment for commit 93b4d51d9f48a194b06ffcaf222d220900bfd1c8 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/58167/93b4d51d9f48a194b06ffcaf222d220900bfd1c8/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/58167/93b4d51d9f48a194b06ffcaf222d220900bfd1c8/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Comment by alexey-milovidov** [comment]
The new test is detected as flaky.

**Comment by jrdi** [comment]
> The new test is detected as flaky.

Yes, turns out providing exact size was not a good idea. I'll rewrite the test to don't rely on exact bytes.

**Pull request merged**
