### PR TITLE
Don't crash the server when Kafka consumers have failed to start

### PR DESCRIPTION
**Pull request by abyss7**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

For changelog. Remove if this is non-significant change.

Category (leave one):
- Bug Fix

### CODE REVIEW

**Comment by abyss7** [comment]
Fixes #5085

**Review by alesapin — APPROVED** [review]

**Review by alesapin — COMMENTED** [review]
Accidently approved

**Review by alexey-milovidov — CHANGES_REQUESTED** [review]
Have questions.

**Comment by alexey-milovidov** [comment]
Questionable. Still Ok to merge because you know better.

**Pull request merged**
