### PR TITLE
Save full server log in AST Fuzzer checks

### PR DESCRIPTION
**Pull request by tavplubix**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Review by alesapin — APPROVED** [review]
Better to rewrite these scripts completely and create a normal report as we have for all other checks.

**Comment by tavplubix** [comment]
Lol, now I get AccessDenied when I'm trying to do download server.log from an AST Fuzzer report, have no ideas why

**Comment by tavplubix** [comment]
Explaination: untrimmed `server.log` is quite big, so `s3_helper.py` decided to compress it and replace with `server.log.gz`. But AST Fuzzer report contains hardcoded link to `server.log` and of course this link became broken...

**Comment by tavplubix** [comment]
AST fuzzer (asan) - all logs are ok

**Pull request merged**
