### PR TITLE
Fix hung query when using empty tuple as lhs of function IN

### LINKED ISSUE #67293: Query hangs by tuple() and the IN operator
**Describe the bug**
Query hangs by tuple() and the IN operator.
It was detected by an in-development fuzzer of WINGFUZZ.

**How to reproduce**
The SQL statement to reproduce:
```sql
SELECT tuple() IN tuple(1)
```

The query will never stop. On my machine, it keeps running for over 10,000 seconds.

It can be reproduced on the official docker image. (clickhouse/clickhouse-server:head (version 24.8.1.473) and clickhouse/clickhouse-server:latest (version 24.6.2.17)).

**Note**
The `allow_experimental_analyzer` is enabled by default in the docker container. If I explicitly **disabled** the `allow_experimental_analyzer`, the server will correctly throw an exception for the syntax error.
```
SELECT tuple() IN tuple(1)
SETTINGS allow_experimental_analyzer = 0

Query id: 71fb6e30-72dc-4600-96ca-00b3abd6c312


Elapsed: 0.001 sec. 

Received exception from server (version 24.8.1):
Code: 124. DB::Exception: Received from localhost:9000. DB::Exception: Incorrect size of tuple in set: 1 instead of 0: While processing tuple() IN tuple(1). (INCORRECT_ELEMENT_OF_SET)
```

### PR DESCRIPTION
**Pull request by canhld94**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
- Fix hung query when using empty tuple as lhs of function IN

Close https://github.com/ClickHouse/ClickHouse/issues/67293

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by canhld94** [comment]
cc @amosbird

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
Amazing, thank you for finding and the fix!

**Comment by robot-ch-test-poll3** [comment]
*This is an automated comment for commit 13c93cc90cc35e33cad71095fa0300c5f4f1753e with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/67295/13c93cc90cc35e33cad71095fa0300c5f4f1753e/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

**Comment by alexey-milovidov** [comment]
@canhld94, tests have failed.

**Comment by canhld94** [comment]
@alexey-milovidov stress test failing with some logical error on replicated merge tree:
```
2024-07-28 18:33:26 Thread 778 "TCPHandler" received signal SIGABRT, Aborted.
2024-07-28 18:33:26 [Switching to Thread 0x7f12fd742640 (LWP 4989)]
2024-07-28 18:33:26 0x00007f15cc1e49fc in pthread_kill () from /lib/x86_64-linux-gnu/libc.so.6
2024-07-28 18:33:26 #0  0x00007f15cc1e49fc in pthread_kill () from /lib/x86_64-linux-gnu/libc.so.6
2024-07-28 18:33:26 No symbol table info available.
2024-07-28 18:33:26 #1  0x00007f15cc190476 in raise () from /lib/x86_64-linux-gnu/libc.so.6
2024-07-28 18:33:26 No symbol table info available.
2024-07-28 18:33:26 #2  0x00007f15cc1767f3 in abort () from /lib/x86_64-linux-gnu/libc.so.6
2024-07-28 18:33:27 No symbol table info available.
2024-07-28 18:33:27 #3  0x000000000c3f8993 in DB::abortOnFailedAssertion (description=..., trace=trace@entry=0x7f12fd727bd8, trace_offset=<optimized out>, trace_size=<optimized out>) at /build/src/Common/Exception.cpp:48
2024-07-28 18:33:27         logger = <optimized out>
2024-07-28 18:33:27 #4  0x000000000c3f8bac in DB::abortOnFailedAssertion (description=...) at /build/src/Common/Exception.cpp:54
2024-07-28 18:33:29         st = {static capacity = 45, size = 28, offset = 0, frame_pointers = {__elems_ = {0xc423d92 <StackTrace::tryCapture()+18>, 0xc3f8b95 <DB::abortOnFailedAssertion(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)+21>, 0x10ae4fa0 <DB::DatabaseReplicated::getConsistentMetadataSnapshotImpl(std::__1::shared_ptr<zkutil::ZooKeeper> const&, std::__1::function<bool (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)> const&, unsigned long, unsigned int&) const+6592>, 0x10ad13d0 <DB::DatabaseReplicated::dumpTablesInZooKeeperForDebugOnly() const+208>, 0x10ad72dd <DB::DatabaseReplicated::checkDigestValid(std::__1::shared_ptr<DB::Context const> const&, bool) const+2525>, 0x10ae8076 <DB::DatabaseReplicated::commitCreateTable(DB::ASTCreateQuery const&, std::__1::shared_ptr<DB::IStorage> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Context const>)+982>, 0x10a9d24d <DB::DatabaseOnDisk::createTable(std::__1::shared_ptr<DB::Context const>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::IStorage> const&, std::__1::shared_ptr<DB::IAST> const&)+1677>, 0x111a573f <DB::InterpreterCreateQuery::doCreateTable(DB::ASTCreateQuery&, DB::InterpreterCreateQuery::TableProperties const&, std::__1::unique_ptr<DB::DDLGuard, std::__1::default_delete<DB::DDLGuard> >&, DB::LoadingStrictnessLevel)+7487>, 0x1119fdb8 <DB::InterpreterCreateQuery::createTable(DB::ASTCreateQuery&)+12568>, 0x111a9bb2 <DB::InterpreterCreateQuery::execute()+530>, 0x115fc0f6 <DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum, DB::ReadBuffer*)+17654>, 0x115feb28 <DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, std::__1::shared_ptr<DB::Context>, std::__1::function<void (DB::QueryResultDetails const&)>, DB::QueryFlags, std::__1::optional<DB::FormatSettings> const&, std::__1::function<void (DB::IOutputFormat&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Context const> const&, std::__1::optional<DB::FormatSettings> const&)>)+936>, 0x10dadc1c <DB::DDLWorker::tryExecuteQuery(DB::DDLTaskBase&, std::__1::shared_ptr<zkutil::ZooKeeper> const&)+828>, 0x10dac03e <DB::DDLWorker::processTask(DB::DDLTaskBase&, std::__1::shared_ptr<zkutil::ZooKeeper> const&)+3934>, 0x10af9738 <DB::DatabaseReplicatedDDLWorker::tryEnqueueAndExecuteEntry(DB::DDLLogEntry&, std::__1::shared_ptr<DB::Context const>)+2456>, 0x10ad8826 <DB::DatabaseReplicated::tryEnqueueReplicatedDDL(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context const>, DB::QueryFlags)+1542>, 0x1119fc19 <DB::InterpreterCreateQuery::createTable(DB::ASTCreateQuery&)+12153>, 0x111a9bb2 <DB::InterpreterCreateQuery::execute()+530>, 0x115fc0f6 <DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum, DB::ReadBuffer*)+17654>, 0x115f78dd <DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum)+189>, 0x1286c75b <DB::TCPHandler::runImpl()+3099>, 0x12881c79 <DB::TCPHandler::run()+25>, 0x1609a267 <Poco::Net::TCPServerConnection::start()+7>, 0x1609a73e <Poco::Net::TCPServerDispatcher::run()+286>, 0x16047052 <Poco::PooledThread::run()+178>, 0x16044d63 <Poco::ThreadImpl::runnableEntry(void*)+131>, 0x7f15cc1e2ac3, 0x7f15cc274850, 0x0 <repeats 17 times>}}}
2024-07-28 18:33:29 #5  0x0000000010ae4fa0 in DB::DatabaseReplicated::getConsistentMetadataSnapshotImpl(std::__1::shared_ptr<zkutil::ZooKeeper> const&, std::__1::function<bool (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)> const&, unsigned long, unsigned int&) const (this=this@entry=0x7f133af11018, zookeeper=..., filter_by_table_name=..., max_retries=max_retries@entry=10, max_log_ptr=@0x7f12fd7280bc: 32531) at /build/src/Databases/DatabaseReplicated.cpp:1414
2024-07-28 18:33:29         escaped_table_names = {__begin_ = 0x7f132858f900, __end_ = 0x7f132858fb88, __end_cap_ = {<std::__1::__compressed_pair_elem<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*, 0, false>> = {__value_ = 0x7f132858fb88}, <std::__1::__compressed_pair_elem<std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, 1, true>> = {<std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >> = {<std::__1::__non_trivial_if<true, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >> = {<No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}}
2024-07-28 18:33:29         futures = {__begin_ = 0x7f147b5e0b60, __end_ = 0x7f147b5e0c38, __end_cap_ = {<std::__1::__compressed_pair_elem<std::__1::future<Coordination::GetResponse>*, 0, false>> = {__value_ = 0x7f147b5e0c38}, <std::__1::__compressed_pair_elem<std::__1::allocator<std::__1::future<Coordination::GetResponse> >, 1, true>> = {<std::__1::allocator<std::__1::future<Coordination::GetResponse> >> = {<std::__1::__non_trivial_if<true, std::__1::allocator<std::__1::future<Coordination::GetResponse> > >> = {<No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}}
2024-07-28 18:33:29         new_max_log_ptr = 55
2024-07-28 18:33:29         table_name_to_metadata = {__tree_ = {__begin_node_ = 0x7f133fa4d9d0, __pair1_ = {<std::__1::__compressed_pair_elem<std::__1::__tree_end_node<std::__1::__tree_node_base<void*>*>, 0, false>> = {__value_ = {__left_ = 0x0}}, <std::__1::__compressed_pair_elem<std::__1::allocator<std::__1::__tree_node<std::__1::__value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, void*> >, 1, true>> = {<std::__1::allocator<std::__1::__tree_node<std::__1::__value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, void*> >> = {<std::__1::__non_trivial_if<true, std::__1::allocator<std::__1::__tree_node<std::__1::__value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, void*> > >> = {<No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}, __pair3_ = {<std::__1::__compressed_pair_elem<unsigned long, 0, false>> = {__value_ = 0}, <std::__1::__compressed_pair_elem<std::__1::__map_value_compare<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::__value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, true>, 1, true>> = {<std::__1::__map_value_compare<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::__value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, true>> = {<std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >> = {<std::__1::binary_function<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, bool>> = {<No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}}}
2024-07-28 18:33:29         iteration = 1
2024-07-28 18:33:29 #6  0x0000000010ad13d0 in DB::DatabaseReplicated::tryGetConsistentMetadataSnapshot (this=0x7f133af11018, zookeeper=..., max_log_ptr=@0x7f12fd7280bc: 32531) at /build/src/Databases/DatabaseReplicated.cpp:1369
2024-07-28 18:33:29 No locals.
2024-07-28 18:33:29 #7  DB::DatabaseReplicated::dumpTablesInZooKeeperForDebugOnly (this=this@entry=0x7f133af11018) at /build/src/Databases/DatabaseReplicated.cpp:696
```

I think same for stateless test. All test passes but server died in the end with error related to replicated engine:

```
2024-07-28 18:35:40 Thread 646 "Common" received signal SIGABRT, Aborted.
2024-07-28 18:35:40 [Switching to Thread 0x7fa5622ce640 (LWP 1564)]
2024-07-28 18:35:40 0x00007fa7c1aaa9fc in pthread_kill () from /lib/x86_64-linux-gnu/libc.so.6
2024-07-28 18:35:40 #0  0x00007fa7c1aaa9fc in pthread_kill () from /lib/x86_64-linux-gnu/libc.so.6
2024-07-28 18:35:40 No symbol table info available.
2024-07-28 18:35:40 #1  0x00007fa7c1a56476 in raise () from /lib/x86_64-linux-gnu/libc.so.6
2024-07-28 18:35:40 No symbol table info available.
2024-07-28 18:35:40 #2  0x00007fa7c1a3c7f3 in abort () from /lib/x86_64-linux-gnu/libc.so.6
2024-07-28 18:35:40 No symbol table info available.
2024-07-28 18:35:40 #3  0x000000000c3f8993 in DB::abortOnFailedAssertion (description=..., trace=<optimized out>, trace_offset=trace_offset@entry=0, trace_size=<optimized out>) at /build/src/Common/Exception.cpp:48
2024-07-28 18:35:40         logger = <optimized out>
2024-07-28 18:35:40 #4  0x000000000c3f9454 in DB::handle_error_code (msg=..., code=49, trace=..., remote=<optimized out>) at /build/src/Common/Exception.cpp:71
2024-07-28 18:35:42 No locals.
2024-07-28 18:35:42 #5  DB::Exception::Exception (this=0x7fa6b0502080, msg_masked=..., code=49, remote_=<optimized out>) at /build/src/Common/Exception.cpp:115
2024-07-28 18:35:42 No locals.
2024-07-28 18:35:42 #6  0x0000000006dff14c in DB::Exception::Exception (this=0x7fa6b0502080, msg=..., code=49, remote_=false) at /build/src/Common/Exception.h:110
2024-07-28 18:35:42 No locals.
2024-07-28 18:35:42 #7  DB::Exception::Exception (this=0x7fa6b0502080, msg=..., code=49) at /build/src/Common/Exception.h:63
2024-07-28 18:35:42 No locals.
2024-07-28 18:35:42 #8  0x000000001204486b in DB::Exception::Exception<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&> (this=this@entry=0x7fa6b0502080, code=49, fmt=..., args=..., args=..., args=...) at /build/src/Common/Exception.h:128
2024-07-28 18:35:49 No locals.
2024-07-28 18:35:49 #9  0x0000000011f9358b in DB::paranoidCheckForCoveredPartsInZooKeeper (zookeeper=..., replica_path=..., format_version=..., covering_part_name=..., storage=...) at /build/src/Storages/StorageReplicatedMergeTree.cpp:2403
```

**Comment by canhld94** [comment]
Failed stress test:

```
/var/log/clickhouse-server/clickhouse-server.err.log:2024.07.29 09:46:50.282909 [ 6212 ] {e6b2590e-e4a2-4726-876f-5e2521148dec} <Fatal> : Logical error: 'Expected the argument №2 ('_CAST(NULL_Nullable(String), 'Nullable(String)'_String)' of type Nullable(String)) to have 2 rows, but it has 0'.
/var/log/clickhouse-server/clickhouse-server.err.log:2024.07.29 09:46:50.620946 [ 6212 ] {e6b2590e-e4a2-4726-876f-5e2521148dec} <Fatal> : Stack trace (when copying this message, always include the lines below):
/var/log/clickhouse-server/clickhouse-server.err.log:2024.07.29 09:47:25.695388 [ 3313 ] {} <Fatal> Application: Child process was terminated by signal 6.
/var/log/clickhouse-server/clickhouse-server.stress.log:2024.07.29 09:46:50.282909 [ 6212 ] {e6b2590e-e4a2-4726-876f-5e2521148dec} <Fatal> : Logical error: 'Expected the argument №2 ('_CAST(NULL_Nullable(String), 'Nullable(String)'_String)' of type Nullable(String)) to have 2 rows, but it has 0'.
/var/log/clickhouse-server/clickhouse-server.stress.log:2024.07.29 09:46:50.620946 [ 6212 ] {e6b2590e-e4a2-4726-876f-5e2521148dec} <Fatal> : Stack trace (when copying this message, always include the lines below):
/var/log/clickhouse-server/clickhouse-server.stress.log:2024.07.29 09:47:25.695388 [ 3313 ] {} <Fatal> Application: Child process was terminated by signal 6.
```

Broken in master https://github.com/ClickHouse/ClickHouse/issues/67330

**Pull request merged**
