### PR TITLE
Fix/sum map overflow

### LINKED ISSUE #2355: questions about sumMap function
Hi,

I have some questions about the sumMap function.
I was first sending a mail to @vavrusa and @bocharov who wrote this function but it's better to write an issue so that it can be useful to other people.

I'm leading the migration of our data infrastructure to Clickhouse and I'm using the sumMap function for one of the features of my company (we're building an analytics tool). It gives very good performance (up to 3 time faster than the same query without sumMap) so many thanks to you guys for this awesome function.

However, I have 2 questions/remarks:
- The first question is about overflow for the result of this function:
If I use sumMap(key,value) where value is an UInt8 or an UInt16, the function will give a result as an UInt8/UInt16 and it will overflow since I'm using sumMap on more than 200 millions rows.
I could store the value field as an UInt64 (with a small storage overhead) or cast the value as an UInt64 (with a small processing overhead) but I was wandering if there is a better way to deal with overflow.

- The second question is about high cardinality keys:
The sumMap function is fast as long as the number of distinct keys is small. I ran some benchmarks and I was having huge performance issues when there were millions of distinct keys (on 6 Amazon i3.8xl instances). One of the solutions I thought about would be to have a "sumMapWithFilter" function that would sum only the keys specified on the filter clause. Before starting to work on this function, I was wondering if you have this kind of problems at Cloudflare and if this kind of function was on your roadmap.

### PR DESCRIPTION
**Pull request by LeoErcolanelli**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

For changelog. Remove if this is non-significant change.

Category (leave one):
- Bug Fix

Short description (up to few sentences):
`sumMap` now relies on `NearestFieldType` in order to define which types will be returned for the summed columns.

Detailed description (optional):
Until now, `sumMap` used to return summed columns with the same types than the input columns. It means that in the case of input columns being `Array(UInt8)` overflows were a common occurrence.
In order to fix that, this PR introduces a change at the `IDataType` level with 2 new virtual methods:
* `canBePromoted` defines if a `promoteNumericType` will throw an exception when called
* `promoteNumericType` returns a promoted `DataTypePtr` according to the logic in `AggregateFunctionSum.cpp`:
    * `Decimal128` for `Decimal` types
    * `NearestFieldType<T>` for `Numeric` types.

~As of today `canBeWiden` returns `true` (and `getWidenDataType` doesn't throw) only for `DataTypeDecimal` and `DataTypeNumber`. I am still unsure whether it should also be implemented for all the types subclassing `DataTypeNumberBase` which are:~
* ~`DataTypeDate`~
* ~`DataTypeDateTime`~
* ~`DataTypeInterval`~
* ~`DataTypeUUID`~

**EDIT:** renaming "widen" to "promote" makes it more self-explanatory as to why it isn't implemented for those types.

Let me know what you think!

Together with https://github.com/yandex/ClickHouse/pull/4129 it can close https://github.com/yandex/ClickHouse/issues/2355.

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
> As of today canBeWiden returns true (and getWidenDataType doesn't throw) only for DataTypeDecimal and DataTypeNumber. I am still unsure whether it should also be implemented for all the types

If we name the method `promoteNumericType` instead of `getWidenDataType`, no question exists.
("type promotion" is a widely used term)

**Comment by ercolanelli-leo** [comment]
@alexey-milovidov Looks good to me ! I'll rename `canBeWiden` to `canBePromoted` and `getWidenType` to `promoteNumericType`!

**Comment by ercolanelli-leo** [comment]
@alexey-milovidov I did the renaming but I am not sure as to why the test `00446_clear_column_in_partition_zookeeper` is failing. It appears that there is no use of `sumMap` in this test that could explain it failing. Are you aware of this issue?

**Comment by alexey-milovidov** [comment]
I need to clarify something.

We have aggregate functions `sum` and `sumWithOverflow`.
`sum` does summation in promoted type.
`sumWithOverflow` does summation with overflow within the range of its argument.

Also we have aggregate function `sumMap` but not `sumMapWithOverflow`.
Before your modifications, `sumMap` had overflow behaviour.
After your modifications, `sumMap` do summation in promoted type.

So, your modifications made the behaviour of `sumMap` function more consistent that is good!

Also we have `SummingMergeTree` table engine and `SummingSortedBlockInputStream` for its implementation. `SummingSortedBlockInputStream` creates aggregate functions to perform calculations. These aggregate functions must return the same data type as the argument (do summation with overflow), because they used to sum data within table columns.

It is used `sumWithOverflow` function to sum scalar values and `sumMap` function to sum maps.
Before your changes, both aggregate functions performed summation with overflow.
After your changes, the logic will break.

See also:
1. https://github.com/yandex/ClickHouse/issues/1975#issuecomment-370033408
2. https://github.com/yandex/ClickHouse/pull/1367

To complete this pull request, you have to add two more changes:
1. Implement aggregate function `sumMapWithOverflow` that behave as old `sumMap`.
2. Use it instead of `sumMap` in `SummingSortedBlockInputStream`.

**Comment by ercolanelli-leo** [comment]
@alexey-milovidov I hesitated implementing `sumMapWithOverflow` but as I didn't know at all about `SummingSortedBlockInputStream` I had no idea it was so crucial! Everything should be implemented now.

Thank you very much for your explanations and reactivity, it is a pleasure contributing to the project!

**Pull request merged**
