### PR TITLE
Do not ignore server memory limits during Buffer flush

### PR DESCRIPTION
**Pull request by azat**
Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Do not ignore server memory limits during Buffer flush

Detailed description / Documentation draft:
Before this patch Buffer engine always ignores the memory limit during
writing to destination table (since #7552).

### CODE REVIEW

**Comment by azat** [comment]
The test fails now because of the text_log, each text_log/query_log/... entry blocks the memory tracking in the thread, however it is not nested and hence after message in the log the memory tracker is not blocked anymore.

This should be fixed in #17658.
Will rebase this PR once it will be merged.

**Comment by alexey-milovidov** [comment]
What was the initial motivation to ignore memory limit in buffer flush?

**Comment by azat** [comment]
>What was the initial motivation to ignore memory limit in buffer flush?

@alexey-milovidov Buffer have two different modes of flushing:
- direct
- background

And in pre #7552 direct flush is accounted for max_memory_usage (and similar) per-query settings, but background does not affected by them anyhow, so it was blocked to avoid accounting this memory for direct flush in that PR.

But sometimes it is too much (in case you have some MV attached to the underlying table), and it is better at least to have some control over this.

**Comment by alexey-milovidov** [comment]
I remember: we disable memory tracking for direct flush, because the data volume is unrelated to the INSERT query:
e.g. you have INSERTed one record, but buffer with million of records will be flushed and it will be over memory limit.

**Comment by azat** [comment]
>I remember: we disable memory tracking for direct flush, because the data volume is unrelated to the INSERT query:

Yes, this is also a good example

**Comment by azat** [comment]
Rebased against upstream/master (to include #17658)

**Comment by alexey-milovidov** [comment]
So, why make the setting 0 by default?

**Comment by alexey-milovidov** [comment]
Maybe you want something more sophisticated:
- ignore per-query and per-user memory limits;
- still respect server total memory limit?

**Comment by azat** [comment]
>So, why make the setting 0 by default?

To avoid hiding possible problems, to me it sounds like it is better to show memory limit error instead of using lots of of RAM and eventually fail in another place.
Since it is way more cleaner to answer the question "why INSERT into Buffer fails with memory limit exceeded" instead of "why my server uses too much memory" (or similar)

>Maybe you want something more sophisticated:

Yes

>still respect server total memory limit?

Good idea, yes, total limit should not be ignored for this case.

**Comment by alexey-milovidov** [comment]
BTW, I don't like to introduce a new setting for every implementation detail.
But as the initial behaviour of ignoring memory limit in Buffer was introduced by you, I'm also Ok with this change.

Does this change reasonably motivated? (by some behaviour observed in production?)

**Comment by azat** [comment]
>BTW, I don't like to introduce a new setting for every implementation detail.

Me neither

>Does this change reasonably motivated? (by some behaviour observed in production?)

Yes, one Buffer table was pushed to the table, that has MV attached, with pretty heavy aggregation (but it wasn't look heavy at first) that requires 30+GB, and it pushes data directly.
And it is not that easy to understand how much memory does the that query uses, since the memory tracker was completely disabled for INSERT into Buffer table (and obviously no logs from MemoryTracker, only after total was synced with RSS)

How about using LockExceptionInThread instead, and:
- add a scope into that locker (to avoid locking exceptions from total memory tracker)
- add an option to throw in case of fault injection (since it is absolutely fine to throw in this case from Buffer)

Thus all tracking will be done, but w/o talking max_memory_usage (and similar) setting into account, but you will see these memory as accounted for query and in logs (during peak updates).

But I would still prefer to leave this setting (and I'm fine with either default, although 0 looks better to me), and I'm not sure that max_memory_usage_for_user should be ignored, what if this setting has been set by some administrator with constraints

**Comment by azat** [comment]
Ok, I did the following:
- Add level for BlockerInThread/LockExceptionInThread to make decisions based on the level
- Add block_fault_injections for LockExceptionInThread
- use LockExceptionInThread in StorageBuffer w/o blocking faulty injections
- keep buffer_ignore_memory_limits_on_flush setting
- keep default value for buffer_ignore_memory_limits_on_flush 1

**Comment by azat** [comment]
Actually [failed `01278_min_insert_block_size_rows_for_materialized_views`](https://clickhouse-test-reports.s3.yandex.net/17646/2777cbe2e055f4632b0a1ec866b9a723e9e798e5/fast_test.html#fail1) shows that the memory limits should be ignored, not just exception blocked, since otherwise it will bail on the next allocation

*P.S. Although looks like memory tracking changes should be done in another PR*

**Comment by azat** [comment]
Fixed few typos and rebased

**Comment by filimonov** [comment]
I don't like the proposed setting. 

For me it sounds like flush from buffer should happen in context/profile of another user (system_profile?). And that flush should be registered in query_log separately from insert into buffer table.

So we actually dealing with 2 inserts. Tiny and cheap insert into buffer, and heavy and slow into underlying table triggered by first one.

**Comment by azat** [comment]
>For me it sounds like flush from buffer should happen in context/profile of another user (system_profile?).

There is direct flush and background, direct is done in context of current query, yes this is tricky to track all those flushes, but this may be useful, and at least if buffer is full, then the query should be blocked to avoid using more memory (and scheduling it to the background thread and wait from the query does not sounds right)

>And that flush should be registered in query_log separately from insert into buffer table.

This is a separate issue in a different place (I have this in my todo list, but it requires some time)

**Comment by azat** [comment]
@alexey-milovidov I've changed the default to 1 (to avoid behavior changes).

I would prefer to leave the setting, but if you still think that this does not worth it (actually I don't like lots of settings either, that said that when it can be done automatically - it should be done that way) I guess I can use per-user memory limits to limit memory during Buffer flush.

**Comment by azat** [comment]
I've reworked this patches, `buffer_ignore_memory_limits_on_flush` had been replaced with `buffer_memory_context` that is set to `Global`, i.e. ignore any memory limits (as before).

This setting control in which context Buffer will flush it's buffer:
- Query - do not ignore anything
- User - ignore query limits, i.e. work from user context
- Server - ignore user limits, i.e. work from server context
- Global - ignore any memory limits

Also note that it contains some refactoring patches for memory tracking, in particular:
- split out CurrentMemoryTracker into separate header, since it is required by Allocator.h, which is required by PODArray.h and it is included into almost every clickhouse header (directly or indirectly)
- Extend BlockerInThread/LockExceptionInThread interface, to respect level (Global/User/Process/Thread)

**Comment by azat** [comment]
@alexey-milovidov can you take a look please?

**Comment by alexey-milovidov** [comment]
> Global - ignore any memory limits

BTW, why it's named "Global" (not something like "None")? It can be mistaken with server context.

**Comment by alexey-milovidov** [comment]
It is for "memory tracker blocked" and means "block everything"?

**Comment by alexey-milovidov** [comment]
I have strange feeling that it's overengineered. So we are going to introduce a settings that is difficult to use. And it is only for Buffer tables that we are going to make obsolete.

But the changes to memory tracked blocker are reasonable. Maybe don't introduce any settings to Buffer engine but just stick to "ignore for query and user level but respect server level limits"?

**Comment by azat** [comment]
>BTW, why it's named "Global" (not something like "None")? It can be mistaken with server context.

By analogy from the VariableContext, but agree, None sounds better.

>It is for "memory tracker blocker" and means "block everything"?

Yes (for particular level, where level User/Query/...)

> But the changes to memory tracker blocker are reasonable. Maybe don't introduce any settings to Buffer engine but just stick to "ignore for query and user level but respect server level limits"?

The problem here is that there are still some corner cases left when the memory tracking is not accurate (especially with multiple queries in parallel), so it will be nice to have ability to ignore even server limits. Although this will indeed make Buffer engine special

OK, I will drop the setting. Will get back with rebased patches.

**Review by alexey-milovidov — APPROVED** [review]

**Pull request merged**
