### PR TITLE
Align branches within a 32B boundary to make benchmark more stable

### PR DESCRIPTION
**Pull request by guowangy**
### Changelog category (leave one):
- Build/Testing/Packaging Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Align branches within a 32B boundary to make benchmark more stable

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by guowangy** [comment]
reference: https://www.intel.com/content/www/us/en/developer/articles/technical/software-security-guidance/best-practices/mitigation-strategies-jcc-microcode.html

**Comment by danlark1** [comment]
This can significantly increase the build size for an already enormous ClickHouse binary

**Comment by guowangy** [comment]
From my local build, for `programs/clickhouse`, only 0.21% size increases:
* Binary size change ratio: 2030389064/2026047584 = 1.0021
* 4.14 MB binary size increase

**Comment by danlark1** [comment]
This should be fine then

**Comment by alexey-milovidov** [comment]
Performance improved by 1..1.5% on x86 and by 0..0.6% on ARM.

The only strange result is in "distinct in order optimization", but it's a new addition, so most likely the difference is not related to this change.

**Review by alexey-milovidov — APPROVED** [review]

**Comment by danlark1** [comment]
Arm cannot show improvements with that :)

**Comment by TianyouLi** [comment]
> Performance improved by 1..1.5% on x86 and by 0..0.6% on ARM.
> 
> The only strange result is in "distinct in order optimization", but it's a new addition, so most likely the difference is not related to this change.

Thanks @alexey-milovidov for sharing the performance improvement number. Could I ask an dumb question if there already have the information in the test log? I am interested with what kinds of workloads we can use to evaluate the performance improvement number.  By saying improvement about ~1.5% on x86 and ~0.6% on ARM,  where could I find the platform information which generation/model of x86 or arm? 

Thanks in advance for any of your response:)

**Comment by alexey-milovidov** [comment]
It's in the details of the Performance Comparison check:

Screenshot_20220712_114849

**Comment by alexey-milovidov** [comment]
And total percentage is from here: 

photo_2022-06-14_16-28-03

**Comment by alexey-milovidov** [comment]
And the total percentage is from here:

Screenshot_20220712_115226

**Comment by guowangy** [comment]
@alexey-milovidov 
We have already signed CCLA and just sent it to ClickHouse. I expect it should take some time to take effect.

**Comment by alexey-milovidov** [comment]
Ok.

**Comment by TianyouLi** [comment]
> And the total percentage is from here:
> 
> Screenshot_20220712_115226

Very appreciated @alexey-milovidov for your detailed explainations. It's definitely helpful. May I find the hardware platform information from the test report you pointed? Thanks.

**Comment by guowangy** [comment]
@alexey-milovidov 
CLA status is OK now.

**Comment by alexey-milovidov** [comment]
It's from AWS, most likely the machines with AMD.

**Comment by alexey-milovidov** [comment]
@guowangy

> Intel(R) Xeon(R) Platinum 8124M CPU @ 3.00GHz

It's in the log of Performance Test.

**Comment by TianyouLi** [comment]
> @guowangy
> 
> > Intel(R) Xeon(R) Platinum 8124M CPU @ 3.00GHz
> 
> It's in the log of Performance Test.

Got it! Thanks Alexey for your kindness response.

**Pull request merged**
