### PR TITLE
Increase the log level of deduplication data

### PR DESCRIPTION
**Pull request by helifu**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Increase the log level of deduplication data from 'info' to 'warning'.

### CODE REVIEW

**Comment by rschu1ze** [comment]
Just wondering if "Block with ID {} already exists as part {}; ignoring it" indicates an event which is handled internally without creating any issues of any kind (e.g. performance degradation). In that case, level "info" may be more appropriate. If it represents an event with impact on operations (e.g. waste of disk space) and the user/admin should be made aware so that he/she may react, then level "warning" is more appropriate. Perhaps you could clarify.

(asking because we should avoid alarming administrators needlessly by printing too much "warning"-level log messages)

**Comment by helifu** [comment]
> 

@rschu1ze Thanks for your info, I agree with you.
Here the log level adjustment is to warn the users that the second execution of the same write(insert) statement is ignored while the dedup is open. No one pays attention to info level logs.

**Comment by rschu1ze** [comment]
Test `01781_merge_tree_deduplication` fails with the newly promoted log message (check "PullRequestCI / FastTest"). Would you like to run it locally and adjust it so that it no longer fails? Thanks!

**Comment by rschu1ze** [comment]
Closing for housekeeping reasons. Please reopen if there is interest in continuing this PR.

**Pull request closed without merging**
