### PR TITLE
Revert "Merge pull request #52395 from azat/rust/reproducible-builds"

### PR DESCRIPTION
**Pull request by Felixoid**
This reverts commit 4f5096c921d4dfa734fd76aef8842c49bfa618d9, reversing changes made to 13ca31edd4970466967fae15c0fa12d5d004efb8.

Docker complains that `tar | docker buildx build --cache-to=... -` causes overbloated config blob. Let's try to fix the latest place where it remains

### CODE REVIEW

**Comment by robot-ch-test-poll4** [comment]
This is an automated comment for commit fc33f05cb36c3e3ce78649db5bacfb110f970cf7 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/55517/fc33f05cb36c3e3ce78649db5bacfb110f970cf7/ci_running.html)
The overall status of the commit is 🟢 success

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>Push to Dockerhub</td><td>The check for building and pushing the CI related docker images to docker hub</td><td>🟢 success</td></tr>
</table>

**Comment by alexey-milovidov** [comment]
What exactly does it, in simple language?

**Comment by Felixoid** [comment]
Somehow the `tar | docker buildx build -` causes bad special effects on docker image config blob. Details are in an email I've redirected to you.

I think, it's safe to merge already

**Comment by Felixoid** [comment]
In 23.8 it's fixed by implementing completely another way to handle the cargo cache. It's too hard to fix it properly, so I discussed it with @azat in telegram, and it's a decent way to have the images with fixed `config` manifest section.

**Pull request merged**
