### PR TITLE
[DRAFT] RAID 1

### PR DESCRIPTION
**Pull request by NanoBjorn**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- New Feature

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

...

Detailed description / Documentation draft:

...

By adding documentation, you'll allow users to try your new feature immediately, not when someone else will have time to document it later. Documentation is necessary for all features that affect user experience in any way. You can add brief documentation draft above, or add documentation right into your patch as Markdown files in [docs](https://github.com/ClickHouse/ClickHouse/tree/master/docs) folder.

If you are doing this for the first time, it's recommended to read the lightweight [Contributing to ClickHouse Documentation](https://github.com/ClickHouse/ClickHouse/tree/master/docs/README.md) guide first.

### CODE REVIEW

**Review by alesapin — COMMENTED** [review]
Semantically idea is clear to me, but I think the current implementation is too complicated. Different part reader and part writer for each `raid type * part type` seems cumbersome. We should try to move raid write/read logic to separate classes with their own hierarchy. `MergeTreeDataPart*Writer/MergeTreeDataPart*Reader` will use them for low-level operations (like `writeSingleGranule` or `writeSingleMark`).

**Comment by NanoBjorn** [comment]
Do not forget to fix doc for `system.storage_policies`

**Comment by excitoon** [comment]
Superseded by #12270

**Comment by alesapin** [comment]
> Superseded by #12270#11883

Ok, can be closed.

**Pull request closed without merging**
