### PR TITLE
Use `SharedMutex` instead of `UpgradableMutex`

### PR DESCRIPTION
**Pull request by serxa**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by serxa** [comment]
I hope `relocation R_X86_64_32S` is now fixed, so I'll just update the branch

**Comment by KochetovNicolai** [comment]
So, a few queries from
https://s3.amazonaws.com/clickhouse-test-reports/49139/c43a0f2ee1e4a11ab839eb380c50e70931096315/performance_comparison_[1/4]/report.html
(hash_table_sizes_stats_small) and 
and one from https://s3.amazonaws.com/clickhouse-test-reports/49139/c43a0f2ee1e4a11ab839eb380c50e70931096315/performance_comparison_[4/4]/report.html
are suspicious.

Let's check if they flaky or degraded

**Comment by KochetovNicolai** [comment]
also, let's try full perftest run

**Comment by serxa** [comment]
I checked 2 suspicious performance tests with benchmark tool and found nothing interesting:
1) `select number from numbers_mt(3000000) group by number format Null` https://pastila.nl/?019cfc45/2b528744a020b8f4c52c8913c7f35c9d
2) `SELECT count() FROM test_in_skip_idx WHERE s IN (SELECT toString(number + 10000000) FROM numbers(100000)) SETTINGS use_skip_indexes = 0` https://pastila.nl/?050d94c6/dd6d97a6c7c571e5e62c6776e25c716b

Actually, results are changing quite significantly from run to run, so I cannot definitely say that there is a performance difference or say that there is no performance difference. But performances are very close, so I think we can deal with tests and maybe merge this PR.

**Comment by serxa** [comment]
00155_long_merges - flaky
01442_merge_detach_attach_long - flaky
01320_create_sync_race_condition_zookeeper - flaky https://github.com/ClickHouse/ClickHouse/issues/49230

**Pull request merged**
