### PR TITLE
Release pull request for branch 19.14

### PR DESCRIPTION
**Pull request by robot-clickhouse**
This PullRequest is part of ClickHouse release cycle. It's used by CI system only. Don't perform any changes with it.

### CODE REVIEW

**Comment by CurtizJ** [comment]
Accidentally backported fix for feature, that is missing in 19.14.

**Comment by CurtizJ** [comment]
Failed tests with memory sanitizer are ok, because they were inroduced only in 19.15.

**Comment by alesapin** [comment]
Failed test depend on unimplemented feature.

**Comment by alesapin** [comment]
Ok, release tests passed except `02000_optimize_skip_unused_shards_type_mismatch`. It's ok.

**Comment by alexey-milovidov** [comment]
Support period for version 19.14 LTS has been ended.

**Pull request closed without merging**
