### PR TITLE
clustercopier.cpp file splitting

### PR DESCRIPTION
**Pull request by nikitamikhaylov**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Non-significant (changelog entry is not needed)

Changelog entry (up to few sentences, required except for Non-significant/Documentation categories):
Needed for #9075 (to see normal diff)

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
staff vs stuff

**Comment by nikitamikhaylov** [comment]
both are appropriate, but stuff is slang and quite rude

**Comment by alexey-milovidov** [comment]
Style check...

**Comment by nikitamikhaylov** [comment]
I know :) They are not mine.

**Comment by nikitamikhaylov** [comment]
`Build failed without build log. It's inner CI problem. Maybe something wrong with docker or host. Just wait for build restart.` The last commit is only style improvements. Other test are broken in master.

**Pull request merged**
