### PR TITLE
Fixed handling of server-side encryption customer keys

### LINKED ISSUE #37943: Server-side encryption with customer key does not work for multi-part uploads in S3
Server-side encryption with customer key does not work for multi-part uploads in S3. Also, customer key appears in unrelated requests like `DeleteObject`, `DeleteObjects`, `ListObjectsV2`, `CreateMultipartUpload`, `UploadPart`, `UploadPartCopy`, `CompleteMultipartUpload`, `AbortMultipartUpload`.

### PR DESCRIPTION
**Pull request by excitoon**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in official stable or prestable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fixed wrong handling of server-side encryption customer keys in S3.

I had to separate making requests into new class `S3::Client` in order to add required settings to them.

Fixes #37943

### CODE REVIEW

**Comment by excitoon** [comment]
For multi-part uploads we shall first upload an object without a key and then copy object to its destination, specifying a key for destination.

**Comment by excitoon** [comment]
At this point client sends all required headers in proper requests, but still misses functionality of copying object after multi-part upload.

**Comment by alexey-milovidov** [comment]
Looks abandoned.

**Comment by excitoon** [comment]
Yes, I need a reviewer so much.

**Comment by alexey-milovidov** [comment]
There are conflicts, please resubmit the PR.

**Pull request closed without merging**
