### PR TITLE
Remove a feature

### LINKED ISSUE #47579: Incorrect values insertion into the `is_deleted` column of new ReplacingMergeTree engine
Disabling the `optimize_on_insert` setting can result in the insertion in a ReplacingMergeTree table of incorrect data into the `is_deleted` column. As a consequence, running `SELECT ... FINAL` queries on the inserted tables leads to an exception.

https://fiddle.clickhouse.com/17113269-e156-4cd3-b00c-6622050c15b9

**How to reproduce:**

ClickHouse version 23.2
```
CREATE TABLE default.test
(
    `id` String,
    `version` UInt32,
    `is_deleted` UInt8
)
ENGINE = ReplacingMergeTree(version, is_deleted)
ORDER BY id
SETTINGS index_granularity = 8192

SET optimize_on_insert=0;

INSERT INTO test VALUES ('data1', 1, '6');

SELECT * from test FINAL

```
**Result:**
Received exception from server (version 23.2.3):
Code: 117. DB::Exception: Received from localhost:9000. DB::Exception: Incorrect data: is_deleted = 6 (must be 1 or 0).: While executing ReplacingSorted. (INCORRECT_DATA)

### LINKED ISSUE #50346: ReplacingMergeTree with `is_deleted` column and `clean_deleted_rows=Always` works incorrectly
```
dell9510 :) CREATE TABLE test (uid String, version UInt32, is_deleted UInt8) ENGINE = ReplicatedReplacingMergeTree('/test/jhbsavk', '1', version, is_deleted) Order by (uid) settings clean_deleted_rows='Always';

dell9510 :) CREATE TABLE test2 (uid String, version UInt32, is_deleted UInt8) ENGINE = ReplicatedReplacingMergeTree('/test/jhbsavk', '2', version, is_deleted) Order by (uid) settings clean_deleted_rows='Always';

dell9510 :) system stop replicated sends test2

dell9510 :) insert into test values (1, 1, 0)
dell9510 :) insert into test2 values (2, 1, 0)
dell9510 :) insert into test values (1, 2, 0)
dell9510 :) insert into test values (1, 3, 1)

dell9510 :) select *, _part from test

┌─uid─┬─version─┬─is_deleted─┬─_part─────┐
│ 1   │       2 │          0 │ all_2_2_0 │
└─────┴─────────┴────────────┴───────────┘
┌─uid─┬─version─┬─is_deleted─┬─_part─────┐
│ 1   │       3 │          1 │ all_3_3_0 │
└─────┴─────────┴────────────┴───────────┘
┌─uid─┬─version─┬─is_deleted─┬─_part─────┐
│ 1   │       1 │          0 │ all_0_0_0 │
└─────┴─────────┴────────────┴───────────┘

3 rows in set. Elapsed: 0.020 sec. 

dell9510 :) select * from test final

Ok.

0 rows in set. Elapsed: 0.019 sec. 

dell9510 :) optimize table test

Ok.

0 rows in set. Elapsed: 0.035 sec. 

dell9510 :) select * from test final

┌─uid─┬─version─┬─is_deleted─┐
│ 1   │       1 │          0 │
└─────┴─────────┴────────────┘

1 row in set. Elapsed: 0.019 sec. 

dell9510 :) select *, _part from test

┌─uid─┬─version─┬─is_deleted─┬─_part─────┐
│ 1   │       1 │          0 │ all_0_0_0 │
└─────┴─────────┴────────────┴───────────┘

1 row in set. Elapsed: 0.014 sec. 
```

Related to https://github.com/ClickHouse/ClickHouse/pull/41005

### LINKED ISSUE #54570: 02490_replacing_merge_tree_is_deleted_column.sql is flaky
2023.09.13 00:50:09.739289 [ 19093 ] {38c86424-30b0-4643-91c5-a049813d2c0b} <Error> executeQuery: Code: 341. DB::Exception: Log entry log-0000000003 is not precessed on local replica, most likely because the replica was shut down. (UNFINISHED) (version 23.9.1.823) (from [::1]:33788) (comment: 02490_replacing_merge_tree_is_deleted_column.sql) (in query: OPTIMIZE TABLE testCleanupR1 FINAL CLEANUP;), Stack trace (when copying this message, always include the lines below)

[Link](https://s3.amazonaws.com/clickhouse-test-reports/47532/d683900765dca78704d59c175189a07a0a240660/stateless_tests__aarch64_.html)

### LINKED ISSUE #54988: Lonely part FINAL optimization for ReplacingMergeTree with is_deleted
I have tried out https://github.com/ClickHouse/ClickHouse/pull/53919, and it looks really good for ReplacingMergeTree with just the `ver` parameter. Can it work just as well using the `is_deleted` parameter, too? For example, here I make two ReplacingMergeTrees. Both have an `is_deleted` column, but only one sets the `is_deleted` parameter on the ReplacingMergeTree:

<table>
<tr>
<td>
<pre><code>
CREATE TABLE rmt
(
`id` UInt64,
`dt` Date,
`val` UInt64,
`version` UInt64,
`is_deleted` Bool
)
ENGINE = ReplacingMergeTree(version)
PARTITION BY dt
ORDER BY (id);
</pre></code>
</td>
<td>
<pre><code>
CREATE TABLE rmt_is_deleted
(
`id` UInt64,
`dt` Date,
`val` UInt64,
`version` UInt64,
`is_deleted` Bool
)
ENGINE = ReplacingMergeTree(version, is_deleted)
PARTITION BY dt
ORDER BY (id);
</code></pre>
</td>
</tr>
</table>

Then, I insert a bunch of records:

```
INSERT INTO rmt SELECT number, '2023-09-25', number*10, 0, number%2 FROM numbers(50_000_000);
INSERT INTO rmt SELECT number, '2023-09-26', number*10, 0, number%2 FROM numbers(50_000_000);

OPTIMIZE TABLE rmt FINAL;

ALTER TABLE rmt_is_deleted ATTACH PARTITION '2023-09-25' FROM rmt;
ALTER TABLE rmt_is_deleted ATTACH PARTITION '2023-09-26' FROM rmt;
```

Performance is good querying ReplacingMergeTree with just the `ver` parameter. We can filter out `is_deleted` records ourselves:

```
SELECT
    max(val),
    count(*)
FROM rmt
FINAL
WHERE NOT is_deleted
SETTINGS max_threads = 1, do_not_merge_across_partitions_select_final = 1

Query id: e6118044-ce91-4900-aaf1-f84120d643df

┌──max(val)─┬──count()─┐
│ 499999980 │ 50000000 │
└───────────┴──────────┘

1 row in set. Elapsed: 1.431 sec. Processed 100.00 million rows, 900.00 MB (69.88 million rows/s., 628.92 MB/s.)
```

Performance is not as good querying ReplacingMergeTree with the `is_deleted` parameter. I guess this is because, due to depending on the `is_deleted` column, we are triggering a merge that would otherwise have been bypassed by https://github.com/ClickHouse/ClickHouse/pull/53919. But, if we have a lonely part, couldn't we filter for `is_deleted` more cheaply, as demonstrated in the previous query?

```
SELECT
    max(val),
    count(*)
FROM rmt_is_deleted
FINAL
SETTINGS max_threads = 1, do_not_merge_across_partitions_select_final = 1

Query id: 7415a4af-1617-4c14-8a82-bbca8fe1bcf2

┌──max(val)─┬──count()─┐
│ 499999980 │ 50000000 │
└───────────┴──────────┘

1 row in set. Elapsed: 5.550 sec. Processed 100.00 million rows, 1.70 GB (18.02 million rows/s., 306.31 MB/s.)
```

<details>
<summary>EXPLAINs for rmt</summary>

```
┌─explain─────────────────────────────────────┐
│ Expression ((Projection + Before ORDER BY)) │
│   Aggregating                               │
│     Expression (Before GROUP BY)            │
│       Filter (WHERE)                        │
│         ReadFromMergeTree (demo.rmt)        │
└─────────────────────────────────────────────┘
```

```
┌─explain──────────────────────────────────────────────────────────────────────────┐
│ (Expression)                                                                     │
│ ExpressionTransform                                                              │
│   (Aggregating)                                                                  │
│   Resize 2 → 1                                                                   │
│     AggregatingTransform × 2                                                     │
│       StrictResize 2 → 2                                                         │
│         (Expression)                                                             │
│         ExpressionTransform × 2                                                  │
│           (Filter)                                                               │
│           FilterTransform × 2                                                    │
│             (ReadFromMergeTree)                                                  │
│             MergeTreeSelect(pool: ReadPoolInOrder, algorithm: InOrder) × 2 0 → 1 │
└──────────────────────────────────────────────────────────────────────────────────┘
```

</details>

<details>
<summary>EXPLAINs for rmt_is_deleted</summary>

```
┌─explain────────────────────────────────────────┐
│ Expression ((Projection + Before ORDER BY))    │
│   Aggregating                                  │
│     Expression (Before GROUP BY)               │
│       ReadFromMergeTree (demo.rmt_is_deleted)  │
└────────────────────────────────────────────────┘
```

```
┌─explain────────────────────────────────────────────────────────────────────────────────┐
│ (Expression)                                                                           │
│ ExpressionTransform                                                                    │
│   (Aggregating)                                                                        │
│   Resize 2 → 1                                                                         │
│     AggregatingTransform × 2                                                           │
│       StrictResize 2 → 2                                                               │
│         (Expression)                                                                   │
│         ExpressionTransform × 2                                                        │
│           (ReadFromMergeTree)                                                          │
│           ExpressionTransform × 2                                                      │
│             ReplacingSorted                                                            │
│               ExpressionTransform                                                      │
│                 MergeTreeSelect(pool: ReadPoolInOrder, algorithm: InOrder) 0 → 1       │
│                   ReplacingSorted                                                      │
│                     ExpressionTransform                                                │
│                       MergeTreeSelect(pool: ReadPoolInOrder, algorithm: InOrder) 0 → 1 │
└────────────────────────────────────────────────────────────────────────────────────────┘
```

</details>

### LINKED ISSUE #57930: Remove `OPTIMIZE CLEANUP` and `is_deleted`
Sorry, you might not like this proposal, but this feature is working incorrectly, and we have no other choice than to remove it. We didn't want or welcome this feature either.

### PR DESCRIPTION
**Pull request by alexey-milovidov**
### Changelog category (leave one):
- Backward Incompatible Change

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Remove the feature of `is_deleted` row in ReplacingMergeTree and the `CLEANUP` modifier for the OPTIMIZE query. This fixes #57930. This closes #54988. This closes #54570. This closes #50346. This closes #47579. The feature has to be removed because it is not good. We have to remove it as quickly as possible, because there is no other option.

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
Screenshot_20231215_224351

**Comment by robot-ch-test-poll3** [comment]
*This is an automated comment for commit ee502ef6b94dbc22ae1b18406cb67e4b2318e08f with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/57932/ee502ef6b94dbc22ae1b18406cb67e4b2318e08f/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td><a href="https://github.com/ClickHouse/ClickHouse/actions/runs/7227336301">✅ success</a></td></tr>
<tbody>
</table>
</details>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/57932/ee502ef6b94dbc22ae1b18406cb67e4b2318e08f/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Comment by aadant** [comment]
@alexey-milovidov do you plan to redo this feature or provide an equivalent feature ?

**Comment by alexey-milovidov** [comment]
It could be resurrected, but most likely with smaller steps - first only to support OPTIMIZE with CLEANUP - maybe with an arbitrary "is_deleted" expression.

**Comment by aadant** [comment]
@alexey-milovidov thanks. This feature is very useful to emulate OTLP workloads. Or to replicate MySQL/ Postgres to ClickHouse. It is superior to lightweight deletes that can take a long time to run a busy server or do not work well concurrently. I used it with Replicated because it is mutation-free.

I was even thinking that you can easy implement 
the delete command for RMT, multi-table updates as an insert select, multi-table deletes (one table is modified to start with).

It also solves the update of primary keys (delete + insert works).

RMT has issues with materialized views and projections but that’s another story !

**Comment by tavplubix** [comment]
You can easily emulate this feature by adding `is_deleted` column to your table, `WHERE ... is_deleted=0` to your SELECT FINAL queries, and periodically running `OPTIMIZE FINAL` + `ALTER DELETE WHERE is_deleted=1` for old data. That's basically how the feature worked. Also, usually people misunderstand this feature, so they can face issues like https://github.com/ClickHouse/ClickHouse/issues/50346

**Comment by aadant** [comment]
Emulation is not user friendly. With final as a profile variable, you do not need any where clause.

**Comment by alifirat** [comment]
Hey @alexey-milovidov 

I don't understand why you have named this branch for this PR `remove-shit-cleanup`. ClickHouse is an OSS and last time I remember, it's open to the contributions. 

We take some time to develop this feature and while it's not perfect, like many contributions made on the repository, it deserves a better naming that something `shitty`.

**Comment by hodgesrm** [comment]
@tavplubix It's true you can emulate this feature and we did prior to the work by @alifirat and team.  However, the idea behind the feature was to avoid having to make changes to queries at all when using this table type. For instance, if you migrate apps from MySQL to ClickHouse it means users can run essentially the same query on both. In this particular use case it makes migration much easier.

**Comment by melvynator** [comment]
@alifirat I'm really sorry for the terminology that was used in the branch name. We have a tendency to use this terminology too loosely, even to describe our own contributions, and we should stop; it is not community-friendly. 

We value everybody's contributions. It's an open-source project, and we are also the one that reviewed and merged this contribution, we don't blame your particular contribution.

**Comment by alexey-milovidov** [comment]
Sorry for the bad naming. We discovered that this feature could lead to data corruption. I am really angry about the fact that this behavior is even possible. It is our responsibility to remove it as fast as possible and prevent its usage in production.

**Comment by alexey-milovidov** [comment]
@alifirat, How about reintroducing it under an experimental flag?
This flag will describe the "downsides" of using this feature in great detail, explaining that it is a bug and it could and will most likely lead to irreparable damage to your data.

Actually, I don't like this option. It will be much better to reintroduce it as no-op for the compatibility on a syntax level.

**Comment by aadant** [comment]
The feature is mentioned here https://clickhouse.com/blog/clickhouse-postgresql-change-data-capture-cdc-part-1#limitations-with-deletes

does the corruption occur with `clean_deleted_rows = Never`, the default ? If it only occurs for Always, we can just disable Always. And make optimize work.

**Comment by alexey-milovidov** [comment]
@aadant, I am reintroducing OPTIMIZE CLEANUP as a no-op. Is it equivalent to `clean_deleted_rows = 'Never'`?

**Comment by alexey-milovidov** [comment]
And we can just keep the setting `clean_deleted_rows` as obsolete for compatibility...

**Comment by alifirat** [comment]
@alexey-milovidov @melvynator @hodgesrm thank you for your answers. Note that my message was also not personal againt the ClickHouse core contributors, we are all here for the same reason: make ClickHouse faster but also safer. 

@alexey-milovidov Ok for me to reintroduce as experimental feature and also if you can open an issue with the potential impacts, to let my team having a look to the potential data corruption it would be great.

**Comment by tavplubix** [comment]
> However, the idea behind the feature was to avoid having to make changes to queries at all when using this table type. For instance, if you migrate apps from MySQL to ClickHouse it means users can run essentially the same query on both.

@hodgesrm, see https://github.com/ClickHouse/ClickHouse/issues/57930#issuecomment-1860578627

> does the corruption occur with clean_deleted_rows = Never, the default ? If it only occurs for Always, we can just disable Always. And make optimize work.

No, it occurs on a `Vertical` merge with cleanup (it can be due to `Always` mode or due to `CLEANUP` keyword in `OPTIMIZE FINAL`, it doesn't matter). See also https://github.com/ClickHouse/ClickHouse/pull/54368 and https://github.com/ClickHouse/ClickHouse/pull/54706. The `Always` mode has another issue (it's basically broken by design): https://github.com/ClickHouse/ClickHouse/issues/50346

**Comment by UnamedRus** [comment]
> @hodgesrm, see https://github.com/ClickHouse/ClickHouse/issues/57930#issuecomment-1860578627

It doesn't looks like viable alternative. 

Plus, clean part of feature wasn't even planned initially and it was asked by core team of ClickHouse.

> From our perspective, deleted data must be filtered out when queried and not removed from disk. When partitioned on several shards, data can have several versions on different partitions. If rows with a -1 sign are deleted, we would lose the information of deleted data which could lead eventually to incorrect KPIs.

**Comment by aadant** [comment]
> @aadant, I am reintroducing OPTIMIZE CLEANUP as a no-op. Is it equivalent to `clean_deleted_rows = 'Never'`?

sure
Let us remove what is broken by design but keep what is working fine. Thanks

**Pull request merged**
