### PR TITLE
Rewrite clickhouse-test to use python clickhouse_driver

### PR DESCRIPTION
**Pull request by azat**
Pros:
- Using native protocol over executing binaries is always better
- `clickhouse-client` in debug build takes almost a second to execute simple `SELECT 1`
  and `clickhouse-test` requires ~5 queries at start (determine some
  flags, zk, alive, create database)

Notes:
- `FORMAT Vertical` had been replaced with printing of `pandas.DataFrame`

And after this patch tiny tests work with the speed of the test, and
does not requires +-5 seconds of bootstrapping.

Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by azat** [comment]
@alexey-milovidov this PR converts only service use of `clickhouse-client` i.e. to:
- run `show processlist`
- to health check (simple `select 1` or `select {test_name}`)
- create database for tests

Every `.sql` test that was started using `clickhouse-client` will still use it.

**Comment by alexey-milovidov** [comment]
> I've converted it to python driver to make it faster since executing binaries (even from release build) will be always slower then simply connect+send+recv (i.e. native protocol).

Ok. I think it's worth doing.
But let's also improve the startup time of clickhouse-client.

`for i in {1..10000}; do clickhouse-local --query "SELECT 1"; done`
- it's spending time in initializing DateLUT - for what?

**Comment by amosbird** [comment]
Btw, why don't we just use HTTP for this purpose instead?

**Comment by azat** [comment]
BTW looks like everything related had been passed!

>Fast test — Cannot install or start ClickHouse

Requires image update (@alesapin I guess it will be done automatically after merge?).

**Comment by azat** [comment]
>Btw, why don't we just use HTTP for this purpose instead?

Ok, I haven't understand that clear enough.

@amosbird is right, HTTP interface can be also used instead of clickhouse-driver (python).

Cons:
- ~~one more extra dependency~~

Pros:
- has better error handling (i.e. defines lots of exceptions for various kind of errors, and also provides lots of predefined error codes)
- ~~provide better API for reading (streaming and so on), but it is not used right now~~
- it is already used for performance tests, so the cost of adding this "extra dependency" should be minor (although I guess not every developer runs performance tests by themselves, but they do run stateless tests for sure)

So maybe someone else has some opinion on this?

**Comment by alexey-milovidov** [comment]
I don't have stong opinion on that - let's use what will be more convenient.

**Comment by azat** [comment]
Some numbers:

- fasttest: before 11min/14min, after 9min/12min -- no benefit
- stateless debug: no benefit

<details>

```sql
SELECT DISTINCT
    check_duration_ms,
    if(report_url LIKE '%268c155b7d4b15524219ea48cf228bf140cf9cdd%', 'python-requests', '') AS mr
FROM checks
WHERE (check_start_time > today()) AND (pull_request_number = 0) AND (report_url LIKE '%stateless_tests_(debug)%')
ORDER BY check_start_time ASC
FORMAT PrettyCompactMonoBlock

Query id: e9252c81-fe1c-4387-b62c-1a4c69e72715

┌─check_duration_ms─┬─mr──────────────┐
│           9168779 │                 │
│          11118219 │                 │
│           7965240 │ python-requests │
│           8240968 │                 │
│           8505889 │                 │
│           8503848 │                 │
│           8318323 │                 │
│           8066711 │                 │
└───────────────────┴─────────────────┘
```

</details>

- under sanitizers stateless tests looks a little bit faster, but no significant difference.

<details>

```sql
SELECT DISTINCT
    check_duration_ms,
    if(report_url LIKE '%268c155b7d4b15524219ea48cf228bf140cf9cdd%', 'python-requests', '') AS mr
FROM checks
WHERE (check_start_time > today()) AND (pull_request_number = 0) AND (report_url LIKE '%stateless_tests_(memory)%')
ORDER BY check_start_time ASC
FORMAT PrettyCompactMonoBlock

Query id: bc1993e5-413f-4d6a-86e2-66e0c1465efb

┌─check_duration_ms─┬─mr──────────────┐
│           7283462 │                 │
│           7491509 │                 │
│           7040965 │ python-requests │
│           6817031 │                 │
│           6866696 │                 │
│           6504630 │                 │
│           6624146 │                 │
│           6728470 │                 │
└───────────────────┴─────────────────┘
```

</detailS>

**Pull request merged**
