### PR TITLE
Fix codec delta endian issue for s390x

### PR DESCRIPTION
**Pull request by HarryLeeIBM**
On s390x, codec delta has endian issue which fails the functional test 01375_compact_parts_codecs.
The fix is to use LittleEndian to load/store data on s390x.

### Changelog category (leave one):
- Build/Testing/Packaging Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fixed codec delta endian issue for s390x

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by robot-ch-test-poll4** [comment]
This is an automated comment for commit 5ab6b34e1191c97d3a590f83345015e059ad3edb with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/52592/5ab6b34e1191c97d3a590f83345015e059ad3edb/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Review by yakov-olkhovskiy — APPROVED** [review]

**Comment by yakov-olkhovskiy** [comment]
test_keeper_client/test.py::test_delete_stable_backups related to #52985

**Comment by HarryLeeIBM** [comment]
@yakov-olkhovskiy, thanks for taking care of this PR. The 5 failed checks seems not related to this change, could you merge the PR or let me know what to do on my side? Thanks!

**Review by yakov-olkhovskiy — APPROVED** [review]

**Comment by yakov-olkhovskiy** [comment]
@HarryLeeIBM merged

**Pull request merged**
