### PR TITLE
Fix segfault when mutation get killed

### PR DESCRIPTION
**Pull request by alesapin**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix segfault when mutation killed and the server tries to send the exception to the client.

### CODE REVIEW

**Comment by alesapin** [comment]
Also, guarantee the order of mutations in exception message.

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
> 00834_kill_mutation

Fixed in #13167

**Comment by alexey-milovidov** [comment]
Don't wait for performance test.

**Comment by alexey-milovidov** [comment]
Fuzz test: https://github.com/ClickHouse/ClickHouse/issues/13196

**Pull request merged**
