### PR TITLE
DOCSUP-8709: Document RELOAD MODEL and RELOAD MODELS system queries

### PR DESCRIPTION
**Pull request by sevirov**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category:

- Documentation for #23182

### CODE REVIEW

**Comment by sevirov** [comment]
@kitaisreal Please, review this PR.

**Comment by sevirov** [comment]
@kitaisreal Please, review this PR.

**Review by Avogar — APPROVED** [review]

**Comment by kitaisreal** [comment]
@sevirov ```SYSTEM RELOAD MODEL [db.]<model_name>```. [db.] cannot be specified for model.

**Comment by Avogar** [comment]
> @sevirov `SYSTEM RELOAD MODEL [db.]<model_name>`. [db.] cannot be specified for model.

My fault, didn't noticed it, will fix

**Pull request merged**
