### PR TITLE
ReplicatedMergeTree storage: provide memory order for readonly flag access

### PR DESCRIPTION
**Pull request by devcrafter**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Use `acquire-release` memory order instead of default `sequential consistency` (which is more expensive) when accessing `is_readonly` atomic flag

### CODE REVIEW

**Comment by alesapin** [comment]
What is the purpose of this change?

**Comment by antonio2368** [comment]
I would be careful with this, I don't like putting `acquire-release` for all loads/stores just because it's faster. I think it's reasonable to discuss about this only if there are noticeable performance improvements or it's really simple to reason about it.

**Comment by KochetovNicolai** [comment]
+1
I don't understand why this change is needed.
In my opinion, we should not use `acquire-release` in most of the cases. The only exception is when it gives some significant perf improvement. This is definitely not the case.

**Comment by KochetovNicolai** [comment]
Sorry for that. Can discuss it later.

**Pull request closed without merging**
