### PR TITLE
Implement array L2 distance with AVX512, AVX2, and SSE

### PR DESCRIPTION
**Pull request by julianzq**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Implement L2 distance in AVX512, AVX2, SSE, and a fallback implementation.

A discussion is needed on how to integrate this work with the array distance functions which were recently added to CH (`arrayDistance.cpp`). Those array distance functions don't use AVX, and use a kind of accumulator/finalize logic which makes AVX not easily pluggable, so for simplicity, I wrote this function separately.

Also, the AVX/SSE code requires Float32, which means for any other type we should use a fallback implementation (ideally the current array L2 function which is already in CH).

Lastly, most vector engine libraries like FAISS avoid using square root as there is no practical need for it when comparing distances, so to be consistent with this practice, I omitted square root from the AVX/SSE L2 as well, perhaps it's worth considering doing so with the current L2 in CH as well.

### CODE REVIEW

**Comment by israelg99** [comment]
@davenger maybe you can take a look

**Comment by alexey-milovidov** [comment]
> Lastly, most vector engine libraries like FAISS avoid using square root as there is no practical need for it when comparing distances, so to be consistent with this practice, I omitted square root from the AVX/SSE L2 as well, perhaps it's worth considering doing so with the current L2 in CH as well.

Just make another set of functions: L2DistanceRaw, L2NormRaw, etc...

**Comment by israelg99** [comment]
> > Lastly, most vector engine libraries like FAISS avoid using square root as there is no practical need for it when comparing distances, so to be consistent with this practice, I omitted square root from the AVX/SSE L2 as well, perhaps it's worth considering doing so with the current L2 in CH as well.
> 
> Just make another set of functions: L2DistanceRaw, L2NormRaw, etc... This set of functions should be consistent with the existing.

@alexey-milovidov Done #38545

**Comment by davenger** [comment]
Looks like there is some bug in arrayL2 implementation:
```
SELECT
    L2SquaredDistance(a, b),
    arrayL2(a, b)
FROM
(
    SELECT
        CAST([1, 0], 'Array(Float32)') AS a,
        CAST([0, 0], 'Array(Float32)') AS b
)

Query id: 39cc3824-5e72-486b-822a-8c394679afd0

┌─L2SquaredDistance(a, b)─┬─arrayL2(a, b)─┐
│                       1 │             0 │
└─────────────────────────┴───────────────┘
```

Also I tried to modify the implementation of norm and distance functions in this PR https://github.com/ClickHouse/ClickHouse/pull/38740
It shows improvements for all *Norm and *Distance functions on x86_64 
https://s3.amazonaws.com/clickhouse-test-reports/38740/8ce8158f7fa7b0cbc911d9e934d55ddb72fb9fcf/performance_comparison_[1/4]/all-queries.html

and on AArch64 as well
https://s3.amazonaws.com/clickhouse-test-reports/38740/8ce8158f7fa7b0cbc911d9e934d55ddb72fb9fcf/performance_comparison_aarch64_[4/4]/all-queries.html

So it probably makes sense to benchmark against that version.

**Comment by qieqieplus** [comment]
I've implemented something similar in my private fork, furthermore, also avx int8.
One question bothers me is that ClickHouse treat literal float numbers as Float64, so I had to cast the nested type of const column to type of non-const.

**Comment by israelg99** [comment]
> I've implemented something similar in my private fork, furthermore, also avx int8. One question bothers me is that ClickHouse treat literal float numbers as Float64, so I had to cast the nested type of const column to type of non-const.

I think a good plan is to merge an initial AVX version for just Float32 and fall back to non-AVX for all other types, after we merge that, we can discuss how to handle Float64 and if should we cast the nested type, etc...

**Comment by alexey-milovidov** [comment]
@evillique, we need to make this function a special case of the existing Lp-distance functions, not a separate function.

**Comment by alexey-milovidov** [comment]
@evillique Let's integrate this code into L2SquaredDistance and use dynamic dispatch.

**Comment by alexey-milovidov** [comment]
Is it a good code? https://godbolt.org/z/TMEf9qo4r
We can make the compiler generate it automatically with our multi-target code infrastructure.

**Comment by alexey-milovidov** [comment]
This is a good code, but we should integrate it into existing functions, without the introduction of a nearly identical function.

**Comment by alexey-milovidov** [comment]
But nothing was done in over a year - closing.

**Pull request closed without merging**
