### PR TITLE
Add new function formatDateTime(datetime, format).

### PR DESCRIPTION
**Pull request by bocharov**
This PR adds new function `formatDateTime(datetime, format)`.

The work started last month and we recently discovered similar PR - https://github.com/yandex/ClickHouse/pull/2770. However, this implementation uses `cctz::format() `, which is superset of what `strftime()` can do, which gives user more flexibility on formatting `DateTime`. This function doesn't have the third optional argument of time zone, because it's very much confusing - is result expected to be in specified time zone OR argument of DateTime is being specified in this time zone OR what if we specify time zone twice - in the date time column and as argument, which one will be used? Thus, this implementation prefers explicit conversion of date time using `toTimeZone()` function and `formatDateTime()` automatically detects the time zone. The same approach used regarding formatting `Date` columns - it requires explicit type conversion using `toDateTime()` function.

Additionally, this PR contains tests to cover various formatting options with different time zones, including fractional time zones like India 05:30. Both English and Russian versions of documentation are modified to reflect the new function syntax and examples.

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
Ok. The only drawback is performance.

```
SELECT count() FROM hits_1000m WHERE NOT ignore(formatDateTime(EventTime, '%m/%d/%Y %H:%M:%S'))
```

33.70 million rows/s.

```
SELECT count() FROM hits_1000m WHERE NOT ignore(toString(toYear(EventTime)), toString(toMonth(EventTime)), toString(toDayOfMonth(EventTime)), toString(toHour(EventTime)), toString(toMinute(EventTime)), toString(toSecond(EventTime)))
```

234.73 million rows/s.

```
SELECT count() FROM hits_1000m WHERE NOT ignore(replaceRegexpOne(toString(EventTime), '^(\\d\\d\\d\\d)-(\\d\\d)-(\\d\\d)( \\d\\d:\\d\\d:\\d\\d)$', '\\3/\\2/\\1\\4'))
```

60.53 million rows/s.

All numbers are from Xeon CPU E5-2650 v2, two sockets.

```
  21.76%  clickhouse             [.] cctz::detail::impl::n_sec
  21.68%  clickhouse             [.] std::string::append
  19.61%  clickhouse             [.] cctz::detail::format
   6.89%  clickhouse             [.] memcpy
   4.42%  libc-2.19.so           [.] __strchr_sse2
   4.20%  clickhouse             [.] malloc
   3.05%  clickhouse             [.] free
```

Here are creation and destruction of temporary `std::string` objects.
Also time manipulation methods of CCTZ is very slow comparing to DateLUT.

**Comment by bocharov** [comment]
@alexey-milovidov please have another look.

I've optimized it to use just `strftime()` and almost no allocations.

These are benchmarks I've run on my laptop:

Initial version of formatDateTime before optimization - 425.70 thousand rows/s:
```
select count() from (select formatDateTime(t, '%m/%d/%Y %H:%M:%S') from (select toDateTime('2018-01-01 00:00:00')+number as t from numbers(10000000)));
```

Regexp - 849.21 thousand rows/s:
```
select count() from (select replaceRegexpOne(toString(t), '^(\\d\\d\\d\\d)-(\\d\\d)-(\\d\\d)( \\d\\d:\\d\\d:\\d\\d)$', '\\3/\\2/\\1\\4') from (select toDateTime('2018-01-01 00:00:00')+number as t from numbers(10000000)));
```

Modified version of formatDateTime using DateLUT + stringstream - 693.63 thousand rows/s
Modified version of formatDateTime using sprintf - 2.46 million rows/s

Just extracting year, month, day, etc - 9.73 million rows/s
```
select count() from (select toString(toYear(t)), toString(toMonth(t)), toString(toDayOfMonth(t)), toString(toHour(t)), toString(toMinute(t)), toString(toSecond(t)) from (select toDateTime('2018-01-01 00:00:00')+number as t from numbers(10000000)));
```

BTW, if we concat the same things above, it becomes very slow - 849.21 thousand rows/s
```
select count() from (select replaceRegexpOne(toString(t), '^(\\d\\d\\d\\d)-(\\d\\d)-(\\d\\d)( \\d\\d:\\d\\d:\\d\\d)$', '\\3/\\2/\\1\\4') from (select toDateTime('2018-01-01 00:00:00')+number as t from numbers(10000000)));
```

And finally, optimized version of formatDateTime using `strftime` + new `DateLUT::makeTM` method - 5.28 million rows/s:
```
select count() from (select formatDateTime(t, '%m/%d/%Y %H:%M:%S') from (select toDateTime('2018-01-01 00:00:00')+number as t from numbers(10000000)));
```

**Comment by alexey-milovidov** [comment]
Are you sure that you build with release mode (it is by default)?
Performance numbers that you show are like numbers from debug build.
(I have debug build on my laptop and get almost the same numbers.)

All performance comparisons in debug build are plain useless.

`stringstream` is the canonical example of slow code. It can never be used in any inner loops. It is so slow that it even has mention in our code style.

C functions like `sprintf`, `strftime` are no-go not only due to terrible performance but also because lack of possibility to use more than single timezone at one moment of time. Note that `strftime` uses `tm` values from proper time zone, but then uses local server time zone for formatting. Some values will be incorrect.

New `DateLUT::makeTM` may be slightly suboptimal because compiler cannot get rid of redundant calculations (but it's about two orders of magnitude less comparing to overhead of C functions).

**Comment by sundy-li** [comment]
```
21.76%  clickhouse             [.] cctz::detail::impl::n_sec
  21.68%  clickhouse             [.] std::string::append
  19.61%  clickhouse             [.] cctz::detail::format
   6.89%  clickhouse             [.] memcpy
   4.42%  libc-2.19.so           [.] __strchr_sse2
   4.20%  clickhouse             [.] malloc
   3.05%  clickhouse             [.] free
```

@alexey-milovidov  BTW, what's the tool set to get the performance informations, looks very useful.

**Comment by alexey-milovidov** [comment]
Just run: `sudo perf top`
(To install run `sudo apt-get install linux-tools-$(uname -r)`)

http://www.brendangregg.com/perf.html

**Comment by bocharov** [comment]
@alexey-milovidov I usually use CLion and it uses debug build by default.
I've built in release mode and here are the numbers:

Just datetime components, without concat: 75.79 million rows/s.
```
select count() from (select toString(toYear(t)), toString(toMonth(t)), toString(toDayOfMonth(t)), toString(toHour(t)), toString(toMinute(t)), toString(toSecond(t)) from (select toDateTime('2018-01-01 00:00:00')+number as t from numbers(100000000)));
```

Regexp: 5.12 million rows/s.
```
select count() from (select replaceRegexpOne(toString(t), '^(\\d\\d\\d\\d)-(\\d\\d)-(\\d\\d)( \\d\\d:\\d\\d:\\d\\d)$', '\\3/\\2/\\1\\4') from (select toDateTime('2018-01-01 00:00:00')+number as t from numbers(100000000)));
```

Datetime components + concat: 6.55 million rows/s.
```
select count() from (select concat(toString(toYear(t)), '/', toString(toMonth(t)), '/', toString(toDayOfMonth(t)), ' ', toString(toHour(t)), ':', toString(toMinute(t)), ':', toString(toSecond(t))) from (select toDateTime('2018-01-01 00:00:00')+number as t from numbers(100000000)));
```

Finally, formatDateTime using DateLUT + strftime: 8.20 million rows/s.
```
select count() from (select formatDateTime(t, '%m/%d/%Y %H:%M:%S') from (select toDateTime('2018-01-01 00:00:00')+number as t from numbers(100000000)));
```
So formatDateTime is faster than concatenating individual components.

Regarding strftime and support of multiple time zones:

1. The tm struct has tm_zone field, so it's possible to pass arbitrary time zone, even something like 'WTF' and it will be used by strftime (https://code.woboq.org/userspace/glibc/time/strftime_l.c.html#544). however cctz takes care of correct time zone abbreviation in the DateLUT constructor.
2. The tm struct is initialized in makeTM method with components already accounting for the timezone, thanks to DateLUT methods working with time zone offsets.
3. According to https://www.mkssoftware.com/docs/man3/strftime.3.asp - The function strftime() is MT-Safe as long as no thread calls setlocale() while this function is executing. Same thing about locale this documentation says - http://www.cplusplus.com/reference/ctime/strftime/
4. I tested many different time zones, including running them in the parallel to see if I can trigger incorrect behaviour when different timezones are used at same time, and I didn't find any discrepancies.

Please let me know if you have any more concerns or suggestions. Feel free to modify this code according to best practices of ClickHouse, so we can finally have this function available.

**Comment by alexey-milovidov** [comment]
Just run: `sudo perf top`
(To install run `sudo apt-get install linux-tools-$(uname -r)`)

http://www.brendangregg.com/perf.html

**Comment by alexey-milovidov** [comment]
Implemented in #2770 by @alex-krash.
Now I'm going to import your tests...

**Comment by alexey-milovidov** [comment]
> Are timezones with non-standard shifts are supported, e.g. 15, 30, 45 minutes?

Yes.

```
SELECT formatDateTime(parseDateTimeBestEffort('2000-01-01T00:00:00Z'), '%m/%d/%Y %H:%M:%S', 'Asia/Calcutta') AS res

┌─res─────────────────┐
│ 01/01/2000 05:30:00 │
└─────────────────────┘

1 rows in set. Elapsed: 0.001 sec. 

SELECT formatDateTime(parseDateTimeBestEffort('2000-01-01T00:00:00Z'), '%m/%d/%Y %H:%M:%S', 'Asia/Katmandu') AS res

┌─res─────────────────┐
│ 01/01/2000 05:45:00 │
└─────────────────────┘

1 rows in set. Elapsed: 0.005 sec.
```

**Comment by bocharov** [comment]
That's great, thank you.

**Pull request closed without merging**
