### PR TITLE
Try to fix RabbitMQ test failures

### PR DESCRIPTION
**Pull request by azat**
### Changes
- use version without management (slightly faster)
- increase startup timeout

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Refs: https://github.com/ClickHouse/ClickHouse/issues/45160

### CODE REVIEW

**Comment by robot-ch-test-poll4** [comment]
*This is an automated comment for commit dc527b6fd1dfdffb1d177237bffc69cd110cd2a7 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/67743/dc527b6fd1dfdffb1d177237bffc69cd110cd2a7/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Builds</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/3efa20868086d518a0983bf5221e3953442f0530/builds/report.html">✅ success</a></td></tr>
<tr><td>ClickBench</td><td>Runs [ClickBench](https://github.com/ClickHouse/ClickBench/) with instant-attach table</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/3efa20868086d518a0983bf5221e3953442f0530/clickbench__aarch64_.html">✅ success</a></td></tr>
<tr><td>Compatibility check</td><td>Checks that <b>clickhouse</b> binary runs on distributions with old libc versions. If it fails, ask a maintainer for help</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/3efa20868086d518a0983bf5221e3953442f0530/compatibility_check__aarch64_.html">✅ success</a></td></tr>
<tr><td>Docker keeper image</td><td>The check to build and optionally push the mentioned image to docker hub</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/3efa20868086d518a0983bf5221e3953442f0530/docker_keeper_image.html">✅ success</a></td></tr>
<tr><td>Docker server image</td><td>The check to build and optionally push the mentioned image to docker hub</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/3efa20868086d518a0983bf5221e3953442f0530/docker_server_image.html">✅ success</a></td></tr>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/ddeb4e7b5572783b72292c1c51c6e9308e9ca16c/docs_check.html">✅ success</a></td></tr>
<tr><td>Fast test</td><td>Normally this is the first check that is ran for a PR. It builds ClickHouse and runs most of <a href="https://clickhouse.com/docs/en/development/tests#functional-tests">stateless functional tests</a>, omitting some. If it fails, further checks are not started until it is fixed. Look at the report to see which tests fail, then reproduce the failure locally as described <a href="https://clickhouse.com/docs/en/development/tests#functional-test-locally">here</a></td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/3efa20868086d518a0983bf5221e3953442f0530/fast_test.html">✅ success</a></td></tr>
<tr><td>Install packages</td><td>Checks that the built packages are installable in a clear environment</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/3efa20868086d518a0983bf5221e3953442f0530/install_packages__aarch64_.html">✅ success</a></td></tr>
<tr><td>Stateful tests</td><td>Runs stateful functional tests for ClickHouse binaries built in various configurations -- release, debug, with sanitizers, etc</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/c6c4b313e6ddbbf680f53f813e55c65409ca1316/stateful_tests__aarch64_.html">✅ success</a></td></tr>
<tr><td>Unit tests</td><td>Runs the unit tests for different release types</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/3efa20868086d518a0983bf5221e3953442f0530/unit_tests__asan_.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Review by kssenii — APPROVED** [review]

**Comment by azat** [comment]
>Cloud fork sync (only for ClickHouse Inc. employees) — tests failed

@kssenii any clue?

**Comment by kssenii** [comment]
> > Cloud fork sync (only for ClickHouse Inc. employees) — tests failed

> @kssenii any clue?

one unrelated test failed...

**Comment by alexey-milovidov** [comment]
Not fixed: https://s3.amazonaws.com/clickhouse-test-reports/0/8af682f7483f3651957200d0a9ef8bbb9b7a0141/integration_tests__tsan__[4_6].html

**Pull request merged**
