### PR TITLE
Fix system.parts _state column

### PR DESCRIPTION
**Pull request by azat**
Changelog category (leave one):
- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix system.parts _state column (LOGICAL_ERROR when querying this column, due to incorrect order)

### CODE REVIEW

**Review by vdimir — APPROVED** [review]
LGTM

Maybe it is better to rename `has_state_column` argument to `add_state_column` to make fact that it is added to the end explicit. But you added a comment and it is enough.

**Comment by alesapin** [comment]
Race fixed in https://github.com/ClickHouse/ClickHouse/pull/19355

**Comment by alesapin** [comment]
`01079_parallel_alter_add_drop_column_zookeeper` suspicious failure...

**Comment by alesapin** [comment]
Didn't fail before:
```
└────────────────────────────────────────────────┴─────────────────────┴──────────────────────────────────────────┴─────────────────────┘
┌─test_name──────────────────────────────────────┬────check_start_time─┬─commit_sha───────────────────────────────┬─pull_request_number─┐
│ 01079_parallel_alter_add_drop_column_zookeeper │ 2020-10-01 11:42:22 │ 4b18e30781bd9f424565279089241942448d54b2 │                9624 │
│ 01079_parallel_alter_add_drop_column_zookeeper │ 2020-10-06 14:47:37 │ 140b59c7bba600987bdc297c6d5760e4ecd35602 │                9624 │
│ 01079_parallel_alter_add_drop_column_zookeeper │ 2020-10-30 14:05:16 │ cf8202d36ebff92e2104859664a24d7547d334d2 │               16555 │
│ 01079_parallel_alter_add_drop_column_zookeeper │ 2020-11-27 16:06:41 │ e623f255984a64a6d5dd4e32904e10a4d22acefe │               17495 │
│ 01079_parallel_alter_add_drop_column_zookeeper │ 2020-11-27 16:10:52 │ e623f255984a64a6d5dd4e32904e10a4d22acefe │               17495 │
│ 01079_parallel_alter_add_drop_column_zookeeper │ 2020-11-27 16:11:12 │ e623f255984a64a6d5dd4e32904e10a4d22acefe │               17495 │
│ 01079_parallel_alter_add_drop_column_zookeeper │ 2020-11-27 16:12:03 │ e623f255984a64a6d5dd4e32904e10a4d22acefe │               17495 │
│ 01079_parallel_alter_add_drop_column_zookeeper │ 2020-11-27 19:14:48 │ e623f255984a64a6d5dd4e32904e10a4d22acefe │               17495 │
│ 01079_parallel_alter_add_drop_column_zookeeper │ 2020-11-28 00:01:03 │ e623f255984a64a6d5dd4e32904e10a4d22acefe │               17495 │
│ 01079_parallel_alter_add_drop_column_zookeeper │ 2020-12-22 18:51:59 │ 6e52fb1f5d1f751023346c80e12a357abae23be7 │                9516 │
│ 01079_parallel_alter_add_drop_column_zookeeper │ 2021-01-21 09:03:25 │ 5f3059555a039181cdb9b558fb073fc7998ad496 │               19346 │
└────────────────────────────────────────────────┴─────────────────────┴──────────────────────────────────────────┴─────────────────────┘
```
But logs don't look good:
```
2021.01.21 12:33:14.744905 [ 12397 ] {} <Error> test_sq0yhe.concurrent_alter_add_drop_1 (69c0cae8-0ea7-484f-8693-87b16c4f6852): auto DB::StorageReplicatedMergeTree::processQueueEntry(ReplicatedMergeTreeQueue::SelectedEntryPtr)::(anonymous class)::operator()(DB::StorageReplicatedMergeTree::LogEntryPtr &) const: Code: 47, e.displayText() = DB::Exception: Missing columns: 'value3' while processing query: 'value5, key, value3, value0', required columns: 'value5' 'key' 'value3' 'value0', maybe you meant: , Stack trace (when copying this message, always include the lines below):

0. DB::TreeRewriterResult::collectUsedColumns(std::__1::shared_ptr<DB::IAST> const&, bool) @ 0xefc278b in /usr/bin/clickhouse
1. DB::TreeRewriter::analyze(std::__1::shared_ptr<DB::IAST>&, DB::NamesAndTypesList const&, std::__1::shared_ptr<DB::IStorage const>, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, bool) const @ 0xefcac1f in /usr/bin/clickhouse
2. DB::MutationsInterpreter::prepareInterpreterSelectQuery(std::__1::vector<DB::MutationsInterpreter::Stage, std::__1::allocator<DB::MutationsInterpreter::Stage> >&, bool) @ 0xeeed81b in /usr/bin/clickhouse
3. DB::MutationsInterpreter::prepare(bool) @ 0xeee9901 in /usr/bin/clickhouse
4. DB::MutationsInterpreter::MutationsInterpreter(std::__1::shared_ptr<DB::IStorage>, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, DB::MutationCommands, DB::Context const&, bool) @ 0xeee545b in /usr/bin/clickhouse
5. DB::MergeTreeDataMergerMutator::mutatePartToTemporaryPart(DB::FutureMergedMutatedPart const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, DB::MutationCommands const&, DB::BackgroundProcessListEntry<DB::MergeListElement, DB::MergeInfo>&, long, DB::Context const&, std::__1::unique_ptr<DB::IReservation, std::__1::default_delete<DB::IReservation> > const&, std::__1::shared_ptr<DB::RWLockImpl::LockHolderImpl>&) @ 0xf4be457 in /usr/bin/clickhouse
6. DB::StorageReplicatedMergeTree::tryExecutePartMutation(DB::ReplicatedMergeTreeLogEntry const&) @ 0xf29d501 in /usr/bin/clickhouse
7. DB::StorageReplicatedMergeTree::executeLogEntry(DB::ReplicatedMergeTreeLogEntry&) @ 0xf28f50b in /usr/bin/clickhouse
8. ? @ 0xf2ff05f in /usr/bin/clickhouse
9. DB::ReplicatedMergeTreeQueue::processEntry(std::__1::function<std::__1::shared_ptr<zkutil::ZooKeeper> ()>, std::__1::shared_ptr<DB::ReplicatedMergeTreeLogEntry>&, std::__1::function<bool (std::__1::shared_ptr<DB::ReplicatedMergeTreeLogEntry>&)>) @ 0xf60c738 in /usr/bin/clickhouse
10. DB::StorageReplicatedMergeTree::processQueueEntry(std::__1::shared_ptr<DB::ReplicatedMergeTreeQueue::SelectedEntry>) @ 0xf2b8d0d in /usr/bin/clickhouse
11. ? @ 0xf410d56 in /usr/bin/clickhouse
12. ThreadPoolImpl<ThreadFromGlobalPool>::worker(std::__1::__list_iterator<ThreadFromGlobalPool, void*>) @ 0x846f8b8 in /usr/bin/clickhouse
13. ThreadFromGlobalPool::ThreadFromGlobalPool<void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda1'()>(void&&, void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda1'()&&...)::'lambda'()::operator()() @ 0x847184f in /usr/bin/clickhouse
```

**Comment by vdimir** [comment]
> Didn't fail before

I'd like to check error in previos fail in #9516, but in logs other test marked as failed https://clickhouse-test-reports.s3.yandex.net/9516/83757e5eb980ed18bd4bd652ca01a5a6001fc9f1/functional_stateful_tests_(thread).html#fail1

**Comment by alesapin** [comment]
Ok, let's merge and check.

**Pull request merged**
