### PR TITLE
Sorting mode renaming

### PR DESCRIPTION
**Pull request by devcrafter**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Renamings:
- SortMode -> SortScope
- SortMode::Stream -> SortScope::Global
- SortMode::Port -> SortScope::Stream

Follow up for #38719, see [comment](https://github.com/ClickHouse/ClickHouse/pull/38719#issuecomment-1216646403)

### CODE REVIEW

**Review by nickitat — APPROVED** [review]

**Review by KochetovNicolai — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
@devcrafter The assertion violation found by the AST fuzzer should be analyzed and reported in a new issue.

**Comment by alexey-milovidov** [comment]
@devcrafter the test about part_log has failed, and it should be investigated:

https://s3.amazonaws.com/clickhouse-test-reports/40305/6fe8b61345c680705a89b1a45760280aa3b3ece0/stateless_tests__aarch64_.html

**Comment by devcrafter** [comment]
> @devcrafter the test about part_log has failed, and it should be investigated:
> 
> https://s3.amazonaws.com/clickhouse-test-reports/40305/6fe8b61345c680705a89b1a45760280aa3b3ece0/stateless_tests__aarch64_.html

@CheSema Please could you check the test failure? AFAIS, you've added it recently. This change is irrelevant to the test

**Comment by devcrafter** [comment]
02277_full_sort_join_misc fails sporadically - created #40977

**Comment by devcrafter** [comment]
01281_group_by_limit_memory_tracking is flaky

see https://play.clickhouse.com/play?user=play&url=https%3A%2F%2Fplay.clickhouse.com%2F#U0VMRUNUICogRlJPTSBjaGVja3MgV0hFUkUgdGVzdF9zdGF0dXMgPSAnRkFJTCcgQU5EIHRlc3RfbmFtZSA9ICcwMTI4MV9ncm91cF9ieV9saW1pdF9tZW1vcnlfdHJhY2tpbmcnCk9SREVSIEJZIGNoZWNrX3N0YXJ0X3RpbWUgREVTQwo=

**Comment by CheSema** [comment]
> 

Hi Igor. You are right that noticed and bring my attention to this. This is my test indeed. Thanks.

This test was created with a flaw from the start. Recently I have fixed it. Here is the fix
https://github.com/ClickHouse/ClickHouse/pull/40455

I see that here is the failure with the code before PR 40455 was merged. (sql file was used in old version, sh file in new one)
There is nothing to investigate for now. If I found fresh flail, I will investigate it.

**Pull request merged**
