### PR TITLE
Fix for positional arguments

### LINKED ISSUE #40634: enable_positional_arguments converts fields into numbers
enable_positional_arguments converts fields into numbers when using construction like `0 as data GROUP BY data`

```
CREATE TABLE `test`
(
	`id`  UInt32,
	`time` UInt32,
	INDEX `id` (`id`) TYPE set(0) GRANULARITY 3,
	INDEX `time` (`time`) TYPE minmax GRANULARITY 3
) ENGINE = MergeTree()
ORDER BY (`time`);

INSERT INTO `test` (`id`, `time`) VALUES (0, 1600000000), (1, 1600000000), (2, 1600000000), (3, 1600000000), (4, 1600000000), (5, 1600000000), (10, 1610000000), (11, 1610000000), (12, 1610000000), (13, 1610000000), (14, 1610000000), (20, 1620000000);

SELECT COUNT(*) as `value`, 0 as `data` FROM `test` GROUP BY `data` SETTINGS enable_positional_arguments=1;

DROP TABLE `test`;
```

SELECT will return
_Received exception from server (version 22.8.2):
Code: 43. DB::Exception: Received from localhost:9000. DB::Exception: Positional argument out of bounds: 0 (exprected in range [1, 2]. (ILLEGAL_TYPE_OF_ARGUMENT)_

Expected:
```
┌─value─┬─data─┐
│    12 │    0 │
└───────┴──────┘
```

### PR DESCRIPTION
**Pull request by kssenii**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in official stable or prestable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix positional arguments exception Positional argument out of bounds. Closes https://github.com/ClickHouse/ClickHouse/issues/40634.

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
> fatal: unable to access 'https://github.com/ClickHouse/clickhouse-odbc.git/': The requested URL returned error: 500
2022-09-11 23:42:23 remote: Internal Server Error.

GitHub was down.

**Comment by den-crane** [comment]
Let's backport it to 22.8 to fix this issue in LTS.

**Comment by den-crane** [comment]
@Felixoid it seems must-backport magic does not work here

**Comment by Felixoid** [comment]
It looks like some PRs are missing in the search https://github.com/ClickHouse/ClickHouse/blob/master/tests/ci/cherry_pick.py#L325, but I can see them by a normal search https://github.com/search?q=type%3Apr+-label%3Apr-backports-created+label%3Apr-must-backport+merged%3A2022-03-03..2023-01-20

Will dig into it tomorrow

**Comment by Felixoid** [comment]
Well, again we have an issue after https://github.com/ClickHouse/ClickHouse/pull/43829

Now the https://github.com/ClickHouse/ClickHouse/blob/master/tests/ci/cherry_pick.py#L315-L318 executes `git merge-base origin/22.3 origin/master` and there is:

```
commit 3eec14790628077ce56bf74e92745f3ea5c917fc
Merge: 120234b512d c822c8161ff
Author: Dan Roscigno <dan@roscigno.com>
Date:   Tue Nov 8 20:27:14 2022 -0500
```

I'll try to find more reliable way to find the first commit

**Comment by Felixoid** [comment]
Should be fixed in #45466, let's see https://github.com/ClickHouse/ClickHouse/actions/runs/3967814934

**Comment by Felixoid** [comment]
Well, obviously, we can't automatically create a backport for anything merged in https://github.com/ClickHouse/ClickHouse/pull/43829, since `git` consider it already being in 22.3

**Pull request merged**
