### PR TITLE
Support SNI in https connections to remote resources

### LINKED ISSUE #10055: SSL connection to external website does not work
**Describe the bug**
```
$ clickhouse-local --query "SELECT count() FROM url('https://data.gharchive.org/2015-01-01-15.json.gz', TSV, 'data String')"
SSL Exception: error:14000410:SSL routines::sslv3 alert handshake failure
```

### PR DESCRIPTION
**Pull request by alexey-milovidov**
Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Support SNI in https connections to remote resources. This will allow to connect to Cloudflare servers that require SNI. This fixes #10055.

Detailed description / Documentation draft:
It may slowdown secure replication because DNS request will be performed for every request. See https://github.com/pocoproject/poco/issues/3123
This PR does nothing for SNI support in clickhouse-server itself.

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
A test:

```
SELECT
    JSONExtractString(data, 'actor', 'login') AS name,
    count() AS c
FROM url('https://data.gharchive.org/2015-01-01-15.json.gz', JSONAsString, 'data String')
GROUP BY name
ORDER BY count() DESC
LIMIT 20

Query id: b830fef5-da3e-4cfb-9078-623e2812903f

┌─name──────────────────┬──c─┐
│ guybedford            │ 95 │
│ KenanSulayman         │ 80 │
│ opencm                │ 79 │
│ automatic-frog        │ 62 │
│ stevewest             │ 60 │
│ altmer                │ 43 │
│ mirror-updates        │ 42 │
│ ARoiD                 │ 40 │
│ Ocramius              │ 37 │
│ peternewman           │ 36 │
│ izuzero               │ 33 │
│ hex7c0                │ 33 │
│ candelorimarco        │ 31 │
│ greysteil             │ 29 │
│ qdm                   │ 29 │
│ brunocarvalhodearaujo │ 28 │
│ jessemillar           │ 28 │
│ floscher              │ 26 │
│ samsonasik            │ 25 │
│ greatfire             │ 24 │
└───────────────────────┴────┘
```

**Comment by filimonov** [comment]
openssl has needed tools to create a mock server:

Check that out

```bash
# bit better/safer to have those hosts predefined...

grep -qE '\slocalhost($|\s|\n|\r)' /etc/hosts || echo '127.0.0.1 localhost' >> /etc/hosts
# actually we can use just localhost instead (simpler) but that is more expressive
grep -qE '\sabc\.localhost($|\s|\n|\r)' /etc/hosts || echo '127.0.0.1 abc.localhost' >> /etc/hosts
# cat /etc/hosts 

# openssl s_server has options '-servername_host ...', '-cert2 ...', '-key2 ...', '-servername_fatal'
# This allows testing the HostName extension for a specific single host name ('-cert' and '-key' remain
# fallbacks for handshakes without HostName negotiation).
# If the unrecognized_name alert has to be sent, this by default is a warning; it becomes fatal with
# the '-servername_fatal' option.

openssl s_server \
    -www -accept 44330 \
    -key /etc/clickhouse-server/server.key \
    -cert /etc/clickhouse-server/server.crt \
    -servername abc.localhost \
    -key2 /etc/clickhouse-server/server.key \
    -cert2 /etc/clickhouse-server/server.crt \
    -servername_fatal \
    -debug &>./openssl_server.log \
    &

OPENSSL_SERVER_PID=$!

clickhouse-local --query "SELECT * FROM url('https://127.0.0.1:44330/', TSVRaw, 'data String')" -- --openSSL.client.invalidCertificateHandler.name=AcceptCertificateHandler
# fails & bug (according to rfc4366.txt p. 3.1: Literal IPv4 and IPv6 addresses are not permitted in "HostName")

clickhouse-local --query "SELECT * FROM url('https://localhost:44330/', TSVRaw, 'data String')" -- --openSSL.client.invalidCertificateHandler.name=AcceptCertificateHandler
# fails, unrecognized name 

clickhouse-local --query "SELECT * FROM url('https://abc.localhost:44330/', TSVRaw, 'data String')" -- --openSSL.client.invalidCertificateHandler.name=AcceptCertificateHandler
# works 

kill $OPENSSL_SERVER_PID
wait $OPENSSL_SERVER_PID

grep 'Hostname in TLS extension' ./openssl_server.log
```

**Comment by abyss7** [comment]
Looks like the query in your test hangs for more than 10 minutes for some reason

**Comment by alexey-milovidov** [comment]
We decided to merge this PR without a test and @filimonov will help to write it.

**Pull request merged**
