### PR TITLE
Correct nullability checker for LowCardinality nested columns

### PR DESCRIPTION
**Pull request by myrrc**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Added the checker as neither calling `lc->isNullable()` nor calling `ls->getDictionaryPtr()->isNullable()` would return the correct result.

### CODE REVIEW

**Comment by myrrc** [comment]
Related: #14590

**Comment by alexey-milovidov** [comment]
Maybe add a test?

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
It's 100% green. Let's add a specific test (to make sure it won't be introduced later) and merge after fast test check.

**Comment by alexey-milovidov** [comment]
The message for changelog is not actually useful.

**Comment by alexey-milovidov** [comment]
I write `Fix function `has` with `LowCardinality` of `Nullable`.`

**Pull request merged**
