### PR TITLE
What happens if I remove everything in msan_suppressions?

### PR DESCRIPTION
**Pull request by rschu1ze**
Cf. https://github.com/ClickHouse/ClickHouse/pull/49678#discussion_r1192252923

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by robot-clickhouse** [comment]
This is an automated comment for commit fa3d564cc6bf2df00276195adf983eae94221a9b with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/49829/fa3d564cc6bf2df00276195adf983eae94221a9b/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Comment by qoega** [comment]
Nothing related fails. We have no tests that trigger this assertions?

**Comment by rschu1ze** [comment]
The reason nothing failed is that @azat fixed the blacklisted msan issues manually in the [Clang 16 upgrade](#49678).

But msan should not have been failing in the [Clang 16 upgrade](#49678) when these issues were not yet fixed. Looks like `-fsanitize-blacklist` broke with the upgrade to Clang 16. The v16 release notes say nothing about changes in this area. Parameter "blacklist" [was renamed at some point](https://reviews.llvm.org/D101832) o "ignorelist" but the old name theoretically continues to work. So it is not really clear why it broke.

Anyways, the ignorelist is a weird out-of-source second method to suppress sanitizer failures (GCC devs [agree](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=61978#c1)). Guess we can do without it.

**Comment by azat** [comment]
FWIW I've verified `-fsanitize-blacklist` and it works:

```sh
$ cat umr.cc
#include <stdio.h>

int main(int argc, char** argv) {
  int* a = new int[10];
  a[5] = 0;
  if (a[argc])
    printf("xx\n");
  return 0;
}

$ cat blacklist.txt
# Maybe comments breaks something?
fun:main

# Maybe comments breaks something?

$ clang++-16 -fsanitize=memory -fno-omit-frame-pointer -g -O2 umr.cc -o umr && ./umr
==25090==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x5555555fd336 in main /tmp/test-msan/umr.cc:6:7
    #1 0x7ffff7a3984f  (/usr/lib/libc.so.6+0x2384f) (BuildId: 2f005a79cd1a8e385972f5a102f16adba414d75e)
    #2 0x7ffff7a39909 in __libc_start_main (/usr/lib/libc.so.6+0x23909) (BuildId: 2f005a79cd1a8e385972f5a102f16adba414d75e)
    #3 0x555555573294 in _start (/tmp/test-msan/umr+0x1f294)

SUMMARY: MemorySanitizer: use-of-uninitialized-value /tmp/test-msan/umr.cc:6:7 in main
Exiting

$ clang++-16 -fsanitize-blacklist=blacklist.txt -fsanitize=memory -fno-omit-frame-pointer -g -O2 umr.cc -o umr && ./umr

```

So there is something not that trivial.

**Review by hanfei1991 — APPROVED** [review]

**Comment by rschu1ze** [comment]
ClickHouse Stress Test (ubsan): #49553

**Pull request merged**
