### PR TITLE
CI: Scale down AutoScaling Groups from runners

### PR DESCRIPTION
**Pull request by maxknv**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
...

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [x]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [x]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-ch-test-poll** [comment]
*This is an automated comment for commit 249f180feed6723f4dbec9175f8e5339fa2e838b with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/66622/249f180feed6723f4dbec9175f8e5339fa2e838b/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Style check</td><td>Runs a set of checks to keep the code style clean. If some of tests failed, see the related log from the report</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/66622/249f180feed6723f4dbec9175f8e5339fa2e838b/style_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Review by alexey-milovidov — APPROVED** [review]
I didn't understand the purpose, but LGTM.

**Comment by alexey-milovidov** [comment]
What does it mean?

**Comment by maxknv** [comment]
> What does it mean?
I want to try a different approach for scaling down the Auto Scaling Group (ASG).

BEFORE: The Lambda function used for auto-scaling would scale down the ASG once it detected more runners than running jobs.

NEW APPROACH: When a runner finishes its assigned job and has no more job assigned, it terminates itself and decreases the ASG capacity by one.

Motivation: This approach results in less code, fewer API calls, and presumably reduced chance of a race condition.

Note: This is a blind experiment. We need to increase observability to better understand the runners' lifecycle.

**Pull request merged**
