### PR TITLE
Added a script to analyze git repository in ClickHouse

### PR DESCRIPTION
**Pull request by alexey-milovidov**
Changelog category (leave one):
- New Feature

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Added a script to import git repository in ClickHouse for further analysis.

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
It has very inefficient algorithm and the speed is about one month per day (for recent commits).
We will have to either leave it working for about a month or rewrite (to calculate "blame" incrementally).

**Comment by BohuTANG** [comment]
It would be interesting if we make a git table engine, synchronized regularly :D

**Comment by alexey-milovidov** [comment]
There are different tables that can be implemented:

1. Current snapshot of the repository: information about every line of every file in master with full blame info.
Allows to answer questions like:
- list files with maximum number of authors;
- show me the oldest lines of code in the repository;
- show me the files with longest history;
- list favorite files for author;
- list largest files with lowest number of authors;
- at what weekday the code has highest chance to stay in repository;
- the distribution of code age across repository;
- files sorted by average code age;
- quickly show file with blame info or just recreate the working copy;

2. Commits with diffs: information about every line in every file that was added or deleted in every commit with full commit info.
Allows to answer questions like:
- commits and lines of code distribution by time; by weekday, by author; for specific subdirectories;
- show history for every subdirectory, file, line of file, the number of changes (lines and commits) across time; how the number of contributors was changed across time.

Both tables can be created very easily in a matter of minutes.
What I have tried to implement in this PR is another, very heavy table:

3. Shapshots of repository: information about every line of every file in *every commit* with full blame info.

This table is overkill for most of the tasks. It is difficult to create and it will have at least a few billions rows even for such small repository like ClickHouse. But maybe it will allow to answer more questions.

**Comment by zhang2014** [comment]
Very interesting. 😂 But `mv dbms -> src`

**Comment by BohuTANG** [comment]
> Very interesting.  But `mv dbms -> src`

We should skip this commits and file changes

**Comment by alexey-milovidov** [comment]
Closed in favor of #14471.

**Comment by alexey-milovidov** [comment]
@zhang2014 `SELECT replaceRegexpOne(path, '^dbms/', '') AS path ...` completely solves it.

**Comment by filimonov** [comment]
I've found today:  https://askgit.com/

Also:
https://github.com/augmentable-dev/askgit
https://willschenk.com/articles/2020/using_askgit/

```
docker run --rm -it -v `pwd`:/repo:ro augmentable/askgit --interactive
```

It may be interesting to compare them a bit.

**Pull request closed without merging**
