### PR TITLE
Table pre-defined index hint.

### PR DESCRIPTION
**Pull request by amosbird**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- New Feature

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Add `INDEX HINT` storage definition to storage engines (currently only implemented in StorageDistributed). This is for https://github.com/ClickHouse/ClickHouse/issues/21238 . This depends on https://github.com/ClickHouse/ClickHouse/pull/21304 .

Detailed description / Documentation draft:

.

### CODE REVIEW

**Comment by nikitamikhaylov** [comment]
@amosbird Why not create one distributed table and a bunch on VIEW's on top of it?

**Comment by amosbird** [comment]
> @amosbird Why not create one distributed table and a bunch on VIEW's on top of it?

It's not easy to keep all these tables' metadata in sync. And iirc VIEW turns distributed table query into subqueries which will disable GLOBAL IN/JOIN and distributed IN/JOIN.

**Comment by nikitamikhaylov** [comment]
@amosbird Why not to simply add expression from FILTER BY (or INDEX HINT) to WHERE clause? It will trigger KeyCondition in the same way.

**Comment by amosbird** [comment]
> @amosbird Why not to simply add expression from FILTER BY (or INDEX HINT) to WHERE clause? It will trigger KeyCondition in the same way.

It's to bind this condition to a given table without intruding normal users. The condition might refer to `dictGet` functions so that we can toggle visibility in other ways.

**Comment by amosbird** [comment]
It seems we should utilize row policy filter for this purpose. However, currently row filters don't take advantage of any indices. Maybe we should extend it. Or is there any consideration?

**Pull request closed without merging**
