### PR TITLE
MaterializedMySQL: Add error message to the user that CREATE DATABASE queries are not supported

### PR DESCRIPTION
**Pull request by subkanthi**
### Changelog category (leave one):
- Bug Fix

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Add error message to the user that CREATE DATABASE queries are not supported in MaterializedMySQL

https://github.com/ClickHouse/ClickHouse/issues/42341

### CODE REVIEW

**Comment by robot-ch-test-poll3** [comment]
This is an automated comment for commit 76a5b82db39f8eca7c851a3ed5a920fd5ac49afd with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/52495/76a5b82db39f8eca7c851a3ed5a920fd5ac49afd/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Comment by tavplubix** [comment]
Integration tests failures from the previous run were probably related to the change, restarting CI doesn't make sense

**Comment by subkanthi** [comment]
> Integration tests failures from the previous run were probably related to the change, restarting CI doesn't make sense

Hi @tavplubix , Can this be merged, it will provide more context to the user, thanks.

**Comment by tavplubix** [comment]
> > Integration tests failures from the previous run were probably related to the change, restarting CI doesn't make sense
> 
> Hi @tavplubix , Can this be merged, it will provide more context to the user, thanks.

@subkanthi, I'm sorry, but no, it can not. It breaks integration tests, and it must be fixed before merging.

https://s3.amazonaws.com/clickhouse-test-reports/52495/6321ae41a069cf65ffbe14e214676f9013ad315e/integration_tests__asan__[4_6].html

https://s3.amazonaws.com/clickhouse-test-reports/52495/6321ae41a069cf65ffbe14e214676f9013ad315e/integration_tests__release__[4_4].html

**Comment by subkanthi** [comment]
> > > Integration tests failures from the previous run were probably related to the change, restarting CI doesn't make sense
> > 
> > 
> > Hi @tavplubix , Can this be merged, it will provide more context to the user, thanks.
> 
> @subkanthi, I'm sorry, but no, it can not. It breaks integration tests, and it must be fixed before merging.
> 
> [https://s3.amazonaws.com/clickhouse-test-reports/52495/6321ae41a069cf65ffbe14e214676f9013ad315e/integration_tests__asan__[4_6].html](https://s3.amazonaws.com/clickhouse-test-reports/52495/6321ae41a069cf65ffbe14e214676f9013ad315e/integration_tests__asan__%5B4_6%5D.html)
> 
> [https://s3.amazonaws.com/clickhouse-test-reports/52495/6321ae41a069cf65ffbe14e214676f9013ad315e/integration_tests__release__[4_4].html](https://s3.amazonaws.com/clickhouse-test-reports/52495/6321ae41a069cf65ffbe14e214676f9013ad315e/integration_tests__release__%5B4_4%5D.html)
> 
> [https://s3.amazonaws.com/clickhouse-test-reports/52495/6321ae41a069cf65ffbe14e214676f9013ad315e/integration_tests__tsan__[4_6].html](https://s3.amazonaws.com/clickhouse-test-reports/52495/6321ae41a069cf65ffbe14e214676f9013ad315e/integration_tests__tsan__%5B4_6%5D.html)

Thanks, I will take a look at the integration tests.

**Comment by alexey-milovidov** [comment]
I see integration tests were not fixed. Please reopen when there will be changes.

**Pull request closed without merging**
