### PR TITLE
Fix stress test after 36639

### PR DESCRIPTION
**Pull request by kssenii**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

https://github.com/ClickHouse/ClickHouse/pull/36639

https://s3.amazonaws.com/clickhouse-test-reports/36639/35b8d302da85472572c42e7d31932ff6825e21ea/stress_test__debug__actions_/fatal_messages.txt

### CODE REVIEW

**Comment by kssenii** [comment]
@Mergifyio update

**Review by tavplubix — APPROVED** [review]

**Comment by kssenii** [comment]
> Stress test (debug, actions) — Fatal message in clickhouse-server.log (see fatal_messages.txt)

:expressionless:

**Comment by kssenii** [comment]
@Mergifyio update

**Comment by tavplubix** [comment]
[1cbf672](https://github.com/ClickHouse/ClickHouse/pull/36660/commits/1cbf67223794d161ac82679d1d1f9e88cee39b2c) - Stress test (debug, actions):
```
/var/log/clickhouse-server/clickhouse-server.err.log:2022.04.29 03:05:45.319954 [ 4931 ] {} <Fatal> BaseDaemon: ########################################
/var/log/clickhouse-server/clickhouse-server.err.log:2022.04.29 03:05:45.437839 [ 4931 ] {} <Fatal> BaseDaemon: (version 22.5.1.1, build id: 4EA65F8EA4C114FE) (from thread 767) (query_id: 0b8eadbb-6941-4298-b6f0-455db58dfd0b::201403_1_7_1) (query: ) Received signal Aborted (6)
/var/log/clickhouse-server/clickhouse-server.err.log:2022.04.29 03:05:45.470491 [ 4931 ] {} <Fatal> BaseDaemon: 
/var/log/clickhouse-server/clickhouse-server.err.log:2022.04.29 03:05:45.502150 [ 4931 ] {} <Fatal> BaseDaemon: Stack trace: 0x7f8be8bb803b 0x7f8be8b97859 0x7f8be8b97729 0x7f8be8ba9006 0x258d1270 0x258d160f 0x26288b47 0x26286d7d 0x2628ecd3 0x17b73114 0x2620394d 0x17b73114 0x2620394d 0x17b73114 0x27ae927d 0x17b73114 0x27c9fb5d 0x27caaa28 0x27caae76 0x27e190f3 0x27e18ff1 0x27b999f1 0x27baf8b8 0x27baf875 0x27baf83d 0x27baf815 0x27baf7dd 0x25cba966 0x25cb2d35 0x27b99bb2 0x27b9961b 0x27f52b67 0x27bc2e0f 0x27bc4882 0x27bcbef8 0x27bcbeb5 0x27bcbe7d 0x27bcbe55 0x27bcbe1d 0x17bcdb06 0x17bca035
/var/log/clickhouse-server/clickhouse-server.err.log:2022.04.29 03:05:45.517957 [ 4931 ] {} <Fatal> BaseDaemon: 4. raise @ 0x7f8be8bb803b in ?
/var/log/clickhouse-server/clickhouse-server.err.log:2022.04.29 03:05:45.520307 [ 4931 ] {} <Fatal> BaseDaemon: 5. abort @ 0x7f8be8b97859 in ?
/var/log/clickhouse-server/clickhouse-server.err.log:2022.04.29 03:05:45.522046 [ 4931 ] {} <Fatal> BaseDaemon: 6. ? @ 0x7f8be8b97729 in ?
/var/log/clickhouse-server/clickhouse-server.err.log:2022.04.29 03:05:45.525047 [ 4931 ] {} <Fatal> BaseDaemon: 7. ? @ 0x7f8be8ba9006 in ?
/var/log/clickhouse-server/clickhouse-server.err.log:2022.04.29 03:05:45.985307 [ 4931 ] {} <Fatal> BaseDaemon: 8. /build/build_docker/../src/Common/FileSegment.cpp:657: DB::FileSegment::assertDetachedStatus(std::__1::lock_guard<std::__1::mutex>&) const @ 0x258d1270 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2022.04.29 03:05:46.198311 [ 4931 ] {} <Fatal> BaseDaemon: 9. /build/build_docker/../src/Common/FileSegment.cpp:718: DB::FileSegmentsHolder::~FileSegmentsHolder() @ 0x258d160f in /usr/bin/clickhouse
```

**Comment by kssenii** [comment]
Not really by chance https://github.com/ClickHouse/ClickHouse/pull/36743

**Pull request merged**
