### PR TITLE
Add ability to create defaults from aliases

### LINKED ISSUE #2283: Can't use alias columns in default expressions
Sample:
```sql
CREATE TABLE test_default_using_alias
(
    what String, 
    a String DEFAULT concat(c, ' is great'), 
    b String DEFAULT concat(c, ' is fast'), 
    c String ALIAS concat(what, 'House')
)
ENGINE = TinyLog

:) insert into test_default_using_alias(what) VALUES ('Click');
Received exception from server (version 1.1.54362):
Code: 47. DB::Exception: Received from localhost:9000, ::1. DB::Exception: Unknown identifier: c. 

1 rows in set. Elapsed: 0.073 sec. 

:) SELECT a,b FROM test_default_using_alias;

SELECT 
    a, 
    b
FROM test_default_using_alias 

Received exception from server (version 1.1.54362):
Code: 1000. DB::Exception: Received from localhost:9000, ::1. DB::Exception: File not found: /var/lib/clickhouse/data/default/test_default_using_alias/a.bin. 
```

### PR DESCRIPTION
**Pull request by alesapin**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Now it's possible to create a column with `DEFAULT` expression which depends on a column with default `ALIAS` expression.

Fixes #2283 #8603

### CODE REVIEW

**Comment by alesapin** [comment]
Merge after https://github.com/ClickHouse/ClickHouse/pull/9481.

**Comment by qoega** [comment]
I think we should write in docs explicitly what we support in default and what we don't.
https://github.com/ClickHouse/ClickHouse/blame/master/docs/en/query_language/create.md#L78-L88

**Comment by filimonov** [comment]
Not clear what with complicated aliases / defaults which depend on other aliases / defaults etc, maybe test for that? 

I.e. something like 
```
create table test (
  a1 UInt64 DEFAULT a+1,
  a1 UInt64 DEFAULT a+1,
  a2 UInt64 DEFAULT a3+a4,
  a3 UInt64 DEFAULT a2+1,
  a4 UInt64 ALIAS      a3+1
) Engine=Log;


-- here if any 2 columns are provided in insert third can be calculated. 
creare table pythagoras (
  a Float64 DEFAULT sqrt(c*c - b*b),
  b Float64 DEFAULT sqrt(c*c - a*a),
  c Float64 DEFAULT sqrt(a*a + b*b)
) Engine=Log;
```

That's not very clear how it should behave with circular references (as depending on columns provided at insert it can be resolvable or not), it seems the simplest option would be just to forbid such scenarios explicitly. 

Can you check how it works / create a test for that?

**Comment by alexey-milovidov** [comment]
```
CREATE TABLE test (a DEFAULT b, b DEFAULT a) ENGINE = Memory
```
It works!

... and what are the types of `a` and `b`?

**Comment by alexey-milovidov** [comment]
I will add a test with cyclic aliases and explicit types.
Then @alesapin will prohibit cyclic aliases with unknown types.

**Comment by alexey-milovidov** [comment]
But it does not work if I specify data types.

**Comment by alexey-milovidov** [comment]
@filimonov Your queries don't work. I will add a test to ensure that they don't work.

**Comment by alexey-milovidov** [comment]
Will merge and then fix the case of
```
CREATE TABLE test (a DEFAULT b, b DEFAULT a) ENGINE = Memory
```
In a separate PR.

**Comment by alexey-milovidov** [comment]
@alesapin I think that we can permit tables like this:
```
CREATE TABLE default.test (`a` DEFAULT b, `b` DEFAULT a) ENGINE = Memory
```

To allow a user to insert one or another column. This have its use.

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
> CREATE TABLE test (a DEFAULT b, b DEFAULT a) ENGINE = Memory

I can execute this query and it will prevent the server to start!

**Comment by filimonov** [comment]
Maybe we should make a note in changelog - just in case if somebody was using circular aliases.

**Comment by alesapin** [comment]
> > CREATE TABLE test (a DEFAULT b, b DEFAULT a) ENGINE = Memory
> 
> I can execute this query and it will prevent the server to start!

https://github.com/ClickHouse/ClickHouse/pull/9603 Fix is here.

**Pull request merged**
