### PR TITLE
independent registration of interpreters

### PR DESCRIPTION
**Pull request by bharatnc**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Allow registering interpreters independently.

Refactor the interpreter factory to enable the registration of each interpreter independently.
cc: @alexey-milovidov

### CODE REVIEW

**Comment by robot-ch-test-poll4** [comment]
*This is an automated comment for commit 2c45b911b9439ab113e402ea3bef2cba72ef31c5 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/58443/2c45b911b9439ab113e402ea3bef2cba72ef31c5/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/58443/2c45b911b9439ab113e402ea3bef2cba72ef31c5/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Comment by bharatnc** [comment]
Build failures for [c1c8f0e](https://github.com/ClickHouse/ClickHouse/pull/58443/commits/c1c8f0ec5cd74dbe82227aee0b768515453d701a) don't look related.
I have just merged into master to pull in latest changes just in case ([ea3da0c](https://github.com/ClickHouse/ClickHouse/pull/58443/commits/ea3da0c785146e389fad4c528267f8073bc3ac85))
[ClickHouse Stateless Tests ](https://s3.amazonaws.com/clickhouse-test-reports/58443/c1c8f0ec5cd74dbe82227aee0b768515453d701a/stateless_tests__release__s3_storage__[2_2].html)
```
01747_system_session_log_long
01702_system_query_log
```
[ClickHouse Upgrade Check (debug) ](https://s3.amazonaws.com/clickhouse-test-reports/58443/c1c8f0ec5cd74dbe82227aee0b768515453d701a/upgrade_check__debug_.html)

**Comment by bharatnc** [comment]
PR is ready for review.

**Comment by al13n321** [comment]
The remaining two CI failures are known problems: https://github.com/ClickHouse/ClickHouse/issues/57893 , https://github.com/ClickHouse/ClickHouse/issues/58319

**Pull request merged**
