### PR TITLE
Fix fasttest retry for failed tests

### PR DESCRIPTION
**Pull request by alesapin**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by alesapin** [comment]
Fast test OK

**Comment by alexey-milovidov** [comment]
Assertion failed when using float in PREWHERE. Need to create a task...

**Review by alexey-milovidov — APPROVED** [review]
The script becomes more happy.

**Comment by alesapin** [comment]
Reported https://github.com/ClickHouse/ClickHouse/issues/20870

**Pull request merged**
