### PR TITLE
Allow Tuple data type inside of Nullable

### PR DESCRIPTION
**Pull request by novikd**
### Changelog category (leave one):

- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Allow Tuple data type inside of Nullable.

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### CODE REVIEW

**Comment by robot-clickhouse** [comment]
*This is an automated comment for commit 82e1c49a91481193c052e4615ca70ae68ce67b56 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/59530/82e1c49a91481193c052e4615ca70ae68ce67b56/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/59530/82e1c49a91481193c052e4615ca70ae68ce67b56/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Comment by nikitamikhaylov** [comment]
What about DataTypeMap? I think the only type which cannot be inside Nullable is DataTypeAggregateFunction.

**Comment by amosbird** [comment]
What about DataTypeArray  https://github.com/ClickHouse/ClickHouse/issues/1062

**Comment by alexey-milovidov** [comment]
Duplicate of https://github.com/ClickHouse/ClickHouse/pull/53443.

**Pull request closed without merging**
