### PR TITLE
Fix stress tests

### PR DESCRIPTION
**Pull request by azat**
Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Right now stress tests almost always fails because service queries (hung check, DROP DATABASE, ...) cannot be executed when total memory limit exceeded.

To avoid this:
- `max_server_memory_usage` had been replaced with `max_memory_usage_for_user` (`max_memory_usage_for_user` is used as a soft limit, and `max_server_memory_usage` as a hard, so queries can allow memory overcommit, using `max_memory_usage_for_user=0` instead of relying on `max_untracked_memory` hack)
- add `SYSTEM DROP MARK CACHE` (just in case, since some of runs uses static database and some tables may left)
- apply `--client-option` in `clickhouse-test` for various service queries (so that it will apply new settings correctly)
- adds memory overcommit via `max_untracked_memory` (this was done just in case)

### CODE REVIEW

**Comment by alesapin** [comment]
`Setting 00001_select_1 is neither a builtin setting nor started with the prefix 'custom_' registered for user-defined settings`

**Comment by alesapin** [comment]
Maybe try `SYSTEM DROP MARK CACHE`?

**Comment by azat** [comment]
>Maybe try SYSTEM DROP MARK CACHE?

Great idea (since some stress runs uses predefined databases that will be preserved), let's try.

**Comment by azat** [comment]
>Stress test (address, actions) — No errors found
>Stress test (debug, actions) — No errors found
>Stress test (memory, actions) — No errors found
>[Stress test (thread, actions) — No errors found](https://s3.amazonaws.com/clickhouse-test-reports/32164/78e7532818e6e5a803344d4605c2cf0f6e62522e/stress_test__thread__actions_.html)
>Stress test (undefined, actions) — No errors found

Passed, with memory pressure:

```
Code: 219. DB::Exception: Received from localhost:9000. DB::Exception: Cannot drop: filesystem error: in remove: Directory not empty [/var/lib/clickhouse/data/test_31/]. Probably database contain some detached tables or metadata leftovers from Ordinary engine. If you want to remove all data anyway, try to attach database back and drop it again with enabled force_remove_data_recursively_on_drop setting. (DATABASE_NOT_EMPTY)
(query: DROP DATABASE test_31)
2021-12-04 00:02:06,717 Checking if some queries hung
WARNING: jinja2 not installed! Template tests will be skipped.
Using queries from '/usr/share/clickhouse-test/queries' directory
Using clickhouse-client as client program (expecting split build)
Connecting to ClickHouse server... OK

Running 1 stateless tests (MainProcess).

00001_select_1:                                                         [ OK ]

1 tests passed. 0 tests skipped. 0.34 s elapsed (MainProcess).

0 tests passed. 0 tests skipped. 0.00 s elapsed (MainProcess).

No queries hung.
All tests have finished.
```

**Comment by azat** [comment]
>[Stress test (thread, actions) — Hung check failed](https://s3.amazonaws.com/clickhouse-test-reports/32164/22b081f2a50b7ad8c5565eefff185dba56401b95/stress_test__thread__actions_.html)

```
Code: 241. DB::Exception: Received from localhost:9000. DB::Exception: Memory limit (total) exceeded: would use 35.64 GiB (attempt to allocate chunk of 0 bytes), maximum: 34.30 GiB: While executing AggregatingTransform: While processing (SELECT maxOrDefault(300 - elapsed) + 1 FROM system.processes WHERE (query NOT LIKE '%from system.processes%') AND (elapsed < 300)) AS _subquery621: While processing ((SELECT maxOrDefault(300 - elapsed) + 1 FROM system.processes WHERE (query NOT LIKE '%from system.processes%') AND (elapsed < 300)) AS _subquery621) / 300: While processing sleepEachRow(((SELECT maxOrDefault(300 - elapsed) + 1 FROM system.processes WHERE (query NOT LIKE '%from system.processes%') AND (elapsed < 300)) AS _subquery621) / 300). (MEMORY_LIMIT_EXCEEDED)
(query: 
    select sleepEachRow((
        select maxOrDefault(300 - elapsed) + 1
        from system.processes
        where query not like '%from system.processes%' and elapsed < 300
    ) / 300)
    from numbers(300)
    format Null
    )
```

Right now this cannot be fixed since this calls `CurrentMemoryTracker::check`

```
Server is not responding. Cannot execute 'SELECT 1' query.             If you are using split build, you have to specify -c option.
```

Exception happens too early:

```
2021.12.04 01:49:43.580768 [ 1604566 ] {} <Error> ServerErrorHandler: Code: 241. DB::Exception: Memory limit (total) exceeded: would use 35.61 GiB (attempt to allocate chunk of 1048591 bytes),
 maximum: 34.30 GiB. (MEMORY_LIMIT_EXCEEDED), Stack trace (when copying this message, always include the lines below):

0. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/exception:0: Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @
 0x1aad0f3b in /usr/bin/clickhouse
1. ./obj-x86_64-linux-gnu/../src/Common/Exception.cpp:57: DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x
9dda9fc in /usr/bin/clickhouse
2. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/string:1444: DB::Exception::Exception<char const*, char const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocato
r<char> >, long&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >(int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<cha
r> > const&, char const*&&, char const*&&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&, long&, std::__1::basic_string<char, std::__1::char_traits<ch
ar>, std::__1::allocator<char> >&&) @ 0x9e02beb in /usr/bin/clickhouse
3. ./obj-x86_64-linux-gnu/../src/Common/MemoryTracker.cpp:226: MemoryTracker::allocImpl(long, bool) @ 0x9e019ac in /usr/bin/clickhouse
4. ./obj-x86_64-linux-gnu/../src/Common/CurrentMemoryTracker.cpp:56: CurrentMemoryTracker::(anonymous namespace)::allocImpl(long, bool) @ 0x9e0c559 in /usr/bin/clickhouse
5. ./obj-x86_64-linux-gnu/../src/Common/CurrentMemoryTracker.cpp:69: CurrentMemoryTracker::alloc(long) @ 0x9e0c3ff in /usr/bin/clickhouse
6. ./obj-x86_64-linux-gnu/../src/Common/Allocator.h:96: DB::Memory<Allocator<false, false> >::alloc() @ 0x9e0990a in /usr/bin/clickhouse
7. ./obj-x86_64-linux-gnu/../src/IO/BufferWithOwnMemory.h:74: DB::ReadBufferFromPocoSocket::ReadBufferFromPocoSocket(Poco::Net::Socket&, unsigned long) @ 0x160f6965 in /usr/bin/clickhouse
8. ./obj-x86_64-linux-gnu/../contrib/poco/Net/include/Poco/Net/Socket.h:578: DB::HTTPServerRequest::HTTPServerRequest(std::__1::shared_ptr<DB::Context const>, DB::HTTPServerResponse&, Poco::Ne
t::HTTPServerSession&) @ 0x1766df09 in /usr/bin/clickhouse
9. ./obj-x86_64-linux-gnu/../src/Server/HTTP/HTTPServerConnection.cpp:33: DB::HTTPServerConnection::run() @ 0x1766cc3c in /usr/bin/clickhouse
10. ./obj-x86_64-linux-gnu/../contrib/poco/Net/src/TCPServerConnection.cpp:57: Poco::Net::TCPServerConnection::start() @ 0x1a9ed363 in /usr/bin/clickhouse
11. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:1397: Poco::Net::TCPServerDispatcher::run() @ 0x1a9edbd3 in /usr/bin/clickhouse
12. ./obj-x86_64-linux-gnu/../contrib/poco/Foundation/src/ThreadPool.cpp:213: Poco::PooledThread::run() @ 0x1ab72cb6 in /usr/bin/clickhouse
13. ./obj-x86_64-linux-gnu/../contrib/poco/Foundation/src/Thread.cpp:56: Poco::(anonymous namespace)::RunnableHolder::run() @ 0x1ab70e50 in /usr/bin/clickhouse
14. ./obj-x86_64-linux-gnu/../contrib/poco/Foundation/include/Poco/SharedPtr.h:277: Poco::ThreadImpl::runnableEntry(void*) @ 0x1ab6f4c8 in /usr/bin/clickhouse
15. __tsan_thread_start_func @ 0x9d2aebd in /usr/bin/clickhouse
16. ? @ 0x7fc86c57c609 in ?
17. clone @ 0x7fc86c4a3293 in ?
 (version 21.12.1.9956)
```

**Review by tavplubix — APPROVED** [review]

**Comment by tavplubix** [comment]
Performance - flat_dictionary - a query has unexpected duration, cc: @kitaisreal

**Pull request merged**
