### PR TITLE
Add a new system.httpclient_log to record HTTP requests issued from ClickHouse

### PR DESCRIPTION
**Pull request by FrankChen021**
### Changelog category (leave one):
- New Feature

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Add a new system.httpclient_log to record HTTP requests issued from ClickHouse.

### Documentation entry for user-facing changes

- [X] Documentation is written (mandatory for new features)

This is useful for trouble shooting when S3 is used as storage. An example output from this table is:

```text
event_date:     2023-03-15
event_time:     2023-03-15 17:19:05.362259
client:         AWS
query_id:       a7120882-3caa-4c5b-9452-aec3cd1bacc3
trace_id:
span_id:        0
duration_ms:    1301
http_method:    GET
uri:            https://ch-nyc-taxi.s3.eu-west-3.amazonaws.com/tsv/trips_1.tsv.gz
status_code:    206
request_size:   0
response_size:  10485760
exception_code: 0
exception:
```

## Changes Description

1. The original HTTP request code in a for-loop(in PocoHTTPClient.cpp) is extracted as a separated function to simply the ProfileEvent and logging and exception processing, but the core code inside the loop remains unchanged. Viewing the code change is a little bit hard.
2. logging HTTP requests to StorageURL is not added in this PR because we're not using StorageURL heavily. But I can add it later

### CODE REVIEW

**Comment by FrankChen021** [comment]
The failed test case looks has nothing to do with the changes in this PR.

02142_http_with_query_parameters | FAIL | 113.85
-- | -- | --
2023-03-16 12:35:29 curl: (28) Operation timed out after 60001 milliseconds with 0 bytes received 2023-03-16 12:35:29 , result: 2023-03-16 12:35:29  2023-03-16 12:35:29  2023-03-16 12:35:29  2023-03-16 12:35:29 stdout: 2023-03-16 12:35:29  2023-03-16 12:35:29  2023-03-16 12:35:29  2023-03-16 12:35:29 MergeTree settings used in test: --ratio_of_defaults_for_sparse_serialization=0.5944243564035934 --prefer_fetch_merged_part_size_threshold=10737418240 --vertical_merge_algorithm_min_rows_to_activate=1 --vertical_merge_algorithm_min_columns_to_activate=100 --min_merge_bytes_to_use_direct_io=5440093969 --index_granularity_bytes=30042210 --merge_max_block_size=11863 --index_granularity=19165 --min_bytes_for_wide_part=965404153 2023-03-16 12:35:29  2023-03-16 12:35:29 Database: test_n3edqkg6

Also, 2 linker errors while other succeeded. don't understand why it fails. Should I make some changes to make files?

https://s3.amazonaws.com/clickhouse-builds/47613/bc26e5de3352a1ca25972700363ab64151cabf0d/package_release/build_log.log

@nikitamikhaylov Could you help take a look?

**Comment by FrankChen021** [comment]
For the link problem, it failed when only clickhouse-keeper is built by executing 'ninja clickhouse-keeper'.

In such case, `IO` directory is compiled and linked, while the newly added class `HttpClientLog`, which is under `Interpreters` directory, is not compiled and linked.

To solve this problem, either we can exclude IO/S3 from he compilation and linkage, or move `HttpClientLog` to the `Common` directory.  I think the 2nd approach is more reasonable.

**Comment by FrankChen021** [comment]
For standalone clickhouse-keeper compilation, it's a little bit tricky to solve the link problem.

clickhouse-keeper has dependency on S3, so `IO/S3` can't be excluded from the compilation.
For the 2nd approach, `HttpClientLog` has dependency to `DataTypes` which are not part of clickhouse-keeper.

Since there's only one static method that's referenced in IO/S3 module, one simple solution is to add a stub method in clickhouse-keeper. What do you think? @nikitamikhaylov

**Comment by FrankChen021** [comment]
The linkage problem for independent keeper is solved by reversing the dependency. Now `PocoHttpClient` does not dependent on the newly added `HttpClientLog`, instead the creator of this client passes the logging function object to the `PocoHttpClient`.

**Comment by FrankChen021** [comment]
Hello @nikitamikhaylov , is there any problems on these changes? Can it be merged? For the failed CI, I don't see there's connection with current changes. If you have any comments, pls let me know.

**Comment by robot-clickhouse** [comment]
This is an automated comment for commit 1f16ead51a92d990a15b20267bfaec1790e9c390 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/47613/1f16ead51a92d990a15b20267bfaec1790e9c390/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Docs Check</td><td>Builds and tests the documentation</td><td>🟡 pending</td></tr>
</table>

**Comment by alexey-milovidov** [comment]
Let's fix the conflicts and continue.

**Comment by alexey-milovidov** [comment]
@FrankChen021 This is valuable PR, please continue.

**Pull request closed without merging**
