### PR TITLE
fix issue #14202

### PR DESCRIPTION
**Pull request by donge**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Fix crash when INERT INTO Kafka engine table from an empty result set with a subquery. 
...

Detailed description / Documentation draft:

...

By adding documentation, you'll allow users to try your new feature immediately, not when someone else will have time to document it later. Documentation is necessary for all features that affect user experience in any way. You can add brief documentation draft above, or add documentation right into your patch as Markdown files in [docs](https://github.com/ClickHouse/ClickHouse/tree/master/docs) folder.

If you are doing this for the first time, it's recommended to read the lightweight [Contributing to ClickHouse Documentation](https://github.com/ClickHouse/ClickHouse/tree/master/docs/README.md) guide first.

Information about CI checks: https://clickhouse.tech/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by filimonov** [comment]
Thank you, it looks good. 
Can you also try to create a test for it?

See 
https://github.com/ClickHouse/ClickHouse/blob/25f55bb5ddc9d52da4542339fee4174ec924be18/tests/integration/test_storage_kafka/test.py#L766

**Comment by donge** [comment]
> Thank you, it looks good.
> Can you also try to create a test for it?
> 
> See
> https://github.com/ClickHouse/ClickHouse/blob/25f55bb5ddc9d52da4542339fee4174ec924be18/tests/integration/test_storage_kafka/test.py#L766

Sure, thanks for the reminder.

**Comment by donge** [comment]
Just get integration test running. not easy for new guy.
will write a case  
```
.Set up TSKV
Set up JSONCompactEachRowWithNamesAndTypes
Set up JSONEachRow
Set up Regexp
Set up TSVWithNames
Set up CSVWithNames
Set up CapnProto
Set up RowBinary
Set up MsgPack
Set up JSONCompactEachRow
Set up Protobuf
Set up RowBinaryWithNamesAndTypes
Set up TSVWithNamesAndTypes
Set up TSV
Set up Values
Set up CSV
Set up ORC
Set up Native
Checking TSKV
Checking JSONCompactEachRowWithNamesAndTypes
Checking JSONEachRow
Checking Regexp
Checking TSVWithNames
Checking CSVWithNames
Checking CapnProto
Checking RowBinary
Checking MsgPack
Checking JSONCompactEachRow
Checking Protobuf
Checking RowBinaryWithNamesAndTypes
Checking TSVWithNamesAndTypes
Checking TSV
Checking Values
Checking CSV
Checking ORC
Checking Native
...../usr/local/lib/python2.7/dist-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.23) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
Pausing rootteststoragekafka_kafka1_1 ... done
/usr/local/lib/python2.7/dist-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.23) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
Unpausing rootteststoragekafka_kafka1_1 ... done
......Produced 20 messages for topic pb
Produced 1 messages for topic pb
Produced 29 messages for topic pb
....
```

**Comment by donge** [comment]
test case for this issue is verified by adding the script, please comment. @filimonov

**Review by filimonov — APPROVED** [review]
> not easy for new guy.

I know that pain... But you did it! :+1: 

Everything looks good. Thank you!

P.S. unbundled failure is non-relevant (https://github.com/ClickHouse/ClickHouse/issues/14257)

**Pull request merged**
