### PR TITLE
Better cmdline client

### PR DESCRIPTION
**Pull request by amosbird**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Enhance commandline client.

1. Enable bracketed paste when only passing `-n`
2. Add option `--case_insensitive_suggestion` for case insensitive completion
3. Allow explicitly linking to libreadline so that multiline editing is possible

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]
Ok.

**Comment by alexey-milovidov** [comment]
Please look at the build check.

**Comment by amosbird** [comment]
test failures are unrelated

**Comment by alexey-milovidov** [comment]
> --case_insensitive_suggestion

Why this is an option? I think that it should be enabled by default or no one will use it ever.

**Comment by amosbird** [comment]
Ok. Do you prefer to inverse the flag or just get rid of it?

**Comment by alexey-milovidov** [comment]
Just get rid of it.

PS. I tried to implement case insensitive suggest with readline long time ago - but with no success.
Now I'm happy that it's done with replxx!

**Pull request merged**
