### PR TITLE
Adding documentation for LIVE VIEWs

### PR DESCRIPTION
**Pull request by vzakaznikov**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Documentation (changelog entry is not required)

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Adding documentation for live views.

Detailed description / Documentation draft:
Adding documentation for live views.

### CODE REVIEW

**Comment by vzakaznikov** [comment]
This PR is ready for review.

**Review by tavplubix — APPROVED** [review]
LGTM, but maybe we should add output examples for queries to make it more clear?

**Comment by vzakaznikov** [comment]
> LGTM, but maybe we should add output examples for queries to make it more clear?

Thanks! I will add output examples.

**Comment by vzakaznikov** [comment]
@tavplubix, I've added examples.

**Pull request merged**
