### PR TITLE
Re-introduce `is_deleted` column for ReplacingMergeTree

### LINKED ISSUE #58026: Upgrade test fails due to removal of is_deleted feature
Example run: https://s3.amazonaws.com/clickhouse-test-reports/57235/52db759c92744bad1a715fb7dbf7ec665ba36452/upgrade_check__tsan_.html

When starting up you'll get this:
```
2023.12.18 15:03:32.310765 [ 1056336 ] {} <Error> Application: Caught exception while loading metadata: Code: 695. DB::Exception: Load job 'load table test_9.testCleanupR1' failed: Code: 36. DB::Exception: Wrong number of engine arguments.: Cannot attach table `test_9`.`testCleanupR1` from metadata file /var/lib/clickhouse/store/b1f/b1fea9ec-714f-42d2-b142-fc481cf10d83/testCleanupR1.sql from query ATTACH TABLE test_9.testCleanupR1 UUID 'a071beb3-4e13-4e22-8f6e-c29ae9714aae' (`uid` String, `version` UInt32, `is_deleted` UInt8) ENGINE = ReplicatedReplacingMergeTree('/clickhouse/test_9/tables/test_cleanup/', 'r1', version, is_deleted) ORDER BY uid SETTINGS enable_vertical_merge_algorithm = 1, vertical_merge_algorithm_min_rows_to_activate = 0, vertical_merge_algorithm_min_columns_to_activate = 0, min_rows_for_wide_part = 0, min_bytes_for_wide_part = 0, index_granularity = 28733, ratio_of_defaults_for_sparse_serialization = 0., replace_long_file_name_to_hash = 1, max_file_name_length = 57, merge_max_block_size = 17933, prefer_fetch_merged_part_size_threshold = 10737418240, min_merge_bytes_to_use_direct_io = 10737418240, index_granularity_bytes = 19047569, allow_vertical_merges_from_compact_to_wide_parts = 1, marks_compress_block_size = 48010, primary_key_compress_block_size = 17627. (BAD_ARGUMENTS), Stack trace (when copying this message, always include the lines below):
```

This is a breaking change (https://github.com/ClickHouse/ClickHouse/issues/57930) so it's expected that it will break things, but there isn't a simple way to fix it. I'm not sure if we should just ignore these errors in CI, have a way to skip loading these tables or autofix them by ignoring the last parameter via setting (which might be troublesome in the future). Thoughs @alexey-milovidov?

### PR DESCRIPTION
**Pull request by tavplubix**
### Changelog category (leave one):
- Backward Incompatible Change

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
The MergeTree setting `clean_deleted_rows` is deprecated, it has no effect anymore. The `CLEANUP` keyword for `OPTIMIZE` is not allowed by default (unless `allow_experimental_replacing_merge_with_cleanup` is enabled).

Reverts https://github.com/ClickHouse/ClickHouse/pull/57932
Reverts https://github.com/ClickHouse/ClickHouse/pull/58100
Reverts https://github.com/ClickHouse/ClickHouse/pull/58104
Partially reverts https://github.com/ClickHouse/ClickHouse/pull/54706
Partially reverts https://github.com/ClickHouse/ClickHouse/pull/54368

Disables `Vertical` merges with cleanup.

Fixes Upgrade check (fixes https://github.com/ClickHouse/ClickHouse/issues/58026)

### CODE REVIEW

**Comment by robot-ch-test-poll1** [comment]
*This is an automated comment for commit f5bcfaffa593a6f42df1d8907eb2df5c6de7e5b8 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/58267/f5bcfaffa593a6f42df1d8907eb2df5c6de7e5b8/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/58267/f5bcfaffa593a6f42df1d8907eb2df5c6de7e5b8/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Comment by tavplubix** [comment]
Actual changes are in the last commit: https://github.com/ClickHouse/ClickHouse/commit/f5bcfaffa593a6f42df1d8907eb2df5c6de7e5b8

**Comment by alexey-milovidov** [comment]
Please add `allow_experimental_replacing_merge_with_cleanup` to SettingChangesHistory for full compatibility.

**Comment by alexey-milovidov** [comment]
A test has failed: https://s3.amazonaws.com/clickhouse-test-reports/0/1b6c5f6a9868896778d8157ee3c6ef550a903d5e/stateless_tests__aarch64_.html

**Comment by alexey-milovidov** [comment]
@tavplubix, please resubmit.

**Comment by canhld94** [comment]
Not directly relates to this PR. `02814_ReplacingMergeTree_fix_select_final_on_single_partition` broken in #58120.
A range cannot be considered non-intersect if table has `is_deleted` column.

**Pull request merged**
