### PR TITLE
Release pull request for branch 20.1

### PR DESCRIPTION
**Pull request by robot-clickhouse**
This PullRequest is part of ClickHouse release cycle. It's used by CI system only. Don't perform any changes with it.

### CODE REVIEW

**Comment by alesapin** [comment]
`test_storage_kafka` error under address sanitizer seems like a flap, because it works in release build and logs don't contain any sanitizer assertions. tests of multiple volumes are known to be flaky.

**Comment by alesapin** [comment]
`01083_expressions_in_engine_arguments` -- OK
`01076_parallel_alter_replicated_zookeeper` -- non flapper, fixed in master.

**Comment by CurtizJ** [comment]
Failures in `test_ttl_move`/`test_multiple_disks` - ok. These tests are fixed in master.

`test_distributed_ddl` fails with `Data type have to be specified for column `s` to add`. Backward compatabity is broken #9227.

**Comment by alesapin** [comment]
`02000_optimize_skip_unused_shards_type_mismatch` accidentely cherry-picked test.

**Comment by alesapin** [comment]
`00804_test_delta_codec_compression` need to fix test in this branch.

**Comment by alesapin** [comment]
All test failures are known except `01200_mutations_memory_consumption`. I think memory consumption maybe larger with sanitizers and it's OK.

**Comment by alesapin** [comment]
`02000_optimize_skip_unused_shards_type_mismatch` and `01120_join_constants` -- tests of features which are absent in 20.1.
`00804_test_delta_codec_compression` in unbundled mode -- test fixed in master.
`Integration test_server_initialization` -- ok, test fixed in master.

**Comment by alesapin** [comment]
It seems ready for release, a summary about failed tests:
1. `Polymorphic Parts Enabled` stateless tests -- not implemented in 20.1
2. `test_settings_constraints_distributed` integration test -- `CREATE USER` not implemented in 20.1
3. `test_server_initialization` integration test -- test fixed in master, here it is OK.
4. `test_multiple_disks` integration test -- `ALTER TABLE {name} MOVE PARTITION` not implemented in 20.1
5. `test_ttl_move` integration test -- failed in previous release too
6. `02000_optimize_skip_unused_shards_type_mismatch` func test -- `Unknown setting force_optimize_skip_unused_shards.`
7. `01245_limit_infinite_sources` funct test -- `There is no table system.zeros`.
8.  `01120_join_constants` func test -- `Unknown function isConstant`
9. `01200_mutations_memory_consumption` func test -- test fixed in master (ok under thread sanitizer)
10. `00804_test_delta_codec_compression` func test -- test fixed in master.
11. `ThreadPool.ExceptionFromSchedule` + segmentation fault in unit tests -- fixed in master.

**Comment by alesapin** [comment]
No new failures https://github.com/ClickHouse/ClickHouse/pull/8639#issuecomment-613917326

**Comment by CurtizJ** [comment]
`test_insert_quorum_with_move_partition` - `ALTER TABLE MOVE PARTITION` is not implemented in 20.1

**Comment by nikitamikhaylov** [comment]
So, i win

**Comment by nikitamikhaylov** [comment]
stateless: tests for new functionality and for removed `findClusterIndex` function
stateless(ubsan): errors with lz4 fixed in master
stress(memory): fixed in master
integration: `test_ttl_move`, `test_multiple_disks` fixed in master, `test_quorum_insert` contains new feature

**Comment by KochetovNicolai** [comment]
**stateless tests**
1. `00810_in_operators_segfault` - `Unknown function findClusterIndex` - ok
2. `00834_cancel_http_readonly_queries_on_client_close`- `Operation timed out after 10001 milliseconds with 0 bytes received` - ??? (failed in prev release too)
3. `00933_test_fix_extra_seek_on_compressed_cache` - was not fixed. Should not affect anything.
4. `00990_metric_log_table_not_empty` - `Table system.metric_log doesn't exist` - ???
5. `01120_join_constants` - `Unknown function isConstant` - ok
6. `01245_limit_infinite_sources` - `There is no table system.zeros` - ok
7. `01249_bad_arguments_for_bloom_filter` - formatting of `create query` has changed - ok
8. `01254_array_of_unnamed_tuples` - `Unknown table function generateRandom ` - ok
9. `01287_max_execution_speed` - `Bad get: has Float64, requested UInt64` - ???
10. `01290_max_execution_speed_distributed` - `Bad get: has Float64, requested UInt64` - ???
11. `02000_optimize_skip_unused_shards_type_mismatch` - `Unknown setting force_optimize_skip_unused_shards` - ok

**Comment by alesapin** [comment]
The only affected part is `alter` query. So only tests for alter is important.

**Comment by alesapin** [comment]
1. `02000_optimize_skip_unused_shards_type_mismatch` -- `Unknown setting force_optimize_skip_unused_shards`
2. `01254_array_of_unnamed_tuples` -- `Unknown table function generateRandom`
3. `01249_bad_arguments_for_bloom_filter` -- formatting of create query has changed - ok
4. `01245_limit_infinite_sources` -- `There is no table system.zeros on server`
5. `01120_join_constants` -- `Unknown function isConstant`
6. `00834_cancel_http_readonly_queries_on_client_close` -- (failed in prev release too)
7. `00809_add_days_segfault` -- `Unknown function findClusterIndex`
8. `01304_direct_io` -- new test.

**Pull request closed without merging**
