### PR TITLE
[do not merge] perf test against 20.8

### PR DESCRIPTION
**Pull request by akuzm**
Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by akuzm** [comment]
previous comparison against 20.3 is here https://github.com/ClickHouse/ClickHouse/pull/16919

**Comment by alexey-milovidov** [comment]
Ok. 10.2% performance improvement in average.
Some regressions due to disabled "move functions out of any" optimization.

**Comment by akuzm** [comment]
> Some regressions due to disabled "move functions out of any" optimization.

That's three regressing queries out of 350. Why are there so many tests that regressed > 10%? It looks weird...

**Comment by akuzm** [comment]
```
2021-04-26 17:17:55	 CXX_COMPILER	/usr/bin/g++-9
2021-04-26 17:17:55	 CXX_COMPILER_VERSION	9.3.0
```

20.8 is compiled with g++-9, that might explain some differences.

**Comment by akuzm** [comment]
New query that finds a "step" in query run time, and then shows particular runs with big difference around that step:
```
WITH 0.1 AS s
SELECT
    old_sha,
    new_sha,
    event_time,
    message,
    old_value AS `old server`,
    new_value AS `new server`,
    before AS `prev 11 runs`,
    after AS `next 11 runs`,
    cpu_model,
    query_display_name
FROM 
(
    SELECT
        *,
        run_attributes_v1.value AS cpu_model,
        median(old_value) OVER (PARTITION BY run_attributes_v1.value, query_display_name ORDER BY event_date ASC ROWS BETWEEN 11 PRECEDING AND CURRENT ROW) AS before,
        median(new_value) OVER (PARTITION BY run_attributes_v1.value, query_display_name ORDER BY event_date ASC ROWS BETWEEN CURRENT ROW AND 11 FOLLOWING) AS after,
        median(stat_threshold) OVER (PARTITION BY run_attributes_v1.value, query_display_name ORDER BY event_date ASC ROWS BETWEEN 11 PRECEDING AND 11 FOLLOWING) AS stat_threshold_med
    FROM query_metrics_v2
    LEFT JOIN run_attributes_v1 USING (old_sha, new_sha)
    WHERE (attribute = 'lscpu-model-name') AND (metric = 'client_time') AND (pr_number = 0) AND (test = 'questdb_sum_int32') AND (query_index = 2)
) AS t
ANY LEFT JOIN `gh-data`.commits ON new_sha = sha
WHERE (((abs(after - before) / if(after > before, after, before)) AS step_height) > s) AND (abs(diff) > (step_height * 0.9)) AND (abs(diff) > stat_threshold_med)
ORDER BY event_time ASC
FORMAT Vertical

Query id: 43d2a94d-f2be-4a37-9bf3-a36688f0a3ae

Row 1:
──────
old_sha:            8fe37ac774944884bd0fd7fc3311e6ea2c07bdc0
new_sha:            6435ab8e4d35df4a550642a525df9492c65efc4d
event_time:         2021-01-18 13:57:22
message:            Merge pull request #19216 from ClickHouse/speedup-sum

Speed up aggregate function sum
old server:         0.1996
new server:         0.2529
prev 11 runs:       0.2090499997138977
next 11 runs:       0.2471500039100647
cpu_model:          Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz
query_display_name: SELECT sum(x) FROM `zz_Int32 NULL_Memory`

Row 2:
──────
old_sha:            aed3f4ae667b31c656de62ff79555bc530ff30c2
new_sha:            308fbd2ba5b908ba019c077dccaa8e4af825a1e8
event_time:         2021-02-11 10:45:51
message:            Update run-fuzzer.sh
old server:         0.2291
new server:         0.2696
prev 11 runs:       0.263250008225441
next 11 runs:       0.3196500092744827
cpu_model:          Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz
query_display_name: SELECT sum(x) FROM `zz_Int32 NULL_Memory`

Row 3:
──────
old_sha:            17af32a59ba93f0e910aeb154df4ba35a410bbad
new_sha:            263d751d64a584595d3b400cb0ae65663862d414
event_time:         2021-02-11 16:38:24
message:            Merge pull request #20169 from ClickHouse/no-excessive-squash-memory

Disable excessive squashing of blocks for StorageMemory #13052
old server:         0.2344
new server:         0.4139
prev 11 runs:       0.2579500079154968
next 11 runs:       0.33104999363422394
cpu_model:          Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz
query_display_name: SELECT sum(x) FROM `zz_Int32 NULL_Memory`
```

**Comment by akuzm** [comment]
The result is stable. The changes are mostly due to compiler change, nothing interesting.

The final query I'm using for investigation:
```
WITH 0.05 AS s
SELECT
    old_sha,
    new_sha,
    event_time,
    message,
    old_value AS `old server`,
    new_value AS `new server`,
    before AS `prev 11 runs`,
    after AS `next 11 runs`,
    diff AS `diff, ratio`,
    stat_threshold_historical AS `stat threshold, ratio, historical`,
    stat_threshold AS `stat threshold, ratio, per-run`,
    cpu_model,
    query_display_name
FROM 
(
    SELECT
        *,
        run_attributes_v1.value AS cpu_model,
        median(old_value) OVER (PARTITION BY run_attributes_v1.value, test, query_index, query_display_name ORDER BY event_date ASC ROWS BETWEEN 11 PRECEDING AND CURRENT ROW) AS before,
        median(new_value) OVER (PARTITION BY run_attributes_v1.value, test, query_index, query_display_name ORDER BY event_date ASC ROWS BETWEEN CURRENT ROW AND 11 FOLLOWING) AS after,
        quantileExact(0.95)(abs(diff)) OVER (PARTITION BY run_attributes_v1.value, test, query_index, query_display_name ORDER BY event_date ASC ROWS BETWEEN 23 PRECEDING AND CURRENT ROW) AS stat_threshold_historical
    FROM query_metrics_v2
    LEFT JOIN run_attributes_v1 USING (old_sha, new_sha)
    WHERE (attribute = 'lscpu-model-name') AND (metric = 'client_time') AND (pr_number = 0) AND (test IN ('scalar'))
) AS t
ANY LEFT JOIN `gh-data`.commits ON new_sha = sha
WHERE
    -- there is a significantly large step in run time graph at this commit
    (((abs(after - before) / if(after > before, after, before)) AS step_height) >= (greatest(greatest(stat_threshold, stat_threshold_historical), s) AS threshold))
         -- the difference of new and old server measured for this commit is significant wrt per-run stat threshold, historical stat threshold and query sensitivity
        AND (abs(diff) >= threshold)
        -- the difference of new and old server (mostly) explains the step. W/o this condition, we'll see a lot of unrelated small changes near the steps.
        AND (abs(diff) >= (0.7 * step_height))
ORDER BY event_time ASC
FORMAT Vertical
``

**Pull request closed without merging**
