### PR TITLE
Regression test for CHECKSUM_DOESNT_MATCH error because of per-column TTL bug

### PR DESCRIPTION
**Pull request by azat**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Follow-up for: #35820 (cc @CurtizJ )

### CODE REVIEW

**Comment by azat** [comment]
>[Stateless tests flaky check (address, actions) — Some tests restarted, fail: 2, passed: 98](https://s3.amazonaws.com/clickhouse-test-reports/35971/bec3461a3e62654cea3c08897de22b7169c5b198/stateless_tests_flaky_check__address__actions_.html)

Added `long` tag

**Comment by azat** [comment]
>[Stress test (thread, actions) — Sanitizer assert (in stderr.log)](https://s3.amazonaws.com/clickhouse-test-reports/35971/bec3461a3e62654cea3c08897de22b7169c5b198/stress_test__thread__actions_.html)

- #35984

**Comment by alesapin** [comment]
@Mergifyio update

**Comment by azat** [comment]
Failures are unrelated (since this patch only adds one stateless test)

>Integration tests (release, actions) [1/2] — fail: 105, passed: 1, flaky: 0
>Integration tests (thread, actions) [2/4] — fail: 100, passed: 0, flaky: 0

```
ERROR: for node1  Get "https://registry-1.docker.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```

>Stress test (memory, actions) — Backward compatibility check: Failed to download previous release packets

```
socket.gaierror: [Errno -3] Temporary failure in name resolution
```

**Review by alesapin — APPROVED** [review]

**Pull request merged**
