### PR TITLE
optimize ColumnVector::insertMany and ColumnVector::insertManyFrom

### PR DESCRIPTION
**Pull request by frinkr**
### Changelog category (leave one):
- Performance Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Performance improvement for `ColumnVector::insertMany` and `ColumnVector::insertManyFrom`

### CODE REVIEW

**Comment by robot-ch-test-poll4** [comment]
*This is an automated comment for commit 82807d5ce7b2b67e06368c0447844ee175a0f341 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/55714/82807d5ce7b2b67e06368c0447844ee175a0f341/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td><a href="https://github.com/ClickHouse/ClickHouse/actions/runs/6544729175">✅ success</a></td></tr>
<tbody>
</table>
</details>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/55714/82807d5ce7b2b67e06368c0447844ee175a0f341/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Comment by SmitaRKulkarni** [comment]
@frinkr  : Code looks good to me. 
Could you please update label to 'Performace Improvement' ?

**Comment by SmitaRKulkarni** [comment]
Unrelated failures : 
 Stress test (asan) — Found signal in gdb.log - #55041

**Comment by frinkr** [comment]
@SmitaRKulkarni done.

**Review by SmitaRKulkarni — APPROVED** [review]
LGTM

**Pull request merged**
