### PR TITLE
Adding basic ssl server testflows suite.

### PR DESCRIPTION
**Pull request by vzakaznikov**
Changelog category (leave one):
- Build/Testing/Packaging Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
NA

Descrtiption:

Adding `tests/testflows/ssl_server` module to demonstrate the following issues:

1. Adding SSL configuration when server key has a passphrase fails
2. Dynamic SSL context configuration without server restart fails with or without passphrase present for server key

```
/tests/testflows/ssl_server$ ./regression.py --local --clickhouse-binary-path docker://clickhouse/clickhouse-server:22.3.2.2-alpine --test-to-end -l test.log -o classic
➤ Apr 04,2022 20:04:31 /ssl server
➤ Apr 04,2022 20:05:03 /ssl server/sanity
➤ Apr 04,2022 20:05:03 /ssl server/sanity/check non secure connection
✔ 46ms      [   OK   ] /ssl server/sanity/check non secure connection
✔ 48ms      [   OK   ] /ssl server/sanity
➤ Apr 04,2022 20:05:03 /ssl server/ssl context
➤ Apr 04,2022 20:05:03 /ssl server/ssl context/enable ssl no server key passphrase
✔ 28s 291ms [   OK   ] /ssl server/ssl context/enable ssl no server key passphrase
➤ Apr 04,2022 20:05:31 /ssl server/ssl context/enable ssl no server key passphrase dynamically
✘ 19s 796ms [  Fail  ] /ssl server/ssl context/enable ssl no server key passphrase dynamically
    ConfigReloader: Error updating configuration
➤ Apr 04,2022 20:05:51 /ssl server/ssl context/enable ssl with server key passphrase
✘ 14s 992ms [  Fail  ] /ssl server/ssl context/enable ssl with server key passphrase
    ConfigReloader: Error updating configuration
➤ Apr 04,2022 20:06:06 /ssl server/ssl context/enable ssl with server key passphrase dynamically
✘ 15s 20ms  [  Fail  ] /ssl server/ssl context/enable ssl with server key passphrase dynamically
    ConfigReloader: Error updating configuration
✘ 1m 18s    [  Fail  ] /ssl server/ssl context
    ConfigReloader: Error updating configuration
✘ 1m 51s    [  Fail  ] /ssl server
    ConfigReloader: Error updating configuration

Passing

✔ [ OK ] /ssl server/sanity/check non secure connection
✔ [ OK ] /ssl server/sanity
✔ [ OK ] /ssl server/ssl context/enable ssl no server key passphrase

Failing

✘ [ Fail ] /ssl server/ssl context/enable ssl no server key passphrase dynamically
✘ [ Fail ] /ssl server/ssl context/enable ssl with server key passphrase
✘ [ Fail ] /ssl server/ssl context/enable ssl with server key passphrase dynamically
✘ [ Fail ] /ssl server/ssl context
✘ [ Fail ] /ssl server
```

### CODE REVIEW

**Comment by vzakaznikov** [comment]
Full test log https://gist.github.com/vzakaznikov/ed57c00a8d616a7f71f805ee62839b1b.

**Comment by vzakaznikov** [comment]
Tests reproduce issue in https://github.com/ClickHouse/ClickHouse/issues/35950.

**Comment by alexey-milovidov** [comment]
We need to add TestFlows to CI before merging this PR.
Otherwise it is a dead code.

**Comment by vzakaznikov** [comment]
I will be using this PR to try to enable TestFlows in CI.

**Comment by alexey-milovidov** [comment]
This PR looks a bit stale, let's merge as is and enable the tests in subsequent PR.

**Comment by alexey-milovidov** [comment]
@mergifyio update

**Comment by alexey-milovidov** [comment]
PS. Testflows still look as an overengineered technology that non one will be able to support.

**Comment by alexey-milovidov** [comment]
@Felixoid said that the "workflow" file is corrupted.

**Comment by Felixoid** [comment]
https://github.com/ClickHouse/ClickHouse/actions/runs/2161228036

**Comment by Felixoid** [comment]
Once the workflow file is fixed, the PR can be reopened

**Pull request closed without merging**
