### PR TITLE
tests/stress: use --privileged over --cap-add syslog to obtain dmesg

### PR DESCRIPTION
**Pull request by azat**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Fixes: #39980 (cc @alexey-milovidov )

### CODE REVIEW

**Comment by azat** [comment]
Now it works:

```
[Fri Aug 19 03:49:12 2022] capability: warning: `clickhouse-serv' uses 32-bit capabilities (legacy support in use)
```

And timestamps looks good.

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
@kssenii https://s3.amazonaws.com/clickhouse-test-reports/40354/50bddc43dc29e308a420d99d2fd191b25dfe7306/stateless_tests__thread__[3/3].html
02313_filesystem_cache_seeks failed due to stderr, but this error looks repeatable and can be ignored by clickhouse-test.

**Comment by alexey-milovidov** [comment]
@nikitamikhaylov test for s3Cluster has failed: https://s3.amazonaws.com/clickhouse-test-reports/40354/50bddc43dc29e308a420d99d2fd191b25dfe7306/integration_tests__thread__[4/4].html

**Comment by alexey-milovidov** [comment]
@azat please check why the AST fuzzer has been killed.

**Comment by azat** [comment]
> please check why the AST fuzzer has been killed.

There is not enough details.

```
AST fuzzer (ASan) Task failed: $?=137
```

137 - `SIGKILL`

- https://github.com/ClickHouse/ClickHouse/runs/7922965632?check_suite_focus=true - first try

```
INFO:root:Going to run docker run --network=host --volume=/home/ubuntu/actions-runner/_work/_temp/ast_fuzzer_asan/workspace:/workspace --cap-add syslog --cap-add sys_admin --cap-add=SYS_PTRACE -e PR_TO_TEST=40354 -e SHA_TO_TEST=50bddc43dc29e308a420d99d2fd191b25dfe7306 -e BINARY_URL_TO_DOWNLOAD="https://s3.amazonaws.com/clickhouse-builds/40354/50bddc43dc29e308a420d99d2fd191b25dfe7306/package_asan/clickhouse" clickhouse/fuzzer:latest
Error: The operation was canceled.
```

- https://github.com/ClickHouse/ClickHouse/runs/7925633268?check_suite_focus=true - second try

```
2022-08-19T20:41:36.3723653Z [36;1mpython3 ast_fuzzer_check.py "$CHECK_NAME"[0m
2022-08-19T20:41:36.3743463Z shell: /usr/bin/bash -e {0}
2022-08-19T20:41:36.3743677Z env:
2022-08-19T20:41:36.3743879Z   PYTHONUNBUFFERED: 1
2022-08-19T20:41:36.3744160Z   TEMP_PATH: /home/ubuntu/actions-runner/_work/_temp/ast_fuzzer_asan
2022-08-19T20:41:36.3744504Z   REPORTS_PATH: /home/ubuntu/actions-runner/_work/_temp/reports_dir
2022-08-19T20:41:36.3744788Z   CHECK_NAME: AST fuzzer (ASan)
2022-08-19T20:41:36.3745092Z   REPO_COPY: /home/ubuntu/actions-runner/_work/_temp/ast_fuzzer_asan/ClickHouse
2022-08-19T20:41:36.3745469Z ##[endgroup]
2022-08-19T20:41:39.0783210Z INFO:root:Check is already finished according to github status, exiting
```

So by some reason first check had been canceled (maybe the instance received termination request?), and the second did not detect it.

**Pull request merged**
