### PR TITLE
Fix pygithub

### PR DESCRIPTION
**Pull request by Felixoid**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix issues with the changed PyGitHub API after updating it in #56459

### CODE REVIEW

**Review by Felixoid — COMMENTED** [review]
test review

**Comment by robot-ch-test-poll1** [comment]
*This is an automated comment for commit 5722ae7c08a42ea4b964ac9b2648ca48e472e63e with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/56778/5722ae7c08a42ea4b964ac9b2648ca48e472e63e/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td><a href="https://github.com/ClickHouse/ClickHouse/actions/runs/6875593410">✅ success</a></td></tr>
<tbody>
</table>
</details>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/56778/5722ae7c08a42ea4b964ac9b2648ca48e472e63e/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Comment by Felixoid** [comment]
The `merge_pr` is fixed https://github.com/ClickHouse/ClickHouse/actions/runs/6875595452/job/18699494081?pr=56778

**Comment by Felixoid** [comment]
The `cherry_pick` works too https://github.com/ClickHouse/ClickHouse/actions/runs/6875656445/job/18699683772#step:5:40

**Review by antonio2368 — APPROVED** [review]

**Comment by Felixoid** [comment]
Good that we test it actually https://github.com/ClickHouse/ClickHouse/actions/runs/6875694891/job/18700012395?pr=56778#step:4:40

Another broken place

**Review by Felixoid — COMMENTED** [review]
another review test

and it works https://github.com/ClickHouse/ClickHouse/actions/runs/6875955795/job/18700589832?pr=56778#step:4:33

**Comment by Felixoid** [comment]
In the backport I'll cherry-pick https://github.com/ClickHouse/ClickHouse/pull/55845/files too

**Pull request merged**
