### PR TITLE
Execute multiIf function columnarly when result_type's underlying type is number

### PR DESCRIPTION
**Pull request by taiyang-li**
### Changelog category (leave one):
- Performance Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Execute multiIf function columnarly when result_type's underlying type is number

#### Changes in detail
improve performance
- Apply `executeInstructionsColumnar` when result_type's underlying type is number, including Decimal*/Enum*/IP*
- Always reserve memory for result column before it is inserted 
- Remove `getDataAt` virtual funtion call in `executeInstructionsColumnar`

bugfix:
- Fix a trivial bug introduced by previous pr: https://github.com/ClickHouse/ClickHouse/pull/57745. It didn't consider the case when source is a constant column
企业微信截图_17091899324377

### CODE REVIEW

**Comment by robot-ch-test-poll3** [comment]
*This is an automated comment for commit ff4231186fce44bc6ab04e31cc327378f763226c with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/60384/ff4231186fce44bc6ab04e31cc327378f763226c/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/60384/ff4231186fce44bc6ab04e31cc327378f763226c/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Comment by taiyang-li** [comment]
@Algunenano  hope for you reviews

**Review by Avogar — APPROVED** [review]

**Comment by Avogar** [comment]
Please, fix `ClickHouse special build check` check

**Comment by taiyang-li** [comment]
image

**Pull request merged**
