### PR TITLE
Raw changelog 20.8 from utils/simple-backport/changelog.sh

### PR DESCRIPTION
**Pull request by abyss7**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by abyss7** [comment]
Do not merge without review.

**Comment by alexey-milovidov** [comment]
I expected that the changelog for version 20.10 will be created :(

**Comment by alexey-milovidov** [comment]
@abyss7 How is it possible that the bugfix release contains any "Improvements"?
Should check carefully, maybe changelog is incorrect.

**Comment by abyss7** [comment]
> @abyss7 How is it possible that the bugfix release contains any "Improvements"?
> Should check carefully, maybe changelog is incorrect.

I used script from @akuzm - will investigate before trying to generate changelists for other versions. Looks like it was used some time because it was still broken after migration to python 3.

**Comment by alexey-milovidov** [comment]
Outdated.

**Pull request closed without merging**
