### PR TITLE
Backport #64769 to 23.8: Fix default database with grant on cluster

### PR DESCRIPTION
**Pull request by robot-clickhouse**
Original pull-request https://github.com/ClickHouse/ClickHouse/pull/64769
Cherry-pick pull-request #64875

This pull-request is a last step of an automated backporting.
Treat it as a standard pull-request: look at the checks and resolve conflicts.
Merge it only if you intend to backport changes to the target branch, otherwise just close it.

### CODE REVIEW

**Comment by robot-clickhouse-ci-1** [comment]
*This is an automated comment for commit 590c7d230d49c1d0dec0b1d7c97d4c7910857c1b with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/64876/590c7d230d49c1d0dec0b1d7c97d4c7910857c1b/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Push to Dockerhub</td><td>The check for building and pushing the CI related docker images to docker hub</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

**Comment by alexey-milovidov** [comment]
@pufit integration tests have failed.

**Comment by pufit** [comment]
> @pufit integration tests have failed.

I tried to rerun the tests, but it still failed. Don't know the reason, though. It all looks entirely unrelated 🤔

**Comment by alexey-milovidov** [comment]
@pufit, they failed again.

**Pull request merged**
