### PR TITLE
Mysql replica support for separate tables

### PR DESCRIPTION
**Pull request by adilyas**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

...

Detailed description / Documentation draft:

...

By adding documentation, you'll allow users to try your new feature immediately, not when someone else will have time to document it later. Documentation is necessary for all features that affect user experience in any way. You can add brief documentation draft above, or add documentation right into your patch as Markdown files in [docs](https://github.com/ClickHouse/ClickHouse/tree/master/docs) folder.

If you are doing this for the first time, it's recommended to read the lightweight [Contributing to ClickHouse Documentation](https://github.com/ClickHouse/ClickHouse/tree/master/docs/README.md) guide first.

Information about CI checks: https://clickhouse.tech/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by zhang2014** [comment]
Maybe use pub/sub to refactor `MaterializeMySQLSyncThread` is better ?(database and table name is topic name, DDL will be pushed in the empty string name topic). topic consumer should be dynamically added.

**Comment by liangli1213** [comment]
@adilyas @zhang2014 , would you please tell me what is the usage or syntax of this feature?

**Comment by alexey-milovidov** [comment]
This PR was abandoned.

**Comment by alexey-milovidov** [comment]
@liangli1213 It should allow to replicate one or a few selected tables from MySQL,
in contrast to MaterializeMySQL feature that replicates whole databases.

**Pull request closed without merging**
