### PR TITLE
Fix sleep_in_send_tables_status_ms/sleep_in_send_data_ms in integration tests

### PR DESCRIPTION
**Pull request by azat**
Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Fixes: #21998
Cc: @Avogar

### CODE REVIEW

**Comment by azat** [comment]
By the way, [parsing](https://clickhouse-test-reports.s3.yandex.net/22151/dfa1a051e763e3c12dfac0db5dc86fa2bca6b8d2/integration_tests_flaky_check_(asan).html#fail1) flaky/error looks wrong

**Comment by azat** [comment]
>Integration tests flaky check (asan) — Flaky tests found: skipped: 0, passed: 1, fail: 1, error: 2, flaky: 0

Test failure is related, will fix separately

**Comment by Avogar** [comment]
@azat did you know the problem? For unknown reason in case when async_socket_for_remote = 1 and use_hedged_requests = 0 receive timeout doesn't work. When I created PR with test_secure_socket everything was ok. I am trying to figure out what the problem is.

**Comment by azat** [comment]
>@azat do you know the problem?

Yep, will send a patch later

**Comment by Avogar** [comment]
If I'm right, the problem appeared in https://github.com/ClickHouse/ClickHouse/pull/21643
Will wait for the patch, thanks!

**Comment by azat** [comment]
>If I'm right, the problem appeared in #21643

You are right.

> Will wait for the patch, thanks!

#22183 - (submitted separately for backporting)

*I can rebase it once this PR will be merged*

**Comment by Avogar** [comment]
Let's merge it then.

**Pull request merged**
