### PR TITLE
Pass a proper message to exception

### PR DESCRIPTION
**Pull request by Felixoid**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

For changelog. Remove if this is non-significant change.

Category (leave one):
- Improvement

Short description (up to a few sentences):

Pass a proper message when a partition doesn't exist.

Detailed description (optional):

Currently, the message is completely unclear:

```
:) SET optimize_throw_if_noop=1

SET optimize_throw_if_noop = 1

Ok.

0 rows in set. Elapsed: 0.002 sec.

:) OPTIMIZE TABLE graphite.data_lr PARTITION 201705

OPTIMIZE TABLE graphite.data_lr PARTITION 201705

Received exception from server (version 19.4.0):
Code: 388. DB::Exception: Received from localhost:9000, ::1. DB::Exception. 

0 rows in set. Elapsed: 0.005 sec. 
```

But it exists in logs:

```
2019.06.26 19:18:30.555755 [ 63 ] {7fb5afee-3b2e-46f3-b65b-cbd925c69a41} <Debug> executeQuery: (from [::1]:55050) OPTIMIZE TABLE graphite.data_lr PARTITION 201705
2019.06.26 19:18:30.558663 [ 63 ] {7fb5afee-3b2e-46f3-b65b-cbd925c69a41} <Information> graphite.data_lr (StorageReplicatedMergeTree): Cannot select parts for optimization
2019.06.26 19:18:30.558820 [ 63 ] {7fb5afee-3b2e-46f3-b65b-cbd925c69a41} <Debug> MemoryTracker: Peak memory usage (total): 4.00 KiB.
2019.06.26 19:18:30.558957 [ 63 ] {7fb5afee-3b2e-46f3-b65b-cbd925c69a41} <Error> executeQuery: Code: 388, e.displayText() = DB::Exception (from [::1]:55050) (in query: OPTIMIZE TABLE graphit
e.data_lr PARTITION 201705), Stack trace:
```

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
Please add a test.
It will be functional test with `-- { serverError NNN }` directive: look at examples around.

**Comment by alexey-milovidov** [comment]
The test is wrong and the code doesn't build.

**Comment by Felixoid** [comment]
@alexey-milovidov I've fixed tests and now both simple and replicated MergeTree behaves identically

**Comment by alexey-milovidov** [comment]
But the test doesn't work.

**Comment by Felixoid** [comment]
Indeed, haven't adjusted it after the latest tiny change.

**Comment by alexey-milovidov** [comment]
Wow, it's green :) Thank you!

**Pull request merged**
