### PR TITLE
fixed json format description in references

### PR DESCRIPTION
**Pull request by Ngalstyan4**
I was researching JSON format and realized that although references in both languages describe JSON usage as I would like it to see, the actual implementation is different :))
So I went a head to first fix the docs to reflect what is in soft.

Secondly, I would like to know why exactly is JSON not suitable as a write format.
I am trying to insert data to clickhouse which is in NEWLINE_DELIMITED_JSON format.
What exactly is needed to develop this feature?

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
1. It is misunderstanding about who does read/write.
See comments here: https://github.com/yandex/ClickHouse/issues/44
Maybe better to replace 'for reads' to 'for INSERTs' and 'for writes' to 'for SELECTs'?
Or to write 'this format is not suitable for parsing'. Or 'this format is only presentational, not for parsing data for INSERT'...
(You could add commit for that.)

2. There is JSONEachRow format. It is suitable both for reads and writes. 
I just written documentation about it recently, so it is only in russian part: https://clickhouse.yandex/reference_ru.html#JSONEachRow
If you could read it, will be nice, if you have a time to add it also in english doc.

In contrast to JSONEachRow, JSON and JSONCompact is 'presentation' formats.

**Comment by Ngalstyan4** [comment]
Done,

Couple of points.
1.) At least for me there is a lot of confusion about what is called "write" and what is "read". As these are used extensively in the documentation.

2) I could not understand this sentence so just omitted it in english reference.
_При чтении, в качестве дополнительного поля, может присутствовать %%tskv%% без знака равенства и без значения. Это поле игнорируется._

3) Why are complex default values not supported?
`
	for (size_t i = 0; i < columns; ++i)
		if (!read_columns[i])
			block.unsafeGetByPosition(i).column.get()->insertDefault();
`
It seems this is the logic for inserting default values. Can't it be modified to pull custom default values and insert these?

**Comment by alexey-milovidov** [comment]
Ok, but I will edit documentation further, because now, read and write concepts are used controversially.

> 1.) At least for me there is a lot of confusion about what is called "write" and what is "read". As these are used extensively in the documentation.

The only vaild way is to make changes in whole documentation.

> 2) I could not understand this sentence so just omitted it in english reference.

It means, that in TSKV format, there could be 'tskv' field without value anywhere, it has no sense and skipped (specific of usage TSKV format in Yandex).

> 3) Why are complex default values not supported?

Default values are evaluated in interpreter of INSERT query, to support complex dependent expressions as defaults. Formats are decoupled with interpreters. Anyway, appropriate solution could be developed in future.

If you specify part of columns in INSERT query `INSERT INTO table (c1, c2...) FORMAT JSONEachRow`, default values for another columns will be calculated by interpreter. It means, that your JSONs doesn't have values for that columns in all rows.

**Comment by alexey-milovidov** [comment]
Updated documentation: https://github.com/yandex/ClickHouse/commit/fe0c6ed801b7fe6ac47af9576a2956f2983c367e

**Pull request merged**
