### PR TITLE
Use tryGetS3StorageClient to avoid raising an exception when logging s3 

### PR DESCRIPTION
**Pull request by elenatorro**
Following this recommendation https://github.com/ClickHouse/ClickHouse/issues/65390#issuecomment-2176429097, this PR adds a method to avoid raising an exception on this step

### Changelog category (leave one):

- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Do not raise a NOT_IMPLEMENTED error when getting s3 metrics with a multiple disk configuration  

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by robot-clickhouse** [comment]
*This is an automated comment for commit 75a4940683c645bb8bb2a3cdc024e48cfbfcf50f with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/65403/75a4940683c645bb8bb2a3cdc024e48cfbfcf50f/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>A Sync</td><td>If it fails, ask a maintainer for help</td><td>⏳ pending</td></tr>
<tbody>
</table>
<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>Checks correctness of the PR's body</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

**Comment by elenatorro** [comment]
I removed the try-catch statement since it's not needed anymore as recommended by @Algunenano. I see some checks failing, I'm not sure if there's something I can review from my side 🤞🏽

**Comment by Algunenano** [comment]
There is some issue in the build. I'll have a look

**Comment by elenatorro** [comment]
Thank you @Algunenano for taking care 🙏🏽

**Comment by alrocar** [comment]
@Algunenano any chance this could be backported to 24.6? 🙏

**Pull request merged**
