### PR TITLE
Slightly improve performance of aggregation by UInt8/UInt16 keys, part 6

### PR DESCRIPTION
**Pull request by alexey-milovidov**
Changelog category (leave one):
- Performance Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Slightly improve performance of aggregation by UInt8/UInt16 keys.

Detailed description / Documentation draft:
Added a method that will use multiple independent arrays of aggregation states in unrolled loop and then merge them together to the final destination. Includes #13056 and #13055 and #13084 and #13091 and #13096 but not strictly depends on them.

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
This optimization is good on AMD Ryzen but bad on Intel Xeon E5-2650v2 (that is 7 years old) due to small cache size.

**Comment by alexey-milovidov** [comment]
Performance test shows significant (more than 1.5 times) performance increase
also it shows slowdown in sumMap, maxMap, because these functions were speed up in master.

**Comment by alexey-milovidov** [comment]
@akuzm It shows 22..24% performance improvement, but for unknown reason, performance test does not show it as confident result.

**Comment by alexey-milovidov** [comment]
00933_test_fix_extra_seek_on_compressed_cache - known bad test.

**Comment by alexey-milovidov** [comment]
Performance test Ok.

**Comment by akuzm** [comment]
> @akuzm It shows 22..24% performance improvement, but for unknown reason, performance test does not show it as confident result.

Let's remove all unknown reasons. Which test do you mean, `synthetic_hardware_benchmark`? We have set `max_ignored_relative_change = 0.2` for it, because it had some unstable queries. This is the reason why it is not shown as changed. Looking at [some recent report from master](https://clickhouse-test-reports.s3.yandex.net/0/8054a08c5564b5de78abe0f4c3d3309ad410055e/performance_comparison/all-queries.html#all-query-times.synthetic_hardware_benchmark.0), I don't see any very unstable queries in this test, all are below 10%. Maybe it was fixed somehow since then. I will remove this 20% restriction in master.

**Comment by alexey-milovidov** [comment]
Yes, I meant this test. Ok.

**Pull request merged**
