### PR TITLE
Added prefix-based S3 endpoint settings

### PR DESCRIPTION
**Pull request by excitoon**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Added prefix-based S3 endpoint settings

Idea is to eventually move from `<s3><some_endpoint><endpoint>https://...</endpoint></some_endpoint>` to `<s3><endpoints><some_endpoint><prefix>https://.../abc/</prefix></some_endpoint></endpoints>` in configuration file.

### CODE REVIEW

**Comment by qoega** [comment]
Can you add a test with this feature?

**Comment by vdimir** [comment]
As I understand this PR allows to call `getSettings` with not full endpoint, but only with prefix.
@excitoon Could you please provide some extra details?

**Comment by excitoon** [comment]
@vdimir Yes, that's in order to allow more granular settings for different URLs. This is particularly important when user specifies path-style URLs.

**Comment by vdimir** [comment]
> @vdimir Yes, that's in order to allow more granular settings for different URLs. This is particularly important when user specifies path-style URLs.

Could you add exmple of usage for exmple in https://github.com/ClickHouse/ClickHouse/tree/70d9c7ea0317edfdfaa0b6bf94c4028d328aa328/tests/integration/test_storage_s3 ?

**Review by vdimir — APPROVED** [review]
Thank you for your changes

**Pull request merged**
