### PR TITLE
Disable send_logs_level for INSERT into Distributed to avoid possible hung

### PR DESCRIPTION
**Pull request by azat**
Changelog category (leave one):
- Bug Fix (user-visible misbehaviour in official stable or prestable release)

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Disable send_logs_level for INSERT into Distributed to avoid possible hung

In case of INSERT into Distributed table with send_logs_level!=none it
is possible to receive tons of Log packets, and w/o consuming it
properly the socket buffer will be full, and eventually the query will
hung.

This happens because receiver will not read data until it will send logs
packets, but sender does not reads those Log packets and so receiver
hung, and hence the sender will hung too, because receiver do not
consume Data packets anymore.

In the initial version of this patch I tried to properly consume Log
packets, but it is not possible to ensure that before writing Data
blocks all Log packets had been consumed, that said that with current
protocol implementation it is not possible to fix Log packets consuming
properly, to avoid deadlock, so send_logs_level had been simply
disabled.

But note, that this does not differs to the user, in what ClickHouse did
before, since before it simply does not consume those packets, so the
client does not saw those messages anyway.

<details>

The receiver:

    Poco::Net::SocketImpl::poll(Poco::Timespan const&, int)
    Poco::Net::SocketImpl::sendBytes(void const*, int, int)
    Poco::Net::StreamSocketImpl::sendBytes(void const*, int, int)
    DB::WriteBufferFromPocoSocket::nextImpl()
    DB::TCPHandler::sendLogData(DB::Block const&)
    DB::TCPHandler::sendLogs()
    DB::TCPHandler::readDataNext()
    DB::TCPHandler::processInsertQuery()

    State      Recv-Q  Send-Q          Local Address:Port         Peer Address:Port Process
    ESTAB      4331792 211637           127.0.0.1:9000            127.0.0.1:24446 users:(("clickhouse-serv",pid=46874,fd=3850))

The sender:

    Poco::Net::SocketImpl::poll(Poco::Timespan const&, int)
    Poco::Net::SocketImpl::sendBytes(void const*, int, int)
    Poco::Net::StreamSocketImpl::sendBytes(void const*, int, int)
    DB::WriteBufferFromPocoSocket::nextImpl()
    DB::WriteBuffer::write(char const*, unsigned long)
    DB::CompressedWriteBuffer::nextImpl()
    DB::WriteBuffer::write(char const*, unsigned long)
    DB::SerializationString::serializeBinaryBulk(DB::IColumn const&, DB::WriteBuffer&, unsigned long, unsigned long) const
    DB::NativeWriter::write(DB::Block const&)
    DB::Connection::sendData(DB::Block const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool)
    DB::RemoteInserter::write(DB::Block)
    DB::RemoteSink::consume(DB::Chunk)
    DB::SinkToStorage::onConsume(DB::Chunk)

    State      Recv-Q  Send-Q         Local Address:Port         Peer Address:Port Process
    ESTAB      67883   3008240           127.0.0.1:24446           127.0.0.1:9000  users:(("clickhouse-serv",pid=41610,fd=25))

</details>

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]
LGTM

**Comment by alexey-milovidov** [comment]
@mergifyio update

**Comment by alexey-milovidov** [comment]
There are failed checks.
@mergifyio update

**Comment by alexey-milovidov** [comment]
https://github.com/Mergifyio update

**Comment by alexey-milovidov** [comment]
@azat Checks are failed.

@Mergifyio update

**Comment by azat** [comment]
>[Stateless tests (debug, actions) [2/3] — fail: 1, passed: 1307, skipped: 18](https://s3.amazonaws.com/clickhouse-test-reports/35075/779e7c878aa0427efb321fd18050ae8fe500056a/stateless_tests__debug__actions__[2/3].html)

- `01091_num_threads` - #35599

>[Stateless tests (thread, actions) [2/3] — Some queries hung, fail: 2, passed: 1306, skipped: 18](https://s3.amazonaws.com/clickhouse-test-reports/35075/779e7c878aa0427efb321fd18050ae8fe500056a/stateless_tests__thread__actions__[2/3].html)
>[Stateless tests (ubsan, actions) — fail: 1, passed: 3918, skipped: 19](https://s3.amazonaws.com/clickhouse-test-reports/35075/779e7c878aa0427efb321fd18050ae8fe500056a/stateless_tests__ubsan__actions_.html)

- `02149_read_in_order_fixed_prefix` - #35599 
- `01514_parallel_formatting` - looks like a real issue

>[Stateless tests (thread, actions) [3/3] — fail: 2, passed: 1280, skipped: 7](https://s3.amazonaws.com/clickhouse-test-reports/35075/779e7c878aa0427efb321fd18050ae8fe500056a/stateless_tests__thread__actions__[3/3].html)

- `01605_adaptive_granularity_block_borders`
- `00113_shard_group_array`

>[Stateless tests flaky check (address, actions) — Timeout, fail: 1, passed: 0](https://s3.amazonaws.com/clickhouse-test-reports/35075/779e7c878aa0427efb321fd18050ae8fe500056a/stateless_tests_flaky_check__address__actions_.html)

- `02232_dist_insert_send_logs_level_hung` - After proper waiting of the query it takes too much...

**Comment by alexey-milovidov** [comment]
@azat bugfix check is saying that the test passed on prev build: https://s3.amazonaws.com/clickhouse-test-reports/35075/98e1e45f860e96edd3bf002c47fa827bd8a61c69/stateless_tests_bugfix_validate_check.html

**Comment by azat** [comment]
>[PullRequestCI / TestsBugfixCheck (pull_request) Failing after 12m — TestsBugfixCheck](https://github.com/ClickHouse/ClickHouse/runs/6158477830?check_suite_focus=true)

Now the test w/o this patch does fails:

```
2022-04-25T14:48:23.2483089Z 2022-04-25 09:48:23 02232_dist_insert_send_logs_level_hung:                                 [ FAIL ] 600.03 sec. - having stderror: 
2022-04-25T14:48:23.2483588Z 2022-04-25 09:48:23 Timeout dropping database test_bnckem after test
```

>[Stateless tests (address, actions) [1/2] — Some queries hung, fail: 1, passed: 2010, skipped: 9](https://s3.amazonaws.com/clickhouse-test-reports/35075/81c3be8be1db807276b4f55703c0f6121dc9d9ba/stateless_tests__address__actions__[1/2].html)

However, the fix is not complete:

```
"elapsed": 1884.992765112,
"query": "insert into function remote('127.2', currentDatabase(), in_02232) select * from numbers(1e6)",
"thread_ids": [
    "21153",
    "39724",
    "39653"
],

"query": "INSERT INTO test_h88210.in_02232 (key) VALUES",
"thread_ids": [
    "3267",
    "3267"
],

Thread 326 (Thread 0x7f4dd2bf7700 (LWP 3267)):
5  0x0000000038d8c548 in Poco::Net::StreamSocketImpl::sendBytes (this=0x6040000d8350, buffer=0x7f4d263ec800, length=419, flags=0) at ../contrib/poco/Net/src/StreamSocketImpl.cpp:63
6  0x000000002b9449df in DB::WriteBufferFromPocoSocket::nextImpl (this=<optimized out>) at ../src/IO/WriteBufferFromPocoSocket.cpp:58
7  0x000000002e3a41b8 in DB::WriteBuffer::next (this=0x7f4dd2beb660) at ../src/IO/WriteBuffer.h:50
8  DB::TCPHandler::sendLogData (this=this@entry=0x61a0014d1880, block=...) at ../src/Server/TCPHandler.cpp:1688
9  0x000000002e38e6b0 in DB::TCPHandler::sendLogs (this=0x7f4dd2beb660) at ../src/Server/TCPHandler.cpp:1759
10 0x000000002e38f7f4 in DB::TCPHandler::readDataNext (this=<optimized out>) at ../src/Server/TCPHandler.cpp:583
11 0x000000002e38bdd2 in DB::TCPHandler::processInsertQuery()::$_0::operator()<DB::PushingPipelineExecutor>(DB::PushingPipelineExecutor&) const (executor=..., this=<optimized out>) at ../src/Server/TCPHandler.cpp:640

Thread 1187 (Thread 0x7f4b23a9e700 (LWP 39653)):
5  0x0000000038d8c548 in Poco::Net::StreamSocketImpl::sendBytes (this=0x6040015e2fd0, buffer=0x7f4d24ef7800, length=54, flags=0) at ../contrib/poco/Net/src/StreamSocketImpl.cpp:63
6  0x000000002b9449df in DB::WriteBufferFromPocoSocket::nextImpl (this=<optimized out>) at ../src/IO/WriteBufferFromPocoSocket.cpp:58
7  0x000000002e13a3c3 in DB::WriteBuffer::next (this=0x7f4b23a93380) at ../src/IO/WriteBuffer.h:50
8  DB::Connection::sendData (this=<optimized out>, block=..., name=..., scalar=<optimized out>) at ../src/Client/Connection.cpp:584
9  0x000000002d77c2da in DB::RemoteInserter::write (this=0x61500595c0f8, block=<error reading variable: Cannot access memory at address 0x1>) at ../src/QueryPipeline/RemoteInserter.cpp:110
```

**Comment by alexey-milovidov** [comment]
@azat let's continue.

**Comment by azat** [comment]
>[Stateless tests flaky check (address, actions) — Tests are not finished, fail: 0, passed: 106](https://s3.amazonaws.com/clickhouse-test-reports/35075/4a064e5b6f81136f2bf923d85001f25fa05d39ce/stateless_tests_flaky_check__address__actions_.html)

`Tests are not finished` likely becase of timeout (30min):

```
2022-05-25 16:43:47 Using queries from '/usr/share/clickhouse-test/queries' directory
...
2022-05-25 17:09:37 02232_dist_insert_send_logs_level_hung:                                 [ OK ] 251.83 sec.
```

**Comment by azat** [comment]
>[Integration tests (asan, actions) [1/3] — fail: 3, passed: 676, flaky: 0](https://s3.amazonaws.com/clickhouse-test-reports/35075/100410cd1941caffb03646e7274ae240be134608/integration_tests__asan__actions__[1/3].html)

- `test_grpc_protocol/test.py::test_progress` - #37908
- `test_keeper_zookeeper_converter/test.py::test_simple_crud_requests[False]` - #37890
- `test_keeper_zookeeper_converter/test.py::test_multi_and_failed_requests[False]` - #37890

>[Stateless tests (thread, actions) [1/3] — fail: 1, passed: 1390, skipped: 11](https://s3.amazonaws.com/clickhouse-test-reports/35075/100410cd1941caffb03646e7274ae240be134608/stateless_tests__thread__actions__[1/3].html)

- `01183_custom_separated_format_http`

>[Stateless tests (thread, actions) [2/3] — fail: 1, passed: 1382, skipped: 18](https://s3.amazonaws.com/clickhouse-test-reports/35075/100410cd1941caffb03646e7274ae240be134608/stateless_tests__thread__actions__[2/3].html)

- `01746_long_zstd_http_compression_json_format` - flaky

>Stateless tests flaky check (address, actions) — Tests are not finished, fail: 0, passed: 105

Timeout - OK

**Comment by azat** [comment]
>[PullRequestCI / TestsBugfixCheck (pull_request) Failing after 55m — TestsBugfixCheck](https://github.com/ClickHouse/ClickHouse/runs/6783167484?check_suite_focus=true)

```
2022-06-07 22:53:30 02232_dist_insert_send_logs_level_hung:                                 [ FAIL ] 620.02 sec. - having stderror: 
...
2022-06-07 22:54:30 Found hung queries in processlist:
2022-06-07 22:54:30         "elapsed": 678.058238597,
2022-06-07 22:54:30         "is_cancelled": 0,
2022-06-07 22:54:30         "is_all_data_sent": 0,
2022-06-07 22:54:30         "query": "insert into function remote('127.2', currentDatabase(), in_02232) select * from numbers(1e6)",
...
```

OK, but let's add a no-bc tag.

**Comment by azat** [comment]
>[PullRequestCI / TestsBugfixCheck (pull_request) Failing after 57m — TestsBugfixCheck](https://github.com/ClickHouse/ClickHouse/runs/6859753891?check_suite_focus=true)

```
2022-06-13T11:04:55.8467948Z 2022-06-13 08:04:55 02232_dist_insert_send_logs_level_hung:                                 [ FAIL ] 620.02 sec. - having stderror: 
...
_csv.Error: field larger than field limit (131072)
...
FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/actions-runner/_work/_temp/tests_bugfix_check/stateless/post_commit_status.tsv'
```

- #38030

**Pull request merged**
