### PR TITLE
Add test to verify #62308 works

### PR DESCRIPTION
**Pull request by antaljanosbenjamin**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Run only fuzzers related jobs (libFuzzer fuzzers, AST fuzzers, etc.)
- [ ]  Exclude: AST fuzzers
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by antaljanosbenjamin** [comment]
@azat I tried to add a test to verify that your PR #62944 actually fixes the issue #62308 you referenced. The good thing is it is working I think, the bad thing is the test also succeeds even without your changes.

It is my bad that I approved the PR without the test, but I hope that you tested your changes actually fixing something. Do you still remember what and how did you test?

**Comment by amosbird** [comment]
> Do you still remember what and how did you test?

I don't know why your test failed to reproduce the original issue, the related kafka code is unfamiliar to me. I'm confident that it fixed real issues some user reported to me directly.

Nevertheless, we can use the following simple test to verify:

```xml
<clickhouse>
    <display_name>42</display_name>
</clickhouse>
```

```sql
select displayName();

42
```
```xml
<clickhouse>
    <display_name>41</display_name>
</clickhouse>
```

```sql
select displayName();
```

Without #62944 it will still be `42`.

**Comment by amosbird** [comment]
I've checked my chat history. The original reported case is the following:
1. Start `clickhouse-server` without any Kafka configuration.
2. Add a topic configuration:
   ```yaml
   kafka:
     kafka_topic:
       - name: topic1
         security_protocol: ssl
         enable_ssl_certificate_verification: false
         ssl_ca_location: /<location>/ca.pem
         ssl_key_location: /<location>/clickhouse-consumer_service.key
         ssl_certificate_location: /<location>/clickhouse-consumer_service.cert
   ```
3. Create a related Kafka engine and materialized view. No data consumption occurs, and an error appears in the log.
4. Restart `clickhouse-server`, and data consumption works correctly.

**Comment by antaljanosbenjamin** [comment]
Thanks for the tip, I changed the test to use `display_name` and it make everything easy. I don't want to add a test to kafka, as kafka tests are always flaky.

**Pull request merged**
