### PR TITLE
add check for systemlog tables' engine definition

### PR DESCRIPTION
**Pull request by spongedu**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Check system log tables' engine definition grammatically to prevent some configuration errors.
Notes that this grammar check is not semantical, that means  such mistakes as non-existent columns / expression functions  would be not found out util the table is created

### CODE REVIEW

**Comment by abyss7** [comment]
What kind of errors and in which scenarios have you encountered?

**Comment by spongedu** [comment]
> What kind of errors and in which scenarios have you encountered?

We customized table engine of `system.part_log` by setting `<engine>` option in `config.xml`。Unfortunately we made a grammar error and before we found out what happened, the service have been running for a while.  So I think it may be good if we can make a check before service really start.

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
LGTM.

I checked the functional tests - some of them failed because of low free space in CI.

PS. It's possible to write a test for the change in this PR but it will be too cumbersome for such a small change.

**Comment by alexey-milovidov** [comment]
@spongedu 

> Infrastructure engineer. Keen on database technologies. TiDB Committer.

Now you can make a correction:

> Infrastructure engineer. Keen on database technologies. TiDB and ClickHouse Committer.

**Comment by spongedu** [comment]
> @spongedu
> 
> > Infrastructure engineer. Keen on database technologies. TiDB Committer.
> 
> Now you can make a correction:
> 
> > Infrastructure engineer. Keen on database technologies. TiDB and ClickHouse Committer.

:)

**Pull request merged**
