### PR TITLE
Tiny cleanup

### PR DESCRIPTION
**Pull request by azat**
Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Checklist:
- align functions in fasttest/run.sh
- align subshells () in fasttest/run.sh
- Replace spaces with tabs in .gitmodules

Cc: @akuzm

### CODE REVIEW

**Comment by azat** [comment]
>Conflicting files
>.gitmodules

Rebased

**Comment by azat** [comment]
>Conflicting files
>docker/test/fasttest/run.sh

Will rebase once someone take a look

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
LGTM

**Comment by azat** [comment]
>Push to dockerhub — Updated yandex/clickhouse-fasttest

Looks like packages are broken

```
/usr/bin/dpkg-deb: 2: Syntax error: newline unexpected
dpkg: error processing archive /tmp/apt-dpkg-install-fdxX1t/00-perl-modules-5.30_5.30.0-9ubuntu0.2_all.deb (--unpack):
```

Maybe someone already looking into this?

**Comment by alesapin** [comment]
> > Push to dockerhub — Updated yandex/clickhouse-fasttest
> 
> Looks like packages are broken, and any fasttest image update will not pass:
> 
> ```
> /usr/bin/dpkg-deb: 2: Syntax error: newline unexpected
> dpkg: error processing archive /tmp/apt-dpkg-install-fdxX1t/00-perl-modules-5.30_5.30.0-9ubuntu0.2_all.deb (--unpack):
> ```
> 
> Maybe someone already looking into this?

Known failure, already fixed, I've just restarted check.

**Pull request merged**
