### PR TITLE
Cherry pick #56274 to 23.9: Fix incomplete query result for UNION in view() function.

### PR DESCRIPTION
**Pull request by robot-clickhouse-ci-2**
Original pull-request #56274

This pull-request is a first step of an automated backporting.
It contains changes like after calling a local command `git cherry-pick`.
If you intend to continue backporting this changes, then resolve all conflicts if any.
Otherwise, if you do not want to backport them, then just close this pull-request.

The check results does not matter at this step - you can safely ignore them.

### Note

This pull-request will be merged automatically as it reaches the mergeable state, **do not merge it manually**.

### If the PR was closed and then reopened

If it stuck, check https://github.com/ClickHouse/ClickHouse/pull/56274 for `pr-backports-created` and delete it if necessary. Manually merging will do nothing, since `pr-backports-created` prevents the original PR https://github.com/ClickHouse/ClickHouse/pull/56274 from being processed.

If you want to recreate the PR: delete the `pr-cherrypick` label and delete this branch.
You may also need to delete the `pr-backports-created` label from the original PR.

### CODE REVIEW

**Comment by robot-ch-test-poll** [comment]
Dear @KochetovNicolai, @alexey-milovidov, the PR is not updated for 1d0h58m5s. Please, either resolve the conflicts, or close it to finish the backport process of #56274

**Comment by robot-ch-test-poll1** [comment]
Dear @KochetovNicolai, @alexey-milovidov, the PR is not updated for 1d0h59m38s. Please, either resolve the conflicts, or close it to finish the backport process of #56274

**Comment by robot-clickhouse-ci-2** [comment]
Dear @KochetovNicolai, @alexey-milovidov, the PR is not updated for 1d0h1m28s. Please, either resolve the conflicts, or close it to finish the backport process of #56274

**Comment by robot-ch-test-poll4** [comment]
Dear @KochetovNicolai, @alexey-milovidov, the PR is not updated for 1d0h3m3s. Please, either resolve the conflicts, or close it to finish the backport process of #56274

**Comment by robot-ch-test-poll3** [comment]
Dear @KochetovNicolai, @alexey-milovidov, the PR is not updated for 1d1h1m25s. Please, either resolve the conflicts, or close it to finish the backport process of #56274

**Comment by robot-ch-test-poll3** [comment]
Dear @KochetovNicolai, @alexey-milovidov, the PR is not updated for 1d0h59m5s. Please, either resolve the conflicts, or close it to finish the backport process of #56274

**Comment by robot-ch-test-poll3** [comment]
Dear @KochetovNicolai, @alexey-milovidov, the PR is not updated for 1d0h55m4s. Please, either resolve the conflicts, or close it to finish the backport process of #56274

**Comment by robot-ch-test-poll1** [comment]
Dear @KochetovNicolai, @alexey-milovidov, the PR is not updated for 1d0h3m20s. Please, either resolve the conflicts, or close it to finish the backport process of #56274

**Comment by robot-ch-test-poll4** [comment]
Dear @KochetovNicolai, @alexey-milovidov, the PR is not updated for 1d0h1m17s. Please, either resolve the conflicts, or close it to finish the backport process of #56274

**Comment by robot-clickhouse-ci-2** [comment]
Dear @KochetovNicolai, @alexey-milovidov, the PR is not updated for 1.0d39.0h45.0m22.421014070510864s. Please, either resolve the conflicts, or close it to finish the backport process of #56274

**Comment by robot-ch-test-poll4** [comment]
Dear @KochetovNicolai, @alexey-milovidov, the PR is not updated for 1d24h12m8s. Please, either resolve the conflicts, or close it to finish the backport process of #56274

**Pull request merged**
