### PR TITLE
transform_null_in option to test NULL values at the IN-Operator.

### PR DESCRIPTION
**Pull request by ghost**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- New Feature

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Consider `NULL` to be equal to `NULL` in `IN` operator, if the option `transform_null_in` is set.

Detailed description / Documentation draft:

Basically, `IN Operator` couldn't test NULL values.

```SQL
CREATE TABLE null_in
(
    `dt` DateTime, 
    `idx` int, 
    `i` Nullable(int), 
    `s` Nullable(String)
)
ENGINE = MergeTree()
PARTITION BY dt
ORDER BY idx

INSERT INTO null_in VALUES (1, 1, 1, '1') (2, 2, NULL, NULL) (3, 3, 3, '3') (4, 4, NULL, NULL) (5, 5, 5, '5');

SELECT *
FROM null_in                  
WHERE i IN (1, 3, NULL)
FORMAT PrettySpace

                 dt   idx   i   s
1970-01-01 09:00:03     3   3   3
1970-01-01 09:00:01     1   1   1
```

I added `transform_null_in` option to test NULL values at the `IN Opreator`.

`transform_null_in` is named after [`transform_null_equals`](https://postgresqlco.nf/en/doc/param/transform_null_equals/) in postgresql.

The below example explains how to use this option.

```SQL
SELECT *
FROM null_in                  
WHERE i IN (1, 3, NULL)
SETTINGS transform_null_in = 1
FORMAT PrettySpace

                 dt   idx      i   s
1970-01-01 09:00:04     4   NULL   NULL
1970-01-01 09:00:01     1   1   1
1970-01-01 09:00:03     3   3   3
1970-01-01 09:00:02     2   NULL   NULL
```

Thank you.

### CODE REVIEW

**Review by qoega — COMMENTED** [review]
Why setting is not enabled by default?

**Comment by alexey-milovidov** [comment]
@qoega NULL is not equals to NULL.

**Comment by alexey-milovidov** [comment]
@achimbab Something is wrong, look at the tests: https://clickhouse-test-reports.s3.yandex.net/10085/53b5dade5ed488f8be0f0b8e7a624be3e5bb206c/functional_stateless_tests_(ubsan)/stderr.log

**Comment by achimbab** [comment]
@alexey-milovidov  @blinkov 
I fixed the failed case.
And I fixed some codes with testcases for Tuple and StorageSet.
Thank you.

**Comment by qoega** [comment]
> NULL is not equals to NULL
OK, is it more user-friendly if we return warning or exception if there is NULL in IN operator values, but this setting is disabled?

**Comment by alexey-milovidov** [comment]
> if there is NULL in IN operator values

Throw an exception if there is NULL in explicit list of values at the right hand of IN:
`x IN (1, NULL, 2)`
(but we cannot do that for subqueries or for Nullable columns at the left hand side)

Yes, that will be good feature.

**Comment by alexey-milovidov** [comment]
Ok.

The name of the setting and implementation functions (`nullIn`, etc.) is slightly non-intuitive but reasonable.

**Comment by alexey-milovidov** [comment]
The query `SELECT NULL IN (1, NULL, 2)` does not work. But it's still Ok.

**Review by alexey-milovidov — APPROVED** [review]

**Pull request merged**
