### PR TITLE
bump compatibility level to 10 for debian manifests

### PR DESCRIPTION
**Pull request by azat**
- d/compat: bump compatibility level to 10
- d/rules: disable hardening (they were not added in official builds anyway)

Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
Reference: https://www.debian.org/doc/manuals/maint-guide/dother.en.html
(does not shed the light)

**Review by alexey-milovidov — CHANGES_REQUESTED** [review]
It stopped to work.

**Comment by alexey-milovidov** [comment]
Maybe it's better to not use `debhelper` at all. We can pack `deb` with `ar` and `tar` manually.
We don't use any dependencies, and Debian/RPM package subsystem is totally irrelevant for us.

**Comment by azat** [comment]
>It stopped to work.

Yes, and this is because of another strange thing that I found in debian manifests - https://github.com/ClickHouse/ClickHouse/blob/97ffc4032150990554a70f03f527d88117269b52/debian/rules#L8

It enables hardening and it should fail, but it will work only since v9 compat level, so they should be disabled too (fixed)

Note, that for now this patches required only for building in debian:testing, but later when clickhouse will be switched to newer version of ubuntu it will also require them

*P.S. commit descriptions contains more details*

> Maybe it's better to not use debhelper at all. We can pack deb with ar and tar manually.
> We don't use any dependencies, and Debian/RPM package subsystem is totally irrelevant for us.

Indeed, I guess `cpack` can be used (instead of doing it manually), I can take a look if this can be solved (I'm afraid that some internal things can depends from these, although it will be pretty strange, but it pops up from time to time)

**Comment by alexey-milovidov** [comment]
> export DEB_BUILD_MAINT_OPTIONS=hardening=+all,-pie 

Let's remove it. BTW we disable `pie` explicitly.

**Comment by alexey-milovidov** [comment]
Hardening (when needed) should be enabled by global compile options in CMake, not via debian scripts.

**Review by alexey-milovidov — APPROVED** [review]

**Comment by azat** [comment]
>Hardening (when needed) should be enabled by global compile options in CMake, not via debian scripts.

Indeed (I was very surprised when I saw `_FORTIFY_SOURCE`)

**Pull request merged**
