### PR TITLE
Fix MSan failure in cache dictionary

### PR DESCRIPTION
**Pull request by alexey-milovidov**
Changelog category (leave one):
- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix potential read of uninitialized memory in cache dictionary.

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
The code of cache dictionary is very complicated and has to be thrown away.
Most likely the bug is still there in String case.

To reprocude, run `01054_cache_dictionary_bunch_update` test.
The issue is reproducing on every commit in master.

**Comment by nikitamikhaylov** [comment]
> The code of cache dictionary is very complicated and has to be thrown away.

I was thinking about simplifying cache-dictionary just yesterday evening.
So, if we will use naive LRU with hash-table and double linked list, then when we discover that some key is too old we can delete all nodes righter this one (or request an update for them). Also we have to delete those keys from hash-table and it is a bit difficult. 
Howeever, this approach will require x2 RAM, but maybe it will speed up dictionary and we will have strong guarantees about cache.

**Review by nikitamikhaylov — APPROVED** [review]
I looked through the history and it was my mistake. Sorry! The idea was not to pop items from queue infinitely (one thread pushes items to queue, our thread pops).

But I don't know how this will prevent us from reading of unitialized memory. And I don't find this issue in commits in master.

**Review by akuzm — APPROVED** [review]
>The code of cache dictionary is very complicated and has to be thrown away.

That's for sure.

**Pull request merged**
