### PR TITLE
Enable YYYY-mM-dD parsing.

### PR DESCRIPTION
**Pull request by amosbird**
This patch makes ClickHouse be able to parse DateTime string like '2017-2-3', '2017-02-3' and '2017-2-03' correctly.

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
We should try to test for performance regression.

**Comment by alexey-milovidov** [comment]
How to test:

1. Get a table with many dates.
2. Run `clickhouse-benchmark <<< "SELECT count() FROM test.hits WHERE NOT ignore(toDate(toString(EventDate)))"`
This will do many roundtrip (Date <-> String) transformations in a loop.
3. Keep the results (example):
```
QPS: 28.321, RPS: 251319059.531, MiB/s: 479.353, result RPS: 28.321, result MiB/s: 0.000.
0.000%  0.027 sec.
10.000% 0.028 sec.
20.000% 0.028 sec.
30.000% 0.033 sec.
40.000% 0.037 sec.
50.000% 0.038 sec.
60.000% 0.038 sec.
70.000% 0.039 sec.
80.000% 0.039 sec.
90.000% 0.039 sec.
95.000% 0.040 sec.
99.000% 0.041 sec.
99.900% 0.056 sec.
99.990% 0.057 sec.
```
4. Compare with the version after modification.

Don't worry if there will be noticeable performance degradation.
Usually it's possible to write the function in the way when there are no degradation in "fast path", and sometimes it will be the reason for further optimizations.

**Comment by amosbird** [comment]
Thanks. I did some tests.

test setup 
```
System:    Host: 142.nobida.cn Kernel: 3.10.0-514.26.2.el7.x86_64 x86_64 bits: 64 Console: tty 0
           Distro: CentOS Linux release 7.3.1611 (Core)
Machine:   Device: server System: Dell product: PowerEdge R720xd serial: N/A
           Mobo: Dell model: 01XT2D v: A01 serial: N/A BIOS: Dell v: 2.0.19 date: 08/29/2013
CPU(s):    2 Hexa core Intel Xeon E5-2620 0s (-HT-MCP-SMP-) cache: 30720 KB
           clock speeds: max: 2500 MHz 1: 1199 MHz 2: 1199 MHz 3: 1199 MHz 4: 1200 MHz 5: 1200 MHz
           6: 1199 MHz 7: 1199 MHz 8: 1199 MHz 9: 1200 MHz 10: 1199 MHz 11: 1200 MHz 12: 1199 MHz
           13: 1199 MHz 14: 1200 MHz 15: 1200 MHz 16: 1199 MHz 17: 1199 MHz 18: 1199 MHz 19: 1199 MHz
           20: 1199 MHz 21: 1200 MHz 22: 1200 MHz 23: 1200 MHz 24: 1199 MHz
Graphics:  Card: Matrox Systems G200eR2
           Display Server: N/A driver: mgag200 tty size: 105x49 Advanced Data: N/A out of X
Network:   Card-1: Intel I350 Gigabit Network Connection driver: igb
           IF: em1 state: up speed: 1000 Mbps duplex: full mac: b8:ca:3a:67:07:70
           Card-2: Intel I350 Gigabit Network Connection driver: igb
           IF: em2 state: down mac: b8:ca:3a:67:07:71
           Card-3: Intel I350 Gigabit Network Connection driver: igb
           IF: em3 state: down mac: b8:ca:3a:67:07:72
           Card-4: Intel I350 Gigabit Network Connection driver: igb
           IF: em4 state: down mac: b8:ca:3a:67:07:73
           Card-5: Intel 82599ES 10-Gigabit SFI/SFP+ Network Connection driver: ixgbe
           IF: p5p1 state: up speed: 10000 Mbps duplex: full mac: 90:e2:ba:34:51:48
           Card-6: Intel 82599ES 10-Gigabit SFI/SFP+ Network Connection driver: ixgbe
           IF: p5p2 state: down mac: 90:e2:ba:34:51:49
Drives:    HDD Total Size: 34000.0GB (28.7% used)
           ID-1: /dev/sda model: PERC_H710 size: 33000.4GB
           ID-2: /dev/sdb model: PERC_H710 size: 999.7GB
Partition: ID-1: / size: 50G used: 18G (36%) fs: xfs dev: /dev/dm-0
           ID-2: /boot size: 1014M used: 277M (28%) fs: xfs dev: /dev/sdb1
           ID-3: /home size: 876G used: 282G (33%) fs: xfs dev: /dev/dm-2
RAID:      No RAID devices: /proc/mdstat, md_mod kernel module present
Sensors:   System Temperatures: cpu: 43.0C mobo: N/A
           Fan Speeds (in rpm): cpu: N/A
Info:      Processes: 453 Uptime: 14 days Memory: 7891.7/80344.1MB Init: systemd runlevel: 3
           Client: Shell (fish) inxi: 2.3.36

Clickhouse commit  c4b4764a0
gcc (GCC) 7.2.0

test data   :   OnTime
record number :  175043894
table size :  14.17GB

test command : clickhouse-benchmark <<<"SELECT count() FROM ontime WHERE NOT ignore(toDate(toString(FlightDate)))"

```

## Test result without this patch

```
Queries executed: 465.

QPS: 0.971, RPS: 169956710.977, MiB/s: 324.167, result RPS: 0.971, result MiB/s: 0.000.
0.000%  1.028 sec.
10.000% 1.028 sec.
20.000% 1.028 sec.
30.000% 1.028 sec.
40.000% 1.028 sec.
50.000% 1.028 sec.
60.000% 1.028 sec.
70.000% 1.028 sec.
80.000% 1.028 sec.
90.000% 1.028 sec.
95.000% 1.028 sec.
99.000% 1.028 sec.
99.900% 1.028 sec.
99.990% 1.028 sec.

Queries executed: 466.

QPS: 0.985, RPS: 172334823.321, MiB/s: 328.703, result RPS: 0.985, result MiB/s: 0.000.
0.000%  1.020 sec.
10.000% 1.020 sec.
20.000% 1.020 sec.
30.000% 1.020 sec.
40.000% 1.020 sec.
50.000% 1.020 sec.
60.000% 1.020 sec.
70.000% 1.020 sec.
80.000% 1.020 sec.
90.000% 1.020 sec.
95.000% 1.020 sec.
99.000% 1.020 sec.
99.900% 1.020 sec.
99.990% 1.020 sec.

Queries executed: 467.

QPS: 0.979, RPS: 171402420.272, MiB/s: 326.924, result RPS: 0.979, result MiB/s: 0.000.
0.000%  1.121 sec.
10.000% 1.121 sec.
20.000% 1.121 sec.
30.000% 1.121 sec.
40.000% 1.121 sec.
50.000% 1.121 sec.
60.000% 1.121 sec.
70.000% 1.121 sec.
80.000% 1.121 sec.
90.000% 1.121 sec.
95.000% 1.121 sec.
99.000% 1.121 sec.
99.900% 1.121 sec.
99.990% 1.121 sec.

Queries executed: 468.

QPS: 0.996, RPS: 174340655.922, MiB/s: 332.528, result RPS: 0.996, result MiB/s: 0.000.
0.000%  0.904 sec.
10.000% 0.904 sec.
20.000% 0.904 sec.
30.000% 0.904 sec.
40.000% 0.904 sec.
50.000% 0.904 sec.
60.000% 0.904 sec.
70.000% 0.904 sec.
80.000% 0.904 sec.
90.000% 0.904 sec.
95.000% 0.904 sec.
99.000% 0.904 sec.
99.900% 0.904 sec.
99.990% 0.904 sec.
^CStopping launch of queries. SIGINT recieved.

Queries executed: 470.

QPS: 1.049, RPS: 183538445.406, MiB/s: 350.072, result RPS: 1.049, result MiB/s: 0.000.
0.000%  0.852 sec.
10.000% 0.879 sec.
20.000% 0.899 sec.
30.000% 0.908 sec.
40.000% 0.917 sec.
50.000% 0.933 sec.
60.000% 0.949 sec.
70.000% 0.976 sec.
80.000% 1.009 sec.
90.000% 1.058 sec.
95.000% 1.104 sec.
99.000% 1.152 sec.
99.900% 1.297 sec.
99.990% 1.305 sec.
```

## Test result with this patch

```
Queries executed: 305.

QPS: 0.988, RPS: 173014779.264, MiB/s: 330.000, result RPS: 0.988, result MiB/s: 0.000.
0.000%  1.012 sec.
10.000% 1.012 sec.
20.000% 1.012 sec.
30.000% 1.012 sec.
40.000% 1.012 sec.
50.000% 1.012 sec.
60.000% 1.012 sec.
70.000% 1.012 sec.
80.000% 1.012 sec.
90.000% 1.012 sec.
95.000% 1.012 sec.
99.000% 1.012 sec.
99.900% 1.012 sec.
99.990% 1.012 sec.

Queries executed: 306.

QPS: 0.976, RPS: 170877424.448, MiB/s: 325.923, result RPS: 0.976, result MiB/s: 0.000.
0.000%  1.023 sec.
10.000% 1.023 sec.
20.000% 1.023 sec.
30.000% 1.023 sec.
40.000% 1.023 sec.
50.000% 1.023 sec.
60.000% 1.023 sec.
70.000% 1.023 sec.
80.000% 1.023 sec.
90.000% 1.023 sec.
95.000% 1.023 sec.
99.000% 1.023 sec.
99.900% 1.023 sec.
99.990% 1.023 sec.

Queries executed: 307.

QPS: 0.923, RPS: 161509778.349, MiB/s: 308.055, result RPS: 0.923, result MiB/s: 0.000.
0.000%  1.086 sec.
10.000% 1.086 sec.
20.000% 1.086 sec.
30.000% 1.086 sec.
40.000% 1.086 sec.
50.000% 1.086 sec.
60.000% 1.086 sec.
70.000% 1.086 sec.
80.000% 1.086 sec.
90.000% 1.086 sec.
95.000% 1.086 sec.
99.000% 1.086 sec.
99.900% 1.086 sec.
99.990% 1.086 sec.

Queries executed: 308.

QPS: 0.995, RPS: 174201433.916, MiB/s: 332.263, result RPS: 0.995, result MiB/s: 0.000.
0.000%  1.105 sec.
10.000% 1.105 sec.
20.000% 1.105 sec.
30.000% 1.105 sec.
40.000% 1.105 sec.
50.000% 1.105 sec.
60.000% 1.105 sec.
70.000% 1.105 sec.
80.000% 1.105 sec.
90.000% 1.105 sec.
95.000% 1.105 sec.
99.000% 1.105 sec.
99.900% 1.105 sec.
99.990% 1.105 sec.
```

It seems there is a 5% performance penalty.

**Comment by alexey-milovidov** [comment]
Almost Ok.

But I don't see total report (the last report after you press Ctrl+C). I want to compare minimum time:
`0.000%  0.852 sec.`

**Comment by amosbird** [comment]
Oh, i didn't notice the last one is a summary :)

## Test without this patch
```
QPS: 1.049, RPS: 183538445.406, MiB/s: 350.072, result RPS: 1.049, result MiB/s: 0.000.
0.000%  0.852 sec.
10.000% 0.879 sec.
20.000% 0.899 sec.
30.000% 0.908 sec.
40.000% 0.917 sec.
50.000% 0.933 sec.
60.000% 0.949 sec.
70.000% 0.976 sec.
80.000% 1.009 sec.
90.000% 1.058 sec.
95.000% 1.104 sec.
99.000% 1.152 sec.
99.900% 1.297 sec.
99.990% 1.305 sec.
```
## Test with this patch
```
QPS: 0.945, RPS: 165406462.828, MiB/s: 315.488, result RPS: 0.945, result MiB/s: 0.000.
0.000%  0.971 sec.
10.000% 0.980 sec.
20.000% 0.995 sec.
30.000% 1.010 sec.
40.000% 1.028 sec.
50.000% 1.048 sec.
60.000% 1.073 sec.
70.000% 1.091 sec.
80.000% 1.114 sec.
90.000% 1.143 sec.
95.000% 1.162 sec.
99.000% 1.233 sec.
99.900% 1.447 sec.
99.990% 1.475 sec.
```

**Comment by alexey-milovidov** [comment]
Ok.

There is 14% performance difference.
Also there is missing test for the modification.

**Comment by alexey-milovidov** [comment]
I will totally rewrite this code in separate PR.
But I like to see you in contributors, so I will merge this pull request :)

**Comment by alexey-milovidov** [comment]
https://github.com/yandex/ClickHouse/pull/1495

Now the code is actually faster than before (+8%).
Also added functional and performance test.

**Comment by amosbird** [comment]
Great!

**Pull request merged**
