### PR TITLE
Fix thread not check joinable before join which may cause risk

### PR DESCRIPTION
**Pull request by xuzifu666**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Fix thread not check joinable before join which may cause risk

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by xuzifu666** [comment]
@rschu1ze PTAL

**Comment by alexey-milovidov** [comment]
What is the scenario?

**Comment by xuzifu666** [comment]
> What is the scenario?

Hi，alexey，in batch threads join add joinable check is better and it is a nesssary specification，can see it in Clickhouse ThreadPool  finalize method and so on. @alexey-milovidov

**Comment by alexey-milovidov** [comment]
What is the scenario when the thread is non-joinable?

**Comment by xuzifu666** [comment]
> What is the scenario when the thread is non-joinable? How is this scenario possible in the code?

It would break out in c++11 or above when calling if thread is non-joinable.  it is a specification for it avoid calling non-joinable thread @alexey-milovidov

**Comment by alexey-milovidov** [comment]
Is it possible that this thread is non-joinable?

**Comment by xuzifu666** [comment]
> Is it possible that this thread is non-joinable?

If it is non-joinable then make thread join，it would break down the process which is dangerous @alexey-milovidov

**Comment by alexey-milovidov** [comment]
I've checked the code of `ThreadPool`, and found that this is an invariant - if the thread exists, it is joinable.
If this invariant is not met, the method `std::thread::join` will terminate.

> If it is non-joinable then make thread join，it would break down the process which is dangerous

Termination on assertion violation is safe, and it is a good practice for writing reliable software - because it does not hide logical errors in code.

**Comment by xuzifu666** [comment]
> t does not hide logical

OK，keep it better

**Comment by alexey-milovidov** [comment]
Ok. But if it reproduces, we should fix it.

**Pull request closed without merging**
