### PR TITLE
Modify find_first_symbols so it works as expected for find_first_not_symbols

### PR DESCRIPTION
**Pull request by arthurpassos**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in official stable or prestable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
`find_first_not_symbols` is not working as expected for different inputs. It works as expected when it is resolved by SSE4, but if it fallsback to the loop method it'll fail. Loop method code compares each of the symbols/ needles characters against the current character and negates each comparison. If any of the negations return true, it will return the current position, but that's a bug. Instead of negating each comparison, the code should negate the result of all comparisons together.

In terms of unit tests, the issue looks like the below:

```
// 15 byte long string, only loop takes place
std::string_view multiple_needles_haystack = "helloworldddddd";
const auto * res = find_first_not_symbols<'h', 'e', 'l', 'o', 'w', 'r', 'd'>(multiple_needles_haystack.begin(), multiple_needles_haystack.end());

ASSERT_EQ(res, multiple_needles_haystack.begin());

// 16 byte long string, only vectorized takes place
std::string_view multiple_needles_haystack = "helloworlddddddd";
const auto * res = find_first_not_symbols<'h', 'e', 'l', 'o', 'w', 'r', 'd'>(multiple_needles_haystack.begin(), multiple_needles_haystack.end());

ASSERT_EQ(res, multiple_needles_haystack.end());

// 17 byte long string, both vectorized and loop takes place
std::string_view multiple_needles_haystack = "helloworldddddddd";
const auto * res = find_first_not_symbols<'h', 'e', 'l', 'o', 'w', 'r', 'd'>(multiple_needles_haystack.begin(), multiple_needles_haystack.end());

ASSERT_EQ(res, multiple_needles_haystack.end() - 1);
```

All assertions hold true with different expressions, but my expectations it that the output of all calls should match. More precisely, I would expect the result that came out of the second execution where only vectorized took place and the returned value was == ::end

This PR changes the loop logic to negate the result of all comparisons instead of negating each of them. 

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by arthurpassos** [comment]
02232_dist_insert_send_logs_level_hung: https://github.com/ClickHouse/ClickHouse/pull/47309#issuecomment-1459801945

**Comment by arthurpassos** [comment]
If I get it right, Bugfix check needs either function or integration tests, right? This is not a bug I spotted while using a CH feature, it was during internal usage of the API. Do I really need those tests or unit tests are enough?

**Comment by alexey-milovidov** [comment]
If it is not a bug in ClickHouse, it should not have a "bugfix" category. Otherwise, it should be proven by functional tests.
If it is not a fix for a major issue, it does not need to be backported.

**Comment by CheSema** [comment]
The most dangerous usage of the function find_first_not_symbols is in quotedHexOrBinString. But for that case defferent realisation find_first_symbols_sse2 is chosen.

**Comment by arthurpassos** [comment]
@CheSema @alexey-milovidov Why was the PR closed? I understand you don't consider it a user-facing bug, but there is a bug in the code and I published a PR to fix it

**Comment by CheSema** [comment]
Nonono! Just my fault. It seems like I push something wrong.

**Comment by arthurpassos** [comment]
> Special build failed :(
> 
> ```
> Mar 09 20:09:28 /build/src/Common/tests/gtest_find_symbols.cpp:82:22: error: redundant string initialization [readability-redundant-string-init,-warnings-as-errors]
> Mar 09 20:09:28     std::string_view s = "";
> Mar 09 20:09:28                      ^~~~~~
> Mar 09 20:09:28                      s
> ```

oh well, hard to make 'em all happy lol. Guess I'll have to refactor to use `std::string` instead of `std::string_view`

**Comment by CheSema** [comment]
> > Special build failed :(
> > ```
> > Mar 09 20:09:28 /build/src/Common/tests/gtest_find_symbols.cpp:82:22: error: redundant string initialization [readability-redundant-string-init,-warnings-as-errors]
> > Mar 09 20:09:28     std::string_view s = "";
> > Mar 09 20:09:28                      ^~~~~~
> > Mar 09 20:09:28                      s
> > ```
> 
> oh well, hard to make 'em all happy lol. Guess I'll have to refactor to use `std::string` instead of `std::string_view`

Why don't we just check for the nullptr in the function? I think would be safer and compatible with empty string_view as well.

**Comment by arthurpassos** [comment]
> 

Hm.. it's one extra check for every lookup, but I don't think it would harm performance. I guess it's a matter of responsability: Should caller ensure function is called with valid input or callee ensure input is valid.

I think I am fine with both, tbh. But bear in mind it'll require changes in multiple functions to make it consistent: `find_first_symbols_sse2`, `find_last_symbols_sse2`, `find_first_symbols_sse42` and etc.

**Comment by CheSema** [comment]
In my opinion, find_first_symbols_dispatch is a right place to check input params for nullptr and return an answer instantly.  
All other specifications find_first_symbols_* are legal to considered pointer as not nullptr after that check. 
Btw those specifications are like private. They aren't reachable by user normally.
I don't see any required changes in specifications in that approach. May be I miss something.

**Comment by arthurpassos** [comment]
> In my opinion, find_first_symbols_dispatch is a right place to check input params for nullptr and return an answer instantly. All other specifications find_first_symbols_* are legal to considere pointer as not nullptr after that check. Btw those specifications are like private. They aren't reachable by user normally. I don't see any required changes in specifications in that approach. May be I miss something.

Oh, true, most of those functions are in the `detail` namespace. Most of the "public" functions go through the `dispatch` one, so that's the place to put it. Aside from these, the `find_last_symbols` functions are public and do not go through the dispatch one, but they all call `find_last_symbols_sse2`.

In a nutshell, two places to add the `nullptr` check: `find_first_symbols_dispatch` and `find_last_symbols_sse2`.

Please correct me if I am wrong

**Comment by alexey-milovidov** [comment]
These are low-level functions. They shouldn't check for nullptr.

**Comment by CheSema** [comment]
> These are low-level functions. They shouldn't check for nullptr.

Well, if so, then this version of code is just fine. No more changes are needed.

**Review by CheSema — APPROVED** [review]

**Comment by CheSema** [comment]
I will check the failed test in Monday if there is no urgency.

**Comment by CheSema** [comment]
test_insert_select_replicated -- fixes in https://github.com/ClickHouse/ClickHouse/pull/47547/files

**Comment by arthurpassos** [comment]
Thanks for looking into this

**Pull request merged**
