### PR TITLE
Better Null format for tcp handler.

### PR DESCRIPTION
**Pull request by amosbird**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

For changelog. Remove if this is non-significant change.

Category (leave one):
- Improvement

Short description (up to few sentences):

so that we can use `select ignore(<expression>) from table format Null` for perf measure via clickhouse-client

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]
Ok.

**Comment by alexey-milovidov** [comment]
I always kept this in mind but refused to implement because of limited benefits and compromised simplicity of code. But it's still nice to have.

**Comment by alexey-milovidov** [comment]
I also used Null format to test network throughput:

`clickhouse-client --host remote-server --query 'SELECT rand64() FROM system.numbers FORMAT Null'`

Now this use case will fail :(

**Comment by alexey-milovidov** [comment]
Probably your use case outweight my use case :)

**Comment by amosbird** [comment]
> I also used Null format to test network throughput:
> 
> `clickhouse-client --host remote-server --query 'SELECT rand64() FROM system.numbers FORMAT Null'`
> 
> Now this use case will fail :(

Interesting use case. Perhaps we can revert this and implement alternative. I also tried extending the `SELECT INTO OUTFILE` grammar as `SELECT INTO NULL`.

**Pull request merged**
