### PR TITLE
add setting exact_rows_before_limit

### LINKED ISSUE #6613: Allow to provide exact value instead of "rows_before_limit_at_least"
**Describe the solution you'd like**
A setting `exact_rows_before_limit` = 0|1. When enabled, `LimitBlockInputStream` will `always_read_till_end_` (we already have this feature in code) and the field `rows_before_limit_at_least` will have precise value.

### PR DESCRIPTION
**Pull request by MaxWk**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- New Feature

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Added a setting `exact_rows_before_limit` (0/1). When enabled, ClickHouse will provide exact value for `rows_before_limit_at_least` statistic, but with the cost that the data before limit will have to be read completely.
This closes #6613.

Detailed description / Documentation draft:

A setting exact_rows_before_limit = 0|1. When enabled, LimitBlockInputStream will always_read_till_end (we already have this feature in code) and the field rows_before_limit_at_least will have precise value.
https://github.com/ClickHouse/ClickHouse/issues/6613

By adding documentation, you'll allow users to try your new feature immediately, not when someone else will have time to document it later. Documentation is necessary for all features that affect user experience in any way. You can add brief documentation draft above, or add documentation right into your patch as Markdown files in [docs](https://github.com/ClickHouse/ClickHouse/tree/master/docs) folder.

If you are doing this for the first time, it's recommended to read the lightweight [Contributing to ClickHouse Documentation](https://github.com/ClickHouse/ClickHouse/tree/master/docs/README.md) guide first.

Information about CI checks: https://clickhouse.tech/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by abyss7** [comment]
Changelog entry (and the in-code description) is obscure for users: you should describe the new setting at the user-level scenarios - since typical user doesn't know what is `LimitBlockInputStream`, where it's located in the pipeline and how it affects typical `SELECT` queries.

Also please add the test.

**Review by abyss7 — CHANGES_REQUESTED** [review]
Changelog entry (and the in-code description) is obscure for users: you should describe the new setting at the user-level scenarios - since typical user doesn't know what is `LimitBlockInputStream`, where it's located in the pipeline and how it affects typical `SELECT` queries.

Also please add the test.

**Comment by MaxWk** [comment]
> Changelog entry (and the in-code description) is obscure for users: you should describe the new setting at the user-level scenarios - since typical user doesn't know what is `LimitBlockInputStream`, where it's located in the pipeline and how it affects typical `SELECT` queries.
> 
> Also please add the test.

Hi abyss7 ,thank you for your quick reply. I have edit the Changelog entry。

**Comment by alexey-milovidov** [comment]
@MaxWk Why it is in draft stage? The change should be quite easy and we need this feature...

**Review by alexey-milovidov — APPROVED** [review]
Everything looks alright :)

**Comment by alexey-milovidov** [comment]
@mergifyio update

**Comment by alexey-milovidov** [comment]
@mergifyio update

**Comment by MaxWk** [comment]
> feature

Sorry for late reply,  This pull request was forgotten by me, I thought it had been merged

**Comment by alexey-milovidov** [comment]
Still not merged - the test about this feature has failed.

**Comment by m1khal3v** [comment]
Any news here?

**Comment by Cimus** [comment]
Update

**Comment by supermarat** [comment]
really need

**Comment by MaxWk** [comment]
update

**Comment by MaxWk** [comment]
@alexey-milovidov @abyss7 I'm sorry it took so long to do this, I've been so busy with work lately, please help me review
 this

**Comment by MaxWk** [comment]
@Mergifyio update

**Comment by MaxWk** [comment]
@qoega These errors seems not relate to my update

**Comment by qoega** [comment]
Yes. Flaky check just shows that timeout was hit before the number of ribs or wanted to run. Absolutely normal if test is long.

**Review by alexey-milovidov — APPROVED** [review]
The code LGTM.

**Pull request merged**
