### PR TITLE
Fix ClickHouse init process failed in docker if any script is added into docker-entrypoint-initdb.d 

### PR DESCRIPTION
**Pull request by istarkov**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):

- Bug Fix

Changelog entry:
Now clickhouse-server docker container will prefer IPv6 checking server aliveness.

Detailed description / Documentation draft:
Docker container doesn't start with error "ClickHouse init process failed." if any script is added into _docker-entrypoint-initdb.d_wget uses 'localhost' which resolves for both ipv4 and ipv6 with current config (/etc/hosts) and so the wget fails _(Address family not supported by protocol)_ and does not retry. Forcing it to use IPv4 fixes the issue

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]

**Comment by qoega** [comment]
Do you know how docker sets up container on ipv6only server with `--network=host`? Probably it is easier to try both `-4 -6` calls?

**Comment by istarkov** [comment]
Have no idea, haven't checked this case

**Comment by istarkov** [comment]
Will check

**Comment by istarkov** [comment]
Instead of forcing protocol prefer-family seems like fixing all issues

**Review by filimonov — APPROVED** [review]
Great! I've also faced that issue once. 

option with `prefer-family=IPv6` looks very clean.

**Review by alesapin — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
test_always_fetch_merged - known flaky test: #11484
Description check — Changelog entry is not found - already fixed.

**Pull request merged**
