### PR TITLE
List replication queue only for current test database

### PR DESCRIPTION
**Pull request by davenger**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by davenger** [comment]
https://s3.amazonaws.com/clickhouse-test-reports/52144/a0fef7496926e0a64797294d97c488b6eb0cf59e/stateless_tests_flaky_check__asan_.html

**Comment by robot-ch-test-poll3** [comment]
This is an automated comment for commit 722b3859083daf255f7dcde1d188cb9521d37962 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/52238/722b3859083daf255f7dcde1d188cb9521d37962/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Review by novikd — APPROVED** [review]

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alesapin** [comment]
Maybe just remove these two tests?

**Comment by davenger** [comment]
> Maybe just remove these two tests?

Hmm... Didn't think about such a way to fix tests :)

**Comment by novikd** [comment]
> Hmm... Didn't think about such a way to fix tests :)

Works all the time

**Comment by davenger** [comment]
At last "Stateless tests flaky check" passed

**Pull request merged**
