### PR TITLE
[RFC] Introduce create_as_skip_indices

### PR DESCRIPTION
**Pull request by azat**
Category (leave one):
- New Feature

Short description (up to few sentences):

Useful to create Distributed/Buffer table using CREATE TABLE ... AS ...
for MergeTree family tables.

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
The problem is clear.

The proposed solution with setting has downside: the user should know about this settings and should enable it.

Wouldn't it be better to add `IStorage::supportSecondaryIndices` method and ignore indices if storage is created AS and indices are not supported?

**Comment by azat** [comment]
>the user should know about this setting and should enable it.

Indeed, plus it is hard to keep all this settings in mind

>Wouldn't it be better to add IStorage::supportSecondaryIndices method and ignore indices if storage is created AS and indices are not supported?

Agree, will update the patch

**Comment by azat** [comment]
>Wouldn't it be better to add IStorage::supportSecondaryIndices method and ignore indices if storage is created AS and indices are not supported?

Hm, we do not have Storage yet during parsing the query (and filling indexes), and during creating Storage we do not have `AS` flag (for now), so I'm thinking about just check against "MergeTree" in `InterpreterCreateQuery::setProperties`, or do you have strong feelings against this?

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
It's Ok. Added a comment.

**Pull request merged**
