### PR TITLE
Parallelize PK range and skipping index stages

### PR DESCRIPTION
**Pull request by bobrik**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Performance Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Parallel PK lookup and skipping index stages on parts, as described in #11564.

Detailed description / Documentation draft:

While #12277 sped up PK lookups, skipping index stage may still be a bottleneck in a select query. Here we parallelize both stages between parts.

On a query that uses a bloom filter skipping index to pick 2,688 rows out of 8,273,114,994 on a two day time span, this change reduces latency from 10.5s to 1.5s.

### CODE REVIEW

**Comment by KochetovNicolai** [comment]
Oops, set index is not thread-safe because of this:
https://github.com/ClickHouse/ClickHouse/blob/3854ce6d8467ca29b7261f9420e25d8551a19bd3/src/Interpreters/Set.cpp#L476-L478

@CurtizJ how do you think it will affect performance if we move those lines back to `checkInRange`?

**Comment by CurtizJ** [comment]
It will affect performance not so much. I think parallelizing will compensate it.

**Comment by bobrik** [comment]
@KochetovNicolai, thanks for taking care of this! One issue I'm seeing with my manual testing is that some logging is missing now, in particular there are no more messages for PK search or skipping indices:

* `Used optimized inclusion search ...`
* `Index X has dropped Y granules`

These were super useful when optimizing, I wouldn't want to lose them.

**Comment by KochetovNicolai** [comment]
@bobrik ok, I'll check it.
No logging have I removed, so this is suspicious.

**Comment by bobrik** [comment]
I'm using this branch rebased on top of v20.7.1.4140-testing, so maybe there was a change in master that caused it.

**Comment by bobrik** [comment]
I checked with v20.7.1.4140-testing and it has logging in place, so it must be something about thread pools that hides logs.

**Comment by KochetovNicolai** [comment]
@bobrik I've build this branch and I can see messages like 
```
Used generic exclusion search over index for part 128_3_3_0 with 4353 steps
Index `a` has dropped 152 granules
```

in log. Code is still here:
https://github.com/ClickHouse/ClickHouse/pull/12589/files#diff-d5c8199c63973fc53a48faa0f94942a8R1525
So, it is strange that you don't see it...

**Comment by KochetovNicolai** [comment]
Tried build from ci, and there are messages in log.

**Comment by KochetovNicolai** [comment]
`Performance — 7 faster, 1 slower, 249 unstable` - good enough.
Merging.

**Comment by bobrik** [comment]
@KochetovNicolai are you querying across multiple parts? I can see the log lines when I only hit one part:

```
MinMax index condition: (negate(toUnixTimestamp(column 0)) in [-1594515600, -1594515600]), unknown, unknown, and, and, (negate(toUnixTimestamp(column 0)) in [-1594515600, -1594515600]), and
Used optimized inclusion search over index for part 20200712_25782_604049_13_10506488 with 47 steps
Index `idx_tags` has dropped 0 granules.
Selected 1 parts by date, 1 parts by key, 19 marks to read from 1 ranges
MergeTreeSelectProcessor: Reading 5 ranges from part 20200712_25782_604049_13_10506488, approx. 19456 rows starting from 4984492032
InterpreterSelectQuery: FetchColumns -> Complete
```

But as soon as multiple parts kick off parallelism, logs disappear:

```
MinMax index condition: (negate(toUnixTimestamp(column 0)) in [-1594517400, -1594517400]), unknown, unknown, and, and, (negate(toUnixTimestamp(column 0)) in [-1594517400, -1594517400]), and
Selected 2 parts by date, 2 parts by key, 21 marks to read from 2 ranges
MergeTreeSelectProcessor: Reading 1 ranges from part 20200712_604050_633634_10_10506488, approx. 1024 rows starting from 263741440
MergeTreeSelectProcessor: Reading 5 ranges from part 20200712_25782_604049_13_10506488, approx. 20480 rows starting from 4956267520
InterpreterSelectQuery: FetchColumns -> Complete
```

It definitely feels like it's related to this PR.

**Comment by KochetovNicolai** [comment]
@bobrik yes, I've checked if to queries from test I added.
But maybe it is connected with thread_pool indeed, cause for single part it is not used.

**Comment by azat** [comment]
>But maybe it is connected with thread_pool indeed, cause for single part it is not used.

Indeed - #13201

**Comment by tangxueming** [comment]
My version is 20.11.4. There is 30 billions+ rows in my dataset.It spends 30+ seconds  for my query with a bloom fliter skipping index (id column).
Example:  select * from my_table where id = 'adasdasdqwdz'; 
Similarly to #7046, nothing happen for long time before appearing the progress bar.
create table query like:
create table bloom_test(
    timestamp Int64 comment 'microsecond',
    time_date                      Date comment 'yyyyMMdd',
    s String,
    INDEX s_index s TYPE bloom_filter() GRANULARITY 5
) Engine=MergeTree 
      PARTITION BY toYYYYMMDD(time_date)
      order by timestamp;
Look forward to your reply, thank you.

**Comment by Slach** [comment]
@tangxueming 
could you open `clickhouse-client `
and run
```
SET send_logs_level='trace'
SELECT * FROM my_table WHERE s = 'adasdasdqwdz';
```

and try to figure out with logs

**Comment by tangxueming** [comment]
@Slach Thank you for your help.

```sql
#schema (in fact, I use distributed table)
CREATE TABLE pupu_monitor.apm_zipkin_shard
(
    `timestamp` UInt64,
    `id` String,
    `kind` LowCardinality(String),
    `name` LowCardinality(String),
    `traceId` String,
    `duration` UInt64,
    `localEndpoint.serviceName` LowCardinality(String),
    `localEndpoint.ipv4` String,
    `localEndpoint.port` UInt16,
    `remoteEndpoint.serviceName` LowCardinality(String),
    `remoteEndpoint.ipv4` String,
    `remoteEndpoint.port` UInt8,
    `tags.api.url` String,
    `tags.args` String,
    `tags.client.name` LowCardinality(String),
    `tags.cluster` LowCardinality(String),
    `tags.database` LowCardinality(String),
    `tags.dubbo.api` LowCardinality(String),
    `tags.env` LowCardinality(String),
    `tags.http.method` LowCardinality(String),
    `tags.http.path` String,
    `tags.http.status_code` UInt16,
    `tags.parent.name` String,
    `tags.sql.query` String,
    `tags.thread.id` String,
    `tags.thread.name` String,
    `tags.type` LowCardinality(String),
    `time_date` Date DEFAULT toDate(time_datetime),
    `time_mills` UInt64 DEFAULT timestamp / 1000,
    `time_datetime` DateTime DEFAULT toDateTime(time_mills / 1000),
    `time_date_hour` DateTime DEFAULT toStartOfHour(time_datetime),
    `time_date_2hour` DateTime DEFAULT toStartOfInterval(time_datetime, toIntervalHour(2)),
    `time_date_4hour` DateTime DEFAULT toStartOfInterval(time_datetime, toIntervalHour(4)),
    `time_date_8hour` DateTime DEFAULT toStartOfInterval(time_datetime, toIntervalHour(8)),
    `time_date_hour_minute` DateTime DEFAULT toStartOfMinute(time_datetime),
    `time_date_hour_5minute` DateTime DEFAULT toStartOfFiveMinute(time_datetime),
    `time_date_hour_10minute` DateTime DEFAULT toStartOfTenMinutes(time_datetime),
    `time_date_hour_15minute` DateTime DEFAULT toStartOfFifteenMinutes(time_datetime),
    `time_date_hour_30minute` DateTime DEFAULT toStartOfInterval(time_datetime, toIntervalMinute(30)),
    `message_stored_at` DateTime64(3) DEFAULT toDateTime64(now64(), 3, 'UTC'),
    `duration_mills` UInt64 DEFAULT duration / 1000,
    `tags.error` String DEFAULT '',
    `parentId` String DEFAULT '',
    `tags.user.id` String DEFAULT '',
    INDEX idx_duration duration TYPE minmax GRANULARITY 5,
    INDEX idx_trace_id traceId TYPE bloom_filter() GRANULARITY 5,
    INDEX idx_id id TYPE bloom_filter() GRANULARITY 5
)
ENGINE = ReplicatedMergeTree('/clickhouse/tables/pupu_monitor.apm_zipkin_shard/{shard}', '{replica}')
PARTITION BY (time_date, time_date_8hour)
ORDER BY (timestamp, duration)
TTL time_date + toIntervalDay(30)
SETTINGS index_granularity = 8192
```
This is the log file.
[log.txt](https://github.com/ClickHouse/ClickHouse/files/5640109/log.txt)
According to log file, I think ck work well.
 Is the dataset too big?  
  select count(*) from distributed;   47 billions
  select count(*) from shard;           7.8 billions
There is 6 nodes in our cluster. We use  one replication.
Do I need add server?

**Comment by bobrik** [comment]
@tangxueming your schema is not optimized for lookup by `id`, because `id` is not a part of the primary key.

Take a look at this: https://github.com/bobrik/jaeger/tree/ivan/clickhouse/plugin/storage/clickhouse#schema

**Comment by tangxueming** [comment]
> @tangxueming your schema is not optimized for lookup by `id`, because `id` is not a part of the primary key.
> 
> Take a look at this: https://github.com/bobrik/jaeger/tree/ivan/clickhouse/plugin/storage/clickhouse#schema

@bobrik  Thanks.
1.After look at the blog, I maybe need to create a new table which set id as primary key and model column is the record info.
select model from new_table where id ='xxx';
This method can resolve my problem.
2.Is  any approach to improve bloom filter performance。

**Pull request merged**
