### PR TITLE
Do not re-create serialization for each row during rocksdb sinking

### PR DESCRIPTION
**Pull request by canhld94**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
- Improve write performance to rocksdb

Creating serialisations for some types can be expensive, e.g. `Enum` with many possible values.
image

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by hanfei1991** [comment]
@canhld94 you are right. I am just curious how much it will help when you insert lots of data in one go. Even if not, this logic will be better too.

**Review by hanfei1991 — APPROVED** [review]

**Comment by canhld94** [comment]
It can be improve a little more. We don't need to create block from chunk now.

**Comment by canhld94** [comment]
And the importing speed change is indeed noticeable:

Before:

```
0 rows in set. Elapsed: 188.351 sec. Processed 8.19 million rows, 6.20 GB (43.46 thousand rows/s., 32.92 MB/s.)
```

After:

```
0 rows in set. Elapsed: 34.621 sec. Processed 8.19 million rows, 6.20 GB (236.46 thousand rows/s., 179.11 MB/s.)
```

**Comment by canhld94** [comment]
All failed tests look unrelated (redis)

**Pull request merged**
