### PR TITLE
Deprecate LIVE VIEW

### PR DESCRIPTION
**Pull request by alexey-milovidov**
### Changelog category (leave one):
- Documentation (changelog entry is not required)

### CODE REVIEW

**Comment by robot-ch-test-poll3** [comment]
*This is an automated comment for commit 0d1bdff3476e2e4406b327ccd7d0bee3bffa8939 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/57706/0d1bdff3476e2e4406b327ccd7d0bee3bffa8939/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td><a href="https://github.com/ClickHouse/ClickHouse/actions/runs/7152153310">✅ success</a></td></tr>
<tbody>
</table>
</details>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/57706/0d1bdff3476e2e4406b327ccd7d0bee3bffa8939/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Comment by azat** [comment]
I would say that changelog entry is useful for this change (even though the code is still there), maybe this will force creators to fix all the bugs in LIVE VIEW to make it upstream ready

P.S. I'm using them to monitor changes to system tables with statistics

**Comment by vzakaznikov** [comment]
I might be mistaken, but the last time I've reviewed issues related to Live Views I did not spot anything specific to Live View code.
Live Views are using internal pipeline code so when some type of query is not working the fix has to go into the query pipeline.

**Comment by vzakaznikov** [comment]
As far as the support for this feature in general. Here is a related comment https://github.com/ClickHouse/ClickHouse/pull/39638#issuecomment-1200329331.

**Pull request merged**
