### PR TITLE
Remove duplicate test: `test_concurrent_alter_with_ttl_move`

### PR DESCRIPTION
**Pull request by alesapin**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

We already have it: https://github.com/ClickHouse/ClickHouse/blob/80b681022c1715da0672f8c3da287fffa2335425/tests/integration/test_ttl_move/test.py#L1395

### CODE REVIEW

**Comment by robot-ch-test-poll2** [comment]
This is an automated comment for commit 80b681022c1715da0672f8c3da287fffa2335425 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/53107/80b681022c1715da0672f8c3da287fffa2335425/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alesapin** [comment]
@amosbird `test_jbod_balancer/test.py::test_replicated_balanced_merge_fetch` flaky :(

**Comment by amosbird** [comment]
Hmm, I guess the probability of `test_jbod_balancer/test.py::test_replicated_balanced_merge_fetch` failure is pretty low. Will try to improve it if we see another flaky case.

**Comment by alexey-milovidov** [comment]
We need zero probability of test failure.
We can also remove this test.

**Pull request merged**
