### PR TITLE
Add remove monotonous functions in order by pass

### PR DESCRIPTION
**Pull request by JackyWoo**
### Changelog category (leave one):
- Performance Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Remove monotonous functions in ORDER BY.
```
Example: SELECT number FROM numbers(3) ORDER BY toFloat32(number);
Result: SELECT number FROM numbers(3) ORDER BY number;

Example: SELECT number FROM numbers(3) ORDER BY toFloat32(toFloat64(number));
Result: SELECT number FROM numbers(3) ORDER BY number;
```

Skip if
1. order by nodes participate in GROUP BY expression,
2. order by nodes have more than one arguments
3. order by nodes are aggregate functions
4. order by nodes match the sorting key to allow execute reading in order of key

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by robot-ch-test-poll** [comment]
This is an automated comment for commit d36bbe8f46a10d7ec665e4290cd505b3d3b1c7ba with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/52396/d36bbe8f46a10d7ec665e4290cd505b3d3b1c7ba/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Comment by novikd** [comment]
This optimization should be applied not to the query tree, but to the query plan. Read-in-order and aggregation-in-order optimizations are done on the query plan level and applying this optimization to the query tree may lead to interfering with those optimizations.

**Comment by JackyWoo** [comment]
@novikd Thanks for your advice.

1. For read-in-order
Rewriting is skipped if order by nodes match the sorting keys, details see `01562_optimize_monotonous_functions_in_order_by`
2. For aggregation-in-order
Rewriting is skipped if order by nodes exists in group by.

Please let me know if I miss something.

**Comment by Algunenano** [comment]
I was checking old disabled optimizations and why they are disabled and noticed this PR.

It's introducing the same buggy behaviour that the Interpreter had (and why the setting was disabled):

```
SELECT
    toStartOfHour(c1) AS _c1,
    c2
FROM values((toDateTime('2020-01-01 01:01:01'), 999), (toDateTime('2020-01-01 01:01:59'), 1))
ORDER BY
    _c1 ASC,
    c2 ASC
SETTINGS allow_experimental_analyzer = 1, optimize_monotonous_functions_in_order_by = 1

Query id: 6ac06df0-2364-4074-b08b-be64a80017d2

┌─────────────────_c1─┬──c2─┐
│ 2020-01-01 01:00:00 │ 999 │
│ 2020-01-01 01:00:00 │   1 │
└─────────────────────┴─────┘
```

**Comment by novikd** [comment]
@Algunenano Yes, this optimization can be implemented only as a query plan optimization.

**Comment by JackyWoo** [comment]
@Algunenano @novikd thank you

**Pull request closed without merging**
