### PR TITLE
Better tests for finalize in nested writers

### PR DESCRIPTION
**Pull request by excitoon**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Additional tests for #21305

### CODE REVIEW

**Comment by excitoon** [comment]
This errors shall be fixed after rebase. @azat I agree that some work was done to make `finish()` logic, but I still believe that we shall remove implicit finalization code from destructors (which makes `finish` calls unnecessary), like in #21325. User must call `finalize()` after they write somthing and the reason we introduce implicit finalization was another bug when `finalize()` was missed in compression streams.

**Comment by azat** [comment]
>User must call finalize() after they write somthing and the reason we introduce implicit finalization was another bug when finalize() was missed in compression streams.

Agree, but what will be if someone will forget to call it?

In my opinion it is better to terminate abnormally then silently ignore write failures.

**Comment by excitoon** [comment]
May be some common runtime check which will be turned on in Debug and throw
exception if at moment of destruction there was written some data but not
finalized?

**Comment by excitoon** [comment]
This PR is ready for review, tests are unrelated.

**Review by akuzm — APPROVED** [review]

**Pull request merged**
