### PR TITLE
Implement ColumnAggregateFunction cloneResized method

### PR DESCRIPTION
**Pull request by templarzq**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix issues with RIGHT and FULL JOIN of tables with aggregate function states. In previous versions exception about `cloneResized` method was thrown.

Detailed description / Documentation draft:

 - Implement ColumnAggregateFunction cloneResized method

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
We also need to add a test that will check that this function is used correctly and initial issue is fixed.
See `tests/queries/0_stateless`.

**Comment by templarzq** [comment]
i will create some test cases

**Comment by templarzq** [comment]
create table test_bm(
  dim UInt64,
  id UInt64
)
ENGINE = MergeTree()
ORDER BY ( dim,id )
SETTINGS index_granularity = 8192;

create table test_bm_join(
  dim UInt64,
  id UInt64
)
ENGINE = MergeTree()
ORDER BY ( dim,id )
SETTINGS index_granularity = 8192;

insert into test_bm VALUES (1,1),(2,2),(3,3),(4,4);

select
	dim ,
	sum(idnum)
from
	test_bm_join
right join(
	select
		dim,
		bitmapOrCardinality(ids,ids2) as idnum
	from
		(
			select
				dim,
				groupBitmapState(toUInt64(id)) as ids
			FROM
				test_bm
			where 
			   dim >2
			group by
			   dim 
		) A 
		all right join (
			select
				dim,
				groupBitmapState(toUInt64(id)) as ids2
			FROM
				test_bm
			where 
			   dim < 2	
			group by
				dim 
		) B
		using(dim)
) C
using(dim)
group by dim;

**Comment by templarzq** [comment]
@alexey-milovidov  it seems that there are bugs in CI programs.

**Comment by alexey-milovidov** [comment]
@templarzq They give legitimate warning:
```
2021-01-08 09:23:53 /build/obj-x86_64-linux-gnu/../src/Columns/ColumnAggregateFunction.cpp:676:10: error: invalid case style for local variable 'cloneCol' [readability-identifier-naming,-warnings-as-errors]
2021-01-08 09:23:53     auto cloneCol = cloneEmpty();
2021-01-08 09:23:53          ^~~~~~~~
2021-01-08 09:23:53          clone_col
2021-01-08 09:23:53 /build/obj-x86_64-linux-gnu/../src/Columns/ColumnAggregateFunction.cpp:677:5: error: 'auto res' can be declared as 'auto *res' [readability-qualified-auto,-warnings-as-errors]
2021-01-08 09:23:53     auto res = typeid_cast<ColumnAggregateFunction *>(cloneCol.get());
2021-01-08 09:23:53     ^~~~~
2021-01-08 09:23:53     auto *
2021-01-08 09:23:53 74834 warnings generated.
```
that has to be addressed.

**Comment by templarzq** [comment]
@alexey-milovidov 

2021-01-11 06:17:08 /ClickHouse/programs/client/Client.cpp:768:87: error: use of undeclared identifier 'VERSION_PATCH'
2021-01-11 06:17:08             auto client_version_tuple = std::make_tuple(VERSION_MAJOR, VERSION_MINOR, VERSION_PATCH);
2021-01-11 06:17:08                                                                                       ^
2021-01-11 06:17:08 1 error generated.

**Comment by alexey-milovidov** [comment]
@templarzq Sorry, there was wrong automated commit to master. Could you please merge with upstream again?

**Comment by alexey-milovidov** [comment]
One more...

```
2021-01-11 07:38:14 /build/obj-x86_64-linux-gnu/../src/Columns/ColumnAggregateFunction.cpp:676:22: error: invalid case style for local variable 'cloneCol' [readability-identifier-naming,-warnings-as-errors]
2021-01-11 07:38:14     MutableColumnPtr cloneCol = cloneEmpty();
2021-01-11 07:38:14                      ^~~~~~~~
2021-01-11 07:38:14                      clone_col
```

**Comment by templarzq** [comment]
/run-fuzzer.sh: line 121: ch/docker/test/fuzzer/run-fuzzer.sh: No such file or directory

**Comment by alexey-milovidov** [comment]
The fuzzer was changed in master, so we will ignore its check in this PR.

**Comment by alexey-milovidov** [comment]
@templarzq Looks like you forgot to commit test files...
This is the only small thing remaining before merge.

**Pull request merged**
