### PR TITLE
Added bitmap function feature with roaring bitmap

### PR DESCRIPTION
**Pull request by andyyzh**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Category (leave one):
- New Feature

Short description:
- Added some Bitmap functions with Roaring bitmaps.
- [Roaring bitmaps](https://github.com/RoaringBitmap/CRoaring) are compressed bitmaps which tend to outperform conventional compressed bitmaps such as WAH, EWAH or Concise. 
- Roaring bitmap is wrapped into a data structure while actual storage of Bitmap object. When the cardinality is less than or equal to 32, it uses Set objet. When the cardinality is greater than 32, it uses RoaringBitmap object. That is why storage of low cardinality set is faster. There are 2 kinds of construction methods for Bitmap object. One is to be constructed by aggregation function groupBitmap with -State, the other is to be constructed by Array object. It is also to convert Bitmap object to Array object.

**Main features:**
**1. uniq exactly:**
Calculates the number of different integers of the argument, exactly. Compared with uniqExact function. It is slightly faster in local table mode and 2 times faster in distributed table mode.

**2. Bitmap object Calculation:**
For two Bitmap objects calculation, it is to return new bitmap or cardinality while using formula calculation, such as and, or, xor, and not, etc.

**3. Bitmap and Array Conversion：**
Build Bitmap from Array, or convert Bitmap to Array. There are many functions of Array type in ClickHouse that can be evaluated in a variety of ways.

### CODE REVIEW

**Comment by andyyzh** [comment]
clang-7 build mode: the files I submitted has passed the compiled. An error occurred when linker libprotobuf.a. I don't know the reason. The error was reported as follows:
> /opt/rh/devtoolset-7/root/usr/lib/gcc/x86_64-redhat-linux/7/../../../../include/c++/7/iostream:74: undefined reference to `std::ios_base::Init::~Init()'
> contrib/protobuf/cmake/libprotobuf.a(any.cc.o):(.eh_frame+0x3f): undefined reference to `__gxx_personality_v0'
> clang-7: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by andyyzh** [comment]
Two test cases :
00281_compile_sizeof_packed
00834_cancel_http_readonly_queries_on_client_close
reported errors that seemed unrelated to the code I had submitted,
I need your help, thanks.  @alexey-milovidov 

[00834_cancel_http_readonly_queries_on_client_close_error_log.txt](https://github.com/yandex/ClickHouse/files/2847849/00834_cancel_http_readonly_queries_on_client_close_error_log.txt)
[00281_compile_sizeof_packed_error_log.txt](https://github.com/yandex/ClickHouse/files/2847850/00281_compile_sizeof_packed_error_log.txt)

**Comment by alexey-milovidov** [comment]
> 00834_cancel_http_readonly_queries_on_client_close_error_log.txt

It was poorly written test. Just merge with master and the test will be fixed.

**Comment by andyyzh** [comment]
I seem to done it, Let's take a look at that failed test case. @alexey-milovidov

**Comment by alexey-milovidov** [comment]
Scheduled for the next few days.

**Comment by vnnw** [comment]
Is it possible to support 64bit integer?

**Comment by andyyzh** [comment]
> Is it possible to support 64bit integer?

64-bit integer is not supported for the time being using CRoaring's C language version. 
The 64-bit version of CRoaring c++ has poor performance because it is packaged as an object.

**Comment by yingfeng** [comment]
Could bitmap be used as a filter in the WHERE clause?

**Comment by andyyzh** [comment]
Currently, it can be converted to array to filter.

> DROP TABLE IF EXISTS bitmap_test;
CREATE TABLE bitmap_test(pickup_date Date, city_id UInt32, uid UInt32)ENGINE = Memory;
INSERT INTO bitmap_test SELECT '2019-01-01', 1, number FROM numbers(1,5);
INSERT INTO bitmap_test SELECT '2019-01-02', 2, number FROM numbers(6,6);

> SELECT groupBitmap( uid ) AS user_num FROM bitmap_test group by pickup_date, city_id having groupBitmap( uid ) > 5;

> SELECT groupBitmap( uid ) AS user_num FROM bitmap_test 
group by pickup_date, city_id 
having bitmapToArray(groupBitmapState( uid )) == [1,2,3,4,5];

In the future, it can be filter by functions: bitmapHasAny, bitmapHasAll.
see more:
New bitmap functions: `bitmapHasAny` and `bitmapHasAll` #5279

**Comment by yingfeng** [comment]
Corruption happened if arguments come from scalar subqueries, seen from [issue 5479](https://github.com/yandex/ClickHouse/issues/5479)

**Pull request merged**
