### PR TITLE
Implement nested renames

### PR DESCRIPTION
**Pull request by AlexeyLebedev1**
### Changelog category (leave one):
- New Feature

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Support rename for nested columns to not nested and vice versa

### Documentation entry for user-facing changes

- [x] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Run only fuzzers related jobs (libFuzzer fuzzers, AST fuzzers, etc.)
- [ ]  Exclude: AST fuzzers
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by AlexeyLebedev1** [comment]
#68992

**Comment by AlexeyLebedev1** [comment]
#68727

**Comment by robot-ch-test-poll1** [comment]
*This is an automated comment for commit 25db7623fba1436a23e5bdde25e0efca5f2c66af with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/68992/25db7623fba1436a23e5bdde25e0efca5f2c66af/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Style check</td><td>Runs a set of checks to keep the code style clean. If some of tests failed, see the related log from the report</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/68992/25db7623fba1436a23e5bdde25e0efca5f2c66af/style_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Comment by Avogar** [comment]
We should not allow renaming normal column to nested element:

```sql
avogar-dev :) create table test (x Array(UInt32), n Nested(y UInt32)) engine=MergeTree order by tuple()

CREATE TABLE test
(
    `x` Array(UInt32),
    `n` Nested(y UInt32)
)
ENGINE = MergeTree
ORDER BY tuple()

Query id: e2a78385-2d88-4a3f-8856-6cc786445b4f

Ok.

0 rows in set. Elapsed: 0.004 sec.

avogar-dev :) insert into test select range(number % 3), range(number % 10) from numbers(100)

INSERT INTO test SELECT
    range(number % 3),
    range(number % 10)
FROM numbers(100)

Query id: 5018579f-c3e0-4bc9-bcf5-322cd518c97b

Ok.

0 rows in set. Elapsed: 0.007 sec.

avogar-dev :) alter table test rename column x to `n.x`

ALTER TABLE test
    (RENAME COLUMN x TO `n.x`)

Query id: 8fb1e16a-348e-437c-a4a1-fa0f8d9bfc48

Ok.

0 rows in set. Elapsed: 0.011 sec.

avogar-dev :) select * from test

SELECT *
FROM test

Query id: 8e175ff0-8d4d-4315-9b0f-9db0eb4e005d

[avogar-dev] 2024.08.28 10:57:28.418312 [ 3938671 ] {8e175ff0-8d4d-4315-9b0f-9db0eb4e005d} <Fatal> : Logical error: 'Found non-equal columns with offsets (sizes: 100 and 100) for stream n.size0'.

```

**Comment by Avogar** [comment]
And vise versa from nested element to normal column:
```
avogar-dev :) create table test (n Nested(x UInt32, y UInt32)) engine=MergeTree order by tuple()

CREATE TABLE test
(
    `n` Nested(x UInt32, y UInt32)
)
ENGINE = MergeTree
ORDER BY tuple()

Query id: b401f255-7ed5-45ad-813f-5fa70cccb40e

Ok.

0 rows in set. Elapsed: 0.004 sec.

avogar-dev :) insert into test select range(number % 10), range(number % 10) from numbers(1000000)

INSERT INTO test SELECT
    range(number % 10),
    range(number % 10)
FROM numbers(1000000)

Query id: 1995111e-c8e1-4d5d-9346-66f2c88fa10f

Ok.

0 rows in set. Elapsed: 0.123 sec. Processed 1.00 million rows, 8.00 MB (8.12 million rows/s., 64.93 MB/s.)
Peak memory usage: 93.44 MiB.

avogar-dev :) alter table test rename column `n.x` to `d`

ALTER TABLE test
    (RENAME COLUMN `n.x` TO d)

Query id: f34992d1-7482-45fa-8e2d-059d2a35b565

Ok.

0 rows in set. Elapsed: 0.009 sec.

avogar-dev :) select d.size0 from test

SELECT d.size0
FROM test

Query id: e5f29932-8377-4326-950c-25a7a47edde2

[avogar-dev] 2024.08.28 11:12:26.969609 [ 3954079 ] {e5f29932-8377-4326-950c-25a7a47edde2} <Fatal> : Logical error: 'Can't adjust last granule because it has 8065 rows, but try to subtract 65409 rows.'.
```

So I am afraid we can only allow renaming columns inside nested structure like `n.<column_name1> -> n.<column_name2>`

**Comment by pamarcos** [comment]
As I understand the original issue and according to @Avogar's comments we still want to implement https://github.com/ClickHouse/ClickHouse/issues/68727, but not for nested elements. Is that correct, @nikitamikhaylov?

**Comment by nikitamikhaylov** [comment]
@pamarcos Yes, exactly. We treat a column with a dot in the name as Nested and that's incorrect. The problem is in the logic which determines it.

**Comment by StashOfCode** [comment]
Any news on this feature?

**Pull request closed without merging**
