### PR TITLE
Allow float string parsed as int, like in MySQL or Spark

### PR DESCRIPTION
**Pull request by taiyang-li**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Allow float string parsed as int, like in MySQL or Spark

In CH
``` sql
select cast('1.8' as Int32)

Code: 6. DB::Exception: Cannot parse string '1.8' as Int32: syntax error at position 1 (parsed just '1'). Note: there are toInt32OrZero and toInt32OrNull functions, which returns zero/NULL instead of throwing exception.: While processing CAST('1.8', 'Int32'). (CANNOT_PARSE_TEXT) (version 23.8.1.2891 (official build))
```

In Spark
``` sql 
0: jdbc:hive2://localhost:10000/> select cast('1.8' as int); 
+-------------------+
| CAST(1.8 AS INT)  |
+-------------------+
| 1                 |
+-------------------+

```

In MySQL
```
mysql> select CAST('1.8' AS UNSIGNED)
    -> ; 
+-------------------------+
| CAST('1.8' AS UNSIGNED) |
+-------------------------+
|                       1 |
+-------------------------+
1 row in set, 1 warning (0.00 sec)

```

### CODE REVIEW

**Comment by robot-clickhouse-ci-2** [comment]
This is an automated comment for commit 2b521680e1b70841f423ff351815e9b612092245 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/54530/2b521680e1b70841f423ff351815e9b612092245/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Comment by taiyang-li** [comment]
https://pipelinesghubeus22.actions.githubusercontent.com/IxlUib3Pq0MWfDRC1Sbu96YxjLYW6mfeG66ckb7519NERLfDQ1/_apis/pipelines/1/runs/349451/signedlogcontent/52?urlExpires=2023-09-12T06%3A12%3A57.5173730Z&urlSigningMethod=HMACV1&urlSignature=ju0Faeyo%2F9PfN7Cu2ROoEjsdCj%2FctiZqQwcc8svOuMU%3D

I have no idea which fast test was failed from this log, it seems different from before.

**Comment by alexey-milovidov** [comment]
It's failed due to changed behavior. Let's add a setting to control this change.

**Comment by taiyang-li** [comment]
> It's failed due to changed behavior. Let's add a setting to control this change.

Introducing a settings needs to modify almost all classes in src/Functions/FunctionsConversion.h. Do you think it is worthy?

**Comment by alexey-milovidov** [comment]
It could make sense.

**Comment by alexey-milovidov** [comment]
A test needed.

**Comment by taiyang-li** [comment]
> It could make sense.

Do you mean we still need introducing a setting to decide whether to throw exception if cast float string to int ?

**Pull request closed without merging**
