### PR TITLE
Experiment on parsing backslash escapes in a more convenient way #10922

### LINKED ISSUE #10922: RFC: excessive escaping in regexps and like
In ClickHouse you need to double escape special characters in regexp and like (for example, underscores in `like` need to be escaped with two backslashes).

The reasons for the behavior are clear (parser extract the regexp / right part of `like` as a regular literal with general rules for escaping, and then `like` function takes the string from AST and uses it's own logic).

But this is inconvenient /  for the user:
1) this is a deviation from the standard (in the case of like)
2) all sorts of complex regexps (which are quite noisy in general) in ClickHouse look more noisy because of double escaping. 

Therefore, the question is - do we want to change this?

It seems to be fundamentally feasible - when parsing, you can simply add the literal in the AST in the original representation and use other deescaping rules for the `like` / `regexp` functions.

But there are also side effects (backward compatibility, "specialization" of parsers / desapaping).

what do you think of this? Do we want to change that? If so, then soon / not soon / "maybe someday." Or leave it as it is?

The second column here is problematic:
```
select 'aXb' like 'a_b', 'aXb' like 'a\_b', 'a_b' like 'a\_b', 'a_b' like 'a\\_b';

Mysql:      1 0 1 1
Postgres:   1 0 1 0
ClickHouse  1 1 1 1
SQLite:     1 0 0 0
```

Alexey Milovidov, [11.05.20 18:57]
In PHP, they did that in string literals, `\{` is parsed not like `{` but like `\{`, and therefore in functions like `preg_replace` you can write only one slash, not two. In earlier versions of MySQL in `LIKE` it was necessary to write two slashes, such as: LIKE 'hello \\ _ world', and then they fixed it similarly to PHP. It is not obvious whether we need to do this.

Such a  strange logic:
https://www.db-fiddle.com/f/kCLJ917M6RFS4XoY4bDnyh/0

Note that by standard, string literals do not support C-style escaping (using backslashes), this is a feature of MySQL.

We can make parsing as in PHP + customization to completely turn off C-style escapes to comply with the standard.

### PR DESCRIPTION
**Pull request by alexey-milovidov**
Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
When parsing C-style backslash escapes in string literals, VALUES and various text formats (this is an extension to SQL standard that is endemic for ClickHouse and MySQL), keep backslash if unknown escape sequence is found (e.g. `\%` or `\w`) that will make usage of `LIKE` and `match` regular expressions more convenient (it's enough to write `name LIKE 'used\_cars'` instead of `name LIKE 'used\\_cars'`) and more compatible at the same time. This fixes #10922

Detailed description / Documentation draft:
Check if it will hurt.

### CODE REVIEW

**Comment by qoega** [comment]
```
2020-05-27 02:26:08 00342_escape_sequences:                                                 [ FAIL ] 0.05 sec. - result differs with reference:
2020-05-27 02:26:08 --- /usr/share/clickhouse-test/queries/0_stateless/00342_escape_sequences.reference	2020-05-27 00:54:57.000000000 +0300
2020-05-27 02:26:08 +++ /tmp/clickhouse-test/0_stateless/00342_escape_sequences.stdout	2020-05-27 02:26:08.791063626 +0300
2020-05-27 02:26:08 @@ -1 +1 @@
2020-05-27 02:26:08 -07080C0A0D090B5C27223FAA
2020-05-27 02:26:08 +07080C0A0D090B5C27225C3FAA
2020-05-27 02:26:08

2020-05-27 02:17:25 00926_multimatch:                                                       [ FAIL ] 0.30 sec. - result differs with reference:
2020-05-27 02:17:25 --- /usr/share/clickhouse-test/queries/0_stateless/00926_multimatch.reference	2020-05-27 00:54:57.000000000 +0300
2020-05-27 02:17:25 +++ /tmp/clickhouse-test/0_stateless/00926_multimatch.stdout	2020-05-27 02:17:25.051340777 +0300
2020-05-27 02:17:25 @@ -620,6 +620,6 @@
2020-05-27 02:17:25  1
2020-05-27 02:17:25  All tests above must return 1, all tests below return something.
2020-05-27 02:17:25  []
2020-05-27 02:17:25 -[1,3]
2020-05-27 02:17:25 +[1]
2020-05-27 02:17:25  []
2020-05-27 02:17:25 -[1,2,3]
2020-05-27 02:17:25 +[1,2]
2020-05-27 02:17:25 

2020-05-27 02:08:12 01075_allowed_client_hosts:                                             [ FAIL ] 0.09 sec. - result differs with reference:
2020-05-27 02:08:12 --- /usr/share/clickhouse-test/queries/0_stateless/01075_allowed_client_hosts.reference	2020-05-27 00:54:57.000000000 +0300
2020-05-27 02:08:12 +++ /tmp/clickhouse-test/0_stateless/01075_allowed_client_hosts.stdout	2020-05-27 02:08:12.794290839 +0300
2020-05-27 02:08:12 @@ -8,10 +8,10 @@
2020-05-27 02:08:12  CREATE USER test_user_01075 HOST LOCAL
2020-05-27 02:08:12  CREATE USER test_user_01075 HOST NONE
2020-05-27 02:08:12  CREATE USER test_user_01075 HOST LIKE \'@.somesite.com\'
2020-05-27 02:08:12 -CREATE USER test_user_01075 HOST REGEXP \'.*.anothersite.com\'
2020-05-27 02:08:12 -CREATE USER test_user_01075 HOST REGEXP \'.*.anothersite.com\', \'.*.anothersite.org\'
2020-05-27 02:08:12 -CREATE USER test_user_01075 HOST REGEXP \'.*.anothersite2.com\', \'.*.anothersite2.org\'
2020-05-27 02:08:12 -CREATE USER test_user_01075 HOST REGEXP \'.*.anothersite3.com\', \'.*.anothersite3.org\'
2020-05-27 02:08:12 +CREATE USER test_user_01075 HOST REGEXP \'.*\\\\.anothersite\\\\.com\'
2020-05-27 02:08:12 +CREATE USER test_user_01075 HOST REGEXP \'.*\\\\.anothersite\\\\.com\', \'.*\\\\.anothersite\\\\.org\'
2020-05-27 02:08:12 +CREATE USER test_user_01075 HOST REGEXP \'.*\\\\.anothersite2\\\\.com\', \'.*\\\\.anothersite2\\\\.org\'
2020-05-27 02:08:12 +CREATE USER test_user_01075 HOST REGEXP \'.*\\\\.anothersite3\\\\.com\', \'.*\\\\.anothersite3\\\\.org\'
2020-05-27 02:08:12  CREATE USER `test_user_01075_x@localhost` HOST LOCAL
2020-05-27 02:08:12  CREATE USER test_user_01075_x
2020-05-27 02:08:12  CREATE USER `test_user_01075_x@192.168.23.15` HOST LIKE \'192.168.23.15\'
2020-05-27 02:08:12 
```

**Comment by alexey-milovidov** [comment]
> 00342_escape_sequences

New result is correct now.

> 00926_multimatch

The test had mistake.

> 01075_allowed_client_hosts

The test had mistake.

**Comment by alexey-milovidov** [comment]
> Stress test (thread) — Sanitizer assert (in stderr.log) 

Already fixed by @KochetovNicolai 

> Performance Pending — Started 

Sandbox quota overload, but I cannot wait.

**Comment by alexey-milovidov** [comment]
Performance test did not finish.

**Pull request merged**
