### PR TITLE
Allow geoHashEncode when its arguments are mixed with const and non-const columns

### PR DESCRIPTION
**Pull request by taiyang-li**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix two issues:
```
select geohashEncode(120.2, number::Float64) from numbers(10);

Code: 44. DB::Exception: Unsupported argument types: Const(Float64), Float64 for function geohashEncode. (ILLEGAL_COLUMN) (version 23.5.1.291 (official build))
```

```
select geohashEncode(120.2, 47.6, number) from numbers(10);

Code: 44. DB::Exception: Argument at index 2 for function geohashEncode must be constant. (ILLEGAL_COLUMN) (version 23.5.1.291 (official build))
```

### CODE REVIEW

**Comment by robot-clickhouse-ci-1** [comment]
This is an automated comment for commit 056e5824b57a78314b7ae565585ef0afea1bd836 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/50066/056e5824b57a78314b7ae565585ef0afea1bd836/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Comment by hanfei1991** [comment]
I think the requirement constant arg of precision is on purpose, regarding performance and user interface.
If we want vector arg of precision, we should implement a function like `vector_vector`, but I wonder if it is worthy.

**Comment by KochetovNicolai** [comment]
@hanfei1991 yes, I think that precision is expected to be constant.

**Comment by taiyang-li** [comment]
> @hanfei1991 yes, I think that precision is expected to be constant. If we want to allow non-constant precision, we will likely need 2 separate implementations for constant and for vector.

Actually, we need to implement those combinations: 
- first column is const, others not
- second column is const, others not
- third columns is const, others not
- first and second is const, others not
- first and third is is const, others not
- second and third is const, others not

It is a trade-off between the possible performance bonus and the boring work of implementations of each combinations.

**Comment by taiyang-li** [comment]
Query: `select geohashEncode(materialize(120.123), materialize(100.456), 7) from numbers(10000000) format Null;`

Before changes: 
```
0 rows in set. Elapsed: 19.577 sec. Processed 10.01 million rows, 80.06 MB (511.19 thousand rows/s., 4.09 MB/s.)
0 rows in set. Elapsed: 20.041 sec. Processed 10.01 million rows, 80.06 MB (499.35 thousand rows/s., 3.99 MB/s.)
```


After changes: 
```
0 rows in set. Elapsed: 20.203 sec. Processed 10.01 million rows, 80.06 MB (495.35 thousand rows/s., 3.96 MB/s.)
0 rows in set. Elapsed: 20.078 sec. Processed 10.01 million rows, 80.06 MB (498.43 thousand rows/s., 3.99 MB/s.)
```

**Comment by taiyang-li** [comment]
Do we have any progress on this PR? I'd like to hear your opinions @hanfei1991  @KochetovNicolai

**Comment by taiyang-li** [comment]
@alexey-milovidov do you have time to review this pr, thanks! I still think it is not reasonable to force some arguments of one funtion to be constant, and forbidden other arguments to be non-constant. It is not friendly for CH users.

**Comment by taiyang-li** [comment]
Okay! It seems that you guys don't care about this improvement, this makes me frustrated. Anyway, it will used internally by ourselves.

**Comment by alexey-milovidov** [comment]
Why closing?

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
This implementation is good to me.
Geohash is slow enough (mainly due to base64 encoding into a variable-length string); that's why virtual calls to getFloat don't matter.

**Pull request merged**
