### PR TITLE
Fix test 02944_variant_as_common_type

### PR DESCRIPTION
**Pull request by alexon1234**
### Changelog category (leave one):
- CI Fix or Improvement (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

The test `02944_variant_as_common_type` is suppose to run with the old analyzer. As the new analyzer is the default. The tests are failing

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Run only fuzzers related jobs (libFuzzer fuzzers, AST fuzzers, etc.)
- [ ]  Exclude: AST fuzzers
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by alexon1234** [comment]
Running `PATH=./build/programs/clickhouse-client:$PATH tests/clickhouse-test 02944_variant_as_common_type_analyzer` from master I get the following error from time to time

```
02944_variant_as_common_type_analyzer:                                  [ FAIL ]
Reason: return code:  27
Received exception from server (version 24.9.1):
Code: 27. DB::Exception: Received from localhost:9000. DB::Exception: Cannot parse input: expected 'eof' before: '\'auto(12)\''. (CANNOT_PARSE_INPUT_ASSERTION_FAILED)
(query: -- this test is just like 02944_variant_as_common_type, but with different expected output, because
-- analyzer changes some return types. Specifically, if(c, x, y) always casts to the common type of
-- x and y, even if c is constant.
set enable_analyzer=1;)
, result:
```

**Comment by robot-ch-test-poll4** [comment]
*This is an automated comment for commit 4a60b4ad866752f3b416cf43436c3421086d8199 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/69088/4a60b4ad866752f3b416cf43436c3421086d8199/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Builds</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/8fbfc61c55923ebab9704fe4194a743676b6aa6b/builds/report.html">✅ success</a></td></tr>
<tr><td>ClickBench</td><td>Runs [ClickBench](https://github.com/ClickHouse/ClickBench/) with instant-attach table</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/8fbfc61c55923ebab9704fe4194a743676b6aa6b/clickbench__aarch64_.html">✅ success</a></td></tr>
<tr><td>Compatibility check</td><td>Checks that <b>clickhouse</b> binary runs on distributions with old libc versions. If it fails, ask a maintainer for help</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/8fbfc61c55923ebab9704fe4194a743676b6aa6b/compatibility_check__aarch64_.html">✅ success</a></td></tr>
<tr><td>Docker keeper image</td><td>The check to build and optionally push the mentioned image to docker hub</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/8fbfc61c55923ebab9704fe4194a743676b6aa6b/docker_keeper_image.html">✅ success</a></td></tr>
<tr><td>Docker server image</td><td>The check to build and optionally push the mentioned image to docker hub</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/8fbfc61c55923ebab9704fe4194a743676b6aa6b/docker_server_image.html">✅ success</a></td></tr>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td>✅ success</td></tr>
<tr><td>Install packages</td><td>Checks that the built packages are installable in a clear environment</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/8fbfc61c55923ebab9704fe4194a743676b6aa6b/install_packages__aarch64_.html">✅ success</a></td></tr>
<tr><td>Integration tests</td><td>The integration tests report. In parenthesis the package type is given, and in square brackets are the optional part/total tests</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/8fbfc61c55923ebab9704fe4194a743676b6aa6b/integration_tests__aarch64__[1_6].html">✅ success</a></td></tr>
<tr><td>Performance Comparison</td><td>Measure changes in query performance. The performance test report is described in detail <a href="https://github.com/ClickHouse/ClickHouse/tree/master/docker/test/performance-comparison#how-to-read-the-report">here</a>. In square brackets are the optional part/total tests</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/8fbfc61c55923ebab9704fe4194a743676b6aa6b/performance_comparison__release__[1_4]/report.html">✅ success</a></td></tr>
<tr><td>Stateful tests</td><td>Runs stateful functional tests for ClickHouse binaries built in various configurations -- release, debug, with sanitizers, etc</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/8fbfc61c55923ebab9704fe4194a743676b6aa6b/stateful_tests__aarch64_.html">✅ success</a></td></tr>
<tr><td>Unit tests</td><td>Runs the unit tests for different release types</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/8fbfc61c55923ebab9704fe4194a743676b6aa6b/unit_tests__asan_.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Comment by alexon1234** [comment]
> The test `02944_variant_as_common_type` is expected to fail with new analyzer, we have this test in the list of tech debt tests for new analyzer: https://github.com/ClickHouse/ClickHouse/blob/master/tests/analyzer_tech_debt.txt
> 
> It will be fixed after the refactoring of the constants in the analyzer. It should not affect CI anyhow, we still run this test with old analyzer and skip this test with new one. It's not supposed to check behaviour of old analyzer.

I was trying to force the test to pass to avoid noise in the CI pipeline. If you are actively working on it, then I will close the PR. Thanks for taking a look

**Comment by Avogar** [comment]
>  noise in the CI pipeline

The only noise this test can make is to be marked as `BROKEN` in the tests output, but it doesn't affect the status of the tests, if all other tests are ok, the status of the whole tests run will be green

**Comment by alexon1234** [comment]
> > noise in the CI pipeline
> 
> The only noise this test can make is to be marked as `BROKEN` in the tests output, but it doesn't affect the status of the tests, if all other tests are ok, the status of the whole tests run will be green

Thanks for the explanation

**Pull request closed without merging**
