### PR TITLE
Add timezone to 02458_datediff_date32

### PR DESCRIPTION
**Pull request by vdimir**
### Changelog category (leave one):

- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

[flaky](https://play.clickhouse.com/play?user=play#ICAgIFNFTEVDVAogICAgICAgIHJlcG9ydF91cmwsCiAgICAgICAgc3Vic3RyaW5nKGNoZWNrX25hbWUsIDEsIDE1KSB8fCAnLi4uJyB8fCBzdWJzdHJpbmcoY2hlY2tfbmFtZSwgLTE1KSBhcyBjaGVjaywKICAgICAgICBzdWJzdHJpbmcodGVzdF9uYW1lLCAtNTApIGFzIHRlc3QsCiAgICAgICAgY2hlY2tfc3RhcnRfdGltZSwKICAgICAgICB0ZXN0X3N0YXR1cywKICAgICAgICBzdWJzdHJpbmcoY29tbWl0X3NoYSwgMSwgMTApIGFzIGNvbW1pdF9zaG9ydCwKICAgICAgICBwdWxsX3JlcXVlc3RfbnVtYmVyIGFzIHBybnVtCiAgICBGUk9NIGNoZWNrcwogICAgV0hFUkUgdGVzdF9zdGF0dXMgbm90IGluICgnT0snLCAnU0tJUFBFRCcpCiAgICAgICAgQU5EIHRlc3RfbmFtZSBsaWtlICclMDI0NThfZGF0ZWRpZmZfZGF0ZTMyJScKICAgICAgICBBTkQgbm93KCkgLSBJTlRFUlZBTCAnNycgZGF5IDw9IGNoZWNrX3N0YXJ0X3RpbWUKICAgICAgICAKICAgIE9SREVSIEJZCiAgICAgICAgCiAgICAgICAgY2hlY2tfc3RhcnRfdGltZSBERVNDCiAgICBMSU1JVCAyMA==) in some timezones

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Review by CheSema — APPROVED** [review]
LGTM

**Comment by rschu1ze** [comment]
@rvasin Just FYI since you did #42611 before ... 1927 was less flaky than 1900 but not 100% stable.

**Comment by rvasin** [comment]
@rschu1ze I remember that I was initially added 'UTC' for toDate32 and for toDateTime64 for the test. But I am not sure that it will help. Did you run the tests for all time zones?  

Right now I am working on similar related issues #42653 and #42615. And I may need some advice from CH community after I finish my research on the subject.

**Comment by rschu1ze** [comment]
Afaik, time zones in CI are randomized. So the best approach is to specify them explicitly.

Sure, just ask in case of questions with both issues.

**Pull request merged**
