### PR TITLE
Refactoring of data types serialization

### PR DESCRIPTION
**Pull request by CurtizJ**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Refactoring of data types serialization. It allows to choose different serializations for single type dynamically.
Part of #19953.

### CODE REVIEW

**Comment by CurtizJ** [comment]
However, now only default serialization is available (besides serialization of subcolumns) and not full interface of getting serializations is implemented in this PR, since it's worthless now. But it will look like this:

```c++
SerializationPtr IDataType::getSerialization(const String & column_name, const SerializationInfo & info) const
{
    ISerialization::Settings settings =
    {
        .num_rows = info.getNumberOfRows(),
        .num_non_default_rows = info.getNumberOfNonDefaultValues(column_name),
        .min_ratio_for_dense_serialization = 10
    };

    return getSerialization(settings);
}

SerializationPtr IDataType::getSerialization(const IColumn & column) const
{
    ISerialization::Settings settings =
    {
        .num_rows = column.size(),
        .num_non_default_rows = column.getNumberOfNonDefaultValues(),
        .min_ratio_for_dense_serialization = 10
    };

    return getSerialization(settings);
}

SerializationPtr IDataType::getSerialization(const ISerialization::Settings & settings) const
{
    if (settings.num_non_default_rows * settings.min_ratio_for_dense_serialization < settings.num_rows)
         return getSparseSerialization();

    return getDefaultSerialization();
}

// static
SerializationPtr IDataType::getSerialization(const NameAndTypePair & column, const IDataType::StreamExistenceCallback & callback)
{
    if (column.isSubcolumn())
    {
        auto base_serialization_getter = [&](const IDataType & subcolumn_type)
        {
            return subcolumn_type.getSerialization(column.name, callback);
        };

        auto type_in_storage = column.getTypeInStorage();
        return type_in_storage->getSubcolumnSerialization(column.getSubcolumnName(), base_serialization_getter);
    }

    return column.type->getSerialization(column.name, callback);
}

SerializationPtr IDataType::getSerialization(const String & column_name, const StreamExistenceCallback & callback) const
{
    auto sparse_idx_name = escapeForFileName(column_name) + ".sparse.idx";
    if (callback(sparse_idx_name))
        return getSparseSerialization();

    return getDefaultSerialization();
}
```

There are two new entities: `SerializationInfo` and `SerializationSettings`. The first one will contain any useful information about content of columns. It will be stored in data parts. The second one can be created for one column  from `SerializationInfo` or from the column itself.

**Comment by CurtizJ** [comment]
This PR has a huge diff, but mostly it's just moving serializations to separate files. However, git history for most serializations (largest part of code of data types) is kept, because there was a move beetween files. But github is unable to show it properly in the interface.

Example of blame:
image

**Review by alesapin — APPROVED** [review]
Of course, I haven't fully read this PR, but the idea is clear and these changes have been asking for a long time. 

Maybe it would be better if we use CRTP for data types. In this case, we can save the pointer to `ISerialization` into the child object (in constructor) and return it from some method in `IDataType` using something like this `static_cast<Child>(this)->getSerializationPointer()`. It will allow us to avoid creating shared pointers to `ISerialization` each time or save them in the user code and manually control consistency between type and serialization (example in `MergeTreeDataWriterWide/OnDisk`). But this is just a suggestion, the current implementation is also Ok and because of size, we should merge this PR as fast as possible.

**Comment by CurtizJ** [comment]
@alesapin
Maybe merge this PR now and implement CRTP for data types later? However, it will not avoid of saving precomputied pointers to serializations in some cases, when dynamic serializations will be ready, because they anyway will give overhead for choosing serialization and creating a new object.

**Comment by CurtizJ** [comment]
Failed tests are the same as in master.

**Comment by alexey-milovidov** [comment]
Finally we have fixed performance regression from #3669 :tada: 

```
milovidov@milovidov-desktop:~/work/ClickHouse$ for i in {1..30}; do time programs/server/clickhouse-21.3.3 local --structure "x UInt64, y UInt64, z UInt64" --query "SELECT count() FROM table" < numbers100m.tsv; done 
100000000

real    0m1,722s
user    0m9,468s
sys     0m0,563s
100000000

real    0m1,653s
user    0m9,302s
sys     0m0,521s
100000000

real    0m1,675s
user    0m9,420s
sys     0m0,490s
100000000

real    0m1,664s
user    0m9,454s
sys     0m0,502s
100000000

real    0m1,690s
user    0m9,412s
sys     0m0,633s
100000000

real    0m1,660s
user    0m9,392s
sys     0m0,507s
100000000

real    0m1,668s
user    0m9,374s
sys     0m0,485s
100000000

real    0m1,685s
user    0m9,371s
sys     0m0,540s
100000000

real    0m1,657s
user    0m9,369s
sys     0m0,530s
100000000

real    0m1,663s
user    0m9,378s
sys     0m0,553s
100000000

real    0m1,675s
user    0m9,366s
sys     0m0,561s
100000000

real    0m1,654s
user    0m9,472s
sys     0m0,445s
100000000

real    0m1,649s
user    0m9,486s
sys     0m0,396s
100000000

real    0m1,659s
user    0m9,315s
sys     0m0,559s
100000000

real    0m1,659s
user    0m9,272s
sys     0m0,584s
100000000

real    0m1,662s
user    0m9,295s
sys     0m0,536s
100000000

real    0m1,661s
user    0m9,394s
sys     0m0,525s
100000000

real    0m1,658s
user    0m9,362s
sys     0m0,542s
100000000

real    0m1,649s
user    0m9,479s
sys     0m0,389s
100000000

real    0m1,679s
user    0m9,405s
sys     0m0,594s
100000000

real    0m1,664s
user    0m9,410s
sys     0m0,503s
100000000

real    0m1,649s
user    0m9,526s
sys     0m0,365s
100000000

real    0m1,680s
user    0m9,291s
sys     0m0,649s
100000000

real    0m1,667s
user    0m9,450s
sys     0m0,477s
100000000

real    0m1,689s
user    0m9,421s
sys     0m0,565s
100000000

real    0m1,664s
user    0m9,295s
sys     0m0,608s
100000000

real    0m1,662s
user    0m9,298s
sys     0m0,566s
100000000

real    0m1,657s
user    0m9,533s
sys     0m0,386s
100000000

real    0m1,678s
user    0m9,353s
sys     0m0,575s
100000000

real    0m1,689s
user    0m9,291s
sys     0m0,563s
milovidov@milovidov-desktop:~/work/ClickHouse$ for i in {1..30}; do time clickhouse-local --structure "x UInt64, y UInt64, z UInt64" --query "SELECT count() FROM table" < numbers100m.tsv; done                       
100000000

real    0m1,574s
user    0m9,738s
sys     0m0,425s
100000000

real    0m1,554s
user    0m9,868s
sys     0m0,386s
100000000

real    0m1,557s
user    0m9,624s
sys     0m0,479s
100000000

real    0m1,544s
user    0m9,854s
sys     0m0,401s
100000000

real    0m1,551s
user    0m9,658s
sys     0m0,453s
100000000

real    0m1,549s
user    0m9,797s
sys     0m0,341s
100000000

real    0m1,548s
user    0m9,762s
sys     0m0,378s
100000000

real    0m1,560s
user    0m9,654s
sys     0m0,469s
100000000

real    0m1,552s
user    0m9,712s
sys     0m0,478s
100000000

real    0m1,552s
user    0m9,682s
sys     0m0,459s
100000000

real    0m1,551s
user    0m9,592s
sys     0m0,476s
100000000

real    0m1,567s
user    0m9,892s
sys     0m0,384s
100000000

real    0m1,548s
user    0m9,713s
sys     0m0,379s
100000000

real    0m1,554s
user    0m9,788s
sys     0m0,420s
100000000

real    0m1,546s
user    0m9,779s
sys     0m0,366s
100000000

real    0m1,562s
user    0m9,856s
sys     0m0,407s
100000000

real    0m1,581s
user    0m9,796s
sys     0m0,476s
100000000

real    0m1,544s
user    0m9,664s
sys     0m0,458s
100000000

real    0m1,549s
user    0m9,764s
sys     0m0,331s
100000000

real    0m1,552s
user    0m9,925s
sys     0m0,415s
100000000

real    0m1,552s
user    0m9,936s
sys     0m0,361s
100000000

real    0m1,555s
user    0m9,832s
sys     0m0,445s
100000000

real    0m1,549s
user    0m9,865s
sys     0m0,395s
100000000

real    0m1,570s
user    0m9,750s
sys     0m0,412s
100000000

real    0m1,552s
user    0m9,734s
sys     0m0,403s
100000000

real    0m1,550s
user    0m9,777s
sys     0m0,384s
100000000

real    0m1,551s
user    0m9,809s
sys     0m0,387s
100000000

real    0m1,545s
user    0m9,847s
sys     0m0,325s
100000000

real    0m1,561s
user    0m9,748s
sys     0m0,459s
100000000

real    0m1,562s
user    0m9,956s
sys     0m0,438s
```

**Pull request merged**
