### PR TITLE
feat(...): [LWD] support getting _part_offset of a row

### PR DESCRIPTION
**Pull request by weeds085490**
Changelog category (leave one):
- New Feature

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
According to the design mentioned at ：https://github.com/ClickHouse/ClickHouse/issues/19627#issuecomment-1068772646

[ Light weight delete] support getting _part_offset of a row.

> Information about CI checks: https://clickhouse.tech/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by WillMeng** [comment]
That's great! Thanks very much.
I have another question, how to do about partial column update？

**Comment by weeds085490** [comment]
Hi @alexey-milovidov,  PTAL

**Comment by davenger** [comment]
I found a bug when _part_offset column was queried along with other virtual columns. So I added more tests and made fixes to make sure that the reader returns columns in the correct order. I also refactored the code a bit to pass the list of non-constant virtual columns instead of 'add_part_offset' flag.

**Comment by davenger** [comment]
@mergifyio update

**Review by KochetovNicolai — APPROVED** [review]

**Comment by davenger** [comment]
@weeds085490 With this PR merged do you plan to do further PR's for LWD?

**Comment by weeds085490** [comment]
> 



> @weeds085490 With this PR merged do you plan to do further PR's for LWD?
Sorry for late reply.  We will gradually merge all the code back over the next one or two months.

**Pull request merged**
