### PR TITLE
Adding documentation on how to use LDAP server as external user authenticator or directory

### PR DESCRIPTION
**Pull request by vzakaznikov**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Documentation (changelog entry is not required)

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Adding documentation on how to use LDAP server as external user authenticator or directory

Detailed description / Documentation draft:
Adding documentation on how to use LDAP server as external user authenticator or directory

### CODE REVIEW

**Comment by vzakaznikov** [comment]
@traceon, could you please review the docs from your side?

**Comment by traceon** [comment]
If it is not urgent, let's merge this after #14995 is merged. It will introduce some syntactic changes.

**Comment by vzakaznikov** [comment]
> If it is not urgent, let's merge this after #14995 is merged. It will introduce some syntactic changes.

As discussed, let's decouple this from Kerberos and push the docs that match the current syntax even if it will change soon.

**Comment by vzakaznikov** [comment]
This PR is ready for review.

**Comment by hodgesrm** [comment]
Hi! Can we get some review on this one? We have a blog article pending and want to be able to point to the [great!] community docs.

**Review by alexey-milovidov — APPROVED** [review]
Perfect.

After reading the docs I'm finally fully aware of the all capabilities of LDAP integration.

**Comment by traceon** [comment]
@alexey-milovidov Well, that never was a secret. :)

Here is the documentation draft, that (always) reflects the current (potentially unmerged yet) functionality around LDAP and Kerberos: [External authentication mechanism support in ClickHouse ](https://gist.github.com/traceon/d922c8452e8065b86667168578dc5c12)

**Pull request merged**
