### PR TITLE
[WIP] tcmalloc allocator (new C++ version by google)

### PR DESCRIPTION
**Pull request by azat**
### `tcmalloc` performance checklist:

- [ ] extract allocations pattern from the perf tests and write new size class for it

### pre-upstream checklist:

<details>

- [ ] loaded too late ([`../contrib/tcmalloc-cpp/tcmalloc/tcmalloc.cc:2270] tcmalloc::GetOwnership(ptr) != tcmalloc::MallocExtension::Ownership::kNotOwned `](https://clickhouse-test-reports.s3.yandex.net/11590/cd902e7d2b0c0c1183507560a6edab8a9d5b1b7a/functional_stateful_tests_(debug)/test_run.txt.out.log))
- [ ] stable abseil-cpp (or the same as in tcmalloc bazel)
- [ ] tcmalloc does not have tags
- [ ] separate build with tcmalloc on CI
- [ ] split into logical parts
- [ ] uses patched version (see commits descriptions/comments for the reason)
- [ ] tcmalloc RSEQ (restartable sequences) requires linux 4.18+
- [ ] telemetry via MallocExtension (like statistics for jemalloc)
- [ ] nallocx
- [ ] terminate in case of allocation failure allows optimization (`noexcept`, `-DABSL_ALLOCATOR_NOTHROW`)
- [ ] [doc states that it depends from THP](https://github.com/google/tcmalloc/blob/master/docs/temeraire.md)
- [ ] background thread that calls `ReleaseMemoryToSystem` (AFAIR there is some API for this in newer version)?
- [ ] [GWP-ASan for debug builds?](https://github.com/google/tcmalloc/blob/master/docs/gwp-asan.md)
- [x] use sized deallocations (optimized, clang does not enables `-fsized-deallocation` by default?)
- [x] report performance "issue" to upstream (if it will not be resolved)
- [x] aligned allocations, also check clickhouse code for possible dependency on alignment (hashtables? trees optimizations?) and add `static_assert` against `__STDCPP_DEFAULT_NEW_ALIGNMENT__`
- [x] tried sized alloc/dealloc via `TCMallocInternalNew`/`TCMallocInternalDeleteSized` -- does not makes any difference for `allocator-perf`
- [x] Logical Page Size (default [8k](6d83a078e3f9caf169aa3074315b67c51a2c73e4), try increase, [`TCMALLOC_256K_PAGES`](cd902e7d2b0c0c1183507560a6edab8a9d5b1b7a)) -- does not makes any difference in performance tests
- [x] use front-end for allocations up to 4MB (`TCMALLOC_4M_MAX_SIZE`)

</details>

Changelog category (leave one):
- Other

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Ability to use tcmalloc allocator (new C++ version by google)

Can be enabled with:

    -DENABLE_JEMALLOC=OFF -DENABLE_TCMALLOC_CPP=ON

Suggested-by: @alexey-milovidov 
Cc: @akuzm (perf test)

<details>

`HEAD`:
- 6d83a078e3f9caf169aa3074315b67c51a2c73e4 -- initial (1 errors, 8 faster, 232 slower, 215 unstable)
- cd902e7d2b0c0c1183507560a6edab8a9d5b1b7a -- `TCMALLOC_256K_PAGES`
- 19c4aa66e2c00c1bde2aa6b1d2e3ab9b0037c039 - `TCMALLOC_4M_MAX_SIZE` (9 faster, 98 slower, 210 unstable)
- f694f412800cebf00ebe4941939d0bc5323c07e4 - same as above
- 87a1002abd736af2ecc6726f43aa0f1c6cc3c110 - same as above + https://github.com/google/tcmalloc/commit/3e01aa2

</details>

### CODE REVIEW

**Comment by azat** [comment]
>Performance — 1 errors, 8 faster, 232 slower, 215 unstable

[right.svg.zip](https://github.com/ClickHouse/ClickHouse/files/4763546/right.svg.zip)

So it does used, but slower, need to dig

**Comment by alexey-milovidov** [comment]
> Performance — 232 slower.

That's interesting, probably some trivial reason.

**Comment by alexey-milovidov** [comment]
Why do we see something like https://github.com/abseil/abseil-cpp/blob/master/absl/base/internal/errno_saver.h in flame graph? This function should be 100% inlined. Maybe it is accidentially compiled with wrong flags?

**Comment by alexey-milovidov** [comment]
By the way, your flame graph is not from perf test, because it is:
- reversed;
- contains inline functions...

Let's look at flame graphs that are automatically build as a result of perftest.
(The link to `.7z` file at bottom)

**Comment by azat** [comment]
>Maybe it is accidentially compiled with wrong flags?

Yes this definitely should be verified

>By the way, your flame graph is not from perf test, because it is:

It was built based on the output.7z from the performance test, using [script](https://gist.github.com/akuzm/3f06cb15c7093d823554a14f1a9a1fcd) by @akuzm (and updated to for `TCMalloc`)

**Comment by alexey-milovidov** [comment]
[svg.zip](https://github.com/ClickHouse/ClickHouse/files/4764675/svg.zip)

**Comment by alexey-milovidov** [comment]
Maybe it is just slower on middle-size allocations (from a few KB to a few MB)?

**Comment by akuzm** [comment]
> Why do we see something like https://github.com/abseil/abseil-cpp/blob/master/absl/base/internal/errno_saver.h in flame graph? This function should be 100% inlined. Maybe it is accidentially compiled with wrong flags?

Looks like it is inlined -- the file is errno_saver, but the function is AbslInternalSpinLockDelay, something locking-related. And there is really a lot of this function, I guess there is heavy contention on some internal data structures.

**Comment by alexey-milovidov** [comment]
Maybe we can create an isolated test case with a huge number of randomly distributed middle sized allocations from miltiple threads?

**Comment by azat** [comment]
Simple test shows that it is slower (2x), but before making conclusions the results should be analyzed more first.

**Comment by alexey-milovidov** [comment]
Please note that the original tcmalloc also was not working well without some tuning:
https://github.com/ClickHouse/ClickHouse/commit/ca9c4bbdbb4c79e6cc945d53282cd1a4acdfb22c

Actually it was working well but degraded after some release.
This is very similar to what happened with jemalloc:
https://github.com/jemalloc/jemalloc/issues/1347#issuecomment-453124310

For some reason, the scenario of middle-sized allocations is "dark zone" for allocators, they just don't have it in their test suite.

We need to isolate this scenario and submit to them.

**Comment by alexey-milovidov** [comment]
There is a feature request to add CMake to tcmalloc: https://github.com/google/tcmalloc/issues/4
As you have added it in this PR, you can also contribute it to upstream.

**Comment by azat** [comment]
>There is a feature request to add CMake to tcmalloc: google/tcmalloc#4
>As you have added it in this PR, you can also contribute it to upstream.

Yep, I'm going to submit this (and also some patches against upstream should be submitted too), but first this should be done in a cleaner way (and I need to dig into abseil more too).

>Please note that the original tcmalloc also was not working well without some tuning:
> ca9c4bb

Thanks, but this implementation is completely different.

>Actually it was working well but degraded after some release.
This is very similar to what happened with jemalloc:
jemalloc/jemalloc#1347 (comment)

Yep, I saw your realloc test (and actually my testing was based on it, but a little bit different)

> We need to isolate this scenario and submit to them.

Yep, or better investigate and share solution :) (if it is more or less simple)

>For some reason, the scenario of middle-sized allocations is "dark zone" for allocators, they just don't have it in their test suite (and the reason of degradation is usually - more page faults due to less caching, more early pages deallocation/invalidation).

And actually I'm not sure that the problem is only in the middle-sized, but it is too early to make conclusions, I'm not finished yet

**Comment by akuzm** [comment]
tcmalloc uses twice less memory than jemalloc:

tcmalloc-MemoryResident

To build this graph from performance test output:
```
export metric="MemoryResident" && clickhouse-local --query "create view l as select * from file('left-async-metric-log.tsv', TSVWithNamesAndTypes, 'event_date Date, event_time DateTime, name String, value Float64'); with (select min(event_time) from l) as min_time select l.event_time - min_time, l.value, r.value from l asof join file('right-async-metric-log.tsv', TSVWithNamesAndTypes, 'event_date Date, event_time DateTime, name String, value Float64') r on l.name = r.name and l.event_time <= r.event_time where name = '$metric' order by event_time" > 1.txt && gnuplot --persist -e "set datafile separator '\t'; set terminal png size 960,540; set xtics time format '%tH:%tM'; set title '$metric' offset 0,-3; set key left top; plot '1.txt' using 1:2 with lines title 'Left', '1.txt' using 1:3 with lines title 'Right'" > tcmalloc-$metric.png
```

To estimate the difference using the graph data:
```
$ clickhouse-local --query "with 0.05 as dd select median((right - left)/left) from file('1.txt', TSV, 'seconds int, left Float64, right Float64')"

-0.5157845029932705
```

**Comment by azat** [comment]
>Maybe it is just slower on middle-sized allocations (from a few KB to a few MB)?

@alexey-milovidov AFAICS the problem is not in the middle-sized but in allocations >~256K (depends on the number of classes for fast path, this depends on the size of pages is used in tcmalloc, tried 8k/256k not helps a lot), and it does not looks like it can be fixed easily.

I have some ideas left, but now I'm already not expecting that it will works better then jemalloc

As the last steps:
- I can bring it into a more cleaner state to keep it in upstream (to update periodically and see if it will be better)
- or just close it

**Comment by alexey-milovidov** [comment]
I name allocation "middle sized" if it is less than what should go directly to mmap (64 MiB in my experience) but greater than a few KiB. We use these allocations a lot for columns and buffers.

There is some code from a sibling project in Yandex to cache middle-sized allocations on top of allocator. We can bring this code into ClickHouse... I did not tested it, but we can try.

**Comment by alexey-milovidov** [comment]
> As the last steps:

We need to make a test case that will show when tcmalloc is worse than jemalloc and send it to Google as an issue.

**Comment by alexey-milovidov** [comment]
BTW it's possible that Linux kernel in our CI does not support "restartable sequences".

**Comment by alexey-milovidov** [comment]
> tcmalloc RSEQ (restartable sequences) requires linux 4.18+

We can print Linux kernel version at server startup.

> doc states that it depends from THP

THP was working extremely bad at least a few years ago, so all the reccomendations states that you should disable them (otherwise you get memory fragmentation when program runs for significantly long time).

> GWP-ASan for debug builds?

How it is implemented? Looks very useful. Maybe we can use the same technique independently of tcmalloc?

> use sized deallocations

We also use (and enable) sized deallocations in our builds.

> aligned allocations, also check clickhouse code for possible dependency on alignment (hashtables? trees optimizations?)

Mostly not, the most cases are 4K alignment for direct IO.

**Comment by azat** [comment]
>There is some code from a sibling project in Yandex to cache middle-sized allocations on top of allocator. We can bring this code into ClickHouse... I did not tested it, but we can try.

Hope that you are not talking about LFAlloc (#5369)

>BTW it's possible that Linux kernel in our CI does not support "restartable sequences".

I'm testing on 5.1.5

```
$ fgrep RSEQ /boot/config-$(uname -r)
CONFIG_RSEQ=y
CONFIG_HAVE_RSEQ=y
```

And the problem does not looks like due to RSEQ, but due to locking overhead (and also maybe more heavy allocation code path in general, not sure)

**Comment by alexey-milovidov** [comment]
> Hope that you are not talking about LFAlloc (#5369)

That separate caching layer was implemented to mitigate the issue that LFAlloc does mmap too frequently :)

**Comment by azat** [comment]
>THP was working extremely bad at least a few years ago, so all the reccomendations states that you should disable them (otherwise you get memory fragmentation when program runs for significantly long time).

I'm seeing this everywhere without any details, but not sure that it is true for recent kernels (I saw some stuff around it in LKML)

>We also use (and enable) sized deallocations in our builds.

That's true, but you need to pass size of the object to the allocator, which is not done right now (AFAICS)

> >aligned allocations, also check clickhouse code for possible dependency on alignment (hashtables? trees optimizations?)
>
>Mostly not, the most cases are 4K alignment for direct IO.

I though that masking MSB (for example when I last saw at rbtree in linux it uses MSB to encode the color) can be a problem, but minimal alignment satisfied, so should not be a problem

Indeed, 4k alignment is another issue

>That separate caching layer was implemented to mitigate the issue that LFAlloc does mmap too frequently :)

Nice! :)

**Comment by alexey-milovidov** [comment]
> That's true, but you need to pass size of the object to the allocator, which is not done right now (AFAICS)

Our new_delete.cpp does it for jemalloc.

**Comment by azat** [comment]
>Our new_delete.cpp does it for jemalloc.

Yep (actually `deleteSized` in `memory.h`)

**Comment by azat** [comment]
>@alexey-milovidov AFAICS the problem is not in the middle-sized but in allocations >~256K (depends on the number of classes for fast path, this depends on the size of pages is used in tcmalloc, tried 8k/256k not helps a lot), and it does not looks like it can be fixed easily.

https://github.com/google/tcmalloc/issues/40

**Comment by alexey-milovidov** [comment]
Thank you!

We can accept tcmalloc version with even more significant patches...

**Comment by azat** [comment]
This is an attempt to use lock-free part of the allocator (front-end) up to 4MB allocations

**Comment by azat** [comment]
FWIW CI adds status for the incorrect commit, the latest commit is 19c4aa66e2c00c1bde2aa6b1d2e3ab9b0037c039 but marked by CI - 24dca801959b241268f8c3608affd26eaa831d7c, looks like it get the last from the list w/o sort (but I'm pretty sure that it uses sources from the correct commit)
Oh, and maybe that's why it does not shows summary table here?

**Comment by azat** [comment]
After patching tcmalloc to use **front-end** (allocations can be done w/o locking) **up to 4MB** (in upstream it is only possible to use it for allocations up to 256K), **perf tests became a little bit faster**, but still not enough:

- default (lock-free up to 8<<10): 1 errors, 8 faster, 232 slower, 215 unstable
- 4m (lock-free up to 4<<20): 9 faster, 98 slower, 210 unstable

**I don't think that using front-end for large allocations will work as a long-term** (this is just out of curiosity), looks like long-term solution will be to make tcmalloc lock-free not only for front-end.
But I also want to try to tune front-end for allocations that is done in perf tests, for this I need to run them with memory sampling

**Pull request closed without merging**
