### PR TITLE
Add documents for window view

### PR DESCRIPTION
**Pull request by Vxider**
Changelog category (leave one):
- Documentation (changelog entry is not required)

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
...

Detailed description / Documentation draft:
...

This PR adds the documents for window view and window function. 

However, I found the window function of window view has the same name as the [window functions in standard SQL](https://clickhouse.com/docs/en/sql-reference/window-functions/). So the window functions might be renamed, any suggestions? Also the `toc_priority` and `toc_title` in `window-functions.md` might be modified.

### CODE REVIEW

**Comment by kssenii** [comment]
> However, I found the window function of window view has the same name as the window functions in standard SQL. So the window functions might be renamed, any suggestions?

may be just `Window-view Functions`?

**Comment by Vxider** [comment]
> may be just `Window-view Functions`?

Brilliant, solved the problem I did not resolve all afternoon👍

**Comment by kssenii** [comment]
@Mergifyio update

**Review by kssenii — APPROVED** [review]

**Comment by Vxider** [comment]
@kssenii How about renaming `window-view function` to `time window function` because window-view functions are used to aggregate data by time.  The naming away from the window view also means that the window-view function does not need to be used with the window view, e.g. use tumble function in a table for batch processing (`SELECT * FROM * GROUP BY tumble()`. (But it is meaningless to use the hop function without the window view)

**Comment by kssenii** [comment]
@Vxider I agree, let's rename.

**Comment by Vxider** [comment]
>  I agree, let's rename.

OK, I'll make a new PR ASAP

**Comment by ka1bi4** [comment]
Internal documentation ticket: DOCSUP-20065

**Pull request merged**
