### PR TITLE
Add --now option to enable and start the service

### PR DESCRIPTION
**Pull request by peter279k**
### Changelog category (leave one):

- Packaging Improvement

I think it should be great to start the service daemon automatically after installing the ClickHouse database server completely.

It can be convenient for users to use the ClickHouse database server and it's not necessary to run the `systemctl start` command after installing the database server completely.

Using the `--now` option in the `systemctl enable` command to achieve the above purpose.

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

- Adding the `--now` option to enable and start service automatically when installing the database server completely.

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]

**Comment by robot-clickhouse-ci-1** [comment]
*This is an automated comment for commit a7aeb4c00f106d396364bf2a21697e329d3d284d with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/60656/a7aeb4c00f106d396364bf2a21697e329d3d284d/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

**Comment by alexey-milovidov** [comment]
@peter279k, AST Fuzzer showed some error.

**Comment by peter279k** [comment]
@alexey-milovidov, after checking the [main.log](https://s3.amazonaws.com/clickhouse-test-reports/60656/a7aeb4c00f106d396364bf2a21697e329d3d284d/ast_fuzzer__asan_/main.log), I don't think it's related to the error because it seems to be related to the memory error I think.

```
......
2024-03-03 02:33:56	 EXC_BAD_ACCESS Yes	Yes	Yes		Could not access memory
2024-03-03 02:33:56	 EXC_BAD_INSTRUCTION Yes	Yes	Yes		Illegal instruction/operand
2024-03-03 02:33:56	 EXC_ARITHMETIC Yes	Yes	Yes		Arithmetic exception
2024-03-03 02:33:56	 EXC_EMULATION Yes	Yes	Yes		Emulation instruction
2024-03-03 02:33:56	 EXC_SOFTWARE  Yes	Yes	Yes		Software generated exception
2024-03-03 02:33:56	 EXC_BREAKPOINT Yes	Yes	Yes		Breakpoint
2024-03-03 02:33:56	 SIGLIBRT      No	No	Yes		librt internal signal
2024-03-03 02:33:56	 
2024-03-03 02:33:56	 Use the "handle" command to change these tables.
2024-03-03 02:33:56	 [Detaching after fork from child process 265]
2024-03-03 02:33:57	 + for _ in {1..180}
2024-03-03 02:33:57	 + clickhouse-client --query 'select 1'
2024-03-03 02:33:57	 Code: 210. DB::NetException: Connection refused (localhost:9000). (NETWORK_ERROR)
......
2024-03-03 02:36:39	 Code: 210. DB::NetException: Connection refused (localhost:9000). (NETWORK_ERROR)
2024-03-03 02:36:39	 
2024-03-03 02:36:39	 + sleep 1
2024-03-03 02:36:40	 + kill -0 158
2024-03-03 02:36:40	 ch/docker/test/fuzzer/run-fuzzer.sh: line 228: kill: (158) - No such process
```

**Comment by peter279k** [comment]
Here are my steps to install the ClickHouse server to verify this PR in the real test:

- Install the ClickHouse server with the [Deb package installation approach](https://clickhouse.com/docs/en/install#install-from-deb-packages).
- After installing the ClickHouse server, running the `sudo /bin/systemctl enable --now clickhouse-server` command and `sudo /bin/systemctl status clickhouse-server` commands.

These commands output are as follows:

```sh
sudo apt-get install -y apt-transport-https ca-certificates dirmngr
sudo gpg --no-default-keyring --keyring /usr/share/keyrings/clickhouse-keyring.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 8919F6BD2B48D754

echo "deb [signed-by=/usr/share/keyrings/clickhouse-keyring.gpg] https://packages.clickhouse.com/deb stable main" | sudo tee \
    /etc/apt/sources.list.d/clickhouse.list
sudo apt-get update

sudo apt-get install -y clickhouse-server clickhouse-client

$ sudo systemctl status clickhouse-server
○ clickhouse-server.service - ClickHouse Server (analytic DBMS for big data)
     Loaded: loaded (/lib/systemd/system/clickhouse-server.service; enabled; vendor preset: enabled)
     Active: inactive (dead)

$ sudo systemctl enable --now clickhouse-server
Synchronizing state of clickhouse-server.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable clickhouse-server

$ sudo systemctl status clickhouse-server
● clickhouse-server.service - ClickHouse Server (analytic DBMS for big data)
     Loaded: loaded (/lib/systemd/system/clickhouse-server.service; enabled; vendor preset: enabled)
     Active: active (running) since Mon 2024-03-04 03:10:03 UTC; 33s ago
   Main PID: 1796 (clickhouse-serv)
      Tasks: 667 (limit: 2309)
     Memory: 144.4M
        CPU: 1.757s
     CGroup: /system.slice/clickhouse-server.service
             ├─1795 clickhouse-watchdog "" "" "" "" "" "" "" --config=/etc/clickhouse-server/config.xml --pid-file=/run/clickhouse-server/clickhouse-server.pid
             └─1796 /usr/bin/clickhouse-server --config=/etc/clickhouse-server/config.xml --pid-file=/run/clickhouse-server/clickhouse-server.pid

Mar 04 03:10:02 ubuntu-s-1vcpu-2gb-amd-sgp1-01 systemd[1]: Starting ClickHouse Server (analytic DBMS for big data)...
Mar 04 03:10:02 ubuntu-s-1vcpu-2gb-amd-sgp1-01 clickhouse-server[1795]: Processing configuration file '/etc/clickhouse-server/config.xml'.
Mar 04 03:10:02 ubuntu-s-1vcpu-2gb-amd-sgp1-01 clickhouse-server[1795]: Logging trace to /var/log/clickhouse-server/clickhouse-server.log
Mar 04 03:10:02 ubuntu-s-1vcpu-2gb-amd-sgp1-01 clickhouse-server[1795]: Logging errors to /var/log/clickhouse-server/clickhouse-server.err.log
......
```

**Comment by alexey-milovidov** [comment]
I don't know why the AST fuzzer has failed. Let's check if merging with the master will help.

**Comment by alexey-milovidov** [comment]
@peter279k AST Fuzzer has failed.

**Comment by alexey-milovidov** [comment]
What happens if I upgrade ClickHouse by installing a new package when the old one is already installed?
The desired effect - keep the previous version running to allow rolling restart.

**Comment by peter279k** [comment]
> What happens if I upgrade ClickHouse by installing a new package when the old one is already installed?

Here are my simple/manual tests to verify the above issue:

```sh
# Firstly, install the outdated ClickHouse version
$ sudo apt-get install -y apt-transport-https ca-certificates curl gnupg
curl -fsSL 'https://packages.clickhouse.com/rpm/lts/repodata/repomd.xml.key' | sudo gpg --dearmor -o /usr/share/keyrings/clickhouse-keyring.gpg

echo "deb [signed-by=/usr/share/keyrings/clickhouse-keyring.gpg] https://packages.clickhouse.com/deb stable main" | sudo tee \
    /etc/apt/sources.list.d/clickhouse.list
sudo apt-get update
$ sudo apt-get install -y clickhouse-server=24.1.5.6 clickhouse-client=24.1.5.6 clickhouse-common-static=24.1.5.6
$ systemctl start clickhouse-server
root@ubuntu-s-2vcpu-4gb-amd-sgp1-01:~# systemctl status clickhouse-server
● clickhouse-server.service - ClickHouse Server (analytic DBMS for big data)
     Loaded: loaded (/lib/systemd/system/clickhouse-server.service; enabled; preset: enabled)
     Active: active (running) since Fri 2024-03-22 02:48:50 UTC; 4s ago
   Main PID: 1686 (clickhouse-serv)
      Tasks: 665 (limit: 4646)
     Memory: 127.3M
        CPU: 621ms
     CGroup: /system.slice/clickhouse-server.service

# Second, install the latest ClickHouse version and run systemctl enable --now command to check whether the ClickHouse version will be restarted.
$ sudo apt-get install clickhouse-server clickhouse-client clickhouse-common-static
$ systemctl enable --now clickhouse-server
$ clickhouse-client --password --query "select version();"
Password for user (default):
24.1.5.6
$ systemctl restart clickhouse-server
$ clickhouse-client --password --query "select version();"
Password for user (default):
24.2.2.71
```

As we can see, this option only enable and start daemon service. We have to restart the current service via the `systemctl restart` command.

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
@peter279k, this change didn't work well. As a result, clickhouse was not installable at all.
I'm not an expert in systemd, so it is on you.

**Comment by peter279k** [comment]
Is there any way to build development Debian packages? So that I can test what's going on about installing development ClickHouse server.

**Comment by peter279k** [comment]
@alexey-milovidov

**Comment by Felixoid** [comment]
You can download the packages from https://s3.amazonaws.com/clickhouse-test-reports/60656/f2b18d279adaf1dc74d14bf0200f501e9f58ac0d/clickhouse_build_check/report.html

**Comment by peter279k** [comment]
> Here what went wrong https://github.com/ClickHouse/ClickHouse/actions/runs/8385054258/job/23019899032

After digging the action running log, I found the problem:

```
......
Synchronizing state of clickhouse-server.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable clickhouse-server
Created symlink /etc/systemd/system/multi-user.target.wants/clickhouse-server.service → /lib/systemd/system/clickhouse-server.service.
Setting up clickhouse-client (24.3.1.2065) ...
+ bash -ex /packages/initd_test.sh
+ set -e
+ trap 'bash -ex /packages/preserve_logs.sh' ERR
+ test_env=TEST_THE_DEFAULT_PARAMETER=15
+ echo TEST_THE_DEFAULT_PARAMETER=15
+ /etc/init.d/clickhouse-server start
/var/run/clickhouse-server/clickhouse-server.pid file exists and contains pid = 191.
The process with pid = 191 is already running.
+ clickhouse-client -q 'SELECT version()'
24.3.1.2065
++ cat /var/run/clickhouse-server/clickhouse-server.pid
+ grep TEST_THE_DEFAULT_PARAMETER=15 /proc/191/environ
++ bash -ex /packages/preserve_logs.sh
+ journalctl -u clickhouse-server
+ journalctl -u clickhouse-keeper
+ cp /var/log/clickhouse-server/clickhouse-server.err.log /var/log/clickhouse-server/clickhouse-server.log /tests_logs/
+ cp '/var/log/clickhouse-keeper/clickhouse-keeper.*' /tests_logs/
cp: cannot stat '/var/log/clickhouse-keeper/clickhouse-keeper.*': No such file or directory
+ :
+ chmod a+rw -R /tests_logs
+ exit 1
.......
```

It's failed when running the `bash -ex /packages/preserve_logs.sh` shell script.

I cannot find the `preserve_logs.sh` script contents and I guess it will check the `clickhouse-keeper` service log when the `clickhouse-server` service is running actually.

For this PR, the `clickhouse-server` service will be run automatically when it's the first time for the installation.

**Comment by peter279k** [comment]
I need to check the `preserve_logs.sh` shell script and modify the behavior.

**Comment by peter279k** [comment]
The copy command is not correct. It should be `cp /var/log/clickhouse-keeper/clickhouse-keeper.* /tests_logs/`, not the `cp '/var/log/clickhouse-keeper/clickhouse-keeper.*' /tests_logs/`.

**Comment by peter279k** [comment]
I also found that the ClickHouse Keeper test has been failed:

```sh
......
Not creating home directory `/dev/null'.
+ bash -ex /packages/keeper_test.sh
+ set -e
+ trap 'bash -ex /packages/preserve_logs.sh' ERR
+ systemctl start clickhouse-keeper
wait for clickhouse-keeper to being up
+ for i in {1..20}
+ echo wait for clickhouse-keeper to being up
/packages/keeper_test.sh: connect: Connection refused
/packages/keeper_test.sh: line 7: /dev/tcp/127.0.0.1/9181: Connection refused
+ sleep 1
wait for clickhouse-keeper to being up
+ for i in {1..20}
+ echo wait for clickhouse-keeper to being up
/packages/keeper_test.sh: connect: Connection refused
/packages/keeper_test.sh: line 7: /dev/tcp/127.0.0.1/9181: Connection refused
+ sleep 1
wait for clickhouse-keeper to being up
+ for i in {1..20}
+ echo wait for clickhouse-keeper to being up
/packages/keeper_test.sh: connect: Connection refused
/packages/keeper_test.sh: line 7: /dev/tcp/127.0.0.1/9181: Connection refused
+ sleep 1
+ for i in {1..20}
+ echo wait for clickhouse-keeper to being up
/packages/keeper_test.sh: connect: Connection refused
/packages/keeper_test.sh: line 7: /dev/tcp/127.0.0.1/9181: Connection refused
+ sleep 1
wait for clickhouse-keeper to being up
wait for clickhouse-keeper to being up
+ for i in {1..20}
+ echo wait for clickhouse-keeper to being up
/packages/keeper_test.sh: connect: Connection refused
/packages/keeper_test.sh: line 7: /dev/tcp/127.0.0.1/9181: Connection refused
+ sleep 1
wait for clickhouse-keeper to being up
+ for i in {1..20}
+ echo wait for clickhouse-keeper to being up
/packages/keeper_test.sh: connect: Connection refused
/packages/keeper_test.sh: line 7: /dev/tcp/127.0.0.1/9181: Connection refused
+ sleep 1
wait for clickhouse-keeper to being up
+ for i in {1..20}
+ echo wait for clickhouse-keeper to being up
/packages/keeper_test.sh: connect: Connection refused
/packages/keeper_test.sh: line 7: /dev/tcp/127.0.0.1/9181: Connection refused
+ sleep 1
+ for i in {1..20}
+ echo wait for clickhouse-keeper to being up
wait for clickhouse-keeper to being up
/packages/keeper_test.sh: connect: Connection refused
/packages/keeper_test.sh: line 7: /dev/tcp/127.0.0.1/9181: Connection refused
+ sleep 1
wait for clickhouse-keeper to being up
+ for i in {1..20}
+ echo wait for clickhouse-keeper to being up
/packages/keeper_test.sh: connect: Connection refused
/packages/keeper_test.sh: line 7: /dev/tcp/127.0.0.1/9181: Connection refused
+ sleep 1
wait for clickhouse-keeper to being up
+ for i in {1..20}
+ echo wait for clickhouse-keeper to being up
/packages/keeper_test.sh: connect: Connection refused
/packages/keeper_test.sh: line 7: /dev/tcp/127.0.0.1/9181: Connection refused
+ sleep 1
wait for clickhouse-keeper to being up
+ for i in {1..20}
+ echo wait for clickhouse-keeper to being up
/packages/keeper_test.sh: connect: Connection refused
/packages/keeper_test.sh: line 7: /dev/tcp/127.0.0.1/9181: Connection refused
+ sleep 1
+ for i in {1..20}
+ echo wait for clickhouse-keeper to being up
/packages/keeper_test.sh: connect: Connection refused
/packages/keeper_test.sh: line 7: /dev/tcp/127.0.0.1/9181: Connection refused
+ sleep 1
wait for clickhouse-keeper to being up
wait for clickhouse-keeper to being up
+ for i in {1..20}
+ echo wait for clickhouse-keeper to being up
/packages/keeper_test.sh: connect: Connection refused
/packages/keeper_test.sh: line 7: /dev/tcp/127.0.0.1/9181: Connection refused
+ sleep 1
wait for clickhouse-keeper to being up
+ for i in {1..20}
+ echo wait for clickhouse-keeper to being up
/packages/keeper_test.sh: connect: Connection refused
/packages/keeper_test.sh: line 7: /dev/tcp/127.0.0.1/9181: Connection refused
+ sleep 1
wait for clickhouse-keeper to being up
+ for i in {1..20}
+ echo wait for clickhouse-keeper to being up
/packages/keeper_test.sh: connect: Connection refused
/packages/keeper_test.sh: line 7: /dev/tcp/127.0.0.1/9181: Connection refused
+ sleep 1
wait for clickhouse-keeper to being up
+ for i in {1..20}
+ echo wait for clickhouse-keeper to being up
/packages/keeper_test.sh: connect: Connection refused
/packages/keeper_test.sh: line 7: /dev/tcp/127.0.0.1/9181: Connection refused
+ sleep 1
wait for clickhouse-keeper to being up
+ for i in {1..20}
+ echo wait for clickhouse-keeper to being up
/packages/keeper_test.sh: connect: Connection refused
/packages/keeper_test.sh: line 7: /dev/tcp/127.0.0.1/9181: Connection refused
+ sleep 1
+ for i in {1..20}
+ echo wait for clickhouse-keeper to being up
/packages/keeper_test.sh: connect: Connection refused
/packages/keeper_test.sh: line 7: /dev/tcp/127.0.0.1/9181: Connection refused
+ sleep 1
wait for clickhouse-keeper to being up
wait for clickhouse-keeper to being up
+ for i in {1..20}
+ echo wait for clickhouse-keeper to being up
/packages/keeper_test.sh: connect: Connection refused
/packages/keeper_test.sh: line 7: /dev/tcp/127.0.0.1/9181: Connection refused
+ sleep 1
wait for clickhouse-keeper to being up
+ for i in {1..20}
+ echo wait for clickhouse-keeper to being up
/packages/keeper_test.sh: connect: Connection refused
/packages/keeper_test.sh: line 7: /dev/tcp/127.0.0.1/9181: Connection refused
+ sleep 1
wait for clickhouse-keeper to answer on mntr request
+ for i in {1..5}
+ echo wait for clickhouse-keeper to answer on mntr request
+ exec
/packages/keeper_test.sh: connect: Connection refused
/packages/keeper_test.sh: line 12: /dev/tcp/127.0.0.1/9181: Connection refused
+ echo mntr
/packages/keeper_test.sh: line 13: 13: Bad file descriptor
+ grep zk_version
+ cat
/packages/keeper_test.sh: line 14: 13: Bad file descriptor
+ sleep 1
wait for clickhouse-keeper to answer on mntr request
+ exec
+ for i in {1..5}
+ echo wait for clickhouse-keeper to answer on mntr request
+ exec
/packages/keeper_test.sh: connect: Connection refused
/packages/keeper_test.sh: line 12: /dev/tcp/127.0.0.1/9181: Connection refused
+ echo mntr
/packages/keeper_test.sh: line 13: 13: Bad file descriptor
+ cat
+ grep zk_version
/packages/keeper_test.sh: line 14: 13: Bad file descriptor
+ sleep 1
wait for clickhouse-keeper to answer on mntr request
+ exec
+ for i in {1..5}
+ echo wait for clickhouse-keeper to answer on mntr request
+ exec
/packages/keeper_test.sh: connect: Connection refused
/packages/keeper_test.sh: line 12: /dev/tcp/127.0.0.1/9181: Connection refused
+ echo mntr
/packages/keeper_test.sh: line 13: 13: Bad file descriptor
+ grep zk_version
+ cat
/packages/keeper_test.sh: line 14: 13: Bad file descriptor
+ sleep 1
wait for clickhouse-keeper to answer on mntr request
+ exec
+ for i in {1..5}
+ echo wait for clickhouse-keeper to answer on mntr request
+ exec
/packages/keeper_test.sh: connect: Connection refused
/packages/keeper_test.sh: line 12: /dev/tcp/127.0.0.1/9181: Connection refused
+ echo mntr
/packages/keeper_test.sh: line 13: 13: Bad file descriptor
+ cat
+ grep zk_version
/packages/keeper_test.sh: line 14: 13: Bad file descriptor
+ sleep 1
wait for clickhouse-keeper to answer on mntr request
+ exec
+ for i in {1..5}
+ echo wait for clickhouse-keeper to answer on mntr request
+ exec
/packages/keeper_test.sh: connect: Connection refused
/packages/keeper_test.sh: line 12: /dev/tcp/127.0.0.1/9181: Connection refused
+ echo mntr
/packages/keeper_test.sh: line 13: 13: Bad file descriptor
+ cat
+ grep zk_version
/packages/keeper_test.sh: line 14: 13: Bad file descriptor
+ sleep 1
+ exec
+ exec
......
```

**Comment by peter279k** [comment]
It seems that I found the problem and please look at the PR #61910. Thanks.

**Pull request merged**
