### PR TITLE
Add ability to override initial INSERT SETTINGS via SYSTEM FLUSH DISTRIBUTED

### LINKED ISSUE #41924: Settings store constantly in tmp files(.bin) when insert Distributed table in asynchronous mode
Since I set `max_concurrent_queries_for_user` with a very small value to the user, a lot pending files in distributed table. A large number of writes to remote table failed because of Exception `Code: 202. DB::Exception: Too many simultaneous queries for user default. Current: 6, maximum: 2.`
```sql
SELECT *
FROM system.metrics
WHERE metric = 'DistributedFilesToInsert'

Query id: ea862251-9475-465d-be3b-458f62697573

┌─metric───────────────────┬─value─┬─description───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ DistributedFilesToInsert │ 13787 │ Number of pending files to process for asynchronous insertion into Distributed tables. Number of files for every shard is summed. │
└──────────────────────────┴───────┴───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

1 rows in set. Elapsed: 0.003 sec.
```
I try to set `max_concurrent_queries_for_user` to 40, however I still got Exception `Code: 202. DB::Exception: Too many simultaneous queries for user default. Current: 6, maximum: 2.` 

I found that Settings store constantly in tmp files
```shell
vim 8094.bin
...max_concurrent_queries_for_user^@^A2...
```
The code also verifies
```c++
void StorageDistributedDirectoryMonitor::processFile(const std::string & file_path)
{
    ...
        RemoteInserter remote{*connection, timeouts,
            distributed_header.insert_query,
            distributed_header.insert_settings,
            distributed_header.client_info};
        bool compression_expected = connection->getCompression() == Protocol::Compression::Enable;
        writeRemoteConvert(distributed_header, remote, compression_expected, in, log);
    ...
}
```
Because of `max_concurrent_queries_for_user` limits , old writes are pending all the time. The writing process is asynchronous, should the new configuration take effect on the old write?  In other words, do we have a better solution to the problem I'm facing？

### PR DESCRIPTION
**Pull request by azat**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Add ability to override initial INSERT SETTINGS via SYSTEM FLUSH DISTRIBUTED

This is useful to overwrite settings in the initial query during force flush with SYSTEM FLUSH DISTRIBUTED.

For example imagine that your server is out of queries (max_max_concurrent_queries_for_all_users had been reached), but you want to flush the distributed table anyway, after this patch you can use something like this:

    SYSTEM FLUSH DISTRIBUTED dist SETTINGS max_concurrent_queries_for_all_users=1000000

And also fix flush_on_detach for SYSTEM FLUSH DISTRIBUTED, it should ignore flush_on_detach (https://github.com/ClickHouse/ClickHouse/pull/53501).

Fixes: https://github.com/ClickHouse/ClickHouse/issues/41924

### CODE REVIEW

**Comment by robot-ch-test-poll2** [comment]
*This is an automated comment for commit d0cd8d0d7f74ff251d52e1871cba57d26a51873b with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/61832/d0cd8d0d7f74ff251d52e1871cba57d26a51873b/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

**Review by alexey-milovidov — APPROVED** [review]
Wow, this is much cleaner, better, and easier to understand!

**Comment by azat** [comment]
Flaky check found something interesting for the new test, it should be fixed by https://github.com/ClickHouse/ClickHouse/pull/61867

**Comment by sunny19930321** [comment]
this PR is better

**Pull request merged**
