### PR TITLE
Correct doc for filesystem_prefetch_max_memory_usage

### LINKED ISSUE #54008: filesystem_prefetch_max_memory_usage can't be zero
`filesystem_prefetch_max_memory_usage` documentation under Settings.h says:

```
    M(UInt64, filesystem_prefetch_max_memory_usage, "1Gi", "Maximum memory usage for prefetches. Zero means unlimited", 0) \
```

But when you try to set it to 0 to allow unlimited memory you get an exception:
```
Code: 36. DB::Exception: Received from localhost:9000. DB::Exception: Setting `filesystem_prefetch_max_memory_usage` must be non-zero. (BAD_ARGUMENTS)
```

This was changed in https://github.com/ClickHouse/ClickHouse/pull/48973 cc @kssenii 

Should 0 be allowed and be unlimited? The code under the condition seems to check if it's or not zero, so it seems like it, but maybe there is a reason this was disallowed when testing random settings.

### PR DESCRIPTION
**Pull request by Algunenano**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
...

### Documentation entry for user-facing changes

Closes https://github.com/ClickHouse/ClickHouse/issues/54008

### CODE REVIEW

**Comment by robot-clickhouse-ci-1** [comment]
This is an automated comment for commit 4f9ddcab2bf99fce04adbd8a9e8c974e6fd58a49 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/54058/4f9ddcab2bf99fce04adbd8a9e8c974e6fd58a49/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Review by kssenii — APPROVED** [review]

**Comment by Algunenano** [comment]
Failures:
* `Stateless tests (release)` -> `00002_log_and_exception_messages_formatting`
```
2023-08-30 12:16:40 --- /usr/share/clickhouse-test/queries/0_stateless/00002_log_and_exception_messages_formatting.reference	2023-08-30 11:22:39.780979538 +0200
2023-08-30 12:16:40 +++ /tmp/clickhouse-test/0_stateless/00002_log_and_exception_messages_formatting.stdout	2023-08-30 12:16:40.903260603 +0200
2023-08-30 12:16:40 @@ -5,7 +5,7 @@
2023-08-30 12:16:40  messages shorter than 16	3
2023-08-30 12:16:40  exceptions shorter than 30	3
2023-08-30 12:16:40  noisy messages	0.3
2023-08-30 12:16:40 -noisy Trace messages	0.16
2023-08-30 12:16:40 +noisy Trace messages	0.21787867188600873
2023-08-30 12:16:40  noisy Debug messages	0.09
2023-08-30 12:16:40  noisy Info messages	0.05
2023-08-30 12:16:40  noisy Warning messages	0.01
2023-08-30 12:16:40 
2023-08-30 12:16:40 
2023-08-30 12:16:40 Settings used in the test: --max_insert_threads 0 --group_by_two_level_threshold 1000000 --group_by_two_level_threshold_bytes 50000000 --distributed_aggregation_memory_efficient 1 --fsync_metadata 1 --output_format_parallel_formatting 0 --input_format_parallel_parsing 1 --min_chunk_bytes_for_parallel_parsing 10933630 --max_read_buffer_size 505282 --prefer_localhost_replica 0 --max_block_size 64168 --max_threads 60 --optimize_or_like_chain 1 --optimize_read_in_order 0 --enable_multiple_prewhere_read_steps 0 --read_in_order_two_level_merge_threshold 38 --optimize_aggregation_in_order 0 --aggregation_in_order_max_block_bytes 39099397 --min_compress_block_size 3007673 --max_compress_block_size 2138527 --use_uncompressed_cache 0 --min_bytes_to_use_direct_io 10737418240 --min_bytes_to_use_mmap_io 10737418240 --local_filesystem_read_method read --remote_filesystem_read_method read --local_filesystem_read_prefetch 1 --remote_filesystem_read_prefetch 0 --allow_prefetched_read_pool_for_remote_filesystem 0 --filesystem_prefetch_max_memory_usage 32Mi --filesystem_prefetches_limit 0 --filesystem_prefetch_min_bytes_for_single_read_task 8Mi --filesystem_prefetch_step_marks 50 --filesystem_prefetch_step_bytes 0 --compile_aggregate_expressions 0 --compile_sort_description 0 --merge_tree_coarse_index_granularity 28 --optimize_distinct_in_order 1 --optimize_sorting_by_input_stream_properties 0 --http_response_buffer_size 242890 --http_wait_end_of_query True --enable_memory_bound_merging_of_aggregation_results 1 --min_count_to_compile_expression 3 --min_count_to_compile_aggregate_expression 3 --min_count_to_compile_sort_description 0 --session_timezone Mexico/BajaSur
2023-08-30 12:16:40 
2023-08-30 12:16:40 MergeTree settings used in test: --ratio_of_defaults_for_sparse_serialization 0.0 --prefer_fetch_merged_part_size_threshold 10737418240 --vertical_merge_algorithm_min_rows_to_activate 770474 --vertical_merge_algorithm_min_columns_to_activate 1 --allow_vertical_merges_from_compact_to_wide_parts 1 --min_merge_bytes_to_use_direct_io 10737418240 --index_granularity_bytes 28472894 --merge_max_block_size 23912 --index_granularity 38326 --min_bytes_for_wide_part 1073741824 --marks_compress_block_size 58106 --primary_key_compress_block_size 61879
2023-08-30 12:16:40 
2023-08-30 12:16:40 Database: test_gsrv2i2d
```


Obviously unrelated to the changes, but let's look at what are the most common messages:
```
2023-08-30 12:16:41 count	count_%	size	size_%	uniq_loggers	uniq_threads	levels	background_%	message_format_string
2023-08-30 12:16:41 UInt64	Float64	String	Float64	UInt64	UInt64	Array(String)	Float64	LowCardinality(String)
2023-08-30 12:16:41 3925817	0.218	317.24 MiB	0.172	141	115	['Trace']	0	Got {} commands for part {} (part data version {}, part metadata version {})
2023-08-30 12:16:41 2028764	0.112	111.30 MiB	0.06	54	2239	['Trace']	0	Access granted: {}{}
2023-08-30 12:16:41 1210614	0.067	27.81 MiB	0.015	1	1087	['Trace']	0.001	{} -> {}
2023-08-30 12:16:41 531770	0.029	23.35 MiB	0.013	1	1	['Trace']	1	Processing requests batch, size: {}, bytes: {}
2023-08-30 12:16:41 500550	0.028	30.54 MiB	0.017	3	17	['Trace']	0	Table {} has {} ({})
2023-08-30 12:16:41 417738	0.023	69.11 MiB	0.037	1	292	['Debug']	0	(from {}{}{}){}{} {} (stage: {})
2023-08-30 12:16:41 417547	0.023	62.52 MiB	0.034	4	289	['Trace']	1	{} Creating query context from {} context, user_id: {}, parent context user: {}
```

The most common message is `Got {} commands for part {} (part data version {}, part metadata version {})` which I agree is super noisy. I've also seen it a lot in servers doing reads over large amount of parts. For example:

```
Looking for mutations for part 20230702_53_77_2_253 (part data version 253, part metadata version 0)
Got 0 commands for part 20230702_53_77_2_253 (part data version 253, part metadata version 0)
```

This seems a) not very informational and b) it's checking all mutations for all parts even when they are already marked as done in its status. @CurtizJ any thoughts about how to improve this process or the message?

**Comment by kssenii** [comment]
@Algunenano, please restart the checks, this PR is not mergeable..
Screenshot 2023-08-31 at 12 46 40

**Comment by Algunenano** [comment]
> please restart the checks by pushing an empty commit, this PR is not mergeable..

This is odd. So it's not possible to merge if an unrelated test doesn't pass but it's possible to merge while the tests are running. Seems like a loop hole :smile:

**Pull request merged**
