### PR TITLE
Nullable simplification

### PR DESCRIPTION
**Pull request by alexey-milovidov**

### CODE REVIEW

**Comment by silviucpp** [comment]
Hello,

is this suppose to fix https://github.com/yandex/ClickHouse/issues/1028 ?

**Comment by alexey-milovidov** [comment]
This fixes tons of another issues, but #1028 is still not fixed.
Maybe I'll look at it at the same time.

**Comment by alexey-milovidov** [comment]
https://github.com/yandex/ClickHouse/commit/e2cd0272a48b9bfa9b2639bc4421283075036dc9

**Comment by silviucpp** [comment]
Another issue involving nullable is that ALTER is not working properly. you can see https://github.com/yandex/ClickHouse/issues/1322 for simple steps to replicate.

**Comment by alexey-milovidov** [comment]
That's more complicated. The reason of #1322
is the same as
```
SELECT CAST(NULL AS Nullable(String)) AS x, CAST(x AS Nullable(UInt8))

... Cannot parse UInt8 from String, because value is too short.
```
and
```
SELECT CAST(NULL AS Nullable(UInt8)) AS x, intDiv(10, x)
... Division by zero.
```
and related to eager evaluation of functions.

The first case can be fixed rather simple.
But for general solution, we have a task
"add support for short-curcuit evaluation of some functions".

**Comment by silviucpp** [comment]
Ah ok ! great !

**Comment by silviucpp** [comment]
I just added some steps to replicate the crash for groupUniqArray that's taking place after this commits

**Pull request merged**
