### PR TITLE
test postgresql database engine connections release

### PR DESCRIPTION
**Pull request by max-vostrikov**
added a new test to checki if connections to postgres are released after some time. At the point they do not, as there is a bug: https://github.com/ClickHouse/ClickHouse/issues/65797

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)
- 
> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by kssenii** [comment]
>  At the point they do not, as there is a bug:

There is a connection pool of connections and yes - they are not removed over time, but once broken connection is identified - it will be restored.

**Comment by max-vostrikov** [comment]
> > At the point they do not, as there is a bug:
> 
> There is a connection pool of connections and yes - they are not removed over time, but once broken connection is identified - it will be restored.

@kssenii Does that mean we can close the underlying issue https://github.com/ClickHouse/ClickHouse/issues/65797 ?

**Comment by kssenii** [comment]
The number of connections should not be bigger than the connection pool size. If this is not the case, then there is a bug.
Then if the number of connection correctly does not go beyond connection pool size, then there can be an improvement to close idle connections in a background thread. So may be makes sense to rephrase the issue if this is the case.

**Comment by kssenii** [comment]
> The number of connections should not be bigger than the connection pool size. If this is not the case, then there is a bug.

There is a test which checks this btw https://github.com/ClickHouse/ClickHouse/blob/a930c768c39c47758499a88d44e450b8f8d2ab05/tests/integration/test_storage_postgresql/test.py#L415-L445

**Comment by max-vostrikov** [comment]
After some discussions, we've decided to close this one - there is already a simple test to check number of connections, and all additional features do not test important things here.
If we do implement an underlying feature, we'll need a rework of this anyway.

**Pull request closed without merging**
