### PR TITLE
Aggregate function `uniqCombined` should return non-nullable type

### LINKED ISSUE #65052: heap-buffer-overflow after uniqCombined
https://s3.amazonaws.com/clickhouse-test-reports/0/686d6d676ac13a2265538cce17db94f4602c749a/ast_fuzzer__asan_.html

```
SELECT sum(u)
FROM
(
    SELECT
        intDiv(number, 4096) AS k,
        uniqCombined(tuple(materialize(toLowCardinality(toNullable(16))))) AS u
    FROM numbers(4096 * 100)
    GROUP BY k
)
```

Does not happen if you replace uniqCombined by a different uniq* aggregate function

### PR DESCRIPTION
**Pull request by canhld94**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
- Fix a bug that uniqCombined can return Nullable type and cause undefined behaviour when there is chain of aggregation and `optimize_injective_functions_inside_uniq = 1`.

Close https://github.com/ClickHouse/ClickHouse/issues/65052

### Documentation entry for user-facing changes

- [x] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: Normal Builds
- [ ]  Allow: Special Builds
- [ ]  Allow: All NOT Required Checks
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Do not test
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-ch-test-poll2** [comment]
*This is an automated comment for commit 8042c3b44cb2f794e007b1af3943d7bb75210a5e with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/65091/8042c3b44cb2f794e007b1af3943d7bb75210a5e/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>A Sync</td><td>If it fails, ask a maintainer for help</td><td>⏳ pending</td></tr>
<tbody>
</table>
<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>Checks correctness of the PR's body</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

**Comment by canhld94** [comment]
> * It seems `optimize_injective_functions_inside_uniq` should be fixed and better checks need to be implemented to avoid this happening, independently of the return type.

@Algunenano I will do this if this is a general optimization. Nevertheless, this optimization only apply to `uniq*` function family, and among all of them, only `uniqCombined` can return `Nullable`. I believee `uniqCombined` can return `Nullable` is a mistake.

But in the end yes, this is a break changes, so we need to things twice. Hope to hear some options from @azat @den-crane @alexey-milovidov .

**Comment by Algunenano** [comment]
As a first step I'd suggest to start by fixing `optimize_injective_functions_inside_uniq` with something that can be backported, like disabling this optimization if the type of the aggregation changes (not sure why it's not detected as such, other optimization enforce this).

Then we can introduce a breaking change, which would need to be analyzed and may (or may not) require a setting, to change the return type of `uniqCombined` with nullable types. Fixing a crash by introducing a breaking change should be used as a last resort.

**Comment by canhld94** [comment]
> As a first step I'd suggest to start by fixing `optimize_injective_functions_inside_uniq` with something that can be backported, like disabling this optimization if the type of the aggregation changes (not sure why it's not detected as such, other optimization enforce this).
> 
> 
> 
> Then we can introduce a breaking change, which would need to be analyzed and may (or may not) require a setting, to change the return type of `uniqCombined` with nullable types. Fixing a crash by introducing a breaking change should be used as a last resort. 

You're right, I didn't think about backporting. Enforcing aggregation type sounds like a good way to go.

**Comment by canhld94** [comment]
> disabling this optimization if the type of the aggregation changes

I implemented this in new PR https://github.com/ClickHouse/ClickHouse/pull/65140, leave this open in case we still want to change uniqCombined return type.

**Comment by Algunenano** [comment]
Closing as we don't want to change the return type to fix a bug. We might still do it in the future if we want to uniformize things, but that's a breaking change

**Pull request closed without merging**
