### PR TITLE
Experiment: Enable SLP vectorizer for faster codegen

### PR DESCRIPTION
**Pull request by rschu1ze**
After the recent upgrades to LLVM 16 and 18, folks started to complain about slower codegen: https://github.com/ClickHouse/ClickHouse/pull/66053#issuecomment-2558266063

Prior to the LLVM 16 upgrade, CHJIT force-enabled the SLP vectorizer (see https://github.com/ClickHouse/ClickHouse/pull/69654/files#diff-897102eb40b3e08e4997b80459a83b97ac7d555e4534942cd30581e4f92cefe2). This PR now does the same using the new LLVM pass manager. Let's see if it helps with performance.

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by robot-ch-test-poll2** [comment]
*This is an automated comment for commit f6ba19106d95a512ab68df9a9a2850eeea506887 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/73957/f6ba19106d95a512ab68df9a9a2850eeea506887/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/73954/d2bdca3e46f361093b0ec8472f803d32606eeb38/docs_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Review by alexey-milovidov — APPROVED** [review]

**Comment by rschu1ze** [comment]
--> 1.5x speedup for JIT tests: https://s3.amazonaws.com/clickhouse-test-reports/73957/f6ba19106d95a512ab68df9a9a2850eeea506887/performance_comparison__release__[2_4]/report.html

**Comment by zhanglistar** [comment]
> --> 1.5x speedup for JIT tests: [https://s3.amazonaws.com/clickhouse-test-reports/73957/f6ba19106d95a512ab68df9a9a2850eeea506887/performance_comparison__release__[2_4]/report.html](https://s3.amazonaws.com/clickhouse-test-reports/73957/f6ba19106d95a512ab68df9a9a2850eeea506887/performance_comparison__release__%5B2_4%5D/report.html)

https://s3.amazonaws.com/clickhouse-test-reports/66053/b0941e6a7967c1f410e473a98101a76532c9e00c/performance_comparison__release__%5B2_4%5D/report.html
Still ~20% slower?

**Comment by rschu1ze** [comment]
Yes that's still 20% slower than before LLVM 16 but nobody said that this PR was going to fix all performance issues 😄

The most reasonable explanation for the slowdown is the transition to the new pass manager: https://github.com/ClickHouse/ClickHouse/pull/69654/files#diff-897102eb40b3e08e4997b80459a83b97ac7d555e4534942cd30581e4f92cefe2

The missing SLP vectorizer enablement (this PR) was obvious but I couldn't find equivalents for 

```cpp
    pass_manager_builder.LoopVectorize = true;
    pass_manager_builder.RerollLoops = true;
```

in the new infrastructure. But I am not an expert in this, the code is actually copy-paste from https://llvm.org/docs/NewPassManager.html.

Further thoughts and inputs highly welcome ...

**Pull request merged**
