### PR TITLE
add runOptimize call in bitmap write method

### PR DESCRIPTION
**Pull request by UnamedRus**
### Changelog category (leave one):
- Performance Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Now roaringBitmaps being optimized before serialization. 

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

Basically this: https://github.com/ClickHouse/ClickHouse/issues/48751, lets see what will happen. Kinda related https://github.com/ClickHouse/ClickHouse/pull/38667#issuecomment-1423860842

```
SELECT length(hex(groupBitmapStateIf(number, NOT ((number % X) = 0)))) / 2 AS res
FROM numbers(1000000)
```

X | Master  | PR | PR w/o NOT in cond |
| ------ | ------------- | ------------- | ------------- |
|     10      | 131224  | 129816  | 126424 |
|   40      | 131224  | 100230 | 50152 |
|   50      | 131224  | 80242 | 40152 |
|   100      | 131224  | 40242  |  20152 |
|   1000      | 131224  | 4241  |  2151 | 
|   10000     | 131224  | 641  | 351 |
|   100000     | 131224  | 281 | 82 |

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by robot-clickhouse** [comment]
This is an automated comment for commit c8d995e42e4e2595981fed21191a20da00f80192 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/52842/c8d995e42e4e2595981fed21191a20da00f80192/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Comment by maxjustus** [comment]
Any chance this will get merged? I'm seeing a big performance hit when loading large bitmaps from disk and I suspect that this will make a big difference.

**Review by evillique — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
@evillique Reverted, see #54528

**Comment by alexey-milovidov** [comment]
@UnamedRus, please resubmit without a bug.

**Pull request merged**
