### PR TITLE
Move to clang-11 in CI builds

### PR DESCRIPTION
**Pull request by alesapin**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Build/Testing/Packaging Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Now we use clang-11 to build ClickHouse in CI.

### CODE REVIEW

**Comment by alesapin** [comment]
Seems like clang-11 can't build clickhouse if ThinLTO enabled.
```
2020-09-15 13:13:07 [3969/8300] Linking CXX executable contrib/llvm/llvm/bin/llvm-tblgen
2020-09-15 13:13:07 FAILED: contrib/llvm/llvm/bin/llvm-tblgen 
2020-09-15 13:13:07 : && /usr/bin/ccache /usr/bin/clang++-11  -fdiagnostics-color=always -std=c++2a -fsized-deallocation  -gdwarf-aranges -pipe -msse4.1 -msse4.2 -mpopcnt   -Wall -Wno-unused-command-line-argument  -fdiagnostics-absolute-paths -Werror -w -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -std=c++11 -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -pedantic -Wno-long-long -Wimplicit-fallthrough -Wcovered-switch-default -Wno-class-memaccess -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wstring-conversion -fdiagnostics-color -ffunction-sections -fdata-sections -O2 -g -DNDEBUG -O3  -flto=thin -fno-pie  -fuse-ld=lld -rdynamic -Wl,--gdb-index -Wl,--no-undefined -Wl,-no-pie -fno-pie -Wl,--color-diagnostics -Wl,-allow-shlib-undefined  -flto=thin   -Wl,-O3 -Wl,--gc-sections contrib/llvm/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/AsmMatcherEmitter.cpp.o contrib/llvm/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/AsmWriterEmitter.cpp.o contrib/llvm/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/AsmWriterInst.cpp.o contrib/llvm/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/Attributes.cpp.o contrib/llvm/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/CallingConvEmitter.cpp.o contrib/llvm/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/CodeEmitterGen.cpp.o contrib/llvm/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/CodeGenDAGPatterns.cpp.o contrib/llvm/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/CodeGenHwModes.cpp.o contrib/llvm/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/CodeGenInstruction.cpp.o contrib/llvm/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/CodeGenMapTable.cpp.o contrib/llvm/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/CodeGenRegisters.cpp.o contrib/llvm/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/CodeGenSchedule.cpp.o contrib/llvm/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/CodeGenTarget.cpp.o contrib/llvm/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/DAGISelEmitter.cpp.o contrib/llvm/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/DAGISelMatcherEmitter.cpp.o contrib/llvm/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/DAGISelMatcherGen.cpp.o contrib/llvm/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/DAGISelMatcherOpt.cpp.o contrib/llvm/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/DAGISelMatcher.cpp.o contrib/llvm/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/DFAPacketizerEmitter.cpp.o contrib/llvm/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/DisassemblerEmitter.cpp.o contrib/llvm/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/ExegesisEmitter.cpp.o contrib/llvm/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/FastISelEmitter.cpp.o contrib/llvm/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/FixedLenDecoderEmitter.cpp.o contrib/llvm/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/GlobalISelEmitter.cpp.o contrib/llvm/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/InfoByHwMode.cpp.o contrib/llvm/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/InstrInfoEmitter.cpp.o contrib/llvm/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/InstrDocsEmitter.cpp.o contrib/llvm/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/IntrinsicEmitter.cpp.o contrib/llvm/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/OptParserEmitter.cpp.o contrib/llvm/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/PredicateExpander.cpp.o contrib/llvm/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/PseudoLoweringEmitter.cpp.o contrib/llvm/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/RISCVCompressInstEmitter.cpp.o contrib/llvm/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/RegisterBankEmitter.cpp.o contrib/llvm/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/RegisterInfoEmitter.cpp.o contrib/llvm/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/SDNodeProperties.cpp.o contrib/llvm/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/SearchableTableEmitter.cpp.o contrib/llvm/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/SubtargetEmitter.cpp.o contrib/llvm/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/SubtargetFeatureInfo.cpp.o contrib/llvm/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/TableGen.cpp.o contrib/llvm/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/Types.cpp.o contrib/llvm/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/X86DisassemblerTables.cpp.o contrib/llvm/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/X86EVEX2VEXTablesEmitter.cpp.o contrib/llvm/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/X86FoldTablesEmitter.cpp.o contrib/llvm/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/X86ModRMFilters.cpp.o contrib/llvm/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/X86RecognizableInstr.cpp.o contrib/llvm/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/WebAssemblyDisassemblerEmitter.cpp.o contrib/llvm/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/CTagsEmitter.cpp.o  -o contrib/llvm/llvm/bin/llvm-tblgen  -Wl,-rpath,"\$ORIGIN/../lib"  contrib/llvm/llvm/lib/libLLVMSupport.a  contrib/llvm/llvm/lib/libLLVMTableGen.a  -lpthread  contrib/llvm/llvm/lib/libLLVMSupport.a  contrib/llvm/llvm/lib/libLLVMDemangle.a  -Wl,--start-group  base/glibc-compatibility/libglibc-compatibility.a  contrib/libcxx-cmake/libcxx.a  contrib/libcxxabi-cmake/libcxxabi.a  contrib/libunwind-cmake/libunwind.a  -Wl,--end-group  -nodefaultlibs /usr/lib/llvm-11/lib/clang/11.0.0/lib/linux/libclang_rt.builtins-x86_64.a  -lc -lm -lrt -lpthread -ldl && :
2020-09-15 13:13:07 ld.lld: error: base/glibc-compatibility/libglibc-compatibility.a(glibc-compatibility.c.o): Invalid record
2020-09-15 13:13:07 clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by alexey-milovidov** [comment]
Would it help if we disable ThinLTO for `libglibc-compatibility`?

**Comment by alexey-milovidov** [comment]
It didn't help:
```
2020-09-16 08:30:49 ld.lld: error: contrib/libcxx-cmake/libcxx.a(algorithm.cpp.o): Invalid record
```

**Comment by alesapin** [comment]
> It didn't help:
> 
> ```
> 2020-09-16 08:30:49 ld.lld: error: contrib/libcxx-cmake/libcxx.a(algorithm.cpp.o): Invalid record
> ```

Try for libcxx or we will leave release build with clang-10?

**Comment by alesapin** [comment]
strange random test failures...

**Comment by alexey-milovidov** [comment]
> Try for libcxx or we will leave release build with clang-10?

Most likely it will fail somewhere else.
It looks like a bug either with ThinLTO or LLD.
If we will have a time, we should make a reproducible example and report to llvm developers.

**Comment by alesapin** [comment]
Almost ok, let's wait for performance tests.

**Comment by alexey-milovidov** [comment]
But clang builds are not covered by performance tests.

**Comment by alesapin** [comment]
> But clang builds are not covered by performance tests.

I just changed the compiler for performance build from gcc-10 to clang-11. Report https://clickhouse-test-reports.s3.yandex.net/14846/a12521dd4d699b06244eec159b2a0b3cdf3450e8/performance_comparison/report.html#fail1

**Comment by alesapin** [comment]
Wait only for a performance build to be sure that it works with gcc-10.

**Comment by alesapin** [comment]
`01193_metadata_loading` :(

**Comment by alesapin** [comment]
Performance build with gcc-10, ok.

**Pull request merged**
