### PR TITLE
Fix `FunctionToSubcolumnsPass` in debug build

### PR DESCRIPTION
**Pull request by CurtizJ**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by CurtizJ** [comment]
It fails only in debug build but we don't have a check with it and analyzer

See https://s3.amazonaws.com/clickhouse-test-reports/0/72b0fed4ef941170e7c94e354f42ca084c625780/fuzzer_astfuzzerdebug/report.html.

**Comment by robot-ch-test-poll2** [comment]
*This is an automated comment for commit 94bb9a171d3661a102aad32c0346073a2169b4b7 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/58930/94bb9a171d3661a102aad32c0346073a2169b4b7/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/58930/94bb9a171d3661a102aad32c0346073a2169b4b7/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
@CurtizJ, let's add a test. It will be effective when we enable analyzer.

**Comment by CurtizJ** [comment]
It's the test `02966_nested_offsets_subcolumn`. It fails with analyzer in debug build as is without fuzzer.

**Pull request merged**
