### PR TITLE
Fix build with Poco Redis

### PR DESCRIPTION
**Pull request by filimonov**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Non-significant (changelog entry is not needed)

Was getting that (Debug build, clang-8) 
```
[build] FAILED: dbms/src/Dictionaries/CMakeFiles/clickhouse_dictionaries.dir/RedisDictionarySource.cpp.o 
...
[build] ../../dbms/src/Dictionaries/RedisDictionarySource.cpp:38:14: fatal error: 'Poco/Redis/Array.h' file not found
[build] #    include <Poco/Redis/Array.h>
[build]              ^~~~~~~~~~~~~~~~~~~~
[build] 1 error generated.
```

### CODE REVIEW

**Comment by filimonov** [comment]
Not sure if needed. Maybe cmake cache cleanup helped.

**Comment by abyss7** [comment]
@filimonov did the cache clean-up actually help?

**Comment by alexey-milovidov** [comment]
Yes, the cache cleanup actually helps.

**Review by alexey-milovidov — APPROVED** [review]
The changes are unnecessarily but look good for consistency.

**Pull request merged**
