### PR TITLE
Materialized view support virtual column

### LINKED ISSUE #11210: Pass virtual column from inner table to materialized view
```
create table x engine=MergeTree ORDER BY tuple() as select * from numbers(100);
create materialized view x_mv engine=MergeTree ORDER BY tuple() as select * from x;
insert into x select * from numbers(100);
```

That works: 
```
select _part, count() from `.inner.x_mv` group by _part;

SELECT 
    _part, 
    count()
FROM `.inner.x_mv`
GROUP BY _part

┌─_part─────┬─count()─┐
│ all_1_1_0 │     100 │
└───────────┴─────────┘

1 rows in set. Elapsed: 0.004 sec.
```

That - not:
```
select _part, count() from x_mv group by _part;
Received exception from server (version 20.5.1):
Code: 47. DB::Exception: Received from localhost:9000. DB::Exception: Missing columns: '_part' while processing query: 'SELECT _part, count() FROM x_mv GROUP BY _part', required columns: '_part', source columns: 'number'. 

```

### PR DESCRIPTION
**Pull request by zhongyuankai**
Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Implement Materialized view `getVirtuals` function. Close #11210

### CODE REVIEW

**Comment by kitaisreal** [comment]
@zhongyuankai looks good. Could you please add test and fix style check then we can merge.

**Comment by zhongyuankai** [comment]
> @zhongyuankai looks good. Could you please add test and fix style check then we can merge.

@kitaisreal Can you help me see how to fix this test failure problem？

**Comment by kitaisreal** [comment]
@zhongyuankai yes, modified test, seems like there we problems for parallel run because of database creation. For each stateless test database is created implicitly.

**Comment by zhongyuankai** [comment]
> @zhongyuankai yes, modified test, seems like there we problems for parallel run because of database creation. For each stateless test database is created implicitly.

Thank you very much, it seems that there is a new problem that is causing the test to fail.

**Comment by kitaisreal** [comment]
@zhongyuankai it looks like our CI issue

**Comment by kitaisreal** [comment]
@Mergifyio update

**Pull request merged**
