### PR TITLE
Fix query start time on non initial queries

### LINKED ISSUE #59608: query_log.query_start_time represents the query start time on the initiator
It seems that for a distributed query shards record into `query_log` the event time from the initiator as the start time of the query, not the time when they received the request and started their own query.
As a result the start time for the local query is lost.
I expect shards to record their own timestamps as the initial stage of a distributed query can be quite long (the initiator might need to prepare a dataset to send with the query, for example).

```
query_id                             | type        | event_time_microseconds    | query_start_time_microseconds | query_duration_ms | is_initial_query | initial_query_id                    
-------------------------------------+-------------+----------------------------+-------------------------------+-------------------+------------------+-------------------------------------
b1c37b4c-3ef3-4026-8888-8facba026268 | QueryStart  | 2024-02-05 14:54:01.083110 | 2024-02-05 14:54:01.083110    |                 0 |                1 | b1c37b4c-3ef3-4026-8888-8facba026268
bec13910-2293-4226-bb2f-64cbac3b38a1 | QueryStart  | 2024-02-05 14:54:01.083110 | 2024-02-05 14:54:01.083110    |                 0 |                0 | b1c37b4c-3ef3-4026-8888-8facba026268
bec13910-2293-4226-bb2f-64cbac3b38a1 | QueryFinish | 2024-02-05 14:54:01.114439 | 2024-02-05 14:54:01.083110    |                 5 |                0 | b1c37b4c-3ef3-4026-8888-8facba026268
```

Logs on the initiator:
```
2024.02.05 14:54:01.083613 [ 2346057 ] {b1c37b4c-3ef3-4026-8888-8facba026268} <Debug> executeQuery: (from [::1]:37336)
...
2024.02.05 14:54:01.108058 [ 1700466 ] {b1c37b4c-3ef3-4026-8888-8facba026268} <Debug> Connection (host4:9000): Sent data for 2 scalars, total 2 rows in 6.429e-05 sec., 30901 rows/sec., 68.00 B (1.00 MiB/sec.), compressed 0.4594594594594595 times to148.00 B (2.18 MiB/sec.)
...
```

Logs on the shard
```
2024.02.05 14:54:01.108337 [ 3870854 ] {} <Trace> TCP-Session: cd600915-61d7-44d6-9d1c-db9be227c9c8 Creating query context from session context, user_id: 94309d50-4f52-5250-31bd-74fecac179db, parent context user: default
2024.02.05 14:54:01.108636 [ 3870854 ] {bec13910-2293-4226-bb2f-64cbac3b38a1} <Debug> executeQuery: (from [::ffff:10.246.128.9]:40804, initial_query_id: b1c37b4c-3ef3-4026-8888-8facba026268)
...
2024.02.05 14:54:01.114457 [ 3870854 ] {bec13910-2293-4226-bb2f-64cbac3b38a1} <Debug> executeQuery: Read 48407 rows, 553.28 KiB in 0.005984 sec., 8089405.080213904 rows/sec., 90.29 MiB/sec.
2024.02.05 14:54:01.114567 [ 3870854 ] {bec13910-2293-4226-bb2f-64cbac3b38a1} <Trace> HashJoin: Join data is being destroyed, 524288 bytes and 4375 rows in hash table
2024.02.05 14:54:01.114597 [ 3870854 ] {bec13910-2293-4226-bb2f-64cbac3b38a1} <Debug> MemoryTracker: Peak memory usage (for query): 725.65 KiB.
2024.02.05 14:54:01.114601 [ 3870854 ] {bec13910-2293-4226-bb2f-64cbac3b38a1} <Debug> TCPHandler: Processed in 0.00642317 sec.
```

It wasn't always like that. Here is an example from 22.8:
```
revision | type        | event_time_microseconds    | query_start_time_microseconds | query_id                             | initial_query_id                    
---------+-------------+----------------------------+-------------------------------+--------------------------------------+-------------------------------------
   54465 | QueryStart  | 2022-09-28 14:12:24.652869 | 2022-09-28 14:12:24.652869    | caa41952-ba5e-4b16-b02f-9c4a7a1cab15 | caa41952-ba5e-4b16-b02f-9c4a7a1cab15
   54465 | QueryFinish | 2022-09-28 14:12:25.153177 | 2022-09-28 14:12:24.652869    | caa41952-ba5e-4b16-b02f-9c4a7a1cab15 | caa41952-ba5e-4b16-b02f-9c4a7a1cab15
   54465 | QueryStart  | 2022-09-28 14:12:24.693056 | 2022-09-28 14:12:24.693056    | 5cf6d587-53e7-49f3-8317-5069048ff4e4 | caa41952-ba5e-4b16-b02f-9c4a7a1cab15
   54465 | QueryFinish | 2022-09-28 14:12:24.821581 | 2022-09-28 14:12:24.693056    | 5cf6d587-53e7-49f3-8317-5069048ff4e4 | caa41952-ba5e-4b16-b02f-9c4a7a1cab15
   54465 | QueryStart  | 2022-09-28 14:12:24.693617 | 2022-09-28 14:12:24.693617    | dcc4e39b-348c-443c-af23-4963f1e54b00 | caa41952-ba5e-4b16-b02f-9c4a7a1cab15
   54465 | QueryFinish | 2022-09-28 14:12:24.807704 | 2022-09-28 14:12:24.693617    | dcc4e39b-348c-443c-af23-4963f1e54b00 | caa41952-ba5e-4b16-b02f-9c4a7a1cab15
   54465 | QueryStart  | 2022-09-28 14:12:24.694179 | 2022-09-28 14:12:24.694179    | 1451941c-59a2-4915-b08f-fd36bf4e81fb | caa41952-ba5e-4b16-b02f-9c4a7a1cab15
   54465 | QueryFinish | 2022-09-28 14:12:25.151079 | 2022-09-28 14:12:24.694179    | 1451941c-59a2-4915-b08f-fd36bf4e81fb | caa41952-ba5e-4b16-b02f-9c4a7a1cab15
   54465 | QueryStart  | 2022-09-28 14:12:24.695337 | 2022-09-28 14:12:24.695337    | 34f1f6f4-3f24-4dc0-9549-97164c446176 | caa41952-ba5e-4b16-b02f-9c4a7a1cab15
   54465 | QueryFinish | 2022-09-28 14:12:24.810671 | 2022-09-28 14:12:24.695337    | 34f1f6f4-3f24-4dc0-9549-97164c446176 | caa41952-ba5e-4b16-b02f-9c4a7a1cab15
   54465 | QueryStart  | 2022-09-28 14:12:24.695458 | 2022-09-28 14:12:24.695458    | 3506703c-2445-4ba8-b13c-325f58280488 | caa41952-ba5e-4b16-b02f-9c4a7a1cab15
   54465 | QueryFinish | 2022-09-28 14:12:24.775568 | 2022-09-28 14:12:24.695458    | 3506703c-2445-4ba8-b13c-325f58280488 | caa41952-ba5e-4b16-b02f-9c4a7a1cab15
   54465 | QueryStart  | 2022-09-28 14:12:24.725217 | 2022-09-28 14:12:24.725217    | c0bf0038-c588-4dd5-aa1e-b2589918ce67 | caa41952-ba5e-4b16-b02f-9c4a7a1cab15
   54465 | QueryFinish | 2022-09-28 14:12:24.728257 | 2022-09-28 14:12:24.725217    | c0bf0038-c588-4dd5-aa1e-b2589918ce67 | caa41952-ba5e-4b16-b02f-9c4a7a1cab15
```

### PR DESCRIPTION
**Pull request by Algunenano**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
- Fix query start time on non initial queries

### Documentation entry for user-facing changes

Fixes https://github.com/ClickHouse/ClickHouse/issues/59608

### CODE REVIEW

**Comment by robot-ch-test-poll1** [comment]
*This is an automated comment for commit b43f90fce209351972fafd420e1b62d58159ba81 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/59662/b43f90fce209351972fafd420e1b62d58159ba81/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/59662/b43f90fce209351972fafd420e1b62d58159ba81/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Review by devcrafter — APPROVED** [review]

**Review by alexey-milovidov — APPROVED** [review]

**Comment by Algunenano** [comment]
02590_interserver_mode_client_info_initial_query_start_time is failing so either some people are expecting `initial_query_start_time_microseconds = query_start_time_microseconds` or the test itself was broken. @azat any clues?

Looking at flakiness of the added test

**Comment by Algunenano** [comment]
Failures:
* I removed 02590_interserver_mode_client_info_initial_query_start_time, pending @azat comments.
* AST fuzzer (ubsan) -> https://github.com/ClickHouse/ClickHouse/issues/59796
* Integration tests (tsan) [4/6] -> https://github.com/ClickHouse/ClickHouse/issues/59631
* Stateful tests (debug) -> Error when fetching from s3
* Stateless tests (release, analyzer) -> Broken in master, fixed in https://github.com/ClickHouse/ClickHouse/pull/59741

**Comment by azat** [comment]
> 02590_interserver_mode_client_info_initial_query_start_time is failing so either some people are expecting initial_query_start_time_microseconds = query_start_time_microseconds or the test itself was broken. @azat any clues?

The test was incorrect, I've resubmit it without this assumption - https://github.com/ClickHouse/ClickHouse/pull/59851

**Pull request merged**
