### PR TITLE
tests: drop existing view in test_materialized_mysql_database

### PR DESCRIPTION
**Pull request by azat**
This is part of **"Why my PR is not merged?"** patch set series.

This should avoid failures of other tests in case of some previous test failed

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by robot-ch-test-poll2** [comment]
This is an automated comment for commit f7551fae3af007c473b0770079c260f4c012ad34 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/52103/f7551fae3af007c473b0770079c260f4c012ad34/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Comment by azat** [comment]
Good catch, mislooked, thank you. The problem was in the view.

**Comment by alexey-milovidov** [comment]
@azat, apparently, we don't have the support for `DROP VIEW ... IF EXISTS`. Please add it in another PR.

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
I've updated a query, now it should be ok.

**Comment by azat** [comment]
>Integration tests (tsan) [1/6] — fail: 2, passed: 356, flaky: 0

```
minio1_1    | WARNING: Console endpoint is listening on a dynamic port (32911), please use --console-address ":PORT" to choose a static port.
minio1_1    | ERROR Unable to initialize console server: Specified port is already in use
minio1_1    |       > Please ensure no other program uses the same address/port
```

**Pull request merged**
