### PR TITLE
Drop RESTART REPLICAS from stateless tests to avoid locking lots of mutexes

### PR DESCRIPTION
**Pull request by azat**
Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Drop RESTART REPLICAS from stateless tests to avoid locking lots of mutexes

Under TSan you can lock only not more then 64 mutexes from one thread at
once [1] [2], while RESTART REPLICAS can acquire more (it depends on the
number of replicated tables).

  [1]: https://github.com/google/sanitizers/issues/950#issuecomment-386711603
  [2]: https://github.com/llvm/llvm-project/blob/b02eab9058e58782fca32dd8b1e53c27ed93f866/compiler-rt/lib/sanitizer_common/sanitizer_deadlock_detector.h#L67

And since stress tests run tests in parallel, you can have more then 64
ReplicatedMergeTree tables at once (even though it is unlikely).

Fix this by using RESTART REPLICA table over RESTART REPLICAS.

And also add a smoke test for `SYSTEM RESTART REPLICAS`

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
> test_testkeeper_back_to_back

@alesapin What's wrong?

**Comment by alesapin** [comment]
> > test_testkeeper_back_to_back
> 
> @alesapin What's wrong?

Suspicious.

**Comment by alesapin** [comment]
```
2021.01.10 14:10:29.190107 [ 8 ] {} <Information> Application: Listening for connections to fake zookeeper (tcp): 0.0.0.0:9181
2021.01.10 14:10:29.300407 [ 10 ] {} <Trace> TestKeeperTCPHandlerFactory: Test keeper request. Address: 172.18.0.1:59556
2021.01.10 14:10:29.301208 [ 10 ] {} <Debug> TestKeeperTCPHandler: Received close request for session #0
2021.01.10 14:10:29.301304 [ 10 ] {} <Debug> TestKeeperTCPHandler: Sent close for session #0
2021.01.10 14:10:29.302137 [ 10 ] {} <Trace> TestKeeperTCPHandlerFactory: Test keeper request. Address: 172.18.0.1:59558
2021.01.10 14:10:29.361654 [ 8 ] {} <Information> Application: Listening for MySQL compatibility protocol: 0.0.0.0:9004
2021.01.10 14:10:29.362069 [ 11 ] {} <Trace> TCPHandlerFactory: TCP Request. Address: 172.18.0.1:57028
<...>
2021.01.10 14:10:29.362237 [ 11 ] {} <Information> TCPHandler: Client has not sent any data.
2021.01.10 14:10:29.362250 [ 11 ] {} <Debug> TCPHandler: Done processing connection.
2021.01.10 14:10:59.303377 [ 10 ] {} <Debug> TestKeeperTCPHandler: Session #1 expired
```
???

**Comment by alesapin** [comment]
These changes useful and don't related to the failure. Will investigate separately.

**Pull request merged**
