### PR TITLE
Add new commands BACKUP and RESTORE (part 1)

### PR DESCRIPTION
**Pull request by vitlibar**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category:
- New Feature

Changelog entry:
Added new commands BACKUP and RESTORE.

---

EARLY STAGE (NOT READY FOR PRODUCTION)

### CODE REVIEW

**Comment by vitlibar** [comment]
Failures:
[Functional stateless tests (thread)](https://clickhouse-test-reports.s3.yandex.net/21945/63e8bc1f203efe86ed24f8a1e8e8223ca7de21fb/functional_stateless_tests_(thread).html#fail1):

```
00489_pk_subexpression:
Limit for rows (controlled by 'max_rows_to_read' setting) exceeded, max rows: 5.00, current rows: 6.00. (TOO_MANY_ROWS)
```

[Integration tests](https://clickhouse-test-reports.s3.yandex.net/21945/63e8bc1f203efe86ed24f8a1e8e8223ca7de21fb/integration_tests_(release).html#fail1):

```
test_dictionaries_all_layouts_separate_sources/test_cassandra.py:
AttributeError: 'backports.zoneinfo.ZoneInfo' object has no attribute 'localize'
```

are not related to this PR.

**Comment by DipalPrajapati** [comment]
Where can I find this backup and restore commands?

**Comment by Slach** [comment]
@DipalPrajapati 
it will be available when 21.10 released as stable
you can try to use a testing package repostitory
look to https://clickhouse.tech/docs/en/getting-started/install/
and replace "stable" to "testing"
or try to download packages from https://github.com/ClickHouse/ClickHouse/releases/

**Comment by vitlibar** [comment]
> Where can I find this backup and restore commands?

This feature is in early stage, it's not recommended for production use yet.

**Pull request merged**
