### PR TITLE
Fix docker entrypoint in case http_port is not in the config

### PR DESCRIPTION
**Pull request by devwout**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Fix docker entrypoint in case `http_port` is not in the config.

...

Detailed description / Documentation draft:

...

By adding documentation, you'll allow users to try your new feature immediately, not when someone else will have time to document it later. Documentation is necessary for all features that affect user experience in any way. You can add brief documentation draft above, or add documentation right into your patch as Markdown files in [docs](https://github.com/ClickHouse/ClickHouse/tree/master/docs) folder.

If you are doing this for the first time, it's recommended to read the lightweight [Contributing to ClickHouse Documentation](https://github.com/ClickHouse/ClickHouse/tree/master/docs/README.md) guide first.

Information about CI checks: https://clickhouse.tech/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by filimonov** [comment]
Vs https://github.com/ClickHouse/ClickHouse/pull/22102 ?

**Comment by devwout** [comment]
> Vs #22102 ?

Seems I went straight for the fix instead of checking the bug reports and open PRs :see_no_evil: . If the other PR is preferred, I can trim it down to only solve the problem with missing `http_port`.

**Comment by devwout** [comment]
Reduced the PR to only contain the fix for config without `http_port`.

**Review by alesapin — APPROVED** [review]
Ok, this fix doesn't change a lot but also doesn't break anything.

**Comment by alesapin** [comment]
Tests not required.

**Pull request merged**
