### PR TITLE
Fix distributed IN without database on initiator

### PR DESCRIPTION
**Pull request by 4ertus2**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix 'Database <db> doesn't exist.' in queries with IN and Distributed table when there's no database on initiator.

### CODE REVIEW

**Comment by 4ertus2** [comment]
`DB::Exception: Database test doesn't exist.` in python live view tests.

**Comment by 4ertus2** [comment]
An issue for fuzzer error #15623

**Comment by 4ertus2** [comment]
There's `helpers.uexpect.ExpectTimeoutError: Timeout 20.000s` error in integration test TestLiveViewOverDistributedSuite.
There's no IN or JOIN in test queries, so PR should not affect the test.

**Comment by alexey-milovidov** [comment]
We no longer support this case. But why did we have to support it in the first place?
There are no references.

**Pull request merged**
