### PR TITLE
Reorganize contrib/ IDE folders

### PR DESCRIPTION
**Pull request by traceon**
Changelog category:
- Not for changelog (changelog entry is not required)

Detailed description:
- Apply custom `FOLDER` property assignment/fixup for targets under `contrib/`, so that there is no more irrelevant targets on the front line.

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
```
Oct 15 20:28:28 CMake Error: The inter-target dependency graph contains the following strongly connected component (cycle):
Oct 15 20:28:28   "cxxabi" of type SHARED_LIBRARY
Oct 15 20:28:28     depends on "cxx" (weak)
Oct 15 20:28:28     depends on "unwind" (weak)
Oct 15 20:28:28   "cxx" of type SHARED_LIBRARY
Oct 15 20:28:28     depends on "cxxabi" (weak)
Oct 15 20:28:28     depends on "unwind" (weak)
Oct 15 20:28:28   "unwind" of type SHARED_LIBRARY
Oct 15 20:28:28     depends on "cxx" (weak)
Oct 15 20:28:28     depends on "cxxabi" (weak)
Oct 15 20:28:28 At least one of these targets is not a STATIC_LIBRARY.  Cyclic dependencies are allowed only among static libraries.
```

**Comment by traceon** [comment]
Is this dependency graph actually correct though?

**Comment by alexey-milovidov** [comment]
cxx depends on cxxabi,
cxxabi depends on libunwind

**Comment by traceon** [comment]
@Mergifyio update

**Review by alexey-milovidov — APPROVED** [review]

**Pull request merged**
