### PR TITLE
S3: Do not match directory itself with trailing wildcard

### PR DESCRIPTION
**Pull request by cwurm**
When reading from S3 with a trailing wildcard, ClickHouse will often fail to read the correct data (see examples below). The reason is that when a path ends in `/*`, the first match will be the directory itself and not the first file. This causes all kinds of problems further up the code.

This PR fixes it by only matching objects with a filename that is not empty. 

I was thinking of writing an integration test for this, but I'm doing my development on macOS, and the integration tests don't run there. I could probably get this all set up on a VM, but I'm not sure how much time that would take, and this is a pretty simple fix.

### Example queries (before)
Here, it returns 0 rows and no error (it works without the LIMIT but will eventually also throw an error):
```sql
SELECT *
FROM s3('https://clickhouse-public-datasets.s3.amazonaws.com/wikistat/**/*', NOSIGN)
LIMIT 1

Query id: 57d81ccb-4ba9-40b3-989a-8253f9c37c9b

Ok.

0 rows in set. Elapsed: 8.357 sec.
```

Here, it returns an error but doesn't read the data it could:
```sql
SELECT *
FROM s3('https://datasets-documentation.s3.eu-west-3.amazonaws.com/amazon_reviews/*', NOSIGN)
LIMIT 1

Query id: 7a4c5505-94dd-41df-ac9a-ed45cb6909cb


Elapsed: 0.345 sec.

Received exception:
Code: 499. DB::Exception: Failed to get object info: No response body.. HTTP response code: 403: The data format cannot be detected by the contents of the files. You can specify the format manually: (in file/uri amazon_reviews/). (S3_ERROR)
```

### Example queries (after)
```sql
SELECT *
FROM s3('https://clickhouse-public-datasets.s3.amazonaws.com/wikistat/**/*', NOSIGN)
LIMIT 1

Query id: b9005894-29a9-4f07-a0b3-ffa0c79068d5

   ┌─c1────────────────┐
1. │ aa Main_Page 12 0 │
   └───────────────────┘

1 row in set. Elapsed: 8.809 sec.
```

```sql
SELECT *
FROM s3('https://datasets-documentation.s3.eu-west-3.amazonaws.com/amazon_reviews/*', NOSIGN)
LIMIT 1

Query id: 820c9c5b-4bad-4ff6-9328-3d094d1a011f

   ┌─review_date─┬─marketplace─┬─customer_id─┬─review_id─────┬─product_id─┬─product_parent─┬─product_title────────────────────────────────────────────┬─product_category─┬─star_rating─┬─helpful_votes─┬─total_votes─┬─vine──┬─verified_purchase─┬─review_headline─┬─review_body────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
1. │        9305 │ US          │    53096571 │ RHL4UW17ZK72A │ 0521314925 │      980601331 │ Invention and Evolution:Design in Nature and Engineering │ Books            │           5 │             9 │           9 │ false │ false             │ BUY THIS BOOK!  │ This is a beautiful book.  French talks about energy, form, mechanism, and economy in natural and man-made things.  He compares birds to planes in terms of fuel-capacity, energy  conversion efficiency, drag, etc.  He compares suspension   bridges and dinosaurs.  He provides examples of neat   inventions and the thought that has gone into them (every-  thing from steam-catapults to toy cars to grommets).  This  is &quot;How Things Work&quot; for the non-moron crowd. │
   └─────────────┴─────────────┴─────────────┴───────────────┴────────────┴────────────────┴──────────────────────────────────────────────────────────┴──────────────────┴─────────────┴───────────────┴─────────────┴───────┴───────────────────┴─────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

1 row in set. Elapsed: 4.771 sec.
```

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix reading files from a path in object storage with a trailing wildcard.

### CODE REVIEW

**Comment by robot-ch-test-poll3** [comment]
*This is an automated comment for commit 97fdd330cf3ee518f672a35f9281d9b3dfae6590 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/72007/97fdd330cf3ee518f672a35f9281d9b3dfae6590/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/8d4cc787fe4e8276163864da1be9a1434fa6532f/docs_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Comment by nickitat** [comment]
pls see if it is fixed by https://github.com/ClickHouse/ClickHouse/pull/71947

**Comment by cwurm** [comment]
> pls see if it is fixed by #71947

I initially considered changing that code as well, but it only fixes one of the situations. With the changes in #71947:
```sql
:) SELECT *
FROM s3('https://clickhouse-public-datasets.s3.amazonaws.com/wikistat/**/*', NOSIGN)
LIMIT 1

SELECT *
FROM s3('https://clickhouse-public-datasets.s3.amazonaws.com/wikistat/**/*', NOSIGN)
LIMIT 1

Query id: 833051d1-c330-4486-a37b-773a5ae17ed7

   ┌─c1────────────────┐
1. │ aa Main_Page 12 0 │
   └───────────────────┘

1 row in set. Elapsed: 9.191 sec.

:) SELECT *
FROM s3('https://datasets-documentation.s3.eu-west-3.amazonaws.com/amazon_reviews/*', NOSIGN)
LIMIT 1

SELECT *
FROM s3('https://datasets-documentation.s3.eu-west-3.amazonaws.com/amazon_reviews/*', NOSIGN)
LIMIT 1

Query id: ae130997-7146-49b6-a657-a18b547537b9


Elapsed: 0.172 sec.

Received exception:
Code: 499. DB::Exception: Failed to get object info: No response body.. HTTP response code: 403: The data format cannot be detected by the contents of the files. You can specify the format manually: (in file/uri amazon_reviews/). (S3_ERROR)
```

**Comment by nickitat** [comment]
> > pls see if it is fixed by #71947
> 
> I initially considered changing that code as well, but it only fixes one of the situations. With the changes in #71947:
> 
> ```sql
> :) SELECT *
> FROM s3('https://clickhouse-public-datasets.s3.amazonaws.com/wikistat/**/*', NOSIGN)
> LIMIT 1
> 
> SELECT *
> FROM s3('https://clickhouse-public-datasets.s3.amazonaws.com/wikistat/**/*', NOSIGN)
> LIMIT 1
> 
> Query id: 833051d1-c330-4486-a37b-773a5ae17ed7
> 
>    ┌─c1────────────────┐
> 1. │ aa Main_Page 12 0 │
>    └───────────────────┘
> 
> 1 row in set. Elapsed: 9.191 sec.
> 
> :) SELECT *
> FROM s3('https://datasets-documentation.s3.eu-west-3.amazonaws.com/amazon_reviews/*', NOSIGN)
> LIMIT 1
> 
> SELECT *
> FROM s3('https://datasets-documentation.s3.eu-west-3.amazonaws.com/amazon_reviews/*', NOSIGN)
> LIMIT 1
> 
> Query id: ae130997-7146-49b6-a657-a18b547537b9
> 
> 
> Elapsed: 0.172 sec.
> 
> Received exception:
> Code: 499. DB::Exception: Failed to get object info: No response body.. HTTP response code: 403: The data format cannot be detected by the contents of the files. You can specify the format manually: (in file/uri amazon_reviews/). (S3_ERROR)
> ```

how the structure of `amazon_reviews/` looks like?

**Comment by cwurm** [comment]
> how the structure of `amazon_reviews/` looks like?

Some Parquet files, plus the 0-byte directory entry that makes it trip:
```sql
$ aws s3 ls s3://datasets-documentation/amazon_reviews/ --no-sign-request
2023-10-27 18:00:05          0
2023-10-28 04:52:46  294651332 amazon_reviews_1990s.snappy.parquet
2023-10-28 04:52:46 8920514145 amazon_reviews_2000s.snappy.parquet
2023-10-28 06:26:47 2048074919 amazon_reviews_2010.snappy.parquet
2023-10-28 06:26:47 3013406813 amazon_reviews_2011.snappy.parquet
2023-10-28 06:26:47 4684779182 amazon_reviews_2012.snappy.parquet
2023-10-28 06:26:47 8816271385 amazon_reviews_2013.snappy.parquet
2023-10-28 06:26:47 11318656940 amazon_reviews_2014.snappy.parquet
2023-10-28 06:26:47 9272420157 amazon_reviews_2015.snappy.parquet
```

Now that I think about it, another way to make it work just with the changes in https://github.com/ClickHouse/ClickHouse/pull/71947 is to specify `s3_skip_empty_files`:
```sql
-- Only changes in #71947
SELECT *
FROM s3('https://datasets-documentation.s3.eu-west-3.amazonaws.com/amazon_reviews/*', NOSIGN)
LIMIT 1
SETTINGS s3_skip_empty_files = 1

Query id: b3192ba7-daac-45b2-8ce8-d0fd9ccf3091

   ┌─review_date─┬─marketplace─┬─customer_id─┬─review_id─────┬─product_id─┬─product_parent─┬─product_title────────────────────────────────────────────┬─product_category─┬─star_rating─┬─helpful_votes─┬─total_votes─┬─vine──┬─verified_purchase─┬─review_headline─┬─review_body────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
1. │        9305 │ US          │    53096571 │ RHL4UW17ZK72A │ 0521314925 │      980601331 │ Invention and Evolution:Design in Nature and Engineering │ Books            │           5 │             9 │           9 │ false │ false             │ BUY THIS BOOK!  │ This is a beautiful book.  French talks about energy, form, mechanism, and economy in natural and man-made things.  He compares birds to planes in terms of fuel-capacity, energy  conversion efficiency, drag, etc.  He compares suspension   bridges and dinosaurs.  He provides examples of neat   inventions and the thought that has gone into them (every-  thing from steam-catapults to toy cars to grommets).  This  is &quot;How Things Work&quot; for the non-moron crowd. │
   └─────────────┴─────────────┴─────────────┴───────────────┴────────────┴────────────────┴──────────────────────────────────────────────────────────┴──────────────────┴─────────────┴───────────────┴─────────────┴───────┴───────────────────┴─────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

1 row in set. Elapsed: 4.767 sec.
```

But it feels like bad UX to require a setting for skipping empty files to read a directory with no empty files. Of course, the whole reason this is so messed up is that S3 technically doesn't have directories - it's just a [naming convention](https://docs.aws.amazon.com/AmazonS3/latest/userguide/using-folders.html). However, it's a pretty strong one - the web consoles of both AWS S3 and GCS don't even show these paths with empty file names (even when they have content and are not 0-byte).

**Comment by nickitat** [comment]
> > how the structure of `amazon_reviews/` looks like?
> 
> Some Parquet files, plus the 0-byte directory entry that makes it trip:
> 
> ```sql
> $ aws s3 ls s3://datasets-documentation/amazon_reviews/ --no-sign-request
> 2023-10-27 18:00:05          0
> 2023-10-28 04:52:46  294651332 amazon_reviews_1990s.snappy.parquet
> 2023-10-28 04:52:46 8920514145 amazon_reviews_2000s.snappy.parquet
> 2023-10-28 06:26:47 2048074919 amazon_reviews_2010.snappy.parquet
> 2023-10-28 06:26:47 3013406813 amazon_reviews_2011.snappy.parquet
> 2023-10-28 06:26:47 4684779182 amazon_reviews_2012.snappy.parquet
> 2023-10-28 06:26:47 8816271385 amazon_reviews_2013.snappy.parquet
> 2023-10-28 06:26:47 11318656940 amazon_reviews_2014.snappy.parquet
> 2023-10-28 06:26:47 9272420157 amazon_reviews_2015.snappy.parquet
> ```
> 
> Now that I think about it, another way to make it work just with the changes in #71947 is to specify `s3_skip_empty_files`:
> 
> ```sql
> -- Only changes in #71947
> SELECT *
> FROM s3('https://datasets-documentation.s3.eu-west-3.amazonaws.com/amazon_reviews/*', NOSIGN)
> LIMIT 1
> SETTINGS s3_skip_empty_files = 1
> 
> Query id: b3192ba7-daac-45b2-8ce8-d0fd9ccf3091
> 
>    ┌─review_date─┬─marketplace─┬─customer_id─┬─review_id─────┬─product_id─┬─product_parent─┬─product_title────────────────────────────────────────────┬─product_category─┬─star_rating─┬─helpful_votes─┬─total_votes─┬─vine──┬─verified_purchase─┬─review_headline─┬─review_body────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
> 1. │        9305 │ US          │    53096571 │ RHL4UW17ZK72A │ 0521314925 │      980601331 │ Invention and Evolution:Design in Nature and Engineering │ Books            │           5 │             9 │           9 │ false │ false             │ BUY THIS BOOK!  │ This is a beautiful book.  French talks about energy, form, mechanism, and economy in natural and man-made things.  He compares birds to planes in terms of fuel-capacity, energy  conversion efficiency, drag, etc.  He compares suspension   bridges and dinosaurs.  He provides examples of neat   inventions and the thought that has gone into them (every-  thing from steam-catapults to toy cars to grommets).  This  is &quot;How Things Work&quot; for the non-moron crowd. │
>    └─────────────┴─────────────┴─────────────┴───────────────┴────────────┴────────────────┴──────────────────────────────────────────────────────────┴──────────────────┴─────────────┴───────────────┴─────────────┴───────┴───────────────────┴─────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
> 
> 1 row in set. Elapsed: 4.767 sec.
> ```
> 
> But it feels like bad UX to require a setting for skipping empty files to read a directory with no empty files. Of course, the whole reason this is so messed up is that S3 technically doesn't have directories - it's just a [naming convention](https://docs.aws.amazon.com/AmazonS3/latest/userguide/using-folders.html). However, it's a pretty strong one - the web consoles of both AWS S3 and GCS don't even show these paths with empty file names (even when they have content and are not 0-byte).

then i'd say that our behaviour is correct since this empty file exists. if it won't be empty we'd extract schema from it and successfully read, but we obviously cannot do it.

**Comment by cwurm** [comment]
> then i'd say that our behaviour is correct since this empty file exists. if it wouldn't be empty we'd extract schema from it and successfully read, but we obviously cannot do it.

Technically, it's correct, but is it the right thing for users? The concept of directories in object storage is so common these days, and since any "directory files" are not even displayed in the cloud provider UIs (which is where people look first to check what's going on) there is no way for most users to even see the difference.

Maybe we should turn on `s3_skip_empty_files` by default? Because what's the point of reading empty files? (But see the example below for when even this wouldn't help.)

Or we could introduce another setting, could be either
- `s3_skip_empty_directory_files` that's `true` by default and skips any files in object storage where both `object_info->getFileName().empty()` and `object_info->metadata->size_bytes == 0` (but it won't help with the example below)

- `s3_skip_directory_files` that's `true` by default and skips any files where just `object_info->getFileName().empty()`

I'd like to see a good default user experience. In my testing I came across more than one folder (and I didn't test that many) that had these 0-byte entries that prevented reading of the actual files with just the default settings.

Here is probably the worst example I've come up with (based on the test in #71947):
```sql
INSERT INTO FUNCTION s3('<bucket>/test/', Parquet) SELECT ''; -- Parquet file with empty string as directory
INSERT INTO FUNCTION s3('<bucket>/test/file1', Parquet) SELECT 1 as num;
INSERT INTO FUNCTION s3('<bucket>/test/file2', Parquet) SELECT 2 as num;
INSERT INTO FUNCTION s3('<bucket>/test/file3', Parquet) SELECT 3 as num;

SELECT * FROM s3('<bucket>/test/*', Parquet) -- We specify Parquet format explicitly
SETTINGS s3_skip_empty_files = 1; -- We also skip empty files (but the first Parquet file is not empty, it has an empty string)

Query id: 18dbb549-eb78-4c0b-ab8d-81b48a003f52

   ┌─''─┐
1. │    │
   └────┘
   ┌─''───┐
2. │ ᴺᵁᴸᴸ │ -- ??
   └──────┘
   ┌─''───┐
3. │ ᴺᵁᴸᴸ │ -- ??
   └──────┘
   ┌─''───┐
4. │ ᴺᵁᴸᴸ │ -- ??
   └──────┘

4 rows in set. Elapsed: 0.834 sec.
```

The problem there is `schema_inference_mode`, and setting it to `union` gets better data. But I'd be surprised if many users could figure this out. It took me a while, and I stepped through the code with a debugger.

**Comment by CheSema** [comment]
I read the motivation.
Thanks that you explained it so verbose.

I agree with the author.
We need `s3_skip_directory_files` settings that should be `true` by default.

**Comment by cwurm** [comment]
Now that https://github.com/ClickHouse/ClickHouse/pull/71947 has changed the default of `s3_skip_empty_files` to `true`, both of the initial queries work with default settings so I'm closing this PR.

Any additional settings can be added in a new PR.

**Pull request closed without merging**
