### PR TITLE
Fix unmatched type comparison in KeyCondition

### LINKED ISSUE #17122: Table ORDER BY wrong "less" comparison with key Date column and DateTime value
**Describe the bug**
If we use WHERE clause with a condition in which we compare the Date column from table ORDER BY and DateTime value that can lead to wrong results for the certain date of DateTime value.

**How to reproduce**
Clickhouse version 20.12, 20.3.21, 20.8.6.6
```
CREATE TABLE test_index(date Date) ENGINE=MergeTree() PARTITION BY toYYYYMM(date) ORDER BY date;
INSERT INTO test_index VALUES('2020-10-30');
SELECT 1
FROM test_index
WHERE date < toDateTime('2020-10-30 06:00:00');

Query id: 2a5ff79c-a109-40be-b23c-7693a0918335

Ok.

0 rows in set. Elapsed: 0.002 sec.

SELECT 1
FROM test_index
WHERE materialize(date) < toDateTime('2020-10-30 06:00:00');

Query id: 807b6095-f26b-48f2-967f-0ad9d4d0471f

┌─1─┐
│ 1 │
└───┘

1 rows in set. Elapsed: 0.002 sec.
```

**Expected behavior**
Clickhouse returns consistent results for both queries.

### PR DESCRIPTION
**Pull request by amosbird**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Fix possible wrong index analysis when the types of the index comparison are different. This fixes https://github.com/ClickHouse/ClickHouse/issues/17122 

Detailed description / Documentation draft:

None.

### CODE REVIEW

**Comment by amosbird** [comment]
A dejavued unrelated test failure

```
2020-11-20 13:45:26 01247_optimize_distributed_group_by_sharding_key:                       [ FAIL ] 0.26 sec. - return code 101
2020-11-20 13:45:26 Received exception from server (version 20.12.1):
2020-11-20 13:45:26 Code: 101. DB::Exception: Received from localhost:9000. DB::Exception: Received from 127.0.0.2:9000. DB::Exception: Unexpected packet Data received from client. 
2020-11-20 13:45:26 
2020-11-20 13:45:26 , result:
2020-11-20 13:45:26 
2020-11-20 13:45:26 -
2020-11-20 13:45:26 0
2020-11-20 13:45:26 1
2020-11-20 13:45:26 0
2020-11-20 13:45:26 1
2020-11-20 13:45:26 optimize_skip_unused_shards
2020-11-20 13:45:26 0
2020-11-20 13:45:26 1
2020-11-20 13:45:26 0
2020-11-20 13:45:26 1
2020-11-20 13:45:26 GROUP BY number
2020-11-20 13:45:26 1	0
2020-11-20 13:45:26 1	1
2020-11-20 13:45:26 1	0
2020-11-20 13:45:26 1	1
2020-11-20 13:45:26 GROUP BY number distributed_group_by_no_merge
2020-11-20 13:45:26 1	0
2020-11-20 13:45:26 1	1
2020-11-20 13:45:26 1	0
2020-11-20 13:45:26 1	1
2020-11-20 13:45:26 GROUP BY number, 1
2020-11-20 13:45:26 1	0
2020-11-20 13:45:26 1	1
2020-11-20 13:45:26 1	0
2020-11-20 13:45:26 1	1
2020-11-20 13:45:26 GROUP BY 1
2020-11-20 13:45:26 4	0
2020-11-20 13:45:26 GROUP BY number ORDER BY number DESC
2020-11-20 13:45:26 1	1
2020-11-20 13:45:26 1	1
2020-11-20 13:45:26 1	0
2020-11-20 13:45:26 1	0
2020-11-20 13:45:26 GROUP BY toString(number)
2020-11-20 13:45:26 1	0
2020-11-20 13:45:26 1	1
2020-11-20 13:45:26 1	0
2020-11-20 13:45:26 1	1
2020-11-20 13:45:26 GROUP BY number%2
2020-11-20 13:45:26 2	0
2020-11-20 13:45:26 2	1
2020-11-20 13:45:26 countDistinct
2020-11-20 13:45:26 2
2020-11-20 13:45:26 countDistinct GROUP BY number
2020-11-20 13:45:26 1
2020-11-20 13:45:26 1
2020-11-20 13:45:26 1
2020-11-20 13:45:26 1
2020-11-20 13:45:26 DISTINCT
2020-11-20 13:45:26 0
2020-11-20 13:45:26 1
2020-11-20 13:45:26 0
2020-11-20 13:45:26 1
2020-11-20 13:45:26 HAVING
2020-11-20 13:45:26 HAVING LIMIT
2020-11-20 13:45:26 1	0
2020-11-20 13:45:26 LIMIT
2020-11-20 13:45:26 1	0
2020-11-20 13:45:26 
```

**Comment by alexey-milovidov** [comment]
> 01247_optimize_distributed_group_by_sharding_key

The fix is merged in https://github.com/ClickHouse/ClickHouse/pull/17254

**Comment by alexey-milovidov** [comment]
RabbitMQ test failure is also fixed.

**Comment by alexey-milovidov** [comment]
Maybe also add a test for getLeastSupertype?
It can be done with function `if` or array construction `toTypeName([x, y])`.

**Review by alexey-milovidov — APPROVED** [review]

**Pull request merged**
