### PR TITLE
Fixed UTF-8 string case-insensitive search when lowercase and uppercase characters are represented by different number of bytes.

### LINKED ISSUE #7334: Cannot use positionCaseInsensitiveUTF8() with "ß" letter
Hello,

**Describe the bug or unexpected behaviour**

Letter "ß" is part of german alphabet. Im not able to search for it using positionCaseInsensitiveUTF8() function. Function returns an error:

```
Code: 2. DB::Exception: Received from localhost:9000, 127.0.0.1. DB::Exception: UTF8 sequences with different lowercase and uppercase lengths are not supported.
```

**How to reproduce**

Examples, where I could not use that sign:

```
CREATE TABLE test2 ( d Date, test String ) ENGINE = MergeTree(d, d, d, 8192);
INSERT INTO test2 VALUES('2019/04/05', 'this is example ß test string');

SELECT * FROM test2 WHERE positionCaseInsensitiveUTF8(test, 'ß') != 0

Received exception from server (version 19.6.2):
Code: 2. DB::Exception: Received from localhost:9000, 127.0.0.1. DB::Exception: UTF8 sequences with different lowercase and uppercase lengths are not supported. 
```

Function positionUTF8 works fine

```
f45b09c5fb9a :) SELECT * FROM test2 WHERE positionUTF8(test, 'ß') != 0

SELECT *
FROM test2 
WHERE positionUTF8(test, 'ß') != 0

┌──────────d─┬─test──────────────────────────┐
│ 2019-04-05 │ this is example ß test string │
└────────────┴───────────────────────────────┘
```

Another example, where I could search for "ß":

```
SELECT positionCaseInsensitiveUTF8('test ß test', 'ß');

SELECT positionCaseInsensitiveUTF8('test ß test', 'ß')

┌─positionCaseInsensitiveUTF8('test ß test', 'ß')─┐
│                                               6 │
└─────────────────────────────────────────────────┘
```

**Which ClickHouse server version to use**

19.6.2.11, problem exists also on 19.13.5.44

**Expected behavior**

Position of this character in string

### PR DESCRIPTION
**Pull request by HarryLeeIBM**
Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fixed UTF-8 string case-insensitive search when lowercase and uppercase characters are represented by different number of bytes. Example is `ẞ` and `ß`. This closes #7334.

Detailed description:

This pull request is addressing [issue 7334](https://github.com/ClickHouse/ClickHouse/issues/7334):  Cannot use positionCaseInsensitiveUTF8() with "ß" letter.

In utf-8 case insensitive searching, if the needle contains characters which lowercase and uppercase have different sizes(Letter "ß" for example), the current algorithm (Volnitsky) and SSE code cannot handle this case. The fix provides a safe path which allows fallback code being executed.

The fix adds a boolean member ("force_fallback") in StringSearcherBase so that VolnitskyBase can pick it up to run fallback code. Also a fix has been added in compareTrivial() method to handle different sizes of lower/upper cases of same characters.

### CODE REVIEW

**Review by Avogar — APPROVED** [review]

**Comment by Avogar** [comment]
Cannot merge this PR, @HarryLeeIBM did you sign the CLA?

**Comment by HarryLeeIBM** [comment]
> Cannot merge this PR, @HarryLeeIBM did you sign the CLA?

@Avogar , Yes I signed the CLA. Do we need to sign for later commits? I didn't see any links for signing CLA when I added another commit.

**Comment by Avogar** [comment]
It seems there are some problems with license/cla check, let's rerun tests

**Comment by Avogar** [comment]
@Mergifyio update

**Comment by alexey-milovidov** [comment]
It does not affect stability or security and it is just an improvement over existing behaviour.
It's pointless to backport in my opinion. Version 21.3 contains much more annoyances comparing to this.

**Pull request merged**
