### PR TITLE
Bypass `Poco::BasicBufferedStreamBuf` in `ReadBufferFromIStream`

### PR DESCRIPTION
**Pull request by nickitat**
### Changelog category (leave one):
- Performance Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Bypass `Poco::BasicBufferedStreamBuf` abstraction when reading from S3 (namely  `ReadBufferFromIStream`) to avoid extra copying of data.

### CODE REVIEW

**Comment by robot-ch-test-poll2** [comment]
*This is an automated comment for commit d353820028bae82776579a4d4f273b2973d3467b with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/56961/d353820028bae82776579a4d4f273b2973d3467b/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td><a href="https://github.com/ClickHouse/ClickHouse/actions/runs/6916786701">✅ success</a></td></tr>
<tbody>
</table>
</details>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/56961/d353820028bae82776579a4d4f273b2973d3467b/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Comment by nickitat** [comment]
here is how it works. data is being copied through `_pBuffer` inside `BasicBufferedStreamBuf`. it is small time of course compared to netw latency, but still something that would be good to avoid IMO.

Untitled-2023-11-17-2013-2

**Comment by alexey-milovidov** [comment]
Let's also merge this: https://github.com/ClickHouse/ClickHouse/pull/56064
Maybe we will get rid of iostreams entirely.

**Review by alexey-milovidov — APPROVED** [review]
This looks perfect!

**Comment by CheSema** [comment]
Btw. How are  the changes related to deleted unit test `TEST_F(WBS3Test, ReadBeyondLastOffset)`?

**Comment by nickitat** [comment]
> Btw. How are the changes related to deleted unit test `TEST_F(WBS3Test, ReadBeyondLastOffset)`?

[this cast](https://github.com/ClickHouse/ClickHouse/pull/56961/files#diff-9739b4e18e778eeb494907ca3becf20c55e067a65b660923dbdf0972b7955df2R53) failed and to preserve the test I'd have to make it test some artificially introduced code path inside ReadBufferFromS3.

**Pull request merged**
