### PR TITLE
Cherry pick #65090 to 23.8: Fix INTERPOLATE (alias) for remote queries with analyzer.

### PR DESCRIPTION
**Pull request by robot-ch-test-poll2**
Original pull-request #65090

This pull-request is a first step of an automated backporting.
It contains changes similar to calling `git cherry-pick` locally.
If you intend to continue backporting the changes, then resolve all conflicts if any.
Otherwise, if you do not want to backport them, then just close this pull-request.

The check results does not matter at this step - you can safely ignore them.

### Note

This pull-request will be merged automatically. Please, **do not merge it manually** (but if you accidentally did, nothing bad will happen).

#### If the PR was manually reopened after being closed

If this PR is stuck (i.e. not automatically merged after one day), check https://github.com/ClickHouse/ClickHouse/pull/65090 for `pr-backports-created` *label* and delete it.

Manually merging will do nothing. The `pr-backports-created` *label* prevents the original PR https://github.com/ClickHouse/ClickHouse/pull/65090 from being processed.

#### If the conflicts were resolved in a wrong way

If this cherry-pick PR is completely screwed by a wrong conflicts resolution, and you want to recreate it:

- delete the `pr-cherrypick` label from the PR
- delete this branch from the repository

You also need to check the original PR https://github.com/ClickHouse/ClickHouse/pull/65090 for `pr-backports-created`, and delete if it's presented there

### CODE REVIEW

**Comment by robot-clickhouse-ci-2** [comment]
Dear @devcrafter, @KochetovNicolai, the PR is not updated for 1d24h0m59s. Please, either resolve the conflicts, or close it to finish the backport process of #65090

**Comment by robot-clickhouse** [comment]
Dear @devcrafter, @KochetovNicolai, the PR is not updated for 1d24h0m27s. Please, either resolve the conflicts, or close it to finish the backport process of #65090

**Comment by robot-ch-test-poll3** [comment]
Dear @devcrafter, @KochetovNicolai, the PR is not updated for 1d25h0m37s. Please, either resolve the conflicts, or close it to finish the backport process of #65090

**Comment by robot-clickhouse** [comment]
Dear @devcrafter, @KochetovNicolai, the PR is not updated for 1d25h1m58s. Please, either resolve the conflicts, or close it to finish the backport process of #65090

**Comment by robot-ch-test-poll** [comment]
Dear @devcrafter, @KochetovNicolai, the PR is not updated for 1d24h58m5s. Please, either resolve the conflicts, or close it to finish the backport process of #65090

**Comment by robot-ch-test-poll1** [comment]
Dear @devcrafter, @KochetovNicolai, the PR is not updated for 1d24h58m40s. Please, either resolve the conflicts, or close it to finish the backport process of #65090

**Comment by robot-clickhouse** [comment]
Dear @devcrafter, @KochetovNicolai, the PR is not updated for 1d24h5m16s. Please, either resolve the conflicts, or close it to finish the backport process of #65090

**Comment by robot-clickhouse-ci-1** [comment]
Dear @devcrafter, @KochetovNicolai, the PR is not updated for 1d24h54m9s. Please, either resolve the conflicts, or close it to finish the backport process of #65090

**Comment by robot-ch-test-poll** [comment]
Dear @devcrafter, @KochetovNicolai, the PR is not updated for 1d24h0m0s. Please, either resolve the conflicts, or close it to finish the backport process of #65090

**Comment by robot-ch-test-poll** [comment]
Dear @devcrafter, @KochetovNicolai, the PR is not updated for 1d24h1m0s. Please, either resolve the conflicts, or close it to finish the backport process of #65090

**Comment by robot-ch-test-poll4** [comment]
Dear @devcrafter, @KochetovNicolai, the PR is not updated for 1d25h0m20s. Please, either resolve the conflicts, or close it to finish the backport process of #65090

**Comment by robot-ch-test-poll** [comment]
Dear @devcrafter, @KochetovNicolai, the PR is not updated for 1d24h59m31s. Please, either resolve the conflicts, or close it to finish the backport process of #65090

**Comment by robot-clickhouse-ci-2** [comment]
Dear @devcrafter, @KochetovNicolai, the PR is not updated for 1d24h1m51s. Please, either resolve the conflicts, or close it to finish the backport process of #65090

**Comment by robot-ch-test-poll** [comment]
Dear @devcrafter, @KochetovNicolai, the PR is not updated for 1d24h58m6s. Please, either resolve the conflicts, or close it to finish the backport process of #65090

**Comment by robot-ch-test-poll2** [comment]
Dear @devcrafter, @KochetovNicolai, the PR is not updated for 1d24h3m0s. Please, either resolve the conflicts, or close it to finish the backport process of #65090

**Comment by robot-ch-test-poll4** [comment]
Dear @devcrafter, @KochetovNicolai, the PR is not updated for 1d25h5m56s. Please, either resolve the conflicts, or close it to finish the backport process of #65090

**Comment by robot-clickhouse-ci-1** [comment]
Dear @devcrafter, @KochetovNicolai, the PR is not updated for 1d24h0m22s. Please, either resolve the conflicts, or close it to finish the backport process of #65090

**Comment by robot-clickhouse-ci-2** [comment]
Dear @devcrafter, @KochetovNicolai, the PR is not updated for 1d25h16m51s. Please, either resolve the conflicts, or close it to finish the backport process of #65090

**Comment by robot-ch-test-poll3** [comment]
Dear @devcrafter, @KochetovNicolai, the PR is not updated for 1d24h1m29s. Please, either resolve the conflicts, or close it to finish the backport process of #65090

**Comment by robot-ch-test-poll2** [comment]
Dear @devcrafter, @KochetovNicolai, the PR is not updated for 1d24h44m28s. Please, either resolve the conflicts, or close it to finish the backport process of #65090

**Comment by robot-ch-test-poll1** [comment]
Dear @devcrafter, @KochetovNicolai, the PR is not updated for 1d24h1m47s. Please, either resolve the conflicts, or close it to finish the backport process of #65090

**Comment by robot-ch-test-poll2** [comment]
Dear @devcrafter, @KochetovNicolai, the PR is not updated for 1d24h1m4s. Please, either resolve the conflicts, or close it to finish the backport process of #65090

**Comment by robot-clickhouse-ci-2** [comment]
Dear @devcrafter, @KochetovNicolai, the PR is not updated for 1d24h45m7s. Please, either resolve the conflicts, or close it to finish the backport process of #65090

**Comment by robot-ch-test-poll1** [comment]
Dear @devcrafter, @KochetovNicolai, the PR is not updated for 1d24h7m52s. Please, either resolve the conflicts, or close it to finish the backport process of #65090

**Comment by robot-clickhouse-ci-2** [comment]
Dear @devcrafter, @KochetovNicolai, the PR is not updated for 1d24h56m14s. Please, either resolve the conflicts, or close it to finish the backport process of #65090

**Comment by robot-ch-test-poll4** [comment]
Dear @devcrafter, @KochetovNicolai, the PR is not updated for 1d24h57m6s. Please, either resolve the conflicts, or close it to finish the backport process of #65090

**Comment by robot-ch-test-poll** [comment]
Dear @devcrafter, @KochetovNicolai, the PR is not updated for 1d24h59m1s. Please, either resolve the conflicts, or close it to finish the backport process of #65090

**Comment by robot-ch-test-poll** [comment]
Dear @devcrafter, @KochetovNicolai, the PR is not updated for 1d25h1m56s. Please, either resolve the conflicts, or close it to finish the backport process of #65090

**Comment by robot-ch-test-poll3** [comment]
Dear @devcrafter, @KochetovNicolai, the PR is not updated for 1d24h0m36s. Please, either resolve the conflicts, or close it to finish the backport process of #65090

**Comment by robot-ch-test-poll3** [comment]
Dear @devcrafter, @KochetovNicolai, the PR is not updated for 1d24h56m20s. Please, either resolve the conflicts, or close it to finish the backport process of #65090

**Comment by robot-clickhouse-ci-1** [comment]
Dear @devcrafter, @KochetovNicolai, the PR is not updated for 1d24h4m49s. Please, either resolve the conflicts, or close it to finish the backport process of #65090

**Comment by robot-clickhouse** [comment]
Dear @devcrafter, @KochetovNicolai, the PR is not updated for 1d24h57m24s. Please, either resolve the conflicts, or close it to finish the backport process of #65090

**Comment by robot-ch-test-poll3** [comment]
Dear @devcrafter, @KochetovNicolai, the PR is not updated for 1d24h58m9s. Please, either resolve the conflicts, or close it to finish the backport process of #65090

**Comment by robot-ch-test-poll3** [comment]
Dear @devcrafter, @KochetovNicolai, the PR is not updated for 1d24h8m25s. Please, either resolve the conflicts, or close it to finish the backport process of #65090

**Comment by robot-clickhouse-ci-2** [comment]
Dear @devcrafter, @KochetovNicolai, the PR is not updated for 1d24h51m1s. Please, either resolve the conflicts, or close it to finish the backport process of #65090

**Comment by robot-clickhouse** [comment]
Dear @devcrafter, @KochetovNicolai, the PR is not updated for 1d24h1m59s. Please, either resolve the conflicts, or close it to finish the backport process of #65090

**Comment by robot-ch-test-poll1** [comment]
Dear @devcrafter, @KochetovNicolai, the PR is not updated for 1d24h2m12s. Please, either resolve the conflicts, or close it to finish the backport process of #65090

**Comment by robot-ch-test-poll4** [comment]
Dear @devcrafter, @KochetovNicolai, the PR is not updated for 1d25h0m11s. Please, either resolve the conflicts, or close it to finish the backport process of #65090

**Comment by robot-ch-test-poll1** [comment]
Dear @devcrafter, @KochetovNicolai, the PR is not updated for 1d24h56m54s. Please, either resolve the conflicts, or close it to finish the backport process of #65090

**Comment by robot-ch-test-poll1** [comment]
Dear @devcrafter, @KochetovNicolai, the PR is not updated for 1d24h0m55s. Please, either resolve the conflicts, or close it to finish the backport process of #65090

**Comment by robot-ch-test-poll1** [comment]
Dear @devcrafter, @KochetovNicolai, the PR is not updated for 1d24h59m56s. Please, either resolve the conflicts, or close it to finish the backport process of #65090

**Comment by robot-clickhouse-ci-1** [comment]
Dear @devcrafter, @KochetovNicolai, the PR is not updated for 1d24h2m46s. Please, either resolve the conflicts, or close it to finish the backport process of #65090

**Comment by robot-ch-test-poll** [comment]
Dear @devcrafter, @KochetovNicolai, the PR is not updated for 1d24h55m34s. Please, either resolve the conflicts, or close it to finish the backport process of #65090

**Comment by robot-clickhouse-ci-2** [comment]
Dear @devcrafter, @KochetovNicolai, the PR is not updated for 1d24h0m22s. Please, either resolve the conflicts, or close it to finish the backport process of #65090

**Comment by robot-clickhouse-ci-2** [comment]
Dear @devcrafter, @KochetovNicolai, the PR is not updated for 1d24h1m5s. Please, either resolve the conflicts, or close it to finish the backport process of #65090

**Comment by robot-clickhouse-ci-1** [comment]
Dear @devcrafter, @KochetovNicolai, the PR is not updated for 1d24h1m39s. Please, either resolve the conflicts, or close it to finish the backport process of #65090

**Comment by robot-ch-test-poll1** [comment]
Dear @devcrafter, @KochetovNicolai, the PR is not updated for 1d24h56m54s. Please, either resolve the conflicts, or close it to finish the backport process of #65090

**Comment by robot-clickhouse-ci-1** [comment]
Dear @devcrafter, @KochetovNicolai, the PR is not updated for 1d24h2m39s. Please, either resolve the conflicts, or close it to finish the backport process of #65090

**Comment by robot-clickhouse-ci-1** [comment]
Dear @devcrafter, @KochetovNicolai, the PR is not updated for 1d24h58m5s. Please, either resolve the conflicts, or close it to finish the backport process of #65090

**Comment by robot-ch-test-poll4** [comment]
Dear @devcrafter, @KochetovNicolai, the PR is not updated for 1d24h59m17s. Please, either resolve the conflicts, or close it to finish the backport process of #65090

**Comment by robot-ch-test-poll1** [comment]
Dear @devcrafter, @KochetovNicolai, the PR is not updated for 1d24h0m12s. Please, either resolve the conflicts, or close it to finish the backport process of #65090

**Comment by robot-ch-test-poll2** [comment]
Dear @devcrafter, @KochetovNicolai, the PR is not updated for 1d24h3m32s. Please, either resolve the conflicts, or close it to finish the backport process of #65090

**Comment by robot-clickhouse-ci-2** [comment]
Dear @devcrafter, @KochetovNicolai, the PR is not updated for 1d25h1m0s. Please, either resolve the conflicts, or close it to finish the backport process of #65090

**Comment by robot-ch-test-poll** [comment]
Dear @devcrafter, @KochetovNicolai, the PR is not updated for 1d24h4m55s. Please, either resolve the conflicts, or close it to finish the backport process of #65090

**Comment by robot-ch-test-poll1** [comment]
Dear @devcrafter, @KochetovNicolai, the PR is not updated for 1d24h0m37s. Please, either resolve the conflicts, or close it to finish the backport process of #65090

**Comment by robot-clickhouse** [comment]
Dear @devcrafter, @KochetovNicolai, the PR is not updated for 1d24h51m30s. Please, either resolve the conflicts, or close it to finish the backport process of #65090

**Comment by robot-ch-test-poll** [comment]
Dear @devcrafter, @KochetovNicolai, the PR is not updated for 1d26h5m3s. Please, either resolve the conflicts, or close it to finish the backport process of #65090

**Comment by robot-ch-test-poll1** [comment]
Dear @devcrafter, @KochetovNicolai, the PR is not updated for 1d24h1m55s. Please, either resolve the conflicts, or close it to finish the backport process of #65090

**Comment by robot-clickhouse** [comment]
Dear @devcrafter, @KochetovNicolai, the PR is not updated for 1d25h23m18s. Please, either resolve the conflicts, or close it to finish the backport process of #65090

**Comment by robot-clickhouse** [comment]
Dear @devcrafter, @KochetovNicolai, the PR is not updated for 1d25h46m8s. Please, either resolve the conflicts, or close it to finish the backport process of #65090

**Comment by robot-ch-test-poll** [comment]
Dear @devcrafter, @KochetovNicolai, the PR is not updated for 1d24h45m9s. Please, either resolve the conflicts, or close it to finish the backport process of #65090

**Comment by robot-clickhouse-ci-2** [comment]
Dear @devcrafter, @KochetovNicolai, the PR is not updated for 1d24h58m44s. Please, either resolve the conflicts, or close it to finish the backport process of #65090

**Comment by robot-ch-test-poll3** [comment]
Dear @devcrafter, @KochetovNicolai, the PR is not updated for 1d24h7m35s. Please, either resolve the conflicts, or close it to finish the backport process of #65090

**Comment by robot-clickhouse-ci-1** [comment]
Dear @devcrafter, @KochetovNicolai, the PR is not updated for 1d24h52m0s. Please, either resolve the conflicts, or close it to finish the backport process of #65090

**Pull request closed without merging**
