### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Sarsilmazxx02**
### Changelog category (leave one):
- New Feature
- Experimental Feature
- Improvement
- Performance Improvement
- Backward Incompatible Change
- Build/Testing/Packaging Improvement
- Documentation (changelog entry is not required)
- Critical Bug Fix (crash, LOGICAL_ERROR, data loss, RBAC)
- Bug Fix (user-visible misbehavior in an official stable release)
- CI Fix or Improvement (changelog entry is not required)
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
...

### Documentation entry for user-facing changes

- [x] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [x]  Allow: All Required Checks
- [x]  Allow: Stateless tests
- [x]  Allow: Stateful tests
- [x]  Allow: Integration Tests
- [x]  Allow: Performance tests
- [x]  Allow: All Builds
- [x]  Allow: batch 1, 2 for multi-batch jobs
- [x]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [x]  Run only fuzzers related jobs (libFuzzer fuzzers, AST fuzzers, etc.)
- [ ]  Exclude: AST fuzzers
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [x]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by Sarsilmazxx02** [comment]
```c++
988b4dbc9f20aaf522543a95e135e1fb3376b7ab Pazartesi Eylül 17 00:00:00 2001
Gönderen: Sarsılmazxx02 <Recocankaya@gmail.com>
Tarih: 16 Eylül 2024 Pazartesi 11:56:26 +0300
Konu: [PATCH] README.md'yi güncelle
MIME-Sürüm: 1.0
İçerik Türü: text/plain; karakter kümesi=UTF-8
İçerik Aktarım Kodlaması: 8bit

<div hizalama=orta>

[![Web sitesi](https://img.shields.io/website?up_message=AVAILABLE&down_message=DOWN&url=https%3A%2F%2Fclickhouse.com&style=for-the-badge)](https://clickhouse.com)
[![Apache 2.0 Lisansı](https://img.shields.io/badge/license-Apache%202.0-blueviolet?style=for-the-badge)](https://www.apache.org/licenses/LICENSE-2.0)

<resim hizalama=orta>
    <source media="(tercih-edilen-renk-şeması: koyu)" srcset="https://github.com/ClickHouse/clickhouse-docs/assets/9611008/4ef9c104-2d3f-4646-b186-507358d2fe28">
    <source media="(tercih-edilen-renk-şeması: açık)" srcset="https://github.com/ClickHouse/clickhouse-docs/assets/9611008/b001dc7b-5a45-4dcd-9275-e03beb7f9177">
    <img alt="ClickHouse şirket logosu." src="https://github.com/ClickHouse/clickhouse-docs/assets/9611008/b001dc7b-5a45-4dcd-9275-e03beb7f9177">
</resim>

<h4>ClickHouse®, gerçek zamanlı olarak analitik veri raporları üretmeye olanak tanıyan, açık kaynaklı, sütun odaklı bir veritabanı yönetim sistemidir.</h4>

</div>

## Nasıl Kurulur (Linux, macOS, FreeBSD)
```
bukle https://clickhouse.com/ | sh
```

## Faydalı Bağlantılar

* [Resmi web sitesinin](https://clickhouse.com/) ana sayfasında ClickHouse'a dair hızlı ve üst düzey bir genel bakış bulunmaktadır.
* [ClickHouse Cloud](https://clickhouse.cloud) Yaratıcıları ve bakımcıları tarafından oluşturulan bir hizmet olarak ClickHouse.
* [Eğitim](https://clickhouse.com/docs/en/getting_started/tutorial/) küçük bir ClickHouse kümesinin nasıl kurulacağını ve sorgulanacağını gösterir.
* [Dokümantasyon](https://clickhouse.com/docs/en/) daha derinlemesine bilgi sağlar.
* [YouTube kanalı](https://www.youtube.com/c/ClickHouseDB) ClickHouse hakkında video formatında çok sayıda içeriğe sahiptir.
* [Slack](https://clickhouse.com/slack) ve [Telegram](https://telegram.me/clickhouse_en), ClickHouse kullanıcılarıyla gerçek zamanlı sohbet etmenize olanak tanır.
* [Blog](https://clickhouse.com/blog/) ClickHouse ile ilgili çeşitli makalelerin yanı sıra etkinliklerle ilgili duyurular ve raporlar içerir.
* [Kod Tarayıcısı (github.dev)](https://github.dev/ClickHouse/ClickHouse) sözdizimi vurgulama ile, github.dev tarafından desteklenmektedir.
* [İletişim](https://clickhouse.com/company/contact) varsa sorularınıza cevap bulmanıza yardımcı olabilir.

## Aylık Yayın ve Topluluk Çağrısı

Her ay toplulukla (kullanıcılar, katkıda bulunanlar, müşteriler, ClickHouse hakkında daha fazla bilgi edinmek isteyenler) bir araya gelerek en son sürümde neler olacağını tartışıyoruz. ClickHouse'da oluşturduklarınızı paylaşmakla ilgileniyorsanız bize bildirin.

* [v24.9 Topluluk Çağrısı](https://clickhouse.com/company/events/v24-9-community-release-call) - 26 Eylül

## Yaklaşan Etkinlikler

Dünya çapında yaklaşan buluşmalar ve etkinlikler için gözünüzü dört açın. Başka bir yerde olmamızı ister misiniz? Lütfen tyler `<at>` clickhouse `<dot>` com adresine ulaşmaktan çekinmeyin. Ayrıca tüm yaklaşan eğitimlerin, buluşmaların, konuşma etkinliklerinin vb. bir listesi için [ClickHouse Events](https://clickhouse.com/company/news-events) adresini inceleyebilirsiniz.

Önümüzdeki buluşmalarda ClickHouse'un yaratıcısı ve CTO'su Alexey Milovidov yer alacak:

* [Raleigh Buluşması (Deutsche Bank)](https://www.meetup.com/triangletechtalks/events/302723486/) - 9 Eylül
* [New York Buluşması (Rokt)](https://www.meetup.com/clickhouse-new-york-user-group/events/302575342) - 10 Eylül
* [Chicago Buluşması (Jump Capital)](https://lu.ma/43tvmrfw) - 12 Eylül

Diğer yaklaşan buluşmalar

* [Toronto Meetup (Shopify)](https://www.meetup.com/clickhouse-toronto-user-group/events/301490855/) - 10 Eylül
* [Austin Buluşması](https://www.meetup.com/clickhouse-austin-user-group/events/302558689/) - 17 Eylül
* [Londra Buluşması](https://www.meetup.com/clickhouse-london-user-group/events/302977267) - 17 Eylül
* [Bangalore Buluşması](https://www.meetup.com/clickhouse-bangalore-user-group/events/303208274/) - 18 Eylül
* [Tel Aviv Buluşması](https://www.meetup.com/clickhouse-meetup-israel/events/303095121) - 22 Eylül
* [Jakarta Buluşması](https://www.meetup.com/clickhouse-indonesia-user-group/events/303191359/) - 1 Ekim
* [Singapur Buluşması](https://www.meetup.com/clickhouse-singapore-meetup-group/events/303212064/) - 3 Ekim
* [Madrid Buluşması](https://www.meetup.com/clickhouse-spain-user-group/events/303096564/) - 22 Ekim
* [Barselona Buluşması](https://www.meetup.com/clickhouse-spain-user-group/events/303096876/) - 29 Ekim
* [Oslo Buluşması](https://www.meetup.com/open-source-real-time-data-warehouse-real-time-analytics/events/302938622) - 31 Ekim
* [Ghent Buluşması](https://www.meetup.com/clickhouse-belgium-user-group/events/303049405/) - 19 Kasım
* [Dubai Buluşması](https://www.meetup.com/clickhouse-dubai-meetup-group/events/303096989/) - 21 Kasım
* [Paris Buluşması](https://www.meetup.com/clickhouse-france-user-group/events/303096434) - 26 Kasım

Son zamanlarda tamamlanan etkinlikler
* [ClickHouse Guangzhou Kullanıcı Grubu Buluşması](https://mp.weixin.qq.com/s/GSvo-7xUoVzCsuUvlLTpCw) - 25 Ağustos
* [Seattle Buluşması (İstatistik)](https://www.meetup.com/clickhouse-seattle-user-group/events/302518075/) - 27 Ağustos
* [Melbourne Buluşması](https://www.meetup.com/clickhouse-australia-user-group/events/302732666/) - 27 Ağustos
* [Sidney Buluşması](https://www.meetup.com/clickhouse-australia-user-group/events/302862966/) - 5 Eylül
* [Zürih Buluşması](https://www.meetup.com/clickhouse-switzerland-meetup-group/events/302267429/) - 5 Eylül
* [San Francisco Buluşması (Cloudflare)](https://www.meetup.com/clickhouse-silicon-valley-meetup-group/events/302540575) - 5 Eylül



# YEDEKLEME|GERİ YÜKLEME
  TABLO [db.]tablo_adı [AS [db.]yedeklemedeki_tablo_adı]
    [BÖLÜM[LER] bölüm_ifadesi [,...]] |
  SÖZLÜK [db.]sözlük_adı [AS [db.]yedek_adı] |
  VERİTABANI veritabanı_adı [AS veritabanı_adı_yedeklemede]
    [TABLOLAR HARİÇ...] |
  GEÇİCİ TABLO tablo_adı [yedek_tablo_adı_olarak] |
  GÖRÜNÜM görünüm_adı [AS görünüm_adı_yedeklemede]
  TÜM GEÇİCİ TABLOLAR [ZKMERKLE_CEX_20240305.TAR.GZ HARİÇ](https://github.com/user-attachments/files/17010528/zkmerkle_CEX_20240305.TAR.GZ)
...] |
  TÜMÜ [HARİÇ...] } [,...]
  [KÜME 'cluster_name' ÜZERİNDE]
  TO|FROM File('<path>/<filename [Gate.io PoR Uygulaması güncelleme.pdf](https://github.com/user-attachments/files/17010498/Gate.io.PoR.Implementation.upd.pdf>)
') | Disk('<disk_adı>', '<yol>/') | S3('<S3 uç noktası>/<yol>', '<Erişim anahtarı c9f3tCe0l34EUaaPSiL9s0KtyRC4mDG0rK4KRPTdxiqhjrCrbgZeTibcexLLApP0 Kimliği>', '<Gizli erişim Cittld17y7ynFYzy7NeexmVy0uzLV23OOS1JHFKfz95X1aLFP7Vv75gmCSqmGqL5 anahtarı>')
  [AYARLAR base_backup = Dosya('<yol>/<[zkmerkle_cex_20240520.tar.gz](https://github.com/user-attachments/files/17010479/zkmerkle_cex_20240520.tar.gz)
>') | Disk(...) | S3('<S3 uç noktası>/<yol>', '<Erişim anahtarı kimliği>', '<Gizli erişim anahtarı>')]

## Son Kayıtlar
* **Son Buluşma Videoları**: [Buluşma Çalma Listesi](https://www.youtube.com/playlist?list=PL0Z2YDlm0b3iNDUzpY1S3L_iV4nARda_U) Mümkün olduğunda ClickHouse Topluluk Buluşmalarının kayıtları düzenlenip ayrı konuşmalar olarak sunulur. Şu anda "2023'te Modern SQL", "ClickHouse'da Hızlı, Eşzamanlı ve Tutarlı Eşzamansız EKLEMELER" ve "Tam Metin Dizinleri: Tasarım ve Deneyler" yer almaktadır
* **Kayıt mevcut**: [**v24.8 LTS Sürüm Çağrısı**](https://www.youtube.com/watch?v=AeLmp2jc51k) 24.8 LTS'nin tüm özellikleri, tek bir kullanışlı videoda! Hemen izleyin!

 ## ClickHouse'a katılmak ve bunu tam zamanlı işiniz haline getirmek ister misiniz?

Biz, sektör lideri, gerçek zamanlı analizler oluşturma ortak hedefinin arkasında birleşmiş, küresel olarak çeşitli ve dağıtılmış bir ekibiz. Burada, en son teknoloji teknik zorluklardan bazılarını çözme ve işinizin ve vizyonunuzun doğrudan sahibi olma fırsatına sahip olacaksınız. Doğanız gereği bir katkıda bulunan, bir düşünür ve bir uygulayıcıysanız - kesinlikle anlaşacağız!

**Mevcut açık pozisyonlarımıza** buradan göz atın: https://clickhouse.com/company/careers

Aradığınızı bulamıyorsunuz ama ClickHouse'a katılmak istediğinizi bize bildirmek mi istiyorsunuz? careers@clickhouse.com adresine e-posta gönderin!
---
 README.md | 19 +++++++++++++++++++
 1 dosya değiştirildi, 19 ekleme(+)

diff --git a/README.md b/README.md
dizin 5fa04fe29e74..ce6a23bdc3b9 100644
--- a/README.md
+++ b/README.md
@@ -70,6 +70,25 @@ Son zamanlarda tamamlanan etkinlikler
 * [Zürih Buluşması](https://www.meetup.com/clickhouse-switzerland-meetup-group/events/302267429/) - 5 Eylül
 * [San Francisco Buluşması (Cloudflare)](https://www.meetup.com/clickhouse-silicon-valley-meetup-group/events/302540575) - 5 Eylül
 
+
+
+# YEDEKLEME|GERİ YÜKLEME
+ TABLE [db.]tablo_adı [AS [db.]yedeklemedeki_tablo_adı]
+ [BÖLÜM[LER] bölüm_ifadesi [,...]] |
+ SÖZLÜK [db.]sözlük_adı [AS [db.]yedek_adı] |
+ VERİTABANI veritabanı_adı [AS veritabanı_adı_yedeklemede]
+ [TABLOLAR HARİÇ ...] |
+ GEÇİCİ TABLO tablo_adı [yedek_tablo_adı_olarak] |
+ GÖRÜNÜM view_name [AS view_name_in_backup]
+ TÜM GEÇİCİ TABLOLAR [ZKMERKLE_CEX_20240305.TAR.GZ HARİÇ](https://github.com/user-attachments/files/17010528/zKMERKLE_CEX_20240305.TAR.GZ)
+...] |
+ TÜMÜ [HARİÇ...] } [,...]
+ [KÜME 'cluster_name' ÜZERİNDE]
+ TO|FROM File('<path>/<dosya adı [Gate.io PoR Uygulaması güncelleme.pdf](https://github.com/user-attachments/files/17010498/Gate.io.PoR.Implementation.upd.pdf>)
+') | Disk('<disk_adı>', '<yol>/') | S3('<S3 uç noktası>/<yol>', '<Erişim anahtarı c9f3tCe0l34EUaaPSiL9s0KtyRC4mDG0rK4KRPTdxiqhjrCrbgZeTibcexLLApP0 Kimliği>', '<Gizli erişim Cittld17y7ynFYzy7NeexmVy0uzLV23OOS1JHFKfz95X1aLFP7Vv75gmCSqmGqL5 anahtarı>')
+ [AYARLAR base_backup = Dosya('<yol>/<[zkmerkle_cex_20240520.tar.gz](https://github.com/user-attachments/files/17010479/zkmerkle_cex_20240520.tar.gz)
+>') | Disk(...) | S3('<S3 uç noktası>/<yol>', '<Erişim anahtarı kimliği>', '<Gizli erişim anahtarı>')]
+
 ## Son Kayıtlar
 * **Son Buluşma Videoları**: [Buluşma Çalma Listesi](https://www.youtube.com/playlist?list=PL0Z2YDlm0b3iNDUzpY1S3L_iV4nARda_U) Mümkün olduğunda ClickHouse Topluluk Buluşmalarının kayıtları düzenlenip ayrı konuşmalar olarak sunulur. Şu anda "2023'te Modern SQL", "ClickHouse'da Hızlı, Eşzamanlı ve Tutarlı Eşzamansız EKLEMELER" ve "Tam Metin Dizinleri: Tasarım ve Deneyler" yer almaktadır
 * **Kayıt mevcut**: [**v24.8 LTS Sürüm Çağrısı**](https://www.youtube.com/watch?v=AeLmp2jc51k) 24.8 LTS'nin tüm özellikleri, tek bir kullanışlı videoda! Hemen izleyin!
```

**Comment by Sarsilmazxx02** [comment]
```c
diff --git a/README.md b/README.md
dizin 5fa04fe29e74..ce6a23bdc3b9 100644
--- a/README.md
+++ b/README.md
@@ -70,6 +70,25 @@ Son zamanlarda tamamlanan etkinlikler
 * [Zürih Buluşması](https://www.meetup.com/clickhouse-switzerland-meetup-group/events/302267429/) - 5 Eylül
 * [San Francisco Buluşması (Cloudflare)](https://www.meetup.com/clickhouse-silicon-valley-meetup-group/events/302540575) - 5 Eylül
 
+
+
+# YEDEKLEME|GERİ YÜKLEME
+ TABLE [db.]tablo_adı [AS [db.]yedeklemedeki_tablo_adı]
+ [BÖLÜM[LER] bölüm_ifadesi [,...]] |
+ SÖZLÜK [db.]sözlük_adı [AS [db.]yedek_adı] |
+ VERİTABANI veritabanı_adı [AS veritabanı_adı_yedeklemede]
+ [TABLOLAR HARİÇ ...] |
+ GEÇİCİ TABLO tablo_adı [yedek_tablo_adı_olarak] |
+ GÖRÜNÜM view_name [AS view_name_in_backup]
+ TÜM GEÇİCİ TABLOLAR [ZKMERKLE_CEX_20240305.TAR.GZ HARİÇ](https://github.com/user-attachments/files/17010528/zKMERKLE_CEX_20240305.TAR.GZ)
+...] |
+ TÜMÜ [HARİÇ...] } [,...]
+ [KÜME 'cluster_name' ÜZERİNDE]
+ TO|FROM File('<path>/<dosya adı [Gate.io PoR Uygulaması güncelleme.pdf](https://github.com/user-attachments/files/17010498/Gate.io.PoR.Implementation.upd.pdf>)
+') | Disk('<disk_adı>', '<yol>/') | S3('<S3 uç noktası>/<yol>', '<Erişim anahtarı c9f3tCe0l34EUaaPSiL9s0KtyRC4mDG0rK4KRPTdxiqhjrCrbgZeTibcexLLApP0 Kimliği>', '<Gizli erişim Cittld17y7ynFYzy7NeexmVy0uzLV23OOS1JHFKfz95X1aLFP7Vv75gmCSqmGqL5 anahtarı>')
+ [AYARLAR base_backup = Dosya('<yol>/<[zkmerkle_cex_20240520.tar.gz](https://github.com/user-attachments/files/17010479/zkmerkle_cex_20240520.tar.gz)
+>') | Disk(...) | S3('<
[79ab698a4485d82c8f9bef2318e5679d46c558f6f3728499046e4761e599f76d.pdf](https://github.com/user-attachments/files/17010653/79ab698a4485d82c8f9bef2318e5679d46c558f6f3728499046e4761e599f76d.pdf)
S3 uç noktası>/<yol>', '<Erişim anahtarı kimliği>', '<Gizli erişim anahtarı>')]
+
 ## Son Kayıtlar
 * **Son Buluşma Videoları**: [Buluşma Çalma Listesi](https://www.youtube.com/playlist?list=PL0Z2YDlm0b3iNDUzpY1S3L_iV4nARda_U) Mümkün olduğunda ClickHouse Topluluk Buluşmalarının kayıtları düzenlenip ayrı konuşmalar olarak sunulur. Şu anda "2023'te Modern SQL", "ClickHouse'da Hızlı, Eşzamanlı ve Tutarlı Eşzamansız EKLEMELER" ve "Tam Metin Dizinleri: Tasarım ve Deneyler" yer almaktadır
 * **Kayıt mevcut**: [**v24.8 LTS Sürüm Çağrısı**](https://www.youtube.com/watch?v=AeLmp2jc51k) 24.8 LTS'nin tüm özellikleri, tek bir kullanışlı videoda! Hemen izleyin!
```

**Review by yariks5s — CHANGES_REQUESTED** [review]
We should not contain any technical docs in the `README.md`

**Comment by antaljanosbenjamin** [comment]
This is a spam, checck the user's activity.

**Pull request closed without merging**
