### PR TITLE
Revert "Revert "Backup_Restore_concurrency_check_node""

### PR DESCRIPTION
**Pull request by SmitaRKulkarni**
Changelog category (leave one):
Bug-fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Updated to use tryGet instead of get for checking stage of backups/restores in concurrency check and updated tests by increasing data size to have a longer backup/restore to ensure the overlap and increased timeout correspondingly.
Renamed cluster config file and removed generated cluster config file for test_concurrency.py
Reverts ClickHouse/ClickHouse#47581 with fix (rename cluster config file)
cc @vitlibar @tavplubix

### CODE REVIEW

**Review by tavplubix — APPROVED** [review]
LGTM, let's wait for tests. Please update the PR description CI will start

**Comment by SmitaRKulkarni** [comment]
Unrelated failures : 
Integration tests (asan) - test_compression_codec_read/test.py 
Integration tests (release) - test_merge_tree_s3/test.py - #47882
Integration tests (tsan) - test_backup_restore_on_cluster/test.py - Most failures are due to DROP or CREATE queries taking longer than DDL timeout. 1 failure because cannot start clickhouse.

**Comment by tavplubix** [comment]
> Most failures are due to DROP or CREATE queries taking longer than DDL timeout

Why were they taking more than timeout?

> 1 failure because cannot start clickhouse.

Why can it not start clickhouse?

Anyway, probably it's the issue that was fixed in https://github.com/ClickHouse/ClickHouse/pull/47839

**Review by tavplubix — APPROVED** [review]

**Comment by tavplubix** [comment]
Hm, I'm sorry, but for unknown reason, a lot of integration tests started to fail in master when this PR was merged. Example: https://s3.amazonaws.com/clickhouse-test-reports/0/04822a63e1e5f0a236c3a247340161b3b74647d4/integration_tests__asan__[3/3].html

I'll try to revert it and see if it helps.

**Pull request merged**
