### PR TITLE
Fix small issues about if... conditions in src/Processors/Merges/IMergingTransform.cpp|.h

### PR DESCRIPTION
**Pull request by Alex-Cheng**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Review by vdimir — COMMENTED** [review]
Can an issue caused by wrong conditions be reproduced?

**Comment by robot-ch-test-poll3** [comment]
This is an automated comment for commit 679c0057d8c7e04b13b91ed2ae33065e8c6c5ccc with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/54348/679c0057d8c7e04b13b91ed2ae33065e8c6c5ccc/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Comment by Alex-Cheng** [comment]
> Can an issue caused by wrong conditions be reproduced?
I havn't worked on reproducing an issue about it because it is not easy. However the logic in if(...) statement should be obvious and the fix should be safe.

**Comment by Alex-Cheng** [comment]
Some Fast test testcases are failed but not related to my PR. @vdimir

**Review by vdimir — CHANGES_REQUESTED** [review]
Thank you for your effort!

I'm afraid we shouldn't change these checks because `bool(chunk)` and `hasChunkInfo` are independent. Check `if (chunk)` checks that the chunk is not empty while chunk info may be attached or not. Therefore, it's possible to have `bool(chunk) == false && chuck.hasChunkInfo() == true`.

https://github.com/ClickHouse/ClickHouse/blob/9e50e8ff2022432cacd78be99e551ec0ca186b61/src/Processors/Chunk.h#L85-L86
https://github.com/ClickHouse/ClickHouse/blob/9e50e8ff2022432cacd78be99e551ec0ca186b61/src/Processors/Chunk.h#L92-L93


However, if you still would like to contribute, you may add comments around this code explaining why they look like that, it'll be appreciated!

**Comment by Alex-Cheng** [comment]
Thank you. I misunderstood. The check `state.output_chunk && state.output_chunk.xxx = ...` look like a usual pattern that check the pointer/reference first then the data it points/references to.

**Pull request closed without merging**
