### PR TITLE
Allow parallel replicas for JOIN with analyzer [part 1].

### PR DESCRIPTION
**Pull request by KochetovNicolai**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fixes `02784_parallel_replicas_automatic_decision_join`

### CODE REVIEW

**Comment by robot-ch-test-poll** [comment]
*This is an automated comment for commit 733ceaa7757af7a993db9adab601a43c3f818aa9 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/58838/733ceaa7757af7a993db9adab601a43c3f818aa9/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/58838/733ceaa7757af7a993db9adab601a43c3f818aa9/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Review by novikd — APPROVED** [review]

**Review by Algunenano — COMMENTED** [review]
You might want to remove `allow_experimental_analyzer` from `02731_parallel_replicas_join_subquery.sql` to test it too.

And remove `2784_parallel_replicas_automatic_decision_join` from `analyzer_tech_debt.txt`.

**Comment by Algunenano** [comment]
This broke 02901_parallel_replicas_rollup for the analyzer:

```
2024-01-17 03:23:55 [7bf12ce67677] 2024.01.17 10:23:54.648720 [ 4671 ] {02901_parallel_replicas_rollup-test_6rmivtmd} <Error> executeQuery: Code: 10. DB::Exception: Not found column max(_CAST(NULL_Nullable(UInt8), 'Nullable(UInt8)'_String)) in block. There are only columns: max(NULL_Nullable(UInt8)): While executing Remote. (NOT_FOUND_COLUMN_IN_BLOCK) (version 24.1.1.1150) (from [::1]:53230) (comment: 02901_parallel_replicas_rollup.sh) (in query:  SELECT 1 FROM nested GROUP BY 1 WITH ROLLUP ORDER BY max((SELECT 1 WHERE 0)); ), Stack trace (when copying this message, always include the lines below):
2024-01-17 03:23:55 
2024-01-17 03:23:55 0. ./build_docker/./src/Common/Exception.cpp:96: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000c7c329b in /usr/lib/debug/usr/bin/clickhouse.debug
2024-01-17 03:23:55 1. DB::Exception::Exception<String const&, String>(int, FormatStringHelperImpl<std::type_identity<String const&>::type, std::type_identity<String>::type>, String const&, String&&) @ 0x0000000007bd0327 in /usr/lib/debug/usr/bin/clickhouse.debug
2024-01-17 03:23:55 2. ./build_docker/./src/Core/Block.cpp:0: DB::Block::getByName(String const&, bool) const @ 0x000000001044028e in /usr/lib/debug/usr/bin/clickhouse.debug
2024-01-17 03:23:55 3. ./build_docker/./src/QueryPipeline/RemoteQueryExecutor.cpp:238: DB::adaptBlockStructure(DB::Block const&, DB::Block const&) @ 0x00000000106e542d in /usr/lib/debug/usr/bin/clickhouse.debug
2024-01-17 03:23:55 4. ./src/QueryPipeline/RemoteQueryExecutor.h:120: DB::RemoteQueryExecutor::processPacket(DB::Packet) @ 0x00000000106e37ca in /usr/lib/debug/usr/bin/clickhouse.debug
2024-01-17 03:23:55 5. ./build_docker/./src/QueryPipeline/RemoteQueryExecutor.cpp:413: DB::RemoteQueryExecutor::readAsync() @ 0x00000000106e4fa2 in /usr/lib/debug/usr/bin/clickhouse.debug
2024-01-17 03:23:55 6. ./src/QueryPipeline/RemoteQueryExecutor.h:135: DB::RemoteSource::tryGenerate() @ 0x0000000012b1a7af in /usr/lib/debug/usr/bin/clickhouse.debug
2024-01-17 03:23:55 7. ./contrib/llvm-project/libcxx/include/optional:344: DB::ISource::work() @ 0x00000000127d6fc3 in /usr/lib/debug/usr/bin/clickhouse.debug
2024-01-17 03:23:55 8. ./build_docker/./src/Processors/Executors/ExecutionThreadContext.cpp:0: DB::ExecutionThreadContext::executeTask() @ 0x00000000127eff7a in /usr/lib/debug/usr/bin/clickhouse.debug
2024-01-17 03:23:55 9. ./build_docker/./src/Processors/Executors/PipelineExecutor.cpp:273: DB::PipelineExecutor::executeStepImpl(unsigned long, std::atomic<bool>*) @ 0x00000000127e6990 in /usr/lib/debug/usr/bin/clickhouse.debug
2024-01-17 03:23:55 10. ./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:833: void std::__function::__policy_invoker<void ()>::__call_impl<std::__function::__default_alloc_func<DB::PipelineExecutor::spawnThreads()::$_0, void ()>>(std::__function::__policy_storage const*) @ 0x00000000127e7a78 in /usr/lib/debug/usr/bin/clickhouse.debug
2024-01-17 03:23:55 11. ./base/base/../base/wide_integer_impl.h:809: ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::worker(std::__list_iterator<ThreadFromGlobalPoolImpl<false>, void*>) @ 0x000000000c8a93e1 in /usr/lib/debug/usr/bin/clickhouse.debug
2024-01-17 03:23:55 12. ./build_docker/./src/Common/ThreadPool.cpp:0: void std::__function::__policy_invoker<void ()>::__call_impl<std::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>(void&&)::'lambda'(), void ()>>(std::__function::__policy_storage const*) @ 0x000000000c8acc3c in /usr/lib/debug/usr/bin/clickhouse.debug
2024-01-17 03:23:55 13. ./base/base/../base/wide_integer_impl.h:809: void* std::__thread_proxy[abi:v15000]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void ThreadPoolImpl<std::thread>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>>(void*) @ 0x000000000c8aba3e in /usr
```

**Comment by tavplubix** [comment]
It was merged without waiting for CI to finish, let's revert

**Pull request merged**
