### PR TITLE
Add a setting check_before_drop which checks permissions before attem…

### LINKED ISSUE #55620: Throw error if `SYSTEM DROP REPLICA %s` cannot drop all database/tables
**Describe the issue**

Currently, the `SYSTEM RESTART REPLICA` and `SYSTEM DROP REPLICA` commands ignore database tables if the user cannot drop the replica due to missing grants. It will silently log a failure that the tables were skipped in server logs.

This is suboptimal since it appears as if the query succeeded at ClickHouse client.

**How to reproduce**

Try to drop a replica with a read-only user. The commands will finish successfully.

**Expected behavior**

The command should throw an exception with the appropriate error code if it cannot succeed. For simplicity, it can throw an error for _any_ one grant that is violated while checking permissions.

### PR DESCRIPTION
**Pull request by alekar**
…pting to drop whole replica.

Closes #55620 

### Changelog category (leave one):
- New Feature

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
New setting `check_before_drop` is introduced. When this setting is `true`, any `DROP REPLICA` or `DROP DATABASE REPLICA` commands will check for permissions against all tables while dropping whole replicas before initiating a drop.

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

<details>
    <summary>Modify your CI run</summary>

**NOTE:** If your merge the PR with modified CI you **MUST KNOW** what you are doing
**NOTE:** Checked options will be applied if set before CI RunConfig/PrepareRunConfig step

#### Include tests (required builds will be added automatically):
- [ ]  Fast test
- [ ]  Integration Tests
- [ ]  Stateless tests
- [ ]  Stateful tests
- [ ]  Unit tests
- [ ]  Performance tests
- [ ]  All with ASAN
- [ ]  All with TSAN
- [ ]  All with Analyzer
- [ ]  All with Azure
- [ ]  Add your option here

#### Exclude tests:
- [ ]  Fast test
- [ ]  Integration Tests
- [ ]  Stateless tests
- [ ]  Stateful tests
- [ ]  Performance tests
- [ ]  All with ASAN
- [ ]  All with TSAN
- [ ]  All with MSAN
- [ ]  All with UBSAN
- [ ]  All with Coverage
- [ ]  All with Aarch64
- [ ]  Add your option here

#### Extra options:
- [ ]  do not test (only style check)
- [ ]  disable merge-commit (no merge from master before tests)
- [ ]  disable CI cache (job reuse)

#### Only specified batches in multi-batch jobs:
- [ ]  1
- [ ]  2
- [ ]  3
- [ ]  4

</details>

### CODE REVIEW

**Comment by robot-ch-test-poll** [comment]
*This is an automated comment for commit 6e1083adf8c1b31bccc7265a5c7209263a2baaf4 with description of existing statuses. It's updated for the latest CI running*

[❌ Click here](https://s3.amazonaws.com/clickhouse-test-reports/64209/6e1083adf8c1b31bccc7265a5c7209263a2baaf4/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>❌ failure</td></tr>
<tbody>
</table>

**Comment by alekar** [comment]
Where would I add a test for https://github.com/ClickHouse/ClickHouse/pull/64209? Could not find existing tests around grants for dropping replicas. I was thinking something like `integration/test_drop_replica`.

**Comment by tavplubix** [comment]
Usually, stateless tests are better: https://github.com/ClickHouse/ClickHouse/pull/39359#issuecomment-1188296170
See https://github.com/ClickHouse/ClickHouse/blob/44c4892a588480288f3f259761ed7a192480748f/tests/queries/0_stateless/01541_max_memory_usage_for_user_long.sh and https://github.com/ClickHouse/ClickHouse/blob/44c4892a588480288f3f259761ed7a192480748f/tests/queries/0_stateless/02447_drop_database_replica.sh (you can create a user and some replicated databases the same way in a .sh test)
You may need a unique replica name or `no-parallel` tag, so it will not affect other tests
But an integration test will be fine too, you can create a new one or add it to an existing test like `test_replicated_database`

---

I don't think we need a setting for this, let's check all grants before executing by default

**Comment by alekar** [comment]
> I don't think we need a setting for this, let's check all grants before executing by default

We had concerns about this approach https://github.com/ClickHouse/ClickHouse/issues/55620#issuecomment-1772387079. Was it specifically around `SYSTEM RESTART REPLICA` commands?

**Comment by tavplubix** [comment]
> > I don't think we need a setting for this, let's check all grants before executing by default
> 
> We had concerns about this approach [#55620 (comment)](https://github.com/ClickHouse/ClickHouse/issues/55620#issuecomment-1772387079). Was it specifically around `SYSTEM RESTART REPLICA` commands?

Ah, yes, I forgot. You're right, we need a setting

**Comment by alekar** [comment]
I will open a new pull request when I work on this again.

**Pull request closed without merging**
