### PR TITLE
Fix distributed subquery max_query_size limitation inconsistency

### PR DESCRIPTION
**Pull request by godliness**
Changelog category (leave one):
- Bug Fix (user-visible misbehaviour in official stable or prestable release)

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix distributed subquery max_query_size limitation inconsistency

> Information about CI checks: https://clickhouse.tech/docs/en/development/continuous-integration/

**When insert distributed table under max_query_size limitation**:
`insert into demo values ('11', 11, 'haha')` sql clause will be rewrite to `INSERT INTO default.demo(name, id, dt) VALUES` and send to local node from distributed node. when max_query_size set to 26, distributed node can parse the sql but local node not, because local node received the longer sql.
So we only let the initial node to check the max_query_size, secondary node for distributed table do not need to check it.

**How to reproduce**:

```
./clickhouse-client

drop table if exists demo_local;
CREATE TABLE default.demo_local
(
    `name` String,
    `id` UInt32,
    `dt` String
)

ENGINE = MergeTree
PARTITION BY dt
ORDER BY name
SETTINGS index_granularity = 8192

drop table if exists demo;
CREATE TABLE default.demo
(
    `name` String,
    `id` UInt32,
    `dt` String
)
ENGINE = Distributed('store', 'default', 'demo_local', rand())

set max_query_size=25;
insert into demo values ('11', 11, 'haha');

Syntax error: failed at position 21 ('values'):

insert into demo001 values ('11', 11, 'haha');

Max query size exceeded: 'values'
========================================
set max_query_size=26;
insert into demo values ('11', 11, 'haha');

Received exception from server (version 21.11.3):
Code: 62. DB::Exception: Received from localhost:9000. DB::Exception: Received from chi-ck-store-1-0.share-store.svc.cluster.local:9000. DB::Exception: Syntax error: failed at position 21 ('demo001'): demo001 (name, id, dt) VALUES. Max query size exceeded: 'demo001'. (SYNTAX_ERROR)
```

### CODE REVIEW

**Comment by godliness** [comment]
I think these failed tests has no relationship with this PR.

**Comment by novikd** [comment]
@Mergifyio update

**Review by novikd — APPROVED** [review]
Add test from PR description

**Comment by godliness** [comment]
> Add test from PR description

Done.

**Comment by godliness** [comment]
What should i do next?

**Comment by Felixoid** [comment]
@Mergifyio update

**Comment by Felixoid** [comment]
Sorry, it has a failing test

**Comment by godliness** [comment]
> Sorry, it has a failing test

Thanks a lot, fixed the failed tests and run again. @Felixoid PTAL

**Comment by Felixoid** [comment]
I've checked on 21.8, it raises `Code: 62. DB::Exception: Received from localhost:9000. DB::Exception: Received from localhost:9000. DB::Exception: Syntax error: failed at position 25 ('data_00612'): data_00612. Max query size exceeded: 'data_00612'.`

LGTM

**Pull request merged**
