### PR TITLE
Mongo Atlas/Non-Atlas URI Support

### PR DESCRIPTION
**Pull request by manish53**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

For changelog. Remove if this is non-significant change.

Category (leave one):
- New Feature

Short description (up to few sentences):
Adding support for configuring MongoDB connections with URI (for Atlas service).

Detailed description (optional):
Adding uri (Atlas/Non Atlas) support in clickhouse. New updated poco version provides uri support hence URI.h is in poco/Foundation. If not found then update poco from pocoproject/poco. 
Clickhouse should also provide the updated version of its submodule.

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
@proller will update Poco library.

**Comment by tavplubix** [comment]
Will be assigned to @akuzm

**Comment by manish53** [comment]
@alexey-milovidov Please review this. I have removed conflicts.

**Comment by akuzm** [comment]
MongoDB URI support was added in Poco release 1.8.0. I'll try to merge it to our fork.

**Comment by akuzm** [comment]
https://github.com/yandex/ClickHouse/pull/6892

**Comment by alexey-milovidov** [comment]
@akuzm This is still to do.

**Comment by alexey-milovidov** [comment]
@akuzm will continue tomorrow.

**Comment by akuzm** [comment]
I added some very basic support here: https://github.com/ClickHouse/ClickHouse/pull/10915 Had to rewrite from scatch because of conflicts.
@manish53 please check if that is suitable for you. I'll close this one.

**Pull request closed without merging**
