### PR TITLE
Implement creating tables in parallel while restoring from a backup

### PR DESCRIPTION
**Pull request by vitlibar**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Implement creating tables in parallel while restoring from a backup.
Before this PR the `RESTORE` command always created tables in one thread, which could be slow in case of backups containing many tables.

### CODE REVIEW

**Comment by robot-clickhouse-ci-1** [comment]
*This is an automated comment for commit eda6c6add8306f87908e30f374e926fd5da557e1 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/72427/eda6c6add8306f87908e30f374e926fd5da557e1/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/72423/c1cefb01908fdb74fb336f8aefa4f32b7177b428/docs_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Comment by vitlibar** [comment]
> QQ: Shouldn't it be a performance improvement, so we can check the performance tests as well?

There is no performance tests which can show the improvement of performance. And it isn't easy to write such tests because usually our performance tests check the performance of a specific query.

**Comment by vitlibar** [comment]
The CI failures seem unrelated.

**Review by alexkats — APPROVED** [review]

**Comment by alexkats** [comment]
> The CI failures seem unrelated.

I see that integration test failure is a known flake (https://github.com/ClickHouse/ClickHouse/issues/71672)
AST fuzzer most likely https://github.com/ClickHouse/ClickHouse/issues/57728

**Comment by vitlibar** [comment]
Follow-up: https://github.com/ClickHouse/ClickHouse/pull/72641

**Comment by vitlibar** [comment]
PR https://github.com/ClickHouse/ClickHouse/pull/73983 will help to improve the performance further for the case when we restore one replicated table containing huge number of tables from a backup.

**Pull request merged**
