### PR TITLE
[RFC] Add a way to track active allocations.

### PR DESCRIPTION
**Pull request by KochetovNicolai**
### Changelog category (leave one):
- New Feature

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Introduced a table `system.allocations` which track all the allocation stacks and the number of allocated bytes. Added commands `SYSTEM START ALLOCATION TRACKER` and `SYSTEM STOP ALLOCATION TRACKER` which enable/disable tracking of allocations. Added command `SYSTEM DUMP ALLOCATIONS [FLAMEGRAPH | TREE] [MAX DEPTH X] [MIN BYTES Y]` to dump active allocations.

### Usage
`SYSTEM START ALLOCATION TRACKER` command enables tracking of all the allocations. **Warning**: this command will significantly slow down server (in order of magnitude).
`SYSTEM STOP ALLOCATION TRACKER` command disables tracking of allocations and clears internal state.
While allocation tracker is active, there are a few ways to analyze allocations.

#### System table
There is a table `system.allocations` with columns `trace` and `bytes`. Query
```
SELECT
    concat('\n', arrayStringConcat(arrayMap(x -> addressToLine(x), trace), '\n')) AS stack,
    formatReadableSize(bytes)
FROM system.allocations
WHERE length(trace) <= 5
ORDER BY bytes DESC
LIMIT 5
```
shows top allocations with stack depth 5.

#### System command

`SYSTEM DUMP ALLOCATIONS` dumps allocation in a form of flamegraph or graphviz tree. Additionally, you can specify parameters `MAX DEPTH` to limit stack trace depth and `MIN BYTES` to filter small allocations. By default, `MIN BYTES` is 1MB and `MAX DEPTH` is 0 (unlimited).

Note: it's hard to build flamegraph from `system.allocations` with `MIN BYTES` limit. In case if we have a limit 1000 bytes and two stacks `a -> b -> c 500` and `a -> b -> d 1500`, flamegraph requires `a;b;d 1500` and `a;b 500` in it's output.

##### Flamegraph

Use `flamegraph.pl` script from https://github.com/brendangregg/FlameGraph

```
clickhouse client -q "system dump allocations flamegraph max depth 4 min bytes 1000000" | ./FlameGraph/flamegraph.pl --countname=bytes --color=mem > flame.svg
```

flame

##### Tree

Use `dot` command (`graphviz` package for ubuntu) or online converters like https://dreampuf.github.io/GraphvizOnline.

```
clickhouse client -q "system dump allocations tree max depth 4 min bytes 1000000" | dot -Tsvg > tree.svg
```
tree

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
@KochetovNicolai we already have Memory Profiler. The data is collected into the system.trace_log.

**Comment by alexey-milovidov** [comment]
```
SET max_untracked_memory = 1, memory_profiler_step = 1, memory_profiler_sample_probability = 1
```

https://pastila.nl/?00051fcc/603984c609172b78c10f9e49a0ad1754

**Comment by KochetovNicolai** [comment]
@alexey-milovidov I definitely was aware that we have Memory Profiler.
Memory Profiler is a useful tool, but it collects only allocations. It is very hard to detect if there is any memory which was not released e.g. after a query was executed. I suppose this feature can help in case if memory consumption is gradually increasing and there is no visible reason why (as in #36367).

**Comment by alexey-milovidov** [comment]
Memory Profiler can collect all (100%) allocations and deallocations with stack traces. How this tool is different?
I'm mostly afraid that introducing a 3rd memory profiler that is different by using SYSTEM queries can lead to confusion.

**Comment by KochetovNicolai** [comment]
The difference it that you can't match allocation and deallocation together only by stacktrace. If you enable Memory Profiler, you can find all the allocations and deallocations, you can calculate the total amount of memory, but you can't tell which exact allocations were not deallocated yet.
Also, the implementation uses a little bit more compact structure in memory.
Also, added system.allocations table does not store anything on disk, it just shows the current snapshot.

**Comment by filimonov** [comment]
Also would be interesting to check how big is the perf impact of that (if it would be enabled globally).

**Comment by filimonov** [comment]
Also - do we have a limit of stacktrace unwinding? For example if allocation will be happening in some recurvive function call...

**Comment by KochetovNicolai** [comment]
@filimonov 

> Maybe we can add query id as the deepmost leaf in the tree?

Maybe. It may be a little bit harder. Right now, I don't deallocated memory for the tree at all.
However I store just all the allocations in a map, so, technically, I can store all query ids. On query time we only need to invert the map. It is still a question how to show this ids.

> Also would be interesting to check how big is the perf impact of that (if it would be enabled globally).

It's a lot, actually. I test on a query which is 10 times slower with tracking. Most of the time is spent on stack unwinding.
Well, maybe we can add probability here, but I don't like it - it contradicts the main idea - to find memory allocations which were not released.

> Also - do we have a limit of stacktrace unwinding? For example if allocation will be happening in some recurvive function call...

Yes, https://github.com/ClickHouse/ClickHouse/blob/8b0cdfa31d5909afc91544c0a45c894f3c3a47b5/src/Common/StackTrace.h#L39-L43

**Comment by filimonov** [comment]
One more advantage of that approach comparing to memory profiler is that it account only deallocations related to allocations it 'saw' before.

In memory profile you can sometimes have some large (and unrelated) free before the first alloc. So sum looks ok, but leak may still exists.

**Comment by rschu1ze** [comment]
For usage in production where many queries run in parallel I would find it useful if the tracking could be limited to a single query. Something like this `SELECT * from T SETTINGS track_allocations = true;`. This may also be faster than tracking everything. Of course, the question is if it is easily possible to associate query ids with allocations - maybe we can put the query id in thread-local storage so that memory management can read it.

**Comment by tavplubix** [comment]
> Of course, the question is if it is easily possible to associate query ids with allocations - maybe we can put the query id in thread-local storage so that memory management can read it.

Yes, it's possible and we already do so, see `ThreadStatus` and `MemoryTracker` (and also maybe `TraceCollector` usages in `MemoryTracker`)

**Comment by KochetovNicolai** [comment]
@tavplubix I suppose adding a hash of address could be a solution. However,
* this hash would be useful only if we track all the allocations; in case of sampling it is (probably) not so
* writing all the allocations to trace_log still may be a little bit more expensive; current implementation aggregates all the allocations with the same stack (and it is already slow)
* it would still be a little bit tricky to build flamegraph form trace_log

**Comment by tavplubix** [comment]
> this hash would be useful only if we track all the allocations; in case of sampling it is (probably) not so

We can use sampling based on this hash

> it would still be a little bit tricky to build flamegraph form trace_log

I though we already have scripts that draw flamegraph from trace_log (for query profiler)

**Comment by KochetovNicolai** [comment]
Well, I checked, and my implementation for some reason is much slower then current memory profiler. Maybe I should throw it away.


For some reason I can't get even value from current memory profiler.
```
SET max_untracked_memory = 1, memory_profiler_step = 1, memory_profiler_sample_probability = 1;
select uniq(number % 100000) from numbers(10000000) group by number % 1000000 format Null

SELECT uniq(number % 100000)
FROM numbers(10000000)
GROUP BY number % 1000000
FORMAT `Null`

Query id: 066f7b8f-8cbc-4338-901d-4295c27b071c

select count(), min(size), max(size), sum(size) from system.trace_log where query_id = '066f7b8f-8cbc-4338-901d-4295c27b071c' and trace_type = 'MemorySample'

SELECT
    count(),
    min(size),
    max(size),
    sum(size)
FROM system.trace_log
WHERE (query_id = '066f7b8f-8cbc-4338-901d-4295c27b071c') AND (trace_type = 'MemorySample')

Query id: f06488bc-c954-41fa-a167-47441a84299c

┌─count()─┬─min(size)─┬─max(size)─┬─sum(size)─┐
│   22527 │ -67108864 │  67108864 │     10312 │
└─────────┴───────────┴───────────┴───────────┘

```

Is it possible to use current memory pofiler for background operations? Like, track, if some background thread holds some memory.

**Comment by filimonov** [comment]
> Is it possible to use current memory pofiler for background operations? Like, track, if some background thread holds some memory.

Edit default profile and restart the server...

**Comment by alexey-milovidov** [comment]
Let's add the address itself as is to the system.trace_log, not the hash.

**Comment by filimonov** [comment]
Maybe we should keep those system commands? But they will be enabling memory_profiler globally?

**Comment by alexey-milovidov** [comment]
@filimonov SYSTEM queries represent something you should not do, or - something that you can do but with extreme caution. Also, SYSTEM commands look like something ad-hoc, not aligned with the overall design. That's why I don't like introducing more system commands.

**Comment by alexey-milovidov** [comment]
Superseded by https://github.com/ClickHouse/ClickHouse/pull/38953

**Pull request closed without merging**
