### PR TITLE
Sharding s3 key names (2)

### PR DESCRIPTION
**Pull request by alexey-milovidov**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Virtual filesystem over s3 will use random object names split into multiple path prefixes for better performance on AWS.

Continuation of #34559.

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
@UnamedRus why do you think this change makes sense and reacted with :rocket: ? Please elaborate.

**Comment by UnamedRus** [comment]
Because it was discussed at least several times, but never implemented. And it's better to implement this change in layout sooner than later. 

5,500 GET/HEAD requests per second per partitioned [prefix](https://docs.aws.amazon.com/general/latest/gr/glos-chap.html#keyprefix) limitation can be achieved pretty fast, if we remember that fact, that all replicas (hopefully we will have zero copy replication prod ready in future) and tables share the same bucket path.

And this limit can be reached pretty fast if we assume: 20 columns x 2 file per column x 20 parts at least 800 GET requests for one query.

**Review by antonio2368 — APPROVED** [review]

**Comment by alesapin** [comment]
I suspect that these changes lead to 'The specified key does not exist' on write requests. This error occurs really often in CI and I don't know any other reasons why except this PR. So I'll try to temporarily revert it just to check.

**Comment by azat** [comment]
Interesting. Apparently it is not required anymore - https://www.youtube.com/watch?v=rHeTn9pHNKo&t=3107s

@UnamedRus seems that you (and Altinity) using S3 extensively, have you measured does this improves performance?

P.S. final PR is #41415

**Comment by UnamedRus** [comment]
Imo 5500 Requests per partition its not a lot. ClickHousencan saturate this quite easily.

**Comment by azat** [comment]
>Imo 5500 Requests per partition its not a lot. ClickHousencan saturate this quite easily.

I'm not talking about number of requests, but instead about the thing that on video someone from amazon saying is that they doing this automatically.

**Comment by UnamedRus** [comment]
>but instead about the thing that on video someone from amazon saying is that they doing this automatically.

I see, 
Yeah, that's an interesting video. But i see 2 potential problems here:

1. He is talking about 99% customers don't need to do this hashing prefix thing. (Who is 1%, which need's to do it, and why)
2. In example, he showed that they can do this kind of partitioning based on prefix "dir". So it's possible that, you still need to have multiple prefixes in order to have multiple partitions. 

In before there was problem with s3, that prefixes like that:

```
20221010_1100
20221010_1200
20221010_1300
```
Didn't work well with partitioning, so your optimized prefix would have to look like this:

```
avx20221010_1100
pdv20221010_1200
wqa20221010_1300
```

Maybe he's talking about this issue (and solution).

For us it does mean, that we still need to have different prefixes, bc otherwise we will keep all data in the same prefix (like in before)= partition.

https://aws.amazon.com/premiumsupport/knowledge-center/s3-object-key-naming-pattern/

```
Amazon S3 automatically scales to high request rates. For example, your application can achieve at least [3,500 PUT/COPY/POST/DELETE or 5,500 GET/HEAD requests per second per prefix](https://docs.aws.amazon.com/AmazonS3/latest/dev/optimizing-performance.html) in a bucket.
```

**Comment by azat** [comment]
>He is talking about 99% customers don't need to do this hashing prefix thing. (Who is 1%, which need's to do it, and why)

Yep. Thought I'm not sure what other 0.1%, maybe those are the one who should write to them first (then said that you can write to them and the will do manual repartitioning for you, since automatic will take 30-60m)

>In before there was problem with s3, that prefixes like that:

Before it uses simply random string, so adding one more "level" does not likely to solve anything (but at least it will not harm).

>that we still need to have different prefixes, bc otherwise we will keep all data in the same prefix (like in before)= partition.

AFAIR he underlines that they don't care about slashes

**Comment by UnamedRus** [comment]
> Before it uses simply random string

I'm talking here about S3 itself, not ClickHouse + S3 integration. 

> AFAIR he underlines that they don't care about slashes

I wasn't sure, what could be prefix then (IE, can it be the whole object key), but i found this:
https://aws.amazon.com/premiumsupport/knowledge-center/s3-prefix-nested-folders-difference/

> A [key prefix](https://docs.aws.amazon.com/general/latest/gr/glos-chap.html#keyprefix) is a string of characters that can be the complete path in front of the object name (including the bucket name). For example, if an object (123.txt) is stored as BucketName/Project/WordFiles/123.txt, the prefix might be “BucketName/Project/WordFiles/123.txt”. The prefix can be any length, including the entire object key name.

So, from partitioning perspective, using /xad/ prefixes looks unneeded.  (For AWS S3, and sadly there is a lot of other implementations, we need to be careful of)
But may be there are some other advantages, which we can get from them: For example parallel listing from different prefixes?

**Comment by azat** [comment]
Just to clarify I don't think that this should be removed, just a note for further development.

>For example parallel listing from different prefixes?

I doubt, since AFAIR everything is related to partitions not "common prefixes" (here by "common prefix" I mean something common divided by "/", i.e. "foo/bar" and "foo/baz", "foo" is "common prefix").

**Comment by den-crane** [comment]
BTW,

HDFS has a limited of number of files, 1048576 by default , and 6.4 millions max

```
<name>dfs.namenode.fs-limits.max-directory-items</name>
<value>1048576</value>
```

https://github.com/naver/hadoop/blob/master/hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/FSDirectory.java#L285

**Comment by den-crane** [comment]
> > Imo 5500 Requests per partition its not a lot. ClickHousencan saturate this quite easily.
> 
> I'm not talking about number of requests, but instead about the thing that on video someone from amazon saying is that they doing this automatically.

It seems this automagic works too late. Our client observes that Clickhouse constantly hits the limitations/rates of a single s3 partition.

**Comment by azat** [comment]
>It seems this automagic works too late. Our client observes that Clickhouse constantly hits the limitations/rates of a single s3 partition

With this patch applied?
Interesting, on video he said something about 60 seconds or something similar (but I may forgot already).
And during this period there are 500x and after some time everything works?

**Pull request merged**
