### PR TITLE
Fix polling of /sys/class on errors

### PR DESCRIPTION
**Pull request by azat**
Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix polling of /sys/class on errors (hwmon, sensors, edac)

Cc: @alexey-milovidov

### CODE REVIEW

**Comment by azat** [comment]
>ClickHouse build check — 14/15 builds are OK

Link to the failed build is broken, internal CI issue?

**Comment by nikitamikhaylov** [comment]
@azat Seems like this is what you need https://clickhouse-builds.s3.yandex.net/27554/67ebcef978764220a881f9c1d2c9a354ef87bd05/clickhouse_build_check/build_1628668096.out.log

**Comment by alexey-milovidov** [comment]
@mergifyio update

**Review by alexey-milovidov — APPROVED** [review]
LGTM

**Comment by alexey-milovidov** [comment]
Someone has broken `test_odbc_interaction/test.py::test_sqlite_odbc_hashed_dictionary`...

**Pull request merged**
