### PR TITLE
Setting parallelize_output_from_storages

### PR DESCRIPTION
**Pull request by devcrafter**
### Changelog category (leave one):
- Backward Incompatible Change

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Compatibility setting `parallelize_output_from_storages` to enable behavior before #48727

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]

**Comment by al13n321** [comment]
If `parallelize_output_from_storages` is going to be true by default, should also make `input_format_parquet_preserve_order` false by default.

Or maybe merge them into one setting: `preserve_input_order`, or something. It would do whatever it takes to preserve row order end-to-end.

("Preserve order" and "don't parallelize" are not exactly the same thing: we could paralellize but keep order. But: (a) if avoiding parallelism is what the user wants, they can set max_threads = 1, (b) if in future we do implement parallelization without reordering, it'll be easy to add another setting for that.)

**Comment by al13n321** [comment]
> And for the Parquet case, if input_format_parquet_preserve_order is true then StorageFile::parallelizeOutputAfterReading() can return false to avoid getting reordered data from the reading step.

Ok, I can plumb input_format_parquet_preserve_order into StorageFile::parallelizeOutputAfterReading() somehow (with an explicit `if` for "Parquet" in StorageFile, or another callback in FormatFactory::Creators), and we can document that the user needs to use different settings for parquet vs everything else (csv etc). Seems worse than renaming the setting though. Am I missing something?

**Comment by alexey-milovidov** [comment]
It's ok to rename or remove the excessive setting and generalize them before the release.

PS. I was also conservative about enabling unordered reading from Parquet by default in the next release, but not anymore... let's go ahead with enabling it.

**Review by alexey-milovidov — COMMENTED** [review]
Not enable it by default as of today.

**Comment by alexey-milovidov** [comment]
I've decided to merge it with the setting disabled and only then enable it in master.

**Pull request merged**
