### PR TITLE
Add type conversion to map matching in bloom filter

### PR DESCRIPTION
**Pull request by iceFireser**
For example:

create database db;

CREATE TABLE db.t1
(
m Map(LowCardinality(String), Int64),
INDEX index_models_value_bloom_filter mapValues(m) TYPE bloom_filter GRANULARITY 1
)
ENGINE = MergeTree
ORDER BY tuple()
SETTINGS index_granularity = 8192;

insert into db.t1 (m) values (map('xxx', 56));

SELECT m
FROM db.t1
WHERE (m['xxx']) = 56

The result could be:

┌─m──────────┐
│ {'xxx':56}                 │
└────────────┘
But it gives results:

Received exception from server (version 24.3.3):
Code: 170. DB::Exception: Received from localhost:29000. DB::Exception: Bad get: has UInt64, requested Int64. (BAD_GET)

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
When using mapKeys and mapValues ​​Bloom filters, add type conversion to the value part in map[key]=value

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: Normal Builds
- [ ]  Allow: Special Builds
- [ ]  Allow: All NOT Required Checks
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Do not test
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by iceFireser** [comment]
git rebase to the latest 24.3 branch and add a test

**Comment by alexey-milovidov** [comment]
Do we need this patch in the master branch?

**Comment by iceFireser** [comment]
> Do we need this patch in the master branch?

I believe so; I've reviewed the code in the master branch, and the issue persists. I encountered this problem while using ClickHouse release 24.3 LTS.

**Comment by alexey-milovidov** [comment]
Please send a pull request to the master branch, then we will backport to LTS.

**Comment by iceFireser** [comment]
> Please send a pull request to the master branch, then we will backport to LTS.

I conducted manual testing and found that the issue no longer exists on the master branch. Upon reviewing the code again, I discovered that the problem had already been resolved through another approach.

commit bfb470535a4b50555fe5b59a1e5615a691757af3 Author: Vitaly Baranov <vitlibar@clickhouse.com> Date: 24-4-8 Allow conversions in Field::safeGet<bool>(): int64 <-> uint64 and int64 <-> bool and uint64 <-> bool

24.3:
template <typename T>
auto & Field::safeGet()
{
    const Types::Which requested = TypeToEnum<NearestFieldType<std::decay_t<T>>>::value;

    if (which != requested)
        throw Exception(ErrorCodes::BAD_GET,
            "Bad get: has {}, requested {}", getTypeName(), requested);

    return get<T>();
}

master:
template <typename T>
auto & Field::safeGet()
{
    const Types::Which target = TypeToEnum<NearestFieldType<std::decay_t<T>>>::value;

    /// We allow converting int64 <-> uint64, int64 <-> bool, uint64 <-> bool in safeGet().
    if (target != which
           && (!isInt64OrUInt64orBoolFieldType(target) || !isInt64OrUInt64orBoolFieldType(which)))
        throw Exception(ErrorCodes::BAD_GET,
            "Bad get: has {}, requested {}", getTypeName(), target);

    return get<T>();
}

**Comment by alexey-milovidov** [comment]
Let's do the following:

1. Extract the test from this PR and submit it in a separate PR to the master branch.
2. Extract the minimal change that is needed (from your comment) and submit it as a PR to 24.3.

**Comment by iceFireser** [comment]
> Let's do the following:
> 
> 1. Extract the test from this PR and submit it in a separate PR to the master branch.
> 2. Extract the minimal change that is needed (from your comment) and submit it as a PR to 24.3.
1. Extract the test from this PR and create a separate PR to the master branch : https://github.com/ClickHouse/ClickHouse/pull/65333
2. Extract the minimal changes from the master branch, replace the original implementation and commit it in the Pr currently under discussion

**Comment by iceFireser** [comment]
Related issues:
https://github.com/ClickHouse/ClickHouse/pull/65333

**Comment by iceFireser** [comment]
@alexey-milovidov I have commited the extracted changes to the current PR. Do I need to resubmit a new PR to 24.3? Does the resubmitted PR need to have the tests that have been submitted to master?

**Comment by iceFireser** [comment]
#68103  (Backport #62206 to 24.3: Fix parsing booleans in settings)  already contains the code in my comment, so I will close this pull request #65197.

**Pull request closed without merging**
