### PR TITLE
Fix all key value is null and group use rollup return wrong answer

### LINKED ISSUE #49280: Group by null value key use rollup with wrong answer
**Describe what's wrong**
When column is Nullable or with LowCardinality.  `ROLLUP`,`WITH TOTALS` returns unexpected results.

To be precise, when the aggregated key is only null, and the aggregate is issued in `convertToBlockImplNotFinal` in `Aggregator.cpp`, the returned result is ignored

https://fiddle.clickhouse.com/e38e044e-dbb5-4ebb-a395-4ca0b4facb88

**How to reproduce**
```sql
CREATE TABLE group_by_null_key (c1 Nullable(Int32), c2 LowCardinality(Nullable(Int32))) ENGINE = Memory();
INSERT INTO group_by_null_key VALUES (null, null), (null, null);

select c1, count(*) from group_by_null_key group by c1 WITH TOTALS;
select c2, count(*) from group_by_null_key group by ROLLUP(c2);
```

**Expected behavior**

```text
┌───c1─┬─count()─┐
│ ᴺᵁᴸᴸ │       2 │
└──────┴─────────┘
┌───c1─┬─count()─┐
│ ᴺᵁᴸᴸ │       2 │
└──────┴─────────┘

---

┌───c2─┬─count()─┐
│ ᴺᵁᴸᴸ │       2 │
└──────┴─────────┘
┌───c2─┬─count()─┐
│ ᴺᵁᴸᴸ │       2 │
└──────┴─────────┘

```

### PR DESCRIPTION
**Pull request by loneylee**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

FIx when group by single key. And key type is `LowCardinality` or `Nullablle`, value is all `null`.Group use rollup or  with totals return wrong result.
Fix #49280

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Fix a bug about grouped single key use `rollup` or `with totals` when value is all null, return empty result.

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by nickitat** [comment]
@loneylee small bug in the new test https://s3.amazonaws.com/clickhouse-test-reports/49282/fd8d3337d0bd78a6b4096e02e450779a810b7d05/fast_test.html

**Review by nickitat — APPROVED** [review]
lgtm

**Comment by alexey-milovidov** [comment]
@loneylee, the reference file wasn't generated correctly.

**Comment by robot-ch-test-poll4** [comment]
This is an automated comment for commit 0be2dcf4210622e3e7438510fb67efea5a3b5af9 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/49282/0be2dcf4210622e3e7438510fb67efea5a3b5af9/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Comment by loneylee** [comment]
> 

@alexey-milovidov @nickitat 
The ci error looks like not relation to my pr. Need i rerun it?

**Pull request merged**
