### PR TITLE
MaterializedMySQL: Add support of double quoted comments

### PR DESCRIPTION
**Pull request by valbok**
Some users use double quotes in comments, so suggesting to support it since it is not so big deal. But users should know that double quotes are not string literals in MySQL
https://dev.mysql.com/doc/refman/8.0/en/string-literals.html
>  If the ANSI_QUOTES SQL mode is enabled, string literals can be quoted only within single quotation marks because a string quoted within double quotation marks is interpreted as an identifier.

### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
- Now double quoted comments are supported in MaterializedMySQL

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by robot-clickhouse-ci-1** [comment]
This is an automated comment for commit fd5782fa0a257baff64d08f878a56a0e94749a0f with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/52355/fd5782fa0a257baff64d08f878a56a0e94749a0f/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Comment by valbok** [comment]
@kssenii

**Review by tavplubix — APPROVED** [review]

**Comment by tavplubix** [comment]
Stateless tests (tsan) [2/5] - https://github.com/ClickHouse/ClickHouse/pull/52537

**Comment by valbok** [comment]
thanks

**Pull request merged**
