### PR TITLE
Revert "New navigation"

### PR DESCRIPTION
**Pull request by tavplubix**
Reverts ClickHouse/ClickHouse#47038

cc: @rfraposa

### CODE REVIEW

**Comment by Avogar** [comment]
Maybe just merge a fix?

**Comment by tavplubix** [comment]
Seems like it breaks Docs Check too: https://s3.amazonaws.com/clickhouse-test-reports/47659/bb7cc975016d68c875e1988a1a1037e9b5813214/docs_check/run.log

```
$ docusaurus build
[INFO] [en] Creating an optimized production build...
[ERROR] Loading of version failed for version current
[ERROR] Unable to build website for locale en.
[ERROR] Error: Invalid sidebar file at "sidebars.js".
```

(I noticed that in https://github.com/ClickHouse/ClickHouse/pull/47659)

**Comment by tavplubix** [comment]
> Seems like it breaks Docs Check too

Yes, it does: https://s3.amazonaws.com/clickhouse-test-reports/47038/9b3e0a7b47e88a90c83bb0362b6d0c2add782331/docs_check.html

**Comment by rfraposa** [comment]
You should have asked me first. This needs to get merged back. That check is no longer relevant as the docs are now deployed in Vercel. 

Frustrating.

**Comment by tavplubix** [comment]
> You should have asked me first. This needs to get merged back. That check is no longer relevant as the docs are now deployed in Vercel.

I'm sorry, but you should have checked the CI status in your PR before merging. PRs that were merged with broken tests can be reverted immediately by anyone without asking the PR's author.

**Comment by rfraposa** [comment]
When I try to open a new pull request, it says the two branches are the same: https://github.com/ClickHouse/ClickHouse/compare/new-nav?expand=1

Did this get reverted or not?

**Comment by rfraposa** [comment]
Never mind - I figured it out. I had to create a new branch. (Github seems to get confused when a PR is reverted.)

**Pull request merged**
