### PR TITLE
Process config w/o extensions as XML format

### PR DESCRIPTION
**Pull request by azat**
Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Process config w/o extensions as XML format

Detailed description / Documentation draft:
I'm using such hack to hide the password:

    $ clickhouse-client --config <(echo '<config><password></password></config>')

But this had been broken in #21858
Cc: @BoloniniD 
Cc: @vitlibar

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
If you want this unusual feature not to be broken, better add a test.

**Review by alexey-milovidov — COMMENTED** [review]
Also need to add a test with unknown formats, e.g. config.conf and config.toml.

**Comment by azat** [comment]
>Also need to add a test with unknown formats, e.g. config.conf and config.toml.

And what behavior it should have? Fail?

**Comment by alexey-milovidov** [comment]
It depends on what files do we search in config.d directories. Do we skip .xml.bak, .xml.tmp, .svn, .git, .kate.swp, etc?

**Comment by alexey-milovidov** [comment]
Maybe better not to implement this feature at all, but make sure that the syntax:

clickhouse-*tool* .. -- config.entry value

is supported.

**Comment by azat** [comment]
>Maybe better not to implement this feature at all, but make sure that the syntax:

But this will still shows the password in the cmdline.

**Comment by azat** [comment]
>It depends on what files do we search in config.d directories. Do we skip .xml.bak, .xml.tmp, .svn, .git, .kate.swp, etc?

Only .yml/.yaml/.xml/.conf, so .conf should be supported as xml too

**Comment by alexey-milovidov** [comment]
Ok. Then the logic is the following:
- xml, conf (case insensitive) and no extension are processed as XML;
- yml and yaml (case insensitive) are processed as YAML;
- all other extensions - throw exception.

**Comment by azat** [comment]
Agree, done

**Comment by filimonov** [comment]
Related reading https://www.netmeister.org/blog/passing-passwords.html

BTW - i think we need to modify the args in memory to remove the password from there. While it's not 100% safe (there is a short moment when password is not replaced yet), it makes chances to see the password via `ps` very small.

**Comment by alexey-milovidov** [comment]
@filimonov We've already done that.

**Comment by filimonov** [comment]
> @filimonov We've already done that.

indeed :+1:
missed that.

**Comment by azat** [comment]
> [Functional stateless tests (debug) — fail: 1, passed: 3063, skipped: 18](https://clickhouse-test-reports.s3.yandex.net/24763/eb08bb066947eb9fea0dde7c6e18c5d5e991d09a/functional_stateless_tests_(debug).html#fail1)
> 01414_freeze_does_not_prevent_alters

#25025

**Comment by alexey-milovidov** [comment]
@mergifyio update

**Review by alexey-milovidov — APPROVED** [review]

**Pull request merged**
