### PR TITLE
Fix bug of datetime64 parsed from string '1969-12-31 23:59:59.123' 

### LINKED ISSUE #36994: ClickHouse 22.4 does not handle DateTime64 correctly
`select '1969-12-31 23:59:59.123'::DateTime64(3, 'UTC') v` should return `1969-12-31 23:59:59.123` but somehow it returns `1970-01-01 00:00:00.877` on 22.4.

This was first mentioned in ClickHouse/clickhouse-jdbc#906 as it failed below case only on 22.4:
```sql
create table test_default_value_datetime64(i Int8, v DateTime64(3, 'UTC') DEFAULT '1969-12-31 23:59:59.123')engine=Memory

insert into test_default_value_datetime64(1, null)

select * from test_default_value_datetime64
┌─i─┬───────────────────────v─┐
│ 1 │ 1969-12-31 23:59:59.123 │
└───┴─────────────────────────┘
```

### PR DESCRIPTION
**Pull request by taiyang-li**
### Changelog category (leave one):
- Bug Fix (user-visible misbehaviour in official stable or prestable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix bug datetime64 parse from string '1969-12-31 23:59:59.123'. Close https://github.com/ClickHouse/ClickHouse/issues/36994

### CODE REVIEW

**Comment by taiyang-li** [comment]
Failed fast tests had been fixed.

**Comment by taiyang-li** [comment]
Failed tests not related to this pr.

**Review by nickitat — APPROVED** [review]
Sorry for not reviewing for so long

**Comment by taiyang-li** [comment]
@nickitat  It's ok. Thanks very much.

**Pull request merged**
