### PR TITLE
Prevent attaching parts from tables with different projections or indices

### LINKED ISSUE #54896: ATTACH PARTITION from source table with different index as destination table throws `Integer divide by zero` error
**Describe the unexpected behaviour**
ATTACH PARTITION from source table with different index as destination table throws `Integer divide by zero` error. 

**How to reproduce**
ClickHouse Cloud v23.8.1.41541
ClickHouse 23.8.2.7

```
create or replace table t1 (
	a UInt32,
	b String,
	INDEX bf b TYPE tokenbf_v1(8192, 3, 0) GRANULARITY 1
)
engine = MergeTree
order by a;

insert into t1 select number, toString(number) from numbers(10);

create or replace  table t2 (
	a UInt32,
	b String,
	INDEX bf b TYPE bloom_filter GRANULARITY 1
)
engine = MergeTree
order by a;

alter table t2 attach partition tuple() from t1;

select * from t2 where b = '1';
```

**Expected behavior**
ATTACH PARTITION from source table with index that is not compatible with the index at destination table should not be allowed. 

**Error message and/or stacktrace**
```
[c-bordeaux-gr-33-server-1] 2023.09.21 14:57:16.807241 [ 536 ] <Fatal> BaseDaemon: ########################################
[c-bordeaux-gr-33-server-1] 2023.09.21 14:57:16.807287 [ 536 ] <Fatal> BaseDaemon: (version 23.8.1.41541 (official build), build id: 0C6F9D74CE985B0E68623C6AE4BBA9E4FBEA2B93, git hash: 2bb8937b298aecf48bb3fe441e69435c645d7166) (from thread 521) (query_id: 827b6395-1d52-4a5d-b9f7-172025e760d2) (query: select * from t2 where b = '1';) Received signal Arithmetic exception (8)
[c-bordeaux-gr-33-server-1] 2023.09.21 14:57:16.807312 [ 536 ] <Fatal> BaseDaemon: Integer divide by zero.
[c-bordeaux-gr-33-server-1] 2023.09.21 14:57:16.807339 [ 536 ] <Fatal> BaseDaemon: Stack trace: 0x00000000152774b1 0x000000001527cbaf 0x0000000015238333 0x0000000015234348 0x000000001523153b 0x0000000015ab9473 0x0000000015ab4607 0x0000000015ab42b0 0x0000000015abc8fa 0x0000000015abeaa7 0x0000000015a7d2a5 0x0000000015a94d6a 0x000000001438adf9 0x00000000146c3b2e 0x00000000146bf42e 0x0000000015681244 0x0000000015697ff9 0x000000000ebaeffc 0x00000000186a1654 0x00000000186a2871 0x000000001882ba67 0x000000001882949c 0x00007f53b4b8eb43 0x00007f53b4c20a00
[c-bordeaux-gr-33-server-1] 2023.09.21 14:57:16.807398 [ 536 ] <Fatal> BaseDaemon: 2. DB::MergeTreeIndexConditionBloomFilter::mayBeTrueOnGranule(DB::MergeTreeIndexGranuleBloomFilter const*) const @ 0x00000000152774b1 in /usr/bin/clickhouse
[c-bordeaux-gr-33-server-1] 2023.09.21 14:57:16.807431 [ 536 ] <Fatal> BaseDaemon: 3. ? @ 0x000000001527cbaf in /usr/bin/clickhouse
[c-bordeaux-gr-33-server-1] 2023.09.21 14:57:16.807460 [ 536 ] <Fatal> BaseDaemon: 4. DB::MergeTreeDataSelectExecutor::filterMarksUsingIndex(std::shared_ptr<DB::IMergeTreeIndex const>, std::shared_ptr<DB::IMergeTreeIndexCondition>, std::shared_ptr<DB::IMergeTreeDataPart const>, DB::MarkRanges const&, DB::Settings const&, DB::MergeTreeReaderSettings const&, unsigned long&, DB::MarkCache*, DB::UncompressedCache*, Poco::Logger*) @ 0x0000000015238333 in /usr/bin/clickhouse
[c-bordeaux-gr-33-server-1] 2023.09.21 14:57:16.807493 [ 536 ] <Fatal> BaseDaemon: 5. ? @ 0x0000000015234348 in /usr/bin/clickhouse
[c-bordeaux-gr-33-server-1] 2023.09.21 14:57:16.807528 [ 536 ] <Fatal> BaseDaemon: 6. DB::MergeTreeDataSelectExecutor::filterPartsByPrimaryKeyAndSkipIndexes(std::vector<std::shared_ptr<DB::IMergeTreeDataPart const>, std::allocator<std::shared_ptr<DB::IMergeTreeDataPart const>>>&&, std::vector<std::shared_ptr<DB::AlterConversions const>, std::allocator<std::shared_ptr<DB::AlterConversions const>>>&&, std::shared_ptr<DB::StorageInMemoryMetadata const>, std::shared_ptr<DB::Context const> const&, DB::KeyCondition const&, DB::UsefulSkipIndexes const&, DB::MergeTreeReaderSettings const&, Poco::Logger*, unsigned long, std::vector<DB::ReadFromMergeTree::IndexStat, std::allocator<DB::ReadFromMergeTree::IndexStat>>&, bool) @ 0x000000001523153b in /usr/bin/clickhouse
[c-bordeaux-gr-33-server-1] 2023.09.21 14:57:16.807578 [ 536 ] <Fatal> BaseDaemon: 7. DB::ReadFromMergeTree::selectRangesToReadImpl(std::vector<std::shared_ptr<DB::IMergeTreeDataPart const>, std::allocator<std::shared_ptr<DB::IMergeTreeDataPart const>>>, std::vector<std::shared_ptr<DB::AlterConversions const>, std::allocator<std::shared_ptr<DB::AlterConversions const>>>, std::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::shared_ptr<DB::StorageInMemoryMetadata const> const&, DB::SelectQueryInfo const&, std::shared_ptr<DB::Context const>, unsigned long, std::shared_ptr<std::unordered_map<String, long, std::hash<String>, std::equal_to<String>, std::allocator<std::pair<String const, long>>>>, DB::MergeTreeData const&, std::vector<String, std::allocator<String>> const&, bool, Poco::Logger*, std::optional<DB::ReadFromMergeTree::Indexes>&) @ 0x0000000015ab9473 in /usr/bin/clickhouse
[c-bordeaux-gr-33-server-1] 2023.09.21 14:57:16.807625 [ 536 ] <Fatal> BaseDaemon: 8. DB::ReadFromMergeTree::selectRangesToRead(std::vector<std::shared_ptr<DB::IMergeTreeDataPart const>, std::allocator<std::shared_ptr<DB::IMergeTreeDataPart const>>>, std::vector<std::shared_ptr<DB::AlterConversions const>, std::allocator<std::shared_ptr<DB::AlterConversions const>>>, std::shared_ptr<DB::PrewhereInfo> const&, DB::ActionDAGNodes const&, std::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::shared_ptr<DB::StorageInMemoryMetadata const> const&, DB::SelectQueryInfo const&, std::shared_ptr<DB::Context const>, unsigned long, std::shared_ptr<std::unordered_map<String, long, std::hash<String>, std::equal_to<String>, std::allocator<std::pair<String const, long>>>>, DB::MergeTreeData const&, std::vector<String, std::allocator<String>> const&, bool, Poco::Logger*, std::optional<DB::ReadFromMergeTree::Indexes>&) @ 0x0000000015ab4607 in /usr/bin/clickhouse
[c-bordeaux-gr-33-server-1] 2023.09.21 14:57:16.807651 [ 536 ] <Fatal> BaseDaemon: 9. DB::ReadFromMergeTree::selectRangesToRead(std::vector<std::shared_ptr<DB::IMergeTreeDataPart const>, std::allocator<std::shared_ptr<DB::IMergeTreeDataPart const>>>, std::vector<std::shared_ptr<DB::AlterConversions const>, std::allocator<std::shared_ptr<DB::AlterConversions const>>>) const @ 0x0000000015ab42b0 in /usr/bin/clickhouse
[c-bordeaux-gr-33-server-1] 2023.09.21 14:57:16.807693 [ 536 ] <Fatal> BaseDaemon: 10. DB::ReadFromMergeTree::getAnalysisResult() const @ 0x0000000015abc8fa in /usr/bin/clickhouse
[c-bordeaux-gr-33-server-1] 2023.09.21 14:57:16.807720 [ 536 ] <Fatal> BaseDaemon: 11. DB::ReadFromMergeTree::initializePipeline(DB::QueryPipelineBuilder&, DB::BuildQueryPipelineSettings const&) @ 0x0000000015abeaa7 in /usr/bin/clickhouse
[c-bordeaux-gr-33-server-1] 2023.09.21 14:57:16.807749 [ 536 ] <Fatal> BaseDaemon: 12. DB::ISourceStep::updatePipeline(std::vector<std::unique_ptr<DB::QueryPipelineBuilder, std::default_delete<DB::QueryPipelineBuilder>>, std::allocator<std::unique_ptr<DB::QueryPipelineBuilder, std::default_delete<DB::QueryPipelineBuilder>>>>, DB::BuildQueryPipelineSettings const&) @ 0x0000000015a7d2a5 in /usr/bin/clickhouse
[c-bordeaux-gr-33-server-1] 2023.09.21 14:57:16.807784 [ 536 ] <Fatal> BaseDaemon: 13. DB::QueryPlan::buildQueryPipeline(DB::QueryPlanOptimizationSettings const&, DB::BuildQueryPipelineSettings const&) @ 0x0000000015a94d6a in /usr/bin/clickhouse
[c-bordeaux-gr-33-server-1] 2023.09.21 14:57:16.807815 [ 536 ] <Fatal> BaseDaemon: 14. DB::InterpreterSelectWithUnionQuery::execute() @ 0x000000001438adf9 in /usr/bin/clickhouse
[c-bordeaux-gr-33-server-1] 2023.09.21 14:57:16.807842 [ 536 ] <Fatal> BaseDaemon: 15. ? @ 0x00000000146c3b2e in /usr/bin/clickhouse
[c-bordeaux-gr-33-server-1] 2023.09.21 14:57:16.807878 [ 536 ] <Fatal> BaseDaemon: 16. DB::executeQuery(String const&, std::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum) @ 0x00000000146bf42e in /usr/bin/clickhouse
[c-bordeaux-gr-33-server-1] 2023.09.21 14:57:16.807914 [ 536 ] <Fatal> BaseDaemon: 17. DB::TCPHandler::runImpl() @ 0x0000000015681244 in /usr/bin/clickhouse
[c-bordeaux-gr-33-server-1] 2023.09.21 14:57:16.807940 [ 536 ] <Fatal> BaseDaemon: 18. DB::TCPHandler::run() @ 0x0000000015697ff9 in /usr/bin/clickhouse
[c-bordeaux-gr-33-server-1] 2023.09.21 14:57:16.807961 [ 536 ] <Fatal> BaseDaemon: 19. ? @ 0x000000000ebaeffc in /usr/bin/clickhouse
[c-bordeaux-gr-33-server-1] 2023.09.21 14:57:16.807993 [ 536 ] <Fatal> BaseDaemon: 20. Poco::Net::TCPServerConnection::start() @ 0x00000000186a1654 in /usr/bin/clickhouse
[c-bordeaux-gr-33-server-1] 2023.09.21 14:57:16.808021 [ 536 ] <Fatal> BaseDaemon: 21. ? @ 0x00000000186a2871 in /usr/bin/clickhouse
[c-bordeaux-gr-33-server-1] 2023.09.21 14:57:16.808062 [ 536 ] <Fatal> BaseDaemon: 22. Poco::PooledThread::run() @ 0x000000001882ba67 in /usr/bin/clickhouse
[c-bordeaux-gr-33-server-1] 2023.09.21 14:57:16.808112 [ 536 ] <Fatal> BaseDaemon: 23. Poco::ThreadImpl::runnableEntry(void*) @ 0x000000001882949c in /usr/bin/clickhouse
[c-bordeaux-gr-33-server-1] 2023.09.21 14:57:16.808145 [ 536 ] <Fatal> BaseDaemon: 24. ? @ 0x00007f53b4b8eb43 in ?
[c-bordeaux-gr-33-server-1] 2023.09.21 14:57:16.808187 [ 536 ] <Fatal> BaseDaemon: 25. ? @ 0x00007f53b4c20a00 in ?
[c-bordeaux-gr-33-server-1] 2023.09.21 14:57:16.982572 [ 536 ] <Fatal> BaseDaemon: Integrity check of the executable successfully passed (checksum: B60DAA55063C7F37A4029B4ECA186BCD)
[c-bordeaux-gr-33-server-1] 2023.09.21 14:57:17.175501 [ 536 ] <Fatal> BaseDaemon: Report this error to https://github.com/ClickHouse/ClickHouse/issues
[c-bordeaux-gr-33-server-1] 2023.09.21 14:57:17.175698 [ 536 ] <Fatal> BaseDaemon: Changed settings: max_insert_threads = 1, max_threads = 4, use_hedged_requests = false, alter_sync = 0, enable_memory_bound_merging_of_aggregation_results = true, use_mysql_types_in_show_columns = true, log_queries = true, log_queries_probability = 1., max_http_get_redirects = 10, insert_distributed_sync = true, final = true, enable_deflate_qpl_codec = false, max_bytes_before_external_group_by = 4294967296, max_bytes_before_external_sort = 4294967296, max_memory_usage = 8589934592, cancel_http_readonly_queries_on_client_close = true, max_table_size_to_drop = 1000000000000, max_partition_size_to_drop = 1000000000000, default_table_engine = 'ReplicatedMergeTree', mutations_sync = 0, optimize_trivial_insert_select = false, allow_experimental_database_replicated = true, database_replicated_allow_only_replicated_engine = true, cloud_mode = true, distributed_ddl_output_mode = 'none', async_insert_busy_timeout_ms = 1000, enable_filesystem_cache_on_write_operations = true, load_marks_asynchronously = true, allow_prefetched_read_pool_for_remote_filesystem = true, filesystem_prefetch_max_memory_usage = 858993459, filesystem_prefetches_limit = 200, insert_keeper_max_retries = 20, date_time_input_format = 'best_effort'

Error on processing query: Code: 32. DB::Exception: Attempt to read after eof: while receiving packet from oa82c44121.us-west-2.aws.clickhouse.cloud:9440. (ATTEMPT_TO_READ_AFTER_EOF) (version 23.3.2.37 (official build))

Connecting to oa82c44121.us-west-2.aws.clickhouse.cloud:9440 as user default.
Code: 210. DB::NetException: SSL connection unexpectedly closed, while reading from socket (35.85.205.122:9440). (NETWORK_ERROR)
```

### PR DESCRIPTION
**Pull request by antaljanosbenjamin**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Prevent attaching partitions from tables that doesn't have the same indices or projections defined. 

### Documentation entry for user-facing changes

- [X] Documentation is written (mandatory for new features)

Fixes #54896.

Not the best solution in terms flexibility, but at least prevents ClickHouse from crashing. In the future we might allow attaching parts if we can attach the parts easily (e.g.: the source tables has extra indices or tables we might be able to ignore those extra projections and indices.

See slightly related issues #13826 and #39507.

### CODE REVIEW

**Comment by robot-ch-test-poll2** [comment]
*This is an automated comment for commit 97e698b1f1624c23ef9661b56fd6fe061f6f80d9 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/55062/97e698b1f1624c23ef9661b56fd6fe061f6f80d9/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>✅ success</td></tr>
<tbody>
</table>
</details>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>⏳ pending</td></tr>
<tbody>
</table>

**Review by pufit — APPROVED** [review]

**Comment by pufit** [comment]
test_delayed_replica_failover/test.py::test - https://github.com/ClickHouse/ClickHouse/issues/54502
02313_filesystem_cache_seeks  - flaky https://aretestsgreenyet.com/

**Comment by qoega** [comment]
Is it related failure? https://s3.amazonaws.com/clickhouse-test-reports/0/10686479f74ab8161a6c272bf2ec2d012fc025e7/stress_test__msan_.html

**Comment by antaljanosbenjamin** [comment]
I think it is not exactly the same, but it might be connected.

**Pull request merged**
