### PR TITLE
DateTime comparison with date string literal

### PR DESCRIPTION
**Pull request by kitaisreal**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Related to: https://github.com/ClickHouse/ClickHouse/issues/15362

During implementation I first tried to implement it in FunctionsComparison.h executeWithConstString and manually convert string if it is date literal to date time type. During testing there were issues with MergeTree KeyCondition that uses convertFieldToType. 
So I decided to update IO functions and for DateTime and DateTime64 accept Date format.

I also checked and PostgreSQL working with dates same way.

Example:

```

postgres=# CREATE TABLE test(value timestamp);
CREATE TABLE
postgres=# INSERT INTO test VALUES ('2020-10-15 00:00:00')
postgres-# ;
INSERT 0 1
postgres=# INSERT INTO test VALUES ('2020-10-16 00:00:00');
INSERT 0 1
postgres=# SELECT * FROM test;
        value
---------------------
 2020-10-15 00:00:00
 2020-10-16 00:00:00
(2 rows)

postgres=# INSERT INTO test VALUES ('2020-10-16');
INSERT 0 1
postgres=# SELECT * FROM test;
        value
---------------------
 2020-10-15 00:00:00
 2020-10-16 00:00:00
 2020-10-16 00:00:00
(3 rows)

postgres=# SELECT * FROM test WHERE value >= '2020-10-15';
        value
---------------------
 2020-10-15 00:00:00
 2020-10-16 00:00:00
 2020-10-16 00:00:00
(3 rows)

postgres=# SELECT * FROM test WHERE value > '2020-10-15';
        value
---------------------
 2020-10-16 00:00:00
 2020-10-16 00:00:00
(2 rows)

postgres=# INSERT INTO test VALUES ('2020-10-15 12:00:00');
INSERT 0 1
postgres=# SELECT * FROM test WHERE value > '2020-10-15';
        value
---------------------
 2020-10-16 00:00:00
 2020-10-16 00:00:00
 2020-10-15 12:00:00
(3 rows)

```

In https://github.com/ClickHouse/ClickHouse/issues/15362 this example was specified.
```
and

dt > '2020-01-01'
should have the same effect as

dt >= '2020-01-02 00:00:00'
and similar.
``` 
It will be broken in case we have date time in format '2020-01-01 12:00:00' then during dt > '2020-01-01' it will not appear in result set. Also postgreSQL does not work that way.

CC: @alexey-milovidov 

Changelog category (leave one):
- New Feature

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Updated DateTime, DateTime64 formatting to accept string Date literal format.

### CODE REVIEW

**Comment by akuzm** [comment]
Looks like these changes have broken the `parse_engine_file` perf test, and the processing of perf tests itself.

Try to reproduce it locally -- start the server with your changes and run `ClickHouse/docker/test/performance-comparison/perf.py -- ClickHouse/test/performance/parse_engine_file.xml`.

The docs for the perf tests are here: https://github.com/ClickHouse/ClickHouse/tree/master/docker/test/performance-comparison#run-a-single-test-on-the-already-configured-servers

**Comment by kitaisreal** [comment]
@akuzm Okay. Will fix that.

**Comment by kitaisreal** [comment]
@akuzm seems after rebase with master test does not fail

**Comment by akuzm** [comment]
> @akuzm seems after rebase with master test does not fail

They haven't finished yet, let's wait.

**Comment by akuzm** [comment]
Test failures are known and not related to the changes.

**Review by akuzm — APPROVED** [review]

**Pull request merged**
