### PR TITLE
Disable system_tables_lazy_load by default

### PR DESCRIPTION
**Pull request by azat**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Build/Testing/Packaging Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Make `system_tables_lazy_load` false by default

Detailed description / Documentation draft:
- make `system_tables_lazy_load` false by default
- fix test, that existed by did not run and did not passed
- add example into `config.xml`

### CODE REVIEW

**Comment by azat** [comment]
>node3_1     | Indirect leak of 5904 byte(s) in 82 object(s) allocated from:
>node1_1     |     #10 0x1fc47388  (/usr/bin/clickhouse+0x1fc47388)

Is there any plans/work in progress to configure symbolizer?

**Comment by Jokser** [comment]
Hi @azat . Thank you for reporting this. Could you please create an issue about this leak, I'll try to fix it in the nearest time.

**Comment by azat** [comment]
>Build/Testing/Packaging Improvement

Did not find he right tag, feel free to update it to the right one.

**Comment by azat** [comment]
About test failures:

> test_replicated_merge_tree_s3/test.py::test_insert_select_replicated | ERROR

```
2020.05.19 19:28:25.278207 [ 1 ] {} <Error> Application: Caught exception while loading metadata: Code: 499, e.displayText() = DB::Exception: The specified bucket does not exist, Stack trace (when copying this message, always include the lines below):
```

> test_version_update_after_mutation/test.py::test_mutate_and_upgrade | FAILED
> test_version_update_after_mutation/test.py::test_upgrade_while_mutation | FAILED
> test_always_fetch_merged/test.py::test_replica_always_download

all above looks time related

**Review by alexey-milovidov — APPROVED** [review]

**Pull request merged**
