### PR TITLE
Zero-initialize Field::storage so that gcc 7.3.0 doesn't complain

### PR DESCRIPTION
**Pull request by pyos**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
How exactly does it complain?

**Comment by pyos** [comment]
```
/home/pyos/ClickHouse/dbms/src/Core/Field.h: In member function ‘virtual bool DB::ParserSetQuery::parseImpl(DB::IParser::Pos&, DB::ASTPtr&, DB::Expected&)’:
/home/pyos/ClickHouse/dbms/src/Core/Field.h:364:34: error: ‘*((void*)&<anonymous> +8)’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
             case Types::UInt64:  f(field.template get<UInt64>());  return;
                                 ~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
etc.

**Comment by alexey-milovidov** [comment]
It looks like false positive.
We can filter it with `pragma GCC diagnostic`.

I doubt about possible performance differences after this change.
We can test with the cases when many simple Field objects are created. Like `sumMap` aggregate function.

Although usage of multiple small Field objects is already suboptimal.

**Comment by alexey-milovidov** [comment]
Fixed in separate PR.

**Pull request closed without merging**
