### PR TITLE
Implement status comment

### PR DESCRIPTION
**Pull request by Felixoid**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Implement a comment with the status of CI checks. Refactor `commit_status_helper` module: update the status automatically; move `RerunHelper` there. Remove arguments for `S3Helper`, it uses global ENV. Implement the report for all CI checks.

### CODE REVIEW

**Comment by Felixoid** [comment]
Sort first by status, then by name.

Think about a single comment with the link to a combined report. Maybe, update the comment only by the failed checks

**Comment by robot-ch-test-poll4** [comment]
This is an automated comment for commit `5bef39d1d35236821e3cd73a4eee260c9b29e11b` with description of existing statuses

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th><th>Status message</th><th>Optional report URL</th></tr></thead>
<tbody><tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td><td>skipped</td><td><a href="https://github.com/ClickHouse/ClickHouse/actions/runs/4787589532">Report</a></td></tr>
<tr><td>Style Check</td><td>Runs a set of checks to keep the code style clean. If some of tests failed, see the related log from the report.</td><td>🟢 success</td><td>Style check success</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/48468/5bef39d1d35236821e3cd73a4eee260c9b29e11b/style_check.html">Report</a></td></tr>
</table>

**Comment by robot-ch-test-poll1** [comment]
This is an automated comment for commit `a3f8a4024ad7a69536a85c148730ff69dabaea52` with description of existing statuses

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th><th>Status message</th><th>Optional report URL</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in `success` or `pending` state. The failed status indicates some problems with the PR</td><td>🟡 pending</td><td>No special conditions apply</td><td></td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td><td>skipped</td><td><a href="https://github.com/ClickHouse/ClickHouse/actions/runs/4787713561">Report</a></td></tr>
</table>

**Comment by Felixoid** [comment]
It's good to go :+1:

**Comment by azat** [comment]
@Felixoid maybe it worth to submit a comment only once checks had been passed? Otherwise what's the difference between this comment and all checks above the comment form in github?

**Comment by Felixoid** [comment]
The idea of the comment is quite orthogonal to the statuses on the commit:

- It's always the first comment because it's created almost instantly after the PR is created
- It's a digest of all checks that applied to the latest comment. With the description of each check + the general report
- It's updated on each new status because there's no other reliable way to basically know if the current status is the last or no

Does it address your concern?

**Comment by azat** [comment]
> It's always the first comment because it's created almost instantly after the PR is created

I see

> It's a digest of all checks that applied to the latest comment.

I talked about "checks below the comment form" they are also updated for the latest commit in the PR.

> With the description of each check + the general report

So it has some descriptions in comparison to checks that is provided by github automatically.

> It's updated on each new status because there's no other reliable way to basically know if the current status is the last or no

So as the checks status below the comment form for PRs, right?

Also I've noticed only now that it contains only list of unique checks (i.e. one statless check for debug/release/...)

_P.S. This is just out of curiosity by the way..._

**Comment by azat** [comment]
@Felixoid by the way, what do you think about sorting checks in the comment, and display failures first?

**Comment by azat** [comment]
>It's not trivial. See [master/tests/ci/commit_status_helper.py#L197-L204](https://github.com/ClickHouse/ClickHouse/blob/master/tests/ci/commit_status_helper.py?rgh-link-date=2023-05-02T12%3A16%3A33Z#L197-L204)

Not sure that I understand why, but it seems to me that you can sort `grouped_statuses` by status before, and do not sort the table (`table_rows.sort()`) ?

By the way, maybe this comment will be more useful if it will include only failures, what do you think @Felixoid ?

**Comment by Felixoid** [comment]
> will be more useful if it will include only failures

No, it's as well the description for each check involved in the PR. 

Regarding sorting, it requires reworking `get_worst_status` and basically just a beautification. Don't know, if it worth, somebody will add it. I have a big pile of urgent tasks after that `¯\_(ツ)_/¯`

**Pull request merged**
