### PR TITLE
Experiment with huge pages

### PR DESCRIPTION
**Pull request by nickitat**
### Changelog category (leave one):
- Performance Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
todo

### CODE REVIEW

**Comment by robot-ch-test-poll2** [comment]
This is an automated comment for commit fac840d492fb4042933ea9b84bd669c0b3c5dc23 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/52157/fac840d492fb4042933ea9b84bd669c0b3c5dc23/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Comment by nickitat** [comment]
perf tests are good. but there is seemingly a better strategy:
1. request HP directly from mmap
2. if failed request HP-s through `madvise` call

should be better for short-living allocations.

**Comment by nickitat** [comment]
afaiu we could emulate this without explicit use of `mmap` with some hooks: https://github.com/jemalloc/jemalloc/blob/dev/TUNING.md#beyond-runtime-options

**Comment by nickitat** [comment]
old perf tests:
https://s3.amazonaws.com/clickhouse-test-reports/52157/cade7dce7a4c8ffe649e4d752ef7e4a2eeffd9ea/performance_comparison_[1_4]/report.html
https://s3.amazonaws.com/clickhouse-test-reports/52157/cade7dce7a4c8ffe649e4d752ef7e4a2eeffd9ea/performance_comparison_[2_4]/report.html
https://s3.amazonaws.com/clickhouse-test-reports/52157/cade7dce7a4c8ffe649e4d752ef7e4a2eeffd9ea/performance_comparison_[3_4]/report.html

**Comment by alexey-milovidov** [comment]
@nickitat, I like this change*. The code is clean. Did it help?

\* However, I already did this change maybe ~10 years ago, and it led to a significant degradation of performance, visible only after several days of production workload, because Linux kernel didn't do either defragmentation or page coalescing.

**Comment by nickitat** [comment]
> @nickitat, I like this change*. The code is clean. Did it help?
> 
> * However, I already did this change maybe ~10 years ago, and it led to a significant degradation of performance, visible only after several days of production workload, because Linux kernel didn't do either defragmentation or page coalescing.

It did, per se. The plan how to avoid the defragmentation problem was to use the fact that we manually call `mmap` for big allocations, so we could request HP only for such mappings and hence make sure that HP-s never "leak" to the "general" working set managed by `jemalloc`. Since then, we removed these explicit `mmap` calls, and `jemalloc` manages all the allocations. So, we need to implement a slightly different approach. The approach suggested by `jemalloc` implementation is to create a separate arena with memory backed by HP-s. In this scheme, `madvise` will be done inside the custom allocation hook for this arena. This is [implemented](https://github.com/facebook/hhvm/blob/master/third-party/folly/src/folly/memory/JemallocHugePageAllocator.cpp#L405) in `HHVM`.

**Pull request closed without merging**
