### PR TITLE
Do not allow to create tables while database is being dropped

### PR DESCRIPTION
**Pull request by alexey-milovidov**
Changelog category (leave one):
- Not for changelog (changelog entry is not required)

See https://clickhouse-test-reports.s3.yandex.net/27677/dafb75c6041dadc1f1e0e8a1882fa270e351426a/stress_test_(thread).html#fail1

#27677
#27538

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
@tavplubix It does not work.

**Comment by tavplubix** [comment]
> @tavplubix It does not work.

As expected, It's not enough to just lock database earlier.
But how is it related to stress test failure and linked PRs?

**Comment by alexey-milovidov** [comment]
I see that in stress test, Lazy database cannot be removed because "directory is not empty".
I checked that every table is removed before removing the database (and it looks like that this include the unloaded tables as well).
So I suspect that another table is created in between.

**Comment by tavplubix** [comment]
> another table is created in between.

No, directory is not empty, because there are detached tables in database. And test does not handle it correctly...

https://github.com/ClickHouse/ClickHouse/blob/a25fa1996b4e7d7db4c469b6fa484774202b71f8/tests/queries/0_stateless/01014_lazy_database_concurrent_recreate_reattach_and_show_tables.sh#L108-L122

**Comment by alexey-milovidov** [comment]
Ok, thank you!

**Pull request closed without merging**
