### PR TITLE
Fix sigabrt while getting PostgreSQL table structure

### PR DESCRIPTION
**Pull request by myrrc**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Handle sigabrt case when getting PostgreSQl table structure with empty array

### CODE REVIEW

**Comment by robot-ch-test-poll2** [comment]
*This is an automated comment for commit 4ef906556780a44c3520755674ef9142f0271e63 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/57618/4ef906556780a44c3520755674ef9142f0271e63/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td><a href="https://github.com/ClickHouse/ClickHouse/actions/runs/7129030987">✅ success</a></td></tr>
<tbody>
</table>
</details>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/57618/4ef906556780a44c3520755674ef9142f0271e63/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Comment by myrrc** [comment]
Reproduced on our side in `23.8.8.20`

**Comment by myrrc** [comment]
@jsc0218 If merged, backports to 23.8 would be highly appreciated

**Comment by alexey-milovidov** [comment]
@myrrc 

> Bugfix validate check — Changed tests don't reproduce the bug

**Comment by myrrc** [comment]
> @myrrc
> 
> > Bugfix validate check — Changed tests don't reproduce the bug

Unfortunately, we haven't been able to reproduce the bug every time, it's appearing every now and then. I've attached the stack trace.

I will add the test but pretty sure it will be marked as flaky by CI.

**Comment by alexey-milovidov** [comment]
Changed from "bug fix" to "improvement". Now it will be acceptable without a test.

**Review by alexey-milovidov — APPROVED** [review]

**Comment by jsc0218** [comment]
I doubt whether we should set it to 0, due to some limitation in postgres's array_ndims itself, please see cases detailed in issue#57436

**Comment by myrrc** [comment]
Related: https://github.com/ClickHouse/ClickHouse/pull/57436

**Comment by jsc0218** [comment]
> Related: #57436

yes, so I think it is better to throw an exception instead of 0, due to the cases like first row null or empty while remaining rows are not.

**Comment by myrrc** [comment]
Well, at least we should catch that exception instead of sigabrt'ing.
However, in this particular case we've observed (table structure that we get is used for creating a backup) this fix so far works ok

**Comment by jsc0218** [comment]
> Well, at least we should catch that exception instead of sigabrt'ing. However, in this particular case we've observed (table structure that we get is used for creating a backup) this fix so far works ok

agree, let's take you approach as temporary, then approach in  https://github.com/ClickHouse/ClickHouse/pull/57436 as a permanen.

**Pull request merged**
