### PR TITLE
Add database_replicated_allow_only_replicated_engine setting.

### PR DESCRIPTION
**Pull request by KochetovNicolai**
Changelog category (leave one):
- New Feature

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Add `database_replicated_allow_only_replicated_engine` setting. When enabled, it only allowed to create `Replicated` tables in `Replicated` database.

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
This is incorrect.

We should allow to create tables that don't store data or that are replicated.

**Comment by KochetovNicolai** [comment]
Right, I did forget to check is storage has a data on disk.
Still, I though to implement it only for database `Replicated`. Should we do it for every database engine? (if so, at least we should check that query_log can be created locally).

**Comment by alexey-milovidov** [comment]
Yes, only for Replicated database.

**Comment by KochetovNicolai** [comment]
Failed tests are flaky. Will merge.

**Pull request merged**
