### PR TITLE
improve kafka parsing performance 

### LINKED ISSUE #7261: Kafka: performance regression in 19.15
We need to improve kafka consuming performance, degraded after #6950 (which is very important and desired change in all other aspects).

### PR DESCRIPTION
**Pull request by filimonov**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Performance Improvement

Changelog entry (up to few sentences, required except for Non-significant/Documentation categories):
Fix performance regression introduced in 19.15.  

Detailed description (optional):
Fixes #7261

### CODE REVIEW

**Comment by filimonov** [comment]
intermediate results:
```
┌─version()────┬─record_count─┬─produce_time─┬─────produce_speed─┬─consume_time─┬──────consume_speed─┐
│ 19.14.7.15   │     335
54432 │           50 │         671088.64 │          203 │  165292.7684729064 │
│ 19.15.3.6    │     33554432 │           42 │ 798915.0476190476 │          623 │   53859.4414125200 │
│ 19.17.1.1557 │     33554432 │           39 │ 860370.0512820513 │          499 │   67243.3507014028 │
│ 19.18.1.1745 │     33554432 │           34 │ 986895.0588235294 │          276 │ 121574.02898550725 │
└──────────────┴──────────────┴──────────────┴───────────────────┴──────────────┴────────────────────┘
```

**Comment by alexey-milovidov** [comment]
The results are very promising!

**Comment by filimonov** [comment]
intermediate results #2

```
# ┌─version()────┬─record_count─┬─consume_time─┬──────consume_speed─┐
# │ 19.14.7.15   │     33554432 │          203 │  165292.7684729064 │
# │ 19.15.3.6    │     33554432 │          623 │   53859.4414125200 │
# │ 19.17.1.1557 │     33554432 │          499 │   67243.3507014028 │
# │ 19.18.1.1745 │     33554432 │          276 │  121574.0298550725 │
# │ 19.18.1.1747 │     33554432 │          241 │  139230.0082987552 │
# └──────────────┴──────────────┴──────────────┴────────────────────┘
```

**Comment by filimonov** [comment]
OK. Now we are back with the original performance in the case when each message contains one row (tested on TSV). In cases when one message contains more rows new versions should be a bit faster than the older one.  
```
# ┌─version()────┬─record_count─┬─consume_time─┬──────consume_speed─┐
# │ 19.14.7.15   │     33554432 │          203 │  165292.7684729064 │
# │ 19.15.3.6    │     33554432 │          623 │   53859.4414125200 │
# │ 19.17.1.1557 │     33554432 │          499 │   67243.3507014028 │
# │ 19.18.1.1745 │     33554432 │          276 │  121574.0298550725 │
# │ 19.18.1.1747 │     33554432 │          241 │  139230.0082987552 │
# │ 19.18.1.1750 │     33554432 │          204 │  164482.5098039215 │
# └──────────────┴──────────────┴──────────────┴────────────────────┘
```

perf report look like that now:
```
   - DB::BackgroundSchedulePoolTaskInfo::execute                                                                                                                                                           ▒
      - 88.81% DB::StorageKafka::threadFunc                                                                                                                                                                ▒
         - 88.81% DB::StorageKafka::streamToViews                                                                                                                                                          ▒
            - 88.80% DB::copyData                                                                                                                                                                          ▒
               - 86.79% DB::IBlockInputStream::read                                                                                                                                                        ▒
                  - 85.95% DB::KafkaBlockInputStream::readImpl                                                                                                                                             ▒
                     - 65.07% DB::ISource::work                                                                                                                                                            ▒
                        - 63.95% DB::IRowInputFormat::generate                                                                                                                                             ▒
                           + 30.34% DB::TabSeparatedRowInputFormat::readRow                                                                                                                                ▒
                           + 16.43% DB::Block::cloneEmptyColumns                                                                                                                                           ▒
                             3.59% DB::KafkaBlockInputStream::readImpl()::{lambda()#1}::operator()                                                                                                         ▒
                           + 1.36% DB::ColumnString::~ColumnString                                                                                                                                         ▒
                           + 1.36% DB::ColumnVector<unsigned long>::~ColumnVector                                                                                                                          ▒
                           + 1.34% operator delete                                                                                                                                                         ▒
                           + 1.12% operator delete                                                                                                                                                         ▒
                           + 0.88% DB::Chunk::Chunk                                                                                                                                                        ▒
                             0.87% sdallocx                                                                                                                                                                ▒
                             0.87% free                                                                                                                                                                    ▒
                           + 0.85% DB::TabSeparatedRowInputFormat::readPrefix                                                                                                                              ▒
                     + 3.18% DB::ColumnString::~ColumnString                                                                                                                                               ▒
                     + 2.06% DB::ColumnVector<unsigned long>::~ColumnVector                                                                                                                                ▒
                       2.00% DB::ISource::prepare                                                                                                                                                          ▒
                     + 1.69% DB::ColumnVector<unsigned int>::~ColumnVector                                                                                                                                 ▒
                       1.17% operator delete                                                                                                                                                               ▒
                       1.04% DB::ColumnString::insertRangeFrom                                                                                                                                             ▒
                       1.02% sdallocx                                                                                                                                                                      ▒
                     - 0.85% DB::TabSeparatedRowInputFormat::resetParser                                                                                                                                   ▒
                        - 0.81% DB::RowInputFormatWithDiagnosticInfo::resetParser                                                                                                                          ▒
                           - 0.70% DB::IRowInputFormat::resetParser                                                                                                                                        ▒
                                DB::IInputFormat::resetParser                                                                                                                                              ▒
                       0.82% memcpy                                                                                                                                                                        ▒
                       0.55% DB::ColumnVector<double>::~ColumnVector                                                                                                                                       ▒
                       0.54% DB::ColumnVector<unsigned int>::insertRangeFrom                                                                                                                               ▒
               + 1.98% DB::CountingBlockOutputStream::write  
``` 

As a subject for further optimizations - there is also a possibility to pass the target
set of columns directly to the parser instead of creating a new set of columns inside and copy them back to target.  that should remove the influence of cloneEmptyColumns and destructors on the performance. That can be done later if will be needed.

For now that should be enough - i want that PR not to influence or change too many things 
to consider it as a bugfix which can be backported to 19.15 / 19.16.

**Comment by filimonov** [comment]
TODO:
[ ] review
[ ] cleanups and after-review fixes 
[ ] tests of inserts in different formats (probably will do that outside of your CI)

**Comment by abyss7** [comment]
Looks good - let's make some cleanup and merge.

**Review by alexey-milovidov — APPROVED** [review]

**Pull request merged**
