### PR TITLE
ALL may not be used in combination with other expressions in the ORDER BY clause

### LINKED ISSUE #59151: Surprising behavior of `ORDER BY ALL` in some cases
- [ ] `SELECT * FROM order_by_all ORDER BY all` should work but it does not
- [ ] To reduce ambiguity, we should unconditionally (independently of setting `enable_order_by_all`) throw an error when `ALL` (case-insensitive: also `all`) appears in `ORDER BY` together with other columns/aliases/expressions. Right now, `SELECT a, b, all FROM order_by_all ORDER BY all, a` works and `all` loses its special meaning.

Also see https://github.com/ClickHouse/ClickHouse/pull/57875#discussion_r1464797988

### PR DESCRIPTION
**Pull request by zhongyuankai**
close #59151 

To reduce ambiguity. `ALL` may not be used in combination with other expressions in the `ORDER BY` clause.

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by robot-clickhouse** [comment]
*This is an automated comment for commit d774d42064a36f8fe1ffe7558d397a4243bb4b2b with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/59247/d774d42064a36f8fe1ffe7558d397a4243bb4b2b/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/59247/d774d42064a36f8fe1ffe7558d397a4243bb4b2b/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Review by novikd — CHANGES_REQUESTED** [review]
This implementation just forbids using a column with the name `ALL`.

**Comment by zhongyuankai** [comment]
@novikd Thank you for your reply. It would be better to split the parser `ORDER BY ALL`.

**Comment by rschu1ze** [comment]
As per #59450, the behavior that this PR tries to achieve is already implemented:

https://fiddle.clickhouse.com/48d97dbd-83ba-471c-8b7e-9ea67e84ac93

**Pull request closed without merging**
