### PR TITLE
Fix test_replica_is_active flaky test

### PR DESCRIPTION
**Pull request by alesapin**
Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by alesapin** [comment]
```____________________________ test_replica_is_active ____________________________
[gw3] linux -- Python 3.8.10 /usr/bin/python3

start_cluster = <helpers.cluster.ClickHouseCluster object at 0x7f13fb3ff3a0>

    def test_replica_is_active(start_cluster):
        query_result = node1.query("select replica_is_active from system.replicas where table = 'test_table'")
>       assert query_result == '{\'node1\':1,\'node2\':1,\'node3\':1}\n'
E       assert "{'node3':1,'node2':1,'node1':1}\n" == "{'node1':1,'node2':1,'node3':1}\n"
E         - {'node1':1,'node2':1,'node3':1}
E         ?       ^                   ^
E         + {'node3':1,'node2':1,'node1':1}
E         ?       ^                   ^
```

**Comment by alesapin** [comment]
Order is not important.

**Review by kitaisreal — APPROVED** [review]

**Comment by alesapin** [comment]
```test_ttl_replicated/test.py::test_modify_ttl``` another flaky test :(((

**Comment by alesapin** [comment]
Flaky check ok

**Pull request merged**
