### PR TITLE
Read Parquet files even faster

### PR DESCRIPTION
**Pull request by al13n321**
### Changelog category (leave one):
- Performance Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
 * Better performance when reading local Parquet files (through parallel reading).
 * Better performance for url() table function in any format (through connection pooling).
 * Fix http_skip_not_found_url_for_globs not working for compressed files.

---

Parquet's parallel random reads from local file are now actually parallel (pread() calls or memcpy from mmap), instead of locking two mutexes for no reason.

---

Added some limited HTTP session pooling for StorageURL. Sessions are now reused by all (non-concurrent) read operations on the same ReadBuffer. This makes `SELECT count(*)` from remote (different region) parquet files 2.5x faster!

We should add similar pooling for StorageS3, but that'll take more work: there's no simple way to attach the pool to a ReadBufferFromS3 instance, so it's either a global pool (with more care for eviction policy and correctness) or some hacks to indirectly pass a pool pointer to PocoHTTPClient.

---

Fixed a confusing error message when getting HTTP 404 error: it used to say "Not a Parquet file" because asArrowFileLoadIntoMemory() was catching exceptions too eagerly.

---

The behavior for skipping not-found URLs for globs was kind of inconsistent, in part broken by me in https://github.com/ClickHouse/ClickHouse/pull/47964

It skipped files by pretending that they're empty. This didn't work when the file is compressed - the decompression would error out trying to decompress an empty string.

Fixed by explicitly skipping the URL if the initial HTTP request failed, without pretending that the file is empty.

---

`input_format_parquet_preserve_order` now implies `parallelize_output_from_storages`.

---

In https://github.com/ClickHouse/ClickHouse/pull/47964 I refactored things to use SeekableReadBufferFactory in more places, as *the* abstraction for random-access "files". I think that was a mistake.

This PR re-refactors everything in the opposite direction: it adds a thread-safe positioned-read method in SeekableReadBuffer and uses it whenever parallel random reading is needed (ParallelReadBuffer and ParquetBlockInputFormat). This turned out better than the factory stuff, I think: less (?) code, fewer boilerplate objects, less useless extra cpu work (like maintaining a pool of ReadBuffers to reuse), less awkward code like `if`s everywhere for buffer vs factory. The factory is removed altogether.

---

Inverted how `attachSessionData()` is used for marking whether HTTP sessions can be reused. Sessions were considered reusable by default, and ReadWriteBufferFromHTTP had to mark them as non-reusable on any error. It was missing some cases because there are lots of them. This PR flips it - the sessions are not reusable unless marked as reusable, which ReadWriteBufferFromHTTP does after receiving full response successfully. It seems silly that any of this needs to be done at all, instead of HTTPClientSession doing this tracking internally; but this was less work than changing HTTPClientSession.

---

Split ReadWriteBufferFromHTTP from header-only into a .h and .cpp files. This had no (easily-) measurable effect on build time (I ran a clean build 3 times with and without the change, difference was within the noise, which was ~0.1%). So I probably won't waste time on this type of refactoring in future :)

### CODE REVIEW

**Comment by al13n321** [comment]
> I'm still not sure whether the SeekableReadBufferFactoryPtr stuff was the right way to parallelize reading in the first place. Maybe instead there should be an optional thread-safe pread-like method in SeekableReadBuffer. Sounds like less code and more speed. I should try that.

Doing this. It turned out ok, probably better than the factory nonsense. But I was hoping to also get rid of the factory in ParallelReadBuffer, then realized it wouldn't work as well: it currently streams data from each read range, in smaller chunks (whatever size the read buffer returns); with a 'readBigAt()' method it would only be able to read the whole range at once; e.g. at default 10 MB ranges, on slow connection, it can be tens of seconds with no progress. So I guess we'll have both the factory and the `readBigAt()`. If anyone has better ideas, plz lmk, I'm going crazy over this :)

Also added session reuse in ReadWriteBufferFromHTTP, it sped up `SELECT count(*)` by 2.5x when reading from different region. Need to add it to S3 too, that's a little more work.

**Comment by robot-clickhouse** [comment]
This is an automated comment for commit 252c8a5e789e2fbe8415e4157c0bbcf6d777ca76 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/49121/252c8a5e789e2fbe8415e4157c0bbcf6d777ca76/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Comment by devcrafter** [comment]
I wonder if it would be possible to break the PR to smaller gradual PRs (according to the description, it addresses many issues at once, so looks feasible). It's quite inconvenient for reviewer big PRs.  Generally, smaller gradual changes are better.

**Comment by al13n321** [comment]
Ok, will split.

**Comment by al13n321** [comment]
https://github.com/ClickHouse/ClickHouse/pull/49536 https://github.com/ClickHouse/ClickHouse/pull/49533 https://github.com/ClickHouse/ClickHouse/pull/49539 https://github.com/ClickHouse/ClickHouse/pull/49540 https://github.com/ClickHouse/ClickHouse/pull/49541

**Comment by al13n321** [comment]
@devcrafter, is there a good way to do dependent PRs?

For https://github.com/ClickHouse/ClickHouse/pull/49539 , https://github.com/ClickHouse/ClickHouse/pull/49540 , and https://github.com/ClickHouse/ClickHouse/pull/49541 I've set base branch to the parent PR's branch. The list of commits in each PR is correct, but CI didn't run any of the checks.

**Comment by qoega** [comment]
No good way in GitHub. But if you merge PR that incorporates some other PRs, they are marked as merged. So you can test and review  separately and merge all at once

**Comment by qoega** [comment]
> It's quite inconvenient for reviewer big PRs. Generally, smaller gradual changes are better.

We rarely ask to split PRs. There is an option to review changes per commit if history is split into separate commits

**Comment by devcrafter** [comment]
> @devcrafter, is there a good way to do dependent PRs?
> 
> For #49539 , #49540 , and #49541 I've set base branch to the parent PR's branch. The list of commits in each PR is correct, but CI didn't run any of the checks.

As mentioned already, unfortunately there is no good way for dependent PRs. [Gerrit](https://www.gerritcodereview.com/) does it much better, but it's a different story. 
Currently, the way to trigger PR is to change parent branch in PR (press `Edit` button near PR name and choose master). It's inconvenient since the PR will contain diff from master to PR branch (i.e. including parent branch), but you can switch the PR parent branch to see exact diff.

**Comment by devcrafter** [comment]
> > It's quite inconvenient for reviewer big PRs. Generally, smaller gradual changes are better.
> 
> We rarely ask to split PRs. 

imo, It makes sense here. To what degree, the author can decide himself (and it's nice if the author considers reviewer PoV)

> There is an option to review changes per commit if history is split into separate commits

It doesn't work since most of the time authors doesn't put effort to separate commits logically (it's also not necessary). Just tackling different issues in different PRs already helps.

**Comment by al13n321** [comment]
I'm ok with it here, it was a bit messy. But it did take 2-3 hours.

**Pull request closed without merging**
