### PR TITLE
Install script for tgz package

### PR DESCRIPTION
**Pull request by alesapin**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Build/Testing/Packaging Improvement

Changelog entry (up to few sentences, required except for Non-significant/Documentation categories):
Add install scripts for .tgz packages.

### CODE REVIEW

**Comment by alesapin** [comment]
Unfortunately, now it works out of the box only for centos and ubuntu :(
```centos:
[root@click package_dir]# tar -xzvf clickhouse-common-static-20.1.1.2074.tgz
[root@click package_dir]# tar -xzvf clickhouse-server-20.1.1.2074.tgz
[root@click package_dir]# tar -xzvf clickhouse-client-20.1.1.2074.tgz
[root@click package_dir]# cd clickhouse-common-static-20.1.1.2074/install
[root@click install]# ./doinst.sh
[root@click install]# cd ../../clickhouse-server-20.1.1.2074/install/
[root@click install]# ./predoinst.sh
[root@click install]# ./doinst.sh
Path to data directory in /etc/clickhouse-server/config.xml: /var/lib/clickhouse/
./doinst.sh: line 133: /tmp/test_setcap.sh: Operation not permitted
Cannot set 'net_admin' or 'ipc_lock' or 'sys_nice' capability for clickhouse binary. This is optional. Taskstats accounting will be disabled. To enable taskstats accounting you may add the required capability later manually.
[root@click package_dir]# cd ../../clickhouse-client-20.1.1.2074/install/
[root@click install]# ./doinst.sh
[root@click install]# /etc/init.d/clickhouse-server start
[root@click install]# clickhouse-client
click.sas.yp-c.yandex.net :) select 1

SELECT 1

┌─1─┐
│ 1 │
└───┘

ubuntu:
root@click:/package_dir# cd clickhouse-common-static-20.1.1.2074/install
root@click:/package_dir/clickhouse-common-static-20.1.1.2074/install# ./doinst.sh
root@click:/package_dir/clickhouse-common-static-20.1.1.2074/install# cd ../../clickhouse-server-20.1.1.2074/install
root@click:/package_dir/clickhouse-server-20.1.1.2074/install# ./predoinst.sh
root@click:/package_dir/clickhouse-server-20.1.1.2074/install# ./doinst.sh configure
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 76.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (Can't locate Term/ReadLine.pm in @INC (you may need to install the Term::ReadLine module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.26.1 /usr/local/share/perl/5.26.1 /usr/lib/x86_64-linux-gnu/perl5/5.26 /usr
/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.26 /usr/share/perl/5.26 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /usr/share/perl5/Debconf/FrontEnd/Readline.pm line 7.)
debconf: falling back to frontend: Teletype
Path to data directory in /etc/clickhouse-server/config.xml: /var/lib/clickhouse
Cannot set 'net_admin' or 'ipc_lock' or 'sys_nice' capability for clickhouse binary. This is optional. Taskstats accounting will be disabled. To enable taskstats accounting you may add the required capability later manually.
root@click:/package_dir/clickhouse-server-20.1.1.2074# service clickhouse-server start
root@click:/package_dir/clickhouse-common-static-20.1.1.2074/install# cd ../../clickhouse-client-20.1.1.2074/install
root@click:/package_dir/clickhouse-client-20.1.1.2074/install# ./doinst.sh
root@click:/package_dir/clickhouse-client-20.1.1.2074/install# clickhouse-client
click.sas.yp-c.yandex.net :) select 1
SELECT 1

┌─1─┐
│ 1 │
└───┘
```

ArchLinux and Gentoo require the installation of `adduser` script.

**Comment by alexey-milovidov** [comment]
I remember that @proller has replaced `useradd` to `adduser` for unknown reason, but it introduced extra dependency.

**Comment by alesapin** [comment]
Not it should work for `gentoo` and `arch`. Will test package after build.

**Review by alexey-milovidov — APPROVED** [review]

**Review by proller — APPROVED** [review]

**Comment by alesapin** [comment]
Works for `gentoo` and `archlinux`!
```
$ docker run --network=host --volume=`pwd`/tgzs:/package_dir -it gentoo/stage3-amd64 bash
click / # cd /package_dir/clickhouse-common-static-20.1.1.2088/install
click /package_dir/clickhouse-common-static-20.1.1.2088/install # ./doinst.sh
click /package_dir/clickhouse-common-static-20.1.1.2088/install # cd ../../clickhouse-server-20.1.1.2088/install 
click /package_dir/clickhouse-server-20.1.1.2088/install # ./predoinst.sh
click /package_dir/clickhouse-server-20.1.1.2088/install # ./doinst.sh

Path to data directory in /etc/clickhouse-server/config.xml: /var/lib/clickhouse/
Cannot set 'net_admin' or 'ipc_lock' or 'sys_nice' capability for clickhouse binary. This is optional. Taskstats accounting will be disabled. To enable taskstats accounting you may add the required capability later manually.

click /package_dir/clickhouse-server-20.1.1.2088/install # /etc/init.d/clickhouse-server start
Start clickhouse-server service: Path to data directory in /etc/clickhouse-server/config.xml: /var/lib/clickhouse/
DONE
click /package_dir/clickhouse-server-20.1.1.2088/install # cd ../../clickhouse-client-20.1.1.2088/install
click /package_dir/clickhouse-client-20.1.1.2088/install # ./doinst.sh
click /package_dir/clickhouse-client-20.1.1.2088/install # clickhouse-client
ClickHouse client version 20.1.1.2088.
Connecting to localhost:9000 as user default.
Connected to ClickHouse server version 20.1.1 revision 54431.

click.sas.yp-c.yandex.net :) select 1

SELECT 1

┌─1─┐
│ 1 │
└───┘

1 rows in set. Elapsed: 0.001 sec.
```

**Comment by alexey-milovidov** [comment]
Ok. Now we need a snippet for the website
`Install packages for Ubuntu/Debian or CentOS/RedHat or Other Linux:`

**Pull request merged**
