### PR TITLE
Fix wrong row id when using full text index with multi column

### LINKED ISSUE #68643: Full text index may filter out wrong columns when index multiple columns
**Describe the unexpected behaviour**
When using full text index with multiple columns, it may filter out some rows which contains the data.

**How to reproduce**
```sql
CREATE TABLE tab (
    v0 String,
    v1 String,
    INDEX idx (v0, v1) TYPE full_text GRANULARITY 1)
ENGINE = MergeTree
ORDER BY tuple()
SETTINGS index_granularity = 1;

INSERT INTO tab VALUES('0,0', '0,1')('2,2','2,3');

-- Return 0 rows
SELECT * FROM tab WHERE hasToken(v1, '1');
```

**Expected behavior**
```sql
--   ┏━━━━━┳━━━━━┓
--   ┃ v0  ┃ v1  ┃
--   ┡━━━━━╇━━━━━┩
--1. │ 0,0 │ 0,1 │
--   └─────┴─────┘
SELECT * FROM tab WHERE hasToken(v1, '1');
```

### PR DESCRIPTION
**Pull request by linkwk7**
fix #68643 

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Full text index may filter out wrong columns when index multiple columns, it didn't reset row_id between different columns, the reproduce procedure is in tests/queries/0_stateless/03228_full_text_with_multi_col.sql. Without this 

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Run only fuzzers related jobs (libFuzzer fuzzers, AST fuzzers, etc.)
- [ ]  Exclude: AST fuzzers
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Review by vdimir — APPROVED** [review]

**Comment by robot-clickhouse** [comment]
*This is an automated comment for commit f12840eb5f289aca0d8ada4cde4c902be00de993 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/68644/f12840eb5f289aca0d8ada4cde4c902be00de993/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/68617/677b28e1ac5f0962f1e43ba7589787105c5f1553/docs_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Comment by linkwk7** [comment]
@vdimir hi, i check the failed integration test test_disk_over_web_server, seems not related to this change, the created table didn't use skip index. is there any method i can rerun the failed cases?

**Comment by vdimir** [comment]
> @vdimir hi, i check the failed integration test test_disk_over_web_server, seems not related to this change, the created table didn't use skip index. is there any method i can rerun the failed cases?

I'll merge with master

**Comment by linkwk7** [comment]
@vdimir hi, please take a look if this MR ok to merge?

**Review by vdimir — APPROVED** [review]

**Comment by vdimir** [comment]
> Performance Comparison (release) [1/4] — 2 errors [Details](https://s3.amazonaws.com/clickhouse-test-reports/68644/50e08ed4f4ab9afd38b67494da0876a1298b011b/performance_comparison__release__[1_4]/report.html)

Same as https://github.com/ClickHouse/ClickHouse/pull/68867#issuecomment-2312563224 , fixing in https://github.com/ClickHouse/ClickHouse/pull/68957

**Pull request merged**
