### PR TITLE
Omit frame pointer.

### PR DESCRIPTION
**Pull request by amosbird**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Performance Improvement

Changelog entry (up to few sentences, required except for Non-significant/Documentation categories):

omit frame pointer globally to spare one more register. Let's see how perf test goes.

### CODE REVIEW

**Comment by amosbird** [comment]
Perf tests run wild again.

**Comment by alexey-milovidov** [comment]
It's basically Ok (and 1% better overall: https://clickhouse-test-reports.s3.yandex.net/8097/9a40c97e2938cbc7071ca29add80bfde4f74554e/performance_test/comparison_min_time_gcc_9.html), but need to validate two queries manually:

```
SELECT  count() FROM system.numbers WHERE NOT  ignore(visitParamExtractRaw(materialize('{"myparam":{"nested_1":"test_string","nested_2":"test_2"}}'),  'myparam'))
```

```
SELECT count() FROM system.numbers WHERE NOT ignore(visitParamExtractRaw(materialize('{"myparam":{"nested_1":"test_string","nested_2":"test_2","nested_1":"test_string","nested_2":"test_2","nested_1":"test_string","nested_2":"test_2"}}'), 'myparam'))
```

**Comment by amosbird** [comment]
I've been seeing these two queries failing from time to time (with the exact regression rate 85%).

**Comment by alexey-milovidov** [comment]
Ok.

**Comment by alesapin** [comment]
Unfortunately, without this option, we broke exceptions handling in clang release build. It doesn't test in CI (we will add it), but it's common build type for developers. 
```
$ cmake ../ClickHouse -DENABLE_TESTS=0 -DENABLE_UTILS=0 -DCMAKE_CXX_COMPILER=/usr/bin/clang++-8 -DCMAKE_C_COMPILER=/usr/bin/clang-8  -DENABLE_TESTS=0 -DENABLE_UTILS=0 -DCMAKE_CXX_COMPILER=/usr/bin/clang++-8 -DCMAKE_C_COMPILER=/usr/bin/clang-8 -DLINKER_NAME=lld-8
```
and simple query:
```
:) select throwIf(1);
SELECT throwIf(1)
```
in server log:
```
2019.12.11 20:32:12.981653 [ 134 ] {} <Fatal> BaseDaemon: ########################################
2019.12.11 20:32:12.981708 [ 134 ] {} <Fatal> BaseDaemon: (version 19.15.1.1) (from thread 131) Received signal Aborted (6).
2019.12.11 20:32:12.981724 [ 134 ] {} <Fatal> BaseDaemon:
2019.12.11 20:32:12.981753 [ 134 ] {} <Fatal> BaseDaemon: Stack trace: 0x7f9ee705de97 0x7f9ee705f801 0x8286640 0xd1f5773 0xd1f4de6 0xd1f4d7c 0x9a6021b 0x9a5f8db 0xb812123 0xb81372c 0xbac4797 0xbacbe28 0xbacb9bb 0xbab72ff 0xbab9049 0xbaae7d5 0xbaae80a 0xbaa540a 0xbaabd96 0xbb0cd54 0xbb0b256
2019.12.11 20:32:12.981856 [ 134 ] {} <Fatal> BaseDaemon: 3. 0x7f9ee705de97 raise /build/glibc-OTsEL5/glibc-2.27/signal/../sysdeps/unix/sysv/linux/raise.c:51
2019.12.11 20:32:12.981893 [ 134 ] {} <Fatal> BaseDaemon: 4. 0x7f9ee705f801 __GI_abort /build/glibc-OTsEL5/glibc-2.27/stdlib/abort.c:81
2019.12.11 20:32:12.982114 [ 134 ] {} <Fatal> BaseDaemon: 5. 0x8286640 terminate_handler() /home/alesap/code/cpp/ClickHouse/libs/libdaemon/src/BaseDaemon.cpp:0
2019.12.11 20:32:12.983100 [ 134 ] {} <Fatal> BaseDaemon: 6. 0xd1f5773 std::__terminate(void (*)()) /home/alesap/code/cpp/ClickHouse/contrib/libcxxabi/src/cxa_handlers.cpp:61
2019.12.11 20:32:12.984007 [ 134 ] {} <Fatal> BaseDaemon: 7. 0xd1f4de6 ? /home/alesap/code/cpp/ClickHouse/contrib/libcxxabi/src/cxa_exception.cpp:1522019.12.11 20:32:12.984896 [ 134 ] {} <Fatal> BaseDaemon: 8. 0xd1f4d7c ? /home/alesap/code/cpp/ClickHouse/contrib/libcxxabi/src/cxa_exception.cpp:284
2019.12.11 20:32:12.985897 [ 134 ] {} <Fatal> BaseDaemon: 9. 0x9a6021b bool DB::FunctionThrowIf::execute<unsigned char>(DB::Block&, DB::IColumn const*, unsigned long, std::__1::optional<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > const&) /home/alesap/code/cpp/BuildCH/dbms/programs/clickhouse2019.12.11 20:32:12.986900 [ 134 ] {} <Fatal> BaseDaemon: 10. 0x9a5f8db DB::FunctionThrowIf::executeImpl(DB::Block&, std::__1::vector<unsigned long, std::__1::allocator<unsigned long> > const&, unsigned long, unsigned long) /home/alesap/code/cpp/BuildCH/dbms/programs/clickhouse
2019.12.11 20:32:12.987400 [ 134 ] {} <Fatal> BaseDaemon: 11. 0xb812123 DB::PreparedFunctionImpl::defaultImplementationForConstantArguments(DB::Block&, std::__1::vector<unsigned long, std::__1::allocator<unsigned long> > const&, unsigned long, unsigned long, bool) /home/alesap/code/cpp/ClickHouse/dbms/src/Functions/IFunction.cpp:3102019.12.11 20:32:12.987918 [ 134 ] {} <Fatal> BaseDaemon: 12. 0xb81372c DB::PreparedFunctionImpl::execute(DB::Block&, std::__1::vector<unsigned long, std::__1::allocator<unsigned long> > const&, unsigned long, unsigned long, bool) /home/alesap/code/cpp/ClickHouse/dbms/src/Functions/IFunction.cpp:303
2019.12.11 20:32:12.988484 [ 134 ] {} <Fatal> BaseDaemon: 13. 0xbac4797 DB::ExpressionAction::prepare(DB::Block&, DB::Settings const&, std::__1::unordered_set<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >&) /home/alesap/code/cpp/ClickHouse/dbms/src/Interpreters/ExpressionActions.cpp:224
2019.12.11 20:32:12.989216 [ 134 ] {} <Fatal> BaseDaemon: 14. 0xbacbe28 DB::ExpressionActions::addImpl(DB::ExpressionAction, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >&) /home/alesap/code/cpp/ClickHouse/contrib/libcxx/include/vector:1629
2019.12.11 20:32:12.989935 [ 134 ] {} <Fatal> BaseDaemon: 15. 0xbacb9bb DB::ExpressionActions::add(DB::ExpressionAction const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >&) /home/alesap/code/cpp/ClickHouse/dbms/src/Interpreters/ExpressionActions.cpp:0
2019.12.11 20:32:12.990507 [ 134 ] {} <Fatal> BaseDaemon: 16. 0xbab72ff DB::ScopeStack::addAction(DB::ExpressionAction const&) /home/alesap/code/cpp/ClickHouse/contrib/libcxx/include/vector:15102019.12.11 20:32:12.991154 [ 134 ] {} <Fatal> BaseDaemon: 17. 0xbab9049 DB::ActionsMatcher::visit(DB::ASTFunction const&, std::__1::shared_ptr<DB::IAST> const&, DB::ActionsMatcher::Data&) /home/alesap/code/cpp/ClickHouse/dbms/src/Interpreters/ActionsVisitor.h:0
2019.12.11 20:32:12.992006 [ 134 ] {} <Fatal> BaseDaemon: 18. 0xbaae7d5 DB::InDepthNodeVisitor<DB::ActionsMatcher, true, std::__1::shared_ptr<DB::IAST> const>::visit(std::__1::shared_ptr<DB::IAST> const&) /home/alesap/code/cpp/ClickHouse/contrib/libcxx/include/memory:3933
2019.12.11 20:32:12.992858 [ 134 ] {} <Fatal> BaseDaemon: 19. 0xbaae80a DB::InDepthNodeVisitor<DB::ActionsMatcher, true, std::__1::shared_ptr<DB::IAST> const>::visit(std::__1::shared_ptr<DB::IAST> const&) /home/alesap/code/cpp/ClickHouse/contrib/libcxx/include/iterator:1394
2019.12.11 20:32:12.993429 [ 134 ] {} <Fatal> BaseDaemon: 20. 0xbaa540a DB::ExpressionAnalyzer::getRootActions(std::__1::shared_ptr<DB::IAST> const&, bool, std::__1::shared_ptr<DB::ExpressionActions>&, bool) /home/alesap/code/cpp/ClickHouse/dbms/src/Interpreters/ExpressionAnalyzer.cpp:0
2019.12.11 20:32:12.994180 [ 134 ] {} <Fatal> BaseDaemon: 21. 0xbaabd96 DB::SelectQueryExpressionAnalyzer::appendSelect(DB::ExpressionActionsChain&, bool) /home/alesap/code/cpp/ClickHouse/contrib/libcxx/include/memory:4520
2019.12.11 20:32:12.994924 [ 134 ] {} <Fatal> BaseDaemon: 22. 0xbb0cd54 DB::InterpreterSelectQuery::analyzeExpressions(DB::ASTSelectQuery const&, DB::SelectQueryExpressionAnalyzer&, DB::QueryProcessingStage::Enum, DB::QueryProcessingStage::Enum, DB::Context const&, std::__1::shared_ptr<DB::IStorage> const&, bool, std::__1::shared_ptr<DB::FilterInfo> const&, DB::Block const&) /home/alesap/code/cpp/ClickHouse/dbms/src/Interpreters/InterpreterSelectQuery.cpp:0
2019.12.11 20:32:12.995617 [ 134 ] {} <Fatal> BaseDaemon: 23. 0xbb0b256 DB::InterpreterSelectQuery::getSampleBlockImpl() /home/alesap/code/cpp/ClickHouse/dbms/src/Interpreters/InterpreterSelectQuery.cpp:530
Aborted (core dumped)
```

**Pull request merged**
