### PR TITLE
Remove the support for Kerberized HDFS

### LINKED ISSUE #62873: clickhouse/kerberized-hadoop docker image is broken
clickhouse/kerberized-hadoop docker image is broken.
If it is rebuilt right now, it is not going to work properly and test_storage_kerberized_hdfs would fail.
(the test is Ok if image is old enough)

The reason is 
```
curl http://archive.apache.org/dist/commons/daemon/source/commons-daemon-1.0.15-src.tar.gz -o commons-daemon-1.0.15-src.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
147   294  147   294    0     0   3034      0 --:--:-- --:--:-- --:--:--  6533
bash-4.1# cat commons-daemon-1.0.15-src.tar.gz
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="https://archive.apache.org/dist/commons/daemon/source/commons-daemon-1.0.15-src.tar.gz">here</a>.</p>
</body></html>
```

Looks like it is happening since March.

I'll take care of this.

### PR DESCRIPTION
**Pull request by alexey-milovidov**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Tests have failed: https://s3.amazonaws.com/clickhouse-test-reports/0/da81588d424efd6de9d8c4dd8395df1f887f1a74/integration_tests__release__[1_4].html

This closes #62873.

Currently, we are removing the tests, but if @ilejn does not add them back and fixed, we will remove the feature from the code entirely.

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-clickhouse** [comment]
*This is an automated comment for commit e156db49225d273abe97eef84612f564a7547be9 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/66998/e156db49225d273abe97eef84612f564a7547be9/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Builds</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/8d3568ce7124cf4fe953a97843146ccb9f905e35/builds/report.html">✅ success</a></td></tr>
<tr><td>ClickBench</td><td>Runs [ClickBench](https://github.com/ClickHouse/ClickBench/) with instant-attach table</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/8d3568ce7124cf4fe953a97843146ccb9f905e35/clickbench__aarch64_.html">✅ success</a></td></tr>
<tr><td>Compatibility check</td><td>Checks that <b>clickhouse</b> binary runs on distributions with old libc versions. If it fails, ask a maintainer for help</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/8d3568ce7124cf4fe953a97843146ccb9f905e35/compatibility_check__aarch64_.html">✅ success</a></td></tr>
<tr><td>Docker keeper image</td><td>The check to build and optionally push the mentioned image to docker hub</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/8d3568ce7124cf4fe953a97843146ccb9f905e35/docker_keeper_image.html">✅ success</a></td></tr>
<tr><td>Docker server image</td><td>The check to build and optionally push the mentioned image to docker hub</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/8d3568ce7124cf4fe953a97843146ccb9f905e35/docker_server_image.html">✅ success</a></td></tr>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/65521/9d7bb2a430b142e0761cc30efcf78ea1bbeb6871/docs_check.html">✅ success</a></td></tr>
<tr><td>Install packages</td><td>Checks that the built packages are installable in a clear environment</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/8d3568ce7124cf4fe953a97843146ccb9f905e35/install_packages__aarch64_.html">✅ success</a></td></tr>
<tr><td>Stateful tests</td><td>Runs stateful functional tests for ClickHouse binaries built in various configurations -- release, debug, with sanitizers, etc</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/8d3568ce7124cf4fe953a97843146ccb9f905e35/stateful_tests__aarch64_.html">✅ success</a></td></tr>
<tr><td>Stress test</td><td>Runs stateless functional tests concurrently from several clients to detect concurrency-related errors</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/8d3568ce7124cf4fe953a97843146ccb9f905e35/stress_test__debug_.html">✅ success</a></td></tr>
<tr><td>Unit tests</td><td>Runs the unit tests for different release types</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/8d3568ce7124cf4fe953a97843146ccb9f905e35/unit_tests__asan_.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Comment by ilejn** [comment]
Looking into test_storage_kerberized_hdfs::test_read_table_expired failure.

**Comment by ilejn** [comment]
@alexey-milovidov ,  
both kerberized kafka and kerberized hdfs use kerberos kdc container
that exposes ports 88 and 749 (constant values).
If these tests bound to one runner, the behavior is unexpected.
Does it make sense?

**Comment by alexey-milovidov** [comment]
@ilejn, yes - good point! Can we either change ports or make sure these tests use separate runners, or merge them together and run sequentially?

**Comment by ilejn** [comment]
> @ilejn, yes - good point! Can we either change ports or make sure these tests use separate runners, or merge them together and run sequentially?

1. Of course the simplest approach is to disable parallel run for either kerberized hdfs or kerberized kafka.
2. The notion of mutually exclusive tests that cannot be put together in a single runner looks too tricky/dirty for me, and I would like to restrain from it while it is possible
3. Changing port seems a preferable way

**Comment by alexey-milovidov** [comment]
@ilejn thank you! Either way is good to me. Please submit these tests.

**Comment by ilejn** [comment]
Current status.
Assumption about port clash on kerberos kdc container came from my limited understanding of docker networking, "expose" does not mean making available to the host.
So disabling parallel run probably does not make sense.
  There is another test `test_kafka_json_as_string_no_kdc` which is similar and is flaky as well https://play.clickhouse.com/play?user=play#c2VsZWN0IHJlcG9ydF91cmwsIGNoZWNrX3N0YXJ0X3RpbWUsIGNoZWNrX25hbWUsIHRlc3RfbmFtZSwgdGVzdF9kdXJhdGlvbl9tcywgdGVzdF9zdGF0dXMgZnJvbSBjaGVja3MgCndoZXJlICcyMDIzLTAxLTAxJyA8PSBjaGVja19zdGFydF90aW1lICBhbmQgKHRlc3RfbmFtZSBpbGlrZSAnJXJlYWRfdGFibGVfZXhwaXJlZCUnIG9yIHRlc3RfbmFtZSBpbGlrZSAnJXRlc3Rfa2Fma2FfanNvbl9hc19zdHJpbmdfbm9fa2RjJScpIGFuZCB0ZXN0X3N0YXR1cyA9PSAnRkFJTCcKb3JkZXIgYnkgY2hlY2tfc3RhcnRfdGltZSBsaW1pdCAxMDA7Ci0tIGRlc2MgY2hlY2tzOwoK
The scenario of both these test: 

- obtain short living ticket
- pause kdc container
- wait while ticket is expired
- perform an operation requires authorization
- ensure that it is failed
- unpause kdc container 

The problem - operation is successful. According to ClickHouse logs, ticket was expired indeed and it was renewed by kdc which is supposed to be stopped.
Moreover, further tests in this module worked Ok although the kdc container was not unpaused due to exception

The only [conspiracy] theory I have is 'docker-compose pause' is not 100% reliable .

**Pull request merged**
