### PR TITLE
Add test for #51321

### LINKED ISSUE #51321: Logical error: Context has expired
**Describe the bug**
[A link to the report](https://s3.amazonaws.com/clickhouse-test-reports/51307/f09bdbd3319c5e44794c07b8a82a5d236aa24bb1/fuzzer_astfuzzerubsan/report.html)

**How to reproduce**

Reproduces easily
```
2023.06.23 07:19:35.418979 [ 152 ] {3bb21950-59c5-4412-90aa-4ac49278b9c3} <Fatal> : Logical error: 'Context has expired'.
2023.06.23 07:19:35.419240 [ 468 ] {} <Fatal> BaseDaemon: ########################################
2023.06.23 07:19:35.419293 [ 468 ] {} <Fatal> BaseDaemon: (version 23.6.1.1, build id: D2B2322202706CC0011ABAC7C0C02796DA976B90, git hash: da2ae3892ab9ed9d34babe16fd2aa8629abc4fb7) (from thread 152) (query_id: 3bb21950-59c5-4412-90aa-4ac49278b9c3) (query: EXPLAIN ESTIMATE  SELECT any(toTypeName(s)) FROM (SELECT 'bbbbbbbb', toTypeName(s), CAST('', 'LowCardinality(String)'), NULL, CAST('\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0', 'String') AS s WITH TOTALS) AS t1 FULL OUTER JOIN (SELECT CAST('bbbbb\0\0bbb\0bb\0bb', 'LowCardinality(String)'), CAST(CAST('a', 'String'), 'LowCardinality(String)') AS s GROUP BY CoNnEcTiOn_Id()) AS t2 USING (s) WITH TOTALS) Received signal Aborted (6)
2023.06.23 07:19:35.419329 [ 468 ] {} <Fatal> BaseDaemon: 
2023.06.23 07:19:35.419365 [ 468 ] {} <Fatal> BaseDaemon: Stack trace: 0x00007f7a0f70300b 0x00007f7a0f6e2859 0x000055ca0f3d6528 0x000055ca0f3d6e8e 0x000055ca03490ecf 0x000055ca0349041e 0x000055ca055cf496 0x000055ca02d2cf1f 0x000055ca02d2bac1 0x000055ca1b3e6a19 0x000055ca1b3e864b 0x000055ca1b3e9ac6 0x000055ca1bff7d7f 0x000055ca1f5e1433 0x000055ca1f8e7124 0x000055ca1f9374b8 0x000055ca1cf3e91f 0x000055ca1cf3c164 0x000055ca1d8020b6 0x000055ca1d7fbffc 0x000055ca1efd3753 0x000055ca1effe332 0x000055ca207a903e 0x000055ca207aa17a 0x000055ca20a3eed0 0x000055ca20a39ff1 0x00007f7a0f8ba609 0x00007f7a0f7df133
2023.06.23 07:19:35.419410 [ 468 ] {} <Fatal> BaseDaemon: 3. gsignal @ 0x00007f7a0f70300b in ?
2023.06.23 07:19:35.419450 [ 468 ] {} <Fatal> BaseDaemon: 4. abort @ 0x00007f7a0f6e2859 in ?
2023.06.23 07:19:35.443772 [ 468 ] {} <Fatal> BaseDaemon: 5. ./build_docker/./src/Common/Exception.cpp:49: DB::abortOnFailedAssertion(String const&) @ 0x000000003785e528 in /workspace/clickhouse
2023.06.23 07:19:35.467211 [ 468 ] {} <Fatal> BaseDaemon: 6. ./build_docker/./src/Common/Exception.cpp:93: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000003785ee8e in /workspace/clickhouse
2023.06.23 07:19:36.800549 [ 468 ] {} <Fatal> BaseDaemon: 7. DB::Exception::Exception<char const (&) [20], void>(int, char const (&) [20]) @ 0x000000002b918ecf in /workspace/clickhouse
2023.06.23 07:19:38.112917 [ 468 ] {} <Fatal> BaseDaemon: 8. DB::WithContextImpl<std::shared_ptr<DB::Context const>>::getContext() const @ 0x000000002b91841e in /workspace/clickhouse
2023.06.23 07:19:39.429463 [ 468 ] {} <Fatal> BaseDaemon: 9. DB::FunctionConnectionId::executeImpl(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long) const @ 0x000000002da57496 in /workspace/clickhouse
2023.06.23 07:19:40.757057 [ 468 ] {} <Fatal> BaseDaemon: 10. DB::IFunction::executeImplDryRun(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long) const @ 0x000000002b1b4f1f in /workspace/clickhouse
2023.06.23 07:19:42.069578 [ 468 ] {} <Fatal> BaseDaemon: 11. DB::FunctionToExecutableFunctionAdaptor::executeDryRunImpl(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long) const @ 0x000000002b1b3ac1 in /workspace/clickhouse
2023.06.23 07:19:42.084176 [ 468 ] {} <Fatal> BaseDaemon: 12. ./build_docker/./src/Functions/IFunction.cpp:0: DB::IExecutableFunction::executeWithoutLowCardinalityColumns(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x000000004386ea19 in /workspace/clickhouse
2023.06.23 07:19:42.099581 [ 468 ] {} <Fatal> BaseDaemon: 13.1. inlined from ./build_docker/./contrib/boost/boost/smart_ptr/intrusive_ptr.hpp:115: intrusive_ptr
2023.06.23 07:19:42.099610 [ 468 ] {} <Fatal> BaseDaemon: 13.2. inlined from ./build_docker/./contrib/boost/boost/smart_ptr/intrusive_ptr.hpp:122: boost::intrusive_ptr<DB::IColumn const>::operator=(boost::intrusive_ptr<DB::IColumn const>&&)
2023.06.23 07:19:42.099647 [ 468 ] {} <Fatal> BaseDaemon: 13.3. inlined from ./build_docker/./src/Common/COW.h:136: COW<DB::IColumn>::immutable_ptr<DB::IColumn>::operator=(COW<DB::IColumn>::immutable_ptr<DB::IColumn>&&)
2023.06.23 07:19:42.099681 [ 468 ] {} <Fatal> BaseDaemon: 13. ./build_docker/./src/Functions/IFunction.cpp:302: DB::IExecutableFunction::executeWithoutSparseColumns(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x000000004387064b in /workspace/clickhouse
2023.06.23 07:19:42.115647 [ 468 ] {} <Fatal> BaseDaemon: 14. ./build_docker/./src/Functions/IFunction.cpp:0: DB::IExecutableFunction::execute(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x0000000043871ac6 in /workspace/clickhouse
2023.06.23 07:19:42.315461 [ 468 ] {} <Fatal> BaseDaemon: 15.1. inlined from ./build_docker/./contrib/boost/boost/smart_ptr/intrusive_ptr.hpp:115: intrusive_ptr
2023.06.23 07:19:42.315492 [ 468 ] {} <Fatal> BaseDaemon: 15.2. inlined from ./build_docker/./contrib/boost/boost/smart_ptr/intrusive_ptr.hpp:122: boost::intrusive_ptr<DB::IColumn const>::operator=(boost::intrusive_ptr<DB::IColumn const>&&)
2023.06.23 07:19:42.315525 [ 468 ] {} <Fatal> BaseDaemon: 15.3. inlined from ./build_docker/./src/Common/COW.h:136: COW<DB::IColumn>::immutable_ptr<DB::IColumn>::operator=(COW<DB::IColumn>::immutable_ptr<DB::IColumn>&&)
2023.06.23 07:19:42.315568 [ 468 ] {} <Fatal> BaseDaemon: 15.4. inlined from ./build_docker/./src/Interpreters/ActionsDAG.cpp:537: DB::executeActionForHeader(DB::ActionsDAG::Node const*, std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>>)
2023.06.23 07:19:42.315603 [ 468 ] {} <Fatal> BaseDaemon: 15. ./build_docker/./src/Interpreters/ActionsDAG.cpp:656: DB::ActionsDAG::updateHeader(DB::Block) const @ 0x000000004447fd7f in /workspace/clickhouse
2023.06.23 07:19:42.327143 [ 468 ] {} <Fatal> BaseDaemon: 16.1. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/unordered_map:1153: ~unordered_map
2023.06.23 07:19:42.327176 [ 468 ] {} <Fatal> BaseDaemon: 16.2. inlined from ./build_docker/./src/Core/Block.h:25: ~Block
2023.06.23 07:19:42.327212 [ 468 ] {} <Fatal> BaseDaemon: 16. ./build_docker/./src/Processors/Transforms/ExpressionTransform.cpp:8: DB::ExpressionTransform::transformHeader(DB::Block, DB::ActionsDAG const&) @ 0x0000000047a69433 in /workspace/clickhouse
2023.06.23 07:19:42.350132 [ 468 ] {} <Fatal> BaseDaemon: 17. ./build_docker/./src/Processors/QueryPlan/ExpressionStep.cpp:0: DB::ExpressionStep::updateOutputStream() @ 0x0000000047d6f124 in /workspace/clickhouse
2023.06.23 07:19:42.394470 [ 468 ] {} <Fatal> BaseDaemon: 18.1. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:701: ~shared_ptr
2023.06.23 07:19:42.394496 [ 468 ] {} <Fatal> BaseDaemon: 18.2. inlined from ./build_docker/./src/Core/SortDescription.h:116: ~SortDescription
2023.06.23 07:19:42.394529 [ 468 ] {} <Fatal> BaseDaemon: 18.3. inlined from ./build_docker/./src/Processors/QueryPlan/IQueryPlanStep.h:21: ~DataStream
2023.06.23 07:19:42.394564 [ 468 ] {} <Fatal> BaseDaemon: 18.4. inlined from ./build_docker/./src/Processors/QueryPlan/QueryPlan.cpp:468: visitBottomUpImpl
2023.06.23 07:19:42.394603 [ 468 ] {} <Fatal> BaseDaemon: 18.5. inlined from ./build_docker/./src/Processors/QueryPlan/QueryPlanVisitor.h:73: DB::QueryPlanVisitor<DB::updateDataStreams(DB::QueryPlan::Node&)::UpdateDataStreams, false>::visitBottomUp(DB::QueryPlan::Node*, DB::QueryPlan::Node*)
2023.06.23 07:19:42.394645 [ 468 ] {} <Fatal> BaseDaemon: 18.6. inlined from ./build_docker/./src/Processors/QueryPlan/QueryPlanVisitor.h:60: DB::QueryPlanVisitor<DB::updateDataStreams(DB::QueryPlan::Node&)::UpdateDataStreams, false>::visit()
2023.06.23 07:19:42.394682 [ 468 ] {} <Fatal> BaseDaemon: 18.7. inlined from ./build_docker/./src/Processors/QueryPlan/QueryPlan.cpp:472: DB::updateDataStreams(DB::QueryPlan::Node&)
2023.06.23 07:19:42.394716 [ 468 ] {} <Fatal> BaseDaemon: 18. ./build_docker/./src/Processors/QueryPlan/QueryPlan.cpp:486: DB::QueryPlan::optimize(DB::QueryPlanOptimizationSettings const&) @ 0x0000000047dbf4b8 in /workspace/clickhouse
2023.06.23 07:19:42.439206 [ 468 ] {} <Fatal> BaseDaemon: 19. ./build_docker/./src/Interpreters/InterpreterExplainQuery.cpp:0: DB::InterpreterExplainQuery::executeImpl() @ 0x00000000453c691f in /workspace/clickhouse
2023.06.23 07:19:42.482125 [ 468 ] {} <Fatal> BaseDaemon: 20. ./build_docker/./src/Interpreters/InterpreterExplainQuery.cpp:0: DB::InterpreterExplainQuery::execute() @ 0x00000000453c4164 in /workspace/clickhouse
2023.06.23 07:19:42.551850 [ 468 ] {} <Fatal> BaseDaemon: 21. ./build_docker/./src/Interpreters/executeQuery.cpp:0: DB::executeQueryImpl(char const*, char const*, std::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, DB::ReadBuffer*) @ 0x0000000045c8a0b6 in /workspace/clickhouse
2023.06.23 07:19:42.626465 [ 468 ] {} <Fatal> BaseDaemon: 22. ./build_docker/./src/Interpreters/executeQuery.cpp:1182: DB::executeQuery(String const&, std::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum) @ 0x0000000045c83ffc in /workspace/clickhouse
2023.06.23 07:19:42.688073 [ 468 ] {} <Fatal> BaseDaemon: 23. ./build_docker/./src/Server/TCPHandler.cpp:0: DB::TCPHandler::runImpl() @ 0x000000004745b753 in /workspace/clickhouse
2023.06.23 07:19:42.776690 [ 468 ] {} <Fatal> BaseDaemon: 24. ./build_docker/./src/Server/TCPHandler.cpp:2045: DB::TCPHandler::run() @ 0x0000000047486332 in /workspace/clickhouse
2023.06.23 07:19:42.782046 [ 468 ] {} <Fatal> BaseDaemon: 25. ./build_docker/./base/poco/Net/src/TCPServerConnection.cpp:57: Poco::Net::TCPServerConnection::start() @ 0x0000000048c3103e in /workspace/clickhouse
2023.06.23 07:19:42.789219 [ 468 ] {} <Fatal> BaseDaemon: 26.1. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:302: std::unique_ptr<Poco::Net::TCPServerConnection, std::default_delete<Poco::Net::TCPServerConnection>>::reset[abi:v15000](Poco::Net::TCPServerConnection*)
2023.06.23 07:19:42.789252 [ 468 ] {} <Fatal> BaseDaemon: 26.2. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:259: ~unique_ptr
2023.06.23 07:19:42.789289 [ 468 ] {} <Fatal> BaseDaemon: 26. ./build_docker/./base/poco/Net/src/TCPServerDispatcher.cpp:116: Poco::Net::TCPServerDispatcher::run() @ 0x0000000048c3217a in /workspace/clickhouse
2023.06.23 07:19:42.796928 [ 468 ] {} <Fatal> BaseDaemon: 27. ./build_docker/./base/poco/Foundation/src/ThreadPool.cpp:202: Poco::PooledThread::run() @ 0x0000000048ec6ed0 in /workspace/clickhouse
2023.06.23 07:19:42.804156 [ 468 ] {} <Fatal> BaseDaemon: 28.1. inlined from ./build_docker/./base/poco/Foundation/include/Poco/AutoPtr.h:205: Poco::AutoPtr<Poco::ThreadImpl::ThreadData>::operator->()
2023.06.23 07:19:42.804179 [ 468 ] {} <Fatal> BaseDaemon: 28. ./build_docker/./base/poco/Foundation/src/Thread_POSIX.cpp:350: Poco::ThreadImpl::runnableEntry(void*) @ 0x0000000048ec1ff1 in /workspace/clickhouse
2023.06.23 07:19:42.804215 [ 468 ] {} <Fatal> BaseDaemon: 29. ? @ 0x00007f7a0f8ba609 in ?
2023.06.23 07:19:42.804251 [ 468 ] {} <Fatal> BaseDaemon: 30. clone @ 0x00007f7a0f7df133 in ?
2023.06.23 07:19:42.804289 [ 468 ] {} <Fatal> BaseDaemon: Integrity check of the executable skipped because the reference checksum could not be read.
2023.06.23 07:19:50.146053 [ 468 ] {} <Fatal> BaseDaemon: This ClickHouse version is not official and should be upgraded to the official build.
2023.06.23 07:19:50.146185 [ 468 ] {} <Fatal> BaseDaemon: Changed settings: receive_timeout = 10., receive_data_timeout_ms = 10000, allow_suspicious_low_cardinality_types = true, log_queries = true, table_function_remote_max_addresses = 200, max_execution_time = 10., max_memory_usage = 10000000000, allow_introspection_functions = true
2023.06.23 07:19:59.734423 [ 143 ] {} <Fatal> Application: Child process was terminated by signal 6.
```

### PR DESCRIPTION
**Pull request by Algunenano**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Fixed in 23.8.
Closes https://github.com/ClickHouse/ClickHouse/issues/51321

### CODE REVIEW

**Comment by robot-clickhouse-ci-1** [comment]
*This is an automated comment for commit 22fcf5b99f677e805824187ad75751379341cced with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/57202/22fcf5b99f677e805824187ad75751379341cced/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td><a href="https://github.com/ClickHouse/ClickHouse/actions/runs/6983131485">✅ success</a></td></tr>
<tbody>
</table>
</details>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/57202/22fcf5b99f677e805824187ad75751379341cced/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Review by evillique — APPROVED** [review]
Looks like we need to add it to the analyzer_tech_debt.txt

**Comment by alexey-milovidov** [comment]
Ok, but it is different with Analyzer.

**Comment by Algunenano** [comment]
In this case it seems like a bug in the old system and the analyzer is doing the right thing:

```
    SELECT 'bbbbbbbb',
            toTypeName(s), '', NULL, '' AS s
    WITH TOTALS
```
* Interpreters: WITH TOTALS, ROLLUP, CUBE or GROUPING SETS are not supported without aggregation. (NOT_IMPLEMENTED)
* Analyzer: WITH TOTALS, ROLLUP, CUBE or GROUPING SETS are not supported without aggregation. (NOT_IMPLEMENTED)


```
SELECT any(toTypeName(s)) FROM
(
    SELECT 'bbbbbbbb',
            toTypeName(s), '', NULL, '' AS s
    WITH TOTALS
) AS t1
```
* Interpreters: `String` (No exception)
* Analyzer:  WITH TOTALS, ROLLUP, CUBE or GROUPING SETS are not supported without aggregation. (NOT_IMPLEMENTED) <- Correct

I'll adjust the test. No need to add it to `analyzer_tech_debt.txt`

**Comment by Algunenano** [comment]
* Fuzzer: https://github.com/ClickHouse/ClickHouse/issues/57193
* ClickHouse Stateless Tests (Analyzer): We keep enabling tests that are flaky with the analyzer (01287_max_execution_speed).
* Stress test (msan). If you don't stop the query (`SELECT 1, count() FROM system.numbers`) it will run forever. The approach we have to kill queries is odd (manually on queries that have caused issues). No idea why we don't kill any running query to be honest.

**Pull request merged**
