### PR TITLE
Fix Merge(Distributed()) with JOIN

### LINKED ISSUE #11755: Missing columns of right table on JOIN query
When I am trying to run this query: 

```sql
SELECT * FROM products_d AS products GLOBAL ALL LEFT JOIN categories_d USING (categoryId);
```
The clickhouse throws an exception:
`[2020-06-18 17:20:01] Code: 47, e.displayText() = DB::Exception: Missing columns: 'categories_d.dateTime' 'categories_d.errorCode' 'categories_d.processingTimestampNs' 'categoryName' 'productIds' while processing query: 'SELECT dateTime, categoryId, productId, name, errorCode, processingTimestampNs, productIds, categoryName, categories_d.dateTime, categories_d.errorCode, categories_d.processingTimestampNs FROM products_d AS products GLOBAL ALL LEFT JOIN categories_d AS categories_d USING (categoryId)', required columns: 'dateTime' 'errorCode' 'categoryId' 'productId' 'productIds' 'name' 'categoryName' 'categories_d.processingTimestampNs' 'processingTimestampNs' 'categories_d.errorCode' 'categories_d.dateTime', source columns: 'processingTimestampNs' 'name' 'productId' 'categoryId' 'errorCode' 'dateTime', joined columns: (version 20.4.5.36 (official build))`

Here are the queries that create 2 tables:

```sql
CREATE TABLE IF NOT EXISTS products_kafka (
   _id                       FixedString(36),
   name                      String,
   createdAt                 String,
   productId                 FixedString(36),
   categoryId                String,
   errorCode                 Nullable(UInt8),
   processedAt               String
) ENGINE = Kafka
      SETTINGS
          kafka_broker_list = '%%BROKER_LIST%%',
          kafka_topic_list = 'products%%KAFKA_TOPICS_VERSION%%',
          kafka_group_name = 'clickhouse-%%DATABASE%%-products',
          kafka_format = 'JSONEachRow',
          kafka_row_delimiter = '\n';

CREATE TABLE IF NOT EXISTS products_data_hist (
   dateTime                  DateTime('UTC'),
   categoryId                LowCardinality(String),
   productId                 UUID,
   name                      LowCardinality(String),
   errorCode                 UInt8,
   processingTimestampNs     UInt64
) ENGINE = ReplicatedReplacingMergeTree('/clickhouse/tables/{shard}/%%DATABASE%%/products_data_hist', '{replica}', processingTimestampNs)
  PARTITION BY toYYYYMM(dateTime)
  ORDER BY (cityHash64(name), toDate(dateTime), productId)
  PRIMARY KEY (cityHash64(name), toDate(dateTime));

CREATE TABLE IF NOT EXISTS products_data_d_hist AS products_data_hist ENGINE = Distributed('kafka-cluster', %%DATABASE%%, products_data_hist, sipHash64(toString(productId)));

CREATE TABLE IF NOT EXISTS products_data_daily as products_data_d_hist ENGINE = ReplicatedReplacingMergeTree('/clickhouse/tables/{shard}/%%DATABASE%%/products_data_daily', '{replica}', processingTimestampNs)
PARTITION BY toYYYYMM(dateTime)
ORDER BY (cityHash64(name), toDate(dateTime), productId)
PRIMARY KEY (cityHash64(name), toDate(dateTime));

CREATE TABLE IF NOT EXISTS products_data_d_daily AS products_data_daily ENGINE = Distributed('kafka-cluster', %%DATABASE%%, products_data_daily, sipHash64(toString(productId)));

CREATE TABLE IF NOT EXISTS products_data_d_auxiliary AS products_data_d_hist ENGINE = ReplicatedReplacingMergeTree('/clickhouse/tables/{shard}/%%DATABASE%%/products_data_d_auxiliary', '{replica}', processingTimestampNs)
    PARTITION BY toYYYYMM(dateTime)
    ORDER BY (cityHash64(name), toDate(dateTime), productId)
    PRIMARY KEY (cityHash64(name), toDate(dateTime));

CREATE TABLE IF NOT EXISTS products_data_d_auxiliary_d AS products_data_d_hist ENGINE = Distributed('kafka-cluster', %%DATABASE%%, products_data_d_auxiliary, sipHash64(toString(productId)));

CREATE MATERIALIZED VIEW IF NOT EXISTS products_mv TO products_data_daily AS
SELECT
    toDateTime(substring(createdAt, 1, 19), 'UTC') as dateTime,
    toUUID(productId) AS productId,
    toLowCardinality(name) AS name,
    toLowCardinality(categoryId) AS categoryId,
    coalesce(errorCode, 0) AS errorCode,
    (
        toUInt64(toDateTime(substr(processedAt, 1, 19), 'UTC')) * 1000000000 +
        toUInt64(1000000000 * toFloat64(concat(replace(substr(processedAt, 20), 'Z', ''), '0')))
    ) AS processingTimestampNs
FROM products_kafka;

CREATE TABLE products_d as products_data_d_hist ENGINE=Merge('%%DATABASE%%', '^products_data_d_');
```

```sql
CREATE TABLE IF NOT EXISTS categories_kafka
(
    _id               FixedString(36),
    productIds        Array(String),
    categoryId        FixedString(36),
    categoryName      String,
    createdAt         String,
    errorCode         Nullable(UInt8),
    processedAt       String
)
    ENGINE = Kafka
        SETTINGS
            kafka_broker_list = '%%BROKER_LIST%%',
            kafka_topic_list = 'categories%%KAFKA_TOPICS_VERSION%%',
            kafka_group_name = 'clickhouse-%%DATABASE%%-categories',
            kafka_format = 'JSONEachRow',
            kafka_row_delimiter = '\n';

CREATE TABLE if NOT EXISTS categories_data_hist (
    productIds              Array(String),
    categoryId              UUID,
    categoryName            String,
    dateTime                DateTime('UTC'),
    errorCode               UInt8,
    processingTimestampNs   UInt64
) ENGINE ReplicatedReplacingMergeTree('/clickhouse/tables/{shard}/%%DATABASE%%/categories_data_hist', '{replica}', processingTimestampNs)
PARTITION BY toYYYYMM(dateTime)
ORDER BY (cityHash64(categoryName), toDate(dateTime))
PRIMARY KEY (cityHash64(categoryName), toDate(dateTime));

CREATE TABLE IF NOT EXISTS categories_data_d_hist AS categories_data_hist ENGINE = Distributed('kafka-cluster', %%DATABASE%%, categories_data_hist, sipHash64(toString(categoryId)));

CREATE TABLE if NOT EXISTS categories_data_daily as categories_data_hist ENGINE ReplicatedReplacingMergeTree('/clickhouse/tables/{shard}/%%DATABASE%%/categories_data_daily', '{replica}', processingTimestampNs)
PARTITION BY toYYYYMM(dateTime)
ORDER BY (cityHash64(categoryName), toDate(dateTime))
PRIMARY KEY (cityHash64(categoryName), toDate(dateTime));

CREATE TABLE IF NOT EXISTS categories_data_d_daily AS categories_data_daily ENGINE = Distributed('kafka-cluster', %%DATABASE%%, categories_data_daily, sipHash64(toString(categoryId)));

CREATE TABLE if NOT EXISTS categories_data_auxiliary as categories_data_hist ENGINE ReplicatedReplacingMergeTree('/clickhouse/tables/{shard}/%%DATABASE%%/categories_data_auxiliary', '{replica}', processingTimestampNs)
PARTITION BY toYYYYMM(dateTime)
ORDER BY (cityHash64(categoryName), toDate(dateTime))
PRIMARY KEY (cityHash64(categoryName), toDate(dateTime));

CREATE TABLE IF NOT EXISTS categories_data_auxiliary_d AS categories_data_hist ENGINE = Distributed('kafka-cluster', %%DATABASE%%, orders_data_auxiliary, sipHash64(toString(categoryId)));

CREATE MATERIALIZED VIEW IF NOT EXISTS categories_mv TO categories_data_daily AS
SELECT
    toDateTime(substring(createdAt, 1, 19), 'UTC') as dateTime,
    productIds,
    toUUID(categoryId),
    categoryName,
    coalesce(errorCode, 0) AS errorCode,
    (
        toUInt64(toDateTime(substr(processedAt, 1, 19), 'UTC')) * 1000000000 +
        toUInt64(1000000000 * toFloat64(concat(replace(substr(processedAt, 20), 'Z', ''), '0')))
    ) AS processingTimestampNs
FROM categories_kafka;

CREATE TABLE categories_d as categories_data_hist ENGINE=Merge('%%DATABASE%%', '^categories_data_d_');
```

I think the issue is about it is not adding the columns from the right table to the joined table when executing the query.

### PR DESCRIPTION
**Pull request by azat**
Changelog category (leave one):
- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix Merge(Distributed()) with JOIN

Fixes: #11755
Refs: #15242
Broken-since: 20.3+ (looks like it had been introduced in #9035)

HEAD:

<details>

- d1f52dc72d417580c4088cf3880593176416bea2

</details>

### CODE REVIEW

**Comment by azat** [comment]
>Functional stateless tests (ubsan) — fail: 1, passed: 2440, skipped: 9

```
2020-11-14 03:24:48 01247_optimize_distributed_group_by_sharding_key:                       [ FAIL ] 0.34 sec. - return code 101
2020-11-14 03:24:48 Received exception from server (version 20.12.1):
2020-11-14 03:24:48 Code: 101. DB::Exception: Received from localhost:9000. DB::Exception: Received from 127.0.0.2:9000. DB::Exception: Unexpected packet Data received from client. 
```

Not related, but interesting, I will take a look

**Comment by azat** [comment]
Cc @4ertus2

**Review by alexey-milovidov — APPROVED** [review]
Ok.

The logic is too complicated.
I strongly don't recommend to use Merge over Distributed.

Prefer Distributed over Merge whenever possible.

PS. Do I understand correctly, that it simply defies the purpose of GLOBAL JOIN? So, data won't be sent to remote servers for joining...

**Comment by azat** [comment]
>The logic is too complicated.
>I strongly not recommend to use Merge over Distributed.

Indeed (this use case looks really doubtful)

>PS. Do I understand correctly, that it simply defies the purpose of GLOBAL JOIN? So, data won't be sent to remote servers for joining...

Kind of, but temporary table will be still created and sent to the remote, while this should not happen.

**Comment by ibeleychev** [comment]
Hello guys, I see, that you backported that bug fix into version version 20.9
But we still get `missing columns` exceptions with versions `20.9.7.11`
Is it 100% fixing or sometimes it cannot be avoided?

**Comment by SaltTan** [comment]
> Hello guys, I see, that you backported that bug fix into version version 20.9 But we still get `missing columns` exceptions with versions `20.9.7.11` I ran queries like in test file in that PR and got exceptions.

The fix was not backported.
The backport PRs are Closed, not Merged.

**Comment by ibeleychev** [comment]
@SaltTan Thank you for explanation. Do not you know they want to backport it?

**Pull request merged**
