### PR TITLE
Revert revert attach partition PR

### PR DESCRIPTION
**Pull request by arthurpassos**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fixes https://github.com/ClickHouse/ClickHouse/pull/59120#issuecomment-1906177350

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by arthurpassos** [comment]
This should fix it, although I am not sure how I can test it.

@rschu1ze

**Comment by rschu1ze** [comment]
@arthurpassos Thanks! Let me check on my MacBook...

**Comment by robot-ch-test-poll4** [comment]
*This is an automated comment for commit 5179891aef9792366d948efd9f1a2454dfe8da69 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/59122/5179891aef9792366d948efd9f1a2454dfe8da69/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/59122/5179891aef9792366d948efd9f1a2454dfe8da69/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Comment by rschu1ze** [comment]
> Also, can you enable CI?

Sure, done. My Mac M1 Pro build are still quite slow, I'll get back to you soon.

**Review by antonio2368 — APPROVED** [review]
Works on my M1 machine
Thanks for quick fix

**Comment by arthurpassos** [comment]
Fixed conflicts, CI was restarted

**Comment by boazin** [comment]
Just to report that current master works on my macOS M2.
There were quite a few commits to master since yesterday when I reported this on the slack channel, so I assume that one of them fixed the issue.

**Comment by antonio2368** [comment]
@boazin we reverted the original PR (the reason why master works now) and this PR is returning it but with a fix for macOS M machines.

**Comment by rschu1ze** [comment]
Confirmed to work. `master` is currently closed for non-bugfix PRs due to too many test failures, I'll merge when it's open again.

**Comment by arthurpassos** [comment]
> Confirmed to work. `master` is currently closed for non-bugfix PRs due to too many test failures, I'll merge when it's open again.

Any estimations of when it'll be open again?

**Comment by rschu1ze** [comment]
Rough estimation: by the end of the week.

**Comment by alexey-milovidov** [comment]
@arthurpassos Please take a look at
> Stress test (ubsan) — Possible deadlock on shutdown (see gdb.log)

**Comment by arthurpassos** [comment]
Hi @rschu1ze 

> @arthurpassos Please take a look at
> 
> > Stress test (ubsan) — Possible deadlock on shutdown (see gdb.log)

@alexey-milovidov @rschu1ze I took a look at `clickhouse-server.log`, `run.log` and `gdb.log`, but couldn't pinpoint what the issue was. Will dive deeper tomorrow.

If you have any hints / clues, that would be highly appreciated. Thanks.

**Comment by arthurpassos** [comment]
Spent some more time on it, could not find the issue. Rebased.

**Comment by arthurpassos** [comment]
@rschu1ze can you merge it?

**Comment by alexey-milovidov** [comment]
@arthurpassos please merge with master.

**Comment by arthurpassos** [comment]
> @arthurpassos please merge with master.

done

**Comment by arthurpassos** [comment]
02908_many_requests_to_system_replicas - https://github.com/ClickHouse/ClickHouse/issues/57443

Can it be merged?

**Comment by rschu1ze** [comment]
Tests look good:

Stateless tests (aarch64)
- 02908_many_requests_to_system_replicas: #57443

@arthurpassos As far as I see, `master` is not officially open again 😢  Will keep an eye on this PR and merge it (along with many other PRs) once the freeze is lifted. Sorry for the delay.

**Comment by alexey-milovidov** [comment]
@arthurpassos, the tests are good. Could you please resolve the conflict?

**Comment by arthurpassos** [comment]
> @arthurpassos, the tests are good. Could you please resolve the conflict?

done

**Review by alexey-milovidov — APPROVED** [review]

**Pull request merged**
