### PR TITLE
Fix MaxOS build doc

### PR DESCRIPTION
**Pull request by ryan-tu**
Changelog category (leave one):
- Documentation (changelog entry is not required)

Detailed description / Documentation draft:
Jemalloc should be disabled when build on MacOS.

When jemalloc is enabled, build on MacOS is ok, but run by command `./clickhouse server --config-files=/path/to/config/file` fails with the following error:
```
<jemalloc>: ../contrib/jemalloc/include/jemalloc/internal/tsd_generic.h:145: Failed assertion: "tsd_booted"
```

### CODE REVIEW

**Comment by azat** [comment]
@ryan-tu IIRC disabling jemalloc is not great, let's try to fix it instead. Which version of MacOS do you have?

Plus it is not an option for osx < 10.15, since ClickHouse requires aligned_alloc which exists only in 10.15 in default libc (https://github.com/ClickHouse/ClickHouse/pull/27753#issuecomment-900855921)

Also I've just checked with 10.15 and it works fine, using ClickHouse from upstream.

What version of ClickHouse you are trying to use/build?
And what is the output of the following command w/ `-DENABLE_JEMALLOC=ON`:

```sh
$ nm clickhouse | fgrep -c zone_register
0
```

Refs: #27753

<details>

FWIW
- osx 10.11.6: fails with `Symbol not found: _os_unfair_lock_trylock`

</details>

**Comment by ryan-tu** [comment]
> * Which version of MacOS do you have?

My MacOS is v10.15.

> * What version of ClickHouse you are trying to use/build?

I just checkout the master branch and the latest commit id is: b040890fcff5c40ee1242c9a85d294e46767f842

> * And what is the output of the `nm clickhouse | fgrep -c zone_register` w/ `-DENABLE_JEMALLOC=ON`?

With `-DENABLE_JEMALLOC=OFF`:
```
nm ./programs/clickhouse | fgrep -c zone_register
0
```

With `-DENABLE_JEMALLOC=ON`:
Run the cmake command, it displays warning: 
```
CMake Warning at contrib/jemalloc-cmake/CMakeLists.txt:23 (message):
  jemalloc support on non-linux is EXPERIMENTAL
```
and  the output is: 
```
nm ./programs/clickhouse | fgrep -c zone_register
2
```

**Comment by azat** [comment]
>I just checkout the master branch and the latest commit id is: b040890

And ClickHouse binaries does not work?
None of binaries, i.e. `clickhouse-server`/`clickhouse-local` (note, that now it has interactive mode, i.e. it is server+client w/o network interaction)/`clickhouse-client`, and it fails with:

```
<jemalloc>: ../contrib/jemalloc/include/jemalloc/internal/tsd_generic.h:145: Failed assertion: "tsd_booted"
```

Oh, I guess I see the reason, you build debug build (`-DCMAKE_BUILD_TYPE=debug`), while I was using release, and assert does not works there.
Ok, need to take a closer look.

>  jemalloc support on non-linux is EXPERIMENTAL

Don't bother about this.

>```
>nm ./programs/clickhouse | fgrep -c zone_register
>2
>```

Interesting, why two symbols, can you also post `nm ./programs/clickhouse | fgrep zone_register`?

**Comment by azat** [comment]
Eventually I figured it out, what was wrong, the fix is in #32219

**Pull request closed without merging**
