### PR TITLE
Adapt marks count for prefetch read pool

### PR DESCRIPTION
**Pull request by nickitat**
### Changelog category (leave one):
- Performance Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Simplify accounting of approximate size of granule in prefetched read pool.

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]
LGTM

**Review by kssenii — APPROVED** [review]

**Comment by kssenii** [comment]
> Integration tests (asan) [3/6] — fail: 1

test_backup_restore_on_cluster/test_disallow_concurrency.py::test_concurrent_restores_on_same_node

> Integration tests (release) [4/4] — fail: 1

test_version_update_after_mutation/test.py::test_mutate_and_upgrade
https://github.com/ClickHouse/ClickHouse/issues/44929

**Comment by alexey-milovidov** [comment]
What was wrong?

**Comment by nickitat** [comment]
> What was wrong?

pls check the linked issue

**Pull request merged**
