### PR TITLE
Do not spam logs with messages related to connection reset by peer

### LINKED ISSUE #34218: Error log full of ServerErrorHandler: Poco::Exception. Code: 1000, e.code() = 107, Net Exception: Socket is not connected
I've got the error log full of errors like this

```
2022.02.01 10:29:55.659210 [ 341370 ] {} <Error> ServerErrorHandler: Poco::Exception. Code: 1000, e.code() = 107, Net Exception: Socket is not connected, Stack trace (when copying this message, always include the lines below):

0. Poco::Net::NetException::NetException(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x16f242ec in /usr/bin/clickhouse
1. Poco::Net::SocketImpl::error(int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x16f36164 in /usr/bin/clickhouse
2. Poco::Net::SocketImpl::peerAddress() @ 0x16f38856 in /usr/bin/clickhouse
3. DB::ReadBufferFromPocoSocket::ReadBufferFromPocoSocket(Poco::Net::Socket&, unsigned long) @ 0x129c87b1 in /usr/bin/clickhouse
4. DB::HTTPServerRequest::HTTPServerRequest(std::__1::shared_ptr<DB::Context const>, DB::HTTPServerResponse&, Poco::Net::HTTPServerSession&) @ 0x13ff7147 in /usr/bin/clickhouse
5. DB::HTTPServerConnection::run() @ 0x13ff5b03 in /usr/bin/clickhouse
6. Poco::Net::TCPServerConnection::start() @ 0x16f3d6af in /usr/bin/clickhouse
7. Poco::Net::TCPServerDispatcher::run() @ 0x16f3fb01 in /usr/bin/clickhouse
8. Poco::PooledThread::run() @ 0x1704e889 in /usr/bin/clickhouse
9. Poco::ThreadImpl::runnableEntry(void*) @ 0x1704bf80 in /usr/bin/clickhouse
10. start_thread @ 0x8ea7 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
11. clone @ 0xfddef in /usr/lib/x86_64-linux-gnu/libc-2.31.so
 (version 21.12.3.32 (official build))
```

1. It's not really visible from the trace what kind of error this is. I have no idea where to look since I don't know what connection fails
2. Any idea what might it be? I have one MergeTree table and inserting into it over http interface. I've disabled clickhouse-keeper since I suspected that might have been the cause but it is not.

### PR DESCRIPTION
**Pull request by vdimir**
### Changelog category (leave one):

- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

* Decrease level of 'Socket is not connected' error when HTTP connection immediately reset by peer after connecting, close https://github.com/ClickHouse/ClickHouse/issues/34218

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Review by hanfei1991 — APPROVED** [review]

**Comment by robot-clickhouse-ci-2** [comment]
*This is an automated comment for commit 0e94132a174bc967b2e85f95853a0b5a20acf255 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/67177/0e94132a174bc967b2e85f95853a0b5a20acf255/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/66982/93a2dbf85c446cd5efa802dfe8fc99e2a82f394f/docs_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Comment by vdimir** [comment]
> Stateless tests (msan) [1/4] — fail: 2, passed: 1708, skipped: 24 [Details](https://s3.amazonaws.com/clickhouse-test-reports/67177/73e71e7b7a476c7073154a112dd12815bbe49bfe/stateless_tests__msan__[1_4].html)

https://github.com/ClickHouse/ClickHouse/issues/67216

> Stateless tests (msan) [2/4] — fail: 1, passed: 1717, skipped: 22 [Details](https://s3.amazonaws.com/clickhouse-test-reports/67177/73e71e7b7a476c7073154a112dd12815bbe49bfe/stateless_tests__msan__[2_4].html)

https://github.com/ClickHouse/ClickHouse/issues/67169

**Comment by vdimir** [comment]
> Upgrade check (debug) — Changed settings are not reflected in settings changes history (see changed_settings.txt)[Details](https://s3.amazonaws.com/clickhouse-test-reports/67177/22b170c920ae8129ff00169d31f5a5dbaeaec321/upgrade_check__debug_.html)

**Comment by vdimir** [comment]
> Integration tests (asan, old analyzer) [5/6] — fail: 4, passed: 611 [Details](https://s3.amazonaws.com/clickhouse-test-reports/67177/71a3fd36ed2c9b0ad4e32b4f42d3e165035ddb72/integration_tests__asan__old_analyzer__[5_6].html)

https://github.com/ClickHouse/ClickHouse/pull/67590

**Pull request merged**
