### PR TITLE
Allow comparison of numbers with constant string in IN and VALUES

### LINKED ISSUE #11630: RFC: automatic type cast of literals in obvious cases
```
select * from numbers(100) where number = '1';
```
literals can be casted to the column type. 

In general case there are too many side effects.

### PR DESCRIPTION
**Pull request by alexey-milovidov**
Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Allow comparison of numbers with constant string in comparison operators, IN and VALUES sections.

Detailed description / Documentation draft:
Also includes #11646. This does not fix #11630 because comparison for index is not covered by this PR.

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
Performance test Ok.

**Comment by filimonov** [comment]
> This does not fix #11630

But st-fixed label added and issue closed :)

**Comment by alexey-milovidov** [comment]
@filimonov 
Follow-up PR is also merged.

**Comment by qoega** [comment]
We should mention it in docs with examples

**Pull request merged**
