### PR TITLE
Performance check build AVX512

### PR DESCRIPTION
**Pull request by kitaisreal**
Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Check performance with AVX512 instructions enabled.

### CODE REVIEW

**Comment by kitaisreal** [comment]
@Mergifyio update

**Comment by kitaisreal** [comment]
@Mergifyio update

**Comment by Algunenano** [comment]
`01681_arg_min_max_if_fix` also fails under Aarch64 (https://github.com/ClickHouse/ClickHouse/issues/33716) so it might be related.

**Comment by kitaisreal** [comment]
@Mergifyio update

**Comment by kitaisreal** [comment]
@Mergifyio update

**Comment by kitaisreal** [comment]
@Mergifyio update

**Comment by kitaisreal** [comment]
@Mergifyio update

**Comment by kitaisreal** [comment]
@Mergifyio update

**Comment by kitaisreal** [comment]
@Mergifyio update

**Comment by tomtom215** [comment]
Hi all, any recent progress on enabling AVX512?

**Comment by alexey-milovidov** [comment]
@tomtom215 We are not going to enable AVX-512 with a global compiler flag.
In the meantime, we already use AVX-512 code in a few places where it is selected with dynamic dispatch, and we are searching for new places where to add AVX-512 optimizations.

**Comment by alexey-milovidov** [comment]
@kitaisreal reopen only if you will fix the conflict and update.

**Pull request closed without merging**
