### PR TITLE
Fix small map

### LINKED ISSUE #39158: SmallMapTable::operator[] looks weird
```cpp
class SmallMapTable : public SmallTable<Key, Cell, capacity>
{
public:
    ...
    mapped_type & ALWAYS_INLINE operator[](Key x)
    {
        typename SmallMapTable::iterator it;
        bool inserted;
        this->emplace(x, it, inserted);
        new (&it->getMapped()) mapped_type();
        return it->getMapped();
    }
};
```
**Maybe it should be like this?**

```cpp
mapped_type & ALWAYS_INLINE operator[](Key x)
{
        ...
        if (inserted)
            new (&it->getMapped()) mapped_type();
        ...
}
```

### PR DESCRIPTION
**Pull request by lokax**
Signed-off-by: lokax <m632656684@gmail.com>

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Fixes #39158 

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Review by evillique — APPROVED** [review]

**Comment by tavplubix** [comment]
Does the issue affect any queries? Is it possible to add a test?

**Comment by tavplubix** [comment]
> Does the issue affect any queries? Is it possible to add a test?

No, see  #39460

**Comment by lokax** [comment]
> > Does the issue affect any queries? Is it possible to add a test?
> 
> No, see #39460

You are going to remove `SmallHashMap`, right?

**Comment by tavplubix** [comment]
> You are going to remove `SmallHashMap`, right?

Yep

**Pull request closed without merging**
