### PR TITLE
Fix named collections on cluster 23.7

### LINKED ISSUE #51609: create named collection on cluster does not work
```sql
:) create named collection foo on cluster c1 AS user = 'user', password = 'password';

CREATE NAMED COLLECTION foo AS user = 'user', password = 'password'

Query id: e4824737-ce7a-4cd6-967a-c3795740794c

Ok.

0 rows in set. Elapsed: 0.004 sec.
```

`if exists` also has issue
```sql
:) drop named collection if exists foo on cluster c1;

DROP NAMED COLLECTION foo ON CLUSTER c1

Query id: e31007c7-48e9-4d13-b691-f12d14a90a3b

┌─host──────────────────────┬─port─┬─status─┬─error────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬─num_hosts_remaining─┬─num_hosts_active─┐
│ host1-1.s12222.mylocalnet │ 9000 │      0 │                                                                                                                                                          │                   1 │                0 │
│ host1-1.s12221.mylocalnet │ 9000 │    669 │ Code: 669. DB::Exception: Cannot remove collection `foo`, because it doesn't exist. (NAMED_COLLECTION_DOESNT_EXIST) (version 23.3.3.52 (official build)) │                   0 │                0 │
└───────────────────────────┴──────┴────────┴──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴─────────────────────┴──────────────────┘
↘ Progress: 0.00 rows, 0.00 B (0.00 rows/s., 0.00 B/s.)
2 rows in set. Elapsed: 0.131 sec.

Received exception from server (version 23.3.3):
Code: 669. DB::Exception: Received from localhost:9000. DB::Exception: There was an error on [host1-1.s12221.mylocalnet:9000]: Code: 669. DB::Exception: Cannot remove collection `foo`, because it doesn't exist. (NAMED_COLLECTION_DOESNT_EXIST) (version 23.3.3.52 (official build)). (NAMED_COLLECTION_DOESNT_EXIST)
```

if not exists also has issue
```sql
 :) create named collection if not exists foo on cluster c1 AS user = 'user', password = 'password';

Syntax error: failed at position 28 ('not'):

create named collection if not exists foo on c1 segmented AS user = 'user', password = 'password';

Expected one of: ON, AS
```

```sql
:) create named collection if not exists foo AS user = 'user', password = 'password';

Syntax error: failed at position 28 ('not'):

create named collection if not exists foo AS user = 'user', password = 'password';

Expected one of: ON, AS
```

### PR DESCRIPTION
**Pull request by alkorgun**
### Changelog category (leave one):

- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Fix named collections related statements: `if [not] exists`, `on cluster`. Closes #51609.

### Documentation entry for user-facing changes

- [x] Documentation is written (mandatory for new features)

### CODE REVIEW

**Comment by alkorgun** [comment]
I also had to fix 3 issues **unrelated to named collections** in order to build from current master:
- d6afa3de0150dfeaf2c346bf6f5080c095d73091
- bcc41fbc2f2f32a7187110583d8739b72a311856
- 5395d34fd719e5ff4b94a522ee42278dcc2acece

**Comment by alexey-milovidov** [comment]
@alkorgun, you are probably using an outdated compiler. We support clang-16 as a minimum version.

**Comment by robot-ch-test-poll2** [comment]
This is an automated comment for commit f026ccf11e2621c0c176ec5cbf7e786fe16c729d with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/52687/f026ccf11e2621c0c176ec5cbf7e786fe16c729d/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Comment by alkorgun** [comment]
> @alkorgun, you are probably using an outdated compiler. We support clang-16 as a minimum version.

Yes, that's true, on openSUSE Leap I have only clang-15. Because it builds just fine except those 3 issues, I didn't feel I really had to upgrade my setup. But if I would make further contributions, I'll absolutely do upgrade.

**Comment by alkorgun** [comment]
Style Check failure was just an errata in docs (_satements_->statements), but I made some other fixes.

# Current status

Works fine:

- `CREATE NAMED COLLECTION`
- `CREATE NAMED COLLECTION * ON CLUSTER`
- `CREATE NAMED COLLECTION IF NOT EXISTS * ON CLUSTER`
- `ALTER NAMED COLLECTION * SET`
- `ALTER NAMED COLLECTION * DELETE` — but I found another issue #52696
- `ALTER NAMED COLLECTION * ON CLUSTER`
- `ALTER NAMED COLLECTION IF EXISTS * ON CLUSTER`
- `DROP NAMED COLLECTION`
- `DROP NAMED COLLECTION * ON CLUSTER`
- `DROP NAMED COLLECTION IF EXISTS * ON CLUSTER`

Don't work:

- `ALTER NAMED COLLECTION * SET *, DELETE *` — it is intended by the original feature author to work. But I'm not sure if it is useful, so i didn't fix it

Test cases:

```sql
--- execute on the first node
create named collection foobar as a=1, b=2;
create named collection if not exists foobar on cluster '{sharded_cluster}' as a=1, b=2;
create named collection foobar_present_on_first as a=1, b=2;

--- execute on any other node
alter named collection foobar on cluster '{sharded_cluster}' set a=2;
alter named collection foobar on cluster '{sharded_cluster}' delete b;
alter named collection if exists foobar_absent on cluster '{sharded_cluster}' delete b;
alter named collection if exists foobar_present_on_first on cluster '{sharded_cluster}' delete b;

--- execute on every node
select * from system.named_collections;

--- execute on any node
drop named collection foobar on cluster '{sharded_cluster}';
drop named collection if exists foobar_absent on cluster '{sharded_cluster}';
```

**Comment by alkorgun** [comment]
> Bugfix validate check

I noticed this and I'll fix it soon. I had already figured out what to do, but I didn't have time for this.

**Review by CurtizJ — APPROVED** [review]

**Pull request merged**
