### PR TITLE
fix session expired while executing Tables

### PR DESCRIPTION
**Pull request by fuwhu**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
When there is some `ReplicatedMergeTree` tables whose zookeeper is expired, it will throw the error below when we select the meta data of some table from `system.tables` with `select_sequential_consistency` is enabled: `Session expired (Session expired): While executing Tables`.

In this PR, we improve ClickHouse by disabling select_sequential_consistency when getting total rows and total bytes in TableBlockSource::generate(), which avoids using zookeeper.

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
Let's simply obtain the number of rows/bytes always without `select_sequential_consistency`.

How to do it:
- you can copy the settings object;
- turn off `select_sequential_consistency`;
- use these settings in getTotalRows/Bytes.

**Comment by alexey-milovidov** [comment]
Also changed the category to "Improvement" as there is no bug.

**Comment by fuwhu** [comment]
> Let's simply obtain the number of rows/bytes always without `select_sequential_consistency` for system.tables.
> 
> How to do it:
> 
> * you can copy the settings object;
> * turn off `select_sequential_consistency`;
> * use these settings in getTotalRows/Bytes.

@alexey-milovidov 
Thanks Alexey for the suggestion.
Already updated as you suggested. Please help review again.

**Comment by alexey-milovidov** [comment]
`isExpiredReplicated`
Now this function is unneeded.

**Comment by fuwhu** [comment]
> isExpiredReplicated

@alexey-milovidov 
sorry, i don't get the point here.
The 'isExpiredReplicated' function here is for avoiding the usage of expired zookeeper object in ReplicatedMergeTree table, which will result in an exception "Session expired".

**Comment by alexey-milovidov** [comment]
But now we don't use ZooKeeper inside calls to getTotalRows/Bytes.

**Comment by alexey-milovidov** [comment]
@fuwhu Minor changes needed.

**Review by alexey-milovidov — APPROVED** [review]
LGTM

**Pull request merged**
