### PR TITLE
[WIP] Add DiskANN Index

### PR DESCRIPTION
**Pull request by JungleTryne**
### Changelog category (leave one):
- New Feature

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Add ANN index based on DiskANN.

TODO:

- [ ] Cross-compilation
- [ ] problems with libaio

### CODE REVIEW

**Comment by ucasfl** [comment]
Why this PR closed?

**Comment by alexey-milovidov** [comment]
Students graduated with an excellent grade.

**Comment by FArthur-cmd** [comment]
As far as I remember, there was an unresolved issue here with integration with openMP

**Comment by rschu1ze** [comment]
ClickHouse prefers static linking but that becomes a problem with OpenMP: https://stackoverflow.com/a/49452402/22422288. Also, having >1 execution framework in the same binary is generally a bad idea.

Anyways, if DiskANN can be built without OpenMP, then we could integrate it as alternative to 'hnsw' index type in the new vector similarity index (#63675). Further experiments are welcome.

**Pull request closed without merging**
