### PR TITLE
fix: Solve the unique invalid problem of negative interval

### PR DESCRIPTION
**Pull request by rgzntrade**
### Changelog category (leave one):

- Bug Fix (user-visible misbehavior in official stable or prestable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

- Fixed bug in `histogram` function accepting negative values.

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

```sql
create table histogram(num Int64) engine=Tinylog;
insert into histogram values(1);
insert into histogram values(1);
select histogram(2)(num) from histogram;
result: [(1,1,2)]

create table histogram(num Int64) engine=Tinylog;
insert into histogram values(-1);
insert into histogram values(-1);
select histogram(2)(num) from histogram;
result: [(-1,-1,1), (-1,-1,1)]

fix:
result: [(-1,-1,2)]
```

### CODE REVIEW

**Review by vdimir — COMMENTED** [review]
Thank you for your PR!

Could you please add test case into `tests/queries/0_stateless`? Check out https://clickhouse.com/docs/en/development/tests/#functional-tests or ask directly if you have any questions.

**Comment by rgzntrade** [comment]
> Thank you for your PR!
> 
> Could you please add test case into `tests/queries/0_stateless`? Check out https://clickhouse.com/docs/en/development/tests/#functional-tests or ask directly if you have any questions.

I added the corresponding test sql

**Comment by rgzntrade** [comment]
what should i do？

**Review by vdimir — APPROVED** [review]
Thank you for your effort!

Now CI is passed, couple of failures in integrations tests looks unrelated, I'll recheck and will merge

**Pull request merged**
