### PR TITLE
CreateQuery nested type column formatting fix

### LINKED ISSUE #16530: Less than perfect formatting of Nested data types.
```
CREATE TABLE nested
(
    `s` String,
    `x` Nested(    a String,     b UInt32)
)
ENGINE = MergeTree
ORDER BY s
```

Strange whitespaces before `a String` and `b UInt32`.

### PR DESCRIPTION
**Pull request by kitaisreal**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Fixes https://github.com/ClickHouse/ClickHouse/issues/16530

Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by alesapin** [comment]
Maybe you can add the `.sh` test? Just count whitespaces in clickhouse-client output?

**Comment by kitaisreal** [comment]
@alesapin okay, sure.

**Comment by alexey-milovidov** [comment]
@alesapin You mean clickhouse-format?

**Comment by alesapin** [comment]
> @alesapin You mean clickhouse-format?

Yes

**Comment by kitaisreal** [comment]
@alesapin added test

**Comment by alexey-milovidov** [comment]
Also the reference for the `01458_named_tuple_millin` test should be updated.

**Review by alexey-milovidov — APPROVED** [review]

**Review by alexey-milovidov — APPROVED** [review]
LGTM

**Comment by kitaisreal** [comment]
@alexey-milovidov ClickHouse build check phase is failed. Should I rebase with master to fix that ?

**Comment by alexey-milovidov** [comment]
@kitaisreal I have fixed this failure for you: https://github.com/ClickHouse/ClickHouse/pull/16586/commits/85ecc9ea104eb76581d4b3426a7609c3882ef8ad

**Pull request merged**
