### PR TITLE
test_merge_tree_s3 with lowcard

### PR DESCRIPTION
**Pull request by vdimir**
Changelog category (leave one):

- Not for changelog (changelog entry is not required)

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
...

Detailed description / Documentation draft:
...

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]
It's interesting, what was wrong.

**Comment by alexey-milovidov** [comment]
@mergifyio update

**Comment by vdimir** [comment]
@mergifyio update

**Comment by vdimir** [comment]
Now we don't have `Invalid version for SerializationLowCardinality key column` error, so issue is solved

**Pull request closed without merging**
