### PR TITLE
Changes to support the JIT in s390x

### PR DESCRIPTION
**Pull request by MeenaRenganathan22**
Changes to support the compiled expression support in s390x.

### Changelog category (leave one):
- Build/Testing/Packaging Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Changes to support the JIT in s390x

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by robot-clickhouse-ci-2** [comment]
This is an automated comment for commit 3d725f1653b796e43f8f3ddf0ded05db607df6bc with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/53423/3d725f1653b796e43f8f3ddf0ded05db607df6bc/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Comment by MeenaRenganathan22** [comment]
I see the following error in the s390x build.

s390x-binfmt-P: Could not open '/lib/ld64.so.1': No such file or directory

My local VM has the corresponding .so file. 
lrwxrwxrwx 1 root root 25 Jul 6 2022 /lib/ld64.so.1 -> s390x-linux-gnu/ld64.so.1

It looks like an environment issue. Any help on this would be much appreciated.

**Comment by zhanglistar** [comment]
@MeenaRenganathan22 Do you use JIT? Actually, most functions are not using JIT even the flag is open.

**Comment by MeenaRenganathan22** [comment]
> @MeenaRenganathan22 Do you use JIT? Actually, most functions are not using JIT even the flag is open.

This fix is to resolve the 02723_jit_aggregation_bug_48120 functional test failure in s390x. 

And, the functional test uses the compiled expression.

**Comment by alexey-milovidov** [comment]
`llvm-tblgen` as a build tool, has to be compiled for the host platform.
See also, `protoc`.

**Comment by ltrk2** [comment]
I think we can close this one because #38217 already implements this.

**Pull request closed without merging**
