### PR TITLE
Revert "[Green CI] Fix test test_storage_s3_queue/test.py::test_max_set_age "

### PR DESCRIPTION
**Pull request by tavplubix**
Reverts ClickHouse/ClickHouse#67035

cc: @pamarcos

### CODE REVIEW

**Comment by robot-ch-test-poll1** [comment]
*This is an automated comment for commit 3ebb38422a41bba923f7c39f3cf1adb140f72382 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/67568/3ebb38422a41bba923f7c39f3cf1adb140f72382/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Builds</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/67566/0e36db543762cb146aa6c233d4536fd62c6101b2/builds/report.html">✅ success</a></td></tr>
<tr><td>Fast test</td><td>Normally this is the first check that is ran for a PR. It builds ClickHouse and runs most of <a href="https://clickhouse.com/docs/en/development/tests#functional-tests">stateless functional tests</a>, omitting some. If it fails, further checks are not started until it is fixed. Look at the report to see which tests fail, then reproduce the failure locally as described <a href="https://clickhouse.com/docs/en/development/tests#functional-test-locally">here</a></td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/a38c2e558b78d8f35a90e328e44a6358765a7357/fast_test.html">✅ success</a></td></tr>
<tr><td>Flaky tests</td><td>Checks if new added or modified tests are flaky by running them repeatedly, in parallel, with more randomization. Functional tests are run 100 times with address sanitizer, and additional randomization of thread scheduling. Integration tests are run up to 10 times. If at least once a new test has failed, or was too long, this check will be red. We don't allow flaky tests, read <a href="https://clickhouse.com/blog/decorating-a-christmas-tree-with-the-help-of-flaky-tests/">the doc</a></td><td>✅ success</td></tr>
<tr><td>Unit tests</td><td>Runs the unit tests for different release types</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/a38c2e558b78d8f35a90e328e44a6358765a7357/unit_tests__release_.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Comment by pamarcos** [comment]
Can we revert just the lines that cause the test to fail? https://github.com/ClickHouse/ClickHouse/pull/67590
The changes to the `test_storage_s3_queue/test.py::test_max_set_age` are not the ones to blame.

**Comment by pamarcos** [comment]
I've ended up fixing the test so that we can keep executing the tests in parallel: https://github.com/ClickHouse/ClickHouse/pull/67590/commits/da3a37c561679daaecbcdece74f92ce98380b2b5

**Comment by tavplubix** [comment]
Closed in favor of https://github.com/ClickHouse/ClickHouse/pull/67590

**Pull request closed without merging**
