### PR TITLE
Slightly optimize very short queries with LowCardinality

### LINKED ISSUE #13864: Performance degradation between 20.1 and 20.3 for large number of very short queries with LowCardinality fields
Schema
```
ATTACH TABLE default.test (`col1` UUID, `col2` LowCardinality(String)) ENGINE = MergeTree ORDER BY (col1, col2) SETTINGS index_granularity = 128;
```

Data sample: https://www.dropbox.com/s/untu96ad69a2thl/test_data.tar.gz?dl=0

Query:
```
echo "SELECT col1, col2 FROM test PREWHERE col1 = '042fecec-ea68-1b26-00a4-a4f3b3987574'" | clickhouse-benchmark -c 1 -i 2000 -d 0 
```

Results - look on QPS metric:

```
### 20.1.16.120
Loaded 1 queries.

Queries executed: 2000.

localhost:9000, queries 2000, QPS: 597.941, RPS: 76536.485, MiB/s: 1.168, result RPS: 0.000, result MiB/s: 0.000.

0.000%		0.001 sec.	
10.000%		0.001 sec.	
20.000%		0.002 sec.	
30.000%		0.002 sec.	
40.000%		0.002 sec.	
50.000%		0.002 sec.	
60.000%		0.002 sec.	
70.000%		0.002 sec.	
80.000%		0.002 sec.	
90.000%		0.002 sec.	
95.000%		0.002 sec.	
99.000%		0.002 sec.	
99.900%		0.003 sec.	
99.990%		0.015 sec.
### 20.3.2.1

Loaded 1 queries.

Queries executed: 2000.

localhost:9000, queries 2000, QPS: 322.157, RPS: 41236.084, MiB/s: 0.629, result RPS: 0.000, result MiB/s: 0.000.

0.000%		0.001 sec.	
10.000%		0.003 sec.	
20.000%		0.003 sec.	
30.000%		0.003 sec.	
40.000%		0.003 sec.	
50.000%		0.003 sec.	
60.000%		0.003 sec.	
70.000%		0.003 sec.	
80.000%		0.003 sec.	
90.000%		0.003 sec.	
95.000%		0.004 sec.	
99.000%		0.004 sec.	
99.900%		0.016 sec.	
99.990%		0.017 sec.

## 20.6.3.28

Loaded 1 queries.

Queries executed: 2000.

localhost:9000, queries 2000, QPS: 308.133, RPS: 39441.007, MiB/s: 0.602, result RPS: 0.000, result MiB/s: 0.000.

0.000%		0.001 sec.	
10.000%		0.002 sec.	
20.000%		0.003 sec.	
30.000%		0.003 sec.	
40.000%		0.003 sec.	
50.000%		0.003 sec.	
60.000%		0.003 sec.	
70.000%		0.003 sec.	
80.000%		0.004 sec.	
90.000%		0.004 sec.	
95.000%		0.004 sec.	
99.000%		0.004 sec.	
99.900%		0.016 sec.	
99.990%		0.017 sec.
```

Bisecting on releases: 
v20.2.1.2442-testing (21-Feb-2020 18:15) - last good
v20.3.1.2495-testing (26-Feb-2020 18:27) - first bad

ps. experimental_use_processors don't change the situation.

### PR DESCRIPTION
**Pull request by CurtizJ**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Performance Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Slightly optimize very short queries with LowCardinality.

Resolves #13864.

### CODE REVIEW

**Comment by CurtizJ** [comment]
Look at QPS.
Before:
```
echo "SELECT col1, col2 FROM test PREWHERE col1 = '042fecec-ea68-1b26-00a4-a4f3b3987574'" | clickhouse-benchmark -c 1 -i 2000 -d 0 
Loaded 1 queries.

Queries executed: 2000.

localhost:9000, queries 2000, QPS: 735.422, RPS: 94134.037, MiB/s: 1.436, result RPS: 0.000, result MiB/s: 0.000.

0.000%		0.001 sec.	
10.000%		0.001 sec.	
20.000%		0.001 sec.	
30.000%		0.001 sec.	
40.000%		0.001 sec.	
50.000%		0.001 sec.	
60.000%		0.001 sec.	
70.000%		0.001 sec.	
80.000%		0.002 sec.	
90.000%		0.002 sec.	
95.000%		0.002 sec.	
99.000%		0.002 sec.	
99.900%		0.004 sec.	
99.990%		0.011 sec.	
```

After:
```
echo "SELECT col1, col2 FROM test PREWHERE col1 = '042fecec-ea68-1b26-00a4-a4f3b3987574'" | clickhouse-benchmark -c 1 -i 2000 -d 0 
Loaded 1 queries.

Queries executed: 2000.

localhost:9000, queries 2000, QPS: 1030.173, RPS: 131862.092, MiB/s: 2.012, result RPS: 0.000, result MiB/s: 0.000.

0.000%		0.001 sec.	
10.000%		0.001 sec.	
20.000%		0.001 sec.	
30.000%		0.001 sec.	
40.000%		0.001 sec.	
50.000%		0.001 sec.	
60.000%		0.001 sec.	
70.000%		0.001 sec.	
80.000%		0.001 sec.	
90.000%		0.001 sec.	
95.000%		0.001 sec.	
99.000%		0.002 sec.	
99.900%		0.003 sec.	
99.990%		0.009 sec.
```

**Comment by CurtizJ** [comment]
Currently it's impossible to add performance test for such short queries.

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
I've read the fix but I don't understand how it's related to LowCardinality.

**Comment by fastest963** [comment]
@CurtizJ looking forward to this! After your change, is there still a difference with `experimental_use_processors`?

**Comment by CurtizJ** [comment]
> I've read the fix but I don't understand how it's related to LowCardinality

The problem appeared, when we read dictionary of low cardinality. Since it has low size, a lot of marks point to one place, and previously we a lot of time was spent in loop, while trying to find mark to next compressed block.

**Comment by CurtizJ** [comment]
> After your change, is there still a difference with experimental_use_processors?

I can't check it now, because in new versions old code is already removed and `experimental_use_processors` is exists just for backward compatibility and does nothing.

**Pull request merged**
