### PR TITLE
Fixed open behavior of remote host filter in case when there is `remote_url_allow_hosts` section in configuration but no entries there

### PR DESCRIPTION
**Pull request by excitoon**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Fixed open behavior of remote host filter in case when there is `remote_url_allow_hosts` section in configuration but no entries there. :warning: please add a note about potential issue when upgrading - @alexey-milovidov 

From documentation: `If this section is not present in configuration, all hosts are allowed`, real behavior was `If section contains no entries, all hosts are allowed`.

**There is a potential problem with this PR, by default configuration file does contain specified tag, empty, so if a user has their custom edited configuration, it may effectively block access to all external URLs for him after an upgrade.**

### CODE REVIEW

**Comment by excitoon** [comment]
There is a potential problem with this PR, by default configuration file does contain specified tag, so if a user has their custom edited configuration, it may effectively block access to all external URLs for him after an upgrade.

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
Ok. I add "no backport" tag to avoid surprises in patch releases.

> if a user has their custom edited configuration

For new versions it's ok if we put a note in the changelog.

**Comment by aberrier** [comment]
This is actually an undocumented breaking change.
Updating from `21.3.2.5` to `21.4.3.21`, breaks all objects (dictionnaries, avro_schema_registry_url, ...) using external URLs because of the previously generated configuration with empty value on `remote_url_allow_hosts`: `</remote_url_allow_hosts><remote_url_allow_hosts>` 
This is probably worth adding a warning on this configuration to avoid potential breaking upgrades.
What do you think ?

**Comment by alexey-milovidov** [comment]
Ok, let's add a warning.

PS. But why do you have empty `<remote_url_allow_hosts></remote_url_allow_hosts>`?

**Comment by alexey-milovidov** [comment]
https://github.com/ClickHouse/ClickHouse/commit/0fca2acbdd1dc4668eb8f52d3120ae6c5f840096#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4ed

**Comment by excitoon** [comment]
Probably that's because of editing main configuration file.

Didn't we add any warning? Actually it is exactly the case I wrote about.

**Comment by aberrier** [comment]
> PS. But why do you have empty `<remote_url_allow_hosts></remote_url_allow_hosts>`?

Like @excitoon said :
> From documentation: `If this section is not present in configuration, all hosts are allowed`, real behavior was `If section contains no entries, all hosts are allowed`.

I believe in that time, we came to the same conclusion as we wanted all hosts to be allowed.

**Pull request merged**
